### ISSUE TITLE
[Bug]: URL Slugs that partially matches a Document path gives 404

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#10005]
### Expected behavior

Any published Data Object with a URL Slug should be reachable

### Actual behavior

Any time a part of the URL Slug matches a full path of an unpublished Document page, the URL Slug will return a 404.

### Steps to reproduce

1. Create a URL Slug on a data object, .e.g. `/a/b/c/123`
2. Create a Document page structure like with a Pretty URL like `/a/b/c`
3. Save, and unpublish the page `c`
4. Visit  `/a/b/c/123` on the front end.

Result: 404

**Comment by brusch** [comment]
Fix is already in #10116 (was not merged because because it's a breaking change - keeping it open wouldn't work because of the target branch).

**Comment by NiklasBr** [comment]
I think this is incorrect reasoning @brusch. It's not prudent to use semver as a kind of shield just to avoid fixing a bug which introduced incorrect behaviour. By their very nature *all bugfixes* changes behaviour, otherwise nothing can be fixed. Especially as the unfixed behaviour has security implications which should not be left unfixed.

**Comment by brusch** [comment]
Well, if this change would break the setup of an important client of you where then confidential data get's exposed, you'd probably see it different 😉
The thing is ... even if we classify it as a bug, it has been always there and was not introduced with new functionality or bug fixes, so someone might rely on that behavior. 

Personally I don't care 🤷‍♂️ - semver (or in general safe upgrades) was requested by the community (#4647), we try our best to make you guys happy 😉

**Comment by NiklasBr** [comment]
SemVer *specifically* provides means to make fixes to incorrectly implemented API:s, so I don't see why that is an issue to begin with. The *current, unfixed* bug is probably classified as `Medium4 - 6.95.2 CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:C/C:L/I:N/A:L` from what I can tell in the report.

**Comment by brusch** [comment]
Yep, I know,  that's why I wrote "safe upgrades" 😉 From a Semver point of view, this fix is probably fine. 

As I said, I personally don't mind, but I'm also aware of the past and that told me a different story 😉

Please feel free to continue the discussion,  if the majority of the community thinks this patch is fine, I'm also fine with that (but don't blame it on the Pimcore crew later on 😉).

**Comment by dpfaffenbauer** [comment]
I would be careful with such changes. It might just be a small bug-fix, but it definitely is one you would oversee on upgrades. maybe some sort of feature switch or configuration might solve it.

**Comment by NiklasBr** [comment]
@brusch I will wrap up more info the security issues with the current solution before I go any further (will send an email), and as a tangent, things like this would be *so much* easier to have a discussion about if the intended behaviour was documented.

**Comment by EqualString** [comment]
@brusch I think that the @dpfaffenbauer solution with configuration could work just fine. What if we leave default behavior as it is, but we make an optional config.yaml param which "turns" @dturopoli  #10116 fix on?

**Comment by brusch** [comment]
@EqualString would be fine for me. Additionally I'd trigger a deprecation message in case the old behavior get's triggered (incl. upgrade note in docs).

**Comment by EqualString** [comment]
@brusch new fix is applied here #10163 , can you check it? Also, what exactly do you mean by "triggering deprecation message" since "new" (fixed) slug behaviour can be switched on by configuration in .yaml, while we left "old" behaviour by default?

**Comment by brusch** [comment]
@EqualString Thanks a lot! 
I'd change the default behavior with the next major release and remove the config switch again. So for that we'd need to trigger a deprecation message in case you're accessing the "old" behavior, so that someone gets aware of the upcoming change in Pimcore 11. Can you please add that to  #10163  Thanks a lot!

**Comment by EqualString** [comment]
@brusch Deprecation message added to #10163, can you check it now?
