### ISSUE TITLE
[Bug][SharedTranslations][AdminTranslations]: Languages of filter results are not consolidated

### ISSUE THREAD

**Issue by rberneder** [pimcore/pimcore#10004]
### Expected behavior

Expecting we have a translation key "back". This key is translated to "back" in EN and "zurück" in DE. When searching for "zurück" the whole translation key with all its translation messages shall appear.

### Actual behavior

If a string is searched that only exists in one/some translated languages, the result shows the translation key with only the translations that match the searched string. All other languages stay empty, also if they are translated as well.

### Steps to reproduce

* Create a translation key "back".
* Translate it to "zurück" (DE) and "back" (EN).
* Search for "zurück".

You will see the translation key with an empty translation cell for EN.

**Comment by brusch** [comment]
Fixed by #10013

**Comment by rberneder** [comment]
Unfortunately there is still a similar issue when sorting for a translation-column (e.g. German) @dvesh3 & @brusch.
If you list all translation keys in the demo installation, and sort them by German, all other language translations disappear.
Should I write a new issue for that?
