### ISSUE TITLE
[Bug]: Pimcore X (10.0.1) Object: CRM Consent-Type not visible because of CSS-Class 

### ISSUE THREAD

**Issue by lisaPolena** [pimcore/pimcore#10006]
### Expected behavior

Expected to see the Consent Checkbox (with the Label "Consent given for field" with the Fieldname, Date and Time.)

![image](https://user-images.githubusercontent.com/88780000/129039090-1d032c02-5a88-421e-80aa-d2f6d0b6c8f9.png)

or 

![image](https://user-images.githubusercontent.com/88780000/129039822-371d0383-3920-470b-ae3e-0afeebea7f96.png)

### Actual behavior

The Checkbox and the Label isn't visible because of this CSS: 

.x-box-layout-ct {
    overflow: hidden;
}

[CSS File](https://github.com/pimcore/pimcore/blob/a4bc3905900cbb09e00c0e519489e6c7750c9ea5/bundles/AdminBundle/Resources/public/extjs/css/PimcoreApp-all_1.css#L1724)

![image](https://user-images.githubusercontent.com/88780000/129039363-20096fb3-de5c-4f2a-a30a-f0bcf011bcb9.png)

### Steps to reproduce

1. Open Demo-Project 
2. Add a new Panel and a new Consent in the Customer Class 

![image](https://user-images.githubusercontent.com/88780000/129040241-bc6c194b-ac30-468b-843d-806359c4b071.png)

3. Open an Customer --> Consent Tab --> no Checkbox visible 
4. if you edit the CSS and delete the CSS-Class, you'll see the Checkbox

**Comment by weisswurstkanone** [comment]
@lisaMariaX could you provide a PR please ?

**Comment by mcop1** [comment]
See follow up issue #10297 10297

**Comment by mcop1** [comment]
Fixed by PR #10006
