### ISSUE TITLE
CSV/XLS export. Align default split button behavior

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#10057]
### Expected behavior

Default export option should be the same.

### Actual behavior

In the asset list view the default is xlsx export, in the dataobject export it is csv which is not consistent.

![image](https://user-images.githubusercontent.com/6142086/129727665-bcf958cb-c659-4f57-bc69-27eff4fe0cff.png)

vs.

![image](https://user-images.githubusercontent.com/6142086/129727760-57af51fc-401c-42f6-a040-8fc0d9088f18.png)

### Steps to reproduce

Open object and asset grid view and compare.

**Comment by dvesh3** [comment]
Fixed by #10240
