### ISSUE TITLE
Corrupt cache unter certain circumstances 

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#1005]
To reproduce the bug:

* Create class with DateTime field (startdate).
* Clear the cache
* In code do this:
* $object = Object::getById(666); // just an example
* $dt = $object->getStartdate(); // get get a REFERENCE to the startdate here
* $dt->add(new \DateInterval('P1D')); // we change the startdate of the object because we chage the reference
* // we never save the changed object
* Now the object with the altered (but not saved!) start date gets cached!

see also https://github.com/pimcore/pimcore/pull/997

**Comment by brusch** [comment]
Create a clone using https://packagist.org/packages/myclabs/deep-copy should do the trick.

**Comment by brusch** [comment]
DeepcCopy causes major performance issues, see #1061
