### ISSUE TITLE
Failed to create a new data object if class has password field with min length attribute

### ISSUE THREAD

**Issue by MyZik** [pimcore/pimcore#10050]
### Expected behavior

The object must be created

### Actual behavior

If we create the class with a password field and this password field has the min length attribute, an exception will be thrown

### Steps to reproduce

1. Create a new DataObject class (e.g. `TestUser`)
2. Add a password field and set the min length attribute value (e.g. 12)
3. Save and try to create the data object `TestUser`

data object class:
<img width="1300" alt="Bildschirmfoto 2021-08-16 um 15 38 21" src="https://user-images.githubusercontent.com/12817320/129573347-bcc824c3-41ac-4acc-b420-d16a81735ea0.png">

tried to create a new object:
<img width="1001" alt="Bildschirmfoto 2021-08-16 um 15 38 41" src="https://user-images.githubusercontent.com/12817320/129573397-a8887c5d-2ba3-4439-a10a-100beff7457a.png">

**Comment by dvesh3** [comment]
Fixed by #10053
