### ISSUE TITLE
[Improvement] Improve document editable so they keep better the front end style for inline element

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1006]
Using editable in document on the Pimcore edit tab, the editable area use "div" tag.
`<div id="pimcore_editable_headDescription" class="pimcore_editable pimcore_tag_input" style="min-height: 20px;" contenteditable="true">`

It prevent use it inside inline element (span, p, ...). If you do this:
`<p class="mycss"><?= $this->input("myInput) ?></p>`
The browser (Firefox last version Windows) will render:
```
<p class="myCssStyle"> (javascript goes here ) </p>
<div id="pimcore_editable_headDescription" class="pimcore_editable pimcore_tag_input" style="min-height: 20px;" contenteditable="true">... </div>
```
And we loose the css style applied on p.

In fact, the browser made automatical correction to the HTML, which is ok (a div cannot be on a inline element), but as Pimcore use DIV, sometimes editable loose the styles.

Solution:
1- 
Maybe it could be changed to (changing to span and add display block style):
`<span id="pimcore_editable_headDescription" class="pimcore_editable pimcore_tag_input" style="min-height: 20px; display: block;" contenteditable="true">`

Same could be done for some other editable (textarea, if used inside a p), etc.

2-
Or another solution is to provide a parameter to the editable to set div or span (but i think 1st solution is nicer because it is automatic).

**Comment by Yivan** [comment]
@brusch 
Can i make a pull request on this based on the first solution : changing generated `<div...` to a `<span style=display: block;...` ?

**Comment by brusch** [comment]
@Yivan I guess this change needs a lot of testing, I wouldn't just change it, because this might break a lot of existing installations.

**Comment by Yivan** [comment]
Thanks for your return.
Ok I understand perfectly.

Is there an existing hook/event we could use to change the DIV in SPAN using a backend plugin ? It seems tricky.

Another more proper way is to provide a configuration parameter to define the surrounding tag (by default "div"). So developper on case of P could configuring the surrounding to SPAN tag.
Exemple:
<p class="mycss"><?= $this->input("myInput, array("surroundingTag" => "span")) ?></p>

It will keep backward compatibily and leave the possibility to use inline element.
If you find this solution good, i can make a PR for input tag. Do you think i make it for others editable (i think of: textarea, wysiwyg and image, but maybe others) ?

**Comment by solverat** [comment]
With that we should get rid of the copy & paste problem (https://github.com/pimcore/pimcore/issues/559). Maybe it's time for refactoring and a good migration script. At least we should pay much more attention to this topic in general. 

With each project we have to explain to our customers "yes, there is a copy & paste element, but you can't use it." - very disappointing. To prevent backwarts compatibility forever can't be the solution...

**Comment by brusch** [comment]
@solverat this topic is not related to #559 in any way, sorry ;)

**Comment by brusch** [comment]
Introduce new global config option `editmodeWrappingTag` that can be set to a different HTML tag.
Add a getter to Document/Tag.php with `<div>` as default. 

Needs to be considered here: 
models/Document/Tag.php:138
models/Document/Tag/Area.php:61
models/Document/Tag/Embed.php:104
models/Document/Tag/Video.php:252

+ Documentation

**Comment by brusch** [comment]
Let's see if this is also a topic for others - if we collect some votes, we're going to implement this.

**Comment by fashxp** [comment]
closed due to inactivity

**Comment by seybsen** [comment]
Where to vote for this feature?
