### ISSUE TITLE
[Bug]: v10.0.9 => v10.1.0: Asset:getById Exception (data cache problem)

### ISSUE THREAD

**Issue by akno77** [pimcore/pimcore#10077]
### Expected behavior

`pimcore/lib/Cache/Core/CoreCacheHandler::load()` returns object

### Actual behavior

`pimcore/lib/Cache/Core/CoreCacheHandler::load()` returns string:

`O:26:"Pimcore\Model\Asset\Folder":20:{s:7:"*type";s:6:"folder";s:5:"*id";i:1;s:11:"*parentId";i:0;s:11:"*filename";s:0:"";s:7:"*path";s:1:"/";s:11:"*mimetype";N;s:15:"*creationDate";i:1608725592;s:19:"*modificationDate";i:1608725592;s:12:"*userOwner";i:1;s:19:"*userModification";i:1;s:11:"*metadata";a:0:{}s:9:"*locked";N;s:17:"*customSettings";a:0:{}s:14:"*hasMetaData";b:0;s:11:"*siblings";N;s:14:"*hasSiblings";N;s:15:"*_dataChanged";b:0;s:15:"*versionCount";i:0;s:25:"*__dataVersionTimestamp";i:1608725592;s:12:"*_fulldump";b:0;}`

I found out that the load() method changed from v10.0.9 => v10.1.0:

`$data = unserialize($data);`

was removed! So this cannot work...

### Steps to reproduce

Update to Pimcore v10.1.0.

I updated v10.0.9 => v10.1.1 and got an excpetion in the admin interface when calling the URL http://localhost/admin/asset/tree-get-root?_dc=1629292560809&id=1&view=&elementType=asset:

**Pimcore\Model\Asset::typeMatch(): Argument #1 ($asset) must be of type Pimcore\Model\Asset, string given, called in /var/www/html/vendor/pimcore/pimcore/models/Asset.php on line 324**

I wonder why it works in the demo.pimcore.com with Version v10.1.0....

**Comment by akno77** [comment]
See also my initial discussion post: #10075

**Comment by brusch** [comment]
Obviously there's a step missing in the upgrade guide, just added it in #10078

**Comment by akno77** [comment]
@brusch I alreday cleared all caches multiple times with the same result. Are you sure the missing `$data = unserialize($data);` is correct?

**Comment by brusch** [comment]
@akno77 yes, because serialization is now completely handled by Symfony Cache, see #9227 (both serialize() and unserialize() we're removed).

**Comment by akno77** [comment]
@brusch It is very strange... If I clear "All Caches (Symfony + Data)" via the CMS and reload the CMS I get the Exception. If I clea the cache and call the URL which causes the Exception (http://localhost/admin/asset/tree-get-root?_dc=1629292560809&id=1&view=&elementType=asset) I get the correct JSON response. And If I reload the CMS afterwards everything works correct.

If I then again clear  "All Caches (Symfony + Data)" and reload the CMS I get the Exception again! I have no idea why...

If I just clear the Cache via command line "pimcore:cache:clear" + "cache:clear" I get the Exception all the time. So it makes a difference If I clear it via the CMS link.

**Comment by akno77** [comment]
@brusch I think it has sth. do with our infrastructure and shared db between dev/int server. I couldn't verify it final because I got to another problem when deployen to the int server which is similar to the #9991 bug...

**Comment by brusch** [comment]
@akno77 ok, thanks for the feedback - I'd suggest to not use the default doctrine caching adapter, but redis instead 😉
