### ISSUE TITLE
   ERROR Composer is not installed properly!  Please ensure that composer is in your PATH variable.

### ISSUE THREAD

**Issue by to-bee** [pimcore/pimcore#1007]
### Expected behavior 
Pimcore should update or give a message that no update is available

### Actual behavior  
 After updating pimcore from 3.9 to 4.3 / chroot installation in /home/user/domainname
 After updating pimcore from 4.0 to 4.3  / installed at /var/www/domainname:

Pimcore Update is no more working it says composer is not installed
I installed the composer in several locations: /usr/local/bin, /home/user/, /home/user/domainname, /var/www/domainname

I added SetEnv to my virtual host:
SetEnv composer /usr/local/bin/composer
SetEnv COMPOSER_HOME /usr/local

and added a composer alias in my php.ini:
alias composer='php -n /usr/local/bin/composer'

composer owner is www-data 
Versions: apache 2.4, php 5.6

The composer was working perfectly until updating to pimcore 4.3 so I'm sure my composer installation is correct 

### Steps to reproduce  
shell: Can delete the vendor folder and run composer update command within my document root  
vendor folder is recreated, no warning, no error

I also tried this workaround
https://groups.google.com/forum/#!msg/pimcore/sBxs60mdF78/7IVvNE0pAAAJ

**Comment by brusch** [comment]
Sorry, I'm unable to reproduce the problem. 
Please provide us more information on how to reproduce the problem or even better a PR that fixes the problem. 

May the following infos can help you to debug the problem: 
- Are the contents of `Pimcore\Update` identical to https://github.com/pimcore/pimcore/blob/b98bef1620ab930eccf1e5ee0fab18042b49ea11/pimcore/lib/Pimcore/Update.php ? 
- Enable your debugger an step through 
https://github.com/pimcore/pimcore/blob/1425a7ceb7e77d90e94a455158374f3220fc9d74/pimcore/lib/Pimcore/Tool/Console.php#L64-L64 
  - What is the output of $process->run(); (check with `$process->getOutput()`  and `$process->getErrorOutput()`
- If you put a breakpoint at this line: 
https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Tool/Console.php#L137-137 what happens there? Is Pimcore entering this function? 
...

So all the "magic" happens at this 2 functions, you should be able to figure out the actual problem there. 

Thanks!

**Comment by to-bee** [comment]
Hi

Thanks for your help:
Update.php is the same. Yesterday I set up a new pimcore with composer and
I got the same composer error after the installation.


I just added some syslog message because I don't have a debugger set up:

*Line 64*

[image: Inline image 6]

[image: Inline image 5]



*Line 137*
Permissions for /var/www/.../website/var/composer are set to
777/www-data:www-data so it should work
I Added the file composer manually into /var/www/.../website/var/composer
directory. Should it be added automatically?

[image: Inline image 2]

[image: Inline image 1]

Kind regards

Tobias








www.wallscrapers.ch

Tobias Ernst
Tüftelstrasse 53
5322 Koblenz
079 325 96 40

**Comment by to-bee** [comment]
Hi

I made some further investigations:

[image: Inline image 1]

is empty

I also added path variable in system settings:
[image: Inline image 4]



new Process didn't enter because $paths is empty

[image: Inline image 3]




Kind regards and thanks

Tobias








www.wallscrapers.ch

Tobias Ernst
Tüftelstrasse 53
5322 Koblenz
079 325 96 40

---------- Forwarded message ----------
From: Tobias Ernst <info@tobias-ernst.ch>
Date: Wed, Nov 2, 2016 at 9:08 AM
Subject: Re: [pimcore/pimcore] ERROR Composer is not installed properly!
Please ensure that composer is in your PATH variable. (#1007)
To: pimcore/pimcore <
reply@reply.github.com
>


Hi

Thanks for your help:
Update.php is the same. Yesterday I set up a new pimcore with composer and
I got the same composer error after the installation.


I just added some syslog message because I don't have a debugger set up:

*Line 64*

[image: Inline image 6]

[image: Inline image 5]



*Line 137*
Permissions for /var/www/.../website/var/composer are set to
777/www-data:www-data so it should work
I Added the file composer manually into /var/www/.../website/var/composer
directory. Should it be added automatically?

[image: Inline image 2]

[image: Inline image 1]

Kind regards

Tobias








www.wallscrapers.ch

Tobias Ernst
Tüftelstrasse 53
5322 Koblenz
079 325 96 40

**Comment by to-bee** [comment]
The output of $process->getOutput() was:
The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly  
My current composer version installed: 1.2.1

The problem could be solved:

Install composer.phar to the folder [your document root]/website/var/composer
cd [your document root]/website/var/
chown -R www-data:www-data composer (maybe you also have to set chmod)
cd composer/
mv composer.phar composer

downgrade composer from 1.2.1 to 1.0.0:
composerself-update 1.0.0-alpha11

pimcore will create[your document root]/website/var/composer/composer anytime if no path variable is set. So your downgraded version will be deleted if you don't set a path variable:
Pimcore -> Settings -> System Settings -> General -> Add path variable:
[your document root]/website/var/composer

More informations:
This is not a pimcore issue but a composer bug
https://github.com/composer/composer/issues/4789

**Comment by brusch** [comment]
@to-bee Thanks for your feedback!

**Comment by dctmc** [comment]
still not works for me (

**Comment by brusch** [comment]
@dctmc not really :( can you try to further debug this? Thanks!

**Comment by dctmc** [comment]
Was done following:
- manual installation of composer 1.0.0-alpha11 to /website/var/composer 
- adding path in Pimcore -> Settings -> System Settings -> General -> Add path variable to WEB-HOME/website/var/composer 
- changes in Pimcore\Lib\Pimcore\Update.php 
 line 405 - $composerPath = \Pimcore\Tool\Console::getExecutable("composer**.phar**");
 line 424 - return (bool) \Pimcore\Tool\Console::getExecutable("composer**.phar**");

starts working but at the end get error
<img width="760" alt="2016-12-19 17 13 09" src="https://cloud.githubusercontent.com/assets/17833150/21317937/40b6b8b6-c618-11e6-8c10-c2f6d19d007a.png">

**Comment by brusch** [comment]
Pimcore requires Composer to be installed as 'composer' and not 'composer.phar' (because composer.phar needs a preceding 'php' , which isn't added by Pimcore). 
Please follow the following guide to install composer properly: 
https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx

**Comment by markus-moser** [comment]
Just an idea: I think an event in the \Pimcore\Tool\Console::getExecutable() method would be nice. I know Pimcore isn't made for shared hosts. But the only reason why it didn't work for me on a shared host was the composer part. It worked perfectly with php composer.phar - but I needed to hack the core to do it like this. ;-)

**Comment by dctmc** [comment]
Thank to all! get it work after manually run 'composer update nothing' in WEB_HOME directory.. error was just during update from 4.1.0 to 4.1.1 ... in my case composer was latest version, installed as 'composer' in WEB-HOME/website/var/composer.. problem was in additional packages which was not installed after update 4.1.0. to 4.1.1 .. and was downloaded and installed during manual composer run .. after this all next updates from 4.1.1 to 4.4.1 runs fine

**Comment by brusch** [comment]
@markus-moser It's now possible to customize all the paths to external programs using DI, see: 
https://github.com/pimcore/pimcore/blob/22fbf473419bdcd89db73d34d71a321e8e822010/website_example/config/di.example.php#L25-L25

**Comment by bbak** [comment]
Question: What happens, if a executable is not set? I assume Pimcore again searches for it.
Use-Case: I'm very happy with just using zopfipng, and therefore I don't want Pimcore to search for (and use) advpng, pngout, pngcrush. Can I set a executable to (bool) false? *eg*

**Comment by brusch** [comment]
Yes, that's possible, at least for most of them. 
Just set them to `false` in your `di.php` 

Note: this doesn't work for soffice, pdftotext, gs, php, ffmpeg at the moment.

**Comment by brusch** [comment]
With the last commit it's possible to deactivate all of them, see: 71e2d95f89c25f3ffb2354cd4b757415a451ca7e

**Comment by brusch** [comment]
fyi: there was a small change recently: I've added the prefix `pimcore.` for the definitions in `di.php`. 
See: https://github.com/pimcore/pimcore/blob/master/website_example/config/di.example.php#L25-25
