### ISSUE TITLE
[Bug]: template engine bundle man kann bei $this->inc keine params mitgeben

### ISSUE THREAD

**Issue by elements-team** [pimcore/pimcore#10083]
### Expected behavior

$this->inc( $page->getCustomSetting('subnavSnippet')->getId(), [ 'pages' => $page ] )

### Actual behavior

Fehler in der Navigation:

$this->inc( $page->getCustomSetting('subnavSnippet')->getId(), [ 'pages' => $page ] )

man kann bei $this->inc keine params mitgeben (also pages wird nicht in das include snippet übergeben)

Wurde durch die template engine bundle ausgelöst.

Im file zb: /Snippets/subnav-3-col.html.php Hab ich die $pages abfrage unterbunden mit einem if somit gibts keine fehler, aber es wird nichts ausgegeben.

### Steps to reproduce

Im Pimcore X Update 
Im file zb: /Snippets/subnav-3-col.html.php Hab ich die $pages abfrage unterbunden mit einem if somit gibts keine fehler, aber es wird nichts ausgegeben.

**Comment by fashxp** [comment]
please create issues in english

**Comment by dvesh3** [comment]
please create an issue on repo https://github.com/pimcore/php-templating-engine-bundle in English. thanks!
