### ISSUE TITLE
Width issue with multiselect field

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#10089]
### Expected behavior

Width of class definition should be respected.

### Actual behavior

Width setting gets ignored.

### Steps to reproduce

- Create new class with select and multiselect field
- Set width to something arbitrary on both of the fields
- Create a new object
- Width gets respected for the select but not for the multiselect

Codewise it looks fine but maybe a 3rd party issue?

Maybe related: https://github.com/pimcore/pimcore/pull/6899

![image](https://user-images.githubusercontent.com/6142086/130059754-798241fe-b400-4647-985f-44ba70aa9896.png)

![image](https://user-images.githubusercontent.com/6142086/130059794-eab79b66-c96d-4241-8963-adbb3384881c.png)

**Comment by weisswurstkanone** [comment]
@blankse could you please have a look ? 🙇

**Comment by blankse** [comment]
@weisswurstkanone Yes the MultiSelect has always the width of the longest value. The width is only for the component around it. This behavior was also before #6899
Maybe a other option can be set? (e. g. columnWidth?)
https://docs.sencha.com/extjs/7.4.0/classic/Ext.ux.form.MultiSelect.html

**Comment by weisswurstkanone** [comment]
Hello @blankse , After reading the docs I doubt that columnWidth would work. 

Would it make sense to investigate this further by diving into the Ext code ? From the config options I don't see a real difference compared to the dropdown.

Btw, just one observation: This is from 6.9 😄

![image](https://user-images.githubusercontent.com/6142086/130206996-e70e7823-360a-4af7-9080-8738c4865d2b.png)

**Comment by blankse** [comment]
@weisswurstkanone I created an PR. 
The multiselect seems to have problems with css width.
So it is related to #6899  😄

**Comment by weisswurstkanone** [comment]
fixed via #10107
