### ISSUE TITLE
[Bug]: SVG image blurred

### ISSUE THREAD

**Issue by elements-team** [pimcore/pimcore#10086]
### Expected behavior

SVG image thumbs are sharp

### Actual behavior

SVG image thumbnails are all blurred.

### Steps to reproduce

Go to pimcore Demo:
https://demo.pimcore.com/admin/login/deeplink?document_151_page

 

Go to the snippet: 
https://demo.pimcore.com/admin/login/deeplink?document_166_snippet
and change the image (need to override) to this svg: https://demo.pimcore.com/admin/login/deeplink?asset_368_image

**Comment by dvesh3** [comment]
Fixed by #10668
