### ISSUE TITLE
[Bug]: Error saving brick with cropped image: __clone method called on non-object

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#10109]
### Expected behavior

Use "select specific area of image" using image editable and save it.

### Actual behavior

When saving the document an error appears.

`__clone method called on non-object
Server threw exception - could not perform action. Please reload the admin interface and try again.`

![image](https://user-images.githubusercontent.com/90033/130225018-14eface3-2ec7-41c9-8ae6-8ebc64a55bb0.png)

### Steps to reproduce

1. Create a brick with an image editable
2. Crop image
3. Save document

I can't reproduce it in the pimcore demo.

Version: 10.x-dev|eb2feb802d9cff6befeb2eb3095d70919579c120

**Comment by dvesh3** [comment]
sorry, not able to reproduce it with image advanced type.
