### ISSUE TITLE
Image view/upload error while reading IPTC data for blocked images

### ISSUE THREAD

**Issue by KailaJayapalreddy** [pimcore/pimcore#1010]
### Expected behavior 
 When file is not readable then its better to skip instead of warning. image should be viewable in pimcore.

### Actual behavior  

i am getting following error while uploading a blocked image. please find it in attachment section.

Warning: Invalid argument supplied for foreach() in /var/www/html/pim-live/pimcore/models/Asset/Image.php on line 376 {"success":true,"msg":"Success"}

### Steps to reproduce  
download attachment from this post and upload it into assets section 
i found this issue in PIMCORE 4.3.1

### Code example 
following funciton should be like below
![down_s_dmas_487721_z_01a](https://cloud.githubusercontent.com/assets/4464755/19920963/b4299714-a101-11e6-9f9c-2c4795e2fb04.jpg)
![down_s_dmas_487721_z_01a](https://cloud.githubusercontent.com/assets/4464755/19920970/bbd734da-a101-11e6-93df-c552383a2ac2.jpg)

    public function getIPTCData()
    {
        $data = [];

        if (is_file($this->getFileSystemPath())) {
            $result = getimagesize($this->getFileSystemPath(), $info);
            if ($result) {
                $mapping = [
                    '2#105' => 'headline',
                    '2#120' => 'caption',
                    '2#092' => 'location',
                    '2#090' => 'city',
                    '2#095' => 'state',
                    '2#101' => 'country',
                    '2#100' => 'countryCode',
                    '2#080' => 'photographerName',
                    '2#110' => 'credit',
                    '2#085' => 'photographerTitle',
                    '2#115' => 'source',
                    '2#116' => 'copyright',
                    '2#005' => 'objectName',
                    '2#122' => 'captionWriters',
                    '2#040' => 'instructions',
                    '2#015' => 'category',
                    '2#020' => 'supplementalCategories',
                    '2#103' => 'transmissionReference',
                    '2#010' => 'urgency',
                    '2#025' => 'keywords',
                    '2#055' => 'date',
                    '2#060' => 'time',
                ];

                if ($info && isset($info['APP13'])) {
                    $iptcRaw = iptcparse($info['APP13']);
                    if (is_array($values) || is_object($values))
                    {
                        foreach ($iptcRaw as $key => $value) {
                            if (is_array($value) && count($value) === 1) {
                                $value = $value[0];
                            }

                            if (isset($mapping[$key])) {
                                $data[$mapping[$key]] = \ForceUTF8\Encoding::toUTF8($value);
                            }
                        }
                    }
                }
            }
        }

        return $data;
    }

**Comment by brusch** [comment]
Was already fixed by #866 
Please verify bugs on demo.pimcore.org first, if possible - Thanks!
