### ISSUE TITLE
CLI Unpublished objects in href relation return null from href getter

### ISSUE THREAD

**Issue by cleggypdc** [pimcore/pimcore#1011]
### Expected behavior 
When using the Commandline with object lists, href relations to unpublished objects should return a related object regardless of it being published or not
  
### Actual behavior  
Href relations to unpublished objects do not get returned through the commandline.
(It is not clear if this happens elsewhere although they do appear in the admin panel correctly)
  
### Steps to reproduce  

1. Create a new ClassDefinition (I created a class called Category).
2. Add an href field and restrict relations to objects (e.g myHref).
3. Create several objects of this class (leave all unpublished).
4. Create an href relationship between each of the new objects.
5. Place following script in /pimcore/cli folder.
  
### Code example 
```php
include "startup.php";
$list = new \Pimcore\Model\Object\Category\Listing();
$list->setUnpublished(true);
$list->setCondition('myHref__id IS NOT NULL');

foreach($list->load() as $index=>$category) {

  $parentCat = $category->getParentCategory();

  if (!$parentCat) {
    echo "missing";
    continue;
  }

```

If the relation is an object folder or published object then the relation is returned, otherwise the realtionship getter returns NULL

Tested on 4.3.1 & nightly build 3997.

**Comment by brusch** [comment]
This is an intended behavior, the CLI has basically the same behavior as the MVC, therefore unpublished relations are filtered. 

The scope of `$list->setUnpublished(true);` is limited to the currently list only, so this has no effect on the relations of an object. 
To get all objects no matter if they are published or not or where they are used, please use the following flag: `\Pimcore\Model\Object\AbstractObject::setHideUnpublished(false);`

**Comment by cleggypdc** [comment]
This makes sense now, thanks for explaining @brusch :)

**Comment by geekdevs** [comment]
@brusch Is it possible to only disable it for one relation and not globally?
