### ISSUE TITLE
[Bug]:  Pimcore 10.1.x - Grid loses focus after row cell editing

### ISSUE THREAD

**Issue by tecbird** [pimcore/pimcore#10131]
### Expected behavior

After editing a row in a grid, with real store changes, the row should not loses its focus.
So after doing store change the keyboard up/down navigation on grid is working as expected to select next row for editing

### Actual behavior

Currently after a cell in a row was changed, the focus is lost and keyboard up/down navigation is not working anymore. 

### Steps to reproduce

1. Open a grid
2. Focus a row
3. Change cell content, e.g. text via "CellEditing" and press "Enter" to save
4. Press keyboard down to select next row => nothing happened

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
