### ISSUE TITLE
Liveupdate 3.11. to 4.31

### ISSUE THREAD

**Issue by pinacolada23** [pimcore/pimcore#1013]
After liveupdate i loose all class definitions.
I didnt' have some fatal error.
I can connect on Pimcore and see version 4.3.1
if i look in settings/Object/class no class appears

**Comment by nspacex** [comment]
Do you use class mappings and an "own" namespace? In this case, maybe your namespace is not correct registered. I had this problem in one updated instance, after i registered my namespace correctly in /website/config/startup.php it works

**Comment by pinacolada23** [comment]
No i don't use class mapping and no specific namespace.
No specific DEV or custom.
I create only standard class from standard interface

**Comment by brusch** [comment]
Seems that something went wrong during the update process. 
But this is definitely a topic for your support forums and not the issue tracker, so may I ask you to open a new topic there (https://groups.google.com/forum/#!forum/pimcore). Thanks! 

Anyway, following some tips that may help to solve your problem: 
- any error message when you open `http://yourhost/admin/class/get-tree`
- are there any `definition_*.php` files in `website/var/classes` if not (or if there are some missing), re-run the following script https://github.com/pimcore/pimcore/blob/master/update/3925/postupdate.php
