### ISSUE TITLE
[Improvement]: Read-only fields for the Advanced Many-to-Many object relation which can only be edited via PHP API (not users)

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#10164]
### Improvement description

With advanced Many-to-Many object relations we have certain use cases where it would be useful to have read-only fields. This is currently not possible (it can be implemented with EventListeners but this is quite cumbersome). I guess this improvement would be quite easy to implement.

![many-to-many-sample](https://user-images.githubusercontent.com/1703552/130945052-4587e481-fc4f-4e7a-8fef-54a227293ce1.png)

Example: In the picture above you can see a sample of a many-to-many object relation. The fields of all columns can be edited in the user interface by users. 

![many-to-many-definition-sample](https://user-images.githubusercontent.com/1703552/130945400-b4641eab-114d-4bb5-b0df-893255cdfcc8.png)

In the picture above you see a sample class definition for a many-to-many object relation field. The suggested improvement is to add a single column into the colmns definition with a checkbox for "readonly". When saving the object the system has to make sure that objects within the UI have read-only system field columns. Modification should not be possible via the admin UI.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
