### ISSUE TITLE
Colon separated PATH variable in pimcore settings causes issues in Windows Environment

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#1017]
# Bug Report
Pimcore recently disabled individual paths to executables and is now using a unified PATH variable in system settings. PATHs can be added with colon as separation. This does cause issues on Windows Systems where paths usually have colons inside itself. Console.php does the following:
```php
$paths = explode(":", $pathVariable);
```
Which does split the system setting which does look like this for example:
```php
"path_variable" => "C:\\Program Files (x86)\\PHP\\v5.6\\:C:\\apps\\wkhtmltopdf\\bin\\",
```
to the following paths:
C
Program Files (x86)\PHP\v5.6
C
apps\wkhtmltopdf\bin

None of them are valid of course.

### Expected behavior 
We should be able to define the paths to ffmpeg, libreoffice and the other software properly.

### Proposal
We could use # or another char as separator. Using 
```php
$paths = explode("#", $pathVariable);
```
and
```php
"path_variable" => "C:\\Program Files (x86)\\PHP\\v5.6\\#C:\\apps\\wkhtmltopdf\\bin\\",
```
works fine with Pimcore 4.3.1.

**Comment by brusch** [comment]
Pimcore now uses the the value of `PATH_SEPARATOR` as separator. 
So on Windows systems this is `;` and on *nix based `:`.

**Comment by Cruiser13** [comment]
Thanks!

**Comment by Cruiser13** [comment]
Hello @brusch Pimcore 4.4.0 still uses colons in Console.php:
https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Tool/Console.php#L72

**Comment by brusch** [comment]
@Cruiser13 Thanks - fixed.
