### ISSUE TITLE
Improve regex validation message for end user.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1018]
If an object has for instance a data field with some regex validation, we found that the message is a little too technical for the end user who manage product datas on Pimcore.

Actually he get this message:
![msg1](https://cloud.githubusercontent.com/assets/9025839/20030629/52a80150-a369-11e6-892b-c40441a7d613.png)

`Value in field [ text ] doesn't match input validation '[a-z]+' fieldname=text` could be changed to something more easy. Only few object editors will understand regex ; ) So better maybe to just say `Value in field [ text ] doesn't match input validation` or at least put the regexp as complementary/aside information:
`Please provide the value in field "text" in a good format` and below in smaller `(pattern:  '[a-z]+')`. You get the idea ; ) (my english is not perfect)

The link below `Detailled information` could scare the user, as he got very technical data (the stack trace), and he can think the system broker or whatever : )

![msg2](https://cloud.githubusercontent.com/assets/9025839/20030693/6c03401e-a36a-11e6-9353-053abb999fb7.png)

Maybe this link should only be added when debug is activated. I think in case of regex validation there should not be this link as this is not an error.

Thanks.

**Comment by MatthewBooth** [comment]
I second this issue. Our clients are not technical at all and I want to have a character limit on a field. Showing them the regex and stacktrace is going to frighten them.

**Comment by weisswurstkanone** [comment]
What about a "human-readable" explanation of the pattern (in addition to the actual regex) which is can be configured in the class definition?

**Comment by MatthewBooth** [comment]
@weisswurstkanone that would be the ideal solution. But at that point do you then add multiple regex fields for different error messages?

At the very least we need to be able to present a regex failure message that's provided in the object definition. So that I can at least say "the entered text is more than 100 characters" upon error or something.

**Comment by weisswurstkanone** [comment]
something like that

![image](https://cloud.githubusercontent.com/assets/6142086/24248881/7bd57b6e-0fd1-11e7-83c6-eba480733bde.png)

**Comment by MatthewBooth** [comment]
That looks perfect!

**Comment by Yivan** [comment]
@weisswurstkanone I confirm your solution is great!
Thanks

**Comment by Yivan** [comment]
I make a bump on this issue, as it is a needed one i think to make better UI for enduser.

Actually regexp message mean nothing at all for people managing Pimcore object wich are not developpers ; )
In fact this message with the regexp make them think something really bad happens and can be freightened : )) Imagine a product manager editing a product on Pimcore wich see ".{5,}"... he will have no clues of what to do to bypass the error message.

**Comment by brusch** [comment]
Currently this is not on our roadmap, but we're happy to merge PRs for that 😊
