### ISSUE TITLE
LTS repository sync error after every commit

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#10195]
### Expected behavior

No message sent

### Actual behavior

After every commit to a repo which is base for a pull request I get an email "LTS repository sync: All jobs have failed", see e.g. https://github.com/BlackbitNeueMedien/pimcore/actions/runs/1182365113

### Steps to reproduce

Create PR, commit something to the source branch.

**Comment by brusch** [comment]
a342c8d5b7bc18e4a63a92c9e6cd18d1fa1aa826 should fix the behavior 😊
