### ISSUE TITLE
Grid improvement: reset filter button

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1019]
Actually to reset the filters on the grid there is two possiblity:
- reload the grid panel (take some times)
- click on the `Direct SQL Query` button (fast, but it was not his main purpose):

![reset1](https://cloud.githubusercontent.com/assets/9025839/20030859/c52ac8bc-a36d-11e6-84a0-24bbeea06612.png)

Maybe a dedicated small button could be added, for instance a cross picto near the `Filter active` button:

![reset2](https://cloud.githubusercontent.com/assets/9025839/20030762/f145cce6-a36b-11e6-84f7-43e668231498.png)

---
Aside this small improvement, the perfect solution would be to be able to uncheck by filters, but it involves more developpement and could maybe be part of a separated improvement more bigger.
Instead of having:
![filter condition](https://cloud.githubusercontent.com/assets/9025839/20030779/458956d8-a36c-11e6-8e76-85e3d762ba2b.png)
We could get it by line, with a cross X to remove the corresponding filter, which will be for this exemple:
```
Title like justo X
modificationDate < 2016-11-09 X
```
In this case i think name should be the column name in the grid (and not the database name column) for better comprehension so `modificationDat`a will be `Modification Date (System)`.
(maybe if such improvement is considered, we should maybe add possibility to create filter and save them as predefined, but it seems complicated i think as there not only one grid, but a grid for each object/directectory... => having predefined filter on custom report could be more consistent for end user finally).
Do you think a separate issue on this idea is a good idea or actually not ?

Thanks.

**Comment by weisswurstkanone** [comment]
Added  a simple "clear filters" button for now. This should allow you to quickly reset all filters without having you to reload the entire tab (which would result in the loss of any other settings, e.g. paging stuff). 
Maybe the visualization is not ideal ... I could imagine a splitbutton instead.
The second proposal sounds interesting. However, I am not sure if this maybe sort of overkill ...

Build 3998

**Comment by Yivan** [comment]
Thanks weisswurstkanone.
Ok if you think the improvements are overkill for now, you can close the task. I needed or could think it easier i would open a separate improvement issue on this subject later.
