### ISSUE TITLE
[Bug]: Saving cache does not take the enabled or cli status into account

### ISSUE THREAD

**Issue by rubanooo** [pimcore/pimcore#10228]
### Expected behavior

When disabling the cache it should also stop saving items into the cache. This can cause a lot of overhead when running scripts with large amounts of data because of the unserialization of objects. 

### Actual behavior

When calling `Pimcore\Cache::disable()` cache items are still being saved, while loading cache items are disabled

Code for loading items from the cache:
https://github.com/pimcore/pimcore/blob/10.x/lib/Cache/Core/CoreCacheHandler.php#L344-L367

Code for saving items into the cache:
https://github.com/pimcore/pimcore/blob/10.x/lib/Cache/Core/CoreCacheHandler.php#L296-L311

As you can see loading items has no check and saving does. Is there is specific reason for this? If not, are you willing to accept a pull request that adds the same checks to the load method?

### Steps to reproduce

Run `Pimcore\Cache::disable()` and try to load any object.

**Comment by brusch** [comment]
Fixed by #10277
