### ISSUE TITLE
[Bug]: not possible to download test/ directory using composer

### ISSUE THREAD

**Issue by rjankiew** [pimcore/pimcore#10226]
### Expected behavior

When using composer, tests/ directory should be downloaded. 

### Actual behavior
In version 10.1.2, however, it is not, even when using `composer update --prefer-source`. There is no mention of any alternate way of downloading this files using composer.

This is due to [this commit](https://github.com/pimcore/pimcore/commit/3429f5c173fa0576169f93182fea725db5f02b55) excluding "build and test files".

### Steps to reproduce

`composer update`

**Comment by jdreesen** [comment]
> When using composer, tests/ directory should be downloaded.

Why should it be downloaded?

**Comment by jdreesen** [comment]
I just tried installing Pimcore with `composer create-project pimcore/skeleton source-test --prefer-source` and Composer downloaded the `tests` folder like it should:
![grafik](https://user-images.githubusercontent.com/424602/131871810-7f49ebb4-fb0f-4917-8179-40dc392977bd.png)

---

In an existing (dist) installation, you must add
```json
  "config": {
    "preferred-install": {
      "pimcore/pimcore": "source",
      "*": "dist"
    }
  },
```
to your `composer.json` file and delete your `vendor/pimcore` folder.
After that, run: `composer update pimcore/pimcore` to make composer re-install the dependency from source.

**Comment by brusch** [comment]
@jdreesen thanks a lot for clarifying! 🙏
