### ISSUE TITLE
[Objects] Quantity Value: Do not store Unit IDs in class definitions

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#1023]
when using units in class configuration, the definition stores unit Ids as reference:

![bildschirmfoto 2016-11-08 um 10 15 50](https://cloud.githubusercontent.com/assets/700119/20093295/717451ee-a59c-11e6-8368-02ec396f2c97.png)

Because of that, we can't share definitions in different environments. The dev DB is not always in sync with the staging or production DB. So we might have different Unit Ids.

It would be great to have a string reference, like the linked objectbricks for example:

![bildschirmfoto 2016-11-08 um 10 19 36](https://cloud.githubusercontent.com/assets/700119/20093394/db26c752-a59c-11e6-8b5d-14b9d94c071a.png)

**Comment by cleggypdc** [comment]
+1 for this experience too.

**Comment by weisswurstkanone** [comment]
Problem here is that there is no other mandatory unique field (other than the internal ID) that could identify the unit. Not even the abbreviation.

**Comment by cleggypdc** [comment]
How about storing the classId in the php config file too, call it originalClassId. Then at least we can build a sanity check into either class deployment or custom deployments to check that the ID's map. It would make debugging easier :-)

**Comment by solverat** [comment]
Because we can't share the unit id between environments, it's quite impossible to use them. The *quantity value* requires "valid units" and can't be empty. With empty fields, the unit will be stored with the given id: 

![bildschirmfoto 2016-12-07 um 10 50 38](https://cloud.githubusercontent.com/assets/700119/20962905/8f2bf17a-bc6b-11e6-8a05-2fef4ef38b26.png)

So, either allow empty "valid units" or even better: store units in class configuration as string or something like that.

**Comment by brusch** [comment]
Proposed solution: 
- Make `id` column initially editable (not editable after it was initially set)
- change `id` columns to a `VARCHAR` in db schema (in definition table and data columns)
- make it visible per default (in grid). 
- save all classes, object bricks, field collections in update script

**Comment by BlackbitNeueMedien** [comment]
@brusch, @weisswurstkanone: Is there a reason why you do not want to use the abbreviation as unique field? I actually do not know of any unit abbreviation which as different meanings in different contexts, do you?

**Comment by brusch** [comment]
@BlackbitNeueMedien not really ... at least from my side.

**Comment by rubanooo** [comment]
@brusch any updates on this issue?

**Comment by blankse** [comment]
Yes abbreviation in class definitions would be nice... I have the same problem now.

**Comment by weisswurstkanone** [comment]
@blankse , as far as I remember there was a requirement from the original sponsor of this datatype that the abbreviations are not unique. Imported data from the external system was mapped by the reference column. The expectation was that exported data results in the same external reference so that units can be mapped again in the external system.

I think we should give it a try.

However, there are more topics
- csv export
- unit definition grid
- migration
- etc....

**Comment by blankse** [comment]
@weisswurstkanone We already changed this behavior in 6.7.0 with this PR #6667

When we make the same as the solution with class id? So we can give a string as ID?

**Comment by weisswurstkanone** [comment]
Ok, didn't notice that #6667 already got merged ...

**Comment by weisswurstkanone** [comment]
@blankse what do you think about the solution proposed by @brusch ?

**Comment by blankse** [comment]
> Proposed solution:
> 
> - Make id column initially editable (not editable after it was initially set)
> - change id columns to a VARCHAR in db schema (in definition table and data columns)
> - make it visible per default (in grid).
> - save all classes, object bricks, field collections in update script

@weisswurstkanone This one? Yes this would be good :)

**Comment by weisswurstkanone** [comment]
Yes, exactly :-)

**Comment by lundenmiika** [comment]
@blankse @weisswurstkanone Is saving the classes (etc.) is truly necessary in the proposed solution, as the ID is not editable after the creation? Also, the current classes reference the Quantity Values by a string, as opposed to an integer, as it stands in the current DB schema. Could you point me to what I'm missing in my thinking?

I'm considering creating a PR for this in the near future, feel free ping me for updates.

**Comment by lundenmiika** [comment]
> @blankse @weisswurstkanone Is saving the classes (etc.) is truly necessary in the proposed solution, as the ID is not editable after the creation? Also, the current classes reference the Quantity Values by a string, as opposed to an integer, as it stands in the current DB schema. Could you point me to what I'm missing in my thinking?

To add to this, updating classes etc. should be required only in a migration script when downgrading. But, again – feel free to guide me, if you think I'm not seeing everything regarding the issue.

**Comment by weisswurstkanone** [comment]
This would imply that we change the base unit as well

**Comment by weisswurstkanone** [comment]
Obstacle: Unit::create does not have a built-in auto-increment anymore
