### ISSUE TITLE
[Bug]: Fallback language not used in shared translations

### ISSUE THREAD

**Issue by thgross** [pimcore/pimcore#10238]
### Expected behavior

shared translations use the fallback language for keys without translation.

### Actual behavior

pimcore shows the translation key instead of the fallback language.

### Steps to reproduce

1. log into https://demo.pimcore.com/admin
2. In system settings, set the fallback language for "German" to "en"
3. In Shared Translations, search for the Key "general.buy" an remove the german word "Kaufen".
4. go to https://demo.pimcore.com/de. At the bottom of the page, the three cars should have a button labeled "Buy". Instead, the button's label reads "general.buy".

**Comment by brusch** [comment]
Fixed by #10241
