### ISSUE TITLE
Thumbnail URLs for images in Wysiwyg fields

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#1024]
### Expected behavior 
When you add an image to a wysiwyg field of an object and try to output this field's content in the front end this image should be displayed regardless if the visitor is logged in or not.
  
### Actual behavior  
Logged-in users see images, logged-out not. When you call the image URL directly you see that not-logged-in users get redirected to login page.

### Steps to reproduce  
* create class with a wysiwyg field
* create object of created class and insert an image into the wysiwyg field by drag & drop
* right-click image, click "image properties", confirm the image URL is "/admin/asset/get-image-thumbnail/id/XXXX/..." and copy this URL
* call this URL prepended by the domain the project runs on, e.g. http://example.org/admin/asset/get-image-thumbnail/id/XXXX/... -> image will be shown
* log out of pimcore
* try to call the image URL again -> you get redirected to login page

Another way to reproduce this is to create a controller + action and output the content of the wysiwyg field via $object->getXXX(). As logged-in user you get to see the image, as logged-out not. This is the normal case but it is slightly more work to reproduce the bug this way.

### Background 
Admin_AssetController contains the getImageThumbnailAction method which gets called by the above image URL. Actually it is defined that the permission system gets bypassed when calling action "get-image-thumbnail" (see Admin_AssetController::init()). 
Nevertheless not logged-in users get redirected in Pimcore\Controller\Action::init() which gets called by Admin_AssetController's init method (parent::init())

**Comment by brusch** [comment]
This is a wanted behavior, you cannot just copy the thumbnail URL from the admin interface and use it without authentication. 
The image sources in the HTML code are rewritten prior output, using 
https://github.com/pimcore/pimcore/blob/bdce56e88bf36bccc2702eb73ce5e0a9f376106a/pimcore/lib/Pimcore/Tool/Text.php#L78-L78

**Comment by BlackbitNeueMedien** [comment]
We tried to output `$object->getNameOfWysiwygField()` and got image URLs like "/admin/asset/get-image-thumbnail/id/XXXX/... 
Or do we need to call `Pimcore\Tool\Text::wysiwygText($object->getNameOfWysiwygField())` ourselves?

**Comment by brusch** [comment]
No, you don't have to call this method manually. 
Seems that you're doing something strange there ;-) 

I've just created a simple test-case and everything works as expected: 

I dropped an image to the WYSIWYG, the HTML source in editmode is: 
```html
<p><img pimcore_id="40" pimcore_type="asset" src="/admin/asset/get-image-thumbnail/id/40/width/600/aspectratio/true" style="width:600px" /></p>
``` 

Later, in my controller I've the following code: 
```php
        $o = Object::getById(55);
        echo $o->getTest();
        exit;
``` 

that outputs: 

```html
<p><img pimcore_id="40" pimcore_type="asset" src="/website/var/tmp/image-thumbnails/0/40/thumb__auto_5100bd88df0075e780bbfb26685378c0/dsc04462.jpeg" style="width:600px" /></p>
``` 

which is completely fine and expected behavior.

**Comment by BlackbitNeueMedien** [comment]
I have a view which gets a product object. This object contains the wysiwyg field. I access the wysiwyg field in a partial which getes included by the view.

In the view I have
`echo $this->partial('product/partials/montagehinweis.php', array('product' => $this->product));`

And in the partial I have:
`$text = $this->product->getWysiwygField();`

This way the image source seems not to get replaced.

But as it is Pimcore 3.1.1 I won't investigate this any further...
