### ISSUE TITLE
Object edition layout broken on v4.3 - ExtJS 6

### ISSUE THREAD

**Issue by lm-galilee** [pimcore/pimcore#1025]
# Bug Report
After upgrading a Pimcore v3.0 to v4.3, object edition layout is broken with ExtJS 6. Everything looks fine when using the ExtJS 3 legacy interface.
# Expected behavior 
![legacy user interface ext js 3 4](https://cloud.githubusercontent.com/assets/18484267/20106802/a83c8e6e-a5d6-11e6-956f-60dac4f628b6.png)
# Actual behavior  
![modern user interface ext js 6](https://cloud.githubusercontent.com/assets/18484267/20106801/a82bb0da-a5d6-11e6-80aa-2d3de99e9c41.png)
# Steps to reproduce
- Create a class following this definition: [class_Fittings_export.json.txt](https://github.com/pimcore/pimcore/files/578702/class_Fittings_export.json.txt)
- Create an object from the new Fittings class.

**Comment by brusch** [comment]
That's ok. 
The ExtJS 6 Interface has a different behavior & styling, so you'll have to adopt your definition to work with the new interface. That's also the reason why we provide the possibility to select whether to use the ExtJS 3 or 6 interface.
