### ISSUE TITLE
[Bug]: Warning in edit mode when using pimcore_cache

### ISSUE THREAD

**Issue by jantomicky** [pimcore/pimcore#10251]
### Expected behavior

Using `pimcore_cache` does not produce a warning when working in document edit mode.

### Actual behavior

When `pimcore_cache` is used as the [template extensions documentation](https://pimcore.com/docs/pimcore/current/Development_Documentation/MVC/Template/Template_Extensions/index.html#page_Example) suggests, a warning shows up in edit mode:

```
An exception has been thrown during the rendering of a template ("Warning: Undefined array key "pimcore_viewcache_test_cache_key"").
```

![Screenshot 2021-09-06 at 15-09-39 localhost Pimcore](https://user-images.githubusercontent.com/41518085/132234233-258516c2-4fec-4336-879f-9e435087da6a.png)

### Steps to reproduce

Install Pimcore (I used Docker instructions from the demo at https://github.com/pimcore/demo#getting-started) & paste a snippet with `pimcore_cache` to a template:

```
{% set cache = pimcore_cache('test_cache_key', 60) %}
{% if not cache.start() %}
    <h1>This is some cached microtime</h1>
    {{ 'now'|date('U') }}
    {% do cache.end() %}
{% endif %}
```

View the document in edit mode in administration, a warning mentioned above shows up.

**Comment by dvesh3** [comment]
Fixed by #10256
