### ISSUE TITLE
[Bug]: Mandatory check for image gallery doesn't work

### ISSUE THREAD

**Issue by MyZik** [pimcore/pimcore#10255]
### Expected behavior

An error should be thrown if mandatory gallery field is empty

### Actual behavior

A mandatory check for gallery field is ignored

### Steps to reproduce

1. Create a new Gallery-field in your data object and mark them as mandatory
2. Create a new data object and don't fill the gallery field:

<img width="1670" alt="Bildschirmfoto 2021-09-06 um 19 02 34" src="https://user-images.githubusercontent.com/12817320/132247380-d75ebb39-ab70-4aaa-b7bf-653830f3ac0a.png">

And

<img width="1670" alt="Bildschirmfoto 2021-09-06 um 19 03 18" src="https://user-images.githubusercontent.com/12817320/132247425-fba08736-94b8-4475-be63-6a2c76d50a4e.png">

**Comment by brusch** [comment]
fixed by #10263
