### ISSUE TITLE
[Bug]: Cannot upload SVG Asset

### ISSUE THREAD

**Issue by iidaloiki** [pimcore/pimcore#10252]
### Expected behavior

SVG can be added as any other asset.

### Actual behavior

Upload modal freezes due to error in asset upload. In network tab, request /add-asset seems to return HTTP 500 with following error:

> Pimcore\Model\Asset\Image\Thumbnail::getLocalFileFromStream(): Return value must be of type string, null returned

### Steps to reproduce

Try to upload an SVG file into assets in Pimcore Admin.

**Comment by brusch** [comment]
@iibs actually I'm not able to reproduce the issue. 
Can you please confirm that you're able to reproduce the issue on out demo instance: 
https://github.com/pimcore/pimcore#demo-community-edition

If you're able to reproduce it, please also share the used SVG file. 
Thanks!

**Comment by iidaloiki** [comment]
Hi,

It seems that the issue is fixed in some minor version. On demo (v.10.1.2) it works fine, so I updated my local environment and seems to work as well. Closing the issue.
