### ISSUE TITLE
[Bug]: Create object via advanced-many-to-many-object-relation, creates duplicated entry

### ISSUE THREAD

**Issue by dpfahlbusch** [pimcore/pimcore#10272]
### Expected behavior

An object will be created and assigned

### Actual behavior

The object is created and is added twice

### Steps to reproduce

1.  Go to current demo
2. Add a advanced-many-to-many-object relation to car class
3. Create object via this relation
4. It will be added twice

**Comment by brusch** [comment]
Fixed by #10280
