### ISSUE TITLE
[Bug]: Table in data object does not use the table config

### ISSUE THREAD

**Issue by jdevries14** [pimcore/pimcore#10285]
### Expected behavior

When you create a table config and create a new data object it should use it such as:

**Config**
<img width="1256" alt="Screenshot 2021-09-09 at 13 59 24" src="https://user-images.githubusercontent.com/44669189/132681804-434d1d9c-c6a8-482c-9d50-1df705c3cccc.png">

**Behavior**
<img width="1507" alt="Screenshot 2021-09-09 at 13 59 35" src="https://user-images.githubusercontent.com/44669189/132681829-917f32c7-76af-41cb-ba30-c0f588b4d6b1.png">

### Actual behavior

Actual behavior is very strange, first the table is totally empty, not even the columns are showing, also you first have to create a new row, new columns, than click trash button to get your own data etc.

<img width="1520" alt="Screenshot 2021-09-09 at 14 00 03" src="https://user-images.githubusercontent.com/44669189/132681879-5ea75600-8250-4987-b74f-c0b176babbd3.png">

### Steps to reproduce

Check in discussion https://github.com/pimcore/pimcore/discussions/10284

**Comment by dvesh3** [comment]
Fixed by #10290

**Comment by jdevries14** [comment]
@dvesh3 did this fix break it? check https://github.com/pimcore/pimcore/discussions/10396 please, it happened after this fix was merged

**Comment by dvesh3** [comment]
@jdevries14 yes, thanks for reporting. now fixed by #10400
