### ISSUE TITLE
[Bug]: CacheKey for Classification Store KeyConfig not removed on delete

### ISSUE THREAD

**Issue by JochenCal** [pimcore/pimcore#10298]
### Expected behavior

CacheKey will be removed when KeyConfig is deleted

### Actual behavior

CacheKey still exists after KeyConfig is deleted

### Steps to reproduce

- Generate a KeyConfig using PHP Api and save it
- Delete this KeyConfig
- Generate a new KeyConfig with same name as before
- Use KeyConfig::getByName() to retrieve the KeyConfig
- Cached KeyConfig that should have been deleted will be returned

When retrieving a KeyConfig and execute $keyConfig->delete(), the KeyConfig still remains.
So when delete a KeyConfig, generate a new one with same name and try to get retrieve if using KeyConfig::getByName(), the KeyConfig that still remain in Cache is returned.

Looking at application/vendor/pimcore/pimcore/models/DataObject/Classificationstore/KeyConfig.php there are two different cache key definitions in the methods getByName() and delete():

getByName()
`$cacheKey = 'cs_keyconfig_' . $storeId . '_' . md5($name);`

delete()
`cacheKey = 'cs_keyconfig_' . $this->getId();`

Seems the problem is that the keys are different in the two methods?!

**Comment by JochenCal** [comment]
In additon when having a look at KeyConfig::getByName() the cache value is always returned due to line ~164:
`$config = Cache::load($cacheKey);`

**Comment by weisswurstkanone** [comment]
@JochenCal could you please provide a PR ?

**Comment by dpfahlbusch** [comment]
maybe this is related https://github.com/pimcore/pimcore/issues/9348 ?

**Comment by weisswurstkanone** [comment]
@dpfahlbusch yes, good point! 

https://github.com/pimcore/pimcore/issues/10298 is more a caching topic. 
So for @JochenCal , could you just kick it out by name and id for now. I guess we need a discussion how to proceed with this disabled flag in the long term.

**Comment by lukmzig** [comment]
Closing this issue for now since it seems to be resolved already
