### ISSUE TITLE
Assets\Images: Picture corrupted after upload

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#1029]
### Expected behavior 
I want to upload this picuture into pimcore.
![corrupted_image](https://cloud.githubusercontent.com/assets/17384333/20174433/0b9f5640-a73e-11e6-8cf9-5724a040e8f2.jpg)

On my machine this image looks totally normal and I can open it without any problems.

### Actual behavior  
Whenever I upload this image to pimcore I get the following error message.
![error_message](https://cloud.githubusercontent.com/assets/17384333/20174507/5a9a2068-a73e-11e6-83c9-49a752125ba7.jpg)

It uploads the image completely to pimcore and even show a preview of the picture when hovering it, but you can't open the asset. Even with those issues you can drag and drop it to documents and objects and it even displays correctly in the frontend.

### Steps to reproduce  
– Download the picture provided above
– Upload it to pimcore
– See the error message
– Try to open it in the Assets panel

**Comment by brusch** [comment]
Unable to reproduce.
I'm pretty sure that you're having the same problem as described in #1010 which is fixed already. 

Please follow the following steps before opening an issue for us: 
- verify the problem on demo.pimcore.org
- check if there's an existing issue for the problem

Thanks!
