### ISSUE TITLE
[Feature]: Tag-Administration doesn't have events

### ISSUE THREAD

**Issue by HaaseIT** [pimcore/pimcore#10306]
### Feature description

As stated in the title, the tags administration doen't currently have any events (onSave, onDelete, ...)

I will be more than happy to supply a pullrequest, on which branch should I base it on, current minor or upcoming minor?

**Comment by fashxp** [comment]
please base it on 10.1 branch

**Comment by HaaseIT** [comment]
I'll put it on 10.2 then propably, I won't have it finished by wednesday.

**Comment by fashxp** [comment]
I doubt that we can make the 10.2 this Wednesday, so it will postponed for another 2 weeks I guess.

**Comment by HaaseIT** [comment]
I just found, this has already been added in 2020-09, see: #5368 - I am closing this.

**Comment by fashxp** [comment]
haha :-)
