### ISSUE TITLE
[Bug]: Scheduled Tasks

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#10318]
### Expected behavior

Can save a schedule task

### Actual behavior

Can not save a schedule task

### Steps to reproduce

1. Open https://demo.pimcore.fun/admin/login/deeplink?object_765_object
2. Save a new draft
3. Go to the Schedule tab and create a new item
4. Save only schedule tasks
5. Reload

**Comment by blankse** [comment]
@weisswurstkanone Seems to be a regression of https://github.com/pimcore/pimcore/pull/8452

**Comment by blankse** [comment]
Fixed by #10320

**Comment by MosiiAUT** [comment]
Is there a possibility to include this fix in Pimcore 6?

**Comment by brusch** [comment]
@MosiiAUT unfortunately no, as support for P6 has been ended already (except enterprise customers who have access to LTS).
