### ISSUE TITLE
[Bug]: Search exception when data object with classification store data exists

### ISSUE THREAD

**Issue by cmann90** [pimcore/pimcore#10327]
### Expected behavior

Have data objects with classification store data and use search without an error occurring.

### Actual behavior

Once a data object is created which contains classification store data the search will throw an exception until all data objects with classification store data are deleted:
![image](https://user-images.githubusercontent.com/68635243/133435828-068ced67-9823-45e1-a46a-a33fc20f1e54.png)

Timestamp: Wed Sep 15 2021 14:29:46 GMT+0200 (Central European Summer Time)
Status: 500 | Internal Server Error
URL: /admin/search/search/quicksearch?_dc=1631708986555
Method: GET
Message: Impossible to invoke a method ("getActiveGroups") on a string variable ("CLASSIFICATIONSTORE").
Trace: 
in /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/object.html.twig:36
#0 /var/www/html/var/cache/dev/twig/3b/3b14fbf32a0832c60e6e31ec1eabd73ed242a430b036933e78d7b0cc12e80262.php(150): twig_get_attribute(Object(Twig\Environment), Object(Twig\Source), 'CLASSIFICATIONS...', 'getActiveGroups', Array, 'method', false, false, false, 36)
#1 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_28341e01fbb69e9da4bbb5e9aba9f8394b034ab78c2cbdcde7c247d4156bc983->doDisplay(Array, Array)
#2 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#3 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#4 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#5 /var/www/html/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#6 /var/www/html/vendor/symfony/framework-bundle/Controller/AbstractController.php(251): Twig\Environment->render('@PimcoreAdmin/S...', Array)
#7 /var/www/html/vendor/pimcore/pimcore/lib/Controller/Controller.php(81): Symfony\Bundle\FrameworkBundle\Controller\AbstractController->renderView('@PimcoreAdmin/S...', Array)
#8 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Searchadmin/SearchController.php(495): Pimcore\Controller\Controller->renderView('@PimcoreAdmin/S...', Array)
#9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(156): Pimcore\Bundle\AdminBundle\Controller\Searchadmin\SearchController->quicksearchAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher), Object(Pimcore\Config))
#10 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(78): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#11 /var/www/html/vendor/symfony/http-kernel/Kernel.php(199): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/www/html/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}

### Steps to reproduce
1. Create classification store with single group and key
2. Create class which uses created classification store
3. Create data object and add classification store data

**Additional information**
- Demo site does not have this issue (https://demo.pimcore.fun/admin)
- Tested with 10.1.3 and 10.1.2 skeleton
- Docker installation with default docker-compose configuration
- Search works fine when no data object is created with classification store data. After deleting the data object with classification store data the search works fine again.

**System Information**
![image](https://user-images.githubusercontent.com/68635243/133435894-4ed8bc5b-7bdd-47f2-8dea-a5cda05be003.png)

![image](https://user-images.githubusercontent.com/68635243/133435937-94766414-25cf-43db-b266-d4f259562ef1.png)

![image](https://user-images.githubusercontent.com/68635243/133435949-7942a94b-1d44-4a0f-ab5f-03f3159ae39f.png)

**Comment by dvesh3** [comment]
Fixed by #10334
