### ISSUE TITLE
[Bug]: JS error in user settings

### ISSUE THREAD

**Issue by aweichler** [pimcore/pimcore#10323]
### Expected behavior

A click on a user should open the user in the user settings.
I am on the latest Pimcore 10 Version.

### Actual behavior

There is a javascript error in user settings, when open a user.
The error is in [Line 501](https://github.com/pimcore/pimcore/blob/ddc570a88760762da3f3f460c0fe9b381ad4d1f0/bundles/AdminBundle/Resources/public/js/pimcore/settings/user/user/settings.js#L501).
The problem is, that the for...in statement should not be uses on arrays.

A possible solution could be, to change the [Line 477](https://github.com/pimcore/pimcore/blob/ddc570a88760762da3f3f460c0fe9b381ad4d1f0/bundles/AdminBundle/Resources/public/js/pimcore/settings/user/user/settings.js#L477) to `var itemsPerSection = {};`.

### Steps to reproduce

It only occures under some circumstances.

**Comment by mcop1** [comment]
Hello @aweichler ,
I am sorry, but we can´t reproduce the issue on our end of the side. Could you please give us a step by step guide of what exactly you are doing? 

Best regards and thank you for your efforts

**Comment by aweichler** [comment]
I tried to figure out why this is happening. I have 2 project. At one project there is no issue and in an other there is the issue.
In Firefox 92.0 i got the following errors / output:
I changed the [code](https://github.com/pimcore/pimcore/blob/ddc570a88760762da3f3f460c0fe9b381ad4d1f0/bundles/AdminBundle/Resources/public/js/pimcore/settings/user/user/settings.js#L495) to following:
![code](https://user-images.githubusercontent.com/53085804/134284678-78fe36d3-4ae1-418d-9aa6-d17c3cef1b21.png)
At the console I got the following output:
![console-log](https://user-images.githubusercontent.com/53085804/134284670-ba414840-f6f4-46f4-b2d5-593962eca132.png)

By changing the `itemsPerSection` to an object all works fine.
