### ISSUE TITLE
Object listing returns empty result on "first call"

### ISSUE THREAD

**Issue by nspacex** [pimcore/pimcore#1033]
# Bug Report
  
### Expected behavior 
Object listing should return all objects from this particular type

### Actual behavior  
The "first call" returns an empty result. Because "first call" is not the best description, please have a look on the following example. We have 10 object from type ClassA.

```php
$callA = new \Pimcore\Model\Object\ClassA\Listing();
print count($callA->getObjects()) // returns 0
```

```php
$callA = new \Pimcore\Model\Object\ClassA\Listing();
$callB = new \Pimcore\Model\Object\ClassA\Listing();
print count($callB->getObjects()) // returns 0
```

```php
$callA = new \Pimcore\Model\Object\ClassA\Listing();
print count($callA->getObjects()) //returns 0
$callB = new \Pimcore\Model\Object\ClassA\Listing();
print count($callB->getObjects()) // returns 10
```

```php
$objectA = \Pimcore\Model\Object\ClassA::getById(1);
$objectB = \Pimcore\Model\Object\ClassA::getById(2);

$callB = new \Pimcore\Model\Object\ClassA\Listing();
print count($callB->getObjects()) // returns 2 (!!!)
```

### Further informations 

Pimcore build 4000, 4001
Linux, PHP7.0.12, MySQL 5.7
Windows, PHP7.0.9, MySQL 5.7
With and without cache (Redis2, MySql)

Sometimes in the Backend i have to reload the object folders in the tree to get a object list. This also happens in the pimcore demo.

**Comment by nspacex** [comment]
It seems as if this only happens in an upgraded instance (4.3.1 -> 4.4.0 and 3.x -> 4.3.1 -> 4.4.0). This problem doesn't occur on a fresh 4.4.0 installation. It's a little bit strange.

**Comment by brusch** [comment]
Seems to be related to the Mysqli DB adapter, please use `PDO_Mysql` while we're further investigating the problem.

**Comment by nspacex** [comment]
Hi brush, thanks for the hint and the of course the fix!

**Comment by brusch** [comment]
A new build is on it's way and should be finished in about 5 minutes.
