### ISSUE TITLE
[Bug]: Styling of Collapsible

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#10342]
### Expected behavior

Users can clearly see that an item can be collapsed.

### Actual behavior

Icon is white on grey background > Hard to see.
![image](https://user-images.githubusercontent.com/13643455/133638583-fa8e51dc-a13c-4af2-ae9c-2b39bb7cd49a.png)

### Steps to reproduce

Create a an object with a collapsible element.

**Comment by fashxp** [comment]
what collapsible?

**Comment by ckemptner** [comment]
![image](https://user-images.githubusercontent.com/13643455/133640837-e2b64a78-092f-453f-9f17-5677115d1090.png)

**Comment by fashxp** [comment]
fixed in current versions
