### ISSUE TITLE
[Bug]: Video-Types throw error in debugmode but work in prod

### ISSUE THREAD

**Issue by CiLLiTxBanger** [pimcore/pimcore#10368]
### Expected behavior

Videos get rendered and displayed OR don't produce an error which freezes the document.

### Actual behavior

BE document stuck in "Please Wait"

### Steps to reproduce

1. Insert random Video Content Area 
2. Change Type to 'dailymotion' 
3. insert random Video ID (eg.: x84cbm1)
4. When in debugmode you get an error
When in prod-mode, the video gets displayed

I tested in Pimcore Demo where i manually changed to debugmode 

Also reproducible with normal Assets:
1. insert random Video Content Area
2. Type->Asset
3. Path->some nonsense
4. When in debugmode you get an error which freezes the document
When in prod-mode the video gets not displayed

Could you please answer why a video can be loaded and rendered in prod but will throw an error in dev?
This makes debugging super hard. 

To reproduce in pimcore demo, it was pretty difficult to change it to debugmode. But this was the only way i could make sure it's not due to my code.

**Comment by dvesh3** [comment]
Fixed by #10370
