### ISSUE TITLE
[Bug]:  Pimcore\Composer::clearCache reports an [ErrorException] Array to string conversion

### ISSUE THREAD

**Issue by gilsys** [pimcore/pimcore#10373]
### Expected behavior

After composer update or require, pimcore executes 
"pimcore-scripts": [
      "Pimcore\\Composer::clearCache",
      "Pimcore\\Composer::installAssets"
]

It should execute the scripts without any problem.

### Actual behavior

After composer update or require, it shows an exception (also on a fresh install)

X packages you are using are looking for funding.
Use the `composer fund` command to find out more!

> Pimcore\Composer::postUpdate
> Pimcore\Composer::clearCache
Script Pimcore\Composer::clearCache handling the pimcore-scripts event terminated with an exception

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

  [ErrorException]
  Array to string conversion

### Steps to reproduce

Doing a composer update on a fresh pimcore x installation.
I found the bug on a windows platform, I don't.
I can clearCache using console cache:clear without any problem.

**Comment by milesimarco** [comment]
Same problem here with XAMPP on Windows, PHP version `8.0.9`

**Comment by brusch** [comment]
We're not officially supporting Windows, however of course we'd merge a PR that fixes the issue. 
Thanks for your understanding & looking forward to a PR. 

Please also consider #10201 which tried already to fix that.
