### ISSUE TITLE
[Bug][Document\Editable\Video]: Pimcore toolbox vs. inline video breaks edit behaviour

### ISSUE THREAD

**Issue by rberneder** [pimcore/pimcore#10417]
### Expected behavior

A video shall be output via ```{{ pimcore_video('video') }}``` in editmode directly in document (desired to be "read-only"), but edited in Pimcore toolbox config dialog.

### Actual behavior

When the video already has an asset as content, and the toolbox gets opened (for example to empty the video), the edit button at the top right corner of the video editable is not shown. This is because the edit button is put to the video in the document.

This leads to confusion, since the video can be correctly edited in the dialog as long as it is empty. As soon as it has content, one has to first open the toolbox dialog, then close it immediately to get the edit button in the document editable.

### Steps to reproduce

- Create an area brick.
- Let it have ```{{ pimcore_video('video') }}``` as editable in the template.
- Add the following config:
```php
$config = new EditableDialogBoxConfiguration();
$config->setItems([[
    'type' => 'video',
    'name' => 'video',
    'label' => 'Video'
]]);
```
- Open the area brick in a document.
- Open the toolbox dialog.
- Click the edit button and add an asset as video.
- Save & reload the document.
- Open the same toolbox dialog again.
- ERROR: The edit button of the video (which was there before saving) is gone.
- Close the dialog.
- ERROR: See that the edit button now appears (only after toolbox was opened) at the template-video editable.

**Comment by dvesh3** [comment]
@rberneder As mentioned in the steps, you are using same name `"video"` for both editables, which is wrong as editables in dialog box are just like editables in the template.

Please see statement in the documentation:
"_The editables in the dialog are just normal editables, there's not difference to editables which are defined via the template. So can either use them as well in the template or access them in your custom code._" https://pimcore.com/docs/pimcore/current/Development_Documentation/Documents/Editables/Areablock/Bricks.html#page_Accessing-Data-of-the-Editable-Dialog

**Comment by rberneder** [comment]
Thanks for your reply. However here is why this is still an issue for me:
Video editables are either rendered as ```<video>``` or ```<iframe>```, which is done by Pimcore automatically. This is very convenient.

If I want to edit the video in the toolbox and preview it in "default" document editmode, I would have to implement the HTML output logic myself, which is cumbersome and redundant. I could imagine to just use ```{{ pimcore_video('video').frontend|raw }}```, but this leads to the same behaviour / error.

**Comment by brusch** [comment]
Please provide a PR that would improve the behavior - from our side there's no priority on that. Thanks for your understanding 😊

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
