### ISSUE TITLE
read only objects field doesn't calculate width of reference column correctly

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#1041]
take a look at this example screen:

![image](https://cloud.githubusercontent.com/assets/4639428/20346886/d9128d08-abfe-11e6-95a7-f235f3cdd003.png)

 The second objects field is set to read only. The reference column should have the same width as the first object field by default.

**Comment by weisswurstkanone** [comment]
fixed build 4006

**Comment by markus-moser** [comment]
great, it work's - thx!
