### ISSUE TITLE
[Bug]: Shortcut Keys permission issue.

### ISSUE THREAD

**Issue by abhishekceon** [pimcore/pimcore#10418]
### Expected behavior

If the user/role has permission to do anything then only related to that action short-cut keys should work.

### Actual behavior

Even User/Role don't have permission to that specific action still user is able to do action through shortcut keys.

### Steps to reproduce

We are experiencing a problem with the key binding section of the Pimcore User section. Even if the user doesn’t have the right to perform any action but using key binding still he/she can do. For example of the user is not allowed to unpublish from rights but using a shortcut key can do

Step:-1 Don't give permission to any user/role for "Unpublish the product"
Step:-2 Login through that User/Role.
Step:-3 As permission is not given "Unpublished" action button will not appear on the screen/frontend. So through button we will not be able to unpublish the product.
Step: -4  Try to "Unpublish" the product through shortcut-keys. It will get "Unpublished" through short-cut keys, even without permission.

**Comment by abhishekceon** [comment]
@brusch  I have not mentioned the Pimcore version. I have checked this issue on Pimcore version 6.6.11.

**Comment by brusch** [comment]
@abhishekceon Thanks for coming back on this - I'm afraid nothing really relevant change there since this version - so I'd assume it's still an issue in Pimcore 10.

**Comment by weisswurstkanone** [comment]
If I see it correctly there was a change in 6.8.12. See https://github.com/pimcore/pimcore/pull/8504
