### ISSUE TITLE
[Bug]: CleanupBrickTables maintenance task does not recognize bricks with capitalization in name

### ISSUE THREAD

**Issue by CountZero1981** [pimcore/pimcore#10427]
### Expected behavior

CleanupBrickTables runs smoothly, without any errors.

### Actual behavior

I've managed to reproduce the problem from #5824.  
Our devops used [this manual](https://github.com/pimcore/pimcore/edit/10.x/doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/05_DB_Setup.md) and added lower_case_table_names=1 in accordance with it.  
Unfortunately, he did it on the production DB, on Linux and on AWS, so I didn't even have access to mysql system settings and I wasn't aware of the changes.  
My next morning started with shouts of angry users, who were completely unable to work with the website. After some research, I changed the actual table names to lower case (luckily, I had access to mysqldump/mysql on production).  
So I appreciate the decision taken in Mysql 8 to disallow changing this setting if DB directory has already been initialized.  
But now we're getting the error with CleanupBrickTables mentioned in #5824, and I was able to reproduce it on a fresh installation, see the steps to reproduce.

### Steps to reproduce

Use Linux, set lower_case_table_names=1 in Mysql config. Create a new DataObject class, named with a capital letter. This creates tables with lower_case, but actual class files are still created case-sensitive. So CleanupBrickTables gets lower_cased Mysql table name and tries to look up a class with a lower_cased filename on a case-sensitive linux filesystem.
But even if we lower_case the filename of the class, datatype definitions (which are string literals in Pimcore) cannot be lower_cased - and Pimcore on Linux still tries to look them up in case-sensitive mode. It should not be a problem on Windows, though - datatype definitions and filenames can be CamelCased there, but CleanupBrickTables should still be able to get them, because the filesystem is case-insensitive there.

I've made a test using fresh & clean Pimcore installation, the result is shown [here](https://raw.githubusercontent.com/CountZero1981/pimcore/image/Untitled.png)

**Comment by jdreesen** [comment]
Is this related: #12391 ?

**Comment by aKugler** [comment]
Hi @jdreesen!

Sorry for my english. 
In my opinion this belongs together. In the code it is searched for the brick tables. If the value is set, then the table is called e.g. object_brick_mybrick_1. Then iterate over the tables and operate out the name of the trick. In this case mybrick remains. Finally mybrick is searched in the cache. But if you have created the brick with the key MyBrick, then it will not be found. At least with the fieldcollections it is the same.

https://github.com/pimcore/pimcore/blob/11.x/lib/Maintenance/Tasks/CleanupBrickTablesTask.php#L51
