### ISSUE TITLE
[Bug]: Not editable fields are editable after page reload

### ISSUE THREAD

**Issue by Navino16** [pimcore/pimcore#10424]
### Expected behavior

Not editable fields must stay not editable after browser page reload.

For example, here the field "product name" is not editable:
![image](https://user-images.githubusercontent.com/22234867/134941011-f74d2903-039f-4ef5-a1e1-c8fba33af3de.png)

This issue have been tested on Chrome and Firefox on pimcore v10.1.3 and pimcore v10.1.x-dev (pimcore demo website)

### Actual behavior

When reloading the browser page all fileds that are marked as not editable are editable

For example, here the field "product name" become editable after page reload:
![image](https://user-images.githubusercontent.com/22234867/134941311-2a8aa220-d818-4251-afc2-b86991f59aeb.png)

### Steps to reproduce

1.  Mark any class field as not editable and save
2. Open an object of this class, not editable field is not editable
3. Reload the browser page
4. Not editable field become editable

**Comment by dvesh3** [comment]
Related to https://github.com/pimcore/pimcore/pull/10079

**Comment by dvesh3** [comment]
Fixed by #10433
