### ISSUE TITLE
[Bug]: Restore folder with file inside it throws error when pimcore S3 filesystem

### ISSUE THREAD

**Issue by jonathantyar** [pimcore/pimcore#10431]
### Expected behavior

The restore folder on recycle should working fine as the same when using local filesystems

### Actual behavior

![image](https://user-images.githubusercontent.com/19704585/135034223-017e77a7-d20c-4e3b-ae59-bd38b7cff218.png)
returning this popup when trying to restore the folder 
`
Timestamp: Tue Sep 28 2021 13:21:36 GMT+0700 (Western Indonesia Time)
Status: 500 | Internal Server Error
URL: /admin/recyclebin/restore
Method: POST
Message: Notice: getimagesize(): Error reading from /home/jonathantyar/Projects/titikpintar/pimcore-dam/var/tmp/temp-file-6152b470146cd-c075631e378cdb4790f6195270900c.tmp!
Trace: 
in /home/jonathantyar/Projects/titikpintar/pimcore-dam/vendor/pimcore/pimcore/models/Asset/MetaData/EmbeddedMetaDataTrait.php:246
#0 /home/jonathantyar/Projects/titikpintar/pimcore-dam/vendor/pimcore/pimcore/models/Asset/MetaData/EmbeddedMetaDataTrait.php(89): Pimcore\Model\Asset\Image->getIPTCData()
#1 /home/jonathantyar/Projects/titikpintar/pimcore-dam/vendor/pimcore/pimcore/models/Asset/MetaData/EmbeddedMetaDataTrait.php(49): Pimcore\Model\Asset\Image->readEmbeddedMetaData()
#2 /home/jonathantyar/Projects/titikpintar/pimcore-dam/vendor/pimcore/pimcore/models/Asset/Image.php(73): Pimcore\Model\Asset\Image->handleEmbeddedMetaData()
#3 /home/jonathantyar/Projects/titikpintar/pimcore-dam/vendor/pimcore/pimcore/models/Asset.php(534): Pimcore\Model\Asset\Image->update()
#4 /home/jonathantyar/Projects/titikpintar/pimcore-dam/vendor/pimcore/pimcore/models/Element/Recyclebin/Item.php(309): Pimcore\Model\Asset->save()
#5 /home/jonathantyar/Projects/titikpintar/pimcore-dam/vendor/pimcore/pimcore/models/Element/Recyclebin/Item.php(322): Pimcore\Model\Element\Recyclebin\Item->doRecursiveRestore()
#6 /home/jonathantyar/Projects/titikpintar/pimcore-dam/vendor/pimcore/pimcore/models/Element/Recyclebin/Item.php(169): Pimcore\Model\Element\Recyclebin\Item->doRecursiveRestore()
#7 /home/jonathantyar/Projects/titikpintar/pimcore-dam/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/RecyclebinController.php(152): Pimcore\Model\Element\Recyclebin\Item->restore()
#8 /home/jonathantyar/Projects/titikpintar/pimcore-dam/vendor/symfony/http-kernel/HttpKernel.php(157): Pimcore\Bundle\AdminBundle\Controller\Admin\RecyclebinController->restoreAction()
#9 /home/jonathantyar/Projects/titikpintar/pimcore-dam/vendor/symfony/http-kernel/HttpKernel.php(79): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#10 /home/jonathantyar/Projects/titikpintar/pimcore-dam/vendor/symfony/http-kernel/Kernel.php(199): Symfony\Component\HttpKernel\HttpKernel->handle()
#11 /home/jonathantyar/Projects/titikpintar/pimcore-dam/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle()
#12 {main}`

### Steps to reproduce

1. Configure pimcore to use S3 filesystem 
2. Create folder on Assets
2. Add file into folder
3. Delete the folder
4. Try to restore the folder

**Comment by dvesh3** [comment]
Sorry, cannot reproduce the issue. what is your folder structure?

**Comment by jonathantyar** [comment]
![image](https://user-images.githubusercontent.com/19704585/135193281-a1318269-05d7-4d26-9b17-78a2e29e8680.png)
@dvesh3 thanks for the response, the folder structure is something like this, the problem only occur when there's an image inside the folder, am i missing some additional tools? https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Additional_Tools_Installation.html

**Comment by dvesh3** [comment]
@jonathantyar I tried with image inside the folder but couldn't reproduce the issue. It is more seems like the file permissions issue. please verify if you have correct permissions on `/var` folder https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/File_Permissions.html

**Comment by jonathantyar** [comment]
@dvesh3 
could you please check the permission? already run the command that pimcore provided

![image](https://user-images.githubusercontent.com/19704585/135220253-6579ff59-a276-4333-95bb-f687838b66da.png)
public folder

![image](https://user-images.githubusercontent.com/19704585/135221048-636a5177-f4d8-445a-9546-4fe1afbc9a78.png)
root folder

**Comment by jonathantyar** [comment]
@dvesh3 if it's because permission issue, why other file besides image can be restored? like mp4 and zip

**Comment by jonathantyar** [comment]
@dvesh3 seems problem with our s3 iam roles, since using local flysystem only for recyclebin seems working fine, closing this issue. thank you
