### ISSUE TITLE
Deleting "all roles" remoes system user and breaks pimcore installation

### ISSUE THREAD

**Issue by Pegasuz** [pimcore/pimcore#1044]
One of our customers reported this weird bug. When you are at the Roles overview, there is an option in the context menu to Delete the folder "All roles". When doing this, Pimcore removes the system user and the Pimcore installation breaks. You are logged out and cannot login again.

Maybe this option can be removed for the "All roles" folder?

### Steps to reproduce  
* Go to Roles
* Open Context menu for folder "All Roles"
* Choose "Remove"

**Comment by weisswurstkanone** [comment]
thx.

fixed in build 4006
