### ISSUE TITLE
BC Support: please provide the Pimcore's PHP Templating plugin to the comunnity.

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#10449]
### Improvement description

It is not cool to leave the community without that bridge when you have it as it makes the upgrade **of the CORE** harder as it is big BC. This in result will lower the upgraded installations significantly I believe, and this is bad for the core and the pimcore community as whole. Please consider to make it available for the community.

**Comment by brusch** [comment]
Sorry, first of all this is not the right place -> moved to Discussions. 
Second, as every product we have to evolve as well and so we did. Actually, if you take it exactly, it was Symfony's decision to drop PHPEngine support 😉

Anyway, we are aware that this is a huge change, therefore we did this as part of a major release and for our enterprise-grade customers we're offering the PhpEngine as part of our commercial enterprise subscription (which is actually really not expensive) also for Pimcore 10 to gain more time for migrating the templates to Twig.
