### ISSUE TITLE
[Bug]: Required fields in Blocks fail serverside check

### ISSUE THREAD

**Issue by HaaseIT** [pimcore/pimcore#10443]
### Expected behavior

In more complex sites, validating required fields within block elements fails.

This is checked in:
vendor/pimcore/pimcore/models/Document/PageSnippet.php:664

Here, we get the list of used editable names. The issue is that, for some block elements, a non-existing ediable name is added with the number of 1000000

I have come so far, as to see, this is added in:
vendor/pimcore/pimcore/lib/Event/Model/Document/EditableNameEvent.php:117
although when you look at the page object, there is no editable with that name.

There will be, for example an editable:
stage_imageset_block:1.stage_image
but this ediable name will also be added to the list:
stage_imageset_block:1000000.stage_image

I will add some screenshots and object dumps.

### Actual behavior

Validation works properly.

### Steps to reproduce

No easy way found yet, to reproduce, will look further.

**Comment by HaaseIT** [comment]
![EditableNameEvent](https://user-images.githubusercontent.com/7584444/135220130-054aeb00-7215-47a6-8247-53dab982a307.png)
![editableNames](https://user-images.githubusercontent.com/7584444/135220133-70983332-03fb-4625-9470-d015cc937e8c.png)
![pageEditables](https://user-images.githubusercontent.com/7584444/135220135-2b27db0c-9dc8-4bdf-93cb-0e60d2628750.png)

**Comment by HaaseIT** [comment]
Also interesing, in:
vendor/pimcore/pimcore/models/Document/Editable.php
the block stage_image actually comes up twice in debug, so, the .1 and the .1000000 are actually seen as seperate blocks.
![editableIndexFirst](https://user-images.githubusercontent.com/7584444/135225451-89de3cad-3b57-4245-ab3a-ce7a49655250.png)
![editableIndexSecond](https://user-images.githubusercontent.com/7584444/135225453-8da7ccbf-d5cd-4819-b5f6-8c20f3643c98.png)

**Comment by HaaseIT** [comment]
Another observation:

When I debug the twig template, the content of the for loop is always run twice:

```twig
                {% for i in pimcore_block('stage_imageset_block').iterator %}
                    {% set foo = 1 %}
                    <div/>
                {% endfor %}
```

When I set a breakpoint in the {% set foo = 1 %} line, it is caught twice when saving the document.

**Comment by HaaseIT** [comment]
So, to me it looks, as if serverside validation of pages is broken, whenever pimcore_block() is used.

Nobody notices though, since this is usually not done, because the request usually has the missingRequiredEditable parameter in POST data.

For some reason, on some of my prod pages this parameter is not sent with the request, hence I encounter this issue.

I do wonder, why is this usually omitted? One could argue, because whoever sends this request is a thrusted user. I for one would not rely on clientside validation even for something as trivial as this.

**Comment by HaaseIT** [comment]
One more thing, the missbehaving pages have all been created in Pimcore 6.9, new pages skip serverside validation.

In table: documents_page, column: missingRequiredEditable
6.9 pages have NULL
10.1 pages have 0

One (null) triggers serverside validation, the other not.

**Comment by HaaseIT** [comment]
Since I don't know the motives for how this is done, I cannot really come up with a fix here. Maybe if I had a quick chat/talk with someone who knows the motives, I could make a PR to fix this.

@brusch  or one of your colleagues, maybe you could have a quick chat with you?

**Comment by dvesh3** [comment]
@HaaseIT thanks for your findings! 

`block:1000000` entries are generated for handling block editables without reload on documents as these gets parsed in javascript on rendering editables in editmode (see here https://github.com/pimcore/pimcore/blob/10.x/bundles/AdminBundle/Resources/public/js/pimcore/document/editables/block.js#L269-L289).

I tried reproducing the issue by creating documents in admin and publishing it through API but no luck. These documents always had `missingRequiredEditable` property so required editables were validated. 

maybe you can share your complete approach of creating and publishing documents that would be helpful in reproducing the issue. thanks!

**Comment by HaaseIT** [comment]
Dear Divesh,
as written further above, this only happens with documents migrated from pimcore 6.9, which have NULL in the DB as well as in the serialized object in the versions.

To reproduce, you need to change the fields value in both locations.

**Comment by dvesh3** [comment]
@HaaseIT sorry, could not reproduce the issue with `missingRequiredFields` => NULL in db & version:
```twig
{% for i in pimcore_block('blocks').iterator %}
    {{ pimcore_input('required-input', {required: true}) }}
{% endfor %}
```

DB:
![image](https://user-images.githubusercontent.com/5137917/137906283-96a10649-bdd7-495f-9714-d42f0350d480.png)
Version:
![image](https://user-images.githubusercontent.com/5137917/137906573-1558673d-ce78-4938-b924-c3440989f078.png)


API publish save:
```php
$document = Document::getById(279);
$document->setPublished(true);
$document->save();
```
![image](https://user-images.githubusercontent.com/5137917/137906672-76ba3c46-2dc6-452f-b1ac-35bfe72511d3.png)

**Comment by HaaseIT** [comment]
What do you mean, you cant reproduce?

You just posted screenshots of the problem.

All required fields are filled but on trying to publish the document, this exception is thrown.

Want to have a quick chat/talk? We are connected on linkedin.

**Comment by dvesh3** [comment]
> What do you mean, you cant reproduce?
> 
> You just posted screenshots of the problem.
> 
> All required fields are filled but on trying to publish the document, this exception is thrown.
> 
> Want to have a quick chat/talk? We are connected on linkedin.

In my case, required fields are not completely filled.

**Comment by HaaseIT** [comment]
Well, in my case they are.

Then this exception is thrown, because it tries to validate element #1000000
