### ISSUE TITLE
[Improvement]: Update Screenshot(s)

### ISSUE THREAD

**Issue by apokalipscke** [pimcore/pimcore#10467]
### Improvement description

https://github.com/pimcore/pimcore/blob/9a5b9adef0889af8fdade11ff3254ff80c47dd6a/doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/README.md#L59

Among other screenshots, this one also contains errors. The screenshot seems to be quite old and contains incorrect information. 

In this example the way placeholders (variables) are specified in email templates.

**Comment by brusch** [comment]
@apokalipscke if you could contribute on this, that would be very nice 😉 PRs are quite simple and help us a lot in getting further. Thanks in advance! 😊

**Comment by solverat** [comment]
@brusch Why has this been closed? The docs are still wrong: https://github.com/pimcore/pimcore/blob/10.2/doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/README.md

BTW: What are the recommendations for editors if they want to define some dynamic fields in their email templates eg. wysiwyg editors (like "Hello {{ name }}")?

**Comment by brusch** [comment]
Must have been by mistake, sorry 😊 
Yes for dynamic fields you can use Twig, as described.

**Comment by brusch** [comment]
Btw. PRs are still welcome 😉

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
