### ISSUE TITLE
Objects: Improve `Text` layout component to allow dynamic texts

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1046]
Similar to Calculated Value, but with the possibility to provide a rendering class, that returns an HTML string that is displayed in the admin interface. 

![image](https://cloud.githubusercontent.com/assets/142037/20425556/63b439e8-ad7b-11e6-9d52-2764e66de5ea.png)

**Comment by dpfaffenbauer** [comment]
👍

**Comment by fashxp** [comment]
see also https://github.com/pimcore/pimcore/issues/709

**Comment by fashxp** [comment]
should it really ba a new datatype?

**Comment by brusch** [comment]
Good question, but calculated value is specialized for "values" and not for eg. displaying HTML tables etc. in the editing interface. The calculated value has also a column in the query table: 
https://github.com/pimcore/pimcore/blob/1dac15fb3a98916e70dc61151b50861ed2af94d9/pimcore/models/Object/ClassDefinition/Data/CalculatedValue.php#L265-L265

**Comment by dpfaffenbauer** [comment]
I guess the new datatype would act like a renderlet? I think it could be very useful just for admin-interface.

**Comment by brusch** [comment]
Not exactly like a renderlet, since the renderlet is a relation, while this data-type should provide the possibility to display data in the context of the actual object.

**Comment by dpfaffenbauer** [comment]
Yeah, but should it call a controller/action? or should it display static html?

**Comment by brusch** [comment]
I'd prefer just a simple rendering class/method, just the same way the calculated value data-type works. I don't think it's worth to start the entire dispatching process of the controller component.

**Comment by dpfaffenbauer** [comment]
you're right. but anyway, sounds like a good idea.

**Comment by weisswurstkanone** [comment]
build 4016
see https://github.com/pimcore/pimcore/blob/master/docs/Development_Documentation/05_Objects/01_Object_Classes/03_Layout_Elements/01_Dynamic_Text_Labels.md
