### ISSUE TITLE
[Bug]: System Settings / Debug: Mail is only sent to the last address in the comma-separated list

### ISSUE THREAD

**Issue by thgross** [pimcore/pimcore#10465]
### Expected behavior

In Debug Mode, mails should be sent to every address that is configured under System Settings / Debug / Debug Email Addresses (CSV).

Also, debug mails should not be send to cc- or bcc-recipients.

### Actual behavior

In Debug Mode, mails are only sent to the last address in the list.
The mail is sent to cc- and bcc-recipients.

### Steps to reproduce

1. in "System Settings" / "Debug" / "Debug Email Addresses (CSV)", configure at least 2 comma-seperated addresses.
2. send any mail.

**Comment by brusch** [comment]
Fixed by #10494
