### ISSUE TITLE
[Bug]: Pimcore Email Template Is Not Working. Showing Memory Leakage

### ISSUE THREAD

**Issue by kumar2112** [pimcore/pimcore#10476]
### Expected behavior

I have created a mail template and and set some parameter which are replaced in mail template . All things are set .
`        $params=['name'=>'Praveen'];
        $mail = new \Pimcore\Mail();
        $mail->to('praveen.jha@credencys.com');
        $mail->setDocument("/Emails/test");
        $mail->setParams($params);
        $mail->send();`
Above is my code  Below is my  Template Screenshot
![image](https://user-images.githubusercontent.com/12470739/135566927-8d7d96f1-5a81-440b-b261-6ff1c0b66abb.png)

In Proper way it should shoot a mail on my email address.

### Actual behavior

But  In Actully It showing Memory leakage issue 
![image](https://user-images.githubusercontent.com/12470739/135567069-5fdf1c03-c10d-470a-899b-88c4bc33e6c7.png)

### Steps to reproduce

1. Create A mail template 
2. in default controller write below code and execute it in browser
/**
     * @Template
     * @param Request $request
     * @return array
     */
    public function defaultAction(Request $request)
    {
        $params=['name'=>'praveen'];
        $mail = new \Pimcore\Mail();
        $mail->to('praveen.jha@credencys.com');
        $mail->setDocument("/Emails/test");
        $mail->setParams($params);
        $mail->send();

        //return [];
    }

After Lot of Debugging In Code I found that location of memory leakage
![image](https://user-images.githubusercontent.com/12470739/135567569-b23c2569-168e-4642-9b32-eb83a2a39953.png)

**Comment by dvesh3** [comment]
@kumar2112 what makes you think that there's a memory leakage in `Document\Service::render`? sorry, i'm missing the point here.

**Comment by dvesh3** [comment]
please check if you are not the using the `defaultAction` for email document, which might then lead to circular reference.

**Comment by kumar2112** [comment]
> @kumar2112 what makes you think that there's a memory leakage in `Document\Service::render`? sorry, i'm missing the point here.

I think $content is holding a value out of limit. . you can use dum before or after the $content

**Comment by kumar2112** [comment]
> please check if you are not the using the `defaultAction` for email document, which might then lead to circular reference.

I have also checked the default mail

**Comment by brusch** [comment]
Would be nice if you could debug this and provide a fix as a PR - as we're not able to reproduce this issue on our side - thanks 😊
