### ISSUE TITLE
[Bug]: Versions data can not be properly restored

### ISSUE THREAD

**Issue by michaelclaesson** [pimcore/pimcore#10477]
### Expected behavior

When I have two or more versions of an asset I'm expecting to be able to both preview the version (if an image) or publish the older one. I'm also expecting the versions to have different file data.

### Actual behavior

Right now it displays the same image when previewing and if I try to publish an older version of an image I get an error message and if it's a PDF file the preview tab disappears. Also if I check the versions folder on the volume all of the files have the same data.

<img width="699" alt="error-message-image" src="https://user-images.githubusercontent.com/18331514/135577835-c64f87c8-5f25-41d2-9178-6b3c985fee57.png">

<img width="518" alt="no-preview-tab" src="https://user-images.githubusercontent.com/18331514/135577962-272bdddc-926f-4efa-aadc-cb1699d9fa31.png">

### Steps to reproduce

1. Upload an image or a PDF to an asset folder
2. Upload a new version to the same asset
3. Check file data and confirm that all versions have the same file data
4. Try to preview or publish an older version of the asset and confirm that it's not possible

**Comment by brusch** [comment]
Fixed by #10562
