### ISSUE TITLE
[Feature]: Running grid export on cli

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#10475]
### Feature description

Hello,

Having the possibility to trigger grid export form cli command would be a nice addition to fill the missing export feature with open-source capabilities (please see here for more details: https://github.com/pimcore/data-importer/issues/98).

There is already a partner extension which provides this possibility : https://github.com/DivanteLtd/pimcore-scheduled-export
But we could have in the core Pimcore, something simplier, a way in command line to run export with something like: `php bin/console pimcore:export:grid -gridId 18 -format csv -output my-export.csv`

It will decouple the usage of the grid export, which is really powerful and can handle many operator/getter. Being able to trigger them from console (so we can batch, cronjob, etc.) will bring a good value to the grid system and for Pimcore native export feature.

Thanks.

**Comment by fashxp** [comment]
we would love to merge PRs for that.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
