### ISSUE TITLE
[Bug]: Wrong Content In Editable Dialog Box 

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#10474]
### Expected behavior

A correct editable dialog should open, even after replacing the brick at the same index.

### Actual behavior

First placed brick dialog config shows up, even if I'm replacing it.

### Steps to reproduce

Screen Capture
![](http://g.recordit.co/3pC4wqZZaJ.gif)

**Comment by brusch** [comment]
Fixed by #10497
