### ISSUE TITLE
Double Click to Edit for Input Fields

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#1048]
It would be great to have a DCTE feature for input fields. In some cases, there a sensible fields (like an url, seo title or an article number field for example) which should be edited with caution. If activated, the user has to double click into the input field / or click at a symbol (see screenshot) to activate the field. It's "just" a front-end feature, but also a good thing for usability. 

The DCTE feature should be disabled if the field is empty (for example when saving a object for the first time).

### Activate DCTE in Field Settings ###
<img width="597" alt="bildschirmfoto 2016-11-19 um 10 36 24" src="https://cloud.githubusercontent.com/assets/700119/20454582/3303ad68-ae45-11e6-8da5-b64d49f07d64.png">

### Possible View ###
*Combined with a custom info-text element below this should give enough awareness to the user.*

<img width="671" alt="bildschirmfoto 2016-11-19 um 10 40 59" src="https://cloud.githubusercontent.com/assets/700119/20454583/36751d56-ae45-11e6-8f1e-b1fccf6c8317.png">

**Comment by brusch** [comment]
I think this makes mainly sense for text data-types. 
PR's are welcome :)
