### ISSUE TITLE
[Feature]: Batch Edit for Selects with OptionsProvider

### ISSUE THREAD

**Issue by MarcW09** [pimcore/pimcore#10482]
### Feature description

Hello, we have noticed, that we cant batch edit select fields with a defined Options Provider Class like normal select fields with static options. Is it because of the dynamic options or are there other reasons?
Batch edit option for normal selects:
![normal_select](https://user-images.githubusercontent.com/91049331/135612300-5974058e-8a6f-40dc-9671-ffbe94025dce.png)
No batch edit option for selects with defined option provider:
![options_provider_select](https://user-images.githubusercontent.com/91049331/135612392-49a6f4e0-b0dd-4f2c-abfd-427321e0ec6e.png)

**Comment by skoch98** [comment]
This already works. You need to return true on the "hasStaticOptions" method:
See: https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Dynamic_Select_Types.html

But be careful the Option-Provider returns options based on the object context.

For exmaple:
Let's assume we have an option provider to output HP/PS values of a car.
The car with the manufacturer "Ford"  has Options up to 300.
The car with the manufacturer "Kia"  has Options up to 132.
If you use static options here it might cause invalid data.

But if the option provider returns the same data in all objects the static option can be use it without any problems:

```php
<?php

namespace App\DynamicOptionsProvider;

use Pimcore\Model\DataObject\ClassDefinition\Data;
use Pimcore\Model\DataObject\ClassDefinition\DynamicOptionsProvider\SelectOptionsProviderInterface;

class RoleOptionsProvider implements SelectOptionsProviderInterface
{
    /**
     * @param array $context 
     * @param Data $fieldDefinition 
     * @return array
     */
    public function getOptions($context, $fieldDefinition) {
        $roles = new \Pimcore\Model\User\Role\Listing();
        $options = [];
        
        foreach ($roles->load() as $role) {
            $options[] = [
                'key' => $role->getName(),
                'value' => $role->getId()
            ];
        }

        return $options;
    }
    
    public function getDefaultValue($context, $fieldDefinition) {
        return $fieldDefinition->getDefaultValue();
    }


    public function hasStaticOptions($context, $fieldDefinition) {
        return true;
    }
}
```

Will results:
![image](https://user-images.githubusercontent.com/31919154/135715186-1abd1386-7ddc-4368-9cb7-3e86ba666d2d.png)

![image](https://user-images.githubusercontent.com/31919154/135715187-92144ecf-de2f-4b27-8fc6-ddfe55a0ab51.png)

If we change "hasStaticOptions" to false:
```php
    public function hasStaticOptions($context, $fieldDefinition) {
        return false;
    }
}
```

Will results:
![image](https://user-images.githubusercontent.com/31919154/135715236-78ca9630-c564-45e8-ae36-64d678b96e9f.png)
