### ISSUE TITLE
Base page for Staticroutes

### ISSUE THREAD

**Issue by chix** [pimcore/pimcore#1049]
It would  be nice to have a Drag&Drop field in staticroutes table for optional base page (similar to the "target" field in redirects). Url path of set page would be prepended to the route. 

## Feature description
- imagine you have a news list page in your document tree and news objects with staticroute routed detail pages and you want to extend the breadcrumbs with the news title
- currently when routing via a staticroute the deepest document matching the URL is automatically loaded for you, so you load the document breadcrumbs and append the news title, which is nice and easy
- but when you (or the client) rename or move the document, then you also have to rename the staticroute to match the document (or pass the document path as a parameter to the staticroute), which is not so nice
- this would allow to link a document to a staticroute via the document ID so the link persists when path of the document changes
- the document path would be prepended during URL assembling and of course it would be considered during route matching
- you could drop document pages, link and hardlinks

Let me know if you find this useful, I can send a PR for this feature.

Martin

**Comment by dpfaffenbauer** [comment]
There is a plugin for that, nor sure if it works with Pimcore 4:

https://github.com/dpfaffenbauer/pimcore-dynamic-routes

**Comment by chix** [comment]
Did not know about it, looks good :+1: . However it currently does not work with Pimcore 4, do you plan to update it? Also, from the plugin description I think it works a little bit different from what I'm proposing here, so I still think this could be added to staticroutes.

**Comment by dpfaffenbauer** [comment]
I don't have any plans in updating the plugin. But as far as I understand your need, the plugin should totally fit your need. You can create routes like in Staticroutes + adding a "Base-Document" to it. So once a Document gets moved, the route still works.

I guess the Problem with Pimcore 4 is ExtJs6 -> the Plugin was never used with ExtJs 6 before. But, Pull-Requets are welcome :)

PS: I don't take the credit for the plugin, I just uploaded it from the Old Pimcore 1/2 Plugin Repository to Github and made it work for Pimcore 3. Actually, I don't know the original author.

**Comment by brusch** [comment]
Although I understand the idea behind this topic, I think a setting for a single base document is not generic enough - e.g. when dealing with different language trees. 

So I'd go for an event listener on `\Symfony\Component\HttpKernel\KernelEvents::REQUEST` and add the document on the request.

**Comment by brusch** [comment]
A solution that works quite well for us is using a custom templating helper (eg. `objectUrl()`), that tries to get the base path from properties (eg. `newsPath` or `blogPath`) of the current document and prepends it to the path. Another possibility would be to use a dedicated config object, that holds the information.
