### ISSUE TITLE
[Bug]: DAM - select a saved grid configuration does not work in File-ListView (Dropdown menu)

### ISSUE THREAD

**Issue by MaximilianZschock** [pimcore/pimcore#10503]
### Expected behavior

After selecting a folder [DAM/Assets] and switch the view to "List", I want to change the grid configuration to a saved view.

### Actual behavior

![select_saved_grid_view](https://user-images.githubusercontent.com/70199060/136025178-ff893c95-d9d5-4776-b25f-9fb7a906e7b7.png)

The user is not able to select saved "Grid Options".

### Steps to reproduce

1. Select a folder 
2. Change the View to so called "List" 
3. Open "Grid Options" Form 
4. Edit selected grid columns
5. Change to "Save&Share" tab an click "Save Copy&Share
6. Open the Dropdown menu of "Grid Options"

**Comment by dvesh3** [comment]
Fixed by #10507
