### ISSUE TITLE
[Bug]: Same action "Save" behaving differently through "Button Click" and through Shortcut keys.

### ISSUE THREAD

**Issue by abhisheksingh-pimcore** [pimcore/pimcore#10501]
### Expected behavior

The same action should get fired even we are doing it through "Button Click" or through "Shortcut-Keys".

### Actual behavior

Different actions get fired for "Save" through  "Button Click" and "Shortcut-Keys".

### Steps to reproduce

Hi All,

I am facing one issue. When I tried to save an object through "**_Button click_**" it fires the event  "**_Save?task=version_**".

![save1](https://user-images.githubusercontent.com/58170048/135988378-2fac8b6c-ed50-4895-b5b4-0423097a84fa.jpg)

However once same action"Save"  I am trying to hit through shortcut-keys "**_Ctrl S"_** its firing event "**_Save?task=publish_**"

![save2](https://user-images.githubusercontent.com/58170048/135988700-76f93aaa-4c18-4587-9b77-a4b2c00b24d0.jpg)

Note : - Either saving through the button or the shortcut keys should fire the same action.

Step : 1   Login with any user.
Step : 2   Open object
Step : 3  Click on save button to save that object and observe the action fired through the developer tool.
Step : 4  Click "Ctrl S" shortcut-Key" to save that same object and observe the action fired through developer tool.

**Comment by matthiashamacher** [comment]
@abhisheksingh-pimcore I just tested it myself and actually I think this is the correct and intended way.

If you have the object not published yet and use the shortcut it sends unpublish which creates a new version but does not publish the object. If you have published the object and save it sends publish because otherwise it will create a new version but does not publish that version. As this is then different from the "Save & Publish" Button it is not correct, therefore I think the current logic is correct.

**Comment by abhisheksingh-pimcore** [comment]
@matthiashamacher  "**_Save"_** and "**_Save and Publish_**" buttons are different. I am talking about only the "**_Save_**" button.

Either product is published/unpublished, when we click on "**_Save Button_**" it fires  "**_Save?task=version_**".

In shortcut-keys it says "Ctrl S" is for Save, when we click "Ctrl S" it should also fire the "**_Save?task=version_**".

**Comment by matthiashamacher** [comment]
@abhisheksingh-pimcore Yeah I understand but if you have already published you have no single save button, therefore publish is ok. And if the object is not yet published "CRTL + S" will result in "save?task=unpublish" which only additionally set published to false which is no problem as it is not yet published.


**Published**
![CleanShot 2021-10-05 at 18 54 29@2x](https://user-images.githubusercontent.com/32356549/136069427-59bff257-c397-4d74-820f-863ffa753079.png)


**Unpublished**
![CleanShot 2021-10-05 at 18 55 02@2x](https://user-images.githubusercontent.com/32356549/136069434-5edacf8b-b90c-440c-aecf-62bee8673eb4.png)

**Comment by abhisheksingh-pimcore** [comment]
@matthiashamacher that is my concern. If the product is unpublished clicking on the "Save" button and "Shortcut-key" for saving "Ctrl-S" should fire the same action "Save?task=version".

In the case of **_published_** also If you will see/click on the arrow icon on "**_Save & publish_**" button it will open the menu and in this menu, you will find the save menu and once click on that manu, that will fire same action "Save?task=version".

For **_Publish_** we already have different shortcut-keys "**_Ctrl-Shift-P_**"    and for **_unpublished_**   "**_Ctrl-Shift-U_**" on which action get fire correspondingly    "**_Save?task=publish_**" and "**_save?task=unpublish"_**.

In any case as per my understanding either product is published/unpublished if the user is clicking on the "Save" button or doing this same action through shortcut-keys "Ctrl-S", action getting fires ( "Save?task=version") should be same.

**Comment by matthiashamacher** [comment]
@abhisheksingh-pimcore Yeah you are right. I haven't thought about the other shortcuts regarding publish and unpublish. I've created a PR that changes the logic so `save?task=version` is triggered.

**Comment by brusch** [comment]
The original intention was that `Ctrl+S` is a shorthand for the main save action in the UI, so whatever is the green button get's triggered by `Ctrl+S` as well, so that it saves the data, but doesn't change the status of the element. 
I think we should keep that as it is and don't change that within a minor version, I'd assume most user would expect that behavior when saving an element.
