### ISSUE TITLE
Replace asset or renaming it

### ISSUE THREAD

**Issue by romainp89** [pimcore/pimcore#1051]
When adding an already existing file (images, docs, pdfs ...), rather than renominating it by adding "_1 / 2/3 ..." 
why not propose to replace them? 
An alert could ask us if we want to keep the 2 or if we want to replace it.

**Comment by weisswurstkanone** [comment]
also see https://github.com/pimcore/pimcore/pull/1827

**Comment by brusch** [comment]
#1827 already covers this topic partly.
If you'd love to see a more advanced implementation -> PRs are always welcome 😉
