### ISSUE TITLE
[Improvement]: Default Value for Bool in Advanced ManyToMany Relation Column

### ISSUE THREAD

**Issue by danielerne** [pimcore/pimcore#10524]
### Improvement description

Currently it is not possible to set a pre checked Bool value in an Advanced ManyToMany Relation.

**Comment by VLynnik** [comment]
why do you need it?

**Comment by paulverdu** [comment]
Default value for select or input could be handy too

**Comment by kaurov** [comment]
Default value and default value service need to be implemented for boolean select

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
