### ISSUE TITLE
Reusable filter logic for object listings

### ISSUE THREAD

**Issue by maff** [pimcore/pimcore#1053]
Extend listings to accept reusable filter instances which encapsulate filter logic. Example:

```php
<?php
// will apply from and to filters to listing query
$listing->addFilter(new DateRangeFilter($from, $to));
```

**Comment by dpfaffenbauer** [comment]
I already did something similar with Indexes in CoreShop. May you have a look here:

https://github.com/coreshop/CoreShop/blob/master/lib/CoreShop/IndexService/Mysql.php
https://github.com/coreshop/CoreShop/blob/master/lib/CoreShop/IndexService/Condition.php

**Comment by markus-moser** [comment]
Would love to see this feature in the core soon!

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
