### ISSUE TITLE
[Bug]: Server file explorer does not expand to full height

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#10530]
### Expected behavior

Content should expand to use the full height of the available view-port.

### Actual behavior

![image](https://user-images.githubusercontent.com/279826/136435835-5a848051-87cf-4f40-b240-80cb07a4e2ca.png)

### Steps to reproduce

Open any file in *Server File Explorer*

**Comment by dvesh3** [comment]
Fixed by #10546
