### ISSUE TITLE
[Bug]: Mail Issues

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#10550]
### Expected behavior

Mail exception handling works properly. Correct newsletter mailer in test mode has been defined.

### Actual behavior

The opposite of the expected behavior...

## Wrong exception management
This array never gets populated (btw a count() > 0 would be the nicer approach to check against population)
https://github.com/pimcore/pimcore/blob/2e71f2ac4eb74cc501d92aea97469837ecdbad31/lib/Mail.php#L574

## Wrong mailer nulled out
Instead of `newsletter` it should be `pimcore_newsletter`:
https://github.com/pimcore/pimcore/blob/417b50202ceba7721311eb73f92c308f84236546/bundles/CoreBundle/Resources/config/pimcore/test.yaml#L9

**Comment by dvesh3** [comment]
Fixed by #10556
