### ISSUE TITLE
PHP Interceptors

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1055]
Maybe another level of extending Pimcore could be added using interception.
It will allow to developpers to hook more easily anywhere on Pimcore to create extension or when customizing some features.

I was thinking using this library:
https://github.com/goaop/framework (PHP side)

Developper could create aspect (by default there will be none, so Pimcore won't be impacted/slowed by adding this new feature). By creating aspect they prepare hooking pre/post/around method execution.
The "around" pointcut would offer more possibility than events (wich are before or after, and need to exists). So a complete hook could be done too.

Just for reference, here is a post detailling how it has been implemented on Magento 2 for instance:
http://brideo.co.uk/magento2/Interception-vs-observers-in-Magento-2/

**Comment by dpfaffenbauer** [comment]
Looks like a very nice Framework and I could imagine this working with Pimcore. So, you gut my thumbs up.

👍

**Comment by brusch** [comment]
Currently we're using events and I don't think we should mix 2 different approaches - this will cause a lot of confusion. Switching to interceptors will break the compatibility, so currently this is no option (maybe for Version 5, but one after the other, ... we have bigger challenges now ;-)).
