### ISSUE TITLE
JavaScript Interceptors

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1056]
Complementary to https://github.com/pimcore/pimcore/issues/1055, the same could be added for the JavaScript scope. It will make easier to hook on the Pimcore backend before or after any method call.

There are not so many library, but this one could do the job maybe:
https://github.com/scarletjs/scarlet (Javascript side to hook on Backend mehtods)

PHP and JavaScript interceptors could give very powerful tools to developper to customise Pimcore and bring a new way to think how to extend it more freely than it is already (and their is already very good extenting capabilities with Pimcore ; ) ).

**Comment by dpfaffenbauer** [comment]
In case of Javascript: ExtJs already implements a very, very, very basic set of AOP functions:

[Ext.Function.createInterceptor](http://docs.sencha.com/extjs/6.2.0/modern/Ext.Function.html#method-createSequence) 
[Ext.Function.createSequence](http://docs.sencha.com/extjs/6.2.0/modern/Ext.Function.html#method-createInterceptor)

**Comment by brusch** [comment]
See also #1055
