### ISSUE TITLE
Missing languages in Admin Translation in Pimcore X

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#10565]
### Expected behavior

After upgrading from 6.9.6 to 10.1.4 _at minimum_ all languages configured in System settings, and probably generally _all_ langaugse, should be available in *Admin Translations*

### Actual behavior

Some languages are missing:

![image](https://user-images.githubusercontent.com/279826/136952155-43326a74-8b97-4b94-a3cf-c603eb9e66dd.png)
![image](https://user-images.githubusercontent.com/279826/136952244-6b7db090-3097-4b2c-be93-b2f6d78f9154.png)

### Steps to reproduce

See above.

**Comment by brusch** [comment]
Why should a frontend language (system settings) be available as a admin/backend language?

**Comment by NiklasBr** [comment]
Because the top-most field in the fieldset says "Default language in the admin interface", suggesting that this has something to do with the admin backend language. Is that not correct?

**Comment by brusch** [comment]
But there you can only select from languages which are available for the admin interface, so basically those: https://github.com/pimcore/pimcore/tree/10.x/bundles/CoreBundle/Resources/translations

Maybe we need a divider in between the 2 language settings (frontend/admin) to better separate them 🤔

**Comment by NiklasBr** [comment]
Where did they go though? Was it a conscious decision to remove them? Can't see any mention that some languages were removed in Pimcore X in [the upgrade notes](https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/Updating_Pimcore/V6_to_V10.html).

**Comment by brusch** [comment]
As far as I'm aware this has been always the case: 
Admin translations: only admin languages (used to translate labels, ...) 
Shared translations: only frontend languages (used in the application)

**Comment by NiklasBr** [comment]
Oh well, I suppose we can import the languages from poeditor.com to see them again. Were they supposed to have survived the upgrade?

**Comment by brusch** [comment]
Here you can find how admin languages are being loaded: 
https://github.com/pimcore/pimcore/blob/cd098f897bc36c415a18d471844e56753c86b7a6/lib/Tool/Admin.php#L55

**Comment by brusch** [comment]
Hopefully clarified by #10568 😊
