### ISSUE TITLE
[Bug]: Editing a link in WYSIYWG field where the link was an object link does not work

### ISSUE THREAD

**Issue by MercuryKojo** [pimcore/pimcore#10578]
### Expected behavior

href of link should change

### Actual behavior

old href of object persists

### Steps to reproduce

1. highlight a text in a wysiwyg and drag an object that has a linkgenerator in its class definition and save -> link to the object is displayed correctly
2. edit this link to for example https://www.google.com and save -> link still points to the object

**Comment by mattamon** [comment]
@MercuryKojo 

Hmm I guess this is a definition of the linkgenerator right? Why would you change the generated Link in the first place? You could also simply just delete the whole link and write it new. 

The linkgenerator will always bear the reference to the object and thus generate the link. I would consider this behavior as correct.
