### ISSUE TITLE
[Bug] [DataObject]: CSS width for a number field doesn't work for new classes

### ISSUE THREAD

**Issue by MyZik** [pimcore/pimcore#10570]
### Expected behavior

Field width for a number should work

### Actual behavior

If we define the new class with a number field with a pre-defined CSS width, it doesn't work

### Steps to reproduce

1. Create a new class (ex. Currency)
2. Added a Number field(-s) to your class definition and give them a CSS width (ex. 80)
3. Create a new data object. 
![Bildschirmfoto 2021-10-12 um 15 01 49](https://user-images.githubusercontent.com/12817320/136961894-ca1e2244-a771-461a-b846-0865f46f4d28.png)

![Bildschirmfoto 2021-10-12 um 15 01 58](https://user-images.githubusercontent.com/12817320/136961905-b9beb425-e232-4eb5-b181-5b38b4f383aa.png)

**Comment by fashxp** [comment]
not reproducible anymore
