### ISSUE TITLE
Elasticsearch as search backend, but global tool too

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1057]
Actually, search backend feature use mysql full text search. It work fine, but can be limited in some way:
- no fuzzy search
- no "speeling" search
- could lead to be slow if millions of datas on very big project
- no data analysis (or basic)
- old mysql version use MyISAM (could led to slowing because of locks)

In system configuration, we could have an option to configure an elascticsearch instance (url, port). If configured, when data is inserted in mysql, it will be inserted in elasticsearch too (ideally it would be nice to split properties and languages as keys so we can run elastic query based on those to, for instance to exclude some document, filter by language, etc.). Idea is to index all data (like actually for search_backend_data), and filtering will be done by the query (and not in the indexing phase). This way it should be more easily to implements.
So it will index: document, asset (even PDF text, IPTC, etc.) and object, like this is already the case for mysql.
If we want to provide some non indexed directory, we could add in the elasticsearch system configuration a multi-element href so we can drag-and-drop multiple paths to exclude from the indexing (will improve security so even if a developper make a wrong/faulty query, elasticsearch will not send those datas as they will not be indexed).

The elasticsearch database could then be used for multiple use case:
- for the backend search functionnality: faster and more powerfull
- could be use in front-end for search engine or any tool who need to do fast and powerfull "documentation" type query
- some in depth analysis on the data could be done using elasticsearch BI products
- big project where elasticsearch clustering could be used easily for replication/cluster

If this feature make sense, later we could use this base to provide some basic tools for front end (search engine with autocompletion and suggestion, etc.), like Paginator or Breadcrumb for instance which are every site good helper.
Or plugin could at least use the elasticsearch database to pull data.

I know this is a pretty big feature, but I think having native elasticsearch database will be a nice feature for developping fast and modern tools around it. It will be a nice "marketing feature" for Pimcore too : )

**Comment by Yivan** [comment]
As PHP layer to communicate with elasticsearch, the official wrapper could be used:
https://github.com/elastic/elasticsearch-php

**Comment by brusch** [comment]
Currently we have no intentions of integrating ElasticSearch into the core. 
We have already a prototype / early version of a plugin that utilizes ElasticSearch for searching & filtering in the backend. We're still working on it, but as soon as it is finished we'll release it.
