### ISSUE TITLE
[Bug]: Snippet publish fails with required input fields

### ISSUE THREAD

**Issue by akno77** [pimcore/pimcore#10584]
### Expected behavior

If you have a snippet template with a required input field like

`{{ pimcore_input('test', {'required': true}) }}`

save & publish is successfull with filled out input.

### Actual behavior

An Exception is thrown:

_**Prevented publishing document - missing values for required editables**_

This error seems to occur only on the first "Save & Publish". If you have the input field not required and publish and then make the field required the problem doesn't appear.

### Steps to reproduce

1. Create a snippet template with a required input field
2. Create a new snippet document based on the template
3. Enter data in the required input field
4. Click "Save & Publish"

**Comment by brusch** [comment]
Fixed by #10836
