### ISSUE TITLE
[Bug]: Warning: Undefined array key "default" when accessing admin page

### ISSUE THREAD

**Issue by sys4cad** [pimcore/pimcore#10594]
### Expected behavior

admin UI

### Actual behavior

Just after completing Skeleton Package  installation.
( i.e. COMPOSER_MEMORY_LIMIT=-1 composer create-project pimcore/skeleton my-project )

I got follwing error when accessing /admin and put the correct password of admin user.
I've noticed that default [] [] is passed and followig lines got exeption.
`$config = $masterConfig[$name];`

Warning: Undefined array key "default"
ExceptionLogs 1Stack Trace
ErrorException
in vendor/pimcore/pimcore/lib/Perspective/Config.php (line 257)

any comments and help will be appreciated.
FYI. demo installation works perfectly fine.

### Steps to reproduce

install pimcore(10.1.4) on ubuntu 18.04
mySQL : 8.0.26
php : 8.0.11
composer : 2.1.9
apache2 : 2.4.29

**Comment by dvesh3** [comment]
duplicate https://github.com/pimcore/pimcore/issues/10587

**Comment by sys4cad** [comment]
@dvesh3  thanks a lot!
