### ISSUE TITLE
Warning: Undefined array key "avif" | Pimcore 10.2.0

### ISSUE THREAD

**Issue by GaneshKandu** [pimcore/pimcore#10590]
### Expected behavior

Pimcore install works

### Actual behavior

![OnPaste 20211014-122009](https://user-images.githubusercontent.com/12833130/137266556-d1de7f03-cc78-4883-8c20-715b2eab2b07.png)

Getting this issue while installing pimcore 10.2.0 on this command ``./vendor/bin/pimcore-install``

in file ``vendor\pimcore\pimcore\lib\Image\Adapter\GD.php`` line no 421

setting error_reporting  to E_ERROR only also not works
```ini
error_reporting  =  E_ERROR
```

### Steps to reproduce

https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Installation.html

getting error on step 4. Launch Installer

**Comment by brusch** [comment]
fixed by #10592
