### ISSUE TITLE
[Bug]: Hide/show button lacks status

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#10596]
### Expected behavior

Clicking on the strike-through'd eye should toggle the buttons status (and and preferably there should also be a tooltip describing what it does).

### Actual behavior

Clicking on it works in that it will hide/show the brick once the content is saved, but it has no status indicator if it is actually on or off.

### Steps to reproduce

Click the eye in the button bar:
![image](https://user-images.githubusercontent.com/279826/137280468-a93c71d7-9ccd-45b6-b1bc-cd75597f8fdf.png)

**Comment by dvesh3** [comment]
Fixed by #10672
