### ISSUE TITLE
Error during update from 3.1.1 to 4.X - missing putPhpFile function

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#1059]
# Bug Report
As discussed in gitter before there is an error if you're updating a pimcore 3.1.1 installation to a recent 4.X installation.

Message:

> Install of update fails, see debug.log for more details.
> Error-Message:
> Fatal error: Call to undefined method Pimcore\File::putPhpFile() in /mypath/website/var/system/update/3615/scripts/postupdate.php on line 29

Overwriting the Pimcore\File.php with the most recent version multiple times during the update solved this problem.

@brusch said in gitter the issue would be fixed now but I just experienced it again so I thought I might open an issue here for it.

**Comment by brusch** [comment]
Oh, I'm sorry, I've fixed the bug only in the pre-update script but not in the post-update script.

**Comment by Cruiser13** [comment]
No problem, thanks for the fix! I'll retry the update now.
