### ISSUE TITLE
[Bug]: Dynamic Text Labels - Twig mode

### ISSUE THREAD

**Issue by milesimarco** [pimcore/pimcore#10602]
### Expected behavior

Ref. "Dynamic Text Labels" doc page: [https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Layout_Elements/Dynamic_Text_Labels.html](pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Layout_Elements/Dynamic_Text_Labels.html)

Example from doc page:
![image](https://user-images.githubusercontent.com/3340185/137300672-73fc96d6-ccd4-4bc6-81bc-2d3f2dcc659f.png)

I should be able to pass `object` and `data` to a text field and render information accordingly:

![image](https://user-images.githubusercontent.com/3340185/137300990-2f6c6d23-76c3-4b02-81bc-c5c166cb43d1.png)

### Actual behavior

The string `​{{ object.getFullpath() }}` is not evaluated and printed "as-is".

Both `object` and `data` seem not to be passed to renderer and both `{ % ... % }` and `{{ ... }}` are printed as plain HTML. 

![image](https://user-images.githubusercontent.com/3340185/137300897-9d7ced1d-60de-4a33-a7d6-9fa6e52264e2.png)

### Steps to reproduce

- Add a text field
- Configurate the field as explained in the documentation
- Output is in plain HTML and not parsed as JS/Twig

Best Regards,
M.

**Comment by dvesh3** [comment]
@milesimarco Hi, please make sure you enable source editing mode before writing any Twig syntax in html editor:
![image](https://user-images.githubusercontent.com/5137917/137306719-074dc59a-4a34-4a48-80bf-b7d8b59cebeb.png)

**Comment by dvesh3** [comment]
Improved documentation with source edit mode example https://github.com/pimcore/pimcore/commit/ee87b2aae150cab3bf4ce98be7f3a2fbac8dc49b

**Comment by milesimarco** [comment]
Still not working, already tried it.

![image](https://user-images.githubusercontent.com/3340185/137314401-8e99651e-180d-494a-976c-c3e4585317c4.png)

![image](https://user-images.githubusercontent.com/3340185/137314486-7ae10b77-1d01-4c86-8008-27405e5a4ec3.png)

(Ps. The documentation example image shows a wysiwyg editor)

**Comment by dvesh3** [comment]
@milesimarco Please note this feature is introduced in version 10.2, so if you are using older then Twig syntax will not work. Could you please confirm if you are on latest version 10.2.0 or 102.1?
