### ISSUE TITLE
[Bug]: Incorrect collation in column

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#10600]
### Expected behavior

`SELECT * FROM object_url_slugs WHERE slug = '🐌';` will not cause any errors.

### Actual behavior

`SELECT * FROM object_url_slugs WHERE slug = '🐌';` causes `pimcore.ERROR: PDOException: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_bin,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='`.

> Occurred on Pimcore 6, reproducible on Pimcore X.

Relates to:
- https://github.com/pimcore/pimcore/issues/6698,
    - which also references an [apparent patch via a script](https://gist.github.com/podarcis/cdce3371b8149e86924e9bb5f91e0961), 
    - and resulted in a [documentation update]( https://github.com/pimcore/pimcore/pull/6773/files), which is [no longer available](https://pimcore.com/docs/4.6.x/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/Witin_V4.html)

Caused by:
- a migration for existing instances https://github.com/pimcore/pimcore/blob/08d0fd81e419909d4cac0bed59f4b0682a96c2b6/bundles/CoreBundle/Resources/migrations/Version20200121095650.php#L23
- the installer for new instances https://github.com/pimcore/pimcore/blob/eecf55da3317d82cc5f2b8b80c1f57f5c3257d38/bundles/InstallBundle/Resources/install.sql#L950

### Steps to reproduce

- Install Pimcore X.
- Execute `SELECT * FROM object_url_slugs WHERE slug = '🐌';`.

> You can check the collation of the `slug` column by executing `SHOW FULL COLUMNS FROM object_url_slugs;`.

### Solution for existing projects
Execute `ALTER TABLE object_url_slugs MODIFY slug VARCHAR(765) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;`.

### Solution for new projects
Update this line: https://github.com/pimcore/pimcore/blob/eecf55da3317d82cc5f2b8b80c1f57f5c3257d38/bundles/InstallBundle/Resources/install.sql#L950

**Comment by dvesh3** [comment]
@passioneight Thanks a lot for your findings. Since you already know the solution, why not provide a PR 😉

**Comment by brusch** [comment]
Fixed by #10723
