### ISSUE TITLE
[Bug]: Calculated Value: UI very small label width

### ISSUE THREAD

**Issue by NikitchenkoSergey** [pimcore/pimcore#10603]
### Expected behavior

Label must have 100px width.

### Actual behavior

After create Calculated Value field in Data Object class Label has style="padding-right:5px;width:5px;"
Bug exists on  https://demo.pimcore.fun/admin/ : need create Panel in Car class, and create new Calculated Value field. ()
I check its on 10.2.1 and 10.0.9 - bug everywhere. Change field width or styles has no affect on label.

![Screenshot_20211014_135104](https://user-images.githubusercontent.com/7048202/137304781-6f6fc739-e540-40a9-af56-810b1f14f77f.png)

![Screenshot_20211014_135753](https://user-images.githubusercontent.com/7048202/137304765-4f124b43-4842-491b-88c3-5d5d3dff1777.png)

### Steps to reproduce

Settings -> Data Objects -> Classes 
Add new Calculated Value field to new Panel.

**Comment by NikitchenkoSergey** [comment]
Understood. If set Label width in Panel settings its works fine. I think this is not obvious behavior. It might be worth making the default width 100 for Calculated Value label.

**Comment by dvesh3** [comment]
Regression of https://github.com/pimcore/pimcore/pull/6895

**Comment by dvesh3** [comment]
Fixed by #10619
