### ISSUE TITLE
DeepCopy Performance

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#1061]
It seems that DeepCopy is very, very slow in cloning objects.

Here is a screenshot of a cachegrind report with DeepCopy enabled:

![bildschirmfoto 2016-11-22 um 16 45 03](https://cloud.githubusercontent.com/assets/5981845/20530443/ac3d3c90-b0d3-11e6-8724-313d74f191f5.png)

Here is a screenshot of a cachegrind report with DeepCopy disabled (commented out)

![bildschirmfoto 2016-11-22 um 16 50 53](https://cloud.githubusercontent.com/assets/5981845/20530502/d9e9c172-b0d3-11e6-9124-89bb579de4fb.png)

Its the same object loaded at the same time in each of the screenshots.

Executing the same request without profiling enabled (it is a frontend-request, so it also loads static contents):

 DeepCopy enabled | Time
------------ | -------------
yes | ~4s
no | ~1.8s

The Xdebug profiler also adds some overhead to execution time, since DeepCopy works recursive, it profiles every recursive call, and thats a lot. But: Here is a test without Profiling:

**Loading 50 Objects with some relations (Order Object with Items, Addresses, Customer, etc):**

**Execution Time**
With DeepCopy: 

 DeepCopy enabled | Time
------------ | -------------
yes | ~20s
no | ~980ms

**Loading ~300 Objects with some relations (Product):**

**Execution Time**
With DeepCopy: 

 DeepCopy enabled | Time
------------ | -------------
yes | ~35s
no | ~6s

All calls where made using ?nocache=true parameter, so Cache::save was called on each Object. I must confess that this system is not optimized!

I think this is a huge deal, it slows down Pimcore heavily.

There is already a Issue about performance reported to DeepCopy: https://github.com/myclabs/DeepCopy/issues/56

**Comment by brusch** [comment]
Better ideas?

**Comment by brusch** [comment]
See #997 & #1005

**Comment by dpfaffenbauer** [comment]
For example:

```php
$data = unserialize(serialize($data));
```

Should make a deep copy as well, but is much faster.

**Comment by brusch** [comment]
DeepCopy removed - closed - reopened original issue: #1005

**Comment by romainbessugesmeusy** [comment]
Hey there,
I noticed a big impact of DeepCopy in my import scripts. It happens when I save a Concrete object. 
<img width="417" alt="Capture d’écran 2019-11-25 à 13 50 15" src="https://user-images.githubusercontent.com/3127404/69541922-9e106700-0f8a-11ea-812b-f3652997b52d.png">

Do you have any workaround to suggest ?

**Comment by dpfaffenbauer** [comment]
disable versions

**Comment by aarongerig** [comment]
@romainbessugesmeusy this is what @dpfaffenbauer means:

```php
use Pimcore\Model\Version;

// ...

Version::disable();
$object->save();
Version::enable();
```

**Comment by romainbessugesmeusy** [comment]
Thank you both, it worked like a charm !
