### ISSUE TITLE
[Improvement]: Use package-manager (npm, ...) to install frontend dependencies

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#10614]
3rd party frontend dependencies should be installed using npm and packed by [Encore](https://symfony.com/doc/current/frontend/encore/installation.html). 

This includes all libraries **EXCEPT** ExtJS, because installing this via npm requires a registration at Sencha and is not very convenient. 

Examples: 
- Ace
- leaflet
- minipaint
- vrview
- Bootstrap (Ecommerce Bundle)

See also: #10606

**Comment by HaaseIT** [comment]
NPM/Yarn is not actually needed for this. You could add this without BC breaking issues I guess with:

https://github.com/oomphinc/composer-installers-extender

All you need to do is include tha package and some config for it in the compoer.json:

```
"extra": {
  "installer-types": ["bower-asset", "npm-asset"],
  "installer-paths": {
    "public/static/js/{$type}/{$name}/": [
      "type:bower-asset",
      "type:npm-asset"
    ]
  }
}
```

On another note, not really fitting this issue, but why not bundle symfony encore for js/scss compression?

**Comment by brusch** [comment]
Topics to consider: 
- https://github.com/eloquent/composer-npm-bridge
- how to deal with bundles, maybe something similar to [Ibexa](https://doc.ibexa.co/en/latest/administration/back_office/back_office_elements/importing_assets_from_bundle/#importing-assets-from-a-bundle)? ( [Example used in bundle](https://github.com/ezsystems/ezplatform-admin-ui/blob/2.3/src/bundle/Resources/encore/ez.config.js) )

**Comment by brusch** [comment]
This is the actual implementation how Ibexa does it: 
https://github.com/ibexa/core/pull/120

**Comment by robertSt7** [comment]
The current approach is to run `npm install` and the build manually in each repo and commit the assembled package with the respective versions. This has the advantage that the package versions are tested and no npm is needed to run Pimcore. 

Alternatively, `npm install` could also trigger with `composer update` and follow the approach of Ibexa and collect all the configs from the bundles and build them at once. This is very dynamic, as the config files from all bundles are added automatically, and everything is built from one place. 

Community input very much appreciated!!!

**Comment by dpfaffenbauer** [comment]
I'd be fine with that every bundle says you need to include these styles in your webpack config and be done with it.

**Comment by brusch** [comment]
@robertSt7 reopened, see [comment](https://github.com/pimcore/pimcore/pull/14182/files#r1111717827)
