### ISSUE TITLE
[Improvement]: Doctrine  DBAL v3

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#10613]
Should fix #5361 as well. 
Consider discussion here: #10648

See also: #12917

**Comment by goetas** [comment]
FYI, 3.3.0 has been released

**Comment by brusch** [comment]
@goetas thanks a lot 👍

**Comment by jdreesen** [comment]
Meanwhile, `doctrine/migrations` is now compatible with DBAL v3 and DBAL v2 will get out of maintenance in April (plus an additional year of security fixes).

See: [Sunsetting Doctrine DBAL 2](https://www.doctrine-project.org/2022/01/22/sunsetting-dbal-2.html)

**Comment by brusch** [comment]
Should be now ready to work on as #12917 got merged
