### ISSUE TITLE
Improvement: protocol for subsites and main domain.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1062]
Actually only the domain name can be configured for the subsite and main domain.

Some custom code or configuration need to be done to setup a protocol when working with multisite, some on http other on https, and even on classic one site with front in http but backend in https for security reason.

The website config could be used for instance by adding a protocol key so developer can rely on it. It works for custom code for the project, but for instance for emails it is not so easy as link are automaticaly generated by Pimcore when dragging assets.

Idea is to add a protocol select (with choices "(Empty) | http | https" in the subsite config panel and in the main domain system configuration. If empty it works as it work actually. But if filled this information will be used for emails when we drag asset images for instance (actually it set the protocol to the same than the back-end...). That's all, purpose is too keep it simple.

I think it will help to generate automatic URL in emails too for developpers, so they can rely on a common implementation of protocol for subdomains. See this issue, on a plugin generating automatic url: https://github.com/basilicom/pimcore-plugin-participation/issues/3 where defining the protocol will be left to the plugin configuration or some basic choice (force http), as the protocol information can not be found for the subsites.

Thanks.

**Comment by bbak** [comment]
I don't really see a (or understand the) use-case for this - at least not on a "per Site" Level. Schemes are not very dynamic, since some Webserver configuration has to be done. 
If you really need to lock-in to a scheme, hardcode it in the view. Or use some DocProperty for that case.
IMHO adding such switches just opens the door for misconfigurations by people with superficial knowledge.

**Comment by solverat** [comment]
> "..even on classic one site with front in http but backend in https for security reason"

I don't think this is a common need. Like Bruno said, it would be more confusing than helping.

**Comment by brusch** [comment]
I also think that the protocol shouldn't be handled within the application. 
I'll close this issue for now. Thanks anyway!
