### ISSUE TITLE
[Bug]: Server file explorer does not display sources correctly

### ISSUE THREAD

**Issue by MagPim** [pimcore/pimcore#10628]
### Expected behavior

Each opened file should display the complete content of the code;

### Actual behavior

The first opened file works correctly. When other files are opened after, they only display the first line <?php

### Steps to reproduce

On demo.pimcore.fun, use the server file explorer and open more than one file
![image](https://user-images.githubusercontent.com/39189262/137701057-c4855634-2965-493b-b2ed-8ccc5020a110.png)

**Comment by dvesh3** [comment]
Regression of https://github.com/pimcore/pimcore/pull/10546

**Comment by brusch** [comment]
Fixed by #10635
