### ISSUE TITLE
[Bug]: Configuration Properties Cache Issue

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#10624]
### Expected behavior

Creating & using config properties on the fly.

### Actual behavior

Instant created configuration flags are not available in same request.

### Steps to reproduce

Example static route (happend in some of our functional tests):

```php
$route = new Staticroute();
$route->setValues([
    'name'      => 'test_route',
    'pattern'   => '/([a-zA-Z0-9-_]*)\\/come-on$/',
    'reverse'   => '/{%%_locale}/come-on',
    'controller'    => '',
    'variables' => '_locale',
]);

$route->save();

$path = $this->container->get('router')->generate('test_route', [], false);

dump($path);
```
![image](https://user-images.githubusercontent.com/700119/137626705-e7035a55-3ad3-4a4c-b1ba-842cde0e6f15.png)

**Comment by dpfaffenbauer** [comment]
I don't see that as a problem honestly. It is the same behaviour as it is with Symfony Routes or any Symfony Configuration. Only issue: it is a BC break to how it worked with 10.0.

**Comment by solverat** [comment]
While this is absolutely true, and I would agree to ignore this, these properties (we're not only talking about routes, this affects every`LocationAwareConfigRepository` configuration [each configuration node in `var/config`]) are editable in backend and so this **may** could lead to funny side effects or at least to misinterpretation/wrong handling on dev side. I'm going to close this for now.

**Comment by brusch** [comment]
@solverat you could switch to `settings-store` backend for your tests, see: 
https://github.com/pimcore/pimcore/blob/10.x/tests/_bootstrap.php#L30
