### ISSUE TITLE
[Bug]: Open a DataObject Version(created on Pimcore 6.9) with ObjectBricks throws error

### ISSUE THREAD

**Issue by CountZero1981** [pimcore/pimcore#10620]
### Expected behavior

I should be able to open a DataObject version with ObjectBricks, created in an old version of Pimcore.

### Actual behavior

When I'm trying to open a DataObject Version with ObjectBricks, created in an old version of Pimcore, I'm getting an error: 
`Cannot assign null to property Pimcore\Model\DataObject\Objectbrick\Data\AbstractData::$doDelete of type bool`
After investigation, I see that DataObject Versions with ObjectBricks, created by Pimcore with versions before 27.04.2021, don't have default values for doDelete, so, they contain NULL values.

### Steps to reproduce

Create DataObject with ObjectBricks, create a version, using Pimcore before pull request 27.04.2021 (#8684), when this was fixed. Any Pimcore version after the pull request should raise an error trying to open a DataObject Version created earlier.  
a quick workaround should be like this:  
`find /home/ubuntu/pimcore/s3/versions/object -type f -name "*" -print0 | xargs -0 sed -i -e 's/doDelete";N;/doDelete";b:0;/g'`

**Comment by brusch** [comment]
Resolved by #10642
