### ISSUE TITLE
[Bug]: pagination not working correctly on Search Key windows of classification.

### ISSUE THREAD

**Issue by gobindpimcore** [pimcore/pimcore#10637]
### Expected behavior

 Pagination should work as it is working without searching any keyword.

if we are passing any keywords in 'searchfilter' total number always getting zero.

/admin/classificationstore/search-relations?_dc=1634552003519&storeId=10&searchfilter=a&page=1&start=1&limit=25

![paginationSearchKEY](https://user-images.githubusercontent.com/67306595/137729506-0aaf0ee1-3aa6-4f25-84b1-e3aa8d7e7ef3.png)

### Actual behavior

Total number not getting in json if we are passing any keyword as a searchfilter.
$list->getTotalCount(); always returning zero if it has keyword in searchfilter.

### Steps to reproduce

got to grid options and click on classification type fields and in pop up windows enter any keyword in search box and hit search.
and check json data you will see always total is zero.

**Comment by dvesh3** [comment]
Fixed by #10891
