### ISSUE TITLE
[Bug]: UI throwing error when a perspective has a space inside its name

### ISSUE THREAD

**Issue by emanmagni** [pimcore/pimcore#10632]
### Expected behavior

When you have a perspective with a space inside its name, you should be able to use and navigate the UI as before.

### Actual behavior

After updating to Pimcore 10.2, if a perspective has a space inside its name, the UI throws the following error:

`Uncaught Error: Invalid component "itemId": "pimcore_menu_file_perspective_My Perspective"`

Probably caused by #10126, as HTML elements cannot have space.

A solution would be to replace all spaces inside the perspective names with hyphens or underscores.
If this seems a good solution to you, I can open a PR.

### Steps to reproduce

1. Change your perspectives.php file and add a perspective with a key containing one or more spaces
2. Refresh the UI. You won't be able to click on any toolbar entry.

Not reproducible neither on https://demo.pimcore.fun/ as its version is 10.1.x-dev nor on https://demo.pimcore.com/ as the "superuser" user doesn't have permissions to explore server files.

**Comment by brusch** [comment]
Fixed by #10633
