### ISSUE TITLE
[Bug]: Documentation not working - 403 Forbidden error

### ISSUE THREAD

**Issue by laurenz-glueck** [pimcore/pimcore#10643]
### Expected behavior

Not sure if you are already aware of this issue (I didn't found a Github issue for that) but when I opening the official Pimcore documentation at [https://pimcore.com/docs/pimcore/current](https://pimcore.com/docs/pimcore/current) there should be no "403 Forbidden" error - I guess 😜

### Actual behavior

I'm getting a 403 Forbidden error (testet on different browsers and WiFi / Cellular network):

![image](https://user-images.githubusercontent.com/2734232/137800273-d438d09d-42e6-448b-aa0e-182250d6f110.png)

### Steps to reproduce

Go to [https://pimcore.com/docs/pimcore/current](https://pimcore.com/docs/pimcore/current) 😉

**Comment by fashxp** [comment]
should work again. thx for reporting

**Comment by laurenz-glueck** [comment]
@fashxp Thanks for the fast reaction! It's working again 👍🏼
