### ISSUE TITLE
Please provide configuration for enabling/disabling the system caches.

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#1064]
While developing I'd like to disable the system caches to have the configurations up-to date always.
The DEV-MODE is really aggressive.

**Comment by cleggypdc** [comment]
Hi,

DEV-MODE is only for debugging core issues and shouldn't be enabled.

For developing your own solutions use PIMCORE_DEBUG mode.

You can also disable system caching via 
\Pimcore\Cache::disable();

Which you can place in your startup.php file in the pimcore configuration directory.

Also look at configuring different environments which should help configure pimcore for develop/staging/production 

https://www.pimcore.org/docs/latest/Deployment/Multi_Environment.html
