### ISSUE TITLE
No preview for office-files (.xls(x), .doc(x)) [Bug]: 

### ISSUE THREAD

**Issue by HeicoSindelItShapes** [pimcore/pimcore#10645]
### Expected behavior

After uploading office-files and running maintenance job a preview should be possible

### Actual behavior

Only Custom Metadata, Probs, ... are shown - for both xls and xlsx

### Steps to reproduce

Upload a Excel File to a folder in assets - wait at least 5 mins (for the maintenance job) and try to "open" the file

**Comment by brusch** [comment]
For me it works just fine ... tested with latest `10.2`.

**Comment by HeicoSindelItShapes** [comment]
I have updated the system from 10.0.8 to 10.2.2 - and it's still not working - also the maintenance jobs are configured as discribed; also reinstalled the libreoffice modules as discribed - any other ideas?

**Comment by brusch** [comment]
System requirements are all marked as ok?

**Comment by HeicoSindelItShapes** [comment]
![image](https://user-images.githubusercontent.com/92674413/138443067-275feda3-9b8c-4110-b365-cb833dbdb2d7.png)

**Comment by brusch** [comment]
That looks good ... hmm, yeah well, no real idea then. 🤔

**Comment by HeicoSindelItShapes** [comment]
<html>
<body>


Couldn't convert document to PDF: /_Internal Files/SAP-FIles/Categories_reduced.xlsx with the command: ''/usr/bin/soffice' '--headless' '--nologo' '--nofirststartwizard' '-env:UserInstallation=file:///var/www/pimcorex/var/tmp/libreoffice' '--norestore' '--convert-to' 'pdf:writer_web_pdf_Export' '--outdir' '/var/www/pimcorex/var/tmp' '/var/www/pimcorex/public/var/assets/_Internal Files/SAP-FIles/Categories_reduced.xlsx''
--
ERROR13:21:46 | pimcore | Couldn't create image-thumbnail of document /_Internal Files/SAP-FIles/Categories_reduced.xlsx
ERROR13:21:46 | pimcore | Exception: Couldn't convert document to PDF: /_Internal Files/SAP-FIles/Categories_reduced.xlsx with the command: ''/usr/bin/soffice' '--headless' '--nologo' '--nofirststartwizard' '-env:UserInstallation=file:///var/www/pimcorex/var/tmp/libreoffice' '--norestore' '--convert-to' 'pdf:writer_web_pdf_Export' '--outdir' '/var/www/pimcorex/var/tmp' '/var/www/pimcorex/public/var/assets/_Internal Files/SAP-FIles/Categories_reduced.xlsx'' in /var/www/pimcorex/vendor/pimcore/pimcore/lib/Document/Adapter/LibreOffice.php:166 Stack trace: #0 /var/www/pimcorex/vendor/pimcore/pimcore/lib/Document/Adapter/LibreOffice.php(95): Pimcore\Document\Adapter\LibreOffice->getPdf() #1 /var/www/pimcorex/vendor/pimcore/pimcore/models/Asset/Document/ImageThumbnail.php(101): Pimcore\Document\Adapter\LibreOffice->load() #2 /var/www/pimcorex/vendor/pimcore/pimcore/models/Asset/Thumbnail/ImageThumbnailTrait.php(115): Pimcore\Model\Asset\Document\ImageThumbnail->generate() #3 /var/www/pimcorex/vendor/pimcore/pimcore/models/Asset/Thumbnail/ImageThumbnailTrait.php(99): Pimcore\Model\Asset\Document\ImageThumbnail->getPathReference() #4 /var/www/pimcorex/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Asset/AssetController.php(1484): Pimcore\Model\Asset\Document\ImageThumbnail->getStream() #5 /var/www/pimcorex/vendor/symfony/http-kernel/HttpKernel.php(156): Pimcore\Bundle\AdminBundle\Controller\Admin\Asset\AssetController->getDocumentThumbnailAction() #6 /var/www/pimcorex/vendor/symfony/http-kernel/HttpKernel.php(78): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #7 /var/www/pimcorex/vendor/symfony/http-kernel/Kernel.php(199): Symfony\Component\HttpKernel\HttpKernel->handle() #8 /var/www/pimcorex/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle() #9 {main}


</body>
</html>

**Comment by brusch** [comment]
Run the command manually and see what LibreOffice has to say ...

**Comment by HeicoSindelItShapes** [comment]
it was a permission problem - i have to check what changes the "ownership" sometimes... thx
