### ISSUE TITLE
[Bug]: Regression with web2print : no pdf gets generated for print documents

### ISSUE THREAD

**Issue by MagPim** [pimcore/pimcore#10655]
### Expected behavior

Generate & preview pdf documents for a print document or container should produce a pdf, which ever the tool used (PDFreactor, WkHtmlToPdf...)

### Actual behavior

The progression bar remains to 0% and nothing gets generated.
![image](https://user-images.githubusercontent.com/39189262/137951671-9ca19cfc-1870-43e1-af4d-1693fdd054ae.png)

### Steps to reproduce

Problem is found on new Pimcore installation using 10.2.x and ALSA on the demo https://demo.pimcore.fun/.

**Comment by brusch** [comment]
@MagPim is the maintenance process running properly? 
The generation of PDFs is now done in a messenger worker, which is automatically started by `bin/console pimcore:maintenance`. However we recommend to run the workers seperately, see: 
https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Installation.html#page_5-Maintenance-Cron-Job

Regarding demo: our public demo instances do not have the maintenance script running, therefore generating PDFs doesn't work (for the moment).

**Comment by MagPim** [comment]
Thanks a lot for this response @brusch, I indeed did not set up maintenance on the system where I performed the tests.
I just did but unfortunately, I still have the same issue. I wil nevertheless investigate a little more...

**Comment by iidaloiki** [comment]
@brusch Maintenance function throws following error:

> 15:09:34 CRITICAL  [messenger] Error thrown while handling message Pimcore\Messenger\GenerateWeb2PrintPdfMessage.
Removing from transport after 3 retries.
Error: "No handler for message "Pimcore\Messenger\GenerateWeb2PrintPdfMessage"."
[
  "message" => Pimcore\Messenger\GenerateWeb2PrintPdfMessage^ { …},
  "class" => "Pimcore\Messenger\GenerateWeb2PrintPdfMessage",
  "retryCount" => 3,
  "error" => "No handler for message "Pimcore\Messenger\GenerateWeb2PrintPdfMessage".",
  "exception" => Symfony\Component\Messenger\Exception\NoHandlerForMessageException^ { …}
]

Could it be related to [this commit](https://github.com/pimcore/pimcore/commit/7bebe9f3e32ba9ab9dbcd734e1a8a4f19c653126) that changes the background process handling?

Any ideas how to fix?

**Comment by blankse** [comment]
@iibs @brusch Seems there is the "messenger.message_handler" tag in the definition missing. I created an PR. Can you test it?

**Comment by iidaloiki** [comment]
@blankse That seemed to fix it for me at least. Thank you very much ☺️

**Comment by brusch** [comment]
Fixed by #10765
