### ISSUE TITLE
[Improvement]: Use foreign keys for `ON DELETE` whenever possible

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#10654]
### Improvement description

- [x] `assets_metadata.cid` ( #11072 ) 
- [x] `documents_*` tables (#11236)
- [ ] ~~`edit_lock.cid/ctype`~~ not possible as reference is based on multiple tables
- [ ] ~~`dependencies` (source & target - if possible)~~
- [ ] ~~`element_workflow_state.cid/ctype`~~
- [x] `gridconfig_favourites` (#11219)
...

I'd go for a PR for each entity to make reviewing easier.

**Comment by kanevbg** [comment]
I was searching for info related to why pimcore does not have any foreign keys for the objects and found that improvement issue, which interestingly still does not mention objects.
Can you provide some info on why there is no FK for ON DELETE for objects.
I'd like being able to truncate object_X table, where X is the id of the class and all the related data for these object to be deleted from DB.
