### ISSUE TITLE
[Bug]: /vendor/pimcore/tests folder disappears after upgrading to newest version

### ISSUE THREAD

**Issue by AlekMosingiewicz** [pimcore/pimcore#10671]
### Expected behavior

/vendor/pimcore/pimcore/tests remains, so that local integration tests that rely on the /vendor/pimcore/pimcore/tests/_support/Util/Autoloader.php class pass.

### Actual behavior

/vendor/pimcore/pimcore/tests/ folder disappears entirely

### Steps to reproduce

run the following command with Pimcore v.10.1.1 installed:
`composer require pimcore/data-importer --with-all-dependencies`
This will upgrade Pimcore version and remove the tests folder.

**Comment by dpfaffenbauer** [comment]
why would you need to have the pimcore tests?

**Comment by brusch** [comment]
See #10226
