### ISSUE TITLE
IE11: Asset tree's context menu behing PDF preview

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#1067]
see screenshot.
- only IE11
- not reproducible in Chrome
![preview](https://cloud.githubusercontent.com/assets/6142086/20556873/4e005216-b169-11e6-83c0-c64d6c5c97aa.png)

**Comment by brusch** [comment]
Unfortunately there's no solution for that. IE11 uses external plugins for displaying PDFs (Acrobat, ...).
