### ISSUE TITLE
[Bug][Workflow Notification] Default html mail sent as text mail 

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#10676]
### Expected behavior

html mail sent as html mail

### Actual behavior

sent as text mail 

![image](https://user-images.githubusercontent.com/8792145/138516502-ee23e17b-0509-4a58-91cd-45ff255d1248.png)

### Steps to reproduce

create workflow with mail notification for a transition

**Comment by dvesh3** [comment]
Fixed by #10704
