### ISSUE TITLE
QuantityValue field without default unit results in error

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#1068]
### Expected behavior 
When using a Quantity Value field with no defined default unit the object should be editable and the unit should be selectable.
  
### Actual behavior  
Object does not open
  
### Steps to reproduce  
* Create Quantity Value Unit
* Create class, add Quantity Value field and assign created unit as valid unit
* Create object of this class -> cannot be opened

**Comment by weisswurstkanone** [comment]
thx. fixed in build 4010
