### ISSUE TITLE
XLIFF Export: ContentMasterDocument exports wrong content

### ISSUE THREAD

**Issue by dominikschnieper** [pimcore/pimcore#1069]
# Bug Report / Question
XLIFF export of a document contains the values of the inherited contentmasterdocument even if the value is overridden inside the document. 

### Expected behavior 
If an element is overridden it should be contained in the xliff export so that it can be translated. contentmaster documents might even be totally ignored as they are exported with the original document and stay inherited?

### Actual behavior
Wrong data of contentmasterdocument is exported in xliff and overridden elements not.

### Steps to reproduce
- Create a document
- Create a second document inherited from the first and override some fields
- Make a copy in another language and export xliff
- check xliff file of inherited document

### Code example
- pimcore/modules/admin/controllers/TranslationController.php Line:645
$doc = $element;
// get also content of inherited document elements
while ($doc) {
    if (method_exists($doc, "getElements")) {
        $elements = array_merge($elements, $doc->getElements());
    }

    if (method_exists($doc, "getContentMasterDocument")) {
        $doc = $doc->getContentMasterDocument();
    } else {
        $doc = null;
    }
}
// your code
$elements = array_merge($elements, $element->getElements());

**Comment by brusch** [comment]
Should be solved by #3248
