### ISSUE TITLE
[Bug]: Grid/list selection looks like every other is selected

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#10698]
### Expected behavior

All selected items in a grid/list view should have the same highlight colour.

### Actual behavior

Only the small checkbox on the left indicates every second selected item. This is especially "treacherous" for the first or last item selected (the ones in-between can be more easily assumed to be selected):

![image](https://user-images.githubusercontent.com/279826/138905129-8c6a5d33-5223-4cc5-b282-06808f99e43c.png)

### Steps to reproduce

See screenshot above

**Comment by NiklasBr** [comment]
The zebra striping is also a bit broken on the Email log page: 
![image](https://user-images.githubusercontent.com/279826/141785146-393625e5-e858-4404-bf0d-a80f3706a2cd.png)

**Comment by NiklasBr** [comment]
This is still relevant

**Comment by blankse** [comment]
@NiklasBr I created a PR https://github.com/pimcore/pimcore/pull/11833
Can you test it?

**Comment by NiklasBr** [comment]
Nice, I'll test it this week @blankse

**Comment by NiklasBr** [comment]
@blankse looks great, only one issue as far as I can see:
- Assets in lists ✔️ 
- DataObject lists ✔️ 
- Versions ✔️ 
- Website Settings ✔️ 
- Email errors: ⚠️ selection not visible
- HTTP Errors ✔️ 
- Notes & events ✔️ 
- Bundles & Bricks ✔️ 
- Recycle bin ✔️

**Comment by blankse** [comment]
@NiklasBr I fixed also the email error grid now. Thanks for review.

**Comment by mcop1** [comment]
@blankse I noticed that the problem occurs in the "search & move" dialog too, e.g.:
![image](https://user-images.githubusercontent.com/89011527/162389960-5a1e5caf-dff8-4c98-be70-06846b91bf9e.png)

Do you mind having a look, please?

**Comment by blankse** [comment]
@mcop1 "search & move" dialog looks good at me. Do you clear the browser cache?
![image](https://user-images.githubusercontent.com/998558/162578039-1180f9a0-deca-4498-a353-2a9b30a86c1d.png)

**Comment by mcop1** [comment]
> @mcop1 "search & move" dialog looks good at me. Do you clear the browser cache? ![image](https://user-images.githubusercontent.com/998558/162578039-1180f9a0-deca-4498-a353-2a9b30a86c1d.png)

Sorry, my bad, it is working, thank you 👍
