### ISSUE TITLE
[Improvement]: Check CSRF token for write requests only

### ISSUE THREAD

**Issue by damijank** [pimcore/pimcore#10693]
### Improvement description

The HEAD operation should not be checked for a CSRF token.

Some external software, we've encountered the issue with Excel, makes HEAD requests to embedded links. Our client uses Excel for some internal documents, and embeds deeplinks into their sheets. Our Sentry is lit up with exception reports over CSRF token issues: `Detected CSRF Attack! Do not do evil things with pimcore ... ;-)` on URIs like `/admin/login/deeplink?object_...`. The thing is, these are requests with http HEAD method, and any READ requests should not be checked against the CSRF token - the token is not provided anyway.

**Comment by dvesh3** [comment]
Fixed by #10694
