### ISSUE TITLE
[Bug]: Close Admin on session expired

### ISSUE THREAD

**Issue by damijank** [pimcore/pimcore#10697]
### Expected behavior

When the session expires, the Admin interface should be closed and the Login form shoud be displayed.

### Actual behavior

When the session expires, the Admin interface repeatedly pops-up a modal `Access Denied!` stating
`You don't have sufficient permissions to open the element or perform the desired action.`

### Steps to reproduce

1. Log into Admin interface in first tab
2. Open Admin interface in second tab
3. Log out of Admin in second tab
4. Close second tab
5. Wait up to 30 seconds in first tab (for `notification/find-last-unread` XHR request)
6. The modal `Access Denied!` appears

Instead, the Login form should be displayed, just like it happens when a session expires "naturally".

The complement to the `notification/find-last-unread` requests is the `misc/ping` request which only begins occurring a minute before the SessionID cookie expires, and causes the Admin interface to be closed accordingly. In the above described scenario this does not happen because the SessionID cookie is not near the end of it's life, it is even replaced with a new one because of the logout in the second tab.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
