### ISSUE TITLE
[Bug]: Grid/list view fails to become scrollable due to img lazy-loading

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#10699]
### Expected behavior

When opening a grid/list view and it should be possible to scroll all the way down.

### Actual behavior

It appears that the lazy-loading of images interfere with how ExtJS calculates the content height.

### Steps to reproduce

Navigate assets in list view:
![image](https://user-images.githubusercontent.com/279826/138905583-a467b24e-f88a-4042-9fb2-e5ed5d747419.png)

**Comment by dvesh3** [comment]
Fixed b #10709
