### ISSUE TITLE
[Bug]: Refresh CSRF token in Admin on session change (and logged in again)

### ISSUE THREAD

**Issue by damijank** [pimcore/pimcore#10700]
### Expected behavior

When the session changes, the Admin interface should detect it and react properly, i.e. by refreshing the CSRF token.

### Actual behavior

When the session changes, the already open Admin interface remains defunct for any WRITE operations, but does not detect it until an actual WRITE operation is being executed.

### Steps to reproduce

1. Log into Admin interface in first tab
2. Open Admin interface in second tab
3. Log out of Admin in second tab
4. Log back in again in second tab
5. Switch to the first tab
6. Any write requests will produce a CSRF error, i.e. an Add Asset operation

![image](https://user-images.githubusercontent.com/19417312/138910251-6af3eef8-c85a-4bae-9177-40ff1a276420.png)

This can be a similar functionality to the Login form's _"refresh CSRF token"_, except this happens on **tab activate** AND the **session ID has changed** AND the session is an **admin user session**, i.e. `((bool) getAdminUser() === true)`.

It would probably be a good idea to check even if the user is (and their permissions?) are the same as before... the Admin UI elements certainly depend on the user, at least the avatar. Maybe he had the "My profile" tab open, too?

If all else fails, maybe completely reload the Admin interface alltogether, without checking for unsaved changes at all? Yes, this could result in data loss, but who's fault is it if someone leaves the Admin open for too long, and lets someone else to login in another tab? Pimcore should not worry about that, IMO.

**Comment by fashxp** [comment]
duplicate of https://github.com/pimcore/pimcore/issues/10740
