### ISSUE TITLE
[Bug]: Can't open DWG file

### ISSUE THREAD

**Issue by lmeazza** [pimcore/pimcore#10708]
### Expected behavior

- Open an asset with dwg extension. (DEBUG MODE)

### Actual behavior

- Can't open an asset with dwg extension without any error. ( Error appears only in debug mode)

### Steps to reproduce

- Set Debug mode on.
- Load an asset with dwg extension.
- Open an asset with dwg extension.
![STEP_1](https://user-images.githubusercontent.com/63634753/139051343-9622a180-4d33-4b87-bc4f-bc96f3a3f81a.PNG)
![STEP_2](https://user-images.githubusercontent.com/63634753/139051394-c346d0df-ab3c-4346-9b97-e99a08aaf8c4.PNG)
![STEP_3](https://user-images.githubusercontent.com/63634753/139051401-7ca8c00a-7914-4fe2-939c-db7b44a25814.PNG)
)
![STEP_4](https://user-images.githubusercontent.com/63634753/139051405-92c978a3-e16d-408b-9b2c-6c055da15dfc.PNG)

**Comment by brusch** [comment]
Ficed by #10711
