### ISSUE TITLE
prevent CLI Commands to be run as "wrong" user (or warn at least)

### ISSUE THREAD

**Issue by bbak** [pimcore/pimcore#1071]
## Feature description 
CLI Commands - especially those that write files to `website/var/**/*` - should emit at least a warning when run as as different User as the SAPI (fpm, CGI, mod_php), since files created by the CLI User may not be (over-)writable by the SAPI User - running CLI Commands as _root_ is the most obvious case.

Since it's virtually impossible to find out the SAPI User from CLI, a comparison of the Owner of directory "website/var" (which should be owned by the SAPI User) with the current User should be sufficient. 

On POSIX-compliant Systems this should do the trick:
```
$fileOwner = posix_getpwuid(fileowner('website/var'))['name'];
// should be the same as: the currently loggedin user
$currentUser = exec('whoami');
// or even better: the owner of the current process.
$processOwner = posix_getpwuid(posix_geteuid())['name'];
```

Doesn't work on Windows, since:
- fileowner() reports (int) 0 way too often.
- posix_* doesn't exist

On Windows perhaps some RegEx Magic on the Output of `exec("dir /q website/var");` to get the Owner of the directory and a comparison to the Output of `exec("whoami")` may be sufficient.
  
P.S.: Drop me a line, if you want me to write such a function that returns a (bool) false, if the check fails. I just have no clue where it has to be integrated in Pimcore\Console\*

**Comment by brusch** [comment]
I really like the idea! 
I think the check should be done right in the CLI startup script: `pimcore/cli/startup.php` but of course we could put the function itself into `Pimcore\Tool\Console`.

**Comment by bbak** [comment]
Haha, obviously I was not the first one with such method in mind. While digging through the code I stumbled upon `Pimcore\Tool\Console::checkExistingUser($allowedUsers = [])`. This already implements the POSIX-compatible approach I outlined above.

Using a search for "checkExistingUser" in all .php Files revealed, that this isn't called anywhere in the code (assuming the call is not generated dynamically).

I'll try to make that function Windows aware, so it can be called e.g. from `pimcore/cli/startup.php`.

**Comment by Cruiser13** [comment]
A short note on windows servers at this point. Our Windows Server Systems do run the PHP as IUSR (which needs writing permissions on /pimcore and /website/var therefor). If commands are executed in the background, they'll be run as the IIS App Pool Identity Instance (e.g. IIS AppPool\DefaultAppPool  ) which does also needs write permissions to /website/var - for example to generate PDFs using the Web2Print mechanism.

Our default check for something like this is a two file check. We execute file test.php which looks like this:
```php
$commandWrapped = "cmd /c php C:\wwwfolder\whoami.php > C:\wwwfolder/website/var/log\test.log 2>&1";
$WshShell = new \COM("WScript.Shell");
$reply = $WshShell->Run($commandWrapped, 1, true);
echo $reply;
```
The called whoami.php looks like this:
```php
echo shell_exec('whoami');
```

On a Windows Server 2012 in standard configuration this will return **iis apppool\defaultapppool**

It's important to know that direct exec()s run as IUSR while exec()s calling php first will run the IIS App Pool Instance instead.
This php file will start Microsoft Paint as IUSR with IUSR write permissions:
```php
$commandWrapped = "cmd /c mspaint";
$WshShell = new \COM("WScript.Shell");
$reply = $WshShell->Run($commandWrapped, 1, true);
echo $reply;
```

**Comment by bbak** [comment]
Looks like I was a bit too optimistic.

If the underlying filesystem supports ACL's, it may of course be perfectly valid if the Owner of the CLI Process differs from the Owner of the HTTP/FPM/CGI Process.

@Cruiser13 You're running IIS, right? When running Apache on Windows, it runs as [LocalSystem if installed as Service](https://httpd.apache.org/docs/current/platform/windows.html); and I assume it runs as the user that started the daemon, when running from CMD (?). And I've no clue, what Nginx, Litespeed and so on do on Windows.

It seems the only solution consists of 2 Steps: 
a) The HTTP/FPM/CGI Process has to regularly dump its Process-Owner somewhere (Cache, system.php, a file in website/var/tmp).
b) When starting a CLI Process, the CLI generates a temporary file, e.g. in website/var/tmp and checks, if the User dumped in Step a) can overwrite that file - which is still some effort when taking ACL Filesystems into account even on Un*x.

Btw. I think I found a reliable way to find the Username executing a PHP-CLI Process on Windows:
`echo (shell_exec('tasklist /V /FO csv /FI "PID eq '.getmypid().'"'));` 

That dumps something like this:
```
"Abbildname","PID","Sitzungsname","Sitz.-Nr.","Speichernutzung","Status","Benutzername","CPU-Zeit","Fenstertitel"
"php.exe","3292","Console","5","12.432 K","Unknown","DOMAIN\username","0:00:00","Nicht zutreffend"
```

**Comment by Cruiser13** [comment]
@bbak yes our Windows Servers are using IIS instead of apache.

**Comment by brusch** [comment]
So far it seems that there's no generic way how to solve this, so I'm going to close this issue for now. But of course we'd still accept PRs if someone finds a proper solution.
