### ISSUE TITLE
[Bug]: Assets - opening .zip file causes infinite requests

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#10716]
### Expected behavior

Zip Asset should be open

### Actual behavior

Infinite requests on opening zip asset and asset doesn't open 
![image](https://user-images.githubusercontent.com/5137917/139207853-5fef272c-6151-4045-824a-2907c58e1065.png)

### Steps to reproduce

Steps: 
Upload & Open a zip file in Admin interface

**Comment by dvesh3** [comment]
Regression of https://github.com/pimcore/pimcore/pull/9700

**Comment by brusch** [comment]
Fixed by #10720
