### ISSUE TITLE
[Bug]: In 10.2 pimcore:maintenance no longer excludes excludedJobs

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#10714]
### Expected behavior

The command `bin/console maintenance --excludedJobs=logmaintenance,cleanuplogfiles,imageoptimize` should not do any of the following:
- logmaintenance
- cleanuplogfiles
- imageoptimize

### Actual behavior

They are all being executed anyway

### Steps to reproduce

Run the command in 10.1:
 - All the above jobs are excluded as expected

Run the command in 10.2:
- All jobs are executed

**Comment by dvesh3** [comment]
Sorry, not able to reproduce on 10.2.3:
![image](https://user-images.githubusercontent.com/5137917/139232396-a894c3ba-4dab-4320-844e-bdfdbc4e0a6a.png)

**Comment by NiklasBr** [comment]
This happens with the command above.
```
08:26:11 ERROR     [messenger] Error thrown while handling message Pimcore\Messenger\OptimizeImageMessage. Sending for retry #2 using 2000 ms delay. Error: "Handling "Pimcore\Messenger\OptimizeImageMessage" failed: The process "'/bin/pngout' '/var/www/pimcore/var/tmp/temp-file-617a424668e8c-7f6aaeb387ce1b334eac595d7b656b.png' '/var/www/pimcore/var/tmp/temp-file-617a424790a98-cd45abc1d9a20fc3389aa7f64bd6ad.png'" exceeded the timeout of 60 seconds." ["message" => Pimcore\Messenger\OptimizeImageMessage { …},"class" => "Pimcore\Messenger\OptimizeImageMessage","retryCount" => 2,"delay" => 2000,"error" => "Handling "Pimcore\Messenger\OptimizeImageMessage" failed: The process "'/bin/pngout' '/var/www/pimcore/var/tmp/temp-file-617a424668e8c-7f6aaeb387ce1b334eac595d7b656b.png' '/var/www/pimcore/var/tmp/temp-file-617a424790a98-cd45abc1d9a20fc3389aa7f64bd6ad.png'" exceeded the timeout of 60 seconds.","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException { …}]
08:28:12 ERROR     [messenger] Error thrown while handling message Pimcore\Messenger\OptimizeImageMessage. Sending for retry #3 using 4000 ms delay. Error: "Handling "Pimcore\Messenger\OptimizeImageMessage" failed: The process "'/bin/pngout' '/var/www/pimcore/var/tmp/temp-file-617a42bf0a60b-429736004095ea58c39f658dd73ba3.png' '/var/www/pimcore/var/tmp/temp-file-617a42c032741-ff08d7dee65f21de42848a81e49ff8.png'" exceeded the timeout of 60 seconds." ["message" => Pimcore\Messenger\OptimizeImageMessage { …},"class" => "Pimcore\Messenger\OptimizeImageMessage","retryCount" => 3,"delay" => 4000,"error" => "Handling "Pimcore\Messenger\OptimizeImageMessage" failed: The process "'/bin/pngout' '/var/www/pimcore/var/tmp/temp-file-617a42bf0a60b-429736004095ea58c39f658dd73ba3.png' '/var/www/pimcore/var/tmp/temp-file-617a42c032741-ff08d7dee65f21de42848a81e49ff8.png'" exceeded the timeout of 60 seconds.","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException { …}]
08:29:17 CRITICAL  [messenger] Error thrown while handling message Pimcore\Messenger\OptimizeImageMessage. Removing from transport after 3 retries. Error: "Handling "Pimcore\Messenger\OptimizeImageMessage" failed: The process "'/bin/pngout' '/var/www/pimcore/var/tmp/temp-file-617a43005c9bb-b0bd21aef66cdc32029aa3f4c4d819.png' '/var/www/pimcore/var/tmp/temp-file-617a430187a58-d5e5cfdbe3f8b42956f5b4b6bb63cd.png'" exceeded the timeout of 60 seconds." ["message" => Pimcore\Messenger\OptimizeImageMessage { …},"class" => "Pimcore\Messenger\OptimizeImageMessage","retryCount" => 3,"error" => "Handling "Pimcore\Messenger\OptimizeImageMessage" failed: The process "'/bin/pngout' '/var/www/pimcore/var/tmp/temp-file-617a43005c9bb-b0bd21aef66cdc32029aa3f4c4d819.png' '/var/www/pimcore/var/tmp/temp-file-617a430187a58-d5e5cfdbe3f8b42956f5b4b6bb63cd.png'" exceeded the timeout of 60 seconds.","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException { …}]
```

**Comment by dpfaffenbauer** [comment]
@NiklasBr I think the problem here is that these tasks got added by either the regular maintenance cron job or some where from inside Pimcore. The Maintenance Command now uses Symfony Messenger to handle this stuff, messenger doesn't care which tasks should be skipped and which not, it just executes what still in the queue.

**Comment by NiklasBr** [comment]
@dpfaffenbauer do you know how these gets added to the queue? I can't find anything on https://pimcore.com/docs

**Comment by dpfaffenbauer** [comment]
with the maintenance command

**Comment by NiklasBr** [comment]
We added `imageoptimize` to `--excludedJobs` about a year ago because it was too slow on an `m5.large` instance and started throwing similar timeout errors. Moving to a larger instance did not help a lot, so it has stayed excluded. Is there something we are missing here? How do we prevent them from being added by the maintenance job?

**Comment by dvesh3** [comment]
We moved Image Optimizer from Maintenance tasks to Symfony Messenger (Is the plan to move other task slowly to Messenger) https://github.com/pimcore/pimcore/pull/10461

and that is the reason for Niklas, the job is not skipped anymore as it is dispatched here https://github.com/pimcore/pimcore/pull/10461/files#diff-16840b1fd40929e8fda46a67eae733c84fc71dc91da6a38097ba58b5da0c321cR406-R407 and served directly by the `Messenger::consume` command run by MaintenanceCommand.

With https://github.com/pimcore/pimcore/pull/10725, we are working  on respecting the `--excludedJobs` & `--job` options passed in maintenance, so that these jobs "Messages" are skipped in current consume worker.

**Comment by NiklasBr** [comment]
Thanks @dvesh3

**Comment by brusch** [comment]
See  #11121
