### ISSUE TITLE
[Improvement]: Implement DataObject::getByKey

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#10710]
### Improvement description

analog to all the other DataObject::getBy* methods

will solve https://github.com/pimcore/data-importer/issues/104

**Comment by danielczestki** [comment]
@fashxp is there a plan for add getByKey method in the near time. I need it very much :)
Is it possible to add it to 6.9 PimCore too ?

**Comment by brusch** [comment]
See #10712

**Comment by danielczestki** [comment]
@brusch #10712 merge is for 10.X not 6.9

**Comment by brusch** [comment]
@danielczestki 6.9 is end of life.

**Comment by danielczestki** [comment]
Yes I know but I need it in 6.9 ? What should I do then ? @brusch 
Using local composer patches ? will it work with pimcore  ?

**Comment by brusch** [comment]
@danielczestki yes, of course that works

**Comment by brusch** [comment]
Resolved by #10712
