### ISSUE TITLE
[Bug]: Auto save for object folders

### ISSUE THREAD

**Issue by sevarozh** [pimcore/pimcore#10724]
### Expected behavior

do not run auto-save for types not supporting versions

### Actual behavior

auto save also uses folders.
https://github.com/pimcore/pimcore/blob/10.x/bundles/AdminBundle/Resources/public/js/pimcore/element/abstract.js:220
`        //do not run auto-save for types not supporting versions
        let nonVersionTypes = ['link', 'hardlink', 'folder'];
        if (this.data.type && in_array(this.data.type, nonVersionTypes)) {
            return;
        }`

but here 'this' has no this.data.type but this.data.general.o_type

### Steps to reproduce

Open folder and select object-class

**Comment by dvesh3** [comment]
Fixed by #10726
