### ISSUE TITLE
[Bug]: Academy: "Data Importer'" not accepting correct answers

### ISSUE THREAD

**Issue by janlucaklees** [pimcore/pimcore#10729]
### Expected behavior

On the 7th question of the Pimcore Juniour Certificate, "**What can be achieved with transformation pipelines and out-of-the-box operators?**", on the Data Importer exam. I choose these options:

- [x] Simple text transformations
- [x] Importing assets from remote locations
- [x] Load existing assets and data object based on ID, path or attributes.
- [ ] Transform data to number fields.
- [ ] Do complex statistical calculations
- [x] Assign data to object fields.

These are the answers I understand to be correct and the ones that were correct last year. 

I expect to have answered the question correctly.

### Actual behavior

No matter what options I choose, the 7th question is wrong.

(I tried probably all plausible combinations. Also this is my third or fourth week of trying.)

### Steps to reproduce

- Go to: https://pimcore.com/academy/course/Data-Importer~158351/exam
- Fill out the 7th question as I showed above.
- Fill out other questions, so you can submit the form.
- Question 7 will be wrong.

Here's my train of thought:
1. [x] Simple text transformations.
  This is shown in the material.
 
2. [x] Importing assets from remote locations.
  This is also shown / mentioned in the material.
 
3. [x] Load existing assets and data object based on ID, path or attributes.
  This is also shown in the material. It is talked about how you can load an object or assets to then assign it to whatever other object you are currently importing.

4. [ ] Transform data to number fields.
  What is this even supposed to mean? Data to fields? To me this sound like: "Can I cast a string to a variable?". So no, obviously I cannot take some imported data and turn it into a DAMN field. But I can cast imported data to a number, meaning a float or integer. This is also shown in the material. Either way, selecting this option or not, I cannot successfully answer this question.
  Also, this wasn't part of the accepted answer last year.
 
5. [ ] Do complex statistical calculations.
  Not mentioned in the material. And wasn't possible last year.
 
6. [x] Assign data to object fields.
  Obviously, this is the whole point, of the importer.

**Comment by dpfaffenbauer** [comment]
Right answer is: 
 - Transform data to number fields
 - Importing assets from remote locations
 - Simple text transformations
 - Load existing assets and data objects based on ID, path or attributes
