### ISSUE TITLE
[Improvement]: Make maintenance jobs lock expiry configurable

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#10738]
### Improvement description

Currently the lock expires after a fixed amount of 24h. Especially the version cleanup job in dev environments may take longer. It would be great, if the expiry was configurable.

https://github.com/pimcore/pimcore/blob/10.x/lib/Maintenance/Executor.php#L67

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
