### ISSUE TITLE
Cache Serialize - Zend_Locale_Data

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#1073]
The new Cache change, breaks Zend_Locale_Data. Don't really know why, but data gets serialized twice and unserialized only once.

You can test it yourself with:

```php
$locale = \Zend_Locale::getLocaleToTerritory('AT');
$zCurrency = new \Zend_Currency($locale);

echo $zCurrency->toCurrency(10, array('symbol' => '€'));
exit;
```

This code will throw a ```Illegal string offset 'decimal'```, thats because the data is still serialized when trying to access 'decimal'

**Comment by brusch** [comment]
The commit above should fix it, please don't forget to clear the cache after this modification. 
Currently this causes double serialization, so a better approach would be to implement a custom cache frontend, but for now this should fix it.

**Comment by dpfaffenbauer** [comment]
Yes, it works :)
