### ISSUE TITLE
[Bug]: Disappearing/duplicated relations when using the same relation field name in class and objectbrick definitions

### ISSUE THREAD

**Issue by rjankiew** [pimcore/pimcore#10747]
### Expected behavior

Relations are added, and do not change on subsequent saves.

### Actual behavior

Relations disappear (on the pimcore demo), or get duplicated (on my local installation -> that can also lead to "Passing relations multiple times not allowed anymore" error).

### Steps to reproduce

1. Go to pimcore demo
2. Open up "car" object class definition
3. Add localized field, and inside add advanced-many-to-many relation field and allow adding assets.
4. Open up brick definitions. Choose any brick, and add an advanced-many-to-many relation field with the same name, permissions as added to car class in step 3.
5. Save the definitions
6. Open up any car object. Add relation to the same asset to both the localized relation field, and in the relation field on the brick
7. Save the object and reload
8. Edit any input field, save and reload
9. Look at the relations added in 6 - there is an unexpected change

I'm attaching some clips made on pimcore demo today:

Class definitions:
https://user-images.githubusercontent.com/89988908/139869356-7c79e2a4-ec95-4c1c-b3c2-3f23cfc88f68.mp4

Reproduction on car object:
https://user-images.githubusercontent.com/89988908/139869374-dab625ff-c7b3-477f-b32d-73d4d6646a42.mp4

**Comment by dvesh3** [comment]
Could not reproduce on latest version 10.2.5. 

please feel free to come back if you still facing the issue. thanks!

**Comment by rjankiew** [comment]
Thank you @dvesh3. I cannot see any linked pull requests, could you shed any light on what changes resolved this?

**Comment by dvesh3** [comment]
Honestly, I'm not sure what fixed it. I just tried to reproduce the issue with mentioned steps on latest version and couldn't anymore.
