### ISSUE TITLE
[Bug]: Inherited areablock combined with Area Editable Dialog Settings

### ISSUE THREAD

**Issue by melissakittl** [pimcore/pimcore#10744]
### Expected behavior

When overriding the area editable dialog settings, only the settings from the current area are overwritten.
In the best way, it should be possible to overwrite each setting of the editable dialog, like all the editables, which are directly within the area.
![image](https://user-images.githubusercontent.com/23357021/139831535-250046ce-836e-4ca0-8917-3a039b1f50e6.png)

### Actual behavior

If you have an inherited document, where an area has an editable dialog for some settings, and you click to overwrite, then you overwrite the whole areablock.
If you then add, remove, or move an area in the content master document, it will not be adjusted in the interited document.

Once saved, it's not possible to undo the overriding.

#### Step 1:
Create document with area with editable dialog

#### Step 2:
Copy and paste this document with inheritance

#### Step 3:
Overwrite the editable dialog in the inherited document and save and publish it.
![image](https://user-images.githubusercontent.com/23357021/139829230-1172d2b8-62d1-456b-a396-2f3def2eee64.png)

#### Step 4:
Add another area in the content master document and save and publish it.
![image](https://user-images.githubusercontent.com/23357021/139830106-b3bf0867-5f2b-4624-8b08-5ad89408e7de.png)

#### Step 5: 
Reload inherited document and check if area is present, it will not be here.
![image](https://user-images.githubusercontent.com/23357021/139830346-91dfa1f6-b191-41aa-89e9-ab1d41021cd1.png)

Can be reproduced on Pimcore Demo.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
