### ISSUE TITLE
[Bug]: Pimcore not installing, database credentials not stored

### ISSUE THREAD

**Issue by mick340** [pimcore/pimcore#10748]
### Expected behavior

When running pimcore install i expect to install pimcore

### Actual behavior

Pimocre is not installing because of Step 6/11 database setup

### Steps to reproduce

I have created a `acceptatie` user to connect to database `pimcore` @ `localhost`

As you below i can connect with the database using tableplus (connection trough ssh)

![Screenshot 2021-11-02 at 16 01 54](https://user-images.githubusercontent.com/8590308/139873118-2f9fd775-7a96-4f02-9676-d136e223a355.png)

When installing pimcore im using the optional parameters to give the required database information (Even the config/installer.yaml file isn't working)

![Screenshot 2021-11-02 at 16 03 52](https://user-images.githubusercontent.com/8590308/139873854-57bcce17-e589-4534-be9b-fef5d3197b9b.png)

I fill in the Admin username and password, and the installer starts and fails.

![Screenshot 2021-11-02 at 16 04 15](https://user-images.githubusercontent.com/8590308/139874252-ce0b6a41-0eb4-40c2-bab6-ed0310461be4.png)

The strange part is that it gives me an error that root@localhost is denied and that is true, because i don't want Pimcore to connect with the root user. It looks like that the given database credentials are not stored / taken over.

But when i try to install pimcore with wrong credentials (wrong password) it stops installing at step 0/11

So somewhere along the installing steps the database credentials are gone.

![Screenshot 2021-11-02 at 16 11 26](https://user-images.githubusercontent.com/8590308/139874873-77ccdf6a-b50b-4989-bae4-44b97d9baace.png)

**Comment by brusch** [comment]
I think you have already a database-config in place that causes the issue. 
The option `--ignore-existing-config` is just not overriding existing config, but doesn't mean it's not loading it.
