### ISSUE TITLE
[Bug]: Links having long URLs not editable in data objects

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#10753]
### Expected behavior

Edit links as expected

### Actual behavior

As the buttons are positioned using js, they get cut off when used long URLs:

![image](https://user-images.githubusercontent.com/90033/140041618-409a461e-82c0-4044-aedc-d4c50787719a.png)

Replaced by a shorter URL:

![image](https://user-images.githubusercontent.com/90033/140041690-e939d5a1-e60e-43e5-a14a-757bfcaa00fd.png)

### Steps to reproduce

Use a long URL in a data object link field

**Comment by brusch** [comment]
Fixed by #10756
