### ISSUE TITLE
[Bug]: Classification store inheritance is broken

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#10754]
### Expected behavior

According to [the docs](https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Classification_Store.html#page_Inheritance) a variant should be able to inherit data from a parent object.

### Actual behavior

Certain fields appear to not inherit properly using the standard getters *OR* the documentation is missing.

### Steps to reproduce

1. Add data to a parent object:
![image](https://user-images.githubusercontent.com/279826/140043608-17f5f48d-0518-41bd-9c24-b752148cae79.png)

2. Make sure it is visible on the variant:
![image](https://user-images.githubusercontent.com/279826/140043706-dfd3a0be-4d1f-404b-a24d-47f495fbbe4e.png)

3. Try to get the data in a controller so that it can be sent to the front end, but none of the expected methods work:

`$classificationStore->getActiveGroups()` does not return this data
`$classificationStore->getGroupIdsWithData()` does not return this data
`$classificationStore->getItems()` does not return this data either.

**Comment by NiklasBr** [comment]
I found some more info, it appears that the values will not be made available because they are default values:

![image](https://user-images.githubusercontent.com/279826/140089664-709c1967-233d-4526-9e26-dbb80f510e65.png)

"Short Circuit Current 1s" has been manually edited with a `0` value, the other three inputs at the bottom have `0` as the default value.
![image](https://user-images.githubusercontent.com/279826/140089922-3af0b857-8876-486a-bea1-f7f56e120319.png)


![image](https://user-images.githubusercontent.com/279826/140089803-0494fafa-b1a6-48e7-977d-0934d52a4622.png)

**Comment by dvesh3** [comment]
Fixed by #10772
