### ISSUE TITLE
Caching: Avoid double serialization

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1076]
See also #1073 
The problem is that the cache is also used to cache some ZF internals, like: 
https://github.com/pimcore/pimcore/blob/fd91ccc6ca2e1f60b4c755d427f8aff38790e7ca/pimcore/lib/Pimcore/Cache.php#L764-L764 

So we can't just turn off `automatic_serialization`. 
But serialization is already done in the static cache interface of pimcore: 
https://github.com/pimcore/pimcore/blob/fd91ccc6ca2e1f60b4c755d427f8aff38790e7ca/pimcore/lib/Pimcore/Cache.php#L361-L361
To avoid corrupted cache items (see #1005 ) 

So the solution would be to implement a custom cache Frontend, which handles serialization propertly.

**Comment by maff** [comment]
@brusch It seems as the only ZF component relying on automatic serialization is the DB metadata cache, the others should work fine with or without. Do you see any problems with the solution in 11ab1422e9dd000f8b2e9c5995338e8f76b43aec? Clones the cache frontend and enables serialization for ZF.

**Comment by brusch** [comment]
@maff No objections :) Looks good, thanks!

**Comment by maff** [comment]
fixed in c49f65634e92427448b3d61b231bcaed1fb52007 👍
