### ISSUE TITLE
[Bug]: many to one relation values are not saved 

### ISSUE THREAD

**Issue by aweichler** [pimcore/pimcore#10779]
### Expected behavior

I drop an object to an many to one relation at an objectbrick in another object. 
When I save and reload the relation field is filled.

### Actual behavior

After save and reload the relation field is empty.

### Steps to reproduce

I put a class "Test" in the zip file with an objectbrick "TestBrick". The relation field "car" accepts an object of class "Car" from the pimcore demo.
Create a object of class "Test", add the objectbrick under the field "attributes" and save and publish.
After that create a variant for that new object and save and publish it.
The drop a car object to the car field from the main object and save. 
After reload the car field is still empty.
class and objectbrick files: [test-classes.zip](https://github.com/pimcore/pimcore/files/7495315/test-classes.zip)
I have Pimcore Version 10.2.3.

**Comment by dvesh3** [comment]
Fixed by #10890
