### ISSUE TITLE
[Improvement]: Message queue asset handler should also generate preview images for videos and office documents

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#10771]
### Improvement description

see title

**Comment by mcop1** [comment]
@brusch 

AssetUpdateTasksHandler already handles videos, images and office documents, it works fine:
https://github.com/pimcore/pimcore/blob/10.x/lib/Messenger/Handler/AssetUpdateTasksHandler.php#L37

Isn´t that what you meant?

**Comment by brusch** [comment]
@mcop1 ah sorry, I guess this is about preview images for die Admin UI, similar what we do for images here: https://github.com/pimcore/pimcore/blob/10.x/lib/Messenger/Handler/AssetUpdateTasksHandler.php#L121

Renamed the issue accordingly 😊
