### ISSUE TITLE
Some minor GUI bugs for variants

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1077]
I was testing some variant functionnality.
I found some small GUI bugs, so i report them here:

1- Direct SQL on the variant tab panel don't work and send a JS error:

![2](https://cloud.githubusercontent.com/assets/9025839/20602757/f2db2e8c-b25e-11e6-8832-6a56f879b307.png)

2- When variant are hidded in the tree (checkbox not checked on the class model), the "+" icons is printed. If we click on it it disapear. I think there should not be at all a "+" icon in this case, as thay are hidden.

![1](https://cloud.githubusercontent.com/assets/9025839/20602810/2a225b86-b25f-11e6-9db6-8052cadf5581.png)

3- The icon on the variant tab panel change sometimes from the object one to the variant one... very strange. To reproduce create a new variant from the tree and after open it:

![3](https://cloud.githubusercontent.com/assets/9025839/20602847/4abd4090-b25f-11e6-9b40-a4f4637e84fb.png)

Save it:

![4](https://cloud.githubusercontent.com/assets/9025839/20602853/5105a47e-b25f-11e6-90c6-5bff68bdae8a.png)

Thanks!

**Comment by Yivan** [comment]
Just a side question: "column configuration" of the variant panel doesn't seem to be save when the object is saved, is it intended ? (each time the object is reopened and variant panel is selected it come back to only system column).

**Comment by Yivan** [comment]
@weisswurstkanone I saw some patches have been just made for variant, maybe some of the problem of this issue are related ?
If not, maybe they could be corrected so variant will be free of those last bugs.
Thanks.

**Comment by weisswurstkanone** [comment]
ad 3) see https://github.com/pimcore/pimcore/issues/1334

**Comment by weisswurstkanone** [comment]
ad 2) fixed in build 4057

**Comment by weisswurstkanone** [comment]
ad 1) fixed in build 4057

**Comment by weisswurstkanone** [comment]
regarding your question about the column configuration: best option would be to create a new ticket for this

**Comment by Yivan** [comment]
Thanks for the fixes.
I think this issue could be close so.

For column configuration, it was just to know if it was intended to work like this. I think saving column configuration can be great, but i think too there are more important issue/improvement in warning, so i prefer not open a issue for this (maybe later when Pimcore 5 will be released as it is the top priority).
Thanks!

**Comment by weisswurstkanone** [comment]
I believe that this was never supported on a variants level. But definitely a good idea! The only thing we should think about is if this should be tied to the object or some other magic. Ideas are welcome!
