### ISSUE TITLE
[Bug]: TypeError when trying to validate inherited localized value in objectbrick from parent with no brick

### ISSUE THREAD

**Issue by wskorodecki** [pimcore/pimcore#10786]
### Expected behavior

Missing value should not be inherited because there is nothing to inherit as the parent object has no ObjectBrick of the same type.

### Actual behavior

PHP throws a TypeError because $parentContainer becomes NULL due to missing ObjectBrick in parent object.
See: https://github.com/pimcore/pimcore/blob/d0b5dc0d78392ee2d4012d228214901fd1080076/models/DataObject/Localizedfield.php#L526

### Steps to reproduce

1. Make sure "Allow inheritance" is enabled.
2. Update one of defined ObjectBricks by adding localized field.
3. Make sure parent object has no ObjectBrick of this type added.
4. Add at least one ObjectBrick of this type to child object, but do not set value in at least one of localized fields.
5. Try to Save & Publish the child object.

https://user-images.githubusercontent.com/7789823/140913527-d5f671fb-2bf2-44eb-ab04-3a7f626d15c6.mp4

Affected versions:
**10.2.1** including current Demo (**10.2.3**).

**Comment by dvesh3** [comment]
Fixed by #10820
