### ISSUE TITLE
Improvement for document link (langage): unlink them

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1079]
Linking document in different langage is a very great new feature, wich helped a lot the editors.
But in some case, we want to remove a link and actully only way is to duplicate document (and so loosing reference anywhere).

Maybe a "Unlink document" option in the menu could be add. It will show the different document linked (like "Open translation"). Choosing one will remove the link.
Here is a try of graphism presentation of this new option:

![link](https://cloud.githubusercontent.com/assets/9025839/20604568/55ee50fa-b267-11e6-9e0d-7526d5cedd55.png)

**Suggestion of documentation improvement on this subject:**
Aside of this, I didn't found in the documentation the way to request linked document using the API. Maybe it could be add. For instance it could be used when generating sitemaps multilingale.

As well, i think it is the case, but it could be add in the documentation that the hreflang meta are automaticaly added to (if zend head helper is injected in the layout template).

**Comment by msenkpiel** [comment]
Yeah... that's a missing feature!!!

**Comment by Yivan** [comment]
I make a bump on this issue as it prevent of using this feature (no possibility to unlink if link has made by error by an editor...).

A pull request was made but got only the Pimcore 4 code : https://github.com/pimcore/pimcore/pull/1248/files
Actually i am not able to provide the pimcore 5 code.

Maybe someone could take back the code of the pull request for Pimcore 4 and add the one for Pimcore 5 so pull request will be accepted.

Thanks.

**Comment by Yivan** [comment]
I just reup this issue, as it lead us for now not using this feature because end user cannot revert his actions without modifing directly database, so it is too risky for now. Or has it been solved on Pimcore 5 (in this case it could be closed).
