### ISSUE TITLE
[Bug]: No switch of decimal separator in backend GUI (works under 6.9)

### ISSUE THREAD

**Issue by woellundwoell** [pimcore/pimcore#10809]
### Expected behavior

Decimal separator switches according to the selected language of the logged in user for all number inputs (number, quantity value, etc.).

### Actual behavior

Decimal separator is always the same: "."
The entry of a comma character is allowed but all data following it will be truncated. Only the first "." sign is treated as decimal separator

### Steps to reproduce

- Log in to the pimcore demo under https://demo.pimcore.com/admin
- Check if user language is set to "English"
- Select a car DataObject to edit
- Select the tab "Sale Information"
- Enter a price with cents in the attribute field "Price in EUR" by using a "." as decimal separator
- Switch user language to "German", save and reload backend
- Repeat the same as above and use a "," as decimal separator

**Comment by blankse** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/10888
