### ISSUE TITLE
[Bug]: Outdated link to community forum in composer file

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#10807]
### Expected behavior

![image](https://user-images.githubusercontent.com/13643455/141255267-1d26aa73-cd2c-4acb-a438-cf46da3e3786.png)

### Actual behavior

Please change it to https://github.com/pimcore/pimcore/discussions

### Steps to reproduce

Thanks!

**Comment by blankse** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/10808
