### ISSUE TITLE
[Bug]: titles and selection values are enclosed by "+ sign" 

### ISSUE THREAD

**Issue by sys4cad** [pimcore/pimcore#10806]
### Expected behavior

title values are displayed with value as it is.

### Actual behavior

title values are enclosed by + sign

### Steps to reproduce

pimcore 10.2.1
![image](https://user-images.githubusercontent.com/9436271/141245631-08c25105-a4af-4aa8-a3b2-92c519ed7205.png)

![image](https://user-images.githubusercontent.com/9436271/141245724-830f00d9-89d9-4aa6-bf71-b7e8764eda0c.png)

As you can see, selection values are A,L... not +A+, +L+...

![image](https://user-images.githubusercontent.com/9436271/141245842-078d0cb8-dae1-4c9a-ad4f-d84eb83d5aa5.png)

**Comment by matthiashamacher** [comment]
It seems that you have enabled debug translations. https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Magic_Parameters.html#page_pimcore-_-debug-_-translations

When that is enabled the translations keys are enclosed by a +: https://github.com/pimcore/pimcore/blob/10.x/bundles/AdminBundle/Resources/public/js/pimcore/functions.js#L75

**Comment by sys4cad** [comment]
Thanks a millon~ @matthiashamacher 

root cause was following setting ( Settings > SystemSettings > Debug )
* I checked this option when set email transport test and didn't know what it mentions even it clearly mentions + translations :)

![image](https://user-images.githubusercontent.com/9436271/141260684-3dfc21e3-40d7-4da4-829a-3cca81b54f22.png)


Please close this issue
