### ISSUE TITLE
[Feature]: Thumbnail transformation "Cover without Crop" and "Crop (Focal Point Support)"

### ISSUE THREAD

**Issue by Zamralik** [pimcore/pimcore#10816]
### Feature description

Contain will make a thumbnail smaller than the width/height dimensions.
Cover will crop the protruding axis.
Crop uses a x/y offset but do not support focal point.

By having the 2 steps of cover available separately, it would give more flexibility in thumbnail configuration.

In some cases of responsive display, it would be better if there was a "Cover without Crop". The image is scaled at the best size without losing parts of the image and there's no blank gap as you would see with Contain or Frame.

And a "Crop (Focal Point Support)" would preserve the focal point of the image and keep the image within maximum width/height boundaries without any unwanted resize.

**Comment by brusch** [comment]
"contain" is exactly doing what you're describing. 
You can't do "cover" without cropping or deforming the image, e.g. source image is 4000x3000 pixels, target thumbnail should have exactly 300x200 pixels, so you need to either crop the image, add transparent frames or deform it to get exactly 300x200.

**Comment by Zamralik** [comment]
@brusch, It doesn't.
If you have a 4000x3000 image and do "cover without crop" set for 300x200, you would end with a 300x225 thumbnail.
Using "contain", you would end with a 267x200 thumbnail.

There is no way to achieve this result with existing transformations unless you do the computation manually in the code itself.
