### ISSUE TITLE
Folders for "namespaced" objects broken

### ISSUE THREAD

**Issue by rolandstoll** [pimcore/pimcore#1082]
### Expected behavior 
objects with a name starting with more than 1 uppercase letters (e.g. "XXXTest...") are not shown in a folder (e.g."XXX") neither in the class pannel nor in the right-click menue in the object tree. 
In pimcore 4.3 and before objects were collected to folders based on the admin translation. Folder were created based on "blanks" (e.g. class-name "XXXTest" + translation "XXX Test" =>folder "XXX")

### Actual behavior  
creating some objects with a name starting with more than 1 uppercase letters (e.g. "XXXTest...") are shown in a nameless folder (even if you create objects starting with different names (e.g. "YYYTest...", "ZZZTest...").

### Steps to reproduce  
created objects names as described above on http://demo.pimcore.org/admin/ with pimcore 4.4.1

**Comment by fashxp** [comment]
best practice would be to use camel case for class names. 
so what is your wish - that the folders are created based on the admin translations?

**Comment by rolandstoll** [comment]
yes, because with admin translation we have all the flexibility to create the namespace / groupname we want.
e.g. I have a object class names "XXXTestName1" and another with "XXXTestName2". Through the admin translation I could call them ""XXXTest Name1" and "XXXTest Name2", so the group name would be ""XXXTest".
In this case you would not get a solution with camel-case (e.g. with ""XxxTestName1" the group would be "Xxx")

**Comment by fashxp** [comment]
we will discuss it internally.

**Comment by rolandstoll** [comment]
thanks :)

**Comment by rolandstoll** [comment]
*push*
any news on that? still seems same-same on pimcore 4.5...

**Comment by brusch** [comment]
Not for the 4.x branch. 
Eventually for 5, but I'd prefer real namespaces for objects rather than virtual grouping.

**Comment by rolandstoll** [comment]
totally agree - namespaces whould be awesome!

unfortunately this is a blocker for us right now - having more than 150 Object types without any grouping functionality is a no-go editorial-wise... :(

**Comment by rolandstoll** [comment]
hi @brusch , just saw this new field "group" object definition in pimcore 4.5 - yeah, exactly what we wanted! :)
for sure namespaces would be even better ("group" doesn't generate a namespace for the object class - just checked out the object class source) - but that's maybe for the future... ;)
