### ISSUE TITLE
Bug: formatted HREF fields revert back to their original full-path after pressing tab 3x

### ISSUE THREAD

**Issue by EazyAlvaro** [pimcore/pimcore#1083]
# Bug Report

Version: 4.4.1
Build: 4009

Non-Security, cannot be reproduced on demo because the demo lacks formatters for the path.

  
### Expected behavior 
'tabbing' through fields without incident, each key-press moves the cursor to the next (input) field.

### Actual behavior  
Tabbing 'into'a HREF field reverts to displaying the full path, in stead of using displaying the Formatted output

### Steps to reproduce  

* Define a class as having an HREF
* implement a formatter for that class
* Create an Object from this class
* Open the Object from previous step
* Click on the field above an HREF relation that has a Custom Formatter. In the provided screenshots we are displaying a name value for a brand in stead of the full path
* press tab to move to next field
* The cursor seems 'stuck when it reaches the HREF field 
* press tab key 2x more (3x more if the above field was also HREF) (this tabs through the buttons to the right of the HREF field)
* The HREF field reverts to displaying the full path, as can be seen in screenshot.

Before
![before](https://cloud.githubusercontent.com/assets/1539652/20628062/506a152a-b324-11e6-8456-e5666e9f8af9.png)

After

![after](https://cloud.githubusercontent.com/assets/1539652/20628074/5a0c5462-b324-11e6-9a95-a9a7a0c5695a.png)

**Comment by weisswurstkanone** [comment]
thx. fixed in build #4010

**Comment by manea-eugen** [comment]
Sorry for late feedback, but are you guys sure about it ? Because i see that this code is still there 
`
// disable typing into the textfield
        this.component.on("keyup", function (element, event) {
            element.setValue(this.data.path);
        }.bind(this));
`
Meaning that any keyup will update the field to path

**Comment by fashxp** [comment]
build 4010 is not yet published

**Comment by manea-eugen** [comment]
I know that, but when i tried to apply the fix temporary i discovered that keyup still updates the value of the element to path

**Comment by manea-eugen** [comment]
Sorry i just noticed that the function also updates the path .
