### ISSUE TITLE
Copy & Paste Documents with spaces ->Error

### ISSUE THREAD

**Issue by Gerhard-Kanzler** [pimcore/pimcore#1084]
If you copy and paste documents (with childs) that contains spaces, you get an error:
![error](https://cloud.githubusercontent.com/assets/290663/20664647/58bf652e-b55c-11e6-8f93-252872030228.png)

**Comment by weisswurstkanone** [comment]
Unable to reproduce. What is your build number? Can you provide more infos, maybe a video?

**Comment by Gerhard-Kanzler** [comment]
Ah ok. In the Version 4008 you can't create documents with a space.
