### ISSUE TITLE
[Bug]: Static Routes not ordered by priority as of 10.2.0

### ISSUE THREAD

**Issue by xlttj** [pimcore/pimcore#10847]
### Expected behavior

Static routes should be ordered by the closure method defined in https://github.com/pimcore/pimcore/blob/10.2/lib/Routing/Staticroute/Router.php#L323

### Actual behavior

Static routes are nor ordered by priority before they are processed in https://github.com/pimcore/pimcore/blob/10.2/lib/Routing/Staticroute/Router.php#L246

The code in https://github.com/pimcore/pimcore/blob/v10.1.5/models/Staticroute/Listing/Dao.php#L40 calls the closure in 10.1.5, but no longer in 10.2.

### Steps to reproduce

Difficult to explain in a few words, so please bear with me and look at the lines of code mentioned above :)

* Create a catch-all static route in Pimcore with the pattern `/^.*$/`
* Create a specific static route in Pimcore with the pattern `/^\/something$/`
* Request the path `/someting`
* See that always the route that was defined first matches instead of that with a higher priority

**Comment by dvesh3** [comment]
Fixed by #10879
