### ISSUE TITLE
[Feature]: Use new authenticator-based Security System 

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#10856]
### Feature description

A new Security was introduced in Symfony 5.1, which will eventually replace security in Symfony 6.0.

```yaml
security:
    enable_authenticator_manager: true
```

Not sure if this is a pimcore XI thing or if it's a good idea to switch over withing X for more freedom in current deprecation logs.

**Comment by dvesh3** [comment]
Yes, this is on our list to check if it can still be supported on Pimcore X (without a BC break).

**Comment by brusch** [comment]
See also #10828 and https://github.com/pimcore/pimcore/issues/8195#issuecomment-785065966
