### ISSUE TITLE
activate/deactivate Tags in the Tag & Snippet Management

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#1085]
# Feature Request

**Comment by fashxp** [comment]
activate & deactivate - or permission to show/hide configuration panel?

**Comment by putzflorian** [comment]
activate & deactivate

**Comment by fashxp** [comment]
so if tags are configured, they should not be injected anymore if deactivated?

**Comment by putzflorian** [comment]
yes

**Comment by putzflorian** [comment]
please allow activate & deactivate per Tag

**Comment by fashxp** [comment]
similar to activate/deactivate personas and targeting rules

**Comment by weisswurstkanone** [comment]
see https://github.com/pimcore/pimcore/issues/1824
