### ISSUE TITLE
[Bug]: VoucherService fails at isReserved

### ISSUE THREAD

**Issue by jansarmir** [pimcore/pimcore#10868]
### Expected behavior

Cannot add token to cart

### Actual behavior

after calling $cart->addVoucherToken with existing token, with no token in cart, operation fails

https://github.com/pimcore/pimcore/blob/91531281537b7cc8307682517fa9cc03aa617e4f/bundles/EcommerceFrameworkBundle/VoucherService/Token/Dao.php#L62

Fails when $reservation === NULL

### Steps to reproduce

Create token, add to cart, process fails with error

**Comment by brusch** [comment]
fixed by #10881
