### ISSUE TITLE
[Bug]: Cant create new VoucherTokenTypeSingle

### ISSUE THREAD

**Issue by jansarmir** [pimcore/pimcore#10869]
### Expected behavior

After saving **OnlineShopVoucherSeries** and clicking on **Voucher Detail** i should see Manager and Statistics

### Actual behavior

Clicking on **Voucher Detail** for new **OnlineShopVoucherSeries** without tokens, we got error

### Steps to reproduce

Create **OnlineShopVoucherSeries** with **VoucherTokenTypeSingle** and click on **Voucher Detail**

**Comment by brusch** [comment]
![image](https://user-images.githubusercontent.com/142037/142847955-2449af3a-2325-4471-8be2-4344127c7a76.png)

**Comment by brusch** [comment]
Fixed by #10876
