### ISSUE TITLE
[Bug]: I can't find the submenu for customer 

### ISSUE THREAD

**Issue by shlingok** [pimcore/pimcore#10863]
### Expected behavior

10.x-dev version

### Actual behavior

10.x-dev version

### Steps to reproduce

10.x-dev version

**Comment by dvesh3** [comment]
sorry, cannot reproduce 
![image](https://user-images.githubusercontent.com/5137917/142601186-0981637e-5060-489e-a658-a2e8e31b7d71.png)

**Comment by shlingok** [comment]
![image](https://user-images.githubusercontent.com/6915649/142793070-c25b31ec-45e9-47c4-b2b6-fb054e59b77a.png)
Click no response, and do not see those submenus

**Comment by blankse** [comment]
Did you test it without browser extensions? I recently had similar problems with an extension.

**Comment by dvesh3** [comment]
> Click no response, and do not see those submenus

@shlingok Please check console for errors.

> Did you test it without browser extensions? I recently had similar problems with an extension.

@blankse do you know which extension?

**Comment by blankse** [comment]
KeePassXC-Browser, but is fixed in the new version.
