### ISSUE TITLE
[Bug]: Unable to serialize objects with Localizedfields

### ISSUE THREAD

**Issue by CountZero1981** [pimcore/pimcore#10889]
### Expected behavior

My controller inherits FrontendController. When I use the method `$this->json` of FrontendController, I should be able to get serialized representation of object.

### Actual behavior

When I use the method `$this->json` of FrontendController, I'm getting the error `A circular reference has been detected when serializing the object of class "Pimcore\Model\DataObject\Bags" (configured limit: 1).` This is because Localizedfields->context['object'] always contains a reference back to object. This was added to fix #3736 (pull request #3938).

UPD:
hmm, no, `models/DataObject/Localizedfield.php:270`, in one of the first commits, in 2011. And Mutiselect fields also have circular references.

### Steps to reproduce

Create a product with Localizedfields and try to serialize it using the method mentioned above.

**Comment by brusch** [comment]
Entities implementing `ElementInterface` are just not JSON serializeable at the moment. There is an existing issue for that, but I can't fint it right now. 😉

**Comment by CountZero1981** [comment]
for those who are interested how to serialize it: use circular references handler as it is described in Symfony documentation, and don't use the default controller->json method. though, still, then it tries to serialize the embedded DBAL object.
