### ISSUE TITLE
[Improvement]: Elasticsearch - remove "indexType"

### ISSUE THREAD

**Issue by ctippler** [pimcore/pimcore#10884]
### Improvement description

Currently the Elasticsearch Index works with indexTypes.
As long as dont specify a custom indexType or you name it "_doc" it works. 

Currently ES 7 shows a warning that "types" won't be supported anymore in ES8. 
![image](https://user-images.githubusercontent.com/8791970/143021329-a39a5395-f59b-4eb1-8aa3-5256fd3ea4f0.png)

Therefore the indexType should be removed. With the removal of the indeType also the parent/child relations should be refactored
More details here:
https://www.elastic.co/guide/en/elasticsearch/reference/7.16/removal-of-types.html

**Comment by fashxp** [comment]
related to #13248

**Comment by fashxp** [comment]
should be fixed by https://github.com/pimcore/pimcore/issues/13411
