### ISSUE TITLE
[ExtJS 6.2] Objects with Metadata - d&d reordering doesn't mark object as dirty

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#1089]
and as a consequence, new order is not saved when saving object.

![image](https://cloud.githubusercontent.com/assets/8792145/20706713/dd22ebca-b628-11e6-87d1-199861bfc2e0.png)

**Comment by weisswurstkanone** [comment]
temporary solution:
- use the drop handler to mark the object as dirty
- this is for sure not the right solution as dirty detection should be done with assistance of the store and not based on how things got changed
- Problem: ExtJS 6.2 does not fire add/remove events in case of a replacement
- not sure if this is now the intended behavior. If this is the case then we are lacking a way to detect reordering.

**Comment by brusch** [comment]
ExtJS 6.2 project stopped, we give 6.3 another try :)
