### ISSUE TITLE
Change Area via drag and drop

### ISSUE THREAD

**Issue by romainp89** [pimcore/pimcore#1091]
Is it possible to change an area by simply drag-and-drop, as we do to change an object in an area, here if we drag an area on another area it just change that one. 

By dragged drop, or via the context menu:
Change area -> Area 1
                      -> Area 2 ...
  
Cheers

**Comment by fashxp** [comment]
please English :-)

**Comment by romainp89** [comment]
Oups ... ^^

**Comment by fashxp** [comment]
sorry, I cannot follow you :-) 
please create a new issue with an example (screenshot or so) if the issue is still valid. 

thank you.
