### ISSUE TITLE
[ExtJS 6.2] Document Editmode: Areablock and Areablock Toolbar D&D

### ISSUE THREAD

**Issue by maff** [pimcore/pimcore#1092]
* dragging of Areablocks works, but they can't be dropped
* dragging from the toolbar does not work at all

**Comment by maff** [comment]
Seems to be a problem with margins on the most outer container on a document (e.g. negative margin on header in pimcore demo).

**Comment by maff** [comment]
Confirmed as ExtJS Bug EXTJS-23240 - our workaround to use the 6.0 implementation of the coordinate calculation seems to work so far. See d36a54b0b145baad784b4200620806c810c82e86.

**Comment by brusch** [comment]
ExtJS 6.2 project stopped, we give 6.3 another try :)
