### ISSUE TITLE
[Improvement]: Nginx config fastcgi.conf

### ISSUE THREAD

**Issue by davordragic** [pimcore/pimcore#10921]
### Improvement description

When using Pimcore with nginx server there is a docs with configuration.
source: https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Nginx_Configuration.html

but if using debian os, fastcgi.conf is not included by default (nor in docker nginx image based on debian).
![image](https://user-images.githubusercontent.com/10212089/143857315-9752df30-b598-4579-8cf6-4f3b0c221ade.png)

Sicer only 1 line is different between fastcgi_params (always included) and fastcgi.conf
![image](https://user-images.githubusercontent.com/10212089/143857391-15471bab-e782-45fe-9617-f6efcc491dc5.png)

I would suggest to change docs to use fastcgi_params like this
![image](https://user-images.githubusercontent.com/10212089/143857457-52071bb7-aca7-4d53-98bc-e43e4f652290.png)

and maybe add nginx.conf file in git repo (like Magento does as sample file).
source: https://github.com/magento/magento2/blob/2.4-develop/nginx.conf.sample

Easier for upgrading and not overlooking changes in nginx when upgrading pimcore.

**Comment by jdreesen** [comment]
The `nginx.conf` is in already the `skeleton` repo: https://github.com/pimcore/skeleton/blob/10.x/.docker/nginx.conf

It even has `include fastcgi_params;`
