### ISSUE TITLE
[Bug]: field with a date type

### ISSUE THREAD

**Issue by VLynnik** [pimcore/pimcore#10925]
### Expected behavior

The field with the Date type will be saved and will not throw an exception.

### Actual behavior

field with a date type: the function expects \Carbon\Carbon, and a \DateTime is passed.

### Steps to reproduce

Create a field with the "date" type in the Object. This field needs to be edited through the form from the symfony.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
