### ISSUE TITLE
Custom Layouts for object bricks + field collections

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#10924]
### Feature description

With custom layouts you can limit the field which a certain user / role can see / edit. But this currently only exists for classes, not for object bricks or field collections. It would be nice if we could extend this functionality also to those.

**Comment by matthiashamacher** [comment]
Seems to be the same as https://github.com/pimcore/pimcore/issues/1002

**Comment by dvesh3** [comment]
> Seems to be the same as #1002

thanks! I would keep this one open as it is clearly described and voted 😜

**Comment by plixus** [comment]
Hi, I came across this when I was looking for a solution to give a field collection a custom layout.

@BlackbitDevs as mentioned in #12084, are you planning to implement this feature for field collections as well?

**Comment by BlackbitDevs** [comment]
@plixus I would love to but this needs some time and currently we have no client who would pay for this. If you are interested, please send an email to info@blackbit.de then we can discuss how to approach.
