### ISSUE TITLE
[Bug]: Areablock Editable - drag + drop not working in manual mode

### ISSUE THREAD

**Issue by shaselboeck** [pimcore/pimcore#10935]
### Expected behavior

Moving elements should be possible via drag + drop.

### Actual behavior

The drop zone is available in the HTML code, but the drop zone is not highlighted with a border and the element cannot be dropped anywhere. Elements can be moved using the arrows (up / down).

### Steps to reproduce

Use this code from the docs:
https://pimcore.com/docs/pimcore/current/Development_Documentation/Documents/Editables/Areablock/index.html#page_Using-Manual-Mode

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
