### ISSUE TITLE
Document what is "Dao"

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#1093]
In practice it seems to take place of the resources models of older Pimcore versions, but what is the meaning of the abbreviation "Dao"?

**Comment by dpfaffenbauer** [comment]
I guess "Data Access Object".

**Comment by fashxp** [comment]
keep in mind, this is a issue tracker. please use our forums for such questions. thank you very much.

**Comment by kanevbg** [comment]
@fashxp For me it is issue for the reason it is not documented.
@dpfaffenbauer My guess was "Data Adapter Object" for the reason it has implementation allowing models to manipulate data from PHP arrays stored in file.
