### ISSUE TITLE
[Bug][DataObject][Reverse Object Relation] Results in error when not defining owner class / owner field

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#10939]
### Expected behavior

do not allow saving incomplete class definition or no error when creating/saving data objects

### Actual behavior

when creating data objects, error message: 

![image](https://user-images.githubusercontent.com/8792145/144398546-36b4d46f-bb1f-4b9f-b148-34bf31043daf.png)

### Steps to reproduce

Create class definition with reverse object relation field, and do not define owner class / owner field setting

![image](https://user-images.githubusercontent.com/8792145/144398473-0f96455c-2b34-4f1b-bddd-c10aef7c0861.png)

Create data object of this class --> error

**Comment by kingjia90** [comment]
I cannot reproduce it, it works fine on my end. 
There's a mention about a fallback for legacy data on the line that throws the error though

https://github.com/pimcore/pimcore/blob/714e8767898d0e89f05c985e5bb13becf74e98d6/models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php#L91

**Comment by kingjia90** [comment]
I've also tried to change it as an empty string in the definition, but on save it turn it back to NULL
![image](https://user-images.githubusercontent.com/6014195/151387766-2ade840e-d552-4db3-abf1-07600347f893.png)
