### ISSUE TITLE
[Bug]: Cannot create "icons" folder in assets

### ISSUE THREAD

**Issue by breakone** [pimcore/pimcore#10930]
### Expected behavior

Create a folder named "icons", upload some assets and use them.

### Actual behavior

Assets within a folder named "icons" cannot be used. A 404 occurs.

### Steps to reproduce

- Create folder named "icons"
- Upload assets
- Call the public url of an asset

Reproduced the bevahior on https://demo.pimcore.fun

![image](https://user-images.githubusercontent.com/4848121/144226232-c58103cc-8040-4faa-8d41-9dd59cca39bc.png)
![image](https://user-images.githubusercontent.com/4848121/144226278-13d88533-121c-4f9b-a4eb-8a5c34a54380.png)

- Rename folder
- try again

![image](https://user-images.githubusercontent.com/4848121/144226419-b895358d-6c65-4140-8387-97c886eebbc6.png)
![image](https://user-images.githubusercontent.com/4848121/144226457-bc92747a-c2b2-4e0f-ac28-4997d887de39.png)

**Comment by dvesh3** [comment]
Seems to be some issue with Demo setup. Works on local instance.

**Comment by podarcis** [comment]
@breakone I guess it's the default Apache `/icons` alias which handles this URL. You might want to disable this alias in your Apache config.

**Comment by dpfaffenbauer** [comment]
we use the pimcore/pimcore docker setup, is the `/icons` alias enabled there by default too?

**Comment by brusch** [comment]
Yes, this comes from the default Apache alias, just delete it and it will work as expected. 
Regarding Pimcore Docker images: there is no more Apache image, so this is obsolete. 
Regarding demo.pimcore.org: this will be soon migrated to Nginx, so will be fixed by then 😉
