### ISSUE TITLE
[Bug]: Objectbrick::getLocalizedTableName() returns wrong value

### ISSUE THREAD

**Issue by CountZero1981** [pimcore/pimcore#10949]
### Expected behavior

Objectbrick::getLocalizedTableName() should return something like `object_brick_Basedata_localized_24`

### Actual behavior

it returns `object_collection_Basedata_localized_24`

### Steps to reproduce

create an Objectbrick and call the function.
Objectbrick\Dao (models/DataObject/Objectbrick/Definition/Dao.php) is inherited from Fieldcollection\Dao, but overrides all parent functions excepting getLocalizedTableName.

probably Objectbrick\Dao should be inherited directly from AbstractDao, because by now all methods in Fieldcollection\Dao are overriden. also Fieldcollection and Objectbrick represent two separate field types.

**Comment by dvesh3** [comment]
Fixed by #10950
