### ISSUE TITLE
Imagick fails to set alpha channel when generating treeview-thumbs

### ISSUE THREAD

**Issue by bbak** [pimcore/pimcore#1095]
`core.ERROR: exception 'ImagickException' with message 'Unable to set image alpha channel' in public/pimcore/lib/Pimcore/Image/Adapter/Imagick.php:186`

Happens, when generating the treeview Image. In console as well as the Ui. The Folder for the thumbnail stays empty. Other Thumbs/ImagePipelines are generated correctly.

It's PHP5.6 from dotdeb. And since this error occurred with the dotdeb package, which has a quite old Imagick extension, we updated Imagick from PECL to Version 3.4.3RC1 with no luck.

Pimcore Version 4.3, but the Imagick adapter didn't change in 4.4.

Seems to happen primarily (don't know if exclusively) when converting PNG to JPEG for the Treeview.

**Comment by maff** [comment]
Thanks for the PRs. For reference: if you're on a recent build and are not able to update PHP or the Imagick extension you could try to use the new `ImageMagick` adapter which uses the `convert` binary directly. See https://www.pimcore.org/docs/latest/Assets/Working_with_Thumbnails/Image_Thumbnails.html.
