### ISSUE TITLE
[Bug]: HttpNotFound for redirects? With exception tracking tool (sentry)

### ISSUE THREAD

**Issue by BentBr** [pimcore/pimcore#10969]
### Expected behavior

Redirects are being processed and resolved without symfony throwing the HttpNotFoundException.

### Actual behavior

When using redirects (path)  [/source] -> [/target] the user is being redirected to the correct page (pimcore document).
In frontend the proper http 301 is being returned. 
This is working as expected for users / crawlers.

Backend-wise our tracking tool is reporting for every redirect a HttpNotFoundException (symfony).
This could be circumvented when using the priority 99, which is not preferably for 100's of redirects.

We are using Sentry with the standard configuration for Symfony.

### Steps to reproduce

**Install:**
    "pimcore/pimcore": "^10.0.0",
    "sentry/sentry-symfony": "^4.2",

**Setup (sentry yaml)**
sentry:
    dsn: '%env(SENTRY_DSN)%'

**Setup (pimcore admin)**
Create redirects (path)

Use the redirect and have a look in sentry.

**Comment by brusch** [comment]
Don't know how to reproduce that or how we can avoid that, would be nice if you could check that and provide a PR - as you have a working case for that. We're not gonna work on that anytime soon, so I'm closing this. looking forward for your PR!
