### ISSUE TITLE
[Bug]: Classification store collections, filter by name "Undefined property stdclass"

### ISSUE THREAD

**Issue by speggi** [pimcore/pimcore#10961]
### Expected behavior

Filter works normally

### Actual behavior

When i try first time (first click on filters) to set a filter by name on my classification store collection it throws "Undefined property stdclass" in `bundles\AdminBundle\Controller\Admin\DataObject\ClassificationstoreController.php` at 284 line.

Guess it happens case onClick event triggers a "Collection" classification store controller function with request without value in filter in filters array (haven't had time to choose anything yet ). Also it may happens in other controllers with filters, didnt seek.

`$conditionParts[] = $db->quoteIdentifier($f->property) . ' LIKE ' . $db->quote('%' . $f->value . '%');`

### Steps to reproduce

go to classification store.
create one or use an existed one.
try to filter collections by name.
![image](https://user-images.githubusercontent.com/49711151/144623961-774d9bdc-7f01-43c7-a342-fd3ce0aeff26.png)

**Comment by dvesh3** [comment]
Fixed by #10968
