### ISSUE TITLE
[DataObject]: enrichLayoutDefinition fails if no layout defined

### ISSUE THREAD

**Issue by hcarsten** [pimcore/pimcore#10966]
### Expected behavior

/vendor/pimcore/pimcore/models/DataObject/Service.php
public static function enrichLayoutDefinition(&$layout, $object = null, $context = [])
fails if no layout are (yet) defined for a DataObjec class

should be catched or just return if $layout is null

### Actual behavior

method_exists will fail with a fatal error

### Steps to reproduce

create a class just with only the base data

**Comment by dvesh3** [comment]
Fixed by https://github.com/pimcore/pimcore/commit/6d96962027db8388ef5e737a69657ba3bb6d9b4a
