### ISSUE TITLE
[Bug]: There is no active transaction when delete asset without user permissons on file system

### ISSUE THREAD

**Issue by speggi** [pimcore/pimcore#10960]
### Expected behavior

An exception throws with right message: "Have no permissions on asset file".

### Actual behavior

Throws an Dao exception in try section in Asset delete fucnction cause www-data have no permissions on asset file, but catch section crashes cause there is no transaction to rollback. The truly exception message lost.

`Status: 500 | Internal Server Error
URL: /admin/asset/delete
Method: DELETE
Message: There is no active transaction.
Trace: 
in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/ConnectionException.php:23
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1840): Doctrine\DBAL\ConnectionException::noActiveTransaction()
#1 /var/www/html/vendor/pimcore/pimcore/lib/Model/Dao/AbstractDao.php(52): Doctrine\DBAL\Connection->rollBack()
#2 [internal function]: Pimcore\Model\Dao\AbstractDao->rollBack()
#3 /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(246): call_user_func_array(Array, Array)
#4 /var/www/html/vendor/pimcore/pimcore/models/Asset.php(1070): Pimcore\Model\AbstractModel->__call('rollBack', Array)
#5 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Asset/AssetController.php(648): Pimcore\Model\Asset->delete()
#6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(156): Pimcore\Bundle\AdminBundle\Controller\Admin\Asset\AssetController->deleteAction(Object(Symfony\Component\HttpFoundation\Request))
#7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(78): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#8 /var/www/html/vendor/symfony/http-kernel/Kernel.php(199): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#10 {main}`

### Steps to reproduce

1) make your user (www-data) have no permissions on asset file. for expampe, install any bundle;
2) try to delete the asset

**Comment by brusch** [comment]
Fixed by #11291
