### ISSUE TITLE
[sabre\dav] sabre dav BC break

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#10986]
### Expected behavior

sabre\dav introduced a BC break in 4.2.2: https://github.com/sabre-io/dav/pull/1365

Two possibilities for a fix:
 1. conflict 4.2.2 and stay on older versions
 2. add new param to Pimcore and use 4.2.2 as min-requirement

Which one do you guys prefer?

### Actual behavior

-

### Steps to reproduce

-

**Comment by dvesh3** [comment]
As there is no decision yet on this change, let's add conflict for `4.2.2` at the moment. We can properly fix it, once they decide if they want to keep this change or revert it.

**Comment by dpfaffenbauer** [comment]
they just reverted and will release 4.2.3: https://github.com/sabre-io/dav/pull/1365, so a conflict is more than enough then

**Comment by jdreesen** [comment]
It was reverted in https://github.com/sabre-io/dav/pull/1375 and will be released in [v4.2.3](https://github.com/sabre-io/dav/pull/1376)

**Comment by phil-davis** [comment]
Apologies guys for breaking it. Thanks for reporting promptly!

**Comment by dvesh3** [comment]
@phil-davis No worries. Thanks for the quick action 👍
