### ISSUE TITLE
[Bug|Tests]: Session has not been set

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#10980]
### Expected behavior

Exception "Session has not been set" should not occur in tests.

### Actual behavior

After several hours of debugging, I'm still not sure why this is happening.

A redirect test from one of our bundles is failing since symfony 5.4. It states:

```php
$site1 = $I->haveASite('test-domain1.test');

$document1 = $I->haveAPageDocumentForSite($site1, 'en', [], 'en');
$document2 = $I->haveAPageDocumentForSite($site1, 'de', [], 'de');

$redirect = [
    'type'       => 'entire_uri',
    'source'     => '@http://test-domain3\.test@',
    'sourceSite' => null,
    'target'     => 'http://test-domain1.test/de',
    'targetSite' => null,
    'statusCode' => 301,
    'regex'      => 1,
    'priority'   => 99
];

$I->haveAPimcoreRedirect($redirect);
$I->amOnPageWithLocale('http://test-domain3.test', 'de');

$I->seeCurrentHostEquals('test-domain1.test');
$I->seeCurrentUrlEquals('/de');
```

I know, this is a stupid one, I simplified it a bit so that there are no external bundles involved. In fact, this could be a pimcore test. However, this worked until Symfony 5.4. 

It also works if you're going to test it via browser. That's because in a non-test environment, the `initialized_session` service is available in container but not in test environments.

I'm event not sure if this is a real PIMCORE thing at all. 

But if I'm changing the priority of the `RoutingListener` to `125`...
https://github.com/pimcore/pimcore/blob/7099fd160c9b061513df814f937e236cc0486d1e/bundles/CoreBundle/EventListener/Frontend/RoutingListener.php#L65

... than the test works as expected because symfonys `AbstractSessionListener` can be dispatched before!
https://github.com/symfony/symfony/blob/060d3286f04ac52adb0649bfa1025e6ee262d786/src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php#L256

Maybe, just maybe, this is related to https://github.com/pimcore/pimcore/issues/10969?

### Steps to reproduce

Create test like described above.

**Comment by solverat** [comment]
maybe related: https://github.com/symfony/symfony/issues/44546

**Comment by solverat** [comment]
https://github.com/symfony/symfony/pull/44618 fixes that! Let's hope it's going to be merged!

**Comment by brusch** [comment]
[#44618](https://github.com/symfony/symfony/pull/44618) was merged, so I guess we can close this issue then.
