### ISSUE TITLE
[Bug]: Pimcore Translator Closes Transaction

### ISSUE THREAD

**Issue by CountZero1981** [pimcore/pimcore#11004]
### Expected behavior

I create a product or do anything else using a transaction. Inside the transaction I use Pimcore translator. This shouldn't have any effect on my transaction.

### Actual behavior

If a translation entity with a translation key doesn't exists, using translator commits transaction prematurely.

### Steps to reproduce

Open a transaction. Try to translate a key which doesn't exists in the DB yet. Commit the transaction. Receive a DB error "No active transaction".  
DBAL counts transactions correctly, the error comes from the DB in this case.  
According to the MySQL documentation (https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html), `CREATE TABLE` causes an implicit transaction commit.
[models/Translation/Dao.php:148](https://github.com/pimcore/pimcore/blob/9edd80dadbb1c0eff7f64af81f0382a03b0496a5/models/Translation/Dao.php#L140) runs `CREATE TABLE` every time when an unknown key met.
Maybe instead of running this (heavy and in the most cases useless) query it makes sense to store all translations in the same table and add a field `domain` to filter by domain?
Another possible solution, check for table existence separately from attempt to create and before it - should allow to avoid implicit commits in the most cases.

**Comment by CountZero1981** [comment]
another possible solution is to save non-translated entries to memory and dump them to db somewhere in onTerminate.
@dveshp3 what do you think? if any of these solutions is fine, I can implement it.

**Comment by CountZero1981** [comment]
@brusch what do you think about it? let's discuss. I'm ready to implement a solution, just not sure which one would fit.

**Comment by brusch** [comment]
@CountZero1981 yes, collecting the non-translated entries in a service and dump them on terminate sounds like a good solution to me also in terms of performance. Looking forward to your PR. Thanks!

**Comment by brusch** [comment]
@CountZero1981 just a gentle reminder for the PR 😉 Thanks!

**Comment by CountZero1981** [comment]
I've had health problems, will do it soon

**Comment by brusch** [comment]
Fixed by #11426
