### ISSUE TITLE
[Bug]: Brick 'xxxx' not found

### ISSUE THREAD

**Issue by ismetsener** [pimcore/pimcore#11005]
### Expected behavior

/opt/pimcore/bin/console pimcore:maintenance

I expected no error

### Actual behavior

Hi,

after the command:
/opt/pimcore/bin/console pimcore:maintenance
I got the next error:

00:14:53 ERROR     [app] Brick 'LuxuryPaperBag2' not found. Please check table object_brick_store_LuxuryPaperBag2_PRDCTS
00:14:53 ERROR     [app] Brick 'LuxuryPaperBag2' not found. Please check table object_brick_query_LuxuryPaperBag2_PRDCTS
I made a brick 'LuxuryPaperBag2' and used it.
after I delete it.
now I get this error.

### Steps to reproduce

creating a objectbrick,  connect/loing it to a class (for example product class)
after delete the object brick
and running:/opt/pimcore/bin/console pimcore:maintenance

than I get that error

**Comment by CountZero1981** [comment]
`bin/console pimcore:deployment:classes-rebuild`?
https://pimcore.com/docs/pimcore/current/Development_Documentation/Deployment/Deployment_Tools.html#page_Pimcore-Class-Definitions

**Comment by ismetsener** [comment]
I did before, but I get still same message:
13:40:29 ERROR     [app] Brick 'LuxuryPaperBag2' not found. Please check table object_brick_store_LuxuryPaperBag2_PRDCTS
13:40:29 ERROR     [app] Brick 'LuxuryPaperBag2' not found. Please check table object_brick_query_LuxuryPaperBag2_PRDCTS
