### ISSUE TITLE
[Feature]: Object DataType RGBA Color: option to hide the alpha channel

### ISSUE THREAD

**Issue by LosHawlos** [pimcore/pimcore#11002]
### Feature description

We often use the [RGBA Color data type](https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Others.html#page_RGBA-Color) in objects but in almost all cases we don't need the alpha channel.

Feature Request: Add an option to disable and hide the input and selection of the alpha channel.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
