### ISSUE TITLE
[Bug]: getChildren() - method of Document fetches unpublished children

### ISSUE THREAD

**Issue by roland4432** [pimcore/pimcore#11015]
### Expected behavior

```php
$children = Document::getById(1)->getChildren(); //getChilren can be called with false(default) or true (to get unpublished children)
```

should only get published children.

### Actual behavior

This call gets unpublished children. What you need to call (and which is pretty unintuitive) is to do this:
```php
Document::setHideUnpublished(true);
$children = Document::getById(1)->getChildren();
```

Why? Because 
```php
//models/Document/Listing.php:95
...
public function getCondition()
{
    $condition = parent::getCondition();
    if ($condition) {
        if (Document::doHideUnpublished() && !$this->getUnpublished()) {  // <- expression with && will mostly be false, since doHideUnpublished is false by default
            $condition = ' (' . $condition . ') AND published = 1';
        }
    } elseif (Document::doHideUnpublished() && !$this->getUnpublished()) {  // <- same goes with this of course
        $condition = 'published = 1';
    }

    return $condition;
}
...
```

So this brings up 2 questions:
1. Why is `private static $hideUnpublished = false;` in the class models/Document the default? As far as I checked, the default is always to *not* get unpublished documents (or objects)
2. I see that for the ease of access the methods are static (meaning the doHideUnpublished and setHideUnpublished methods), but this is not a good approach and as I mentioned it is not untuitive to have both triggers to _don't show unpublished items_ regarding the _setHideUnpublished_ and call _getChildren_ with false.

=> You could go with either || instead of && in the if clause to check wether one of the options is set or remove the 2 static functions (setter and getter for static $hideUnpublished) since they are not good practice anyways.
Why bad practice? Check this:

Let's say we want to get children of 2 Documents and either published and unpublished or only published children:
```php
Document::setHideUnpublished(true); //needs to be called, since the changed variable is static
$onlyPublishedChildren = Document::getById(1)->getChildren();

Document::setHideUnpublished(false); //needs to be called again
$allChildren = Document::getById(2)->getChildren(false); // false does not have any effect here

Document::setHideUnpublished(true); //aaaaaand needs to be called again
$allChildren = Document::getById(3)->getChildren(false); // now this parameter triggers the query for only published children
```

So you basically need to switch the state of the static $hideUnpublished

### Steps to reproduce

* add a document and a children.
* set the children to unpublished
* get the parent-document and call _getChildren()_ with either true or false
* results in querying all children despite their publish state

**Comment by jdreesen** [comment]
`$hideUnpublished` should be `true` for the frontend context and `false` for the backend context by default. 

Are you in frontend or backend context? 

If you are in frontend context, are you sure there's no `Document::setHideUnpublished(false)` (that doesn't reset it to `true` afterwards) anywhere in your code?

**Comment by roland4432** [comment]
Found the issue within a twig extension gathering some documents for navigation stuff. So yepp, it came up in the frontend and as far as I checked my code, there is no call for the setter to switch it to `false`.

**Comment by brusch** [comment]
@roland4432 thanks for the feedback - so obsolete, right?
