### ISSUE TITLE
[Bug]: Pricing Rules - Saving pricing rule with date range condition leads to "setTime() on bool" error

### ISSUE THREAD

**Issue by asysrieke** [pimcore/pimcore#11028]
### Expected behavior

Saving pricing rules with date range condition should be possible.

### Actual behavior

On saving Pimcore shows an error dialogue with the following message:
![image](https://user-images.githubusercontent.com/15608701/146195465-269b5119-a812-409a-a09f-3d3e57cc14d9.png)
No further stacktrace is given. 

Error is triggered in fromJSON() function in Pimcore\Bundle\EcommerceFrameworkBundle\PricingManager\Condition\DateRangeCondition.

`$starting = \DateTime::createFromFormat('Y-m-d\TH:i:s', $json->starting);`
`$starting->setTime(0, 0, 0);`
` $ending = \DateTime::createFromFormat('Y-m-d\TH:i:s', $json->ending);`
`$ending->setTime(23, 59, 59);`

Starting and ending keys in the decoded json array are not of expected format, therefore DateTime returns null.

### Steps to reproduce

1) Open Pimcore Demo
2) Open arbitrary pricing rule
3) Add a date range condition on tab "conditions" and fill in date values
4) Click "save"

**Comment by dvesh3** [comment]
Fixed by #11050
