### ISSUE TITLE
[Bug]: Classification store - inherited value not shown when value is cleared/empty after save

### ISSUE THREAD

**Issue by simonkey** [pimcore/pimcore#11025]
### Expected behavior

When using inheritance the value of the parent should be shown if a previous override is cleared of a quantity value in the classification store. This means the value should also be removed in the database.

### Actual behavior

The value of the quantity value is set to NULL in the database, but not deleted. Therefore the field is not inactive and doesn't show the inherited value.

In this example the values of min. and max. length and wire diamater has been changed and afterwards emptied. Trying to set the dimension to NULL doesn't clear the entry either.

Screenshot of the issue:
![image](https://user-images.githubusercontent.com/1583145/146173039-85359219-69d2-480d-af3c-b1c8ed024b1f.png)

Entries in the database:
![image](https://user-images.githubusercontent.com/1583145/146173102-46c33f4d-a373-4250-a492-9c92bdff9b70.png)

### Steps to reproduce

Pimcore version: **10.2.6**

Create a data object class and allow inheritance. Add a classification store with a "quantity value"-key definition (no default value).

Add a parent object and fill the quantity value field with some value. Add a child object and set an override. Save the child. Remove the override and save and reload again.

**Comment by simonkey** [comment]
**Update:** 
Tested it with Version 10.2.9 and when changing the Quantity value (e.g. mm) to (empty) the entry is removed after saving the Dataobject. The change or inheritance from the parent is visible after a reload.

**Comment by dvesh3** [comment]
@simonkey yes, you have to clear both value & unit fields to remove the entry from DB, so that it starts inheriting the value from parent again.

The reason for this behavior is that if we start inheriting value from parent with unit defined in the child then it could lead to unwanted situation.

**Comment by simonkey** [comment]
Ok, I understand. I'll close the issue.
