### ISSUE TITLE
[Ecommerce]: Pricing Rules - Do not allow negative discounts

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#11024]
### Expected behavior

Not possible to set negative discounts

### Actual behavior

It is possible to set negative discounts for Cart & Product discount actions, then adds it to to total amount.

### Steps to reproduce

1. Login to the application https://demo.pimcore.fun/admin
2. Navigate to Online shop -> Pricing Rules -> Voucher Discount -> Actions``
3. Enter Negative amount in Cart Discount and click on save.

**Comment by blankse** [comment]
Was fixed by #11206
