### ISSUE TITLE
[Bug]: Filter with > 3000 Options does not open

### ISSUE THREAD

**Issue by matthiashamacher** [pimcore/pimcore#11036]
### Expected behavior

When adding a field with many options through an option provider, it is expected that you could filter that field in the grid.

### Actual behavior

Filtering is not possible as loading of the filters takes too long and lets the browser think that the page crashed.

We have the following loading times:
2000 -> ~ 2s
3500 -> ~ 13s
15000 -> ~ 2m 30s

In the last case, both Chrome and Firefox constantly show that the page isn't working properly, because you cannot do anything until it is loaded completely. The threshold from the browser side seems to be 15s because in the first two cases the notification didn't show

### Steps to reproduce

1. Create two classes
2. Add an option provider to one of them which returns the other class
3. Create > 3000 data objects from which you can select
4. Open the grid, add the field with the options provider as column
5. Try to filter. The Filter popup will show eventually but it takes > 10 Seconds depending on how many data objects you got

I checked a little bit into that issue myself and found that the problem seems to be connected to the presentation of the options rather than loading all the options. This already happens when you add the column to the grid. So, all options are there but showing them inside the list seems to be the problem.

**Comment by dpfahlbusch** [comment]
Maybe this issue is related: https://github.com/pimcore/pimcore/issues/10468

**Comment by matthiashamacher** [comment]
@dpfahlbusch 
Unfortunately not. I did some further testing regarding the #10468 issue and it seems to be better in the newer versions, as you can see in my [Test Results](https://gist.github.com/matthiashamacher/cbb8e3cd8dfaa2bf89d80d142ec73315#results-1).

The issue can be reproduced with the code examples provided in the [Gist](https://gist.github.com/matthiashamacher/cbb8e3cd8dfaa2bf89d80d142ec73315)

**Comment by brusch** [comment]
Hmm, probably this is just too much options for ExtJS and the browser. Not really sure if we can do anything about it ... probably it's better to think about the data-model and use a relation field instead. 

Anyway, we're not going to work on this anytime soon,  however we'd of course accept a PR for that. Therefore I'm closing this issue.
