### ISSUE TITLE
[Bug]: SQL exception on obscure URL with encoded entities

### ISSUE THREAD

**Issue by GALCF** [pimcore/pimcore#11038]
### Expected behavior

Opening an obscure URL should not result in an SQL exception

### Actual behavior

The URL causes an SQL exception:

![An exception occurred while executing 'SELECT id FROM documents WHERE path = ? AND `key` = ?' with params ["\/", "\xaa"]: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_bin,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='](https://user-images.githubusercontent.com/14803394/146352519-b5195dae-fd9a-4900-b44f-466269eb9c39.png)

### Steps to reproduce

Open this URL: https://demo.pimcore.com/%25AA

### Proposed solution

```diff
--- a/models/Document/Dao.php
+++ b/models/Document/Dao.php
@@ -58,7 +58,7 @@ class Dao extends Model\Element\Dao
     public function getByPath($path)
     {
         $params = $this->extractKeyAndPath($path);
-        $data = $this->db->fetchRow('SELECT id FROM documents WHERE path = :path AND `key` = :key', $params);
+        $data = $this->db->fetchRow('SELECT id FROM documents WHERE path = BINARY :path AND `key` = BINARY :key', $params);
 
         if (!empty($data['id'])) {
             $this->assignVariablesToModel($data);
```

**Comment by brusch** [comment]
@GALCF your proposed solution makes sense to me, can you please create a PR for that? (`10.2` branch). 
Thanks a lot!
