### ISSUE TITLE
[Bug]: OptionsProviderResolver::resolveProvider is always called with MODE_SELECT, both for Select and for Multiselect field. Then MultiSelectOptionsProviderInterface does not work because it needs MODE_MULTISELECT.

### ISSUE THREAD

**Issue by sevarozh** [pimcore/pimcore#11030]
### Expected behavior

Provider implemented MultiSelectOptionsProviderInterface must be resolved for MultiSelect field in OptionsProviderResolver.

### Actual behavior

for MultiSelect field is SelectOptionsProviderInterface resolved

### Steps to reproduce

- assign a data provider with MultiSelectOptionsProviderInterface for MultiSelect Field
- open object
- Provider is not called and the options are not displayed

\Pimcore\Model\DataObject\ClassDefinition\DynamicOptionsProvider\SelectionProviderTrait::doEnrichDefinitionDefinition 

`        $optionsProvider = DataObject\ClassDefinition\Helper\OptionsProviderResolver::resolveProvider(
            $this->getOptionsProviderClass(),
            DataObject\ClassDefinition\Helper\OptionsProviderResolver::MODE_SELECT
        );`

**Comment by dvesh3** [comment]
Already fixed in 10.2 version https://github.com/pimcore/pimcore/pull/10167/files#diff-93f22a71bb9681a676a589766af1415bf62c9578960abaf9298f0845552b8ed3R685-R702
