### ISSUE TITLE
[Bug]: Saving object without permissions with keybindings

### ISSUE THREAD

**Issue by BabovicT** [pimcore/pimcore#11047]
### Expected behavior

You are not able to save object if user has no permission to save an object. This is also the case when object has applied workflow that should disable the saving(save or modify = false).

### Actual behavior

User is able to save the object even if he has no permission using keybinding for save.

### Steps to reproduce

Make user that has access to objects(list, view) but has no permission to publish or save the object. Since fields on object aren't disabled user can enter new value and it will save them when publishing/unpublishing the object.

1. Permissions. 
This only happens when object is unpublished and user has unpublish allowed or orbject is published and user can publish objects. 
If user has permission to publish/unpublish object but has no save permission he is still able to save data with keybindgs. Maybe this is not bug but it seams odd. When you use ctrl+S to save then it send data to save route with task=publish/unpublish.
```        else if (el.object) {
            if (el.object.data.general.o_published) {
                el.object.publish();
            } else {
                el.object.unpublish();
            }
        }
```
Shouldn't it check here if object can even be saved by user before, and in 
``` 
if ($request->get('data') )

to

if ($request->get('data') && $object->isAllowed('save'))
``` 
it should also see if object can be saved before getting data from request.

Maybe this is intentional to always save data with publish and unpublish.

2. Workflows
Almost the same situation. If user has permission to publish or unpublish object then it will also trigger the save with using keybinding. For this scenario above if logic wouldn't work because user is allowed to save objects but workflow should deny that. Not sure where in code is logic for that, i didn't have time to search for it today. But somewhere in /get route it triggers that logic to override user permission based on workflow so code exists it should just be added to /save route also.

If you think that this is indeed bug and not intended behavior then i can provide PR for one or both situations depending if first is the bug or not.

**Comment by dvesh3** [comment]
Concerning the main reported issue. It is not reproducible anymore(ctrl+s when user no save & publish/unpublish permissions):
![image](https://user-images.githubusercontent.com/5137917/155564668-5e67ed45-98c0-4040-b7d3-423044822a74.png)

For points 1 & 2, when a user has publish/unpublish permission, it is not necessary to have save permission to perform these actions. As save permission is mainly about saving a version which is not possible even with hotkeys. On save hotkey, based on the object status the task is assigned on the request .i.e., task=publish/unpublish.

I got your point, regarding saving the data with only publish/unpublish permission, but this is intended as the publish status cannot be changed without saving the object itself.

**Comment by dvesh3** [comment]
Please feel free to come back, if you have any further questions regarding the issue. thanks!
