### ISSUE TITLE
[Improvement]: option to cancel asset download / upload

### ISSUE THREAD

**Issue by TheCodyKnight** [pimcore/pimcore#11053]
### Improvement description

In Pimcore Admin Backend, in the Asset area, once a (bulk) asset download or upload has been started, there is no way to abort it, except for reloading the website. This mainly is an issue when uploading/downloading a bigger bulk of images.

<img width="522" alt="Bildschirmfoto 2021-12-17 um 10 34 50" src="https://user-images.githubusercontent.com/19357290/146526922-de8d44b7-8cc2-4636-b19d-15232f5418e7.png">

A "cancel upload" / "cancel download" button would be a user-friendly addition to this otherwise nice feature.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
