### ISSUE TITLE
[Bug]: PCX Update tables in DataObject migration

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#11059]
### Expected behavior

Tables in DataObjects get migrated to new format during Pimcore Update Migrations. 

Previously the array got serialized:
I.e. empty table was `s:0:"";` --> now it's a null value

### Actual behavior

After the update an error is shown:

`Pimcore\Model\DataObject\MyObject::setMyTable(): Argument #1 ($myValue) must be of type ?array, string given, called in /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php on line 206`

### Steps to reproduce

Create a class with a table field in Pimcore < v10, perform Update to Pimcore >10, load the object.

## Suggested solutions:

1. Writing migration 
2. 
Changing https://github.com/pimcore/pimcore/blob/10.x/models/DataObject/ClassDefinition/Data/Table.php#L357 
to
`if ($data === null || $unserializedData === null || $unserializedData === "") {`

so empty strings get considered as well.

**Comment by dvesh3** [comment]
Fixed by #11061
