### ISSUE TITLE
[Bug]: Lacking docker (compose) documentation

### ISSUE THREAD

**Issue by stschatzl** [pimcore/pimcore#11060]
### Expected behavior

Having docker support for current Pimcore version (10), also for docker-compose.

Also, there is no description of the provided tags and no versions on dockerhub.
At least, provide description, some "latest" tag for the greatest and latest and then for every version tags.

### Actual behavior

just a link on https://hub.docker.com/r/pimcore/pimcore to the outdated github repo

### Steps to reproduce

Open browser with https://hub.docker.com/r/pimcore/pimcore.

**Comment by brusch** [comment]
There's a link pointing to the docs: 
https://github.com/pimcore/docker#pimcore-php-fpm-docker-image
Also for starting new projects: https://github.com/pimcore/skeleton#docker
