### ISSUE TITLE
[Bug]: Pimcore\Model\DataObject PHPdoc getList() wrong

### ISSUE THREAD

**Issue by leuchtdiode** [pimcore/pimcore#11071]
### Expected behavior

The getList()-Method of Pimcore\Model\DataObject\Concrete accepts an array as config as the first parameter.
The PHPdoc for this method in generated DataObject classes (Pimcore\Model\DataObject\*) states that getList() does not accept any parameter. This leads to code completion errors in the IDE.

PHPdoc should be

@method static \Pimcore\Model\DataObject\*\Listing getList($listConfig)

### Actual behavior

PHPdoc is

@method static \Pimcore\Model\DataObject\*\Listing getList()

in generated DataObject classes.

### Steps to reproduce

Let pimcore generate a DataObject class and look for @method static \Pimcore\Model\DataObject\*\Listing getList()

**Comment by leuchtdiode** [comment]
I wanted to submit a pull request, but I'm getting "Permission denied" when pushing. Sorry, but this is my first pull request ;)

Do I need any permission?

**Comment by leuchtdiode** [comment]
#11084

**Comment by brusch** [comment]
Fixed by #11087
