### ISSUE TITLE
[Bug][Dashboards] Buttons of Portlets are not clearly visible

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#11074]
### Feature description

![image](https://user-images.githubusercontent.com/8792145/147065158-bb711a00-4ea5-4aa7-9bbd-4c9ca363e2c9.png)

**Comment by mcop1** [comment]
I would suggest to change the color of the buttons, e.g. upload dialog in data importer
![image](https://user-images.githubusercontent.com/89011527/150107714-969d6fd3-92bd-4757-aebd-33263bc374a6.png)

**Comment by fashxp** [comment]
related ... https://github.com/pimcore/advanced-object-search/issues/132

**Comment by fashxp** [comment]
fixed via #11271
