### ISSUE TITLE
[Bug]: Custom Editor Configuration of WYSIWYG field type in class definition breaks Admin-UI

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#11077]
### Expected behavior

A custom editor configuration (CKEditor) is required for a WYSIWYG field type in a class definition.

### Actual behavior

The mentioned custom editor configuration in the [documentation](https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Text_Types.html) of a WYSIWYG text field type breaks the Admin UI.

Class Definition example on demo.pimcore.com:
![Pimcore_Definitionn](https://user-images.githubusercontent.com/33122456/147080375-2c72f768-a3d1-4f30-8d77-4f0886a8f720.png)

Admin UI:
![Pimcore_Object](https://user-images.githubusercontent.com/33122456/147080389-b1d1f1fa-14ff-4227-8c8d-ee6f062219fa.png)

### Steps to reproduce

1. Add the configuration to a WYSIWYG field type of a class.

Either this:
`{
  toolbarGroups : [ { name: 'links' }],
  enterMode: CKEDITOR.CKEDITOR.ENTER_BR,
}`

Or this:

`{
 'enterMode': 2,
 'toolbar': [
        {
            'name': 'basicstyles',
            'items': ['Bold']
        }
    ]}`

2. Go to an object of the class. The UI is broken as seen on the screenshot above.

**Comment by NiklasBr** [comment]
I think the docs use are incomplete, the JSON need to validate and I can get the following configuration to work:
```json
{
  "toolbarGroups": [
    {"name": "links"}
  ],
  "enterMode": 2
}
```
and this:
```json
{
  "enterMode": 2,
  "toolbar": [
    {
      "name": "basicstyles",
      "items": [
        "Bold"
      ]
    }
  ]
}
```

**Comment by ghost** [comment]
Thanks, this works.

So not a bug, just the snippet in the documentation is not valid.
It's rather an improvement, as Pimcore 6.9 tolerated invalid JSON with single quotes.
