### ISSUE TITLE
[Bug]: Content page scrolls up by itself

### ISSUE THREAD

**Issue by katharina-kopf** [pimcore/pimcore#11081]
### Expected behavior

You can scroll down the content page

### Actual behavior

When you scroll down, the content page scrolls back up by itself

### Steps to reproduce

Copy the master tree and paste it with "Paste (inheritance) > Paste language (recursive), updating references" and start overwriting the content. When you have to scroll down to continue your work, the content page will scroll up a little bit by itself. Again and again ...

Please have a look at the screen video:
https://user-images.githubusercontent.com/52708291/147104732-75df8cbb-2c1a-4cca-b3f2-c71fca75586d.mp4

Thank you!

**Comment by SaschaHowe** [comment]
Hey, 

I think it's the `Ext.Tooltip` with `showDelay > 0`
It happens everywhere that thing is used. We notice it mostly on the image editable. 

No idea how this can be fixed without upstream fix from ExtJS or removing the `showDelay`

Greetings,

**Comment by brusch** [comment]
@SaschaHowe Thanks for your feedback, do you know where `ExtJs.Tooltip` with `showDelay > 0` is used?

**Comment by SaschaHowe** [comment]
Hey, 

first of all, sry it's called `Ext.Tooltip` not `ExtJs.Tooltip`. May bad. 

For Example here: https://github.com/pimcore/pimcore/blob/10.x/bundles/AdminBundle/Resources/public/js/pimcore/document/edit/startup.js#L172

This is what is creating page jumping for us in our web (or in the demo application) You hover over an Image Editable and scroll down before the second Tooltip is show (there are 2, on instant one with delay) and then the page jumps. It's a bit tricky to intentionally get in jumping but it happens a lot when you have many images on a page. 

Hope this helps?
