### ISSUE TITLE
[Bug][DAM] [View] - Trying to set Focal Point results in blue image 

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#11092]
### Feature description

HOW TO REPRODUCE

-Open image (jpg/png, etc.)
-Click on "Set Focal Point" --> Red dot appears withing the image
-move it to a random spot
-image is blue (marked)

![image](https://user-images.githubusercontent.com/8792145/147473361-8612dbb7-6f1b-4286-9de2-cfd75eb4a4f3.png)

**Comment by brusch** [comment]
Fixed by #11394
