### ISSUE TITLE
Cache::save forced or norma is doing nothing because of 'write lock'

### ISSUE THREAD

**Issue by BlackIkeEagle** [pimcore/pimcore#1109]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [x] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [x] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [x] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [x] There's no existing ticket for the same issue

### Expected behavior 

When Cache::save() is called something ends up in the cache (test example redis)

especially when Cache::save() is called with force you would want it to be sent to your cache immediatly.
  
### Actual behavior

Nothing is added to the cache because there is a timestamp set in: 

~~~
protected static $writeLockTimestamp;  
~~~
  
### Steps to reproduce  
 
Use translations before adding something to the cache

### Code example 
```php
// your code
$translate = null;
if (\Zend_Registry::isRegistered('Zend_Translate')) {
     $translate = \Zend_Registry::get('Zend_Translate');
}
// for the sake of the example assume $translate is filled an not null
$someOuputString = $translate->translate("Lets Translate This");

/**
 * because of the translate clearTags is called,
 * see followin partial stacktrace from xdebug
 * [0] Pimcore\Cache::setWriteLock @ /home/ike/src/pimcore/pimcore/lib/Pimcore/Cache.php:501
 * [1] Pimcore\Cache::clearTags @ /home/ike/src/pimcore/pimcore/lib/Pimcore/Cache.php:625
 * [2] Pimcore\Model\Translation\AbstractTranslation::clearDependentCache @ /home/ike/src/pimcore/pimcore/models/Translation/AbstractTranslation.php:163
 * [3] Pimcore\Model\Translation\AbstractTranslation\Dao->save @ /home/ike/src/pimcore/pimcore/models/Translation/AbstractTranslation/Dao.php:67
 * [4] Pimcore\Model\Translation\AbstractTranslation->save @ /home/ike/src/pimcore/pimcore/models/Translation/AbstractTranslation.php:274
 * [5] Pimcore\Model\Translation\AbstractTranslation::getByKey @ /home/ike/src/pimcore/pimcore/models/Translation/AbstractTranslation.php:217
 * [6] Pimcore\Model\Translation\AbstractTranslation::getByKeyLocalized @ /home/ike/src/pimcore/pimcore/models/Translation/AbstractTranslation.php:257
 * [7] Pimcore\Translate->translate @ /home/ike/src/pimcore/pimcore/lib/Pimcore/Translate.php:155
 * ...
 * 
 * Now we have a timestamp in $writeLockTimestamp;
 */

// forced cache save
\Pimcore\Cache::save(['data' => 'bla', 'more' => 'data'], 'my_cache_key', [], 3600, 0, true);

// nothing is saved in cache because we hit the following code in \Pimcore\Cache see snippet of \Pimcore\Cache below
/**
 * self::hasWriteLock() returns true so nothing was saved
 */
```

``` php
// \Pimcore\Cache line 337 in pimcore 4.4.1
    /**
     * @param $data
     * @param $key
     * @param array $tags
     * @param null $lifetime
     * @param int $priority
     * @param bool $force
     * @return bool|void
     */
    public static function save($data, $key, $tags = [], $lifetime = null, $priority = 0, $force = false)
    {
        if (!$force && php_sapi_name() == "cli") {
            return;
        }

        if (self::getForceImmediateWrite() || $force) {
            if (self::hasWriteLock()) {
                return;
            }

            $data = serialize($data);
            return self::storeToCache($data, $key, $tags, $lifetime, $force);
        } else {
            if(count(self::$saveStack) < self::$maxWriteToCacheItems) {
                $data = serialize($data);
                self::$saveStack[] = [$data, $key, $tags, $lifetime, $force];
            }
        }
    }

```

So our question is why is cache saving blocked because of the translation triggering clearTags

**Comment by fashxp** [comment]
this is actually a wanted behavior. as soon as any save operation takes place in a process, the cache gets write locked. this is necessary to prevent elements that are not valid any more from going into cache and therefore to prevent cache inconsistency. 

this should only happen as long as the translation key 'Lets Translate This' is not translated in translations. as soon as the key is available and no save is called, it should go into the cache. 
can you confirm that?

**Comment by BlackIkeEagle** [comment]
I should check this, because I guess the translate will only add 1 per request, so the page I was testing has a lot of new translates.

**Comment by fashxp** [comment]
closed due to inactivity
