### ISSUE TITLE
[Bug]: No route found for "GET http://example.com/image.png"

### ISSUE THREAD

**Issue by rpayanm** [pimcore/pimcore#11099]
### Expected behavior

Show the image.

### Actual behavior

It gives a 404 error.

### Steps to reproduce

Version: `Pimcore Platform (v10.2.7|82dae6902d9a78c48e8de9e4fdbd2ecf0cec7816)`

1. Go to assets.
2. Right-click on Home -> Add Asset(s) -> Upload Files, upload an image.
3. Click on the newly added image, click on the info icon and select and copy the public URL.
4. Paste the URL on a new tab and you should see this error:

```
No route found for "GET http://example.com/image.png"
```

**Comment by brusch** [comment]
Seems to be an issue with your setup, works on our public demo: 
https://github.com/pimcore/pimcore#demo-community-edition
