### ISSUE TITLE
[Bug][DAM] [View] Focal point cannot be set after switching between "Standard Preview" and "360 Viewer" 

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#11093]
### Feature description

HOW TO REPRODUCE

-Open Image
-Set Focal point
-Change to "360 Viewer"
-Change back to "Standard Preview"
-Set Focal point does not work anymore

**Comment by mattamon** [comment]
@fashxp is the 360 Viewer obsolete?
I cannot find it anymore in the code base.

**Comment by fashxp** [comment]
probably, let's close that.
