### ISSUE TITLE
[Feature]: make vrana/adminer an optional, suggested dependency

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#11102]
### Feature description

Currently, Pimcore is requesting **a lot of dependencies**, some of which are more important than others.

[One example is `vrana/adminer`](https://github.com/pimcore/pimcore/blob/404fae9c61ac05e48e4432d31a456a358984428f/composer.json#L148), which is integrated in the admin. From my current experience using Pimcore, I have yet to use it, but it's still getting installed and is allowing logged in Pimcore admins to access the database management, which is not what should happen by default.

Also, the package itself seems a bit iffy, for one thing it produces `Warning: Ambiguous class resolution` for Composer when installing it.

My suggestion is to remove it as a must have dependency. It could be suggested by Pimcore, then downstream can require it themselves and Pimcore recognizes it's installed and adds it in the UI same as currently. It does allow developers to also **not** have it.

**Comment by solverat** [comment]
+1 +1

**Comment by brusch** [comment]
I'm ok with separating Adminer out into a bundle. Contributions are welcome.

**Comment by brusch** [comment]
Closed in favor of #11105 as it is about the same topic.
