### ISSUE TITLE
[Bug]: getChildren() method of AbstractObject results in doctrine SyntaxErrorException error when object has null id

### ISSUE THREAD

**Issue by rjankiew** [pimcore/pimcore#11104]
### Expected behavior

when calling `->getChildren()` on newly created object (before the first save), empty array should be returned.

### Actual behavior

In version 10.2.7 (not sure in which version exactly this change happened) newly created objects have `id=null` before the first save. As a result, Doctrine\DBAL\Exception\SyntaxErrorException exception is thrown.

### Steps to reproduce

Create a new object of class that inherits from AbstractObject class. Do not save that object. Call `->getChildren()` method on it.

**Comment by blankse** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/11111
