### ISSUE TITLE
[Bug]: ON DUPLICATE KEY UPDATE will set row id to 0 if 2 processes try to insert the same value at the same time

### ISSUE THREAD

**Issue by HaaseIT** [pimcore/pimcore#11109]
### Expected behavior

Does not set ID to 0

### Actual behavior

Sets ID to 0

### Steps to reproduce

Let me explain where this comes from and why this might be an edge-case for the most users:

I have a project, where the customer uploads Images that contain keywords in the metadata.

When the images are added, I will look for Tags that have the same name as each of these keywords. If there is no tag like that, I will create one like this:

`
        $tag = new PimcoreTag();
        $tag->setName($name);
        $tag->setParentId(0);
        $tag->save();
`

Now, the issue is, if the customer uploads multiple images at the same time (as it is almost always done) and if multiple images have the same keyword, it will try to create the tag multiple times simultaneously and run into timing problems.

First Tag is created and gets its insertId, but another instance has also already started inserting the tag. This would normally break since you cannot insert it again because it has the same IdPath.

But because of the `ON DUPLICATE KEY UPDATE` in Pimcore\Db\PimcoreExtensionsTrait::insertOrUpdate() it will update the row and since this will have the id in the fields after the UPDATE with the value of NULL, mariadb/mysql will update the id to 0.

Statement would look like this:

`INSERT INTO `tags` (`id`, `name`, `parentId`, `idPath`) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE `id` = ?, `name` = ?, `parentId` = ?, `idPath` = ?`

with these values for example:

`[null,"Foo",179,"\/179\/",null,"Foo",179,"\/179\/"]`

If the field id would be removed for the second set, this would not happen. Maybe some table locking might also help.

As a footnote I would like to say that this might in rare cases also occur for other tables for high-frequency installations, where for example multiple editors try to add the same thing simultaneously although this would be extremely rare I guess.

Nonetheless, it is an issue that might occur and that for others might be nearly impossible to track down because they don't have it occur in the frequency that I have.

**Comment by brusch** [comment]
For me this is not reproducible, so we'd need more details on it how to reproduce it, or even better, if you could provide a PR with the fix. It also sounds a bit weird to me, because the PK if the table `tags` is `AUTO_INCREMENT`: 

https://github.com/pimcore/pimcore/blob/3f0281828d513b210f389193d66f2d67b5ed6903/bundles/InstallBundle/Resources/install.sql#L475

**Comment by HaaseIT** [comment]
Good Morning.
This occurs when one process inserts the row with insertOrUpdate() and another process also uses the insertOrUpdate() for a row with equal content.

So, the first process will do the insert while the second also tries to insert it. Since the query uses ON DUPLICATE KEY UPDATE, it will try to insert but a row with the same composite key is already there. Since both processes think, this is an insert, they will have NULL as value for the primary key. The first process inserts correctly, the second does the on duplicate key update and has NULL as value for the primary key, so the already inserted row gets updates with NULL as value for the primary key, which mysql casts to 0.

I can prepare a pull request for one possible solution, that would be, to check if the field id is in the fleid list and if its value is null for the update arguments.

If this is fine for you, please just give me a quick info on which branch I should base it.

**Comment by brusch** [comment]
Thanks - PR should be based on  `10.2` - looking forward to your PR! Thanks again!

**Comment by HaaseIT** [comment]
This will be resolved by: https://github.com/pimcore/pimcore/pull/11159
