### ISSUE TITLE
Disabling the areablocks toolbar removes the icon on the areablocks selector

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1110]
Tested on the the last stable version.
When disabling the toolbar (parmeter "toolbar" set to false):
```
echo  $this->areablock("content", [
    'toolbar' => false
]); 
```

The selector doesn't display no more the icons:
![bug no toolbar](https://cloud.githubusercontent.com/assets/9025839/21024702/c335135a-bd85-11e6-9736-5a26c395df40.png)

**Comment by weisswurstkanone** [comment]
fixed in build 4026
