### ISSUE TITLE
[Improvement]: Tag Tree collapses whenever changes are made to Tags

### ISSUE THREAD

**Issue by HaaseIT** [pimcore/pimcore#11114]
### Improvement description

Whenever you do changes on the tag tree, the whole tree will be collapsed. This is quite annoying.

Is it possible to keep the tree open, just as it was when the edit was started?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
