### ISSUE TITLE
[Bug]: Could not delete item

### ISSUE THREAD

**Issue by Dau-Duc-Hai** [pimcore/pimcore#11113]
### Expected behavior

Cannot delete assets. Find out that, thumbnails (in var/tmp/ folder) are not apache (www-data) owner

### Actual behavior

System alert cannot delete then delete folder instead

### Steps to reproduce

Try to delete assets

**Comment by brusch** [comment]
Fix your permissions ...

**Comment by Dau-Duc-Hai** [comment]
Can you show me? the website / apache run under www-data and I thinks www-data should the account to generate thumbnails? Please help
