### ISSUE TITLE
Drag and drop areablock doesn't work on last stable version 4.4.1 (b4008)

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1111]
On the last stable Pimcore, dragging areablock from the toolbar doesn't work (forbidden icon and so cannot be realeased) as soon as the page is scrolled. If you just open the document and drag an area without scrolling, drag and drop work ok.

You will find a basic test page here:
[test-drag.zip](https://github.com/pimcore/pimcore/files/640412/test-drag.zip)

I think it is linked maybe to: https://github.com/pimcore/pimcore/issues/1089 , but as it occurs on the stable version with ExtJS 6.0, i opened a separate issue. It occurs as soon as the page is scrolled, so i don't know if it is a margin problem.

Maybe a separate patch could be realeased as it prevent the use of areablock toolbar on the stable version and the next realease will be only in some times i think (as extjs 6.2 migration is on the work, so great! :smiley: ).

**For people having this problem, here is a temporary workaround:**
As a workaround for now is disabling the areablock toolbar so enduser doesn't get this problem.
As seen here, https://www.pimcore.org/docs/latest/Documents/Editables/Areablock/index.html, the "toolbox" parameter could be set to false.

Thanks.

**Comment by fashxp** [comment]
hmm, I cannot reproduce this on our demo instance. I added your test-template but d&d just works fine.
are you on the latest build?

**Comment by Yivan** [comment]
I encounter the problem on the last stable version 4.4.1 build 4008, using Chrome (didn't try Firefox), with the file i joined to the issue.

As soon as I get time later in this day, i will try again on another fresh install (last stable) and several browsers, and will ke you updated. Thanks.

**Comment by Yivan** [comment]
I just made some further test, downloading last stable version and using areabriks from demo.
All work as expected and the bug is no more here.
It is really strange as my other version with the bug is the same build. But it seems to be a problem on my side so. I will investigate it.

You can close this issue, sorry about this false alert.
Thanks.

**Comment by fashxp** [comment]
thx for your support.
