### ISSUE TITLE
[Bug]: Unable to edit/save a document when it contains an empty property of type document

### ISSUE THREAD

**Issue by LosHawlos** [pimcore/pimcore#11136]
### Expected behavior

I want to be able to edit and save a document.

### Actual behavior

Editing triggers an error:

(reproduced on demo.pimcore.com and locally in Pimcore 10.2.7)

> Pimcore\Model\Element\Service::correctPath(): Argument #1 ($path) must be of type string, null given, called in /var/www/html/vendor/pimcore/pimcore/models/Document.php on line 230
> 
> Server threw exception - could not perform action. Please reload the admin interface and try again.

It is caused by the ajax call to `/admin/page/save-to-session` or `/admin/page/save?task=autoSave` that posts the document properties, and sometimes for an empty property of type "document" the value is null (which triggers the error) and sometimes  the value is an empty string (which works fine).

The error then happens because the posted json data for the properties ist processed with almost no data validation.
In case of a property of type "document" this will pass down the null value but the type hint for a string is set:

> Timestamp: Wed Jan 05 2022 14:21:21 GMT+0100 (Mitteleuropäische Normalzeit)
> Status: 500 | Internal Server Error
> URL: /admin/page/save?task=autoSave
> Method: PUT
> Message: Pimcore\Model\Element\Service::correctPath(): Argument #1 ($path) must be of type string, null given, called in /var/www/html/vendor/pimcore/pimcore/models/Document.php on line 230
> Trace: 
> in /var/www/html/vendor/pimcore/pimcore/models/Element/Service.php:829
> #0 /var/www/html/vendor/pimcore/pimcore/models/Document.php(230): Pimcore\Model\Element\Service::correctPath(NULL)
> #1 /var/www/html/vendor/pimcore/pimcore/models/Element/Service.php(396): Pimcore\Model\Document::getByPath(NULL)
> #2 /var/www/html/vendor/pimcore/pimcore/models/Property.php(79): Pimcore\Model\Element\Service::getElementByPath('document', NULL)
> #3 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php(101): Pimcore\Model\Property->setDataFromEditmode(NULL)
> #4 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/PageController.php(493): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\DocumentControllerBase->addPropertiesToDocument(Object(Symfony\Component\HttpFoundation\Request), Object(Pimcore\Model\Document\Page))
> #5 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/PageController.php(229): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\PageController->setValuesToDocument(Object(Symfony\Component\HttpFoundation\Request), Object(Pimcore\Model\Document\Page))
> #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(152): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\PageController->saveAction(Object(Symfony\Component\HttpFoundation\Request), Object(Pimcore\Document\StaticPageGenerator))
> #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
> #8 /var/www/html/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
> #9 /var/www/html/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
> #10 {main}

### Steps to reproduce

I can not reliably reproduce it but got the error sometimes using either this 2 ways on demo.pimcore.com:

**A) Delete the document which is used in a property of an other document**

1. Create a new document "aaa" and publish it.
2. Close document "aaa"
3. Create a second document "bbb"
4. In document "bbb" add a property "aaa"of type "Document" and drag document "aaa" onto it.
5. Close document "bbb"
6. Delete document "aaa"
7. Open document "bbb"
8. In the content of document "bbb" add a "Blockquote" and switch the Orientation drop down to a different value
9. This will trigger the reload of the document and the error will appear.

**B) Add empty property an continue editing of the content directly**
1. Create a new document "ccc".
4. In document "ccc" add a property "ccc"of type "Document" and leave it empty.
5. Switch directly back to the edit tab
8. Now add a "Blockquote" and switch the Orientation drop down to a different value
9. This will trigger the reload of the document and the error will appear.

**Comment by brusch** [comment]
Fixed by #11143
