### ISSUE TITLE
Cache - writelock across parallel processes

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#1113]
if a cache write lock is set, write lock is active for current process (due to [static variable](https://github.com/pimcore/pimcore/blob/76bcbe5460e363da4e4f5ad6e1204e2e206d2e4b/pimcore/lib/Pimcore/Cache.php#L93-L93)) and is active for all other processes (due to added [cache entry](https://github.com/pimcore/pimcore/blob/76bcbe5460e363da4e4f5ad6e1204e2e206d2e4b/pimcore/lib/Pimcore/Cache.php#L505-L505)). 
at the end of the 'cache locking process' the write lock is removed during [shutdown](https://github.com/pimcore/pimcore/blob/3e41eec10559d9e2634276f6311ef2710c150835/pimcore/lib/Pimcore.php#L1020-L1020). 
so far so good. 
but what if a second parallel process is running longer that the first (cache locking) process and writes 'old' entries that were changed by the first process into the cache and therefore creates inconsistent cache?
shouldn't be the write lock kept for a certain amount of time after the process shut down? or can that even be prevented?

**Comment by brusch** [comment]
This is already the case: 
https://github.com/pimcore/pimcore/blob/c62924ca5c3d0c482a71097cb0231aff143208d6/lib/Cache/Core/WriteLock.php#L137
