### ISSUE TITLE
[Bug]: POEditor links for translation in README.doc works no more.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#11138]
### Expected behavior

The links given in README.doc should work:
- https://poeditor.com/join/project/VWmZyvFVMH
- https://poeditor.com/join/project/XliCYYgILb

### Actual behavior

On the POEdit page, it returns `There are no languages available to translate in this project.`

### Steps to reproduce

Just go on the links ; )

Thanks!

**Comment by brusch** [comment]
Fixed ... they archived our projects, no clue why, but reopened them now 😊
