### ISSUE TITLE
[Bug] Admin/Shared Translations not working

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#11139]
### Expected behavior

can edit translations

### Actual behavior

cannot edit translations

### Steps to reproduce

open admin translations and try to edit a translation after filtered ... 

![image](https://user-images.githubusercontent.com/8792145/148286779-ea11526f-0ad9-46c8-95d4-e0981951b7ab.png)

**Comment by brusch** [comment]
This particular issue I wasn't able to reproduce (I really tried hard 😉), but I've stumbled upon other issues: 
The row-editor seems to not properly update (width and fields) when changing the amount of columns.

**Comment by brusch** [comment]
Also using the context menu with "Edit as HTML" doesn't seem to work properly.
