### ISSUE TITLE
Improvement: forgotten password email in multilanguage and event admin.login.lostpassword

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1114]
Actually the email sent by the "Forgotten password" link on the login page is sended only in english and is really short/not very friendly. See here please: https://github.com/pimcore/pimcore/blob/master/pimcore/modules/admin/controllers/LoginController.php#L43

1-
The purpose of this improvement is made the mail translated, maybe using $this->translate and add the translation in the pimcore poedit so it could be translated.

2-
And as extra improvement, maybe we could left to developpers to handle the emailing process, so a custom email could be make. Maybe an event `admin.login.lostpassword ` could be added. The hook sould send back a value **so we can disable the default sending mail**. Paramters send by the hook could be `$user` and `$loginUrl`.

Those are small improvement, and i think they make senses when many users, from different country, are created in a Pimcore instance and log in it.
With the hook, developper could make a custom email with company logo, add a "Hello XXX, ..." making it more human and company branded to give better confidence in such a security feature.

Thanks.

**Comment by fashxp** [comment]
pull requests are welcome ;-)

**Comment by Yivan** [comment]
Thanks fashxp, ok i will try to make a PR based on the second option: an event hook so developper can make custom email for different langage.

**Comment by brusch** [comment]
closed by #1179
