### ISSUE TITLE
[Bug]: "false" sortOrder concated into sql statement in DataObjectController

### ISSUE THREAD

**Issue by rjankiew** [pimcore/pimcore#11155]
### Expected behavior

When reordering tree elements sorted by index, no error should appear, and elements in tree should be reordered.

### Actual behavior

In `reindexBasedOnSortOrder` method of `Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject/DataObjectController` class, `$currentSortOrder` can in some cases have `"false"` value, leading to error:
![obraz](https://user-images.githubusercontent.com/89988908/148773425-72f8ce86-001c-4b8f-bff7-4a716ea88222.png)
![obraz](https://user-images.githubusercontent.com/89988908/148773440-ddaf26c0-861b-4443-a253-040e105bae5f.png)

### Steps to reproduce

use order by index option:
![obraz](https://user-images.githubusercontent.com/89988908/148774873-27e20416-8dc2-4bf3-aac9-aacfe64319b7.png)
on an object with large number of children

**Comment by brusch** [comment]
Not really sure how this could happen, but validating the input is anyway not a bad idea 😉 
Fixes by #11156
