### ISSUE TITLE
Custom layout panels

### ISSUE THREAD

**Issue by ckogler-elements** [pimcore/pimcore#1117]
# Custom layout panels

To implement custom layout panels we need a hook to change the "allowedTypes" in the class.js.

With the hook we are more flexible than with the "allowIn" params, which is used in the data types because otherwise we would have to modify other layout-components...

**Comment by fashxp** [comment]
please add documentation, thx

**Comment by ckogler-elements** [comment]
Has been added
https://www.pimcore.org/docs/latest/Extending_Pimcore/Plugin_Developers_Guide/Plugin_Backend_UI.html
