### ISSUE TITLE
[Bug]: Inconsistent getter behaviour when getting values from object brick in preSave listener

### ISSUE THREAD

**Issue by rjankiew** [pimcore/pimcore#11181]
### Expected behavior

No matter what fields user edits on the UI, the backend getters of object should behave in consistent manner. 

### Actual behavior

There are differences in getter behaviour, depending on whether an autosave was triggered during editing.

### Steps to reproduce

Create an object with a object brick, that has a ManyToManyObjectRelation field (object→object brick→relation field). Add one other field (e.g. input) on object brick level. Add a relation and fill in the input and save the instance. Add a listener that will "catch" this object type on preSave.

Behaviour 1:
Go to created object, remove the relation and save object. In the listener, if you call: `$relation = $object->getTestBrick()->getTestRelation()` the value of `$relation` will be `null`. This I would call expected behaviour.

Behaviour 2:
Go to created object, and edit the input field - the edit will trigger an autosave. Than, remove the relation and click save. In the listener, if you now try to call  `$relation = $object->getTestBrick()->getTestRelation()`, value of `$relation` will be a relation object. This in not expected.

This difference in behaviour did not occur in 10.2.1. I suspect it may be related to this changes https://github.com/pimcore/pimcore/pull/10820 and this issue https://github.com/pimcore/pimcore/issues/10786

**Comment by fashxp** [comment]
probably it is because getting published version of element vs. getting latest version of element.

need to check, if event contains the latest version of an element or the published version.
