### ISSUE TITLE
[Bug]: No frontend_prefixes in Thumbnail when original file is used

### ISSUE THREAD

**Issue by woellundwoell** [pimcore/pimcore#11182]
### Expected behavior

Prefix src-attributes in picture / image tags rendered by thumbnail config "ORIGINAL" when set in config

`pimcore:
     assets:
        frontend_prefixes:
            source: https://[domain]/asset`

plus Flysystem config to SFTP-Adapter in our case

### Actual behavior

No prefix is set for picture / image tags rendered by thumbnail config "ORIGINAL"

### Steps to reproduce

- Set symphony config (e.g. in config.yaml) 
- Create an image thumbnail using format "ORIGINAL"
- Try to display a svg Asset by (twig code)

`asset.thumbnail('thumbnailName').getHtml([some attributes])`

The reason could be in https://github.com/pimcore/pimcore/blob/b92cbf2083983b5dfeedd40f1fee0f575dfa4a20/models/Asset/Thumbnail/ImageThumbnailTrait.php#L295-L307

A fix could be
<img width="1175" alt="Bildschirmfoto 2022-01-13 um 14 13 20" src="https://user-images.githubusercontent.com/16014748/149336982-3e4d0a77-cd2a-4c75-bd5a-5f977ea919db.png">

Should we provide a PR?

**Comment by brusch** [comment]
@woellundwoell agree, this should fix the issue. A PR would be nice, please don't forget to base it on the `10.3` branch, as it is a bug fix. Looking forward to the PR 😊

**Comment by brusch** [comment]
@woellundwoell 🏓😉 Thanks

**Comment by blankse** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/11769
