### ISSUE TITLE
Internal execution interval for cron tasks

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#1118]
For example, like in Magento. Magento is reading the configuration for defined cron tasks and each cron task can be configured for execution on different schedule using the cron time definition syntax. So basically what the request is about, is a implementation for mechanism allowing internal scheduling of Pimcore maintenance tasks.

**Comment by mk-conn** [comment]
Oh yes.. that would be very welcome! Something like Laravels scheduled tasks... https://laravel.com/docs/5.4/scheduling#schedule-frequency-options

**Comment by cleggypdc** [comment]
We use this for parsing cron syntax in a couple of pimcore plugins
https://github.com/mtdowling/cron-expression

**Comment by kanevbg** [comment]
Any opinion on this feature?

**Comment by ckogler-elements** [comment]
Hi,

we have a plugin which can do this: https://github.com/elements-at/ProcessManager/

You have to set up one cronjob - e.g.:
*/5 * * * * php /home/my-project/www/bin/console process-manager:maintenance

Then you can define each job/pimcore command in the ProcessManger. This plugin uses https://github.com/mtdowling/cron-expression to excute the "cronjobs".

**Comment by brusch** [comment]
Since this topic is already well covered by 2 plugins, I'm closing this for now. 
https://github.com/elements-at/ProcessManager/
