### ISSUE TITLE
[Bug]: Layout Element "Text" fails to load in object class configuration (settingsconfiguration)

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#11188]
### Expected behavior

Load configuration/input fields for layout element of type  "Text" in multiple opened classes.

### Actual behavior

Whenever more than one class that contains a layout element of type  "Text" is opened, the configuration gets not loaded and the JS Console shows the following error as seen in the screenshot below:

**Ext.ComponentManager.register(): Duplicate component id "settingsconfiguration**

![Bug_Text](https://user-images.githubusercontent.com/33122456/149499521-21cefb85-fa9a-4c46-aa81-f1823911ff63.png)

1. 

### Steps to reproduce

In Data Objects > Classes:

* Open a class and add a layout element of type  "Text", save it.
* Leave the class configuration open!
* Open another class and add/save a layout element of type  "Text".
--> Text configuration gets no longer loaded in none of the classes.

**Comment by dvesh3** [comment]
Fixed by #11258
