### ISSUE TITLE
[Bug]: Change order of areabrick settings

### ISSUE THREAD

**Issue by drilonmaloku** [pimcore/pimcore#11192]
### Expected behavior

I want to change the settings order based on the current settings based on other settings of the brick.

### Actual behavior

The order does not change

### Steps to reproduce

Try to change the items order if any select has some value.

**Comment by brusch** [comment]
Can you please make it a bit more clear what your intention is, including an example. 
Thanks. 

I'm closing the issue for the time being, we'll reopen it as soon as the topic was clarified. Thanks.
