### ISSUE TITLE
[Bug]:Webinterface Feature New Folder Chrome and Edge 

### ISSUE THREAD

**Issue by GunnarGillert** [pimcore/pimcore#11198]
### Expected behavior

In the web interface /admin right click on an existing folder. Now the menu appears. Selection of new folders. Enter the new folder name. The new folder appears.
With the browsers:
Firefox => works
Chrome => works
Edge => works

### Actual behavior

In the web interface /admin right click on an existing folder. Now the menu appears. Selection of new folders. Enter the new folder name. The new folder **not** appears when you use the Browser Chrome or Edge.
With Firefox works fine.

Pimcore Plattform 10.2.8
CentOS Linux release 8.4.2105
nginx 1.14.1
Chrome 97.0.4692.71 (64bit)
Edge 97.0.1072.62 (64bit)
Firefox 96.0.1 (64bit)

### Steps to reproduce

1. Open Chrome or Edge
2. go to /admin
3. select a folder
4. right click on folder
![2022-01-17 09_33_56](https://user-images.githubusercontent.com/62211300/149735753-bfd57cc1-4deb-4aba-8b21-7ca8ad2cd9c5.png)
5. menue appears
![2022-01-17 09_34_18](https://user-images.githubusercontent.com/62211300/149735806-8c98a4e5-6e4d-47d5-90d1-209ff4b2bb33.png)
6. Enter new folder name
![2022-01-17 09_34_33](https://user-images.githubusercontent.com/62211300/149735853-f6e96801-b7fd-437d-9c68-b3d10a06da7e.png)
![2022-01-17 09_35_03](https://user-images.githubusercontent.com/62211300/149735862-b4c5eaed-6d7f-4bc8-9384-714551253f3d.png)
7. Result
![2022-01-17 09_35_15](https://user-images.githubusercontent.com/62211300/149735909-cee407f6-b9e0-4e69-ac48-4fedac3f6fe7.png)

**Comment by brusch** [comment]
Unable to reproduce, just tested on https://demo.pimcore.fun/admin/ (`admin` / `demo` ) - works as expected.
