### ISSUE TITLE
[Bug]: Expected variable in catch block in initializeContainer()

### ISSUE THREAD

**Issue by antonio-masotti** [pimcore/pimcore#11193]
### Expected behavior

in `pimcore/lib/Kernel.php` at line 260 the catch block is missing the variable for the exception and this throws an error:
The exception should be handled, logged or ignored.

I think it could just be enough to give the exception a variable name like this:

~~~php
 try {
                $container = $this->getContainer();
            } catch (\LogicException $e) {
                // Container is cleared. Allow tests to finish.
            }
~~~

I'll try to submit a PR if this can help.

### Actual behavior

Current code: 

~~~php
 try {
                $container = $this->getContainer();
            } catch (\LogicException) {
                // Container is cleared. Allow tests to finish.
            }
~~~

once in the catch block, I get this error:

`syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE)`

![image](https://user-images.githubusercontent.com/91308510/149531515-40dd2be9-3708-4aa1-aec9-871a0ccf8468.png)

### Steps to reproduce

It happens when the a LogicException occurs while initializing the container.

**Comment by jdreesen** [comment]
There's nothing wrong with it, it's [supported in PHP 8](https://wiki.php.net/rfc/non-capturing_catches). Are you sure you're using the right PHP version?

**Comment by antonio-masotti** [comment]
Interesting... I didn't know (thanks for the docs) but yes  I'm sure:

![image](https://user-images.githubusercontent.com/91308510/149560564-62a32633-f2eb-4618-94a8-e1de7287e33c.png)

Still I get that error.

**Comment by antonio-masotti** [comment]
I've closed the PR. 

I still had composer associated with PHP 7.4 instead of 8.0. 
jdreesen was of course right.
