### ISSUE TITLE
Targeting code for personas relies on an enter in the HTML

### ISSUE THREAD

**Issue by lmanzurv** [pimcore/pimcore#1119]
When creating personas in the marketing section, the HTML head breaks if the whole template was wrapped around a spaceless tag (with Twig).

As seen in https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Controller/Plugin/Targeting.php#L213 it relies in an existing break after the <head> opening tag, which is not present if the head was included inside the spaceless tag.

See following images for examples.

**With the spaceless around the head**
![screen shot 2016-12-13 at 11 25 15 am](https://cloud.githubusercontent.com/assets/3003634/21134528/fd346070-c126-11e6-929f-9a93b1603d91.png)
![screen shot 2016-12-13 at 11 25 33 am](https://cloud.githubusercontent.com/assets/3003634/21134529/fe908674-c126-11e6-8e63-a416bc02eae7.png)

**With the spaceless around the body**
![screen shot 2016-12-13 at 11 25 49 am](https://cloud.githubusercontent.com/assets/3003634/21134535/09b65baa-c127-11e6-8177-11081be2e1f5.png)
![screen shot 2016-12-13 at 11 26 06 am](https://cloud.githubusercontent.com/assets/3003634/21134537/0b09e094-c127-11e6-91a5-431293290e16.png)

**Comment by fashxp** [comment]
shoud be fixed now since whole targeting was redesigned.
