### ISSUE TITLE
[Bug]: Document Types list breaks when showing creation or modification date

### ISSUE THREAD

**Issue by LosHawlos** [pimcore/pimcore#11224]
### Expected behavior

In the Document Types List all available columns can be shown properly

### Actual behavior

As soon as either the creation date or the modification date columns are selected to be shown, the new date columns are empty, and additionally the buttons in the delete and translate columns disappear.

There is also a JavaScript error in the console:
ext-all.js?_dc=a23ccb2bfaf92b1723e16ddd94e6cd296c50387f:1878 [W] XTemplate evaluation exception: Cannot read properties of undefined (reading 'format')

### Steps to reproduce

Reproduced on https://demo.pimcore.com/

Click on Settings > Document Types

![document_types_before](https://user-images.githubusercontent.com/7881418/150134214-2612c669-2dbd-48c9-9de6-aad7e678432d.PNG)

Click the arrow down button on any of the visible columns
Check either the Creation Date or the Modification Date (or both)

=> See that the newly enabled columns are empty
=> Additionally the delete and translate buttons are gone.

![document_types_after](https://user-images.githubusercontent.com/7881418/150134244-e06b4f4c-7418-4cf0-a470-fda145c2deae.PNG)

**Comment by fashxp** [comment]
fixed via #11226
