### ISSUE TITLE
[Bug]: The autoloader expected class "Symfony\Component\Messenger\Transport\AmqpExt\AmqpReceivedStamp"

### ISSUE THREAD

**Issue by alexanderkroneis** [pimcore/pimcore#11237]
### Expected behavior

Send a mail.

### Actual behavior

Pimcore crashes and shows a RunTimeException with HTTP 500 and displays following error message:

The autoloader expected class "Symfony\Component\Messenger\Transport\AmqpExt\AmqpReceivedStamp" to be defined in file "/var/www/vendor/composer/../symfony/symfony/src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpReceivedStamp.php". The file was found but the class was not in it, the class name or namespace probably has a typo.

### Steps to reproduce

1. Install Pimcore 10.0.9
2. Use Pimcore Mailer to send mail

**Comment by alexanderkroneis** [comment]
I investigated on that and it seems like Pimcore is using a deprecated class of a Symfony package.

```
<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\Component\Messenger\Transport\AmqpExt;

use Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpReceivedStamp as BridgeAmqpReceivedStamp;

trigger_deprecation('symfony/messenger', '5.1', 'The "%s" class is deprecated,use "%s" instead. The AmqpExt transport has been moved to package "symfony/amqp-messenger" and will not be included by default in 6.0. Run "composer require symfony/amqp-messenger".', AmqpReceivedStamp::class, BridgeAmqpReceivedStamp::class);

class_exists(BridgeAmqpReceivedStamp::class);

if (false) {
    /**
     * @deprecated since Symfony 5.1, to be removed in 6.0. Use symfony/amqp-messenger instead.
     */
    class AmqpReceivedStamp
    {
    }
}
```

**Comment by alexanderkroneis** [comment]
I just checked with another project, we are using the same setup there and mailing is working. It seems to be a misconfiguration, I'll let you know as soon as I find something.

**Comment by fashxp** [comment]
I'll close this for now, please feel free to share your findings - and create a ticket (or PR ;-) ) with more details if there is something to fix in Pimcore.
