### ISSUE TITLE
[Ecommerce] [Index] Unpublished Shop Categories are getting indexed

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#11234]
### Improvement description

Currently unpublished Shop Categories are getting indexed by default.
This is because of this line here: https://github.com/pimcore/pimcore/blob/10.x/bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultMysql.php#L100

You can of course override this in multiple ways and set/change the unpublished flag any way you want it but in my opinion the current way should not be the default implementation. 

WDYT?

**Comment by fashxp** [comment]
Hmm, but then we would need to update all products if the published state of one category changes (every time), otherwise the index is not consistent and products might be not listed in a category (which just got published).
Thus, I would leave it as it is.
