### ISSUE TITLE
[Bug]: data object preview generator with url slugs with sites

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#11242]
### Expected behavior

When implementing a [PreviewGenerator](https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Class_Settings/Preview_Generator.html) for an object that contains `UrlSlug`s - while using `Site`s - the preview is displayed.

### Actual behavior

When implementing a [PreviewGenerator](https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Class_Settings/Preview_Generator.html) for an object that contains `UrlSlug`s, the preview fails to match the url to the slug, due to the `Site` not being resolved.

Specifically, this is because of the `pimcore_object_preview` parameter as the `RequestHelper` will then return `true` for the `isFrontendRequestByAdmin` method call in the `RoutingListener`:

https://github.com/pimcore/pimcore/blob/1be5e36fb7300ff31842c1fce8581ff71109fd61/bundles/CoreBundle/EventListener/Frontend/RoutingListener.php#L137-L156

https://github.com/pimcore/pimcore/blob/1be5e36fb7300ff31842c1fce8581ff71109fd61/lib/Http/RequestHelper.php#L189-L212

Ultimately, this means the `Site` is not being resolved, which leads to a mismatch for the slug since the `Site` is `null`, thus `0` is passed as `$siteId`, but the `object_url_slugs` table has an id set:
https://github.com/pimcore/pimcore/blob/1be5e36fb7300ff31842c1fce8581ff71109fd61/lib/Routing/Dynamic/DataObjectRouteHandler.php#L94-L106

### Steps to reproduce

1. Create an object class definition containing an `UrlSlug` type
2. Create a `Site`
3. Create an object and manually enter slug
4. Create a preview generator and simply return the same value that was entered in the prev. step
5. Open the preview tab of the object - it won't display the preview as seen in the frontend

> You can also inspect the iframe in the preview tab, open the url in a new tab and remove the parameters to see that the url is actually working.

**Comment by passioneight** [comment]
As a workaround, we return a url in this format instead: `/preview/{originalUrl}` (with the requirements set to `requirements={"originalUrl"=".*"}`).

The action that is called then redirects to the url in `$originalUrl`.

**Comment by passioneight** [comment]
Seems related: https://github.com/pimcore/pimcore/issues/7657

**Comment by brusch** [comment]
It might be necessary here to pass the site ID as a parameter, because actually we can't use the site's hostname, because of sessions ...

**Comment by passioneight** [comment]
@brusch what exactly do you mean?

**Comment by brusch** [comment]
The thing is that sites are identified using the host name, but for previews you're on the main domain (or whatever hostname you use for the admin). So if you generate a slug the router can't determine which site is used, because actually the hostname doesn'T match with the site and the path/slug is not enought. You know what I mean?

**Comment by passioneight** [comment]
<s>Ah yes, that makes sense.

I think a select would be a great solution, as the user can decide which domain they want to look at. As default value, the current domain's site should be selected (with a fallback to the first site that's available).

However, one would also have to be able to restrict the options in the select, as not every user might have access to every site.

Additionally, the select should be `readonly` if there's only 1 option.

I'd see this feature as part of Pimcore, since every project with sites would need that, wdyt?</s>

---
I just realised that you were talking about the URL directly, while I was talking about the preview tab.

So, basically, you meant that we should add something like `pimcore_object_preview_site=<id>` to the line below, right?
 https://github.com/pimcore/pimcore/blob/89ecd1b81d4e955164027ca3a9129fa4b0d82679/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L2214

This would allow us to set the site's ID based on a select in the preview tab by appending it to the resulting URL. The parameter can then be used to resolve the site (if that's even necessary) and match the slug.

Not sure how to handle this for the "eye"-button in the header of the object - not even sure if anyone is even using this button: 
<img width="49" alt="image" src="https://user-images.githubusercontent.com/57256630/163192710-c9b4560c-c3ed-46d3-b07e-2cca947127c4.png">

I guess, a select for each main domain should work - similar to the info-button: 
<img width="235" alt="image" src="https://user-images.githubusercontent.com/57256630/163193508-8104d05d-1a0c-458e-baeb-eb37b97d461b.png">

**Comment by brusch** [comment]
@passioneight exactly 🤗 
But i think we should provide a more generic way of how to add the site info to a preview link.
I'm thinking of a trait ... something like that: 

```php
namespace Pimcore\Model\DataObject\ClassDefinition;

trait PreviewGeneratorSiteAwareTrait
{
    public function addSiteToParameters(int $siteId, array &$params): void
    {
        $params[PreviewGeneratorInterface::SITE_ID_PARAMETER_NAME] = $siteId;
    }
}
```

That can then be used in the custom preview generator: 
```php
    public function generatePreviewUrl(\Pimcore\Model\DataObject\Concrete $object, array $params): string {
        $additionalParams = [];

        $this->addSiteToParameters(123, $additionalParams);

        return $this->productLinkGenerator->generate($object, $additionalParams);
    }
```


WDYT?

**Comment by passioneight** [comment]
@brusch looks good to me. Although, I wonder if we should add a generic `PreviewGenerator` instead, while we are at it:

The `PreviewGenerator` can be used by default as soon as a link generator is provided. It will automatically add a `Site` dropdown, as well as a `locale` dropdown if - and only if - more than one `Site`/locale is available, respectively.

Whenever there's a need for customization, the `PreviewGenerator` can either be extended/decorated or a completely customized implementation of the `PreviewGeneratorInterface` can be used (as it is now).

WDYT?

**Comment by brusch** [comment]
@passioneight sounds good to me! Looking forward to the PR 😊

**Comment by passioneight** [comment]
@brusch great, I'll try to find some time soon.

**Comment by passioneight** [comment]
@brusch assuming that the site-id was added to the URL, where's the best place to resolve the site? I was hoping to find a way to just add the `SiteResolver::ATTRIBUTE_SITE` to the request. But since we are redirecting, we'll have to add the site-id as part of the `query`, which means that the `SiteResolver` will not resolve the site, as it is only looking in the request's `attributes` (and rightfully so).

**Comment by passioneight** [comment]
🏓

**Comment by passioneight** [comment]
🏓 ...

**Comment by brusch** [comment]
@passioneight sorry for the late answer 😳
The best place for that would be probably here: 

https://github.com/pimcore/pimcore/blob/c7f023cf2e349bba8794795f6365447b836c887a/bundles/CoreBundle/src/EventListener/Frontend/RoutingListener.php#L153

There we could add an `elseif` clause that checks if you're logged in and if the site-id param is set (should only work for logged in users of course).

**Comment by passioneight** [comment]
@brusch alright, thanks, I'll have a look soon :-)

**Comment by passioneight** [comment]
Seems like I won't find any time soon. Anyone else has some time to spare?
