### ISSUE TITLE
Multiple wysiwyg editables with customConfig bug

### ISSUE THREAD

**Issue by chix** [pimcore/pimcore#1124]
# Bug Report
It is not possible to use multiple wysiwyg document editables with different customConfig files on the same document.
  
### Expected behavior 
Each instance of ckeditor should be configured according to passed configuration in customConfig.
  
### Actual behavior  
For the scenario described below, the result is OK for w1 and w2, but not for w3 and w4.
  
### Steps to reproduce  
In the latest build run this code in your view
```php
<?php
    echo $this->wysiwyg('w1', ['customConfig' => '/cke_max_config.js']);
    echo $this->wysiwyg('w2', ['customConfig' => '/cke_min_config.js']);
    echo $this->wysiwyg('w3', ['customConfig' => '/cke_max_config.js']);
    echo $this->wysiwyg('w4', ['customConfig' => '/cke_max_config.js']);
?>
```
And use this configs for ckeditor https://gist.github.com/chix/9388101f887d39dbac2c433baf0ea27a (copy them into your web root). You should see, that w3 and w4 are configured with cke_min_config.js instead of cke_max_config.js.

Martin

**Comment by chix** [comment]
So it seems to be some caching issue, because if you append a random query string parameter to each customConfig file URL (e.g. `'/cke_max_config.js?v=1'`, `'/cke_max_config.js?v=2'`, ...) it will work.

**Comment by brusch** [comment]
But isn't this an issue of CKEditor? `customConfig` is passed directly to the CKEditor configuration, there's nothing in between from Pimcore.

**Comment by chix** [comment]
Yes, you are right. Even a clean html-only example with latest CKEditor behaves the same. I guess there is nothing to do here for Pimcore, so I'm closing this issue. I will have a look at CKEditor's bug tracker and maybe open an issue there. Thanks anyway.

**Comment by julmot** [comment]
I'm still having the same issue here, unable to provide differently configured CKEditor profiles for each WYSIWYG editable individually. Did you find a solution @chix, or do you have any tips to solve the issue @brusch?

**Comment by julmot** [comment]
I'm also having the exact same issue. The config gets correctly applied if there's only one configuration per page, but mixing configurations for different editables on the same page causes CKEditor to not correctly apply the configurations, thus I'm seeing a wrong toolbar.

Do you have any tips to resolve this issue @chix @brusch? Do you have a reference to the bug you filled @chix?
