### ISSUE TITLE
[Bug]: Set test database

### ISSUE THREAD

**Issue by LeonNoBears** [pimcore/pimcore#11247]
### Expected behavior

the given test database is used

### Actual behavior

the develop database is used

### Steps to reproduce

`COMPOSER_MEMORY_LIMIT=-1 composer create-project pimcore/skeleton ./projectname`
Open composer.json and add
```
"config": {
    "preferred-install": {
      "pimcore/pimcore": "source",
      "*": "dist"
    }
}
```
remove `vendor/pimcore` folder
`composer update pimcore/pimcore`
( _see_ https://github.com/pimcore/pimcore/issues/10226 )
`composer require codeception/codeception --dev`
`./vendor/bin/pimcore-install`
follow pimcore steps: https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Testing/Application_Testing.html#page_Codeception
create `./env.test` and set vars:

```
###> symfony/framework-bundle ###
APP_ENV=test

#TRUSTED_PROXIES=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
#TRUSTED_HOSTS='^(localhost|example\.com)$'
###< symfony/framework-bundle ###

PIMCORE_TEST=true
DB_HOST=mysql
DB_USER=root
DB_PASS=root
DB_NAME=clean_demo_test
DB_PORT=3306
DB_DRIVER=pdo_mysql
DB_VERSION=8.0
PIMCORE_TEST_DB_DSN=mysql://root:root@clean-demo.test/clean_demo_test
DATABASE_URL=mysql://root:root@clean-demo.test/clean_demo_test
DB_NAME_TEST=clean_demo_test
```

open file `./tests/codeception.dist.yml` edit params 
```
params:
    - ../.env.test
```

open file: `./config/packages/test/config.yaml` either hardcode params or set via env
`dbal: { connections: { default: { host: localhost, port: 3306, user: root, password: root, dbname: clean_demo_test, mapping_types: { enum: string, bit: boolean }, server_version: 5.5.5-10.6.4-MariaDB } } }`

create file: `./config/config_test.yaml`
```
imports:
    - { resource: services.yaml }
    - { resource: 'test/' }

pimcore:
framework:

```

create `./config/test/database.yaml` 
insert:
`dbal: { connections: { default: { host: localhost, port: 3306, user: root, password: root, dbname: clean_demo_test, mapping_types: { enum: string, bit: boolean }, server_version: 5.5.5-10.6.4-MariaDB } } }`

run command: `PIMCORE_TEST_DB_DSN="mysql://root:root@localhost/clean_demo_test" vendor/bin/codecept run -c tests/codeception.dist.yml`

develop db is used... 
a issue was already created but not this extended and it was closed https://github.com/pimcore/pimcore/issues/10232#issuecomment-1018486844

**Comment by dvesh3** [comment]
When application tests are run without prefix `APP_ENV=test`, then `Bootstrap::prepareEnvVariables` loads the environment vars using default path `root/.env`, ignoring the the test env file defined in `codeception.dist.yml`. We can utilize the new config from https://github.com/pimcore/pimcore/pull/12099 to skip loading `.env` file in case of tests, so that the one in `codeception.dist.yml` is only used to load env vars.

**Comment by LeonNoBears** [comment]
As @dvesh3 said `APP_ENV=test` is required for Pimcore >= 10.3.* so for me it is:
`APP_ENV=test php vendor/bin/codecept run integration -c tests/codeception.dist.yml`

**Comment by dvesh3** [comment]
@LeonNoBears let's keep it open, as we hav to fix the issue about ignoring the the test env file defined in `codeception.dist.yml` (basically waiting for #12099 to introduce `SKIP_DOTENV_FILE` var then we can skip loading the environment vars from bootstrap and load the one from  `codeception.dist.yml`).
