### ISSUE TITLE
Rate Limiting Requests and the CMS Backend

### ISSUE THREAD

**Issue by bbak** [pimcore/pimcore#1125]
### Actual behavior 
When the Image Preview Layer opens after hovering over a folder in the Assets Section, Pimcore issues a request to the server for each Image; the GET Request looks like this:
`GET /admin/asset/get-image-thumbnail/id/346/treepreview/true HTTP/1.0`

This easily leads to hundreds of GET Request to the PHP Engine. Sure, the request is easily answered without much load on the Server-Side. Nevertheless it makes Request Rate-Limiting virtually impossible since this would degrade the User Experience in the Backend.
But Rate-Limiting requests to the PHP Engine is quite important nowadays to mitigate the effects of DDOS attacks that try to overload the server through PHP calls. 

Note: Limiting the number of PHP-Processes doesn't help in this case.

### Expeced behavior  
Query the Thumbnail State of the whole Asset tree using one (or at least much less) GET-Request(s) to the Backend.

**Alternative**: Document ALL URIs leading to GET-Requests involving the PHP-Engine of the Backend, so that Rate-Limiting can be set up to not apply to these URIs. Then it would be possible to (at least in nginx) to apply the limit only to public URIs. 
I assume this would be just a hand full of RegEx'.

Once I know these URIs, I can provide a nginx config. 

### Steps to reproduce  
Upload "some dozen" Images, hover over the asset folder in the Backend and Monitor the number of Request send to the Server.

**Comment by Pegasuz** [comment]
We also have (had) problems with this. Especially when using fail2ban on the server. In some cases the user is blocked from the server due to the huge amount of requests. 
There is an option in the system settings to Disable Tree Preview, but sometimes we need the previews.

**Comment by bbak** [comment]
Made some progress excluding the admin Interface from Rate-Limiting: 
With Nginx it's possible to take the Pimcore Admin Cookie into Account when Rate-Limiting. It should look like this:
**In the http {} Block:**
```
# If the pimcore_admin_sid cookie is set, don't rate-limit.
map $http_cookie $doratelimit {
	default                  $binary_remote_addr;
	"~*pimcore_admin_sid"    "";
}
limit_req_zone $doratelimit zone=reqip:10m rate=10r/s
```
**Then, in the location for the PHP Engine add e..g. :**
`limit_req zone=reqip burst=10 nodelay;`

I know it's quite simple, since it only checks the existence of a cookie with the name "pimcore_admin_sid"; which is easy to fake. 
Using Lua it should be possible to validate the Cookie-Value against the PHP Session Store - e.g. a Redis Database or something like that.

**Comment by brusch** [comment]
Thanks for sharing you findings!
