### ISSUE TITLE
[Bug]: Grid view multi-select render issue

### ISSUE THREAD

**Issue by Navino16** [pimcore/pimcore#11259]
### Expected behavior

When using grid view and editing a multi-select value configured with an Option Provider Class and an Option Provider Data, we should see all availlable values for this field.

![image](https://user-images.githubusercontent.com/22234867/150778859-9c11aa90-23fb-475a-9efa-05808b572cf7.png)

### Actual behavior

When using grid view and editing a multi-select value configured with an Option Provider Class and an Option Provider Data, we don't see all availlable values for this field.

![image](https://user-images.githubusercontent.com/22234867/150778813-a28167c0-4f03-4712-bb2f-682ec2dddded.png)

### Steps to reproduce

1 - Create a multi-select field
2 - Add an Option Provider Class and an Option Provider Data to this field
3 - Create a grid view with this multi-select field and save
4 - Try to edit this field in grid view

![image](https://user-images.githubusercontent.com/22234867/150778967-6ab0c00b-3309-41af-82ac-da835037da3d.png)

**Comment by robertSt7** [comment]
@Navino16 Could you please provide the Option Provider Class and Option Provider Data? Thank you

**Comment by robertSt7** [comment]
We are closing the ticket due to inactivity. But you can always reply and we will take a look at it again.
