### ISSUE TITLE
Notes & Events panel is not expanded to 100% width in admin panel

### ISSUE THREAD

**Issue by kovinet** [pimcore/pimcore#1127]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [x] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [x] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [x] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [x] There's no existing ticket for the same issue

### Expected behavior 
Notes & Events Panel should be expanded to cover all remaining area but there is unnecessary white space on the right.
   
### Actual behavior  
Grid panel has 349px white space at the right. In smaller screens this is a problem since there is not enough space left to clearly see the grid.
  
### Steps to reproduce  
Just open Notes & Events tab (for Documents, Objects or  Assets)

**Comment by weisswurstkanone** [comment]
![details](https://cloud.githubusercontent.com/assets/6142086/21844691/e4ee5e78-d7ef-11e6-802a-16ac6bd241f0.png)

This space is reserved for the detailed view. However, it is only rendered when you click on an item for the first time.
