### ISSUE TITLE
[Feature]: Possibility to put a directory or page on error code 410

### ISSUE THREAD

**Issue by martinmoravec** [pimcore/pimcore#11282]
### Feature description

Hi peps,

I do need the possibility to send for 
- certain pages
- certain paths of my page via regex'es 
the status code 410 (for SEO issues). 

Is there any SEO out there who already has a workaround or a developer who would like to implement the feature. I guess it can be made via various ways, i.e. with an asset or within the siteconfig 

Thanks for your help!

**Comment by alyna** [comment]
Hi @fashxp ,

Would it be a good solution to extend the functionality of the Redirects table and also add the 410 status in the Status column?

Thanks

**Comment by dvesh3** [comment]
@alyna How about implementing something which allows to override and set new status codes. At the moment, these are hardcoded in the Redirect Class https://github.com/pimcore/pimcore/blob/10.x/models/Redirect.php#L134 so we can move it Symfony config and then you can add/modify the status codes.

**Comment by dvesh3** [comment]
Fixed by #11916
