### ISSUE TITLE
[Bug]: Constant refreshing/regenerating of preview of uploaded video asset

### ISSUE THREAD

**Issue by markvomark** [pimcore/pimcore#11287]
### Expected behavior

A preview of an uploaded video asset should be generated and shown.

### Actual behavior

A preview of an uploaded video asset is being generated and after approx. 5  seconds the asset is refreshed and the generation starts again.

### Steps to reproduce

Login to pimcore demo https://demo.pimcore.fun/admin/ (admin / demo), upload a test mp4 file (https://test-videos.co.uk/bigbuckbunny/mp4-h264) and open the asset afterwards.
You should be presented with this view:
![image](https://user-images.githubusercontent.com/50262740/151365143-77ea5319-d629-49cd-b370-c669b167efc2.png)

which is constantly refreshing:
![image](https://user-images.githubusercontent.com/50262740/151365204-5f2563ad-cccc-4086-a4d8-61e21504eba1.png)

Tested in Chrome 97.0.4692.99 and Firefox 96

**Comment by fashxp** [comment]
should only happen until the preview of the image is generated. please make sure, the symfony messenging queue is processed (which takes care of preview generation). 
at demo.pimcore.fun the queue is currently not activated thus the video previews are not generated. ad demo.pimcore.com it should work fine.

**Comment by markvomark** [comment]
Thanks for clarifying, Christian! In deed everything's fine, once pimcore:maintenance takes over the job. 👍🏻

**Comment by rjankiew** [comment]
@fashxp I have a similar issue, but with running messenger queues consumption. A row with message gets added to and deleted from messenger_messages table when I trigger generating the preview, but it's endless "(...) currently in progress. Please wait…". Could you recommend any steps to debug this further? E.g. where to look to confirm if the preview is generated, and what class is responsible? Thanks in advance.
