### ISSUE TITLE
[Bug]: "Predefined Document Type"-Select not working correctly in Document Settings

### ISSUE THREAD

**Issue by clangegger** [pimcore/pimcore#11283]
### Expected behavior

When creating a blank Page it should be possible to change the Document Type according to the created predefined Document Types in the SEO & Settings Section of the Document.

![image](https://user-images.githubusercontent.com/96467523/151305084-43968891-04c2-460e-bbac-db121a7d6811.png)

![image](https://user-images.githubusercontent.com/96467523/151304698-a0009ca3-d0a8-494a-a112-b63b3bc5a4b3.png)

### Actual behavior

When selecting a Document Type in the SEO & Settings Section of the Document it should prefill the predefined Controller and Template, but nothing happens.

![image](https://user-images.githubusercontent.com/96467523/151304845-93847573-8645-4da5-aaac-de6809518cb3.png)
![image](https://user-images.githubusercontent.com/96467523/151305017-0087b590-9685-43f0-a411-59de028b5c04.png)

### Steps to reproduce

The behavior can be reproduced on a fresh Pimcore install and on https://demo.pimcore.com/ too.

1. Create a new Document Type in `Settings > Document Types`
2. Create a new blank Page in the Documents-Tree
3. In the `SEO & Settings` Section of the newly created Document, select a predefined Document Type

**Comment by blankse** [comment]
@clangegger I create a PR for this: https://github.com/pimcore/pimcore/pull/11302
