### ISSUE TITLE
[Bug]: Invalid input regex crashes admin view

### ISSUE THREAD

**Issue by laurenz-glueck** [pimcore/pimcore#11280]
### Expected behavior

If there is an invalid regex for a DataObject input the Ext JS UI should not crash.

### Actual behavior

If you have an invalid regex in one of your DataObject input fields, you can not open this Object in the admin UI anymore.

### Steps to reproduce

1. Add invalid regex to DataObject input field.
2. Save DataObject class definition
3. Try to open instance of this object

**Comment by laurenz-glueck** [comment]
With Pimcore 10.2.7 the `u` flag was added to the Input regex validation: https://github.com/pimcore/pimcore/pull/11056

This has made my previously working regex invalid. 

My suggestion would be to add some try / catch logic around this line: https://github.com/r-vanstraaten/pimcore/blob/6039855ec04c3d64f291d24d8cd0be3089de5105/bundles/AdminBundle/Resources/public/js/pimcore/object/tags/input.js#L99

Otherwise a small regex error is breaking the whole backend UI.

FYI: @r-vanstraaten (added `u` flag) and @dvesh3 (approved PR)

**Comment by brusch** [comment]
Can you please share an example that get's broken by #11056 ? Thanks in advance!

**Comment by laurenz-glueck** [comment]
Sure - I had a kind of complex email regex I used for an input field which was working before / without the `u` flag:

```
^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$
```

If you add this one to an input field regex and then try to open an instance of this object, you will see the Ext JS ui break...
