### ISSUE TITLE
[Bug]: Nested Area Toolbar missing

### ISSUE THREAD

**Issue by eliasfellner** [pimcore/pimcore#11285]
### Expected behavior

If I have a Block Editable in a Document which contains an Areablock
I expect to be able to add a new Block Item and immediately add an Area in the Areablock, without the Area Toolbar missing

### Actual behavior

When adding a new Block Item which contains an Areablock, and immediately adding an Area
The Area is rendered but not the Toolbar.
You have to reload the Document to see the Toolbar (which is not good when using EditableDialogBoxConfiguration)

### Steps to reproduce

In a Document have this structure:
Block -> Areablock

1. Add a new Block Item
2. Add an Area in the Areablock
3. Check if the Area Toolbar is there

Pimcore Version: 10.2.9

**Comment by passioneight** [comment]
I can confirm this. Additionally to the missing toolbar, if you don't need the toolbar while adding content, the content is lost on save.

Only after a reload you are able to save the content as expected.

**Comment by passioneight** [comment]
@dvesh3 any updates on this?

**Comment by dvesh3** [comment]
@passioneight sorry, not the priority for us at the moment. It would be great to receive a PR for the fix 😉

**Comment by blankse** [comment]
@eliasfellner @passioneight I had the same issue and I created a PR. Can you test it? #12012

**Comment by passioneight** [comment]
@blankse thanks, I can verify that the toolbar is now available and everything works as expected.

**Comment by dvesh3** [comment]
Fixed by #12012
