### ISSUE TITLE
[Bug]: Error when removing classification group which has key relationships

### ISSUE THREAD

**Issue by AlekMosingiewicz** [pimcore/pimcore#11284]
### Expected behavior

The group which has key relationships is removed.

### Actual behavior

Removing group which has key relationships gives the following error
![2022-01-24 155548](https://user-images.githubusercontent.com/3677352/151317974-b7b5a707-d430-41c4-9686-f1ca0177ed05.png)
:

### Steps to reproduce

Create several classification keys. Create a classification group. Add created keys to the created group. Attempt to remove the group.

**Comment by aashan10** [comment]
From the digging I did on this issue, following are the results:

- This issue does not occur when no group is selected before clicking the remove icon.
- When a group is clicked and the remove icon is clicked, there is a side effect in first load where all the relations of that group are refreshed on the backend. Meaning, post requests for each key-group relation are sent to the backend which refreshes the relation in the backend.
- If all the post requests are completed before we press `Yes`, no exception occurs.
- If we press `Yes` before any of the request are yet to complete, the delete request deletes the group and hence the subsequent post relation requests can't find the group with the id that was just deleted and hence trigger the mentioned exception.

**Comment by dvesh3** [comment]
Fixed by #12410

**Comment by fashxp** [comment]
@dvesh3 please double check due to the the rebase

**Comment by dvesh3** [comment]
Fixed by #12502
