### ISSUE TITLE
[Bug]: data object link type escapes text

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#11297]
### Expected behavior

When rendering a `Link` set in an object, the text is rendered as provided in the backend (or programmatically).

> To clarify: the `getText` method call within the `getHtml` method is meant.

### Actual behavior

When rendering a `Link` set in an object, the text is escaped, preventing HTML to be rendered.

https://github.com/pimcore/pimcore/blob/fdfe5d1ca3e67ca16c707bab04c1ca6aa10af80d/models/DataObject/Data/Link.php#L557

> This can be useful when rendering icon-links - e.g., for social media - while still supporting all fields in the backend without having to manually render everything.

### Steps to reproduce

1. Create any object with a `Link`.
2. Fill the `Link`'s *text* either manually or programmatically with HTML.
3. Render the `Link`.

**Comment by blankse** [comment]
How do you render the link? In twig you must use the raw filter. https://twig.symfony.com/doc/2.x/filters/raw.html

**Comment by passioneight** [comment]
`|raw` is in use, but it doesn't matter because of the `htmlspecialchars` in the `getHtml` method.

**Comment by blankse** [comment]
Ah, you mean HTML in the text value of the link.

**Comment by passioneight** [comment]
Yes, sorry if that wasn't clear. I'll update the description shortly.

### Edit
Description was updated.

**Comment by fashxp** [comment]
be careful about potential XSS

**Comment by passioneight** [comment]
@fashxp fair point. Any suggestion on how to solve this without having to render the markup manually?

**Comment by fashxp** [comment]
nope

**Comment by passioneight** [comment]
I see. Well, probably the fastest way to just manually render the link then.

Though, I'd like to throw in the idea of using templates instead having the HTML code for editables within the PHP files. I haven't thought about the details of the implementation yet, but maybe it can kickstart some brainstorming. Thoughts?

**Comment by passioneight** [comment]
Closing this issue as manually rendering works around this. Any improvement related brainstorming should be part of a discussion first, then the discussion can be converted into an issue.
