### ISSUE TITLE
Document->getFullPath() urlencodes the protocol on a multisite

### ISSUE THREAD

**Issue by LosHawlos** [pimcore/pimcore#1129]
We are building a multisite setup and are linking pages between the different sites.

Document->getFullPath() includes the sheme and domain when the document is located in a different site, which is a great feature.
But the full url is returned urlencoded and thus not usable. 
instead of "http:// ..." it returns "http%3A// ..."

Problem ist that Document->prepareFrontendPath() is used after the full url is build together.
for example in the case of the document beeing the root of an other site:
```
$link = $scheme . $site->getMainDomain() . "/";
$link = $this->prepareFrontendPath($link);
```
prepareFrontendPath() then uses urlencode_ignore_slash() which corrupts the url in that case.

**Comment by brusch** [comment]
Duplicate, already fixed by #1144
