### ISSUE TITLE
[Bug]: Thumbnail <img> fallback does not have srcset attribute

### ISSUE THREAD

**Issue by John5** [pimcore/pimcore#11316]
### Expected behavior

In Pimcore 6.x thumbnail images generate an img element with srcset attribute with multiple versions. Only if media queries are defined are picture/source used.

I would expect the img element to have a srcset attribute like it did before.
Also I expect to have control over which HTML elements are used.

Maybe adding an option like this for use cases when the picture/source  elements are undesirable:
image.thumbnail('myThumb').html({'tag': 'img'})

### Actual behavior

In Pimcore 10.x picture/source is now always used for all images. The img element is included as a fallback but it does not have the srcset attribute.

This causes a tool like wget to not download the high resolution image when downloading the page.

### Steps to reproduce

Add a thumbnail mage to a template and observe generated HTML source. Look for img element and see that srcset attribute is missing.

**Comment by brusch** [comment]
Since the `<img>` tag is just a fallback, I'd not include the `srcset` to keep it simple...

**Comment by John5** [comment]
Like I mentioned in the bug report there are clients like GNU Wget 1.21.2  that do support srcset but not the source/picture elements and it is causing real compatibility issues.

I understand if this has no priority for you but I think I can make a fix and submit a PR and I hope you will consider merging it.

**Comment by brusch** [comment]
@John5 thanks for your feedback - I'd be ok with a PR 😻

**Comment by Brainshaker95** [comment]
@brusch With this PR, the issue of #8818 pops up again. LQIP do not load the content of src attribute with srcset present.

**Comment by brusch** [comment]
@Brainshaker95 can you please create a new issue for that, or even better a PR fixing the issue? Thanks a lot in advance!

**Comment by Brainshaker95** [comment]
#12045

**Comment by brusch** [comment]
@Brainshaker95 Thanks a lot! 👍
