### ISSUE TITLE
[Bug][DataObjects]: Autosave throws Error if only publish permission (and not save) given

### ISSUE THREAD

**Issue by chrisjung-dev** [pimcore/pimcore#11314]
### Expected behavior

When an User have explicit publish rights (and no explicit save rights) to an object, one of these should be correct behaviour:

1. Disabling all Fields, making just Publish and Unpublish working, but no other edits
2. Not showing an error popup.

### Actual behavior

An Error popup shows.

![grafik](https://user-images.githubusercontent.com/209926/151796076-7efe81fd-93a1-42b5-b97f-9ed992ce48b0.png)

### Steps to reproduce

1. Create Folder, DataObject etc. as needed
2. Create Object in Folder. 
2. Create User
3. Give User list, view and publish rights on folder (via workspace)
4. Login with new User
5. Open Object in Folder from Step 1.
6. Change value of some field e.g. input field.

**Comment by brusch** [comment]
I'd expect that `publish` includes `save`, right?

**Comment by chrisjung-dev** [comment]
But https://github.com/pimcore/pimcore/blob/6dcd2a1ee3af8fd43c3fc0d844e316417b08d59b/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L1358 ff. just checks save right, not publish.

**Comment by brusch** [comment]
Yep, both needs to be checked here.

**Comment by chrisjung-dev** [comment]
@brusch so this bug can be closed, since https://github.com/pimcore/pimcore/commit/877c7303b82348550eecd2f97a48eca2e43d8e5c is beeing shipped?

**Comment by brusch** [comment]
@campino2k ah, yes, thanks 😊
