### ISSUE TITLE
Pimcore calendar issue 

### ISSUE THREAD

**Issue by firojkhan** [pimcore/pimcore#1131]
### Expected behavior 
  When I select year 2051 from PIMCORE calendar, It should display 2051.

### Actual behavior  
After 2050 it is treating the year as from 20th century not as 21st century.  
### Steps to reproduce  
1. Select year 2051 and more from calendar.
2.  It will display xx/xx/51.
3. again click the calendar icon.
4. actually selected year was 1951 instead of 2051

**Comment by markus-moser** [comment]
I can confirm this issue. It happens in the English version. In the German version it works as there the date format displays the year with 4 digits.

**Comment by weisswurstkanone** [comment]
see https://github.com/pimcore/pimcore/issues/1329
