### ISSUE TITLE
[Bug]: Video Editable not rendering correctly

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#11321]
### Expected behavior

The `EditableDialogBoxConfiguration` renders the `Video` editable, including any necessary buttons, like so: 

![image](https://user-images.githubusercontent.com/57256630/151940066-85ab243d-cbc4-4dfc-acbe-380fbe9999ce.png)

### Actual behavior

Similar to https://github.com/pimcore/pimcore/issues/10417 (but not quite the same), the `EditableDialogBoxConfiguration` does not render the `Video` editable properly (edit button is missing):

![image](https://user-images.githubusercontent.com/57256630/151940492-6402f853-0017-4c57-a397-14a346c3d153.png)

### Steps to reproduce

1. Create a document
2. Create area containing a `Video` editable in the `EditableDialogBoxConfiguration`
    1. Also render the Video directly in the area itself, like so: `{{ pimcore_video('video').frontend|raw }}` 
3. Add area to document and open the `EditableDialogBoxConfiguration`

**Comment by dvesh3** [comment]
Sorry, not able to reproduce the issue:
![image](https://user-images.githubusercontent.com/5137917/154095956-6e8db497-2c57-4980-804f-6e85193afab5.png)

Please feel free to come back with reproducible scenario. thanks!

**Comment by passioneight** [comment]
@dvesh3 can you add the code you used to render the editables as well?

**Comment by dvesh3** [comment]
@passioneight sure, here it is:

```php 
//src/Document/Areabrick
class Video extends AbstractAreabrick implements EditableDialogBoxInterface
{
    public function getEditableDialogBoxConfiguration(Editable $area, ?Editable\Area\Info $info): EditableDialogBoxConfiguration
    {
        $config = new EditableDialogBoxConfiguration();
        $config->setWidth(600);
        //$config->setReloadOnClose(true);
        $config->setItems([
            [
                'type' => 'video',
                'label' => 'Some additional Text', // labels are optional
                'name' => 'myDialogVideo'
            ],
        ]);


        return $config;
    }
}
```

```twig
///templates/areas/video/view.html.twig
<section class="area-video">
{{ pimcore_video('video').frontend|raw }}
</section>
```

```twig
//page template
{{ pimcore_area('myArea', { 'type' : 'video' }) }}

**Comment by passioneight** [comment]
@dvesh3 thanks - it seems there was a misunderstanding. In your template, try using `{{ pimcore_video('myDialogVideo').frontend|raw }}` instead, so that the _same_ video is rendered, not a different one. This should help you reproduce the issue.

Current Pimcore version is v10.3.0.

**Comment by dvesh3** [comment]
Then it is duplicate of https://github.com/pimcore/pimcore/issues/10417. please see https://github.com/pimcore/pimcore/issues/10417#issuecomment-927876225

**Comment by passioneight** [comment]
@dvesh3 either one of the issue should be open then, no? Seems like you just dismissed this, because it's not a priority on your side. But that doesn't mean the issue should be closed since it still persists, wouldn't you agree?

**Comment by dvesh3** [comment]
@passioneight you are right..please see https://github.com/pimcore/pimcore/issues/10417

**Comment by passioneight** [comment]
@dvesh3 great, thanks!
