### ISSUE TITLE
[Bug]: Display error in admin backend at URLslug attribute with multiple sites

### ISSUE THREAD

**Issue by woellundwoell** [pimcore/pimcore#11327]
### Expected behavior

Display the URLslug in the right way when using multiple sites:
![Bildschirmfoto 2022-02-01 um 14 43 18](https://user-images.githubusercontent.com/16014748/151979578-8ed7cf5e-7e9c-42f5-85ae-28f6bf31e1e4.png)

### Actual behavior

If the slug of a page is in alphabetical order before the standard site the GUI display works not as expected:
![Bildschirmfoto 2022-02-01 um 14 47 59](https://user-images.githubusercontent.com/16014748/151980285-8896f828-bcc4-48d2-b3a7-5023fd243a85.png)

### Steps to reproduce

- Create at least 2 sites
- Set the slug of one site in alphabetical order before the default slug
- Reload edit tab in admin backend after saving

The reason of this behavior seems to be the order from the controller, more precisely the order from the function return of UrlSlug::getDataForEditmode(...):
![Bildschirmfoto 2022-02-01 um 14 53 36](https://user-images.githubusercontent.com/16014748/151981424-937b5e9a-cb36-498e-8fe5-90c5880e9c39.png)
See lines 118 + 122
https://github.com/pimcore/pimcore/blob/e464b003b51a92ebd7abc989883a1d3da34bebeb/models/DataObject/ClassDefinition/Data/UrlSlug.php#L100-L125

**Comment by brusch** [comment]
Fixed by #11336
