### ISSUE TITLE
Enable Show in Tree also in Combination with Custom Views

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#1132]

**Comment by markus-moser** [comment]
+1 for this feature

**Comment by markus-moser** [comment]
at least it should be possible that the show in tree function works for one tree if the default tree is disabled and replaced by a custom view in a perspective.

**Comment by weisswurstkanone** [comment]
build 102

**Comment by weisswurstkanone** [comment]
[config.zip](https://github.com/pimcore/pimcore/files/1263310/config.zip)

attached config used for testing

**Comment by camico** [comment]
I was looking for exactly this issue. Unfortunately it doesn't work for me in build 105, even with the attached test config (with the only change being that I set the rootfolder of the customview "Objekte (Intranet)" to a folder I have).

Always bails out with the error:
`Sorry, this is not possible in elements which are paged, try to restructure your data to avoid pages in the tree`

And in JS Console:
`TypeError: Cannot read property 'expand' of null`
in
```js
try {
  var lastExpandedNode = pimcore.treenodelocator.getLastExpandedNode(path, tree);
  lastExpandedNode.expand();
  pimcore.treenodelocator.getDirection(lastExpandedNode, element, elementType, null, callback);
} catch (e) {
  console.log(e);
  pimcore.treenodelocator.showError(lastExpandedNode, lastExpandedNode.data.elementType);
}
```
When I set rootfolder to "/" it works (but then of course my custom view is not really custom enough)...
Are there any prerequisites for this feature to work?

**Comment by fashxp** [comment]
doesn't work in advanced-demo either...

**Comment by weisswurstkanone** [comment]
build 106

**Comment by fashxp** [comment]
very nice 👍

**Comment by markus-moser** [comment]
Thank you very much - it work's perfectly in my case. I added it to Pimcore 4 too.
