### ISSUE TITLE
[Improvement]: Maintenance | Messenger

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#11320]
### Improvement description

Follow-Up: https://github.com/pimcore/pimcore/pull/10329
***

## Maintenance Command
I guess there are some conceptional issues here. There is a `async` option which is deprecated (why? We always need a sync option) but not stored as default. So in documentation, the default maintenance call needs to be defined as `bin/console pimcore:maintenance -a` 

But using this option is wrong per se, IMO. Instead, the message flow should determinate which command should be sync or async.  There are two options to go:

### I. Dynamic Transport Definition
If this PR gets merged, we're able to determinate the transport by its origin:
https://github.com/symfony/symfony/issues/38200

### II. Sync/Async Transports
In larger projects, I'm using two transports and two routes. Every Transport gets dispatched by a dedicated Interface:

```yaml
framework:
    messenger:
        transports:
            app_async: 'doctrine://default'
            app_sync: 'sync://'
        routing:
            App\Message\Routing\AsyncMessageInterface: app_async
            App\Message\Routing\SyncMessageInterface: app_sync
```

For the PIMCORE Maintenance task, there could be a `MaintenanceTaskSyncMessage` and a  `MaintenanceTaskAsyncMessage`. Dispatching the command directly would submit the sync message, dispatching it via cron would dispatch the async message. I think you will get the idea.

UPDATE: Currently, it is also hard to debug specific maintenance task because you always need to monitor two terminals (one with the running messenger and one to dispatch the task itself). With the dedicated transports described above, this would be easier too.

## Best Practice | Documentation
I think there are some missing links, e.g. gaps regarding documentation about the messenger component:
https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Installation.html#page_5-Maintenance-Cron-Job

### Deployment
Stopping the messenger immediately after the deployment is very important. Five minutes can be a very destructive timespan. Always execute this command after every release: `bin/console messenger:stop-workers`.  Just linking the symfony documentation is too easy and should be visible in documentation. 

### Maintenance Trigger
I dare to say that most PIMCORE installations or hosters are delivered or installed without supervisor.
So we should improve the documentation about this.

#### Without Supervisor
Since we cannot rely on supervisors process handling, we need to "fake" it:

```cronjob
*/5 * * * * /your/project/bin/console pimcore:maintenance -a
* * * * * /your/project/bin/console messenger:consume pimcore_core pimcore_maintenance --memory-limit=512M
```

Legend:
- Dispatches the maintenance tasks every 5 minute asynchronously 
- Dispatches the messenger every minute with a memory limit of `512M`

Now by adding the event listener below, the messenger will stop immediately after the worker is done but would start again a minute later. You may even could skip the messenger:stop-workers part! This would give as some "real-time" impression, like using supervisor.

```php
<?php

namespace App\EventListener;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Messenger\Event\WorkerRunningEvent;

class MessengerProcessEventListener implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            WorkerRunningEvent::class => 'onWorkerRunning',
        ];
    }

    public function onWorkerRunning(WorkerRunningEvent $event): void
    {
        if ($event->isWorkerIdle()) {
            $event->getWorker()->stop();
        }
    }
}
```

#### With Supervisor
We only need the maintenance cycle dispatcher as a cronjob

```cronjob
*/5 * * * * /your/project/bin/console pimcore:maintenance -a
```

```conf
[Unit]
Description=PIMCORE Core & Mainenance
After.mysql.service

[Service]
Type=simple
User=www-data
Restart=always
ExecStart=/your/project/bin/console messenger:consume pimcore_core pimcore_maintenance --time-limit=300
```

Please, not the `time-limit=300`. It is recommended to use it even if you're using Supervisor: Pimcore uses a lot of static `self::$cache` properties, which can be very very very messy if the process runs too long.

Thanks for all the fish!

**Comment by dpfaffenbauer** [comment]
# Maintenance Command

the async option is deprecated cause it will be removed with 11 and async will be the default then. 

I don't really understand the need for Sync and Async Messenges. Everything with messenger is basically async. The CronJob is needed to trigger time sensitive background tasks. Whereas others are triggered by actions taken directly in Pimcore (eg: deleting thumbnails on image updates).  It doesn't matter who triggers it, important is that they are executed.

# Best Practice | Documentation

Can be better, but:

```
*/5 * * * * /your/project/bin/console pimcore:maintenance
```

Sends the maintenance messages and STARTS the worker directly. Where as

```
*/5 * * * * /your/project/bin/console pimcore:maintenance -a
```

Only sends the messages and doesn't start anything. So without -a is correct as well. But: For Pimcore > 10 -a is deprecated and running the command then will only send the messages but doesn't start the worker.

**Comment by solverat** [comment]
> the async option is deprecated cause it will be removed with 11 and async will be the default then.
> 
> I don't really understand the need for Sync and Async Messenges. Everything with messenger is basically async. The CronJob is needed to trigger time sensitive background tasks. Whereas others are triggered by actions taken directly in Pimcore (eg: deleting thumbnails on image updates). It doesn't matter who triggers it, important is that they are executed.

That is not entirely true. There are two important arguments for `sync`:
1. If you're using a query bus for example, which even should return something immediately (CQRS pattern)
2. Running a maintenance task or command for debug purposes or/and to allow them to run differently. The fact that I otherwise have to restart the consumer with every change is argument enough.

> Only sends the messages and doesn't start anything. So without -a is correct as well. But: For Pimcore > 10 -a is deprecated and running the command then will only send the messages but doesn't start the worker.

The `pimcore:maintenance` command should never start any workers (separation of concerns). To sum things up, this command should execute the `maintenanceExecutor->executeMaintenance()` asynchronously by default and with the `--async` argument it should do the same but with instant feedback (synchronously).

**Comment by dpfaffenbauer** [comment]
> That is not entirely true. There are two important arguments for sync:

> If you're using a query bus for example, which even should return something immediately (CQRS pattern)
Running a maintenance task or command for debug purposes or/and to allow them to run differently. The fact that I otherwise have to restart the consumer with every change is argument enough.

Use a separate BUS for that and run YOUR custom commands in sync. What I meant is that Pimcore does not need to run its task sync.

```
framework:
    messenger:
        transports:
            sync: "sync://"
            async: "doctrine://default"
        routing:
            'App\Messenger\SyncMessageInterface':  sync
            'App\Messenger\AsyncMessageInterface':  async
```

Pimcore should not be responsible in providing you helpers to create Sync or Async bus messages. Symfony is quite flexible in doing that already.

> The pimcore:maintenance command should never start any workers (separation of concerns). To sum things up, this command should execute the maintenanceExecutor->executeMaintenance() asynchronously by default and with the --async argument it should do the same but with instant feedback (synchronously).

No, cause that would have been a BC Break. Messenger for Pimcore was introduced with 10.1. The async option is for BC reasons.

There is no need to run the maintenance jobs sync. They should give the worker tasks to execute and not run it directly. There is no point in that.

**Comment by solverat** [comment]
> Use a separate BUS for that and run YOUR custom commands in sync. What I meant is that Pimcore does not need to run its task sync.

Just calm down. You asked "_I don't really understand the need for Sync and Async Messages_" and I answered that. It is just an example, the second argument is pimcore related BTW. 

> Pimcore should not be responsible in providing you helpers to create Sync or Async bus messages. Symfony is quite flexible in doing that already.

> There is no need to run the maintenance jobs sync. 

No one is talking about running my custom commands - no worries, my own implementations are working just fine.  
But when it comes to debugging my own maintenance tasks (`pimcore.maintenance.task`) for example, then pimcore should do a proper job (which also increases core DX). Now I have to execute `bin/console pimcore:maintenance -j my_job -vv` which runs `messenger:consume` as a sub-command and that's not correct. For that, I suggested those two transports, which would simplify the command a lot:

```php
// simplified
$this->messageBus->dispatch(
    $input->getOption('sync') 
        ? new MaintenanceSyncTaskMessage($options) 
        : new MaintenanceTaskMessage($options)
);
```
As you can see (hopefully) it's not just about "no need" but also about proper integration.

> No, cause that would have been a BC Break. Messenger for Pimcore was introduced with 10.1. The async option is for BC reasons.

Sorry my mistake. I was thinking about the opposite way (as you can see on my typo `by default and with the --async argument`) to keep BC of course.

I just wanted to share some (mainly documentation based) improvements here, and not trigger anyone's bias.

**Comment by dpfaffenbauer** [comment]
I think you are more upset than me am about that :D 

> No one is talking about running my custom commands - no worries, my own implementations are working just fine.
But when it comes to debugging my own maintenance tasks (pimcore.maintenance.task) for example, then pimcore should do a proper job (which also increases core DX). Now I have to execute bin/console pimcore:maintenance -j my_job -vv which runs messenger:consume as a sub-command and that's not correct. For that, I suggested those two transports, which would simplify the command a lot

I honestly cannot agree with that. I think it is fine as it is. With Pimcore 11, the maintenance command will only trigger the messages and the worker starts somehow else. (for debugging: manually starting the worker). Absolutely fine.

**Comment by fashxp** [comment]
Pimcore 11 is out for a while. If there are still issues, please create a new issue and discuss improvements based on Pimcore 11. 
Thanks...
