### ISSUE TITLE
[Bug]: Misleading error message in checkPermission() function

### ISSUE THREAD

**Issue by schmidt-travixmedia** [pimcore/pimcore#11344]
### Expected behavior

Display/log a non misleading error message (like 'Admin user object could not be retrieved.')

### Actual behavior

Error message creation creates an error ;-)
As a consequence, a misleading error message is generated and so the real problem gets lost.

In my case, this was shown:
`The "Symfony\Contracts\Translation\TranslatorInterface" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.`

### Steps to reproduce

vendor/pimcore/pimcore/bundles/AdminBundle/Controller/AdminController.php:

```
protected function checkPermission($permission)
{
    if (!$this->getAdminUser() || !$this->getAdminUser()->isAllowed($permission)) {

        Logger::error(
            'User {user} attempted to access {permission}, but has no permission to do so',
            [
                'user' => $this->getAdminUser()->getName(),
                'permission' => $permission,
            ]
        );

        throw $this->createAccessDeniedHttpException();
    }
}
```

`$this->getAdminUser()->getName()`

fails inside the if-block, when the block was entered because the first part

`!$this->getAdminUser()`

of the if-condition matched (in my case it returned NULL due to configuration problems).

**Comment by kingjia90** [comment]
@schmidt-travixmedia could you please share more details on the configuration problems you mentioned? just wanted to reproduce the error before merging the neat solution from @matthiashamacher

**Comment by kingjia90** [comment]
update: just merged to have it in today's release
