### ISSUE TITLE
Proposal: Add random condition to persona to allow A/B Testing

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#1134]
# Feature Request 
## Feature description 
The persona feature does currently allow us to send different content to users based on conditions like referrer, browser and so on.
I think it'd be great to have a persona condition based on random so we could do A/B testing withing pimcore directly.

Let's say we have three pimcore personas with random as condition, pimcore could just randomly assign visitors to one of these three personas and we could server the content for this persona. We can measure conversions for each persona in this case and optimize content step by step.

At the moment this is only possible if we assign conditions which could lead to a restricted result (e.g. based on browser - but people using firefox might be more open-minded and prefer different content than people using default IE...).

What do you think? It'd allow content A/B Testing, design A/B Testing is still better done via external tools I think.

**Comment by fashxp** [comment]
Should now (with Pimcore 5) be possible by modifying the VisitorInfo. See https://pimcore.com/docs/5.x/Development_Documentation/Tools_and_Features/Targeting_and_Personalization/Visitor_Info.html

**Comment by Cruiser13** [comment]
Thanks @fashxp
