### ISSUE TITLE
[Improvement]: add method Relations to ClassificationStore class CollectionConfig

### ISSUE THREAD

**Issue by awroblewski** [pimcore/pimcore#11341]
### Improvement description

Hi,

The classificationStore class GroupConfig implements a method called "Relations" giving a list of all keys belonging to a group. However, the CollectionConfig class did not have such a method giving a  list of all groups belonging to a collection.
To stay consistent across the implementation of the classificationstore classes GroupConfig and CollectionConfig we should implement the Relations method for CollectionConfig as well.

**Comment by brusch** [comment]
Fixed by #11342
