### ISSUE TITLE
[Improvement]: Possible Duplication of lines / Called the same function twice after each other

### ISSUE THREAD

**Issue by mmodmmod** [pimcore/pimcore#11345]
### Improvement description

In the reverseObjectRelation.js the function this.specificPanel.removeAll() is called twice, once in line 56 as well as 58. 
Is this intentional or actually a mistake?

For clarification: we are talking about:
/vendor/pimcore/pimcore/bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/reverseObjectRelation.js
or
https://github.com/pimcore/pimcore/blob/10.x/bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/reverseObjectRelation.js

**Comment by dvesh3** [comment]
Fixed by #11443
