### ISSUE TITLE
[Feature]: Possibility to show and assign (even batch) tags from Assets/DataObjects grid

### ISSUE THREAD

**Issue by ramundomario** [pimcore/pimcore#11350]
### Feature description

It would be usefult show and assign (even batch) tags from the Assets/DataObjects grid.
Currently if you want to see associated tags to Assets/DataObjects in grid you have to open all the items and repeat for all elements involved.

**Comment by SamyMP** [comment]
Hi,

I would add that it could also be very useful to be able to filter on those tags on the DataObject grid, when listing all DataObjects from clicking on a folder on the tree for example. I don't know if this is directly related to this isssue or if it needs to its own issue for this feature.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
