### ISSUE TITLE
getFieldDefinition() from Class doesn't consider localized fields

### ISSUE THREAD

**Issue by ckogler-elements** [pimcore/pimcore#1135]
# Bug Report
Localized fields are ignored when getFieldDefinition() is called from the ClassDefinition Class.

-> add option to consider loclized fields

**Comment by fashxp** [comment]
is this really wanted? because technically fields in localized fields are not direct members of the class definition :)

**Comment by brusch** [comment]
Yep, I also think that this may causes more confusion then it would help. 
A quick solution would be: 
```php 
$class = Object\ClassDefinition::getById(123);
$lf = $class->getFieldDefinition("localizedfields");
if($lf) {
    $lf->getFieldDefinition("yourFieldInsideLF"); 
}
```

**Comment by rishadomar** [comment]
I have more than 1 localizedfields. There is no way to get all of them.
