### ISSUE TITLE
prepareOnRowContextmenu object folder context menu js event

### ISSUE THREAD

**Issue by kylepwarren** [pimcore/pimcore#1136]
# Feature Request 
## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [check ] There is no existing issue regarding the same topic

## Feature description 
  
prepareOnRowContextmenu object folder context menu js event, similar to the one in object tree

**Comment by weisswurstkanone** [comment]
already implemented via https://github.com/pimcore/pimcore/commit/b9abacc4701f503733aa209a7ccedd966fe606ee
