### ISSUE TITLE
[Bug]: Image Face detection fails, 'the process has been signalled with signal 6' 

### ISSUE THREAD

**Issue by msteyrer** [pimcore/pimcore#11377]
### Expected behavior

do not pass the filetype-not-supported.svg or other unsupported filetypes to the facedetect binary.

### Actual behavior

In the detectFaces method of Pimcore\Model\Asset\Image the filetype-not-supported.svg is passed to the facedetectBin. Whenever this happens, it results in an uncaught error and the image can not be saved. 

### Steps to reproduce

pimcore 6.9.6
It can not be reproduced with any jpg, but it happens quite often when importing images from external systems. As a result we had to deactivate the focal_point_detection for several customers importing larger amounts of images from a third party systems.

**Comment by brusch** [comment]
Fixed by #11395
