### ISSUE TITLE
[Bug]: Updating from Pimcore 10.2.7 to 10.3 through Composer results in Migration Exception

### ISSUE THREAD

**Issue by abcpremium** [pimcore/pimcore#11379]
### Expected behavior

Hello all,

I updated Pimcore from version 10.2.7 to 10.3 by following the guide at [https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/Updating_Pimcore/index.html](https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/Updating_Pimcore/index.html), executing `COMPOSER_MEMORY_LIMIT=-1 composer update`, however, the migration script that gets executed afterwards results in an exception. I never got this exception when performing updates before. Can anyone tell me what exactly is wrong? Or how I can fix this?

Thanks in advance!

### Actual behavior

```
[notice] Migrating up to Pimcore\Bundle\CoreBundle\Migrations\Version20220201132131
[error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20211103055110 failed during Execution. Error: "An exception occurred while executing 'ALTER TABLE object_relations_BS CHANGE COLUMN
                        `type` `type` VARCHAR(50)  NULL DEFAULT NULL ;':

SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead"

In AbstractMySQLDriver.php line 125:

  An exception occurred while executing 'ALTER TABLE object_relations_BS CHAN
  GE COLUMN
                          `type` `type` VARCHAR(50)  NULL DEFAULT NULL ;':

  SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIM
  ARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead


In Exception.php line 18:

  SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIM
  ARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead


In PDOConnection.php line 141:

  SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIM
  ARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead


doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--prefix [PREFIX]] [--] [<version>]

Script Pimcore\Composer::executeMigrationsUp handling the post-update-cmd event terminated with an exception


  [RuntimeException]
  An error occurred when executing the "/Applications/MAMP/bin/php/php8.0.8/bin/php --php-ini=/Applications/MAMP/bin/php/php8.0.8/conf/php.ini bin/console --ansi doctrine:migrations:migrate -n --prefix Pimcore\Bundle\CoreBundle" command:

  Exit code: 1

  [notice] Migrating up to Pimcore\Bundle\CoreBundle\Migrations\Version20220201132131


  [error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20211103055110 failed during Execution. Error: "An exception occurred while executing 'ALTER TABLE object_relations_BS CHANGE COLUMN
                          `type` `type` VARCHAR(50)  NULL DEFAULT NULL ;':

  SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead"

  In AbstractMySQLDriver.php line 125:

    An exception occurred while executing 'ALTER TABLE object_relations_BS CHAN
    GE COLUMN
                            `type` `type` VARCHAR(50)  NULL DEFAULT NULL ;':

    SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIM
    ARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead


  In Exception.php line 18:

    SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIM
    ARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead


  In PDOConnection.php line 141:

    SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIM
    ARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead


  doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--prefix [PREFIX]] [--] [<version>]

```

### Steps to reproduce

Execute `COMPOSER_MEMORY_LIMIT=-1 composer update` on Pimcore version 10.2.7.

**Comment by dvesh3** [comment]
Seems like regression of https://github.com/pimcore/pimcore/pull/10760. I'm not sure if `NULL` default value for type column is a valid case though https://github.com/pimcore/pimcore/pull/10760#discussion_r751294935

**Comment by brusch** [comment]
@dvesh3 yep, you're right, it's a regression of #10760 
I've requested to change the default value to `NULL` as `object` felt wrong to me. 
As a fix we could either use one of `asset` `document` or `object` again as the default, or we introduce another enum value, like `default` which is then used as the default value. wdyt?

**Comment by dvesh3** [comment]
@brusch what i'm not sure of that do we really need a default value? isn't it type should always be passed?
 
 e.g. https://github.com/pimcore/pimcore/blob/acb371a1bff695d56084c9f372d7eab41361f305/models/DataObject/ClassDefinition/Data/ManyToOneRelation.php#L230
 or https://github.com/pimcore/pimcore/blob/acb371a1bff695d56084c9f372d7eab41361f305/models/DataObject/ClassDefinition/Data/ManyToManyRelation.php#L252

**Comment by brusch** [comment]
Yes, the type should be always there. 
Just checked: 
https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html#:~:text=If%20a%20data%20type%20specification,with%20no%20explicit%20DEFAULT%20clause.

It seems that we should be fine by not defining a default value.

**Comment by abcpremium** [comment]
So, is there a hotfix for me to get it working again?

**Comment by dvesh3** [comment]
@abcpremium please check this PR https://github.com/pimcore/pimcore/pull/11383

**Comment by brusch** [comment]
Fixed by #11383

**Comment by brusch** [comment]
@abcpremium btw. which MySQL/MariaDB are you using?

**Comment by abcpremium** [comment]
> @abcpremium btw. which MySQL/MariaDB are you using?

It's MariaDB 10.3
