### ISSUE TITLE
[Improvement]: Poster image for videos should be available independent of selected type

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#11371]
### Improvement description

When using `Video` editables or types, only the `asset` type has the field _Poster Image_ available:

![image](https://user-images.githubusercontent.com/57256630/152495002-91126437-58a8-4816-9091-c42cf6bb3514.png)

![image](https://user-images.githubusercontent.com/57256630/152495051-2d77835c-75ec-45da-8ec2-1894bdcd5410.png)

Chances are that the client wants a specific poster image regardless of the chosen type. Thus, it would be nice if the poster image field is available for all video types.

> Of course, there are work arounds, such as adding an additional field for the poster image. But this will have a negative effect on usability/maintainability.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
