### ISSUE TITLE
[Feature]: Date Fields instead of Text Fields

### ISSUE THREAD

**Issue by alexanderkroneis** [pimcore/pimcore#11381]
### Feature description

Hi,

a customer of ours asked whether we can change the date format. We investigated on that and recognized that this is not possible within Pimcore backend and we also detected that the input fields for date fields are `type="text"` instead of `type="date time-local"`. Why is this? Please change it to HTML5 date field.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
