### ISSUE TITLE
[Bug]: Cant login to Pimcore in Test Environment

### ISSUE THREAD

**Issue by Humb3l** [pimcore/pimcore#11403]
### Expected behavior

I set up a Test Environment with a Test Database and I still can login to the Pimcore Admin interface

### Actual behavior

If I try to login to Pimcore I get a 403 Error "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)". I copied the dev database and I would expect that I still can login to Pimcore after using the copied dev Database as a test db (I also tried this with a fresh installed (from pimcore install script) database).

![image](https://user-images.githubusercontent.com/88077406/153000604-c22b718c-35c8-43d7-9e3b-7aa7f015f4d9.png)
 I recognized that some of the HTTP are different to the dev env (like the _remove_csp_header flag).

### Steps to reproduce

1. Create a new Project with the Pimcore skeleton
2. Install Pimcore
3. Copy the DB and create a Test DB from that dump (u can use the mysql root user)
4. Add the new DB as config in the config/packages/test/config.yaml
5. Change the APP_ENV from "dev" to "test"
6. Try to login

**Comment by brusch** [comment]
`test` environment is only for running local test, not to run the UI
