### ISSUE TITLE
[Bug]: Thumbnails using manually set 'specific area' are broken after clearing temporary files

### ISSUE THREAD

**Issue by LeaveAirykson** [pimcore/pimcore#11419]
### Expected behavior

When an pimcore_image is overwritten manually by selecting a 'specific area' to use for the thumbnail and the temporary files are cleared, the new thumbnail should be recreated when frontend is opened.

### Actual behavior

After a 'specific area' is set the new thumbnail shows in frontend. But as soon as the temporary files are cleared, these thumbnails break. This is replicable in the live demo as well as seen in the attached gif. The thing is, as long as I'm logged in the backend and view the frontend in the same browser session, it looks like its working. But when I open the frontend in a different browser (I used FF incognito for testing) the image is broken.

### Steps to reproduce

- Log in to demo site https://demo.pimcore.com
- Find an element where you want to change the thumbnails specific area
- Set specific area on thumbnail
- Save & publish
- Clear temporary files
- Open Frontend in different browser (or incognito window)

![recording_pimcore_thumbnail_issue](https://user-images.githubusercontent.com/6337515/153383990-44fc9e0c-f723-4b21-ad9d-638638c16aca.gif)

**Comment by tom2796** [comment]
Hi 
I had the same issue and could solve it by updating the thumbnails section in the .htaccess File with a newer version. 
E.g. https://github.com/pimcore/skeleton/blob/v10.1.13/public/.htaccess

**Comment by LeaveAirykson** [comment]
> Hi I had the same issue and could solve it by updating the thumbnails section in the .htaccess File with a newer version. E.g. https://github.com/pimcore/skeleton/blob/v10.1.13/public/.htaccess

Oh nice, I will try it out, thx!

**Comment by brusch** [comment]
@LeaveAirykson please let us know if this fixed your issue. Thanks!

**Comment by LeaveAirykson** [comment]
Sadly this did not fix the issue. It is still present and even in the pimcore demo site https://demo.pimcore.com/ which runs on v10.5.10

**Comment by fashxp** [comment]
this is already fixed now.
