### ISSUE TITLE
[Bug]: `BlockElement` inside an `Objectbrick` gets incorrectly serialized into cache

### ISSUE THREAD

**Issue by jdreesen** [pimcore/pimcore#11412]
### Expected behavior

When there's a `DataObject` with an `Objectbrick` that contains a field of type `block`, its serialized cache entry should not expand exponentially by the amount of `BlockElement`s it contains.

### Actual behavior

Each `BlockElement` has an `_owner` field that contains the `Objectbrick` instance it belongs to. This field in turn contains the `Objectbrick`s data instance (`Objectbrick\Data\AbstractData`), which itself contains the block again, so we have a circular dependency.

When a `BlockElement` gets serialized for caching, its [`marshalForCache()`](https://github.com/pimcore/pimcore/blob/4cd9301b1f40b9e67ac73c3e49fcaeaab9f33fb7/models/DataObject/Data/BlockElement.php#L220-L249) method gets called, which creates a `DeepCopy` of the
whole `BlockElement` with all instances of `ElementInterface` replaced by `ElementDescriptor` objects.

But as the `Objectbrick` instance inside the `_owner` field is no `ElementInterface`, it doesn't get replaced with an `ElementDescriptor` but just gets *copied* - the same happens for the `Objectbrick`s data instance.

Because it gets copied, it's another instance and thus gets duplicated in the serialized cache entry (instead of just referenced), which expands exponentially by the amount of `BlockElement`s, so if we have only 1 `BlockElement`, everything is fine, but if we have two, there are already 4 `BlockElement`s (two of each) in the serialized cache entry, if we have 3 entries, there are 9 `BlockElement`s in the serialized cache entry...

As you can see, it grows pretty fast, especially if every `BlockElement` has several fields, which results in the cache entry to be many MiB in size where it should only be a few KiB. 

---

In one of our projects we have a `DataObject` with an `Objectbrick` which contains several blocks that contain ~3 fields each and some of them have tenth to hundreds `BlockElement`s which results in the cache entries of the `DataObject`s to grow to ~30-80 MiB in size (where it should only be about ~100-200 KiB) - also the `DeepCopy` needs tens of seconds to finish!

### Steps to reproduce

- Define a `Class` and an `Objectbrick` with a `block` field (see below for simple examples)
- Create a `DataObject` of the new `Class` and add the `Objectbrick`
- Add some entries to the block
- Save the `DataObject`
- Look into the created cache entry (e.g. by creating a [debug breakpoint here](https://github.com/pimcore/pimcore/blob/4cd9301b1f40b9e67ac73c3e49fcaeaab9f33fb7/lib/Cache/Core/CoreCacheHandler.php#L581))

You'll see that it contains the `Objectbrick`, its data, and the block entries several times, which is wrong.

---

<details><summary>Contents of: class_BlockInBrickTest_export.json</summary>
<pre>
{
    "id": "block_in_brick_test",
    "description": "",
    "modificationDate": 1644339251,
    "parentClass": "",
    "implementsInterfaces": "",
    "listingParentClass": "",
    "useTraits": "",
    "listingUseTraits": "",
    "allowInherit": false,
    "allowVariants": false,
    "showVariants": false,
    "layoutDefinitions": {
        "fieldtype": "panel",
        "layout": null,
        "border": false,
        "name": "pimcore_root",
        "type": null,
        "region": null,
        "title": null,
        "width": 0,
        "height": 0,
        "collapsible": false,
        "collapsed": false,
        "bodyStyle": null,
        "datatype": "layout",
        "permissions": null,
        "childs": [
            {
                "fieldtype": "panel",
                "layout": null,
                "border": false,
                "name": "Layout",
                "type": null,
                "region": null,
                "title": "",
                "width": "",
                "height": "",
                "collapsible": false,
                "collapsed": false,
                "bodyStyle": "",
                "datatype": "layout",
                "permissions": null,
                "childs": [
                    {
                        "fieldtype": "objectbricks",
                        "allowedTypes": [
                            "BlockInBrickTest"
                        ],
                        "maxItems": "",
                        "border": false,
                        "name": "Brick",
                        "title": "Brick",
                        "tooltip": "",
                        "mandatory": false,
                        "noteditable": false,
                        "index": false,
                        "locked": false,
                        "style": "",
                        "permissions": null,
                        "datatype": "data",
                        "relationType": false,
                        "invisible": false,
                        "visibleGridView": false,
                        "visibleSearch": false
                    }
                ],
                "locked": false,
                "icon": "",
                "labelWidth": 0,
                "labelAlign": "left"
            }
        ],
        "locked": false,
        "icon": null,
        "labelWidth": 100,
        "labelAlign": "left"
    },
    "icon": "",
    "previewUrl": "",
    "group": "",
    "showAppLoggerTab": false,
    "linkGeneratorReference": "",
    "previewGeneratorReference": "",
    "compositeIndices": [],
    "generateTypeDeclarations": true,
    "showFieldLookup": false,
    "propertyVisibility": {
        "grid": {
            "id": true,
            "key": false,
            "path": true,
            "published": true,
            "modificationDate": true,
            "creationDate": true
        },
        "search": {
            "id": true,
            "key": false,
            "path": true,
            "published": true,
            "modificationDate": true,
            "creationDate": true
        }
    },
    "enableGridLocking": false
}
</pre>
</details>

<details><summary>Contents of: objectbrick_BlockInBrickTest_export.json</summary>
<pre>
{
    "classDefinitions": [
        {
            "classname": "BlockInBrickTest",
            "fieldname": "Brick"
        }
    ],
    "key": null,
    "parentClass": "",
    "implementsInterfaces": "",
    "title": "",
    "group": "",
    "layoutDefinitions": {
        "fieldtype": "panel",
        "layout": null,
        "border": false,
        "name": null,
        "type": null,
        "region": null,
        "title": null,
        "width": 0,
        "height": 0,
        "collapsible": false,
        "collapsed": false,
        "bodyStyle": null,
        "datatype": "layout",
        "permissions": null,
        "childs": [
            {
                "fieldtype": "panel",
                "layout": null,
                "border": false,
                "name": "Layout",
                "type": null,
                "region": null,
                "title": "",
                "width": "",
                "height": "",
                "collapsible": false,
                "collapsed": false,
                "bodyStyle": "",
                "datatype": "layout",
                "permissions": null,
                "childs": [
                    {
                        "fieldtype": "block",
                        "lazyLoading": false,
                        "disallowAddRemove": false,
                        "disallowReorder": false,
                        "collapsible": false,
                        "collapsed": false,
                        "maxItems": null,
                        "columnType": "longtext",
                        "styleElement": "",
                        "childs": [
                            {
                                "fieldtype": "input",
                                "width": "",
                                "defaultValue": null,
                                "queryColumnType": "varchar",
                                "columnType": "varchar",
                                "columnLength": 190,
                                "regex": "",
                                "unique": false,
                                "showCharCount": false,
                                "name": "Text",
                                "title": "Text",
                                "tooltip": "",
                                "mandatory": false,
                                "noteditable": false,
                                "index": false,
                                "locked": false,
                                "style": "",
                                "permissions": null,
                                "datatype": "data",
                                "relationType": false,
                                "invisible": false,
                                "visibleGridView": false,
                                "visibleSearch": false,
                                "defaultValueGenerator": ""
                            }
                        ],
                        "layout": null,
                        "fieldDefinitionsCache": null,
                        "name": "Block",
                        "title": "Block",
                        "tooltip": "",
                        "mandatory": false,
                        "noteditable": false,
                        "index": false,
                        "locked": false,
                        "style": "",
                        "permissions": null,
                        "datatype": "data",
                        "relationType": false,
                        "invisible": false,
                        "visibleGridView": false,
                        "visibleSearch": false
                    }
                ],
                "locked": false,
                "icon": "",
                "labelWidth": 0,
                "labelAlign": "left"
            }
        ],
        "locked": false,
        "icon": null,
        "labelWidth": 100,
        "labelAlign": "left"
    },
    "generateTypeDeclarations": true
}
</pre>
</details>

---

Here's the data of the example `Class`/`Objectbrick` from above with three `BlockElement`s (`test1`, `test2` and `test3`):
<details><summary>Serialized cache entry</summary>
O:41:"Pimcore\Model\DataObject\BlockInBrickTest":23:{s:12:" * o_classId";s:19:"block_in_brick_test";s:14:" * o_className";s:16:"BlockInBrickTest";s:8:" * Brick";O:47:"Pimcore\Model\DataObject\BlockInBrickTest\Brick":5:{s:15:" * brickGetters";a:1:{i:0;s:16:"BlockInBrickTest";}s:19:" * BlockInBrickTest";O:58:"Pimcore\Model\DataObject\Objectbrick\Data\BlockInBrickTest":6:{s:7:" * type";s:16:"BlockInBrickTest";s:8:" * Block";a:3:{i:0;a:1:{s:4:"Text";O:42:"Pimcore\Model\DataObject\Data\BlockElement":7:{s:7:" * name";s:4:"Text";s:7:" * type";s:5:"input";s:7:" * data";s:5:"test1";s:23:" * needsRenewReferences";b:1;s:9:" * _owner";O:47:"Pimcore\Model\DataObject\BlockInBrickTest\Brick":5:{s:15:" * brickGetters";a:1:{i:0;s:16:"BlockInBrickTest";}s:19:" * BlockInBrickTest";O:58:"Pimcore\Model\DataObject\Objectbrick\Data\BlockInBrickTest":6:{s:7:" * type";s:16:"BlockInBrickTest";s:8:" * Block";a:3:{i:0;a:1:{s:4:"Text";r:11;}i:1;a:1:{s:4:"Text";O:42:"Pimcore\Model\DataObject\Data\BlockElement":7:{s:7:" * name";s:4:"Text";s:7:" * type";s:5:"input";s:7:" * data";s:5:"test2";s:23:" * needsRenewReferences";b:1;s:9:" * _owner";r:16;s:13:" * _fieldname";s:5:"Block";s:12:" * _language";N;}}i:2;a:1:{s:4:"Text";O:42:"Pimcore\Model\DataObject\Data\BlockElement":7:{s:7:" * name";s:4:"Text";s:7:" * type";s:5:"input";s:7:" * data";s:5:"test3";s:23:" * needsRenewReferences";b:1;s:9:" * _owner";r:16;s:13:" * _fieldname";s:5:"Block";s:12:" * _language";N;}}}s:12:" * fieldname";s:5:"Brick";s:11:" * doDelete";b:0;s:11:" * objectId";i:9;s:12:" * _fulldump";b:0;}s:8:" * items";a:0:{}s:12:" * fieldname";s:5:"Brick";s:11:" * objectId";i:9;}s:13:" * _fieldname";s:5:"Block";s:12:" * _language";N;}}i:1;a:1:{s:4:"Text";O:42:"Pimcore\Model\DataObject\Data\BlockElement":7:{s:7:" * name";s:4:"Text";s:7:" * type";s:5:"input";s:7:" * data";s:5:"test2";s:23:" * needsRenewReferences";b:1;s:9:" * _owner";O:47:"Pimcore\Model\DataObject\BlockInBrickTest\Brick":5:{s:15:" * brickGetters";a:1:{i:0;s:16:"BlockInBrickTest";}s:19:" * BlockInBrickTest";O:58:"Pimcore\Model\DataObject\Objectbrick\Data\BlockInBrickTest":6:{s:7:" * type";s:16:"BlockInBrickTest";s:8:" * Block";a:3:{i:0;a:1:{s:4:"Text";O:42:"Pimcore\Model\DataObject\Data\BlockElement":7:{s:7:" * name";s:4:"Text";s:7:" * type";s:5:"input";s:7:" * data";s:5:"test1";s:23:" * needsRenewReferences";b:1;s:9:" * _owner";r:57;s:13:" * _fieldname";s:5:"Block";s:12:" * _language";N;}}i:1;a:1:{s:4:"Text";r:52;}i:2;a:1:{s:4:"Text";O:42:"Pimcore\Model\DataObject\Data\BlockElement":7:{s:7:" * name";s:4:"Text";s:7:" * type";s:5:"input";s:7:" * data";s:5:"test3";s:23:" * needsRenewReferences";b:1;s:9:" * _owner";r:57;s:13:" * _fieldname";s:5:"Block";s:12:" * _language";N;}}}s:12:" * fieldname";s:5:"Brick";s:11:" * doDelete";b:0;s:11:" * objectId";i:9;s:12:" * _fulldump";b:0;}s:8:" * items";a:0:{}s:12:" * fieldname";s:5:"Brick";s:11:" * objectId";i:9;}s:13:" * _fieldname";s:5:"Block";s:12:" * _language";N;}}i:2;a:1:{s:4:"Text";O:42:"Pimcore\Model\DataObject\Data\BlockElement":7:{s:7:" * name";s:4:"Text";s:7:" * type";s:5:"input";s:7:" * data";s:5:"test3";s:23:" * needsRenewReferences";b:1;s:9:" * _owner";O:47:"Pimcore\Model\DataObject\BlockInBrickTest\Brick":5:{s:15:" * brickGetters";a:1:{i:0;s:16:"BlockInBrickTest";}s:19:" * BlockInBrickTest";O:58:"Pimcore\Model\DataObject\Objectbrick\Data\BlockInBrickTest":6:{s:7:" * type";s:16:"BlockInBrickTest";s:8:" * Block";a:3:{i:0;a:1:{s:4:"Text";O:42:"Pimcore\Model\DataObject\Data\BlockElement":7:{s:7:" * name";s:4:"Text";s:7:" * type";s:5:"input";s:7:" * data";s:5:"test1";s:23:" * needsRenewReferences";b:1;s:9:" * _owner";r:98;s:13:" * _fieldname";s:5:"Block";s:12:" * _language";N;}}i:1;a:1:{s:4:"Text";O:42:"Pimcore\Model\DataObject\Data\BlockElement":7:{s:7:" * name";s:4:"Text";s:7:" * type";s:5:"input";s:7:" * data";s:5:"test2";s:23:" * needsRenewReferences";b:1;s:9:" * _owner";r:98;s:13:" * _fieldname";s:5:"Block";s:12:" * _language";N;}}i:2;a:1:{s:4:"Text";r:93;}}s:12:" * fieldname";s:5:"Brick";s:11:" * doDelete";b:0;s:11:" * objectId";i:9;s:12:" * _fulldump";b:0;}s:8:" * items";a:0:{}s:12:" * fieldname";s:5:"Brick";s:11:" * objectId";i:9;}s:13:" * _fieldname";s:5:"Block";s:12:" * _language";N;}}}s:12:" * fieldname";s:5:"Brick";s:11:" * doDelete";b:0;s:11:" * objectId";i:9;s:12:" * _fulldump";b:0;}s:8:" * items";a:0:{}s:12:" * fieldname";s:5:"Brick";s:11:" * objectId";i:9;}s:20:" * __rawRelationData";a:0:{}s:14:" * o_published";b:1;s:7:" * o_id";i:9;s:13:" * o_parentId";i:1;s:9:" * o_type";s:6:"object";s:8:" * o_key";s:16:"BlockInBrickTest";s:9:" * o_path";s:1:"/";s:10:" * o_index";i:0;s:17:" * o_creationDate";i:1644339290;s:21:" * o_modificationDate";i:1644402783;s:14:" * o_userOwner";i:2;s:21:" * o_userModification";i:2;s:13:" * o_siblings";a:0:{}s:16:" * o_hasSiblings";a:0:{}s:11:" * o_locked";N;s:19:" * o_childrenSortBy";N;s:22:" * o_childrenSortOrder";N;s:17:" * o_versionCount";i:37;s:25:" * __dataVersionTimestamp";i:1644402783;s:12:" * _fulldump";b:0;}
</details>

**Comment by jdreesen** [comment]
When I add a filter that sets the `_owner` field to `null` to the DeepCopy instance in [`marshalForCache()`](https://github.com/pimcore/pimcore/blob/4cd9301b1f40b9e67ac73c3e49fcaeaab9f33fb7/models/DataObject/Data/BlockElement.php#L220-L249) (like `$copier->addFilter(new SetNullFilter(), new PropertyNameMatcher('_owner'));`) the cache entry doesn't expand anymore.

But I don't know how to re-create the `_owner` field after deserialization of the cache entry.

**Comment by jdreesen** [comment]
Maybe #6789 is related?

**Comment by dvesh3** [comment]
@jdreesen could you please give it a try? https://github.com/pimcore/pimcore/pull/11561 thanks! 😉

**Comment by brusch** [comment]
Fixed by #11561

**Comment by jdreesen** [comment]
@dvesh3 A bit late, but as far as I can see this fixes the issue. Many thx for this! :heart:
