### ISSUE TITLE
[Improvement]: Highlight localized fields in data object edit mode

### ISSUE THREAD

**Issue by akno77** [pimcore/pimcore#11413]
### Improvement description

If you have some localized fields in your data object followed by some none localized fields it is hard to recognize which fields belong to the localization tab and which not. Would it be possible to highlight somehow the localized fields tab area?

The current situation can lead to accidentally entering localized data into non-localized fields.

Here you don't see, which fields belong to the localized tab:
![grafik](https://user-images.githubusercontent.com/35833873/153213606-133c225d-4d4d-4805-bc2a-5169a2797344.png)

If the following fields were actually localized fields with the same data entered for each locale it would look exactly the same when switching between the tabs.

Better would be too highlight the localzed fields:
![grafik](https://user-images.githubusercontent.com/35833873/153213643-ae614eba-d8ad-49fa-bac4-3d42ce5b4cd5.png)

**Comment by fashxp** [comment]
We will improve that with the new UI.
