### ISSUE TITLE
[Bug]: \Pimcore\Bootstrap::prepareEnvVariables forces using DotEnv

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#11411]
### Expected behavior

When running in modern environments like Lambda or containers (local dev and prod), the env vars are not distributed via files but are **real environment variables**. In which case the DotEnv component creates some issues and noise, so it's generally a best practice to not use it there at all. This is known even to Symfony so [they support checking for it being installed or disabling it in their Runtime component](https://symfony.com/doc/current/components/runtime.html#using-options).

Pimcore currently hard requires the `DotEnv` component (which is IMO a mistake, as discussed in #11105), but the component itself can be removed in a hackish way by adding this to your own `composer.json`:

```json
    "provide": {
        "symfony/dotenv": "v5.4.0"
    },
```

The `DotEnv` component should be removed as the hard dependency and the loading using it of it should be made optional (either via config or at least checking with `class_exists` that it's there).

### Actual behavior

`DotEnv` component hardcoded into Pimcore 10.x

### Steps to reproduce

1. add to your `composer.json`:
```json
    "provide": {
        "symfony/dotenv": "v5.4.0"
    },
```
2. run `composer update`, `symfony/dotenv` gets removed
3. `\Pimcore\Bootstrap::prepareEnvVariables` complains about the class not being available

**Comment by dpfaffenbauer** [comment]
Solution is: make `dotenv` optional and check if installed in `prepareEnvVariables`?

**Comment by dkarlovi** [comment]
@dpfaffenbauer I think so, yes. AFAIK, it's only ever used there and the behaviour is optional anyway: if your `.env` file is empty, it does nothing. This would make the whole component optional (can be suggested in `composer.json`) and, if there, it loads the `.env` file.
