### ISSUE TITLE
[Bug]: Nice Paths for Reverse object relations are  not working

### ISSUE THREAD

**Issue by ctippler** [pimcore/pimcore#11427]
### Expected behavior

If you define a path formatter in a reverse object relation the returned values are not applied.
The url /admin/element/get-nice-path is called but the returned values are not applied

### Actual behavior

...

### Steps to reproduce

..

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
