### ISSUE TITLE
Object brick specific settings panel is empty

### ISSUE THREAD

**Issue by schuttelaar** [pimcore/pimcore#1142]
When adding an object brick field to an object there is supposed to be the ability to set the "allowed types". However, this option does not appear in the user interface. The "Specific settings" panel remains empty. What should appear is a multiselect where the user can select multiple object bricks that are allowed to be used.

I was using the Pimcore E-Commerce Framework when I encountered this. It is impossible to add another payment method to the OnlineShopOrder object. When exporting the class it does contain the following data with a list of allowed types, but these are not editable though the Pimcore UI.
`
{
								"fieldtype":"objectbricks",
								"phpdocType":"\\Pimcore\\Model\\Object\\Objectbrick",
								"allowedTypes":[
									"PaymentProviderQpay",
									"PaymentProviderPayPal",
									"PaymentProviderDatatrans"
								],
								"name":"paymentProvider",
								"title":"Payment Provider",
								"tooltip":"",
								"mandatory":false,
								"noteditable":false,
								"index":false,
								"locked":false,
								"style":"",
								"permissions":null,
								"datatype":"data",
								"columnType":null,
								"queryColumnType":null,
								"relationType":false,
								"invisible":false,
								"visibleGridView":false,
								"visibleSearch":false
							},
`
![screen shot 2016-12-21 at 11 29 19](https://cloud.githubusercontent.com/assets/385347/21386023/236a73c4-c771-11e6-84cb-7c5f5c3eaacb.png)

**Comment by weisswurstkanone** [comment]
Hi, this works the other way round. You have to specify this in the brick definition. See https://www.pimcore.org/docs/latest/Objects/Object_Classes/Data_Types/Object_Bricks.html
