### ISSUE TITLE
[Bug]: Restore document from recycle bin fails

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#11421]
### Expected behavior

can restore pimcore documents

### Actual behavior

fails due to database error .... 

Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`pimcore`.`documents_editables`, CONSTRAINT `fk_documents_editables_documents` FOREIGN KEY (`documentId`) REFERENCES `documents` (`id`) ON DELETE CASCADE) in /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117 Stack trace: #0 /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute(NULL)

### Steps to reproduce

create document, delete document, try to restore it from recyclebin

**Comment by dvesh3** [comment]
Fixed by #11425
