### ISSUE TITLE
[Bug]: Translations - filtered CSV export not possible

### ISSUE THREAD

**Issue by laurenz-glueck** [pimcore/pimcore#11429]
### Expected behavior

If I filter down translations and click "CSV export".
A dialog appears and I have the option to download only the filtered values.
If I click "yes" - I expect the CSV file to only contain the filtered translations.

### Actual behavior

Clicking on "CSV export" in a filtered state opens the "Do you want to export only the filtered values?" dialog but immediately downloads a CSV with all unfiltered translations.

Selecting "yes" in the dialog has no effect.

### Steps to reproduce

1. Go to translations menu
2. Filter translations (for example by searching for a specific key)
3. Click on "CSV export"
4. Dialog for filtered download appears but CSV download with all translations is triggered

**Issue is reproducible on public Pimcore demo!**

**Comment by dvesh3** [comment]
Fixed by #11439
