### ISSUE TITLE
[Improvement]: Translations UI improvements

### ISSUE THREAD

**Issue by laurenz-glueck** [pimcore/pimcore#11430]
### Improvement description

Before Pimcore v10.3.0 it was possible to right-click on a translation value and select "Edit as plain text" and "Edit as HTML":

<img width="301" alt="Screenshot 2022-02-10 at 19 53 49@2x" src="https://user-images.githubusercontent.com/2734232/153476945-39a770be-6a55-4f04-b4f0-eba10926f73d.png">

Now you don't have the right click option anymore. It would be nice to bring this option back...

Previously it was also possible to just click on HTML translations and the "HTML Editor" was opened immediately.
Now you need to click on the translation and then on the new HTML edit button. (1 click more)

I think the UX could be improved as for my experience it got worse with the new implementation...

**Comment by fashxp** [comment]
Changes were necessary due to possible race conditions when updating multiple translations very fast. 
I fear we don't have too much options to improve that in combination with ExtJS. We will address that issue though in the new UI.
