### ISSUE TITLE
[Bug]: Reloading dirty data object fails

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#11454]
### Expected behavior

can reload any data object

### Actual behavior

reloading fails with JS error

![image](https://user-images.githubusercontent.com/8792145/154065548-c218a7cd-cde8-4ae8-a078-478d2f8262b9.png)

### Steps to reproduce

- Open data object
- change some data
- press reload button

**Comment by dvesh3** [comment]
Fixed already by https://github.com/pimcore/pimcore/pull/11417
