### ISSUE TITLE
[Bug]: The Calculated Field cloning skips Type and Expression.

### ISSUE THREAD

**Issue by kaurov** [pimcore/pimcore#11452]
### Expected behavior

When the 'Calculated value' field is cloned, then:
-  'Calculator type' is copied and is the same as of source field, not empty
- 'Calculator expression' is the same as of source field, not empty

### Actual behavior

When Calculate field is cloned, then:
-  'Calculator type' property is empty but should be the same as of source field
- 'Calculator expression' property is empty but should be the same as of source field

### Steps to reproduce

1. Click on Settings -> Data Objects -> Classes,
2. choose existing or create the new Class
3. choose existing or create the new Calculated Field (Add Data Component -> Others -> Calculated Value)
4. Fill 'Calculator type' property 
5. Fill 'Calculator expression' property
6. Save
7. Click on the existing Calculated field with a right mouse button and select 'Clone'
8. Open the newly cloned Calculated field for editing and see the following: <See Actual behavior>

behavior

**Comment by blankse** [comment]
@kaurov I created a PR. Can you test it?

**Comment by dvesh3** [comment]
> @kaurov I created a PR. Can you test it?

verified it.
