### ISSUE TITLE
Workflow: required date-field in additional fields doesn't validate

### ISSUE THREAD

**Issue by RobinBrackez** [pimcore/pimcore#1146]
# Bug Report
Date fields in the workflowmanagement are not validated even if they are set to be required.
  
### Expected behavior 
I expect that there will be warning saying "you have to fill in the date field". I also expect that the form shouldn't submit until a date is filled in.
  
### Actual behavior  
Form submits and "false" (or: 0) is being set as value of the date
  
### Steps to reproduce  
Create a workflow in workflowmanagement.php with an action that has a date as additional field.
Then go to the workflow, don't fill in the date and submit it.
  
### Code example 
file: website/config/workflowmanagement.php

Example configuration:

``` php
            "actions" => [
                     ...
                    "additionalFields" => [                    //define additional fields needed
                        [
                            "name"=> "date_from",              // the name (for the frontend form)
                            "fieldType"=> "date",              // the fieldtype (pimcore object tag name)
                            "title"=> "Publish from (date)",           // the title
                            "required"=> true,                 // whether or not the field is required
                        ]
```

**Comment by brusch** [comment]
Obsolete because of #3288
