### ISSUE TITLE
[Bug] [DataObjects]: Incorrect index sorting

### ISSUE THREAD

**Issue by MyZik** [pimcore/pimcore#11468]
### Expected behavior

 If folder/object has option "Sort children by -> Index (Manual)", the objects should be automatically sorted and reindexed by CRUD-actions. Actually reindex only works if we change the place manually.

### Actual behavior

I have created a folder with option "Sort children by -> Index (Manual)". Then I have added data objects, but they getting per default index 0. Example here:

<img width="311" alt="Bildschirmfoto 2022-02-16 um 15 28 46" src="https://user-images.githubusercontent.com/12817320/154285644-dbfa8834-e3c2-4032-b2f5-d451661ef773.png">

View in a database:

<img width="866" alt="Bildschirmfoto 2022-02-16 um 15 29 47" src="https://user-images.githubusercontent.com/12817320/154285615-be44e051-0f93-420f-a710-0d0ebdd42d1e.png">

After publishing the problem still the same:

<img width="860" alt="Bildschirmfoto 2022-02-16 um 15 31 27" src="https://user-images.githubusercontent.com/12817320/154285928-4231fe7f-d4c5-42ba-b4b1-450f2d66272d.png">

Then I have reordered the categories and reindex works:

<img width="307" alt="Bildschirmfoto 2022-02-16 um 15 34 20" src="https://user-images.githubusercontent.com/12817320/154286482-df572f02-b52e-4f14-9551-4057b59e4e27.png">
<img width="877" alt="Bildschirmfoto 2022-02-16 um 15 34 39" src="https://user-images.githubusercontent.com/12817320/154286524-d03043f0-bcac-4eff-8e52-f35bc317ada8.png">

Then I have added 2 new categories:
<img width="312" alt="Bildschirmfoto 2022-02-16 um 15 36 45" src="https://user-images.githubusercontent.com/12817320/154286960-5196f56c-afb1-4240-a9ba-f9c92acde723.png">

And we have wrong values by o_Index
<img width="860" alt="Bildschirmfoto 2022-02-16 um 15 36 30" src="https://user-images.githubusercontent.com/12817320/154286906-d28defd3-621c-4e87-bf8d-f0e182007349.png">

 

### Steps to reproduce

1. Create folder with option Sort children by -> Index (Manual)
2. Add objects in your folder
3. Check indexes in DB

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
