### ISSUE TITLE
Quicksearch exception if brick found

### ISSUE THREAD

**Issue by ascheider** [pimcore/pimcore#11460]
### Expected behavior

I should be able to use quick search without error.

### Actual behavior

Currently if you have bricks with localized fields and use quick search, you get exception: Variable "languages" does not exist in pimcore/bundles/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/object.html.twig
![quicksearch](https://user-images.githubusercontent.com/6016485/154220345-d87ef90b-46ab-4ff6-b6a0-18488ebbf3b5.png)
It seems pimcore tries to access "languages" which are not defined in this elseif branch
![image](https://user-images.githubusercontent.com/6016485/154221560-38879e6b-a637-4007-a319-77f7eaa9665f.png)

### Steps to reproduce

Create brick with localized fields and input some data into brick. Run pimcore:search-backend-reindex and try to search in the quicksearch for your keyword.

**Comment by blankse** [comment]
@ascheider I created a PR. Can you test it?

**Comment by dvesh3** [comment]
> @ascheider I created a PR. Can you test it?

verified it.
