### ISSUE TITLE
[Bug]: Tooltips overriding error popups

### ISSUE THREAD

**Issue by thijs-windels** [pimcore/pimcore#11476]
### Expected behavior

In the admin interface, field description tooltips should be hidden when you stop hovering over them.

### Actual behavior

Tooltips with the description of a field in the admin interface sometimes just don't disappear. If then an error popup opens, the interface gets stuck and I'm unable to continue. I always need to refresh the page.
![image](https://user-images.githubusercontent.com/23450920/154438717-d44558db-007c-4229-9546-4fd1b76af820.png)

### Steps to reproduce

It's hard to reproduce and I am unable to make a simple list. It mostly happens suddenly when working on a DataObject. The description tooltips just don't disappear.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
