### ISSUE TITLE
[Bug]: Processing of messenger_messages becomes very slow

### ISSUE THREAD

**Issue by ctippler** [pimcore/pimcore#11486]
### Expected behavior

I had the issue that the entries in messenger_messages were not processed fast enough. This lead to the problem, that processing gets slower and slower, because a index is missing on a column and the table gets bigger and bigger.

I had 700000 entries in the table:

The following query is executed when a entry is selected:
SELECT m.* FROM messenger_messages m WHERE (m.delivered_at is null OR m.delivered_at < '2022-02-17 23:03:56') AND (m.available_at <= '2022-02-18 00:03:56') AND (m.queue_name = 'default') ORDER BY available_at ASC LIMIT 1 FOR UPDATE

The query took > 8 Seconds because a index is missing on "available_at". I added the index on available_at  manualliy and the query executes in < 0.2 seconds

This index should be set automatically

### Actual behavior

...

### Steps to reproduce

...

**Comment by dpfaffenbauer** [comment]
The table is actually created by Symfony and Symfony should take care about creating the index.

**Comment by brusch** [comment]
Yep, @ckogler-elements please open a ticket at Symfony, or even better a PR, makes definitely sense! Thanks!

**Comment by fashxp** [comment]
also check that out: 
https://github.com/symfony/doctrine-messenger/blob/5.4/Transport/Connection.php#L416

seems they are not creating these indices on purpose

**Comment by ctippler** [comment]
Thx for your hints. 

As fash mentioned it turned out to be because of deadlocks which occure when multiple "messenger:consume" processes were running. Although if you are just using one process it would be much faster... 

There seems to be a lot of disussion (and allready a pull request for creating the index):
https://github.com/symfony/symfony/pull/45007
https://github.com/symfony/symfony/pull/42345

For now i guess the best solution is to set up multiple "messenger:consume" processes so the table dosn't fill up that much :-).

Regards
