### ISSUE TITLE
Inheritance and localized fields -> improve performance

### ISSUE THREAD

**Issue by ckogler-elements** [pimcore/pimcore#1149]
### Actual behavior  
If we have a object with some childs (500) and many languages (~45) it might be, that we can't save the object anymore if inheritance is enabled. 
The saving process might stop because we get a DB-Error "General error: 1205 Lock wait timeout exceeded;".

This happens because the InhertanceHelper builds the object-tree for each language which might take a lot of time and therefore the transaction timeout occurs.

# Feature Request 
Improve performance: Cache first query result so we don't have to "build the tree" for each language because it is always the same.

**Comment by fashxp** [comment]
isn't that dangerous in case the tree changes (and the cached parentIds don't get cleaned up)?

**Comment by ckogler-elements** [comment]
Hmm... good point. As the runtime cache key contains the whole query (which also includes the object path) i think its unlikely that this leads to a problem (but it can, if you do some renaming of objects within the same process).  The question is: How can i clear the runtime cache without a lot of refactoring?

**Comment by fashxp** [comment]
what about this usecase? 
parent object gets updated (runtime cache is filled) > other objects get moved below parent object > parent object gets updated once more.

**Comment by ckogler-elements** [comment]
We now cache the result just during the iteration over the languages and clean the cache when all languages are processed. This way we are save. Further optimizations were also done. 

With this adoptions we can save the object much faster:
In my test-case (one object with about 40000 childs) was saved in:
Old version took: 41m13.685s
New version took: 2m22.196s

**Comment by fashxp** [comment]
did you test following use case: 
> parent object has no brick, add child to parent, add brick to parent & click save. without this code there will not be an entry in the query table for the child object?

**Comment by ckogler-elements** [comment]
Yes - it works. The logic is the same as it was before. We just build the id array in the buildTree() method because the recursive call of extractObjectIdsFromTreeChildren() took some seconds...

**Comment by fashxp** [comment]
nice 👍
