### ISSUE TITLE
[Bug]: colums missing in CSV Export from GRID with multiple operators of the same type

### ISSUE THREAD

**Issue by FranzRest** [pimcore/pimcore#11493]
### Expected behavior

When exporting a CSV from the grid I would expect to get a file with all the columns that are shown in Pimcore.
This should also be the case, when I use the same operator/formatter multiple times.

No columns should be missing.

### Actual behavior

Currently when you use the same operator/formatter multiple times, the csv export removes all of them except the first one.
This is the case, when you use the grid options to define your columns and use the same type multiple times.

It seems to be the case with all operators, where you can not explicitly set a name for the column head.
The export removes duplicate column-names.

### Steps to reproduce

1. Open a grid view for data objects
2. Set Grid Options with operators of the same type
![image](https://user-images.githubusercontent.com/6606770/154931116-075c379a-9ec6-4d7f-9710-ac74347e87e8.png)

2a) Grid View is fine
![image](https://user-images.githubusercontent.com/6606770/154930746-7780c2c0-f523-4ca4-a8d9-8fb5e1d6ee43.png)

3. Export the CSV File -> colum missing
![image](https://user-images.githubusercontent.com/6606770/154930908-e6c21520-e885-4342-b1d6-93ac48e6b0df.png)

**Comment by dvesh3** [comment]
If possible, I would pick the name of the attribute used in the formatter, since each formatter works with single attribute and then export data is meaningful with correct attribute headers.

**Comment by FranzRest** [comment]
consistency wise I would suggest that the user can set a custom label as well. 
For most of the other operators this can be done and would solve the problem, as the user is respsonible for non-duplicate labels.
Maybe the user can optionally set a custom label, the default ist your suggestions.

Picking the attribute name would work for most cases as well. But there could be edge cases that don't work like:
Formatting Date field with -> Y-M-D
Formatting same Date field with -> Y-D-M
Same field but different options would still lead to a missing column in the export

**Comment by mcop1** [comment]
We decided to revert the changes in the linked pull request, because it affects other bundles too. Please use the "alias" operator in the grid config dialog to add an alias to duplicate column names. See https://pimcore.com/docs/pimcore/current/User_Documentation/DataObjects/Grid_Configuration_Operators/Others/Alias.html#_
