### ISSUE TITLE
[Bug]: Encoding error, caused by HTML in pimcore_area brick settings

### ISSUE THREAD

**Issue by studio1gmbh** [pimcore/pimcore#11499]
### Expected behavior

Using HTML Markup in a `defaultValue` of an AreaBrick Editable Configuration should be possible without errors.  

### Actual behavior

When using HTML markup as a `defaultValue` inside a Area Brick configuration, the edit window wont open.

For example, the following config will not work:

```
$config->setItems([
    [
        'type' => 'wysiwyg',
        'label' => 'wysiwyg',
        'name' => 'myWysiwyg',
        'config' => [
            'defaultValue' => '<p>This will not work!</p>'
        ]
    ]
]);
```

Pimcore will `json_encode` the brick configuration and puts it inside a `<template>` tag. In the Pimcore backend the JSON will be used to populate the configuration window. 

https://github.com/pimcore/pimcore/blob/655c03bf92f2063852e1ed64b41099d4a2c407bb/models/Document/Editable/Area.php#L177

The result in the browser of the example above looks like this: 

![image](https://user-images.githubusercontent.com/99351817/154949303-f68a6501-2aec-45f0-a942-1de9041f5302.png)

As you see, the browser is interpreting the markup. Since the browser don't find any closing `<p>` tag in this example, it automatically creates one.  This causes a JS error, because the json is not valid anymore.

![image](https://user-images.githubusercontent.com/99351817/154949591-a8881da4-7662-4b58-bc8a-2c3bfdfb50a1.png)

https://github.com/pimcore/pimcore/blob/4d8a322a5ac18bf89e2f0fc7bf345346de857e88/bundles/AdminBundle/Resources/public/js/pimcore/document/editables/area_abstract.js#L21

This will only happen in the context of `pimcore_area`, because the `json_encode` happens in a PHP script. When using `pimcore_areablock` `json_encode` will be executed via twig without problems here: 
https://github.com/pimcore/pimcore/blob/4550a053fac47a1d2c0406bf15c9799ef078bbb7/bundles/CoreBundle/Resources/views/Areabrick/wrapper.html.twig#L34

--- 

The whole problem has been noticed by using the [Pimcore Toolbox ](https://github.com/dachcom-digital/pimcore-toolbox), which merges every regular value inside the `defaultValue`. 

A possible fix could be using a flag like `json_encode($dialogConfig, JSON_HEX_TAG)`.

### Steps to reproduce

1. Create an area brick with HTML markup in its `defaultValue``
2. Include the area brick with ` {{ pimcore_area("myArea", { 'type' : 'my-input' }) }}` 
3. JS error is thrown, editable window wont open

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
