### ISSUE TITLE
[Bug]: Closing object folder requires double click

### ISSUE THREAD

**Issue by Maksonis** [pimcore/pimcore#11504]
### Expected behavior

When click on "x" close object folder.

### Actual behavior

- first click results gray background:
![image](https://user-images.githubusercontent.com/17277953/155135469-db8f7e6a-7dce-41eb-a957-865fc42ef7a0.png)

- second click: closed

### Steps to reproduce

- In objects sections click on Home
- Select class, e.g. Car
- Click on "X" sign

**Comment by dvesh3** [comment]
Fixed by #11542
