### ISSUE TITLE
[Bug]: scripts used for admin minimized on demand (even in prod env) instead of at built-time

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#11505]
### Expected behavior

The admin UI is a build-time requirement, it should be satisfied as such.

Currently, scripts listed in `vendor/pimcore/pimcore/bundles/AdminBundle/Resources/views/Admin/Index/index.html.twig` get processed and minified into `var/admin/minified_javascript_core_bf4669852c609bea6be38a41c0f8485e.js` on demand (meaning, in runtime), this file then gets served by `\Pimcore\Bundle\AdminBundle\Controller\Admin\MiscController::scriptProxyAction`. This means:
1. `var/admin` **must** be writable at runtime
2. if you have Pimcore deployed in a HA environment, each instance will need to build their own copy of this
3. you can't (easily) do this work upfront, say when building a Docker image

Proposal here is to:
- move these files into `var/cache/<env>`
- add a Symfony cache warmer which will generate these files upfront when doing `cache:warmup` or `cache:clear --warmup`

Ideally, I guess the best possible solution would be to implement Symfony Webpack Encore, but that's a much more complex thing, as discussed in https://github.com/pimcore/pimcore/issues/10614

### Actual behavior

Assets minimized and processed on demand instead of being pre-processed and placed in the correct place by default.

### Steps to reproduce

Install skeleton Pimcore 10.x, go to /admin/, the files get generated in `var/admin` or a permission error is raised.

**Comment by dkarlovi** [comment]
Note: I know this is using Flysystem `admin` filesystem, but it's important to note this is not "data", it part of the application itself. The filesystem here is not really applicable.

**Comment by dpfaffenbauer** [comment]
👍

**Comment by brusch** [comment]
@dkarlovi Would be fine for me, we can even build the stuff using a GitHub Action and just add it statically to the repo ...
However this is currently not on our top priority list, so PRs are welcome 😊

**Comment by dkarlovi** [comment]
@brusch sure, understandable, I see none of my issues as "FIX THIS NOW!" :beers: It's more me going through a process and documenting things which seem out of place (to me), for (hopefully) a betterment to all.

I'm quite interested to get Pimcore in a place where it serves as a development platform better and my company and I will be doing work to do just that. Adding features and fixes which improve robustness / DX in our use cases will be our top priority.

**Comment by brusch** [comment]
@dkarlovi Yeah, definitely got your intention, just wanted to share that this topic makes sense to us and if anyone is interested in contributing this, we're willing to review and merge the PR 😉

**Comment by brusch** [comment]
Obsolete because of #10614
