### ISSUE TITLE
[Bug]: PimcoreUrl cannot resolve a data object's site-specific URL slug

### ISSUE THREAD

**Issue by woellundwoell** [pimcore/pimcore#11502]
### Steps to reproduce

We have a shop with categories. These categories are data objects and have a URL slug property. We also have two different sites set up. Now add a fallback URL slug to one category. Now add a slug for one specific site to the same category. (If you refresh the data object in the backend gui now the slugs will disappear but this a different matter and will receive a separate bug report or pull request today depending on what time allows us to do.)

Call the fallback slug URL: works. Creating links based on this (e.g. pagination) works as well.

Call the site specific slug URL: works as long as there are no links created in the rendered template.

### Actual behavior

Having links generated in the rendered template (e.g. pagination of articles inside a category in a shop) leads to a RouteNotFoundException:
`An exception has been thrown during the rendering of a template ("None of the chained routers were able to generate route: Route 'data_object_12345_/exampleSlug' not found").`

### Expected behavior

The route can be resolved and links/URLs can be generated.

Assumption: It works for the fallback slug but not for the site-specific slug because this line ultimately resolves the route "data_object_12345_/exampleSlug": https://github.com/pimcore/pimcore/blob/10.x/lib/Routing/Dynamic/DataObjectRouteHandler.php#L61
However this method has no knowledge of sites and therefore site specific slugs cannot be resolved.

We're happy to provide a pull request for this matter but we definitely need some pointers and directions on how to fix this to be able to do so in a timely manner.

**Comment by kingjia90** [comment]
i have took a look and it seems that multisite is kind of "not supported" here
https://github.com/pimcore/pimcore/blob/131ec1750f20b35142afeb4d1a0addeb1edfd38c/models/DataObject/Data/UrlSlug.php#L333
as far as i can tell, the /exampleSlug must always be something related to siteId=0 to work, because `resolveSlug` doesn't have the second parameter related to the siteId here in `getRouteByName`
https://github.com/pimcore/pimcore/blob/131ec1750f20b35142afeb4d1a0addeb1edfd38c/lib/Routing/Dynamic/DataObjectRouteHandler.php#L58-L61

not sure if it's a bug or is intended, i will ask the team and let you know, in the meanwhile i leave some notes of what i have noticed

**Comment by passioneight** [comment]
FYI, there is already an issue for the missing input fields: https://github.com/pimcore/pimcore/issues/10604. Also, the described behaviour is somewhat related to https://github.com/pimcore/pimcore/issues/11242.

**Comment by kingjia90** [comment]
@passioneight thank you, that's very helpful and they are indeed related.
I am close to getting a solution, i will test it over #11242 as well

**Comment by kingjia90** [comment]
@woellundwoell could you please try if the solution proposed here in #11557 fixes the problem? 
If no, could you please provide some further details on how to reproduce the problem (to see if we missed something)? 
Thank you in advance and wish you a nice weekend in the meanwhile

**Comment by brusch** [comment]
@woellundwoell 🏓

**Comment by woellundwoell** [comment]
@kingjia90 @brusch Sorry for the delay, we will try the proposed solution later this week. But it does look promising :)

**Comment by woellundwoell** [comment]
@kingjia90 @brusch 
Works like a charm!
