### ISSUE TITLE
[ImageThumbnails] Respect quality configuration for auto formats in pimcore:thumbnails:image command

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#11508]
### Expected behavior

please see https://github.com/pimcore/pimcore/commit/77bcc93b019ef83412f829948ca6fd279bc0dd59#commitcomment-67228922

### Actual behavior

please see https://github.com/pimcore/pimcore/commit/77bcc93b019ef83412f829948ca6fd279bc0dd59#commitcomment-67228922

### Steps to reproduce

1. Set quality of image thumbnail auto format as mentioned here https://pimcore.com/docs/pimcore/current/Development_Documentation/Assets/Working_with_Thumbnails/Image_Thumbnails.html#page_Customize-Auto-Web-Optimized-Format
2. Run command to generate image thumbnail `bin/console pimcore:thumbnails:image --thumbnails=MyThumbnail`
3. Image thumbnails are generated with quality defined in thumbnail config not the custom config in YAML.

**Comment by brusch** [comment]
Fixed by #11530
