### ISSUE TITLE
[Bug]: Create document translation -> inherit controller

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#11507]
### Expected behavior

When creating a document translation with inheritance the controller is set to defaultAction.

I've created a listener to inherit the controller, but imho this should be the default behaviour as the document type for main page and translation should match.

### Actual behavior

Document EN:
![image](https://user-images.githubusercontent.com/90033/155289335-73614a2b-0d77-4d0d-8762-558303d1c27b.png)

Creating a translation for DE will use the default controller:
![image](https://user-images.githubusercontent.com/90033/155289425-d7867bfc-ff70-4021-8b9b-cdca30a75c10.png)

### Steps to reproduce

Create a document with a custom controller.
Create a translation for this document.

Pimcore 10.3

**Comment by dvesh3** [comment]
Fixed by #11641
