### ISSUE TITLE
[Improvement]: Unify and clarify `oldest supported maintenance branch` for new PRs

### ISSUE THREAD

**Issue by mysliwietzflorian** [pimcore/pimcore#11514]
### Improvement description

Currently, the `supported maintenance branch` is inconsistent or unclear across the repository.

- In [README.md](https://github.com/pimcore/pimcore/blob/10.x/README.md) there is no mention of the maintenance branch or version
![image](https://user-images.githubusercontent.com/23225429/155305259-7046a01a-f4fa-491a-95e6-ea843de11e75.png)
![image](https://user-images.githubusercontent.com/23225429/155305304-3e4b6f13-38c5-4895-8134-593e241e1ce7.png)

- In [CONTRIBUTING.md](https://github.com/pimcore/pimcore/blob/10.x/CONTRIBUTING.md) it is stated to use *e.g. 10.1*
![image](https://user-images.githubusercontent.com/23225429/155305613-3e0609dd-3f97-4655-a2e9-68a600ce8496.png)

- While creating a new PR you can see *e.g. 10.0*
![image](https://user-images.githubusercontent.com/23225429/155306011-bd7474d1-84c0-4021-99e9-7f9ff49d22ff.png)

What's the currently supported maintenance branch or how can I find out?

**Comment by NiklasBr** [comment]
I think this is a good example of an issue where Stale Bot's *PR Welcome* is not correct. This seems like something that only Pimcore can clarify.

**Comment by fashxp** [comment]
> I think this is a good example of an issue where Stale Bot's _PR Welcome_ is not correct. This seems like something that only Pimcore can clarify.

that's exactly why we introduced the stale bot ... to be able to have an overview and prioritize - and also communicate clearly on what we will working on.

**Comment by mysliwietzflorian** [comment]
@NiklasBr Agreed. But with some more information from the core team a pull request - in this case - is still feasible from anybody.   😉
