### ISSUE TITLE
[Bug]: syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE)

### ISSUE THREAD

**Issue by lchhieu** [pimcore/pimcore#11517]
### Expected behavior

   .

### Actual behavior

syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE)

### Steps to reproduce

I used php 8.1.16 
+ run ./vendor/bin/pimcore-install
+ point virtual host to public folder
+ open in the browser and got the issue "syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE)"
_(Dont update anything in the code)_

**Comment by jdreesen** [comment]
In which file/line does the error occur?

**Comment by lchhieu** [comment]
@jdreesen just shows generic errors, doesn't find any specific view file. I will send you the error image tomorrow

**Comment by dpfaffenbauer** [comment]
seems you used a different PHP Version to run composer install than you use on your webserver

**Comment by brusch** [comment]
Try `composer diagnose` and check the PHP version.
