### ISSUE TITLE
[DISCUSSION]: ReverseObjectRelation should not support inheritance

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#11529]
### Expected behavior

Actually I don't think it makes sense that this data-type supports inheritance - for what reason, any use-cases? 

### Actual behavior

Actually the `ReverseObjectRelation` does support inheritance.

### Steps to reproduce

...

**Comment by fashxp** [comment]
possible use case: 
- products have relation to category, category has corresponding reverse object relation to its products. 
- products have inheritance activated, variants are implemented via child objects and inherit category relation from their master product
- on category reverse object relation, you might wanna see also variants that are assigned to that category

**Comment by brusch** [comment]
The described use-cases are about the inheritance on the originating objects, I was thinking about the actual reverse relation field, so e.g. if the reverse relation field on category object can't find reverse relations, should it try to get reverse relations from the parent category....

All of the 3 described use-cases are anyhow not possible at the moment, as the inherited data is not gettings persited in the corresponding `object_relation_*` tables, thus it cannot be queried.

**Comment by brusch** [comment]
Added 
https://github.com/pimcore/pimcore/blob/b26d41f4f7dfd7a6b606b30495bab56ffc305d7c/models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php#L248
in #10242 as it's currently anyway not working 😉

Closing this for now.
