### ISSUE TITLE
[Feature]: database export

### ISSUE THREAD

**Issue by cipribucur** [pimcore/pimcore#11525]
### Feature description

- command line entry pimcore:database:export where you can, based on the existing db config, export the pimcore database. some cleaning parameters will also be nice to have. 
- a pair pimcore:database:export/pimcore:database:import will also increase the developer experience

**Comment by spotbot2k** [comment]
We do integrate a command for export in our installation, it uses `mysqldump`, I could create a PR. Or is a standalone solution like [https://write.corbpie.com/php-pdo-mysql-backup-script-with-compression-option/](https://write.corbpie.com/php-pdo-mysql-backup-script-with-compression-option/) more suitable?

**Comment by aryaantony92** [comment]
@spotbot2k Nice. We would prefer to have a standalone solution using a php library.

**Comment by brusch** [comment]
Why not using plain `mysqldump`? 😬 It has covers all possible use cases and has many options to customize the export ...?

**Comment by fashxp** [comment]
- what about cloud databases? 
- would add an additional requirement to system requirements

**Comment by brusch** [comment]
What I meant was to NOT provide another Pimcore tool/command that does that, but instead just use tools like `mysqldump` that are build for just do this job 😉 (and probably do it much better than a Pimcore command could do it)
