### ISSUE TITLE
[Bug]: "black bars" in images of asset folder preview

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#11528]
### Expected behavior

the tile size in the asset folder preview is 130x130, if an image is bigger than it, it should just shrink to fit and to not affect the tile look (#9029) by adding any black bars.

### Actual behavior

Any image that have less than 800px (either width or height) have black bars around it when generated as a tile in the folder preview.

![image](https://user-images.githubusercontent.com/6014195/155517575-d765211c-38ac-43ab-a493-10a5001d4094.png)
 

### Steps to reproduce

Upload any image that have a size less than 800x800 and hover on the parent folder to see the folder preview.
On the Demo, it's visible in the "Brand Logos" folder as the provided screenshot. Citroen logo is the only one bigger than 800x800, good as reference of how big the tile actually should be.

Likely caused by things involving DPI when generating the tile🤔

**Comment by brusch** [comment]
Fixed by #11534
