### ISSUE TITLE
[Bug]: PDF thumbnail generation is not working

### ISSUE THREAD

**Issue by Ricardocanul7** [pimcore/pimcore#11532]
### Expected behavior

upload PDF assets should generate thumbnails

### Actual behavior

When creating a thumbnail for a PDF document it doesn't create the file, so when trying to fetch the asset stream back, it throws an error

I notice in Demo this is not working as well, I uploaded 2 pdf and there's no thumbnail.
![image](https://user-images.githubusercontent.com/18083362/155545620-3daa4a92-8b3d-434e-b173-78d4e797dc61.png)

### Steps to reproduce

Call getImageThumbnail and then call getStream to save thumbnail as an asset

Tracing the problem I found that commenting
`Console::addLowProcessPriority($cmd);` located in
`/pimcore/lib/Document/Adapter/Ghostscript.php:197`

Will allow to generate the thumbnails, there's an error when executing `nice -n 19`, and breaks the whole functionality

![image](https://user-images.githubusercontent.com/18083362/155547082-2952f1f1-033a-4b33-bbaa-94a5e1ad3396.png)

**Comment by dvesh3** [comment]
@Ricardocanul7 Asset Document (PDF in your case) thumbnail generation is done asynchronously as part of the maintenance job or through a Symfony messenger worker. On demo, no worker is setup so thumbnails are not generated. please see https://github.com/pimcore/pimcore/issues/7665

**Comment by Ricardocanul7** [comment]
Ohh you're right I notice workers are not working in the demo now, but in my local I have maintenance worker running and I have the same issue, the thing is that it generates thumbnail for images but only pdf doesn't work.

**Comment by dvesh3** [comment]
please check if your maintenance worker is setup correctly. see upgrade notes https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/index.html#page_10-2-0

**Comment by Ricardocanul7** [comment]
This problem has been solved

#11537
