### ISSUE TITLE
[Bug]: ObjectBrick does not properly inherit data from parent object when validating fields

### ISSUE THREAD

**Issue by aclDeveloper** [pimcore/pimcore#11538]
### Expected behavior

Saving a child element containing an Objectbrick with inherited mandatory values takes parent's values into consideration when validating, as hinted correctly in UI.

### Actual behavior

This applies to all objects' children (Variants, Children) where inheritance is enabled and object bricks are present. After creating a new child element, the values of the parent object's brick are correctly shown. Publishing the child element triggers a ValidationException.

![Callstack_invalid_brick](https://user-images.githubusercontent.com/20439617/155710485-06b8df09-2476-419f-8b53-8eb6dd427073.png)

During validation in `models/DataObject/Concrete.php/update()` in line 128 `$this->$getter()` returns a new/blank instance of the Objectbrick instead of the parent's values. I suppose this is because of an existing entry in `object_brick_store_<name>_<clsId>` table which is channeled through the DAO and not enriched with the parent's data?

![image](https://user-images.githubusercontent.com/20439617/155710691-6abcc308-95dc-4e10-9492-e39cd6a372e8.png)

In `models/DataObject/ClassDefinition/Data/Objectbricks.php/checkValidity()` the validation fails due to empty field contents on the mandatory field by definition.

See the call stack here:

Timestamp: Fri Feb 25 2022 12:19:57 GMT+0100 (Mitteleuropäische Normalzeit)
Status: 422 | Unprocessable Content
URL: /admin/object/save?task=publish
Method: PUT
Message: Validation failed: invalid brick misc: Empty mandatory field [ specialNumber ][ misc ]
Trace: 
in /var/www/vendor/pimcore/pimcore/models/DataObject/Concrete.php:188
#0 /var/www/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(734): Pimcore\Model\DataObject\Concrete->update(true, Array)
#1 /var/www/vendor/pimcore/pimcore/models/DataObject/Concrete.php(714): Pimcore\Model\DataObject\AbstractObject->save(Array)
#2 /var/www/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(1367): Pimcore\Model\DataObject\Concrete->save()
#3 /var/www/vendor/symfony/http-kernel/HttpKernel.php(152): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#4 /var/www/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 {main}

### Steps to reproduce

1. Create a new Object definition
2. In said definition enable Inheritance and Variants
![image](https://user-images.githubusercontent.com/20439617/155711875-a1755b80-ef6e-425f-9720-fb08e40f3908.png)

3. Add an Object Brick field to the definition
![image](https://user-images.githubusercontent.com/20439617/155711931-d0e4dbfe-2e03-4cda-8470-a1b9547466c3.png)

4. Create a new Object Brick definition
5. In said Object Brick definition add a mandatory field
![image](https://user-images.githubusercontent.com/20439617/155712066-dad78bf4-9d4a-486e-8069-26bf706c2f56.png)

6. Link the definition with the Object's brick field
![image](https://user-images.githubusercontent.com/20439617/155712024-74739aa3-909e-43a2-989f-def8879acb3c.png)

7. Create a new Object and fill all data, save
8. Create a new Variant of that Object 
9. You can see the inherited value
![image](https://user-images.githubusercontent.com/20439617/155712129-6f1a16c8-2de2-4488-8aec-6b37d7e983c0.png)

10. When trying to publish you will get the validation error.

**Comment by kingjia90** [comment]
Thank you for the very detailed info on the issue.


So far, i've found that we are skipping this "fallback" here
https://github.com/pimcore/pimcore/blob/aa0ed48fd97757fc0b30bd2985eef2a237b373c6/models/DataObject/Concrete.php#L135 
related to #10529

because for object bricks, the `$fd->isEmpty($value)` returns `false` since the getter (`getMisc` in the example) returns an object. 
The check in the parent class simply does a php [empty()](https://github.com/pimcore/pimcore/blob/aa0ed48fd97757fc0b30bd2985eef2a237b373c6/models/DataObject/ClassDefinition/Data.php#L1206)


So to fix, need to add the method isEmpty in the derived class (and probably for each type of more structured data components) in
[pimcore\models\DataObject\ClassDefinition\Data\Objectbricks.php](https://github.com/pimcore/pimcore/blob/10.x/models/DataObject/ClassDefinition/Data/Objectbricks.php)
or probably something like this could do the trick:
``` 
if ($this->getClass()->getAllowInherit() && $fd->supportsInheritance() &&
   ($fd->isEmpty($value) || is_object($value))
 ) {
```
