### ISSUE TITLE
[Bug]: calling getConditionVariables resets condition variables

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#11535]
### Expected behavior

On any `AbstractListing`, calling `setConditionVariables` will have the DAO use the set condition variables. So the implementation should be the same as for `getConditionVariableTypes`:

https://github.com/pimcore/pimcore/blob/b26d41f4f7dfd7a6b606b30495bab56ffc305d7c/lib/Model/Listing/AbstractListing.php#L96-L103

### Actual behavior

When calling `setConditionVariables`, the set condition variables are not used in the SQL query, due to the DAO calling `getConditionVariables`. This call will overwrite all condition variables based on the logic implemented in `getCondition`:

https://github.com/pimcore/pimcore/blob/b26d41f4f7dfd7a6b606b30495bab56ffc305d7c/lib/Model/Listing/AbstractListing.php#L472-L477

### Steps to reproduce

1. Create a class
2. Use the classes listing to call `setConditionVariables(['test-value'])`
3. Call `$list->load()` (use xdebug to check the condition variables for this test case)

**Comment by passioneight** [comment]
Somewhat related to https://github.com/pimcore/pimcore/issues/11212

**Comment by dvesh3** [comment]
Fixed by #11536
