### ISSUE TITLE
[Bug]: Model overwrite causes issue on deployment

### ISSUE THREAD

**Issue by jensschaerer** [pimcore/pimcore#11553]
### Expected behavior

Deployment via Gitlab / Building a Docker container should result in a working image

### Actual behavior

Inheritance of Models fails because model classes are not generated while cache clear is already called

### Steps to reproduce

There is an old ticket relating this issue from Pimcore 5 (see https://github.com/pimcore/pimcore/issues/2543). When using Git and ignoring files in var/classes/DataObject (as recommended) and you overwrite your models using the official Symfony way (and the claimed way by Pimcore, see https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Overriding_Models.html), you ran into problems, when deploying using a Pipeline. During building the image or during deployment, composer install is executed and after that, cache clear is called - before the classes-rebuild of the deployment process is triggered. The extended model class isn't found (because it is not generated at this stage) and it keeps running into an error.

Any suggestions on this? I don't think this is intended behaviour and we have to fix our deployment pipeline somehow.

**Comment by dpfaffenbauer** [comment]
I do deployments to Kubernetes and building the image inside gitlab. It works fine for me, something you do might be wrong. How do you extend the classes? Do you use the classmap thing?

**Comment by jensschaerer** [comment]
@dpfaffenbauer I just use the way described at https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Overriding_Models.html for extending models, nothing special here. Deployment is basically building a standard docker container:

```
FROM pimcore/pimcore:PHP8.0-apache-buster

WORKDIR /var/www/html

COPY entrypoint.sh /usr/local/bin/docker-php-entrypoint
RUN chmod +x /usr/local/bin/docker-php-entrypoint

ADD --chown=www-data:www-data ./pimcore ./

# we switch user to perform some run tasks as www-data
USER www-data

ARG BUILD_ENVIRONMENT=prod
ENV APP_ENV=${BUILD_ENVIRONMENT}

RUN chmod +x bin/console
RUN composer run post-install-cmd
```

**Comment by dpfaffenbauer** [comment]
Don't use `class_overrides`. I am saying that for years now. That is magic and can cause unknown side-effects. You now experiencing them. Better to use parent-class in DataObject Classes instead.

**Comment by mattamon** [comment]
@dpfaffenbauer could you provide an example of the parent-class? How do I get custom logic in my pimcore dataobject without overriding it?

**Comment by dpfaffenbauer** [comment]
@mattamon 
![Screenshot 2022-08-04 at 12 48 42](https://user-images.githubusercontent.com/5981845/182829221-a347f87b-c431-4904-9076-f430290d64a3.png)

**Comment by mattamon** [comment]
@dpfaffenbauer Ahhhh! Okay thanks! Gonna try that.

**Comment by fashxp** [comment]
What about removing cache:clear from your projects composer.json and make sure you execute it manually afterwards? 
See also https://github.com/pimcore/skeleton/blob/11.x/composer.json#L49C9-L50
