### ISSUE TITLE
[Bug]: Inheritance layout - can't differ between editable and not editable fields

### ISSUE THREAD

**Issue by ctippler** [pimcore/pimcore#11562]
### Expected behavior

It would be nice if the enduser can differ between editable and not editable fields when inheritance is enabled.

### Actual behavior

If inheritance is enabled on a class the enduser cannot differ between editable and not editable fields.

Lets assume this example 
![image](https://user-images.githubusercontent.com/8791970/156302721-6c905c8f-d8a3-45ed-8296-07bbbaad87b1.png)

The first marked field is editable - the second is not not editable. 

Maybe it should be displayed with a "lock" icon if the field ist not editable?
![image](https://user-images.githubusercontent.com/8791970/156303263-40b8a1c0-2570-43fc-9033-b8ba1b1fcd1e.png)

### Steps to reproduce

Create a klass. Enable inheritance. Make one field not editable. Check the view on the of the last objekt in the tree.

**Comment by brusch** [comment]
Lock icon (monochrome similar and same size to `i` icon) would be fine for me.

**Comment by ctippler** [comment]
Hi,
pull request is created. 
It looks like this:
![image](https://user-images.githubusercontent.com/8791970/156410191-c118bdfe-0d3f-42bb-b4e3-6704aa10fe2a.png)
