### ISSUE TITLE
[Bug]: Cannot configure VoucherSeries with VoucherTokenTypePattern

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#11578]
### Expected behavior

Configuration of VoucherTokenTypePattern does not result in JS error

### Actual behavior

JS Error when adding FieldCollection VoucherTokenTypePatter to any VoucherSeries object.

### Steps to reproduce

1.
![image](https://user-images.githubusercontent.com/9052094/156524703-2504c5e0-b142-4184-9d48-8a92748fe656.png)

2.
![image](https://user-images.githubusercontent.com/9052094/156524532-59722ce5-7873-43d3-a8d2-ebc86773e8fd.png)

**Comment by dvesh3** [comment]
Related to https://github.com/pimcore/pimcore/issues/11280

**Comment by dvesh3** [comment]
Fixed by #11586
