### ISSUE TITLE
[Bug]: OnlineshopVoucherSeries displays empty alert in Voucher Details tab

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#11579]
### Expected behavior

No alert is displayed, if no error occurs. If an alert is displayed, it must have a textual content.

### Actual behavior

Empty altert is shown for some seconds after opening "Voucher Details" Tab in OnlineshopVoucherSeries object.

![image](https://user-images.githubusercontent.com/9052094/156534436-9fd67f59-bd3f-43f8-94e5-06aa03541be5.png)

### Steps to reproduce

1. Create OnlineShopVoucherSeries
2. Add any Token Config 
3. Open Voucher Details tab
4. Red empty alert box is shown

**Comment by dvesh3** [comment]
Fixed by #11582
