### ISSUE TITLE
[Improvement]: mail settings error message

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#11588]
### Improvement description

The error message in the following line seems a bit outdated:

https://github.com/pimcore/pimcore/blob/aa0ed48fd97757fc0b30bd2985eef2a237b373c6/lib/Mail/Plugins/RedirectingPlugin.php#L80

Should be something like: `Please update your system settings for 'pimcore.email.debug.email_addresses'`.

**Comment by passioneight** [comment]
@dvesh3 seems like we can close this, right?

**Comment by dvesh3** [comment]
@passioneight done. thanks!
