### ISSUE TITLE
[Improvement]: Consent service shouldn't save object

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#11584]
### Improvement description

Currently, when using the consent service provided by Pimcore, the passed object is automatically saved when giving or revoking a consent:

https://github.com/pimcore/pimcore/blob/aa0ed48fd97757fc0b30bd2985eef2a237b373c6/lib/DataObject/Consent/Service.php#L97

https://github.com/pimcore/pimcore/blob/aa0ed48fd97757fc0b30bd2985eef2a237b373c6/lib/DataObject/Consent/Service.php#L122

Saving the object is quite a heavy task, which should be done explicitly.

---

For example, a registration workflow for users of a website would roughly look like this:

```php
$registrationForm = $this
    ->createForm(RegistrationForm::class, new User(), $options)
    ->handleRequest($request);

if ($registrationForm->isSubmitted()) {
    if ($registrationForm->isValid()) {
        /** @var User $user */
        $user = $registrationForm->getData();
        $user->save(['versionNote' => 'User registered']);

        $consentService->giveConsent(...);

        // Omitted: send confirmation mail
    }
}
```

Now, since the object needs to be saved before giving consent, we already have 1 save-call. Then, _for each consent_ we'll have to call `$consentService->giveConsent(...);`, which will save the object _every time_. Say, TAC and GDPR consent need to be separate fields - we'd already have 3 save-calls.

Instead, the consent service shouldn't save the object, so that an explicit call to `$user->save(['verisionNote' => 'Consents given'])` is necessary after the consents were given. This will improve performance for the registration _and_ increase readability.

### Further thoughts
It would be even better to re-think how the `Consent` type is implemented. I.e., allow to give consent without having to save the object beforehand. This would allow us to fully leverage [`DataMapper`s](https://symfony.com/doc/current/form/data_mappers.html). This, in turn, allows us to simply save the object since the consents would correctly be set on the user object already:
```php
$registrationForm = $this
    ->createForm(RegistrationForm::class, new User(), $options)
    ->handleRequest($request);

if ($registrationForm->isSubmitted()) {
    if ($registrationForm->isValid()) {
        /** @var User $user */
        $user = $registrationForm->getData();
        $user->save(['versionNote' => 'User registered']); // Consents already set due to DataMapper

        // Omitted: send confirmation mail
    }
}
```
What's tricky here, though, is the `Note` that still needs to be saved somehow.

> Note that `DataMapper`s can already be used to map the consents, but it would only help pre-filling the form when rendering it, not the other way around - since we'd have to save the object, which we don't want when mapping data.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
