### ISSUE TITLE
[Improvement]: throw DuplicateFullPathException instead of Exception

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#11589]
### Improvement description

Ever so often, one needs to handle a duplicate full path situation gracefully. For example, when a user registers with the same email twice (with the email being used as the object's key).

Pimcore only triggers an `Exception`, which is just too generic:

https://github.com/pimcore/pimcore/blob/aa0ed48fd97757fc0b30bd2985eef2a237b373c6/models/DataObject/AbstractObject.php#L857

It would be nice to have an explicit exception, such as `DuplicateFullPathException` to catch. Otherwise, one has to check beforehand if the user already exists or check if the error message contains `Duplicate full path`.

Where the former is prone to error because some values might not be set at the time of checking the path - especially when using event subscribers. The latter, though, is also prone to error, because the exception might be caused by the application trying to create another already existing object (e.g., an `Address`).

Ultimately, the final application code should look something like this:

```php
try {
    $user->save(['versionNote' => 'User registered']);
} catch (DuplicateFullPathException $e) {
    $emailService->sendAlreadyRegisteredEmail($user);
    return $this->redirectToRoute('app_foo_bar');
}
```

**Comment by passioneight** [comment]
Also, the `DuplicateFullPathException` should be thrown for all types of elements (i.e., documents and assets as well as data objects).

**Comment by brusch** [comment]
👍agree, can you provide a PR for that?

**Comment by passioneight** [comment]
I'll see what I can do, but seems like I won't get to it any time soon.
