### ISSUE TITLE
Relation object without lazy loading aren't refresh in the cache if modified

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1158]
We got this problem updating from v3 to last v4.

In backend:
- Create two object: object A and object B.
- Create a multiobject relation field in object A, so we can link on it some B objects. **Do not check "lazy loading" option**.
- Create a wysiwyg field in B object.
- Create some instances (instA linked to instB).

In frontend (website):

- Display the wysiwyg of instB by loading instA (so using this way: `instA->getObjectB()->getWysiwyg()`)

The bug:
If instA is loaded a first time or fresh cache all is ok.
But after we change just some words in the wysiwyg of instB object, the old datas of instB are used. Cache need to be flush manually or we need to manually save instA (even if we change nothing on it) to clear the cache and display new words of instB wysiwyg.

In v3 and maybe some v4, there was not this problem, even without lazy loading the cache was automatically clearing the sub-object cache when we update those sub-object.

This problem occurs only when lazy loading is not checked.

I hope i manage to explain the problem. If you need more information I will be happy to give somes.

Thnaks a lot.

**Comment by maff** [comment]
Thanks for reporting. As we needed to switch the way cache-items are serialized (see #1005) the parent object cache item didn't contain child object tags anymore and its cache was never cleared on a child update.

@Yivan Could you check if the change above fixes the issue?

**Comment by markus-moser** [comment]
Great, for me it works now. It's necessary to clear once the total cache - afterwards it will work as expected with this patch!

**Comment by Yivan** [comment]
Thanks maff!
All is ok now.
