### ISSUE TITLE
Web2Print: call to undefined method getLatestVersion()

### ISSUE THREAD

**Issue by RobinBrackez** [pimcore/pimcore#1161]
Bug happens in the following scenario:

1) enable Web2Print
2) create a folder inside the Documents tree
3) create a PrintPage inside that folder, click "save and publish"
4) create a PrintContainer inside the same folder, click "save and publish"
5) now drag and drop the PrintPage inside the PrintContainer
6) open the PrintPage and click the Refresh button inside the Edit tab
7) you get the error:   call to undefined method getLatestVersion()

It requests the wrong path. It still thinks the PrintPage is inside the Folder instead of being in the PrintContainer, so it tries to load the getLatestVersion() of the Print but instead it gets the Folder object.

If you reload the PrintPage, it works, but as long as you haven't done that it wont work.

**Example error page:**
![template error](https://cloud.githubusercontent.com/assets/7022901/21547657/ccb76280-cde7-11e6-9926-53bff67347c8.JPG)

**A possible scenario:** 
![selection_225](https://cloud.githubusercontent.com/assets/7022901/21547658/ccba9018-cde7-11e6-8460-90f81773a506.png)

**You can see that the path is incorrect:**
![selection_224](https://cloud.githubusercontent.com/assets/7022901/21547659/ccbd0690-cde7-11e6-8b45-6cb795b44174.png)

**This is the line that causes the error. Method getDocument() returns the wrong object.**
![selection_223](https://cloud.githubusercontent.com/assets/7022901/21547660/ccbf486a-cde7-11e6-90e1-96fa9cabdd4e.png)

**Comment by fashxp** [comment]
can you reproduce this at http://ecommercedemo.pimcore.org/admin - I couldn't.

**Comment by RobinBrackez** [comment]
Yes I can, I made a screen recording to illustrate it, it's in the zipfile:

[pim_printpage_error.mp4.zip](https://github.com/pimcore/pimcore/files/684340/pim_printpage_error.mp4.zip)

Error: 
Fatal error: Uncaught exception 'Zend_Controller_Router_Exception' with message 'No route, document, custom route or redirect is matching the request: /print/new-printpage?extjs6=1&pimcore_editmode=true&systemLocale=en&_dc=1483524193681 | Specific ERROR: No route matched the request' in /home/pimcore_ecommercedemo/www/pimcore/lib/Pimcore.php:263 Stack trace: #0 /home/pimcore_ecommercedemo/www/index.php(18): Pimcore::run() #1 {main} thrown in /home/pimcore_ecommercedemo/www/pimcore/lib/Pimcore.php on line 263

**Comment by fashxp** [comment]
ok, but this is a different exception then? 
says nothing about getLatestVersion(), does it?

**Comment by fashxp** [comment]
see also other issue I created, we'll discuss this internally. 

the question remains if your original exception is reproducible. otherwise we could close this issue.
