### ISSUE TITLE
[Bug]: abandoned dependency inflector 

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#11628]
### Expected behavior

No abandoned dependencies get required. 

### Actual behavior

`symfony/inflector` which is deprecated, is required

> Package symfony/inflector is abandoned, you should avoid using it. Use EnglishInflector from the String component instead.

### Steps to reproduce

Install Pimcore via composer, you will see the warning above.

Also see https://symfony.com/blog/new-in-symfony-5-1-deprecated-the-inflector-component#:~:text=Symfony%20Inflector%20component%20converts%20words,addFoo()%20).

**Comment by dvesh3** [comment]
Already done in https://github.com/pimcore/pimcore/pull/13097
