### ISSUE TITLE
[Feature]: ARM compatible Pimcore-apache Docker container

### ISSUE THREAD

**Issue by marlonbasten** [pimcore/pimcore#11634]
### Feature description

Hey there,

I am working on the new Apple processors since a few months and would really like to use the Pimcore provided docker setup.
But I can't use it since it's really slow because I have to emulate a x64 architecture.

Is there any way the docker container could be updated to support the M1 Macs or ARM in general?

All the best

**Comment by brusch** [comment]
https://github.com/pimcore/docker/pull/76

**Comment by jdreesen** [comment]
Note that there aren't any Apache containers anymore!

**Comment by marlonbasten** [comment]
@brusch Thanks for the info. But as far as I can see there aren't any arm docker images on docker hub yet?

**Comment by brusch** [comment]
@marlonbasten see, the PR is still not merged ... subscribe to it and you will get notified once it's ready and available on the hub.
