### ISSUE TITLE
[Bug]: Custom Editable js error

### ISSUE THREAD

**Issue by matthiashamacher** [pimcore/pimcore#11643]
### Expected behavior

When following the [documentation for adding custom editables](https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/Adding_Document_Editables.html), the editable should work.

### Actual behavior

After adding all files I'm getting the following error:
```
[Error] TypeError: undefined is not an object (evaluating 'Object.keys(source)')
	keys (class.js:58)
	addMethods (class.js:58)
	create (class.js:47)
	Global Code (info.js:2)
```
The problem seems to be that [during this function call](https://github.com/pimcore/pimcore/blob/10.x/bundles/AdminBundle/Resources/public/js/lib/class.js#L46) properties has two entries: 
1. undefined
2. the methods from the create file (info.js in my case)

### Steps to reproduce

Follow the Tutorial in the documentation: https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/Adding_Document_Editables.html

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
