### ISSUE TITLE
[Bug]: Video thumbnail generation failes in distributed environments

### ISSUE THREAD

**Issue by denniskorbginski** [pimcore/pimcore#11645]
### Expected behavior

The message queue consumer should be able to create a video thumbnail regardless of the container/vm that created the message originally.

### Actual behavior

The video processor [creates a local temporary copy](https://github.com/pimcore/pimcore/blob/10.x/models/Asset/Video/Thumbnail/Processor.php#L130) of the video before passing the processing job to the message queue. In cases where the queue consumer does not run in the very same environment, the processing job fails. This can be the case when you have a separate container running the consumer, or multiple VMs behind a load balancer. The consumer might not have access to the same temporary directory that was used in the original request, thus failing with a "file not found" error.

I would suggest to move the creation of the temporary local file to the processing of the queue message and not do that beforehand. What do you think?

### Steps to reproduce

To simulate this behavior, have the queue worker use a different `PIMCORE_SYSTEM_TEMP_DIRECTORY` then the pimcore instance.
Alternatively, you can create two separate containers, one for pimcore, one for the worker. Once you trigger video thumbnail generation in pimcore, the processing job in the worker will fail if the two containers do not share the same temporary directory.

**Comment by brusch** [comment]
@denniskorbginski yep, makes sense, can you create a PR for that? Thanks a lot!

**Comment by brusch** [comment]
Fixed by #11862
