### ISSUE TITLE
[Bug]: Date & Time "use current date" cannot be checked

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#11650]
### Expected behavior

Be able to check and use the _Use current date_ on Date & Time fields on Data Objects

### Actual behavior

The checkbox does not work.

### Steps to reproduce

Try clicking on the checkbox on the bottom right on demo.pimcore.fun.

![image](https://user-images.githubusercontent.com/279826/157862717-a95707b5-6156-426b-984c-207fa17278a1.png)

**Comment by mcop1** [comment]
Resolved by #11744
