### ISSUE TITLE
[Improvement]: Filters should be saved for table options too

### ISSUE THREAD

**Issue by danielerne** [pimcore/pimcore#11651]
### Improvement description

Currently we can save table options in dataobject folders.
But it should be possible to save the filters too. For example if someone wants to save a list of users which have newsletter enabled.

<img width="1306" alt="Bildschirmfoto 2022-03-11 um 14 42 57" src="https://user-images.githubusercontent.com/546931/157881609-6893dafd-a2fd-4995-ab1e-3a5dcd2e4fc2.png">

**Comment by passioneight** [comment]
I'd love to see this too. Also, would be great to be able to create deeplinks to these folders to pre-select the settings (both filter and options).

A `Custom Report` can be created as a workaround.

**Comment by SamyMP** [comment]
Any chance to have this feature in the next release or in Pimcore 11 ?

**Comment by brusch** [comment]
@SamyMP if you (or someone else) provides a PR for that, the chance is about 100% 😉

**Comment by SamyMP** [comment]
Currently trying to work on it as we speak, not sure if I'll be able to pull this off though 😅
I'll keep you updated
