### ISSUE TITLE
Notice error on localized field

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1166]
Saving an object using the API send a notice error on localized field if you set just one language (**field is not required**).
For instance having "fr", "en", "de" as available language, and creating a new object by setting just "en" value send the following error:

`Error: [Notice] Undefined index: fr in pimcore\models\Object\ClassDefinition\Data\Localizedfields.php on line 937`

Problem is caused by:
https://github.com/pimcore/pimcore/blob/master/pimcore/models/Object/ClassDefinition/Data/Localizedfields.php#L937

This line:

`$fd->checkValidity($data[$language][$fd->getName()]);`

Should be replaced by:

`if (isset($data[$language])) $fd->checkValidity($data[$language][$fd->getName()]);`

Maybe the same problem can occur at other place, as it seems a recent change (whe didn't had this problem with Pimcore 3).

Thanks.

**Comment by weisswurstkanone** [comment]
Not sure ... wouldn't this completely skip a "mandatory" check?

**Comment by Yivan** [comment]
I understand, you mean for instance an input field with a regexp wanting not empty value...
I think maybe in those case, "Required" checkbox for the field should be checked.

Maybe we can just remove the error and leave as it act actually: passing a null value if not defined and notice error is not triggered.

The good replacement could be so:
```
if (isset($data[$language])) $fd->checkValidity($data[$language][$fd->getName()]);
else $fd->checkValidity(null);
```
It is wat does actually the code but it would not trigger a notice error (PHP silently replace not defined value by null if i am right).

**Comment by weisswurstkanone** [comment]
thx, makes sense. fixed in build 4024

**Comment by JulienHenchoz** [comment]
Hi, I'm having the same issue in pimcore/models/Object/ClassDefinition/Data/Localizedfields.php in resolveDependencies. 
The following line doesn't check if the array key exists : 
`$dependencies = array_merge($dependencies, $fd->resolveDependencies($values[$fd->getName()]));`

This leads to a failure if some of the translations are not set.
@weisswurstkanone  Is it worth opening a new case ? What do you think ?
