### ISSUE TITLE
[Bug]: Reindex of children doesn't work

### ISSUE THREAD

**Issue by MyZik** [pimcore/pimcore#11665]
### Expected behavior

If parent (Object or folder) has options "Sort children by" = Index and one of children was deleted, all other children should be resorted.

### Actual behavior

Reindex doesn't work.

I have a categories in my folder:
![Bildschirmfoto 2022-03-14 um 13 50 25](https://user-images.githubusercontent.com/12817320/158175510-53c2ab74-374e-4dc9-87f6-537f0ad0a4ce.png)

Database view:
![Bildschirmfoto 2022-03-14 um 13 47 01](https://user-images.githubusercontent.com/12817320/158175556-daf1cd6f-f767-4ccf-8369-b7afced29246.png)

If I delete an "Test2" object, the indexes still the same.

![Bildschirmfoto 2022-03-14 um 13 47 18](https://user-images.githubusercontent.com/12817320/158175569-1140467f-b7e0-4467-b623-d6d40b6f8817.png)

### Steps to reproduce

1. Create a folder (or an object).
2. Set "Sort children by" option to "Index (Manual)"
3. Add 2 or more objects to your folder / object.
4. Delete an object.

**Comment by dvesh3** [comment]
@MyZik this option is manual indexing, which means user is responsible for changing the indexes. Also it doesn't change when adding new objects. 

Is this really an issue? as you will still the objects in specified order in tree.
