### ISSUE TITLE
[Improvement]: do not alter value in select

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#11671]
### Improvement description

Would be nice to be able to use _any_ `Display Name` - i.e., plain text, HTML, ..., what have you. Currently, only specific HTML tags are allowed:

https://github.com/pimcore/pimcore/blob/848c8d1cf023dfe1a3fe95c6e5c3228c8934180f/bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/select.js#L129

Seems like this was added to support rendering in the grid view: https://github.com/pimcore/pimcore/commit/0605ae9e3d6a6200f020453f267a6b1fa664ddd3.

Should be possible to have any value independent of where the select is rendered.

**Comment by fashxp** [comment]
cannot be done due to security reasons ... XSS ...
