### ISSUE TITLE
[Improvement]: Web2print Chrome Renderer: change library to chrome-php/chrome

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#11673]
### Improvement description

Implementation for previews, see #10934

See also: https://github.com/pimcore/pimcore/pull/10934#issuecomment-1068085492

**Comment by dkarlovi** [comment]
This would be a good candidate to allow replacing. For example, if you're trying to deploy Pimcore in a lean environment like Docker, you probably don't want to bundle the entire Chrome in your image just for a few PDFs and images you generate here and there.

A better approach there would be to have the PDF generator available as a separate service which you're able to hook into Pimcore. The pre-requisite for this is for the screenshot / PDF generators to have an interface and the rest of the code to accept those interface and not specific implementations.

One example how this could work is https://github.com/xjodoin/htmlpdfconverter, it's basically "Chrome via HTTP". I could run this in my k8s cluster once and share it between many (Pimcore or other) applications, not deploy one copy into each Pimcore Docker image.

**Comment by brusch** [comment]
See #12607 
Maybe Gotenberg is the even better and generic solution ... needs to be considered ...
