### ISSUE TITLE
[Bug]: Name of control doesn´t reflect the order in the page

### ISSUE THREAD

**Issue by mcop1** [pimcore/pimcore#11685]
### Expected behavior

Name of control should reflect the order

### Actual behavior

Name of control doesn´t reflect the order in the page

### Steps to reproduce

See https://github.com/pimcore/data-hub/issues/493 for details/example

It can be reproduced without headless documents too

1.) Add new content page
2.) Add blockquote
3.) Add more blockquotes by using the "+" button on the first added blockquote
<img width="637" alt="image" src="https://user-images.githubusercontent.com/89011527/158606492-4bb44bcb-bc42-43d4-b275-67481a48cbee.png">

**Comment by fashxp** [comment]
is intended the way it is .... there is a key, which is part of the name, and there is the index which defines the order of the editables.
