### ISSUE TITLE
[Improvement]: PHP 8.1 deprecation messages

### ISSUE THREAD

**Issue by Ricardocanul7** [pimcore/pimcore#11687]
### Improvement description

When running tests in a project with PHP8.1 I receive a lot of deprecation messages from Pimcore code

a few of the messages are:

`Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated`
`Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated`
`Deprecated: strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated`
`Deprecated: array_slice(): Passing null to parameter #2 ($offset) of type int is deprecated`
`Deprecated: strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated`
`Deprecated: PDO::quote(): Passing null to parameter #1 ($string) of type string is deprecated`
`Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated`

**Comment by fashxp** [comment]
also check why phpstan is not catching that.

**Comment by blankse** [comment]
@fashxp Parameter types are checked by PhpStan in level 5. We are on level 4.
https://phpstan.org/user-guide/rule-levels

**Comment by fashxp** [comment]
also related: 
- https://github.com/pimcore/pimcore/pull/11792 
- https://github.com/pimcore/pimcore/pull/11785
- https://github.com/pimcore/pimcore/pull/11786
- https://github.com/pimcore/pimcore/pull/11787
- https://github.com/pimcore/pimcore/pull/11788
- https://github.com/pimcore/pimcore/pull/11789

**Comment by aryaantony92** [comment]
@Ricardocanul7  Could you please provide the logs regarding the deprecated error messages in PHP 8.1 ?

**Comment by aryaantony92** [comment]
Could you please provide the complete logs regarding the deprecation error messages in PHP 8.1 ?

**Comment by fashxp** [comment]
closed due to inactivity. please come back, if they still occur with more insights. thx.
