### ISSUE TITLE
[Bug]: multiple licence instance

### ISSUE THREAD

**Issue by jerem-eng** [pimcore/pimcore#11705]
### Expected behavior

Hello, i want to create portal with the portal engine 

### Actual behavior

in local environment i have one error cause my hostname doesn't exist -> i solve this when i fill the field in general settings -> website setting -> principal domain

i tried do to the same with production environment  but my licence crying cause there are multiple production instances.

i think this is set in BDD but i don't know where. how i can remove this production instance ?  

### Steps to reproduce

set principal hostname in settings with one licence

**Comment by fashxp** [comment]
please contact your contact directly at pimcore or reach out via email to enterprise-support[at]pimcore.com

**Comment by jerem-eng** [comment]
thanks for the email
