### ISSUE TITLE
[Bug]: Pricing Rules are not correctly migrated from 6.x to 10.x

### ISSUE THREAD

**Issue by mysliwietzflorian** [pimcore/pimcore#11700]
### Expected behavior

Serialized conditions in the table `ecommerceframework_pricing_rule` should be migrated in some way. E.g.: The namespace like `AppBundle` should be transformed to `App` along with the "size" encoding from the `serialize()` method.

Possibly via Migration or Export/Import process.

### Actual behavior

We could have overlooked or missed something but conditions in the table `ecommerceframework_pricing_rule` were not properly formatted to unserialize anymore.

Our quick and dirty solution was to update those entries with a simple command. Needs to be adjusted for own needs but might help someone in the future: https://gist.github.com/mysliwietzflorian/676b8de2e7c953593a2bf4e130e1e4af

One more aspect concerning serialized objects in the database: please try to avoid them in the future. See https://www.php.net/manual/de/function.serialize.php#107717

### Steps to reproduce

not reproducible again but:

- Pimcore 6.x
- Price rules with conditions as serialized objects in the table `ecommerceframework_pricing_rule`
- Update to PCX
- Pricing rule conditions in the Pimcore Backend are not visualized anymore. Serialized conditions in the table are corrupted.

**Comment by dvesh3** [comment]
@mysliwietzflorian please share a case where it is possible to have `AppBundle` in the condition of a PricingRule. thanks!

**Comment by mysliwietzflorian** [comment]
@dvesh3 Actually good question:

I could only reproduce it in Pimcore 6.6.2 and on our instance of PCX. In the demo project the condition column in the table `ecommerceframework_pricing_rule` was not filled. Maybe a different Configuration Storage?

The gist is to use some config with object in the App namespace. I used the Voucher class.

![image](https://user-images.githubusercontent.com/23225429/159238863-f683bc59-eaa8-42a6-b095-43d867cf4a24.png)

The serialized object in the table would be the following (6.6.2):

```bash
O:72:"Pimcore\Bundle\EcommerceFrameworkBundle\PricingManager\Condition\Bracket":2:{s:13:" *
conditions";a:1:{i:0;O:57:"AppBundle\Ecommerce\PricingManager\Condition\VoucherToken":6:{s:19:" *
validityInterval";O:21:"Carbon\CarbonInterval":28:{s:9:" * tzName";N;s:7:" * step";N;s:22:" *
localMonthsOverflow";N;s:21:" * localYearsOverflow";N;s:25:" * localStrictModeEnabled";N;s:24:" *
localHumanDiffOptions";N;s:22:" * localToStringFormat";N;s:18:" * localSerializer";N;s:14:" * localMacros";N;s:21:" *
localGenericMacros";N;s:22:" * localFormatFunction";N;s:18:" *
localTranslator";N;s:1:"y";i:0;s:1:"m";i:0;s:1:"d";i:120;s:1:"h";i:0;s:1:"i";i:0;s:1:"s";i:0;s:1:"f";d:0;s:7:"weekday";i:0;s:16:"weekday_behavior";i:0;s:17:"first_last_day_of";i:0;s:6:"invert";i:0;s:4:"days";b:0;s:12:"special_type";i:0;s:14:"special_amount";i:0;s:21:"have_weekday_relative";i:0;s:21:"have_special_relative";i:0;}s:17:"
* isPersonalized";b:0;s:22:" * failedVoucherTokens";a:0:{}s:15:" * whiteListIds";a:1:{i:0;i:6406022;}s:12:" *
whiteList";a:1:{i:0;O:8:"stdClass":3:{s:2:"id";i:6406022;s:4:"path";s:40:"/Ecommerce/Voucher/de_newsletter_abo_10p";s:4:"type";s:23:"OnlineShopVoucherSeries";}}s:16:"
* errorMessages";a:5:{s:2:"de";s:4:"test";s:2:"en";s:0:"";s:2:"fr";s:0:"";s:2:"nl";s:0:"";s:5:"de_AT";s:0:"";}}}s:11:"
* operator";a:1:{i:0;s:3:"and";}}
```

In PCX we changed the namespace to the correct `App\...` prefix.

A further question: what happens with the condition, e.g., on the Pimcore Demo?

**Comment by dvesh3** [comment]
@mysliwietzflorian seems like you are using class override for VoucherToken. I would suggest to create a class alias like explained here https://github.com/pimcore/pimcore/issues/10661#issuecomment-979886344

**Comment by mysliwietzflorian** [comment]
@dvesh3 actually a good quick idea. We could fix it ourselves with the command listed above but this could be relevant for future devs. 😉 

But still, as VoucherTokens are quite frequently overwritten there should be some kind of migration (or at least a hint for serialized objects in the DB) in place.
