### ISSUE TITLE
[Bug]: bulk Moving Tree Entrys results in a lot of Errors

### ISSUE THREAD

**Issue by cutec-chris** [pimcore/pimcore#11708]
### Expected behavior

no Errors when moving Tree Items 

### Actual behavior

when moving at least 5 Tree Items Pimcore often this error occours:

An exception occurred while executing 'UPDATE objects o,
                    (
                        SELECT newIndex, o_id FROM (SELECT @n := IF(@n = ? - 1,@n + 2,@n + 1) AS newIndex, o_id
                        FROM objects,
                        (SELECT @n := -1) variable
                        WHERE o_id != ? AND o_parentId = ? AND o_type IN ('object','variant','folder')
                            ORDER BY o_index, o_id=?
                        ) tmp
                    ) order_table
                    SET o.o_index = order_table.newIndex
                    WHERE o.o_id=order_table.o_id' with params [30, 5775, 4226, 5775]:

SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction

after that the interface reacts unreliable

### Steps to reproduce

Move 20-50 Data Objects from one Tree folder to another

**Comment by fashxp** [comment]
can you share some steps to reproduce this on our public demo?

**Comment by cutec-chris** [comment]
unfortunally not, ive tried with several data items in the demo but there those issue seems not to occour. 
but i also have no clue what should be different on our setup. 

i would like to show it to you per teams call or simelar would that be possible ?

**Comment by brusch** [comment]
Unfortunately we can't do a Teams session. Please try to create a reproducible scenario that can be shared here, or even better debug and try to implement a pull request fixing the issue. 
I'll close this issue here for now, if there are any new findings I'm happy to re-open the issue. 
Thanks!
