### ISSUE TITLE
[Improvement]: Allow change of sort method of data object children based on a user role

### ISSUE THREAD

**Issue by andi-schlosser** [pimcore/pimcore#11716]
### Improvement description

Since Pimcore 6.9 only admin users are allowed to change the sort method (key or index) of children of data objects.
Is there a specific reason why?
And would it be possible to change this behaviour so users with a specific role are able to change the sort method?

That's the old pull request which introduced the changes vor Pimcore 6.9: https://github.com/pimcore/pimcore/pull/9307

If you accept the change from admin user only to a specific user role, i would be able to work on a new pull request for this improvement.

**Comment by fashxp** [comment]
We would love to see a PR for that 👍

**Comment by andi-schlosser** [comment]
Perfect! 
I will work on that end of this week or next week.
