### ISSUE TITLE
[Bug]: Sorting is disabled in  Advanced Many to many object Relation 

### ISSUE THREAD

**Issue by vaishali-hm** [pimcore/pimcore#11719]
### Expected behavior

if the attribute is editable then sorting should be editable as in the previous version of pimcore

### Actual behavior

![Screenshot from 2022-03-21 17-51-44](https://user-images.githubusercontent.com/96772636/159260300-a938499e-904f-45fd-a16e-419b322e08d7.png)

### Steps to reproduce

1) Go to https://demo.pimcore.fun/admin/?perspective=default website
2) open ID 1018 in the Customer class
3) check Manual Segments attribute , I unable to sort ids

**Comment by fashxp** [comment]
this is actually on purpose, because the order of the related elements is also stored.

**Comment by cancan101** [comment]
It would be great if sorting of table was enabled for:
1. Reverse relationships (order is not defined on that reverse side)
2. Non editable (Advanced) Many to many Relations
