### ISSUE TITLE
Custom order of DataObjects in Pimcore

### ISSUE THREAD

**Issue by stefanos87** [pimcore/pimcore#11720]
This feature is convenient because with drag and drop I can change the sorting manually, the problem is that when I have many objects, these are paginated, how can I move for example an object from the last page to the first?

![image](https://user-images.githubusercontent.com/21968830/159271117-67492fc4-6524-4275-a579-85b92a13e779.png)

Thank you

_Originally posted by @stefanos87 in https://github.com/pimcore/pimcore/discussions/9435#discussioncomment-2406909_

**Comment by kingjia90** [comment]
I think it cannot be done directly by drag and drop. 
At the moment, one possible solution would be dragging the item temporary somewhere outside, then change the to page 1 and drag it back in the desired position.
The cut/paste function seems not considering the custom order, probably could be improved to paste in the current pagination index.

**Comment by dkarlovi** [comment]
One possible solution would be to add some feature to the context menu which allows setting `o_index`, maybe directly or indirectly ("Move to Front", "Move to Back").

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
