### ISSUE TITLE
[Bug]: table datatype does not register change when data pasted from clipboard

### ISSUE THREAD

**Issue by xonu** [pimcore/pimcore#11729]
### Expected behavior

Paste data from the clipboard into the table, save object. Update object and find that the pasted data has been saved.

### Actual behavior

Pimcore does not register the change of object data when data has been pasted from the clipboard. Note that there is no asterisk after inserting the data, which shows that the change to the object has not been registered before saving. If the object is now saved by clicking on "Save" or "Save and Publish", the inserted data is not saved. You have to reload the object to see the data disappear.
![insert-data-into-table](https://user-images.githubusercontent.com/5429616/159465602-d61aa236-fec6-4785-90bb-dfd9defe4d98.png)
Pimcore version: 10.3.2

### Steps to reproduce

1. create class with attribute of type table
2. create an object and insert data from clipboard
3. save object
4. reload object
5. inserted data has not been saved

**Comment by FrederikHulleman** [comment]
@brusch both https://github.com/pimcore/pimcore/issues/11795 and https://github.com/pimcore/pimcore/issues/11729 are closed. Is there another issue where this is addressed?

**Comment by dvesh3** [comment]
@FrederikHulleman #11795 was closed in favor of #11729, which is the current open issue.

**Comment by niederberger-qw** [comment]
Please consider this issue with priority. The function to paste data is for some customers an important one. Is there a hotfix or something? We need that for example to paste curve data into a form. X Y coordinates. Not working at the moment...

**Comment by brusch** [comment]
@niederberger-qw PRs are welcome 😉

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
