### ISSUE TITLE
[Feature]: cascading fallback languages

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#11740]
### Feature description

**Suggestion**:

Fallback languages should work in a cascading manner. 

So that if locale `nl `is configured as the fallback for `nl_BE` and `en` is configured as fallback for `nl`, that if there is no value in `nl_BE `it will look in `nl `and then also falling back to `en`. 

Currently only the first defined level of fallback language applies.

**Comment by fashxp** [comment]
This is actually on purpose to prevent unwanted endless loops. 
You can define multiple fallback languages for one language though.
