### ISSUE TITLE
[Bug]: Tag filter in search does not work

### ISSUE THREAD

**Issue by danielerne** [pimcore/pimcore#11748]
### Expected behavior

Objects can be filtered by Tags

### Actual behavior

No items found

### Steps to reproduce

Open Pimcore Demo
Open a car and assign a tag like Country "Germany"
Go to a news object and click Search for selecting a Car
Open Tag filter and choose Germany
- No Items

<img width="1622" alt="Bildschirmfoto 2022-03-23 um 16 47 24" src="https://user-images.githubusercontent.com/546931/159739820-cabb3a66-8e0c-4377-a422-ea2d28fca239.png">

**Comment by fashxp** [comment]
works for me ... are you testing on demo.pimcore.com or on demo.pimcore.fun?

**Comment by danielerne** [comment]
On demo.pimcore.com
Assets are working but for objects it is not working

**Comment by danielerne** [comment]
<img width="884" alt="Bildschirmfoto 2022-03-23 um 17 09 26" src="https://user-images.githubusercontent.com/546931/159744683-4374019d-0e9f-43c9-bdc7-c287723962cd.png">

**Comment by danielerne** [comment]
@fashxp Any news on this?

**Comment by fashxp** [comment]
verified, doesn't work as soon as a data object class is selected in search dialog

**Comment by mcop1** [comment]
Resolved by #11939
