### ISSUE TITLE
[Bug]: Localized CalculatedValue field is not aware of its position in Field-Collection

### ISSUE THREAD

**Issue by kaurov** [pimcore/pimcore#11759]
### Expected behavior

public function compute(Concrete $object, CalculatedValue $context): string

Localized fields will get current position in Fileds-Collection in $context->getIndex() as well es untranslated fields do.

### Actual behavior

The untranslated field can access current Fileds-Collection item by calling
```
 $fieldCollectionItem = $object->getAttributes()
                                          ->get($context->getIndex());
```
but there is no such ability if the filed to locate the same field inside  LocalizedField

### Steps to reproduce

- Create a Fields-Collection with 2 fileds: 
  - type: string, name 'AttributeOverwrite', parent: LocalizedField 
  - type: calculatedValue, name 'Attribute'
- Set a class AttributeSetAttributeCaptionCalculator as 'class' parameter of calculated value 

put the content to class:
```
class AttributeSetAttributeCaptionCalculator implements CalculatorClassInterface
{
    public function compute(Concrete $object, CalculatedValue $context): string
    {
        try {
            /* @var AttributesSet $object */
            if (!$object instanceof AttributesSet) {
                throw new \Exception('It should be used in AttributesSet object only');
            }
            if (!$object) {
                return '';
            }
            /* @var AttributeSetTable $fieldCollectionItem */
            $fieldCollectionItem = $object->getAttributes()
                                          ->get($context->getIndex());
            $language = $context->getPosition();
            $overwrite = (string)$fieldCollectionItem->getAttributeOverwrite($language);
            if ($overwrite) {
                return $overwrite;
            }
            return 'default value';
     }
}
```

> after saving and reloading, the calculated field will have the value from $currentFiledsCollectionItem->getAttributeOverwrite() ?: 'default value'
> 
> if to put calculatedValue filed 'Attribute' inside LocalizedField, there is no chance to get currentFiledsCollectionItem since $context has empty $_owner and empty getIndex().

**Comment by brusch** [comment]
Fixed by #11816
