### ISSUE TITLE
[Bug]: In the Classification store view the X button deletes without warning

### ISSUE THREAD

**Issue by niederberger-qw** [pimcore/pimcore#11754]
### Expected behavior

We need a message "are you sure to delete the group with all values? After the next save the values from that group will be empty".

### Actual behavior

Deletes the whole data without a warning. (Missclick is a problem here)

### Steps to reproduce

Click on the X after you added a group and then save.

**Comment by dkarlovi** [comment]
Maybe having a dedicated UX label for this? There's other things in admin exactly like this, adding a dedicated label would make it easier to find them and fix in bulk.

**Comment by dkarlovi** [comment]
Maybe having a dedicated UX label for this? There's other things in admin exactly like this, adding a dedicated label would make it easier to find them and fix in bulk.
