### ISSUE TITLE
[Bug]: DEV MODE enabled despite being disabled in .env file

### ISSUE THREAD

**Issue by tebulrich** [pimcore/pimcore#11768]
### Expected behavior

DEV MODE should be disabled and not show up under the notifications when 

APP_ENV=prod
APP_DEBUG=0
PIMCORE_DEV_MODE=false

### Actual behavior

DEV MODE shows up under the notifications button

### Steps to reproduce

As seen above with version 10.3.3. All caches cleared multiple times + also manually removed files in var/cache. Its a fresh install with no other data than the admin user. The server runs the latest Apache2 with PHP 8.1.3 and the latest MySQL

**Comment by brusch** [comment]
Seems that the settings actually work, but it's wrongly reported in the UI 🙃

**Comment by brusch** [comment]
The issue is that `false` is not yet considered, you'd have to use `0` instead.

**Comment by brusch** [comment]
Fixed by #11776
