### ISSUE TITLE
[Bug]: Split view settings affect other user accounts

### ISSUE THREAD

**Issue by xonu** [pimcore/pimcore#11764]
### Expected behavior

Split view settings are saved for every **user** individually.

### Actual behavior

Split view settings are saved for every **browser** individually. Are cookies used without a connection to the current user session?

### Steps to reproduce

![split-view-settings](https://user-images.githubusercontent.com/5429616/160189223-90db2c7d-b008-4b59-bf9f-380ea369b9a7.png)

To reproduce, you need two user accounts with access on an object with split view enabled.
Let these users be **dietz** and **bernie**.
Here are the steps to reproduce:

1. login to Pimcore as **dietz**
2. open an object with split view enabled
3. change the setting, e. g. German on the left, English on the right
4. logout from Pimcore
5. login to Pimcore as **bernie** in the same browser on the same computer (without changing the windows user)
6. open an object with split view enabled: bernie has now German on the left, English on the right, although he has not configured it that way!
7. bernie may now add French and Spanish to the right side to suprize or annoy dietz by changing his split view configuration.

PS: And yes, sometimes people do use the same computer because ...sharing is caring.

**Comment by dvesh3** [comment]
Fixed by #11853
