### ISSUE TITLE
[Bug]: pimcore.bundle_pimcore_direct_edit_asset_token' doesn't exist

### ISSUE THREAD

**Issue by yamenalahlas** [pimcore/pimcore#11766]
### Expected behavior

**Direct-edit**
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pimcore.bundle_pimcore_direct_edit_asset_token' doesn't exist

### Actual behavior

After installation and configuration for direct-edit and mercure. 
When I click Open to edit locally I get the error
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pimcore.bundle_pimcore_direct_edit_asset_token' doesn't exist

### Steps to reproduce

in the console:
bin/console pimcore:direct-edit:cleanup --hours=1

or in the Admin-ui click  "open to edit locally"

**Comment by brusch** [comment]
As this is about an enterprise bundle this is not the right place, please talk to your contact directly at pimcore or reach out via email to enterprise-support[at]pimcore.com

Thanks
