### ISSUE TITLE
[Bug]: Pimcore 10 pagination issue on dashboard custom reports 

### ISSUE THREAD

**Issue by veenus93** [pimcore/pimcore#11779]
### Expected behavior

First page and previous page of the custom reports pagination should be visible when user open the dashboard after the load of the application 
![expected](https://user-images.githubusercontent.com/34839656/160413245-64778511-14be-4eae-9762-c1f171f3b147.png)

### Actual behavior

When clicked on last page of the custom report pagination , First page and previous page at the bottom of the custom reports on the dashboard are not visible only for the first time after the hard referesh of the application .
![error2](https://user-images.githubusercontent.com/34839656/160412186-87754a1d-b78d-4b61-80c5-3057445fd21a.png)

### Steps to reproduce

1) Click on file menu on left panel 
2) Click on dashboards 
3) Click on welcome 
4) Click on last Page of the custom report.
![dashboard-custom-report-1](https://user-images.githubusercontent.com/34839656/160411029-69d4ab2f-c30e-4d44-ae50-fba05ee7837e.png)

**Comment by jeremygnoonan** [comment]
Note on replication, the window size needs to be narrower than 1080p.

**Comment by torqdev** [comment]
@veenus93 A PR has been merged, has this fixed your issue? Thanks

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
