### ISSUE TITLE
[Bug]: Pimcore\Bundle\CoreBundle\EventListener\ResponseExceptionListener::determineErrorPath(): Return value must be of type string, null returned

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#11797]
### Expected behavior

Correct type returned.

### Actual behavior

Null returned.

### Steps to reproduce

/vendor/pimcore/pimcore/bundles/CoreBundle/EventListener/ResponseExceptionListener.php in Pimcore\Bundle\CoreBundle\EventListener\ResponseExceptionListener::determineErrorPath at line 216

Looking at the code, `$defaultErrorDocumentPath` is expected to always be string, but it can be null.

Since there's *a lot* of these types of issues, improving the static analysis should be of higher priority IMO. It will catch many of these so we don't need to individually find / report / fix them one by one.

**Comment by dvesh3** [comment]
@dkarlovi we have a PR for increasing the static analysis level. please see https://github.com/pimcore/pimcore/pull/11826

**Comment by dkarlovi** [comment]
@dvesh3 looks great, thanks for linking!

**Comment by dvesh3** [comment]
Fixed by #11868
