### ISSUE TITLE
[Bug]: Paste into table of DataObjects

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#11795]
### Expected behavior

Paste window imports data to table.

### Actual behavior

Paste window immediatly closes if you start typing. Pasted data is not applied after save.
![image](https://user-images.githubusercontent.com/9052094/160585875-b98c49d3-2323-48ba-9015-eefd9e6ca86e.png)

### Steps to reproduce

1. Create class with table
2. Try to paste any data via the paste button into the table
3. save
4. reload
5. no data applied

**Comment by brusch** [comment]
Duplicates #11795

**Comment by passioneight** [comment]
@brusch seems like you linked the wrong issue.

**Comment by brusch** [comment]
@passioneight Ooops, you're right, sorry, this is the correct one: #11729
