### ISSUE TITLE
Upload Path Asset in Objects: renaming asset path afterwards causes invalid asset path

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#1181]
+) create class and set upload path to image/href attribute
+) rename folder path afterwards
+) try to upload asset within object, open the asset and try to find it in asset tree

**Comment by brusch** [comment]
At least partly solved by #3281 - you can find those asses in `/_default_upload_bucket`. 
The upload path config is not based on the ID, otherwise this would cause again issues in various deployment scenarios.
