### ISSUE TITLE
[Bug]: $storage->deleteDirectory does not seem to be working on S3

### ISSUE THREAD

**Issue by pimcore-galilee** [pimcore/pimcore#11819]
### Expected behavior

Hello all. 
I have set up my pimcore to work on S3 for the storage.
I am of course expecting to be able to delete assets and folders.

### Actual behavior

What I can see is : 
When trying to delete an image, pimcore deletes the image (here this is ok) but next tries to delete thumbnails. To do so,  the following function fails : $storage->deleteDirectory($item->path());
This is also this function that is being call when trying to delete a folder. And of course I cannot delete folder either in Pimcore (even an empty one).

I am wondering if specific IAM rights are needed to do batch operations since the AWS class that is being used is the BatchDelete class.

Also for thumbnails any reasons why not simply using :
$storage->delete($item->path());

Since this is actually solving the issue.

### Steps to reproduce

Use teh following conf for example : 
services:
    pimcore_s3:
        class: 'Aws\S3\S3Client'
        arguments:
            -  endpoint: "%env(APP_S3_ENDPOINT)%"
               region: 'us-east-1'
               version: 'latest'

flysystem:
    storages:
        pimcore.asset.storage:
            adapter: 'aws'
            visibility: private
            options:
                client: 'pimcore_s3'
                bucket: '%env(APP_S3_BUCKET)%'
                prefix: assets
        pimcore.thumbnail.storage:
            adapter: 'aws'
            visibility: private
            options:
                client: 'pimcore_s3'
                bucket: '%env(APP_S3_BUCKET)%'
                prefix: thumbnail
        pimcore.version.storage:
            adapter: 'aws'
            visibility: private
            options:
                client: 'pimcore_s3'
                bucket: '%env(APP_S3_BUCKET)%'
                prefix: version
        pimcore.asset_cache.storage:
            # Storage for cached asset files, e.g. PDF and image files generated out of Office files or videos
            # which are then used by the thumbnail engine as source files
            adapter: 'aws'
            visibility: private
            options:
                client: 'pimcore_s3'
                bucket: '%env(APP_S3_BUCKET)%'
                prefix: asset-cache
        pimcore.recycle_bin.storage:
            # Storage for serialized recycle bin data of documents/asset/data objects
            adapter: 'local'
            visibility: private
            options:
                directory: '%kernel.project_dir%/var/recyclebin'
        pimcore.admin.storage:
            # Storage for shared admin resources, such as the user avatar, custom logos, ...
            adapter: 'local'
            visibility: private
            options:
                directory: '%kernel.project_dir%/var/admin'

**Comment by pimcore-galilee** [comment]
[trace.log](https://github.com/pimcore/pimcore/files/8392007/trace.log)

**Comment by brusch** [comment]
Thanks for reporting the issue. However, we're using Flysystem without any modifications,  so probably better to report your issue there: 

https://github.com/thephpleague/flysystem-aws-s3-v3

**Comment by pimcore-galilee** [comment]
Just for information you are right. I updated both League and aws sdk and everything is ok now. For some reasons my packages were not at the right level.
