### ISSUE TITLE
[Improvement]: sort rows in table data type

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#11821]
### Improvement description

Currently, the only way to sort entries in a [`Table` within a data object](https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Table.html) is by:

1. Clicking the copy button
2. Changing the order of the rows in text form
3. Clicking "Copy" to actually copy the modified data to the clipboard
4. Clicking the paste button
5. Paste the copied content to apply the new order

Instead of this, it would be nice to have arrow-buttons to change the order of rows - similar to the `Relations` field:
<img width="106" alt="image" src="https://user-images.githubusercontent.com/57256630/161206559-f07c7a86-a600-4ff8-90f6-79dd2df6f986.png">

**Comment by rberneder** [comment]
I agree with @passioneight and would even extend this idea to the whole user interface:

As the backend UI will be re-implemented, we should use the chance to harmonize the look and the capabilities of all editable UI components. One can feel that along the growth of Pimcore some UI components like the editables evolved differently than others.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
