### ISSUE TITLE
Table object data type: add option to force fixed number of rows/columns

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#1183]
![image](https://cloud.githubusercontent.com/assets/4639428/21896696/8e9e6a56-d8e7-11e6-8d63-7adfb1e91772.png)

An option next to the "Columns" option for forcing the number of columns would be a good improvement. In many cases it would be needed to have a fixed number of table columns but the user still has the options to add and remove columns. It would be much easier for the user if we drop these buttons if not needed:

![image](https://cloud.githubusercontent.com/assets/4639428/21896832/fa7e77a2-d8e7-11e6-82d8-974e6ec4e1f5.png)

The same improvement could be done for rows too.

**Comment by ultramegatom** [comment]
+1
