### ISSUE TITLE
[Bug]: Advanced Many-to-Many Relation loses configuration on context switch

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#11837]
### Expected behavior

When adding columns to a Advanced Many-to-Many Relation it should not be lost.

### Actual behavior

After adding a column, and switching to another data input and back again the content of the column configuration is lost.

### Steps to reproduce

On demo.pimcore.fun:

1. Add an Advanced Many-to-Many Relation
2. Configure a column like this:
![image](https://user-images.githubusercontent.com/279826/161514737-d98b8663-f910-4ce5-aa3d-626d4c9672c3.png)

3. Click on another data input e.g. like this:
![image](https://user-images.githubusercontent.com/279826/161514828-79023736-9477-4ee5-af32-0d22d2ee4abf.png)

4. Go back to the Relation:
![image](https://user-images.githubusercontent.com/279826/161514942-515a113b-9113-46ce-bbae-a44ba7d6ea48.png)

**Comment by mcop1** [comment]
Resolved by #11942
