### ISSUE TITLE
[Improvement]: Search & Move should support object variants

### ISSUE THREAD

**Issue by dlhck** [pimcore/pimcore#11854]
### Improvement description

Currently only objects and folders can be moved with "Search & Move", but it would be also very handy with variants.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
