### ISSUE TITLE
[Bug]: integer number field error entering e

### ISSUE THREAD

**Issue by kjkooistra-youwe** [pimcore/pimcore#11864]
### Expected behavior

When entering an 'e' in an integer number field it should be filtered out.

### Actual behavior

An error popup is displayed with a PHP error.
![Pimcore_number_field_e](https://user-images.githubusercontent.com/24292941/162214370-0f9b1b5e-c26d-43b9-8f9a-139d232d6287.png)

### Steps to reproduce

- Modify or create a new class, add a number field and check the integer checkbox.
- Create a new data object of this class and add one or more `e`s to the number input.
- The error popup is displayed.
- Reload the data object to reproduce it again.

**Comment by NiklasBr** [comment]
It's not just a question about removing letters and other non-numbers from the input. E.g. `3.2E+11` is [a valid integer though](https://en.wikipedia.org/wiki/Scientific_notation#E_notation). But the error message is bad and should be fixed so that it is human-readable.
