### ISSUE TITLE
[Bug]: Index Field Selection with "Multi Select from Remote" not working in Blocks

### ISSUE THREAD

**Issue by mysliwietzflorian** [pimcore/pimcore#11861]
### Expected behavior

Data in blocks should be persisted in the database.

### Actual behavior

 Index Field Selection with "Multi-Select from Remote" is not persisted into a serialized PHP object, indifferent to inheritance settings.

### Steps to reproduce

Reproducible in the Pimcore Demo. A minimal class definition is provided in the attachment.  
Fill the block data, save, and reload. I will also take a further look into the problem.

![indexFieldSelectionTest](https://user-images.githubusercontent.com/23225429/162148324-9bee9464-eede-4804-9320-48a7d115a165.png)

[class_IndexFieldSelectionTest_export.zip](https://github.com/pimcore/pimcore/files/8440755/class_IndexFieldSelectionTest_export.zip)

**Comment by jremmurd** [comment]
This is especially fatal during Pimcore X Update. Before the update data gets saved as expected, afterwards all data is lost when saving any of the objects.

**Comment by mysliwietzflorian** [comment]
Will be fixed with #11895. `ClassDefinition\IndexFieldSelection` has not implemented the `NormalizerInterface` which is needed to store the data inside blocks in the DB.

As @jremmurd mentioned, this has already worked before (at least Pimcore 6.4). In the meantime, any saving action meant a loss of the block data in the Pimcore objects. The PR should fix that.


A retrospective question would be: can we mitigate or prevent these kinds of problems in the future? For instance, could be create a collection of automated tests for Pimcore data types in various configurations where we focus on storing and retrieving data?

**Comment by fashxp** [comment]
there are already tests for that, still they are not complete yet and cover all cases ... seems blocks is one of these cases.
