### ISSUE TITLE
[Feature]: fully integrate Symfony's ErrorHandler

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#11878]
### Feature description

Currently, Pimcore doesn't correctly handle deprecations (reported in #11870).

This can be fixed with carefully navigating between errors, deprecations, tweaking own error handlers, etc.

Since Pimcore wants to align itself more with Symfony (as seen in #10344), it should embrace the ErrorHandler fully, by removing Pimcore's own error handling code and delegating all those tasks to ErrorHandler.

**Comment by robertSt7** [comment]
@dkarlovi Hi, I linked a PR to this issue, may you could take a quick look to see if anything else is missing. Thanks

**Comment by dkarlovi** [comment]
@robertSt7 I'm not seeing any place where you enable ErrorHandler? I remember it used to be enabled in debug mode.
https://github.com/symfony/recipes/blob/90f05b162bcf87755eafb73f5ae4f4f8a1b8f1ef/symfony/framework-bundle/4.4/public/index.php#L12

**Comment by robertSt7** [comment]
@dkarlovi We now using it here for debug mode and normal mode: https://github.com/pimcore/pimcore/pull/14331/files#diff-ae4fd3053efaec0fe50cc39c28378027e8884af72d1facbb19980ade26f36220R221-R226
