### ISSUE TITLE
[Bug]: Pimcore X by default displays deprecations directly in output (even in prod mode), breaking JSON etc

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#11870]
### Expected behavior

Logs and error handling managed in a streamlined way, through Symfony's features (ErrorHandler, Monolog integration, etc).

### Actual behavior

Logs managed in all sorts of different ways, including PHP's legacy error log.

### Steps to reproduce

Run Pimcore X on PHP 8.1, you'll get all sorts of deprecations. This is OK in principle because [deprecations are not errors](https://wouterj.nl/2021/11/deprecations-are-not-errors).

What's not OK is that Pimcore basically forces you to have some specific logging / error handling settings enabled, namely:

https://github.com/pimcore/pimcore/blob/c13fb850a024ca7b81f3c940f186cfb9e10aeb56/lib/Bootstrap.php#L79-L80

https://github.com/pimcore/pimcore/blob/c13fb850a024ca7b81f3c940f186cfb9e10aeb56/lib/Bootstrap.php#L126-L127

This is by default basically incompatible with "12 factor" app architecture (which I've wrote about before in #8531), but also makes things difficult to debug and fix, like **deprecations being displayed in prod env** in API responses (breaking JSON) and frontend rendered pages.

This applies specifically to `var/log/php.log`, but perhaps to

```
var/log/loginerror.log
var/log/usagelog.log
```

also? In short, all of these things should be deprecated in favor of them being setup in "the Symfony way", which allows the developers to reconfigure them (for example, Sentry, Logwatch, etc).

**Comment by brusch** [comment]
We can probably change that also without breaking anything: 
- CLI should be safe to change imho
- We can check whether `PIMCORE_PHP_ERROR_LOG` is customized, if not, nothing will be set 
WDYT?

**Comment by dkarlovi** [comment]
@brusch that might make sense, this issue should probably be 3-4 separate issues because there's several different issues listed here.

If we're talking just about `PIMCORE_PHP_ERROR_LOG`, allowing setting it to `null` or similar to disable writing `var/log/php.log` and enabling display errors might work, yes. In 11.x it could be opt-in instead of opt-out, but maybe not even needed since you can handle it "the Symfony way".

I do think the other things should be addressed too:
1. `loginerror.log`, `usagelog.log` (probably others, email log?) migrated to Monolog, allowing developers to reconfigure / disable them
2. better integration with `ErrorHandler`, which is IMO a prerequisite for #10344, currently Pimcore and Symfony are in a bit of a collision, each one trying to do its own thing, [undoing what the other did](https://gfycat.com/ambitiouslikablebanteng).

**Comment by dkarlovi** [comment]
@brusch created #11877, #11878 for the other two issues, this one can then deal with the over-zealous error reporting.

**Comment by brusch** [comment]
@dkarlovi 👍 assigned already the `11` milestone.

**Comment by dkarlovi** [comment]
@brusch I think this should be treated as a bug because it does break stuff as is in prod. I had Pimcore respond with

```json
Deprecated: passing null to strlen blah blah

{"success": true}
```

I'm currently manually disabling `display_error` in front controllers.

**Comment by paulhaem** [comment]
This is still a big issue using stable version 10.x as it has been only fixed in 11x. which is not production ready yet.
