### ISSUE TITLE
[Bug]: CKEditor: Tables in new created areabricks have no border

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#11879]
### Expected behavior

If you create a new areabrick with WYSIWYG editable and create a table (with border: 0). You should see the border in the editor because of the cke_show_borders and cke_show_border CSS classes.

### Actual behavior

The cke_show_borders css class is missing. After reloading the edit window you can see the border.

### Steps to reproduce

1. Open a document in demo https://demo.pimcore.fun/admin/login/deeplink?document_65_page
2. Create a new Areabrick "WYSIWYG"
3. Create a new table with border size 0
4. The table is not visible
5. Refresh the window and you can see the table

**Comment by dvesh3** [comment]
Fixed by #11886
