### ISSUE TITLE
[Bug]: Documentation info regarding render method of editables is wrong

### ISSUE THREAD

**Issue by Brainshaker95** [pimcore/pimcore#11904]
### Expected behavior

The correct information is displayed

### Actual behavior

The wrong information is displayed

### Steps to reproduce

[The documentation states](https://pimcore.com/docs/pimcore/current/Development_Documentation/Documents/Editables/index.html):

> Pimcore automatically displays an input widget in the edit mode and renders the content when accessing the document via the frontend.

This is wrong since the returned string value will not be rendered raw. Instead the escaped version of the HTML string is displayed. 
As I see it, the caller is required to add "|raw" after the call to "render" to ensure the correct display in the edit mode.

**Comment by matthiashamacher** [comment]
Noticed the same thing in the "[Create a First Project](https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Create_a_First_Project.html#page_Showing-the-Image-in-the-View)" Documentation and added the `|raw` filter as part of my PR #11680 

See: https://github.com/pimcore/pimcore/pull/11680/files#diff-dfe66d9ff5bdd0ac142b097584577c6b666bf048487d36bfedfafd8f9f8df117R377

Could add it in that PR too, if that is wanted?

**Comment by Brainshaker95** [comment]
@matthiashamacher As far as I am concerned, go for it 🙂
