### ISSUE TITLE
[Bug]: Preview doesn´t get updated, after reapplying Content Master Document

### ISSUE THREAD

**Issue by mcop1** [pimcore/pimcore#11918]
### Expected behavior

Update preview

### Actual behavior

Preview doesn´t get updated

### Steps to reproduce

1.) Create a new page
2.) Apply Content Master Document in settings
3.) Overwrite one of the inherited fields
4.) Check preview tab -> preview should be fine
5.) Reapply Content Master Document 
6.) Check and compare edit / preview tab

**Comment by dvesh3** [comment]
Seems like an edge case as you would simply flush the values with bin icon:
![image](https://user-images.githubusercontent.com/5137917/167808351-99ce742b-aeba-4896-829b-010d94bfe7d1.png)
on editmode instead of reapplying the content master document without saving values.

**Comment by fashxp** [comment]
but isn't that also the case when applying a different master document?

**Comment by dvesh3** [comment]
> but isn't that also the case when applying a different master document?

yes, that's a valid case. It causes problem with draft versions(autosave) only.

**Comment by dvesh3** [comment]
Fixed by #12128
