### ISSUE TITLE
Newsletter: delivery settings not capable of multisite

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#1191]
# Feature Request 
#### Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [ x ] There is no existing issue regarding the same topic

## Feature description
When dealing with an pimcore instance, which makes use of its great multisite feature, unfortunately it is not possible to have different delivery settings for each site yet. It would be nice to be able to configure for example different SMTP settings for each site within the system settings > newsletter. Something similar to this already exists in marketing > marketing settings (Google Tracking ID, etc.). 

Thanks!

**Comment by brusch** [comment]
I'd prefer a more flexible system, as suggested here: #252
So I close this issue here for now.
