### ISSUE TITLE
[Bug]: User - Update - Error - Array to string conversion

### ISSUE THREAD

**Issue by QuarkWave** [pimcore/pimcore#11920]
### Expected behavior

Being able to Update an User

### Actual behavior

Create a new user is OK 
but updating an existing one rises a "Warning: Array to string conversion" error.
It seems that this problem started with the 10.3.x versions

Or maybe it s just me ?

I tried on my 3 servers and get the error with versions 10.3.4 and 10.3.5
but it s still working with the 10.2.3

> An exception occurred while executing 'UPDATE users SET `type` = ?, `password` = ?, `firstname` = ?, `lastname` = ?, `email` = ?, `language` = ?, `admin` = ?, `active` = ?, `roles` = ?, `welcomescreen` = ?, `closeWarning` = ?, `memorizeTabs` = ?, `allowDirtyClose` = ?, `contentLanguages` = ?, `activePerspective` = ?, `lastLogin` = ?, `keyBindings` = ?, `twoFactorAuthentication` = ?, `permissions` = ?, `classes` = ?, `docTypes` = ?, `perspectives` = ?, `websiteTranslationLanguagesView` = ?, `websiteTranslationLanguagesEdit` = ?, `id` = ?, `parentId` = ?, `name` = ? 
> WHERE `id` = ?' with params ["user", null, "wer", "", "", "en", 0, 1, "", 0, 1, 1, 0, [], null, 0, "[{\"action\":\"save\",\"key\":83,\"ctrl\":true},{\"action\":\"publish\",\"key\":80,\"ctrl\":true,\"shift\":true},{\"action\":\"unpublish\",\"key\":85,\"ctrl\":true,\"shift\":true},{\"action\":\"rename\",\"key\":82,\"alt\":true,\"shift\":true},{\"action\":\"refresh\",\"key\":116},{\"action\":\"openDocument\",\"key\":68,\"ctrl\":true,\"shift\":true},{\"action\":\"openAsset\",\"key\":65,\"ctrl\":true,\"shift\":true},{\"action\":\"openObject\",\"key\":79,\"ctrl\":true,\"shift\":true},{\"action\":\"openClassEditor\",\"key\":67,\"ctrl\":true,\"shift\":true},{\"action\":\"openInTree\",\"key\":76,\"ctrl\":true,\"shift\":true},{\"action\":\"showMetaInfo\",\"key\":73,\"alt\":true},{\"action\":\"searchDocument\",\"key\":87,\"alt\":true},{\"action\":\"searchAsset\",\"key\":65,\"alt\":true},{\"action\":\"searchObject\",\"key\":79,\"alt\":true},{\"action\":\"showElementHistory\",\"key\":72,\"alt\":true},{\"action\":\"closeAllTabs\",\"key\":84,\"alt\":true},{\"action\":\"searchAndReplaceAssignments\",\"key\":83,\"alt\":true},{\"action\":\"glossary\",\"key\":71,\"shift\":true,\"alt\":true},{\"action\":\"redirects\",\"key\":82,\"ctrl\":false,\"alt\":true},{\"action\":\"sharedTranslations\",\"key\":84,\"ctrl\":true,\"alt\":true},{\"action\":\"recycleBin\",\"key\":82,\"ctrl\":true,\"alt\":true},{\"action\":\"notesEvents\",\"key\":78,\"ctrl\":true,\"alt\":true},{\"action\":\"applicationLogger\",\"key\":76,\"ctrl\":true,\"alt\":true},{\"action\":\"reports\",\"key\":77,\"ctrl\":true,\"alt\":true},{\"action\":\"tagManager\",\"key\":72,\"ctrl\":true,\"alt\":true},{\"action\":\"seoDocumentEditor\",\"key\":83,\"ctrl\":true,\"alt\":true},{\"action\":\"robots\",\"key\":74,\"ctrl\":true,\"alt\":true},{\"action\":\"httpErrorLog\",\"key\":79,\"ctrl\":true,\"alt\":true},{\"action\":\"customReports\",\"key\":67,\"ctrl\":true,\"alt\":true},{\"action\":\"tagConfiguration\",\"key\":78,\"ctrl\":true,\"alt\":true},{\"action\":\"users\",\"key\":85,\"ctrl\":true,\"alt\":true},{\"action\":\"roles\",\"key\":80,\"ctrl\":true,\"alt\":true},{\"action\":\"clearAllCaches\",\"key\":81,\"ctrl\":false,\"alt\":true},{\"action\":\"clearDataCache\",\"key\":67,\"ctrl\":false,\"alt\":true},{\"action\":\"quickSearch\",\"key\":70,\"ctrl\":true,\"shift\":true}]", "{\"required\":false,\"enabled\":false,\"secret\":\"\",\"type\":\"\"}", "", "", "", "", "", "", 34, 0, "BUG", 34]: Warning: Array to string conversion
> 
> Server threw exception - could not perform action. Please reload the admin interface and try again.

### Steps to reproduce

- Open an existing User
- Make a change
- Click Save

**Comment by aryaantony92** [comment]
Fixed by #11935
