### ISSUE TITLE
Object with Metadata and checkbox can not be selected using ExtJS 6

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#1193]
# Bug Report

### Expected behavior 
Create a datatype object with metadata and add a boolean to it like this:
![object-meta-configuration](https://cloud.githubusercontent.com/assets/2771909/22101717/e2a6aabc-de34-11e6-953f-4f5dd8208510.png)

You should be able to change the value of the boolean in the interface, like you can change the number field here:
![object-meta-1](https://cloud.githubusercontent.com/assets/2771909/22101737/f5af7260-de34-11e6-8cc3-32aaf620993e.png)

  
### Actual behavior  
  
The checkbox is continuesly being activated / deactivated but never selected:
![object-meta-2](https://cloud.githubusercontent.com/assets/2771909/22101758/0cef6368-de35-11e6-9df3-8ee507f70f8c.png)

Tested with Firefox 50.1.0 and Chrome 52.

Selecting the checkbox does work when using ExtJS 3 by appending ?extjs3=true to the url.

### Steps to reproduce  

Create a relation with object metadata in a class and assign a boolean type to it. Create objects related to each other and try to activate the boolean checkbox as metadata.

**Comment by ckogler-elements** [comment]
Hi,

does this also occure in the latest Pimcore Version? 
I think this Commit https://github.com/pimcore/pimcore/commit/d008354e456c459ab9d5b7be58f65d907e654b0d 
should fix it.
