### ISSUE TITLE
[Feature]: Add ManyToManyRelation type to function addMetadata 

### ISSUE THREAD

**Issue by ServiceWebLG** [pimcore/pimcore#11949]
### Feature description

Hello devs,
We are under Pimcore Enterprise and we install Enterprise Metadata Bundle.
With a command, we want to add programmatically objects coming from the PIM in a ManyToManyRelation type field.
But apparently this is not possible because authorized fields type in the AddMetadata function are "$type can be "asset", "checkbox", "date", "document", "input", "object", "select " or "textarea" "

Maybe there is another way to add objects in metadata of type ManyToManyRelation, but we didn't found it.
Thanks for you feedback.

Best regards

**Comment by fashxp** [comment]
Hmm, works as expected. The `type` parameter of `addMetadata` function is a normal string. 

```
        $asset = Asset::getById(318);
        $col = new Collections();
        $col->setAssetId($asset->getId());
        $col->setCollections(['MyCollection']);
        $col->applyToAsset();

        $asset->addMetadata('MyCollection.relations', 'manyToManyRelation', [
            Concrete::getById(22222),
            Concrete::getById(22225),
        ]);
        $asset->save();
```

Please understand, that we cannot provide enterprise support via our open source channels. If you need further assistance, please contact your contact person at Pimcore for further support. Thank you.
