### ISSUE TITLE
[Bug]: Index Field Selection - last change in the current dev branch introduced backward compatibility break

### ISSUE THREAD

**Issue by mysliwietzflorian** [pimcore/pimcore#11941]
### Expected behavior

Follow up to #11861.

In the PR #11895, the NormalizerInterface is implemented for IndexFieldSelections.

I used an array to normalize the relevant properties from the data object. With the help of a backup from before a PCX update, I noticed that the `ObjectData\IndexFieldSelection` object was used before PCX for serialization (which is not a best practice I suppose).

So instead the ` DataObject\Traits\SimpleNormalizerTrait` could have been used instead.

We now have two options:
1. Either, keep it in an array (current state of the code) and break backward compatibility further (which was already broken since PCX) but do not use a dependency to a data object in the serialization OR
2. Implement NormalizationInterface with SimpleNormalizerTrait instead and keep it serialized in the data object. I can provide a new PR for that.

**What would you say?**

### Actual behavior

Serialized Index Field Selection from before PCX can not be loaded correctly.

### Steps to reproduce

Apply a serialized DB entry from before a PCX update to the current dev branch and it will not be loaded correctly.

**Comment by mcop1** [comment]
@mysliwietzflorian good catch, thank you! I created a pr that should resolve the problem. We already did it that way for other datatypes, e.g. https://github.com/pimcore/pimcore/pull/10130 

Could you please check if this resolves your problems? Would be appreciated. 

Thanks again

**Comment by brusch** [comment]
Fixed by #11972
