### ISSUE TITLE
[Bug]: Memory Leak issue when generating QR code in pimcore document preview tab.

### ISSUE THREAD

**Issue by pdchaudhary** [pimcore/pimcore#11958]
### Expected behavior

it should generate qr code in pimcore document preview.

### Actual behavior

It is not generating QR code and throwing 500 error.

### Steps to reproduce

-  Open document in admin
-  Go to preview tab
-  Click on QR code 
-  Download QR code 
-  And it is throwing "Allowed memory size of 134217728 bytes exhausted (tried to allocate 63138913 bytes) in /var/www/html/vendor/endroid/qr-code/src/Writer/PngWriter.php on line 50"

I have also checked on pimcore demo site and it is reproducible.

**Comment by brusch** [comment]
Works for me like a charm, also on our public demo (demo.pimcore.fun).

**Comment by brusch** [comment]
Probably your mem-limit is just too low.

**Comment by pdchaudhary** [comment]
![image](https://user-images.githubusercontent.com/30948231/165694131-89757939-efe1-4c5d-8b6f-1eca3b97c212.png)
@brusch Yes, it is working after increasing mem-limit but you can check on above image. it is reproducible on the pimcore demo.
