### ISSUE TITLE
The targeting JS should be added at the end of the head, not the beginning

### ISSUE THREAD

**Issue by lmanzurv** [pimcore/pimcore#1195]
Change the following code to add the targeting JS at the end of the head instead of the beginning to comply with W3C standards.

https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Controller/Plugin/Targeting.php#L211

```
            $headEndPosition = stripos($body, "</head>");
            if ($headEndPosition !== false) {
                $body = substr_replace($body, $code."\n</head>", $headEndPosition, 8);
            }

            $this->getResponse()->setBody($body);
```

**Comment by brusch** [comment]
This is by intention, because the script can redirect the user to another URL based on certain rules. Having the script at the beginning, can avoid loading unnecessary data. 
Btw. in which standard it is defined that scripts have to be at the end of ´<head>`? Any reference?

**Comment by lmanzurv** [comment]
It’s not that scripts need to be at the end, it is that the charset and http-equiv metadata need to be in the first 1024 bytes of the document, hence they need to be exactly after the head opening tag. Here’s the link for reference: Quick answer <https://www.w3.org/International/questions/qa-html-encoding-declarations.en#quickanswer>

**Comment by ThomasKeil** [comment]
In any case it would be nice if the include of the script could be disabled like it is possible for the picture polyfills:

`Asset\Image\Thumbnail::setEmbedPicturePolyfill(false);`

This way you can include it anywhere you want or even feed it to your own minifier/concatenizer like grunt- or gulp-tasks

We did this in Targeting.php:

```
    /**
     * @var bool
     */
    protected static $embedTargetingJavascript = true;

    /**
     * @return boolean
     */
    public static function getEmbedTargetingJavascript()
    {
        return self::$embedTargetingJavascript;
    }

    /**
     * @param boolean $embedTargetingJavascript
     */
    public static function setEmbedTargetingJavascript($embedTargetingJavascript)
    {
        self::$embedTargetingJavascript = $embedTargetingJavascript;
    }
```
And in dispatchLoopShutdown:

```
            if (self::getEmbedTargetingJavascript()) {
                $code .= '<script type="text/javascript" src="/pimcore/static6/js/frontend/targeting.js"></script>';
            }
```


I can provide this as pull request if you want :-)

**Comment by brusch** [comment]
@ThomasKeil yes, please provide a PR - Thanks :)
