### ISSUE TITLE
[DataObject] Support convertTo on InputQuantityValue

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#11973]
### Improvement description

please see https://github.com/pimcore/pimcore/pull/11968

**Comment by Corepex** [comment]
This ticket is obsolete since `InputQuantityValue` now extends `QuantityValue`

https://github.com/pimcore/pimcore/blob/8d70cd65af5d834275d6c55d518beb8e18457038/models/DataObject/Data/InputQuantityValue.php#L21

**Comment by blankse** [comment]
@Corepex Why was this done? I think `InputQuantityValue` should only accept strings, and `QuantityValue` should only accept numbers. So both accept all types...

**Comment by Corepex** [comment]
> @Corepex Why was this done? I think `InputQuantityValue` should only accept strings, and `QuantityValue` should only accept numbers. So both accept all types...

created a followup: https://github.com/pimcore/pimcore/issues/14474
