### ISSUE TITLE
[Bug]: Grid Option window: top border hidden

### ISSUE THREAD

**Issue by kkirsz** [pimcore/pimcore#11986]
### Expected behavior

The window borders are always inside the browser and visible.

### Actual behavior

When dragging top border, the top border is hidden under the browser. User can't drag it back.

### Steps to reproduce

This defect only impacts usability. Click Grid Option.
![01](https://user-images.githubusercontent.com/26323830/165504967-8bc9bc79-8e55-471c-a67c-05d43cd9d078.jpg)
Drag the window border to change size.
![02](https://user-images.githubusercontent.com/26323830/165506096-9694889e-3422-47cd-81f0-fa781c987c9d.jpg)

**Comment by brusch** [comment]
@kkirsz can you maybe provide a PR fixing the issue? Thanks in advance!

**Comment by fashxp** [comment]
should be fixed by #13628
