### ISSUE TITLE
[Documents] Not possible to save documents

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#11987]
### Expected behavior

Documents should be saved

### Actual behavior

throwing exception Doctrine\DBAL\Connection::fetchOne(): Argument #2 ($params) must be of type array, null given

### Steps to reproduce

1. Open Document
2. Click save / save & publish.

**Comment by dvesh3** [comment]
Regression of https://github.com/pimcore/pimcore/pull/11931/files#diff-48235de7b392a4ff9ed273062d750e2732a5b1f8355cd76109abf4c5538a6c45R1085

**Comment by blankse** [comment]
@dvesh3 Fix https://github.com/pimcore/pimcore/pull/11988 the error?

**Comment by dvesh3** [comment]
@blankse yes, but `\Pimcore\Db:fetch..` method doesn't expect null params...

**Comment by blankse** [comment]
Yes, I've thought about deprecating all values except arrays. It should always be possible to specify an array here.
