### ISSUE TITLE
[Bug]: Keyboard shortcut to save causes error within folders

### ISSUE THREAD

**Issue by GAL-GC** [pimcore/pimcore#11992]
### Expected behavior

When pressing the shortcut to save (ctrl + s), it should save (here the folder).

However, a popup is then visible, saying, that save was not successful. If I manually click the save button, it works fine and no error message is visible.

![image](https://user-images.githubusercontent.com/91726275/165694688-e15b2caf-8845-45ba-b285-d005507c512a.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/91726275/165694440-416d2f6a-6551-4d29-83c5-5a2a524d48f7.png)

It triggers a save action, but not the correct one.

This is what I get inside network traffic out of debugger console

![image](https://user-images.githubusercontent.com/91726275/165695018-e1c5d0de-d1d0-4446-a98d-67a05c0a32ce.png)

### Steps to reproduce

- Create a folder in the document tree
- Press the shortcut to save when within the folder window (usually CTRL+S)
- You'll see an error message. If you click the save button by hand, you won't get it

**Comment by mcop1** [comment]
https://github.com/pimcore/pimcore/pull/12025 fixes the error message
https://github.com/pimcore/pimcore/pull/12050 fixes the difference in clicking the save button and pressing CTRL+S
