### ISSUE TITLE
[Bug]: Predefined Metadata: Attempted to call an undefined method named "marshal" of class ClassDefinition\Data\Textarea

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#11994]
### Expected behavior

(we do not have access to the Enterprise repository, therefore adding the bug report here, feel free to move it)

It should be possible to add and edit and use predefined metadata fields of type "textarea".

### Actual behavior

![image](https://user-images.githubusercontent.com/279826/165708313-15125ed1-e60c-4e9f-82da-bcf79622218d.png)

```
Timestamp: Thu Apr 28 2022 10:13:32 GMT+0200 (Central European Summer Time)
Status: 500 | Internal Server Error
URL: /admin/settings/get-predefined-metadata
Message: Attempted to call an undefined method named "unmarshal" of class "Pimcore\AssetMetadataClassDefinitionsBundle\Model\ClassDefinition\Data\Textarea".
Trace: 
in /var/www/pimcore/vendor/pimcore/pimcore/models/Metadata/Predefined.php:369
#0 /var/www/pimcore/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/SettingsController.php(264): Pimcore\Model\Metadata\Predefined->expand()
#1 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(152): Pimcore\Bundle\AdminBundle\Controller\Admin\SettingsController->getPredefinedMetadataAction(Object(Symfony\Component\HttpFoundation\Request))
#2 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#3 /var/www/pimcore/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /var/www/pimcore/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#5 {main}
```

### Steps to reproduce

1. Have a metadata item that ls a textarea:
![image](https://user-images.githubusercontent.com/279826/165708177-4ef25568-b12b-49fc-a648-8b1c8ce90a2a.png)
2. [Install the Metadata Bundle](https://pimcore.com/docs/asset-metadata/current/Installation/index.html)
3. Attempt to use it on an Asset

**Comment by fashxp** [comment]
can you please describe the steps to reproduce more in detail? 
the screen you showed should not be possible, because as soon as you activate the enterprise metadata bundle, you don't have access to the standard predefined asset metadata anymore.

**Comment by NiklasBr** [comment]
Nothing fancy I think, this is the first time using it. Executed `composer require pimcore/asset-metadata-class-definitions` (got `v1.2` which by the way is still marked as "dev" in the docs), then installed the bundle and enabled it in the admin UI. Followed by a `bin/console cache:clear` with Pimcore 10.3.6.

**Comment by fashxp** [comment]
did you reload admin interface?

**Comment by NiklasBr** [comment]
Yes

**Comment by dvesh3** [comment]
> can you please describe the steps to reproduce more in detail? the screen you showed should not be possible, because as soon as you activate the enterprise metadata bundle, you don't have access to the standard predefined asset metadata anymore.

@NiklasBr As Christian said, It is not possible to set predefined Asset metadata once you enable the bundle (see below):
![image](https://user-images.githubusercontent.com/5137917/166432728-08e97d28-9229-4c04-959c-80a6388e60d2.png)

Could you please share the correct steps to reproduce the issue? thanks!

**Comment by NiklasBr** [comment]
@dvesh3 These are *literally* the steps done, nothing less, nothing more. There are not a lot of things which are ambiguous here, I don't understand what else you need?

1. In your terminal run: `composer require pimcore/asset-metadata-class-definitions`
2. In your terminal navigate to the Pimcore root directory, then run the command: `bin/console pimcore:bundle:enable PimcoreAssetMetadataClassDefinitionsBundle`
3. In your terminal, run the next command: `bin/console pimcore:bundle:install PimcoreAssetMetadataClassDefinitionsBundle`
5. Clear browser cache, reload the browser.
6. Navigate to the *Metadata* tab in an asset.

(step 3 could also be tried in the Bundles view in the Pimcore admin interface with the same result).

**Comment by dvesh3** [comment]
Sorry, not reproducible. please feel free to come up with a PR to fix the issue then we can reopen it. thanks!

**Comment by NiklasBr** [comment]
WTF kind of response is that?

**Comment by dvesh3** [comment]
A sensible one 😉
