### ISSUE TITLE
[Bug]: advancedManyToManyRelations: Saving changes not possible

### ISSUE THREAD

**Issue by mcop1** [pimcore/pimcore#12007]
### Expected behavior

Saving changes should work

### Actual behavior

Error message when adding a new relation:
![image](https://user-images.githubusercontent.com/89011527/166201954-9fcf04a8-93b1-428e-92d6-4e5d07971800.png)

Sometimes I even had the problem that my changes (on existing relations) weren´t saved properly. 

### Steps to reproduce

1.) Add advanced many to many relation to data object class
2.) Try to name it "manyToManyRelations"
3.) See error message above

**Comment by kingjia90** [comment]
the problem is caused by this PR
https://github.com/pimcore/pimcore/pull/11942/files
