### ISSUE TITLE
[Bug]: Grouped Area Brick List not scrollable

### ISSUE THREAD

**Issue by SaschaHowe** [pimcore/pimcore#12005]
### Expected behavior

Be able to scroll the grouped area brick list and access all bricks without scrolling the whole page

### Actual behavior

When having a grouped brick list, the brick lis is not scrollable under all conditions. 
Looks like if the interaction with the list happens far enough at the top of the current page, the list is scrollable
However this is almost always not the case and list is not scrollable. 

Img: cut of brick list on editor edges
<img width="748" alt="brick list cut off on screen editor edges" src="https://user-images.githubusercontent.com/340244/165931519-eb6c0830-3f64-4403-af39-5b15935c7c7c.png">

Img: carefully scrolled page up to see top of brick list
<img width="762" alt="carfully scrolled page up" src="https://user-images.githubusercontent.com/340244/165931523-4c63303d-c4ae-43c1-bea1-b2b611084cbe.png">

### Steps to reproduce

Have a long list of bricks in a brick group
access the content of brick group while somewhere down on the page you want to edit

**Comment by brusch** [comment]
@SaschaHowe can you maybe provide a PR for this issue? Thanks in advance!

**Comment by torqdev** [comment]
@SaschaHowe a PR has been merged, has this fixed your issue? Thanks

**Comment by fashxp** [comment]
should be fixed by #13626
