### ISSUE TITLE
[Bug]: an object on the same level can't be moved under other object as a child, if the other object has't children

### ISSUE THREAD

**Issue by arn1ex** [pimcore/pimcore#12016]
### Expected behavior

you can move object under another object.

### Actual behavior

An error occurring  as soon as you try to drag an object under other object 
![pimcorebug](https://user-images.githubusercontent.com/104794370/166412477-72483232-ba46-4099-b5d4-9bdfd1e9e10d.PNG)

### Steps to reproduce

- Go to the Pimcore demo and create a new object. No need to be published, just save.
- Create a second object.
- Try to dragg an object under other (as a child)

**Comment by GALCF** [comment]
Regression of https://github.com/pimcore/pimcore/pull/11908 ?

**Comment by kingjia90** [comment]
> Regression of #11908 ?

Confirming that.
Thank you for reporting!

**Comment by dvesh3** [comment]
Fixed by #12072
