### ISSUE TITLE
Add application logger tab to the object editor

### ISSUE THREAD

**Issue by datom** [pimcore/pimcore#1201]
and show all related logger entries there

**Comment by weisswurstkanone** [comment]
build 60

**Comment by weisswurstkanone** [comment]
In addition: only show tab if enabled in class config

**Comment by weisswurstkanone** [comment]
![image](https://cloud.githubusercontent.com/assets/6142086/26725356/71db228a-479e-11e7-9b85-5f14b9657181.png)

**Comment by weisswurstkanone** [comment]
![image](https://cloud.githubusercontent.com/assets/6142086/26725369/86211704-479e-11e7-9f88-d5674a9cfecb.png)
