### ISSUE TITLE
[Bug]: PHPStan failing on 10.x

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#12010]
### Expected behavior

Should not fail.

### Actual behavior

Failing 😊

### Steps to reproduce

See https://github.com/pimcore/pimcore/runs/6255058093?check_suite_focus=true#step:8:26

**Comment by blankse** [comment]
@brusch Is already fixed in 10.4 branch. You need to merge it to 10.x
https://github.com/pimcore/pimcore/pull/12000

**Comment by brusch** [comment]
@blankse ah, thanks for the hint - I did compare the branches but it seems my local fetch didn't work and I didn't notice 🤗
