### ISSUE TITLE
[Bug][EcommerceFramework]: Voucher Token Manager Tab, inline Javascript not executed due CSP

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#12040]
### Expected behavior

No Content Security Policy or JS related errors during Voucher Generation

### Actual behavior

![image](https://user-images.githubusercontent.com/6014195/167015233-5dcb11be-9f75-4d81-9493-fd699c89290a.png)

### Steps to reproduce

Create a new Voucher Series
Switch to `Voucher Details` tab after filling the required fields

Problem is caused by inline JS here:
https://github.com/pimcore/pimcore/blob/10.4/bundles/EcommerceFrameworkBundle/Resources/views/voucher/parts/usage_statistic_script.html.twig
and 
https://github.com/pimcore/pimcore/blob/22e4ac71b55b4a16337363f25bed333e4fa417a5/bundles/EcommerceFrameworkBundle/Resources/views/voucher/voucher_code_tab_pattern.html.twig#L212-L282

**Comment by brusch** [comment]
See also #12013 which fixes already similar regressions from #11447
So doing `<script {{ pimcore_csp.getNonceHtmlAttribute()|raw }}>` should fix the issue: 
https://github.com/pimcore/pimcore/pull/12013/files#diff-8916ae3f42cad275ad7968f389db77a5b51a22b8fef6c778634b2a11402b2cecR54

**Comment by dvesh3** [comment]
Fixed by #12054
