### ISSUE TITLE
Advanced Many-To-Many Relation duplicate entries in object, if fallback languages defined

### ISSUE THREAD

**Issue by ascheider** [pimcore/pimcore#12043]
### Expected behavior

I want to assign files depending on language and have the relation only once.

### Actual behavior

Currently if you defines Advanced Many-To-Many Relation inside localized fields and use fallback languages, the relation will be created twice in the object in fallback languages.
I created screen capture: https://www.dropbox.com/s/47eevn9ib6ewesj/screen-capture_relation.webm?dl=0
Example class: https://www.dropbox.com/s/1fq9itg111aq65f/class_Award_export.json?dl=0

### Steps to reproduce

Create languages de, de_CH, en and define fallbacks.
System.yml looks like this:
![image](https://user-images.githubusercontent.com/6016485/167104500-f0d19f0a-8e35-4184-bf27-cc5e6330d6d2.png)
Import example class and create object.
Assign each language one asset, save and publish.
After reload the relation exists only once, also in object_relation_award table.
Remove file in base language, and assign new one.
Save and publish and reload object, the relation exist twice in fallback languages de_Ch and en.
Entries exists also multiple times in relation table:
![image](https://user-images.githubusercontent.com/6016485/167104996-4c28ce9d-5766-43f0-a3d9-18d2f7488715.png)

**Comment by mcop1** [comment]
@ascheider thanks for creating such a detailed issue, but unfortunately I can´t reproduce the problem.

I imported your class, created a data object and added an asset for every language.
After that I remove the asset from "German", since it is my default language, add any other asset again and save. After reload I still have one item in each language only
![image](https://user-images.githubusercontent.com/89011527/167572706-8043f4fc-00e6-4d8f-a195-ca486353b330.png)

My system.yaml
` redirect_to_maindomain: false
        language: en
        valid_languages: 'en,de,de_CH'
        fallback_languages:
            en: de
            de: ''
            de_CH: de
        default_language: de
        debug_admin_translations: false`

![image](https://user-images.githubusercontent.com/89011527/167573266-224c384d-bf21-41f8-8f6d-caed03b201ce.png)

At first glance I can´t see any difference in my approach compared to yours. Any suggestions?

**Comment by ascheider** [comment]
@mcop1 
Hey, thank you for checking. I still can reproduce the issue on my machine. The bug appear salso if i change the award name in 'de' language.
PHP Version 8.0.1
Db Version: Server version: 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~focal mariadb.org binary distribution
I will try to debug the issue deeper, maybe i will find something

**Comment by mcop1** [comment]
> @mcop1 Hey, thank you for checking. I still can reproduce the issue on my machine. The bug appear salso if i change the award name in 'de' language. PHP Version 8.0.1 Db Version: Server version: 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~focal mariadb.org binary distribution I will try to debug the issue deeper, maybe i will find something

That would be highly appreciated, thank you for your efforts!

**Comment by patkul0** [comment]
Hello guys,
one of our customers has the same problem as @ascheider and we didn't find a working solution yet. One thing that Alexander probably forgot to mention about reproducing that bug is to disable 'auto_save_interval' for objects in config.yaml file. We can see that drafts are disabled in screen capture attached to this issue. Can you confirm that?

**Comment by ascheider** [comment]
@patkul0 yes the autosave was disabled. I did not found the solution. Fortunate the customer did not needed the fallback languages, so i removed them. Wish you luck to track this bug down.

**Comment by patkul0** [comment]
I can confirm that the same thing happens if we modify object with PHP API. In our example I changed name of Award in German and duplicate entries appear in other language layer for Advanced Many-To-Many Relation attribute. This confirms that the problem is not related with ExtJS interface.

**Comment by valentin-** [comment]
This also happens in one of my installations. 

- Saving the object the first time is fine
- Saving the object a second time adds the duplicate entries
- Saving a third time (without reloading) throws the error

There is no additional data for this field in the request when saving the object.

Restoring the original object and repeat changing the object shows the same behaviour.

I've implemented a hook to clean up those entries for specific fields, but it's a bad solutions as it occurs in multiple data objects.

Update: Happened in 10.3, also 10.5

**Comment by turbo-ele** [comment]
I can confirm that this also happens on Pimcore 11.
I was just able to reproduce this on the Pimcore demo instance https://demo.pimcore.com/admin by implementing a simple class having a localized field with a many-to-many relation for assets (see class_Test_export.json) together with a fallback language.

I also found out that it's even more easy to reproduce the behavior when disabling the auto save feature.

Could please someone from Pimcore be so kind and confirm that this issue is still on your radar?

## How to reproduce

0. Optional: Disable Auto-save
1. Add class with localized many-to-many relation
2. In system settings set `en` as fallback-language for `de`
3. Create a new data object of instance `Test` and assign any asset in `en` and `de`
4. Save & Publish
5. Reload the tab
6. Delete the asset in `en`
7. Save & Publish **2 - 3 times**



## Files:

`class_Test_export.json`
```json
{
    "id": "6",
    "title": "",
    "description": "",
    "modificationDate": 1692186270,
    "parentClass": "",
    "implementsInterfaces": "",
    "listingParentClass": "",
    "useTraits": "",
    "listingUseTraits": "",
    "allowInherit": false,
    "allowVariants": false,
    "showVariants": false,
    "layoutDefinitions": {
        "name": "pimcore_root",
        "type": null,
        "region": null,
        "title": null,
        "width": 0,
        "height": 0,
        "collapsible": false,
        "collapsed": false,
        "bodyStyle": null,
        "datatype": "layout",
        "children": [
            {
                "name": "Layout",
                "type": null,
                "region": null,
                "title": "",
                "width": "",
                "height": "",
                "collapsible": false,
                "collapsed": false,
                "bodyStyle": "",
                "datatype": "layout",
                "children": [
                    {
                        "name": "localizedfields",
                        "title": "",
                        "tooltip": null,
                        "mandatory": false,
                        "noteditable": false,
                        "index": null,
                        "locked": false,
                        "style": null,
                        "permissions": null,
                        "fieldtype": "localizedfields",
                        "relationType": false,
                        "invisible": false,
                        "visibleGridView": true,
                        "visibleSearch": true,
                        "children": [
                            {
                                "name": "assets",
                                "title": "assets",
                                "tooltip": "",
                                "mandatory": false,
                                "noteditable": false,
                                "index": 0,
                                "locked": false,
                                "style": "",
                                "permissions": null,
                                "fieldtype": "manyToManyRelation",
                                "relationType": true,
                                "invisible": false,
                                "visibleGridView": false,
                                "visibleSearch": false,
                                "classes": [],
                                "displayMode": null,
                                "pathFormatterClass": "",
                                "maxItems": null,
                                "assetInlineDownloadAllowed": false,
                                "assetUploadPath": "",
                                "allowToClearRelation": true,
                                "objectsAllowed": false,
                                "assetsAllowed": true,
                                "assetTypes": [],
                                "documentsAllowed": false,
                                "documentTypes": [],
                                "enableTextSelection": false,
                                "width": "",
                                "height": "",
                                "datatype": "data"
                            }
                        ],
                        "region": null,
                        "layout": null,
                        "maxTabs": null,
                        "border": false,
                        "provideSplitView": false,
                        "tabPosition": "top",
                        "hideLabelsWhenTabsReached": null,
                        "permissionView": null,
                        "permissionEdit": null,
                        "labelWidth": 100,
                        "labelAlign": "left",
                        "datatype": "data"
                    }
                ],
                "locked": false,
                "fieldtype": "panel",
                "layout": null,
                "border": false,
                "icon": "",
                "labelWidth": 100,
                "labelAlign": "left"
            }
        ],
        "locked": false,
        "fieldtype": "panel",
        "layout": null,
        "border": false,
        "icon": null,
        "labelWidth": 100,
        "labelAlign": "left"
    },
    "icon": "",
    "group": "",
    "showAppLoggerTab": false,
    "linkGeneratorReference": "",
    "previewGeneratorReference": "",
    "compositeIndices": [],
    "showFieldLookup": false,
    "propertyVisibility": {
        "grid": {
            "id": true,
            "key": false,
            "path": true,
            "published": true,
            "modificationDate": true,
            "creationDate": true
        },
        "search": {
            "id": true,
            "key": false,
            "path": true,
            "published": true,
            "modificationDate": true,
            "creationDate": true
        }
    },
    "enableGridLocking": false
}
```

**Comment by fashxp** [comment]
@valentin- @turbo-ele  @ascheider  could please somebody of you guys check if https://github.com/pimcore/pimcore/pull/16545 solves the issue for you? 
thx very much!

**Comment by sevarozh** [comment]
> [@valentin-](https://github.com/valentin-) [@turbo-ele](https://github.com/turbo-ele) [@ascheider](https://github.com/ascheider) could please somebody of you guys check if [#16545](https://github.com/pimcore/pimcore/pull/16545) solves the issue for you? thx very much!

yes it is tested, this patch solves this problem, thanks

**Comment by ascheider** [comment]
@fashxp Works fine now.
