### ISSUE TITLE
[Bug]: LQIP are not loaded when img tag has a srcset attribute

### ISSUE THREAD

**Issue by Brainshaker95** [pimcore/pimcore#12045]
### Expected behavior

The srcset attribute should not be set, when lowQualityPlaceholder is set

### Actual behavior

The srcset attribute is set and so the lowQualityPlaceholder in the src attribute is ignored.

### Steps to reproduce

Add an image with the thumbnail configuration `lowQualityPlaceholder: true`

**Comment by fashxp** [comment]
@Brainshaker95  isn't that fixed already?

**Comment by brusch** [comment]
Yes, that got fixed.
