### ISSUE TITLE
Missing documentation for Tag & Snippet Management

### ISSUE THREAD

**Issue by kkarkus** [pimcore/pimcore#1205]
As title says, there's missing documantation for this feature (it can be found on old confluence doc) or I'm not able to find it.
Anyway I'd like to say something more what should be included in this documenation.
If you have malformed html like(and active at least one tag):
```
<input class="something" name="anyname" class="and again class" />
```
Tag & Snippet Management will remove name and second class attributes. In my opinion it's unwanted behaviour.

**Comment by brusch** [comment]
Tag & Snippet Mgmt. is a topic for our user documentation which is on our roadmap, but thanks anyway :)

**Comment by julmot** [comment]
I'm missing this documentation too – I'm curious why code will be inserted into areas where no Twig blocks are defined (like e.g. outside `pimcore_head_script()`)

**Comment by zwif** [comment]
Same here, we are loosing Tags/Snippets during deployment. Some documentation would be helpful!

**Comment by julmot** [comment]
@brusch Is this still on your roadmap?

**Comment by brusch** [comment]
@julmot the docs as a whole yes, but doesn't have priority at the moment.
