### ISSUE TITLE
[Bug]: \Pimcore\Model\Asset\Thumbnail\ImageThumbnailTrait::getDimensions is reading dimensions from file every time

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#12057]
### Expected behavior

With a remote storage, reading remote files just to find out the thumbnail width / height is suboptimal. The asset cache could cache these values.

### Actual behavior

The values are read from the file which is pulled from remote storage.

### Steps to reproduce

1. have a remote storage for thumbnails set up
2. call `\Pimcore\Twig\Extension\ImageThumbnailExtension::getImageThumbnailHtml`
3. `\Pimcore\Model\Asset\Thumbnail\ImageThumbnailTrait::readDimensionsFromFile` is triggered, which pulls the remote file and reads width / height directly from it

This also applies to filesize, maybe MIME type?

**Comment by brusch** [comment]
Sounds like a very good idea.
Mime-type should be fine as it is, as it doesn't require access to the file, it just uses the file extension see: 
https://github.com/pimcore/pimcore/blob/90a603647ae074be3b99b545b8246a4a59244fdd/models/Asset/Thumbnail/ImageThumbnailTrait.php#L274

But `width`, `height` and `filesize` makes sense. 
Would you create a PR for that? 😊

**Comment by dkarlovi** [comment]
@brusch do you have a rough idea when 10.5 will be released, I'll try to do it before.

**Comment by brusch** [comment]
@dkarlovi I don't expect it to be finished before mid of June - but of course the earlier we get the PR the better it is, as we also need some time for reviewing and testing 🤗

**Comment by dkarlovi** [comment]
Illustration of the problem, 80% of the runtime was spent on fetching width / height for 9 images on the page.
![Untitled-profile-Blackfire](https://user-images.githubusercontent.com/209225/167671998-230bc116-440c-4c44-9004-45075efedcfa.png)

**Comment by brusch** [comment]
@dkarlovi just wanted to let you know, that 10.5 is not that far away anymore - so the sooner we can get the PR, the better 😊 Thanks!

**Comment by dkarlovi** [comment]
OK I'll create it tomorrow first thing.

**Comment by dkarlovi** [comment]
@brusch working on this now, I notice the thumbnails could use a cache buster if you're serving them from remote storage.

One thing we did (on non-Pimcore projects) is hash all the inputs for the thumbnail (original image checksum, thumbnail config), hash that and use as part of the target thumbnail file name. This means that, whatever changes (thumbnail config, original image), you know if you're up to date just by the file existing or not (and also, free cache busting). Upside to this is you get to keep the old thumbnails in place if they're hard-linked somewhere and you can afford the storage, but can also bulk delete them (immediately or later) since you know which one is the actual one.

Pimcore should do something similar IMO.

**Comment by dkarlovi** [comment]
See https://github.com/pimcore/pimcore/pull/12414

**Comment by brusch** [comment]
@dkarlovi this would be a different topic then, but yes, would make sense 😊 You can put that into a different PR or issue. Thanks!

**Comment by dkarlovi** [comment]
@brusch created https://github.com/pimcore/pimcore/issues/12424
