### ISSUE TITLE
[Bug]: Composite indices failing to save for relation data type

### ISSUE THREAD

**Issue by SpicySpaceman** [pimcore/pimcore#12060]
### Expected behavior

It should be possible to also create composite indices on relation data types like Many-To-One.

### Actual behavior

Currently it is not possible to create such composite keys. An error message like ```An exception occurred while executing 'ALTER TABLE `object_query_test` ADD INDEX `c_test` (test1_id,test2_id);': SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'test1_id' doesn't exist in table``` appears.

The actual fields in the database are `test1_id__id` and `test2_id__id`. 

### Steps to reproduce

1. Create a new data object class.
2. Add two Many-To-One relations to the class.
3. Try to set a composite index on these fields.
4. Error message appears on saving.

Observed in 10.4.0 with MariaDB 10.7.3

**Comment by evanjamesjackson** [comment]
Note that a workaround for this issue is to simply type the name of the column (e.g. in the case above typing `test1_id__id` would have worked)

**Comment by fashxp** [comment]
fixed via #14015
