### ISSUE TITLE
[Bug]: getenv not returning variables defined in .env anymore (possible regression)

### ISSUE THREAD

**Issue by alexej-d** [pimcore/pimcore#12068]
### Expected behavior

getenv should return variables from .env- and .env.local files.

### Actual behavior

Calling getenv anywhere with a variable name of a variable that only exists in an env file returns false, even though $_ENV returns the correct value.

### Steps to reproduce

1. Add a line like this to your .env file: `NODE_ENV=development`
2. Call `getenv('NODE_ENV')` anywhere you like.
3. If NODE_ENV does not exist as a shell variable, the return value is false instead of `'development'`

I believe all versions of Pimcore 6 and early versions of Pimcore X would return a correct value in this situation.

Changing the prepareEnvVariables method in Pimcore\Bootsrap.php to this fixes the regression (notice the usePutenv):

```php
    private static function prepareEnvVariables()
    {
        (new Dotenv())->usePutenv()->bootEnv(PIMCORE_PROJECT_ROOT .'/.env');
    }
```

**Comment by brusch** [comment]
We're not using `usePutEnv()` because of the following reason: 

> If `putenv()` should be used to define environment variables or not. Beware that `putenv()` is not thread safe, that's why this setting defaults to false

So you should use either `$_ENV` or `$_SERVER` to access the values defined in `.env`.

**Comment by alexej-d** [comment]
That's fine with me, but is there any mention of it in the upgrade docs? As far as I am concerned this is a breaking change... @brusch

**Comment by brusch** [comment]
This has not changed within v10 as far as I've seen.

**Comment by alexej-d** [comment]
@brusch i had no problems using getenv in 10.2.6 the way I mentioned as far as I can tell. Today I tried Pimcore 10.4 for the first time and getenv's behaviour changed.

**Comment by brusch** [comment]
@alexej-d see status of `10.0.0`: https://github.com/pimcore/pimcore/blob/v10.0.0/lib/Bootstrap.php#L150

**Comment by alexej-d** [comment]
@brusch sorry, you are right, I used docker-compose for env management, that's why I did not notice the change from 6.9. Still, shouldn't that be mentioned in the upgrade notes for Pimcore X?
