### ISSUE TITLE
[Bug]: There is no active transaction when opening [Document] Link 

### ISSUE THREAD

**Issue by bitver** [pimcore/pimcore#12062]
### Expected behavior

Opened document

### Actual behavior

Getting error when trying to open link which refferes to Data Object
`Status: 500 | Internal Server Error
URL: /admin/link/get-data-by-id
Message: There is no active transaction.
Trace: 
in /var/www/*/vendor/doctrine/dbal/lib/Doctrine/DBAL/ConnectionException.php:23
#0 /var/www/*/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2001): Doctrine\DBAL\ConnectionException::noActiveTransaction()
#1 /var/www/*/vendor/symfony/property-access/PropertyAccessor.php(468): Doctrine\DBAL\Connection->isRollbackOnly()
#2 /var/www/*/vendor/symfony/property-access/PropertyAccessor.php(154): Symfony\Component\PropertyAccess\PropertyAccessor->readProperty()
#3 /var/www/*/vendor/symfony/serializer/Normalizer/ObjectNormalizer.php(140): Symfony\Component\PropertyAccess\PropertyAccessor->getValue()
#4 /var/www/*/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(181): Symfony\Component\Serializer\Normalizer\ObjectNormalizer->getAttributeValue()
#5 /var/www/*/vendor/symfony/serializer/Serializer.php(161): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize()
#6 /var/www/*/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(215): Symfony\Component\Serializer\Serializer->normalize()
#7 /var/www/*/vendor/symfony/serializer/Serializer.php(161): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize()
#8 /var/www/*/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(215): Symfony\Component\Serializer\Serializer->normalize()
#9 /var/www/*/vendor/symfony/serializer/Serializer.php(161): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize()
#10 /var/www/*/vendor/symfony/serializer/Serializer.php(179): Symfony\Component\Serializer\Serializer->normalize()
#11 /var/www/*/vendor/symfony/serializer/Serializer.php(179): Symfony\Component\Serializer\Serializer->normalize()
#12 /var/www/*/vendor/symfony/serializer/Serializer.php(134): Symfony\Component\Serializer\Serializer->normalize()
#13 /var/www/*/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/LinkController.php(62): Symfony\Component\Serializer\Serializer->serialize()
#14 /var/www/*/vendor/symfony/http-kernel/HttpKernel.php(152): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\LinkController->getDataByIdAction()
#15 /var/www/*/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#16 /var/www/*/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle()
#17 /var/www/*/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle()
#18 {main}`

### Steps to reproduce

- Create link
- Drag n drop DataObject to Path attribute
- Close link
- Reopen link
- error

**Comment by aryaantony92** [comment]
@bitver  I just reproduced the mentioned scenario. 
i.e I have 

1. Created a Link
2. Dragged a DataObject to the path attribute.
3. Closed the Link
4. Reopened the Link

But I didn't get the error. And the link was opened.

Could you please tell me whether there are any special cases for the test ?

**Comment by bitver** [comment]
@aryaantony92 It's very strange and I can't reproduce issue locally, but getting error stabely on production server.
`vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/LinkController.php:61`
if I add `$link->setProperties(null);` in line 61 then issue is gone.

Could you help me, How can I figure out what the problem is when `$link` object in server suddenly has `$properties` while locally it has not? I think it depends on pimcore.
All I have done in code in total - changed some templates and Objects in pimcore/demo app. So I didn't change any bundles and didn't apply any patches or whatever.

**Comment by bitver** [comment]
Issue has gone with [10.4.1]. Idk what issue was related.
Can be closed, thanks a lot.
