### ISSUE TITLE
Add workflow state information, like the status

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1207]
Actually "state" information is not visible directly (but we can choose a color). But status is visible.
Maybe the state could be added before the status.

![state](https://cloud.githubusercontent.com/assets/9025839/22170928/d4b2a4be-df84-11e6-9d8a-a4c988dbb1c6.png)

For the exemple in documentation, it will make for instance: `| Done | Accepted product |` or `| In progress | Check the quantity and price |`

**Comment by Yivan** [comment]
I just understand that state are symbolized by the color. So if we not add it like showed just before on the image exemple, maybe the state label could be show as tooltip on the hover at least ?
Another option, is to add it on the same place: "Accepted product (Done)" for instance.

**Comment by brusch** [comment]
Should be obsolete with #3288 

State is shown on hover: 
![image](https://user-images.githubusercontent.com/142037/52060946-9734e580-256d-11e9-98cf-5022abc1ea19.png)
