### ISSUE TITLE
[Bug]: \Pimcore\Translation\Translator doesn't implement \Symfony\Component\HttpKernel\CacheWarmer\WarmableInterface

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#12087]
### Expected behavior

Since the Pimcore translator decorates Symfony's Translator, it should at least proxy its `warmUp()` process to ensure the translations get warmed up when Symfony's cache is being warmed.

### Actual behavior

Translations are not warmed with the rest of the cache.

### Steps to reproduce

Run `bin/console cache:warmup -e prod`, you should have `var/cache/prod/translations`, but there's not one.

Caused by a type check in `\Symfony\Bundle\FrameworkBundle\CacheWarmer\TranslationsCacheWarmer::warmUp` which skips the Pimcore Translator since it's not warmable.

**Comment by aryaantony92** [comment]
Fixed by #12197
