### ISSUE TITLE
[Bug]: Some image thumbnail transformations no longer work

### ISSUE THREAD

**Issue by GAL-GC** [pimcore/pimcore#12086]
### Expected behavior

When i define a thumbnail configuration for my image, some transformations no longer work. 

For example, I create a new thumbnail, with a transformation "Cover" and define their the specific configuration. As soon as I save and deliver the asset with my thumbnail configuration to the frontend, I get an `image-thumb__1__thumbnail/myasset.png` path for example. The path is the compressed image path.

### Actual behavior

When I change the transformation mode now to "Scale by Height" for example, this no longer works. Suddenly I no longer get the image thumbnail path, instead I receive the original asset path. So the configuration and compression no longer works. I tested it with a few others and they aren't working too. Cover mode seems to work fine, as in previous versions.

### Steps to reproduce

- Create an image thumbnail
- Choose Cover Transformation
- Render to frontend, you'll see correct compressed path
- Chance to scaleByHeight Transformation
- You'll no longer get a compressed path, instead you'll get the unchanged original asset path

**Comment by mcop1** [comment]
@GAL-GC sorry, I am not able to reproduce the issue. I created 3 thumbnail configurations (cover, grayscale, scalebyheight) and called getThumbNail for each of them in a controller action:

```
        $image = Asset::getById(410);
        $pathToThumbnail = $image->getThumbnail("CoverTransformation");
        $pathToThumbnail2 = $image->getThumbnail("GrayScale");
        $pathToThumbnail3 = $image->getThumbnail("ScaleByHeight");

        return new Response($pathToThumbnail . " <br/> " . $pathToThumbnail2 . " <br/> " . $pathToThumbnail3);
```

This returns the following:
![image](https://user-images.githubusercontent.com/89011527/169267367-a18571bf-7bdb-40c7-88bb-9b5c388bd53a.png)

When I open one of the urls the corresponding thumbnail gets displayed. 
Did I get something wrong?

**Comment by fashxp** [comment]
related? https://github.com/pimcore/pimcore/issues/12117

**Comment by mcop1** [comment]
Closed due to inactivity, feel free to reopen the issue if needed.
