### ISSUE TITLE
[Docs] Ecommerce framework yaml not working

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12082]
### Discussed in https://github.com/pimcore/pimcore/discussions/12001

<div type='discussions-op-text'>

<sup>Originally posted by **langert** April 28, 2022</sup>
Is there a working example for ecommerce framework?

Using 
bin/console config:dump-reference pimcore_ecommerce_framework
generates a yaml that causes different errors:

`noShipping:          { price_calculator: { factory_id: PriceCalculatorFactory, modificators: '~' } }`
=> error on array to string conversion

```
# Placeholder values in this tenant attributes definition (locale: "%%locale%%") will be replaced by the given placeholder value (eg. "de_AT")
placeholders:

  # Example:
  placeholders:        { '%%locale%%': de_AT }
```

=> error (placeholder key is doubled)

```
token_managers: 
 name: ~
```
=> error (should not be null) - same for pricing_manager ...

What is the correct way to get a working example in a blank pimcore installation?

Thx, Timo</div>

**Comment by dvesh3** [comment]
Fixed by #12148
