### ISSUE TITLE
[Bug]: Cannot save user settings / OPCache error

### ISSUE THREAD

**Issue by alexmf23** [pimcore/pimcore#12098]
### Expected behavior

I wanted to create a new user but couldnt set password nor save settings.

### Actual behavior

I create the user, I set a password ( i get Save. successfully ) but the user password wont set. ( If i use CLI to reset password for the created user than it works - using cli )

Also I see now that in PHP OPcache Status i get an error:
<img width="1900" alt="Screenshot 2022-05-11 at 15 55 29" src="https://user-images.githubusercontent.com/63473281/167866994-85716397-97bc-4dee-83af-7c770d59c88b.png">
.

### Steps to reproduce

Pimcore Version: v10.4.0
Plesk centOS Server

**Comment by blankse** [comment]
Should be fixed in 10.4.1
