### ISSUE TITLE
[Task]: Move specific functionalities into bundles to keep the core leaner

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#12094]
| Functionality     | Package Name                    | Notes                                          | Own Git Repo / Package |  
|-------------------|---------------------------------|------------------------------------------------| ---- | 
| Custom Reports  | pimcore/custom-reports-bundle   |                                                | ❌  
| Glossary          | pimcore/glossary-bundle         |                                                | ❌ 
| SEO               | pimcore/seo-bundle              | redirects, robots.txt, SEO Editor, HTTP Errors, Sitemap | ❌ 
| ~~System Info~~   | [pimcore/system-info-bundle](https://github.com/pimcore/system-info-bundle)      | PHP info, OpCache status                       | ✅ | 
| ~~File Explorer~~     | [pimcore/file-explorer-bundle](https://github.com/pimcore/file-explorer-bundle)    |                                                | ✅ | ✅ |
| Word Export    | pimcore/word-export-bundle      |                                                |❌ | 
| ~~Personalization~~ | [pimcore/personalization-bundle](https://github.com/pimcore/personalization-bundle)  | personalization and targeting                  |✅ | 
| ~~Google Marketing~~  | [pimcore/google-marketing-bundle](https://github.com/pimcore/google-marketing-bundle) | Everything in "Marketing Settings"             | ✅ | 
| ~~Web-to-print~~      | [pimcore/web-to-print-bundle](https://github.com/pimcore/web-to-print-bundle)     |                                                | ✅ |   
| ~~Ecommerce~~         | [pimcore/ecommerce-framework-bundle](https://github.com/pimcore/ecommerce-framework-bundle)        |                                                | ✅ | 
| Static Routes | pimcore/static-routes-bundle        |                                                |❌ | 
| Simple Backend Search | pimcore/simple-backend-search-bundle        |                                                |❌ | 
| XLIFF | pimcore/xliff-bundle        |                                                |❌ | 
| Application Logger | pimcore/application-logger-bundle        |                                                |❌ | 
| ~~Admin UI Classic~~ | [pimcore/admin-ui-classic-bundle](https://github.com/pimcore/admin-ui-classic-bundle)        |                                                | 
| UUID | pimcore/uuid-bundle | | ❌ | 
| ~~Newsletter~~ | [pimcore/newsletter-bundle](https://github.com/pimcore/newsletter-bundle) | | ✅ | 

Tasks: 
- [x] https://github.com/pimcore/pimcore/issues/12516
- [x] https://github.com/pimcore/pimcore/issues/12517
- [x] https://github.com/pimcore/pimcore/issues/12518
- [x] https://github.com/pimcore/pimcore/issues/12519
- [x] https://github.com/pimcore/pimcore/issues/12521
- [x] https://github.com/pimcore/pimcore/issues/12522
- [x] https://github.com/pimcore/pimcore/issues/12523
- [x] https://github.com/pimcore/pimcore/issues/12524
- [x] https://github.com/pimcore/pimcore/issues/12525
- [x] https://github.com/pimcore/pimcore/issues/12526
- [x] https://github.com/pimcore/pimcore/issues/12527
- [x] https://github.com/pimcore/pimcore/issues/12528
- [x] https://github.com/pimcore/pimcore/issues/12529
- [x] https://github.com/pimcore/pimcore/issues/12530
- [x] https://github.com/pimcore/pimcore/issues/12531
- [x] https://github.com/pimcore/pimcore/issues/12532
- [x] https://github.com/pimcore/pimcore/issues/12533
- [x] https://github.com/pimcore/pimcore/issues/14260
- [x] https://github.com/pimcore/pimcore/issues/14802

Also consider #9357 for each functionality

**Comment by dkarlovi** [comment]
Related #11105.

**Comment by passioneight** [comment]
@brusch will the bundles stay open source?

**Comment by brusch** [comment]
@passioneight yes, of course. This task is just about restructuring and possibly also about priorities, but not about licensing 😊

**Comment by NiklasBr** [comment]
Regarding `pimcore/web-to-print-bundle`, [wkhtmltopdf is no longer being maintained](https://wkhtmltopdf.org/status.html), maybe it should be deprecated and removed in 11?

**Comment by brusch** [comment]
@NiklasBr thanks for the hint, you're right, that should be deprecated, no reason to further support an unmaintained product.

**Comment by brusch** [comment]
See #12431

**Comment by jdreesen** [comment]
Pimcore will still be a monorepo-right? Cause the issues you created read like the code will actually be *moved* to independent repos, instead of creating subtree splits of this monorepo.

**Comment by brusch** [comment]
@jdreesen this is not yet finally decided, but currently our favorite is to separate them out into their own repos. There are multiple reasons for that, mostly organizational wise, e.g. this gives us a better control over permissions and responsibilities. Of course we also know about the drawbacks, but as we're currently only talking about additional features, which are not essential core features such as data objects, I think it would be still reasonable.

**Comment by dkarlovi** [comment]
IMO, the value of having it be a mono-repo heavily outweighs the drawbacks. Symfony proved the mono-repo approach works on a huge scale, I don't see why it would work for Pimcore.

Managing many repos, keeping their settings, tags, GH actions etc in sync, making cross-cutting PRs, doing releases in sync will be a huge PITA otherwise.

**Comment by dpfaffenbauer** [comment]
CoreShop also successfully uses the mono-repo approach and works flawless. Makes development a lot easier

**Comment by brusch** [comment]
Strategy is as follows: 

1. bundles which will be a community bundle in future, will be moved to their own repos / packages
2. functionality / bundles that are going to be replaced in future should also be in a separate repo (e.g. Classic Admin UI) 
3. smaller commonly used functionalities will be extracted into bundles, but remain in the core repo. They are not provided as their own packages via Composer, when using them you just need to enable them in `bundles.php`.
