### ISSUE TITLE
[Bug]: Shared Translations in admin mode not opening

### ISSUE THREAD

**Issue by tom2796** [pimcore/pimcore#12096]
### Expected behavior

The shared translations in the admin mode are opening as usual.

### Actual behavior

Pop up opens, with error message, that translations are not configuared. 
![image](https://user-images.githubusercontent.com/105366530/167857337-7f3a4d75-51d8-4b99-a736-7a497e0def34.png)

Further a console error appears: 
_Error: Duplicate component id "translation_column_website_de"_
![image](https://user-images.githubusercontent.com/105366530/167859951-04472355-1121-490c-a8c3-68006818c45c.png)

### Steps to reproduce

I am using Pimcore 10.2.10

The error only occures when the user has a role assigned, where all permissons for all languages are set
![image](https://user-images.githubusercontent.com/105366530/167857664-cd646678-b402-41d3-8b78-3c0107bd10ed.png)

and in the user settings not all translations are selected: 
![image](https://user-images.githubusercontent.com/105366530/167857841-0c8646f8-e5cf-4dd6-87ba-820f41c03176.png)

In the user I have assigned following permissions: 
Admin Translations, Bundles, Clear Cache, Document Types, Documents, Emails, Glossary, Notifications, Objects, Recycle Bin Redirects, Send Notifications, Translations, Users

In the Role following permissions are assigned: 
Admin Translations, ApplicationLogger, Asset Metadata, AssetsBundles, Bundles, Classes, Clear Cache, Dashboards, Document Types, Documents, Emails, Glossary, Notes & Events, Notifications, Objects, Recycle Bin Redirects, Predefined Properties, Send Notifications, System Settings, Tags Assignment, Tags Configuration, Tags Search, Targeting, Thumbnails, Translations, Users, Website Settings

I could produce the error with german and english assigned to the users as backend language. 

When I allow the user to see all languages in the shared translation settings, it works as usual

**Comment by aryaantony92** [comment]
Fixed by #12139
