### ISSUE TITLE
[Bug]: Variants tab is empty

### ISSUE THREAD

**Issue by mhgtlc** [pimcore/pimcore#12107]
### Expected behavior

POST request to `/admin/variants/get-variants` does return results

### Actual behavior

POST request to `/admin/variants/get-variants` does not return results

### Steps to reproduce
Pimcore 10.4.1

1. Add variant for an object
2. Variant is created
3. Open variants tab of parent object
4. No variant is shown

**Comment by aryaantony92** [comment]
Fixed by #12169
