### ISSUE TITLE
WYSIWYG - impossible to remove toolbar Groups

### ISSUE THREAD

**Issue by zoransalamun** [pimcore/pimcore#1210]
Hi, in older version we were able to add custom editor configuration (and replace default) on class for example. Since last update (to 4.4.1) that is impossible due changes in script:
pimcore/static6/js/pimcore/object/tags/wysiwyg.js

Old code (line 154):
`       if(this.fieldConfig.toolbarConfig) {
            eConfig.toolbarGroups = Ext.decode("[" + this.fieldConfig.toolbarConfig + "]")
        }`

New code:
```
 if(this.fieldConfig.toolbarConfig) {
            var elementCustomConfig = Ext.decode(this.fieldConfig.toolbarConfig);
            eConfig = mergeObject(eConfig, elementCustomConfig);

        }

```
As you can see now configuration is merged and there is no solution to remove any toolbar part. By looking at ckeditor documentation only solution to remove group is to add to ckeditor configuration list - "removeButton", for example:
`config.removeButtons = 'Underline,Subscript,Superscript';`

**Can you improve system** with new field in WYSIWYG data component configuration so we can enter buttons to remove, or to make logic like before (replace instead of merge)?

Thank you

**Comment by brusch** [comment]
rtfm :)  https://www.pimcore.org/docs/latest/Objects/Object_Classes/Data_Types/Text_Types.html#page_Editor_Configuration 

```
{
    toolbarGroups : [ { name: 'links' }]
}
```

![image](https://cloud.githubusercontent.com/assets/142037/22364224/334ca11a-e470-11e6-9b7f-bd9b895048d1.png)

results in: 

![image](https://cloud.githubusercontent.com/assets/142037/22364233/3f8c4444-e470-11e6-8af8-730119e7c3eb.png)
