### ISSUE TITLE
[Bug]: Cleanup FC and Bricks Stores on lower-case DB Servers

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#12101]
Pimcore's cleanup tasks checks for tables like 'object_collection_%' and 'object_brick_%',  extrudes the brick/collection name from that and checks if the brick/collection in Pimcore exists. That doesn't work with Database Servers that are lower-case by default. Pimcore then logs "Fieldcollection 'coreshoptaxitem' not found. Please check table object_collection_coreshoptaxitem_cs_order_item".

Pimcore should rather ignore the case for this task.

**Comment by mcop1** [comment]
I would suggest the following:

1.) Add a new method `Classdefinition\Dao::getNameByIdIgnoreCase()`, which executes the corresponding SQL statement with table and id in lower case.
2.) Add a new method `ClassDefinition::getNameByIdIgnoreCase()`, which calls the method mentioned in 1.). But this method **won´t** add the ClassDefinition to the runtime cache.
3.) Substitute `ClassDefinition::getNameById()` with `ClassDefinition::getNameByIdIgnoreCase()` in: 

```
CleanupClassificationstoreTablesTask
CleanupBrickTablesTask
CleanupFieldcollectionTablesTask
```

What do you guys think @dpfaffenbauer, @fashxp ?
