### ISSUE TITLE
[Bug]: getImageThumbnail doesn't work for documents (PDF etc.) if no thumbnail name is given but thumbnail config

### ISSUE THREAD

**Issue by akno77** [pimcore/pimcore#12117]
### Expected behavior

Calling Method pdfAsset.getImageThumbnail() in Twig with no thumnail name given, but thumbnail config retuns the PDF Thumbnail:

`{{ pdfAsset.getImageThumbnail({height: 290}) }}`

### Actual behavior

The return value is empty. This worked before one of the last updates....

### Steps to reproduce

Call getImageThumbnail on a PDF asset with thumbnail width/height config given.

**Comment by brusch** [comment]
The processing is done in the background, please ensure your maintenance cron is running correctly.

**Comment by akno77** [comment]
@brusch The cron/supervisor is setup and image thumbnails work. But only document thumbnails not...

**Comment by akno77** [comment]
In the backend asset list the document thumbnails are generated

**Comment by fashxp** [comment]
just tested it on the demo based on our docker images ... works for me.

**Comment by fashxp** [comment]
if problem still persists on your end, would be great if you can debug it further and provide more information or even a PR. 

thx...

**Comment by akno77** [comment]
@fashxp Did you test it with explizit height property?

`{{ pdfAsset.getImageThumbnail({height: 290}) }}`

This doesn't work for me. If I pass a Thumbnail Config name it works.

**Comment by fashxp** [comment]
yes I did. 

![image](https://user-images.githubusercontent.com/8792145/170028130-b5a0e407-8fd7-445a-a7e7-d4da21ad58d6.png)
