### ISSUE TITLE
[Bug]: Login as user does not work with custom entrypoint

### ISSUE THREAD

**Issue by matthiashamacher** [pimcore/pimcore#12111]
### Expected behavior

When copying the login as user link and opening the link in a new browser, you should be login as that user regardless of the admin entry point

### Actual behavior

If you have configured a custom admin entry point you get a 404 error as you cannot access the /admin route without being redirected from the custom entry point route

### Steps to reproduce

1. Configure a custom admin entry point as described here: https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Custom_Admin_Login_Entry_Point.html
2. Create a second test user and click on "Login as this user in a different browser"
3. Open the copied URL in a new browser

It seems that replacing /admin/login/login with the custom entry point (i.e. /myadmin) works for custom entry points, but trying to do that by removing /login/login so you only have the default admin entry point (/admin) does not work.

**Comment by matthiashamacher** [comment]
I found the issue. It already works if you name the route for the custom entry point "my_custom_admin_entry_point" https://github.com/pimcore/pimcore/blob/10.x/bundles/AdminBundle/Controller/Admin/UserController.php#L1242
As our route was named "custom_admin_entry_point" it did not match and the fallback with /admin/login/login was used.

I think we have two possibilities to fix this:
1. Add a configuration to let the user define the route name which should be used
2. Clarify that the route must be named "my_custom_admin_entry_point" so the current use case works

I also suggest removing "my_" from the route name.

Personally, I prefer option 1 as this isn't so fixed.

@dvesh3 @fashxp How about you? I'm happy to implement the changes.

**Comment by fashxp** [comment]
I vote for 1) (with a default value to `my_custom_admin_entry_point`)

**Comment by dvesh3** [comment]
Fixed by #12202
