### ISSUE TITLE
Add method to get  'pretty' value, not just data from Select

### ISSUE THREAD

**Issue by zzarazza** [pimcore/pimcore#1212]
This is a screenshot of official documentation:
<img width="400" alt="screenshot 2017-01-24 12 07 16" src="https://cloud.githubusercontent.com/assets/1878488/22240817/b00fc10e-e22d-11e6-84e0-e05a8250abed.png">

I want to be able to get a pretty **"Three months"** as a value of the dropdown in the frontend in addition to the actual data of "three-months" which I get with getData().

**Comment by weisswurstkanone** [comment]
You can use the helper method from the Service class as follows:

        $object = \Pimcore\Model\Object\Concrete::getById(52);
        $options = \Pimcore\Model\Object\Service::getOptionsForSelectField($object, "myselectfield");
        var_dump($options);

Output will be something like:

/home/pimcore/www/website/controllers/TestController.php:12:
array (size=2)
  2 => string 'name2' (length=5)
  1 => string 'name1' (length=5)

**Comment by weisswurstkanone** [comment]
![image](https://cloud.githubusercontent.com/assets/6142086/22241177/9b460efe-e21e-11e6-90f8-25fa414a9401.png)

**Comment by zzarazza** [comment]
I'm using that in the document in the Admin, not on object. 

Like this:
<img width="554" alt="screenshot 2017-01-24 12 33 50" src="https://cloud.githubusercontent.com/assets/1878488/22241667/691b5764-e231-11e6-975f-47672280f7cb.png">

**Comment by brusch** [comment]
@zzarazza 
If you'd like to have label=value you can use the following simple configuration: 
```php 
<?= $this->select("valid_for", [
        "store" => ['One month', 'Three months', 'Unlimited']
    ]);
?>
```

Getting the label for a certain value like: 
`$this->select("mySelect")->getSelectedLabel()` wouldn't work, because the configuration of an editable isn't stored anywhere, this information is just in your template as an PHP array, so you'd have to do something like: 

```php 
<?php

$values = [
    'one-month' => 'One month',
    'three-months' => 'Three months',
    'unlimited' => 'Unlimited'
];

$storeValues = [];
foreach($values as $key => $value) {
    $storeValues[] = [$key, $value];
}

if($this->editmode) {
    echo $this->select("valid_for", [
        "store" => $storeValues
    ]);
} else {
    echo $values[$this->select("valid_for")->getData()];
}

?>
```
