### ISSUE TITLE
[Feature]: Search Documents: Search within Site

### ISSUE THREAD

**Issue by puecher** [pimcore/pimcore#12129]
### Feature description

Working with Sites it could be useful to add a dropdown near "All Types" like "All Sites" where you can search within a Site.

For example:

![grafik](https://user-images.githubusercontent.com/3795812/168582431-55e3c367-55fc-4bc1-a5ee-b6d119541add.png)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
