### ISSUE TITLE
[Bug]: User - not possible to update password anymore in Admin Interface

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#12138]
### Expected behavior

User password should be updated

### Actual behavior

User password not updated

### Steps to reproduce

- Add new user or open existing user.
- Set new password
- Save User
- Use new password to login

**Comment by dvesh3** [comment]
Regression of #11961

**Comment by blankse** [comment]
Should be already fixed in 10.4.1
See https://github.com/pimcore/pimcore/issues/12024 and https://github.com/pimcore/pimcore/pull/12026

**Comment by dvesh3** [comment]
> Should be already fixed in 10.4.1 See #12024 and #12026

yes, you are right. thanks!
