### ISSUE TITLE
[Bug]: Loading problem, potentially FOSjJsRouting

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#12165]
### Discussed in https://github.com/pimcore/pimcore/discussions/12122

<div type='discussions-op-text'>

<sup>Originally posted by **Hbitvof** May 15, 2022</sup>
Hi,

I have a strange issue that occured after updating from 6.9 to 10.x. Every day when first starting Pimcore the site is not loading, after refreshing Pimcore is loading.

The first time I get these errors:

![image](https://user-images.githubusercontent.com/41229269/168468071-bed5b269-95c8-4d88-abf5-5907dbd05373.png)

There is also a warning about an expired cookie:

Cookie “_pc_tvs” has been rejected because it is already expired.

I already cleared all browser cache, but this is not solving the problem. Is this a known issue and what can I do to solve this?</div>

**Comment by kingjia90** [comment]
I am also facing this problem, it would be gone by just reloading again, so i have no idea on how to reproduce it but it seem happening on the first time loading the page.

![image](https://user-images.githubusercontent.com/6014195/169260841-45f8c276-1280-469d-a1ac-d081f0f12190.png)

**Comment by kingjia90** [comment]
I was able to reproduce the same JS error by making `expose` to false, https://github.com/pimcore/pimcore/blob/01e01e6da5cf9baf910a7832e930dec941a4253f/bundles/AdminBundle/Resources/config/pimcore/routing.yaml#L34

so my first guess would be that there' some problem loading the routing.yaml only under certain "first time loading" circumstances where the cache is not warmed up

**Comment by Hbitvof** [comment]
Any update on this problem? It's getting pretty annoying to refresh every time starting PIM.

**Comment by kingjia90** [comment]
@Hbitvof unfortunately, this problem cannot be easily reproduced, that must be something in your local.
I have now noticed that you have "I don't care about cookies" [plugin](https://addons.mozilla.org/de/firefox/addon/i-dont-care-about-cookies/) active and the error appears on GDPR related, Could you try to disable that browser plugin and try again next time starting PIM?

**Comment by Hbitvof** [comment]
> @Hbitvof unfortunately, this problem cannot be easily reproduced, that must be something in your local. I have now noticed that you have "I don't care about cookies" [plugin](https://addons.mozilla.org/de/firefox/addon/i-dont-care-about-cookies/) active and the error appears on GDPR related, Could you try to disable that browser plugin and try again next time starting PIM?

I don't have that plugin active. That plugin is called Cookie Editor. Also in other browsers without any plugin I have this issue related to PIM.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
