### ISSUE TITLE
[Bug]: new static() in abstract class

### ISSUE THREAD

**Issue by olifrieda** [pimcore/pimcore#12160]
### Expected behavior

`$printDocument = Document\PrintAbstract::getById((int) $request->get('id'));` ends up with a valid object assigned.

### Actual behavior

Status check for PDF generate returns an error.

### Steps to reproduce

Generate a PDF using the web2print default controller. The process will be started but the status check returns an error at the end, that it is not possible to instantiate a abstract class.

See e. g. vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php:263 or vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php:230

The error is thrown here: vendor/pimcore/pimcore/models/Document.php:300

`$document = new Document();` has been changed from **10.4.0** to **10.4.1** into `$document = new static();`

**Comment by blankse** [comment]
@olifrieda Is fixed in https://github.com/pimcore/pimcore/pull/12104

**Comment by olifrieda** [comment]
@blankse ... but not released yet. So it is still there. Thank you for reporting.

**Comment by dvesh3** [comment]
Fixed by #12104
