### ISSUE TITLE
[Bug]: Admin cannot delete Translation Key

### ISSUE THREAD

**Issue by dmaerzendorfer** [pimcore/pimcore#12166]
### Expected behavior

A user with admin privileges can do everything. Including deleting Translation Keys.

### Actual behavior

A user with admin privileges is not able to delete Translation Keys.

### Steps to reproduce

https://user-images.githubusercontent.com/19265816/169284186-cd647742-17d9-4e1a-bc81-5f076b274092.mp4

If a user has a role assigned which limits the access to the shared translation columns he is not able to delete keys.

After the user gets admin priviliges the does see all the translation columns, however he still cannot delete keys.

**Comment by antonio-masotti** [comment]
I don't quite get the problem:

- your user is not an admin as the title here suggests
- if the user has permissions over the translations, he can (at least in Pimcore 10.4.1 where I tested) delete the translations. This user is not an admin for example but has the permission to modify the translations:

![image](https://user-images.githubusercontent.com/91308510/169556201-3254e36b-3369-4231-8be8-f150f68bdd99.png)


In your case is not working - I suppose  - because you didn't selected all the languages (French is missing). Now imagine you delete a translation key: if this user doesn't have permission for a given language, than it's totally fine that he cannot delete the key, otherwise he would also delete the translation for a language he's not supposed to be able to modify.

**Comment by dmaerzendorfer** [comment]
Yes, at first the user was not an admin.

I just gave him permissions to view German and English translations. This worked as intended, his view was limited and he could not delete any keys.

However, afterwards I gave the user admin privileges. Then the "shared Translations" Section in the user-settings also vanished (since its not needed, he sees everything anyway?). On logging in with the now admin user, he could also see all three Languages (German, English, French), just as intended. 
Though, he still could not delete any Keys. Why is that? Apparently the user has the permission to see all languages? Why can't he delete keys then?

**Comment by robertSt7** [comment]
I can't reproduce the bug.
Could you please provide more information or have a look into the debbuger?

**Comment by dmaerzendorfer** [comment]
Have a look at the video, it includes all the steps.

However, here is a written guide to reproduce the bug:
1. create a new role
    a) give this role "Translations" permissions
    b) limit the "Shared Translation Settings" to only one language (view+edit)
2. create a new user
    a) assign the earlier role to the user and save it
    b) give the user admin privileges and save it again
3. login as the user and check the translations. The user should now see all the languages but won't be able to delete any keys.

Hope this clarifies the scenario. What debugger info would help you in this case?

**Comment by robertSt7** [comment]
When I do these 3 steps, I am able to delete keys.

`        if (this.domain === 'admin' || pimcore.settings.websiteLanguages.length == this.editableLanguages.length) {
            typesColumns.push({
                xtype: 'actioncolumn',
                menuText: t('delete'),
                width: 30,
                items: [{
                    tooltip: t('delete'),
                    icon: "/bundles/pimcoreadmin/img/flat-color-icons/delete.svg",
                    handler: function (grid, rowIndex) {
                        grid.getStore().removeAt(rowIndex);
                    }.bind(this)
                }]
            });
        }`

Could you maybe try to debug these lines of code from https://github.com/pimcore/pimcore/blob/10.x/bundles/AdminBundle/Resources/public/js/pimcore/settings/translation.js#L306 ?

**Comment by dmaerzendorfer** [comment]
Hey, so the project in which this bug originally occurred is Pimcore Version v10.2.9 so the Code for this differs a bit.

Here is what I found though:

` if (pimcore.settings.websiteLanguages.length == this.editableLanguages.length || this.translationType === 'admin') {
            typesColumns.push({
                xtype: 'actioncolumn',
                menuText: t('delete'),
                width: 30,
                items: [{
                    tooltip: t('delete'),
                    icon: "/bundles/pimcoreadmin/img/flat-color-icons/delete.svg",
                    handler: function (grid, rowIndex) {
                        grid.getStore().removeAt(rowIndex);
                    }.bind(this)
                }]
            });
        }` 
pimcore.settings.websiteLanguages.length evaluates to 8; this.editableLanguages.length to 0;
this.translationType is 'website'

However, when I tested this on https://demo.pimcore.fun/admin (10.4.x-dev) I could recreate the bug.

**Comment by robertSt7** [comment]
Hi, sorry, but I also can't reproduce the bug on the demo app. Maybe you can tell me what I do differently with this video:

https://user-images.githubusercontent.com/104770750/171564883-22673e11-a60e-418a-881b-36f92eb94da8.mp4

**Comment by dmaerzendorfer** [comment]
Hello there!

After watching your video and following your steps myself I noticed something. The Delete-Option is visible for the admin section of the Translations but not for the message section! Perhaps this has something to do with it?
![image](https://user-images.githubusercontent.com/19265816/171798835-72855f40-4a09-4c1a-80af-228f32bb4d74.png)
