### ISSUE TITLE
[Bug]: Backend DataObject and Asset Export with multiple Pods (Kubernetes)

### ISSUE THREAD

**Issue by breakone** [pimcore/pimcore#12174]
### Expected behavior

Use File Storage for exports of [DataObjects](https://github.com/pimcore/pimcore/blob/10.x/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php) and [Assets](https://github.com/pimcore/pimcore/blob/10.x/bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php) via backend grid view to get a **full** export of a list.

### Actual behavior

The `PIMCORE_SYSTEM_TEMP_DIRECTORY` is used to get the temp directory for saving csv files. So if exports are chunked to multiple jobs, only the export file filled by the last job is returned if a stateless environment is used.

### Steps to reproduce

The `PIMCORE_SYSTEM_TEMP_DIRECTORY` is used to get the temp directory for saving csv files in e.g. [DataObjectHelperController](https://github.com/pimcore/pimcore/blob/fc12de487cd0153736e9c55d90438f8fb5cf2b25/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php#L1290)

```
protected function getCsvFile($fileHandle)
{
    return PIMCORE_SYSTEM_TEMP_DIRECTORY . '/' . $fileHandle . '.csv';
}
```

So because of chunking the export file `$jobs = array_chunk($ids, 20);` in [DataObjectHelperController](https://github.com/pimcore/pimcore/blob/fc12de487cd0153736e9c55d90438f8fb5cf2b25/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php#L1321), in a **stateless environment**, the file may not exist, if the export is chunked to multiple jobs:

`$fp = fopen($this->getCsvFile($fileHandle), 'a');`

So the configured [File Storage](https://pimcore.com/docs/pimcore/10.0/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/File_Storage_Setup.html) should be used instead.

**Comment by kingjia90** [comment]
What about instead adding the `FILE_APPEND` flag to [file_put_contents](https://www.php.net/manual/en/function.file-put-contents.php)? 
It seems that the exported file contains only the last job because it somehow overwritten and missed/ignored existing data. Unfortunately, i am unable to quickly replicate a stateless enviroment, could you please give it a quick try?
