### ISSUE TITLE
[Bug]: Disable unsaved content warning no working

### ISSUE THREAD

**Issue by PGBrandi** [pimcore/pimcore#12176]
### Expected behavior

When the box is not checked it should alert the user if there are not saved changes when closing the tab.

### Actual behavior

It just saves the content and closes the tab.

### Steps to reproduce

- Uncheck "Disable unsaved content warning"
- Save user
- Change something in a document
- Close the tab without saving
- It just saves the content without asking first
![image](https://user-images.githubusercontent.com/24474378/169506441-caab35f1-cfc0-4990-a1ba-f77122534e0a.png)

**Comment by dvesh3** [comment]
It happens because you have [Auto Save](https://pimcore.com/docs/pimcore/current/Development_Documentation/Tools_and_Features/Auto_Save_Drafts.html) enabled, which saves the draft data on close.

**Comment by PGBrandi** [comment]
Makes absolutely sense. Would be nice if the correlation between these two settings could be found on the documentation page you linked. Would prevent some confusion in the future. Anyway, thanks for the clarification. :)

**Comment by aryaantony92** [comment]
Fixed by #12208
