### ISSUE TITLE
[Improvement]: Generate return types for setters in data objects

### ISSUE THREAD

**Issue by mysliwietzflorian** [pimcore/pimcore#12185]
### Improvement description

We noticed, that the return type in the generated setter methods of the data objects is missing. Is this on purpose?
Otherwise, I would suggest adding that, if it's possible and does not create any problems with the class overrides.  
(e.g.: `public function setSeries(?string $series): self {...}`)

Example of the current state (from the Pimcore demo):

```php
/**
* Set series - Series
* @param string|null $series
* @return \Pimcore\Model\DataObject\Car
*/
public function setSeries(?string $series)
{
	$this->series = $series;

	return $this;
}
```

**Comment by fashxp** [comment]
this is a Pimcore 11 thing... would be a BC break

**Comment by dkarlovi** [comment]
@fashxp restricting return types is not a BC break, widening them is.
https://en.wikipedia.org/wiki/Covariant_return_type
