### ISSUE TITLE
[Bug]: Grid rows not equal in Grid View

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#12181]
### Expected behavior

See https://github.com/pimcore/pimcore/issues/6918

### Actual behavior

See https://github.com/pimcore/pimcore/issues/6918

### Steps to reproduce

See https://github.com/pimcore/pimcore/issues/6918

**Comment by Hbitvof** [comment]
What is this for stupid auto reply? All the information is in #6918 and this bug is not fixed.

**Comment by brusch** [comment]
@Hbitvof read the message from the bot ... PRs are welcome 😉

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
