### ISSUE TITLE
[Bug]: Filter is missing on Published column in Grid view

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#12184]
### Expected behavior

In Pimcore 6.x it was possible to filter on published state, in Pimcore 10.x this filter is missing.

### Actual behavior

Filter is missing

### Steps to reproduce

Compare version 6.x with version 10.x

**Comment by dvesh3** [comment]
Sorry, not a valid issue.
![image](https://user-images.githubusercontent.com/5137917/169785489-be6939fc-ff88-401d-9f84-d52def785c50.png)

**Comment by Hbitvof** [comment]
> Sorry, not a valid issue. ![image](https://user-images.githubusercontent.com/5137917/169785489-be6939fc-ff88-401d-9f84-d52def785c50.png)

Maybe this is related to migrating 6.x to 10.x? I don't have the filter option for this column:

![image](https://user-images.githubusercontent.com/41229269/169786703-e862fa5f-7eb1-4786-9be0-0a46667d6c40.png)

And I do have the filter for other column:

![image](https://user-images.githubusercontent.com/41229269/169786846-9b47dc6d-8146-4d9a-85e8-91d8e188b276.png)

**Comment by dvesh3** [comment]
@Hbitvof It is not a migration issue. In your case, the published column is **locked**, so the filtering is disabled by ExtJS.

**Comment by Hbitvof** [comment]
> @Hbitvof It is not a migration issue. In your case, the published column is **locked**, so the filtering is disabled by ExtJS.

You are right when the column is unlocked the filter is back. This behaviour was different in 6.x, for this reason I thought this was a bug, my apologies.
