### ISSUE TITLE
2x Thumbnails are not properly scaled up

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#1219]
# Bug Report
### Expected behavior 
2x retina thumbnails are generated and are twice the size of the normal thumbnail size.

### Actual behavior  

2x retina thumbnails have the same size as normal thumbnails

### Steps to reproduce  

Latest Pimcore 4.4.2 (but same behaviour in 4.4.0).
Create a thumbnail with COVER modification and size 1240x300, positioning top-left and Force resize = true.
Set high resolution to 2 (or leave it at 0, doesn't matter).
A Picture code will be rendered but the thumbnail given for 2x will actually have the same size (1240px) as the normal thumbnail.

In earlier versions of pimcore, the thumbnail has been rendered as 2480px wide thumbnail in this case for the 2x thumbnail.

This matters especially because the layout will change - the browser does render the 1240px in half resolution leaving space all around the image.

**Comment by Cruiser13** [comment]
Hello @brusch ,
I applied your fix but the thumbnails are still not scaled up. Thumbnail is generated in the same size as before.

**Comment by brusch** [comment]
@Cruiser13 Cleared temporary data?

**Comment by Cruiser13** [comment]
Yes I cleared the thumbnail file directly and it's being regenerated in the wrong size.

**Comment by brusch** [comment]
Hmm, for me it works just perfectly.
Can you please try to debug it? Thanks!

**Comment by Cruiser13** [comment]
It jumps into the first if clause and runs until
`goto prepareTransformations;`
$highResFactor is 1.25 before that goto, sourceImageWidth is 1500.

**Comment by brusch** [comment]
You ticked `forceResize` in the thumb config right? 
If so, you can't get to `goto prepareTransformations;` , see this `if`: 
https://github.com/pimcore/pimcore/blob/1af704f6f6ec88a4c933e44f9cd767a15371affb/pimcore/models/Asset/Image/Thumbnail/Processor.php#L292-L292

**Comment by Cruiser13** [comment]
I see, logic switched here between the 4.4.0 version and the new 4.4.2. The checkbox used to be "do not scale up" but is now "force scale up". Sorry.

A 4.4.2 with your fix applied does the job. Thanks!
