### ISSUE TITLE
[Bug]: Saving of Object with reverseObjectRelation to ManyToOneRelation not possible

### ISSUE THREAD

**Issue by dpfahlbusch** [pimcore/pimcore#12199]
### Expected behavior

Saving is possible

### Actual behavior

It's not possible to save object.
Exception is thrown:
Invalid non owner object relation to object.

### Steps to reproduce

1. Create objectclass with reverseObjectRelation to a ManyToOneRelation
2. Create object and add relation
3. Try to save object with reverseObjectRelation
4. Exception is thrown

**Comment by dpfahlbusch** [comment]
I think this line causes the problem:
https://github.com/pimcore/pimcore/blob/10.x/models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php#L159

Maybe add another instanceof check:
`$fd instanceof DataObject\ClassDefinition\Data\ManyToManyObjectRelation || $fd instanceof DataObject\ClassDefinition\Data\ManyToOneRelation`

**Comment by fashxp** [comment]
already fixed by https://github.com/pimcore/pimcore/pull/12144?

**Comment by dpfahlbusch** [comment]
Yeah, did not find this issue :)
