### ISSUE TITLE
[Improvement]: Limit input of Editables

### ISSUE THREAD

**Issue by pimcoreneusta** [pimcore/pimcore#12206]
### Improvement description

As an user/editor editing either **headless documents** or **documents** I'm looking for additional information on editables (e.g. **Input** or **WYSIWYG**) showing a **character count** while editing the field. 

In case the field is limited to a maximum count of characters the current and remaining characters will be shown close to the editable field (see example depicted below). 

![image](https://user-images.githubusercontent.com/99489645/170062331-7674108d-966d-44fe-8f04-ab26313d9359.png)

Based on configuration, input is cut/limited to maximum count of characters or further input is allowed and count of characters indicating exeeded limitation is shown.

Below you see an example where limit/count would be very useful …

![image](https://user-images.githubusercontent.com/99489645/170065242-cf4e7bdc-2a7a-43b7-8734-e68d73681a82.png)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
