### ISSUE TITLE
[Bug]: Deeplinks with 2FA login does not work

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#12219]
### Expected behavior

Deeplinks work even if the user has enabled 2FA login.

### Actual behavior

Deeplinked element does not get opened after login

### Steps to reproduce

1. Create user with 2FA
2. Copy deeplink of an element
3. Log out
4. Open deeplink
5. Log in
Now the element should get opened

**Comment by dvesh3** [comment]
@BlackbitNeueMedien Sorry, not able to reproduce the issue. Could you please share more information like Pimcore version, Element type etc.

**Comment by dvesh3** [comment]
@BlackbitNeueMedien 🏓

**Comment by BlackbitDevs** [comment]
Yes, works in Pimcore 10.4 - original bug report was based on 6.9.
