### ISSUE TITLE
[Task] Add @param and @return php doc types to /lib/Console

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12216]
### Improvement description

- [ ] Add @param php doc types for all public/protected classes/methods/properties in /lib/Console (excl. Dao and @internal) 
- [ ] Add @return php doc types for all public/protected classes/methods/properties in /lib/Translation (excl. Dao and @internal) 
- [ ] Make sure phpstan tests still run through

**Comment by aashan10** [comment]
Nothing to change here!
