### ISSUE TITLE
[Task] Add @param and @return php doc types to /lib/Maintenance 

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12228]
### Improvement description

- [ ] Add @param php doc types for all public/protected classes/methods/properties in /lib/Maintenance (excl. Dao and @internal) 
- [ ] Add @return php doc types for all public/protected classes/methods/properties in /lib/Maintenance (excl. Dao and @internal) 
- [ ] Make sure phpstan tests still run through

**Comment by robertSt7** [comment]
no changes necessary
