### ISSUE TITLE
[Task] Add @param and @return php doc types to /lib/Image 

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12226]
### Improvement description

- [ ] Add @param php doc types for all public/protected classes/methods/properties in /lib/Image (excl. Dao and @internal) 
- [ ] Add @return php doc types for all public/protected classes/methods/properties in /lib/Image (excl. Dao and @internal) 
- [ ] Make sure phpstan tests still run through

**Comment by kingjia90** [comment]
no changes are needed.

Only found one case that may require some improvement https://github.com/pimcore/pimcore/blob/60eaa297641d9c48a5790433f170a342e319aa46/lib/Image/Adapter/GD.php#L402-L403
but it's about @var.
