### ISSUE TITLE
exif orientation not properly respeced for asset images

### ISSUE THREAD

**Issue by LosHawlos** [pimcore/pimcore#1225]
Pimcore does not properly handle jpeg images that have certain orientation flags set in the exif data.

The witdh and heigth returned by the asset image and thumbnail object can be switched. Depending on how the image is displayed in the website this can lead to the images looking stretched.

This screenshot shows correctly the landscape image but the width and height are those of a portrait image (exif orientation 5).
![exif orientation bug](https://cloud.githubusercontent.com/assets/7881418/22403049/4a548164-e60c-11e6-8347-9264c1270ca1.png)

In our setup the scaled thumbnails show the correct orientation, so the thumbnail processor seems to properly respect the exif orientation.

You can reproduce this using this sample from this repository:
https://github.com/recurser/exif-orientation-examples

**Comment by brusch** [comment]
Fix works only for newly created images, existing images have the value cached in custom settings.
