### ISSUE TITLE
[Bug]: New created users can't login with the assigned username and password after upgraded to 10.4

### ISSUE THREAD

**Issue by wumi20** [pimcore/pimcore#12253]
### Expected behavior

Create a new user in the admin portal

### Actual behavior

Here's the situation:

- The application works well before we upgraded to 10.4, and we have a "admin" account
- We upgrade the system to v10.4
- We create a user account with the existing "admin" account, eg with the user named "test" and set it checked the Admin
- And then we log out with the current admin and tried to login with "test", and it says the Login failed!
Please try again.
- Get into the systems with the existing admin and surprised to find the "test" account is not Admin any more. 
- We've tried to create another account without Admin role, and still it says the Login failed!
Please try again.

It seems that after the upgrades, the users couldn't be edited properly. 

And we have upgraded another our existing Pimcore instance to 10.4, the same issue happens as well. How to solve this problem. 

### Steps to reproduce

Here's the situation:

- The application works well before we upgraded to 10.4, and we have a "admin" account
- We upgrade the system to v10.4
- We create a user account with the existing "admin" account, eg with the user named "test" and set it checked the Admin
- And then we log out with the current admin and tried to login with "test", and it says the Login failed!
Please try again.
- Get into the systems with the existing admin and surprised to find the "test" account is not Admin any more. 
- We've tried to create another account without Admin role, and still it says the Login failed!
Please try again.

**Comment by fashxp** [comment]
maybe related? https://github.com/pimcore/pimcore/issues/12024 

did you try latest 10.4 release?

**Comment by wumi20** [comment]
Hi 

Yes, we've just tried the updates, the problem solved. I think it is the issue of #12024. Many thanks for the fast response
