### ISSUE TITLE
[Bug]: Pimcore creates var/classes/customlayout even though classes are not writable

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#12262]
### Expected behavior

`var/classes/customlayouts` not created if classes are not writable.

### Actual behavior

`var/classes/customlayouts` created if missing.

### Steps to reproduce

1. Move classes to `config/pimcore` as described [here](https://pimcore.com/docs/pimcore/current/Development_Documentation/Deployment/Deployment_Tools.html#page_Pimcore-Class-Definitions)
2. refresh
3. `var/classes/customlayouts` created

**Comment by kingjia90** [comment]
I wasn't able to reproduce this problem, do you mean that you refresh the page and the custom layouts are created automatically?

The only things i have noticed is: 
1) not writable classes/custom definition still allow new custom layout being created and saved
2) if the folder permission `config/pimcore/classes/customlayouts` doesn't have [execute ](https://www.php.net/manual/en/function.is-file.php#107403)permissions, then there are problems [here](https://github.com/pimcore/pimcore/blob/7b9d387aaa1e77884a1cf75a7342fbcbeebed873/models/DataObject/ClassDefinition/CustomLayout.php#L285) , maybe could you double-check this?

**Comment by dkarlovi** [comment]
@kingjia90 maybe there's a misunderstanding? Custom layouts are not created automatically, the folder is created. It seems Pimcore is very eager to create one if it doesn't exist, even if you're not using them at all. It will try to do it on each request, it seems.

This creates a problem when you're trying to run on a read-only filesystem (Docker, Lambda) and having Pimcore fail because it's for some reason trying to create a folder (which it shouldn't) which you don't even need / use.

**Comment by kingjia90** [comment]
@dkarlovi Thank you for clarifying, i think i got it now.

This could be the culprit, it's in the cache warmer, so may happen after every cache clear.
https://github.com/pimcore/pimcore/blob/597b1629f8c990781763a455372715fb2ac9ce9b/lib/HttpKernel/CacheWarmer/MkdirCacheWarmer.php#L59

Potentially, as point 1 of my previous comment, you can actually create new ones even if the class is not writeable and there it will also create the folder in `var/class` first. 
https://github.com/pimcore/pimcore/blob/597b1629f8c990781763a455372715fb2ac9ce9b/models/DataObject/ClassDefinition/CustomLayout.php#L211-L214

I will take a deeper look in what can be done and let you know

**Comment by dkarlovi** [comment]
The cache warmer seems suspicious since some of those folders shouldn't always exist, with the recent move to Flysystem based storage. For example, the mail log was moved to Flysystem in 10.4 (IIRC?) meaning it might be on AWS S3, it shouldn't be created for sure. :thinking:

**Comment by kingjia90** [comment]
So i had some chat with the team and there will some changes that will fix the initial problem.

- [x] The folder creation in the cache warmer would be removed/deprecated wherever possible (eg. email log should be already deprecated in favor of flysystem as you also mentioned, while for PIMCORE_SYSTEM_TEMP_DIRECTORY is not possible). #12443
- [x] The custom layout would be stored in the `LocationAwareConfigRepository` to have maximum flexibility. https://github.com/pimcore/pimcore/pull/12428
- [x] The env `PIMCORE_CLASS_DEFINITION_WRITABLE` (and related functions and docs) may be changed(or "extended") to allow a global read-only (no add/update) if the value is 0.  https://github.com/pimcore/pimcore/pull/12392
