### ISSUE TITLE
[Improvement]: Pimcore\Navigation\Builder marked as internal but mentioned in documentation

### ISSUE THREAD

**Issue by IAmMajo** [pimcore/pimcore#12276]
### Improvement description

`Pimcore/Navigation/Builder` was marked as internal on 29th April 2021 (https://github.com/pimcore/pimcore/commit/f85ba025c30aae29a78805f822002bf9fd96b39e#diff-0ae9dfd15f90eab5d95db3ca02c83501513ecb88b3700267e2f3fd7d83c0d16d). However, the documentation still mentions it as an alternative to building the navigation in the view:

> The building step does not necessarily need to happen in the view script. In fact the view helper just forwards the `build()` call to the `Pimcore\Navigation\Builder` service. You can also build the navigation in your controller or a service and pass the navigation object to the view. (https://pimcore.com/docs/pimcore/current/Development_Documentation/Documents/Navigation.html)

Either the class was mistakenly marked as internal or the documentation needs to be updated. Removing the notice from the documentation would mean that the navigation has to be build in the view and can not be build in a controller.

**Comment by jdreesen** [comment]
I stumbled upon this, too. I need a way to build the navigation outside of templates, so I'd prefer to remove the `@internal` marker.

**Comment by brusch** [comment]
Removing `@internal` would be ok for me, but we then should tag `protected` methods and properties as `@internal` because the class is not `final` (see #9364 and https://github.com/pimcore/pimcore/pull/9918)

**Comment by jdreesen** [comment]
That's okay for me, I (currently :wink:) only need to call `getNavigation(...)`.
