### ISSUE TITLE
Deprecate Extension Manager

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#12274]
### Improvement description

Use Symfony Flex's `config/bundle.php` for bundles instead. 
For Areabricks I think we don't need a management (enable/disable), they are just getting loaded automatically. 

- [x] check if non-flex bundles are supported in `bundles.php` - yes, it works!
- [x] when there are extensions defined in the `bundles.php` then need to be activated by default.
- [x] issue deprecation warnings when there is content in the `extensions.php`
- [x] make `extensions.php` optional
- [x] deprecate enable/disable in the `pimcore:bundle` command
- [x] deprecate all related classes
- [x] add deprecation message for bundle entries in the UI

**Comment by brusch** [comment]
Adding this to `10.5` milestone for now, as this change would require some deprecations 😉

**Comment by fashxp** [comment]
keep marketplace in mind for that one

**Comment by brusch** [comment]
Just as an idea: marketplace could be a dedicated composer package (included in `pimcore/demo` and `pimcore/skeleton` default)

**Comment by dkarlovi** [comment]
I'm all for this since this is exactly how we use everything. If you wanted the feature, you install an additional Pimcore package to enable this type of app management. :100:
