### ISSUE TITLE
[Bug]: Grid options metadata display issue (DAM)

### ISSUE THREAD

**Issue by ServiceWebLG** [pimcore/pimcore#12271]
### Expected behavior

In assets, when we want to configure the grid options, the assets metadata must be displayed.

### Actual behavior

Since the update of the PimcoreAssetMetadataClassDefinitionsBundle (v 1.2.6), the assets metadata are no longer displayed on the configuration options of the grid on the DAM part.
We are successfully retrieving JSON responses from the get-metadata-for-column-config method. 

<img width="705" alt="Capture d’écran 2022-05-30 à 14 38 40" src="https://user-images.githubusercontent.com/93980838/170994164-0a518f5a-3d49-4171-a43d-3d46a96deb89.png">

### Steps to reproduce

In Enterprise version, DAM part, in a directory, click on "List" and "grid options"

**Comment by fashxp** [comment]
Most likely, you need to configure `Asset Metadata Class Definitions`, see also see also https://pimcore.com/docs/asset-metadata/current/index.html#screen-0

Besides that, this is the wrong place for support for enterprise extensions. Please contact your contact person at Pimcore to get support for enterprise extensions.
Thank you...
