### ISSUE TITLE
[Bug]: Data missing from Pimcore 10 admin data objects UI.

### ISSUE THREAD

**Issue by manasaR507** [pimcore/pimcore#12275]
### Expected behavior

Data is missing from Pimcore10 admin -> data objects UI. In versions tab it is showing & in database also having the data. But, it's not displaying on pimcore data objects UI. Verified with asset install & cache clear & php 8.0 requirements check. Everything is perfect. We have verified with all the ways. But, still issue is there. After updating the data, after 24 hrs. data is vanishing from object UI.  In local environment working fine. On production having the issue. Need urgent support from you guys. Any idea! 

Please observe in below screen. 

 ***
![Screenshot1_LI (2)](https://user-images.githubusercontent.com/64125570/171011637-f861ae15-2672-4a5d-8777-fe7a2d1c3672.jpg)
![Screenshot 2_LI (2)](https://user-images.githubusercontent.com/64125570/171011646-2da90730-b1f1-4215-b8af-e67bb45be419.jpg)
*

### Actual behavior

After updating the data in data object UI. Data should be present. But, it's not showing on particular data object filed.

### Steps to reproduce

1. Open the particular data object and modified particular field data.  After 24 hrs, data is not showing on pimcore data object UI.

**Comment by manasaR507** [comment]
Hi Guys, Any idea?

**Comment by manasaR507** [comment]
If I run pimcore:deployment:classes-rebuild command. Data was showing in Data objects UI. After some time again data was missing.

**Comment by dvesh3** [comment]
@manasaR507 Hi, please check if the data is returned in the response (below) and not just shown in the edit window? 
![image](https://user-images.githubusercontent.com/5137917/172596676-837beec7-cee2-42e4-a921-91ef4d5831ca.png)
 if it is not there in the response, then debug the data flow and see where it is getting lost, if it is there in the database. I would put a break point in `AbstractObject::assignVariablesToModel`.

**Comment by dvesh3** [comment]
@manasaR507 please share your findings here. thanks!

**Comment by dvesh3** [comment]
Closed due to inactivity. Please feel free to continue the discussion.

**Comment by manasaR507** [comment]
> Closed due to inactivity. Please feel free to continue the discussion.

Hi Divesh Pahuja,

Sorry for the delay. We have observed in the network tab also not getting the value for missing filed. Can you please guide me. How to fix this issue?

**Comment by dvesh3** [comment]
@manasaR507 please see 
> if it is not there in the response, then debug the data flow and see where it is getting lost, if it is there in the database. I would put a break point in AbstractObject::assignVariablesToModel.

**Comment by manasaR507** [comment]
Hi @dvesh3 

Below,  I have added few  screenshots.  it is present in versioning. But not in api response. In object ui side is not displaying. But it's present in db. 

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/64125570/175029995-abd887bb-b5ad-452b-9793-453557a51fe0.png)



![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/64125570/175030342-b51a973a-59d0-45b7-81fc-99b5c3eedb4f.png)

**Comment by manasaR507** [comment]
> @manasaR507 please see
> 
> > if it is not there in the response, then debug the data flow and see where it is getting lost, if it is there in the database. I would put a break point in AbstractObject::assignVariablesToModel.

Yes, verified in data flow. It's missing. So please put a break point in AbstractObject::assignVariablesToModel. And also please give me the clear idea about what changes your doing for fixing this issue.

**Comment by manasaR507** [comment]
Hi @dvesh3,

 Any update on this? 
Do you have any suggestion for checking this issue from my end. Please Let me know.

**Comment by dvesh3** [comment]
Hi @manasaR507 sorry, I can't provide a fix or suggest a solution, as i was not able to reproduce the issue. It would be good if you can provide a fix or share exact steps to reproduce it.
