### ISSUE TITLE
How should deployment:classes-rebuild work?

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#1228]
As far as I understand the command, it should rebuild-all/create database-tables. But, I did came up with following problem:

ClassDefinitions: It doesn't load files from PIMCORE_CLASS_DIRECTORY, it loads it from the database.
FieldCollections: Loads definitions from PIMCORE_CLASS_DIRECTORY/fieldcollections
Bricks: Loads definitions from PIMCORE_CLASS_DIRECTORY/objectBricks.

So, on an initial class-import, it creates definitions for field-collections and bricks, but nothing for classes. How should classes ever be initially deployed? (Sure, it still is possible to export via JSON and import them, but it's not an automated task)

In my opinion, it should check for existing classes in the database and new classes in PIMCORE_CLASS_DIRECTORY, shouldn't it?

something like this:

```php
$objectClassesFolder = PIMCORE_CLASS_DIRECTORY ;
$files = glob($objectClassesFolder . "/*.php");

foreach ($files as $file) {
    $class = include $file;

    if($class instanceof ClassDefinition) {
        $existingClass = ClassDefinition::getByName($class->getName());

        if($existingClass instanceof ClassDefinition) {
            $existingClass->save();
        }
        else {
            $class->save();
        }
    }
}
```

**Comment by brusch** [comment]
I'd provide this functionality as an extra flag, like: 
`php pimcore/cli/console.php deployment:classes-rebuild -c` 

Then it's up to the user to decide if newly created classes should get created automatically or not. Can you make an PR for that?

**Comment by dpfaffenbauer** [comment]
Yes, I can do that.

**Comment by dpfaffenbauer** [comment]
already done, so I'll close this
