### ISSUE TITLE
[Improvement]: Limit items of Many-To-Many Relations in Editable

### ISSUE THREAD

**Issue by neusta-diaspero** [pimcore/pimcore#12284]
### Improvement description

As an user/editor editing either **headless documents**, **headless bricks** or **documents** using Many-To-Many Relation Editable it would be great to be supported by a limitation e.g. to a maximum of three related objects in order to not link more objects than needed/consumed in the current context.

![image](https://user-images.githubusercontent.com/36693399/171109778-aefa2cff-8a67-44aa-ad26-4ac1ede7f86a.png)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Comment by cngJo** [comment]
I'd also be interested in this feature. Would you accept a PR implementing this?

**Comment by fashxp** [comment]
yes indeed

**Comment by taherbensassi** [comment]
Hey guys, is there any update on this ? we will need this feature 

In the meantime i want to know is there any work around to achieve it ? Thanks
