### ISSUE TITLE
[Improvement]: Add "order by" to custom report with sql adapter

### ISSUE THREAD

**Issue by aweichler** [pimcore/pimcore#12288]
### Improvement description

In custom reports with the SQL adapter there should be the possibility to specify an order by. The order should be done when initially loading the data and when exporting the data.
What do you think?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Comment by frithjof** [comment]
i am currently in need of the feature ( diagrams look wonky without being sorted by date ) will try to supply a pull request in the next weeks
