### ISSUE TITLE
[Bug]: Unable to save password, first name, last name, email of the admin panel user

### ISSUE THREAD

**Issue by ubaranouski-pl** [pimcore/pimcore#12296]
### Expected behavior

Fields are saved

### Actual behavior

Fields aren't saved despite the getting a successful ajax response.

### Steps to reproduce

1. Create a new admin user.
2. Fill the Password field or any of the Firstname, Lastname, email
3. Press the save button at the bottom.
4. Refresh user tab

**Comment by ubaranouski-pl** [comment]
The UserController::update action get the UserRole object which has no such fields thus they can't be set.

**Comment by kingjia90** [comment]
Which version of Pimcore are you experiencing this problem? 
It could be related to 
https://github.com/pimcore/pimcore/issues/12253 and #12024 and it's solved in 10.4.1

**Comment by ubaranouski-pl** [comment]
Thank you
