### ISSUE TITLE
[Maintenance]: Using lower_case_table_names does not work with "CleanupFieldcollectionTablesTask"

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#12292]
### Expected behavior

The [CleanupFieldcollectionTablesTask](https://github.com/pimcore/pimcore/blob/10.x/lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php#L65-L69) should work and not throw any errors when using the setting `lower_case_table_names=1` on your DB server.

### Actual behavior

Right now, when using the `lower_case_table_names=1` setting (as described in the [documentation](https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/DB_Setup.html#page_Database-Server-Configuration-Optional)), all table names are being lower cased as expected. When the maintenance task "CleanupFieldcollectionTablesTask" is running the field collection cannot be found, because the key is now lower-cased.

**Example:**
Imagine the following data structure. We have a DataObject class called "MyClass" (ID: "my_class") containing a field collection called "MyFieldCollection". For this scenario we receive following error message:

```log
app.ERROR: Fieldcollection 'myfieldcollection' not found. Please check table object_collection_myfieldcollection_my_class
```

This is because Pimcore is trying to get the field collection by key (reading the table name) here.

```php
\Pimcore\Model\DataObject\Fieldcollection\Definition::getByKey('myfieldcollection');
```

### Steps to reproduce

1. Set `lower_case_table_names=1` in your DB server configurations
2. Create a Pimcore DataObject class with a field collection
3. Create a Pimcore Field Collection and assign it to the object
4. Run the maintenance CLI command `bin/console pimcore:maintenance --async`
5. Open the log file for your current environment (dev.log, prod.log, ...)

**Comment by blankse** [comment]
Duplicate of https://github.com/pimcore/pimcore/issues/12101 ?

**Comment by aarongerig** [comment]
Ah yes, thank you @blankse !
Closing this issue.
