### ISSUE TITLE
[Bug]: Error during PDF-Generation:Notice: fwrite(): Write of 156826 bytes failed with errno=32 Datenübergabe unterbrochen (broken pipe)

### ISSUE THREAD

**Issue by Chris-Gett** [pimcore/pimcore#12299]
### Expected behavior

Generate a PDF Document

### Actual behavior

Error during PDF-Generation:Notice: fwrite(): Write of 156826 bytes failed with errno=32 Datenübergabe unterbrochen (broken pipe) after Update to PIMCORE 10.4.2 from 10.4.1 yesterday

After the second click on the "Gernerate Button" this warning occurs:

Error during PDF-Generation:Binary error: /home/xxx/xxx/vendor/spiritix/php-chrome-html2pdf/index.js:11
import getStdin from 'get-stdin';
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
 

### Steps to reproduce

generate an PDF Document

**Comment by Chris-Gett** [comment]
@fashxp
I can not reproduce the behavior in the Pimcore demo site. Generally, it seems that it is not possible to generate a PDF with all 3 web to print tools in the demo.

**Comment by dvesh3** [comment]
@Chris-Gett could you please confirm if you are using `Headless Chrome` tool to generate PDFs? is the issue reproducible on all tools? 
Also, please share settings used and error stack trace. thanks!

**Comment by Chris-Gett** [comment]
@dvesh3 Yes i use Headless Chrome tool to generate the PDFs. WkHtmlToPdf is working, also PDF Reactor.
At this point the generation of the PDF stops and the error message appears.
![Headless_Chrome](https://user-images.githubusercontent.com/73822840/172569208-50618587-b704-4c46-8e7d-50063f174992.png)
.
These are the Web to Print settings:
![Headless_Chrome2](https://user-images.githubusercontent.com/73822840/172569778-6f5b5a83-d504-4672-91c2-6dc976b2cb84.png)

**Comment by dvesh3** [comment]
@Chris-Gett Seems like `spiritix/php-chrome-html2pdf` released new a version 1.7 which now requires ["node": ">=18.0.0"](https://github.com/spiritix/php-chrome-html2pdf/blob/master/package.json#L11) if you have lower version installed then you'll see warning on composer update:
![image](https://user-images.githubusercontent.com/5137917/173094423-6c86ad80-ce93-4500-a39b-d19ba23dc889.png)

If this is the case then please update requirements to the latest version and try generating pdf or you could also just downgrade the `spiritix/php-chrome-html2pdf` package to version 1.6.1.

**Comment by Chris-Gett** [comment]
@dvesh3 Thank you very much. That was indeed the problem. I have downgraded to version 1.6.1 and it now works properly.
Is there any further development or adaptation of the packages planned by Pimcore?
Does node >18 work properly with Pimcore and all extensions? Is there any experience?

**Comment by dvesh3** [comment]
@Chris-Gett Hi, sorry for late response. We are checking if pimcore bundles are supported on node > 18. Based on the findings, we'll either update the docs to use latest version of node or update the dev requirement for `spiritix/php-chrome-html2pdf` to stay on 1.6.1

**Comment by brusch** [comment]
Closed see https://github.com/pimcore/pimcore/pull/12496#discussion_r904926023
