### ISSUE TITLE
[Bug]: Filter for object brick attributes does not work 

### ISSUE THREAD

**Issue by EvaStudioEmma** [pimcore/pimcore#12293]
### Expected behavior

Sort or filter on an attribute of an object brick in the grid view.

### Actual behavior

An error message pops up:
![image](https://user-images.githubusercontent.com/106537233/171001830-1075b183-f152-43ef-846c-fea2eba3e235.png)

### Steps to reproduce

1. Open a gridview for a class that contains objectbricks
2. Add a random attribute (from an objectbrick) to the grid view. (in my case this was a WYSIWYG-field)
3. Try to sort or filter on it.

Pimcore-version: 10.3.3

**Comment by dvesh3** [comment]
Fixed by #12416
