### ISSUE TITLE
CLI Installer

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#1229]
I think a CLI Installer would be very handy for Pimcore. 

The idea is to make automated-installs/deployments more easy.

Before I create a PR, I would like to discuss it with you. What is your opinion about this?

I could imagine it being very similar to magento's cli installer (http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-install.html)

Name | Value | Required | Default
------------ | -------------|--------|-------
admin-user | Admin User Name | no | admin
admin-password | Admin Password | yes | 
db-host | Database Host | yes |
db-user | Database Username | yes |
db-password | Database Password | yes |
valid-languages | Valid Languages | no | en

**Comment by Pegasuz** [comment]
Installation of Pimcore using the CLI can also be done using our Migration Plugin (https://github.com/studioemma/pimcore-plugin-migrations)

That said, I think it would be great if this was part of the core.

**Comment by dpfaffenbauer** [comment]
Yes, I did something myself als well. Not open source though.

**Comment by maff** [comment]
Implemented in #1778
