### ISSUE TITLE
[Bug]: Document Tree doesn't load anymore after using one Document as Site (Symfony\Contracts\Translation\TranslatorInterface service error)

### ISSUE THREAD

**Issue by dasraab** [pimcore/pimcore#12300]
### Expected behavior

Document-Tree in Pimcore-Backend loads

### Actual behavior

Backend doesn't load the Document Tree after using one Document as "Site". Instead this error is shown

> The "Symfony\Contracts\Translation\TranslatorInterface" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

<img width="708" alt="image" src="https://user-images.githubusercontent.com/1923919/171167671-fdb03590-b102-4483-bee1-d82d24ee970c.png">

### Steps to reproduce

Create a Document and use it as site. Enter a Domain name and click save. Now the error appears for the first time. From now on if you reload the Backend the error appears and the document tree isn't loaded anymore.

**Comment by dasraab** [comment]
Here is where the error is thrown: [AdminStyle.php | Line 100](https://github.com/pimcore/pimcore/blob/0520fd4e7b0e8cf33de43625c09f1f62612096f4/models/Element/AdminStyle.php#L100)

```php
 $translator = \Pimcore::getContainer()->get(TranslatorInterface::class);
```

**Comment by dvesh3** [comment]
please see https://github.com/pimcore/pimcore/pull/12041#discussion_r867312266

**Comment by dasraab** [comment]
@dvesh3 Thank you so much!
