### ISSUE TITLE
\Pimcore\Tool::isFrontend() returns false for correct Frontend requests

### ISSUE THREAD

**Issue by alesak** [pimcore/pimcore#1230]
We have some plugins which also provides functionality for frontend requests like:

`/plugin/PluginName/frontend/doSomething` calls to plugins controller

or providing scripts or css files for frontend users?

`/plugins/PluginName/static/js/frontendLib.js`
`/plugins/PluginName/static/js/frontendCSS.css`

I hope this is perfectly valid approach for plugins to provide extended functionality for frontend users...

Problem is that Pimcore thinks for all /plugin.*/ requests that those requests are not frontend requests according to` \Pimcore\Tool::isFrontend()` method.

Usually it is not an issue until you have multi-site configuration and $conf->general->domain (Main Domain) in Settings is configured.

At this time all requests to Site requests targeting /plugin.*/ are redirected to main domain (make them slower) and biggest problem accessing scripts cause CORS issues.

I think we should have some way to declare path in the script to be valid frontend request so pimcore can recognize it as a frontend and stop acting as if it is admin request...

I am more than happy to implement this, just would love to have some feedback before I start working on it....

My suggestion is:

enhance plugin.XML schema with something like `<pluginFrontendPaths/>` with list of `<path/>` to regex path patterns to be considered as a frontend requests

enhance ExtensionManager with method to check if requested path is frontend request to the plugin

update  `\Pimcore\Tool::isFrontend()` to check if request URI is actually frontend call to plugin

**Comment by fashxp** [comment]
please test again with pimcore 5 - should be fixed now since routing . thank you.
