### ISSUE TITLE
[Improvement]: Targeting should use opt-in approach

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#12307]
### Improvement description

Currently, the [Targeting and Personalization](https://pimcore.com/docs/pimcore/current/Development_Documentation/Tools_and_Features/Targeting_and_Personalization/index.html#page_Opt-out-from-targeting) feature is enabled "by default". That is, an opt-_out_ approach is used as soon as `isTargetingConfigured` returns `true`:

https://github.com/pimcore/pimcore/blob/c73a4641ba6b815f1e5787e642591284b982a92c/lib/Targeting/EventListener/TargetingListener.php#L134-L136

> The opt-out approach is also documented [here](https://pimcore.com/docs/pimcore/current/Development_Documentation/Tools_and_Features/Targeting_and_Personalization/index.html#page_Opt-out-from-targeting).

Instead of this, an opt-_in_ approach should be used. For example, instead of `pimcore_targeting_disabled=1`, introduce something like a `pimcore_targeting_enabled=1` cookie and enable the targeting only if this cookie was set.

Using tools like Cookiebot, the user can now choose to consent to the _marketing_-cookies (which are needed according to Cookiebot). If the user consents, the `pimcore_targeting_enabled=1` cookie can be set, which will then enable the actual targeting functionality (starting with the next request).

**Comment by brusch** [comment]
This depends on https://github.com/pimcore/pimcore/issues/12523 which need to be done first

**Comment by aryaantony92** [comment]
This will be obselete as we are moving 'targeting and personalization' module into its own repository. See https://github.com/pimcore/pimcore/issues/12523

**Comment by fashxp** [comment]
but still, in that repos we also need to change that behavior!

**Comment by aryaantony92** [comment]
So, it would be like, after installing and enabling the personalization bundle, we have to set the 'pimcore_targeting_enabled' cookie also to enable the targeting.

**Comment by jdreesen** [comment]
Yes, if the user consents to it.
