### ISSUE TITLE
[Bug]: Data Components in Custom Layout without Layout Component

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#12309]
### Expected behavior

Every Data Component have to be in a Layout Component in a Custom Layout

### Actual behavior

There can be Data Components outside of Layout Components
![image](https://user-images.githubusercontent.com/104770750/171348606-26fdb0d6-684b-4616-8713-77280a5265cc.png)

### Steps to reproduce

- Create a Custom Layout
- Drag and drop some Data Components to the "Base"

**Comment by dvesh3** [comment]
This should be the case with ClassDefinition & AssetsMetadataDefinition as well, so if we fix it for Custom Layouts then we have to consider other places too.
