### ISSUE TITLE
Render MultiSelection fields as ExtJs Formtags

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#1231]
# Feature Request 
Represent MultiSelect fields as tags in ExtJs.

## Feature description 
Currently multiselect fields are represented in lists. This can result in very long lists that are difficult to manage if there are many options (example: 250 colors). An alternative representation (ExtJs Tags; see http://examples.sencha.com/extjs/5.0.0/examples/kitchensink/#form-tag) would be a good solution! 

It would be great, if there would be the option in the multiselection field, whether the output is as a list (=default), or as tags. With the current ExtJs version this shouldn't be too complicated.

**Comment by Yivan** [comment]
Hello Andreas!

You have a plugin which do this here: https://github.com/ThomasKeil/pimcore-plugin-DynamicDropdown
You can activated it, it will show new datatype for classes. If you uninstall the plugin 3 of them are backward compatible, I mean if you revert type to multihref, data is keep consistent without the plugin. They are just extending multihreg to provide other GUI possibility.

I would like to have directly with the core version the choice of different select GUI too (combobox, itemselector...) for select and multiselect type. Sometimes those are more friendly user depending the use case. It could be an option of the datatype. But actually it can be solved by this plugin or by creating a custom plugin extending select/multiselect.

**Comment by dpfaffenbauer** [comment]
PS: Look please at the ExtJs 6.0.2 Kitchen Sink. It's a little bit different ;)

http://examples.sencha.com/extjs/6.0.2/examples/kitchensink/#form-tag

**Comment by andreas-gruenwald** [comment]
@brusch We still need that feature. Can you give me an update whether this will be realised or not? 
Thx
