### ISSUE TITLE
[Bug]: Batch append doesn't work on CS attributes

### ISSUE THREAD

**Issue by Maksonis** [pimcore/pimcore#12313]
### Expected behavior

- Add multiselect classification store attributes to Data Object list via Grid Options
- Batch Append To all/select should keep existing maintenance and only add the new options

### Actual behavior

- Can't apply grid config changes after adding CS multiselect attribute:

![image](https://user-images.githubusercontent.com/17277953/171373309-5d425d3c-c96d-4877-bae8-19de1f2a7376.png)

- Batch Append To all/select replace the existing maintenance instead of only add the new options in case of CS store multiselect attributes

### Steps to reproduce

- Create CS store
- Create test multiselect attribute with few options
- Add it to Class
- Open Grid and try to add above attribute in grid
- Try to use Batch append option

**Comment by robertSt7** [comment]
see #12297 
Does this solve your problem?

**Comment by Maksonis** [comment]
Thanks, it solves first issue. But second one is still there. Check:

1. Add classification store multiselect attribute in grid. Select values for e.g. three news
![image](https://user-images.githubusercontent.com/17277953/173011328-97e525e5-b7c2-4f18-84c1-3cc9911f5946.png)

2.  go to Batch append to selected
![image](https://user-images.githubusercontent.com/17277953/173011379-5e69717d-717a-4d3d-9634-f773f87825a0.png)

3. select for example 6 and click Save
![image](https://user-images.githubusercontent.com/17277953/173011457-16a4535a-9686-444a-ba71-d819633e6251.png)

4. Old select values are gone:
![image](https://user-images.githubusercontent.com/17277953/173011598-3c3220e9-52dd-4260-8833-74ed771b48ea.png)

**Comment by dvesh3** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/12297 & #12418
