### ISSUE TITLE
[Improvement]: extend PIMCORE_CLASS_DEFINITION_WRITABLE to be globally read-only when value is 0

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#12323]
### Improvement description

Currently the `PIMCORE_CLASS_DEFINITION_WRITABLE` env parameter just allows the pimcore classes definition in `config/pimcore/` to be [writable](https://pimcore.com/docs/pimcore/current/Development_Documentation/Deployment/Deployment_Tools.html#page_Pimcore-Class-Definitions) again.

After #12321, it should be considering `0` to make globally read-only.
As found [here ]( https://github.com/pimcore/pimcore/issues/12262#issuecomment-1141426534), classes moved in `config/pimcore` are read-only but still allow the creation of new.

**Comment by dkarlovi** [comment]
Excellent suggestion, inline with my many previous issues about the filesystem being considered read-only in modern deployment scenarios. :1st_place_medal:
