### ISSUE TITLE
[Data Objects] General search field in Pimcore grid views

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#1232]
Is it possible to add a general wildcard search field for children grids?

Currently, filtering can only take place by selecting a specific column (e.g. firstname), then clicking on "Filters" and enter a search term for that column. If I want to look for a term (e.g., "Max") without exactly knowning the column, then this can become a tedious task.

It would be much more comfortable if there would be a general search field, which supports wildcards and searches in all (existing / visualized) data columns.

**Comment by brusch** [comment]
Should utilize the backend search index (table `search_backend_data`). 

UI: 
![image](https://user-images.githubusercontent.com/142037/52065399-bab05e00-2576-11e9-9f38-32c5d1aba0dc.png)
