### ISSUE TITLE
[Improvement]: Migrate Custom Layout definition files to use LocationAwareConfigRepository

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#12321]
### Improvement description

Currently the ~~[PHP classes definitions](https://pimcore.com/docs/pimcore/current/Development_Documentation/Deployment/Deployment_Tools.html#page_Pimcore-Class-Definitions) and~~ custom layout are saved in `/var/classes` but it should be using `LocationAwareConfigRepository` (which is already in use for [perspective/custom view](https://github.com/pimcore/pimcore/pull/10564/files)) as it will provide more flexibility and legacy support until Pimcore 11.

See https://github.com/pimcore/pimcore/issues/12262 where the filesystem is read-only it, it may cause problems.

Also: `PIMCORE_CLASS_DEFINITION_WRITABLE` var should not have any effect on custom layout screens.

**Comment by dvesh3** [comment]
This should be implement on Pimcore 11 with BC breaks as it is not possible to use `setCondition` on CustomLayout\Listing with these changes.

Todo: Add option to filter listing which should replace `setCondition` on Pimcore 11 https://github.com/pimcore/pimcore/issues/12544
