### ISSUE TITLE
[Bug]: $currentFilter not correct?

### ISSUE THREAD

**Issue by elements-team** [pimcore/pimcore#12333]
https://github.com/pimcore/pimcore/blob/10.x/bundles/EcommerceFrameworkBundle/FilterService/FilterService.php <- line 84

### Expected behavior

I guess the initFilterService() should return a array of all currently set filters (as it is described in the Doc-Block).

### Actual behavior

Currently $currentFilter is always overwritten and filters are not added to the $currentFilter array .

### Steps to reproduce

I guess the the code should be changed from 
`$currentFilter = $this->addCondition($filter, $productList, $currentFilter, $params);`
to
`$currentFilter[] = $this->addCondition($filter, $productList, $currentFilter, $params);`

**Comment by dvesh3** [comment]
@elements-team sorry, it works for me, filters are added up when selecting multiple on the frontend:
![image](https://user-images.githubusercontent.com/5137917/172340162-b443023b-f0b3-40ff-b939-988609904639.png)

FilterType `addCondition()` returns the appended array and set (overwrite) the $currentFilter value. please see https://github.com/pimcore/pimcore/blob/2f18a0f26380c56b609d937b40d2050c8d1a3e1a/bundles/EcommerceFrameworkBundle/FilterService/FilterType/MultiSelect.php#L69

**Comment by ctippler** [comment]
Hi,
sorry - you are right. I just figured out that project specific custom filter types caused the problem.
Regards,
Christian
