### ISSUE TITLE
[Bug]: LocationAwareConfigRepository doesn't check SERVER

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#12335]
### Expected behavior

`LocationAwareConfigRepository` checks both `$_ENV` and `$_SERVER`, same as Symfony's `\Symfony\Component\DependencyInjection\EnvVarProcessor` does.

### Actual behavior

`LocationAwareConfigRepository` only checks `$_ENV`, which is commonly disabled by setting PHP's `variables_order` to not include it. [`$_SERVER` is populated from underlying environment variables](https://www.php.net/manual/en/ini.core.php#ini.variables-order).

### Steps to reproduce

See https://github.com/pimcore/data-hub/issues/539

**Comment by dkarlovi** [comment]
Note, this is only an issue because https://github.com/pimcore/pimcore/issues/12066 is an issue. Otherwise I'd never use env vars for this.

**Comment by brusch** [comment]
Should be changed to `$_SERVER` because Symfony DotEnv is doing that: 
https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Dotenv/Dotenv.php#L151

**Comment by dvesh3** [comment]
Fixed by #12384
