### ISSUE TITLE
[Bug]: Cannot add grid options - Apply button inactive [10.4.2]

### ISSUE THREAD

**Issue by Pierre-Datasolution** [pimcore/pimcore#12332]
### Expected behavior

Click Apply button to modify grid display new grid

### Actual behavior

Nothing happens => grid apply button inactive
![image](https://user-images.githubusercontent.com/43100677/171603476-314b429a-aa35-402a-bc33-deb3f7748f26.png)

### Steps to reproduce

On 10.4.2 demo https://demo.pimcore.com/admin
Display a grid
Try to modify

It seems to be ok on https://demo.pimcore.fun/admin [10.4.x-dev]

**Comment by kingjia90** [comment]
seems same as #12281, if yes, then is already merged and will be released in 10.4.3

**Comment by Pierre-Datasolution** [comment]
Yes, sorry. I searched for an opened issue... my bad.
thanks
