### ISSUE TITLE
[Bug] Minipaint not considered in Content Security Policy

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12331]
### Expected behavior

Minipaint works..

### Actual behavior

Minipaint not loading images, only white square is shown... 

![image](https://user-images.githubusercontent.com/8792145/171602928-9c4faa75-f3fc-4b51-82d7-0c5e432a8a18.png)

### Steps to reproduce

open image and try to edit

**Comment by dvesh3** [comment]
Already fixed in https://github.com/pimcore/pimcore/pull/12303
