### ISSUE TITLE
[Feature]: cache warming features

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#12330]
### Feature description

1. rename, "warming" doesn't fit, Symfony calls it "warmup"
2. progress bar, I don't know long long it will take
3. multithreading, my hardware might be capable of ingesting 2x or 3x the rate it is, but it's bottlenecked by network or something
4. async, just schedule it via the command and workers can warmup the cache behind the scenes, this also somewhat solves 3. since I can have many workers running
5. ~~warmup filtering: warmup just documents, just assets, skip folders, etc~~ (this is already possible)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
