### ISSUE TITLE
[Bug]: Unable to add objects to product grid in Pimcore 10.4.2

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#12346]
### Expected behavior

Before version 10.4.2 it's possible to add object to grid view.  Now when you want to do this you get the following error:

![image](https://user-images.githubusercontent.com/41229269/172013779-6cfe94e9-424f-41ed-8db6-6d1fa4394b26.png)

This also occurs on the demo (demo.pimcore.com) so this is not only related to our own installation.

### Actual behavior

Unable to add objects to grid view.

### Steps to reproduce

Try to add an object to grid view.

**Comment by blankse** [comment]
Is it fixed with https://github.com/pimcore/pimcore/pull/12297 ? Seems like a duplicate.

**Comment by Hbitvof** [comment]
> Is it fixed with #12297 ? Seems like a duplicate.

But what do I need to do now to fix this? I see it's fixed in 10.4.3 but that's version is not released yet.

**Comment by kingjia90** [comment]
> > Is it fixed with #12297 ? Seems like a duplicate.
> 
Yes, it's a duplicate.

> But what do I need to do now to fix this? I see it's fixed in 10.4.3 but that's version is not released yet.

10.4.3 will be released on Wednesday, 8th June around afternoon. 
In the meantime, if it is necessary to avoid inconveniences in production, you could manually "hot fix" there by applying the changes of the PR.
At least that is what i would do as temporary remedy, not sure if there is any other better practice.
