### ISSUE TITLE
[Bug]: Scheduled Blocks are not created in case of Advanced Usage

### ISSUE THREAD

**Issue by aryaantony92** [pimcore/pimcore#12345]
### Expected behavior

Scheduled blocks should be created and does not throw error when it's create using the "blockStart" function.

### Actual behavior

When we try to create the scheduled block using "blockStart()" function, it's throwing an error "An exception has been thrown during the rendering of a template. ("Warning undefined array key 1).

### Steps to reproduce

Try creating a scheduled block with the blockStart() function.

{% set block = pimcore_scheduledblock("gridblock",{"manual": true}).start() %}
    <div>
        {% for b in block.iterator %}
            {% do block.blockConstruct() %}
            {% do block.blockStart(true, false, 'my-additional-class') %}
                Some message
            {% do block.blockEnd() %}
          {% do block.blockDestruct() %}
        {% endfor %}
    </div>
  {% do block.end() %}

**Comment by dvesh3** [comment]
Manual mode is not supported for scheduled blocks as it needs datetime along with indices.
