### ISSUE TITLE
[Bug]: Deleted Class is not removed in Objecktbrick-definition

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#12359]
### Expected behavior

When a Class is deleted, it is also removed in the Objecktbrick-definition

### Actual behavior

![bug](https://user-images.githubusercontent.com/104770750/172543372-e9b0a237-b312-4f74-aeeb-119f873379b9.png)

### Steps to reproduce

- Create a Class with an Objecktbrick component
- Assign some Objecktbrick to the component
- Delete the Class

**Comment by evanjamesjackson** [comment]
Given the way Pimcore generates bricks, I'm not sure this is even possible to remedy - would the definition file for the brick not need to be automatically updated?
