### ISSUE TITLE
[Improvement]: Replace all deprecated \Doctrine\DBAL\Connection methods & constants usages

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#12363]
`Doctrine\DBAL\Connection` has some deprecated methods and constants, which shouldn't be used anymore.

**Comment by brusch** [comment]
See #12123

**Comment by brusch** [comment]
@aashan10 this is still relevant, although #12123 fixed some deprecations, there are still some left, e.g. `fetchAll()`.

**Comment by brusch** [comment]
@aashan10 please be aware that `fetchAll()` is not the only deprecated method which is in use by Pimcore .. there are also: 
- `fetchAssoc()` 
- `query()`
- `executeUpdate()`
- `exec()`

and possibly others.

**Comment by aashan10** [comment]
@brusch I have looked for all the deprecated methods and replaced the usage with the suggested methods in the linked pr.
