### ISSUE TITLE
Workflow: "elementPublished" => TRUE don't publish it.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1238]
On the last stable Pimcore 4.4.3, configuring a workflow status with `"elementPublished" => TRUE` don't publish the object when he got this status.
(all required fields are previously filled in previous status and have been save without publish).

By the way, i was just asking me what happen if not all required fields are filled when workflow is going to a status asking for publishing the object using `"elementPublished" => TRUE`. Are some warning triggered for the end user ?

Thanks.

**Comment by Yivan** [comment]
As mentionned in the pull request https://github.com/pimcore/pimcore/pull/1246, there is always an issue regarding refreshing the tree after the element has been publishd/unpublished.
Thanks.

**Comment by fashxp** [comment]
should be fixed now. 
for the issue with published/unpublished refresh please make an additional issue.
