### ISSUE TITLE
[Bug]: Urgent: not able to view the objects in the admin panel with the 10.4.3 newest one

### ISSUE THREAD

**Issue by wumi20** [pimcore/pimcore#12381]
### Expected behavior

We want to view objects in the admin panel

### Actual behavior

There's error messages

[2022-06-09T14:06:40.527513+00:00] php.CRITICAL: Uncaught Error: method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given {"exception":"[object] (TypeError(code: 0): method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given at /mnt/pimcore/vendor/pimcore/pimcore/models/DataObject/Service.php:1463)"} []

[2022-06-09T14:06:40.527736+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given" at /mnt/pimcore/vendor/pimcore/pimcore/models/DataObject/Service.php line 1463 {"exception":"[object] (TypeError(code: 0): method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given at /mnt/pimcore/vendor/pimcore/pimcore/models/DataObject/Service.php:1463)"} []

<img width="742" alt="c26d37ceb7e7326d7e40f3dc55286e2" src="https://user-images.githubusercontent.com/66587336/172866639-abf2b5f6-897f-4037-989f-c624c0615afd.png">

### Steps to reproduce

view the objects

**Comment by dvesh3** [comment]
@wumi20 please share the complete stack trace from error details when you try to open the object in admin interface.

**Comment by wumi20** [comment]
@dvesh3 : I am in the admin panel,  and double click any objects or click to see the details, and there's an error message
<img width="1014" alt="381fd07ada0e8ee07f3b98d6b9bb8e7" src="https://user-images.githubusercontent.com/66587336/172874144-3cd95138-dc73-4e2b-9edc-df9c710dfaea.png">
 
And we use tail -f var/log/prod.log

<img width="658" alt="d9239328fef102868522bb3b2361976" src="https://user-images.githubusercontent.com/66587336/172874239-af072d7b-f21d-44d1-81d5-f0c803bb52c5.png">

**Comment by dpfaffenbauer** [comment]
@wumi20 did you clear the pimcore cache after deployment of the update?

**Comment by dvesh3** [comment]
> @wumi20 did you clear the pimcore cache after deployment of the update?

@dpfaffenbauer Is this known issue?

**Comment by dpfaffenbauer** [comment]
@dvesh3 sometimes it helps between deployments with "old" stuff being in cache. Depending on the version he used before that could be a Problem, yes. (due to changes how Pimcore serializes and de-serializes cache entries)

**Comment by dvesh3** [comment]
@dpfaffenbauer thanks for the info!

@wumi20 please try clearing cache as Dominik suggested. If it still doesn't work, then please click on Details button and paste the details from exception window in admin interface.

**Comment by wumi20** [comment]
@dvesh3 @dpfaffenbauer Thanks for the quick response. And we have cleared all caches, and the problem remains

<img width="1077" alt="710b96c7a0c513e975df1a7e54583dc" src="https://user-images.githubusercontent.com/66587336/172879810-4c6468df-8e27-42d1-90ab-2726e69529b6.png">

**Comment by wumi20** [comment]
Additionally, we have another test environment, which is 10.4.2, and it works good (a few tiny bugs). But  when the new built production environment is upgraded to 10.4.3,  the problem arises. Does it because method_exists ()?

**Comment by wumi20** [comment]
Thanks for the kindly response. @dvesh3 @dpfaffenbauer . We did a re-install, and it works now. Yes, I think there are some problems when direct upgrading, better not to online upgrading
