### ISSUE TITLE
[Bug]: custom reports with HAVING statement not working

### ISSUE THREAD

**Issue by MadeP** [pimcore/pimcore#12388]
### Expected behavior

Custom report should display correct data

### Actual behavior

Following error occurs when executing the sql statement on the dashboard:

An exception occurred while executing 'SELECT COUNT(*) FROM (SELECT han as han, COUNT(*) AS counter FROM object_1 GROUP BY han HAVING COUNT(*) >1;) AS somerandxyz WHERE 1 = 1': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ';) AS somerandxyz WHERE 1 = 1' at line 1

Server threw exception - could not perform action. Please reload the admin interface and try again.

----------

Executing directly in the database works without problems
(SELECT han, COUNT(*) AS counter FROM object_1 GROUP BY han HAVING  counter>1;)

### Steps to reproduce

Create custom report

SELECT han, COUNT(*) AS  counter
FROM object_1
GROUP BY han HAVING counter >1;

In my case the field han is a text field.

**Comment by NiklasBr** [comment]
It looks like you are missing an argument inside two of the `COUNT()` parts in your original query as it looks like in the error message:
```sql
SELECT COUNT() FROM (SELECT han as han, COUNT() AS counter ...
```
Can you post the complete conditions you are using?

**Comment by jdreesen** [comment]
What about the semicolon at the end of the subquery? I don't think this is right.

**Comment by MadeP** [comment]
Thias was my configuration:

![grafik](https://user-images.githubusercontent.com/66425228/173054334-bdca2958-76e7-4307-8ed5-30a292eaf64c.png)

After i removed the semicolon at the end everything worked.

Thanks a lot!
