### ISSUE TITLE
[Admin][Documents] Refactor Meta property settings

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#12399]
When using documents, we always need to add a property `og-image` for the client to set the `og-image`. This results in the following code for every project:

```twig
{% if document.property('og-image') %}
    {% do pimcore_head_meta().setProperty('og:image', host_url() ~ document.property('og-image').thumbnail('og-image').path) %}
{% endif %}
```

However, working with properties is quite cumbersome for almost every client. Especially, since there is no preview of the asset. Additionally, most clients try to find the setting in the `SEO & Settings` tab.

So, I propose adding an image field to the `SEO & Settings` tab, which can then be used for Open Graph. WDYT?

> Note that the field should be called `image` (as opposed to `ogImage`), so it can be used in various contexts. For example, the same field could be used for teasers in a blog or in search results - as these teasers should use the same preview image anyway.

_Originally posted by @passioneight in https://github.com/pimcore/pimcore/discussions/12367_

**Comment by dvesh3** [comment]
please see the suggested approach https://github.com/pimcore/pimcore/discussions/12367#discussioncomment-2936492

**Comment by aarongerig** [comment]
Just as an FYI: There is [this bundle](https://github.com/dachcom-digital/pimcore-seo), which already provides the Pimcore user with such functionality. Maybe that's something to consider before creating the PR. 🙂

**Comment by passioneight** [comment]
@aarongerig thanks! While the bundle looks promising, the documentation states that support is only available for 10.1-10.2. Additionally, it seems unmaintained for almost half a year. Maybe @dpfaffenbauer has more information on this?

**Comment by dpfaffenbauer** [comment]
@passioneight not my bundle, but it works with Pimcore 10.4 too. Great extension for Pimcore.

**Comment by passioneight** [comment]
@dpfaffenbauer I know, I just figured you may have some information, because your are seemingly part of every Pimcore-related code :-D

Anyway, thanks for the info - glad to hear everything's still working in 10.4. I wonder though, if this bundle should be at least added to the `suggest` part of the `composer.json`. Any thoughts?

**Comment by aarongerig** [comment]
I would not suggest adding this bundle to the `suggest` section of Pimcore's `composer.json` as there are many great bundles out there, which would then belong onto this list as well. So the list of suggestions would quickly become confusing/messy.

Star it, bookmark it and tell others instead! 😉

**Comment by dpfaffenbauer** [comment]
https://pimcore.com/en/developers/marketplace ;)

**Comment by passioneight** [comment]
@aarongerig fair point.
@dvesh3 I guess, we can close this issue.

Thanks to everyone for sharing your feedback!

**Comment by solverat** [comment]
Just for the record: The SEO Bundle works with Pimcore 10.5 and will also support upcoming PIMCORE Versions like 11.0.
