### ISSUE TITLE
Objects > Select Data Types > CSV-Seperated Options > Support Quotes

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#1239]
see screen: 
![image](https://cloud.githubusercontent.com/assets/8792145/22460022/613dc348-e7a3-11e6-8a15-9e38d82f74ca.png)

**Comment by fashxp** [comment]
best would be to go for RFC 4180 https://tools.ietf.org/html/rfc4180 -> maybe there is a JS lib out there somewhere to take care of this

**Comment by weisswurstkanone** [comment]
build #4049 - ExtJS6 only

**Comment by fashxp** [comment]
implemented by using http://docs.sencha.com/extjs/6.2.0/modern/Ext.util.CSV.html
