### ISSUE TITLE
[Bug]: "Warning: Undefined array key "key""

### ISSUE THREAD

**Issue by spotbot2k** [pimcore/pimcore#12398]
### Expected behavior

Object to be moved in a new Folder on Drag&Drop

### Actual behavior

Exception thrown by the "admin/object/update" route

### Steps to reproduce

1. Create a user with all permissions but "settings"
2. Log in
3. Drag&Drop an Object from one folder to another

Permissions are not checked properly in Admin-JS, it leads to Exceptions and unexpected behaviour. For example in `tree.js`

``` js 
if (node.data.permissions.settings) {
```

But at this point the permission setting has a value of `"0"`, and as an non-empty string is evaluated as `true`. It depends on the used browser, but it is the case for chrome. Can be checked by typing

``` js
console.log("0" ? true : false); // will return true
```

in the browser console.

**Comment by brusch** [comment]
@spotbot2k can you please share the stack trace? Thanks!

**Comment by spotbot2k** [comment]
Can be avoided by using `Boolean(node.data.permissions.settings)`, but I think it needs an update in many of the admin js files. 

``` js
if(!newParent.data.permissions.create){
```
on the other hand will be handeled correctly, as it imples a boolean conversion due to `!`

**Comment by spotbot2k** [comment]
> @spotbot2k can you please share the stack trace? Thanks!

There is no stack trace for the frontend, as it is not an error by itself, the one for backend is 

``` bash
[2022-06-13T07:58:24.052760+00:00] request.CRITICAL: Uncaught PHP Exception ErrorException: "Warning: Undefined array key "key"" at /var/www/html/dev/spotbot2k/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php line 1087 {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"key\" at /var/www/html/dev/spotbot2k/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php:1087)"} []
```

At this point backend tries to handle it as a "Rename", but will not be able to as there is no key provided by frontend

**Comment by blankse** [comment]
@brusch @spotbot2k I created a PR https://github.com/pimcore/pimcore/pull/12400

**Comment by spotbot2k** [comment]
> @brusch @spotbot2k I created a PR #12400

Thanks, but is does not resolve the fact that the action is not handeled properly in the admin UI. Changing the line 318 in `/pimcore/bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js` from

``` js
        if (node.data.permissions.settings) {
```

to

``` js
        if (!!!node.data.permissions.settings) {
```
will do, if this type of conversion is ok for you I might do a PR

**Comment by blankse** [comment]
@spotbot2k I added a commit to my PR. The permissions should be integers now. Can you test it?
FYI @brusch

**Comment by spotbot2k** [comment]
@blankse it works, thanks!
