### ISSUE TITLE
[Bug]: "Visible in Grid View" and "Visible in Search Result" for CS cause some problems

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#12409]
### Expected behavior

Deactivate "Visible in Grid View" and "Visible in Search Result" in the Class config for CS 

### Actual behavior

CS is displayed wrong in the grid
Grid functions lead to errors

### Steps to reproduce

- Open Object grid
- Execute some Grid functions

**Comment by dvesh3** [comment]
Fixed by #12411
