### ISSUE TITLE
[Bug]: Sort by CS in a grid

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#12407]
### Expected behavior

Grid is sorted or deactivate sort for CS

### Actual behavior

![image](https://user-images.githubusercontent.com/104770750/173382879-73216d1b-7a20-4974-a789-f9e37a24c398.png)

### Steps to reproduce

- Open Object grid
- Click on the column header of the CS

**Comment by dvesh3** [comment]
Invalid: ClassificationStore datatype is not supported on the grid. It is even not possible to add one now coz of https://github.com/pimcore/pimcore/pull/12411
