### ISSUE TITLE
No colorspace transformation when downloading thumbnails from backend

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#1241]
There are multiple options to download thumbnails when you open an image in the backend. With the preserveColor-Option introduced in 19eb5f3 and 1306e02, the generated images will preserve their colorspace, even when converting from a CMYK TIF to jpg.

Is this intentional, since the preserveColor-Flag gets explicitly set to true for jpegs in the Admin_AssetController? If so, it would be great to have the option to disable this behaviour.

**Comment by brusch** [comment]
#3050 introduced the possibility to specify custom thumbnails for download, that should make the this issue obsolete.
