### ISSUE TITLE
[Bug]: Batch remove doesn't work on CS attributes

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#12415]
### Expected behavior

remove the selected value

### Actual behavior

set the selected value

### Steps to reproduce

- Create CS store
- Create test multiselect attribute with few options
- Add it to Class
- Open Grid Options and add multiselect attribute in grid
- Try to use Batch remove option

**Comment by robertSt7** [comment]
see #12313

**Comment by dvesh3** [comment]
Fixed by #12418
