### ISSUE TITLE
[Improvement]: use maxHeight instead of height in advancedManyToManyObjectRelation/advancedManyToManyRelation....

### ISSUE THREAD

**Issue by ctippler** [pimcore/pimcore#12421]
### Improvement description

In the object class editor we can define the height for 
advancedManyToManyObjectRelation, 
advancedManyToManyRelation,
manyToManyObjectRelation,
manyToManyRelation

data types. The height is set in ExtJs as "height" attribute of the panel. 
https://github.com/pimcore/pimcore/blob/9b9404ef17e9c7af644231dfb47bb7ee18e20b31/bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js#L417

This has the drawback that the editable has always this hight, also if no items were added.  
![image](https://user-images.githubusercontent.com/8791970/173684752-84978b6d-5eba-4e1b-b306-4b97528dd815.png)

Instead of using the height attribute we should use the "maxHeight" attribute. 
`
maxHeight: this.fieldConfig.height,
`

This way the panel could take up to e.g. 300px height and doesn't waste space if it is empty.
If using the maxHeight attribute is ok, i could probably create a PR.

Regrads,
Christian

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
