### ISSUE TITLE
GUI Grid : Filtering date ON don't work (empty result)

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1243]
If you try to filter some date column using "ON" feature, it don't work (send empty result list) even if there is a row having the date asked in the filter.
I think it is a global problem in the grid filtering for date ON feature as other grids are impacted too.

It is reproducible it on the demo, for instance delete an element, go to the Recycle Bin and try to filter the Date using ON fetaure on the date where the element has been deleted. Result grid will be empty.

![date](https://cloud.githubusercontent.com/assets/9025839/22507098/1fc319a4-e884-11e6-9ea3-3eee00a0eea8.png)

**Comment by weisswurstkanone** [comment]
works for date fields in the normal object grid. fixed it for datetime right now.

**Comment by weisswurstkanone** [comment]
fixed for the recycle bin grid as well ...

build #4049
