### ISSUE TITLE
[Task]: Deprecate Wkhtmltopdf

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#12431]
### Improvement description

As  [wkhtmltopdf is no longer being maintained](https://wkhtmltopdf.org/status.html) - we should also deprecate the support in Pimcore and remove it in Pimcore 11. 

This is about the Web2Print and the preview topics.

**Comment by podarcis** [comment]
I guess Headless Chrome (#7108) will be the successor to a free option for Web2Print? If yes, I suggest we also add the required dependencies to the official Pimcore Docker image.

**Comment by jdreesen** [comment]
Should be already there, see pimcore/docker#67 and https://github.com/pimcore/docker/commit/4261c4e74c07b0ea8f841480d4746fd880fbc0ff

**Comment by podarcis** [comment]
@jdreesen Not sure about that. The Web2Print processor uses Composer package `spiritix/php-chrome-html2pdf` (requires Node, which is not present), while the image processor uses `chrome-php/chrome` (utilizes Chromium binary).

**Comment by podarcis** [comment]
Seems with #11673 the Web2Print processor will be changed to use chrome-php/chrome as well.

**Comment by brusch** [comment]
@jdreesen yes, but I think NodeJS is missing, which is required as well. 🤔
