### ISSUE TITLE
[Bug][Backend]: Wrong Date and DateTime value

### ISSUE THREAD

**Issue by foxgreek** [pimcore/pimcore#12435]
### Expected behavior

If I select the date 2022-07-02 01:00 I expect to see the same date in the frontend.

### Actual behavior

If I use a Date or a Date&Time field in a dataObject und select a date, e.g. 2022-07-02 01:00 I get the wrong date in frontend: 2022-07-01 11:00 PM.

### Steps to reproduce

Select in a news DataObject (pimcore demo) the date 2022-07-02 01:00.
<img width="354" alt="Bildschirmfoto 2022-06-17 um 12 20 12" src="https://user-images.githubusercontent.com/40141606/174279569-63f3f737-8b4b-415a-abe9-a52655da2a89.png">

You will see the wrong date in frontend 2022-07-01 11:00 PM
<img width="256" alt="Bildschirmfoto 2022-06-17 um 12 20 21" src="https://user-images.githubusercontent.com/40141606/174279613-aee05de8-caca-4b96-928a-53b2ed5b6c92.png">

Any ideas why this happens?

**Comment by mcop1** [comment]
@foxgreek Can you please check your config.yaml and see if you have set a timezone? Default timezone is UTC.

**Comment by foxgreek** [comment]
@mcop1 No sorry - I haven't set another timezone. It it is the default timezone. The wrong date occurs in the demo too.

**Comment by mcop1** [comment]
@foxgreek ok, could you please try to set the timezone to your local timezone?

![image](https://user-images.githubusercontent.com/89011527/174739939-32e0b075-d9c5-4bf7-be61-eba1302e2542.png)
```
pimcore:
    general:
        timezone: Europe/Berlin
```

The problem occurs in the demo too, because it is set to UTC and I am guessing you are somewhere in the CET space, right?

**Comment by foxgreek** [comment]
@mcop1 thanks for your reply. It's working now! Is it possible to add this information to the docs? I didn't find any information about it in the docs and the upgrade notes.

**Comment by mcop1** [comment]
We are working on an approach to refactor the timezone handling, but until then I will add an information to the docs.

**Comment by dvesh3** [comment]
Docs Added #12454
