### ISSUE TITLE
Improvement : Add filtering column on Notes & Events panel

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1244]
In case there is a lot of notes and events for an element, it begin to be hard to find specifical information as there is only ordering but no filter for the grid.

I think it will be valuable to add filtering on the columns of Notes & Events of the element (document, asset, object) panel:
- Type : string filter
- Title: string filter
- Description: string filter
- User: string filter
- Date: date filter

![notes](https://cloud.githubusercontent.com/assets/9025839/22507529/41a8099c-e886-11e6-9f37-677156452e75.png)

Same could be added to the global "Notes & Events" panel (i don't think it is needed to add filtering on "Element" column as a user can go to the Notes & Events of the element to have only the one linked to it).

With this it would be possible to seach for specific type of notes, specific notes from a user, events wich happen between two dates, ... It would make usage more friendly for enduser.

**Comment by weisswurstkanone** [comment]
build 60
