### ISSUE TITLE
Pimcore v10.4.3 Not able to search Assets Metadata

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#12440]
Hello @dvesh3 @fashxp 

I can not able to Search Assets metadata on the Assets List view on Pimcore v10.4.3. 
https://demo.pimcore.fun/admin/

Pim v10.4.3
![image](https://user-images.githubusercontent.com/52573912/174526310-823cf94e-e74f-4d34-917f-723009ea1b59.png)

Pim v6.8.4
![image](https://user-images.githubusercontent.com/52573912/174526401-733e9ad9-32c4-43d7-9c55-68b366b1e30b.png)

Earlier we use the Pimcore v6.8.4 and I can search the Metadata.

So is there any configuration or issue, pls guide.

_Originally posted by @rushit-credencys in https://github.com/pimcore/pimcore/discussions/12438_

**Comment by aryaantony92** [comment]
Fixed by #12447
