### ISSUE TITLE
Add type declarations

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#12469]
### Improvement description

Follow up to: 
#12240
#12238 
#12237 
#12236 
#12235 
#12234 
#12233 
#12232 
#12231 
#12230 
#12229 
#12228
#12227 
#12226 
#12225 
#12224 
#12223 
#12222 
#12221 
#12220 
#12217 
#12216 
#12215 
#12214 
#12213 
#12212 
#12211

**Comment by fashxp** [comment]
same as https://github.com/pimcore/pimcore/issues/12240 ?

**Comment by brusch** [comment]
Yep - closed
