### ISSUE TITLE
[Improvement]: Slow "object_url_slugs" queries / add indices

### ISSUE THREAD

**Issue by hethehe** [pimcore/pimcore#12486]
### Improvement description

**Problem:**
If you have a project with multiple sites (e.g. 4) and multiple languages (e.g. 6), then pimcore can generate up to 30 URL slugs for one object (every site + the fallback) * every language).

When you open a product in the backend, the URL slugs are queried:
SELECT * FROM object_url_slugs WHERE fieldname = 'slug' AND ownertype = 'localizedfield' AND position = 'de' AND objectId = '1234'
This query slows down with every new site, language, product.

**Solution:**
    Add an index for (fieldname, ownertype, position and objectId)

**Comment by robertSt7** [comment]
@hethehe Thank you for reporting the issue. Since you have already described the solution, do you also want to create the PR?
