### ISSUE TITLE
[Bug]: Classification Store - No "Are you sure" message on click X

### ISSUE THREAD

**Issue by niederberger-qw** [pimcore/pimcore#12494]
### Expected behavior

If you click here:
![grafik](https://user-images.githubusercontent.com/85213755/175249565-40e88310-726b-4f71-b958-39999bda31b0.png)

It should be  message like
![grafik](https://user-images.githubusercontent.com/85213755/175249835-6f43460f-2c80-427e-87e1-67b195dad862.png)

### Actual behavior

It's deletes directly the group or the key definition

### Steps to reproduce

It's on every group in the classification store.

**Comment by dvesh3** [comment]
already fixed by https://github.com/pimcore/pimcore/pull/12410. thanks!

**Comment by fashxp** [comment]
already fixed by https://github.com/pimcore/pimcore/pull/12102
