### ISSUE TITLE
[Bug]: AssetUpdateTasksMessage queues endless for Video with errors

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#12504]
### Expected behavior

Pimcore should only try once to create run AssetUpdateTasksMessage for Video

### Actual behavior

it runs it endless due to how `AssetUpdateTaskHlandler` works and how `AssetUpdateTasksMessage` is queued.

### Steps to reproduce

Upload a broken Video and see how the messages get spammed.

**Comment by dpfaffenbauer** [comment]
https://user-images.githubusercontent.com/5981845/175475775-a7301112-2e2f-4b0a-8b54-9b3efd98b7a5.mp4

like this MP4

**Comment by aryaantony92** [comment]
@dpfaffenbauer Could you please share the broken video for testing. Thanks!

**Comment by dpfaffenbauer** [comment]
https://github.com/pimcore/pimcore/issues/12504#issuecomment-1165244354

**Comment by aryaantony92** [comment]
It was unable to download the video directly.  Thanks!

**Comment by dpfaffenbauer** [comment]
[Screenshot 2022-06-24 at 09.15.11 copy 4.mp4.zip](https://github.com/pimcore/pimcore/files/9083876/Screenshot.2022-06-24.at.09.15.11.copy.4.mp4.zip)

It's basically an empty file with an mp4 suffix

**Comment by dvesh3** [comment]
Fixed by #12692
