### ISSUE TITLE
[Bug]: use of "Operator Required By" in Gridconfig results in SQL exception

### ISSUE THREAD

**Issue by seybsen** [pimcore/pimcore#12501]
### Expected behavior

Operator Required By should return an array with all dependants

### Actual behavior

Results in database error

### Steps to reproduce

1. In /admin navigate to Data Objects -> Product Data -> Cars -> ac cars (https://demo.pimcore.com/admin/login/deeplink?object_79_folder)
2. Open Grid Configuration
3. Drag Operator Required By to Selected grid columns
4. Dismiss Settings window
5. See error message

Seems to be related to these two lines:
https://github.com/pimcore/pimcore/blob/10.x/lib/DataObject/GridColumnConfig/Operator/RequiredBy.php#L76-L77

**Comment by mcop1** [comment]
Resolved by https://github.com/pimcore/pimcore/pull/12493
