### ISSUE TITLE
[Bug]: LocationAware Custom Layout dropdown showing definitions of other Classses

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#12508]
### Expected behavior

Only the custom layouts related to the class of which you opened the custom layout popop for should be appearing in the dropdown.

### Actual behavior

![image](https://user-images.githubusercontent.com/6014195/175530564-9a146b4b-ca2a-4086-92e4-26d1d4316c8f.png)

It's showing custom layouts of other classes as well

### Steps to reproduce

After #12428 using LocationAwareConfigRepository, just open `Configure Custom Layouts` and the dropdown to see there are custom layouts.

NB: It's a "bug" of something i've merged in 10.x and didn't realized that this is not expected, but it should belong to `10.5`

**Comment by dvesh3** [comment]
we need to revert https://github.com/pimcore/pimcore/pull/12428 as `setCondition()` will not work anymore on CustomLayout\Listing as the Dao is moved to `LocationAwareConfigRepository` so if you have existing sql conditions then it will not apply anymore on the listing. Then it is considered as a BC break.
