### ISSUE TITLE
Composer: do not run migrations automatically on post update

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#12514]
### Improvement description

see: https://github.com/pimcore/skeleton/blob/469496120e95dd7755d7368c3ac168363ede20b0/composer.json#L34

**Comment by cancan101** [comment]
What was the reason for removing `Pimcore\\Composer::executeMigrationsUp` from `post-update-cmd` in the composer file?

**Comment by brusch** [comment]
@cancan101 it should be up to the developer to decide when the migration scripts should run, as this heavily depends on the deployment method.
