### ISSUE TITLE
[Task] Move Personalization to repository pimcore/personalization-bundle

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12523]
### Improvement description

Move `Personalization` to repository `pimcore/personalization-bundle`

**Comment by dvesh3** [comment]
Remove `geoip2/geoip2` from Core composer.json when extracting bundle.

Add the bundle info to `poeditor-export-action` for the translations after extracting the bundle

**Comment by dvesh3** [comment]
Re-opening for extraction to own repo.
