### ISSUE TITLE
[Task] Move Web-to-print to repository pimcore/web-to-print-bundle

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12525]
### Improvement description

Move `Web-to-print` to repository `pimcore/web-to-print-bundle`

Related and depends on https://github.com/pimcore/pimcore/pull/14047

**Comment by NiklasBr** [comment]
Will https://github.com/pimcore/web2print-tools remain it's own bundle? It would make some sense to combine these two now that the regular web2print also exists as a bundle.

**Comment by kingjia90** [comment]
Re-opening, only the extraction from Core/Admin Bundles into a bundle under `/bundle` was done. 
The next step is moving all to its own repository.

**Comment by kingjia90** [comment]
some thoughts after reading this

> Will https://github.com/pimcore/web2print-tools remain it's own bundle? It would make some sense to combine these two now that the regular web2print also exists as a bundle.

if  not combined, 
- should be added as depedant bundle/composer suggest?
- the naming prefix inconsistency, `web2print-tools` and `web-to-print-bundle`, should rename one? eg. `web-to-print-tools` or `web2print-bundle`?

**Comment by mattamon** [comment]
I think it would be better if they were combined tbh.
Would you only use web2print-tools without the bundle?

I would use the new scheme so web-to-print-tools.
