### ISSUE TITLE
[Task] Move Simple Backend Search to SimpleBackendSearchBundle within bundles folder in pimcore/pimcore repository

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12528]
### Improvement description

Move `Simple Backend Search` to `SimpleBackendSearchBundle` within bundles folder in `pimcore/pimcore` repository

**Comment by mcop1** [comment]
Be aware of other occurrences where the search dialog might be used, e.g. search in relations.

**Comment by Corepex** [comment]
Steps to do:

1. create new bundle in `dev/pimcore/pimcore/bundles` (name: `SimpleBackendSearchBundle`)
2. move files from `AdminBundle/Resources/public/js/pimcore/element/selector/*` to new bundle `SimpleBackendSearchBundle/Resources/public/js/pimcore/element/selector/`
3. ?? change the namespace of the `selector` files ??
4. move `quickSearchCombo` to new bundle -> https://github.com/pimcore/pimcore/blob/10.6/bundles/AdminBundle/Resources/public/js/pimcore/startup.js#L952
5. move toolbar search navigation entry (`searchMenu`) to new bundle -> https://github.com/pimcore/pimcore/blob/10.6/bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js#L1108
6. recheck if field definitions still work (`relations`, `image`, `image gallery`, `image advanced` and `video, link`)
7. recheck editable (in documents) - some of the editables implement a search (see field definitions)

**Comment by Corepex** [comment]
Additional Steps:

1. check if `pimcore:search-backend-reindex` command should also be migrated
2. add bundle to `.github/ci/files/config/bundles.php`

**Comment by brusch** [comment]
yep, should be migrated as well
