### ISSUE TITLE
Objects country multiselect empty in ExtJS 6

### ISSUE THREAD

**Issue by ilmarsZ** [pimcore/pimcore#1252]
- [x] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [x] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [x] There's no existing ticket for the same issue
 
### Expected behavior 
If objects country multiselect property has "Restrict Selection To" countries selected, then in object edit view country multiselect only has countries selected in class definition.
### Actual behavior  
If object class country multiselect property has restricted selection values defined then in object edit view this multiselect is empty (no countries in list). This error happens only in new Ext JS 6 admin UI AND if anything is selected in class definition country multiselect "Restrict Selection To" field. Id old UI everything works as expected.  
### Steps to reproduce  
Add Countries (multiselect) property to class with at least one country selected in "Restrict Selection To".
Open or create object of this class. Countries (multiselect) has no values to select.

  
  
![example](https://cloud.githubusercontent.com/assets/1984047/22544158/4cc668e4-e93c-11e6-8257-c795fb36a947.png)

**Comment by weisswurstkanone** [comment]
fixed in #4049
