### ISSUE TITLE
[Task] Remove Database Explorer

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12520]
Since we're going away from adminer it doesn't make sense to move it to a bundle, we just remove it.

**Comment by NiklasBr** [comment]
Adminer looks effectively abandoned, [not a single commit in over a year](https://sourceforge.net/p/adminer/git/commit_browser) and with [some outstanding bugs](https://github.com/pimcore/pimcore/issues/11304) I wonder if it is a good idea to name this bundle to something more generic like `pimcore/database-explorer-bundle` (similar as the file-explorer-bundle)?

**Comment by brusch** [comment]
@NiklasBr very good point!
