### ISSUE TITLE
[Task] Move Admin UI Classic to repository pimcore/admin-ui-classic-bundle

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12531]
### Improvement description

Move `Admin UI Classic` to repository `pimcore/admin-ui-classic-bundle`

**Comment by dvesh3** [comment]
Also consider for extraction:
- `\Pimcore\Tool\Admin`
- `EditmodeListener`

**Comment by fashxp** [comment]
https://github.com/pimcore/pimcore/pull/13297
