### ISSUE TITLE
[Task] Move Web Analytics to repository pimcore/web-analytics-bundle

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12533]
### Improvement description

Move `Web Analytics` to repository `pimcore/web-analytics-bundle`

**Comment by dvesh3** [comment]
Initial idea was to separate marketing and analytics into two different repos, however later decision was to keep them into one [bundle ](https://github.com/pimcore/pimcore/issues/12524)as the analytics and marketing are closely coupled and there's not much left in marketing without analytics.
