### ISSUE TITLE
[CustomLayouts] Add filter option on listing

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#12544]
### Feature description

 - Add option to filter custom layout listing which should replace `setCondition` on Pimcore 11
 - Deprecate `setCondition`

**Comment by mcop1** [comment]
We can do something like
https://github.com/pimcore/pimcore/blob/07f2bae8a1aef1c923fdd78d66602bf2cde29f1a/bundles/AdminBundle/Controller/Admin/Document/DocumentController.php#L775

Maybe we can extract the filter methods, properties, .. to a separate trait? That way we don´t need to extend from JsonListing class. Use the trait in listing class for CustomLayouts and in JsonListing class.

**Comment by mcop1** [comment]
@dvesh3  what about `getOrder` method? I think we would need to do same as for `getFilter` ?

**Comment by dvesh3** [comment]
@mcop1 good point. yes, I would also cover ordering with new method.
