### ISSUE TITLE
[Improvement]: Drag & Drop in asset list not working

### ISSUE THREAD

**Issue by Fabian-Hofer-Mastertent** [pimcore/pimcore#12554]
### Expected behavior

In the tree-view of the assets it is possible to drag&drop one or more elements and move them fron one folder to another.
The same should work if moving an asset from the main asset view (preview or list view) to the three view.
After selecting multiple assets in the list-view, the expected behavior should be, that all selected elements are moved to the new folder when dropping on the tree-list.

Testet in the public demo with Version 10.4.4

### Actual behavior

When dragging an asset from the asset-preview or list-view to the tree view, an empty message window opens and nothing happens. The window disappears after a few seconds.

![image](https://user-images.githubusercontent.com/99820683/176434351-a68f93bd-4dff-498c-aae9-33cfafd67ec7.png)

### Steps to reproduce

1. open the "Assets"-view
2. drag & drop an asset from the preview- or list-view to the tree-list on the side.

![image](https://user-images.githubusercontent.com/99820683/176434830-f0f62d57-dcd2-4479-a18e-cd11cf1bfd54.png)

**Comment by dvesh3** [comment]
Fixed by disable dragging assets from Asset Preview and List view in #12681
