### ISSUE TITLE
Travis Builds

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#1255]
PHPUnit released Version 6 and Pimcore includes PHPUnit with * in composer.json. Therefore builds are failing because it is not compatible to 5. PHPUnit 6 only supports PHP 7.*. So Pimcore needs to require PHPUnit 5.7.* within its composer.json for Unit Tests to be runable.

This issue also affects CoreShop's Unit Tests, because CoreShop uses Pimcore's PHPUnit dependencies for its tests.

**Comment by maff** [comment]
thx :)
