### ISSUE TITLE
[Bug]: Exception when clicking on folder under dataobjects in Backend

### ISSUE THREAD

**Issue by Stefan-JustMe69-SQ** [pimcore/pimcore#12569]
### Expected behavior

Using pimcore actual version with coreshop.

When I try to click on folder coreshop, I expect, as on every other folder in dataobjects, a list of objects is listed, or a selection appears where I can choose which objects I like to see listed.
I see described Excption every time I click on the folder 'coreshop'

expected:
no exception, existing classes should be selectable

### Actual behavior

Exception is raised:
```
URL: /admin/object/get-folder
Message: Call to a member function getId() on null
Trace: 
in /var/www/dev/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php:777
#0 /var/www/dev/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(729): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->prepareChildClasses()
#1 /var/www/dev/vendor/symfony/http-kernel/HttpKernel.php(152): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->getFolderAction()
#2 /var/www/dev/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#3 /var/www/dev/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle()
#4 /var/www/dev/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle()
#5 {main}
```

### Steps to reproduce

not sure how this can be reproduced. On my system every time.

I could provide a PR if wanted, that null-objects are ignored for building the selection list.

**Comment by mcop1** [comment]
@JustMe69 
Hello :) 
A pull request would be highly appreciated. 
Please make sure to link it to this issue. 

Thank you for your efforts!
