### ISSUE TITLE
newsletter test without Placeholders

### ISSUE THREAD

**Issue by mediafant** [pimcore/pimcore#1256]
### Steps to reproduce  
  Send an Newsletter with Placeholders in an WYSIWYG.
Placeholders in final sending are replaced by firstname, lastname ... but in test-sending it doesn't work.

**Comment by LosHawlos** [comment]
I came across this, too.

A solution could be a dropdown where you select one person out of the recipients list, that is then used for personalisation in the newsletter test send. This List of recipients could be limited to e.g. 20.
That way it would be much easier to test the newsletter personalisations.

I currently work around this by creating different custom reports that select only a few specific recipients that I only use for testing and do a real sendout to this test list.

**Comment by fashxp** [comment]
I like your idea. would you like to prepare a pull-request? we would definitely accept it.

**Comment by brusch** [comment]
Waiting for a PR ... closed for now.
