### ISSUE TITLE
php-cli - executable-name in system-config

### ISSUE THREAD

**Issue by mediafant** [pimcore/pimcore#1257]
# Feature Request 
## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [ x] There is no existing issue regarding the same topic

## Feature description 

There are some systems they use other names than "php" (for example "php-cli") so it would be nice if it is possible to define it in system-config-file and use it in composer.php like this:

public static function getPhpCli()
    {
        $phpCli = Config::getSystemConfig()->general->phpCli;
        if($phpCli) {
            $php = $phpCli;
        } else {
            $php = "php";
        }
        return self::getExecutable($php,true);
    }

Andreas

**Comment by dpfaffenbauer** [comment]
This should work for you:

https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Tool/Console.php#L68

You need to define the executable in your di.php:

```php
<?php
return [
   "pimcore.executable.php" => "/usr/bin/php-cli"
]
```

PS: Not tested, but should work this way.

**Comment by mediafant** [comment]
Great - Thanks !
