### ISSUE TITLE
[Bug]: "Exclusive locks are not supported for this stream" when rebuilding classes

### ISSUE THREAD

**Issue by wuw-marc** [pimcore/pimcore#12582]
### Steps to reproduce

1. Have a setup where the data classes are stored on NFS (e.g. k8s cluster)
2. Change a class
3. Enjoy error message ;-)

### Actual behavior

An error message is produced: 
```
user@server:~/html$ bin/console pimcore:deployment:classes-rebuild -c -d -n

In File.php line 117:
                                                                                   
  Warning: file_put_contents(): Exclusive locks are not supported for this stream  
                                                                                   

pimcore:deployment:classes-rebuild [-c|--create-classes] [-d|--delete-classes]
```

### Expected behavior

No error message is produced and all classes are rebuilt.

### Further details:
We had been using version 10.3.6 up until yesterday when we updated to 10.4.4. Previously we didn't have this issue.

When editing the vendor code in said line to pass `0` instead of `self:$default_flags` everything works (as would be expected from reading the error message - just wanted to mention it for detail's sake).

We already know that NFS apparently doesn't support exclusive locks in general so if there is any setting or something similar that we missed that could have prevented this error, we're happy being told about it.

**Comment by mcop1** [comment]
@wuw-marc we changed that part with this pr https://github.com/pimcore/pimcore/pull/9032 . But that was already in Pimcore 10.0. Are you sure you didn´t change anything else in your configuration?
Could you please share more information, e.g. the complete call stack?

**Comment by wuw-marc** [comment]
@mcop1 Unfortunately I can't provide you with a complete call stack as I cannot reproduce the error locally and don't have the necessary access to the production environment to get one.

Have there been any changes in the process between starting the pimcore:deployment:classes-rebuild command and actually writing the file that might explain this?

**Comment by woellundwoell** [comment]
@mcop1 What is the reason for the lock at this point? With the knowledge we could possibly provide a PR. ;)

**Comment by brusch** [comment]
The reason for the lock is described in detail here: https://github.com/pimcore/pimcore/pull/9031
If you'd like to change the default flag you can use the following code in your [startup.php](https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Configuration.html#page_Adding-logic-to-the-startup-process): 

```php
\Pimcore\File::setDefaultFlags(0); 
```

I don't know where you got the info from that NFS doesn't support locking, but I think this is just wrong at least for NFSv4.
