### ISSUE TITLE
Property - Description not saved

### ISSUE THREAD

**Issue by mediafant** [pimcore/pimcore#1258]
### Steps to reproduce  
On saving property to document, description isn't saved. Also last option heredity not saved.
### Code example 
```php
$this->view->setProperty('newsletterLastDate',date('d.m.Y H:i',$ts),$ts,false)->save();  
```

**Comment by brusch** [comment]
Which description?

**Comment by brusch** [comment]
ah, you mean ... 
![image](https://cloud.githubusercontent.com/assets/142037/24142116/e23d7242-0e25-11e7-9587-0324163ef262.png)

Yes, we cannot change the signature of `setProperty()` so you'd need to create the property object manually and add it to the document, like: 
https://github.com/pimcore/pimcore/blob/d8d539516d20fc0150b005afbfa7834796c729b3/pimcore/models/Document.php#L1251-L1251
