### ISSUE TITLE
[Bug]: You have requested a non-existent parameter "20"

### ISSUE THREAD

**Issue by yamenalahlas** [pimcore/pimcore#12592]
### Expected behavior

Folder names for assets should be freely selectable by the user

### Actual behavior

if the user creates folder name as " background & logo " and then uses public url for an image in this folder as custom admin login background the error message comes up (You have requested a non-existent parameter "20" )

### Steps to reproduce

1. add a new Folder in assets with this name (background & logo)
2. add an image to this folder
3. open the image info and copy the public url for this image
4. go to system settings
5. add the copied url to Custom Login Background Image
6. in debuging mode
<img width="1114" alt="Screenshot 2022-07-05 at 19 32 14" src="https://user-images.githubusercontent.com/79138176/177383931-3acfd7be-8ebc-4328-b7f0-a43c177b1208.png">

**Comment by jdreesen** [comment]
Sounds like it's *urlencoded* (`background%20%26%20logo`) and Symfony somehow thinks it's a parameter because of the `%...%` xD

**Comment by dvesh3** [comment]
Fixed by #12632
