### ISSUE TITLE
Some objects cannot be saved after Pimcore update because the key is invalid.

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#1259]
https://github.com/pimcore/pimcore/commit/c58585ae5109888344f1d055fe8772e4923281b3

A trailing dot in the key is not valid anymore. If you updated your Pimcore and already had objects with trailing dots, they cannot be saved anymore.  

We should either have an update script that fixes this new invalid keys or state it in the update notes.

**Comment by brusch** [comment]
Thanks!
