### ISSUE TITLE
[Bug]: Wysiwyg Content Security Policy error

### ISSUE THREAD

**Issue by lukutisz** [pimcore/pimcore#12594]
### Expected behavior

Wysiwyg editor fully working

### Actual behavior

Any special function of Wysiwyg editor cannot be used due to the Content Security Policy errors.

Same is happening in my local env and also in the pimcore official demo admin account.

![image](https://user-images.githubusercontent.com/66670706/177416856-2705b9ea-40d3-4820-b51e-3401d023bfc2.png)
![image](https://user-images.githubusercontent.com/66670706/177416909-59a434fe-3b57-4b07-baba-7dd839d6189f.png)

### Steps to reproduce

Open Wysiwyg text editor
Try clicking on any of buttons, as example Create table

**Comment by dvesh3** [comment]
Seems like CKeditor 4 does not properly support content security policy. please see https://github.com/ckeditor/ckeditor4/pull/254#issuecomment-357099415

This will be fixed with https://github.com/pimcore/pimcore/issues/2499

**Comment by brusch** [comment]
Actually we need to add `'unsafe-inline'` to our demos for now.

**Comment by dvesh3** [comment]
Fixed by https://github.com/pimcore/pimcore/issues/2499
