### ISSUE TITLE
[Improvement]: abstract web2print to support replacing it with alternative providers like Gotenberg

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#12607]
### Improvement description

See https://github.com/pimcore/pimcore/issues/11673#issuecomment-1165685397

A possible alternative (includes PHP client): https://gotenberg.dev/

Ideally, Pimcore would allow replacing the PDF / page screenshot tool to allow decorating.

**Comment by brusch** [comment]
Actually I'm thinking of making Gotenberg even the default implementation and use it in our default `docker-compose.yml` files. This would shrink our `pimcore/pimcore` images massively and if you don't need it you can just kick it out.

**Comment by dkarlovi** [comment]
@brusch I can see value in having it be bundled for simpler install, but for more advanced teams and deployments, the separation would be very beneficial. You could have say 10 or 100 Pimcore installs in a cluster all sharing a common print service.

**Comment by brusch** [comment]
Sure, it's just about having a ready to use `docker-compose.yml` - of course you're still free to adapt it to your setup.
