### ISSUE TITLE
[Bug]: Paging in Back Office is not working

### ISSUE THREAD

**Issue by MercuryKojo** [pimcore/pimcore#12605]
### Expected behavior

if there are more than 10 orders in Pimcore the backoffice should show pagination at the bottom and Total Orders should show the correct count

### Actual behavior

Back Office only shows count of current page and does not show total count

![image](https://user-images.githubusercontent.com/12114276/177557604-fdb366f0-43fc-49ae-aa04-c148a25a7899.png)
![image](https://user-images.githubusercontent.com/12114276/177557716-1fdb7a63-f4db-4a6b-8e57-679feac8b281.png)

This commit caused the problem:
https://github.com/pimcore/pimcore/commit/4013e6c6df912c4a060d53e1a854b8c2b743289d

Reverting this, fixes the pagination issue

### Steps to reproduce

Commit more than 10 Orders and open Back Office

**Comment by brusch** [comment]
#11322 was the reason for 4013e6c6df912c4a060d53e1a854b8c2b743289d - so just reverting is not the solution

**Comment by MercuryKojo** [comment]
I quessed there was a reason for it. That's why I didn't make a PR
Comparing it to the doctrine pagination listener in the Knp Package it seems it would be the correkt logic to revert it and maybe search for a solution in the Elastic Search part?
