### ISSUE TITLE
Translations not cached when more than 5K records in translation_website

### ISSUE THREAD

**Issue by cehrig** [pimcore/pimcore#1260]
If there are more than 5000 records in translation_website, caching for website translations is disabled.

See: Pimcore\Model\Translation\AbstractTranslation\Listing\Dao:201

It would be good to have this value configurable.

**Comment by weisswurstkanone** [comment]
build #4049

Place the following call in your \website\config\startup.php (or wherever it best fits your needs) to override the current default value of 5000 items.

\Pimcore\Model\Translation\AbstractTranslation\Listing::setCacheLimit(9999999);
