### ISSUE TITLE
[Improvement]: Definitions Bulk export/import

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#12600]
### Improvement description

![image](https://user-images.githubusercontent.com/279826/177525188-4077466e-e6a6-4c37-8deb-ac15b119b648.png)

Some thoughts:

1. Classification Stores and their definitions are unfortunately not included.
2. Neither are Quantity Values.
3. It should not be titled "Export" when importing.
4. Position is too far down to the right.
5. It would be good if it said which definition is currently imported.
6. Once the import is done, you are not greeted with a confirmation of any kind, the progress bar in the bottom right corner disappears and the import window looks just like nothing has happened.

**Comment by fashxp** [comment]
related to https://github.com/pimcore/pimcore/issues/12600

**Comment by NiklasBr** [comment]
That's the same issue...
