### ISSUE TITLE
Relation getter method sometimes returns ElementDescriptor object

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#12638]
### Expected behavior

Getter methods of relational fields should always return the related element.

### Actual behavior

In some cases an `ElementDescriptor` object gets returned - which then causes for example
`TypeError: Pimcore\Model\DataObject\Product::getBrand(): Return value must be of type ?Pimcore\Model\Element\AbstractElement, Pimcore\Model\Element\ElementDescriptor`

I do not know how to reproduce it currently but saw that in https://github.com/pimcore/pimcore/blob/5a7729d37b353ae13271a2447311efe43ba33382/models/Element/Recyclebin/Item.php#L342-L363 for recycle bin items relations get replaced by `ElementDescriptor` objects. But when restoring those recycle bin items, the element descriptors are not resolved again https://github.com/pimcore/pimcore/blob/5a7729d37b353ae13271a2447311efe43ba33382/models/Element/Recyclebin/Item.php#L389
Or is this done on another place?
In Pimcore backend the error does not occur - only when I use the getter method. But admin backend loading is not handled with the getter methods anyway, so probably the `ElementDescriptor`s get resolved somewhere where the getter methods do not get.

In other places like version marshalling and unmarshalling, the `ElementDescriptor`s get resolved when the version gets restored / published, see https://github.com/pimcore/pimcore/blob/9d5c6fc46ac1bd3bcdaacf39dcce256b78bf16bb/models/Element/Service.php#L1573-L1607

### Steps to reproduce

Currently don't know...

**Comment by fashxp** [comment]
do you have already some more information on how to reproduce?

**Comment by BlackbitDevs** [comment]
@fashxp Actually not. From our client projects it happens only in Pimcore 6.9 as far as I know - but this is only a gut feeling. And it mainly happens in preUpdate / postUpdate event handlers being unreproducible (when the object gets saved again, there is no error). As described above I suspect the recycling bin or restoring a version. As far as I remember the relations get saved in the recycling bin versions - what happens on restoring of an object if a related object does not exist anymore?

**Comment by mcop1** [comment]
@BlackbitDevs I tried to reproduce this issue again with deleted and restored data objects, but I just couldn´t do it. If you restore a data object with a relation, that was deleted in the meantime, it still works. 
Any chance you have new infomations/hints on this?

**Comment by BlackbitDevs** [comment]
Hmm, have no idea. Just noticed that it happened again, I saw this error
`Object #35 could not be saved. Reverted changes. Error: TypeError: Pimcore\Model\DataObject\Objectbrick\Data\Medien::getArtikelbild(): Return value must be of type ?Pimcore\Model\Asset\Image, Pimcore\Model\Element\ElementDescriptor returned`

**Comment by mcop1** [comment]
There was a similar issue with the preview a while back: https://github.com/pimcore/pimcore/issues/9521
We fixed that one and we worked on it again. But still I can´t reproduce the issue with the recycle bin. 

I close this issue for now, if you have any further information please add a comment and reopen the issue. Thank you!

**Comment by BlackbitDevs** [comment]
Last week I saw that this (also) happens if there is a draft version of the object (in Pimcore 10.5 so the changes from #9537 are included and nevertheless the error occured). I will continue to watch this and notify you if I can explain the exact steps of how to reproduce the problem...

**Comment by jcalifice-basecom** [comment]
Got the same issue running Pimcore 11.2.2 and was able to reproduce it local and within demo.pimcore.fun.

Task is to import video files as assets, relate them using video data type fields inside data object and add poster image.
Szenario works fine as long as not using blocks for multiple video fields. When adding block, it get's broken.

To reproduce...

Class definition:
- Tab
-- Block 'videos'
--- Video field 'video'

Inside object editor:

- Adding block element
- Relating video
- Add image asset as poster image
- Save object
- Reload object

leads to Exception as mentioned before:

'Message: Pimcore\Model\DataObject\Data\Video::getPoster(): Return value must be of type Pimcore\Model\Asset|string|int|null, Pimcore\Model\Element\ElementDescriptor returned'

**Comment by fashxp** [comment]
could you please create a new issue, thx.
