### ISSUE TITLE
[Bug][Assets] Extracting text from assets does not work anymore

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12631]
### Expected behavior

Text can be extracted from assets and added to the full-text search index after uploading/updating an asset

### Actual behavior

command fails because it tries to send a docx/pptx/etc to ghost script ... which does not work

most likely regression of that change: 
https://github.com/pimcore/pimcore/commit/2fabce94fa9a9a13a68a9013afe183ec302bdb24#diff-463c7c3a9e135e190743ca5a25b3eee85e94d97a4fb9db2fbe67ca964198f86bR180

### Steps to reproduce

just upload an document asset like docx or pptx and watch the logs of the symfony messenger queue

**Comment by dvesh3** [comment]
Fixed by #12735 & #12770
