### ISSUE TITLE
[Improvement]: better API for filtering by many-to-many relations

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#12642]
### Improvement description

Currently, the common [many-to-many filtering API](https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Relation_Types.html#page_Filtering-for-relations-via-PHP-API) is quite convoluted, involving substring matching (?) which is unable to use regular database features like indices effectivly.

For example, let's say we have
1. `Category`
2. `Product`
3. `Product.Categories >-< Category # many to many relation`

If we now want to find all `Product` which belong to at least one from a list of categories, the current solution which looks up with `LIKE` and `object|id` seems quite poor: you'd need to construct an elaborate query which, if it worked, would perform poorly since it's doing string matching. Since all the data is there in `object_relations_X`, it seems a shame there's not a nice API which would allow doing a join and filter using it instead.

**Comment by hethehe** [comment]
@dkarlovi and others with the same concern:

I came across this post when I was looking for a similar feature.

Here [Access and modify internal object list query](https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Working_with_PHP_API.html#page_Access-and-modify-internal-object-list-query) I found a solution how to access the Doctrine Querybuilder - this helped me.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
