### ISSUE TITLE
[Bug]: LinkGenerators to not work with path/url twig extension

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12656]
### Expected behavior

thinks like `{{ url(car) }}` work in template when car is instance of a dataobject with link generator defined ... as stated here in [docs](https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Class_Settings/Link_Generator.html#page_path-url)

### Actual behavior

![image](https://user-images.githubusercontent.com/8792145/179012808-56bcb342-70ce-4f34-9231-406ee3130502.png)

### Steps to reproduce

create a template and call  `{{ url(car) }}`

**Comment by blankse** [comment]
Maybe we should update the docs. I changed it here:
https://github.com/pimcore/pimcore/pull/9694

`{{ url('pimcore_element', {'element': car}) }}` should work

**Comment by dvesh3** [comment]
Fixed by https://github.com/pimcore/pimcore/commit/31b495fc62e0c243c7f126a37c60a9f1c92311cf
