### ISSUE TITLE
[Bug]: Impossible to overwrite certain editables in the Editable Dialog in an inherited document

### ISSUE THREAD

**Issue by vintagesucks** [pimcore/pimcore#12664]
### Expected behavior

In an inherited document, all contents of editables can be overwritten in the Editable Dialog.

### Actual behavior

The following editables cannot be overwritten in an inherited document in the Editable Dialog: `image`, `video`, `wysiwyg`.

### Steps to reproduce

On https://demo.pimcore.fun/admin/?perspective=default (`admin`/`demo`):

1. Open [/en/Error-Page](https://demo.pimcore.fun/admin/login/deeplink?document_198_page)
2. Add an `Image w. Metadeta` to the document
3. Open the Editable Dialog of the added `Image w. Metadeta`
4. Fill out `Image Author` and `Some additional Text` with test data
5. Close the Editable Dialog
6. Save & Publish the document
7. Right-click the document in the document tree and select `Copy`
8. Paste the document somewhere in the document tree by selecting `Paste (Inheritance)` and `Paste as child`
9. Open the new document
10. Right-click on `Image w. Metadeta` and select `Overwrite`
11. Open the Editable Dialog of `Image w. Metadeta`
12. Overwrite `Image Author` and `Some additional Text` with new test data
13. Close the Editable Dialog
14. Save & Publish the document
15. Reopen the document
16. Open the Editable Dialog of `Image w. Metadeta`

→ `Some additional Text` (`wysiwyg`) contains the initial data, not the new data. 

Video:

https://user-images.githubusercontent.com/13335308/179217701-744914be-bb59-4143-a181-de84b1405ca3.mp4

---

Some hints I could find in my debugging that might be helpful:

1. The behavior does not occur if the following `!editable.getInherited()` check is not present:

https://github.com/pimcore/pimcore/blob/acd4512a0090bb3b748c34b25354c1f9fbd809ae/bundles/AdminBundle/Resources/public/js/pimcore/document/edit.js#L405

The check was added in this commit: https://github.com/pimcore/pimcore/commit/e79302ded0d8f41c55ee51d7338639406dc523c8#diff-960b43f525b7ee9bffd3cf7e66cb7c3604c290296032af462b78ffb37cefd84a

2. Affected editables `image`, `video` and `wysiwyg` have the following `this.inherited = inherited;` line in common:

https://github.com/pimcore/pimcore/blob/acd4512a0090bb3b748c34b25354c1f9fbd809ae/bundles/AdminBundle/Resources/public/js/pimcore/document/editables/wysiwyg.js#L20-L31

This distinguishes them from the rest of the editables, which do not use `inherited` in `initialize()` at all:

https://github.com/pimcore/pimcore/blob/acd4512a0090bb3b748c34b25354c1f9fbd809ae/bundles/AdminBundle/Resources/public/js/pimcore/document/editables/input.js#L17-L27

Unfortunately, I don't understand the underlying inheritance features well enough to try to submit a pull request with a fix myself.

**Comment by jdreesen** [comment]
Is this related? #10744

**Comment by dvesh3** [comment]
@jdreesen this issue is about some editable types are not overridden in the dialog box on inherited document. 

and #10744 is a different issue, as it is about making editables in the dialog box separately inheritable as right now they just consider the property from the parent editable, which means when you overwrite areablock editable then you also overwrite all of its dialog box editables.

**Comment by dvesh3** [comment]
Fixed by #12724
