### ISSUE TITLE
[Bug]: Animated GIF Support does not work (#7075)

### ISSUE THREAD

**Issue by danielerne** [pimcore/pimcore#12667]
### Expected behavior

Thumbnail is created with animation

### Actual behavior

A still image without any animation and with wrong mime type

### Steps to reproduce

Upload a GIF image
Create a thumbnail with preserve Animation checked
Set a Cover or Frame transformation
Go to the Image and download the thumbnail

**Comment by dvesh3** [comment]
@danielerne works for me...please confirm if you have selected the correct format in thumbnail config e.g. either `ORIGINAL` or `GIF`
![image](https://user-images.githubusercontent.com/5137917/179534278-ea35ae51-29f4-40f6-91c1-5ae826bbf778.png)

**Comment by danielerne** [comment]
@dvesh3  thanks for the info. We had the format Auto. Didn't know that it needs to be set to ORIGINAL. It works now.
Is this mentioned somewhere? ;)

**Comment by dvesh3** [comment]
@danielerne yes, here https://pimcore.com/docs/pimcore/current/Development_Documentation/Assets/Working_with_Thumbnails/Image_Thumbnails.html#page_Customize-Auto-Web-Optimized-Format
