### ISSUE TITLE
[Bug]: HTML content not available in object views

### ISSUE THREAD

**Issue by DerickVanDerSandt** [pimcore/pimcore#12675]
### Expected behavior

The query table must contain HTML data.

### Actual behavior

The query table removes HTML data.

### Steps to reproduce

We currently have an object that uses the WYSIWYG controls. When viewing the data in the object store table we can see the HTML.
If we look at the corresponding query table those fields have HTML removed. When we check the view we can see that the view is based on the object_query table. As such when we query the view (in order to maintain inheritance and also not have to query relational tables) we are not able to get the HTML that was saved in the store table, this in turn means we have to join the view against the store twice (once for object and once for parent) in order to get this field.
Does anyone know why this has been implemented this way, or if it's an oversite or a workaround?
This is for pimcore 6.6.11

**Comment by fashxp** [comment]
Pimcore 6.6 is EOL ... moved to discussions.
