### ISSUE TITLE
[Feature]: Possibility to make boolean select mandatory

### ISSUE THREAD

**Issue by LukasLoeffler** [pimcore/pimcore#12678]
### Feature description

In some cases you want to make a boolean select mandatory with a default value to prevent the field of having no value.

In simple use cases its possible to use a conventional select with "True"/"False" as string values. In more complex situation where data is imported from upstream systems or exported to downstream systems, you dont want to rely on this hack.

Maybe this issue also could be by an datahub transformer to transform a string to a boolean and vice versa.

What do you guys think?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
