### ISSUE TITLE
[Improvement]: Disable edit lock for folders in Asset management

### ISSUE THREAD

**Issue by Andreas-Koepke** [pimcore/pimcore#12673]
### Improvement description

At the moment when a backend user views an Assets folder, an edit lock is automatically applied to it. This will then show a warning to anyone other user that tries to access this folder.

I suggest changing AssetController->getDataByIdAction() to exclude folders from the automatic edit lock.

I am happy to make a PR with this change.

**Comment by brusch** [comment]
Yep, that makes definitely makes sense and probably also for document and data object folders. 
A PR would be very nice 😊

**Comment by Andreas-Koepke** [comment]
PR has been added
