### ISSUE TITLE
Make traits in /lib/Extension/Bundle/Traits `@internal`

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#12684]
### Improvement description

Shouldn't be necessary to provide them publicly

**Comment by blankse** [comment]
@brusch See https://github.com/pimcore/pimcore/pull/12757#issuecomment-1427511817

**Comment by brusch** [comment]
@blankse has a valid point here, I guess we should just revert #12757 , right?

**Comment by blankse** [comment]
@brusch The StateHelperTrait was removed in https://github.com/pimcore/pimcore/pull/13393

I created a PR with a partly revert: https://github.com/pimcore/pimcore/pull/14438

**Comment by aryaantony92** [comment]
Shouldn't we need to deprecate the Trait StateHelperTrait  which is removed in https://github.com/pimcore/pimcore/pull/13393.
