### ISSUE TITLE
[Docs]: Complete preparation guide for v11 

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#12709]
### Improvement description

See: https://github.com/pimcore/pimcore/blob/10.x/doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md

We should add a complete list of things to fix/prepare for v11, deprecations, etc. probably mostly can be taken from the upgrade notes.

**Comment by dvesh3** [comment]
Fixed by #12830
