### ISSUE TITLE
Pass objectBrickLayout definition to CLASS_OBJECTBRICK_LIST_PRE_SEND_DATA event 

### ISSUE THREAD

**Issue by gjorgic** [pimcore/pimcore#12719]
### Improvement description

I wondering, why we do not pass object brick layout definition data into event object [here](https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php#L1414), and give possibility for developer to modify this layout information

Same approach is used on `..../object/get` route [here](https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L539)

**Comment by fashxp** [comment]
fixed via https://github.com/pimcore/pimcore/pull/12723
