### ISSUE TITLE
[Bug]: shared translations does not apply language permissions

### ISSUE THREAD

**Issue by kjkooistra-youwe** [pimcore/pimcore#12722]
### Expected behavior

When a user has view permissions for a language he should not be able to edit the shared translations for that language.

### Actual behavior

The user is able to edit the restricted language.

### Steps to reproduce

Tested on Pimcore 10.5. Unable to test this on the demo environment as it requires access to the users/roles.

Create a new user
- Permissions: enable 'Translations'
- Shared Translation Settings > Language Permissions: enable view access for one or more languages
- Save

![Language_permissions](https://user-images.githubusercontent.com/24292941/180157943-63cb65ea-83e3-4188-b075-cc5165ae2cbe.png)

- Log in as the new user
- Go to shared translations
- Edit a translation for a restricted language

![Shared_translations_edit](https://user-images.githubusercontent.com/24292941/180158012-2ca9d40c-8584-469e-93e4-4729cf14fb70.png)

The same happens when setting the language permissions on a role and assigning the role to a user.

In Pimcore 6 the bug already existed partially. Directly editing the cell by double clicking was blocked, but you were still able to right click and edit the text/HTML.

**Comment by aryaantony92** [comment]
Fixed by #12756
