### ISSUE TITLE
[Bug]: Scheduled time sets time 2 hours forward

### ISSUE THREAD

**Issue by danielerne** [pimcore/pimcore#12721]
### Expected behavior

The time is set correctly

### Actual behavior

The time is set 2 hours forward

### Steps to reproduce

Go to Pimcore Demo (10.5.0)
Open an object
Set a scheduled time to 13:00 and save scheduled time only
Open the object again and it shows 15:00

<img width="858" alt="Bildschirmfoto 2022-07-21 um 09 25 57" src="https://user-images.githubusercontent.com/546931/180154914-88e96b43-955e-4c0a-ae32-a13bd734efef.png">
<img width="1033" alt="Bildschirmfoto 2022-07-21 um 09 25 49" src="https://user-images.githubusercontent.com/546931/180154920-6ac0c44e-c70b-4d50-bca8-ef8165866ba3.png">

**Comment by fashxp** [comment]
related to https://github.com/pimcore/pimcore/issues/12436?

**Comment by mcop1** [comment]
@danielerne right now you have to set a timezone in config.yaml, for the demo-env this is set to UTC. That´s why you are seeing the difference in time. 

Take a look here on how to set the timezone for your own environment:
https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Advanced_Installation_Topics.html

**Comment by danielerne** [comment]
@mcop1  Thanks. I missed this config. It works now.
