### ISSUE TITLE
[Bug]: pimcore_image() does not render image

### ISSUE THREAD

**Issue by HaaseIT** [pimcore/pimcore#12739]
### Expected behavior

Renders image tag

### Actual behavior

in 10.4.6 and 10.5.0, in some cases (couldnt pinpoint where exactly yet) the image tag is not rendered at all.

pimcore_image(...).getSrc() works fine.

I updated two of my projects and this behaviour started, downgraded to 10.4.5 and everything was fine again.

### Steps to reproduce

upgrade project to 10.4.6 or 10.5.0 and use pimcore_image

**Comment by dvesh3** [comment]
@HaaseIT Related #12734?

**Comment by HaaseIT** [comment]
I'm not sure, the regression mentioned there was merged on 2022-06-22 and in 10.4.5 which was released after that, everything still works fine.

**Comment by dvesh3** [comment]
The changes were introduced in 10.5 release https://github.com/pimcore/pimcore/pull/12461

**Comment by brusch** [comment]
@HaaseIT can you please try if #12734 fixes the issue for you? Thanks 😊

**Comment by HaaseIT** [comment]
Hi @brusch , no, this does not fix the issue.

**Comment by dvesh3** [comment]
@HaaseIT please share the exact code to reproduce the issue with properties used like thumbnails or so on. 

On [demo](http://demo.pimcore.fun/), we use this tag on lot of pages and the images are rendered without any problem.

**Comment by dvesh3** [comment]
Closed due to inactivity. Feel free to come back with reproducible case.

**Comment by HaaseIT** [comment]
Hi Divesh, sorry, I am on vacation right now, I will try to make a reproducible case asapl

**Comment by dvesh3** [comment]
> Hi Divesh, sorry, I am on vacation right now, I will try to make a reproducible case asapl

@HaaseIT No worries. Enjoy your vacation 🍹 we'll take care of it when your are back 😉

**Comment by HaaseIT** [comment]
@dvesh3 You can keep this closed, it appears to work properly again in 10.5.2
