### ISSUE TITLE
[Bug]: Error on opening video asset in Pimcore backend 

### ISSUE THREAD

**Issue by siddharth-chaudhery** [pimcore/pimcore#12740]
### Expected behavior

On opening a video, it should show up on right side with default thumbnail or no thumbnail.

### Actual behavior

It is throwing exception. Something is not right with video thumbnail path. 

![Screenshot from 2022-07-23 01-53-50](https://user-images.githubusercontent.com/6791496/180556192-896b3f44-1b1b-414e-8152-6ec9d4e67d1e.png)
.

### Steps to reproduce

- Upload video in the assets.
- Open video asset.

**Comment by kingjia90** [comment]
It seems is the same issue reported on https://github.com/pimcore/pimcore/discussions/12549 and potentially related/fixed with #12697

**Comment by fashxp** [comment]
@siddharth-chaudhery  can you please check, if https://github.com/pimcore/pimcore/pull/12697 fixes your problem?

**Comment by kingjia90** [comment]
I've gave it a try by reverting the changes in the fixing PR and can confirm the problem, so it should be considered as resolved. 
I am closing for the moment, feel free to reopen/add more feedback if is still happening.
