### ISSUE TITLE
[Improvement]: make maintenance task frequency configurable

### ISSUE THREAD

**Issue by kaurov** [pimcore/pimcore#12755]
### Improvement description

Why do you use hardcoded 86400 seconds (24 hours) for maintenance task?
`     $lock = $this->lockFactory->createLock('maintenance-' . $name, 86400);`
in [\Pimcore\Maintenance\Executor::executeTask()](https://github.com/pimcore/pimcore/blob/11.x/lib/Maintenance/Executor.php)

We [setup cron job for every 5 minutes](https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Installation.html#page_5-Maintenance-Cron-Job) and also with a time_limit = 5 minutes (300 seconds)
If anything will interupt the 'consume' command execution before the task would be released then the task would be locked for 24 hours.
Why is that number hardcoded, not from yml or at least constant?

**Comment by bellu** [comment]
Is there a way to reset the timer for the tasks?

**Comment by kaurov** [comment]
@bellu 
to reset the lock timer we can delete all locks:
`DELETE FROM `lock_keys`;`

or to install bundle https://github.com/samynw/pimcore-maintenance-toolbox and use the task-specific command 
`php bin/console maintenance:release-lock versioncleanup`
but after enabling it https://github.com/samynw/pimcore-maintenance-toolbox/issues/6
