### ISSUE TITLE
[Bug]: redirecting sites to main domain not working

### ISSUE THREAD

**Issue by troxxs** [pimcore/pimcore#12750]
### Expected behavior

When activating the flag "redirect additional domains to main domain" in the backend's "edit sites", all additional domains should be redirected to the main domain.

### Actual behavior

An additional domain is not redirected to the site's main domain. Instead, the site can't be found and also, logging in to the backend over an additional domain (<additional-domain>/admin) leads to js errors and the backend is not being loaded.

### Steps to reproduce

1. create a site with a main and an additional domain and check the flag "redirect additional domains to main domain"
2. open the site in the browser by using the additional domain and see what happens
3. also, try to log in to the backend, using the additional domain and see the error

**Comment by troxxs** [comment]
Pimcore Version 10.5.0

**Comment by dvesh3** [comment]
This is related to "_There is currently no session available._" in  `TrackingCodeFlashMessageListener` and will be fixed by https://github.com/pimcore/pimcore/pull/12746

**Comment by dvesh3** [comment]
Fixed by #12746
