### ISSUE TITLE
[Improvement][Docs]: Versions of 3rd party libraries

### ISSUE THREAD

**Issue by mysliwietzflorian** [pimcore/pimcore#12763]
### Improvement description

Would it make sense to add the versions for the 3rd party libraries somewhere?  
I would propose it in this file https://github.com/pimcore/pimcore/blob/11.x/3rd-party-licenses.md

**Comment by fashxp** [comment]
https://github.com/pimcore/pimcore/blob/11.x/composer.json ?

**Comment by mysliwietzflorian** [comment]
Sorry for being imprecise. I meant the javascript and CSS 3rd-party dependencies like Ext, CKEditor, FontAwesome, Bootstrap, etc that are copied directly into the code base.

See https://github.com/pimcore/pimcore/blob/11.x/3rd-party-licenses.md
https://github.com/pimcore/pimcore/tree/11.x/bundles/EcommerceFrameworkBundle/Resources/public/vendor

**Comment by mattamon** [comment]
@mysliwietzflorian a documentation would be awesome. I know ext is not relevant for pimcore 11 but it would have helped me a lot in pimcore  > 6  to X to implement new backend features.

**Comment by dvesh3** [comment]
we already maintain the versions in this doc https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/Resources/public/js/lib/PIMCORE_MODIFICATIONS.md

**Comment by mysliwietzflorian** [comment]
@dvesh3 Thanks for the response. That is exactly what I was looking for!

I created a pull request to maybe cross-reference this in `3rd-party-licenses.md`. I expected that information somewhere there.

Edit: we can either close this issue or wait until PR is merged. Your call.
