### ISSUE TITLE
[Improvement]: getEditables should return inherited and overwritten editables

### ISSUE THREAD

**Issue by mcop1** [pimcore/pimcore#12762]
### Improvement description

Right now, `$document->getEditables()` returns null if all editables are inherited from parent.
See https://github.com/pimcore/data-hub/issues/570 for further information.

E.g.
1.) Copy a document e.g. "Data Quality" (ID: 193)
2.) Paste this document using inheritance (of structure and content)
3.) Call `getEditables` on both documents

```
$parent = Document\Page::getById(193);
$child = Document\Page::getById(209);

p_r($parent->getEditables()); // returns all editables
p_r($child->getEditables()); // returns null, even when editables are inherited
```

**Comment by mattamon** [comment]
@mcop1 Calling PageSnippet::setGetInheritedValues(true); now before getting the editables, solves the problem.
Resolved by #14085
