### ISSUE TITLE
[Admin] Documents - remove inherited param from editables initialize

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#12778]
### Improvement description

please see https://github.com/pimcore/pimcore/pull/12724/files#diff-93033ddf3b21c7c9fbb07a9cdb664889b6d3181dc173cb56d82c638a34a5bf16R39

**Comment by dvesh3** [comment]
Please remove comment as obsolete due to https://github.com/pimcore/pimcore/pull/12811

**Comment by aashan10** [comment]
@dvesh3 the comment was already removed in https://github.com/pimcore/pimcore/pull/12811/files#diff-93033ddf3b21c7c9fbb07a9cdb664889b6d3181dc173cb56d82c638a34a5bf16

This issue can be closed as resolved!
