### ISSUE TITLE
[Task] Move WYSIWYG editor to repository pimcore/TBD

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12780]
### Improvement description

Depends on https://github.com/pimcore/pimcore/issues/13499

related to https://github.com/pimcore/pimcore/issues/2499#issuecomment-1176040443

**Comment by brusch** [comment]
Closed for now, actually TineMCE should cover all CKEditor functionalities.
CKEditor could be added again as a community bundle.
