### ISSUE TITLE
[Bug]: System setting "Store version history for x steps" not working for DataObjects

### ISSUE THREAD

**Issue by SamyMP** [pimcore/pimcore#12784]
### Expected behavior

When the setting is set and different than 0, it should delete the oldest version of the saved object.

![image](https://user-images.githubusercontent.com/35225430/181242957-858080d3-5207-4a4c-a2f5-6304892e90f1.png)

For exemple : if the setting is set to 10, it should delete the 1st version of the object on the 11th save. Then delete the 2nd version of the object on the 12th save, etc.

### Actual behavior

The versions are not deleted and keep pilling up indefinitly

On the [demo](https://demo.pimcore.fun/admin) :
![image](https://user-images.githubusercontent.com/35225430/181272297-eb90e290-7f36-4ee2-840f-1526d7635b3f.png)

### Steps to reproduce

0. Ensure the setting is set to 10 for example
1. Open a DataObject
2. Save it more than 10 times
3. Go to the "Versions" tab

**Comment by blankse** [comment]
@SamyMP This is done via Symfony Messenger. Do you configure the Cron Job?
https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Installation.html#page_5-Maintenance-Cron-Job

The public demo has no cron job running. See https://github.com/pimcore/pimcore/issues/10655#issuecomment-947378454

**Comment by SamyMP** [comment]
Thank you @blankse, it works with the cron job in place :)
I didn't realize the cron was not set on the demo env, my bad.

Actually, I did try to set up the maintenance jobs on my local environment but it never worked. I couldn't make the versionning parameter work on my laptop
I tried on my production environment and it works
