### ISSUE TITLE
Localized fields at a glance (side-by-side)

### ISSUE THREAD

**Issue by msenkpiel** [pimcore/pimcore#1279]
Add a new option to localizedfields data object definition. So you can view mutliple language fields at a glance side by side. That's helpful to translate text.

**Comment by brusch** [comment]
A generic approach would be to let the user choose the languages and save it somewhere in the local storage.

**Comment by frithjof** [comment]
An overlay as long as you are in the field showing the other language values could be nice

**Comment by brusch** [comment]
Duplicate of #3054
