### ISSUE TITLE
Fix Psr\Container\ContainerInterface injection to Symfony\Component\DependencyInjection\ContainerInterface Rest Deprecations...

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12790]
### Improvement description

...

**Comment by aashan10** [comment]
@fashxp 

There are multiple cases where the `Psr\Container\ContainerInterface` resolves to `Symfony\Component\DependencyInjection\Argument\ServiceLocator` which does not implement the `Symfony\Coponent\DependencyInjection\ContainerInterface` but relies on the `Psr\Container\ContainerInterface`.

What should be done for such service locators?

**Comment by brusch** [comment]
@aashan10 it's about fixing deprecations, right? What does Symfony suggests here?
