### ISSUE TITLE
[Bug]: Asset "Preview" tab pagination breaks for the folder which has audio files and other files (jpg,mp4 etc)

### ISSUE THREAD

**Issue by pradeep-pimcore** [pimcore/pimcore#12808]
### Expected behavior

Items equal to the total value in pagination should be listed in preview tab.  System can display a fixed thumbnail for audio files.
So that the pagination total matches with the items count.

### Actual behavior

Asset preview tab does not list the audio files, but it does list the other files.
Because of this, the total value in pagination toolbar does not match with the count of items shown on the page.

### Steps to reproduce

Create a new folder in Assets.
Add an audio file in folder
Add a jpg/mp4/png file in the folder
Click on folder
Notice the items displayed on the tab and the total count displayed on the pagination.

![audio_preview_not_supported](https://user-images.githubusercontent.com/58973662/182352029-67c4bf42-adee-4e0b-91e7-d0313582e957.png)

**Comment by kingjia90** [comment]
Fixed by #12880
