### ISSUE TITLE
[Bug]: explode_and_trim() returns empty array

### ISSUE THREAD

**Issue by elements-team** [pimcore/pimcore#12819]
### Expected behavior

The function ``explode_and_trim('/', '/my/test/path/)``should return a non empty array.

The expected result is:
```
array(
 'my',
'test',
'path'
)
```
.

### Actual behavior

In Pimcore 10.5 and above the function is returning:
```
array(
'/my/test/path'
)
```

This is because the ``limit``parameter is defaulted to zero and passed to the ``explode`` function as a third parameter within the helper method in helper-functions.php.

https://www.php.net/manual/en/function.explode.php:
> If the limit parameter is zero, then this is treated as 1.

see https://github.com/pimcore/pimcore/blob/11.x/lib/helper-functions.php#L376

### Steps to reproduce

See example provided in expected behavior section.
Error exists in 10.5 and ^11. 

### Solution
Defaulting parameter ``$limit = PHP_INT_MAX`` might do it.

**Comment by dvesh3** [comment]
Fixed by #12820
