### ISSUE TITLE
[Bug]: pimcore_head_title() of document gets overriden by pimcore_inc()

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#12822]
### Expected behavior

The title of the document gets not overriden if pimcore_inc() is used in the template.

### Actual behavior

The title of the document has the content of the page that is included via pimcore_inc().

### Steps to reproduce

In the layout template I have code to set the title of the document:

`{% do pimcore_head_title().set(metaTitle) %}`

Now let's say metaTitle of the document mit the ID 30 is set to 'Foo'. If you open the document in your browser you can read 'Foo' in the tab. There is also another document with the ID 40 where metaTitle is set to 'Bar'. If I use the following code for the document with the ID 30 to include the document with the ID 40, like:

`{{ pimcore_inc(40) }}`

… then the title of the document with the ID 30 is suddenly 'Bar' (it uses the title of the document with the ID 40).

Tested with Pimcore 10.5.0 and 10.5.1.

_To be clear: I don't know if there is legit use case for including a full document into another document. I found this issue while developing on a new site because in one template a wrong document was included (instead of a snippet). But it seems unexpected to me that the use of pimcore_inc changes anything with regards to the document that includes another document._

**Comment by dvesh3** [comment]
@cadeyrn thanks for reporting the issue. I don't think it is a valid case using same layout for parent & child document as then you would be creating wrong HTML with multiple head tags. If you use different layout, then you should take care of the output in the included doc as not to print head tags under content and should still have the possibility to prepend or append text to the main title. 

I would mark this issue as invalid.
