### ISSUE TITLE
[Bug]: Markers/Hotspots lose relation data

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#12835]
### Expected behavior

Data stays.

### Actual behavior

Data is lost.

### Steps to reproduce

I can confirm, that the dialog can now be opened. However, when using assets, the path is lost, instead the ID is set.

Reproduce like this:

1. Add Asset relation in marker/hotspot
2. Drag & Drop Asset onto relation field
![image](https://user-images.githubusercontent.com/57256630/183019498-cbe40d41-0a33-41ac-8804-b2642364d3e1.png)
3. Save everything an reload the document
4. Reopen the marker/hotspot and find the an ID is now displayed of the path
<img width="540" alt="image" src="https://user-images.githubusercontent.com/57256630/183019032-f25e0a52-2483-4cd5-9080-942f48e5e1ff.png">

_Originally posted by @passioneight in https://github.com/pimcore/pimcore/issues/12777#issuecomment-1206113519_

**Comment by aryaantony92** [comment]
Fixed by #12851
