### ISSUE TITLE
[Bug]: Thumbnails are not shown

### ISSUE THREAD

**Issue by cami0092** [pimcore/pimcore#12843]
### Expected behavior

If I click on the Select where I can choose between my thumbnails configuration, I expect to see my configured thumbnails.

### Actual behavior

If I click on the Select where I can choose between my thumbnails configuration, nothing happens. For a very short time "loading" is shown and then nothing happens.

### Steps to reproduce

Click on any asset. Go to "View" and click on the select field next to "Thumbnail" on the right side
<img width="1076" alt="Bildschirmfoto 2022-08-08 um 15 50 38" src="https://user-images.githubusercontent.com/55980768/183434048-75e4d31d-ece5-42aa-9bc2-243dc5b4ee04.png">
.

**Comment by blankse** [comment]
@cami0092 Have you activated the advanced setting on your thumbnail configurations?
![image](https://user-images.githubusercontent.com/998558/183435040-03e95dad-df90-4ca7-8179-491a7fdd3def.png)

**Comment by cami0092** [comment]
> @cami0092 Have you activated the advanced setting on your thumbnail configurations?
> ![image](https://user-images.githubusercontent.com/998558/183435040-03e95dad-df90-4ca7-8179-491a7fdd3def.png)

Thank you for your response. Where do I find this checkbox? I tried it on the demo version and it doesn't work for any of the preset thumbnail configurations.

**Comment by blankse** [comment]
@cami0092 Settings -> Thumbnails -> Image Thumbnails
![image](https://user-images.githubusercontent.com/998558/183437139-ac31a896-0cb1-4507-9bd6-67b4c752bfc8.png)

Select one config in the tree, open the "Advanced" section, activate the checkbox and save. Than you can see this thumbnail in this select.
![image](https://user-images.githubusercontent.com/998558/183437487-32336634-2fe0-4ef6-92a9-f41d7ea97966.png)

@brusch Maybe you should make one example in the demo. At the moment all thumbnails are deactivated for the download section.

**Comment by cami0092** [comment]
@blankse Thank you so much! That worked! (I really didn't notice that advanced field 🤦🏼‍♀️)
