### ISSUE TITLE
Global disable of automatic_serialization for cache in Cache.php causes crash Zend Paginator

### ISSUE THREAD

**Issue by CptnChoas** [pimcore/pimcore#1284]
# Bug Report
The change of:

self::$instance->setOption("automatic_serialization", true);

to:
self::$instance->setOption("automatic_serialization", false);

in Cache.php in line 172, causes the Zend Paginator to crash.
In getTotalItemCount() the paginator tries to write the $itemCount to the cache. This is an integer. Without automatic_serialization set to true, this will cause an "Datas must be string or set automatic_serialization = true"-error in the save function of the Zend/Cache/Core.php. This may not be the only function where this will lead to an exception.

In an old issue ([1076](https://github.com/pimcore/pimcore/issues/1076)), which resulted in the above change, you said that the solution would be a custom frontend cache. The problem with that is, that the automatic_serialization option set in the frondend cache is globally overwritten by the above line (Pimcore/Cache.php l.172).

**Comment by brusch** [comment]
The cache for the paginator component is now set on initialization. @maff jfyi
