### ISSUE TITLE
[Bug]: Static Pages with json request to a non document route saves wrong content

### ISSUE THREAD

**Issue by Gerhard-Kanzler** [pimcore/pimcore#12840]
### Expected behavior

We want to use the Static Page Generation. 
When i open the Document "/en" this page is saved as .html file.

On this page is a JS fetch request to "/en/cart" this route is only existing as Annotation.
No Document only the route and the action with a json Response.

This virtual Route is not saved as Static file ... this is correct

So on every request to "/en" i get the static file with the correct content and not the content from a fetch request.

### Actual behavior

But the Problem is, the json response from "/en/cart" overrides the "/en" content ".html" file!

This is a problem by inheritance of the parent document to a virtual routed action!

So on every Request where i use a json response the document gets overriden

### Steps to reproduce

1. Create a document like "/en"
2. Create a action with an router (annotation or so) with "/en/cart"
  - create a simple json response in this action
4. on the "en" page start a js fetch request to the cart url
5. now you can see in the /public/var/tmp/pages/en.html file the content is overriden.

i use this fetch script:
`
<script>

        fetch('/en/cart')
            .then( response => response.json() )
            .then( function( data ){
                console.log( data )
            } )

    </script>
`

**Comment by dvesh3** [comment]
Fixed by #12920
