### ISSUE TITLE
[Task]: Generate a migration for rebuilding data object classes

### ISSUE THREAD

**Issue by mcop1** [pimcore/pimcore#12859]
### Improvement description

Generate a migration for rebuilding data object classes for Pimcore 11 to make sure that the changes (like return types for setters) take effect

We need to rebuild classes, object-bricks, etc .. see pimcore:build:classes command

**Comment by dvesh3** [comment]
we might have to consider this on `10.6` to add the required steps in [v11 prepare guide](https://github.com/pimcore/pimcore/blob/11.x/doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md):

-   changing the classes to use strict types which are extending & implementing Pimcore interfaces
- run command `pimcore:build:classes` 

as running migration will not be possible with declaration errors on Pimcore 11.
