### ISSUE TITLE
[Bug]: CKEditor customConfig only applied for non existing attributes

### ISSUE THREAD

**Issue by patric-eberle** [pimcore/pimcore#12858]
### Expected behavior

Using a CKEditor [`customConfig`](https://pimcore.com/docs/pimcore/current/Development_Documentation/Documents/Editables/WYSIWYG.html#page_Custom-configuration-for-CKEditor) for a `pimcore_wysiwyg()` instance, I'm able to forward a custom configuration, which overwrites ALL attributes of the editor configuration with the ones from the custom config file.

Additionally I can define a global [default config](https://pimcore.com/docs/pimcore/current/Development_Documentation/Documents/Editables/WYSIWYG.html#page_Global-Configuration).

### Actual behavior

What actually happens is that:

1) The global OR default (fallback) config is applied as expected
1) The custom config is NOT applied as expected. It's values are not applied if they are already defined
    1) in the global config
    1) in the `/bundles/pimcoreadmin/js/pimcore/document/editables/wysiwyg.js` (which uses a fallback `toolbarGroups` and some other values)

This results in a config that contains my `customConfig` path, but all other options are taken from the global config OR the logic from the `wysiwyg.js` file. Thus I'm for example never able to overwrite `toolbarGroups` or (if I define it on my global config) `removeButtons`, because they already exist.

I'm unsure if this is intended, by design or a bug.

### Without global config

1) Define an area brick with an editable that uses a customConfig:

```
{{ pimcore_wysiwyg('content', {
  customConfig: '/admin-static/js/ckeditor_textarea.js',
}) }}
```

2) define the custom config file:

```
CKEDITOR.editorConfig = function( config ) {
    config.toolbarGroups = [
        {"name":"styles","groups":["styles"]},
    ];
};
```

3) In the admin edit mode, the WYSIWYG field will show the same toolbar as if I did not define one, because the fallback value from `/bundles/pimcoreadmin/js/pimcore/document/editables/wysiwyg.js` overwrites my custom `toolbarGroups`.
<img width="611" alt="grafik" src="https://user-images.githubusercontent.com/10571945/183845440-91d79e49-5922-47d5-ba7f-f23197c210f0.png">

### With global config

1) Define an area brick with an editable that uses a customConfig:

```
{{ pimcore_wysiwyg('content', {
  customConfig: '/admin-static/js/ckeditor_textarea.js',
}) }}
```

2) define the custom config file:

```
CKEDITOR.editorConfig = function( config ) {
    config.toolbarGroups = [
        {"name":"styles","groups":["styles"]},
    ];
    config.removeButtons = 'Bold';
};
```

2) Define a global config as documented on https://pimcore.com/docs/pimcore/current/Development_Documentation/Documents/Editables/WYSIWYG.html#page_Global-Configuration (I did as EventSubscriber) with the following content:

<details>
<summary>Show code</summary>

```
const defaultEditorConfig = {
    toolbarGroups: [
        {"name":"styles","groups":["styles"]},
        {"name":"basicstyles","groups":["cleanup","basicstyles"]},
        {"name":"colors","groups":["colors"]},
        {"name":"paragraph","groups":["list","indent","align"]},
        "/",
        {"name":"links","groups":["links"]},
        {"name":"insert","groups":["insert"]},
        {"name":"clipboard","groups":["clipboard","undo"]},
        {"name":"document","groups":["mode"]}
    ],
    stylesSet: [
        {"name":"Heading 2","element":"div","attributes":{"class":"typo--h2"}},
        {"name":"Heading 3","element":"div","attributes":{"class":"typo--h3"}},
        {"name":"Heading 4","element":"div","attributes":{"class":"typo--h4"}},
        {"name":"Body L","element":"p","attributes":{"class":"typo--body-l"}},
        {"name":"Body M","element":"p","attributes":{"class":"typo--body-m"}},
        {"name":"Body S","element":"p","attributes":{"class":"typo--body-s"}},
        {"name":"Legal","element":"p","attributes":{"class":"typo--legal"}},
        {"name":"Button full width","element":"a","attributes":{"class":"e-button e-button--spacing-600"}},
        {"name":"Button auto width","element":"a","attributes":{"class":"e-button e-button--spacing-600 e-button--width-auto"}}
    ],
    removeButtons: "Save,NewPage,ExportPdf,Preview,Print,Templates,PasteFromWord,Find,Replace,SelectAll,Scayt,Form,Checkbox,Radio,TextField,Textarea,Select,Button,ImageButton,HiddenField,Strike,CopyFormatting,Blockquote,CreateDiv,JustifyBlock,BidiLtr,BidiRtl,Language,Image,Flash,Smiley,SpecialChar,PageBreak,Iframe,Font,FontSize,BGColor,ShowBlocks,Maximize,About",
    format_tags: "p;h1;h2;h3;h4",
    colorButton_enableAutomatic:false,
    colorButton_enableMore:false,
    colorButton_colors: "FontColor1/696969,FontColor2/005091,FontColor3/00b4f0"
};

try {
    pimcore.document.editables.wysiwyg.defaultEditorConfig = defaultEditorConfig;
} catch (e) {}

try {
    pimcore.object.tags.wysiwyg.defaultEditorConfig = defaultEditorConfig;
} catch (e) {}
```
</details>

3) In admin edit mode, the `toolbarGroups` AND `removeButtons` are not applied from my custom config, because they already exist on my global config.

### Current workarounds

1) If I only forward the `specificConfig` as soon as the `customConfig` attribute exists in `/bundles/pimcoreadmin/js/pimcore/document/editables/wysiwyg.js`, I get the expected result (IF I don't overwrite some attributes in the editable config)
1) If I only define `toolbarGroups` in my global configuration I can roughly control the toolbar style with `removeButtons` on my custom configuration. But I would have to always remove buttons, that I don't want by default.

**Comment by dvesh3** [comment]
@patric-eberle you need to pass `toolbarGroups: false` when changing the style of `toolbarGroups` in custom config. please see https://pimcore.com/docs/pimcore/current/Development_Documentation/Documents/Editables/WYSIWYG.html#page_Custom-configuration-for-CKEditor

**Comment by patric-eberle** [comment]
Using `false` on `toolbarGroups` did not work either. Only if `toolbarGroups` is not set at all (e.g. adding `delete specificConfig.toolbarGroups;` if `this.config['toolbarGroups'] === false` in wysiwyg.js), it will take the `toolbarGroups` from the `customConfig` file. And even then ONLY if we also don't define a general configuration for the editor.

**Comment by patric-eberle** [comment]
I personally would have expected. that only the `customConfig` is applied, IF defined. But that is probably not the desired behaviour for everyone and would be a quiet different behaviour from what is happening right now.

**Comment by patric-eberle** [comment]
Additionally `object/tags/wysiwyg.js` uses a different merge logic for the configuration on Object Tags, which ALWAYS sets the `toolbarGroups` and thus never allows to define them with `customConfig`.

**Comment by patric-eberle** [comment]
I eventually got this to work with a small "hack". The above mentioned Problem still exists but it is possible to use a default/fallback AND a custom config by using `toolbarGroups` and `toolbars` at the same time. This solution works for editables and object tags.

- Use `toolbarGroups` in the global configuration on `pimcore.document.editables.wysiwyg.defaultEditorConfig` and `pimcore.object.tags.wysiwyg.defaultEditorConfig` to define the default/fallback toolbar (if no `customConfig` is used on the instance).
- Use `toolbars` on the `customConfig` definition. Since it seems to have a higher priority it overwrites the `toolbarGroups` configuration from the fallback. You don't even have to define `toolbarGroups: false`.

Drawbacks
- Still not possible to use `removeButtons` in the fallback AND in the `customConfig`, since they will not be overwritten once defined.
- `toolbars` requires more maintenance and has some minor drawbacks: https://ckeditor.com/docs/ckeditor4/latest/features/toolbarconcepts.html#the-drawbacks-of-item-by-item-configuration

**Comment by julkue** [comment]
The WYSIWYG integration of Pimcore really needs to be refactored a lot. It's a pain in the ass, sorry. 

> I personally would have expected. that only the customConfig is applied, IF defined. But that is probably not the desired behaviour for everyone and would be a quiet different behaviour from what is happening right now.

I totally agree, that's the point of defining a custom config. If you define a custom config with `toolbarGroups` then those will not be forwarded to CKEditor, because Pimcore overrides it with their default. Even when setting `toolbarGroups` to `false` in Twig like you suggested @dvesh3, then the `toolbarGroups` config in the customConfig file is still overriden with this `false` value, CKEditor will still receive `false`. The entire point of customizing is lost with this integration.

Also, even the Twig integration is totally different from CKEditor originally. In CKEditor `toolbarGroups` is used ONLY to describe the order / structure of groups and their buttons. In the Twig integration, however, this option is used as definition of only those groups you want to be generated. 

Have you ever customized CKEditor fully? If you simply want to provide your own toolbar group structure and limit buttons per brick, how is this intended to be done? The customConfig isn't working, like I mentioned. And `toolbarGroups` in Twig behaves completely different than CKEditor originally, making it impossible to re-use the config from the Toolbar Configurator of CKEditor.

**Comment by julkue** [comment]
[Those lines](https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/public/js/pimcore/document/editables/wysiwyg.js#L78-L92) would need to be extended with this `else`, then `toolbarGroups: false` would no longer be passed as CKEditor config value and the `toolbarGroups` of the customConfig file would work. Otherwise, this `false` value always overrides the config in the customConfig file.

```javascript
            // if there is no toolbar defined use Full which is defined in CKEDITOR.config.toolbar_Full, possible
            // is also Basic
            if(!this.config["toolbarGroups"] && this.config['toolbarGroups'] !== false){
                eConfig.toolbarGroups = [
                    { name: 'basicstyles', groups: [ 'undo', "find", 'basicstyles', 'list'] },
                    '/',
                    { name: 'paragraph', groups: [ 'align', 'indent'] },
                    { name: 'blocks' },
                    { name: 'links' },
                    { name: 'insert' },
                    "/",
                    { name: 'styles' },
                    { name: 'tools', groups: ['colors', "tools", 'cleanup', 'mode', "others"] }
                ];
            } else {
                // make sure "false" value is not passed along to CKEditor, only settings in
                // potential customConfig
                delete specificConfig.toolbarGroups;
            }
```

**Comment by fashxp** [comment]
closing as ckeditor will be removed with Pimcore 11 and replaced with https://github.com/pimcore/pimcore/issues/2499
