### ISSUE TITLE
[Bug][CustomViews] Allow objects - empy does not allow all

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12863]
### Expected behavior

when allow objects, all objects are allowed to be created in that custom view

![image](https://user-images.githubusercontent.com/8792145/181703377-e3d30a92-54b0-45b2-b112-4ce4882b834a.png)

### Actual behavior

no objects are allowed to be created

### Steps to reproduce

create custom view, don't select any object classes in that list and try to create a new object in that view --> add object menu is empty

![image](https://user-images.githubusercontent.com/8792145/181703548-45ee79bd-96e8-4fdb-a96d-5a77a455cdd2.png)

**Comment by mcop1** [comment]
The allowedClasses property is an empty array for custom views and `null` for data objects.
Check where the empty array is coming from (most likely somewhere in the save function). 
Easy solution would be to check for the length of the array too.
