### ISSUE TITLE
[Bug]: Target Groups not selected

### ISSUE THREAD

**Issue by tom2796** [pimcore/pimcore#12878]
### Expected behavior

If I add a Target Group to a document it is marked as selected. Like here:
![image](https://user-images.githubusercontent.com/105366530/184132446-788998df-e4f0-4511-9cc3-ed1f7cb0e7a9.png)

### Actual behavior

After assigning a Target Group and the document is reopend, the Target Group is not selcted anymore. 
The entries are in the Database so I think this should be only a small Problem. 

![image](https://user-images.githubusercontent.com/105366530/184132896-b6cf8459-1759-4c3c-b318-0207aacfb68a.png)

### Steps to reproduce

I could find this bug in following pimcore versions: 

- 10.4.5
- 10.4.6
- 10.5.2

**Comment by dvesh3** [comment]
Fixed by #12990
