### ISSUE TITLE
Pimcore 4.4.2 doesn't work properly when opened in an iframe

### ISSUE THREAD

**Issue by salexfo** [pimcore/pimcore#1287]
### Expected behavior 
Being able to view objects/assets in the right panel  
### Actual behavior  
 Nothing is shown
### Steps to reproduce  
 Open pimcore 4.4.2 in an iframe (make sure that you don't have a same origin policy problem)
### Code example 
Here is a screenshot of the javascript errors that appear in the console:
http://prnt.sc/e8jx1h

**Comment by brusch** [comment]
Using Pimcore within an Iframe is not officially supported, but we are happy to accept PRs. 
Thanks for your understanding.

**Comment by JeffinJ** [comment]
Is this still the case. I am trying to implement this in Angular and facing the same error.
