### ISSUE TITLE
[Bug]: Problem in versions after removing related asset from Pimcore

### ISSUE THREAD

**Issue by eciosk** [pimcore/pimcore#12889]
### Expected behavior

After removing (assigned to object) asset from Pimcore the version shows correct fullPath of asset that has been removed.

### Actual behavior

After removing (assigned to object) asset from Pimcore the version shows error 500 (tested on Pimcore demo). On my local project, I see "Call to a member function getRealFullPath() on null" - tested on v10.4.3.

### Steps to reproduce

1. Add model with Advanced many to many relation attribute (allow assets).
2. Create an object and add asset to mentioned attribute. Save object.
3. Remove assigned document from Pimcore (not from data model).
4. Refresh object and go to "Versions" tab.
5. Choose version where you added asset to object.

**Comment by eciosk** [comment]
@mcop1 
Any thoughts, ideas?

**Comment by mcop1** [comment]
@eciosk It is a bug. Problem is, that only the id gets persistet in the version data. We can check if the asset is still existing, but if it is not, we can´t display the proper data right now. We will find a solution for that though, but it may take some time.
