### ISSUE TITLE
[Bug]: app cache still being read while the Symfony cache warmer is running

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#12887]
### Expected behavior

See https://github.com/pimcore/pimcore/pull/12571

### Actual behavior

See https://github.com/pimcore/pimcore/pull/12577

### Steps to reproduce

Enable Redis cache and try to build Pimcore into a Docker image.

It will try to trigger a cache connection from `\Pimcore\Tool::getSupportedLocales()`.

IMO the original PR still seems like the most correct solution. /cc @brusch

**Comment by brusch** [comment]
@dkarlovi I see, depends probably on the used data-types in the class definition ... can you re-create a PR for https://github.com/pimcore/pimcore/pull/12571? 

Thanks!

**Comment by kingjia90** [comment]
Fixed by #13114
