### ISSUE TITLE
[Bug]: Fallback for parentId not working anymore

### ISSUE THREAD

**Issue by mcop1** [pimcore/pimcore#12892]
### Expected behavior

If no parentId is set it should fallback to parentId = 1

### Actual behavior

Fallback isn´t working anymore, because id and parentId are null. And therefore the same.
Check for dataObjects, assets and documents.

### Steps to reproduce

Create new DataObject without parentId

```
        $dataObject = new DataObject\Product();
        $dataObject->setKey(\Pimcore\Model\Element\Service::getValidKey('New Name', 'object'));
        $dataObject->setName("test");
        $dataObject->save();
```
results in 

![image](https://user-images.githubusercontent.com/89011527/184884034-8ae3725c-a87c-42b4-93d4-18d704a42ba3.png)

**Comment by kingjia90** [comment]
Fixed by #12897
