### ISSUE TITLE
[Bug]: Error `Cannot autowire argument $bruteforceProtectionHandler` on Forgot Password Page

### ISSUE THREAD

**Issue by bigiagipa** [pimcore/pimcore#12893]
### Expected behavior

The login page offers a reset password feature adter clicking the "Forgot your password?" button.

### Actual behavior

The forgot/lost password page opens with error like below : 

`Cannot autowire argument $bruteforceProtectionHandler of "Pimcore\Bundle\AdminBundle\Controller\Admin\LoginController::lostpasswordAction()": it references class "Pimcore\Bundle\AdminBundle\Security\BruteforceProtectionHandler" but no such service exists.`

![image](https://user-images.githubusercontent.com/50323723/184589549-4078dfd7-1ed7-434a-8cdf-dfba652a1048.png)

### Steps to reproduce

1. Install vanilla Pimcore Project Skeleton ("^10.5")
2. Go to admin/login page
3. Click "Forgot your password?"

**Comment by dvesh3** [comment]
Fixed by #12894
