### ISSUE TITLE
[Bug]: ContentMasterDocument breaks when the Master Document gets deleted

### ISSUE THREAD

**Issue by Fabian-Hofer-Mastertent** [pimcore/pimcore#12915]
I got this error after updating to 10.5.3, i had 10.4.2 before where the error was not appearing.

### Expected behavior

After deleting a page (A) that is the Content Master Document of another page (B), the other page (B) should open anyway or - event better - the "Content Master Document" of (A) should be removed from the field in page (B).

### Actual behavior

After deleting a page that is the Content Master Document of another page, the page could not be opend anymore and the following error is returned:

Status: 500 | Internal Server Error
URL: /admin/page/get-data-by-id
Message: Call to a member function getId() on null

Thats because the ID of the Content Master Document does not exist anymore.

### Steps to reproduce

Tested in the Demo-Pimcore.

1. create a new page "test" under /en/
2. copy the page
3. paste the page as a new language variant under /de/
4. remove the page /en/test/
5. try to open /de/test/ and get the error

**Comment by blankse** [comment]
@Fabian-Hofer-Mastertent I created a PR: https://github.com/pimcore/pimcore/pull/12921
Can you test it?

**Comment by fsamareanu** [comment]
> @Fabian-Hofer-Mastertent I created a PR: #12921 Can you test it?

I hit the same issue when upgrading from 10.5.2 to 10.5.3 and can confirm the issue is resolved after manually patching PageSnippet.php

**Comment by Fabian-Hofer-Mastertent** [comment]
@blankse thank you very much for the quick fix. I can confirm that the patch resolved the issue.
