### ISSUE TITLE
[Mail] Remove deprecated methods

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#12924]
### Feature description

- https://github.com/pimcore/pimcore/blob/27b0b2201e44e6da9f69f80ecf87bcee7840ab26/lib/Mail.php#L879
- https://github.com/pimcore/pimcore/blob/27b0b2201e44e6da9f69f80ecf87bcee7840ab26/lib/Mail.php#L866
- https://github.com/pimcore/pimcore/blob/27b0b2201e44e6da9f69f80ecf87bcee7840ab26/lib/Mail.php#L912
- https://github.com/pimcore/pimcore/blob/dedb59336dabf4ce5288b514dcffeb82d34a6eaf/lib/Mail.php#L966

**Comment by blankse** [comment]
@dvesh3 Why is `setSubject()` not deprecated? I think it should be replaced by `subject()`.
I also think it should be triggert a deprecation message in 10.5.

**Comment by dvesh3** [comment]
@blankse good catch! yes, it should be deprecated and trigger a deprecation. Issue #13006
