### ISSUE TITLE
[Bug]: 10.5.2 language selection does not work on grid

### ISSUE THREAD

**Issue by kamilawiercinska** [pimcore/pimcore#12958]
### Expected behavior

After choosing language in grid options, user can see translated values on the grid

### Actual behavior

After choosing language in grid options, user cannot see translated values on the grid. User has to change application language in order to see translated values.

### Steps to reproduce

1. open grid options
2. choose english language
3. choose desired attribute

Additional info:
my attribute (type:select) is translated in the translations "messages" and "admin"
![admin](https://user-images.githubusercontent.com/49391646/186371753-9a7d1da1-701a-45c2-a460-5bfaa84ebd68.PNG)

Grid view with polish language in the app:
![grid with polish app language](https://user-images.githubusercontent.com/49391646/186371916-a706d2e3-2612-48a0-907b-5398c181365c.PNG)

Grid view with english language in the app:
![grid with english app language](https://user-images.githubusercontent.com/49391646/186371972-2d9a0aad-fea7-4684-a09d-5900edd834f6.PNG)

**Comment by kamilawiercinska** [comment]
Hello, any updates?

**Comment by robertSt7** [comment]
@kamilawiercinska Sorry, but I couldn't reproduce the bug. Could you please try it on our demo: https://demo.pimcore.fun/admin

**Comment by kamilawiercinska** [comment]
@robertSt7  sure can you give me the username/pass?

**Comment by robertSt7** [comment]
Yes demo/admin

**Comment by kamilawiercinska** [comment]
![image](https://user-images.githubusercontent.com/49391646/188140492-140a2f27-5d30-48c2-9645-166c29db4f39.png)

![image](https://user-images.githubusercontent.com/49391646/188140313-bba976de-0184-4b65-b32a-b888a5276485.png)


as you can see, displayed values are not in the language selected on the grid.


but then, I change my language
![image](https://user-images.githubusercontent.com/49391646/188140782-9024f101-4934-4638-8660-ddcb7fdb3cc1.png)


and now it's all good


![image](https://user-images.githubusercontent.com/49391646/188140844-f7be47c5-4701-4a05-831a-ca8d1fb3f939.png)



even in english, which is incorrect:

![image](https://user-images.githubusercontent.com/49391646/188140895-d7db2768-d5e3-4448-b3ff-01add33c4a6a.png)

**Comment by robertSt7** [comment]
@kamilawiercinska  Now I got it, thank you. We will consider it next week in the planning.

**Comment by fashxp** [comment]
There is a difference between content language (= language for data from localized fields) and UI language (for all labels as well as translation of select value labels).
The language setting in the grid reflects to content language, and does not change UI language. 

So this is actually intentional behavior.
