### ISSUE TITLE
Feature Request: Granular Custom Report Permissions

### ISSUE THREAD

**Issue by cleggypdc** [pimcore/pimcore#1295]
# Feature Request 
## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [x] There is no existing issue regarding the same topic

## Feature description 
A more granular permission system for custom reports, so that either individual users or entire roles with the custom report permission could be restricted at the individual report level.

A simple implementation would be to leave the user permissions system as is, and have a setting in the custom report config, such as an array of users/roles that are allowed access to the report, and the appropriate configuration on the controller side.

What do you think?

**Comment by brusch** [comment]
Duplicates #3673
