### ISSUE TITLE
[Bug]: Unable to export translated values from the grid

### ISSUE THREAD

**Issue by kamilawiercinska** [pimcore/pimcore#12959]
### Expected behavior

Exported xlxs/csv file has translated values

### Actual behavior

Exported xlxs/csv file has values equal to the key, not translation.

![image](https://user-images.githubusercontent.com/49391646/186381037-9ca3cc61-01ad-4623-82b3-940613bf8ca8.png)
![image](https://user-images.githubusercontent.com/49391646/186381234-2588c5a2-2a03-4592-9fd2-840f8d44b968.png)
![image](https://user-images.githubusercontent.com/49391646/186381346-cdb346cc-723a-4269-9fbc-aba79a703140.png)
![image](https://user-images.githubusercontent.com/49391646/186381823-e941bbbd-6dc5-464b-ba5d-95224ad2e43e.png)

### Steps to reproduce

1. open object grid options
2. select desired attirbutes, that have translations in messages/admin translations
3. select english language
4. observe the result on grid
5. export grid

additional info:
these may be linked to this issue:
https://github.com/pimcore/pimcore/issues/12958
https://github.com/pimcore/pimcore/issues/12903

**Comment by kamilawiercinska** [comment]
just for the explanation, yes- screenshots are from the old version of the app, 6.9, however error occurs on 10.5.2 also

**Comment by kamilawiercinska** [comment]
Hello, any updates?

**Comment by robertSt7** [comment]
@kamilawiercinska I was able to reproduce the bug and estimate the time it will take to fix. We will consider it next week in the planning.

**Comment by brusch** [comment]
Don't think this is a valid bug ... the CSV export should export the values of a field not the labels.
So imho everything is correctly here.

**Comment by kamilawiercinska** [comment]
@brusch  but we are talking here about the values of the fields :) labels are not being exported and I am aware of that.
but the values are not being translated in the export, which makes an issue for me.

**Comment by brusch** [comment]
@kamilawiercinska no you're talking about the translated labels of for instance an select field, the value is this: 
![image](https://user-images.githubusercontent.com/142037/191772488-ae1a3d7f-465b-4912-a36e-b83c5d262f81.png)

**Comment by kamilawiercinska** [comment]
@brusch okay, so please review this scenario:
I am french. I am using pimcore in french. I am looking at the grid, I can see a translated value FRENCH LUXURY CAR:

![image](https://user-images.githubusercontent.com/49391646/191774165-23e60685-b974-47ca-ac43-9eb4d44dd8f4.png)

But I need to make a pivot table with my data, so I want to export data to xls/csv.

![image](https://user-images.githubusercontent.com/49391646/191774315-1b997453-d052-4aea-92e3-8da8492f2ee8.png)

Now I do not uderstand my data, because it is not my language. It is not the same as it was on the grid.
what do you advise to do then?

**Comment by fashxp** [comment]
@kamilawiercinska for that last use case you could use the `Translate Value` operator. With that, you can translate values, show them in the grid and also use these values for the export. 

![image](https://user-images.githubusercontent.com/8792145/213996989-c77e4069-313c-4feb-9cc7-3163fdda40b4.png)

![image](https://user-images.githubusercontent.com/8792145/213997079-4a6b286c-41c5-48b8-961d-4eb4fa2665f6.png)


Right now, the `Translate Value` operator uses the `messages` domain for translation. Eventually, it needs to be extended so that one can use other domains like the `admin` domain or any custom domain for translation. We would accept a PR for that improvement.
