### ISSUE TITLE
[Bug]: ClassDefinitionManager fails to create multiple classes if id of the multiple definition files are same

### ISSUE THREAD

**Issue by sndsabin** [pimcore/pimcore#12968]
### Expected behavior

In the case of two class definitions files with the same id for different classes. for example (Customer and Product):
- `definition_Customer.php`
```php
return Pimcore\Model\DataObject\ClassDefinition::__set_state(array(
   'dao' => NULL,
   'id' => '6',
   'name' => 'Customer',
   ...
```
- `definition_Product.php`
```php
return Pimcore\Model\DataObject\ClassDefinition::__set_state(array(
   'dao' => NULL,
   'id' => '6',
   'name' => 'Product',
   ...
```
**Expected Behaviour**
`bin/console pimcore:deployment:classes-rebuild -c`  to create two Data Objects Class 
- Customer
- Product

### Actual behavior

`bin/console pimcore:deployment:classes-rebuild -c` will first create the `Customer` class and then will update the same `Customer` class definition with the `Product` class definition, seeming as if it never created the `Customer` class but only `Product` class.

**Verbose output of `bin/console pimcore:deployment:classes-rebuild -c -v`**
```
---------------------
Saving all classes
Customer [6] created
Product [6] created
---------------------
```

### Steps to reproduce

- create Data object *Customer* via admin panel
- `cp defintion_Customer.php defintion_Product.php` and change `name` attribute of ``defintion_Product.php`` to `product`
- `bin/console pimcore:deployment:classes-rebuild -c`

**Comment by brusch** [comment]
You need to omit the `id` properties when they should be auto-generated, if ID is specified, it needs to be unique.
