### ISSUE TITLE
[Bug]: Uncaught Error: fstat(): supplied resource is not a valid stream resource 

### ISSUE THREAD

**Issue by mturalenka** [pimcore/pimcore#12970]
### Expected behavior

When uses S3 as file storage for assets/thumbnails with public url pimcore should use Flysytem functionality to get file size as described in #9234

### Actual behavior

Exception is raised 
> "exception": "[object] (TypeError(code: 0): fstat(): supplied resource is not a valid stream resource at vendor/pimcore/pimcore/bundles/CoreBundle/Controller/PublicServicesController.php:161)"

### Steps to reproduce

1. configure S3 storage for assets and thumbnails 
2. configure public url for thumbnails
3. render thumbnail

**Comment by dvesh3** [comment]
Fixed by #12996
