### ISSUE TITLE
[Bug]: class export messes up the json file

### ISSUE THREAD

**Issue by aweichler** [pimcore/pimcore#12983]
### Expected behavior

The export file of class / objectbrick has each field only one time.

### Actual behavior

The export file of a class / objectbrick has the fields multiple times.
In the json Files there are the children under "childs" and "children".
I have attached 2 zip files. One created with Pimcore 6 and one with Pimcore 10.5.3.
The error seems to be only for Pimcore 10.5.x.

I have created a objectbrick with a panel and a number field "color". In the Pimcore 6 file you see the panel and the "color" field one time. In the Pimcore 10 file you see the "color" field multiple times.

[objectbrick_Test_export_pimcore_10_5.zip](https://github.com/pimcore/pimcore/files/9425104/objectbrick_Test_export_pimcore_10_5.zip)

[objectbrick_Test_export_pimcore_6.zip](https://github.com/pimcore/pimcore/files/9425108/objectbrick_Test_export_pimcore_6.zip)

### Steps to reproduce

Look at the attached file for PImcore 10.

**Comment by mcop1** [comment]
@aweichler We renamed the "childs" property to "children", but left the "childs" property in the definition for now- as a bc layer so to say. It will be removed with Pimcore 11.

**Comment by aweichler** [comment]
ok, then I can close this issue.
@mcop1 thank you for your fast answer.
