### ISSUE TITLE
[Bug]: Renaming Data Objects and their folders does no longer work after upgrade from v10.5.2 to v10.5.3

### ISSUE THREAD

**Issue by skygatewitt** [pimcore/pimcore#12998]
### Expected behavior

Renaming an existing Data Object or (Data Objects-) folder should persist the changed name. (Both tree renaming and the rename button in an open element are affected)

### Actual behavior

The name changes in the tree view, but when opening the object, the tab shows the old name. Refreshing the tree also reverts the change.

### Steps to reproduce

- Update from 10.5.2 to 10.5.3
- Right-click on any element in the Data Objects tree (folder / objects) and click rename or use the "Rename" button in an opened element
- Change the name 
- Open the element or refresh the tree node above
- The name is still the old one

This behaviour is not reproducible in the demo, but has been reproduced in multiple local Pimcore projects. After reverting back to 10.5.2, renaming works again. This only seems to affect the Data Objects. Both documents and assets can be renamed.

**Comment by mcop1** [comment]
@skygatewitt should be fixed with tomorrow´s release, please see:
https://github.com/pimcore/pimcore/pull/12985

**Comment by skygatewitt** [comment]
I only searched the issues, and not the pull requests. This is my first time opening any issue on Github. I apologize for the duplicate.

**Comment by mcop1** [comment]
No need to apologize and you are right, normally there should be an issue with every pull request :)
