### ISSUE TITLE
[Bug]: Overriding "From" in newsletter for test mail does not work

### ISSUE THREAD

**Issue by limenet** [pimcore/pimcore#13004]
### Expected behavior

When sending a test email for a newsletter, there's an option to specify the `From` address in the "Send Test-Email" modal. The value in the modal should (or rather is expected to) take precedence over the value stored in the newsletter settings.

### Actual behavior

The value from the newsletter settings is used instead of the value in test email modal.

### Steps to reproduce

1. Open https://demo.pimcore.fun/admin/login/deeplink?document_119_newsletter
2. Under "Settings" > "Email Settings" > "From:" specify `settings@example.com`
3. Click "Save & Publish"
4. Click "Send Test-Email"
5. Set "From:" to `modal@example.com`
6. Fill in "To:" and "Subject:"
7. Click "Send"
8. Navigate to "Tools" > "Email" > "Sent Emails"
9. Observe the value for "To:" being `settings@example.com`

**Comment by dvesh3** [comment]
Fixed by #13070
