### ISSUE TITLE
Prepare for Doctrine v4

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#13015]
### Improvement description

Ensure we're not using any of the deprecated things and try to be compatible whenever possible (ideally `doctrine/dbal: ^3.4 || ^4.0`).

**Comment by kingjia90** [comment]
A report after initial  scanning through https://github.com/doctrine/dbal/releases/tag/4.0.0-beta1

- [x] [`Table::changeColumn()` renamed to `Table::modifyColumn()` ](https://github.com/doctrine/dbal/pull/5747)
https://github.com/pimcore/pimcore/blob/c97929ab2e8976e646c8b10f4121053e51de71d1/bundles/CoreBundle/src/Migrations/Version20211018104331.php#L133 
- [x] [replace `hasPrimaryKey` with `getPrimaryKey()` in CMF migrations](https://github.com/doctrine/dbal/pull/5733)
https://github.com/pimcore/customer-data-framework/pull/373
- [ ] [replace `getSchemaManager()` with `createSchemaManager()`](https://github.com/doctrine/dbal/pull/5465) 
- [ ]  [In bundle installers (eg.ecommerceframework, portal engine) replace `createSchema` with `introspectSchema` ](https://github.com/doctrine/dbal/pull/5613)
https://github.com/pimcore/pimcore/blob/c7f023cf2e349bba8794795f6365447b836c887a/bundles/EcommerceFrameworkBundle/src/Tools/Installer.php#L412

- [x] [replace `$qb->execute` with `$qb->executeQuery`](https://github.com/doctrine/dbal/pull/4843)
https://github.com/pimcore/pimcore/blob/c7f023cf2e349bba8794795f6365447b836c887a/lib/Targeting/Storage/DbStorage.php#L129 https://github.com/pimcore/pimcore/search?q=%24qb-%3Eexecute%28%29&type=code

**Comment by kingjia90** [comment]
Keeping this task on hold for the moment, as Symfony is [ not supporting yet](https://github.com/symfony/symfony/issues/47962#issuecomment-1288156758) for v4 (eg. [Doctrine Messenger](https://github.com/symfony/doctrine-messenger/blob/049d69b76aa3f8d8336d6209b4422435115eaf20/composer.json#L20)) making it difficult to test it

**Comment by brusch** [comment]
@kingjia90 But we could do already all the changes you listed above, right?

**Comment by kingjia90** [comment]
Yes, even though needs to be checked again since [BETA2 ](https://github.com/doctrine/dbal/releases/tag/4.0.0-beta2) was released in the meanwhile.

**Comment by kingjia90** [comment]
Blocker list:

- [ ] Can't use the query part getters anymore from the query builder , needs some refactor, especially for subqueries https://github.com/pimcore/pimcore/blob/9b560dcb983ae2561ebea6a085a7175104bcf5bc/lib/Model/Listing/Dao/QueryBuilderHelperTrait.php#L160
see also https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#deprecated-getting-query-parts-from-querybuilder
 https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#bc-break-changes-in-the-querybuilder-api
  - [ ] Custom views [joins](https://github.com/pimcore/pimcore/pull/17003/files#diff-f1c5d50aa07c3685f76a2947c0c3859e2582f8b683ebadf175679eb4aae78785) also relies on reading the `FROM` or table alias
  - [ ] Can't reset `FROM` part via `resetQueryParts` anymore, and only method is an array push, see https://github.com/doctrine/dbal/issues/6371, trying with alternative https://github.com/pimcore/pimcore/pull/17003/files#diff-09de6410fb1e06d3d60e14877c348e74e247f47b13a4f4730bf76b9ff19bf744R216
- [x] Waiting for `ramsery uuid` to support doctrine v4 in `v2.1` or `v3`? https://github.com/ramsey/uuid-doctrine/pull/247 for statistic explorer https://github.com/pimcore/statistics-explorer/blob/b59f20b19f4b4e24829ac8625c711151afc69211/composer.json#L25
- [ ] All `$db->quote()` where accepting `mixed`, but now are strictly `string`, also it's [discouraged](https://github.com/doctrine/dbal/blob/61d79c6e379a39dc1fea6b4e50a23dfc3cd2076a/src/Driver/Connection.php#L32) https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#bc-break-statementquote-only-accepts-strings
  - [ ] Probably can just add a deprecation, but to fully support it we need a major, see also https://github.com/pimcore/pimcore/pull/17003/commits/6b697872e1119a1ab5138735fceddc0dcb2efda2

**Comment by kingjia90** [comment]
Re-opening, needs a quick confirmation that would be fine to just getting closer to support v4 and if it would be possible to just support it in next major or must support both

**Comment by markus-moser** [comment]
We prepared for doctrine V4. The actual upgrade will happen in the next major release: #17096
