### ISSUE TITLE
General document tag wysiwyg configuration not working.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1302]
If we try to make as said on the documentation https://www.pimcore.org/docs/latest/Documents/Editables/WYSIWYG.html, using `pimcore.document.tags.wysiwyg.defaultEditorConfig.allowedContent` in a plugin don't work because `pimcore.document.tags.wysiwyg` doesn't exist.

It seems on pimcoreReady the document wysiwyg tag doesn't exist in fact (for object wysiwyg it exist). Object and document seems to work differently in their initialisation.

Actually we come back to modify pimcore\static6\js\lib\ckeditor\config.js; but it is not reliable as it could be overwritten by a futur update.

Does there is a bug on the core or need the documentation to be updated ?
Thanks a lot.

**Comment by brusch** [comment]
The docs were wrong, this was fixed already, see: 
https://www.pimcore.org/docs/latest/Documents/Editables/WYSIWYG.html#page_Global_Configuration 

So the right way is not to use the `pimcoreReady` event :)
