### ISSUE TITLE
Check if there are any other outdated Composer packages

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#13034]
### Improvement description

1. Check `composer outdated`  and see if we need to upgrade other packages as `symfony/*` as well.
2. Create extra tickets per package and add them to https://github.com/pimcore/product-management/issues/67

**Comment by kingjia90** [comment]
At the current state these packages can be updated, just writing down a list here so each item can be then converted to issue on github,

### Symfony Bundles
Major `6` adds support to Symfony 6, while minor `1` bump minimum PHP to 8.1
- [ ] Bump symfony/asset to ^6.1
- [ ] Bump symfony/cache to ^6.1
- [ ] Bump symfony/console to ^6.1
- [ ] Bump symfony/debug-bundle to ^6.1
- [ ] Bump symfony/dependency-injection to ^6.1
- [ ] Bump symfony/dom-crawler to ^6.1
- [ ] Bump symfony/dotenv to ^6.1
- [ ] Bump symfony/error-handler to ^6.1
- [ ] Bump symfony/event-dispatcher to ^6.1
- [ ] Bump symfony/expression-language to ^6.1
- [ ] Bump symfony/filesystem to ^6.1
- [ ] Bump symfony/finder to ^6.1
- [ ] Bump symfony/form to ^6.1
- [ ] Bump symfony/framework-bundle to ^6.1
- [ ] Bump symfony/http-foundation to ^6.1
- [ ] Bump symfony/http-kernel to ^6.1
- [ ] Bump symfony/lock to ^6.1
- [ ] Bump symfony/mailer to ^6.1
- [ ] Bump symfony/messenger to ^6.1
- [ ] Bump symfony/mime to ^6.1
- [ ] Bump symfony/options-resolver to ^6.1
- [ ] Bump symfony/password-hasher to ^6.1
- [ ] Bump symfony/process to ^6.1
- [ ] Bump symfony/property-access to ^6.1
- [ ] Bump symfony/rate-limiter to ^6.1
- [ ] Bump symfony/routing to ^6.1
- [ ] Bump symfony/security-bundle to ^6.1
- [ ] Bump symfony/security-core to ^6.1
- [ ] Bump symfony/security-http to ^6.1
- [ ] Bump symfony/serializer to ^6.1
- [ ] Bump symfony/stopwatch to ^6.1
- [ ] Bump symfony/templating to ^6.1
- [ ] Bump symfony/translation to ^6.1
- [ ] Bump symfony/twig-bridge to ^6.1
- [ ] Bump symfony/twig-bundle to ^6.1
- [ ] Bump symfony/uid to ^6.1
- [ ] Bump symfony/validator to ^6.1
- [ ] Bump symfony/var-dumper to ^6.1
- [ ] Bump symfony/web-link to ^6.1
- [ ] Bump symfony/web-profiler-bundle to ^6.1
- [ ] Bump symfony/workflow to ^6.1
- [ ] Bump symfony/yaml to ^6.1

### Nice to update for better PHP 8 support 

- [ ] Bump mjaschen/phpgeo to ^4 https://github.com/mjaschen/phpgeo/blob/master/CHANGELOG.md#400---2021-11-29
- [ ] bump monolog/monolog to ^3 https://github.com/Seldaek/monolog/releases/tag/3.0.0
- [ ] Bump psr/simple-cache to ^3 https://github.com/php-fig/simple-cache/releases/tag/3.0.0 we are 2 major behind, but in one it adds return type and the other one param native types

### Nice to update but low priority
- [ ] league/flysystem-bundle  to `^3.`
  - [ ] Clean-up task https://github.com/pimcore/pimcore/blob/ece8fb4941784bc6c0aab3f499ced300b14e3dd6/lib/Maintenance/Tasks/LogArchiveTask.php#L138-L139 follow-up of https://github.com/pimcore/pimcore/pull/12704#issuecomment-1190120082
- [ ] Elastic Search to `^8` [BC](https://github.com/elastic/elasticsearch-php/blob/master/BREAKING_CHANGES.md#80)
- [ ] matomo/device-detector to `^6` apparently just some improvements
- [ ] league/html-to-markdown to `^5` https://github.com/thephpleague/html-to-markdown/releases/tag/5.0.0

**Comment by kingjia90** [comment]
weird, don't we have this feature here? 🙈 
![image](https://user-images.githubusercontent.com/6014195/191948995-142c505d-8b28-40a8-b78f-49f31b2d934d.png)

**Comment by brusch** [comment]
We should imho update all of them to the latest major version.

**Comment by brusch** [comment]
Created follow-up tickets: 

- [x] https://github.com/pimcore/pimcore/issues/13242
- [x] https://github.com/pimcore/pimcore/issues/13243
- [x] https://github.com/pimcore/pimcore/issues/13244
- [x] https://github.com/pimcore/pimcore/issues/13245
- [x] https://github.com/pimcore/pimcore/issues/13246
- [x] https://github.com/pimcore/pimcore/issues/13247
- [ ] https://github.com/pimcore/pimcore/issues/13248
- [x] https://github.com/pimcore/pimcore/issues/13249
- [ ] #13579 
- [ ] #13580
