### ISSUE TITLE
[Bug]: Endless message loop in pimcore_maintenance

### ISSUE THREAD

**Issue by danielerne** [pimcore/pimcore#13038]
### Expected behavior

Maintenance task is running without errors

### Actual behavior

Maintenance task runs in endless queue with these errors:

15:04:39 INFO      [messenger] Received message Pimcore\Messenger\AssetUpdateTasksMessage ["class" => "Pimcore\Messenger\AssetUpdateTasksMessage"]
15:04:39 WARNING   [php] Warning: Undefined array key 1 ["exception" => ErrorException { …}]
15:04:39 WARNING   [php] Warning: Undefined array key 1 ["exception" => ErrorException { …}]

How we can find the ErrorException? It is not tracked in php.log?

We've updated to 10.5.3 but the error still exists.
We looked for unknown or empty images and videos too in our Assets.

### Steps to reproduce

Sadly we can't share the steps how to reproduce. 
Maybe there's a corrupt image or video but the customer has over 2'000 assets.

**Comment by blankse** [comment]
@danielerne I don't know how to get the full ErrorException. Maybe with -vvv param?

Which FFMPEG version do you have. What is the output when you try this:
`ffmpeg -i /path/to/one/video/file.mp4`

Maybe it is this array key 1:
https://github.com/pimcore/pimcore/blob/e53d45e0e69883ebc86cc273a2dcca2faa0cf4c6/lib/Video/Adapter/Ffmpeg.php#L307

**Comment by brusch** [comment]
Try to run the maintenance job with `--async` and then run the queue manually with `bin/console messenger:consume ...` as described here: 
https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Installation.html#page_5-Maintenance-Cron-Job

**Comment by dvesh3** [comment]
Fixed by #13039
