### ISSUE TITLE
Asset document preview tab uses Google service - possible privacy issue?

### ISSUE THREAD

**Issue by christophluehr** [pimcore/pimcore#1306]
# Feature Request 
## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [x] There is no existing issue regarding the same topic

## Feature description 

The asset preview tab in the backend for document uses a Google service. (Url: `https://docs.google.com/viewer?embedded=true&url=` )
As this makes data pass through a 3rd party service of a company whose privacy terms might not be compatible with the providers terms, i think there should be a way to disable this "Feature".
I agree that this is an edge case, as the assets are publicly accessible anyway - still it is non-obvious for users of the system. 
  
[https://github.com/pimcore/pimcore/blob/master/pimcore/modules/admin/views/scripts/asset/get-preview-document.php#L54](https://github.com/pimcore/pimcore/blob/master/pimcore/modules/admin/views/scripts/asset/get-preview-document.php#L54)

If you agree, we should discuss the best way how to handle this issue. A switch in the system config? Just hiding/disabling the preview tab?
I would be happy to work on this and provide a pull request once the best solution is determined.

Chris

**Comment by solverat** [comment]
just as a note: the evil google doc viewer will be trigger only if your browser does not support the native pdf view (which, if i'm not wrong, chrome, firefox, safari and IE11 does).

**Comment by fashxp** [comment]
if LibreOffice is installed correctly on your system, pimcore should generate pdfs from the most common file types and display the pdfs instead of using the google service. 
see also your demo - no google service there.

**Comment by christophluehr** [comment]
Allright, i understand - nevertheless, as this kind of "hit" us unexpectedly; Would you mind me adding a note to the docs (maybe here: https://www.pimcore.org/docs/latest/Assets/Working_with_Thumbnails/Document_Thumbnails.html) that without LibreOffice and/or no native pdf viewer in the browser available, document assets are being sent over to Google? Methinks it is a good idea to let people know ...

**Comment by fashxp** [comment]
pullrequests are welcome :)
