### ISSUE TITLE
[Improvement]: Add fullPath columns to objects/assets/documents tables

### ISSUE THREAD

**Issue by ctippler** [pimcore/pimcore#13081]
### Improvement description

Sometimes we need to get all objects ids below a certain object, or from assets or documents... 

Currently we achive this with a query like 
`SELECT  o_id FROM objects WHERE o_classId="product" AND CONCAT(o_path,o_key) LIKE '/Produktdaten/Produktbaum/Filter/Motorölfilter/00101072%';
`
This works good as long as you don't have big datasets. If you have big datasets the query takes quite long. In my case 0.9 seconds. Therefore it would be great if we add a fullPath column to objects/assets/documents so we can easely query them like 

`
SELECT o_id FROM objects WHERE o_fullPath LIKE '/Produktdaten/Produktbaum/Filter/Motorölfilter/00101072%';
`
The query above takes 0.016 seconds.

What do you think?

Regards,
Christian

**Comment by markus-moser** [comment]
But as the path column contains a trailing slash something like this would give the same results, right?

```SQL
SELECT id FROM objects WHERE `path` LIKE '/Produktdaten/Produktbaum/Filter/Motorölfilter/00101072/%';
```

**Comment by ctippler** [comment]
Hm... i guess i was a little confuced / overworked when i created the issue :D. You are absolutely right :)
