### ISSUE TITLE
[Bug]: empty values in $context in CalculatorClassInterface

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#13098]
### Expected behavior

`$context` should have set according data in instances of CalculatorClassInterface 

### Actual behavior

$context has empty values for index, position and groupId in CalculatorClassInterface within object bricks

maybe related to #13028 ?

![image](https://user-images.githubusercontent.com/9052094/189059576-b210c101-80ba-42d6-9c0c-010630466bd0.png)

### Steps to reproduce

Create a calculated value field within an object brick and check the values of `$context`

`public function compute(Concrete $object, CalculatedValue $context): string`

**Comment by mcop1** [comment]
@jremmurd I think #13028 won´t fix your problems, because the values do not get passed here:

https://github.com/pimcore/pimcore/blob/e4d4d0fdf12d1d850b098f728f43fc4b09733d33/models/DataObject/ClassDefinition/Data/Objectbricks.php#L184

Which values would you expect here, since group and key normally refer to the classification store group & key values?

**Comment by jremmurd** [comment]
> @jremmurd I think #13028 won´t fix your problems, because the values do not get passed here:
> 
> https://github.com/pimcore/pimcore/blob/e4d4d0fdf12d1d850b098f728f43fc4b09733d33/models/DataObject/ClassDefinition/Data/Objectbricks.php#L184
> 
> Which values would you expect here, since group and key normally refer to the classification store group & key values?

I would expect the values as they where previously. So i.e. `$context->getIndex()` in a calculated value field within a brick would return the name of the Brick.

So i.e. container field `tenantData` (ownerName) and brick name `MyTenantData` then, `getIndex()` should return "`MyTenantData`"

**Comment by mcop1** [comment]
Hello @jremmurd ,
I had the chance to create a pull request for this issue today, maybe you want to take a look and check if it is working again:
https://github.com/pimcore/pimcore/pull/13346 - then we could even include it in tomorrow´s bugfix release.

**Comment by jremmurd** [comment]
> Hello @jremmurd , I had the chance to create a pull request for this issue today, maybe you want to take a look and check if it is working again: #13346 - then we could even include it in tomorrow´s bugfix release.

Hi @mcop1, I can confirm that the issue is resolved by your PR. Thx!
