### ISSUE TITLE
[Bug]: CS translations on UI

### ISSUE THREAD

**Issue by kamilawiercinska** [pimcore/pimcore#13099]
### Expected behavior

None of the values are tranlsated

### Actual behavior

Shouldn't at least one of these values be translated? e.g. description?

### Steps to reproduce

Not sure whether it's a bug, so please advise.
I translate key "color"
I choose english language for the app
![image](https://user-images.githubusercontent.com/49391646/189087749-cab688ca-1b07-4270-9f73-fb7389649352.png)

CS name, title , description is not translated
![image](https://user-images.githubusercontent.com/49391646/189087793-a13c9322-5afd-4d53-99a4-3c2c9513caf2.png)

**Comment by robertSt7** [comment]
@kamilawiercinska  We are not translating it at the moment and we do not plan to, so we do not consider it a bug
