### ISSUE TITLE
[Bug]: Duplicates over Sites should be allowed in Pretty URL setting for Document

### ISSUE THREAD

**Issue by kraedler** [pimcore/pimcore#13095]
### Expected behavior

For every site with a specific domain the pretty url should be unique, but duplicates should be allowed, if in diffrent site context.

### Actual behavior

Error Message "URL path already exists" is displayed, if two pretty urls with the same name are set within diffrent sites.

### Steps to reproduce

- Create two documents configured as sites
- Create one document per site
- Set pretty url for both documents to the same string (e.g.: "/newsletter")
- After saveing error message "URL path already exists" is displayed

**Comment by kingjia90** [comment]
Thank you for reporting, i've took a look and can confirm the problem.
I've also found out that it was already reported on https://github.com/pimcore/pimcore/issues/7219, so i am closing here in foavor of the other one
