### ISSUE TITLE
[Bug]: Classification Store groups cannot list everything if there are many items

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#13101]
### Expected behavior

All items in a CS group should be visible and editable.

### Actual behavior

![image](https://user-images.githubusercontent.com/279826/189089508-25a5a6a4-74d1-42df-b9c7-782c82b099e5.png)

### Steps to reproduce

Image above shows how it looks with a group with 30 keys:
![image](https://user-images.githubusercontent.com/279826/189090003-ccb53540-aedc-4404-8e85-da37e1b9a3d5.png)

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/13103
