### ISSUE TITLE
Bug: Inserting a Dailymotion video

### ISSUE THREAD

**Issue by MercuryKojo** [pimcore/pimcore#1311]
# Bug Report
inserting a dailymotion link with the short url (for example: http://dai.ly/x5cwsz2) results in a page not found.
It doesn't extract the ID

**Comment by weisswurstkanone** [comment]
Works perfectly fine for me. Note that you have to enter the ID instead of the short URL.
See https://www.pimcore.org/docs/latest/Documents/Editables/Video.html

![video-tag](https://cloud.githubusercontent.com/assets/6142086/23659288/ed527c4e-0345-11e7-91df-c8a02eb5a99f.png)
