### ISSUE TITLE
[Bug]: preCopy Event is not Working

### ISSUE THREAD

**Issue by praveenjha2112** [pimcore/pimcore#13128]
### Expected behavior

![image](https://user-images.githubusercontent.com/112381479/189639123-989f0e5f-e4db-475f-a633-7c50f8ca30d3.png)
When i create a copy/paste an object it  should display me the dump of event/object in  .

`class ObjectActionListener{
   /*
    * funcation to handle preCopy Event
    * 
    */
    
    public function onPreCopy(\Pimcore\Event\Model\DataObjectEvent $event){
        
        $object = $event->getObject();
        $object->setName("postCopyEvent");
        //$this->preventCopyAction($object);
        //dd($object);
        
    }`

`App\EventListener\ObjectActionListener:
        tags:
          - { name: kernel.event_listener, event: pimcore.dataobject.postCopy, method: onPreCopy }`

### Actual behavior

Its not showing any output /dump  on copy

### Steps to reproduce

1. Create an event listener 
`lass ObjectActionListener{
   /*
    * funcation to handle preCopy Event
    * 
    */
    
    public function onPreCopy(\Pimcore\Event\Model\DataObjectEvent $event){
        
        $object = $event->getObject();
        $object->setName("postCopyEvent");
        //$this->preventCopyAction($object);
        //dd($object);
        
    }
    
    /*
     * function to prevent the copy action on given instance
     * 
     * @param $objet
     * 
     * throw ValidationException on true
     */
    private function preventCopyAction($object){
        
        if($object instanceof \App\Model\Customer ||
           $object instanceof \Pimcore\Model\DataObject\Vendor ||
           $object instanceof \Pimcore\Model\DataObject\Product
        ){
            $objectKey = $object->getKey();
            if(str_contains($objectKey,"_copy")==true){
                throw new \Pimcore\Model\Element\ValidationException("Copy/Paset action not allowed");
            }
        }
    }
}`

2. Configure it in services.yaml

`App\EventListener\ObjectActionListener:
        tags:
          - { name: kernel.event_listener, event: pimcore.dataobject.postCopy, method: onPreCopy }`

And try the copy action.

**Comment by SamyMP** [comment]
The "PRE_COPY" event is fired when you paste the copied object. I feel like this event needs to be rename "PRE_PASTE" and "POST_PASTE" since the event is triggered chen you click on "Paste as a child"

**Comment by robertSt7** [comment]
@praveenjha2112 Hello, thanks for reporting this bug. I'm not quite sure what you're trying to accomplish. But if you want to make changes to an object with setter, you have to save the object afterwards. dd doesn't work here, please try var_dump or p_r and look in the javascript console. I hope I could help you with this

**Comment by robertSt7** [comment]
The issue is closed due to inactivity.
Please feel free to reopen the issue at any time if you need further help.
