### ISSUE TITLE
Add a shorthand for "getter" and "setter" on Objects

### ISSUE THREAD

**Issue by ckogler-elements** [pimcore/pimcore#1312]
# Feature Request 
Currently we often need to create getter/setter to get or set values by a field name.

                    $fieldNames = ['field1','field2'];

                    foreach($fieldNames as $field){
                        #currently
                        $value = $o->{"get".ucfirst($field)}();
                        #could be
                        $value = $o->get($field);
                    }

Add a shorthand to get and set Values on objects by there field Name. 

Add the following Code to the AbstractObject.php

    /**
     * @param string $fieldName
     * @return mixed
     */
    public function get($fieldName){
        return $this->{"get".ucfirst($fieldName)}();
    }

    /**
     * @param string $fieldName
     * @param $value
     * @return mixed
     */
    public function set($fieldName,$value){
        return $this->{"set".ucfirst($fieldName)}($value);
    }

**Comment by brusch** [comment]
Would be also good then to have them on localized fields and objects bricks (and maybe somewhere else?) - just to be consistent.
