### ISSUE TITLE
[Improvement]: Version storage migration from file system to database

### ISSUE THREAD

**Issue by adriangronau** [pimcore/pimcore#13120]
### Improvement description

First of all, thank you to the maintainers for adding the possibility to use a database to store version files instead of the file system!

While I've managed to setup the new storage adapters, I'm wondering if there is any (standard) way to transfer version files from the file system to the database. Did anyone already wrote a script for this purpose? I couldn't find anything online related to this ...

Thanks!

**Comment by mcop1** [comment]
@tharkay I moved your question to the discussions as there is no migration from pimcore side. Maybe someone in the community can help you out.
