### ISSUE TITLE
Different key on Variant create

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#1315]
# Different key on Variant create

The Key of an Object get a different Name when you add a New Variant by click Add on the MainObject

![key](https://cloud.githubusercontent.com/assets/1086343/23304262/2b411688-fa99-11e6-90f3-73d9c2b8bfb7.png)

**Comment by weisswurstkanone** [comment]
Could you please give a precise example / steps to reproduce ... ?

**Comment by weisswurstkanone** [comment]
@putzflorian also see https://github.com/pimcore/pimcore/issues/1334

**Comment by weisswurstkanone** [comment]
fixed in build 4057

**Comment by weisswurstkanone** [comment]
also see https://github.com/pimcore/pimcore/issues/1335
