### ISSUE TITLE
[Bug]: Pimcore portal: public share link "in collections" is not working 

### ISSUE THREAD

**Issue by Hcheikhis** [pimcore/pimcore#13168]
### Expected behavior

After generating public share link , should the result be available .

### Actual behavior

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

No Results

### Steps to reproduce

1. create new collection 
2. add some assets 
3. defining the public share configs (name, expire day , ...)
4. copy, past the generated link in new browser tap

**Comment by mcop1** [comment]
Is the other issue you created a duplicate or a really a separate issue?
https://github.com/pimcore/portal-engine/issues/240

**Comment by Hcheikhis** [comment]
Is a separate issue

**Comment by kingjia90** [comment]
@Hcheikhis could you please provide further details about the output `<!DOCTYPE `... ? It could be hinting a permission issue or some other bugs. If possible, a screenshot of the developer tools preview tab of the given XHR call.

**Comment by kingjia90** [comment]
Thank you again for reporting!
I am closing this issue, as it feels may be originated by the same problem that we found about the `collectionId` not being nullable in the db table of the prod env (which is now https://github.com/pimcore/portal-engine/issues/240)

@Hcheikhis If it's still occuring, please open a new ticket on the Portal Engine repository.
If you don't have already access to it, please contact [enterprise-support@pimcore.com](mailto:enterprise-support@pimcore.com)
