### ISSUE TITLE
[Improvement]: Admin translation in Document to use current admin language

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#13161]
### Improvement description

If you are currently using some admin translation in a twig template of your documents (as described in the docs [here](https://pimcore.com/docs/pimcore/current/Development_Documentation/Multi_Language_i18n/Admin_Translations.html#page_Example-Translate-Options-of-a-Select-Editable) ) this translation will use the language of the current document. I propose to use the language of the current admin user instead as admin translations are used for the currently logged admin and it'd behave the same way as the names of editables.

**Comment by kingjia90** [comment]
Not sure if i got it right, did you mean that since the 'admin' translation domain is set, it should consider the current user (logged in admin interface) language, right?

**Comment by Cruiser13** [comment]
Yes, exactly @kingjia90 
If it does just take the document language, we could use a normal translation instead of an admin translation.
We'd like to use admin translations for editmode notes for the current user. Would be great to have them in his (user) language, even if he is on a document with a different language.

**Comment by kingjia90** [comment]
@Cruiser13 The PR #14074 may solve the situation you have described.
At the moment, is not possible to make it as default behaviour to switch to which language depending on the translation domain (as it would take changes that diverge too much from the native twig functionalities), but at least  the PR provides helpers to manually set that behaviour whenever needed.

**Comment by Cruiser13** [comment]
@kingjia90 looks good to me! Any chance to get this in the Pimcore X branch instead of 11?

**Comment by kingjia90** [comment]
Even though i don't see any drawbacks (since the twig function is added in a internal class), the chances are unfortunately low, we are trying to keep 10.6 reserved for things that will smoothen transition to 11 and it doesn't look like strictly to a bug neither, but who knows, maybe something else come up during the review

**Comment by kingjia90** [comment]
> but who knows, maybe something else come up during the review

@Cruiser13 it happened! It's planned for 10.6 now 😄

**Comment by jdreesen** [comment]
Just out of curiosity: is there an ETA for `v10.6`? Will it be released together with Pimcore `v11.0` or before?

**Comment by kingjia90** [comment]
> Just out of curiosity: is there an ETA for `v10.6`? Will it be released together with Pimcore `v11.0` or before?

I don't know if there's any change, but officially and ideally it should be before, but realistically could be that will be released together. 
It depends on how many other BC breaking changes, maybe after the beta release, there would be a more clearer big picture

**Comment by dvesh3** [comment]
Fixed by #14074
