### ISSUE TITLE
[Bug]: svg with transparent background becomes black background

### ISSUE THREAD

**Issue by hethehe** [pimcore/pimcore#13167]
### Expected behavior

background remains transparent

### Actual behavior

background becomes black

### Steps to reproduce

Upload a .svg image with transparent background (or without background at all)
Show the preview in admin mode or in frontend (with defined thumbnail)

Didn't found out where exactly the bug is, but with an older (about 3 month ago / Image) pimcore/pimcore:PHP8.1 image it worked as expected. The only difference I found is that on the old image Inkscape was NOT installed.
ImageMagick Version of the old (working) image was:
Version: ImageMagick 7.1.0-32 Q16-HDRI x86_64 20006

**Comment by dvesh3** [comment]
seems related to https://github.com/pimcore/pimcore/pull/11807

**Comment by dvesh3** [comment]
My findings are:

When taking pull of latest docker images and building the containers, the new version of imagemagick is installed which is version `7.1.0-48 Q16-HDRI x86_64 20449` and the svg transparent thumbnail issue is reproducible on latest version as shown below:

Image used: 
![transparency-svgrepo-com (1)](https://user-images.githubusercontent.com/5137917/191730667-1df1c59e-7024-4120-947c-bb2bb5e56900.svg)


:heavy_check_mark: Thumb on old imagemagick version: `ImageMagick 7.1.0-32 Q16-HDRI x86_64 20006`

![image](https://user-images.githubusercontent.com/5137917/191731212-8b4a3f75-8bb1-47ea-99fd-d73240136e5d.png)

:x: Thumb on imagemagick version: `ImageMagick 7.1.0-48 Q16-HDRI x86_64 20449`
![image](https://user-images.githubusercontent.com/5137917/191731056-5df2c510-eb16-4bd4-baaf-5ed97a34f922.png)


This [PR](https://github.com/pimcore/pimcore/pull/11807) fixed the problem on 10.3.* version but it is not working anymore.

**Comment by brusch** [comment]
Please check if this still remains an issue in latest v2 Docker images (`php8.2-latest`). 
There we have `ImageMagick 7.1.0-4 Q16 x86_64 2021-07-18`. 
If it's still an issue we need to see how we can implement a proper workaround fixing the issue.

**Comment by dvesh3** [comment]
Issue resolved with latest version `ImageMagick 7.1.0-4 Q16 x86_64 2021-07-18` in `php8.2-latest`
