### ISSUE TITLE
Pimcore login username should be case sensitive

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#13174]
### Expected behavior

Pimcore login username should be case sensitive

### Actual behavior

Login is not implemented with case sensitive username like,
IF we have username: admin,  in that case, we can log in with **ADmiN** username also, I think the username should be case sensitive.

### Steps to reproduce

Go to Pimcore admin login page -> https://demo.pimcore.fun/admin

we have username: **admin** and password: **demo** but If we use **ADmiN** as username and click on the login button, then we login successfully on the Pimcore admin.

**Comment by NiklasBr** [comment]
OWASP suggests that usernames should be case insensitive.

> Make sure your usernames/user IDs are case-insensitive. User 'smith' and user 'Smith' should be the same user. Usernames should also be unique. For high-security applications, usernames could be assigned and secret instead of user-defined public data.

https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html

**Comment by robertSt7** [comment]
Closed due to owasp recommendation
