### ISSUE TITLE
[Bug]: Pimcore Backend UI: object.edit.getLayout() returns only first tab

### ISSUE THREAD

**Issue by MyZik** [pimcore/pimcore#13181]
### Expected behavior

`object.edit.getLayout()` should return the layout data with all fields

### Actual behavior

`object.edit.getLayout()` returns the from the first tab

### Steps to reproduce

I have custom `Property` objects like: Color, Size, etc.
Then I have a `PropertyOption` object with relation to `Property` like: Red -> Color, Green -> Color, Blue -> Color, S -> Size, M -> Size, L -> Size. In my `Product` object I have a FieldCollection with `property` and `propertyOption` fields. 

I want to create a select field in my FieldCollection, that shows only propertyOption from selected Property. I've built a script that dynamically sets the options for selected field based on data from read-only `property` field in FieldCollection.

```js
pimcore.registerNS('pimcore.test.admin.plugin');

pimcore.test.admin.plugin = Class.create(pimcore.plugin.admin, {
    getClassName: function () {
        return 'pimcore.test.admin.plugin';
    },

    initialize: function () {
        pimcore.plugin.broker.registerPlugin(this);

        this.initializeStores();
    },

    initializeStores: function () {
        Ext.define('Product', {
            extend: 'Ext.data.Model',
            fields: [
                { name: 'key', type: 'string' },
                { name: 'value', type: 'int' }
            ]
        });
    },

    postOpenObject: function (object, type) {
        if (object.data.general.o_className !== 'Product' || type !== 'object') {
            return;
        }

        let properties = object.edit.getLayout().query('combobox[name=productProperty]');
        let propertyOptions = object.edit.getLayout().query('combobox[name=productPropertyOption]');

        if (properties.length > 0) {
            properties.forEach(function callback(property, index) {
                let store =  Ext.create('Ext.data.Store', {
                    model: 'Product',
                    proxy: {
                        type: 'ajax',
                        url: '/admin/store/property-options/',
                        reader: { type: 'json', rootProperty: 'data' }
                    }
                });

                property.on('select', (cb, m) => {
                    store.load({ params: { propertyId: m.data.value }});
                });

                propertyOptions[index].setStore(store);
            });
        }
    }
});

let PimcoreTestAdminPlugin = new pimcore.test.admin.plugin();
```

The problem is: it worked with Pimcore 10.2, but after update to Pimcore 10.4 `object.edit.getLayout()` it returns only the field from the first tab (In my object I have 10 Tabs)

![Bildschirmfoto 2022-09-16 um 13 49 25](https://user-images.githubusercontent.com/12817320/190632867-4ad31015-cd8a-4aa4-9938-20988b2a876f.png)

**Comment by robertSt7** [comment]
@MyZik Hello, thanks for reporting this problem. Since the other tabs are not rendered in the DOM, only the first tab is ever returned. Maybe you could try not to address the elements via the DOM, but via the ExtJS elements. Hope this helps, thank you.

**Comment by robertSt7** [comment]
The issue is closed due to inactivity.
Please feel free to reopen the issue at any time if you need further help.
