### ISSUE TITLE
[Bug]: Warning: "Attempt to read property "containerKey" on null" when i want to save a data object

### ISSUE THREAD

**Issue by Chris-Gett** [pimcore/pimcore#13189]
### Expected behavior

just safe the object without the warning...

### Actual behavior

The Warning: "Attempt to read property "containerKey" on null" appears when i want to save a data object. 

The message does not appear with all, but only with a certain class of data objects. I have for me at the moment no approach where I can look for the error.

Also, I can't edit this data object in the table view either, I always have to open the object first.

____
Status: 500 | 
URL: /admin/object/save?task=publish
Method: PUT
Message: Warning: Attempt to read property "containerKey" on null
Trace: 
in /home/xxx/pimcore_live/vendor/pimcore/pimcore/lib/DataObject/GridColumnConfig/Value/DefaultValue.php:197
#0 /home/xxx/pimcore_live/vendor/pimcore/pimcore/lib/DataObject/GridColumnConfig/Operator/Base64.php(55): Pimcore\DataObject\GridColumnConfig\Value\DefaultValue->getLabeledValue(Object(Pimcore\Model\DataObject\Keyboard))
#1 /home/xxx/pimcore_live/vendor/pimcore/pimcore/models/DataObject/Service.php(560): Pimcore\DataObject\GridColumnConfig\Operator\Base64->getLabeledValue(Object(Pimcore\Model\DataObject\Keyboard))
#2 /home/xxx/pimcore_live/vendor/pimcore/pimcore/models/DataObject/Service.php(1976): Pimcore\Model\DataObject\Service::calculateCellValue(Object(Pimcore\Model\DataObject\Keyboard), Array, '#62fc901fc9aba', Array)
#3 /home/xxx/pimcore_live/vendor/pimcore/pimcore/models/DataObject/Service.php(1830): Pimcore\Model\DataObject\Service::getCsvFieldData('de', '#62fc901fc9aba', Object(Pimcore\Model\DataObject\Keyboard), 'de', Array)
#4 /home/xxx/pimcore_live/vendor/pimcore/data-hub-file-export/src/Exporter/AbstractExporter.php(297): Pimcore\Model\DataObject\Service::getCsvDataForObject(Object(Pimcore\Model\DataObject\Keyboard), 'de', Array, Array, Object(Pimcore\Localization\LocaleService), true, Array)
#5 /home/xxx/pimcore_live/vendor/pimcore/data-hub-file-export/src/Exporter/File.php(105): Pimcore\Bundle\DataHubFileExportBundle\Exporter\AbstractExporter->getItemData(Object(Pimcore\Model\DataObject\Keyboard))
#6 /home/xxx/pimcore_live/vendor/pimcore/data-hub-file-export/src/Exporter/AbstractExporter.php(388): Pimcore\Bundle\DataHubFileExportBundle\Exporter\File->getItemData(Object(Pimcore\Model\DataObject\Keyboard))
#7 /home/xxx/pimcore_live/vendor/pimcore/data-hub-file-export/src/EventSubscriber/DataObjectSubscriber.php(99): Pimcore\Bundle\DataHubFileExportBundle\Exporter\AbstractExporter->getExportData(Array)
#8 /home/xxx/pimcore_live/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(117): Pimcore\Bundle\DataHubFileExportBundle\EventSubscriber\DataObjectSubscriber::doExport(Object(Pimcore\Event\Model\DataObjectEvent), 'pimcore.dataobj...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#9 /home/xxx/pimcore_live/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Pimcore\Event\Model\DataObjectEvent), 'pimcore.dataobj...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#10 /home/xxx/pimcore_live/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'pimcore.dataobj...', Object(Pimcore\Event\Model\DataObjectEvent))
#11 /home/xxx/pimcore_live/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(154): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Pimcore\Event\Model\DataObjectEvent), 'pimcore.dataobj...')
#12 /home/xxx/pimcore_live/vendor/pimcore/pimcore/lib/Event/Traits/RecursionBlockingEventDispatchHelperTrait.php(41): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(Object(Pimcore\Event\Model\DataObjectEvent), 'pimcore.dataobj...')
#13 /home/xxx/pimcore_live/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(822): Pimcore\Model\Element\AbstractElement->dispatchEvent(Object(Pimcore\Event\Model\DataObjectEvent), 'pimcore.dataobj...')
#14 /home/xxx/pimcore_live/vendor/pimcore/pimcore/models/DataObject/Concrete.php(720): Pimcore\Model\DataObject\AbstractObject->save(Array)
#15 /home/xxx/pimcore_live/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(1375): Pimcore\Model\DataObject\Concrete->save()
#16 /home/xxx/pimcore_live/vendor/symfony/http-kernel/HttpKernel.php(153): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#17 /home/xxx/pimcore_live/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#18 /home/xxx/pimcore_live/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 /home/xxx/pimcore_live/public/index.php(37): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#20 {main}

### Steps to reproduce

hard to say... it´s just in my specific data object

**Comment by damianlinek** [comment]
https://github.com/pimcore/pimcore/pull/12908/files
Upper PR is causing a problem. Im not sure why there is containerKey attribute, cause I have nothing like this at my objectbricks and json is always null in all of my tests.

### Steps to reproduce
1. Add Operator to grid
2. Add field from objectbrick as child to operator
3. save

Grid view:
![image](https://user-images.githubusercontent.com/86970682/193211928-d5f6b99b-3b79-49a6-805f-2cc5ab99f9a5.png)

**Comment by Chris-Gett** [comment]
I have found the cause. It was an old file export that I had created at some point and that contained an outdated schema including the operator. So I can confirm the reproduction of @damianlinek

**Comment by mcop1** [comment]
@Chris-Gett Sorry, couldn´t reproduce the problem, are you sure you are using a localized field with the locale switcher operator?

**Comment by damianlinek** [comment]
@mcop1 Problem is not with LocaleSwitcher and localizedfields, that was just example. Problem is with Operators and using ObjectBricks fields. 
Example of TranslatorOperator and objectbrick field. I supposed that this operator is not created only for localizedfields?

![image](https://user-images.githubusercontent.com/86970682/195533772-68d62acb-2822-41a4-bf85-e190ed095f35.png)

Error is occurring at `Pimcore\DataObject\GridColumnConfig\Value\DefaultValue()->getLabeledValue()` for everything on objectbrick what is not an localizedfield.

**Comment by mcop1** [comment]
@damianlinek I see, thanks, I got your point now
