### ISSUE TITLE
impossible to override unchecked checkbox state in variant object

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#1318]
Currently it's impossible to uncheck a inherited checkbox in a object variant. for sure there is a logical reason for that (empty value => inherit from parent) but i think this is not an expected behaviour.

### Steps to reproduce

> 1. variant untouched:

![bildschirmfoto 2017-02-27 um 14 25 27](https://cloud.githubusercontent.com/assets/700119/23363018/ccd6e9d0-fcf8-11e6-84c6-b55fb24acf42.png)

> 2. disable inheritance for checkbox and uncheck it:

![bildschirmfoto 2017-02-27 um 14 26 03](https://cloud.githubusercontent.com/assets/700119/23363024/d7199992-fcf8-11e6-8dd2-a325661fe36e.png)

> 3. after a reload, the inherited value will show up again:

![bildschirmfoto 2017-02-27 um 14 26 09](https://cloud.githubusercontent.com/assets/700119/23363056/f4824eb6-fcf8-11e6-80ec-752f45ed569f.png)

**Comment by brusch** [comment]
This is a known "problem" and caused by the fact that a checkbox has only 2 states, but it would require at least 3 to allow the behavior you described (`true` | `false` | `null`). 

So in your case it's best to go for the select data-type.

**Comment by brusch** [comment]
see also #201
