### ISSUE TITLE
[Bug]: search_backend_data does not get updated when the folder changes

### ISSUE THREAD

**Issue by hethehe** [pimcore/pimcore#13208]
### Expected behavior

Backend Search Index (table: search_backend_data) should also be updated if the folder changes (rename)

### Actual behavior

Backend Search Index (table: search_backend_data) is not updated if the folder changes (rename)

### Steps to reproduce

- create a folder in assets
- upload a file to this folder
- open database and search for the ID of this document in the table "search_backend_data"
  - check "fullpath" and "data"
- rename the folder
- refresh database view
  - check "fullpath" and "data" again (its still the old value)

**Comment by dvesh3** [comment]
Fixed by #13417
