### ISSUE TITLE
[Feature]: Restrict dev environment to certain ip adresses

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#13215]
### Feature description

I'd love to see this feature, it has been really useful for Pimcore 6 and is gone since Pimcore X.
It's problematic to set the whole instance to dev mode if you want to debug a live system and creating another instance for debugging each time can really slow down the work process.
Some IP specification option for the DEV environment would be awesome.

**Comment by NiklasBr** [comment]
I suppose you could [use Symfony's access_control for this](https://symfony.com/doc/5.4/security/access_control.html) and have different [ENV variables per environment](https://symfony.com/doc/5.4/configuration.html#overriding-environment-values-via-env-local).

**Comment by Cruiser13** [comment]
I'm not sure about this @NiklasBr because the access control is already loaded inside an environment. If Pimcore is loading in the prod environment, it's not possible to switch to the dev environment at a point where access control can check something. But I might have missed something here.

**Comment by NiklasBr** [comment]
Aha, yeah now I think I understand. My suggestion would not help with that unfortunately.

**Comment by Cruiser13** [comment]
We found a general solution but some easier way/pimcore implementation would be great. 

Will post here for others with the same issue anyway.
Use the generally wished environment in our .env file, e.g.
```
APP_ENV=prod
APP_DEBUG=false
```
Modify the public/.htaccess with the following lines:
```
SetEnvIf Remote_Addr 255\.255\.255\.0 APP_ENV=dev
SetEnvIf Remote_Addr 255\.255\.255\.0 APP_DEBUG=1
```
where 255.255.255.0 is your IP address which should have the debug mode enabled.

**Comment by brusch** [comment]
Thanks for sharing your ideas, however, my feeling is we should stay as close to Symfony here as possible and follow their best practices. Therefore I'm closing this issue for now, but please feel free to continue the discussion 😊
