### ISSUE TITLE
[Bug] 2FA not trigger with new authenticator

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#13220]
After installing the latest Demo Package Version (10.5) on PHP 8.1, i tried to setup 2FA but it simply does not work. 

- Enabled the 2FA checkbox in the user profile 
- After reloading the backend no change in login form - 2FA does not trigger
- Fresh browser instance with cleared caches does not work either

I cleared all caches and temporary files, doesn't help. 

Setup: 
- Apache / PHP 8.1 FPM
- Redis Cache
- Maria DB 10.5

Thanks in advance!
Elmar

_Originally posted by @elmarputz in https://github.com/pimcore/pimcore/discussions/13219_

**Comment by elmarputz** [comment]
@dvesh3 thanks

**Comment by kingjia90** [comment]
Fixed by  #13225
