### ISSUE TITLE
Hospots & markers should not always disappear when replacing image

### ISSUE THREAD

**Issue by schuttelaar** [pimcore/pimcore#1322]
Sometimes people want to update an image in an image editable which has hotspots and markers. Currently the hotspots and markers all disappear without warning when the image is updated. This is very annoying because it takes a lot of time to add hotspots with all the data manually. 

It would be nice if there was an optional parameter for the image editable to keep the hotspot/markers when an image is replaced.

**Comment by weisswurstkanone** [comment]
![image](https://user-images.githubusercontent.com/6142086/34558046-bcb98574-f13c-11e7-81eb-b41d986b514c.png)

Added a confirmation window in case additional data exists.

Build 168.
