### ISSUE TITLE
Bump elasticsearch to ^8.0

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#13248]
### Improvement description

Elastic Search to ^8 [BC](https://github.com/elastic/elasticsearch-php/blob/master/BREAKING_CHANGES.md#80)

**Comment by fashxp** [comment]
This needs some more attention because of dependencies to https://github.com/ongr-io/ElasticsearchDSL
... there is no ES 8 support yet, and it seems it is quite inactive.

**Comment by fashxp** [comment]
- [x] https://github.com/pimcore/advanced-object-search/pull/176
- [x] https://github.com/pimcore/data-hub-simple-rest/pull/79
- [x] https://github.com/pimcore/portal-engine/pull/262
- [x] https://github.com/pimcore/statistics-explorer/pull/55
- [x] https://github.com/pimcore/pimcore/pull/13410
- [x] https://github.com/pimcore/pimcore/issues/13411
