### ISSUE TITLE
[Bug]: \Pimcore\Console\Application marked @internal, but meant for direct use by Pimcore apps' bin/console

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#13254]
### Expected behavior

Public API is not marked internal.

### Actual behavior

Pimcore Console Application marked `@internal`.

### Steps to reproduce

1. create a project from pimcore/skeleton
2. analyze with Psalm
3. [usage of Application](https://github.com/pimcore/skeleton/blob/b408879dd362a441646d0d1f7eb20c208c629d06/bin/console#L48) marked as invalid

**Comment by brusch** [comment]
Seems like a special case, because it's used in `bin/console`, but I'd keep it `@internal` because everything except `run()` shouldn't be used from outside.

**Comment by dkarlovi** [comment]
@brusch there's an option to do exactly what you've said: remove `@internal` from the class, add it to all the methods except the constructor and `run()`.
