### ISSUE TITLE
[Bug]: Updating Number field to only unsigned throws ValidationException but shows negative value on refresh

### ISSUE THREAD

**Issue by Krojan** [pimcore/pimcore#13269]
### Expected behavior

- Unsigned number field should not show negative value on refresh

### Actual behavior

-Unsigned number field shows negative value too but does not save that value in database

### Steps to reproduce
![Screenshot from 2022-09-29 10-30-17](https://user-images.githubusercontent.com/67037903/192940992-163d6404-552f-45e0-9986-d8e5ea6527f8.png)

![Screenshot from 2022-09-29 10-30-35](https://user-images.githubusercontent.com/67037903/192941039-29a098d8-40dc-4913-a867-c725b7883fd9.png)
![Screenshot from 2022-09-29 10-31-08](https://user-images.githubusercontent.com/67037903/192941111-c4095f63-4b72-4cf0-bd94-b36d39097848.png)

**Comment by brusch** [comment]
That probably happens when you change the setting of the field after you've set the value, right? 
That's probably a behavior we can't change ... 🤔

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
