### ISSUE TITLE
[Bug]: composer install with maintenance enabled

### ISSUE THREAD

**Issue by Navino16** [pimcore/pimcore#13283]
### Expected behavior

When maintenance mode is enabled we should be able to run "composer install"

### Actual behavior

When maintenance mode is enabled, composer install stop when running "Pimcore\Composer::clearCache"

![image](https://user-images.githubusercontent.com/22234867/193252253-b466481d-fee3-47fa-8f37-cc44295f2b98.png)

### Steps to reproduce

* Install last pimcore version
* Enable maintenance mode
* Run `composer install`

**Comment by dvesh3** [comment]
Regression of https://github.com/pimcore/pimcore/pull/12364
