### ISSUE TITLE
[Bug]: Statically generated page doesn't resolve with pretty URL

### ISSUE THREAD

**Issue by tmannherz** [pimcore/pimcore#13299]
### Expected behavior

Documents with pretty URLs configured should support server side-static rendering.

### Actual behavior

Static page generation doesn't consider the pretty URL when creating the static html file so the requested uri never matches the static file path. This causes nginx to miss rendering the page from a static file and voids the benefits of static generation.

### Steps to reproduce

1. In the Pimcore demo project, open any document. Set a pretty URL and enable static page generation:
    ![image](https://user-images.githubusercontent.com/533798/193710659-12b46f54-7b85-4b71-ab9e-e4677599e057.png)
1. Visit the page in the browser (eg. `/news`). A static html filed is generated to the document path (eg. `en/News.html`) rather than the pretty URL path (eg. `news.html`)
    ![image](https://user-images.githubusercontent.com/533798/193710976-9e293504-8277-4547-8151-38f7fe4a314d.png)
1. Visit the page again -- the static file is never accessed since the request URI doesn't match the generated file path

**Comment by dvesh3** [comment]
Fixed by #13310
