### ISSUE TITLE
[Pimcore5] Fieldtype date is not able to save the correct value (before 1951)

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#1329]
# Bug Report

When saving a date before the year 1951 (e.g. 01/01/1950) with the fieldtype "date" inside a object ...
  
### Expected behavior
... the timestamp saved into the database should contain the date 01/01/1950.
  
### Actual behavior  
... but it actually contains the value of 01/01/2050.

### Steps to reproduce  
I think this is an issue by the ExtJs Datepicker. Pimcore uses a date format like this:

**01/01/17** (two digit year)

eventhough it would be safer to have a format like this:

**01/01/2017** (four digit year)

The problem right now is, that you can't save a date correctly before 1951.
For example if I choose the date 01/01/1950 it automatically will be converted to 01/01/2050 by the datepicker. Please see the [video](https://github.com/pimcore/pimcore/files/819410/date-fieldtype.mov.zip)  attached. This was tested on https://demo.pimcore.org/.

I could imagine that the fieldtype "date & time" does the same, not tested though ...

**Comment by weisswurstkanone** [comment]
Probably aready fixed in ExtJS 6.0.2 (we are using 6.0.1)

Compare 
http://examples.sencha.com/extjs/6.0.1/examples/kitchensink/#form-fieldtypes
vs
http://examples.sencha.com/extjs/6.0.2/examples/kitchensink/#form-fieldtypes

**Comment by Cruiser13** [comment]
This is also true for dates after 2100 and this really needs to be fixed.

**Comment by weisswurstkanone** [comment]
As mentioned above, this seems to be already fixed in the next ExtJS version. We will upgrade asap.

**Comment by weisswurstkanone** [comment]
build 74
