### ISSUE TITLE
Wrong email HTML generated, dynamic params are correctly set

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#1330]
# Bug Report  

I'm sending out emails by cronjob using a foreach loop of accounts. I do assign the values to params like this:

```php
                //Send mail to the user according to cases
                if ($testprofileowner->getEmail() && ($testprofileowner->getEmailsactive() == true)) {
                    $maildoc = Document::getByPath('/mails/user/somemail'); //Warning: hard-coded path!
                    if ($maildoc) {
                        $params['link'] = '/somelink/'; 
                        $params['name'] = $testprofileowner->getFirstname() . ' ' . $testprofileowner->getLastname();
                        $mail = new \Pimcore\Mail();
                        $mail->setParams($params);
                        $mail->setDocument($maildoc);
                        $mail->setTo($testprofileowner->getEmail());
                        try {
                            $mail->send();
                        } catch (Exception $e) {
                            echo $e;
                        }
                    }
                }
```

The email template looks like this:

```php
Hello <?= $this->name ?>,<br />
```

  
### Expected behavior 
Each user does get a mail greeting him with first and lastname.

### Actual behavior  
Users do get emails with firstname and lastname of other accounts, sent in the same foreach loop. 
  

In the email document, the rendered html of the sent emails contains the wrong first- and lastname. The dynamic params do display the proper name though.

![email issue](https://cloud.githubusercontent.com/assets/2771909/23609735/bfd80a4e-026f-11e7-8fb3-d0e3e54855d2.png)

**Comment by datom** [comment]
I can confirm this bug. The first will generated correctly but any other mails will have the values.
A quick workaround for this issue is to use "$this->getParam('name')" instant of "$this->name" in the view.

**Comment by Cruiser13** [comment]
Thanks for confirmation and thanks for the quick fix @brusch !
