### ISSUE TITLE
[Bug]: Editing multiple Document Type rows causes issues

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#13313]
### Expected behavior

When editing Document Types they should all be updated with no error.

### Actual behavior

Sometimes ExtJs will send multiple edits simultaneously if the user makes many small edits after each other.

Because `bundles/AdminBundle/Controller/Admin/Document/DocumentController.php` expects only a single item rather than an array of items it breaks fatally in the method

https://github.com/pimcore/pimcore/blob/caab4a9186b302dfcadcb48b4bb414fbecabb350/bundles/AdminBundle/Controller/Admin/Document/DocumentController.php#L708

Screen shot showing debug:
![image](https://user-images.githubusercontent.com/279826/194031840-2dc3ed59-ecde-4186-88e8-c8d7bfbc2065.png)

Screen showing two rows being edited, this causes `$data` in DocumentController to be an `array`:
![image](https://user-images.githubusercontent.com/279826/194034813-67e3b40f-f1c8-457d-aba0-cb2dea5fcf61.png)

### Steps to reproduce

1. Add a number of Document Types
2. Update them (e.g. the name) in quick succession, best way appears to quickly set focus on a second item quickly after pressing the `enter` key

**Comment by aryaantony92** [comment]
Fixed by #13324
