### ISSUE TITLE
[Bug]: Video - Thumbnail is not generated

### ISSUE THREAD

**Issue by vignesh-happiestminds** [pimcore/pimcore#13337]
### Expected behavior

When we upload the video into Asset and open the video . The video should show play and thumbnail should shown in right side

![Screenshot from 2022-10-07 19-20-55](https://user-images.githubusercontent.com/109342064/194569633-d8fc0039-d00e-433b-a41e-2ffa1ba3e7a2.png)

### Actual behavior

I am using  pimcore version 10.5.7. 

When i upload the video into assets. When we opened the video, the video not playing. When we close the video tab and reopened. The video is playing without an issue.

But thumbnail image is not generated and not shown in the right side bar.

![Screenshot from 2022-10-07 19-20-55](https://user-images.githubusercontent.com/109342064/194571449-6a29faaf-b82d-4c6c-8e5f-8a0498ec4423.png)

### Steps to reproduce

- Login into application as admin
- Click on Assets Menu
- Under Asset - Click on Add Asset -> Upload File - Select video file
- Open the uploaded video

**Comment by brusch** [comment]
@vignesh-happiestminds Can you confirm this happens also on demo.pimcore.org? 
My guess is that you don't have the message queue processing running, see:  https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Installation.html#page_5-Maintenance-Cron-Job

**Comment by vignesh-happiestminds** [comment]
@brusch , i have running below command to verify the Thumbnail generation.

**bin/console messenger:consume pimcore_core pimcore_maintenance pimcore_image_optimize -vv --time-limit=300**

I attached log screenshot here.

![Screenshot from 2022-10-10 14-59-12](https://user-images.githubusercontent.com/109342064/194836282-1d939295-2b2b-4504-a293-235d26a36cce.png)

Also, In demo site "https://demo.pimcore.fun/" video preview is not working.

![Screenshot from 2022-10-10 14-57-53](https://user-images.githubusercontent.com/109342064/194835997-285d892a-0569-4f5f-8ee0-92dbda63f5e8.png)

**Comment by brusch** [comment]
ah, I'm sorry, on the demo.pimcore.fun the messenger:consume command is also not running 😉

**Comment by vignesh-happiestminds** [comment]
@brusch  But in my local development environment "**messenger:consume**" is running . I have attached screen-shot as well on the above comments.

**Comment by vignesh-happiestminds** [comment]
@brusch  Any update on this issues. When can i expect issue fix.

**Comment by brusch** [comment]
I can't reproduce it locally, so doesn't seem to be an issue in general, but related to your local setup ...
