### ISSUE TITLE
[Bug]: FullPageCacheListener starts session before custom session bags are registered

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#13333]
### Expected behavior

No error with enabled full page cache and disabled debug mode.

### Actual behavior

Following error occurs:
![image](https://user-images.githubusercontent.com/9052094/194512955-a1f8228c-8dce-4133-bd11-bdfd9b130690.png)

**Likely cause:**
FullPageCacheListener starts session before custom session bags are registered. See https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/src/EventListener/Frontend/FullPageCacheListener.php#L243 (`::authenticateSession()`)

### Steps to reproduce

Use the following config:

```
pimcore:
    full_page_cache:
        enabled: true
```

and 

```
APP_DEBUG=0
```

and access any route not skipped by FullPageCacheListener.

**Comment by brusch** [comment]
@jremmurd I think we just need to change the priority here
https://github.com/pimcore/pimcore/blob/d328bcd040ecd1f66e2536db92aa8e7b5369fcc0/bundles/EcommerceFrameworkBundle/EventListener/SessionBagListener.php#L41

to be executed before: 
https://github.com/pimcore/pimcore/blob/07ec590718221bc65e460d1eed09953d19208cc5/bundles/CoreBundle/Resources/config/event_listeners.yaml#L131

Can you check that and provide a PR if it fixes the issue? 
Thanks a lot in advance!

**Comment by jremmurd** [comment]
> @jremmurd I think we just need to change the priority here
> 
> https://github.com/pimcore/pimcore/blob/d328bcd040ecd1f66e2536db92aa8e7b5369fcc0/bundles/EcommerceFrameworkBundle/EventListener/SessionBagListener.php#L41
> 
> to be executed before:
> 
> https://github.com/pimcore/pimcore/blob/07ec590718221bc65e460d1eed09953d19208cc5/bundles/CoreBundle/Resources/config/event_listeners.yaml#L131
> 
> Can you check that and provide a PR if it fixes the issue? Thanks a lot in advance!

Setting the prio, to a value higher than 610 (i.e. 620), results in another error `session has not been set`. 

<details><summary>Click to see the stacktrace</summary>

![image](https://user-images.githubusercontent.com/9052094/194540700-23edd08e-d430-46b1-9308-772d342b4e53.png)

</details>

**Comment by dvesh3** [comment]
@jremmurd SessionBagListener already considers if the session is started and doesn't register bag in that case. please see https://github.com/pimcore/pimcore/blob/d328bcd040ecd1f66e2536db92aa8e7b5369fcc0/bundles/EcommerceFrameworkBundle/EventListener/SessionBagListener.php#L70 Looking at your screenshot, it seems the issue is coming from `workfront-auth-bundle`. could you please try changing the prio in the bundle SessionBagListener? thanks!

**Comment by jremmurd** [comment]
> @jremmurd SessionBagListener already considers if the session is started and doesn't register bag in that case. please see
> 
> https://github.com/pimcore/pimcore/blob/d328bcd040ecd1f66e2536db92aa8e7b5369fcc0/bundles/EcommerceFrameworkBundle/EventListener/SessionBagListener.php#L70
> 
> Looking at your screenshot, it seems the issue is coming from `workfront-auth-bundle`. could you please try changing the prio in the bundle SessionBagListener? thanks!

If I disable all bundles which register custom session bags, then it hangs where Berni already pointed out - in the EcommerceFramework. 
See https://github.com/pimcore/pimcore/blob/d328bcd040ecd1f66e2536db92aa8e7b5369fcc0/bundles/EcommerceFrameworkBundle/EventListener/SessionBagListener.php#L81

**Comment by dvesh3** [comment]
@jremmurd could you please put a break point [here](https://github.com/pimcore/pimcore/blob/d328bcd040ecd1f66e2536db92aa8e7b5369fcc0/bundles/EcommerceFrameworkBundle/EventListener/SessionBagListener.php#L70)? as Ecommerce SessionBagListener should not register bags when the session already started. thanks!

**Comment by dvesh3** [comment]
Closed due to inactivity. Please feel free to discuss further. thanks!

**Comment by jremmurd** [comment]
> Closed due to inactivity. Please feel free to discuss further. thanks!

Due to changes in our environment we deactivated the full page cache at all, thus I did not have any time to look into the matter any further, but I think the issue still exists.

**Comment by dvesh3** [comment]
Already fixed by https://github.com/pimcore/pimcore/pull/13442. thanks!
