### ISSUE TITLE
[Bug]: country not displayed in advanced many to many object relation column

### ISSUE THREAD

**Issue by kjkooistra-youwe** [pimcore/pimcore#13341]
### Expected behavior

Display the country when a country select field is configured as visible field on an advanced many to many object relation.

### Actual behavior

The country is not displayed.

### Steps to reproduce

- Go to the [demo environment](https://demo.pimcore.com/admin/) and open the class editor.
- Add a Country class (identifier 'country') and import [class_country_export.json.zip](https://github.com/pimcore/pimcore/files/9745559/class_country_export.json.zip).
- Add a Test class (identifier 'test') and import [class_test_export.json.zip](https://github.com/pimcore/pimcore/files/9745564/class_test_export.json.zip).

- Edit the 'countries' field.
- Select 'Country' as 'Allowed Class' (doesn't appear to be imported correctly).
- Save the class.

![Test_countries_allowed_class_empty](https://user-images.githubusercontent.com/24292941/194857790-79ac92bd-ed16-48ea-a4e6-8961f6dadeb7.png)

- Create a few Country data objects.

![Country_AT](https://user-images.githubusercontent.com/24292941/194857827-2f6ecc46-56e5-476c-bd5d-3a2ca3aa5a12.png)
![Country_NL](https://user-images.githubusercontent.com/24292941/194857846-8ad2f025-b548-4bc6-8009-4072188a9294.png)

- Create a Test data object.
- Drag and drop the Country data objects into the countries relation field.
- Save and publish.
- Reload the data object.

![Test_countries](https://user-images.githubusercontent.com/24292941/194857893-61aff7da-2806-4afd-807b-e725595ca808.png)

**Comment by mattamon** [comment]
Hey @kjkooistra-youwe,

I found the problem and will provide a solution.
https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/public/js/pimcore/object/tags/country.js#L27

If the config for the country is loaded in the Advanced Many-To-Many Object Relation, the value is a string and not an object. Therefore value.value returns undefined. 

My fix simply adds another if condition to check if the value is an object.

`if (value && Ext.isObject(value))`

Tested it locally with pimcore version 10.5.7 and it works.
