### ISSUE TITLE
[Bug]: Why is `QueryBuilderHelperTrait` marked as `@internal`?

### ISSUE THREAD

**Issue by jdreesen** [pimcore/pimcore#13344]
### Expected behavior

The docs suggest using the trait here: https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Custom_Persistent_Models.html#page_Listing-Dao

So I'd assume it isn't `@internal`.

### Actual behavior

The trait is marked as `@internal`.

### Steps to reproduce

Try to create a new listing DAO according to the docs.

**Comment by dvesh3** [comment]
Fixed by #13364
