### ISSUE TITLE
[Improvement]: use JSON data type where appropriate

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#13359]
### Improvement description

With MySQL v8, [JSON data type](https://dev.mysql.com/doc/refman/8.0/en/json.html) is available. Pimcore stores JSON in some places into plain text fields (for example, classification store keys definition), while storing as actual JSON has benefits. Pimcore 11 could take advantage of it.

**Comment by NiklasBr** [comment]
This would be nice in e.g. `documents_editables.data`

**Comment by lukmzig** [comment]
Possible tables for change:

- classificationstore_keys.defintion
- gridconfigs.config
- importconfigs.config
- users.keyBindings
- ecommerceframework_pricing_rule.label
- ecommerceframework_pricing_rule.description
- targeting_storage.value
- settings_store.data? (data with ID Bundle are not in JSON format right now)

**Comment by mcop1** [comment]
> Possible tables for change:
> 
>     * classificationstore_keys.defintion
> 
>     * gridconfigs.config
> 
>     * importconfigs.config
> 
>     * users.keyBindings
> 
>     * ecommerceframework_pricing_rule.label
> 
>     * ecommerceframework_pricing_rule.description
> 
>     * targeting_storage.value
> 
>     * settings_store.data? (data with ID Bundle are not in JSON format right now)

Right now we will only change columns which contain json strings and nothing else.
