### ISSUE TITLE
[Bug]: Icon inconsistency when creating a document named `home`

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#13354]
### Expected behavior

The 🏠 icon on Root Home (id:1) and sites/portal, but not on the pages

### Actual behavior

![image](https://user-images.githubusercontent.com/6014195/195302158-ed70658a-d979-4dc5-9ac6-2c8e1d6919a6.png)

The page and icon are inconsistent, it somehow replaces the icon in the tree and it's never shown as :house: in the tab bar.

### Steps to reproduce

Just create a document/page named as `home` and playing around with tabs and tree view.

**Comment by mattamon** [comment]
@kingjia90 I think this is fixed? At least I cannot reproduce it anymore.

**Comment by kingjia90** [comment]
Probably it got indirectly fixed, it's just small visual one, let's close it
