### ISSUE TITLE
[Bug]: Data component time - reset button

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#13358]
### Expected behavior

Reset all three values when you click the "Reset" button
![image](https://user-images.githubusercontent.com/104770750/195336451-3af979c3-3e89-433c-bbc9-66653cf656bb.png)

### Actual behavior

Nothing happens

### Steps to reproduce

Click on the "Reset" button in the time data component

**Comment by mattamon** [comment]
Hey @robertSt7,

I could reproduce the problem on pimcore version 10.5.7 and I can provide a fix.

The original values of the field are:
Increment Step: 15
min. Value: null
max. Value: null.

On reset I would restore these original values. 

Is that what you would expect?

**Comment by robertSt7** [comment]
@mattamon Hello, yes this is exactly what we need. That would be great if you create a PR for it. Thanks a lot

**Comment by robertSt7** [comment]
closed with #13383
