### ISSUE TITLE
[Improvement]: store a checksum for each asset

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#13362]
### Improvement description

There's value in knowing a checksum of a file, for example you can later have a feature which shows duplicates and allows the user to deduplicate in some way.

It probably makes sense it's MD5 just like `versions.binaryFileHash`, but would work even without versions being enabled. MD5 is also offered by cloud storages (for example, Azure blob storage automatically keeps an MD5 hash), some features in the future could benefit from that overlap, for example, "Check asset health" would go through the assets and check the cloud storage checksum against the one in the database to see they still match.

**Comment by brusch** [comment]
I wouldn't go for a specific hashing algorithm, I'd keep that flexible and just use Flysystem's `$filesystem->checksum('path/to/file.txt');` without a config. 

https://flysystem.thephpleague.com/docs/usage/checksums/

This would have the benefit that you can then use the storages native checksum generation capabilities, as described in the link above. If you want to use a specific checksum, you can anytime change that in your flysystem config. 

I think it also makes sense to provide a command that re-indexes all checksums for all or a filterable subset of assets. 

WDYT?

**Comment by dkarlovi** [comment]
Great suggestions. :+1:
