### ISSUE TITLE
[Bug]: Errorpage not working

### ISSUE THREAD

**Issue by Hcheikhis** [pimcore/pimcore#13366]
### Expected behavior

if the page is not found,  the error page should be rendered.

### Actual behavior

the error page I had configured is not showing up!

### Steps to reproduce

pimcore admin interface -> settings -> system settings -> website -> error page default .
then calling a none existing page.

**Comment by mattamon** [comment]
Which pimcore version are you using?

I tested it on Pimcore 10.5.7 locally and everything works fine.

Could you provide screenshots of your settings and the error page?

**Comment by NiklasBr** [comment]
This might be because of your environment type if all you are seeing is something like this:

![image](https://user-images.githubusercontent.com/279826/195631968-4c0a11a2-d21c-4aae-9e14-747d2f01fb39.png)

[Symfony docs on the subject](https://symfony.com/doc/5.4/controller/error_pages.html):
> In the [development environment](https://symfony.com/doc/5.4/configuration.html#configuration-environments), Symfony catches all the exceptions and displays a special exception page with lots of debug information to help you discover the root problem

Try setting `APP_ENV=prod` in `.env` (might need to restart the environment).

**Comment by Hcheikhis** [comment]
@mattamon actually  am using the same version 10.5.7 
@NiklasBr I already have a prod Env and everything was working fine in both environments dev and prod actually, but suddenly it just stop working !!

![Bildschirmfoto 2022-10-14 um 10 09 52](https://user-images.githubusercontent.com/53570249/195796553-74eb6461-d5e7-4608-8657-54161b87e048.png)

![Bildschirmfoto 2022-10-14 um 10 14 52](https://user-images.githubusercontent.com/53570249/195797434-9a5de0f2-4eb9-4839-bbfd-07895d0afb79.png)

**Comment by brusch** [comment]
Seems your error page is producing an error, check your `prod.log` and also try to access the error page directly and see what happens 😉

**Comment by mattamon** [comment]
I totally agree with brusch. Something must be wrong with the errorPage itself.

**Comment by robertSt7** [comment]
@Hcheikhis Were you able to fix the problem?

**Comment by robertSt7** [comment]
Closed due to inactivity. Feel free to open this issue again, if you have any further information.
