### ISSUE TITLE
[Bug]: ReadOnly layout for Float number classification store key cause javascript exception "Layout run failed"

### ISSUE THREAD

**Issue by luan-bui** [pimcore/pimcore#13377]
### Expected behavior

Class fields (classification store keys) should be shown.

### Actual behavior

Javascript error and fields are not shown

### Steps to reproduce

Using pimcore demo (PIM/MDM):
- Select "PIM" perspective
- Settings -> Data Objects -> Classification Store -> ProductAttributes -> change key definition 'height' from 'Input' to 'Number'. Edit its detail: decimal size: 2, decimal precision: 2 then click 'Apply'
- Settings-> Data Objects -> Classes -> Product Data -> AccessoryPart -> Configure Custom Layouts -> Add new layout called 'ReadOnly'
- Drag the root 'Layout' from Class to Base of Custom Layout
- Select 'Technical Attributes' and check 'Not Editable'
- Save then close Custom Layout Definition dialog
- Open object /Product Data/Accessories/windows/wind screens/austin-healey-3000 mk ii-windscreens
- Tab 'Structured Data' we will see Technical Data with Dimensions group that has 'Height', 'Width' and 'Length'
- Click Reload button and select 'ReadOnly' (which was created before)
- Now 'Dimensions' group will be empty because of javascript error 'Layout run failed' in browser's developer console

**Comment by luan-bui** [comment]
![error-layout-readonly](https://user-images.githubusercontent.com/115776819/195801403-f8ca4663-da55-43cd-9e8a-077be3a2fa03.png)
![layout-master](https://user-images.githubusercontent.com/115776819/195801414-a1ede0fd-27aa-418c-b506-bfbb5e3beb63.png)

**Comment by luan-bui** [comment]
Hello,
  Any news on this issue?

**Comment by brusch** [comment]
@luan-bui PR's are welcome 😉
