### ISSUE TITLE
[Bug]: Preview Of Document File is Not Visible In PIM  DAM UI

### ISSUE THREAD

**Issue by praveenjha2112** [pimcore/pimcore#13374]
### Expected behavior

![image](https://user-images.githubusercontent.com/112381479/195753285-7508eda8-a8cc-4588-85b2-427b25430265.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/112381479/195753375-49f8f9e6-ce04-4695-b682-abc103f3d1e7.png)

### Steps to reproduce

1. Upload  attached file in asset 
2. open it in ui.
[Sis_Thai_Test_Cases_Oct_6_2022_V1.5.xlsx](https://github.com/pimcore/pimcore/files/9782138/Sis_Thai_Test_Cases_Oct_6_2022_V1.5.xlsx)

**Comment by brusch** [comment]
Seems your maintenance/messenger:consume is not running properly, or LibreOffice dependency is missing.
