### ISSUE TITLE
[Improvement]: Add unit select data type

### ISSUE THREAD

**Issue by dlhck** [pimcore/pimcore#13375]
### Improvement description

Sometimes it is necessary to store units without a quantified value. Currently you could use plain inputs or custom select fields with a mapping for that. 
I would like to have a select data type that shows all units that are stored. The getter should return the unit entity not just the abbreviation.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
