### ISSUE TITLE
[Bug]: Building selectbox options takes long time

### ISSUE THREAD

**Issue by CountZero1981** [pimcore/pimcore#13389]
### Expected behavior

Increase in number of options DOESN'T affect UI.

### Actual behavior

Increase in number of options DOES affect UI, greatly increasing UI rendering time.

### Steps to reproduce

Create a DataObject with several lengthy (up to 100 items) selectboxes. Check product rendering time in Google Chrome Developer Tools console. An example on a production server is attached. As shown in the picture, most part of time Pimcore doesn't send any requests to server, simply rendering selectboxes.
![image](https://user-images.githubusercontent.com/4760207/195860922-17ba90dc-7fc2-418a-a197-c6860d12000e.png)

**Comment by brusch** [comment]
Duplicate, see #10468
