### ISSUE TITLE
[Bug]: AbstractListing::addConditionParam overriding previous condition "template"

### ISSUE THREAD

**Issue by jakesde** [pimcore/pimcore#13387]
### Expected behavior

Each `$listing->addConditionParam(...)` should result in the same number of conditions added, regardless of the `condition` argument value. 

### Actual behavior

Internally, the condition added with `$listing->addConditionParam(...)` is stored in the `conditionParams` array **keyed by the condition value** therefore each `$listing->addConditionParam(X, ...)` overrides previous `$listing->addConditionParam(X, ...)` (where `...` are additional parameters which do not affect this behavior)

### Steps to reproduce

Create `Pimcore\Model\DataObject\Listing` , let’s say `$listing`

1. Add 2 conditions with same template condition but different value
   - `$listing->addConditionParam('someTable.some_field = ?', value: 30, concatenator: 'AND')`
   - `$listing->addConditionParam('someTable.some_field = ?', value: 24, concatenator: 'AND')`
2. See that the SQL query and therefore the results only seem to apply the LAST of these 2 conditions added

**Comment by mattamon** [comment]
Can you give an example of real situation where this is needed? 
I don't grasp the idea behind it. For me this is a intended behaviour and more like a user handling error.

What do you expect to happen with these two statements? The value of "someTable.some_field" can not be 30 and 24 at the same time, if you use the AND connector. 

On the other hand you can always use named parameters instead and add more params in one statement.
`$listing->addConditionParam('someTable.some_field = :first AND someTable.some_field = :second', ['first' => 30, 'second' => 24])`

But like I said before, this statement would not work in the first place.

**Comment by mcop1** [comment]
@jakesde Like mattamon said, could you please provide a use case? After that we can see what we can do. Thanks!

**Comment by mcop1** [comment]
Closed due to inactivity. Feel free to open this issue again, if you have any further information.
