### ISSUE TITLE
[Bug]: Search & Move

### ISSUE THREAD

**Issue by EvaStudioEmma** [pimcore/pimcore#13388]
### Expected behavior

When trying to move attributes via the 'search & move' functionality, they should move to the correct folder they have been assigned to.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/106537233/195850292-3183af18-29d6-40c0-a4fe-8b3a708214f5.png">

### Actual behavior

The attributes (AVS-SANY SAFE TANK 10L until AVS-SANY SAFE-XL 2G) move to a different folder (INTRUSION) than the intended folder (which was CARE SOLUTIONS), the wrong folder (INTRUSION) does not get the 'minus' sign to open it, but the file it was assigned to (Care solutions), does get the 'plus' sign to open/collapse the folder. Only when refreshing the parent folder, the attributes are assigned to the right folder (care solutions).

![image](https://user-images.githubusercontent.com/106537233/195851451-09a37b21-75e7-49f9-95be-0c22f112d5d0.png)

### Steps to reproduce

Select a few attributes, which are saved in a parent folder. There are a few subfolders, with no objects yet.
right mouse click -> advanced -> search & move. opt for 'folder' in the dropdown, and opt for an empty subfolder, then click 'select'

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/106537233/195852849-cda136eb-18dd-4760-8dd2-381b3ea67de3.png">

Pimcore version = 10.2.6

**Comment by mcop1** [comment]
Hello @EvaStudioEmma 
sorry, I am not able to reproduce the problem. Could you please try to reproduce the problem within our demo environment -> https://demo.pimcore.fun ? That would be appreciated.

**Comment by mcop1** [comment]
Closed due to inactivity. Feel free to open this issue again, if you have any further information.
