### ISSUE TITLE
[Improvement]: Video Editable droppable to set image poster and video, allowing document/link types

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#13386]
### Improvement description

The idea is to make it possible to drag and drop an image/video to set/replace the video editable: if dragged element is an image, it updates the poster, if is a video it should do the automatically set `type: asset` and the path.
![image](https://user-images.githubusercontent.com/6014195/195838234-aee0c146-cd03-4aa9-baf7-871889c57f06.png)

Also what about allowing the drop of `document/link` type, as long as they are redirecting to something that starts with youtube/dailymotion/vimeo domain?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
