### ISSUE TITLE
[Task]: Checkup column quoting 

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#13392]
### Improvement description

Related to #13373 
Since the replacement of `Pimcore\Db\Connection`, it would be necessary to manually quote these columns.
`insertOrUpdate` is fine because it automatically quotes.

- [x]	range	|	bundle_number_sequence_generator_randomregister
https://github.com/pimcore/number-sequence-generator/issues/9
- [x]	key,index	|	documents https://github.com/pimcore/pimcore/blob/c7f023cf2e349bba8794795f6365447b836c887a/models/Document/Dao.php#L83
https://github.com/pimcore/pimcore/blob/c7f023cf2e349bba8794795f6365447b836c887a/models/Document/Dao.php#L150-L154
- [x]	from,to	|	documents_email
- [x]	from	|	documents_newsletter
- [x]	key	|	ecommerceframework_cartcheckoutdata https://github.com/pimcore/pimcore/pull/13547
- [x]	condition	|	ecommerceframework_pricing_rule #13373 
- [x]	to,from	|	email_log 
https://github.com/pimcore/pimcore/pull/13586
- [x]	read	|	notifications
- [x]	index,column	|	object_metadata_CAR
- [x]	index	|	object_relations_BS https://github.com/pimcore/pimcore/blob/c7f023cf2e349bba8794795f6365447b836c887a/models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php#L121
- [x]	numeric	|	object_store_6 
- [x]	select,table	|	object_store_7 https://github.com/pimcore/pimcore/blob/c7f023cf2e349bba8794795f6365447b836c887a/models/DataObject/Concrete/Dao.php#L291-L295
- [x] custom field like 'condition' | object_brick_store_SaleInformation_AP
https://github.com/pimcore/pimcore/pull/13585
- [x]	index	|	object_url_slugs
https://github.com/pimcore/pimcore/issues/13435
- [x]	trigger,condition	|	plugin_cmf_actiontrigger_rules
https://github.com/pimcore/customer-data-framework/pull/345
- [x]	key	|	plugin_cmf_activities_metadata
https://github.com/pimcore/customer-data-framework/pull/345
- [x]	delete,create,read,update	|	plugin_datahub_workspaces_x
https://github.com/pimcore/data-hub/issues/619
- [x]	group	|	quantityvalue_units
- [x]	key,index	|	search_backend_data
- [x]	key	|	translations_admin
- [x]	key	|	translations_messages
- [x]	key	|	users_permission_definitions https://github.com/pimcore/pimcore/blob/c7f023cf2e349bba8794795f6365447b836c887a/models/User/Permission/Definition/Dao.php#L32
- [x]	create,rename,delete	|	users_workspaces_x
https://github.com/pimcore/pimcore/blob/c7f023cf2e349bba8794795f6365447b836c887a/models/User/Workspace/Dao.php#L53

I've used the following query to get those: 
```
SELECT GROUP_CONCAT(`COLUMN_NAME`), TABLE_NAME
FROM `INFORMATION_SCHEMA`.`COLUMNS`
WHERE TABLE_SCHEMA = 'pimcore' AND UPPER(COLUMN_NAME) IN (           
 'ACCESSIBLE',
'ADD',
....
'YEAR_MONTH',
'ZEROFILL'
)
GROUP BY TABLE_NAME ORDER BY TABLE_NAME, COLUMN_NAME
````
copying the fields from https://github.com/doctrine/dbal/blob/a24b89d663d8f261199bc0a91c48016042ebda85/src/Platforms/Keywords/MariaDBKeywords.php#L24

**Comment by kingjia90** [comment]
Just wanted to add a note that if https://github.com/pimcore/pimcore/pull/13613 gets merged, whenever we replace `insertOrUpdate` with `upsert` (which at the current state, it is without the quotation of the column identifiers) then it would require quoting too.

**Comment by jdreesen** [comment]
This doesn't seem to be completed yet.

**Comment by aryaantony92** [comment]
@jdreesen Thanks! I think it closed automatically when I merged the PR. I have reopened it.

**Comment by jdreesen** [comment]
It's those `Partially resolves #...` messages, where GitHub only sees `resolves #...` and closes the issue xD
