### ISSUE TITLE
[Feature]: Import/Export QuantityValueUnitDefinition

### ISSUE THREAD

**Issue by prunepal333** [pimcore/pimcore#13401]
### Feature description

Since, quantity value unit definition is stored in the db table `quantityvalue_units`. I couldn't find a way around to transport the definition from one system to another (local server -- development server -- test server -- production 
server) without sharing database table. It would be nice to integrate them as a command like in deployment tools

```./bin/console pimcore:definition:import:quantityvalue_units ./quantityvalue_units.json```

```./bin/console pimcore:definition:export:quantityvalue_units ./quantityvalue_units.json```

**Comment by prunepal333** [comment]
I have a working solution for this, Why do I think, it's important is,
because the amount of time we are spending re-creating the same stuff over
multiple servers(dev, staging, uat, production) which brings
inconsistencies and intimidating to repeat for large collections. I would
like to contribute and create a pull request if pimcore thinks it's nice to
have feature.

**Comment by mcop1** [comment]
Hello @prunepal333 ,
no problem, you can create a pr based on the 11.x branch (since it is a new feature). Every pr is highly appreciated.
