### ISSUE TITLE
ConsoleParallelization update

### ISSUE THREAD

**Issue by theofidry** [pimcore/pimcore#13412]
### Feature description

Hi there, just a heads up.

The ConsoleParallelization package was left a bit unattended mostly due to lack of time but especially because of maintainability issues. The code was very hard to work with in the sense that it was a nightmare to test and had close to no tests.

I've actively worked on the 2.x version on the past few weeks which addresses that and should make working on that codebase easy. There is a few things left to do such as adding a better BC layer and a few tiny TODOs left, but you can expect it to be ready in a few weeks.

That being said, I still think it makes more sense for it to be an opt-in feature so I am not suggesting in any way to make the package required again.

/cc @dvesh3 @brusch

**Comment by brusch** [comment]
@theofidry thanks for the info! We'll then consider v2 for our v11 milestone 🤗

**Comment by theofidry** [comment]
@brusch I've tagged a new beta for v2. On my side everything is ready for tagging a stable release, but maybe you want to have a little check see if there is anything you're not happy with that would need to be fixed before that.

**Comment by brusch** [comment]
@theofidry thank you very much for your info, we bumped already to the v2-beta a couple of days ago 😊
See: https://github.com/pimcore/pimcore/pull/13480

We'll update `composer.json` again as soon as you have tagged the final release 😊

**Comment by theofidry** [comment]
Added a few notes in #13480. I'll be closing this issue otherwise as 2.0.0 has been tagged already
