### ISSUE TITLE
[Bug]: Objectbrick definition update fails when changing field of type text to type textarea

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#13436]
### Expected behavior

Save of objectbrick field definition to succeed.

### Actual behavior

Save fails with MySQL error resulting in the following exception:
`An exception occurred while executing 'ALTER TABLE `object_brick_query_catalog_product_description_1` CHANGE COLUMN `fieldValue` `fieldValue` longtext NULL;':
SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'fieldValue' used in key specification without a key length.`
![image](https://user-images.githubusercontent.com/11477130/197297026-747a834b-27bc-4c3a-8831-c743312cbbdf.png)

### Steps to reproduce

From admin panel:
- Create Class definition with objectbrick field.
- Create object brick definition with 1 text field linked to the class and save it.
- Change the type of the objectbrick field from text to textarea and save.
The exception occurs.
This same fieldtype change scenario works as expected when done in class definition but fails when done to objectbrick definition.
If we create the objectbrick field with type textarea the first time than the save works as expected as there is no such index. It seems that the index created for the text type field is not being dropped before changing the column type in MySQL.

**Comment by mcop1** [comment]
Hello @kanevbg ,
sorry I wasn´t able to reproduce the problem- which pimcore version are you using? Could you please try to reproduce the issue in our demo (https://demo.pimcore.fun)?

**Comment by kanevbg** [comment]
@mcop1 in a hour or two I will postback info.

**Comment by kanevbg** [comment]
It's Pimcore Version: v10.5.8.
I understood that there were one more condition in order for the issue to occur in my environment. There should be at least one object with the class using the brick in order for the Pimcore to create the table which has problematic index. So in order to reproduce it is very important to create object with the brick while the brick is configured to have indexed text field. After the object is stored for first time the table will be created with column index for the text field. Than saving the brick definition will fail when the text field is changed to textarea.
However I was unable to reproduce it on the demo. I saw that the demo uses MariaDB.
In my the DBMS is Percona MySQL (ver. 8.0.28-19).
It maybe that Percona MySQL 8 is not supporting that query:

> ALTER TABLE `object_brick_query_test2_1` CHANGE COLUMN `fieldValue` `fieldValue` longtext NULL;

> BLOB/TEXT column 'fieldValue' used in key specification without a key length

while MariaDB does thus cannot be reproduced on the demo?

PS: https://stackoverflow.com/a/1827099

**Comment by mcop1** [comment]
@kanevbg Good catch, we execute the `alter table` statement first, after that we drop the indexes (and recreate them if necessary). Think we should drop the indexes first, change the column and recreate the indexes at last. 

TextAreas can´t be indexed anyways, the according option is disabled.
![grafik](https://user-images.githubusercontent.com/89011527/197770318-0925d2d1-1057-4199-9cdb-b28891f27e12.png)

**Comment by kanevbg** [comment]
Yep

**Comment by dvesh3** [comment]
Fixed by #13538
