### ISSUE TITLE
[Bug]: Visible fields on many-to-many object relations are not shown.

### ISSUE THREAD

**Issue by jacobsyentl** [pimcore/pimcore#13439]
### Expected behavior

When enabling visible fields on a many-to-many object relation. The visible fields should be shown on the object:
<img width="506" alt="image" src="https://user-images.githubusercontent.com/9139261/197483175-dc0a4c30-de94-4f91-8bfe-34d68aa4b299.png">

### Actual behavior

**Only two of the selected visible fields are shown properly:**

<img width="1534" alt="image" src="https://user-images.githubusercontent.com/9139261/197483318-3398d878-0538-49d6-bc95-962a8924b20d.png">

### Steps to reproduce

1. Add many-to-many object relation
2. Select multiple visible fields ( incl. image & boolean select fields)
3. Assign objects on the relation & check the visible fields.

**Comment by jacobsyentl** [comment]
This issue is possible related to: https://github.com/pimcore/pimcore/pull/8141

**Comment by mcop1** [comment]
Hello @jacobsyentl,
I tried to reproduce the problem, but it seems fine for me:
![grafik](https://user-images.githubusercontent.com/89011527/199964263-cdf7c27a-b72c-4a55-9c94-6216a754cf9c.png)

Could you please export your class definition and attach as zip file in your comment?

**Comment by kjkooistra-youwe** [comment]
@mcop1 You can find class definition files in this similar issue: https://github.com/pimcore/pimcore/issues/13489

**Comment by mcop1** [comment]
@kjkooistra-youwe sorry, I must have missed them. I can reproduce the error with your class definitions, we will have a look into it, thanks!

**Comment by mcop1** [comment]
@kjkooistra-youwe I found a problem with calculatedValues, could you please have a look at the linked pr, does this solve your problem?

**Comment by kjkooistra-youwe** [comment]
@mcop1 That does indeed solve the problem. Thanks.
