### ISSUE TITLE
[Bug]: relations editable in editable dialog box for brick can not be overwritten with inheritance

### ISSUE THREAD

**Issue by aweichler** [pimcore/pimcore#13431]
### Expected behavior

I have a simple test brick with one "relations" editable in editable dialog box.
I created a English page, add the brick and add an data object to the relations editable.
Then I copied the English page with inheritance to german language. When I add an other data object to the relation editable in the german version (click override at the brick), save an reload, there are 2 data objects in the relations editable.

### Actual behavior

After overriding the brick in the German language an add an other data object, I save the page, reload it and then the relations editable only shows the data object from the English page. The newly added data object is not there.
With inheritance it is not possible to override a relations editable in the editable dialog box.
Without inheritance all works fine.

### Steps to reproduce

You can use the brick from the [zip](https://github.com/pimcore/pimcore/files/9836263/pimcore-test.zip) file.

I am on Pimcore 10.5.8.

**Comment by hallekamp** [comment]
Steps to use the fix prior to being merged:

- copy `vendor/pimcore/pimcore/bundles/AdminBundle/Resources/public/js/pimcore/document/editables/area_abstract.js` to `public/`
- add the missing line
- override `\Pimcore\Bundle\CoreBundle\EventListener\Frontend\EditmodeListener` and replace `/bundles/pimcoreadmin/js/pimcore/document/editables/area_abstract.js` with the path to your modified version (see https://symfony.com/doc/current/service_container/service_decoration.html)

or just add the line to  `vendor/pimcore/pimcore/bundles/AdminBundle/Resources/public/js/pimcore/document/editables/area_abstract.js` for a quick test, but any update will revert it

**Comment by aryaantony92** [comment]
@hallekamp Thank you, will check it

**Comment by aryaantony92** [comment]
Fixed by #13533
