### ISSUE TITLE
CJPEG not recognized / wrong ch

### ISSUE THREAD

**Issue by smaier** [pimcore/pimcore#1343]
### Expected behavior 
  cjpeg checked in the system-requirements tab / cjep beeing used  
### Actual behavior  
  cjpeg is not checked / will not be executed
### Steps to reproduce  
  log in to admin-backend
### Code example 
  in Pimcore\Tool\Console
  function checkCjpeg => checks output of cjpeg --h for "mozjpeg"
 Version on [Pimcore Documentation](https://www.pimcore.org/docs/latest/Installation_and_Upgrade/System_Setup_and_Hosting/Additional_Tools_Installation.html) does not work

My question: should we remove the check for "mozjpeg" in cjpeg? As far as i see "mozjpeg" is not even used in Pimcore\Image\Optimizer::optimizeCjpeg($path) ?
Solution 1) change Lib to mozjpeg
Solution 2) "fix" the checkCjpeg Method

im not quite sure which is the right way especially in combination of all the other optimize methods

**Comment by brusch** [comment]
`Pimcore\Image\Optimizer::optimizeCjpeg()` is used here (it's a dynamic call): 
https://github.com/pimcore/pimcore/blob/d8d539516d20fc0150b005afbfa7834796c729b3/pimcore/lib/Pimcore/Image/Optimizer.php#L46-L46

I've just downloaded `https://github.com/imagemin/mozjpeg-bin/raw/master/vendor/linux/cjpeg`
and the help message includes the keyword `mozjpeg` so the check is correct and works as expected. 

Please ensure you have installed mozjpeg properly and the MozJPEG's version of cjpeg is correctly in place.

**Comment by smaier** [comment]
Thanks for your reply. Seems to be an OS-Issue - if we use the version u linked i get error-messages in the cli:
`./cjpeg: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory`
i hope there is a "mozjpeg" version of cjpeg for our distribution. Regards, Stefan

**Comment by brusch** [comment]
Just use a static binary, such as: 
https://github.com/imagemin/mozjpeg-bin/tree/master/vendor/linux 
it works on every distribution without dependencies and you can put this anywhere, even within your project folder. Don't forget to permission it properly, eg. `chmod 0744 ./cjpeg`

**Comment by bbak** [comment]
There's another reason, why the check fails: for whatever reason cjpeg ( from Debian 9 Package: [libjepeg-turbo-progs](https://packages.debian.org/stretch/libjpeg-turbo-progs) ) returns `(int) 1` as exit code when called with `--help`, `-h` or `-help`; see [here](https://helpmanual.io/help/cjpeg/). Therefore `$process->isSuccessful()` in `Pimcore\Tool\Console` Line 112 always returns `false`. 

Therefore `pimcore.executable.cjpeg` has to be set in `di.php` to override autodetection when using `cjpeg`.
