### ISSUE TITLE
[Task]: Remove unused `index` column in `object_url_slugs` table 

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#13435]
### Improvement description

~I am suspecting that~ `index` column in table `object_url_slugs`  is not used at all and always `0`, and therefore could be removed. 
The column which is used is called `position`, likely because `index` as int field couldn't store the country code or so.

![image](https://user-images.githubusercontent.com/6014195/197211279-23fe77fc-12d3-45e4-89a9-970d5d6bc1fe.png)

So far is not causing any troubles, found this issue when checking if it needs to be quoted.

**Comment by NiklasBr** [comment]
All slugs use `index=0` here at least.

![image](https://user-images.githubusercontent.com/279826/197217380-49cc808e-b9ec-4612-b165-0e0b1c3dd9f8.png)
![image](https://user-images.githubusercontent.com/279826/197217433-1720d873-b05e-482d-b428-0a237254aa21.png)
