### ISSUE TITLE
Newsletter Test-Send fails when address source is empty

### ISSUE THREAD

**Issue by LosHawlos** [pimcore/pimcore#1344]
We use different custom reports as address souce for newsletter sendouts.
One of these reports did not select any recipient.
When now using this report to start a test send, it fails without showing any feedback to the user.

The ajax call returns an error:
> Fatal error: Uncaught TypeError: Argument 2 passed to Pimcore\Document\Newsletter\SendingParamContainer::__construct() must be of the type array, boolean given, called in /public/pimcore/lib/Pimcore/Document/Newsletter/AddressSourceAdapter/ReportAdapter.php on line 114 and defined in /public/pimcore/lib/Pimcore/Document/Newsletter/SendingParamContainer.php on line 35
> TypeError: Argument 2 passed to Pimcore\Document\Newsletter\SendingParamContainer::__construct() must be of the type array, boolean given, called in /public/pimcore/lib/Pimcore/Document/Newsletter/AddressSourceAdapter/ReportAdapter.php on line 114 in /public/pimcore/lib/Pimcore/Document/Newsletter/SendingParamContainer.php on line 35

**Comment by dvesh3** [comment]
Hello @LosHawlos , Could you please share steps to reproduce this? Thanks!

**Comment by LosHawlos** [comment]
Hi, this is an old bug that was present a year ago in Pimcore 4 (probably 4.4.1).

To reproduce:
- Create a custom report to select the recipients, but have it actually not select any rows.
For example:
SELECT name, email FROM users WHERE id=0 and id=1
- In the newsletter document select this report as address source
- Then do a newsletter test sending.
=> In Pimcore 4 no email was sent, and no feedback was given to the user (no error message).

I have reproduced this in Pimcore 5.2.1
=> No email is sent, but now the user at least sees the error popup showing an exception:
Status: 500 | Internal Server Error
URL: /admin/newsletter/send-test
Method: post
Message: Type error: Argument 2 passed to Pimcore\Document\Newsletter\SendingParamContainer::__construct() must be of the type array or null, boolean given, called in /.../pimcore/lib/Pimcore/Document/Newsletter/AddressSourceAdapter/ReportAdapter.php on line 111

**Comment by dvesh3** [comment]
@LosHawlos Thanks for info!
