### ISSUE TITLE
[Bug]: UI message "Server threw exception" but server actually did not

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#13440]
### Expected behavior

Error messages should be as correct as possible.

I suggest the error message is reformulated so that it only says that it is the server which threw an exception if the server actually threw an exception and not on something like a timeout or communication failure.

### Actual behavior

The message _"Server threw exception - could not perform action. Please reload the admin interface and try again."_ appears very often when doing anything which takes more than a few seconds. For example saving an object with computationally complex EventListeners, or just logging in after a deploy.

### Steps to reproduce

Easiest I think is in a `dev` type environment where caches are often invalidated.  You could also just add a `sleep(15)` to a controller.

**Comment by aryaantony92** [comment]
Fixed by #13506
