### ISSUE TITLE
[Bug]: Unable to unserialize snippets in areabricks created in Pimcore 6

### ISSUE THREAD

**Issue by alexej-d** [pimcore/pimcore#13454]
### Expected behavior

Successfully open a document in admin UI after updating from P6 to P10.

### Actual behavior

Opening some documents throws an error:
```
Message: Cannot assign string to property Pimcore\Model\Document\Editable\Snippet::$id of type ?int
Trace: 
in /project/vendor/pimcore/pimcore/lib/Tool/Serialize.php:43
#0 /project/vendor/pimcore/pimcore/lib/Tool/Serialize.php(43): unserialize('O:27:"Pimcore\\M...')
#1 /project/vendor/pimcore/pimcore/models/Version.php(371): Pimcore\Tool\Serialize::unserialize('O:27:"Pimcore\\M...')
#2 /project/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php(287): Pimcore\Model\Version->loadData()
#3 /project/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/PageController.php(102): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\DocumentControllerBase->getLatestVersion(Object(Pimcore\Model\Document\Page), NULL)
#4 /project/vendor/symfony/http-kernel/HttpKernel.php(153): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\PageController->getDataByIdAction(Object(Symfony\Component\HttpFoundation\Request), Object(Pimcore\Document\StaticPageGenerator))
#5 /project/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#6 /project/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /project/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
```

### Steps to reproduce

It looks like some snippet editables serialized the snippet IDs as strings to the version storage. Removing the `?int` from the $id prop on the `Pimcore\Model\Document\Editable\Snippet` class fixes the error.

**Comment by brusch** [comment]
It's a known issue that version data is not always 100% compatible between major versions, that's why we need to think of a different and more flexible serializer in the future (JSON, ...). 

See also: #8257

**Comment by alexej-d** [comment]
@brusch I am fine with old versions not working, but it is a pretty severe bug not being able to edit the current version of a document… Any idea what to do apart from editing the Snippet class?

**Comment by brusch** [comment]
@alexej-d seems there's a newer not published version in your case, that's why the version is loaded (see `#1` in your stack trace). Probably it would be best to just kick all versions containing snippet data with a simple SQL query from the `versions` table.
