### ISSUE TITLE
[Feature]: PHP API and UI for control of which classes, objectbricks and others file-defined structures to be gitignored

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#13458]
### Feature description

Pimcore is unique, extremely powerful system. By default it's accepted that classes, objectbricks, fieldcollections (etc) are manually generated and thus they should enter git. However if one do generate objectbricks or class definitions dynamically , he has no API to instruct the system to gitignore specific definitions. Depending on the use case a custom workaround can be implemented, however I see that as powerful devops feature very well suited to be part of pimcore. So I propose to add checkbocks to each type of definition in the UI (and provide PHP API) to mark it "Add in .gitignore". I can add thumbnail definitions to the list too.
This allows you from the PHP API to dynamically generate definitions depending on the environment and do not propagate to the git project.

**Comment by brusch** [comment]
To be honest, I don't like the idea of changing the `.gitignore` automatically for several reasons. 
I'd suggest to use different directories for that, which is already possible now: 

Class definitions added to VCS are stored in: `config/pimcore/classes` 
while ignored definitions are saved in excluded `var/classes`. 

This works out of the box.

**Comment by kanevbg** [comment]
Does the pimcore system automatically starts to read the classes from config/pimcore/classes or I have to do something? I moved classes from var/classes to config/pimcore/classes but they are were not used.

**Comment by brusch** [comment]
@kanevbg this should work automatically ... 🤔
