### ISSUE TITLE
Fix Restricting_Public_Asset_Access Docs

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#13469]
## Issue
Pimcore\Tool\Storage is marked as Internal so [code sample](https://github.com/kaurov/pimcore/blob/6631184a72cdc93069cf3bf57afcb5b0d337fdb4/doc/Development_Documentation/04_Assets/07_Restricting_Public_Asset_Access.md?plain=1#L157) is outdated. 

## Solution
Add a helper service (e.g. `Asset\Service::getThumbnailByUri()`) to get thumbnail storage stream and update the code sample in docs.

**Comment by brusch** [comment]
Related to #13468

**Comment by aashan10** [comment]
Fixed by #14155
