### ISSUE TITLE
[Bug]: JS-files from disabled bundles are loaded

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#13463]
### Expected behavior

Bundles are loaded in the order in which they are mentioned in bundles.php

### Actual behavior

JS-files are loaded in a different order

### Steps to reproduce

Install data-hub and data-hub-simple-rest

**Comment by dvesh3** [comment]
@robertSt7 Data hub simple-rest bundle registers dependent Datahub bundle with higher priority [here](https://github.com/pimcore/data-hub-simple-rest/blob/2bea3205e9acd9f5cbc9def34282cfc4f7613adc/src/PimcoreDataHubSimpleRestBundle.php#L55) so it will be always be loaded before.

I even tried to reproduce the problem with wrong order however it still works:
![image](https://user-images.githubusercontent.com/5137917/199035118-3dd68fe6-df67-4d91-a080-c604b6745a9c.png)
![image](https://user-images.githubusercontent.com/5137917/199035264-2336a9d2-1c43-4dde-8819-c47f1aa4014c.png)

**Comment by robertSt7** [comment]
> @robertSt7 Data hub simple-rest bundle registers dependent Datahub bundle with higher priority [here](https://github.com/pimcore/data-hub-simple-rest/blob/2bea3205e9acd9f5cbc9def34282cfc4f7613adc/src/PimcoreDataHubSimpleRestBundle.php#L55) so it will be always be loaded before.
> 
> I even tried to reproduce the problem with wrong order however it still works: ![image](https://user-images.githubusercontent.com/5137917/199035118-3dd68fe6-df67-4d91-a080-c604b6745a9c.png) ![image](https://user-images.githubusercontent.com/5137917/199035264-2336a9d2-1c43-4dde-8819-c47f1aa4014c.png)

@dvesh3 It looks like that there is a problem with the symlinks from the assets. The following command should fix it: `php bin/console assets:install public --symlink --relative`

**Comment by dvesh3** [comment]
I still can't reproduce the problem, so for me public files are not loaded for disabled bundles:
![image](https://user-images.githubusercontent.com/5137917/199768681-7f4a467e-29de-47e6-9a24-068264e9fee5.png)

![image](https://user-images.githubusercontent.com/5137917/199762841-250c8a7c-0368-4976-b820-99d377efb98f.png)

**Comment by robertSt7** [comment]
see https://github.com/pimcore/demo-enterprise/pull/66/files#r1014010629
