### ISSUE TITLE
[Bug]: grid CSV export extremely slow

### ISSUE THREAD

**Issue by kjkooistra-youwe** [pimcore/pimcore#13467]
### Expected behavior

CSV export in the grid should be done in a few seconds.

### Actual behavior

When exporting 100,000 items it can last up to an hour. Even when exporting very basic data.

### Steps to reproduce

Reproduced on the [demo environment](https://demo.pimcore.com/admin/).

- Create a basic test class containing a name field ([class_Test_export.json.zip](https://github.com/pimcore/pimcore/files/9878704/class_Test_export.json.zip)).
- Import 30,000 records (I used DataHub) ([30000_records.csv](https://github.com/pimcore/pimcore/files/9878987/30000_records.csv)).
- Open the folder you imported the items into.
- Limit the grid to id and name columns (if not already).
- Run the CSV Export.

In my case it lasted 7 minutes for the export to finish.

For comparison:
- Create a new custom report with these settings.
  - SELECT: o_id,name
  - FROM: object_test
- Open the report.
- Run the CSV Export.

The export is finished in mere seconds.

**Comment by SamyMP** [comment]
Hi @dvesh3,

Is this still PR welcomed ? I have worked a bit on something that could help with that, but I have to know if that's going to be accepted or not, and if it is not already being reworked by one of the core members. 

Basically, I am using the `Pimcore\Db::getConnection()` and Doctrine query builder to be able to retrieve large amount of data directly from database as it is way faster than using the DataObject Listing offered by Pimcore objects. I believe that is what `CustomReportController` is doing, although they use `Tool\Config::getAdapter($configuration, $config);` which is deprecated. 

Obviously, there would be a lot left to do. I believe the main problem in this issue comes from the fact that transformers can be used to alter data on the grid, and we would have to implement a SQL query that matches what the transformer does so that the export can be as the user sees it on the grid, but it's not impossible. 

What are your thoughts ?

Here's the code if you want to have an idea : 

```php
/**
 * @Route("/get-export-jobs", name="getexportjobs", methods={"POST"})
 *
 * @param Request $request
 * @param GridHelperService $gridHelperService
 * @param EventDispatcherInterface $eventDispatcher
 *
 * @return JsonResponse
 */
public function getExportJobsAction(Request $request, GridHelperService $gridHelperService, EventDispatcherInterface $eventDispatcher): JsonResponse
{
    $db = Db::getConnection();
    $tableName = 'object_query_' . $request->get('classId');
    $tempfields = $request->get('fields');
    $fields = [];

    $schemaManager = $db->createSchemaManager();

    $columnsDataobject = $schemaManager->listTableColumns($tableName);
    $columnsObjects = $schemaManager->listTableColumns('objects');
    $columnsSBD = $schemaManager->listTableColumns('search_backend_data');

    if ($request->get('query')) {
        // Handle what the user has typed in the search bar
    }

    foreach ($tempfields as $field) {
        if (in_array(strtolower($field), array_keys($columnsDataobject))) {
            $fields[] = $tableName . '.' . $field;
        } elseif (in_array(strtolower($field), array_keys($columnsObjects))) {
            $fields[] = 'objects.' . $field;
        } elseif (in_array(strtolower($field), array_keys($columnsSBD))) {
            $fields[] = 'sbd.' . $field;
        }
    }

    $querybuilder = $db->createQueryBuilder();
    $querybuilder->select(join(',', $fields));
    $querybuilder->from('objects');
    $querybuilder->join('objects', $tableName, $tableName, $tableName . '.oo_id = objects.id');
    $querybuilder->join('objects', 'search_backend_data', 'sbd', 'sbd.maintype = objects.type and sbd.id = objects.id');

    $sqlResult = $querybuilder->executeQuery();
    $data = $sqlResult->fetchAllAssociative();
    $count = $sqlResult->rowCount();

    $exportFile = PIMCORE_SYSTEM_TEMP_DIRECTORY . '/report-export-' . uniqid() . '.csv';
    @unlink($exportFile);

    $fp = fopen($exportFile, 'a');

    fputcsv($fp, $tempfields, ';');

    foreach ($data as $row) {
        $row = Service::escapeCsvRecord($row);
        fputcsv($fp, array_values($row), $request->get('delimiter', ';'));
    }

    fclose($fp);

    $offset = $request->get('offset', 0);
    $limit = 5000;

    $progress = $count ? ($offset * $limit) / $count : 1;
    $progress = $progress > 1 ? 1 : $progress;

    return new JsonResponse([
        'exportFile' => basename($exportFile),
        'offset' => $offset,
        'progress' => $progress,
        'finished' => empty($data) || count($data) < $limit,
    ]);
}

/**
 * @Route("/download-export-jobs", name="download-export-jobs", methods={"GET"})
 *
 *
 */
public function downloadCsvAction(Request $request): BinaryFileResponse
{
    if ($exportFile = $request->get('exportFile')) {

        $response = new BinaryFileResponse(PIMCORE_SYSTEM_TEMP_DIRECTORY . '/' . $exportFile);
        $response->headers->set('Content-Type', 'text/csv; charset=UTF-8');
        $response->setContentDisposition(ResponseHeaderBag::DISPOSITION_ATTACHMENT, 'export.csv');
        $response->deleteFileAfterSend(true);

        return $response;
    }

    throw new FileNotFoundException("File \"$exportFile\" not found!");
}
```

**Comment by fashxp** [comment]
There will be a sightly different (and hopefully much faster) approach for studio. 
But it cannot be compared to a static report export, as for the CSV export in the grid we need to load the data objects - which results it much more operations than just a simple SELECT statement.
