### ISSUE TITLE
[Bug]: A string and int operation problem in Video Editable error return html code

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#13472]
### Expected behavior

Using css [calc](https://developer.mozilla.org/en-US/docs/Web/CSS/calc) for `%` and `px` values and consistency between `width` and `height`.

### Actual behavior

https://github.com/pimcore/pimcore/blob/c07e8ab75a89c859e4ea1bbbb9a6174bd9cd6fc9/models/Document/Editable/Video.php#L557-L559

`($this->getHeight() - 1)` in this line
https://github.com/pimcore/pimcore/blob/c07e8ab75a89c859e4ea1bbbb9a6174bd9cd6fc9/models/Document/Editable/Video.php#L568

### Steps to reproduce

I don't remember how i end up to see it, just had some problems with video editable and thumbnails. 
The height value was set to be `auto` somehow and with the `-1` in php caused a fatal error.

**Comment by aryaantony92** [comment]
Fixed by #13511
