### ISSUE TITLE
"Call to a member function getFielddefinitions() on boolean"

### ISSUE THREAD

**Issue by kylepwarren** [pimcore/pimcore#1347]
### Steps to reproduce  
1) copy database and files to another environment (eg dev to production)  
2) click a folder to load object grid

related groups thread: https://groups.google.com/d/msg/pimcore/VBTEAltJsqc/1W5Eg_iaEgAJ

**Comment by bbak** [comment]
@kylepwarren Question: Did the Database-User (`pimcore_user`@`hostname_or_ip`) change? In this case, you have to change the DEFINER clause of the VIEW Definitions in the SQL Dump to match the "new" User before reimporting.

**Comment by kylepwarren** [comment]
They were the same, but the destination mysql server had, "skip-grant-tables". I tried disabling that config, and making sure the DEFINER clauses looked good. 

The views I have with ONLY class/object attributes seem fine - load fine the first time after the file&db transfer. 

the views/grids with columns from object **bricks** do NOT. Plan to(for now) use a script to re-save all the object bricks.
