### ISSUE TITLE
[Bug]: Unable to remove  shortcut add button  from many to many object relation field

### ISSUE THREAD

**Issue by praveenjha2112** [pimcore/pimcore#13495]
### Expected behavior

![image](https://user-images.githubusercontent.com/112381479/199309959-bffcb7cf-1e01-4b37-9517-563bc7ad6416.png)
![image](https://user-images.githubusercontent.com/112381479/199310486-d64a4e1e-e0a5-4e12-96de-dfc1df305073.png)

If we add a many to many object relation field in class It should display  checkbox for  shortcut object create button

### Actual behavior

But its not showing if I  add many to many object relation field in class
![image](https://user-images.githubusercontent.com/112381479/199310403-c26e588c-1eb8-4ffb-9be2-9ef46b9cefb0.png)

### Steps to reproduce

1. Create Field Collection 
2. Add a many to many object relation

**Comment by mattamon** [comment]
@praveenjha2112 I am a little confused. The title of your issue, is not at all what I was expecting.

What exactly do you mean?

When creating a field collection and adding a Many-To-Many-Object Relation, the checkbox "Allow to create a new object in relation field" is not shown, when it should, correct?

**Comment by praveenjha2112** [comment]
> @praveenjha2112 I am a little confused. The title of your issue, is not at all what I was expecting.
> 
> What exactly do you mean?
> 
> When creating a field collection and adding a Many-To-Many-Object Relation, the checkbox "Allow to create a new object in relation field" is not shown, when it should, correct?

yes

**Comment by mattamon** [comment]
The checkbox will only be shown in a class and is checked by default for field collections.
https://github.com/pimcore/pimcore/blob/10.5/bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToManyObjectRelation.js#L193

@fashxp is there a specific reason why the option "allowToCreateNewObject" is only shown in class or can we move this option to the outside scope?

**Comment by robertSt7** [comment]
@mattamon There is no specific reason for showing the option "allowToCreateNewObject" only in classes. Could you please provide a PR for moving this option to the outside scope? Thank you

**Comment by robertSt7** [comment]
solved by #13544
