### ISSUE TITLE
Upgrading from php 5.4

### ISSUE THREAD

**Issue by AndreasFurster** [pimcore/pimcore#1350]
Hi,

We have a server running on php 5.4 with a lot of pimcore installations. Some are still running Pimcore 2. (Maybe even pimcore 1).

So we can't run pimcore 4 since it requires at least php 5.6. Now we want to upgrade to 5.6 or 7. Would this result in errors in the old installations? Can they all run on 5.6 (or even 7)?

Kind regards,
Andreas Furster

**Comment by solverat** [comment]
jop, pimcore runs smoothly on php 5.6 or 7.0.

**Comment by Pegasuz** [comment]
We already use php 7.1 in production. Everything works nicely.

**Comment by AndreasFurster** [comment]
Yeah, but also for old versions of pimcore like v1?

**Comment by solverat** [comment]
since php 5.6 has been released in aug 2014 and php7 somewhere in 2015 and pimcore 1.x [between 2010 and 2013](https://www.pimcore.org/docs/latest/Installation_and_Upgrade/Version_History.html) i guess you're out of luck. pimcore 2.x is probably not ready too.

**Comment by brusch** [comment]
Please use our Google Group for these kind of questions - thank you. 

To answer your question: we don't test EOL versions of Pimcore against current PHP Versions, so we cannot guarantee that they work properly, but normally there shouldn't be any issues - not that we know of.
