### ISSUE TITLE
[Bug]: "Publish" in document context menu published wrong version

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#13500]
### Expected behavior

The saved version will be published

### Actual behavior

A old version will be published

### Steps to reproduce

- Go to pimcore demo
- Unpublish document (for example /en/Events)
- Change title
- Click "Save" button
- Close document tab
- "Publish" over the tree context menu
- Open document -> Wrong title

**Comment by blankse** [comment]
[Issue-13500.webm](https://user-images.githubusercontent.com/998558/199528810-3fbd7eb7-be33-46bb-86de-3e6c3f3dae6a.webm)

**Comment by dvesh3** [comment]
Fixed by #13504
