### ISSUE TITLE
[Bug]: ParamConverter returns an empty object

### ISSUE THREAD

**Issue by dvelguru** [pimcore/pimcore#13510]
### Expected behavior

```
public function defaultAction(DataObject\Family $family): Response
{
    dd($family);
}
```

<img width="384" alt="Bildschirm­foto 2022-11-03 um 13 49 52" src="https://user-images.githubusercontent.com/3622712/199724837-6f3d41f7-049e-4e21-bafc-fae9681d9b94.png">

### Actual behavior

<img width="371" alt="Bildschirm­foto 2022-11-03 um 13 50 36" src="https://user-images.githubusercontent.com/3622712/199724964-975e1667-0725-4233-9859-33358958fad6.png">

### Steps to reproduce

In Pimcore Admin, create a simple static route with `id` as a variable pointing to demo controller.

Configure a defaultAction method inside of the demo controller. (Annotations are unnecessary)
```
public function defaultAction(DataObject\Family $family): Response
{
    dd($family);
}
```

As depicted in documentation, the parameter `id` inside of the request will be converted to an object.
[
<img width="796" alt="Bildschirm­foto 2022-11-03 um 14 01 33" src="https://user-images.githubusercontent.com/3622712/199727296-e11de983-5626-470c-9c32-1a8535ce64b4.png">](https://pimcore.com/docs/pimcore/current/Development_Documentation/MVC/Routing_and_URLs/Custom_Routes.html#page_Using-Param-Converter-to-convert-request-ID-to-Data-Object)

### The Cause
In File: `Pimcore\Bundle\CoreBundle\Request\ParamConverter\DataObjectParamConverter.php`
The `$param` variable is using the actual variable name `$family` from the Controller `public function defaultAction(DataObject\Family $family)` and searching for the request attributes using `$request->attributes->has($param)` where `$param = 'family'` as opposed to `$param = 'id'` when by default, it should be `$request->attributes->has('id')`.
<img width="579" alt="Bildschirm­foto 2022-11-03 um 14 11 22" src="https://user-images.githubusercontent.com/3622712/199729573-f6b1549b-4f67-4c14-898e-d8ea9d62d807.png">

### Workaround
<img width="473" alt="Bildschirm­foto 2022-11-03 um 14 25 50" src="https://user-images.githubusercontent.com/3622712/199732773-7a7ca7be-3770-4231-94b4-a467d066aa76.png">

### Fix
<img width="573" alt="Bildschirm­foto 2022-11-03 um 14 24 40" src="https://user-images.githubusercontent.com/3622712/199732543-7133b377-d850-4701-8fd3-c41bf8554aa2.png">

**Comment by robertSt7** [comment]
@dvelguru Thanks for reporting this bug with a fix. Could you please create a PR with your fix?

**Comment by blankse** [comment]
@dvelguru Why did you not name the static route param "family". This would work right? I think we should not hard code the route param name. It should be possible to have multiple.

**Comment by dvelguru** [comment]
@blankse  It's really based on preference. But it will be used in the `getById()` method and not the `getByFamily()` method for example.

**Comment by brusch** [comment]
Agree with @blankse - name of placeholder on route and variable name in action have to match 🤗
