### ISSUE TITLE
[Bug]: Advanced Many To Many Relationship table does not work when table includes a calculated value

### ISSUE THREAD

**Issue by Johanna-Maria** [pimcore/pimcore#13531]
## Expected Behavior
When I write a value into an additional field in an advanced many to many relation, I would like to see this value after saving

## Actual Behavior
When a calculated value is included into the table, the value vanishes after saving. It is also partially not visible during editing (described below)

## Steps to reproduce this bug

https://11.x-dev.pimcore.fun/admin
Create an Advanced Many-To-Many Relationship and include a field of the type calculated value.
![image](https://user-images.githubusercontent.com/77202738/200538166-f75177c4-144e-4057-8a93-12d4a8773537.png)

When an object is dragged into the table, the test field is hardly clickable (it takes like five clicks before one is possible to randomly access the field). In addition, once the test field is edited and I click elsewhere, the value is not visible until I click on the field again.
![image](https://user-images.githubusercontent.com/77202738/200538886-70a97c8f-74c4-4ac1-a096-8e82e1316a97.png)

After saving (and reloading) the value in the test field is not visible anymore and the table looks a bit broken.
![image](https://user-images.githubusercontent.com/77202738/200539082-0c01a0eb-607d-4cf4-9429-6a1870c625d9.png)

**Comment by mcop1** [comment]
Hello @Johanna-Maria,
thank you for reporting the problem, but there are already similar issues, e.g. 
https://github.com/pimcore/pimcore/issues/13439
or
https://github.com/pimcore/pimcore/issues/13489 

We already provided a pull request for this, so things are looking good that it will be included in the release tomorrow.
