### ISSUE TITLE
Newsletter additional events

### ISSUE THREAD

**Issue by dominikschnieper** [pimcore/pimcore#1353]
# Feature Request 
I would like to have some more events within the sending process of newsletters. I have added these three in my code, would be nice to have it in the core:

### NewsletterController.php, sendAction: before console call:
```
\Pimcore::getEventManager()->trigger("admin.document.send.preSendNewsletter", $this, [
    'document' => $document,
    'addressSourceAdapterName' => $this->getParam("addressAdapterName"),
    'adapterParams' => json_decode($this->getParam("adapterParams"), true)
]);
```

### NewsletterController.php, stopSendAction: before json response:
```
\Pimcore::getEventManager()->trigger("admin.document.send.stopSendNewsletter", $this, [
    'document' => $document
]);
```

### InternalNewsletterDocumentSendCommand.php, execute: before delete tempstore:
```
\Pimcore::getEventManager()->trigger("admin.document.send.newsletterSent", $this, [
    'document' => $document
]);
```

### AddressSourceAdapterInterface.php, getParamsForSingleSending, add additional parameter to access newsletter document for mail-parameters
```
public function getParamsForSingleSending($limit, $offset, \Pimcore\Model\Document\Newsletter $document);
```

**Comment by fashxp** [comment]
could you provide a pull request for that?

**Comment by markus-moser** [comment]
Your examples are for pimcore 4, correct?

I needed the same for pimcore 5 and therefore I added pre and post save events to the version 5 of pimcore.

**Comment by dominikschnieper** [comment]
Yes correct. That's great to have now although i could solve my problem anther way!
Thanks

**Comment by fashxp** [comment]
ok, then we close this issue for now. when you need the events for pimcore4, please just create a pullrequest, we will accept it. thank you.
