### ISSUE TITLE
[Bug]: Site Requests with `install` url prefix cannot generate links correctly

### ISSUE THREAD

**Issue by jheimbach** [pimcore/pimcore#13545]
### Expected behavior

Document Page with pretty-url /installateursuche should not be classified as backend request

### Actual behavior

Document Page with pretty-url /installateursuche is always classified  as backend request, because the request url starts with /install ( source of bug: https://github.com/pimcore/pimcore/blob/11.x/lib/Http/RequestHelper.php#L127-L145)

### Steps to reproduce

1. Create a Site /example
2. Create a Page /example/installateursuche
3. (Optional create a different page in /example)
4. visit http://example.com/installateursuche
5. each internal link will be shown as document path /example/internal-link instead of the correct /internal-link route

**Comment by jheimbach** [comment]
Not sure if the checks for install and plugin prefixes in `detectFrontendrequest` are still relevant, so I am not sure what the solution should be.

**Comment by brusch** [comment]
@JHeimbach no this is just a leftover and can be removed, can you create a PR for us? Thanks in advance.

**Comment by dvesh3** [comment]
Fixed by #13549
