### ISSUE TITLE
[Bug]: DateTime ISO8601 issues

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#13540]
### Expected behavior

Replace `DateTime` to `DateTimeInterface::ISO8601` in a bugfix release and switch and migrate to `DateTimeInterface::ATOM` in major

### Actual behavior

![image](https://user-images.githubusercontent.com/6014195/200801259-8f83e764-2294-471d-b6d8-cdf69e8ec227.png)

These places may have same issues, if this format constant is removed

https://github.com/pimcore/pimcore/blob/c1f1f832be30136bc920cedbfee1e687267d0650/bundles/CoreBundle/src/EventListener/Frontend/StaticPageGeneratorListener.php#L104
https://github.com/pimcore/pimcore/blob/b2110bb3c416cbf4a7fce967fe98a0e031d642a0/bundles/CoreBundle/src/EventListener/Frontend/FullPageCacheListener.php#L381

and some hardcoded places (correct one should end with `P` instead of `O`)
https://github.com/pimcore/pimcore/blob/c7f023cf2e349bba8794795f6365447b836c887a/models/Document/Editable/Date.php#L82

See also CMF and Portal Engine

### Steps to reproduce

`DateTime::ISO8601` is removed since `php 7.2`, the replacement to avoid BC Breaks is `DateTimeInterface::ISO8601`, but both of  them, despite the name ISO8601 are not actually compatible with that ISO, so the final fix would  be using `DateTimeInterface::ATOM`

More info: https://www.php.net/manual/en/class.datetimeinterface.php#datetimeinterface.constants.iso8601

**Comment by dvesh3** [comment]
Fixed by #13578
