### ISSUE TITLE
Performance improvement: Ability to disable tree preview per user/role

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1355]
We currently have a Pimcore instance running multiple websites and having more 500 backend users.
Actually tree preview is enable, but we are about to disable it because we think it is ressource hog if many users are connected at the same time (tree preview send many HTTP request...).
But we would have liked to leave it enabled for admin user for instance so they can faster spot assets by hovering folders.

This issue is a proposal to bring the global system "disable tree preview" option to user/role level.

![disable-tree-preview](https://cloud.githubusercontent.com/assets/9025839/24174700/4a40e02e-0e92-11e7-9aa9-cb73675d82b7.png)

It would be great to adjust backend performance depending role/user needs.

I know new feature are closed for Pimcore 4, but maybe it could be integrated in Pimcore 5.

Thanks.

**Comment by brusch** [comment]
see also: #1125
I would prefer a user-specific setting instead of a system-wide.

**Comment by Yivan** [comment]
Sure, this issue is to make it on role/user level.
Something like that for user:

![userlevel](https://cloud.githubusercontent.com/assets/9025839/24211311/ece6c6ba-0f2b-11e7-934d-1b6dbd8a992e.png)

And for role level:

![rolelevel](https://cloud.githubusercontent.com/assets/9025839/24211324/f26cd494-0f2b-11e7-8929-61d1d3aeaa92.png)

**Comment by Yivan** [comment]
Maybe the other users checkbox could be added in the role level too:
"Show welcome screen on startup"
"Memorize open tabs"
"Disable unsaved content warning"
"Show close warning"
It will help administrator to manage user preference based on role.

A new checkbox could be added too at the user/role level:
"Hide edit image tab" (actually only available on the assets global system settings)

**Comment by brusch** [comment]
PRs are welcome 😊
At the moment we do not have the ambition to implement this.

**Comment by andreas-gruenwald** [comment]
I would also like to see that feature implemented.
