### ISSUE TITLE
[Bug]: After Objectbrick delete the database is not updated (Maybe add it to the classes-rebuild?)

### ISSUE THREAD

**Issue by niederberger-qw** [pimcore/pimcore#13550]
### Expected behavior

I delete an object brick and deploy it on the server and after classes-rebuild -d the tables for that objectbrick are gone.

### Actual behavior

I did delete an objectbrick local and deployed everything with git. The problem is, that the database is not updated if only the files are gone.

### Steps to reproduce

Add an objectbrick. Delete only the files and do a classes-rebuild -d

**Comment by niederberger-qw** [comment]
I use Pimcore 10

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
