### ISSUE TITLE
[Bug]: Read only style for Quantity Value

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#13554]
### Expected behavior

Quantity Value should have the same not-editable-style (grey label) as Input

### Actual behavior

![image](https://user-images.githubusercontent.com/104770750/201083134-ad683a03-e77d-4731-a696-56d444d43a1d.png)

### Steps to reproduce

Create a class with Quantity Value and Input and set both to Not editable

**Comment by Corepex** [comment]
we use `Ext.form.FieldContainer` for the quantityValue fields, which have no `readOnly` property. To achieve a "disabled" state we have to use `disabled`. 

https://docs.sencha.com/extjs/6.0.2/classic/Ext.form.FieldContainer.html#cfg-disabled
