### ISSUE TITLE
[Bug]: XLIFF Import - document target language not checked

### ISSUE THREAD

**Issue by simonkey** [pimcore/pimcore#13557]
### Expected behavior

When importing a xliff file with documents in it there should be a check if the target language of the document is the same of the current document. If the language doesn't match the entry should either be skipped totally, or the corresponding translation of the document should be resolved, or if the no translation exists at all a new document should be created . 

The behavior could/should be changed via a checkbox or something similar (e.g. _Overwrite if language doesn't match_). Default behavior should be IMO the skipping/resolving of the entries.

### Actual behavior

There is no check if the target-language matches the language of the page. This results in an overwriting of pages in the source language.

### Steps to reproduce

Tested on the pimcore demo
Pimcore 10.5.10

Create new language tree with one of the following options:

- Paste as language variant
- Paste as language variant (recursive)
- Paste language (recursive) ...

![image](https://user-images.githubusercontent.com/1583145/201292515-b730a0a3-b693-4f9a-9faa-aded7bc6d75d.png)

Select language

![image](https://user-images.githubusercontent.com/1583145/201292568-05e268c0-ba87-492a-909e-619f4cbf1a1e.png)

Export language with "Relations"-Option checked, otherwise no original documents won't be in the export!

![image](https://user-images.githubusercontent.com/1583145/201292682-e7bf3f14-21d6-4788-bc6f-ef17e7ebea11.png)

The new created tree starts with ID 255

![image](https://user-images.githubusercontent.com/1583145/201292898-e1b09952-fd7b-46cb-aa17-88f78d4bd9cc.png)

But there are entries lower than this ID e.g. ID54.

![image](https://user-images.githubusercontent.com/1583145/201292844-c3372be8-dfac-4017-83b1-9703c5c868f2.png)

If everything is translated, the documents with IDs lower 255 will be overwritten with the translated language.

**Comment by dvesh3** [comment]
Fixed by #13729
