### ISSUE TITLE
CKEDITOR: Add extra plugin should be possible without touching core

### ISSUE THREAD

**Issue by mk-conn** [pimcore/pimcore#1356]
It should be possible to add a ckeditor plugin without the need to put the plugin into the core ckeditor folder. Is that possible at all, since ckeditor requires a plugin to reside in that folder?

**Comment by brusch** [comment]
Please do **NOT** use our issue tracker for Q&A use our forums instead: https://groups.google.com/forum/#!forum/pimcore

**Comment by mk-conn** [comment]
I thought this was more of a feature request?

**Comment by brusch** [comment]
This is already possible, by setting the following variable: 
`pimcore.document.tags.wysiwyg.defaultEditorConfig`

eg.
`pimcore.document.tags.wysiwyg.defaultEditorConfig.allowedContent = true;` 

It doesn't matter if you overwrite the config using a plugin or just plain in your template.
