### ISSUE TITLE
Tag configuration screen remains empty

### ISSUE THREAD

**Issue by schuttelaar** [pimcore/pimcore#1357]
### Expected behavior 
When opening the "Tag Configuration" in Pimcore I expect to see a folder "All tags" which I can right click to add a tag.
  
### Actual behavior
When opening the "Tag Configuration" the panel remains white (blank).
  
### Steps to reproduce  
Open "Tag Configuration", with Firefox or Chrome, in both the latest stable release of Pimcore and the latest build.

**Comment by schuttelaar** [comment]
It does appear after opening another tab in Pimcore, and then going back to the Tag Configuration.

**Comment by weisswurstkanone** [comment]
Could you please remove the following lines (132-134) from
pimcore\static6\js\pimcore\element\tag\tree.js

and try again ? Are there any noticable side effects ?

                    afterrender: function () {
                        this.tree.getRootNode().expand();
                    }.bind(this)

**Comment by schuttelaar** [comment]
Yes it seems to work. Only side effect is that the tag tree does not expand automatically when opening the tab.

**Comment by weisswurstkanone** [comment]
I guess this can be achieved by adding
expanded: true
to the root config (line 120).

                root: {
                    id: '0',
                    text: t('element_tag_all_tags'),
                    iconCls: 'pimcore_icon_folder',
                    expanded: true
                },

If there are no objections I will commit the two changes.

**Comment by weisswurstkanone** [comment]
build 4064
