### ISSUE TITLE
[Feature]: Inheritance for Fieldcollections 

### ISSUE THREAD

**Issue by storbahn** [pimcore/pimcore#13574]
### Feature description

For Fieldcollections (with simple fields like text input) it is possible to use inheritance by changing the return value of supportsInheritance() (in \Pimcore\Model\DataObject\ClassDefinition\Data\Fieldcollections) to true.

```
public function supportsInheritance()
{
    return true;
}
```

Is it possible to set it to true as default or do we have any limitations (e.g. more complex field types)?

**Comment by fashxp** [comment]
there are some more aspects to be considered: 
- how to consider inherited values in queries of listings: for all inherited values, you can query in query tables, for field collections there are no query tables
- how to overwrite single field collection values - or just implement a all or nothing approach?

for now we didn't find an approach that follows same principles as for the other data types. that's the reason, why inheritance is not supported. 
any ideas and PRs are welcome though.

**Comment by storbahn** [comment]
Hi @fashxp,

thanks for the feedback. unfortunately then it is not as simple as I assumed

**Comment by fashxp** [comment]
sadly not 😀

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
