### ISSUE TITLE
[Bug]: Cannot set NULL value programmatically for Boolean Select

### ISSUE THREAD

**Issue by doncatnip** [pimcore/pimcore#13582]
### Expected behavior

$value->set("BooleanSelectProperty", null);
$value->save();

results in empty selection.

### Actual behavior

Actual result is an unresolved state in the UI. The field is greyed out while the label for True is shown.

![Screenshot 2022-11-15 at 15 05 27](https://user-images.githubusercontent.com/692660/201939340-a42261dc-82f0-477d-af7e-1e48f90c61e4.png)

The Database is inconsistent as well, as the table object_xxx contains 1 for that property, while object_store_xxx contains NULL.

### Steps to reproduce

Add a boolen select field to a class. Call $value->set("property", null); via PHP API on that field. Observe property not set to null/empty.

**Comment by Corepex** [comment]
@doncatnip, can you provide me some more information according to this bug? 

I tried to reproduce the bug in pimcore version `10.5` and there everything works fine!

I tested these options to set the value (both work as expected):
 - `$object->setBooleanSelect(null)` 
 - `$object->set('booleanSelect', null)`

**Comment by kjkooistra-youwe** [comment]
This looks like an inherited valued.

**Comment by doncatnip** [comment]
> This looks like an inherited valued.

Indeed! There was a vital piece of information missing about data inheritance on my side. I am very sorry and thanks!
