### ISSUE TITLE
Update to Zend Framework 3

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#1358]
The heading says everything

**Comment by Pegasuz** [comment]
The pimcore team is currently making Pimcore 5, which is based on Symfony 3.

**Comment by dpfaffenbauer** [comment]
First alpha gets released this month.

**Comment by kanevbg** [comment]
Is that info coming from pimcore internals or I missed some good source of information? :)

**Comment by brusch** [comment]
Yes, I can confirm that we are going to release the first alpha version of Pimcore 5 basd on Symfony next week.
