### ISSUE TITLE
[Improvement]: Dangerous feature on user class

### ISSUE THREAD

**Issue by mcmaroon** [pimcore/pimcore#13616]
### Improvement description

The scenario is simple:
1. High traffic on the site 
2. Log into the admin panel
3. We delete any user
4. The server goes down due to high load 
https://github.com/pimcore/pimcore/blob/v6.9.6/models/User/AbstractUser.php#L248

**Comment by brusch** [comment]
I'd consider this as a bug. 
First we need to check why the cache is cleared here, I currently can't think of any valid reason for that.

**Comment by dvesh3** [comment]
Fixed by #15609
