### ISSUE TITLE
composer.json / autoload_static.php inconsistency

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#1361]
I think there is a conceptional problem within the collaboration of composer and the pimcore internal update procedure.

### Example
the pimcore composer.json requires:

```json
"php-di/php-di": "~5"
```

### Stacktrace
1. create your custom composer.json
```json
{
    "name": "your-company/your-project",
    "type": "library",
    "config": {
        "vendor-dir": "src/vendor",
        "document-root-path": "./src/"
    },
    "require": {
        "pimcore/pimcore": "4.4.3",
        "another/repo": "1.1.0"
    }
}
```
2. do  a `$ composer install`
3. *note*: composer says: `Installing php-di/php-di (5.4.1)`
4. try to update pimcore to the next build (4045)
5. pimcore delivers some [autoload files](https://update.pimcore.org/v2/getFiles.php?for=4045&offset=0&limit=50)
5. update throws an error: `Fatal error: Interface 'Psr\Container\ContainerInterface' not found`

## But why?
The latest release of `php-di/php-di` is `5.4.1`. Because pimcore says "`~5`", the update from `5.4.0` to `5.4.1` is okay. **But**: `php-di/php-di 5.4.1` requires the [psr/container](https://github.com/PHP-DI/PHP-DI/commit/4ec345f6e7f5e18e955d0973f8611dcc0ab348be) package now. With every build update pimcore overrides the [`/vendor/composer/autoload_static.php`](https://update.pimcore.org/v2/getFiles.php?for=4045&offset=0&limit=50) file - which doesn't have any clue about this new requirement and so the the `Psr\\Container\\` autoload prefix gets removed - the update will fail.

For now, every installation which did a composer install or update in time of development will face this problem. 

Either you stick explicitly to the required versions like "`php-di/php-di": "5.4.0`" (this applies to all the other required repos also btw.) or you have to exclude the autoload overrides.

**Comment by cyawman** [comment]
I'm experiencing the same problem when I add my own composer packages. I don't think composer autoloads should be included in updates. It would make more sense to merge the composer.json files and then run the composer dump-autoload function as part of the cleanup process.

**Comment by solverat** [comment]
not by default, right. we're having some post movements after the composer process which allows us to use pimcore as a depenency. but like you said, it won't change a thing.

**Comment by cyawman** [comment]
@brusch My situation my be a little unique. I'm using an external dependency in my startup.php file. When I run the pimcore update it merges my composer.json files, then it replace the composer autoloaders. Since the dependency is in startup.php it errors out 'Class not found' and the update process fails. I'll try and work around it.

**Comment by brusch** [comment]
This issue is addressed in v5. 
The updater doesn't touch the `/vendor` folder anymore, everything in there is managed by composer.

**Comment by solverat** [comment]
Why did you close this ticket in the first place? Right now it's impossible to update any pimcore 4.x installation which has custom composer dependencies. We tried to fix the dependency in composer.json with a bounded `"php-di/php-di" : "5.4.1"`, but that's an pointless act because pimcore overrides the composer.json with every build update.

**Comment by dpfaffenbauer** [comment]
Really big issue and shouldn't be closed without an actual solution. A lot of people are going to face this problem!

My solution is following:

```cli
composer require php-di/php-di:5.4.0
composer require container-interop/container-interop:1.1
```

This downgrades PHP-DI to 5.4.0 and container-interop to 1.1. Since PHP-DI 5.4.1 requires both: container-interop:~1 and psr/container:1.0, you need to downgrade both packages.

**Comment by solverat** [comment]
thanks @dpfaffenbauer!
