### ISSUE TITLE
[Bug] [Tests]: Pimcore Helper

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#13614]
### Expected behavior

Clean Test-Setup

### Actual behavior

Error-prone Test modules.

### Steps to reproduce

In https://github.com/pimcore/pimcore/pull/11756, you've ripped out the symfony module.

But you kept several references, which are invalid now:

- `getContainer`
- `getKernel`
- Whole Kernel initialization (Happens now in `_bootstrap`)

https://github.com/pimcore/pimcore/blob/10.5/tests/_support/Helper/Pimcore.php#L82

Documention is also outdated:
https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Testing/Application_Testing.html

Things like `$I->amOnPage()` won't work anymore.

**Comment by dvesh3** [comment]
Reverted the removal on 10.5 with #13762.
