### ISSUE TITLE
[Bug]: Disallow Add/Remove/Reordering for Field-Collections doesn't work

### ISSUE THREAD

**Issue by jdreesen** [pimcore/pimcore#13621]
### Expected behavior

It's not possible to add/remove or reorder field collections if it's disabled in the class definitions.

### Actual behavior

The buttons are still displayed and working.

### Steps to reproduce

- Login to the official demo: https://demo.pimcore.fun/admin/?perspective=default
- Look at the `paymentInfo` field definition of the `OnlineShopOrder` class.
  The options are checked, so it should be disabled:
  ![image](https://user-images.githubusercontent.com/424602/202694973-0b48ede1-4b36-4849-9721-a7993a1a6353.png)
- Open any `OnlineShopOrder` object, go to the "Edit" tab and then the "Payment" tab.
  The buttons are still displayed and can be used:
  ![image](https://user-images.githubusercontent.com/424602/202695600-a883852c-dc3c-469e-b15b-cbf26979d607.png)

**Comment by Corepex** [comment]
@jdreesen, thanks for reporting this bug. The bug seems to have already been fixed and will be released with the 10.5.11 bugfix release tomorrow. I'll recheck it tomorrow after the release and reopen the issue if necessary.
