### ISSUE TITLE
Wrong sort order in classification store group definition

### ISSUE THREAD

**Issue by tetrascout** [pimcore/pimcore#1363]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [X] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [X] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [ ] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [X] There's no existing ticket for the same issue

### Expected behavior 
Sorter field should be numerically sorted
### Actual behavior  
Sorter field is alpha sorted  

![image](https://cloud.githubusercontent.com/assets/25662951/24413912/27c6c338-13dd-11e7-8796-b39ae5e9ed2e.png)

**Comment by weisswurstkanone** [comment]
many thanks.

fixed in build #4066

**Comment by piotrecky** [comment]
Hi, when I insert the classification store to object than sorting in that object editor doesn't work. The keys order is ok but the groups is incorrect.
