### ISSUE TITLE
[Bug]: Saving an unpublished snippet results in HTTP 500

### ISSUE THREAD

**Issue by limenet** [pimcore/pimcore#13632]
### Expected behavior

Version is saved and no error message is shown.

### Actual behavior

Version is saved and error message is shown:

```
Status: 500 | 
URL: /admin/snippet/save?task=version
Method: PUT
Message: Call to a member function getId() on null
Trace: 
in /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/SnippetController.php:133
#0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(163): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\SnippetController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#2 /var/www/html/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#3 /var/www/html/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
```

Most likely this is caused by https://github.com/pimcore/pimcore/commit/8dba6abc63751670db50f97df1b5bb7801837c6f#diff-080c43a34b67f92b75610e8130534562d0f994cd0f8771cff9b167a9ab42aa1e since `$version` is now null in `\Pimcore\Bundle\AdminBundle\Controller\Admin\Document\DocumentControllerBase::saveDocument` and then a `$version->getId()` in `\Pimcore\Bundle\AdminBundle\Controller\Admin\Document\SnippetController::saveAction` is effectively `null->getId()`.

### Steps to reproduce

1. Create a new snippet in the document tree
2. Click "Save"

Tested against Pimcore 10.5.10 but `11.x` appears to still exhibit this behavior: https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/src/Controller/Admin/Document/DocumentControllerBase.php#L446-L453

**Comment by dvesh3** [comment]
Fixed by #13709
