### ISSUE TITLE
[Bug]: QuantityValue Field returns '0' instead of 'NULL' after saving an empty Value

### ISSUE THREAD

**Issue by luka-jukic** [pimcore/pimcore#13646]
### Expected behavior

If a Quantity Value Field is saved with an empty value, this value should also be empty again when the DataObject is reloaded.

### Actual behavior

If a Quantity Value Field is saved with an empty value, the value will be '0' after reloading.

### Steps to reproduce

To reproduce the error, you can simply create a new TestClass and enrich it with a QuantityValue Field.

If you now create a new object, select the unit, but leave the value empty and then save it, the value '0' is displayed when the object is reloaded, although the value in the database is 'NULL'.

<img width="314" alt="Empty Test Class befor Save" src="https://user-images.githubusercontent.com/40577324/203263088-db0e2364-be41-4458-8a8f-aad9d777535d.png">

The problem is that when the data object is saved again, the value '0' is saved and not the value 'NULL'.

<img width="361" alt="Test Class After Save and Reload" src="https://user-images.githubusercontent.com/40577324/203262413-5137bb96-49dc-4456-a724-38891d719510.png">

We noticed this error after updating from 10.3.4 to 10.5.10. Now all 'NULL' values suddenly become '0' values.

If that was the intention, there should have been a migration, as the state cannot be controlled in this way. Moreover, this change was also not really mentioned in the upgrade notes.

**Comment by mcop1** [comment]
Hello @luka-jukic , 
thank you for reporting this problem. 
I linked a pull request that could fix the issue. Do you mind having a look?

**Comment by luka-jukic** [comment]
Hello @mcop1 
Thank you for the pull request.
I have looked at it and tested it. Your adjustment fixes the problem. Thank you very much!

**Comment by mcop1** [comment]
Sounds great, it should be in the next patch then.

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/13893
