### ISSUE TITLE
Column configuration not working on Variants list #953 still not working in 4.5.0

### ISSUE THREAD

**Issue by tetrascout** [pimcore/pimcore#1366]
# Bug Report
- [X] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [X] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [ ] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [ ] There's no existing ticket for the same issue
 
### Expected behavior 
See #953   
### Actual behavior  
Should have been fixed by 4.5.0
### Steps to reproduce  
customise grid layout of variant and try to save it

**Comment by fashxp** [comment]
also happens in pimcore 5

**Comment by weisswurstkanone** [comment]
fixed in build 4105

**Comment by weisswurstkanone** [comment]
Please be aware that the approach how grid configuations are saved will change in pimcore 5.

see https://github.com/pimcore/pimcore/issues/2074
