### ISSUE TITLE
[Bug]: pimcore_block inside pimcore_areablock area produces broken html in editmode

### ISSUE THREAD

**Issue by RaederDev** [pimcore/pimcore#13660]
### Expected behavior

I have a custom area inside an areablock, inside that area I have a pimcore_block:

```twig
<ul class="list-disc list-inside sm:list-outside">
    {% set listBlock = pimcore_block("list") %}
    {% for i in listBlock.iterator %}
        <li class="sm:py-4 py-2">
            {{ pimcore_input("list_entry",{
                "placeholder": "Text",
                "reload": true,
            }) }}
        </li>
    {% endfor %}
</ul>
```
  
("reload": true) or ("reload": false) does not change the behavior.
  
When I click to add a new entry to the list the first entry is created correctly in the editor:
```html
<div data-name="content:3.list:2.list_entry" data-real-name="list_entry" data-type="input"
     data-block-names="content, list" data-block-indexes="3, 2" id="pimcore_editable_content_3_list_entry"
     class="pimcore_editable pimcore_editable_input empty" contenteditable="true" data-placeholder="Text"></div>
```

After I click to add a second block invalid html is created and the input is invisible:
```html
<div data-name="content:3.list:3.list_entry" data-real-name="list_entry" data-type="input"
     data-block-names="content, list" data-block-indexes="3, 3" id="pimcore_editable_content_3_list_entry"
     class="pimcore_editable pimcore_editable_input"></div>
```

Note the duplicated ID on the second div. Also contenteditable="true" is missing, I assume this is related to the duplicate ID. Re-opening the Document fixes it for all invisible entries until you add > 1 more again.

### Actual behavior

Correct html is added to the DOM in the admin interface and the field is not invisible.

### Steps to reproduce

Create a new Areabrick extending AbstractTemplateAreabrick with no changed defaults other than name and description. In the template for that areabrick add the twig code I posted above.

I also tried using a textarea instead of a simple input but had the same behavior.

**Comment by kingjia90** [comment]
Thank you for the report, but it seems that there is a mistake.

The `reload` should be added to the `block` like: https://github.com/pimcore/pimcore/blob/e39d24f4610a35eaf2487b8a28ffd9917fa653d3/doc/Development_Documentation/03_Documents/01_Editables/06_Block.md?plain=1#L57
See also https://pimcore.com/docs/pimcore/current/Development_Documentation/Documents/Editables/Block.html, the `pimcore_input` itself don't have the `reload` config available

In other words, the code should be

```twig
<ul class="list-disc list-inside sm:list-outside">
    {% set listBlock = pimcore_block("list", {'reload': true}) %}
    {% for i in listBlock.iterator %}
        <li class="sm:py-4 py-2">
            {{ pimcore_input("list_entry",{
                "placeholder": "Text"
            }) }}
        </li>
    {% endfor %}
</ul>
```
Hope it helps

Closing for the moment, as it is working fine. 
If not , please re-open with further details.
