### ISSUE TITLE
[Bug]: Deadlock on relations Table (again)

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#13678]
### Expected behavior

When running multiple workers to process async imports, the relations table should not lock. Reason for the lock is the `key`: `forward_lookup`.

### Actual behavior

it does lock.

### Steps to reproduce

Run multiple workers with imports. (create or update object)

```
*** (1) TRANSACTION:
TRANSACTION 572017002, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
LOCK WAIT 19 lock struct(s), heap size 1128, 8 row lock(s), undo log entries 10
MySQL thread id 3738690, OS thread handle 508, query id 894258846 20.71.67.44 pimcore_dev Update
INSERT INTO object_relations_as_standard (`dest_id`, `type`, `fieldname`, `index`, `src_id`, `ownertype`) VALUES ('530970', 'object', 'attributes', '1', '769190', 'object')
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 4090 page no 4679 n bits 656 index forward_lookup of table `pimcore_dev`.`object_relations_as_standard` trx id 572017002 lock_mode X insert intention waiting
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

*** (2) TRANSACTION:
TRANSACTION 572017005, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
20 lock struct(s), heap size 1128, 9 row lock(s), undo log entries 10
MySQL thread id 3738691, OS thread handle 4428, query id 894258867 20.71.67.44 pimcore_dev Update
INSERT INTO object_relations_as_standard (`dest_id`, `type`, `fieldname`, `index`, `src_id`, `ownertype`) VALUES ('530970', 'object', 'attributes', '1', '769191', 'object')
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 4090 page no 4679 n bits 656 index forward_lookup of table `pimcore_dev`.`object_relations_as_standard` trx id 572017005 lock_mode X
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 4090 page no 4679 n bits 656 index forward_lookup of table `pimcore_dev`.`object_relations_as_standard` trx id 572017005 lock_mode X insert intention waiting
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

```

**Comment by dpfaffenbauer** [comment]
I don't think there is an easy solution for this. The index `forward_lookup` is needed. Problem is that this is not a rare case, it happens for every 4th or 5th message in the queue.

**Comment by solverat** [comment]
Been there. We had huge issues with multiple queue processes. We stopped all those approaches, and we're now doing batched pulls/pushes only. Maybe something you also want to consider. :)

**Comment by dpfaffenbauer** [comment]
Problem is that the data comes from an external system into a azure service bus, we process that with symfony messenger. but we have about 2 million messages to process. if we can process only about 1500 per hour, it still takes 55 days to import. there has to be a better way to scale that.

**Comment by dpfaffenbauer** [comment]
I am gonna reopen this, this is still relevant. I figured out why the deadlock happens.

Pimcore handles the object_relations_* table quite stupid to be honest. On save, the data is deleted in Concrete/Dao and then inserted by Type/AbstractRelations. This is causing the locking behaviour. Transaction 1 is waiting for the Gap created by Transaction 2 and Transaction 2 is waiting for the gap created by Transaction 1. If we would not delete the whole directly but like per relational field or by actually computing the differences, we could solve this deadlock.

**Comment by dpfaffenbauer** [comment]
ping @brusch @fashxp

**Comment by dpfaffenbauer** [comment]
Pimcore, as a PIM, should be able to handle loads of data and quickly as well. The only issue here is how Pimcore does it and that is fixable.
