### ISSUE TITLE
RFC: Enhance backend search

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#13689]
### Improvement description

Currently the Pimcore backend search is not very user friendly as for example prefixes are not found: searching for "Pim" will not find an element with "Pimcore". We tried to change this in #13573 but perhaps this approach was not well designed. For this reason here is a concept of refactoring the search functionality to achieve the following goals:

-   UX of search should be similar to what users learned from search engines like Google:
    -   automatic prefix + suffix search, e.g. typing `john` should find "John Doe" but also "Don Johnson"
    -   negative terms to exclude results, e.g. searching for `john -doe` will only find "Don Johnson", but not "John Doe"
    -   exact match with quotes, searching for `"john doe"` (search term wrapped in quotes) will find "John Doe" but not "Don Johnson"
-   search should work for all languages, e.g. splitting search term by spaces does not work in chinese / japanese
-   no additional setup for the fields to be indexed → just use Pimcore's default indexing → no additional configuration, no additional effort necessary during saving
-   prepare to connect to search providers via adapters, e.g. Doofinder, FactFinder, Algolia etc. → may be implemented later
-   later: support fuzzy search (correct spelling errors) with https://github.com/tigitz/php-spellchecker or based on words of existing object data
-   later: search should be usable also for frontend applications (via JSON API)
-   later: search in search results / faceted search (automatically suggest attributes to filter search result - like on Amazon when you search for "Sneaker", it suggests you a shoe size filter)

__Implementation concept (plugin)__

1.  For internationalisation (languages without word separators like Chinese / Japanese), in installation add FULLTEXT `bb_fulltext` index `WITH PARSER ngram` to table `search_backend_index`, for details see https://dev.mysql.com/doc/refman/5.7/en/fulltext-search-ngram.html
    -   for MariaDB this does not work, see https://jira.mariadb.org/browse/MDEV-10267
    -   → try to convert table `search_backend_index` to table engine "Mroonga": `ALTER TABLE search_backend_index ENGINE = Mroonga;`
    -  → if this also fails, it is no problem but we have to care for ngram indexing ourselves.
2.   For suffix search we need a reverse index as MySQL only supports prefix searches. Add column `data_reverse` to table `search_backend_index`. Add FULLTEXT index to it (with same settings as above).
3.  For indexing, add event handler for `pimcore.search.backend.preSave`:
     - ngram indexer: check if index `bb_fulltext` has been created with `ngram` parser or if table engine is "Mroonga". If any of those is true, skip this event handler, otherwise tokenize the input data to ngrams of length `innodb_ft_min_token_size` (shorter tokens cannot be used anyway for InnoDB's fulltext search)
4.   For suffix search, add event handler for `pimcore.search.backend.postSave`: fill column `data_reverse`, e.g. data to be indexed = "Pimcore", then in column `data_reverse` write "erocmiP"
5.   Add event handler for `pimcore.admin.search.list.beforeListLoad` → change search term to fulfill above criteria:
      - check if index `bb_fulltext` has been created with `ngram` parser or if table engine is "Mroonga". If none of this applies, change search term according to the following rules:
         1.  tokenize quoted phrases, e.g. with ngram length=2, "abc def" gets converted to "ab bc de ef" (with quotes!)
         2.  for trailing asterisks (prefix search)
            1.  if term length < `innodb_ft_min_token_size`, keep asterisk in search term, e.g. with `innodb_ft_min_token_size=4` search term "car*" stays "car*"
            2.  if term length >= `innodb_ft_min_token_size`, tokenize term, e.g. "john*" with `innodb_ft_min_token_size`=2 gets tokenized to "jo oh hn*"
         4.  for suffix searching, add above conditions with reverse terms on column `data_reverse`
      - if fulltext index has been created with `ngram` parser or table engine "Mroonga", ngram search already works as defined above, see https://dev.mysql.com/doc/refman/5.7/en/fulltext-search-ngram.html#idm46347601044064

This concept uses terms of a plugin. In #13573 I unexpectedly got a refusing answer as if the Pimcore search would work quite well currently but in fact in each PIM systems pitch the search is one of the pain points currently. As we are big fans of solving problems at root, we are interested if Pimcore could imagine to accept this as a core change. If not, we would implement this as a plugin.

Please feel free to add comments to get a good solution in the end.

**Comment by fashxp** [comment]
Thx for the thread, looking forward to the discussion. 

Just to clarify one thing: 
>  (...) refusing answer as if the Pimcore search would work quite well currently but in fact (...)

There wasn't a refusing answer, in the discussion we tried to come to a better solution which also does not change existing behavior and potentially cause confusion. And we were of the impression, that we archived that and came to a good solution?

**Comment by BlackbitDevs** [comment]
@brusch @dvesh3 WDYT? Could you imagine to accept such a big change? I want to ask before because I have invested too many hours into PRs which in the end got simply declined.

**Comment by BlackbitDevs** [comment]
Interesting alternative: https://github.com/manticoresoftware/manticoresearch/ (suggested by https://github.com/pimcore/pimcore/discussions/13429)

**Comment by BlackbitDevs** [comment]
We decided to implement this as a plugin, see https://pimcore.com/en/developers/marketplace/blackbit_digital_commerce/pimcore-better-search_e333574

This plugin is based on https://github.com/teamtnt/tntsearch - and it is implemented as a drop-in replacement for the default Pimcore backend search.
Thus, with this plugin you get the following features for the PImcore backend search:

----

Problems with Pimcore's built-in search functionality
-----------------------------------------------------

Pimcore provides an object search in

-   global search
-   relation field search (via looking glass icon)
-   grid search

All of these places share the same underlying search engine and thus the same problems:

-   by default (without MySQL's search operators) only word search is supported
    -   e.g. searching `product` will not find a data object which only contains `products`
-   terms with less than 3 characters get ignored (with MySQL's default `innodb_ft_min_token_size` setting)
    -   e.g. searching for `CD` will never find anything
-   there is no fuzzy search which searches tolerating typo errors
    -   e.g. searching for `produt` will not find `product`
-   there is no word-stemming
    -   e.g. searching for `shirts` (plural) will not find an object which contains `shirt`
-   sometimes order of search results is irritating
    -   e.g. elements which contain the search term only once get listed higher than those which contain it multiple times
-   search is unusable for languages which do not have word separators (like Chinese, Japanese)

What does the plugin do different?
----------------------------------

This bundle uses [TNT Search](https://github.com/teamtnt/tntsearch) as underlying library. This library solves all above issues, as it:

-   supports prefix and suffix search
-   supports any word length
-   implements fuzzy / typo-tolerant search
-   implements word-stemming for many languages
-   implements [TF/IDF algorithm](https://en.wikipedia.org/wiki/Tf%E2%80%93idf) to better sort search results
-   implements n-gram search
    -   for use with languages like Chinese / Japanese which do not have word separators
