### ISSUE TITLE
[Bug]: User changes to the frontend user when saving documents and throws errors while publishing.

### ISSUE THREAD

**Issue by roland4432** [pimcore/pimcore#13687]
### Expected behavior

Admin user session is persistently pointing to the backend user when saving documents.

### Actual behavior

The user changes to the frontend user when storing documents and throws errors while publishing.

### Steps to reproduce

- Create a user object with username, password (just suitable to serve as a user object)
- Define a firewall rule to have the user cover all frontend routes and configure the user provider to use the created userobject
- Go to the frontend and simultaneously login as this user (so you have the admin and frontend user being logged in at the same time in the same browser instance)
- Go to any document, put some dummy context & save
- Yields error upon saving
tatus: 500 | Internal Server Error
URL: /admin/page/save?task=publish
Method: PUT
Message: Call to a member function getId() on null
Trace: 
in /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php:387
0 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php(467): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\DocumentControllerBase->handleTask('publish', Object(Pimcore\Model\Document\Page))
1 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/PageController.php(155): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\DocumentControllerBase->saveDocument(Object(Pimcore\Model\Document\Page), Object(Symfony\Component\HttpFoundation\Request))
2 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(163): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\PageController->saveAction(Object(Symfony\Component\HttpFoundation\Request), Object(Pimcore\Document\StaticPageGenerator))
3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
4 /var/www/html/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
5 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
6 {main}

vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase (lines 427+):
```php
 $task = strtolower($task ?? $request->get('task'));
$version = null;
switch ($task) {
    case $task === self::TASK_PUBLISH && $document->isAllowed($task):
        $this->setValuesToDocument($request, $document);
        $document->setPublished(true);
        $userIsStillBackendUser = $this->getAdminUser(); // will return the correct user currently logged in the backend
        $document->save();
        $userIsNotBackendUserAnymore = $this->getAdminUser(); // will return null -> TokenStorage is now holding the frontend user
```

**Comment by roland4432** [comment]
Possibly caused by code in our project. If the above lines of code don't change the user, please close this issue.
Thank you

**Comment by aryaantony92** [comment]
> 

Thanks for the update. Will check it 👍

**Comment by mattamon** [comment]
Hey @roland4432,

could you please specify why you need the user to be logged in as backend user and frontend user in the same session?
Wouldn't it be easier to login them in in separate sessions, like open a private/incognito window?

**Comment by mattamon** [comment]
@roland4432, any update on this? :)

**Comment by mattamon** [comment]
I'm closing this issue now. If this is still relevant please open another issue.
