### ISSUE TITLE
[Task]: Check for phpstan Release (>=1.9.3) 

### ISSUE THREAD

**Issue by mcop1** [pimcore/pimcore#13688]
### Improvement description

Adapt composer.json accordingly

Remove at least the then unnecessary line `// @phpstan-ignore-next-line - phpstan expects bool, but actually doc says int` in
`lib/Image/Adapter/Imagick.php` on line 328, above `getColor` method:
`$color = $pixel->getColor(1); // get the real alpha not just 1/0`

**Comment by blankse** [comment]
Should also be fixed in 10.5
