### ISSUE TITLE
PDF - return in startPdfGenerator

### ISSUE THREAD

**Issue by mediafant** [pimcore/pimcore#1369]
## Feature description 
For this:
https://groups.google.com/forum/#!topic/pimcore/X18UYV5E5MU
I found a solution to get the pdf-file as a return of generator. But in core code there is no return of this pdf. So it would be nice if generator return this:
/pimcore/lib/Pimcore/Web2Print/Processort.php
(line 118) Last line in methode: startPdfGeneration add: return $pdf;
 
Andreas

**Comment by fashxp** [comment]
fixed in build 29 (pimcore 5)
