### ISSUE TITLE
[Bug]: Limit for Classificationstore doesn't work with inheritance

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#13692]
### Expected behavior

Limit can't be exceeded

follow up: https://github.com/pimcore/pimcore/pull/13690

### Actual behavior

Limit can be exceeded

### Steps to reproduce

- Create an class with a CS
- Create an object with this class
- Create a child of this object
- Create a child of the child
- Try do delete and add (inhertited) CS-Groups

Possible problem:
getUsedActiveGroups https://github.com/pimcore/pimcore/blob/631a52073541777720403653f987bd62f1ac881f/bundles/AdminBundle/public/js/pimcore/object/tags/classificationstore.js#L691 behaves incorrectly

**Comment by lukmzig** [comment]
@robertSt7 can please also crate a follow up for these changes for admin bundle repository? Thanks!
