### ISSUE TITLE
[Improvement]: don't render documents when saving

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#13700]
### Improvement description

Rendering documents when saving shouldn't be necessary. 

I guess it was used because it is easier to load the available data (based on what's available in the template), but it seems we should apply separation of concerns here. Would most likely improve performance when saving.

Related https://github.com/pimcore/pimcore/issues/8992

**Comment by fashxp** [comment]
consider: checking required editables ...

**Comment by passioneight** [comment]
Well, personally, I don't need this feature, but I can see why some would want it.

Either way, the separation of concerns makes sense, because when saving documents in the CLI, the check will output the HTML even if no verbosity level is set. Some hosters will see the output of commands as errors and kill the command - no matter if it's just a dump or not. They usually also do not allow to disable this behaviour.

Additionally, the rendering does have negative impact on the performance - especially if there are no required editables available anyway.

Of course, changing this is not trivial and I'm merely suggesting that we should find a different solution to this.

For example, if I wanted to check the editable requirements, maybe the functionality should live in an `EditableService`, which I can then inject and call as needed. Or if Pimcore decides to call the service before the document is saved, the `EnabledTrait` would be helpful to allow disabling this functionality.

**Comment by fashxp** [comment]
any suggestions and contributions are welcome

**Comment by passioneight** [comment]
Just wondering if this is something you intend to solve soon?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
