### ISSUE TITLE
[Bug]: newly created asset becomes null if assigned to hotspotimage

### ISSUE THREAD

**Issue by frithjof** [pimcore/pimcore#13704]
### Expected behavior

the hotspotimage contains the asset image

### Actual behavior

 object(Pimcore\Model\DataObject\Data\Hotspotimage)#2259 (7) {
    ["image":protected]=>
    NULL
    ["hotspots":protected]=>
    array(0) {
    }
    ["marker":protected]=>
    array(0) {
    }
    ["crop":protected]=>
    array(0) {
    }
    ["_owner":protected]=>
    NULL
    ["_fieldname":protected]=>
    NULL
    ["_language":protected]=>
    NULL
  }

### Steps to reproduce

use Pimcore\Model\Asset;
use Pimcore\Model\DataObject\Data\Hotspotimage;

.....
`
                                        $prod_image = new Asset();
                                        $prod_image->setParentId(1);
                                        $prod_image->setKey('somekey.jpg');
                                        $content = 'xxxxx';
                                        $prod_image->setData($content);
                                        $prod_image->save();
                                     $pim_img_arr[] = new Hotspotimage($prod_image);

-----
var_dump(pim_img_arr)
-----------
array(1) {
  [0]=>
  object(Pimcore\Model\DataObject\Data\Hotspotimage)#2081 (7) {
    ["image":protected]=>
    NULL
    ["hotspots":protected]=>
    array(0) {
    }
    ["marker":protected]=>
    array(0) {
    }
    ["crop":protected]=>
    array(0) {
    }
    ["_owner":protected]=>
    NULL
    ["_fieldname":protected]=>
    NULL
    ["_language":protected]=>
    NULL
  }
}

            if you use use Pimcore\Model\Asset\Image; for the new file it works fine so i am not sure if we should file this as bug or feature request that the asset changes to image type on save

**Comment by torqdev** [comment]
Hi @frithjof -

We experienced the same issue as yours a few months ago. We dug a bit further into how Pimcore creates assets in the `Pimcore\Bundle\AdminBundle\Controller\Admin\Asset\AssetController:addAsset()`, and they actually have a `create` function in the `Asset` class that helps out with creating the proper type. For your example you may want to do the following:
```
use Pimcore\Model\Asset;
$content = 'xxxxx';
$asset = Asset::create(1, [
    'filename' => 'somekey.jpg',
    'data' => $content
]);
```
When using this function it uses the MimeType to define the proper asset. So for your example it would return Asset\Image.

**Comment by Corepex** [comment]
Hi @frithjof, thanks for creating this ticket. 

I looked into the problem you described, and now I can give you a detailed answer according to your problem.

First, I want to mention that this behavior is no error. 
It's expected to only pass objects of type `Pimcore\Model\Asset\Image` to the constructor of `Hotspotimage`.

You can view the according code here:
https://github.com/pimcore/pimcore/blob/520f220a77fffcfe0b3e6a9c414765e01b1d20df/models/DataObject/Data/Hotspotimage.php#L56-L60

So if you want to create a `Hotspotimage` and add an `Image` you have two possible options:

1) use the `Asset::create` method (@torqdev already mentioned that option in their comment above)
2) use the `Pimcore\Model\Asset\Image` class (also described in our docs https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Image_Types.html#page_Image-Gallery - look at the code example)
