### ISSUE TITLE
[Feature]: JSON field for data objects

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#13702]
### Feature description

Propose to support JSON field type for data objects which to create JSON column in the database.
https://dev.mysql.com/doc/refman/8.0/en/json.html

The field will likely have to accept only valid JSON data.

For this will be needed UI for the field in the admin panel, that can be eventually used: [josdejong/jsoneditor](https://github.com/josdejong/jsoneditor) or [josdejong/svelte-jsoneditor](https://github.com/josdejong/svelte-jsoneditor) but R&D should be done.

**Comment by brusch** [comment]
@kanevbg that sounds like a perfect match for a bundle 😉

**Comment by kanevbg** [comment]
@brusch Did you mean as part of the Pimcore or to be developed independently of Pimcore?

**Comment by brusch** [comment]
@kanevbg independently 😊 Should be quite easy by adapting the existing textfield data-type.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
