### ISSUE TITLE
[Bug]: Web2Print - "active-generate-process": Method Not Allowed

### ISSUE THREAD

**Issue by agendartobias** [pimcore/pimcore#13717]
### Expected behavior

When i want to print some demo catalog from Pimcore Documents i click on the button "Generate PDF" and it get stuck at 0%. In Web-To-Print-Settings test print is OK.

I think it some kind of loop because when i check Network with Chrome debugging tools (F12) i see XHR request that are generating every second - /admin/printpage/active-generate-process

If i open this XHR request i get an error: No route found for "GET https://mydomain.com/admin/printpage/active-generate-process": Method Not Allowed (Allow: POST)

### Actual behavior

When i click on Generate PDF button it shoud generate PDF catalog.

### Steps to reproduce

Pimcore version: 10.5.10 & PHP 8.1.x

**Comment by mattamon** [comment]
Hey @agendartobias,

thank you for your report.
The method not allowed for GET is fine. 
The endless loop on the other hand is not. 
I was able to reproduce it on the official demo https://demo.pimcore.fun/

I will investigate this further.

**Comment by blankse** [comment]
@agendartobias The pdf will be generated with the symfony messenger queue. Is the cronjob process running? See doc:
https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Installation.html#page_5-Maintenance-Cron-Job

In demo this process doesn't run, see:
https://github.com/pimcore/pimcore/issues/10655#issuecomment-947378454
> Regarding demo: our public demo instances do not have the maintenance script running, therefore generating PDFs doesn't work (for the moment).

**Comment by agendartobias** [comment]
Hey, yes i have working maintenance cron job. And still same problem

**Comment by mattamon** [comment]
Hey @agendartobias,

but did you also check the symfony messenger queue? 
It is about this command: 
`*/5 * * * * /your/project/bin/console messenger:consume pimcore_core pimcore_maintenance pimcore_image_optimize --time-limit=300`

You can also debug the queue with `php bin/console debug:messenger`
For more details please see [Messenger: Sync & Queued Message Handling](https://symfony.com/doc/current/messenger.html)

**Comment by dvesh3** [comment]
Closed due to inactivity.
