### ISSUE TITLE
[Bug] Document Types | Predefined Properties translate doesn't work

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#13712]
### Expected behavior

![image](https://user-images.githubusercontent.com/8792145/204780908-581dc6bb-ad2f-4c69-b3ee-0e70c4306535.png)

translate button has function

### Actual behavior

translate button has no function and throws JS error

### Steps to reproduce

klick  button

**Comment by fashxp** [comment]
Same also is for predefined properties

**Comment by kingjia90** [comment]
Fixed by #13745
