### ISSUE TITLE
Many-To-One Relation within a field collection is not saved when triggering workflow when the object is in draft

### ISSUE THREAD

**Issue by flamadrid-jsmdg** [pimcore/pimcore#13736]
### Expected behavior

Having a field-collection that is composed by a localized field that has a Many-To-One and it is used in a data object that has a workflow, I expect an object to be saved after triggering the workflow with an object in draft state. 

### Actual behavior

If an object using the field-collection with a localized Many-To-One relation in a Data Object that is in draft state, after the workflow is triggered, the object relation get's rolled back to the previous last published state, however the other fields are saved correctly. _(Using Pimcore 10.5.11)_

### Steps to reproduce

1. Create a field collection that has 2 localized fields a Text for example and a Many-to-One relation:
<img width="1236" alt="Screenshot 2022-12-05 at 11 32 43" src="https://user-images.githubusercontent.com/94067364/205618325-a32252f6-d783-4d2b-89a2-a7db565657ae.png">

2. Create a data object that uses the previous field collection:
<img width="1100" alt="Screenshot 2022-12-05 at 11 32 01" src="https://user-images.githubusercontent.com/94067364/205618704-1db51288-d69a-4474-ab2c-27c43b908fa9.png">

3. Giving the data object with the initial (published) state:
<img width="1024" alt="Screenshot 2022-12-05 at 11 30 25" src="https://user-images.githubusercontent.com/94067364/205618869-1287e3db-d668-44f2-a37a-4872f8b50982.png">

4. Now, create a new draft by changing Text field to something different and changing the the Many-to-One relation field (Page) to pointing to a different object.
<img width="1090" alt="Screenshot 2022-12-05 at 11 30 49" src="https://user-images.githubusercontent.com/94067364/205619999-1da41fca-cf42-4b5c-a13d-db0dda5d1f2c.png">

5. While the Data object is in draft state, trigger a workflow change.
<img width="1090" alt="Screenshot 2022-12-05 at 11 31 06" src="https://user-images.githubusercontent.com/94067364/205620151-98e2005d-2a6a-4902-8148-ed5818d9dd40.png">

6. After the workflow is triggered, the text field has been saved correctly as "Name 2", however the Many-To-One field relation now points back to the original object rather than the object specified in the draft version.
<img width="1090" alt="Screenshot 2022-12-05 at 11 31 26" src="https://user-images.githubusercontent.com/94067364/205622305-a015ce31-986d-4ac6-8797-73cb700220dd.png">

**Comment by flamadrid-jsmdg** [comment]
I have debugged this but I could not find an explanation it seems when the object get saved after the workflow transition is trigger the Many-To-One relation (when calling $object->save()) does not take on account the draft version, however the text field works well.

**Comment by robertSt7** [comment]
@flamadrid-jsmdg Thanks for reporting the bug. Unfortunately i can't reproduce it. Could you please test it with 10.5.13 again and provide more information like the workflow config? Thanks

**Comment by flamadrid-jsmdg** [comment]
@robertSt7 Hi, below is our workflow config. I'm running locally now **10.5.13** and I tried to strip out all listeners, and custom code. But the issue persists. Note that if I use "Save & Publish" and then trigger the workflow, works as expected.
It is only when you use "Save", that is a new draft is created, and then directly use the workflow that the relation is broken and the case stated in this issue happens. At first I wasn't sure if that this is the actual expected behaviour, but If I test by changing a a simple text field, then it works and with a many to one relation it does not.

[page_workflow.txt](https://github.com/pimcore/pimcore/files/10286311/page_workflow.txt)

**Comment by mattamon** [comment]
Hey @robertSt7, 

I just tried it with the steps above and I can reproduce it on my local machine as well. 
Should I take a look?

**Comment by mattamon** [comment]
@robertSt7, it has something to do with lazy loading.
Problem is, you can't disable the lazy loading for a many-to-one relation in a fieldcollection.
So the data would be correct, but then it is lazy loaded. 
https://github.com/pimcore/pimcore/blob/10.5/models/DataObject/Localizedfield.php#L291 and it seems getById does not get the latest Version.

I tried to load the latest version in here, so it works. But it should also work if we could disable the lazy loading feature for many-to-one relations in fieldcollections.

```php
  /**
   * @return Concrete|null
   */
  public function getObject(): ?Concrete
  {
      if ($this->objectId && !$this->object) {
          $object = Concrete::getById($this->objectId);
          if($object->getLatestVersion()) {
              $object = $object->getLatestVersion()->loadData();
          }
          $this->setObject($object);
      }

      return $this->object;
  }
```

**Comment by fashxp** [comment]
@flamadrid-jsmdg can you please check, if that would fix your problem: #14089
thx

**Comment by flamadrid-jsmdg** [comment]
@fashxp Thanks! I tested the changes locally and #14089 fixes it.

**Comment by fashxp** [comment]
thx for the fast reply!
