### ISSUE TITLE
[Bug]: The UI for chosing objectbrick when adding in object is not responsive

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#13743]
### Expected behavior

Expecting to be able to chose objectbrick even if they are 1000.

### Actual behavior

Not able to chose objectbrick when they a little more as it is outside of the visible screen (viewport), depending on the screen size and the compatible objectbricks count. On these image the last object brick visible is "Visibility" but there are more, they are out of the viewport.

![image](https://user-images.githubusercontent.com/11477130/205737592-3c67b183-92fd-4e6f-8019-c72cb8138f16.png)

You may consider using some kind of search of that UI in order to resolve even better the UX when there are a lot of object bricks.

### Steps to reproduce

Its obvious, you need enough object bricks compatible for given field in order to get them out of the viewport.

**Comment by fashxp** [comment]
Having a very high number of object bricks also has some other implications like creating a lot of tables in the background and potentially doing a lot of joins. The architecture of object bricks is not really meant to have a very high number of them in one data object class. Please also have a look at our [docs](https://pimcore.com/docs/pimcore/current/Development_Documentation/Best_Practice/Object_Bricks_vs_Classification_Store.html). 

We are happy about any ideas and improvements though.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
