### ISSUE TITLE
[Bug][Shared Translations]: WYSIWYG translation not editable

### ISSUE THREAD

**Issue by foxgreek** [pimcore/pimcore#13761]
### Expected behavior

If I use a WYSIWYG translation, it should be editable after saving the translation.

### Actual behavior

Edit Button is missing.

### Steps to reproduce

1. Create a new shared translation in pimcore demo
2. Add WYSIWYG content
3. save edit
4. try to reopen WYSIWYG edit field

https://user-images.githubusercontent.com/40141606/206162786-6dcc41f8-0925-4a39-9d76-1ee17c8093c7.mov

**Comment by dvesh3** [comment]
fixed by #13779
