### ISSUE TITLE
[Improvement]: Being able to locate a node when objects are sorted with custom order

### ISSUE THREAD

**Issue by SamyMP** [pimcore/pimcore#13765]
### Improvement description

I want to be able to change sort order in the tree, under a specific folder. Let's say I have this structure :
![image](https://user-images.githubusercontent.com/35225430/206168127-67170f12-fcb6-43fd-a780-4d6ee95e3895.png)

I want the dataobjects to be sorted alphabetically by brand. The order would be : 
3 - Audi
1 - Mecedes
2 - Renault

To achieve this, I use the [beforeListLoad](https://github.com/pimcore/pimcore/blob/77a80f1a3c61bee064d15fcc1ece929ed0316904/lib/Event/AdminEvents.php#L157) event, in which there is something along these lines : 

```php
// ...

/**
 * @var \Pimcore\Model\DataObject\Listing $list
 */
$list = $e->getArgument('list');
// https://mariadb.com/kb/en/substring_index/
$list->setOrderKey("substring_index(o_key, '-', -1)", false);
```

It works, the list is displayed in the expected order. However, if there are more than 1 page, the tree node locator doesn't work if the item is not on the first page. 

Also, it would be great to be able to change the sort order on an attribute that doesn't necessarily apprears in the key

**Comment by fashxp** [comment]
I think there we would need another event that is fired right after the listing is built. 
We would accept a PR for that.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
