### ISSUE TITLE
[Pimcore4] Issue: [assets]Select folder, select tag, apply  tags to children, children not found

### ISSUE THREAD

**Issue by Yihka** [pimcore/pimcore#1377]
### Expected behavior 
When you log in as a non-admin user, with all rights to tag management, and you want to apply tags to children by selecting the parent folder, the tags should be applied to the children.

### Actual behavior  
When you log in as a non-admin user, with all rights to tag management, and you want to apply tags to children by selecting the parent folder, you get an error saying the children are not found.
  
### Steps to reproduce  
  
1. Create a new user
2. Give the user asset management rights and tag rights.
3. Give the user a workspace in the assets where they can do everything they want.
4. Login as the user
5. Create a folder called A and add a few images to it.
6. Select the folder A and go to the tags tab
7. Select a tag, add a tag if needed.
8. Press the 'apply tags to children' button to apply it.
9. You get an error saying no children are found, while you can view these children with no problem.

### Extra

I've tried to reproduce it on the demo pimcore website first but for some reason I can't assign de tag permissions rightfully to a user. 'tag management' permissions does not work.

**Comment by weisswurstkanone** [comment]
fixed in build 4087
