### ISSUE TITLE
[Feature][Asset] Add permissions for tag, like workspace permissions.

### ISSUE THREAD

**Issue by Yihka** [pimcore/pimcore#1378]
## Feature description 
  
Hey. We'd like to use Pimcore as a DAM. One thing we'll have is multiple customers from different branches. What we currently miss is the ability to give each customer their own tags only they can see. So as example:

Customer A
Tag B
Tag C
Tag D

Customer E
Tag F
Tag G
Tag H

Customer A can only see tag B, C and D and Customer E can see tag F, G and H. This is currently not possible.

A suggestion would be to add a workspace for tags. So we can say, customer can see all tags under Tag A. Basically let it work the same way the folders and files do.

**Comment by brusch** [comment]
Currently we don't have the intention to add permissions on tag level.
