### ISSUE TITLE
[Bug]: Glossary not working with pimcore_wysiwyg content

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#13793]
### Expected behavior

Glossary should work for content from `pimcore_wysiwyg`

### Actual behavior

Glossary not working content from `pimcore_wysiwyg`

### Steps to reproduce

1. Use predefine `wysiwyg` brick, which uses the glossary.
2. Add keywords for Glossary links
3. Open document on frontend.

**Comment by mattamon** [comment]
Maybe this was a temporary issue, I can't reproduce it on my machine and the demo seems to work fine too.

**Comment by dvesh3** [comment]
Sorry, I was using the wrong example. I used the self-reference link example on the document and the glossary processor skips generating the link if the target document is current: https://github.com/pimcore/pimcore/blob/2ce8f9a7e2694b3a5b3f1b7e370dff150fe7cb8c/lib/Tool/Glossary/Processor.php#L115
