### ISSUE TITLE
[Bug]: Checkbox in grid moves down by selection. If a class has a checkbox field, editing will slide that field down the grid instead of checking it in. To check, you have to click on the slipped checkbox again.

### ISSUE THREAD

**Issue by sevarozh** [pimcore/pimcore#13804]
### Expected behavior

When clicking checkbox field in grid, checkbox should be direct checked/unchecked.

### Actual behavior

Checkbox is slid down and only then can it be edited.

### Steps to reproduce

This can easily be reproduced on demo system:
- Add checkbox-Field to class definition
<img width="848" alt="Bildschirmfoto 2022-12-14 um 18 17 38" src="https://user-images.githubusercontent.com/5694627/207686667-caf31559-04fa-43ed-9aab-52556a40059d.png">

- add this field to grid view 
<img width="1144" alt="Bildschirmfoto 2022-12-14 um 18 17 07" src="https://user-images.githubusercontent.com/5694627/207686844-62d66e00-c8af-405b-be9a-d652cbb7c9ef.png">

- click on checkbox field. checkbox is slid down 
<img width="1102" alt="Bildschirmfoto 2022-12-14 um 18 17 19" src="https://user-images.githubusercontent.com/5694627/207687271-f540154d-22fd-466b-be20-bc5f0cb923cf.png">

**Comment by mattamon** [comment]
Closed via #14017
