### ISSUE TITLE
(Pimcore 5) Update not working

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1381]
First of all, a big thumbs up for the new Pimcore 5 wich seems awesome ; ))
And it is really great to have an alpha already very stable!
I wish to thanks all the core team dev which make such a big job on porting it to Symfony 3.

I will report here my first issue, is it the good place ? (i saw a repo pimcore-5-issue is it better to post here ?)

It seems update is not working. I got this error:

Server threw exception - could not perform action. Please reload the admin interface and try again.

```
Status: 500 | Internal Server Error
URL: /admin/update/index/get-available-updates
Message: 

Unable to retrieve response from update server. Please ensure that your server is allowed to connect to update.pimcore.org:443 (500 Internal Server Error)
```

Is it normal because updater is not fully functionnal ?
Thanks!

**Comment by brusch** [comment]
It is fully functional. 
Please ensure that your server is allowed to connect to `liveupdate.pimcore.org:443` (the error message is wrong here, it says `update.pimcore.org`. 

You can verify it by testing the URL https://liveupdate.pimcore.org/getUpdateInfo.php?revision=20
