### ISSUE TITLE
[Improvement]: Prompt a confirmation message when doing a batch modification

### ISSUE THREAD

**Issue by SamyMP** [pimcore/pimcore#13829]
### Improvement description

Currently, when you select a field in the data object grid and select to batch edit it, there is no warning or confirmation message, letting the user potentially modify the entire database, with no option to cancel either

Would you consider prompting a message when the batch modifies more than a certain number (like 25 for example) of data objects ? Something like this : 
![image](https://user-images.githubusercontent.com/35225430/208377404-00b634eb-1992-4277-97be-65ce42e41680.png)

It would pop up after clicking on the save button, which is in the background on this screenshot. The code to achieve this is this one : 

```js
var formPanel = Ext.create('Ext.form.Panel', {
            xtype: "form",
            border: false,
            items: [editor.getLayoutEdit()],
            bodyStyle: "padding: 10px;",
            buttons: [
                {
                    text: t("save"),
                    handler: function () {
                        if (formPanel.isValid()) {
                            if (jobs.length > 25) {
                                Ext.Msg.confirm("Confirmation", `You are about to update <b>${new Intl.NumberFormat(navigator.language).format(jobs.length)}</b> dataObjects.\nDo you want to continue ?`,
                                     (btn) => {
                                        if (btn === "yes") {
                                            this.batchProcess(jobs, append, remove, editor, fieldInfo, true);
                                        } else {
                                            this.batchWin.close()
                                            return;
                                        }
                                    });
                            } else {
                              this.batchProcess(jobs, append, remove, editor, fieldInfo, true);
                            }
                        }
                    }.bind(this)
                }
            ]
        });
```

To be placed [here](https://github.com/pimcore/pimcore/blob/d416f676947f3f98da32f2aec75786afd873ba3d/bundles/AdminBundle/public/js/pimcore/element/helpers/gridColumnConfig.js#L559)

What do you think ?

Edit: This line would go like this to take advantage of translations : 
```js
Ext.Msg.confirm("Confirmation", sprintf(t('batch_confirmation'), `<b>${new Intl.NumberFormat(navigator.language).format(jobs.length)}</b>`),
```

with 
```json
    "batch_confirmation": "You are about to update %s dataObjects. Do you want to continue ?"
```

**Comment by dvesh3** [comment]
Hi @SamyMP, this is a nice improvement as changing the multiple objects with one action should trigger the confirmation dialog first. 

Could you please provide a PR with changes you suggested? thanks!

**Comment by SamyMP** [comment]
I tried to submit the pull request on 10.5 but I still struggle a bit with branches, will try again

**Comment by SamyMP** [comment]
I submitted another pull request to address the fact a user could not cancel a batch edit here #13839
