### ISSUE TITLE
(Pimcore 5) Do not transform 127.0.0.1 to localhost during installation

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1382]
When installing Pimcore 5, i needed to install mariadb and so configure a specific port different than usual one.
So in the installer (web install gui), for the database i gave 127.0.0.1 and the port number.
Install went ok.
But going to /admin bring a database connection error.
In fact the 127.0.0.1 has been transformed in "localhost" in the config file. Problem is with mariadb if you use a specific port, you need to explicitely use 127.0.0.1 and not localhost (if localhost is used it will use socket connection and so going to my already installed oracle mysql).
So i have directly modified the config file to change localhost to 127.0.0.1 and all was working ok after.

I think if user enter 127.0.0.1, it has to be kept as this in the config file and not automaticaly transformed to localhost, so it will prevent this problem (for mysql localhost use socket and 127.0.0.1 use tcp/ip and port).

Thanks.

**Comment by brusch** [comment]
The mysql host isn't converted by the installer routine. 
I've just verified that it isn't the case. Please check `var/config/system.php` after the install - you'll see that the original value from the installer is there.
