### ISSUE TITLE
[Docs] Change perspective and custom view docs to YAML

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#13823]
### Improvement description

currently, they are still in PHP 

https://pimcore.com/docs/pimcore/11.0/Development_Documentation/Objects/Object_Classes/Class_Settings/Custom_Views.html
https://pimcore.com/docs/pimcore/11.0/Development_Documentation/Tools_and_Features/Perspectives.html

**Comment by mcop1** [comment]
Also make sure to include a link (and some words)  to the perspective editor
