### ISSUE TITLE
(Pimcore 5) Check mysql version for requirement

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1383]
I struggle a litte to discover finaly that my sql version was outdated. I know requirement are in documentation.
But as their is a requirement checker in the gui installer, maybe checking DB version could be done ?
At least for best knowed mysql database (oracle mysql, mariadb and percona), if it is not a knowed database system check is bypassed.

It will help people to transit easily to Pimcore 5 (as actually for instance the current stable Debian mysql do not pass the requirement, many people could fall in this problem. Having a requirement check on this will be more explicit for the user than a database sql error...).

**Comment by brusch** [comment]
Hmmm, I'm afraid that this could be quite tricky. 
How to reliably determine which DBMS is used? Eg. Oracle doesn't expose itself as such, so how to implement the bypass?
