### ISSUE TITLE
[Bug]: Adding existing translation results in error in Pimcore admin

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#13860]
### Expected behavior

Adding an existing translation does not result in an error.

### Actual behavior

Error is shown:

![image](https://user-images.githubusercontent.com/9052094/208845119-56ced825-c07c-4899-befa-6ea89832cd89.png)

### Steps to reproduce

1. Open Pimcore Demo /admin
2. Trie to add an already existing translation key

**Comment by dvesh3** [comment]
Fixed by #13866
