### ISSUE TITLE
failed: Permission denied (13)

### ISSUE THREAD

**Issue by GaneshKandu** [pimcore/pimcore#13878]
### Expected behavior

It should work without any error.

### Actual behavior

```
otice: SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php80) failed: Permission denied (13)
```

### Steps to reproduce

install pimcore on CPanel installed server and access admin panel.

### solution

setting following configuration works for this issue.

``config/packages/framework.yaml``
```ini
# config/packages/framework.yaml
framework:
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
```

Is it ok to use this solution ?

**Comment by brusch** [comment]
This seems to be related to your infrastructure ... you don't have sufficient permissions to write sessions to the default location (`php.ini`). 

Changing the config to resolve your issue is of course fine.
