### ISSUE TITLE
[Pimcore 11]: Session Management by Symfony (RoadRunner vs FPM)

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#13876]
### Description

I've been playing around with Roadrunner (https://github.com/roadrunner-server/roadrunner) to see if it works with Pimcore and what the Performance is. Thirst thing that didn't work is: the Admin Session is never passed to the client. Reason for that is that the Managed Worker is basically in a CLI sort of Mode:

RoadRunner PHP:
<img width="429" alt="Screenshot 2022-12-22 at 10 31 06" src="https://user-images.githubusercontent.com/5981845/209103576-4a2e2e7b-f77a-4548-be9c-2cfea97b8dde.png">

FPM:
<img width="403" alt="Screenshot 2022-12-22 at 10 31 10" src="https://user-images.githubusercontent.com/5981845/209103608-3ea01fc9-c74c-4c2e-b58a-650bb5d5ddcd.png">

Therefore the Session ID is not passed to the Client. (https://www.php.net/manual/en/function.headers-list.php#120539, https://www.php.net/manual/en/features.commandline.differences.php) 

This has to be done within the Application.  Symfony handles that: https://github.com/symfony/symfony/blob/v6.2.0/src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php#L106. But only if the Session has been started. Since Pimcore manages the Session itself like here: https://github.com/pimcore/pimcore/blob/b11f2dd51cf89e92cd27bc5cac1b6830a8a78d01/bundles/AdminBundle/src/Session/Handler/AdminSessionHandler.php#L252 

The session is closed already when the Response is sent and the new SessionID is never passed to the Client.

Pimcore 11 should be refactored in terms of Session Management and it should all be handled by Symfony. I don't see the need for why Pimcore does it.

A simpler solution would be to not close the Session and let Symfony handle that, I tested that and it works for RoadRunner and PHP-FPM.

**Comment by dpfaffenbauer** [comment]
Off Topic: I didn't test it with FrankenPHP, but it runs with a different SAPI were it might work already. I find this topic of PHP runtimes quite interesting and it can bring a lot of improvements and advantages to the space.

**Comment by brusch** [comment]
The main reason for having our own session handler is/was session locking, because this results in really bad user experience when working with the Pimcore backend (a lot of parallel requests, e.g. in the tree, ...).

**Comment by dpfaffenbauer** [comment]
You could use database sessions or redis session to overcome that issue.

**Comment by brusch** [comment]
That's of course true, but until now we thought it's best to just use PHP's default ... and ensure it works properly. 
I'm fine with database sessions as the default as well, not sure if it could have some potential unwanted side-effects (performance, ...). Redis can be just an alternative, not the default imho, and you need to consider that it needs a dedicated instance with different config than the cache (not volatile-lru).

**Comment by dpfaffenbauer** [comment]
@brusch We use the same Redis instance for Cache and Session. Both without volatile-lru without issues.

I can make a PR moving the session to DB by default and removing the Pimcore Session Management.

**Comment by brusch** [comment]
@dpfaffenbauer Regarding Redis: well mostly it shouldn't be an issue when using LRU, since session items are usually renewed every so often, but it's not 100% reliable. 

But yes, having DB as the default would be great - looking forward to you PR! 

Merry Christmas!!! 🎄🧑‍🎄

**Comment by dpfaffenbauer** [comment]
Merry Christmas 🎄 to you too :) 🍺 

As well too all Pimconauts out there 🧑‍🚀 🎅

**Comment by brusch** [comment]
@dpfaffenbauer one more thing, ... we need to deprecate all the stuff which is not `@internal` in `10.6` first, such as `\Pimcore\Tool\Session`.

**Comment by dpfaffenbauer** [comment]
@brusch sure, I'll start with the Pimcore 11 part to see what I actually need to remove :D

**Comment by dkarlovi** [comment]
Note about this
> The main reason for having our own session handler is/was session locking, because this results in really bad user experience when working with the Pimcore backend (a lot of parallel requests, e.g. in the tree, ...).

The API requests shouldn't rely on the session being available at all, see #13271.
