### ISSUE TITLE
Pagelock feature not supported in rights/roles configuration?

### ISSUE THREAD

**Issue by mkjn72** [pimcore/pimcore#13891]
### Discussed in https://github.com/pimcore/pimcore/discussions/13650

<div type='discussions-op-text'>

<sup>Originally posted by **mkjn72** November 22, 2022</sup>
I've been searching for a way to configure a role in Pimcore that will allow me to grant the 'lock page' or 'lock page and propagate to children' function to users. Without making them 'admin'.

![image](https://user-images.githubusercontent.com/68860845/203290499-b5e3066d-1a81-417e-aa41-50e2d08621f4.png)

Either I'm looking in the wrong place or this is not supported in Pimcore X (yet)? Any help/pointers appreciated</div>

**Comment by mattamon** [comment]
@mkjn72 please check my answer #13650

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
