### ISSUE TITLE
[Bug]: Direct SQL query button is not visible

### ISSUE THREAD

**Issue by Maksonis** [pimcore/pimcore#13905]
### Expected behavior

See direct SQL query button in DataObjects grid:

![image](https://user-images.githubusercontent.com/17277953/209543879-3af110c5-b56f-4651-966e-04d4c8e29ced.png)

### Actual behavior

Direct SQL query button is not visible in DataObjects grid:

![image](https://user-images.githubusercontent.com/17277953/209543973-42c02db9-7f73-4307-b289-996962be4c68.png)

### Steps to reproduce

Click on any folder in DataObjects.

**Comment by SamyMP** [comment]
Hi,

I don't know which version of Pimcore you are using, but if you are using the alpha / Pimcore 11, it was removed, see this [pull request](https://github.com/pimcore/pimcore/pull/13395)

**Comment by Maksonis** [comment]
Hi, but should be available in latest 10.5. version, right ? I am using 10.5.13.

**Comment by dpfaffenbauer** [comment]
@Maksonis Are you full admin?

**Comment by Maksonis** [comment]
@dpfaffenbauer that's the catch, since superuser on pimcore live demo is not full admin. The thing is that direct SQL condition is not taken into account when do exports. E.g. I have four results:

![image](https://user-images.githubusercontent.com/17277953/209632382-fa92714b-9e7d-40a0-a1f1-74b54232c032.png)

and get 20 in exports

![image](https://user-images.githubusercontent.com/17277953/209632445-4ff2711d-666f-487d-949b-bcf3afda7536.png)

Wanted to check it on live demo to be sure.

**Comment by fashxp** [comment]
use demo.pimcore.fun, there admin is full admin.

**Comment by Maksonis** [comment]
@fashxp thanks, my issue is fixed by: https://github.com/pimcore/pimcore/pull/13663. After updating pimcore to latest 10.5. version everything works as expected.
