### ISSUE TITLE
Revisit Bundle Class Naming Schema

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#13912]
### Improvement description

Currently the naming schema could be a bit confusing, since we're using
`\Pimcore\Bundle\CoreBundle\PimcoreCoreBundle`  instead of `\Pimcore\Bundle\CoreBundle\CoreBundle` so we have this extra `Pimcore` prefix. 

Imho this is just redundant and not consistent, so we should remove this extra prefix.

**Comment by dpfaffenbauer** [comment]
Good reason for this is that if another bundle comes along with name "CoreBundle", the suffix is the same. CoreShop also names all Bundles as `CoreShopCoreBundle` or `CoreShopIndexBundle`. Reason also is the Symfony configuration "namespace" as `core_shop_core` or `core_shop_index`. 

I think it is fine that the Pimcore Bundles are prefixed with Pimcore.

**Comment by brusch** [comment]
I was just wondering, because Symfony does not use this schema. But the config root node name makes sense yes ... 🤔

**Comment by dvesh3** [comment]
Symfony suggests to use the prefix in bundle class name. please see https://symfony.com/doc/current/bundles/best_practices.html#bundle-name

**Comment by brusch** [comment]
@dvesh3 thanks for clarifying - so we leave everything as it is and consider it for all the new bundle classes. 
@pimcore/dev-team
