### ISSUE TITLE
[DOCS] AWS Setup

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1392]
_From @brusch on March 22, 2017 15:45_

- archtecture recommendation (EC2, EFS, S3, CloudFront, Aurora, ...) 
- S3 Storage example for assets, ... 
- CloudFront Setup

... see v4 docs 

_Copied from original issue: pimcore/pimcore-5-issues#30_

**Comment by Yivan** [comment]
Just a suggestion: maybe setup for Google Cloud Plateform could be added as it is more and more used (not at the same level than AWS for sure, but many people tend to swith to GCP for simplicity, lower price, Kumbertenes containers, etc.).

Always on arhitecture, I know it is new, but making a page about container/docker implementation could be great. I saw there is a Pimcore Docker available: https://hub.docker.com/r/pimcore/docker-pimcore-demo-standalone/~/dockerfile/
I think it has been done as this for simplicity installation for testing purpose, but it break stateless principles and manage multiple process in one container (normally to be scalable you have to have one process per container).
A new page on documentation for Docker, with multiple container by using services and docker-compose.yml (https://docs.docker.com/get-started/part3/#about-services) could be great. As Pimcore 5 can be installed/manager better from command line/composer it will make it fesable.

**Comment by brusch** [comment]
S3 was done by #2755
[CloudFront](https://pimcore.com/docs/4.6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Amazon_AWS_Setup/Amazon_AWS_Cloudfront_CDN_Setup.html) and [overview page](https://pimcore.com/docs/4.6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Amazon_AWS_Setup/index.html) is still missing
