### ISSUE TITLE
[Bug]: Pimcore ^10.5 and Twig 3.5.0 (First install)

### ISSUE THREAD

**Issue by Pierre-Datasolution** [pimcore/pimcore#13939]
### Expected behavior

Just after basic install, I should get http://127.0.0.1/admin

### Actual behavior

I get a Twig exception

### Steps to reproduce

Basic install from scratch of Pimcore 10.5.13
Since 2 days, twig/twig now has a 3.5.0 version that is installed during 'composer install'
Played twice, reproduced twice !

Notice : When downgrading to twig/twig 3.4.3, no exception even if upgrading to 3.5.0 (seems the error is only at first launch of Pimcore... init ?)

![image](https://user-images.githubusercontent.com/43100677/210054857-1bb50305-2c09-48a6-8cf1-f5fd12c7f8db.png)

![image](https://user-images.githubusercontent.com/43100677/210057499-ad5904e8-5032-4399-a9ec-695036c2fce2.png)

**Comment by kingjia90** [comment]
Thank you for the report, but i have to close it, because it was [already covered ](https://github.com/pimcore/skeleton/issues/130) in the Pimcore skeleton repository.
The solution proposed on https://github.com/pimcore/skeleton/pull/131 should fix this, feel free to re-open if that doesn't work
