### ISSUE TITLE
[Bug]: 10.5.13 In Classification Store and Detailed Configuration of the key, in "Select" fields you can save values out of the dictionary

### ISSUE THREAD

**Issue by krzysztofkowalski1** [pimcore/pimcore#13949]
### Expected behavior

Path: Classification Store / Key Definition / Key Detailed Configuration

In the "Select" type fields, values out the dictionary mustn't be saved - additional validation is needed

### Actual behavior

Path: Classification Store / Key Definition / Key Detailed Configuration

In the "Select" type fields, values out the dictionary can be saved.

### Steps to reproduce

1. Go to https://demo.pimcore.com/admin/

2. Go to Settings / Data Objects / Classification Store / ProductAttributes / Key Definitions

3. Find any "Quantity Value" key, i.e. "height" and open it's "Detailed Configuration"

4. In "Default unit" field enter i.e. "Test"

![image](https://user-images.githubusercontent.com/121801378/210230867-9f0f37b8-83f2-4692-b550-fe8511f984be.png)

5. Click "Apply"

6. Open again "Detailed Configuration" of the "height" key

7. In "Default unit" field "Test" value, which is not in the related dictionary, has been saved

![image](https://user-images.githubusercontent.com/121801378/210231245-4698b8c1-5423-42b0-a1f2-2714040a1410.png)

This is just an example. The same happens to the custom "Select" fields added to "Detailed Configuration" in my project.

**Comment by lukmzig** [comment]
Hi @krzysztofkowalski1,
thank you for reporting this problem. Can you have a look at the pull request https://github.com/pimcore/pimcore/pull/14060 if this resolves your issue?
