### ISSUE TITLE
[Bug]:  self::checkMaxPixels can result in files not being suppressed from temporary folders

### ISSUE THREAD

**Issue by pimcore-galilee** [pimcore/pimcore#13969]
### Expected behavior

When self::checkMaxPixels($tmpFile, $data) throws an exception, temp file must be suppressed from PIMCORE_SYSTEM_TEMP_DIRECTORY 

### Actual behavior

the temporary file might not be deleted if an exception is rised.

### Steps to reproduce

use Asset:create() function on a file with a lot of pixels that would be greater from defaut number of max pixels. File will not be suppressed from  PIMCORE_SYSTEM_TEMP_DIRECTORY folder resulting after a batch of a lot of files creation to have no space left on device.

**Comment by dvesh3** [comment]
Fixed by #14012
