### ISSUE TITLE
[Newsletter] add new way to inject custom Address Source Adapter

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1397]
_From @fashxp on March 28, 2017 13:7_

via services or same way like to add custom data types... 
https://github.com/pimcore/pimcore-5/blob/symfony/doc/Development_Documentation/03_Documents/02_Document_Types/05_Newsletter_Documents.md#creating-a-custom-address-source-adapter

_Copied from original issue: pimcore/pimcore-5-issues#55_

**Comment by maff** [comment]
Implemented in #1952 / #1957
