### ISSUE TITLE
[Bug]: Advanced Relation Many-Many Error

### ISSUE THREAD

**Issue by torqdev** [pimcore/pimcore#13979]
### Expected behavior

Allow adding advanced many-many with no errors.

### Actual behavior

When adding a new advanced many-many relation we get type errors.

`Message: Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectHelperController::getDefaultGridFields(): Argument #4 ($noBrickColumns) must be of type bool, string given, called in /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectHelperController.php on line 371`

![image](https://user-images.githubusercontent.com/67965755/210596498-d0a45421-e721-4ac6-85f6-5dff88384069.png)

### Steps to reproduce

1. Checkout `11.x` branch or go to `11.x` demo site (https://11.x-dev.pimcore.fun/admin/)
2. Add `Advanced Many-To-Many Object Relation`
3. Error above will appear

**Comment by blankse** [comment]
@torqdev I created a PR https://github.com/pimcore/pimcore/pull/13981

**Comment by torqdev** [comment]
Thanks @blankse. Will close our PR.
