### ISSUE TITLE
[Bug]: Error message for duplicate URL slug is not helpful

### ISSUE THREAD

**Issue by woellundwoell** [pimcore/pimcore#13984]
### Steps to reproduce

Prerequisites: You have an object class that contains a URL Slug field (let's call it "exampleSlug"). 

One object has a certain value set for the slug. On a different object you want to set the same value for the slug. This produces an error message, which is of course correct.

### Actual behavior

The error message reads: "Unique constraint violated. Slug alreay used by object exampleSlug, fieldname: exampleSlug."

### Expected behavior

The error message should read: "Unique constraint violated. Slug alreay used by object [id], fieldname: exampleSlug."

**Comment by kingjia90** [comment]
also need to fix typo `alreay` ->`is already`

**Comment by kingjia90** [comment]
Resolved by #13987
