### ISSUE TITLE
[Controller] should we make website config available in controller again with $this->config?

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1398]
_From @fashxp on March 28, 2017 13:17_

see https://github.com/pimcore/pimcore-5/blob/symfony/doc/Development_Documentation/08_Tools_and_Features/27_Website_Settings.md#example-in-a-controller 

otherwise add to change notes and remove docs

_Copied from original issue: pimcore/pimcore-5-issues#61_

**Comment by dpfaffenbauer** [comment]
If you can ensure that it works for all document related stuff, including email and multi-sites, I would give this feature a thumbs up.

**Comment by maff** [comment]
Is there a benfit over just calling `Pimcore\Config::getWebsiteConfig()`? I'd rather avoid adding more "magic" controller properties than really needed (as we do now with `document`, `view`, and `editmode` on the `FrontendController`).

**Comment by maff** [comment]
Implemented in https://github.com/pimcore/pimcore/pull/1854
