### ISSUE TITLE
[CustomReports] add new way to inject custom Data Source Adapters

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1399]
_From @fashxp on March 28, 2017 13:18_

see https://github.com/pimcore/pimcore-5/blob/symfony/doc/Development_Documentation/08_Tools_and_Features/29_Custom_Reports.md#custom-data-source-adapters

_Copied from original issue: pimcore/pimcore-5-issues#62_

**Comment by maff** [comment]
Implemented in #1960
