### ISSUE TITLE
[Bug][Pimcore 11][Objects] Advanced many-to-many object relation tag mode not working or doesn't make sense at all

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#13993]
### Expected behavior

regression of #13227

Currently tag mode can be selected and it is not working. 
Actually for advanced many-to-many object relation, tag mode does not really make sense, as there is no possibility to edit the additional columns

### Actual behavior

```
Status: 500 | Internal Server Error
URL: /admin/object/relation-objects-list?_dc=1672928472754
Method: GET
Message: Too few arguments to function Pimcore\Model\DataObject\AbstractObject::get(), 0 passed in /var/www/html/dev/pimcore/pimcore/bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectController.php on line 613 and at least 1 expected
Trace: 
in /var/www/html/dev/pimcore/pimcore/models/DataObject/AbstractObject.php:1066
#0 /var/www/html/dev/pimcore/pimcore/bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectController.php(613): Pimcore\Model\DataObject\AbstractObject->get()
#1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(163): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->optionsAction(Object(Symfony\Component\HttpFoundation\Request))
#2 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#3 /var/www/html/vendor/symfony/http-kernel/Kernel.php(184): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#5 {main}
```

### Steps to reproduce

- create data object class with advanced many-to-many object relation in tag mode
- create object of that class and try to save

**Comment by brusch** [comment]
@BlackbitDevs since this PR was originally created by you, can you make have a look at this issue? Thanks in advance!

**Comment by BlackbitDevs** [comment]
Ok, will remove tag mode from advanced m2m object relation as @fashxp is right:
> Actually for advanced many-to-many object relation, tag mode does not really make sense, as there is no possibility to edit the additional columns

**Comment by fashxp** [comment]
@BlackbitDevs any chance you can provide that until Wednesday for the next alpha release?
