### ISSUE TITLE
[Bug]: Keybindings with CTRL,ALT combination not working properly 

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#13994]
### Expected behavior

The combination of modifiers (<kbd>ALT,CTRL</kbd>) in keybindings would work without overlapping

As default, for example:
<kbd>ALT + O</kbd> to open `Search Object`
<kbd>CTRL + ALT + O</kbd> to open `HTTP Errors`

### Actual behavior

<kbd>CTRL + ALT + O</kbd> opens both `HTTP Errors` and `Search Object` at the same time

### Steps to reproduce

After login, press this hotkey combination <kbd>CTRL + ALT + O</kbd> or any combination that exists with <kbd>ALT + something</kbd> and <kbd>CTRL + ALT + something</kbd>

**Comment by mattamon** [comment]
In pimcore 11 this will shift to the config. 
https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/config/pimcore/default.yaml

We would just need to make all keys like ctrl, shift and alt required to overcome this issue.

**Comment by dvesh3** [comment]
Fixed by #14014
