### ISSUE TITLE
[Bug]: Main Site robots.txt is saved as robots.txt-0 in settingsstore

### ISSUE THREAD

**Issue by mattamon** [pimcore/pimcore#14005]
### Expected behavior

Main Site robots.txt will be saved as robots.txt-default in settingsstore.
The robots.txt will work as intended.

This behaviour changed with type fix [PR](https://github.com/pimcore/pimcore/commit/92da8b98e56ef80ddf4e5cefa5fdb78b7af999f9#diff-d8a9d98ddf01d40976e2f54e4ed4c36bdd81218f67107385e81f3947911b7828R1044)

### Actual behavior

Main Site robots.txt is saved as robots.txt-0 in settingsstore.

If there is an upgrade from 10 to 11 the robots.txt for the Main Site will stop working without saving it again.

### Steps to reproduce

Open robots.txt editor and save the robots.txt for the Main Site. Check the settingsstore entry in the database.

A migration is needed or changing the id back to "default"

**Comment by mattamon** [comment]
We found this behaviour while reviewing the PimcoreSeoBundle extraction.
https://github.com/pimcore/pimcore/pull/13851#discussion_r1064388154

```php
 $siteId = SiteId::forMainDomain();
```
The [SiteId](https://github.com/pimcore/pimcore/blob/11.x/lib/Analytics/SiteId/SiteId.php#L43) class uses "default" as the config key for the main domain, but this key does not reference the id.

The Portalcontroller uses the id but here the id for the main_site is 0 since 2017
https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/src/Controller/Admin/PortalController.php#L396

We should change the `$siteId` in PublicServicesController too for the robots.txt
https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/src/Controller/PublicServicesController.php#L205

Slugs for DataObjects should also be fine since the Id is 0
https://github.com/pimcore/pimcore/blob/11.x/lib/Routing/Dynamic/DataObjectRouteHandler.php#L64

The Config should also be fine I guess altough we could change it to 0 instead too, same goes for the Router in the Staticroutes and the Redirect Dao
https://github.com/pimcore/pimcore/blob/11.x/lib/Config.php#L197
https://github.com/pimcore/pimcore/blob/11.x/lib/Routing/Staticroute/Router.php#L126
https://github.com/pimcore/pimcore/blob/11.x/models/Redirect/Dao.php#L61

**Comment by aashan10** [comment]
Saw similar behavior in Marketing Settings as well. Previously, the marketing settings were being saved under `reports` id in setting store and had JSON like
```
{
  "analytics": {
    "sites": {
      "site_default": {
        "profile": "",
        "trackid": "",
        "gtagcode": false,
        "asynchronouscode": false,
        "retargetingcode": false,
        "additionalcode": "",
        "additionalcodebeforepageview": "",
        "additionalcodebeforeinit": "",
        "accountid": "",
        "internalid": "",
        "universal_configuration": ""
      }
    }
  },
  "tagmanager": {
    "sites": {
      "site_default": {
        "containerId": "abcde"
      }
    }
  },
  "webmastertools": {
    "sites": {
      "site_default": {
        "verification": ""
      }
    }
  }
}
```

But now I am seeing something like this 
```
{
  "analytics": {
    "sites": {
      "site_0": {
        "profile": "",
        "trackid": "",
        "gtagcode": false,
        "asynchronouscode": false,
        "retargetingcode": false,
        "additionalcode": "",
        "additionalcodebeforepageview": "",
        "additionalcodebeforeinit": "",
        "accountid": "",
        "internalid": "",
        "universal_configuration": ""
      }
    }
  },
  "tagmanager": {
    "sites": {
      "site_0": {
        "containerId": "abcde"
      }
    }
  },
  "webmastertools": {
    "sites": {
      "site_0": {
        "verification": ""
      }
    }
  }
}
```
