### ISSUE TITLE
[Bug]: Tabs don't automatically switch to the currently selected object

### ISSUE THREAD

**Issue by judip** [pimcore/pimcore#14004]
### Expected behavior

If we have a lot of tabs open (more than fits on the screen), when the next tab is opened, they move to the currently selected object.

### Actual behavior

If we have a lot of tabs open (more than fits on the screen), when we open another tab, we have to move the tabs yourself using the arrow.

### Steps to reproduce

Open a lot of tabs (more than fits on the screen) and then open next and next tab.

**Comment by lukmzig** [comment]
Hello @judip, thank you for reporting this issue. Unfortunately I was not able to reproduce it but maybe I missed something. 

- Is this also happening in our demo? https://demo.pimcore.com/admin/
- Are we talking about opening DAO detail views? For me always the latest object I clicked on in the tree was open and tab listed as active.

**Comment by lukmzig** [comment]
Issue closed due to inactivity.
