### ISSUE TITLE
[Bug]: Mime type error when uploading a new image in ImageGallery object

### ISSUE THREAD

**Issue by Schubie** [pimcore/pimcore#14003]
### Expected behavior

Upload new image at imageGallery directly. 

### Actual behavior

Pimcore throws an error:

`
{"success":false,"message":"Mime type does not match with asset type: hotspotimage"}`

### Steps to reproduce

Add a new element in object imageGallery. Click on Hamburger-Menu and upload a new image. 
This happens on official pimcore demo site, too.

**Comment by mattamon** [comment]
@Schubie than you for reporting this. I could reproduce it on the demo version. We will fix it asap.

**Comment by dvesh3** [comment]
Fixed by #14007
