### ISSUE TITLE
[Docs] start with doc/Development_Documentation/09_Development_Tools_and_Details/13_Debugging.md

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1400]
_From @fashxp on March 28, 2017 13:22_

maybe a good point to start with this page :-) 

_Copied from original issue: pimcore/pimcore-5-issues#66_

**Comment by fashxp** [comment]
see https://pimcore.com/docs/5.0.x/Development_Documentation/Development_Tools_and_Details/Debugging.html
