### ISSUE TITLE
[Docs]: Reverse Object Relation Type | Wrong / unclear documentation

### ISSUE THREAD

**Issue by hethehe** [pimcore/pimcore#14001]
### Expected behavior

Documentation should define why the descriped way is the "best way".

### Actual behavior

At least for me it's unclear why this is the best way.

### Steps to reproduce

https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Reverse_Object_Relation_Type.html#page_Working-with-PHP-API

Why do we have to use:
```
$def = $object->getClass()->getFieldDefinition("myNonOwnerObjectField");
$refKey = $def->getOwnerFieldName();
$refId = $def->getOwnerClassId();
$nonOwnerRelations = $object->getRelationData($refKey, false, $refId);
```
which returns an array with the object id's instead of
```
$object->getMyNonOwnerObjectField()
```
which returns an array with the objects?

**Comment by blankse** [comment]
@hethehe The getter method was added in Pimcore 10.4. see https://github.com/pimcore/pimcore/pull/10242

Yes the docs are outdated, this was the old way without this getter method. Can you create a PR?
