### ISSUE TITLE
Move translations from CoreBundle to AdminBundle

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#14038]
### Improvement description

As most translations in the core bundle are used by the admin bundle they should be moved to the bundle they belong to 😉

**Comment by kingjia90** [comment]
not sure if #14185 is right, everything got moved beside 3 lines https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/translations/admin.en.yaml?

**Comment by aryaantony92** [comment]
Yes, because there was only these 3 translations used in the core bundle.

**Comment by kingjia90** [comment]
ahh ok then, that surprised me a little bit
