### ISSUE TITLE
[Bug]: document tree broken after adding a site

### ISSUE THREAD

**Issue by langert** [pimcore/pimcore#14044]
### Expected behavior

document tree is shown

### Actual behavior

document tree fails

### Steps to reproduce

convert a document page as a site and save. document tree is broken.
deleting the row in db in table "sites". document tree is shown up correctly as before.

`
Status: 500 | 
URL: /admin/document/tree-get-childs-by-id?_dc=1673473738065
Method: GET
Message: The "Symfony\Contracts\Translation\TranslatorInterface" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
Trace: 
in /var/www/html/www/cms/pimcore/vendor/symfony/dependency-injection/Container.php:257
#0 /var/www/html/www/cms/pimcore/vendor/symfony/dependency-injection/Container.php(219): Symfony\Component\DependencyInjection\Container->make('Symfony\\Contrac...', 1)
#1 /var/www/html/www/cms/pimcore/vendor/pimcore/pimcore/models/Element/AdminStyle.php(100): Symfony\Component\DependencyInjection\Container->get('Symfony\\Contrac...')
#2 /var/www/html/www/cms/pimcore/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Traits/AdminStyleTrait.php(37): Pimcore\Model\Element\AdminStyle->__construct(Object(Pimcore\Model\Document\Page))
#3 /var/www/html/www/cms/pimcore/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Traits/DocumentTreeConfigTrait.php(105): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\DocumentController->addAdminStyle(Object(Pimcore\Model\Document\Page), 1, Array)
#4 /var/www/html/www/cms/pimcore/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/DocumentController.php(215): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\DocumentController->getTreeNodeConfig(Object(Pimcore\Model\Document\Page))
#5 /var/www/html/www/cms/pimcore/vendor/symfony/http-kernel/HttpKernel.php(163): Pimcore\Bundle\AdminBundle\Controller\Admin\Document\DocumentController->treeGetChildsByIdAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#6 /var/www/html/www/cms/pimcore/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#7 /var/www/html/www/cms/pimcore/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /var/www/html/www/cms/pimcore/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#9  #{main}`

**Comment by jdreesen** [comment]
Aah, the good old "TranslatorInterface service or alias has been removed or inlined" error that nobody knows where it comes from.

See #10952, #11344, #12041, #12300

**Comment by langert** [comment]
thx! hm, did not find all these issues before... sorry

Defined as service =>

Symfony\Contracts\Translation\TranslatorInterface: '@Pimcore\Translation\Translator'

worked for me. But only if I set service defaults to public:true. Could @Pimcore\Translation\Translator set public without setting the default to public?

**Comment by dvesh3** [comment]
It is public https://github.com/pimcore/pimcore/blob/10.5/bundles/CoreBundle/Resources/config/aliases.yaml#L13

**Comment by langert** [comment]
in my service.yaml I had ;-)

_defaults:
  public: false

**Comment by jdreesen** [comment]
But the `_defaults:` are scoped to the current file, as far as I know.

**Comment by mattamon** [comment]
@langert so you did overwrite the service in your services.yaml? 
Because as shown before it should be defined in the aliases.yaml in the CoreBundle already.
https://github.com/pimcore/pimcore/blob/10.5/bundles/CoreBundle/Resources/config/aliases.yaml#L13

As @jdreesen mentioned _defaults only scoped to the current file -> https://symfony.com/doc/current/service_container.html#service-container-services-load-example

Can you please check if your aliases.yaml is correct?

**Comment by langert** [comment]
@mattamon yes, I set the alias in my service.yaml and there I have a _defaults setting as public:false

**Comment by mattamon** [comment]
@langert but why do you set it in your services yaml? 
Like I mentioned it should already be in Pimcore itself: https://github.com/pimcore/pimcore/blob/10.5/bundles/CoreBundle/Resources/config/aliases.yaml#L13

**Comment by langert** [comment]
@mattamon yes, in the coreBundle I can see the alias to be set. But if I do not set it as an alias in config/aliases.yaml or my own service.yaml in my bundle, I get the error. But in my service.yaml there is no other initial setting or overwriting for Symfony\Contracts\Translation\TranslatorInterface

**Comment by mattamon** [comment]
Hmm okay, like in all other issue this is a really strange behaviour. Which pimcore version are you using?

**Comment by langert** [comment]
I updated to 10.5.14 when the error occured, but that did not resolve it

**Comment by mattamon** [comment]
Have you seen this comment? https://github.com/pimcore/pimcore/pull/12041#discussion_r867312266

**Comment by langert** [comment]
yes, i got the same response:
![grafik](https://user-images.githubusercontent.com/11093410/212684866-30215cd4-6f12-4571-90eb-7e2539985829.png)

After setting it as alias on my own, i got:

![grafik](https://user-images.githubusercontent.com/11093410/212685102-cb53ef77-0988-4c25-89d7-1f2f998a8db3.png)

**Comment by mattamon** [comment]
Have you also seen the comment below? 
`My fault - removed Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true] from bundles.php after Symfony flex installation and everything is fine. Otherwise aliases.yaml ist not loaded.`

**Comment by langert** [comment]
yes, but did not really know how to interpret it...
I have a definition

`Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],`

in my bundles.php and did not touch/remove this.

**Comment by mattamon** [comment]
Hmm okay can you try to add some characters to the https://github.com/pimcore/pimcore/blob/10.5/bundles/CoreBundle/Resources/config/aliases.yaml so it is invalid yaml to check if the aliases are even loaded, because it doesn't seem to be the case.

**Comment by langert** [comment]
adding a syntax error to the alias.yaml and calling the command cache:clear shows up the syntax error correctly

In Parser.php line 459:
                                                                                                                                            
  Unable to parse in "/var/www/html/xxxxx/pimcore/vendor/pimcore/pimcore/bundles/CoreBundle/DependencyInjection/../Resources/config/alia  
  ses.yaml" at line 1 (near " services:").

**Comment by jdreesen** [comment]
And what happens if you remove the line `Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],` from your `bundles.php`?

**Comment by langert** [comment]
if I remove the lines in bundles.php and do not set the alias on my own, the error is solved!

**Comment by jdreesen** [comment]
As far as I know, the `FrameworkBundle` is already loaded in the Pimcore Kernel. It seems like it's not good to also load it (later) in your app.

I could imagine what's happening is that it's loaded by Pimcore, then the service is made public, and then it's loaded in your project and this makes it private again.

**Comment by langert** [comment]
thx for your support!
