### ISSUE TITLE
[Bug]: Cropped image auto generated name fails

### ISSUE THREAD

**Issue by TobiSW** [pimcore/pimcore#14054]
### Expected behavior

Set up a thumbnail config item as a closure. Crop the image in an image editable and dont receive a serialization error.

### Actual behavior

Setting up an thumbnail config item as an closure and cropping the image in an image editable throws the following exception:

Serialization of 'Closure' is not allowed File: /var/www/html/vendor/pimcore/pimcore/lib/Tool/Serialize.php Line: 32

### Steps to reproduce

1. Setup thumbnail config item as closure. For Example:
As it is possible => https://github.com/pimcore/pimcore/blob/11.x/models/Asset/Image/Thumbnail/Processor.php#L400
```
  $items = $config->getItems();
  $items[] = [
      'method' => function ($image) {
          if (method_exists($image, 'copyrightDisclaimer')) {
              $image->copyrightDisclaimer();
          }
      },
      'arguments' => [],
  ];
  $config->setItems($items);
```

3. Crop one image in an image editable:
4. https://github.com/pimcore/pimcore/blob/11.x/models/Document/Editable/Image.php#L267 creates the exception as the serialization fails for an closure

**Comment by aashan10** [comment]
@TobiSW as far as I know, php does not support serialization of methods.

In your case, you can instead do something like 
```
function addCopyrightDisclaimer($image) {
    if (method_exists($image, 'copyrightDisclaimer')) {
        $image->copyrightDisclaimer();
    }
}

```

and now instead of passing anonymous function in the method array, you can pass the name of the function to be called.

Something like:
```

$items = $config->getItems();
  $items[] = [
      'method' => 'addCopyrightDisclaimer',
      'arguments' => [
           $image
      ],
  ];
  $config->setItems($items);
```

This should work.

**Comment by dvesh3** [comment]
This feature is deprecated with [v10.6](https://github.com/pimcore/pimcore/pull/14226) and will be removed in [v11](https://github.com/pimcore/pimcore/pull/14434). 

If you would like to temporarily fix the issue then you can use this [patch](https://github.com/pimcore/pimcore/commit/ad57c242b3dda338c7cf4f614933ac0a8fa0f652.patch) with latest version of `opis/closure`.

**Comment by TobiSW** [comment]
thank you for this update @dvesh3 . Fine for us
