### ISSUE TITLE
[Object Classes] - Export

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1406]
_From @dpfaffenbauer on April 4, 2017 16:14_

Exporting Object Classes results in an Error:

Webservice\Data\Mapper: Cannot map [ Object\ClassDefinition\Data\Localizedfields ] - class does not exist

```
Stack Trace
in pimcore/models/Webservice/Data/Mapper.php at line 93   -
                    $object = $new;
                }
            } else {
                throw new \Exception("Webservice\\Data\\Mapper: Cannot map [ $apiclass ] - class does not exist");
            }
        } elseif (is_array($object)) {
            $tmpArray = [];
at Mapper ::map (object(Localizedfields), 'Object\\ClassDefinition\\Data\\Localizedfields', 'out') 
in pimcore/models/Webservice/Data.php at line 53   + 
at Data ->map (object(ClassDefinition)) 
in pimcore/models/Webservice/Data/ClassDefinition.php at line 125   + 
at ClassDefinition ->map (object(ClassDefinition), null) 
in pimcore/models/Webservice/Data/Mapper.php at line 89   + 
at Mapper ::map (object(ClassDefinition), '\\Pimcore\\Model\\Webservice\\Data\\ClassDefinition\\Out', 'out') 
in pimcore/models/Object/ClassDefinition/Service.php at line 33   + 
at Service ::generateClassDefinitionJson (object(ClassDefinition)) 
in pimcore/lib/Pimcore/Bundle/PimcoreAdminBundle/Controller/Admin/ClassController.php at line 533   + 
at ClassController ->exportClassAction (object(Request)) 
at call_user_func_array (array(object(ClassController), 'exportClassAction'), array(object(Request))) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 153   + 
at HttpKernel ->handleRaw (object(Request), 1) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 68   + 
at HttpKernel ->handle (object(Request), 1, true) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php at line 168   + 
at Kernel ->handle (object(Request)) 
in web/app.php at line 21   + 
```

_Copied from original issue: pimcore/pimcore-5-issues#95_

**Comment by weisswurstkanone** [comment]
Unable to reproduce with the demo "news" class

**Comment by dpfaffenbauer** [comment]
strange... happens with every class on my installation.

inquiry class: Webservice\Data\Mapper: Cannot map [ Object\ClassDefinition\Data\Datetime ] - class does not exist
news class: Webservice\Data\Mapper: Cannot map [ Object\ClassDefinition\Data\Image ] - class does not exist
person class: Webservice\Data\Mapper: Cannot map [ Object\ClassDefinition\Data\Checkbox ] - class does not exist

I will try to debug it and give you more about this.

**Comment by dpfaffenbauer** [comment]
Pimcore\Model\Webservice\Data\Mapper:63

changing from:
```
$apiclass = $orgclass;
```

to

```
$apiclass = get_class($object);
```

fixes the issue. I guess thats an autoloader problem.

Maybe a good hint: I disabled the Zend Backward Compatibility Bundle. It seems like it adds include paths, therefore the class can be found.

Anyway: 'Object\ClassDefinition\Data\Datetime' shouldn't be used anymore, shouldn't it?
