### ISSUE TITLE
[Bug]: Saving of select value in Block > Field Collection > Block produce 500 | Internal Server Error

### ISSUE THREAD

**Issue by svenkovhd** [pimcore/pimcore#14072]
### Expected behavior

To be saved value in the select of the Class Instance.

I tried it in the https://demo.pimcore.fun/admin/ and error is available. 

### Actual behavior

Got error:

Status: 500 | Internal Server Error
URL: /admin/object/get
Message: 
{"success":false,"message":"Call to a member function getData() on string"}
Fatal error:  Uncaught Error: Call to a member function getData() on string in /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Block.php:823
Stack trace:
#0 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Fieldcollections.php(418): Pimcore\Model\DataObject\ClassDefinition\Data\Block->getCacheTags(Array, Array)
#1 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Block.php(825): Pimcore\Model\DataObject\ClassDefinition\Data\Fieldcollections->getCacheTags(Object(Pimcore\Model\DataObject\Fieldcollection), Array)
#2 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Concrete.php(364): Pimcore\Model\DataObject\ClassDefinition\Data\Block->getCacheTags(Object(Pimcore\Model\DataObject\Fieldcollection), Array)
#3 /var/www/html/vendor/pimcore/pimcore/lib/Cache/Core/CoreCacheHandler.php(472): Pimcore\Model\DataObject\Concrete->getCacheTags(Array)
#4 /var/www/html/vendor/pimcore/pimcore/lib/Cache/Core/CoreCacheHandler.php(907): Pimcore\Cache\Core\CoreCacheHandler->prepareCacheTags('object_1189', Object(Pimcore\Model\DataObject\ClassWithFieldCollectionInBlock), Array)
#5 /var/www/html/vendor/pimcore/pimcore/lib/Cache/Core/CoreCacheHandler.php(960): Pimcore\Cache\Core\CoreCacheHandler->writeSaveQueue()
#6 /var/www/html/vendor/pimcore/pimcore/lib/Cache.php(200): Pimcore\Cache\Core\CoreCacheHandler->shutdown(false)
#7 /var/www/html/vendor/pimcore/pimcore/lib/Pimcore.php(259): Pimcore\Cache::shutdown()
#8 /var/www/html/vendor/pimcore/pimcore/lib/Kernel.php(328): Pimcore::shutdown()
#9 [internal function]: Pimcore\Kernel->Pimcore\{closure}()
#10 {main}
  thrown in /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Block.php on line 823

### Steps to reproduce

1. Create Field Collection with Fieldset > Block > Fieldset > Select.
2. Create Class with Fieldset > Block > Fieldset > Field Collection [created above].
3. Create instance of the Class.
4. Select any value in the select and save.
5. Got error in the admin panel.

**Comment by fashxp** [comment]
field collections are not allowed inside blocks. 

see also https://github.com/pimcore/pimcore/pull/14139

**Comment by brusch** [comment]
Imho this won't be possible in future anyway, closing this.

**Comment by kanevbg** [comment]
In Pimcore 10.5.16 you can add blocks to field collection definitions, but I guess you did not support that either?

![image](https://user-images.githubusercontent.com/11477130/216794606-2b584cdf-260e-4daf-a1b1-f372d453dcad.png)

@brusch @fashxp Please let me know if this should not be used too.

**Comment by kanevbg** [comment]
up

**Comment by fashxp** [comment]
> In Pimcore 10.5.16 you can add blocks to field collection definitions, but I guess you did not support that either?
> 
> ![image](https://user-images.githubusercontent.com/11477130/216794606-2b584cdf-260e-4daf-a1b1-f372d453dcad.png)
> 
> @brusch @fashxp Please let me know if this should not be used too.

That should be perfectly fine afaik.
