### ISSUE TITLE
[Pimcore 11][Bug] Translations got lost

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#14097]
e.g. for GDPR extractor

![image](https://user-images.githubusercontent.com/8792145/213395081-1ad2a9ad-618d-4361-90fb-0e02d0fd8ae9.png)

**Comment by aashan10** [comment]
![Image](https://user-images.githubusercontent.com/18713900/217172835-8c15d30f-016d-43d4-8ed8-2510acdb2195.png)

Translations for GDPR data extractor are there for all 10.5, 10.6 and 11.x branches as I checked

**Comment by brusch** [comment]
@aashan10 ok, thanks for checking @fashxp maybe it was a local issue then?
