### ISSUE TITLE
Admin translations: Support for country specific locales (and fallback to primary language)

### ISSUE THREAD

**Issue by gadget60** [pimcore/pimcore#14092]
### Expected behavior

_Disclaimer:_ This is a behaviour that is kind of "swiss german" specific (maybe other locales too I'm not aware of), but most users probably may not have experienced this issue. However I consider it a bug, for following reason:

In swiss german Switzerland, we use the dot (.) as decimal separator. Hence our keyboard layouts have a "dot key" in the numeric pad. Also, users are familiar to using the dot in decimal value inputs.

Pimcore ships with many translations, all of them are not region-aware (e.g. just "de" instead of "de_CH") which is fine. However this means I just can choose between languages like "German", "English" etc as admin user language. Now Extjs (Ext.util.Format) in the admin backend will use this admin user language for stuff like number formatting. Using the non-region-specific language "de", the comma (,) is selected as decimal separator. This forces the user to use the "comma key" in decimal number field - the numeric pad "dot key" gets useless. 

The obvious solution to solve this issue is to define country specific admin locales, as described in:
https://pimcore.com/docs/pimcore/current/Development_Documentation/Multi_Language_i18n/Admin_Translations.html

For example:
```
pimcore_admin:
    admin_languages:
        - de_CH
        - en
```

Also, I provide our app-specific admin translations in following files:
- /translations/admin.en.yaml
- /translations/admin.de_CH.yaml

Now we have the following situation:

- I can choose "German (Swiss)" for my user account in Pimcore's user profile, which is fine
- Numeric inputs expect the dot as decimal separator, which is fine
- In Pimcore translation's admin domain, we have both "English" and "German (Swiss)", which also works fine

**BUT: Pimcore's "built-in" translations (like all the menus, dialogs etc) now show up in english.**
That means, only my own translations (from admin.de_CH.yaml) are used, but everything else in Pimcore's admin backend is english.
Here, the fallback mechanism from "de_CH" to pimcore's available translations (namely to "de" in this case) does not work.

### Actual behavior

See above

### Steps to reproduce

- Create a vanilla pimcore project
- Switch the "admin" user's language to "German"
- Create any Object with a field type "Numeric" that allows decimal values
- The input just accepts the comma sign (,) as decimal separator, which is okay for "de_DE", but not for "de_CH"

**Comment by mattamon** [comment]
Hey @gadget60,

we do see a couple of solutions here. 

1. Maybe you could do some research if there is a fallback solution for regional languages to the default language e.g. de_CH to de so on? We would really appreciate a PR if there is something existing.

2. We do add de_CH to our translations for PO Editor. Problem is, that about 90% of all keys need to be translated, so we do import the language in the core. You could basically copy most of the German translations I guess. 
Core -> https://poeditor.com/join/project/VWmZyvFVMH
Bundles -> https://poeditor.com/join/project/XliCYYgILb

3. You create the de_CH in your project and just copy the German translations into the file, so it won't use English as fallback.

**Comment by gadget60** [comment]
Hi @mattamon 

Thanks for your reply.

I did some more investigation: The server side fallback mechanism actually works, as it is based on Symfony which falls back from a region specific language back to the "generic" one.

The issue origins from the fact that 99% of all admin labels/texts are translated client-side in global Javascript 
 t(...) function. This one relies on pimcore.system_i18n object, which in turn is generated in:

https://github.com/pimcore/pimcore/blob/46c8fe5c31e5cd78ebd6e6d0afcea55b4ea374ae/bundles/AdminBundle/src/Controller/Admin/MiscController.php#L93

Now this method MiscController::jsonTranslationsSystemAction() is not region-aware - it tries to load (via $translator->getCatalogue()) a catalogue  from json files named exactly as the language (e.g. "de_CH.json" and "de_CH.extended.json") and falls back to english if those do not exist. I think this is where some kind of region specific fallback should be implemented: Initialze with "en" first, then load the generic language "de", and finally (if at all) try to load a region-specific catalogue "de_CH". 

If you decide to not maintain region-specific translations in Pimcore, this step is even simpler - we basically chop the region part and just load the "generic" catalogue: "de_CH" => "de".

To answer your propsals:

1. See above - this is where I think we should implement a fallback mechanism. If you agree on that, I can provide a PR. (...for PC 10? or for 11?)
2. That's not a great idea. We have the same issue for our other official languages, namely fr_CH and it_CH. We basically would copy/paste 99% of the labels, and would have to maintain them in future.
3. Actually my current workaroud is simalar to this:

I just symlink both the de_CH.json and de_CH.extended.json to their generic language files (but in their original location), and everything works as expected:
```
[PROJECT_ROOT]> cd vendor/pimcore/pimcore/bundles/CoreBundle/Resources/translations \
&& ln -s de.json de_CH.json \
&& ln -s de.extended.json de_CH.extended.json
```
However this needs extra steps in DEV and on deployment, and should work out of the box IMHO.

**Comment by mattamon** [comment]
Hey @gadget60 

thank you for investing time into the translations. 

I think the easiest solution here is to chop the region-specific translation part. We would be happy if you could provide a PR for this for Pimcore 11.

**Comment by gadget60** [comment]
Hi @mattamon 

I created a PR for Pimcore 11. However, I don't just chop the region-specific part: This would affect current functionality as there are already region specific translations for "pt_br" and "sv_fi".

Thx for checking
