### ISSUE TITLE
Inherited field collection value not shown

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#1410]
# Bug Report

### Expected behavior 
Inherited field collections of parent objects should be shown.
  
### Actual behavior  
Inheritance marker (grren arrow in upper left panel corner) is present but content of inherited field collections is not visible.
  
### Steps to reproduce  
1. create field collection with 1 input field
1. create class with "inheritance allowed" 
1.1. add a field collection field to this class and assign the field collection from 1. as allowed type
1. create object of this class, add the field collection and enter any value to the input field of the field collection
1. create another object of the same class as child element of the first object
1. open second object and see that inherited field collection value is not shown

**Comment by weisswurstkanone** [comment]
Field collections do not support inheritance. Therefore, there is also no inheritance marker.
See https://www.pimcore.org/docs/latest/Objects/Object_Classes/Data_Types/Fieldcollections.html
at the very bottom.
