### ISSUE TITLE
[Bug]: Showroot in customview not working

### ISSUE THREAD

**Issue by Julia-SOLIGNAC** [pimcore/pimcore#14112]
### Expected behavior

Hello :)

When using 'showroot' => true, in the custom view config file, it should show the root node folder.

### Actual behavior

It always only show childrens, not parent folder.

Tested with : 
'showroot' => 1, 
'showroot' => TRUE,
'showroot' => true,  

### Steps to reproduce

Create custom view, set showroot parameter to true, see the view : no root folder.
Even in the example on documentation page (https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Class_Settings/Custom_Views.html) it doesn't work.

**Comment by mattamon** [comment]
Hey @Julia-SOLIGNAC, 

we gonna take a look at it! Thank you for the input!
