### ISSUE TITLE
[Bug]: Knp\Component\Pager\PaginatorInterface service not found 

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#14131]
### Expected behavior

No error is thrown, when open Voucher Details

### Actual behavior

![image](https://user-images.githubusercontent.com/104770750/214318673-f370fcdf-8119-459a-a48e-d237dadcd062.png)

### Steps to reproduce

Try to open Voucher Details from an OnlineShopVoucherSeries Object

**Comment by dvesh3** [comment]
Regression of https://github.com/pimcore/pimcore/pull/13766/files#diff-d8b32ac5dfd96e61b04a0acc639e673c92a989df9281e4a3d36ae9e5b07a50d9L210
