### ISSUE TITLE
[Bug]: Video dialog produces JS error

### ISSUE THREAD

**Issue by Noxoreos** [pimcore/pimcore#14149]
### Expected behavior

When I save the video dialog, I should be able to open it up to do further changes.

### Actual behavior

When the video dialog is saved and opened again, it does not open, but outputs a JS error instead. It only works again after reloading the data object or after clearing the data using the recycle bin symbol.

> Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
>     at pimcore.helpers.editmode.openVideoEditPanel (script-proxy?storageFile=minified_javascript_core_d8167ecfebb9b7d04a3bc6abced7244a.js&_dc=4cd0d7549853d350210f8cf658939170246e3483:5148:22)
>     at klass.openEdit (script-proxy?storageFile=minified_javascript_core_d8167ecfebb9b7d04a3bc6abced7244a.js&_dc=4cd0d7549853d350210f8cf658939170246e3483:83513:48)
>     at Object.callback (ext-all.js?_dc=4cd0d7549853d350210f8cf658939170246e3483:1827:134)
>     at constructor.fireHandler (ext-all.js?_dc=4cd0d7549853d350210f8cf658939170246e3483:8936:359)
>     at constructor.onClick (ext-all.js?_dc=4cd0d7549853d350210f8cf658939170246e3483:8936:55)
>     at constructor.fire (ext-all.js?_dc=4cd0d7549853d350210f8cf658939170246e3483:2407:19)
>     at constructor.fire (ext-all.js?_dc=4cd0d7549853d350210f8cf658939170246e3483:3087:49)
>     at constructor.publish (ext-all.js?_dc=4cd0d7549853d350210f8cf658939170246e3483:3085:125)
>     at constructor.publishDelegatedDomEvent (ext-all.js?_dc=4cd0d7549853d350210f8cf658939170246e3483:3086:92)
>     at constructor.doDelegatedEvent (ext-all.js?_dc=4cd0d7549853d350210f8cf658939170246e3483:3087:421)

This portion of JS code is affected: `script-proxy?storageFile=minified_javascript_core_d8167ecfebb9b7d04a3bc6abced7244a.js&_dc=4cd0d7549853d350210f8cf658939170246e3483:5148`

```
    if (allowedTypes.includes("asset")) {
        fieldPath.on("render", initDD);
        poster.on("render", initDD);
    }
```

### Steps to reproduce

1. Open the video dialog in a data object that contains a video-media data component.
2. Save the dialog without any changes.

I could reproduce this in the Pimcore demo after adding the video-media data component in the Media section of the "Car" Data Object Class and then performing the above steps.

**Comment by mattamon** [comment]
Fixed by #14336
