### ISSUE TITLE
[Improvement]: RFC - Hide unpublished dataobjects in object tree

### ISSUE THREAD

**Issue by SamyMP** [pimcore/pimcore#14148]
### Improvement description

Currently, there is no way to hide unpublished dataobjects in the object tree.

For my needs, I created a javascript event to add a button in the context menu to hide/show unpublished objects : 
```js
document.addEventListener(pimcore.events.prepareObjectTreeContextMenu, (e) => {
    const { detail } = e;

    const isShown = detail.object.childNodes.every(child => child.get('visible'));

    // If the object has children
    if (detail.object.childNodes.length > 0) {
        if (isShown) {
            detail.menu.add(new Ext.menu.Item({
                text: 'Hide unpublished',
                iconCls: "pimcore_icon_hide",
                handler: function () {
                    detail.object.childNodes.filter(child => !child.data.published).forEach(child => child.set('visible', false));
                }
            }));
        } else {
            detail.menu.add(new Ext.menu.Item({
                text: 'Show unpublished',
                iconCls: "pimcore_icon_seemode",
                handler: function () {
                    detail.object.childNodes.filter(child => !child.data.published).forEach(child => child.set('visible', true));
                }
            }));
        }
    }
})
```

It works well 
![image](https://user-images.githubusercontent.com/35225430/214784490-90486b00-dcb7-4642-b9e0-5b3cda46c2d6.png)

And I thought this could be a good idea to add this natively in pimcore, but I wanted the user to have a choice to hide them by default. Also, the drawback of my event is that you have to first expand the node before clicking on hide (since it works with the elements in the DOM)
So I started working on this, with a checkbox in the profile settings 
![image](https://user-images.githubusercontent.com/35225430/214794210-3f89dc8a-a43b-48fa-a463-4e7edd248a08.png)

```js
// tree.js

         store.on("nodeexpand", function (node, index, item, eOpts) {
            if (!node.isRoot()) {
                if (pimcore.currentuser.hideUnpublished) {
                    node.childNodes.filter(child => child.data.type === 'object' && !child.data.published).forEach(child => child.set('visible', false));
                } else {
                    node.childNodes.filter(child => child.data.type === 'object' && !child.data.published).forEach(child => child.set('visible', true));
                }
            }
             pimcore.helpers.removeTreeNodeLoadingIndicator("object", node.data.id);
         });
```

I modified everything accordingly in the code. This feature seemed fine at first, but there are other problems : 
- When creating an object via UI, it is unpublished by default. So, when I create it, it doesn't appear in the tree... 
- What happens when an object has a pagination in the tree ? The pagination is displayed, but if all the children are unpublished, nothing is shown in the tree
- What happens if an object is unpublished, but has children that are not ? Should we still display the unpublished item to access its children which are published or not ? 

Anyway, there are solutions to these problems but I wanted to know if this potential PR has any chance of being merged or not, what do you think ?

**Comment by fashxp** [comment]
I can see the use case, but I'm not so sure how to tackle that topic the most elegant way. 


You always could create a [custom view](https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Class_Settings/Custom_Views.html) that filters out the unpublished objects and include that view into your perspective.
Would that work for your use case? 

Of course that would not solve the issue with newly created objects - but allowing the creation of new objects and not showing unpublished objects at the same time might be problematic anyway? 

Any other input from the community?

**Comment by fashxp** [comment]
I'll close this for now ... feel free to continue discussion there and tag me if necessary.
