### ISSUE TITLE
[Improvement]: Update best practice documentation

### ISSUE THREAD

**Issue by mattamon** [pimcore/pimcore#14145]
### Improvement description

Update best practice documentation. Some practice are outdated and even still use images from Pimcore 6

We need to rework the whole section and add new code everywhere.
A caution message has been added in the readme, waiting for an update. This will have to be removed after reworking the full section.

Updated docs:
- [ ]  [Open_By-External_Id](https://pimcore.com/docs/pimcore/11.0/Development_Documentation/Best_Practice/Open_By-External_Id.html)

**Comment by mcassier31** [comment]
See https://github.com/pimcore/pimcore/pull/15437

We need to update the code and rework the documentation.

**Comment by mattamon** [comment]
I close the ticket since caution was added.
