### ISSUE TITLE
[Bug]: Priority of redirect cannot be changed when value is 99

### ISSUE THREAD

**Issue by rberneder** [pimcore/pimcore#14142]
### Expected behavior

Priority of redirects should be adjustable at any time.

### Actual behavior

Priority of a redirect cannot be changed once it has a value of 99. The warning dialog appears (in this case too late, since the value of 99 can be set without warning) and prevents the update.

### Steps to reproduce

- Add a redirect (I created it in expert mode).
- Add source and target URLs.
- Save.
- Change priority to 99.
- Save.
- Change priority to something else.

Then you should see the warning message that prevents you from saving.

**Comment by mattamon** [comment]
Fixed by #14343
