### ISSUE TITLE
FormBuilder

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#1415]
With the new Pimcore 5 we can use the power of Symfony Forms Component ( http://symfony.com/components/Form ). We'll probably also no longer use Zend_Form in projects. The extension Zend Form Builder ( https://github.com/dachcom-digital/pimcore-formbuilder ) will no longer fit aswell I guess.

I'd like to request a form builder for the pimcore core at this point. There are a couple of reasons why I think this would be a good idea.
1) Forms are needed on almost every website (contact forms, comment forms...)
2) You could connect forms to object classes. Pimcore does already render form inputs in the backend for objects, enforcing data types. If we could get the same for the frontend, we could easily allow object editing in frontend solutions.
3) An integrated forms solution would be great for editors. If you take a look at the solution in the new Typo3 8 LTS release they offer very easy handling of forms for editors. Same goes for wordpress and other cms solutions.

I'd like to see a form feature, where editors can create forms with various input fields. Forms could be dropped into area blocks in documents, file uploads could be saved into preconfigured asset paths (like image fields in objects). In the end, I'd like to see multiple options to handle a form submission, maybe like the finishers in Typo3 ( https://youtu.be/F9sTAOEcTI0?t=40s ). We could email it (using Pimcore Email component) and take the input field names as placeholders in email templates (great for editors), we could directly fill objects with the information (like we do it in the backend editing) or we could simply call some custom class/function we define which does handle the request.

I think there is a lot of potential in a core embedded forms solution. What do you think?

**Comment by dpfaffenbauer** [comment]
I also thought about this. Pimcore could generate FormType classes for each Object Class which then could be rendered using Symfony. If someone needs a customized version of a form, he could create his own and use other Class Forms inside as well. 

For example. Customer Registration in a Shop. Every Customer has at least on Address. Address and Customer are separated Classes. Customer is a FormType which uses the AddressFormType. Makes live so much easier.

The possibilities are endless.

Validation could be done using forms, so Pimcore would be enriched with better backend Validations as well.

Class Data Types could be FormTypes as well.... so they could be reused. 

And: worth mentioning: If Pimcore decides one day to move away from ExtJs, Symfony Forms would be a great replacement for all Object Backend Forms as well ;)

**Comment by dpfaffenbauer** [comment]
Worth mention as well:

 - You can extend Forms (http://symfony.com/doc/current/form/create_form_type_extension.html)
 - You can have different validation groups for forms: (http://symfony.com/doc/current/form/validation_groups.html)

**Comment by solverat** [comment]
We've also talked about the future of [formbuilder](https://github.com/dachcom-digital/pimcore-formbuilder). Actually we've planned to create a _pimcore5_ repo and rebuild it with the symfony form bundle. so this is kind of a exciting ticket here :)  I'm curious to hear the response of the core guys, but i guess this is heavy stuff.

**Some aspects we need to consider:**

- multifile ajax upload
- dynamic forms (modifying pre/post submitting)
- repeater fields (for example: _"add another user"_ will append 1-n fields to form => CollectionType)
- complex condition logic (also for validation - for example: field B is required if A is not empty)
- allow editor user to create custom forms and subforms (awesome gui)
- restrict specific fields to users (for example: restrict users to add input fields only)
- security fields (re-captcha, csrf and honeypot)
- email templates (zurb implementation) / which fields to send in mail etc.

because i don't think that pimcore will provide all this stuff (and be responsible for it) it has to be a very abstract implementation (a custom bundle for example) so we could create a internal bundle to extend it in all possible ways.

**Comment by Cruiser13** [comment]
Thanks for your input so far @dpfaffenbauer and @solverat .
If I look at the aspects you posted here @solverat I don't think that we'll see all of them in the core. But I'm also not sure if we really need all of them. As @dpfaffenbauer said, forms can be quite easily extended.
If Pimcore would provide a basic form (composed in the backend by an editor) with a good connection to assets/objects/emails we can actually get the form and extend it in the frontend before displaying it to the user or sending it to pimcore (or our own controller functions) for processing.

I'll take the complex condition logic example you posted. In 70% of the forms we're building at the moment, we do not need such a specialised condition logic. And it'd probably be overwhelming for editors. If the editor could build the form and we could simply add our own validators for the 30% cases where we need conditions like field a depends on field b and c, that'd absolutely be enough.

Since we're talking about frontend here too (and pimcore comes without frontend) we can also implement our own JS validation on top too.

But the base component should be in the core I think. Because it'd ease the integration with objects, assets and mails. If we change a text field of an object inside a class to a number field the text field in the backend becomes a number field. For the frontend, we have to go into our own solutions and change them too (from Zend_Form_Element_Text to Zend_Form_Element_Number here for example).
If we could simply get some generated form object for our object class this'd be much easier.

**Comment by aarongerig** [comment]
+1 for this feature!

**Comment by dominikschnieper** [comment]
We have already started developing such a plugin. Mainly to display and handle pimcore classes or custom layouts of it as forms including validation and storage. We are far away from having all features included but maybe we can share this work within the next weeks if someone is interested in it and maybe wants to help.

**Comment by Cruiser13** [comment]
So there are already two companies developing such a plugin, @dominikschnieper and @solverat .
We do not have a plugin here but we have some classes to work with forms for pimcore 4. And I guess that other pimcore users also frequently need forms in their projects.

I think we can judge from this information that forms are quiet an important factor for a lot of pimcore projects. An inclusion in the core could be useful to connect forms more deeply with the other models and classes.

**Comment by Yivan** [comment]
+1 too

I confirm that manageable forms are more and more needed by our customers. They begin to be used to be able to create form on other web management content / marketing plateforms, and so intend to be present on Pimcore (user want more and more... like us... ; )) )

Actually, we sometimes use Mautic (https://www.mautic.org/), a famous open source marketing plateform, so user can manage forms. But many of the Mautic features are already on Pimcore (contact management as object, reports as custom reports, emails marketing as the email/newsletter frameworks, landing pages as pimcore document, etc).
The only thing which miss to Pimcore is the "form" part. With such a new feature, it will make Pimcore a true integrated marketing plateforme too, which will interact with other pimcore component.
Here is classic marketing workflow, and it will be achievable on Pimcore with nice GUI tools for enduser:
-> web page -> **integrate form** -> object data created ->emails/newsletters -> reportings.
Only the piece **integrate form** is missing to make a full a-z workflow native on Pimcore (i didn't mention the targeting possibility wich are so great on Pimcore : ) ).

I think it will be a really valuable addition to the core of Pimcore, and this is going to enforce the path taken to Pimcore as a Digital Experiences & Transformation Plateform, here the **Transformation** part will be more user/flexible for enduser admin working on Pimcore.

**Comment by solverat** [comment]
Follow-Up: The [formbuilder](https://github.com/dachcom-digital/pimcore-formbuilder) is now ready for pimcore5.

- [ ] multifile ajax upload _- on our roadmap_
- [x] dynamic forms (modifying pre/post submitting)
- [ ] repeater fields (for example: "add another user" will append 1-n fields to form => CollectionType) _- on our roadmap_
- [ ] complex condition logic (also for validation - for example: field B is required if A is not empty) _- on our roadmap_
- [ ] allow editor user to create custom forms and subforms (awesome gui) _- on our roadmap_
- [ ] restrict specific fields to users (for example: restrict users to add input fields only) _- partly implemented, on our roadmap_
- [x] security fields (re-captcha, csrf and honeypot)
- [x] email templates (zurb implementation) / which fields to send in mail etc.

**Comment by Yivan** [comment]
This is really great news @solverat ! Thanks a lot for your work and providing such a quality plugin to the community.

Just one side question, are the form generated in Twig and/or PHP ?
Having them in PHP would be really great.

Such a discussion has been on CoreShop, and Pimcore team seems to go for the road Twig/PHP in the same time (great!), see @maff comment : https://github.com/coreshop/CoreShop/issues/178#issuecomment-328760636
CoreShop and FormBuilder are going to be one of the best of plugins for Pimcore 5, so it will be so good to be able to use them without Twig hard dependence.

**Comment by aarongerig** [comment]
@Yivan Looks like Twig to me... 👍 
https://github.com/dachcom-digital/pimcore-formbuilder/tree/master/src/FormBuilder/Resources/views/Form

**Comment by solverat** [comment]
Some updates for the record: conditional logic functionality is on the way: https://github.com/dachcom-digital/pimcore-formbuilder/blob/conditionalLogic/docs/81_ConditionalLogic.md

Use the conditional logic to hide/show fields, toggle classes, change validation (real server validation bound to the powerful symfony constraints) and more... depending on given field values.

**Comment by fashxp** [comment]
can be handled with extensions

**Comment by brusch** [comment]
@clementdes https://packagist.org/?query=pimcore%20form or build your own

**Comment by clementdes** [comment]
build my own is an option (if nobody's done it yet).
Thank you !

**Comment by dpfaffenbauer** [comment]
https://packagist.org/packages/dachcom-digital/formbuilder
