### ISSUE TITLE
[Bug]: Slider has NULL value in database when changing value to 0

### ISSUE THREAD

**Issue by Butterd** [pimcore/pimcore#14150]
### Expected behavior

When setting a slider in a dataobject to the value 0, this value should be stored.

### Actual behavior

When setting a slider in a dataobject to the value 0, this value is set to null.  

This has sideeffects for inheritance as well (i.e. parent has a value of 4, child's value is 0 => The value from the parent is used)

### Steps to reproduce

- Add a slider-component to a data object
- set the value of the slider to 0
- in the database the value of the slider is NULL

**Comment by mattamon** [comment]
Hey @Butterd,

this only happens when you instantly set the value to 0 right?
If you set it e.g. to 1, save it and then set it to 0, the 0 will be stored in the database.

**Comment by Butterd** [comment]
Hey @mattamon ,
Thanks for your answer.

The behavior as described happens either way.
So whether you set it to 0 instantly or after saving another value first. It always ends up being NULL in the Database.

**Comment by mattamon** [comment]
I do see the problem now.

If only happens with inheritance. If you reset the value from the child to 0 the value of the parent object is applied.
Gonna take a look. It seems to work for the number types though.
