### ISSUE TITLE
document assets no preview/thumbnail

### ISSUE THREAD

**Issue by beisert1** [pimcore/pimcore#1416]
For .xlsx, .docx, and .pptx I have no preview/thumbnail available.

![image](https://cloud.githubusercontent.com/assets/6433253/24772181/4d0fb9ee-1ade-11e7-8985-2aa65f55eb7e.png)

I have almost all of the requirements installed.

![image](https://cloud.githubusercontent.com/assets/6433253/24772218/739d120a-1ade-11e7-8bfd-628318ec7d47.png)

**Comment by brusch** [comment]
Sorry without any additional information such as version numbers, operating system, ..., we cannot do anything for you.

**Comment by psuhane** [comment]
Hi @brusch,

I have seen thumbnails works on demo.pimcore.org for .xlsx, .docx, and .pptx but how?

In Ghostscript.php file only pdf documents supported for thumbnail..
if (!$this->isFileTypeSupported($path)) {
            $message = "Couldn't load document " . $path . " only PDF documents are currently supported";
            Logger::error($message);
            throw new \Exception($message);
        }

I am just trying to generate the treeview image thumbnail by passing document id() in following url
http://autoparts.local/admin/asset/get-document-thumbnail/id/<.xlsx, .docx, or .pptx doc id>/treepreview/true

But only filetype-not-supported.png coming only in output.

I am using pimcore latest version. Please let me know how this is working on demo.pimcore.org?

**Comment by faridmovsumov** [comment]
I have the same problem on pimcore 4
