### ISSUE TITLE
[Bug]: Ecommerce Voucher Detail paginator when switching entries per page

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#14162]
### Expected behavior

When switching entries per page button, it should do some check:

41 tokens /  25 tokens per page  = 1,64 and current page is between 1 and 2 (round up of 1,64), then it's ok, anything above it , then force current page to the maximum, which is 2.
41 tokens / 75 tokens per page = 0,54 , if current page is above 1, force it to 1

### Actual behavior

![image](https://user-images.githubusercontent.com/6014195/215093956-f376e354-eb8f-4636-b4c9-ecf55afc500c.png)
It's empty because it is still on page 2, so technically trying to show entries in the range of 75-150 but there are only 41 entries.

https://github.com/pimcore/pimcore/blob/b5b83ca5ef5a6e2a151c2fa5a683bcfc65fd5595/bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Single.php#L86-L92

![image](https://user-images.githubusercontent.com/6014195/215096122-854012d5-4957-4951-9c20-32e18e2a8695.png)

### Steps to reproduce

Go on any voucher, generate at least to have 25+ entries but fewer than 75.
Press page `2` to display entries in the range 25-50, then switch the `Tokens per page` to 75. 
It stays on page 2 but it's hidden, so unless one switch back to `25 entries per page`, the following buttons do not appear (like in the other screenshot)
![image](https://user-images.githubusercontent.com/6014195/215095459-e405d239-2203-478c-861b-9f4bf660b14a.png)

**Comment by dvesh3** [comment]
Fixed by #14196
