### ISSUE TITLE
[Bug]: Exception during classes-rebuild because of types in uuid

### ISSUE THREAD

**Issue by matthiashamacher** [pimcore/pimcore#14165]
### Expected behavior

`bin/console pimcore:deployment:classes-rebuild` executes without any errors

### Actual behavior

The command fails with an exception in UUID.php

```bash
In UUID.php line 96:

  Pimcore\Bundle\UuidBundle\Model\Tool\UUID::setItemId(): Argument #1 ($id) m
  ust be of type int, string given, called in /var/www/pimcore/vendor/pimcore
  /pimcore/bundles/UuidBundle/src/Model/Tool/UUID.php on line 157


pimcore:deployment:classes-rebuild [-c|--create-classes] [-d|--delete-classes]
In UUID.php line 96:

  Pimcore\Bundle\UuidBundle\Model\Tool\UUID::setItemId(): Argument #1 ($id) m
  ust be of type int, string given, called in /var/www/pimcore/vendor/pimcore
  /pimcore/bundles/UuidBundle/src/Model/Tool/UUID.php on line 157
```

### Steps to reproduce

1. Configure the UUID Bundle
2. Create classes with strings as an identifier
3. Run the classes-rebuild command

### Error
The error is because the UUIDListener listens on [DataObjectClassDefinitionEvents::POST_ADD](https://github.com/pimcore/pimcore/blob/11.x/bundles/UuidBundle/src/EventListener/UUIDListener.php#L45) and calls the same function that is called if an asset, document or object is created. The problem is now, that with the [parameter and return types added](https://github.com/pimcore/pimcore/commit/83142b53cfd5a791e3c6167470a66336fd03da22#diff-c5ca413fbc56c00a39bded05525fb3ef63918f07474b3d57298e6fba24634055) the [itemId in the UUID Class](https://github.com/pimcore/pimcore/blob/11.x/bundles/UuidBundle/src/Model/Tool/UUID.php) is type hinted with int. Classes can have and in our case or the demo, always have, a string as an identifier.

### Solution
I don't know why a UUID is created in the first place for the classes. This doesn't make sense in my opinion. So there are two options in my opinion:
1. Allow string as itemId
4. Remove the DataObjectClassDefinitionEvents::POST_ADD listener

I'm happy to create a PR for that if you can tell me which option should be used.

**Comment by dvesh3** [comment]
@matthiashamacher this never worked for classes with string names as the table column type is `int(11)` https://github.com/pimcore/pimcore/blob/bc7d4771194da9b1ae6258375985e065c62fbc14/bundles/InstallBundle/dump/install.sql#L694

so we have to fix both API and the table column to have strings.

**Comment by matthiashamacher** [comment]
@dvesh3 Yeah that is another point. But what is the reason to create a UUID for the class definition? Wouldn't it be easier to remove the logic for class definitions if it never worked? Seems that it was no problem until now where to types require int.

If we remove it we also need to remove this if statement:
https://github.com/pimcore/pimcore/blob/bd48f4e7dc5252ef1c1a5ab692c07fd064430ca3/bundles/UuidBundle/src/Model/Tool/UUID.php#L161-L163

**Comment by blankse** [comment]
In the docs is also no word of class definitions:
https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/UUID_Support.html

When we want to support it, the docs should also be updated.

**Comment by dpfaffenbauer** [comment]
It used to have worked one day, it might still work for class-definitions that use a number as identifier. I never used it, but I think there are installation that do

**Comment by dvesh3** [comment]
@matthiashamacher It always worked for classes until the type change was added in Pimcore 11, so removing it is not option. I would provide a fix for accepting string type in `UUID::$itemId` API, DB column and Docs instead.

**Comment by matthiashamacher** [comment]
@dvesh3 
We need to revert the change and remove the event listener for the classes creation. I now have the issue that I cannot install pimcore successfully because the uuid table does not exist during installation:

```
Running installation. You can find a detailed install log in var/log/dev.log

Marking all migrations as done ...

 10/10 [============================] 100%



 Trying to install assets as relative symbolic links.

 --- ---------------------------------- ------------------
      Bundle                             Method / Error
 --- ---------------------------------- ------------------
  ✔   FOSJsRoutingBundle                 relative symlink
  ✔   PimcoreCoreBundle                  relative symlink
  ✔   PimcoreAdminBundle                 relative symlink
  ✔   BasecomCoreBundle                  relative symlink
  ✔   PimcoreSystemInfoBundle            relative symlink
  ✔   NelmioApiDocBundle                 relative symlink
  ✔   PimcoreCustomReportsBundle         relative symlink
  ✔   PimcoreSimpleBackendSearchBundle   relative symlink
 --- ---------------------------------- ------------------


 [OK] All assets were successfully installed.


In ExceptionConverter.php line 49:

  An exception occurred while executing a query: SQLSTATE[42S02]: Base table
  or view not found: 1146 Table 'pimcore.uuids' doesn't exist


In Exception.php line 28:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pimcore.uuids' d
  oesn't exist


In Statement.php line 121:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pimcore.uuids' d
  oesn't exist


pimcore:deployment:classes-rebuild [-c|--create-classes] [-d|--delete-classes]
In ExceptionConverter.php line 49:

  An exception occurred while executing a query: SQLSTATE[42S02]: Base table
  or view not found: 1146 Table 'pimcore.uuids' doesn't exist


In Exception.php line 28:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pimcore.uuids' d
  oesn't exist


In Statement.php line 121:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pimcore.uuids' d
  oesn't exist


pimcore:deployment:classes-rebuild [-c|--create-classes] [-d|--delete-classes]

 ! [NOTE] Installing class definitions failed. Please run the following command manually:

  /usr/local/bin/php /var/www/pimcore/bin/console pimcore:deployment:classes-rebuild -c
```

First I thought that it could be fixed by installing the uuid bundle before running the installation but that is also not possible as the `settings_store` table does not exist until the installation is completed.

I think the only possible solution is to remove the event listener for classes and then we can also revert the changes back to only support int. Not sure why It didn't come up while I tested it with a patch but after updating to the latest alpha the issue occurs and all pipelines of ours are failing as we always reinstall pimcore for linter and unit tests.

**Comment by blankse** [comment]
@matthiashamacher Can we check in the listener if the bundle is installed? At the moment it only checks if it is enabled.

Edit: This need also the settings_store table... Maybe we can check if the table exists or simple catch the error?

**Comment by mattamon** [comment]
@matthiashamacher we faced the same problem for the SEOBundle for the redirects. 
https://github.com/pimcore/pimcore/blob/11.x/bundles/SeoBundle/src/EventListener/UrlSlugUpdateListener.php#L42

We check that the bundle is installed in the listener. We can do the same for the UUIDBundle. 
Maybe you could try this for yourself and tell us if this solves your problem.

Is there already another issue for this? If not please provide a new one. Thanks!

**Comment by matthiashamacher** [comment]
@mattamon 
I'll try that later and give feedback.

> Is there already another issue for this? If not please provide a new one. Thanks!

No, I haven't created a new issue for that. I will do that also when I have news.

**Comment by matthiashamacher** [comment]
@mattamon Checked it and directly created the pr to fix it.
