### ISSUE TITLE
[Improvement]: Clarify php 8.2 support for pimcore 10.x

### ISSUE THREAD

**Issue by juckerf** [pimcore/pimcore#14174]
### Improvement description

Currently the documentation (https://github.com/pimcore/pimcore/blob/10.5/doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md#php--80) and the `composer.json` of pimcore 10.x (https://github.com/pimcore/pimcore/blob/10.5/composer.json#L31) suggest that it's compatible with php 8.2.

But this open PR (https://github.com/pimcore/pimcore/pull/14080) targeted to pimcore 11 and this comment (https://github.com/pimcore/pimcore/pull/13861#issuecomment-1361307701) suggest otherwise.
* If pimcore 10.x is already compatible with php 8.2: feel free to close this issue
* Otherwise I suggest updating the docs and `composer.json` accordingly (I'm happy to provide a PR for this)

**Comment by brusch** [comment]
@juckerf Thanks for pointing our, you're right, we should update the docs and the `composer.json` for `10.5` accordingly. 
A PR would be very nice 😊 Thanks in advance

**Comment by brusch** [comment]
Fixed by #14180
