### ISSUE TITLE
[Bug]: Glossary not working with partial pimcore_wysiwyg content

### ISSUE THREAD

**Issue by luka-jukic** [pimcore/pimcore#14184]
### Expected behavior

If a text in pimcore_wysiwyg is set to bold or italic, and parts of the other text are adjusted by the glossary, the text that is bold or italic should remain so.
<img width="628" alt="Expected Behaviour" src="https://user-images.githubusercontent.com/40577324/215612557-57831cda-6982-4729-996f-18724f7f9a24.png">

### Actual behavior

This does not happen.
<img width="658" alt="Error Behaviour" src="https://user-images.githubusercontent.com/40577324/215612579-7de2e428-c1ac-4d72-8e79-fcbd9f95cf56.png">

### Steps to reproduce

1. Copy following text in the pimcore_wysiwyg :
`<p><strong>Style fixes (<em>light</em>)</strong><br />
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>`

2. Set up the Gloassary to 
<img width="1091" alt="Glossary Test" src="https://user-images.githubusercontent.com/40577324/215612846-bd2f1970-6f08-4029-a8de-06ab37846a51.png">

3. Open up the Document with the Content

---

Steps where reproduced in the pimcore demo.

**Comment by luka-jukic** [comment]
I also noticed that if the text from a glossary entry was included at the beginning of the HTML in an a-tag, the glossary is not applied at all, which is correct, but the subsequent places are not adjusted and ignored.

If this is the case the other way round, the text comes before the a-tag with the same text, the a-tag is removed.

Here is the HTML code for the other two cases:

1. The link tag occurs first:
`<p><strong>Style fixes (<em>light</em>)</strong><br />
<a href="https://demo.pimcore.com/de">Lorem ipsum dolor sit amet</a>, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
`

2. The link tag occurs in middle:
`<p><strong>Style fixes (<em>light</em>)</strong><br />
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum <a href="https://demo.pimcore.com/de">dolor sit amet. Lorem ipsum</a> dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
`
![Cases-3](https://user-images.githubusercontent.com/40577324/216307931-0963f801-bfb2-4b1e-bb4e-c2e21507c642.png)

**Comment by mattamon** [comment]
Fixed by #14333
