### ISSUE TITLE
[Improvement]: ScheduledTasks MaintenanceTask blocked by other MaintenanceTasks

### ISSUE THREAD

**Issue by juckerf** [pimcore/pimcore#14183]
### Improvement description

Maintenance tasks (from https://github.com/pimcore/pimcore/tree/10.5/lib/Maintenance/Tasks) that take some time to execute can potentially block scheduled tasks (https://github.com/pimcore/pimcore/blob/10.5/lib/Maintenance/Tasks/ScheduledTasksTask.php) to be executed on time.
In pimcore 6.x one could work around this issue by creating separate cronjobs using `-j scheduledtasks`/`-J scheduledtasks` of  the `maintenance` command.
With pimcore 10.x the maintenance task was refactored to be asynchronous using symfony messenger. While one could still create separate cronjobs for the `pimcore:maintenance` command this has no effect as the messages are written to the same queue and processed by the same consumer(s). I think this is the only maintenance task which is time critical.
Probably it would make sense to move the ScheduledTasksTask to the `pimcore_core` queue or even a dedicated queue.

**Comment by fashxp** [comment]
TODO: move ScheduledTasks to a separate transport queue

**Comment by dpfaffenbauer** [comment]
Maybe create separate queues for separate tasks, we run into the issue that many entries in a pimcore_core queue block other things, we cannot properly scale that, since all run in the same queue
