### ISSUE TITLE
[Bug]: Fieldcollection default value not set

### ISSUE THREAD

**Issue by MosiiAUT** [pimcore/pimcore#14190]
### Expected behavior

- Add a Fieldcollection to an object with fields that have default values
- Default values should now be set

### Actual behavior

- no default values are set, it is all empty

### Steps to reproduce

- Add a Fieldcollection with e.g. a number-field and set the default-value in the definition to e.g. 10
- Add the fieldcollection-field to an object-definition
- create that object and add the fieldcollection to it

I only tested this with the "number" and the "input" field
Reproduced in the Pimcore Demo 10.5.15

**Comment by lukmzig** [comment]
Should be fixed by https://github.com/pimcore/pimcore/pull/14265
