### ISSUE TITLE
[Installer] add way to integrate additional repositories - like demo-ecommerce

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#1420]
important aspects
- download additional installation profiles from github repositories into /install-profiles/xxx
- list additional install-profiles in install.php
- add possibility to run composer update in order to add additional dependencies if necessary.

**Comment by dpfaffenbauer** [comment]
What does this mean? Are install-profiles only available before pimcore is installed, or can you execute them afterwards as well?

I would much rather like the idea of an CLI Installer which asks like:
 - Do you wan't to install the Pimcore demo?
 - Do you wan't to install the Ecommerce Demo?
 - Do you wan't to install the Output Data Configuration example?
 - etc.

CLI Installer could load Bundle "Install Profiles" via container.

And: CLI Installer could be used for automated installs as well.

So, if you insist of having an Web installer (which I like as well): it could just trigger install commands.

**Comment by maff** [comment]
Installer now supports install profiles defining a `pimcore-install-profile` type in combination with a `manifest.yml`. Example:

* https://github.com/pimcore/demo-ecommerce/blob/master/composer.json
* https://github.com/pimcore/demo-ecommerce/blob/master/manifest.yml
