### ISSUE TITLE
[Bug]: SanityCheckMessage should provide useful error/retry data

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#14217]
### Expected behavior

When performing retries on failed queues Pimcore should provide useful data like an Element-ID.

`bin/console messenger:failed:retry --transport=failed`

### Actual behavior

 No element relation is provided, so we just get "some sanity check failed".

![Screenshot from 2023-02-02 14-13-13](https://user-images.githubusercontent.com/9052094/216334655-fd91c00c-928d-4a0d-911f-04bb84831162.png)

### Steps to reproduce

Trigger SanityCheck failure and execute messenger retry command on configured failed queue for `pimcore_core` transport.

**Comment by martineiber** [comment]
Hi @jremmurd,

Have you tried using the `-vv` option to see more details?
