### ISSUE TITLE
[Bug]: pimcore.report.abstract is undefined

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#14219]
### Expected behavior

Error is fixed

### Actual behavior

JS error is thrown in the console: `class.js?_dc=68e86786778387b23aa20de74a7812d84a8688b6:48 Cannot create class with null properties! A possible case for this error is using the class pimcore.plugin.admin`

### Steps to reproduce

https://github.com/pimcore/pimcore/blob/6b7b4ee668fa7c5907c26d068eee20ca28f4388d/bundles/AdminBundle/public/js/pimcore/report/analytics/elementoverview.js#L18

**Comment by robertSt7** [comment]
Extract all files that are dependent on CustomReportsBundle

**Comment by mcop1** [comment]
File is part of https://github.com/pimcore/pimcore/pull/13943 and should stay there, because it is related to the google analytics functionality. Should be fixed after the mentioned pr was merged.

Closed for now.
