### ISSUE TITLE
DB Cache fallback due to Maintenance Job cleanupcache with Redis

### ISSUE THREAD

**Issue by sebastianMoser** [pimcore/pimcore#1421]
We have noticed that Redis is too busy to answer requests when the maintenance-script calls the cleanupcache Meinantance-Job.

In the debug.log you can find the following entry:
`core.CRITICAL: can't initialize cache with the given configuration BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE.`

Redis.log
`# Lua slow script detected: still in execution after 5575 milliseconds. You can try killing the script using the SCRIPT KILL command.`

It seems that the LUA script in the Redis Backend (clean up old tags) simply takes to long: https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Cache/Pool/Redis.php#L534

Have you any ideas to fix this?

**Comment by maff** [comment]
Could you give us some background on your environment (Pimcore version, amount of objects, amount of entries in Redis)? Thanks!

**Comment by sebastianMoser** [comment]
Sure.
Pimcore Version: 4.3.1
Amount of Objects: 1644074
Redis info:
`# Keyspace
db0:keys=9,expires=5,avg_ttl=450455381
db8:keys=1082536,expires=520968,avg_ttl=115417272`

**Comment by sebastianMoser** [comment]
Do you think the Redis garbage collector function is still necessary? Redis already has implemented an active and passive way to remove expired keys. --> https://redis.io/commands/expire

**Comment by sebastianMoser** [comment]
May this help you: after disabling the redis garbage collector we still get the slow lua script warning which ends up in unpredictable php errors (fatals).
As a test we have disabled LUA now (cache.php - use_lua => false). We will monitor this change for the next couple of days.

**Comment by podarcis** [comment]
We're also experiencing this problem when there are many accesses to the cache and the Pimcore maintenance (cleanupCache) kicks in. Any new insights on this?

@sebastianMoser: We also disabled LUA scripting as a workaround. What is the result of your monitoring? Any problems so far?

**Comment by sebastianMoser** [comment]
Well, we switched back to MongoDB-Caching because the Redis implementation is just too slow to work with - especially on large environments. I have rewritten the Pimcore Mongo-Backend to work with PHP 7 (Pimcore will not support Mongo running under PHP 7 https://github.com/pimcore/pimcore/issues/1275)

We did not detected any issues when we disabled the LUA part. But we detected real strange issues when we disabled the maintenance job "cleanupcache"

**Comment by brusch** [comment]
If you're experiencing this problem, please ensure your're using the right Redis config: 
```
maxmemory-policy volatile-lru   
save ""
```

Using `volatile-lru` is critical, using any other policies will cause data inconsistencies! 

If this is the case and you're still having problems, please try the following: 
Disable LUA scripting with the following config: 
```yml
pimcore: 
    cache:
        redis: 
            options: 
                use_lua: false
```

if this still doesn't help, just disable the cleanup job by appending the following options to your maintenance command: 
`./bin/console pimcore:maintenance -J cleanupcache`

Since you're using the max. memory policy `volatile-lru` this should be perfectly fine.
