### ISSUE TITLE
[Feature]: allow defining custom asset types

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#14238]
### Feature description

Currently, asset types are hardcoded as `Image`, `Video`, `Document`, `Archive` etc. This same list enables us to restrict relations.

It would be nice to be able to define own asset types. For example, I want to add an asset which is only a specific type of a 3D model GLB, [MIME type `model/gltf-binary`](https://www.iana.org/assignments/media-types/model/gltf-binary), it would be nice to be able to define it and use that to restrict the relation and/or use to search by.

**Comment by dvesh3** [comment]
Duplicate of https://github.com/pimcore/pimcore/issues/10245
