### ISSUE TITLE
[Bug][Data Objects]: Default layout for admin users

### ISSUE THREAD

**Issue by t-zilla** [pimcore/pimcore#14241]
### Expected behavior

Master Layout is the default layout for admin users

### Actual behavior

Master Layout (Admin Mode) is the default layout for admin users

### Steps to reproduce

Related to #14160
https://github.com/pimcore/pimcore/blob/v10.5.16/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L516

This change affects which layout is selected by default for admin users.

![Screenshot from 2023-02-06 14-52-32](https://user-images.githubusercontent.com/32539404/216993452-164445fb-d250-43d6-b6d7-609c25543091.png)

* index `-1` refers to Master Layout (Admin Mode)
* index `0` refers to Master Layout
* indices `1` onwards are custom layouts

Not sure if this effect was intentional. If it is, can we make it configurable? The reason for defaulting to Master Layout is that the Admin Mode layout makes it unnecessarily easy for users to input invalid data into non-editable fields.

**Comment by fashxp** [comment]
Thx for reporting. No, that was not intentional.

**Comment by lukmzig** [comment]
Should be resolved by this pull request https://github.com/pimcore/pimcore/pull/14283
