### ISSUE TITLE
[Bug]: Type select / multiselect not updated in custom layouts

### ISSUE THREAD

**Issue by jensschaerer** [pimcore/pimcore#14251]
### Expected behavior

Update select options for field types select/multiselect when object class is modified

### Actual behavior

Select options are not updated, when options in a field in class is updated

### Steps to reproduce

The values in our class "Product" for field regions were wrong and were updated, but select option in the custom layouts are fixed to the old values. This breaks compatibility while editing in one custom layout and show / edit data in Master layout.

Select options in class after updating options:
![image](https://user-images.githubusercontent.com/1929590/217232411-1d4c3a05-2e00-4a84-865e-af419719e9a6.png)

Select options in custom layout after updating options:
![image](https://user-images.githubusercontent.com/1929590/217232935-08bb8b7f-6fbb-4d03-9906-216971c96e00.png)

Workarround: remove field from custom layout and add it again. As we have > 20 custom layouts, this is not the way to go, especially when the developer adds / removes options and don't care about custom layouts.

**Comment by robertSt7** [comment]
- Do not save the options in the custom layouts anymore
- Load the options in the object editor from the class definition, when a custom layout is loaded
