### ISSUE TITLE
Can access/save thumbnails and image editor without correct permissions

### ISSUE THREAD

**Issue by Yihka** [pimcore/pimcore#1425]
### Introduction
There are various asset actions that are not yet checked for if the user has the correct permissions. It is for example possible for a user that has access to the system but only a certain folder ( workspace ) to use the following path to fetch thumbnails of all images, even those he has no access to:
- /admin/asset/get-image-thumbnail/id/55/treepreview/true_dc=149180345346

This means users can see images they're not supposed to see. A more experienced user can make a script and fetch all thumbnails out of the system.

But this is not all, a user can also edit images easily using the following path, while having no access to the images:
- /admin/asset/image-editor/id/206

This means a user can modify each image they want while they have no access to it. A very big problem.

**Please know I did not check all the other controllers but I'm expecting to find similar permission problems. Please make sure people can't simply access things they're not supposed to!**

### Expected behavior 
When using these links, prohibit access to it unless the user has the correct rights. 'view' and 'edit'.  

### Actual behavior  
The user is not stopped and can access the images without the correct rights
  
### Steps to reproduce  

1. Login as admin
2. Create a folder called 'no access'
3. Add some images to this folder
4. Create a folder called 'access'
5. Add an image to this folder
6. Create a new user, with workspace access to 'access'. Give him all the rights. Also asset rights of course.
7. Use the login token to login as that user from another browser.
8. As admin, select an image from the 'no access' folder and find out which ID it is.
9. Use following URL with new user admin/asset/get-image-thumbnail/id/[id_here]/treepreview/true_dc=149180345346
10. Use the following URL with n ew user /admin/asset/image-editor/id/[id_here]
11. You will see you can access both paths and see the image while you have no access to those images.

### Code example to fix problem
```php
It's probably as easy as adding this check
$asset->isAllowed("view")
```

### Other paths found:
The following other paths have no permission check. I don't know what they all do, but please check if it's needed or not.

- downloadImageThumbnailAction
- getImageThumbnailAction
- getVideoThumbnailAction
- getDocumentThumbnailAction
- getPreviewDocumentAction
- getPreviewVideoAction
- imageEditorAction
- imageEditorSaveAction
- getFolderContentPreviewAction
- downloadAsZipAction
- importZipAction
- importServerAction
- clearThumbnailAction
- gridProxyAction
- getTextAction

**Comment by weisswurstkanone** [comment]
build 4082
