### ISSUE TITLE
[Bug]: SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by myrdrks** [pimcore/pimcore#14254]
### Expected behavior

Container should start

### Actual behavior

When I follow the steps from xxx I end up after `docker-compose up`.
The console logs:

supervisord_1  | messenger:consume [-l|--limit LIMIT] [-f|--failure-limit FAILURE-LIMIT] [-m|--memory-limit MEMORY-LIMIT] [-t|--time-limit TIME-LIMIT] [--sleep SLEEP] [-b|--bus BUS] [--queues QUEUES] [--no-reset] [--] [<receivers>...]
supervisord_1  |
supervisord_1  | 2023-02-01 16:22:05,891 INFO exited: messenger-consume_00 (exit status 1; not expected)
supervisord_1  | 2023-02-01 16:22:06,901 INFO spawned: 'messenger-consume_00' with pid 5786
supervisord_1  | 2023-02-01 16:22:07,903 INFO success: messenger-consume_00 entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
supervisord_1  |
supervisord_1  | In AbstractMySQLDriver.php line 112:
supervisord_1  |
supervisord_1  |   An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or dir
supervisord_1  |   ectory
supervisord_1  |
supervisord_1  |
supervisord_1  | In Exception.php line 18:
supervisord_1  |
supervisord_1  |   SQLSTATE[HY000] [2002] No such file or directory
supervisord_1  |
supervisord_1  |
supervisord_1  | In PDOConnection.php line 40:
supervisord_1  |
supervisord_1  |   SQLSTATE[HY000] [2002] No such file or directory

### Steps to reproduce

1. docker run -u `id -u`:`id -g` --rm -v `pwd`:/var/www/html pimcore/pimcore:php8.1-latest composer create-project pimcore/skeleton pimcore
2. cd pimcore
3. echo `id -u`:`id -g` and put in the docker-compose.yaml
4. docker-compose up

I thought I could ignore this and could continue but than I get this after
`docker-compose exec php vendor/bin/pimcore-install --mysql-host-socket=db --mysql-username=pimcore --mysql-password=pimcore --mysql-database=pimcore`

php: symbol lookup error: /usr/local/lib/libMagickCore-7.Q16HDRI.so.10: undefined symbol: heif_init

**Comment by jdreesen** [comment]
I assume you are using an Apple laptop with ARM processor. Please look here: pimcore/docker#121

**Comment by myrdrks** [comment]
In docker-compose.yaml I changed
```
    php:
        image: pimcore/pimcore:php8.1-debug-latest
```
Version to `php8.1-latest`
Now it works
