### ISSUE TITLE
Not all sql data is escaped,  leaving potentional sql injections

### ISSUE THREAD

**Issue by Yihka** [pimcore/pimcore#1426]
Hey,

Zend db connections are used, which is good, however, at many queries the data is still not escaped. Non-escaped data is not dangerous by itself, only when the user somehow can get to the point of modifying the data in the query. Luckily as far as I've seen, most of these queries which do not escape data, are not easily modified by a user, if at all. This does not change that it's a best practice to escape everything.

Not escaped, core from pimcore/models/asset/dao.php, line 385:
```php
$parentIds = $this->getParentIds();
$inhertitedLocks = $this->db->fetchOne("SELECT id FROM tree_locks WHERE id IN (" . implode(",", $parentIds) . ") AND type='asset' AND locked = 'propagate' LIMIT 1");
```
Escaped example:
```php
$parentIds = $this->getParentIds();
$select = $db->select();
$select->from('tree_locks')
$select->where->in('id', $parentIds);
```
Above is just an example. Pimcore is full of these query strings that are not escaped. It'd be nice to see them all being properly escaped to prevent an sql injection in all possible cases.

**Comment by brusch** [comment]
In the example above it's not possible to inject anything, since the IDs are generated by `getParentIds()` and it does only return integers. 

If there's a real potential vulnerability , please report it to security@pimcore.org. 

Thanks!
