### ISSUE TITLE
Pimcore 5: SQL Error on saving Object with Lazy Loaded fields

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#1430]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [ x ] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [ x ] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [ x ] There's no existing ticket for the same issue
- [ x ] Remove unused sections and this bullet points from the template below. 
  
### Steps to reproduce  
 - Create two classes with a multihref **AND** href field (be sure its lazy loaded!)
 - Create two objects and link the first one to the multihref and href of the second one
 - Reload and save again -> Error

Error looks like this:

```
An exception occurred while executing 'INSERT INTO object_relations_30 (`dest_id`, `type`, `fieldname`, `index`, `src_id`, `ownertype`) VALUES (?, ?, ?, ?, ?, ?)' with params [38, "object", "test2", 1, 39, "object"]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '39-38-object--test2-object-0' for key 'PRIMARY' (500 Internal Server Error)
```

**Comment by weisswurstkanone** [comment]
fixed in build 40

**Comment by dpfaffenbauer** [comment]
cheers
