### ISSUE TITLE
User-role relation not removed when removing role (causing fatal error on login)

### ISSUE THREAD

**Issue by janwalther** [pimcore/pimcore#1431]
# Bug Report

### Expected behavior 
User-role relation should be removed when role gets deleted.
  
### Actual behavior  
User-role relation is kept for a deleted role. When trying to login Pimcore won't find the assigned role (because it does not exist anymore) and tries to call "getPerspectives()" on boolean false which causes a fatal error, see https://github.com/pimcore/pimcore/blob/master/pimcore/models/User.php#L602.
  
### Steps to reproduce  
1. Create role
1. Create user
1. Assign created role to user
1. Delete role
1. Try to login with created user

### Solution
Role id of deleted role needs to be removed from database table users, column roles.

**Comment by weisswurstkanone** [comment]
fixed in build 4081 pimcore4, build 51 pimcore5
