### ISSUE TITLE
[Bug]: Web2Print processor type error

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#14328]
### Expected behavior

Fix type error

### Actual behavior

![image](https://user-images.githubusercontent.com/104770750/218777227-67b55b06-844a-42e8-b7ad-0015a6058a29.png)

### Steps to reproduce

- Go to Settings->Web-to-Print Settings
- Select for Tool: PDFreactor
- Save & reload
- Test the settings

**Comment by blankse** [comment]
@robertSt7 I created a PR https://github.com/pimcore/pimcore/pull/14330
