### ISSUE TITLE
[Bug]: Type error in Predefined Asset Metadata

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#14345]
### Expected behavior

Typ error is fixed

### Actual behavior

![image](https://user-images.githubusercontent.com/104770750/219054409-88c20ebc-b040-4759-b950-70a2fb4a657d.png)

### Steps to reproduce

- Open Settings->Predefined Asset Metadata
- Try to set some fields to an empty string

**Comment by blankse** [comment]
@robertSt7 I created a PR https://github.com/pimcore/pimcore/pull/14347
