### ISSUE TITLE
[Bug][DataObject]: not editable and invisible not working

### ISSUE THREAD

**Issue by foxgreek** [pimcore/pimcore#14341]
### Expected behavior

If I select "not editable" the field should not be editable and if I select "invisible" the field should be invisible.

### Actual behavior

Both functionalities are not working.

### Steps to reproduce

Mark a field in the demo (10.5.16) as "not editable" or "invisible".

**Comment by mattamon** [comment]
Will be fixed by https://github.com/pimcore/pimcore/pull/14283
Closing, because it is a duplicate of https://github.com/pimcore/pimcore/issues/14241 and https://github.com/pimcore/pimcore/issues/14280
