### ISSUE TITLE
UserRole class should be abstract

### ISSUE THREAD

**Issue by Navino16** [pimcore/pimcore#14365]
### Expected behavior

When calling UserRole::getBynName with a valid role name, it should return the given role

### Actual behavior

When calling UserRole::getBynName with a valid role name, it's always return null.
But if you try to get UserRole by it's ID with UserRole::getById, no problem UserRole is returned.

### Steps to reproduce

* Create a new role in pimcore backend (for example "appAdmin")
* Call UserRole::getByName("appAdmin") and try to dump the return value (for example inside a command)
* Return value is null

**Comment by blankse** [comment]
@Navino16 `\Pimcore\Model\User\UserRole` should be a abstract class for `\Pimcore\Model\User\User` and `\Pimcore\Model\User\Role`. You need to use `\Pimcore\Model\User\Role::getByName()` to load roles and `\Pimcore\Model\User\User::getName()` to load users.

**Comment by brusch** [comment]
Yep, I think we should make `UserRole` abstract ... changed the title and scheduled it for `11.x`.
