### ISSUE TITLE
[Bug]: getPriceInfo() throws in CLI due to missing custom session bag

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#14374]
### Expected behavior

PricingManager / PriceSystem can be used in CLI (Tested in Pimcore 10.5.x)

### Actual behavior

`$checkoutable->getPriceInfo() `throws error in cli ` The SessionBagInterface "ecommerceframework_pricing_environment" is not registered.`

see https://github.com/pimcore/pimcore/blob/10.6/bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php#L234 and https://github.com/pimcore/pimcore/blob/10.6/bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php#L328

### Steps to reproduce

Call `$checkoutable->getPriceInfo()` within a command.

Use case: export prices via command/messenger considering configured pricing rules.

**Comment by mattamon** [comment]
Same issue as described here: https://github.com/pimcore/pimcore/issues/9905
The workaround from Butterd should work in the meanwhile. 
Will be fixed with Pimcore 11.
