### ISSUE TITLE
[System Settings] Use LocationAwareConfigRepository

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#14373]
This allows to store the system config into the database or any other supported location. 
Approach similar to what we do e.g. with `\Pimcore\CustomView\Config` or `\Pimcore\Perspective\Config`. 

Please consider #14372 which should be done first.

**Comment by mcop1** [comment]
- We leave system.yaml as it is, but we extract the system setting into a separate config and admin_config (you can think of better names of course)
- Add those 2 new configs here https://github.com/pimcore/pimcore/blob/4f37f72d95e41a2c4720f4da340aa0f091a1a91a/lib/Kernel.php#L109
- We need two different config classes, 1 for pimcore settings, 1 for pimcore admin settings (like we already talked about). Maybe we can implement a base class which covers most of the work for both classes.
- We need to split the UI into 2 tabs, for pimcore settings and pimcore admin settings (with 2 different save buttons) 
- It should be possible to configure them separately. It can happen that you can´t save the pimcore settings, but can save pimcore admin settings
- We need to check every occurence of getParameter->('pimcore.config') and check if pimcore or pimcore admin settings are read. If so, then we have to replace those parts with the config classes mentioned above. 
- We need to check the installer. Check if it relies on `system.yaml`, if it is only about the default config, then we can move that
