### ISSUE TITLE
[Bug]: Cannot retain slash at the end of the URL on link editable under Documents

### ISSUE THREAD

**Issue by taigao9** [pimcore/pimcore#14375]
### Expected behavior

Retain trailing slash on the Path of the Link editables in Documents

<img width="162" alt="expectedbehavior" src="https://user-images.githubusercontent.com/125644793/219599535-5f6bfd88-b2ba-4d96-a50c-5f27de372d74.png">

### Actual behavior

Trailing Slash is being removed by PIMCore automatically after adding on the editable and reloaded/previewed the page.

<img width="181" alt="image" src="https://user-images.githubusercontent.com/125644793/219599996-15999a77-ecaf-4ac9-b01b-c800d8f9b862.png">

<img width="139" alt="image" src="https://user-images.githubusercontent.com/125644793/219600260-59c0e816-1f73-4708-b501-5df29d8943ba.png">

### Steps to reproduce

1. Create Link editable in Documents
2. Add path which is also present from Documents section

<img width="418" alt="image" src="https://user-images.githubusercontent.com/125644793/219600980-874303cf-7cf1-401e-a6db-ff204e1d126f.png">

**Comment by kingjia90** [comment]
Confirmed the described behaviour, but just wondering, what's the purpose/benefit of retaining the slash? 
This happens when the link editable is detecting a path that matches an existing document and replaces it with the `internal type`

**Comment by taigao9** [comment]
Thanks for checking on it, as for retaining the trailing slash we need it to comply with SEO findings of our website that causes redirection.

**Comment by kingjia90** [comment]
I am not sure if that could be seen as a bug.
The purpose of this is that whenever the target document url/path gets changed, the links would not break but will always return the right one and therefore the trailing slash would be not present.

What if we add a new checkbox `Add trailing slashes` here below in the Properties
![image](https://user-images.githubusercontent.com/6014195/221144527-02b11d10-1751-40b9-9cda-460e4fda482d.png)
in a similar way that `Parameters` adds `?some=thing` and `Anchor` adds `#some_anchor`, or is something that needs to be globally set?

**Comment by kingjia90** [comment]
May fixed by https://github.com/TorqIT/pimcore/pull/56
Thank you Torq It !

**Comment by dvesh3** [comment]
please see https://github.com/pimcore/pimcore/pull/14898#issuecomment-1504822039
