### ISSUE TITLE
[Improvement]: Add ManyToOneObjectRelation data type

### ISSUE THREAD

**Issue by prunepal333** [pimcore/pimcore#14370]
### Improvement description

Currently, we don't have ManyToOneObjectRelation type. To get this feature, we need to use ManyToOneRelation type with object restrictions. But, this approach lacks a possibility to have visible fields for Objects like in ManyToManyObjectRelation. Using ManyToManyObjectRelation to have this feature have two drawbacks.
* Philosphically wrong usage (even if we put validation on inserting object)
* For a single field, we don't want grid like view.
![Screenshot from 2023-02-16 20-01-51](https://user-images.githubusercontent.com/59438412/219524609-bb5e99f3-ee53-4737-b3ec-cc3544f269d9.png)
So, the possible solution that's currently in my mind is to create a new field ManyToOneObjectRelation (with similar ideas of ManyToManyObjectRelation).
After the implementation, it should look like this in object editor.
![Screenshot from 2023-02-16 20-01-06](https://user-images.githubusercontent.com/59438412/219524475-f8273fff-a492-4a73-9fc6-a8423e15f866.png)
And, the class editor will look-alike to the ManyToManyObjectRelation Type.

**Comment by matthiashamacher** [comment]
For what do you want to choose the visible fields? As we don't have a table how should those fields be shown?

If its just regarding showing other data then the path (which is the default) the Path Formatter would be the way to go: https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Class_Settings/Path_Formatter.html

**Comment by brusch** [comment]
Yep, I agree, this shouldn't be necessary - closing it for now 😊
