### ISSUE TITLE
[Improvement]: separate metadata & actual file when versioning changes

### ISSUE THREAD

**Issue by svdv22** [pimcore/pimcore#14381]
### Improvement description

When working with assets I could change the custom metadata and/or properties. When I do a new version of the asset is saved. When this happens to a large set of assets this will take up a lot of space, even though the actual file did not change.

Perhaps it's a good idea to separate the information saved on versions of assets. Preferably also when the embedded meta data changed but just the embedded meta data, not the file itself.

One possible solution would be to omit the file. Whenever a version of an asset is accessed that does not have a file it should request an older version until it finds one that does.

**Comment by fashxp** [comment]
Isn't that implemented already? @brusch

**Comment by brusch** [comment]
Fixed by https://github.com/pimcore/pimcore/issues/3797
