### ISSUE TITLE
[Bug]: Document editable data not saved properly when editing the data for different target groups

### ISSUE THREAD

**Issue by aryaantony92** [pimcore/pimcore#14394]
### Expected behavior

Modified data in the document editables should be saved for each target group.

### Actual behavior

Data in the document editables lost after saving it for different target groups.

### Steps to reproduce

Open a document and select a target group for eg: "new customer". 
Modify a document editable and save.
Select a new target group for eg: "regular customer".
Edit the document editable and save again. 
Try to select the target group "new customer" again. And the saved editable will be lost.

**Comment by dvesh3** [comment]
Fixed by #14460

**Comment by tomhatzer** [comment]
@dvesh3 we also have this problem now on Pimcore 11. Is there also a solution for the current version?
Or are you aware that there's an almost similar problem with Pimcore 11?

Thank you very much and have a great day 🤗

**Comment by kingjia90** [comment]
Thank you for reporting, it seems that the fix in 10.5 got somehow lost during the move out from the core into an own bundle.

Opened a PR with the same fix on the same spot, please see https://github.com/pimcore/personalization-bundle/pull/67

**Comment by tomhatzer** [comment]
Hey @kingjia90, thank you very much for taking care of this. 🤗 

I'm not sure if it's correct what has been merged as the state before was the same as in the main repo before. The parameter being passed (`true`) was removed in the previous PR while it is now added again.
I'm still trying to find out why we are not able to get the "Overwrite" right click action even though we are in the selected Target group. Bundle is installed and enabled, navigation items are there but there's no right click action when clicking on different editables like WYSIWYG editable and likewise.

I wish you a wonderful day!

**Comment by kingjia90** [comment]
Hi @tomhatzer , thank you, i have made a mistake when merging that, it's now reverted, i guess i'll have to revisit the issue.
Could you please open a new issue in https://github.com/pimcore/personalization-bundle/issues and link/mention this issue? just to give it a better visibility than something already closed and done for 10.5
