### ISSUE TITLE
Object grid: add new objectbricks column throws error

### ISSUE THREAD

**Issue by Bhavik-kumar** [pimcore/pimcore#1439]
when I am trying to add any new **object bricks** column in product grid and try to sort by ID, getting 500 Below error.

```
Server threw exception - could not perform action. Please reload the admin interface and try again.

Status: 500 | Internal Server Error
URL: /admin/object/grid-proxy/classId/12/folderId/33?xaction=read&_dc=1491993093467
Params:
-> language: en_GB
-> class: Product



Fatal error:  Uncaught exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Column 'o_id' in order clause is ambiguous' in /home/pimcore_ecommercedemo/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Mysqli.php:77
Stack trace:
#0 /home/pimcore_ecommercedemo/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('SELECT COUNT(*)...')
#1 /home/pimcore_ecommercedemo/www/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'SELECT COUNT(*)...')
#2 /home/pimcore_ecommercedemo/www/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('SELECT COUNT(*)...')
#3 /home/pimcore_ecommercedemo/www/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(828): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#4 [internal function]: Zend_Db_Adapter_Abstract->fetchOne in /home/pimcore_ecommercedemo/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Mysqli.php on line 77
```

**Comment by Bhavik-kumar** [comment]
Hey guys, Any Solution ?

**Comment by solverat** [comment]
I just experienced the same.

## Error
 `Integrity constraint violation: 1052 Column 'o_id' in order clause is ambiguous`

## Query  

```sql
SELECT COUNT(*) AS `totalCount` FROM `object_localized_7_de`  
LEFT JOIN `object_brick_query_myBrick_7` AS `myBrick` 
   ON 1 AND `myBrick`.o_id = `object_localized_7_de`.o_id 
WHERE (o_parentId = 684
   AND object_localized_7_de.o_type IN ('variant')) 
ORDER BY `o_id`
```

Only occurs if you have enabled the "allow variants" flag in class configuration (you can also reproduce this on the demo page).

**Comment by solverat** [comment]
addendum: beside the variant check the class needs a localized field. the object brick also needs a "visible in grid view" element.

**Comment by cleggypdc** [comment]
👍 also reproducable via and object class with localiszed values, without variants or inheritance enabled.

**Comment by cleggypdc** [comment]
class definitions to reproduce 

[objectbrick_testbrick_export.zip](https://github.com/pimcore/pimcore/files/957825/objectbrick_testbrick_export.zip)

Steps to reproduce:
1: Create classes (attached)
2: Create multiple test objects of the new class
3: Open the parent folder view, select a brick column in the column editor
4: observe error in grid view

**Comment by Bhavik-kumar** [comment]
Any Solution ?

**Comment by solverat** [comment]
@Bhavik-kumar this has been fixed, see https://github.com/pimcore/pimcore/commit/b3f102285b2b8f5b73d1b291c62f36e5c4be817c. I think @brusch just forgot to close the issue. :).

Now you have to wait for the the next build or the 4.5.1 release.

**Comment by Bhavik-kumar** [comment]
@solverat Thanks for updaing. 
It's working fine
