### ISSUE TITLE
iOs touch device compatibility: right click not available

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1440]
It seems Pimcore is not compatible with iOs touch device (ipad, iphone). We try with the demo website (Pimcore 4.5 so).
Here is a screenshoot from iOs simulator (same on real iphone/ipad):
![ios](https://cloud.githubusercontent.com/assets/9025839/24979450/6f00d22c-1fd4-11e7-8b30-4fcf17ac1cf0.png)

By bypassing the message ("Click here to proceed"), we can go on on Pimcore, but **right click is not supported** like on Android/Windows touch device where it is a long touch.
**Same on Chrome browser on iOs too, no right click availability** making Pimcore unusable.

Is it because of those last 2 fix wich break iOs ?
https://github.com/pimcore/pimcore/commit/d20e23cbad4b51463fdca6a437a6ac3ab6395c01
https://github.com/pimcore/pimcore/commit/d20e23cbad4b51463fdca6a437a6ac3ab6395c01

If not, is it planned to be iOs device compatible ? (maybe ExtJs 6.2)

On Android touch device, it works fine, we can use Pimcore.

Thanks.

**Comment by Yivan** [comment]
Site note: on Sencha website, it seems iOs tablets should be ok:
https://docs.sencha.com/extjs/6.0.0/guides/supported_browsers.html

**Comment by brusch** [comment]
No, the last 2 patches are only for the Gecko engine (firefox) (see `if` statement). 
ExtJS 6.0.0 has multiple bugs, same as 6.2.0 (we tried already to migrate, but stopped due too many critical bugs (more than 6.0.0 has). 6.2.1 seems to be better, but there's no GPL release yet.

**Comment by Yivan** [comment]
Thanks Brush for your answer. I hope it will be ok on the next ExtJS because we are facing more and more customer need on this which prevent from suggesting them Pimcore.
Just for reference I open a thread to go on the discussion on the official Pimcore forum for people interested/having side solutions:
https://groups.google.com/forum/#!topic/pimcore/21sOKogkz6w

If yourself know a way to being able to make it work on iPad device, i would be very glad to know it.

**Comment by Armin-Rabensteiner** [comment]
Hi, I now also have the case that I need Pimcore on the iPhone.
Are there any updates on this?

**Comment by twin-elements** [comment]
I join the question
