### ISSUE TITLE
[Task]: Deprecate Web2print related DocumentEvents 

### ISSUE THREAD

**Issue by mattamon** [pimcore/pimcore#14418]
### Task description

Print related events are moved into the PimcoreWebToPrintBundle and need to be deprecated in 10.6
Also consider a fc layer/alias 

Events that are moved: 
https://github.com/pimcore/pimcore/blob/10.6/lib/Event/DocumentEvents.php#L127
https://github.com/pimcore/pimcore/blob/10.6/lib/Event/DocumentEvents.php#L140
https://github.com/pimcore/pimcore/blob/10.6/lib/Event/DocumentEvents.php#L152
https://github.com/pimcore/pimcore/blob/10.6/lib/Event/DocumentEvents.php#L178

**Comment by fashxp** [comment]
Hmm .... Why do we need to deprecate them?

**Comment by brusch** [comment]
@fashxp I guess because the name(space) changes, right? 🤔

**Comment by mattamon** [comment]
@fashxp as brusch says, the namespaces change and the events are now in the bundle so you need to install the bundle and check your imports if you used them.

**Comment by mattamon** [comment]
We discussed this, we do not deprecate all the other files that are moved to a bundle. 
The events are mentioned in the Upgrade notes. This should be enough.
