### ISSUE TITLE
[Bug]: load setting from SettingsStore by id returns null

### ISSUE THREAD

**Issue by arn1ex** [pimcore/pimcore#14414]
### Expected behavior

// load setting by id
$setting = SettingsStore::get('my-setting-id');

### Actual behavior

returns null. 

### Steps to reproduce

SettingsStore::set('my-setting-id', 'this is some setting value', 'string', 'bundle-settings-1');

// load setting by id
$setting = SettingsStore::get('my-setting-id');

you can get storred value back if you set a scope as well 
$setting = SettingsStore::get('my-setting-id', 'my-scope ');

Suggestion:
casting scope to string in 
getDao()->getById($id, $scope)
or 
adjust Docs.

**Comment by aryaantony92** [comment]
@masonger https://github.com/pimcore/pimcore/blob/be4515a8583fa9181db3a3112ec3eb59c0dec665/doc/Development_Documentation/19_Development_Tools_and_Details/42_Settings_Store.md?plain=1#L19
The doc says that it's highly recommended to use the scope also except for the settings store for your app.

**Comment by arn1ex** [comment]
@aryaantony92 that still sounds wrong.
highly recommended isn't required! And I am getting null, if I don't set optional highly recommended parameter

**Comment by dvesh3** [comment]
@masonger Since you used scope for `set()` to the settingStore then you need to get the value with the scope since there is no fallback to the default. 

What about the scenario if there are multiple keys with same name and different scopes? It would be hard to decide what to return when no scope is given in `get()`.

**Comment by Brainshaker95** [comment]
I think it's just the documentation that needs some work here.  
This is the current example:
```php
// store or update setting (id, data, type, scope)
SettingsStore::set('my-setting-id', 'this is some setting value', 'string', 'bundle-settings-1');

// load setting by id
$setting = SettingsStore::get('my-setting-id');

// load all settings ids for specific scope
$ids = SettingsStore::getIdsByScope('bundle-settings-1');

// delete setting
SettingsStore::delete('my-setting-id');
```

It really gives the impression that the value of `$setting` will be the stored value and not null (which it will be when the setting was written to the store like shown a few lines above).
