### ISSUE TITLE
[Improvement]: Should FullPageCacheListener::responseCanBeCached() honor header "Cache-Control: no-store"?

### ISSUE THREAD

**Issue by youwe-petervanderwal** [pimcore/pimcore#14429]
### Improvement description

As per [RFC 7234](https://www.rfc-editor.org/rfc/rfc7234#section-5.2.1.5)

> The "no-store" request directive indicates that a cache MUST NOT store any part of either this request or any response to it. This directive applies to both private and shared caches.

To me it makes sense that this also applies to the Pimcore Full Page cache.

I know that there are options to disable the full page cache in your application code (either via a `FullPageCacheListener::disable()` call or by implementing an event listener on the `FullPageCacheEvents::CACHE_RESPONSE` event) however, I think Pimcore should follow standards / best-practices here instead of requiring custom logic.

I'm happy to create a PR if you agree with this.

**Comment by brusch** [comment]
@youwe-petervanderwal Sounds good to me, looking forward to your PR 😊
