### ISSUE TITLE
Clearing Cache via Pimcore Admin needs a couple of minutes with Redis

### ISSUE THREAD

**Issue by sebastianMoser** [pimcore/pimcore#1444]
We have about 2-3 million keys stored in Redis. Clearing the cache via Pimcore Admin needs 2-3 minutes which ends up in fatals like this:

`PHP Fatal error:  Uncaught exception 'RedisException' with message 'read error on connection' in /var/www/htdocs/wot/vendor/colinmollenhour/credis/Client.php:1044
Stack trace:
#0 [internal function]: Redis->select(8)
#1 /var/www/htdocs/wot/vendor/colinmollenhour/credis/Client.php(1044): call_user_func_array(Array, Array)
#2 /var/www/htdocs/wot/vendor/colinmollenhour/credis/Client.php(603): Credis_Client->__call('select', Array)
#3 /var/www/htdocs/wot/vendor/colinmollenhour/credis/Client.php(462): Credis_Client->select(8)
#4 /var/www/htdocs/wot/vendor/colinmollenhour/credis/Client.php(773): Credis_Client->connect()
#5 /var/www/htdocs/wot/pimcore/lib/Pimcore/Cache/Backend/Redis2.php(761): Credis_Client->__call('sUnion', Array)
#6 /var/www/htdocs/wot/pimcore/lib/Pimcore/Cache/Backend/Redis2.php(761): Credis_Client->sUnion(Array)
#7 /var/www/htdocs/wot/pimcore/lib/Pimcore/Cache/Backend/Redis2.php(452): Pimcore\Cache\Backend\Redis2->getIdsMatchingAnyTags(Array)
#8 /var/www/htdocs/wot/pimcore/lib/Pimcore/Cache/Backend/Redis2.php(644 in /var/www/htdocs/wot/vendor/zendframework/zendframework1/library/Zend/Cache.php on line 209`

Server Infos:
Pimcore 4.3.1
PHP 5.6
94GB RAM
used memory of redis: up to 6GB

**Comment by brusch** [comment]
I assume you're using 'Clear only Output Cache', right? 
I guess there's nothing we can improve, it takes the time it takes...

**Comment by sebastianMoser** [comment]
No, clearing only the output cache works fine.
The problem occurs when we delete the backend cache.

So we cannot clear the cache without running into fatals when using Redis?

I guess there are some options we can do - throwing an exception is not the best way.
If Redis is not responding or available the Caching system should use the configured fallback (=db caching) or just return false and ignore the Caching.

**Comment by kanevbg** [comment]
Have not investigated but ~deleting million keys per minute or ~16k keys per second seems acceptable (based on the provided information). If you believe there is problem please do some benchmarks and find a eventual bottleneck(s). Thanks.

**Comment by sebastianMoser** [comment]
Well, for a production environment this is not acceptable, because while the cache is flushed fatal errors occurs (from other requests, because the redis server blocks) and the website is down.

**Comment by kanevbg** [comment]
Sure, what I said is there is no easy way to improve the performance if there is no application bottleneck on first place. So the problem is better to be fixed by looking for implementation design which will prevent such blocking moments instead of improving the raw performance.
