### ISSUE TITLE
[Bug]: Classification Store type error

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#14459]
### Expected behavior

No error is thrown

### Actual behavior
`
Status: 500 | Internal Server Error
URL: /admin/classificationstore/properties?_dc=1677481949365
Method: GET
Message: Pimcore\Model\DataObject\Classificationstore\KeyConfig::setDescription(): Argument #1 ($description) must be of type string, null given, called in /var/www/html/dev/pimcore/pimcore/lib/Model/AbstractModel.php on line 188
Trace: 
in /var/www/html/dev/pimcore/pimcore/models/DataObject/Classificationstore/KeyConfig.php:188
#0 /var/www/html/dev/pimcore/pimcore/lib/Model/AbstractModel.php(188): Pimcore\Model\DataObject\Classificationstore\KeyConfig->setDescription(NULL)
#1 /var/www/html/dev/pimcore/pimcore/lib/Model/AbstractModel.php(171): Pimcore\Model\AbstractModel->setValue('description', NULL, false)
#2 /var/www/html/dev/pimcore/pimcore/models/DataObject/Classificationstore/KeyConfig/Listing/Dao.php(41): Pimcore\Model\AbstractModel->setValues(Array)
#3 [internal function]: Pimcore\Model\DataObject\Classificationstore\KeyConfig\Listing\Dao->load()
#4 /var/www/html/dev/pimcore/pimcore/lib/Model/AbstractModel.php(225): call_user_func_array(Array, Array)
#5 /var/www/html/dev/pimcore/pimcore/bundles/AdminBundle/src/Controller/Admin/DataObject/ClassificationstoreController.php(1302): Pimcore\Model\AbstractModel->__call('load', Array)
#6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(163): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\ClassificationstoreController->propertiesGetAction(Object(Symfony\Component\HttpFoundation\Request))
#7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#8 /var/www/html/vendor/symfony/http-kernel/Kernel.php(184): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#10 {main}
`
### Steps to reproduce

Open a Classification Store

**Comment by lukmzig** [comment]
@robertSt7 closing the issue because this seems to be resolved by https://github.com/pimcore/pimcore/pull/13605
See [here](https://github.com/pimcore/pimcore/commit/d31bbcc056ad3325fc0d309e6efc6944f0758cee#diff-84deb071723bb01bc61df282f9203b089e43ff48116ab01f5f844cce1320b245R172)
