### ISSUE TITLE
[Bug][Documents][Blocks] Manual mode is not working anymore

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#14465]
### Expected behavior

Manual mode with blocks and area blocks works 

### Actual behavior

throws exception because `start` function does not return anything anymore, so it cannot be used as described here anymore: https://pimcore.com/docs/pimcore/current/Development_Documentation/Documents/Editables/Block.html#page_Using-Manual-Mode

### Steps to reproduce

create document with block in manual mode

Regression of #13869 

- `start` should return `$this`
- also check areablock
- see https://github.com/pimcore/pimcore/pull/13869/files#diff-dd1f76a3addc35093557ab2c0f606902e559901e9b16cee98141840604161f41L232 and https://github.com/pimcore/pimcore/pull/13869/files#diff-d80b7e0f085732af7646014b34c070e2908365436af54dc979d2af09cf0a9ae6L357

**Comment by fashxp** [comment]
@blankse could you have a look there?

**Comment by blankse** [comment]
@fashxp I will take a look at it

**Comment by blankse** [comment]
@fashxp I created a PR #14473
