### ISSUE TITLE
[Task] Narrow allowed types of `InputQuantityValue::convertTo`

### ISSUE THREAD

**Issue by Corepex** [pimcore/pimcore#14474]
Now `InputQuantityValue::convertTo` and `QuantityValue::convertTo::convertTo` allow all types. 

This should be changed to:
`InputQuantityValue` should only accept strings
`QuantityValue` should only accept numbers

_Originally posted by @blankse in https://github.com/pimcore/pimcore/issues/11973#issuecomment-1443380311_

**Comment by blankse** [comment]
@Corepex It can't be a part of 11.1.0 because its a BC break. I included this in https://github.com/pimcore/pimcore/pull/14447
