### ISSUE TITLE
Change `Pimcore\Image\Chromium` to use `chrome-php/chrome`

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#14489]
### Improvement description

Currently it's using the chromium binary, see: 
https://github.com/pimcore/pimcore/blob/c2c4eb0bd3b184c4df272031c1e68cac2ddce33a/lib/Image/Chromium.php#L38

See also: #14457

**Comment by kingjia90** [comment]
I feel i am missing something, the `chrome-php/chrome` requires the binary to work and doesn't come with anything bundled, right?
https://github.com/chrome-php/chrome/blob/4b47ab94531c6c9dd6ecd426d7975c8bfee60ef1/README.md?plain=1#L27

**Comment by brusch** [comment]
@kingjia90 see https://github.com/pimcore/pimcore/pull/14457#issuecomment-1448366982
It should be possible to also connect to a "remote" instance using `ws://....`

**Comment by kingjia90** [comment]
@brusch thank you, cleared that doubt later on

@mcop1 i see that it got assigned to Lukas, but i have some work in progress on https://github.com/pimcore/pimcore/pull/14457 that may solve this as well (my bad, didn't assign myself this issue beforehand), let me know if it's fine if i take over or should we split the tasks

**Comment by lukmzig** [comment]
Hi @kingjia90, if you have some WIP related to this issue, I think it is okay that you would take over since I did not start working on this yet.
