### ISSUE TITLE
[Bug]: Weekday translation key conflicting with short country code (Language)

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#14507]
### Expected behavior

The week day translation keys should be all made to be at least 3 chars (MON,TUE,WED,etc..), even better if not using translation at all and rely on php/js native localization.

### Actual behavior

![image](https://user-images.githubusercontent.com/6014195/222664870-8850fd54-98c2-453e-8569-984e88870ca3.png)
Notice how is `Fr` instead of lowercase

https://github.com/pimcore/pimcore/blob/28dadd20829da6f3e647b01bd8056c9aba9685eb/bundles/AdminBundle/translations/admin.en.yaml#L368-L374

The affected languages beside French, could be like (SU) Sudanese, (TH) Tailandese,  (SA) Saudi Arabian or so.

### Steps to reproduce

In https://github.com/pimcore/asset-metadata-class-definitions/issues/105 was found out that in a language select menu the value `fr` (country code for France) would be translated to `Fr` (as short form of Friday), if you use eg. Italian translation, then it would appear as `Ve` (Venerdi')

**Comment by lukmzig** [comment]
What should be done here:

1. check why lang codes are translated in the first place
2. in asset metadata grid use language names instead of codes (same as DAO grid)
3. remove translation keys as they do not seem to be used anywhere (if related to bug 10.6 otherwise in 11.x)

**Comment by robertSt7** [comment]
10.5 is done
