### ISSUE TITLE
[Feature]: Object Inheritance - Revert fields to inherit again

### ISSUE THREAD

**Issue by danielerne** [pimcore/pimcore#14515]
### Feature description

We have complex data objects for course management and they are inherited for each course date. 
So there's a master object and every date is inherited from this master object.

If the customer is changing a field the field is not inherited anymore. But what if the customer has accidentally changed the field? How can he revert it to a inherited field again? 
There should be a button to activate the inheritance again.

**Comment by mattamon** [comment]
This mechanism is already implemented with many fields. If you reset it to and empty state, the inheritance will kick back in.

E.g. change the Manufacturer of a car in the demo to something else and save it. The value is now overridden. If you empty this relation and save it again you will get the initial state of the inheritance. 

For the date it works similarly. You just have to delete the date. Basically clicking into the field and deleting the content does the trick. 

For an easier way of deleting the content, I agree a button would be nice.

**Comment by danielerne** [comment]
Ah, yes. Thanks for the info.

So then it is not working for the Block Type. We are using it a lot, because it can be inherited instead of field collections.

**Comment by fashxp** [comment]
works for me ... empty every entry of the block and then it starts inheriting again.

**Comment by danielerne** [comment]
@fashxp  I forgot to mention that the block is inside a localized field

<img width="243" alt="Bildschirm­foto 2023-03-06 um 08 44 42" src="https://user-images.githubusercontent.com/546931/223048574-452878ff-41a7-4fe9-bfb8-ab4e516c8fa7.png">

**Comment by danielerne** [comment]
Tested on pimcore demo and it is not working
Block inside localized fields and block with localized fields

<img width="924" alt="Bildschirm­foto 2023-03-06 um 08 52 05" src="https://user-images.githubusercontent.com/546931/223049897-d204b940-a0ef-4721-babd-2b4a705a40a8.png">

<img width="280" alt="Bildschirm­foto 2023-03-06 um 08 52 30" src="https://user-images.githubusercontent.com/546931/223049966-e48c6a36-72ee-4c4b-86e0-ff668d181fcb.png">

**Comment by fashxp** [comment]
that also works for me. 
Important: not empty fields inside block items, but delete all block items themselves. 

![image](https://user-images.githubusercontent.com/8792145/223073495-8d4fe481-df22-4cdc-b72a-59235c0b1d52.png)

**Comment by danielerne** [comment]
@fashxp ah, ok. Thank you for this clarification 🙏
