### ISSUE TITLE
[Bug]: Save of custom layout doesn't work

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#14527]
### Expected behavior

Layout is saved

### Actual behavior
`
Status: 404 | Not Found
URL: /admin/class/save-custom-layout
Method: PUT
Message: Not Found
Trace: 
in /var/www/html/vendor/symfony/framework-bundle/Controller/AbstractController.php:317
#0 /var/www/html/dev/pimcore/pimcore/bundles/AdminBundle/src/Controller/Admin/DataObject/ClassController.php(405): Symfony\Bundle\FrameworkBundle\Controller\AbstractController->createNotFoundException()
#1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(163): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\ClassController->saveCustomLayoutAction(Object(Symfony\Component\HttpFoundation\Request))
#2 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#3 /var/www/html/vendor/symfony/http-kernel/Kernel.php(184): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#5 {main}
`
### Steps to reproduce

Try to save a custom layout

**Comment by lukmzig** [comment]
This is related and should by fixed by https://github.com/pimcore/pimcore/pull/14486 and to the [comment](https://github.com/pimcore/pimcore/pull/14263#pullrequestreview-1319266592)

**Comment by lukmzig** [comment]
Fixed by #14486
