### ISSUE TITLE
[Improvement]: Replace usages of `strftime` and `Carbon::formatLocalized()`

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#14524]
### Improvement description

![image](https://user-images.githubusercontent.com/6014195/222687501-a4954aec-0268-4aad-90d8-e65b23103ac7.png)

src: https://www.php.net/manual/en/function.strftime.php

![image](https://user-images.githubusercontent.com/6014195/222685878-92bc38eb-b20d-4cf6-b378-a86575ca7320.png)

Needs to deprecate and replace the [format parameters](https://www.php.net/manual/en/function.strftime.php#refsect1-function.strftime-parameters), they are not interchangeable with the replacement, for example [%a](https://www.php.net/manual/en/function.strftime.php#:~:text=%2D%2D%2D-,%25a,-An%20abbreviated%20textual) cannot be just [a](https://www.php.net/manual/en/datetime.format.php#:~:text=%2D%2D%2D-,a,-Lowercase%20Ante%20meridiem) 

see also https://github.com/pimcore/pimcore/pull/14431#issuecomment-1441644584

**Comment by kingjia90** [comment]
> Needs to deprecate and replace the [format parameters](https://www.php.net/manual/en/function.strftime.php#refsect1-function.strftime-parameters), they are not interchangeable with the replacement, for example [%a](https://www.php.net/manual/en/function.strftime.php#:~:text=%2D%2D%2D-,%25a,-An%20abbreviated%20textual) cannot be just [a](https://www.php.net/manual/en/datetime.format.php#:~:text=%2D%2D%2D-,a,-Lowercase%20Ante%20meridiem)

Mostly done but for data hub file export and ecommerce framework the challenge is how to tackle this without BC breaks
https://github.com/pimcore/ecommerce-framework-bundle/blob/d75b6a6e52be1d3635ef2fc435082794becc88a4/src/OrderManager/V7/OrderManager.php#L603

We could map the former formats and translate to the desired format, strftime ones are always prefixed by `%` and are one character BUT carbon ISO have no prefix and have a variable length making it hard to distinguish text from parameter, so we may  introduce some "meta-symbols" to tag them, eg.`today is *dd*.xls`) and skip this "translator" when `*anything*` are found or do it once via a migration(?).

see
https://carbon.nesbot.com/docs/#api-localization:~:text=to%20Sa)%2C%20translatable-,ddd,-Thu
 ![image](https://github.com/pimcore/pimcore/assets/6014195/1660c168-3fa4-48f0-a9aa-968fe5b2c82f)


Alternatively, creating a new config for existing config fields and deprecate the current one, and use the new one when is set.

Another input would be introducing something more custom (instead of `*dd*` to `*MIN_DAY_NAME_T*` or `*MDNT*`) and properly documented, that we can limit and have more control on, because we actually don't/shouldn't support every date format parameter, eg. `strftime('today is %D.xls', time());` results in a date with forward slashes (which is forbidden for filenames) as `m/d/Y`.

**Comment by markus-moser** [comment]
@kingjia90 Please let's solve it like this:

- [x] Ecommerce framework: go with your suggested "new config option" solution https://github.com/pimcore/ecommerce-framework-bundle/pull/185
- [x] Data hub file export: let's do a new major release at the end of the year and introduce the new date format there. https://github.com/pimcore/data-hub-file-export/issues/160

**Comment by mcop1** [comment]
@kingjia90 I am currently working on https://github.com/pimcore/data-hub-file-export/issues/160 and had a look at the implementation in ecom framework. It uses Carbon, but doesnt require it in composer.json - as far as I can see. Maybe I missed something, but it should probably be added there.
