### ISSUE TITLE
Deprecations in 10.6 for removed methods are missing

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#14525]
see #13888

              @brusch @mcop1 deprecations in 10.6 for removed methods are missing

_Originally posted by @fashxp in https://github.com/pimcore/pimcore/issues/13888#issuecomment-1453272135_

**Comment by fashxp** [comment]
also add `Data::getFieldType()` to 10.6 if possible

**Comment by mcop1** [comment]
> also add `Data::getFieldType()` to 10.6 if possible

JFI: Method is already there, but not abstract. We will leave it as it is in 10.6.
