### ISSUE TITLE
Retina/HDPI Support for image assets dragged into WYSIWYG

### ISSUE THREAD

**Issue by jstsch** [pimcore/pimcore#1452]
### Expected behavior 

When I drag a high-resolution image asset into a WYSIWYG field I expect to receive see a retina version of the image on a retina screen. Preferably using srcset. Perhaps we should be able to set one of the Thumbnail configurations to be used for all WYSIWYG fields?

### Actual behavior  

The image is non-retina, the returned HTML has a thumbnail image which is the same width as the CSS width (as set by CKEditor).

```html
<p><img pimcore_id="39" pimcore_type="asset" src="/website/var/tmp/image-thumbnails/0/39/thumb__auto_7e7e0dad23d3cca166d67825e3368bc6/dsc04344.jpeg" style="width:600px" /></p>
```

### Steps to reproduce  

1. Go to demo.pimcore.org
2. Open a blog object
3. Drag in one of the photos from the Assets/Examples folder
4. Observe that the image is 600 actual pixels wide.
5. Observe that even if you remove the thumbnail from the src, and after saving a new thumbnail is made with the same 600 pixels.

The same happens with WYSIWYG fields in Documents.

**Comment by brusch** [comment]
Related to #1507
