### ISSUE TITLE
[Bug]: Scheduled tasks doesn't execute

### ISSUE THREAD

**Issue by SamyMP** [pimcore/pimcore#14530]
### Expected behavior

When creating a scheduled task in an object, it should trigger when the time comes

e.g. Unpublish an object

![image](https://user-images.githubusercontent.com/35225430/222745253-e3edae37-13e2-4f12-aa2b-08ae59fe1fe9.png)

### Actual behavior

The tasks doesn't execute

e.g.  The object is still published

### Steps to reproduce

1. Make sure maintenance is enabled and running
2. Create a scheduled task to unpublish an object
3. Wait until the time comes
4. Reload the object

Note: I have waited several hours after the time had passed to make sure it was an issue.

Version 10.5.18

**Comment by mattamon** [comment]
@SamyMP I was able to reproduce the problem. Thank you for your issue.
Another strange behavior I noticed, that when I update the time, an hour will be added automatically. 
So If I schedule something for 10:00, it will automatically be 11:00.

**Comment by SamyMP** [comment]
I saw that the problem you describe is supposed to be solved by #10367 which was a while ago. Have you set a timezone in your `config.yaml` ?
I don't have this problem of hour being added, just the scheduled task that doesn't execute

**Comment by mattamon** [comment]
Ah no I did not, was just wondering about that, but thanks for the heads-up. We gonna check what we can do with the scheduling problem!

**Comment by SamyMP** [comment]
No problem, thank you for investigating this 🙂

**Comment by mattamon** [comment]
@SamyMP can you please check your logs?
I had some errors related to some custom implementations. 

I ran bin/console maintenance manually now a few times and there the scheduling worked fine for me.

**Comment by SamyMP** [comment]
I've run the maintenance manually a few times (on top of having the cron running) but the tasks are still not executed 😕
This is quiet odd

Edit: What kind of log should I be looking for ? I've trying in `dev.log`, `usage.log` and `php.log` but I didn't notice anything strange

**Comment by mattamon** [comment]
Hmm, I had some errors when I ran maintenance with `-vv` which basically stopped my scheduled tasks from executing. 

It should be in one of the logs you mentioned. 
Can you debug it a bit more? 
It should all be in this file https://github.com/pimcore/pimcore/blob/10.5/lib/Maintenance/Tasks/ScheduledTasksTask.php#L58
Basically, it's just a Listing that gets processed.

**Comment by SamyMP** [comment]
I'll see what I can do and I'll get back to you

**Comment by SamyMP** [comment]
Hi @mattamon, 

I did some experimentation and here's what I found : 
The tasks are executed if you set up the cron that regularly start the maintenance (`pimcore:maintenance --async`) **and** the `messenger:consume` command.

It is actually documented, here's the [documentation](https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Installation.html#page_5-Maintenance-Cron-Job). I personally find it unclear because of this sentence :

>  The `pimcore:maintenance` command will add the maintenance messages to the bus and **runs them afterwards immediately from the queue.** However it's recommended to setup independent workers that process the queues, by running `bin/console messenger:consume pimcore_core pimcore_maintenance pimcore_image_optimize` (using e.g. Supervisor) and adding `--async` option to the `pimcore:maintenance` command that stops the maintenance command to process the queue directly.

It says it "runs them afterwards immediately", but it doesn't if you don't add the `messenger:consume` command, although it is said the latter is "recommended".

Maybe we could add some explicit instructions in the note in the [Scheduling documentation](https://pimcore.com/docs/pimcore/current/Development_Documentation/Tools_and_Features/Scheduling.html) ?

What do you think ? Is it still a "bug" or does it really requires `messenger:consume` as of now ?

**Comment by mattamon** [comment]
@SamyMP Ah i see the confusion here. Maybe the docs are not as clear as they should be. 
You have to run both commands . It is just recommended to run it using a process control system like Supervisor
Check the upgrade notes from 10.2
https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/index.html#page_10-2-0


Maybe you could do a PR to clear up the documentation a little more?

**Comment by SamyMP** [comment]
I wouldn't mind doing a pull request to update the doc, I'll try to do that before the end of the week if I have time. I would need to update both the current and the 11.x doc though ? That makes 2 different pull request ?

**Comment by mattamon** [comment]
We recently updated all the docs and shifted them into another location. 
I would update it for 10.5, then we merge it into 10.6 and 11.x and then let's check what's left of your PR :) 
We will take that the info is not lost :)

**Comment by dvesh3** [comment]
Closed as nothing to fix here. PRs are welcomed for improving the docs 😊
