### ISSUE TITLE
[Bug]: PIMCore can not handle Redis as targeting storage

### ISSUE THREAD

**Issue by eciosk** [pimcore/pimcore#14549]
### Expected behavior

Correctly log in and use Redis as targeting storage.

### Actual behavior

I receive an exception: "Detected CSRF Attack! Do not do evil things with pimcore … ;-)"

### Steps to reproduce

1. Put the following config into your files
2. Restart containers.
3. Try to log in.

config.yaml
pimcore:
    targeting:
        storage_id: Pimcore\Targeting\Storage\RedisStorage

services.yaml
pimcore.targeting.storage.redis.connection:
    class: Credis_Client
    arguments:
        $host: '%env(REDIS_HOST)%'

Pimcore\Targeting\Storage\RedisStorage:
    arguments:
        $redis: '@pimcore.targeting.storage.redis.connection'

Version: 10.4.3

Note: In the example config in the docs you suggest using 'Pimcore\Storage\Redis\ConnectionFactory' but as far as I can tell this class has been deleted about 5 years ago.

Do I miss something in my config?

**Comment by kamilawiercinska** [comment]
Hello, can we please have an update on this one?

**Comment by kingjia90** [comment]
Hello, i'm currently working on this and will let you know by the end of the day.
Thank you for your patience

**Comment by kingjia90** [comment]
I've took a deeper look witth the same exact Pimcore version but couldn't reproduce the exact problem.

The config looks totally fine (beside the missing indentation). 

It would surely "crash" before that `Detected CSRF Attack` message, if it was syntaxically wrong, and if misconfigured Redis server throws something like 
![image](https://user-images.githubusercontent.com/6014195/230088830-4acc9f7b-d69a-4937-9aba-ccb1dc3ffefc.png)

Must be something else, would need further details on how to reproduce it.


Just one extra check, you are not double-clicking on the login button, right? It happens to me that sometimes it triggers this CSRF message if i do that

**Comment by eciosk** [comment]
@kingjia90 Thanks for response. The reason to use redis as targeting storage is to share session between multiple docker containers. Given config works fine but only with one pimcore container. If I add second container with pimcore I recieve csrf exception.
Did you try given config with multiple pimcore docker containers?

**Comment by kamilawiercinska** [comment]
@kingjia90 can you please give an update on this one?

**Comment by kingjia90** [comment]
@kamilawiercinska yes, thank you for your patience.

Knowing that the purpose is to share session between different containers and as we excluded “direct” Redis setup issues, i would like to suggest to check if the symfony configuration mentioned in the following link are set up accordingly
https://symfony.com/doc/5.4/session.html#store-sessions-in-a-key-value-database-redis
