### ISSUE TITLE
Unrelated code introduced by #14175

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#14542]
### Improvement description

#14175 introduced this code block in the configuration, which seems to be useless: 

https://github.com/pimcore/pimcore/blob/f5edb29173a9beeed856b9f8715799599912a962/bundles/CoreBundle/src/DependencyInjection/Configuration.php#L864-L877

**Comment by kingjia90** [comment]
Confirmed, actual implementation should be as seen on https://github.com/pimcore/pimcore/pull/14047
