### ISSUE TITLE
[Bug][11]: Ecommerce and Personalization bundles: `targetGroup.js` loading priority issue

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#14552]
### Expected behavior

It should either load the JS `pimcorepersonalization/js/ecommerce/pricing/conditions/targetGroup.js` in the ecommerceFramework bundle among the `getJsPaths` (since it's a dependentBundle) https://github.com/pimcore/pimcore/blob/7015390dfa11b2f318ddb89a2fb24533c539d4e7/bundles/EcommerceFrameworkBundle/src/PimcoreEcommerceFrameworkBundle.php#L91 and/or be directly moved over in that folder/bundle

### Actual behavior

Currently,  the JS would crash  if you load PersonalizationBundle before EcommerceFrameworkBundle due this line 
https://github.com/pimcore/pimcore/blob/7015390dfa11b2f318ddb89a2fb24533c539d4e7/bundles/PersonalizationBundle/src/PimcorePersonalizationBundle.php#L63

### Steps to reproduce

Just use 11.x demo, see also https://github.com/pimcore/demo/pull/436

Related https://github.com/pimcore/pimcore/issues/12526, https://github.com/pimcore/pimcore/issues/12523

**Comment by jdreesen** [comment]
If it depends on the other one, it should probably be stated via https://github.com/pimcore/pimcore/blob/11.x/lib/HttpKernel/Bundle/DependentBundleInterface.php#L37
This should ensure the correct loading order.

**Comment by kingjia90** [comment]
> If it depends on the other one, it should probably be stated via https://github.com/pimcore/pimcore/blob/11.x/lib/HttpKernel/Bundle/DependentBundleInterface.php#L37

it is already like that:
https://github.com/pimcore/pimcore/blob/7015390dfa11b2f318ddb89a2fb24533c539d4e7/bundles/EcommerceFrameworkBundle/src/PimcoreEcommerceFrameworkBundle.php#L88-L93

the issue is that the JS loading order seem based on the list under `config/bundles.php`

**Comment by jdreesen** [comment]
But that says that the Ecommerce bundle depends on the Personalization bundle, however it seems to be the other way around (at least for the JS file).

**Comment by kingjia90** [comment]
PersonalizationBundle should be independent to ecommerceFramework, so moving this specific js to the ecommerceFramework would make sense

**Comment by dvesh3** [comment]
I would move this to EcommerceBundle since the js file uses the bundle namespace https://github.com/pimcore/pimcore/blob/d505e46b8b9ff9505e2fb1f1bcb0616321a3b8a8/bundles/PersonalizationBundle/public/js/ecommerce/pricing/conditions/targetGroup.js#L20
