### ISSUE TITLE
Change Maintenance Mode to use TmpStore

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#14575]
Also check whether `\Pimcore\Tool\Admin::scheduleMaintenanceModeOnLogin()` is still relevant.

**Comment by fashxp** [comment]
@brusch we could also use tmpstore or settings store table, right?
when using cache, a pimcore:cache:clear could accidentally deactivate maintenance mode

**Comment by brusch** [comment]
@fashxp I was thinking about performance here, because this would need to be checked on every request, but theoretically it would also work with database-based storages, yes 😊 

Maybe there's even something better for that, or we make it configurable, e.g. with a dedicated cache pool or so ...

**Comment by brusch** [comment]
Let's go for `TmpStore`, it's the most error proof solution.
