### ISSUE TITLE
[Bug][11]: Pimcore\Config::setWebsiteConfig() cannot handle empty Website Settings

### ISSUE THREAD

**Issue by elbkapitaenehh** [pimcore/pimcore#14577]
### Expected behavior

Make sure $config is initialized as empty array in app/vendor/pimcore/pimcore/lib/Config.php

### Actual behavior

In a new installation of v11.0.0-ALPHA6 the following exception occurs on the startpage when the content is not delivered from the cache:

`Pimcore\Config::setWebsiteConfig(): Argument #1 ($config) must be of type ?array, bool given, called in /Volumes/Projekte/pimcore/demo-11/app/vendor/pimcore/pimcore/lib/Config.php on line 287`

in app/vendor/pimcore/pimcore/lib/Config.php Line 16 sets $config to false if not available in the cache, which produced the error further on. 

```
  $config = Cache::load($cacheKey); // -> can be false
  if (!$config) {
    ...
   } elseif (is_array($config)) {
    ... 
  }

  self::setWebsiteConfig($config, $language); // -> throws error when $config is false
```

### Steps to reproduce

* use a fresh installation of v11.0.0-ALPHA6 (with no website settings)
* clear the cache
* access the startpage

**Comment by mattamon** [comment]
Thank you @elbkapitaenehh, we gonna take a look!

**Comment by mattamon** [comment]
@elbkapitaenehh 
#14579 should fix your problem. Maybe you can check if it actually resolves it.

**Comment by elbkapitaenehh** [comment]
@mattamon yes, it does. Thx.
