### ISSUE TITLE
`ConsoleCommandPluginTrait` and `ConsoleOutputDecorator` obsolete? 

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#14600]
### Improvement description

Seems that `ConsoleCommandPluginTrait` and `ConsoleOutputDecorator` are obsolete.
It's not used or documented somewhere. If so we should deprecate in `10.6` and remove it in `11.x`.

**Comment by mattamon** [comment]
The `ConsoleOutputDecorator` is used in the InstallCommand: https://github.com/pimcore/pimcore/blob/11.x/bundles/InstallBundle/src/Command/InstallCommand.php#L390

The `ConsoleCommandPluginTrait ` can be deprecated in 10.6
I did not find any usage.

I also tried to remove the `ConsoleOutputDecorator` with the following result at installation:

![image](https://user-images.githubusercontent.com/38959016/224927711-a35d3fae-d039-4710-8235-94b65435dd80.png)

**Comment by aryaantony92** [comment]
Fixed by #14646
