### ISSUE TITLE
[Bug]: CStore invisible paramter corrupt the layout

### ISSUE THREAD

**Issue by mohammed-mahmoud-scandi** [pimcore/pimcore#14638]
### Expected behavior

Siting visibility to false should make this input invisible 

### Actual behavior

UI get corrupted with this message in the console 
it seems that the field -CSTORE- does not implement the isRendered() method and doesn't contain this.component

![image](https://user-images.githubusercontent.com/121216666/224753528-e38d191a-854c-4970-930f-9a593dda9e11.png)

### Steps to reproduce

1- create a controller with method to handle requests 
2- add route to this method
3- create new object from this class 
`use Pimcore\Model\DataObject\ClassDefinition\Data\Input;`
4- decode json request and map invisible to setInvisible method
`$dataObject->setInvisible($requestDataDefinition->invisible ?? null);`
5- add this key to CStore group
6- add CStore to any class (Product)
7- create object of that class 
8- when loading CStore Tab, UI get corrupted

**Comment by robertSt7** [comment]
@mohammed-mahmoud-scandi Thanks for reporting this bug. Unfortunately I am not able to reproduce it. Could you please provide more information? Thanks

**Comment by fashxp** [comment]
Closed due to inactivity
