### ISSUE TITLE
Do not care about Symfony environments

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#14647]
### Improvement description

Currently there are multiple locations where Pimcore is dealing with Symfony environments directly, e.g.: 
```
\Pimcore\Tool::getCachedSymfonyEnvironments()
```

This is sometimes also used by bundles, e.g. here: 
https://github.com/pimcore/portal-engine/blob/3.x/src/Service/PortalConfig/FrontendBuildService.php#L207

In general Pimcore shouldn't care about environments and so we need to check how we can get rid of those code pieces. 
Either by providing better UI feedback and/or documentation.

**Comment by dvesh3** [comment]
@brusch In the core, this is only used to provide options to clear cache for specific environments (based on which env folders are available in the cache dir).
![image](https://github.com/pimcore/pimcore/assets/5137917/759a6c4a-0a8c-4892-8b3e-3ab9eb0f8232)

Should we get rid of these options in Admin UI and always clear current environment cache?

**Comment by dpfaffenbauer** [comment]
I never cleared the cache for the not used environment, so I don't really see a point of having the option to do that.

**Comment by brusch** [comment]
@dvesh3 I'd remove the entire `Cache` menu from the UI. 
There are already commands for clearing the Symfony and the Pimcore data cache, that's the way how it should be used. 
For clearing temporary files, I'd create a section in our docs, how to clear them using system tools (`rm -r` on traditional filesystems or other tools for object storages like S3, ...)   and also explain the possible impacts when doing so (high load on server because of regenerating thumbnails, ...)

**Comment by dpfaffenbauer** [comment]
@brusch Sometimes it is necessary to clear the Pimcore Data Cache due to inconsistencies in the data-model between deployments or just having some odd behaviour. we have to do that quite often honestly (more often than I want it to)

**Comment by brusch** [comment]
Even if running `./console pimcore:cache:clear` after deployment? 🤔 It's actually doing the same.

**Comment by dpfaffenbauer** [comment]
@brusch we don't wanna clear the cache each time we have a deployment, we sometimes do 10-20 deployments a day, and clearing the cache each time has a negative effect on runtime performance.

**Comment by dvesh3** [comment]
@brusch I think removing the options with minor release is not a good idea. I guess we just need to trigger the deprecation, if someone is using these options from the UI and also mark them deprecated in API. Also, need to consider user permissions `clear_cache`, `clear_fullpage_cache` & `clear_temp_files` for removal afterwards.

**Comment by brusch** [comment]
Agree, but maybe we should create a follow-up ticket for v12 then 😊 
Thanks!
