### ISSUE TITLE
[Bug]: AssetUpdateTasksHandler cleanup

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#14656]
### Behavior

The `AssetUpdateTasksHandler` loads the asset from the storage and process it locally. We have a weird issue that ghostscript throws seg-fault errors.  Pimcore sort of catches the issue, but it doesn't cleanup the tmp storage folder.

We run supervisor for messenger consume tasks with a time-limit of an hour and a memory-limit of 250mb. The problem is that our Cluster Nodes have very little storage. So Pimcore loads the assets, tries to process them (with ghostscript) and throws an error. It loads about 30 gigs of data before the pod gets evicted and removed. Supervisor never restarts the process, (or initiates the shutdown so Pimcore cleans-up the files).

The `AssetUpdateTasksHandler` should clean up the file before giving an ack or no-ack.

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/14688
