### ISSUE TITLE
[Bug]: Unique contraint still allows for duplicated data

### ISSUE THREAD

**Issue by rjankiew** [pimcore/pimcore#14654]
### Expected behavior

When choosing "unique" option in object model for an input field, it should not be possible to create an object with duplicated value on this field.

### Actual behavior

Although UNIQUE constraint is added to `object_store_*` table on a proper column, it is still possible to assign duplicated value both through the UI and API.

### Steps to reproduce

 Create "SomeObject" class with "someUniqueField" of type input, and set it to unique. Then:

```php
$object = new SomeObject();
$object->setKey('1');
$object->setParent(Folder::getByPath('/'));
$object->setSomeUniqueField('test');
$object->save();

$anotherObject = new SomeObject();
$anotherObject->setKey('2');
$anotherObject->setParent(Folder::getByPath('/'));
$anotherObject->setSomeUniqueField('test');
$anotherObject->save();
```

…should result in some kind of constraint violation exception, but doesn't.

**Comment by Corepex** [comment]
Hi @rjankiew, I tested the scenario you described, and I can't really reproduce it. I tried to save the object via the AdminUI and via the API, and both work for me. 
Pimcore gives me a "unique constraint violation" exception. 

Do I understand something wrong? Did I miss something?
Tested in 10.5 (10.6) and 11.x

<img width="350" alt="image" src="https://user-images.githubusercontent.com/16717695/226566194-88eccd16-a614-4923-8fad-48852b03cf53.png">
<img width="536" alt="image" src="https://user-images.githubusercontent.com/16717695/226566215-6f5b231a-7c47-40a0-bfc4-e3be86211263.png">

**Comment by rjankiew** [comment]
@Corepex I guess you did understand, somehow it  just doesn't work for me, and can even lead to erasing data from exising objects - at least that's how it looks on the UI. I have this issue with one project only. 

I'm a bit at a loss, since I see that unique constraint was added to the database. Are `object_store_*` tables the only place where the constraint should be added? Could you maybe point me in the right direction with debugging? Could it be generated class code or database schema issue?

**Comment by Corepex** [comment]
@rjankiew, the according error will be thrown here. 
https://github.com/pimcore/pimcore/blob/58bc2480063d544ac4e5e86860f286ee5e446988/models/DataObject/AbstractObject.php#L596-L598

You could check via step-by-step debugging if everything works at your instance.

Besides that, you could also try to reproduce the problem on our official demo instances. 

Let me know if you could reproduce it there :)

**Comment by rjankiew** [comment]
@Corepex  I checked with the step debugging, and suddenly it's fine. I did an update in the meantime, strange still that it did not work… Probably not something to dig into anyway.
