### ISSUE TITLE
[Improvement]: allow disabling generating thumbnail, counting pages, extracting text from documents

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#14683]
### Improvement description

Currently, your document-like assets are being processed for several things:
1. page count
2. creating a thumbnail
3. extracting text

These features are valuable in some situations, but if you don't need them, you'd like to disable them without your error logs (Sentry) getting filled in by Pimcore:
https://github.com/pimcore/pimcore/blob/d823d70c22fee63d9dbccf9bb85ef9149531ba0a/models/Asset/Document.php#L57

Ideally, I'd like to disable these in config and have everything work as if they're not yet created, but *not* get errors regarding adapters being unavailable.

**Comment by fashxp** [comment]
also might reduce load on the system if really not needed.
