### ISSUE TITLE
[Image Thumbnails] Better handling of SVG files

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#1468]
If you upload a svg vector file as asset and drop it into a document using an image tag (for example into the featurette in the demo.pimcore.org), it'll be output as png file (thumbnail and embedded image). The png has less quality and a bigger file size. Since svg is supported by > 97% of browsers ( http://caniuse.com/#search=svg ), I'd suggest to handle SVG files differently in Pimcore 5 and display them directly instead of converting them.

**Comment by vanwilligen** [comment]
Please fix this issue. It's unacceptable (in 2017) you can't use SVG's as asset.

**Comment by brusch** [comment]
PRs are welcome all the time ;-)

**Comment by Cruiser13** [comment]
I think the main issue here is the integration with thumbnails. We'd need to dynamically set the width and height of the SVGs to the thumbnail size a PNG or other image format would have.

**Comment by brusch** [comment]
And we also have to keep in mind that there are use-cases where you'd like to rasterize the SGV (high complex SVGs, not suitable to be displayed in browsers, SVG with embedded raster graphics, ...). 
So just passing SVGs through would produce new problems.

**Comment by brusch** [comment]
Also no chance to fully support all transformations, like cover, frame, contain, rounded corners,  background ... especially when chained together.

**Comment by brusch** [comment]
Only `resize`, `scaleByWidth` and `scaleByHeight` can be supported.

**Comment by brusch** [comment]
Solved by another config option: 
![image](https://user-images.githubusercontent.com/142037/42378947-6fb2e16c-8129-11e8-8c41-057674583987.png)

Even mixed configurations are possible: 
![image](https://user-images.githubusercontent.com/142037/42378984-93c8bfa4-8129-11e8-8d3c-ddf22f2f27a3.png)

![image](https://user-images.githubusercontent.com/142037/42378971-8b807918-8129-11e8-8eea-eddc3827130e.png)

**Comment by Cruiser13** [comment]
Very nice, thanks!

**Comment by Shalice1218** [comment]
> Solved by another config option: ![image](https://user-images.githubusercontent.com/142037/42378947-6fb2e16c-8129-11e8-8c41-057674583987.png)
> 
> Even mixed configurations are possible: ![image](https://user-images.githubusercontent.com/142037/42378984-93c8bfa4-8129-11e8-8d3c-ddf22f2f27a3.png)
> 
> ![image](https://user-images.githubusercontent.com/142037/42378971-8b807918-8129-11e8-8eea-eddc3827130e.png)

May I know where I can find these settings, please, is it theme restricted? I am using OceanWP. I tried to use SVG for my product image, it works well in a single product page, but if I archive them in Gutenberg with a product filter, the image is far too small, I tried to add additional CSS in the Gutenberg, but still, it doesn't work.
