### ISSUE TITLE
[Task]: Move EnabledTrait to GoogleMarketingBundle

### ISSUE THREAD

**Issue by aryaantony92** [pimcore/pimcore#14693]
### Improvement description

The Trait https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/src/EventListener/Traits/EnabledTrait.php is shared between the GoogleMarketingBundle and the PersonalizationBundle.

For PersonalizationBundle, it is not used anymore.

Move the trait to the GoogleMarketingBundle and remove it from the core.

**Comment by brusch** [comment]
This needs to be redone in https://github.com/pimcore/google-marketing-bundle and removed in this repo ... thanks!

**Comment by dvesh3** [comment]
Fixed by 
#14784
https://github.com/pimcore/ecommerce-framework-bundle/pull/7
https://github.com/pimcore/google-marketing-bundle/pull/5
