### ISSUE TITLE
[Improvement]: Filter the data in dependencies view.

### ISSUE THREAD

**Issue by Geni2** [pimcore/pimcore#14690]
### Improvement description

Hi,

Currently, if you have a lot of dependencies it's very hard to go through all of them and find what you are looking for, so one solution for this is to have a search or filter as it exists in the Notes & Events view for example.
This could be a very important feature for all the users who use the dependencies view often.

Now there is a solution for this and you can filter the data based on their Path.
Follow up [#14671](https://github.com/pimcore/pimcore/pull/14671)

**Comment by brusch** [comment]
Closing this as there's already a PR for that: https://github.com/pimcore/pimcore/pull/14671
