### ISSUE TITLE
[Bug]: Typed property $fieldtype must not be accessed before initialization

### ISSUE THREAD

**Issue by mattamon** [pimcore/pimcore#14703]
### Expected behavior

This bug actually occurred while trying to add a filter condition in the AdvancedObjectSearchBundle

Adding a new condition should not result in an error message

### Actual behavior

Adding a new condition results in the following error
![image](https://user-images.githubusercontent.com/38959016/226357449-dd5aca93-f5df-4c7b-84f3-1c5cb10d6d61.png)

### Steps to reproduce

1. Install AdvancedObjectSearchBundle
2. Try to add a new "SavedSearch" via the menu
3. Use e.g. event as class and try to add a condition
4. Error occurs

**Comment by SamyMP** [comment]
For information, same thing happens when trying to compare 2 objects in the [11.x-dev environment](https://11.x-dev.pimcore.fun/admin/) with the object merger plugin

![image](https://user-images.githubusercontent.com/35225430/226358879-7f3614d6-7f59-4d23-8ee0-4c53ae5040f1.png)

**Comment by mattamon** [comment]
@SamyMP ah good to know! Maybe this fixes even more problems!
