### ISSUE TITLE
[Bug]: Can't open Voucher Details

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#14716]
### Expected behavior

No error is thrown

### Actual behavior

![image](https://user-images.githubusercontent.com/104770750/226635616-ccd9aa47-1d5c-4190-88b1-ecdbc3048c68.png)

### Steps to reproduce

Open Voucher Details

**Comment by martineiber** [comment]
Fixed in https://github.com/pimcore/ecommerce-framework-bundle/pull/10
