### ISSUE TITLE
[Bug]: Infinite Messenger Loop with `AssetUpdateTasksMessage` and `Asset\Document` files

### ISSUE THREAD

**Issue by jheimbach** [pimcore/pimcore#14720]
### Expected behavior

`AssetUpdateTasksMessage` should fail if `Asset\Document` page count cannot be extracted

### Actual behavior

The `AssetUpdateTasksMessage` creates an infinite loop of Messages trying to get the page count.

### Steps to reproduce

If a document asset file (tested with .docx and .pdf) is uploaded that for some reason cannot be converted to a pdf (e.g. because the .docx file is password protected) or the file is missing from storage.

If a AssetUpdateTaskMessage with this "broken" Asset is now added to the Queue, it will create an infinite loop of `AssetUpdateTaskMessage` messages.

Debugging:
 - the [pagecount process in the message handler]( https://github.com/pimcore/pimcore/blob/11.x/lib/Messenger/Handler/AssetUpdateTasksHandler.php#L64) fails because the underlying Adapater fails (does not matter why it fails). The  CustomSetting `document_page_count` will be set to "failed".
 - [the following `getImageThumbnail` call will add a new `AssetUpdateTaskMessage`](https://github.com/pimcore/pimcore/blob/11.x/models/Asset/Document.php#L107) because the CustomSetting `document_page_count` is "failed"

**Comment by fashxp** [comment]
See #14686

**Comment by jheimbach** [comment]
I searched for the open tickets before writing my own... looks like not thoroughly enough. 

Will close this ticket in favor of the linked one.
