### ISSUE TITLE
Symfony 6.3 scheduler 

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#14757]
### Improvement description

Symfony 6.3 will introduce a Scheduler Component that solves the maintenance tasks thing quite nicely. Pimcore 11 should take advantage of that:

https://github.com/symfony/symfony/tree/6.3/src/Symfony/Component/Scheduler

**Comment by jdreesen** [comment]
Here are the slides from SymfonyLive Paris 2023: https://speakerdeck.com/fabpot/s

**Comment by brusch** [comment]
Very nice! But unfortunately it's already too late for considering it for `11.0` release, but maybe it's possible to have it in `11.1` without any bc-breaks 😊
