### ISSUE TITLE
Object bricks - add check for reserved keywords in object brick name

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#1480]
When someone creates an object brick called "Metadata" an exception will be thrown if afterwards an object of the related class gets opend (in the tree or by ID) as there already a "getMetadata()" method exists. Also deleting the object brick doesn't solve the problem immediately - it was necessary to save the class again and to clear the cache. Sometimes object bricks are created by the customer directly. If the customer then creates a brick called "Metadata" he has no chance to get the system up and working again as he will not know that he has to play arround with saving the class and clearing the cache in order to get it to work again.

Therefore a check for reserved names in object brick names would be useful.

**Comment by markus-moser** [comment]
I created a separate issue for the part that deleting an object brick could break the system: #1481

**Comment by dpfaffenbauer** [comment]
If you are working on bricks, could you please change identification of bricks from ID's to Names? As my PR did for Version 4, but was rejected due to Pimcore 5.

**Comment by markus-moser** [comment]
I was wrong: Metadata is not a reserved keyword... But it happens with for example a brick name like "Items" or "Object"

**Comment by weisswurstkanone** [comment]
build 4080 pimcore4, build 52 pimcore5
