### ISSUE TITLE
Move Ecommerce Config to Bundle Repo

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#14810]
### Improvement description

File https://github.com/pimcore/pimcore/blob/11.x/bundles/EcommerceFrameworkBundle/src/Resources/config/order_agent.yaml got added to this repo by #14679 

Needs to be moved to `pimcore/ecommerce-framework-bundle`.

**Comment by dvesh3** [comment]
please see https://github.com/pimcore/ecommerce-framework-bundle/issues/12
