### ISSUE TITLE
Deletion of an object brick requires saving the related class and clearing the cache

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#1481]
When a brick gets deleted for example the object tree will crash as somewhere the brick getter still exists in the code. Afterwards it's needed to play around with saving the related class and clearing the cache to make it work again.

**Comment by weisswurstkanone** [comment]
Unable to reproduce. Maybe a side-effect of #1480 (which has been fixed already) ?

**Comment by weisswurstkanone** [comment]
Not related to #1480 but already fixed anyway.

In the affected build 4021 the class_* cache tags were not written correctly. The object_* tags were ok but the class_* tags are of critical importance when class definitions are changed.
