### ISSUE TITLE
[Improvement] Change all return types to mixed

### ISSUE THREAD

**Issue by mattamon** [pimcore/pimcore#14817]
### Improvement description

Tests are always failing because of too strict types. Changing them to mixed would guarantee more successfully executed tests.

**Comment by dvesh3** [comment]
Maybe we just kick phpstan completely. Wdyt?

**Comment by mattamon** [comment]
> Maybe we just kick phpstan completely. Wdyt?

Sounds good to me. Maybe kick all tests since they are pretty error prone? 
Maybe also kick the docs since code should be documentation enough?

**Comment by dvesh3** [comment]
yes, remove docs as well since AI is here to explain it 😉

**Comment by mattamon** [comment]
> yes, remove docs as well since AI is here to explain it 😉 

Perfect. Since we modernize the architecture we could also modernize the programming language to something more common, like Cobol or Fortran? Any other ideas?

**Comment by kingjia90** [comment]
> Maybe we just kick phpstan completely. Wdyt?

Let’s outsource all to Sebastian, and call this workflow PHPStian

**Comment by mattamon** [comment]
> > Maybe we just kick phpstan completely. Wdyt?
> 
> Let’s outsource all to Sebastian, and call this workflow PHPStian 

@blankse wdyt? Would you be up for this task?

**Comment by blankse** [comment]
@mattamon @kingjia90 😂 Made my day
