### ISSUE TITLE
Revisit URL slug check validity 

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#14813]
### Improvement description

please see https://github.com/pimcore/pimcore/pull/14301#issuecomment-1491893317

**Comment by NiklasBr** [comment]
Here's a list of allowed characters: https://stackoverflow.com/a/1547940

**Comment by NiklasBr** [comment]
While revisiting the validation, may I suggest to also return the offending characters? Something like this:

```php
if (preg_match_all('/[#\?\*\:\\\\<\>\|"%&@=;]/', $item->getSlug(), $matches)) {
    throw new Model\Element\ValidationException('Slug contains forbidden characters: [ ' .  implode(' ', $matches[0]) . ' ] ');
}
```
Could save a lot of digging around.

**Comment by Cruiser13** [comment]
Is this issue responsible for issues with chinese letters in url slugs being removed too?
This will not work as pretty url / url slug anymore for example:
/zh/搜索

**Comment by Corepex** [comment]
> Is this issue responsible for issues with chinese letters in url slugs being removed too? This will not work as pretty url / url slug anymore for example: /zh/搜索

@Cruiser13, no that shouldn't affect other languages since we only replace certain chars (like a blocklist). 

See: https://github.com/pimcore/pimcore/blob/212044d146eb7ffcf832b14440bff01e955f97da/bundles/AdminBundle/Resources/public/js/pimcore/object/tags/urlSlug.js#L155

**Comment by Corepex** [comment]
> While revisiting the validation, may I suggest to also return the offending characters? Something like this:
> 
> ```
> if (preg_match_all('/[#\?\*\:\\\\<\>\|"%&@=;]/', $item->getSlug(), $matches)) {
>     throw new Model\Element\ValidationException('Slug contains forbidden characters: [ ' .  implode(' ', $matches[0]) . ' ] ');
> }
> ```
> 
> Could save a lot of digging around.

@NiklasBr since the check is done here: 

https://github.com/pimcore/pimcore/blob/212044d146eb7ffcf832b14440bff01e955f97da/bundles/AdminBundle/Resources/public/js/pimcore/object/tags/urlSlug.js#L155-L158

... I would suggest something like this: 

```js
const match = [...part.match(/([#\?\*\:\\\\<\>\|"%&@=;])/)];
if (match.length > 0) {
     return t('url-slug-invalid-chars') + '[' + match.join(' ') + ']';
}
```

**Comment by NiklasBr** [comment]
I don't think including some of the characters in `/[#\?\*\:\\\\<\>\|"%&@=;]/g` is a good idea, it will fail on many Wikipedia-style URL:s such as:

https://en.wikipedia.org/wiki/The_Lord_of_the_Rings:_The_Fellowship_of_the_Ring
```js
"/wiki/The_Lord_of_the_Rings:_The_Fellowship_of_the_Ring".replace(/[#\?\*\:\\\\<\>\|"%&@=;]/g, '-');
"/wiki/The_Lord_of_the_Rings-_The_Fellowship_of_the_Ring" 
```

https://en.wikipedia.org/wiki/UTC+02:00
```js
"/wiki/UTC+02:00".replace(/[#\?\*\:\\\\<\>\|"%&@=;]/g, '-');
"/wiki/UTC+02-00" 
```

https://en.wikipedia.org/wiki/*repeat_repeat
```js
"/wiki/*repeat_repeat".replace(/[#\?\*\:\\\\<\>\|"%&@=;]/g, '-');
"/wiki/-repeat_repeat"
```

https://en.wikipedia.org/wiki/?_(Nena_album)
```js
"/wiki/?_(Nena_album)".replace(/[#\?\*\:\\\\<\>\|"%&@=;]/g, '-');
"/wiki/-_(Nena_album)"
```

Maybe base it on https://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid/1547940#1547940 instead?

**Comment by Corepex** [comment]
@NiklasBr, thanks. I implemented the regex according to [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986#section-2).
