### ISSUE TITLE
Prepare WebToPrint Bundle for extraction

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#14827]
### Improvement description

- common repo files are missing (`.gitattributes`, `.editorconfig`, ...) 
- `composer.json` is missing 

See https://github.com/pimcore/pimcore/tree/11.x/bundles/WebToPrintBundle

**Comment by kingjia90** [comment]
Reopen: need for https://github.com/pimcore/pimcore/pull/14852 to be finalized and merged first
