### ISSUE TITLE
[Task]: Add documentation for `pimcore\compatibility-bridge`

### ISSUE THREAD

**Issue by mcop1** [pimcore/pimcore#14843]
### Improvement description

Preparation guide/upgrade guide for 10.6 -> 11.0 should be a good place for that

**Comment by dvesh3** [comment]
Added here https://github.com/pimcore/pimcore/blob/11.x/doc/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md?plain=1#L108-L112
