### ISSUE TITLE
 [Classification Store] Inheritance not working properly on the metadata

### ISSUE THREAD

**Issue by lukmzig** [pimcore/pimcore#14874]
I think this PR https://github.com/pimcore/pimcore/pull/14477 is breaking something else related to inherited flag on the metadata

See also for more info: https://github.com/pimcore/pimcore/pull/14477#issuecomment-1498669306

_Originally posted by @flamadrid-jsmdg in https://github.com/pimcore/pimcore/issues/14477#issuecomment-1495048903_

**Comment by jensschaerer** [comment]
Some additional note: After updating to 10.5.20 where the inheritance issue should be fixed, the getGroups() method returns duplicates for all groups (in my case, every group is available 3 times in the result array). I didn't debug this case and implemented a workaround for my case (consolidating all groups to get only unique groups as result), but I think there is a bug as well regarding getGroups() on classification store.

**Comment by procnet0** [comment]
> Some additional note: After updating to 10.5.20 where the inheritance issue should be fixed, the getGroups() method returns duplicates for all groups (in my case, every group is available 3 times in the result array). I didn't debug this case and implemented a workaround for my case (consolidating all groups to get only unique groups as result), but I think there is a bug as well regarding getGroups() on classification store.

Some additionnal information As far as I understood it: 

The buggy behaviour is that getGroups() get groups of all inheritables parents + for all Classifications store configured for the current Class. No regards for the current field.

so if I have a :
```
Class A { 
 ClassificationStore<store1> $field1
 ClassificationStore<store2> $field2
 }
 
```
and Object of class A, hierarchy like 
Object1 > Object2 > Object3 

$Object3->field2->getGroups(); 
Could retrieve  groups from store1 or store2 of parents objects 
with a result looking like :
```
[
group1-store1-fromObject1
group1-store1-fromObject2
group2-store2-fromObject2
group2-store2-fromObject3
ect...
]

```
