### ISSUE TITLE
[Bug]: Maintenecae versioncleanup is not removing versions

### ISSUE THREAD

**Issue by teklakct** [pimcore/pimcore#14886]
### Expected behavior

Running the maintenance job `versioncleanup` in a deprecated way without `--async` flag

```bash
$ /bin/console pimcore:maintenance -j versioncleanup
```

should remove obsolete DataObject versions. 

### Actual behavior

In the system settings store version history for Data Objects is set to 3 steps.

![Screenshot 2023-04-07 at 09 25 53](https://user-images.githubusercontent.com/1399832/230562880-74e7f08b-beae-44cc-bf57-c77ad92a6248.png)

Running the SQL from `Pimcore\Model\Version\Dao::maintenanceGetOutdatedVersions` but without the limit, directly on the DB

```sql
SELECT cid, GROUP_CONCAT(id ORDER BY id DESC) AS versions FROM versions WHERE ctype = 'object' AND NOT public AND id NOT IN (0) GROUP BY cid HAVING COUNT(*) > 3;
```
returns `33741 rows`.

Running maintenance with a force flag in the more verbose output

```bash
$ /bin/console pimcore:maintenance -vv -f -j versioncleanup
```

IMO everything looks fine 

The command prints an output about sending and consuming messages
![Screenshot 2023-04-07 at 09 35 42](https://user-images.githubusercontent.com/1399832/230564427-bd94aa4a-637b-4239-9478-07f5e82f7f72.png)
there is also info that messages are handled
![Screenshot 2023-04-07 at 09 39 11](https://user-images.githubusercontent.com/1399832/230564932-a4315c22-91a4-40e7-b97d-d76f561eacfa.png)

After a default time limit that is used by the message consumer it prints a fine output:
![Screenshot 2023-04-07 at 09 43 20](https://user-images.githubusercontent.com/1399832/230565595-00ff46da-6bb4-44af-9c00-4812669c8141.png)

Nevertheless, the obsolete DataObject versions are still there
![Screenshot 2023-04-07 at 09 41 54](https://user-images.githubusercontent.com/1399832/230565216-45331363-cad9-4c63-bce1-5764c71703e1.png)

### Steps to reproduce

Really don't know how to reproduce that. 

I just upgraded from Pimcore v6.5 to Pimocre v10.5.17 according to https://pimcore.com/docs/pimcore/10.2/Development_Documentation/Installation_and_Upgrade/Updating_Pimcore/V6_to_V10.html 

---

I don't know where should I start looking for.

**Comment by SamyMP** [comment]
You should add the command `bin/console messenger:consume pimcore_core pimcore_maintenance` in your cron, it is part of the [installation doc](https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Installation.html#page_5-Maintenance-Cron-Job)

Tell us if it solves the problem 🙂

**Comment by teklakct** [comment]
As far as I understand If I omit the `--async` then the consumer is called at the end of the `pimcore:maintenance` command and it should work until v11. 

Is there no option to run maintenenca without supervisor?

**Comment by teklakct** [comment]
@SamyMP consumer is working in the background and the only thing that changed is the CPU utilization. When the consumer is running then the mysql process took resources

```bash
top - 10:45:41 up 38 days, 14:35,  2 users,  load average: 0.35, 0.52, 0.51
Tasks: 140 total,   1 running, 139 sleeping,   0 stopped,   0 zombie
%Cpu(s): 34.0 us,  0.2 sy,  0.0 ni, 65.4 id,  0.0 wa,  0.0 hi,  0.4 si,  0.0 st
MiB Mem :   3934.0 total,   1515.1 free,   1473.3 used,    945.7 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   2019.4 avail Mem

PID USER      PR    NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
20517 mysql     20   0 1681800 526064  10168 S  99.7  13.1   1241:55 mysqld
```

**Comment by teklakct** [comment]
ok got it. thx @SamyMP for a clue

In my case, the problem was with an enormous amount of messages in a queue. With the current configuration, a Doctrine is used as a messenger transport. Because of that, and also because the message consumer was not running the message queue was huge. 
When I ran consumer it took messages one by one but the "version cleanup" messages were far far at the end of the queue. 

### My ugly fix:
1. Temporary disable both cronjobs (run maintenance and consumer)
2. Truncate the `messenger_messages` table;
3. Enable cronjobs again. 

Now it looks good.
