### ISSUE TITLE
[Pimcore 4] Zend_Controller_Router_Exception on custom route don't load template

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1489]
This is a tricky case we encounter on a projet:

**How to recreate:**
- Create a document with a custom template file associated (different name than controller/action.php)
Ex: module: mymodule / controller: mycontroller / action: myaction.php / template: mytemplate
- Use this document as an error document (system configuration on the GUI Pimcore or subsite edit if multisite)
- Make a custom route
- In the controller associated to this custom route, throw a Zend_Controller_Router_Exception.

**Result:**
The view renderer will seach for mycontroller/myaction.php and send an error (can be viewed in the php.log)

**Why it is problematic:**
When custom route is used for object detail pages on a web site, and if objects are unpublish or ID is wrong, it is classic to send a 404 (as explained at the bottom of the official documentation: https://www.pimcore.org/docs/latest/MVC/Routing_and_URLs/Custom_Routes.html)

**Solution:**
The problem come from here:
https://github.com/pimcore/pimcore/blob/pimcore4/pimcore/lib/Pimcore/Controller/Action/Frontend.php#L450
Static route don't set the template.

So it is needed here:
https://github.com/pimcore/pimcore/blob/pimcore4/pimcore/lib/Pimcore/Controller/Plugin/ErrorHandler.php#L82
To add:
`$this->getRequest()->setParam("pimcore_request_source", null);`
So in the error loop, template is associated and all work great for sending a router exception using custom routes. This patch has been tested.

I cannot provide a pull request for this sorry, because I am not able for now to make this patch for Pimcore 5. Maybe only Pimcore 4 (and the compatility stub on Pimcore 5) need to be patched.

Thanks a lot.

**Comment by brusch** [comment]
fixed in compatibility bridge: https://github.com/pimcore/pimcore4-compatibility-bridge/commit/fd43cd99e748b19f13cc5d003e9645b9d8a4405d
