### ISSUE TITLE
[Bug]: Versions that have ever been in used in scheduler are never deleted

### ISSUE THREAD

**Issue by AndrewKMoses** [pimcore/pimcore#14926]
### Expected behavior

Pimcore maintenance Versions clean up task should clean up tasks that do not fullfil the version storage configuration (X days or X steps), except for versions that are published or used in _active_ scheduled tasks.

### Actual behavior

A version thas has _ever_ been used as scheduled task is never deleted.

Scheduled tasks are never deleted, even if they have been inactive for a long time.

In our case, we have a specific document where publishing and unpublishing is used frequently. This means that a lot of versions are being created that are never deleted.

https://github.com/pimcore/pimcore/blob/11.x/models/Version/Dao.php#L88

### Steps to reproduce

Create enough versions that some of them should be removed by version clean up task.
Assign those that should be cleaned up to inactive scheduled tasks.

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/17296
