### ISSUE TITLE
Change Psalm back to latest version

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#14956]
### Improvement description

Follow-up to: #14951 
Psalm is failing with v5.9.0 so we had to revert to v5.8.0. 

See also ticket at Psalm: https://github.com/vimeo/psalm/issues/9671

**Comment by kingjia90** [comment]
No way…  yesterday said that it didn’t look they gonna release soon and on time for 11 release, today https://github.com/vimeo/psalm/releases/tag/5.10.0 is out. 😄
Switching back to 11 milestone, to verify that it fixes the former problem
