### ISSUE TITLE
Newsletter sending is stuck when SMTP throws error

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#1496]
When sending a newsletter via smtp (we are using SendGrid, but that shouldn't matter, as there could be any kind of error from any provider), there is a possibility that the smtp provider throws an error (for example invalid email address given).

### Expected behavior
The transport ignores the errors and continues sending.

### Actual behavior
The transport is stuck and won't send the remaining newsletters. 

### Steps to reproduce
- Create an example mailing
- Configure a smtp transport in system properties
- Start sending the newsletter (for example via CSV)
- Make sure you include an invalid email address (e.g. email@.domain., email@domain, etc.)

**Comment by weisswurstkanone** [comment]
Please provide your pimcore build number

**Comment by weisswurstkanone** [comment]
already fixed via https://github.com/pimcore/pimcore/pull/1346
