### ISSUE TITLE
[Bug]: Beta1 Documents only open when TinyMce is installed

### ISSUE THREAD

**Issue by Gerhard-Kanzler** [pimcore/pimcore#14977]
### Expected behavior

Create a new document, open it and edit the content

### Actual behavior

Document cannot be opened until i will install the TinyMce Bundle

### Steps to reproduce

Fresh plain install from skeleton without any bundle!
create a document
open the document (nothing happens)

-> install TinyMceBundle
now you can open a document.

**Comment by youwe-petervanderwal** [comment]
I noticed similar on the demo environment ( https://11.x-dev.pimcore.fun/admin/ ), wysiwyg fields don't have an editor toolbar at the moment.

**Comment by mcop1** [comment]
@youwe-petervanderwal this should be fixed by now, just had a look at the 11.x-dev demo

![grafik](https://user-images.githubusercontent.com/89011527/235932348-1b0d5fe2-4909-4c30-a724-92cc6a0d9f9d.png)

**Comment by mcop1** [comment]
@Gerhard-Kanzler just installed the skeleton without any bundles, added page, snippet, etc .. everything was working fine. Seems like this issue got fixed already.

**Comment by youwe-petervanderwal** [comment]
Looking good @mcop1! I like the switch to TinyMCE (and the option to use a different editor if you want)
