### ISSUE TITLE
[Improvement]: Core Bundle Documentation

### ISSUE THREAD

**Issue by Gerhard-Kanzler** [pimcore/pimcore#14978]
### Improvement description

It would be nice to add more informations about the core Bundles in the Pimcore Docs

A List with all Bundles and maybe the linked Readmes?

PimcoreApplicationLoggerBundle
PimcoreCustomReportsBundle
PimcoreGlossaryBundle
PimcoreSeoBundle
PimcoreSimpleBackendSearchBundle
PimcoreStaticRoutesBundle
PimcoreTinymceBundle
PimcoreUuidBundle
PimcoreWordExportBundle
PimcoreXliffBundle

**Comment by mcassier31** [comment]
See https://github.com/pimcore/pimcore/pull/15149

(To be completed)
