### ISSUE TITLE
[Pimcore 11][Bug] Deleting Notes not possible anymore

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#14989]
### Expected behavior

Can delete notes in UI

### Actual behavior

Button is not visible

### Steps to reproduce

![image](https://user-images.githubusercontent.com/8792145/233389092-f50d8841-f236-4160-89a1-b7c1a7c7471c.png)

**Comment by fashxp** [comment]
see also https://github.com/pimcore/pimcore/pull/13206

**Comment by martineiber** [comment]
By default notes are locked by the Database scheme see.
https://github.com/pimcore/pimcore/blob/69cb798b93b35d1b96bba1f0b9b5f5ead2fa9bad/bundles/InstallBundle/dump/install.sql#L247

When a new note is added via the admin ui, this note is not locked and can be deleted. 
<img width="987" alt="image" src="https://user-images.githubusercontent.com/11687066/235666915-399466fd-a58e-4dfb-8d25-9433530757e0.png">


We could set all notes in the demo here to be unlocked by default.
https://github.com/pimcore/demo/blob/c0fc0205ea404b049e7e207d64a1b195e9a2ddb5/dump/data-1-notes.sql#LL4C203-L4C203

@fashxp Should we change the demo dump or leave it like it is?
