### ISSUE TITLE
Batch assignment classification store

### ISSUE THREAD

**Issue by manea-eugen** [pimcore/pimcore#1500]
Hi. I noticed an issue with batch assignment for classification store fields. On https://demo.pimcore.org there is no classification store so i guess we cannot reproduce it there, but the if you have a project with classification store installed try to do the following:
1. Select a folder from treeview that has a classification store field attach to it 
2. Make sure a classification store field is in the list 
3. Select a few objects 
![screen shot 2017-05-08 at 14 05 21](https://cloud.githubusercontent.com/assets/8200242/25803853/39f199ca-33f9-11e7-9038-cc0d7eee8539.png)
4. From the classification store field try to batch assign a value
![screen shot 2017-05-08 at 14 19 01](https://cloud.githubusercontent.com/assets/8200242/25803868/4fc5b6dc-33f9-11e7-97be-3775d11ff1ce.png)
5. Notice the errors 
![screen shot 2017-05-08 at 14 20 04](https://cloud.githubusercontent.com/assets/8200242/25803891/784d4ebc-33f9-11e7-9b86-c5db156c053d.png)
![screen shot 2017-05-08 at 14 05 26](https://cloud.githubusercontent.com/assets/8200242/25803874/586e6a54-33f9-11e7-967e-c921dc046094.png)

I am not sure what is the problem but it seems that it thinks its a key value field on ObjectHelperController.php
![screen shot 2017-05-08 at 14 08 07](https://cloud.githubusercontent.com/assets/8200242/25803929/a470910c-33f9-11e7-89d5-ffa33b2c0cc5.png)

Please let me know if you need any additional information regarding this issue

**Comment by weisswurstkanone** [comment]
fixed in pimcore4 build 4081, pimcore5 build 52

**Comment by manea-eugen** [comment]
@weisswurstkanone thanks, i will update as soon as posible
