### ISSUE TITLE
[Bug]: Publishing Documents

### ISSUE THREAD

**Issue by tomhuber96** [pimcore/pimcore#15019]
### Expected behavior

When I use the publish button in the document sidebar to publish an unpublihsed document the most recent draft is not published.

![image](https://user-images.githubusercontent.com/52798757/234004662-66495bf8-ce93-4466-a078-1ecb3c2adc1d.png)

### Actual behavior

But any drafts between the last published version will be deleted and the last published version is published again.

![image](https://user-images.githubusercontent.com/52798757/234005234-c10852ab-7a34-4733-a52f-bcd9b927c49b.png)

### Steps to reproduce

1) Unpublish a document
2) Create one or more drafts
3) optional: reload Pimcore
4) right click on the document
5) click on publish
6) the last draft is not published

Bug found on v10.4.6 an reproduced on v10.5.17.

**Comment by dvesh3** [comment]
Fixed by #15194
