### ISSUE TITLE
[Bug]: Filtering website settings when paginated breaks

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#15017]
### Expected behavior

When filtering for a known website setting key, it should be displayed. For example "defaultTaxClass" should be shown (or at least the pagination should work) when filtering for "default" even when it is not available on the current page.

Website settings should work just like Folder or Variant filtering.

For example here:
![Screenshot 2023-04-24 at 13 50 28](https://user-images.githubusercontent.com/279826/233987977-e5efaf3b-2366-404d-9e10-6d40d66d7d8e.png)

Filtering for "Ford" shows a full page of cars from Ford even though none were on the current page before filtering.
![Screenshot 2023-04-24 at 13 51 52](https://user-images.githubusercontent.com/279826/233988258-f935d03b-3bb1-4ddd-95cf-72be75d23745.png)

### Actual behavior

All hidden when not on the "correct" page, as if there were zero results.

### Steps to reproduce

See:

https://user-images.githubusercontent.com/279826/233987594-2862eccf-e4b6-4081-bbbf-c421c994234d.mov

**Comment by dvesh3** [comment]
Fixed by #15069
