### ISSUE TITLE
[Pimcore 11][ApplicationLogger][Bug]: Not possible to open detailView

### ISSUE THREAD

**Issue by dpfahlbusch** [pimcore/pimcore#15029]
### Expected behavior

DetailView of application log opens on double click

### Actual behavior

DetailView of application log doesn't open and throws js error
<img width="617" alt="Bildschirm­foto 2023-04-25 um 11 32 41" src="https://user-images.githubusercontent.com/22637136/234236360-8560b2d0-be5c-4b2b-b0bc-a69291b57f33.png">

### Steps to reproduce

1. Log entry in ApplicationLogger
2. Try to open it

**Comment by Corepex** [comment]
@dpfahlbusch thanks for creating this issue. I can't really reproduce the error you mention. The detail window worked fine for me. Could you please check if the issue still occures when pulling the latest 11.x changes?

Besides that i created a PR to fix certain application logger issues. The CSP error (when clicking the related object link), and the detail window (https://github.com/pimcore/pimcore/pull/15095/files#diff-40e0b7c0239ace99b51f069d7bbfe227533796876384faeb98b7f0a8b9f09ddfR118) work now as expected.

**Comment by Corepex** [comment]
@dpfahlbusch, feel free to reopen the issue if there are any errors ...
