### ISSUE TITLE
[Docs]: Improve Web to Print documentation by adding a hint about maintenance cron jobs

### ISSUE THREAD

**Issue by foxgreek** [pimcore/pimcore#15031]
### Expected behavior

When clicking the "Generate PDF" button, it should start the PDF generation.

### Actual behavior

It remains at 0%

### Steps to reproduce

Try in pimcore demo with any print document

**Comment by blankse** [comment]
@foxgreek See https://github.com/pimcore/pimcore/issues/10655#issuecomment-947378454

> Regarding demo: our public demo instances do not have the maintenance script running, therefore generating PDFs doesn't work (for the moment).

**Comment by foxgreek** [comment]
Hello @blankse, thanks for your feedback. Is it possible to include this anywhere in the docs? I didn't knew about this change until now

**Comment by blankse** [comment]
@foxgreek The docs say you have to set up the maintenance cron jobs in the installation page:
https://github.com/pimcore/pimcore/blob/10.5/doc/Development_Documentation/01_Getting_Started/00_Installation.md#5-maintenance-cron-job

But feel free to create a PR to add a hint to the print page doc:
https://github.com/pimcore/pimcore/blob/10.5/doc/Development_Documentation/03_Documents/02_Document_Types/15_Print_Documents.md

**Comment by kingjia90** [comment]
Just a quick change on #15269, but we definitely need to improve the output message to be more clear why it's stopping or not working at all.
Annoting the former reported problem to this issue https://github.com/pimcore/web-to-print-bundle/issues/5

**Comment by dvesh3** [comment]
Fixed by #15269
