### ISSUE TITLE
Pimcore problem after update from 2.x.x to 4.5

### ISSUE THREAD

**Issue by jborewicz** [pimcore/pimcore#1505]
Dear All,

Recently I get from my friend webpage based on Pimcore CMS(version 2.x.x, not sure exact version now).

Due to the old version i decided to upgrade cms to the newest version(4.5.0), using update option from pimcore admin panel. During the installation update failed, not sure what information was displayed but after this I was not able to access pimcore anymore.

I tried to copy pimcore backup to the server(backup created from admin panel) but after this on main page I get "HTTP ERROR 500", When i try to access admin panel I get info: "It seems that /www/..../www/html/website/var/log/loginerror.log is not writable."

Seems that there is an issue with file permissions but I am not sure.

Do you have any idea what can be wrong?

I am new with Pimcore and any help will be highly appreciated:)

Best,
Jarek

**Comment by brusch** [comment]
This bug tracker is not for support question, please visit our Google Group instead: https://groups.google.com/forum/#!forum/pimcore

**Comment by jborewicz** [comment]
sorry and thank you for information, please kindly delete this issue
