### ISSUE TITLE
[Bug]: security.listener.user_provider has a dependency on a non-existent service

### ISSUE THREAD

**Issue by felixflor-twocream** [pimcore/pimcore#15075]
### Pimcore version

v11.0.0-RC1

### Steps to reproduce

Call Admin URL or bin/console cache:clear

### Expected / actual behavior

Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException^ {#12112
  #message: "The service "security.listener.user_provider" has a dependency on a non-existent service "Pimcore\Bundle\AdminBundle\Security\User\UserProvider". Did you mean this: "Pimcore\Bundle\AdminBundle\Security\CsrfProtectionHandler"?"
  #code: 0
  #file: "/var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php"
  #line: 83
  -id: "Pimcore\Bundle\AdminBundle\Security\User\UserProvider"
  -sourceId: "security.listener.user_provider"
  -alternatives: array:1 [
    0 => "Pimcore\Bundle\AdminBundle\Security\CsrfProtectionHandler"
  ]
  trace: {
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:83 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:80 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:46 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:89 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:46 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:80 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:46 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:44 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:37 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/symfony/dependency-injection/Compiler/Compiler.php:73 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/symfony/dependency-injection/ContainerBuilder.php:721 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/symfony/http-kernel/Kernel.php:487 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/pimcore/pimcore/lib/Kernel.php:181 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/symfony/http-kernel/Kernel.php:709 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/symfony/http-kernel/Kernel.php:122 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/pimcore/pimcore/lib/Kernel.php:160 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/pimcore/pimcore/lib/Bootstrap.php:212 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/pimcore/pimcore/lib/Bootstrap.php:58 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/bin/console:36 {
      {closure}^
      › return function (array $context) {
      ›     $kernel = Bootstrap::startupCli();
      › 
    }
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/symfony/runtime/Resolver/DebugClosureResolver.php:25 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/vendor/autoload_runtime.php:24 { …}
    /var/www/public/twocream/pimcore/2023-pimcore-11-beta/bin/console:20 { …}
  }
}

**Comment by felixflor-twocream** [comment]
v11.0.0-RC1 UserProvider found in: vendor/pimcore/pimcore/lib/Security/User/UserProvider.php
Before v11.0.0-RC1: vendor/pimcore/pimcore/bundles/AdminBundle/Security/User/UserProvider.php

Namespaces also changed.

**Comment by felixflor-twocream** [comment]
Affected Files:

In Pimcore Sekeleton:
./config/packages/security.yaml

Pimcore Files:
./vendor/pimcore/pimcore/bundles/CoreBundle/config/services.yaml
./vendor/pimcore/admin-ui-classic-bundle/.github/ci/files/config/packages/security.yaml
./vendor/pimcore/admin-ui-classic-bundle/.github/ci/files/config/security_services.yaml
./vendor/pimcore/admin-ui-classic-bundle/config/pimcore/security.yaml

**Comment by dvesh3** [comment]
Hi @felixflor-twocream `Pimcore\Bundle\AdminBundle\Security\User\UserProvider` including other security user classes has been deprecated on 10.6 and now removed in `v11.0.0-RC1`.

Please see[ upgrade notes ](https://github.com/pimcore/pimcore/blob/ef69b13da7c1ba7a3b94d94a73c663ebaf4f5798/doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md#1060)

```
[Security] Deprecated Security User classes in favor of Pimcore core classes:
Pimcore\Bundle\AdminBundle\Security\User => Pimcore\Security\User
Pimcore\Bundle\AdminBundle\Security\User\UserChecker => Pimcore\Security\User\UserChecker
Pimcore\Bundle\AdminBundle\Security\User\UserProvider => Pimcore\Security\User\UserProvider
Pimcore\Bundle\AdminBundle\Security\User\UserLoader => Pimcore\Security\User\UserLoader
Pimcore\Bundle\AdminBundle\Security\User\TokenStorageUserResolver => Pimcore\Security\User\TokenStorageUserResolver
```

Unfortunately, It doesn't work without some manual changes if you are upgrading from Beta version to RC.
