### ISSUE TITLE
[Bug]: Broken inheritance on InputQuantityValue in DataObjects when CalculatedValue has no class or expression value

### ISSUE THREAD

**Issue by felixflor-twocream** [pimcore/pimcore#15081]
### Pimcore version

10.x.x / 11.x.x

### Steps to reproduce

1. Create DataObject Class
2. Make it Inheritable
3. Add some e.g. Textfields (optional)
4. Add a CalculatedValue field and leave expression or class value empty (bug on both)
5. Add a InputQuantityValue field behind
6. Save class and create a Partent and Child Object

### Expected / actual behavior

**Expected**
The inherited InputQuantityValue must be marked as an inherited value. 

**Actual behavior**
The inherited InputQuantityValue is not marked as inherited.

**Comment by robertSt7** [comment]
@felixflor-twocream Hi, thanks for reporting this bug. For me InputQuantityValue is marked as inherited, but not CalculatedValue. Did you mean that CalculatedValue is not marked as inherited?

**Comment by kingjia90** [comment]
Closing as not reproducible. Feel free to reopen if it's still occurring and can be reproduce in the demo.

![image](https://github.com/user-attachments/assets/7361f91c-c95d-45b7-8a2c-b5405a92930a)
Confirming the input from @robertSt7 that the calculated value might be missing the green arrow that suggests it would be inheriting, but mis-configuring the calculated value could mislead the empty check necessary for inheritance AND that's likely a ticket for admin-ui-classic-bundle repo.
