### ISSUE TITLE
[Bug][Pimcore 10.6] Loading not existing settings.js

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#15099]
### Pimcore version

10.6

### Steps to reproduce

- install empty Pimcore 10.6
- load Pimcore Backend

### Expected / actual behavior

![image](https://user-images.githubusercontent.com/8792145/236033583-3ea68bf5-fbdf-4d02-a2d8-0c176e7e27a7.png)

**Comment by kingjia90** [comment]
Fixed by #15154

**Comment by kingjia90** [comment]
Merged as an "hotfix", but for more consistency and future-proof, this https://github.com/pimcore/pimcore/issues/15182 should be considered
