### ISSUE TITLE
[Bug]: session is not set using external links

### ISSUE THREAD

**Issue by paulhaem** [pimcore/pimcore#15090]
### Pimcore version

10.5.19 and Pimcore Demo (10.5.17)

### Steps to reproduce

1. Login as a customer / frontend user on https://demo.pimcore.com/
2. Click on a external link to the website: https://demo.pimcore.com/
3. Session is not set, not even after refreshing the page
4. After navigating to any other page or clicking on a internal link to the current page the session is set

This is reproducable using any page: https://demo.pimcore.com/en/Magazine

Manually entered links, bookmarked links and internal links are working fine.

### Expected / actual behavior

I would expect the session to be set after navigating to the website via external link if I have a ongoing session or "remember me" session.

**Comment by brusch** [comment]
This is caused by `samesite=strict` attribute,
see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

This is for security reasons the default configuration, but you can change it in the config for your individual project.

**Comment by paulhaem** [comment]
Thanks @brusch for looking into it. Is it safe to set `samesite` to e.g. `lax` which is the default value if `samesite` is not specified?

**Comment by brusch** [comment]
@paulhaem That depends on your application 😉 But for Pimcore itself it basically makes no difference.
