### ISSUE TITLE
[Bug]: faulty cart item amount

### ISSUE THREAD

**Issue by paulhaem** [pimcore/pimcore#15104]
### Pimcore version

10.5.19

### Steps to reproduce

1. Add a product to the cart, the cart item amount should now be `1`
2. Delete the product you added to the cart
3. The cart should now be empty and the cart item amount should still be `1`

`getItems()` does only return the products that are still available while `getItemAmount()` looks into the database table `ecommerceframework_cartitem` which still holds the record referencing a deleted product.

### Expected / actual behavior

The cart item amount should be `0` after deleting the product.

**Comment by mattamon** [comment]
Hey @paulhaeml

I tried to reproduce it but no luck. 

Could you please explain it in a little more detail? 

On demo when I remove the product the `getItemAmount` will be 0.

**Comment by mattamon** [comment]
@paulhaem any news?

**Comment by paulhaem** [comment]
@mattamon thanks for looking into it. What kind of information do you need?

Problem was that the related record in the `ecommerceframework_cartitem` table still persist after deleting the product it has a relation to. I was thinking that the cascade delete was missing out here but as you were not able to reproduce it I will setup the demo and try to reproduce it.

**Comment by paulhaem** [comment]
@mattamon I was able to reproduce it using https://demo.pimcore.com/

Steps to reproduce:
1. Login as customer
2. Add two products to the cart, they should now be listed in the cart and the cart item amount (top right) should be `2`
3. Open the detail page of product A and in a new tab open the cart
4. Login as superuser
5. Open product A (Strg + Shift + O) and delete it
6. Refresh both tabs
7. The detail page of product A should now show 404 error page, the cart should now show product B and the cart item amount should still be `2`

![image](https://github.com/pimcore/pimcore/assets/6862218/7ad6ac5b-f9b0-45e0-bb72-b6d7b593f349)

**Comment by mattamon** [comment]
@paulhaem Ahhh, I do get it now. You delete the product from the system. I did not get that and I removed ("deleted") it from the cart. 

I will check this out and get back to you. Thank you for the clarification!

**Comment by mattamon** [comment]
@paulhaem

In the meanwhile you could implement a EventSubscriber which updates the carts like this.

```php
<?php
use Pimcore\Bundle\EcommerceFrameworkBundle\Factory;
use Pimcore\Bundle\EcommerceFrameworkBundle\Model\CheckoutableInterface;
use Pimcore\Event\DataObjectEvents;
use Pimcore\Event\Model\DataObjectEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class CartUpdateSubscriber implements EventSubscriberInterface
{

    /**
     * @return array
     */
    #[\ReturnTypeWillChange]
    public static function getSubscribedEvents()//: array
    {
        return [
            DataObjectEvents::PRE_DELETE => 'onObjectDelete',
        ];
    }

    public function onObjectDelete(DataObjectEvent $event)
    {
        $object = $event->getObject();
        if ($object instanceof CheckoutableInterface) {
            $carts = Factory::getInstance()->getCartManager()->getCarts();
            foreach ($carts as $cart) {
                if ($cart->getItem($object->getId())) {
                    $cart->removeItem($object->getId());
                    $cart->save();
                }
            }
        }
    }
}
```

The question is if we should do this in the core too. Deleting products has more impact than only the cart. It also would e.g. ruin the whole selling history. The best way would be to unpublish this products or deactivate them somehow. 

We will check this in the team, if we should implement something like this in the core. This also has implications here: https://github.com/pimcore/ecommerce-framework-bundle

**Comment by mattamon** [comment]
@paulhaem,

We discussed it in the team and decided not to tackle this problem.
Some of the problems I mentioned in the comment above like the history and other statistics e.g.

My described approach is also not feasible for huge ecommerce applications since there could be thousands or even million carts that would need to be checked and this would impact performance.

**Comment by paulhaem** [comment]
Too bad. Is there any best practice to handle such situations instead? I am sure others will stumble upon the same issue again. Would suggest that the docs be updated to treat this delicate topic.
