### ISSUE TITLE
New feature: Add event after creating grid on object listing view

### ISSUE THREAD

**Issue by sidd-chaudhery** [pimcore/pimcore#1511]
I want to do some customization on the object grid based on some condition. For example - lets assume I have a class of "Member" that has an email attribute. I want to make the rows red on grid view if the email column is having an invalid email address. 

I think if you can trigger some event after grid gets created something like this 
`pimcore.plugin.broker.fireEvent("objectGridPostLoad", this.grid);`
so then I can attach a listener to that and I can make some customizations there. 

Let me know your thoughts please. 

Siddharth

**Comment by sidd-chaudhery** [comment]
Do you want me to create a pull request for the same

**Comment by brusch** [comment]
Please give us some time to discuss this feature request internally. 
At the moment we're thinking of changing the way how the admin UI events will work in version 5, so probably it's better to wait until we've made a decision. 

Thanks for your patience.

**Comment by brusch** [comment]
Maybe it's anyhow better to use custom reports for that purpose? 
The problem I see is, the more you're customizing the UI the more issues you'll have with upgrades.

**Comment by brusch** [comment]
We should go for a more specific approach here, because the grid itself is too generic and would make backward compatibility even harder.
