### ISSUE TITLE
[Task]: Remove `Button` control for `DataObjects`

### ISSUE THREAD

**Issue by mcop1** [pimcore/pimcore#15124]
### Improvement description

 Remove `Button` control for `DataObjects`

Check if it is necessary to do the same for `asset-metadata-class-definitions` bundle.

Follow up to https://github.com/pimcore/pimcore/issues/15123

**Comment by aweichler** [comment]
@mcop1 Why do you drop the Button? We are using it in serveral projects.

**Comment by NiklasBr** [comment]
What was the motivation for this @Corepex?

**Comment by Corepex** [comment]
@aweichler and @NiklasBr the button component was a security issue in itself. We decided to remove the feature to prevent any security vulnerabilities in the future.

**Comment by NiklasBr** [comment]
Do you have any documentation about it in the migration notes and recommendations for achieving the same functionality with another feature?

**Comment by fashxp** [comment]
Create your custom layout component, see https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/Adding_Object_%20Layout_types.html

@Corepex maybe we can add that to upgrade notes
