### ISSUE TITLE
[Improvement]: Link Editable: Allow $allowedAttributes to be extended by config or give an option to disable check for allowed attributes

### ISSUE THREAD

**Issue by schmidt-travixmedia** [pimcore/pimcore#15148]
### Improvement description

There was a PR that fixed a security issue: https://github.com/pimcore/pimcore/pull/14986

See https://github.com/pimcore/pimcore/blob/10.5/models/Document/Editable/Link.php

The newly introduced "allow list" sanitizing makes it impossible (or at least difficult) for us to give an `<a>` tag Vue.js attributes like `v-if="..."` or `@click="getData"` in an easy way like it was before in Pimcore 10.4. In a world of JavaScript Frameworks, it is a bad idea to restrict attributes completely in such an inflexible way.

Please allow $allowedAttributes to be extended by config or give an option to disable check for allowed attributes.

I understand security is a big issue, but restricting things by default that were widely used before and thus stop applications working, is not for minor updates.
Moreover, content in Editables is created by editors in the backend, who should actually be trusted.
This "security feature" should have better been introduced in Pimcore 11, as its introducing a new functionality that is not really backward compatible.

**Comment by blankse** [comment]
Milestone should be 11.1.0
