### ISSUE TITLE
[Bug]: Can not select a Thumbnail for download. 

### ISSUE THREAD

**Issue by martineiber** [pimcore/pimcore#15170]
### Pimcore version

11.0

### Steps to reproduce

Open an Asset and try to select a Thumbnail for Download. There is no Thumbnail to select. 

### Expected / actual behavior

It Should be possible to select a Thumbnail and Download it.

**Comment by fashxp** [comment]
is it configured in thumbnail config? 

![image](https://github.com/pimcore/pimcore/assets/8792145/9f0f010c-81a6-48ef-98ee-c6260dcbfe5b)

**Comment by martineiber** [comment]
Thank you for the hint, this was the Issue.
