### ISSUE TITLE
[Improvement]: Pimcore Docs: Upgrade Notes for 10.x to 10.y missing after today's documentation update

### ISSUE THREAD

**Issue by schmidt-travixmedia** [pimcore/pimcore#15217]
### Improvement description

Hi,

I have to upgrade a project from Pimcore 10.4 to Pimcore 10.5.

This morning (today is May, 16th, 2023) the documentation was fine, I was able to find the necessary infos about updating from 10.4 to 10.5.

Today, a Pimcore Docs update was released. Now I cannot find the classic "Upgrade notes" that used to be here:
https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/index.html

On the new Docs page, I also cannot switch between Pimcore minor versions like before.
Is there something missing by mistake, or is there a new Docs concept I don't understand?

Please make the classic Docs accessible again.

Thank you!

**Comment by brusch** [comment]
@schmidt-travixmedia we're just in the process of the v11 release, the "old" docs will be back as soon as we're done 😉

**Comment by NiklasBr** [comment]
Related: https://github.com/pimcore/pimcore-docs/issues/32

**Comment by brusch** [comment]
Here we go: https://pimcore.com/docs/pimcore/10.6/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/index.html 

The old docs are also linked in the header and footer of the new docs :)

**Comment by jdreesen** [comment]
The academy banner is in the lower left corner is broken. The linked image https://pimcore.com/docs/platform/Pimcore/themes/pimcore/img/02_970x250_Billboard.jpg is 404.

![image](https://github.com/pimcore/pimcore/assets/424602/5242b3bc-24f0-45cc-88e6-03e3144d0f37)

**Comment by brusch** [comment]
@jdreesen Thanks for the hint, I was already on it 😅 
https://github.com/pimcore/pimcore-docs/pull/34
