### ISSUE TITLE
[Bug]: Permission problems with objectbricks in the enterprise demo for superuser

### ISSUE THREAD

**Issue by heigpa** [pimcore/pimcore#15220]
### Pimcore version

11

### Steps to reproduce

- Login to the enterprise demo with user = superuser
- Open a car object
- Open the attributes tab in the object editor

### Expected / actual behavior

**Expected:**

- Attributes should be shown

**Actual:**

- An 'Access denied!' warning is shown

**Comment by mcop1** [comment]
Permissions were introduced with https://github.com/pimcore/pimcore/pull/13605
