### ISSUE TITLE
[Bug]: Export grid to xlsx file with S3 storage dosn't work

### ISSUE THREAD

**Issue by MasterOfDeath** [pimcore/pimcore#15225]
### Pimcore version

10.5.23

### Steps to reproduce

Setup storages `pimcore.asset.storage` and `pimcore.temp.storage` to S3 and push button "XLSX Export"

![image](https://github.com/pimcore/pimcore/assets/1111867/23bef351-6e52-4bee-a412-bb56ad4f4732)

### Expected / actual behavior

Expected: File is downloading without issuses  
Actual behavior: After pushing button "XLSX Export" we have error:
![image](https://github.com/pimcore/pimcore/assets/1111867/97555554-ad4a-411c-9f15-ec4e4c0457f1)

**Comment by kingjia90** [comment]
Resolved by https://github.com/pimcore/pimcore/pull/15227
