### ISSUE TITLE
[Bug]: \Pimcore\Model\Asset\Thumbnail\ImageThumbnailTrait::readDimensionsFromFile uses just getimagesize()

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#15231]
### Pimcore version

10.5, 10.6

### Steps to reproduce

Currently, if you try to use `\Pimcore\Model\Asset\Thumbnail\ImageThumbnailTrait::readDimensionsFromFile` on PHP 8.0, you might run into the fact [`getimagesize` doesn't yet support AVIF](https://github.com/php/php-src/pull/7091). This itself is not an issue because we're using Imagick which does know how to *generate* AVIF, but then Pimcore doesn't know how to read the dimensions of the image it just generated. 

Reproduce (on PHP 8.0):
1. have imagick enabled
2. upload a new image
3. run `bin/console pimcore:thumbnail:image --id=<new image ID>`
4. it generates the AVIF, but it's not added to `assets_image_thumbnail_cache`

This is caused by it using `getimagesize` (with errors suppressed, even!):
https://github.com/pimcore/pimcore/blob/dc67e0d46b93806fb52214bbbec80cfac877fd0a/models/Asset/Thumbnail/ImageThumbnailTrait.php#L180

which returns false for AVIF images. If we try to use Imagick here, it works as expected. The side-effect of this the AVIF images are constantly seen as "not created" since they never get added to the cache.

### Expected / actual behavior

Read the AVIF image you've just created dimensions correctly. Maybe by using the adapter, it would be future proof. This is currently describing the specific case of "AVIF on 8.0", but it will apply on "some other new format on PHP 10" in the future which is supported by Imagick or VIPS or whatever the future adapter is available, but not yet by `getimagesize`.

**Comment by brusch** [comment]
We should still try `getimagesize()` first and only fallback to Imagick if necessary for performance reasons.  
Or (probably even better) we have a whitelist for formats using `getimagesize()` and use Imagick for the rest.

**Comment by dkarlovi** [comment]
Performance difference should be negligible because the point is to fill up the thumbnail cache where either path is skipped anyway IMO.

**Comment by brusch** [comment]
@dkarlovi Formats supported by GD are anyway not that much an allowlist shouldn't hurt here as well ... and Imagick is not a requirement.

**Comment by dkarlovi** [comment]
If Imagick is not available, the GD adapter is used anyway, which already uses `getimagesize`, no? The adapters also already have a whitelist of formats.

Anyway, I'm not married to the implementation either way, it's up to you. :+1:

**Comment by brusch** [comment]
👍 the thing that makes me think, is that loading images using Imagick is quite expensive as there are many other things that happen here 😊 
See https://github.com/pimcore/pimcore/blob/b5a2129e8ff5f8cbb1595ecdc8c39abdfa2151c5/lib/Image/Adapter/Imagick.php#L51

**Comment by dkarlovi** [comment]
>  loading images ~~using Imagick~~ is quite expensive

Right, this is why I'm saying this should ideally run only once and then never again so it doesn't matter you gain a few ms using this or that approach.

It does mean Pimcore needs to be much much more protective of the thumbnail cache and not just wipe it ever chance it gets tough: https://github.com/pimcore/pimcore/issues/15273

Ideally:
1. I upload an image asset
2. thumbs get generated, stored in storage and cache
3. if I don't change the underlying original image or thumbnail config, the **thumbs are never ever touched by Pimcore again**, they're being served by CDN and Pimcore just knows about them from the database

With that approach in mind, it shouldn't matter the adapter approach is a bit more expensive (but you not being able to use the adapter image to inspect images might be seen as an architectural bug), it wouldn't matter in the overall lifecycle of the thumbnail, the cost of the execution approaches zero.

**Comment by brusch** [comment]
Fixed by #15323
