### ISSUE TITLE
[Bug]: pimcore:thumbnails:image -s returns an exception

### ISSUE THREAD

**Issue by lukmzig** [pimcore/pimcore#15234]
### Pimcore version

11.0

### Steps to reproduce

Run command `pimcore:thumbnails:image -s`

## Expected
Command runs through without an exception even when optional `webmozart parallelization` is not installed

## Actual
Command runs through but it returns an exception:

Error thrown while running command "pimcore:thumbnails:image -s". Message: "The "processes" option does not exist." ["exception" => Symfony\Component\Console\Exception\InvalidArgumentException { …},"command" => "pimcore:thumbnails:image -s","message" => "The "processes" option does not exist."]

 

                                          
  The "processes" option does not exist.  
                                          

 

pimcore:thumbnails:image [--parent [PARENT]] [--id [ID]] [--pathPattern [PATHPATTERN]] [-t|--thumbnails [THUMBNAILS]] [-s|--system] [-f|--force] [--skip-medias] [--skip-high-res] [--skip-avif] [--skip-webp]

**Comment by martineiber** [comment]
Fixed by #15235
