### ISSUE TITLE
[Bug]: getSourceTagHtml produces wrong with and height

### ISSUE THREAD

**Issue by Fabian-Hofer-Mastertent** [pimcore/pimcore#15243]
### Pimcore version

10 & 11

### Steps to reproduce

can be reproduced in the pimcore demo:

1. Open a existing pimcore Thumbnail (for example "Areas" > "portalCarousel")
2. Check the different sizes from the media-queries
3. open the demo pimcore website (https://demo.pimcore.com/) and check the source of the website

### Expected / actual behavior

**Expected behaviour:**

Current browsers allow to set the width and height attribute not only on the img-Tag but also on the source-Tag. Which pimcore does. The sizes on the source-Tags can be used by the browser to compute the aspect ratio on the different media queries (for example on chrome: https://chromestatus.com/feature/5737185317748736)
Normally Pimcore should use the width and height set on the different media queries.

**Actual Behaviour:**

The with and height attribute on the source tag is always the same as on the default-image. This makes the widht and height on the source-tag useless because the browser always uses the aspect-ratio of the default image element.

**Comment by dvesh3** [comment]
Fixed by #15253
