### ISSUE TITLE
CSV Import Fails on Objects Tree

### ISSUE THREAD

**Issue by pagliaso** [pimcore/pimcore#1524]
Hello,

I think to remember that import csv on Objects Tree uses to bring up an import dialog to map fields on the file to fields on the object.

I was getting an error on my Pimcore installation on my server upon import any csv file. It is just an Error Dialog with no other info.

![imagen](https://cloud.githubusercontent.com/assets/2955272/26046286/8351f0f6-394e-11e7-8c69-d1b3bb572bfb.png)

I have look for more information on debug log and php and can't find any more detail about the error.

I exported inquiries on demo site and try to import them with csv import and I get the exact same Error dialog.

### Expected behavior 
  I was expecting that import csv file on Objects Tree would bring an import dialog to map fields to objects after uploading the csv file to the server.
 
### Actual behavior  
  The process fails before even uploading the file to the server (while uploading) with the mentioned Error Dialog without any further detail. The file is only about 65 kilobytes.

### Steps to reproduce  
  Import a csv file from Objects Tree

Many thanks and kind regards from Spain,

**Comment by weisswurstkanone** [comment]
build 4082
