### ISSUE TITLE
[Bug]: Shared Translations Import & Merge CSV does not unescape CSV

### ISSUE THREAD

**Issue by siwa-ddiesenreither** [pimcore/pimcore#15249]
### Pimcore version

v10.6.1

### Steps to reproduce

Add a translation message having e.g. a "+" as value. The export adds a "'" to the "+". When re-importing the exported file, the escape character ("'") doesn't get removed.

The function for escaping CSV was added here: https://github.com/pimcore/pimcore/pull/9992/files

### Expected / actual behavior

The characters should get removed so the correct translations get imported.

**Comment by dvesh3** [comment]
Fixed by #15310
