### ISSUE TITLE
[Targeting]: Configured redirects with priority 99 cause error in targeting toolbar when enabled

### ISSUE THREAD

**Issue by mysliwietzflorian** [pimcore/pimcore#15254]
### Pimcore version

>=10.5.8

### Steps to reproduce

- Add a redirect with priority 99 via Admin UI
- If the targeting toolbar is activated a call of the redirect route causes the error **The SessionBagInterface "pimcore_admin" is not registered.**

(Screenshots are not from the demo project as I have no Debug-Toolbar there)

![image](https://github.com/pimcore/pimcore/assets/23225429/f9fc0707-12b1-413a-946a-38a5ca46e410)

![image](https://github.com/pimcore/pimcore/assets/23225429/f579e02d-fe42-4782-b566-0d54cd0e7644)

## Explanation

With a redirect configured the RoutingListener.php stops KernelEvents::Request propagation, which is followed later by KernelRequest::Response. E.g.: the AdminSessionBagListener is not called and therefore is not available in the Response events. ToolbarListener calls `Authentication::authenticateSession($request)` which results in the error.

https://github.com/pimcore/personalization-bundle/blob/1.x/src/Targeting/EventListener/ToolbarListener.php#L147

![image](https://github.com/pimcore/pimcore/assets/23225429/a49960ad-fa85-460a-994e-60880dbdff27)

## Our quick-fix solution

We added the following line to `https://github.com/pimcore/pimcore/blob/10.6/bundles/CoreBundle/EventListener/Frontend/RoutingListener.php#L100`:  
`$request->attributes->set('pimcore_targeting_debug', false);`

### Expected / actual behavior

Redirect works as intended and redirects to the target.

**Comment by mysliwietzflorian** [comment]
Update: A cleaner workaround solution would be:

```php
<?php

namespace App\EventListener\Core;

use Pimcore\Event\RedirectEvents;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Pimcore\Event\Model\RedirectEvent;
use Symfony\Component\HttpFoundation\RequestStack;

class RedirectsListener implements EventSubscriberInterface
{
    private RequestStack $requestStack;

    public static function getSubscribedEvents(): array
    {
        return [
            RedirectEvents::PRE_BUILD => 'onPreBuild',
        ];
    }

    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }

    public function onPreBuild(RedirectEvent $e)
    {
        /** @see https://github.com/pimcore/pimcore/issues/15254 */
        $request = $this->requestStack->getMainRequest();
        $request->attributes->set('pimcore_targeting_debug', false);
    }

}
```

**Comment by mysliwietzflorian** [comment]
A cleaner workaround without patching anything would be:

```php
<?php

namespace App\EventListener\Core;

use Pimcore\Event\RedirectEvents;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Pimcore\Event\Model\RedirectEvent;
use Symfony\Component\HttpFoundation\RequestStack;

class RedirectsListener implements EventSubscriberInterface
{
    private RequestStack $requestStack;

    public static function getSubscribedEvents(): array
    {
        return [
            RedirectEvents::PRE_BUILD => 'onPreBuild',
        ];
    }

    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }

    public function onPreBuild(RedirectEvent $e)
    {
        /** @see https://github.com/pimcore/pimcore/issues/15254 */
        $request = $this->requestStack->getMainRequest();
        $request->attributes->set('pimcore_targeting_debug', false);
    }

}

```

**Comment by jremmurd** [comment]
@dvesh3 The same error occurs if the maintenance-mode is activated via  `bin/console pimcore:maintenance-mode --enable` (see `MaintenancePageListener` in the above screenshot of `debug:event-dispatcher kernel.request`)

<details><summary>Click to expand screenshot</summary>

![image](https://github.com/pimcore/pimcore/assets/9052094/49bb18e7-3200-4fd3-8f5f-676b5a2fd5b2)

</details>

**Comment by dvesh3** [comment]
@mysliwietzflorian @jremmurd duplicate https://github.com/pimcore/pimcore/issues/11927? I can't reproduce it on latest version 10.5.23. please confirm?

**Comment by jremmurd** [comment]
@dvesh3 can't confirm, same error in 10.5.23

**Comment by jremmurd** [comment]
Our current patch: https://github.com/jremmurd/pimcore/commit/22c4573e2cae6242e063b6019c4245df09315f22

**Comment by dvesh3** [comment]
On v10.5, we still use the deprecated [AdminSessionBagConfigurator](https://github.com/pimcore/pimcore/blob/00d27b3f8cce4e51aac1fbd3cbab7912f81f7c06/bundles/AdminBundle/Resources/config/services.yaml#L7) for BC reasons, which registers the session bag on [compilation](https://github.com/pimcore/pimcore/blob/c7e9391768b2efcb261640a140b922316344ad13/bundles/CoreBundle/DependencyInjection/Compiler/SessionConfiguratorPass.php#L68). I still don't get why it is not registered in your case.

**Comment by dvesh3** [comment]
Sorry not able to reproduce the issue with reported steps. please feel free to continue the discussions. thanks!
