### ISSUE TITLE
[Bug]: AVIF support by Assets

### ISSUE THREAD

**Issue by polargold-dev** [pimcore/pimcore#15260]
### Pimcore version

10.6

### Steps to reproduce

1. Upload any AVIF image to assets. Example image: https://raw.githubusercontent.com/link-u/avif-sample-images/master/red-at-12-oclock-with-color-profile-10bpc.avif
2. Open image. A thumbnail will not be shown.
![Bildschirm­foto 2023-05-23 um 11 40 52](https://github.com/pimcore/pimcore/assets/129742405/95d12d23-5ca3-4b5c-a20f-f56eccb61fcf)
3. If we try to generate the thumbnail via console command, then we will get an exception like this.
![Bildschirm­foto 2023-05-23 um 11 42 00](https://github.com/pimcore/pimcore/assets/129742405/8e92f2f3-649f-4194-afe1-5680d63fa737)

### Expected / actual behavior

Thumbnails of AVIF images can be generated.

**Comment by polargold-dev** [comment]
vendor/pimcore/pimcore/lib/Image/Adapter/Imagick.php: 

Line: 157- 162
```php
} catch (\Exception $e) {
            Logger::error('Unable to load image: ' . $imagePath);
            Logger::error($e->getMessage());

            return false;
        }
        
```

**Comment by brusch** [comment]
Is Imagick compiled with AVIF support? What does phpinfo() says about avif?

**Comment by NiklasBr** [comment]
AVIF file linked above does not work on demo.pimcore.fun/admin either.

![image](https://github.com/pimcore/pimcore/assets/279826/d1448726-9b6e-48d7-a7b7-2a1143b4daeb)

**Comment by brusch** [comment]
Yes, because we've decided to disable AVIF support temporarily, see reason here: https://github.com/pimcore/docker/pull/138
But if you enable AVIF support in your ImageMagick policy it should work.

**Comment by brusch** [comment]
See also: 

![image](https://github.com/pimcore/pimcore/assets/142037/21a8de47-3f5a-4e27-a8fe-a571bcca1ad1)

**Comment by NiklasBr** [comment]
🤷  still, it makes not a lot of sense to force everyone to rebuild their Docker images or do custom mounting to get back functionality which can be disabled by a regular setting in Pimcore. Looks like a waste of resources here. I bet you are going to get a lot more of these reports in the future.

**Comment by dpfaffenbauer** [comment]
@NiklasBr I do agree with you

**Comment by brusch** [comment]
Well, the Docker image is a different thing ... AVIF doesn't work, so we didn't add it to the next version - it's as easy as that 🤷
Still the product has AVIF capabilities that work, independently from the Docker image. Pimcore itself is NOT equal to our Docker images as Docker is not a requirement.
