### ISSUE TITLE
[Bug]: 10.6.0 migration fails on mariadb < 10.5.2

### ISSUE THREAD

**Issue by frithjof** [pimcore/pimcore#15262]
### Pimcore version

upgrade 10.5.21 -> 10.6.0

### Steps to reproduce

caused by the migration in https://github.com/pimcore/pimcore/pull/14738/files#

use standard mariadb server from ubuntu 20.04
error with Sql syntax with rename

RENAME s invalid for mariadb < 10.15.2

### Expected / actual behavior

Rename the columns or at least have a Upgrade Note and adjust min sys reqirements accordingly

**Comment by brusch** [comment]
So actually it's about: 
https://github.com/pimcore/pimcore/blob/10.6/bundles/CoreBundle/Migrations/Version20230322114936.php

and we need to use `ALTER TABLE %s CHANGE COLUMN ... ` instead.
