### ISSUE TITLE
$this->_helper->json return Zend Helper instead of Pimcore Json Helper

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#1528]
This was not the case in previous builds (maybe since ~4078 ? )

Example:

        $this->_helper->json([
            "success" => true
        ], false);

Problem:
     The behavior is completely different when sendDirect is set to false.

**Comment by brusch** [comment]
Fixed in 2d306f9e67e140130dcf5443b5b8e8da03e043c1
