### ISSUE TITLE
[Bug]: Return type incompatibility in \Pimcore\Model\DataObject\ClassDefinition\Data\Date

### ISSUE THREAD

**Issue by drs-anton** [pimcore/pimcore#15296]
### Pimcore version

11.0.0

### Steps to reproduce
We are migrating from pimcore 10.6 to 11.0.0 at the moment and stumbled across the following behaviour
Return types between 
\Pimcore\Model\DataObject\ClassDefinition\Data\Date::getDataForResource (int|string|null)
and
\Pimcore\Model\DataObject\ClassDefinition\Data\Date::getDataForQueryResource (int|null)
are not compatible.

For example if there is an object field from type Date with the datatype DATE, getDataForResource() returns a date string.
But getDataForQueryResource only allows int or null as return type and in the example above getDataForQueryResource throws a PHP-Error because getDataForQueryResource returns the return value from getDataForResource

### Expected / actual behavior

getDataForQueryResource should also be able to return a string

**Comment by mcop1** [comment]
Duplicate of https://github.com/pimcore/pimcore/issues/15292?

**Comment by drs-anton** [comment]
> Duplicate of #15292?

Absolutely!

**Comment by mcop1** [comment]
Ok, then I will close this issue and we will take a look at the problem in https://github.com/pimcore/pimcore/issues/15292. 

Thanks for reporting the problem.
