### ISSUE TITLE
[Bug]: Numeric trims all decimal places

### ISSUE THREAD

**Issue by chabicht** [pimcore/pimcore#15324]
### Pimcore version

11.0.0

### Steps to reproduce

- Create a class with a Number editable. Set `Decimal size` to 10 and `Decimal precision` to 2.
- Create an object of the class.
- Enter a value with decimal places, e.g. 1234.56.
- Reload the object.
- Decimal places are gone.

This is caused by casting $data to int in the preSetData method of Numeric
```
    public function preSetData(mixed $container, mixed $data, array $params = []): mixed
    {
        if (!is_null($data) && $this->getDecimalPrecision()) {
            $data = round((int)$data, $this->getDecimalPrecision());
        }

        return $data;
    }
```

**Comment by jdreesen** [comment]
This is a regression of #13474

I created a PR with the fix: #15325
