### ISSUE TITLE
[Bug]: It is not possible to delete a document link

### ISSUE THREAD

**Issue by j-jonas** [pimcore/pimcore#15348]
### Pimcore version

11.0.0

### Steps to reproduce

Create a document link
Try to delete the document link

Pimcore tries to add a recyclebin entry with:

curl "https://****/admin/recyclebin/add" -X POST -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0" -H "Accept: */*" -H "Accept-Language: de-DE,de;q=0.8,en;q=0.5,en-US;q=0.3" -H "Accept-Encoding: gzip, deflate, br" -H "X-pimcore-csrf-token: 1f4269a5815d1ac8dd9d3bf858e3878f44e25955" -H "X-pimcore-extjs-version-major: 7" -H "X-pimcore-extjs-version-minor: 0" -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" -H "X-Requested-With: XMLHttpRequest" -H "Origin: https://****" -H "Connection: keep-alive" -H "Referer: https://****/admin/" -H "Cookie: teaser=1; PHPSESSID=316b0f97f1f996643b6007ff6a0a40ed" -H "Sec-Fetch-Dest: empty" -H "Sec-Fetch-Mode: cors" -H "Sec-Fetch-Site: same-origin" -H "Pragma: no-cache" -H "Cache-Control: no-cache" -H "TE: trailers" --data-raw "type=document&id=62"

but this request is not working an ends with the error:

"in /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:266\n#0 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(266): ReflectionProperty->setValue(Object(Pimcore\\Model\\Document\\Link), Object(Pimcore\\Model\\Element\\ElementDescriptor))\n#1 ....
message	"Cannot assign Pimcore\\Model\\Element\\ElementDescriptor to property Pimcore\\Model\\Document\\Link::$object of type ?Pimcore\\Model\\Element\\ElementInterface"

**Comment by aryaantony92** [comment]
Unable to reproduce. It's working now.

**Comment by j-jonas** [comment]
I can verify it on https://demo.pimcore.com/admin/. Pimcore 11.0.3
Just create a link in the document tree, link it to a page and than try to delete it. The recyclebin/add request will fail...

`{
    "success": false,
    "traceString": "in \/var\/www\/html\/vendor\/myclabs\/deep-copy\/src\/DeepCopy\/DeepCopy.php:262\n#0 \/var\/www\/html\/vendor\/myclabs\/deep-copy\/src\/DeepCopy\/DeepCopy.php(262): ReflectionProperty-\u003EsetValue(Object(Pimcore\\Model\\Document\\Link), Object(Pimcore\\Model\\Element\\ElementDescriptor))\n#1 \/var\/www\/html\/vendor\/myclabs\/deep-copy\/src\/DeepCopy\/DeepCopy.php(214): DeepCopy\\DeepCopy-\u003EcopyObjectProperty(Object(Pimcore\\Model\\Document\\Link), Object(ReflectionProperty))\n#2 \/var\/www\/html\/vendor\/myclabs\/deep-copy\/src\/DeepCopy\/DeepCopy.php(150): DeepCopy\\DeepCopy-\u003EcopyObject(Object(Pimcore\\Model\\Document\\Link))\n#3 \/var\/www\/html\/vendor\/myclabs\/deep-copy\/src\/DeepCopy\/DeepCopy.php(95): DeepCopy\\DeepCopy-\u003ErecursiveCopy(Object(Pimcore\\Model\\Document\\Link))\n#4 \/var\/www\/html\/vendor\/pimcore\/pimcore\/models\/Element\/Recyclebin\/Item.php(343): DeepCopy\\DeepCopy-\u003Ecopy(Object(Pimcore\\Model\\Document\\Link))\n#5 \/var\/www\/html\/vendor\/pimcore\/pimcore\/models\/Element\/Recyclebin\/Item.php(180): Pimcore\\Model\\Element\\Recyclebin\\Item-\u003EmarshalData(Object(Pimcore\\Model\\Document\\Link))\n#6 \/var\/www\/html\/vendor\/pimcore\/pimcore\/models\/Element\/Recyclebin\/Item.php(69): Pimcore\\Model\\Element\\Recyclebin\\Item-\u003Esave(Object(Pimcore\\Model\\User))\n#7 \/var\/www\/html\/vendor\/pimcore\/admin-ui-classic-bundle\/src\/Controller\/Admin\/RecyclebinController.php(194): Pimcore\\Model\\Element\\Recyclebin\\Item::create(Object(Pimcore\\Model\\Document\\Link), Object(Pimcore\\Model\\User))\n#8 \/var\/www\/html\/vendor\/symfony\/http-kernel\/HttpKernel.php(166): Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\RecyclebinController-\u003EaddAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#9 \/var\/www\/html\/vendor\/symfony\/http-kernel\/HttpKernel.php(74): Symfony\\Component\\HttpKernel\\HttpKernel-\u003EhandleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#10 \/var\/www\/html\/vendor\/symfony\/http-kernel\/Kernel.php(197): Symfony\\Component\\HttpKernel\\HttpKernel-\u003Ehandle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#11 \/var\/www\/html\/public\/index.php(35): Symfony\\Component\\HttpKernel\\Kernel-\u003Ehandle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#12 {main}",
    "trace": [
        {
            "file": "\/var\/www\/html\/vendor\/myclabs\/deep-copy\/src\/DeepCopy\/DeepCopy.php",
            "line": 262,
            "function": "setValue",
            "class": "ReflectionProperty",
            "type": "-\u003E",
            "args": [
                {},
                {}
            ]
        },
        {
            "file": "\/var\/www\/html\/vendor\/myclabs\/deep-copy\/src\/DeepCopy\/DeepCopy.php",
            "line": 214,
            "function": "copyObjectProperty",
            "class": "DeepCopy\\DeepCopy",
            "type": "-\u003E",
            "args": [
                {},
                {
                    "name": "object",
                    "class": "Pimcore\\Model\\Document\\Link"
                }
            ]
        },
        {
            "file": "\/var\/www\/html\/vendor\/myclabs\/deep-copy\/src\/DeepCopy\/DeepCopy.php",
            "line": 150,
            "function": "copyObject",
            "class": "DeepCopy\\DeepCopy",
            "type": "-\u003E",
            "args": [
                {}
            ]
        },
        {
            "file": "\/var\/www\/html\/vendor\/myclabs\/deep-copy\/src\/DeepCopy\/DeepCopy.php",
            "line": 95,
            "function": "recursiveCopy",
            "class": "DeepCopy\\DeepCopy",
            "type": "-\u003E",
            "args": [
                {}
            ]
        },
        {
            "file": "\/var\/www\/html\/vendor\/pimcore\/pimcore\/models\/Element\/Recyclebin\/Item.php",
            "line": 343,
            "function": "copy",
            "class": "DeepCopy\\DeepCopy",
            "type": "-\u003E",
            "args": [
                {}
            ]
        },
        {
            "file": "\/var\/www\/html\/vendor\/pimcore\/pimcore\/models\/Element\/Recyclebin\/Item.php",
            "line": 180,
            "function": "marshalData",
            "class": "Pimcore\\Model\\Element\\Recyclebin\\Item",
            "type": "-\u003E",
            "args": [
                {}
            ]
        },
        {
            "file": "\/var\/www\/html\/vendor\/pimcore\/pimcore\/models\/Element\/Recyclebin\/Item.php",
            "line": 69,
            "function": "save",
            "class": "Pimcore\\Model\\Element\\Recyclebin\\Item",
            "type": "-\u003E",
            "args": [
                {}
            ]
        },
        {
            "file": "\/var\/www\/html\/vendor\/pimcore\/admin-ui-classic-bundle\/src\/Controller\/Admin\/RecyclebinController.php",
            "line": 194,
            "function": "create",
            "class": "Pimcore\\Model\\Element\\Recyclebin\\Item",
            "type": "::",
            "args": [
                {},
                {}
            ]
        },
        {
            "file": "\/var\/www\/html\/vendor\/symfony\/http-kernel\/HttpKernel.php",
            "line": 166,
            "function": "addAction",
            "class": "Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\RecyclebinController",
            "type": "-\u003E",
            "args": [
                {
                    "attributes": {},
                    "request": {},
                    "query": {},
                    "server": {},
                    "files": {},
                    "cookies": {},
                    "headers": {}
                }
            ]
        },
        {
            "file": "\/var\/www\/html\/vendor\/symfony\/http-kernel\/HttpKernel.php",
            "line": 74,
            "function": "handleRaw",
            "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
            "type": "-\u003E",
            "args": [
                {
                    "attributes": {},
                    "request": {},
                    "query": {},
                    "server": {},
                    "files": {},
                    "cookies": {},
                    "headers": {}
                },
                1
            ]
        },
        {
            "file": "\/var\/www\/html\/vendor\/symfony\/http-kernel\/Kernel.php",
            "line": 197,
            "function": "handle",
            "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
            "type": "-\u003E",
            "args": [
                {
                    "attributes": {},
                    "request": {},
                    "query": {},
                    "server": {},
                    "files": {},
                    "cookies": {},
                    "headers": {}
                },
                1,
                true
            ]
        },
        {
            "file": "\/var\/www\/html\/public\/index.php",
            "line": 35,
            "function": "handle",
            "class": "Symfony\\Component\\HttpKernel\\Kernel",
            "type": "-\u003E",
            "args": [
                {
                    "attributes": {},
                    "request": {},
                    "query": {},
                    "server": {},
                    "files": {},
                    "cookies": {},
                    "headers": {}
                }
            ]
        }
    ],
    "message": "Cannot assign Pimcore\\Model\\Element\\ElementDescriptor to property Pimcore\\Model\\Document\\Link::$object of type ?Pimcore\\Model\\Element\\ElementInterface"
}`

**Comment by dvesh3** [comment]
> Just create a link in the document tree, link it to a page and than try to delete it. The recyclebin/add request will fail...

I can reproduce it with these steps.

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15524
