### ISSUE TITLE
Asset preloading with HTTP/2 Push

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1534]
In templating helpers: 
- `headLink`
- `headScript`

**Comment by brusch** [comment]
See also http://symfony.com/blog/new-in-symfony-3-3-asset-preloading-with-http-2-push

**Comment by brusch** [comment]
Maybe also consider: https://css-tricks.com/cache-aware-server-push/

**Comment by jansarmir** [comment]
Actualy headScript does not add cache buster.
Is it somehow linked with this feature, or it is just bug?
HeadLink adds cache buster, so i am confused, if iam missing something.
