### ISSUE TITLE
[Bug]: gridconfigs.setAsFavourite column is missing from install.sql script

### ISSUE THREAD

**Issue by torqdev** [pimcore/pimcore#15359]
### Pimcore version

10.5

### Steps to reproduce

1. Begin a new Pimcore 10.5 (or 10.6 or 11.x) project
2. Run `pimcore-install`

### Expected / actual behavior

# Expected
`gridconfigs.setAsFavourite` column would exist on the database schema, because migration `Version20211016084043` creates this column, and no future migrations modify or drop this column. The migration history of the generated database also states migration `Version20211016084043` has been run so the migration can't add it again later. 

# Actual
The `migrations_versions` table shows that migration `Version20211016084043` has been applied, but the `gridconfigs` table does not have a `setAsFavourite` column.

**Comment by kingjia90** [comment]
Fixed by #15360
