### ISSUE TITLE
[Bug]: Breadcrumbs navigation doesn't show any pages

### ISSUE THREAD

**Issue by HemiCZ** [pimcore/pimcore#15366]
### Pimcore version

11.0

### Steps to reproduce

https://pimcore.com/docs/platform/Pimcore/Documents/Navigation/#breadcrumbs

### Expected / actual behavior

The problem is in `lib/Navigation/Renderer/Breadcrumbs.php`, function `getPages()`, row 164. Function `$this->findActive($container)` returns empty array, because parameter `$maxDepth` will be always -1 and then parameter `$found` is always null because `$foundDepth > $maxDepth` is always true.

**Comment by blankse** [comment]
@HemiCZ I created a PR https://github.com/pimcore/pimcore/pull/15376

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15376
