### ISSUE TITLE
[Bug]: Relations throw error

### ISSUE THREAD

**Issue by HemiCZ** [pimcore/pimcore#15367]
### Pimcore version

11.0

### Steps to reproduce

https://pimcore.com/docs/platform/Pimcore/Documents/Editables/Relations_Many-To-Many#basic-usage

### Expected / actual behavior

`Pimcore\Model\Element\Service::doHideUnpublished(): Argument #1 ($element) must be of type ?Pimcore\Model\Element\ElementInterface, bool given, called in /var/www/html/vendor/pimcore/pimcore/models/Document/Editable/Relations.php on line 290 File: /var/www/html/vendor/pimcore/pimcore/models/Element/Service.php Line: 245`

There si this error when I use `{% for element in pimcore_relations("objectPaths") %}`. When I use `{% for element in pimcore_relations("objectPaths").getElements() %}` then everything works fine.

**Comment by blankse** [comment]
@HemiCZ I created a PR https://github.com/pimcore/pimcore/pull/15375

**Comment by dvesh3** [comment]
Fixed by #15375
