### ISSUE TITLE
[Bug]: copyAsChild() creating duplicate documents

### ISSUE THREAD

**Issue by epochlabs-dev** [pimcore/pimcore#15361]
### Pimcore version

11.0.0

### Steps to reproduce

Hit the following code from a controller:
     
```
/**
   * @Route("/clone-page/{name}", name="clone-page")
   *
   */
public function clonePage($name)
{
                $enableInheritance = false;
                $resetIndex = false;
                $language = false;
                $target = \Pimcore\Model\Document\Page::getByPath('/');
                $source = \Pimcore\Model\Document\Page::getByPath('/en/Magazine/Lifestyle');
                $systemAdmin = \Pimcore\Model\User::getById(0);
                $documentService = new \Pimcore\Model\Document\Service($systemAdmin);
                $newPage = $documentService->copyAsChild($target, $source, $enableInheritance, $resetIndex, $language);
                $newPage->setKey($name);
                $newPage->save();
                dd("Doc ID: ".$newPage->getId());
}

```
Delete the resulting document via the Admin portal, and re-run the clonePage() function with a different name. Repeat 4-5 times. 

### Expected / actual behavior

**Expected:**

Document ID should increment by 1 each time, and 1 new copy of the cloned document should appear in the Documents list in the Admin portal.

**Actual:**

After a few tries of repeating the above steps, document ID starts incrementing by 2 at a time, and 2 copies of the cloned document appear in the list (one with the expected name, and one with a previously deleted name).

**Comment by dvesh3** [comment]
Hi @epochlabs-dev I cannot reproduce the issue with given steps. Could you please check with latest version 11.0.3? thanks!

**Comment by epochlabs-dev** [comment]
Upgraded to 11.0.3 and it is still happening. I found that I can only reproduce it when using the same browser for the admin session and clone-page URL, so something to do with session-sharing somehow?

I made a screen recording of the bug in action in case my explanation was not clear:
https://www.dropbox.com/s/jv1f2mde9e5vzdv/pimcore%20page%20clone%20bug.mov?dl=0

You can see in this video that the first clone I create has document ID 295. Then when I delete it and create another clone, it skips a number and gets document ID 297. Then when I refresh the document list in the admin portal, I see "clone2" as document 297, but also the deleted name "clone1" comes back, with ID 296. Delete them both, and the same thing happens again. Somehow by running this code once I am getting two documents each time, one of which is named after a previously deleted document.

**Comment by dvesh3** [comment]
Sorry, still not able to reproduce it on my end. Could you please check if you don't have a custom event listener on document update event interfering on the save?

**Comment by dvesh3** [comment]
@epochlabs-dev any more findings?

**Comment by dvesh3** [comment]
Closed due to inactivity. Please feel free to continue the discussion. thanks!

**Comment by epochlabs-dev** [comment]
My latest test was on a fresh copy of Pimcore 11.0.3, so no custom event listeners or anything else.

However I am also getting a lot of "Detected CSRF Attack" errors even on this fresh install, so this may be related.  
If you are not able to reproduce my symptoms, it could be that they stem from some kind of problem with PHP sessions on my server.
