### ISSUE TITLE
Symfony 6.3 incompatibility

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#15370]
### Pimcore version

11.0.0 - 11.x

### Steps to reproduce

This change in `symfony/doctrine-messenger` causes the Codeception tests to fail: 
https://github.com/pimcore/pimcore/actions/runs/5242173161/jobs/9467698999?pr=15350#step:11:28

This is caused by this change: 
https://github.com/symfony/symfony/pull/50524/files#r1229509009

Actually this change deletes all existing tables in the database when creating the schema for the messenger component here: 
https://github.com/pimcore/pimcore/blob/11.x/bundles/InstallBundle/src/Installer.php#L666

**Comment by brusch** [comment]
See also comments here: https://github.com/symfony/symfony/pull/50524#discussion_r1229509009

**Comment by brusch** [comment]
Created a PR fixing the issue at Symfony: https://github.com/symfony/symfony/pull/50717

**Comment by jdreesen** [comment]
Is this also a problem in Pimcore 10? Because the first Symfony issue you mentioned ([#50524](https://github.com/symfony/symfony/pull/50524)) was merged into Symfony 5.4.

**Comment by brusch** [comment]
I'd assume so, yes.

**Comment by brusch** [comment]
See also: https://github.com/doctrine/dbal/pull/5766

**Comment by jdreesen** [comment]
Okay, but this PR was merged into Doctrine DBAL `v3.5` and Pimcore 10 is `^2.12`, so it shouldn't be an issue there.
