### ISSUE TITLE
New messenger queue for recalculating dependencies on save/update of elements

### ISSUE THREAD

**Issue by aryaantony92** [pimcore/pimcore#15378]
### Improvement description

Please see https://github.com/pimcore/pimcore/issues/15426#issuecomment-2089991720 and https://github.com/pimcore/pimcore/pull/15280#discussion_r1211346600

**Comment by brusch** [comment]
We need to check if this could have some negative side-effects in terms of data consistency (cleanups, ...)

**Comment by fashxp** [comment]
duplicate of https://github.com/pimcore/pimcore/issues/15426
