### ISSUE TITLE
[Bug]: GeoCoordinates getLatitude and getLongitude allow return of null

### ISSUE THREAD

**Issue by mmoesenbacher** [pimcore/pimcore#15389]
### Pimcore version

11.0.0

### Steps to reproduce

GeoCoordinates Latitude/Longitude can can be null, but getter does not allow return of null.

Reproduce:
new object with empty GeoCoordinates

$object->save();

error: 
Pimcore\Model\DataObject\Data\GeoCoordinates::getLongitude(): Return value must be of type float, null returned

fix:
public function getLongitude(): ?float instead of public function getLongitude(): float
public function getLatitude(): ?float instead of public function getLatitude(): float

**Comment by blankse** [comment]
@mmoesenbacher I created a PR https://github.com/pimcore/pimcore/pull/15390
