### ISSUE TITLE
[Bug]: Can't open Custom Report with data source

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#15393]
### Pimcore version

11.x

### Steps to reproduce

follow-up: https://github.com/pimcore/pimcore/issues/14745

Create a new Custom Report and add a data source without filling in the mandatory fields
Save it and try to open it

### Expected / actual behavior

Show report without exception

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15804
