### ISSUE TITLE
[Asset] Filename hashes for thumbnails are wrong for AVIF images

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#15392]
### Pimcore version

11.x

### Steps to reproduce

Pimcore 11 introduced a hash of the config that is appended to the thumbnails filename: 
`foo.53e2fd88.avif`

The actual  issue with AVIF thumbnails is, that the hash is different depending on from where the thumbnail was generated. 

Calling the thumbnail from `\Pimcore\Bundle\CoreBundle\Controller\PublicServicesController::thumbnailAction()` results in a different hash than calling it from `\Pimcore\Model\Asset\Image\Thumbnail::getHtml()`. 

This is caused by the fact that the `auto_formats` config is not getting applied in the `PublicServicesController` and therefore the hash is different (default quality is different for AVIF formats).

**Comment by brusch** [comment]
Already fixed by f7ed709ed10b7bb591828930244ba1f237930a6b which was commited by mistake to the wrong branch.

**Comment by blankse** [comment]
@brusch But https://github.com/pimcore/pimcore/commit/f7ed709ed10b7bb591828930244ba1f237930a6b is only in branch `11.x`. Should be in branch `11.0`, right?

**Comment by brusch** [comment]
@blankse yes, thanks for the hint, I'm just in the process of 🍒-picking 😉
