### ISSUE TITLE
[Bundles] Post Update Commands & Migration Commands

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1539]
A Pimcore bundle should offer the possibility to perform a post update command automatically after  `composer update`. Additionally there should be the possibility manually perform a migration/update command. 

Maybe we should also think about a prompt directly after `composer update` that asks if the migrations/update script should be performed or not.

**Comment by dpfaffenbauer** [comment]
Does this mean you provide a way for Bundles (=Plugins) to perform migrations?

**Comment by brusch** [comment]
yes

**Comment by brusch** [comment]
See also: #1303

**Comment by maff** [comment]
@dpfaffenbauer @solverat (and anybody else interested) #1847 implements the basic infrastructure for bundle and global app migrations. It would be great if you'd find the time to give a look at the current state to share your thoughts :)

**Comment by dpfaffenbauer** [comment]
@maff This is awesome 👍 , I owe you some 🍻  :)

I already started testing with it, here is my CoreShop Branch for it: https://github.com/coreshop/CoreShop/tree/migrations looks good so far 👍

**Comment by solverat** [comment]
Looks good to me also (great, great work). The only thing i'm struggling with is that you're going to force every bundle to use autowire and autoconfiguration. maybe you could define the `MigrationInstaller` class as an abstract service and every installer needs to define it as its parent?

```yaml
awesome_bundle.installer:
        parent: '@pimcore.installer.migration_installer'
        class: AwesomeBundle\Installer
```

**Comment by dpfaffenbauer** [comment]
@maff Just wrote and executed my first Bundle Migration. Works like a charm 👍  (https://github.com/coreshop/CoreShop/commit/83d9e117b094e9be8adfb340c2626d0d1cc6add6)

one thing I came upon is: DoctrineMigrationsBundle supports ContainerAwareInterface, doesn't seem like Pimcore Migrations support that?

**Comment by maff** [comment]
@dpfaffenbauer `ContainerAware` migrations should now work (see df6cb5c211adcbe17464fea16ab9283f2409718a).

**Comment by dpfaffenbauer** [comment]
👍 awesome, I'll give it a try when writing my next migration
