### ISSUE TITLE
AbstractObject getById with ForceReload

### ISSUE THREAD

**Issue by mschweiger90** [pimcore/pimcore#1540]
# AbstractObject getById with ForceReload

## Feature description 
Function to force reload a object. Works with a Hack in Pimcore 4:
 \Pimcore\Cache::remove('my_object_id');
\Zend_Registry::getInstance()->offsetUnset("my_object_id");

**Comment by brusch** [comment]
This is already there, see: 
https://github.com/pimcore/pimcore/blob/ca8072ef7a70ad1b59513c70f770ab489f069698/pimcore/models/Object/AbstractObject.php#L246-L246

Just pass `true` as the 2nd argument ;) 

### Example

```
$a = Object::getById(123, true);
$b = Object::getById(123, true); 
$a !== $b
```

**Comment by brusch** [comment]
This is of course also possible with Documents and Assets. 
I've just added the same functionality to `getByPath()` (Pimcore 5 only).
