### ISSUE TITLE
[Bug]: Can't preview object for main site if other sites are configured

### ISSUE THREAD

**Issue by tmannherz** [pimcore/pimcore#15417]
### Pimcore version

10.6.2 & 11.0.0

### Steps to reproduce

1. Create a document (`other-site` in screenshot)
![image](https://github.com/pimcore/pimcore/assets/533798/56b23c4f-d5b8-44ff-82b3-dbfab4241b09)
2. In the context menu, choose _Advanced -> Use as site_
![image](https://github.com/pimcore/pimcore/assets/533798/ea3f6395-dd00-427e-aa8d-0f871767028e)
3. Configure the site in the modal that pops up. The info you put here doesn't matter for reproducing this issue.
4. Open a data object and go to the Preview tab. With a Site configured, you'll see an additional dropdown where you can select the site context in which to load the preview. This dropdown will only include a single option for the site you just configured. There's no way to preview the "main" site.
![image](https://github.com/pimcore/pimcore/assets/533798/c2c9a366-3269-4e3a-a39e-2a9eb0f57824)

This is reproducible on the demo site (https://demo.pimcore.fun/admin/).

### Expected / actual behavior

Without any sites configured, Pimcore will load data object previews under the context of the "main" site.

With sites configured, there is no way to preview data objects under the context of the "main" site since it's not an option within the Preview's Site dropdown.

I would expect to see an additional option in the dropdown for "Main" or something similar.

**Comment by kingjia90** [comment]
Fixed
- Pimcore `10.6` by https://github.com/pimcore/pimcore/pull/15506
- Pimcore `11` by https://github.com/pimcore/admin-ui-classic-bundle/pull/162
