### ISSUE TITLE
[Bug]: Nginx does not allow to deliver .webp files

### ISSUE THREAD

**Issue by jhormel** [pimcore/pimcore#15416]
### Pimcore version

11.0.0

### Steps to reproduce

1. Upload an image with format `.webp`
2. Access it via its public URL

Results in 404 // NotFound.

### Expected / actual behavior

1. Upload an image with format `.webp`
2. Access it via its public URL

Should display the image.

Further notes:
Pimcore Nginx Config: https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/System_Setup_and_Hosting/Nginx_Configuration/

Line: `location ~* ^(?!/admin)(.+?)\.((?:css|js)(?:\.map)?|jpe?g|gif|png|svgz?|eps|exe|gz|zip|mp\d|m4a|ogg|ogv|webm|pdf|docx?|xlsx?|pptx?)$ {`
Does not contain `webp`

Fix suggestion: `location ~* ^(?!/admin)(.+?)\.((?:css|js)(?:\.map)?|jpe?g|gif|png|svgz?|eps|exe|gz|zip|mp\d|m4a|ogg|ogv|webp|webm|pdf|docx?|xlsx?|pptx?)$ {`

**Comment by blankse** [comment]
@jhormel I created a PR: https://github.com/pimcore/pimcore/pull/15519

**Comment by jdreesen** [comment]
And I created: pimcore/skeleton#157

**Comment by dvesh3** [comment]
Fixed by #15519
