### ISSUE TITLE
[Feature]: improve command line naming and consistency

### ISSUE THREAD

**Issue by cipribucur** [pimcore/pimcore#15421]
### Feature description

all these commands take care of creating/updating indexes, yet the names are not consistent

bin/console ecommerce:indexservice:bootstrap --create-or-update-index-structure
bin/console ecommerce:indexservice:reset-queue update-index --tenant=es
bin/console datahub:simple-rest:create-or-update-mapping
bin/console datahub:simple-rest:init-index 
bin/console portal-engine:update:index-recreate

can you please align the naming. 

thanks.

**Comment by dvesh3** [comment]
Use aliases for existing names and trigger deprecation on using the alias.

**Comment by aryaantony92** [comment]
Command list with new names

https://github.com/pimcore/portal-engine/pull/448#issuecomment-1737581424

**Comment by fashxp** [comment]
I would postpone that topic for now and push it to Pimcore 11 for several reasons:  
- if we would do it, there would be much more commands involved (also for other task groups like queue processing, etc.) 
- some command names also reflect namespace structure (e.g. in portal engine)
- some commands would need to be splitted at all or changed in scope they are handling (e.g. ecommerce framework bootstrap command)

Thus commands itself would need to be refactored, eventually namespaces would need to be changed which would result in much bigger tasks and potential BC breaks. 
First we should create a general naming schema, summarize that in our internal guidelines and then refactor all affected modules.

**Comment by markus-moser** [comment]
@fashxp I would say let's close this topic for now, okay? For sure it would be possible to harmonize it a little bit but all of these technologies work a little bit different and I do not think that it is worth to rename it as we potentially could produce quite a bit of confusion without big benefit.
