### ISSUE TITLE
[Bug]: TinyMCE removes <br>

### ISSUE THREAD

**Issue by Myrmidonut** [pimcore/pimcore#15423]
### Pimcore version

11.0

### Steps to reproduce

Insert a line-break inside a wysiwyg field, either using `<br>` inside the code view of TinyMCE, or with shift + enter.

### Expected / actual behavior

**Expected:**

The `<br>` stays in the wysiwyg element when using the default TinyMCE editor.

**Actual behavior:**

All `<br>` get removed after saving and reloading.

**Additional Information:**

I tried these options without the desired effect:

```
newline_behavior: 'default'
valid_children: '+p[br]'
remove_trailing_brs: false
remove_linebreaks: false
```

Enforcing `<br>` with `newline_behavior: 'linebreak'` loses all `<br>` as well.

I added a `console.log(tinymce.activeEditor.contentAreaContainer.innerHTML);` inside the `editor.on('input', function (eChange) {` and it gets the correct `<br>`. It happens somewhere down the line.

You can try it out in the Pimcore Demo, it happens there as well.

I initially mentioned this in the Discussions section: [https://github.com/pimcore/pimcore/discussions/15399](https://github.com/pimcore/pimcore/discussions/15399) , but I believe it is either a bug, or line-breaks should be allowed by default.

**Comment by Myrmidonut** [comment]
Turns out it is the HTML sanitizer that does it. I suggest adding `br: ''` to 
```
framework:
    html_sanitizer:
        sanitizers:
            pimcore.wysiwyg_sanitizer:
                allow_elements:
```
in `vendor/pimcore/pimcore/bundles/CoreBundle/config/pimcore/default.yaml` to have the default `<br>` behavior back.

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15456

**Comment by Myrmidonut** [comment]
Thanks guys! :-D
