### ISSUE TITLE
Image Cropper: Strange behavior of Resizable-Component

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1543]
See video:

**Comment by brusch** [comment]
[17-05-_2017_14-32-37.zip](https://github.com/pimcore/pimcore/files/1007694/17-05-_2017_14-32-37.zip)

**Comment by weisswurstkanone** [comment]
already fixed in ExtJS 6.5, waiting for the next GPL version

**Comment by brusch** [comment]
Only on hybrid touch devices (ultrabooks, ...).
