### ISSUE TITLE
[Bug]: Wysiwyg editor doesn't show the blocks select by default

### ISSUE THREAD

**Issue by luka-jukic** [pimcore/pimcore#15444]
### Pimcore version

11.0.2

### Steps to reproduce

Open up any Object or Document with a Wysiwyg field in it and have a look at the toolbar.

<img width="504" alt="image" src="https://github.com/pimcore/pimcore/assets/40577324/8da1e24b-c09a-4e21-84f3-809b52b9f95f">

### Expected / actual behavior

As the basic implementation of the editor in bundle shows, the blocks select part should be displayed.
<img width="669" alt="image" src="https://github.com/pimcore/pimcore/assets/40577324/e5234cdf-00a8-434e-88c2-dc084308b003">
Due to the installation of version 6.*, the key which displays the block selects had changed.

This was changed from 'formselect' to 'blocks'.

<img width="564" alt="image" src="https://github.com/pimcore/pimcore/assets/40577324/66cabd0e-007e-4182-b76e-fd4a47579309">

**Comment by dvesh3** [comment]
Fixed by #15445
