### ISSUE TITLE
[PIMCORE 5 (Empty Installation)] : Search Window: Class selection dropdown throws no route found exception

### ISSUE THREAD

**Issue by anupam1501** [pimcore/pimcore#1544]
### **Steps to Reproduce :**
 1- Click on the search icon - Objects
 2 - Select a class from dropdown

### **Expected Behaviour :**
 - Show objects listing as per selection

### **Actual Behaviour :**
- Throws exception - **"No route found for "POST /admin/search/search/find&xaction=read"**

![screenshot](https://cloud.githubusercontent.com/assets/28050181/26204369/28e8b2ac-3bfc-11e7-9cc5-81e06b166b7c.png)

**Comment by weisswurstkanone** [comment]
Unable to reproduce on 
https://demo-5.pimcore.org/admin/

**Comment by weisswurstkanone** [comment]
Any steps to reproduce would be welcome ;-)

**Comment by anupam1501** [comment]
It seems issue has been resolved.Thanks :+1:
