### ISSUE TITLE
[Bug]: Typed static property Pimcore\Image\Adapter\Imagick::$CMYKColorProfile must not be accessed before initialization 

### ISSUE THREAD

**Issue by pimcore-galilee** [pimcore/pimcore#15450]
### Pimcore version

11.0

### Steps to reproduce

with following attached file preview will not succeed.
[C013900279 Diorshow Palette 5COULEURS DENIM 20 DT SL Pti_F39.psd.zip](https://github.com/pimcore/pimcore/files/11904448/C013900279.Diorshow.Palette.5COULEURS.DENIM.20.DT.SL.Pti_F39.psd.zip)
You can reproduce on demo env.

### Expected / actual behavior

changing properties such as : 
    protected static ?string $RGBColorProfile = null;
    protected static ?string $CMYKColorProfile = null;
fixes the problem.

**Comment by dvesh3** [comment]
Fixed by #15528
