### ISSUE TITLE
[Bug]: Workflow translate place indicator title

### ISSUE THREAD

**Issue by MG-Arnaud** [pimcore/pimcore#15457]
### Pimcore version

10.6

### Steps to reproduce

Hello,

When you use an admin translation for the workflow place indicator title, it's not translated... 

You have translated the place indicator label but not the title as you can see on the below picture : 
![image](https://github.com/pimcore/pimcore/assets/18262300/b5385476-51b3-41e1-9fc2-861a7d09db71)

File to modify in the Pimcore version 10.6 : 
https://github.com/pimcore/pimcore/blob/10.6/bundles/CoreBundle/Resources/views/Workflow/statusinfo/toolbarStatusInfo.html.twig

I check also in the new Pimcore 11 and the bug is still present : 
https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/templates/Workflow/statusinfo/toolbarStatusInfo.html.twig

So you just have to replace this title code : 
`title="{{ place.title }}"`

with : 
`title="{{ translator.trans(place.title,[],'admin') }}"` 

By doing that we can have the correct translation for the title as you can see on this picture : 

![image](https://github.com/pimcore/pimcore/assets/18262300/d483c500-e759-4d84-b5df-2d83e810ecfe)

Thanks.

**Comment by MG-Arnaud** [comment]
Hello,

Can you also translate the places title in the file :
[bundles/CoreBundle/Resources/views/Workflow/statusinfo/allPlacesStatusInfo.html.twig](https://github.com/pimcore/pimcore/blob/10.6/bundles/CoreBundle/Resources/views/Workflow/statusinfo/allPlacesStatusInfo.html.twig)

By doing that you correct this problem in the grid view : 
![image](https://github.com/pimcore/pimcore/assets/18262300/0f23610b-edb3-4f52-9a18-8ca14dfe7cea)



And you need also to translate the label of the workflow in your Controller in the function getWorkflowDetailsStore : 
[bundles/AdminBundle/Controller/Admin/WorkflowController.php](https://github.com/pimcore/pimcore/blob/10.6/bundles/AdminBundle/Controller/Admin/WorkflowController.php)

Indeed we have this bad result in the BO when we used a translated key for the label : 
![image](https://github.com/pimcore/pimcore/assets/18262300/d3e2e0cb-a3d9-4ae8-865f-cae38d75cb7d)

Thanks

**Comment by aryaantony92** [comment]
@MG-Arnaud Thank you for the suggestions. Created a PR with the given suggestions.https://github.com/pimcore/pimcore/pull/15736

**Comment by MG-Arnaud** [comment]
Oh thanks you very much for your pull request @aryaantony92 it's a very nice initiative 😀

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15736

**Comment by aryaantony92** [comment]
@MG-Arnaud Thanks again
