### ISSUE TITLE
[Improvement]: Change test to allow for setting of max depth in navigation renderer.

### ISSUE THREAD

**Issue by efnack** [pimcore/pimcore#15458]
### Improvement description

Setting max depth in navigation renderer does not seem to work.

Suggest changing line 198 of pimcore/lib/Navigation/Renderer/AbstractRenderer.php

From:
if ((!is_int($maxDepth) || $maxDepth < 0) && null !== $maxDepth) {

To:
if ((!is_int($maxDepth) || $maxDepth < 0) || null == $maxDepth) {

**Comment by blankse** [comment]
@efnack Should be fixed with https://github.com/pimcore/pimcore/pull/15376, right?

**Comment by efnack** [comment]
Yes, this fixes the issue. On 21 Jul 2023, at 09:56, Sebastian Blank ***@***.***> wrote:﻿
@efnack Should be fixed with #15376, right?
