### ISSUE TITLE
[Bug]: Thumbnails broken when setting PIMCORE_SYSTEM_TEMP_DIRECTORY to work with cloud storage (s3)

### ISSUE THREAD

**Issue by flamadrid-jsmdg** [pimcore/pimcore#15454]
### Pimcore version

10.5.25

### Steps to reproduce

We have a setup that uses Kubernetes so we have multiple Pimcore pods, therefore we use S3 as blob storage, and we have configured the **flysystem** accordingly. 
Because of multiple pods we needed to specify too **pimcore.temp.storage** to use S3 and also adjust the constant **PIMCORE_SYSTEM_TEMP_DIRECTORY** to point to the same place.
This way we can make sure that exports with the **Advanced Object Search** works correctly.
All this is fine but when setting the constant PIMCORE_SYSTEM_TEMP_DIRECTORY to use S3 instead, the images thumbnails break. I debugged it and they seem to work if the `[0]` is removed in here: https://github.com/pimcore/pimcore/blob/99a8d04f0790145cfb7f44472222b7d26e595944/lib/Image/Adapter/Imagick.php#L80
Not sure why is that there, perhaps is used for PDF or something like that, but I wanted to check before creating a PR.
With thumbnails breaking I mean that the subsequent call `$i->readImage($imagePathLoad) ` will end up in an exception with the message "fail to read the file", however it works without adding the `[0]`
Cheers.

**Comment by brusch** [comment]
This is mainly because of multilayered/paged image formats, such as PSD. 
Maybe we should add this just for certain file formats 🤔

**Comment by solverat** [comment]
@flamadrid-jsmdg I also stumbled on that before. I faced the same exception when we had to generate an SVG preview. However, I realized that it won't work with ImageMagick `6.9.11-60` but works on `6.9.10-23` (Q16).

**Comment by flamadrid-jsmdg** [comment]
@solverat So they kind of removed that _feature_? Not 100% sure but I think pimcore's dockerfile includes the latest stable version that would be 7, which is what we are currently using.

**Comment by solverat** [comment]
@flamadrid-jsmdg: Not sure either, using the `[0]` is still valid. I've already googled for a solution some time ago but was not able to find a solid answer/solution.

 A easy way could be:

```php
try {
    $status = $i->readImage($imagePathLoad . '[0]');
} catch(\Throwable $e) {
    $status = $i->readImage($imagePathLoad);
}
```

However, checking for valid extensions like pdf, psd would be the more correct solution but then we need to maintain a proper extension list.

**Comment by solverat** [comment]
Btw regarding SVG. We also had the case that the SVG extension was not available. Check ` /usr/lib/x86_64-linux-gnu/ImageMagick-6.9.11/modules-Q16/coders/` (or similar) for `svg.la` for example. If it's not present you need to install the libmagickcore extra package:

`sudo apt-get install libmagickcore-6.q16-2-extra`

**Comment by flamadrid-jsmdg** [comment]
@solverat I think your solution here https://github.com/pimcore/pimcore/issues/15454#issuecomment-1619102366 seems to be the most pragmatic as a bugfix. Maintaining a list is a chore, not sure if there is a lib that provides what file types are support layering or not. More over I tried with a sample PSD and using ` $status = $i->readImage($imagePathLoad);` directly without the `[0]` seems to work too.
So perhaps we can use that directly, specially that it works with the current versions of libmagickcore that is included Pimcore's official docker image.

**Comment by brusch** [comment]
I think there's a misunderstanding, `PIMCORE_SYSTEM_TEMP_DIRECTORY` shouldn't be on S3, it's fine to have it on a local temp volume, there's no need to share this between pods. How do you even point `PIMCORE_SYSTEM_TEMP_DIRECTORY`to S3, using stream wrappers?

**Comment by flamadrid-jsmdg** [comment]
@brusch The reason that we have to put `PIMCORE_SYSTEM_TEMP_DIRECTORY` on S3 is that the **advanced-object-search**  makes use of it to create a initial csv ([here](https://github.com/pimcore/advanced-object-search/blob/5.x/src/Controller/AdminController.php#L220)), but consecutive requests will fail as they could be handled by another pod instance that does not have the csv file in its local storage. I think this file is generated initially in the` /get-export-jobs` endpoint from the **advanced-object-search**.
I've seen other parts of the pimcore source code that they refer to the **temp** storage like so
`$storage = Storage::get('temp');
$storage->write($this->getCsvFile($fileHandle), '');`

**Comment by brusch** [comment]
@flamadrid-jsmdg still, `PIMCORE_SYSTEM_TEMP_DIRECTORY` should be on a local filesystem for several reasons, so imho this should be fixed in advanced-object-search.

**Comment by flamadrid-jsmdg** [comment]
@brusch hmm ok. But then what is the difference of `PIMCORE_SYSTEM_TEMP_DIRECTORY` and `Storage::get('temp')` ?
The fix in **advanced-object-search** should involve not using `PIMCORE_SYSTEM_TEMP_DIRECTORY` ?
I'm not much deep into the code specifics, but the **advanced-object-search** is not aware of any file abstraction right?

**Comment by brusch** [comment]
`Storage::get('temp')` is intended to be used for temp files which need to be stateful, e.g. when having multiple export jobs writing to the same file. `PIMCORE_SYSTEM_TEMP_DIRECTORY` is used for stateless stuff, it's just used locally and only relevant for the current process.

**Comment by flamadrid-jsmdg** [comment]
@brusch I created the [issue](https://github.com/pimcore/advanced-object-search/issues/230) in **advanced-object-search** and the [PR](https://github.com/pimcore/advanced-object-search/pull/231), so I think we can close this one.

**Comment by aryaantony92** [comment]
Closed in favour of advanced-object-search issue
