### ISSUE TITLE
[Bug]: Various Deprecations are not resolve-able within the same version.

### ISSUE THREAD

**Issue by rliebi** [pimcore/pimcore#15469]
### Pimcore version

10.6.3

### Steps to reproduce

Summary:
The return typehint in the getAdapter() method of PdfService in Pimcore 10.6.3 references a deprecated class Pimcore\Web2Print\Processor\HeadlessChrome and suggests it will be replaced by Processor\Chromium in Pimcore 11. However, in Pimcore 10.6.3, Processor\Chromium does not exist. This report requests clarification or an alternative solution for the return typehint to ensure compatibility and prevent issues during the transition to Pimcore 11.

Description:
In Pimcore 10.6.3, the getAdapter() method of PdfService specifies a return typehint of Pimcore\Web2Print\Processor\HeadlessChrome, which is marked as deprecated. The deprecation message suggests that in Pimcore 11, the class will be replaced by Processor\Chromium. However, in the current version (10.6.3), Processor\Chromium does not exist.

This discrepancy between the deprecation message and the actual availability of Processor\Chromium can lead to confusion and potential compatibility issues when migrating to Pimcore 11. It is recommended to either provide the missing Processor\Chromium class in the current version or update the deprecation message to reflect the correct replacement in Pimcore 11.

Steps to Reproduce:

Use Pimcore 10.6.3.
Examine the getAdapter() method in PdfService.
Note the return typehint referencing Pimcore\Web2Print\Processor\HeadlessChrome.
Observe the deprecation message suggesting the replacement class as Processor\Chromium.

### Expected / actual behavior

Expected Result:
The return typehint in the getAdapter() method should reference the correct replacement class that exists in the current version of Pimcore 10.6.3 or provide clear instructions on how to handle the deprecated class during the transition to Pimcore 11.

Actual Result:
The return typehint in the getAdapter() method references a deprecated class Pimcore\Web2Print\Processor\HeadlessChrome and suggests it will be replaced by Processor\Chromium. However, in Pimcore 10.6.3, Processor\Chromium does not exist, causing potential compatibility issues during the transition to Pimcore 11.

This is a similar issue to the one solved in #15468

**Comment by kingjia90** [comment]
just need to remove the `@` in the `@deprecated` phpdoc tag, right?
https://github.com/pimcore/pimcore/pull/14572/files?w=1#diff-17942b8841b66a708834009b355107475c5c02f51b0b0f3844a569d01b3620d4R30-R32
and maybe a link to this instructions
https://github.com/pimcore/pimcore/blob/11.x/doc/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md#additional-things-to-consider:~:text=%5BWeb2Print%5D%20Please%20keep%20in%20mind%20that%20the%20deprecated%20processor%20HeadlessChrome%20needs%20to%20be%20replaced%20with%20the%20new%20processor%20Chrome%20in%20Pimcore%2011.

**Comment by dvesh3** [comment]
Unfortunately, we can't work on this anymore as 10.6 reached EOL. thanks!
