### ISSUE TITLE
[Bug]: JsonHelperTrait is marked as internal despite being a deprecation resolution

### ISSUE THREAD

**Issue by rliebi** [pimcore/pimcore#15466]
### Pimcore version

10.6.3

### Steps to reproduce

1. Open the AdminController file in the project.
2. Check if the AdminController extends Pimcore\Bundle\AdminBundle\Controller\AdminController.
3. Observe the deprecation message for AdminController indicating that it will be removed in Pimcore 11.
4. Notice the deprecation message for the adminJson() method, which suggests using Pimcore\Controller\Traits\JsonHelperTrait::jsonResponse() instead.
5. Observe that Pimcore\Controller\Traits\JsonHelperTrait is marked as @internal.
6. Refer to the documentation provided at https://pimcore.com/docs/platform/Pimcore/Extending_Pimcore/Add_Your_Own_Permissions#inside-an-admincontroller for further details.

### Expected / actual behavior

Expected Behavior:
When migrating from Pimcore version 10.5.23 to 10.6.3, the deprecation message for the adminJson() method should be publicly accessible or clarified in the documentation, allowing developers to handle the deprecation correctly.

Actual Behavior:
The adminJson() method displays a deprecation message suggesting the usage of JsonHelperTrait::jsonResponse(). However, the JsonHelperTrait is marked as @internal, which indicates that it is not intended for external usage. This makes it challenging for developers to handle the deprecation correctly and find a suitable alternative. The documentation does not provide clear instructions on how to address this deprecation, further adding to the confusion.

Note: It is recommended to update the deprecation message or provide additional information in the documentation to clarify how to handle the deprecation of adminJson() when JsonHelperTrait is marked as @internal. This will help developers migrating to Pimcore 10.6.3 to address the deprecation properly without relying on internal traits.

**Comment by dvesh3** [comment]
Fixed by #15467
