### ISSUE TITLE
[Bug]: Add check for classification store groups

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#15473]
### Pimcore version

10.6

### Steps to reproduce

As getGroupConfigById() could return null, there should be an if check.

https://github.com/pimcore/pimcore/blob/11.x/models/DataObject/Classificationstore.php#L446

**Comment by blankse** [comment]
@valentin- I created a PR: https://github.com/pimcore/pimcore/pull/15607

**Comment by dvesh3** [comment]
Fixed by #15607
