### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rkhyd** [pimcore/pimcore#15489]
### Pimcore version

11.0.2

### Steps to reproduce

Goto demo website, Click DataObjects, Cars and select any car.
This error appears https://prnt.sc/rnUGr2Iyk059

### Expected / actual behavior

The cars information should be shown.

**Comment by blankse** [comment]
@rkhyd Is already fixed by https://github.com/pimcore/admin-ui-classic-bundle/issues/149
