### ISSUE TITLE
Object Data-Type: Dynamic Select

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1548]
- extending the existing select datatype
- available option key/values are dynamically provided by a data provider class (like calculated fields, ...) 
- allows to implement any dynamic values for a select data-type due it's data provider approach

**Comment by cleggypdc** [comment]
What about having a configurable option to allow new values to be created by users on the fly?

**Comment by weisswurstkanone** [comment]
build 60

**Comment by weisswurstkanone** [comment]
https://www.pimcore.org/docs/5.0.0/Objects/Object_Classes/Data_Types/Dynamic_Select_Types.html
