### ISSUE TITLE
[Bug]: Assets with invalid keys (originating from upgraded older Pimcore versions) don't get indexed by command 'pimcore:search-backend-reindex'

### ISSUE THREAD

**Issue by schmidt-travixmedia** [pimcore/pimcore#15495]
### Pimcore version

^10

### Steps to reproduce

We have upgraded a Pimcore project from 5.3.1 -> 5.8.9 -> 6.9.6 -> 10.6.3 as described in the upgrade notes, running all migrations.

In older Pimcore versions, "keys" (generated from file names) were allowed for assets, which are no longer allowed to be set in Pimcore >= X.

Example: If a file named `Info Haus+Hof+Garten.pdf` was previously uploaded to a `Flyer` folder, the following key was set:

`Info Haus+Hof+Garten.pdf`

Uploading the same file in Pimcore X, the following key is now set:

`Info Haus-Hof-Garten.pdf`

Although the key `Info Haus+Hof+Garten.pdf` is no longer valid, the asset can be opened and displayed in the Pimcore X backend without errors (which is good).

But if we now execute the command `bin/console pimcore:search-backend-reindex`, we get the following error for all assets with keys that are not valid in Pimcore X anymore:

`ERROR     [pimcore] Exception: invalid filename 'Info Haus+Hof+Garten.pdf' for asset with id [ 11111 ] in /var/www/html/vendor/pimcore/pimcore/models/Asset.php:632`

Code in `/var/www/html/vendor/pimcore/pimcore/models/Asset.php:632` (function correctPath(), executed inside save())

```
if (!Element\Service::isValidKey($this->getKey(), 'asset')) {
    throw new Exception("invalid filename '" . $this->getKey() . "' for asset with id [ " . $this->getId() . ' ]');
}
```

Code in `/var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/Command/SearchBackendReindexCommand.php`

```
try {
    //process page count, if not exists
    if ($element instanceof Asset\Document && !$element->getCustomSetting('document_page_count')) {
        $element->processPageCount();
        $this->saveAsset($element);
    }

    $searchEntry = Search\Backend\Data::getForElement($element);
    if ($searchEntry instanceof Search\Backend\Data && $searchEntry->getId() instanceof Search\Backend\Data\Id) {
        $searchEntry->setDataFromElement($element);
    } else {
        $searchEntry = new Search\Backend\Data($element);
    }

    $searchEntry->save();
} catch (\Exception $e) {
    Logger::err((string) $e);
}
```

`$this->saveAsset($element);` results in an exception because of the invalid key, so the asset is not indexed, because we jump into catch block and therefore skip the indexing part.

Since we have thousands of assets with keys that are no longer valid in Pimcore X, these assets are all NOT indexed. This results in our customer not being able to find files that they used to be able to find easily via search in previous Pimcore version.

3 possible solutions I see:

1. Core migrations could update keys of assets so that they are valid in Pimcore X (-> this could of course lead to errors in custom PHP code if certain assets are addressed by their key in it).
2. Pimcore X delivers an additional command to convert invalid keys of assets into valid keys (thus, in contrast to the 1st solution, developers could decide themselves whether to make the keys of assets valid. The developer has to be aware that he has to check his custom PHP code if assets are refenced by key in it). This command could also control by parameter how to handle keys that are "locked" in the Assets tree.
3. The command "bin/console pimcore:search-backend-reindex" should somehow also accept non-valid asset keys, so that these assets are also indexed.

### Expected / actual behavior

Assets with invalid keys must be respected by command `pimcore:search-backend-reindex`

**Comment by brusch** [comment]
To be honest, I'd not implement a migration, but offer an additional command as a Gist that you can optionally use and we can reference this in our docs.  
PRs welcome 😊
