### ISSUE TITLE
[Bug]: Pimcore ignores the constant PIMCORE_CONFIGURATION_DIRECTORY

### ISSUE THREAD

**Issue by hethehe** [pimcore/pimcore#15534]
### Pimcore version

10.6.x

### Steps to reproduce

set the `PIMCORE_WRITE_TARGET_IMAGE_THUMBNAILS` to `symfony-config`

create a constant `PIMCORE_CONFIGURATION_DIRECTORY` in config/pimcore/constants.php and set it to `__DIR__ . "/system"` for example.

create a new thumbnail or static route.

### Expected / actual behavior

Expected: the configuration is saved to config/pimcore/system/image_thumbnails/

Actual: Pimcore ignores the constant and save the thumbnail config to var/config/image_thumbnails

**Comment by brusch** [comment]
True, probably we need to include `PIMCORE_CONFIGURATION_DIRECTORY` here: 
https://github.com/pimcore/pimcore/blob/1bb27c2812cf7154c7adc3da90f35f53752cea06/bundles/CoreBundle/src/DependencyInjection/Configuration.php#L133

and remove `%kernel.project_dir%` prefix here: https://github.com/pimcore/pimcore/blob/f3f3fc0c0cfc39f41493428a19477acbf800ea02/bundles/CoreBundle/src/DependencyInjection/ConfigurationHelper.php#L58

Additionally we should do proper code formatting there 😉

**Comment by dvesh3** [comment]
Fixed by #15735
