### ISSUE TITLE
[Pimcore 4] Allow object grid configuration save and delete based on list permission instead publish

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1555]
Pimcore user can only save grid column configuration if they have the "publish" permission.
It should be based on the "list" permission instead, it make more sense.

![column-grid](https://cloud.githubusercontent.com/assets/9025839/26597481/70f4dc40-4572-11e7-9f73-e6949a811f04.png)

Use case:
We want to give user the possibility to list/view some object. But they cannot save a personnalized grid list which make hard to them to list/view datas as each time they need to configure the column configuration. Giving them the possibility to save the column configuration will be a lot more convenient for them to work on Pimcore.

Patch => replace "publish" by "list" here:
https://github.com/pimcore/pimcore/blob/pimcore4/pimcore/modules/admin/controllers/ObjectHelperController.php#L294
https://github.com/pimcore/pimcore/blob/pimcore4/pimcore/modules/admin/controllers/ObjectHelperController.php#L329

Thanks.

**Comment by Yivan** [comment]
I saw issue https://github.com/pimcore/pimcore/issues/1614 was resolved, thanks a lot.

Maybe this one could be processed, so grid configuration will be all fine in next update ?

**If it was in pending because it can break BC, maybe we can authorise publish & list, so it won't remove the feature to enduser having "publish" right, and it will add the feature to those having "list" right.**

Thanks.

**Comment by weisswurstkanone** [comment]
build 4088
