### ISSUE TITLE
[Bug]: WYSIWYG Drag & drop asset images not saved.

### ISSUE THREAD

**Issue by fracsi** [pimcore/pimcore#15582]
### Pimcore version

11.0.4

### Steps to reproduce

1. In Document or DataObject with a WYSIWYG field, add an Asset image by drag and drop to thea field.
2. Save and publish.
3. Reload the document or open the document / dataobject in the browser

### Actual Behavior

Drag & dropped image is saved and visible as intended

### Expected Behavior

The image is not displayed. The `<img>` tag is missing from the HTML.

**Comment by dvesh3** [comment]
already fixed by https://github.com/pimcore/pimcore/pull/15584? please check on https://demo.pimcore.fun/admin

**Comment by fracsi** [comment]
@dvesh3 Yes. That was my PR for this issue.
