### ISSUE TITLE
[Bug]: Unknown column 'object_metadata_[ID_OF_CLASS].o_id' in 'where clause'

### ISSUE THREAD

**Issue by mhgtlc** [pimcore/pimcore#15589]
### Pimcore version

11.0.4

### Steps to reproduce

It happens when retrieving relations of an object.
<img width="1025" alt="Screenshot 2023-07-21 at 13 33 06" src="https://github.com/pimcore/pimcore/assets/6807023/2d56a6dd-6eac-4ebc-ba22-fceb1bbe36ce">

I think it is related to: https://github.com/pimcore/pimcore/pull/15543

Noticed that a new column o_id has has to be there, but even if i saved a class, that column has not been created

### Actual Behavior

Error when access relations of an object 
```
Message: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_metadata_1.o_id' in 'where clause'
Trace: 
in /var/www/html/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:67
#0 /var/www/html/vendor/doctrine/dbal/src/Connection.php(1935)
#1 /var/www/html/vendor/doctrine/dbal/src/Connection.php(1878)
#2 /var/www/html/vendor/doctrine/dbal/src/Connection.php(1103)
#3 /var/www/html/vendor/doctrine/dbal/src/Connection.php(899)
#4 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Data/ElementMetadata/Dao.php(74):
#5 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Data/ElementMetadata.php(107)
#6 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php(173)
#7 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php(186): Pimcore\Model\DataObject\ClassDefinition\Data\AdvancedManyToManyRelation->loadData(Array,...
```

### Expected Behavior

Relations are retrieved without errors

**Comment by dvesh3** [comment]
https://github.com/pimcore/pimcore/pull/15587 fixes it

**Comment by dvesh3** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15592
