### ISSUE TITLE
[Bug]: Admin panel does not work for skeleton and demo

### ISSUE THREAD

**Issue by betterapp** [pimcore/pimcore#15597]
### Pimcore version

11

### Steps to reproduce

1. Install PimCore 11 with composer on local machine on pimcore11.pim domain
2. run /vendor/bin/pimcore-install
3. everything is ok
4. go to http://pimcore11.pim/ -> I see PimCore logo
5. go to http://pimcore11.pim/admin and I see

Not Found
The requested URL was not found on this server.

As I see there is no any .htaccess file in /public directory. Is it ok ?

### Actual Behavior

Not Found
The requested URL was not found on this server.

### Expected Behavior

loading admin panel

**Comment by brusch** [comment]
Seems to be related to #15471 🤔

**Comment by fashxp** [comment]
just tried another empty demo package installation and it worked like a charm.

are you using apache?

**Comment by fashxp** [comment]
if you using apache, please consider following docs: https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/System_Setup_and_Hosting/Apache_Configuration
