### ISSUE TITLE
[Bug]: WYSIWYG editor not saving any content

### ISSUE THREAD

**Issue by alexej-d** [pimcore/pimcore#15604]
### Pimcore version

10.6.5

### Steps to reproduce

Create a snippet and use a WYSIWYG editable. Input some text and save.

### Actual Behavior

After inputing content into the editable and saving, it seems that everything worked, but the content is newer written to the DB. There is an error on the console:

`TypeError: Cannot read properties of undefined (reading 'up')`

The error is produced in this file bundles/AdminBundle/Resources/public/js/pimcore/document/editables/wysiwyg.js on line 110. This is the pull request, that produced the issue I assume: #15024 

Changing the code on line 110 to this fixes it: `let panelComponent = this.component?.up('panel');`

### Expected Behavior

The text should persist to the DB.

**Comment by cadeyrn** [comment]
Confirmed. Line 124 has to be changed as well:

`panelComponent = panelComponent?.up('panel');`

**Comment by kingjia90** [comment]
Thank you @alexej-d  and @cadeyrn for reporting and suggesting the fix!
