### ISSUE TITLE
[Bug]: Migrating pimcore v 6.9.6 to pimcore 10.6.3 v, facing issue

### ISSUE THREAD

**Issue by Thejaswini-Rao-U** [pimcore/pimcore#15600]
### Pimcore version

Pimcore migrating to 10.6.3 v

### Steps to reproduce

Hi 

Im updating pimcore v 6.9.6 to 10.6.3v , 

Initially did all the changes to the folder structures manually and executed this command COMPOSER_MEMORY_LIMIT=-1 composer update

### Actual Behavior

while migrating im getting below error which is attached
im using php 8.1 v and mysql 8.0v
composer version is 2.5v

**[error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20210107103923 failed during Execution. Error: "Please provide select options as associative array with fields "key" and "value""

In Select.php line 206:**
  Please provide select options as associative array with fields "key" and "value"**                                         

![10_key ValueSelectError](https://github.com/pimcore/pimcore/assets/78895325/f8615cb7-aeb2-4828-ba42-b25cf5f935f7)

Please help me to solve this issue
Thanks in advance

### Expected Behavior

Successfully it should migrate

**Comment by NiklasBr** [comment]
It looks like perhaps one of your data oject classes has a select/multiselect field whose values are not in the expected format.

Check the `pimcore/var/classes/definition_Classwitherror.php` it should have some `options` looking something like this 

```php
'options' => 
    array (
        0 => 
                  array (
                    'key' => 'Closing down',
                    'value' => 'closing',
                  ),
        1 => 
                  array (
                    'key' => 'Opening',
                    'value' => 'opening',
                  ),
```

**Comment by Thejaswini-Rao-U** [comment]
@NiklasBr , Thanks for the quick resonse.

i have checked all the classes options provider , all have similar expected type of array. 


array:81 [
  0 => array:2 [
    "key" => "NAVY LIGHT BLUE"
    "value" => "NLB"
  ]
  1 => array:2 [
    "key" => "OLIVE"
    "value" => "OL"
]
]

But Im not sure why this error still exists?

**Comment by NiklasBr** [comment]
Are you able to add a debugger breakpoint where the error happens? 

https://github.com/pimcore/pimcore/blob/947054028b6fbfe58b4ced996f88fc7614ab5cb4/models/DataObject/ClassDefinition/Data/Select.php#L116-L133

Looks like maybe `WebsiteCategory` or an optionsprovider is the culprit.

**Comment by Thejaswini-Rao-U** [comment]
@NiklasBr , Even if i remove all the class option provider and classes definition, still i get the issue.

is it due to PHP deprecation error? earlier version we have used 7.2 and now switched to 8.1 when migrating



![12 RemovedClassDefinitionSelectError](https://github.com/pimcore/pimcore/assets/78895325/6ed4b8d1-f71d-4fc2-b194-354f3d63c2b0)

**Comment by NiklasBr** [comment]
I can't see any reason why the PHP version would have an effect. Are you able to provide the class definition which fails here?
