### ISSUE TITLE
[Bug]: Ceil():Argument #1 ($num) must be of type int|float, null given  when uploading video

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#15611]
### Discussed in https://github.com/pimcore/pimcore/discussions/15601

<div type='discussions-op-text'>

<sup>Originally posted by **YaseeraCentric** July 24, 2023</sup>
ceil():Argument #1 ($num) must be of type int|float, null given  when uploading video using pimcore Video editable in pimcore version 11</div>

**Comment by kingjia90** [comment]
confirming potential error
https://github.com/pimcore/pimcore/blob/389ec16318e6140fb0aac8443466998df4a7e65d/models/Document/Editable/Video.php#L930

https://github.com/pimcore/pimcore/blob/389ec16318e6140fb0aac8443466998df4a7e65d/models/Asset/Video.php#L224-L226

**Comment by YaseeraCentric** [comment]
is this fixed now?

**Comment by kingjia90** [comment]
Not yet, it will be likely released on 3rd August

**Comment by blankse** [comment]
@YaseeraCentric @kingjia90 I created a PR https://github.com/pimcore/pimcore/pull/15621
