### ISSUE TITLE
[Bug]: Invoking __toString for QuantityValue in ClassificationStore throws TypeError

### ISSUE THREAD

**Issue by woellundwoell** [pimcore/pimcore#15618]
### Pimcore version

11.x

### Steps to reproduce

* add a ClassificationStore with QuantityValue to  a classDefinition
* set some value
* invoke __toString, e.g `var_dump((string)TestClass::getById(ID)->getTestRange()->getLocalizedKeyValue(GROUP_ID,KEY_ID));`

### Actual Behavior

throws typeError: NumberFormatter::format(): Argument #1 ($num) must be of type int|float, string given

### Expected Behavior

should return the numerical value (and the UnitAbbreviation, if set) as a string, e.g. "10 mm"

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15762
