### ISSUE TITLE
[Bug]: Invalid Custom Reports configuration on config_location symfony-config

### ISSUE THREAD

**Issue by sebiacus** [pimcore/pimcore#15626]
### Pimcore version

11.0.4

### Steps to reproduce

1) Enable + Install PimcoreCustomReportsBundle
2) Set config_location for custom reports to symfony-config
3) Create a new custom report within the admin interface.

### Actual Behavior

Pimcore creates a new yaml-config in var/config/custom_reports:
```
pimcore:
    custom_report:
        definitions:
```
This configuration tree is invalid as the Custom Reports Bundle got its own configuration tree "pimcore_custom_reports".
![image](https://github.com/pimcore/pimcore/assets/19584235/160cb5ff-3307-4a19-954d-f5f81e2c1a36)

If you switch to config_location=settings-store it works fine

### Expected Behavior

Config should be created under tree "pimcore_custom_reports".

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15670
