### ISSUE TITLE
[Bug]: Change in type system cause serialized data objects to throw type error when updating to Pimcore 11

### ISSUE THREAD

**Issue by aashan10** [pimcore/pimcore#15629]
### Pimcore version

11.0.3

### Steps to reproduce

I have a pimcore 10.6 instance that I am trying to update to pimcore 11.
It has a data object with a `website` field which is a link, which is not a mandatory field.

![Screenshot 2023-07-26 at 15 30 04](https://github.com/pimcore/pimcore/assets/18713900/52448794-23e1-494e-98d7-f56cb2efc16f)

Now, up until pimcore 10.6, the types were nullable as in 
https://github.com/pimcore/pimcore/blob/89d0af7753f242378c22aab19ec00f678be3d780/models/DataObject/Data/Link.php#L35-L102

So the actual value for this field was stored serialized in database in a format 

```
O:34:"Pimcore\Model\DataObject\Data\Link":17:{s:7:"�*�text";s:0:"";s:15:"�*�internalType";N;s:11:"�*�internal";N;s:9:"�*�direct";s:24:"https://some-domain.com/";s:11:"�*�linktype";s:6:"direct";s:9:"�*�target";N;s:13:"�*�parameters";s:0:"";s:9:"�*�anchor";s:0:"";s:8:"�*�title";s:0:"";s:12:"�*�accesskey";s:0:"";s:6:"�*�rel";s:0:"";s:11:"�*�tabindex";s:0:"";s:8:"�*�class";s:0:"";s:13:"�*�attributes";s:0:"";s:9:"�*�_owner";N;s:13:"�*�_fieldname";s:0:"";s:12:"�*�_language";N;}
```

But as the `string` type hints were added in Pimcore 11, now the objects can't be unserialized and throw type error.

### Actual Behavior

The data objects stored in the database prior to pimcore 11 should be unserialized 

### Expected Behavior

An exception is thrown when trying to unserialize the objects

![Screenshot 2023-07-26 at 15 40 12](https://github.com/pimcore/pimcore/assets/18713900/58a79b3f-c6bc-4fe5-a6bd-5ef38393a101)

**Comment by blankse** [comment]
@aashan10 I created already a PR for this: https://github.com/pimcore/pimcore/pull/15577

**Comment by aashan10** [comment]
@blankse sorry I didn't realize 🥇
