### ISSUE TITLE
[Bug]:  Warning Array to string conversion with Range Numeric

### ISSUE THREAD

**Issue by zekuraz** [pimcore/pimcore#15643]
### Pimcore version

11.0.5

### Steps to reproduce

1. Had a classification store, like Etim
2. Had a feature with Numeric Range Data types
3. Had a objets who the class has a store classification
4. Try to save and publish with the values entered in the feature, such as a temperature minimum and maximum

![Capture d’écran du 2023-07-27 15-02-39](https://github.com/pimcore/pimcore/assets/18125616/3b9b40e7-3611-4325-93b1-a54153bdff7c)

### Actual Behavior

When I try to save and publish, if data is entered in numeric range, I get an error message. In addition, the list does not include Numeric Range and Quantity Value Range

![2023-07-27_15-15](https://github.com/pimcore/pimcore/assets/18125616/d4a3e6d9-171f-41ee-be7c-20f60045b123)

### Expected Behavior

To be able to select them Numeric Range and Quantity Value Range

**Comment by aryaantony92** [comment]
@zekuraz Thanks for reporting the issue. But, I am unable to reproduce the error. Could you please try with the latest version (11.0.8) ?

**Comment by aryaantony92** [comment]
@zekuraz The reason is that, numeric range data type is not supported in classification store.

**Comment by zekuraz** [comment]
@aryaantony92 can we see it coming in new feature ?

**Comment by dvesh3** [comment]
@zekuraz this is not planned on our side. We would be happy to receive a PR 😊
