### ISSUE TITLE
[Bug]:  Pimcore\Model\Dependency::addRequirement(): Argument #1 ($id) must be of type int, string given

### ISSUE THREAD

**Issue by svdv22** [pimcore/pimcore#15652]
### Pimcore version

10, 11

### Steps to reproduce

Honestly not sure; I've updated my project from Pimcore 6 to 11 and when saving some pages I get this error (see title). Possible this happens as soon as there's a wysiwyg (with related content) on the page.

### Actual Behavior

I get an error when trying to save the page; `Pimcore\Model\Dependency::addRequirement(): Argument #1 ($id) must be of type int, string given, called in vendor/pimcore/pimcore/models/Document.php on line 526`

### Expected Behavior

I expect the page to save (and publish) without issues

**Comment by svdv22** [comment]
I found the issue to be in the `getElementsInWysiwyg` method in `Pimcore\Tool\Text`. The `preg_match` method returns an array with string values. On line 217 the `$id` is defined: `$id = $idMatches[0];`. This value bubbles up to the `addRequirment` method call that expects an int instead of a string.

**Comment by kingjia90** [comment]
Fixed by #15653

Thank you for the report & fix!
