### ISSUE TITLE
[Bug]: Error OpenStreetMap Cors Headers

### ISSUE THREAD

**Issue by MG-Arnaud** [pimcore/pimcore#15661]
### Pimcore version

ALL version

### Steps to reproduce

- Go to the https://demo.pimcore.fun/admin/ and login **admin / demo**
- Open a car object (ex : /Product Data/Cars/ac cars/Cobra 427)
- Set a location in the **Sale Information** tab
- An error occured each time you open the object

![image](https://github.com/pimcore/pimcore/assets/18262300/d8ca79ab-79aa-4610-b8cc-f02e52f892ec)
![image](https://github.com/pimcore/pimcore/assets/18262300/abcd6c25-e3df-4da3-99f9-95d62f4ae547)

### Actual Behavior

Hello,

I would like to report you a cross headers error when you have a GeoCoordinate field.
Indeed the URL  : https://nominatim.openstreetmap.org/reverse?format=json&lat=47.040182144807&lon=2.8125&addressdetails=1 is blocking when Pimcore try to get the location from the Latitude and longitude.
If we analyzed the console we can see that : 
`Access to XMLHttpRequest at 'https://nominatim.openstreetmap.org/reverse?format=json&lat=47.040182144806664&lon=2.8125&addressdetails=1&_dc=1690875423920' from origin 'https://demo.pimcore.fun' has been blocked by CORS policy: Request header field x-pimcore-extjs-version-major is not allowed by Access-Control-Allow-Headers in preflight response.`

So it's maybe OpenStreepMap with their policy (https://operations.osmfoundation.org/policies/nominatim/) that blocked Pimcore headers. 

Can you investigate ?

May be if you don't send the extra headers (X-Pimcore-Csrf-Token, X-Pimcore-Extjs-Version-Major, X-Pimcore-Extjs-Version-Minor) it will be working ?

Thanks

### Expected Behavior

- Open an object with a location set and don't have the Popup error ! 
- Set a location and don't have the error.

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15689
