### ISSUE TITLE
[Bug]: Document version can not be opened after Pimcore 11 update

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#15662]
### Pimcore version

v11.0.5

### Steps to reproduce

Create a Pimcore 10.6 document with a version. Update to pimcore 11. Try to preview the version of the document created in Pimcore 10.6.

### Actual Behavior

Error "Cannot assign null to property Pimcore\Model\Document\Editable\Areablock::$currentIndex of type array" thrown
![Cannot assign null to property version error](https://github.com/pimcore/pimcore/assets/2771909/011b29a5-b979-4eb7-a407-a63cbeedfa2e)

### Expected Behavior

Display the document in the proper version

**Comment by kingjia90** [comment]
Looks similar to https://github.com/pimcore/pimcore/pull/15577, unserializer and native type changes of 11, but in a different place

**Comment by blankse** [comment]
@Cruiser13 @kingjia90 I created a PR https://github.com/pimcore/pimcore/pull/15702

**Comment by Cruiser13** [comment]
Thanks to your PR I found another issue here and did also submit a PR.

**Comment by dvesh3** [comment]
Fixed by #15702 & #15713
