### ISSUE TITLE
[Improvement]: Rebuilding brick and classes should not change order of getters

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#15687]
### Improvement description

When updating Pimcore or otherwise running a class/brick rebuild command the result should not be in a random order. Every time a class is rebuilt the methods in the definition file should always be in the same order.

Take for example these Bricks in the screen shot below which were recently rebuilt, nothing actually changed, but on most Pimcore updates they will switch order back and forth adding noise and uncertainty in the update process because it makes it much harder to track *actual* changes.

![image](https://github.com/pimcore/pimcore/assets/279826/77ce556d-2bb1-406e-aa7c-448ddf871a60)

**Comment by dpfaffenbauer** [comment]
We never have these files in our Source code repository, they are generated when needed.

**Comment by NiklasBr** [comment]
That would be even better, we have tried that on multiple projects but Jenkins cannot deploy to AWS without them being committed.

**Comment by dpfaffenbauer** [comment]
Create them when you need them with `bin/console pimcore:build:classes`. It doesn't need a DB Connection (for most of the field-types). We use that do build our docker images with classes pre-build.

**Comment by NiklasBr** [comment]
Wish we could do that with Jenkins...
