### ISSUE TITLE
[Bug]: Workflow saving race condition

### ISSUE THREAD

**Issue by evanjamesjackson** [pimcore/pimcore#15715]
### Pimcore version

10.6

### Steps to reproduce

1. Set up a simple Data Object class
2. Set up a simple workflow for the Data Object, with two "places" and a single transition
3. Save the workflow configuration
4. Create a new object, enter some data, then use the workflow to transition it

### Actual Behavior

The entered data is not maintained in the new place. However, a version will have been created with the data, and the workflow will appear to have created a new version of the object that doesn't maintain the data (which to me looks like a race condition).

Here is a screen recording:

![Animation](https://github.com/pimcore/pimcore/assets/5866481/11404ce9-21e7-4a0b-84a0-5df878ab9682)

I have tried setting the "Change Published State" to "Save Version", but the same issue occurs.

### Expected Behavior

The data should be maintained across versions

**Comment by kingjia90** [comment]
It seems that the described cause has to do with autosave functionalities (`objects: auto_save_interval`).
When turning that off, it would trigger a "All unsaved changes will be lost, are you really sure?" after the workflow action is successful 🤔 

It seem also it was and always worked with latest saved version but didn't trigger a save itself on the draft
https://github.com/pimcore/pimcore/blob/b448b008b018bad6fbc31ecec1dfd3c64ad50a87/bundles/AdminBundle/Controller/Admin/WorkflowController.php#L446-L455

**Comment by dvesh3** [comment]
please use `unsavedChangesBehaviour` option to perform desired action on workflow action. please see https://github.com/pimcore/pimcore/pull/13018

**Comment by dvesh3** [comment]
Documented here https://github.com/pimcore/pimcore/blob/0194ba7c8946f701242f637c8d5d935c6225417f/doc/07_Workflow_Management/01_Configuration_Details/README.md#L271

**Comment by kingjia90** [comment]
Closing as it was improved by https://github.com/pimcore/pimcore/pull/13018 but is only valid from Pimcore 11.

It looks like workflow actions shouldn't implicitly save https://github.com/pimcore/pimcore/issues/7660#issuecomment-755936535 and were not intended to be use that way and guess any [potential fix](https://github.com/pimcore/pimcore/pull/15745) would cause a behaviour change and that's the reason that it was introduced only in 11.
