### ISSUE TITLE
[Events] [Deprecation] ResolveUploadTargetEvent to move context info to arguments

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#15716]
### Improvement description

As `ResolveUploadTargetEvent` is already using [`ArgumentsAwareTrait`](https://github.com/pimcore/pimcore/blob/a732bf41f55e8116e48672d577882f936d11d01e/lib/Event/Model/Asset/ResolveUploadTargetEvent.php#L23), the context info can be moved to the arguments. 

Also,´property should be deprecated before removal.

**Comment by jdreesen** [comment]
Is this related to #14363?

**Comment by aryaantony92** [comment]
> Is this related to #14363?

Yes

**Comment by martineiber** [comment]
Context will be removed here: https://github.com/pimcore/pimcore/issues/17766
