### ISSUE TITLE
[Bug]: Element/Service::getSafeCopyName doesn't provide a correct filename for assets on copy

### ISSUE THREAD

**Issue by nkirich** [pimcore/pimcore#15747]
### Pimcore version

11.0.6

### Steps to reproduce

The issue comes from this line https://github.com/pimcore/pimcore/blob/37a28f780a669bbf1058d9bda7c96ea3e20c1d6c/models/Element/Service.php#L367C17-L367C17
Here for assets it's not checked whether the filename has _copy prefix in it and just adds another one at the end.

To reproduce:
Copy the same asset multiple times inside the same folder.

### Actual Behavior

the filename is always updated with a _copy prefix (**filename**_copy_copy_copy) resulting in an endless filename length increase
<img width="769" alt="image" src="https://github.com/pimcore/pimcore/assets/117178102/8aca5aab-c1b3-4172-8335-fadb9e547507">

### Expected Behavior

the filename is updated correctly with an integer increment in the name (**filename**_copy_3)

**Comment by dvesh3** [comment]
Fixed by #15851
