### ISSUE TITLE
[Bug]: Wrong return type in Pimcore\Model\DataObject\ClassDefinition\Data\RgbaColor::getDataForEditmode()

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#15756]
### Pimcore version

11

### Steps to reproduce

create class with RgbaColor in localized fields

### Actual Behavior

Error when handling search backend message: 

Handling "Pimcore\Bundle\SimpleBackendSearchBundle\Message\SearchBackendMessage" failed: Pimcore\Model\DataObject\ClassDefinition\Data\RgbaColor::getDataForEditmode(): Argument #2 ($object) must be of type ?Pimcore\Model\DataObject\Concrete, Pimcore\Model\DataObject\Localizedfield given, called in /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/RgbaColor.php on line 276

### Expected Behavior

no error

**Comment by blankse** [comment]
@fashxp I created a PR https://github.com/pimcore/pimcore/pull/15763

**Comment by dvesh3** [comment]
Fixed by #15763
