### ISSUE TITLE
[Bug]: Adding a new classification field to an object deletes any existing fields after saving

### ISSUE THREAD

**Issue by ayoob-lfc** [pimcore/pimcore#15751]
### Pimcore version

11.0.6

### Steps to reproduce

1: Go to the Pimcore demo and open any AccessoryPart:

https://demo.pimcore.fun/admin/login/deeplink?object_408_object

2: Add a new field "group" to the "Structured Data -> Technical Attributes" classification field.

3: Save and Reload

### Actual Behavior

Previous Fields are deleted

### Expected Behavior

Both previous and new fields should be saved.

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15757
