### ISSUE TITLE
[Bug]: Editing the Classification values in grid view throws an error

### ISSUE THREAD

**Issue by ayoob-lfc** [pimcore/pimcore#15758]
### Pimcore version

11.0.6

### Steps to reproduce

1: Log in to https://demo.pimcore.fun/admin/

2: Open the "Accessories" folder:

https://demo.pimcore.fun/admin/login/deeplink?object_361_folder

3: Add the "Technical Specification" Classification field:

![image](https://github.com/pimcore/pimcore/assets/46787382/8303b162-4d1d-4e17-8f64-ff6bfc73d0f4)

4: Apply

### Actual Behavior

Throws the following error:

```
Timestamp: Wed Aug 16 2023 18:14:04 GMT+0100 (British Summer Time)
Status: 500 | Internal Server Error
URL: /admin/object/grid-proxy?classId=AP&folderId=361&xaction=read&_dc=1692206044296
Method: POST
Message: Pimcore\Model\DataObject\Service::getStoreValueForObject(): Return value must be of type ?string, array returned
```

### Expected Behavior

Should be able to view and edit the field in Grid View

**Comment by dvesh3** [comment]
Fixed by #15773
