### ISSUE TITLE
Support Lazy Loading in Relation Data-Types inside Localized Fields and Field-Collections

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1577]

**Comment by weisswurstkanone** [comment]
obsolete

**Comment by svenanderzen** [comment]
Hi, quick question; was this implemented somewhere else in another issue/PR or what's the reason for this getting closed as "obsolete"? Is there some other way to have localized relations between Pimcore objects that's considered better? :)

**Comment by weisswurstkanone** [comment]
as far as I remember this one os closed in favour of https://github.com/pimcore/pimcore/issues/1623
