### ISSUE TITLE
[Improvement]: FOSJsRoutingBundle route disclosure & jsonp callback security implications

### ISSUE THREAD

**Issue by damianglx** [pimcore/pimcore#15789]
### Improvement description

After running a security audit on a pimcore page the following minor issues were reported: 

- **Symfony FOSJsRoutingBundle Exposure**: 
pimcore.system/js/routing?callback=fos.Router.SetData shows all existing routes, and could in theory expose sensitive endpoints
Is it possible to reduce the list to only needed endpoints, to reduce theoretical attack surfaces? 

- **JSONP Callback Injection**:
The callback could in theroy be used to extract data or conduct various other attacks. As only the callback name "fos.Router.SetData" is used by pimcore, it would be nice if there was a whitelist for the allowed callback names.

**Comment by NiklasBr** [comment]
Seems like a false positive similar to this discussion https://github.com/pimcore/pimcore/discussions/15400

If you have sensitive endpoints you should use authentication to prevent unauthorised access.
