### ISSUE TITLE
Pimcore does apply endless scrolling to views with 100% height

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#1581]
# Bug Report
### Expected behavior 
Edit sites with 100% height elements (e.g. using Bootstrap 4) without issues in the pimcore backend
### Actual behavior  
Pimcore does apply endless scrolling to sites in editmode in backend which does make it impossible to edit the sites.
### Steps to reproduce  
Setup a view like this and access it in editmode
### Code example 
```php
<html>
<head>
    <style>
        html,
        body,
        .view {
            height: 100%;
        }
        .view {
            cursor: default;
            overflow: hidden;
            position: relative;
        }
    </style>
</head>
<body>
<div class="view">
    Test
</div>
<div>
    <?= $this->areablock('firstarea') ?>
</div>
</body>
</html>

```

Tested in latest Firefox on Windows 10.

**Comment by brusch** [comment]
It seems that the DnD component in ExtJS 6 doesn't rely on the body's height anymore, so this functionality is obsolete.

**Comment by Cruiser13** [comment]
@brusch will this also be applied to the Pimcore 4 series?

**Comment by brusch** [comment]
sure, see commit above (Backport ...) which was made to the pimcore4 branch ;) 46b1a85bcc620e5d53a4fa17d785b7b76c9ef34a

**Comment by Cruiser13** [comment]
Thanks!
