### ISSUE TITLE
[Bug]: object can't be created if class contains integer number field with default value and decimal precision or decimal size

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#15813]
### Pimcore version

11.0.7

### Steps to reproduce

1. Create a class with a number field
2. The numer field should have the following properties: default vaue = 1, Decimal precision = 0 (or a decimal size), integer = true
3. Create a object of this class

### Actual Behavior

Message: Pimcore\Model\DataObject\SampleObject::setTestfield(): Argument #1 ($testfield) must be of type ?int, string given, called in /var/www/html/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php on line 973

### Expected Behavior

Successful object creation.

**Comment by dvesh3** [comment]
Might be related to https://github.com/pimcore/pimcore/pull/15640/

**Comment by aryaantony92** [comment]
Will be fixed by https://github.com/pimcore/pimcore/pull/15640

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15640
