### ISSUE TITLE
[Bug]: Adding multiple advanced many to many object relation in field collection while creating an object gives "Pimcore\Model\DataObject\Data\ObjectMetadata::save(): Argument #4 ($position) must be of type string, int given" this error

### ISSUE THREAD

**Issue by prateeksahus** [pimcore/pimcore#15821]
### Pimcore version

11.0.4,11.0.0,11.0.7

### Steps to reproduce

1. Inside a field collection create an advanced many to many object relation with metadata.
2. Now create an object with this fieldcollection and add more than one same fieldcollection instance to it.
3. Try saving and publishing the object, will get the error
![Screenshot from 2023-08-24 20-01-53](https://github.com/pimcore/pimcore/assets/72745617/75863271-428c-45da-b9d7-3570d97d83aa)

### Actual Behavior

Getting the error
![Screenshot from 2023-08-24 20-01-53](https://github.com/pimcore/pimcore/assets/72745617/cd32921a-bc5f-4216-824e-6f8bda9eab56)

### Expected Behavior

The object should get save and published without this error

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15853
