### ISSUE TITLE
[Bug]: relations records are not removed when the relation attribute is removed from the class

### ISSUE THREAD

**Issue by dev-pim** [pimcore/pimcore#15833]
### Pimcore version

10.x, 11.x

### Steps to reproduce

1. add a relations attribute to the class (eg many to many object relations), let it be called "relatedProducts"
2. add objects to "relatedProducts" attribute
3. remove the "relatedProducts" attribute from the class
4. records from the object_relations_ table with fieldname = "relatedProducts" will not be deleted automatically

### Actual Behavior

relations records are not removed by fieldname when the relation attribute is removed from the class

### Expected Behavior

records from the object_relations table should be deleted automatically by fieldname when the relation attribute is removed from the class

**Comment by dev-pim** [comment]
to solve this problem, you need to swap the variables $datastoreColumnsToRemove -> $columnsToRemove, $protectedDatastoreColumns -> $protectedColumns

in the following block of code:
https://github.com/pimcore/pimcore/blob/11.x/models/DataObject/ClassDefinition/Dao.php#L202C34-L202C34
![image](https://github.com/pimcore/pimcore/assets/66632919/587eea79-324a-499e-a113-be57c3ee2c4b)

because $datastoreColumnsToRemove does not contain a relations attribute column, because this is the object_store table

ps I'm too lazy to create a pull request, but this will fix the broken functionality

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15845
