### ISSUE TITLE
[Bug]: Old versions of objects prior 10 -> 11 cant be loaded anymore

### ISSUE THREAD

**Issue by frithjof** [pimcore/pimcore#15839]
### Pimcore version

10 -> 11

### Steps to reproduce

save version in 10.x -> migrate to 11.x and try to load the version

### Actual Behavior

version cant be loaded because it does not have id field ( only o_id )

### Expected Behavior

load the old version

**Comment by frithjof** [comment]
i would make a pull request but i am unsure what is better:
* convert all of them via migration and regex
* convert them on the fly in models/Element/AbstractElement.php 670
  `  if($this->getId() === null){
                $id = $this->o_id;
                $originalElement = static::getById($id);
            }
            else{
                $originalElement = static::getById($this->getId());
            }

`
but this also needs 
` /**
     * @internal
     * this is only used to convert old objects with o_id ( from serialized data ) on the fly
     */
    protected ?int $o_id = null;`

so we will carry along the $o_id in all elements

**Comment by dvesh3** [comment]
As per [upgrade notes](https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/Upgrade_Notes/#data-objects), you need to migrate your data to not have `o_` prefixes anymore. This should be added to preparation guide https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/Updating_Pimcore/Preparing_for_V11

**Comment by dvesh3** [comment]
@frithjof could you please try these [scripts](https://gist.github.com/dvesh3/96e68c1fe0e9d03996e09857105813c3) to migrate o_ prefixes on v11 serialized data? thanks!

**Comment by frithjof** [comment]
@dvesh3 works fine for simple objects but if you have a version containing an object brick it is still broken

`php.CRITICAL: Uncaught Error: Cannot assign null to property Pimcore\Model\DataObject\Objectbrick\Data\AbstractData::$doDelete of type bool {"exception":"[object] (TypeError(code: 0): Cannot assign null to property Pimcore\\Model\\DataObject\\Objectbrick\\Data\\AbstractData::$doDelete of type bool at ...`

**Comment by frithjof** [comment]
i have fixed mine with loading as unnamed class 
`$data_raw = $this->storage->read($this->getStorageFilename($version->getId(), $version->getCid(), $version->getCtype()));
$data = unserialize($data_raw , ['allowed_classes' => false]);
 $obj = $this->casttoclass('stdClass', $data);
                        $obj_new = get_object_vars($obj);
                        
                         function casttoclass($class, $object)
    {
        return unserialize(preg_replace('/^O:\d+:"[^"]++"/', 'O:' . strlen($class) . ':"' . $class . '"', serialize($object)));
    }`
    
    
to get the old data and then apply to new object -> serialize it and save it to version

but this is also still way off from using it generalised for all cases

**Comment by dvesh3** [comment]
@frithjof this is a different issue as the script is only trying to migrate `o_` system properties.

**Comment by frithjof** [comment]
system properties work fine +1 for the helper scripts for migration
