### ISSUE TITLE
[Bug]: Version error when using a Calculated Value in Objects Bricks

### ISSUE THREAD

**Issue by ayoob-lfc** [pimcore/pimcore#15846]
### Pimcore version

11.0.7

### Steps to reproduce

1 - Head over to https://demo.pimcore.fun/admin/

2 - Create a Calculated Value type in an Object Brick:

![image](https://github.com/pimcore/pimcore/assets/46787382/3eec2b93-fa31-40e6-975c-c478d1b4956c)

3 - Add the Brick to any Car object and save it:

![image](https://github.com/pimcore/pimcore/assets/46787382/fc2df85f-64cc-40a7-93eb-932267d9d5dd)

4 - Version throws an error:

![image](https://github.com/pimcore/pimcore/assets/46787382/5bae0f73-4468-4510-9abe-7d571e55363f)

### Actual Behavior

I get the following error:

`Pimcore\Model\DataObject\ClassDefinition\Data\CalculatedValue::getDataForEditmode(): Return value must be of type ?string, bool returned`

![image](https://github.com/pimcore/pimcore/assets/46787382/83f8d9cb-8498-48c4-8a36-0776271990ea)

### Expected Behavior

Shouldn't throw the error

**Comment by blankse** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15850
