### ISSUE TITLE
[Bug]: WYSIWYG editable "<" (&lt;) will be deleted

### ISSUE THREAD

**Issue by gadget60** [pimcore/pimcore#15858]
### Pimcore version

11.0.7

### Steps to reproduce

In a WYSIWYG editable, enter a "lower than" character (<) and save. After reloading the document, the character is gone - depending on the text after the character, some more text is missing too.

What happens here:
- On save, the payload to the admin controller is okay, for example `"<p>&lt;</p>"`
- Next, in the Wysiwyg editable, the HTML sanitizer kicks in, but *first* the html source is *decoded*. At this stage (befor sanitizing), the string contains `"<p><</p>"` which is invalid.

https://github.com/pimcore/pimcore/blob/e22a8209fde57c953a5caba13292d60ae3b06979/models/Document/Editable/Wysiwyg.php#L81C52-L81C52
- But even if the data would have been saved correctly to the database, it gets decoded and sanitized once again on load. I doubt that it makes any sense to sanitize at all on "setDataFromResource()" in the first place. But even if this is necessary for some reason, the HTML entity gets stripped here too:
https://github.com/pimcore/pimcore/blob/e22a8209fde57c953a5caba13292d60ae3b06979/models/Document/Editable/Wysiwyg.php#L89

The same issue exists in DataObject WYSIWYG:
https://github.com/pimcore/pimcore/blob/91811b8b8214917e71027f90de90a4426abc9395/models/DataObject/ClassDefinition/Data/Wysiwyg.php#L117C63-L117C63

### Actual Behavior

It is not possible to use `<` as a text character in a WYSIWYG editable. Even worse, text following the &lt; character may be lost after save.

### Expected Behavior

`<` should be possible to be used in a WYSIWYG editable.

**Comment by blankse** [comment]
Should be fixed with https://github.com/pimcore/pimcore/pull/15811

**Comment by gadget60** [comment]
Thanks and sorry, didn't see this issue because it was already closed.

@robertSt7 What is the reason for HTML sanitizing on setDataFromResource() at all? This seems to me like a lot of work which is done on every read (from database) access. 

https://github.com/pimcore/pimcore/blob/d1129258a41eb77e5f73b4d86d7018eb4666ae15/models/Document/Editable/Wysiwyg.php#L93C41-L93C41

**Comment by robertSt7** [comment]
Hi @gadget60 because there could be a stored XSS code in the database

**Comment by gadget60** [comment]
Thanks, @robertSt7 
Closing this issue in favour of #15938
