### ISSUE TITLE
Migrating pimcore 10.6 version to 11.0, composer udpate got success, error in migration

### ISSUE THREAD

**Issue by Thejaswini-Rao-U** [pimcore/pimcore#15867]
### Pimcore version

pimcore v 11.0

### Steps to reproduce

When i execute bin/console doctrine:migrations:migrate , migration command getting issue

### Actual Behavior

At first i have updated composer as per document and have resolved issues while updating..

after composer update is successfull, i executed **bin/console doctrine:migrations:migrate** command getting some class error

 i have no idea how to resolve it? 

as i see in the document, its mentioned to rebuild the class after this migration, so i have not executed class rebuild command,

![migrationError](https://github.com/pimcore/pimcore/assets/78895325/53592f21-4f91-4d35-9c20-5ee9555e8b80)

Anyone have idea , please let me know for the solution

Thanks in advance.

### Expected Behavior

success

**Comment by blankse** [comment]
Than you haven't execute the migration in Pimcore 10.6
This migration should save all ClassDefinitions and should make the maxItems to null or int. Before Pimcore 10.4.4 this attributes can be a emty string: https://github.com/pimcore/pimcore/commit/6245efe3be3d64ca5f3369a8472533f98d73043e

Otherwise you can patch manually this attributes in your definiton files (var/classes or config/pimcore/classes dirs)

See also: https://github.com/pimcore/pimcore/discussions/15857

**Comment by Thejaswini-Rao-U** [comment]
@blankse , Thanks for the quick response.

when i executed migration in 10.6 version, it showed me nothing to migrate. 

anyway i will try to do manually and fix.

**Comment by Thejaswini-Rao-U** [comment]
@blankse , how to run specific patch migration command for the classes to migrate in pimcore 11?
because in the 10.6 version after executing migration command, it didnt migrate the classes properly

can you tell, what are the files or datatypes of classes i need to fix it manually,

if fixing manually not good idea, is there any patch migration command execute at this stage?

please suggest?

**Comment by Thejaswini-Rao-U** [comment]
@blankse 
whenever  i execute migrate command in 10.6 version, i get successfull saying , its already in the latest version

please refer below screenshot
![amrod10migrate](https://github.com/pimcore/pimcore/assets/78895325/9b5cf785-3ecc-45f1-90a2-beedb533267e)

it means 10.6 migration is successfull, im getting error while migrating in pimcore 11, 

@blankse  or anyone please tell how to solve it in pimcore 11 without manually doing it ?

**Comment by blankse** [comment]
I see, that the Version20230720161000 migration only save all classes and custom layouts. Maybe there are object bricks and field collections with wrong types. Can you manually save all classes / object bricks / field collections in the pimcore 10.6 admin interface before you migrate to 11?

**Comment by Thejaswini-Rao-U** [comment]
@blankse , thanks for the response

okay i will manually save all the classes/ bricks/collections.

after saving should i run migrate command of 10.6 => ./bin/console doctrine:migrations:migrate --prefix=Pimcore\\Bundle\\CoreBundle
? then update to pimcore 11 ?

is it correct? in this way will this issue resolves?

**Comment by blankse** [comment]
Yes I think so. Your are on the latest 10.6.9 version?

**Comment by Thejaswini-Rao-U** [comment]
yes.

**Comment by Thejaswini-Rao-U** [comment]
@blankse 

after saving classes / object bricks / field collections in the pimcore 10.6 admin interface, /bin/console doctrine:migrations:migrate --prefix=Pimcore\Bundle\CoreBundle, then updated to pimcore 11 version

now after composer update, and while migrating using bin/console doctrine:migrations:migrate command getting different issue related to class definiation

please refer below screenshot

![classbuttonerror1](https://github.com/pimcore/pimcore/assets/78895325/5f3b5f1e-f5d1-4e74-9296-8011ccdacf79)


anyone please suggest the cause of this error and its solution

Thanks in advance
