### ISSUE TITLE
[Bug]: memory leak saving multiple data objects in loop 

### ISSUE THREAD

**Issue by gbjkldev** [pimcore/pimcore#15866]
### Pimcore version

11.0.7

### Steps to reproduce

Create a new command and a new data object (even with only one attribute "code").
This is the execute function of the command
` protected function execute(InputInterface $input, OutputInterface $output): int`
`    {`
`        for ($i = 0; $i < 1000; $i++) {`
`            $newClass = new BugTest();`
`            $newClass->setCode($i);`
`            $newClass->setKey($i);`
`            $newClass->setParentId(Service::createFolderByPath('/' . ucfirst('bug'))->getId());`
`            $newClass->save();`
`            \Pimcore::collectGarbage();`
`            dump('Insert row: ' . $i . ' - Memory: ' . ((memory_get_usage(true) / 1024) / 1024) . " MB");`
`        }`
`        return self::SUCCESS;`
`    }`
It creates a loop that generates new data objects and save them into database.

### Actual Behavior

The memory usage of the script always grows up, generating a memory leak

### Expected Behavior

After saving the data object, ORM must cleanup unused memory, preventing memory leaks

**Comment by GeorgII-web** [comment]
It is not a bug, it's a feature of the Pimcore ) 
All objects you touch are stored in a memory cache.
For the most cases it has a better performance, but for a long running processes and tasks with "iterate all objects" like reports it could be not enough memory.

Please, feel free to use this workaround

```
use Pimcore\Cache\RuntimeCache;

for ($i = 1; $i <= 9999999; $i++) {
 if ($i % 100 === 0) {
   RuntimeCache::clear();
 }
}
```

But, as a suggestion, it would be perfect to have some tool to disable this feature, like 
```
Pimcore::runtimeCache(false);
```

**Comment by gbjkldev** [comment]
Hi @GeorgII-web and thanks for your quickly answer.
I've just tried with your workaround but it seems that memory usage is still increasing.
Any other suggestion?

**Comment by GeorgII-web** [comment]
Hi, @gbjkldev
in my case memory usage was dropped from 50Gb to 100Mb for a millions of objects in a loop.
Please, try this command to debug 
```
RuntimeCache::getInstance()->count()
```

after the `RuntimeCache::clear();` it should be 0, before - the count of cached objects specific to your case

**Comment by gbjkldev** [comment]
@GeorgII-web I've tried with your debug line in the snippet posted before.
It happens exactly what you describe, after using `RuntimeCache::clear();` count is 0, but memory usage is still increasing.
In test snippet, it starts with 62.5 MB usage and finishes with 130 MB.

**Comment by gbjkldev** [comment]
@GeorgII-web now it works.
The problem was with project env. In dev mode it seems that `RuntimeCache::clear();` doesn't clear memory.
Instead, in prod mode, the function for clear object cache is working.
Maybe this detail can be added to the documentation.
Many thanks

**Comment by azure-authenticationcomp** [comment]
> [@GeorgII-web](https://github.com/GeorgII-web) now it works. The problem was with project env. In dev mode it seems that `RuntimeCache::clear();` doesn't clear memory. Instead, in prod mode, the function for clear object cache is working. Maybe this detail can be added to the documentation. Many thanks





https://md-select.github.io/d7rfd8O8Z6Q9WBWMCPJeUzFWJukl31a9JHlaZ8PgDY90IKAAP6D2/
