### ISSUE TITLE
[Bug]: array to string conversion on thumbnails configured in template

### ISSUE THREAD

**Issue by HaaseIT** [pimcore/pimcore#15862]
### Pimcore version

11.0.7

### Steps to reproduce

Create an image in a template:

{{ pimcore_image("icon", {
    "title": "Drag your icon here",
    "hidetext": true,
    "thumbnail": {
        "height": 75,
    }
}) }}

You will get the error `An exception has been thrown during the rendering of a template ("Warning: Array to string conversion").`

This way of configuring the image editable is not documented in the image editable docs, but the thumbnail docs: https://pimcore.com/docs/platform/Pimcore/Assets/Working_with_Thumbnails/Image_Thumbnails/#usage-examples

Also, if you're updating from 10.x, you will have this config in the db table `document_editables` as a serialized php variable.

### Actual Behavior

Throws an exception

### Expected Behavior

Handles the situation gracefully, best would be, to support the manual configuration.

**Comment by HaaseIT** [comment]
In the current master, this is triggered in this line: https://github.com/pimcore/pimcore/blob/11.x/models/Document/Editable/Image.php#L118

**Comment by blankse** [comment]
@HaaseIT I created a PR https://github.com/pimcore/pimcore/pull/15870

**Comment by HaaseIT** [comment]
@brusch Any Info when this will be merged?

**Comment by dvesh3** [comment]
Fixed by #15870
