### ISSUE TITLE
[Bug]: Images Linked "/admin/asset/get-image-thumbnail?id=XXX&width=600&aspectratio=true" are NOT Displayed

### ISSUE THREAD

**Issue by capitalfuse** [pimcore/pimcore#15874]
### Pimcore version

11.0.6

### Steps to reproduce

Drag & Drop images from Assets into Wysiwyg text area on Documents or Data Objects files, image link shows like below. 

> `/admin/asset/get-image-thumbnail?id=XXX&width=600&aspectratio=true`

**Issues**

1. Images are displayed on the browser only if you have already logged in the admin page on the same browser.
2. So, anyone can't see the above images.

### Actual Behavior

Drag & Drop images from Assets into Wysiwyg text area on Documents or Data Objects files, image link shows like below. 

> `/admin/asset/get-image-thumbnail?id=XXX&width=600&aspectratio=true`

### Expected Behavior

Actual path for images 
ex)  `pimcore/public/var/assets/News/example.png`

**Comment by capitalfuse** [comment]
#### Relevant file

**`public/bundles/pimcoretinymce/js/editor.js`**
```
if (data.elementType === "asset") {
            if (data.type === "image" && textIsSelected === false) {
                // images bigger than 600px or formats which cannot be displayed by the browser directly will be
                // converted by the pimcore thumbnailing service so that they can be displayed in the editor
                let defaultWidth = 600;
                let additionalAttributes = {};

                if (typeof data.imageWidth != "undefined") {
                    const route = 'pimcore_admin_asset_getimagethumbnail';
                    const params = {
                        id: id,
                        width: defaultWidth,
                        aspectratio: true
                    };

                    uri = Routing.generate(route, params);

                    if (data.imageWidth < defaultWidth
                        && in_arrayi(pimcore.helpers.getFileExtension(data.text),
                            browserPossibleExtensions)) {
                        uri = data.path;
                        additionalAttributes = mergeObject(additionalAttributes, {pimcore_disable_thumbnail: true});
                    }

                    if (data.imageWidth < defaultWidth) {
                        defaultWidth = data.imageWidth;
                    }

                    additionalAttributes = mergeObject(additionalAttributes, {style: `width:${defaultWidth}px;`});
                }

                additionalAttributes = mergeObject(additionalAttributes, {
                    src: uri,
                    pimcore_type: 'asset',
                    pimcore_id: id,
                    target: '_blank',
                    alt: 'asset_image'
                });
                tinymce.activeEditor.selection.setContent(tinymce.activeEditor.dom.createHTML('img', additionalAttributes));
                return true;
            } else {
                tinymce.activeEditor.selection.setContent(tinymce.activeEditor.dom.createHTML('a', {
                    href: uri,
                    pimcore_type: 'asset',
                    pimcore_id: id,
                    target: '_blank'
                }, wrappedText));
                return true;
            }
        }
```
The below is correct?
> `const route = 'pimcore_admin_asset_getimagethumbnail';`

**Comment by kingjia90** [comment]
All good in there, your suggestion on https://github.com/pimcore/pimcore/issues/15878 is actually the remedy for both problems (link,images)

Will be resolved by https://github.com/pimcore/pimcore/pull/15940

The only missing things is that for existing wysiywg content from `11.0.0` to `11.0.8`, there would be needing a manual script (a gist maybe) to re-order these attributes in the correct way

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15940

**Comment by twin-elements** [comment]
Are you sure the problem has been solved?
After all, the link "/admin/asset/get-image-thumbnail?id=XXX&width=600&aspectratio=true" still appears on the frontend and the image is displayed only if you are logged into the panel.
Pimcore version: 11.1.1

**Comment by kingjia90** [comment]
@twin-elements did you have data saved while on 11.0.0 and 11.0.8? then might still be broken, need to some way refresh these content
> The only missing things is that for existing wysiywg content from `11.0.0` to `11.0.8`, there would be needing a manual script (a gist maybe) to re-order these attributes in the correct way

**Comment by twin-elements** [comment]
> @twin-elements did you have data saved while on 11.0.0 and 11.0.8? then might still be broken, need to some way refresh these content
> 
> > The only missing things is that for existing wysiywg content from `11.0.0` to `11.0.8`, there would be needing a manual script (a gist maybe) to re-order these attributes in the correct way

Hi.
I have tested this in various ways and the behavior is very unstable, because for some images it just doesn't work.

I insert different images one by one and for some it just adds src, for some it generates thumbnail and for some it generates link **/admin/asset/get-image-thumbnail?id=1437&width=600&aspectratio=true**

![image](https://github.com/pimcore/pimcore/assets/17727266/e5fa5937-d72f-4f15-b2c5-fedc93c15bdb)

Pimcore version 11.1.4
I'm doing it on a new instance of Pimcore.
