### ISSUE TITLE
[Bug]: WYSIWYG internal links are not updated on render

### ISSUE THREAD

**Issue by gadget60** [pimcore/pimcore#15878]
### Pimcore version

11.0.8

### Steps to reproduce

- In a WYSIWYG editable, insert a link to a document via drag'n'drop: "pimcore_id" and "pimcore_type" are set, if you check the HTML source. Save the document that holds the editable.
- Rename or move the document that has been linked.
- Check the rendered HTML: The link has not been updated; it points to the "old" location of the linked document. The same applies to Pimcore objects BTW.

The issue has already been mentioned in #15410 , but still exists:
Problem seems that the Regex in 
https://github.com/pimcore/pimcore/blob/40608fb9faff7aaa02d8014761036abb28843a66/lib/Tool/Text.php#L194
...expects pimcore_id and pimcore_type in a specific order, which currently does not match how links are saved.

### Actual Behavior

pimcore_id and pimcore_type are not matched in in Links. Href-attributes therefore won't be updated when WYSIWYG-editables are rendered.

### Expected Behavior

Links having pimcore_type and pimcore_id attributes are updated on-the-fly to reflect current state.

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15940
