### ISSUE TITLE
[Bug]: WYSIWYG "Editor Configuration" field ignored

### ISSUE THREAD

**Issue by tmannherz** [pimcore/pimcore#15873]
### Pimcore version

11.0.7

### Steps to reproduce

\* The screenshots below are from the Pimcore demo site, https://demo.pimcore.com/admin/

1. Open a data object class (or a field collection) with a WYSIWYG field
![image](https://github.com/pimcore/pimcore/assets/533798/b5c104e0-3174-42e6-b6e6-9ac0e87df68b)
2. Enter config into the `Editor Configuration` field and save the class, eg.
    ```json
    {
        "plugins": "lists link code",
        "toolbar1": "undo redo | bold italic underline | bullist numlist link | removeformat code"
    }
    ``` 
    ![image](https://github.com/pimcore/pimcore/assets/533798/fb0d9ca3-5b3e-4f63-aea5-f06866ed5789)
3. Refresh a data object and click into the description field. You see the default WYSIWYG config rather than your custom config. 
![image](https://github.com/pimcore/pimcore/assets/533798/625b0515-4469-4145-979b-b65e337f2a2b)

### Actual Behavior

WYSIWYG editor configuration is _not_ applied to the editor.

If the config above were applied, the editor toolbar should like this:
![image](https://github.com/pimcore/pimcore/assets/533798/f086fa74-f579-4241-a59f-704866f64431)

Similar to if the config was set in a Twig template for a `pimcore_wysiwyg` editable:
```
{{ pimcore_wysiwyg("content", {
    plugins: 'lists link code',
    toolbar1: 'undo redo | bold italic underline | bullist numlist link | removeformat code'
}) }}
```

### Expected Behavior

WYSIWYG editor configuration _is_ applied to the editor.

**Comment by dvesh3** [comment]
Fixed by #16000
