### ISSUE TITLE
[Bug]: Class definitions file names are case sensitive in Linux filesystem

### ISSUE THREAD

**Issue by aashan10** [pimcore/pimcore#15889]
### Pimcore version

10.5

### Steps to reproduce

Consider you have a fieldcollection with key `DownloadDocuments` and the definition is something like 

```php
return Pimcore\Model\DataObject\Fieldcollection\Definition::__set_state(array(
   'dao' => NULL,
   'key' => 'DownloadDocuments',
   'parentClass' => '',
   'implementsInterfaces' => '',
   'title' => '',
   'group' => 'Downloads',
   'layoutDefinitions' => 
  Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
     'name' => NULL,
     'type' => NULL,
     'region' => NULL,
     'title' => NULL,
     'width' => 0,
     'height' => 0,
     'collapsible' => false,
     'collapsed' => false,
     'bodyStyle' => NULL,
     'datatype' => 'layout',
     'permissions' => NULL,
     'children' => array(),
   ),
   'generateTypeDeclarations' => true,
   'blockedVarsForExport' => 
  array (
  ),
));
```

Now, when you use the field collection, it is being loaded by the key as in 
https://github.com/pimcore/pimcore/blob/dd81ef4c666b18c254333867a60f6ed455025076/models/DataObject/Fieldcollection/Definition.php#L114-L117

Now, since linux filesystem is case-sensitive by default, if a class definition file has its name same as the key of the definition file but in different case, like `downloaddocuments.php` in this case, php does not recognize that `downloaddocuments.php` is the definition file for `DownloadDocuments` fieldcollection. This results in the fieldcollection being discarded when the object using it is loaded.

### Actual Behavior

Class definition file names are case sensitive and are not loaded

### Expected Behavior

Class definition file names should be case insensitive and should be loaded

**Comment by kingjia90** [comment]
Closing in favor of https://github.com/pimcore/pimcore/issues/14790
