### ISSUE TITLE
[Bug]: call to undefined method isPublished

### ISSUE THREAD

**Issue by Mordef** [pimcore/pimcore#15894]
### Pimcore version

10.6.3

### Steps to reproduce

Used in a console-command-script:

https://pimcore.com/docs/platform/Pimcore/Assets/Working_with_PHP_API

```php
//creating and saving new asset
$newAsset = new \Pimcore\Model\Asset();
$newAsset->setFilename("myAsset.png");
$newAsset->setData(file_get_contents("some-file.png"));
$newAsset->setParent(\Pimcore\Model\Asset::getByPath("/"));

// the optional parameter allows you to provide additional info
// currently supported:
//      * versionNote: note added to the version (see version tab)
$newAsset->save(["versionNote" => "my new version"]);
```

### Actual Behavior

Asset ist created, but this error comes:
```
ERROR     [pimcore] Class: Pimcore\Model\Asset => call to undefined method isPublished
```

### Expected Behavior

No Error-message

**Comment by blankse** [comment]
@Mordef I couldn't reproduce it in Pimcore 10.6.9 and Pimcore 11.0.8
I get no error if I execute your code in a symfony console command.

**Comment by NiklasBr** [comment]
Do you have any event listeners which may trigger on save?

**Comment by Mordef** [comment]
Thanks @NiklasBr 
I have DynamicSearch and there i found it.
