### ISSUE TITLE
[Bug]: After upgradning from 10.6.9 to 11.0.8 classes rebuild fails on object bricks

### ISSUE THREAD

**Issue by morgannilsson** [pimcore/pimcore#15897]
### Pimcore version

11.0.8

### Steps to reproduce

bin/console pimcore:deployment:classes-rebuild -ncd

### Actual Behavior

In ExceptionConverter.php line 117:
                                                                                                                       
  An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1828 Cannot drop column 'o_id': need  
  ed in a foreign key constraint 'fk_object_brick_store_DTypeA1Certificate_document__o_id'

### Expected Behavior

Command completed ok,

**Comment by morgannilsson** [comment]
After running:

console doctrine:migrations:migrate --prefix=Pimcore\\Bundle\\CoreBundle

I get:

[error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20230616085142 failed during Execution. Error: "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1553 Cannot drop index 'PRIMARY': needed in a foreign key constraint"

In ExceptionConverter.php line 117:
                                                                                                                       
  An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1553 Cannot drop index 'PRIMARY': needed in a foreign key constraint

**Comment by dvesh3** [comment]
@morgannilsson It seems the migration `Version20221003115124` is not executed which migrates the `o_id` columns to `id`. Could you please check if this is migrated?

**Comment by dvesh3** [comment]
@morgannilsson any update on this?

**Comment by kingjia90** [comment]
Closing due inactivity

**Comment by neha04** [comment]
@dvesh3 @morgannilsson i am facing same issue while rebuilding classes. Any update or resolution on this?

[Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'CREATE TABLE IF NOT EXISTS `object_query_Acquisitions` (
                          `oo_id` int(11) UNSIGNED NOT NULL default '0',
                          `oo_classId` varchar(50) default 'Acquisitions',
                          `oo_className` varchar(255) default 'Acquisitions',
                          PRIMARY KEY  (`oo_id`),
                          CONSTRAINT `fk_object_query_Acquisitions__oo_id` FOREIGN KEY (`oo_id`) REFERENCES objects (`o_id`) ON DELETE CASCADE
                        ) DEFAULT CHARSET=utf8mb4;':

 

  SQLSTATE[HY000]: General error: 1826 Duplicate foreign key constraint name 'fk_object_query_Acquisitions__oo_id'
