### ISSUE TITLE
Error on process manager , while migrating to pimcore version 11

### ISSUE THREAD

**Issue by Thejaswini-Rao-U** [pimcore/pimcore#15928]
### Pimcore version

pimcore v11

### Steps to reproduce

While executing command **bin/console doctrine:migrations:migrate**

getting process manager error

### Actual Behavior

Getting error on process manager, please refer screenshot

![configurationProcessError](https://github.com/pimcore/pimcore/assets/78895325/fd8ff796-cbb9-4721-82bf-9981247b1faf)

how to solve please suggest?

### Expected Behavior

it should work

**Comment by kingjia90** [comment]
Closing as duplicate and because it out of the Pimcore direct scope (bundle belongs to elements.at)
See also https://github.com/pimcore/pimcore/discussions/15890#discussioncomment-6987208 for any follow-up on this
