### ISSUE TITLE
[Bug]: CKEditor (WYSIWYG) thumbnails not used

### ISSUE THREAD

**Issue by Mordef** [pimcore/pimcore#15929]
### Pimcore version

10.6.9

### Steps to reproduce

I try to insert the asset manuel  (You can also dragndrop an asset and change the url with `thumbnail=YOUR_RULE`
```
/admin/asset/get-image-thumbnail?id=2179&thumbnail=content
```
The CKEditor show now correct, also when i call it direct, image is shown with thumbnail scale (scale width to 870px)

In Frontent, the url is like
```
path/to/asset/image-thumb__2179___auto_546c3c4099a3e23ac125f4df4426d4dc/filename.jpg
```
But this is the original Image, not scaled. (2000px x 1500px)

After save und reload the Backend, inside the CKEditor the url is rewritten to `path/to/asset/image-thumb...` 
And now its also not scaled.

### Actual Behavior

Thmbnail-rule is not used in the frontend

### Expected Behavior

Thmbnail-rule is used in the frontend

**Comment by kingjia90** [comment]
Thank you for reporting but unfortunately Pimcore 10.6 is EOL.
