### ISSUE TITLE
[Bug]:  Unaable to install 11.0.8 version.

### ISSUE THREAD

**Issue by shree0** [pimcore/pimcore#15934]
### Pimcore version

11.0.8

### Steps to reproduce

After this commnad `.--admin-username=xxx --admin-password=xxxx --mysql-username=xxxx --mysql-password=xxxx --mysql-database=xxxx --no-interaction` 
I am getting
`[ERROR] The following errors were encountered during installation `
`* Manage Indexes is required.` 
errors.
In `var/log/dev.log` I can see the following error message:
```
php.INFO: User Deprecated: Not configuring a schema manager factory is deprecated. Use Doctrine\DBAL\Schema\DefaultSchemaManagerFactory which is going to be the default in DBAL 4. (Connection.php:225 called by DriverManager.php:196, https://github.com/doctrine/dbal/issues/5812, package doctrine/dbal) {"exception":"[object] (ErrorException(code: 0): User Deprecated: Not configuring a schema manager factory is deprecated. Use Doctrine\\DBAL\\Schema\\DefaultSchemaManagerFactory which is going to be the default in DBAL 4. (Connection.php:225 called by DriverManager.php:196, https://github.com/doctrine/dbal/issues/5812, package doctrine/dbal) at /..../..../.../pimcore/vendor/doctrine/deprecations/lib/Doctrine/Deprecations/Deprecation.php:209)"} []
```
please help to resolve this.

### Actual Behavior

This commnad `.--admin-username=xxx --admin-password=xxxx --mysql-username=xxxx --mysql-password=xxxx --mysql-database=xxxx --no-interaction`  is not excuted.

### Expected Behavior

Not facing any issues during 10.x versions. But in 11.x getting error during installation.

**Comment by kingjia90** [comment]
Looks like the user is not allowed to manage indexes
See also https://github.com/pimcore/pimcore/blob/33173df4b983fe81035e44e8b7dadf956f49f5cc/doc/23_Installation_and_Upgrade/01_System_Requirements.md?plain=1#L64

**Comment by shree0** [comment]
But in the error log, I can see

 `php.INFO: User Deprecated: Not configuring a schema manager factory is deprecated. Use Doctrine\DBAL\Schema\DefaultSchemaManagerFactory which is going to be the default in DBAL 4. (Connection.php:225 called by DriverManager.php:196, https://github.com/doctrine/dbal/issues/5812, package doctrine/dbal) {"exception":"[object] (ErrorException(code: 0): User Deprecated: Not configuring a schema manager factory is deprecated. Use Doctrine\\DBAL\\Schema\\DefaultSchemaManagerFactory which is going to be the default in DBAL 4. (Connection.php:225 called by DriverManager.php:196, https://github.com/doctrine/dbal/issues/5812, package doctrine/dbal) at /..../..../.../pimcore/vendor/doctrine/deprecations/lib/Doctrine/Deprecations/Deprecation.php:209)"} []
`

error. I think this is causing the issue while installing.

**I am installing it in the CPanel server.**

**Comment by kingjia90** [comment]
No, deprecation warning are not stopping the exection or affecting it, these are just heads-up for future releases/upgrades, we are not even on DBAL4 for example, it's not affecting the code "yet" (otherwise it's a bc break and a potential regression from their end).

**Comment by shree0** [comment]
OK, Is there any other ways to trace my problem during installation?

**Comment by kingjia90** [comment]
the installation script works with multiple steps, right now is stopping because the user doesn't have the permission to manage the indexes and therefore it wouldn't be able to create/modify the table indexes and is stopping.
You just need to grant the permissions to the user (the same defined after `mysql-username=`) and should be good to go.

Any other errors, will interrupt the script from continuing within red blocks, can't miss/overlook them.
