### ISSUE TITLE
[Bug]: Document versions with `pimcore_image()` can't be opened after Pimcore 11 upgrade

### ISSUE THREAD

**Issue by tmannherz** [pimcore/pimcore#15932]
### Pimcore version

11.0.8

### Steps to reproduce

1. Create a Pimcore 10.6 document with a widget that itself has an image editable (`pimcore_image()`). Save that document yielding a new version. [The `Hero Grid` widget](https://github.com/pimcore/demo/blob/11.x/templates/areas/hero-grid/view.html.twig#L17) in the Pimcore demo site is an example of such a widget. 
1. Update to Pimcore 11. 
1. Try to preview the version of the document created prior to the upgrade.

Related to https://github.com/pimcore/pimcore/issues/15662

### Actual Behavior

Rather than rendering the old version, you get an error `Cannot assign null to property Pimcore\Model\Document\Editable\Image::$cropPercent of type bool`

![image](https://github.com/pimcore/pimcore/assets/533798/0b5ebbdc-0fcd-4450-b565-6584a6532d13)

Making the following properties nullable in `Pimcore\Model\Document\Editable\Image` seems to resolve the issue:
```php
    /**
     * @internal
     *
     * @var bool
     */
    protected ?bool $cropPercent = false;

    /**
     * @internal
     *
     * @var float
     */
    protected ?float $cropWidth = 0.0;

    /**
     * @internal
     *
     * @var float
     */
    protected ?float $cropHeight = 0.0;

    /**
     * @internal
     *
     * @var float
     */
    protected ?float $cropTop = 0.0;

    /**
     * @internal
     *
     * @var float
     */
    protected ?float $cropLeft = 0.0;
```

### Expected Behavior

Document version is successfully rendered.

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16009
