### ISSUE TITLE
[Bug]: Save object with table in objectbrick

### ISSUE THREAD

**Issue by LeonNoBears** [pimcore/pimcore#15955]
### Pimcore version

11.0.8

### Steps to reproduce

Create Object Class
Create ObjectBrick
Add Table to ObjectBrick
Link ObjectBrick to Class
Create Object with Class and Add ObjectBrick
Save Object

### Actual Behavior

Error:
 Pimcore\Model\DataObject\ClassDefinition\Data\Table::getDataForResource(): Argument #2 ($object) must be of type ?Pimcore\Model\DataObject\Concrete, Pimcore\Model\DataObject\Objectbrick\Data\Foo given, called in /vendor/pimcore/advanced-object-search/src/Filter/FieldDefinitionAdapter/Table.php on line 111

### Expected Behavior

Tables + content is saved and published

**Comment by LeonNoBears** [comment]
https://github.com/pimcore/advanced-object-search/pull/244

**Comment by aryaantony92** [comment]
Reproducible with 'Column Configuration' enabled for the table data type

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/advanced-object-search/pull/244
