### ISSUE TITLE
[Pimcore 4.6.0] Classification Store column attribute sorting issue under object grid listing

### ISSUE THREAD

**Issue by anupam1501** [pimcore/pimcore#1596]
**Steps to Reproduce :-**

- Open Object grid listing under "Objects" Panel.
- Click on "Column Configuration".
- Select "classification store" class attribute and add any "key" in grid column configuration.
- Now perform sorting using classification store key column that you just added above.

**Expected behavior** 
- Objects will get sorted on the basis of sorting selection.
  
**Actual behavior**
- **Throws an error saying : "Fatal error: Uncaught Zend_Db_Statement_Mysqli_Exception: Mysqli prepare error: Column 'o_id' in field list is ambiguous"**
  
![demo pimcore org pimcore](https://user-images.githubusercontent.com/28050181/27069671-7e3a945a-5033-11e7-9525-055c0f8c9d3e.png)

Thanks

**Comment by weisswurstkanone** [comment]
already fixed via https://github.com/pimcore/pimcore/commit/6354699ce0ad86d71f158f8c921b52b6f1d5c6a6
