### ISSUE TITLE
Move function to admin-ui-classic-bundle

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#15971]
### Improvement description

https://github.com/pimcore/pimcore/blob/0fcf252faafdaf270d620d1cc96bb49fc14dabcc/models/Asset/Service.php#L277

doesn't belong to pimcore/pimcore it should be in https://github.com/pimcore/admin-ui-classic-bundle

**Comment by dvesh3** [comment]
This is called in `gridAssetData` so that should be moved to admin bundle as well and maybe other element types as well e.g. `gridObjectData`& `gridDocumentData`. maybe implement a new service in admin ui bundle.
