### ISSUE TITLE
CsvFormulaFormatter breaks with league/csv:9.11

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#15998]
### Improvement description

Fix type hints for extended method:
```
Fatal error: Declaration of Pimcore\Helper\CsvFormulaFormatter::unEscapeField(string $field): string must be compatible with League\Csv\EscapeFormula::unescapeField(mixed $cell): mixed in /var/www/html/vendor/pimcore/pimcore/lib/Helper/CsvFormulaFormatter.php on line 22
```

**Comment by dvesh3** [comment]
Fixed by #15999

**Comment by jhormel** [comment]
Hey @dvesh3 

I am right now creating a new project and took notice of this because I run into it.

Could you please double check:

- Parameter type has been fixed
- Return type has **not** been fixed (must be `mixed` instead of `string` // same as the parameter)

Or am I missing something?

**Comment by dvesh3** [comment]
@jhormel return type can be more specific in child class(Covariance) so `string` is fine.

**Comment by jhormel** [comment]
ah alright, thanks :+1:
