### ISSUE TITLE
[Bug]: `league/csv` EscapeFormula has a new method added which conflicts with the return types in `CsvFormulaFormatter`

### ISSUE THREAD

**Issue by aashan10** [pimcore/pimcore#16008]
### Pimcore version

10.6

### Steps to reproduce

`league/csv` package added a function in their CsvFormula class 

https://github.com/thephpleague/csv/blob/94bff989f22fbc9f939af10a1f15402949ccbb98/src/EscapeFormula.php#L118
The function name matches (apparently method names are case insensitive for some reason), but the method signatures do not match.

https://github.com/pimcore/pimcore/blob/46833bf1bdb91691522534713352bd4897f8b9ec/lib/Helper/CsvFormulaFormatter.php#L22

### Actual Behavior

Error should not be thrown when running `bin/console c:c`

### Expected Behavior

Declaration of Pimcore\Helper\CsvFormulaFormatter::unEscapeField(string $field): string must be compatible with League\Csv\EscapeFormula::unescapeField(mixed $cell): mixed in /var/www/html/vendor/pimcore/pimcore/lib/Helper/CsvFormulaFormatter.php on line 22

**Comment by jdreesen** [comment]
See: #16006
