### ISSUE TITLE
[Bug]: Translation XLIFF export/import bug

### ISSUE THREAD

**Issue by akno77** [pimcore/pimcore#16037]
### Pimcore version

11.0.9

### Steps to reproduce

- Create a content page (i.e EN)
- Copy this page as a new language version (i.e. DE)
- Change content in the original content page (i.e. EN)
- Export the copied language page (i.e. DE) as XLIFF

### Actual Behavior

The XLIFF file contains only the content for the exported page but not for the source page

Here are some screenshots.

The German language version document:
![270619289-474f10a9-7062-4640-b3a3-a62aea25f80f](https://github.com/pimcore/pimcore/assets/35833873/add9d724-f5fd-4e29-aa5c-a23639361f49)

The English language version document:
![270619385-2f570244-10b9-4b7e-bf86-4be43ca13c42](https://github.com/pimcore/pimcore/assets/35833873/459c56e1-7539-4f75-834b-b46a611dce75)

The export of the German language document with source = EN and traget = DE
![270619423-56fc7398-50eb-4dde-8c0a-da7845ccaf79](https://github.com/pimcore/pimcore/assets/35833873/171c480a-cfd1-4ff9-a100-f496989212ee)

The exported XLIFF file in poedit, the source and target are the same:
![270619457-44ed7e88-ad15-4d99-8b41-ed71dc8c836d](https://github.com/pimcore/pimcore/assets/35833873/85544b4f-08ac-44f3-97f7-8d831be9fdc2)

### Expected Behavior

The XLIFF file contains the current content of the source document and the current content of the document to be translated

**Comment by akno77** [comment]
I created this bug report based on this discussion: https://github.com/pimcore/pimcore/discussions/15575

**Comment by dvesh3** [comment]
@akno77 It is intended behavior of XLIFF export/import for documents. You have to copy the source document and export the target docuement (with source document copy content). please see notes from the UI:

```
If you want to translate eg. the whole /en tree to a different language, first create a copy of the /en tree. Afterwards use the copied tree in the export and select the source language 'en' and the target language 'de'. When importing the translated XLIFF file, the contents of the exported documents (in this case the copied tree documents) will be overwritten by the German translations in the XLIFF file.
```

**Comment by akno77** [comment]
@dvesh3

1. The mentioned instruction only works as long the tree is newly copied and the source tree is unchanged in the meantime (as I said the exported XLIFF **always** displays the wrong source language values, it is **always** the same value as the target language value!
2. So you mean the whole export/import only works for the first tree translation and as soon the source has changes to be translated it has not to work anymore? Did you try my example? I tried **every** possible variant to export/import and **none** did work as expected!

**Comment by dvesh3** [comment]
@akno77 you could simply use the inheritance option while copy/pasting the new tree to make sure the extracted data is latest from source document.
![image](https://github.com/pimcore/pimcore/assets/5137917/fb182f61-238d-4dca-8565-c783e8533cc6)

**Comment by akno77** [comment]
@dvesh3 This only "works" as long you didn't translate any text... I see, I have to find the bug by myself and fix it :-(

**Comment by port-neo-peterlang** [comment]
As akno said it does not not meet the requirements that we have. Let me try to explain it again. Concretely, it is about the fact that either for the translation the "original" document in the xliff must be exchanged manually or only the contents from one language are exported.

Scenario: A new text is added or changed in a German document. I want to apply the changed text to the linked English document.

Procedure:
Variant 1:
- XLIFF Export/Import
- Selection of the English document
- Source: DE / Target: EN
- Result: XLIFF ONLY with English content (no German texts from the source), i.e. the translation agency would not have the - German source texts.
- But during the import the English page would be imported.
 
Variant 2:
- XLIFF export/import
- Selection of the German document
- Source: DE / Target: EN
- Result: XLIFF with German content as source and English content as target (correct), BUT: the original-document Id points to the German document.
But during import the German page would be imported and NOT the English page as desired. (only after manual change to the document-id of the English document it would work).
 
So the feature is currently not usable for us and it turns into a blocker.
Is THIS the desired behavior? What can we do?

**Comment by port-neo-peterlang** [comment]
sorry if I'm annoying, but is there an update?

**Comment by aryaantony92** [comment]
@port-neo-peterlang Sorry for the delayed response. The topic is in discussion internally. And we will keep you posted. We highly appreciate some suggestions/possible solutions from you. Thank you!

**Comment by dvesh3** [comment]
@port-neo-peterlang @akno77 After discussing it internally, we came to the conclusion to consider this request as improvement not bug. We would like to add an option for exporting documents content to consider source language translation links to avoid breaks if a custom implementation somehow relies on current approach. The current behavior is just a reason for not having translations links in the past. please see https://github.com/pimcore/pimcore/issues/16188

**Comment by dvesh3** [comment]
@akno77 @port-neo-peterlang While working on the improvement, we realized that it is indeed seems to be a bug as the source language tags are exported with wrong data. 

Please see https://github.com/pimcore/pimcore/pull/16269 could you please confirm if this fixes the issue when selecting the source with changed data? thanks!

**Comment by akno77** [comment]
@dvesh3 Yes, it seems to work now!
