### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tomhuber96** [pimcore/pimcore#16038]
### Pimcore version

11.0.11

### Steps to reproduce

Call \Pimcore\Model\Document\Editable\Video->setDataFromResource() with  another datatype then a string, e.g. with an array. 

### Actual Behavior

Throws an error, when called with an array, because \Pimcore\Tool\Serialize::unserialize() expects ?string datatype, but setDataFromResource allows mixed data. 

### Expected Behavior

The function setDataFromResource should not throw an error, if another datatype then a string is passed. 
Could be fixed by changing: 
if (!empty($data)) {
   $data = \Pimcore\Tool\Serialize::unserialize($data);
}

to

if (!empty($data) && is_string($data)) {
   $data = \Pimcore\Tool\Serialize::unserialize($data);
}

**Comment by aryaantony92** [comment]
@tomhuber96 Thank you for the suggestion. Looks good. Created a PR https://github.com/pimcore/pimcore/pull/16058

**Comment by dvesh3** [comment]
Fixed by #16058
