### ISSUE TITLE
[Bug]: WYSIWYG editable "<" (&lt;) will be deleted 

### ISSUE THREAD

**Issue by mhgtlc** [pimcore/pimcore#16031]
### Pimcore version

11.0.11

### Steps to reproduce

See https://github.com/pimcore/pimcore/issues/15858 and https://github.com/pimcore/pimcore/issues/15938
it was fixed, but problem reappeared after:
https://github.com/pimcore/pimcore/pull/16013
https://github.com/pimcore/pimcore/pull/15960

### Actual Behavior

See See https://github.com/pimcore/pimcore/issues/15858 and https://github.com/pimcore/pimcore/issues/15938

### Expected Behavior

See See https://github.com/pimcore/pimcore/issues/15858 and https://github.com/pimcore/pimcore/issues/15938

**Comment by dvesh3** [comment]
duplicate of #15740
