### ISSUE TITLE
[Bug]: setMaxItems expects int, but includes a integerCast function

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#16051]
### Pimcore version

11.0.11

### Steps to reproduce

Im currently performing an update from Pimcore 10 to 11.

I get following error in the backend:

Message: Pimcore\Model\DataObject\ClassDefinition\Data\ManyToManyObjectRelation::setMaxItems(): Argument #1 ($maxItems) must be of type ?int, string given, called in /app/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data.php on line 226

Probably there are some values stored wrongly in the database (as string), as the classes were created with Pimcore 10. I'm confused as setMaxItems expects an int value, but getAsIntegerCast allows mixed with a further check.

https://github.com/pimcore/pimcore/blob/ae5f6732edb7a1e1b5530ff3b1bc29aa8e74ed25/models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php#L366 (other locations also)

Is it intended to be ?int or should it also be mixed?

This also affects setMaxTabs

**Comment by blankse** [comment]
There are migrations in 10.x to migrate the empty string values to null. See https://github.com/pimcore/pimcore/discussions/15890#discussioncomment-6901924
