### ISSUE TITLE
[Bug][P11]: Using any button on the TinyMCE editor does not trigger a pimcore.events.changeWysiwyg event

### ISSUE THREAD

**Issue by alexej-d** [pimcore/pimcore#16059]
### Pimcore version

11.0.11

### Steps to reproduce

Go to the Pimcore demo and use the WYSIWYG editor in any document. Select some text an click the bold button. Save the document immediately.

### Actual Behavior

When you reload the document you can see, that the last change ist not visible, as it did not trigger the changeWysiwyg event.

### Expected Behavior

After reloading the document the last change should be visible.

**Comment by alexej-d** [comment]
BTW: The same goes for pasting. Immediately saving, after pasting content, does not persist the pasted text to the DB.

**Comment by dvesh3** [comment]
Sorry, not able to reproduce on demo.pimcore.fun 
![image](https://github.com/pimcore/pimcore/assets/5137917/5edcc900-4a93-4f9f-be14-9a9766309775)

**Comment by alexej-d** [comment]
Please check @dvesh3 https://demo.pimcore.com/admin/. Here is a screen capture: https://drive.google.com/file/d/1Wjn7mJjFYIxtbl6E5VtMdo5KvfekCk9-/view?usp=sharing

**Comment by dvesh3** [comment]
@alexej-d thanks for sharing the recording. It seems rendering issue as the source code looks fine 
![image](https://github.com/pimcore/pimcore/assets/5137917/133747ce-651b-4876-b1e6-8940755df266)

**Comment by alexej-d** [comment]
@dvesh3 what do you mean with rendering issue? The new HTML Code is not persisted to the DB. You can see in my recording that I open the code view and the area I fattened is not bold anymore after reloading, so this is clearly not a simple rendering issue 😄 

FYI: I am using Chrome on Mac OS.

**Comment by robertSt7** [comment]
@alexej-d I think the problem is the `font-family`, because with `italic` it works. Could you may please try to reproduce it with `italic`? Thanks

**Comment by alexej-d** [comment]
@robertSt7 it appears the newest Chrome version fixed this, so I cannot reproduce the bug anymore 👍
