### ISSUE TITLE
[Bug]: TinymceBundle defaultEditorConfig is ignored

### ISSUE THREAD

**Issue by GALPR** [pimcore/pimcore#16061]
### Pimcore version

11.0.11

### Steps to reproduce

- Specify a default WYSIWYG configuration (`pimcore.documents.editable.wysiwyg.defaultEditorConfig`)
- Add a WYSIWYG editable to a document
- At this time the specified config is correctly loaded
- Reload the document (Pimcore internal reload)
- At this time the default config is ignored

### Actual Behavior

The value of `defaultEditorConfig` is `undefined` after a document reload.

### Expected Behavior

The value of `defaultEditorConfig` is correctly loaded even after a document reload.

I found out that [this change](https://github.com/pimcore/pimcore/pull/15701) started causing this issue for me.

**Comment by fracsi** [comment]
Current workaround: https://github.com/pimcore/admin-ui-classic-bundle/issues/294#issuecomment-1737181744

**Comment by robertSt7** [comment]
Hi @GALPR and @fracsi, sorry I am not able to reproduce this. Are you loading the JS file with this event?
https://github.com/pimcore/pimcore/blob/f5cd2e82a7b6faf89688e734ca60bee2bc1f7a24/lib/Event/BundleManagerEvents.php#L55

**Comment by GALPR** [comment]
Yes, that is exactly what I am using.  
Inside the JS file that I load via this event I reassign `pimcore.document.editables.wysiwyg.defaultEditorConfig` but this doesn't seem to work.

**Comment by fracsi** [comment]
@robertSt7 
For me it works, and the linked comment is how i use it.

**Comment by robertSt7** [comment]
@GALPR Have you also added this line before ? `pimcore.document.editables.wysiwyg = pimcore.document.editables.wysiwyg || {};`

**Comment by GALPR** [comment]
yes, I don't get any console errors

**Comment by GALPR** [comment]
I am so sorry. After further analyzing the problem I noticed that this is not a Pimcore issue. It did not work because of a weird race condition we had.

**Comment by robertSt7** [comment]
@GALPR No problem. Thanks for closing the issue
