### ISSUE TITLE
[Bug]: Memory issue with cache:clear

### ISSUE THREAD

**Issue by mattamon** [pimcore/pimcore#16068]
### Pimcore version

11.0 - 11.x

### Steps to reproduce

1. Checkout demo-enterprise version
2. Install pimcore
3. Add/install as many bundles as possible / also maybe new ones that are not published yet
4. Try to clear cache bin/console cache:clear

Memory limit is set to 256MB

### Actual Behavior

A memory error is thrown while cache clear

![image](https://github.com/pimcore/pimcore/assets/38959016/2a5111fa-d364-4dea-a67f-9834c2a6bd15)

### Expected Behavior

No errors should appear and the cache should be cleared.

**Comment by brusch** [comment]
I'm not sure if this can be even improved, or if it just needs that much memory, in cases where you have a lot of classes ... 🤔 

In such cases, you probably need to run the command with additional flags to increase the memory, e.g. `php -d memory_limit=128M bin/console cache:clear ...`

**Comment by cipribucur** [comment]
then why not increase the memory in the docker image to a value where all the pimcore commands can run without this problem? with the demo data inside.

**Comment by fashxp** [comment]
docker container cannot know what bundles will be installed and what files need to be loaded...

**Comment by dpfaffenbauer** [comment]
Installing all Enterprise Bundles is a Enterprise worthy installation that should be manually configured, or at least given more memory in general. It might need more memory anyway for eg. Frontend Applications.

**Comment by mattamon** [comment]
@dpfaffenbauer In general I agree with you, but in this case it is bad memory management, since in `cache:clear` around 700+ pimcore classes are loaded unnecessarily, causing the memory issue. 
In my PR https://github.com/pimcore/pimcore/pull/16069 you can see that the Preloader actually already takes care of loading the classes, so we do not need to do it in Cache warm up and therefore in the `cache:clear`.

**Comment by dvesh3** [comment]
Fixed by #16069
