### ISSUE TITLE
[Bug]: users.lastLogin is not updated

### ISSUE THREAD

**Issue by picman** [pimcore/pimcore#16076]
### Pimcore version

11.0.11

### Steps to reproduce

Log in to Pimcore Admin interface.

### Actual Behavior

Database column `users.lastLogin` remains unchanged.

### Expected Behavior

Database column `users.lastLogin` is updated with the current timestamp.

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16131

**Comment by picman** [comment]
Thank you!
