### ISSUE TITLE
[Bug]: child is not inherting the parent object many-to-one relation field

### ISSUE THREAD

**Issue by abhiramalli** [pimcore/pimcore#16071]
### Pimcore version

11

### Steps to reproduce

create one class which includes the many-to-one relation; and make class as inhirtable

create parent object add the relation field and save
 and try to create child object for above parent 

### Actual Behavior

child is not inheriting the parent objects many-to-one  relation field
it is saving as null for field_id and type field in object_query_table
![image](https://github.com/pimcore/pimcore/assets/85212799/c1b8b498-330c-4b9b-b81c-31982260a1cd)
i have checked in the demo same issue is reproducable
after debugging i found issue
is in vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
getDataForQueryResource method which is returning null instead of array with keys and empty value to Dao for saving parents data in child
![image](https://github.com/pimcore/pimcore/assets/85212799/7ec13498-d293-4304-a3e6-7621be20d11d)

it will work fine if i make changes like below
![image](https://github.com/pimcore/pimcore/assets/85212799/802228fc-be7c-4a5c-afd0-5ad774fcd31b)

### Expected Behavior

child should inherit the parents relation type
and in db object_query_classId the field of reation should save

**Comment by abhiramalli** [comment]
@dvesh3  any updates about this??

**Comment by dvesh3** [comment]
@abhiramalli thanks for the suggested fix. I have created a PR #16095

**Comment by dvesh3** [comment]
Fixed by #16095
