### ISSUE TITLE
[Bug]: Unable to select options in the thumbnail dropdown

### ISSUE THREAD

**Issue by aryaantony92** [pimcore/pimcore#16088]
### Pimcore version

11.0.11

### Steps to reproduce

- Go to an asset
- Try to select the predefined option from the dropdown to download the thumbnail

![image](https://github.com/pimcore/pimcore/assets/97134765/611eed2d-22b7-4c10-bc7e-84bbcbcee77c)

### Actual Behavior

When it's clicked on the drop down, options are only visible for a second

### Expected Behavior

Should be able to select a predefined option from the drop down.

**Comment by dvesh3** [comment]
@aryaantony92 Did you enable it here?
![image](https://github.com/pimcore/pimcore/assets/5137917/93ba7f7a-e378-4726-8aca-8073da400837)

**Comment by aryaantony92** [comment]
@dvesh3 No, I missed it. Thanks, it's working now.
