### ISSUE TITLE
[Bug]: keybinding_ translations missing

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#16094]
### Improvement description

Pimcore 11.0.11

All `keybinding_`translations are missing. please see https://github.com/pimcore/pimcore/pull/14069#issuecomment-1759493977

Regression of #14069

**Comment by blankse** [comment]
Duplicate of https://github.com/pimcore/admin-ui-classic-bundle/issues/237

**Comment by dvesh3** [comment]
Ohh, I didn't rem this one. thanks!
