### ISSUE TITLE
[Bug]: Locale Fallback is not considered during language selection

### ISSUE THREAD

**Issue by hethehe** [pimcore/pimcore#16090]
### Pimcore version

11.x

### Steps to reproduce

Define a admin language e.g. de_CH but do not provide a translation file for this locale.
Try to select this language in the Pimcore back-end user interface.

Some more information:
This PR added a fallback logic from country specific locales to primary language: https://github.com/pimcore/pimcore/issues/14092
The language selection still checks for a existing translation file but does not consider the fallback.

PR is on the way.

### Actual Behavior

Locale Fallback is not considered during language selection

### Expected Behavior

Locale Fallback is considered during language selection

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16093

Thank you for reporting an the PR
