### ISSUE TITLE
Add conflict for pimcore/admin-ui-classic-bundle < 1.2

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#16107]
### Improvement description

Add to composer.json
```json
"conflict": {
    "pimcore/admin-ui-classic-bundle": "<1.2"
  },
```

**Comment by brusch** [comment]
@dvesh3 what is the reason for this? If there's something breaking that requires a newer version, it would require a major version, right? 😬

**Comment by brusch** [comment]
> @dvesh3 what is the reason for this? If there's something breaking that requires a newer version, it would require a major version, right? 😬

@robertSt7 can you maybe help out? 😊

**Comment by jdreesen** [comment]
I'd guess that `v1.2` has features that will be used in Pimcore `11.1`, so it's the new minimum version. 
But `pimcore/admin-ui-classic-bundle` is not in Pimcore's require section, so we can't just set it to `^1.2`.
