### ISSUE TITLE
[Bug]: Download assets issue

### ISSUE THREAD

**Issue by axessandro** [pimcore/pimcore#16110]
### Pimcore version

11.0.5

### Steps to reproduce

Download filename issue
Having an asset with filename “ASSET 1.jpg” when we download from portal engine frontend, backend original file or backend with thumbnail we have 3 different filenames

There is a way to get the same filename in all 3 methods?

### Actual Behavior

Portal engine frontend: “ASSET%201.jpg”
Backend original file: “ASSET 1.jpg”
Backend with thumbnail: “asset 1.jpg”

### Expected Behavior

Portal engine frontend: “ASSET 1.jpg”
Backend original file: “ASSET 1.jpg”
Backend with thumbnail: “ASSET 1.jpg”

**Comment by dvesh3** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/354 & https://github.com/pimcore/portal-engine/pull/462
