### ISSUE TITLE
Workspace Permission Analyzer

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#1612]
Allowing you to drop a resource and a user...

Tool should tell you which permissions the user would have for that resource +give you a hint which user/role workspace settings is relevant.

**Comment by weisswurstkanone** [comment]
build 68

**Comment by Yivan** [comment]
It seems a great tool! Thanks @weisswurstkanone 
I didn't test it for now but just two point:
- maybe "Username" or "User" would be better than "Name" in the grid label (it take me some times to undestand the name of what it was ; )).
- Is there grid filtering ? It would be top notch as we can directly filter to see wich user can LIST AND VIEW the folder for instance (by filtering LIST "yes" and VIEW "yes", like the filter for object grid wich are cumulative).

I know it is not linked to this task, but as you are working on permission, maybe it is a good time to work on two bug which impact some project in production:

- https://github.com/pimcore/pimcore/issues/1000: picmore users ask us why those buttons don't works or are there ; )
- https://github.com/pimcore/pimcore/issues/993: more important i think, a security issue wich can lead to give access to some data to user which are not intended.

Thanks.

**Comment by weisswurstkanone** [comment]
* Changed header label to "Username"
* string filter for username
* yes/no filter for permission

build 72
