### ISSUE TITLE
[Pimcore4] Object grid listing: resizing column don't display the save configuration icon.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1614]
In the object grid listing, size width of the column seems saved along the field displayed.
But the icon to save grid configuration is only displayed when a field is added or remove (or at least the "apply" button on the field selection popin is clicked).

The save configuration icon should be displayed if column are resized so user can save the actual columns size configuration.

**Comment by weisswurstkanone** [comment]
build 4088
