### ISSUE TITLE
[Bug]: Thumbnails don't preserve profile color and meta datas

### ISSUE THREAD

**Issue by axessandro** [pimcore/pimcore#16148]
### Pimcore version

11.0.5

### Steps to reproduce

- Update an asset with meta data and profile color;
- Create thumbnail and check "Preserve Color" and "Preserve meta data" fields;
- Add a background.

Download asset with thumbnail already created 

Without set background color, the image maintain datas and profile color

### Actual Behavior

Downloaded image doesn't maintains color profile and meta datas

### Expected Behavior

Download image maintains datas and profile color

**Comment by kingjia90** [comment]
> Without set background color, the image maintain datas and profile color


This might be a known limitation/issue, there's a  “fine prints” in the UI that warns about it
![image](https://github.com/pimcore/pimcore/assets/6014195/18363739-0fda-445d-ad60-e550b28bb725)

('Preserve meta data' and 'preserve color' `only works` for transitions `without` compositions (frame, `background color`, ...)
