### ISSUE TITLE
[Bug]: Portal Engine - Statistic Explorer deny permission

### ISSUE THREAD

**Issue by axessandro** [pimcore/pimcore#16149]
### Pimcore version

11.0.5

### Steps to reproduce

I can't deny user access to _Statistic Explorer_ page

- Create a Portal, user and user group
- In user group deny permission to "Statistic Explorer" and set user permission on Deny or Inherit

### Actual Behavior

User is still able to access this page

### Expected Behavior

User can't access to this page

**Comment by fashxp** [comment]
already fixed with portal engine version 3.1.3
