### ISSUE TITLE
[Bug]: pimcore_enterprise_subscription_tools flag "production_system" not working

### ISSUE THREAD

**Issue by pcwiecek** [pimcore/pimcore#16156]
### Pimcore version

10.6.9

### Steps to reproduce

Log in to the panel and click on the enterprise icon 

### Actual Behavior

Since Wednesday, the verification server has stopped recognizing the test environment from the prod. It treats all environments as PROD environments by displaying the error "Multiple production instances"

### Expected Behavior

The authorization server should detect the type of environment by the production_system flag

**Comment by fashxp** [comment]
Hi, 
please contact your contact person at Pimcore or raise a ticket via enterprise-support(at)pimcore.com 
and share the details.
Thanks...
