### ISSUE TITLE
[Bug]: Migrate object_metadata schema to have a auto increment column fails

### ISSUE THREAD

**Issue by ascheider** [pimcore/pimcore#16155]
### Pimcore version

11.1.0

### Steps to reproduce

Updating from pimcore 10 and run bin/console doctrine:migrations:migrate -n
The migration Version20230616085142 fails with error: 
 An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1553 Cannot drop index 'PRIMARY': needed in a foreign key constraint 
![image](https://github.com/pimcore/pimcore/assets/6016485/3f42eca5-2516-4daa-8ad5-af891169a64d)
MySQL: 8.0.30 

### Actual Behavior

I migrate from pimcore 10 to 11 and get errors

### Expected Behavior

I want to migrate from pimcore 10 to 11 without errors

**Comment by dvesh3** [comment]
@ascheider Did you run migrations on 10.6 before upgrading to v11?

**Comment by ascheider** [comment]
@dvesh3 I upgraded from 10.5.23 to 11.1 via composer and run migrations.

**Comment by dvesh3** [comment]
It is a required step to run upgrade to 10.6 and run migrations before upgrading from v10 to v11. Please see https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/Updating_Pimcore/Preparing_for_V11

**Comment by dvesh3** [comment]
Please see https://github.com/pimcore/pimcore/issues/16155#issuecomment-1785478277
