### ISSUE TITLE
[Bug]: Filtering for tags with option `Consider child tags too` does not work

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#16169]
### Pimcore version

11

### Steps to reproduce

- Open object search
- Filter for tag `countries`
- Activate `Consider child tags too`

![image](https://github.com/pimcore/pimcore/assets/8792145/66c263de-1a0a-4516-96bb-fc47eaa0e69c)

### Actual Behavior

Error message

### Expected Behavior

No error message

**Comment by dvesh3** [comment]
Fixed by #16190
