### ISSUE TITLE
[Task]: Fix PR checklist action 

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#16163]
### Improvement description

https://github.com/pimcore/pimcore/blob/a52dc8ff829938e766997f8be5b208f5397083a6/.github/workflows/pull-request-checklist.yaml#L19

See also https://github.com/pimcore/pimcore/pull/16162#issuecomment-1782815430

**Comment by blankse** [comment]
It exists already a PR for this: https://github.com/pimcore/pimcore/pull/16153

**Comment by kingjia90** [comment]
Ah great, thank you! 👍🏻
