### ISSUE TITLE
[Bug]: MaintenanceModeHelperInterface Error after Update from 11.0.9 to 11.1.0

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#16161]
### Discussed in https://github.com/pimcore/pimcore/discussions/16158

<div type='discussions-op-text'>

<sup>Originally posted by **Fabian-Hofer-Mastertent** October 27, 2023</sup>
Hello Community,

I updated Pimcore from 11.0.9 to 11.1.0 (pimcore/admin-ui-classic-bundle to 1.2 at the same time) but get this error after the composer update:

`Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException {#350
  #message: "You have requested a non-existent service "Pimcore\Tool\MaintenanceModeHelperInterface"."
  #code: 0
  #file: "./vendor/symfony/dependency-injection/Container.php"
  #line: 264
  -id: "Pimcore\Tool\MaintenanceModeHelperInterface"
  -sourceId: null
  -alternatives: []
  trace: {
    ./vendor/symfony/dependency-injection/Container.php:264 { …}
    ./vendor/symfony/dependency-injection/Container.php:212 { …}
    ./vendor/pimcore/pimcore/lib/Console/Application.php:68 { …}
    ./bin/console:38 {
      {closure}
      ›
      ›     return new Application($kernel);
      › };
    }
    ./vendor/autoload_runtime.php:24 { …}
    ./bin/console:20 { …}
  }
}`

I don't understand what the problem could be in this situation because the files and classes seem to be at the right place.

there was a update on the MaintenanceModeHelper as i saw at #15954 in version 11.1.0. Migth there be an issue with this update?</div>

**Comment by ascheider** [comment]
@kingjia90 Had the same issue. Remove cache folder completely, should work afterwards

**Comment by kingjia90** [comment]
Thank you @ascheider ! 
@Fabian-Hofer-Mastertent please check if the hint about removing cache folder would help

**Comment by Fabian-Hofer-Mastertent** [comment]
@kingjia90 thank you, removing the cache folder resolved the issue!

**Comment by kingjia90** [comment]
Great! Then, i'm closing the issue here.
@ascheider if possible, please write the solution there https://github.com/pimcore/pimcore/discussions/16158 and will mark as answer

**Comment by StefanRickli** [comment]
To spare others the confusion, I had to remove `project_root/var/cache/env_name` and not `project_root/cache`.
