### ISSUE TITLE
New feature: custom namespace for Pimcore object

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1617]
I think this new feature would make too much change in the code, but i would like to propose it, maybe for latter or if not so difficult for Pimcore 5.

All generated Pimcore object classes get the same namespace: `Pimcore\Model\Object`
Sometime we need same class name, but in different namespace, ensentially in multiple website/module/bundle configuration.

For instance:
Having one Pimcore for several website. Each website has a news system wich are pretty different and need to have their own Pimcore object for each website.
Actually, a way to do this is to give a classname for the object depending the website/module:

- newsSite1
- newsSite2
...

Having namespace will be more clean and modern:

- site1\news
- site2\news
...

I think it will be too difficult to implement and making serious change, but i would like just to share this idea of improvement. Maybe you know some doable way not so much difficult.

**Comment by dpfaffenbauer** [comment]
Why don't you just add a Site field to your News Object and query on that? I always make it this way. 

This change would break BC as well.

**Comment by Yivan** [comment]
Yes that is something we do too like a select field (site1, site2, ...) in the object class.
It works great if news have the same structure.

This issue is more about having two news object classes (differently structured, which cannot be same object/class), but the need to have the same name on different bundle/module.
Another exemple could be having different Customer or Product class on multi website (it can happen if websites haven't been thinked at a "all" because one was made several year ago, etc.)

Yes i think like you said it will break BC totally and increase complexity. But as core developper have a better vision of the way to implement it maybe there is some more easy approach...

Exemple:

- On the backend GUI class editor: adding a namespace text field in the base class configuration
- It will change generated php class by using this namespace (like: \Pimcore\Model\Object\MyNamespace or \MyNamespace...), but always extending \Pimcore\Model\Object\Concrete

If no namespace is filled, it won't break any BC. If namespace filled... i don't know the implication.
With this we can call:
\Pimcore\Model\Object\MyNamespace\MyClassName:: getById for instance, etc.
(or maybe: \MyNamespace\MyClassName:: getById for instance, etc.).

But the more i think about the implication, the more i think it will need to much work (all backend GUI will need to handle this namespace when we display the class name to unambiguate them... and this is on many places on the administration backend!).

So if this idea is bad, this issue can be closed ; ) If something is good it can be keep ; )
