### ISSUE TITLE
Improvement: extending list and traits for list

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1618]
Like object, objectList could be extended the same way and having the possibility to use traits on them too:

![list-object](https://user-images.githubusercontent.com/9025839/27331786-37c02a44-55bf-11e7-9a5e-728f8c1219b8.png)

Fill those two new fields will generate the classList file (`listing.php` in `website\var\classes\Object\...`) based on this.

This way we could have true inheritence available if needed (sometimes DI is not sufficient).

**Comment by fashxp** [comment]
why not use overriding models functionality for that? 
https://pimcore.com/docs/5.x/Development_Documentation/Extending_Pimcore/Overriding_Models.html

**Comment by Yivan** [comment]
@fashxp yes for sure, we can overide the model.
But using override is less powerfull as it is only active at run time (using static method like `::getList()`).
But if you use the classic:
`$objectList = new Pimcore\Model\DataObject\MyClass\Listing();`
You don't have the possibility to have any extend/traits.

Actually, the only way is like you said overide the model list and call the new class which override: `new AppBundle\Model\DataObject\MyClass\Listing();`
Problem is if it is an existing project it needs code refactoring : ( and even for new project developpers generally prefer to call directly the pimcore class name (not the overiding one).

To resume, having those two new field would allow a proper extending directly in the model objectList generated by Pimcore (like it is for object).

If i am not wrong, I think this is a really valuable addition and this issue should be reopen please.
And i think it is pretty straightforward to implement (two new extjs fields for the class, no db change, and adding the value of those field in the generated list class, exactly like it is done for object class).

If you are ok to implement it, I can prepare a pull request if you want.

Thanks a lot.

**Comment by fashxp** [comment]
yes, that would be great!
