### ISSUE TITLE
[Bug]: Breadcrumbs navigation doesn't show all pages

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#16183]
### Pimcore version

11.1.0

### Steps to reproduce

Create a new project as described here: https://github.com/pimcore/pimcore#getting-started
In the frontend, go to a subpage with depth 2 or deeper, for example "/en/More-Stuff/Demo-Features/Data-Quality".

The Problem is located in the file /vendor/pimcore/pimcore/lib/Navigation/Renderer/AbstractRenderer.php at line 233.
Should be `if (is_int($maxDepth) && $foundDepth > $maxDepth) {` instead of `if ($foundDepth > $maxDepth) {`

### Actual Behavior

Only one page is displayed in breadcrumb. In this example "More Stuff"

![pimcore_breadcrumb_bug](https://github.com/pimcore/pimcore/assets/149571567/31884f77-a564-4701-9006-b4d9355da13d)

### Expected Behavior

The whole Pagetree should be displayed in breadcrumb. In this example "More Stuff > Demo-Features > Data-Quality"

![pimcore_breadcrumb_bug_target](https://github.com/pimcore/pimcore/assets/149571567/f7698880-434a-465c-9a71-b8c259075426)

**Comment by dvesh3** [comment]
@kkwa-hd thanks for the report. Can you please provide a PR? since you already know the fix :wink:

**Comment by kingjia90** [comment]
Thank you! 

Fixed by https://github.com/pimcore/pimcore/pull/16189
