### ISSUE TITLE
[Bug]: CORS Issue with snippets in editmode when two different sites are used

### ISSUE THREAD

**Issue by BranchJedi** [pimcore/pimcore#16192]
### Pimcore version

10.6.9 and 11.1.0

### Steps to reproduce

1. Set up site with domain demo.pimcore.fun and another site with the domain demo2.pimcore.fun

![1-page-setup](https://github.com/pimcore/pimcore/assets/25201222/d4e88697-7981-4eb7-92ec-f305b906eaa1)

2. Add page test to demo2.pimcore.fun
3. Add standard teaser snippet named test to demo2.pimcore.fun

4. Add snippet test to test page

![4-drag- -drop-snippet-into-teaser](https://github.com/pimcore/pimcore/assets/25201222/32d1a411-cf30-421f-b587-dc408d97cc91)

5. Save and publish page
6. Reload page

### Actual Behavior

When reloading the page, the snippet does not show.

![7-snippet-will-not-be-shown](https://github.com/pimcore/pimcore/assets/25201222/cb388e81-e4b4-46fa-84ee-41daf8eb7ba7)

You'll see a CORS error message when trying to load snippet.

![8-cors-message-in-console](https://github.com/pimcore/pimcore/assets/25201222/3bc276e3-5c0d-4186-96cc-bcfdb8cd0aba)

As you can see, the snippet is loaded with host demo2.pimcore.fun instead of demo.pimcore.fun which results in a CORS error. Changing CORS headers doesn't do anything because the preflight is already done at this point.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSPreflightDidNotSucceed

### Expected Behavior

Being on https://demo.pimcore.fun I want to see snippets added on site demo2.pimcore.fun.

![6-reload-page](https://github.com/pimcore/pimcore/assets/25201222/2361b3c8-3ca2-48e2-9d3b-2b52e72aa82a)

**Comment by dvesh3** [comment]
Fixed by https://github.com/pimcore/pimcore/commit/f999d3740c4afd0837811d48e63fad816f705995
