### ISSUE TITLE
[Bug]: Add support for decorating LocaleService again

### ISSUE THREAD

**Issue by studio1gmbh-pimcore** [pimcore/pimcore#16215]
### Improvement description

Decorating the [LocaleService](https://github.com/pimcore/pimcore/blob/11.x/lib/Localization/LocaleService.php) can be used to add new languages to Pimcore. In the current state this is not possible because in some places Pimcore uses the concrete Service instead of the [LocalServiceInterface](https://github.com/pimcore/pimcore/blob/11.x/lib/Localization/LocaleServiceInterface.php).

In the past this problem was already solved by https://github.com/pimcore/pimcore/pull/3021 but in preparation of Pimcore 11 (https://github.com/pimcore/pimcore/pull/13474) new type delcarations were added and now the concrete `LocaleService` is used again, which makes the decoration impossible.

**Comment by blankse** [comment]
@studio1gmbh-pimcore I created a PR https://github.com/pimcore/pimcore/pull/16216
Can you test it?

**Comment by studio1gmbh-pimcore** [comment]
@blankse Thank you, I already testet locally and can confirm that it works. 

fyi: following bundles are affected too, are you planing to update these too?

* [pimcore/admin-ui-classic-bundle](https://github.com/pimcore/admin-ui-classic-bundle/blob/a4f807ed2f05653524e298485325df9c102dc200/src/Controller/Admin/Document/PageController.php#L390)
* [pimcore/portal-engine](https://github.com/pimcore/portal-engine/blob/51d26fafe85fa613408049c71412200df7454e81/src/Service/Rest/Api/DataObject/DetailHandler.php#L62)
* [pimcore/translations-provider-interfaces](https://github.com/pimcore/translations-provider-interfaces/blob/11abded41a88d93eef6241ab185d4786779eca29/src/DataChangedHandler/DataChangedHandler.php#L30)

**Comment by blankse** [comment]
@studio1gmbh-pimcore I created also a PR for https://github.com/pimcore/admin-ui-classic-bundle/pull/339
For the other repositories I haven't access.

**Comment by studio1gmbh-pimcore** [comment]
@blankse perfect, thank you! 

@dvesh3 any chance you guys fix it in the enterprise bundles too, in the near future?

[pimcore/portal-engine](https://github.com/pimcore/portal-engine/blob/51d26fafe85fa613408049c71412200df7454e81/src/Service/Rest/Api/DataObject/DetailHandler.php#L62)
[pimcore/translations-provider-interfaces](https://github.com/pimcore/translations-provider-interfaces/blob/11abded41a88d93eef6241ab185d4786779eca29/src/DataChangedHandler/DataChangedHandler.php#L30)

**Comment by dvesh3** [comment]
@studio1gmbh-pimcore @blankse thank you for the fix and yes, we'll cover this in the enterprise bundles when merged in the core and admin bundle.
