### ISSUE TITLE
[Improvement]: put Pimcore description on Symfony website in category CMS

### ISSUE THREAD

**Issue by kaurov** [pimcore/pimcore#16224]
### Improvement description

Today 08.11.2023 I see nothing about Pimcore on https://symfony.com/projects/category/cms
I believe it is worth of adding it.

**Comment by dvesh3** [comment]
It is there under "PIM & CRM" category https://symfony.com/projects/category/pim-crm. I'm not sure if you can define multiple categories for a project.

**Comment by kaurov** [comment]
even if so -- what prevent you from creation of project named a bit
differently, like PimcoreCMS instead Pimcore with a link to main website?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
11/10/23,
06:54:15 PM
Remove

**Comment by kingjia90** [comment]
Thank you!

Closing as this might not concerning the code, would forward this input to our Head of Dev&Product
