### ISSUE TITLE
Run tests (PhpStan & Codeception) with latest Symfony dev-version (currently 6.4-dev)

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#16222]
### Improvement description

Currently we're running just 6.3-dev against PhpStan, but we should always use the latest dev version and also test against Codeception tests.

**Comment by fashxp** [comment]
@herbertroth we need to do that ASAP. 
now we have already the situation that pimcore is not compatible with symfony 6.4 anymore

**Comment by kingjia90** [comment]
Resolved by https://github.com/pimcore/pimcore/pull/16445
