### ISSUE TITLE
Import function for assets

### ISSUE THREAD

**Issue by Armin-Rabensteiner** [pimcore/pimcore#16244]
### Feature description

I have a website with many images and languages, so there are always a lot of alt and title tags to enter in the different languages.

There is already an export that allows you to export all images to excel and then edit the desired fields (for example, all alt fields in all languages).
However, an import would be helpful, then you could export all images - enter all alt and titles in excel for the corresponding image and then import them again.
After the import, all images should be filled correctly and you don't always have to open each image separately to fill the various fields.

Then you would not always have to edit all images separately in all languages, but you could go through the list in excel and then import it again.

What do you think?

**Comment by NiklasBr** [comment]
https://github.com/pimcore/data-importer?

**Comment by Armin-Rabensteiner** [comment]
Thank you @NiklasBr for your tip.
We have now programmed something of our own that helps us to implement the desired behaviour :)
