### ISSUE TITLE
Tmp-file cleanup: skip if temporary directory doesn't exists

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#1624]
The maintenance cli command throws exceptions like this:

```php
UnexpectedValueException: RecursiveDirectoryIterator::__construct(/home/customerdataframework/www/web/var/tmp): failed to open dir: No such file or directory in /home/customerdataframework/www/pimcore/lib/Pimcore/Tool/Housekeeping.php:24
```
Shouldn't the constant PIMCORE_TEMPORARY_DIRECTORY point to PIMCORE_PRIVATE_VAR instead of PIMCORE_PUBLIC_VAR?

**Comment by brusch** [comment]
`PIMCORE_TEMPORARY_DIRECTORY` is still fine - it points to the public temporary directory, so it is a subdirectory of `PIMCORE_PUBLIC_VAR`. 

https://github.com/pimcore/pimcore/blob/8b32223cc18d154fbfab0a69bee0c3fb564fccdd/pimcore/config/constants.php#L90-L90

**Comment by markus-moser** [comment]
Ok, but why do I get the above exception? When I manually create the tmp folder then the first call of the maintenance works but then the directory gets deleted and I receive the exception again.

**Comment by brusch** [comment]
Added missing check in house-keeping job - thanks!
