### ISSUE TITLE
[Bug]: Custom tooltip for dataobject not working

### ISSUE THREAD

**Issue by Lars77** [pimcore/pimcore#16264]
### Pimcore version

11.0.12

### Steps to reproduce

Wanted to implement custom tooltip for project class as described in https://pimcore.com/docs/platform/Pimcore/Tools_and_Features/Custom_Icons. Implemented EventListener (updated services.yaml), implemented AdminStyle class.

### Actual Behavior

default tooltip is shown

### Expected Behavior

custom tooltip is shown

**Comment by fashxp** [comment]
@Lars77  are you using Data Quality Management bundle?

**Comment by Lars77** [comment]
Yes, Data quality management bundle is required.

**Comment by fashxp** [comment]
can you try with version 1.1.1 of data quality management bundle. should fix it.

**Comment by Lars77** [comment]
Hello, sorry for my late respone. I can't update to this version, because ``pimcore/platform-version v2023.2 conflicts with pimcore/data-quality-management-bundle v1.1.1``. But anyway, we use DataDirector Bundle for custom tooltips instead.

**Comment by fashxp** [comment]
Thx for your response. You could savely update to platform-version 2023.3
