### ISSUE TITLE
[Bug]: Cache has concurrency problems

### ISSUE THREAD

**Issue by lukadschaak** [pimcore/pimcore#16266]
### Pimcore version

10, 11

### Steps to reproduce

In high-load scenarios where many requests are sent directly after another and the same object is loaded and saved in every request, it can happen, that incorrect objects are used.

For example during the purchase process in CoreShop with the Payum bundle, several redirects are send and received between the browser and server. With each request, the order is loaded and saved again and written to the cache accordingly.

The fact that the cache is only flushed in the kernel terminate can lead to concurrency.
* Browser sends request 1 loads and saves order
* Request 1 is terminated and response 1 is sent
* Response 1 is received and processed in the browser
* Browser sends request 2
* Request 2 loads order < wrong object
* Cache of request 1 is saved

In Coreshop there is also an issue from me: https://github.com/coreshop/CoreShop/issues/2399
There was also a first workaround there in which orders are simply never cached. A response listener deletes the order entries from the Pimcore cache handler so that they never end up in the cache: https://github.com/dpfaffenbauer/CoreShop/commit/7c936189d141d07b4968d1b8b9f11c83aed3b20a

We use Pimcore 10.5.*, Coreshop 3.1.0 and use Redis as cache server.

Any ideas for possible solutions?

### Actual Behavior

Wrong objects may be loaded

### Expected Behavior

The correct (latest) object is loaded.

**Comment by ghost** [comment]
@lukadschaak Hi, sorry, but it's not reproduceable for us. Please refer to https://github.com/pimcore/ee-pimcore/blob/d16f5632ecd50b56f8c600e169d83166b5fbdd81/lib/Cache/Core/CoreCacheHandler.php#L462 for further guidance. Thanks!

**Comment by NiklasBr** [comment]
![Screenshot 2023-12-07 at 11 55 02](https://github.com/pimcore/pimcore/assets/279826/e91250b7-2279-4486-af18-1df82e0d510d)

**Comment by brusch** [comment]
@NiklasBr Sorry: https://github.com/pimcore/pimcore/blob/11.x/lib/Cache/Core/CoreCacheHandler.php#L462 😉

**Comment by dpfaffenbauer** [comment]
The Problem comes down to how Pimcore serializes for Cache with DeepCopy. If you add Doctrine ORM to the mix, a Cache Entry can be more than 1MB. (since DeepCopy recursively copies everything, also triggering DB Requests from Dcotrine Relations). Then you get a race condition: The Cache entry gets generated in the shutdown in the meantime the new Request loads the old Cache Entry since the shutdown of the previous request is not finished yet.
 
DeepCopy is super inefficient in what it does. Pimcore should have a proper serializer to handle this things. Also for eg. Versioning. DeepCopy is the wrong tool for that.

**Comment by brusch** [comment]
I think at least an improvement would be to move this part here: 
https://github.com/pimcore/pimcore/blob/11.x/lib/Cache/Core/CoreCacheHandler.php#L462-L470
after the serialization happened, so just before writing to the cache with `$this->pool->save($item);`: 
https://github.com/pimcore/pimcore/blob/11.x/lib/Cache/Core/CoreCacheHandler.php#L504

**Comment by brusch** [comment]
But with that, it could be that we do the extra effort of serializing data that actually doesn't go to the cache 🤔 But still better than having corrupted data ... 
Anyone wants to create a PR?

**Comment by dpfaffenbauer** [comment]
@brusch What are you saying? It has nothing todo with`__isBasedOnLatestData` and nothing with corrupted data. Cache serialization just takes to long with DeepCopy so the next request gets the "old" cached data. Which is not corrupted nor not __isBasedOnLatestData. It just hasn't been serialized and stored yet. Race Condition.

**Comment by brusch** [comment]
Ah got the point - Sorry ☺️

**Comment by fashxp** [comment]
But isn't it the case, that as soon as any data object is updated in a request it is never written into the cache in that same request but just removed from cache? 

If that is the case, the concurrency problem would be because the object is loaded from cache by request 2, because request 1 didn't cleared the cache yet ... which means faster serialization would not make a difference...

**Comment by dpfaffenbauer** [comment]
@fashxp nope, items are written to cache regardless if something changed.

> If that is the case, the concurrency problem would be because the object is loaded from cache by request 2, because request 1 didn't cleared the cache yet ... which means faster serialization would not make a difference...

True. Practically though it made a difference. But yes, there might still be cases. If Pimcore would clear data that has been changed, it might even work better.

**Comment by fashxp** [comment]
@dpfaffenbauer 
Hmm, I didn't run the debugger now, but from reading code I would say: 
- On every save of e.g. a data object, the depending cache is cleared [here](https://github.com/pimcore/pimcore/blob/11.x/models/DataObject/AbstractObject.php#L615). 
- This ends up in clearing tags and activating a write lock [here](https://github.com/pimcore/pimcore/blob/11.x/lib/Cache/Core/CoreCacheHandler.php#L579) - and this is done synchronously. 
- That write lock is checked when writing the cache queue and if write lock is set, nothing is written to the cache, see [here](https://github.com/pimcore/pimcore/blob/11.x/lib/Cache/Core/CoreCacheHandler.php#L779)

So, if nothing interferes there, no cache item should be written in the same request when a data element (asset, data object, document) is updated. Affected cache items are just cleared from the cache - and this is done before request returns. 
At least from what I see here, the scenario described in that issue should not happen. 

Maybe you can double check that on your end. Thx...

**Comment by dpfaffenbauer** [comment]
@fashxp Yes, that is right.

So this is whats going on:

 - Request 1 loads the Cart from DB and saves it to cache
 - Request 2 loads the Cart from Cache and clears it on save
 - Request 3 loads the Cart from DB and saves it to cache
 - Request 4 loads the Cart from Cache and clears it on save

But then I cannot get my head around how an request can get old cache items. We introduced a fix for the cache performance in general, but still without that, the second request either gets it right from the cache or right from the db. 

We should keep an eye on that, we clearly had issues with it, so there is something wrong. But nothing I can re-produce now easily.

**Comment by fashxp** [comment]
Ok, so for now I'll close that issue. Feel free to collect your findings here and we reopen when we have something to reproduce.

**Comment by lukadschaak** [comment]
Sorry, i were not able to answer last week. I want to mention that we still have some issue with concurrency with orders and order state. But i don't know if this is a caching problem. We decided to not futher investigate in this problem and using workarounds instead.

One additional question: Does the write lock works over multiple requests? Only then, the write lock would behave like exepted.

But in general i would agree with you @fashxp, we have to find a szenario example with (propably) a raw Pimcore where these cache errors occour. I am still curios, that no one else using Pimcore ever got problems with this way of storring the cache in the kernel shutdown. Maybe it is in issue indeed and so i hope the people find this thread in the future and can add helpful information.
