### ISSUE TITLE
[Bug]: Video Editable - TypeError in getErrorCode method

### ISSUE THREAD

**Issue by GALPR** [pimcore/pimcore#16261]
### Pimcore version

11.1.1

### Steps to reproduce

Add a Video editable and assign an unsupported video asset (e.g. .mov).

The Problem ist that the `getWIdth` and `getHeight` methods return either a string or an integer. 
When the return value is an integer these lines throw an error:
`/models/Document/Editable/Video.php:512`
`/models/Document/Editable/Video.php:521`

A potential fix might be to cast these values to strings before passing them into `preg_match`.

### Actual Behavior

A TypeError gets thrown: `preg_match(): Argument #2 ($subject) must be of type string, int given`

### Expected Behavior

No TypeError is thrown.

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16263
