### ISSUE TITLE
[Bug]: Errors during re-index simple backend search with asset metadata class definitions

### ISSUE THREAD

**Issue by studio1gmbh-pimcore** [pimcore/pimcore#16260]
### Pimcore version

11.0.12

### Steps to reproduce

1. Adding and `pimcore/asset-metadata-class-definitions` v2.0.2
2. Define asset meta data class incl. multi-select field
3. Add multiple values to multi-select field in asset
4. Update SimpleBackendSearch via its re-index command

### Actual Behavior

Log output like following:
```
WARNING   [php] Warning: Array to string conversion ["exception" => ErrorException { …}]
```

### Expected Behavior

No log output. Support of multi-select asset metadata class definition fields.

### Reason:
In method `\Pimcore\Bundle\SimpleBackendSearchBundle\Model\Search\Backend\Data::setDataFromElement()` `$instance` is instance of `\Pimcore\AssetMetadataClassDefinitionsBundle\Model\ClassDefinition\Data\Multiselect`. `\Pimcore\AssetMetadataClassDefinitionsBundle\Model\ClassDefinition\Data\Multiselect::getDataForSearchIndex()` is inherited from `\Pimcore\AssetMetadataClassDefinitionsBundle\Model\ClassDefinition\Data\Data`.
This method returns an `array` (as `mixed` is allowed due to its method signature), as `$md['data']` contains an array for multi-select fields (at least if there are multiple values selected).

The doc-block in method `\Pimcore\Bundle\SimpleBackendSearchBundle\Model\Search\Backend\Data::setDataFromElement()` implies an other case.  According to this doc-block `$instance` is an instance of `\Pimcore\Model\Asset\MetaData\ClassDefinition\Data\Data`. The method `\Pimcore\Model\Asset\MetaData\ClassDefinition\Data\Data::getDataForSearchIndex()` only supports `?string` as return value.
 
This case is not covered by the code itself, no suitable return value validation, no try-catch-block and it its method signature is not defined in the used interface `Pimcore\Model\Asset\MetaData\ClassDefinition\Data\DataDefinitionInterface`. This interface is used by both classes `\Pimcore\Bundle\SimpleBackendSearchBundle\Model\Search\Backend\Data` and `Pimcore\Model\Asset\MetaData\ClassDefinition\Data\Data`.

### Solution proposal:
Maybe this should be fixed in both `pimcore/pimcore` (extending the interface by adding the method `getDataForSearchIndex()` / validate return type in method `setDataFromElement()`) and `pimcore/asset-metadata-class-definitions` (change method signatue from `mixed` to `?string` and optimize return value for non-scalar data types).

**Comment by robertSt7** [comment]
Hi @studio1gmbh-pimcore thanks for your suggested solution, I like it a lot, but changing the return type of a function and adding a function to an interface is a BC-break, so I fixed only the return values here: https://github.com/pimcore/asset-metadata-class-definitions/pull/156. Thanks for your understanding

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/asset-metadata-class-definitions/pull/156 

Wiil be released in `pimcore/asset-metadata-class-definitions` `v2.0.5` this Thursday, please apply changes from PR, if required in the meanwhile
