### ISSUE TITLE
[Bug]: updating advanced many-to-many relationship fails when changing metadata

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#16265]
### Pimcore version

11.0.9

### Steps to reproduce

See https://github.com/pimcore/data-hub/issues/819

### Actual Behavior

See https://github.com/pimcore/data-hub/issues/819

### Expected Behavior

See https://github.com/pimcore/data-hub/issues/819

I can confirm charging 

https://github.com/pimcore/pimcore/blob/74c15378aa58f6ee4b7e667f94cbe992b24ccfa7/models/DataObject/Data/ElementMetadata/Dao.php#L46

to 
```php
            Helper::upsert($this->db, $table, $data, ['id', 'dest_id', 'type', 'fieldname', 'column', 'ownertype', 'ownername', 'position', 'index']);
```

seems to fix it.

**Comment by kingjia90** [comment]
Could it be that you didn't run this migration? 
https://github.com/pimcore/pimcore/blob/74c15378aa58f6ee4b7e667f94cbe992b24ccfa7/bundles/CoreBundle/src/Migrations/Version20230616085142.php#L33

Please check if every `object_metadata_` table has `auto_id` column

**Comment by dkarlovi** [comment]
@kingjia90 it does.

The issue here is the fact auto_id doesn't matter here, the unique key does.

**Comment by kingjia90** [comment]
Ok, we need some more time to carefully double-check it. 
FYI this `auto_id` was introduced to avoid some deadlock issues, see https://github.com/pimcore/pimcore/issues/15064#issuecomment-1541424498
https://github.com/pimcore/pimcore/pull/15746

changing it as suggested may re-introduce the deadlock

**Comment by dkarlovi** [comment]
Right, we added `upsert()` for the same problem, not sure how they correlate. The fact remains this doesn't work without the fix outlined above. :)
