### ISSUE TITLE
[Bug, EC]: Grid View filtering: No results using reverse object relations on M2M relations

### ISSUE THREAD

**Issue by jc-fwg** [pimcore/pimcore#16273]
### Pimcore version

11

### Steps to reproduce

Using Pimcore demo:

- Open grid view for Data Objects/Product Data/Categories
- Add 'Cars' relation to selected grid columns
- Apply
- Select 'Filter by relations' at 'Cars' column head
- Select 'Search objects'
- Select object '/Product Data/Cars/citroen/2CV'
- Apply filter

### Actual Behavior

Existing relation isn't displayed. 

### Expected Behavior

Existing relations should be displayed, too.

**Comment by kingjia90** [comment]
Reverse relation might not be supported https://pimcore.com/docs/pimcore/10.6/User_Documentation/DataObjects/Grid_Configuration_General.html#page_Filtering:~:text=one%20to%20many,advanced%20many%20to%20many%20object

**Comment by ghost** [comment]
@kingjia90 Feature is really not supported. Please refcous to the following fix: remove filter option when using reverse object relations.

**Comment by kingjia90** [comment]
Resolved by https://github.com/pimcore/admin-ui-classic-bundle/pull/375 which removes the misleading unsupported functionality.

However, it is `PR welcome` for actually extending support to Reverse object relations. Looking forward for it

**Comment by cancan101** [comment]
@fashxp , looking at https://github.com/pimcore/pimcore/pull/18036/files#diff-9e4f5a55dfbd0457a253717c7ad893e830d16f8fc63701c23eed7f6d145a91d2L95-R96, won't there now be cases that this line gets called with a null `$prefix` when it wasn't in the past?
```php
$this->getRelationFilterCondition($value, $operator, $prefix . $name);
```
