### ISSUE TITLE
Consolidation of PHP Namespaces, Service-Naming/Visibility

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1629]

**Comment by maff** [comment]
* Move `Pimcore\Service\Request\PimcoreContextResolverAwareInterface` and `Pimcore\Bundle\CoreBundle\EventListener\Traits\PimcoreContextAwareTrait` to the same namespace (move the `matchesPimcoreContext` method to the resolver?)

**Comment by brusch** [comment]
- `Pimcore\Facade` (is it really still necessary?) 
- `Pimcore\CacheWarmer` (maybe to be moved to `Pimcore\Cache`?) 
- `Pimcore\Admin` move to `Pimcore\Bundle\AdminBundle\Helper`
- `Pimcore\Glossary` -> `Pimcore\Tool\Glossary` ? 
- `Pimcore\Placeholder` -> `Pimcore\Tool\Placeholder` ?

**Comment by brusch** [comment]
- [ ] use 3.3 service naming (class names) wherever it is possible
- [ ] set internal services to private
