### ISSUE TITLE
[Improvement]: The new HTML Sanitizer's max_input_length is too low

### ISSUE THREAD

**Issue by alexej-d** [pimcore/pimcore#16297]
### Improvement description

Since introducing the HTML Sanitizer component, I noticed the content on some of my documents being cut off (mainly legal docs). After doing some research, I saw that the default character count set in the component is 20k. Isn't this something, that only makes sense in the context of public facing text inputs and less in the context of a CMS?

It is extremely inconvenient that content is now being truncated. Should this not at least be documented somewhere (except Symfony docs)?

**Comment by kingjia90** [comment]
It should be implicitly covered as part of this line
https://github.com/pimcore/pimcore/blob/b2c5423ec477aded98c31b0034e5e6f4ff6bcb0c/doc/03_Documents/01_Editables/40_WYSIWYG.md?plain=1#L66

but won't mind to add a commented line eg. `# max_input_length: 20000` somewhere here https://github.com/pimcore/pimcore/blob/d85498b6359b3466017d714be7bbde8efecc3c6e/bundles/CoreBundle/config/pimcore/default.yaml#L60-L65

Please open a PR for this improvement

**Comment by rubanooo** [comment]
I we need to modify the default Pimcore configuration, the max should be more than 20000 characters. The wysiwyg fields in are stored as `LONGTEXT` in the database, shouldn't the max match the storage limit? Or should the limit be removed because editing is not a public api

It's very confusing when editing an object and your text will be cut off.

**Comment by fashxp** [comment]
see also https://github.com/pimcore/pimcore/pull/16451 for some docs enhancements ... 
not sure about removing it at all due to security reasons. what do the others think?

**Comment by brusch** [comment]
Should be solves already by #17247

**Comment by kingjia90** [comment]
Just noticed that the doc line added in https://github.com/pimcore/pimcore/pull/16451 may be contradicting #17247

It feels like we need a follow up, either by removing/redact that doc line or eventually move the limit change to infinite to a minor release?

**Comment by brusch** [comment]
Nice catch - created a follow up #17391
