### ISSUE TITLE
[Bug]: DataObject/Service copyRecursive crashes

### ISSUE THREAD

**Issue by gfemorris** [pimcore/pimcore#16302]
### Pimcore version

11.1.2

### Steps to reproduce

Call method copyRecursive

### Actual Behavior

Crashes with 
Typed property Pimcore\Model\DataObject\Service::$_copyRecursiveIds must not be accessed before initialization

### Expected Behavior

`
if (!$this->_copyRecursiveIds) {
            $this->_copyRecursiveIds = [];
}
`
should be
        
`if (!isset($this->_copyRecursiveIds)) {
            $this->_copyRecursiveIds = [];
}
`

**Comment by blankse** [comment]
@gfemorris I created a PR https://github.com/pimcore/pimcore/pull/16303

**Comment by blankse** [comment]
@github-actions I already created a PR #16303

**Comment by gfemorris** [comment]
Is this planned for a release? There is already a pull request that will fix it and we are using this feature which is currently broken.

**Comment by gfemorris** [comment]
Sorry i have seen that the puill request is merged in the latest release. So this issue can be closed.
