### ISSUE TITLE
[Bug]: Thumbnail generation on the fly is broken with current regex

### ISSUE THREAD

**Issue by gfemorris** [pimcore/pimcore#16301]
### Pimcore version

11.1.2

### Steps to reproduce

Try to generate a thumbnail on the fly. Like:
https://example.com/examples/panama/6644/image-thumb__6644__contentimages/img_0037.jpeg

### Actual Behavior

No thumbnail is created.

### Expected Behavior

The regular expression in models/Asset/Service.php in line 563 does not match anymore.
It was changed from
`preg_match("@([^\@]+)(\@[0-9.]+x)?\.([a-zA-Z]{2,5})@", $config['filename'], $matches);`
to
`preg_match("@([^\@]+)(\@[0-9.]+x)?\.([^\.]+)\.([a-zA-Z]{2,5})@", $config['filename'], $matches);`

The new version requires an extra "." which is not present in the filename.

Regression from https://github.com/pimcore/pimcore/pull/15594

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16354
