### ISSUE TITLE
[Bug]: pimcore_inc() no longer accepts a path

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#16313]
### Pimcore version

11.1.2

### Steps to reproduce

Include in your template:

`{{ pimcore_inc('/path/to/your/snippet') }}`

### Actual Behavior

Snippet won't be included.

### Expected Behavior

Snippet will be included as it worked in Pimcore 10.6 and it's still documented as allowed: https://pimcore.com/docs/platform/Pimcore/MVC/Template/Template_Extensions/#pimcore_inc

**Comment by blankse** [comment]
@cadeyrn I cant't reproduce it.
When I change following in the demo it also works:

Template `templates/layouts/layout.html.twig`, Line 200
Before:
`{{ pimcore_inc(document.getProperty('footer')) }}`
After:
`{{ pimcore_inc('/en/shared/includes/footer') }}`

Maybe you have a typo in your string? It doesn't show an error/warning, if the snippet is not found.

**Comment by NiklasBr** [comment]
We got the same problem, includes using paths such as `{{ pimcore_inc('/se/snippetsfooter') }}` which worked in v10.6 no longer worked after v11.

**Comment by cadeyrn** [comment]
@blankse Yes, I am sure that there is no typo in the path. I also tried different snippets. They all work if I use a document property as parameter for pimcore_inc(), but not if I use the path. The exactly same code works in my Pimcore 10.6 installation.

But now that you write that, I have tested another Pimcore 11 installation and it works there. There is one difference: In the installation where it doesn't work, I use sites. I don't use sites on the installation where it works.

**Comment by blankse** [comment]
@cadeyrn I created a Site in the demo and use the snippet via string in the template. It also works...
![image](https://github.com/pimcore/pimcore/assets/998558/2feb5c96-e46a-4377-bcfb-caa7831fad79)
![image](https://github.com/pimcore/pimcore/assets/998558/b141a903-f772-4123-93fd-44cc54df552c)

Can you debug the `Pimcore\Templating\Renderer\IncludeRenderer::render()` method? I think it must throw an error in the try/catch in the lines 62-66. What is here the exception message?

**Comment by cadeyrn** [comment]
`Model\Document::getByPath($include)` just returns `null`, therefore there is no exception.

**Comment by cadeyrn** [comment]
> There is one difference: In the installation where it doesn't work, I use sites. I don't use sites on the installation where it works.

I can confirm that it works once I move the snippet folder outside the site to the root.

**Comment by blankse** [comment]
@cadeyrn So can you debug the `Pimcore\Model\Document\Dao::getByPath()` method? What is here the SQL query before you move the snippet? What is the path before you move? Is there a special character in the path which can make trouble?

**Comment by cadeyrn** [comment]
The SQL query for `$data = $this->db->fetchAssociative('SELECT id FROM documents WHERE `path` = BINARY :path AND `key` = BINARY :key', $params);` is in both cases exactly the same:

```
SELECT id FROM documents WHERE `path` = BINARY ? AND `key` = BINARY ?

Parameters:

[▼
  "/tagesbestpreise/"
  "12"
]
```

If the snippet folder is on the root, it gives the following result for `$data`:

`array(1) { ["id"]=> int(194) } `

Within a site, $data is `bool(false) `.

**Comment by blankse** [comment]
@cadeyrn When the snippet folder is in the site you have to add the site key to the path. The path of the snippet must be always absolute I think. So the parameter should have the site key as prefix.

**Comment by cadeyrn** [comment]
True, this works. I was pretty sure that I tested it, but obviously I tested it wrong. Thank you for your help in debugging the problem.

@NiklasBr Does your issue have the same cause?

**Comment by blankse** [comment]
@cadeyrn I tested it in Pimcore 10. There I must also set the absolute path with the site key. So why do you think there is a difference from Pimcore 10 to Pimcore 11?

**Comment by cadeyrn** [comment]
When I opened the issue, I hadn't thought about the use of sites being a factor here. It happened to always be Pimcore 10 installations without sites where the code was written that way, and now happened to be a Pimcore 11 installation with sites where it didn't work. So it was a misjudgment on my part that it broke with Pimcore 11.

**Comment by blankse** [comment]
@cadeyrn Okay :) So only @NiklasBr had a problem with the update? Or can we close the issue?
