### ISSUE TITLE
[Bug] Workflows broken with symfony 6.4

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#16315]
### Pimcore version

11

### Steps to reproduce

- try to execute transitions for workflows
- also phpstan tests fail

### Actual Behavior

 The "workflow.wfdesigner_test" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

### Expected Behavior

transition work

**Comment by robertSt7** [comment]
Fixed by #16320

**Comment by fashxp** [comment]
fixed via #16328
