### ISSUE TITLE
[Bug]: Pre-assignment for Twig function pimcore_link no longer works with Pimcore11

### ISSUE THREAD

**Issue by Lars77** [pimcore/pimcore#16310]
### Pimcore version

11.0.12

### Steps to reproduce

Create a twig template and make use of twig function [pimcore_link](https://pimcore.com/docs/platform/Pimcore/Documents/Editables/Link). To set default values of the link, use the function `setDataFromResource`
```twig
{% set link = pimcore_link('link') %}
{% set text = link.isEmpty() ?  "Search on Google" : link.getText() %}
{% set url = link.isEmpty() ? "https://www.google.com" : link.getHref %}
{% set data = {'path' : url, 'text': text} %}
{% do link.setDataFromResource(data) %}
{{ link | raw }}
```

### Actual Behavior

`setDataFromResource` throws an error, because string is expected, but array given
Reasons for that is the function call of `\Pimcore\Tool\Serialize::unserialize($data);` in [Link.php](https://github.com/pimcore/pimcore/blob/11.x/models/Document/Editable/Link.php#L292) is expecting string and not array.

### Expected Behavior

preassign data of `pimcore_link` with url and text via `setDataFromResource` like in Pimcore10

**Comment by blankse** [comment]
@Lars77 I created a PR: https://github.com/pimcore/pimcore/pull/16312

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16312

**Comment by Lars77** [comment]
Perfect! Thank you.
