### ISSUE TITLE
[Bug]: Static Routes Bundle ignores the PIMCORE_CONFIGURATION_DIRECTORY constant

### ISSUE THREAD

**Issue by hethehe** [pimcore/pimcore#16330]
### Pimcore version

11.x

### Steps to reproduce

Similar to #15534 

- Define the PIMCORE_CONFIGURATION_DIRECTORY constant.
- Create a static route

The .yaml files are stored in `/var/config/staticroutes` instead of `PIMCORE_CONFIGURATION_DIRECTORY/staticroutes`

### Actual Behavior

The StaticRoutesBundle ignores the constant and saves the static route config to `var/config/staticroutes`

### Expected Behavior

the configuration is saved to `PIMCORE_CONFIGURATION_DIRECTORY/staticroutes`

**Comment by kingjia90** [comment]
Thank you for reporting!

It should be fixed by https://github.com/pimcore/pimcore/pull/16331, could you please try it and let us know?

**Comment by kingjia90** [comment]
fixed by https://github.com/pimcore/pimcore/pull/16331
