### ISSUE TITLE
Add option to assign editables to areablocks in documents

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#1633]
# Feature Request 
It should be possible to create documents (or printpages) with editables inside areablocks using a controller.

## Feature description 
Something like this should be possible:
### Code example 
```php
        //Setup a new print page
        $printpage = new \Pimcore\Model\Document\Printpage();
        $printpage->setKey('somekey);
        $printpage->setParentId(12345);
        $printpage->setController('Web2print');
        $printpage->setAction('myaction');
        $printpage->setTemplate('/web2print/myaction.php');
        $printpage->save();

        //Assign an areablock
        $printpage->setRawElement('someareablock', 'areablock', null);

        //Create editable elements
        $input = new Document_Tag_Input();
        $input->setName('someheadline');
        $input->setDataFromResource("Some Headline");
        //Here should follow some more later

        //Here I am missing a function to assign the $input to the areablock element on the printpage


        $printpage->save();
```
  
As far as I've seen there is no option to assign editables in this way to some areablock inside a document. I'd like to request such a feature. Use case are semi-automated reports where data will be automatically injected in input tags inside areablocks and the user has the option to modify the content, delete single editables from the areablock and create a document or printpage.

**Comment by Cruiser13** [comment]
@brusch any info on why this has been closed?

**Comment by brusch** [comment]
@Cruiser13 sure, sorry, I missed that one 😊
It is not possible to "assign" an editable to an areablock, because they are not managed in a hierarchical manner - all editables are in a flat structure regardless if they are used within an areablock or not. The affiliation is only made by the naming structure.

**Comment by Cruiser13** [comment]
@brusch but if I have multiple areablocks I need to define which areablock an editable is in, right? Would I use setParentBlockNames in this case?
