### ISSUE TITLE
[Bug]: Warning: Undefined array key "unitId" Data\QuantityValueRange->toArray() has wrong return data 

### ISSUE THREAD

**Issue by NikitaKharkov** [pimcore/pimcore#16334]
### Pimcore version

v11.1.2

### Steps to reproduce

- Create class;
- Create a panel, under it block, under it QuantityValueRange;
- Create any quantity value in Settings->Data Objects->Quantity Values
- Save; Create an instance and add one block item
- Fill it and try to save;

### Actual Behavior

**Message: Warning: Undefined array key "unitId"**
![image](https://github.com/pimcore/pimcore/assets/19974632/a88e92be-4db9-48b0-a5c6-cacfae377079)
Cannot save an object.

Working around:

This is because **Data\QuantityValueRange->toArray()** has a return with only max/min array values, without unitId. And after normalizing/denormalizing while block update processing it misses the unitId and gets such an error.

What I suggest just to add to the return array not max/min, but also unitId.

```php
# vendor/pimcore/pimcore/models/DataObject/Data/QuantityValueRange.php:76
public function toArray(): array
    {
        return [
            'minimum' => $this->getMinimum(),
            'maximum' => $this->getMaximum(),
            'unitId' => $this->getUnitId(),
        ];
    }
```

### Expected Behavior

Should be saved correctly

**Comment by kingjia90** [comment]
Thank you for reporting and the suggestion

Fixed by https://github.com/pimcore/pimcore/pull/16346
