### ISSUE TITLE
Two roles with same workspace but different rights

### ISSUE THREAD

**Issue by janwalther** [pimcore/pimcore#1634]
### Expected behavior 
Rights should be additive
  
### Actual behavior  
Rights are not additive but one role defines access rights for workspace (which one seems unclear at the moment but the steps below reproduce the bug for sure), others are ignored
  
### Steps to reproduce  
1. Create role "write" with right for assets and add asset folder X as asset workspace and assign it all rights (list, view, publish etc.)
1. Create role "read" without right for assets and add asset folder X as asset workspace and assign only list and view rights
1. Create user and assign both roles
1. Login as new user and right click on folder X -> cannot upload

**Comment by markus-moser** [comment]
fixed in pimcore 4 and pimcore 5: permissions are now additive in this case (and not "random" anymore)

**Comment by brusch** [comment]
This topic needs to be revised again, see #4499 - seems we need a more sophisticated query to achieve the desired behavior for the scenario described above.

**Comment by brusch** [comment]
Additionally we should think about the behavior when having multiple roles assigned to a user and the roles have colliding or overlaping workspaces.

**Comment by weisswurstkanone** [comment]
Already touched by https://github.com/pimcore/pimcore/pull/6670

Current behavior is that:

- Longer cpath always has higher priority regardless of whether defined in any role or user workspace
- For same cpath user setting always takes preference
- If there is no user workspace setting for the cpath then ...
- Overlapping roles settings are then additive (e.g. read write for the cpath get merged)
