### ISSUE TITLE
[Bug]: Apploger Timezone in admin

### ISSUE THREAD

**Issue by sevarozh** [pimcore/pimcore#16345]
### Pimcore version

11.1.1

### Steps to reproduce

Application Logger open. Log time is displayed incorrectly.

In pimcore/bundles/ApplicationLoggerBundle/src/Controller/LogController.php::showAction is DB entry always converted into timestamp with UTC:

            $carbonTs = new Carbon($row['timestamp'], 'UTC');
            $logEntry = [
                'id' => $row['id'],
                'pid' => $row['pid'],
                'message' => $row['message'],
                'date' => $row['timestamp'],
                'timestamp' => $carbonTs->getTimestamp(),
                'priority' => $row['priority'],
                'fileobject' => $fileobject,
                'relatedobject' => $row['relatedobject'],
                'relatedobjecttype' => $row['relatedobjecttype'],
                'component' => $row['component'],
                'source' => $row['source'],
            ];

The config.yaml is ignored:
  ```
  pimcore:
       general:
         time zone: Europe/Berlin
```

### Actual Behavior

Log time is displayed incorrectly.

### Expected Behavior

local log time is displayed.

**Comment by paulverdu** [comment]
Any plans on fixing this bug? We have a time difference of 2 hours now in ApplicationLogger on our servers.

**Comment by blankse** [comment]
@sevarozh @paulverdu Should be fixed by https://github.com/pimcore/pimcore/pull/16678
Isn't it?

**Comment by paulverdu** [comment]
> @sevarozh @paulverdu Should be fixed by #16678 Isn't it?

Aah, gonna update Pimcore to a newer version and see if it resolves the issue. Thanks!

**Comment by blankse** [comment]
@paulverdu Did you check it? Can we close the issue?

**Comment by paulverdu** [comment]
@blankse Yes it's working correctly. You can close the issue 👍
