### ISSUE TITLE
[Bug]: Unable to install enterprise packages with demo version

### ISSUE THREAD

**Issue by rushabhcredencys** [pimcore/pimcore#16368]
### Pimcore version

11.1.1

### Steps to reproduce

composer require pimcore/enterprise-subscription-tools

### Actual Behavior

![image](https://github.com/pimcore/pimcore/assets/129751901/c0902a62-ea2c-4e04-a602-dffe2c1c8cbe)

### Expected Behavior

It should works

Kindly refer attached composer.json file for more detail

[composer.json](https://github.com/pimcore/pimcore/files/13673144/composer.json)

**Comment by rushabhcredencys** [comment]
Also facing same issue with portal engine
![image](https://github.com/pimcore/pimcore/assets/129751901/52daa6f4-65c1-43e6-b94d-271c6a95906b)

**Comment by kingjia90** [comment]
The composer is missing the private repository source
```
  "repositories": {
    "dev": {
      "type": "path",
      "url": "./dev/*/*",
      "options": {
        "symlink": true
      }
    },
    "enterprise": {
      "type": "composer",
      "url": "https://enterprise.repo.pimcore.com/"
    }
  }
```
You have to do
`composer config repositories.pimcore_enterprise composer https://enterprise.repo.pimcore.com`
`composer config --auth http-basic.enterprise.repo.pimcore.com token <insert your token here>`

**Comment by rushabhcredencys** [comment]
Thanks @kingjia90
