### ISSUE TITLE
[Bug]: TinyMce in Objects empty textfield not possible

### ISSUE THREAD

**Issue by hadl** [pimcore/pimcore#16372]
### Pimcore version

11.1.3

### Steps to reproduce

* Create object with WYSIWYG field
* Focus field without entering text
* Blur field and / or save

### Actual Behavior

Check Dev-Tools Network panel:

- Save-Payload will contain `{"technicalHighlights":"<p><br data-mce-bogus=\"1\"></p>"}`
- Table e.g. object_localized_data_1 column technicalHighlights: `"<p><br /></p>"`
- Frontend getter output is the same

### Expected Behavior

Save empty content without/not the mce-bogus tags.

**Comment by hadl** [comment]
@kingjia90 wrong milestone?

**Comment by kingjia90** [comment]
Fixed by #16373 

Thank you for reporting and the PR!
