### ISSUE TITLE
[Bug]: Pimcore\Messenger\SearchBackendMessage not found during decoding

### ISSUE THREAD

**Issue by bitfactory-falko-neven** [pimcore/pimcore#16390]
### Pimcore version

11.1.2

### Steps to reproduce

Run ``bin/console messenger:consume pimcore_core``

I did recently upgrade from pimcore 10 to 11 could there be old records in the ``messenger_messages`` that would cause this issue? I've cleared them currently which solves the issue for now but nothing new seems to be written to ``pimcore_core`` anymore.

### Actual Behavior

1. When running ``bin/console messenger:consume pimcore_core`` it fails

```
/app # bin/console messenger:consume pimcore_core


 [OK] Consuming messages from transport "pimcore_core".


 // The worker will automatically exit once it has received a stop signal via the messenger:stop-workers command.

 // Quit the worker with CONTROL-C.

 // Re-run the command with a -vv option to see logs about consumed messages.


In PhpSerializer.php line 117:

  Message class "Pimcore\Messenger\SearchBackendMessage" not found during decoding.


messenger:consume [-l|--limit LIMIT] [-f|--failure-limit FAILURE-LIMIT] [-m|--memory-limit MEMORY-LIMIT] [-t|--time-limit TIME-LIMIT] [--sleep SLEEP] [-b|--bus BUS] [--queues QUEUES] [--no-reset] [--] [<receivers>...]

/app #
```

This only occurs for ``pimcore_core``. When running the other queue's ``bin/console messenger:consume pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize pimcore_asset_update``

There is no issue

### Expected Behavior

Expected behaviour is that the worker also finishes tasks from ``pimcore_core``

**Comment by kingjia90** [comment]
Sounds like you overridden the default Messenger routing config and it now needs a manual adaptation due our change of extracting the functionality in [own built-in bundle.](https://github.com/pimcore/pimcore/issues/12528)

Please check this change and eventually apply to your custom config:

![image](https://github.com/pimcore/pimcore/assets/6014195/7a16c82d-e3ab-450d-a8b7-5bf4ef2aa1aa)


https://github.com/pimcore/pimcore/pull/13978/files#diff-34d259c58a9001df91ca2ccc5f41ab960a307d1566cffceb88262d679cfc6c70

**Comment by bitfactory-falko-neven** [comment]
Thank you for responding, since this regards old messages i've removed the ones in regards to SearchBackendMessage which allows the `bin/console messenger:consume pimcore_core pimcore_maintenance pimcore_scheduled_tasks pimcore_image_optimize pimcore_asset_update` as intended.
