### ISSUE TITLE
[Bug]: Batch action in grid not working anymore with "advanced relations" fields

### ISSUE THREAD

**Issue by tecbird** [pimcore/pimcore#16397]
### Pimcore version

11.1.3

### Steps to reproduce

1) Open any grid
2) Use a advanced relation field, and select "Batch action" (like add a relation to all selected elemens)
![image](https://github.com/pimcore/pimcore/assets/16688055/3ecbaba8-62db-4ea2-ac76-27e31c9f2fcd)

3) Add a new element as relation
4) Apply changes

### Actual Behavior

Fails with hard php error:
`Uncaught Error: Pimcore\Model\DataObject\ClassDefinition\Data\AdvancedManyToManyObjectRelation::buildUniqueKeyForAppending(): Argument #1 ($item) must be of type Pimcore\Model\Element\ElementInterface, Pimcore\Model\DataObject\Data\ObjectMetadata given, called in /php/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php on line 268`

### Expected Behavior

Working, appending data to advanced relation fields.

The problem is "appendData" using relation Models "ObjectMetaaata" but  "buildUniqueKeyForAppending" allowing only objects
Starting point in application is: \Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectHelperController::batchAction

**Comment by tecbird** [comment]
Original code that worked 
![image](https://github.com/pimcore/pimcore/assets/16688055/48956817-a192-41ed-ab29-e477229243a6)

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16458
