### ISSUE TITLE
After updating from 10.6 pimcore v to 11 version, facing version count issue

### ISSUE THREAD

**Issue by Thejaswini-Rao-U** [pimcore/pimcore#16404]
### Pimcore version

pimcore v 11.0

### Steps to reproduce

Hi

I have updated pimcore 10.6 v to pimcore 11, followed all the steps as per pimcore documentation. 
After login to admin, gives version count error.

### Actual Behavior

After login to admin UI, gives version count error.

Error attached here
![pimcore11](https://github.com/pimcore/pimcore/assets/78895325/f28c41f1-d6b6-475c-8d1d-7dc5bdf45206)

### Expected Behavior

It should work without error

Please let me know how to solve this?

thanks in advance

**Comment by Thejaswini-Rao-U** [comment]
Anyone please suggest?

**Comment by dpfaffenbauer** [comment]
https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/Updating_Pimcore/Preparing_for_V11#migrate-o_-prefix-properties-in-the-stored-data

**Comment by Thejaswini-Rao-U** [comment]
@dpfaffenbauer, Thanks for the response,

i executed these command 
**composer require --no-update pimcore/compatibility-bridge-v10** && 

**bin/console doctrine:migration:exec 'Pimcore\Bundle\CoreBundle\Migrations\Version20230508121105'**

followed same document before raising issue here.

but error still exists on admin panel after login
when im rebuilding classes command gives below error
i could not upload screenshot here so attaching error msg got in command line

**Saving all classes
11:55:03 ERROR     [pimcore] Class: Pimcore\Model\DataObject\FileExtensionMaster => call to undefined method seto_versionCount
11:55:03 EMERGENCY [pimcore] Exception: Call to undefined method seto_versionCount in class Pimcore\Model\DataObject\FileExtensionMaster in /var/www/html/projectName/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:231
Stack trace:
#0 /var/www/html/projectName/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(189): Pimcore\Model\AbstractModel->__call()
#1 /var/www/html/projectName/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(170): Pimcore\Model\AbstractModel->setValue()
#2 /var/www/html/projectName/vendor/pimcore/pimcore/lib/Model/Dao/DaoTrait.php(39): Pimcore\Model\AbstractModel->setValues()
#3 /var/www/html/projectName/vendor/pimcore/pimcore/models/DataObject/Concrete/Dao.php(68): Pimcore\Model\Dao\AbstractDao->assignVariablesToModel()
#4 /var/www/html/projectName/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(244): Pimcore\Model\DataObject\Concrete\Dao->getById()
#5 /var/www/html/projectName/vendor/pimcore/pimcore/models/DataObject/Listing/Dao.php(66): Pimcore\Model\DataObject\AbstractObject::getById()
#6 [internal function]: Pimcore\Model\DataObject\Listing\Dao->load()
#7 /var/www/html/projectName/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(220): call_user_func_array()
#8 /var/www/html/projectName/src/Service/OptionProviderFEM.php(52): Pimcore\Model\AbstractModel->__call()
#9 /var/www/html/projectName/src/Service/OptionProviderFEM.php(26): App\Service\OptionProviderFEM->getChannelOpt()
#10 /var/www/html/projectName/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Multiselect.php(451): App\Service\OptionProviderFEM->getOptions()
#11 /var/www/html/projectName/vendor/pimcore/pimcore/models/DataObject/ClassDefinition.php(342): Pimcore\Model\DataObject\ClassDefinition\Data\Multiselect->preSave()
#12 /var/www/html/projectName/vendor/pimcore/pimcore/lib/Model/DataObject/ClassDefinition/ClassDefinitionManager.php(81): Pimcore\Model\DataObject\ClassDefinition->save()**


As i see in the Pimcore\Model\DataObject\FileExtensionMaster  class there is no method defined as seto_versionCount ? 
also i have searched whole project folder with this method  i didnt find any or similar to that?

the service file OptionProviderFEM.php pointing error, doesnt have any such method?
line no it showing has method  **$optionsData->setOrderKey("masterOrder");**

in the fileExtensionMaster class has method below which is pointing in the service file

/**
* Set masterOrder - Order
* @param float $masterOrder
* @return \Pimcore\Model\DataObject\FileExtensionMaster
*/
public function setMasterOrder ($masterOrder) {
	$fd = $this->getClass()->getFieldDefinition("masterOrder");
	$this->masterOrder = $fd->preSetData($this, $masterOrder);
	return $this;
}

regarding this gives error i dont have any idea of this?
how to solve this?

**Comment by Thejaswini-Rao-U** [comment]
Hi Team

Any response?

**Comment by dpfaffenbauer** [comment]
Did you actually read what I wrote? There is a separate script to migrate versions.

**Comment by Thejaswini-Rao-U** [comment]
@dpfaffenbauer , 

sorry i missed it, now i have read the scripts
but how to execute it? it should be only inside project root? not under any other folders?
let me know how to execute it?

**Comment by dpfaffenbauer** [comment]
> # Migrate o_ prefix properties in the stored data
> As o_ prefix will be removed from data objects system properties in v11. It is recommended to migrate the stored data to use new properties (without o_ prefix). Please adapt and use these [scripts](https://gist.github.com/dvesh3/50a1a99fd337d461e1652f2fd3b4d6cd) to migrate versions and recycle-bin data.

**Comment by Thejaswini-Rao-U** [comment]
@dpfaffenbauer , I got it, but how to execute it?
i have placed these 2 files inside project folder?
i tried using bin/console doctrine:migrations:migrate pimcore10.6_migrate_o_prefixes_recyclebin
didnt work
how to execute it please let me knw?

**Comment by dpfaffenbauer** [comment]
```php filename-of-script.php```

**Comment by Thejaswini-Rao-U** [comment]
@dpfaffenbauer , Thanks for response

i executed 2 commands. In the version command getting below error attached

command => php pimcore10.6_migrate_o_prefixes_versions.php

**Exception {#1022
  #message: "Call to undefined method seto_versionCount in class Pimcore\Model\DataObject\Tier"
  #code: 0
  #file: "./vendor/pimcore/pimcore/lib/Model/AbstractModel.php"
  #line: 231
  trace: {
    ./vendor/pimcore/pimcore/lib/Model/AbstractModel.php:231 { …}
    ./vendor/pimcore/pimcore/lib/Model/AbstractModel.php:189 { …}
    ./vendor/pimcore/pimcore/lib/Model/AbstractModel.php:170 { …}
    ./vendor/pimcore/pimcore/lib/Model/Dao/DaoTrait.php:39 { …}
    ./vendor/pimcore/pimcore/models/DataObject/Concrete/Dao.php:68 { …}
    ./vendor/pimcore/pimcore/models/DataObject/AbstractObject.php:244 { …}
    ./vendor/pimcore/pimcore/models/Element/AbstractElement.php:644 { …}
    ./vendor/pimcore/pimcore/models/DataObject/Concrete.php:736 { …}
    Pimcore\Model\DataObject\Concrete->__wakeup() {}
    ./vendor/pimcore/pimcore/lib/Tool/Serialize.php:31 { …}
    ./vendor/pimcore/pimcore/models/Version.php:290 { …}
    ./vendor/pimcore/pimcore/models/Version.php:413 { …}
    ./pimcore10.6_migrate_o_prefixes_versions.php:26 {
      › $data = null;
      › $data = $version->getData();
      › 
    }
  }
}**

**Comment by Thejaswini-Rao-U** [comment]
anyone please let me know how to solve this?
