### ISSUE TITLE
[Bug]: Data Component Quantity Value Range does not allow 0

### ISSUE THREAD

**Issue by dark-cms** [pimcore/pimcore#16401]
### Pimcore version

11.1.3

### Steps to reproduce

1. Create a Class with Data Component -> Quantity Value Range
2. Create an object based on this Class and set Minimum to 0 
3. Save and reload Layout.

The Minimum-Value is empty and resave throws an exception: 

`Validation failed: Invalid dimension unit data: `

This also happens if minimum is negative and maximum is 0
This behaviour does not occur with Data Components Number and Quantity Value.

### Actual Behavior

The 0 is not displayed in input fields of "Quantity Value Range" after open or reload a data object with this type of element.

### Expected Behavior

The "0" must also be displayed in "Quantity Value Range" input fields after open or reload a data object with this type of element.

**Comment by dark-cms** [comment]
There is another bug that is related to this. If a quantity value range field is used within an object brick, saving it again does not throw an error. The formerly non-empty field is now also empty.

**Comment by kingjia90** [comment]
Thank you for reporting, couldn't reproduce it, it could be that it got fixed somewhere else.
Could you please retry again with a more recent pimcore version?

**Comment by kingjia90** [comment]
Thank you for reporting!
i was able to reproduce it, basically after save, the `0` becomes empty somehow, will provide a PR with the fix ASAP

**Comment by kingjia90** [comment]
https://github.com/pimcore/admin-ui-classic-bundle/pull/561 PR is ready, please give it a try by applying the changes if possible.
