### ISSUE TITLE
[Bug]: Error in menu renderer

### ISSUE THREAD

**Issue by twin-elements** [pimcore/pimcore#16402]
### Pimcore version

11.1.4

### Steps to reproduce

I have a document whose children are active and disabled from navigation (all children are disabled from navigation) 
![image](https://github.com/pimcore/pimcore/assets/17727266/ff2de793-2381-49fa-a83f-17870246a4f6)

and I am trying to render a menu with this document with the parameters "renderParentClass: true".

![image](https://github.com/pimcore/pimcore/assets/17727266/5f44a7fc-5371-4692-bc6a-14e6cc0c00c4)

As a result, the document is rendered with the parent class, which is an error because there are no children in the menu.

![image](https://github.com/pimcore/pimcore/assets/17727266/6b359422-a43a-4621-874d-59d7462cc10b)

### Actual Behavior

Parent class should not render when parent's children are excluded from navigation

### Expected Behavior

In the file 
[/lib/Navigation/Renderer/Menu.php](https://github.com/pimcore/pimcore/blob/75b854f9bd1f783ac3a7ba63174856caa92bacbd/lib/Navigation/Renderer/Menu.php#L834)
 line 834 it must be checked if the document has children that are not excluded from navigation instead of "$page->hasChildren()"

**Comment by twin-elements** [comment]
Of course, I can take care of this problem if there is acceptance

**Comment by fashxp** [comment]
Hi, we would appreciate any contributions. Thank you very much!

**Comment by twin-elements** [comment]
fixed by https://github.com/pimcore/pimcore/pull/16462

**Comment by hadl** [comment]
@twin-elements @kingjia90 

> In the file
> [/lib/Navigation/Renderer/Menu.php](https://github.com/pimcore/pimcore/blob/75b854f9bd1f783ac3a7ba63174856caa92bacbd/lib/Navigation/Renderer/Menu.php#L834)
> line 834 it must be checked if the document has children that are not excluded from navigation instead of "$page->hasChildren()"

Thats correct -> https://github.com/pimcore/pimcore/pull/16462#issuecomment-1896169009

**Comment by twin-elements** [comment]
@hadl Yes, I agree with you 100%.
I took the liberty of urgently implementing your proposal. Thank you very much.
