### ISSUE TITLE
[Bug]: Statically-generated pages via CLI have invalid hostname in generated URLs

### ISSUE THREAD

**Issue by tmannherz** [pimcore/pimcore#16408]
### Pimcore version

11.1.4

### Steps to reproduce

1. Configure a document as statically generated: 
![image](https://github.com/pimcore/pimcore/assets/533798/4bdba07b-c445-4118-b8c0-b47a2b12ffed)
2. Run the console command to regenerate all configured documents, `bin\console pimcore:documents:generate-static-pages`
3. Inspect the generated source, somewhere in `public/var/tmp/pages`.

### Actual Behavior

Any usage of a url helper (`Symfony\Component\HttpFoundation\UrlHelper`) to generate a URL will yield a url like `https://http/my-document`, where the desired hostname is replaced with `http`. Using the url twig function (eg. `{{ url('my-link') }}`) in a template will utilize the UrlHelper and reproduce the issue.

The issue stems from [this line](https://github.com/pimcore/pimcore/commit/f86800008e233cedb24f31b21005c2fb6210bd18#diff-29ee94726c0bbd4602ec6202c94c2d68c557621d0e50f057b37efed3a299652aR96):
```php
}elseif( $systemMainDomain = Tool::getHostUrl() ){
```
It's grabbing a full URL instead of a hostname. The simple fix is:
```php
}elseif( $systemMainDomain = Tool::getHostname() ){
```

### Expected Behavior

Generating static pages via the cli command should yield URLs with the correct hostname.

**Comment by kingjia90** [comment]
Confirming the problem, opened a PR with the suggested changes, thank you!

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16479
