### ISSUE TITLE
[Docs] Add note to the docs for: Pimcore 11 TinyMCE Default Config truncating content

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#16426]
Add notes to the docs as discussed here: https://github.com/pimcore/pimcore/discussions/16414#discussioncomment-8008499

### Discussed in https://github.com/pimcore/pimcore/discussions/16414

<div type='discussions-op-text'>

<sup>Originally posted by **mlkdev** January  4, 2024</sup>
Pimcore Version 11.0.12

We have a DataObject class we're using for Articles and other publications, and for the most part it works as expected. However, we recently encountered an instance where text is being truncated without apparent reason.

We've tested to make sure it's not an issue with the database, and we were able to insert our markup directly into the database, flushed the caches and it output as expected. However, using the Pimcore UI, and the out-of-the-box config for TinyMCE, it appears that the content is being truncated before being saved.

We also followed various guides online that instruct how to remove the character limit using the following markup:
```
{
  selector: 'textarea',
  max_chars: -1
}
```
This appears to not have any affect on storage process, and still results in truncation of content. It appears to truncate around 20,000 characters. I just tried storing a block of Lorem Ipsum with no markup, and it concatenated at exactly 20,000 characters.

Anyone have any ideas?</div>

**Comment by waggyman** [comment]
Hello, where to put the `max_input_length` for the wysiwyg? Because, I already read the documentation and implement it in `html_sanitizers.yaml` file. But I still got the issue. https://github.com/pimcore/pimcore/issues/17371
