### ISSUE TITLE
Chrome headless as PDF renderer for web2print

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1643]
The last Chrome version can be used headless to print PDF, see:
https://developers.google.com/web/updates/2017/04/headless-chrome

I didn't try it, but maybe it is better than wkhtml2pdf. There is often CSS breaking-page problem with wkhtml2pdf wich could be not with the crome rendering.

This is just an idea of new feature, but maybe use Chrome Headless could bring more easy web2print work.
For html integrator, it would be easier as the render will be the same than Chrome browser so more consistent.

**Comment by cleggypdc** [comment]
Heya, here's our solution for the time being, still PC4, but we're working on a PC5 ready plugin
https://github.com/gatherdigitaluk/pimcore-plugin-pdf

**Comment by brusch** [comment]
If someone is willing to contribute, we'd be happy to accept a PR for that. 
For now I'm closing this issue, since the core team isn't going to implement this soon.
