### ISSUE TITLE
Translation import - determineCsvDialect fails for quotechar if too many single quotes are in the first few lines

### ISSUE THREAD

**Issue by gfemedia** [pimcore/pimcore#1644]
# Bug Report
If there are too many single quotes in the first few lines, the automatic csv dialect detection fails and detects single quote as quotechar. If you import a file in to an existing project all keys are duplicate with double quotes afterwards. Maybe it would be better to detect the first character of the line or the combination of quote character and delimiter.
  
### Code example 
```
"'%hostname%' is not a valid hostname for email address '%value%'";"'%hostname%' ist keine gültige Domain für E-Mail-Adresse '%value%'";""
"'%value%' appears to be a dns hostname but cannot match tld against known list";"'%value%' ist kein gültige TLD";""
"'%value%' appears to be a local network name but local network names are not allowed";"'%value%' ist keine gültige Domain";""
"'%value%' does not appear to be a valid ip address";"";""
"'%value%' does not appear to be a valid local network name";"";""
"'%value%' does not match the expected structure for a dns hostname";"'%value%' weist keine gültige Domain-Struktur auf.";""
"'%value%' is not a valid email address in the basic format local-part@hostname";"'%value%' ist keine gültige E-Mail-Adresse";
```

**Comment by brusch** [comment]
I think we should add the possibility to manually set the delimiter and quoting character, all other approaches and automatisms will never be 100% accurate.
