### ISSUE TITLE
[Bug]: Saving a Document doesn't clear the full page cache

### ISSUE THREAD

**Issue by bitbirddev** [pimcore/pimcore#16453]
### Pimcore version

11.x

### Steps to reproduce

- Create a Testpage in Pimcore
- Enable Full Page Cache
- Load Page into Cache (visit the Page - make sure you're not logged into Pimcore-Backend)
- Log into Backend and make some changes to the Page
- Log out
- Visit the Page again

### Actual Behavior

- the changes are not shown

### Expected Behavior

- saving the Document should clear related Cache-Keys in the Full-Page-Cache

**Comment by bitbirddev** [comment]
Additionally it seems like in the backend, the Cache => Clear Full Page Cache - Button doesn't actually clear the cache.

**Comment by bitbirddev** [comment]
[here is where the Cache is cleared via the Button in the Backend](https://github.com/pimcore/admin-ui-classic-bundle/blob/1eeb2536ebb3f8e7f596743ef9a214f582d8cd4a/src/Controller/Admin/SettingsController.php#L645)

[here is where the Cache gets cleared when saving a Document](https://github.com/pimcore/pimcore/blob/2b3bb4d10f4c32270589bb37557b932ca38d2a7e/models/Document.php#L372C20-L372C39)

[here is where the cache-entry is created](https://github.com/pimcore/pimcore/blob/2b3bb4d10f4c32270589bb37557b932ca38d2a7e/bundles/CoreBundle/src/EventListener/Frontend/FullPageCacheListener.php#L348)

**Comment by kingjia90** [comment]
thank you for reporting, just wondering, have you set the `lifetime` option by any chance?  If so, 
https://pimcore.com/docs/platform/Pimcore/Development_Tools_and_Details/Cache/Full_Page_Cache/#:~:text=If%20there%20is%20a%20lifetime%20the%20item%20stays%20in%20the%20cache%20even%20when%20it%20is%20changed%20until%20the%20TTL%20is%20over.

**Comment by kingjia90** [comment]
~confirming the issue, but~ for me `Clear Full Page Cache` works

update: it was a false positive, tried with lifetime and it was still displaying the cache until it expired to me

**Comment by bitbirddev** [comment]
@kingjia90 in my tests i think the lifetime was set to "null".

```yaml
    full_page_cache:
        enabled: true
        lifetime: null
        # exclude_cookie: ''
        exclude_patterns: '@^/health-check@'

```

**Comment by bitbirddev** [comment]
there is also another issue with the full page cache. 

when using frontend-prefixes, for example when you want to deliver your images via cdn. when frontend prefixes are enabled, on the first page load the srcset for each image is generated (no thumbnails) and then when the browser loads a URL of the srcset, the corresponding thumbnail is generated - but only the one the browser loads, assuming you have an srcset with 4 different formats and your browser requests the .webp thumbnail there are still 3 thumbs that haven't been created.

now on the ***SECOND*** pageload the frontend-prefixes get added to those entries in the srcset where a thumbnail has been generated already.

so the problem here is that the full page cache caches the ***FIRST*** pageload where we might have 0 thumbnails generated. Even the ***SECOND*** Pageload is not the one that should be cached due to missing frontend prefixes because not alle thumbnails have been generated.

So the question here is, how can the cache check if frontend-prefixes are used and if all thumbnails for a page are generated before caching it.

**Comment by kingjia90** [comment]
Could you please share the response header of the cached page from developer tools?
![image](https://github.com/pimcore/pimcore/assets/6014195/1797b0b2-7edb-403e-b945-ace318296d7c)

**Comment by bitbirddev** [comment]
This is from a Page that i've modified a minute ago.

<img width="991" alt="image" src="https://github.com/pimcore/pimcore/assets/15128942/5ca6222f-17c5-42a3-887a-de187dc7ab3b">

lifetime is set to 300 so i hope i'll see the changes within the next 5 minutes.
fact is that the cache is not cleared when the document is saved/published.

**Comment by bitbirddev** [comment]
this screenshot is taken right after editing and saving a document in pimcore. i was still logged in thats why the cache is disabled. the strange thing is that i cant see my changes in the frontend despite the cache being disabled.

<img width="888" alt="SCR-20240116-uboz" src="https://github.com/pimcore/pimcore/assets/15128942/e983b33a-fe91-4b83-a01c-87f1df6d5f94">

**Comment by bitbirddev** [comment]
this is after logging out from the backend. my content is behind a login in the frontend so it also makes sense here that the cache is disabled... but my changes are still not shown...

<img width="817" alt="SCR-20240116-ucst" src="https://github.com/pimcore/pimcore/assets/15128942/843e21ef-4bab-4f67-bb6d-b7c897e63906">

**Comment by bitbirddev** [comment]
Hitting "Clear Full Page Cache" didnt work so i cleared the data cache
<img width="968" alt="image" src="https://github.com/pimcore/pimcore/assets/15128942/3ef2234f-5142-4253-888f-7b3867e53c7c">

after clearing the cache the changes are visible in the frontend

<img width="560" alt="SCR-20240116-udta" src="https://github.com/pimcore/pimcore/assets/15128942/0cd54cdb-e321-49fd-9206-4b9e39f419f4">

**Comment by hadl** [comment]
@bitbirddev  https://github.com/pimcore/pimcore/issues/16453#issuecomment-1889038033  may be fixed with https://github.com/pimcore/pimcore/pull/16467

**Comment by bitbirddev** [comment]
> @bitbirddev [#16453 (comment)](https://github.com/pimcore/pimcore/issues/16453#issuecomment-1889038033) may be fixed with #16467

@hadl: i don't see any relation to this Bug to be honest, at least not for the full page cache clearing problem.

**Comment by fashxp** [comment]
@bitbirddev what kind of changes are you doing? 
Just tried to reproduce this with a simple document and a text editable. Everything worked like expected. 

If a page is delivered from full-page-cache, you should see `X-Pimcore-Output-Cache-Tag:` header in the response. Do you see that?
![image](https://github.com/pimcore/pimcore/assets/8792145/4353e1ad-23ee-4d83-9f69-f44ceb2bcd2f)

Maybe, you have activated static page generator with some livetime? But also with that activated, in my tests the response is updated after document is saved. 
![image](https://github.com/pimcore/pimcore/assets/8792145/e34893e8-22b2-40d2-a890-c17c21f6510a)

**Comment by fashxp** [comment]
> there is also another issue with the full page cache.
> 
> when using frontend-prefixes, for example when you want to deliver your images via cdn. when frontend prefixes are enabled, on the first page load the srcset for each image is generated (no thumbnails) and then when the browser loads a URL of the srcset, the corresponding thumbnail is generated - but only the one the browser loads, assuming you have an srcset with 4 different formats and your browser requests the .webp thumbnail there are still 3 thumbs that haven't been created.
> 
> now on the _**SECOND**_ pageload the frontend-prefixes get added to those entries in the srcset where a thumbnail has been generated already.
> 
> so the problem here is that the full page cache caches the _**FIRST**_ pageload where we might have 0 thumbnails generated. Even the _**SECOND**_ Pageload is not the one that should be cached due to missing frontend prefixes because not alle thumbnails have been generated.
> 
> So the question here is, how can the cache check if frontend-prefixes are used and if all thumbnails for a page are generated before caching it.

Please create a separate issue for that, and maybe you even have an idea how to solve it.

**Comment by bitbirddev** [comment]
@fashxp just had that problem again.

I've changed the contents of a wysiwyg editable (added that "Datenschutz-Einstellungen" Link). Then i've saved and published the document. No Errors popping up, everything seems fine.

<img width="1148" alt="image" src="https://github.com/pimcore/pimcore/assets/15128942/40e5904f-1730-4eed-a492-0e12fcd7d07a">

When opening the page in the frontend i see the old version... even though the cache should be completely disabled because i'm still logged in. Im using the real frontend link not a Version-Preview Link etc. My Browser Cache is also disabled.

<img width="1391" alt="SCR-20240126-pzor" src="https://github.com/pimcore/pimcore/assets/15128942/d136f57c-e47c-444d-9b77-861127fbe8fa">

this is my cache configruation:
```yaml
framework:
  cache:
    prefix_seed: '%env(REDIS_CACHE_PREFIX_SEED)%'
    pools:
      pimcore.cache.pool:
        public: true
        default_lifetime: 31536000 # 1 year
        adapter: cache.adapter.redis_tag_aware
        provider: 'redis://%env(REDIS_CACHE_HOST)%/%env(REDIS_CACHE_DB)%'

```

this is my full page cache config
```yaml
  full_page_cache:
    enabled: true
    lifetime: 300
    # exclude_cookie: ''
    exclude_patterns: '@^/health-check@'
```

Static Page generation is disabled.

The changes are only reflected if i clear the Cache manually 

<img width="578" alt="SCR-20240126-qdxa" src="https://github.com/pimcore/pimcore/assets/15128942/7878f4aa-1b42-4e33-9a36-98f0c13122fe">

**Comment by fashxp** [comment]
Could you please try to debug that on your end?
Maybe also try once without redis. Thy very much.

**Comment by fashxp** [comment]
@bitbirddev any new insights on that one? thx for the update.

**Comment by bitbirddev** [comment]
@fashxp i did some further research and it seems like this was a problem with tinymce removing tags in combination with the new 2000 char limit in symfonys html_sanitizer. i think we can close this for now. if the problem occurs again i'll open a new issue.

**Comment by fashxp** [comment]
thx for checking and sharing!
