### ISSUE TITLE
[Bug]: Unit conversion with offset returns incorrect values

### ISSUE THREAD

**Issue by beheist** [pimcore/pimcore#16470]
### Pimcore version

11.1.4

### Steps to reproduce

- Create two units that depend on each other with a conversion factor, like Celsius and Fahrenheit in the docs (https://pimcore.com/docs/platform/Pimcore/Objects/Object_Classes/Data_Types/Number_Types/#quantity-value-unit-conversion):  
![image](https://github.com/pimcore/pimcore/assets/10347669/a0868580-de70-4944-9a3d-48052e1fe58a)
- Create an object class with a quantity value field that allows both units
- Check the "automatic conversion" box

### Actual Behavior

When switching between units, conversion works correctly, using the following formula:
°F = °C * 1.8 + 32

### Expected Behavior

The conversion applies the incorrect formula.
Instead of the formula above, the following is applied:
°F = °C * **1/1.8** + 32
This occurs only if an offset is used.

**Comment by beheist** [comment]
Sorry, I mixed up the expected and actual behaviors here. Hope you see the problem anyway ;)
When repeatedly switching between units in the object edit screen, the values "jump around" instead of just switching between two values.

**Comment by fashxp** [comment]
@BlackbitDevs since the original formula came from you, could you please have a look at this. Thx very much.

**Comment by Maksonis** [comment]
I think only documentation should be updated in with more details about formula:

![image](https://github.com/pimcore/pimcore/assets/17277953/a464f4f9-d93f-440a-93cf-0bc69dd5bf54)

since formula is:

`$convertedValue = ($quantityValue->getValue() * $fromUnit->getFactor() - $fromUnit->getConversionOffset()) / $toUnit->getFactor() + $toUnit->getConversionOffset();`

Formula is fine, since you can multiply/divide units with offset when converting.

**Comment by beheist** [comment]
Hey @fashxp and @Maksonis, thanks for your feedback and sorry for my late reply. I completetely missed the notifications on this one.
While it does help to make the docs more clearer, there is still an issue imho. What if I want to maintain more than one alternative unit? That would not be possible with the current setup. Also, don't you think it is a bit counterintuitive to maintain the offset and factor for the alternative unit in the base unit's row?
WDYT?
