### ISSUE TITLE
Editing a grid value only works the first time for column editors (vs. cell editors)

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1650]
![image](https://user-images.githubusercontent.com/142037/27636708-049b4e1a-5c0d-11e7-94da-8b460769c3f8.png)

**Comment by weisswurstkanone** [comment]
This has nothing to do with inheritance. There are "static" column editors (input field, textarea) and "dynamic" cell editors which need to change their behavior depending on the actual options (e.g. dynamic select)

**Comment by weisswurstkanone** [comment]
build 70
