### ISSUE TITLE
[Pimcore4] Object Grid: Batch assignment of objects doesn't work

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1651]
![image](https://user-images.githubusercontent.com/142037/27643778-4a957282-5c22-11e7-96d8-087146d5d250.png)

![image](https://user-images.githubusercontent.com/142037/27643806-5d025692-5c22-11e7-84b6-c5ed189b38ba.png)

+ also check MultiHref  (Advanced) + Objects Metadata

**Comment by weisswurstkanone** [comment]
build 4089
