### ISSUE TITLE
[Improvement]: Allow headings in the html wysiwyg sanitizer

### ISSUE THREAD

**Issue by daves-weblab** [pimcore/pimcore#16521]
### Improvement description

Currently in the WYSIWYG sanitizer config doesn't support h2,h3,h4,h5 and h6 only h1 is allowed. I suppose those heading tags should be allowed as well

See the config for reference:
https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/config/pimcore/default.yaml#L71

**Comment by jdreesen** [comment]
I think this has already been fixed by #16229 (which is not yet released).

**Comment by brusch** [comment]
Hmm, `h1` has been there before #16229 🤔 
@daves-weblab can you maybe check and debug this? Thanks a lot!

**Comment by jdreesen** [comment]
That's what he said:

> the WYSIWYG sanitizer config doesn't support h2,h3,h4,h5 and h6 **only h1 is allowed**.

**Comment by brusch** [comment]
Thanks 🤦
Anyone who can read has a clear advantage ... 😂

**Comment by daves-weblab** [comment]
Yeah when I add the other tags by overriding the config from outside, it works fine. h1 as mentioned also worked before.

**Comment by brusch** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16229
