### ISSUE TITLE
[Bug]: Admin interface language can not be changed anymore 

### ISSUE THREAD

**Issue by MagPim** [pimcore/pimcore#16548]
### Pimcore version

11.1.5

### Steps to reproduce

Tested on demo.pimcore.fun.
Admin default language can be changed in the system settings and set to a different language. Unfortunately, after updating the BO, we still get English like if nothing had changed. The language has been correctly saved in the configuration but admin remains in English. 
I have the same behaviour with a different Pimcore 11 installation. 

### Actual Behavior

I can change the default lauguage and save but English remains as default admin language.

### Expected Behavior

I should load Pimcore admin in the set language.

**Comment by blankse** [comment]
@MagPim The language of the admin interface can be set for every user. You need to edit the profile:
![Screenshot 2024-02-02 144611](https://github.com/pimcore/pimcore/assets/998558/ec1ff6d4-81bd-43a6-bf58-883d5a1fe758)
And set there the language:
![Screenshot 2024-02-02 144616](https://github.com/pimcore/pimcore/assets/998558/1012c32e-b870-44a4-8bcb-7ae671dd3d9c)
It works in the actual demo:
https://demo.pimcore.fun/admin/

**Comment by MagPim** [comment]
Ok thanks, The behaviour is different than before. 
I will close this request then.

**Comment by blankse** [comment]
I haven't noticed any change in behavior. This was already the case in the older Pimcore versions. The default language should be used for new users. The language remains unchanged for those already created.

**Comment by MagPim** [comment]
![image](https://github.com/pimcore/pimcore/assets/39189262/2d55634d-36b4-4bf3-9f0d-f5fb499bcbe1)
I mean this used to work...

**Comment by blankse** [comment]
I think since I use Pimcore (since version 5.2)  I always set the language at the users. There is no option to set a empty language to a user. So I don't know what the effect of this setting. 

@brusch @fashxp Do you know? Is this a old field before the user have a language field?

**Comment by MagPim** [comment]
The user always had language field but we could set the default admin interface here for the user admin... 
The question is more now : why do we still have this field in the system settings if it does not work...  Not a big deal... 
Thanks

**Comment by blankse** [comment]
Maybe the admin user had in older version a empty language field in the db. It can be possible to create users via PHP with empty language field. Than this option is the default for this users. 

Should we extend the language select in the admin interface with a "default"/"empty" option?

**Comment by MagPim** [comment]
We will see if someone replies but I closed this ticket, not a big deal. Thanks

**Comment by fashxp** [comment]
I would need to investigate what the reason for that setting field is. Don't know of a specific change of behavior there.
