### ISSUE TITLE
[Bug]: Higher bundle priority is disregarded if set once

### ISSUE THREAD

**Issue by mattamon** [pimcore/pimcore#16544]
### Pimcore version

11.1

### Steps to reproduce

1. Implement a bundle and register a dependent bundle with a priority.
2. Implement another bundle and register the same bundle as in step one dependent bundle with a higher priority.

### Actual Behavior

It depends which bundles of the two is getting loaded first. Once the priority is set for a dependent bundle it cannot be changed.

### Expected Behavior

The highest priority is used and not the one from the first loaded bundle.

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16546
