### ISSUE TITLE
[Bug]: After download, I can't see the downloaded file, for example, if I downloaded the original file in web format, print format, or Office format. I am unable to open the image.

### ISSUE THREAD

**Issue by pimcoreanand** [pimcore/pimcore#16557]
### Pimcore version

v11.1.4

### Steps to reproduce

[Bug]: After download, I can't see the downloaded file, for example, if I downloaded the original file in web format, print format, or Office format. I am unable to open the image.

![image](https://github.com/pimcore/pimcore/assets/158617745/0cb820a8-d029-4e8c-acbe-96855676526b)

### Actual Behavior

[Bug]: After download, I can't see the downloaded file, for example, if I downloaded the original file in web format, print format, or Office format. I am unable to open the image.

### Expected Behavior

How to download file and see original format or particular format

**Comment by pimcoreanand** [comment]
Can anyone help here?

**Comment by kingjia90** [comment]
I don't fully get the issue, works fine to me, can you reproduce it on the public demo?

**Comment by brusch** [comment]
@pimcoreanand please ensure you have Imagick installed properly. If all system requirements are met, please also share the file you're having issues with. Thanks

**Comment by pimcoreanand** [comment]
Hi All, 

I have already installed it but could not download file in particular format.

**Comment by blankse** [comment]
@pimcoreanand What do you expect from each download?

I see the following settings behind the buttons (which also work for me):
![image](https://github.com/pimcore/pimcore/assets/998558/d1e0e58a-d164-40c6-b97b-2fc2207f6ccb)

**Comment by pimcoreanand** [comment]
Thanks for valuable response.

I have found solution for that... chrome browser stopped to download file... we changed privacy security settings.. we can able to download now.
