### ISSUE TITLE
[Bug]:  The preview for this video is currently in progress. Please wait

### ISSUE THREAD

**Issue by pimcoreanand** [pimcore/pimcore#16550]
### Pimcore version

v11.1.4

### Steps to reproduce

After I uploaded video in pimcare admin panel. I could not preview uploaded video and it was showing this "The preview for this video is currently in progress. Please wait" I have installed and configured in Ubuntu system. 

### Actual Behavior

After I uploaded video in pimcare admin panel. I could not preview uploaded video and it was showing this "The preview for this video is currently in progress. Please wait" I have installed and configured in Ubuntu system. 

### Expected Behavior

After I uploaded video in pimcare admin panel. I could not preview uploaded video and it was showing this "The preview for this video is currently in progress. Please wait" I have installed and configured in Ubuntu system.

**Comment by pimcoreanand** [comment]
> ### Pimcore version
> v11.1.4
> 
> ### Steps to reproduce
> After I uploaded video in pimcare admin panel. I could not preview uploaded video and it was showing this "The preview for this video is currently in progress. Please wait" I have installed and configured in Ubuntu system.
> 
> ### Actual Behavior
> After I uploaded video in pimcare admin panel. I could not preview uploaded video and it was showing this "The preview for this video is currently in progress. Please wait" I have installed and configured in Ubuntu system.
> 
> ### Expected Behavior
> After I uploaded video in pimcare admin panel. I could not preview uploaded video and it was showing this "The preview for this video is currently in progress. Please wait" I have installed and configured in Ubuntu system.

Kindly help here to fix this issue

**Comment by blankse** [comment]
@pimcoreanand Did you config the maintenance cron job and the messenger worker? See https://pimcore.com/docs/pimcore/10.6/Development_Documentation/Getting_Started/Installation.html#page_5-Maintenance-Cron-Job

The video thumbnail will generated by the worker.

**Comment by pimcoreanand** [comment]
Thank you so Much, it is working

**Comment by pimcoreanand** [comment]
> @pimcoreanand Did you config the maintenance cron job and the messenger worker? See https://pimcore.com/docs/pimcore/10.6/Development_Documentation/Getting_Started/Installation.html#page_5-Maintenance-Cron-Job
> 
> The video thumbnail will generated by the worker.
