### ISSUE TITLE
Error Fatal error: Maximum function nesting level of '256' reached, aborting! during Installation

### ISSUE THREAD

**Issue by Lexipowder** [pimcore/pimcore#1656]
That are the first few line of the only page I see during installation. Version: latest download "unstable pimcore" Did i miss any necessary settings?

in vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\ParameterBag.php on line 88

1	0.0012	364520	{main}( )	...\app.php:0
2	0.0990	7555608	Symfony\Component\HttpKernel\Kernel->handle( )	...\app.php:21
3	0.1192	8070928	Symfony\Component\HttpKernel\HttpKernel->handle( )	...\Kernel.php:171
4	0.2771	12860984	Symfony\Component\HttpKernel\HttpKernel->handleException( )	...\HttpKernel.php:79
5	0.2780	12867176	Symfony\Component\EventDispatcher\EventDispatcher->dispatch( )	...\HttpKernel.php:230
6	0.2861	13015824	Symfony\Component\EventDispatcher\EventDispatcher->doDispatch( )	...\EventDispatcher.php:44
7	0.2861	13015824	call_user_func:{\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php:212} ( )	...\EventDispatcher.php:212
8	0.2861	13015824	Pimcore\Bundle\CoreBundle\EventListener\ResponseExceptionListener->onKernelException( )	...\EventDispatcher.php:212
9	0.2861	13015824	Pimcore\Bundle\CoreBundle\EventListener\ResponseExceptionListener->handleErrorPage( )	...\ResponseExceptionListener.php:77
10	0.2949	13431776	Pimcore\Templating\Renderer\ActionRenderer->render( )	...\ResponseExceptionListener.php:117
11	0.2949	13431832	Symfony\Bundle\FrameworkBundle\Templating\Helper\ActionsHelper->render( )	...\ActionRenderer.php:62
12	0.2949	13431920	Symfony\Component\HttpKernel\DependencyInjection\LazyLoadingFragmentHandler->render( )	...\ActionsHelper.php:52
13	0.2975	13476056	Symfony\Component\HttpKernel\Fragment\FragmentHandler->render( )	...\LazyLoadingFragmentHandler.php:79
14	0.2975	13476456	Symfony\Component\HttpKernel\Fragment\InlineFragmentRenderer->render( )	...\FragmentHandler.php:91
15	0.3038	13644712	Symfony\Component\EventDispatcher\EventDispatcher->dispatch( )	...\InlineFragmentRenderer.php:92
16	0.3038	13644712	Symfony\Component\EventDispatcher\EventDispatcher->doDispatch( )	...\EventDispatcher.php:44
17	0.3038	13644712	call_user_func:{\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php:212} ( )	...\EventDispatcher.php:212

**Comment by brusch** [comment]
Can you give us a few more details? 
What is the actual error message (the above is only the stack trace)? At which step the message is shown ...? 

Thanks

**Comment by Lexipowder** [comment]
It happens before any step. Please see below the screenshots.

![error1](https://user-images.githubusercontent.com/20427487/27676118-03454dc2-5cad-11e7-9c04-e373789b42c7.PNG)
![error2](https://user-images.githubusercontent.com/20427487/27676130-0dc207e0-5cad-11e7-9e7f-c5c30be4c5de.PNG)

**Comment by brusch** [comment]
To install pimcore, please open http://localpimcire/install.php
