### ISSUE TITLE
[Bug]: CKEditor notification bug

### ISSUE THREAD

**Issue by snmabaur** [pimcore/pimcore#16573]
### Pimcore version

10.6.9

### Steps to reproduce

Install pimcore v10.6.9, create a class with a WYSIWYG field

### Actual Behavior

Opening the newly created dataobject I get an error line across the screen or inside the WYSIWYG field

<img width="1716" alt="Bildschirmfoto 2024-02-08 um 09 33 21" src="https://github.com/pimcore/pimcore/assets/92374296/5649750e-ae07-407f-9824-17c025e8c4c3">
<img width="1717" alt="Bildschirmfoto 2024-02-08 um 09 33 34" src="https://github.com/pimcore/pimcore/assets/92374296/b8dffb1a-4638-484a-be38-98043a905801">
<img width="1717" alt="Bildschirmfoto 2024-02-08 um 09 35 39" src="https://github.com/pimcore/pimcore/assets/92374296/f2071de0-6d9a-42b9-a320-2cd751108c3d">

### Expected Behavior

This line shouldn't go across the screen or inside the field... and only show if in debug mode not in production mode

**Comment by brusch** [comment]
@snmabaur Thanks for reporting the issue, however, v10 has already reached it's end of life and CKEditor has been replaced by TinyMCE 😉

**Comment by LosHawlos** [comment]
@brusch is/will this be fixed in the LTS Version of the enterprise subscription?

**Comment by brusch** [comment]
@LosHawlos for LTS we're going to implement this workaround https://github.com/pimcore/pimcore/issues/16574#issuecomment-1933870255 which disables the error message. 
We won't provide a fix, because only severity "critical" and upwards is covered by LTS.
