### ISSUE TITLE
[Bug]: CKEditor security vulnerability message

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#16574]
### Pimcore version

v10.6.9

### Steps to reproduce

Open anything in the Admin-Panel that has a WYSIWYG-Editable that still uses the CK-Editor.

### Actual Behavior

There is a message displayed warning me about some security vulerability.
![image](https://github.com/pimcore/pimcore/assets/142798779/cb010da4-4199-4784-94ba-8af9d3294420)

### Expected Behavior

I can use the editor normally without interruption.

**Comment by ghost** [comment]
As a workaround one can add this JavaScript code and inject it into the admin panel as described here: [https://pimcore.com/docs/pimcore/10.6/Development_Documentation/Documents/Editables/WYSIWYG.html#page_Registering-global-configuration-via-events](https://pimcore.com/docs/pimcore/10.6/Development_Documentation/Documents/Editables/WYSIWYG.html#page_Registering-global-configuration-via-events)


```
CKEDITOR.on('instanceCreated', function( event ) {
  let editor = event.editor;
  editor.on('configLoaded', function() {
    // Suppress warnings about CKEditor being insecure.
    editor.config.versionCheck = false;
  });
});
```

**Comment by LosHawlos** [comment]
Hi @jlkleanatic,
that is the same solution that I found earlier today. Works fine for me.

**Comment by LosHawlos** [comment]
Duplicate of #16573

**Comment by youwe-petervanderwal** [comment]
> As a workaround one can add this JavaScript code and inject it into the admin panel as described here: https://pimcore.com/docs/pimcore/10.6/Development_Documentation/Documents/Editables/WYSIWYG.html#page_Registering-global-configuration-via-events
> 
> ```
> CKEDITOR.on('instanceCreated', function( event ) {
>   let editor = event.editor;
>   editor.on('configLoaded', function() {
>     // Suppress warnings about CKEditor being insecure.
>     editor.config.versionCheck = false;
>   });
> });
> ```

Adding to add that the event EDITMODE_JS_PATHS only applies to the document editables. I used the following event listener so that the javascript is applied to both DataObject Wysiwyg fields as document editables.

```
#[AsEventListener(BundleManagerEvents::JS_PATHS)]
#[AsEventListener(BundleManagerEvents::EDITMODE_JS_PATHS)]
public function disableCkeditorVersionWarning(PathsEvent $event): void
{
    $event->setPaths([
        ...$event->getPaths(),
        '/admin-static/js/disable-ckeditor-version-warning.js',
    ]);
}

```
