### ISSUE TITLE
[Bug]: links do not resolve correctly on multi-site environment

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#16595]
### Pimcore version

11.1.5

### Steps to reproduce

1. Make sure that you have a multi-site environment (one installation with two different sites).
2. Create a document with a WYSIWYG text field.
3. Type somthing into this field.
4. Link a word of this text via drag and drop from the document tree.

### Actual Behavior

1. The site is part of the link, for example: /sitename/de/foo
2. When you click on the link, it resolves to domain-of-the-site.com/**sitename**/de/foo

(Please note the bold highlight, that's the important difference to the expected behavior.)

### Expected Behavior

1. The site is part of the link, for example: /sitename/de/foo (just /de/foo would be better, but that's the same behavior as in Pimcore 10, therefore I don't see that as a bug)
2. When you click on the link, it resolves to domain-of-the-site.com/de/foo (without the site name)

This is how it worked in my projects with Pimcore 10. With Pimcore 11, there is still the site name in the link and therefore all internal links are broken until you manually remove the site name from the path.

**Comment by cadeyrn** [comment]
Coud someone please have a look? This is a critical issue for multi-site environments as every link in documents is broken if you don't manually correct them after dragging a document from the document tree. We, as an agency, can take care of the issue. But we can't expect that our customers do that.

**Comment by GALPR** [comment]
I am running into the same issue. Are there any updates or at least a general direction in which to look for a potential fix?

**Comment by kingjia90** [comment]
Thank you for reporting, i've provided a PR https://github.com/pimcore/pimcore/pull/16892 that may fixes it, could you please have a look and help reviewing that?

**Comment by GALPR** [comment]
@kingjia90 LGTM

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16892

Thank you again for reporting and check on it
