### ISSUE TITLE
[BUG, EC]: Workflow Actions - publish rights necessary

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#16616]
### Pimcore version

11.x

### Steps to reproduce

Create setup as denoted below.

### Actual Behavior

For accessing the workflow actions, a user needs publish rights (tested with assets).

### Expected Behavior

Fix rights.

**Comment by kingjia90** [comment]
The normal button seem not wrapped under any specific permission
https://github.com/pimcore/admin-ui-classic-bundle/blob/bf05f0bf7c43b9a2fac8e06b467f78a9529c7b90/public/js/pimcore/asset/asset.js#L353-L365

See also screenshot, works fine
![image](https://github.com/pimcore/pimcore/assets/6014195/6c6dd357-3081-4ffe-a932-13b2ddd9f821)
as i don't have the `publish` right as per https://github.com/pimcore/admin-ui-classic-bundle/issues/435


Maybe is a Portal Engine issue

**Comment by ghost** [comment]
Closed as agreed with customer.
