### ISSUE TITLE
[Bug]: Core migration Version20230616085142 does not run properly when upgrading from 10.6 to 11.5

### ISSUE THREAD

**Issue by muratbinerbay** [pimcore/pimcore#16620]
### Pimcore version

11.1.5

### Steps to reproduce

- Run migrations after updating to Pimcore 11.1.5 from 10.6.7
- Foreign key constraint on `object_metadata_%` tables is not re-created

### Actual Behavior

- Foreign key constraint on `object_metadata_%` tables are not dropped and recreated because the migration looks for the foreign key with the wrong name.
- Foreign key name is `fk_object_metadata_%__o_id` but the migration is looking for `fk_object_metadata_%__id`
- This leads to an exception when trying to delete any kind of object (regardless if it is related to the metadata tables)

> Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails

### Expected Behavior

The migration drops & re-creates the foreign keys on `object_metadata_%`.

I assume the migration script could have checked for both names to support upgrades from 10.6.x ( `fk_object_metadata_%__o_id` and  `fk_object_metadata_%__id`)

**Comment by ibousfiha** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16621
and https://github.com/pimcore/pimcore/pull/16657
