### ISSUE TITLE
`.env` files processed twice, booting not consistent between web and CLI

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#16638]
### Improvement description

Pimcore is using Symfony Runtime for bootstrapping.
Symfony runtime is using DotEnv (when available) and does parsing `.env` file. 

Pimcore is also using DotEnv here: https://github.com/pimcore/pimcore/blob/2ab61dfd32e1734eb846ad8abe2cf2921ebddf04/lib/Bootstrap.php#L125

So `.env'  file are getting processed twice during bootstrapping. 

Also booting is not consistent between CLI and web.
For web `Bootstrap::bootstrap()` is called before the callback: 
https://github.com/pimcore/demo/blob/6978c2d36e9f580e22654e9970aa411487f320e0/public/index.php#L23

however for CLI, it's called inside the callback as part of `startupCli()`: 
https://github.com/pimcore/demo/blob/6978c2d36e9f580e22654e9970aa411487f320e0/bin/console#L36

This could cause very weird behavior, especially when doing some stuff in `config/pimcore/startup.php`, e.g. overriding env variables, which are then again overridden from values in `.env`.

**Comment by kingjia90** [comment]
Hope i got the issue right, it seems that by adding `$_ENV['APP_RUNTIME_OPTIONS'] = ['disable_dotenv' => true];` to `config/pimcore/startup.php` will be fixing it.

The "second time" that env get processed is done by `/vendor/autoload_runtime.php`
![image](https://github.com/pimcore/pimcore/assets/6014195/e9809299-d566-4779-9eb0-5d84e6f13627)

See also https://github.com/symfony/symfony/blob/635a9f1bcc48386e5013bcf0454b5857d407cc78/src/Symfony/Component/Runtime/SymfonyRuntime.php#L38


If it's the right fix, it's something that we need to add to the documentation or set by default?

**Comment by brusch** [comment]
To be consistent I'd do the following: 
1. Move `Bootstrap::bootstrap();` in `index.php` into the callback function, then it's consistent with `bin/console`. 
This is something that we'd need to include in upgrade notes, since this change needs to be made in the projects repo. 
2. I'd remove `self::prepareEnvVariables();` as it's covered by Runtime

Shouldn't break anything right?

**Comment by kingjia90** [comment]
Thank you for the feedback!

On index.php and CLI seem that the suggested change would be fine and safe so far.

Looks like it would be breaking the install script instead
https://github.com/pimcore/pimcore/blob/f8a4c7aed335d5e90ec1bb1e0da35435bec29c0a/bin/pimcore-install#L46
since it's not loading the runtime one
https://github.com/pimcore/pimcore/blob/f8a4c7aed335d5e90ec1bb1e0da35435bec29c0a/bin/pimcore-install#L30
So if i got correctly, `prepareEnvVariables` was more for `PIMCORE_COMPOSER_PATH` to be changed by the value set in `env` before defining the Constant or something like that

**Comment by brusch** [comment]
@kingjia90 
`prepareEnvVariables()` comes from a time where Symfony Runtime didn't exist 😉 Since it's `private` I'd assume it can go completely. 

Regarding the installer: 
I'd refactor the installer to use Runtime as well - so that we're consistent - would make sense, right?

**Comment by kingjia90** [comment]
Thank you for the feedback, i've applied the requested change to https://github.com/pimcore/pimcore/pull/16652 and seems working fine so far

**Comment by danielerne** [comment]
After Updating to 11.2.0 .env variables are not set anymore. 
Has this change caused this problem? If I downgrade to 11.1.5 it works again.

Could this be that our project was migrated from Pimcore 10?


Our index.php - looks like this:

```
use Pimcore\Tool;
use Symfony\Component\Debug\Debug;
use Symfony\Component\HttpFoundation\Request;

include __DIR__ . "/../vendor/autoload.php";

\Pimcore\Bootstrap::setProjectRoot();
\Pimcore\Bootstrap::bootstrap();

$request = Request::createFromGlobals();

// set current request as property on tool as there's no
// request stack available yet
Tool::setCurrentRequest($request);

/** @var \Pimcore\Kernel $kernel */
$kernel = \Pimcore\Bootstrap::kernel();

// reset current request - will be read from request stack from now on
Tool::setCurrentRequest(null);

$response = $kernel->handle($request);
$response->send();

$kernel->terminate($request, $response);

```

**Comment by jdreesen** [comment]
You should probably update your `index.php` (and `bin/console`) to use [Symfony Runtime](https://symfony.com/doc/current/components/runtime.html). 

See: https://github.com/pimcore/skeleton/blob/11.x/public/index.php

**Comment by blankse** [comment]
@brusch @kingjia90 Should be added to the upgrade notes if Symfony Runtime is required now in Pimcore 11.
https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/Updating_Pimcore/V10_to_V11/

**Comment by brusch** [comment]
@danielerne @jdreesen @blankse plz have a look at #16796 - i's kind of a poor mans solution, but should do the job for backwards compatibility. Thanks for your feedback 😊

**Comment by dpfaffenbauer** [comment]
@brusch Is Pimcore 11.1 compatible with runtime? I am having the issue to support both in CoreShop for testing purposes.

**Comment by brusch** [comment]
@dpfaffenbauer yeah, should be, since parts were using it already before, see: https://github.com/pimcore/skeleton/pull/183/files 
This whole topic was just about making it consistent throughout all packages.

**Comment by Cruiser13** [comment]
@brusch we just updated to pimcore 11.2.2 and now _APP_ENV=prod_ from our .env file is ignored by CLI. 
**php bin/console about** will output:

>   Type                 App\Kernel                                 
>   Environment          dev                                        
>   Debug                false         

We adjusted our index.php to the one from skeleton: https://github.com/pimcore/skeleton/blob/11.x/public/index.php

Is this intended behaviour?

**Comment by jdreesen** [comment]
Did you also adjust your `bin/console`? => https://github.com/pimcore/skeleton/blob/11.x/bin/console

**Comment by Cruiser13** [comment]
Thank you @jdreesen totally missed that. Added it to the docs.

**Comment by brusch** [comment]
@Cruiser13 I'm wondering why you're experiencing the issue ... how did your `bin/console` before? 
Because acutally `bin/console` didn't change recently, see: 
https://github.com/pimcore/skeleton/commits/11.x/bin/console 

I'd assume you missed the upgrade of the file earlier 😉

**Comment by Cruiser13** [comment]
@brusch you are right, looks like we missed https://github.com/pimcore/skeleton/commit/b1075d646d4303df849a4c709f3de33868e0d577 before. Worked fine until the update though.
I guess we need to have a closer look at the skeleton project on updates as some changes do not seem to be documented.

**Comment by patrick-rudolph-umusic** [comment]
I'm getting the same error when running tests. How do I need to setup my tests/bootstrap.php in order to work again? The one used in skeleton does not help

**Comment by agdrs** [comment]
> I'm getting the same error when running tests. How do I need to setup my tests/bootstrap.php in order to work again? The one used in skeleton does not help

@patrick-rudolph-umusic 
We faced the same issue and fixed it with following tests/bootstrap.php (based on the standard symfony bootstrap.php)

```php
declare(strict_types=1);

use Pimcore\Bootstrap;
use Symfony\Component\Dotenv\Dotenv;

include __DIR__ . '/../vendor/autoload_runtime.php';

if (method_exists(Dotenv::class, 'bootEnv')) {
    (new Dotenv())->bootEnv(dirname(__DIR__).'/.env');
}

Bootstrap::setProjectRoot();
Bootstrap::bootstrap();

```
