### ISSUE TITLE
[Bug]: Wysiwyg editors all use the same max length (max characters)

### ISSUE THREAD

**Issue by notsure** [pimcore/pimcore#16630]
### Pimcore version

11.1.5

### Steps to reproduce

1. Create a new or open an existing data object class definition
2. Edit or add a new wysiwyg field
3. Add some max characters value (eg. 10)
4. Add one more wysiwyg field without a max length
5. Visit the data object or create a new one
6. Try to enter more than 10 chars to the field and you will see an error (which is fine, by the way ESC should close this window, which it doesn't) 
7. Try to enter more than 10 chars in the second field and you will see the same error.
8. ONE MORE THING: this same error will now also occur in any other wysiwyg in any other editor.

### Actual Behavior

It seems like the max chars config is used for all wysiwyg fields across the page.

This leads to the issue, that there is a max length error in all wysiwyg fields no matter if a max length is defined for them or not.

### Expected Behavior

Only the wysiwyg field with a defined max length should throw the error.

**Comment by notsure** [comment]
Hi There, 
any progress on this one?

best regards

**Comment by fashxp** [comment]
we have it on our todo list, but there is no ETA yet. 
a PR would speed things up certainly ;-)

**Comment by kingjia90** [comment]
@notsure Thank you for reporting and your patience!

Please have a look at #16975 and give it a try, i have also considered the feedback that the error popup can't be closed by ESC, made it more less intrusive instead by highlighting the text area with a red border and text on hover (html title)

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16975
