### ISSUE TITLE
[Bug]: Login as this user in a different browser don't work with long usernames

### ISSUE THREAD

**Issue by storbahn** [pimcore/pimcore#16636]
### Pimcore version

Pimcore 11

### Steps to reproduce

Create a new user with long username e.g. abcdefghijklmnopqrstuvwxyz1234567890 (or long email adresses) and set a password for this user.

### Actual Behavior

The user can't be logged-in and gets the error "Token does not match any user." when using the process "Login as this user in a different browser"

The generated token for the url and in the db (passwordRecoveryToken in users) differ. The token in the db is cutted after 255 chars.

### Expected Behavior

The user can be logged-in and the both token db and url are equal.

**Comment by kingjia90** [comment]
Resolved by https://github.com/pimcore/pimcore/pull/16533

**Comment by storbahn** [comment]
> Resolved by #16533

thanks :)
