### ISSUE TITLE
[Bug]: Hotspotimage::getImage() is typed to return `Asset/Image|null` but can return `Asset/Unknown` causing a TypeError

### ISSUE THREAD

**Issue by IronSean** [pimcore/pimcore#16648]
### Pimcore version

10.6

### Steps to reproduce

Currently it depends on data on a system I can't share, but the steps to reproduce are essentially
1. Call `->save()` on a DataObject with an ImageGallery.
2. Eventually as part of the process `Pimcore\Model\DataObject\Data\Hotspotimage::getImage()` is called

### Actual Behavior

`TypeError: Return value must be of type ?Pimcore\Model\Asset\Image, Pimcore\Model\Asset\Unknown returned` is thrown, because `Pimcore\Model\DataObject\Data\Hotspotimage` defines the return types as `?Asset\Image` but `Asset\Unknown` appears possible to return instead. 

Worse, a messenger Handler class calling this method will cease processing new messages, and keep an open lock on the messenger_messages table until the consumer thread is stopped and restarted after this error is thrown.

```
-previous: TypeError {#1
      #message: "Pimcore\Model\DataObject\Data\Hotspotimage::getImage(): Return value must be of type ?Pimcore\Model\Asset\Image, Pimcore\Model\Asset\Unknown returned"
      #code: 0
      #file: "./vendor/pimcore/pimcore/models/DataObject/Data/Hotspotimage.php"
      #line: 159
      trace: {
        ./vendor/pimcore/pimcore/models/DataObject/Data/Hotspotimage.php:159 { …}
        ./vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Hotspotimage.php:440 { …}
        ./vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/ImageGallery.php:455 { …}
        ./vendor/pimcore/pimcore/models/DataObject/Concrete.php:386 { …}
        ./vendor/pimcore/pimcore/models/DataObject/AbstractObject.php:943 { …}
        ./vendor/pimcore/pimcore/models/DataObject/Concrete.php:204 { …}
        ./vendor/pimcore/pimcore/models/DataObject/AbstractObject.php:773 { …}
        ./vendor/pimcore/pimcore/models/DataObject/Concrete.php:727 { …}
        ./src/Product/Services/ProductService.php:190 {
          App\Product\Services\ProductService->Update(ProductUpdateRequest $dataModel)^
          › 
          ›     $prod->save();
          › } catch (Exception $e) {
        }
```

### Expected Behavior

DataObject will save.
Perhaps instead of `Asset/Unknown` it should be a `null`, or perhaps the `Asset\Unkown` should be listed as a possible return type to not cause an unhandled `TypeError`.

**Comment by dpfaffenbauer** [comment]
I had the same thing today with a folder being returned. I am not sure what caused it, but it breaks the DataObject as you cannot open it in Backend.

**Comment by IronSean** [comment]
> I had the same thing today with a folder being returned. I am not sure what caused it, but it breaks the DataObject as you cannot open it in Backend.

Thanks, I forgot about that aspect. Products affected by this can't be saved via the API, or opened in the backend and viewed.

**Comment by IronSean** [comment]
If I were to try and make a Pr to address this (especially because the milestones seem to indicate it's being addressed in 11 but not 10), is the fix to acknowledge Asset/Unknown is a potential response from these methods, or to prevent the return of Asset/Unknown and instead return `null` from these methods?

**Comment by kingjia90** [comment]
Unfortunately Pimcore 10 is EOL, only security related topics would be considered for the LTS.
If you are opening a PR, suggesting to temporary base it on `11.x`, if you don't see it a branch `11.2` yet, we are tagging `11.2` before EOD and moved the milestone for that reason

**Comment by IronSean** [comment]
@kingjia90 this applies even for enterprise customers?

**Comment by kingjia90** [comment]
Yes, actually LTS itself is for enterprise customers only

**Comment by IronSean** [comment]
@kingjia90 The project I'm running into this on is a Pimcore 10 instance which is a Pimcore Enterprise licensee. We've got the 11 upgrade in progress, but it's not ready to go live yet.

However, I did finally track down the cause of the issue. There was a .psd file which was defined in some imageGallery relations. The .psd file was an Asset of type Unknown, but somehow was added to imageGallery relations (possibly with a datahub import). That caused any DataObjects with a reference to the .psd in their imageGalleries to fail to load in pimcore backend or programmatically. In this case we could safely delete the asset which fixed things for the DataObjects referencing it, but if that asset was required for other reasons (say a normal Relation field on another DataObject) deleting wouldn't have been an option. I'm also not positive if loading the DataObjects in the backend to fix it with a Command would be possible.

The true solution for this might involve preventing imageGallery images being added if they aren't of type Image, and/or more gracefully handling the situation where a non-image was somehow added to the gallery. If the dataObject could at least be loaded then it could be corrected either by hand or programatically. Given the imageHotspot serialized data even going into the database and removing the referenced image wasn't enough without recreating the hotspots object.

**Comment by kingjia90** [comment]
Thank you for clarifying that it was related to a `.psd` file.
I believe that in Pimcore 11 it's even more stricter in terms of types and would fatally throw a warning before reaching that point
https://github.com/pimcore/pimcore/blob/50340aa5ca234280894ce5b24db5851fd8d30856/models/DataObject/Data/Hotspotimage.php#L127

Could we close it as it is not possible to add any changes  to `10.6` and by considering that in Pimcore v11 it's better handled (eg. otherwise PHPStan would have reported it already)?
