### ISSUE TITLE
[Bug]: Missing translations for input types (booleanSelect, quantityValue ...)

### ISSUE THREAD

**Issue by root913** [pimcore/pimcore#16646]
### Pimcore version

v11.1.5

### Steps to reproduce

Enter Key Definitions and try to add key with on of types:
- rgbaColor
- booleanSelect
- quantityValue
- inputQuantityValue
- calculatedValue

### Actual Behavior

After adding keys they will appear without translation in key list.
![MicrosoftTeams-image](https://github.com/pimcore/pimcore/assets/3902450/b00b99a1-b5c3-467b-b8be-960793b12e96)

### Expected Behavior

Pimcore use type (eg. egbaColor) for translating.
Types mentioned above use different translations.
booleanSelect use "boolean_select"

Solution to this is to add translations for those fields coresponding with their type name.

**Comment by mattamon** [comment]
Solved with https://github.com/pimcore/admin-ui-classic-bundle/pull/452 and bundle release tag 1.5.0
