### ISSUE TITLE
not getting fieldcollection index when overriding block data for validation

### ISSUE THREAD

**Issue by Thejaswini-Rao-U** [pimcore/pimcore#16659]
### Pimcore version

6.6

### Steps to reproduce

i want to throw validation for the multiple blocks inside field collection.

i have overridden block.js for the validation to get run time block data and index.
im getting block data, but field collection index not getting..

i want to implement in ext js not using event listener on save & publish

### Actual Behavior

Example: if fieldcollection1 has block1 data has color dropdown => color1, color2, color2 etc, here i have selected color as color1
if fieldcollection1 has block2 data has color dropdown => color1, color2, color2 etc, here i have selected color as color2 
then before adding block3 in fieldCollection1, on click of adding block i have to throw error that you cant add any other block once color1 and color2 are choosen as per order. 

Here i get block data, there is no issue. but need to get fieldCollection index so that i can validate and throw exception for the specific field collection not for all field collection block.

### Expected Behavior

work

**Comment by fashxp** [comment]
Pimcore 6.6 is EOL
