### ISSUE TITLE
[Bug]: Display Issue with Localized Attribute Values

### ISSUE THREAD

**Issue by stephangmms** [pimcore/pimcore#16651]
### Pimcore version

11.1.5

### Description:
 
In Pimcore version 11.1.5, an issue has been identified where the display of localized attribute values in Many-to-Many-Relation/Advanced Many-to-Many-Relation/Many-to-Many-Object-Relation/Advanced Many-to-Many-Object-Relation attributes is not adhering to the selected display language of the object or the user's configured language setting.

![MicrosoftTeams-image (10)](https://github.com/pimcore/pimcore/assets/160856098/e0ea04db-267e-4173-9c2a-33dde2f7a2fa)
 
1. Configure Pimcore to use multiple languages.
2. Create reference objects with localized attribute values. see Category ID 559 "Sports Cars/Sportwagen"
3. Set up an Advanced Many-to-Many-Relation attribute. see Car ID 81 "Cobra 427"
4. Select a different language in the user settings (or in the object display).
5. The localized attribute values continue to display in the original language (an English one) rather than the chosen one.

### Actual Behavior

The localized attribute values remain in the original language, irrespective of the selected display language of the object or the user's chosen language.

### Expected Behavior

The localized attribute values should change according to the selected user's chosen language (or the display language of the object).
This (selected user's chosen language) corresponds to the behavior of the older Pimcore for example version 10.5.8.

**Comment by sl0wlydeadly** [comment]
Any updates?

**Comment by lukmzig** [comment]
Resolved by PR https://github.com/pimcore/pimcore/pull/16806
