### ISSUE TITLE
[Bug]: I have created New directory under /var/assets/ in Pimcore server but It is not showing on Pimcore admin panel.

### ISSUE THREAD

**Issue by pimcoreanand** [pimcore/pimcore#16658]
### Pimcore version

11

### Steps to reproduce

What should I do that if created directory from Ubuntu server then same should show in Pimcore admin panel

### Actual Behavior

What should I do that if created directory from Ubuntu server then same should show in Pimcore admin panel

### Expected Behavior

What should I do that if created directory from Ubuntu server then same should show in Pimcore admin panel

**Comment by dpfaffenbauer** [comment]
That's not how it works. Pimcore is not scanning your folder for files but just storing them there. You have to create the files in Pimcore to be shown in the folder on the server
