### ISSUE TITLE
[Bug]: method hasProperty() throws an error if object is new and not saved yet

### ISSUE THREAD

**Issue by hethehe** [pimcore/pimcore#16668]
### Pimcore version

11.x

### Steps to reproduce

run:
```
$newObject = new Xy();
$newObject->setParent($parent);
if( $newObject->hasProperty('property_name')) {
...
}
$newObject->save();
```

### Actual Behavior

throws an error:

> Pimcore\Model\Property::setCid(): Argument #1 ($cid) must be of type int, null given, called in /var/www/html/vendor/pimcore/pimcore/models/DataObject/AbstractObject/Dao.php on line 250

error is only thrown when $parent does have the property 'property_name'

### Expected Behavior

check if $newObject or the parent has a property 'property_name'.

**Comment by blankse** [comment]
@hethehe I created a PR: https://github.com/pimcore/pimcore/pull/16669

**Comment by hethehe** [comment]
Wow, that was quick - thank you
