### ISSUE TITLE
[Bug]: ApplicationLogger Bundle logs not stored in UTC

### ISSUE THREAD

**Issue by hanneslauritz3n** [pimcore/pimcore#16667]
### Pimcore version

v11.1.4

### Steps to reproduce

- Set timezone via YAML file
- Log something using the ApplicationLogger Bundle
- Check output in the ApplicationLogger which does not match the current timezone

### Actual Behavior

It appears that the timestamp stored in the database isn't in UTC format. Monolog utilizes the timezone specified in the YAML configuration file. For instance, if Berlin time (UTC+1) is configured, it will use this timezone to record entries in the database table. For instance, if I log something at 15:33 (Berlin timezone), it will be saved precisely like that in the database. However, the output in the backend, which employs the Date function in Typescript, also adheres to my browser's timezone, thus adding an extra hour to the output. Consequently, the displayed output becomes 16:33.

### Expected Behavior

The initial timestamp in the database should be UTC and not the timezone defined via config. So if i log something at 15:33 (berlin timezone) it should be stored as 14:33 (UTC). The final output using the date function would then be 15:33 as it would use my local timezone. It seems like there already was an [migration](https://github.com/pimcore/pimcore/pull/14741/commits/15175e0623e3ad66383841aff5c8e3c63fd9ab99) for converting the values into UTC but that doesn't help for future entries.

**Comment by blankse** [comment]
@hanneslauritz3n I created a PR: https://github.com/pimcore/pimcore/pull/16678

**Comment by hanneslauritz3n** [comment]
@blankse Thanks! Fixes the issue ✅

**Comment by blankse** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16678
