### ISSUE TITLE
[Bug]: DataObject Checkbox loses value on save when user cannot see checkbox

### ISSUE THREAD

**Issue by Johanna-Maria** [pimcore/pimcore#16674]
### Pimcore version

10.5.17

### Steps to reproduce

1. Create a Block with a checkbox (default value null) and some other data.
![image](https://github.com/pimcore/pimcore/assets/77202738/86d02b94-c867-457b-a409-cd978eedc6a6)
2. Create a Custom View for this structure that can see everything except the checkbox
![image](https://github.com/pimcore/pimcore/assets/77202738/0b1e7b61-0b4f-4bec-8bad-e8ff8c6af9e3)
3. Assign this custom view to a user/role
4. Go to the object as admin, add a bloxk, click on the checkbox so that the value is set to true and save. When the object reloads, the value of the checkbox is still true (as it should be)
![image](https://github.com/pimcore/pimcore/assets/77202738/e8abb671-0cfc-4bef-ba79-b6a972da1991)
5. log in as the user with the custom view and change something in the block (eg. add a new block entry), then save.
![image](https://github.com/pimcore/pimcore/assets/77202738/42b2e1d2-3811-4183-991a-0ef7e92f21c3)
6. The value of the checkbox will now be null
![image](https://github.com/pimcore/pimcore/assets/77202738/9fd470e2-908d-4b5c-8b17-ef38e733084d)

The checkbox is already null in the first line of save() in Concrete.php

### Actual Behavior

The checkbox (which cannot be seen by the user) changes its value to null when some other value in the block is edited.

### Expected Behavior

The checkbox (which cannot be seen/edited by the other user) should not change its value.

**Comment by kingjia90** [comment]
Thank you for reporting!
I've opened a PR https://github.com/pimcore/pimcore/pull/16727 that potentially fixes the issue, however the 
> ### Pimcore version
> 10.5.17
> 
is EOL, therefore you might need to manually apply this patch.

Let me know if you have a chance to try this out and if it solves the issue.
Thank you in advance

**Comment by Johanna-Maria** [comment]
Works fine, thanks!

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16727
