### ISSUE TITLE
[Improvement]: There is no way to filter objects in grid views based on whether they are of variant type or not

### ISSUE THREAD

**Issue by lucfumagalli** [pimcore/pimcore#16681]
### Pimcore version

11.1.4

### Steps to reproduce

Select a folder. Now in the grid view you can see objects and variants together. 

### Actual Behavior

I have this problem. 
In the grid views, all objects in a given folder are retrieved, including variants. 
Having removed in Pimcore 11 the ability to do a direct query, I am no longer able to get only the objects or only the variant objects. 
I wonder if there might be a solution. 
Thanks

### Expected Behavior

It would help me greatly to have a way to choose which objects to show in the grid view, based on whether they are normal objects, variants, or perhaps both.

**Comment by MarcoGuiducci** [comment]
I have the same issue.

I have many projects in which my customers need to have grids to export object data, edit massively on Excel, and then re-import data through data-importer.

In these processes is crucial to separate "object" data from "variant" data, to proceed with two different imports.

I agree with the fact that direct query must be disabled for security reasons (although it was very useful) as mentioned in #15634, but I think that we must be able to perform this kind of filtering.

**Comment by fzoccarato-sintra** [comment]
+1

**Comment by fzoccara** [comment]
+1

**Comment by laltie** [comment]
I had the same problem.

**Comment by g-acciai-sintraconsulting** [comment]
We also have this issue

**Comment by jacopoArtini** [comment]
I have the same issue.

**Comment by fashxp** [comment]
someone in for providing a PR instead of spamming there :-)
