### ISSUE TITLE
[Bug]: Split view for localized fields in object bricks not working properly (data loss)

### ISSUE THREAD

**Issue by isekep** [pimcore/pimcore#16697]
### Pimcore version

11.1.5

### Steps to reproduce

1. Configure Pimcore to use multiple languages (e.g. en, de, fr)
2. Update data model: class using object brick, object brick with localized fields providing split view, add data component (e.g. input) to these localized fields
3. Open data object with class described in step 2 (create one if necessary) and open editor
4. Add object brick to object
5. Enter some data in one language (e.g. en "Hello world")
6. Save & publish object (everything looks fine, new data is shown)
7. Click "Reload" button
8. Everything is okay ✅ 
9. Split languages (e.g. en left, de right, fr hidden)
10. Update input data from step 5 (e.g. en "Hello Pimcore world")
11. Save & publish object (everything looks fine, new data is shown)
12. Click "Reload" button
13. New value from step 10 disappeared, old value from step 5 is shown instead ⚠️ 

We already reproduced the issue in https://demo.pimcore.com/admin/ with these steps.

### Actual Behavior

In Split view changed values will not be stored properly, old values are shown after reload.
Without split view changed values will be stored properly and are shown after reload.

### Expected Behavior

In both, split view and without split view, changed values will be stored properly and are shown after reload.

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/451 (upcoming `v1.3.5`)

Thank you for reporting
