### ISSUE TITLE
[Bug]: Thumbnails generation with frame=true throw exception, if GD image adapter in use

### ISSUE THREAD

**Issue by sevarozh** [pimcore/pimcore#16693]
### Pimcore version

11.1.5

### Steps to reproduce

Thumbnails generation with frame=true throw exception, if GD image adapter in use

example URL:
admin/asset/get-image-thumbnail?id=247&width=88&height=88&frame=true

### Actual Behavior

TypeError: imagecopy(): Argument #4 ($dst_y) must be of type int, float given

### Expected Behavior

generated thumbnail in response

**Comment by blankse** [comment]
@sevarozh I created a PR: https://github.com/pimcore/pimcore/pull/16700

**Comment by martineiber** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16774
