### ISSUE TITLE
[Bug]: Localized calculated value has wrong index within field collection

### ISSUE THREAD

**Issue by studio1gmbh-pimcore** [pimcore/pimcore#16718]
### Pimcore version

11.1.5

### Steps to reproduce

1. Create a field collection including a localized calculated value
2. Create a simple calculator class, that returns the current index
```php
    // ...
    public function compute(Concrete $object, CalculatedValue $context): string
    {
        return 'I have index ' . $context->getIndex();
    }
    // ...
```
3. Set the calculator class in the calculated value
4. Create a class using the field collection
5. Create a new object and add field collection items

### Actual Behavior

Index is always 0

![image](https://github.com/pimcore/pimcore/assets/125017857/29d9e4b3-aee4-4ecf-96e6-98f76b082e86)

### Expected Behavior

Index should be same as the position within the field collection

![image](https://github.com/pimcore/pimcore/assets/125017857/79a06ab4-f8f7-49ee-9113-1e99fe6367b8)

This is probably related to https://github.com/pimcore/pimcore/pull/11816. 

Inside the loop, the index *must be updated every iteration*, not just the first time, when `$params['context']['containerKey']` is not set.

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16735
Thank you for suggesting the fix

**Comment by studio1gmbh-pimcore** [comment]
@kingjia90 thx for fast fix!
