### ISSUE TITLE
[Bug, EC]: Custom OptionsProvider value reset in Class definition edit mode of DataObject Select field

### ISSUE THREAD

**Issue by tomhatzer** [pimcore/pimcore#16739]
### Pimcore version

11.x

### Steps to reproduce

- Create a new `OptionsProvider` with some example values.
- Create a new DataObject class.
- Add a new default layout to the class definition.
- Add a `Select` field to the layout.
- Set `Options Source` to `Options Provider`.
- Set the `Options Provider Class or Service Name` for the select field to the previously created class name.
- Save the class definition.
- Reload the whole interface/browser tab (eg. F5).
- Reopen the class definition editor.
- Reopen the newly created class.
- Click on the `Select` field.
- The value of `Options Provider Class or Service Name` will be reset to `Pimcore\Bundle\CoreBundle\OptionsProvider\SelectOptionsOptionsProvider`.

### Actual Behavior

Value of `Options Provider Class or Service Name` field will be reset to `Pimcore\Bundle\CoreBundle\OptionsProvider\SelectOptionsOptionsProvider` upon clicking on the `Select` field definition.

### Expected Behavior

Value of `Options Provider Class or Service Name` field will have the same value as specified earlier when saving the Class definition.

**Comment by tomhatzer** [comment]
**Additional information:**
It looks like ExtJS is behaving differently and the issue is that, if the `optionsProviderData` value is an empty string inside the `definition_*.php` file, ExtJS will trigger a `change` event for the field and reset the value of the `Options Provider Class or Service Name` to the previously mentioned `SelectOptionsOptionsProvider` value.
![CleanShot 2024-03-05 at 16 42 31@2x](https://github.com/pimcore/pimcore/assets/3952168/28d76dd7-6c69-4fc2-b8e4-f3350c64b253)


If the value of `optionsProviderData` is `null` in the `definition_*.php` file instead, everything works as expected and the specified value stays in the UI like it exists in the definition file.
![CleanShot 2024-03-05 at 16 42 05@2x](https://github.com/pimcore/pimcore/assets/3952168/679045b8-2206-48f9-b8ac-347548593772)


Specific place in Admin UI ExtJS code: https://github.com/pimcore/admin-ui-classic-bundle/blob/cd5cb36beda37d87059d3eb7f88a8b393c98492a/public/js/pimcore/object/helpers/selectField.js#L48-L53

**Quick & dirty fix:**
If we update the `setOptionProviderData` method [here](https://github.com/pimcore/pimcore/blob/4da5b84117965399f87d6151b765f25cddb01a6c/models/DataObject/ClassDefinition/Data/OptionsProviderTrait.php#L55-L58) like this, everything works again:
```
    public function setOptionsProviderData(?string $optionsProviderData): void
    {
        $this->optionsProviderData = !empty($optionsProviderData) ? $optionsProviderData : null;
    }
```

**Comment by kingjia90** [comment]
Resolved by https://github.com/pimcore/admin-ui-classic-bundle/pull/485

Just picked this approach as i don't see ways in the front-end to manually turn the value to `null`, so must be some init thing falsely triggering as change

Let me know if it works

**Comment by Navino16** [comment]
@kingjia90 I have apply on my local instance the patch you provided. For me it's working
