### ISSUE TITLE
[Bug]: Custom LinkGenerator is not executed in Block field

### ISSUE THREAD

**Issue by 80Quattro** [pimcore/pimcore#16748]
### Pimcore version

10 & 11

### Steps to reproduce

1. To Product class add Custom Link Generator in `Link Provider Class or Service Name:` field
2. Create New Class with structure:
    - WYSIWYG [text1]
    - Block
        - WYSIWYG [text2]
3. Create new object of that type
4. Paste dummy text to [text1] & [text2]
5. Select a part of text in [text1] and drag & drop a product on it. Do the same in [text2]

![Screenshot 2024-03-07 at 10 57 37](https://github.com/pimcore/pimcore/assets/24212368/5a829043-7b77-4ef3-a248-98869619ec71)
![Screenshot 2024-03-07 at 10 56 36](https://github.com/pimcore/pimcore/assets/24212368/7431ffa2-1799-4461-a072-bee105670871)

### Actual Behavior

- Product Link in [text1] will be properly generated: `<a href="<host>/aricle/<slug>">text</a>`
- Product Link in [text2] won't be properly generated: `<a href="<host>/<direcotry in Pimcore BE>/<article title>">text</a>`

What I saw, in the first example, the custom Link Generator will be called, but in the second (with [text2]) not.

### Expected Behavior

- Custom Link Generator defined in `Link Provider Class or Service Name:` field is called also in WYSIWYG in Block Element
- Product Link is generated properly in both examples

**Comment by kingjia90** [comment]
Thank you for reporting and the patience

Could you please share the generator script? 
Codewise there are no difference in the source, it would in both case end up in here (could you please double-check with a breakpoint?) https://github.com/pimcore/pimcore/blob/bcd9003c875de53c54f4c1b8bbd3d649837570db/lib/Tool/Text.php#L91-L95, so suspecting it must be some condition in the link generator that may potentially exclude the block.

**Comment by kingjia90** [comment]
@80Quattro Any updates on this? Let me know if it's still occurring and if you could share some more code to reproduce it, just a friendly reminder before this issue would be  closed as stale soon. Thank you in advance
