### ISSUE TITLE
[Bug]: Question mark comes instead of asset thumbnail in Asset's left grid

### ISSUE THREAD

**Issue by rajeshkumarhm** [pimcore/pimcore#16759]
### Pimcore version

11

### Steps to reproduce

Go to the Assets section -> Upload an image with capital letter extension name, for ex: "rabbit.PNG" -> Question mark icon will be appeared in left tree instead of thumbnail

### Actual Behavior

Go to the Assets section -> Upload an image with capital letter extension name, for ex: "rabbit.PNG" -> Question mark icon will be appeared in left tree instead of thumbnail

### Expected Behavior

Go to the Assets section -> Upload an image with capital letter extension name, for ex: "rabbit.PNG" -> Thumbnail should be displayed instead of question mark icon.

**Comment by rajeshkumarhm** [comment]
![tmp_4438a8e3-f026-4a2f-bd5d-ea8e1179ae38](https://github.com/pimcore/pimcore/assets/108528191/9a567c64-6055-4af0-82be-5a943e1dac6e)

**Comment by kingjia90** [comment]
Thank you for reporting!

It's clearly because the file format is uppercase as `JPG`, which might not be best practice.
If renamed  to `.jpg` it should work fine

**Comment by kingjia90** [comment]
I've created a PR https://github.com/pimcore/pimcore/pull/16886 that should help and fix it, but in general (by looking at all overall usages) it seems that it would be not recommended to use it as upper cased
