### ISSUE TITLE
Passing through of E-Mail parameters

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#1676]
Currently, when emails are rendered with 
`$mail = new \Pimcore\Mail(['document' => $supplierEmail, 'params' => $params]);`
then the parameters have to be explicitly passed through to the view within the controller by adding
`$this->view->param1 = $request->get('param1');`

It would be better it that would happen automatically for emails.

**Comment by brusch** [comment]
I'm not sure if this is a good idea ... it opens doors for injections and other malicious things.
