### ISSUE TITLE
BC-Break: Default value on multiselect object type introduced by #15871

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#16777]
### Pimcore version

11.2

### Steps to reproduce

See https://github.com/pimcore/pimcore/pull/15871#issuecomment-1992050364

### Actual Behavior

https://github.com/pimcore/pimcore/pull/15871#issuecomment-1992050364

### Expected Behavior

https://github.com/pimcore/pimcore/pull/15871#issuecomment-1992050364

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16779
