### ISSUE TITLE
[Bug]: Panel labels are not translated on language change

### ISSUE THREAD

**Issue by varshaekrocx** [pimcore/pimcore#16781]
### Pimcore version

11

### Steps to reproduce

1. Create class with panel and contains some fields inside that.
2. Add Chinese  text inside Chinese language option inside admin translations for that panel name.
3. Create object and change the language from language option at top right.

### Actual Behavior

It not converting the panel label on language change
![image](https://github.com/pimcore/pimcore/assets/124252930/435f4dbf-4a99-44a2-a9b2-2bb21e9da9bd)

![image](https://github.com/pimcore/pimcore/assets/124252930/dbb2f6f2-36e4-4fc3-9925-767fa80640af)

### Expected Behavior

I want to get the label name in chinese if i switch the language inside object.

**Comment by GALPR** [comment]
I think this feature just switches the currently active language on localized fields. The translations for the admin interface in general are loaded depending on the language setting of the currently logged in user.

**Comment by varshaekrocx** [comment]
> I think this feature just switches the currently active language on localized fields. The translations for the admin interface in general are loaded depending on the language setting of the currently logged in user.

Thanks @GALPR.
