### ISSUE TITLE
[Bug, EC]:  If DataObjects are moved multiple times to a higher-level DataObject, the childCount is always 1

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#16795]
### Pimcore version

11

### Steps to reproduce

We have created a DataObject (data object - ID: 1), which initially has no further DataObjects subordinate to it.
We also have another five DataObjects with IDs 2,3,4,5,6.

The 5 objects are now all marked and moved under the parent object with ID 1. An "onPostUpdate" is implemented in the EventListener and this is also triggered cleanly. "onPostUpdate" is also called for each child element.

We now get the parent: $parent = $object->getParent();

Now we need all the child objects attached under this object.

### Actual Behavior

If we now call up the “children” by $children = $object->getParent()->getChildren();, we only get the 1st object (ID: 2) that was moved back, even though all children have been appended under the item. So the number of children remains at 1 even though we moved five objects,

### Expected Behavior

On the first call 1 child, on the second call 2 children, on the third call 3 children, but we only get 1 child on each call.
OR that we receive 5 Children directly, since we are in the PostUpdate.

**Comment by kingjia90** [comment]
Haven't reproduced it yet, but It seems due the fact that getChildren gets "cached" everytime it get a listing

https://github.com/pimcore/pimcore/blob/b9386e41457787db4c12741295c7aa1faf1e9f59/models/DataObject/AbstractObject.php#L341-L367

So by calling the setter `setChildren(null)` before getting the children, should work 
https://github.com/pimcore/pimcore/blob/b9386e41457787db4c12741295c7aa1faf1e9f59/models/DataObject/AbstractObject.php#L876-L878

**Comment by kingjia90** [comment]
Or maybe the $params array as `['force'=>true]` could be passed to this static method https://github.com/pimcore/pimcore/blob/7ef4ae5ff22bad445cacb7ec38241ca4cd5b1fdb/models/Element/AbstractElement.php#L225

**Comment by ghost** [comment]
Works for the customer with ['force'=>true].
