### ISSUE TITLE
[Bug]: Pimcore 11.2 needs a runtime without requiring one

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#16794]
### Pimcore version

11.2

### Steps to reproduce

Install Pimcore without a runtime, you will get an error on vendor/bin/pimcore-install that no runtime is installed and composer install should be called

### Expected Behavior

Pimcore should either require a runtime, or don't require one at all.

**Comment by blankse** [comment]
See also https://github.com/pimcore/pimcore/issues/16638#issuecomment-1998293078

**Comment by dpfaffenbauer** [comment]
ok, if there is already a ticket, I'll close this one.

But this has to be considered a BC break.

**Comment by fashxp** [comment]
please keep it open, the linked one is the original one ;-)

**Comment by blankse** [comment]
I only want to refer to my comment to extend the upgrade note. There is missing the change in public/index.php and bin/console

This should not be closed 😊

**Comment by dpfaffenbauer** [comment]
there is also issues with dotenv

**Comment by dpfaffenbauer** [comment]
ok, no, it comes down to being the runtime as well.

**Comment by brusch** [comment]
@dpfaffenbauer @blankse plz see #16638 - this should fix the issue (yes I know, it's not a candidate for the most beautiful piece of code awards 😅 )

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16833
