### ISSUE TITLE
[Bug]: get-current-user error after update to 11.1.6

### ISSUE THREAD

**Issue by paulhaem** [pimcore/pimcore#16826]
### Pimcore version

11.1.6

### Steps to reproduce

Using PHP 8.2.15.

After updating Pimcore from version 11.0.12 to 11.1.6 by following the [instructions](https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/Updating_Pimcore/#upgrading-within-version-11) I am not able to use the Admin UI due to an error when retriving the current user.

The update process went through without any noticeable problems. Symfony, Pimcore and Browser Cache were cleared.

### Actual Behavior

This error is returned from `/admin/user/get-current-user` after successful login:

```php
Uncaught Error: Pimcore\Model\User\Permission\Definition::setCategory(): Argument #1 ($category) must be of type string, null given, called in /projectFolder/vendor/pimcore/pimcore/lib/Model/AbstractModel.php on line 186
```

Additionally the admin UI is not rendered properly, but this might be just a reaction to the user not being loaded correctly:
![image](https://github.com/pimcore/pimcore/assets/6862218/1a1f0879-06eb-4e34-bce5-94584c6a3dfe)

### Expected Behavior

No error when retrieving the current user.

**Comment by kingjia90** [comment]
Thank you for reporting!

Weird, there are no migrations related to that and no recent changes that would suggest this error.
I'd double-check if the table `users_permission_definitions` is still is [not nullable and sets empty string as default](https://github.com/pimcore/pimcore/blob/0e11820647a4d4bb05713f758ab2c3e61b40a873/bundles/InstallBundle/dump/install.sql#L493), it seems coming from that.

**Comment by paulhaem** [comment]
Thanks for looking into it! You were right, inside the `users_permission_definitions` table there was a single entry `selectoptions` with `NULL` instead of `''` as the `category`. After updating the entry the admin UI worked again. Thanks a lot for the hint! ❤️ 

I then looked into the schema and saw that the `category` column allows `NULL` values and sets `NULL` as a default. Is it possible that this migration has been skipped somewhere in between?
