### ISSUE TITLE
[Pimcore4] Adding a objects with metadata field without Allowed class send JS error on object opening

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1682]
In the class object editor, adding a "objects with metadata" field without Allowed class send JS error on object opening.

To recreate on the demo:
- open class editor for "inquiry", and add a field "objects with metadata" named "test" for instance. Save the class
- open an inquiry object: it won't open because of a JS error.

Here is a screenshot:

![bug-js](https://user-images.githubusercontent.com/9025839/27842188-f122aa40-6107-11e7-9a29-2d5ff2d97d17.png)

I didn't try for other type (objects, href, multi href, multi href with metadatas...), maybe there is the same poblem.

Thanks.

**Comment by weisswurstkanone** [comment]
fixed in build 4089
