### ISSUE TITLE
[Bug]: Issue loading .env variables from 11.2.0

### ISSUE THREAD

**Issue by bitfactory-falko-neven** [pimcore/pimcore#16843]
### Pimcore version

11.2.1

### Steps to reproduce

When upgrading pimcore to 11.2.0 with composer and attempting to run `bin/console debug:dotenv`  the following error occurs:

![Screenshot 2024-03-25 at 14 13 28](https://github.com/pimcore/pimcore/assets/85358506/00e15092-65b2-44ae-811b-bef7d2b4d3b7)

This occurs because of the changes made in:
* https://github.com/pimcore/pimcore/commit/620bf66123e411dd190b516aa34ffb229afbc721
* https://github.com/pimcore/pimcore/commit/3a8393169f24a4c34f68d64e7ceb39a14346a19b

where the `prepareEnvVariables` function has been removed.

### Actual Behavior

The following error occurs:

![Screenshot 2024-03-25 at 14 13 28](https://github.com/pimcore/pimcore/assets/85358506/61dd65e4-cb74-45b3-83ff-11ea6519b2aa)

### Expected Behavior

The expected behaviour is that all  variablaes within the .env file are being loaded

**Comment by jdreesen** [comment]
See: #16794 (will be released with `11.2.2`)

Do you use [Symfony Runtime](https://symfony.com/doc/current/components/runtime.html) in your `index.php` (and `bin/console`)? 
I think you should. See: [pimcore/skeleton@11.x/public/index.php](https://github.com/pimcore/skeleton/blob/11.x/public/index.php?rgh-link-date=2024-03-14T18%3A23%3A18Z)

**Comment by bitfactory-falko-neven** [comment]
No, I was not using that. I've updated both `bin/console` to https://github.com/pimcore/skeleton/blob/11.x/bin/console and `index.php` to https://github.com/pimcore/skeleton/blob/11.x/public/index.php which seems to resolve the issue.

Bit more testing required on my part but that seems to be it. Thank you for responsing @jdreesen

**Comment by kingjia90** [comment]
Closing as `11.2.2` just got tagged. Feel free to re-open if it still occurs
