### ISSUE TITLE
[Bug]: CalculatedField Expression in Objects should support int as well

### ISSUE THREAD

**Issue by danielerne** [pimcore/pimcore#16847]
### Pimcore version

11.1.5

### Steps to reproduce

Create a calculated field and add an expression from a numeric field (likes) like object.getLikes()
And open the object.

### Actual Behavior

An error is shown:
<img width="989" alt="Bildschirmfoto 2024-03-25 um 17 42 51" src="https://github.com/pimcore/pimcore/assets/546931/776d905b-71d2-4c3a-986b-65469dbb21f9">

### Expected Behavior

int values should be supported as well. Like in Pimcore 10

**Comment by blankse** [comment]
@danielerne I created a PR: https://github.com/pimcore/pimcore/pull/16967
Can you test it?

**Comment by danielerne** [comment]
> @danielerne I created a PR: #16967 Can you test it?

Great Thanks!

**Comment by danielerne** [comment]
@blankse Great! Thanks!
