### ISSUE TITLE
[Bug]: Gotenberg problem documents version comparison

### ISSUE THREAD

**Issue by heigpa** [pimcore/pimcore#16858]
### Pimcore version

2024.1

### Steps to reproduce

Login as admin
Open a document
Create Versions of the document
Have a look at the version comparison of the document

### Actual Behavior

Paltform test system:
CSS Problems
<img width="499" alt="Screenshot 2024-03-27 092909" src="https://github.com/pimcore/pimcore/assets/129785940/8780386a-ca82-48f7-87c1-f94a18f11675">

### Expected Behavior

Comparison is shown correct

**Comment by martineiber** [comment]
Fixed by  https://github.com/pimcore/pimcore/pull/16859
