### ISSUE TITLE
[Bug]: Workflow notification send to inactive users

### ISSUE THREAD

**Issue by jensschaerer** [pimcore/pimcore#16867]
### Pimcore version

11.2.2

### Steps to reproduce

See `\Pimcore\Workflow\Notification\AbstractNotificationService::getNotificationUsersByName`

There is no check, if a user is active or inactive. Notifications are send to all users, regardless of status

### Actual Behavior

Notifications are send to all users, regardless of user status

### Expected Behavior

Notifications should only be send to active users

**Comment by markus-moser** [comment]
Fixed in #16904
