### ISSUE TITLE
[Improvement]: manyToOneObjectRelation similar to manyToManyObjectRelation

### ISSUE THREAD

**Issue by prunepal3339** [pimcore/pimcore#16868]
### Improvement description

Here are the ideas of introducing a PIMCore oneToManyObjectRelation similar to ManyToManyObjectRelation with improved object editor view as shown below:
![image](https://github.com/pimcore/pimcore/assets/29293380/47c216d0-dfca-4cd5-8864-186b441851d7)
The idea is to update the display mode store to support "single view" along with tag view in the class defintion editor so that object editor will be built as the above screenshot.

**NOTE**: The PathFormatter service to display multiple fields in a single input box with delimiter separation is cluttered and less informative from my perspective,  
Having two different fields as above (meta fields like description in above screenshot are noteditable input fields and for illustrations purpose only) is less cluttered and clean.

Any Views?

**Comment by fashxp** [comment]
Not sure I'm getting what you want to archive. 
Could you please elaborate a bit and also share actual use cases you would need that for. Thank you.

**Comment by prunepal3339** [comment]
The basic idea is to support ManyToOneRelation for Object types only.
The features it includes will be similar to the case of ManyToManyObjectRelation field.
One unique feature I want to introduce to this data type is to be able to display just one extra field as shown below:
![image](https://github.com/pimcore/pimcore/assets/29293380/6f41f712-59d3-46cc-bf0c-db4e9df00bd3)


In the above image, "Country" is the attribute of the relation field "Branch", ("Description" is the attribute of the relation field "Fragrance"), 
when we use relation field like this, we are able to display additional information that can be selected through class definition editor, which field to display along with the relation path.

**Comment by prunepal3339** [comment]
The most probable use case is to increase verbosity and add more description to the relation field in use, so the data makes more sense.
![image](https://github.com/pimcore/pimcore/assets/29293380/da2de788-9d98-4ad1-b7c2-b50b404cfb73)
![image](https://github.com/pimcore/pimcore/assets/29293380/f06ebbca-8c0d-4cd8-9638-dc82db06ecce)
If we look at the fields itself, it is partially descriptive.
Story:
As a user of PIMCore, I want to be able to add one more field for descriptive purpose to the respective many-to-one object relation fields.

**Comment by fashxp** [comment]
this could be archived already with the [path formatter](https://pimcore.com/docs/platform/Pimcore/Objects/Object_Classes/Class_Settings/Path_Formatter/)
