### ISSUE TITLE
[Bug]: Base Unit list is limited to 25 results in Quantity Value list

### ISSUE THREAD

**Issue by Maksonis** [pimcore/pimcore#16874]
### Pimcore version

11.1.6

### Steps to reproduce

- Add more than 25 units in Quantity values (Settings -> Data Objects -> Quantity Value)
- Open Base unit list
![image](https://github.com/pimcore/pimcore/assets/17277953/92e7a616-9ef0-4348-896e-a677225de143)

- 25 results are shown instead all units

### Actual Behavior

Only 25 units in list are shown, instead a whole list.

### Expected Behavior

Whole list should be shown.

**Comment by blankse** [comment]
There is a open PR for this: https://github.com/pimcore/admin-ui-classic-bundle/pull/415

**Comment by Maksonis** [comment]
Ah, I also created one. Thank you, didn't notice.

**Comment by robertSt7** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/415
