### ISSUE TITLE
Add a checking to see if file can be written when uploading an asset 

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1687]
When uploading an asset image in Pimcore using the backend GUI, we encounter a problem on Windows server because a too long file name is uploaded. It ends up with a fatal error because file cannot be written on the disk.

Please see the error message:

```
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'Unable to open file: \www/website/var/assets/test2/asset_105_7968bdf071a0fcf3e0efacca1be5798f__https-dartagnans-assets.s3-eu-central-1.amazonaws.com-assets-pictures-000-004-408-medium-vaux_le_vicomte_2_-_photo_lourmel_-ef-80-a2_chicurel.jpg-591b08631774a.jpg for asset 1174' in \www\pimcore\models\Asset.php:636
Stack trace:
#0 \www\pimcore\models\Asset\Image.php(59): Pimcore\Model\Asset-&gt;update()
#1 \www\pimcore\models\Asset.php(465): Pimcore\Model\Asset\Image-&gt;update()
#2 \www\pimcore\models\Asset.php(339): Pimcore\Model\Asset-&gt;save()
#3 \www\pimcore\modules\admin\controllers\AssetController.php(277): Pimcore\Model\Asset::create('1169', Array)
#4 \www\pimcore\modules\admin\controllers\AssetController.php(186):  in <b>\www\pimcore\models\Asset.php</b> on line <b>636</b><br />
```

I know Windows server is not supported, but maybe problem could arise on other operating system too.
Maybe the error could be catched or a check could be done before, so a clean message is sent to the user if he use the GUI or a clean exception is sent if using the API.

Thanks.

**Comment by brusch** [comment]
As far as i know this limitation is gone by Server 2016, so I don't think it's worth to make a platform specific check and error handling for this.
