### ISSUE TITLE
[Bug]: Two multifactor login code is not asking after logout.

### ISSUE THREAD

**Issue by gobind9** [pimcore/pimcore#16917]
### Pimcore version

6.9

### Steps to reproduce

Enable two multifactor login from my profile.

first time login with code from google authentication.
Next time logout and login again.
It is not asking for google authentication code directly it is being logged in

### Actual Behavior

If two multifactor login is enable. 

Code is not asking for next time login from doing logout.
Even you are able to login from other device without two factor login code.

### Expected Behavior

If two factor is enabled code should be ask every time or login from other device.

**Comment by kingjia90** [comment]
I can't reproduce it so far, it works as expected, the first time it shows the QR code, the second time it's not but asks for the code.

![image](https://github.com/pimcore/pimcore/assets/6014195/90a243b4-559c-47c1-8594-727adabb5046)

Any tips on how to reproduce it? Did you recently upgraded from  Pimcore 10?

**Comment by gobind9** [comment]
It’s my bad. This error in pimcore 6.9.

**Comment by kingjia90** [comment]
Ah ok, no problem.

Closing this issue as we don't actively work on 6.9 nor support it anymore
