### ISSUE TITLE
[Bug, EC]: Pimcore 11.x- AWS Blob Storage Breaking Change

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#16920]
### Pimcore version

11.x

### Description

- In 11.x, Pimcore added a function after every asset save to generate checksum of the asset content and save it along with the asset.
- When flysystem is used with AWS Blob storage, if the file size is larger than 32MB, the checksum doesn’t get generated.
- This is causing failure in assets upload for more than 32MB. This is a constant.
- When the file is more than 32 MB, azure code breaks it down to four blocks and uploads it without the checksum. [https://github.com/Azure/azure-storage-blob-php/blob/207c0c335bcc946bc6867752d366ad3dbfed8476/src/Blob/BlobRestProxy.php#L1843]
- I couldn’t find any document by Pimcore on this in upgrade to 11.x
- This is affecting existing assets more than 32MB and new assets cannot be uploaded for more than 32MB.
- Found the change from the merge logs:
[https://github.com/pimcore/pimcore/commit/41d8033ce5c87a214af76f41bfbaf6399f0ff576]

### Library used

- "league/flysystem-azure-blob-storage": "^3.0",
- "microsoft/azure-storage-blob": "^1.5",

### Actual Behavior

No checksum created for big files

### Expected Behavior

Checksum created for big files

**Comment by mattamon** [comment]
@wisconaut 

Tried to reproduce with the help of MinIO and AWS S3 Client  but was not able to reproduce the issue. I uploaded a zip files with 56MB and did not encounter any issue. I checked the file in pimcore backend and in the MinIO UI and could also download the file again without any problems from either interface. 

In the issue it is mentioned that "league/flysystem-azure-blob-storage" the azure blob storage is used and it seems that the problem needs to be fixed there. 

What we actually do in our code is actually calling the adapter function from the storage system adapter to get the checksum. This should work regardless of the adapter and not cause problems.

**Comment by ghost** [comment]
Closed as not reproduceable / possibly 3rd party issue

**Comment by alessandrofilira** [comment]
Hi @wisconaut, did you find any solution for this issue? I've same error you described.
Thanks in advance

**Comment by ghost** [comment]
@alessandrofilira Please see the [comment of our developer above](https://github.com/pimcore/pimcore/issues/16920#issuecomment-2049391153): As the problem seems to be in a 3rd party library, we unfortunately cannot provide further support on this topic.
I am sorry, but there currently is nothing else we can contribute here.

**Comment by cancan101** [comment]
Related convo: [#17472 ](https://github.com/pimcore/pimcore/issues/17438).
You can bump the limit to 256MB with something like:
```php
class BlobRestProxy extends \MicrosoftAzure\Storage\Blob\BlobRestProxy
{
    public static function createBlobService($connectionString, array $options = [])
    {
        $service = parent::createBlobService($connectionString, $options);
        $service->setSingleBlobUploadThresholdInBytes(Resources::MB_IN_BYTES_256);

        return $service;
    }
}
```
and then there is a new library that will handle chunking and md5 locally.
