### ISSUE TITLE
[Improvement]: Submit .gitignore template to gitignore.io

### ISSUE THREAD

**Issue by cancan101** [pimcore/pimcore#16957]
### Improvement description

I suggest submitting the recommended `.gitignore` template to [gitignore.io](https://www.toptal.com/developers/gitignore/) through: https://github.com/toptal/gitignore.

At present the [docs](https://pimcore.com/docs/platform/Pimcore/Deployment/Version_Control_Systems) suggest getting a template / sample from: https://github.com/pimcore/demo/blob/11.x/.gitignore. However, there is some value to submitting to the generator as it can be used to create a `.gitignore` file that can include multiple frameworks and / or IDEs and / or OS'.

**Comment by brusch** [comment]
Seems to be there already: 
https://www.toptal.com/developers/gitignore/api/pimcore5 😊 

But usually you start a Pimcore project anyway from our [skeleton package](https://github.com/pimcore/skeleton) that includes already the .gitignore. Don't think that it is very common that you have multiple products together with Pimcore on the project root level 🤔 

Thanks anyway for suggesting this.
