### ISSUE TITLE
[Pimcore5] move Pimcore static files into AdminBundle

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#1695]
Can you please move the Pimcore static files (js, css, fonts, ...) from web/pimcore into the AdminBundle/public? I don't see any reason why it should sit in the public directory.

I could create a PR for that, but some feedback on this would be nice.

PS: Already tried it, and works flawless.

**Comment by brusch** [comment]
Why?

**Comment by brusch** [comment]
Just to have again longer pathes, linking and copying stuff for now reason ...? (keep in mind that Windows has it's problems with long pathes). I don't think this is a good idea at all. And to be honest, I'm not a huge fan of idealism - let's keep it practical, simple and constructive :)

**Comment by dpfaffenbauer** [comment]
Because they belong there. Why scatter files around in different places? Symfony provides a nice and comfort way of linking bundle resources into the web folder, therefore Pimcore should take advantage of this feature. And file paths don't really get longer, they move from /pimcore to /bundles/pimcoreadmin which should be fine for windows as well. All though, I thought windows isn't officially supported anyway?

**Comment by Cruiser13** [comment]
Windows is not supported officially but Pimcore is still used often on Windows Systems if I look through the forums and the tickets here at github. Path length should not be an issue in Windows Server 2016+ and Windows 10+ though, so we could probably ignore that in the future: https://www.saotn.org/ntfs-long-paths-windows-server-2016-gpo/
