### ISSUE TITLE
[Bug]: Numeric Editable config option "decimalPrecision" does not work / is hard coded

### ISSUE THREAD

**Issue by marvin-bilharz** [pimcore/pimcore#16959]
### Pimcore version

11.2.2

### Steps to reproduce

- create a numeric editable inside a brick editable dialog
`[
                'type' => 'numeric',
                'label' => 'image_count',
                'name' => 'imageCount',
                'config' => [
                    'minValue' => 1,
                    'decimalPrecision' => 0
                ]
            ]`
- go to backend, add your brick, open editable dialog and write number e.g. "1.52" inside the numeric editable it and save/close the dialog
- reopen the dialog

### Actual Behavior

After saving and reopen the number is still "1.52".

This is because the decimalPrecision option is hardcoded in _vendor/pimcore/admin-ui-classic-bundle/public/js/pimcore/document/editables/numeric.js_

![image](https://github.com/pimcore/pimcore/assets/140318395/78ec2fd7-7e04-4b5a-ac87-516b7ef67e69)

### Expected Behavior

After input change the number should transform to "2".
Should be an option as stated in https://pimcore.com/docs/platform/Pimcore/Documents/Editables/Numeric/#advanced-usage

**Comment by blankse** [comment]
@marvin-bilharz I created a PR: https://github.com/pimcore/admin-ui-classic-bundle/pull/507
