### ISSUE TITLE
[Bug]: Video data type field getter throws exception on poster image within related videos when using blocks

### ISSUE THREAD

**Issue by jcalifice-basecom** [pimcore/pimcore#16963]
### Pimcore version

11.2.2

### Steps to reproduce

Class definition:

- Some Tab
-- Block 'videos'
--- Video field 'video'

Inside object editor:

- Adding block element
- Relatinge video
- Add image asset as poster image
- Save object
- Reload object

### Actual Behavior

'Message: Pimcore\Model\DataObject\Data\Video::getPoster(): Return value must be of type Pimcore\Model\Asset|string|int|null, Pimcore\Model\Element\ElementDescriptor returned'

### Expected Behavior

Return correct type without any exception

**Comment by blankse** [comment]
@jcalifice-basecom I created a PR: https://github.com/pimcore/pimcore/pull/16972

**Comment by blankse** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16972
