### ISSUE TITLE
[Docs] Possibility to show in documentation php and twig in different tabs

### ISSUE THREAD

**Issue by jorisros** [pimcore/pimcore#1699]
Is it possible to create a feature on the docs page where you are able to give example code in different tabs?  So we would be able to document for example the php and twig editables examples at the same time.
It would be great if we do this the same way as Symfony does this with their configuration files in different tabs.

Example:
![screen shot 2017-07-06 at 15 24 32](https://user-images.githubusercontent.com/752283/27913297-eef76810-625f-11e7-8fed-4d441855e04c.png)
![screen shot 2017-07-06 at 15 25 42](https://user-images.githubusercontent.com/752283/27913199-a4835a64-625f-11e7-8389-55a5c21694b1.png)

And this will be generated from the *.md file, example:
![screen shot 2017-07-06 at 15 40 12](https://user-images.githubusercontent.com/752283/27913896-d1f738e2-6261-11e7-8d88-6534c6bbf731.png)

**Comment by maff** [comment]
@jorisros Yes, we definitely want something like this and have such a feature on our roadmap, we're just not there yet.

**Comment by jorisros** [comment]
@maff Thats great! Do you already know how you going format the MD file? Because then i can already  start updating the documentation.

**Comment by brusch** [comment]
@jorisros not yet, but hopefully soon. We'll keep you updated.

**Comment by jorisros** [comment]
Great, thank you

**Comment by maff** [comment]
@jorisros We're currently updating our documentation build to support the following structure:

    <div class="code-section">
    
    ```php
    <section id="foo-bar">
        <?= $this->action("foo", "Bar", null, ["awesome" => "value"]) ?>
    </section>
    ```
    
    ```twig
    <section id="foo-bar">
        {{ pimcore_action('foo', 'Bar', ~, { awesome: 'value' }) }}
    </section>
    ```
    
    </div>

Wrapping multiple fenced code blocks inside a `.code-section` div will result in a tabbed code block:

![image](https://user-images.githubusercontent.com/27403/30215762-40b9773c-94b1-11e7-9f11-e813724fd418.png)

Please note that the extra lines after opening div/before closing div are important.

**Comment by dpfaffenbauer** [comment]
@maff you are using daux, right? could you open-source your change/adaption/plugin (whatever its called) then? CoreShops docs are using the same, would be nice for it as well.

**Comment by brusch** [comment]
@dpfaffenbauer yep, we're using daux.
We'll open source the entire code base anyway, since we plan to involve Travis CI into the build process.

**Comment by maff** [comment]
@dpfaffenbauer it's just a little jQuery magic looking for code blocks inside `.code-section` blocks. Until the docs build is available - these are the changes (you may need to activate `nav-tabs` bootstrap support in Daux' gulpfile depending on the version you're using): https://gist.github.com/maff/8c3f92bbb6a01ca0049c4a667dd636b9

**Comment by maff** [comment]
Et voilà: https://www.pimcore.org/docs/5.0.0/MVC/Template/Templating_Helpers/index.html
