### ISSUE TITLE
[Bug]: Empty glossary line crashes rendering

### ISSUE THREAD

**Issue by questionmark78** [pimcore/pimcore#17001]
### Pimcore version

11.2.3

### Steps to reproduce

Add a new line in the glossary, without any data in it

### Actual Behavior

An Exception is thrown:

An exception has been thrown during the rendering of a template ("htmlentities(): Argument #1 ($string) must be of type string, null given"). 
#0 /app/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#1 /app/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#2 /app/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
#3 /app/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render(Array)

### Expected Behavior

The glossary should just work, because the new line should be getting data in it, but perhaps in a later stage.

**Comment by kingjia90** [comment]
Thank you for reporting and the PR!

Fixed by https://github.com/pimcore/pimcore/pull/17002
