### ISSUE TITLE
[Improvement]: Insert right autoload path in Application Testing Documentation 

### ISSUE THREAD

**Issue by sl0wlydeadly** [pimcore/pimcore#17004]
### Description

In the Application Testing section of the Pimcore documentation there is a discrepancy between the _bootstrap.php and the functional.suite.yml code examples.
The autoloader for the first has the following path 
``` 
PIMCORE_PROJECT_ROOT . '/vendor/pimcore/pimcore/tests/Support'
``` 
mapped to:
``` 
'Pimcore\Tests'
``` 

But then in the functional.suite.yml example the Helper is called like this:
``` 
\Pimcore\Tests\Support\Helper\Pimcore:
``` 
Instead of this:
``` 
\Pimcore\Tests\Helper\Pimcore:
``` 

which is a small detail but can save a lot of time and research for copy pasters like myself.

Generally I would prefer to have 'Pimcore\Tests' mapped to PIMCORE_PROJECT_ROOT . '/vendor/pimcore/pimcore/tests instead of PIMCORE_PROJECT_ROOT . '/vendor/pimcore/pimcore/tests/Support'

### Suggestions

I would also like to suggest removing 
``` 
- \Tests\Support\Helper\Functional:
``` 
From the functional.suite.yml code example since it does not exist and is not being generated. 

And I think functional.suite.yml should be renamed to **Functional.suite.yml** as it being generated and mentioned in the Codeception documentation.

### Sources
- Pimcore Application Testing Documentation:
``` 
https://pimcore.com/docs/platform/Pimcore/Development_Tools_and_Details/Testing/Application_Testing
``` 
- Codeception Functional Suite Documentation:
``` 
https://codeception.com/docs/FunctionalTests
``` 

### Screenshots
![Bildschirmfoto 2024-04-30 um 11 52 19](https://github.com/pimcore/pimcore/assets/67418418/69943963-9251-45f5-99da-0404e52fbb4a)

![Bildschirmfoto 2024-04-30 um 11 51 21](https://github.com/pimcore/pimcore/assets/67418418/27efec66-9d98-4e4a-8587-cce9a71e515e)

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/17603
