### ISSUE TITLE
Document throws error - when hit "Save and close"

### ISSUE THREAD

**Issue by mk-conn** [pimcore/pimcore#1700]
# Bug Report

The following is reproducible on demo.pimcore.org/admin 
  
### Expected behavior 
Document will be saved and closed without error message  
### Actual behavior  
Document will be saved and closed but with error message saying "Document couldn't be saved"  
### Steps to reproduce  
Create new page, edit, hit "Save and close".

**Comment by brusch** [comment]
Document was saved, but generic error message was shown.
