### ISSUE TITLE
[Bug]: Option "Add print page" can't be disabled in context menu

### ISSUE THREAD

**Issue by MarkTro** [pimcore/pimcore#17017]
### Pimcore version

11.2.3

### Steps to reproduce

If you create a perspective view to disable the option "Add print page" in the document context menu it still remains, always. No matter what the settings are.

Create a perspective and disable "Add print page":
![perspective-config](https://github.com/pimcore/pimcore/assets/12793886/4c203d8c-ebfd-45b1-b198-150ab5b8afec)

Set the user and its roles to use this perspective, and open the backend with this user. The option is still available:
![context-menu](https://github.com/pimcore/pimcore/assets/12793886/5b33f0ee-e4db-4f1b-bb67-32d81c5cfb36)

I checked the network communication. In the page load the perspective config is also included. This config looks like it is configured in the backend before, but it has no effect. I tried the same with "add link" which work perfect.
![network](https://github.com/pimcore/pimcore/assets/12793886/39fdae30-8917-4c0a-accf-7fc45628c026)

### Actual Behavior

The option "Add print page" appear in the context menu always. 

### Expected Behavior

The option "Add print page" behaves like it's configured in the perspective config.

**Comment by kingjia90** [comment]
Resolved by https://github.com/pimcore/web-to-print-bundle/pull/77
It seems it got lost during the move to its own bundle
