### ISSUE TITLE
[Improvement]: pimcore:bundle:install should no-op if a bundle is already installed

### ISSUE THREAD

**Issue by evanjamesjackson** [pimcore/pimcore#17029]
### Improvement description

Currently, when running `bin/console pimcore:bundle:install` with a bundle that is already installed, an error is generated: `[ERROR] Bundle BundleName can not be installed.` This is a problem in Docker-based and continuous integration/deployment scenarios, as we regularly run (and re-run) such commands as part of the init operations of our applications. In order to workaround this issue, we have to use the `--fail-without-error` flag (which may ignore legitimate problems with the bundle installation), or choose to ignore errors altogether in the init script (e.g. by _not_ setting `set -e` in the entrypoint of a container, which is not ideal as this will cause the script to skip other legitimate errors)

In my view, trying to install a bundle that is already installed is not an error situation, and the default behaviour of this command should be to no-op and continue without error. **Alternatively**, if the behaviour of the current command is desirable, I suggest adding an optional flag to the command to ignore bundles that are already installed.

**Comment by jdreesen** [comment]
I can't comment in the PR anymore, but it is not assigned to any milestone.

**Comment by mattamon** [comment]
> I can't comment in the PR anymore, but it is not assigned to any milestone.

Thanks for the reminder, totally missed that :) Added now 11.3 since we did not release it yet.
