### ISSUE TITLE
communication failure| status 0

### ISSUE THREAD

**Issue by AbdulWajid04** [pimcore/pimcore#17037]
### Pimcore version

10.5

### Steps to reproduce

1. After successfully login
2. when click on any tree
3. when click on refresh on object editor 
4. quick search 

### Actual Behavior

It should work smoothly  and load the data in one go

### Expected Behavior

we should directly load the tree without any issue

**Comment by brusch** [comment]
This sounds like an issue with your webserver (Nginx, Apache) or your network infrastructure (WAF, ...) and not with Pimcore. 
Just to be sure, I've tried to reproduce this on our public demo ( https://demo.pimcore.fun/admin/ `admin/demo`), without luck 😉 

Closing this for now, if you can share a reproducible case on our demo instance, please reach out again. Thanks!
