### ISSUE TITLE
[Bug]: pimcore_relations does not accept more than one folder after reload in the back-end.

### ISSUE THREAD

**Issue by valik404** [pimcore/pimcore#17046]
### Pimcore version

11.1.3

### Steps to reproduce

Create a relation (doesn't matter if it's a editable dialog box or not). Drag in two folder's and save & publish. Now the relation will show objects of both folders. If you reload the page in the back-end, you will only see the last added folder in the relation. At this moment it will still show objects of both folders. Now if you save & publish again while there is only one folder in the relation, it will only display objects of the last added folder.

### Actual Behavior

pimcore_relation only accepts one folder with objects.

### Expected Behavior

Should accept more than one folder.

**Comment by kingjia90** [comment]
Can it be reproduced in the public demo? Any notable JS error in the Developer Tools' Console? 
So far i wasn't able to exactly reproduce it, but i am on `11.2` and it could be already fixed somewhere else 🤔

**Comment by valik404** [comment]
Hey, no there are no errors. I couldn't find any relations in the demo. Maybe it is already fixed with your version. I will check it. Thanks

**Comment by kingjia90** [comment]
Mhh, i think i have misread the first time, you are using [pimcore_relation](https://pimcore.com/docs/platform/Pimcore/Documents/Editables/Relation_Many-To-One/#general) which is many-to-one, therefore it HAS to be one, while you may want [pimcore_relations](https://pimcore.com/docs/platform/Pimcore/Documents/Editables/Relations_Many-To-Many) (NB: plural) if you want to link multiple elements or folders. 

So probably a visual/UI bug that somehow allows dropping more than one element on the many-to-one? I will double check that.

**Comment by valik404** [comment]
My fault, I meant pimcore_relations. So it should accept more than one folder right?

**Comment by kingjia90** [comment]
Ahh ok, all good. So far, it should be working as intended, I didn't find any problem in both editables types and there are no any recent changes from the JS side as well.

Maybe try to keep an eye on the `Versions` tab, to see if there's any change triggered by some custom implementation/third-party/autosave(?) to make sure whether it is losing data by not actually saving it or if it is "overwritten".

Looking forward to any further details and steps on how to reproduce it.

**Comment by valik404** [comment]
Here is what I tryed:

- Cloned the demo project of pimcore
- Created a new areabrick 
- Created a twig template with a pimcore_relations from the official pimcore documentation (https://pimcore.com/docs/pimcore/10.6/Development_Documentation/Documents/Editables/Relations_(Many-To-Many).html)
- Modified the default.html.twig to make it possible to use my areabrick (I added the name of my twig folder)
- A excerpt from the default.html.twig:

{{ pimcore_areablock('content', {
            'allowed': ['blockquote', 'embed', 'featurette', 'gallery-carousel', 'gallery-folder',
                'gallery-single-images', 'headlines', 'horizontal-line', 'icon-teaser-row', 'image',
                'image-hotspot-marker', 'image-metadata', 'pdf', 'product-grid', 'product-teaser', 'standard-teaser', 'text-accordion',
                'time-slider-featurette', 'validity', 'video', 'wysiwyg', 'wysiwyg-with-images', 'personalized-product-teaser', 'teaser-news']
        }) }}

- "teaser-news" is my areabrick
It's is still the same behavior. I got version 11.2.3 in this project now.

Before reload:
![grafik](https://github.com/pimcore/pimcore/assets/145031747/9b3d9a6a-f47e-426b-90a1-116e648fe16a)

After reload:
![grafik](https://github.com/pimcore/pimcore/assets/145031747/479be7b6-ad65-4df3-9a3b-0c2d09b7554d)

Hope this helps to reproduce it.

**Comment by kingjia90** [comment]
Ahh thank you for the detailed instruction, i am also confirming the issue as reproduce-able.
The fact that the subtype somehow becomes `variant` suggests that there might be a bug in there. 
I will let you know when i find the cause


Update: by changing this line (removing the variant constant), it would work
https://github.com/pimcore/pimcore/blob/4b28c29eab589cae051dc0c3b1ef6dc8b6bb7e89/models/Document/Editable/Relations.php#L89
Potential regression from https://github.com/pimcore/pimcore/pull/13233

**Comment by kingjia90** [comment]
PR https://github.com/pimcore/pimcore/pull/17054 is ready, feel free to review it and give it a try

Thank you again for reporting!

**Comment by valik404** [comment]
Yes, it actually works fine. Thank you very much for your fast help.
Have a good time.
