### ISSUE TITLE
[Bug]: Cannot set own TinyMCE config for translation

### ISSUE THREAD

**Issue by HemiCZ** [pimcore/pimcore#17041]
### Pimcore version

11.2.3

### Steps to reproduce

Cannot set own TinyMCE config for translation

### Actual Behavior

https://github.com/pimcore/pimcore/blob/230610923ee36ab370261fd13a84619be0162ad8/bundles/TinymceBundle/public/js/editor.js#L55

### Expected Behavior

I want to set own config.

**Comment by alexej-d** [comment]
The problem still persists. I would trigger an event before passing the final config to TinyMCE. Shall I create a PR?

**Comment by brusch** [comment]
@alexej-d that would be very nice, yes 👍😊 Thanks

**Comment by alexej-d** [comment]
@brusch [done](https://github.com/pimcore/pimcore/pull/17436) (you only need to trigger the workflow again, as I have signed the CLA too late)

**Comment by brusch** [comment]
@alexej-d thanks a lot, regarding CLA, you need to trigger it by commenting either `I have read the CLA Document and I hereby sign the CLA`´or  `recheck` (when done already), see also instructions here: 
https://github.com/pimcore/pimcore/pull/17436#issuecomment-2264868328 

Thanks!

**Comment by alexej-d** [comment]
@brusch thank you. The PR is ready

**Comment by brusch** [comment]
Nice, thanks a lot! 👍
