### ISSUE TITLE
[Bug]: CleanupBrickTask does not handle initial lower case letter in bricks and fieldcollections

### ISSUE THREAD

**Issue by morgannilsson** [pimcore/pimcore#17101]
### Pimcore version

2024.1

### Steps to reproduce

Create a brick with initial lower case letter, e.g: unitScannerPartner.
Create a field-collection with initial lower case letter, e.g: phone or email.

Run bin/console messenger:consume pimcore_maintenance

### Actual Behavior

No errors

### Expected Behavior

Errors:

11:02:57 ERROR     [app] Brick 'UnitScannerPartner' not found. Please check table object_brick_store_unitscannerpartner_organisationunit
11:02:57 ERROR     [app] Brick 'UnitScannerPartner' not found. Please check table object_brick_query_unitscannerpartner_organisationunit
11:02:57 ERROR     [app] Fieldcollection 'Email' not found. Please check table object_collection_email_organisation
11:02:57 ERROR     [app] Fieldcollection 'PersonalIdentifier' not found. Please check table object_collection_personalidentifier_person
11:02:57 ERROR     [app] Fieldcollection 'Phone' not found. Please check table object_collection_phone_organisation

**Comment by NiklasBr** [comment]
What's holding this one back @kingjia90?

**Comment by kingjia90** [comment]
@NiklasBr I just moved to next milestone, because it's likely on hold due to some still unresolved errors when applying the PR on https://github.com/pimcore/pimcore/pull/17342#issuecomment-2378540830
