### ISSUE TITLE
[Bug]: checkAllowedFormats throws an error when the format ORIGINAL is used

### ISSUE THREAD

**Issue by alexej-d** [pimcore/pimcore#17128]
### Pimcore version

11.2.3

### Steps to reproduce

Create an image thumbnail config with the format set to "ORIGINAL" – you may call it "meta_thumb_fb". Then generate the path of the newly created thumbnail like this `$asset->getThumbnail('meta_thumb_fb')->getPath(['deferredAllowed' => false]);`.

### Actual Behavior

ThumbnailFormatNotSupportedException is thrown. I believe [this line](https://github.com/pimcore/pimcore/blob/cc1a1fff78686423f616c7fe7c5d634a2ac71600/models/Asset/Thumbnail/ImageThumbnailTrait.php#L438) should be changed to allow 'original' in addition to 'source'.

### Expected Behavior

The path to the thumbnail should be returned without problems.

**Comment by brusch** [comment]
Seems to duplicate #17051 - thanks anyway 😊
