### ISSUE TITLE
[Improvement]: In the video lectures of Pimcore Academy, the audio is muted/missing for the last 40 seconds.  

### ISSUE THREAD

**Issue by vinishakankariya** [pimcore/pimcore#17149]
### Improvement description

 In the video lectures of Pimcore Academy ->Pimcore Developer Senior -> E-Commerce Framework -> Module Overview -> Index Service ->the audio is muted/missing for the last 40 seconds.  
Could you kindly reupload those videos.

**Comment by fashxp** [comment]
fixed, actually it was just muted video, no actual content was missing.

**Comment by vinishakankariya** [comment]
thanks for the clarification.
