### ISSUE TITLE
[Bug, EC]: Missing translations in workflows

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#17150]
### Pimcore version

11.x

### Steps to reproduce

Switch e.g. to German language and check workflow fields like "Workflow State". Also check potential error messages.

### Actual Behavior

Backend switched to German, but some messages and fields stay in English.

<img width="2060" alt="image001" src="https://github.com/pimcore/pimcore/assets/150000890/713af822-0f2a-4eb3-a472-2f197a2d5119">
<img width="1833" alt="image002" src="https://github.com/pimcore/pimcore/assets/150000890/7db75e37-158c-44ba-ad89-d4d314dcf7c0">

### Expected Behavior

All messages and fields are translated.

**Comment by kingjia90** [comment]
I wasn't able to find any occurrence of the first screenshot, is it something custom or third party?
I have tried to fix by https://github.com/pimcore/pimcore/pull/17252 but it's likely that we have to move the `Pimcore\Workflow\Place\StatusInfo` to `admin-ui-classic-bundle`, maybe in the next minor/major
