### ISSUE TITLE
[Web2Print] PDF response instead of the html response

### ISSUE THREAD

**Issue by ckogler-elements** [pimcore/pimcore#1718]
# Feature Request 
## Implement a method to easily display a PDF instead of the HTML.

- Use build in Web2Print functions
- Move tmp files out of public directory
- Add placeholder replacements...
- Generate the PDF directly from the html instead of URL calls/tmp HTML files
- integrate a sample

**Comment by ckogler-elements** [comment]
Sample integrated in /en/advanced-examples/blog-test?pdf=1

**Comment by fashxp** [comment]
should we add this somewhere into the docs too?

**Comment by maff** [comment]
We also should maintain demo changes in both Twig and PHP demo install profiles.
