### ISSUE TITLE
[Bug]: getLastLogin() must not be accessed before initialization on User model

### ISSUE THREAD

**Issue by martineiber** [pimcore/pimcore#17196]
### Pimcore version

11.2

### Steps to reproduce

Create a new user who has never logged in before.

Retrieve the user by their ID and attempt to get the last login time with:
`$user->getLastLogin();`

### Actual Behavior

However, this throws the following exception:
`Typed property Pimcore\Model\User::$lastLogin must not be accessed before initialization`

### Expected Behavior

It should return `0` or `null`

**Comment by blankse** [comment]
@martineiber I created a PR: https://github.com/pimcore/pimcore/pull/17197

**Comment by blankse** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/17197
