### ISSUE TITLE
user documentation for document areas

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#172]
add possibility to include user documentation directly to document areas. 
e.g. with optional help.php which is shown - if available - as popup behind a ? in edit mode of area

**Comment by jansarmir** [comment]
Will help.php support localization?
Areablock's name + description is no longer localized, why?

**Comment by brusch** [comment]
@jansarmir it's still possible to localize the name and the description using admin translations (just tested on demo.pimcore.org).

**Comment by jansarmir** [comment]
right, it is localized in admin translations
prior 4.x i had area's localization in plugin's text file (Plugin::getTranslationFile), now its localized in Areablock::setOptions, so that was problem

**Comment by florian25686** [comment]
@brusch This issue can be closed i guess
