### ISSUE TITLE
[Bug]: Undefined constant "GLOB_BRACE" on Alpine (musl)

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#17204]
### Pimcore version

11

### Issue

Try installing Pimcore on alpine Linux. Constant `\GLOB_BRACE` is not supported there and therefore does not exist. So the installer fails. Regression of https://github.com/pimcore/pimcore/pull/16798

**Comment by fashxp** [comment]
fixed via https://github.com/pimcore/pimcore/pull/17205
