### ISSUE TITLE
[Ecommerce][IndexService] multiple filterGroup for index field selection does not work

### ISSUE THREAD

**Issue by MHundeloh** [pimcore/pimcore#1720]
Hey,
when selecting multiple filter groups of an index filter selection field in a FilterType fieldcollection definition and adding this FilterType to a filterdefinition only those index columns from tenants column configuration are shown which have the last selected filterGroup. All the other filterGroups are ignored.

How to reproduce:
1. Define a columns configuration with 2 or more filtergroups for your productindex tenant
2. Select 2 filterGroups in fieldcollection definition of a FilterType with an index field selection field
3. Add that FilterType to a filterdefinition
4. Open the dropdown for available index fields
5. Only those index fields from columns configuration with the last selected filterGroup are shown.

It seems that the comma separated filterGroup list will not be send correctly by JsonStore proxy ajax call in static6\js\indexfieldselectionfield\tags\indexFieldSelection.js.
The called getFieldsAction() from EcommerceFrameworks IndexController does not get a comma separated list of filterGroups but only the name of the last select filterGroup.

As a workaround I quoted the comma separated list of this.fieldConfig.filterGroups in .js and unquoted it in the controller action before exploding it to a filtergroups array.

Best regards,
Matthias

**Comment by fashxp** [comment]
hi, could you provide a pullrequest with your solution?

**Comment by brusch** [comment]
@MHundeloh Any updates?

**Comment by MHundeloh** [comment]
I provided a pullrequest at pimcore-partner/ecommerce-framework:
Mhundeloh index field patch #149

**Comment by fashxp** [comment]
thank you very much. 
I solved it a bit differently now. Patched it in Pimcore5 and in Pimcore4 plugin.
