### ISSUE TITLE
[Bug]: Forgot Password Link are not working properly

### ISSUE THREAD

**Issue by sarweshsingh** [pimcore/pimcore#17219]
### Pimcore version

11.2.3

### Steps to reproduce

Step1-  Goto to left side setting menu 
Step2- Goto to system setting section inside website section 
Step3- Setting the main domain configuration eg - http://360.local
Step4- click on forgot password link
step 5- link are generated successfully and recieved the mail based on register user email.

![Screenshot from 2024-06-24 16-28-16](https://github.com/pimcore/pimcore/assets/134602692/a40b423f-a256-4806-b7b2-9c3c024a96c6)

### Actual Behavior

Link are not generated properly automatic remove the (:) from the url.
![Screenshot from 2024-06-24 16-28-16](https://github.com/pimcore/pimcore/assets/134602692/7ca3137e-26d2-4aef-8093-eccb24232af7)

### Expected Behavior

We want a forgot password link with remove the (:) from the http or https

**Comment by blankse** [comment]
@sarweshsingh The main domain configuration should be without protocol. In your case only 360.local

**Comment by sarweshsingh** [comment]
@blankse I have changed my domian **360.local** and I have also recieved the mail but when click on the link page redirected on the login page.
![image](https://github.com/pimcore/pimcore/assets/134602692/31198ef3-dd7f-4a90-a5b9-b32495cb16b9)
 
![image](https://github.com/pimcore/pimcore/assets/134602692/ce6d5089-67a7-4213-9f4c-3b07ffba50b2)

**Comment by blankse** [comment]
@sarweshsingh I think it doesn't work without https. Can you use https?

**Comment by kingjia90** [comment]
![image](https://github.com/user-attachments/assets/23a94fb0-8417-4638-97b7-e87406514a90)
I also see that Outlook's SafeLink mechanism is in place, i'd also recommend to avoid clicking the link but copy and paste the visibile url

Closing as stale, feel free to open a new issue if it still occurs
