### ISSUE TITLE
[Bug]: GCS: Asset Upload broken - stream is not a valid resource

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#17227]
### Pimcore version

11.2.6

### Steps to reproduce

Configure Google Cloud Storage and try to upload assets - it fails. Reason is that after using storage->write, the stream is closed and therefore not a valid resource anymore. 11.2.6 is the first release were this happens cause here https://github.com/pimcore/pimcore/blob/11.x/models/Asset.php#L737 it tries to get a local file to guess the mime-type. $src is not valid anymore here.

**Comment by albertmueller** [comment]
i can confirm this bug, i think it affects all cloud based systems where the fly system is configured (azure in our case). 
the bug was added from this pr: https://github.com/pimcore/pimcore/pull/17148/files
the title from this pr doesn't match to the code, im surprised that it was merged.

**Comment by brusch** [comment]
Very strange, I'm wondering why Flysystem closes the stream, can't find anything in the code of the GCS adapter 🤔 
And also in the local adapter, it doesn't close the stream.

**Comment by brusch** [comment]
Fixed by reverting #17005 
Created follow-up issue for fixing the original issue: #17257
