### ISSUE TITLE
AbstractObject::getList loads the list

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#1723]
Why needs AbstractObject::getList() the load() method call?

```php

$listClass = $className . '\\Listing';
$list = \Pimcore::getContainer()->get('pimcore.model.factory')->build($listClass);
$list->setValues($config);
$list->load(); //hm?
return $list;
```

I think this is a bug. It should just return the list instance. Otherwise it could happen that the list get's loaded without any conditions...

**Comment by dpfaffenbauer** [comment]
guess thats related to #1495
