### ISSUE TITLE
[Bug]: getClassificationStoreFieldName 

### ISSUE THREAD

**Issue by zekuraz** [pimcore/pimcore#17238]
### Pimcore version

11.2.6

### Steps to reproduce

Hey !

In this documentation https://pimcore.com/docs/platform/Pimcore/Objects/Object_Classes/Data_Types/Classification_Store/#using-classification-store-via-php-api , it's write

`
/** @var \Pimcore\Model\DataObject\Classificationstore $classificationStore */
$classificationStore = $dataObject->getClassificationStoreFieldName();

foreach ($classificationStore->getGroups() as $group) {
    var_dump($group->getConfiguration()->getName());

    foreach ($group->getKeys() as $key) 
    {
        $keyConfiguration = $key->getConfiguration();

        $value = $key->getValue();
        if ($value instanceof \Pimcore\Model\DataObject\Data\QuantityValue) {
            $value = (string)$value;
        }

        var_dump([
            $keyConfiguration->getId(),
            $keyConfiguration->getType(),
            $keyConfiguration->getName(),
            $keyConfiguration->getTitle(),
            $value,
            ($key->getFieldDefinition() instanceof QuantityValue),
        ]);
    }
}
`

So i try this 
`
$classificationStore = StoreConfig::getById(1);
$classificationStore = $dataObject->getClassificationStoreFieldName();
`

### Actual Behavior

I got error 

`06:16:07 ERROR     [pimcore] Class: Pimcore\Model\DataObject\Classificationstore\StoreConfig => call to undefined method getClassificationStoreFieldName`

### Expected Behavior

Should work so that we can then use The ClassificationStore::getGroups() method returns an array of Group objects. In turn, the Group::getKeys() method returns an array of Key objects for that group.

I may be using the function incorrectly. In this case I'd like to understand where the "$dataObject"' comes from.

Thanks in advance

**Comment by fashxp** [comment]
getClassificationStoreFieldName is a placeholder for your your classification store field name ... 

For example, if your classification store field in your data object class is called `attributes` it needs to be `getAttributes()`.

Tried to clarify docs a bit here https://github.com/pimcore/pimcore/pull/17678
