### ISSUE TITLE
[Elements] getById() and getByPath() shouldn't write to log when element not found

### ISSUE THREAD

**Issue by mk-conn** [pimcore/pimcore#1724]
Use case is the following: when importing objects, sometimes it will be checked if an object with a given path exists or will be treated as new. In case of many objects to be created, the log is filled with (in my opinion) useless entries. Is there a reason why it is implemented like that? 
  
### Expected behavior 
just `null` is returned  

### Actual behavior  
throws exception 'object does not exist' and creates log entry

**Comment by brusch** [comment]
Well, this depends heavily on the use case. 
If you're requesting an object in an action, you probably want to see an entry in your log file... 
So maybe we have to think about an additional flag, which controls the error handling. As of now it wasn't really a problem.

**Comment by mk-conn** [comment]
Yes, your right - its not really a problem per se, but consider some monitoring tool like Nagios thats going thrue logfiles and finds something like "prod.warning" (don't know the exact string thats written to output as I can't look into it right now), you will end up with a lot of false positives you have to click away...

**Comment by mk-conn** [comment]
I guess there was not really progress on this as nobody else thinks this could be a problem? ;)

Again, why this is a problem in my case: When I import lots of objects I check if it already exists or not (via *::getByPath() )  so I can decide if I have to create or just update - when there are lots of objects to import the logger will write unecessary lots of log entries with "object doesn't exists" lines which in the end could lead to a full hard disk... And for this use case a non existing object should not trigger a warning...

**Comment by dpfaffenbauer** [comment]
I agree with @mk-conn here, if you expect the object to exist, you should manually log it. a `getBy` function should return null when nothing found. That should be done for every model in Pimcore. Also for like `ClassDefinitions`. The behaviour with `getBy` functions is completely different with different models. Like a `Site` for example just throws an Exception when using `getByRootDocumentId` when in reality the developer only expects `null` to be given.

**Comment by dpfaffenbauer** [comment]
What about ClassDefinitions getByName? and Sites and so on? Should I create a separate ticket for those to have same API behaviour everywhere?

**Comment by brusch** [comment]
@dpfaffenbauer yes, please, as this ticket is about logging not about a consistent API behavior. Thanks!
