### ISSUE TITLE
[Bug]: GLOB_BRACE used in #16798 not available on specific platforms like Musl / Alpine

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#17265]
### Pimcore version

11.3.0

### Steps to reproduce

1. try to run the installer on Alpine
2. output:

```                                                                                                                        
 [ERROR] The following errors were encountered during installation                                                      
                                                                                                                        
 * Undefined constant "GLOB_BRACE"
```

Introduced in #16798 by @jdreesen. We can probably do two globs and merge them instead.

### Actual Behavior

Installer fails.

### Expected Behavior

Installer passes as it used to.

**Comment by blankse** [comment]
@dkarlovi A PR already exists: https://github.com/pimcore/pimcore/pull/17205

**Comment by dkarlovi** [comment]
Duplicate #17204
