### ISSUE TITLE
[Bug]: QuantityRangeValue validation failed on empty field

### ISSUE THREAD

**Issue by DGrosmayer** [pimcore/pimcore#17286]
### Pimcore version

2024.2

### Steps to reproduce

- Create a Product with a QuantityRangeValue 
- Add a valid range from min to max.  / Add any value to a QuantityRangeValue field
- Empty both fields and click on save

### Actual Behavior

Error pops up 
![image](https://github.com/pimcore/pimcore/assets/110802714/f7600978-c6f2-4c0a-a574-d7ed17f69e86)

### Expected Behavior

Save goes through

**Comment by kingjia90** [comment]
Thank you for reporting!
It will be fixed by  #17743
