### ISSUE TITLE
Exchange leafo/lessphp with oyejorge/less.php for better compatibility with twbs/bootstrap

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#173]
(https://www.pimcore.org/wiki/pages/viewpage.action?pageId=14551673)

It turns out the lessphp lib (http://leafo.net/lessphp v0.4.0) used in Pimcore is not fully compatible with Bootstraps less. But I found another one wich could be used as just an easy replacement: https://github.com/oyejorge/less.php
Just use composer to 'require' the library oyejorge/less.php and (hack) replace the file pimcore/lib/lessc.inc.php with the one from oyejorge. The autoloading mechanism from composer should take care of finding the correct classes in the vendor map, the classes used in the replacement of lessc.inc.php .

**Comment by ametad** [comment]
:+1: Nice to know this is on the task list!
