### ISSUE TITLE
[Pimcore4] calling Pimcore::collectGarbage when database transaction is in progress results in PDOException

### ISSUE THREAD

**Issue by questionmark78** [pimcore/pimcore#1730]
At some point we added a \Pimcore::collectGarbage() to increase performance. It turned out this call was also performed during a database transaction, which resulted in a PDOException: There is no active transaction.
The collectGarbage does a DB::close(), which presumably breaks the transaction?
Is it possible to have a check here if there is a transaction active?

**Comment by brusch** [comment]
I don't think we need a check here, since `Pimcore::collectGarbage()` shouldn't be called during an active database transaction. Usually the db connection is one of the most memory intensive component, so it makes no sense calling `Pimcore::collectGarbage()` without resetting the db connection.

**Comment by jstsch** [comment]
Hi! Perhaps we can throw an exception in collectGarbage() at the start of the function when in an active transaction? I can understand that perhaps in some contexts it's not wise to call collectGarbage, but the error that shows up is quite hard to debug (stack trace is no help) and also left the object database in an inconsistent state in our case (new unpublished versions of semi-saved objects were written). Typically you'd expect garbage collection to have no side-effects.

```php
if (DB::get()->inTransaction()) throw new \Exception('Pimcore::collectGarbage() should not be called whilst in a database transaction.');
```
