### ISSUE TITLE
[Bug]: DAO helper doesn't detect localized indices exists properly

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#17318]
### Pimcore version

11.3.0

### Steps to reproduce

1. add a localized field `Name`, make it unique
2. run `bin/console pimcore:deploy:class -f`

It will try to re-add the index even though it already exists. This is due to this line checking for exactly one

https://github.com/pimcore/pimcore/blob/a96a60244d7d9bb26a0d69500a7075efc6fac686/models/DataObject/ClassDefinition/Helper/Dao.php#L197

but it should be checking for 1 or more, in this case the lines will be

```
Name
Language
```

and it will be 2, not 1.

### Actual Behavior

Localized indices failed to get detected correctly.

### Expected Behavior

Localized indices detected correctly.

**Comment by kingjia90** [comment]
Closing as it was fixed by https://github.com/pimcore/pimcore/pull/17374 in `11.3.2`

Thank you again for reporting
