### ISSUE TITLE
How to update ckeditor from 4.22.1 version to 4.24.0-lts in pimcore 10.6 version

### ISSUE THREAD

**Issue by Thejaswini-Rao-U** [pimcore/pimcore#17317]
### Pimcore version

10.6.9

### Steps to reproduce

Hi
In my project, sometimes in the object i see below message appearing 

" **This CKEditor 4.22.1 version is not secure. Consider "https://ckeditor.com/ckeditor-4-support/" 4.24.0-lts.**"

how to update ckeditor version from 4.22.1 to 4.24.0 ? i tried to find out in pimcore document or anywhere i did not find updating command or procedure for this?

please let me know how to solve this?

Thanks in advance
Thejaswini

### Actual Behavior

gives warning or error in admin interface object

### Expected Behavior

how to update

**Comment by blankse** [comment]
@Thejaswini-Rao-U You can deactivate the version check. See https://github.com/pimcore/pimcore/issues/16574
