### ISSUE TITLE
[Improvement]: Execution modes for `Generic Execution Engine`

### ISSUE THREAD

**Issue by mcop1** [pimcore/pimcore#17312]
### Improvement description

Currently, each selected element inside a JobStep triggers the execution of the action separately. For example, selecting 5 elements results in the action being executed 5 times.

However, we need a feature that allows all selected elements to be passed at once to the action, meaning 5 selected elements would result in the action being executed just once.

### Mode 1: All At Once

Advantages:

- Facilitates easier migration from the old Job Execution Engine to the new Generic Execution Engine.
- FilterActions, such as the PQL action, will only be called once, avoiding redundant operations.
- Could simplify implementation for actions like generating CSV files, ZIP archives, uploading data, etc., which are currently possible but require extensive use of JobRunContext or spawning sub-jobs.

Disadvantages:

- Simplified error handling, limited to "job completed successfully" or "job failed".
- Limits parallel execution to a single worker since only one message is generated.

### Mode 2: For Each

Advantages:

- Potentially faster processing as each element generates a message that can be processed in parallel.
- Improved error handling, with each element able to independently result in success or failure.

Disadvantages:

- May result in unnecessary executions for FilterActions like the PQL action.

**Comment by fashxp** [comment]
This even could be considered as a bug - at least in combination with copilot. 

![image](https://github.com/pimcore/pimcore/assets/8792145/2cb24ab0-5bc2-48f5-8285-895e47aeb6ed)

When I start an action with that configuration with four assets, the configured action will be sent 4 times... 
![image](https://github.com/pimcore/pimcore/assets/8792145/0681da50-976d-4ca4-8cb5-bebff8808729)
