### ISSUE TITLE
[Bug]: Character Count Not Showing for WYSIWYG Control on v11

### ISSUE THREAD

**Issue by cancan101** [pimcore/pimcore#17324]
### Pimcore version

v11.2.2

### Steps to reproduce

Create a WYSIWYG control with a maximum characters

### Actual Behavior

No count shown. This did work on prior rich editor: https://github.com/pimcore/pimcore/pull/9554

### Expected Behavior

Count to show like here: https://github.com/pimcore/pimcore/pull/9554

I posted this here: https://github.com/pimcore/tinymce-bundle/issues/12 as well

**Comment by fashxp** [comment]
duplicate of https://github.com/pimcore/tinymce-bundle/issues/12
