### ISSUE TITLE
[Bug]: changing many-to-many into many-to-one relations loses data

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#17320]
### Pimcore version

11.3.0

### Steps to reproduce

1. create a many-to-many relation linking to the class `Class1`
2. create a new object ID=1 of that class, fill it in, add 2 objects, `Rel1`, `Rel2`
3. change the relation to many-to-one, still linking to the same class
4. check object ID=1, relation is now empty

Assuming the relation is getting cleared to ensure consistent behaviour, it could clear it where `index > 0` instead of clearing everything. Doing it in reverse works as expected, no data is lost.

### Actual Behavior

Complete data loss, object ID=1 is cleared of both related objects.

### Expected Behavior

Object ID=1 links to `Rel1`.

**Comment by brusch** [comment]
@dkarlovi please be aware that renaming and changing the type of a field can lead to data loss. 
This is also mentioned in the docs, e.g. here: https://pimcore.com/docs/platform/Pimcore/Objects/Object_Classes/Data_Types/#general-aspects 

We are aware that this works in some cases, but you cannot assume that it works in all cases. Displaying a warning in the UI is pretty tricky, so we decided to leave it with a warning in the docs. 

Thanks anyway for reporting 👍😊

**Comment by dkarlovi** [comment]
@brusch I'll be honest: it's weird **Pimcore** (as a tool aiming to be your MDM) **is so comfortable with losing data**.

I know about the docs, my issue here was attempting to signal Pimcore should work harder to NOT lose data, that seems like it would be a top design priority for a PIM system.

For example, Pimcore could have "safe conversions" where it doesn't clear your dataset when going from type A to type B and vice versa. Going from many-to-many to many-to-one and back seems like it could be one of those. This would allow model designers flexibility within specific constraints.

> renaming a field can lead to data loss

This is another example where Pimcore is losing valuable knowledge by not persisting the **intent** the model designer had at the time of the change being made and trying to reconstruct it at runtime from current class definition data (when it's way too late), see #12065 and a lost opportunity to use [a fully supported MySQL feature](https://dev.mysql.com/doc/refman/8.0/en/alter-table.html#alter-table-redefine-column) to streamline the experience.

**Comment by brusch** [comment]
Thanks for sharing your thoughts and your opinion. We highly appreciate any kind of feedback and be sure we take it serious - it's the key factor for us to make the product better together 😊 
In the end it's a matter of priorities and as always we have to accept some trade-offs, as it's simply impossible to make every single target group happy.  

I just want wo clarify again, that changing the type of a field is not data loss, it can be also seen as deleting the field and creating a new field with the same name. It's also important to know that, most of the field types are simply not compatible in any way (except some simple scalar types). 
Take your example, what is the expectation when changing from many-to-many relations to many-to-one relation when having multiple relations on the field in an object? Keep the first relation, or the last one, or just a random one? You probably get the point 😉
