### ISSUE TITLE
staticroutes in hardlinks context and direct calls of hardlinks are in wrong context  

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#1733]
## direct call of a hardlink document
1. create a document (`/de`) set language to `de`
2. create a hardlink (`/de-at`), link it to the document, enable both checkboxes and set language to `de_AT`
3. open hardlink in frontend `/de-at`: the request locale is still `de` but it should be `de_AT` (i think all the overwritten properties should be available).
4. if you create a subpage in the hardlink context, everything works as expected.
 
## call a staticroute in hardlink context
1. create a document (`/de`) set language to `de`
2. create a hardlink (`/de-at`), link it to the document, enable both checkboxes and set language to `de_AT`
3.  create a staticroute: 
3.1 `pattern: /([a-z-]+)\\/your-slug\\/([A-Za-z0-9._-]+)\\-([0-9]+)/`  
3.2 `reverse: /%_locale/your-slug/%entryName-%entryId`
3.3`variables: _locale,entryName,entryId`
4. call staticroute: `/de-at/your-slug/my-entry-1`
5. since pimcore is calling the `getNearestDocumentByPath()` method, pimcore should get all the properties from the `de-at`hardlink document, instead the root document `1` gets loaded.

**Comment by solverat** [comment]
fixed in 87c44978ac91fd46fb355bff41388eb75a1a4d07. successfully tested with build 82.

**Comment by maff** [comment]
@solverat thanks for testing! The change also fixed a third issue but I didn't find the time to test if it addresses this issue as well.

**Comment by solverat** [comment]
@maff i'm just working on a special customer case and i'm wondering if we could have short discussion about the `getNearestDocumentByPath()` method. Please check this line:

https://github.com/pimcore/pimcore/blob/5483c6f0fa00cfb4026b15ef5ffbfaf9dcee66ca/pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/DocumentFallbackListener.php#L136

In my case we have site structure like:

```yml
- site1 #pimcore site
     - de # a link (!) to a subpage, but with the property "language" for german
     - en # default start page with property "language" for english
- site2 #second pimcore site
     - de
     - en
```
As you can see `site1/de` is a link which does not fit into the `getNearestDocumentByPath` standard. Now i had to implement a specific static route like `site1/de/my-static-route`. The `getNearestDocumentByPath`will return `site1` instead of `site1/de/` which would be the real start of the page where we define the language and so on.

So, what do you think? I can't see any disadvantages if we would add `link` to the allowed fallback document types but maybe i don't see the big picture.

**Comment by maff** [comment]
@solverat I'd prefer to not change this behaviour by default as it was already handled like this in Pimcore 4 and could lead to unexpected side effects in projects relying on this behaviour if we now change this, even if it would be more "correct" to include links.

We could however make that hardcoded array configurable, so you could reconfigure it in your project where you know about the change. If it's feasible to change this on the long term we could plan to change and document the default value to include links for Pimcore 6. What do you think?

**Comment by solverat** [comment]
Ok sounds good to me. Let's do this configuration madness. :D

**Comment by maff** [comment]
@solverat added a configuration possibility in 5417c21f8fa642dff2dca4deebc1befb49336c92. There is no configuration option on the config files, you need to change the service definition instead. The easy way would be to just overwrite the service definition:

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Bundle\CoreBundle\EventListener\Frontend\DocumentFallbackListener:
        arguments:
            $options:
                nearestDocumentTypes: ['page', 'snippet', 'hardlink', 'link']
```

The more compatible way however is to change the service definition in a compiler pass and just change the options argument instead of overwriting the definition. This prevents issues in case the core adds things (e.g. a call) to the service definition. Something like this should work:

```php
<?php

namespace AppBundle\DependencyInjection\Compiler;

use Pimcore\Bundle\CoreBundle\EventListener\Frontend\DocumentFallbackListener;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class DocumentFallbackListenerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $fallbackListener = $container->findDefinition(DocumentFallbackListener::class);
        $arguments        = $fallbackListener->getArguments();

        $options = array_merge($arguments['$options'] ?? [], [
            'nearestDocumentTypes' => ['page', 'snippet', 'hardlink', 'link']
        ]);

        $fallbackListener->setArgument('$options', $options);
    }
}
```
