### ISSUE TITLE
[Bug]: Error check version when delete video

### ISSUE THREAD

**Issue by tintin-q** [pimcore/pimcore#17336]
### Pimcore version

11.1.0

### Steps to reproduce

1)Upload video for object
2)Save object
3)Remove video from object
4)Remove video in assets tree
5)Open versions
6)Open the version in which the video was uploaded
![2024-07-12_14-13](https://github.com/user-attachments/assets/42f40930-551c-42be-a4ac-563986bddd98)

### Actual Behavior

The selected version opens

### Expected Behavior

A version error is displayed
`Cannot assign null to property Pimcore\Model\DataObject\Data\Video::$data of type Pimcore\Model\Element\ElementInterface|Pimcore\Model\Asset|Pimcore\Model\Element\ElementDescriptor|string|int`

**Comment by tintin-q** [comment]
I tried correcting the code in  Pimcore\Model\DataObject\Data\Video (add null type for $data and in set and get data)

Set
`protected string|int|ElementInterface|Asset|\Pimcore\Model\Element\ElementDescriptor|null $data;`
And
```
public function setData(Asset|int|string|null $data): void
    {
        $this->data = $data;
        $this->markMeDirty();
    }
```

```
    public function getData(): Asset|int|string|null
    {
        return $this->data;
    }
```
    
It works, but I'm afraid it might affect other code.

**Comment by blankse** [comment]
@tintin-q Should be already fixed by https://github.com/pimcore/pimcore/pull/16972
