### ISSUE TITLE
[Bug]: Adding a link in a Localized-Field breaks Object

### ISSUE THREAD

**Issue by MosiiAUT** [pimcore/pimcore#17346]
### Pimcore version

v11.1.4 + v2024.2

### Steps to reproduce

Can be reproduced in Demo:
- add a link in a localized field in your object-class (e.g. News)
- create a new object and fill the link with a pimcore-document -> save
- delete the data of the link but don't use the "empty" button -> save
- object can not be saved

### Actual Behavior

if the empty button isn't used, the object will cannot be saved anymore
Message: Pimcore\Model\Document::getById(): Argument #1 ($id) must be of type string|int, null given, called in /var/www/html/vendor/pimcore/pimcore/models/DataObject/Data/Link.php on line 377

### Expected Behavior

Object should be saveable, even if the empty-button isn't used

**Comment by blankse** [comment]
@MosiiAUT I created a PR: https://github.com/pimcore/pimcore/pull/17348

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/17348

Thank you both for reporting and for the PR
