### ISSUE TITLE
Get options for nested (block, LF, FC, Bricks) select/multiselect

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1736]
For `Block` data type, getOptionsForSelectField and getOptionsForMultiSelectField don't works for children data type.

Here:
https://github.com/pimcore/pimcore/blob/2bb14ffbd193b1137304e09eac4243576dd2c5ab/pimcore/models/Object/Service.php#L810
Return is empty.

I managed to get the child field with custom code, but second problem: it seems it need fully qualified name of instanceOf, see https://github.com/pimcore/pimcore/blob/2bb14ffbd193b1137304e09eac4243576dd2c5ab/pimcore/models/Object/Service.php#L810, where it worked with Pimcore\Model\Object\ClassDefinition\Data\Select.

Here is for now the work around i made with a custom function:

```
    public static function getBlockOptionsForSelectField($object, $fieldname, $childFieldname) {
        // return the value for the given key (for blocks fieldname are childs of the block fieldname, and getOptionsForSelectField don't work)
        $class = null;
        $options = [];

        if (is_object($object) && method_exists($object, "getClass")) {
            $class = $object->getClass();
        } elseif (is_string($object)) {
            $object = "\\" . ltrim($object, "\\");
            $object = new $object();
            $class = $object->getClass();
        }

        if ($class) {
            $definition = null;
            $childDefinitions = $class->getFielddefinition($fieldname)->getChilds();
            foreach ($childDefinitions as $childDefinition) {
                if ($childDefinition->getName() == $childFieldname) $definition = $childDefinition;
            }

            if ($definition instanceof Pimcore\Model\Object\ClassDefinition\Data\Select || $definition instanceof Pimcore\Model\Object\ClassDefinition\Data\Multiselect) {
                $_options = $definition->getOptions();

                foreach ($_options as $option) {
                    $options[$option["value"]] = $option["key"];
                }
            }
        }

        return $options;
    }
```

It would be great if we could get options for childs of block data type using directly getOptionsForSelectField and getOptionsForMultiSelectField.

---

By the way, i know it is not the purpose of this issue, but it would be very nice for developpers to have directly a method less verbose to get the display value. Actually, we need to do:

`$myObject->getMyField() ? Object\Service::getOptionsForSelectField($myObject, "myField")[$myObject->getMyField()] : ""`

(the `if` is needed to not having notice error on non required field)

Something like $myObject->getDisplayValue("myField"), will work for select/multiselect like usualy but instead send the display values (string or array if multiselect).
This is just an idea which can be surely better implemented ; )

**Comment by brusch** [comment]
Imho the following approach is more generic and solved also the issue with all other field containers like: localized fields, object bricks, field collections, ...

```php
$selectField = $class->getFieldDefinition('myBlock')->getFieldDefinition('mySelect'); 
$options = Object\Service::getOptionsForSelectField($selectField); 
```

**Comment by Yivan** [comment]
Thanks @brusch 
Maybe it could be documented in pimcore 4 and 5 docs so people are aware of this ?
