### ISSUE TITLE
[Bug]: localized multiselect field does not provide an option to add select options in different language

### ISSUE THREAD

**Issue by varshaekrocx** [pimcore/pimcore#17375]
### Pimcore version

11

### Steps to reproduce

1. Add a new class 
2. Add localized field
3. Add multiselect field
4. save class and create an object
5. Now we can see the multiselect options in English (default selected) in English language  as well as other language.

### Actual Behavior

Multiselect field provides option in english  while checking in English language as well as other language
For English language
![image](https://github.com/user-attachments/assets/e646a66a-72f6-42df-be64-9d2131603409)
For Chinese Language
![image](https://github.com/user-attachments/assets/488d6766-c061-44f1-bf25-d1ec4d2152f6)

### Expected Behavior

I want a multiselect localized field where i can add both option for english and for chinese language as well.

I want like this but for a same Multiselect field
for English language
![image](https://github.com/user-attachments/assets/6e2a0a17-7d50-4dc5-8f72-1522d46cd51e)
For chinese language
![image](https://github.com/user-attachments/assets/23a94300-e9c0-4465-be14-95ab9cf52ff7)

There is one option if i add the admin translation but how can i then provide that translated value through custom rest api. and if i want to add new option in Chinese language separately then how that can be done.

**Comment by fashxp** [comment]
We don't see that as a bug. 
Pimcore differentiates between value and label. The value is not translated. If you need the Chinese values as well, you would need to add them to the value list. 

Labels can be translated, e.g. in the admin UI via the admin translations. 
For providing translated labels via custom APIs, you need to solve that in a custom way - e.g. providing an additional endpoint for providing the admin translations, or already including the translated labels in your custom response.
