### ISSUE TITLE
[Bug] Documentation error: Hard coded Content-Type in example MyAssetController class for asset protection

### ISSUE THREAD

**Issue by elbkapitaenehh** [pimcore/pimcore#17379]
### Pimcore version

2024.2

### Steps to reproduce

1. Implement the solution documented in https://pimcore.com/docs/platform/Pimcore/Assets/Restricting_Public_Asset_Access/#option-2---checking-permissions-before-delivery
2. Upload any non-pdf asset in the protected folder
3. Authenticate and open the public link
4. The Content-Type says 'application/pdf'

### Actual Behavior

The Content-Type header is hard coded as application/pdf. It should be $asset->getMimeType() in order to match the delivered asset MimeType

### Expected Behavior

A protected asset should be delivered with the correct Content-Type header after one included the example code for the MyAssetController class from https://pimcore.com/docs/platform/Pimcore/Assets/Restricting_Public_Asset_Access/#option-2---checking-permissions-before-delivery

**Comment by blankse** [comment]
@elbkapitaenehh I created a PR: https://github.com/pimcore/pimcore/pull/17380
