### ISSUE TITLE
[Bug]: Reorder of localized fields in class definition doesn't work

### ISSUE THREAD

**Issue by akno77** [pimcore/pimcore#17387]
### Pimcore version

11.3.1

### Steps to reproduce

1. Create localized fields in the class definition
2. Try to reorder the fields via drag & drop
3. Try to drag & drop a non localized field into the localized fields

### Actual Behavior

It is not possible to move the localized fields to another position and it is not possible to drag & drop existing non localized fields into the localized fields.

### Expected Behavior

It is possible to reorder localized fields via drag & drop and also move non localized fields into localized fields

**Comment by akno77** [comment]
I recognized that its also not possible to move existing non localized fields into the localized fields. I updated the issue.

**Comment by markus-moser** [comment]
Fixed in https://github.com/pimcore/admin-ui-classic-bundle/pull/635
