### ISSUE TITLE
[Pimcore4] Dropping elements into hrefs should produce same result as obtained by selecting them

### ISSUE THREAD

**Issue by AlternateIf** [pimcore/pimcore#1743]
## Prerequisite

1. A type-specified href in your view (type = 'document')
`<?= $this->href('test', ['types' => ['document'] ]); ?>`

## Description

Dropping Snippets into the Href is not possible. By 'Right-Clicking' said snippets can be added though.

## Problem
Inconsistent behaviour. Dropping should be possible since Snippets are Documents

**Comment by weisswurstkanone** [comment]
build 4095
