### ISSUE TITLE
[Bug]: Maintenance of translations partially not possible

### ISSUE THREAD

**Issue by SeatbeltElstner** [pimcore/pimcore#17430]
### Pimcore version

10.6.9

### Steps to reproduce

In our Pimcore 10.6.9 System used as CMS we faced the following issue:

We had two languages active in the System: de and en

We had an admin user and some editor users which where configured to maintain the shared and admin translations.

We added a new language (en_US) to the system and configured the editor users to be able to maintain them.

The admin user before was an editor user which were allowed to maintain languages de and en in shared and admin translations an after a while we configured him as admin user by just setting the checkbox in the user settings.

### Actual Behavior

After adding the new language en_US to the system, the editor users were after configuration able to maintain the translations (shared and admin).

The admin user was not able to maintain the translations (shared and admin) only for the new language which was added to the system.

Input fields for the new language are disabled for the admin user.

### Expected Behavior

We expected, that the admin user should be able to maintain all translations for all languages out of the box with now further configuration needed, but thats not the case.

After a while I found the reason:

The admin user was an editor user before and configured to maintain languages de and en.
On configuring him as an admin user by setting the checkbox in user configuration, the configuration
for language maintainance possibility is hidden in the user configuration.
In the Database the user configuration for fields "websiteTranslationLanguagesEdit" and "websiteTranslationLanguagesView" stays at the values "de,en" and after adding en_US as a new language
the fields in Database for this user are never updated. Also you are not able to update them in the user Settings of the
admin user anymore, because it`s an admin user ...

For me thats false !

On configuring an user as admin the database fields should be reseted or on adding a new language this language should be added in database for the admin but actually after adding a new language the admin can not maintain shared or admin translations for this language.

**Comment by mattamon** [comment]
Hey @SeatbeltElstner,

sorry that this is causing you troubles. 
Unfortunately we do not support Pimcore Version 10.6.9 anymore. 
As it seems that this is also not an LTS Issue I have to close your ticket.

Have you you already tried it with a newer version? If not I would encourage you to try it and maybe upgrade.
