### ISSUE TITLE
New Data Type - Input Quantity Value

### ISSUE THREAD

**Issue by mgomse** [pimcore/pimcore#1747]
## Feature description 
Quantity Value Data Type is really great but sometimes there is a need for some kind of merge between Quantity Value and Input Data types. 

I think that the best use case is that:
* we import some attributes from an external system (e.g. CSV file). Let say it looks like this:
    * Attributes Import

AttributeId | Attribute Name
------------ | -------------
1 | Weight
2 | Dimension (H/W/D)
3 | Type

 * Product Import

ProductId | AttributeId | Attribute Value | Attribute Unit 
------------ | ------------- | ------------ | -------------
1 | 1 | 20 | kg
1 | 2 | 2 / 3 / 4 | H/W/D
1 | 3 | Super Product | {no_unit_here}
* we store attributes them into classification store
* we cannot predict the type of attribute so we need to choose one
    * normally we will choose input
    * but we MUST import also units
    * so it seems that Quantity Value is a great type
    * but Value sometimes is not a "Quantity"

And here is my proposition for new type: "Input Quantity Value" - based mainly on Quantity Value, but with Input field for Value (not Number). An example of view (in the Object Classification Store Keys view) is below:

![image](https://user-images.githubusercontent.com/16497506/28413872-76343f8a-6d49-11e7-8e18-fa49cfd86cc8.png)

**Comment by weisswurstkanone** [comment]
Any updates on this one? See my comments in https://github.com/pimcore/pimcore/pull/1748

**Comment by brusch** [comment]
@mgomse  Anything?

**Comment by mgomse** [comment]
@weisswurstkanone @brusch 

Hi, sorry, but somehow I missed emails... I just saw your comment in #1748 so I'll try to do fixes as soon as possible and I'll let you know about progress

**Comment by weisswurstkanone** [comment]
great 👍 please don't hesitate to contact me if there are any questions

**Comment by mgomse** [comment]
FYI: #1748 is updated and I also added a comment with explanations: https://github.com/pimcore/pimcore/pull/1748#issuecomment-326748585

**Comment by sumit1337** [comment]
Hello sir I am facing below issue on saving quantity value  in my pimcore class
Please help me as soon as possible

 Reading... IDW Package.csv
07:18:21 ERROR     [pimcore] Class: Pimcore\Model\DataObject\Package => call to undefined method setLowestLevelUOMImperial

In AbstractModel.php line 266:
                                                                                                
  Call to undefined method setLowestLevelUOMImperial in class Pimcore\Model\DataObject\Package
