### ISSUE TITLE
[Bug]: Hotspotimage cannot save object with empty relational field inside marker

### ISSUE THREAD

**Issue by hadl** [pimcore/pimcore#17486]
### Pimcore version

Platform Version: 2024.2
Version: v11.3.0

### Steps to reproduce

- add marker to Hotpotimage with data asset, document or object
- do not set a value
- save data object

### Actual Behavior

Cannot save object exception:

`Message: Handling "Pimcore\Messenger\ElementDependenciesMessage" failed: Pimcore\Model\Element\Service::getElementById(): Argument #2 ($id) must be of type string|int, null given, called in ***/vendor/pimcore/pimcore/models/Element/Data/MarkerHotspotItem.php on line 89
`

Another exception:

`Pimcore\Model\Element\Service::getElementByPath(): Argument #2 ($path) must be of type string, null given, called in ***/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Hotspotimage.php on line 252`

### Expected Behavior

Use-case:
Marker with text has an optional CTA -> build with a document and an input field.

User should be able to save the object.

**Comment by mattamon** [comment]
@kingjia90 can we close this ticket since the PR is merged?

**Comment by kingjia90** [comment]
Yes, doing right now, thank you for the reminder

Fixed by https://github.com/pimcore/pimcore/pull/17492
