### ISSUE TITLE
[Documents] Show navigation visibility status in tree

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1749]
- same concept as publish state (which is gray & strike through) 
- use color code `#8e8e8e` for not visible in navigation

**Comment by ckemptner** [comment]
For the color I suggest => grey, non-strike-through 

A red color would highlight it, but if it is excluded from navigation, it should not be highlighted, but should rather be hidden / displayed less prominently.

**Comment by brusch** [comment]
I agree, the color code `#8e8e8e` should be fine. 

Example: 
![image](https://user-images.githubusercontent.com/142037/70917002-df8db280-201c-11ea-8f80-64bcae0e5bda.png)
