### ISSUE TITLE
Objectbrick inheritance not reflecting in REST

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#175]
If create a new brick and attach to the object class, then adding an object brick to parent object will be reflecting on variant in Backend UI but not in REST. And i need to save or save & publish all child objects to see newly added brick attributes of parent object.

Please follow the attached video to reproduce issue. 

Link to the forum post: https://www.pimcore.org/board/viewtopic.php?f=18&t=2372

**Comment by brusch** [comment]
This is currently a wanted bahavior, ... we need to introduce a switch that enables or disables inheritance for the actual REST request. Reason: for synchronisations of 2 pimcore instances it's necessary to not have inheritance, ...

**Comment by weisswurstkanone** [comment]
see [Webservices] Do not deliver inherited values #3411
