### ISSUE TITLE
[PIMCORE5] Pimcore Bundle Registering in AppKernel

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#1750]
## Feature
Register a Pimcore Bundle in AppKernel as a custom one without colliding.

## Possible Solution
1. Change Bundle Order [here](https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Kernel.php#L151): Switch L148 with L151 and skip activated bundles in the later pimcore bundle iteration.

2. Grey out the bundle in the extension manager, set it automatically to active and disallow any interaction with it:
![bildschirmfoto 2017-07-24 um 08 52 31](https://user-images.githubusercontent.com/700119/28511421-78895912-704d-11e7-8818-25c79e337502.png)

If you also think this is a good idea we could provide a PR for that. :)

**Comment by dpfaffenbauer** [comment]
The basic idea is to allow other Bundles to have a dependency on Pimcore-Bundles. With the proposed solution, it's not possible anymore to deactivate this dependency within the extension-manager and therefore break the application.

As @solverat already proposed, the extension-manager needs to check if the bundle has already been added to the kernel manually (inside the AppKernel) and disable the GUI for actions (enable, disable, update, install, etc.). 

It also needs to check if the bundle has already been added to the Kernel and doesn't enable it twice. This could happen if someone installs the Pimcore-Bundle first, and then installs another bundle, which enables the Pimcore-Bundle again.

Our basic idea is to have dachcom\members-bundle as dependency for CoreShop. So, if someone installs Members-Bundle, activates it in the Extension-Manager, installs CoreShop after that, and runs CoreShops install routine, the Bundle would be added twice and breaks Pimcore. 

The other side around would cause a similar Problem. Install CoreShop first (which already activates MembersBundle) and activate MembersBundle in the ExtensionManager.

Another possible idea would be to not display manually added bundles at all.
