### ISSUE TITLE
Importing native functions with use changes their strict behaviour

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#17504]
https://github.com/pimcore/pimcore/blob/a7f3fef2f8368122cb69c75bd1d4bb6726e638cc/models/Asset/Image/Thumbnail/Processor.php#L33 

with that statement, it seems the method call becomes strict concerning types ... which results in following error when generating thumbnails in backend ui:

![image](https://github.com/user-attachments/assets/5ee45ab4-6bb4-4687-922d-382556f3198a)

do you know anything about that?

_Originally posted by @fashxp in https://github.com/pimcore/pimcore/issues/17000#issuecomment-2293138869_

**Comment by blankse** [comment]
@fashxp I can't answer your comment because the PR is locked.

I don't know anything about that. 

But I think the imported functions now also use the strict mode in line 2. Because when you remove `declare(strict_types=1);` it also work.

**Comment by fashxp** [comment]
> I can't answer your comment because the PR is locked. 

need to check why that is happening... 

> But I think the imported functions now also use the strict mode in line 2. Because when you remove declare(strict_types=1); it also work.

But that behavior potentially introduces a lot of additional type errors, doesn't it? 
So I'm a bit afraid of introducing that in a minor :-) 

And what does this line do? https://github.com/pimcore/pimcore/blob/11.x/.php-cs-fixer.dist.php#L85

**Comment by jdreesen** [comment]
https://mlocati.github.io/php-cs-fixer-configurator/#version:3.62|fixer:native_function_invocation
> `strict` option: Whether leading `\` of function call not meant to have it should be removed.

**Comment by fashxp** [comment]
I don't understand this sentence :smile: 

Does it mean, when set to `false`, `\call_user_func_array()` won't be replaced to `call_user_func_array()`?

**Comment by jdreesen** [comment]
I'd say so, yes. 
Because `include` is set to `@compiler_optimized` I would expect everything else to be without a leading slash. 
So when `strict` is `true` the fixer should remove it if someone adds it. 
But when it's `false` the fixer ignores it (which means you are allowed to add leading slashes if you want to).

**Comment by fashxp** [comment]
ok, but in the case above this doesn't help. 

The code only works when removing the use statement and calling `call_user_func_array` without leading `\`. 
Without the use statement, but calling `\call_user_func_array` it also seems to be strict...
