### ISSUE TITLE
[Bug]: using agorate/pimcore-deepl not working with pimcore 11

### ISSUE THREAD

**Issue by ehabgrs** [pimcore/pimcore#17505]
### Pimcore version

11

### Steps to reproduce

First the package itself not able to be installed with pimcore 11, I have to fork the package repo and change the composer.json to allow pimcore 11.
Then after Install the agorate/pimcore-deepl package from the fork,  if you open a document. You should see a “DeepL Translation” button added to the translation icon. However, this button is not showing up.

### Actual Behavior

After install [agorate/pimcore-deepl](https://pimcore.com/en/developers/marketplace/agorate/pimcore-deepl_e235865) , When opening a document or any object there are no buttons for deepl translation.

### Expected Behavior

Show up a "deepl translation" button appended to the translation icon as it supposed to work here in the package js code https://github.com/agorate/pimcore-deepl/blob/main/src/PimcoreDeeplBundle/Resources/public/js/deepl-translation/startup.js

**Comment by fashxp** [comment]
not a Pimcore issue, please report in extension repository https://github.com/agorate/pimcore-deepl
