### ISSUE TITLE
Add UTF-8 support for keys/filenames of elements

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1754]
Only available if: 
- `innodb_file_format = Barracuda`
- `innodb_default_row_format = DYNAMIC`
- `innodb_large_prefix = 1` (if <= 5.7.6) 

Then max key-length = 3072 bytes => 768 characters when using utf8mb4. 
Default is to support utf8 chars, installer sets a flag if MySQL isn't compatible and changes the schema back to `ascii` (behavior as it is now). 

Row format for tables `objects`, `assets` and `documents` needs to be `ROW_FORMAT = DYNAMIC`.

**Comment by Cruiser13** [comment]
Will this fix #1070 ?

**Comment by brusch** [comment]
Yes

**Comment by camico** [comment]
Will this also allow "any" kind of character in asset-keys, or especially, object-keys?
(see also my question in https://talk.pimcore.org/t/allowed-characters-in-object-keys/127)
Thank you.

**Comment by brusch** [comment]
Yes, it will allow any (visible) characters. But I guess we'll filter some weird (non-printing) control characters, because they are completely unnecessary for this use-case and can cause confusion and lots of debugging effort (when copy & pasting them ...).

**Comment by brusch** [comment]
Only UTF8 characters with max. 3 bytes in length will be supported, otherwise we'd break the backward compatibility.
