### ISSUE TITLE
[Improvement]: Website settings events

### ISSUE THREAD

**Issue by jan888adams** [pimcore/pimcore#17543]
### Improvement description

I encountered an issue where it's necessary to purge the Varnish cache after a change in website settings. I noticed there were no existing events to hook into for this purpose. As a result, I created a patch for the project to address this need. I believe this could be useful for others as well.

Events:

Pre Add
Post Add
Pre Update
Post Update
Pre Delete
Post Delete
Post Load

**Comment by fashxp** [comment]
A PR would be great!
