### ISSUE TITLE
[Bug]: Compile Error: Cannot make non static method Pimcore\Model\DataObject\SelectOptionsInterface::getValues() static in class

### ISSUE THREAD

**Issue by paulverdu** [pimcore/pimcore#17554]
### Pimcore version

11.3.2

### Steps to reproduce

- Open any object with select options and notice the error `Compile Error: Cannot make non static method Pimcore\Model\DataObject\SelectOptionsInterface::getValues() static in class`.
- Open any created SelectOption and notice the error `Declaration of 'EnumGetValuesTrait::getValues()' must be compatible with 'SelectOptionsInterface->getValues()', cannot make interface method static`

### Actual Behavior

Interface `Pimcore\Model\DataObject\SelectOptionsInterface` is not compatible anymore because of the method `getValues` being static now in `models\DataObject\SelectOptions\Traits\EnumGetValuesTrait.php` due to PR merge https://github.com/pimcore/pimcore/pull/17349.

### Expected Behavior

Object loads without any problem and interface and Trait are compatible with each other.

**Comment by mattamon** [comment]
Thank you @paulverdu for creating the issue. 

I reverted PR and the fix will be released with the next Bugfix Version.
