### ISSUE TITLE
[Feature]: Analogue Document->getElement in twig

### ISSUE THREAD

**Issue by esisl** [pimcore/pimcore#17574]
### Feature description

In version 6, it was possible to access a document from a template

```
$doc = Document::getById($id);
echo $doc->getElement('name');

```
Is there an analogue in version 11 for twig templates?
I don't understand how to use pimcore_document for this

**Comment by kingjia90** [comment]
Thank you for your prompt!

This should work, not familiar with Pimcore 6, but getElement is only present in the `link` document type so far, so the code should look like
```
    {% set document = pimcore_document(236) %}
    {% if document is pimcore_document_link %}
        {{ document.getElement() }}
    {% endif %}
```
What would/should `getElement('name')` return?

Moving to discussion area, as it doesn't sound like a Feature
