### ISSUE TITLE
[Bug]: Migration Fails Due to Index Length Limitation with utf8mb4 Collation

### ISSUE THREAD

**Issue by developkariyer** [pimcore/pimcore#17581]
### Pimcore version

2024.2

### Steps to reproduce

1. Migrate Pimcore to a new server.
2. Do not be careful enough to keep the collation of the migration_versions table as utf8mb3 and leave it utf8mb4 after transfer.
3. Run the following migration command when required:

`bin/console doctrine:migrations:migrate`

4. Observe the error related to index length limitations.

### Actual Behavior

When running the migration with the utf8mb4 collation, the migration fails with the following error:
`SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes`

This occurs because of my mistake. However, the version column in the migration_versions table is VARCHAR(1024), and under utf8mb4 (which uses 4 bytes per character), the index exceeds MySQL’s InnoDB limit of 3072 bytes for indexed columns.

Temporary Solution: Changing the collation back to utf8mb3 allows the migration to succeed. However, MySQL warns that utf8mb3 is deprecated and will be converted to utf8mb4 in future versions, meaning this issue will likely reappear after an upgrade.

### Expected Behavior

The migration should complete successfully without hitting the index length limit, even with the utf8mb4 collation. Pimcore should handle the collation change and the long VARCHAR index in the migration_versions table in a future-proof way, given that utf8mb3 is deprecated and will soon be replaced by utf8mb4.

Key Issue: Since utf8mb3 is deprecated, continuing to rely on it will only postpone the problem. It is important to address this to ensure compatibility with future MySQL versions where utf8mb4 will be the default.
**`The recommended character set for MySQL is utf8mb4. All new applications should use utf8mb4. The utf8mb3 character set is deprecated.`**

**Comment by fashxp** [comment]
We are using doctrine migrations, so the `migration_versions` table is not created by Pimcore itself and we don't have control over its creation...

We could reduce the version_column_length in [configuration](https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/config/pimcore/doctrine_migrations.yaml#L9) ... but that could be potentially a BC break...

**Comment by fashxp** [comment]
I'll close for now. If this is a bigger topic, maybe someone can provide a PR for reducing the column length configuration.
