### ISSUE TITLE
[Bug]: since [#17435] cover function in image adapter completely ignores scaleByWidth and scaleByHeight when focalPoint is set

### ISSUE THREAD

**Issue by siwa-ddiesenreither** [pimcore/pimcore#17590]
### Pimcore version

11.3.2

### Steps to reproduce

Thumbnail Config:
[product-detail-thumb.yaml.zip](https://github.com/user-attachments/files/16961157/product-detail-thumb.yaml.zip)

I want the image having a focal point to cover my dimensions but not to be cropped out by the dimensions.

### Actual Behavior

![bug-actual-behaviour](https://github.com/user-attachments/assets/36ad5db6-aa42-43fd-b3e1-47d5e32f6225)

### Expected Behavior

![bug-expected-behaviour](https://github.com/user-attachments/assets/0fda628c-d306-4441-8a3c-441a69ae402c)

**Comment by kingjia90** [comment]
Thank you for reporting, I've reverted the changes that caused this regression on https://github.com/pimcore/pimcore/pull/17609 and will find a proper way to fix the initial reported case
