### ISSUE TITLE
[Bug]: $listing->getTotalCount() ignores offsets and limits

### ISSUE THREAD

**Issue by hethehe** [pimcore/pimcore#17618]
### Pimcore version

11.x

### Steps to reproduce

```
$list = new \Pimcore\Model\DataObject\Sample\Listing();
dump($list->getTotalCount()); //output 50
dump(count($list->loadIdList())); //output 50

$list->setoffset(20);
dump($list->getTotalCount()); //output 50
dump(count($list->loadIdList())); //output 30

$list->setlimit(10);
dump($list->getTotalCount()); //output 50
dump(count($list->loadIdList()));` //output 10
```

### Actual Behavior

the `$listing` method `getTotalCounts` ignores `offset `and `limit`

### Expected Behavior

the `$listing` methods `getTotalCounts` should consider `offset `and `limit`

**Comment by kingjia90** [comment]
Thank you for reporting!

From what i see, it is not a bug,  what you are looking for is [getCount()](https://github.com/pimcore/pimcore/blob/57504a894a54259ff7ffe1b7c3e5600733a7d60e/models/DataObject/Listing/Dao.php#L86-L95) and not `getTotalCount()`.

Looking forward for an eventually PR to improve the documentation but the issue would be closed
