### ISSUE TITLE
[Bug]: sku in order list

### ISSUE THREAD

**Issue by pmcr234** [pimcore/pimcore#17617]
### Pimcore version

v6.6.1

### Steps to reproduce

Hey I want to export my order data with the sku, however that doesnt work. how do I do it? please help

### Actual Behavior

No data is shown, when I add "items" via Operator any getter, no info is being shown.

### Expected Behavior

Need the sku to be shown

**Comment by siwa-ddiesenreither** [comment]
@pmcr234 as for Pimcore v6.6.1 please read this - https://pimcore.com/en/resources/blog/pimcore-x-prepare-and-schedule-update_a148335

Could you also provide a bit more detail on how your order data is stored? Are you using Coreshop, the E-Commerce Framework, or a custom solution?

By the way, this might not be the best place for these technical questions, but I'm happy to help as much as I can!

**Comment by pmcr234** [comment]
Hey thanks for your reply! We are using coreshop. here is a screenshot of what I see in pimcore!

<img width="809" alt="Bildschirmfoto 2024-09-16 um 17 30 52" src="https://github.com/user-attachments/assets/21794ebb-c1a7-4e0b-a010-e01fe8df3f57">
