### ISSUE TITLE
[Bug]: Thumbnail Generation is broken with Imagick

### ISSUE THREAD

**Issue by foxgreek** [pimcore/pimcore#17644]
### Pimcore version

11.3.2

### Steps to reproduce

Try to upload this image to the pimcore demo instance:
![broken-image](https://github.com/user-attachments/assets/65a95926-3474-4f49-8518-56c54f47d424)

### Actual Behavior

You will see this broken image in the preview:
![broken-image-thumbnail](https://github.com/user-attachments/assets/ec36b718-3190-4880-baf8-5d425f66559e)

Currently we deactivated Imagick in our projects with pimcore 11.3.2 and only use GD

### Expected Behavior

It should not be broken

**Comment by lukmzig** [comment]
@foxgreek can you please check if this is the same issue? https://github.com/pimcore/pimcore/issues/17589

**Comment by foxgreek** [comment]
@lukmzig amazing, works perfectly - thanks!
