### ISSUE TITLE
[Bug]: Assigning root document to pimcore_relation in twig fails

### ISSUE THREAD

**Issue by BentBr** [pimcore/pimcore#17649]
### Pimcore version

11.3.2

### Steps to reproduce

Using following snippet:
        {% set navigationRoot = pimcore_relation('root_node', {
            "types": ["document"],
            "subtypes": {
                "document": ["page", "folder"],
            },
            "reload": true,
        }) %}
        
If you now assign (via drag&drop) folders or documents (pages) to the relation it works just fine.
But if this document is the root doc with id=1 (home) than it fails.

### Actual Behavior

When assigning the rood document with id = 1 to the relation it fails due to a string to int conversion.

A quick fix would be to either remove the strictness again from `vendor/pimcore/pimcore/models/Document/Editable/Relation.php` or to cast in line 126 the id to int.

### Expected Behavior

All documents independent of if they are pages, snippets, sites or even the rood node should be assignable.

**Comment by Brainshaker95** [comment]
I think this issue relates to the admin ui classic bundle. It looks like the ID of the root document is [submitted as a string](https://github.com/pimcore/admin-ui-classic-bundle/blob/v1.6.1/public/js/pimcore/document/tree.js#L96).  
The same also happens in the `tree.js` files for [assets](https://github.com/pimcore/admin-ui-classic-bundle/blob/v1.6.1/public/js/pimcore/asset/tree.js#L83) and [objects](https://github.com/pimcore/admin-ui-classic-bundle/blob/v1.6.1/public/js/pimcore/object/tree.js#L92).  
This change was initially made to fix some kind of bug with the [showInTree](https://github.com/pimcore/admin-ui-classic-bundle/blob/v1.6.1/public/js/pimcore/treenodelocator.js#L37) function and ergo [this](https://github.com/pimcore/admin-ui-classic-bundle/blob/v1.6.1/public/js/pimcore/treenodelocator.js#L109) request.  (https://github.com/pimcore/pimcore/commit/3352e2e51f43dbe66b1055b7074db17d90b8bed1)
The [ElementController](https://github.com/pimcore/admin-ui-classic-bundle/blob/v1.6.1/src/Controller/Admin/ElementController.php#L460) now casts to an integer [which it didn't](https://github.com/pimcore/pimcore/blob/v10.6.9/bundles/AdminBundle/Controller/Admin/ElementController.php#L496) in the past.  
To me it looks like this fix from 2015 is no longer necessary. I will gladly provide a PR if I am correct here. Can anyone confirm my theory?

**Comment by fashxp** [comment]
we can give it a try for sure
