### ISSUE TITLE
[Bug]: Using an environment variable for "pimcore.general.domain" is not possible anymore

### ISSUE THREAD

**Issue by AlexanderHeidrich** [pimcore/pimcore#17667]
### Pimcore version

11.4.0

### Steps to reproduce

Adapt the config.yaml and add 
```
pimcore:
  general:
    domain: '%env(APP_URL)%'
```

### Actual Behavior

Open Pimcore in the browser. You will get the exception:
```
Invalid configuration for path "pimcore.general.domain": Invalid domain name ""%env(APP_URL)%""
```

### Expected Behavior

The url becomes processed correctly (before validation)
This worked before https://github.com/pimcore/pimcore/pull/17221

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/17685
Will be tagged by EOD
