### ISSUE TITLE
[Bug]: Wildcard Domains for the additional Domains in Sites not more possible.

### ISSUE THREAD

**Issue by et-cschwarze** [pimcore/pimcore#17669]
### Pimcore version

11.4.0

### Steps to reproduce

Add a Wildcard Domain in the "Additional Domains" Field in the Sites Formular. 

![Bildschirmfoto 2024-10-01 um 16 59 04](https://github.com/user-attachments/assets/ad648420-3b7b-4b73-8e46-344314c1a17e)

The Problem is the "FILTER_VALIDATE_DOMAIN" Flag in the setDomains Function from the Sites Model. 

![Bildschirmfoto 2024-10-01 um 17 07 48](https://github.com/user-attachments/assets/4bbeb801-d52a-4e0e-8630-3dd9ea89c9df)

The "FILTER_VALIDATE_DOMAIN" checks the RFC-compliant structure of a domain name. A wildcard (*) is not a valid part of a host name because, according to RFC standards, host names may not begin with special characters such as *.

### Actual Behavior

The System throw an exception.

### Expected Behavior

The Wildcard Domain is stored.

**Comment by fashxp** [comment]
related? https://github.com/pimcore/pimcore/issues/17667

**Comment by kingjia90** [comment]
It seems so, then i feel the best would be to revert https://github.com/pimcore/pimcore/pull/17221 and eventually provide a "less stricter" approach to validate 
@blankse could you please have a second look?

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/17685
Will be tagged by EOD

**Comment by blankse** [comment]
@kingjia90 Sorry for the late review, I was on vacation. The solutions look good.
