### ISSUE TITLE
[PIMCORE5] Unstable Alpha relies on PHP 7.1 dependencies

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#1766]
# Bug Report
I think Pimcore 5 still has PHP 7.0 as minimum requirement as of #1616 and the composer.json file.
But in the current unstables, zend-code is used in the vendor folder which does require PHP 7.1.
As a result, it's not possible to install the current Pimcore 5 alpha on PHP 7.0.

The following error will be thrown on install:
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /testpimcore/web/vendor/zendframework/zend-code/src/Generator/DocBlock/Tag/VarTag.php on line 24

There are other dependencies which require PHP 7.1 in the meantime too, for example the Doctrine Annotations.

Pimcore should probably set PHP 7.1 as minimum requirement or not ship with dependencies which require PHP 7.1.

**Comment by maff** [comment]
Doctrine updated many of their libraries to a new minor version requiring PHP 7.1 as minimum version. We updated our composer version constraints in cae862958d848cd5bc8651294986f69c9b754c31 - with the latest build you should only get PHP 7.0 dependencies.

However the problem should only arise if you install dependencies via PHP 7.1 and run the code via 7.0 (e.g. CLI running 7.1, webserver/FPM 7.0 or a deployment setup where code is deployed from a 7.1 environment to a 7.0 one) as composer should check the version constraints and only install packages matching your PHP version.
