### ISSUE TITLE
[Bug]: 11.3 broke some Advanced relations fields

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#17686]
### Pimcore version

11.3.2.1

### Steps to reproduce

1. Create a "Advanced Many-to-Many relation" field on a DataObject class in Pimcore 11.2.
2. Add some Columns.
3. Update to Platform version 2024.2.
4. Add an asset to the relation field.
5. Save & publish the DataObject.
6. Remove the asset from the relation.

### Actual Behavior

Error message and the relation remains:
```
Timestamp: Mon Oct 07 2024 12:48:25 GMT+0200 (Central European Summer Time)
Status: 500 | 
URL: /admin/object/save?task=publish
Method: PUT
Message: Warning: Undefined array key "id"
Trace: 
in /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php:286
#0 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Relations/ManyToManyRelationTrait.php(61): Pimcore\Model\DataObject\ClassDefinition\Data\Relations\AbstractRelations->save(Object(App\Model\DataObject\Product), Array)
#1 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php(596): Pimcore\Model\DataObject\ClassDefinition\Data\ManyToManyRelation->save(Object(App\Model\DataObject\Product), Array)
#2 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/Concrete/Dao.php(227): Pimcore\Model\DataObject\ClassDefinition\Data\AdvancedManyToManyRelation->save(Object(App\Model\DataObject\Product), Array)
#3 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/Concrete.php(213): Pimcore\Model\DataObject\Concrete\Dao->update(true)
#4 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(535): Pimcore\Model\DataObject\Concrete->update(true, Array)
#5 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/Concrete.php(667): Pimcore\Model\DataObject\AbstractObject->save(Array)
#6 /var/www/pimcore/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Admin/DataObject/DataObjectController.php(1389): Pimcore\Model\DataObject\Concrete->save()
#7 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(181): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#8 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#9 /var/www/pimcore/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /var/www/pimcore/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#11 /var/www/pimcore/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#12 /var/www/pimcore/public/index.php(19): require_once('/var/www/pimcor...')
#13 {main}
```

Breakpoint shows that there is no `id` in the array:
![image](https://github.com/user-attachments/assets/5de3b1cb-7e27-4ab8-9b38-8e0c1fffe708)

*Update:* Looking at the database it seems that all *Advanced* relation fields are missing the `id` column, while all simple ones have an `id` which is set to `auto_increment`.

### Expected Behavior

Relation should be removed without any errors.

**Comment by kingjia90** [comment]
Thank you for reporting!

~Looks like it would be fixed #17344 , would you be able to apply the changes and test it?~ 
Update: ah no, that PR is related to auto_id and not id

**Comment by kingjia90** [comment]
Could it be that it's an old project and missed this migration in https://github.com/pimcore/pimcore/pull/6961 at the time and the changes from https://github.com/pimcore/pimcore/pull/16482 (11.3.0) simply brought this back to the surface?

**Comment by NiklasBr** [comment]
The project in question started at Pimcore v6.5.1, so that is a plausible explanation. I can't see `Version20200817133132` in the migrations table.

**Comment by kingjia90** [comment]
Ahh that would be the case, thank you for the update, then this can be closed and marked as resolved.
In the case that the problem persists or is affecting in other ways, please re-open this or a new issue with more details.
