### ISSUE TITLE
[Bug]: Dashboard sidebar panel icon disappeared after upgrade to 11.x

### ISSUE THREAD

**Issue by medovanx** [pimcore/pimcore#17683]
### Pimcore version

11.4.0

### Steps to reproduce

After I upgraded using composer I found the icons missing

### Actual Behavior

![image](https://github.com/user-attachments/assets/2ad7bca6-33b3-4d24-9b6f-3fe7fc2173fa)

### Expected Behavior

Icons appear

**Comment by jdreesen** [comment]
Have you cleared your browser cache?

**Comment by medovanx** [comment]
> Have you cleared your browser cache?

Yes already tried that also cleared pimcore cache, no useful info in logs as well

**Comment by kingjia90** [comment]
Thank you for reporting!

Could you please share a screenshot of the `Console` of the `Developers Tools`? TIA
![image](https://github.com/user-attachments/assets/5e3a052b-d181-4e4c-b962-3bdfcc060a37)

**Comment by medovanx** [comment]
Thank you @kingjia90 and @jdreesen 

I tried clearing the browser cache and the cache again for the third time, and it worked this time..
