### ISSUE TITLE
[Improvement]: Remove direct `doctrine/collections` dependency

### ISSUE THREAD

**Issue by michalananapps** [pimcore/pimcore#17690]
### Improvement description

**Description:**
I kindly request an upgrade of the `doctrine/collections` dependency in the `composer.json` file to versions `^1.6.8 || ^2.0`. This upgrade is necessary to ensure compatibility with newer versions of Doctrine packages and to leverage the improvements and bug fixes in these versions.

**Current Dependency:**
```json
"doctrine/collections": "^1.6.8"
```

**Proposed Change:**
```json
"doctrine/collections": "^1.6.8 || ^2.0"
```

**Reason for Change:**
- Compatibility with newer versions of Doctrine packages.
- Access to improvements and bug fixes in the newer versions of `doctrine/collections`.

Thank you very much for considering this improvement request.

**Comment by jdreesen** [comment]
It seems that this library is not even used by Pimcore. Therefore, I think it can be removed instead.

**Comment by michalananapps** [comment]
@jdreesen

The `doctrine/collections` library is directly used in the following file:
[models/Element/Service.php](https://github.com/pimcore/pimcore/blob/15080bb27db59ce30680e5054bb2262ed41b1bbe/models/Element/Service.php)

**Comment by jdreesen** [comment]
Right, but just the class name for an `instanceof` check (in the `PropertyTypeMatcher`), and you can check against anything, the class doesn't need to exist, see: https://3v4l.org/9YmVm

**Comment by michalananapps** [comment]
> Right, but just the class name for an `instanceof` check (in the `PropertyTypeMatcher`), and you can check against anything, the class doesn't need to exist, see: https://3v4l.org/9YmVm

You are right. Thanks for an example.
