### ISSUE TITLE
[Bug]: The 'kernel' service is synthetic, it needs to be set at boot time when running update index command on 11.4.0

### ISSUE THREAD

**Issue by medovanx** [pimcore/pimcore#17691]
### Pimcore version

11.4.0

### Steps to reproduce

This happened after the upgrade from 10.x to 11.x, I have the following in services.yaml

```
    Symfony\Component\Lock\LockFactory:
        public: true
        
```
When running 
```
bin/console \
ecommerce:indexservice:bootstrap --update-index \
--object-list-class Pimcore\\Model\\DataObject\\Products\\Listing
```

### Actual Behavior

```
 ERR  In Container.php line 246:
 ERR                                                                                 
 ERR    The "kernel" service is synthetic, it needs to be set at boot time before i  
 ERR    t can be used.
```
![image](https://github.com/user-attachments/assets/1e3f0646-ac75-43c9-b7dc-64dcd1bf7660)

### Expected Behavior

Products are added to index

**Comment by fashxp** [comment]
duplicate https://github.com/pimcore/ecommerce-framework-bundle/issues/202
