### ISSUE TITLE
[Improvement] Upgrade dependencies where possible without BC break

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#17696]
### Improvement description

Check all dependencies for new major versions and add support/upgrade to it when easily possible without major efforts or BC breaks.  
Preferred solution would be to support old and new major version now (due to LTS support) and remove support for old major version then in pimcore/pimcore 12.

**Comment by jdreesen** [comment]
Like Symfony 7? :star_struck:

**Comment by fashxp** [comment]
egulias/email-validator 3.2.6 ~ 4.0.2 A library for validating email...
endroid/qr-code 4.8.5 ~ 5.1.0 Endroid QR Code
nesbot/carbon 2.72.5 ~ 3.8.0 An API extension for DateTime ...
presta/sitemap-bundle 3.3.1 ~ 4.1.1 A Symfony bundle that provides...
scheb/2fa-bundle 6.12.0 ~ 7.5.0 A generic interface to impleme...
scheb/2fa-google-authenticator 6.12.0 ~ 7.5.0 Extends scheb/2fa-bundle with ...

**Comment by fashxp** [comment]
> Like Symfony 7? 🤩

without BC break :smile:

**Comment by jdreesen** [comment]
Are there that many deprecations in Symfony 6 that require BC breaks to solve? :cry:

**Comment by michalananapps** [comment]
> Are there that many deprecations in Symfony 6 that require BC breaks to solve? 😢

I'm not sure if the difference in the minimum PHP version (8.1 for Symfony 6.4 and 8.2 for Symfony 7.x) might cause any issues here. It's also possible that Pimcore itself should require PHP ^8.2 in the 12.x versions, especially since PHP 8.1 is now only receiving security updates, and its support will expire in just over a year.

**Comment by michalananapps** [comment]
@fashxp `scheb/2fa` 7.x versions requires `"php": "~8.2.0 || ~8.3.0"`. Should pimcore also drop support for php8.1 here?

**Comment by jdreesen** [comment]
It shouldn't be a problem if you support both library versions, the current one and additionally the next mayor version. Composer will then select the library versions matching with your PHP version.

**Comment by michalananapps** [comment]
@fashxp Hello, will anyone be reviewing this pull request? Should I tag someone, or is it pending a release cycle and will be reviewed by a member of the Pimcore team in some time?

**Comment by fashxp** [comment]
@michalananapps thx very much for your efforts. yes, we will review the PR ... this whole topic is planned for die upcoming weeks

**Comment by fashxp** [comment]
> Are there that many deprecations in Symfony 6 that require BC breaks to solve? 😢

@jdreesen Actually I don't know. Believe me, we also would like to upgrade to Symfony 7 as soon as possible. 
The thing is though: right now, we have our priority on studio and not so much resources left for additional work. Also we need to keep an eye on our customers and their migration efforts.
 
Since Symfony 6 gets security updates until end of 2027, we plan Symfony migration in course of 2025 and be ready for 2026.1. 
Maybe we even manage to have one version (2025.4) to support symfony ^6.4 || ^7 - but that we will see when we are there. 

In the meantime, if anybody can support us in getting rid of deprecations (without BC breaks) and so preparing for the symfony upgrade, we are happy to review and merge PRs 😄. 

@michalananapps thx again for your efforts and support in that regards.
