### ISSUE TITLE
[PIMCORE5] internal server error leads to browser crash

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#1769]
- create a document
- **enable** debug mode
- open document, go to settings and define a not existing controller
- save document
- reload document in backend
- 500 internal server error: browser tab will crash since there seems to be a infinity 

> reproducable on [pimcore5-demo](https://demo-5.pimcore.org/).

**Comment by solverat** [comment]
it's a symfony bug: https://github.com/symfony/symfony/pull/23577 (should be fixed in 3.3.6)

**Comment by maff** [comment]
See #1763
