### ISSUE TITLE
[Bug]: Invitation link is send with protocol http and i need it to be https 

### ISSUE THREAD

**Issue by abdelrhmanyosry** [pimcore/pimcore#17702]
### Pimcore version

11

### Steps to reproduce

try to send invitaiton link for users 
check the  mail 
you will find your domain start with HTTP instead  of HTTPS 

### Actual Behavior

it send to new user  the domain with HTTP protocol and the link doesn't work if i don't change it manually to HTTPS 

### Expected Behavior

should send the right link for users with right protocol.

**Comment by fashxp** [comment]
are you in a docker setup or behind a proxy? 
does Pimcore know, that you are running in HTTPS? Eventually you need to forward certain headers, see also https://pimcore.com/docs/platform/Pimcore/Getting_Started/Configuration/#adding-logic-to-the-startup-process

**Comment by abdelrhmanyosry** [comment]
i'm in docker setup

**Comment by abdelrhmanyosry** [comment]
i added  custom_admin_route_name
![Untitled design](https://github.com/user-attachments/assets/344329e7-08db-438b-832a-100a66367e85)

but i get this error 
![Untitled design (1)](https://github.com/user-attachments/assets/0466710c-d436-45a5-9b55-5b25e577214d)

**Comment by fashxp** [comment]
it is not about configuring a custom route, it is about configuring symfony working properly behind a proxy .. see my link above and respective symfony docs: https://symfony.com/doc/current/deployment/proxies.html

**Comment by abdelrhmanyosry** [comment]
@fashxp i fixed the protocol issue but still has not worked!

[Image](https://github.com/user-attachments/assets/977595b6-9459-4e07-b770-d3db11e32c35)
![Image](https://github.com/user-attachments/assets/039cf5be-fb86-4eed-a3cd-24ef89750cfd)
