### ISSUE TITLE
[Bug]: [#17685] Crashes Pimcore instances having empty domain line in sites table/configuration

### ISSUE THREAD

**Issue by siwa-ddiesenreither** [pimcore/pimcore#17713]
### Pimcore version

11.4.1

### Steps to reproduce

Insert `a:1:{i:0;s:0:"";}` instead of `a:0:{}` to table `sites` into the `domain` field.

### Actual Behavior

Exception: Invalid domain name ""

### Expected Behavior

Ignore empty lines or trim field.

**Comment by kingjia90** [comment]
Thank you for reporting!

Closing as it is a duplicate of https://github.com/pimcore/pimcore/issues/17697 (as described [here](https://github.com/pimcore/pimcore/issues/17697#issuecomment-2399709051))and will be fixed by https://github.com/pimcore/pimcore/pull/17698 in upcoming `11.4.2`
