### ISSUE TITLE
[Bug]: MariaDB-Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535.

### ISSUE THREAD

**Issue by medovanx** [pimcore/pimcore#17733]
### Pimcore version

10.6.9

### MariaDB  version
10.6.8-MariaDB

### Steps to reproduce

When trying to add a new field to the Products class (it has many fields),
I'm trying to add  a (select list) field, I get the following database error

`An exception occurred while executing 'ALTER TABLE `object_query_6` ADD COLUMN `status_new` varchar(190) NULL;': SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs.`

`(ERROR 1118: Row size too large)` occurs because MySQL's row size limit for InnoDB tables is 65535 bytes, and the combined size of all columns, including storage overhead, exceeds this limit as far as I understand.

I have tried
- `ALTER TABLE `object_query_6` ROW_FORMAT=DYNAMIC;` (Which is useless because it's Dynamic by default in MariaDB anyways)
**DYNAMIC -> stores large variable-length columns like VARCHAR, TEXT, and BLOB outside of the row, reducing the row's size.**
- I also tried setting the following settings in my docker-compose according to some solutions found on Stackoverflow, but they didn't help

```
    db:
        image: mariadb:10.6.8
        working_dir: /application
        command:
            [
                mysqld,
                --character-set-server=utf8mb4,
                --collation-server=utf8mb4_unicode_ci,
                --innodb-file-per-table=1,
                --innodb-strict-mode=OFF,
                --innodb-log-file-size=500M,
                --innodb-log-buffer-size=800M,
                --innodb-file-format=Barracuda,
            ]
```

Not sure what to do ?
P.S it also happens for fields of **Type: Input**, haven't tried other types..

### Actual Behavior
![Image](https://github.com/user-attachments/assets/5055da1b-1182-41f7-8d91-090573a2c333)

A database error is raised when pressing save button in class from Dashboard

### Expected Behavior
New field added sucessfully

**Comment by brusch** [comment]
@medovanx Unfortunately this is a technical limitation of MySQL/MariaDB we have to deal with. 
Possible solutions how to solve this topics are: 
1. specify a length for input, numeric, ... fields whenever possible, either make them shorter, or use a length => 256
2.  use a textfield text instead of an input (blobs don't count for row size) 
3. rethink your data model 😉 often there are better ways to structure the data more efficient

See also: 
https://mariadb.com/kb/en/troubleshooting-row-size-too-large-errors-with-innodb/
