### ISSUE TITLE
[Bug]: copyRecursive fails on copying a folder with emails

### ISSUE THREAD

**Issue by lukadschaak** [pimcore/pimcore#17749]
### Pimcore version

11.3.0

### Steps to reproduce

Given this document structure
![Image](https://github.com/user-attachments/assets/4bd8c86b-87cb-4926-995b-c9c0bc2a365f)

Executing this code:
```php
$user = User::getByName('admin');
$targetParent = Document::getByPath('/documentB');
$sourceDocument = Document::getByPath('/documentA/emails');

$service = new \Pimcore\Model\Document\Service($user);
$service->copyRecursive($targetParent, $sourceDocument);
```

### Actual Behavior

The execution fails:
`Call to a member function getId() on null` at `vendor/pimcore/pimcore/models/Element/Service.php:594`

### Expected Behavior

It seems that `$new->getType()` is `email` and not `document` as expected some lines below in the `updateChildren` method [here](https://github.com/pimcore/pimcore/blob/11.x/models/Element/Service.php#L578).

Unfortunally i don't know how the updateChildren method is supposed to work, so i cannot fix it.

**Comment by dpfaffenbauer** [comment]
it also seems that properties are not copied anymore on recursive paste with updating references

**Comment by lukadschaak** [comment]
Super fast. The copying works for me. Thanks!

I do not have properties at the moment, but Dominik is right. Properties are not copied. Also not with `copyAsChild`.
