### ISSUE TITLE
[Bug]: Version preview of .ai files is broken

### ISSUE THREAD

**Issue by Navino16** [pimcore/pimcore#17768]
### Pimcore version

11.4.1

### Steps to reproduce

- Upload any .ai file
- Open version of this asset

### Actual Behavior

![Image](https://github.com/user-attachments/assets/32b0ddee-7546-4741-ac68-6468416eff11)

### Expected Behavior

We should be able to open version of .ai files

**Comment by kingjia90** [comment]
Thank you for reporting!

weird...by looking at https://github.com/pimcore/admin-ui-classic-bundle/blob/f178737274a38c7039fe4c5131aeeae98bded5db/src/Controller/Admin/Asset/AssetController.php#L936-L941
the asset's mimetype may be wrong, was it a pdf?

**Comment by Navino16** [comment]
@kingjia90 From what I see on google, ai files can have application/pdf as mimetype.

Also here you force all .ai files to be images: https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/config/pimcore/default.yaml#L200
So maybe the easiest solution is to add an exclusion on the AssetController for ai files?

And this can be related to: https://github.com/pimcore/pimcore/pull/17428

**Comment by kingjia90** [comment]
Ah, interesting, it seems so https://radu.link/mime-type-adobe-illustrator-ai-files/

Then the easiest and straightforward fix would be https://github.com/pimcore/admin-ui-classic-bundle/pull/733 
Let me know if it works and wish you a nice weekend

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/733
