### ISSUE TITLE
[Bug]: Pimcore Saving more than allowed number of objects in setting

### ISSUE THREAD

**Issue by abdelrhmanyosry** [pimcore/pimcore#17764]
### Pimcore version

11

### Steps to reproduce

set the number of versions to any number you want 
-> save the object many time. 
-> go check version page 
-> more than allowed number of versions are there. 

### Actual Behavior

more than allowed number of versions are there. 

### Expected Behavior

pimcore should delete versions after passing the number i set in settings.

**Comment by fashxp** [comment]
Versions are cleanup asynchronously via maintenance. So it might be, that there are more versions available temporarily.
Please verify that your maintenance is running properly.
