### ISSUE TITLE
[Bug]: Merge conflict mistake in Installer `mark_migrations_as_done`

### ISSUE THREAD

**Issue by morgannilsson** [pimcore/pimcore#17773]
### Improvement description

Version: pimcore:11.x

bundles/InstallBundle/src/Installer.php:478
Why is installClasses() called in both cases? Look like a merge error.

```
         if (in_array('install_classes', $stepsToRun)) {
            $this->dispatchStepEvent('install_classes');
            $this->installClasses();
        }

        if (in_array('mark_migrations_as_done', $stepsToRun)) {
            $this->dispatchStepEvent('install_classes');
            $this->installClasses();

            $this->dispatchStepEvent('migrations');
            $this->markMigrationsAsDone();
        }
```

**Comment by kingjia90** [comment]
Thank you for reporting!
Indeed, looks like i have messed up here https://github.com/pimcore/pimcore/commit/bac7e58136534a14bbdeeb4db77ca1d7183648f5 with https://github.com/pimcore/pimcore/pull/16729, 

Fixing it by https://github.com/pimcore/pimcore/pull/17774
