### ISSUE TITLE
[Bug]: EncryptedField getDataForGrid return typehint is defined as array while it could returns string

### ISSUE THREAD

**Issue by ComteZeroVD** [pimcore/pimcore#17777]
### Pimcore version

11

### Steps to reproduce

1. Create an EncryptedField with datatype "Input"
2. Add new object
3. Put some value in the EncryptedField
4. Display these objects in grid view
5. Add the EncryptedField in grid options

### Actual Behavior

Error is thrown : Message: Pimcore\Model\DataObject\ClassDefinition\Data\EncryptedField::getDataForGrid(): Return value must be of type array, string returned

### Expected Behavior

It should display the value as string

**Comment by blankse** [comment]
@ComteZeroVD I created a PR https://github.com/pimcore/pimcore/pull/17778

**Comment by robertSt7** [comment]
fixed by https://github.com/pimcore/pimcore/pull/17778
