### ISSUE TITLE
[Cache] Relations in Field-Collections are not cleared from cache when related object is updated

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#1777]
Scenario: 

objectA 
objectB has a fieldcollection with an relation to objectA which is called something like that
`$objectB->getFieldcollection()[0]->getRelation()` -> returns objectA

since lazyloading of relation data types in fieldcollections is not supported, cache entry of objectB also contains objectA (since it is related to it). 

if both objects (objectA and objectB) are in cache and objectA gets updated, objectB is not cleared from cache. and since objectA is also in the cache entry of objectB, the call `$objectB->getFieldcollection()[0]->getRelation()` returns old version of objectA

**Comment by brusch** [comment]
v4 + v5

**Comment by weisswurstkanone** [comment]
build 4095
