### ISSUE TITLE
[Bug]:  Cstore getter and setter is not Working

### ISSUE THREAD

**Issue by abdelrhmanyosry** [pimcore/pimcore#17786]
### Pimcore version

11

### Steps to reproduce

create a product with Cstore value let's call it $product_1  and try to set the cstore value inside $product_2 

`$product2->setCstoreAttribute($product_1->getCstoreAttribute); 
`
open the $product_2 you will find nothing there. 

### Actual Behavior

The Cstore Data Is NOT saved in the new product. 

### Expected Behavior

Data Should Be Saved inside CSTORE attribute

**Comment by abdelrhmanyosry** [comment]
@kingjia90  is there any updates on why it doesn't work as expected?

thankyou!

**Comment by kingjia90** [comment]
Thank you for reporting!

From a quick glance, it should likely be

```
$product2->setCstoreAttribute($product_1->getCstoreAttribute());

```
The parentesis after the getter getCstoreAttribute were missing

Hope it helps

**Comment by kingjia90** [comment]
Closing for the moment as it seems there is nothing to do on our side.
If i misunderstood and it still occurs, please open a new issue with more detail on how to reproduce it.

**Comment by abdelrhmanyosry** [comment]
@kingjia90 did you try to assign cstore from product1 to product2 and works with you?

**Comment by kingjia90** [comment]
I didn't reproduce it, the getter method was clearly missing the parenthesis, therefore it was never called to return values
