### ISSUE TITLE
[Bug, EC]: Error in DB query when using objectBrick in gridview

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#17814]
### Pimcore version

11.4.x

### Steps to reproduce

1. Create 2 objectBricks and on each one create a manyToOne field with same name 
2. Open grid view and add the 2 fields on different bricks
3. Populate the relation fields with some test value and then try to filter with "filter by relation”

### Actual Behavior

 An error occurs in DB query while using 2 relation fields (manyToOne) with same name in different objectBricks. For example, if you have 2 fields named "Color” in 2 different brick and you try to filter in a grid view, it shows the error attached.

![Image](https://github.com/user-attachments/assets/dfea2cb8-89e4-4fa2-aba6-6023b4d5da1d)
![Image](https://github.com/user-attachments/assets/1bda0ab2-88ac-4c9c-b50e-633df246169c)

### Expected Behavior

It works :-)

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/17815
