### ISSUE TITLE
[Bug]: Docs for SelectOptionsProviderInterface have bad example for getDefaultValue

### ISSUE THREAD

**Issue by cancan101** [pimcore/pimcore#17846]
### Pimcore version

11.4

### Steps to reproduce

The example docs for implementing `SelectOptionsProviderInterface` show  calling `getDefaultValue` on the `Data $fieldDefinition`:
https://github.com/pimcore/pimcore/blob/ee9bc5b162e68c25428963c693dfe980884d5ceb/doc/05_Objects/01_Object_Classes/01_Data_Types/30_Dynamic_Select_Types.md?plain=1#L61-L67

however that [class does not define](https://github.com/pimcore/pimcore/blob/ee9bc5b162e68c25428963c693dfe980884d5ceb/models/DataObject/ClassDefinition/Data.php#L31) a `getDefaultValue`.

### Actual Behavior

IDE error / warning on that line

### Expected Behavior

Example code as provided in docs will compile.

**Comment by blankse** [comment]
@cancan101 I created a PR: https://github.com/pimcore/pimcore/pull/17848
