### ISSUE TITLE
[Bug]: fieldcollection not found by maintenance task

### ISSUE THREAD

**Issue by klickparkdominik** [pimcore/pimcore#17854]
### Pimcore version

11.4.1

### Steps to reproduce

Exectue and consume the maintenance task with `bin/console pimcore:maintenance && bin/console messenger:consume pimcore_maintenance`

### Actual Behavior

An error is thrown while “pimcore_maintenance” is running:
`Fieldcollection 'Xxxx' not found. Please check table object_collection_xxxx`

![Image](https://github.com/user-attachments/assets/f0220cd3-9e3b-40f3-a75c-80730161f980)

### Expected Behavior

Perform all required actions without errors.

**Comment by blankse** [comment]
@klickparkdominik Duplicate of https://github.com/pimcore/pimcore/issues/17101 ?

**Comment by klickparkdominik** [comment]
I have already gone deeper into the problem, here are my findings.

To fix this problem I guess this file needs to be fixed. I can locate the error going back to this file:
https://github.com/pimcore/pimcore/blob/ee9bc5b162e68c25428963c693dfe980884d5ceb/lib/Maintenance/Tasks/DataObject/CleanupFieldcollectionTablesTaskHelper.php

In line 63 the value of the variable is lowercase. Example value: "keyfacts".
https://github.com/pimcore/pimcore/blob/ee9bc5b162e68c25428963c693dfe980884d5ceb/lib/Maintenance/Tasks/DataObject/CleanupFieldcollectionTablesTaskHelper.php#L63

In line 64 the value of the variable is suddenly uppercase, which leads to the task not being able to locate the correct table. Example value: "Keyfacts".
https://github.com/pimcore/pimcore/blob/ee9bc5b162e68c25428963c693dfe980884d5ceb/lib/Maintenance/Tasks/DataObject/CleanupFieldcollectionTablesTaskHelper.php#L64

The array `collectionNames` stores the values in uppercase, because they are read from the folder structure.

This is a screenshot of the pimcore folder on the webserver. You can see the filenames "Keyfacts" and "Benefits" being uppercase.
 ![Image](https://github.com/user-attachments/assets/9051f919-db17-42f0-8fb8-9d6f9eb3b4fc)
These filenames are being read by the cleanup-task: https://github.com/pimcore/pimcore/blob/ee9bc5b162e68c25428963c693dfe980884d5ceb/lib/Maintenance/Tasks/DataObject/CleanupFieldcollectionTablesTaskHelper.php#L28

This is a screenshot of the actual tablenames. You can see the tablenames "keyfacts" and "benefits" being lowercase.
![Image](https://github.com/user-attachments/assets/61f73d76-261c-4be2-8225-2d6638979940)
These tablenames are being read by the cleanup-task:
https://github.com/pimcore/pimcore/blob/ee9bc5b162e68c25428963c693dfe980884d5ceb/lib/Maintenance/Tasks/DataObject/CleanupFieldcollectionTablesTaskHelper.php#L56

**Workaround (not fix)**
To temporarly avoid throwing the error mentioned above I created a maintenance.yaml config and overwrote the task config like this:
```
services:
    Pimcore\Maintenance\Tasks\DataObject\CleanupFieldcollectionTablesTaskHelper:
    #     arguments:
    #         - '@logger'
    #         - '@Pimcore\Maintenance\Tasks\DataObject\DataObjectTaskHelper'
    #         - '@doctrine.dbal.default_connection'

    Pimcore\Maintenance\Tasks\CleanupFieldcollectionTablesTask:
    #     arguments:
    #         - '@Pimcore\Maintenance\Tasks\DataObject\CleanupFieldcollectionTablesTaskHelper'
    #     tags:
    #         - { name: pimcore.maintenance.task, type: cleanupFieldcollectionTables }
```

**Maybe related issues**

I found some issues that might be related:

- https://github.com/pimcore/pimcore/issues/12101
- https://github.com/pimcore/demo/issues/245
- https://github.com/pimcore/pimcore/issues/15413

I think this changed caused the problem:

- https://github.com/pimcore/pimcore/commit/03c06ee6cdc9533e821fc173f39a5688a1f9a069

Please note that our Pimcore installation is very old. It has been updated multiple times from version 6. Maybe this is not a problem for fresh installations but instead only for updated systems.

**Comment by klickparkdominik** [comment]
@blankse 
> [@klickparkdominik](https://github.com/klickparkdominik) Duplicate of [#17101](https://github.com/pimcore/pimcore/issues/17101) ?

This could indeed be related. My fieldcollection is also named with an initial lowercase letter. And I do run the same command aswell.

The referenced pullrequest (https://github.com/pimcore/pimcore/pull/17342) mentions the OS filesystem. We run Pimcore on Ubuntu 20.04.6 LTS.

Even tough I did not try the mentioned steps to reproduce, the description looks slimilar to my problem. I have attached valuable information in my comment above.

**Comment by klickparkdominik** [comment]
I digged deeper into the filechanges of this open pullrequest: https://github.com/pimcore/pimcore/pull/17342

This new line looks (on paper without testing) indeed like a solution to my problem:
https://github.com/pimcore/pimcore/blob/5919a4fc2dacd399f2951dc643bef529b659073e/lib/Maintenance/Tasks/DataObject/CleanupFieldcollectionTablesTaskHelper.php#L64

I am looking forward to the release of this change.

**Comment by klickparkdominik** [comment]
This issue is also related I guess:
https://github.com/pimcore/pimcore/issues/17741

**Comment by klickparkdominik** [comment]
Resolved by https://github.com/pimcore/pimcore/pull/17891
