### ISSUE TITLE
[Pimcore5] app/config/pimcore/system.php is overwritten by the Pimcore backend UI

### ISSUE THREAD

**Issue by pschirch** [pimcore/pimcore#1786]
Regarding to your [docs](https://www.pimcore.org/docs/5.0.0/Deployment/Multi_Environment.html) it is possible to create a file `app/config/pimcore/system.php` which is not touched by the Pimcore backend UI. Unfortunately the file is actually overwritten if a user saves the changes.

We use this file for our automated building environments, so it is necessary that this file can not be changed by the Pimcore backend UI.

Any advice?

**Comment by dpfaffenbauer** [comment]
One thing you could do: Create a Plugin and remove the System Settings menu point from the backend. Therefore nobody can open the Settings View and overwrite settings ;)

Another thing is: Change file permissions of your system.php to be readonly.

**Comment by brusch** [comment]
@pschirch yep, I can confirm that changing the permission is the way to go.

**Comment by pschirch** [comment]
@dpfaffenbauer @brusch 

Using file permissions or disabling the backend UI for handle system configurations sounds like a **unfortunate workarround**. Because the fact is only is a sympton of how Pimcore handle system configurations, I will create a new issue to discuss how we should improve this especially for a modern containerized environment.

**Comment by pschirch** [comment]
Please discuss the related topic in #1795.
