### ISSUE TITLE
[TinyMCE] Add deprecation info

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#17874]
### Improvement description

See #17821 

TinyMCE is going to be moved in it's own package, so we should deprecate it in `pimcore/pimcore` accordingly. 
-> add upgrade notes with reference to new Quill bundle as the successor or TinyMCE

Incl. some info about compatibility between TinyMCE and Quill, e.g. that it could be that certain attributes are not supported vice-versa, ...

**Comment by robertSt7** [comment]
see https://github.com/pimcore/pimcore/pull/17884
