### ISSUE TITLE
[Bug]: pimcore_video editable allowedTypes cannot be empty

### ISSUE THREAD

**Issue by muratbinerbay** [pimcore/pimcore#17923]
### Pimcore version

11.4.3

### Steps to reproduce

Try editing a video editable inside a document that does not have the `allowedTypes` set in the template.

Replicated on the Pimcore Demo site.

### Actual Behavior

There is a Javascript error logged in the console which blocks the video editable dialog from opening.
If the field is set there is no problem and the dialog will open.

![Image](https://github.com/user-attachments/assets/bb7491fc-2749-4c49-9c32-bb7a94a78036)

### Expected Behavior

Dialog should work with or without the `allowedTypes` attribute.

**Comment by blankse** [comment]
@muratbinerbay Duplicate of https://github.com/pimcore/admin-ui-classic-bundle/issues/784

**Comment by muratbinerbay** [comment]
Oops! Thanks @blankse, I missed to check in the admin-ui-classic-bundle.
