### ISSUE TITLE
[Bug]: show in tree button no longer works

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#17928]
### Pimcore version

11.4.3 / 11.5.0

### Steps to reproduce

Open a document, asset or object and click the button to show it in the tree.

### Actual Behavior

Nothing happens.

### Expected Behavior

The document / asset / object / asset should be shown in the tree.

It works in Pimcore 11.3.3, but no longer in Pimcore 11.4.3 and 11.5.0.

**Comment by blankse** [comment]
@cadeyrn Already fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/783

**Comment by cadeyrn** [comment]
Ah, thanks! I still need to get used to searching in multiple issue trackers. 😉

**Comment by jdreesen** [comment]
But not yet released, right?

**Comment by blankse** [comment]
@jdreesen I think you are right :)

**Comment by cadeyrn** [comment]
I can confirm that it works again in Pimcore Admin Classic Bundle 1.7.3.
