### ISSUE TITLE
[Pimcore5] Improve system configuration by supporting the environment variable mapping

### ISSUE THREAD

**Issue by pschirch** [pimcore/pimcore#1795]
As mentioned in [#1786](/pimcore/pimcore/issues/1786) the Pimcore system configuration can only used in automated or containerized environments with some unfortunate workarounds.

It should be possible to use the Pimcore backend UI and environment variables together. So if a environment variable is configured use it, otherwise use Pimcores system configuration as fallback. The backend UI can deactivate parameters are consumed by environment variables and show a tooltip that this parameter is managed by an environment variable and in addition provide the possibility to force an overwrite by the UI.

How that can be implemented? In a first iteration it can looks like following example.

1. The Pimcore backend UI only handle the parameters in `/var/config/system.php`.
2. The `/app/config/pimcore/system.php` ([docs](https://www.pimcore.org/docs/5.0.0/Deployment/Multi_Environment.html)) work as an environment variable mapper like:

```php
<?php

return call_user_func(
    function () {
        # filter all PIMCORE__ environment variables
        $environmentVariables = array_filter(
            $_SERVER,
            function ($key) {
                return strpos($key, 'PIMCORE__') === 0;
            },
            ARRAY_FILTER_USE_KEY
        );

        # build environment configuration
        $environmentConfiguration = [];

        foreach ($environmentVariables as $key => $value) {
            $realKey = substr($key, 9);
            $paths = explode('__', $realKey);
            $realVariable = &$environmentConfiguration;
            foreach ($paths as $path) {
                if (!isset($realVariable[$path])) {
                    $realVariable[$path] = [];
                }
                $realVariable = &$realVariable[$path];
            }
            $realVariable = $value;
        }

        # merge configurations
        $guiConfiguration = include(PIMCORE_PRIVATE_VAR.'/config/system.php');
        $configuration = array_merge($guiConfiguration, $environmentConfiguration);

        return $configuration;
    }
);
```

Now it is possible to define environment variables and consume it. For example in a docker compose file:

```yaml
  pimcore-cli:
    # ...
    environment:
      PIMCORE__database__params__dbname: pimcore
      PIMCORE__database__params__host: pimcore-mysql
      PIMCORE__database__params__password: secret
      PIMCORE__database__params__port: 3306
      PIMCORE__database__params__username: pimcore
    # ...
```

> Of cource, in a production environment  the env's are pushed by a configuration or secrets mangement system (Docker secrets, ...).

> **This example only demonstrate what the aim is.**

Since Pimcore is build on top of Symfony 3.3 the more sophisticated manner is to use their environment variable mapping:

* https://symfony.com/blog/new-in-symfony-3-2-runtime-environment-variables
* http://symfony.com/doc/current/configuration/external_parameters.html
 
@brusch @dpfaffenbauer What do think?

**Comment by dpfaffenbauer** [comment]
@pschirch I am not in a position to decide this, thats job of the core team. (@brusch, @maff)

In my opinion: I would move Database stuff out of the system.php config and move them into symfony configs (parameters.yml). Would make a lot of sense to load them via env variables for containerization as well.

I am happy with the rest of the stuff, since it makes a lot of sense to change settings within the backend, even though only administrators are doing that.

**Comment by pschirch** [comment]
The example handels the database configuration, but the mapping should be available for all parameters (especially mail settings, database settings, debug settings, proxy ...).

Furthermore, the flexbility is necessary for integrating health check and heartbeat services so you can auto migrate and restart containers with new database and mailing configurations controlled by environment variables.

**Comment by dpfaffenbauer** [comment]
@pschirch just stumbled upon this again. Some things changed since then, most didn't. So this is still not possible as you would think, but: Since all of the Pimcore System Settings are stored as parameters in the container and used in the config for other bundles (doctrine, swiftmailer), you can simply overwrite the configuration with what you need. Or also create a compiler pass to overwrite settings with ENV values.

**Comment by brusch** [comment]
Topic will be covered by #3268 and the use of `%env(FOO)%`
