### ISSUE TITLE
allow mail object modification in newsletter context

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#1801]
Some mail delivery providers allow [special header information](https://sendgrid.com/docs/API_Reference/SMTP_API/index.html) when sending emails via smtp (to pass a category for example). To add those information we need to modify the mail header. for example:

```php
$mail = new \Pimcore\Mail();
$headers = $mail->getHeaders();
$headers->addTextHeader('X-MC-Track', 'opens, clicks_htmlonly');
```

To do so, we could create a custom adapter (like the reportAdapter) and add some additional fields. But there is no way to add those infos to the email object. 

Maybe we should add a new method to `AddressSourceAdapterInterface`?

```php
<?php

//interface:
public function getMailObject();

//in the adapter itself:
public function getMailObject()
{
     $mail = new Mail();
     //do your config
     return $mail;
}

```
And instead of [this](https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Bundle/CoreBundle/Command/InternalNewsletterDocumentSendCommand.php#L157), we could do:

```php
<?php
 $mail = $addressAdapter->getMailObject();
 $mail = \Pimcore\Tool\Newsletter::prepareMail($mail, $document, $sendingParamContainer, $hostUrl);
```

what do you think?

**Comment by dpfaffenbauer** [comment]
relates to https://github.com/pimcore/pimcore/issues/1397 and https://github.com/pimcore/pimcore/issues/1191

**Comment by dpfaffenbauer** [comment]
and kinda to https://github.com/pimcore/pimcore/issues/252

**Comment by brusch** [comment]
I'd suggest: 
- `getMailObject()` in AddressSourceAdapterInterface
- event `pimcore.newsletter.preSend` passing same arguments as to `\Pimcore\Tool\Newsletter::prepareMail()`

**Comment by brusch** [comment]
That should be already possible by using the event `\Pimcore\Event\MailEvents::PRE_SEND`.
See also: #2495
