### ISSUE TITLE
Rethink Navigation Concept in Admin-UI

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1802]
Actually, on the Pimcore GUI, if we add parameters in the link url of `document link`, Pimcore will not find the linked document.
Adding parameters provide the ability to create link for menus for instance (using navigation helper) to bring some page with selected filtering (exemple: only a specific category of list of object, etc.).

`To reproduce:`
- create a document page `/blog/post-list`
- create a link `/blog/post-car` and and set the link to `/blog/post-list?category=car`, as in the following screenshot:

![link](https://user-images.githubusercontent.com/9025839/29183520-49c70eb2-7e03-11e7-89d8-ebae998c8e89.png)

- after rename the `post-list` document to post-listing for instance => the `post-car` link is not updated...

**Comment by brusch** [comment]
Currently Pimcore tries to resolve the corresponding document based on the given path, a query string is currently not handled separately. 

To achieve this, it would be necessary to introduce additional fields for the query string and the fragement, similar to the link dialogs we're using for document editables and object data-types. With this kind of separation it would be possible to save the according ID reference to a document while keeping the query string / fragment information.

**Comment by Yivan** [comment]
Thanks brush for your answer.
I dig in the code and it seems more difficult/changes than what i was thinking.
I was thinking to change the code here: https://github.com/pimcore/pimcore/blob/pimcore4/pimcore/modules/admin/controllers/LinkController.php#L106, but JS side need to be changes too it seems for displaying the correct value in the extJs input field.
And it would introduce a strange entity/data, hybrid between external and internal, a sort of monster :japanese_ogre: 

I like you idea of separating in string/fragment, but it will involves non negligible code changes...
Maybe there are some other way to do it. The heart of this issue was the need to pass some parameters from the link to the page... We cannot use properties of the link as it will be those of the linked page at the end.

**But finaly, i found a way, which is the Pimcore way i think:**
![url-param](https://user-images.githubusercontent.com/9025839/29423697-051f1f28-837d-11e7-900e-62aa1aed70f0.png)
It works great with pimcore pagination, even with custom navigation renderding ($page->getHref() take this parameters in the rendering).
**The issue can be close if you think this is a valid solution.**

Thanks.

**Comment by brusch** [comment]
Thanks for coming back on this topic. 
Maybe we should think about improving the UI in that matter -> but that's a different story :)

**Comment by Yivan** [comment]
Actually using "Parameters" in the "Enhanced" section of "Navigation settings" was ok, so yes can be closed for now.
