### ISSUE TITLE
Image editor - Display warning if dimensions are too big

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#1805]
# Bug Report
If an image in the image editor is too large (apparently more than 1000px width), it will be saved in max 1000px width.

### Expected behavior 
A warning should be display either before editing the image or before the actual saving takes place if the image dimensions will get smaller in the editing process.

### Actual behavior  
No warning is displayed.

### Steps to reproduce  
1)	Openimage with width >1000px
2)	Tab „Edit“ – „Effects“ –> Apply any Effect –> „Apply“ – „Save“
3)	Tab “View” -> Image only 1000px wide

**Comment by Cruiser13** [comment]
This is a limitation of the Adobe Creative SDK, I recently added the info to the docs here: https://www.pimcore.org/docs/latest/Assets/index.html

A warning inside Pimcore would be helpful.

**Comment by brusch** [comment]
Image Editor UI is deprecated, so it needs to be replaced / removed anyway. 
https://creativesdk.zendesk.com/hc/en-us/articles/115004788243

This has to be done until Nov. 2018 (the earlier the better).

**Comment by brusch** [comment]
See also #2010
