### ISSUE TITLE
[Redirects] Rethink implementation concept & improve UX

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1808]
- Source URLs like `https://www.example.com/de/xyz/foo/bar/MBB+2500+KL?page=5` are quite a challenge at the moment

Maybe we should think about offering different types of sources like: 
- match entire uri (proto+host+path+query)
- match everything after host (path + query) 
- match only path

All options either using regex or "match exactly".

**Comment by Yivan** [comment]
Is it linked to https://github.com/pimcore/pimcore/issues/1802 ?

**Comment by brusch** [comment]
@Yivan no, not that I'm aware of ;)

**Comment by brusch** [comment]
- Option "*Entire URL*" is then obsolete and should be migrated to new type (update script) 
- New option "*Regular Expr.*" which is off by default
- Beginner presets should continue to select the most appropriate type (see above) 
- Keep in mind that it is also possible to manage redirects directly on document pages, there it would make sense to replace the current interface with a grid based one -> same columns as the global redirect management, except the target page & target site (set implicitly).
