### ISSUE TITLE
ExtJS runs on loading iframes, throwing incorrect warnings, possible conflicts

### ISSUE THREAD

**Issue by deltafactory** [pimcore/pimcore#1809]
When loading Pimcore admin, there are warnings such as 
```
[W] Ext JS requires a viewport meta tag in order to function correctly on mobile devices.  Please add the following tag to the <head> of your html page: 
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
```

The relevant code is running against the home page of the empty profile. While the warning is true, it shouldn't be checking the iframe's document at all.

**Comment by brusch** [comment]
Well, there's no way I know of to disable this check.
