### ISSUE TITLE
Add the choice between DateTime and Zend_Date for dates getter.

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#181]
Actually the getter for the date of object send back Zend_Date object.
It would be great to be able to choose (at the object field level or as system configuration) beetwen this format or the DateTime format (and maybe string format as raw data for the date). Or just adopt DateTime instead Zend_Date (but would break many application using Pimcore).

Reason is Zend_Date is so slow that now DateTime is widespread it would be maybe better to use it as it is greatly faster. More and more application make use of dates (i think to all aplication making use of period, range, date for booking services, hotel...). Using Zend_Date for some complex algorithm like yield management is a no way as it is up to 10 times slower than native php DateTime.
Searching google for "zend date slow" show it is not the holy grail for managing date now. You can find a benchmark here:
http://riotech.blogspot.fr/2009/03/zenddate-vs-datetime-performance.html
It show a 60x improvment by using DateTime (but biased because we can improve Zend_Date by caching it).

Maybe extend DateTime use for creation/modification date (and planified event for publish, etc.) would imporve as well Pimcore globaly.

Third point to take into account is that if you plan to move from ZF1, using DateTime will make process of migration easier for actual Pimcore user. So implementaing DateTime as soon as possible will remove this hard dependency to ZF1. One way to handle this would be new installation are by default using DateTime, but in system config it can be switched to Zend_Date wich will be indicated as deprecated. Updating old Pimcore would keep Zend_Date as prefered method for global configuration.

Another good point is when ZF1 will be end of life, Pimcore won't suffer of this (or less).

Regards.

**Comment by kanevbg** [comment]
Fully supporting the idea for configuration giving a choice whether to use DateTime or Zend_Date

**Comment by zspine** [comment]
+1

**Comment by brusch** [comment]
See: https://www.pimcore.org/wiki/display/PIMCORE4/Upgrade+Notes

**Comment by brusch** [comment]
see: 
c8e661c65b978fae1813b84b342ec5e91befceba
and
e08ac85707bdc5cf85a6527514031a37cad6515a
