### ISSUE TITLE
Better in-place description of DEV-MODE in system settings

### ISSUE THREAD

**Issue by deltafactory** [pimcore/pimcore#1810]
From https://talk.pimcore.org/t/debug-mode-that-allows-use-of-un-minified-assets/85/3:

> Would it be reasonable to request that the "DEV-mode" setting includes a brief description of its purpose and correct usage, indicating that it's not intended for most users, instead of a scary red-text warning?

**Comment by solverat** [comment]
see also https://github.com/pimcore/pimcore/issues/654 :)

**Comment by deltafactory** [comment]
@solverat I ran across that issue while searching for an explanation of what it was. Unfortunately, the exact explanation was found elsewhere.

If it helps clean up the UI, perhaps it could only expose the DEV-mode option once Debug mode is enabled/active.
