### ISSUE TITLE
Session lock when generating Document Version Comparison Preview

### ISSUE THREAD

**Issue by IgorBenko** [pimcore/pimcore#1812]
I am not creating a pull request since I still haven't figured out exactly where the problem comes from. We have multiple installations of Pimcore 4.5 and we wanted to use the Version Compare feature of documents. I properly installed ImageMagick, wkhtmltopdf with QT patched and xvfb but it still didn't work. Then I figured out that wkhtmltoimage could never load the html since the request was blocked. This was caused by the session lock of the original DocumentController::diffVersionsAction() request. 

Adding session_write_close() before the HtmlToImage calls in DocumentController seems to solve the problem.

I checked the newest pimcore demo and the document compare feature works perfectly. I checked the source code and there you don't do anything special with the session. 

My question would be, was this somehow fixed in Pimcore 5? If it did work properly in 4.5 what do you think could be a problem for our installations? We are using nginx instead of apache, but I don't see that as an issue. 

I would be happy to do a pull request with above described change, but beforehand I would like to understand why it works for Pimcore Demo installation and not our installation.

Any input would be highly appreciated!

**Comment by brusch** [comment]
Which `session.save_handler` are you using? 
The demo uses just the standard `files` handler ... very interesting :|

**Comment by IgorBenko** [comment]
Thanks for your reply Bernhard! I finally tracked down the culprit. I am setting some things in the /website/var/config/startup.php based on a value in session (for testing purposes).

Just by calling this, already the session lock is there:
```
$session = \Pimcore\Tool\Session::getReadOnly();
```
I would expect using getReadOnly wouldn't lock the session, but I am not sure why this is so.
Doing session_write_close on next line doesn't help, nor does \Pimcre\Tool\Session::writeClose().

Adding session_write_close directly to the DocumentController does work for some reason.

Would adding the session_write_close to the DiffVersionsAction method be OK for you?

Do you have any idea why that would happen? I guess starting session in startup.php might change something with how the session is then initialized for the Admin Controller.

**Comment by brusch** [comment]
Session handling is completely different in Pimcore 5, I'd assume that this isn't an issue anymore.
