### ISSUE TITLE
Prevent warning by adding override property in overrides.js

### ISSUE THREAD

**Issue by deltafactory** [pimcore/pimcore#1813]
There's a warning message for re-defining `Ext.scroll.TouchScroller` in overrides.js.
https://github.com/pimcore/pimcore/blob/dce23faacfbb388028282f94769fc0f9e5ecdb08/web/pimcore/static6/js/pimcore/overrides.js#L799-L802

I don't know the desired behavior or if this is the correct way to address it.

**Comment by deltafactory** [comment]
This override attempts to address changes in ExtJS 6.2. If a move to ExtJS 6.2 (or higher) is still on the roadmap, then use of scrollers methods should be verified.

Accidental use of the TouchScroller in desktop browsers may be triggered by a bug in `Ext.supports.Touch` discussed here: https://www.sencha.com/forum/showthread.php?336762-Examples-don-t-work-in-Firefox-52-touchscreen/

**Comment by brusch** [comment]
ExtJS 6.2 is not GPLv3, therefore we're not going to migrate to Ext 6.2 for licensing reasons. 
The next GPLv3 licensed ExtJS version will be 7.
