### ISSUE TITLE
Terminate ffmpeg preview generation process when asset is deleted

### ISSUE THREAD

**Issue by deltafactory** [pimcore/pimcore#1815]
### Steps to reproduce
1. Upload video asset
2. View video asset, observe that the preview is being generated. On host system, verify ffmpeg process is running
3. Delete asset, confirm
4. See that ffmpeg is still executing

This task may be very difficult depending how the transcoding process is tracked. It's more of a nice-to-have feature than anything.

**Comment by brusch** [comment]
To be honest, while technically possible, this is not a critical issue nor it is somehow relevant and it would make the already very complex asynchronous transcoding job even more complicated.
