### ISSUE TITLE
Create button (and other action) in toolbar of object view screen

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#182]
It would be very helpful if there is an action button (dropdown) in the toolbar of the object view screen.

This action button could have the following functions:
- Create object of your choice, that will nested directly under the opened object
- rename the object ( key)
- Import objects directly
- locking
- copy/paste

For more detail see: https://www.pimcore.org/board/viewtopic.php?f=17&t=2337

**Comment by brusch** [comment]
- Rename: Done

**Comment by fashxp** [comment]
since show in tree works now also for paged trees, not necessary anymore
