### ISSUE TITLE
Tag&Snippet Management: Add configuration option to disable a tag without having to delete it

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#1824]
Currently the only way to disable a tag configuration is to completely get rid of it.

![image](https://user-images.githubusercontent.com/6142086/29400507-e7fa5966-832d-11e7-9fa2-f76c5692e59f.png)

**Comment by markus-moser** [comment]
see #1085

**Comment by weisswurstkanone** [comment]
many thanks, closed 1085 in favour of this one

**Comment by weisswurstkanone** [comment]
builld 95

can be completely disabled or just on tag level

![image](https://user-images.githubusercontent.com/6142086/29462010-1ee9610a-842e-11e7-841d-e1b9a42ef631.png)
