### ISSUE TITLE
[Pimcore 4] For same page, static route event send all parameters, no reset possible.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1828]
Actually the event frontend.path.staticroute send 3 parameters:
- params
- reset
- encode

If the url is the same page, request value are merged even if reset is true.
The problem is we cannot with this event know if the parameters in even data "params" is really a parameter passed to the url view helper method or parameter in the request.

See this line:
https://github.com/pimcore/pimcore/blob/pimcore4/pimcore/models/Staticroute.php#L504
`self::$_currentRoute->_values` add back the values

We are stuck with some custom route, because we use some optionnal parameters in $this->url, and they are setted automaticaly from the actual request... even with the reset params.

**Solution for the event:**
Maybe add least add a 4th parameter in the event: "urlOptions" so we can access to the exact parameters given at the url method and code logic from this if wanted.

Solution more global:
I think this problem can arise more generaly for static routes.
For instance actual request is:
`http://www.domain.com/blog?cat=car&tag=blue`
And we get a static route called `blog` (having `cat` and `tag` as **optionnal parameters**) in the view with the following code:
`$this->url(["cat" => "car"], "blog", true)`
=> tag will always be "blue" for the route url generation... : (
The only way is to force manually a `$this->url(["cat" => "car", "tag" => ""], "car", true)`, but this is not convenient and will lead to error as using "reset" we think of those parameters being reseted.
So maybe code need to be adapte the code here:
`https://github.com/pimcore/pimcore/blob/pimcore4/pimcore/models/Staticroute.php#L506 to strip of route parameters from `self::$_currentRoute->_values ?

**Comment by brusch** [comment]
Pimcore 4 is EOL
