### ISSUE TITLE
Possibility to desactivate srcset in the getHMTL method for thumbnail.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1829]
Actually, it is not possible to desactivate srcset tag when using getHMTL() for thumbnail.
Ex:
`$myImage->getThumbnail(["width" => 200])->getHTML();`

We had some problems with srcset tag (with some JS code/sliders), and i think it would be nice to have an option like ["no-srcset" => true] for the getHMTL method.

**Comment by tgross-m-s** [comment]
Same problem with
`$this->image('bild', ['thumbnail' => 'content']);`

I don't understand why pimcore forces all thumbnails to use high-res images.
This should be optional!

**Comment by brusch** [comment]
```php
<?= $this->image("image", [
    "thumbnail" => "content",
    'removeAttributes' => ['srcset']
]); ?>
```
