### ISSUE TITLE
Assets: ContentOptimizedFormat on PNG causes Problems with X-Content-Type-Options: nosniff

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#183]
When using ContentOptimizedFormat on PNG's without Alpha-Channels, Pimcore converts those Thumbnails to JPEGS but keeps the file suffix to PNG. 

When sending the HTTP-Header "X-Content-Type-Options: nosniff",
that causes a problem on IE11 so the Image won't be displayed.

Currently i have no Test-Setup to show you the problem. I tested it on the Pimcore-Demo, everything seems alright there, because of the missing Header "X-Content-Type-Options: nosniff".

http://answers.microsoft.com/en-us/ie/forum/ie11-iewindows8_1/image-is-not-decoded-by-ie-11/b4a5467b-ad7e-4612-8ea5-d2508533381c

**Comment by BenjaminEden** [comment]
Is there a way to get Pimcore to change the file extension to jpeg for this case (png with no alpha channel)? IE11 seems to have problems with jpegs that have a png file extension.

**Comment by brusch** [comment]
@BenjaminEden unfortunately there's no way of doing so, because it's an asynchronous process and we can't predict the most efficient format. 
But the referenced patch should solve the problem for you.

**Comment by BenjaminEden** [comment]
Thanks Bernhard,
for some reason I had to add

`Header unset X-Content-Type-Options`

as well (without "always"). But now it's working.
I'm using Apache 2.4.25.

Thank you!
