### ISSUE TITLE
Improvement: add open linked document for link and hard-link

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1832]
Like many linked fields in Pimcore, it would be great to be able to open directly the linked document in the link and hard-link document type. It could greatly improve the navigation for editing pages on comlexe site with many documents/links.
It will only appear for those of "internal" type (for external it could be a new tab).

![linked-document](https://user-images.githubusercontent.com/9025839/29426002-80cf3452-8385-11e7-93b5-9c0c82bd1493.png)

**Comment by brusch** [comment]
See also #1802

**Comment by weisswurstkanone** [comment]
build 106
