### ISSUE TITLE
[Pimcore 5] Area Brick names are not shown in toolbar and buttons

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1837]
![image](https://user-images.githubusercontent.com/142037/29454594-0912a172-840e-11e7-954f-9a717440b2bb.png)
![image](https://user-images.githubusercontent.com/142037/29454602-11505b0e-840e-11e7-8941-c82819b3b3ca.png)

**Comment by maff** [comment]
Seems to be caused by https://github.com/pimcore/pimcore/issues/1845#issuecomment-324101148.
