### ISSUE TITLE
addConditionParam method for list don't encapsulate the query fragment

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1838]
Actually using addConditionParam method for object listing dont put parenthesis for the sql fragment.
I think the usual way is it is automaticaly encapsulated by parenthesis because:
- ZF1 work like this when you add a ->where in a chaining select
- If not parenthesis is added, the 3rd parameter (the concatenator AND/OR) is less predictable

Exemple:

```
$appList = new App\Listing();
if (isset($params["category"]) && $params["category"]) $appList->addConditionParam("category = ?", $params["category"]);
if (isset($params["isFree"])) {
	if ($params["isFree"] == "0") $appList->addConditionParam("isFree = ? OR isFree IS NULL", 0);
	if ($params["isFree"] == "1") $appList->addConditionParam("isFree = ?", 1);
}
if (isset($params["order"]) && $params["order"] == "averageRating") {
	$appList->setOrderKey("averageRating");
	$appList->setOrder("desc");
} else {
	$appList->setOrderKey("lastUpdate");
	$appList->setOrder("desc");
}
$appList->load();
echo $appList->getQuery()->__toString();
```

Will output:
`SELECT object_18.o_id as o_id, `object_18`.`o_type` FROM `object_18` WHERE ((category = ?  AND isFree = ? OR isFree IS NULL  AND  object_18.o_type IN ('object','folder')) AND object_18.o_published = 1) ORDER BY `lastUpdate` DESC`

As it can be seen the **"isFree = ? OR isFree"** fragment is not encapsulated by parenthesis.

Proposed solution:
Maybe here https://github.com/pimcore/pimcore/blob/pimcore4/pimcore/lib/Pimcore/Model/Listing/AbstractListing.php#L209 we could add:
**$key = "(".$key.")";**

**Comment by Yivan** [comment]
Can I made a pull request with the proposed modification so the addConditionParam is properly encapsulated ?

_But maybe it could break existing Pimcore because some code could rely on being not encapsulated...
If you think it will break backward compatibility, maybe we should add a bolean parameter to `addConditionParam`. It could be named `$encapsulate` and be false by default (so it won't break compatibility). Setting it true will encapsulate like this: `$key = "(".$key.")";`_

**Comment by fashxp** [comment]
how was the behavior in pimcore4?

**Comment by Yivan** [comment]
This is the behaviour on Pimcore 4.

For instance, making:
```
$appList->addConditionParam("category = ?", 17)
$appList->addConditionParam("isFree = ? OR isFree IS NULL", 0);
```
will construct a where condition like this:
`category = 17 AND isFree = 0 OR isFree IS NULL`

I propose to add `$key = "(".$key.")";` right at the start of the method here https://github.com/pimcore/pimcore/blob/pimcore4/pimcore/lib/Pimcore/Model/Listing/AbstractListing.php#L209.
So the where condition will be:
`(category = 17) AND (isFree = 0 OR isFree IS NULL)`
which make more sense and is what is attended (ZF1 autoencapsulate the ->where() method).

The same patch could be done for Pimcore 5 by adding `$key = "(".$key.")";` here:
https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Model/Listing/AbstractListing.php#L214

**Comment by Yivan** [comment]
Thanks!
Be carefull to make a note in Pimcore changelog about it because it can break existing code relying on the old way of not encapsulate (query result could be different before and after this commit)
