### ISSUE TITLE
Translate key with empty translation returns empty value, not key anymore

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#1845]
# Bug Report
When Pimcore creates new translations automatically, the texts are deleted as soon as a refresh occurs.
 It used to work for the previous Pimcore versions, and the bug probably relates to one of the latest updates.

### Steps to reproduce  
1) Add a new translation key in a view with $this->t("my-translation-key")
2) Press refresh => a translation is created.
3) Press refresh again => the result of $this->t("my-translation-key") is an empty string.

**Comment by solverat** [comment]
i can confirm this. since this commit (https://github.com/pimcore/pimcore/commit/ea53b3e470d68aa5365665a6cf94bd4ffe50798f), 
backend translations are empty which leads to empty / not working area bricks...

**Comment by solverat** [comment]
btw. nothing gets deleted, it's "just" a empty translation key return.

**Comment by brusch** [comment]
@maff 

Adding 

```php
if ($id && !$translated) {
    return $id;
}
```

At the end of 
`Translator::checkForEmptyTranslation` 
should fix it.

**Comment by brusch** [comment]
So befor the last line `return $translated;` ;-)

**Comment by fashxp** [comment]
I'll have a look at it today

**Comment by andreas-gruenwald** [comment]
I tested it, it works.
