### ISSUE TITLE
[Pimcore5] Dropping elements into hrefs should produce same result as obtained by selecting them

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#1859]
see https://github.com/pimcore/pimcore/issues/1743

**Comment by weisswurstkanone** [comment]
build 97

**Comment by AlternateIf** [comment]
i experience the same/a similar problem on build 137. a extjs object-panel doesn't allow dropping elements at all. When i try to select via search all items are insertable

@weisswurstkanone
