### ISSUE TITLE
Routes for admin ui

### ISSUE THREAD

**Issue by schauer** [pimcore/pimcore#1861]
In order to change the route for the AdminBundle from "/admin" to something else please use the Router the generate Urls.

See using Router to generate URLS in Contoller: https://symfony.com/doc/current/routing.html#generating-urls

So for example in the method \Pimcore\Tool\Admin::getMinimizedScriptPath do not use hard codet url like
`'/admin/misc/script-proxy?' . array_toquerystring($params);`
 instead use 
`$router = \Pimcore::getContainer()->get('router')

 return $router->generate('pimcore_admin_misc_scriptproxy',$params);
`

For JavaScript use the Bundle FOSJsRoutingBundle, see https://symfony.com/doc/current/routing/generate_url_javascript.html and https://github.com/FriendsOfSymfony/FOSJsRoutingBundle

**Comment by fashxp** [comment]
see https://github.com/pimcore/pimcore/issues/2544
