### ISSUE TITLE
Object with geo data using Google won't open offline

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1866]
I get this problem, working offline on a Pimcore project.
Some object have geo data element like "Geopoint".(https://www.pimcore.org/docs/latest/Objects/Object_Classes/Data_Types/Geographic_Types.html).
Those use Google API.

But when open in Pimcore back-end, to edit the object, with no network connection, a JS error is trigerred saying google class doesn't exists (as the js file has not been fetched on the google domain because no network on my workstation during traveling).

Maybe the error could be catched, so the objects using geo data could be open offline ? 
(this issue is more for developpers, because at the end the web site will be online... but the problem could arise if for some reason google domains are filtered/firewalled on some enterprise network).
At least we could be able to open the object.

**Comment by weisswurstkanone** [comment]
build 99

**Comment by Yivan** [comment]
Thanks a lot!
Could this fix be ported to Pimcore 4 ? (we made some demo of existing project to customers sometimes, and not having always a connection during those meetings. It will prevent to break it if geo data is in some object).

**Comment by fashxp** [comment]
could you provide a pull request for pimcore4? :)
