### ISSUE TITLE
UI: error grouping classes in object contextual menu

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#187]
![image](https://cloud.githubusercontent.com/assets/142037/8722369/405fb902-2bc4-11e5-88f0-d67626d82135.png)

![image](https://cloud.githubusercontent.com/assets/142037/8722370/44c58274-2bc4-11e5-97ee-417b0cdf3d55.png)

**Comment by mrudnicki-pimcore** [comment]
see #643
