### ISSUE TITLE
No valid debug email address given in "Settings" -> "System" -> "Email Settings"

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#1877]
Is it really necessary to throw that exception? Wouldn't it be enough to raise an warning in log?

It's kinda annoying when developing and people always forget to set that :/

**Comment by fashxp** [comment]
There is an exception thrown by swift anyway: 

```
Error during sending confirmation e-mail: Swift_TransportException: Cannot send message without a recipient in /home/ecommerce/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/MailTransport.php:133
```

But this error message will cause you endless searching why mail could not be sent - at least we did at the beginning ;-). 

Our error message `No valid debug email address given in "Settings" -> "System" -> "Email Settings"` helps you to find out where to search.

**Comment by dpfaffenbauer** [comment]
I guess that's because you didn't set any recipients? I do set a recipient and Pimcore throws an exception anyway.

**Comment by fashxp** [comment]
but when in debug mode I don't want that the mail is sent to its original recipient, therefore no recipient is set if no debug address is set.
