### ISSUE TITLE
Adding possibilty to use GA Pimcore reporting without inject the tag in frontend.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1882]
Google analytics can be configured in the marketing settings.

We wanted to add ourselves the GA tags in the front-end website (because of some custom handling of it), but having possibility to have the GA reporting associated in documents in the Pimcore back-end.
Actually, this is not possible.

Solution.
Adding a checkbox to disable injection, like showed on this image:

![ga-inject](https://user-images.githubusercontent.com/9025839/29890194-10ffce60-8dc7-11e7-96d5-1e40336f62e9.png)

This way, developpers can handle themselve the inject of the GA analytics code in the website if needed.

**Comment by brusch** [comment]
I'm just thinking if this really needs another configuration or if this should be better done in the code...
I'd prefer the latter option. 

In the code you can easily deactivate the code injection using the following code: 

Pimcore 4: 
```php
$front = \Zend_Controller_Front::getInstance();
$front->unregisterPlugin('\Pimcore\Controller\Plugin\Analytics');
```

Pimcore 5: 
```php
$gaListener = $container->get('pimcore.event_listener.frontend.google_analytics_code');
$gaListener->disable();
```

**Comment by brusch** [comment]
I'll close this issue for now. 
If anyone else would love to see this feature in Pimcore please react with a +1 :)

**Comment by Yivan** [comment]
Thanks @brusch for your answer, it is a perfect solution. No need to make it UI for us.
Maybe this could be added to the documentation page in marketing settings ? So other people wanting to disable it can read how to do it from the documentation.
