### ISSUE TITLE
[Extensions] Populate version of extension based on composer package version

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#1888]
![image](https://user-images.githubusercontent.com/8792145/29918204-e946a9ce-8e44-11e7-9fc5-4295138327d3.png)

is that even possible?

**Comment by dpfaffenbauer** [comment]
Yes, composer.lock stores version strings. But thats only possible if the bundle has been installed using composer, so it wouldn't work for the ecommerce-framework.

**Comment by brusch** [comment]
ecommerce framework uses same versioning as the core ;)
