### ISSUE TITLE
Could not save bricks

### ISSUE THREAD

**Issue by daniel-travix** [pimcore/pimcore#1889]
Hi,

its impossible to save the objectbrick if you are using the class definitions. Without it is possible.

![image](https://user-images.githubusercontent.com/19191046/29920328-500ad84e-8e4d-11e7-9ae4-3af90a21e801.png)

**Comment by weisswurstkanone** [comment]
Hi @dpfaffenbauer, is this related to 
https://github.com/pimcore/pimcore/issues/1584 ?
It seems that createContainerClasses tries to resolve a ID as name.
Best regards,
Josef

**Comment by dpfaffenbauer** [comment]
@weisswurstkanone I'll have a look at it and provide another PR to fix that, ok?

**Comment by weisswurstkanone** [comment]
Perfect, many thanks! 👍

**Comment by dpfaffenbauer** [comment]
@weisswurstkanone seems like on of your changes messed up the JS class

This is your change which reverts changes from my PR: https://github.com/pimcore/pimcore/commit/bcc629ac17e4c23059ac6e1e444acdb22c70d959
https://github.com/pimcore/pimcore/pull/1594/files

I'll create a PR anyway to fix that.

**Comment by weisswurstkanone** [comment]
Yes exactly :-( sorry about that!

**Comment by weisswurstkanone** [comment]
seems to be fine again

**Comment by brusch** [comment]
@weisswurstkanone 
So this can be closed?
