### ISSUE TITLE
Tag and Snippet Manager: disable tags in editmode

### ISSUE THREAD

**Issue by elements-team** [pimcore/pimcore#1893]
# Bug Report
I included a Livechat snippet with the Tag and Snippet Manager. Those are present in the Backend of documents and a customer requested to remove it. 
The Livechat is set to class selector head and end.

Should be disabled in Editmode

**Comment by ckemptner** [comment]
+1 -> I sometimes insert marketing pixels which then mess up the backend (Doubleclick for example)

**Comment by brusch** [comment]
- add an option on tag level to exclude from editmode
- in certain cases it is necessary to embed them also in editmode
