### ISSUE TITLE
Asynchronous queues in Pimcore

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#1895]
# Feature Request
Currently the event system of Pimcore does not support asynchronous events.
There are many use-cases, in which it is helpful for developers, to push asynchronous events into a queue, and process those events later, for instance in a batch job.

+ the queue should make it possible to save various data (for instance as JSON)
+ it could be even possible to assign events to a specific data object in Pimcore.
+ in a later stage, it then could be even possible to visualize events in the Pimcore backend (e.g., related to an object, or in a separate view).

**Comment by dpfaffenbauer** [comment]
I quite like the idea of having this inside Pimcore. I currently do this manually when needed. Thats the reason I created the ProcessManager Plugin (https://github.com/dpfaffenbauer/ProcessManager).

How am I doing this now?
 - 1. Create a TmpStore Record
 - 2. Call a CLI Task which handles the async task
 - 3. Give feedback to ProcessManager to see whats going on

**Comment by brusch** [comment]
Probably a topic for Pimcore 6 and https://symfony.com/doc/current/components/messenger.html

**Comment by brusch** [comment]
I guess https://symfony.com/doc/current/components/messenger.html should be the way to go. 
Visualization could be realized by a bundle.

**Comment by dpfaffenbauer** [comment]
@brusch Exactly, messenger is the way I solved that quite often now.
