### ISSUE TITLE
IPTC Keywords not displayed

### ISSUE THREAD

**Issue by monaBinder** [pimcore/pimcore#1896]

**Comment by brusch** [comment]
php.net/exif is enabled? 
System requirements-check says everything is ok? 
Can you please provide us an example image?

**Comment by monaBinder** [comment]
System is ok, exif enabled.

In case of test1.jpg data is transferred by http://localhost:32772/admin/asset/get-data-by-id/?_dc=1504265193988&id=5313&type=image but not displayed in the iptc (nor exif) tab of the Asset Detail View.
![screen shot 2017-09-01 at 13 27 21](https://user-images.githubusercontent.com/21080166/29968089-5af00176-8f1a-11e7-93cb-59a211ac0895.png)

For tiff files iptc data is not even available.

Test images:
![test1](https://user-images.githubusercontent.com/21080166/29968124-80113984-8f1a-11e7-88dc-6a31d7a6004d.jpg)
