### ISSUE TITLE
Object bricks error while filter an export in object grid

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#190]
I have some object bricks ( Name: MOTClothing , Field name: occasion ) which are linked with object class (Product class - MOTProduct ). There is a export option in object (product) grid. The grid contains object bricks - occasion  also. If we CSV export products it's works. But if I try to filter with object bricks - occasion and CSV export then I will get fatal error like,

Fatal error: Uncaught exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'MOTClothing.occasion' in 'where clause'' in /home/ecomweb1/connect.com/pimcore/pimcore/lib/Zend/Db/Statement/Mysqli.php:77 Stack trace: #0 /home/ecomweb1/connect.com/pimcore/pimcore/lib/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('SELECT object_l...') #1 /home/ecomweb1/connect.com/pimcore/pimcore/lib/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'SELECT object_l...') #2 /home/ecomweb1/connect.com/pimcore/pimcore/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('SELECT object_l...') #3 /home/ecomweb1/connect.com/pimcore/pimcore/lib/Zend/Db/Adapter/Abstract.php(737): Zend_Db_Adapter_Abstract->query('SELECT object_l...', Array) #4 [internal function]: Zend_Db_Adapter_Abstract->fetchAll('SELECT object_l...', Array) #5 /home/ecomweb1/connect.com/pimcore/pimcore/lib/Pimcore/Resource/Wrapper.php(230): call_user_func_arra in /home/ecomweb1/connect.com/pimcore/pimcore/lib/Zend/Db/Statement/Mysqli.php on line 77

I tried with some other object bricks and different server but still i got error. 
Its seems like the filter passing wrong element.  

Other filter and CSV export working fine, only problem with object bricks.

![image](https://cloud.githubusercontent.com/assets/142037/8744491/d4b48fca-2c77-11e5-9b49-75d42483fe68.png)

![image](https://cloud.githubusercontent.com/assets/142037/8744493/d7aa7406-2c77-11e5-8e34-4823fea02acf.png)

![image](https://cloud.githubusercontent.com/assets/142037/8744506/f7d6d3d2-2c77-11e5-976c-9992df6fb1ce.png)

![image](https://cloud.githubusercontent.com/assets/142037/8744508/fb169a3c-2c77-11e5-886e-ef7f3ddaaac4.png)

![image](https://cloud.githubusercontent.com/assets/142037/8744508/fb169a3c-2c77-11e5-886e-ef7f3ddaaac4.png)

![image](https://cloud.githubusercontent.com/assets/142037/8744524/12a4ce8a-2c78-11e5-942e-d8ee0931d5d1.png)

**Comment by ryanwebdev** [comment]
Yeah, I encounter this bug as well after I upgrade my Pimcore from 1.4.9 to 3.1.1
I had a extended discussion in the pimcore google group about this bug. https://groups.google.com/forum/#!topic/pimcore/Z9yBcj2CCMQ

This bug can be reproduce in any official pimocre demo sites. Columns are not able to to filter or sort in the "Search, Edit and Export" views.

Here is the error message I got:

Date: 2015-12-21T18:40:37.934Z
Status: 500 | Internal Server Error
URL: /admin/object/grid-proxy/classId/1/folderId/46
Params:
-> sort: DecorativeHardware~colour
-> dir: ASC
-> language: en

Fatal error:  Uncaught exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Unknown column 'DecorativeHardware~colour' in 'order clause'' in /var/www/ryan-live/pimcore/lib/Zend/Db/Statement/Mysqli.php:77
Stack trace:
#0 /var/www/ryan-live/pimcore/lib/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('SELECT SQL_CALC...')
#1 /var/www/ryan-live/pimcore/lib/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'SELECT SQL_CALC...')
#2 /var/www/ryan-live/pimcore/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('SELECT SQL_CALC...')
#3 /var/www/ryan-live/pimcore/lib/Zend/Db/Adapter/Abstract.php(794): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#4 [internal function]: Zend_Db_Adapter_Abstract->fetchCol(Object(Zend_Db_Select), Array)
#5 /var/www/ryan-live/pimcore/lib/Pimcore/Resource/Wrapper.php(263): call_user_func_array(Array, Array)
#6 /var/www/ryan-live/pimcore/lib/Pimcore/Resource/Wrapper.php(233): Pi in /var/www/ryan-live/pimcore/lib/Zend/Db/Statement/Mysqli.php on line 77

**Comment by fashxp** [comment]
fixed in build 3774
