### ISSUE TITLE
Mime type mp4 is not supported

### ISSUE THREAD

**Issue by elenachoi** [pimcore/pimcore#1900]
File pimcore/lib/Pimcore/Tool/Mime.php is missing mp4 extension which prevents uploads to S3 at least (Pimcore 5).

(1/1) UnexpectedValueExceptionType is not supported
--
in JsonEncode.php (line 43)
at JsonEncode->encode(array('success' => false, 'message' => 'Warning: finfo_file(): Failed identify data 0:invalid mode 00', 'trace' => array(array('file' => '/var/www/html/pimcore/models/Asset.php', 'line' => 679, 'function' => 'detect', 'class' => 'Pimcore\\Tool\\Mime', 'type' => '::', 'args' =>array('s3://pimcore5assets/assets/files/SampleVideo_1280x720_1mb_1.mp4', 'SampleVideo_1280x720_1mb_1.mp4')), array('file' => '/var/www/html/pimcore/models/Asset/Video.php', 'line' => 48, 'function' => 'update', 'class' => 'Pimcore\\Model\\Asset', 'type' => '->', 'args' => array()), array('file' => '/var/www/html/pimcore/models/Asset.php', 'line' => 494, 'function' => 'update', 'class' => 'Pimcore\\Model\\Asset\\Video', 'type' => '->', 'args' => array()), array('file' => '/var/www/html/pimcore/models/Asset.php', 'line' => 359, 'function' => 'save', 'class' => 'Pimcore\\Model\\Asset', 'type' => '->', 'args' => array()), array('file' => '/var/www/html/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/AssetController.php', 'line' => 318, 'function' => 'create', 'class' => 'Pimcore\\Model\\Asset', 'type' => '::', 'args' => array('66',array('filename' => 'SampleVideo_1280x720_1mb_1.mp4', 'userOwner' => '8', 'userModification' => '8', 'stream' => resource))), array('file' => '/var/www/html/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/AssetController.php', 'line' => 206, 'function' => 'addAsset', 'class' => 'Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\AssetController', 'type' => '->', 'args' =>array(object(Request))), array('function' => 'addAssetAction', 'class' => 'Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\AssetController', 'type' => '->', 'args' =>array(object(Request))), array('file' => '/var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php', 'line' => 153, 'function' => 'call_user_func_array', 'args' => array(array(object(AssetController), 'addAssetAction'), array(object(Request)))), array('file' => '/var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php', 'line' => 68, 'function' => 'handleRaw', 'class' => 'Symfony\\Component\\HttpKernel\\HttpKernel', 'type' => '->', 'args' => array(object(Request), 1)), array('file' => '/var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php', 'line' => 171, 'function' => 'handle', 'class' => 'Symfony\\Component\\HttpKernel\\HttpKernel', 'type' => '->', 'args' => array(object(Request), 1, true)), array('file' => '/var/www/html/web/app.php', 'line' => 32, 'function' => 'handle', 'class' => 'Symfony\\Component\\HttpKernel\\Kernel', 'type' => '->', 'args' =>array(object(Request))))), 'json', array('json_encode_options' => 15))in JsonEncoder.php (line 44)

**Comment by brusch** [comment]
Unable to reproduce on our side. Detection also works correctly in our demos (https://demo-basic.pimcore.org/admin/). 

The detection in `\Pimcore\Tool\Mime::detect` uses not only a static file extension mapping but also `finfo_file()` maybe you have an imcomplete mime database on your server environment?

**Comment by brusch** [comment]
Anyway, I've now added `mp4` to the static mapping table - it can't hurt ;-)
