### ISSUE TITLE
paramter seems to be ingored getting an absolute url in generateUrl method

### ISSUE THREAD

**Issue by js-aw** [pimcore/pimcore#1902]
the 3rd parameter $referenceType in Pimcore\Routing\Staticroute\Router::generate is apparently ignored. want to use it with to get a absolute link:

$url = $this->generateUrl('my_test_route', [
    'hello' => 'world'
], UrlGeneratorInterface::ABSOLUTE_URL);

**Comment by maff** [comment]
Implemented in #2019
