### ISSUE TITLE
Error when you save a Role or User with Workspace Permissions with Data Objects

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#1904]
# Bug Report

if you add the Data Objects Permissions in Roles or User Permissions you get the following Error:

Message: Attempted to load class "Object" from namespace "\Pimcore\Model\User\Workspace".
Did you forget a "use" statement for "Pimcore\Model\Object"?
Trace: [
  {
    "function": "updateAction",
    "class": "Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\UserController",
.............

**Comment by weisswurstkanone** [comment]
fixed in build 105

**Comment by camico** [comment]
The same happens when trying to _clone_ a user by right-click, and that user has at least one 'Data Objects' permission set under Workspaces tab.
```
Message: Attempted to load class "Object" from namespace "\Pimcore\Model\User\Workspace".
Did you forget a "use" statement for "Pimcore\Model\Object"?
```
Reproducible on demo-basic.pimcore.org build 124
