### ISSUE TITLE
[PIMCORE5] pass parameter in pimcore_inc

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#1906]
https://github.com/pimcore/pimcore/commit/037dbbe279c24a25ed5fc20f79e2ae14c0d5ba96#diff-771f961e5c33ba7d41934f0543a02683R37

I'm trying to pass some params with the twig `{{ pimcore_inc(doc, {params}) }}` extension but i think they're getting lost during the __invoke method. 

- load snippet via `pimcore_inc(doc, {'additional': 'test'})`
- in the snippet template: {{ dump('additional') }}
- twig error: additional does not exist

**Comment by maff** [comment]
The parameters passed to `inc` are not automatically set on the view, but are added as request attributes instead (for both PHP and Twig templates). If you need those parameters on the view, you need to pass the parameter from your controller (the controller handling the included document) and pass it to its view. According to your example:

```php
public function defaultAction(Request $request)
{
    $this->view->additional = $request->get('additional');
}
```

Now you can use `{{ additional }}` in the template as expected.

**Comment by solverat** [comment]
ah, ok - thanks for your investigation! 👍
