### ISSUE TITLE
Object Search can't search for numbers

### ISSUE THREAD

**Issue by georgkoch** [pimcore/pimcore#1910]
# Bug Report

### Version
Version: 5.0.0-BETA1
Build: 93

### Expected behavior 
When I use the object search within Pimcore I want to be able to search for example the term "1.12.1.1"
The "1.12.1.1" is a value in a "Eingabefeld"

### Actual behavior  
Search delivers no result

![image](https://user-images.githubusercontent.com/20354625/30060571-3f7d3382-9244-11e7-9a92-03baf6e8bd3a.png)

### Steps to reproduce  
Create an input field -> key in a number -> search for the number in the object search
I can also give you a live demo in an actual project.

**Comment by markus-moser** [comment]
"1.12.1.1" as search term should help

**Comment by georgkoch** [comment]
nope - tried this already

**Comment by markus-moser** [comment]
ah this happens because . , and so own are remove from the search_backend_data table

**Comment by fashxp** [comment]
"1.12.1.1" is not a number ;-)

**Comment by georgkoch** [comment]
OK - doesn't even work with 1 ;-)

**Comment by georgkoch** [comment]
@fashxp -> so you won ;-) with 123456 the search works.......

So it seams that there is an issue with the "." "," and to short nummeric strings-> is there a minimum string length?

**Comment by brusch** [comment]
Yes, there's a minimum string length that comes from MySQL/MariaDB and is by default `3`. 
`.` however is a delimiting character, like ` ` and `,` and therefore ignored by the index parser. See also: 
https://dev.mysql.com/doc/refman/5.7/en/fulltext-natural-language.html

> The built-in FULLTEXT parser determines where words start and end by looking for certain delimiter characters; for example,   (space), , (comma), and . (period).
