### ISSUE TITLE
Database cluster setup with read only connections

### ISSUE THREAD

**Issue by gadget60** [pimcore/pimcore#1912]
# Support database cluster setup with read only connections
Pimcore 4 provided a database cluster setup using read only connections. This feature is currently not supported in Pimcore 5, although Doctrine provides a MasterSlaveConnection wrapper: http://www.doctrine-project.org/api/dbal/2.5/class-Doctrine.DBAL.Connections.MasterSlaveConnection.html

Now Pimcore\Db\Connection does not extend (or wrap) this wrapper, on the other hand, many Pimcore classes typehint against Pimcore\Db\Connection. This makes it almost impossible to set up a Doctrine MasterSlaveConnection without major code changes.

**Comment by brusch** [comment]
`Pimcore\Db\Connection` adds quite a lot of additional functionality to `Doctrine\DBAL\Connection` and since `Doctrine\DBAL\Connections\MasterSlaveConnection` extends directly from `Doctrine\DBAL\Connection` and doesn't decorate/wrap it, it is impossible to use `MasterSlaveConnection` directly anyway. 

So the only possible solution would be to create a custom `MasterSlaveConnection` that extends `Pimcore\Db\Connection` and merge the code from `Doctrine\DBAL\Connections\MasterSlaveConnection` into it. 

Currently we don't have this on our roadmap, but maybe you could provide this functionality as an additional composer package and share it with the community ;)

**Comment by gadget60** [comment]
Agree. I'll give it a try. However - at least when it comes to database configuration this is getting messy: Master db config comes from system.php, slave configs from config.yml. Therefore, I would love to see this feature on the roadmap.

**Comment by sebwebdev** [comment]
+1

I agree that this should become part of the roadmap. We require this for AWS Aurora, where you have a classic master/slave setup and need to incorporate two endpoints in order to leverage the round-robin of the slave nodes.

@brusch Maybe I give your suggestion a try in the meantime. :-)

**Comment by brusch** [comment]
Hmmm, I'm just thinking, ... maybe we could try to stuff everything from `Pimcore\Db\Connection` into a trait, so that `Pimcore\Db\Connection` would be shortened to: 

```php
<?php
namespace Pimcore\Db;
class Connection extends \Doctrine\DBAL\Connection
{
    use Helpers;
}
```

Then it would be easy to provide also a `Pimcore\Db\MasterSlaveConnection` with just the same content. 

Maybe you can try that approach - if it works we definitely would accept that PR ;)

**Comment by sebwebdev** [comment]
Sounds good 👍 I will try it as soon as our setup is running.

**Comment by brusch** [comment]
Ok, this isn't as simple as I thought, we have to consider that the master-slave replication is asynchronous, and therefore you could get into massive troubles, mainly because of the cache and race conditions.  
Pimcore uses a tagged cache, items get invalidated immediately as soon as there's a change on them or any other related item. Now when the item gets loaded from a slave (because it wasn't in the cache), which isn't up-to-date with the master (for whatever reason), the system loads outdated data into the cache - the cache again is also used in the backend, so this can lead to data-loss and inconsistencies. 

Another topic is that the `MasterSlaveConnection` is assuming that `executeQuery()` is only used for read operations, which isn't the case at the moment, but that would be an easy one to fix, compared to the issue above.

**Comment by sebwebdev** [comment]
OK, that's a bummer then. AWS Aurora claims that the lag between master and slaves to be "tens of milliseconds". Of course in that scenario you may still experience nasty race-conditions regarding the cache invalidation as you described. It's eventual consistent after all.

Maybe a possibility would be to differentiate between master reads and slave reads. The former should  always occur on object manipulation and read ops in the backend, i.e. when I have to be a 100% sure to get a fresh object. The latter may be exclusive for frontend queries, i.e. when the site is rendered or during REST API calls. But that is just a thought, and leads to other complexities and a lot of responsibility being put on the shoulders of developers. Which may not be feasible as well.

Do you see any problems using Master/Slave, when there is no cache pool enabled and thus no tagging?

**Comment by brusch** [comment]
Regarding master/slave without a cache: well, that would work in theory, but you'll loose a lot of performance by disabling the entire caching of Pimcore - I definitely wouldn't recommend that. 

The crucial question is: does the use-case really require read-only slave connections and is it worth to bring in more complexity because of that. Our experience is that the cache of Pimcore does a real good job in taking load off the database, due to it's approach with tagging and invalidating. But of course it always depends on the use-case ...

**Comment by gadget60** [comment]
@brusch I'm just curious: The master/slave connection was supported in Pimcore4 - and it seems there's also been a tagged cache: https://github.com/pimcore/pimcore/blob/4.6.3/pimcore/lib/Pimcore/Cache/Backend/MysqlTable.php

Why hasn't this been an issue back in the version 4 days...?

**Comment by brusch** [comment]
@gadget60 Well, there's a big difference between having a clustered (multi-master/active-active, eg. Galera) environment or an asynchronous master/slave replication setup. Pimcore 4 had/has support for write only connections, but that doesn't mean that you can use that for asynchronous master/slave setups. 
The reason why there was the possibility of write-only connections in Pimcore 4 was to avoid dead-locks in master/master environments with high i/o, but that is also mentioned in the docs - the only missing part is that this functionality is **NOT** designed to be used for master/slave setups. 
Reference: https://pimcore.com/docs/4.6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Cluster_Setup.html#page_Database-Cluster-with-Write-Only-Connection

**Comment by gadget60** [comment]
@brusch Thank you for pointing that out. There was my misconception, I thought PC4 was built to support Master/Slave replication. 
Anyway: Is there a plan to bring back write-only-Connections for a Galery setup? Because this is what (in my case) I am really looking for...

**Comment by brusch** [comment]
Ok, I've moved now all additional functionalities from Pimcore on the db connection to a trait and made them ready for the master-slave connection (use `executeQuery()` only for read operations): 0ced7fcf58ea95f95e5e9df8db0532dd73872746 

So it should be a bit easier now to use `Doctrine\DBAL\Connections\MasterSlaveConnection` by doing the following: 

Create a project specific db connection: 
```php
<?php

namespace AppBundle\Db;

use Pimcore\Db\PimcoreExtensionsTrait;

class Connection extends \Doctrine\DBAL\Connections\MasterSlaveConnection
{
    use PimcoreExtensionsTrait;
}
```

Override the connection class in config: 
```yaml
doctrine:
    dbal:
        connections:
            default:
                wrapper_class: '\AppBundle\Db\Connection'
```

With that you should be able to use master-slave connections. 

**IMPORTANT NOTICE**
As mentioned already before, ... this should be only used in clustered environments, to minimize the risk of dead-locks, and **NOT** for master/slave setups! 

That's all we could do for now.

**Comment by puecher** [comment]
When extending from \Doctrine\DBAL\Connections\MasterSlaveConnection I get the following error:

```
FatalThrowableError

Type error: Argument 2 passed to Pimcore\Bundle\CoreBundle\EventListener\ResponseExceptionListener::__construct() must be an instance of Pimcore\Db\Connection, instance of AppBundle\Db\Connection given
```

Using

```php
<?php

namespace AppBundle\Db;

use Doctrine\DBAL\Connection as DbalConnection;
use Doctrine\DBAL\Driver;
use Doctrine\DBAL\Driver\Connection as DriverConnection;
use Doctrine\DBAL\Configuration;
use Doctrine\Common\EventManager;
use Doctrine\DBAL\Event\ConnectionEventArgs;
use Doctrine\DBAL\Events;
use function array_rand;
use function count;
use function func_get_args;

class Connection extends \Pimcore\Db\Connection // \Doctrine\DBAL\Connections\MasterSlaveConnection :'(
{
    /**
     * Master and slave connection (one of the randomly picked slaves).
     *
     * @var DriverConnection[]|null[]
     */
    protected $connections = ['master' => null, 'slave' => null];

    /**
     * You can keep the slave connection and then switch back to it
     * during the request if you know what you are doing.
     *
     * @var bool
     */
    protected $keepSlave = false;

    /**
     * Creates Master Slave Connection.
     *
     * @param array                              $params
     * @param \Doctrine\DBAL\Driver              $driver
     * @param \Doctrine\DBAL\Configuration|null  $config
     * @param \Doctrine\Common\EventManager|null $eventManager
     *
     * @throws \InvalidArgumentException
     */
    public function __construct(array $params, Driver $driver, Configuration $config = null, EventManager $eventManager = null)
    {
        if (! isset($params['slaves'], $params['master'])) {
            throw new \InvalidArgumentException('master or slaves configuration missing');
        }
        if (count($params['slaves']) == 0) {
            throw new \InvalidArgumentException('You have to configure at least one slaves.');
        }

        $params['master']['driver'] = $params['driver'];
        foreach ($params['slaves'] as $slaveKey => $slave) {
            $params['slaves'][$slaveKey]['driver'] = $params['driver'];
        }

        $this->keepSlave = (bool) ($params['keepSlave'] ?? false);

        parent::__construct($params, $driver, $config, $eventManager);
    }

    /**
     * Checks if the connection is currently towards the master or not.
     *
     * @return bool
     */
    public function isConnectedToMaster()
    {
        return $this->_conn !== null && $this->_conn === $this->connections['master'];
    }

    /**
     * {@inheritDoc}
     */
    public function connect($connectionName = null)
    {
        $requestedConnectionChange = ($connectionName !== null);
        $connectionName            = $connectionName ?: 'slave';

        if ($connectionName !== 'slave' && $connectionName !== 'master') {
            throw new \InvalidArgumentException("Invalid option to connect(), only master or slave allowed.");
        }

        // If we have a connection open, and this is not an explicit connection
        // change request, then abort right here, because we are already done.
        // This prevents writes to the slave in case of "keepSlave" option enabled.
        if (isset($this->_conn) && $this->_conn && !$requestedConnectionChange) {
            return false;
        }

        $forceMasterAsSlave = false;

        if ($this->getTransactionNestingLevel() > 0) {
            $connectionName     = 'master';
            $forceMasterAsSlave = true;
        }

        if (isset($this->connections[$connectionName]) && $this->connections[$connectionName]) {
            $this->_conn = $this->connections[$connectionName];

            if ($forceMasterAsSlave && ! $this->keepSlave) {
                $this->connections['slave'] = $this->_conn;
            }

            return false;
        }

        if ($connectionName === 'master') {
            $this->connections['master'] = $this->_conn = $this->connectTo($connectionName);

            // Set slave connection to master to avoid invalid reads
            if ( ! $this->keepSlave) {
                $this->connections['slave'] = $this->connections['master'];
            }
        } else {
            $this->connections['slave'] = $this->_conn = $this->connectTo($connectionName);
        }

        if ($this->_eventManager->hasListeners(Events::postConnect)) {
            $eventArgs = new ConnectionEventArgs($this);
            $this->_eventManager->dispatchEvent(Events::postConnect, $eventArgs);
        }

        return true;
    }

    /**
     * Connects to a specific connection.
     *
     * @param string $connectionName
     *
     * @return DriverConnection
     */
    protected function connectTo($connectionName)
    {
        $params = $this->getParams();

        $driverOptions = $params['driverOptions'] ?? [];

        $connectionParams = $this->chooseConnectionConfiguration($connectionName, $params);

        $user = $connectionParams['user'] ?? null;
        $password = $connectionParams['password'] ?? null;

        return $this->_driver->connect($connectionParams, $user, $password, $driverOptions);
    }

    /**
     * @param string $connectionName
     * @param array  $params
     *
     * @return mixed
     */
    protected function chooseConnectionConfiguration($connectionName, $params)
    {
        if ($connectionName === 'master') {
            return $params['master'];
        }

        $config = $params['slaves'][array_rand($params['slaves'])];

        if ( ! isset($config['charset']) && isset($params['master']['charset'])) {
            $config['charset'] = $params['master']['charset'];
        }

        return $config;
    }

    /**
     * {@inheritDoc}
     */
    public function executeUpdate($query, array $params = [], array $types = [])
    {
        $this->connect('master');

        return parent::executeUpdate($query, $params, $types);
    }

    /**
     * {@inheritDoc}
     */
    public function beginTransaction()
    {
        $this->connect('master');

        parent::beginTransaction();
    }

    /**
     * {@inheritDoc}
     */
    public function commit()
    {
        $this->connect('master');

        parent::commit();
    }

    /**
     * {@inheritDoc}
     */
    public function rollBack()
    {
        $this->connect('master');

        return parent::rollBack();
    }

    /**
     * {@inheritDoc}
     */
    public function delete($tableName, array $identifier, array $types = [])
    {
        $this->connect('master');

        return parent::delete($tableName, $identifier, $types);
    }

    /**
     * {@inheritDoc}
     */
    public function close()
    {
        unset($this->connections['master'], $this->connections['slave']);

        parent::close();

        $this->_conn = null;
        $this->connections = ['master' => null, 'slave' => null];
    }

    /**
     * {@inheritDoc}
     */
    public function update($tableName, array $data, array $identifier, array $types = [])
    {
        $this->connect('master');

        return parent::update($tableName, $data, $identifier, $types);
    }

    /**
     * {@inheritDoc}
     */
    public function insert($tableName, array $data, array $types = [])
    {
        $this->connect('master');

        return parent::insert($tableName, $data, $types);
    }

    /**
     * {@inheritDoc}
     */
    public function exec($statement)
    {
        $this->connect('master');

        return parent::exec($statement);
    }

    /**
     * {@inheritDoc}
     */
    public function createSavepoint($savepoint)
    {
        $this->connect('master');

        parent::createSavepoint($savepoint);
    }

    /**
     * {@inheritDoc}
     */
    public function releaseSavepoint($savepoint)
    {
        $this->connect('master');

        parent::releaseSavepoint($savepoint);
    }

    /**
     * {@inheritDoc}
     */
    public function rollbackSavepoint($savepoint)
    {
        $this->connect('master');

        parent::rollbackSavepoint($savepoint);
    }

    /**
     * {@inheritDoc}
     */
    public function query(...$params)
    {
        $this->connect('master');

        return parent::query(...$params);
    }

    /**
     * {@inheritDoc}
     */
    public function prepare($statement)
    {
        $this->connect('master');

        return parent::prepare($statement);
    }
}
```

it seems to work.

**Comment by brusch** [comment]
Proposed solution: 
Introduce `Pimcore\Db\ConnectionInterface` which extends from `\Doctrine\DBAL\Driver\Connection` and additionally defines all methods defined in `\Pimcore\Db\PimcoreExtensionsTrait` and `\Doctrine\DBAL\Connection`. Then replace all type-hints from `\Pimcore\Db\Connection` to `Pimcore\Db\ConnectionInterface` and additionally create an service alias for `Pimcore\Db\ConnectionInterface` 

Then using the `MasterSlaveConnection` should be as easy as described above: 

```php
<?php

namespace AppBundle\Db;

use Pimcore\Db\PimcoreExtensionsTrait;
use Pimcore\Db\ConnectionInterface;

class Connection extends \Doctrine\DBAL\Connections\MasterSlaveConnection implements ConnectionInterface
{
    use PimcoreExtensionsTrait;
}
```

Override the connection class in config: 
```yaml
doctrine:
    dbal:
        connections:
            default:
                wrapper_class: '\AppBundle\Db\Connection'
```

**Comment by brusch** [comment]
Here you can find the latest documentation: https://pimcore.com/docs/5.x/Development_Documentation/Best_Practice/Master-Slave_Database_Connection.html

**Comment by sknuell** [comment]
Nice, especially the first IMPORTANT note is helpful. So that users will not be confused and use this in a master/slave setup.

**Comment by Forestsoft-de** [comment]
Hey I have trouble with master/slave database setup

PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Pimcore\Maintenance\Tasks\LogErrorCleanupTask::__construct() must be an instance of Pimcore\Db\Connection, instance of AppBundle\Db\Connection given, called in /var/www/pimcore/var/cache/prod/ContainerVLBhaOj/getExecutorService.php on line 18 in /var/www/pimcore/vendor/pimcore/pimcore/lib/Maintenance/Tasks/LogErrorCleanupTask.php:30

The LogErrorCleanupTask should use the Interface :)

**Comment by Debanshu123** [comment]
I am also facing the same issue any fix suggested for the same.

**Comment by brusch** [comment]
@Debanshu123 @Forestsoft-de Would be nice if someone facing the issue can try to provide a fix. 
Thanks a lot!
