### ISSUE TITLE
4.6.1 - Backend Classes Localized Fields unable to add fields

### ISSUE THREAD

**Issue by fffab** [pimcore/pimcore#1914]
# Bug Report
  
### Expected behavior 
In pimcore 4.6.0 the normal behavior was ta add a localized field in classes and fields attached using context menu on tree.
  
### Actual behavior  
in 4.6.1 this is broken (also on  https://demo.pimcore.org/admin/) triger a Js error
TypeError: initData is null   script-proxy:51078:9
initData.name = "localizedfields";

what i alse sawed is that in 4.6.0 Localized Fields added are called "localizedfields" (name not changeable) in 4.6.1 they are called "Localized Fields"
  
could'nt find a way out / workaround yet.
would be great if you can investigate / fix / help

Regards,

**Comment by brusch** [comment]
see 301c7d25db995b0ded77a30af1386ad1715614fa

**Comment by fffab** [comment]
great. thanks !
