### ISSUE TITLE
[Pimcore5] TemplatingEngineAwareHelperPass breaks when using JMS Serializer

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#1918]
Actually, it breaks when using Parameters as class-name.

```
(1/1) ReflectionExceptionClass %jms_serializer.templating.helper.class% does not exist
--
in TemplatingEngineAwareHelperPass.php (line 35)
```

adding class_exists would solve the problem, but I am not sure if thats the correct behaviour then, since jms_serializer.templating.helper.class should resolve to a class name.

**Comment by maff** [comment]
Good catch, thx!
