### ISSUE TITLE
Object grid view broken for non admin users?

### ISSUE THREAD

**Issue by camico** [pimcore/pimcore#1919]
# Bug Report
I think there is an issue (in recent 5.0.0-builds?) with object grid views.
It seems that for all _non-admin users_ (set up for example like shown in #270 by zieglerh), no columns and thus no objects at all are shown in any object grid view by default.

![column-configuration](https://user-images.githubusercontent.com/614571/30123662-0ba73b8a-9333-11e7-8428-cd4d0acb3518.jpg)

This is reproducible on https://demo-basic.pimcore.org.

I already traced it back into DataObjectHelperController.php -> gridGetColumnConfigAction
I'm landing in the else case here:
```
if (!$fields && $class) {
    $fields = $class->getFieldDefinitions();
} else {
    return $this->json([
        'availableFields' => [],
    ]);
}
```

### Expected behavior 
By default, to see all fields as columns that have a checkmark 'Visible in Grid View' in the class configuration.

### Actual behavior  
- No columns visible
- Column Configuration -> Reset to default doesn't change anything
- When adding columns manually in the column configuration, they will appear - however, the configuration cannot be saved (with the save button) - after a refresh, the columns are lost again
- When clicking on 'just direct child objects', one column will appear that shows a checkbox for each object

**Comment by weisswurstkanone** [comment]
build 106
