### ISSUE TITLE
Class definition LOST when renaming a class into an already existing class

### ISSUE THREAD

**Issue by camico** [pimcore/pimcore#1922]
# Bug Report
Given classes A and B exist. 
Try to rename A into B.

### Expected behavior 
Maybe to see a warning, and it should not be allowed to rename A into B.

### Actual behavior  
Class A will be completely lost (defintion_A.php as well as DataObject/A.php).
'Reload Definition' or try to save it again with another name won't bring it back.
Moreover it seems the whole Classes tab is broken after reopening and won't show anything.

**Comment by weisswurstkanone** [comment]
build 106
