### ISSUE TITLE
PHP-API to restrict Object Listings by linked objects

### ISSUE THREAD

**Issue by camico** [pimcore/pimcore#1923]
# Feature Request
It seems there is no "clean" API method to restrict Object Listings by linked objects (be it objects relations, hrefs, multi-hrefs).

While it is possible to achieve that restriction using the setCondition method of \Pimcore\Model\DataObject\Listing and then "manually" joining over the correct object_relations_xxx and object_store_xxx tables, it would be convenient to have something like, e.g.:
```php
User::getByCustomer($customer)
```
(where Customer is a user-defined class).
Similar to the existing API for "flat" data fields:
```php
User::getByName($name)
```
Or alternatively it could look like this:
```php
$listing->setCondition("customer = :customer", ["customer" => $customer])
```

**Comment by dpfaffenbauer** [comment]
you can use use

```
//href
$listing->setCondition("customer__id = :customer", ["customer" => $customer->getId()])

//multihref, fells kinda messy, but works really good, though
$listing->setCondition('customer__id LIKE '%,'.$customer->getId().',%') //not sure if works with named parameters
```

**Comment by camico** [comment]
Still it seems it's not possible for object relations, have you decided to not implement this feature?
Actually the method a la "User::getByCustomer" is there, but when trying to execute it, it gives you:

 `Static getter ... is not allowed for fieldtype 'objects', it's only allowed for the following fieldtypes: input,numeric,checkbox,country,date,datetime,image,language,multihref,multiselect,select,slider,time,user,email,firstname,lastname,localizedfields`
