### ISSUE TITLE
Pimcore 5, small IDE errors

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1926]
Netbeans IDE (last version) reports some code errors, maybe they could be corrected so source code is more clean.
Those are:

\install-profiles\demo-basic\app\Resources\views\Newsletter\standardMail.html.php, line 182:
`.body .column td.one, { width: 8.333333% !important; }`
shoud be replaced by:
`.body .column td.one { width: 8.333333% !important; }`

\app\Resources\views\Newsletter\standardMail.html.php, line 182:
`.body .column td.one, { width: 8.333333% !important; }`
shoud be replaced by:
`.body .column td.one { width: 8.333333% !important; }`

This one come maybe from bootstrap so could maybe not be patched...
\pimcore\lib\Pimcore\Bundle\EcommerceFrameworkBundle\Resources\public\vendor\bootstrap\css\bootstrap-theme.css, line 53:
`filter: progid:DXImageTransform.Microsoft.gradient(s#artColorstr='#ffffffff', endColorstr='#ffe0e0e0', GradientType=0);`
s#artColorstr seems to have a typo problem here

Some other errors come from /vendor, but we cannot do something for it ; )

Thanks.

**Comment by maff** [comment]
Thanks for reporting. I fixed the first one (the standardMail.html.php you referenced twice is the same file as the second one is the copy created when installing the profile). The bootstrap file should be left untouched to ensure we can upgrade without having to backport changes.
