### ISSUE TITLE
[Pimcore 5] Search and Replace Assignments  functionality is not working with Multi-Href with metadata

### ISSUE THREAD

**Issue by KailaJayapalreddy** [pimcore/pimcore#1930]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [Y] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [Y] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [Y] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [Y] There's no existing ticket for the same issue
- [x] Remove unused sections from below and this bullet points

### Expected behavior 

Source object should be replaced with destination object in Search and Replace functionality. 

### Actual behavior  

Its working with all the input fields and relations but the problem with Multi-Href with metadata relation.

I am getting following exception when i use Multi-Href with metadata relation.

Server threw exception - could not perform action. Please reload the admin interface and try again.

Timestamp: Fri Sep 08 2017 17:54:15 GMT+0530 (IST)
Status: 500 | Internal Server Error
URL: /admin/element/replace-assignments
Params:
-> type: object

Fatal error:  Uncaught Exception: Requested data object not available in /home/pimcore_demo/www/pimcore/models/Object/Data/ElementMetadata.php:76
Stack trace:
#0 /home/pimcore_demo/www/pimcore/models/Object/ClassDefinition/Data/MultihrefMetadata.php(751): Pimcore\Model\Object\Data\ElementMetadata->__call('getObject', Array)
#1 /home/pimcore_demo/www/pimcore/models/Object/Service.php(920): Pimcore\Model\Object\ClassDefinition\Data\MultihrefMetadata->rewriteIds(Object(Pimcore\Model\Object\Item), Array)
#2 /home/pimcore_demo/www/pimcore/modules/admin/controllers/ElementController.php(281): Pimcore\Model\Object\Service::rewriteIds(Object(Pimcore\Model\Object\Item), Array)
#3 /home/pimcore_demo/www/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Admin_ElementController->replaceAssignmentsAction()
#4 /home/pimcore_demo/www/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('replaceAssignme...')
#5 /home/pimcore_demo/www/vendor/ze in /home/pimcore_demo/www/pimcore/models/Object/Data/ElementMetadata.php on line 76

### Steps to reproduce  

1) Create two classes with Class1 and Class2.
2) Class1 should contain multiple filed types such as input, number, relations and it must include at least one Multi-Href with metadata relation (this should allow multiple classes) and objects with metadata ( this should allow Class1 ).
3) For Class2 add few attributes.
3) Now Create 3 objects for the Class1 which we created in Step 1 with following names ( object1, object2, object3  ). Similar way create one object for Class2 i.e class2object1.
4) Now open object1,  Add object2 to object1 in objects with metadata relation. And Add class2object1 to object1 in multi-href with metadata and save it.
5) Now open Pimcore Search and Replace Assignments and for the source Select object2 and search for dependencies, select object1 from the list of dependencies.
6) choose object3 as the replace( or destination).
7) Click on the Replace assignments in selected items.
8) following exception will raise

Server threw exception - could not perform action. Please reload the admin interface and try again.

Timestamp: Fri Sep 08 2017 17:54:15 GMT+0530 (IST)
Status: 500 | Internal Server Error
URL: /admin/element/replace-assignments
Params:
-> type: object

Fatal error:  Uncaught Exception: Requested data object not available in /home/pimcore_demo/www/pimcore/models/Object/Data/ElementMetadata.php:76
Stack trace:
#0 /home/pimcore_demo/www/pimcore/models/Object/ClassDefinition/Data/MultihrefMetadata.php(751): Pimcore\Model\Object\Data\ElementMetadata->__call('getObject', Array)
#1 /home/pimcore_demo/www/pimcore/models/Object/Service.php(920): Pimcore\Model\Object\ClassDefinition\Data\MultihrefMetadata->rewriteIds(Object(Pimcore\Model\Object\Item), Array)
#2 /home/pimcore_demo/www/pimcore/modules/admin/controllers/ElementController.php(281): Pimcore\Model\Object\Service::rewriteIds(Object(Pimcore\Model\Object\Item), Array)
#3 /home/pimcore_demo/www/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Admin_ElementController->replaceAssignmentsAction()
#4 /home/pimcore_demo/www/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('replaceAssignme...')
#5 /home/pimcore_demo/www/vendor/ze in /home/pimcore_demo/www/pimcore/models/Object/Data/ElementMetadata.php on line 76

## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [Y] There is no existing issue regarding the same topic

**Comment by weisswurstkanone** [comment]
build 106
