### ISSUE TITLE
Install Pimcore5: check requirements fatal error

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1934]
In the process of installing Pimcore 5, on the install process, using the "check requirement" button display a fatal error at the bottom of the popin, please see:

![pim5-install-error](https://user-images.githubusercontent.com/9025839/30250220-c2e97d98-964a-11e7-81bd-381f367a84c8.png)

It seems it try to connect as root, why ?

Config provided is this one (user and bdd have been created and we checked by connection on phpMyAdmin, credential are working fine with all privileges for this user):

![install-config](https://user-images.githubusercontent.com/9025839/30250254-5c41c45a-964b-11e7-8471-27f23892f100.png)

**Comment by Yivan** [comment]
Note, this is the last Pimcore5 build:
Version: 5.0.0-BETA1
Build: 105

**Comment by maff** [comment]
Fixed in #1953
