### ISSUE TITLE
Pimcore 5 install: setting environment can break install

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1935]
If the environment is set before installation (https://www.pimcore.org/docs/5.0.0/Deployment/Multi_Environment.html), it break the installation process.

How to reproduce:

For instance, we set a custom env in virtual host:
`SetEnv PIMCORE_ENVIRONMENT staging`

Calling `/install.php`, it will output:

```
Fatal error: Uncaught Symfony\Component\Config\Exception\FileLocatorFileNotFoundException: The file "/.../app/config/config_staging.yml" does not exist. in /.../vendor/symfony/symfony/src/Symfony/Component/Config/FileLocator.php:46

Stack trace:
#0 /.../vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Config/FileLocator.php(54): Symfony\Component\Config\FileLocator->locate('/...', NULL, true)
#1 /.../vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(107): Symfony\Component\HttpKernel\Config\FileLocator->locate('/...')
#2 /.../vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(45): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/...', NULL)
#3 /.../pimcore/lib/Pimcore/Kernel. in /.../vendor/symfony/symfony/src/Symfony/Component/Config/FileLocator.php on line 46
```
Maybe, the documentation should be updated saying environment must be set AFTER install.
Or better, installation must be environment agnostic (but some people want maybe different install settings depending environment),
Or more simply don't send errors if the `config_{environment}.yml` is not found, and fallback to the `config.yml` file.

---

Same errors is produced on already installed Pimcore, if we add the environment after install.
It should not produce errors (and maybe fallback to the default `config.yml` config file like the system.php config files do it ?).

The documentation don't cover this `config_{environment}.yml` file, its purpose and how it works (at least should refer to the symfony documentation)
 (https://www.pimcore.org/docs/5.0.0/Deployment/Multi_Environment.html)

Thanks.

**Comment by Yivan** [comment]
Maybe it could be added in the documentation in this page too (https://www.pimcore.org/docs/5.0.0/Deployment/Multi_Environment.html), that if database credential are changed (by editing the system_.{environment}.php file), change aren't effective because of the symfony caching. Cache must be cleared. As in some case we cannot have no more access to Pimcore GUI (as DB credential changed) to clear the cache, it must be done by clearing the cache manually.
Maybe the process could be explained in the documentaiton, so user aren't stuck ; )
(i think it is `./bin/console cache:clear` maybe which should be run).

I think a transparent clearing cache could be implemented in the code... for instance if credential are not good, clear the cache and try only one time again to connect to bdd... so user don't have to fight against the system ; ))

**Comment by brusch** [comment]
Hmm, I don't think we can or should catch every possible misconfiguration.
The same happens to a normal Symfony application, if you're referring to a non existing config file, and imho this is the correct behavior.

But a short hint in the docs can't hurt, we're happy to merge a corresponding PR for that :)
