### ISSUE TITLE
[Pimcore5] [Idea] new DataObject Field "parent"

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#1944]
This is just an idea which could help making parent-children relations via Object-Tree easier.

A lot of people adding parent-child relations in DataObjects directly using a href for the Parent, which in most cases is the parent within the DataObject-Tree. A new field, which sets this relation automatically would make UX and DX friendlier by automatically adding this relation with a new DataObject Field Type/Tag called "parent".

This field automatically sets the parent-child relation for a selected class/multiple classes when the object is saved.

Example:

Category->Category relation, when adding this field-type, the child-category automatically gets the parent-category set and I can filter in a list for parentCategory__id=?

What do you think?

**Comment by fashxp** [comment]
why not go for the parent relation of Pimcore (o_parentId) ?

**Comment by dpfaffenbauer** [comment]
cause of multiple reasons:
 - can't restrict to certain classes
 - can't sql filter for objects with no parent (first-level)
 - can't sql filter for objects with parent

**Comment by fashxp** [comment]
ad 1) Good point, but then you would have to restrict moving elements around in the tree. So just adding a new data type would not be sufficient. 
ad 2) There is always a parent, filtering for first level would be 'o_parentId = 1' - wouldn't it? 
ad 3) Filtering for objects with 'o_parentId != 1' ? 

Hmm, maybe we are missing something there. But we still understand the benefit of an additional field.

**Comment by dpfaffenbauer** [comment]
For example, you got Product Categories in folder '/categories', how would be able to filter all Categories without a parent, eg. first-level? You would need to know which ID /categories is to be able to do that, which requires a second query to get that.

CoreShop solves this issue currently using an pre-save event to set the category: https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/ProductBundle/EventListener/CategoryPersistEventListener.php#L22, therefore I am able to do queries like: https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/ProductBundle/Pimcore/Repository/CategoryRepository.php

With this solution, I am not restricted to have my categories sitting in a certain directory. they can be in /shop1/category and /shop2/category and the solution always works.

My proposal is to do exactly that with a new field-type.

**Comment by fashxp** [comment]
but you will always need an event listener who decides if a parent should be assigned or not...

**Comment by dpfaffenbauer** [comment]
in my case: yes

but, that should be possible using a object-tag as well, shouldn't it?

**Comment by fashxp** [comment]
hmm, what do you mean with object-tag? :-)

**Comment by dpfaffenbauer** [comment]
Editable field inside dataobjects, like input, numeric and href ;)

**Comment by fashxp** [comment]
ok, then my feeling was right ;-). 
but still, something has to decide, if and what parent should be assigned. and that will be implementation dependent. at least I can think of a few constellations where this behavior has to be be different. 

and thinking about that, I'm not sure, if a bundle would not be a better place for such a datatype? we will discuss about internally.

**Comment by dpfaffenbauer** [comment]
I would make it this way: a setting like in href which parents class names are allowed and assign the direct parent (one level up) if the class is in the selection. Hmm, maybe even write the class name into the table for queries on a specific parent type?

**Comment by brusch** [comment]
Can (and should) be solved by a custom data-type - not a core topic as of now.
