### ISSUE TITLE
Installation Pimcore5 problem

### ISSUE THREAD

**Issue by RolandoPer** [pimcore/pimcore#1945]
**Although my configuration is correct, when I press the "check requirement" button I get:**
Ooops ... something went wrong
Please check your database configuration values and your log files.

**When trying the installation I get the message:**
ERROR(s) (please see var/installer/logs for details):
syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)

**This is the log (var/installer/logs/prod.log):**
`
app.ERROR: ParseError: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /...../vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:72 
Stack trace: #0 /...../vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile(......')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Doctrine\\Common...')
#2 [internal function]: spl_autoload_call('Doctrine\\Common...') 
#3 /......./vendor/doctrine/doctrine-bundle/DependencyInjection/Configuration.php(664): ReflectionClass->__construct('Doctrine\\Common...') 
#4 /......./vendor/doctrine/doctrine-bundle/DependencyInjection/Configuration.php(288): Doctrine\Bundle\DoctrineBundle\DependencyInjection\Configuration->getAutoGenerateModes() 
#5 /......./vendor/doctrine/doctrine-bundle/DependencyInjection/Configuration.php(52): Doctrine\Bundle\DoctrineBundle\DependencyInjection\Configuration->addOrmSection(Object(Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition)) 
#6 /......./vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Processor.php(50): Doctrine\Bundle\DoctrineBundle\DependencyInjection\Configuration->getConfigTreeBuilder() 
#7 /......./vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Extension/Extension.php(96): Symfony\Component\Config\Definition\Processor->processConfiguration(Object(Doctrine\Bundle\DoctrineBundle\DependencyInjection\Configuration), Array) 
#8 /......./vendor/doctrine/doctrine-bundle/DependencyInjection/DoctrineExtension.php(71): Symfony\Component\DependencyInjection\Extension\Extension->processConfiguration(Object(Doctrine\Bundle\DoctrineBundle\DependencyInjection\Configuration), Array) 
#9 /......./vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(66): Doctrine\Bundle\DoctrineBundle\DependencyInjection\DoctrineExtension->load(Array, Object(Symfony\Component\DependencyInjection\ContainerBuilder)) 
#10 /......./vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) 
#11 /......./vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(143): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) 
#12 /......./vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(746): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) 
#13 /......./vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(577): Symfony\Component\DependencyInjection\ContainerBuilder->compile() 
#14 /......./pimcore/lib/Pimcore/Kernel.php(116): Symfony\Component\HttpKernel\Kernel->initializeContainer() 
#15 /......./pimcore/lib/Pimcore/Install/Installer.php(226): Pimcore\Kernel->boot() 
#16 /......./pimcore/lib/Pimcore/Install/Installer.php(165): Pimcore\Install\Installer->runInstall(Object(Pimcore\Install\Profile\Profile), Array, Array) 
#17 /......./pimcore/lib/Pimcore/Install/Controller/InstallController.php(45): Pimcore\Install\Installer->install(Array) 
#18 [internal function]: Pimcore\Install\Controller\InstallController->installAction(Object(Symfony\Component\HttpFoundation\Request), Object(Pimcore\Install\Installer)) #19 /......./vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(153): call_user_func_array(Array, Array) 
#20 /......./vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 
#21 /......./vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(171): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#22 /......./web/install.php(44): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #23 {main} [] []
`

Please, any suggestions?

I updated to php 7.1 and am working with mysql 5.7
Obviously "/......./" is the path of the application. Thanks in advance.

**Comment by dpfaffenbauer** [comment]
error comes from here: https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php#L72.

this is a new feature introduced in PHP 7.1, are you sure your webserver is using PHP7.1 to run Pimcore? Please try running phpinfo() and see what PHP Version is actually used.

**Comment by brusch** [comment]
@maff seems to be related to #1911

**Comment by maff** [comment]
@RolandoPer could you run `composer update` on the command line and post its output? Does that fix the error?

**Comment by zhartaunik** [comment]
**Solution: Use PHP 7.1**

I faced with the same issue. It happened because you have doctrine/common latest version (probably 2.8.0.). If you have a look at 

vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:72

you may notice that it's using scopes for constants (private const) which is possible in php 7.1 and not possible in php 7.0

**Comment by maff** [comment]
Note: as we support PHP 7.0 in Pimcore, we updated our dependencies to use Doctrine versions compatible with 7.0: https://github.com/pimcore/pimcore/pull/1948

@RolandoPer does the latest build fix your problem?

**Comment by RolandoPer** [comment]
Hi.
I ran the command `php -v` in the terminal, obtaining:
PHP 7.1.9-1

However when doing a phpinfo(), I got:
PHP Version 7.0.17-1

So I proceeded to activate php7.1.
`$ a2dismod php7.0`
`$ a2enmod php7.1`
`$ service apache2 restart`

With this I managed to install pimcore5 built 106.

After that I had problems installing an extension, so I ran `composer update`, successfully. Now I have pimcore5 built 108 and I can install the extension.

Thanks for your quick response, friends.

**Comment by dpfaffenbauer** [comment]
Since Pimcore 5 hasn't been released yet, all Bundles/Plugins try to keep with current development, therefore I suggest you to keep up with Pimcore Builds as well.

**Comment by maff** [comment]
@RolandoPer thanks for the feedback. Pimcore should work fine on 7.0, the problem in your case were composer dependencies which were installed for 7.1 from the zip file (should be fixed with #1948). However, using 7.1 directly is definitely the better solution for this problem :)
