### ISSUE TITLE
[CLI BundleInstaller] - throws error trying installing already installed bundle

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#1949]
Hi,

pimcore:bundle:install throws error on trying to install already installed bundle. Is this really necessary? Can't it just say bundle already installed?

```
 [ERROR] Bundle *Bundle can not be installed
```

**Comment by maff** [comment]
It's up to the bundle installer to determine if it can be installed, the only prerequisites are that the bundle is enabled and has an installer: https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Extension/Bundle/PimcoreBundleManager.php#L512

If the installer returns false, an error is the right thing to return as the command "install" couldn't be executed. There is, however, a `fail-without-error` option for the bundle commands which prints a warning message and exits with a 0 exit code if given:

```bash
$ bin/console pimcore:bundle:install PimcoreEcommerceFrameworkBundle
[ERROR] Bundle PimcoreEcommerceFrameworkBundle can not be installed

$ echo $?
1

$ bin/console pimcore:bundle:install PimcoreEcommerceFrameworkBundle --fail-without-error
[WARNING] Bundle PimcoreEcommerceFrameworkBundle can not be installed

$ echo $?
0
```

A nice to have would be to allow the installer to add information about its status (e.g. *why* the bundle can't be installed) to the CLI output and extension manager. There's already the output writer in place, but we still need to wire this into the UI and CLI output.

**Comment by dpfaffenbauer** [comment]
alright, happy with that :) 👍
