### ISSUE TITLE
Dropdown/Select in MultiHref Advanced custom column not properly selectable 

### ISSUE THREAD

**Issue by michaelclaesson** [pimcore/pimcore#1950]
# Bug Report
  
### Expected behavior 
You want to be able to select the field in your dropdown by clicking it and selecting the option of choice. This works in Objects with metadata with similar custom column, but not here in MultiHref Advanced. 
  
### Actual behavior 
It seems like the object gets out of focus immediately after you've clicked it. Perhaps two handlers acting on the same click? You can make it work by focusing the select and searching for the value or using arrow down on your keypad to bring up the values.

https://www.youtube.com/watch?v=6U-_5V1ls8E
  
### Steps to reproduce  
Create a MultiHref Advanced relation with a custom column with select value. Add at least two values and try to select them by clicking on the dropdown menu and select a value.

**Comment by weisswurstkanone** [comment]
@fashxp , is this somehow related to this commit?
https://github.com/pimcore/pimcore/commit/3128d138a019526f93e9833a226fdb49f4776375

**Comment by fashxp** [comment]
could be. yes.

**Comment by weisswurstkanone** [comment]
build 122
