### ISSUE TITLE
[Newsletter] Consider loading AddressSourceAdapter from Container

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#1952]
Currently Pimcore still loads AddressSourceAdapter from Namespace ```\\Pimcore\\Document\\Newsletter\\AddressSourceAdapter\\```. This should be done using the container.

https://github.com/pimcore/pimcore/blob/1da1bd126caca24cf12e696889aea7da0055ba4c/pimcore/lib/Pimcore/Bundle/CoreBundle/Command/InternalNewsletterDocumentSendCommand.php#L66

If you wish, I could create a PR for that, just wanted to discuss this with you before.

**Comment by fashxp** [comment]
👍 for that one. Maybe similar to https://github.com/pimcore/advanced-object-search/blob/master/src/Service.php#L85 ? 

Could you provide a PR and also add a note here https://github.com/pimcore/pimcore/blob/master/doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/02_V4_to_V5.md? 

Thank you very much...

**Comment by fashxp** [comment]
related to https://github.com/pimcore/pimcore/issues/1397

**Comment by fashxp** [comment]
related to https://github.com/pimcore/pimcore/issues/1399

**Comment by dpfaffenbauer** [comment]
#1399 can be done the same way actually. but should be in a separate PR.

**Comment by fashxp** [comment]
yes, bit it is still related :-)

**Comment by dpfaffenbauer** [comment]
solved :)

I'll create a PR for #1399 as well.

**Comment by fashxp** [comment]
Thx!!
