### ISSUE TITLE
[Pimcore 5] Documentation don't give hints about Logger Core level configuration.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1954]
On Pimcore 5, it seems the debug level for the Core Logger is no more on the GUI in "System Settings".
But documentation (https://www.pimcore.org/docs/5.0.0/Tools_and_Features/System_Settings.html) mention it on this panel (like the Pimcore 4):
"Several debugging settings for Pimcore, like Debug Mode, Password Protection, **Core Logger**, and Application Logger settings."

Maybe the way to set it on Pimcore 5 should be given here int he documentation (or a link to the page explaining it).
I cannot help for a pull request on this as I don't know myself how to change the Logger Core debug level ; ) (i imagine it is now handled by core symfony maybe, so i had to refer to the symfony 3 documentation...).

---

Documentation could be updated too by removing the mention of "Password Protection" as it is now to the developper to place it (via htaccess for instance with apache, etc...).

**Comment by maff** [comment]
Fixed, thanks for reporting :)

**Comment by Yivan** [comment]
Thanks @maff !

Just it seems by default no core logging is configured in /app/config/config.yml.
Maybe a default one could be added (so user see it if they do not read the documentation). It could be added in config.yml or a separate one like logger.example.yml for instance. I think it will help developper to swith from pimcore 4 to pimcore 5 for configuring log level.

**Comment by Yivan** [comment]
Ok, i didn't checked in the Pimcore  bundle. It is great to know those default settings !
Maybe what you said in your last comment could be added in the documentation too (here: https://www.pimcore.org/docs/5.0.0/Tools_and_Features/System_Settings.html). I didn't find any reference of this in the actual documentation (here it talk about extending but don't mention exactly where are the default: https://www.pimcore.org/docs/5.0.0/Extending_Pimcore/Bundle_Developers_Guide/Auto_Loading_Config_And_Routing_Definitions.html).

So adding this somewhere in the documentation could be a good hint:

```
Pimcore includes a set of standard configuration files which (in contrast to a standard Symfony project) are not located in app/config. This gives us the possibility to ship and update default configurations without affecting project code in app. See here and here.

Any of these settings can be overridden in app/config and displayed via bin/console debug:config monolog.
```

**Comment by maff** [comment]
Good idea :) Added a config page in #1961 describing the default config: https://www.pimcore.org/docs/5.0.0/Getting_Started/Configuration.html

**Comment by Yivan** [comment]
Thanks for your reactivity !
This is a really great addition to the documentation, many valuable information.
