### ISSUE TITLE
[Pimcore 5] Configuration imporvement

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1956]
It seems in Symfony5 some parameters from system settings are stored in other files than "system_{env}.php" (if debug is activated or not for instance).
It would be nice to have separated the "application settings" and the "developpement settings", at least the debug email address.
We often need to exlude from git our "system_dev.php" because developper customize often this debug email adress to their one when developping.
Having the development settings separated would authorize to put the system settings in git (because for one projet other settings are the same from one dev to another: languages, versionning, smtp, database credential).

This is just an idea, but mabye could make sense.

**Comment by maff** [comment]
The idea makes perfect sense. In he long term, we're planning to migrate Pimcore's configuration from custom PHP files to Symfony's configuration component (the YAML files we're already using throughout the system) which already supports different environments (prod, dev, ...) and allows to set config values for a local environment - e.g. via env variables or by reading a file which is not tracked in the repository such as files in `app/config/local`.

**Comment by Yivan** [comment]
This will be a great solution, thanks again!
