### ISSUE TITLE
Pimcore 5: Harmonizing icons for `Preview` and `Open`

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#1965]
The link editable currently looks strange (tried in the latest pimcore 5 demo):

![image](https://user-images.githubusercontent.com/4639428/30428108-ac2a7228-9952-11e7-9d5c-8b07eb1c5c3d.png)

There are 2 edit buttons shown.  Aren't there any better icon possibilities? :)

**Comment by weisswurstkanone** [comment]
see https://github.com/pimcore/pimcore/issues/1832

**Comment by brusch** [comment]
Open is now always: 
![image](https://user-images.githubusercontent.com/142037/30478436-4c4fca32-9a11-11e7-95c9-cf7ffda5b5c1.png)
![image](https://user-images.githubusercontent.com/142037/30478443-558b1278-9a11-11e7-9265-d6dfb501f15e.png)

Preview is now always: 
![image](https://user-images.githubusercontent.com/142037/30478461-661fc070-9a11-11e7-8506-181817d17be2.png)
