### ISSUE TITLE
Pimcore 5: link object + document tag improvement request

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#1966]
Currently a link is only marked as "set" in the GUI if both the "text" and the "path" are filled up.

But there are many situations where only the link is needed and the text has no relevance. Remember for example a teaser where the whole teaser is clickable but the link itself is "hidden". In this case the only way currently is to tell the user "just type anything into the text - it has no relevance". The teaser is just one example - there are many other use cases where only a "URL" is needed.

![image](https://user-images.githubusercontent.com/4639428/30428334-7b682db4-9953-11e7-852e-ff18d97afa20.png)

I think it would be great if the link displays the path in the backend if no text is set. 

(A perfect solution would be an option to disable the text field so that it's hidden or maybe a separate editable called "URL".)

**Comment by weisswurstkanone** [comment]
build 118
