### ISSUE TITLE
EccomerceBundle js/css not found

### ISSUE THREAD

**Issue by ascheider** [pimcore/pimcore#1967]
Pimcore Platform (5.0.0-BETA1|117)

![bildschirmfoto 2017-09-14 um 13 58 28](https://user-images.githubusercontent.com/6016485/30428700-e1058daa-9954-11e7-850a-69524200598e.png)

Ecommerce Bundle resources are not found. So i can't see Bundle menu in admin.
![image](https://user-images.githubusercontent.com/6016485/30428756-1a163266-9955-11e7-8ff6-26d5287eaeb8.png)

**Comment by maff** [comment]
Could you please run `bin/console assets:install --symlink --relative`? How did you enable the ecommerce framework bundle?

**Comment by ascheider** [comment]
@maff thank you. That did the trick.
i enabled and installed ecommerce bundle via admin.
while installation i got exception:
Failed to run assets:install command. Please run command manually. which is implemented in ExtensionManagerController and installAssets method. i didn't know that this command is necessary for the bundle resources.
The problem was in my default php version on mac os which is 5.6.
so i need to run it with the right php executable: php7 bin/console instead of bin/console
Thank you for your help.

**Comment by maff** [comment]
The `assets:install` command makes sure that assets are copied/symlinked from the bundle directory into the document root. This should be done automatically from the extension manager but failed as the error stated. I'll create an issue to make sure the command can be run also in environments with a non-standard PHP CLI executable as `php7`.

**Comment by maff** [comment]
@ascheider The assets installer now respects the configured PHP executable. Before pimcore tries to auto-resolve the executable from the `$PATH`, it will look for a `pimcore_executable_php` parameter and use that if it is set (see https://github.com/pimcore/pimcore/blob/master/app/config/parameters.example.yml#L4). In your case you could do something like this:

```
parameters:
    pimcore_executable_php: /usr/bin/php7.0
```

**Comment by ascheider** [comment]
Thank you very mich. I will try it and give you feedback

**Comment by ascheider** [comment]
@maff i just tested the feature with the latest build. works perfectly. Thank you:)
