### ISSUE TITLE
[ECOMMERCE] Update icon to match UI updates

### ISSUE THREAD

**Issue by maff** [pimcore/pimcore#1968]
Currently, the ecommerce icon is smaller than the remaing ones:

![image](https://user-images.githubusercontent.com/27403/30429667-92acf25c-9958-11e7-922c-351a586a9679.png)

**Comment by fashxp** [comment]
fixed by https://github.com/pimcore/pimcore/commit/ee1c98b2a0d7cd1881f0f8ddab8ca934df532be9
