### ISSUE TITLE
[Updater] Skip .htaccess (if it was customized)

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#1970]
While using the web-updater, pimcore also updates the `web/.htaccess` file. Since this file mostly has some additional/custom data, pimcore should respect that and skip it if - for example - a checksum is inconsistent. If I remember rightly, pimcore4 already had a implemented check.

Bonus: If the .htaccess file needs to be updated and it's modified, the updater should show a message after the update is complete.

**Comment by brusch** [comment]
Pimcore 4 only updated the `.htaccess' if it was not changed manually (md5-check afaik).

**Comment by Yivan** [comment]
The "bonus" is a very good idea, because on Pimcore 4 sometimes we forgot to check the .htaccess manually on github to see if their has been changes.

**Comment by brusch** [comment]
Closed in favor of #3120
