### ISSUE TITLE
[Documents] Wysiwyg is randomly injecting non-intended ExtJS HTML attributes

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1978]
Sometimes when saving wysiwyg editable field for documents, Pimcore inject strange character.
Something like:

Rendering in the front end website will diplay:
`
This is my text <div role="presentation" class="x-mask-border box" id="ext-element-27"...> ...
`

This is randomply problem and linked to the admin editor environment it seems. When making test, one time we desactivate Symatec AV and it worked ok (no more injecting custom HTML). After reactivating it was not more injecting it. We dind't have made further test because it happen on customer environment so not easy!
We got one project like this at the begininng, but now we have three customer having sometimes this random/computer dependant behaviour (totally different projets made with Pimcore 4 recent versions, with no customization of backend).
Some of them need to change of computer to be able to edit wysiwyg documents, this is anoying for them, i understand.

I am sorry for the lack of detail, but maybe some Pimcore developper/user have been in the same issue and could report things to help tracking. Maybe the Pimcore core team developper know from where this problem could arise ?

It is a rare problem, but when it happen, the customer will destroy all the wysiwyg entries because it add html extjs tag inside wich are diplay in the front end (and the bad part is that **if they didn't refresh the document in backend, they won't see it has added non wanted extjs tag...**). So if a such editor edit many document in one row without checking in frontend, result can be desastrous. After we have to clean it manually.

I hope some people can give some insight and reports better than me for this.
Thanks.

**Comment by Yivan** [comment]
The "bonus" is a very good idea, because on Pimcore 4 sometimes we forgot to check the .htaccess manually on github to see if their has been changes.

**Comment by Yivan** [comment]
Here is a screen capture of the problem, maybe can help:

![exemple-bug](https://user-images.githubusercontent.com/9025839/30556145-26549dd0-9caa-11e7-8eeb-37a567b8e017.png)

**Comment by brusch** [comment]
Dublicate, see  #2318 (fixed)
