### ISSUE TITLE
Redis Cache backend completely non-functional

### ISSUE THREAD

**Issue by IgorBenko** [pimcore/pimcore#1979]
When using the Redis cache backend, I could never get values from the cache. For example in this code $value would always be null:

```
$value = \Pimcore\Cache::load('testkey');

if (!$value) {
    \Pimcore\Cache::save('testvalue', 'testkey');
}
echo $value;
```

The problem is caused by this commit - which seems to be a workaround for some other issue: 
https://github.com/pimcore/pimcore/commit/b4c3aaee32190b4f222f7c173ec1641a50b9d2d4#diff-c9c7ca2fb97ccb73af916c614b11315b

There might be a good reason for this commit, and the change might be related to different version of redis or credis, but with the latest version, the Redis cache just doesn't work.

![4395ae97-8dbb-49f0-9041-69f6e1c72b67](https://user-images.githubusercontent.com/10233647/30525788-afd03de6-9c0d-11e7-8c80-9518b2621c6d.png)

![634881ac-30c3-4a6d-ae4c-d7ddf4972313](https://user-images.githubusercontent.com/10233647/30525766-5d806f2a-9c0d-11e7-9539-3369508caad7.png)

As can be seen in the images above, $entry is an associative array, so numerical indexes will never be found. 

I can do a pull request, but we need to understand the issue first. Is Redis Cache working OK for you? 

My environment:
Pimcore build 105
Redis server v=4.0.1 (docker image: redis:latest)
colinmollenhour/credis v1.8.2

**Comment by maff** [comment]
@IgorBenko interesting. It's working fine in my environment on travis. At the same location my response looks like expected:

![image](https://user-images.githubusercontent.com/27403/30532542-1f457762-9c55-11e7-8bae-544a212bcd44.png)

Currently investigating what's happening here and how we can fix this.

**Comment by IgorBenko** [comment]
@maff Yes, I was expecting that you would get such output, I am not sure what is different in my setup. I am also trying to figure it out. Will let you know if I find something.

**Comment by maff** [comment]
@IgorBenko you're running this on an environment which has the redis PHP extension installed, right?

**Comment by IgorBenko** [comment]
Yes, I have it installed:
![8bb4037f-91ef-413c-b6e6-aa45e0f92088](https://user-images.githubusercontent.com/10233647/30533552-2159582a-9c5a-11e7-80f9-a80926527a93.png)

I am running redis on another host/container, but that should not make any difference, I guess

**Comment by IgorBenko** [comment]
I think that my response is actually the correct one:
https://github.com/phpredis/phpredis/#hmget
![b36ded1b-6dc1-4743-8e32-6491f01f686c](https://user-images.githubusercontent.com/10233647/30534695-a014523c-9c5f-11e7-9d5c-2562cb4ab84e.png)

In /pimcore/lib/Pimcore/Cache/Pool/Redis.php in doFetch method hMGet is being called.

Testing with these lines might make it easier for you:
```
$redis = new \Redis();
$redis->connect('localhost');
$result = $redis->hMGet('zc:k:document_1', ['d', 'm', 's']);
```
In this case I am also getting an associative array. What do you get?

**Comment by maff** [comment]
@IgorBenko Credis returns the associative array only if the redis extension is enabled. Otherwise, it returns an array with numeric indexes. I opened an issue on https://github.com/colinmollenhour/credis/issues/84 and am currently working on a fix to cope with both situations.

**Comment by IgorBenko** [comment]
@maff That's perfect. Thanks a lot!

**Comment by maff** [comment]
@IgorBenko #1982 should fix this issue (build will be ready soon)

**Comment by IgorBenko** [comment]
@maff Looks good, will test it later. Thanks a lot!

Cheers, Igor

**Comment by IgorBenko** [comment]
@maff I tested it and it works perfectly. Thanks!
