### ISSUE TITLE
[Pimcore 5] Improvement - Add non-owner "href" (object) and "objects with metadata" datatype

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1983]
Actually, the non owner datatype for objects, only work with "Objects" datatype.
It woul be great to have the same for:

- Href (maybe hard to implement because it must consider just object and not document/asset)
- Objects with metadata

**Comment by brusch** [comment]
Actually that's not on our roadmap - but we'd of course merge a PR. Thanks!
