### ISSUE TITLE
[Pimcore 5] "Data Object" typo consistency

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1984]
Is it normal that sometimes the old "Object" name is always presents instead of "Data Object" ? Is it wanted ?

See the two following please - Pimcore 5 online demo (maybe there are other place in GUI where "object" is use instead of "data object"):

![data-objects](https://user-images.githubusercontent.com/9025839/30539946-30e2e5a2-9c75-11e7-9a98-3107a5562536.png)

![data-objects2](https://user-images.githubusercontent.com/9025839/30539947-347acc16-9c75-11e7-90af-f99c87ef7e01.png)

**Comment by brusch** [comment]
We discussed renaming also the data-types, but we stayed away from it because to be consistent we'd also need to rename the underlying PHP classes and that would cause massive issues when updating or migrating from v4 - so we stayed away from it.

**Comment by Yivan** [comment]
Yes I understand better this choice, it would have made long work and break BC. Thanks for your fast answer!
