### ISSUE TITLE
SEO Document Editor for Objects

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#1988]
**Feature Request**: Allow objects to modify SEO Information in a global manner, since there are always objects like news, categories, products.

- use the default SEO Document Editor
- define title and description field via service (maybe like the [link generator](https://www.pimcore.org/docs/5.0.0/Objects/Object_Classes/Class_Settings/Link_Generator.html)
- crawl meta data (h1,h2 etc.), thanks to the link generator :)

What do you think?

**Comment by brusch** [comment]
Closed due to inactivity - but if there are any more specific ideas/concepts please feel free to continue the discussion.
