### ISSUE TITLE
Shared translation file import

### ISSUE THREAD

**Issue by tarun-singhal** [pimcore/pimcore#1993]
### Expected behavior 
  - System should be able to import the file successfully after edit of some content.
 
### Actual behavior  
  - Getting JS error
  
### Steps to reproduce  
  - Import the CSV file through the shared translation page
  - After success import of data, edit the "Text from CSV" column
  - Update the value via just remove the "p" tag.
  - Then re-try to import the CSV file
  - System should be able to import the file successfully.
    
### Code example 
```php
// changed the code in AbstractTranslation.php file
$delta[]=
                                            [
                                                "lg" => $key,
                                                "key" => $textKey,
                                                "text" => $t->getTranslation($key),
                                                "csv" =>  addslashes($value) //changed section with addslashes function 
                                            ];
```

//still i am getting error

# Feature Request 
## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [x] There is no existing issue regarding the same topic

## Feature description 
Please use the below content for import CSV file

```
﻿"key";"de"
"legal - terms and conditions"; "<p> <a href=&quot;http://example.com/24&quot; target=&quot;_blank&quot;>Click here</a>  Sample content <a http://example.com/24&quot; target=&quot;_blank&quot;> Click here </a> dump data. </p>"
```

**Comment by weisswurstkanone** [comment]
Hi, could you please provide the full CSV File. I failed to reproduce the described behavior. We would be happy to resolve this!

BR,
Josef

**Comment by tarun-singhal** [comment]
Hi Josef,
I tried to upload the CSV file, but it's not supported here to upload CSV file format.

Kindle create a CSV file at your end with the below content.
-----------------------------
﻿"key";"de"
"legal - terms and conditions"; "<p> <a href=&quot;http://example.com/24&quot; target=&quot;_blank&quot;>Click here</a>  Sample content <a http://example.com/24&quot; target=&quot;_blank&quot;> Click here </a> dump data. </p>"


-------------------------------------------
-
Thanks,
Tarun

**Comment by weisswurstkanone** [comment]
I think the only way is to do some htmlspecialchars encoding/decoding and display the "raw" text value instead. ExtJS seems to mess it up quite a bit when it tries to update the cell value with a value which is not well-formed.

Build 134

**Comment by tarun-singhal** [comment]
exactly, ExtJs makes issue with some html special char only when we do update case with the old html special values of cell value ..
