### ISSUE TITLE
Missing Backend Translations in Safari

### ISSUE THREAD

**Issue by ascheider** [pimcore/pimcore#1997]
Pimcore Platform (5.0.0-BETA1|121)
Backend is not translated in Safari. In Chrome it works fine.
![image](https://user-images.githubusercontent.com/6016485/30635549-0acf78b0-9df3-11e7-9ce4-6e30051d2469.png)
![image](https://user-images.githubusercontent.com/6016485/30635574-1b2714d4-9df3-11e7-9fa1-1f1f4b3feb0c.png)

**Comment by camico** [comment]
In fact the same happens in older Chrome versions...e.g. 46 (okay, no need to be supported, but maybe to give a hint)

**Comment by maff** [comment]
Thanks for reporting, fixed in #2013.
