### ISSUE TITLE
Hardcoded mapping in lib/Pimcore/Model/AbstractModel.php

### ISSUE THREAD

**Issue by ihaltsou** [pimcore/pimcore#2000]
We would like to create our custom DataObject Loader in our custom bundle. But it looks like following hardcoded piece of mapping does block us. 

```
// we have 2 static mappings for objects for performance reasons
if ($this instanceof DataObject\Concrete) {
    $dao = 'Pimcore\Model\DataObject\Concrete\Dao';
} elseif ($this instanceof DataObject\Listing\Concrete) {
    $dao = 'Pimcore\Model\DataObject\Listing\Concrete\Dao';
}
```

It looks like there's no significant performance effect from this solution. But it brakes the Pimcore's flexibility. I'm just curious if you can fix that. Or if we can prepare a PR which will fix that. 

Thank you in advance. 

https://github.com/pimcore/pimcore/blob/99dc0f204e09a83369e02a4bab573dc55970bbd3/pimcore/lib/Pimcore/Model/AbstractModel.php#L96

**Comment by ihaltsou** [comment]
Hello, could you please share the date when this PR could be added into release? Thank you in advance.

**Comment by brusch** [comment]
We need to review this PR first. This will not be possible before end of next week.

**Comment by ihaltsou** [comment]
Thank you for your prompt response. 
Looking forward for your decision.
