### ISSUE TITLE
[Windows Support] Image Thumbnails return 503

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2002]
e.g. http://localhost/examples/panama/image-thumb__21__standardTeaser/img_0037.jpeg

environment: default xmapp stack

**Comment by brusch** [comment]
Not directly a Pimcore issue. 
The problem is caused by a weird mod_proxy_ajp Apache configuration in XAMPP. Removing 
`LoadModule proxy_ajp_module modules/mod_proxy_ajp.so` in `httpd.conf` solved the issue.
