### ISSUE TITLE
GD Adapter error when opening thumbnail configuration

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2003]
Timestamp: Wed Sep 20 2017 20:29:53 GMT+0200 (W. Europe Daylight Time)
Status: 500 | Internal Server Error
URL: /admin/settings/thumbnail-adapter-check
Message: Warning: imagedestroy() expects parameter 1 to be resource, null given
Trace: [
  {
    "file": "PATHs\\xampp\\htdocs\\pimcore\\lib\\Pimcore\\Image\\Adapter.php",
    "line": 515,
    "function": "destroy",
    "class": "Pimcore\\Image\\Adapter\\GD",
    "type": "->",
    "args": []
  },

**Comment by maff** [comment]
Not only Windows. Also happens in Linux when falling back to GD (e.g. when imagemagick is not available).
