### ISSUE TITLE
[ECOMMERCE] find a faster way to check if the bundle is installed

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#2004]
On my system "show tables like" is a very slow operation. The query needs about 4-10ms. This might not sound that much but it runs on each request.  This could be up to more then 5% of the total request time. I have pages with 25 queries with a total runtime of 3-5ms if I exclude the install check query...

**Comment by maff** [comment]
It's about this call, right? https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PimcoreEcommerceFrameworkBundle.php#L86

**Comment by markus-moser** [comment]
Correct, it only runs when the legacy classmap is activated. Do you have a good idea how to solve it? Otherwise I will think about it and create a pull request.

**Comment by maff** [comment]
As this is already configurable through the `use_legacy_class_mapping` option I think we should do the following:

* Default the config option to false as the legacy mapping is not needed in new installations. Enabling legacy mapping should be done explicitely when migrating from previous versions.
* Remove the `isInstalled()` check and make sure the legacy class mapping can run indepenently of the installed status. Should already be the case (at least it works on my environment without installing the framework).

@fashxp what do you think?

**Comment by markus-moser** [comment]
This sounds good.

**Comment by fashxp** [comment]
:+1:

**Comment by markus-moser** [comment]
Another detail: the `isInstalled()` method is called on other places too. For example in the `IndexFieldSelectionCombo` field definition class. This results in multiple install check queries..

**Comment by maff** [comment]
Fixed in #2057 and #2058 (build 134).
