### ISSUE TITLE
[INSTALLER] ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by mojeprojekty** [pimcore/pimcore#2008]
Expected behavior: GUI installer on http://example.com/install
Actual behavior: Browser error - ERR_TOO_MANY_REDIRECTS

Steps to reproduce:
- composer create-project -s dev pimcore/pimcore ./pimcore5 dev-master
- cd pimcore5 && composer update
- add nginx configuration like https://www.pimcore.org/docs/5.0.0/Installation_and_Upgrade/System_Setup_and_Hosting/Nginx_Configuration.html
- open link http://example.com/install in browser

**Comment by maff** [comment]
Can you post your nginx config? Does this still happen if you remove this redirect? https://github.com/pimcore/pimcore/blob/master/web/install.php#L55

**Comment by mojeprojekty** [comment]
Yes I tried to remove these lines but the problem was in my nginx config. I did not remove these condition from my nginx:

`
if (-f $document_root/install.php) {
        rewrite ^/install(/?.*) /install.php$1 last;
    }
`
Now its working fine. Sorry and thanks for quick response. Regards
