### ISSUE TITLE
Redis cache doInvalidateTags() fails to remove tags from zc:tags using LUA

### ISSUE THREAD

**Issue by gadget60** [pimcore/pimcore#2009]
Tag names in the Redis set SET_TAGS (zc:tags) are non-prefixed. But the LUA implementation of doInvalidateTags() gets tag names prefixed ($pTags which is $tags after calling the preprocessTagIds() method). Therefore KEYS in the LUA script are prefixed, and the following command must fail:

https://github.com/pimcore/pimcore/blob/53fe103062833ba3da1cdca9607a5534997651f3/pimcore/lib/Pimcore/Cache/Pool/Redis.php#L494

The non-LUA implementation does it right:
https://github.com/pimcore/pimcore/blob/53fe103062833ba3da1cdca9607a5534997651f3/pimcore/lib/Pimcore/Cache/Pool/Redis.php#L522

**Comment by gadget60** [comment]
Didn't test it yet - but at first glance I think you must not reuse the variable name "i" for the inner loop - it is already used by the main loop...

**Comment by maff** [comment]
@gadget60  thx, you're right - I tested that change directly without the outer loop and just with one tag against the adapter.
