### ISSUE TITLE
inheritance of checkbox

### ISSUE THREAD

**Issue by fmoreira75** [pimcore/pimcore#201]
Hi all

When we use inheritance on a class, we can have different values between parents and children objects but not for checkbox field.
If we uncheck the field in a child of a parent who have the field checked, when we reopen the child the checkbox still checked.
Is it a normal behaviour? Is it a bug?

Regards

**Comment by brusch** [comment]
Hi, 

This is a known "problem". 
Checkboxes or in specific booleans have 2 possible values, ... TRUE & FALSE. But for inheritance you'd need 3 values, ... TRUE, FALSE, NULL and in the user-interface you'd need the functionality to set the checkbox to NULL. 

In my optinion this makes it more complicated for many other users (without using inheritance) so my suggestion is to use a select-box instead, ... with that you do not have this problem.
