### ISSUE TITLE
[Pimcore 4] Object Listing with added fieldcollection - count() wrong amount

### ISSUE THREAD

**Issue by Swissbrain** [pimcore/pimcore#2014]
When adding fieldcollection with multiple entries on the same object to a object listing, the count() method returns a wrong result.

### Expected behavior 
count() counts objects correctly
  
### Actual behavior  
count() counts objects wrong

### Steps to reproduce  
- Create class
- Create fieldcollection
- Add fieldcollection data component in Class and assign created fieldcollection to Allowed Types
- Create Object and add **two** fieldcollection entries
- Create Listing instance and add fieldcollection to it
```php
$liste = new \Pimcore\Model\Object\Example\Listing();
$liste->addFieldCollection('ExampleFc', 'fc');
echo $liste->count();
```
### Possible Fix
https://github.com/pimcore/pimcore/blob/pimcore4/pimcore/models/Object/Listing/Concrete/Dao.php#L181
Instead of adding the DISTINCT as a string in the $this->getSelectPart() method.
```php
$fieldCollections = $this->model->getFieldCollections();
if (!empty($fieldCollections)) {
    $selectPart = "DISTINCT " . $column;
 }
```
add it with $this->db->select()->distinct(true)
https://github.com/pimcore/pimcore/blob/pimcore4/pimcore/models/Object/Listing/Concrete/Dao.php#L60
```php
$fieldCollections = $this->model->getFieldCollections();
if (!empty($fieldCollections)) {
   $this->db->select()->distinct(true);
}
```

https://github.com/pimcore/pimcore/blob/pimcore4/pimcore/models/Object/Listing/Dao.php#L118
$this->isQueryPartinUse($query, \Zend_Db_Select::DISTINCT) seems not capable of detecting the DISTINCT when adding it with \Zend_Db_Expr as a string, therefore it always returns false.

**Comment by weisswurstkanone** [comment]
build 4105
