### ISSUE TITLE
[Pimcore Website] French version glitches

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2017]
Just to report that the website in French site get some gitches, it could give not professional impression.

Actually (i am in France/French) if i search Pimcore on Google, click on the link Pimcore on the result search (https://www.pimcore.org/, which is the first result ; )) ), i am automaticly directed to https://www.pimcore.org/fr.
This is great but some pages have problem, I think they should be corrected.
Many of our french customer don't know Pimcore and are going to check the website (and we refer sometimes to website during demonstration so they can check Pimcore functionnality/ecosystem/usecase), and surely spot some of those problem.

Pages:
- https://www.pimcore.org/fr/services/professional-services: empy
- https://www.pimcore.org/fr/ressources/blog: empy
- https://www.pimcore.org/fr/ressources/demonstration: basic and advanced not aligned
- The case study in ressources is missing
- If are on the french website and swith to EN ou NL after you cannot choose back FR (doesn't appear in the flag select language menu)

For blog and case study, i sugest to hardlink them to EN version while staying to https://www.pimcore.org/fr section so visitors can go on surfing other pages in FR. Maybe adding [Only available in english] (or something like that) on the top of the blog and case study pages so visitor know it is not a bug. The best would be to have them in French if you target seriously French business for sure (and by the way improve your SEO/visibility).

**Comment by ckemptner** [comment]
@Yivan 
Thank you for reporting this.
We just relaunched the whole website and are currently working on the French translation.
Therefore we closed this issue.
