### ISSUE TITLE
[Pimcore website] Newsletter to be more constantly aware of Pimcore activity.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2018]
It would be great to be able to register to a newsletter so we are not need anymore to check regularly manualy blog, use-case, new Pimcore release, etc, and be easily informed of hot information.
This newsletter could come every week with:
- new blog post
- news use-case post
- new Pimcore release
- week hot features (linking to some page feature of the website) to promote some features
- annoucement not made on the website (saying Pimcore 5 is for soon, ...)
- hot new forum thread (https://talk.pimcore.org/t/curated-list-of-pimcore-5-bundles-plugins/53 => great to make it know to the community, ...)
- hot issues corrected/improvement (github)
- ...

From the bullet point, it can be seen that maybe that two types of newsletter could be possible: news and developper newsletter.

Depending newsletter content it can need human ressources on your side to make them, or be automaticaly generated if restricted to the first 3 bullet-point suggestion for instance (and if nothing new, just send a "No news for this week" newsletter or don't send at all newsletter for this week). For developper newsletter it could be automatically generated too by adding forum thread from the week  having at least one answer and github issue which have been resolved in the week (or just imporvement issue if you want to limit... just idea).

You could make registered by default all peope having contributed to Pimcore (github, forums, partners, etc.), those on your list/crm, etc... (opt-in by default) and provide a unregistration option at the bottom of the newsletter (or if there is some legal problem by include them by default, just send one email saying newsletter is available and give advantage of it with a link to be able to register).  In the same times provide visible registration for new people on the website (no popin necause it is so hassle/negative experience, but an email field in the header or a link in the header opening a popin with a more complete newsletter registration form providing two checkbox to choose to register for the news and/or developper newsletter if you go for two types of newsletters ... just ideas).

**Comment by fashxp** [comment]
thank you very much for your input. 
we are planning lots of things in that direction in the aftermath of pimcore 5 release. so stay tuned ;-)

**Comment by Yivan** [comment]
I close it, as the newsletter is there now and many more things !
