### ISSUE TITLE
Object relations - allow assignment of an item multiple times

### ISSUE THREAD

**Issue by ckogler-elements** [pimcore/pimcore#2022]
# Feature Request 

Currently the relation object types (e.g. Multi-Href, Multi-Href with Metadata ) only allow the assignment of an item once. It would be great if we can assign one item multiple times.

**Comment by fashxp** [comment]
what would be the usecase?

**Comment by weisswurstkanone** [comment]
makes sense Multihref Advanced - multiple items with different metadata

**Comment by cleggypdc** [comment]
+1 for this on multihref with metadata at least, to save having to use field collections as a workaround.

**Comment by dpfaffenbauer** [comment]
But that should be configurable, there are also valid cases where you don't want that at all.

**Comment by datom** [comment]
+1

**Comment by andreas-gruenwald** [comment]
+1

**Comment by brusch** [comment]
- additional config option on the data-type (allow multiple assignments) 
- supported data-types: 
  - advanced many to many relations
  - advanced many to many object relations
