### ISSUE TITLE
Documentation link wrong

### ISSUE THREAD

**Issue by ascheider** [pimcore/pimcore#2024]
Pimcore Platform (5.0.0-RC|124)

File -> Help -> Documentation link points to https://www.pimcore.org/docs/4.6.x/index.html instead of https://www.pimcore.org/docs/5.0.0/index.html
![image](https://user-images.githubusercontent.com/6016485/30846698-f91aefe6-a298-11e7-8e1e-fc9cfbf99cfa.png)

**Comment by maff** [comment]
Fixed in both Pimcore 4 and 5. Thanks for reporting!
