### ISSUE TITLE
[Pimcore5]ObjectsMetadata/Multihref Advanced: support multiselect column type

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#2029]
see [Pimcore4] ObjectsMetadata/Multihrefmetadata: support multiselect column type #2028

**Comment by weisswurstkanone** [comment]
build 129

**Comment by Yivan** [comment]
@weisswurstkanone Thanks for this improvement! I know it is not directly linked, but as i see you worked on multihref and metadatahref, so it is fresh, maybe this issue could be considered https://github.com/pimcore/pimcore/issues/1983 ? ; )
