### ISSUE TITLE
Followup: Namespace `Pimcore\Model\Object` to `Pimcore\Model\DataObject` - Cleanup

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2030]
Old classes in /var/classes/Object are not cleaned up

**Comment by brusch** [comment]
Old directory get's renamed: 
https://github.com/pimcore/pimcore/blob/5ee8182fc45c8f5a3c9406a2be137ccaf1f32856/update-scripts/100/postupdate.php#L5
