### ISSUE TITLE
Followup: Namespace `Pimcore\Model\Object` to `Pimcore\Model\DataObject` - Objectbricks

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2031]
Objectbrick Classes in /var/DataObject/... are not created (objectbricks need to be saved manually at the moment to solve this issue) 

also check for fieldcollections, etc.

**Comment by brusch** [comment]
https://github.com/pimcore/pimcore/blob/5ee8182fc45c8f5a3c9406a2be137ccaf1f32856/update-scripts/100/postupdate.php#L13
