### ISSUE TITLE
Options precision and max-min for quantity value

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#2035]
Offer same options as for numeric data type.

https://github.com/pimcore/pimcore/pull/845 could be used as a guideline

**Comment by SGerry** [comment]
Since we need this feature with max-min values also for one of our customers, i want to ask if this is on the roadmap for a near future release?

**Comment by brusch** [comment]
@SGerry not yet, but you can provide as a PR 😉

**Comment by dpfahlbusch** [comment]
I will provide an PR :)
