### ISSUE TITLE
Dissociate email debug and code debug options in system settings.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2040]
Sometime we need to activate the email debug without the code debug.
I think it is two fonctionnality wich need to be separated (concern two differents things) to be more flexible.

Sugesstion:
Adding a checkbox "Activate debug email" in the "Email Settings" section of "System Settings".

Use case:
When customer controll the project during finalisation/delivery, he cannot check if 404 pages is working great because we need to active "debug" so he can test sended emails too.
With separate debug activation for email debug, we can leave "debug" unchecked (so he see 404 erros, no more exception pages) and we can check "Activate debug email" so all email testing go into his mailbox.

**Comment by brusch** [comment]
We'd accept a PR for that, if someone is willing to contribute this feature.
