### ISSUE TITLE
Bundle Generator Skeleton

### ISSUE THREAD

**Issue by Heiko-H** [pimcore/pimcore#2041]
Documentation seems incorrect or an error exists:
[https://pimcore.com/docs/5.0.x/Extending_Pimcore/Bundle_Developers_Guide/index.html#page_Generating_Pimcore_Bundles](https://pimcore.com/docs/5.0.x/Extending_Pimcore/Bundle_Developers_Guide/index.html#page_Generating_Pimcore_Bundles)

`$ bin/console pimcore:generate:bundle`

Error is shown: 

> [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "pimcore:generate" namespace.

Plugin skeleton cannot be created

**Comment by maff** [comment]
The `PimcoreGeneratorBundle` is only loaded in the dev environment by default (see https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Kernel.php#L228). If you run the console with one of the following variants the command should show up:

```
$ bin/console --env=dev

# or
$ PIMCORE_ENVIRONMENT=dev bin/console
```

**Comment by Yivan** [comment]
@maff i think it should be added on the documentation that it is limited by default to `dev `environment. I searched for this and don't find it in:
- https://pimcore.com/docs/5.0.x/Extending_Pimcore/Bundle_Developers_Guide/index.html
- https://pimcore.com/docs/5.0.x/Extending_Pimcore/Bundle_Developers_Guide/index.html
- https://pimcore.com/docs/5.0.x/Extending_Pimcore/Bundle_Developers_Guide/Pimcore_Bundles/Installers.html

The way to change it (configure one or more environmement, removing `dev` environment, ...) should be documented too.
Why having it restricted by default, is it for security purpose ?

In the code https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Kernel.php#L228, `dev` is hardcoded, shouldn't be a configuration parameter instead ? So it can be easily changed to make it active for one or more another environment ?
Use case: we often make database/classes/assets/plugins changes on our `integration` environment so developpers can update their `dev` environment by simply pulling database/classes/assets (mysqldump -> mysql import + classes/assets files). In this use case `integration` environment need to be able to generate plugin/bundle.

**Comment by maff** [comment]
@Yivan I added a note to the documentation regarding the dev environment. The hardcoded environments are a good point, but not that easy to fix as we currently use these in multiple locations. We'll address this in #2059, but don't expect this happening soon.

We only load the bundle in `dev` primarily for performance reasons, but also security-wise it's good practice to only load what's needed. It's also what Symfony does in its standard distribution (see https://github.com/symfony/symfony-standard/blob/3.3/app/AppKernel.php#L21).

In the meantime, you can just add the bundles (the Symfony Generator Bundle is needed as well) for your `integration` environment manually in your `AppKernel`. Basically that means replicating the following lines in your `AppKernel` and adapting the checked environments: https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Kernel.php#L212

**Comment by Yivan** [comment]
Thanks @maff for your detailled answer. I understand better!
Ok for the hardcoded environment value, there is no hurry ; ) But sure, it is better to be able to change them later.
