### ISSUE TITLE
Weird output of letter "1" on every page before the footer. 

### ISSUE THREAD

**Issue by davidhoeck** [pimcore/pimcore#2044]
Having this issue now in the third project I've started with Pimcore 5. Somehow the view engine is output "1" on every page after the ``` $this->slots->output('_content'); ?>```. 
I have tripple checked there is no number in the code, so i really don't know what to do 👎  

<img width="985" alt="bildschirmfoto 2017-09-30 um 22 09 49" src="https://user-images.githubusercontent.com/24294584/31049127-ba4693dc-a62c-11e7-8aa7-5860e26399ec.png">

**Comment by maff** [comment]
The `output` already contains an echo printing its results and returns a bool (see https://github.com/symfony/templating/blob/master/Helper/SlotsHelper.php#L107). If you echo `output`'s return value, it would explain the "1" being the string representation of the returned bool. Your template call should look something like this:

    <?php $this->slots()->output('_content') ?>

**Comment by davidhoeck** [comment]
@maff Thanks! I just took the old syntax from 4.x with the ```<?= ``` opening tag. My fault :-D
