### ISSUE TITLE
[Pimcore4][Documents] Wysiwyg doesn't read data properly

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#2053]
## Bug report

If have this weird issue with a wysiwyg editable inside a block element, when adding links to it.

After saving and closing the document, you would expect the document to have the same data as before when opening it, but it throws a javascript error: `Uncaught SyntaxError: Invalid or unexpected token` and therefore doesn't initialize the wysiwyg editable, which results in a invisible editable field.

I checked the database and the data in there is stored correctly. I tried clearing the cache, but that had no influence on the issue.

Pimcore v4.6.2, build 4098 (checked Github for commits regarding this issue, but didn't find anything, hence the reason I'm not on the very latest build).

**Database:**
```html
<!-- HTML -->
<a href="http://www.domain.com/" target="_blank">
```

**Backend:**
```json
## JSON ##
<a href="\"http:\/\/www.domain.com\/\"" target="\"_blank\"">
```

**Frontend:**
```html
<!-- HTML -->
<a href="http://www.domain.com/" target="_blank">
```

As you can see above, the error only occurs in the backend, when passing the data via JSON. Even in the frontend the data displays correctly.

Any idea what the issue could be?
Thanks.

**Comment by brusch** [comment]
Unable to reproduce in Pimcore 5.
