### ISSUE TITLE
Asset document thumbnail generation should work asynchronously

### ISSUE THREAD

**Issue by abernardgalilee** [pimcore/pimcore#206]
Hello all.
We currently have several projects in which PDFs or OpenOffice documents are HUGE.
As a result, Ghostscript or LibreOffice consume all CPUs and RAM in order to build preview.

A nice way to handle that would be to globaly call asynchonous services so that php-fpm is not stuck and so that site navigation is not stuck either.

Hope this is clear.

Also you might have workaround to provide to us in order to avoid this problem.

Arnaud.

**Comment by brusch** [comment]
See also #518

**Comment by brusch** [comment]
Already fixed by be7787a18a6c9c60090804b38bc0f79bf7c45fca
See also #5266
