### ISSUE TITLE
[Ecommerce] Refactor installer to use migrations

### ISSUE THREAD

**Issue by maff** [pimcore/pimcore#2066]
Use the MigrationInstaller to handle updates to DB tables and to class definitions in incremental migrations to make sure other bundles can rely on and extend the framework class definitions.

Interaction with other extensions would be:

* Ecommerce framework installs its class definitions (e.g. OnlineShopOrder) and DB structures
* Other extensions handle enhancing those definitions in their own installer. E.g. a bundle relying on the Ecommerce Framework adds a field definition to the OnlineShopOrder class definition upon install
* Changes to framework classes are delivered as migrations. E.g. a field added by the framework will be done via a migration which only adds that field without touching the field added by the other extension.
* The full definition exports are only imported once. Already created classes are never overwritten from exports to avoid data loss. Instead, migrations take care of updating definitions to the desired state.
* At any point, triggering an `update` of the framework in the extension manager allows to migrate data structures to the current migration state.

**Comment by dpfaffenbauer** [comment]
I just created a ClassUpdate Helper class for CoreShop. This looks like this:

https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Component/Pimcore/ClassUpdate.php

It can do following things:

 - insertFieldsBefore - Inserts a new field before an existing field
 - insertFieldsAfter - Inserts a new field after an existing field
 - replaceField - Replace existing field with a new field (or update anything in it)
 - replaceFieldProperties - Replace properties of existing field
 - removeField - Removes existing field

In practice, this then can be used like this:

https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/AdminBundle/Migrations/Version20171013073325.php#L51

I guess that should help you with your Problem 😄
