### ISSUE TITLE
User Notifications

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#2079]
- icon in main toolbar
- message list

**Comment by kubaplas** [comment]
Hi brush, have you seen Divante's Notification Plugin (https://github.com/DivanteLtd/pimcore5-notifications)? 
If you want, we can merge it into the core.

**Comment by Yivan** [comment]
+1
I would like to see it native, more and more user ask for this feature.
Divante's Notification is really great too! I don't know if it can be merged in the core..., but if it is integrated, it will permit to integrate it better with the workflow for instance.

**Comment by weisswurstkanone** [comment]
We would be really happy to integrate this into the core if we are allowed to do so!
@kubaplas , you offered to provide a PR? This would save us a lot of effort :-)

An addittional feature would be nice though: some kind of simple user interface allowing you to pick a recipient similar to the "send to the send test email" form (ideally also offering a way to attach a referenced element).

**Comment by kubaplas** [comment]
@weisswurstkanone we'll do it, just give us a week or two :smile: 
If you have some other suggestions, we'll be happy to hear them.

**Comment by IgorBenko** [comment]
@weisswurstkanone @kubaplas Are there any plans when this would be added? :)

**Comment by weisswurstkanone** [comment]
Hello @kubaplas , any updates regarding this new cool feature ?

**Comment by kubaplas** [comment]
@weisswurstkanone Yeah, we started moving our notifications, see: https://github.com/DivanteLtd/pimcore/tree/issue/2079-user-notifications

**Comment by weisswurstkanone** [comment]
see https://github.com/pimcore/pimcore/pull/3401

**Comment by brusch** [comment]
Closed by #3401
