### ISSUE TITLE
[Installer] Deprecation Warnings

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2090]
User Deprecated: Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "pimcore_ecommerce.locator.order_manager" service to "Pimcore\Bundle\EcommerceFrameworkBundle\OrderManager\IOrderManagerLocator" instead.

**Comment by maff** [comment]
* #2177 
* pimcore/demo-ecommerce@75aba5008da107553deebd2675bdf631e8ef9d64
* pimcore/customer-data-framework#35
* pimcore/advanced-object-search@f7997f2e72b2253f016ea8b70a49408a32b6559e
