### ISSUE TITLE
Custom reports: You have requested a non-existent service "pimcore.custom_report.adapter.factories"

### ISSUE THREAD

**Issue by IgorBenko** [pimcore/pimcore#2094]
I am getting a really weird problem with the Pimcore 5.0.1 (build 133). The 'pimcore.custom_report.adapter.factories' Service can't be retrieved from the container, which kind of makes sense since all service_locator services have their public flag changed to false (in ServiceLocatorTagPass), so they can not be retrieved from the container by just using 'get' on the container. If I remove the 'container.service_locator' tag from the service, then the service is found, but then I get 'Function name get a string' error, since container now tries to call the Class as function. 

Weird is that this seems to function perfectly fine in Pimcore Advanced Demo so I am now out of ideas :)

This is my debug output for this service:
```
$ bin/console debug:container pimcore.custom_report.adapter.factories

Information for Service "pimcore.custom_report.adapter.factories"
=================================================================

 ---------------- ------------------------------------------------------ 
  Option           Value                                                 
 ---------------- ------------------------------------------------------ 
  Service ID       pimcore.custom_report.adapter.factories               
  Class            Symfony\Component\DependencyInjection\ServiceLocator  
  Tags             container.service_locator                             
  Public           no                                                    
  Synthetic        no                                                    
  Lazy             no                                                    
  Shared           yes                                                   
  Abstract         no                                                    
  Autowired        yes                                                   
  Autoconfigured   yes                                                   
 ---------------- ------------------------------------------------------ 
```

I did clear the cache multiple times and rebuilt the DI Container, but nothing seems to work.

Any tip would be highly appreciated.

**Comment by IgorBenko** [comment]
Sorry, forgot to add the screenshot.
![58e03a7f-991d-494e-a3b6-cd3cf6170064](https://user-images.githubusercontent.com/10233647/31441298-113ec1d2-ae93-11e7-9351-ca8f8eaaa73a.png)

**Comment by dpfaffenbauer** [comment]
oh right. Since this is kinda my fault, I'll provide a PR to fix that.

**Comment by maff** [comment]
Setting the service definition to `public: true` wouldn't harm, but I'm wondering how you're running into that issue as it's public on my environment. As far as I can see the `ServiceLocatorTagPass` does register its aliases as private, but does not change the existing definition (at least not for me).

@IgorBenko On which version of `symfony/symfony` are you testing?

**Comment by dpfaffenbauer** [comment]
@maff Guess that happens here: https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/DependencyInjection/Compiler/ServiceLocatorTagPass.php#L67

My idea for a fix would be: Create a Facade Service which gets the ServiceContainer injected and Pimcore uses the facade services instead.

**Comment by IgorBenko** [comment]
Thanks for your reply. I tried setting the `public: true`flag but it didn't change anything. The flag still became false. I think that actually aliases stay public but original service gets set to `public: false`.
@dpfaffenbauer What do you think might have caused this, I checked all the configs after 133 and I couldn't see anything that would make a difference. If you give me a hint where the problem is, I can do the Pull Request, I just couldn't figure out what is causing this.

**Comment by maff** [comment]
@dpfaffenbauer Hmm, I'm not running into this line for those locators as `$isRoot` is true in that case (but I still to check in detail what's going on). Anyways a service handling the locator internally would be a good idea (as we do in the Ecommerce Framework, e.g. OrderManagerLocator).

@IgorBenko Do you have a `{ config: { platform: 7.0 } }` in your `composer.json`? If so, could you remove that and run a composer update? It should update to Symfony 3.3.10 which might make a difference.

**Comment by IgorBenko** [comment]
@dpfaffenbauer Damn you're fast :) I find your solution great. Even better would be to not use the Service Locator at all, but step by step :)

@maff Updating to Symfony 3.3.10 resolved the issue for me. Thanks a lot for the hint! It would still probably make sense to do it like Dominik suggested.

**Comment by dpfaffenbauer** [comment]
@IgorBenko ServiceLocator makes total sense in this case, since there are multiple factories and we need to access these services somehow ;). One thing could be to create a custom registry like: https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Component/Registry/ServiceRegistry.php. But that would be conceptually the same.

Since Symfony 3.3.10 resolves this issue, do we still need this PR at all? I mean, I would consider this as symfony bug anyway then.

**Comment by IgorBenko** [comment]
@maff and @dpfaffenbauer  thanks a lot for your support!

@dpfaffenbauer I had in mind a factory of factories that would get injected, but I might be overthinking this or (and that's absolutelly possible) not even thinking correctly about the problem :)
