### ISSUE TITLE
[Improvement] Improve Pimcore object import by adding a way to handle localized fields

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2106]
Actually, localized fields cannot at all be imported. They are not in the list of possible mapping.

Importer could be improved. I think of two possibility (one simple, one more complex):

- simple: we add the localized fields on the list of fields for the mapping, and we add a global select box for the import to choose the language. On the PHP side, i think it will make just small change, we call the setMyField($value, $langue).
To import another language, administrator will have to import a second CSV (having only id and localized fields) and select the other language. This second import will update the object (to keep initial data and localized field from the first import).

- more complex: we add the localized fields on the list of field for the mapping with post-prefixed them by language. So for exemple a list of available mappings will be:
  - id
  - category
  - name (en)
  - name (de)
  - ...
On the php side, we need to handle the langage depending the selected mappings.

For complex object, there is this plugin https://github.com/w-vision/ImportDefinitions , but it would be great to have a core importer handling simple localized object without relying on an extension.

**Comment by Yivan** [comment]
Is this issue always necessary as you are working on a new importer ? : ) Will it handle the localized files ?

**Comment by weisswurstkanone** [comment]
Simply combine it with the localeswitcher operator
https://github.com/pimcore/pimcore/blob/master/doc/User_Documentation/01_Objects/02_CSV_Import/02_Operators/03_LocaleSwitcher.md

**Comment by Yivan** [comment]
Seems great ! Thanks for this improvement.
So I think this issue can be closed.
