### ISSUE TITLE
[Docs] Add List of good Bundles?

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#2107]
This is an idea I just had: Why not create a list of third-party pimcore bundles in docs? So new people know what plugins are out there. Pimcore Team would also have the possibility to review changes in documentation and kinda "approve" (=more or less) what comes in.

And of course: We need to add a big note that Pimcore is not responsible for third-party bundles ;)

**Comment by Yivan** [comment]
I like really this one!
We could start from https://talk.pimcore.org/t/curated-list-of-pimcore-5-bundles-plugins/53 , Pimcore team can currate it and manage the list if it is on the documentation, really good idea, simple and effective!
People will be more aware of the existence of those extension.

**Comment by fashxp** [comment]
Hi, 
thank you very much for your input. 
We would prefer it to go for some kind of marketplace. Currently we are working on a concept and want to have a first version as soon as possible. We'll keep you updated!

Cheers...

**Comment by brusch** [comment]
Marketplace is on the roadmap and will be available on pimcore.com around Q3
