### ISSUE TITLE
Option to duplicate whole panel and other containers in the class definition

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#211]
Will be great to have a option for panel and other containers duplications not only for properties.
![axxxxxxxxx](https://cloud.githubusercontent.com/assets/11477130/9130016/468bcb70-3ce7-11e5-96a3-a62d767cf036.png)

**Comment by kanevbg** [comment]
In the attached image you will see I have opened the right mouse click menu, there is missing a duplicate option.

**Comment by weisswurstkanone** [comment]
Isn't this already possible via the copy/paste feature (since build 3510). See screenshot

**Comment by weisswurstkanone** [comment]
![copy](https://cloud.githubusercontent.com/assets/6142086/12233061/23b80e9e-b864-11e5-8c73-130e0c9cbdc7.png)

**Comment by weisswurstkanone** [comment]
already implemented
