### ISSUE TITLE
Store empty fields as NULL in DB

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#2110]
## Reproducing
- Create a object with some textfields / wysiwyg fields
- Activate at least two languages in system settings. Add the first language as fallback to the second one
- Open object and add some text to a field of the first language tab and save
-  Check db: table of second language`object_localized_query_xy_LANG`:  all fields are stores as `NULL` - which is fine
- Check db: view of second language `object_localized_xy_LANG`: fields are populated with data from the first language - which is fine, the fallback works
- Now, open the object again and **just** place the cursor in one of the fields of the second language tab
- Save object
- Check DB again: fields are updated as empty strings, so the fallback will not work anymore.

**Comment by solverat** [comment]
@brusch could you give us a good advise how to handle the language fallback? Currently we need to explain customers that they are not allowed to click into a localizedField otherwise the language callback does not work anymore. 

- not touched field: `NULL`
- touched field: `""`

As you can imagine this is a tricky one for content administrators. It's also tricky from the technical perspective (both values can be valid: `null` => override, `""` => explicitly empty **or** no content) So... how do you handle this? We thought about implementing a `dirty` flag to each localized field but i'm not quite sure about that.

**Comment by fashxp** [comment]
We'll have to check that in detail. I put it into our next sprint so we have a look at it.

**Comment by solverat** [comment]
@fashxp thanks for your investigation!

**Comment by fashxp** [comment]
Hi @solverat, 
now I had the time to check this in detail. 
I can reproduce the problem, that once a value was stored to a localized field in a certain language and removed afterwards, fallback languages did not work anymore (because in the tables the value '' instead of NULL was stored). 
I cannot reproduce this behavior by just clicking into localized fields. 

But anyway, could you please check if #2842 solves this issue?
