### ISSUE TITLE
Encrypted Credential Store

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#2115]
Simple and very generic set/get encrypted credential store for username/passwords, tokens, service / client ids, ... 

Using `defuse/php-encryption` 

Maybe we can use the Symfony secret: 
https://github.com/pimcore/pimcore/blob/2ef649f058639ce1711f501fdafb4a8ba92102c7/app/config/parameters.example.yml#L2

Refactoring all existing credential configurations to use this new service: 
- database
- tracking (Piwik, Google, ...) 
- Google services (system settings) 
- email smtp? 
- proxy?

**Comment by cleggypdc** [comment]
- payment provider keys (ecommerce config)
