### ISSUE TITLE
Assets - Do not Display Warning When Deleting Folders without Dependencies

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#2119]
### Expected behavior 
When deleting an asset folder if none of the assets in the subfolder have dependencies the system should not show a warning.
  
### Actual behavior  
The warning "There are dependencies, delete anyway?" is displayed even if no assets in the subfolder have dependencies.

Latest version (5.0.1)

**Comment by brusch** [comment]
We'll that depends on the point of view ;) Actually Pimcore sees children also as a dependency (since they depend on the parent). Maybe the message is a bit misleading, but I wouldn't remove the warning completely.
