### ISSUE TITLE
Sending newsletters doesn't work, cannot find adapter factory

### ISSUE THREAD

**Issue by dominikschnieper** [pimcore/pimcore#2126]
# Bug Report
Pimcore 5 issue
 
### Expected behavior 
No error should appear

### Actual behavior
You have requested a non-existent service "pimcore.newsletter.address_source_adapter.factories"

### Steps to reproduce  
try to send a newsletter to test or real recipents

**Comment by maff** [comment]
Hi Dominik,

I suspect this is the same issue as #2094 - if there still is a `{ config: { platform: 7.0 } }` entry in your `composer.json` it won't upgrade to Symfony > 3.3.6 resulting in the factory locator being private. If that's the case removing that config and running a `composer update` should update to the latest Symfony version and fix the issue.

Note: this only applies to Pimcore 5 installations which were installed prior to the 5.0.0 release as the `platform` config entry was removed before 5.0.0 was released.

Cheers,
Mathias

**Comment by dominikschnieper** [comment]
Thank you, this is correct and i could fix it!

Thanks,
Dominik
