### ISSUE TITLE
AbstractObject & Document: unpublished objects in getChildren vs. hasChildren

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#2128]
In [getChildren](https://github.com/pimcore/pimcore/blob/5483c6f0fa00cfb4026b15ef5ffbfaf9dcee66ca/pimcore/models/DataObject/AbstractObject.php#L424) method the query only loads unpublished objects by default. In [hasChildren](https://github.com/pimcore/pimcore/blob/5483c6f0fa00cfb4026b15ef5ffbfaf9dcee66ca/pimcore/models/DataObject/AbstractObject.php#L446) method on the other hand all objects gets loaded (without any option to change that). I think this method also should load only unpublished objects too? Am i missing something?

**Comment by weisswurstkanone** [comment]
Are you sure. It seems that it is the other way round (i.e. ut only loads published objects).
