### ISSUE TITLE
Admin Translation Exception

### ISSUE THREAD

**Issue by KarlXOL** [pimcore/pimcore#2129]
# Bug Report
When working with Admin Translation you get this exception
![pimcore_admintranslation_exception](https://user-images.githubusercontent.com/21153915/31718037-a8c5c52a-b40e-11e7-98aa-940c18a7cad1.PNG)

This must be somehow related to changing columns in the list, or using filtervalues. 
The first time I was able to view and enter some translations. The next time I tried to update translations here I got this exception.

The same behaviour in the pimcore advanced-demo. Screen-shot is also attached
![pimcore_admintranslation_exception- advanced demo](https://user-images.githubusercontent.com/21153915/31718179-31af3ab0-b40f-11e7-8a59-eaa974fb58ea.PNG)

**Comment by weisswurstkanone** [comment]
fixed in build 167
