### ISSUE TITLE
Add class name to the opened object panel element in the class property

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#213]
![azzaaa](https://cloud.githubusercontent.com/assets/11477130/9132962/1efc1556-3d00-11e5-8034-5ae2ee5e6238.png)
Please look at the attachment.
The idea is that the class in the selected element will be "x-panel x-panel-noborder class-CLASSNAME" instead of "x-panel x-panel-noborder" as is at this time.
This will enhance the styles related for specific type of object.

For example if we have class "Article" the panel will have a class "class-article" and by this class we can style for example the way the styles in the WYSIWYG redactor will appear strictly for this type of objects from custom plugin which has own CSS for the backend.

It is just simple improvement in the code but will allow enhanced styling.

**Comment by weisswurstkanone** [comment]
build 3595
