### ISSUE TITLE
[Pimcore 5] Webservice REST translation return empty datas

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2134]
The webservice REST return empty datas for translations.

To reproduce:
- login to the online demo as admin / demo
- on another tab call: https://demo-basic.pimcore.org/webservice/rest/translations?type=website or https://demo-basic.pimcore.org/webservice/rest/translations?type=admin

Returns is:
{"success":true,"total":0,"data":[]}

It should send back the translations.
(I didn't check if other webservice are broken ... but maybe the bug is on others methods too)

**Comment by weisswurstkanone** [comment]
fixed in build 141
