### ISSUE TITLE
[ECOMMERCE] - make adding pricingrule ext-classes simpler

### ISSUE THREAD

**Issue by AlternateIf** [pimcore/pimcore#2137]
if you want to add pr-ext-classes from another bundle the ecommerceFramework has to be loaded before the adding bundle. In order to guarantee this the priority of the ecommerceFrameworkBundle needs to be higher than the adding bundle.

Since this makes the adding bundle not work out of the box (because the priority can't be set from the code) the only other way is to use the pimcoreReady function and add the ext-classes there

@maff

**Comment by fashxp** [comment]
won't fix for now
