### ISSUE TITLE
[ECOMMERCE] - make the icon-class of pricingrules completely configurable

### ISSUE THREAD

**Issue by AlternateIf** [pimcore/pimcore#2138]
Currently the icon class of  the menu-item is set as bundle_ecommerce_pricing_icon_condition%CONDITIONNAME%. The same applies for actions.

It is possible to fully define the icon-class in the panel opened by clicking on the menu-item though. Regarding the fact the icon-class is defined in another bundle the menu-item icon-class should also be fully customizable

@maff

**Comment by AlternateIf** [comment]
see

https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Resources/public/js/pricing/config/item.js#L553 

https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Resources/public/js/pricing/config/item.js#L209

**Comment by fashxp** [comment]
won't fix for now
