### ISSUE TITLE
[ECOMMERCE] Access the service container within a cart price modificator

### ISSUE THREAD

**Issue by davidhoeck** [pimcore/pimcore#2145]
I tried to find a smooth way to access the service container from within an cart price modificator. 
Is there a way to pass services to the modificators ? 
If not it would be a pretty good feature, because I think in many cases developers need to have access to the service container.
e.g. custom HTTP clients for shipping carriers and so on ...

**Comment by dpfaffenbauer** [comment]
Pimcore::getContainer always works ;)
