### ISSUE TITLE
width or height undefined in thumbnail configuration

### ISSUE THREAD

**Issue by h2g-internetagentur** [pimcore/pimcore#215]
If the width or height is undefined in a thumbnail configuration over url the thumbnail generator fires PHP errors cause the incomplete dimensions. to fix this i modificated the getThumbnail method in the Pimcore\Model\Asset\Image Class.

    public function getThumbnail($config = null, $deferred = false) {
        if( is_array( $config ) && ( isset( $config['width'] ) == true || isset( $config['width'] ) == true ) ) {
            if( @$config['width'] == 'undefined' )
                $config['width'] = round( ( $this->getWidth() / $this->getHeight() ) * $config['height'] );
            if( @$config['height'] == 'undefined' )
                $config['height'] = round( ( $this->getHeight() / $this->getWidth() ) * $config['width'] );
        }
        $thumb = new Image\Thumbnail($this, $config, $deferred);
        return $thumb;
    }

**Comment by brusch** [comment]
Sorry, can you explain the problem a little bit more in detail? The above fix looks more like a hack for an incorrect usage of the thumbnail functionality. 

Thanks!

**Comment by brusch** [comment]
Closed due inactivity. 
Please answer if this is still an issue. Thanks!

**Comment by h2g-internetagentur** [comment]
It affects only the preview image in the editmode. That means a broken image is shown cause of a PHP error from the thumbnail generator caused by the undefined heigth specification:
/admin/asset/get-image-thumbnail/id/270/width/288/height/undefined?id=270&path=....

Ofcourse, if pimcore is built the way that I have to provide a width and the acurate height of the image I want to generate a thumbnail of, then my code is a hack to a incorrect thumbnail usage.
