### ISSUE TITLE
Can't access editables in areabrick class

### ISSUE THREAD

**Issue by go4webch** [pimcore/pimcore#2152]
In pimcore 4 we could access editables declared in the view file in the areabrick class (Most used in the action() method).

Now it seems this isn't working anymore:

#### Areabrick Class
```php
<?php

namespace AppBundle\Document\Areabrick;

use Pimcore\Extension\Document\Areabrick\AbstractTemplateAreabrick;
use Pimcore\Model\Document\Tag\Area\Info;

class Calendar extends AbstractTemplateAreabrick
{
    // implementing class methods
    public function action(Info $info) {
        $demoField = $info->getView()->input("title");
    }
}

```

#### View File
```php
<section class="calendarSearch">
<h2><?= $this->input("title"); ?></h2>
<?php
	$targetDocument = \Pimcore\Model\Document::getByPath('/de')->getProperty('searchsite');
?>
// some more code...
</section>
```
### Expected behavior 

I should be able to read the content of $this->input("title"); in the areabrick class to keep the view clean from any logic.

### Actual behavior 

Call to undefined method Pimcore\Templating\Model\ViewModel::input()

... or alternatively, what would the pimcore 5 way be to keep the areabrick views clean of any logic?

**Comment by maff** [comment]
There's a `getDocumentTag` method on the base areabrick class which you can use to access an editable (see https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Extension/Document/Areabrick/AbstractAreabrick.php#L154). In your case:

```php
<?php

namespace AppBundle\Document\Areabrick;

use Pimcore\Extension\Document\Areabrick\AbstractTemplateAreabrick;
use Pimcore\Model\Document\Tag\Area\Info;

class Calendar extends AbstractTemplateAreabrick
{
    public function action(Info $info)
    {
        $demoField = $this->getDocumentTag($info->getDocument(), 'input', 'title');
    }
}
