### ISSUE TITLE
Upgrading issue depending on Composer version: Please ensure that composer is in your PATH variable

### ISSUE THREAD

**Issue by davidbhlm-github** [pimcore/pimcore#2157]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [X] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [ ] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [X] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [X] There's no existing ticket for the same issue
- [X] Remove unused sections from below and this bullet points

### Expected behavior 
To access _admin/update/index/check-composer-installed_ and receive:

> {"success":true}

### Actual behavior  
  
When accessing _admin/update/index/check-composer-installed_ with composer 2015-09-28, I can see:

> {"success":true}

However, when accessing _admin/update/index/check-composer-installed_ with composer 2016-12-11, 2017-01-11 and 2017-07-20 (or after applying `composer selfupdate`), I receive:

> {"success":false}

### Steps to reproduce  

 * Install pimcore 5.0.0. 
 * Add composer 2015-09-28 to the PATH. 
 * Try to upgrade to pimcore 5.0.1. It will pass the checkComposer(). You will be prompted to execute `composer update` from command line. 
 * Run `composer update`. You will receive the error below

```
Script @symfony-scripts handling the post-update-cmd event returned with an error

  [RuntimeException]
  Error Output: sh: 1: @symfony-scripts: not found

```

 * The error disappears by executing `composer selfupdate`. However, _admin/update/index/check-composer-installed_  returns false after that. 

If you try the steps above with different composer version, you can't proceed with the upgrade. I have tried the code with different versions of composer (2016-12-11, 2017-01-11 and 2017-07-20), and checkComposer() always fails. 

# Feature Request 

Fix the issue to detect new versions of Composer in the PATH.

## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [X] There is no existing issue regarding the same topic

**Comment by maff** [comment]
This seems to be related to #1362. Until we found a fix for that you can use the following workaround to define the path to your composer executable (Pimcore will skip trying to lookup the executable and use the configured one). You might need to try if prefixing the path to composer with something like `php` or `/usr/bin/php` is necessary:

```yaml
parameters:
    pimcore_executable_composer: php /opt/vendor/bin/composer.phar
```
