### ISSUE TITLE
[New feature] Queue/Delay for emails

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2159]
Sometimes when several objects are updated we need to send emails to peoples. This use case appears often on the project we worked pimcore with.
Actually, using the API, the email are sent in a syncrhone way, so the request take more lognuer to finish. With many emails to send it can lead to long process when updating objects which leads to send email.

Some custom queue could be developped depending of the project, but it would be nice to have already a delayed sending system available in Pimcore in the email framework, by adding just:

```
$mail = new Pimcore\Mail();
$mail->addTo($email);
$mail->...
$mail->setDelayed(true);
$mail->send();
```

The mail will be sent delayed in an asynchrone way not blocking the current script.
Maybe we could imagine an email queue which is processed depending the maintenance script interval.
Another way, will be like for the asset to run some sort of delayedsending (like the delayed processing of thumbnail).

It will offer to the developpers to easily use it by just set `setDelayed` to true. All front-end forms sending emails could benefits of this too, having a faster return message (as email will be sent delayed, the http response will be faster) and so having better experience.

---

A more complexe step could be implemented later, like some sort of plannification by giving a date.
$mail->setDelayed($timestamp);

**Comment by maff** [comment]
Hi @Yivan,

actually Swiftmailer already provides a spooling solution which is integrated into Symfony, see https://symfony.com/doc/current/email/spool.html. Could you give it a try and check if there is anything missing from a PImcore point of view?

Thanks,
Mathias

**Comment by Yivan** [comment]
It seems great and provide abilities to delay email! I will try it and reopen the issue if needed.
You can close it for now.
Thanks.
