### ISSUE TITLE
Problem with Backend cache growing object size stored.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#216]
Following the discussion here : https://www.pimcore.org/board/viewtopic.php?f=7&t=1386&p=9480

It seems that the stored cached object (called back in getById) take more size than the object itself. Maybe some information is appended in the time making it growing... but problem is after some days, getList method can use all memory if many object are fetched from the cache.

We got problem with Redis2 cache, but user in the forum reported having same problem with memcache.
I think it is a global cache problem (not depending from the backend cahce method), as the memory problem is object use more and more memory and finally overflow the PHP limit.

As other user we only had this problem with the recents Pimcore versions. Maybe something changed.

Best regards!

-------------------------
Fact posted by us on the forum at the mentionned thread:

I got the same problem with Redis as backend cache.
<backend>
<type>\Pimcore\Cache\Backend\Redis2</type>
<custom>true</custom>
<options>
<server>127.0.0.1</server>
<port>6379</port>
<persistent>1</persistent>
<database>1</database>
<use_lua>1</use_lua>
</options>
</backend>

So it doesn't come specificaly from Memcached, but from the global cache mecanism maybe.

Pimcore 3.0.6 (last stable version):
PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 512 bytes) in .../pimcore/lib/Zend/Cache/Core.php on line 313

It works well and after some days we got this error. Flushing the cache make it work again.
Ok after further investigation, it seems that the cached object (when you get them with getById) take more memory than if you do not fetch them from the cache.

-------------------------
After more investigation we found:

If i keep code fetching from cache i got (memory_get_usage() / memory_get_usage(true) is given)

Is going to getById object ID: 46 (memory before: 3.47 mb / 3.75 mb)
Is going to getById object ID: 48 (memory before: 36.19 mb / 44.25 mb)
Is going to getById object ID: 50 (memory before: 36.66 mb / 44.25 mb)
Is going to getById object ID: 52 (memory before: 38.32 mb / 44.25 mb)
Is going to getById object ID: 54 (memory before: 38.7 mb / 44.25 mb)
Is going to getById object ID: 56 (memory before: 40.33 mb / 44.25 mb)
Is going to getById object ID: 58 (memory before: 41.08 mb / 44.75 mb)
Is going to getById object ID: 60 (memory before: 41.24 mb / 44.75 mb)
Is going to getById object ID: 94 (memory before: 41.46 mb / 44.75 mb)
Is going to getById object ID: 97 (memory before: 41.75 mb / 44.75 mb)
Is going to getById object ID: 104 (memory before: 42.22 mb / 44.75 mb)
Is going to getById object ID: 105 (memory before: 42.22 mb / 44.75 mb)
Is going to getById object ID: 107 (memory before: 42.22 mb / 44.75 mb)
Is going to getById object ID: 108 (memory before: 42.65 mb / 44.75 mb)
Is going to getById object ID: 109 (memory before: 43.28 mb / 44.75 mb)
Is going to getById object ID: 110 (memory before: 43.45 mb / 44.75 mb)
Is going to getById object ID: 111 (memory before: 43.83 mb / 44.75 mb)
Is going to getById object ID: 112 (memory before: 43.91 mb / 44.75 mb)
Is going to getById object ID: 113 (memory before: 75.75 mb / 83.75 mb)
Is going to getById object ID: 114 (memory before: 76.14 mb / 83.75 mb)
Is going to getById object ID: 115 (memory before: 80.45 mb / 84.75 mb)
Is going to getById object ID: 116 (memory before: 83.59 mb / 84.75 mb)
Is going to getById object ID: 117 (memory before: 83.77 mb / 84.75 mb)
Is going to getById object ID: 118 (memory before: 83.93 mb / 84.75 mb)
Is going to getById object ID: 119 (memory before: 84.04 mb / 84.75 mb)
Is going to getById object ID: 120 (memory before: 84.17 mb / 84.75 mb)
Is going to getById object ID: 121 (memory before: 84.31 mb / 84.75 mb)
Is going to getById object ID: 122 (memory before: 84.46 mb / 85 mb)
Is going to getById object ID: 123 (memory before: 84.66 mb / 85.25 mb)
Is going to getById object ID: 124 (memory before: 84.74 mb / 85.25 mb)
Is going to getById object ID: 126 (memory before: 84.83 mb / 85.25 mb)
Is going to getById object ID: 127 (memory before: 85.06 mb / 85.5 mb)
Is going to getById object ID: 128 (memory before: 85.29 mb / 85.75 mb)
Is going to getById object ID: 129 (memory before: 85.52 mb / 86 mb)
Is going to getById object ID: 130 (memory before: 85.6 mb / 86 mb)
Is going to getById object ID: 131 (memory before: 86.98 mb / 87.75 mb)
Is going to getById object ID: 132 (memory before: 87.08 mb / 87.75 mb)
Is going to getById object ID: 914 (memory before: 87.17 mb / 87.75 mb)
Is going to getById object ID: 936 (memory before: 87.45 mb / 88 mb)

And if i disable cache loading (by directly editing getById method in \pimcore\models\Object\AbstractObject.php and disable $object = Cache::load($cacheKey) line 238) i got:

Is going to getById object ID: 46 (memory before: 3.47 mb / 3.75 mb)
Is going to getById object ID: 48 (memory before: 5.49 mb / 5.75 mb)
Is going to getById object ID: 50 (memory before: 5.92 mb / 6.25 mb)
Is going to getById object ID: 52 (memory before: 6.46 mb / 6.75 mb)
Is going to getById object ID: 54 (memory before: 6.8 mb / 7 mb)
Is going to getById object ID: 56 (memory before: 7.22 mb / 7.5 mb)
Is going to getById object ID: 58 (memory before: 7.44 mb / 7.75 mb)
Is going to getById object ID: 60 (memory before: 7.59 mb / 7.75 mb)
Is going to getById object ID: 94 (memory before: 7.79 mb / 8 mb)
Is going to getById object ID: 97 (memory before: 8.18 mb / 8.75 mb)
Is going to getById object ID: 104 (memory before: 8.18 mb / 8.75 mb)
Is going to getById object ID: 105 (memory before: 8.18 mb / 8.75 mb)
Is going to getById object ID: 107 (memory before: 8.18 mb / 8.75 mb)
Is going to getById object ID: 108 (memory before: 8.57 mb / 9 mb)
Is going to getById object ID: 109 (memory before: 8.57 mb / 9 mb)
Is going to getById object ID: 110 (memory before: 8.72 mb / 9.25 mb)
Is going to getById object ID: 111 (memory before: 8.72 mb / 9.25 mb)
Is going to getById object ID: 112 (memory before: 8.8 mb / 9.25 mb)
Is going to getById object ID: 113 (memory before: 8.8 mb / 9.25 mb)
Is going to getById object ID: 114 (memory before: 8.8 mb / 9.25 mb)
Is going to getById object ID: 115 (memory before: 9.03 mb / 9.5 mb)
Is going to getById object ID: 116 (memory before: 9.03 mb / 9.5 mb)
Is going to getById object ID: 117 (memory before: 9.19 mb / 9.75 mb)
Is going to getById object ID: 118 (memory before: 9.34 mb / 9.75 mb)
Is going to getById object ID: 119 (memory before: 9.34 mb / 9.75 mb)
Is going to getById object ID: 120 (memory before: 9.46 mb / 10 mb)
Is going to getById object ID: 121 (memory before: 9.6 mb / 10 mb)
Is going to getById object ID: 122 (memory before: 9.73 mb / 10.25 mb)
Is going to getById object ID: 123 (memory before: 9.92 mb / 10.5 mb)
Is going to getById object ID: 124 (memory before: 9.99 mb / 10.5 mb)
Is going to getById object ID: 126 (memory before: 9.99 mb / 10.5 mb)
Is going to getById object ID: 127 (memory before: 10.2 mb / 10.75 mb)
Is going to getById object ID: 128 (memory before: 10.4 mb / 11 mb)
Is going to getById object ID: 129 (memory before: 10.4 mb / 11 mb)
Is going to getById object ID: 130 (memory before: 10.49 mb / 11 mb)
Is going to getById object ID: 131 (memory before: 10.49 mb / 11 mb)
Is going to getById object ID: 132 (memory before: 10.57 mb / 11 mb)
Is going to getById object ID: 914 (memory before: 10.65 mb / 11.25 mb)
Is going to getById object ID: 936 (memory before: 10.92 mb / 11.5 mb)

There is a problem as cached data take many more memory than directly fetching them freshly.
So actullay i thing it use the 128mb available at the end and Zend_Cache has no more memory to unserialize it in /pimcore/lib/Zend/Cache/Core.php on line 313, making the fatal error.

**Comment by brusch** [comment]
Please provide us the following: 
- a class schema (JSON export out of pimcore) 
- a script how we can reproduce the behavior 

Thanks!

**Comment by brusch** [comment]
I tried the following script: 

```php
<?php

include("../pimcore/cli/startup.php");

use Pimcore\Model\Object;

$news = new Object\News\Listing();
$ids = $news->loadIdList();

foreach($ids as $id) {
    $object = Object::getById($id);

    echo "ID: $id | " . formatBytes(memory_get_usage()) . "/" . formatBytes(memory_get_usage(true)) . "\n";
}
´´´

**Comment by Yivan** [comment]
I can just attach PNG, GIF, JPG... so no luck to attach .json export.

I made further search. The memory leak occurs during the unserialize (in /pimcore/lib/Zend/Cache/Core.php on line 313). The load is ok (use a little more memory from usual but ok i think), but the unserialize make the big leap (around 40Mo).

The class used for the object has cross-reference (a field "Relation" of type "Objects").
There is no lazy-loading on this.

I check the object for those this leap occurs and they are those with 2 cross-references:
A->B, A->C, C->A, B->A, C->B... i don't know if it is chance or not... 

So a solution can be to check lazy loading for this field class.

I cleared the cache, and now the cache loaded is ok. I don't understand why after somedays it is no more okay (for the same objects, no change...).
So actually I cannot reproduce it. I am try a way to anderstand why after cleaning the cache, the stored object in cache use memory normally, and why after somedays there is a huge leap for some of them.

**Comment by Yivan** [comment]
Yes it the same script I used but directly in the loop foreach ($objectsData as $objectData) in the load() method of /pimcore/models/Object/Listing/Concrete/Resource.php.

I made another script in the /pimcore/lib/Zend/Cache/Core.php, from wich i have seens that this is the unserialize wich use many memory. After that I make a var_dump of one of the unserialized object (stored in a file so i can chek it because too big for browser). And seems many recurssion, so i am in favor that it comes from the model wich should use lazy loading for the field making recursion.

I could join you this file of the object too, but as mentionned earlier only image seems to be allowed.

----
By the way when we create issue, i cannot no more choose Improvment, Bug... etc, is there a way to give more details like before (pimcore version priority, etc...) ? Thanks!

**Comment by Yivan** [comment]
Here is the reslut after flushing cache and make sure all object are again in the redis cache:

Is going to getById object ID: 46 (memory before: 3.47 mb / 3.75 mb)
Is going to getById object ID: 48 (memory before: 4.41 mb / 4.75 mb)
Is going to getById object ID: 50 (memory before: 4.88 mb / 5.25 mb)
Is going to getById object ID: 52 (memory before: 5.4 mb / 5.75 mb)
Is going to getById object ID: 54 (memory before: 5.78 mb / 6 mb)
Is going to getById object ID: 56 (memory before: 6.24 mb / 6.5 mb)
Is going to getById object ID: 58 (memory before: 6.49 mb / 6.75 mb)
Is going to getById object ID: 60 (memory before: 6.65 mb / 6.75 mb)
Is going to getById object ID: 94 (memory before: 6.87 mb / 7 mb)
Is going to getById object ID: 97 (memory before: 7.16 mb / 7.5 mb)
Is going to getById object ID: 104 (memory before: 7.63 mb / 8 mb)
Is going to getById object ID: 105 (memory before: 8.22 mb / 8.5 mb)
Is going to getById object ID: 107 (memory before: 8.38 mb / 8.5 mb)
Is going to getById object ID: 108 (memory before: 8.8 mb / 9 mb)
Is going to getById object ID: 109 (memory before: 9.44 mb / 9.75 mb)
Is going to getById object ID: 110 (memory before: 9.6 mb / 9.75 mb)
Is going to getById object ID: 111 (memory before: 9.98 mb / 10.25 mb)
Is going to getById object ID: 112 (memory before: 10.06 mb / 10.25 mb)
Is going to getById object ID: 113 (memory before: 10.57 mb / 10.75 mb)
Is going to getById object ID: 114 (memory before: 10.86 mb / 11 mb)
Is going to getById object ID: 115 (memory before: 11.12 mb / 11.25 mb)
Is going to getById object ID: 116 (memory before: 11.38 mb / 11.5 mb)
Is going to getById object ID: 117 (memory before: 11.55 mb / 11.75 mb)
Is going to getById object ID: 118 (memory before: 11.72 mb / 12 mb)
Is going to getById object ID: 119 (memory before: 12.23 mb / 12.5 mb)
Is going to getById object ID: 120 (memory before: 12.36 mb / 12.5 mb)
Is going to getById object ID: 121 (memory before: 12.52 mb / 12.75 mb)
Is going to getById object ID: 122 (memory before: 12.79 mb / 13.25 mb)
Is going to getById object ID: 123 (memory before: 12.99 mb / 13.5 mb)
Is going to getById object ID: 124 (memory before: 13.07 mb / 13.5 mb)
Is going to getById object ID: 126 (memory before: 13.58 mb / 14 mb)
Is going to getById object ID: 127 (memory before: 13.81 mb / 14.25 mb)
Is going to getById object ID: 128 (memory before: 14.04 mb / 14.5 mb)
Is going to getById object ID: 129 (memory before: 14.27 mb / 14.75 mb)
Is going to getById object ID: 130 (memory before: 14.36 mb / 14.75 mb)
Is going to getById object ID: 131 (memory before: 14.82 mb / 15.25 mb)
Is going to getById object ID: 132 (memory before: 14.92 mb / 15.25 mb)
Is going to getById object ID: 914 (memory before: 15.01 mb / 15.5 mb)
Is going to getById object ID: 936 (memory before: 15.29 mb / 15.75 mb)

And same with fetch directly (nocache=1 in URL):

Is going to getById object ID: 46 (memory before: 3.65 mb / 4 mb)
Is going to getById object ID: 48 (memory before: 5.77 mb / 6 mb)
Is going to getById object ID: 50 (memory before: 6.25 mb / 6.5 mb)
Is going to getById object ID: 52 (memory before: 6.72 mb / 7 mb)
Is going to getById object ID: 54 (memory before: 7.04 mb / 7.25 mb)
Is going to getById object ID: 56 (memory before: 7.57 mb / 8.25 mb)
Is going to getById object ID: 58 (memory before: 7.78 mb / 8.25 mb)
Is going to getById object ID: 60 (memory before: 7.93 mb / 8.5 mb)
Is going to getById object ID: 94 (memory before: 8.12 mb / 8.75 mb)
Is going to getById object ID: 97 (memory before: 8.37 mb / 9 mb)
Is going to getById object ID: 104 (memory before: 8.37 mb / 9 mb)
Is going to getById object ID: 105 (memory before: 8.37 mb / 9 mb)
Is going to getById object ID: 107 (memory before: 8.37 mb / 9 mb)
Is going to getById object ID: 108 (memory before: 8.74 mb / 9.25 mb)
Is going to getById object ID: 109 (memory before: 8.74 mb / 9.25 mb)
Is going to getById object ID: 110 (memory before: 8.89 mb / 9.5 mb)
Is going to getById object ID: 111 (memory before: 8.89 mb / 9.5 mb)
Is going to getById object ID: 112 (memory before: 8.96 mb / 9.5 mb)
Is going to getById object ID: 113 (memory before: 8.96 mb / 9.5 mb)
Is going to getById object ID: 114 (memory before: 8.96 mb / 9.5 mb)
Is going to getById object ID: 115 (memory before: 9.18 mb / 9.75 mb)
Is going to getById object ID: 116 (memory before: 9.18 mb / 9.75 mb)
Is going to getById object ID: 117 (memory before: 9.33 mb / 9.75 mb)
Is going to getById object ID: 118 (memory before: 9.48 mb / 10 mb)
Is going to getById object ID: 119 (memory before: 9.48 mb / 10 mb)
Is going to getById object ID: 120 (memory before: 9.59 mb / 10 mb)
Is going to getById object ID: 121 (memory before: 9.73 mb / 10.25 mb)
Is going to getById object ID: 122 (memory before: 10.1 mb / 10.5 mb)
Is going to getById object ID: 123 (memory before: 10.28 mb / 10.75 mb)
Is going to getById object ID: 124 (memory before: 10.35 mb / 10.75 mb)
Is going to getById object ID: 126 (memory before: 10.35 mb / 10.75 mb)
Is going to getById object ID: 127 (memory before: 10.55 mb / 11 mb)
Is going to getById object ID: 128 (memory before: 10.74 mb / 11.25 mb)
Is going to getById object ID: 129 (memory before: 10.75 mb / 11.25 mb)
Is going to getById object ID: 130 (memory before: 10.83 mb / 11.25 mb)
Is going to getById object ID: 131 (memory before: 10.83 mb / 11.25 mb)
Is going to getById object ID: 132 (memory before: 10.91 mb / 11.5 mb)
Is going to getById object ID: 914 (memory before: 10.99 mb / 11.5 mb)
Is going to getById object ID: 936 (memory before: 10.23 mb / 11.75 mb)

----------------

As you can see even with the cross-reference (no lazy loading used) all seems okay (fetched cache use a little more memory because of the unserialize i think).

So why after several days we got some object using more memory when fteched from the cache than currently as they are fetched from the cache ?
Is there something appended at each call and specifically concerning cross-reference, so after somedays it take to much memory ?

**Comment by brusch** [comment]
There are only particular objects that cause an abnormal increase of the memory, eg: 

Is going to getById object ID: 46 (memory before: 3.47 mb / 3.75 mb)
Is going to getById object ID: 48 (memory before: 36.19 mb / 44.25 mb)

Is going to getById object ID: 112 (memory before: 43.91 mb / 44.75 mb)
Is going to getById object ID: 113 (memory before: 75.75 mb / 83.75 mb)

So it would be interesting what the content of these cache items is eg. ID 48 and 113. So maybe when this happens again please create a dump of the data in the cache of the items causing this massive hops. 

Thanks!

**Comment by Yivan** [comment]
Yes, I arrived to the same conclusion. As explained, i manage to make a dump via var_dump (using ob_start) and store in a file. It worked for ID 50 (but has no problem), so I got only this one. I tried those mentionned, but even with 3048Mo for memory limit (i cannot go upper) I got a memory_limit when trying to dump 46, 48 and 112. Next time I will try to dump them directly from Redis.

Here a more detailled for those one i checked especially (before cleaning the cache), memroy before unserialize and after unserialize:

Is going to unserialize object ID: 46 (memory: 8.04 mb / 8.75 mb)
Is unserialized object ID: 46 (memory: 40.76 mb / 44.25 mb)

Is going to unserialize object ID: 112 (memory: 48.14 mb / 49.75 mb)
Is unserialize object ID: 112 (memory: 79.99 mb / 83.5 mb)

Is going to load object ID: 118 (memory: 84.09 mb / 85 mb)
Is loaded object ID: 118 (memory: 93.2 mb / 94.75 mb)
Is going to unserialize object ID: 118 (memory: 93.2 mb / 94.75 mb)
... fatal error... no more memory to unserialize it.

And 46, 112 and 118 are cross related (2 cross related each one).
46 > 112 and 118
112 > 46 and 118...

For now, I will add a lazy loading for the related field, and I will keep you informed if it reproduce.
It will maybe correct the problem, but it is always a myster for me why the same object is taking several day after so much more memory to unserialize. Maybe a problem in our code making the object cached big under some circunstance (a bug which occurs sometimes so it store the backtrace, etc... in the cache maybe...).
As you say it only an export of those object could help so I will try to do it next times.

Thanks for all!

**Comment by brusch** [comment]
Yes, please dump it directly from redis, so the serialized contents that are actually stored in redis. 
That would help a lot. 

We did already some improvements on the memory consumption, see: 
https://github.com/pimcore/pimcore/commit/9b836f5a8b2eebf8d9613066283111456fbc3e6a
https://github.com/pimcore/pimcore/commit/561b4cd59f45f92877fa4a12d3bcae3125daa27b
https://github.com/pimcore/pimcore/commit/bf01893859e0bb53428e2e8a64fe53b64b906b4c

Maybe this makes it any better for you. 
To try it you can just use the latest build of pimcore.

**Comment by Yivan** [comment]
Yes maybe the improvment will correct the problem (but they seems to be for Document object, and actullay it is an Object object). But as it is a production application, we will wait for the stable version. As soon as it is released we will update it.
Thanks again for all the help!

**Comment by brusch** [comment]
There was actually also a fix for objects (image & image advanced).

**Comment by Yivan** [comment]
You can close this task, thanks.

It seems it come back from some objet referencing other object wich reference original object (making a circle recursion). We put those object href field in lazy loading, and now there seems to be no problem.

**Comment by brusch** [comment]
Thanks
