### ISSUE TITLE
[Pimcore4] Popup on Empty Datefield closes in IE & Edge

### ISSUE THREAD

**Issue by ThomasKeil** [pimcore/pimcore#2164]
Empty DateFields can't be populated with the calendar popup in IE and Edge, it closes immediately when moving the pointer.
This is not the case with filled out DateFields

Please see attached movie.
[20171025_150426.mp4.zip](https://github.com/pimcore/pimcore/files/1414679/20171025_150426.mp4.zip)

**Comment by weisswurstkanone** [comment]
fixed in build 4105

**Comment by ThomasKeil** [comment]
Great, thanks a lot!
