### ISSUE TITLE
[Pimcore4] Multihref (advanced) not saving relations to database

### ISSUE THREAD

**Issue by nahilep** [pimcore/pimcore#2167]
# Bug Report
 
### Expected behavior 
When creating a new class for a dataobject, adding the component "Multihref Advanced" and connecting objects through this field, I would expect to have the column in the view object_1 have the relation saved. E.g. ,object|1,
  
### Actual behavior  
  The column stays empty i.e. ",," (" excluded)

### Steps to reproduce  
  On a clean install create a class and add a multihref advanced data component then create 2 objects and link the second with the first object

~~Switching to a normal multihref helped and the column was filled~~
Edit: This helped on my project, but not on the clean install I have at the moment. Here the column switched from ",," to null
Other changes like renaming the object are visible in the database column

**Comment by weisswurstkanone** [comment]
fixed in build 4105
