### ISSUE TITLE
Maintenance link broken

### ISSUE THREAD

**Issue by ascheider** [pimcore/pimcore#2170]
Pimcore Platform (5.0.1|133)

If maintenance cronjob is not running, there is icon in pimcore backend
![image](https://user-images.githubusercontent.com/6016485/32091438-7774ca92-baf4-11e7-8c13-e3d0208e0695.png)
By follow icon link, we get 404 page instead on cronjob document page
![image](https://user-images.githubusercontent.com/6016485/32091493-b8deab38-baf4-11e7-8948-391b10a3c9d1.png)

**Comment by weisswurstkanone** [comment]
already fixed via 
https://github.com/pimcore/pimcore/commit/72f3b6f9d8205876f10590ed80cd6f5e4cad7095

8.10.2017
