### ISSUE TITLE
Safari 11 doesn't show the legend titles

### ISSUE THREAD

**Issue by jorisros** [pimcore/pimcore#2178]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [x] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [x] There's no existing ticket for the same issue
  
### Expected behavior 
The fieldset should be having a readable legend and a working collapsible content. 
### Actual behavior  
When a fieldset has been used in Safari 11 the legend is unreadable and it is impossible to collapse the field. This occur in Pimcore 4 & 5.
<img width="782" alt="screen shot 2017-10-31 at 01 50 09" src="https://user-images.githubusercontent.com/752283/32202694-ace8cd44-bdde-11e7-96fb-3ef358c772f2.png">
 
### Steps to reproduce  
Open the 'System settings' in Safari 11 browser.

**Comment by jorisros** [comment]
Same bug occurred in EXTJS 6.5 and is classified as EXTJS-26380. See: https://www.sencha.com/forum/showthread.php?423768-ExtJS-6-5-0-Fieldset-legend-are-not-visible-in-Safari-11

**Comment by jorisros** [comment]
Please see the following pull requests: 
#2179 for Pimcore5
#2180 for Pimcore4

**Comment by maff** [comment]
PRs merged, thanks!
