### ISSUE TITLE
REST POST object pimcorev5 404 error

### ISSUE THREAD

**Issue by kylepwarren** [pimcore/pimcore#2188]
I'm digging through the log files but nothing is really sticking out as a reason why I'm getting a 404 error for a webservice call that was working fine in 4.x versions of PIMcore. Other requests work (GET).

I tried increasing server post size and input limits. 
I see the requests in logs, but have not found a point where an error is thrown, or why the 404 is caused.

Can you think of anything I should check / is there anything that's changed, specifically about POST web service object requests? 

It is a new server, so there's a chance it could be something like not having an apache module enabled.. 

Any ideas?

Thanks

**Comment by kylepwarren** [comment]
Found the problem, and what seems to be a problem with the documentation now:
"{\"success\":false,\"msg\":\"Object 0 does not exist\",\"code\":-1}"

removing the id attr all together worked. they doc still says set to 0 is ok

**Comment by kylepwarren** [comment]
Closely related: When posting [data]object json to the webservice handler, occasionally get: "Invalid json message received", though I take the string, and decode it in a browser dev console just fine... hmmm

**Comment by kylepwarren** [comment]
Appears to no longer be happy with JSON serialized data - application/x-www-form-urlencoded
Seems to want only stringified - application/json

**Comment by kylepwarren** [comment]
Back at it. I almost think it's some sort of post related encoding problem.
run down:
-same requests work fine on pimv4.x
-get various json format errors on create object web service requests, lately this one a lot: JSON_ERROR_CTRL_CHAR
-if I copy and paste the json string to the same server, json_decode works fine, no errors

**Comment by kylepwarren** [comment]
Solved: program posting was using utf8y encoding, that is utf8 with BOM.
I was able to change the encoding luckily.
I guess v4.x checked for this? seems like a good thing to check for.

**Comment by kylepwarren** [comment]
Of course there were changes I made along the way, so can't exactly pinpoint what the original problem was, but in general it was an encoding problem. An encoding problem that v4.x didn't have

**Comment by fashxp** [comment]
Hi,
is there anything left open or everything resolved? 
Thanks for info...
