### ISSUE TITLE
RFC - Add event before object is loaded in UI

### ISSUE THREAD

**Issue by iceburg1991** [pimcore/pimcore#219]
## Problem
When an object is opened in de backend I want Pimcore to load an object specific layout (not class level specific). I want to manipulate the loaded layout. The only thing I can currently do is specify a class specific default layout, I need an object specific layout. 

## Usecase  
In my case I use the custom layouts for specific product layouts. So object A of type/class 'product' should load custom layout 1 named 'hardware' and object B of type/class 'product' should load custom layout 2 named 'software'. The reason that I don't use different objects is because I want 1 attribute set which all different product types can use to prevent duplicate attributes. So when a product object is saved it should save the selected layout for the specific object ( custom functionality I made). Pimcore has an event called 'preSendData' which is called right before al the object data is send. Although this is nice, I want to manipulate the loaded layout when you open a object. 

## Solution
In the /Pimcore/models/Object/ObjectController.php add an event so the object data can be manipulated before the object is loaded in de GUI. That way one of the things is that I can change the layout it should load. This would be a simple but great improvement for pimcore.
I have added the next code/event at the start of the getAction() function in the ObjectController to solve my problem. Maybe you can add an event ( similar to the one I use ).
<pre><code>
public function getAction(){
   $object = "";
   $returnValueContainer = new Model\Tool\Admin\EventDataContainer($this);
   \Pimcore::getEventManager()->trigger("admin.object.get.preCreateData", $this, [
        "object" => $object,
        "returnValueContainer" => $returnValueContainer
    ]);
</code></pre>

**Comment by dpfaffenbauer** [comment]
I don't understand why preSendData doesn't fit your needs? preSendData is called right before the data is sent to the GUI.

**Comment by brusch** [comment]
This was also my first thought.
@iceburg1991 have you already tried "preSendData"? What's the problem with this hook?

**Comment by iceburg1991** [comment]
I have tried the 'preSendData' hook but even when I get the Request Uri changed in the event object with a 'layoutId' parameter, I can't get the loaded layout different from master. Maybe I didn't change the right attribute in the event object, but I tried a lot of attributes without succes. This new event solves this problem by simply add the next lines in the function which hooks the new event:
<pre><code>
\Pimcore::getEventManager()->attach("admin.object.get.preCreateData", array($this, "customLayout") );

public function customLayout( $event ){
$object  = $event->getTarget();
$object->setParam("layoutId", $layoutId);
</code></pre>
Where $layoutId is the id of the wanted layout

**Comment by iceburg1991** [comment]
So can someone show me an example how I can achieve to change the layoutId with the 'preSendData' event so that a different layout is loaded then the master layout?
