### ISSUE TITLE
Probleme install.php with last stable release download

### ISSUE THREAD

**Issue by souvrard** [pimcore/pimcore#2191]
Hello,

I just downloaded the  pimcore-stable.zip from the official site (Pimcore 5) and I have problems installing it (on Debian 9 with php 7):

When I open http://localhost/install.php =>

Fatal error: Default value for parameters with a class type hint can only be NULL in /var/www/pimcore/pimcore/lib/Pimcore.php on line 146

If I remove "bool"  => setDebugMode($debugMode = true)...

I obtain:
Parse error: syntax error, unexpected ':', expecting ';' or '{' in /var/www/pimcore/pimcore/lib/Pimcore.php on line 252

What is the problem ? my php version ? the package I have downloaded ?

I just followed the documentation:
- download the zip archive,
- extract it in a directory,
- set apache docroot on the "web" directory,
- create a database, user.....

and open http://localhost/install.php

Thanks for your help (and sorry for my english, I am french)

**Comment by maff** [comment]
Are you sure your webserver is running PHP 7?

**Comment by souvrard** [comment]
arfff sorry !!php7 cli is the default, php5 apache2 module was the default :-(It is correct now.... but I have to go with others errors (intl extension not installed).....thank you for your answerCordialement,Stéphane OUVRARDDéveloppement webRAUTUREAU APPLE SHOES85130 LA GAUBRETIERE06 46 41 39 01-----Mathias Geat <notifications@github.com> a écrit : -----A : pimcore/pimcore <pimcore@noreply.github.com>De : Mathias Geat <notifications@github.com>Date : 03/11/2017 08:47Cc: souvrard <souvrard@rautureau-appleshoes.fr>, Author <author@noreply.github.com>Objet : Re: [pimcore/pimcore] Probleme install.php with last stable release download (#2191)Are you sure your webserver is running PHP 7?
