### ISSUE TITLE
Requirements Check: PHP and Composer fails

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#2192]
# Bug Report

We yesterday set up about 50 Installations of the latest Pimcore built on XAMPP in windows on different machines and experienced that in at least 10% of the installations the "Check Requirements" functionality in the installation window showed PHP and Composer as red, even though PHP and Composer was installed and added to the PATH variable of the systems. So the execution of `php -v` or `composer --version` in the terminal showed the according correct results. The installation itself worked without issues, but the check was interpreting the requirements wrong.

**Comment by tgross-m-s** [comment]
I have the same problem with all of my pimcore installations on windows. It looks like pimcore tries to check if commands like `php` or `composer` are available with some symfony functions that are not fully compatible with windows.
`composer` is only really needed to update pimcore on the commandline: `php bin/console pimcore:update ...`.
However, I strongly recommend to **not** update pimcore on windows because it will break your installation for several reasons.

It is safe to say that pimcore is no longer compatible with windows.

**Comment by Thamakil** [comment]
You can get around the requirements check by adding the following line to your parameters.yml:
`pimcore_executable_composer: composer`
However: the **update process will still fail** on windows.
The reason are lines like this one :
`$process = new Process($composerPath . ' update ' . implode(' ', $composerOptions) . ' -d ' . PIMCORE_COMPOSER_FILE_PATH);`
This results in the following command being executed:
`composer update -someoptions -d C:\Path\To\Project\Root`
Under windows in this case the backslashes seem to be ignored by composer.
So you will get the following exception from composer:
`[RuntimeException] Invalid working directory specified, C:PathToProjectRoot does not exist.`
So the command should actually look like this (note the quotes):
`composer update -someoptions -d "C:\Path\To\Project\Root"`
What I currently do not know is if that is the only problem with updating on windows and how things would work on other systems if the command would be modified as mentioned above.

**Comment by israasalameh95** [comment]
how to solve this issue ? !! it doesnt appear in version 5 on windows , but on version 4.6 yes its appear

**Comment by bbak** [comment]
@israasalameh95 Have a look at the file `\website\config\di.example.php` in your Document-Root. You can set all paths to the various executables Pimcore expects to find, if you save this file as `di.php` in the same folder and change the appropiate setting, like this one `"pimcore.executable.php" => "/usr/local/custom-php/bin/php",` 
You should remove the entries that you don't use or which are correctly detected by the autodetection.

**Comment by brusch** [comment]
This should be fixed by abbe44d414dbe262ad24afc3fffae16406472ea0
