### ISSUE TITLE
[Documents] Add Navigation Name to Folders

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#2195]
Add the navigation name as a default property to folders: 
![image](https://user-images.githubusercontent.com/142037/32431190-bd4fb6c2-c2d2-11e7-91a8-0abafe5b30cd.png)

Folders can then be used as structural components in navigations (headlines, ...) as shown below: 
![image](https://user-images.githubusercontent.com/142037/32431145-84eddfde-c2d2-11e7-90c0-5034021931eb.png)

**Comment by brusch** [comment]
Navigation properties available on folders: 
- name
- exclude 
- css class
- title

**Comment by weisswurstkanone** [comment]
build 160
