### ISSUE TITLE
[Translations] Priorities of `admin` Translations

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#2197]
It should be possible to override translations of Pimcore in bunldes using the default Symfony translations, see also #2165 

Priorities should be: 
1. pimcore stock translations
2. other bundles
3. pimcore admin translations

**Comment by dpfaffenbauer** [comment]
Wasn't that already the case? What annoys me the most is, that when a translation is missing in the symfony translations, Pimcore will add it to the admin translations, but as an empty string. If I add it then to the Symfony Translations, it still uses the Pimcore Admin Translation. Would it be possible to add the translation, but check if its empty or not?

**Comment by brusch** [comment]
No, that wasn't the case, Symfony translations defined in the `admin` domain were overridden by the Pimcore stock translations. 

> If I add it then to the Symfony Translations, it still uses the Pimcore Admin Translation.
That should be fixed now with  #4116
