### ISSUE TITLE
Creation of new order object does not take Pimcore Mapping into consideration

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#2198]
Let's say I have a class im Pimcore called MyOrder, which extends the OnlineShopOrder class.

By default, at the very first creation of the order object within the getNewOrderObject method of the OrderManager, the object is initialized as follows:

    protected function getNewOrderObject() {
        $orderClassName = $this->getOrderClassName();
        if(!\Pimcore\Tool::classExists($orderClassName)) {
            throw new \Exception("Order Class" . $orderClassName . " does not exist.");
        }
        return new $orderClassName();
    }
return new $orderClassName(); does not consider the Pimcore class mapping correctly, so the instance will be of type OnlineShopOrder instead of MyOrder. It would be better to call a factory and delegate to Pimcore?

See pimcore/customer-data-framework@0bfd860 as an example for that.

**Comment by weisswurstkanone** [comment]
why not do it this way ?

                $className = 'Pimcore\\Model\\DataObject\\' . ucfirst($wsDocument->className);
                $object = \Pimcore::getContainer()->get('pimcore.model.factory')->build($className);
