### ISSUE TITLE
Store object/document/asset tree level information

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#220]
Add DB column for documents, objects and assets - o_treeLevel or o_pathLevel or o_level
This will allow easy level-based SQL conditions/orders when retrieving objects and object collections (listing) based on the tree level

**Comment by brusch** [comment]
There's already a column for the "path", which content should be in the "treeLevel" column and for which use case this would make sense?

Thanks for clearifying!

**Comment by kanevbg** [comment]
Since we have a tree view by default in Pimcore, it may be useful to make custom logic based on the tree and the level of each instance of object/document/asset is.

If we have a object with path /products/test/ then the treeLevel must equal 2.

Here is one use case: Retrieve a object instance of type Category which is in the most possible deepest level.

Here we might come with a kind of SQL sorting by o_treeLevel descending.

**Comment by brusch** [comment]
what about ```ORDER BY LENGTH(path) DESC´´´ ?

**Comment by kanevbg** [comment]
/a/b/c/ -> 7
/abcdeabcde/ -> 12
second is going before first but it is actually shallower

**Comment by dpfaffenbauer** [comment]
what about split and count with mysql?

**Comment by kanevbg** [comment]
There IS way to calculate it but these calculations will become expensive that is why I considered it will be useful to have it stored as unsigned int

**Comment by dpfaffenbauer** [comment]
A quick fix for you: Write your own plugin that hooks into the save methods of asset/document/object and write the level to the database.

@brusch: this feature could be useful and would also be easy to implement.

**Comment by bbak** [comment]
Yes, a triple self-join in case of a 'adjacency list' like Pimcore uses. Perhaps converting that to 'nested set' would be better in the long run.

B. 


   Kostadin A. --- Re: [pimcore] Store object/document/asset tree level information (#220) --- 
    Von:"Kostadin A." <notifications@github.com>An:"pimcore/pimcore" <pimcore@noreply.github.com>Datum:Mo., 17.08.2015 16:47Betreff:Re: [pimcore] Store object/document/asset tree level information (#220)
  
  There IS way to calculate it but these calculations will become expensive that is why I considered it will be useful to have it stored as unsigned int

**Comment by brusch** [comment]
I know how easy it is to implement ;-) But the question is: is there really a real use for many users, not just for one particular case - we also have to ensure pimcore stays maintainable and unfortunately we cannot implement everyones wishes :)

**Comment by kanevbg** [comment]
I am not sure that there will be important use cases relevant to the level of the nodes for the core but will be useful in some cases when custom (non-core) features have to be implemented and maybe for the plugins. In my opinion this information is great to be stored for entities which are presented as tree nodes in the system using paths like in Pimcore.

**Comment by brusch** [comment]
Sorry, I still see no concrete use case. Why should I want to get all categories of the most deepest tree level? Or wich advantage should I have to get all nodes of the 3rd level?

**Comment by kanevbg** [comment]
Here is one use case currently I have found while working "Generate navigation menu from categories but take in account that the frontend GUI have no capabilities for more than 2 levels of navigation so limit the data retrieved from the DB"

If we have stored the level of each node we can set condition WHERE o_treeLevel <= $levelLimit

This way we retrieve with one query all the required nodes and can use the collection(Listing) to generate the navigation. Currently I am making this kind of navigations by using getChilds method which makes additional queries.

**Comment by kanevbg** [comment]
It seems to me that the level of a tree node is abstract property of tree navigation which should persist even if it is more rarely needed.
