### ISSUE TITLE
Bundle Generator needs lowercase for js links

### ISSUE THREAD

**Issue by ctrl-s** [pimcore/pimcore#2200]
Wrong asset links are created by the Bundle Generator.

Example:
We let the generator build a bundle which is called: AsdQwertBundle.
A AsdQwertBundle class is generated in 'src/AsdQwertBundle/AsdQwertBundle.php' and the link to the startup.js inside of the getJsPath method is predefined like:
'/bundles/AsdQwert/js/pimcore/startup.js'

The problem with that is that Symfonys AssetsInstallCommand which creates the relative links in the /web directory, uses a strtolower when creating the bundle folder.

This way the startup.js can't be loaded because the predefined path is wrong.
The Bundle Generator has to provide the bundlename part for the link in lowercase.

Reproduce:
Use 'bin/console pimcore:generate:bundle' in CLI to build a bundle.
Enable the bundle in the extension backend.
Notice the 404 errors in the browsers debug interface while loading the Pimcore Backend.

**Comment by dpfaffenbauer** [comment]
already fixed here https://github.com/pimcore/pimcore/commit/cdef5cc132ab5100a97f8cc249c3297bbc5ec326

**Comment by ctrl-s** [comment]
Oh nice. Sorry I couldn't find it by searching through the issues :)

**Comment by maff** [comment]
The issue was this one: #2112
