### ISSUE TITLE
Symfony form inside Snippet is never submitted and method in request object is GET

### ISSUE THREAD

**Issue by tgrueber** [pimcore/pimcore#2205]
## Please answer the following questions 
Is there a way to use a Symfony form inside a snippet? Actually the form is never submitted and the method of the request object inside the controller action is GET.

**Comment by brusch** [comment]
Is this really a Pimcore issue? 
Can you provide some more details on it? 
Thanks!

**Comment by dpfaffenbauer** [comment]
Guess that snippets create a new Sub-Request, to solve your issue, inject the RequestStack into your controller and call ->getMasterRequest. That should give you the main request.

**Comment by tgrueber** [comment]
That's it! Thank you Dominik!
