### ISSUE TITLE
Debug bar in frontend is super scary for users

### ISSUE THREAD

**Issue by John5** [pimcore/pimcore#2210]
In Pimcore 5 when the debug mode is enabled something that people describe as a "a huge black bar" appears on every page in the frontend.

Even when debug mode is limited to a single IP address, the consultants, marketing and HR department and CEO in the same office all freak out by this scary thing staring back at them while they look at their website.

Possible solutions that I came up with that would improve the situation:

1. Collapse debug bar by default, requiring a click to see it (and save this state in the session)
2. Allow a custom message to be displayed in the bar, for example "Don't panic! This debug bar is only visible from IP 123.123.123.123 and is temporarily enabled because John is working on the website".
3. Add an option to enable debug mode for IP address AND session or user agent for the person who enabled it so that other people with the same IP don't see it.

**Comment by dpfaffenbauer** [comment]
Can't agree with you. It's very easy to explain the customer what that means, and that it disappears as soon as the website goes live.

**Comment by brusch** [comment]
@John5 you can disable the debug bar in your `app/config/config/config.yml` using the following config: 

```yml
web_profiler:
    toolbar: false
```

or you can run your app in 2 different environments, one with the debug toolbar on, and one without the debug bar (using 2 different hostnames)
