### ISSUE TITLE
Class Export/Import - Make Class-Import & Export linkGeneratorReference aware

### ISSUE THREAD

**Issue by AlternateIf** [pimcore/pimcore#2212]
Currently the JSON-Dump does not contain any information about a potentially set linkGeneratorReference. I guess that due to that there's also no way of setting the linkGeneratorReference by importing a Dump.

The linkGeneratorInterface can be retrieved/set with the Definition object though.

occured on build 143

@maff

**Comment by weisswurstkanone** [comment]
fixed in build 145
