### ISSUE TITLE
deployment:classes-rebuild throws exception when using options provider which refers to other classes

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#2214]
Imagine you have two classes:
 - 1: BlogArticle
 - 2: BlogCategory

The BlogArticle now has a ```select``` with a OptionsResolver. The OptionsResolver refers to ```BlogCategory\Listing``` to resolve a list of categories.

Now we want to deploy our application to staging, when calling ```deployment:classes-rebuild```, pimcore throws an exception ```class BlogCategory\Listing not found```. Since the BlogCategory has not yet been created.

Only solution so far: use ```class_exists``` and check if ```BlogCategory\Listing``` already exists. This conceptual problem will potentially kill a lot of time on automatic deployed systems. Since this is kinda dangerous, we should address it and find a way of solving it. 

In the mean time, ```class_exists``` is a valid, but dirty, solution, but the OptionsResolver should not get called on ```deployment:classes-rebuild```

**Comment by fashxp** [comment]
any idea how to solve this?

**Comment by dpfaffenbauer** [comment]
not calling the OptionsResolver on layout creation ;), only call it when in Admin Context.

**Comment by dpfaffenbauer** [comment]
@brusch sure that really fixes that? running a command is different than being in Admin.

**Comment by dpfaffenbauer** [comment]
Will let you know if it still fails.
