### ISSUE TITLE
[Admin Translations] Do not work in combination with classification store

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2215]
Labels of classification store get not translated

**Comment by kubaplas** [comment]
@fashxp you mean that labels are not translated in the Classification Store editor? What about values (e.g. in select)?
If it's a bug, we could try to fix it - I've stumbled upon it today.

**Comment by fashxp** [comment]
hmm strange ... just retried it, and every thing got translated properly now - labels, and also select values.

**Comment by dpfaffenbauer** [comment]
Guess that’s the same that happens to me often: clearing shared translations and cache often helps when having problems with translations.

**Comment by fashxp** [comment]
hmm, but in this case not shared translantions but admin translations are relevant - they should be a seperate catalog

**Comment by dpfaffenbauer** [comment]
thats right, but it seems for me to work :D No idea why, never had the time to investigate. Maybe it can help you identify the problem correctly. As far as I know: Symfony stores translation in the cache, right? So I guess there could be the reason.
