### ISSUE TITLE
Pimcore Installer should honor Symfony path Layout Settings

### ISSUE THREAD

**Issue by bbak** [pimcore/pimcore#2216]
### Expected behavior 
Symfony [allows to change the Path Layout](https://symfony.com/doc/current/configuration/override_dir_structure.html#override-the-web-directory) in the extra Section of `composer.json` (along with renaming the folders of course):
```
  "extra": {
    "symfony-app-dir": "app",
    "symfony-bin-dir": "bin",
    "symfony-var-dir": "var",
    "symfony-web-dir": "public",
    "symfony-tests-dir": "tests",
    "symfony-assets-install": "relative",
    ....
   }
```
Pimcore should honor these Settings.

### Actual behavior  
Pimcore Installer (and perhaps other components also) ignore these settings. 

### Steps to reproduce

1. Do a composer install.
2. Rename Folder `web` to `public`
3. Change `extra.symfony-web-dir` accordingly
4. Run Web-Installer
-> Web-Installer want's to create `/base/dir/web/var/assets`, while it should be  `/base/dir/public/var/assets`

**Comment by brusch** [comment]
The problem with that is, that we need this information also at runtime here https://github.com/pimcore/pimcore/blob/c81f0713d1a90daf41e8bc7b7cb9a095018c88c1/pimcore/config/constants.php#L52 

and Composer doesn't provide this extra configuration outside of `composer.json`, so we'd have to parse `composer.json` on boostrap (even after the install process), which is imho a performance impact, which is not worth the small benefit it brings to the setup process. 

I haven't tried that yet, but additionally setting `PIMCORE_WEB_ROOT` either as ENV variable or in you `.env` prior the install process should work. Maybe you can confirm that.

**Comment by bbak** [comment]
Well, in the meantime we've get uset to the Pimcore 5 path-layout and updated our internal tooling.
