### ISSUE TITLE
Updated to 5.0.2 (Build 147) - Error when deleting Objects

### ISSUE THREAD

**Issue by davidhoeck** [pimcore/pimcore#2218]
Tried to delete objects, got the following errors:

``` 
Timestamp: Thu Nov 09 2017 16:04:20 GMT+0100 (CET)
Status: 500 | Internal Server Error
URL: /admin/object/delete
Message: An exception occurred while executing 'DELETE FROM gridconfig_favourites where objectId = 442':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bts_staging.gridconfig_favourites' doesn't exist
```

**Comment by weisswurstkanone** [comment]
Mhm, the table should have been created by this update script:
https://github.com/pimcore/pimcore/blob/master/update-scripts/144/postupdate.php

**Comment by davidhoeck** [comment]
Should i run it manually ?

**Comment by weisswurstkanone** [comment]
Hi, please provide the build/revision number before your update and I will try to reproduce this behavior. Thx!

**Comment by davidhoeck** [comment]
@weisswurstkanone I think the problem is that I updated Pimcore locally and pulled the changes on the remote server from the git repo. So the files are updated but the database is on the wrong revision number. 

I think the best option is that I just run the SQL manually on the server

**Comment by davidhoeck** [comment]
ran the mysql query from https://github.com/pimcore/pimcore/blob/master/update-scripts/144/postupdate.php manually .. everything working fine now.
