### ISSUE TITLE
New object data type - "Images/Gallery"

### ISSUE THREAD

**Issue by ckogler-elements** [pimcore/pimcore#2219]
# Feature Request 
Goal: Assign multiple assets to an object/brick... with an nice admin interface (image preview). 

Features:
- assign multiple assets
- image preview
- advaced image capabilities (hotspots...)
- sort / reorder
- supported in object / brick / fieldcollections

**Comment by Yivan** [comment]
Great new data type!
Just to know will a caption and an url be configurable ? (so we can add text to each image and a link to a page) => for the classic use case of a slider.

**Comment by weisswurstkanone** [comment]
The intention would be to use the asset's metadata (which of course is then also localized) for frontent purposes.

**Comment by LosHawlos** [comment]
Hi, found an error in this fantastic new data type:
**You can drop anything into the image drop zones**. This includes documents, assets folders, objects.
It perfectly shows the disabled mouse pointer but accepts the drop.
When dropping for example an asset folder to the new image zone it shows an error:
```
URL: /admin/asset/get-image-thumbnail?id=14&width=140&height=113&contain=true&
Message: Call to undefined method getThumbnailConfig in class Pimcore\Model\Asset\Folder
```
It doesnt show this error when dropping onto a previously added image or for some of the other document/object types.


Side question: Any change to get this as document tag too?

**Comment by weisswurstkanone** [comment]
added additional checks to drop handler (build159)

side question answer: not that I am aware of :-)

**Comment by brusch** [comment]
```text
Type error: Argument 1 passed to Pimcore\Model\DataObject\Data\ImageGallery::setItems() must be of the type array, null given, called in /home/xxxx/www/pimcore/models/DataObject/Data/ImageGallery.php on line 34
```
