### ISSUE TITLE
[DOCS] Csv export/import

### ISSUE THREAD

**Issue by mgomse** [pimcore/pimcore#2224]
According to https://talk.pimcore.org/t/question-import-csv-file-for-object/285 I think that it will be great to have some user documentation about how to use csv import/export.

Right now quite everything is to be read from code (https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php#L1035) but in the documentation, I wasn't able to find anything usefull for end-users.

**Comment by weisswurstkanone** [comment]
see 

https://github.com/pimcore/pimcore/issues/1796

and

https://github.com/pimcore/pimcore/pull/2271

**Comment by weisswurstkanone** [comment]
https://pimcore.com/docs/5.0.x/User_Documentation/Objects/CSV_Import/index.html

**Comment by brusch** [comment]
https://pimcore.com/docs/5.x/User_Documentation/DataObjects/CSV_Import/index.html
