### ISSUE TITLE
Integrate Google's new Global Site Tag (gtag.js)

### ISSUE THREAD

**Issue by bbak** [pimcore/pimcore#2226]
Google is heavily pushing it's new Tracking Script `gtag.js`, which seems to unify the old analytics.js/ga.js tracking code and Google Tag Manager.
A [Migration Guide](https://developers.google.com/analytics/devguides/collection/gtagjs/migration) as well as other Info is available from Google.

**Comment by brusch** [comment]
Add another  option additionally to `ga.js` and `dc.js`

![image](https://user-images.githubusercontent.com/142037/35683352-f12f605c-0763-11e8-9700-4369a9b4f44c.png)
