### ISSUE TITLE
Change the error message in update case failing at composer update

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2235]
The actual message is:

![update](https://user-images.githubusercontent.com/9025839/32794159-54daeb06-c968-11e7-8e10-459eb54026dc.png)

Maybe the good command should be given ? Aka:
`composer update -n -d /path/to/the/root/directory`
(with a mention to not run it has root to not break permissions. `su -l www-data -s /bin/bash` is a solution)

It will help people to update i think in case of problem at this stage.

**Comment by Yivan** [comment]
Can I add a pull request for this one ?
Changing the text "composer update" by "composer update -n -d /path/to/the/root/directory".

**Comment by brusch** [comment]
Every PHP developer should be familiar with composer, so I think this could lead to more problems than it solves (windows, systems, containerized environments, ...)
