### ISSUE TITLE
No debug.log

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2236]
During an update from Pimcore i got some error, but there where no file `debug.log` on the server at all.

![no-debug](https://user-images.githubusercontent.com/9025839/32794568-80d2590a-c969-11e7-985e-ca586bee8676.png)

I searched for `debug.log` all over the server (linux find command). Searching for the file `php.log` nothing too.
Nothing in /var/log of the system, nor the var/log of Pimcore.
Is monolog replacing it by some other file or is php error logging disabled ?
I found nothing about it on: https://github.com/pimcore/pimcore/blob/c75105230152bd263d43f8b0da9ae2a7c77579ea/doc/Development_Documentation/19_Development_Tools_and_Details/07_Logging.md
dev.log or prod.log doesn't contains the errors (i searched for the touch problem in the dev.log, but nothing).

Is there some special things to do to activate it ? If yes, it could be documented ?
Thanks.

(aside: maybe the update popin need some CSS modification so message doesn't overflow to the right of the popin, like on my screen capture above)

**Comment by Yivan** [comment]
I should add the phpinfo (from the pimcore menu):

![error_level](https://user-images.githubusercontent.com/9025839/32795309-962d7c4c-c96b-11e7-88b1-1d31d412f94e.png)

All seems ok at this level, but the file `php.log` doesn't exist after the install error like i explained.

**Comment by davidhoeck** [comment]
@Yivan The NGINX or Apache User is not able to write your `debug.log`

Please try the following commands in your project directory depending on your server setup: 

Apache: `sudo chown -R apache:apache . `
Nginx: `sudo chown -R www-data:www-data . `

**Comment by Yivan** [comment]
Thanks @davidhoeck but I think PHP should be able to write debug.log as dev.log and prod.log in var/log haven't any writing problem, and both of those are writen by www-data too.
With the same permission configuration I haven't any problem with Pimcore 4.

**Comment by fashxp** [comment]
which pimcore version are you using?

**Comment by Yivan** [comment]
@fashxp I used the last stable Pimcore 5 version downloaded from the website.

**Comment by fashxp** [comment]
in pimcore 5 there is no debug.log anymore. it is - depending on the environment - dev.log or prod.log ... so it is just the text that is misleading.

**Comment by fashxp** [comment]
created a new issue for that: https://github.com/pimcore/pimcore/issues/2288

**Comment by Yivan** [comment]
@fashxp I understand better thanks.

But i should add, that the error i had during the installation thewarning error i got wasn't logged in any log files in /var/log...
**Is logger desactivated/not installed during the installation of Pimcore ?** (and in the same time debug.log too so).

**Comment by fashxp** [comment]
normally logger should be available during installation. isn't there anything in the log? maybe you can start a discussion in our forums https://talk.pimcore.org/  and see if anyone had already a similar problem

**Comment by Yivan** [comment]
Ok thanks i will try to dig on it as soon i have time and expose my problem on the forum if i didn't found why.

**Comment by maff** [comment]
Regarding installation: the installer is a separate Symfony micro-application having its own cache and log files in `var/installer/cache` and `var/installer/logs`. See https://pimcore.com/docs/5.0.x/Development_Documentation/Getting_Started/Installation.html#page_Debugging-installation-issues.

**Comment by Yivan** [comment]
Thanks @maff you get it ; )
I haven't well read the documentation.

Maybe this issue should be reopened because in case of error during installation the error message is not good, and people will mayble like me hardly find the logs.

Please see update.js: https://github.com/pimcore/pimcore/commit/470feb2f54096cd7ade99c6c3b4a98ec80f3a508#diff-5f5ed561c2bcf36be0aad4baee925841R387

It say `Install of update fails, see log files in /var/logs for more details.` which is not true so and should be something like `Install of update fails, see log files in var/installer/logs for more details.` (or maybe better to tell more, even if /var/logs is not used, like: `Install of update fails, see log files in /var/logs or var/installer/logs for more details.`)

**Comment by maff** [comment]
@Yivan good idea, would you create a PR for that change?

**Comment by Yivan** [comment]
Ok great, i will do a PR for this!
