### ISSUE TITLE
Pimcore v4.6.3 update broken - ComposerAutoLoaderInit

### ISSUE THREAD

**Issue by jedis00** [pimcore/pimcore#2238]
Updated to v4.6.3 and have the following error. The interface will not load, gives a server 500 error. When I try to clear the cache from the command line, I get the following:

PHP Fatal error:  Class 'ComposerAutoloaderInit0f299cb7aff9c4ef51612174db89e6aa' not found in /webroot/vendor/autoload.php on line 7

```
<?php
// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return ComposerAutoloaderInitba82824dbdc822eda120ab38b0f72935::getLoader();
```

Going back to my copy of vendor/autoload.php from v4.6.2, I replaced the contents with the following and the error went away:

```
<?php
// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return ComposerAutoloaderInit61a9f296e4b63da064be1fd2b3530fcc::getLoader();

```

**Comment by fashxp** [comment]
anyone else facing this issue?

**Comment by dpfaffenbauer** [comment]
seems to be related to this: https://github.com/pimcore/pimcore/issues/1361
