### ISSUE TITLE
v4.6.2 and v4.6.3 will not load admin gui

### ISSUE THREAD

**Issue by jedis00** [pimcore/pimcore#2239]
The interface starts to load, the dots can be seen as the loading animation. Then, it goes away and the following errors are in the browser console.

The line 292 is the following: pimcore.globalmanager.add("document_types_store", store);

The line 739 is the following: pimcore.registerNS("pimcore.layout.refresh");

Clearing the cache from the command line does not get rid of the error.
```
Uncaught TypeError: pimcore.registerNS is not a function
    at startup.js?_dc=4099:739
(anonymous) @ startup.js?_dc=4099:739
startup.js?_dc=4099:292 Uncaught TypeError: Cannot read property 'add' of undefined
    at startup.js?_dc=4099:292
    at Object.invoke (ext-all.js?_dc=4099:22)
    at Object.doInvokeAll (ext-all.js?_dc=4099:22)
    at Object.invokeAll (ext-all.js?_dc=4099:22)
    at Object.unblock (ext-all.js?_dc=4099:22)
    at Object.triggerReady (ext-all.js?_dc=4099:22)
    at Object.checkReady (ext-all.js?_dc=4099:22)
    at Object.load (ext-all.js?_dc=4099:22)
    at Object.require (ext-all.js?_dc=4099:22)
    at Object.triggerReady (ext-all.js?_dc=4099:22)
```

**Comment by davidhoeck** [comment]
Have you checked the permissions on your files ? Had the almost the same error a time ago, because of missing permission ...

**Comment by jedis00** [comment]
@davidhoeck Yes, permissions are good. The issue is that the vendor/autoload.php composer randomly generated namespace does not match the namespace in vendor/composer/autoload_real.php. There is a mismatch. If I copy the namespace from autoload-real.php and replace it in autoload.php, it fixes the issue and Pimcore does load correctly.

I don't think this is the right fix though.

**Comment by fashxp** [comment]
anyone else facing this issue?

**Comment by cleggypdc** [comment]
Its quite a common prolem for us in deployment/dev. I've found there's a unique order to run console commands.

rm -f "/path/to/pimcore/website/config/autoload-classmap.php"

sudo -u apache-user php "/path/to/pimcore/cli/console.php" deployment:classes-rebuild -c -v

sudo -u apache-user php "/path/to/pimcore/cli/console.php" classmap-generator -v

sudo -u apache-user php "/path/to/pimcore/cli/console.php" cache:clear -v

Cheers!

**Comment by brusch** [comment]
@jedis00 is this really an issue of Pimcore? Doesn't sound like this is the case.
