### ISSUE TITLE
Email documents: allow address format: 'John Doe <john.doe@example.com>'

### ISSUE THREAD

**Issue by John5** [pimcore/pimcore#224]
Document_Email has the fields To/From/CC/BCC under the settings tab.
When entering an email address with a name in the following format:
`John Doe <john.doe@example.com>` it is sometimes silently ignored. When reading the property getCc() it is present, but when reading getCcAsArray() it is empty.

It would also be very nice if you could directly pass the input to Pimcore_Mail like this: `Pimcore_Mail->addCc('John Doe <john.doe@example.com>');`
without having to write additional code to separate the name and email address.

**Comment by dpfaffenbauer** [comment]
Pimcore_Mail inherits from Zend_Mail.

take a look at Zend_Mail (http://framework.zend.com/manual/1.12/en/zend.mail.adding-recipients.html). The Format 'John Doe <john.doe@example.com>' is invalid. You should do it like:

addCc->('john.doe@example.com', 'John Doe');

**Comment by John5** [comment]
The user interface only has one input field for multiple addresses. You
need a convention of formatting the names. Having the email in between
brackets is how the headers, and many email clients work.

**Comment by Hanadbeazi** [comment]
johndoe@example.com
