### ISSUE TITLE
Thumbnail config - sort by name + add grouping functionality

### ISSUE THREAD

**Issue by ckogler-elements** [pimcore/pimcore#2240]
# Feature Request 

In some projects there are quite a lot of thumbnail configs. Therefore it would be helpful to sort the configs by name in the admin interface (easier to find :-)). Maybe a grouping function (like it is in the Class editor tree) would also be helpful.

**Comment by weisswurstkanone** [comment]
Implemented the sorting. biold 151.

Instead of the grouping I could imagine something like a typeahead textfield filtering the tree down.
