### ISSUE TITLE
Order Manager produces "ghost order" for every valid order

### ISSUE THREAD

**Issue by davidhoeck** [pimcore/pimcore#2243]
My complete checkout / ordering flow is working fine, but since the last update every order has an "ghost" order with absolutely no informations __except the order number__ .

Anybody an idea, what the problem could be ? 

<img width="1041" alt="bildschirmfoto 2017-11-15 um 20 25 04" src="https://user-images.githubusercontent.com/24294584/32856920-826542ae-ca46-11e7-97bb-ceeab4a7ef12.png">

**Comment by fashxp** [comment]
strange ... are you calling [`getOrCreateOrderFromCart`](https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/OrderManager/IOrderManager.php#L58) on a empty cart somewhere?

**Comment by davidhoeck** [comment]
Ooops closed it sorry ... no I'm actually not calling this function anywhere in my code. 
Could it be that ` $checkoutManager->getOrder() ` produces an order if it is not existing yet ?

**Comment by fashxp** [comment]
yes, it calls the function mentioned above ... can you check, when this is called, and which cart is present there?

**Comment by davidhoeck** [comment]
Hmm yeah .. I think I know whats wrong. 

After the payment via the external payment provider I am redirecting to the checkout success where I call `$checkoutManager->getOrder()`. Because the POST push-confirmation of the PP is delayed, there is maybe no order available for this checkout, 'cause the order is only created in the method of the controller that handles the POST confirmation. 

Hmm... tricky things :-D

**Comment by davidhoeck** [comment]
So I checked the carts of a valid order and ghost order: 

Ghost: `Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\SessionCart_sesscart_5a0cc12ceaa88`
Valid: 
`Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\SessionCart_sesscart_5a0cc0bfb82b1`

So there are two different carts ...

**Comment by fashxp** [comment]
mhm, that explains it. 
but the order should be available with the moment you start the payment. in which order object the payment information is stored?

**Comment by fashxp** [comment]
any updates?

**Comment by brusch** [comment]
Closed due to inactivity - feel free to come back on this discussion at any time.
