### ISSUE TITLE
Issue with update script from build 3565

### ISSUE THREAD

**Issue by jedis00** [pimcore/pimcore#2244]
Running through updating a Pimcore v3.1.1 to the latest. It appears the update script in build 3565 is broken on the Pimcore update server: https://update.pimcore.org/v2/getUpdateFiles.php?for=3565

```
<?php
// get db connection
$db = Pimcore_Resource::get();
$db->query("ALTER TABLE `classificationstore_groups`
	DROP COLUMN `sorter`;
");
$db->query("ALTER TABLE `classificationstore_keys`
	DROP COLUMN `sorter`;
");
$db->query("ALTER TABLE `classificationstore_collectionrelations`
	MODIFY COLUMN `sorter` INT NULL AFTER `groupId`;
");
$db->query("ALTER TABLE `classificationstore_relations`
	MODIFY COLUMN `sorter` INT NOT NULL AFTER `keyId`;
");
```

It was marked resolved, but it is not.

#1261 Upgrade script 3565:
https://github.com/pimcore/pimcore/blob/pimcore4/update/archive_4000/3565/postupdate.php

Drop sorter column was already removed in a prior update.

**Comment by mturalenka** [comment]
can confirm, faced with the same issue while updating from 3.0.6 to 4.0.0
