### ISSUE TITLE
Pimcore class export/import uses ClassId instead of the class name for the allowed class in "Objects with metadata"-fields

### ISSUE THREAD

**Issue by TeamRocketYolo** [pimcore/pimcore#225]
When exporting classes containing "objects with metadata"-fields the resulting JSON does not contain the classname for the allowed classes for these fields but only the classId. When importing the same thing happens which makes it impossible to export these classes and properly import them on another pimcore instance.

**Comment by Thamakil** [comment]
Related to: #2515

**Comment by weisswurstkanone** [comment]
already fixed via #2515
