### ISSUE TITLE
Inherited checkbox values can not be overriden in child objects

### ISSUE THREAD

**Issue by afridlin** [pimcore/pimcore#2251]
# Bug Report

Version: 4.6.0 to 4.6.3

### Expected behavior 
Checkboxes in a Classification Store of an object that inherits from another object should keep their value when the object is saved.
  
### Actual behavior  
When an object is saved and reloaded it loses the changed value of the checkbox and falls back to the inherited value of its parent. This is only the case if the checkbox of the parent object is checked and you want to uncheck and override it in the child object. The other way round everything works as expected.

**Comment by weisswurstkanone** [comment]
See https://github.com/pimcore/pimcore/issues/201 for an explanation why this cannot work.
Also see https://github.com/pimcore/pimcore/issues/2083 for an alternative.
