### ISSUE TITLE
Variant grid view does not support classification store attributes

### ISSUE THREAD

**Issue by RasmusMagnell** [pimcore/pimcore#2252]
Replicated in the demo pim v.5.0.2.
  
The variant grid view crashes when adding a classification store attribute through the column configuration.

### Expected behavior 
  Opening the variant gridview on an object with classification store attributes and adding the classification store attribute through column configuration shows the grid with the added column.
### Actual behavior  
  Error popup appears with the message "No objectbrick given" and no rows are shown.
### Steps to reproduce  
1) Setup a classification store, group and a key, and add the key to the group.
2) Create a data object class that allows inheritance and variants.
3) Add a classification store attribute to the class
4) Create an object of the new class
5) Add the defined group to the object and save
6) Go the objects variant grid and add the classification store attribute in the column configuration

  ## Note
It is the getVariantsAction in VariantsController that does not support classification store attributes. It should work similar to the gridProxyAction in DataObjectController.php.

**Comment by weisswurstkanone** [comment]
fixed in build 151
