### ISSUE TITLE
Admin console plugin on the frontend has dissappeared after upgrade

### ISSUE THREAD

**Issue by asimlqt** [pimcore/pimcore#2253]
Hi,

We upgraded one of our sites from Pimcore 3 to 4. One of the things the client noticed was the pimcore plugin on the frontend which allows you to edit the page in the admin if you're logged in has dissappeared.

Is there any way to get this feature back?

**Comment by fashxp** [comment]
what feature do you mean exactly?

**Comment by dpfaffenbauer** [comment]
I guess the one in the frontend, where you could directly open the site within Pimcore. (https://github.com/pimcore/pimcore/blob/3.0.0/pimcore/lib/Pimcore/Controller/Plugin/AdminButton.php)

**Comment by brusch** [comment]
No, actually this feature was removed - sorry :|
