### ISSUE TITLE
[Bug - Pimcore 5] In search result, column values should not be clickable.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2256]
The bug is reproductible on the online demo of Pimcore 5.
If a search is made and the published checkbox are clicked, it make strange behavious...
Maybe the same bug can occurs with other columns having checkbox too or other type of field (i did test only with the published checkbox).

See this screenshot please:

![search-checkbox](https://user-images.githubusercontent.com/9025839/33092269-ef6216e0-cef9-11e7-85db-7439b329e9c9.png)

Thanks.

**Comment by weisswurstkanone** [comment]
thx, fixed in build 152
