### ISSUE TITLE
[New feature] Visual indicator of object progress % of filled data

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2257]
One feature asked when people compare Pimcore to some other PIM (like Akeneo or other which have this feature), is to able to check easily the progress % of the filled datas.

If done properly and usefull for user, i think we need it in 4 areas:

- a dashboard so we can spot easily the global status of the datas, like:

![progress-dashboard](https://user-images.githubusercontent.com/9025839/33092910-d97121ee-cefb-11e7-84cb-6d5ab50e31b5.png)

Maybe this dashboard could be a hard configured custom report and/or portal widget.

- indicate the progress in % in the object list, like:

![progress-list](https://user-images.githubusercontent.com/9025839/33092959-f692eb18-cefb-11e7-9943-556732837d04.png)

Add % progress like other columns in the list, with the possibility to filter objects with a range filter (from 23% to 56%) or fixed (all 0%, or all 100%).

- indicate the progress % on the object panel, like:

![progress-object](https://user-images.githubusercontent.com/9025839/33093103-4ff05736-cefc-11e7-8420-a1a7545b80d0.png)

- indicate the progress % on the search panel (with filter possibility)

---

From the PHP API side, maybe object will have two new fields: progress % and progress status (new, in progress and completed), so we can get this information directly from the object API or get list by using those two fields in condition parameters. Should be requestable from the REST API too.

One main question, is what define the progress ? Two possibility:

1- adding in the fields of object class, a check box to count it in the progress

![count](https://user-images.githubusercontent.com/9025839/33093582-a3cc0516-cefd-11e7-8129-028fd3dc364d.png)

**The rule will be: % progress = number of "count in progress" field filled in the object / total "count in progress" field of the class definition.
Some tricky case should managed (checkbox for instance, as checked or not they should be counted as always filled).**

Considering custom layout:
_For now, i don't think it is needed to make total "count in progress" field of the custom layout. It will make harder to implement the feature, but will permit user to know if he has filled all the fields he can.
Maybe to make it simple, just a "User progress" (so different than the "Progress" %) in the object panel could be added, and the rule will be:
% user progress = number of "count in progress" field filled in the object / total "count in progress" field of the custom layout.
So user get the global progress + his progress :)_

2- Same principle than 1- but we use the "required" checkbox instead of a new "count in progress" checkbox. Less flexible but will work out of the box without needing to change anything on existing classes.

If we want 1 and 2, we could add a system parameter to configure the global behaviour, with two values possible. For instance:
In system configuration, add a select labeled "Method for counting progress", with two option "By required" (this will be the default value), or "By count in progress". We can image a third option if needed "None" wich will disable the feature (but it will make code more complicated, so i don't think this is a good idea to be able to disable progress feature...).

Those propositions are just first idea, but the main idea is to have natively such a usefull information for PIM management.

**Comment by uniring** [comment]
+1

**Comment by fashxp** [comment]
This feature is implemented with our Data Quality Management Extension, details see https://pimcore.com/docs/platform/Data_Quality_Management/
