### ISSUE TITLE
[Improvement] Abilities to filter object list with events and custom condition.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2258]
This impovement is for object listing in Pimcore backend / GUI.

Sometimes we need to remove some objects from listing depending other parameters than the role/user defined (using role/user workspaces).
In such case, we need to hook an event to be able to modify the list returned. Proper way is to modify the condition request before the SQL request is sended to the database. This way pagination is not broken (if we remove item after, pagination will be no more good).

Actually, object list can be filtered like this, if i am not wrong:

- search list:
SEARCH_LIST_BEFORE_FILTER_PREPARE (event: pimcore.admin.search.list.beforeFilterPrepare')
This one is ok, as we can inject custom condition params in the requestParams.
See: https://github.com/pimcore/pimcore/blob/5483c6f0fa00cfb4026b15ef5ffbfaf9dcee66ca/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Searchadmin/SearchController.php#L54

- tree list:
We got only OBJECT_TREE_GET_CHILDREN_BY_ID_PRE_SEND_DATA ( event: pimcore.admin.dataobject.treeGetChildsById.preSendData)
This one is not ok, because we can only filter after the SQL request has been done, so removing element will break pagination.
**Like for the search list, it would be great to add an event to be able to inject condition parameters in the SQL request.**
Actually, the only way to achieve proper object removing in the tree is to use sql rule filter on the custom views (which is well handled before make the SQL request: https://github.com/pimcore/pimcore/blob/57cc6d0a39602f140549348ac90efe0d26aaa899/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectController.php#L83)

- object list:
Actually there is no way to hook, **so maybe we could add an event here as first line of the action, so just before this line**:
https://github.com/pimcore/pimcore/blob/5483c6f0fa00cfb4026b15ef5ffbfaf9dcee66ca/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectController.php#L1525
This event will take the request as parameter so we can modify it, and inject specific condition parameter in it.

To resume, i think by adding 2 new events, one for the tree list and one for the object list, developpers can easily make consistent list on all Pimcore backend according to custom conditions.

Use case:
Many, but one of them often asked will be the user can only see the object he created. With those events it will be possible by adding a condition owner_id = user_id.
Our use case is more complex as it involve listing product depending a field value of the object (authorized country) and the user role (one role per country). But with those new event it could be easily done too. 

I hope it make senses by just adding those two events Pimcore listing could be customized on the three area where there is listing: search, object list and tree. I hope i don't forget other panel wich could list object, but if it is the case they should provide the same event mecanism so the developpers can make the all experience ok.

---

If we go further, adding a unique event (present in the 3 action controllers for findAction, gridProxyAction and treeGetChildsByIdAction) will be the top. An event like `global.object.list.filter` and developpers know if he inject custom parameters here, all over Pimcore listing are impacted. Just an idea ; )
(this should not replace the two new event proposed before as it offers flexibility, but be a supplementary global object list event, for ease of use for developpers and prevent displaying by error some objects if the developper forgot to hook in every controllers).

Same will be nice for object open/save/delete... an unique event like `global.object.filter` so we can send true or false and it prevent access to the object for security (actually we need to hook many methods...).
If you think this last one is a good idea (centralize permission object in a simple true/false), i can make a separate issue.

Thanks for reading me as this is a long improvement request ; )

**Comment by Yivan** [comment]
Can I add a pull request for the events asked in this issue ? Or do you prefer to handle it ?
If i made a pull request all is ok from my issue or you see it in another way ?

We actually are blocked because we cannot manipulate list of object and because of this we need to modify core files actually.

Thanks.

**Comment by fashxp** [comment]
Hi,
if I would go for one event similar to the existing `AdminEvents::SEARCH_LIST_BEFORE_LIST_LOAD` event that is fired when tree or grid are loaded - something like `pimcore.admin.object.listing.beforeListLoad`. 
And the same we should add for assets `pimcore.admin.asset.listing.beforeListLoad` and documents `pimcore.admin.document.listing.beforeListLoad`.
