### ISSUE TITLE
Changes in grid view on classification store attributes does not change the value on the object

### ISSUE THREAD

**Issue by RasmusMagnell** [pimcore/pimcore#2262]
Replicated on pimcore demo 5.0.2

### Expected behavior 
  Changing a classification store attribute in the grid view changes the value on the object. 
### Actual behavior  
  The new value is shown in the grid but is not updated on the object. Even after refreshing the grid the new value is shown.
### Steps to reproduce  
  1) Create an object and set a classification store group with an attribute
  2) Go to a parents grid view
  3) Add the classification store attribute to the grid through the column configuration and change the value
  4) Go back to the object and refresh it

**Comment by weisswurstkanone** [comment]
Unable to reproduce. Did you pick the right grid language. See files attached
![cs2](https://user-images.githubusercontent.com/6142086/33175874-685c19e2-d05d-11e7-819a-27b562420acd.png)
![cs1](https://user-images.githubusercontent.com/6142086/33175875-6886f0b8-d05d-11e7-8779-d9340e46e908.png)

.

**Comment by RasmusMagnell** [comment]
Ah yes, you are correct. Mistake by me
