### ISSUE TITLE
Make Pimcore-Object-Classes not override parent functions by annotating

### ISSUE THREAD

**Issue by AlternateIf** [pimcore/pimcore#2272]
e.g 

The Pimcore-Object class A extends the non-pimcore-object class B

A has the pimcore-input property customId.  Due to that a getByCustomId is possible on the class. Since the customId property is unique the developer decided to implement the function getByCustomId in class B (to only return a single object)

Since Pimcore annotates its class properties with functions (e.g. getByCustomId) the function of class B is overlapped although it's the method that's going to be used

A solution may be to reflect the class and look for a implemented function before generating a function annotation

@brusch @maff

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
