### ISSUE TITLE
I have downloaded the latest pimcore-stable from site, when tried to access the /web, it redrected me to 404 page "http://localhost/install",

### ISSUE THREAD

**Issue by ramwaykar** [pimcore/pimcore#2277]

**Comment by brusch** [comment]
https://talk.pimcore.org/
https://pimcore.com/docs/5.0.x/Development_Documentation/Getting_Started/Installation.html

> Point the document root of your vhost to the newly created /web folder out of the ZIP archive (eg. /your/project/web). Keep in mind, that Pimcore needs to be installed outside of the document root.

rtfm ;)

**Comment by ramwaykar** [comment]
Thank you
