### ISSUE TITLE
Object image with related asset does not change when new asset image is uploaded

### ISSUE THREAD

**Issue by linkebon** [pimcore/pimcore#228]
Description: 
When uploading a new image to an asset, objects which have references to the asset will not display the new uploaded image after reloading the object. The new image is not displayed even if the image is removed from the object, saved, and related again.  The listing the image from the object tree view the wrong image is displayed also. 

Though under the objects version the correct image is displayed.

Recreate: 
1. Create class called Image with an Image attribute and create an object.
2. Upload new image asset. 
3. Relate object and asset and save object.
4. Upload new image to the asset and save.
5. Reload object. The new picture is not displayed on the object.
6. Remove the objects related image and save. 
7. Relate the asset again and save. Still the old image is displayed.

**Comment by dpfaffenbauer** [comment]
Have you tried clearing the cache?

**Comment by linkebon** [comment]
No, will try that today.

**Comment by brusch** [comment]
Any updates?

**Comment by linkebon** [comment]
Sorry for late response. Seems to have been some local cash histroy. Works on demo.pimcore.org.

**Comment by brusch** [comment]
Thanks for your feedback!
