### ISSUE TITLE
Documentation to fix

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2281]
**On this page:** https://pimcore.com/docs/5.0.x/Development_Documentation/Deployment/Multi_Environment.html

**Section:**

Loading example for PIMCORE_ENVIRONMENT = dev:

```
app/config/pimcore/system_dev.php
var/config/system_dev.php
app/config/pimcore/system.php
var/config/system.php
```

**The last two lines should be:**
```
app/config/pimcore/system_dev.php
var/config/system_dev.php
```

**Comment by Yivan** [comment]
Can I add a pull request for this one ?

**Comment by fashxp** [comment]
No, that makes no sense ... 
It is the loading order ... pimcore checks if `app/config/pimcore/system_dev.php` is available, if not checks for `var/config/system_dev.php`, if not available checks for `app/config/pimcore/system.php` and so on...

**Comment by fashxp** [comment]
if you change the last two lines as you suggested, they would be the same as the frist two lines, or do I miss something?

**Comment by Yivan** [comment]
You are totally right! I didn't see it was the same and was thinking dev_system.php can be placed in 4 places. This issue could be closed and forgotten ; )
