### ISSUE TITLE
Document\Service::render() exits when using in Console CLI

### ISSUE THREAD

**Issue by BenjaminEden** [pimcore/pimcore#2283]
### Code example 
```php
<?php
include(__DIR__ . "/../pimcore/config/startup_cli.php");
echo \Pimcore\Model\Document\Service::render(\Pimcore\Model\Document\Page::getById(1), [], false);
echo 'will not be shown';
```

Run your PHP file:

`php bin/test.php`

### Documented in
[https://pimcore.com/docs/master/Development_Documentation/Development_Tools_and_Details/Console_CLI.html#page_Simple-CLI-Scripts](url)

and

[https://pimcore.com/docs/master/Development_Documentation/Development_Tools_and_Details/Static_Helpers.html#page_Document-Service](url)

**Comment by maff** [comment]
Unable to reproduce here. Does the page you're trying to render exist and is it a page (not a link)? What version of Pimcore are you running?

My test case (used with the `demo-ecommerce` install profile):

```php
<?php

use Pimcore\Model\Document\Page;
use Pimcore\Model\Document\Service;

include __DIR__ . '/pimcore/config/startup_cli.php';

$doc  = Page::getByPath('/en/terms');
$html = Service::render($doc);

echo $html;
```

**Comment by BenjaminEden** [comment]
I had this problem with version 4 and 5.
It is not really a bug. I've found the cause for this behavior.

My page with the ID 1 is some kind of "language switch". It looks for the language of the browser and redirects to /de or /en .
Unfortunately, it does not only redirect via

`header("HTTP/1.1 302 Language switch");`
`header("Location: /en");`

but has an `exit()` at the end. This was what caused the render service to exit.
Sorry. So obvious...
