### ISSUE TITLE
Locking node in the tree results in all nodes collapsed

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#229]
This is very annoying when we have a lot of levels and we have to lock some nodes in depth.
Would be great if the system remember and auto-open the nodes again for us (after reloading the tree). In terms of performance it may be more efficient if the system only updates the nodes (properties and colors) without reloading the tree but not sure if there is good way for this implementation.

So the main improvement idea is that to keep the tree nodes open state just like before the locking/unlocking operation.

**Comment by brusch** [comment]
Unfortunately there isn't a callback for that in ExtJS - so no way.
