### ISSUE TITLE
Unable to open column header dropdown in variant grid view

### ISSUE THREAD

**Issue by RasmusMagnell** [pimcore/pimcore#2291]
Replicated in pimcore demo 5.0.2.

I get an extjs error when trying to open some column headers menu in the variant grid view. 

In the image below "Path" works fine but Username, Modification Date, etc does not show anything and the error appears in the console.
![image](https://user-images.githubusercontent.com/31310953/33450337-c288ec3e-d60b-11e7-88c8-17f38dcfb726.png)

The error:
![image](https://user-images.githubusercontent.com/31310953/33450429-104beff2-d60c-11e7-9447-b95d79aa1ac0.png)

In the file gridTabAbstract on the line 102, this.noBatchColumns is undefined in some cases:
![image](https://user-images.githubusercontent.com/31310953/33450555-740885e6-d60c-11e7-84b2-76cfc9f16b50.png)

**Comment by weisswurstkanone** [comment]
fixed in build 153
