### ISSUE TITLE
[Importer] If user doesn't have permission 'user' error message is shown

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2293]

**Comment by fashxp** [comment]
same applies for grid column configuration

**Comment by weisswurstkanone** [comment]
Tying this to the 'user' permission is problematic as this would allow the user also to edit existing users.
We should either add a new permission for
- listing users or
- sharing configurations

Any preferences ?

**Comment by fashxp** [comment]
I would take 'sharing configurations' since it might not be clear that 'listing users' is linked to sharing ...

**Comment by weisswurstkanone** [comment]
build153
