### ISSUE TITLE
[Importer] refactor to take more advantage of DI, Tags or Configurations

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#2299]
Currently, the Importer uses static Pimcore Namespace for resolving available operators and values. This should be done using the DI Container using configurations or tags. (https://github.com/pimcore/pimcore/blob/master/pimcore/models/DataObject/ImportColumnConfig/Service.php#L62) Currently it is not possible to extend it outside the Pimcore namespace and inject different kinds of services into a value or operator.

As well as the resolver configuration: its currently not extendable using the DI Container itself. You tricked it using the Code Resolver, which creates a PHP Class which then resolves the object. But: Still not injectable using the Container itself and not possible to inject services into my Resolver Class as well. It would refactor the Code Class to configure a service-name which will be used then.

IMHO: I would change following stuff (and don't take it personal or get me wrong):
 - Move Importer out of Model Namespace, since its not a Model, it just happens to work with DataObjects but its not a model itself and therefore doesn't need to live there.
  - Using a ServiceContainer or Registry to register Operators, Values and Resolver using tags. This would also resolve usage of Pimcore::getContainer(). I do understand the BC idea of it, but you should not introduce more usages of it. This makes it even harder to remove all usages of it. And as you know: thats an anti-pattern.
  - Create Tests for Imports, as far as I know, there are no unit-tests for the new feature.
  - Always think about extendability, testability and usability. Extending Pimcore in some places is not as good as it could be. The DI-Container gives you a great opportunity of having clean and extendable code without usage of static Namespaces like 'Pimcore\\Model\\DataObject\\ImportColumnConfig'
  - Add Interface for Resolver -> Since it should be extendable
  - don't use Db::get() -> inject it using the Container. (Db::get calls Pimcore::getContainer again, which is bad ;) )

**Now is the best time to do that**: Feature has not been released yet, releasing it and refactoring it again is a BC break.

PS: Same applies to Export Configurations, but: That feature has already been released right? I would still refactor it, its just good for the future of the pimcore project and it helps getting better ;)

**Comment by maff** [comment]
Thanks for the input @dpfaffenbauer, those are good points. We'll address most in #2307.

**Comment by dpfaffenbauer** [comment]
just saw it, looks good so far. 👍 

What about Exports? Do you gonna refactor as well?
