### ISSUE TITLE
[Importer Docs] add more detail description for AnyGetter

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2300]

**Comment by weisswurstkanone** [comment]
build 153

**Comment by Yivan** [comment]
I was just looking the doc for this PR https://github.com/pimcore/pimcore/blob/bdd2251f5f52d2f1b2c9eb901af316714535ca21/doc/User_Documentation/01_Objects/01_Grid_Configuration_Operators/Operators/02_AnyGetter.md and i saw two typo errors which need to be fixed i think:
- in the screenshot" "Paramater"
- in the text below: "Paramter"

**Comment by weisswurstkanone** [comment]
thx!
