### ISSUE TITLE
Grid configurator send error for user without the "user" permission.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2309]
An admin user get an error message if he open the grid configurator, if he has not the "user" permission.

To reproduce, on the online demo:
- create a user with `object `permission and add `news `folder in workspace object will all permission
- log with this user and open the `news` folder

Following error is displayed:
![operator-errot](https://user-images.githubusercontent.com/9025839/33560357-cc804334-d90f-11e7-8cf9-0bebbbe72895.png)

I don't know if this problem can occurs with the share new functionnality too.

Solution: the user should be able to use the grid configurator/operators/share without having the `user `permission.

**Comment by fashxp** [comment]
duplicate with https://github.com/pimcore/pimcore/issues/2293 
should be fixed with next build
