### ISSUE TITLE
No more HTTP keep-alive connection is possible

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#231]
I posted problem (in old Jira ticket) about HTTP keep-alive/pagespeed problem. I was trying to search more deeper why it happens.
But it seems that now all pimcore request send back HTTP closed connection (even desactivating page speed i got closed connection, and the demo website send closed connection too).

So we cannot make persistant keep-alive connection with Pimcore framework for now. Only way would be to unregister the event "system.shutdown" or use Cli script.

Is it intended ?

After studying the code, process seems like that (Pimcore 3.0.6 Stable):
- startup.php:

***create an event:***
Pimcore::getEventManager()->attach("system.shutdown", array("Pimcore", "shutdown"), 9999);
when triggered this will call Pimcore::shutdown() method wich set self::$inShutdown = true; making outputBufferEnd() function send "Connection: close"
OutputBufferStart() is started in the Pimcore::run() method and use as callback outputBufferEnd() (in case of non PHP-CLI).

***send this event:***
This event is always launched at the end by register_shutdown_function()

So actually Pimcore is ALWAYS sending "Close: connection". The only case it is not closed is in CLI mode where outputBufferEnd() is not used as callback for outputBufferStart().

**Comment by brusch** [comment]
"Connection: close" is necessary to allow the process run in the background, while the browser can start rendering. After "Connection: close" is sent, pimcore writes the items into the cache and does some other time intensive post-processing tasks. 

So I think there's unfortunately no way around this.

**Comment by Yivan** [comment]
Ok, I undestand so.
But there is one case where $inShutdown could be set to false maybe: when the page is comming from the output cache ?
And to left possibilty to developpers to force keep-alive $inShutdown could be a public property (it is private actually) or to have a setter public method.
If you think it is a good idea, i can open an issue as improvment for this.
Thanks!

**Comment by smaier** [comment]
@brusch ist the "Connection: close" still necessary in Pimcore 4.5 / will it be necessary in Pimcore 5? I stumpled upon those headers in https://gtmetrix.com 's speed optimizations, too.

**Comment by brusch** [comment]
@smaier at the moment we're not using `Connection: close` in v5.
