### ISSUE TITLE
Unwanted html appended to textarea

### ISSUE THREAD

**Issue by jnstr** [pimcore/pimcore#2318]
# Bug Report
  
### Expected behavior 

When saving a page, the contents of a textarea are saved correctly.
  
### Actual behavior  

It works as expected when the editable fieds aren't highlighted. But if they are, there is html appended to the textarea contents.

![afbeelding](https://user-images.githubusercontent.com/4415223/33659087-37b31efe-da7f-11e7-873c-79c361f3d1e7.png)
  

### Steps to reproduce  
Open a page in the pimcore admin that contains a textarea, highlight the editable fields and save the page.  
Tested on the demo installation (en/basic-examples/editable-roundup)

**Comment by jnstr** [comment]
Looks like this bug applies on both Pimcore 4 and 5

**Comment by brusch** [comment]
![image](https://user-images.githubusercontent.com/142037/34570368-da0f0cdc-f16b-11e7-96a1-e3f551659973.png)

**Comment by brusch** [comment]
Fixed in both v5 and v4

**Comment by Yivan** [comment]
Cool !! So great. It was a very anoying one. Thanks a lot.
