### ISSUE TITLE
Services.yml example no more uptodate.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2319]
The example on https://github.com/pimcore/pimcore/blob/master/app/config/services.yml#L18 is no more uptodate.

```
# Example event listener for objects
# app.event_listener.test:
#    class: AppBundle\EventListener\TestListener
#    tags:
#        - { name: kernel.event_listener, event: pimcore.object.preUpdate, method: onObjectPreUpdate }
```

should be:

```
# Example event listener for objects
# AppBundle\EventListener\TestListener:
#    tags:
#        - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate, method: onObjectPreUpdate }
```
=> directly giving the class name (if i remember well this is the good way now ?) and `pimcore.dataobject.preUpdate` is the good event name.

I don't know if the section `# Example custom templating helper` should be updated to.

**Comment by maff** [comment]
Thanks for reporting :)
