### ISSUE TITLE
Disabling output cache does not work

### ISSUE THREAD

**Issue by John5** [pimcore/pimcore#232]
The documentation describes several ways of disabling the cache: https://www.pimcore.org/wiki/display/PIMCORE3/Output-Cache

Our server does not use Memcache or any other additional caching mechanisms.

On one our websites we store a visitors email address in a session to display it on the following page. Because we don't want the email address to be cached, we disable the output cache for this page.

```php
	public function successAction() {

		//disable output cache to prevent this page from being cached.
		$front = Zend_Controller_Front::getInstance();
		$front->unregisterPlugin("Pimcore\Controller\Plugin\Cache");
	
		$session = new Zend_Session_Namespace('trial');
		$email = $session->email;

		if(isset($email) && !$this->view->editmode) {
			$text = $this->view->wysiwyg('body')->text;
			$text = str_replace('{{email}}', $email, $text);
			$this->view->wysiwyg('body')->text = $text;
		}
	}
```
When another person requests the same page however, the email address of the previous visitor is still visible. Adding a regex to disable the output cache for the page in System settings does not work either.
Only when `?nocache=true` is added to the URI, the cache is bypassed and we see "`{{email}}`" (the placeholder) displayed.

`\Pimcore\Model\Cache::disable();` does not disable the output cache either, while the documentation says it disables all caches.

**Comment by brusch** [comment]
Unfortunately this isn't reproducible on our testing envorinments. 
Please use our forums to get help. If you have any additional informations to this problem, and how we can fix it in general, please let us know. 

Thanks
