### ISSUE TITLE
Bugs Save&Share: graphic and predefined name

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2320]
I was just testing the news Save&Share feature on the online demo.
This is a really good new feature!! : )) Thanks for the work on it.

I tried it  on a restricted user (only "Object" permission and only "News" folder with all permission (list, view, ...) allowed.
Logging with this user and trying save and share feature.

Share feature is not available but i think because the user has not the "User" permission.

But i found two bugs.

1- Small graphic problem on Firefox (last stable):

![save-copy](https://user-images.githubusercontent.com/9025839/33711253-b057b22e-db43-11e7-9d2d-26ebceef0166.png)

2- Always on Firefox, trying to configure a grid (i add only "title" input field) and Save & Share:

![save-step1](https://user-images.githubusercontent.com/9025839/33711279-c61587ee-db43-11e7-91ce-8a2ea30bf2da.png)

Diplay a null value for the name:

![save-step2](https://user-images.githubusercontent.com/9025839/33711291-d11b9b24-db43-11e7-8b7a-c3ac46b0245f.png)

I think this is because this user has some limited right as this problem doesn't occur with the admin user.

**Comment by weisswurstkanone** [comment]
build 161
