### ISSUE TITLE
[Improvement] Adding a date operator

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2321]
I really love the new operators for the grid.
But one of them seem to miss and is maybe one of the most needed for end user is to transfom the date.
Actually date is displayed in the grid as human format but as soon you export it it is in timestamp... so end user are a little lost about it and we need to provide them sometimes an excel macro : )

With operator date can be formatted (using some operators, after dragging a date field the date format is asked, great!), but i think an operator named "date" would be more efficient for end user ? Maybe with some classic exemple bellow or a default value so he doesn't need to get in the technical php doc.

This is just an idea and give my feeling about end user experience i had on some project.
If you think it is not a good idea you can close it and this will be to the administrator create predefined grid for the end users.

Another option would be to export date in the same format than it is displayed on the grid.

**Comment by weisswurstkanone** [comment]
You are right, this one should be put on the list.

For now you can use a simple workaround. Just pick an operator (like trimmer) which can be disabled (meaning that it simply passes the value through) and drag the date field underneath it.

![image](https://user-images.githubusercontent.com/6142086/33829668-7ca8f8ee-de71-11e7-8923-d25798142981.png)

**Comment by Yivan** [comment]
Thanks for your answer. Yes I seen that and that's why i said an administrator can prepare the grid for enduser this way (and he will know the PHP date placeholder's too - see click for help button). But for enduser doesn't knowing PHP he will be lost I think.
It's great if a date operator more easier for enduser could be on the list : ) I hope it will be implemented.

**Comment by weisswurstkanone** [comment]
I would suggest to get rid of the formatting capabilities of the current Date Value node and move this stuff to an operator instead.

**Comment by weisswurstkanone** [comment]
replaced Date/DateTime Value with da DateFormatter operator. Build 160

**Comment by Yivan** [comment]
@weisswurstkanone 
Thanks!
Just maybe you should pointing the help to the english documentation instead the german one ?
Please see here:
https://github.com/pimcore/pimcore/commit/f8ff9853f60aafecac4e2e5aba69a2353f56fd24#diff-858fbb9b3cca439334ad916d33b5580dR97

**Comment by weisswurstkanone** [comment]
done
