### ISSUE TITLE
When editing classes: 404 in icon field ends up in pending php process 

### ISSUE THREAD

**Issue by danielschmieder** [pimcore/pimcore#2326]
When editing classes in Pimcore 5's backend and filling out the input field for the class icon, every typo produces a 404 (on key up) and a pending php process.

For sure it's better to have a look in the static6/img-folder if you don't know the exact image name, but in my case it ended up with a non-responding server by guessing image names. The server reached a limit of 50 entry processes – bleeding out very slow due to a high value for max. script running time. Just by typing the word "objects" as an image name would produce more than five pending processes. :-/

Hopefully this is reproducible – in case ask me for more details.

opening the class:
![opening-class](https://user-images.githubusercontent.com/20857191/33757289-c7f1dc6e-dbf9-11e7-8c97-14b6511bc012.png)

first typo:
![first-typo](https://user-images.githubusercontent.com/20857191/33757290-caf448b6-dbf9-11e7-8f94-c824bb286cfe.png)

second typo:
![second-typo](https://user-images.githubusercontent.com/20857191/33757292-cd35819e-dbf9-11e7-87e0-c931410a4f4a.png)

**Comment by brusch** [comment]
Maybe it's better to implement a dedicated preview button instead of pulling the icon on every key event ... 
The reason why the PHP process (404 page) ends as a zombie is a mystery to me ... maybe you can further debug this (Xdebug) for us.

**Comment by weisswurstkanone** [comment]
From now on (build 179) you have to manually refresh the icon.

![image](https://user-images.githubusercontent.com/6142086/35033757-16811b60-fb6c-11e7-8f9a-d0685c68bb21.png)
