### ISSUE TITLE
Opening image thumbnails tab twice leads to invalid UI state

### ISSUE THREAD

**Issue by schuttelaar** [pimcore/pimcore#2330]
To reproduce:
1. Log in in Pimcore admin
2. Open Image thumbnails panel.
3. Open Image thumbnails panel again.

Observe that 2 tabs appear, content does not appear in panel. Closing one tab closes both.

When there are other tabs and the image thumbnail does not have focus when opening the second panel, the behavior is different, but also wonky.

Expected behavior should be that when the tab is already open the previously opened tab receives focus and no new tabs are added.

**Comment by weisswurstkanone** [comment]
fixed in build 155
