### ISSUE TITLE
[Class Definition] Calculated value returns null, when inside fieldcollection

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#2332]
# Bug Report
I have a calculated field type within a fieldcollection in one of my objects. It calculates some value with other values from other fields inside my fieldcollection. Everything works as expected (also in the backend) until I call `$entry->getMyCalculatedValue();` on it.
  
### Expected behavior
When I call the getter method of the field I expect it to return its value, which was calculated inside the static `::compute` method.
  
### Actual behavior
It returns `null`.
  
### Steps to reproduce
Here's my controller code:
```php
$object = DataObject\MyObject::getById($id);
$fieldCollection = $order->getMyFieldcollection();

$i = 0;
/** @var DataObject\Fieldcollection\Data\MyFieldcollection $entry */
foreach ($fieldCollection->getItems() as $entry) {
    $myArray[$i]['myCalculatedValue'] = $entry->getMyCalculatedValue(); // this returns null

    $i++;
}
```  
  
### Code example
I think the problem is within the class definition:

Shouldn't this ...
```php
/**
* Get myCalculatedValue - My Calculated Value
* @return \Pimcore\Model\DataObject\Data\CalculatedValue
*/
public function getMyCalculatedValue ()
{
    $data = new \Pimcore\Model\DataObject\Data\CalculatedValue('myCalculatedValue');
    $data->setContextualData("fieldcollection", $this->getFieldname(), $this->getIndex(), null);
    $data = DataObject\Service::getCalculatedFieldValue($this, $data);

    return $data;
}
```

... look something like this?
Especially have a look at `$data->setContextualData(...)` and `DataObject\Service::getCalculatedFieldValue(...);`.
```php
/**
* Get myCalculatedValue - My Calculated Value
* @return \Pimcore\Model\DataObject\Data\CalculatedValue
*/
public function getMyCalculatedValue ()
{
    /** @var $definition DataObject\Fieldcollection\Definition */
    $definition = $this->getDefinition();
    $data = new \Pimcore\Model\DataObject\Data\CalculatedValue('myCalculatedValue');
    $data->setContextualData("fieldcollection", $this->getFieldname(), $this->getIndex(), null, null, null, $definition->getFieldDefinition('myCalculatedValue'));
    $data = DataObject\Service::getCalculatedFieldValue($this->getObject(), $data);

    return $data;
}
```

**Comment by weisswurstkanone** [comment]
fixed in build 159

**Comment by weisswurstkanone** [comment]
Note that you will have to save the fieldcollection as the fix is in the generated getter code.

**Comment by aarongerig** [comment]
Thank you very much!
