### ISSUE TITLE
Add button to open objects with LinkGenerator in new tab.

### ISSUE THREAD

**Issue by schuttelaar** [pimcore/pimcore#2337]
Documents have a button with a mouse pointer icon that opens the document in a new tab. Objects don't because it is ambiguous which URL to use.

When an object has a [LinkGenerator](https://github.com/pimcore/pimcore/blob/master/doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/15_Link_Generator.md) the object has a clearly defined URL and it should possible to have the same functionality.

I think it would be a good addition to have the "Open" button for objects that have a LinkGenerator associated with them.

**Comment by weisswurstkanone** [comment]
build 159
