### ISSUE TITLE
Cut and Paste wont work with Bricks in Pimcore Backend with IE11 and Edge

### ISSUE THREAD

**Issue by knoepfchen23** [pimcore/pimcore#2338]
In Version 5.0.2 (147) of Pimcore it is not possible to paste Bricks in documents that you have cut before (no matter if you try to paste it in the same or in a different document). If you cut it, you can't paste it - if you try it, nothing happens. The Browser doesn't reload after pasting, as it does in other browsers like Google Chrome or Mozilla Firefox e.a.

I also checked out the behavior in the demo version (admin and user).

**Comment by weisswurstkanone** [comment]
fixed in build 172

**Comment by knoepfchen23** [comment]
thanks for the fix
