### ISSUE TITLE
[DOC] Operator ObjectBrickGetter and ObjectFieldGetter

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2339]
Just to report that it seems new operators ObjectBrickGetter and ObjectFieldGetter are not documented.
https://pimcore.com/docs/5.0.x/User_Documentation/Objects/Grid_Configuration_Operators/Operators/Anonymizer.html

![operator](https://user-images.githubusercontent.com/9025839/33942070-1392b7dc-e015-11e7-9f29-433cbd126f20.png)

**Comment by weisswurstkanone** [comment]
build 158

**Comment by Yivan** [comment]
Thanks!
Just on https://pimcore.com/docs/5.0.x/User_Documentation/Objects/Grid_Configuration_Operators/Operators/ObjectFieldGetter.html
the image seems broken: https://pimcore.com/docs/5.0.x/User_Documentation/img/gridconfig/operator_objectfieldgetter_symbol.png => 404

**Comment by weisswurstkanone** [comment]
thx!
