### ISSUE TITLE
Opcache Status does not work in https mode

### ISSUE THREAD

**Issue by ascheider** [pimcore/pimcore#2345]
How to reproduce.
1. Login in Pimcore Backend via https
2. Click on Tools -> System Info & Tools -> PHP OPcache Status
3. Open Dev Tools -> Network
4. React and jquery are blocked because of mixed content
  
![image](https://user-images.githubusercontent.com/6016485/33985616-6f75bd3c-e0bb-11e7-9cb7-bc321dffba66.png)

**Comment by maff** [comment]
The `amnuts/opcache-gui` includes its files via `//`, e.g. `https://cdn.jsdelivr.net/react/15.4.2/react.min.js`. Looking at the asset versions it tries to load in your screenshot you seem to run a really old version of `amnuts/opcache-gui`. Can you check `composer info` which version is installed and try to update it via `composer update`? The `~2` constraint should install the latest version `2.4.0` and fix your SSL problem.
