### ISSUE TITLE
Environment test prevent logging in the backend.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2346]
By using the default test environment, i cannot log in the Pimcore backend.

Information:
- Debian 9, Pimcore 5.0.2 stable
- I got no error message (authentification failed), it just bring back to the login screen without any message.
- By looking in the log i got:
`security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at .../vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []`
- session directory has all the permissions to be written
- deleted manually /var/cache/test directory and clearing the Pimcore cache/cache_tags table change nothing

Actual solution:
If i comment the session handler
```
    session:
        storage_id: session.storage.mock_file
```
in pimcore\lib\Pimcore\Bundle\CoreBundle\Resources\config\pimcore\config_test.yml
i can log in the backend.

Why there is a problem with the session.storage.mock_file ? Is it a bug ? I don't find any information on this on the Pimcore documentation.

**Comment by maff** [comment]
Hi,

the test environment isn't meant for logging into the admin via browser but only for testing (unit/integration tests). Therefore the session is a mock session which doesn't actually start a session and won't work with browsers. See https://github.com/symfony/http-foundation/blob/master/Session/Storage/MockFileSessionStorage.php.

**Comment by Yivan** [comment]
@maff Thanks for the ultra fast answer!
I undestand better now.

Is it documented somewhere ? If not I think you should explain this here that "test" is some special environement presseted: https://pimcore.com/docs/5.0.x/Development_Documentation/Deployment/Multi_Environment.html
Will help people comming from Pimcore 4 where test env could be used like any other environnement whereuser intend to log.

So we need to create a "testing" environment for instance.
For reference, when trying to set a new environment (by copying de dev environment files), some problems occurs => https://github.com/pimcore/pimcore/issues/2265

**Comment by maff** [comment]
No not explicitely in Pimcore as it follows the Symfony convention (see https://github.com/symfony/symfony-standard/blob/3.4/app/config/config_test.yml). It's also the environment which is used to run Pimcore's test suite on Travis.
