### ISSUE TITLE
Programatically adding multiple bricks on object do not work as expected

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#235]
Reproduce steps:

Create following objectbricks: "Limestone", "Pattern", "TechnicalDetails", "Usage".
All of these has one field of type "multihref" named "relationalData" allowing only objects each of which allows one class as follows: "SetLimestone", "SetPattern", "SetTechnicalDetail", "SetUsage". So you should set up these classes firstly. There is no actually matter what is the definition of these classes put it simple - one input field. Create one more class which will have field for the bricks, in my case it is named "CatalogItem". Create one instance of each classes and use the following script to see the wrong result in the object of type CatalogItem. (Please change the hardcoded IDs)

```
    <?php
    use Pimcore\Model\Object;
    $oLimestone = Object\SetLimestone::getById(44);
    $oPattern = Object\SetPattern::getById(51);
    $oDetails = Object\SetTechnicalDetail::getById(64);
    $oUsage = Object\SetUsage::getById(74);

    $items = new CatalogItem\Listing();
    foreach ($items as $item) {
        try {
            var_dump($item->getId());

            $item->getBricks()->delete($item);
            $item->save();

            $limestone = new Object\Objectbrick\Data\Limestone($item);
            $limestone->setRelationalData([$oLimestone]);
            $item->getBricks()->setLimestone($limestone);

            $patterns = new Object\Objectbrick\Data\Pattern($item);
            $patterns->setRelationalData([$oPattern]);
            $item->getBricks()->setPattern($patterns);

            $details = new Object\Objectbrick\Data\TechnicalDetails($item);
            $details->setRelationalData([$oDetails]);
            $item->getBricks()->setTechnicalDetails($details);

            $usage = new Object\Objectbrick\Data\Usage($item);
            $usage->setRelationalData([$oUsage]);
            $item->getBricks()->setUsage($usage);

            $item->save();
        } catch (\Exception $e) {
            echo $e->getMessage() . PHP_EOL;
        }

        break;
    }
```

I am expecting all of the 4 bricks to be applied and each of them to have one item in the multihref of the just right type. See what actually happens in the screenshot.

![s1](https://cloud.githubusercontent.com/assets/11477130/9783822/d45e47e2-57af-11e5-8a0a-389b27680fe0.png)
![s2](https://cloud.githubusercontent.com/assets/11477130/9783821/d45bb950-57af-11e5-9255-0f1aa6399e7c.png)
![s3](https://cloud.githubusercontent.com/assets/11477130/9783820/d45b1284-57af-11e5-8860-f30d8c296c84.png)

And in the backend it is allowing me to "save & publish" the object even that it has forbidden classes in the multihref field.

**Comment by kanevbg** [comment]
Technology info: Apache/2.4.6 (CentOS) PHP/5.5.23 MySQL 5.6.26

**Comment by kanevbg** [comment]
Any updates on that? When we can expect resolution?

**Comment by kanevbg** [comment]
That bug seems to be dangerous, please kill it, it scares me.

**Comment by weisswurstkanone** [comment]
Unable to reproduce, build 4053.
Please try with the latest build. Let us know if it still fails.
