### ISSUE TITLE
Add Reply-To in Pimcore Mail

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#2351]
![bildschirmfoto 2017-12-14 um 16 54 44](https://user-images.githubusercontent.com/700119/34001194-a613f1d6-e0ef-11e7-9ec7-f135adc18f27.png)

Sometimes it's quite important to have a reply-to in emails (contact form => reply-to => customer email). Since the `setReplyTo` method is fully supported by SwiftMailer (actually the default pimcore mail ReplyTo is populated with the value from system settings) this would be a great and "easy-to-integrate" feature. Providing an PR is possible, if you agree with this feature.

**Comment by fashxp** [comment]
We would like to see a PR for that.

**Comment by solverat** [comment]
your wish is my command! :)
