### ISSUE TITLE
WebDAV Documentation

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2352]
Is WebDAV always possible for assets with Pimcore 5 ?

If yes, documentation is missing (i found nothing with the "webdav" keyword using the search feature), maybe it should be added to documentation (like a dedicated page as it was on the Pimcore 4 documentation).

Thanks.

**Comment by fashxp** [comment]
webdav is available on pimcore 5 too. 
there wasn't a webdav section in pimcore 4 either. it will be part of the user documentation we are starting to create now.

**Comment by fashxp** [comment]
https://YOUR-DOMAIN/admin/asset/webdav
