### ISSUE TITLE
SEO Document editor gives warnings for unpublished documents

### ISSUE THREAD

**Issue by schuttelaar** [pimcore/pimcore#2354]
When a page is unpublished he SEO Document editor warns that there are no headlines or &lt;h1&gt; tag on the page. When the document is published these warnings disappear.

To reproduce:
1. Log in Pimcore admin
2. Open SEO Document editor and observe that a published document has no warnings about headings.
3. Close SEO Document editor
4. Unpublish document
5. Open SEO Document editor
6. Observe that there are now warnings for that document that were not there before.

Expected behavior:
Unpublished documents should be treated the same as published documents.

**Comment by brusch** [comment]
Related to #2098
