### ISSUE TITLE
Redirect grid behaves strangely sometimes

### ISSUE THREAD

**Issue by maff** [pimcore/pimcore#2357]
While implementing #2356 I noticed some strange behaviour on the redirects grid which was not always reproducible. E.g.:

* Clicking on multiple times quickly started to send an array request with multiple items to the server, not a single one with ID. As there is no check if the loaded redirect exists, this error wasn't noticed before. However, the redirects are not deleted as expected.
* It tries to write to a redirect with ID 0 sometimes after adding/updating a row.
* Sometimes, after updating a row, multiple redirects are created on the backend

Suggestion: rebuild redirects controller and grid handling to use proper distinct REST actions with the REST proxy and validate requests better.

**Comment by weisswurstkanone** [comment]
fixed in build 189
