### ISSUE TITLE
[DataObject] Inherited multi-href cannot be emptied

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#2360]
# Bug Report
When clearing a inherited multi-href field inside a DataObject, the empty state will not be saved. Instead it still contains the old value. You can see the described behavior in this [video](https://github.com/pimcore/pimcore/files/1568516/multihref_inheritance.zip).

### Expected behavior 
When clearing the inherited multi-href field, it should stay empty when saving the DataObject.

### Actual behavior
The multi-href still contains the old value, when reloading the DataObject. 
  
### Steps to reproduce  
- Go to https://demo-advanced.pimcore.org/admin
- Open a product variant (e.g. ID 1607)
- Under Base Data empty out a multi-href field
- Save the variant
- Reload the variant

**Comment by weisswurstkanone** [comment]
Works as designed. If it is empty then it inherits the value from the parent.

Please check
https://pimcore.com/docs/5.0.x/Development_Documentation/Objects/Object_Classes/Class_Settings/Inheritance.html

"... If data inheritance is enabled and an attribute of an object is empty, Pimcore tries to get this attribute from a parent object. This works only, if the parent object has the same class as the child object. Data inheritance between different classes is not supported...."
