### ISSUE TITLE
Ordering objects by position

### ISSUE THREAD

**Issue by knickedixen** [pimcore/pimcore#2364]
I would like to be able to order objects in the tree by position rather than alphabetically. The same functionality as for documents. 

I can see traces of this in the database. There is a column o_index in object tables which I suspect is the object equivalent to column index for documents. But this doesn't seem to ever be used, except that it is always set to 0 whenever you update an object.

Was this ever intended to work, or is o_index used for something else?

**Comment by brusch** [comment]
Initially this was planned but then we decided against this feature for several reasons and issues that came up. At the moment we have no intentions to integrate/enable this feature.
