### ISSUE TITLE
Static routes exception

### ISSUE THREAD

**Issue by kroupa1985** [pimcore/pimcore#2385]
I think i've get an isshue, that could be a bug.

I was working on static routes, when i encauntered an exception, adding, update or destroy a route. Next time this exception happened when i opened static routes tab:

`Timestamp: Mon Dec 25 2017 18:05:25 GMT+0100 (Central Europe Standard Time)
Status: 500 | Internal Server Error
URL: /admin/settings/staticroutes?&xaction=read&_dc=1514221524724
Method: POST
Message: Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW)`

I can't open static routes any more. I was adding a route when this happended. Actions wich get the same error were also update and destroy. I was able to add a couple of routes, when this happened.

Maybee you know wich file to correct, wich would work and not throw an exception.

**Comment by fashxp** [comment]
can you check if your static routes file `var/config/staticroutes.php` is a valid php file?

**Comment by weisswurstkanone** [comment]
any updates on this ?

**Comment by fashxp** [comment]
closed due to inactivity.
