### ISSUE TITLE
Pimcore-stable.zip install problem

### ISSUE THREAD

**Issue by elwininc** [pimcore/pimcore#2386]
Hello
I just downloaded the pimcore-stable.zip from the official site (Pimcore 5) and I have problems installing it 
(Centos 7 and Apache 2.4 ,PHP7.1.11)
When I open http://localhost/install.php =>
Warning: file_put_contents(/var/www/pimcore/var/installer/cache/prod/installerProdDebugProjectContainerDeprecations.log): failed to open stream: No such file or directory in /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 578

Warning: file_put_contents(/var/www/pimcore/var/installer/cache/prod/installerProdDebugProjectContainerCompiler.log): failed to open stream: No such file or directory in /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 579

Fatal error: Uncaught RuntimeException: Unable to create the cache directory (/var/www/pimcore/var/installer/cache/prod) in /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:672 Stack trace: #0 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(572): Symfony\Component\HttpKernel\Kernel->buildContainer() #1 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(117): Symfony\Component\HttpKernel\Kernel->initializeContainer() #2 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(166): Symfony\Component\HttpKernel\Kernel->boot() #3 /var/www/pimcore/web/install.php(69): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #4 {main} thrown in /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 672

What is the problem ? 

I just followed the documentation:

download the zip archive,
extract it in a directory,
set apache docroot on the "web" directory,
setup chown -R apache:apache /myproject/
setup 775 premission for  /myproject/
create a database, user.....
and open http://localhost/install.php

Thanks for your help

**Comment by elwininc** [comment]
issue solve

close it

**Comment by BelaD** [comment]
What is the solution?

**Comment by mikroobdj** [comment]
Same problem with Pimcore 6 & PHP 7.2.24-0ubuntu0.18.04.2

" Warning: file_put_contents(/var/www/pim-skl/myxlp/var/cache/dev/appAppKernelDevDebugContainerDeprecations.log): failed to open stream: No such file or directory "

**Comment by z4ph0d8** [comment]
what was the resolution?
