### ISSUE TITLE
search_backend_data issue at pimcore v4

### ISSUE THREAD

**Issue by stanley87** [pimcore/pimcore#2387]
I think i has critical issue with pimcore v4 table search_backend_data

currently we have 9mil data record in this table search_backend_data and cause a lot of issue due to this huge table search_backend_data, is that possible to truncate this table directly ? or any clean up suggestion ?

**Comment by fashxp** [comment]
hi, 
please refer to our forums ... https://groups.google.com/forum/#!topic/pimcore/8Po_0lf1qjQ 

thanks...
