### ISSUE TITLE
SEO - Documenteditor not working with ssl

### ISSUE THREAD

**Issue by ChristianBre** [pimcore/pimcore#239]
##### The Bug:
Opening the SEO-Document Editor i receive 0-value for all fields which are requestes via Zend_Http_Client (h1, hx, images with alt, images without alt, external links and links). 

##### Tracking it
After a while i found there is no Error thrown in 
pimcore/lib/Pimcore/Tool.php:483

##### The Message
Unable to Connect to ssl://www.myproject.com:443. Error #0:

**Comment by brusch** [comment]
This seems to be an issue on your side, ... since the Zend_HTTP_Client tries to load the resource via HTTPS and you have to ensure that he can access himself using HTTPS.

**Comment by brusch** [comment]
closed due inactivity
