### ISSUE TITLE
Check ecommerframeworkbundle/bundle.js

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#2391]
Why is there a 
`if(true || perspectiveCfg.inToolbar("ecommerce")) {
`
in the ecommerce bundle.js?
Please verify if that is ok.

**Comment by maff** [comment]
This was actually removed in [#2381](https://github.com/pimcore/pimcore/pull/2381/files#diff-fa91328ef6d07e7646fcd3d4fb9891ffL38).
