### ISSUE TITLE
[Ecommerce] - onmaintenance throws exception if no steps are defined

### ISSUE THREAD

**Issue by AlternateIf** [pimcore/pimcore#2392]
'Checkout manager needs at least one checkout step' exception gets thrown onMaintenance since the default tenant config has no steps defined. 

this causes pending orders not being cleaned up (set to aborted)

creation of checkoutManager: https://github.com/pimcore/pimcore/blob/0e2b4ea615eb4b81e4e2a28e30a908d9461df0bd/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/CheckoutManager/CheckoutManagerFactory.php#L140

config:
https://github.com/pimcore/pimcore/blob/0e2b4ea615eb4b81e4e2a28e30a908d9461df0bd/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Resources/config/checkout_manager.yml

checkoutManager construction:
https://github.com/pimcore/pimcore/blob/5483c6f0fa00cfb4026b15ef5ffbfaf9dcee66ca/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/CheckoutManager/CheckoutManager.php#L124

@fashxp

**Comment by datom** [comment]
need this too :)

https://github.com/pimcore/pimcore/blob/0e2b4ea615eb4b81e4e2a28e30a908d9461df0bd/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/EventListener/SystemEventsListener.php#L65

the maintenance listener should loop all valid checkout manager and execute the clean up?

**Comment by fashxp** [comment]
ideally this should go even further ... every order should know with what checkout tenant it was created and the corresponding checkout manager should only cleanup orders it created.
so this would be a bit more refactoring. 
what do you think?
