### ISSUE TITLE
[Targeting] Save order of global targeting rule doesn't work

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2393]
![image](https://user-images.githubusercontent.com/8792145/34478758-f82c5e60-efa2-11e7-8ab1-dc140f85ee6e.png)

**Comment by maff** [comment]
Not related to saving the order, but saving rules in general when there is still data from the previous targeting implementation. Update script will make sure no old targeting rules exist after an update, so this is obsolete.
