### ISSUE TITLE
Pimcore 5 errors with PHP 7.2

### ISSUE THREAD

**Issue by mimmi20** [pimcore/pimcore#2398]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [x] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [ ] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [x] There's no existing ticket for the same issue

### Expected behavior 
no error
  
### Actual behavior  
Warning: count(): Parameter must be an array or an object that implements Countable in pimcore/models/Document.php (line 659)

Line 659
Is: if (is_array($children) and count($children > 0)) {
Should be: if (is_array($children) and count($children) > 0) {
  
### Steps to reproduce  
install Pimcore with PHP 7.2
login into demo

**Comment by mimmi20** [comment]
![image](https://user-images.githubusercontent.com/1120192/34520069-678c0db6-f087-11e7-9e47-de78384a0381.png)

**Comment by weisswurstkanone** [comment]
thx
