### ISSUE TITLE
Colorpicker Object DataType

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#2399]
# Feature Request 

Is it useful to create a Colorpicker Object DataType like?

https://examples.sencha.com/extjs/6.0.2/examples/kitchensink/#form-color-picker

**Comment by brusch** [comment]
The ExtJS color picker seems to be more advanced now then it used to be ... see also former feature request: 
https://github.com/pimcore/pimcore/pull/839#issuecomment-244337042

I'd say that would be absolutely worth a data-type.

**Comment by weisswurstkanone** [comment]
build 172
