### ISSUE TITLE
Fallback translation in combination with caseinsensitive website translations

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#2405]
I tried to solve this in #2371

Unfortunately it does still not work under all cercumstances. The only way how I can solve it is to do a check here:
https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Translation/Translator.php#L317

And return the translated value only when it is actually translated (different from the ID). But this results in multiple SQL insert statements.

I think this needs some refactoring otherwise it's not really possible to solve the the problem.

**Comment by fashxp** [comment]
what is the way to reproduce that?
