### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by mimmi20** [pimcore/pimcore#2406]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [x] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [x] There's no existing ticket for the same issue

### Expected behavior 

No error
  
### Actual behavior  

Error Message

**Comment by mimmi20** [comment]
![image](https://user-images.githubusercontent.com/1120192/34558177-3f0cd8e6-f13d-11e7-90d5-9ab2ba1eafa7.png)

**Comment by brusch** [comment]
Unable to reproduce this on the demo (https://pimcore.com/en/try). 
Any further details? I assume you deleted the corresponding news objects or the class. 
For further questions please use our forums. Thank you very much.
