### ISSUE TITLE
CSV import error

### ISSUE THREAD

**Issue by elwininc** [pimcore/pimcore#2408]
when I import CSV file. it show error

error:
Exception: Could not resolve object with id 13026701 in /var/www/pimcore/pimcore/lib/Pimcore/DataObject/Import/Resolver/Id.php:36 Stack trace: #0 /var/www/pimcore/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php(1293): Pimcore\DataObject\Import\Resolver\Id->resolve(Object(stdClass), 11842, Array) #1 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObjectHelperController->importPreviewAction(Object(Symfony\Component\HttpFoundation\Request), Object(Pimcore\DataObject\Import\Service), Object(Pimcore\Localization\Locale), Object(Pimcore\Model\Factory), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)) #2 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #3 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/pimcore/web/app.php(55): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #5 {main}
![image](https://user-images.githubusercontent.com/28559251/34563451-aae130bc-f18d-11e7-9fb0-d9382d1f33bf.png)
![image](https://user-images.githubusercontent.com/28559251/34563458-b3fbaa92-f18d-11e7-96f3-9556ecd716b8.png)
![image](https://user-images.githubusercontent.com/28559251/34563463-bcea84ac-f18d-11e7-9d62-ca1f4112a8cb.png)

![image](https://user-images.githubusercontent.com/28559251/34563262-ec6d0cf0-f18c-11e7-9b0f-a902d2a45f4b.png)
![image](https://user-images.githubusercontent.com/28559251/34563500-d786c5aa-f18d-11e7-939e-ba4e7c2a44f1.png)

**Comment by elwininc** [comment]
by the way, I try to the  same operate on demo.pimcore.org, it is same problem.

**Comment by weisswurstkanone** [comment]
Well, the "itemno" coluimn does not contain pimcore IDs, right ?
At least for T00593  and T00605 this is impossible.

**Comment by aarongerig** [comment]
In the third screenshot you have to set `Resolver Strategy` to your column `itemno`, otherwise it is looking for an DataObject with the ID of some of your `itemno`.

**Comment by elwininc** [comment]
Thank you

I setup some structured table on class.like the photo, then how to import the data from csv.file into
these sheet. it is  no idea for me now.

![image](https://user-images.githubusercontent.com/28559251/34564848-75df6ad6-f193-11e7-88ce-8bcdad0d1fdb.png)

**Comment by brusch** [comment]
At the moment you can't within the interface - you'd have to script this import.

**Comment by ramya343** [comment]
I am trying to load the CSV file into the portal but its showing validation error.
below screenshot is for your reference 
![image](https://user-images.githubusercontent.com/61545414/75443603-c3e14980-5987-11ea-882e-22ce65c96fad.png)
could you help me with this?

**Comment by ramya343** [comment]
Whenever I am creating a attributes it's showing the below error
![image](https://user-images.githubusercontent.com/61545414/75443765-1a4e8800-5988-11ea-98dd-01f88f50b2fa.png)

I am new to pimcore  source system 
can you help me with this?

**Comment by sameeradamith** [comment]
Go to **Resolve settings tab** and then select **Resolve Strategy** as **Filename** and then click **import**. 

![test](https://user-images.githubusercontent.com/4506338/94402543-d162ea00-0189-11eb-986c-09f02fe72468.png)
