### ISSUE TITLE
Respect Unique Fields on Copy/Paste 

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#2416]
You also can reproduce this on demo:
- create class `test` with two fields (text[default textfield], unique[textfield with unique check])
- create one object type `test` with name `object1` and fill out both fields
- copy `object1` object and paste it into same directory
- open `object1_copy`: both fields have identical values than `object1`.
- save  `object1_copy`: **no error**! object stored with duplicate unique field data
- clear cache (or empty `cache` and `cache_table` table)
- open both objects `object1` and `object1_copy`: one of them does **not have any values** anymore!

This is a nasty one, we searched for hours to find out whats going on. Maybe just clean the unique fields before create copy objects?

**Comment by weisswurstkanone** [comment]
fixed in build 173.

However, the consequence is that such objects cannot be pasted anymore. Your suggestion to null them out sound quite reasonable. Do you wann a create a separate issue for this?

thx!
