### ISSUE TITLE
Lost password unexpected exception when password is empty

### ISSUE THREAD

**Issue by kkarkus** [pimcore/pimcore#2417]
### Expected behavior 
I should receive an email.

### Actual behavior  
 I get CryptException "Expected a string".

### Steps to reproduce  
  1. Create user, fill email address and DO NOT FILL password.
  2. Go to https://demo-basic.pimcore.org/admin/login/lostpassword
 
I can solve this, my proposal is to create random password before generating token, is it good approach?

**Comment by Yivan** [comment]
Maybe is linked to this one: https://github.com/pimcore/pimcore/issues/2310
