### ISSUE TITLE
pimcore 3.1.0 two bugs

### ISSUE THREAD

**Issue by piotrecky** [pimcore/pimcore#242]
hi, I have a problem after the upgrade to 3.10 version.

1) New version was added to the menu two items such as application logger, that doesn't work because it refers extjs 6 library but default extjs 3.4 is active?

2) Problem with list of objects in CMS panel - a problem in the file:
https://github.com/pimcore/pimcore/blob/master/pimcore/models/Object/Listing/Resource.php
- method addGroupBy () is not found

Is version 3.10 is now stable?

Regards

**Comment by brusch** [comment]
1.) The application logger just works perfectly with ExtJS 3.4.
See also: https://www.pimcore.org/demo 
What is the 2nd problem you mentioned? 

2.) I can't see any problem, can you be more specific? 

Thanks!

**Comment by piotrecky** [comment]
Today I'm downloaded from github version 3.10 and now OK. Update script from CMS not download all files from 3.10 version and this is a problem.
