### ISSUE TITLE
Nginx configuration - no styles for Adminer

### ISSUE THREAD

**Issue by mgomse** [pimcore/pimcore#2425]
With current nginx configuration (https://pimcore.com/docs/5.1.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Nginx_Configuration.html) Adminer don't have styles

commenting 
```
location ~* (.+?)\.((?:css|js)(?:\.map)?|jpe?g|gif|png|svgz?|eps|exe|gz|zip|mp\d|ogg|ogv|webm|pdf|docx?|xlsx?|pptx?)$ {
        try_files /var/assets$uri $uri =404;
        expires 2w;
        access_log off;
        log_not_found off;
        add_header Cache-Control "public";
    }
```

fix it but probably is not the best/safe solution

For now I just have this workaround so maybe somebody else will fix it correctly 😸

**Comment by gadget60** [comment]
Actually I've mentioned this issue a while ago on the documentation page itself - but somehow the Disqus comments have gone...

I came up with the following solution:
```
location ~* ^(?!/admin/)(.+?)\.((?:css|js)(?:\.map)?|jpe?g|gif|png|svgz?|eps|exe|gz|zip|mp\d|ogg|ogv|webm|pdf|docx?|xlsx?|pptx?)$ {
   ...
}
```
However, there's a second issue with the provided nginx configuration. It just allows you to access assets with a filename suffix that matches the regex above. Unlisted file extensions (like .txt or .dxf) yield a 404. The reason is that non-matching filename extensions won't be checked against the assets dir. We fixed it using:
```
location / {
    ...
    try_files $uri /var/assets$uri /app.php$is_args$args;
}
```

**Comment by bbak** [comment]
Adding `/var/assets$uri` is dangerous. That's - obviously - a folder allowing uploads. If you upload a PHP Script in there, it may be passed to the PHP Engine!
The sole purpose of the long RegEx with File Extensions is to prevent exactly this case. 

If you need to make `.txt`, `.dxf`or whatever available through assets, the better approch is, to add that extension to the long RegEx matching file extensions.

I'll have a look into adminer.

**Comment by gadget60** [comment]
I don't really agree - this is what the rule below is for. Additionally, uploaded .php files get renamed to .txt by Pimcore. Sure, the whitelist approach may be another security layer, However predefining every allowed filename extension may not be feasible for some projects.

```
    # Stay secure
    #
    # a) don't allow PHP in folders allowing file uploads
    location ~* /var/assets/*\.php(/|$) {
        return 404;
    }
```

Anyway, thanks for the advice!
