### ISSUE TITLE
Grid configuration and Classification Store

### ISSUE THREAD

**Issue by incoxx** [pimcore/pimcore#2426]
Failure in pimcore 5.1:
1. Open a grid configuration for objects with assigned classification store.
2. Try to add a key from the classification store (show all keys)
3. Sort the keys by name. See screenshots below. SQL must be: "order by classificationstore_keys.name" (not keyname)

Error:
URL: /admin/classificationstore/search-relations?_dc=1515586117258
Method: GET
Message: An exception occurred while executing 'SELECT classificationstore_relations.*,classificationstore_keys.*, classificationstore_groups.name as groupName FROM classificationstore_relations,classificationstore_keys, classificationstore_groups WHERE   groupId IN (select id from classificationstore_groups where storeId = '1')  AND classificationstore_relations.keyId = classificationstore_keys.id and classificationstore_groups.id = classificationstore_relations.groupId ORDER BY `keyName` ASC LIMIT 25':

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'keyName' in 'order clause'

![image](https://user-images.githubusercontent.com/21988262/34772308-e150f244-f607-11e7-9294-23d89bd56c61.png)

![image](https://user-images.githubusercontent.com/21988262/34772339-f3b1f7c6-f607-11e7-8e05-1c1666a977c4.png)

**Comment by weisswurstkanone** [comment]
fixed in build 175
