### ISSUE TITLE
recycle bin: allow deletion of filtered item list

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#2436]
Use case:
Delete all items older than 2 weeks. Filtering is perfectly possible but a lot of clicks are needed to delete all of them.

**Comment by weisswurstkanone** [comment]
Introduced a check column and a context menu (build 177). Select model is now a multiselect. Use the checkbox in the header bar to mark all visible rows.

![image](https://user-images.githubusercontent.com/6142086/34877984-a23d7742-f7a8-11e7-80c3-09bd3bbe2f1c.png)
