### ISSUE TITLE
Undefined error on object metadata with new metadata key.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2439]
When metadata key is added to a metarelation field, already recorded datas aren't completed.
So when accessing with PHP to the non defined key an error is produced. This patch just send back null instead of an undefined error (the key must be allowed in all case and not falling in the exception). 

Here: https://github.com/pimcore/pimcore/blob/master/pimcore/models/DataObject/Data/ObjectMetadata.php#L76
`return $this->data[$key];`
should be replaced by:
`return isset($this->data[$key]) ? $this->data[$key] : null;`

Same should be applied to Pimcore 4 as well:
https://github.com/pimcore/pimcore/blob/pimcore4/pimcore/models/Object/Data/ObjectMetadata.php#L73

Thanks.

**Comment by weisswurstkanone** [comment]
thx!
