### ISSUE TITLE
Doc to update for Lock which is in Tool now

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2441]
In the documentation:
https://github.com/pimcore/pimcore/blob/c75105230152bd263d43f8b0da9ae2a7c77579ea/doc/Development_Documentation/19_Development_Tools_and_Details/17_Static_Helpers.md#locking

`Just have a look at Pimcore\Model\Lock and the static class functions`
should be replaced by
`Just have a look at Pimcore\Model\Tool\Lock and the static class functions`

**Comment by weisswurstkanone** [comment]
fixed in build 177
