### ISSUE TITLE
CLI Updater fails with no error on Windows

### ISSUE THREAD

**Issue by alasdair-shields** [pimcore/pimcore#2442]
# Bug Report
Submitted in response to request from Fash on Forum:
https://talk.pimcore.org/t/cli-updater-fails-with-no-error-on-windows/176/4
  
### Expected behavior 
Expect update to succeed.  If update fails then expect an error message

### Actual behavior  
Update fails but reports that it has succeeded.

# Example output from a failed update:
```
$ bin/console pimcore:update -u 128 --env=dev
You are going to update to build 128! Continue with this action? (y/n)y
Starting the update process ...
 98/98 [============================] 100%

Update done!
```

  
### Steps to reproduce  
On Windows 10 run CLI updater:

`bin/console pimcore:update --version --env=dev`

### Notes:
Sourced problem to the following method: UpdateCommand::execute 
pimcore/pimcore/lib/Pimcore/Bundle/CoreBundle/Command/UpdateCommand.php (line 171)

It looks like escapeshellarg() works differently on Windows breaking the JSON formatting.

**Comment by brusch** [comment]
Obsolete, see: #3121
