### ISSUE TITLE
[Assets] Creating asset without binary data and setting type manually creates corrupt database entry

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2443]
```
        $asset = new Asset();
        $asset->setFilename("my-asset3.png");
        $asset->setParent(Asset::getById(1));
        $asset->save();
```

ends up in a database entry without asset type ... when trying to load that asset, exception is thrown...

Solution: don't allow to save assets without a type.

**Comment by weisswurstkanone** [comment]
fixed in build  181

**Comment by fashxp** [comment]
recheck and reinclude automatic detection of file type.

**Comment by weisswurstkanone** [comment]
moved the check to the update method (after mimetype detection)
