### ISSUE TITLE
Adminer / Database Administrator in Pimcore UI produces a warning

### ISSUE THREAD

**Issue by AlternateIf** [pimcore/pimcore#2444]
The Database Administrator produces a warning on **PHP: 7.2** / **Pimcore 5 build 174**

Warning: session_cache_limiter(): Cannot change cache limiter when session is active

this may be related to the php 7.2 changes

@maff

**Comment by maff** [comment]
Also happens on PHP 7.1 when output buffering is turned off (see #2472).
