### ISSUE TITLE
Improve API to save version update note

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#2445]
Currently, in order to save a version note when saving a data object you first have to call  `$object->save()`. Afterwards you have to get the latest version and then update the state on your own.

It would be great if a note could be passed more easily, such as
`$object-save("Product importer update")` or `$object-save("Product asset assigned")` . This would be very helpful for script processing.

Advantages:
- reduced implementation time.
- standardised implementation of that feature.
- easier debugging / tracing of errors if developers use the note feature more frequently.
- easier to understand what hapened for the customer

**Comment by brusch** [comment]
`$object->save('My versioning note');` 
**vs** 
```php
$object->save([
    'versionNote' => 'My versioning note'
])
```

Consistent for all 3 main entities: Assets, Documents & Objects (that support versioning)

**Comment by weisswurstkanone** [comment]
since build 181

**Comment by brusch** [comment]
Please add some hints in the docs. 
doc/Development_Documentation/04_Assets/01_Working_with_PHP_API.md

**Comment by weisswurstkanone** [comment]
build 185
