### ISSUE TITLE
Not minified JS libs in DEV-Mode (editmode) v4.6.3

### ISSUE THREAD

**Issue by BenjaminEden** [pimcore/pimcore#2451]
With enabled dev mode Pimcore should load unminified JS libs in editmode.
There is a small bug, which prevents this:

In /pimcore/lib/Pimcore/Controller/Plugin/Frontend/Editmode.php line 251

`if ($conf->general->devmode) {`

It should be

`if ($conf->general->debug) {`

**Comment by brusch** [comment]
I think there's a misunderstanding. 
It's correctly that the original JS files are only loaded in dev-mode, not when debug mode is enabled.

**Comment by BenjaminEden** [comment]
Oh, sorry. I assumed that this should happen in debug mode. The dev-mode is something I haven't used at all.
Thanks Bernhard!
