### ISSUE TITLE
HeadScript doesnot use CacheBuster

### ISSUE THREAD

**Issue by jansarmir** [pimcore/pimcore#2453]
https://github.com/pimcore/pimcore/blob/6ca91569142e1c20b01a110a40dc9ef6ce94523b/pimcore/lib/Pimcore/Templating/Helper/HeadScript.php#L521

as prepareEntries is implemented, but never used
CacheBuster is not functional

**Comment by maff** [comment]
Thanks for reporting! Will be fixed with build 178.
