### ISSUE TITLE
[Fieldcollections] Add info about if and where field collection is used

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2459]
Show info in field collection definition in which class definitions it is used 

![image](https://user-images.githubusercontent.com/8792145/35037246-4eeaf2ea-fb77-11e7-90c6-aab251d9cd14.png)

**Comment by weisswurstkanone** [comment]
would a similar thing, i.e. overview in the class definition which bricks are allowed also make sense ?

**Comment by weisswurstkanone** [comment]
build 181

![image](https://user-images.githubusercontent.com/6142086/35152088-34865466-fd21-11e7-912b-0df8602182a4.png)

![image](https://user-images.githubusercontent.com/6142086/35152098-4104137c-fd21-11e7-8e7a-173ce17c5244.png)
