### ISSUE TITLE
Exception during FullPageCache for BinaryFileResponse 

### ISSUE THREAD

**Issue by RoKoh** [pimcore/pimcore#2460]
It looks like the FullPageCache tries to Cache a BinaryFileResponse and fails on the serialize function later in pimcore/lib/Pimcore/Cache/Core/CoreHandler.php.

Not sure if it should be cached or can be ignored/skipped.

## Error Log Sample
  
[2018-01-17 16:11:14] pimcore.ERROR: Exception: Serialization of 'Symfony\Component\HttpFoundation\File\File' is not allowed in 
~/www/pimcore/lib/Pimcore/Cache/Core/CoreHandler.php:456 Stack trace: #0 
~/www/pimcore/lib/Pimcore/Cache/Core/CoreHandler.php(456): serialize(Object(Symfony\Component\HttpFoundation\BinaryFileResponse)) #1 
~/www/pimcore/lib/Pimcore/Cache/Core/CoreHandler.php(337): Pimcore\Cache\Core\CoreHandler->prepareCacheItem('output_d13edfb1...', Object(Symfony\Component\HttpFoundation\BinaryFileResponse), NULL) #2 
~/www/pimcore/lib/Pimcore/Cache.php(92): Pimcore\Cache\Core\CoreHandler->save('output_d13edfb1...', Object(Symfony\Component\HttpFoundation\BinaryFileResponse), Array, NULL, 1000, true) #3 
~/www/pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/FullPageCacheListener.php(370): Pimcore\Cache::save(Object(Symfony\Component\HttpFoundation\BinaryFileResponse), 'output_d13edfb1...', Array, NULL, 1000, true) #4 
~/www/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): Pimcore\Bundle\CoreBundle\EventListener\Frontend\FullPageCacheListener->onKernelResponse(Object(Pimcore\Event\Cache\FullPage\PrepareResponseEvent), 'kernel.response', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #5 
~/www/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.response', Object(Symfony\Component\HttpKernel\Event\FilterResponseEvent)) #6 
~/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(191): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.response', Object(Symfony\Component\HttpKernel\Event\FilterResponseEvent)) #7 
~/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(173): Symfony\Component\HttpKernel\HttpKernel->filterResponse(Object(Symfony\Component\HttpFoundation\BinaryFileResponse), Object(Symfony\Component\HttpFoundation\Request), 1) #8 
~/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #9 
~/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 
~/www/web/app.php(55): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 {main} [] []

**Comment by maff** [comment]
`BinaryFileResponse` and `StreamedResponse` are now excluded by default, but behaviour can be altered by handling the `FullPageCacheEvents:: CACHE_RESPONSE` event.
