### ISSUE TITLE
Make creation of trees with many objects easier

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#2461]
# Feature Request 
Creating an initial data object tree with many data objects of the same type can be time-consuming!

Improvement suggestion:
 - add a "Duplicate" function to the tree menue, similar as the "Duplicate Field" feature in the class editor.
 - after selecting the "Duplicate" option, the "rename object"  box should pop up.
- the "rename object" box can have another checkbox "create new object" instead of duplicating content (when selected creates an empty object instead of an existing one).

**Comment by brusch** [comment]
Hmm, for objects this saves only one click and for folders there would be no benefit at all, or I'm missing something?

**Comment by dpfaffenbauer** [comment]
I would love that as well ;)

Also, it would be nice to create a tree with putting this into the "name" box: 'folder1/sub1/sub2/sub3'  ;)

**Comment by dpfaffenbauer** [comment]
or even change the copy&paste for objects/assets/documents to open the rename-box before pasting and give it a name before adding it. Otherwise I have to copy-paste and rename, and the rename is done in 99.999%.

**Comment by andreas-gruenwald** [comment]
@brusch 
Actually you don't save many clicks, but it safes time to lookup the copy and the user doesn't have to wait till the copy has been created, and carry on with their work, while the copy is created in the background.

**Without duplicate-feature:**
1. Right-Click on object.
2. Click "copy".
3. Click "paste".
5. Wait until object has been created.
4. Lookup the copy, right click on "rename".
5. Rename and save.

**With duplicate feature:**
1. Right-Click on object.
2. Click "duplicate".
3. Enter new name and save.
4. Continue with next object, creation is done in background.

I experienced the issue on my own, when supporting a client, and from my point of view I can say that this would be a really nice UX feature.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
