### ISSUE TITLE
[StaticRoutes] Combo for controller is too small

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2462]
![image](https://user-images.githubusercontent.com/8792145/35098666-6e758736-fc55-11e7-8018-a4071524a80c.png)

**Comment by weisswurstkanone** [comment]
An slight improvement could be the matchFieldWidth configuration option.
"...Whether the picker dropdown's width should be explicitly set to match the width of the field. Defaults to true...."

![image](https://user-images.githubusercontent.com/6142086/35099741-700b3196-fc59-11e7-8f05-aeb95d33eedc.png)

**Comment by fashxp** [comment]
yes go for it
