### ISSUE TITLE
Small english translaction fix

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2463]
I just went through the French translation on Pimcore on poeditor which are now 100% filled.
During the translation work i noticed two english translations which need to be corrected. I do it on poedit, but i think they need to be done directly on the github repository instead.

Here they are (key: original wrong value => new value proposed)
```
substract: substract => subtract
operator_php_settings: Operator PHP Un&Serialize => Operator PHP Un&Serialize Settings
```

**Comment by weisswurstkanone** [comment]
fixedi in build 181
please note that a changed the translation key substract as well

**Comment by Yivan** [comment]
Thanks! (i have refilled the new key subtract translation on poedit for french)
