### ISSUE TITLE
[Bug] Colorpicker don't work with manuel color setted

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2465]
The new colorpicker is really great, thanks for it!

I seems there is a bug preventing to fill manually the colors. So for now we have to make it with the mouse and it is not easy to pick an exact color.

Here how to reproduce it on the basic online demo, using Chrome browser stable uptodate:

Create a class with the colorpicker data type, and fill manually color (using the keyboard):

![step1](https://user-images.githubusercontent.com/9025839/35103346-d56042aa-fc65-11e7-9bbd-7c485b5c7a8d.png)

Click ok. The value is not updated and is #ffffff:

![step2](https://user-images.githubusercontent.com/9025839/35103374-ea596df8-fc65-11e7-85f9-7a92c3dc70cc.png)

**Comment by weisswurstkanone** [comment]
Hmm, seems to be a ExtJS bug.
Try the same at
https://examples.sencha.com/extjs/6.0.1/examples/kitchensink/#form-color-picker

**Comment by weisswurstkanone** [comment]
seens to be fixed in 6.2

**Comment by weisswurstkanone** [comment]
fixed in build 181 by adding an override for the Ext.ux.colorpick.Selector constructor
