### ISSUE TITLE
Extension requirements ECommerce framework

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#2466]
# Feature Request 

Can we add the following features to the Ecommerce Core:

1.  Add setter for default currency in Environment:

IEnvironment.php
```php
public function setDefaultCurrency(Currency $currency);
```

Environment.php
```
    public function setDefaultCurrency(Currency $currency)
    {
        $this->defaultCurrency = $currency;
    }
```

2. In the AttributePriceSystem.php line 139 in calculateAmount:
 ```
return Decimal::create((double) $product->$getter());
```
in order to avoid exceptions with null values.

**Comment by fashxp** [comment]
can you provide a pull request for that?

**Comment by fashxp** [comment]
ad 1) ... what would be the usecase for that?

**Comment by ckogler-elements** [comment]
> ad 1) ... what would be the usecase for that?

I would also need the "setDefaultCurrency". Usecase:
You have 2 tenants. Tenant A has EUR and tenant B has CZK .

Currently you can't switch the currency per tenant because the currency can only be defined globaly.

**Comment by andreas-gruenwald** [comment]
@fashxp  See PR https://github.com/pimcore/pimcore/pull/4764 for that.
Hope that will help to close the issue.
