### ISSUE TITLE
unicode character problems in translation CSV file export

### ISSUE THREAD

**Issue by h2g-internetagentur** [pimcore/pimcore#248]
There are unicode de/encoding problems when you export a translation as a CSV file. I did not try importing the generated file again but I guess things would getting worse. But regardless to that, the generated file is not editable in Excel cause all special characters like ä,ö, etc. are replaces by unreadble rubbish like Ã¶Ã©lÃ©

Perhaps you could make use of https://phpexcel.codeplex.com/ ?

**Comment by brusch** [comment]
This is not a problem pimcore can solve. The contents of the CSV are encoded in UTF-8 - this is what you have specify when importing the CSV in Excel. 

Please google for 'excel open utf 8 csv' and you will get thousands of answers.
