### ISSUE TITLE
Console fatal error when using custom environment variable

### ISSUE THREAD

**Issue by kjkooistra-youwe** [pimcore/pimcore#2481]
### Expected behavior 

For the console to work when using a custom environment variable.
  
### Actual behavior 

- Command returns a 255 error code.
- var/logs/php.log shows the following fatal error:

> PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "Pimcore\Log\Handler\ApplicationLoggerDb" has a dependency on a non-existent service "monolog.processor.psr_log_message". in /path/to/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:32

### Steps to reproduce

Run any console command with a different environment set. For example:
`PIMCORE_ENVIRONMENT=testing ./bin/console help`
`./bin/console --env=testing help`

### Additional information

- Pimcore version 5.1.1.
- Updated from Pimcore version 5.0.1 where it worked just fine.
- Using custom testing environment variable since the default test environment variable locks the system into test mode.
- Managed to fix the issue by adding the following to the services section in app/config/services.yml:

`monolog.processor.psr_log_message:
    class: Monolog\Processor\PsrLogMessageProcessor`

**Comment by maff** [comment]
Fixed in e2e2315c54f121573c7b21b723e1be55ccd0c4cc - the `monolog.processor.psr_log_message` service is now always available.
