### ISSUE TITLE
Uploading an existing asset with a capital file extension fails

### ISSUE THREAD

**Issue by StobiTerner** [pimcore/pimcore#2485]
### Expected behavior 
When uploading an asset with a capital file extension (e.g. test.JPG), which already exists in the target folder, the asset should be added and renamed with an index prefix.

### Actual behavior  
The upload hangs and breaks after a while. No asset added.
  
The error does not occur for non capital file extensions (e.g. test.jpg)

**Comment by fashxp** [comment]
cannot be reproduced in latest version
