### ISSUE TITLE
[Targeting] Visualize current target group when editing target group variant of document

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2487]
add a more obvious label somewhere in toolbar

![image](https://user-images.githubusercontent.com/8792145/35263968-28ec1116-001b-11e8-94b1-88c042ea52c5.png)

**Comment by fashxp** [comment]
fixed in build 224

**Comment by Mansoorali-Ali** [comment]
Can we display the content of two target groups having same threshold value in one document ?
