### ISSUE TITLE
[Column Configuration] Date Formatter Operator does not accept sub elements

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2492]
Date Formatter Operator does not allow sub elements when it is added newly to the column configuration
![image](https://user-images.githubusercontent.com/8792145/35273995-c8f1254c-003a-11e8-8fa9-29627f7defa4.png)

when modifying existing column configuration, sub elements are accepted.

**Comment by weisswurstkanone** [comment]
fixed in build 185
