### ISSUE TITLE
TineMCE WYSIWYG Editor

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#2499]

**Comment by dpfaffenbauer** [comment]
That sounds dangerous. A lot of my project depend on it as I either
- installed extensions for it
- changed configurations

So, this is at least a BC Break and needs to be well thought thru.

**Comment by Yivan** [comment]
Is there any reason CKEditor must be replaced ?

**Comment by brusch** [comment]
@Yivan  Yes, version 4 of CKEditor will not be supported forever

We'll perform this change in 3 steps: 
- alternative will be added, but CKEditor 4 will remain the default (config option to change for the new one)
- default will be changed to the new editor (config option provided to switch back to CKEditor
- CKEditor 4 will be removed

**Comment by Yivan** [comment]
@brusch @dpfaffenbauer 
But when you mean replacement, you mean replace it by CKEditor 5 or another editor ?
Isn't CKEditor 5 BC comptible with the 4 ?

**Comment by brusch** [comment]
CKEditor 5 is not backward-compatible to version 4.

**Comment by cadeyrn** [comment]
I hope the "alternative" will be CKEditor 5 because it's not only a new version of CKEditor but a really great WYSIWYG editor which does not depend on the contenteditable attribute [1] like most popular WYSIWYG editors (CKEditor 4, TinyMCE, Redactor, …) which is one of the main reasons for all the pain with WYSIWYG editors.

Yes, CKEditor 5 does not yet have as many features as the CKEditor 4 but enough for a lot of projects and since CKEditor 4 will remain the default in the first step it's okay to have some features at a later point and it would be an investment in the future of content editing. 

[1] https://ckeditor.com/blog/CKEditor-5-A-new-era-for-rich-text-editing/

**Comment by cleggypdc** [comment]
@kirjavascript recommended me this one https://prosemirror.net/ - looks pretty lightweight and supports back to IE11 (eugh)

**Comment by aarongerig** [comment]
I'd recommend https://quilljs.com/ to have another alternative. ;)

**Comment by cadeyrn** [comment]
ProseMirror and Quill are only other WYSIWYG editors which depend on the contenteditable attribute which is a bad thing for a lot of reasons.

**Comment by dpfaffenbauer** [comment]
CKEditor 5 looks promising tbh. If it has the same features as version 4, why not use that. (Providing the BC config @brusch mentioned ;))

**Comment by julmot** [comment]
I would like to push this topic, since there's a bug since 2016 (see #1124) that makes all WYSIWYG fields useless in my opinion, since you can not specify or limt tags and functiononalities users can create and manage. And you don't want to have the possibilities to offer adding headings for example, when placing the WYSIWYG content already inside a heading.

I've already filled a [bug at the CKEditor repository](https://github.com/ckeditor/ckeditor-dev/issues/3361#issuecomment-525672289), however, it's unlikely that this will be solved soon or at all since a contributor mentioned that this is a general architecture problem of CKEditor. And since `customConfig` properties aren't available in CKEditor v5 at all currently, it's unlikely that Pimcore can stick to this integration approach anyway.

So I'm curious @pimcore: What are the current plans to move forward with WYSIWYG editable fields, with which editor or version and in which timeline?

**Comment by cleggypdc** [comment]
Hi, you can specify tags that users are allowed to create, and get around #1124 byt inserting config directly into the editable. See my example, I have disallowed h1 tags on blog post content :)

https://gist.github.com/cleggypdc/e07c8314067e48238e191ecaf57ff9b5

**Comment by julmot** [comment]
Thanks a lot for this tip @cleggypdc! I will try this out next week.

**Comment by julmot** [comment]
It works @cleggypdc, thanks very much! However, two things to notice:

* CKEditor JavaScript functions can not be used inside the configuration, so it still requires a solution @pimcore
* This makes use of something undocumented: For example `enterMode` isn't a documented option in the Pimcore WYSIWYG documentation, but it is in CKEditor. However, seems like Pimcore is passing it to CKEditor, so it just need to be documented @pimcore

**Comment by julmot** [comment]
It works @cleggypdc, thanks very much! However, two things to notice:

* CKEditor JavaScript functions can not be used inside the configuration, so it still requires a solution @pimcore
* For example `disallowedContent`, `allowedContent`, `shiftMode` or `autoParagraph` aren't valid options in the Pimcore [WYSIWYG documentation](https://pimcore.com/docs/5.x/Development_Documentation/Documents/Editables/WYSIWYG.html), however, they are required if it's needed to only allow specific tags @pimcore

**Comment by brusch** [comment]
We should also consider to decouple the WYSIWYG implementation more, so that it would be possible to change the default editor using a bundle ...

**Comment by brusch** [comment]
Ckeditor 5 can't be used as the successor, reason: it's GPLv2 only, see: 
https://ckeditor.com/docs/ckeditor5/latest/support/license-and-legal.html

We need to look for something else then as the default editor. However if we decouple the WYSIWYG editor, someone could provide CKEditor 5 as a bundle, which would be fine if you're using Pimcore CE.

**Comment by brusch** [comment]
Also important for the new editor: it needs to fully support CSP, see #12594

**Comment by NiklasBr** [comment]
The "... or later" part is important here, isn't it?

https://github.com/ckeditor/ckeditor5/blob/master/LICENSE.md

> Licensed under the terms of [GNU General Public License Version 2 or later](http://www.gnu.org/licenses/gpl.html).

https://www.gnu.org/licenses/quick-guide-gplv3.html#new-compatible-licenses

>  GPLv2 is compatible with GPLv3 if the program allows you to choose “any later version” of the GPL

So, couldn't Pimcore choose to license it under GPLv3 for the community edition?

https://www.gnu.org/licenses/gpl-3.0.html#section14

> Each version is given a distinguishing version number. If the Program specifies that a certain numbered version of the GNU General Public License “or any later version” applies to it, you have the option of following the terms and conditions either of that numbered version or of any later version published by the Free Software Foundation. If the Program does not specify a version number of the GNU General Public License, you may choose any version ever published by the Free Software Foundation.

**Comment by brusch** [comment]
@NiklasBr 
> So, couldn't Pimcore choose to license it under GPLv3 for the community edition?

Actually no, not for licensing reasons, but we don't want to maintain 2 editors, one for CE one for EE 😉
But as I mentioned, it should be possible to provide that in a community bundle in future.

**Comment by NiklasBr** [comment]
Why not license the same CK Editor with GPLv2 for EE and GPLv3 for CE?

**Comment by fashxp** [comment]
Pimcore EE is not GPL!

**Comment by NiklasBr** [comment]
Isn't CK Editor 4 used under GPLv2 today in EE or do you have a custom license?

Edit: What I am asking is, what is the material difference between the GPLv2 for CK Editor that allows compatibility with EE today that prevents version 5 from doing the same?

**Comment by fashxp** [comment]
LGPL & MPL vs. GPL only...

**Comment by NiklasBr** [comment]
Which one of those do you consider compatible with the EE license?

**Comment by cadeyrn** [comment]
Did you reach out to CKSource?

> If you are running an Open Source project with an OSS license incompatible with GPL please [contact us](https://ckeditor.com/contact/) and we will be happy to support your project with a [CKEditor 5 license](https://ckeditor.com/wysiwyg-editor-open-source/).

https://ckeditor.com/legal/ckeditor-oss-license/

**Comment by brusch** [comment]
@cadeyrn the problem is **NOT** the community edition licensed under the terms of the GPLv3 which would be compatible, the problem **IS** our enterprise edition, which is licensed under a proprietary license.

**Comment by jdreesen** [comment]
@NiklasBr [MPL](https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)) should be fine for commercial use.

**Comment by NiklasBr** [comment]
> @NiklasBr [MPL](https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)) should be fine for commercial use.

If **Commercial Use** as defined there is your threshold requirement for license choice, GPLv2 which CKEditor uses [also allows Commercial Use](https://tldrlegal.com/license/gnu-general-public-license-v2) (as does [GPLv3 by the way](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3))). What is the material difference in the forms of Commercial Use they allow that makes you say it is incompatible?

**Comment by brusch** [comment]
@NiklasBr commercial use !== commercial license
GPL is a copyleft license, it's not about use, it's about licensing. You can use GPL for commercial purposes, but you need to keep GPL (copyleft) - GPL doesn't mean it needs to be free, just that the source code needs to remain accessible and the license needs to be the same. 

So, PCL is a proprietary license, that is incompatible with GPL. 😉

**Comment by NiklasBr** [comment]
You wrote commercial _use_, which is why I asked.

**Comment by brusch** [comment]
| Editor    | Link                    |   License  | Suitable | Inline-Mode | Comment                                                                             |
|-----------|-------------------------|:----------:|:--------:|:-----------:|-------------------------------------------------------------------------------------|
| Quill     | https://quilljs.com/    |    BSD-3   |     👎    |      ❓      | Last release 3 years ago?                                                           |
| TinyMCE   | https://www.tiny.cloud/ |     MIT    |     👍    |      ✅      | Long history                                                                        |
| Lexical   | https://lexical.dev/    |     MIT    |     👍    |      ❓      | Seems to be quite unstable, frequent API changes                                    |
| Editor.js | https://editorjs.io/    | Apache 2.0 |     👎    |      ✅      | Block-style concept - hard to keep compatibility, limited HTML import functionality |


Many others, see e.g. 
https://github.com/JefMari/awesome-wysiwyg#standalone
https://project-awesome.org/dok/awesome-text-editing
https://github.com/topics/wysiwyg-editor?o=desc&s=stars
https://github.com/topics/rich-text-editor?o=desc&s=stars

Most of them are dead, abandoned, ... 

Any other suggestions?

**Comment by Cruiser13** [comment]
@brusch we recently used https://tiptap.dev on some of our projects and had a great developer experience. License is MIT.
We moved away from quill because of maintenance issues.

**Comment by ChrisB9** [comment]
We, too, used [tiptap.dev](https://github.com/ueberdosis/tiptap) for a project and had a wonderful time integrating it, worked like a charm with the TYPO3 project
But this would be less of a replacement for CKEditor but more of a new page editing experience, replacing/extending areabricks

**Comment by brusch** [comment]
@Cruiser13 @ChrisB9 but tiptap doesn't offer "inline" - editing (floating toolbar) as CKEditor and TinyMCE do, right? 
At least I was not able to find an example for this. Thanks for your feedback!

**Comment by Cruiser13** [comment]
@brusch that's called floating menu for tiptap and is an official extension. You can find it here: https://tiptap.dev/api/extensions/floating-menu
I think that you could style it similary to ckeditor bar since tiptap is very open to any styling. You can consider it a framework, not a plugin solution.

**Comment by brusch** [comment]
@Cruiser13 Thanks! 
Yeah, I've read that it's more a framework than a plugin, but to be honest I'd like to keep the integration effort on our end as low as possible, so probably the plugin approach is the right one for us ...

**Comment by tmannherz** [comment]
@brusch How was/is this not included in the v11 upgrade guide? There no mention that explicit action needs to be taken if you want to continue to use a WYSIWYG in the PIM/CMS. Nor is there any mention that if you've added config specific to CKEditor, that needs to be migrated to support TinyMCE when upgrading.

https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/Upgrade_Notes/
https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/Updating_Pimcore/V10_to_V11/

It would be helpful to have a section about the WYSIWYG for others using these upgrade guides.

**Comment by dvesh3** [comment]
@tmannherz yes, the upgrade guide is missing at the moment. I have created an issue to add the related info to the docs. thanks for reporting :+1:
