### ISSUE TITLE
Vrana/Jush (Adminer) cannot be correctly versionned in the project git repository.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2504]
Adminer need Vrana/Jush and is included in the downloadable stable from the Pimcore website:
http://pimcore.com/download-5/pimcore-stable.zip

Problem is that Vrana/jush is included directly from cloning the git directory, so it creates a .git directory inside /vendor/vrana/jush. This lead to side effects on the main git repository for the project, as it will not include contents of directory having already a .git repo in a subdirectory.

To reproduce:
- Download the master on the Pimcore website
- Make a "git init" and "git add --all", you get this message:
```
warning: adding embedded git repository: vendor/vrana/jush
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint:
hint:   git submodule add <url> vendor/vrana/jush
hint:
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint:
hint:   git rm --cached vendor/vrana/jush
hint:
hint: See "git help submodule" for more information.
```
- If you list tracked files `git ls-tree -r master --name-only` you will see that files inside /vendor/vrana/jush aren't tracked.
- Make a git push
- Another developper make a git pull... /vendor/vrana/jush will be empty : (

This is a knowed problem:
https://sourceforge.net/p/adminer/bugs-and-features/468/?SetFreedomCookie

From here: https://github.com/pimcore/pimcore/issues/2472, more explaination:
```
This is on purpose - the adminer composer package is broken as it does not include its syntax highlighter (vrana/jush) and there is no proper package for that dependency, so Pimcore's composer.json is configured to clone/update vrana/jush directly from its git directory.

See https://sourceforge.net/p/adminer/bugs-and-features/468/
```

Maybe some hints could be given in the Pimcore documentation how to handle it or at least add a warning about it ?
For now, i delete the .git folder in vrana/jush before init git, but this is pretty dirty solution.

Maybe this is a adminer problem, and this issue could be left open as reminder. If there is another solution it will be great.

Thanks.

**Comment by dpfaffenbauer** [comment]
You shouldn’t commit the vendor folder anyway. That’s what the composer.lock file is for. Including all dependencies into the git repo misses the point of having dependency management by composer at all.

**Comment by Yivan** [comment]
Thanks dpfaffenbauer! Yes i know correct workflow is to gitignore vendor directory to keep light repo and use composer for versionning, but in our workflow it is more convenient to put all on git. It was working great until this problem with Vrana/Jush.
We will have to revise our workflow ; )

**Comment by dpfaffenbauer** [comment]
I guess you have to ;)
