### ISSUE TITLE
[Proposal] Add an environment variable for debug email.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2507]
I just saw some changes are made in website settings.
I would like to propose an alternative to issue https://github.com/pimcore/pimcore/issues/1956 which need to wait for a yaml/symfony settings.

Maybe we could at least introduce an environment variable like PIMCORE_DEBUG_EMAIL and if setted it will prevail on the one in system.php.
It will allow to developpers to set it on their environment one time for all (all Pimcore project could use it), and the system.php could be in a versionning system (system_dev.php for instance) so they keep uptodate easily with language addition, and others projects settings which can evolve during the project.

**Comment by brusch** [comment]
This will be possible once #3268 is done.
