### ISSUE TITLE
[Assets] Focal point on images

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#2509]
# Feature Request 
Tweak "Select specific area of image" feature. This is already a great feature, which lets the user select the exact part / outer limit of an image, to be rendered in the frontend.

## Problem description 
It is hard for the user to predict how the image will be rendered in the front end, for example when using different thumbnail settings for various responsive states.
 
## Possible solution
One possible solution would be to add an option to set a focus point (e. g. center of a face) combined with a focal cropping option for the thumbnails (+ crop left or right of focus point). I am open to other suggestions for an improvement.

**Comment by BlackbitNeueMedien** [comment]
That would be a really nice feature. I can also see other areas where this might be useful. If you have a thumbnail definition with media queries, for example, it's also hard to predict what the generated thumbnail will look like considering the different sizes and aspect ratios. Having an option to set a focus point on an asset could help to create a more "reliable" result in the eyes of a user.

**Comment by brusch** [comment]
Maybe it's more useful to set the focus point directly on the asset and not in the context of a document or object. Imho the focus point of an image stays the same, regardless in which context it is used.

**Comment by brusch** [comment]
The focus point should be automatically processed by the `cover` transformation on image thumbnails. The current _Positioning_ setting is then only used as a fallback setting.

**Comment by brusch** [comment]
Also consider TensorFlow for object recognition: 
https://www.tensorflow.org/tutorials/image_recognition

**Comment by ckemptner** [comment]
Face autodetection would be awesome!
