### ISSUE TITLE
"Apply Tags to Children" Error

### ISSUE THREAD

**Issue by sstanzione** [pimcore/pimcore#2513]
"Apply Tags to Children" button causes error. Reproducible on demo site.

Build:
Version: 5.1.1
Build: 179 (2018-01-17T10:58:49+00:00)

Here's the error:

Timestamp: Thu Jan 25 2018 14:45:37 GMT-0800 (Pacific Standard Time)
Status: 500 | Internal Server Error
URL: /admin/tags/get-batch-assignment-jobs
Message: Type error: Too few arguments to function Pimcore\Bundle\AdminBundle\Controller\Admin\TagsController::getSubAssetIds(), 1 passed in /home/pimcore_demo_advanced/www/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/TagsController.php on line 265 and exactly 2 expected
![pimcore error on demo site](https://user-images.githubusercontent.com/35820239/35416612-93fab6c8-01de-11e8-8fc2-82088429e4f9.png)

**Comment by weisswurstkanone** [comment]
related to https://github.com/pimcore/pimcore/commit/d994cf4d7ab280a1b8d8b54ab96064ed5b28c302

fixed in build 188
