### ISSUE TITLE
Dynamic Email Delivery Settings

### ISSUE THREAD

**Issue by jansarmir** [pimcore/pimcore#252]
We have general problem with sending emails with some services, example: mandrill.com
If i set sending email with logger, there is big possibility to be blocked with those email services.

It would be great to have possiblity to define dynamic list of Delivery settings
Those settings would be able to choose in
- Email settings
- Newsletter
- Core logger
- Application logger
- or event more with some name, which could be used in application with \Pimcore\Mail

**Comment by brusch** [comment]
That should be already possible by using the event `\Pimcore\Event\MailEvents::PRE_SEND`. 
See also: #2495
