### ISSUE TITLE
Exception when installing Symfony 3.4.4 via Composer

### ISSUE THREAD

**Issue by skrahlQW** [pimcore/pimcore#2523]
We get the following exception after doing a "composer update":

`Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Pimcore\Tool\ArrayUtils::arrayMergeRecursiveDistinct() must be of the type array, null given, called in D:\Projekte\pimcore-test\pimcore\lib\Pimcore\Bundle\CoreBundle\DependencyInjection\PimcoreCoreExtension.php on line 483 in D:\Projekte\pimcore-test\pimcore\lib\Pimcore\Tool\ArrayUtils.php:33
Stack trace:
#0 D:\Projekte\pimcore-test\pimcore\lib\Pimcore\Bundle\CoreBundle\DependencyInjection\PimcoreCoreExtension.php(483): Pimcore\Tool\ArrayUtils::arrayMergeRecursiveDistinct(Array, NULL)
#1 D:\Projekte\pimcore-test\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass.php(43): Pimcore\Bundle\CoreBundle\DependencyInjection\PimcoreCoreExtension->prepend(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#2 D:\Projekte\pimcore-test\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass.php(39): Symfony\ in D:\Projekte\pimcore-test\pimcore\lib\Pimcore\Tool\ArrayUtils.php on line 33
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception`

This seems to break Pimcore completely. After some research, we found out that this exception is caused by version 3.4.4 of Symfony. When changing the line 
`"symfony/symfony": "3.4.*" `
to 
`"symfony/symfony": "3.4.3" `
in composer.json an reverting symfony to version 3.4.3 all is working fine again.

**Comment by maff** [comment]
Please see https://github.com/pimcore/pimcore/issues/2521. We're currently in the process of fixing this through the updater. In the meantime please set the version manually to 3.4.3 before upgrading to build 189 or patch your installation with https://github.com/pimcore/pimcore/commit/7d6c2168bebe2ada7be66c1af9ad1d07719843fe.

After build 189 the error is fixed and Pimcore works fine with Symfony 3.4.4.
