### ISSUE TITLE
Support of calculated fields in webservice API

### ISSUE THREAD

**Issue by acheloos-m** [pimcore/pimcore#2524]
### Expected behavior 
When querying the webservice api, all class fields should return the value, which is visible in the admin interface. 
For example textAvailable field in demo class 'Product' should return:
`[...]
{
                        "type": "calculatedValue",
                        "value": "completed",
                        "name": "textsAvailable",
                        "language": "en_GB"
 }` 

### Actual behavior  
When using calculated fields, these do always return null in REST requests.  
`[...]
{
                        "type": "calculatedValue",
                        "value": null,
                        "name": "textsAvailable",
                        "language": "en_GB"
 }` 

Also calculated fields are not exported via csv.

### Steps to reproduce  

1. Create API key in demo instance
2. Query a product, e.g. 
`curl https://demo-advanced.pimcore.org/webservice/rest/object/id/1448?apikey=5ac86b4690dae71d0ec353911a74cb2d3afd61968d3fb65ce320568d311fcf61`
3. look for a calculated field, e.g. Base > Data Quality > localizedfields > textsAvailable

# Feature Request 
Support of calculated fields in webservice api

## Feature description 
Using calculated fields, it's quite easy to query for complex data. When using pimcore as the pim backbone, webservice api is a must have.

For example, one can combine several structured fields into one calculated text field, which is queried via REST API by the sales system. Also one could use one api call to get the contents of multi-href linked objects.

Our current solution is to query the parent object and send another query for each linked child object. So with two levels of 3 Objects each this result in in 1 * 3 * 3 = 9 REST Api calls which can put quite stress on the production system. Also the "re-assembling" of the fields into a combined text has to be implemented on client side, which means both sides have to be changed, each time a class changes.

There should be a check in PUT/POST requests to ignore updates on calculated fields of course.

Kind Regards
Martin

**Comment by weisswurstkanone** [comment]
fixed in build 191
