### ISSUE TITLE
User Permission asset_metadata is missing but is checked

### ISSUE THREAD

**Issue by isekep** [pimcore/pimcore#2525]
https://github.com/pimcore/pimcore/blob/62ed16ce1cf15c4745951dd4bb43846a5634b9e5/pimcore/models/Tool/Setup/Dao.php#L126

A user/customer asked us for an error message. He wanted to add some metadata. Unfortunately the permission `asset_metadata` was not set. In admin backend we don't see this permission. This permission is not available in `users_permission_definitions` database table.

Unfortunately it is also missing in demo system.

**Comment by weisswurstkanone** [comment]
fixed in build 191
