### ISSUE TITLE
ExtJs 6 Object Layout

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#253]
I tested the new ExtJs 6 object layout for a complex Pimcore object class and compared it with the old ExtJs 3 version. Looks quite good so far - but I found some issues and improvement ideas:

#### There should be a clearly visible difference between editable and non-editable fields.

In this screen shot the first field is non-editable and the second one editable:
![image](https://cloud.githubusercontent.com/assets/4639428/10117967/306631dc-646a-11e5-8d9f-cc32fc73de26.png)
Drop target icon should be hidden too...

#### Label width setting does not apply to href field within a fieldset (other combinations not tested):
![image](https://cloud.githubusercontent.com/assets/4639428/10117999/9abca628-646b-11e5-9698-ad2315aceaa0.png)
(edit button is not placed perfectly too)

#### The green symbol (jump to inheritance source) doesn't work in my example:
![image](https://cloud.githubusercontent.com/assets/4639428/10118042/f4ae72f0-646c-11e5-821e-e15f06e5b160.png)

#### Tab switch within localized fields let the whole tab panel jump to bottom in some cases:
![image](https://cloud.githubusercontent.com/assets/4639428/10118064/0ffc2dee-646e-11e5-88e0-5a752b5f2fad.png)

#### Object brick styling looks a little bit confusing:
![image](https://cloud.githubusercontent.com/assets/4639428/10117978/7efbeae4-646a-11e5-9fb5-070094a3053c.png)

Old version looks clearer:
![image](https://cloud.githubusercontent.com/assets/4639428/10117990/0552ca90-646b-11e5-8a45-aa8ad20bdae6.png)

Maybe just remove or restyle the message "No further objectbricks allowed"?

#### Header styling of multi-relation fields looks too big and with too much spacing to me compared to other content elements:
![image](https://cloud.githubusercontent.com/assets/4639428/10118008/097d5b8e-646c-11e5-8341-be3d96d3df3e.png)

#####  (Just a matter of taste but some icons are a little bit old fashioned for the new stylish interface. Maybe think about some new icon sets or fonts in future versions? Also icons which are optimized for retina resolutions would be cool.)
![image](https://cloud.githubusercontent.com/assets/4639428/10118104/851877c6-646f-11e5-99cf-1ef4f924a0dd.png)

**Comment by fashxp** [comment]
fixed in build 3774
if some things are still not fixed properly please make seperate issues per topic. thank you.
