### ISSUE TITLE
Show in tree not working when keys have underscores -> collation issue

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#2530]
# Bug Report

## Expected behavior 
Open object, click on button "show in tree", tree jumps to object
  
### Actual behavior  
After clicking "show in tree" pagination of tree stops and does not go to the right page
  
### Steps to reproduce  
1. Create data object with key "aa" in folder x. Copy and paste it until tree items in folder x paginate and the last object on page 1 has a key "aa_*". 
1. Now create object with key "a_". Object gets opened
1. Go to page 1 in tree of folder x
1. click "show in tree" in object "a_"
1. Object does not get found in tree
  
I figured out the problem: Tree items get sort by MySQL. When clicking "show in tree" treenodelocator.js checks the first and last object on the current page and compares their keys to the target object's key with JS string comparison. But objects.o_key has collation ascii_general_ci. In this collation underscores are sort behind characters whereas in JS string comparison "a_" < "aa".

It works e.g. with collation utf8_german2_ci. Perhaps there is a better choice regarding performance.

**Comment by weisswurstkanone** [comment]
maybe this is not relevant anymore as paging will change anyway through https://github.com/pimcore/pimcore/pull/2501 ?

**Comment by BlackbitNeueMedien** [comment]
No, this won't solve this problem because the option to sort by key alphabetically will stay. See https://github.com/pimcore/pimcore/pull/2501/files#diff-5c3fefc8736fc2548d94869c5e3f4742R118
This uses the collation of column objects.o_key.
But pimcore.treenodelocator.getDirection does string comparison of the first and last element's keys, see https://github.com/pimcore/pimcore/blob/46ee9f8c3ef5185f71f8a028204fd1d3bd0acb0b/web/pimcore/static6/js/pimcore/treenodelocator.js#L207-L234

**Comment by michalfilik** [comment]
Yes, @BlackbitNeueMedien has right. It won't solve this issue

**Comment by brusch** [comment]
fixes by #2820
