### ISSUE TITLE
Pimcore Security Adaptations 

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#2537]
This is more a RFC than a issue. We recently worked on a (really long) security report as part of a customer project. They assigned a security company to put our website through its paces :). Beside a lot of server configuration there are also some pimcore related stuff which i want to list here:

## /pimcore/static6/js/lib/jquery.min.js
During the stress tests they fetched the 2.1.4 version of jquery which has some security issues. I know that you guys [just upgraded](https://github.com/pimcore/pimcore/issues/2498) to 3.3.1 but most likely there will be some other troubles in the near future.

#### Solution
Should we update the `.htaccess` to disable access to those files (/pimcore/static6/*) if no pimcore authentication is active?

##  X-Frame-Options
They also claimed to add the "anti-clickjacking" `x-frame-options` to `DENY` or `SAMEORIGIN`to each request to prevent iframe highjacking. While this could be easily done with a simple kernel response event, i'm wondering if the (i would suggest `sameorigin`) state should be implemented as default by pimcore.

##  /admin
This one is the most obvious one and those guys nearly had a heart attack after the `/admin` ping returned a 200 status code... :) So, obviously we don't need to go deep with this. 

#### Solutions
- Implement a backend setting for a custom `/admin` route. But i guess this sounds easier than it is
- Recently i read a [interesting approach](https://groups.google.com/d/msg/pimcore/tjXReAf0wyc/FmiPgOU5AwAJ) by @Yivan which in my opinion seems to be sexy simple, smart and secure enough. I never tested it with P5 though. If this works, then there should be a guide in the pimcore installation section i think.

## X-Powered-By
The last point on our list they criticized is the `x-powered-by` header entry. _"It's easy to detect the system behind a website and could simplify the hunting for security breaches."_ Like the x-frame-option, this could be removed with a prioritized event but maybe we don't need it at all?

**Comment by Yivan** [comment]
We get recently a security audit made by a specialized firm too on a Pimcore (version 4) project.

Admin section passes the test, with just some recommandation:
- Login Brute Force Vulnerability:
  - maybe it should be tightened by using strong time_cost option for password_hash or using a simple sleep to slow down brute force attack.
  - a system of number connection attempts during a time frame could be activated, so if user try to much time in a short period, it will have to wait longuer until he manage to log (better than balcklist him becaude it need OP intervention to un-blacklist it).

Report give this recommandation:
```
Implement a mechanism that will limit the number of attempts for a given username. This will prevent any brute forcer to test for more complex passwords.
Enforce a password policy that will make sure that the password is complex enough to prevent any easy guess (password equals username, or is a number, or a
dictionary word). It is really important because if a password can be guessed in one attempt (for example, password equals username) then any limitation of
number of attempts would useless.
It is recommended that a password has at least 8 characters containing numbers and special characters. Avoid replacing a letter that looks like a number by its
corresponding number (for example, o with zero, e with 3) since many brute forcers do check for them.
```
I know Pimcore restrict password to a complexe one, but it could be improved by library like https://github.com/dropbox/zxcvbn It could give advice during password creating or we could enforce a minimum complexity in a Pimcore settings for instance.

- Slow HTTP POST vulnerability
This one is more server side i think, and I don't know if Pimcore can do for it.
More information here:
https://blog.qualys.com/securitylabs/2011/11/02/how-to-protect-against-slow-http-attacks
And a tool to test: https://github.com/shekyan/slowhttptest

---

Like @solverat, the X-Frame option was mentionned too. If i remember we setted it on the webserver level, but it could be great if setted by Pimcore so it is protected by default.

For the change of `/admin` url, i think the method i proposed should work on Pimcore 5, as it work on several CMS we use (Pimcore 4, Magento, ...). As it is only based on cookies/redirection, i think it could be handled by Pimcore as system setting directly, so we don't need to edit htaccess and create an index file.

**Comment by fashxp** [comment]
hi guys, 
please don't create github issues for security topics - please use security@pimcore.org instead!

thx...

**Comment by solverat** [comment]
hey @fashxp, i'm aware of it but i think those points aren't real evil vulnerabilities which need to be kept from public.

**Comment by Yivan** [comment]
Thanks for remembering this email adress, i was aware of it too. I gave only generic recommandation in this issue, no real vulnerabilities which can be used. For sure we will not post vulnerablities on github and use this email instead.

If you want @fashxp you (or i) can delete my comments if you think it is better this way.

**Comment by brusch** [comment]
## jQuery
Unfortunately we cannot easily restrict the access to static files to authenticated backend-users using rewrite rules, for that we'd have to proxy all requests through PHP. 
In general I'm wondering how the accessibility of the jQuery file should affect security without having the script embedded somewhere on a HTML page...? 
Some more info on that would be appreciated. 

## X-Frame-Options
Pimcore utilizes the `X-Frame-Options` header already in editmode, to prevent click-jacking. 
https://github.com/pimcore/pimcore/blob/97d2987fe526dee6f1a467841cf8cec81ecd3a7b/pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/EditmodeListener.php#L148
I don't think it's a good idea that Pimcore enforces this header in general, I'm pretty sure this will break a lot of things :| 

## `/admin` 
I like the approach @Yivan has implemented.
I've created a dedicated issue for that one #2544

## X-Powered-By
This header is used by platforms such as https://builtwith.com/ and https://www.wappalyzer.com/ to identify Pimcore. Nearly every system exposes some kind of characteristics which lets them identify´ (see BuiltWith), either in the generated source code or with custom header, so I don't think this is a critical one. 

## Slow HTTP POST 
Needs to be done on the webserver. 

## Login Brute Force
There's a protection against brute force: 
https://github.com/pimcore/pimcore/blob/5483c6f0fa00cfb4026b15ef5ffbfaf9dcee66ca/pimcore/lib/Pimcore/Bundle/AdminBundle/Security/BruteforceProtectionHandler.php#L24

**Comment by Yivan** [comment]
Many tanks brush for those details. Very happy to see there is a brute force protection, this is great!
