### ISSUE TITLE
MethodArgumentValueNotImplementedException 

### ISSUE THREAD

**Issue by Biggisb** [pimcore/pimcore#2540]
Hey All!

> The Symfony\Component\Intl\DateFormatter\IntlDateFormatter::__construct() method's argument $locale value 'de' behavior is not implemented. Only the locale "en" is supported. Please install the "intl" extension for full localization capabilities.
> 
> Symfony\Component\Intl\Exception\MethodArgumentValueNotImplementedException:
> The Symfony\Component\Intl\DateFormatter\IntlDateFormatter::__construct() method's argument $locale value 'de' behavior is not implemented. Only the locale "en" is supported.  Please install the "intl" extension for full localization capabilities.
> 
>   at C:\xampp\htdocs\pimcore\vendor\symfony\intl\DateFormatter\IntlDateFormatter.php:138
>   at Symfony\Component\Intl\DateFormatter\IntlDateFormatter->__construct('de', 0, 0, 'Europe/Vienna', 1, 'EEEE')
>      (C:\xampp\htdocs\pimcore\pimcore\lib\Pimcore\Tool\Requirements.php:588)
>   at Pimcore\Tool\Requirements::checkPhp()
>      (C:\xampp\htdocs\pimcore\pimcore\lib\Pimcore\Install\Installer.php:146)
>   at Pimcore\Install\Installer->checkPrerequisites()
>      (C:\xampp\htdocs\pimcore\pimcore\lib\Pimcore\Bundle\InstallBundle\Controller\InstallController.php:62)
>   at Pimcore\Bundle\InstallBundle\Controller\InstallController->indexAction(object(Installer), object(ProfileLocator))
>      (C:\xampp\htdocs\pimcore\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:151)
>   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
>      (C:\xampp\htdocs\pimcore\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:68)
>   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
>      (C:\xampp\htdocs\pimcore\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php:202)
>   at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
>      (C:\xampp\htdocs\pimcore\web\install.php:72)
I fresh installed Pimcore with composer on Windows 10 inside Xamp and gettings this Error!
I used composer require symfony/intl (cuz stackowerflow told me to do that), but that didnt help still getting the error any help?

**Comment by brusch** [comment]
Read the error message ... 
**Please install the "intl" extension for full localization capabilities.**

So you need to install the intl PHP extension on your system. 
http://php.net/intl

**Comment by Yivan** [comment]
@brush i don't know if possible, but as you are thigthening the check requirement (i saw for mariadb/mysql, great thing), the installer could check to see if required php extension are ok ? I know there are already some checks done at this level, but how @Biggisb manage to go on the installation without the INTL requirement ?

**Comment by brusch** [comment]
@Yivan Done.
