### ISSUE TITLE
[Bug] New image editor break asset when saving

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2548]
I just try the new image editor on the pimcore 5 online demo.

If you:
- open an asset
- draw a line
- click save in the editor windows
- go back to view tab: the asset isn't modified
- if if reloading the asset object, it will no more show the image, as if it was broken

Browser used for this test: chrome last stable on Windows.

**Comment by Yivan** [comment]
I tried to download the asset after to see if binary has been damaged, and it is the case, the image is corrupted.

**Comment by brusch** [comment]
[06-02-_2018_17-33-37.zip](https://github.com/pimcore/pimcore/files/1699906/06-02-_2018_17-33-37.zip)

Works fine for me ... any more details, such as browser, ...? 

Thanks!

**Comment by Yivan** [comment]
@brusch Thanks for your feedback. I tried again and like you said i cannot reproduce it too...
Very strange. Maybe because someone acted on the demo on the same time doing some stuff or i tested while demo reinit/reinstall...

You can close the task, if it happen again i will comment here.
