### ISSUE TITLE
ExtJs 6 - Custom object icons are not displayed

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#255]
When a custom icon is added to a class it will not be displayed in the objects and class editor tree:

![image](https://cloud.githubusercontent.com/assets/4639428/10118260/67d19ce2-6474-11e5-922f-c6030b484dbf.png)

**Comment by weisswurstkanone** [comment]
Unable to reproduce. Seems to be feature of 3.4 that backslashes also work.
