### ISSUE TITLE
Add Predefined Data Templates for Document Images

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#2551]
# Feature Request 

Add Predefined Data Templates for Document Images like for Object Images
https://pimcore.com/docs/5.1.x/Development_Documentation/Objects/Object_Classes/Data_Types/Image_Types.html#page_Predefined-Data-Templates
  
example:
````html
<?= $this->image("myImage", [
    "title" => "Drag your image here",
    "width" => 200,
    "height" => 200,
    "thumbnail" => "contentimages",
    "config" => [
		"marker" => [
			"menuName" => "marker config 1",
			"name" => "hotspot name",
			"data" => [
				"name" => "my asset href",
				"type" => "asset"
			]
		],
		"hotspot" => []
	]
]); ?>
````

**Comment by ckogler-elements** [comment]
Implemented with https://github.com/pimcore/pimcore/pull/2554
