### ISSUE TITLE
Missing build or release instruction

### ISSUE THREAD

**Issue by johnbendi** [pimcore/pimcore#256]
There is no concrete instruction on how you build the codebase for a release.

**Comment by brusch** [comment]
There's one in the wiki, but only for the release managers - not public.

**Comment by johnbendi** [comment]
Does it mean I won't be able to access the instructions?  I don't really understand your reply.

**Comment by brusch** [comment]
Yes, this description is only available to release managers. 
Why you would need this?

**Comment by johnbendi** [comment]
When I need to deploy at a particular build or a patched version from the codebase without having to checkout the worktree and have all manner of files accompany it. In essence I should be able to get something similar to the files you offer for download.
