### ISSUE TITLE
"Extras -> Download System Languages" missing with pimcore 3.1.1

### ISSUE THREAD

**Issue by rolandstoll** [pimcore/pimcore#257]
With pimcore 3.1.1 "Extras -> Download System Languages" is not available anymore. On the other hand a couple of new languages are now installed automatically, some are even activated in some areas (e.g. "Admin Translation").

**Comment by brusch** [comment]
That's true. 
We're using now POEditor https://poeditor.com/join/project/VWmZyvFVMH 
All translations are now part of the distribution package and are versioned in Git. 

Cheers

**Comment by Kodmaster** [comment]
The problem is when I select a language (i.e French) from the dropdown list (Default Language in Admin-interface) in Settings/System Settings, it does not work. The changes are not saved after language selection. Do you have any idea what it could be?

Thanks in advance.

**Comment by brusch** [comment]
This is not really releated to this, but i think this sounds like a permission problem. Please ensure that /website/var/config/system.xml is writeable.

**Comment by Kodmaster** [comment]
Sorry. Since this post was mentioning the new system languages, I used the opportunity.
