### ISSUE TITLE
stacked edit-buttons on edit-view while using bricks

### ISSUE THREAD

**Issue by eqvvs** [pimcore/pimcore#2575]
# Bug Report
All Edit-Buttons are stacked in editmode. 

using this functions doesn't solve the problem completely 
```
public function getHtmlTagOpen(Info $info)
    {

       if( !$info->getView()->get('editmode') ) {
           return '';
       }

    }

    public function getHtmlTagClose(Info $info)
    {

       if( !$info->getView()->get('editmode') ) {
           return '';
       }

    }
```

# Suggested Solution

on line 96 in editmode.css (web/static6/css/) add this:

```
    position: relative;
```

before:
```
.pimcore_block_entry {
	clear:both;
}
```
after:
```
.pimcore_block_entry {
	clear:both;
        position: relative;
}
```

**Comment by mittererr** [comment]
It is still possible to add a custom editmode.css in an extra bundle. I prefered this way. 
See [Docs](https://pimcore.com/docs/5.0.x/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/Loading_Admin_UI_Assets.html)

**Comment by brusch** [comment]
@mittererr @eqvvs You don't even need an extra bundle you can do this also directly on the existing AppBundle. 

@eqvvs can you provide us a example so that we can reproduce the issue? Thanks a lot!

**Comment by brusch** [comment]
Or just include the stylesheet in your layouts: 
```php
<?php if($this->editmode) { ?>
    <link rel....>
<?php } ?>
```
