### ISSUE TITLE
Language Chooser Localization Bug en and en_US

### ISSUE THREAD

**Issue by eqvvs** [pimcore/pimcore#2578]
# Bug Report

Aloha Pimconauts!

There is a not so funny bug in the Language Chooser. If you activate englisch and englisch USA in your project, you see the language "englisch" twice. but it must be "englisch uk" and englisch us". 

it is important to seperate this because the date-time output has another format in us as it is in europe and many other country. In case that the customer want to get a nother formatted date out on e.g. news blog you have to activate both langs. 

please fix this or give me a hint were the lang-matching is done. i will fix this and give you a push request.

best wishes

**Comment by brusch** [comment]
Where exactly do you mean? In the demo project?
