### ISSUE TITLE
Advanced Image (objects) bug in combination with thumbnails

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#258]
An example:
```php
<?if($image = $article->getImage()) {?>
        <?=$image->getThumbnail('image-small')->getHtml()?>
<?}?>
```

This works perfectly when an image is added to the advanced image field. When no image is added, it works perfetcly too.

But when an image is added and later on will be removed by clicking on the delete button an exception will be thrown in the template.
![image](https://cloud.githubusercontent.com/assets/4639428/10216873/855d0042-682c-11e5-899d-05ed988dc24b.png)

```
Call to a member function getHtml() on string
```

It's easy to handle this with an additional if in the template but I think it's is a bug. Especially this behavior is hard to test...

**Comment by brusch** [comment]
Thanks!
