### ISSUE TITLE
GA overview - missleading source tooltip

### ISSUE THREAD

**Issue by jansarmir** [pimcore/pimcore#2583]
https://github.com/pimcore/pimcore/blob/02b70e96c27e61c4df66d8d54af82d196997e7d8/web/pimcore/static6/js/pimcore/report/analytics/elementoverview.js#L180

tooltip shows pageviews with % suffix, which is confusing

i suggest something like this: google 587 (13 %)

**Comment by brusch** [comment]
Can you create an PR for that? :) 
Thanks!
