### ISSUE TITLE
create redirect for old path - partial functional

### ISSUE THREAD

**Issue by jansarmir** [pimcore/pimcore#2584]
https://github.com/pimcore/pimcore/blob/02b70e96c27e61c4df66d8d54af82d196997e7d8/pimcore/models/Document/Page.php#L126

redirect is created, but without type and regex option
so it requires manualy modification of created redirect in UI to add those options, to work correctly

**Comment by maff** [comment]
Thanks for reporting! Will be fixed with build 202.
