### ISSUE TITLE
Referenced, deleted object bricks in versions causes error on restore

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#2585]
When an object brick gets deleted, object versions stay untouched (clearly it would be too much effort to read all object versions). If one wants to restore an old version which had the deleted brick assigned there is the error
`Error: Pimcore\Model\DataObject\ClassDefinition\Data\Objectbricks::checkValidity(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "Pimcore\Model\DataObject\Objectbrick\Data\Brick" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition`

Could this be programmed more defensively by simply checking if the brick still exists when loading object data?

**Comment by brusch** [comment]
Yep, should be possible - we'll check.

**Comment by weisswurstkanone** [comment]
build 205
