### ISSUE TITLE
The file is giving a PDO error during upload

### ISSUE THREAD

**Issue by omeryuce** [pimcore/pimcore#2587]
Hello,

I use this software for digital asset management. But I was taking a PDO error. I finally found the cause of the mistake.

You should see the screen below. This problem is caused by a Turkish character (I and ı).

Is there a way to solve this problem?

Error message:
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '/sadBASINasdaassad/2017/-Buyuksehir den irakli depremzedelere ya' for key 'fullpath'' in /data/wwwroot/pim463.core/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228 Stack trace: #0 /data/wwwroot/pim463.core/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array) #1 /data/wwwroot/pim463.core/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array) #2 /data/wwwroot/pim463.core/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array) #3 /data/wwwroot/pim463.core/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `as...', Array) #4 /data/wwwroot/pim463.core/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Zend_D in /data/wwwroot/pim463.core/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

https://i.hizliresim.com/D7BLoy.jpg

Test file name:
Büyükşehir den ıraklı depremzedelere yardım Malatya Haberleri.png
Büyükşehir den Iraklı Depremzedelere Yardım Malatya Haberleri.png

Pimcore 4.4.3 and 4.6.3

**Comment by brusch** [comment]
This should be solved by #1754 unfortunately this is only v5. 
Can you verify that it is working in our demo? 
https://demo-basic.pimcore.org/admin/ (admin/demo) 

Thanks!

**Comment by omeryuce** [comment]
The new version gives a similar error.

http://prntscr.com/ie0csl

`{"success":false,"message":"An exception occurred while executing \u0027INSERT INTO assets (`filename`, `path`, `parentId`) VALUES (?, ?, ?)\u0027 with params [\u0022Bu\\u0308yu\\u0308ks\\u0327ehir den \\u0131rakl\\u0131 depremzedelere yard\\u0131m Malatya Haberleri.png\u0022, \u0022\\\/problem\\\/\u0022, 71]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry \u0027\/problem\/-Bu\u0308yu\u0308ks\u0327ehir den \u0131rakl\u0131 depremzedelere yard\u0131m M\u0027 for key \u0027fullpath\u0027"}`

**Comment by brusch** [comment]
Interesting ... maybe this is caused by the tables collation (`utf8_general_ci`)? 
Is the difference of the characters `I` and `ı` only the case, or are they completely different letters?

**Comment by omeryuce** [comment]
This is the database structure.

https://i.hizliresim.com/nOWm0a.png

**Comment by brusch** [comment]
Yes, so the standard Pimcore database schema ;) 
But my question was if this could be an uppercase/lowercase problem?

**Comment by omeryuce** [comment]
Both I and ı are exact same letters in Turkish. But as you know they are totally different letters in English.

So in Turkish "I" is not İ or i

Also İ is not I and ı

http://turkishbasics.com/grammar/alphabet.php

**Comment by brusch** [comment]
Ok if `I` and `ı` are exactly the same, the behavior of Pimcore is correct.

**Comment by omeryuce** [comment]
Windows and Mac computers allow these files to be created because they are different. At the very least, can you add an attachment like 1 or 2 at the end when uploading such files?
