### ISSUE TITLE
[DOC] Mariadb requirements should be 10.2 minimum.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2595]
Some recent changes seems not to be compatible with mariadb 10.1:
https://github.com/pimcore/pimcore/issues/1754

I think the 10.0 could be compatible but not the 10.1 because of a bug which will not be backported it seems, please see:
- https://jira.mariadb.org/browse/MDEV-14904
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886756

innodb_default_row_format option doesn't exist in 10.1, so it is needed to be set manually (something like that: https://mariadb.com/kb/en/library/how-to-change-innodb-fileformat-to-barracuda/). I think Pimcore set it during installation, but in update ?

Maybe to be safe 10.2 minimum mariadb should be pointed to requirements (the 10.2 is a more better backport from mysql 7.1). As it is state in the link i gave before:
```
PS: This problem doesn't exist with MariaDB >= 10.2 or MySQL 5.7 as
both switched to `Barracudea` as default `innodb_file_format` along
with `innodb_large_prefix` and `dynamic` as default row format.
```
So hinting directly to 10.2 in documentation will be better as it is natively configured to those new Pimcore requirements.

Thanks.

**Comment by brusch** [comment]
`innodb_default_row_format ` isn't need by Pimcore, so everything should be ok.
