### ISSUE TITLE
Object tree is slow with a lot of data

### ISSUE THREAD

**Issue by jakubderdziak** [pimcore/pimcore#2597]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [ ] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [ ] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [ ] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [ ] There's no existing ticket for the same issue
- [ ] Remove unused sections from below and this bullet points
  
### Expected behavior 
Expanding tree element should be fast
  
### Actual behavior  
For 1 500 000 can be really slow
  
### Steps to reproduce  
1. Create folder in Data Objects -> Home
2. Create 10 subfolders within folder created in 1.
3. Into each of subfolders generate 100 000 objects
4. Refresh page
5. Try to expand folder created in 1.

**Comment by weisswurstkanone** [comment]
see PR
