### ISSUE TITLE
Slow count query children count

### ISSUE THREAD

**Issue by jakubderdziak** [pimcore/pimcore#2601]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [ ] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [ ] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [ ] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [ ] There's no existing ticket for the same issue
- [ ] Remove unused sections from below and this bullet points

### Expected behavior 
Count query should be fast
  
### Actual behavior  
For 600 000 elements in folder it can take few seconds.
  
### Steps to reproduce  
1. Create folder
2. Create subfolder
3. Generate 600 objects into subfolder
4. Refresh page
5. Click + next to folder
6. Click + next to subfolder

Reason lies here:

https://github.com/pimcore/pimcore/blob/master/pimcore/models/DataObject/AbstractObject/Dao.php#L334

WHERE IN for 600 000 is terrible slow, and probably not necessary in STR provided above (since this flow uses all types: https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectController.php#L141

## Very simple walkaround: 
```php
            $dbObjectTypes = $this->db->fetchCol('SELECT o_type from objects GROUP BY o_type');

            $query = "SELECT COUNT(*) AS count FROM objects WHERE o_parentId = ?";

            //If there are more types in db than in provided objectTypes, then we don't need WHERE IN
            if (!empty(array_diff($dbObjectTypes, $objectTypes))) {
                $query .= " AND o_type IN ('" . implode("','", $objectTypes) . "')";
            }
```

## Better solution:
allow 

```php
getChildAmount(null);
``` 

 that will skip whole "WHERE IN" part, and call it this way from Controller.

**Comment by weisswurstkanone** [comment]
PR welcome :-)

**Comment by jakubderdziak** [comment]
@weisswurstkanone Just to be sure: Are the

```php
[DataObject\AbstractObject::OBJECT_TYPE_OBJECT, DataObject\AbstractObject::OBJECT_TYPE_FOLDER,
DataObject\AbstractObject::OBJECT_TYPE_VARIANT]
```

all possible types in objects? Is there any list of all types within code?

**Comment by weisswurstkanone** [comment]
guess so

CREATE TABLE `objects` (
	`o_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`o_parentId` INT(11) UNSIGNED NULL DEFAULT NULL,
	`o_type` ENUM('object','folder','variant') NULL DEFAULT NULL,

**Comment by jakubderdziak** [comment]
@weisswurstkanone Got some strange build error. Can you verify/restart?

**Comment by weisswurstkanone** [comment]
see https://github.com/pimcore/pimcore/pull/2602
