### ISSUE TITLE
Multihref: Cannot drop folders if there is a class list specified.

### ISSUE THREAD

**Issue by go4webch** [pimcore/pimcore#2603]
If you have a multihref editable configured to accept object folders or objects of a certain class, you can't drop folders in it:

**Configuration**
`
echo $this->multihref("myMultihref",  [
    "types" => ["object"], 
    "subtypes" => [
        "object" => [
            "object", 
            "folder"
        ]
    ],
    "classes" => [
        "myObject"
    ]]);
 `

**Expected behaviour**
A user should be able to either drop objects of the class 'myObject' or object folders into the element

**Actual behaviour**
You can only drop objects of the class 'myObject' into the element

**Explanation**
The code is found at web/pimcore/static6/js/pimcore/document/tags/multihref.js:249

The code checks first the type (asset, document or object). If one matches it reads the configuration and sets the checkSubType and checkClass variables. If there is a class list given, it enables the class check which then disallows folders to be dropped.

**Solution 1**
Insert the following code at line 294:
`
if (data.data.type == "folder" && checkClass) {
    checkClass = false;
}
`
This disables the check if the subtype is a folder

**Solution 2**
Change the line 303 from 
`if (checkClass) {`
to
`if (checkClass && data.data.className) {`

This disables the check if there is no class name given.

I'd prefer the solution 1, since it is self explanatory, though the solution 2 is a bit cleaner.

**Comment by weisswurstkanone** [comment]
fixed in build 205
