### ISSUE TITLE
[Translations] Option for Multiline and HTML

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#2605]
There should be 1 additional column with a select field to set a type for a translation, possible options: 
- Default
- Multiline
- HTML

The editor of the row should change accordingly to the value of the type.

**Comment by weisswurstkanone** [comment]
There will be no additional column. Instead:
- add cell context menu to choose between plain text multiline and html editor
- item click will open the html editor if html stuff is detected
- or as fallback will open the multiline editor if newlines are detected
- or as fallback will behave as usual

![image](https://user-images.githubusercontent.com/6142086/37406114-aff1fd90-2796-11e8-981a-dbe89193d53d.png)

![image](https://user-images.githubusercontent.com/6142086/37406152-c2f519fe-2796-11e8-8e2d-73a30661e849.png)

![image](https://user-images.githubusercontent.com/6142086/37406179-d6d26d32-2796-11e8-9e19-8b44b4caf920.png)

**Comment by weisswurstkanone** [comment]
build 224
