### ISSUE TITLE
[Assets] Add download option to tree context menu

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#2609]

**Comment by jorisros** [comment]
Printscreen how it looks now.

<img width="282" alt="screen shot 2018-02-19 at 09 34 26" src="https://user-images.githubusercontent.com/752283/36368588-3fea97dc-1558-11e8-9642-056f7a1166b0.png">

**Comment by weisswurstkanone** [comment]
Does this work for single files as well ?

**Comment by jorisros** [comment]
No its only working on folders at the moment. Is it needed on singles files to download as zip?

**Comment by fashxp** [comment]
would be nice, yes.

**Comment by jorisros** [comment]
Added the download functionality to a single asset.
<img width="428" alt="screen shot 2018-02-19 at 22 12 38" src="https://user-images.githubusercontent.com/752283/36397451-22ecd68e-15c3-11e8-9c7f-0344e2b2e503.png">
