### ISSUE TITLE
Adminer not working properly anymore

### ISSUE THREAD

**Issue by nicogasque** [pimcore/pimcore#2610]
Hi,

Cannot access to Tables or Optimize, Repair,... via GUI on Pimcore 5.1.3 Build: 197 

The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

This is a fresh installation. 

Thanks

**Comment by AlternateIf** [comment]
trying to open a table in database administration on build 202 i get an exception in vrana 'Call to a member function tableHelp() on null'

**Comment by nicogasque** [comment]
Hello,

Is anyone know why I can't access to database tables in GUI.

Thanks

**Comment by BlackbitNeueMedien** [comment]
When opening a table structure or table data an exception gets thrown (resulting in a 500 error).
See https://demo-basic.pimcore.org/admin/external_adminer/adminer?username=pimcore_demo_basic&db=pimcore_demo_pimcore_basic&table=assets to see the error.
Steps to reproduce:
1. open database administration tool
1. klick any table

As $driver is a global variable it may also be an error outside of vrana/adminer.

Current workaround is to downgrade to 4.4.*

**Comment by brusch** [comment]
https://sourceforge.net/p/adminer/bugs-and-features/601/

**Comment by brusch** [comment]
Problem was already fixed in Adminer: https://github.com/vrana/adminer/pull/257 
We just have to wait for a new version, afterwards a `composer update` will fix the problem.
