### ISSUE TITLE
[BUG] i don't get the value of the default language by calling a method, except i give the lang-string of default language by Pimcore\Tool (since update 5.1.3)

### ISSUE THREAD

**Issue by eqvvs** [pimcore/pimcore#2614]
### Expected behavior 

if i call a method of a class ( e.g. getName() for the name-field ) without a language i get the name of the field the default language is defined for. used in a class-override.
  
### Actual behavior  
  
i get null. i have to give the default language from \Pimcore\Tool::getDefaultLanguage().

### Steps to reproduce  

don't know, it is since update to pimcore 5.1.3.
  
### Code example 
```php

// Expected and before 5.1.3 worked
public function save(){

       $name = $this->getName($language);

        if(null == $this->getName($language))
             $name = $this->getName();
        
        ... some other code
}

// Actual "fix"
public function save(){

       $name = $this->getName($language);

        if(null == $this->getName($language))
             $name = $this->getName($defaultLanguage);
        
        ... some other code
}

```

**Comment by brusch** [comment]
When calling `$this->getName()` without a language, Pimcore's behavior isn't to use the default language, it uses the language on the current request if possible, only if this fails, Pimcore uses the default language, see: https://github.com/pimcore/pimcore/blob/2e380453ea022307fd8eca5ac2d99b3ce4ac2fa4/pimcore/models/DataObject/Localizedfield.php#L210

So I guess what changed in your case was that the locale service now returns a valid language.
