### ISSUE TITLE
\Pimcore\Mail treats cyrillic incorrectly.

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#262]
By using
```
$mailer = \Pimcore\Tool::getMail($recipients, $subject);
$mailer->setFrom($email);
$mailer->setReplyTo($email);
$mailer->setBodyHtml(nl2br($message));
$mailer->send();
```

Put cyrillic in $message and you will receive symbols like (you may put "кирилица има тук"):
"ÑÑÐ¾Ð±ÑÐµÐ½Ð¸Ðµ Ð¾Ñ ÑÐ¸ÑÐ¼Ð°"

System: PHP 5.6.13, Apache 2.2.13
default_charset is UTF-8

If you need more details to reproduce, please ask.

By sending same data in the same environment by using Zend_Mail the message is correct.

I noticed that third library "URL2" is doing something by using substr and strlen but this may be not accurate on multibyte strings so it must use "mb_" prefixed functions.

**Comment by brusch** [comment]
Just tested the following: 

```php
$message = "кирилица има тук";
$mailer = \Pimcore\Tool::getMail("pimcore@byom.de", $message);
$mailer->setFrom("pimcore@byom.de");
$mailer->setReplyTo("pimcore@byom.de");
$mailer->setBodyHtml(nl2br($message));
$mailer->send();
```

without any problems. 
you can try it yourself (byom.de is a trashmail provider).

**Comment by kanevbg** [comment]
Okay, let me check more in depth the buggy case it may be already solved because right now similar project is working well but with version 3.0.6. The problem appears on 3.0.5 installation.

**Comment by brusch** [comment]
ok, please come back on this issue if you have a reproducible test-case (or pull request ;-)). 

Thanks!
