### ISSUE TITLE
About AWS Aurora

### ISSUE THREAD

**Issue by lorextera** [pimcore/pimcore#2620]
Hi there,
I need to create a new db for a new Pimcore 5 installation in an AWS Aurora instance that contains a production db for Pimcore 4.

The [documentation](https://pimcore.com/docs/5.0.x/Development_Documentation/Installation_and_Upgrade/System_Requirements.html#page_System-Variables) suggests to configure mysql with these system variables: 
```
innodb_file_format = Barracuda
innodb_large_prefix = 1
innodb_file_per_table = 1
```
My questions:
1. Is this configuration mandatory for AWS Aurora? Can I ignore it?
2. Is this configuration dangerous for the Pimcore 4 installation?
3. Why `innodb_file_per_table = 1` ? :)

Thanks

**Comment by brusch** [comment]
Please don't use issues to get support. 
We have a forum (https://talk.pimcore.org/) with a very polite and helpful community for that. 

Thanks! 

Answers: 
1. Of course
2. No
3. https://dev.mysql.com/doc/refman/5.6/en/innodb-physical-record.html
