### ISSUE TITLE
[Translation POEdit] Invalide modified translation

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2624]
I just saw a translation has been updated:
https://github.com/pimcore/pimcore/commit/2cde8f533b6f454afafa7fa0b2d5c0247609e6c3

Problem is on other language for instance French, all is always 100%.
So if you update some translations in english, it can not be updated in other langage as their is no way to spot them on Poedit.
I think maybe the "fuzzy" tag of poedit could be used.

**Comment by Yivan** [comment]
@brusch 
Any news on it ?
I work on the french translation (trying to keep them to 100%) but i cannot know when an existing one need to be changed.

By the way, is there any way to have an alert a few days (2 for instance) to be aware of a soon new release version, so i can add missing translation before the release.
Actually, i saw a new release, so i check translation after to complete then. So translation arrive often only on the next release.

Thanks

**Comment by mattamon** [comment]
@Yivan this is more of a discussion topic then an Issue.
We do have release cycles but there is no guarantee that there will be new translations.

I will close the ticket sorry for the late response though.
