### ISSUE TITLE
Making change from the admin grid of the objects should update modification data

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#2627]
### Expected behavior 
  Making change from the admin grid of the objects should update the user modification value of the object and the time of the last modification.

### Actual behavior  
  It is currently preserving the last user modification.

### Steps to reproduce  
  Edit object which has previous changes using the grid with user different from the one made the last change.

FIX:
```
//add this before $object->save(); in the "gridProxyAction" method
$object->setModificationDate(time());
$object->setUserModification($this->getUser()->getId());
```

**Comment by kanevbg** [comment]
Tested in Pimcore 4

**Comment by weisswurstkanone** [comment]
fixed in build 4112

**Comment by kanevbg** [comment]
I think the modification  time should be changed too. Don't you?
