### ISSUE TITLE
Field containers get constantly renamed when saving the class

### ISSUE THREAD

**Issue by SmashingQuasar** [pimcore/pimcore#2628]
Hello,

It is a simple bug to reproduce. I'm using Pimcore 5.1.3 at this moment. When you give a name to a field container inside a class, the next time you reload the class, if you click on the field container, it will loose its name and the name will get back to default. ("Field Container") There is also another issue, since you are using thoses names to create classes inside the DOM (E.g.:  a field container named "test_container" will result in the following class in the back-office DOM: objectlayout_element_test_container), it causes problems if you allow spaces inside the naming. Currently the default name injects "objectlayout_element_Field Container" in the DOM which means the classes are somewhat broken.

I think it would be really good if we could just have a class like "Class.propertyName.{input/label}" to customize the back-office because right now it is extremely difficult to alter the CSS of the back-office.

**Comment by weisswurstkanone** [comment]
fixed in build 214
