### ISSUE TITLE
Email Export

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#2629]
Are there any plans to integrate a email export functionality? If not - do you see any potential for that?
We're willing to provide a PR with a simple csv export mechanism.

## Worldwide Emails
- Add a export button in grid view (right before search field)
- Export mails (current or filtered by search) as csv with all given rows + all fields with type `simple` as additional rows from `params`

## Single Emails
- Add a export button in grid view (right before search field)
- Export mails (current or filtered by search) as csv with all given rows + all fields with type `simple` as additional rows from `params` 

What do you think?

**Comment by fashxp** [comment]
sounds good. can you provide a PR?

**Comment by solverat** [comment]
@fashxp. ok than.

**Comment by fashxp** [comment]
any updates on this one?

**Comment by fashxp** [comment]
hm?

**Comment by brusch** [comment]
Closed due to inactivity. 
But we'd still ❤ to see a PR for that (@solverat 😉)
