### ISSUE TITLE
Clicking on update, cancelling and then reopening causes duplicate selection boxes

### ISSUE THREAD

**Issue by cleggypdc** [pimcore/pimcore#263]
To reproduce:
 1. Open up the admin panel
 2. Click on Extras Menu - > Update.
 3. Click Yes to continue
 4. Wait for UI to load.
 5. Click the X to cancel.
 6. Click on Extras Menu -> Update.
 7. Click Yes to continue
 8. Wait for UI to load
 9. Observe the duplicate selection boxes

Pimcore Build: 3550
Browser: Chrome 45.0.2454.101

![image](https://cloud.githubusercontent.com/assets/1098498/10373288/6e1c5816-6de4-11e5-9cbd-823e1baf8f70.png)

**Comment by brusch** [comment]
fixed by b8f9f883799c258918ad5dc11f0e40ddf6b42d44
