### ISSUE TITLE
staticroute for specific site causes error in pimcore preview

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#2631]
steps to reproduce:

- create a staticroute with a siteId (e.g.  'staticroutename' siteId: 2)
- create a document within the site. In the template generate an url for the staticroute (e.g. $this->pimcoreUrl([...], 'staticroutename') )

if you open the document in the pimcore backend you should get an error: 'None of the chained routers were able to generate route: Route 'staticroutename' not found'. 

Pimcore: Version: 5.0.1 Build: 133

**Comment by andreas-gruenwald** [comment]
@ultramegatom is this still relevant? Probably most developers nowadays don't use pimcore static routes anymore?

**Comment by dpfaffenbauer** [comment]
@andreas-gruenwald most still do. But when you use a staticroute with a site, don't expect preview to work, furthermore you should add a separate preview route which handles the preview for you.

**Comment by ultramegatom** [comment]
@andreas-gruenwald 
Legacy projects will always use custom routes. 

@dpfaffenbauer 
strongly disagree. There is a big difference between not working and throwing an exception. 

I still have this workaround in my project because of it.
```php
if($this->editmode) {
    $url = '#';
} else {
    $url =  $this->pimcoreUrl([...], 'routname', true, false);
}
```

At the end of the day this was a regression from Pimcore 4 --> 5 update. And is probably not relevant anymore because it has been broken since.
