### ISSUE TITLE
Adminer not showing data in tables with Pimcore 4 build 4109

### ISSUE THREAD

**Issue by tfarmerjms** [pimcore/pimcore#2635]
### Expected behavior 
  Browse to adminer database admin. Select a table and use the select data link. New page loads, and should show data in table.
### Actual behavior  
  adminer doesn't show any data in table. All it shows as the nav menu items, Select data, show structure, etc. Browsing to tables using mysql command line does show data in tables.
### Steps to reproduce  
  Select database administration. Pick a table. Click select data. No results show. No errors in browser console.

**Comment by brusch** [comment]
This is a problem of Adminer which was fixed already: 
https://github.com/vrana/adminer/pull/257

After they release the next version a simple `composer update` should fix the problem.
