### ISSUE TITLE
On local admin pimcore 5 on windows

### ISSUE THREAD

**Issue by romyrudiansah** [pimcore/pimcore#2636]
![image](https://user-images.githubusercontent.com/11264366/36711261-0a6e8fe2-1bb5-11e8-9031-544da43dcd1d.png)

![image](https://user-images.githubusercontent.com/11264366/36711155-839b6bd4-1bb4-11e8-94e2-044d723ae037.png)

![image](https://user-images.githubusercontent.com/11264366/36711173-99a633b4-1bb4-11e8-9848-466940adbda6.png)

![image](https://user-images.githubusercontent.com/11264366/36711178-9e8dc8b0-1bb4-11e8-8400-74fa59a1ea5f.png)

![image](https://user-images.githubusercontent.com/11264366/36711183-a256820c-1bb4-11e8-91c1-f90dac68f51e.png)

![image](https://user-images.githubusercontent.com/11264366/36711186-a55e89c2-1bb4-11e8-95f3-8cab74ac35aa.png)

pls tell me how to fix it. its annoying for me.
thanks,

**Comment by brusch** [comment]
https://talk.pimcore.org plz - thanks ;)
