### ISSUE TITLE
[Classification Store] Values not shown in grid

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2637]
you can select classification store columns in grid, but the values are not shown

![image](https://user-images.githubusercontent.com/8792145/36725747-98a605e0-1bb7-11e8-84e0-e9d51ec2f8c2.png)

vs. 

![image](https://user-images.githubusercontent.com/8792145/36725754-a2046a8c-1bb7-11e8-82ef-156eef2e6fab.png)

**Comment by fashxp** [comment]
also filtering for classification store attributes is not possible

**Comment by weisswurstkanone** [comment]
build 213
