### ISSUE TITLE
[Classification Store] Batch update updates data in grid, but not in object editor view

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2638]
maybe related to https://github.com/pimcore/pimcore/issues/2637? 

1) open object in grid and batch update classification store attribute - changes are visible, even after reload
![image](https://user-images.githubusercontent.com/8792145/36725867-01d50264-1bb8-11e8-81bc-14fbb6d5e4a6.png)

2) open object in detail editor view - changes are not there
![image](https://user-images.githubusercontent.com/8792145/36725889-13094860-1bb8-11e8-8af4-16f644aa0c3c.png)

**Comment by weisswurstkanone** [comment]
build 213
