### ISSUE TITLE
Non-owner object relation does not work if getter for this field exists

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#2639]
1. Create data object class "Nonowner"
1. Create class Owner with object relation names "relation" to class Nonowner
1. Edit class "Nonowner" and add nonowner relation field named "nonowner" for objects of class "Owner"
1. override class Nonowner via app/config/config.yml
1. in overridden class implement a public method getNonowner:
```php
/**
@return Owner[]
*/
public function getNonowner()
    {
        /** @var Nonownerobjects $def */
        $def = $this->getClass()->getFieldDefinition("nonowner");
        $refKey = $def->getOwnerFieldName();
        $refId = $def->getOwnerClassId();
        $relationData = $this->getRelationData($refKey, false, $refId);

        $objects = [];
        foreach($relationData as $relation) {
            $objects[] = OwnerList::getById($relation['id']);
        }

        return $objects;
    }
```
1. Create Nonowner object and assign Owner object.
1. Save() -> crashes with exception "Invalid non owner object relation to object"

The problem seems to be in [NonownerObjects::allowObjectRelation()](https://github.com/pimcore/pimcore/blob/master/pimcore/models/DataObject/ClassDefinition/Data/Nonownerobjects.php#L201). 
$object is of class Owner in this case (as returned by getNonowner()). This is why `$ownerClass->getId() == $object->getClassId()` returns true in line 198 (nonowner field references Owner objects and $object is of class Owner). But in line 201 the $fd field definition is for the field Owner::relation which of course must only accept Nonowner objects but in this case gets called with $object - which is a Owner object.

A workaround is to allow Owner and Nonowner objects for field Owner::relation but of course this is not correct.

**Comment by brusch** [comment]
Sorry, maybe I don't understand the problem entirely .. but everything works as expected if you don't override the class right? 
May I ask you to provide more example code alongside with a PR that fixes the issue you mean? 
Thanks a lot!

**Comment by katwer** [comment]
I have the same problem. 
When I overwrite class, update is crash with 
"Validation failed: Invalid non owner object relation to object... "

Change name of getter in Owner class on something not default (from getField() to getRelatedFiedl()) works..
