### ISSUE TITLE
[Versions] Add "clear all" functionality

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2641]
- should delete all versions of current element
- as new entry in the context  menu

![image](https://user-images.githubusercontent.com/142037/37344550-f460550c-26ca-11e8-82fa-755eddf8f539.png)

**Comment by dvesh3** [comment]
![screenshot from 2018-03-19 22 08 45](https://user-images.githubusercontent.com/5137917/37609374-f8df1db4-2bc2-11e8-8781-426108ca2eac.png)

Please confirm if it is correct location to add this option?

**Comment by brusch** [comment]
Confirmed ;)
