### ISSUE TITLE
vrana/jush dependency

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#2647]
Recently, sourceforge seems to have a lot of issues and therefore doing deployments/installations via composer is not possible anymore. It always runs into the issue that ```https://git.code.sf.net/p/jush/git``` is not accessible.

Only valuable solutions are:
 - Remove vrana/jush from project -> but that breaks adminer
 - Providing a ZIP file instead

As of now, there is no valuable solution available. Maybe the package will be distributed through github properly someday, but until that, we need to have a proper solution.

**Comment by dpfaffenbauer** [comment]
If somebody needs a source for the zip, you can use this configuration:

```
"repositories": {
    "vrana-jush": {
        "info1": "External dependency of vrana/adminer which isn't included or referenced by adminer, see also https://sourceforge.net/p/adminer/bugs-and-features/468/ ",
        "info2": "The package on GitHub isn't compatible with Adminer, it doesn't contain the /modules/ folder.",
        "type": "package",
        "package": {
            "name": "vrana/jush",
            "version": "1.0.0",
            "dist": {
                "type": "zip",
                "url": "https://www.coreshop.org/vrana-jush.zip",
                "reference": "master"
            }
        }
    }
}
```

**Comment by brusch** [comment]
https://github.com/vrana/jush/pull/1
https://sourceforge.net/p/adminer/bugs-and-features/602/
