### ISSUE TITLE
[Pimcore Backend Users] Store last login date directly in user

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2648]
to make cleanup routines for users that did not log in for a while possible

+ update of Pimcore docs https://pimcore.com/docs/5.x/User_Documentation/Administration_of_Pimcore/Data_Protection_and_GDPR.html

**Comment by brusch** [comment]
Cleanup routine is not part of this issue, only the additional date property stored on the user (in database: int column).

**Comment by dvesh3** [comment]
So i guess we don't need to update documentation for this issue?
