### ISSUE TITLE
[E-Mail Logs] Add Cleanup-Command for E-Mail Log

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2649]
Add command for cleanup for e-mail logs 
- with param for delete all mails older than 

And update Pimcore docs here: https://pimcore.com/docs/5.x/User_Documentation/Administration_of_Pimcore/Data_Protection_and_GDPR.html

**Comment by brusch** [comment]
eg `./bin/console pimcore:email:cleanup --older-than-days=14` 
without `--older-than-days` param => exception: missing option.
