### ISSUE TITLE
Inner join of objects in GUI list view

### ISSUE THREAD

**Issue by callesg** [pimcore/pimcore#2652]
# Feature Request 
Hi we have a object structure that looks like this

Article
    ->ArticleColor
        ->->ArticleSize

So the ArticleColor objectss are children of the Article object, and the ArticleSize objects are children of the ArticleColor object.

So an article in our pimcore consists of 3 object class and between 3 and about 300 objects(where one article has 6 colors and 20 sizes)

As a technical person i often use the underlying SQL db to get the information i want

ie
```sql
SELECT * FROM `object_localized_39_mas`
INNER JOIN `object_localized_40_mas` ON `object_localized_39_mas`.`oo_id` = `object_localized_40_mas`.`o_parentId`
INNER JOIN `object_42` ON `object_localized_40_mas`.`oo_id` = `object_42`.`o_parentId`
WHERE object_localized_39_mas.Season = 2016
LIMIT 100
```

That way i can search for all sizes that belong to season 2016 but that is impossible in the GUI

What would be nice is if we could get a feature that would support that someway in the pimcore GUI most of our users don't know how to use SQL and even if they did, i don't want to give them access to the sql database.

**Comment by kubaplas** [comment]
You should check out https://github.com/pimcore/advanced-object-search
You can easily add support for parent and you'll have a gui for your searches.

**Comment by brusch** [comment]
Since https://github.com/pimcore/advanced-object-search covers this topic already, I'm closing this feature request for now.
