### ISSUE TITLE
image preview generation causes php to crash

### ISSUE THREAD

**Issue by tgross-m-s** [pimcore/pimcore#2653]
https://github.com/pimcore/pimcore/blob/8a87fae84a4fdced87453b5fdb1fb5dfb3b667f7/pimcore/models/Asset/Image.php#L123

The existence of the line above causes many PHP installations to crash on this line:
https://github.com/pimcore/pimcore/blob/8a87fae84a4fdced87453b5fdb1fb5dfb3b667f7/pimcore/models/Asset/Image.php#L126

because of the following ImageMagick bug: http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=24366

I know this is not a pimcore bug, but it happens on many current PHP Installations, for example zend server, using PHP 7.1.

I suggest not using "jpeg:extent" at all, but set the compression quality instead:
`$imagick->setImageCompressionQuality(50);`

Thank You!

**Comment by leuchtdiode** [comment]
Please fix this bug as soon as possible. I think much more people are affected by the bug in imagick.

Look here for our conversation and 2 possible "quick fixes": https://talk.pimcore.org/t/cant-upload-images-to-assets/493/8

**Comment by brusch** [comment]
Using `$imagick->setImageCompressionQuality(50);` will not have the desired effect, what we'd like to achieve is a maximum file size of 1kB.

**Comment by leuchtdiode** [comment]
So how does someone prevent PHP to crash besides installing SQIP?
At least it should be mentioned in the documentation!

**Comment by tgross-m-s** [comment]
@leuchtdiode: The issue has been fixed, see https://github.com/pimcore/pimcore/issues/2653#event-1528040541.

Just wait for 5.2.2 to be released.

**Comment by leuchtdiode** [comment]
Ok sorry. Then I misunderstood.
