### ISSUE TITLE
Objects copy/paste breaks at unique constraint violation

### ISSUE THREAD

**Issue by jansarmir** [pimcore/pimcore#2658]
After added feature to support diacritic for Object's key, copy/paste stopped working for diacritic's values
new object with suffix **_copy** is not created

````
unique constraint violation in object /news/Praveké technológie v službách ľudstva [id: 4]
````

**Comment by weisswurstkanone** [comment]
fixed in build 214

**Comment by zoltanbirnerelegantdigital** [comment]
I'm getting the same error  
Pimcore version: v6.2.1
Build  7cf81c67e93e113ef855ff3643f5fda328f3f6af
