### ISSUE TITLE
[5.2.0] Error "Save & publish" after "Only save new version" on object with non-owner relationship attribute

### ISSUE THREAD

**Issue by RasmusMagnell** [pimcore/pimcore#2662]
Tested in the Demo environment on version 5.2.0 (213)
# Bug description
 Saving and publishing an object with a non-owner relationship attribute after a save version only generates an error. 
 
  
### Steps to reproduce  
  1) create two classes, one with a Objects relation and the other with a Objects (non owner) relationship and connect them to each other
2) Create an object  of the class with the non owner attribute
3) On the object click "save version only" 
4) Click Save & publish

Example with the Object (non owner) attribute nonOwnerAttribute.
![save-nonowner-bug](https://user-images.githubusercontent.com/31310953/37084057-b9b23804-21f1-11e8-9dec-52af9daee0fa.PNG)

There is a check in the file pimcore/pimcore/models/DataObject/Concrete/Dao.php that these kind of attribute passes on a normal save & publish but not in this case.
```
foreach ($fieldDefinitions as $key => $fd) {
            if (method_exists($fd, 'getLazyLoading') && $fd->getLazyLoading()) {
                if (!in_array($key, $this->model->getLazyLoadedFields())) { // This check fails and the attribute is not added to the $untouchable array
                    //this is a relation subject to lazy loading - it has not been loaded
                    $untouchable[] = $key;
                }
            }
        }
```

**Comment by weisswurstkanone** [comment]
fixed in build 214
