### ISSUE TITLE
Support datatype 'image' in Classification Store

### ISSUE THREAD

**Issue by podarcis** [pimcore/pimcore#2663]
# Feature Request 
## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [x] There is no existing issue regarding the same topic

## Feature description 
Currently there is no support for the datatype `image` in the Classification Store. As an image can be legitimate data for technical data (which is best stored in a Classification Store as the Key-Value-Type has been removed) it would be nice if this Pimcore type could be supported as well.

What do you think about supporting images? Do you see any difficulties in the implementation, such as storing/resolving dependencies?

**Comment by dpfaffenbauer** [comment]
I guess to solve this, the classification store should first be able to handle dependencies. So, in that case it could be possible to add href fields as well. What do you think?

**Comment by podarcis** [comment]
@dpfaffenbauer I agree, with proper dependency handling other/ complex types could be supported as well.

**Comment by fashxp** [comment]
PRs always welcome ;-)

**Comment by brusch** [comment]
I'm closing this issue for now as it is currently not in our top priorities. 
However, as already said, PRs are welcome 😉
