### ISSUE TITLE
[Objects] InnoDB Tablespace Encryption Support

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#2664]
Possibility to enable tablespace encryption on class level. 
https://dev.mysql.com/doc/refman/5.7/en/innodb-tablespace-encryption.html

**Comment by dpfaffenbauer** [comment]
And that works for MySQL and MariaDB?

**Comment by brusch** [comment]
https://mariadb.com/de/node/150

**Comment by brusch** [comment]
![image](https://user-images.githubusercontent.com/142037/52620386-beac7c00-2ea4-11e9-8243-8af3a282437f.png)
