### ISSUE TITLE
Uploading an empty Asset (=0 Bytes size) fails

### ISSUE THREAD

**Issue by gadget60** [pimcore/pimcore#2667]
Uploading an empty file into Assets fails:

- Via "Add asset" > "Upload files" > Select an empty file: Silently fails
- Via drag'n'drop: Fails with error: {"success":false,"message":"Something went wrong, please check upload_max_filesize and post_max_size in your php.ini and write permissions of \/home\/pimcore_demo_basic\/www\/web\/var"}

I just ran into this while I was trying to upload an empty .txt file. I can't imagine this is intended behaviour, however if it is then at least the error message is misleading.

**Comment by weisswurstkanone** [comment]
ad a) Empty files are silently ignored. tree.js line 311

                if (window.FileList && file.name && file.size) { // check for size (folder has size=0)
                    doFileUpload(file);
                }

**Comment by weisswurstkanone** [comment]
ad b) AssetController ~328

            if (!is_file($sourcePath) || filesize($sourcePath) < 1) {
                throw new \Exception('Something went wrong, please check upload_max_filesize and post_max_size in your php.ini and write permissions of ' . PIMCORE_PUBLIC_VAR);
            }

Voting for a better error message ...
