### ISSUE TITLE
Installing old Pimcore version make composer run an exception

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2669]
If you install an old Pimcore version, for instance the 5.1.2 stable from here:
https://github.com/pimcore/pimcore/releases

Before running installation, a composer install need to be runned. But when runned it send exceptions (because database not configured i think, but as it can not be installed without vendors library... it is an irresolvable loop problem : )) )
Please see the error messages:

![composer-first-install](https://user-images.githubusercontent.com/9025839/37163670-a1cae44a-22f8-11e8-9268-9cc62ad4e478.png)

Thanks.

**Comment by Yivan** [comment]
By the way, the link "Install via Composer" on the Pimcore website here https://pimcore.com/en/download is broken (https://pimcore.com/docs/5.0.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Composer_Install.html)

**Comment by brusch** [comment]
Link fixed. 

Install problems: i guess this is caused by some dependency problems, but there is nothing we can do, to fix a release later on.
