### ISSUE TITLE
Allow user folders with the same key name to be created elsewhere in tree

### ISSUE THREAD

**Issue by cleggypdc** [pimcore/pimcore#267]
Currently there is a table restriction that stops users / folders with the same names being created. This has an impact when trying to structure user folders. For instance I would be unable to create the following user folder structure for easy navigation.

editors
    -> uk
    -> fr
    -> de
publishers
    -> uk
    -> fr
    -> de

**Comment by brusch** [comment]
That's intentional :-) 
The username of editors/uk is still "uk" and the username has to be unique, so that we can identify the user at the login. If we'd remove this restriction, the username "uk" wouldn't be unique anymore.
