### ISSUE TITLE
Create a field Object whith Metadata send an error on GUI when opened

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2670]
It is reproducible on the Pimcore 5.2.1 online demo (with Chrome last stable version on Windows 10 uptodate):
- create a new class
- add an Object whith Metadata field
- click to open the field config panel: it send an error

Please see this screenshot:

![panel-objects-with-metadata](https://user-images.githubusercontent.com/9025839/37166751-406e125a-2300-11e8-8b2f-5e6729ea0065.png)

Thanks.

**Comment by weisswurstkanone** [comment]
fixed in build 218
