### ISSUE TITLE
caching full pages with dynamic url parameters

### ISSUE THREAD

**Issue by piotrecky** [pimcore/pimcore#2679]
Is there any way to cache sites for urls with dynamic parameters like gclid in full page cache?

Example urls:

- example.com/landing-page
- example.com/landing-page?gclid=abc
- example.com/landing-page?gclid=xyz

All of the above urls are the same page but full page cache treats all pages as different.

**Comment by brusch** [comment]
Currently there's no event for that - but probably that's something useful for the future. 
In the meantime you could change the request uri in the request object, either by using a custom event listener with a higher priority than the full page cache or by a custom startup.php. 
https://pimcore.com/docs/5.x/Development_Documentation/Getting_Started/Configuration.html#page_Adding-logic-to-the-startup-process

**Comment by piotrecky** [comment]
Thanks, custom event method is good for me.
