### ISSUE TITLE
Request source code of E-Commerce demo website

### ISSUE THREAD

**Issue by zjhiphop** [pimcore/pimcore#268]
Hi, Guys
   Recently, i need to build an e commerce website kind like 'http://ecommercedemo.pimcore.org/'. But i found there is no way to find the source code of this website. Anyone can tell me where i can download the source code?

  Thanks!

**Comment by dpfaffenbauer** [comment]
hey, the official ecommerce demo is not open source. you can try my implemenation: https://github.com/dpfaffenbauer/pimcore-coreshop

**Comment by brusch** [comment]
The official pimcore e-commerce framework is at the moment only available to pimcore partners.
