### ISSUE TITLE
vrana/jush dev-master requires minimum-stability

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#2683]
Pimcore requires vrana/jush on `dev-master` which leads to a "conflict with your requirements or minimum-stability" in composer if pimcore is running as dependency. Currently we need to set the minimum-stability to `dev` (and prefer-stable though).

**Comment by brusch** [comment]
@solverat : Please ask @vrana to make a release tag on https://github.com/vrana/jush 
Thanks!

**Comment by vrana** [comment]
Done.

**Comment by brusch** [comment]
@vrana unfortunately the tags are in the wrong format, so packagist doesn't recognize it as a proper version. You'd have to use tag names as described here: 
https://getcomposer.org/doc/articles/versions.md#composer-versions-vs-vcs-versions 

so eg. `git tag v2.0.1`

Thanks again!

**Comment by brusch** [comment]
And you'd need to setup the update hook on GitHub or refresh it manually after you've created the tag :)

**Comment by solverat** [comment]
@vrana just fixed it. thanks to all!

**Comment by brusch** [comment]
@vrana thanks for fixing the tag!
Now only Packagist needs again an update, so that Composer sees the tag. 
Just click the *Update* button on https://packagist.org/packages/vrana/jush

![image](https://user-images.githubusercontent.com/142037/37388406-acd2deda-2760-11e8-8119-aed10fb1565e.png)

Thanks again!

**Comment by vrana** [comment]
Done, I guess.

**Comment by brusch** [comment]
@vrana unfortunately not, there's still no release available on Packagist: 
![image](https://user-images.githubusercontent.com/142037/37583993-001abe2c-2b54-11e8-97ef-ae7f7bfe1ce4.png)

**Comment by vrana** [comment]
I don't know what to do. I clicked Update, the page refreshed but nothing changed. I've even deleted dev-master but it re-appeared after update.

**Comment by vrana** [comment]
I've deleted the tag. Still no luck.

**Comment by dpfaffenbauer** [comment]
Did you update it on packagist or did you setup the automatic update?

**Comment by vrana** [comment]
Updated on Packagist.

**Comment by brusch** [comment]
@vrana Maybe it helps to re-create the package on Packagist? Otherwise we'd have to contact the guys from Packagist, I'd say :|

**Comment by brusch** [comment]
@vrana would be good if you could try this again today, because this is the only thing that blocks our release since days ;) Thank you very much for your help!

**Comment by blankse** [comment]
@vrana The v2.0.1 tag hasn't a composer.json
https://github.com/vrana/jush/tree/v2.0.1

**Comment by brusch** [comment]
@blankse Thanks! :)

**Comment by brusch** [comment]
@vrana Any chance you can fix that quickly? Would be really great! Thank you very much!

**Comment by fashxp** [comment]
@vrana one last try, could you create a new release v2.0.2 from the current master? would be really great. thx.

**Comment by vrana** [comment]
Done. The tag is now on Packagist.

**Comment by fashxp** [comment]
yeyy, thank you very much! 
I already updated the pimcore composer.json, so with the next build pimcore will not require dev-master anymore. 

thanks again.
