### ISSUE TITLE
Use Pimcore as a Composer Dependency

### ISSUE THREAD

**Issue by foobar13373** [pimcore/pimcore#2687]
I'm trying to setup a pimcore environment, my `composer.json` looks like this:

```
{
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require": {
    "pimcore/pimcore": "5.2.*"
  },
  "config": {
    "optimize-autoloader": true,
    "platform": {
      "php": "7.1.6"
    }
  }
}
```
This downloads everything nicely. But when I try to run
`vendor/pimcore/pimcore/bin/install pimcore:install`
I get errors that `vendor/pimcore/pimcore/vendor/autoload.php` was not found (vendor in vendor).

So this is either a documentation bug (in case I miss some configuration) or an installer bug (in case it is really looking in the wrong directory).

I do not want to use the `composer create-project` way to keep everything as minimal and cleaned up as possible. In case this is not possible at all currently, I'd like to see this as a feature-request instead, so that I can just require pimcore and run the installer afterwards.

edit: Just saw this was already requested in #781 - however it was closed because v5 has "a new architecture". But the new architecture still does not seem to allow this kind of setup.

**Comment by brusch** [comment]
Closed in favor of #3120
