### ISSUE TITLE
ExtJS 6 - ObjectsWithMetaData editing

### ISSUE THREAD

**Issue by cleggypdc** [pimcore/pimcore#269]
This is really minor, but when using an objectsWithMetaData (particularly with a boolean checkbox field). If the user is to double click to edit the field value, then immediately click save on the object, the new value does not get stored, I think as the field is still in focus.

Build: 3555
Browser: Chome 45.0.2454.101

**Comment by brusch** [comment]
Should be fixed, see: https://github.com/pimcore/pimcore/commit/d008354e456c459ab9d5b7be58f65d907e654b0d
and #1193
