### ISSUE TITLE
[Custom Reports] Add fields for max-results in GA API query string

### ISSUE THREAD

**Issue by ppi-buck** [pimcore/pimcore#2694]
# Feature Request: Add more fields to Google Analytics API query config 

This is a feature request regarding the integration of Google Analytics in Custom Reports.

I would like to add an optional parameter for max-results to my query string via an input field to limit the amount of results.

## Feature description 
Configuring a custom report to show data from Google Analytics works fine in pimcore but is missing at least one important field IMO. There should be an input field for **max-results** to limit the number of results right after the **Sort** field.

![image](https://user-images.githubusercontent.com/37330764/37466138-502713a6-285d-11e8-94be-ff44947d9d15.png)

Use-case: I want to show the top 10 most viewed articles of my website. 

Would be nice to have more fields/a single field for multiple optional parameters. See docs for reference https://developers.google.com/analytics/devguides/reporting/core/v3/reference#maxResults 

PS: Looking at some code it looks like it's already prepared to get the limit but it cannot be configured in the GUI.

---
Thanks,
Basti

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
