### ISSUE TITLE
isDocumentInSite documentation error and improve performance.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2702]
\Pimcore\Tool\Frontend::isDocumentInSite is not good documented at the bottom of those pages:
https://pimcore.com/docs/4.6.x/Development_Documentation/MVC/Routing_and_URLs/Working_with_Sites.html
https://pimcore.com/docs/5.0.x/Development_Documentation/MVC/Routing_and_URLs/Working_with_Sites.html

`\Pimcore\Tool\Frontend::isDocumentInSite($document);`
should be replaced by:
`\Pimcore\Tool\Frontend::isDocumentInSite($site, $document)`

By the way, it seems the method performance could be improved by replacing:
`if (!preg_match("@^" . $site->getRootDocument()->getRealFullPath() . "/@", $document->getRealFullPath())) {`
by
`if (!strpos($document->getRealFullPath() . '/', $site->getRootDocument()->getRealFullPath()) === 0) {`

Thanks!

**Comment by Yivan** [comment]
EDIT:
It seems the good code should be:
`if (!strpos($document->getRealFullPath(), $site->getRootDocument()->getRealFullPath() . '/') === 0) {`

**Comment by Yivan** [comment]
@brusch Thanks! You think there is no need to optimize getSiteForDocument method too ? (see the end of my last comment above please)

**Comment by brusch** [comment]
@Yivan sorry, I didn't see this hint -> fixed :)
