### ISSUE TITLE
Asset gets processed as Document

### ISSUE THREAD

**Issue by puecher** [pimcore/pimcore#2704]
Hi!

**Documents**
Home >
/series/batman (Unpublished)

**Assets**
/series/batman/batman.jpg

When opening the page /series/batman as preview, the image

<img src="/series/batman/image-thumb__123__large/batman~-~767w.jpeg" ... >

is not visible (the asset throws a 404 error).

The debug mode shows that the ElementListener https://github.com/pimcore/pimcore/blob/73b00d44cb072e04da29a4ab7bd1a4324765f917/pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/ElementListener.php#L122 processes the asset as document. The document is unpublished so the thumb gets not created.

**Comment by brusch** [comment]
Needs further information, see: https://github.com/pimcore/pimcore/pull/2826#issuecomment-387652353 

Also possibly related to #2712
