### ISSUE TITLE
Add option to set CSV settings on import

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#2705]
Sometimes Pimcore can not guess the proper CSV Settings for a data import. All data will be in one row in this case. It'd be great to have the option to set the CSV settings (e.g. delimiter sign) on import if needed.

**Comment by ScottThornton** [comment]
I second the request here.   And soon yes ?    I'm at a loss as to why its detecting the wrong delimiter and can't correct it.  I have ; as delimiter but its detecting : .   There are strings containing Https:// and dates with times containing :  .   When I search a replace : with something like ~ it will then detect correctly the delimiter of ; .

**Comment by ScottThornton** [comment]
I have repro file if you so desire.   1 header and 6 records that blows it up.  I've torn it apart and can't seem to find the pattern.   Let me know and I will send you.
