### ISSUE TITLE
WebTestCase Client in insulated mode does not work

### ISSUE THREAD

**Issue by i-telligence-af** [pimcore/pimcore#2709]
### System
Pimcore 5.2.1
Symfony 3.4
PHP 7.1.3
OSX 10.10.5

### Expected behavior 
Running clients in insulated mode should work, or at least the Pimcore documentation should mention that this is not supported (yet).

### Actual behavior  
Test crashes. It seems that Pimcore isn't bootstrapped.

php_error.log:
`[20-Mar-2018 13:13:28 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Pimcore' not found in /***/pimcore/lib/Pimcore/Kernel.php:155
Stack trace:
#0 -(10): Pimcore\Kernel->boot()
#1 {main}
  thrown in /***/pimcore/lib/Pimcore/Kernel.php on line 155`

### Steps to reproduce  
Follow the instructions for "The PHPUnit Testing Framework" at
https://symfony.com/doc/3.4/testing.html#the-phpunit-testing-framework
namely:
composer require --dev symfony/phpunit-bridge

Follow the instructions for "Bootstrapping Pimcore" at https://pimcore.com/docs/5.0.x/Development_Documentation/Development_Tools_and_Details/Testing.html

Create a functional controller test in
tests/AppBundle/Controller/SomeControllerTest.php:
```php
<?php

namespace Tests\AppBundle\Controller;

use Pimcore\Test\WebTestCase;
use Symfony\Component\HttpFoundation\Response;

class SomeControllerTest extends WebTestCase
{

    public function testInsulated()
    {
        $client = static::createClient();
        $client->insulate();
        $crawler = $client->request('GET', '/some-url');
    }

}

```
Run 
`./vendor/bin/simple-phpunit`

**Comment by brusch** [comment]
PR is welcome :)
