### ISSUE TITLE
Carpe Diem Website

### ISSUE THREAD

**Issue by fabianallgaeuer** [pimcore/pimcore#2711]
Hallo,

die Carpe Diem Website verlinkt auf der Titel Seite ganz unten "Carpe Diem Finest Fingerfood" auf eine fehlerhafte Seite.... 

Bitte als Link die richtige Page angeben. https://www.carpediemfinestfingerfood.com/de/

![image](https://user-images.githubusercontent.com/37531896/37698632-047d93ae-2ce4-11e8-847f-0dbd0fd60802.png)

Danke und schöne Grüße
Fabian

**Comment by fashxp** [comment]
this is an issue tracker for the open source core product only. for solution specific questions please contact your integrator or our professional services (see https://pimcore.com/en/services/support).

thank you for your understanding.
