### ISSUE TITLE
Unable to route if url pattern matches unpublished document/site

### ISSUE THREAD

**Issue by podarcis** [pimcore/pimcore#2712]
# Bug Report
The application will throw an AccessDeniedHttpException for routes (e.g. annotated Symfony routes in controller) if it matches the beginning of an unpublished document/site path.

  
### Expected behavior 
Regardless of the page being unpublished, custom routes _with_ same path-prefix should still work.
  
### Actual behavior 
AccessDeniedHttpException is thrown and route (e.g. controller action) not accessible.
  
### Steps to reproduce  

Setup:
We've got multiple sites which key/path equals the language, e.g. /de, /at... And we've got some legacy piece which resides within a bundle (controller action with Symfony annotation) and is accessible at /{language}/whatever.

1. Create a controller action and add a route annotation like `@Route(/{language}/whatever)`
2. Verify: Route is accessible at `/de/whatever`
3. Add a new document or site with key `/de` and leave it _unpublished_.
4. Verify: Route `/de/whatever` isn't available anymore, AccessDeniedHttpException is thrown
5. Add a new _published_ document below `/de` with key `/de/foobar`
6. Verify: `/de/foobar` is accessible even though `/de` is unpublished; expected behavior, however inconsistent with not accessible `/de/whatever`
7. Publish page/site `/de`
8. Verify: Route `/de/whatever` is now accessible

**Comment by brusch** [comment]
I see no way how to realize that at the moment without massive side-effects on performance. 
However if someone finds a solution how to solve that without any negative side-effects, we're happy the merge a PR.

**Comment by brusch** [comment]
Maybe we should just don't allow the usage of the same path in assets and documents - that would be imho the easiest fix without any negative side-effects.

**Comment by dpfaffenbauer** [comment]
why? just change the priority of routes

1. symfony routes
2. static routes
3. assets
4. documents

should solve it right?

**Comment by brusch** [comment]
The priority is kind of already like this ... 😉 (only assets have highest prio, because they are delivered directly by the webserver). This doesn't have anything to do with priorities.
