### ISSUE TITLE
Website Settings based on Environment

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#2717]
Since Pimcore moved the website settings to a config file we have some troubles with our different environments. Assets for example are stored as IDs:

```php
return [
    1 => [
        "name" => "websiteLogo",
        "type" => "asset",
        "data" => "2328",
        "siteId" => "1",
        "creationDate" => "1485329989",
        "modificationDate" => "1485330020",
        "id" => 1
    ],
```

Since this file obviously should be versioned (otherwise the whole db-to-file step would make no sense) the relation should get stored as fullpath instead of ids.

**Comment by dpfaffenbauer** [comment]
I don't think having this config as php-file is good at all. It is to much environment specific to be a file. It potentially also makes troubles on multi-stages/multi-release deployments. This is also valid for files like web2print config or reports config.

**Comment by fashxp** [comment]
website settings should follow the same environment mechanism as system config ... see https://pimcore.com/docs/5.x/Development_Documentation/Deployment/Multi_Environment.html

**Comment by fashxp** [comment]
IDs is still a problem though

**Comment by brusch** [comment]
But ID's would have to match anyway, regardless if they are numeric or not :) 
Maybe it's then better to think about custom and alphanumeric site IDs, similar what we did with data object class IDs.

**Comment by tfarmer00** [comment]
@solverat @brusch Agreed, moving these settings to a php file has made our environment much more complex to manage alternate values. Previously, we were transforming the values in the database as part of the deploy. Now, we have to use sed to modify these in real time. Major PITA.

**Comment by dpfaffenbauer** [comment]
Migrations should be the go-to solutions for deploying new settings, not the PHP file itself.
