### ISSUE TITLE
WYSIWYG is locked for non-default language inside a localized field when using dropdown

### ISSUE THREAD

**Issue by maff** [pimcore/pimcore#272]
When creating a WYSIWYG element inside a localized field, the element is locked/non-editable for all languages besides the default one when using the dropdown to select the language. This does not apply when using tabs for language selection.

![2015-10-19 14_53_22-__ pimcore_localized_field](https://cloud.githubusercontent.com/assets/27403/10578235/407ed0a6-7671-11e5-8938-7dae9c2cd6e6.png)

### Steps to reproduce ###

1. Create a class with a localized field containing a WYSIWYG element
2. Make sure the localized field is shown as dropdown selection instead of tabs (e.g. set maximum number of tabs to 0)
3. Create an object of the new class
4. The WYSIWYG will be editable in the default language, but locked for every other language

**Comment by weisswurstkanone** [comment]
fixed for extjs6
