### ISSUE TITLE
Asset filenames with @ symbol not supported

### ISSUE THREAD

**Issue by tfarmer00** [pimcore/pimcore#2722]
Pimcore v4.6.3 build 4109

Assets use the @2x designation to indicate they are retina images. This is an industry standard. Pimcore converts the @ symbol into a -, thus breaking out of the box functionality with many web standards and libraries.

**Comment by brusch** [comment]
@tfarmer00 Pimcore generates the hdpi images automatically when using image thumbnails, so jut upload the highest resolution you have and let Pimcore do the rest :) 
Anyway, in Pimcore 5 `@` characters are allowed.
