### ISSUE TITLE
GDPR - extending functionality

### ISSUE THREAD

**Issue by mischief24** [pimcore/pimcore#2727]
# GDPR - extending functionality
In Pimcore5 was added new functionality GDPR. Unfortunately, after testing it, in my opinion, based on the General Data Protection Regulation, which becomes enforceable from 25 May 2018 this functionality may turn out to be insufficient.

The missing elements are listed below:
- if user create the object we have some information but is not enough, because we don’t know what user did – a type of action should be added (create, publish etc.)
- an activity doesn’t exist when user display some object - in my opinion, it should be added
- an activity when the user deletes the object. What more, when the user deletes some object all information about actions on this object disappears.

**Comment by brusch** [comment]
Can you please give us some (official) references where this needs are described in detail? 
Afaik the GDPR does not require to save an entire audit trail of personal data, you only need to save the legally valid consent given by the user.

**Comment by mischief24** [comment]
In our opinion information about that there is in Article 30, here: https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0679&from=EN

**Comment by brusch** [comment]
Can you please quote the relevant part ...? Thanks!

**Comment by mischief24** [comment]
Sure, Article 30:
> Records of processing activities
> 1. Each controller and, where applicable, the controller's representative, shall maintain a record of processing
> activities under its responsibility. That record shall contain all of the following information:
> (a) the name and contact details of the controller and, where applicable, the joint controller, the controller's representative
> and the data protection officer;
> (b) the purposes of the processing;
> (c) a description of the categories of data subjects and of the categories of personal data;
> (d) the categories of recipients to whom the personal data have been or will be disclosed including recipients in third
> countries or international organisations;
> (e) where applicable, transfers of personal data to a third country or an international organisation, including the identification
> of that third country or international organisation and, in the case of transfers referred to in the second
> subparagraph of Article 49(1), the documentation of suitable safeguards;
> (f) where possible, the envisaged time limits for erasure of the different categories of data;
> (g) where possible, a general description of the technical and organisational security measures referred to in
> Article 32(1).
> 2. Each processor and, where applicable, the processor's representative shall maintain a record of all categories of
> processing activities carried out on behalf of a controller, containing:
> (a) the name and contact details of the processor or processors and of each controller on behalf of which the processor
> is acting, and, where applicable, of the controller's or the processor's representative, and the data protection officer;
> (b) the categories of processing carried out on behalf of each controller;
> (c) where applicable, transfers of personal data to a third country or an international organisation, including the identification
> of that third country or international organisation and, in the case of transfers referred to in the second
> subparagraph of Article 49(1), the documentation of suitable safeguards;
> (d) where possible, a general description of the technical and organisational security measures referred to in
> Article 32(1).
> 3. The records referred to in paragraphs 1 and 2 shall be in writing, including in electronic form.
> 4. The controller or the processor and, where applicable, the controller's or the processor's representative, shall make
> the record available to the supervisory authority on request.
> 5. The obligations referred to in paragraphs 1 and 2 shall not apply to an enterprise or an organisation employing
> fewer than 250 persons unless the processing it carries out is likely to result in a risk to the rights and freedoms of
> data subjects, the processing is not occasional, or the processing includes special categories of data as referred to in
> Article 9(1) or personal data relating to criminal convictions and offences referred to in Article 10

especially this fragment: 

> 2. Each processor and, where applicable, the processor's representative shall maintain a record of all categories of
> processing activities carried out on behalf of a controller, containing:
> (a) the name and contact details of the processor or processors and of each controller on behalf of which the processor
> is acting, and, where applicable, of the controller's or the processor's representative, and the data protection officer;
> (b) the categories of processing carried out on behalf of each controller;
> (c) where applicable, transfers of personal data to a third country or an international organisation, including the identification
> of that third country or international organisation and, in the case of transfers referred to in the second
> subparagraph of Article 49(1), the documentation of suitable safeguards;
> (d) where possible, a general description of the technical and organisational security measures referred to in Article 32(1).

**Comment by brusch** [comment]
Well, but it's not a must have (_shall_) and in my opinion it doesn't make sense to store all this additional information on records which do not contain personal data at all (which is normally the case). 
We recommend to utilize Notes & Events for that and only on entities where needed, in practice we're adding an event listener and push notes on every CRU-operation on objects containing personal data. With that solution you can really customize it for the specific needs of a project, which makes absolutely sense, because the requirements vary from case to case.

**Comment by brusch** [comment]
@mischief24 Forget my previous answer, that is a bit out of context :) 

You're talking about the record of data processing activities, which is basically an company internal register of which kind of personal data is being processed by either the controller or a processor. This has absolutely nothing to do with Pimcore and should be stored somewhere else.

For details please have a look at: 
https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/accountability-and-governance/documentation/

**Comment by fashxp** [comment]
any updates on this one?
