### ISSUE TITLE
XLIFF-Export/Import does not export localized content of Datatype "Block" 

### ISSUE THREAD

**Issue by writecode** [pimcore/pimcore#2730]
### Expected behavior 
Backend->Tools->Translation->XLIFF-Export/Import | MS-Word Export:
Localized Content of ObjectClasses DataType Blocks can be exported and imported.

### Actual behavior  
Localized Blocks or localized Fields in Blocks are not exported (and imported)

**Comment by weisswurstkanone** [comment]
please create a seperate issue for ms word export
