### ISSUE TITLE
Document Translations Multi-Join Gets Lost

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#2736]
I have the following problem (latest Pimcore version 5.2):

4 language trees (en/de/nl/pl)

1) en document is connected to nl+de documents
2) pl editor (can edit pl documents and read en documents) connects pl document to en document
3) en document loses connection to nl+de documents and is now only connected to pl document

**Comment by solverat** [comment]
maybe related to #2579.

**Comment by ckemptner** [comment]
@brusch @dvesh3 
Could you please look into this again?

3 documents
- english
- german
- french

a) open english document - connect with german document - save+publish
b) open french document - connect with english document - save+publish
c) WORKS => open english document => connected with german+french document
d) BUG? => open french document => only connected with english document, not with french document
