### ISSUE TITLE
Pimcore instance stops working when Object brick is re-added in object without reloading object

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#2738]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [x ] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [x ] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [x ] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [x ] There's no existing ticket for the same issue
  
### Expected behavior 
Pimcore instance should work fine and object brick should be added without breaking layout.

  
### Actual behavior  
Pimcore instance stops working and admin instance view is broken.
  
### Steps to reproduce  
1. Create Object brick with few panels inside tabpanel (This issue is mostly faced when panels are added inside tabpanel) and add some data components like image or structured table.  
![1](https://user-images.githubusercontent.com/21308144/38195355-c0bec7c6-369a-11e8-9f88-0628fe1ec5fa.png)

2.Open object and add object brick by clicking "+' icon.
![2](https://user-images.githubusercontent.com/21308144/38195429-0c53de1a-369b-11e8-88d4-5a04b3358751.png)
Object brick is added successfully in first attempt.

3. Now delete object brick.
![3](https://user-images.githubusercontent.com/21308144/38195480-4260a588-369b-11e8-90b9-dd698efd80fb.png)

4. Without reloading admin instance, add object brick again.
![4](https://user-images.githubusercontent.com/21308144/38195540-89937e44-369b-11e8-9aee-f9ac42fd59d6.png)

![5](https://user-images.githubusercontent.com/21308144/38195605-ef878128-369b-11e8-996a-ec0cf9331882.png)

- [x] There is no existing issue regarding the same topic

**Comment by weisswurstkanone** [comment]
fixed in build 229
