### ISSUE TITLE
Export CSV with localized fields

### ISSUE THREAD

**Issue by albertopallotto** [pimcore/pimcore#2742]
Hi,
I have to export a CSV file with all products, and also “localized fields” for all languages.
Debugging in the code I realize that this  function is already present and it's possible but unfortunately esist a block code, so I cannot go on.
I've tried to pass the checks, but in any case it does not work as it returns all the multilingual fields but always with the default language value.
I would like to know if development and also the correction of this function has been foreseen or not. 
If possible, I would like to receive support to solve this issue

**Comment by brusch** [comment]
I'm sorry, but I'm afraid that I didn't get the point :( 
Can you please try to explain it a bit more in detail (eg. by pointing to the lines of code in question)? 

Thank you very much!

**Comment by ckemptner** [comment]
@brusch I think this has been resolved: https://talk.pimcore.org/t/export-csv-with-localized-fields/772/2
