### ISSUE TITLE
User cannot login anymore

### ISSUE THREAD

**Issue by ofriedrich** [pimcore/pimcore#2750]
After a role has been removed, users owning this role won't be able to login.

_website/var/log/php.log:_
```
PHP Fatal error:  Call to a member function getPerspectives() on boolean in ...pimcore/lib/Pimcore/Config.php on line 661
```

*See:*
https://github.com/pimcore/pimcore/blob/343e00264db4177130ad3574127bd90f4ad5bb85/pimcore/lib/Pimcore/Config.php#L661

*How to test:*
1. User and roles should not have any perspective selected
2. Add role
3. Connect user to role
4. Delete role
=> User cannot login anymore

*Goal:*
User can login even after a connected role has been deleted.

*Possible solution:*
File pimcore/lib/Pimcore/Config.php Line 661: 
```
$perspectives = $userOrRoleToCheck->getPerspectives();
```
Change into:
```
$perspectives = $userOrRoleToCheck ? $userOrRoleToCheck->getPerspectives() : null;
```

**Comment by weisswurstkanone** [comment]
thanks a lot! fixed in build 231.

**Comment by ofriedrich** [comment]
I tried to reproduce this on an fresh installation and it looks like it depends on the configured permissions. So this seems no to be an issue.
