### ISSUE TITLE
ExtJS 6 - Copy/Paste missing in class editor

### ISSUE THREAD

**Issue by maff** [pimcore/pimcore#276]
Context menu in class editor is missing copy/paste for fields.

**Comment by weisswurstkanone** [comment]
c15dc801cc1d369c32e9638543f0a72d34e7100f 
25.6.2015 
Class Editor: copy/paste

needs to be ported from 3.4

**Comment by weisswurstkanone** [comment]
build 3558

**Comment by maff** [comment]
Looks good to me
