### ISSUE TITLE
cleanupLogFiles job not working properly 

### ISSUE THREAD

**Issue by RoKoh** [pimcore/pimcore#2762]
# Bug Report

The cleanupLogFiles jobs is rotating the logfiles on every run and does not update the timestamp in tmp_store, hence it also overwrites always the same archive log version. 

This is since Build 224, due to the following Commit: https://github.com/pimcore/pimcore/commit/2e1d136c9e1a4c4f6d9b5917658172564bcd01b3

There the TmpStore::add is used, but this does not update an existing row, due to following if statement: 
https://github.com/pimcore/pimcore/blob/master/pimcore/models/Tool/TmpStore.php#L90

**Comment by fashxp** [comment]
also the cleanup of the archived files does not work properly
