### ISSUE TITLE
Remove `type="text/javascript"`out of all <script> tags

### ISSUE THREAD

**Issue by tobiasfeldmethwalter** [pimcore/pimcore#2766]
Hello Pimcore team,

we currently have the following problem.
We integrate Javascript and CSS libraries via web feature. If we test the page with W3C, we get the warning "The type attribute is unnecessary for JavaScript resources." For each Javascript file included.
Please remove the "type =" text / javascript "when generating the Javascript Include.

Thank you

**Comment by brusch** [comment]
What do you mean by "web feature"? Just to be sure ;)
