### ISSUE TITLE
Class editor copy/paste allows to paste a Fieldcollection in an ObjectBrick

### ISSUE THREAD

**Issue by maff** [pimcore/pimcore#277]
Field collections can't be added to object bricks with the editor, however a FC can be pasted into a brick definition after copying it from a class definition.
### Steps to reproduce
1. Open a class definition containing a field collection
2. Right click the field collection and click copy
3. Open an object brick definition
4. Paste the field collection into the object brick definition and save the brick
### Issues
- Opening objects containing such a brick will fail (backend error)
- Creating new objects with such a brick works, however saving fails with an error message (`~Field Collections are only valid in Objects fieldname=[...]~`)

**Comment by weisswurstkanone** [comment]
build 67
