### ISSUE TITLE
[Assets] Ability to define custom asset types

### ISSUE THREAD

**Issue by alexpozzi** [pimcore/pimcore#2773]
First of all thanks for the great work!

I’d like to add support for InDesign files, more specifically I would like to be able to extract and show previews and attach a pdf file from the Pimcore’s asset management ui.

I saw that I can override the Pimcore\Model\Asset\Unknown class (the currently matched class for indd files) and the relative javascripts to add the features I need but it's not so clean.

It would be better to have the possibility to define custom asset types.
A possible solution would be to override the Pimcore\Model\Asset class but from what I read on the documentation this is actually not supported (it's understandable).

Does it make sense to you?
Am I the only one asking for this feature?

Regards,
Alessandro

**Comment by brusch** [comment]
@alexpozzi can you give us some more technical details of what you're planning, as we're very interested in having InDesign file support also directly in the core :) 

Thanks!

**Comment by alexpozzi** [comment]
First of all I'd like to be able to define an InDesign asset type.
This would add the possibility to easily define a specific implementation for this kind of asset.
The features I was having in mind are:
- import page previews (like image previews)
- import output assets such as pdf, eps, etc.. (like pdfs for webtoprint documents)
- store relations between assets (such as InDesign files and images)
- integrate InDesign server to run automatic tasks such as generate pdfs every time my asset changes

Besides this InDesign comes with a problem that has to be managed which is "related assets" (such as images). 
Related assets must be accessible by the client using the InDesign file in order to work properly (it's impossible to generate an high quality pdf without having access to the original images).

In my opinion this issue can be solved with different approaches:
- ship an InDesign plugin/script which will handle the upload/download (from Pimcore) of all required assets when needed (best option)
- when uploading an InDesign file to Pimcore look for related assets using xmp relational metadata and store the relation both sides (InDesign and asset side). This option would give the user the responsibility to upload related assets to Pimcore but could give him back the possibility to download a complete InDesign package if it will need to use/edit it in the future (this option is risky because you can't guarantee that all the required assets are gonna be present in Pimcore but it's less expensive in terms of development and maintenance)
- accept InDesign packages only so the user will be always forced to generate and upload an InDesign package (zipped) with all the related assets (this option is like the second one in terms of development and maintenance but it's not optimized in terms of space because it means that you could possibly store the same related assets multiple times)

I hope this would give you a better explanation of what I would like to achieve.
If I wasn't clear or if you need more details we can plan a call to discuss it better.

Alessandro

**Comment by rkxml** [comment]
Hi,
I would also be interested in having InDesign documents recognized as such, and not as Document/Unknown.

What is necessary in Pimcore (e.g. Settings/Controller/Actions ) to identify a 'new' document-type

Best Regards
Roman

**Comment by studio1gmbh** [comment]
@alexpozzi why did you close this issue? Did you manage to implement such a feature? We are looking for InDesign support too.

**Comment by NiklasBr** [comment]
Might be a duplicate of #10245?

**Comment by studio1gmbh** [comment]
@NiklasBr I thought that too but this is relating to a complete different feature (predefined document feature for assets). :) 

Here we are looking for a possibility to implement support for custom asset (file) types, that are yet unknown to pimcore (like .indd files). So users are for example able to use the thumbnail preview feature.
