### ISSUE TITLE
[Tool] \Pimcore\Tool::getHttpClient method not available in Pimcore 5

### ISSUE THREAD

**Issue by alexpozzi** [pimcore/pimcore#2777]
I don't know if this is wanted or not but the \Pimcore\Tool::getHttpClient method described in the documentation https://pimcore.com/docs/5.x/Development_Documentation/Development_Tools_and_Details/Static_Helpers.html is missing.

Should I submit a pull request?

Regards,
Alessandro

**Comment by dpfaffenbauer** [comment]
IMO: Its good that it is missing, use DI instead:

Either you inject `Pimcore\Http\ClientFactory` and use createClient function, or inject `guzzle.client` and use guzzle client directly. The difference between these two: Pimcore Factories respects proxy settings from system configuration.

**Comment by alexpozzi** [comment]
Yes, I'm already doing it (I'm actually injecting pimcore.http_client).
I was reading this piece of documentation and I was wondering if it was a documentation issue or a code issue.

BTW thanks for the answer.

**Comment by fashxp** [comment]
just removed the doc entry. ... also see here: 
https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/V4_to_V5.html#page_Pimcore-Tool-getHttpClient
