### ISSUE TITLE
CachePool - Doctrine - Tag Mismatch causes "random" removed cache-entries

### ISSUE THREAD

**Issue by Apke** [pimcore/pimcore#2783]
# Bug Report

FYI and some Question about a Refactoring for Model\Element\AbstractElement cache handling.

## Fix - Status

- Working on
  - i created a [branch](https://github.com/Apke/pimcore/tree/fix_property-cache-refresh) and add some Comments. And a debuging showed me, that adding a id to tags is only a workaround. Currently i have much to do, but next week i will add a pull-request.

## Workaround

- using Redis
  
### Expected behavior 
  
all related cache items are removed from Cache  `AbstractElement::save()` and the called `AbstractElement::clearDependentCache()`.

### Actual behavior  

"Random" deleted keys.
Ok not Random, the schema is simple `DB/cache_tags`:
- 'related' tag without-id (for example: element_properties) contains the key of the last AbstractElement, which stored that tag
- 'main' tag with element-id contains the 'related'-tag-name of the last stored on

that means: that i remove my last cached 'related'-tag like properties instead of the real-related....ohhh and i never remove the cached element

#### Debug Example

save on document with id '4' awaiting new properties.

call on `Document::clearDependentCache()`

![start](https://user-images.githubusercontent.com/5233027/38890836-d508995c-4282-11e8-9c80-f2add82e8c1a.png)

at first i jumped over `\Pimcore\Cache\Pool\Doctrine::getItemKeysByTags()`, but here is the remix of the next result

![the-remix](https://user-images.githubusercontent.com/5233027/38890948-337300d6-4283-11e8-9bf8-909330633093.png)

here i remmebered that i 'collected' the properties of child Document first and this was the first time i checked table `cache_tags` and i can only guess what the expected behaviour should be...but i will come to this point again.

only a look to the finish

![the-right-does-the-wrong](https://user-images.githubusercontent.com/5233027/38891714-72570d68-4285-11e8-9ece-3da839558b6f.png)

And at least a cache::save on that document properties.
![reason_tag-mismatch](https://user-images.githubusercontent.com/5233027/38896422-eeb92e6a-4292-11e8-9797-1526844cd6d5.png)

  
### Steps to reproduce

- go to a element like document
- switch to a 'related'-tag like properties (set a property if no one is set)
- save element

### Important Questions for Fix implementation

1. I wanted to refactor the Element-Cache usage a bit (if i am at this scope, it could be also done) and would move some duplicated code to AbstractElement and let the specific things at the specific elements. _Would this be ok?_ 
is ok if not...less work for me then ;-) ... i am not sure about which way will be better with Symfony-Autowiring feature, i got problems with static factory methods, but maybe i did something wrong

2. Cache-Tag-Konzept (optional)?
i will grep it from redis tables and create a abstraction.

Thanks and regards

Apke

P.S.: I am not sure who leave that [comment](https://github.com/pimcore/pimcore/blob/4b55e81cc109a32958c13c514645e796ed0df7cc/pimcore/models/Document.php#L847) and i was not really confused, but i got the same feelings as i run into a compareable problem with a property and connected (possible: "child"-)-relations ... and i'd like to have that beer :-D and while drinking we can think about a better solution ... maybe

and sry for my view last words...

_from developer to developer:_

please do not missunderstand it, i will explain my, first of all, reconstructered meaning.
the redis implementation is the real reason of this bug.
Really guys i like that you use a light-weight implementation and for sure the script usage will be faster then php. Really i am happy that someone think about such a stuff too, sometimes i suspect if developer questioning about the sense of purpose before cooking.
i see libraries which are toooooo much OOP for a fast key-value store like redis, and in some i really ask me how nice-looking-code should be possible if i need to create each operation, for unit-test ok...

ok to the point, you didn't follow the MVC pattern. If the PimcoreRedis is the controller, ok...it is no controller, but it prepares the data for the external service, then it should prepare the data and not the script. 
There are many class variables, which are not used, and it is possible not nice to read, but this stays the same then. Guys you need to contribute Comments in the external script.

What i want to say is, we have to services, which get the same data, which needs to do the same stuff, except the prefix thing, but both do completly different stuff and it can't be shared. If you want that only redis is used, then remove the table and the entity implementation then and return false on cache-actions without redis.
On the othersite did you really need all that stuff and think about key-length? I mean it is a key-value store with really useful features like pattern-handling on get key-values like `document_properties/*` or `dcoument/4/*` which would be resolved to `dcoument/4/dcoument` or `dcoument/4/properties`.
All the string handling looks more likes a unneeded complexity for a non-existing 'key-handling'. i mean, how would you abstract this to a memcache(d) or db?
What i see in code says: the feauture of taged-sub-object caching was created and implemented for redis.

**Comment by brusch** [comment]
Obsolete, see #7635
