### ISSUE TITLE
Strange ClassDefinition formatting when saving via listing

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#2784]
This Update-Script will update all Class-Definitions:
https://github.com/pimcore/pimcore/blob/v5.2.2/update-scripts/227/postupdate.php#L3

After that, the localizedFields are available multiple times, see screenshot below. If i'm updating the class in the backend class builder, the definition gets restored to its correct data layout (I need to say, the class itself still works correctly and so does the backend class builder)

![class](https://user-images.githubusercontent.com/700119/38931165-915af0b6-4312-11e8-839c-a4aea2dccce5.jpg)

**Comment by dvesh3** [comment]
@solverat I'm not able to reproduce it. Please share detailed steps to reproduce the issue. Thanks!

**Comment by solverat** [comment]
hey @dvesh3: create an object with some layouts, localized and non-localized fields and run the update script:

```php
$classList = new \Pimcore\Model\DataObject\ClassDefinition\Listing();
$classes = $classList->load();
foreach ($classes as $class) {
    $class->save();
}
```

**Comment by fashxp** [comment]
@solverat could you please verify if the changes of #2857 will solve that issue?
