### ISSUE TITLE
Pimcore 5.2.2 update from 5.2.1 gives error while updating

### ISSUE THREAD

**Issue by roopak27** [pimcore/pimcore#2787]
I'm trying to update Pimcore from 5.2.1 to 5.2.2 but got this error "Server threw exception - could not perform action. Please reload the admin interface and try again." I have tried this multiple times and i get the same error every time. Please see the screenshot attached for Error details. 

![screen shot 2018-04-19 at 12 47 26 pm](https://user-images.githubusercontent.com/5624780/38976761-dd7c3a46-43cf-11e8-8801-6752e4be4c2d.png)

**Comment by fashxp** [comment]
any additional information in the logs?

**Comment by roopak27** [comment]
Strange. I tried this again and It was stuck at 80% for a while and now it worked. Thanks for the quick response. Closing this issue.

**Comment by jansarmir** [comment]
i had same problem and only error, that exception was throwen, without closer description
internal:update-processor doesnot catch exceptions, so i digged here to dump problems
