### ISSUE TITLE
Feature Request: Bigger edit dialog

### ISSUE THREAD

**Issue by stefan-h-singer** [pimcore/pimcore#2798]
# Feature Request 
## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [x] There is no existing issue regarding the same topic

## Feature description 

Make edit dialog better utilize the available screen estate

![image](https://user-images.githubusercontent.com/968574/39054626-71ba406c-44b2-11e8-869d-1d61a24b1d8d.png)

**Comment by fashxp** [comment]
should be possible already. see https://pimcore.com/docs/5.x/Development_Documentation/Documents/Editables/Areablock/index.html#page_Brick-specific-Configuration

**Comment by stefan-h-singer** [comment]
Omg thanks, missed that

Den mån 30 apr. 2018 16:30Christian Fasching <notifications@github.com>
skrev:

**Comment by stefan-h-singer** [comment]
OK, stupid question perhaps but... Do I need to do this for **every** brick in **every** areablock in every view?

Also, it seems to work fine to use percent as a size specifier, should perhaps be default? IE 75% width and height?

**Comment by brusch** [comment]
@stefan-h-singer yes, at the moment there's no possibility to globally set default configurations for editables.

**Comment by stefan-h-singer** [comment]
Then I think we can reopen this feature request please. We have a lot of
area bricks and many areas, having to always specify a size to get a
decently sized edit window makes no sense.

Either there could be a way to change it globally on a per brick basis or
the default size could be changed to for instance 75% of the surface it's
in.

Den tis 8 maj 2018 06:15Bernhard Rusch <notifications@github.com> skrev:
