### ISSUE TITLE
Image Gallery attribute when marked as non-editable UI breaks and system stop working.

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#2801]
Image Gallery attribute when created under tab panel and is marked as non-editable breaks  the UI and system stop working.
** Unable to open the object when created under panel.

### Expected behavior
When image gallery attribute is added under tab panel and marked as non-editable then it should not be editable

### Actual behavior
When image gallery attribute is added under tab panel and marked as non-editable then system stop working and UI of PIM admin breaks.

### Steps to reproduce

1) Create a class and add image gallery under “Tab panel “, save the class definition.

![capture 2018-04-02 at 12 31 41](https://user-images.githubusercontent.com/21308144/39124074-ad14d958-4717-11e8-9c23-74f9ccbb57d7.png)

2) Create an object of test class(Image gallery field is editable in class) 

![capture 2018-04-02 at 12 34 12](https://user-images.githubusercontent.com/21308144/39124122-e374d192-4717-11e8-8146-b7f074523885.png)
Object is saved successfully and images are added to the “image gallery”.

3) Now mark image gallery as non-editable and save the class definition 

![capture 2018-04-02 at 12 36 33](https://user-images.githubusercontent.com/21308144/39124193-2a93911c-4718-11e8-823d-7371e16b0141.png)

4) Reload the object and save and publish it  

![tab](https://user-images.githubusercontent.com/21308144/39124528-67bd79e4-4719-11e8-94e5-62fd7ca36d2e.png)

Now try save and publish  

![capture 2018-04-02 at 12 40 52](https://user-images.githubusercontent.com/21308144/39124578-86aed172-4719-11e8-9877-34d753f21055.png)

UI breaks and whole instance stop working 

![capture 2018-04-02 at 12 44 50](https://user-images.githubusercontent.com/21308144/39124627-bc2a3044-4719-11e8-85a5-88a6e3bce05d.png)

**Comment by faridmovsumov** [comment]
I was able to reproduce this error.  This code is inside edit.js
web/pimcore/static6/js/pimcore/object/helpers/edit.js

![image](https://user-images.githubusercontent.com/1541412/39430059-066cd3f0-4c8d-11e8-933d-3c4b3cc09e46.png)

**Comment by weisswurstkanone** [comment]
fixed in build 235
