### ISSUE TITLE
Add getters to HeadMeta Templating Helper

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#2803]
## Feature description 
There is the setProperty function in the HeadMeta Templating Helper but I'm missing a getProperty function. Would be useful to see if og:title is already filled before setting it for example.

**Comment by dpfaffenbauer** [comment]
👍 for that as well, this is how I do it currently:

https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Behat/Context/Domain/SEOContext.php#L85

**Comment by brusch** [comment]
```php
$headMeta->getItem('name', 'description');
```
