### ISSUE TITLE
Call to a member function supportsInheritance() on null

### ISSUE THREAD

**Issue by elenachoi** [pimcore/pimcore#2809]
This bug appears when creating child objects (class allows inheritance) with field collections that have empty localized fields.

Stack trace:
Symfony\Component\Debug\Exception\
`FatalThrowableError`
in pimcore/models/DataObject/Localizedfield.php (line 275)

`Localizedfield->getLocalizedValue('text', 'en', true)`
in pimcore/models/DataObject/Localizedfield.php (line 299)

`Localizedfield->getLocalizedValue('text', 'en')`
in var/classes/DataObject/Fieldcollection/Data/Repeater.php (line 124)

`Repeater->getText()`
in vendor/twig/twig/lib/Twig/Extension/Core.php (line 1605)

**Comment by fashxp** [comment]
hi,
could you describe the steps to reproduce it a bit more in detail? 

Thanks...

**Comment by elenachoi** [comment]
Hi yes. My apologies for an incomplete report.

The same steps to reproduce as in issue #2810. No errors as of now. The error is thrown when I am trying to call the method `repeater->getText()` to render it in a view. On another note, it doesn't seem like fieldcollection supports inheritance (doesn't create same repeater fields in the child objects as in parent), so my quick fix is to set `$allowInheritance = false` for `$context['containerType'] == 'fieldcollection'`.

**Comment by weisswurstkanone** [comment]
Thanks a lot!

Fixed in build 236.

**Comment by MansoorAliBabar** [comment]
thank you so much Avatar
Josef Aichhorn it was big problem for to handle but thanks to your help it was sorted
