### ISSUE TITLE
XML Sitemap bugs

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#2811]
# Bug Report
Sitemaps do not behave the way I think they should behave but maybe that's just my usecase.

Problem 1: Sites
If we have multiple sites, our current structure is sitemap_com.xml for website.com and sitemap_de.xml for website.de if website.de and website.com are sites in pimcore. The current sitemap feature does list all sites in one single sitemap under the first site and does include sites as subtree.

Problem 2: Pretty URLs
I believe that the Pretty URL (Custom Slugs / Clean URL) should be used in the sitemap (as it is used by links everywhere) but instead the full path is being used.

Problem 3: New sections as described in the docs are added if the sitemap is generated on the fly but are ignored if the cli command bin/console presta:sitemaps:dump is executed.

**Comment by Cruiser13** [comment]
@brusch could you look into these bugs please?

**Comment by brusch** [comment]
Problem 2 solved by #2982

**Comment by Cruiser13** [comment]
@brusch thank you. Any idea concerning problem 1 and 3?

**Comment by dvesh3** [comment]
Hey @Cruiser13 could you please explain problem 1 & problem 3 in detail like if you are using custom generator? or any configuration for your sitemaps? for me both option works as expected!

**Comment by dvesh3** [comment]
Hey @Cruiser13 any update on this?

**Comment by Cruiser13** [comment]
@dvesh3 for problem #1: there should be one sitemap for each site in a multi domain setup. But pimcore does render all docs in one sitemap. In this setup, we'll end up with a sitemap containing the en tree although it's a different site:

![pimcore tree](https://user-images.githubusercontent.com/2771909/49430771-3460e100-f7ac-11e8-9846-184b3aa2fa8f.png)

Problem 3 exists if using custom link generators as described in the docs (BlogGenerator) here: https://pimcore.com/docs/5.x/Development_Documentation/Tools_and_Features/Sitemaps.html
If you call the sitemap directly everything is fine (but you'll run into timeouts on larger sites). If you run the console command, it'll not include the custom sections (app_news section in the docs).

**Comment by brusch** [comment]
Closed due to inactivity.
