### ISSUE TITLE
HTTP Error list is empty

### ISSUE THREAD

**Issue by ba-c** [pimcore/pimcore#2822]
### Expected behavior 
404 Errors are shown at Marketing => Search Engine Optimization => HTTP Errors
  
### Actual behavior  
No 404 errors are shown. Table "http_error_log" is empty.
  
Tested at five different installations:
Pimcore 5 Build: 235

**Comment by brusch** [comment]
Was not migrated from v4: 
https://github.com/pimcore/pimcore/blob/b98bef1620ab930eccf1e5ee0fab18042b49ea11/pimcore/lib/Pimcore/Controller/Plugin/HttpErrorLog.php#L67
