### ISSUE TITLE
Bug on a sent email item deleting

### ISSUE THREAD

**Issue by iantiporuk** [pimcore/pimcore#2828]
There is no pagination parameters in the request POST /admin/email/email-log.
![screenshot from 2018-05-08 13-46-52](https://user-images.githubusercontent.com/4301213/39753128-5e2034a4-52c6-11e8-87fb-1b7f82c61018.png)
You need to add pagination information to  the  request when email deleted from Sent Email table.

### Expected behavior 
Updates only current page of table.

### Actual behavior  
The entire table is updated.

### Steps to reproduce  
Go to Tools -> Email -> Sent Emails(Global)
Try to delete a row from table.
  
### Code example 
/web/pimcore/static6/js/pimcore/settings/email/log.js:357
```js
            {
                xtype: 'actioncolumn',
                width: 30,
                menuText: t('delete'),
                items: [{
                    tooltip: t('delete'),
                    icon: '/pimcore/static6/img/flat-color-icons/delete.svg',
                    handler: function (grid, rowIndex) {
                        var rec = grid.getStore().getAt(rowIndex);
                        Ext.Ajax.request({
                            url: '/admin/email/delete-email-log',
                            success: function(response){
                                var data = Ext.decode( response.responseText );
                                if(!data.success){
                                    alert('Could not delete email log');
                                }
                            },
                            failure: function () {
                                alert('Could not delete email log');
                            },
                            params: { id : rec.get('id') }
                        });
                        grid.getStore().removeAt(rowIndex);   <--------- Problem is here
                    }.bind(this)
                }]
            }
``` 
I have fixed this bug using method `reload` instead of `removeAt`:
```js
grid.getStore().reload(); 
```
But it sent incorrect xaction parameter.

**Comment by brusch** [comment]
Can't see any problem. 
When I delete an item, it get's removed from the grid and correctly deleted in the backend. 
Why would we completely reload the grid if just one item was deleted? 
Can you be a bit more specific of what you want to achieve? 

Thanks!

**Comment by iantiporuk** [comment]
Yeah, the removing process works good. But after removing you send request in background i have mentioned above. So this request doesn't have pagination parameters. My grid  has more then 50 000 rows and it takes a lot of time to process this request, I geuss this is because this request doesn't have pagination parameters and all rows are processed instead of only a current page.

Thanks.

**Comment by brusch** [comment]
Hmmm, I still don't get the point (why should we pass the paging information to the deletion request?) - maybe it's easier if you just create a PR to fix your problem? :) 

Thanks!

**Comment by pquerner** [comment]
You delete 1 item from page 5, you expect it to reload page 5 only, not page 1...10000.

I completely understand the issue here, as it can take ages for the page to respond for such a little task.

**Comment by iantiporuk** [comment]
Hi,
Yes, this is exactly what i meant.

Thank you
