### ISSUE TITLE
Purpose of preOpen Object/Document/Asset

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#2833]
I was just playing around with preOpenObject and actually tried to not allow the user to open the Object for any reason. But thats not possible, even if I throw an error, Pimcore keeps carrying on with opening the object. I guess thats the same case for Documents und Assets.

So, now I am wondering whats the actual purpose for those functions? I mean, without the PR #2832 preOpenObject is useless, you don't get any information what object is getting opened. You can't prohibit Pimcore of opening the object, so what it is for then?

**Comment by brusch** [comment]
Done by  #2832

**Comment by brusch** [comment]
At the moment not, but we could implement it (eh, by using the return value) ... I don't see any problems with that.

**Comment by dpfaffenbauer** [comment]
It would make sense, should I create a separate issue for that?

**Comment by brusch** [comment]
yep, thanks!
