### ISSUE TITLE
[Extjs] allow preOpen events to stop pimcore on opening the element

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#2845]
It should be possible to stop Pimcore on opening a element using the preOpen Event.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
