### ISSUE TITLE
installing Pimcore 5

### ISSUE THREAD

**Issue by GaneshKandu** [pimcore/pimcore#2848]
Hi,

I am installing Pimcore 5 using installation Guide given in link

[https://pimcore.com/docs/5.x/Development_Documentation/Getting_Started/Installation.html#page_Pimcore-Installation](https://pimcore.com/docs/5.x/Development_Documentation/Getting_Started/Installation.html#page_Pimcore-Installation)

Installation Guide says to create virtual Directory
web is as vhost and remaining out side of document root
like

- .ci
- .github
- .travis
- app
- bin
- install-profiles
- pimcore
- src
- web (document root)
	- pimcore/static6
	- .htaccess
	- app.php
	- install.php
- src
- ...

i have all ready setup document root as public_html & want to install like

- Pimcore
	- .ci
	- .github
	- .travis
	- app
	- bin
	- install-profiles
	- pimcore
	- src
	- src
	- ...
- public_html ( Document root )
	- pimcore/static6
	- .htaccess
	- app.php
	- install.php
 

Is there any way in which we install like this ?

**Comment by brusch** [comment]
First of all, please use our forum ( https://talk.pimcore.org/ ) for support, this is not the right place for asking questions. 

Anyway, ... what you are asking for is possible, although it isn't recommended. 

### How-To

- Open `composer.json` and change the value of `symfony-web-dir` from `web` to `public_html`. 
- Create the file `app/constants.php` and put the following content into it: 
```php
<?php

define('PIMCORE_WEB_ROOT', realpath(__DIR__ . '/../public_html'));
```

- That's it (just tested and works fine).
