### ISSUE TITLE
Generation of low quality previews with sqip and spaces in the imagename

### ISSUE THREAD

**Issue by go4webch** [pimcore/pimcore#2853]
Hi there,

We were having some problems with the generation of low quality previews for images.

After some search, we realised it only happend with images with spaces in their names.

A quick fix did the work for us:

**pimcore/models/Asset/Image.php:122**

old:
`\Pimcore\Tool\Console::exec($sqipBin . ' -o ' . $svgPath . ' '. $pngPath);`

new:
`\Pimcore\Tool\Console::exec($sqipBin . ' -o "' . $svgPath . '" "'. $pngPath . '"');`

Could you check this fix and implement it in future versions?

Thank you.

**Comment by dpfaffenbauer** [comment]
I would recommend to create a PR with that fix, so it is easier for the Pimcore Team to include that fix

**Comment by brusch** [comment]
Absolutely, please just quickly create us a PR :) Thank you very much!
