### ISSUE TITLE
'Just direct child objects' option in Object and Asset grid is not working properly

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#2860]
### Expected behavior 
  When checkbox 'just direct child objects' is checked , Only the direct children of that folder must be listed.
### Actual behavior  
   When checkbox 'just direct child objects' is checked , all children of that folder gets listed.
Sometimes it happens that the direct children gets listed , just uncheck and again check the checkbox, all children of that folder gets listed.

### Steps to reproduce  
Open a folder that have sub folders that have some object under them.Check 'just direct child objects' checkbox.
![child object issuess](https://user-images.githubusercontent.com/21308144/40236859-732905b6-5acc-11e8-9c4f-201dca37c0ad.png)
![child object issues](https://user-images.githubusercontent.com/21308144/40236860-73597642-5acc-11e8-84ff-ae6d319f5e11.png)

Same issue persists in asset listing as well .
![assetsjustchilds](https://user-images.githubusercontent.com/21308144/40236649-e4ace8fc-5acb-11e8-8859-0d3c64dab606.png)

**Comment by weisswurstkanone** [comment]
fixed in build 238
