### ISSUE TITLE
[Objects] Possibility to show the key in default grid views

### ISSUE THREAD

**Issue by camico** [pimcore/pimcore#2870]
# Feature Request 
## Feature description 
In the Data Objects - Classes configuration UI, would it be possible to add the object's KEY as a possible selection under "Visibility of system properties"?
While it is already possible to show the full PATH, but sometimes this may not be desirable for not-so-technical users, or for complex tree structures.

And I'm aware it's also possible to create a custom column configuration for the grid views and add the KEY there, but I haven't found a way to set a configuration as the default for all users?
It would be an even cooler feature if that could be done under the "Save & Share" tab maybe? (like "Share globally + Set as global default")?

**Comment by brusch** [comment]
![image](https://user-images.githubusercontent.com/142037/41219791-b9ab5638-6d5f-11e8-927b-271da5170187.png)

**Comment by weisswurstkanone** [comment]
build 259
