### ISSUE TITLE
Tabulator key no longer usable in shared translation

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#2889]
### Steps to reproduce

1. open Tools > Translation > Shared Translations
2. click the "add" button and enter a translation key
3. click in one language field, enter a translation for the new translation key
4. press the tabulator key

### Expected behavior

The translation is saved and you're in the field for the next language.
  
### Actual behavior  
  
You're in the field for the next language, but the translation is gone and you have to enter it again (and don't use the tabulator key again!).

It's a regression but I can't say which version broke this. It definitively worked in Pimcore 5.0.2 and it's definitively broken in Pimcore 5.2.2 and 5.2.3.

Tested with Firefox and Chrome.

**Comment by weisswurstkanone** [comment]
fixed in build 253
