### ISSUE TITLE
Grid-View of Objects in Search-View not sortable

### ISSUE THREAD

**Issue by smaier** [pimcore/pimcore#289]
I choose:
search > objects > select my class (with custom fields) > i select "firstname" or any other field but the default-fields (id, path, creation-date, modification-date) > it seems pimcore sorts but in fact does not - at least not by the choosen field.
The Problem seems to exists in any pimcore-version (1.4, 2.0,3.1.1 testet)

**Comment by smaier** [comment]
is this the expected behaviour? thus my request a feature-request, or is it a bug?

**Comment by fashxp** [comment]
sorting for object class specific fields in object search result is currently not possible.
sorting for columns that do not allow sorting is already disabled.
