### ISSUE TITLE
Grid-Configuration in Search-View not saved

### ISSUE THREAD

**Issue by smaier** [pimcore/pimcore#290]
I choose:
Search > objects > select any custom class (p.e. customer) > click on the right-arrow / kotext-menu next to any field (p.e. "id") > column-configurator (Spaltenkonfigurator) > i make my selection > i close the search-window > reopen and select my class > fields are back to default / no way to save the column-setup

**Comment by smaier** [comment]
is this the expected behaviour? thus my request a feature-request, or is it a bug?

**Comment by weisswurstkanone** [comment]
Hi, this is a feature request :-)

**Comment by smaier** [comment]
thanks a lot!

**Comment by fashxp** [comment]
add predefined grid configuration button to search dialog once a specific class is selected

![image](https://user-images.githubusercontent.com/8792145/37365373-99da7256-26fd-11e8-840d-d49b090554df.png)
