### ISSUE TITLE
Error occurs if admin translations are opened through document types

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#2900]
### Expected behavior 
 When Admin Translations are opened through document types no error message should be displayed 
### Actual behavior  
  When Admin Translations are opened through document types  error message is be displayed. 
### Steps to reproduce  
  1.Open Admin Translations.
![open admin translations](https://user-images.githubusercontent.com/21308144/40980349-c85c9a48-68f5-11e8-8076-295ebdab3039.png)

  2.Open Document Types
![open document types](https://user-images.githubusercontent.com/21308144/40980348-c82baa28-68f5-11e8-9824-64aa9f0afe62.png)

  3. Click on translate button given on the right side of document type.
![syntax error](https://user-images.githubusercontent.com/21308144/40980347-c7f9e376-68f5-11e8-80d7-667473d0b8ca.png)

Error message is displayed.This message is also displayed if opening admin translations for the second time from document types.
Steps-  1.Open Document Types
             2. Click on translate Button.Now Admin Translations will be opened without any error.
             3. Go Back to document types and again click on translate button
             4.Error message is displayed.

**Comment by weisswurstkanone** [comment]
fixed in build 250
