### ISSUE TITLE
UI of number slider breaks if marked as vertical

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#2901]
### Expected behavior 
  UI of number slider must not break if marked as vertical
### Actual behavior  
  UI of number slider breaks if marked as vertical
### Steps to reproduce  
1.Add a number slider in your class.
![add slider](https://user-images.githubusercontent.com/21308144/40981221-10decb72-68f8-11e8-8977-9b21c3e3850d.png)

2.Now create a object of that class. Open the object. Number slider is does not breaks in this case.
![horizontal image slider](https://user-images.githubusercontent.com/21308144/40981220-10b30280-68f8-11e8-8211-3d2f31e0e2ab.png)

3.Mark Number slider as vertical.
![make slider vertical](https://user-images.githubusercontent.com/21308144/40981219-1084b07e-68f8-11e8-8ed8-8f809a6132e2.png)

4.Open the Object.
![ui of slider breaks](https://user-images.githubusercontent.com/21308144/40981216-10536b0e-68f8-11e8-9405-c11a52b708cb.png)

**Comment by weisswurstkanone** [comment]
thx, fixed in build 253
