### ISSUE TITLE
error robots.txt if php.ini zlib.output_compression = On 

### ISSUE THREAD

**Issue by lorextera** [pimcore/pimcore#291]
When zlib.output_compression is set to "On", the code  `while (@ob_end_flush()) ;` suddenly exits the PHP script.
See in [CommonFilesFilter.php @ line 65](https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Controller/Plugin/CommonFilesFilter.php#L65)

```php
if(is_file($robotsPath)) {
    while (@ob_end_flush()) ;
    header("Content-Type: text/plain; charset=utf8");
    readfile($robotsPath);
    exit;
}
```

In parallel I suggest sending header before flush (*this doesn't solve*): 
```php
if(is_file($robotsPath)) {
    header("Content-Type: text/plain; charset=utf8");
    while (@ob_end_flush()) ;
    readfile($robotsPath);
    exit;
}
```

**Comment by brusch** [comment]
Thanks!

**Comment by NiklasBr** [comment]
I don't think `ob_end_flush()` is used in Pimcore today. Maybe `zlib.output_compression` no longer need to be turned off?

**Comment by jdreesen** [comment]
https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/src/Controller/PublicServicesController.php#L83

**Comment by NiklasBr** [comment]
Didn't see it when I search, thanks @jdreesen.

Thinking out loud here: If this is only affecting robots.txt rendering, maybe it no longer need to be globally disabled and be moved there, so it is skipped in every Kernel boot phase?
