### ISSUE TITLE
[Assets] Make image transformation adapters configurable again

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#2914]
Functionality wasn't migrated from v4 to v5. 
see: https://github.com/pimcore/pimcore/blob/fa8298c6caabc3496d17a3b25107d4ad1e10bc9d/pimcore/lib/Pimcore/Image.php#L28 

- \Pimcore\Image\Adapter\ImageMagick should be usable again
- possibility to add custom transformation adapters (eg. Libvips, GraphicsMagick, ...)

**Comment by stormbyte** [comment]
@brusch Is this functionality going to be added to the roadmap?
on some versions of image magic don't handle certain new images with has been solved in newer versions of image magic but not always available.
Adding this option would allow the thumbnail to be created.
The GD fallback is not in the creation of the thumbnail.

**Comment by brusch** [comment]
@stormbyte actually not, but we're happy to merge PRs for that! (Shouldn't be too hard to implement and we're happy to help) 😊

**Comment by ramundomario** [comment]
it would be nice to be able to configure video adapters as well. 
Use Case: Making Video Thumbnails with [AWS Elemental MediaConvert.](https://aws.amazon.com/mediaconvert/?nc1=h_ls)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
