### ISSUE TITLE
[Ecommerce] Evaluate Integration of OmniPay to Ecommerce Framework

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2917]
see https://github.com/thephpleague/omnipay

is integration possible and therefore profit from all the integrated payment providers there?

**Comment by dpfaffenbauer** [comment]
saying that with experience: not really a one implementation, use a lot of providers lib. I did it with CoreShop 1 and still had to make a lot of custom stuff for each provider. We ended up having a OmnipayCoreShop Plugin and implement each provider separated as well in there.

**Comment by fashxp** [comment]
so, it sounds better as it actually is?

**Comment by dpfaffenbauer** [comment]
Yes, unfortunately. Take a look here https://github.com/coreshop/Omnipay

**Comment by brusch** [comment]
Maybe https://github.com/Payum/Payum ?

**Comment by fashxp** [comment]
maybe I'm missing something ... but it seems that payum only handles client-side redirects but no server-to-server requests between payment provider and shop - which can be dangerous when client-side redirect doesn't work and therefore the shop never gets to know that a payment transaction was successful.

**Comment by dpfaffenbauer** [comment]
you are definitely missing something ;) Payum is super powerful and great but very hard to understand and implement. it handles all the token validation/invalidation for you and url generation for capture/refund/notify (which based on experience can raise problems as well

Payum is able to do server2server requests as well, and that in multiple ways, either for payment notifications (NotifyRequest) or for client side Payments where you communicate via tokens. 

But: Doing client side payments is a bit tricky to be honest, you need some extensions and inject variables like Pimcore Document, Order, etc. Still not a big deal if you know how to do it. But took me hours of debug to understand it.

The easiest way of course is a Off-Site Payment, such a payment provider is implemented pretty quickly if you are doing the payum inclusion right. Like CoreShop does -> there is only one Controller that handles all the Payments, regardless of the Provider nor Order Type or anything else you can imagine. Everything is done using extension tight to the gateway type.

And: There is also a Omnipay Bridge for Payum which works as well. I use it in production for Worldpay.

So overall: 
 - CoreShop uses Payum for Payment Handling and it is great.
 - It only uses one entry point for payment: https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/PayumBundle/Controller/PaymentController.php and of course the Symfony Payum Controllers
 - No matter what Payment Provider you need, you don't need to write any weird stuff for Order Management or Controller stuff, that is handled with extension: https://github.com/coreshop/CoreShop/tree/master/src/CoreShop/Bundle/PayumBundle/Extension
 - Integrating a new Provider is pretty easy, you only need to create some extension for specific Payment Provider Events to trigger a workflow or something https://github.com/coreshop/PayumPowerpayBundle/blob/master/src/CoreShop/Payum/Powerpay/Extension/CancelPaymentExtension.php
 - Configuration is sort-of handled by the Bundle as well, and can also use straight Symfony Configuration
 - Bridge available for Omnipay 3 (https://github.com/Payum/OmnipayV3Bridge)

**Comment by fashxp** [comment]
wait for https://github.com/pimcore/pimcore/issues/3285 ... 
then payment handling and integration of payum should be easier

**Comment by brusch** [comment]
Obsolete due to #6805
