### ISSUE TITLE
Unable to expand collapsed panel.

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#2920]
# Bug Report
### Expected behavior 
  Unable to expand collapsed panel.
### Actual behavior  
  On Clicking expand button , the collapsed panel must get expanded.
### Steps to reproduce  
  In Class add a panel and mark this panel as collapsed and collapsible.
![make pannel collapsed and collapisibe](https://user-images.githubusercontent.com/21308144/41226157-4dae1978-6d8e-11e8-978f-b89f003f54e2.png)

Now create an object of that class and click on expand button.The panel will not get expanded.

![not able to expand](https://user-images.githubusercontent.com/21308144/41226193-6ac303ac-6d8e-11e8-93f3-3ffca4701a45.png)

**Comment by brusch** [comment]
I'm afraid that this options can't work at the root-level :|
