### ISSUE TITLE
Database admin, select table doesn't work

### ISSUE THREAD

**Issue by avdb** [pimcore/pimcore#2926]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [x] This is not a security issue / vulnerability -> use [this form](https://pimcorehq.wufoo.com/forms/pimcore-security-report/) instead
- [x] Behavior is reproducible on http://demo-basic.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [x] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [x] There's no existing ticket for the same issue
- [x] Remove unused sections from below and this bullet points

### Expected behavior 
  - get table data
### Actual behavior  
  - get 500 error
### Steps to reproduce  
 - login in admin interface as admin in Pimcore 5
 - go to database administration
 - select a table to show data
 - get 500 error (Call to a member function tableHelp() on null)

# Feature Request 
## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [x] There is no existing issue regarding the same topic

<img width="1792" alt="screen shot 2018-06-11 at 15 59 34" src="https://user-images.githubusercontent.com/1193946/41236399-50992760-6d91-11e8-8cc0-f5b038b618d6.png">

**Comment by brusch** [comment]
Dublicates #2610 #2635
