### ISSUE TITLE
[Objects] Backend validation for Email data component field

### ISSUE THREAD

**Issue by kovinet** [pimcore/pimcore#2931]
## Feature description 
When adding normal Text Data Component to Data Object there is a part for RegEx validation string , which is nice. But, if you add CRM > Email instead, then there is no option to enter validation string.

It would be nice if there would be email validation by default for this field in backend or at least same inputs for manually entering RegEx expression.

**Comment by brusch** [comment]
You mean a real time frontend validation? 
Because when hitting save, the email address is already validated: 

![image](https://user-images.githubusercontent.com/142037/42440436-09c54720-8366-11e8-8251-82a25f7a7215.png)

**Comment by kovinet** [comment]
When I tested at the time of reporting this issue I didn't get this error message. Since it is already validated I think this is enough.
