### ISSUE TITLE
Error while Basic Migration from Pimcore 4.6 to Pimcore 5

### ISSUE THREAD

**Issue by BenjaminEden** [pimcore/pimcore#2938]
Pimcore-CLI is installed

pimcore.phar pimcore5:check-requirements -> everything OK

Downloaded pimcore-5.0.1-zip

pimcore.phar pimcore5:migrate:filesystem . ./pimcore-5.0.1.zip -> everything OK

sudo -u www-data composer update --no-scripts -> everything OK

sudo -u www-data composer update -> Error:

[RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:
  Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Pimcore\Tool\ArrayUtils::arrayMergeRecursiveDistinct() must be of the type array, null given, called in /var/www/sperrer/pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/PimcoreCoreExtension.php on line 367 in /var/www/sperrer/pimcore/lib/Pimcore/Tool/ArrayUtils.php:33
  Stack trace:
  #0 /var/www/sperrer/pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/PimcoreCoreExtension.php(367): Pimcore\Tool\ArrayUtils::arrayMergeRecursiveDistinct(Array, NULL)
  #1 /var/www/sperrer/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(39): Pimcore\Bundle\CoreBundle\DependencyInjection\PimcoreCoreExtension->prepend(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
  #2 /var/www/sperrer/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\M in /var/www/sperrer/pimcore/lib/Pimcore/Tool/ArrayUtils.php on line 33

bin/console -> give's the same error.  
  
I've successfully done the migration process for another project some time ago. But I'm stuck now...

Is there a way to migrate the database from hand? The rest (get a clean pimcore 5 instalation, rewrite the  templates) could not be as hard, but there is a lot of data in the database.

**Comment by brusch** [comment]
-> https://talk.pimcore.org/ thanks!

**Comment by brusch** [comment]
Quick fix: 
Open `pimcore/lib/Pimcore/Tool/ArrayUtils.php` remove type hints of `\Pimcore\Tool\ArrayUtils::arrayMergeRecursiveDistinct` and try again.

**Comment by BenjaminEden** [comment]
Thanks Bernhard, but the fix only resolves in an invalid argument exception from the foreach.
If I test for NULL on the second parameter and return the first if it is, there are only more errors.

If've tried to install a clean pimcore 5.0.1 via composer and get the exact same error. I think there is something wrong with the thirdparty libs loaded via composer.
