### ISSUE TITLE
Broken 404 page on /admin[...] urls

### ISSUE THREAD

**Issue by laurenz-glueck** [pimcore/pimcore#2939]
# Bug Report
  
### Expected behavior 
Opening a not existing link like [https://demo-basic.pimcore.org/administration](https://demo-basic.pimcore.org/administration) should redirect to the configured 404 error page of the site.
### Actual behavior  
Opening any link starting with /admin followed by any character besides a slash (e.g. /administration) shows this standard / confusing error page and not the configured error page in the site config:
![image](https://user-images.githubusercontent.com/2734232/41355601-354aebbe-6f22-11e8-95c6-53289daa78b6.png)

### Steps to reproduce  
Open [https://demo-basic.pimcore.org/administration](https://demo-basic.pimcore.org/administration) or any other link starting with /admin followed by any character besides a slash (for the actual admin backend). We found this issue because of old links used by our customer from the previous cms...
**Note:** The project needs to be in prod mode, in dev the normal dev-error page appears.

### Current "quick" fix in htaccess
We redirect this links to the start page
```
RewriteCond %{REQUEST_URI} ^\/admin[^\/]+
RewriteRule .* https://%{HTTP_HOST} [R=301,L]
```

**Comment by brusch** [comment]
See also #3598 - Pimcore has 3 reserved route prefixed, that behave differently - solving that would cost a lot of time and would add a lot of additional complexity - cost effectiveness not really given. For that reason I'm closing this issue now. 

Thanks anyway for reporting.
