### ISSUE TITLE
Type restriction on href fields in custom Layouts

### ISSUE THREAD

**Issue by cleggypdc** [pimcore/pimcore#294]
It seems that by creating a custom layout on an href with restrictions, these restrictions are nested in admin/object/get/ - also something funky is happening with documentTypes

![image](https://cloud.githubusercontent.com/assets/1098498/10971928/c29bc6c4-83ce-11e5-86d8-e9275494a042.png)

BUILD: 3561

**Comment by weisswurstkanone** [comment]
Hi Paul,

Unfortunately, I failed to reproduce this. Could you please share a (condensed) class definition (json export would be very helpful) and let us know whether you are switching forth and back from Ext 3.4 to 6 or not. 

Thx!

Josef

**Comment by cleggypdc** [comment]
Hi Josef,

Since fixing this in the class definition itself I also cannot reproduce this error, I think it may well have been because of a switch between ExtJS 3.4 / and 6 and back and forth. I spent a couple of hours looking into this issue and have found a different issue.

Attached is a condensed version of the definition
https://dl.dropboxusercontent.com/u/1321201/pimcore/class_test_export%20%281%29.json

**Comment by weisswurstkanone** [comment]
![assettypes](https://cloud.githubusercontent.com/assets/6142086/10998694/3315f8a2-8497-11e5-98d2-8448fae27440.png)

**Comment by weisswurstkanone** [comment]
Hi Paul,

many thanks! I was able to reproduce this. I will submit a fix ASAP (see screenshot above).

Josef

**Comment by weisswurstkanone** [comment]
Ok, that was too early. I again failed to reproduce this with a fresh class. However, I can clearly see it in your custom layout definition. Maybe for historical reasons?
If you have any idea regarding special steps needed to investigate this further please give me a shot.

**Comment by brusch** [comment]
Please reopen if this is still an issue or if there are any new findings. Thanks!
