### ISSUE TITLE
Localized fields hide/disable single fields by language

### ISSUE THREAD

**Issue by ascheider** [pimcore/pimcore#2945]
## Feature description 
Currently it is not possible to hide or disable single localized fields by language.
It is only possible to do for entire language by rights.
So i want for example be able to do something like:
EN:
Name - visible
Street - visible
Zip - invisible
DE:
Name - invisible
Street - visible
Zip - visible

**Comment by brusch** [comment]
Thanks a lot for sharing your ideas. However, since this is quite a special interest use-case, we're not gonna work on that anytime soon. Please feel free to continue the discussion here. 
Thanks for your understanding.
