### ISSUE TITLE
[Documentation] Informe Redis version compatible

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2947]
From the documentation (https://pimcore.com/docs/4.6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Performance_Guide.html), Redis v2 is recommended.
Is it always the case (as it seems it is outdated: https://redis.io/download).
If not it should be corrected i think.

Maybe documentation should say which version of Redis Pimcore is compatible 3 and/or 4 ?
(For esxemple here: https://pimcore.com/docs/4.6.x/Development_Documentation/Installation_and_Upgrade/System_Requirements.html)

On the same subject, same remark for ElasticSearch too (v5 and/or v6 ?), advised/compatible version isn't mentionned for the Advanced Object Search (https://github.com/pimcore/advanced-object-search). Maybe you gave no information because it works with any versions ?

Thanks.

**Comment by mgomse** [comment]
@Yivan 

Pimcore 4 (which links you provided) is not supported anymore (well it is just for critical bugs and security issues) - https://pimcore.com/en/resources/legacy

About Pimcore5:

- redis:
  - right now there is just "Redis is recommended" : https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Performance_Guide.html
  - moreover [here](https://pimcore.com/docs/5.x/Development_Documentation/Development_Tools_and_Details/Cache/index.html#page_Recommended-Redis-Configuration) you can find some info about minimum supported version ([this link](https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/Within_V5.html#page_Build-188-2018-01-26) can also be interesting for you)
- Advanced Object Search:
   - https://github.com/pimcore/advanced-object-search/blob/master/composer.json - from here we can find information that **"ongr/elasticsearch-dsl": "~5"** is used
  - it means (I understand it this way) that Advanced Object search is compatible with >= v5 of ElasticSearch (according to https://github.com/ongr-io/ElasticsearchDSL#version-matrix)

So in my opinion it seems that for Pimcore5 the higher versions (of Redis and ES) are recommended, **but I agree that maybe it will be good to add somewhere this information in the documentation** :smile_cat:

**Comment by Yivan** [comment]
Thanks @mgomse for your comment.
Like you said, maybe eslasticsearch 6 is not compatible so, i think it depend if multiple mapping is used for indices (https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking-changes-6.0.html).

**Comment by Yivan** [comment]
Thanks @brush !

What about elasticsearch version for advanced objet search please ? (see previous posts) Do i need to open an issue for this too ? It seems the plugin is compatible >= v5 < 6 of ElasticSearch (according to https://github.com/ongr-io/ElasticsearchDSL#version-matrix). Maybe should be on the requirement documentation of the plugin.

**Comment by brusch** [comment]
@Yivan Yes, please open a ticket at the right place for AOS: 
https://github.com/pimcore/advanced-object-search/issues

Thanks!

**Comment by Yivan** [comment]
@brush Issue is opened for Advanced Object Search: https://github.com/pimcore/advanced-object-search/issues/23
Thanks.
