### ISSUE TITLE
Image asset preview in tag assignment view

### ISSUE THREAD

**Issue by hschulz** [pimcore/pimcore#2950]
#### Add an image preview (thumbnail?) to the tag assignment view for image assets

As the title says I would very much like the ability to see the image that I am tagging in the tag view tab.
I have searched through the code and documentation but haven't found a way to modify the Ext JS code that renders the backend UI through a bundle in pimcore 5.

As far as I know the only way of seeing the image in the tag view is to hover over the filename in the asset tree which then shows the preview popout or whatever that is called.

Looking forward to your response.

**Comment by fashxp** [comment]
if we add this, we should make it hideable, because for small screens this could become quite challenging.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
