### ISSUE TITLE
Static Select options for Dynamic select

### ISSUE THREAD

**Issue by avdb** [pimcore/pimcore#2956]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [x] This is not a security issue / vulnerability -> use [this form](https://pimcorehq.wufoo.com/forms/pimcore-security-report/) instead
- [ ] Behavior is reproducible on http://demo-basic.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [ ] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [x] There's no existing ticket for the same issue
- [x] Remove unused sections from below and this bullet points

### Expected behavior 
- export class should not have options for the dynamic select options

  
### Actual behavior  
- export class has names of other objects as dynamic select options
  
### Steps to reproduce  
- create object class
- use dynamic select, fill in "Options Provider Class or Service Name"
( I made a service to get the name of published objects of other object class )
- save and export object class

**Comment by weisswurstkanone** [comment]
build 270
