### ISSUE TITLE
Only one language mandatory

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#2958]
Hi,

For a client (for several projects even) need to make only one language mandatory on the set of localized fields. Assuming that my content is localized in 3 languages (FR, EN, ES), we would like only one of these 3 languages to be required during registration and publication.

Cheers,

**Comment by jansarmir** [comment]
set field as optional and implement **onObjectPreUpdate** event with your own rules
and throw exception if problem
````
throw new ValidationException("Empty title value (sk_SK)");
````

**Comment by romainp89** [comment]
Yes, it's a solution, but an improvement in the configuration of the class would be more flexible for non-developer users

**Comment by kanevbg** [comment]
Had this requirement many times. Will be practical says my experience.

**Comment by kanevbg** [comment]
Will be great to can mark what languages for are required for both on field-level and on global level. Field has higher priority than global.

**Comment by akno77** [comment]
Any news about this feature request?

**Comment by cancan101** [comment]
Is there a way to have the required language for an object be based on another field on the object? For example for Products sold in the European market, the primary (mandatory) language differs from Products sold in the north American market.

**Comment by matthiashamacher** [comment]
@cancan101 Not by default. But if you update the following if condition / function and implement the logic by yourself, you should be able to achieve that.
Admin Bundle: https://github.com/pimcore/admin-ui-classic-bundle/pull/472/files#diff-a766de56f4c567bb52ebb79d4a65e86ea496c006742b6b5a465e06ae4a104e9bR307-R312
Core Bundle: https://github.com/pimcore/pimcore/pull/16835/files#diff-214f01c1c5bb57516e182edb3c147c5be07eff7fe243c3229b491ad3eb445dd6R116-R135 or maybe its better to implement that in the checkValidity Function https://github.com/pimcore/pimcore/pull/16835/files#diff-fdf5ea53db66a5ec71cdc16ba799cd7d068b27e01ca83ea4f5544ca1087df07aR635
