### ISSUE TITLE
REST API : get data for object version

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#2959]
Hi,

Is it possible to add a route to retrieve data from a version with the REST API.
We have a client that needs to push the "published" object data but also the latest version to preview its products on an external system.

```
Method: GET
URL: http://YOUR-DOMAIN/webservice/rest/object/version/1234?apikey=[API-KEY]
Returns: JSON-encoded object data.
```

Cheers,

**Comment by brusch** [comment]
PRs will be accepted ;) (but please also for assets & documents to be consistent).

**Comment by romainp89** [comment]
Super ! :-)

**Comment by brusch** [comment]
Obsolete, see #6369
