### ISSUE TITLE
Folder Listing Breaks if there are a lot of objects in the folder

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#2964]
### Expected behavior 
  The Object Listing (in Folder) Must not break
### Actual behavior  
  Object Listing in folder breaks if 'all' option is selected in pagination toolbar and there are a no. of records in that folder.Sometimes it breaks at 1000 and sometimes at 5000 depending on the Grid Configuration.
### Steps to reproduce  
Open the Folder that has thousands of records.Select All option from the pagination toolbar provided at the bottom of Folder Listing.
![breaked grid](https://user-images.githubusercontent.com/21308144/41643498-f74c33a6-7488-11e8-97c3-6a046a5aaf8f.png)
![php error](https://user-images.githubusercontent.com/21308144/41643499-f77b61d0-7488-11e8-8286-3572fdc41a74.png)

**Comment by brusch** [comment]
That's why a paging is offered (memory limits on the client/server, ...) ... no way we can solve that, sorry.
