### ISSUE TITLE
[CSV Export] restrict AnyGetter to Pimcore Elements (Asset/Document/Object) and check user permission

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2965]

**Comment by fashxp** [comment]
as an alternative we would restrict the any getter to admins

**Comment by solverat** [comment]
@fashxp is there any explanation for that decision? 

We're (obviously we're the only one, it's in core almost a year) using the `anygetter operator` for our clients in almost every grid view. We can't just give them admin access just to display a grid properly (showing the name of a relation is a daily use case for example)

Maybe this should be restricted to the grid editor only?

**Comment by fashxp** [comment]
reason for that was security, because with the any-getter you could traverse to any data - even data you must not access due to permissions or internal data.

> Maybe this should be restricted to the grid editor only?

what do you mean with that?

**Comment by solverat** [comment]
>what do you mean with that?

Maybe we could disallow the anygetter inside the grid configuration view. so non-admins cannot add or modify them but should be able to view / export data.

**Comment by fashxp** [comment]
We could yes, but I'm not sure if this is possible consistently. 
And then admins still could configure something that other users must not see (and they might expect that the users don't see that). 
Probably we can add an additional flag to the configuration which says `Allow non-admin users to see getter result`. 

If you want to give it a try, go for it 👍
