### ISSUE TITLE
SVG flag-icons are not shown with proper size when configured as class icon

### ISSUE THREAD

**Issue by basgabrieljost** [pimcore/pimcore#2966]
### Expected behavior 
When I configure a SVG as icon for a class, it'll be resized to whatever size is available when the class icon is shown somewhere (e.g. in Data Objects tree).
  
### Actual behavior  
When I configure a SVG as icon for a class, it's **not** resized to whatever size is available when the class icon is shown somewhere (e.g. in Data Objects tree). This has the effect, that only a small part of the configured icon (SVG) is shown, which in case of country flags (see example below) results in single-coloured squares shown as class icons. 
  
### Steps to reproduce  

1. In https://demo-basic.pimcore.org/admin/ go to "Wheel-Main-Menu->Data Objects->Classes".
2. Select/open class "Inquiry".
3. For "Icon" property set ``/pimcore/static6/img/flags/countries/fr.svg`` (french flag).
4. Save class.
5. Refresh object tree in "Data Objects".
6. Open "inquiries" folder in object tree in "Data Objects".
7. See that there is a blue square shown as object icon for objects of type inquiry.

**Comment by basgabrieljost** [comment]
I've tested the functionality with four other (non-flag) SVG-icons and couldn't reproduce the problem with any of them. So it almost seems as if the SVGs are the problem here.

**Comment by brusch** [comment]
Flags are currently not intended to be used as class icons -> feature request.
