### ISSUE TITLE
http_auth with non-standard ports

### ISSUE THREAD

**Issue by etwasch** [pimcore/pimcore#297]
Zend/Auth/Adapter/Http.php throws an exception when a server is configured with a non-standard port. Because "Config key \'realm\' is required, and must contain only printable characters, excluding quotation marks and colons" which I assume is right. (line 201 etc.)

realm comes from Pimcore/Controller/Router/Route/Frontend.php line 109:
"realm" => $_SERVER["HTTP_HOST"]
gives "server:port" for non-standard ports on most servers.
$_SERVER["SERVER_NAME"] contains the server only, which would solve the issue.

**Comment by brusch** [comment]
Strip port in Pimcore\Tool::getHostname()
https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Tool.php#L329

use Pimcore\Tool::getHostname() instead
