### ISSUE TITLE
Pimcore install command doesn't allow empty password for MySQL.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2975]
We are scripting Pimcore installation for developement purpose.
This environment don't need to be secure and so to make life easier to developpers no password is set for mysql.

Problem is that the cli install command of Pimcore doesn't allow empty value:
https://github.com/pimcore/pimcore/blob/fad2751d4271803f655fff0286a7cb28a50d9886/pimcore/lib/Pimcore/Bundle/InstallBundle/Command/InstallCommand.php#L332

It would be nice to allow an empty mysql password (variable not set or set to nothing).

**Comment by brusch** [comment]
We'd accept a PR for that :)
