### ISSUE TITLE
Do not translate Custom Renderer Classes

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#2978]
Dynamic data should not get translated via the backend translator. It also will break the grid layout in backend translation grid view (reproducible in demo advanced):

![bildschirmfoto 2018-06-23 um 14 43 04](https://user-images.githubusercontent.com/700119/41809793-ccf10358-76f3-11e8-8755-60cbb461a5aa.png)

**Comment by weisswurstkanone** [comment]
build 269
