### ISSUE TITLE
Objects field is storing allowedClassId instead of reference

### ISSUE THREAD

**Issue by rliebi** [pimcore/pimcore#2980]
# Bug Report
- [x] This is not a security issue / vulnerability -> use [this form](https://pimcorehq.wufoo.com/forms/pimcore-security-report/) instead
- [x] Behavior is reproducible on http://demo-basic.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [x] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [x] There's no existing ticket for the same issue

### Expected behavior 
  When creating an 'Objects with Metadata' Field (Either in an Object or in a FieldCollection) the Property 'allowedClassId' should **not** be an integer value instead it should be a reference to the object. This is elemental if you use multiple environments in which the object keys could differ. The objectId's should rely only on the database and shall not be hardcoded.
### Actual behavior  
  After Creating a 'Objects with Metadata' Field the allowed object is referenced by its object id which can differ in each environment.
### Steps to reproduce  
-   Create an Object
-   Add an Object with Metadata
-   define 'Allowed Class' as an other Object
-   look up the definition Code (definition_<ObjectName>.php) and the first property is `'allowedClassId' => 6,` instead of `'allowedTypes' => 
            array (
              0 => 'features',
            ),` or `'allowedClass' => 
             'features',`

**Comment by weisswurstkanone** [comment]
Already fixed.
See https://github.com/pimcore/pimcore/issues/2515

**Comment by rliebi** [comment]
Oh perfect! Sorry for the dupe, I only checked the open issues.
