### ISSUE TITLE
Cannot Overrides \Pimcore\Model\Asset

### ISSUE THREAD

**Issue by SmashingQuasar** [pimcore/pimcore#2983]
Hello,

I want to use classes overrides. This works perfectly on \Pimcore\Model\Document\Page but doesn't seem to work on \Pimcore\Model\Asset.

I edited my config.yml and added the following:

`    models:
        class_overrides:
            'Pimcore\Model\Document\Page': 'AppBundle\Model\Document\Page'
            'Pimcore\Model\Asset': 'SenzoBundle\Model\Asset'
`

The first line works like a charm, the second one is totally ignored.

When I get an Asset and try to use the ->format() method, it triggers a Symfony exception.

I erased the cache after editing the config.yml file.

Here's the \SenzoBundle\Model\Asset class:

`
<?php

namespace SenzoBundle\Model;

use SenzoBundle\Tools\Debug;

class Asset extends \Pimcore\Model\Asset
{
    public function format()
    {
        Debug::Dump($this);
        
    }
}

?>

Here's the exception:

`Call to undefined method format in class Pimcore\Model\Asset\Image`

In the official documentation it is documented that \Pimcore\Model\Asset can be overriden but apparently something went south on the asset side.

If you need any information please let me know.
`

**Comment by dpfaffenbauer** [comment]
you need to override a specific subtype of asset. Like `Asset\Image` or `Asset\Archive`. It is not possible to override the class for the actual parent class.

**Comment by SmashingQuasar** [comment]
Couldn't this be an improvement?
It doesn't seem to be a technical issue considering you can override \Pimcore\Model\DataObject since you can override any implementation of \Pimcore\Model\AbstractObject.

We develop a lot of tools to make it easier to work with Pimcore here and we have great ideas to improve Pimcore DAO by developing noSQL implementation. This would be so much easier if we could override anything.

**Comment by dpfaffenbauer** [comment]
thats technically spoken not possible. If you want to override \Pimcore\Model\Asset, Pimcore would need to change the inheritance of Asset\Image, Asset\Folder, Asset\Archive, and so on. And they are statically inherited and therefore it is not possible for you to change that inheritance.

**Comment by SmashingQuasar** [comment]
I'm sorry I don't understand this. If you can override DataObject (since the documentation states you can override any implementation of AbstractObject, and DataObject is one), it isn't technically impossible considering DataObject is extended by all custom classes. You could also allow the extension of the existing classes like Model\Asset using Traits instead of classes. This wouldn't allow us to rewrite methods but at least we could implement new ones. I'm pretty sure there is no real technical difficulty here.

**Comment by SmashingQuasar** [comment]
We have developed a lot of tools around Pimcore to allow us to work faster.
Currently we create parent classes for each and every object class we create in the Back-office. We implement a custom format() method that will output an easily usable, standardized array. The main advantage of an array is avoiding fatal errors on multiple getters like $object->getPropertyA()->getSubPropertyB() which cannot be avoided without writing very long lines like !empty($object->getPropertyA()) && !empty($object->getPropertyA()->getSubPropertyB()) ? $pbject->getPropertyA()->getSubPropertyB() : ''. With an array you can make this much easier, not saying we need to reformat some objects for very complex projects.
In this case we wanted to implement a format() method in the Asset class to make our life so much easier working with Assets. To do this we will need to create a custom implementation of each Asset type which will be very time consuming.

This is especially handy because Pimcore tends to return inconsistent values like "null" on getting empty multi-href relations while it should output an empty array (which can seriously break your code). It also allows us to create specific representations of objects depending on the context to load data which cannot be retrieved through native PHP API (such as non-owner object relations).

Anyway, we will work around it as usual...
