### ISSUE TITLE
Problem saving objects with inherited mandatory attributes.

### ISSUE THREAD

**Issue by SEYentl** [pimcore/pimcore#2985]
### Expected behaviour
Mandatory localised fields can be saved & published with inherited values.

### Actual behavior  
Mandatory localised fields can't be saved & published with inherited values.
I have to manually adjust the title of the object before I can save.

### Steps to reproduce

On the online pimcore demo:
1. Adjust class definition for "news" -> make class inheritable and set localised title as mandatory.
2. Create a new news object and set a title. Save & publish this news object.
3. Create a new news object that inherits from the previous news object.
4. Save & publish this new news object.
5. Exception is thrown.

### Detailed exception
![screen shot 2018-06-25 at 15 52 12](https://user-images.githubusercontent.com/40569826/41854152-c52297de-788f-11e8-9860-ca03174467bc.png)

**Comment by vg-bgp** [comment]
This issue is still present in Pimcore 6.6.1.
Is there a plan to fix that or is the behaviour described in this issue expected behaviour?
