### ISSUE TITLE
Do not show "Old Password" field when using password reset link

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#2988]
### Expected behavior 
  User is not able to reset the password (in case user is not admin)
### Actual behavior  
  User must be able to reset the password.
### Steps to reproduce  
1.Click on 'Forgot password' link given on the login screen.

![click on forgot password link](https://user-images.githubusercontent.com/21308144/41914442-b62ed85a-7970-11e8-90a5-127241d95966.png)

2.Now enter your username.Please choose a user that is not admin as admin user can change password of any other user.

![enter username](https://user-images.githubusercontent.com/21308144/41914440-b5f72f72-7970-11e8-85f3-2da59b9c8aca.png)

If no email id is configured with that username , improper message is displayed.If the username entered by the user is incorrect then also the same message is displayed.Messages can be made some more relevant or informative.

![wrong message is displayed](https://user-images.githubusercontent.com/21308144/41914436-b51bcf5e-7970-11e8-9a66-8897d199272c.png)

3.Click on the link received in the mail.On clicking the link user gets logged in but no option is given to change the password.

![getlogged in if admin user no option to change password](https://user-images.githubusercontent.com/21308144/41914438-b58560b8-7970-11e8-876e-5172bf07a39b.png)

One can click on 'My Profile' option given in the settings but that too requires old password.So there is no option for the user to change the password.

![forget password_my profile](https://user-images.githubusercontent.com/21308144/41914439-b5bc98c6-7970-11e8-92a5-652d3cd31eca.jpg)

**Comment by brusch** [comment]
It was possible to reset the password by just leaving the field for the old password empty. 
But I agree, this is confusing, so the _Old password_ field is hidden now when coming from the reset password link. 

Thanks!

**Comment by neha04** [comment]
Thanks.
It would be great if error messages are made informative too.Both on forgot password screen and in user profile section.

While saving new password if password doesn't fulfil the password requirements 'Password wasn't changed because it isn't secure enough' is shown. The same error message is shown if the 'new password' and 'retype new password' entered by the user is not same.

**Comment by neha04** [comment]
Also on entering wrong password a success message is displayed along with the error message.Nothing is saved, but success message is still shown.

![success message](https://user-images.githubusercontent.com/21308144/42361952-b40e15b8-810e-11e8-9af6-b004f728a8c0.jpg)
