### ISSUE TITLE
Remove IE11 support

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#2989]

**Comment by julmot** [comment]
Why? In the industry, IE is still often the standard browser.

**Comment by brusch** [comment]
Don't worry, we haven't assigned this issue to a milestone yet :) 
This issue is primarily here for discussion and reference - but at some point this will definitely happen.

**Comment by solverat** [comment]
BTW: Login with latest IE11 does not work anymore (pimcore 5.4).

**Comment by brusch** [comment]
@solverat thanks, created a ticket for that #3283 
Maybe that's already a sign to get rid of it 😎

**Comment by brusch** [comment]
Official support will end in v6.
That doesn't mean that IE11 won't work anymore straight away (although a warning will be shown on login), but we cannot guarantee it anymore for the entire lifecycle of v6.
