### ISSUE TITLE
Cannot edit object relation in the grid view

### ISSUE THREAD

**Issue by camico** [pimcore/pimcore#2991]
# Bug Report

Editing an object relation from the grid view is only possible via 'Batch edit'.

### Expected behavior 
 
Clicking on a single object's "object relation field table cell" should open the popup to set or change or remove the relation. Analogous to e.g. 'href' and other fields.

### Actual behavior  

Nothing happens when clicking the table cell.
However, via 'Batch edit selected' an object relation can indeed be changed, also for single objects. Side note: When doing this for an object relation that already has one or more objects set, the popup contains nothing, and thus hitting 'Save' will immediately unset all objects.

**Comment by fashxp** [comment]
cannot be reproduced in latest version
