### ISSUE TITLE
Extended CSRF token validation BC break

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#2992]
'Extended CSRF token validation' commits break BC for bundles not implementing any CSRF feature from Pimcore:

This commit is responsible for this: https://github.com/pimcore/pimcore/commit/ef6fe655630ded3fffbe888dffab5b0ca0467d3d#diff-f26ed94c9be51d006e1a4b5b8ca97c67

**Comment by brusch** [comment]
Well, nothing really we can do about that ...

**Comment by brusch** [comment]
We're planning to exclude `GET` requests, but prior to that we have to check/change all existing requests that use `GET` instead of `POST`, `PUT` ...

**Comment by brusch** [comment]
I hope I can put that fixes in tomorrow, then we're able to remove the check for GET requests. I guess that would solve a lot of problems.
