### ISSUE TITLE
REST Webservice doesn't allow updating objects with image gallery

### ISSUE THREAD

**Issue by ppi-buck** [pimcore/pimcore#2993]
# Bug Report
Updating/Creating an object via the REST API seems to be bugged when the object contains an image gallery. If I make the values of the gallery empty it works and saves successfully. But it's missing the images of course.

Pieces of code that I found to have an impact are inside [ImageGallery](https://github.com/pimcore/pimcore/blob/master/pimcore/models/DataObject/ClassDefinition/Data/ImageGallery.php#L489). The `$idMapper` falls back to `null` if not passed. I managed to reproduce inside the demo where the object and definition should still be for now.
  
### Expected behavior 
POST an update to `http://mydomain.de/webservice/rest/object?apikey=[APIKEY]` including images for an image gallery should be succesful.
  
### Actual behavior  
The response success is `false` with error message: `Call to a member function getMappedId() on null` 
  
### Steps to reproduce  
1. Create a very simple object definition that has an image gallery
1. Create an object of that type and fill the gallery in pimcore backend
1. GET the object via REST API
1. try to POST an update back to the object by sending the gotten `data` as body.
  
#### GET response
https://demo-basic.pimcore.org/webservice/rest/object?apikey=[APIKEY]
```json
{
  "success": true,
  "data": {
    "path": "/test/",
    "creationDate": 1530169608,
    "modificationDate": 1530169615,
    "userModification": 4,
    "childs": null,
    "elements": [
      {
        "type": "imageGallery",
        "value": [
          {
            "image__image": 4,
            "image__hotspots": {
              "hotspots": [],
              "marker": [],
              "crop": null
            }
          }
        ],
        "name": "test",
        "language": null
      }
    ],
    "className": "test",
    "id": 53,
    "parentId": 52,
    "key": "test",
    "published": true,
    "type": "object",
    "userOwner": 4,
    "properties": null,
    "notes": [],
    "index": null
  }
}
```  
#### POST request body
https://demo-basic.pimcore.org/webservice/rest/object?apikey=[APIKEY]
```json
{
  "path": "/test/",
  "creationDate": 1530169608,
  "modificationDate": 1530169615,
  "userModification": 4,
  "childs": null,
  "elements": [
    {
      "type": "imageGallery",
      "value": [
        {
          "image__image": 4,
          "image__hotspots": {
            "hotspots": [],
            "marker": [],
            "crop": null
          }
        }
      ],
      "name": "test",
      "language": null
    }
  ],
  "className": "test",
  "id": 53,
  "parentId": 52,
  "key": "test",
  "published": true,
  "type": "object",
  "userOwner": 4,
  "properties": null,
  "notes": [],
  "index": null
}
```

#### POST response
```json
{
  "success": false,
  "msg": "Call to a member function getMappedId() on null"
}
```

**Comment by weisswurstkanone** [comment]
fixed in build 270
