### ISSUE TITLE
Performance issue with localized related objects.

### ISSUE THREAD

**Issue by ascheider** [pimcore/pimcore#2998]
## Feature description 
  
Localized related objects in pimcore are currently not lazy loaded.
This leads to the performance problems and timeouts in the backend.
How to reproduce:
1. Create object class with localized relation to some another object.
2. Create a object tree with 10 children.
3. Assign to each children 100 different objects.
4. Reload backend and try to open object tree.
Pimcore will made more than 1000 database queries to load each category and related children.

How to solve issue:
1. Lazy load localized filelds
2. Optimize loading of related objects with single database query and create paging with limit for related objects.

**Comment by brusch** [comment]
Closed in favor of #3736
