### ISSUE TITLE
disable video providers in video editable

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#2999]
# Feature Request 

## Feature description 

It would be great if there was an way to configure the video providers for the video editable. At the moment you can select between an asset, youtube, vimeo and dailymotion. I want to disable dailymotion and vimeo so that only an asset or youtube video can be selected.

**Comment by timwiechers** [comment]
I would suggest to pass the allowed types in Twig for each Editable.
Like so: 
`{{ pimcore_video('video1', {
                width: 700,
                height: 400,
                allowedTypes: ['asset', 'youtube']
            })
        }}`

I would ignore configuration for a non-allowed type.
`allowedTypes: ['asset', 'youtube'],
                vimeo: {
                    autoplay: true,
                }`

I am happy to create a PR for this issue if there are no concerns about this approach.

**Comment by dvesh3** [comment]
> I am happy to create a PR for this issue if there are no concerns about this approach.

@timwiechers Sounds good to me. please go ahead with the PR 👍 thanks!

**Comment by passioneight** [comment]
@timwiechers how do you intend to handle the use case where no `allowedTypes` are set?

**Comment by timwiechers** [comment]
@passioneight i would suggest if the option is not set or the content is empty, all available options are displayed.

**Comment by passioneight** [comment]
@timwiechers sounds good!
