### ISSUE TITLE
"Appearance & Branding" Settings does not applies to "Forgot Password Screen"

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#3000]
### Expected behavior 
  "Appearance & Branding" Settings must be applied to "Forgot Password Screen"
### Actual behavior  
  "Appearance & Branding" Settings does not applies to "Forgot Password Screen"
### Steps to reproduce  
1.Change The color for login screen in "Appearance & Branding" option in system settings.

![change settings](https://user-images.githubusercontent.com/21308144/42078097-d4a70440-7b98-11e8-814f-d8d9aff34ec4.png)

2.Now go to login screen .The new color is applied on login screen.

![applied on login](https://user-images.githubusercontent.com/21308144/42078098-d4d13918-7b98-11e8-9824-d7d821131673.png)

3.Click Forgot password link.Here color is not changed.Either the same login color must be applied to this forgot password Screen or new settings must be there for this screen.

![not applied on forgot password](https://user-images.githubusercontent.com/21308144/42078096-d47a2628-7b98-11e8-903e-03196ff0e7e7.png)

**Comment by brusch** [comment]
Was fixed already as part of #2918
