### ISSUE TITLE
[Custom Reports] Better titles in charts

### ISSUE THREAD

**Issue by jansarmir** [pimcore/pimcore#3005]
**Bar chart**
- chart uses titles like "ext-chart-series-bar-*", better would be Label from configuration or column name
- for displaying more then 1 column, combined type would be better, now they are placed over, so only one bar is vissible

**Line chart**
- chart uses column names, better would be Label from configuration, is exists

**Comment by fashxp** [comment]
PRs are welcome :)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
