### ISSUE TITLE
Can not create new Classes - MySQL Syntax Error

### ISSUE THREAD

**Issue by ppi-buck** [pimcore/pimcore#3006]
# Bug Report

### Expected behavior 
By clicking the "Add" button in **DataObjects > Classes** a new class definitions can be added.
  
### Actual behavior  
After clicking the mentioned button Pimcore throws an error: 
```php
Status: 500 | Internal Server Error
URL: /admin/class/suggest-class-identifier
Message: An exception occurred while executing 'select max(cast(`id` as int)) from classes;':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'int)) from classes' at line 1
``` 
  
### Steps to reproduce 
1. Have newest build (270 - possibly also earlier builds as I updated from stable 5.2.3)
1. Try adding a new class in DataObjects > Classes

### Comments
It seems like this commit introduced a new method that contains the error https://github.com/pimcore/pimcore/commit/d81d52d3c556cdf3dc74a91f3883cb37564415df. 

The line of code that causes the error to throw is this one https://github.com/pimcore/pimcore/blob/d0c424ab324b9849e0917c3da20b6fcaae15e84e/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/ClassController.php#L1514 

In my understanding the MySQL syntax is wrong: see allowed types at bottom of https://dev.mysql.com/doc/refman/5.7/en/cast-functions.html#function_cast 
There is no type of **int** there.

### Possible fix
When testing in MySQL both these variants work:
```mysql
 SELECT MAX(CAST(id AS SIGNED)) FROM classes;
 SELECT MAX(CAST(id AS UNSIGNED)) FROM classes;
```
Also changing the line mentioned above to either one of the showed variants works for me.
  

### Side note
The unique class identifier is now editable - should I only use INT values here as the GUI suggests?

**Comment by weisswurstkanone** [comment]
thx.

build 271

**Comment by ppi-buck** [comment]
You're welcome!

Can I use strings as unique identifiers now? Looks like it to me...
Cheers

**Comment by weisswurstkanone** [comment]
yes, definitely. but be careful regarding the length of the table names.

**Comment by ppi-buck** [comment]
Okay, awesome! 
Thanks for the quick fix

**Comment by ppi-buck** [comment]
_Maybe this is related and you need to re-open this or reference it in another issue_

When creating a new class with an unique identifier other than the interger one that is already in there at the start of the creation process it fails like shown in the screenshots below.

1. Create a Class with unique identifier of a string "test"
![screenshot from 2018-07-02 12-57-21](https://user-images.githubusercontent.com/37330764/42160644-3d74661e-7df8-11e8-92f9-313575102962.png)

1. Error message thrown after hitting "Ok"
![screenshot from 2018-07-02 12-57-58](https://user-images.githubusercontent.com/37330764/42160647-3febcc98-7df8-11e8-872f-14774eae9f13.png)

1. Next open ID is used in parentheses and the class definition rather than the string "test".
![screenshot from 2018-07-02 12-59-01](https://user-images.githubusercontent.com/37330764/42160655-4e238fee-7df8-11e8-8d6c-8c8943c487b4.png)
![screenshot from 2018-07-02 12-59-28](https://user-images.githubusercontent.com/37330764/42160668-5f9a91dc-7df8-11e8-8707-b7631d68b559.png)

1. deleting this new class again also causes an error since the table doesn't exist inside the DB.
![screenshot from 2018-07-02 13-02-50](https://user-images.githubusercontent.com/37330764/42160818-e6c153c6-7df8-11e8-81f2-6d5ccf154f6f.png)


## Observations
* When using the pre-calculated numeric ID it works fine.
* When using another numeric ID it works fine

**Comment by ppi-buck** [comment]
Sorry to ping you again @weisswurstkanone  but the above https://github.com/pimcore/pimcore/issues/3006#issuecomment-401770281 still persists in build 273.

**Comment by weisswurstkanone** [comment]
Unable to reproduce. Maybe I am missing an important step here?

**Comment by ppi-buck** [comment]
You're right I cannot reproduce it in the demo neither.

That's super weird as I have the same version/build ... Good to know that's not an issue with your code. Bad to know that I have to do some digging now ;-) 

Thanks!
