### ISSUE TITLE
Maximum call stack size exceeded in chrome on object sorting

### ISSUE THREAD

**Issue by ascheider** [pimcore/pimcore#3009]
### Expected behavior 
  Sort assigned objects
### Actual behavior  
  Sort assigned objects, browser freeze
### Steps to reproduce  
Open object with id 1594Product on https://demo-advanced.pimcore.org/admin/?_dc=1530534255 got to base data, sort Features list multiple times. Browser freeze with message "Maximum call stack size exceeded" in Dev Tools.
Video: https://drive.google.com/file/d/1rUe_dGuHLuY8x_MBTwOrY61uVE3TLSqm/view

Browser Version: Version 67.0.3396.99 (Offizieller Build) (64-Bit) Mac OS

**Comment by brusch** [comment]
@ascheider is this still an issue in Pimcore X?

**Comment by ascheider** [comment]
@brusch i think not anymore. could not reproduce withe the current version. I guess you can close the issue

**Comment by brusch** [comment]
@ascheider alright, thanks for your feedback!
