### ISSUE TITLE
[Website Settings] missing @method annotations 

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#3011]
# Bug Report  
### Expected behavior 
  Modify website settings by calling save() function as described in the docs: https://pimcore.com/docs/5.x/Development_Documentation/Tools_and_Features/Website_Settings.html
### Actual behavior  
  save() function does not exist in \Pimcore\Model\WebsiteSetting
### Steps to reproduce  
  Run Code from docs
### Code example 
  Code from docs

**Comment by brusch** [comment]
The code in the docs works, but there were some `@method` annotations missing on the class.
