### ISSUE TITLE
Field definition for localized fields is incorrectly builded

### ISSUE THREAD

**Issue by mbolka** [pimcore/pimcore#3015]
# Bug Report
Fields definitions are built incorrectly for class with multiple localized fields nodes.
  
### Expected behavior 
When a user created definition with multiple localized fields nodes and multiple fields under them, all of those fields are available through $object->getClass()->getFieldDefinition('localizedfields');
### Actual behavior  
  Only attributes from a first localizedfields node are available through getFieldDefinition() method.
### Steps to reproduce  
  1. Create class definition with multiple localizedfields nodes and multiple attributes underneath them.
  2. Create object of this class and fill it with data.
  3. Execute this method:
```php
$attributes = $object->getClass()->getFieldDefinition('localizedfields')->childs;
print_r($attributes);
```

**Comment by brusch** [comment]
They are referenced here: 
https://github.com/pimcore/pimcore/blob/f625174bcdff644cb2ccc57fed8d20cab8542559/pimcore/models/DataObject/ClassDefinition/Data/Localizedfields.php#L98
