### ISSUE TITLE
Ecommerce pricing manager refactoring (#2823) breaks loading of read only marked carts

### ISSUE THREAD

**Issue by deltatag** [pimcore/pimcore#3019]
Change of function **setCount($count)** in https://github.com/pimcore/pimcore/commit/d84d3cf94223a8cf55861a0d68956df126e1b6c5#diff-bff0ed738d7a32697ae9bbd8afec7ef7 prevents loading of read only marked carts (because of setting the modification timestamp) and breaks further handling due to following function returns null on exception for cart items:

https://github.com/pimcore/pimcore/blob/72f085add4f632f1b90c7b06ceb5089e9a6674a1/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/CartManager/CartItem.php#L63

I would suggest checking if $this->count is null before comparing.

**Comment by fashxp** [comment]
see also https://github.com/pimcore/pimcore/issues/3080
