### ISSUE TITLE
Objectbrick Grouping

### ISSUE THREAD

**Issue by psuhane** [pimcore/pimcore#3027]
# Improvement

Pimcore has a good feature in classes to group them. It would be great if the same feature will be available with Objectbrick. If system has large number of objectbrick then it will be easier to organize them in groups. Please refer attached screen

![group](https://user-images.githubusercontent.com/12061880/42362738-453e1238-8112-11e8-9857-2688c669b3f2.png)

Also grouped objectbricks should be available while associating with object. Please refer following screen

![group1](https://user-images.githubusercontent.com/12061880/42363119-db6f7b6a-8113-11e8-8652-efce6247104b.png)

**Comment by weisswurstkanone** [comment]
build 282
