### ISSUE TITLE
[Objects] Objectbrick UI Optimizations + Title

### ISSUE THREAD

**Issue by psuhane** [pimcore/pimcore#3029]
# Improvement

It would be good if label(title) field available on objectbrick. And label should be displayed while choosing a objectbrick and in the associated objectbrick. 

Please refer following screens

![label1](https://user-images.githubusercontent.com/12061880/42365018-e5d60306-811a-11e8-8468-03b013752210.png)

![label2](https://user-images.githubusercontent.com/12061880/42364919-80c62126-811a-11e8-8a7d-1852332d5264.png)

**Comment by weisswurstkanone** [comment]
build 275

**Comment by psuhane** [comment]
Thanks for quick fix @weisswurstkanone :)

I think, in case of objectbrick title(in right position) is not required. While adding a objectbrick title already displaying on tab. Please refer following screen


![bi](https://user-images.githubusercontent.com/12061880/42407385-f4cbe7e0-81d8-11e8-8b14-28ae0a454eb0.png)

**Comment by brusch** [comment]
I think we can even further improve the editing interface for Object Bricks by removing the entire top toolbar with the delete button and the title which can be replaced by a closable tab. 

![image](https://user-images.githubusercontent.com/142037/42417401-87fe8d32-8289-11e8-9154-62c6fc2b18c5.png)
