### ISSUE TITLE
Fieldcollection title(label)

### ISSUE THREAD

**Issue by psuhane** [pimcore/pimcore#3030]
# Improvement

It would be good if label(title) field available on Fieldcollection. And label should be displayed while choosing a Fieldcollection and in the associated Fieldcollection. 

Please refer following screens

![fc_l1](https://user-images.githubusercontent.com/12061880/42365958-8d6cdd7c-811d-11e8-9b46-ad39d8b86099.png)

![fc_l2](https://user-images.githubusercontent.com/12061880/42365968-933b9446-811d-11e8-8cfc-668a89107947.png)

**Comment by weisswurstkanone** [comment]
build 275

**Comment by psuhane** [comment]
Thanks @weisswurstkanone :)

I think, on the right position objectbrick's title should be displayed not it's key. Please refer attached screen

![fi](https://user-images.githubusercontent.com/12061880/42407441-4e07df66-81da-11e8-8341-f7747fb64f46.png)

**Comment by amarjeet6694** [comment]
**Title of Field collection is not updated**

I created a field collection **sampleCollection** and **sampleCollectionNew** with title **Description Collection** and **Others**.
But once I use that field collection in the object, neither the title is showing in the drop down of the field collection nor the title is updated on the right.

![screenshot--2018-07-12-18-12-20](https://user-images.githubusercontent.com/29056383/42633816-39fc5ec4-85ff-11e8-8a02-bba5a121aa4f.png)


But once the reload the object, the right title or label is updated

**Comment by weisswurstkanone** [comment]
Probably a side effect of #3028
