### ISSUE TITLE
Object grid filters on all relation fields

### ISSUE THREAD

**Issue by psuhane** [pimcore/pimcore#3031]
# Improvement

It would be great if in object grid have filters available for all the relation fields - Object relation, Object with metadata, Href, Multi-href, Multi-href advanced. The same interface can be used that is being used for Batch Update in object grid, in addition to that if AND/OR operator can be handled. Please refer following screen

![relation](https://user-images.githubusercontent.com/12061880/42368753-84decc1c-8125-11e8-91d8-6f3390a66a89.png)

**Comment by BlackbitNeueMedien** [comment]
For this we need to implement an own filter type (based on https://docs.sencha.com/extjs/6.2.1/classic/Ext.grid.filters.filter.Base.html) which opens the field layout in a modal window (as batch editing does). ExtJS does not provide an "action filter" or anything like that.

**Comment by fashxp** [comment]
duplicate of #699
