### ISSUE TITLE
Task management within Pimcore

### ISSUE THREAD

**Issue by psuhane** [pimcore/pimcore#3033]
# New Feature Request

Wherever we implement workflow, customer also ask for task management. This is the most wanted feature in Pimcore. Following are few points for the basic tasks management

* Create new task. Sample fields for tasks
    * Subject
    * Due Date
    * Description
    * Priority - High, Normal, Low
    * Status - Not started, In Progress, Completed
    * Start Date
    * Completion Date
    * Associated element - object, document, asset

* Task Reminder Settings
* Task Reminder Notification
* Dashboard portlets for tasks - e.g. Pending tasks, Top 10 high priority tasks
* Delete tasks
* Move to archive

Tasks can be assigned to users on different workflow events. This is very basic task management feature request and can be start with this. In future, functionality can be enriched e.g. assign task to any other user, comments, subtasks, attachments etc.

**Comment by dpfaffenbauer** [comment]
I also have the use-case for something like this. I would have implemented a Plugin for that. But if pimcore plans to do that in the core, that would be amazing as well.

**Comment by brusch** [comment]
A plugin sounds the better choice for me, for the following reasons: 
- The functionality doesn't need a tight integration into the core
- Many organizations have existing tools for that
- There are a lot of tools doing a great job for managing tasks

**Comment by brusch** [comment]
I'll close this issue for now, but discussion can continue :)

**Comment by psuhane** [comment]
Thanks @brusch, then we'll create a plugin for this :)
