### ISSUE TITLE
[TWIG] Editables in view/edit template of Brick cause a redefinition

### ISSUE THREAD

**Issue by ramundomario** [pimcore/pimcore#3043]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [X] This is not a security issue / vulnerability -> use [this form](https://pimcorehq.wufoo.com/forms/pimcore-security-report/) instead
- [X] Behavior is reproducible on http://demo-basic.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [X] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [X] There's no existing ticket for the same issue
- [X] Remove unused sections from below and this bullet points

### Expected behavior 
**1. Create a brick which has edit template [PHP]:**
![test-php](https://user-images.githubusercontent.com/16133208/42441429-75beb90a-8368-11e8-8ce6-e5aea377d5f3.PNG)

**2. Create view/edit template [PHP]:**
![view php](https://user-images.githubusercontent.com/16133208/42441514-a66f84ee-8368-11e8-9805-c98e671e80ef.PNG)
![edit php](https://user-images.githubusercontent.com/16133208/42441515-a7f54e8e-8368-11e8-809b-76e279cf2ce0.PNG)

**3. Print and allow edit of input editable 'title' in edit template [PHP]:**
![edit-php](https://user-images.githubusercontent.com/16133208/42441768-4148e956-8369-11e8-81f2-5ae5114a6db6.png)

**4. Print and not allow edit of input editable 'title' in view template [PHP]:**
![view-php](https://user-images.githubusercontent.com/16133208/42441795-50e4bce6-8369-11e8-97b1-222734380f0e.png)

### Actual behavior / Steps to reproduce  

**1. Create a brick which has edit template [TWIG]:**
![test-twig](https://user-images.githubusercontent.com/16133208/42441094-b8aa1800-8367-11e8-8a1b-13aed65d465d.PNG)

**2. Create view/edit template [TWIG]:**
![view twig](https://user-images.githubusercontent.com/16133208/42441184-f86b1c14-8367-11e8-8b05-474d0a484a61.PNG)
![edit twig](https://user-images.githubusercontent.com/16133208/42441186-fa7f53bc-8367-11e8-94e3-5ec7582f7e33.PNG)

**3. Redefinition of input editable 'title' in view template [TWIG]:**
![view-edit-twig-1](https://user-images.githubusercontent.com/16133208/42441311-217da31a-8368-11e8-8149-0e168e4bf006.png)
![view-edit-twig-2](https://user-images.githubusercontent.com/16133208/42441316-23506056-8368-11e8-8d22-1875e234d941.png)

# Feature Request 
## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [X] There is no existing issue regarding the same topic

## Feature description 
I created a simple example of the problem, for most of the editable can be resolved using the getXXX method in view template, but I can't loop the Block editable for retrieve data because there is no method that makes available the unsaved & published loop elements.

**Comment by ramundomario** [comment]
No update regarding this problem? Thanks

**Comment by brusch** [comment]
@ramundomario no

**Comment by ramundomario** [comment]
Ok, are there alternatives way for get editmode data from Block?
