### ISSUE TITLE
Image toolbar gets cropped on decreasing the image width

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#3045]
### Expected behavior 
  Image toolbar must not get cropped on decreasing the image width
### Actual behavior  
  Image toolbar gets cropped on decreasing the image width
### Steps to reproduce  
  1.Add an image in class 

Before reducing the width..

![posterimage_before width change](https://user-images.githubusercontent.com/21308144/42442778-39415a3e-8389-11e8-88b9-06a429b21cc8.jpg)

2.Now reduce the width of the image

![chnge width](https://user-images.githubusercontent.com/21308144/42442804-50543da4-8389-11e8-8251-0dd5bc01384d.jpg)

3.Reload the object .Image toolbar gets cropped.This happens with both image and advanced image type.

![icons disappear](https://user-images.githubusercontent.com/21308144/42442845-6cf131e2-8389-11e8-9bb6-3342d01c6050.jpg)

**Comment by weisswurstkanone** [comment]
overflow menu: 
![image](https://user-images.githubusercontent.com/6142086/42444730-1499d868-8371-11e8-8e4c-249a416c39bb.png)

build 277

**Comment by neha04** [comment]
Thanks @weisswurstkanone  

It would be  great if same will be implemented for advanced image as well...
Same issue there as well..

**Comment by weisswurstkanone** [comment]
done
