### ISSUE TITLE
Custom layout is not working as expected

### ISSUE THREAD

**Issue by AmitThakur23** [pimcore/pimcore#3046]
# Bug Report

A new user is created and custom layout is linked to it. When user opens the object layout is not implemented although when object is refreshed then custom layout is applied 
  
**Expected behavior** 
linked custom layout should display when object is opened
  
 **Actual behavior**  
  Custom layout is not applied, user needs to reload the object in order to see the layout implemented

**Steps to reproduce**  
  1) Create a custom layout "Sample Layout", add few attributes and then save it.

![sample layout for blogarticle class](https://user-images.githubusercontent.com/29056713/42443909-67bd54fa-838c-11e8-9b5b-ca7bfdea65fb.png)

 2) Create a new user.

![demo user creation](https://user-images.githubusercontent.com/29056713/42443966-8e6dc7ba-838c-11e8-9728-385004bb92e2.png)

  3) Attach the custom layout to the user work space

![applying sample layout to demo user](https://user-images.githubusercontent.com/29056713/42443984-9d47b840-838c-11e8-8b61-54003ab3ab13.png)

  4) Login with the new user.
  5) Open the respective object.
  6)  layout is not applied.

![layout not applied](https://user-images.githubusercontent.com/29056713/42444000-a78f5312-838c-11e8-97af-fac7780dc0d5.png)

  7) Reload the object, now the custom layout is applied.

![layout applied after reloading the object](https://user-images.githubusercontent.com/29056713/42444011-add9f1d2-838c-11e8-85d4-16cbe87af9aa.png)

**Comment by brainsbucket** [comment]
+1

**Comment by weisswurstkanone** [comment]
fixed in build 280

**Comment by brainsbucket** [comment]
@weisswurstkanone Thanks it work
