### ISSUE TITLE
Image thumbnails not build because of HHVM_VERSION check

### ISSUE THREAD

**Issue by strati1991** [pimcore/pimcore#3048]
### Expected behavior 
The command bin/console pimcore:thumbnails:image runs correctly when not running pimcore on HHVM.
### Actual behavior  
The command bin/console pimcore:thumbnails:image throws for each thumbnail the error "ImagickException: unable to open image" and generates just an svg placeholder.
### Steps to reproduce  
 Run bin/console pimcore:thumbnails:image in the a pimcore root directory without HHVM.
# Feature Request 
Find a solution by correcting the lines 106 - 108 in pimcore/lib/Pimcore/Image/Adapter/Imagick.php

**Comment by brusch** [comment]
This check was already removed, please have a look at the latest version of 
https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Image/Adapter/Imagick.php#L109 

Please try again using the latest version of `Imagick.php` (or update to the latest build).
