### ISSUE TITLE
href within a block is not respecting 'Label Width'

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#3052]
Repreducable on the latest demo - see example below.

Create Class with the following:
Panel (set labelWidth here) -> block -> href
The href is using a fixed Label Width of 100px and not the one defined on the parent panel.

![image](https://user-images.githubusercontent.com/7206334/42452918-97e58536-838b-11e8-9247-2b6adca75e64.png)

![image](https://user-images.githubusercontent.com/7206334/42452926-9f1331d2-838b-11e8-8f24-335e8cdbae2a.png)

**Comment by weisswurstkanone** [comment]
build 278

**Comment by ultramegatom** [comment]
that was fast. thx :)
