### ISSUE TITLE
ExtJS 6 - Google analytics settings are not saved

### ISSUE THREAD

**Issue by maff** [pimcore/pimcore#306]
When in ExtJS 6 mode, saving Report Settings (e.g. adding a Google Analytics ID) results in an empty `reports.xml`. Seen on a fresh Pimcore installation from composer/dev-master. The data JSON sent to `/admin/reports/settings/save` is empty - resulting in an empty `Zend_Config` XML file. Works in ExtJS 3 mode. Resulting XML file:

```xml
<?xml version="1.0"?>
<zend-config xmlns:zf="http://framework.zend.com/xml/zend-config-xml/1.0/"/>
```

**Comment by weisswurstkanone** [comment]
build 3569
