### ISSUE TITLE
Admin - Undefined asset

### ISSUE THREAD

**Issue by jansarmir** [pimcore/pimcore#3062]
i have critical errors from administration (current 5.2.3)

/admin/asset/get-image-thumbnail?id=**undefined**&width=360&height=310&contain=true

Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError:
"**Call to a member function isAllowed() on null**" at */pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/AssetController.php line 1152
*/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151 */vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68
*/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:202
*/web/app.php:55

i tried to find the problem for long time, but no progress
i thing it happens, when i have opened administration and suspend computer, and come back to administration, sometimes this error happens

any ideas or hints how to solve this?

**Comment by brusch** [comment]
Not, really, we'd need a reproducible case to tackle this issue :( 
I'll close this issue for now. If you have any further information on that, please come back on this issue. 
Thank you very much!

**Comment by eliasfellner** [comment]
Hey Berni,

i found a way of reproducing this issue. :)

Set up a Class with:
- an "Image Advanced" Component in it
- set that Component to "Not editable"

Now create an Object of that Class.
You'll get the Error mentioned above "Call to a member function isAllowed() on null" 

The same thing doesn't happen for normal Images.

So Pimcore always wants to display the Thumbnail of Advanced Images (when they're not editable), without checking if there is one. :)

@brusch
