### ISSUE TITLE
GraphQL Support

### ISSUE THREAD

**Issue by julmot** [pimcore/pimcore#3065]
I'm currently looking at Pimcore for a decoupled frontend application, usually with React. Until now (with other systems) I've been using GraphQL instead of REST APIs to avoid multiple API calls and only transfer data that I actually need.

Beside of the fact that I don't know if the [documented REST API of Pimcore](https://pimcore.com/docs/master/Development_Documentation/Web_Services/index.html) was built for decoupled applications, I haven't found anything about GraphQL.

Therefore, please take this issue as feature request.

**Comment by cgpro** [comment]
+1

**Comment by cgpro** [comment]
Would be very nice for GatsbyJS :)

**Comment by milanbolland** [comment]
That would be awesome!

**Comment by ApolloLV** [comment]
This feature would be very helpful for an application we are currently building, please consider implementing a GraphQL interface.

**Comment by brusch** [comment]
I think that would be quite easy to provide as an additional bundle. Anyone willing to contribute?

**Comment by mingfang** [comment]
The doc here https://pimcore.com/docs/5.x/Development_Documentation/Web_Services/index.html states 
```Important: Frontend Applications
The Pimcore REST API is not intended to be used as a data provider for frontend applications (Vue.js, React, Angular, ...), please build your own actions for that purpose or use any existing bundles.```

Has that changed?
If not then is the proposed GraphQL intended for frontend applications?

**Comment by brusch** [comment]
No that hasn't changed, this was already always the case, but obviously not communicated explicitly enough. 

GraphQL is designed for frontend applications, yes.

**Comment by brusch** [comment]
@julmot that building custom REST endpoints is very easy

**Comment by julmot** [comment]
@brusch Thanks for this clarification 👍  I'm looking forward to this feature. If you need any help from a front-end side, you can let me know.

**Comment by ThisIsRuddy** [comment]
❤️

**Comment by brusch** [comment]
UI idea 

![20181030_154133](https://user-images.githubusercontent.com/142037/47726349-9765d200-dc5a-11e8-8476-d033757b3b50.jpg)

**Comment by brusch** [comment]
@not4fame thank you very much for the hint! 
Currently we're just evaluating if we should go with [API Platform](https://api-platform.com/) or directly with [Webonyx](https://github.com/webonyx/graphql-php) (which is used by API Platform as well).

**Comment by dpfaffenbauer** [comment]
API-Platform 👍

**Comment by not4fame** [comment]
I'm not quite familiar with  API Platform , it looks for me a little bit like overklill (just first impression, it can change), espesially that, in my opinion, our only (except validation, and permissions, which are totally different topics) task, is to map class definitions to correct graphQl schema. Thank You for Your feedback, I will dig more in to the API platform, to have better understanding of it.

**Comment by dpfaffenbauer** [comment]
The thing about API-Platform is: it gives you complete freedom over the API you wanna use. Either XML or JSON Responses and you could also finally extend Pimcore's API with custom API's which is currently not really possible (I mean, sure it is, but tricky).

And it also generates nice looking and usable API-Docs.

**Comment by dkarlovi** [comment]
Hello,

I'm a long time API Platform user (there wasn't even a 2.x branch yet when I started) and a rather recent Pimcore user.

I'd like to weigh in here: having API Platform as your outward layer would mean the end user (ie. the developer) would be in full control over the behavior the API has, which is of course very handy.

But also, this means all the benefits API Platform provides are automatically available to Pimcore users.

These are only some of the things APIP gained after I started using it and, by extension, now have access to:

- [GraphQL support](https://api-platform.com/docs/core/graphql/)
- Swagger UI 3.x, automatic documentation generator
- UUID support for all your primary keys (if so desired)
- [innumerable performance improvements](https://dunglas.fr/2018/07/api-platform-2-3-major-perf-improvement-api-evolution-deprecation-better-dev-tools-and-much-more/)
- support for [real-time API communication with Mercure](https://medium.com/@dunglas/http-2-speed-up-your-apps-and-dispatch-real-time-updates-symfony-and-api-platforms-features-76fdc5bf6339)
- support for [HTTP/2 server push and preloading](https://dunglas.fr/2017/10/symfony-4-http2-push-and-preloading/)

This means **Pimcore core team could focus their effort on building Pimcore and not infrastructure** supporting it. If you're planning to stay on PHP, API Platform is probably the best API framework available, not just for Symfony.

**Comment by dkarlovi** [comment]
BTW the HTTP/2 + push thing basically makes GraphQL not needed since it allows the server to just push all the required data as separate responses while still keeping all the data cacheable.

**Comment by dkarlovi** [comment]
@julmot GraphQL is not without issues and some problems it solves are more easily solved by something else:

> not make multiple requests necessary

This is done by HTTP2+push too:
1. you create the first request `GET /foo`
2. server responds with a list, saying you need to `GET /foo/1`, `GET /foo/2`, `GET /foo/3`
3. but then, it actually sends you those too, as if you've requested them yourself

This allows the app to respond N times for a single request, getting pretty much the same effect, only way better since each additional response can be cached at any level. This means you no longer need to fetch `GET /foo/2` again when you click on a link in the listing, you already have it.

> reduce data transmission by only responding the actually requested data

GraphQL wins here, **for the first request**. On average, you transfer less data with the approach described above since it transfers more data per requests, but does less requests overall (since most of them can be cached by you, the server and everything between).

> reducing development complexity by directly responding in the specified schema

This is also debatable. I feel GraphQL is like old "no SQL" databases: it's easier to not have any structure which allows you to build your **current** requirement, but as you add additional requirements, the app at your end gets ever so complex and it turns out the structure actually had some desiredable attributes you wish you had right now. :+1:

This and more is described in a series of articles called [You Might Not Need GraphQL](https://philsturgeon.uk/api/2017/04/18/you-might-not-need-graphql/).

**Comment by dpfaffenbauer** [comment]
I agree with @dkarlovi, thats why I also think Pimcore should implement API Platform and not GraphQL directly. That way GraphQL is implemented in a more abstracted way and could be swapped out with a new trendy thing in a few years.

**Comment by not4fame** [comment]
Hi, guys, I agree that API Platform is a great tool, but in my opinion, without changing DataObjects to use Doctrine it doesn't make too much sense to use it with them. I think it is a great discussion and we should continue with it, but we can also do that:
![graphql](https://user-images.githubusercontent.com/31779190/49645904-c6bbeb80-fa1d-11e8-98ae-7c71ca016a3c.gif)

**Comment by weisswurstkanone** [comment]
Early preview available at:
https://github.com/pimcore/data-hub

Short & basic introduction:
https://github.com/pimcore/data-hub/blob/master/doc/img/graphql/intro.mp4

**Comment by dpfaffenbauer** [comment]
Ok. first find: DON'T USE `Pimcore::getContainer`. Accessing the Container directly is a anti-pattern and will break most of the times for Symfony > 4.0. This is a completely new bundle and I don't see any point why it has to do that!

BTW: Would have opened an issue on the github page for the package, but issues have been disabled.

**Comment by dpfaffenbauer** [comment]
PS: There are 40 usages of that!

**Comment by brusch** [comment]
@dpfaffenbauer PRs are open 😉

**Comment by brusch** [comment]
Further development happens at https://github.com/pimcore/data-hub so'll close this issue here.
