### ISSUE TITLE
Set Editable Languages Systemwide per User/Role

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#3066]
# Feature Request 

add the ability to set the editable Languages systemwide per user/role.
in this case you do not add the shared translation settings per user and the language settings in workspaces for objects...

e.g. user "publisher" can only edit english and german systemwide.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
