### ISSUE TITLE
Add Pinned Tab in Language Tabs

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#3068]
# Feature Request 

add a pinned tab in language tabs, this would be helpful when you translate to a specific language you don't have to scroll left or right when you switch the language

![pinned_tab](https://user-images.githubusercontent.com/1086343/42622726-619dc4ec-85c1-11e8-8310-8fca12e86706.png)

**Comment by putzflorian** [comment]
The difference is when you slide left or right with the arrows the pinned language should remain fixed as the first tab and the other language slide.
This is useful when you translate from your pinned tab to a language who is to far right in the list.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
