### ISSUE TITLE
Add tagging functionality for documents/assts/objects

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#307]
+) define tag tree centrally
+) assign documents/assets/objects one or more tags
+) extend search-dialog to search based on the tag tree and the assigned tags

**Comment by bbak** [comment]
Good Idea, but please make it optional, not implemented in the 'core'. 
Implementing a tagging system like this (across all content-types) may lead to either another LEFT OUTER JOIN or additional SQL-Queries. Both may become at least a major slowdown on larger installations.

**Comment by fashxp** [comment]
we want to integrate it into core since it is a very central feature. 
of course we will have performance in mind. additional queries or joins are only done when tags need to be considered in a search. if not, nothing will change to the current queries.
