### ISSUE TITLE
Date filter is not working on custom report .

### ISSUE THREAD

**Issue by AroraVaishali** [pimcore/pimcore#3071]
### Expected behavior 
 Date filter is working for timestamp also or formatted date
### Actual behavior  
  Custom report is saving date in timestamp and cutsom report sent params in api like (

filter | [{"operator":"eq","value":"06/27/2018","property":"o_creationDate","type":"date"}]
-- | --
)

so it is not working
### Steps to reproduce  
  1) create a test custom report for query (select o_creationDate from objects) 
   2) Apply filter for date 
   3) Save and check for date filter.
   4) It is not working for exact date ie "ON" [filter]
(url
![customreport](https://user-images.githubusercontent.com/19402815/42636343-2a70fe68-8606-11e8-9965-0d8be22ac0f0.png)
)
### Code example 
```php
// your code
```

**Comment by dmiller0620** [comment]
This is still not working for me
![image](https://user-images.githubusercontent.com/55711342/65452495-f7331180-de06-11e9-8bc7-c10237ca4183.png)
