### ISSUE TITLE
Payment creation problem

### ISSUE THREAD

**Issue by sivaranjaniRam** [pimcore/pimcore#3072]
I have created a custom payment module in core shop and create a Type file  in src/AppBundle/Form/Type folder. But I am getting this error  
Fatal error: Cannot declare class AppBundle\CoreShop\Form\Type\InvoiceGatewayConfigurationType, because the name is already in use in /var/www/dev/pimcore_dev/src/AppBundle/Form/Type/InvoiceGatewayConfigurationType.php on line 0

**Comment by fashxp** [comment]
core shop is not part of pimcore core distribution. please refer to https://github.com/coreshop/CoreShop for core shop issues. thx.
