### ISSUE TITLE
Objectbrick fields are not restored

### ISSUE THREAD

**Issue by amarjeet6694** [pimcore/pimcore#3078]
# Bug Report
  
### Expected behavior 
When the user disagrees on deleting an object brick on object, the system should not remove the brick.
  
### Actual behavior  
Even if the user disagrees on deleting an object brick on object, the object brick is removed but appears again after reloading. 
 
### Steps to reproduce  
1. Click on add button to add an object brick.

![screenshot--2018-07-13-17-37-16](https://user-images.githubusercontent.com/29056383/42690789-438236a2-86c3-11e8-8a14-f2ba62bb2556.png)

2. Click on cross button to remove the brick but then click on **No** option.

![screenshot--2018-07-13-17-36-43](https://user-images.githubusercontent.com/29056383/42690806-4faabe90-86c3-11e8-83ea-fc6b02f9b7b6.png)

3. Object brick is removed (even before the user selects any option).    

![screenshot--2018-07-13-17-36-07](https://user-images.githubusercontent.com/29056383/42691514-f8efacd4-86c5-11e8-9511-015a359639b2.png)

**Comment by weisswurstkanone** [comment]
fixed in build 283
