### ISSUE TITLE
[Workflowmanagement] Conditional Workflow

### ISSUE THREAD

**Issue by psuhane** [pimcore/pimcore#3086]
# Improvement

In most of the application it is required to apply workflow on elements on the basis of some conditions e.g. Apply workflow on Product variants with category Shoes. 

It would be great if condition handler available while configuring workflow. Please refer following screen

![workflow](https://user-images.githubusercontent.com/12061880/42752755-8c188998-890c-11e8-95e2-a915894c53c0.png)

The workflow will only be applied on element if handler returns true(In addition to whatever the element types has been selected in workflow). In this way workflow can be triggered on the basis of any condition.

Note: The screenshot attached is from workflow gui plugin just for reference. But the changes has be be made workflowmanagement.php and core system.

**Comment by fashxp** [comment]
We are currently working on refactoring the workflow engine and migrate it to the symfony workflow engine. There this should be perfectly possible.
This is planned for next release after Pimcore 5.3 ...
