### ISSUE TITLE
Image is possible to add on locked field

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#3087]
It is possible to add an image to an Image Editable when the Editable is locked from the Master Document.

![2018-07-16_14-59-55](https://user-images.githubusercontent.com/1086343/42759956-051db5f6-8909-11e8-9b6e-3548a1a4241b.gif)

**Comment by brusch** [comment]
Probably all DnD enabled editables affected: snippet, href, ... -> needs to be checked.
