### ISSUE TITLE
[CSV Import] Not all fields are visible, you need to 

### ISSUE THREAD

**Issue by avdb** [pimcore/pimcore#3089]
# Bug Report

## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [x] This is not a security issue / vulnerability -> use [this form](https://pimcorehq.wufoo.com/forms/pimcore-security-report/) instead
- [x] Behavior is reproducible on http://demo-basic.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [x] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [x] There's no existing ticket for the same issue
- [x] Remove unused sections from below and this bullet points

### Expected behavior 
See all fields in csv-import view
  
### Actual behavior  
Don't see all fields in csv-import view
![screen shot 2018-07-16 at 16 19 04](https://user-images.githubusercontent.com/1193946/42763903-9ae34654-8914-11e8-927e-6ca516faf047.png)

If you collaps "Approval Columns" you see other fields popup at the end of the list
![screen shot 2018-07-16 at 16 19 12](https://user-images.githubusercontent.com/1193946/42763902-9ac7c8ca-8914-11e8-8551-05067d35b61b.png)
  
### Steps to reproduce  

- Do csv-import for products
- Go to tab "Column configuration"
- Collapse "Object Columns"
- You will see other fields popup at the end of the list.

**Comment by weisswurstkanone** [comment]
fixed in build 293
