### ISSUE TITLE
Not editable + Collapsible + Collapsed = broken Field-Collection

### ISSUE THREAD

**Issue by StephanWeinhold** [pimcore/pimcore#309]
When adding a Field-Collection to an object and checking the boxes at "Not editable", "Collapsible" and "Collapsed"...

![image](https://cloud.githubusercontent.com/assets/7237290/11337290/320f2c6e-91ec-11e5-970c-6054ae6f1f5c.png)

..the Field-Collection can't be viewed, because the unfold-caret can't be clicked:

![image](https://cloud.githubusercontent.com/assets/7237290/11337297/425e59f0-91ec-11e5-8de3-63571285c54b.png)

Don't know if this is a bug or a feature.

**Comment by weisswurstkanone** [comment]
build 3558 - ExtJS 3.4 and 6
