### ISSUE TITLE
Create separate permission for Master (Admin-Mode) data object layout

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#3111]
Sometimes advanced customers need to be able to change not-editable fields. At the moment this is only possible when the user is a real Pimcore admin. But generally it's not a good idea to give the customer access for example to the database or the server file explorer. Therefore some kind of user right for this feature would be appreciated.

**Comment by dpfaffenbauer** [comment]
Why would you have the need to change a non-editable field? That renders the whole concept of non editable fields obsolete.

**Comment by markus-moser** [comment]
Sometimes it's helpful for admins who know exactly what they are doing (for example for testing purpose or in very special cases).

**Comment by brusch** [comment]
Can be solved via `AdminEvents::OBJECT_GET_PRE_SEND_DATA` ... eg.: 

```php
<?php

namespace AppBundle\EventListener;

use Pimcore\Event\AdminEvents;
use Pimcore\Model\DataObject;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\EventDispatcher\GenericEvent;

class TestListener implements EventSubscriberInterface
{
    /**
     * @inheritDoc
     */
    public static function getSubscribedEvents()
    {
        return [
            AdminEvents::OBJECT_GET_PRE_SEND_DATA => 'onObjectPreUpdate'
        ];
    }

    public function onObjectPreUpdate(GenericEvent $event)
    {
        $data = $event->getArgument('data');
        array_unshift ($data['validLayouts'], ['id' => -1, 'name' => 'Master (Admin Mode)']);

        if($_REQUEST['layoutId'] === "-1") {
            $layout = DataObject\Service::getSuperLayoutDefinition($event->getArgument('object'));
            $data['layout'] = $layout;
        }

        $event->setArgument('data', $data);
    }
}
```
