### ISSUE TITLE
[ClassificationStore] Encrypted Field not working properly

### ISSUE THREAD

**Issue by mbolka** [pimcore/pimcore#3112]
### Expected behavior 
  A group containing Encrypted Field type key displays properly in an object.
### Actual behavior  
  A group containing encrypted field is not displayed at all. Browser developer console displays error 
```
Uncaught TypeError: Cannot set property 'csKeyId' of null
``` 
### Steps to reproduce  
  1. Create new classification store.
  2. Create a new key with type Encrypted Field
  3. Create a new group and attach this key into it.
  4. Add the group to an object.
  5.  The group is not visible at the object. Browser console displays error.
Issue can be reproduced in https://demo-advanced.pimcore.org

This problem occurs in web/pimcore/static6/js/pimcore/object/tags/classificationstore.js:424

**Comment by brusch** [comment]
fixed by 11a865225d17c4cb7702ffc7ca3d8c7c7d68135a
