### ISSUE TITLE
Pimcore should not depend on *new* dependencies during update process

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#3115]
# Bug Report

### Actual result

The update from Pimcore 5.2 to 5.3 aborted during the updated process because of the following error:

```
ClassNotFoundException
                                    
Attempted to load class “SchebTwoFactorBundle” from namespace “Scheb\TwoFactorBundle”.
Did you forget a “use” statement for another namespace?
                                
in Kernel.php line 256
at Kernel->registerCoreBundlesToCollection(object(BundleCollection))in Kernel.php line 202
at Kernel->registerBundles()in Kernel.php line 494
at Kernel->initializeBundles()in Kernel.php line 134
at Kernel->boot()in Kernel.php line 161
at Kernel->boot()in kernel.php line 27
at require_once(‘/home/danubcbm/pimcore/config/kernel.php’)in app.php line 50
```
As a result the website was broken. I had to execute `composer update` which installed SchebTwoFactorBundle, then the website was "repaired" and I was able to repeat the update without any error.

### Expected result

The update process should run without any exceptions.

Maybe the updater could check at the beginning of the update process if all dependencies are there.

**Comment by brusch** [comment]
Normally Pimcore checks for new dependencies and runs Composer when necessary - maybe something went wrong in your case.

**Comment by brusch** [comment]
Just tried the update with the basic demo package from 5.2.0 to 5.3.0 - no issues so far, so i assume your problem was caused by some project specific configurations.

**Comment by cadeyrn** [comment]
I guess it's because we always had to execute the composer update manually. Probably the path to composer has to be added to the path settings. I'll check this once the next update is available. ;-)

**Comment by brusch** [comment]
yep, or you can also specify it in your `parameters.yml`: 
https://github.com/pimcore/pimcore/blob/master/app/config/parameters.example.yml#L9

**Comment by Cruiser13** [comment]
For the record - we just excperienced the exact same issue on one of our installations.

**Comment by dpfaffenbauer** [comment]
For the record: This isn't a issue anymore in Pimcore 5.4 since it depends on composer for updates anyway ;)
