### ISSUE TITLE
[Updater] Use Composer for Updates

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#3120]
- Up / down migrations
- Pimcore as Composer dependency - #2687

**Comment by dpfaffenbauer** [comment]
BTW: Do you really plan on releasing this with 5.4?

**Comment by brusch** [comment]
Yes

**Comment by dpfaffenbauer** [comment]
Isn't this more of a 6.0 change? I mean, many workflows depend on the way Pimcore works right now, with the release of 5.4, all of that would be broken.

How do you plan the update anyway?

**Comment by brusch** [comment]
At the moment it seems that the impact on application-code is very low, that's why the working title is `5.4` for the moment. If we encounter any major issues with that, we'd have to think about releasing this change as a new major version. 

The update process is planned as follows: 
- Update with the existing updater to version `5.4.0` (that option will be offered) 
- At a certain point the updater will display a message, that you should continue the update by running `composer update`
- Continuing the update with `composer update` ... 
- Manual cleanup tasks 
  - `rm -r pimcore/`
  - get rid of Pimcore dependencies in `composer.json` (tbd) 
  - ... probably others

**Comment by dpfaffenbauer** [comment]
Ok, sounds good so far.

**Comment by dpfaffenbauer** [comment]
🎉 🍻
