### ISSUE TITLE
Render ObjectMeadata ends up with a javascript error

### ISSUE THREAD

**Issue by lgaidzik** [pimcore/pimcore#3129]
Pimcore Version 5.3.0

MetaObjects are not shown in the Frontend. The Javascript throws the exception: 

> Cannot read property 'fullpath' of undefined

This exception occurre in the Javascript  file: 

> web/pimcore/static6/js/pimcore/object/tags/objectsMetadata.js:108

I add a console output to see how the object `fieldConfig` looks like in the javascript but the field `visibleFieldDefinitions` does not exist.

I try to reproduce it on a fresh pimcore installation and the same error occurre.

What I did:

1. create a new  fieldcollection `ExampleCollection` with a `Objects with Metadata` inside
2. add some `Visible Fields` in the ObjectMetadata like `fullpath` and `key` for example
3. save `ExampleCollection` definition
4. create a new object `ExampleObj` with a `Field-Collections` of the before created type: `ExampleCollection`
5. save `ExampleObj` definition
6. create a new Object under `Data Objects` and try to add a new `FieldCollection`
7. js exception is thrown

**Comment by weisswurstkanone** [comment]
build 293
