### ISSUE TITLE
Pimcore\Controller\FrontendController doesn't implements __isset() magic method

### ISSUE THREAD

**Issue by Zamralik** [pimcore/pimcore#3130]
In you have a controller like this
```php
class MyController extends Pimcore\Controller\Frontend
{
    public function myAction(Request $request)
    {
        $document = $this->document;
        if (empty($this->document) !== empty($document))
        {
            thow new Exception('It is inconsistent!');
        }
    }
}
```
And a document configured to use MyController->myAction.

If you open that document, you'll get the exception "It is inconsistent!" because Pimcore\Controller\Frontend doesn't implements a __isset() magic method, it only implements a __get() magic method.

The internal behavior of empty($this->document) is
```php
function fake_empty($object, $property_name)
{
    if (
        method_exists($object, '__isset')
        &&
        method_exists($object, '__get')
        &&
        $object->__isset($property_name)
    )
    {
        $value = $object->__get($property_name);

        if (is_array($value))
        {
            return 0 === count($value);
        }
        elseif (is_scalar($value))
        {
            return false === (bool) $value;
        }
    }

    return false;
}
```

**Comment by brusch** [comment]
I'm not sure what you're talking about, ... there is no class `Pimcore\Controller\Frontend` and the existing class `\Pimcore\Controller\FrontendController` has `__get()` implemented and everything works as expected. 

https://github.com/pimcore/pimcore/blob/5483c6f0fa00cfb4026b15ef5ffbfaf9dcee66ca/pimcore/lib/Pimcore/Controller/FrontendController.php#L51

**Comment by Zamralik** [comment]
You're right, I mistype the namespace. It's `\Pimcore\Controller\FrontendController`
As explained the issue is the missing `__isset()` magic method.
Without it, empty() always returns true and isset() always returns false, causing inconsistencies.

```php
class MyController extends \Pimcore\Controller\FrontendController
{
    public function myAction(Request $request)
    {
        if (empty($this->document))
        {
            thow new Exception('Missing document');
        }
        // or
        if (!isset($this->document))
        {
            thow new Exception('Missing document');
        }
        // You'll never reach here
        $response = new Response();
        $response->setContent('Hello, World!');
        $response->send();
    }
}
```
