### ISSUE TITLE
Support of 'Objects with Matadata' field with Non-owner object relation field

### ISSUE THREAD

**Issue by psuhane** [pimcore/pimcore#3135]
Support of 'Objects with Matadata' field with Non-owner object relation field

**Comment by brusch** [comment]
This is a feature request, currently it's intended to work with "Objects" data-type only.

**Comment by SEYentl** [comment]
Would be nice if it also works with "single" href.

**Comment by dergab** [comment]
@psuhane, we found a kind of a hidden path to achieve that. At least with Pimcore v5.5. First add a standard object-relation field (e.g. F1) to your model (e.g. in class A), then add the non-owner relation field (e.g. F2) to the other side (e.g. class B) referencing F1. After that you can change ("Convert to") F1 in class A to objects with metadata type. After saving it the F2 still relates (shows) objects added to F1. ;)

@brusch, this is really a drawback to not have this feature "enabled" for objects with metadata. We frequently have to workaround this missing option. Maybe the above "workaround" hints on a quick way to implement it (properly), so it finds its way into the core soon? ;D

**Comment by brusch** [comment]
@dergab maybe you should think about making a PR for that, instead of frequently working around this missing feature 😉

**Comment by dergab** [comment]
> @dergab maybe you should think about making a PR for that, instead of frequently working around this missing feature 😉
I did think about it, but I'm not very experienced in PHP-dev. So I fear a PR (in such an important part of the core) could cause more time spend on reviewing and commenting than the actual implementation. ;)
...but maybe I'll give it a try anyways...

**Comment by dergab** [comment]
As it turned out it wasn't too much of coding...basically nothing at all... 😬

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
