### ISSUE TITLE
Objects: Tabpanel in Block breaks Pimcore

### ISSUE THREAD

**Issue by Lexipowder** [pimcore/pimcore#3138]
![tab in block](https://user-images.githubusercontent.com/20427487/43202526-0cc50ede-901c-11e8-8199-b3cb943ba0e3.PNG)

Behavior is reproducible on http://demo-basic.pimcore.org/admin/ (admin/demo) 

Object structure:
![tab in block2](https://user-images.githubusercontent.com/20427487/43202855-e0dc6a1e-901c-11e8-8ecf-16890c8e2643.PNG)

Block element breaks when you want to add a second item, please see first pic.

**Comment by brusch** [comment]
Not sure if we can _fix_ / _make that possible_ since ExtJS has also it's limits ;-) 
@weisswurstkanone can you please check that when you have time?
