### ISSUE TITLE
Wrong PHPDoc for magic methods getBy... for objects

### ISSUE THREAD

**Issue by TPETb** [pimcore/pimcore#314]
PHPDoc for object classes would contain something like

* @method static \Pimcore\Model\Object\Forum getByTitle ($value, $limit = 0)

actually type hinting is wrong, should be 

* @method static \Pimcore\Model\Object\Forum\Listing getByTitle ($value, $limit = 0)

this confused both IDE and newcomers of pimcore coding

**Comment by brusch** [comment]
https://github.com/pimcore/pimcore/blob/master/pimcore/models/Object/ClassDefinition.php#L269
