### ISSUE TITLE
update 5.3.0 -> 5.3.1 fails with errors

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#3144]
# Bug Report

The update from Pimcore 5.3.0 to 5.3.1 fails with two error messages.

![bildschirmfoto 2018-07-26 um 12 56 45](https://user-images.githubusercontent.com/1100614/43258566-8509d854-90d3-11e8-8d80-690e4ecc3181.png)

![bildschirmfoto 2018-07-26 um 12 56 54](https://user-images.githubusercontent.com/1100614/43258572-8887e804-90d3-11e8-928f-3e3569bb1dcb.png)

I tested the update three times, always with the same result. Unfortunately there are no more detailed error messages. If you need more information let me know.

**Comment by cadeyrn** [comment]
I get the same error after the failed update when executing "php bin/console cache:clear":

PHP Fatal error:  Uncaught Error: Class 'Pimcore' not found in /web/web10650/pimcore/lib/Pimcore/Bootstrap.php:130
Stack trace:
#0 /web/web10650/pimcore/lib/Pimcore/Bootstrap.php(49): Pimcore\Bootstrap::boostrap()
#1 /web/web10650/bin/console(24): Pimcore\Bootstrap::startupCli()
#2 {main}
  thrown in /web/web10650/pimcore/lib/Pimcore/Bootstrap.php on line 130

**Comment by brusch** [comment]
Just updated from a fresh `5.2.2` to `5.3.1` without any problems. 
Can you share the contents of your `composer.json` or can you please try to further debug the problem? 
Thanks!

**Comment by mittererr** [comment]
My composer.json:

```
{
	"name" : "pimcore/pimcore",
	"type" : "project",
	"description" : "Content & Product Management Framework (CMS/PIM/E-Commerce)",
	"keywords" : [
		"CMS",
		"PIM",
		"DAM",
		"E-Commerce",
		"RAD",
		"Product Information Management"
	],
	"homepage" : "http://www.pimcore.org/",
	"license" : "GPL-3.0-or-later",
	"authors" : [{
			"name" : "pimcore Team",
			"email" : "info@pimcore.com",
			"homepage" : "http://www.pimcore.org/",
			"role" : "Developer"
		}
	],
	"support" : {
		"issues" : "https://github.com/pimcore/pimcore/issues",
		"wiki" : "https://pimcore.com/docs/5.0.x/index.html",
		"source" : "https://github.com/pimcore/pimcore",
		"forum" : "https://groups.google.com/forum/#!forum/pimcore",
		"docs" : "https://pimcore.com/docs/5.0.x/index.html"
	},
	"config" : {
		"optimize-autoloader" : true,
		"sort-packages" : true
	},
	"require" : {
		"php" : ">=7.1",
		"ext-SimpleXML" : "*",
		"ext-bz2" : "*",
		"ext-dom" : "*",
		"ext-exif" : "*",
		"ext-fileinfo" : "*",
		"ext-gd" : "*",
		"ext-iconv" : "*",
		"ext-mbstring" : "*",
		"ext-mysqli" : "*",
		"ext-openssl" : "*",
		"ext-pdo_mysql" : "*",
		"ext-zip" : "*",
		"ext-zlib" : "*",
		"amnuts/opcache-gui" : "~2",
		"cache/tag-interop" : "^1",
		"cocur/slugify" : "^3.1",
		"colinmollenhour/credis" : "1.8.*",
		"composer/ca-bundle" : "^1",
		"debril/rss-atom-bundle" : "^3.0",
		"defuse/php-encryption" : "~2",
		"doctrine/annotations" : "~1.4.0",
		"doctrine/cache" : "~1.6.2",
		"doctrine/collections" : "~1.4.0",
		"doctrine/common" : "~2.7.3",
		"doctrine/dbal" : "~2.5.13",
		"doctrine/doctrine-bundle" : "~1.6.8",
		"doctrine/doctrine-migrations-bundle" : "~1.2.1",
		"doctrine/instantiator" : "~1.0.5",
		"egulias/email-validator" : "*",
		"endroid/qr-code" : "~2.2",
		"geoip2/geoip2" : "~2",
		"google/apiclient" : "^2.0",
		"guzzlehttp/guzzle" : "~6.0",
		"hybridauth/hybridauth" : "~2",
		"lcobucci/jwt" : "^3.2",
		"league/csv" : "^9.1",
		"linfo/linfo" : "~3",
		"mjaschen/phpgeo" : "^2.0",
		"monolog/monolog" : "~1",
		"mpratt/embera" : "~1",
		"myclabs/deep-copy" : "~1.3",
		"myclabs/php-enum" : "^1.5",
		"neitanod/forceutf8" : "~2",
		"nesbot/carbon" : "~1",
		"ocramius/package-versions" : "^1.2",
		"ocramius/proxy-manager" : "2.1.*",
		"oyejorge/less.php" : "~1.7",
		"pear/net_url2" : "~2.2",
		"phive/twig-extensions-deferred" : "^2.0",
		"pimcore/core-version" : "v5.3.0",
		"piwik/device-detector" : "^3.9",
		"presta/sitemap-bundle" : "^1.5",
		"ramsey/uuid" : "~3",
		"sabre/dav" : "~3.1",
		"sensio/distribution-bundle" : "^5.0.19",
		"sensio/framework-extra-bundle" : "^3.0.2",
		"sensio/generator-bundle" : "^3.0",
		"sensiolabs/ansi-to-html" : "^1.1",
		"symfony-cmf/routing-bundle" : "^2.0",
		"symfony/monolog-bundle" : "^3.1.0",
		"symfony/polyfill-apcu" : "^1.0",
		"symfony/swiftmailer-bundle" : "^2.6.4",
		"symfony/symfony" : "3.4.13",
		"tijsverkoyen/css-to-inline-styles" : "~1.5",
		"twig/extensions" : "^1.5",
		"twig/twig" : "^2.0",
		"umpirsky/country-list" : "2.0.4",
		"vrana/adminer" : "~4.6",
		"vrana/jush" : "~2.0.2",
		"wa72/htmlpagedom" : "^1.3",
		"wikimedia/composer-merge-plugin" : "^1.4",
		"zendframework/zend-code" : "~3.1.0",
		"zendframework/zend-paginator" : "^2.7",
		"zendframework/zend-servicemanager" : "^3.2",
		"scheb/two-factor-bundle" : "~3.0"
	},
	"require-dev" : {
		"cache/integration-tests" : "^0.15.0",
		"codeception/codeception" : "~2.3.8"
	},
	"suggest" : {
		"ext-curl" : "*",
		"ext-imagick" : "*",
		"ext-redis" : "*",
		"ext-memcache" : "*",
		"klarna/checkout" : "1.2.0",
		"elasticsearch/elasticsearch" : "2.0.0"
	},
	"autoload" : {
		"psr-4" : {
			"" : "src/",
			"Pimcore\\Model\\DataObject\\" : "var/classes/DataObject",
			"Pimcore\\Model\\Object\\" : "var/classes/Object",
			"Pimcore\\Model\\" : "pimcore/models",
			"Pimcore\\" : "pimcore/lib/Pimcore",
			"Website\\" : "legacy/website/lib"
		},
		"classmap" : [
			"app/AppKernel.php",
			"pimcore/lib/Pimcore.php"
		],
		"exclude-from-classmap" : [
			"install-profiles/",
			"pimcore/lib/compatibility-stubs.php",
			"pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/config/namespace_compatibility.php"
		]
	},
	"scripts" : {
		"post-create-project-cmd" : "Pimcore\\Composer::postCreateProject",
		"post-install-cmd" : [
			"Pimcore\\Composer::postInstall",
			"@symfony-scripts"
		],
		"post-update-cmd" : [
			"Pimcore\\Composer::postUpdate",
			"@symfony-scripts"
		],
		"symfony-scripts" : [
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
			"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
		]
	},
	"extra" : {
		"symfony-app-dir" : "app",
		"symfony-bin-dir" : "bin",
		"symfony-var-dir" : "var",
		"symfony-web-dir" : "web",
		"symfony-tests-dir" : "tests",
		"symfony-assets-install" : "relative",
		"merge-plugin" : {
			"include" : [
				"composer.local.json"
			],
			"recurse" : true,
			"replace" : false,
			"merge-dev" : true,
			"merge-extra" : false,
			"merge-extra-deep" : false,
			"merge-scripts" : false
		}
	}
}
```

**Comment by cadeyrn** [comment]
composer.json:

`{
    "name": "pimcore/pimcore",
    "type": "project",
    "description": "Content & Product Management Framework (CMS/PIM/E-Commerce)",
    "keywords": [
        "CMS",
        "PIM",
        "DAM",
        "E-Commerce",
        "RAD",
        "Product Information Management"
    ],
    "homepage": "http://www.pimcore.org/",
    "license": "GPL-3.0-or-later",
    "authors": [
        {
            "name": "pimcore Team",
            "email": "info@pimcore.com",
            "homepage": "http://www.pimcore.org/",
            "role": "Developer"
        }
    ],
    "support": {
        "issues": "https://github.com/pimcore/pimcore/issues",
        "wiki": "https://pimcore.com/docs/5.0.x/index.html",
        "source": "https://github.com/pimcore/pimcore",
        "forum": "https://groups.google.com/forum/#!forum/pimcore",
        "docs": "https://pimcore.com/docs/5.0.x/index.html"
    },
    "config": {
        "optimize-autoloader": true,
        "sort-packages": true
    },
    "repositories": {
        "vrana-jush": {
            "info1": "External dependency of vrana/adminer which isn't included or referenced by adminer, see also https://sourceforge.net/p/adminer/bugs-and-features/468/ ",
            "info2": "The package on GitHub isn't compatible with Adminer, it doesn't contain the /modules/ folder.",
            "type": "package",
            "package": {
                "name": "vrana/jush",
                "version": "1.0.0",
                "source": {
                    "url": "https://git.code.sf.net/p/jush/git",
                    "type": "git",
                    "reference": "master"
                }
            }
        }
    },
    "require": {
        "php": ">=7.1",
        "ext-SimpleXML": "*",
        "ext-bz2": "*",
        "ext-dom": "*",
        "ext-exif": "*",
        "ext-fileinfo": "*",
        "ext-gd": "*",
        "ext-iconv": "*",
        "ext-mbstring": "*",
        "ext-mysqli": "*",
        "ext-openssl": "*",
        "ext-pdo_mysql": "*",
        "ext-zip": "*",
        "ext-zlib": "*",
        "amnuts/opcache-gui": "~2",
        "cache/tag-interop": "^1",
        "colinmollenhour/credis": "1.8.*",
        "composer/ca-bundle": "^1",
        "debril/rss-atom-bundle": "^3.0",
        "defuse/php-encryption": "~2",
        "doctrine/annotations": "~1.4.0",
        "doctrine/cache": "~1.6.2",
        "doctrine/collections": "~1.4.0",
        "doctrine/common": "~2.7.3",
        "doctrine/dbal": "~2.5.13",
        "doctrine/doctrine-bundle": "~1.6.8",
        "doctrine/doctrine-migrations-bundle": "~1.2.1",
        "doctrine/instantiator": "~1.0.5",
        "egulias/email-validator": "*",
        "geoip2/geoip2": "~2",
        "google/apiclient": "^2.0",
        "guzzlehttp/guzzle": "~6.0",
        "hybridauth/hybridauth": "~2",
        "lcobucci/jwt": "^3.2",
        "league/csv": "^9.1",
        "linfo/linfo": "~3",
        "mjaschen/phpgeo": "^2.0",
        "monolog/monolog": "~1",
        "mpratt/embera": "~1",
        "myclabs/deep-copy": "~1.3",
        "neitanod/forceutf8": "~2",
        "nesbot/carbon": "~1",
        "ocramius/package-versions": "^1.2",
        "ocramius/proxy-manager": "2.1.*",
        "oyejorge/less.php": "~1.7",
        "patchwork/jsqueeze": "^2.0",
        "pear/net_url2": "~2.2",
        "phive/twig-extensions-deferred": "^2.0",
        "pimcore/core-version": "v5.3.0",
        "piwik/device-detector": "^3.9",
        "ramsey/uuid": "~3",
        "sabre/dav": "~3.1",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^3.0.2",
        "sensio/generator-bundle": "^3.0",
        "sensiolabs/ansi-to-html": "^1.1",
        "symfony-cmf/routing-bundle": "^2.0",
        "symfony/assetic-bundle": "^2.8",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.6.4",
        "symfony/symfony": "3.4.13",
        "tijsverkoyen/css-to-inline-styles": "~1.5",
        "twig/twig": "^2.0",
        "vrana/adminer": "~4.6",
        "vrana/jush": "~2.0.2",
        "wikimedia/composer-merge-plugin": "^1.4",
        "zendframework/zend-code": "~3.1.0",
        "zendframework/zend-paginator": "^2.7",
        "zendframework/zend-servicemanager": "^3.2",
        "endroid/qr-code": "~2.2",
        "presta/sitemap-bundle": "^1.5",
        "twig/extensions": "^1.5",
        "wa72/htmlpagedom": "^1.3",
        "myclabs/php-enum": "^1.5",
        "umpirsky/country-list": "2.0.4",
        "voku/html-min": "^3.0",
        "scheb/two-factor-bundle": "~3.0"
    },
    "require-dev": {
        "cache/integration-tests": "^0.15.0",
        "codeception/codeception": "~2.3.8"
    },
    "suggest": {
        "ext-curl": "*",
        "ext-imagick": "*",
        "ext-redis": "*",
        "ext-memcache": "*",
        "klarna/checkout": "1.2.0",
        "elasticsearch/elasticsearch": "2.0.0",
        "codeception/codeception": "^2.2"
    },
    "autoload": {
        "psr-4": {
            "": [
                "src/"
            ],
            "Pimcore\\Model\\DataObject\\": "var/classes/DataObject",
            "Pimcore\\Model\\Object\\": "var/classes/Object",
            "Pimcore\\Model\\": "pimcore/models",
            "Pimcore\\": "pimcore/lib/Pimcore",
            "Website\\": "legacy/website/lib"
        },
        "classmap": [
            "app/AppKernel.php",
            "pimcore/lib/Pimcore.php"
        ],
        "exclude-from-classmap": [
            "install-profiles/",
            "pimcore/lib/compatibility-stubs.php",
            "pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/config/namespace_compatibility.php"
        ]
    },
    "scripts": {
        "post-create-project-cmd": "Pimcore\\Composer::postCreateProject",
        "post-install-cmd": [
            "Pimcore\\Composer::postInstall",
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "Pimcore\\Composer::postUpdate",
            "@symfony-scripts"
        ],
        "symfony-scripts": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "merge-plugin": {
            "include": [
                "composer.local.json"
            ],
            "recurse": true,
            "replace": false,
            "merge-dev": true,
            "merge-extra": false,
            "merge-extra-deep": false,
            "merge-scripts": false
        }
    }
}`

Executing "composer update" manually makes the website usable again (maybe because of the regenerated autoload files?)

**Comment by brusch** [comment]
Hmmm `pimcore/lib/Pimcore.php` is referenced in the classmap, so the autoloader should be able to find the class. 

No more ideas so far, so it would be good if you could debug that on your end.

**Comment by brusch** [comment]
hmm, interesting...

**Comment by brusch** [comment]
Can you please try it again?

**Comment by Svensson11** [comment]
Got the same problem. 5.3.0 to 5.3.1.
`
},
    "autoload": {
        "psr-4": {
            "": [
                "src/"
            ],
            "Pimcore\\Model\\DataObject\\": "var/classes/DataObject",
            "Pimcore\\Model\\Object\\": "var/classes/Object",
            "Pimcore\\Model\\": "pimcore/models",
            "Pimcore\\": "pimcore/lib/Pimcore",
            "Website\\": "legacy/website/lib"
        },
        "classmap": [
            "app/AppKernel.php",
            "pimcore/lib/Pimcore.php"
        ],`

**Comment by mittererr** [comment]
Still no luck - same error. The update download is very quick. About 2 seconds from 0 to 100%. Maybe there is something wrong in the download?

**Comment by brusch** [comment]
How long is it ago, can you please try it again?

**Comment by brusch** [comment]
Hmm, I'm wondering how this could be ... there's `include_once` used now ...
https://github.com/pimcore/pimcore/commit/db6d1e3aea4673353d1263ea5379421b91fccd22

**Comment by brusch** [comment]
Still the same error or a different one?

**Comment by mittererr** [comment]
The same error in my case.

**Comment by cadeyrn** [comment]
I also tested again. Still the same error and the file pimcore/lib/Pimcore/Bootstrap.php does not contain the new line (include_once __DIR__ . '/../Pimcore.php';) after the update failed.

**Comment by brusch** [comment]
This is how the updater get's the files: 
https://liveupdate.pimcore.org/download-files?for=291&offset=0&limit=50 
Content is base64 encoded, if you decode the content of `` it definitely contains the `include_once` line.

**Comment by cadeyrn** [comment]
I don't know how the update process of Pimcore works. Is it possible that the error occurs before the file is being replaced?

I tested several times and the issue is still there. And  mittererr also wrote 30 minutes ago that the problem is still there.

**Comment by cadeyrn** [comment]
for the record: the update to the unstable build 293 and from there to the build 295 worked for me.

**Comment by brusch** [comment]
That should be fixed now.

**Comment by brusch** [comment]
see also https://github.com/pimcore/pimcore/issues/3177#issuecomment-410146282
