### ISSUE TITLE
Filter Feature in element tree

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#3149]
![image](https://user-images.githubusercontent.com/8792145/43383372-17baaa5c-93db-11e8-9ddb-46c0258c83bd.png)

![image](https://user-images.githubusercontent.com/8792145/43383377-1a63c6f8-93db-11e8-9e4c-1ed5c44c26aa.png)

**Comment by brusch** [comment]
@weisswurstkanone please change the search behavior from `*bar*` to `bar*` + additional support to place a `* ` individually anywhere in the search query (eg. `*foo*bar*awe*`)
