### ISSUE TITLE
When creating a new class definition an error is logged

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#3152]
# Bug Report
When you save a new class definition, Pimcore write an error entry in the var/log/prod.log:
`[2018-07-30 09:58:38] pimcore.ERROR: Exception: Class definition with name  or ID 8 does not exist in /home/pimcore_demo_basic/www/pimcore/models/DataObject/ClassDefinition.php:181 Stack trace: #0 /home/pimcore_demo_basic/www/pimcore/models/DataObject/ClassDefinition.php(276): Pimcore\Model\DataObject\ClassDefinition::getById('8') #1 /home/pimcore_demo_basic/www/pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/ClassController.php(258): Pimcore\Model\DataObject\ClassDefinition->save(true) #2 /home/pimcore_demo_basic/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): Pimcore\Bundle\AdminBundle\Controller\Admin\ClassController->addAction(Object(Symfony\Component\HttpFoundation\Request)) #3 /home/pimcore_demo_basic/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /home/pimcore_demo_basic/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /home/pimcore_demo_basic/www/web/app.php(48): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #6 {main} [] []`
  
### Expected behavior 
Pimcore shouldn't write this entry
  
### Actual behavior  
Pimcore write this entry
  
### Steps to reproduce  

1. Go to classes in the admin interface
2. Create a new class
3. Save

**Comment by brusch** [comment]
Unable to reproduce - tested on demo-basic.pimcore.org and demo-advanced.pimcore.org

**Comment by blankse** [comment]
@brusch I tested also on demo-basic.pimcore.org

Here the log after I create the Test class:

`[2018-07-31 11:42:57] pimcore.ERROR: Exception: Class definition with name  or ID 9 does not exist in /home/pimcore_demo_basic/www/vendor/pimcore/pimcore/models/DataObject/ClassDefinition.php:193 Stack trace: #0 /home/pimcore_demo_basic/www/vendor/pimcore/pimcore/models/DataObject/ClassDefinition.php(288): Pimcore\Model\DataObject\ClassDefinition::getById('9') #1 /home/pimcore_demo_basic/www/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/ClassController.php(258): Pimcore\Model\DataObject\ClassDefinition->save(true) #2 /home/pimcore_demo_basic/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): Pimcore\Bundle\AdminBundle\Controller\Admin\ClassController->addAction(Object(Symfony\Component\HttpFoundation\Request)) #3 /home/pimcore_demo_basic/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /home/pimcore_demo_basic/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /home/pimcore_demo_basic/www/web/app.php(42): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #6 {main} [] []`
