### ISSUE TITLE
startup_cli.php  broken

### ISSUE THREAD

**Issue by Sunohara666** [pimcore/pimcore#3154]
# Bug Report
 
  
### Expected behavior 
  no error

### Actual behavior  
PHP Fatal error:  Uncaught Error: Class 'Pimcore\Bootstrap' not found in /data/projects/kh-pimcore/pimcore/config/startup_cli.php:14
Stack trace:
#0 {main}
  thrown in /data/projects/kh-pimcore/pimcore/config/startup_cli.php on line 14

Fatal error: Uncaught Error: Class 'Pimcore\Bootstrap' not found in /data/projects/kh-pimcore/pimcore/config/startup_cli.php:14
Stack trace:
#0 {main}
  thrown in /data/projects/kh-pimcore/pimcore/config/startup_cli.php on line 14
  
### Code example 
```php
see https://pimcore.com/docs/5.x/Development_Documentation/Development_Tools_and_Details/Console_CLI.html

code:

<?php 
include(__DIR__ . "/../pimcore/config/startup_cli.php");
```

**Comment by brusch** [comment]
See #3144

**Comment by Sunohara666** [comment]
require (__DIR__ . '/../../../../pimcore/lib/Pimcore/Bootstrap.php');

$kernel = \Pimcore\Bootstrap::startupCli();

**Comment by Jaswinder00** [comment]
@Sunohara666 
Thanks for the response! 
I had to modify the the path to following and then it worked.
require (__DIR__ . '/../lib/Pimcore/Bootstrap.php');

**Comment by brusch** [comment]
See also https://github.com/pimcore/pimcore/issues/3177#issuecomment-410146282
