### ISSUE TITLE
Deprecate/Remove "Simple CLI Script"

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#3155]
There is no real need or benefit of using "simple CLI Scripts" over Symfony Console. I suggest deprecate this feature and remove it in the next major release. (https://pimcore.com/docs/5.x/Development_Documentation/Development_Tools_and_Details/Console_CLI.html#page_Simple-CLI-Scripts)

**Comment by brusch** [comment]
They were already removed, just updated the docs accordingly.
