### ISSUE TITLE
Upgrade to Pimcore 5.3.1 Class 'Pimcore\Bootstrap' not found

### ISSUE THREAD

**Issue by bramstroker** [pimcore/pimcore#3158]
During upgrade of Pimcore 5.2.0 to 5.3.1 with the UI I first got the error as reported in https://github.com/pimcore/pimcore/issues/3115.

Did a manual `composer update` as indicated and rerun the update process.

Now the update continues to approx 88% en than the following error pops up:

`Fatal error: Uncaught Error: Class 'Pimcore\Bootstrap' not found in pimcore/config/startup.php on line 14`

Look like autoloading is completely broken.
I look in both index.php and startup.php but composer autoloading file is never included?

Do I miss something? Not sure how to continue and successfully upgrade to 5.3.1

**Comment by brusch** [comment]
The file `/pimcore/lib/Pimcore/Bootstrap.php` does exist? 
What is the content of `startup.php?

**Comment by bramstroker** [comment]
Yes that file exists.
I managed to get it working now. I see in the new version there is no index.php anymore, but app.php
Copied contents of app.php to index.php and now it is working.
I see a .htaccess file is provided, but we don't use apache but nginx.
This should definitely be documented somewhere because this is a major change and will really give unexperienced developers headaches.

**Comment by bramstroker** [comment]
The update now completed succesfully, but unfortunately I stumble upon new issues. Will create a new bug report for that.

**Comment by dpfaffenbauer** [comment]
I know what the issue is, at least for CLI.

`startup_cli.php` requires Bootstrap before Pimcore loads the composer autoloader.

**Comment by dpfaffenbauer** [comment]
and `startup.php` does the same

**Comment by dpfaffenbauer** [comment]
oh, it didn't update the `bin/console`, thats the reason.

**Comment by brusch** [comment]
I did some manual patches on the updater, so everything should run smoothly since that, see also #3115
