### ISSUE TITLE
[Shared Translations] Possibilty to import from bundle

### ISSUE THREAD

**Issue by Sonja-Schubert** [pimcore/pimcore#3162]
Hi there,

It would be useful if there is a possibility to import some shared translations as soon as a bundle is installed / loaded in the installation. 

I would save an exportfile, which was generated by exporting some shared translations, to Resources/install folder of the bundle and would like to import these by Installer PHP script as soon as bundle is loaded.

Kind regards,
Sonja

**Comment by brusch** [comment]
Bundles can contain there own translations (Symfony default), eg.: 
https://github.com/pimcore/output-data-config-toolkit/tree/master/src/Resources/translations
