### ISSUE TITLE
[Static Routes] Possibility to import from bundle

### ISSUE THREAD

**Issue by Sonja-Schubert** [pimcore/pimcore#3163]
Hi there,

It would be useful if there is a possibility to import a static route as soon as a bundle is installed / loaded in the installation. 

I would save a local static routes php file in the bundle, which should be loaded automatically as soon as the global staticroutes.php file is loaded also.

With this feature every static route which belong to a bundle would gone away as soon as the bundle is deinstalled, which is cleaner than manually deleting the route in the global staticroutes.php file.

Kind regards,
Sonja

**Comment by brusch** [comment]
You can include Symfony routes in your bundle, eg. https://github.com/pimcore/customer-data-framework/blob/master/src/Resources/config/pimcore/routing.yml 

Of you can use migrations to install static routes: 
https://pimcore.com/docs/5.x/Development_Documentation/Development_Tools_and_Details/Migrations.html
