### ISSUE TITLE
Option to delete Bulk Emails 

### ISSUE THREAD

**Issue by AmitThakur-23** [pimcore/pimcore#3171]
Bulk Email Delete option is not available.

**Steps to Produce**:
1) Go to Tools
2) Select Emails > Sent emails

![email_1](https://user-images.githubusercontent.com/42028592/43573541-91087a5c-965f-11e8-8147-066b6cef3aa7.jpg)

3) Here no option is available to delete multiple emails / Bulk emails.

![email_2](https://user-images.githubusercontent.com/42028592/43573563-a0d099e2-965f-11e8-8ced-58365f93b7af.jpg)

**Comment by fashxp** [comment]
there is a cli command `pimcore:email:cleanup`
see also https://pimcore.com/docs/5.x/User_Documentation/Administration_of_Pimcore/Data_Protection_and_GDPR.html#page_Right-to-Erasure

**Comment by AmitThakur-23** [comment]
Can there be a Checkbox for selecting multiple emails in order to delete, if user want to delete it from Admin UI?

**Comment by fashxp** [comment]
PRs for this are welcome ;-)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
