### ISSUE TITLE
No option is available to Remove Application Logger from Admin UI

### ISSUE THREAD

**Issue by AmitThakur-23** [pimcore/pimcore#3172]
No option is available to Remove Application Logger from Admin UI

**Steps to produce:**
1) Go to tools 
2) Select Application Logger

![application_logger](https://user-images.githubusercontent.com/42028592/43573996-b0876496-9660-11e8-930e-7288fb804840.jpg)
3) No option is available to remove it from Admin UI

**Comment by brusch** [comment]
There's a user permission for that. 
![image](https://user-images.githubusercontent.com/142037/43574180-cee40bb4-9643-11e8-80aa-f157e9fbd748.png)
