### ISSUE TITLE
Select box options in different languages if localized.

### ISSUE THREAD

**Issue by AmitThakur-23** [pimcore/pimcore#3173]
Select box options in different languages if localized.

**Steps to produce:**
1) Add a Select attribute under localized field to the class 
2) Go to Selection Options
3) Option to set display name in multiple languages

![selectbox_options localized](https://user-images.githubusercontent.com/42028592/43576149-42f5a75c-9666-11e8-89dd-36cbc17e67a5.jpg)

**Comment by brusch** [comment]
Please, before opening a ticket, ask your question in our forums or Gitter channel. 

Answer: the values in _Display name_ can be translated using _Admin Translations_.
