### ISSUE TITLE
Use the intl Transliterator for transliteration

### ISSUE THREAD

**Issue by Magnum5234** [pimcore/pimcore#3175]
iconv is currently used for translitaration, please see https://github.com/pimcore/pimcore/blob/master/lib/Tool/Transliteration.php#L48

In this day and age when using containers you are forced to use a container with glibc support. (Also I believe this has the downside of forcing user to have certain locales installed on their operating system.)

Please replace this in favor of http://php.net/manual/en/class.transliterator.php (the intl package is already listed in the required packages). This will use the ICU library which should lead to the same result across different setups and operating systems.

# Related Error-Messages:

## Alpine linux
```
// Notice: iconv(): Wrong charset, conversion from `UTF-8' to `ASCII//IGNORE' is not allowed
echo iconv('ASCII', 'UTF-8', iconv('UTF-8', 'ASCII//IGNORE', 'blödṕ'));

// Notice: iconv(): Wrong charset, conversion from `UTF-8' to `ASCII//TRANSLIT' is not allowed
echo iconv('ASCII', 'UTF-8', iconv('UTF-8', 'ASCII//TRANSLIT', 'blödṕ'));

// Notice: iconv(): Wrong charset, conversion from `UTF-8' to `ASCII//IGNORE//TRANSLIT' is not allowed
echo iconv('ASCII', 'UTF-8', iconv('UTF-8', 'ASCII//IGNORE//TRANSLIT', 'blödṕ'));
```
## Alpine linux with compat library
(https://pkgs.alpinelinux.org/package/edge/testing/x86/gnu-libiconv)
```
// works
echo iconv('ASCII', 'UTF-8', iconv('UTF-8', 'ASCII//IGNORE', 'blödṕ'));

Notice: iconv(): Detected an illegal character in input string
echo iconv('ASCII', 'UTF-8', iconv('UTF-8', 'ASCII//TRANSLIT', 'blödṕ'));

// works apparently *shrug*
echo iconv('ASCII', 'UTF-8', iconv('UTF-8', 'ASCII//IGNORE//TRANSLIT', 'blödṕ'));
```

# Links
See related issue in the php docker image: https://github.com/docker-library/php/issues/240

**Comment by brusch** [comment]
Seems that `Transliterator::transliterate` has some issues, see: 

```php
var_dump(transliterator_transliterate('Any-Latin; Latin-ASCII; [\u0100-\u7fff] remove',
    "A æ Übérmensch på høyeste nivå! И я люблю PHP! есть. ﬁ"));
```

Any solutions are highly appreciated. 
Of course we're also accepting PRs, if the full functionality is given.

**Comment by brusch** [comment]
Details here: https://stackoverflow.com/a/16022459

**Comment by brusch** [comment]
We'd also need a replacement for the other usages of `iconv()` in the code: 
https://github.com/pimcore/pimcore/blob/c62924ca5c3d0c482a71097cb0231aff143208d6/lib/simple_html_dom.php#L818
https://github.com/pimcore/pimcore/blob/c62924ca5c3d0c482a71097cb0231aff143208d6/lib/Tool/Text.php#L358

Additionally, if change that, it would be also great if we could get rid of https://github.com/pimcore/pimcore/blob/c62924ca5c3d0c482a71097cb0231aff143208d6/lib/Tool/Transliteration.php#L77 and https://github.com/pimcore/pimcore/tree/c62924ca5c3d0c482a71097cb0231aff143208d6/lib/Tool/Transliteration/Data 

As I said, PR's are welcome 🤓

**Comment by j-jonas** [comment]
Maybe interesting for others, at the moment our quickfix is:

```
# Iconv Fix, siehe https://github.com/docker-library/php/issues/240#issuecomment-305038173
# Pimcore Issue: https://github.com/pimcore/pimcore/issues/3175
RUN apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing gnu-libiconv
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php
```

**Comment by Magnum5234** [comment]
@brusch 
> Seems that Transliterator::transliterate has some issues, see:
> Any solutions are highly appreciated.

Apparently this depends on your viewpoint. You can read a lot about this [soft sign](https://en.wikipedia.org/wiki/Soft_sign) in the corresponding [unicode trac ticket](http://unicode.org/cldr/trac/ticket/8921). I'm not an expert in Cyrillic letters and how to transliterate them. But it seems to me that the so called broken use case only works for plain Russian but not for other (Cyrillic) languages, where a quotation mark might still be the correct way to go.

> Of course we're also accepting PRs, if the full functionality is given.

Depends on what you want to archive. Is there a unit test one could look up?
```Any-Latin; Latin-ASCII; [^a-zA-Z[:space separator:]] Any-remove``` results in ```string(53) "A ae Ubermensch pa hoyeste niva I a lublu PHP est fi "``` for the given example above. You can also play around [here](http://demo.icu-project.org/icu-bin/translit)

**Comment by brusch** [comment]
@Magnum5234 currently we don't have unit tests for that, probably a good chance to add them :) 

But even the example above shows differences: 

```php
        $subject = "A æ Übérmensch på høyeste nivå! И я люблю PHP! есть. ﬁ ¦";

        $foo = transliterator_transliterate('Any-Latin; Latin-ASCII; [\u0080-\u7fff] remove', $subject);
        $bar = Transliteration::toASCII($subject);

        dump([$foo, $bar]);
```

Result: 
```
  0 => "A ae Ubermensch pa hoyeste niva! I a lublu PHP! est'. fi "
  1 => "A ae Ubermensch pa hoyeste niva! I ya lyublyu PHP! est. fi |"
```

I have also no clue about Cyrillic letters and the correct way of transliterating them, but obviously we're getting different results from ICU data :) 

There are also some issues with language specific transliterations, for example: 

```php
        $subject = "üöä";

        $foo = transliterator_transliterate('Any-Latin; Latin-ASCII; [\u0080-\u7fff] remove', $subject);
        $bar = Transliteration::toASCII($subject, 'de');

        dump([$foo, $bar]);
```

```
  0 => "uoa"
  1 => "ueoeae"
```

**Comment by brusch** [comment]
Maybe it's enough to just replace `iconv()` with the following code: 

```php
$bar = transliterator_transliterate('Any-Latin; Latin-ASCII; [\u0080-\u7fff] remove', $bar);
$bar = preg_replace('/[^\x1F-\x7F]+/', '', $bar);
```
and keep the custom transliteration (`_transliterationProcess()`) in place as it is now. 

This solution looks quite promising (at least for my tests i did).

**Comment by Magnum5234** [comment]
@brusch Character set conversion did not cause any issues so far.

Thanks for your work! :)

P.S. With ICU 60.x you can do this:
```php
$subject = "üöä";
$foo = transliterator_transliterate('Any-Latin; de-ASCII; [\u0080-\u7fff] remove', $subject);
var_dump($foo); // string(6) "ueoeae"
```
see https://www.unicode.org/repos/cldr/trunk/common/transforms/de-ASCII.xml
Unfortunately this version of ICU is apparently not widespread used. At least not in the docker images of php. Latest alpine (3.8) and debian (stretch) install only 5.x version of ICU.

**Comment by brusch** [comment]
@Magnum5234 thanks for the hint with `de-ASCII`! I've seen that feature in the docs and tried it, but it didn't work, now I know why (ICU `57.1`) ;)
