### ISSUE TITLE
5.4 UI Update Checker doesn't work properly

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#3176]
I am up2date with Pimcore 5.4.0, but the UI tells me that there is a newer version available:

![bildschirmfoto 2018-08-02 um 15 47 01](https://user-images.githubusercontent.com/5981845/43587835-672cf328-966b-11e8-853f-d8f50d429205.png)

**Comment by brusch** [comment]
Thanks - the check (`version_compare()`) wasn't aware of the leading `v` :)
