### ISSUE TITLE
Broken v5.3.1 versions at startup_cli.php line 14

### ISSUE THREAD

**Issue by Jaswinder00** [pimcore/pimcore#3177]
# Bug Report
 
  
### Expected behavior 
  The composer update command should complete without any errors. Also, the php bin/console command should run without fatal error
### Actual behavior  
  I am getting the below error when running composer update or php bin/console command.
Pimcore\Composer::postInstall
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Fatal error:  Uncaught Error: Class 'Pimcore\Bootstrap' not found in /var/www/project/pimcore/config/startup_cli.php:14
Stack trace:
#0 /var/www/project/bin/console(33): require_once()
#1 {main}
  thrown in /var/www/project/pimcore/config/startup_cli.php on line 14
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception

In ScriptHandler.php line 293:
                                                                                                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command:                     
   
  PHP Fatal error:  Uncaught Error: Class 'Pimcore\Bootstrap' not found in /var/www/project/pimcore/config/startup_cli.php:14  
  Stack trace:                                                                                                                           
  #0 /var/www/project/bin/console(33): require_once()                                                                          
  #1 {main}                                                                                                                              
    thrown in /var/www/project/pimcore/config/startup_cli.php on line 14   
### Steps to reproduce  
  
Run composer install or update with a Pimcore version v5.3.1
You will see a fatal error on the console.
This issue was reported before #3144 and I tried to fix it by adding the include_once statement which did not work.

Please let me know how I can make the installation work. The code is in broken state.

**Comment by brusch** [comment]
### Update the following files / folders with the ones on GitHub: 
- https://github.com/pimcore/pimcore/tree/pimcore-5.3.x/pimcore/config
- https://github.com/pimcore/pimcore/blob/pimcore-5.3.x/web/app.php
- https://github.com/pimcore/pimcore/blob/pimcore-5.3.x/bin/console
- https://github.com/pimcore/pimcore/blob/pimcore-5.3.x/pimcore/lib/Pimcore/Bootstrap.php

### Run Composer
`composer update`

**Comment by brusch** [comment]
Can you tell me a bit more on how you performed the update? 
- CLI or web-based updater? 
- start build -> target build (version) 
- any additional composer dependencies? 
- PHP version
- any other incident during the update process?

**Comment by Jaswinder00** [comment]
@brusch 
The CLI updater did not work.
I moved the working site to another server with PHP 7.2 running. So, I resolved the Object issue using search and replace and replace the existing composer with 5.3.1 to do fresh install.
This issue is resolved now by adding the Bootstrap file path in startup_cli.php file

**Comment by shahilkhandelwal** [comment]
@Jaswinder00 how you have added Bootstrap file?
