### ISSUE TITLE
Scheduled Block Improvements

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#3178]
The Scheduled Block is a great new feature but also comes with some lacks in usability. 

## Change first added Block
![bildschirmfoto 2018-08-02 um 18 39 33](https://user-images.githubusercontent.com/700119/43597801-6f1eeba0-9683-11e8-818b-85905c791fea.png)

Currently it's not possible to change the date of the first added block. It's always the current date.

## Time-Slider
In short: I'm definitely too stupid for this. Sometimes there is a range slider (two knobs), sometimes only one and sometimes there is simply nothing. 

## Deleting Entries
![bildschirmfoto 2018-08-02 um 18 44 04](https://user-images.githubusercontent.com/700119/43598035-0e19ca22-9684-11e8-918e-6792a5ea1a35.png)

### Actual Status
- "_Delete all past entries_" -> only removes the oldest scheduled block
- "_Delete all entries_" -> only removes the oldest scheduled block
- It's not possible to remove a selected block

### Desired Status
- "_Delete all past entries_"  -> remove scheduled block `< NOW`
- "_Delete all entries_" -> remove all blocks
- "_Remove selected entry_" -> removes current block

## Highlighting
![bildschirmfoto 2018-08-02 um 18 51 45](https://user-images.githubusercontent.com/700119/43598500-209b494a-9685-11e8-9714-f0ef4cabcdf3.png)

Currently it's hard to see the current selection. It would be great if we could add some background color to the selected item in block selector.

**Comment by fashxp** [comment]
a few thoughts to your points: 

- change date of first entry: that is true, but you always can create another entry. but we plan a context-menu feature per entry to specify date+time in a popup-dialog. PRs are welcome ;-) 
- it is never a range slider. each entry is one "knob", if you have multiple entries then you have multiple knobs and the knob defines the start timestamp of the corresponding content.   
- delete all past entries: it deletes all past entries except the one that specifies the current content
- delete all entries: true, there is something broken - please make a seperate issue
- delete selected entry: use context menu.
- current selection: current active knob is marked yellow

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
