### ISSUE TITLE
Quicksearch fails when using classification store

### ISSUE THREAD

**Issue by daniel-travix** [pimcore/pimcore#3181]
### Actual behavior

**Exception is thrown in:** /admin/search/search/quicksearch
**Exception:** Catchable Fatal Error: Object of class Pimcore\Model\DataObject\Classificationstore could not be converted to string

### Steps to reproduce  

1. Create a classification store
2. Add a new group
3. Add a key and assign it to the group
4. Create a class and assign the store
5. Create a new object with this class and put some content in the field from the classification store
6. Save the object and reload your browser
7. Do a quicksearch that matches the object

![auswahl_079](https://user-images.githubusercontent.com/19191046/43635807-86c41bf8-9710-11e8-8398-b69d6c5d612a.png)

This is also reproducible at:
https://demo-basic.pimcore.org/admin/

**Comment by mbolka** [comment]
I have this same problem on version: 5.3.0 Build: 290
