### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by MhdRafik** [pimcore/pimcore#3198]
# Bug Report
hello i get an error during the installation:
Checking prerequisites...
  2/10 [=====>----------------------]  20%

 [ERROR] The following errors were encountered during installation
 * Fulltext Indexes is required.

any suggestions

**Comment by brusch** [comment]
Please don't make issues for support, use our Gitter channel or our forum instead. 
Thanks you very much! 

The error message says everything, ... your MySQL server needs to support full text indices.
