### ISSUE TITLE
Translations don't seems up to date on POEditor

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3207]
Hello,

I don't know if this is normal, but translations don't seems up to date on POEditor.

For instance, if you take https://github.com/pimcore/pimcore/blob/8cf32b125eb33b95f46ee8533af852273d0e3ff8/bundles/CoreBundle/Resources/translations/en.extended.json , the last translation key `listing_parent_php_class` has been added 10 days ago by this merge https://github.com/pimcore/pimcore/pull/3157.
This key is not in https://poeditor.com/join/project/XliCYYgILb

Thanks.

**Comment by brusch** [comment]
Fixed. Was caused by the change of the directory structure for Pimcore 5.4.
Thanks for the hint!

**Comment by Yivan** [comment]
Great, thanks. I updated french translations so they are 100% now.
