### ISSUE TITLE
Use of select box with all possible options while using different operators in Import/Export

### ISSUE THREAD

**Issue by psuhane** [pimcore/pimcore#3213]
It would be great if select box with all possible options available while configuring different operators(wherever applicable) in Import/Export. Following is an example

![op](https://user-images.githubusercontent.com/12061880/44033228-605039d8-9f27-11e8-97c2-cf216d1b254f.png)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
