### ISSUE TITLE
Show user id in user settings

### ISSUE THREAD

**Issue by cleggypdc** [pimcore/pimcore#322]
Somewhere around here

![image](https://cloud.githubusercontent.com/assets/1098498/11567898/49eaefec-99e1-11e5-9f95-f3a46060eba3.png)

(feel free to assign it to me)

**Comment by weisswurstkanone** [comment]
![image](https://cloud.githubusercontent.com/assets/6142086/11583908/58f307bc-9a5f-11e5-9c43-02f886338428.png)
![image](https://cloud.githubusercontent.com/assets/6142086/11583914/5ea3fd38-9a5f-11e5-970b-bca8769f12ec.png)

Would it be sufficient to show a tooltip when you hover over the treenode or tab ?

**Comment by cleggypdc** [comment]
Yeah sure :)

**Comment by weisswurstkanone** [comment]
Modified it a little bit to stay consistent. Tooltip in tree is still there but moved the stuff from the tab into the settings panel.
Build 3580

**Comment by cleggypdc** [comment]
Thanks Josef!
