### ISSUE TITLE
Installation fails due to missing app/config/parameters.example.yml

### ISSUE THREAD

**Issue by basgabrieljost** [pimcore/pimcore#3224]
### Expected behaviour 
executing ```php ./bin/pimcore-install``` on pimcore 5.4.2 starts and processes interactive installation successfully.

### Actual behaviour
Executing interactive installation with ```user@server$ php ./bin/pimcore-install``` results in the following (both questions are answered with "return"):

 MySQL Port (will be omitted if socket is set) [3306]:
 > 

 This will install Pimcore with the given settings. Do you want to continue? (yes/no) [yes]:
 > 

Running installation. You can find a detailed install log in var/installer/logs/prod.log

Creating config files...

  4/10 [===========>----------------]  40%

                                                                                                                        
 [ERROR] The following errors were encountered during installation                                                      
                                                                                                                        

 * Warning: file_get_contents(/php/app/config/parameters.example.yml): failed to open stream: No such file or directory
 
### Steps to reproduce  
Download pimcore-5.4.2.zip from Github, unzip it and run the above install-script.

**Comment by dpfaffenbauer** [comment]
you should not use pimcore/pimcore anymore to create new project, use the skeleton instead: https://github.com/pimcore/skeleton
