### ISSUE TITLE
[Glossary] Option to limit maximum possible replacements for each term

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#3230]

**Comment by piotrecky** [comment]
Limit parameter probably not working on the twig templates?

**Comment by dpfaffenbauer** [comment]
@piotrecky nope, as for twig this is handled differently: https://github.com/pimcore/pimcore/blob/master/lib/Twig/Node/GlossaryNode.php#L32

**Comment by piotrecky** [comment]
in the twig you can not pass this parameter :(

**Comment by dpfaffenbauer** [comment]
yep, thats what I was pointing out. @brusch plans to implement that for twig as well?
