### ISSUE TITLE
WorkflowGui : Action edit popup doesnot open ,display this js error Object.clone is not a function

### ISSUE THREAD

**Issue by AroraVaishali** [pimcore/pimcore#3233]
# Bug Report
I downloaded new version Pimcore5.4.2. Then I installed workflowgui by this command (composer require dpfaffenbauer/workflow-gui:^2.0)
  
### Steps to reproduce  
  1) Created new state , new statues then new action. When I click on edit button js error display :  [Show/hide message details.] TypeError: Object.clone is not a function
[Action edit popup doesnot [open]]
![workflowgui](https://user-images.githubusercontent.com/19402815/44263693-8867aa00-a23d-11e8-9f07-71f300767c7c.png)

### Code example 
```php
// your code
```

# Feature Request

**Comment by fashxp** [comment]
workflow-gui is not part of pimcore core. please use the corresponding repository for issure reporting https://github.com/dpfaffenbauer/WorkflowGUI
