### ISSUE TITLE
[Core] Refactor the architecture to allow core extensibility and easier maintainability

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#3235]
When working on big project with Pimcore a big problem in my opinion is that developer can not change core logic in a way which will allow easier core updates and preserve custom logic or custom fixes applied to the core. Excuse me if I am missing some improvements in PC5 in this direction but AFAIK there are no such. 

Here is one example. Pimcore provides class \Pimcore\Placeholder, than in this class I see opportunity to add enhancements or fix a bug in a given method. The current solution is to work at the original file which is non acceptable as it is core file which will be rewritten during update. Here is example of how Magento (ecommerce web system) solves this - provides XML API to instruct the system that for class alias "pimcore/placeholder" a new actual class will be used instead of \Pimcore\Placeholder, for example I may say use Website\Pimcore\Placeholder or MyCorePlugin\Placeholder and I will write this class to extend \Pimcore\Placeholder. When this placeholder class is needed it is gotten by class alias pimcore/placeholder. This allows to rewrite only a given method from the pimcore's core class. If the system gets upgraded the Website's class will be based eventually on the new version of the core's file. This approach still requires maintenance however much less, it is safer and easier to see what is changed. This has been designed for Magento 1 which is old software, and the system may be greatly improved I believe. For example by introducing PHP Traits in it. Pimcore is great system but seems behind from this perspective. Controller rewrites should be possible too, actually every part of the app should be. Another PHP web system I know of having good extensibility is OroPlatform. I do not have concrete suggestions but more like a request to work at this direction.

**Comment by dpfaffenbauer** [comment]
Symfony would already solve that by using services and decorate those services or even replace the class. The thing is that Pimcore has still a lot of old code that hasn’t been ported yet to symfony. If you need to change something with placeholders, you could create a PR todo so.

BTW: placeholders are actually extendable anyway. You can add different types like Text and Object already provided. For example I created one that uses the Symfony Expression Engine and allows more flexible ways for placeholder stuff.

**Comment by kanevbg** [comment]
> Pimcore has still a lot of old code

Yes, that is the main point. Pimcore uses dependency inject however not on all the classes which are created by pimcore are utilizing this, in fact AFAIK a lot are not. Enterprises will not wait or hope their needs will be implemented in the core and some will not allow to make the core improvements needed by the project to go public.

Thanks for commenting, you see that my point is architectural improvements not specifically the placeholders, they are just example to explain the kind of improvements I am imagining.

**Comment by brusch** [comment]
That's a continuous process that's going on already. It's a huge amount of work and as it has being said already, we're happy to accept contibutions.
