### ISSUE TITLE
Multiple versions of Pimcore running on same domain, different ports

### ISSUE THREAD

**Issue by tfarmer00** [pimcore/pimcore#3239]
Hello,

There seems to be an issue with running multiple copies of Pimcore on the same domain, with different ports.

We are using Docker and the admin interface gets confused when switching between admin screens. It seems to be cookie related and not storing a cookie prefix along with the cookie itself.

Opening the different admin sessions on different ports works across different browsers, so definitely appears to be cookie related.

Each copy of Pimcore has its own copy of the code and its own database.

**Comment by brusch** [comment]
Please use our forums for support! https://talk.pimcore.org

Pimcore uses standard Symfony sessions, the default save path is `%kernel.root_dir%/../var/sessions`, so I'd assume that this has something to do with your environment. 
https://github.com/pimcore/pimcore/blob/8e0898bd343c7a6473dd8086d661aeca560637b2/bundles/CoreBundle/Resources/config/pimcore/default.yml#L25

Check that this directory isn't shared between the containers or change the save path or handler to something different. 

See also: 
https://symfony.com/doc/current/reference/configuration/framework.html#session
