### ISSUE TITLE
Consider using Hoa\Compiler for Placeholder instead of regex

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#3242]
# Feature Request 
- [x] There is no existing issue regarding the same topic

## Feature description 
  
 Currently, the [`Placeholder` uses regex](https://github.com/pimcore/pimcore/blob/132933484df724e6d31f837efab7bdc07c6ffca2/lib/Placeholder.php#L185-L186) to match individual placeholders and their configuration. While this is simple, it's also quite fragile to get wrong and run into problems you can't easily debug if you're an end user (or even a developer).

Using some dedicated component like [`Hoa\Compiler`](https://github.com/hoaproject/Compiler) there exists an opportunity to define the grammar in a much more robust way, together with strict validation and interpretation. It might provide additional opportunities in the future.

**Comment by brusch** [comment]
Closed in favor of #7215
