### ISSUE TITLE
Trailing whitespaces in object field's titles cause translation problems

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#3243]
# Bug Report

For every class field's title an admin translation entry gets created automatically. When you add a trailing whitespace in the title of the data object class field, the whitespace is kept in the translation key. 
When you later on recognize your mistake and you remove the trailing whitespace from the class field's title, no new admin translation gets added. Moreover when you want to add the translation entry manually it is not possible as the entry with the traling whitespace in the key gets found. So you get stuck without translation.

### Expected behavior 
Whitespaces in automatically created admin translation keys for data object class field's titles should get trimmed.
  
### Actual behavior  
Admin translation entry can contain trailing whitespaces making it impossible to add a translation when trailing whitespace gets removed.
  
### Steps to reproduce  
1. create data object field with title "abc "
1. Clear temporary files cache
1. go to admin translations, search "abc" and add translation to it
1. open object and check if translation works
1. change class field's title to "abc"
1. Clear temporary files cache
1. go to admin translations, search "abc" -> only 1 entry exists
1. open object -> see that the field title does not get translated
1. go to admin translations, add "abc" manually and add translation to it
1. Clear temporary files cache
1. go to admin translations, search "abc" -> only 1 entry exists

**Comment by brusch** [comment]
@BlackbitNeueMedien can you maybe create a PR for that? 
Thanks in advance 😊

**Comment by brusch** [comment]
🏓

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
