### ISSUE TITLE
Display error while taking workflow action in object after update version

### ISSUE THREAD

**Issue by AroraVaishali** [pimcore/pimcore#3245]
# Bug Report
 
  
### Actual behavior  
  I updated Pimcore 5.1.3 to Pimocre5.4.2. My workflowgui and workflow module is working fine in Pimcore 5.1.3 but after update , I am taking action from one state to another state, it got this error -:
error performing action on this element
An exception occurred while executing 'SELECT id,type FROM users WHERE id in () AND id > 0 AND type IN ('role','rolefolder')': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND id > 0 AND type IN ('role','rolefolder')' at line 1
### Code example 
```php
// your code
```

# Feature Request

**Comment by brusch** [comment]
Support in the [forum](https://talk.pimcore.org)/[chat](https://gitter.im/pimcore/pimcore) please, thanks!
