### ISSUE TITLE
Add tips for memory limitation in the update documentation page

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3252]
Hello,

We just updated some project to the last 5.4.2 stable, all went ok.

Just for testing, after the update we have run `composer update`, it sends some memory errors.

```
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.
```

I think you should add as tips the command `COMPOSER_MEMORY_LIMIT=3G composer update` in this page  https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/Updating_Pimcore/index.html to prevent some users having problem.
(in our case we are on docker environment so maybe memory is more restricted).

Using `COMPOSER_MEMORY_LIMIT=3G composer update` we have no more memory errors.

**Comment by Yivan** [comment]
By the way, just to know and for reference for other user, why this memory limit is needed ? New Pimcore need more memory to manage postscript or packages ? The best would be not to have on rely on adding memory limit on composer command.

**Comment by brusch** [comment]
Well, we're trying to optimize what we can, but not all is in our hands ... you can try to open a ticket at Composer.

**Comment by brusch** [comment]
The memory limit is ONLY for composer, it has nothing to do with scripts, it's just to resolve the dependencies, as far as we could debug it.

**Comment by brusch** [comment]
Just for reference, it was mentioned already in the detailed upgrade notes: 
https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/Within_V5.html

**Comment by Yivan** [comment]
@brusch Yes i know this is not in your hand and this is a composer problem. I don't think open a ticket on composer will help as it is a very generic problem. I just wanted to be sure this was not on the pimcore side.

Composer already document this problem: https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors
They seem to said another way could be to increase php memory limit. **Maybe this could be done directly in the composer.json (so we don't have to prepend the composer command): please see https://getcomposer.org/doc/03-cli.md#environment-variables.**
```
Environment variables

You can set a number of environment variables that override certain settings. Whenever possible it is recommended to specify these settings in the config section of composer.json instead. It is worth noting that the env vars will always take precedence over the values specified in composer.json.
```

Or maybe on the pimcore side during upgrade (with something like `ini_set('memory_limit', '3072M');`).

Thanks for adding it to upgrading page too (yes i know it was in upgrade notes within v5, that is why i suggested adding it to the upgrade page too, as for us it helped us to upgrade and it work only with COMPOSER_MEMORY_LIMIT=3G).
