### ISSUE TITLE
Cache mismatch: Object is different than value in Database

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#3254]
There is a nasty cache issue we just found which is also a little bit hard to reproduce:

- create a simple object creation loop (about 100+ products)
- update and change a object property several times in the same loop cycle
- execute loop
- refresh backend grid view in short sequences (**WHILE** creation loop is running!)

Objects (sometimes) gets loaded with wrong property data. Watch the "walkthrough" [here](http://recordit.co/GYMgMFR0Ez).

```php
<?php

private function test()
{
    $old = new DataObject\Test\Listing();
    $old->setUnpublished(true);
    $old->load();

    foreach ($old->getObjects() as $obj) {
        $obj->delete();
    }

    for ($i = 0; $i < 150; $i++) {
        $ob = new DataObject\Test();
        $ob->setState('new'); //Only field the object has
        $ob->setKey(uniqid());
        $ob->setParent(DataObject::getByPath('/test'));
        $ob->save();

        sleep(0.5);

        $ob->setState('updated step1');
        $ob->save();

        sleep(0.5);

        $ob->setState('updated step2');
        $ob->save();

    }
}

```

You can also see this via the API, look for the Object that is displayed wrong in the grid and execute following code:

```php
<?php

$objectCache = DataObject\Test::getById(256);
$object = DataObject\Test::getById(256, true);

$output->writeln($objectCache->getState()); // wrong (cached) state
$output->writeln($object->getState()); // actual state from db
```

The major problem is, that those objects get further processed with wrong information and therefore sometimes get stuck in a certain workflow. In our case this sometimes happens with Orders, they are already in a "confirm" state, but Pimcore gives us a wrongly cached object which says "new" state and can therefore not be further processed cause of an invalid state.

We tried several things of clearing the cache during runtime or even re-caching it, but nothing helped. Only solution was to always force load Pimcore Objects by changing the `getById` function in `AbstractObject` to completely remove the `Cache::load` function.

**Comment by markus-moser** [comment]
I noticed quite similar problems with the cache too.

**Comment by brusch** [comment]
Related to #3254
