### ISSUE TITLE
[Objects] Error on object grid: call an undefined method named "getLanguage"

### ISSUE THREAD

**Issue by mbolka** [pimcore/pimcore#3260]
https://github.com/pimcore/pimcore/blob/bf4799782bb6d10ebe2adab85d9eb555ce0b84f9/bundles/AdminBundle/Controller/Admin/DataObjectHelperController.php#L621
When a user adds own, custom language by extending service pimcore.locale, he gets stuck with an error 

> Attempted to call an undefined method named "getLanguage" of class "Pimcore\Bundle\AdminBundle\Controller\Admin\DataObjectHelperController"

There is no method called getLanguage on DataObjectHelperController nor AdminController.

**Comment by brusch** [comment]
Sorry, that's too less information ... please provide us a detailed description of the problem as well as step-by-step instruction how to reproduce the issue.

**Comment by mbolka** [comment]
@brusch on the line 621 in DataObjectHelperController there is a call of method getLanguage which does not exist in this controller not its parent

**Comment by brusch** [comment]
@mbolka I see, thanks for clarifying  👍
