### ISSUE TITLE
Application Logger - delete instead archive log entries

### ISSUE THREAD

**Issue by deltatag** [pimcore/pimcore#3265]
It would be great to have the possibility to decide wether to archive or delete application log entries after a defined period e.g. 30 days.

https://github.com/pimcore/pimcore/blob/845b4690e3a73de80d8a9f7d922212d7d505db94/lib/Log/Maintenance.php#L138

The current settings under Pimcore => System Settings => Debug => Application Logger only allow to define an archive threshold in days.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
