### ISSUE TITLE
Classification store values are not inherited in Webservice API

### ISSUE THREAD

**Issue by mbolka** [pimcore/pimcore#3269]
### Expected behavior 
  Inherited classification store values are available when an object is requested through API
### Actual behavior  
  Inherited classification store values are not available when an object is requested through API

### Steps to reproduce  
  1. Create classification store group with some attributes.
![image](https://user-images.githubusercontent.com/31479820/44720826-5588a600-aac8-11e8-9036-5148049e90be.png)
2. Add a classification store attribute to a class.
3. Create an object with this classification group and fill values.
4. Create subobject that inherits all values.
![image](https://user-images.githubusercontent.com/31479820/44720894-8ff24300-aac8-11e8-8c96-4d310ebd24f2.png)

5. Request subobject through Pimcore API.
6. Classification store values are missing.
![image](https://user-images.githubusercontent.com/31479820/44720962-b617e300-aac8-11e8-9ead-eaa853959b28.png)

**Comment by Yivan** [comment]
If this is a wanted limitation, I think it should be documented on those both pages, so developpers can make the right choice when modeling objects with in mind using the webservice:

- https://pimcore.com/docs/master/Development_Documentation/Web_Services/index.html
- https://pimcore.com/docs/master/Development_Documentation/Objects/Object_Classes/Data_Types/Classification_Store.html

Thanks.

**Comment by fashxp** [comment]
https://github.com/pimcore/pimcore/issues/3411
