### ISSUE TITLE
Unable to open admin in IE11

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#3283]

**Comment by mysliwietzflorian** [comment]
Same problem as mentioned in issue #2989 by @solverat still persists.
Login with IE11 does not work anymore (here pimcore 5.5.4).

![image](https://user-images.githubusercontent.com/23225429/49077932-e80e2200-f23c-11e8-8f8a-087f0a1abc6b.png)

**Comment by brusch** [comment]
@mysliwietzflorian thanks for reporting! Unfortunately these are new issues, therefore I've created a new ticket for that: #3662
