### ISSUE TITLE
Cache\Runtime breaks Classes Rebuilder

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#3294]
After several hours of testing and failed deployments, we finally found a way to reproduce an class rebuild exception:

```bash
Message: "bin/console pimcore:deployment:classes-rebuild  -c -d --no-interaction" failed.
           
Exception: In AbstractMySQLDriver.php line 115: An exception occurred while executing 'ALTER TABLE `object_query_1` DROP COLUMN `field2`;'
```

## Preparation
- Create a class: `myClass`
- add two fields: `field1` (ObjectBrick) and `field2` (simple text field)
- create **TWO** ObjectBricks and add a simple textfield (naming doesn't matter) to each of them
- Connect both ObjectBricks to `myClass` => `field` so the Brick `classDefinitions` node should look like this:

```php
'classDefinitions' => 
  array (
    0 => 
    array (
      'classname' => 'myClass',
      'fieldname' => 'field1',
    ),
  ),
```
- Create a dummy DataObject and add a dummy ObjectBrick of each type

## Step 1
- Deploy to a different server / instance
- Check Instance: Class and ObjectBricks should be available 
- Everything should be fine

## Step 2
- Remove `field2` from `myClass` and save
- Deploy again to the instance / server
- Run `bin/console pimcore:deployment:classes-rebuild  -c -d` on your second instance

Exception from above should appear.

We're still not sure why this is happening (we're even unsure if it's necessary to create two bricks...) but we think it's because of the runtime cache combined with the `classDefinitions` in the ObjectBrick definition.

## Solution (sort of?)
Checkout this Line:

https://github.com/pimcore/pimcore/blob/ccc6d5f92b1fd3c55b09759db30c257352e00d1a/bundles/CoreBundle/Command/ClassesRebuildCommand.php#L139

Before that, we added the `\Pimcore::collectGarbage();` method. After that, the deployment finished properly.

**Comment by brusch** [comment]
Anyone else facing similar issues?

**Comment by solverat** [comment]
We just experienced it in other projects too. It also relies on the cache issue i've submitted previously (#3254) (we need a new label `nightmare` btw): If you're having some objectbricks connectet with some data objects and you're removing some fields within the deployment process (-> classes:rebuild) the error above appears. We copied the command and added the ` Pimcore::collectGarbage();` execution which did the trick. If you're ok with that i could provide a PR.

**Comment by solverat** [comment]
Follow-Up: As we talked about it with @brusch at the pimcore inspire event: Adding the collectGarbage method is not right way to go and seems to be rather a workaround than a real solution.

**Comment by davidmaes** [comment]
> Anyone else facing similar issues?

Yes, whenever you have a block in your dataobject, you can' t seem to upgrade from 5.5.4 to 5.6. It tries to delete the block column (for instance videos). And as the column is there before the upgrade, I can only conclude one of the migrations removes it, and then another migration tries to remove it again, which of course fails.

**Comment by dpfaffenbauer** [comment]
I can imagine this is happening cause PHP creates different references for the same thing. This happens when you use force-load. That will cause Pimcore to create a new instance and therefore PHP creates a new reference id. So when working with these objects, data runs apart and causes things like described.

I am not sure if thats the case here, but I faced that issue with Behat tests before.

**Comment by davidmaes** [comment]
> I can imagine this is happening cause PHP creates different references for the same thing. This happens when you use force-load. That will cause Pimcore to create a new instance and therefore PHP creates a new reference id. So when working with these objects, data runs apart and causes things like described.
> 
> I am not sure if thats the case here, but I faced that issue with Behat tests before.

Hi,

We have managed to solve it by disabling the migrations in the composer.json scripts section. After upgrading we did all the migrations through bin/console. By doing them one by one, everything went well. I think my problem isn't completely related to @solverat's. However, it can be fixed by running migrations in isolation.

**Comment by dpfaffenbauer** [comment]
Doing them one by one solves it, true. The problem here is how pimcore caches things into the runtime cache.

**Comment by solverat** [comment]
@brusch Ok, just struggled again, this time within the migration process (since we're using a "garbage collector" patched class-rebuild command, we had no more deployment issues until today...). Its quite easy to reproduce: 

## Steps to Reproduce
- Use Pimcore 5.4.4
- Create a class with an object brick connector
- Create an object brick, add some fields and connect it with the class
- Create one / two demo objects and add the object brick you've just created
- Update pimcore to 5.5.0 via `composer update`
- Migration fails at 20180907115436:

```bash
++ migrating 20180904201947

     -> Changing Database schema for new workflows. Please see upgrade notes for migration of data!
     -> INSERT IGNORE INTO users_permission_definitions VALUES('workflow_details');
     -> ALTER TABLE element_workflow_state DROP PRIMARY KEY
     -> ALTER TABLE element_workflow_state ADD workflow VARCHAR(100) NOT NULL, ADD place VARCHAR(255) NOT NULL
     -> ALTER TABLE element_workflow_state ADD PRIMARY KEY (cid, ctype, workflowId, workflow)

  ++ migrated (3.85s)

  ++ migrating 20180906142115

     -> Please note that object properties are not public anymore !!

  ++ migrated (43.97s)

  ++ migrating 20180907115436

     -> Please note that object properties are not public anymore !!
Migration 20180907115436 failed during Execution. Error An exception occurred while executing 'ALTER TABLE `object_brick_query_YOUR_BRICK_3` DROP COLUMN `exampleColumn`;':

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'exampleColumn'; check that column/key exists
```

## Reason

- [Version20180906142115](https://github.com/pimcore/pimcore/blob/master/bundles/CoreBundle/Resources/migrations/Version20180906142115.php) triggers a class rebuild
- [Version20180907115436](https://github.com/pimcore/pimcore/blob/master/bundles/CoreBundle/Resources/migrations/Version20180907115436.php) also triggers a rebuild
- RuntimeCache (packed with old versions of all available class definitions  - see ticket description) kicks in: error! (Not tested but I'm quite sure it would work: add ` \Pimcore::collectGarbage();` at the end of each migration...)

**Comment by dpfaffenbauer** [comment]
Best solution would be to either:
 1. Not cache class-definitions (not sooo good)
 2. Update the cache after save has been triggered. 
 3. Try to never loose track of the actual reference -> happens sometime with the runtime cache, so 2 objects, same Pimcore ID but two different object hashes (internal identifier for PHP to identify an instance)

**Comment by solverat** [comment]
@brusch, @dpfaffenbauer.

Okay, after hours of testing, i finally got it. In my tests I couldn't reproduce it with object bricks but with a block element... so yea... don't ask. The important thing is: It's reproducible. :)

Please download this zip file (Be sure docker is running): [issue-3294-bootstrap.zip](https://github.com/pimcore/pimcore/files/2836311/issue-3294-bootstrap.zip)

1. unzip it
2. enter directory
3. execute: `$ docker-compose up -d`
4. execute  `$ docker-compose exec web bash`

Pimcore Backend: http://localhost:2000/admin/

There are three scripts:

## 1. setup.sh
Execute this script to get a proper environment:

```bash
$ sh ./1_setup.sh
```
This script will:
- load pimcore ~5.4.0 skeleton
- install pimcore with user `admin/admin`
- execute `resources/boot.php`
  - install `Test` Class
  - add a dummy object based on `Test` class
- backup `public` directory in a tar file to allow rollback
- backup db to allow rollback

## 2. update.sh
Execute this script update pimcore to ~5.6.

```bash
$ sh ./2_update.sh
```
> This is the most "exciting" step!

This script will:
- modifiy `composer.json` => `pimcore ~5.6.0`
- execute composer update

**Important:** You should now see a migration error.

## 3. rollback.sh
Execute this script to restore step 1.

```bash
$ sh ./3_rollback.sh
```
This script will:
- remove `public`dir and restore it from the tar backup
- remove all db tables and restore it from backup

Now you're back at step one. This allows you to investigate the backend for example. Just repeat step two to execute the update again.

So - hopefully we'll bring some light into this weird behavior.

**Comment by dpfaffenbauer** [comment]
One solution would be for pimcore to use Doctrine DBAL Schema to create/update db layout for classes, sort of like CoreShop does with indexes: 

https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php#L84
https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php#L114

It doesn't really solve the Core Issue that the cache is invalid. But: it is a cleaner solution that doing it manually and sort of a workaround for that. Also: All the changes get executed at once, instead of one-by-one.

**Comment by solverat** [comment]
After more than two years I guess this is more than outdated. We're currently deploying with class-rebuild and executing migrations afterwards which is the best we can do and therefor I'm sending this old bastard to the grave!
