### ISSUE TITLE
Ecommerce Migration in Core Bundle

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#3295]
This Migrations here belong to the Ecommerce Framework but sit in the CoreBundle:

https://github.com/pimcore/pimcore/blob/master/bundles/CoreBundle/Resources/migrations/Version20180830122128.php#L18
https://github.com/pimcore/pimcore/blob/master/bundles/CoreBundle/Resources/migrations/Version20180830113528.php

The CoreBundle has no relation to the ecommerce-bundle, therefore this migration should be in the 
EcommerceBundle and not CoreBundle.

INMO the ecommerce-framework should be moved away into a separate package anyway, but thats a different story.

**Comment by brusch** [comment]
This was also a discussion internally, our conclusion was to create migration scripts within the core bundle for now for several reasons.

**Comment by dpfaffenbauer** [comment]
What are the reasons?

**Comment by kubaplas** [comment]
@brusch 
I don't have ecommerce bundle enabled and running composer update causes this:
`Migrating up to 20180830122128 from 20180724144005

  ++ migrating 20180830113528

     -> Updating field collection definition 'paymentState' - adding additional paymentState
     ->  ... nothing to do because field collection definition does not exist.
Migration 20180830113528 was executed but did not result in any SQL statements.

  ++ migrated (0.06s)

  ++ migrating 20180830122128

     -> Updating class definition 'OnlineShopOrder' - adding index to cartId
09:33:18 ERROR     [pimcore] Exception: There is no class with the name: OnlineShopOrder in /var/www/vendor/pimcore/pimcore/models/DataObject/ClassDefinition.php:222
Stack trace:
#0 /var/www/vendor/pimcore/pimcore/bundles/CoreBundle/Resources/migrations/Version20180830122128.php(18): Pimcore\Model\DataObject\ClassDefinition::getByName('OnlineShopOrder')`

**Comment by dpfaffenbauer** [comment]
@kubaplas yes, thats why I created this issue. This is confusing and totally makes no sense.

**Comment by brusch** [comment]
Made some optimizations to the migrations, should solve the issue with the warnings

**Comment by romainbessugesmeusy** [comment]
Hey @brusch it looks like the same issue happens today with the specific migration : 
https://github.com/pimcore/pimcore/blob/master/bundles/CoreBundle/Resources/migrations/Version20191230103524.php
Could you please look into it? Thank you and happy new year.

**Comment by brusch** [comment]
@romainbessugesmeusy Happy new year as well! 
Thanks for reporting the issue, fixed by 4b9b96a9e707e584a5168b24d95cd2b28b3b8ec5

**Comment by romainbessugesmeusy** [comment]
Thank you very much
