### ISSUE TITLE
Filter Service example is incomplete, missing key info

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#3297]
# Summary
I am a beginner at Pimcore but have basic Symfony knowledge, but I am unable to follow the documentation to complete the steps given in the documentation.

# Bug Report

Especially after reading through the Ecommerce documentation and trying to set up a working Filter service I have hit a wall and think the documentation is incomplete. Especially the parts about how to:
 1. Set up a fully configured filter
 2. Access the filter in the controller bundle.

For example, the code example:

```php
//get filter definition from document, category or global settings
$this->view->filterDefinitionObject = $filterDefinition;
```
...have no corresponding guide on how to get the definition from the global settings. Do I need to manually add it to the settings? Should it appear automatically when creating the FilterDefinition in the user interface? Where is it stored in the Document? Or how is it stored in the document? How to I access the Category? How to I connect the FilterDefinition to the Category?

Nowhere does the guide answer any of these question and I think that is key to me understanding the guide. I can't find answers to those questions anywhere on that page or elsewhere in the guide.

## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [x] This is not a security issue / vulnerability -> use [this form](https://pimcorehq.wufoo.com/forms/pimcore-security-report/) instead
- [x] Behavior is reproducible on http://demo-basic.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [x] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [x] There's no existing ticket for the same issue
- [x] Remove unused sections from below and this bullet points

### Expected behavior 
Fully documented behaviour for the [Filter service](https://github.com/pimcore/pimcore/blob/master/doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service.md)

I hope that my questions can aid you to improve the documentation here. It would be very appreciated!

**Comment by fashxp** [comment]
Actually this is nothing filter-service specific but standard pimcore stuff. 
Also have a look at the demo-ecommerce here: https://github.com/pimcore/demo-ecommerce/blob/master/src/AppBundle/Controller/ShopController.php#L57-L71

I added this link to documentation too...
