### ISSUE TITLE
DB storage data type for select / input

### ISSUE THREAD

**Issue by ctippler** [pimcore/pimcore#3298]
# Feature 

The "select" and "input" Data type use varchar(190) to store the values in the db. 
We often need to store a lot of data in the objects (we don't need to query them) but if we add a lot of input fields we get the "Row size to large" error from the db. 
Therefore it would be great if we can define the storage type in the editable - e.g store value of an input field as "TEXT" so the row size is not affected. Currently we could use a textfield, but this doesn't look that well in the Pimcore UI. 

Changing the ROW FORMAT to DYNAMIC/COMPRESSED is often a workaround, but wouldn't be requried.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
