### ISSUE TITLE
Back-office incompatible with Internet Explorer 10-11

### ISSUE THREAD

**Issue by SmashingQuasar** [pimcore/pimcore#3304]
Hello,

It is pretty straightforward. The back-office does not work with internet explorer 10 and 11.

In the [official documentation](https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/System_Requirements.html) it is written:

# Browser Requirements

Pimcore supports always the latest 2 versions of all 4 major browsers at the time of a release.

* **Google Chrome (Recommended)**
* Mozilla Firefox
* Microsoft Internet Explorer / Edge
* Apple Safari

I strongly suggest that you do not support IE at all as it is right now but you should however edit the official documentation to remove this reference has it will most likely backfire on us Pimcore partners when delivering a website to customer.

**Comment by dpfaffenbauer** [comment]
just got a call from a customer => same issue with Internet Explorer 10.

**Comment by Yivan** [comment]
I think documentation should be modified to make it more clear, maybe split IE / Edge on two line.
As i think IE10 is not supported, it will be:
```
Microsoft Internet Explorer : only IE11
Edge : last 2 versions
```

Make say too what is meaned by "latest 2 versions", minor ou major ? (i know each browser could be having is own versionning sheme, but it will help).

Purpose is because customer ask often on which computer they can use Pimcore, so information need to be more precise so we can confidently announce to them which one or at least what is meaned by 2 lasts versions.

Thanks!

**Comment by brusch** [comment]
fixed by b26802efe8463b49b4342a4473ae8cdea2635182

**Comment by Yivan** [comment]
@brush Thanks as always your fast reactivity!

Just you didn't answered to the meaning of "latest 2 versions", are they minor versions (so just the current and the just previous version, minor or not) or the 2 last major versions ?

Ex., if 2 last major versions at the today date it will give:
Chrome 68 & 67
Safari 11 & 10
Firefox 61 & 60
etc...
It is this way you mean "latest 2 versions"?

Thanks for bringing us some light ; )

**Comment by aarongerig** [comment]
@Yivan I think it‘s meant like this: http://browserl.ist/?q=last+2+versions
(have a look at Desktop browsers)

**Comment by brusch** [comment]
@aarongerig exactly (for Chrome, FF, Safari, Edge)

**Comment by Yivan** [comment]
@aarongerig great link!
Thanks with this we can have the last 2 versions without having to check each browser : )

@ brush, maybe adding the link to the documentation page will make clearly which version is supported for everyone who look for this information:

```
You can check versions supported with the following link:
http://browserl.ist/?q=last+2+Chrome+versions%2C+last+2+Firefox+versions%2C+last+2+Edge+versions%2C+last+1+IE+versions%2C+last+2+Safari+versions
```

**Comment by Yivan** [comment]
By the way I don't think mobile browser are supported by Pimcore ? Maybe adding it to the documentation too ?

**Comment by brusch** [comment]
@Yivan thanks for you input, done.
