### ISSUE TITLE
[Asset|Object|Document] Set all public properties to protected

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#3313]

**Comment by fashxp** [comment]
depends on the scope you are calling `get_object_vars` ...  see http://php.net/manual/en/function.get-object-vars.php

**Comment by brusch** [comment]
@dpfaffenbauer yep
I'd suggest a trait as a replacement for that. 

eg.: 

```php
<?php

namespace Pimcore\Model\Traits;

trait ObjectPropertyAccessTrait {

    public function getObjectProperties() {
        return get_object_vars($this);
    }
}
```

```php
class Asset extends Element\AbstractElement
{
    use Pimcore\Model\Traits\ObjectPropertyAccessTrait; 

    // ...
}
```

in Dao: 
```php
    public function update()
    {
            $asset = $this->model->getObjectProperties();
```

**Comment by brusch** [comment]
@weisswurstkanone
It seems that adding the following method to `\Pimcore\Model\AbstractModel` would be also sufficient an covers everything ... less code and easier ;-) 

```php
    // name of the method is TBD
    public function getObjectProperties() {
        return get_object_vars($this);
    }
```

**Comment by dpfaffenbauer** [comment]
Why not use property accessor instead? Sort of like Doctrine does?

**Comment by brusch** [comment]
@dpfaffenbauer because the above solution is just 3 LOC and does it's job, or not?

**Comment by dpfaffenbauer** [comment]
@brusch right
