### ISSUE TITLE
Asset Drag&Drop upload Specific Destination of Asset

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#3331]
# Feature Request 

Is ist possible to choose the destination of an Asset which is uploaded via Drag&Drop?

After a Image is dropped to an Imagefield a Modal appears wehre you can add the Asset Folder to save the Image.

![asset_upload](https://user-images.githubusercontent.com/1086343/45742066-66c16000-bbf9-11e8-85ee-5d71556fd797.png)

Add a Specific Setting in the ClassDefinition

![asset_upload2](https://user-images.githubusercontent.com/1086343/45742735-ebf94480-bbfa-11e8-9626-12822f6c4738.png)

Add a Specific Setting in the ImageEditable

````
<?= $this->image("myImage", [
    "title" => "Drag your image here",
    "width" => 200,
    "height" => 200,
    "thumbnail" => "contentimages",
    "manualUploadDestination" => true
]); ?>
````

**Comment by brusch** [comment]
Fixed by a5425ac345b82d704924d7d2f33ff406a2937eae
