### ISSUE TITLE
Using upload bouton on multihref fields don't run path formater the second time.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3344]
When using upload bouton on multihref fields, it don't run path formater the second time.

How to reproduce:
- add a field "multihref with metadata" to a class object
- create a cusom path formater for it (https://pimcore.com/docs/5.x/Development_Documentation/Objects/Object_Classes/Class_Settings/Path_Formatter.html#page_Path-Formatter), like displaying the current date for our testing purpose
- create an object of this class
- use the "upload" button of this field to add an image
- current date will be ok
- use again the "upload" button for upload a new image
- **it won't go throuh the path formater and ignore it**, the normal path is displayed.

We have seen in JS console that `/admin/element/get-nice-path` is only called the first time, maybe the problem is here and JS sould be corrected so it is called the second time too.

Feel free to ask any precision.

Thanks.

**Comment by Yivan** [comment]
@weisswurstkanone Thanks for providing this fix, as always very reactive ; )

Just do you check if other fields have this problem too, i think to: `href` and `multihref` (without metadata) ?
Thanks

**Comment by weisswurstkanone** [comment]
also fixed for multihref, href was fine already
