### ISSUE TITLE
Add a Custom Event on Asset Drag&Drop upload

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#3358]
# Feature Request 

Add an Event when a Image is Uploaded via Drag&Drop

**Comment by fashxp** [comment]
for what usecase?

**Comment by weisswurstkanone** [comment]
let's say you want to upload an asset for a news object which lives in /news/2018 then probably you want to save the asset to the  /news/2018 asset folder

**Comment by weisswurstkanone** [comment]
yep, but the related one provides a user interface whereas this one decides it programmatically
