### ISSUE TITLE
Objects with metadata in object brick does not work if a group is set.

### ISSUE THREAD

**Issue by SEYentl** [pimcore/pimcore#3362]
### Expected behavior 
Object with metadata can be saved whilst the object brick is in a group. 
  
### Actual behavior
The pimcore backoffice stops working and needs to be refreshed in order to work again. 
  
### Steps to reproduce  
  
On the online demo:
1. Go to Settings>Data Objects> Objectbricks.
2. Add an objectbrick (E.g. ArticleCollection)
3. Set the group for the objectbrick (E.g. Articles)
4. Add a panel + the data object "objects with metadata".
5. Set a name for the "objects with metadata" (E.g. articles)
6. Set the allowed class to "News" and visible field to "title" 
7. Add an extra column "quantity" with type number.
8. Add the object brick to the blogarticle class.

![pimcore bug](https://user-images.githubusercontent.com/40569826/45865467-ebd58200-bd7d-11e8-9764-d42fc429312f.gif)

**Comment by weisswurstkanone** [comment]
many thanks for the excellent instructions on how to reproduce this! fixed in the next build.
