### ISSUE TITLE
SELECT ... LOCK IN SHARE MODE instead of SELECT ... FOR UPDATE for improved performance

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#3365]
- check if there are possible issues when using `LOCK IN SHARE MODE`

See also: https://dev.mysql.com/doc/refman/5.6/en/innodb-locking-reads.html

**Comment by weisswurstkanone** [comment]
also check if 
$oldData = $this->db->fetchRow('SELECT * FROM object_query_' . $this->model->getClassId() . ' WHERE oo_id = ?', $this->model->getId());
has to take as well

**Comment by markus-moser** [comment]
The inheritance helper does not use any lock too although it uses the data for updates. Might this be the reason why the data in the query table is sometimes wrong?

**Comment by brusch** [comment]
@markus-moser that's a good point ... the existing implementation seems to lock only the direct parent. 
@weisswurstkanone so we should introduce that for the `InheritanceHelper` as well.

**Comment by brusch** [comment]
@markus-moser @weisswurstkanone It seems that we don't need the suffix `FOR UPDATE` for the `SELECT` statements in the `InheritanceHelper`. The values which are selected to update the query table of children are always selected from the query table of the current data object, which is locked anyway, because it get's updated, see: https://github.com/pimcore/pimcore/blob/4c986d60d890898e466533a21dfd29bde2acb9f6/models/DataObject/Concrete/Dao/InheritanceHelper.php#L517

So in my opinion it's not necessary to lock any further rows / objects.
