### ISSUE TITLE
[Asset] Restricting public asset access without breaking the admin app

### ISSUE THREAD

**Issue by alexpozzi** [pimcore/pimcore#3383]
# Feature Request 

## Feature description 
Since most of my company's customers are using PimCore as a PIM, and they don't need to expose any public asset, I always restrict public asset access as described in your documentation (https://pimcore.com/docs/5.x/Development_Documentation/Assets/Restricting_Public_Asset_Access.html).
All the assets are accessed from the admin app and accesses to them are regulated by roles.
I never had any problem with images and videos, since the admin app doesn't use the "public asset url" in any of their panels.
The problem comes when I try to preview pdfs assets (and other document assets) because I found out that in this case the admin app is actually using the "public asset url" resulting in an access denied response.

I already fixed the issue adding a rewrite rule (for pdfs only) and a custom controller action (which check the access to the desired asset and returns it) but it would be nicer that the admin app wouldn't use any "public asset url" in order to be able to secure assets in an easier and standard way.

Does this feature request make sense to you?
If you want I can work on a PR.

Best Regards,
Alessandro

**Comment by alexpozzi** [comment]
You are totally right!
I searched for other similar issues but I probably used the wrong keywords.

Thanks!

**Comment by brusch** [comment]
Yep, that should be solved already.
