### ISSUE TITLE
RGBA Color hex field uneditable

### ISSUE THREAD

**Issue by dkidd** [pimcore/pimcore#3384]
# Feature Request 
Currently there's no way to enter a hex value into the RGBA Color object datatype field. R,G, and B values can entered, but the HEX field is read-only.  

## Feature description 
The RGBA field is otherwise great, but not being able to copy and paste values into it is a serious shortcoming. Even just being able to enter a six digit hex code would be a huge improvement.

**Comment by dkidd** [comment]
I'm not familiar enough with ExtJS and Pimcore's use of it to be comfortable making a pull request, but here are some code snippets that someone might be able to use:

```
// in colorpicker-overrides.js
Ext.override(Ext.ux.colorpick.ColorUtils, {
            hex2rgb: function(hex){
                hex = hex.replace(/^#/, '');

                var parts = hex.match(/[a-f\d]{2}/ig);

                if( parts === null || parts.length !== 3){
                    return null;
                }

                return {
                    r: parseInt(parts[0], 16),
                    g: parseInt(parts[1], 16),
                    b: parseInt(parts[2], 16)
                };
            }
        });
```

```
// In colorpicker-overrides.js around line 124 (after me.items has been set)

// Make the HEX field editable (see ext/ux/colorpick/Selector.js line 206)
// This is really smelly, but it seems like overkill to override the whole getMapAndHexRGBFields method
me.items[0].items[1].items[0].readOnly = false;
```

And the last change is to `Ext.ux.colorpick.SelectorModel`, but I'm not sure what the best way to do this is. The HEX field setter, defined in the formulas in ext/ux/colorpick/SelectorModel.js at line 46, could be:
```
set: function (hex) {
    var rgb = Ext.ux.colorpick.ColorUtils.hex2rgb(hex);
    if( rgb !== null ){
        this.changeRGB(rgb);
    }
}
```

**Comment by weisswurstkanone** [comment]
Could you please give my commit a try?

**Comment by dkidd** [comment]
This works for me.

**Comment by weisswurstkanone** [comment]
thx!
