### ISSUE TITLE
Twig trans extension is giving the wrong translation for Shared Translations into a simple PrintContainer

### ISSUE THREAD

**Issue by gorisken** [pimcore/pimcore#3385]
There is a problem when you use the twig trans extension in combination with a simple PrintContainer.
If you set the PrintContainer to English for example and 1 of the underlying documents to another language, for example French.

All the data coming out of a related data object is rendered in English. All the data coming out of a shared translation will be in the language of the underlying document, French in this example, instead of the language of the PrintPage, English in this example.

**Comment by brusch** [comment]
We had to revert the changes regarding this issue, since it breaks other functionality, see #3731

**Comment by brusch** [comment]
Normally this shouldn't be the case anyway .. since this should be handled by `\Symfony\Component\HttpKernel\EventListener\TranslatorListener()` 

Just tried to reproduce it without this changes (with PHP templates) but wasn't able to do so...

**Comment by brusch** [comment]
@gorisken maybe you can create a reproducible case for us, thanks!
