### ISSUE TITLE
Error share configuration, user permission

### ISSUE THREAD

**Issue by brainsbucket** [pimcore/pimcore#3388]
Hi,

It is not possible to use the "share configuration" permission without the "user" permission, this generate an error when you try to open the "grid option" of a object folder.

To reproduce simply create a new user with the permission : 
- object
- share configurations

The exception text : 

> Status: 403 | Forbidden
URL: /admin/user/get-roles?_dc=1538035062365
Method: GET
Message: Attempt to access users, but has no permission to do so.

**Comment by markus-moser** [comment]
Same as #3354 - right?
