### ISSUE TITLE
Ckeditor window persists even after clicking the Source option

### ISSUE THREAD

**Issue by amarjeet6694** [pimcore/pimcore#3389]
When **WYSIWYG** editable is used and then on the ck-editor option I try to enter my HTML code after clicking **Source** option, the ckeditor still persists. It should be hidden.

The error is reproducible at https://demo-advanced.pimcore.org/admin

![ckeditor-error](https://user-images.githubusercontent.com/29056383/46189900-ae896b00-c30e-11e8-8b36-20d67118e74d.png)

**Comment by matthiashamacher** [comment]
Not reproducible anymore. Please close.

**Comment by brusch** [comment]
@matthiashamacher thanks a lot for checking! 🙏
