### ISSUE TITLE
Keyboard combination STRG+ALT+Q wants to enable dev mode instead of inserting @

### ISSUE THREAD

**Issue by leuchtdiode** [pimcore/pimcore#3390]
# Bug Report
 
  
### Expected behavior 
When I hit "STRG+ALT+Q" as admin to insert an @ sign in any input field, pimcore is asking me if I really want to enable the dev mode. So the only possibility to add an @ sign is "ALT-GR + Q". Is this really on purpose?
  
### Actual behavior  
Dev mode wants to be enabled
  
### Steps to reproduce 
Login to your live demo, open any document, set the cursor into any input field and hit "STRG+ALT+Q"
  
### Code example 
```php
// your code
```

# Feature Request

**Comment by brusch** [comment]
@dvesh3 we should choose a different default key combination

**Comment by dvesh3** [comment]
@brusch how about explicitly setting ctrl=false? as current combination for clear all cache is *atl+Q* but it is ignoring ctrl.

**Comment by brusch** [comment]
@dvesh3 yep, that should work, afaik

**Comment by aarongerig** [comment]
Just a heads up: On my keyboard I have to hit `Option + G` in order to add `@` and that opens up the Glossary, which is quite annoying TBH.

**Comment by dvesh3** [comment]
@aarongerig Glossary keyboard shortcut updated to `Option+Shift+G`.. Cheers!!

**Comment by aarongerig** [comment]
@dvesh3 Thank you, appreciate it!
