### ISSUE TITLE
Associated Assets in a Object Localized Block Wysiwyg will not be updated

### ISSUE THREAD

**Issue by albertmueller** [pimcore/pimcore#3392]
### Expected behavior
when i rename a asset folder, then all associated assets within a wysiwyg should be updated.

### Actual behavior
it shows in frontend the old link and on click it ends up in 404

### Steps to reproduce
the issue can reproduce in the current version 5.4.4, for a reproducible step:
1. upload a asset in a folder like "/digital-essentials/research/insights"
2. create a new class or update someone with following tree/fields:
- panel
-- localizedfields
--- wysiwyg (this works)
--- block
---- wysiwyg (here is the issue)
3. write in both wysiwyg's in a dummy object a word like "test" and associate it via drag&drop with the uploaded asset, save the object
4. rename the asset folder insights to "thisisatest", save the folder
5. reload the object in frontend then u will see that the associated asset in the first wysiwyg was updated, but in the second wysiwyg within the block element it shows u the old path
6. if u reload the object in backend it shows sometimes the new link and when i save the object again it works, but in normal use case i doesn't want to open and save all objects again :)

**Comment by matthiashamacher** [comment]
Not reproducible anymore. Please close.

**Comment by brusch** [comment]
Thanks for the feedback!
