### ISSUE TITLE
Asset and Document List foreach-Iteration-Bug

### ISSUE THREAD

**Issue by bruenner-elements** [pimcore/pimcore#3393]
When iterating over a list of assets or documents without using `load`, then there are more elements within this list than selected. 

For instance:

`$assetList = Asset\Image::getList(); // max count 10 for instance`
`$assetList->setCondition("id in (?)",[213]);`
`foreach($assetList as $fetchAsset){`
`   var_dump($fetchAsset); // there is more than one output`
`}`

But this actually works:

`$assetList = Asset\Image::getList(); // max count 10 for instance`
`$assetList->setCondition("id in (?)",[213]);`
`foreach($assetList->load() as $fetchAsset){`
`   var_dump($fetchAsset); // there is only one output`
`}`

Referenced Issue: #1723

**Comment by youwe-petervanderwal** [comment]
This issue old and no longer can be reproduced (tested Pimcore 10.5.2), I think it can be closed

**Comment by dvesh3** [comment]
@youwe-petervanderwal thanks for confirming.
