### ISSUE TITLE
Do not pass parameters by default in Staticrouter-Router

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#3394]
# Bug Report
The Symfony router interface (generate) and the StaticRouter interface (with reset parameter) are not compatible. I think thus, when Pimcore was upgraded to V5, the followin line in the static router has been added:

 Pimcore\Routing\Staticroute\Router.php
```php
$reset  = isset($parameters['reset']) ? (bool)$parameters['reset'] : false;
```
In my opinion this is very dangerous, as arbitrary parameters that are added by the user to the URL are passed through, without the awareness of the developer.
  
### Expected behavior 
Never automatically append parameters that are not explicitly defined to a route!

### Actual behavior  
Arbitrary parameters are added.
  
### Steps to reproduce  
https://www.my-project.com/?_prefix=insecure-parameter....

```php
router = \Pimcore::getContainer()->get('router');
//route should be a static route.
$url = $this->router->generate('app_shop_product_overview', [
          'slug' => $object->getSlug($locale) ? : File::getValidFilename($object->getName($locale)),
]);
 ```

# Feature Request 
Can we change the line so that reset by default is always true in Pimcore 6?
Optionally we could define a global parameter (parameters.yml) where it is possible to disable that behavior for a specific project.

**Comment by dpfaffenbauer** [comment]
IMO: Be compatible with Symfony, and don't provide any other configuration parameters. The developer is responsible for what he wants to append to the URL, not Pimcore.
