### ISSUE TITLE
Deleting Notes

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#3396]
Currently it's not possible to delete notes. Are there any reasons for that? I could imagine that it's connected with important workflow / system / commerce notes which are not allowed to delete. But maybe we could allow the deletion of notes made by non-system users?

**Comment by dpfaffenbauer** [comment]
Maybe with another parameter: `locked` or something like that

**Comment by KatrinAckermannEk** [comment]
I would like to see this enabled/fixed, too. As well as the possibility of editing a note after it has been made by a non-system user.

**Comment by brusch** [comment]
- only by admin users 
- possibility to `lock` a note -> this should be the default (BC) 
- notes which are created manually using the admin interface are set to `lock = false` so that they can be deleted

**Comment by alexthunder3** [comment]
Is there at least some sort of cleaning job that is part of maintenance which I've missed? I haven't found a section for it in the system settings (as there is for objects/ documents versions), the php API doesn't give me any methods for deleting, the documentation doesn't even mention it. So the only way to keep these in check for now is to make your own query command?

**Comment by dvesh3** [comment]
Fixed by #13206
