### ISSUE TITLE
Could you add JSON_PARTIAL_OUTPUT_ON_ERROR option to json_encode to avoid "Recursion detected" error

### ISSUE THREAD

**Issue by imilyukov** [pimcore/pimcore#3397]
Could you add JSON_PARTIAL_OUTPUT_ON_ERROR option to json_encode to avoid "Recursion detected" error

https://github.com/pimcore/pimcore/blob/be371cb8c55fb84f57f48647bdf0117859b42c1b/lib/helper-functions.php#L160

**Comment by brusch** [comment]
In which case does this happen? 
Please provide a full example how to reproduce the problem - thanks!

**Comment by imilyukov** [comment]
Hi @brusch ,
It happens when I try rename a document key in admin panel and the target for renaming document is opened in preview mode.
Many thanks

**Comment by brusch** [comment]
@dvesh3 can you please try to verify that? 
If this is really the case, we should trying to avoid the problem. Imho using `JSON_PARTIAL_OUTPUT_ON_ERROR` would be just a dirty hack.

**Comment by dvesh3** [comment]
Hello @imilyukov I'm not able to reproduce the problem. 
Could you please share more details like which version of Pimcore has this issue? and exact steps to reproduce the problem? Thnx!

**Comment by brusch** [comment]
Closed due to inactivity.
