### ISSUE TITLE
S3 as storage for Assets

### ISSUE THREAD

**Issue by ajaygarga** [pimcore/pimcore#340]
We are currently using PIMCore (3.0.4) as backend with our own custom UI. Since our application is running on AWS, it is ideal to have the assets (images, pdfs etc..) stored in S3 fronted with CloudFront and use http link to these files directly in the UI. Currently we identified to mount S3 as File system using S3FS-Fuse and use PIM core to use the mounted file system. Instead, is there a way to plugin a new storage for assets wherein we write a custom plugin to write and read files to and fro from S3?

Also is there a ticket to support S3 as file store for Assets in the future?

**Comment by brusch** [comment]
No, there's currently no plugin for a seamless S3 integration we know of. Suggestions & pull requests are of course welcome ;-) If you're interested in contributing this feature, please let me know.

**Comment by ajaygarga** [comment]
Yes I am interested in contributing to this feature.

**Comment by cmaerz** [comment]
Pretty sure you can just mount your s3 bucket and then create a symlink. (not tested)
http://tjstein.com/articles/mounting-s3-buckets-using-fuse/

**Comment by ajaygarga** [comment]
Yes there are ways to mount S3 and create a symlink. But I feel a storage plugin to use S3 for file store using AWS SDK could be a cleaner solution. So what I feel is either we need a way to plugin a custom plugin to be used a file store (so that anybody can write their custom plugin) or we can have an out of box support for S3.

**Comment by cleggypdc** [comment]
An S3 plugin can easily be integrated using Pimcore plugins, for instance we have a basic asset sync plugin which hooks into asset.postAdd/Update/Delete event, syncing them to an S3 bucket, that way we always have a local copy of the asset in the pimcore admin, and can use helpers to retrieve the S3 link.

It would be interesting to see the performance implications of directly rewriting assets using s3fs.

**Comment by brusch** [comment]
I also think that this is a perfect use-case for a plugin. 
If there's anything we can improve in the core to better support this, let us know! :-)

**Comment by jbelke** [comment]
Has this feature path begun yet? 
Self-healing storage with compatible s3 objects would be great, I would be interested in contributing to accommodate B2 and Minio as well CDN support.

**Comment by brusch** [comment]
@jbelke 
See: 
https://www.pimcore.org/docs/latest/Installation_and_Upgrade/System_Setup_and_Hosting/Amazon_AWS_Setup/Amazon_AWS_S3_Setup.html

AWS / Microservices in general: 
https://www.pimcore.org/docs/latest/Installation_and_Upgrade/System_Setup_and_Hosting/Amazon_AWS_Setup/index.html

**Comment by brusch** [comment]
Issue was already closed ;)
