### ISSUE TITLE
Symfony PHPUnit Bridge does not find any tests

### ISSUE THREAD

**Issue by podarcis** [pimcore/pimcore#3402]
# Bug Report

Main issue: Following the guide at [Docs Testing](https://pimcore.com/docs/5.x/Development_Documentation/Development_Tools_and_Details/Testing.html) the binary `vendor/bin/simple-phpunit` (Symfony's PHPUnit Debug Bridge) does not find any tests. Any ideas?

Other issues, for which I might create a PR:

- For the standalone example the path `bootstrap="../../vendor/autoload.php"` seems to be incorrect.
- Typo in [Bootstrap::boostrap()](https://github.com/pimcore/pimcore/blob/v5.4.4/lib/Bootstrap.php#L118) and in examples
- [Symfony docs](https://symfony.com/doc/3.4/components/phpunit_bridge.html) tell it's recommended to use the very latest stable major version, as it's designed to be compatible.

  
### Expected behavior 

Following the example (both standalone and Pimcore) the wrapper `vendor/bin/simple-phpunit` should execute configured tests.

### Actual behavior  

No tests are executed:
```
$ vendor/bin/simple-phpunit 
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Time: 42 ms, Memory: 12.00MB

No tests executed!
```

Running the test explicitly:
```
$ vendor/bin/simple-phpunit tests/CalculatorTest.php 
Class 'tests/CalculatorTest' could not be found in '/path/to/pimcore5/tests/CalculatorTest.php'.
```

### Steps to reproduce  

- Create a fresh Pimcore5 installation and follow the steps on (https://pimcore.com/docs/5.x/Development_Documentation/Development_Tools_and_Details/Testing.html)
- Correct the `bootstrap` path to `vendor/autoload.php`
- Run `vendor/bin/simple-phpunit` -> No tests executed
- Run `vendor/bin/phpunit` -> Tests are executed

  
When I create a Symfony 3.4 project from scratch, the tests are executed as well:
- `composer create-project symfony/website-skeleton symfony3 "^3.4"`
- `composer require --dev "symfony/phpunit-bridge:*"`
- Create Calculator class and test
- Run `vendor/bin/simple-phpunit` -> Tests are executed:
```
$ vendor/bin/simple-phpunit 
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Testing Project Test Suite
........                                                            8 / 8 (100%)

Time: 25 ms, Memory: 4.00MB

OK (8 tests, 8 assertions
```

### Environment/ versions
```
$ bin/console -V
Pimcore v5.4.4 (kernel: app, env: dev, debug: true)

$ php --version
PHP 7.1.17-0ubuntu0.17.10.1 (cli) (built: May  9 2018 17:28:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.17-0ubuntu0.17.10.1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

**Comment by SmashingQuasar** [comment]
Hello,

We tried to implement PHPUnit following Pimcore official documentation and ran into the exact same problems.
Another thing to fix in this issue is the version of PHPUnit. This seems to use PHPUnit 5 which is no longer supported and deprecated. PHPUnit should be updated to at least PHPUnit 7 considering PHPUnit 6 won't be supported as of Feb '19.

**Comment by Yivan** [comment]
Hi !
@podarcis I got the same problem. It comes from the fact that phpunit is already installed as phpunit 5 in vendor directory and registered in the autoloader.
It makes conflict with the phpunit installed by phpunit-bridge (simple-phpunit).

simple-phpunit install its own phpunit in vendor/bin/.phpunit. You will see version number installed directly in this directory.
But as vendor/phpunit/phpunit is registered in autoloader, when you run the test case it use this one, which is phpunit 5. Phpunit 5 is no more supported and reached EOL.
The code provided in the Pimcore documentation is for phpunit 6 or 7.

So, the best solution is to use phpunit 7 (as 6 is bout to reach EOL in few month: https://phpunit.de/) (if you are on php7.0 use phpunit 6):
- First, you unregister vendor/phpunit directory by excluding the classmap in the project composer.json. In the autoload section add:
```
    "exclude-from-classmap": [
      "vendor/phpunit
    ]
```
and run an update of the autoload, on the project root directory: `COMPOSER_MEMORY_LIMIT=3G composer dump-autoload --optimize`
- Force simple-php to install and use phpunit 7: edit phpunit.xml.dist (or phpunit.xml if you use this one) to add:
```
    <php>
	<env name="SYMFONY_PHPUNIT_VERSION" value="7.4" />
    </php>
```

In the next run of simple-phpunit phpunit 7.4 will be installed in vendor/bin/.phpunit.

It should works now ; )
Tips: if you run simple-phpunit from transversal directory (like `../simple-phpunit --configuration ../phpunit.xml.dist` i found a strange bug making it ignoring SYMFONY_PHPUNIT_VERSION so if it happens you can add it before the command by running: `SYMFONY_PHPUNIT_VERSION=7.4 ../simple-phpunit --configuration ../phpunit.xml.dist`

Hope it helps!

**Comment by fashxp** [comment]
any updates of the docs are be appreciated!

**Comment by Yivan** [comment]
@fashxp Sure, I will make a PR with usefull informations so people can get in on more easily.

**Comment by podarcis** [comment]
@Yivan Thanks. You might want to include attached two commits I've done yesterday in your PR.

**Comment by Yivan** [comment]
Yes sure, it is documentation modification ? How can i get the commits ? (or if just one/two files modified you can join the file in a comment here).

**Comment by podarcis** [comment]
@Yivan Yes, it's related to this issue. Since you offered doing the docs improvement I don't wanted to risk a conflict w/ your modification.

You could cherry-pick the commits from podarcis/pimcore@30d44ef77ed0 and podarcis/pimcore@5ecaa2c1c03.

Thanks!

**Comment by podarcis** [comment]
Hi @Yivan, any updates on this? Do you want me to update the documentation?

**Comment by Yivan** [comment]
Sorry pretty busy those last days! I haven't finish setting up the CI and i wanted to update documentation when it's done.

@podarcis Sure if you have time to update the documentation you are welcome.
On my side the codeception part was wroking great. The glitch was on the first part of the documentation to set phpunit alone.
In fact there is problem when phpunit AND phpunit-bridge are installed together. phpunit-bridge has his own phpunit embedded, but if phpunit package is already installed separatly class will be loaded from this one... and if phpunit version are not the same it can lead to problem.

One way would be to do:
```
COMPOSER_MEMORY_LIMIT=3G composer remove --dev phpunit/phpunit
COMPOSER_MEMORY_LIMIT=3G composer require --dev "symfony/phpunit-bridge:*"
```
And set phpunit-bridge to use phpunit 6 or 7 (phpunit 5 don't work with Pimcore exemple in the documentation) : https://symfony.com/doc/current/components/phpunit_bridge.html#modified-phpunit-script

The other way would be to only use the classic php unit and not install phpunit-bridge, for exemple for phpunit 7:
```
COMPOSER_MEMORY_LIMIT=3G composer require --dev phpunit/phpunit ^7
```

If you want you can update the documentation with those information if it work good for you.
Thanks!

**Comment by podarcis** [comment]
I updated the docs via #4171, reflecting some of the information @Yivan provided (thanks!). I'm closing this issue.

**Comment by Yivan** [comment]
Thanks a lot @podarcis I didn't had time to propose those change to the docs (actually our CI implementation was in standby, i was waiting to finish it to mk a PR to Pimcore). If i found some others things to mention in the documentation i will make  PR but yours seems perfect, thanks !
