### ISSUE TITLE
Objectbrick cannot be saved if class was renamed

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#3406]
- Create a class with an objectbrick
- Create an Objectbrick referencing the class and the fieldname
- Rename the Class
- You cannot save the objectbrick anymore

The 'Allowed Class' field in the objectbrick definition is empty. Saving the objectbrick causes an error in https://github.com/pimcore/pimcore/blob/master/models/DataObject/Objectbrick/Definition.php#L126 because $class is null.

![image](https://user-images.githubusercontent.com/7206334/46293321-7181da80-c593-11e8-8191-7806c3c70a91.png)

**Comment by ultramegatom** [comment]
Manually editing the classname in the Objectbrick definition file and re-saving it works.

**Comment by ultramegatom** [comment]
The 'Objects (Non-Owner)'-Datatype also seems to have problems when the 'Owner class' was renamed.

**Comment by weisswurstkanone** [comment]
@ultramegatom , please create a separate ticket for the non-owner issue
