### ISSUE TITLE
[Webservices] Do not deliver inherited values

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#3411]
currently it delivers inherited values except of classification store.

**Comment by fashxp** [comment]
can we find out how long it has been wrong?

**Comment by dpfaffenbauer** [comment]
I guess thats difficult to do. Guess the best way is to test it with a existing Pimcore 4 installation.

I just checked the RestController in Pimcore 4 and there is no disabling of inheritance there.

**Comment by fashxp** [comment]
in pimcore 4 inherited values were definitely not delivered

**Comment by weisswurstkanone** [comment]
mhm ... PimcoreContextListener ($context would be "webservice" in our case) ... explicitly enables it

    protected function initializeContext($context)
    {
        if ($context == PimcoreContextResolver::CONTEXT_ADMIN) {
            \Pimcore::setAdminMode();
            Document::setHideUnpublished(false);
            DataObject\AbstractObject::setHideUnpublished(false);
            DataObject\AbstractObject::setGetInheritedValues(false);
            DataObject\Localizedfield::setGetFallbackValues(false);
        } else {
            \Pimcore::unsetAdminMode();
            Document::setHideUnpublished(true);
            DataObject\AbstractObject::setHideUnpublished(true);
            **DataObject\AbstractObject::setGetInheritedValues(true);**
            DataObject\Localizedfield::setGetFallbackValues(true);
        }
    }

**Comment by weisswurstkanone** [comment]
IMO, behavior should be the same as for CONTEXT_ADMIN

**Comment by markus-moser** [comment]
related to #175

**Comment by dpfaffenbauer** [comment]
what speaks against a query parameter to enable/disable inheritance?

**Comment by fashxp** [comment]
I think it is the only option, since the behavior is since pimcore 5 to include inherited values. 
that's the reason why I reopened the issue, we need to discuss that internally.

**Comment by fashxp** [comment]
Proposed Solution: 

- Default behavior like in Pimcore 4 (no inheritance by default) 
- Add param to change default behavior and enable inheritance 
- Add upgrade notice and note in docs (https://pimcore.com/docs/master/Development_Documentation/Web_Services/index.html)

**Comment by dpfaffenbauer** [comment]
- Add Tests to test both behaviours ;)

**Comment by fashxp** [comment]
> * Add Tests to test both behaviours ;)

pullrequests are as always welcome ;-)

**Comment by dpfaffenbauer** [comment]
and this now also works for classification stores? Which was the actual source of this problem.

PR: Well, tests should be included in the actual implementation ;)

**Comment by weisswurstkanone** [comment]
see https://github.com/pimcore/pimcore/issues/3269
