### ISSUE TITLE
add possibility to edit an existing object version

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#3416]
That is currently only possible for documents but not objects. 

You cannot revert to a version where validation fails, so the possibility to allow editing an existing version would be good.

**Comment by dpfaffenbauer** [comment]
I tried to implement that myself, but it turned out that it is a bit more difficult and needs discussion. Cause, once you save a Object, you automatically set it as a current version. I didn't quite get where the difference between `save as new version` and save is. Thats what this should do, you should have an "edit" option in the version context-menu and this should set it as new version (or create a new version) but keep the old version as current/published version. So pimcore displays "this is a newer version" in the backend.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
