### ISSUE TITLE
[ClassificationStore] allow to use only individual keys from a group

### ISSUE THREAD

**Issue by datom** [pimcore/pimcore#3420]
# Our case
We have multiple groups with sometimes over >100 keys per group. But most of the time, we only need five or less keys from this huge groups. This leads now to two thinks:
1) massive performance problems with extjs
2) the user is overloaded with such huge list

# Possbile solution

## Group definition
- add a switch to change the behavior from "use all keys" (default setting) to "use individual keys"

### "use all keys" (default setting)
is the classical behavior we already know

### use individual keys
- create new dialog for adding keys like
![image](https://user-images.githubusercontent.com/1777505/46522236-7c35bb80-c882-11e8-8f8b-394120781b39.png)
- this leads to a dialog that is similar to adding a complete group
![image](https://user-images.githubusercontent.com/1777505/46522507-34636400-c883-11e8-85cc-88fae05e7731.png)
- now the user can select wich keys form the current group he want do add / edit

**Comment by weisswurstkanone** [comment]
Instead of selecting the keys afterwards we will go for the following approach:
- initially hide features with empty data
- press a toggle button to expand the whole group including empty features

**Comment by fashxp** [comment]
+ make that behaviour configurable on group level

**Comment by weisswurstkanone** [comment]
![image](https://user-images.githubusercontent.com/6142086/46876251-2478f080-ce3e-11e8-8505-3ced3530cc0a.png)

![image](https://user-images.githubusercontent.com/6142086/46876263-2b9ffe80-ce3e-11e8-8ff6-b0bb827953f1.png)
