### ISSUE TITLE
Option in relation fields to enable pagination

### ISSUE THREAD

**Issue by psuhane** [pimcore/pimcore#3426]
# Improvement

We have a usecase where we have to show more than 3000 relations. But the relations fields(Object relation(with metadata), multihref(with metadata), non-owner relation) available in pimcore have no option to show them in pagination.  

It would be great if in relation field's specific configuration itself have option to enable pagination with records count limit in each page. This will improve the performance of object load and improve the UI.

**Comment by brusch** [comment]
Did #4122 solved your problems? 
Thanks for your feedback!

**Comment by aclDeveloper** [comment]
@brusch this sadly doesn't solve the issue as is. We have elements with 100k relations assigned and the UI doesn't really keep up with loading this. The browser instance becomes unresponsive and slow. 
Our solution was to turn the relation around and therefore display fewer objects in the referenced object.
A way to limit the amount of items displayed at the same time would greatly improvde this behavior.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
