### ISSUE TITLE
Wrong @return type in DocBlock comment for auto generated DataObject classes of Number type

### ISSUE THREAD

**Issue by kovinet** [pimcore/pimcore#3429]
# Bug Report
 
  
### Expected behavior 
If field of DataObject is 'Number', there should be `@return float' in DocBlock in auto generated class methods
  
### Actual behavior 
Documented type is 'string', which results in warning messages in IDEs when using return value
  
### Steps to reproduce 
Create any DataObject with Number field 
  
### Code example 
```php
/**
* Get subTotalPrice - SubTotalPrice
* @return string
*/
public function getSubTotalPrice () {
	$preValue = $this->preGetValue("subTotalPrice"); 
	if($preValue !== null && !\Pimcore::inAdmin()) { 
		return $preValue;
	}
	$data = $this->subTotalPrice;
	if ($data instanceof \Pimcore\Model\DataObject\Data\EncryptedField) {
		    return $data->getPlain();
	}
	return $data;
}
```

**Comment by brusch** [comment]
This is fixed since 5.0.0, see #1704
And https://github.com/pimcore/pimcore/blob/cc9cc918972c40674fc4fbe10d5947ea862498ca/models/DataObject/ClassDefinition/Data/Numeric.php#L64

Just tested and works as expected.
