### ISSUE TITLE
Rare LockWaitTimeoutException

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#3432]
Hi,

I am getting a very rare LockWaitTimeoutException in CoreShop Behat Tests. The funny thing is, I am only getting it for one Test. With other tests that do similar things that doesn't happen. This also only happens on dev-master (it works fine with 5.4.4). I can somehow show you how to reproduce it, as I can not find a way to reproduce it outside that Behat Test Context.

To reproduce it, you must install CoreShop and run the Behat test command:

```
PIMCORE_TEST_DB_DSN=mysql://root:ROOT@db/coreshop2___behat vendor/bin/behat -c lib/CoreShop/behat.yml.dist --tags shipping_rule_condition_customer
```
(If you run it multiple times, you can extend CORESHOP_SKIP_DB_SETUP=1, so the installer doesn't trigger every time)

What happens is following:

 - Behat runs the test, that does
 - Creating some meta infos like stores, tax rules, etc.
 - Create a Customer (save)
 - Create a Product (save)
 - Assign the Product a Tax Rule (save)
 - Add the Product to the Cart (Cart Save, Cart Item Save, Cart Save)
 - Run the scenario (add shipping rule and test something)
 - After that, the cleanup hits in, where all Pimcore Objects and Doctrine Objects are deleted
 - Thats where the odd thing happens, since CoreShop has a Listener to remove CartItems when a Product gets deleted, the Cart gets saved again. There all Relations are persisted and a LockWaitTimeout on the `objects_relations_1` occurs on the customer relation (where the customer object has already been deleted as well)

That command assumes that you have CoreShop installed within the lib folder and symlinked using the repository entry in composer.json:

```json
{
    "name": "coreshop-dev",
    "type": "project",
    "description": "",
    "license": "GPL-3.0-or-later",
    "authors": [
        {
            "name": "Dominik Pfaffenbauer"
        }
    ],
    "config": {
        "optimize-autoloader": true,
        "sort-packages": true
    },
    "require": {
        "coreshop/core-shop": "dev-master"
    },
    "require-dev": {
        "behat/behat": "^3.3",
        "friends-of-behat/context-service-extension": "^1.1",
        "friends-of-behat/cross-container-extension": "^1.1",
        "friends-of-behat/service-container-extension": "^1.0",
        "friends-of-behat/symfony-extension": "^1.2",
        "friends-of-behat/variadic-extension": "^1.1",
    },
    "autoload": {
        "psr-4": {
            "": [
                "src/"
            ],
            "Pimcore\\Model\\DataObject\\": "var/classes/DataObject",
            "Pimcore\\Model\\Object\\": "var/classes/Object",
            "Website\\": "legacy/website/lib"
        },
        "classmap": [
            "app/AppKernel.php"
        ]
    },
    "scripts": {
        "post-create-project-cmd": "Pimcore\\Composer::postCreateProject",
        "post-install-cmd": [
            "Pimcore\\Composer::postInstall",
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "Pimcore\\Composer::postUpdate",
            "@symfony-scripts"
        ],
        "pre-package-update": [
            "Pimcore\\Composer::prePackageUpdate"
        ],
        "symfony-scripts": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative"
    },
    "repositories": {
        "coreshop": {
            "type": "path",
            "url": "lib/CoreShop"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by brusch** [comment]
Maybe we should think about clearing the runtime cache in `Kernel::shutdown()` as well as some other cheap cleanup tasks.

**Comment by dpfaffenbauer** [comment]
thats a good point actually.
