### ISSUE TITLE
Object Tree Search doesn't work in IE11

### ISSUE THREAD

**Issue by georgkoch** [pimcore/pimcore#3451]
# Bug Report
 
  
### Expected behavior 
When I click on the Search Icon in the object tree I want to key in a search term  

### Actual behavior  
can't key in the search term in IE 11
  
### Steps to reproduce  
open the demo-> navigate eg. to products->apparel->running->fw12_13-> try to enter a something 

  
![image](https://user-images.githubusercontent.com/20354625/46739682-6a4c8200-cca1-11e8-9e33-bc7e2e6657eb.png)

**Comment by weisswurstkanone** [comment]
Actually it works but there was a CSS issue in IE that makes you feel then key input doesn't work.

**Comment by weisswurstkanone** [comment]
Also note that a * will be appended by the default.
So if you search for "dic" it will actually search for "dic*".
If you wan to find cedic_men you have to prepend the asterisk yourself ("*dic*")
