### ISSUE TITLE
Fields label are not translated in the grid column configuration

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3457]
Hello,

As can be seen in the following screenshot (pimcore last stable demo), translations are not used in the right column (active field in the grid) on the grid column configuration popin.
If you drag and drop the field, it is well in French, but if you save and close the popin and reopen it, it will no more be translated on the right side.

Please see:
![conf-grid-columns](https://user-images.githubusercontent.com/9025839/46803131-a1816880-cd5f-11e8-9941-db914f155daa.png)

It should be translated in the choosen language so end user can easily manage column configuration (same label/langage on the right/left side).

Thanks.

**Comment by weisswurstkanone** [comment]
Chosen language is not possible but it is at least translated now.

**Comment by Yivan** [comment]
@weisswurstkanone Thanks a lot for this speedy fix ! : )

Just what do you mean, chosen langage is not possible ? Fields on the right column are only translated in english, it doesn't use the langage selection of the field on the top of the popin (the field on the left of the pagination selector) ?

**Comment by Yivan** [comment]
Ok great this is perfect so! Thanks again, have a nice day.
