### ISSUE TITLE
System displays error when the "Notification users" field in Workflow Actions is left blank  

### ISSUE THREAD

**Issue by AroraVaishali** [pimcore/pimcore#3474]
# Bug Report
 
  
### Expected behavior 
  No error should be displayed
### Actual behavior  
I have used  below  function (Workflow > Actions> Events > Failure) in my code to display any error if occurred in taking action from one state to another state in workflows

public function onFailure(WorkflowEvent $event) {
        //to do exception for getArgument not empty
        throw new \Exception($event->getArgument("exception")->getMessage());
    } 
  I am taking action from one state to another state, it got this error -:
error performing action on this element
An exception occurred while executing 'SELECT id,type FROM users WHERE id in () AND id > 0 AND type IN ('role','rolefolder')': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND id > 0 AND type IN ('role','rolefolder')' at line 1
### Steps to reproduce  
  1) In manager.php, there is a function performAction, put this code  "throw new \Exception($e->getMessage());" in catch block.
2) Then take Workflow action in your object, it displays below error   
{"success":false,"message":"error performing action on this element","reason":"An exception occurred while executing \u0027SELECT id,type FROM users WHERE id in ()  AND id \u003E 0 AND `type` IN (\u0027role\u0027,\u0027rolefolder\u0027)\u0027:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \u0027)  AND id \u003E 0 AND `type` IN (\u0027role\u0027,\u0027rolefolder\u0027)\u0027 at line 1"}

![dsad-1](https://user-images.githubusercontent.com/19402815/46951642-33fa7280-d0a6-11e8-9463-dce2a799ea32.png)
![screenshot from 2018-10-15 18-14-39](https://user-images.githubusercontent.com/19402815/46951772-8d62a180-d0a6-11e8-80ea-461565bd0210.png)

### Solution
```php
I checked that performAction function in Manager.php, it passes empty notificationUsers.If we can use notempty check for notificationUsers array. This error will not occur

  //notify users
            if (isset($actionConfig['notificationUsers']) && is_array($actionConfig['notificationUsers'])) {
               
                Workflow\Service::sendEmailNotification(
                    $actionConfig['notificationUsers'],
                    $note
                );
            }
```
# Feature Request

**Comment by brusch** [comment]
We have introduced a all new workflow engine with v5.5.0, see: 
https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/Within_V5/Workflow_Management.html 

So we cannot provide any further fixes for the old version. 
Thanks for your understanding.
