### ISSUE TITLE
[Objects] Do not allow `children` as field name

### ISSUE THREAD

**Issue by ehaeusler** [pimcore/pimcore#3475]
# Bug Report
Create a class and give it a field with a name, which has an already existing method in AbstractObject. (e.g. our customer created a field named **children**. Obviously this resulted in a method named getChildren() in the created class, which is incompatible with the original method declared in AbstractObject)
  
### Expected behavior 
The admin interface should throw a warning, that such a fieldname cannot be used
  
### Actual behavior  
The class can be saved but upon use the following error is thrown:
`Warning: Declaration of Pimcore\Model\DataObject\FAQItem::getChildren() should be compatible with Pimcore\Model\DataObject\AbstractObject::getChildren($objectTypes = <expression>, $unpublished = false)`

**Comment by brusch** [comment]
Check for forbidden field names does already exist, only `children` was missing ;) 
Thanks for reporting!
