### ISSUE TITLE
[Improvement] Abilities to create a children object directly from an object.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3476]
Hello,

For some complexe project, object tree has many objects, and so is paginated.
If we want to create sub-object, actually it can only be done from the object tree, so we use the function `Find in tree`.
Sometimes we get the "Sorry, this is not possible in elements which are paged, try to restructure your data to avoid pages in the tree", so we cannot spot the element to make a children object of it.

I understand finding/displaying object in tree can be difficult from code perspective.

**As an alternative, the purpose of this issue is to add a new button directly in the object pannel to create children of an object.**
So in case the` find in tree` don't work, enduser can use the button as alternative option to create children object.
The best would be ` find in tree`  work always but i imagine you try already many solutions.

Actually we get stuck because we cannot move all the tree/architecure just to be able to create a chlidren of objects.

I hope my improvement proposition make sense.

Thanks.

**Comment by brusch** [comment]
I guess #3697 has eliminated the original problem with the paging already, so that shouldn't be an issue anymore ☺
