### ISSUE TITLE
[Installation] MySQL Error while installing latest Pimcore via Composer create-project

### ISSUE THREAD

**Issue by kovinet** [pimcore/pimcore#3477]
# Bug Report
 
  
### Expected behavior 
Following CLI commands should install Pimcore Demo:
```
COMPOSER_MEMORY_LIMIT=3G composer create-project pimcore/demo-basic pimcore5
./vendor/bin/pimcore-install
```
  
### Actual behavior  
Installation fails with following error:

  

>  [ERROR] The following errors were encountered during installation                                                      
 * An exception occurred while executing 'CREATE TABLE `element_workflow_state` (
  `cid` int(10) NOT NULL DEFAULT '0',
  `ctype` enum('document','asset','object') NOT NULL,
  `place` varchar(255) DEFAULT NULL,
  `workflow` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`cid`,`ctype`,`workflow`)
) DEFAULT CHARSET=utf8mb4;':

SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead

### Steps to reproduce  

Install Pimcore demo as instructed on Website. My MySQL version meets the requirements and is 5.7.23.

**Comment by brusch** [comment]
Fixed by #3478
