### ISSUE TITLE
[Admin Translations] Extra permission for editing translations

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#3480]
### Expected behavior 
Allow users to edit admin translations who are not admins.  

### Actual behavior  
Only admins can edit admin translations
  
Either the admin translations could be connected to the "Translations" permission (which currently is only for shared translations) or there should be a separate permission "Admin translations".

**Comment by brusch** [comment]
Imho an extra permission makes sense.

**Comment by brusch** [comment]
PRs are welcome 😊

**Comment by brusch** [comment]
Obsolete see #6568
