### ISSUE TITLE
[DX] Optimize Pimcore-managed code files for merges with fewest conflicts possible

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#3483]
# Feature Request 

- [x] There is no existing issue regarding the same topic

## Feature description 
  
Code files managed by Pimcore which are expected to be checked in by VCS like Git should be optimized for easier merges (which might come from different branches doing different things with them).

The idea is to minimize the possibility of different actions changing the code at the same place in the same file, making merging much more difficult. It also makes diffs minimal since the changes are predictable.

Making these quite small changes makes for quite a difference in the long term.

For example:

1. always add trailing commas where possible:

```php
return [
    "bundle" => [
        "OutputDataConfigToolkitBundle\\OutputDataConfigToolkitBundle" => TRUE,
    ]
];
```

2. where the order is unimportant, sort by name, key, etc:

```php
return [
    "bundle" => [
        // even though this bundle is installed last, it comes first in the list
        "ImportDefinitionsBundle\\ImportDefinitionsBundle" => TRUE,
        "OutputDataConfigToolkitBundle\\OutputDataConfigToolkitBundle" => TRUE,
    ]
];
```

3. in fluent invocations, hang the semicolon (this might not be applicable currently):

```php
$listing
    ->setLimit(10)
    ->setOffset(20)
; // if this is on the last line, it is never touched as new calles in the fluent chain are added / removed / updated
```

**Comment by paulovitorbal** [comment]
It will be really nice. 
Also not recording the date timestamps on the definition files or other values that change just by saving the class (on GUI).

**Comment by dpfaffenbauer** [comment]
Symfony actually did something similar. Re compiling the container without changing anything gives the same sha1. Pimcore should do the same.

**Comment by brusch** [comment]
PRs are welcome 😊

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
