### ISSUE TITLE
[Improvement] Website settings per site.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3485]
Hello,

On multi-sites project, website settings are managed inside the same panel "Website settings".
The way it is presented make it difficult to spot settings from one site, and it is not possible to give user permissions to a specific site configuration.

This issue is a proposition to make website settings filtered by site, with the abilities to set permissions for user per site for Website settings.
The idea is:
- remove the `site` columns
- add a dropdown `site` near `Filter/Search` : changing the value will display only the settings from this site. A "default" value will display all the settings not tied to a site.
- add a multiselector on the role/user permissions so we can set which site he can access website settings.

Here are some picture to illustrate the concept:

![website-settings](https://user-images.githubusercontent.com/9025839/47021267-64501880-d15b-11e8-9e1b-b247eb10d4bd.png)

![website-settings-perms](https://user-images.githubusercontent.com/9025839/47021278-674b0900-d15b-11e8-9d9d-1ec3e3a72934.png)

I think it is valuable addition, because sometimes we want user access only to the site he manage, not other settings, and sometimes sensible settings (like api token/password or other things which need to be easily managed by administrator of the site).

Thanks.

**Comment by brusch** [comment]
Currently it's not planned to implement any further improvements for Website Settings. You can make use of Properties (on the site root node) for the case described above, basically there's no difference if you use Properties or Website Settings.
