### ISSUE TITLE
DataObject->save() returns null

### ISSUE THREAD

**Issue by mittererr** [pimcore/pimcore#3491]
After updating PIMCORE from 5.4.4 to 5.5.0 the save() method on all DataObjects (using PHP API like in documentation) returns null?
A bug?

**Comment by mittererr** [comment]
If I add 
`return $this;`
in Pimcore\Model\DataObject\Concrete.php the save method works again.

**Comment by dpfaffenbauer** [comment]
Didn’t it always return null?

**Comment by aarongerig** [comment]
@dpfaffenbauer No, it always returned the saved object, which is quite useful TBH. :)

**Comment by mittererr** [comment]
I agree to aarongerig - till 5.4.4 the saved object was returned.
I'm not sure but I think null was return in case of failure while saving.
