### ISSUE TITLE
"Search & Replace Assignment" with no target -> Deleting assignments impossible

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#3493]
### Expected behaviour
The function "Search & Replace Assignments" states that the target is optional. When not choosing a target the assignment should be removed.

### Actual behaviour
Message "Please select items where to replace and a new target item." appears.

**Comment by brusch** [comment]
A PR would be nice😊
Thanks in advance!

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
