### ISSUE TITLE
Show in tree  functionality is not working if object is created under sub folders and if object exists on the 2nd page

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#3497]
# Bug Report
 
  
### Expected behavior 
  It should be display
### Actual behavior  
  Not showing the path if the selected object is from 2nd page.
### Steps to reproduce  
  1.) Login into the application in the perspective mode.
2.) Click on the 2nd to select the object from 2nd page. Expand the folder by clicking "+" icon.
3.) Click on any object from the page 2.
4.) Click on previous page "<" icon to go back to the previous page.
5.) Click on the show in the tree icon.
### Code example 
```php
// your code
```

# Feature Request

**Comment by brusch** [comment]
Are you using Pimcore 4, as this does work as expected on https://demo-advanced.pimcore.org/

**Comment by AroraVaishali** [comment]
This issue is in Pimcore 5.4.4, show in tree is working fine but not with sub folders or if folder has lots of records with pagination.
![index](https://user-images.githubusercontent.com/19402815/47087127-dba7aa00-d238-11e8-916f-c32bfd3b6f61.jpeg)

**Comment by BlackbitNeueMedien** [comment]
Currently we have a customer where the problem also occurs. We have recently updated to Pimcore version 6.5.3.
The customer reports that when he searches for an object and presses the "Show in tree" button after opening it, there are some objects that are not found. 

My observation showed that the root node is already found, but the offset is not given with the second request.
<img width="847" alt="Bildschirmfoto 2020-03-16 um 14 17 11" src="https://user-images.githubusercontent.com/8749138/76762130-ff09b800-6790-11ea-9a43-61e2801001c1.png">

Here are the requests, where an object is :
<img width="1125" alt="Bildschirmfoto 2020-03-16 um 14 17 45" src="https://user-images.githubusercontent.com/8749138/76762195-1b0d5980-6791-11ea-91dd-3bdc1e834608.png">

I am a little desperate right now. Does anyone have a solution for this problem?
