### ISSUE TITLE
clarify necessary changes for sending e-mails in documentation

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#3501]
Hi,

after #3257, could you please clarify in the documentation what has to be done so that emails (not the SMTP method) work again? The only real hint was the following in the migration script:

> The email method mail() is not supported anymore, please configure sendmail or SMTP in your system settings in order to use Pimcores email capabilities. <error>WARNING: Emails are not going to work until you have changed your configuration!</error>

I added the path to sendmail in the system settings. It looks like the following now:

`/.local/bin:/opt/composer/bin/composer:/usr/sbin/sendmail`

I also made sure that "mail" is selected as transport method in the e-mail settings.

But all I get is the following error when sending e-mails:

```
Swift_TransportException
HTTP 500 Internal Server Error
Expected response code 220 but got an empty response
```

I verified via command line that sendmail is working on the server:

`echo "Subject: test" | /usr/sbin/sendmail -v mail@example.org`

So it seems more changes are needed. But I can't find more information in the documentation.

**Comment by brusch** [comment]
The docs are clear, use either Sendmail or SMTP transport mode. 
We don't provide how-to's how to setup Sendmail or a SMTP server.

**Comment by brusch** [comment]
You can also check out [Swiftmailers documentation](https://swiftmailer.symfony.com/docs/introduction.html) for further details.
