### ISSUE TITLE
[Versions] Version preview of Assets shows always the latest version

### ISSUE THREAD

**Issue by SEYentl** [pimcore/pimcore#3503]
The versioning of assets stopped working in the latest pimcore version.

### Expected behavior
Going back to previous version of an assets is possible.
  
### Actual behavior
Previous versions are overwritten by new asset versions.
  
### Steps to reproduce 
1. Upload asset in asset folder (e.g. image)
2. Save the asset.
3. Overwrite the asset with a new version.
4. Go to versions and set the version back to the previous version.
5. Result: previous version is the same as current version.

**Comment by brusch** [comment]
There's currently no feature to download previous version. 
Publishing a previous version works as expected for me, if it doesn't for you, please provide me a reproducible case - thanks!

**Comment by brusch** [comment]
Btw, you'd have to update to the latest `dev-master` to get the fixed version of Pimcore :)

**Comment by SEYentl** [comment]
![demo](https://user-images.githubusercontent.com/40569826/47153249-5a572280-d2df-11e8-98a6-47bc9e82639a.gif)

As you can see the first picture is removed, since I can not download it anymore.
This was tested on the demo environment.

**Comment by brusch** [comment]
@SEYentl as I said ... please try it again with the latest `dev-master`  ... it was fixed some minutes ago and the demo is only resetted every so often.

**Comment by brusch** [comment]
@SEYentl Demo is now updated, so feel free to test it there again.
