### ISSUE TITLE
ImageAdvanced - hotspot/marker window to small

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#3508]
If you try to add hotspots / markers to a small image (e.g. 100x100px) the window is too small to show all buttons:

![image](https://user-images.githubusercontent.com/7206334/47158382-d5263a80-d2eb-11e8-80e0-c38b1f167d30.png)

**Comment by weisswurstkanone** [comment]
solved by using overflow menus for now. maybe a minimum sized container would be better.

![image](https://user-images.githubusercontent.com/6142086/48840048-d7b5fd00-ed8d-11e8-9e61-cc4fadf257ee.png)

**Comment by ultramegatom** [comment]
thx
