### ISSUE TITLE
Add a possibility to adjust the quality of preview images in the asset view

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#3512]
Add a possibility to adjust the quality of preview images in the asset view.
Maybe if the filesize of an svg will not exceeded a maximum filesize, load the original svg in the asset view

![thumbnail_quality](https://user-images.githubusercontent.com/1086343/47202099-7b218580-d37c-11e8-83f0-742181bb7881.png)

**Comment by brusch** [comment]
Obsolete due to  #3742 ,which gives you a lot more possibilities and covers also the functionality requested here.
