### ISSUE TITLE
[ecommmerce] Invisible variant in tree view

### ISSUE THREAD

**Issue by lorextera** [pimcore/pimcore#3514]
# Bug Report

### Expected behavior 

I can create a variant from the **variant tab** in the product's sheet then the new variant appears in the **tree view**.

### Actual behavior  

When I add a variant (id: 12472) from the **variant tab** in the product's sheet, the new variant does not appear in the **tree view**.

A pre-existent (id: 1537) product's child (a variant?) is visible in the **tree view** but it does not appear in the **variant tab**.

![variant_0](https://user-images.githubusercontent.com/1744861/47212670-28a29200-d399-11e8-8c17-0a38faeb2a01.png)

#### Difference between objects

The difference between objects is **o_type**:

- `object`: visible on the tree view, invisible on the variant grid
- `variant`: invisible on the tree view, visible on the variant grid

![variant_1](https://user-images.githubusercontent.com/1744861/47212675-2dffdc80-d399-11e8-83e7-17c239b9a75a.png)

### Steps to reproduce  

Try to add a variant to a [product](https://demo-advanced.pimcore.org/admin/login/deeplink?object_1521_object) in the e-commerce demo site.

**Comment by fashxp** [comment]
Hi, 
this is actually wanted behavoir. Variants are - compared to objects - treated differently in object tree and in the grid. 
Product first level children (color way) in our demo advanced are normal objects, not variants. 

For doc concerning variants see: https://pimcore.com/docs/5.x/Development_Documentation/Objects/Object_Classes/Class_Settings/Variants.html

Optionally you can also activate showing variants in tree in the class definition by activating the checkbox `show variants in tree`.
