### ISSUE TITLE
ExtJS 6: document settings - action selection buggy

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#352]
Changing of the action of a document doesn't work on first click. 

![image](https://cloud.githubusercontent.com/assets/4639428/11928275/6bc75aac-a7d2-11e5-9ef0-f0869b2559e0.png)

Chrome dev-tools shows that 2 requests are fired:
![image](https://cloud.githubusercontent.com/assets/4639428/11928302/8d38392c-a7d2-11e5-8dde-ea5dab2945dd.png)

The first request seems to deliver the right content whereas the second request is empty.

**Comment by markus-moser** [comment]
This bug also occurs in the static routes admin panel...

**Comment by weisswurstkanone** [comment]
fixed in build 3586

**Comment by ptaferner** [comment]
Thanks for resolving this issue, as it was kind of annoying for me - I can confirm that it works fine again now :-)
