### ISSUE TITLE
Showing tree (with pagination and subfolders) is not working in Pimcore 5.4.4

### ISSUE THREAD

**Issue by AroraVaishali** [pimcore/pimcore#3520]
# Bug Report
 
  
### Expected behavior 
 There should be no error popup
### Actual behavior  
  It displays error. PFA
![showintree](https://user-images.githubusercontent.com/19402815/47289904-7da10b00-d61a-11e8-9e33-dbb400852060.png)

### Steps to reproduce  
https://demo-advanced.pimcore.org/admin/?_dc=1540206620
  1) Search an object id 1511 and click on show in tree icon
### Code example 
```php
// your code
```

# Feature Request

**Comment by AroraVaishali** [comment]
Any update when this fix will be available?

**Comment by brusch** [comment]
@AroraVaishali no, actually that should work in most cases, but there are some edge-cases in combination with custom views/perspectives where this feature isn't available at the moment (see info message). 

Contributions are of course always appreciated ;-)
