### ISSUE TITLE
Show in tree icon functionality(with pagination and subfolder) is not working in Pimcore 5.4.4

### ISSUE THREAD

**Issue by AroraVaishali** [pimcore/pimcore#3521]
# Bug Report
 
  
### Expected behavior 
  There should be no error message
### Actual behavior  
  It displays error message
![showintree-1](https://user-images.githubusercontent.com/19402815/47290212-02405900-d61c-11e8-8c1c-cc09249fd3a3.png)

### Steps to reproduce  
  1) Open pimcore demo website https://demo-advanced.pimcore.org/admin/
   2) Search an object  ID 1511.
   3) Click on show in tree icon.
   4) System gives error message "Sorry, this is not possible in elements which are paged, try to restructure your data to avoid pages in the tree"
### Code example 
```php
// your code
```

# Feature Request

**Comment by brusch** [comment]
Duplicates #3520
