### ISSUE TITLE
Prevent saving if new version has been written after loading

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#3522]
When multiple PHP processes load and modify the same Pimcore data object, only the data of the last process will land in the database (race condition).
Example:
1. process 1 reads object "abc"
1. process 2 runs in parallel to process 1 and also fetches object "abc"
1. process 1 changes object's data
1. process 2 changes object's data
1. process 1 saves object
1. process 2 saves object

Only data of one process will land in database: the one which finishes later.

This could be solved by optimistic locking: When saving an object the version of the object must be equal to the current version of th object in database. Otherwise an exception should be thrown (which can be catched somewhere to retry the saving process.
To achieve this, the object's version has to be updated as soon as the saving process startet, e.g. in \Pimcore\Model\Element\AbstractElement::updateModificationInfos().
If you agree I would like to offer a PR (but want to hear if this is ok because ot would slow down saving a bit because of the additional SQL update für setting the current version / last modified timestamp)

PS: One more thought on this: Currently the version of an object's data is only visualized via the timestamp. As this is a Unix timestamp which is based on seconds multiple versions are marked as "current version" in versions tab. Perhaps this should also be changed so there is a real 1:1 relation between objects and versions.

**Comment by brusch** [comment]
You can use `$object->__isBasedOnLatestData()` wherever you need this behavior.
