### ISSUE TITLE
[Demo-Basic] Blog not working

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#3524]
https://demo-basic.pimcore.org/en/advanced-examples/blog

404 Error

**Comment by fashxp** [comment]
please create bug-reports for demos in demo repositories ... like here https://github.com/pimcore/demo-basic/issues/2

**Comment by ckemptner** [comment]
@fashxp - Thank you - There is still the same error showing up?

**Comment by brusch** [comment]
@ckemptner the bug was fixed but there was no release tagged. Release is done now, so demo works again.

**Comment by ckemptner** [comment]
Ahh! Thanks! @brusch
