### ISSUE TITLE
QuantityValue: Remove (empty) unit

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#3528]
# Bug Report

### Expected behavior 
When valid units are set for a quantity value field only these should be available for selection. 
  
### Actual behavior  
Beside set valid units there is the "(empty)" option. 

If the "(empty)" unit option nevertheless is useful (I do not think so) an additional "unit mandatory" checkbox would be useful.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
