### ISSUE TITLE
Grid Operators "context"

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#3538]
In the constructor of the AbstractOperator there is a parameter "context". Unfortunately it is always "null". Would it be possible to use this to differentiate between CSV-Export and regular Grid-View?

There are constellations where the output in the CSV export should be different from the grid view. Therefore it would be great to use this context for this kind of purpose.

**Comment by fashxp** [comment]
if then `context` should not only contain info csv/grid but it should be possible to also attach additional information to it ... so maybe an extendable object or so

**Comment by weisswurstkanone** [comment]
Info should be there from now on - $context["purpose"] == "gridview"

**Comment by markus-moser** [comment]
Many thanks. I added a pull request for the workflow state operator as one use case for this new context/purpose param. I have similar cases in some custom operators and maybe we will find additional cases in the existing operators too in the future.
