### ISSUE TITLE
Object's datetime field save error

### ISSUE THREAD

**Issue by silvantroxler** [pimcore/pimcore#354]
Whenever I choose or change a date in an object's datetime field and then save the object the following message appears: "Empty mandatory field [ date ] fieldname=date".
I've checked the request and it sends date:null as a parameter to the publish request. Therefore, the datetime field cannot be saved.
I have this bug in IE, Safari and Firefox, but not in Google Chrome.

**Comment by weisswurstkanone** [comment]
build 3586
