### ISSUE TITLE
Grid data and column alignments are not synchronized in Pimcore 5.4.4

### ISSUE THREAD

**Issue by AroraVaishali** [pimcore/pimcore#3541]
# Bug Report
 
  
### Expected behavior 
  It should be appropriate.
### Actual behavior  
Grid and columns border are not synchronized.
![2124124 1](https://user-images.githubusercontent.com/19402815/47565961-ca048780-d947-11e8-8347-e75f7c9f7b14.png)
![322424 1](https://user-images.githubusercontent.com/19402815/47565976-d7217680-d947-11e8-9350-296cd2da0768.png)

### Steps to reproduce  
  1.) Login into the application.
2.) Click on Products.
3.) Expand apparel and click on running folder.
4. ) Click on Grid option.
5. ) Select all the fields under Grid Configuration.
6. ) Click on Apply button.
7. ) Scroll right to the end and scroll left again.
8. ) Repeat step no 7 for 2-3 times.
### Code example 
```php
// your code
```

# Feature Request

**Comment by weisswurstkanone** [comment]
maybe somehow related to https://www.sencha.com/forum/showthread.php?335102 ?

**Comment by brusch** [comment]
No override available, so we have to wait until the next GPLv3 release.
