### ISSUE TITLE
Add option to set globally thumbnail quality or document the way to do it.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3542]
Hello,

It seems there is a way to set default backend thumbnail (please see: https://github.com/pimcore/pimcore/issues/272).
On the same idea, is it possible to set a global quality for frontend and backend thumbnail ?
If yes it should be documented (i found nothing in the document, neither the document of the option to override like it is presented in issue 272). If it is not possible actually, so implementing it.

Actually value 85 is hardcoded as default value and looking in the core code their don't seem any way to override it with environment parameters or symfony/pimcore config files.
Sometimes for website presention quality graphism 85 is a litte to low (or at the inverse, for a website made only for mobile, having possibility to set to low settings is useful). So having the possibility to set it globaly (without having to have to extend or creating custom classes) would be very good.

**To summary:**
It would be a nice addition to be able to set quality for front and backend globally or if it exists it would help to document it here : https://pimcore.com/docs/5.x/Development_Documentation/Assets/Working_with_Thumbnails/Image_Thumbnails.html

Thanks!

**Comment by brusch** [comment]
@Yivan Issue #272 has nothing to do with thumbnails, probably a typo, can you please reference the right one? 

Imho this request makes absolutely no sense for frontend thumbnails, as the quality is in the configuration anyway and it should be changed there: 
![image](https://user-images.githubusercontent.com/142037/48708208-3484ac80-ec02-11e8-9c8e-5813fbf8823f.png)

**Comment by Yivan** [comment]
Hello @brush, sorry about the wrong link (i had too much tabs open i think and pasted the wrong link). I didn't manage to find the good one and retrieve it (I updated the original message).

Yes we can set quality here in thumbnail config, but purpose was to be able to set it globally as it is hardcoded to 85 in case we use direct asset api call like:
`$this->myObject->getMyImage()->getThumbnail(["width" => 220])->getPath()` and be able to set the quality globally for the project different than 85 (i know quality can be set in my above example code, but this will not be convenient/maintenable).

I know it could be done by overriding asset classe maybe, but the purpose of this issue was to offer the possibility (yaml config or params env ou system settings, or other) to be able to set globally diffent than 85.

**Comment by Yivan** [comment]
@brusch 
Sorry to come back on this, but we have more and more project asking sometimes for better quality than 85. As I explained we don't use a lot the thumbnail config, but generate directly asset in the front end with `$image->getThumbnail(["width" => 220])` for instance.
Only way for now is adding quality parameters on all call `getThumbnail`.

I think this value should be configurable. It is a pretty important one.
It will be more easy to optimize page size in a glance by adjusting just one global value (trying at 90, 80 and compare several page size...).

Please see here:
https://github.com/pimcore/pimcore/blob/08b6245bcc828321f7555faf37ea546ed4ab2633/models/Asset/Image/Thumbnail/Config.php#L78

I think a global config make senses. Or better by yaml config in the bundle (so it can handle multisite case with different quality for instance).
