### ISSUE TITLE
Tree won't refresh after translation copy

### ISSUE THREAD

**Issue by RuudvdvNB** [pimcore/pimcore#3552]
When we copy a document using the translation button in the toolbar we choose for 'using inheritance'. After the document is copied it opens as a new tab, but the document tree on the left doesn't update. 

We first noticed this in version 5.2 (haven't used it in earlier versions) and also noticed this in version 5.5.
  
![image](https://user-images.githubusercontent.com/36728652/47781031-07c52f80-dcfd-11e8-9f42-a62d352af09b.png)

**Comment by brusch** [comment]
Yep, especially when creating or copying elements inline there isn't auto-refresh, that's why we offer a refresh button in the tree context menu - imho that's reasonable as this is also known from operating systems and other web software.
