### ISSUE TITLE
Drag & Drop freezes browser

### ISSUE THREAD

**Issue by AndrewAteles** [pimcore/pimcore#3559]
# Bug Report
 
  
### Expected behavior 
  Browser does not freeze
### Actual behavior  
  Browser freezes when dragging and dropping an object.
### Steps to reproduce  
 -  On demo site, create two new classes, Category and Products.
 -  On class Category add layout component Panel and under it add data component Relation -> Objects with allowed classes set to Products. 
 -  Create one Category data object and 4 Product data objects and add the Products to the Category.
 -  Now in the products list drag products up and down in the list a few times and the browser will hang (usually it will happen before 10 attempts).

I have been able to reproduce this in Chrome and Opera, not in Firefox and Edge.
The issue exists in Pimcore 5.0.2 and Pimcore 5.4.4.

**Comment by NiklasBr** [comment]
Yup, the browser console will fill quickly with: 
````js
ext-all.js:22 Uncaught RangeError: Maximum call stack size exceeded
````
