### ISSUE TITLE
Incompatibility with the latest MySQL version

### ISSUE THREAD

**Issue by luklewluk** [pimcore/pimcore#356]
Hi everyone.
I just wanted to set up a new project based on Pimcore using server with following setting: OpenLiteSpeed, PHP 7.0.1 and MySQL 5.7.10. Unfortunately during the installation I got a mysql error:
```
Fatal error: Uncaught Zend_Db_Statement_Mysqli_Exception: Mysqli statement execute error : All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead in /Library/WebServer/Documents/pimcore/pimcore/lib/Zend/Db/Statement/Mysqli.php:214 Stack trace: #0 /Library/WebServer/Documents/pimcore/pimcore/lib/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array) #1 /Library/WebServer/Documents/pimcore/pimcore/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array) #2 [internal function]: Zend_Db_Adapter_Abstract->query('\nCREATE TABLE `...') #3 /Library/WebServer/Documents/pimcore/pimcore/lib/Pimcore/Resource/Wrapper.php(263): call_user_func_array(Array, Array) #4 /Library/WebServer/Documents/pimcore/pimcore/lib/Pimcore/Resource/Wrapper.php(233): Pimcore\Resource\Wrapper->callResourceMethod('query', Array) #5 /Library/WebServer/Documents/pimcore/pimcore/models/Tool/Setup/Resource.php(42): Pimcore\Resource\Wrapper->__call('query', Array) #6 [internal function]: Pimcore\ in /Library/WebServer/Documents/pimcore/pimcore/lib/Zend/Db/Statement/Mysqli.php on line 214
```

The problem is with the both (PDO and Mysqli) adapters.
In database only 13 tables are created before error occurs.

I tried with the newest Pimcore 4.0 (nightly) and Pimcore 3 as well.
Also I thought that maybe it's PHP 7 issue but I tried with PHP 5.6.16 and I got exactly the same error.

I know it's not Pimcore failure because the error comes from Zend 1 library but I think we shouldn't use deprecated framework version forever (even if Magento and many others do) :)
Anyway I hope this error is easy to solve (maybe Zend already released an update for this lib) and I could help you by reporting it.

**Comment by brusch** [comment]
Thanks!

**Comment by luklewluk** [comment]
Wow! Thank you very much for very quick response and fix!

**Comment by brusch** [comment]
Build is already finished, to you can try it again using the latest build: 
Demo/Boilerplate: https://www.pimcore.org/download/pimcore-data.zip
Empty Inst.: https://www.pimcore.org/download/pimcore-build.zip

**Comment by luklewluk** [comment]
Now it works like a charm! :)
I'm glad it wasn't difficult to fix it! So I shouldn't have assumed that it was a Zend bug :)
I can use Pimcore with the newest PHP & MySQL then. Thank you again!
