### ISSUE TITLE
DataObjectEvents::PRE_UPDATE always fires two events

### ISSUE THREAD

**Issue by thgross** [pimcore/pimcore#3563]
# Bug Report

When you set up an ``DataObjectEvents::PRE_UPDATE`` event, it is always fired twice when you save the object.
The same thing happens on ``DataObjectEvents::POST_UPDATE``.

### Expected behavior 
Only fire a single event.
  
### Actual behavior  
pimcore fires 2 events.

### Steps to reproduce  
Set up an ``DataObjectEvents::PRE_UPDATE`` event using the code below. Open an save an object in pimcore. In the Application Logger, you see 2 preUpdate-events on the same object.

### Code example 
```yml
# app/config/service.yml
   AppBundle\EventListener\DataobjectListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate, method: onPreUpdate }
```

```php
namespace AppBundle\EventListener;
class DataobjectListener implements EventSubscriberInterface
{
  public static function getSubscribedEvents()
  {
    return [DataObjectEvents::PRE_UPDATE  => 'onPreUpdate'];
  }

  public function onPreUpdate(DataObjectEvent $event)
  {
    \Pimcore\Log\ApplicationLogger::getInstance()->debug(
      'onPreUpdate Object',
      ['relatedObject' => $event->getObject()]
    );
  }
}

```

**Comment by brusch** [comment]
I'm not able to reproduce this in the latest version of Pimcore.

**Comment by thgross** [comment]
It happens for me in 5.4.2, 5.5.3 and dev-master.
