### ISSUE TITLE
Performance issue with localized relation fields

### ISSUE THREAD

**Issue by sidd-chaudhery** [pimcore/pimcore#3566]
# Bug Report
It is a performance issue related to relation fields which are localized. Since we cannot make localized relation fields lazy loaded, every time when I expand a object in tree, open a folder grid or open a object, it fires a lot of queries in the background to get that relation data. Now because in my case, the no. of localized relation fields is 20 and total locales is 40, the no. of queries which run in the background increases drastically which in turn makes a major performance issue and also make Pimcore breaks with a popup "communication failure"

![communicationfailure](https://user-images.githubusercontent.com/21220016/48045555-c928ec80-e1b6-11e8-8648-d0b6bf0d1692.png)
I have tried expanding a folder which in turn shows me this popup  
  
### Expected behavior 
It should not break and loading time should also be increased.  
  
### Actual behavior  
Currenlty the request takes a lot of time to load and after some time it comes with a popup communication failure

**Comment by brusch** [comment]
Duplicates #2998
