### ISSUE TITLE
Default values in select menus of ExtJS 6 UI

### ISSUE THREAD

**Issue by ptaferner** [pimcore/pimcore#357]
There are a couple of places in the ExtJS 6 UI of pimcore where you can't revert to the default value after having chosen a value in the select menu.
For instance, if you choose a value for the option "Layout" when creating a new object class via the frontend (currently the only option here is "fit"), you can't go back to the state of "no selection". However, there is a difference in the layout whether you choose "fit" or nothing, so it might be desirable to return to "no selection" from the "fit" selection.
The same situation occurs in the "Transformations" settings under image thumbnails: Select a value for "Positioning", e.g. for the transformation "Cover" and again, you can't go back to the initial setting.

**Comment by weisswurstkanone** [comment]
Is a bit misleading. The height of the "no selection" row is even smaller than in 3.4.

**Comment by brusch** [comment]
I think we should just use the text "[no selection]" or something similar.

**Comment by weisswurstkanone** [comment]
Changed to empty string to "Default". Build 3588
