### ISSUE TITLE
New Request() in DocumentRenderer clears RequestContext Data

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#3579]
https://github.com/pimcore/pimcore/blob/4c986d60d890898e466533a21dfd29bde2acb9f6/lib/Document/Renderer/DocumentRenderer.php#L129

As you can see here, pimcore generates a new request object if the request stack has no active requests (in cli mode for example).

That's ok if you're submitting just one email per request. But if you're going to send multiple mails (or something else with an involved request context) via CLI in a loop, this becomes a major problem. For example:

## Preparation
- Populate system settings `host` with `my-domain.com`
- Create a email
- Create a command with a containing loop (more than one cycles) and send the mail on each cycle:

```php
foreach ($infos as $info) {
   $email = Email::getByPath('/your-email');
   $url = $this->urlGenerator->generate('route_name', []);
   $mail = new Mail();
   $mail->setDocument($email);
   $mail->setTo('your-email-address');
   $mail->setParam('url', $url);
   $mail->send();
}
```

## Result
- Mail 1: Param `url` is `http://my-domain.com/my-url-structure`
- Mail 2: Param `url` is `http://localhost/my-url-structure`

## Explanation
1. The first mail generation is valid since the default RequestContext contains the default host (search for`pimcore.routing.router.request_context` service in your compiled container).
2. DocumentRenderer does not find any request and creates a new one
3. Empty request will be injected in `RouteListener` => `$this->context->fromRequest($request);`
4. In the next cycle, the context does not have any default data anymore.

**Comment by FredoVelcro** [comment]
Have the same problem ! The router generate a proper absolute url containing the right Host on first call and then, it returns "localhost" as the host...
