### ISSUE TITLE
[Objects] Class Editor: Prompt for name of newly added field

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#3580]
### Current behavior
After adding a new field you have to click the new node in the tree and edit the name, that are avoidable clicks. 

### Improved behavior
The editor should prompt for the name of the new field, the `name` and `title` attribute should be prefilled. The configuration form of the newly created field should be opened after it was added.

**Comment by dpfaffenbauer** [comment]
but don't do that for fields that are not changeable (crm)

**Comment by brusch** [comment]
![07-11-_2018_15-18-48](https://user-images.githubusercontent.com/142037/48136696-94915f80-e2a0-11e8-9496-1547f5259775.gif)

**Comment by dpfaffenbauer** [comment]
seems that this broke copy-paste within the editor. When I copy a field-definition, it misses the name and label (probably all settings)

**Comment by brusch** [comment]
@dpfaffenbauer can you provide me a reproducible scenario, because for me it actually works fine: 

![05-12-_2018_14-50-35](https://user-images.githubusercontent.com/142037/49517742-2dfe6200-f89d-11e8-8fc4-f4c66624e18f.gif)

**Comment by dpfaffenbauer** [comment]
try it with a container (panel) thats where it fails for me.

**Comment by brusch** [comment]
Works as well or I'm getting something wrong? 
![05-12-_2018_15-04-20](https://user-images.githubusercontent.com/142037/49518570-3fe10480-f89f-11e8-8b0d-df59fc3102db.gif)

**Comment by dpfaffenbauer** [comment]
you're right... there is something off with my installation, just tried on the demo and it works there.... thanks for checking though :)
