### ISSUE TITLE
Aerospike cache adapter

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#3582]
Which will be superior to the best adapter currently available - Redis.

https://www.aerospike.com/technology/
Aerospike’s unique storage layer incorporates both DRAM and Flash, giving in-memory characteristics at the price of SSDs. With continual data expiration, Aerospike can operate as a cache with minimal maintenance. Aerospike is multi-threaded software to compare with Redis.

**Comment by brusch** [comment]
@kanevbg Contributions are always welcome ;) 
At the moment it's not planned that the core-team provides another caching adapter. 
So it would be a perfect fit for an additional community bundle.
