### ISSUE TITLE
Default Quantity Value does not get saved on object

### ISSUE THREAD

**Issue by tose08** [pimcore/pimcore#3585]
# Bug Report
 
  
### Expected behavior 
If a new object is created which has a default value, the value should be saved after saving the object. Later this value should also be found on the corresponding object (DB, PHP API)
  
### Actual behavior  
All values - except for the default value - are saved. See DB. After changing the default value in the form, it will also be saved.

### Steps to reproduce
1. Create new class with Data Compontent "Quantity Value", set default value (in class definition) and new Quantity Value ("Euro")
2. Create new Object of this class
3. Edit the Object and do not change the default value!
4. Save

After that the value in the database is null.
  
### Code example 
```php
// your code
```

# Feature Request

**Comment by epicsoft-de** [comment]
+1
