### ISSUE TITLE
Shorten path in grid view

### ISSUE THREAD

**Issue by SEYentl** [pimcore/pimcore#3588]
# Feature Request

## Feature description 
 Show short version of paths in gridview from objects that have very long paths.
This would be very handy for an easy overview of the objects with there paths.

Example AS-IS:
/Catalogus/Producten/Categorized/Audio/Audio Converters/2135

Example To-BE:
.../Audio Converters/2135

**Comment by weisswurstkanone** [comment]
maybe "misuse" this one AdminEvents::OBJECT_LIST_AFTER_LIST_LOAD ?

**Comment by weisswurstkanone** [comment]
maybe a use case for https://pimcore.com/docs/5.x/User_Documentation/DataObjects/CSV_Import/Operators/PHPCode.html

**Comment by SEYentl** [comment]
Could you guide me on how I can use this in combination with the "php code" operator.

Just placing AdminEvents::OBJECT_LIST_AFTER_LIST_LOAD in the "php class" field won't do the trick I guess?

**Comment by BlackbitNeueMedien** [comment]
Hmm, how is CSV import connected to shortening the displayed path in grid view?
Wouldn't be using https://pimcore.com/docs/5.x/Development_Documentation/Objects/Object_Classes/Class_Settings/Path_Formatter.html an option?

**Comment by brusch** [comment]
Well that always depends on the with of the column in the grid, so I'd go for the sub-string operator in grid config, or just double click on the right edge of the column to enlarge the column to the full with. 

![image](https://user-images.githubusercontent.com/142037/52354940-a914fd80-2a31-11e9-88f0-b53a6fd05683.png)
