### ISSUE TITLE
Resize of grid columns in object search can't be saved.

### ISSUE THREAD

**Issue by SEYentl** [pimcore/pimcore#3593]
### Expected behavior 
After resizing the columns in the object search grid, the configuration can be saved by pressing the save button.

I would expect the same functionality as on the normal grid overview.
  
### Actual behavior  
There is no save button available after changing the column width.

### Steps to reproduce 
1) open the object search
2) Select an object type.
3) Change and save the grid configuration.
4) Resize columns
5) Try to save the column size -> this doesn't work.

**Comment by brusch** [comment]
@SEYentl please create

**Comment by brusch** [comment]
@SEYentl please create issues with meaningful descriptions and take away the parts of the template that are not used. Thanks

**Comment by jacobsyentl** [comment]
@brusch 

First and foremost, best of wishes in 2019!
Do you have an idea if this issue will be picked up soon?

**Comment by brusch** [comment]
@jacobsyentl no, but PRs are welcome ;-)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
