### ISSUE TITLE
[Document] Copy & paste of area blocks with inherited editable contents 

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#3594]
# Bug Report
  
### Expected behavior 
If you copy an area block which contains inherited editables, the contents of the inherited elements should be pasted properly in the target area block. 

### Actual behavior  
The contents of the inherited editables are missing.

**Comment by fashxp** [comment]
hmm, really? I think both ways might have entitlement. 
I might want to really duplicate the content, or I want to preserve the inheritance chain and also inherit the content in the newly pasted document. 
shouldn't there at least a difference between past with inheritance and normal paste?

**Comment by brusch** [comment]
@fashxp preserving the inheritance would only work if the source and the target document have the same master document. Imho that's rarely the case if you copy a block from one document to another. 
What we could do is checking whether the source and the target document have the same master and behave accordingly, but that would also mean adding some extra complexity and probably causing more confusion for editors than it helps. I guess an editor expects from a copy functionality that he can paste 1:1 the contents to the target document of what was previously copied to the clipboard.

**Comment by fashxp** [comment]
ahh, reading titles properly helps a lot - this is dealing about copying area blocks, mixed it up with copying whole documents. 
forget my comment
