### ISSUE TITLE
[XLIFF] Support for Classification Store Values

### ISSUE THREAD

**Issue by REABMAX** [pimcore/pimcore#3595]
# Bug Report
  
### Expected behavior 
The xliff-Export exports everything translatable in DataObjects including classification store values.

### Actual behavior  
The xliff-Export only exports localizedfields. localizedfields are not able to contain classificationstore, so classificationstore inputs cannot be translated via xliff.
  
### Steps to reproduce  
- Create a classification store with input key
- Create a classificationstore property on a class
- Add a value in any language or default
- try to export the object in xliff

**Comment by brusch** [comment]
@REABMAX PRs / contributions are always welcome :)
