### ISSUE TITLE
Redirect Entries beginning with ^install not working

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#3598]
Funny (but also reasonable) Issue here:

- go to demo
- create new redirect entry (Source: `@^/installationprotocol@`)
- open `/installationprotocol`

-> Redirect not found

**Reason**: RequestMatcher introduces the `CONTEXT_INSTALL` pimcore context after an url `^/install` has been requested. 

![bildschirmfoto 2018-11-13 um 15 16 04](https://user-images.githubusercontent.com/700119/48419082-5213cb00-e757-11e8-8752-88b7007f6821.png)

**Comment by brusch** [comment]
I don't think we can solve that without introducing much more overhead.
Imho it is reasonable to have 3 reserved prefixes (`/install`, `/admin` and `/webservice`) that can't be used in custom routes, also because other things such as firewall configs rely on that.

**Comment by solverat** [comment]
Well... the decision has been made. Throwing an exception (and documentation) while adding redirects of such types would be time-saving for developers though.

**Comment by dpfaffenbauer** [comment]
`/install` isn't used anymore anyway, why not remove it?! deprecate the whole `install_context` and remove it with the next version.

**Comment by brusch** [comment]
@dpfaffenbauer yep, that makes sense - but then issue still exists for `^/admin` and `^/webservice`.

**Comment by dpfaffenbauer** [comment]
thats not an issue, thats valid ;) just document that and done.
