### ISSUE TITLE
Variant disappears after moving out of object context

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#3602]
Reproducable on demo-basic:
![](http://g.recordit.co/V1vfyQWMxp.gif)

- create an object 
- add a variant to the object
- move variant to parent folder
- refresh folder
-> Variant is gone - and as far I've tested it, there is no way to get it back (except changing the parent id in database)

Solution: Disallow dropping variants on folders?

**Comment by fashxp** [comment]
or dropping variants on any place in tree ... 
at least dropping variants below objects that do not have variants activated will have similar effects

**Comment by psuhane** [comment]
What if dropping variants will only be allowed in the same parent, just to support the feature 'Sort manually' in tree?
