### ISSUE TITLE
Filterting Grid with Classification Store

### ISSUE THREAD

**Issue by incoxx** [pimcore/pimcore#3608]
# Bug Report
 
  
### Expected behavior 

PIMCORE 5.3.3
Git Hash: 593880d6b3170cb095e7b47682e197845031e3a2

In a customer project we use the classification store for some objects.
If i list all objects in the "grid view" and assign some keys to grid, the keys and values are visible.
Expected: i´d like to filter (!) the grid for values in the classification store
  
### Actual behavior  

[2018-11-15 09:32:41] php.CRITICAL: Call to a member function isLocalized() on boolean {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function isLocalized() on boolean at /var/www/httpdocs/vendor/pimcore/pimcore/models/DataObject/Service.php:784)"} []

It seems $csFieldDefinition in line 784 is boolean and not an object...

**Workaround**: We add the following patch to Service.php

/* incoxx */
if (is_bool($csFieldDefinition)) {
                    $language = 'default';

} elseif (!$csFieldDefinition->isLocalized()) {
                    $language = 'default';
                }
/* incoxx */

instead of 

if (!$csFieldDefinition->isLocalized()) {
                    $language = 'default';
                }  
### Code example 
```php
// your code
```

# Feature Request

**Comment by weisswurstkanone** [comment]
this should be fixed already. see https://github.com/pimcore/pimcore/issues/3551
