### ISSUE TITLE
[Objects] Add Info Icon for Tooltip

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#3609]
Add a Info Icon at the end of an Label when the given Field has a Tooltip

![i arow](https://user-images.githubusercontent.com/1086343/48555730-528c9d00-e8e2-11e8-8d59-a8bf8682c894.png)

**Comment by zieglerh** [comment]
I just copied this because we need it in Pimcore v4, but had to make a little adjustment. I'm not sure if this is still the same in Pimcore 5, so please validate it @brusch 
Tooltips do not show on not editable fields

Either show tooltips on not editable fields or disable the icon with:
```
if(l.tooltip && !(l.noteditable || noteditable)) {
    l.title += ' <span class="pimcore_object_label_icon pimcore_icon_info"></span>';
}
```

**Comment by zieglerh** [comment]
About the tooltip not showing on disabled items is browser specific:
Ref: https://www.sencha.com/forum/showthread.php?310184-Show-Tooltip-on-disabled-Button
Adding this will fix it:
```
.x-item-disabled {
    pointer-events: all;
}
```

**Comment by brusch** [comment]
@zieglerh the ExtJS fix is already there, but thanks anyway :) 
see https://github.com/pimcore/pimcore/blob/543fd1bcfe057c3fd7e6cad2ae00764fc7d30af0/bundles/AdminBundle/Resources/public/css/ext-modifications.css#L408
