### ISSUE TITLE
[Feature request] Ability to hide workflow transitions in backend

### ISSUE THREAD

**Issue by gadget60** [pimcore/pimcore#3616]
### Feature request
  
For workflow PLACES there exists a parameter "visibleInHeader". I wish to have an equal setting for workflow TRANSITIONS: A setting that just hides a transition from being displayed in the workflow actions menu. 

Background: We have set up a workflow that is partionally automated, meaning some transitions will be started by imports via maintenance cron. 

![image](https://user-images.githubusercontent.com/23076771/48620760-79f66f00-e9a1-11e8-8d2e-7089f615aa38.png)
To get an image: 
Imported products both require manual interaction (assigning assets - lower part in the workflow above) as well as augumenting data from a second source (upper part in the workflow above) in order to be published. I therefore would like to hide the automated transitions in Pimcore backend. 
To be clear: This is not a permission issue, setting up a guard just arises other problems. I just want the user to see the actions (transitions) that he actually is supposed to apply!

**Comment by gadget60** [comment]
Yes, I need to display some of the transitions... Thanks for your suggestion anyway.

**Comment by markus-moser** [comment]
I've done this with guards. Why do guards not work in your case?

**Comment by markus-moser** [comment]
But yes, might be a good idea to a flag for this.

**Comment by fashxp** [comment]
I would try to go for guards ... because it might prove useful at some point, that a admin user would still be able to trigger a certain transition manually ... because you never know ;-)

**Comment by gadget60** [comment]
@markus-moser: Actually I did solve it using a guard, but what I came up with is pretty ugly. I require a certain role, something like:
```
        guard: "is_fully_authenticated() and has_role('ROLE_DATA_IMPORT')"
```
...whereby the user does not belong to the ROLE_DATA_IMPORT. So far, so good - transition is hidden.
 
Problem now is: At some point the transition MUST be applied during the import, launched either via console command (where no permission system is present at all) or manually in the backend GUI, launched by the same user that does not belong to ROLE_DATA_IMPORT. In both cases I must create/inject a fake token in order to not throw an exception. This is why I said it is not permission issue. The user actually *has* permission to launch the import, which in turn applies the transition.

You solved this using guards - maybe you enlighten me at this point....? :-)

**Comment by markus-moser** [comment]
@gadget60 I had exactly the same situations. There are some different possibilities to solve it. I used a custom guard event subscriber instead of a guard expression. Then it's possible to disable the guard for the import process.

**Comment by fashxp** [comment]
@gadget60 didn't try it, but shouldn't that work? 
`guard: "(is_fully_authenticated() and has_role('ROLE_DATA_IMPORT')) or (!is_fully_authenticated())" `

**Comment by markus-moser** [comment]
@fashxp should work for the importer but not if the user has the possibility to trigger the importer in the backend and the authenticated user applies to the import job too.

**Comment by gadget60** [comment]
Nope - just gave it a try. It does not even work for the console command. As soon as I use any guard that checks for authentication I get an exception "There are no tokens available for workflow product_workflow."
Also see https://github.com/symfony/symfony/issues/26401

**Comment by markus-moser** [comment]
Maybe a good solution improvement for the future could be if we add a `is_in_actions_button()` helper function for the expressions.

**Comment by fashxp** [comment]
ok let's reopen that and see if adding this helper is possible. 
pull requests are welcome ;-)

**Comment by BlackbitNeueMedien** [comment]
Any news on this @fashxp / @brusch ?
Just stumbled upon this problem when executing a command which saves data objects which have an event handler which cares for applying workflow transitions based on the object's data.
Would do a PR but do not know where a good plac would be to add `$this->tokenStorage->setToken(new AnonymousToken('a_secret', 'username'));` - I also do not know what exactly the secret is good for as I can set it to anything.

**Comment by fashxp** [comment]
not from my side ... actually also have no idea where to place that and what it does.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Comment by JSMD-maintainers** [comment]
It would be a really handy feature also for us to have the option to hide transitions via a flag. So +1 from our side to have this feature implemented in the near future
