### ISSUE TITLE
Just direct children functionality not working properly

### ISSUE THREAD

**Issue by amarjeet6694** [pimcore/pimcore#3625]
On clicking **"just direct children**" checkbox on folder grid, it should display children of 1 hierarchy only but showing all the records.

**Comment by weisswurstkanone** [comment]
Which build are we talking about?
Maybe already fixed, see https://github.com/pimcore/pimcore/issues/2860

**Comment by amarjeet6694** [comment]
The issue is reproducible at https://demo-advanced.pimcore.org/admin
