### ISSUE TITLE
Restructure object grid configuration dialog

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#3631]
* use accordion for operators
* split them up into groups
* get rid of renderer column, should be a operator instead
* offer a preview for the first result item

**Comment by weisswurstkanone** [comment]
![image](https://user-images.githubusercontent.com/6142086/48780670-bcd68080-ecda-11e8-942e-6d14887facea.png)

**Comment by brusch** [comment]
Resolved by #3633
