### ISSUE TITLE
Documented instructions for cloning elements out of date

### ISSUE THREAD

**Issue by dkidd** [pimcore/pimcore#3638]
The documentation for cloning elements (doc/Development_Documentation/18_Tools_and_Features/31_Cloning Elements.md) is out of date. The `Service` classes have been substantially refactored, and the code examples no longer work.

I'd be happy to suggest revisions, but I'm not sure of the best practice for getting the current admin user.

**Comment by weisswurstkanone** [comment]
What exactly is out of date ?

**Comment by dkidd** [comment]
Sorry. I should have clarified that. The documentation says:

> If you want to get a persistent copy use the copyAsChildmethod of the corresponding service. E.g.

> `Pimcore\Model\Asset\Service::copyAsChild($target,` $source)

> where `$source` is the source element and `$target` the parent element of the new element. This will also create a unique element key (or filename for asset elements).


`Pimcore\Model\Asset\Service::copyAsChild()` is no longer a static function. Neither are the equivalent functions for DataObjects and Documents.
