### ISSUE TITLE
Performance impact of IndexFieldSelectionCombo in 5.4+

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#3640]
After upgrading to version 5.4, I noticed a drop in performance on all pages that create a product listing via the ecommerce framework. After some digging, I found that this is related to the `IndexFieldSelectionCombo`. In its getOptions method, it checks if the Ecommerce Framework is installed. This eventually calls the `PimcoreBundleLocator::findBundlesInPaths` method. Since the static files of the AdminBundle were moved out of `web/pimcore/static6` into the bundle itself, the amount of files that is checked there increased massively. In my case, the Symfony finder takes now ~1 second to iterate over all files, making all product listings about a second slower.

**Comment by dpfaffenbauer** [comment]
why does a EcommerceFramework Editable even have to check if it is installed when it is only available when its installed?!

**Comment by fashxp** [comment]
actually a good question. 
I just removed these lines of code and could install ecommerce framework without problems. 
I'll have a more detailed look into it, maybe we can get rid of the check at all....

**Comment by fashxp** [comment]
didn't find any problems without this check, so removed it.
