### ISSUE TITLE
Button Layout element JS Error 

### ISSUE THREAD

**Issue by AroraVaishali** [pimcore/pimcore#3657]
# Bug Report
 
  
### Expected behavior 
  It should be work with no JS error
### Actual behavior  
  unable to open/add object of class TestButtonClass (contains Button Layout)
### Steps to reproduce  
  1) Open https://demo-advanced.pimcore.org
   2)Created TestButtonClass -> which contains input and button layout
   3) Add a new object of this class , it displays javascript error TypeError: "eval(...) is undefined"
![button](https://user-images.githubusercontent.com/19402815/49059569-9e6b0a80-f22f-11e8-85e8-bf2b59b14b75.png)
 
### Code example 
```php
// your code
```

# Feature Request

**Comment by brusch** [comment]
The button should alway have a handler function assigned, anyway ... I've now integrated a check.

**Comment by AroraVaishali** [comment]
ok. Thanks
