### ISSUE TITLE
trigger necessary postupdate.php when updating with composer

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#366]
after an composer-update to dev-master, all required versions of ```postupdate.php``` should be triggered. maybe when triggering the composer post update method? (```\Pimcore\Composer::postUpdate( $event );```)

**Comment by brusch** [comment]
Updating using composer is currently not supported, you should use the live-updater. 
Just out of interest, how did you forced the update to the dev-master?

**Comment by solverat** [comment]
that's a pity... because our deployment is completely composer based. I've created an custom post-install-cmd, as long pimcore itself doesn't have its own repo:

```composer
 "require" : {
        "pimcore/pimcore" : "dev-master", 
    },

  "autoload": {
        "psr-4": {
            "Dachcom\\Composer\\": "vendor/dachcom/composer",
            "Pimcore\\": "pimcore/lib/Pimcore"
        }
    },
    "scripts": {
        "post-install-cmd":"Dachcom\\Composer\\PimcoreInstaller::postInstallEvent",
        "post-update-cmd": "Dachcom\\Composer\\PimcoreInstaller::postUpdateEvent"
    }
``` 

and thats the update part of my install script. in short:

- get the pimcore folder from vendor
- move it to root

```php

public static function postUpdateEvent(Event $event) {

        list($installPath, $vendorPath) = self::prepareBaseDirectories($event);

        $fromPath = $vendorPath . '/pimcore/pimcore/';
        $srcPath = $installPath  .'/';

        $fromCorePath = $fromPath . '/pimcore/';
        $newSrcPath = $srcPath . 'pimcore/';

        self::deleteFolder( $newSrcPath );

        mkdir( $newSrcPath, 0755);

        self::moveFolder($fromCorePath, $newSrcPath);

        self::deleteFolder($vendorPath . '/pimcore/pimcore');

        //it would be perfect if the postupdate.php will be triggered in here.
        \Pimcore\Composer::postUpdate( $event );

    }

```

**Comment by fashxp** [comment]
The problem is that the postupdate scripts need to be executed in an environment based on their build since they might need class files etc. that exist only in their specific build.

Do you have an idea how we could deal with that issue?

**Comment by brusch** [comment]
see https://github.com/pimcore/pimcore/issues/373

This should help as well :-)
