### ISSUE TITLE
[Improvement] Information popin before running batch process.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3666]
Hello,

I woul like to suggest an improvement about using batch feature on object grids.
Actually, the process is risky and some customer are pretty frightned about the batch processing because no summary information are given before the process.

At least, it would be great to have a small popin saying:
"You are about to update X items, are you ok ?", something like that to prevent errors.
To be more precise, enduser always ask themselves, does it update only those i see or all ? (only current page or all element included in the resut even in the other paging page).

It would improve UX and confidence about batch processing.

Thanks.

**Comment by brusch** [comment]
Imho that would be redundant, we have this information already here: 

![image](https://user-images.githubusercontent.com/142037/51909518-248d0400-23cd-11e9-92bd-e4c17f604712.png)

and here: 

![image](https://user-images.githubusercontent.com/142037/51909540-31a9f300-23cd-11e9-801a-4eac10478cc5.png)
