### ISSUE TITLE
[New feature] More granular permissions on custom reports than all/none.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3673]
Hello,

Custom reports is a very powerfull feature of Pimcore we use more and more.
It can provide to end user some metrics, dashboard, specific datas listing he can filter and export, etc.

But there a really missing feature to be able to use in real world all this power: be able to set permission on them.
Often those reports deliver sensible datas, it is their purpose. But anybody can access to them. With the current permissions settings, we can just set actually: user can not access to any reports or user can access to all reports.

**Proposition:**
It would be very usefull to be able to set user/role permission per custom reports. This way we can deliver the information to the right people without leaking sensible information.

And with the RGPD, being able to ensure datas are only deliver to user/role permission has been setted will be great.

Like for classes, a select list of the custom reports could be added (if none selected, all are accesible, so it won't break backward compatibility).

It would really be a top new feature making a big jump in custom report usability!

Thanks for reading this suggestion.

**Comment by fashxp** [comment]
I would prefer to configure the visibility of a custom report directly in custom reports configuration rather that in user permission settings.

**Comment by Yivan** [comment]
Thanks @fashxp for your attention to this issue.
Yes, if you think it is better to set this directly in the custom reports, it will works too. The idea is just to be able to restrict custom reports to defined users/roles.
Have a nice evening.
