### ISSUE TITLE
Bug: Localized fields of object version

### ISSUE THREAD

**Issue by iventura** [pimcore/pimcore#3676]
# Bug Report

- Behavior is reproducible on http://demo-basic.pimcore.org/admin/ (admin/demo) 
  
### Steps to reproduce  

1) change the data of one of the localized fields of any DataObject in admin GUI
2) save only new version of the object by click the button
3) click save&publish
4) click refresh objects data or the hole page (does not matter)

You will get the old data.

**Comment by Seosreda** [comment]
Have the same problem, but with PHP API.

**Comment by djbodya** [comment]
Have the same problem((( Waiting for result) Now use the version object to get the data from localized via PHP API.

**Comment by iventura** [comment]
Hallo, i tested the solution, but it does not solved the issue :(

**Comment by weisswurstkanone** [comment]
Please give it another try. We found out that the demo-basic instance hasn't been updated for a while. Should be on the latest state now.

**Comment by iventura** [comment]
thank you a lot for your reply and the fix. i just tested it on the demo instance, and it works now! So the fix resolved the issue. But i checked it yesterday on my local test environment with the current version 5.5.4 and yours fix, and it does not helped me. Maybe due to the other changes? Anyway, i can wait for the next official release 5.6.0 on 12' Dec and test again.

**Comment by ivan-vetoskin-racechip** [comment]
...and i can reproduce it again on demo instance and for DE specific field

**Comment by ivan-vetoskin-racechip** [comment]
Hallo @brusch, @weisswurstkanone, do you have any updates or should i create a new issue?

**Comment by brusch** [comment]
@ivan-vetoskin-racechip I've just tested it on the demo, but I'm not able to reproduce it, see: 

![21-01-_2019_09-48-29](https://user-images.githubusercontent.com/142037/51462780-c1162d00-1d61-11e9-8173-ae07870b1f1c.gif)

**Comment by ivan-vetoskin-racechip** [comment]
Please test with DE locale

**Comment by ivan-vetoskin-racechip** [comment]
i was able to reproduce it now for German language, but only if the dataobject has already versions before. By the first save and save&publish it worked well.

**Comment by brusch** [comment]
Reproducible, created a new ticket: #3851
