### ISSUE TITLE
Can't update to 5.5.4

### ISSUE THREAD

**Issue by lp741** [pimcore/pimcore#3677]
# Update from 5.5.3 to 5.5.4 ignored!

### Expect to update 
```json
  "require": {
    "php": ">=7.1",
    "wikimedia/composer-merge-plugin": "^1.4",
    "pimcore/pimcore": "~5.5.0"
  },
```
this is my composer.json

I tried 

```
$ COMPOSER_MEMORY_LIMIT=3G composer update
```

it complete correctly bu on admin view it still notify update available! 

  ```
        {
            "name": "pimcore/pimcore",
            "version": "v5.5.3",
            "source": {
                "type": "git",
                "url": "https://github.com/pimcore/pimcore.git",
                "reference": "593880d6b3170cb095e7b47682e197845031e3a2"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/pimcore/pimcore/zipball/593880d6b3170cb095e7b47682e197845031e3a2",
                "reference": "593880d6b3170cb095e7b47682e197845031e3a2",
                "shasum": ""
            },
```

**Comment by brusch** [comment]
-> Composer
Please use our forum for support, thanks!

**Comment by blankse** [comment]
I had also a problem to update to 5.5.4.

My reason was the missing php extension zend-opcache. Which is a dependency of amnuts/opcache-gui.

Pimcore increased the version of this dependency:
https://github.com/pimcore/pimcore/commit/c46d708261d92345e32dcc771d7a6ce5ab8e3f7c#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780
