### ISSUE TITLE
Timeout during installation

### ISSUE THREAD

**Issue by khusseini** [pimcore/pimcore#3681]
# Bug Report
 
  
### Expected behavior 
Installer should not run into timeout, or the timeout should be configurable
  
### Actual behavior  
`
 * The process "'/usr/bin/php' '/var/www/bin/console' 'pimcore:deployment:classes-rebuild' '-c'" exceeded the timeout of 60 seconds.
`

A lot of times when I install pimcore, I get a timeout from `pimcore:deployment:classes-rebuild`. Is there any way to increase the timeout?

**Comment by brusch** [comment]
This tasks shouldn't take more than 1-2 secs on an average system, no idea why it takes so long for you. 
Anyway, I've increased the timeout to 120 secs, what  shouldn't hurt.
