### ISSUE TITLE
[Bug] CSS errors

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3684]
Hello,

Our linting tools reported the following CSS errors:
https://github.com/pimcore/pimcore/blob/b714c00002cdfbed22ae414eb8bb5d352d9c59c1/bundles/AdminBundle/Resources/public/css/admin.css#L1970
https://github.com/pimcore/pimcore/blob/b714c00002cdfbed22ae414eb8bb5d352d9c59c1/bundles/AdminBundle/Resources/public/css/ext-modifications.css#L408

Have a nice day.

**Comment by weisswurstkanone** [comment]
thx
