### ISSUE TITLE
User rights for localized fields

### ISSUE THREAD

**Issue by incoxx** [pimcore/pimcore#3686]
# Bug Report
 
  
### Expected behavior 
 
I have a user role for a product manager in Poland. He should be able to see German an English localized texts and he will have the right to edit texts only in Polish language (all other languages are read only)

### Actual behavior  

I created a new role "product manager PL" and in the "Shared translation settings":
View Geman an Engish. 
View and edit Polish

Result in the object edtior: The role is able to edit ALL languages without restriction.

### Steps to reproduce  
  
I created a role "test" and a user "test" on the pimcore basic testsystem.
The role "test" has the right to view "English and German" and right to edit "German"
If you open an object with localized data (e.g. the News object) you are able to edit both languages

**Comment by ckemptner** [comment]
I think you are mistaking "shared translations" settings (which are mainly used for documents / CMS pages) with the "localized fields" settings for data objects. If you want to restrict languages for editors on data objects you don't have to use "shared translations" but rather the "localized fields" settings directly in the "workspaces" tab, where you also define the access rights.

**Comment by incoxx** [comment]
Hi Christian,
you are right!!! 
Now i made the settings within the workspaces tab:
![image](https://user-images.githubusercontent.com/21988262/49426264-59e7ed80-f7a0-11e8-9920-bda37c08cd61.png)
But the behaviour is the same. For the object path /PIM/Produkte i gave the access right "Bearbeiten" for the Polish language.
But when i login with a user and the assigned role - same result. I am able to edit all other languages

**Comment by incoxx** [comment]
PS: PIMCORE Version is 5.5.3

**Comment by ckemptner** [comment]
"Roles" override "Users" => Check your "Roles" Settings (Workspaces Tab again)
Next time please use our community forums https://talk.pimcore.org/
