### ISSUE TITLE
ImageAdvanced: Wrong bounds for hotspot marker

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#3687]
# Bug Report
  
### Expected behavior 
It should be possible to move a marker to the upper edge of an image. 
It should not be possible to move a marker below the bottom edge of the image.
  
### Actual behavior  
You cannot put the marker on the top edge because the tip of the marker is used to store its position but you cannot move the marker above the image so that only the tip remains inside the image.
You can put the marker below the bottom edge of the image resulting in bottom position > 100%.

Both bugs originate because the tip of the marker is used to store the position while the top-left-point of the marker image is used to define the marker's possible region.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
