### ISSUE TITLE
ExtJs 6 - Publish of objects via context menu bug

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#369]
When I try to publish an object via context menu the strikethrough styling doesn't disappear:

![image](https://cloud.githubusercontent.com/assets/4639428/12200167/aa557f3e-b61d-11e5-9432-2e0bac593eff.png)

This bug only occures when the object is already unpublished after the tree node was loaded (not immediatly after clicking on unpublish in the context menu)

**Comment by weisswurstkanone** [comment]
fixed in 3595
