### ISSUE TITLE
OwnerAwareField shouldn't save Owner

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#3698]
# Bug Report

I have a Link Localizedfield in a class with many languages.

The Dao couldn't load the data, because the serialized string is cut off in the database.

Here is the owner set:
https://github.com/pimcore/pimcore/blob/master/models/DataObject/Localizedfield/Dao.php#L537

I think it should be removed before saving.

### Steps to reproduce 

1. Create class with panel, localizedfield, input and link
![test](https://user-images.githubusercontent.com/998558/49474056-fdbeb100-f813-11e8-9a5f-e63e22a003a1.jpg)
2. Create data object with filled input and link
3. Save and Publish
3. Reload the tab (Required!)
4. Change the input
5. Save and Publish
6. The owner is filled in the db table
![test2](https://user-images.githubusercontent.com/998558/49474208-6c9c0a00-f814-11e8-9aae-a524235cf80c.jpg)

**Comment by weisswurstkanone** [comment]
IMHO, the right place to hanle this (compare it with other data types like HotspotImage) is in Pimcore\Model\DataObject\ClassDefinition\Data\Link::getDataForResource and getDataFromResource.

Just make sure that it doesn't get serialized and set the owner again in getDataFromResource.

**Comment by brusch** [comment]
@blankse Could you please create a new PR considering the comment of @weisswurstkanone 
Thanks a lot!

**Comment by blankse** [comment]
@weisswurstkanone @brusch 
I created a new PR.

I havent't tested it yet. I will it tomorrow.

**Comment by dpfaffenbauer** [comment]
this looks very familiar to https://github.com/pimcore/pimcore/issues/3543
