### ISSUE TITLE
[DataObjects] Objects with readonly DateTime do not open anymore

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#3718]
related to #3693

**Comment by BlackbitNeueMedien** [comment]
Regarding the docs Ext.form.field.Date and Ext.form.field.Time do support setReadOnly:
https://docs.sencha.com/ext/6.2.0/classic/Ext.form.field.Date.html#method-setReadOnly
https://docs.sencha.com/extjs/6.2.0/classic/Ext.form.field.Time.html#method-setReadOnly
