### ISSUE TITLE
Add Character count to WYSIWYG

### ISSUE THREAD

**Issue by ulilicht** [pimcore/pimcore#3720]
# Feature Request 
## Feature description 
With the tickets #3717 and #3714, a character count was added to Textarea and Input elements. It would be great to have the same feature for WYSIWYG fields as well. 

This would include: 
- A character count info on the WYSIWYG Editor
- A setting in Pimcore DataObject how many characters are allowed for this input

There are plugins for CKEditor to realize this feature, e.g. this one: http://w8tcha.github.io/CKEditor-WordCount-Plugin/ 

My recommendation would be to include the plugin with the configuration
```
config.extraPlugins = 'wordcount';
config.wordcount = {
    // Whether or not you want to show the Word Count
    showWordCount: false,

    // Whether or not you want to show the Paragraphs Count
    showParagraphs: true,

    // Whether or not you want to show the Char Count
    showCharCount: true,

    // Whether or not you want to count Spaces as Chars
    countSpacesAsChars: true,

    // Maximum allowed Char Count
    maxCharCount: ##PIMCORE_VALUE##
};
```

Does anyone else need this feature?

**Comment by brusch** [comment]
Hmm, I'm afraid that this plugin doesn't work with CKEditor's inline mode, has anyone tested it?
