### ISSUE TITLE
[Asset] Image Editor: increase size of image that get loaded into the editor

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3723]
Hello,

As Pimcore admin logged in the Pimcore backend, using miniPaint image editor on an image asset, the opened image is not open with the good resolution.
Concequence is that if the image is save just after being opened in the image editor, the new image lost quality as resolution is splitted by a factor 2 it seems.
So if an enduser use the editor, he will degrade the resolution of the assets... : ( (pretty dangerous for system in production, actually the only way to prevent this is to disable temporarly the image editor).

Here is an opened image on the Pimcore demo:

![image-editor](https://user-images.githubusercontent.com/9025839/49655788-e5c97600-fa3b-11e8-92e0-dbc32be65700.png)

Here is the same image opened in the online demo of miniPaint:

![image-editor-demo](https://user-images.githubusercontent.com/9025839/49655798-ecf08400-fa3b-11e8-8ac4-134f9ba549da.png)

So the problem seems to be on the Pimcore side i think.

Thanks.

**Comment by brusch** [comment]
That's acutally no bug, it is necessary that Pimcore converts images to a smaller size and to a format miniPaint can read. It used to be 1000x1000 pixels at maximum, I've increased it now to 3000x3000 which seems to work on an average PC.

**Comment by Yivan** [comment]
@brusch Thanks for your explaination and fix.

I understand this is a miniPaint limitation. Can i suggest the folowing:
- if image is too big to display a message saying "_Be carreful: picture was too big and has been reduced to XXX x YYY pixels_". Because if user just open the image, make a small modification and save it, he can miss the fact that resolution of the image asset has been reduced.
I really think it would be safer to inform the user via such an alert message, so he doesn't degrate asset resolution unintentionnaly.

Thanks.

**Comment by Yivan** [comment]
@brusch 
Sorry to come back on this, we are using more and more pimcore as a couple PIM/website, so image asset have sometime really big resolution. I know it has been extended to 3000x3000, but with PIM sometimes there a more bigger images.
And actually customer can destroy the image quality (downsizing the resolution) without any message informing it. It is problematic for a PIM centralized image. Please read my previous comment. Do you think it is a good idea to prevent this ?

Thanks for reading me.

**Comment by fashxp** [comment]
@Yivan  could you provide a PR for it?

**Comment by Yivan** [comment]
@fashxp Yes, ok i will try to make it.
Thanks!

**Comment by Yivan** [comment]
@fashxp I just made a PR https://github.com/pimcore/pimcore/pull/4551
I don't know why it hasn't been coded like this in first, it seems to work pretty well and there is no more limitation (so no more warning message to display ! : ) )
