### ISSUE TITLE
Table Datatype - add option for column header

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#3724]
Add an option to define a header for the table datatype. 
Currently the only way to do this is to add data to the first row - but this is editable.

A header would in theory work with the structuredTable - but there is no way to have unlimited rows on this datatype so it is not an option either.

**Comment by brusch** [comment]
Wouldn't it be better to use the structured table data-type instead?

**Comment by ultramegatom** [comment]
@brusch 
My use case is having a table with a fixed number of columns and unlimited rows. Im afraid i cannot do this with the structured table because i have to define the exact number of rows (and add key/label 
 for the rows).

The normal table datatype allows for fixed- Rows/Cols. If i tick either of this it should be possible to add the corresponding header to the table. Or is there something im missing?
![image](https://user-images.githubusercontent.com/7206334/51907100-2c957580-23c6-11e9-8e73-af8af174df51.png)

**Comment by brusch** [comment]
Hmm, maybe another checkbox "Use first row as header" that is available if "Cols fixed" is ticked 🤔
PR's are welcome 🤓

**Comment by RogerWaters** [comment]
We run into the same situation. However it will not be really useful to only define fixed column header. Therefore we decided to create a new datatype for every table we need. 
It would be nice if there will be a new table-type with the following options:
- allow add row (checkbox)
- max rows
- initial sort column
  - autosort / manual sort
- column definitions
  - label (translatable)
  - key
  - required
  - type (date, numeric, text, checkbox, select, calculated)
    - typespecific configurations (datetimeformat, numericformat, maxlength, minlength, options)
  - action buttons (delete, add)

Probably this solution is a littlebit overhead for your needs, but I want to place it here :-)
