### ISSUE TITLE
[Data Object] Remove dirty indicator in data-type grids

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#3725]
Elements in ```Many-To-Many Object Relations``` get a red dirty-marker when elements are added - ```Many-To-Many Relations``` dont.

Fields in Tables also get marked.

After saving the object the marker still stays. 
The marker should either be removed entirely, or get removed after saving the objekt.

**Comment by fashxp** [comment]
do you have a screenshot?

**Comment by ultramegatom** [comment]
![b3afce74-ac6e-4be5-8b53-1599ca560cf6](https://user-images.githubusercontent.com/7206334/49656614-11e5f680-fa3e-11e8-81ab-7b1ae9d599dc.GIF)

**Comment by brusch** [comment]
In my opinion we should remove them entirely.
