### ISSUE TITLE
[Data Objects] Many-To-Many Object Relation Performance Issues in Admin UI

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#3737]
The problem is that the data-type doesn't utilize `getRelationData()` anymore to obtain the relational data, instead all objects are loaded and `getDataForEditmode()` is called. 

See: https://github.com/pimcore/pimcore/blob/cf8186c048650146a825b07ce91f02953282437c/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L554

**Comment by weisswurstkanone** [comment]
are you referring to this commit ?
https://github.com/pimcore/pimcore/commit/2b99cea2f0f39e42c79681aec81ccd1e42c5d699

**Comment by weisswurstkanone** [comment]
temporary fix: use the old strategy if no visible fields are selected.
long-term solution: lazy load the metadata (just like the path formatter does)

**Comment by blankse** [comment]
I don't test it, but after looking in the fix i think it is not enough. The getter method will also be executed. Am I wrong?

**Comment by weisswurstkanone** [comment]
when, where ?

**Comment by blankse** [comment]
https://github.com/pimcore/pimcore/blob/dd9d7a856bba6621c51a514d169d28ac76fcb7f9/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L566-L568

**Comment by weisswurstkanone** [comment]
good catch

**Comment by fashxp** [comment]
still relevant?

**Comment by weisswurstkanone** [comment]
Don't think so. Just enable async loading. 

see https://github.com/pimcore/pimcore/commit/62204339d7c582612596e877b52f29fe834790ac

![image](https://user-images.githubusercontent.com/6142086/71171623-844b0280-225e-11ea-8b7e-f17e13e7c017.png)
