### ISSUE TITLE
[Ecommerce] Default rounding mode for decimals to PHP_ROUND_HALF_UP

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#3738]
I am curious as to why _round to even_ was chosen as the default rounding method in this ecommerce context. Would it not make sense to replace it with PHP_ROUND_HALF_UP in [the Decimal class](https://github.com/pimcore/pimcore/blob/cf8186c048650146a825b07ce91f02953282437c/bundles/EcommerceFrameworkBundle/Type/Decimal.php#L114) instead? 

In the following scenario, the prices shown to the customer to not line up because the 0.5 cents are rounded down in the discount and in the grant total:
Subtotal: 19.45
Discount 10%: 1.94
Total: 17.50

**Comment by BlackbitNeueMedien** [comment]
Well, nevermind. That wouldn't really change anything in my case, would it?
But should it not be changed nonetheless?

**Comment by fashxp** [comment]
a good question. 
but in your case, if you are using a scale of 4 (which is default), there should be no rounding taking place. 
is that your actual result of the calculations?

**Comment by fashxp** [comment]
it think we should change it to `PHP_ROUND_HALF_UP` ... but I'm not sure if we should add it to 5.6? What do you think?
