### ISSUE TITLE
CORS - Access-Control-Request-Headers for REST API

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#374]
Using the REST API, it doesn't set any Access-Control-Request-Headers.
So we tried to set them in the .htaccess:
```
Header add Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"
```
"Access-Control-Allow-Origin" worked for our custom controllers, but if we call http://www.domaine.com/webservice/rest/... the header was not set. Maybe something in Pimcore prevent this, intentionnaly or maybe it's a bug.

The idea is to permit to configure those header (at least "Access-Control-Allow-Origin") or at least leave the possibility to set them in the htaccess.
If we could be great to configure them for each user (maybe by adding a field below the user API Key),
and have the same option globaly (in settings for instance), so i many user we can rely on this global option.

**Comment by brusch** [comment]
I don't think that pimcore is able to prevent headers added by 'Header add', if pimcore does anything like this, please let us know, so that we can fix this. 

I also think that the CORS headers should not be configured in pimcore and absolutely not on user level.

**Comment by Yivan** [comment]
Just tested with fresh install and CORS in htaccess are well used for webservice module and rest controller. It was a problem on my side.

I agree with you and anderstand the choice to keep those configuration on the server side.

Thanks for your fast answer.
