### ISSUE TITLE
Set empty mhref in Object Bricks

### ISSUE THREAD

**Issue by UgurT** [pimcore/pimcore#3757]
I expected an empty object relation in my object brick.

Workflow in frontend:
1. The logged User has no more products
2. He clicks all checkboxes empty
3. The User clicks on the form to save. 

I expected an empty object relation in my object brick but is not empty. (In database)

$objectBrick = new DataObject\Objectbrick\Data\myObjectBrick($this);
$objectBrick->setMyObjectRelation($myRelationValues);
$this->getObjectBrick()->setMyObjectBrick($objectBrick);
$this->save();

After saving an empty value ($myRelationValues) is ignored. The relation in the database is not deleted. 
If values are present, the save works and relations in the database will be updated.

**Comment by weisswurstkanone** [comment]
please save the brick definition so this can have an effect
