### ISSUE TITLE
Pimcore Editmode Toolbar

### ISSUE THREAD

**Issue by tobiasfeldmethwalter** [pimcore/pimcore#3771]
Please create a way to make the toolbar again permanently visible. Currently, this is only visible when hovering over an element.
This is very irritating from time to time - especially for customers who maintain content themselves.
Many Thanks

**Comment by fashxp** [comment]
should be possible already. 
use `controlsTrigger` option in areablock configuration, see also https://pimcore.com/docs/5.x/Development_Documentation/Documents/Editables/Areablock/index.html and #3549
