### ISSUE TITLE
Tree Structure: Data in multiple hierarchies not sorted alphabetically

### ISSUE THREAD

**Issue by dezuludani** [pimcore/pimcore#3780]
On Pimcore version 5.2.1 Build: 217 localized data is imported and put in multiple hierarchies. In some cases, we found that the data is not sorted even though there is no customization on the sorting. When we removed the special characters like Hyphen (-), Double quotes (" ") and accented characters, the data showing up correctly.

![sort](https://user-images.githubusercontent.com/41774824/50286200-add32180-0484-11e9-9969-869a09686524.PNG)

Expected behavior - Data in the tree structure should always appear alphabetically when there is no customization.
  
Actual behavior - Some data with special characters are not sorted alphabetically.

**Comment by fashxp** [comment]
why was this closed again?

**Comment by dezuludani** [comment]
@fashxp Team was able to fix this one.
