### ISSUE TITLE
[Search] Error when class filter is active and dialog get's moved to tab

### ISSUE THREAD

**Issue by Debanshu123** [pimcore/pimcore#3781]
While you search Data Object the screen comes where user can search all data objects records using different filters.

Now if user clicks on the click on **"Move to Tab"** option the screen freezes and only if you refresh the screen the system works. Also in the console we get the following error:

Uncaught TypeError: Cannot read property 'remove' of null
    at E.unregister (ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22)
    at E.destroy (ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22)
    at E.callParent (ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22)
    at E.destroy (ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22)
    at Object.destroy (ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22)
    at E.beforeDestroy (ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22)
    at E.destroy (ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22)
    at E.callParent (ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22)
    at E.destroy (ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22)
    at E.doRemove (ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22)
unregister @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
callParent @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
(anonymous) @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
beforeDestroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
callParent @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
(anonymous) @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
doRemove @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
beforeDestroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
callParent @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
(anonymous) @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
callParent @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
(anonymous) @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
doRemove @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
beforeDestroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
beforeDestroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
beforeDestroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
callParent @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
(anonymous) @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
callParent @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
(anonymous) @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
doRemove @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
beforeDestroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
beforeDestroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
callParent @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
(anonymous) @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
doRemove @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
beforeDestroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
beforeDestroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
callParent @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
(anonymous) @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
doRemove @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
beforeDestroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
beforeDestroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
callParent @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
(anonymous) @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
destroy @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
doRemove @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
doRemove @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
remove @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
remove @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
closeTab @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
onCloseClick @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
onClick @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
fire @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
fire @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
publish @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
doDelegatedEvent @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
onDelegatedEvent @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22
(anonymous) @ ext-all.js?_dc=21053c366507cbd167e213c4bb1b46e70cf37a00:22

**Comment by fashxp** [comment]
hmm, cannot really follow you. for me everything works fine.
can you provide maybe a screenshot and more information about your pimcore and browser version?

**Comment by Debanshu123** [comment]
I have replicated the same on @diveshp3 system, he can help you more on this.

**Comment by Debanshu123** [comment]
![screenshot from 2018-12-21 16 29 17](https://user-images.githubusercontent.com/46043918/50339733-221dcb80-053e-11e9-9293-54e0c30af613.png)


![screenshot from 2018-12-21 16 30 43](https://user-images.githubusercontent.com/46043918/50339772-4a0d2f00-053e-11e9-9dfe-c609d898a9e3.png)


Now once you click on the close icon the screen freezes and you need to reload the system or else it stops working.

**Comment by fashxp** [comment]
I understand, can you reproduce that on our public demos? because I can't :(

**Comment by Debanshu123** [comment]
I tested on you demo instance even on the latest instance and i can reproduce the same.

**Comment by fashxp** [comment]
ahh, it appears when you have more than one search tab open

**Comment by fashxp** [comment]
ok, now I got it. appears when class is selected. 
if not, everything works fine

**Comment by Debanshu123** [comment]
Yes.

**Comment by dvesh3** [comment]
duplicate #1016
