### ISSUE TITLE
Checkbox with default value checked is NULL in database

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#3784]
# Bug Report  
### Expected behavior 
  A object datatype checkbox with default option checked should insert 1 in the database if no user interaction takes place.

### Actual behavior  
  A object datatype checkbox with default option checked does insert NULL in the database if no user interaction takes place - same as with object datatype checkboxes which do not have a default option checked selected.
### Steps to reproduce  
Create a checkbox datatype in some object. Check the default value. 
  ![checkbox-default-checked](https://user-images.githubusercontent.com/2771909/50335423-8e330c00-050b-11e9-8fc3-3ee9b940c672.png)
Create some object of this and save it. Value in database will be null. To get a 1, you'll need to uncheck the default checked checkbox and check it again.

Tested on Pimcore v5.5.4

**Comment by NiklasBr** [comment]
We have also encountered this.

Do you think it is related to  #3585?

**Comment by prugala** [comment]
@Cruiser13 @NiklasBr I fixed it in PR #3853

**Comment by Cruiser13** [comment]
Thanks!
