### ISSUE TITLE
Pagination on object folders does not function correctly

### ISSUE THREAD

**Issue by cleggypdc** [pimcore/pimcore#379]
The dropdown initially shows 20 per page, whereas the page text says 1-25. 

The grid shows 20 items but paging causes the next page to show 26-49

BUILD: 3587

![image](https://cloud.githubusercontent.com/assets/1098498/12266148/74aec826-b939-11e5-9c4b-0eb9bcbfc6a5.png)

**Comment by weisswurstkanone** [comment]
build 3596
