### ISSUE TITLE
Unable to install Pimcore using composer - out of memory

### ISSUE THREAD

**Issue by NielsHavermans** [pimcore/pimcore#3795]
Unable to install Pimcore using composer. Every time I get an out of memory error while installing/updating dependencies. This on a remote server and a local server (Mac OS Mojave).

Does anyone has a solution to install pimcore/skeleton?
  
### Expected behavior 
Installing using composer with the provided commands on Github and pimcore.com

### Actual behavior  
Out of memory error: 
Fatal error: Out of memory (allocated 922755072) (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer.phar/src/Composer/DependencyResolver/Rule2Literals.php on line 53

And allocate memory error:
mmap() failed: [12] Cannot allocate memory.

**Comment by brusch** [comment]
https://talk.pimcore.org - thanks!
