### ISSUE TITLE
[Quick Search] Optimizing display of preview images

### ISSUE THREAD

**Issue by vpapula** [pimcore/pimcore#3798]
# Bug Report
 
  
### Expected behavior 
  For finding a correct asset easily there should be a preview/thumbnail of PDF file formats as well in the search results. 
### Actual behavior  
  With "quick search" the preview flashes once and disappears immediatelly and with "Search assets" the previews are not showing at all
### Steps to reproduce  
  https://demo-advanced.pimcore.org
--> make a new folder on the root level, upload any PDF file and make a search

# Feature Request

**Comment by vpapula** [comment]
Okay, my bad. The quick search does it yes, but it do not scale the preview to fit into the area. – I had a document with nothing in the upper left corner of the first page, so the preview was a bit too white :). Fitting would be good to see the whole page.. But anyhow the "Search assets" doesn't show any previews in the results.

**Comment by vpapula** [comment]
As an addition to this issue regarding to the asset search in general. In the search results, a feature which would allow a user to browse asset previews in large size quickly and maybe zoom as well would bring the search into the next level.

**Comment by brusch** [comment]
@vpapula isn't this was the quick search is already, or do you have a concrete example for that?

**Comment by vpapula** [comment]
@brusch It is quite already it. For image file format assets e.g. product images etc. it serves the purpose fantastically but when it comes to marketing material in PDF format with many elements in it, then a large preview is needed to find the right asset quickly. For example telecom operator ads are usually based on templates which means the background of the material is the same in multiple ads and only the phone offers in it changes per ad. This leads to a search result with a great amount of similar looking ads when reviewed from the distance. To just mention the operator ads, there are many similar examples to follow. - The feature in the quick search and search assets would possibly be somewhat similar to macOS "quick look" feature in Finder. Does this give the big picture?
