### ISSUE TITLE
The changes in the main class is not getting reflected in the custom layouts

### ISSUE THREAD

**Issue by Debanshu123** [pimcore/pimcore#3801]
There is a field SKU which is mandatory and I have created a custom layout too. Now I made SKU as non-mandatory the change is not getting reflected in the custom layouts, also Mandatory option is disables in custom layout and as a user I have to re-create the custom layouts.

**Comment by brusch** [comment]
That's intentional and in your responsibility to change as an admin/developer. 
If that would be automatically, it wouldn't be possible anymore to make a field mandatory in a custom layout while it's not mandatory in a different layout. 

So, we can't make it work for both use-cases.
