### ISSUE TITLE
Update pimcore 5.5.5 to 5.6

### ISSUE THREAD

**Issue by incoxx** [pimcore/pimcore#3804]
# Bug Report
 
  
### Expected behavior 

No errors
  
### Actual behavior  

I performed an update from pimcore 5.5.4 to 5.6. In the Composer Report the following Warning/Error appears

![image](https://user-images.githubusercontent.com/21988262/50691743-edc40800-1031-11e9-91ed-6ef28ae799d6.png)

  
### Steps to reproduce  

Not possible. 5.6 is up and running. Not sure, if this warning is really a problem
Cheers
Markus
  
### Code example 
```php
// your code
```

# Feature Request

**Comment by brusch** [comment]
I've experienced that as well, but it can be safely ignored. 
Nevertheless, I'm currently investigating how we can avoid this.

**Comment by brusch** [comment]
@dpfaffenbauer any idea?

**Comment by brusch** [comment]
Aaaah, got the problem!
The reason for this warning is that the service `Pimcore\Bundle\CoreBundle\Command
  \ThumbnailsOptimizeImagesCommand` already exists in 5.5.4, but with a different signature for the constructor. 

So after the update and right before the cache is getting cleared, the old service definition is used to initiate the service, but the class itself and therefore the signature of the constructor changed already.

**Comment by brusch** [comment]
Changing the class-name of the command would solve the problem, I'm just checking of this could have negative side effects.

**Comment by brusch** [comment]
The complete error message as plain text - just for the sake of completeness ;-) 

```
> Pimcore\Composer::postUpdate
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache


 [WARNING] Some commands could not be registered:


In ThumbnailsOptimizeImagesCommand.php line 33:

  Type error: Too few arguments to function Pimcore\Bundle\CoreBundle\Command
  \ThumbnailsOptimizeImagesCommand::__construct(), 0 passed in /home/install-
  test/www/var/cache/prod/ContainerYvotyre/getThumbnailsOptimizeImagesCommand
  Service.php on line 8 and exactly 1 expected

```
