### ISSUE TITLE
 Plugins are not displayed in backend (Pimcore 4)

### ISSUE THREAD

**Issue by tobiasfeldmethwalter** [pimcore/pimcore#3807]
Hello Pimcore team,

For a project we currently use the **Pimcore Version 4**.

Here we have the problem that the Lucene Search and the Form Builder are no longer displayed in the backend.
Maybe someone has an idea what this may be? - Problem with Pimcore, Lucene Search, Formbuilder?
Since when we have the problem with the project is not very clear. It was only reported to us.

Thanks for feedback and hints

**Comment by dpfaffenbauer** [comment]
1. There is no support for Pimcore 4 anymore -> You can purchase Enterprise Support directly from Pimcore though.
2. Use the Forum for such thinks: talk.pimcore.org
3. I guess you just installed the version for >= 5 instead of <= 4.
