### ISSUE TITLE
inject assets (js/css) in footer area

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#382]
Is there any chance to inject assets in footer area?

injecting data in header with ```headScript()``` and ```headLink()``` is already possible:

```php
//css
$this->view->headLink()->appendStylesheet('/website/static/css/style.css');
//js
$this->view->headScript()->appendFile('/website/static/js/script.js', 'text/javascript');
```

at the moment, the only solution i found is to manipulate the reponse with ```dispatchLoopShutdown()``` which i think is not the right way.

do i miss something?

**Comment by brusch** [comment]
please use StackOverflow or our Google Group for this kind of questions :) 
Thanks!
