### ISSUE TITLE
Website settings vanished after any kind of interruption during writing/changing.

### ISSUE THREAD

**Issue by SEYentl** [pimcore/pimcore#3824]
# Bug Report
It seems that an interruption during writing/changing of website settings can result in a loss of the settings. The hypotheses is that website settings are kept in-memory while changing them, if on that moment a problem occurs with the server, the settings are lost.

### Expected behavior 
Website settings are not lost after any sort of interruption (server down, memory swap,...)
  
### Actual behavior  
Website settings remain as-is after any kind of interruption occurs.  

### Steps to reproduce 
1) A process that is ran recurrently changes a flag (i.e. a boolean) during a maintenance job.
2) During the change of this flag, the server runs out of memory.
3) After a reboot of the server the website settings are vanished.

It seems weird that the website settings are kept on file-system without fallback in database. Is it possible to elaborate why these settings are managed like that? It can be that I'm wrong about this.

**Comment by brusch** [comment]
Won't fix.
