### ISSUE TITLE
Assets thumbnail download not working

### ISSUE THREAD

**Issue by justbane** [pimcore/pimcore#3829]
# Bug Report
![screen shot 2019-01-11 at 1 02 36 pm](https://user-images.githubusercontent.com/4744199/51059726-0e481100-15a2-11e9-840b-f65c883bf033.png)
 
  
### Expected behavior 
I believe a list of available thumbnail types should be shown
  
### Actual behavior  
  Nothing is shown in the dropdown

### Steps to reproduce  
Select any image from the Assets section and try to select a thumbnail from the list to download.

**Comment by brusch** [comment]
Only thumbnails with the following option get listed: 
![image](https://user-images.githubusercontent.com/142037/51109757-7bec7b00-17f6-11e9-8a65-0145f28ed756.png)
