### ISSUE TITLE
WYSIWYG: Remove clipboard plugin

### ISSUE THREAD

**Issue by zerlpaMMT** [pimcore/pimcore#3831]
The use of copy and paste function in the wysiwyg toolbar ends in alert / failure / security message: "Your browser security settings don't permit the editor to automatically execute copying operations. Please use the keyboard for that (Ctrl/Cmd+C)."

**Comment by brusch** [comment]
Caused by https://github.com/ckeditor/ckeditor-dev/issues/469#issuecomment-306279192

**Comment by deltatag** [comment]
The context menu entry for "Paste CTRL+V" should also be removed. This action will also lead to the same error as clicking on the paste button.

**Comment by brusch** [comment]
@deltatag done by #4908 😊
