### ISSUE TITLE
Deadlock found... on upload multiple assets

### ISSUE THREAD

**Issue by gadget60** [pimcore/pimcore#3836]
With Pimcoure 5.6 I run into an exception while trying to upload multiple assets via drag'n'drop.
`
{"success":false,"message":"An exception occurred while executing \u0027SELECT GREATEST(a.versionCount, IFNULL(v.versionCount, 0)) FROM assets as a LEFT JOIN versions as v\n ON ctype=\u0022asset\u0022 AND v.cid=a.id WHERE a.id = ? ORDER BY v.id DESC LIMIT 1 FOR UPDATE\u0027 with params [1074]:\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction"}
`

The problem appears both on DEV and PROD system, the amount of assets that can be successfully uploaded however is different (DEV: 3, PROD: around 15). However this was never a problem on the very same environments up to Pimcore 5.5.4.

Can you reproduce this?

**Comment by brusch** [comment]
Yep, reproducible.
