### ISSUE TITLE
change the workflow place of dataobject with versions

### ISSUE THREAD

**Issue by iventura** [pimcore/pimcore#3838]
Hallo,

i think, i found a new issue in the pimcore 5.6.0. If i changing in admin the workflow place of some dataobject with newer versions, a new version will created and declared as "Publish". In the API, i will get the data not from the last published object, but modified from the latest version with the status unpublished. Also in the list of versions in admin, the last version will be marked as "Publish". 

But from the logic, i don't need any new version in this case. Only place should be changed. It's OK, if the new version will be created, but then, the version should not be "Publish". Don't tangle with the published flag.

Am i wrong, or forgot to do something in additional?

With best regards,
Ivan

**Comment by brusch** [comment]
Everytime when the save() method of an element is called a version get's created. 
In the admin interface always the latest version (regardless of it's published state) is displayed, which makes sense ... just think of an editor working on a page over some days, he want's to continue the work were he stopped, not on the latest published version. 

This behavior we have since version 1, so nothing changed here in 5.6.

**Comment by iventura** [comment]
Hi Bernhard, and thank you for the explanation. But how can i change the workflow place of an dataobject without getting changes live?

**Comment by brusch** [comment]
What do you mean by workflow place? Do you mean the state in the workflow?

**Comment by iventura** [comment]
yes, a mean the current state, i am just use the new nomenclature since 5.5 :)

**Comment by iventura** [comment]
as possible workaround, follow solution works fine for me:
in the  pimcore/lib/Workflow/Manager.php i've extended the function applyWithAdditionalData from line 237 with:
    
public function applyWithAdditionalData(Workflow $workflow, $subject, string $transition, array $additionalData, $saveSubject = false)
    {
        $this->notesSubscriber->setAdditionalData($additionalData);

        $marking = $workflow->apply($subject, $transition);

        $this->notesSubscriber->setAdditionalData([]);

        if ($saveSubject && $subject instanceof AbstractElement && method_exists($subject, 'save')) {
            **if($subject->getPublished())
                $subject->save();
            else
                $subject->saveVersion();**
        }

        return $marking;

**Comment by ivanmerta** [comment]
Did you mean @iventura? :)

**Comment by iventura** [comment]
Hi Bernhard, so that is the current status? I think the issue is very important for all customers. The current solution works fine only if you are working with a new product. But if you have to change products data using workflows with "live product", your changes will be live immediately after place(state) of the object were changed.

**Comment by brusch** [comment]
@ivanmerta oh, yes, sorry ;) 
@iventura please create a PR with the changes you suggested. Thanks!

**Comment by fashxp** [comment]
this needs a bit more attention, see my comment on the pull request: 
https://github.com/pimcore/pimcore/pull/3844#pullrequestreview-194959836

**Comment by brusch** [comment]
fixed in https://github.com/pimcore/pimcore/commit/af71227b37d22a0b8b24b675ef54d547c55c78f2
