### ISSUE TITLE
[Data Object] Layout Permissions: Error if class name is using underscores

### ISSUE THREAD

**Issue by FredoVelcro** [pimcore/pimcore#3839]
https://github.com/pimcore/pimcore/blob/0bc632afa1fa778bc80c416b9dceb6e4cf0d3ec2/models/DataObject/Service.php#L587

My object class is for example "BM_product" (underscore in it)  and so the custom layouts are not well parsed...

Proposed changes : 
https://github.com/FredoVelcro/pimcore/pull/1

**Comment by FredoVelcro** [comment]
Great thanks ! we need this fix ASAP cause our customer need this functionnality.
When will you release the 5.6.3 version ?
Regards.

**Comment by brusch** [comment]
@FredoVelcro 5.6.3 is planned for this Friday.
