### ISSUE TITLE
Install: character set check logic is reversed

### ISSUE THREAD

**Issue by joshuamarshall** [pimcore/pimcore#384]
The database character set checking logic in the installer appears to be reversed.

On line 80 of the installer file /pimcore/modules/install/controllers/IndexController.php
```php
$result = $db->fetchRow('SHOW VARIABLES LIKE "character\_set\_database"');
if (in_array($result['Value'], ["utf8", "utf8mb4"])) {
    $errors[] = "Database charset is not utf-8";
}
```
The check if the character set is in the array will cause it to fail if the db character set is utf-8.
This is the reverse of the what it should be checking for.

**Comment by brusch** [comment]
Absolutely, ... thank you very much!
