### ISSUE TITLE
Option to skip database structure on install is not working

### ISSUE THREAD

**Issue by mugge6** [pimcore/pimcore#3852]
# Bug Report
 
  
### Expected behavior 

Trying to install a new Pimcore version on an existing installation without loosing already existing DB data. The installer option `skip-database-structure` can be used, to prevent the initial deletion of the DB data. See issue #3035
  
### Actual behavior  

To reinstall Pimcore and update it to a new version, the following commands will be used:

```
composer install
./vendor/bin/pimcore-install --ignore-existing-config --skip-database-structure -n -e dev --mysql-username=xxx --mysql-password=xxx
```
Currently the `--skip-database-structure` has no impact, because in `vendor/pimcore/pimcore/bundles/InstallBundle/Command/InstallCommand.php` the method `installerNeedsOption()` will return false:

```
if ('install_options' === ($config['group'] ?? null) && InputOption::VALUE_OPTIONAL === ($config['mode'] ?? null)) {
```
In that case, this option will never added to the `$params`-Array. Because of that, the variable `$this->createDatabaseStructure` will be always `true` in `vendor/pimcore/pimcore/bundles/InstallBundle/Installer.php` in method `install()`:

```
//check skipping database creation or database data
if (array_key_exists('skip_database_structure', $params)) {
    $this->createDatabaseStructure = false;
}
``` 
The same for the other install options:
* skip-database-data
* skip-database-data-dump

 
### Steps to reproduce  

1. Add some data to an existing Pimcore installation (for example a new object)
2. Run  `./vendor/bin/pimcore-install --ignore-existing-config --skip-database-structure -n -e dev --mysql-username=xxx --mysql-password=xxx` on an existing Pimcore installation
3. Object is now deleted from the DB

**Comment by brusch** [comment]
@mugge6 Thanks for reporting! Would it be possible for you to create a PR for us? 😊 Thanks in advance!

**Comment by dpfaffenbauer** [comment]
If you do that, could you move the database creation into a separate command and call that new command from the install command? It would be useful just to create the database and nothing else.

**Comment by brusch** [comment]
@mugge6 Had to revert PR  #3858, it broke normal installations completely.

**Comment by nandorholozsnyak** [comment]
Hey.
I have just encountered the same problem, is there any fix for this scenario, to skip building the database in the install phase?
