### ISSUE TITLE
Folder grid config preapply event

### ISSUE THREAD

**Issue by psuhane** [pimcore/pimcore#3860]
It would be great if there will be event available on grid config preapply. In this event listener grid config validation or modification can be done.

**Comment by brusch** [comment]
What would be an actual use-case for that? Thanks :)

**Comment by psuhane** [comment]
Currently user can configure any operator with inappropriate parameter e.g. in case of fieldcollection operator user can enter any text in free fields. In such cases a proper validation message can be prompted to the user if configured operators have wrong params. 

If there will be preapply event will there in grid config then grid config validations can be done.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
