### ISSUE TITLE
CSV Export with classification store data throws error

### ISSUE THREAD

**Issue by rfischinger** [pimcore/pimcore#3862]
When any attribute of a classification store is added to the grid view, CSV Export fails with following message:

```
Status: 500 | Internal Server Error
URL: /admin/object-helper/do-export
Method: POST
Message: Call to undefined method get1-Wert in class AppBundle\Model\DataObject\Product
```

**Comment by weisswurstkanone** [comment]
unable to reproduce,
maybe related to https://github.com/pimcore/pimcore/issues/3634 which has been fixed already ?

**Comment by dvesh3** [comment]
@rfischinger unable to reproduce! can you please share specific use-case? with Pimcore version. Thanks!

**Comment by brusch** [comment]
Closed due inactivity. 
Feel free to come back on this issue with a reproducible case. :)
