### ISSUE TITLE
Version data is based on object's current data (reference problem)

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#3865]
# Bug Report
  
### Expected behavior 
Loading the latest version of an object should load an object with the same data as displayed in the version tab in the backend UI.  

### Actual behavior  
Latest version object is somehow referenced to current data of original object, making comparison of an object to its latest version prone to errors.
  
### Code example 
```php
<?php
$object = \Pimcore\Model\DataObject\Concrete::getById(123);
var_dump($object->getKey());
$object->setKey('test');
var_dump($object->getKey());
var_dump($object->getLatestVersion(true)->getData()->getKey());
```
Output is:
```
string(48) "Real title of the object"
string(4) "test"
string(4) "test"
```

In contrast loading the latest version before calling the object setter:
```php
<?php
$object = \Pimcore\Model\DataObject\Concrete::getById(123);
var_dump($object->getKey());
$latestVersion = $object->getLatestVersion(true)->getData();
$object->setKey('test');
var_dump($object->getKey());
var_dump($latestVersion->getKey());
```
Output is:
```
string(48) "Real title of the object"
string(4) "test"
string(48) "Real title of the object"
```

**Comment by brusch** [comment]
This behavior is intentional for the key and the path. 
More details on this here: https://github.com/pimcore/pimcore/blob/0d8ebccabd21b4f817dc010802dbc0e273cc2bb5/models/DataObject/AbstractObject.php#L1233 

If you do the same with other properties than the 2, you won't experience this behavior.
