### ISSUE TITLE
Composer install failing

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#3869]
# Bug Report
Using this command
`./vendor/bin/pimcore-install --mysql-host-socket=/opt/percona-server/5.7.22-22/var/mysql.sock`
produces
` [ERROR] The following errors were encountered during installation`

>  * An exception occured while establishing a connection to figure out your platform version.
> You can circumvent this by setting a 'server_version' configuration value
> 
> For further information have a look at:
> https://github.com/doctrine/DoctrineBundle/issues/673

I was unable to find a way to provide `server_version`

**Comment by brusch** [comment]
https://talk.pimcore.org/ - Thanks!

**Comment by kanevbg** [comment]
sorry...!
for reference, here it is https://talk.pimcore.org/t/how-to-prevent-server-version-error-from-doctrine-during-instalation/1753
