### ISSUE TITLE
Backend RTL (right to left) support

### ISSUE THREAD

**Issue by podarcis** [pimcore/pimcore#3875]
# Feature Request 

Is there currently support for RTL (right to left) languages in Pimcore, especially within the backend? We might have a use case for the Arabic language.

If not, is there any plan to support RTL in the near future and/ or are you interested in accepting a pull request?

Under the assumption there's no support at all: What would be the best way to implement it? 

## Considerations

- Decision for putting backend into RTL mode based on browser locale or by user setting?
- RTL for the whole backend or just for input components?

### Whole backend

Put ```<html dir="rtl">``` into admin template. This puts almost all components (ExtJS/CKEditor) into RTL mode. For a LTR-user this feels weird and might not be the way it's supposed to be.

### Specific input components

Inject this stylesheet into backend:
```css
textarea, input[type=text] {
    direction: rtl !important;
}
```
Override CKEditor default config:
```javascript
pimcore.object.tags.wysiwyg.defaultEditorConfig.contentsLangDirection = 'rtl';
```

At first glance this looks promising for editing data.

**Comment by brusch** [comment]
@podarcis currently there's no out of the box support of rtl in the backend and it is also not planned to provide this functionality. However we'd accept a PR under the following conditions: 
- it has to be complete, everything throughout the admin interface needs to support rtl, not just some parts that you'd actually need for your project
- it shouldn't make the code less readable or far more complex

**Comment by podarcis** [comment]
@brusch Thanks for your reply. That's enough information we need right now. I'll do a follow up when it becomes concrete.

**Comment by brusch** [comment]
Thanks 👍 I'll close this issue in the meantime.
