### ISSUE TITLE
All object relations in Fieldcollections are lost when copied

### ISSUE THREAD

**Issue by tschuessler** [pimcore/pimcore#3881]
# Bug Report
 
  
### Expected behavior 
Relations in field collections should not be lost when copying a DataObject

### Actual behavior  
Relations within field collections in a DataObject are lost when copied. This behaviour only occurs if there are localized fields defined in the field collection. Also relations are not lost when the relations themselves are localized. **All relation types ( Many-To-One Relation, Many-To-Many Object Relation, Advanced Many-To-Many Relation, Advanced Many-To-Many Object Relation, Many-To-Many Relation) are affected.**
  
### Steps to reproduce
1) Create a fieldcollection-definition with the following elements:
- Many-To-One Relation
- Many-To-Many Object Relation
- Advanced Many-To-Many Relation
- Advanced Many-To-Many Object Relation
- Many-To-Many Relation
- localizedfields
  - text

2) Create a DataObject-definition with only a fieldcollection-container. Allow fieldcollections of 1) to be used in this collection

3) Create a new DataObject of type 2) and add object-relations to all relation-fields. Save the object

4) Copy the DataObject: all of the relations are lost

5) Remove the localized-field block (including the text-field) from the field-collection-definition 1)

6) Copy the DataObject: all relations are still there

The problem seems to revolve around localized-fields and their tables. If a relation is part/within a localized-field, the relation will **not** be lost though.

**Comment by brusch** [comment]
The fix for #3874 should cover all other relational data-types mentioned here as well. 
So that should be fixed already.
