### ISSUE TITLE
[XLIFF] Deal with object folders

### ISSUE THREAD

**Issue by msphn** [pimcore/pimcore#3882]
The XLIFF Exporter can't export an object which contains folders of objects. If a user ticks the "children" checkbox while exporting I'd expect PimCore to deal with folders of objects and not just with objects underneath the actual object I'm exporting.

I actually think about implementing it myself but would like to get your feedback first. Don't want to put any effort in it if there are good reasons to not go this way.

**Comment by brusch** [comment]
I'd classify that as a bug.
PR's are welcome :)

**Comment by msphn** [comment]
Hah! Ok. I'll have a look at it :-).

**Comment by msphn** [comment]
Alright, I had a look at it.
I'd be glad if someone with frontend experience would have a look at it.

## Quick analysis
### ExportService::exportTranslationItems
Get's a TranslationItemCollection where at some point one element is a folder. It's not distinguished later on between object AND object folder.

There are two ExportDataExtractorServiceInterface one for documents one for objects. They are working fine. They are only there to extract data from either documents OR objects.

### DataObjectDataExtractor::extractRawAttributeSet
As expected, this can and should only deal with actual objects. There is a check ensuring this.

I suggest going through folders in the frontend, grabbing all object ids from the folders and making more jobs in the content-export-jobs request.

I hope I still could help here!

**Comment by weisswurstkanone** [comment]
Unable to reproduce. Could you please try again on the current pimcore 6 demo instance and provide a specific example? thx!

**Comment by msphn** [comment]
It works with pimcore 6 :). @weisswurstkanone

**Comment by weisswurstkanone** [comment]
thx for verifying!
