### ISSUE TITLE
[Assets] Show File Size & URL

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#3885]
When clicking the (i) Icon

(1) It would be great to be able to retrieve the file size of an asset
(2) For quick sharing of an asset, it would be great to include the URL of the Main Domain in "Path:"

![image](https://user-images.githubusercontent.com/13643455/51894585-7c654400-23a8-11e9-86c5-8334eec8b594.png)

**Comment by brusch** [comment]
![image](https://user-images.githubusercontent.com/142037/51896206-38743e00-23ac-11e9-9a66-dd1126d6436f.png)
