### ISSUE TITLE
Copy & Paste messes with the configured language

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#3887]
# Steps to reproduce

1. Create doc and assign language
2. Copy that
3. paste without inheritance and as child (recursive or not)
4. language now broken

![bildschirmfoto 2019-01-29 um 10 54 07](https://user-images.githubusercontent.com/5981845/51900010-80975e80-23b4-11e9-9fca-4aae2b097f0b.png)

Version: 5.5 and 5.6

**Comment by brusch** [comment]
fixed by #3877
