### ISSUE TITLE
Unify Classification Store Translation

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#3888]
There are several translation mismatches if I'm in a classification store context:

## Keys
If I'm defining a nice translation title for a simple key:

![bildschirmfoto 2019-01-29 um 11 06 17](https://user-images.githubusercontent.com/700119/51900710-4333d080-23b6-11e9-91fe-e45b92098797.png)

=> The name itself still shows up in admin translation:

![bildschirmfoto 2019-01-29 um 11 10 52](https://user-images.githubusercontent.com/700119/51900837-90b03d80-23b6-11e9-9aab-d4547d6af892.png)

***

If I'm adding a description:

![bildschirmfoto 2019-01-29 um 11 22 02](https://user-images.githubusercontent.com/700119/51901513-27312e80-23b8-11e9-83e5-435bf330d72f.png)

=> The single key does not show up in the translator. Instead, the name (not title) + description will be added concatenated in backend translation:

![bildschirmfoto 2019-01-29 um 11 21 55](https://user-images.githubusercontent.com/700119/51901547-36b07780-23b8-11e9-9bc6-b0e6864d8639.png)

## Groups
If I'm opening the CL search field, the name does not show up translated:
![bildschirmfoto 2019-01-29 um 11 05 33](https://user-images.githubusercontent.com/700119/51900521-d1f41d80-23b5-11e9-8539-2baaf42675fe.png)

***

If I'm adding a description:

![bildschirmfoto 2019-01-29 um 11 20 13](https://user-images.githubusercontent.com/700119/51901410-e6d1b080-23b7-11e9-85fb-ac19c79fd9e4.png)

=> The single key does not show up in the translator. Instead, the name + description will be added concatenated in backend translation:

![bildschirmfoto 2019-01-29 um 11 19 50](https://user-images.githubusercontent.com/700119/51901377-d28db380-23b7-11e9-851a-688fc42d186a.png)

## Collections
The collection name and description skips the translation fetch at all (Probably because it's not shown up as a real field in the object layout). Logically, if I'm opening the CL search field, the name does not show up translated:
![bildschirmfoto 2019-01-29 um 11 25 48](https://user-images.githubusercontent.com/700119/51901725-a58dd080-23b8-11e9-8ecd-2dc544d42702.png)

**Comment by skochTC** [comment]
A couple of months ago I integrated the classification system ETIM in Pimcore and there was the same problem.

I have solved this bundle side but I now provide this in the core.

The editing window, with the translation key:
![grafik](https://user-images.githubusercontent.com/54348050/80140207-ec607b00-85a7-11ea-91fb-3d6cf862f7c6.png)

The grid options:
![grafik](https://user-images.githubusercontent.com/54348050/80140411-30538000-85a8-11ea-9da7-16faa84ab7d6.png)

The grid view:
![grafik](https://user-images.githubusercontent.com/54348050/80142708-e9678980-85ab-11ea-9338-36061571b539.png)

For ETIM I mentioned the group in the GRID-View, but this is not a general use case for pimcore users, so it looks like this in my PR (last two columns):
![grafik](https://user-images.githubusercontent.com/54348050/80142526-91308780-85ab-11ea-81d7-d3870f1251d8.png)

Keys:
![grafik](https://user-images.githubusercontent.com/54348050/80142865-2af83480-85ac-11ea-804f-4e24157d7418.png)

Groups:
![grafik](https://user-images.githubusercontent.com/54348050/80142893-3a777d80-85ac-11ea-98f9-bdf79b6e6320.png)

Collections:
![grafik](https://user-images.githubusercontent.com/54348050/80142901-419e8b80-85ac-11ea-8f42-deffe061ad33.png)

In the object editing mask (name and description are now translated separately):
![grafik](https://user-images.githubusercontent.com/54348050/80143000-67c42b80-85ac-11ea-9d72-28fc77718a99.png)

And finally, in the admin translations:
![grafik](https://user-images.githubusercontent.com/54348050/80143364-fc2e8e00-85ac-11ea-8329-9e8ab302dc28.png)

**Comment by parthvora-credencys** [comment]
Hi @skoch-twocream,

Can you please explain how to import ETIM CSV/XML/XLSX files into a Pimcore classification store? Is there any free bundle available for that?

**Comment by skoch-twocream** [comment]
Hi @parthvora-credencys - no there is not free bundle on the market. We developed a own bundle-solutions for our customers.

If you are interested, please contact us via the contact area on our website (mentioned in my profile).
