### ISSUE TITLE
Return hashed user passwords for REST API (web service)

### ISSUE THREAD

**Issue by binarykitchen** [pimcore/pimcore#3894]
Would be great if the "Get User" web service also returns passwords
https://pimcore.com/docs/5.x/Development_Documentation/Web_Services/index.html#page_Get-User

Before you think I'm crazy, read first. Everyone might think never to give out password. Agree. Although when hashed, shouldn't harm and secondly, the API consumer in our case is another local sever on the local network, not accessible to the public.

That second local server wants to do some further processing regarding user authentication we can't nor want to implement on the Pimcore side.

**Comment by binarykitchen** [comment]
I think the problem is this code line
https://github.com/pimcore/pimcore/blob/master/models/DataObject/ClassDefinition/Data/Password.php#L382

Can we make this somehow configurable?

**Comment by brusch** [comment]
I wouldn't do that in the core product. 
If you really want to expose password hashes, I'd suggest to implement a custom API endpoint.

**Comment by binarykitchen** [comment]
Thanks. What about overriding methods with subclassing?

**Comment by binarykitchen** [comment]
Thanks man. 

It is really possible to select a different data type for the password on the default user class without "disturbing" the whole security model?

**Comment by brusch** [comment]
Yes, it is just a normal data-type as every other.
