### ISSUE TITLE
[Improvement] Coherent and complete asset column filter/order.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3899]
Hello,

We have tried to list asset by date of creation and having the image preview in the listing.
For now this seems not possible.
The purpose of this issue is to make column for asset listing coherent between the search and listing panel view.

Actually we have, for panel asset listing:

![panel-asset-listing](https://user-images.githubusercontent.com/9025839/52059444-29d38580-256a-11e9-8578-5efbb4ef16cb.png)

And for asset search:

![search-asset](https://user-images.githubusercontent.com/9025839/52059454-3061fd00-256a-11e9-9917-93746500d5ab.png)

It would be nice if both could have all those fields:
ID
Path
Filename
Type
Creation date
Modification date
Size
Preview

It would allow ordering by creation date with the preview image, and other ordering possibility (notably for the seach where dates and other column are missing).

Thanks.

**Comment by fashxp** [comment]
closed in favor of https://github.com/pimcore/pimcore/pull/5093

**Comment by Yivan** [comment]
#5093 is perfect, thanks.
