### ISSUE TITLE
Role management not as expected

### ISSUE THREAD

**Issue by rolandstoll** [pimcore/pimcore#390]
The role management doesn't behave as expected...

The following is e.g. defined in the role management:
- role A: user has access to folder A and can create objects based on object class A
- role B: user has access to folder B and can create objects based on object class B

If I give one user both roles A + B, he can even create objects based on object class B in folder A and vice versa. I would have expected, that even with both roles asigned to the user he can only create objects based on object class A in folder A and objects based on object class B in folder B...

tested with Version 3.1.1 (Build 3543)

**Comment by brusch** [comment]
This is actually no bug. The class restriction is a global permission, which is completely independent from a workspace, thats why it is not defined on workspace level. So this is class pemission is equatable with all the permissions on the same page which are also additive and independend from the workspace.
