### ISSUE TITLE
possibility to extend resources

### ISSUE THREAD

**Issue by mzulis** [pimcore/pimcore#392]
Long time ago it was possible to extend Pimcore resources by creating Mysql.php file e.g. 
<pre>
namespace Pimcore\Model\Document\Listing\Resource;

class Mysql extends \Pimcore\Model\Document\Listing\Resource {
</pre>

This code part made it possible
https://github.com/pimcore/pimcore/blob/e8eb681416767ca545e41aa5befd5bc7b2ed93f6/pimcore/lib/Pimcore/Model/AbstractModel.php
<pre>
// this is just for compatibility anymore, this was before the standard way
                        // but as there will not be a specialized implementation anymore eg. Oracle, PostgreSQL, ...
                        // we can move that below the general resource adapter as a fallback
                        $tmpClassName = implode($delimiter, $classParts) . $delimiter . "Resource" . $delimiter . ucfirst(Resource::getType());
                        if($className = $this->determineResourceClass($tmpClassName)) {
                            break;
                        }
</pre>

Above code part didn't work also long time ago, as order of resource file finding was changed:
search for Resource.php then only search for Mysql.php.

Of course I can create empty Website Model object and extend Pimcore model object. But that creates extra empty class, and in code it wouldn't be so obvious that I'm working with Pimcore model, and it won't be possible to add extra functionality to existing functions.

**Comment by brusch** [comment]
see: https://www.pimcore.org/wiki/display/PIMCORE4/Upgrade+Notes

If you have any questions please use StackOverflow or our Google Group. Thanks

**Comment by mzulis** [comment]
I understand that changes was made. That's a reason why I'm pointing out that it was very good functionality. But now it can't be used. We can't extend resource functionality. .e.g. add function getByMisticalParameter or overwrite any existing function.
