### ISSUE TITLE
[Object][Tag] One-to-many and Many-To-Many Reverse with getter

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#3920]
Imagine the following model:

Objects:
  - Customer
  - Addresses

**Customer** 
Fields:
 - Addresses (One-to-many)

**Address** 
Fields:
 - Customer (Many-to-one)
 - Street
 - Name
 - etc.

The Reverse side of Address (Customer), would be the One-to-Many. In theory Pimcore should be able to allow that type, it knows the relation and allowed-types and could create a getter called `getAddresses` and get me all Addresses defined from the reverse side.

As well as with the many-to-many which partly already is implemented, but only for `Many-To-Many Objects`. But: It requires to have a unique name, but doesn't generate a getter.

**Comment by rubanooo** [comment]
@pimcoreteam

Are there any plans to implement this? It would be quite useful to show the one-to-many reverse grid on the object when using many-to-one relations

**Comment by paulverdu** [comment]
This is a mandatory feature if you ask me. Why isn't this implemented yet?

**Comment by brusch** [comment]
Resolved by #10242
