### ISSUE TITLE
Feature Request: credit authors for free icons

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#3923]
# Feature Request 

I like the feature of customizing icons of Pimcore DataObjects inside the admin panel via the `getElementAdminStyle()` method or the class definition, but as I am not a great designer I am mostly using free icons. For these icons the license often states that you must credit the author. So it would be great if Pimcore had a simple ways for that. I am thinking of something like adding a new method to the `Pimcore\Extension\Bundle\AbstractPimcoreBundle` class `getIconAuthorCredits():string` or something similar, the returned text could then be printed at the very bottom of in the `Icon Library` tab. 

For details concerning crediting authors see i.e. https://support.flaticon.com/hc/en-us/articles/207248209-How-I-must-insert-the-attribution-

**Comment by brusch** [comment]
Hmmm, could be quite challenging and doesn't look very nice I guess ... wouldn't it be better to just use attribution free icon sets, such as Pimcore already offers in the backend? _Settings_ -> _Icon Library_

**Comment by dpfaffenbauer** [comment]
I don't feel thats a thing pimcore has to solve.

**Comment by jremmurd** [comment]
Yes, attribution free is another thing, but good and customized icons sets mostly require attribution. If it is a thing Pimcore has to solve or not is a matter of opinion I'd say. Maybe you are right and a entry in the best practice section of the docs is enough.

**Comment by dpfaffenbauer** [comment]
I don't even feel like it should be in docs. Why should Pimcore care about licensing/author credits for things you need in your project? Pimcore is a framework that lets you do certain stuff, if you use it and have to add credits, you have to sort it, not Pimcore.

I would just go ahead, create a plugin that adds a new menu entry somewhere to display the credit. You don't have to display the credit directly where you use it, it can also be in the imprint or something.

**Comment by jremmurd** [comment]
I thought of it as a addition or completion of the custom icon feature. If I can use custom icons, it should be possible to credit the author of the icons. Since Pimcore is not only used as a Web CMS, but also for PIM, DAM, etc there is not always an imprint page available. 

As you mentioned my current approach is to just add a new menu entry which opens a tab in which the credits are listed.

**Comment by dpfaffenbauer** [comment]
IMHO: Still: in terms of PIM or DAM. Having the possibility for credits is not pimcore's responsability

**Comment by brusch** [comment]
I'd say that would be a perfect topic for a bundle.
Would be quite a simple bundle that adds another menu **_Credits_** that displays just a simple rich text area that can be edited somewhere else or as as html file in the `/app` folder.

**Comment by jremmurd** [comment]
You guys may have a look at https://github.com/jremmurd/pimcore-copyright-attribution-bundle. No rich text, but does the job.

**Comment by brusch** [comment]
@jremmurd  very nice - thanks for sharing!
