### ISSUE TITLE
[Ecommerce][Indexservice] limit amount of maximum parallel index update processes

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#3928]
If the indexupdate (preparation + index queue) runs for example once every 5 minutes and for some reason there is a massive amount of products which need to be updated (for example 100.000) the cronjob will produce a lot of parallel jobs which could result in a major performance issue. Therefore some kind of mechanism to limit the maximum amount of parallel jobs is needed.

**Comment by dpfaffenbauer** [comment]
Pimcore Lock?

**Comment by markus-moser** [comment]
Maybe - at the moment the command does not provide any lock. There should be something like a maximum parallel jobs (e.g. 3) setting for this command and maybe Pimcore then can provide different numbered lock keys until the maximum number is reached.

**Comment by markus-moser** [comment]
Ah there is a max rounds command option - this should do the job.
