### ISSUE TITLE
override PIMCORE_DOCUMENT_ROOT in cli mode

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#393]
it's not possible to define PIMCORE_DOCUMENT_ROOT constant, if user is in cli mode:

```$ php php src/pimcore/cli/console.php```

**case:** when installing pimcore via composer, we symlink the */vendor/pimcore/pimcore/pimcore* to */pimcore*. in the index.php we define the PIMCORE_DOCUMENT_ROOT:

```define('PIMCORE_DOCUMENT_ROOT', realpath( dirname(__FILE__) ) ); ````

this is also needed in CLI Mode => but there is no chance to override them without hacking corefiles. 

Maybe pimcore should allow an config.php in root, which overrides the system constants?

**Comment by solverat** [comment]
after some deeper research i think it's not possible to access the document root in cli mode, when the real document is unknown. so copying the core folder from vendor to root is the only way.

**Comment by brusch** [comment]
Have you seens this already: https://www.pimcore.org/wiki/pages/viewpage.action?pageId=16854180 

php composer.phar create-project pimcore/pimcore ./your-project-name

should do the trick ;-)

**Comment by brusch** [comment]
If you want to add some custom dependencies: 

        php composer.phar create-project pimcore/pimcore ./your-project-name
        cd ./your-project-name 
        // edit composer.json -> add your own deps. 
        php composer.phar update

done :-)
