### ISSUE TITLE
Custom layout lost after workflow transition (and F5) reload

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#3934]
## Workflow
- Open object and apply custom layout "example"
- Dispatch workflow transition

**Current** **behavior**: Object gets reloaded with layout "master"
**Expected** **behavior**: Object should be available with custom layout "example" after reload
 
## UI
- Open object and apply custom layout
- Hit F5

**Current** **behavior**: Object gets reloaded with layout "master"
**Expected** **behavior**: Object should be available with custom layout "example" after reload

**Comment by fashxp** [comment]
is this fixed now?
