### ISSUE TITLE
Possibility to setup email cleanup in system settings

### ISSUE THREAD

**Issue by leuchtdiode** [pimcore/pimcore#3935]
We are sending a lot of emails via pimcore. My folder var/email had 4+ GB. I searched the documentation how to clean up emails.

Could not find anything until I listed all console commands. Later I llanded on the GDPR documentation page where it is documented. I think the command

> pimcore : email : cleanup

should be documented here https://pimcore.com/docs/5.x/Development_Documentation/Development_Tools_and_Details/Email_Framework/index.html as well as people tend to search there first (my guess).

FYI: My thread regarding the topic on talk.pimcore.org: https://talk.pimcore.org/t/clean-up-var-email/1812

Now to the "real concern" this issue is about:

I think it would be great to have the possibility to setup email cleanup in system settings like version cleanup for  documents and assets.

**Comment by brusch** [comment]
Thanks for your input! 
Docs: we'd be happy to merge a PR for that :) 
System setting: we decided to offer this functionality as an additional command for several reasons, so currently I don't see an advantage of providing an additional system setting.
