### ISSUE TITLE
XSS: Pimcore

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#3936]
ExtJs is open to XSS attacks. The Grid/Button/Panels, etc don't take care about sanitizing user inputs. Exmaple on basic demo:

<img width="683" alt="bildschirmfoto 2019-02-13 um 09 20 31" src="https://user-images.githubusercontent.com/5981845/52697034-cb96a180-2f70-11e9-9ba1-70a03ca90c33.png">
<img width="1732" alt="bildschirmfoto 2019-02-13 um 09 20 36" src="https://user-images.githubusercontent.com/5981845/52697037-cb96a180-2f70-11e9-87af-427608da6475.png">

**Comment by brusch** [comment]
We are aware of this, but decided to not handle that for the time being, since there are only trusted users in the admin interface anyway...

**Comment by dpfaffenbauer** [comment]
But people don't know that and should be told somehow. Very often values come from outside admin.

**Comment by NiklasBr** [comment]
We'll just wait for a user to register with a js payload as street name for their delivery address on orders... And boom. Compromise! 🤕

**Comment by brusch** [comment]
We're always happy to see PRs improving our product - @NiklasBr maybe you? 😊

**Comment by NiklasBr** [comment]
@brusch While I sure would like to give it a try, I do not have dedicated time to work on issues like this.

**Comment by brusch** [comment]
Fixed at least partly by 0bf1b9643d33a5dcd45c3f89135a1965fd55cce9 
But it is still required that every developer cares about sanitizing application specific user input!

**Comment by NiklasBr** [comment]
Thank you

**Comment by crimcol** [comment]
> Fixed at least partly by [0bf1b96](https://github.com/pimcore/pimcore/commit/0bf1b9643d33a5dcd45c3f89135a1965fd55cce9) But it is still required that every developer cares about sanitizing application specific user input!

I don't think every developer should think about sanitizing.
The problem apear on any input field or data display control.
There is no any issues with an Angular application. It will simply display the script string but do not evaluate it.
