### ISSUE TITLE
JSON response for GetDocumentByID-Call changed with 5.6.3

### ISSUE THREAD

**Issue by leuchtdiode** [pimcore/pimcore#3937]
I updated my TEST instance to 5.6.3. My LIVE instance is still 5.6.2.

Starting with 5.6.3 the payload for a document is slightly different when calling /webservice/rest/document/id/[id].

Until 5.6.2 the property "properties" did not have the property name as associative array key in it (see https://imgur.com/CwBAXiQ). Starting wih 5.6.3 it's popping up (see https://imgur.com/gS5f30L).

Is this a bug or on purpose? Because it's not documented in the "Upgrade Notes within 5.x"

**Comment by brusch** [comment]
No, that wasn't on purpose, it is really different from 5.6.2 to 5.6.3?

**Comment by brusch** [comment]
Regression caused by 6021a890376a1ffe06cbeb740a6c5b27520a34cc

**Comment by leuchtdiode** [comment]
> No, that wasn't on purpose, it is really different from 5.6.2 to 5.6.3?

Yes look at the images I provided. I downgraded my TEST instance to 5.6.2 and I can confirm that the response is back to "no associative array key".

**Comment by brusch** [comment]
Obsolete with the release of v6.
