### ISSUE TITLE
XSS in Ecommerce backoffice ordering

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#3940]
# Bug Report
 

Related and somewhat similar to  #3936, but different because this time it is not ExtJS components, but raw JS and unlike  #3936 this is also *guaranteed* to include data from untrusted sources.

### Expected behavior 

Sanitised data only.  

### Actual behavior  
  
Arbitrary code may be executed in the backoffice admin interface by any visitor to the site. Very high probability of getting session and cookie data for the admin users.

### Steps to reproduce  

Just try `<script>alert("XSS");</script>` in any field in the order checkout on the frontend.

![skarmbild 55](https://user-images.githubusercontent.com/279826/52784919-e0e5fb80-3056-11e9-9935-995cf58ca8a0.png)

**Comment by NiklasBr** [comment]
@brusch While this fixed the vanilla JS injection in the Ecommerce interface it is unfortunately incomplete, the ExtJS injection still works in the grid view. Still with input from unauthenticated users. See:

![skarmbild 57](https://user-images.githubusercontent.com/279826/52790490-fc590280-3066-11e9-9237-99ee4c5bc039.png)

**Comment by brusch** [comment]
I know, the issue was about the backoffice. 
And as I said ... PRs are welcome 😉

**Comment by NiklasBr** [comment]
Point was, you ignored @dpfaffenbauer's bug report because you (incorrectly) claimed that the ExtJS values are only from trusted sources. This is your product, I use it, I try to help as much as I can, but ultimately this is your product and your responsibility to properly diagnose and take responsibility for.

If you consider arbitrary code execution from unauthenticated users to not be a problem worthy of your time or energy, so be it, but it is **very** disappointing.
