### ISSUE TITLE
[Asset] properties on assets-folders are no longer inherited by assets

### ISSUE THREAD

**Issue by thgross** [pimcore/pimcore#3946]
# Bug Report

since pimcore 5.6.4, the properties you put on assets-folders are no longer inherited by assets inside the folders.
It breaks many of our webs. This still works on documents and data objects.
 
### Expected behavior 
inheritable properties on asset-folders should be inherited to assets.

### Actual behavior  
inheritable properties on asset-folders are not inherited to assets.

### Steps to reproduce  
1. add any property to an asset folder, make sure it ist marked as 'Inheritable'.
2. open the properites-tab of any asset inside that folder. The iherited property is not there.

**Comment by brusch** [comment]
Thanks for reporting 5.6.5 is already released.
