### ISSUE TITLE
Changelog - Provide all Issues/PR with the release

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#3948]
Is it possible to provide all Issues/PR's regarding a release in the Description here: https://github.com/pimcore/pimcore/releases/tag/v5.6.5 like https://github.com/coreshop/CoreShop/releases/tag/2.0.3?

Currently it is quite hard to figure what a release contains

**Comment by fashxp** [comment]
using milestones? https://github.com/pimcore/pimcore/milestone/52?closed=1

**Comment by dpfaffenbauer** [comment]
👍 didn't think about it. Yes that works.
