### ISSUE TITLE
Changing metadata of AdvancedManyToManyObjectRelation does not mark field dirty

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#3951]
# Bug Report

### Expected behavior 
Changing a meta field's value of an AdvancedManyToManyObjectRelation should mark the field dirty.
  
### Actual behavior  
Field does not get marked dirty and so does not get saved.  

### Code example 
```php
<?php
use Pimcore\Model\DataObject\Concrete;

// if you uncomment the follwoing line, everything works as expected
// Concrete::setDisableDirtyDetection(true);

$object = Concrete::getById(52807);

$refObject = Concrete::getById(52053);
$metaObject = new Pimcore\Model\DataObject\Data\ObjectMetadata('Distri', ['scaled_prices'], $refObject);
$metaObject->setScaled_prices('abc');
$object->setDistri([$metaObject]);
var_dump($object->getDistri()[0]);
$object->save();

$metaObject = $object->getDistri()[0];
$metaObject->setScaled_prices('def');
var_dump($object->getDistri()[0]);
$object->save();

// meta field scaled_prices still contains "abc"
```

In https://github.com/pimcore/pimcore/blob/848ec673a728e8d1e1bd85eefea1134992dc9a6c/models/DataObject/Data/ObjectMetadata.php#L85 $this->markMeDirty() gets called. This call is handled by https://github.com/pimcore/pimcore/blob/848ec673a728e8d1e1bd85eefea1134992dc9a6c/models/DataObject/Traits/OwnerAwareFieldTrait.php#L52 but as the field `_owner` is null (at least in my case), the relation field is not set dirty.

**Comment by weisswurstkanone** [comment]
Unable to reproduce.
Are you sure that this isn't a duplicate of https://github.com/pimcore/pimcore/issues/3911

**Comment by BlackbitNeueMedien** [comment]
Could be a duplicate of #3911 but the example there seems to be a bit too short.
With above script the meta field contains "def" at your test? 
Can you follow my point which lead to the relation field not being marked dirty from code perspective?

**Comment by weisswurstkanone** [comment]
yes, it contains "def".
Place would be 
https://github.com/pimcore/pimcore/commit/6c153018297fbee914401c7060803d36cb75e284

**Comment by BlackbitNeueMedien** [comment]
Ok, really works with #3911's change. I have not tested with the latest version.

**Comment by Lexipowder** [comment]
Still the problem exists or most likly through code changes it came up again:

Happens when untouched AdvancedManyToManyObjectRelation field is filled during the preUpdate hook via api, in this case different existing dimensions-objects should be saved as relation without and user interaction.

```
//Switch of dirty field detection
Concrete::setDisableDirtyDetection(true);
//Get object before save -> getById with force!!
$preSaveObject = DataObject::getById($object->getid(), true);

$object->setKey($object->getShortMark());

if ($preSaveObject->getSpecification() === NULL) {

    $dimensionGroup = $object->getSpecification()->getItems()[0]->getDimensionGroup()->getId();

    $lengthconfigitems = new DataObject\ConfiguratorItem\Listing();
    $lengthconfigitems->setOrderKey("ShortMark");
    $lengthconfigitems->setOrder("desc");
    $lengthconfigitems->setCondition("ConfigurationGroup__id Like :id", ["id" => $dimensionGroup]);
    $lengthconfigitems->load();

    $lengthsarray = array();

    foreach ($lengthconfigitems as $lengthconfigitem) {

        //create the objectmetadata Object, "yourObject" is the referenced object
        $objectMetadata = new DataObject\Data\ObjectMetadata('PowerConsumption', ['powerconsumption'],  $lengthconfigitem);
        array_push($lengthsarray, $objectMetadata);
    }

    $object->getSpecification()->getItems()[0]->setPowerConsumption($lengthsarray);                            
}
```
Pimcore Version: v6.2.1

**Comment by BlackbitNeueMedien** [comment]
@Lexipowder, could you provide a simplified example starting with creating two classes where one contains a relational field to the other?
I wonder why you set `Concrete::setDisableDirtyDetection(true);` - is this already to bypass the bug you have noticed?

**Comment by Lexipowder** [comment]
Concrete::setDisableDirtyDetection(true); is the bypass.
Example will follow.

**Comment by Lexipowder** [comment]
```
Pimcore\Model\DataObject\Length Object
(
    [objectId] => 367
    [LengthInMm] => 934
    [ShortMark] => 934
)
```

First of all the object above will be created with the id 367, saved via GUI
Second, the object below will be created via GUI:

```
$dimensionsObject = new Pimcore\Model\DataObject\Dimensions Object
(
    [ShortMark] => Redster
    [Specification] => Pimcore\Model\DataObject\Fieldcollection Object
        (
            [items] => Array
                (
                    [0] => Pimcore\Model\DataObject\Fieldcollection\Data\DetailsClass Object
                        (
                            [type] => DetailsClass
                            [PowerConsumption] => Array
                                (
                                    
                                )
                        )
                )
        )
)
```

Within the preUdate hook of the $dimensionsObject->save() all length objects shall be set in the PowerConsumption relation field like this:

```
Pimcore\Model\DataObject\Dimensions Object
(
    [ShortMark] => Redster
    [Specification] => Pimcore\Model\DataObject\Fieldcollection Object
        (
            [items] => Array
                (
                    [0] => Pimcore\Model\DataObject\Fieldcollection\Data\DetailsClass Object
                        (
                            [type] => DetailsClass
                            [PowerConsumption] => Array
                                (
                                    [0] => Pimcore\Model\DataObject\Data\ObjectMetadata Object
                                        (
                                            [object] => 
                                            [objectId] => 367
                                            [fieldname] => PowerConsumption
                                            [columns] => Array
                                                (
                                                    [0] => powerconsumption
                                                )

                                            [data] => Array
                                                (
                                                    [powerconsumption] => 12
                                                )

                                            [_owner] => Pimcore\Model\DataObject\Fieldcollection\Data\DetailsClass Object
 *RECURSION*
                                            [_fieldname] => PowerConsumption
                                            [_language] => 
                                        )
                                )
                        )
                )
        )
)
```

preUpdate hook script:

```
$lengths = new DataObject\Length\Listing();
$lengths ->load();

 $lengthsarray = array();

foreach ($lengths as $length) {

        $objectMetadata = new DataObject\Data\ObjectMetadata('PowerConsumption', ['powerconsumption'],  $dimensionsObject);
$objectMetadata->setPowerConsumption(12);
        array_push($lengthsarray, $objectMetadata);
    }

    $dimensionsObject->getSpecification()->getItems()[0]->setPowerConsumption($lengthsarray); 
```

What's happening is that the relation field [PowerConsumption] isn't set dirty and so won't be saved.
Is this more clear?

`Concrete::setDisableDirtyDetection(true);` is then the bypass which makes it work like in your example.

**Comment by BlackbitNeueMedien** [comment]
@Lexipowder Could you try to set the object of the `ObjectMetadata` object to the field collection item:
```php
$objectMetadata = new DataObject\Data\ObjectMetadata('PowerConsumption', ['powerconsumption'],  $dimensionsObject->getSpecification()->getItems()[0]);
$objectMetadata->setPowerConsumption(12);
```

Because the setDirty gets called for the "owner" object of the `ObjectMetadata` object. In your example this is the `Dimensions` object - that means that the field collection is never set dirty und thus not saved.

**Comment by weisswurstkanone** [comment]
Question is if this can be reproduced without the preUpdate hook, i.e. under normal circumstances.

**Comment by Lexipowder** [comment]
![image](https://user-images.githubusercontent.com/20427487/67556312-378df400-f713-11e9-9d34-34c88cb63216.png)

**Comment by weisswurstkanone** [comment]
Tried to reproduce your example as realistic as possible. No success. In other words, everything is fine.
I fear you have to debug this.

**Comment by Lexipowder** [comment]
Thanks for all the help, got it solved. 

Problem was, the relation field was encapsulated in a fieldcolletion, own setter and getter!
https://pimcore.com/docs/6.x/Development_Documentation/Objects/Object_Classes/Data_Types/Fieldcollections.html#page_Working-with-PHP-API

Working code below:

```
$lengths = new DataObject\Length\Listing();
$lengths ->load();

$lengthsarray = array();

foreach ($lengths as $length) {
        $objectMetadata = new DataObject\Data\ObjectMetadata('PowerConsumption', ['powerconsumption'],  $dimensionsObject);
	$objectMetadata->setPowerConsumption(12);
        array_push($lengthsarray, $objectMetadata);
}

// First get all data from the field collection
$fieldcollectionData = $dimensionsObject->getSpecification()->getItems();

// Then store the relations (including metadata) to the specific item within the field collection array                        
$fieldcollectionData[0]->setPowerConsumption($lengthsarray);

// And here it gets "dirty", reset the items of the field collection itself.  
$dimensionsObject->getSpecification()->setItems($fieldcollectionData);
```

**Comment by BlackbitNeueMedien** [comment]
@Lexipowder Imho it should work without calling the fieldcollection container's `setItems` method. But this would only be possible if the `owner` of the `ObjectMetadata` object was the field collection and not the object. 
If the `owner` is the `Concrete` object, then the metadata "setter" (__call) of the `ObjectMetadata` calls `markMeDirty`:
https://github.com/pimcore/pimcore/blob/master/models/DataObject/Data/ObjectMetadata.php#L106-L114

From there the following code is executed:
https://github.com/pimcore/pimcore/blob/b82d45be35158ae1692134cd33d04f568566f068/models/DataObject/Traits/OwnerAwareFieldTrait.php#L52-L60

When the owner is the `Concrete` object this `Concrete` is marked dirty for the advanced many to many field in the field collection - of course this field does not exist in the `Concrete` and so this has no effect in the dirty map.

**Comment by Lexipowder** [comment]
@BlackbitNeueMedien Ran your code, no metadata objects were built. 

I agree that direct access to relations with metadata objects in field collections should be possible like it works for simple input fields.
Spend a couple of hours trying to debug the whole process, but didn’t find a amother way to get the field collection “dirty”.

Also when you look into the database structure, the field collection is linked to the object, as well the metadata object is linked to the object.
In my understanding it metadata object should be linked to the field collection, which design-wise would follow the pattern that the owner metadata object is the field collection.
It seems some fundamental changes in the data structure would be necessary to achieve that.
