### ISSUE TITLE
pimcore.registerNS is not a function

### ISSUE THREAD

**Issue by Chetan07j** [pimcore/pimcore#3958]
TypeError: pimcore.registerNS is not a function
 - http://example.com/pimcore/static6/js/pimcore/startup.js:748:1

TypeError: pimcore.globalmanager is undefined
- http://example.com/pimcore/static6/js/pimcore/startup.js:689:9

**Comment by brusch** [comment]
Doesn't seem to be reproducible on our public demos, so I'd assume it's specific to your setup.

**Comment by dpfaffenbauer** [comment]
try looking at permissions...

**Comment by Chetan07j** [comment]
its not permission issue.
after admin login page goes blank and in console I get above error.

**Comment by Chetan07j** [comment]
@brusch this issue is not yet resolved. Why did u closed this ticket?

**Comment by Chetan07j** [comment]
https://hostpresto.com/community/tutorials/how-to-install-pimcore-cms-on-ubuntu-16-04/

this is what I followed.

**Comment by brusch** [comment]
@Chetan07j Because it's not an issue ... for support please use https://talk.pimcore.org - Thanks!

**Comment by sharris-spark** [comment]
For anyone else who comes across this, I initially got a blank screen except for a PHP error message indicating the permissions were wrong on the /var/system directory (couldn't write the minified js files). After fixing this I still got what the original user saw in that the admin starts to load but then goes blank. Running  

    php webroot/pimcore/cli/console.php cache:clear

resolved the issue.

**Comment by ghost** [comment]
> TypeError: pimcore.registerNS is not a function
> 
> * http://example.com/pimcore/static6/js/pimcore/startup.js:748:1
> 
> TypeError: pimcore.globalmanager is undefined
> 
> * http://example.com/pimcore/static6/js/pimcore/startup.js:689:9

@Chetan07j I am also facing same error
