### ISSUE TITLE
[Object] Geo data type map widget resolves wrong coordinates

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3964]
Hello,

This bug concerne the geo datatype for object.

If you zoom out at maximum, so you see the earth map, and scroll several times the map, and place the marker, the longitude is outside normal coordinates.

Here is a screenshot, it is simplier ; )

![bug-geo](https://user-images.githubusercontent.com/9025839/53020649-a4037580-3457-11e9-89d9-e853a875c73b.png)

Another exemple without moving the map:

![bug-geo2](https://user-images.githubusercontent.com/9025839/53020815-0c525700-3458-11e9-8250-4918f186984e.png)

Problem is in both way (negative and positive).
I think it should be caped/moduled so longitude is in normal/classic coordinates.

Thanks.

**Comment by Yivan** [comment]
Any upadate about this one ? It can lead to wrong datas stored in the data system if backend operator isn't watchful.
I know it could be corrected on post-save events (and reloading the map maybe so good coordinates are displayed... a ugly solution ; )), but better if it is handled natively by Pimcore.

**Comment by fashxp** [comment]
you could provide a PR ;-)

**Comment by dvesh3** [comment]
I guess that's how leafletjs works...not a Pimcore issue!
![image](https://user-images.githubusercontent.com/5137917/56747231-dd20d480-677d-11e9-95bd-5a5f0ab55425.png)

**Comment by Yivan** [comment]
@fashxp @brusch @dvesh3 

Yes this is the way leaflet work, the purpose of this issue is to have proper geocordinate in database, i think as a PIM we should record true coordinates in the database.

A solution like post-process to renormalise them before storing in database ? (a cos and after inv_cos should return a normalized one).
So after any code using geo algorythme can work as intended with good coordinates.

I am not a specialist of geo cordinate calulation, but it seems longitude are limited by -180 / +180
(https://stackoverflow.com/a/47188298)
Code using geocordinate work maybe with value further than 180 (as it is cos/sin/rad calculation)... so maybe having in database +720 is like +180 for calculation is the same and has no impact.
Maybe a specialiste will read this issue ? : )

Thanks.
