### ISSUE TITLE
[Data Object] In backend the input fields mixed between various blockelements, after changing the order of element of block

### ISSUE THREAD

**Issue by p4004p4004** [pimcore/pimcore#3968]
# Bug Report

### Expected behavior
when i change the order of blockelements, then should in frontend/backend updated.

### Actual behavior
In backend the input fields mixed between various blockelements, after changing the order of element of block

### Steps to reproduce
1\. create a new class or update someone with following tree/fields:
    * tabpanel
      -- panel
      --- block
      --- panel
      ---- localizedfields
      ----- input (here ist the issue)
2\. create a new object with three various block: write something in input fields
3\. change the order of blockelements and change the value of input field 
4\. refresh the object

**Comment by p4004p4004** [comment]
Can somebody help with it? This structure is a customer need, so would it be as soon as possible to find a solution?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
