### ISSUE TITLE
Make it possible to link two or more objects with the same id in an advanced many-to-many object relation.

### ISSUE THREAD

**Issue by jacobsyentl** [pimcore/pimcore#3971]
## Feature description
Since the metadata in an advanced many-to-many object relation can be the differentiating attribute it would be nice if multiple instances of the same object can be linked in this field.

Example:
![screenshot 2019-02-20 at 17 14 26](https://user-images.githubusercontent.com/9139261/53106323-1301cc80-3533-11e9-995f-94cd02620055.png)

**Comment by weisswurstkanone** [comment]
see https://github.com/pimcore/pimcore/issues/2022
