### ISSUE TITLE
In back office, in editmode, subsite with $this->path resolve always to site 0

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3972]
Hello,

Actually, if a static route is created without an hardcoded site id given in the parameters, using `$this->path()` resolve to the good subsite in the front end.
But in editmode in the pimcore backend, it resolve always to the site 0 (main root site).

As consequence, we have to force the `site` as parameters to the call `$this->path`.
It would be great it resolve automatically to same subsite than the document where `$this->path` is called, even in backend. Actually we have to get it manually and inject it as parameters each time.

**EXEMPLE**

Working in frontend, but not working in backend:
`$this->path('Product Details', ['product_id' => $crosssell_product['id']]);`

Working everywhere:
`$this->path('Product Details', ['product_id' => $crosssell_product['id'], 'site' => $this->document->getSite()->getId()]);`

Thanks.

**Comment by dpfaffenbauer** [comment]
The reason for that is that in the backend, Pimcore doesn't care about the site at all. In fact: for pimcore it's not even a site.

**Comment by Yivan** [comment]
Thanks for your insight.
But it would be nice using `$this->path('Product Details', ['product_id' => $crosssell_product['id']]);` work the same in backend by adding `$this->document->getSite()->getId()` as default site.

**Comment by dpfaffenbauer** [comment]
anyway, why do you need working/right links in the pimcore backend editmode?

**Comment by Zamralik** [comment]
It throws an Exception because it can't find the route (route available to specific site ids)

**Comment by Yivan** [comment]
@dpfaffenbauer It is needed because of some ajax behaviour calling/parsing urls.

**Comment by Yivan** [comment]
Any news on it ? I think the patch is pretty easy. Instead using default site 0, use $this->document->getSite()->getId() as default site when editing document in back-office.
Are their more complications ?

Thanks.

**Comment by mattamon** [comment]
@Yivan is this still relevant for Pimcore 11?

**Comment by Yivan** [comment]
@mattamon Hello, I don't know, but as their is a workaround (by forcing the site parameter), you can close it if needed. Thanks.

**Comment by mattamon** [comment]
@Yivan Thank you for your response! I will close the ticket then! :)
