### ISSUE TITLE
[ASSETS] upload problems with large office files

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#3974]
# Bug Report

Try to upload the Attached Excel File (or a certain bigger Excel File) you run in an error like "pimcore.ERROR: Couldn't load document /home/project/www/web/var/assets/_temp/downloads/2019_02_21_09_16_49_export.xlsx only PDF documents are currently supported [] []". After a few Minutes or you reload the Pimcore UI the File is successfully saved and is available!

It seems the error only occures on bigger Excel Files.

[2019_02_20_16_17_44_export.xlsx](https://github.com/pimcore/pimcore/files/2888413/2019_02_20_16_17_44_export.xlsx)

**Comment by brusch** [comment]
Possible solution: do the processing in the background -> similar to the image optimization queue (using the `TmpStore` and a maintenance job).
