### ISSUE TITLE
[Feature request] More verbose translation import error dialouge

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#3976]
# Feature Request

## Feature description

When something goes wrong with Import & Merge CSV for translations the only error given is this:

![skarmbild 68](https://user-images.githubusercontent.com/279826/53163886-5a3d9b00-35cf-11e9-8224-5dd8ebff2d0f.png)

The CSV file has been run through a linter with no reported problems and visually inspected.

A way to know with a little more detail what is actually wrong would be very nice.

**Comment by NiklasBr** [comment]
This is still relevant

**Comment by NiklasBr** [comment]
This is still relevant

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
