### ISSUE TITLE
OneToOne DataType/Reverse OneToOne

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#3977]
A OneToOne Datatype would be good. Basically what the OneToMany already is, but explicitly only allow it to be related to one other Item. A use case for that is following:

 - Customer
     - user (`getUser`, `setUser`)
 - User (Reverse)
      - customer (`getCustomer`, `setCustomer` - calls `setUser with $this`)

Where the relation is between those two, and can only between those two and the relation should never be allowed to be used again (can be done with indexes). The relation will only be persisted on one side of the relation.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
