### ISSUE TITLE
Grid displayed empty if all attributes are assigned to operators

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#3978]
#### Steps to reproduce
1. Open Advanced Demo
2. Open any grid
3. Open grid config
4. Create new grid config where all attributes are assigned to operators, i.e.:
![image](https://user-images.githubusercontent.com/9052094/53170250-f8396180-35df-11e9-98b9-c3d30b3a0ae3.png)
5. Grid will be displayed empty even though there is data available

**Comment by weisswurstkanone** [comment]
Not related to operators but to filterable columns.
If grid only contains non-filterable columns then store is not automatically loaded.

Steps to reproduce:
- open grid config dialog
- remove all columns
- add image column
- apply
