### ISSUE TITLE
Memory Limit in PHP Hit when Pimcore Object Admin Screen shows too many records

### ISSUE THREAD

**Issue by adrianatyolk** [pimcore/pimcore#398]
When showing more than ~1000+ objects without pagination on pimcore admin screen - we will hit a memory error:

PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 79 bytes) in /var/www/html/pimcore/lib/Zend/Cache/Core.php on line 313

Is there a better way to query these objects in a non-linear complexity?

**Comment by brusch** [comment]
Please use our Google Group or Stackoverflow for this kind of questions. 
Basically the memory consumption heavily depends on the complexity and size of your objects.
