### ISSUE TITLE
Translation overriding

### ISSUE THREAD

**Issue by smoench** [pimcore/pimcore#3983]
As a symfony developer I would have the assumption that I am able to override translation messages as the [symfony documentation](https://symfony.com/doc/3.4/translation.html#translation-resource-file-names-and-locations) pronounce. Unfortunately you are decorating the symfony translator with your own to load json files. With this behaviour I'm not able to override messages as your message catalogue is added at last.

I'm aware of the admin/shared database translations but this not option for us. We have different deployment systems and we would not have a db migration for that.

A solution would be not decorate the symfony translator but adding a [custom loader](https://symfony.com/doc/3.4/components/translation/custom_formats.html#creating-a-custom-loader) instead. Shared database translation could be integrated there or provided as another custom loader.

Did I miss anything?
Please tell me your concerns and/or how I could help you.

**Comment by brusch** [comment]
This should be already solved by #4116 (see also #2197)
