### ISSUE TITLE
[Ecommerce] Unpublished object are indexed and used for search/filter, they should not and can lead to data disclose in frontend.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3984]
Hello,

It seems if we edit an object in the backend GUI, and click "Save a new version" (so we don't publish it), the change are made in the index so search/filter use those new values... but they are not published.
Is it the intended way to work ? Are there special configuration to prevent this...

**By default, ecommerce index should only be updated on the Save & Publish.**

Forcing reindex by using `php bin/console ecommerce:indexservice:bootstrap --update-index` correct the index with the data of the published object.

It is a real problem for now has it means some information on non-published new version could be disclosed as they are in the index, but they should not be until the version of the object is published.

For information, same problem on DefaultMysql and OptimizedMysql (didn't try ElasticSearch or other backend).

Thanks.

**Comment by fashxp** [comment]
it's a bug

**Comment by Yivan** [comment]
Thanks @fashxp for having fixed it quickly !
Have a nice evening.
