### ISSUE TITLE
Applying workflow actions on objects grid

### ISSUE THREAD

**Issue by FredoVelcro-zz** [pimcore/pimcore#3987]
Hello,

Is there a way to apply a workflow action to a objects grid listing ? (bulk workflow action in fact)
Thank you.

Best regards

**Comment by kubaplas** [comment]
@FredoVelcro If you're keeping data about workflow status in data object (e.g. using single_state type), you can change status in bulk using standard grid features. Another thing is to perform actions that are connected to this status change (notifying users, publishing objects) - you can catch an object save event and perform those operations manually.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
