### ISSUE TITLE
Image Advanced (object) - can't change the image

### ISSUE THREAD

**Issue by chix** [pimcore/pimcore#399]
Hi, after you drop an asset into the Image Advanced component, you can't change the asset, because the drop location is disabled. After you reload the object it works again. See animation:

![animation](https://cloud.githubusercontent.com/assets/2148902/12475951/ae69ea84-c026-11e5-8aa8-1917d9aa1c9a.gif)

**Comment by weisswurstkanone** [comment]
fixed in build 3608

**Comment by chix** [comment]
thank you :)
