### ISSUE TITLE
Notes & Events are not deleted when its Document,Asset or DataObject is deleted.

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#3990]
Notes & Events are not deleted when its Document,Asset or DataObject is deleted.

According to this Notes -> https://pimcore.com/docs/5.x/Development_Documentation/Tools_and_Features/Notes_and_Events.html

**Comment by brusch** [comment]
This is/was intentional, since we saw Notes & Event as kind of a log that shouldn't be modified by users. 
But this can be discussed, both approaches have it's pros and cons.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
