### ISSUE TITLE
[Object] Grid: SQL Filter Restriction via Permission

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#3992]
![bildschirmfoto 2019-02-26 um 10 37 31](https://user-images.githubusercontent.com/700119/53402730-921f5680-39b2-11e9-95fd-d68511c853ff.png)

Currently only admins are able to use the sql editor:

```js
hidden: !pimcore.currentuser.admin,
```
But sometimes it's useful or even required by users to use the sql editor even if they're no admins. Using a dedicated permission for that would be solution, what do you think?

**Comment by solverat** [comment]
Plus: Wouldn't it be a great thing if we could define a custom sql statement in each custom layout? For example, an input field above the "Selected Grid Columns" section:

![bildschirmfoto 2019-02-26 um 10 44 17](https://user-images.githubusercontent.com/700119/53403223-884a2300-39b3-11e9-9137-de4595bf98f6.png)

**Comment by brusch** [comment]
Hmm, to be honest, I'm not really a big fan of having too many different permissions, since this is a very specific feature,  I wouldn't see this as an additional permission.
