### ISSUE TITLE
Link error 5.4.0 Update message

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#3996]
# Bug Report
The message which does inform the user updating to 5.4.0 that this is the end of the traditional update path leads to the URL https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/Within_V5.html#page_Version-5-4-0 which is wrong and should be adapted.

**Comment by AlternateIf** [comment]
the link should be changed to: https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/Within_V5/index.html#page_Version-5-4-0

**Comment by brusch** [comment]
Fixed. Thanks!
