### ISSUE TITLE
[Element] Show notice message before closing a changed element

### ISSUE THREAD

**Issue by smoench** [pimcore/pimcore#3997]
# Bug Report / Feature Request

### Expected behavior
Given an user is logged-in in the admin panel
When they are starts editing an object
And changing a value
When they accidentally closing the tab
Then an dialog appears which describes the repercussions
And the user can choose between "Closing" and "Abort"

### Actual behavior
Given an user is logged-in in the admin panel
When they are starts editing an object
And changing a value
When they accidentally closing the tab
Then changes are lost

**Comment by fashxp** [comment]
should be already there
![image](https://user-images.githubusercontent.com/8792145/53496528-890db280-3aa2-11e9-811c-962296c3a042.png)

seems not to work anymore though, can you confirm?

**Comment by smoench** [comment]
I did not know about those options and I would not have excepted those options are enabled by default. Might be fair enough for admin users but opt-out those options on every new user is created is not very (user/admin) friendly. Having a "Don't show this message again" in those dialogs or having those options in group settings would be another solution.

When I opt-out "Disable unsaved content warning" and "Show close warning" everything works as expected :-)

**Comment by brusch** [comment]
_Show close warning_ is used for the Pimcore admin ui in general, not for individually opened entities, see https://github.com/pimcore/pimcore/blob/6b76fbafb8d193b55f9ff5cf64cd99eb9f8a2e0b/bundles/AdminBundle/Resources/public/js/pimcore/startup.js#L169

**Comment by smoench** [comment]
Yes, `Show close warning` is used for the Pimcore admin ui in general. The option `Disable unsaved content warning` is for a notice message before closing a changed element.

IMHO `Disable unsaved content warning` should be opt-out by default. This would be a huge improvement for the user experience.

**Comment by brusch** [comment]
@smoench  agree!
