### ISSUE TITLE
[Ecommerce] Inject RequestStack to FilterTypes via DI

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#4009]
to avoid things like https://github.com/pimcore/pimcore/blob/master/bundles/EcommerceFrameworkBundle/FilterService/FilterType/SelectCategory.php#L48

**Comment by dpfaffenbauer** [comment]
you should revise that a bit more to allow to inject whatever you want.

**Comment by fashxp** [comment]
this is possible anyway, since they are all services.
