### ISSUE TITLE
[Image-Thumbnails] Race condition for recursive mkdir

### ISSUE THREAD

**Issue by podarcis** [pimcore/pimcore#4011]
# Bug Report

Generating image thumbnails semi-parallel (both single instance and especially in cluster setup) can result in a race condition while creating the required sub-directory in web/var/tmp/image-thumbnails/ with the actual directory not being created.

The actual race condition may happen in [Asset/Thumbnail/Processor](https://github.com/pimcore/pimcore/blob/v5.6.5/models/Asset/Image/Thumbnail/Processor.php#L187) if another process already created sub-directories of the desired path or even the desired directory itself. The latter one isn't a problem as the call isn't checked anyway (another potential bug in case of "permission denied"). However, if part of the path (common sub directories) is being created by another process while current's process is doing the mkdir, [PHP seems to stop creating sub directories](https://bugs.php.net/bug.php?id=35326), which is plausible according to [PHP src](https://github.com/php/php-src/blob/PHP-7.3.3/main/streams/plain_wrapper.c#L1308).

There has been a [Symfony issue](https://github.com/symfony/symfony/issues/11626) for component Filesystem which detects such race condition and carries on if the desired directory has been created, but I assume it's also affected. Anyway, Pimcore\File is currently being used.

While in most environments this might not be a huge problem, as the thumbnail is generated on the next request. But in environments cached by a CDN or reverse proxy cache this leads to "filetype-not-supported" dummy image going to cache for some time depending on TTL.

### Example

1. First process recursively creates web/var/tmp/image-thumbnails/a/**b**/**c**/ for foo.png
2. Another process creates web/var/tmp/image-thumbnails/a/**b**/**d**/ for bar.png
3. When the first process created sub-dir "b" and the other process is trying to create "b", mkdir exits without creating "d"

### Expected behavior

Thumbnail generation should always work regardless of parallel processes requesting thumbnails. Frameworks mkdir should either ensure the directory is correctly created and/or at least throw an exception, if the directory could not be created instead of returning "filetype-not-supported" image.

### Actual behavior

Directory isn't created and the response is "filetype-not-supported" image which might be cached by CDN/Varnish/...

The logs shows ```ImagickException: unable to open image    [...]   No such file or directory``` or ```ImagickException: WriteBlob Failed``` as it tries to create a file in a non-existing directory.

### Steps to reproduce

- Clear temporary files (thumbnail cache)
- Start multiple requests to thumbnails. Could be easily reproduced with multiple app instances sharing var/ and web/var (cluster setup) but even on single machine this happens occasionally.

### Crude workaround - just for testing - not a fix!

This test checks whether directory has been created. If not, it waits a random number of microseconds and tries creating the directory again. If it still does not exist, throw an exception.

```diff
--- a/htdocs/pimcore/models/Asset/Image/Thumbnail/Processor.php	2019-03-01 10:08:40.440999318 +0100
+++ b/htdocs/pimcore/models/Asset/Image/Thumbnail/Processor.php	2019-03-01 10:27:28.017894543 +0100
@@ -176,7 +176,15 @@
         }
 
         if (!is_dir(dirname($fsPath))) {
-            File::mkdir(dirname($fsPath));
+            // Workaround für mkdir race condition
+            if (!File::mkdir(dirname($fsPath)) && !is_dir(dirname($fsPath))) {
+                Logger::error("Unable to create dir " . dirname($fsPath) . " or parts of it already exist, trying again");
+                usleep(rand(100, 100000));
+                if (!File::mkdir(dirname($fsPath)) && !is_dir(dirname($fsPath))) {
+                    Logger::error("Still no luck creating dir " . dirname($fsPath) . ". Throwing exception...");
+                    throw new \Exception("mkdir race condition for thumbnail {$fsPath}");
+                }
+            }
         }
 
         $path = self::returnPath($fsPath, false);
```

### Possible fix for just "filetype-not-supported" being returned

This checks whether the directory has been successfully created and throws an exception if it hasn't.

```diff
--- a/htdocs/pimcore/models/Asset/Image/Thumbnail/Processor.php	2019-03-01 10:08:40.440999318 +0100
+++ b/htdocs/pimcore/models/Asset/Image/Thumbnail/Processor.php	2019-03-01 10:27:28.017894543 +0100
@@ -176,7 +176,15 @@
         }
 
         if (!is_dir(dirname($fsPath))) {
-            File::mkdir(dirname($fsPath));
+            if (!File::mkdir(dirname($fsPath)) && !is_dir(dirname($fsPath))) {
+                throw new \Exception("Error creating directory for thumbnail '{$fsPath}'.");
+            }
         }
 
         $path = self::returnPath($fsPath, false);
```
### Possible fix for race condition?

Don't use PHP's recursive-mkdir and instead create each sub-directory within a loop.

### Used/ affected versions

* PHP 7.1.26 but shouldn't matter
* Pimcore 5.1.3 but shouldn't matter

**Comment by podarcis** [comment]
About my "Possible fix for just "filetype-not-supported" being returned": Wouldn't work, as ```Image\Thumbnail::generate()``` catches any exception and returns the filetype-not-supported image. 

Maybe hard errors should be handled by responding with 500 and only if the filetype is really not supported, return the dummy image.

**Comment by dpfaffenbauer** [comment]
Would it help to use Symfony Filesystem Component instead of Pimcore\File?

Another thing is: The thumbnail generations should be moved to a service and if it can't create the image, it should throw an exception or an event or something, that then handles the fallback image thing. So, with a service, it's easier extendable.

**Comment by podarcis** [comment]
@dpfaffenbauer 

> Would it help to use Symfony Filesystem Component instead of Pimcore\File?

I don't think so, as it only handles the case "desired directory has already been created by another process, so be nice" https://github.com/symfony/filesystem/blob/3.4/Filesystem.php#L93
