### ISSUE TITLE
Always edit in window/overlay

### ISSUE THREAD

**Issue by julmot** [pimcore/pimcore#4013]
In e.g. the video brick in the basic demo, an overlay/window appears to enter all the needed properties.

Maybe I'm missing something or haven't found the corresponding documentation, but to avoid any conflicts with existing frontend components in the editmode and avoid spending time in optimizing complex bricks for the editmode, I would like to always edit a brick within the overlay/window.

It seems that Pimcore shows the overlay based on the editable (e.g. video). Is there a way to re-use the existing Pimcore modal/overlay/window component to make the editing process recognizable with the Pimcore look and feel? So, basically move everything that can be edited into the Pimcore overlay? Then, of course I would also need to have a way to always generate Pimcore editables inline, without the overlay (otherwise it would result in two overlays overlapping each other).

So, I'd like to always have this button:

![000030](https://user-images.githubusercontent.com/8310677/53655501-ada78d00-3c50-11e9-8636-b30840b33656.png)

**Comment by solverat** [comment]
You may want to checkout the [toolbox bundle](https://github.com/dachcom-digital/pimcore-toolbox).

**Comment by fashxp** [comment]
you can specify a edit template `<templateLocation>/edit.<suffix>`
see also https://pimcore.com/docs/5.x/Development_Documentation/Documents/Editables/Areablock/Bricks.html and https://pimcore.com/docs/5.x/Development_Documentation/Documents/Editables/Areablock/index.html#page_Brick-specific-Configuration

**Comment by julmot** [comment]
Thank you guys for your help! Unfortunately I'm sick at the moment, but I'll test this as soon as I can.

**Comment by julmot** [comment]
Thanks @fashxp, this was exactly what I needed!
