### ISSUE TITLE
CSV import fails on upload

### ISSUE THREAD

**Issue by lucjanw** [pimcore/pimcore#4015]
Hi there,

I've got fresh installation of pimcore 5 advanced-demo on centos 7. I did an upgrade to version 5.6.6.

I tried to import simple CSV with new categories of products (just two values separated by “;”).
From the tree of Category I select CSV import ile by Upload feature, a file is on my laptop. 

![obraz](https://user-images.githubusercontent.com/47985846/53738432-796ddf80-3e8f-11e9-876a-f49dbfb78d7c.png)

Just after file selection I receive below error message:
![obraz](https://user-images.githubusercontent.com/47985846/53738518-ae7a3200-3e8f-11e9-9655-1710194b6237.png)

![obraz](https://user-images.githubusercontent.com/47985846/53738558-c8b41000-3e8f-11e9-9a14-805def49cb47.png)

I’ve checked current demo.pimcore.org and this upload works there.
I tried to check this error message on github and forum but there is no information about such case.
I asked about that on talk.pimcore.ord forum but no answer. 
I'm not sure if this is a bug but may I ask about some tips what I’m doing wrong, maybe some settings somewhere?

Thank you

**Comment by brusch** [comment]
Doesn't seem to be an error of the Pimcore core ... can't din the error message, maybe it's specific to your code?

**Comment by kraigmustard** [comment]
Did you  ever manage to solve this? I'm having the same problems. I export a csv from the data object section as a CSV. but when selecting the file  to upload it into the same folder on my staging server. It shows error as well.
