### ISSUE TITLE
Right click on tree nodes (document, asset, object) also triggers a left click in Firefox

### ISSUE THREAD

**Issue by chix** [pimcore/pimcore#402]
Tested in Firefox 43.0.4. It does not happen in Chrome and IE. Don't know about other browsers.

**Comment by brusch** [comment]
This is actually a bug in ExtJS 6 - this should be fixed in the next GPL version of ExtJS 6

**Comment by chix** [comment]
oh, ok, thanks for the info

**Comment by weisswurstkanone** [comment]
fixed in build 3622
