### ISSUE TITLE
[2FA] Forcing 2FA for Roles

### ISSUE THREAD

**Issue by scrummer** [pimcore/pimcore#4024]
# Feature Request
Enforce 2-factor-authentication on group level.

## Feature description
Currently it's possible to force a single user to use 2FA by checking the corresponding checkbox in the user settings:
![image](https://user-images.githubusercontent.com/15173170/53866814-bbfbfd00-3ff2-11e9-80b8-cc97c58b9b13.png)

It would be nice to have the same option for groups, as in most cases the 2FA is enforced when a user has some permission to handle sensitive data. Those permissions are mostly granted by roles and not directly on the user.

**Comment by brusch** [comment]
Agree ... we'd be happy to merge a PR for that - shouldn't be too hard to implement. 
Thanks in advance! 😊

**Comment by brusch** [comment]
Closing for now, but as I said, we're happy to merge a PR for that 😊
