### ISSUE TITLE
Cart->getItemAmount(true) returns mixed amount

### ISSUE THREAD

**Issue by deltatag** [pimcore/pimcore#4025]
https://github.com/pimcore/pimcore/blob/dc6a0a3c35f32f5240e9c091528a934fcee8a987/bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php#L386

Calling getItemAmount(true) returns mixed amount for items:
* Calculates amount of items without sub items
* Calculates amount of items with sub items **without adding the amount of parent item**

Calling getItemAmount(true) should either return only the count of sub items **or** return the count of all items in the cart

**Comment by fashxp** [comment]
we need to add a third calculation mode to cope with all possibilities. 

```
    const COUNT_MAIN_ITEMS_ONLY = false;
    const COUNT_MAIN_OR_SUB_ITEMS = true;
    const COUNT_MAIN_AND_SUB_ITEMS = 'main_and_sub';
```

should also be applied to `getItemCount`

since `getItemCount` and `getItemAmount` are not consistent, this will be a BC at one of the cases.

**Comment by brusch** [comment]
Would be nice to have that in 5.8.0 ... @deltatag can you provide a PR for that? 😊
