### ISSUE TITLE
Document\Hardlink  is using source document properties instead of hardlink properties itself.

### ISSUE THREAD

**Issue by anyMOTION-GRAPHICS** [pimcore/pimcore#4026]
# Bug Report
Document\Hardlink is using source document properties instead of hardlink properties itself.

### Expected behavior
(Like in Pimcore 5.2.1) Hardlink should use properties from hardlink and not form source document. There is also a checkbox "Use properties from source document" if the editor wants properties from source document.

### Actual behavior
Hardlink is using always properties from source document.

### Steps to reproduce
Here are some screenshots from https://demo-basic.pimcore.org to reproduce bug:
![step_1](https://user-images.githubusercontent.com/12711917/53867346-f1edb100-3ff3-11e9-8da3-23376d21902f.jpeg)
![step_2](https://user-images.githubusercontent.com/12711917/53867356-f74afb80-3ff3-11e9-8b38-2cee1979dfeb.jpeg)
![step_3](https://user-images.githubusercontent.com/12711917/53867360-f914bf00-3ff3-11e9-8755-7bf1bcd6a438.jpeg)
![step_4](https://user-images.githubusercontent.com/12711917/53867364-fade8280-3ff3-11e9-8c44-ba8a52f380cd.jpeg)

**Comment by brusch** [comment]
Sorry, I wasn't able to reproduce the problem, see: 
![13-03-_2019_11-47-56](https://user-images.githubusercontent.com/142037/54273310-f2eb8900-4585-11e9-9073-93a792b90113.gif)

**Comment by anyMOTION-GRAPHICS** [comment]
Dear Mr. @brusch 
sorry for the late reply and thank you for the fast processing on our request. Your conclusion is missing out one little detail, maybe our description wasnt too good. Therefore we made a short demonstration video which may help you to reproduce this issue.
Please have a view at it >> https://download.anymotion.de/pimcore-issue-4026-anymotion.mp4
USER: anymotion     PASS: dowNLo4D
best regards, j.domdey /anymotion QA
