### ISSUE TITLE
YouTube Embed - Subscribe to channel not working

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#4035]
The YouTube player offers the possibility to directly subscribe to a channel.
This is not working and giving a 404 - I guess because of the "no-cookie" integration.
https://www.youtube-nocookie.com/signin?context=popup&next=https%3A%2F%2Fwww.youtube-nocookie.com%2Fpost_login

![image](https://user-images.githubusercontent.com/13643455/53951668-487bed80-40cf-11e9-8811-4950316c4a3c.png)

**Comment by brusch** [comment]
I'm afraid that there's nothing really we can do about it, that needs to be fixed by YouTube.
