### ISSUE TITLE
Rename Ecommerce Interfaces to comply with PSR

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#4038]
see: https://www.php-fig.org/bylaws/psr-naming-conventions/

Interfaces in the EcommerceBundle are currently prefixed with ```I``` 

PSR-Naming Convention is postfixing with ```Interface```

e.g. 
ICart --> CartInterface
ICartItem --> CartItemInterface

**Comment by brusch** [comment]
Duplicates #3652
