### ISSUE TITLE
[Data Object] Class Definitions: Allow underscores in ID and Class Name

### ISSUE THREAD

**Issue by FredoVelcro** [pimcore/pimcore#4047]
Hello,

Why can't we use underscore in the Object Class creation modal in BackOfice ?
In our use case, we have a class import process with custom ids like BM_PageCustom for our classes and it works fine.

As the database field "id" is of type varchar, it would cause no problem / regression i think ?
This issue may reconsider the question of disallowing underscore : 
https://github.com/pimcore/pimcore/issues/3839

Thank you for feedback !

Best regards.

**Comment by brusch** [comment]
It is just not allowed at the moment, but I also see no problem by allowing them.
@weisswurstkanone what do you think?

**Comment by brusch** [comment]
For the ID we need additional validation: if `/(query|store|relations)_[^_]+$/` is true, the name is not valid. 
Explanation: 
Consider you have the following 2 ID's: 
`query_2` and `2` then this will end up in a name collision.

**Comment by brusch** [comment]
@FredoVelcro Would you make us a PR for that? :)

**Comment by FredoVelcro** [comment]
👍
