### ISSUE TITLE
Weird code found in class exporter (webservice)

### ISSUE THREAD

**Issue by SmashingQuasar** [pimcore/pimcore#4049]
Hello,

I stumbled upon the following code:
```php
    /**
     * @param $class
     * @param $options
     */
    public function map($class, $options = null)
    {
        $arr = $class->fieldDefinitions;
        $result = [];
        foreach ($arr as $item) {
            $result[] = $item;
        }
        $class->fieldDefinitions = $item;

        parent::map($class);
    }
```
This code originates from this file: `vendor\pimcore\pimcore\models\Webservice\Data\ClassDefinition.php`.
I think there are multiple oversights in this code. `$options` is never used and `$result` is incremented but never used. Moreover, in some cases it seems that `$class->fieldDefinitions` is a boolean (`false`) and not an array which completely crashes the script.

I stumbled upon this since I tried to export a class and it crashed. I can provide the json of the class exported if you want. I managed to export it by deleting this code and using only the `parent::map`.

Thanks

**Comment by weisswurstkanone** [comment]
Thx. Guess we should get rid of it as it is a) wrong and b) will be sorted out by the parent anyway.
