### ISSUE TITLE
[Ecommerce] First run of index creation for Elastic6 send error

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4051]
Hello,

@fashxp I saw all your fix for the ecommerce, thanks a lot.

Here is a small one which can be easily fixed.
With Elastic6, on the first run of:
`php bin/console ecommerce:indexservice:bootstrap --create-or-update-index-structure`

this error is returned :

```
In AbstractElasticSearch.php line 114:
  Warning: file_put_contents(/var/www/html/var/ecommerce/elasticsearch-index-version-ecommerce.txt): failed to open stream: No such file or directory
```

Creating manualy `/var/www/html/var/ecommerce` prevent this error.
I think this directory should be automaticaly created by the command `ecommerce:indexservice:bootstrap`.

Thanks.

**Comment by fashxp** [comment]
should be already fixed with this one: 
https://github.com/pimcore/pimcore/pull/4016

https://github.com/pimcore/pimcore/pull/4016/files#diff-d02a59391d96d7d11a3a41cfdf9270deR114
