### ISSUE TITLE
Advanced object to object relation field issue with fieldcollection

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#4054]
When dirty detection is disabled this bug still occurs:
https://github.com/pimcore/pimcore/issues/3558

**Comment by weisswurstkanone** [comment]
Unable to reproduce. Please provide more details.

**Comment by markus-moser** [comment]
Hm... I am not able to reproduce it in the latest dev-master too. But I was able to reproduce it in 5.5.4 where the bugfix from the link issue is contained. So either any other commit fixed it or there is something different in my constellation. I'll check it again when I update my client project to the latest Pimcore version.
