### ISSUE TITLE
Twig issue with version 2.7

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#4058]
Twig 2.7 is not compatible with Pimcore due some major namespace changes: 
https://twig.symfony.com/doc/2.x/deprecated.html

**Comment by brusch** [comment]
Fixed in b44d85f95ecbeb8b27db0ad0c191ae22fc431fd4

**Comment by dpfaffenbauer** [comment]
what exactly is not compatible?

**Comment by smoench** [comment]
Twig 2.7 is keeping backwards compatibility:
>This document lists deprecated features in Twig 2.x. Deprecated features are kept for backward compatibility and removed in the next major release (a feature that was deprecated in Twig 2.x is removed in Twig 3.0).

Everything works as before. Only deprecation warnings are trigger.

**Comment by brusch** [comment]
Was a bug in `2.7.0`: 

> ( ! ) Fatal error: Declaration of Pimcore\Twig\TokenParser\GlossaryTokenParser::parse(Twig_Token $token) must be compatible with Twig\TokenParser\TokenParserInterface::parse(Twig\Token $token) 

Fixed in Twig `2.7.2` - revered changes of b44d85f95ecbeb8b27db0ad0c191ae22fc431fd4
