### ISSUE TITLE
composer / self-updater mode

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#406]
**awesomeness**
- split *"file update"* and *"system updates"*
- integrate *"system updates"* as own command, so we can trigger it with the post composer event
- each build can have a `post-update.php` which will be delivered with each update 
- separate and integrate version and build numbers to `config/system.php` so the post update event knows what to do (for example, if build 10 is installed and the update comes with build 14, the composer / or self-updater command will trigger the post-update.php for 11,12,13 and 14.
- check if system is running with composer or self-updater. if the system runs with composer, disable the self-update feature to reduce confusion

**super awesomness**
- move "pimcore" and "website_example" to a stand-alone repo to reduce data and clarify things out
- run pimcore straight out of vendor

the only disadvantage is the lost of the pre- and post-update manipulation of builds, because composer updates straight to the given build/version. but a partly integration of composer is not useful.

i think that would be a great feature for version 4.

**Comment by brusch** [comment]
I see the same problems as already discussed here: #366 
We can't split the update process into "file update" and "system update", ... you have cases like "object classes" where the actual code (file) depends on the database and vice versa, e.g. take this example using pre and post updates: 
https://github.com/pimcore/pimcore/blob/fb5d57e7b09ec1e0581b91beeb7b5db86c383c23/update/3615/preupdate.php
https://github.com/pimcore/pimcore/blob/24bcc168fac0a7699f1a74baf6bf0f4abc544d90/update/3615/postupdate.php

in this case it's essential that one part is executed before the "file update" and the other one after it. 

I hope you understand the problem. 
If you have any possible solution how to avoid this problems -> let us know :)
