### ISSUE TITLE
[Document] Areabrick configuration in service class

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#4066]
# Feature Request

It would be great if there was the possibility to set the Area parameters from inside the respective service class rather than only from the editbale. The parameters of the areas are mostly not dependent of the editable's context.

Currently the configuration is only possible as stated in the docs:

```php
<?= $this->areablock("myArea", [
    "params" => [
        "my-brick" => [
            "forceEditInView" => true,
            "editWidth" => "800px",
            "editHeight" => "500px"
        ]
    ]
]); ?>
```

**Comment by brusch** [comment]
What do you think about the following approach? 

```twig
{{ pimcore_areablock('foo-bar', 'AppBundle\\Document\\MyTagConfiguratorService', {
    param1: 'foo',
    param2: 'bar'
}) }}
```

```php
<?php

namespace AppBundle\Document;

use Pimcore\Model\Document\Tag\TagConfiguratorInterface;

class MyTagConfiguratorService implements TagConfiguratorInterface {

    public function getConfiguration(array $params = []) : array
    {
        // return config used by the tag
        return [
            'reload' => $params['reload'] ?? false,
            "allowed" => ["iframe","googletagcloud","spacer","rssreader"],
            "group" => [
                "First Group" => ["iframe", "spacer"],
                "Second Group" => ["rssreader"]
            ],
        ];
    }
}
```

@dpfaffenbauer @markus-moser @dvesh3 @jremmurd  what do you think? Is there a better way? 
Thanks for your feedback :)

**Comment by dvesh3** [comment]
@brusch This suggested approach breaks existing templates, right? we can move service param to the last. Everything else looks good to me ☝️

**Comment by brusch** [comment]
Shouldn't break existing templates, as the type of the 2nd parameter isn't defined. 
But you're right, maybe it's better to change the order and make the service name the 3rd argument 👍

**Comment by brusch** [comment]
Updated the example above accordingly.

**Comment by dpfaffenbauer** [comment]
why not use twig extensions? it is "just" a template config

**Comment by dpfaffenbauer** [comment]
Or PHP Template Extensions in that case

**Comment by brusch** [comment]
Yes, would be also possible, like that idea as well (nothing to change then in Pimcore 😊).

**Comment by dpfaffenbauer** [comment]
And: No BC, and no magic call of `Pimcore::getContainer()` ;)

It works pretty good with template extensions, toolbox is doing that

**Comment by brusch** [comment]
See https://github.com/dachcom-digital/pimcore-toolbox/tree/master/src/ToolboxBundle/Twig/Extension

**Comment by dpfaffenbauer** [comment]
More precisely: 

https://github.com/dachcom-digital/pimcore-toolbox/blob/master/docs/0_Usage.md

And

https://github.com/dachcom-digital/pimcore-toolbox/blob/master/src/ToolboxBundle/Twig/Extension/AreaBlockConfigExtension.php#L39

**Comment by brusch** [comment]
I'd really prefert the Twig extension approach -> closed for now, please feel free to continue the discussion.

**Comment by khusseini** [comment]
Here also an addition to the toolbox solution. I created a bundle with which you can create and configure areabricks using yaml only. It does not mess with twig templating and can be used alongside the pimcore toolbox. It basically injects the configured editables in your `areabrick/view.html.twig` with some other features like injecting data from symfony services as variables. 

 https://github.com/khusseini/PimcoreRadBrickBundle

**Comment by mcuenez** [comment]
I would love to see this feature though.

When using the approach shown in the comment of @dpfaffenbauer:

> More precisely:
>
> https://github.com/dachcom-digital/pimcore-toolbox/blob/master/docs/0_Usage.md

It will always lead to the necessity of knowing that this extension exists. Thus, this approach is prone to error (as the referenced link states):

> Important! Make sure that every pimcore_areablock in your project implements the toolbox_areablock_config() element. If you miss this, the toolbar will get messy.

Pimcore already uses a config to define how editables are loaded:

```yaml
documents:
    tags:
        # ... omitted
        prefixes:
            - \Pimcore\Model\Document\Tag\
            - \Document_Tag_
```

Why not allow custom `prefixes` here too? This way you provide more flexibility, avoid the need of `Twig` extension, and decrease the development efforts.
