### ISSUE TITLE
Raw Meta Tags not rendered when using \Pimcore\Model\Document\Service::render

### ISSUE THREAD

**Issue by knoepfchen23** [pimcore/pimcore#4068]
When rendering a Document with the service "\Pimcore\Model\Document\Service" the Meta Tags (on Document in Tab "SEO & Settings" -> Section "HTML-Tags (<meta .../> <link .../> ...)" ) not get rendered.
The Problem is in the DocumentMetaDataListener (`Pimcore\Bundle\CoreBundle\EventListener\Frontend\DocumentMetaDataListener`). In method "`onKernelRequest`" the following lines are problematic:
```php
if (!$event->isMasterRequest()) {
    return;
}
```
After removing these lines it works.

Code to reproduce:
```php
    /**
     * @Route("/admin/meta-tag-error")
     */
    public function metaTagErrorAction() {
        $document = \Pimcore\Model\Document::getById(1);
        $attributes = [
            \Pimcore\Bundle\CoreBundle\EventListener\Frontend\ElementListener::FORCE_ALLOW_PROCESSING_UNPUBLISHED_ELEMENTS => true,
        ];
        $html = \Pimcore\Model\Document\Service::render($document, $attributes);
        dump($html);
        exit(1);
    }
```
When you put the Code in an Controller and add some Meta Tags to that document (id:1) you should be able to reproduce. In the template (twig) for the document the helper "`{{ pimcore_head_meta() }}`" should be used.

**Comment by brusch** [comment]
I've just introduced a new attribute that allows you to force the injection. 
Just add `\Pimcore\Bundle\CoreBundle\EventListener\Frontend\DocumentMetaDataListener::FORCE_INJECTION => true` to your attributes in order to force it :)

**Comment by knoepfchen23** [comment]
Thanks:)
