### ISSUE TITLE
Missing config and cancel button for areas

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#4070]
# Bug Report

If an areabrick is included via `$this->area()` rather than via `$this->areablock()` 

1. there is no cancel button in the editing popup (in the docs refered to as `edit.php`) and so I cannot close the popup without saving (there is no close button and the esc key does not work as well).
![image](https://user-images.githubusercontent.com/9052094/54349931-838c9c80-464c-11e9-9bcf-be683d712b55.png)

2. the config params `editWidth` and `editHeight` are not applied.

**Comment by brusch** [comment]
See: https://github.com/pimcore/pimcore/blob/c62924ca5c3d0c482a71097cb0231aff143208d6/bundles/AdminBundle/Resources/public/js/pimcore/document/tags/area.js#L46
