### ISSUE TITLE
[Cache] Define behavior when cache backend redis is configured but not available for Pimcore

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#4073]
currently, also pimcore is down. 

possible necessary to ensure cache consistency. 
if so, add corresponding explanation to docs.

**Comment by brusch** [comment]
1. find out why Pimcore crashes when Redis is not available
2. find out if this is necessary
3. fix it or document it accordingly

**Comment by dvesh3** [comment]
> 1. find out why Pimcore crashes when Redis is not available

No failover handling in Redis connection factory https://github.com/pimcore/pimcore/blob/5e5d3a0fa57c81fa2f1006f57beb3b21961881ea/lib/Storage/Redis/ConnectionFactory.php#L38

> 2. find out if this is necessary

I believe it is necessary to stop application from working completely if redis is configured and not available as it is then considered as final source of truth.

Think about the scenario: In case of Redis failure, you use fallback storage for a while and then Redis is up again! user will see/use obselete data from Redis, which is completely wrong and leads to lot of confusion.

> 3. fix it or document it accordingly

I think we should just add notice in docs

@brusch @fashxp your thoughts?

**Comment by brusch** [comment]
> I think we should just add notice in docs
Agree - I'm totally fine with that as well.

**Comment by fashxp** [comment]
optional, more sophisticated solution would be automatic failover to mysql cache, but not return to redis automatically anymore.
