### ISSUE TITLE
Wrong parent for variants in V5.6.6

### ISSUE THREAD

**Issue by faridmovsumov** [pimcore/pimcore#4079]
When I create variant parent_id is wrong in a database. It should be an id of parent object but instead of this it is id of folder that parent object is under.

I couldn't see variants in the tree after this happening. 

Is that known bug? If not I will try to fix it.

**Comment by brusch** [comment]
Shouldn't be the case, so yes a PR would be great!

**Comment by faridmovsumov** [comment]
The reason was some code in our listener. I am closing the issue.
