### ISSUE TITLE
Pretty url is not working for main domain 

### ISSUE THREAD

**Issue by pimcore-sg** [pimcore/pimcore#4099]
Pretty url is not working for home if other websites are created. Please refer the attached screenshot.

![pim local com    Pimcore](https://user-images.githubusercontent.com/47360708/54672409-f949aa00-4b1d-11e9-9a59-8fbaf5b69dfc.png)

**Comment by brusch** [comment]
Since we're really talking about an edge-case here, this has absolutely no priority, but of course we'd be happy to merge a PR for that. 
If you don't want or can't provide a PR, please let me know, so we can close this ticket. 
Thanks!
