### ISSUE TITLE
[Ecommerce] Getting sub items of cart item ignores defined cart item class

### ISSUE THREAD

**Issue by deltatag** [pimcore/pimcore#4100]
The cart item class can be defined via the following method in own cart class implementations:

https://github.com/pimcore/pimcore/blob/master/bundles/EcommerceFrameworkBundle/CartManager/Cart.php#L25

But this method defines only the class for the items fetched by `$cart->getItems()`. All sub items received with `$cartItem->getSubItems()` are implementations of the default cart item class. I think the problem lies somewhere near:

https://github.com/pimcore/pimcore/blob/master/bundles/EcommerceFrameworkBundle/CartManager/CartItem.php#L106

This problem could be fixed by adding:

`$itemList->setCartItemClassName(get_class($this));`

**Comment by fashxp** [comment]
fixed with #4136
