### ISSUE TITLE
[Permissions] Divide "publish" and "only save new version" permission

### ISSUE THREAD

**Issue by ivanmerta** [pimcore/pimcore#4102]
In Workspaces you can assing save and publish permission. With publish you also get "only save new version" permission. 
I am having use case where I want to assign users/roles permission only to " only save new version" (without unpublishing it - but last version would still remain published) but not to "publish".
This is not natively possible currently as "save" button actually unpublishes the object.

Improvement: To divide "publish" and "only save new version" into two permissions.

**Comment by brusch** [comment]
Currently it's not the plan to make the permissions more granular.
