### ISSUE TITLE
[Object] Grid: don't clear active filters when adding a new column

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4108]
Hello,

This is more a UX improvement. It has been noticed by some of people using pimcore, than adding a new colomn in the object grid make the active filters reset.

The use case is if grid users begin to set some filters, and after they want to add a new column because they need this information... they will loose the filters, and so need to set them again.

I hope it makes sense, it can really help daily work for users on Pimcore GUI as grid is a central tool.

Thanks.

**Comment by weisswurstkanone** [comment]
https://github.com/pimcore/pimcore/pull/4249
