### ISSUE TITLE
[DataObjects] Many-To-Many Object Relation Field ignores "Visible Fields" if set to "Not editable"

### ISSUE THREAD

**Issue by ttheuerkauf** [pimcore/pimcore#4109]
# Bug Report
If for a Many-To-Many Object Relation Field setting **Visible Fields** is set and the relation field is also set to **not editable**, the standard view with full object path is displayed and **Visible Fields** is ignored.

### Expected behavior
The setting **Visible Fields** is working for editable and not editable fields the same way.

### Actual behavior
See introduction of bug report above.

### Steps to reproduce
1. Add Many-To-Many Object Relation Field (e. g. for **news** in class **user** in demo) with only **key** set in **Visible Fields** and set it to be **editable**.
2. Open a user and add a news-relation, only field **key** is shown there as expected.
3. Save the user (optional, not required for reproduction).
4. Change the relation field to **not editable**.
5. Reload user, standard view of relation field is shown, **Visible Fields** is ignored.

**Comment by brusch** [comment]
Fixed by 00d1120f8a13def7b22362883d5f9dbdc8bc002d
