### ISSUE TITLE
[Workflow] `supports` class_exists validation problem/error

### ISSUE THREAD

**Issue by smoench** [pimcore/pimcore#4110]
# Bug Report
We have a docker environment and have some integration tests for our workflows. In our CI we have an extra testing image/container, creating a new db container and executing the installation process. As we are not adding the generated data object classes to our repository the installation process is failing with: `Invalid configuration for path "pimcore.workflows.XXX.supports.0": The supported class "\\Pimcore\\Model\\DataObject\\XXX" does not exist.`

This error is happening as data object class generation is executed after the Symfony configuration validation.

My proposal would be remove the following validation from configuration at https://github.com/pimcore/pimcore/blob/master/bundles/CoreBundle/DependencyInjection/Configuration.php#L966.

**Comment by brusch** [comment]
Just ensure that the classes are there, then it works like a charm 😉In my opinion it's not right to take the validation away, as this will may cause other confusions for others who rely on that.

**Comment by dpfaffenbauer** [comment]
but thats a chicken - egg problem. You need to have the classes installed in order to run the task to create the classes in the first problem. So you will never be able to generate the classes.

**Comment by smoench** [comment]
Really? Without an DB Pimcore cannot generate classes so I need to install Pimcore. We have a chicken-egg-problem here.

**Comment by dpfaffenbauer** [comment]
I would also remove the class_exists check

**Comment by smoench** [comment]
@brusch Could please reopen this ticket? We might could find another solution for that.

**Comment by dpfaffenbauer** [comment]
@smoench as a temporary solution: just create parent classes and configure the workflow for the parent-class. That class always exists

**Comment by smoench** [comment]
@brusch Should be reopened! The workaround is working but not a solution!
