### ISSUE TITLE
extraAllowedContent not settable via custom  configuration by adding customConfig.

### ISSUE THREAD

**Issue by michas79** [pimcore/pimcore#4114]
# Bug Report

It is not possible to use ckeditor config "extraAllowedContent"
### Expected behavior
It is possible to change allowed content by using custom configuration for CKEditor like it is discribed here https://pimcore.com/docs/5.x/Development_Documentation/Documents/Editables/WYSIWYG.html

### Actual behavior
Some config  will be overwritten for example "extraAllowedContent" by 
 eConfig.extraAllowedContent = "*[pimcore_type,pimcore_id]";

### Steps to reproduce

- Using the Code from the code example 'custom config'.
- try to put a span-tag in wysiwyg editor
- watch result 

### Code example
```
CKEDITOR.editorConfig = function (config) {
    config.uiColor = '#AADC6E'; //this works
    config.extraAllowedContent = 'span{unicode-bidi,direction,display}'; // this not
};
```

# Feature Request

**Comment by sebastianMoser** [comment]
The following works for me.

Put this in wysiwyg.js for instance:
```
pimcore.document.tags.wysiwyg.defaultEditorConfig = pimcore.document.tags.wysiwyg.defaultEditorConfig || {
   extraAllowedContent : 'span'
};
```

Include the javascript in your Bundle class:
```
<?php
   use Pimcore\Extension\Bundle\AbstractPimcoreBundle;

   class BaseBundle extends AbstractPimcoreBundle {

      public function getEditmodeJsPaths() {
         return [
            '/bundles/base/js/pimcore/wysiwyg.js'
         ];
      }
   }
```

**Comment by fashxp** [comment]
we switched to tinymce with Pimcore 11
