### ISSUE TITLE
Open reports in new tabs 

### ISSUE THREAD

**Issue by Heiko-H** [pimcore/pimcore#4118]
# Feature Request
Open and show a report in its own tab
## Feature description
One of our customer works a lot with reports. He sometimtes needs to open more than one report at the time with different filters and sorting. Switching between reports resets filters and sorting. Is there any chance to implement for example a checkbox in the custom reports which indicates that the report should (or can) be opened in an extra tab and not inside the reports tab?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
