### ISSUE TITLE
Adding multiple ClassificationStore Keys to a Group throws an exception (v3.1.1)

### ISSUE THREAD

**Issue by EazyAlvaro** [pimcore/pimcore#412]
Reproduction Path:
==
* Create a new Classification Group
* Click "add" in the right-hand relations panel
* Select 2 key definitions simultaineously using _ctrl_ key
* Click "Apply"

Results
==
* Exception window is presented with the error reproduced below
* Only the first Key is added to the Group

>Date: 2016-01-26T11:40:23.848Z
>Status: 500 | Internal Server Error
>URL: /admin/classificationstore/relations
>Params:
>Fatal error:  Uncaught exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'keyId' cannot be null' in [PROJECT NAME OMITTED]/htdocs/pimcore/lib/Zend/Db/Statement/Mysqli.php:214

**Comment by weisswurstkanone** [comment]
fixed in build 3624
