### ISSUE TITLE
[Improvement] collect bricks in folders for visibility

### ISSUE THREAD

**Issue by Sonja-Schubert** [pimcore/pimcore#4124]
Hi all,

it would be great if it would be possible to collect area bricks in folders because our list of bricks is longer than our screen now. Or is there already such possibility?

Further, It would be helpful if area bricks could be limited for normal users as some of them are technical stuff and not for the marketing manager..

Kind regards,
Sonja

**Comment by fashxp** [comment]
group option
``` 
    "group" => [
        "First Group" => ["iframe", "spacer"],
        "Second Group" => ["rssreader"]
    ],
```
see also https://pimcore.com/docs/5.x/Development_Documentation/Documents/Editables/Areablock/index.html#page_Integrate-an-Areablock-in-a-Template
