### ISSUE TITLE
Custom reports

### ISSUE THREAD

**Issue by cleggypdc** [pimcore/pimcore#413]
Just tried the latest build, it looks like custom SQL reports are broken.

Custom report configurations are being loaded into the Adaptor as an associative array rather than the expected object. This happens on both legacy and new reports

**Comment by cleggypdc** [comment]
Specifically this function https://github.com/pimcore/pimcore/blob/master/pimcore/models/Tool/CustomReport/Adapter/Sql.php#L90 :-)

**Comment by brusch** [comment]
see #416
