### ISSUE TITLE
[XLIFF] adding Dataobjects from root path

### ISSUE THREAD

**Issue by plexmaniax** [pimcore/pimcore#4130]
The export should work from the DataObjects rootpath / 
The export should ignore folders

At the moment the export fails with this message
![staging_blessart_ch____Pimcore](https://user-images.githubusercontent.com/18365319/54994002-892aa080-4fc3-11e9-8397-978871078a7d.png)

**Comment by markus-moser** [comment]
see #4064 - is this patch contained in your pimcore version?
