### ISSUE TITLE
[DataObjects] Markup in Grids in Select Fields is not working anymore

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#4133]
![image](https://user-images.githubusercontent.com/8792145/55013158-dec57400-4fe8-11e9-9477-84b016713d72.png)

**Comment by brusch** [comment]
Regression of #3936 ( 0bf1b9643d33a5dcd45c3f89135a1965fd55cce9 )

**Comment by fashxp** [comment]
still not a satisfying solution, see e.g. fields wfstate and colors in demo-advanced' product objects
