### ISSUE TITLE
[DataObjects] Handle ValidationException in Admin\DataObjectController

### ISSUE THREAD

**Issue by smoench** [pimcore/pimcore#4134]
# Feature Request
We would like to have some custom validations on data-objects and display those violations before publishing them. In a workflow-context it is possible to throw a validation exception which will be handled by the [controller](https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Controller/Admin/WorkflowController.php#L123).

Would it be possible adapt this behaviour? This would be a huge step adding custom validation plus get rid of non-translatable string like this https://github.com/pimcore/pimcore/blob/master/models/DataObject/Concrete.php#L186

**Comment by fashxp** [comment]
Here would be a possibility to add validations on client side: https://pimcore.com/docs/5.x/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/Plugin_Backend_UI.html#page_Validate-Pimcore-Object-s-Data-in-frontend-before-saving
