### ISSUE TITLE
getItems() within LocalizedField.php throw Exception

### ISSUE THREAD

**Issue by ITspirit** [pimcore/pimcore#4135]
With Pimcore 5.7.0 you removed method Pimcore\Model\DataObject\getItems()

Well, but now it's broken within Pimcore\Model\DataObject\ClassDefinition\Data\Localizedfield
in function "marshal" which still calls "->getItems()".

Seems currently wrong too in marhsal-Function within "ImageGallery"

### Actual behavior
Throws an Exception "undefind method".

```php
    public function marshal($value, $object = null, $params = [])
    {
        if ($value instanceof DataObject\Localizedfield) {
            $items = $value->getItems();
            if (is_array($items)) {
```

**Comment by weisswurstkanone** [comment]
many thanks! Fixed it for localized fields, but don't quite see the point regarding the image gallery.

**Comment by ITspirit** [comment]
Thanks a lot - works like a charm. Have upgraded to dev-master (till final release 5.7.2) ;-)

You are right, ImageGallery is unaffected. All fine!
