### ISSUE TITLE
Application_log table engine to InnoDB

### ISSUE THREAD

**Issue by RuudvdvNB** [pimcore/pimcore#4145]
# Feature Request
Change the application_log database table to InnoDB engine.

## Feature description
When working with a database cluster MyISAM tables are not synced between servers. In this case the application_log differs on every server. 

Is is possible to change this table's engine to InnoDB?

**Comment by brusch** [comment]
Using `MyISAM` is intentional for performance reasons (to keep the InnoDB memory footprint as small as possible). 
But you can change it manually to InnoDB at any time, this shouldn't have any side-effects.
