### ISSUE TITLE
[Object grid] Feature request: make it possible to edit localized fields in grid with operator locale switcher.

### ISSUE THREAD

**Issue by jacobsyentl** [pimcore/pimcore#4147]
## Feature description
It would be nice that localized fields can be edited in the gridview if an operator locale switcher is applied. Currently this is not possible.

## Screenshots
Grid config:
![Screenshot 2019-03-28 at 13 58 41](https://user-images.githubusercontent.com/9139261/55159591-b1500600-5161-11e9-81b4-ac9ee8f484e4.png)

Grid overview:
![Screenshot 2019-03-28 at 13 58 34](https://user-images.githubusercontent.com/9139261/55159600-bad96e00-5161-11e9-8805-fd4a239c862f.png)

Current errormessage:
![Screenshot 2019-03-28 at 13 59 01](https://user-images.githubusercontent.com/9139261/55159614-c4fb6c80-5161-11e9-9375-628cc7cace6f.png)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Comment by betterapp** [comment]
@fashxp Hi, Why this is not planned. It is very useful feature.

**Comment by fashxp** [comment]
I agree it is a useful feature. But right now we don't have resources for that and up to now nobody was ready to contribute. 
If you are ready to provide a PR, just let us know - we would be ready to merge a (properly made) PR :-)
