### ISSUE TITLE
[Bug] HTML header charset isn't inserted (by default or forcing it)

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4148]
Hello,

It seems that by default html header charset utf-8 tag is added automatically, but it isn't.
Trying using  `$this->headMeta()->setCharset('UTF-8');` don't add the tag `<meta charset="UTF-8" />` (it add nothing). 

On the header template we have well added  `<?=$this->headMeta();?>`.
Other metahelpers works great and are inserted, only this one isn't inserted.

Thanks.

**Comment by brusch** [comment]
@Yivan  Thanks for reporting! Would it be possible to make a PR for that - that would speed things up 😉 Thanks in advance!

**Comment by Yivan** [comment]
Hi @brusch I just tried to take some times to dig in the code, but i cannot get it to correct this sorry. Pimcore helper seems to extend Symfony template helper which has the setCharset method.
By the way, I saw setCharset method is not documented (https://pimcore.com/docs/5.x/Development_Documentation/MVC/Template/Templating_Helpers/HeadMeta.html).

To reproduce it easily, you can just add in a template:

```
<?php $this->headMeta()->appendName('description', 'My SEO description for my awesome page'); ?>
<?php $this->headMeta()->setCharset('UTF-8'); ?>
<?=$this->headMeta();?>
```

Meta description will be displayed in the source code of the generated page, but not the meta charset.

**Comment by dpfaffenbauer** [comment]
I don't feel this is a bug, you just simply use it wrong. the `setCharset` from the symfony template helper determines the output charset for the helper result. (eg. build a helper to create some sort of HTML, and that charset is defined as output charset). 

What you want is to set the `<meta charset` which, I guess, is simply not supported by the pimcore meta helper, and I don't even think it should. Since UTF-8 is the standard anyway today.

**Comment by Yivan** [comment]
Yes that was my feeling. It inherit from the response helper it seems (`https://symfony.com/doc/current/components/http_foundation.html#response` where we can set with setCharset method).
But this is measleading to have a setCharset method for the Pimcore helper (don't produce any error) and which produce nothing. Maybe it should be overloaded and throw an exception...

**Comment by dpfaffenbauer** [comment]
nope.

it should definitely not! That could cause a lot of other issues. It's just a matter of reading documentation or understanding how Symfony/Pimcore works.

**Comment by brusch** [comment]
I'll close this here for now, but feel free to continue the discussion 😊

**Comment by Zamralik** [comment]
@dpfaffenbauer 
Even if UTF-8 is the standard, it doesn't mean that the end customers have updated browsers with a charset fallback configured on UTF-8.
And there is no generic method headMeta allowing to do:
`$this->headMeta()->headMeta(['charset' => 'UTF-8']);`
