### ISSUE TITLE
Logging configuration bugs

### ISSUE THREAD

**Issue by rwos** [pimcore/pimcore#4156]
# Bug Report

### Expected behavior
1. running pimcore with the environment variable `PIMCORE_PHP_ERROR_LOG=/dev/stderr` sets the PHP `error_log` to `/dev/stderr`
2. running pimcore with the environment variable `PIMCORE_PHP_ERROR_REPORTING=-1` sets the PHP `error_reporting` to `-1`

(both described here: https://pimcore.com/docs/5.x/Development_Documentation/Development_Tools_and_Details/Logging.html)

### Actual behavior
1. it checks if `/dev` is writable (of course not), and then doesn't set `error_log`
2. there's an `is_integer` check that will never return true for an environment variable (always a string), and it leaves `error_reporting` at the pimcore default

### Steps to reproduce
I'm using [this](https://github.com/dockerwest/compose-pimcore/blob/master/docker-compose.yml) docker-compose setup, and added above vars to the pimcore container, but any setup should display this behaviour.

**Comment by brusch** [comment]
@rwos Thanks for reporting! Would it be possible for you to provide a PR? Thanks in advance!

**Comment by brusch** [comment]
Fixed by #4173 resp. 77c3827d91eaa228c8ffc6370313a39721efaeb9
