### ISSUE TITLE
[DataObjects] inline upload of assets in datatype gallery does not consider upload-path setting

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#4158]
always uploaded in _default_upload-bucket

**Comment by ssiergl** [comment]
Hey,

well this is simply due of missing uploadPath set in `getDefaultFieldConfig`

This said....we are limitting in our bundles as well the gallery search/assign to the given upload path, due that user are expecting to search only in the path they are uploading to.

What do you think? If it is ok for you I can push the fix and the improvement

**Comment by fashxp** [comment]
Hi,
hmm ... I think both use cases make sense: just search in upload folder, but also search in whole system and if not found upload to upload folder, whereas the latter one is I think the more common one. 

Therefore I'm skeptical concerning the improvement. What do the others think? @brusch 


Bugfix would be very much appreciated 😄

**Comment by ssiergl** [comment]
Yeah will push the fix.

Regarding the search...what about to make it optional (last option)......

![image](https://user-images.githubusercontent.com/38670469/55323706-21230100-5480-11e9-8f6e-9d680cbbdce7.png)

We have implemented it optional.

**Comment by brusch** [comment]
@ssiergl I'd rather go for an extra setting for restricting the path and do not bind it to the upload path. Reason: you might want to restrict the selection of items to a higher level than the upload path is, e.g. 

Restriction: `/my/custom/folder`
Upload-Path: `/my/custom/folder/_inline_upload`

But we should focus on fixing the current issue first 😊

**Comment by ssiergl** [comment]
@brusch yeah let's focus on the bug. Just pushed the fix for it.

We can discuss the search restriction in an own issue :)

**Comment by cancan101** [comment]
> @brusch yeah let's focus on the bug. Just pushed the fix for it.
> 
> We can discuss the search restriction in an own issue :)

Did a ticket ever get created for the search restriction?

**Comment by brusch** [comment]
Nope, don't think so 😊
