### ISSUE TITLE
Article release storage type xss

### ISSUE THREAD

**Issue by Virtual-1** [pimcore/pimcore#4174]
# Bug Report

### Steps to reproduce

The xss code was not filtered, resulting in a storage type xss.
`<iframe src="javascript:alert('xss')"></iframe>`

![image](https://user-images.githubusercontent.com/45929615/55527190-85d19c00-56ca-11e9-9965-e03fa8f2f920.png)

The xss code is fired when the article is viewed.

![image](https://user-images.githubusercontent.com/45929615/55527252-cd582800-56ca-11e9-83ac-d347c98ef914.png)

### Code example
```javascript
// your code
<iframe src="javascript:alert('xss')"></iframe>
```

# Feature Request

**Comment by brusch** [comment]
Well yes ... that's the intention of a HTML markup field ...

**Comment by Virtual-1** [comment]
This is a global problem. When the user input is displayed on the back end, an attack will be triggered to steal the cookie of the administrator.
 
 
------------------ Original ------------------

**Comment by brusch** [comment]
Users with appropriate rights are allowed to put scripts into a markup field, same for the Tag Manager. 
If you don't trust your backend admin users you shouldn't give them the right to edit content.

**Comment by Virtual-1** [comment]
Understand, I said some ordinary user input can directly attack the background. Look at the other two questions
 
------------------ Original ------------------
