### ISSUE TITLE
Ordinary user profile information can get background permissions from xss

### ISSUE THREAD

**Issue by Virtual-1** [pimcore/pimcore#4176]
# Bug Report

### Steps to reproduce

Log in with a Google account, enter the xss code after the user name, and encounter xss attacks when purchasing items and managing user profiles in the background.

![image](https://user-images.githubusercontent.com/45929615/55532358-28e0e080-56e0-11e9-97db-f07f67e3898c.png)

Here I successfully triggered the xss attack while viewing the profile.

![image](https://user-images.githubusercontent.com/45929615/55532324-fdf68c80-56df-11e9-82eb-271993014385.png)

When performing user management in the background, viewing user details can also trigger xss attacks. Hackers can use this vulnerability to obtain system background permissions, and the background can edit any file to get system permissions.

![image](https://user-images.githubusercontent.com/45929615/55532281-d6072900-56df-11e9-9e3f-416b781ebcad.png)

### Code example

```javascript
<IFRAME src=javascript:alert('XSS1')></IFRAME>
```

# Feature Request

**Comment by brusch** [comment]
This is a different module/bundle -> see https://github.com/pimcore/customer-data-framework
Please also respect our policy for reporting security issues! 
You should read the notes when creating a new issue, before submitting something ;-) 
Thanks anyway.
