### ISSUE TITLE
Unable to generate PDF of parent in Print Container in CMS

### ISSUE THREAD

**Issue by amarjeet6694** [pimcore/pimcore#4180]
I tried to generate few PDFs in CMS by creating printpage and print container, but unable to generate PDF for print container i.e for Parent.

Error: **Illegal Argument: fromIndex(4) > toIndex(3**

The issue is reproducible on https://demo-advanced.pimcore.org

![Webtoprint](https://user-images.githubusercontent.com/29056383/55542360-80814b00-56e4-11e9-9c8c-bda8f66db472.png)

**Comment by fashxp** [comment]
this is a pdfreactor problem (and already know by them with their internal ticketnumber 7604). 
if you deactivate Tags while creating pdf it should work.

**Comment by amarjeet6694** [comment]
Okay thankx @fashxp
