### ISSUE TITLE
Allow restricting Link editable fields

### ISSUE THREAD

**Issue by julmot** [pimcore/pimcore#4184]
# Feature Request

## Feature description

It seems that there's no way to restrict fields of the Link editable:

```twig
{%- set button = pimcore_link('button-' ~ column) -%}
```

I'm only reading out the link title and href with the provided `.getText()` and `.getHref()` methods, nothing else. I don't need "Properties" or "Advanced":

![000060](https://user-images.githubusercontent.com/8310677/55568030-2b066780-56ff-11e9-883b-64e2db10b21c.png)

Users may be confused because they can still enter it, even though it's not used in the frontend. For me, even the implemented `noText` config option didn't have an impact on the editing itself – I could still see the "Text" field.

**Comment by akno77** [comment]
I have the same request and `noText` doesn't work for me either.

**Comment by jdreesen** [comment]
Would love to be able to disable these fields in `Link` fields of data objects, too. The popup looks the same for them.
