### ISSUE TITLE
Visible fields in ManyToMany and AdvancedManyToMany fields are not showing default language value configured in system settings

### ISSUE THREAD

**Issue by psuhane** [pimcore/pimcore#4186]
# Bug Report
Visible fields in ManyToMany and AdvancedManyToMany fields are not picking default language(from system setting) in case of localized fields. Please refer following screen

![screenshot-demo-basic local-2019 04 05-14-35-19](https://user-images.githubusercontent.com/12061880/55616913-893f5300-57b0-11e9-933b-5ddaf3b259e9.png)

See the value in german, this should be displayed in visible fileds
![screenshot-demo-basic local-2019 04 05-14-37-11](https://user-images.githubusercontent.com/12061880/55616914-893f5300-57b0-11e9-92ee-acdc4e5553a3.png)

But in relation field en language value is coming
![screenshot-demo-basic local-2019 04 05-14-38-05](https://user-images.githubusercontent.com/12061880/55616916-8a708000-57b0-11e9-8aec-110fd2956638.png)

Please let me know if any clarity required in this issue.

**Comment by brusch** [comment]
@psuhane Pimcore tries to use the editors language setting for the admin interface, only if there's no match, the default language is used.

**Comment by psuhane** [comment]
But this is also not working. 

The default language configured in system settings is Norwegian and this language is not available to select in editors language setting for the admin interface. In this case Norwegian language should be displayed but it is always picking en language.

**Comment by BlackbitNeueMedien** [comment]
I can confirm that this is a bug currently. In our customer's case we have an advanced many to many object relation in a localized field:
<img width="1646" alt="Bildschirmfoto 2020-12-11 um 13 58 01" src="https://user-images.githubusercontent.com/8749138/101906291-04c5ea00-3bb9-11eb-9c39-3c6ec1413f0a.png">

The current user has these editor settings:
<img width="621" alt="Bildschirmfoto 2020-12-11 um 14 03 12" src="https://user-images.githubusercontent.com/8749138/101906882-faf0b680-3bb9-11eb-9902-a0488a6efe99.png">

The Pimcore backend language for this user is German.

The localized relation looks like this:
<img width="1635" alt="Bildschirmfoto 2020-12-11 um 14 06 40" src="https://user-images.githubusercontent.com/8749138/101906975-1c51a280-3bba-11eb-8710-ba6a3140246b.png">

The column fname comes from the related object - and it uses the french name for whatever reason although the german name is filled:
<img width="676" alt="Bildschirmfoto 2020-12-11 um 14 09 14" src="https://user-images.githubusercontent.com/8749138/101907172-77839500-3bba-11eb-9582-81b77242a326.png">

**Comment by BlackbitNeueMedien** [comment]
In my case the problem the reason was that user's language was `de` but this is not a valid language in this system. Only `de_DE` is. This problem is solved in #7752

**Comment by twin-elements** [comment]
Has anyone managed to solve this problem?

The system language is **PL** and the default frontend language is also **PL**
![image](https://github.com/pimcore/pimcore/assets/17727266/12269ba0-b45e-419d-a106-216c5d53091e)

User language is also PL
![image](https://github.com/pimcore/pimcore/assets/17727266/1cbf3381-ea78-48e1-9296-8b64f62371dd)

For the text editor, **PL** is set as the first language
![image](https://github.com/pimcore/pimcore/assets/17727266/f3dcd0f0-0f42-448b-bd92-f5ecd7f74130)

However, the **EN** language is always chosen in the relationship. And where there is no English version, the field is left blank

![image](https://github.com/pimcore/pimcore/assets/17727266/561e7435-3c5b-445b-beab-ef647814dc7f)
