### ISSUE TITLE
Calculated value - cannot save object with enabled inheritance

### ISSUE THREAD

**Issue by chix** [pimcore/pimcore#420]
Hi,

this one is a bit complicate to reproduce. You need a class with enabled inheritance and with a calculated value field which has to have a value. [Here you can download an example class definition and value calculator implementation](https://mega.nz/#!dVkzTAzK!JsREJ5l4X6BJbVWdlbHFiqb3nZAjb-oIqDj2CFQ4qcY) (I am not able to upload a zip archive in this issue). You should get this error `~SQLSTATE[42S22]: Column not found: 1054 Unknown column 'url' in 'field list', query was: SELECT ooo_id AS id, `url` FROM object_localized_data_1 WHERE ooo_id = ?~`

I think that the problem is on this line https://github.com/pimcore/pimcore/blob/master/pimcore/models/Object/Localizedfield/Dao.php#L201 which flags the calculated value as changed and then, the inheritance helper tries to select it in the DB, which fails, because calculated value is not saved in the DB? So maybe a check like this 
`if ($fd->getFieldType() == 'calculatedValue') { continue; }` should help?

Martin

**Comment by weisswurstkanone** [comment]
Hi,
the ZIP file does not contain anything localized-field related. Are you sure it is the right one?

Josef

**Comment by weisswurstkanone** [comment]
A check like suggested makes definitely sense. Fixed in build 3627

**Comment by chix** [comment]
Hi,
thank you for the fix. The problem exists also on non-localized fields, so the check should also probably go in here https://github.com/pimcore/pimcore/blob/master/pimcore/models/Object/Concrete/Dao.php#L239

Martin

**Comment by weisswurstkanone** [comment]
Wait, I believe this was the wrong place anyway.
Shouldn't it rather go into 
LocalizedField/Dao.php line 169 and
Concrete/Dao.php line 265
as it should only be ignored for the inherited code part?

**Comment by chix** [comment]
yes you are right, the problem happens only with inheritance enabled, so it would be better to check also for enabled inheritance

**Comment by weisswurstkanone** [comment]
Done
