### ISSUE TITLE
DeepCopy 1.9.0 not working with Pimcore

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#4203]
Withing a `composer update` process, deep-copy gets updated to "`1.9.0`":

https://github.com/pimcore/pimcore/blob/9bdb03c8c8cdbf002661be2df54c60112e8d808a/composer.json#L68

After this update, no document / object can be copied anymore:

```json
Fatal error:  Declaration of class@anonymous::matches($object, $property) must be compatible with DeepCopy\Matcher\Matcher::matches(object $object, ReflectionProperty $reflectionProperty): bool in /var/www/public/vendor/pimcore/pimcore/models/Element/Service.php on line 1054
{"success":false,"message":"Compile Error: Declaration of class@anonymous::matches($object, $property) must be compatible with DeepCopy\\Matcher\\Matcher::matches(object $object, ReflectionProperty $reflectionProperty): bool","trace":[],"traceString":"#0 {main}"}
```

**Comment by NiklasBr** [comment]
👍 on the Pull Request, anyone who wants to temporarily solve this issue can run the following command:

`composer require myclabs/deep-copy ~1.8.0`

and it will update your own composer file and downgrade to 1.8.1. Don't forget to remove it later when the above PR is merged.
