### ISSUE TITLE
Reload tree after deleting elements

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#4214]
# Bug Report

### Expected behavior
After an element gets deleted via context menu the tree should get refreshed

### Actual behavior
Tree is not refreshed after deleting elements which can cause an empty tree page in the extreme case of deleting all elements in the current tree page via multiselect.

### Steps to reproduce
1. Create 26 objects so tree gets paginated
1. delete one object on page 1
1. delete all objects in page 1 via multiselect -> right-click -> Delete

An optimal solution would reload all parent elements of deleted elements.

**Comment by brusch** [comment]
Maybe it is also sufficient if we do a full reload of the parent node only when the amount of children == 0 after the deletion.

**Comment by BlackbitNeueMedien** [comment]
@brusch, I do not think that this would be enough because when you initially have 26 items and delete one then there won't be page 2. So the tree pagination is not guaranteed to work if we do not refresh the tree after deletion - regardless on the number of remaining child items.

**Comment by brusch** [comment]
Ok, let's try to refresh every time first, I don't think that should have any negative side-effects.

**Comment by NiklasBr** [comment]
I have a problem related to this reload: Any time I delete an item in the tree it reloads and kicks me back to the first pagination. This is a little irritating because I do not always pay full attention to exactly which page I was on and have to flip through them all again. Can we fix it?

**Comment by brusch** [comment]
The question is how ... 🤔

**Comment by NiklasBr** [comment]
Idea: Take the element with index-1 of the deleted element (sibling above) and when the deletion is completed go to the page with the sibling visible?
