### ISSUE TITLE
[Objects] Select data-type: automatically set display value to value

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#4215]
A lot of our customers forget to set values for select field options. They only fill the "display name", then they edit these select fields in the data objects and wonder why their selection does not get saved.

What do you think of using the "display value" as "value" if no value got entered for an option?
Or: Do not allow to save the class / brick / field collection if there is an option without a value.

**Comment by brusch** [comment]
I don't think it is a good idea to magically use the display value as the value, I'd rather go for a validation here - either on save or just by giving real time feedback, which is probably a bit easier to implement. 

Can you create a PR for that? 😊
