### ISSUE TITLE
Confusing methods in Pimcore

### ISSUE THREAD

**Issue by Zamralik** [pimcore/pimcore#4216]
Object, Asset, and Document have two identical methods: getFullPath, and getRealFullPath.
Because Page::getFullPath() behavior is modified to return the path relative to the site document and not the absolute path.
Different behaviors are confusing and can cause bugs.

Recommendations:
Rename getFullPath() to getSitePath() for Page class.
Remove getRealFullPath().

Object and Document have methods setKey and getKey.
Asset equivalent methods are setFilename and getFilename.
This cause confusion and extra work for implementation of generic elements processing.

Recommendations:
Rename setFilename() to setKey().
Rename getFilename() to getKey().

**Comment by brusch** [comment]
This is not only used for sites, but also for pretty urls and some other things, that's why we've choosen such a generic name.
