### ISSUE TITLE
Unique key constraint not considered when restoring from recycling bin

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#4219]
# Bug Report

When an object is restored from the recyclin bin the unique key contraint is not considered.

## Steps to reproduce:

1. Create a class with an unique key field
2. Create an object of the created class an set a value to the unique field
3. Delete the object
4. Create another object with the same value for the unique field
5. Restore the deleted object from the recyling bin
6. Now you have 2 object with the same value for the field which should actually be unique, you can even save the objects without any error. If you now save the class definiton again, the value of the second created object will be cleared.

**Comment by dpfaffenbauer** [comment]
sure? that is a database index and that should never allow an insert for a unique key if it already exists

**Comment by andreas-gruenwald** [comment]
I was able to reproduce it as well on the ecommerce demo system.
