### ISSUE TITLE
PDF drag and drop results in Sorry something went wrong (BITNAMI pimcore 3.1.1)

### ISSUE THREAD

**Issue by withindale** [pimcore/pimcore#423]
When using the demo site, dragging a pdf from assets onto PDF field in a content page does not work. While dragging there is a green tick but the drop fails.

**Comment by brusch** [comment]
We have no access to the bitnami package. Please ask bitnami for a fix - thanks! 
It seems that bitnami doesn't include Ghostscrip, or isn't able to utilize it correctly.

**Comment by withindale** [comment]
Thanks I will pass that on to BITNAMI.

Ian Russell
