### ISSUE TITLE
[Objects] Many-to-many Object Relation: Column `Reference` stays empty on assignment

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#4237]
- many-to-many object relation with no visible fields specified
- drag & drop a relation onto the field
- **Reference** column stays empty 

Reproducible on demo-basic.pimcore.org 

![image](https://user-images.githubusercontent.com/142037/56122309-695b1c80-5f72-11e9-9290-b68fac9ba346.png)

**Comment by weisswurstkanone** [comment]
probably related to 
https://github.com/pimcore/pimcore/commit/62204339d7c582612596e877b52f29fe834790ac
