### ISSUE TITLE
[Documents] When documents have children, the attribute fullpath is not available

### ISSUE THREAD

**Issue by roland4432** [pimcore/pimcore#4250]
When iterating the pages of a document and the pages have children, the attribute **fullPath** is not available on the document.  
Only **_uri** or **realFullPath** are viable options.  
This is breaking pages when marking the parent as site and iterating through children to build a navigation

```
{% set mainNavStartNode = pimcore_document(1) %}
{% set mainNav = pimcore_build_nav(document, mainNavStartNode) %}

{% for page in mainNav.pages %}
  {% set hasChildren = page._pages|length > 0 %}
  <div>{{page.fullPath }}</div> #ok if hasChildren is false, breaking, when hasChildren is true
  {% if hasChildren %}
    {% for childpage in page._pages %}
      <div> {{ childpage._uri }}</div>
     {% endfor %}
  {% endif %}
{% endfor %}
```

Behavior is a little odd, since the documentation is telling to use fullPath: https://pimcore.com/docs/5.x/Development_Documentation/MVC/Routing_and_URLs/Working_with_Sites.html
(mentioned in the lower sections)

**Comment by brusch** [comment]
Why not using `_uri` ?

**Comment by roland4432** [comment]
Since it's not mentioned in the docs, it's a thing you have to dig for first,
second its a _-prefixed variable, "inofficially" marked for non-public access
and last, it's not persistent, you can use a member variable only under certain circumstances

;)

**Comment by brusch** [comment]
The `getFullPath()` method is only available on the document object, not on the `Page\Uri` object used by the navigation. But I guess it shouldn't be a problem to rename `_uri` to `uri` and make it `public` accessible. 
PRs are welcome 😊

**Comment by roland4432** [comment]
I am pretty much fine with what ever, but imho it should correspond with the doc

@brusch anything preferred?
