### ISSUE TITLE
Fetal Error : Call to a member function setABC() on null in Pimcore5 

### ISSUE THREAD

**Issue by eramit11** [pimcore/pimcore#4253]
# Bug Report

### Steps to reproduce
      When set any value for product object like
         
### Code example
```php
// your code
  $exitProductObj = new \Pimcore\Model\DataObject\Product\Listing();
            $exitProductObj->setEAN('7894ABC');
           $exitProductObj->save();


# Feature Request
<!--
## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [ ] There is no existing issue regarding the same topic
-->
## Feature description

**Comment by eramit11** [comment]
i have update composer, permission, clear cache also run rebuild class. but getting same error when set value for any field in product.

**Comment by fashxp** [comment]
you can't set values to listings as listings are a list of objects... please see https://pimcore.com/docs/5.x/Development_Documentation/Objects/Working_with_PHP_API.html for details or use our forums to get support. 
thanks.

**Comment by eramit11** [comment]
i have provide code step wise 
$exitProductObj = $this->find('Product','ProductId',$data['productid']);
 $exitProductObj->setEAN('88C');
  $exitProductObj->save();

### Find class
public function find($className, $field, $value) {
        $class = "Pimcore\\Model\\DataObject\\" . $className . "\\Listing";
        $list = new $class();
        $list->setCondition( $field . '= ?', $value);
        $list->setlimit('1');

        foreach ($list as $item) {
           // p_r($item);exit;
            return $item;
        }
    }

### FATAL ERROR
 Call to a member function getEAN() on null
