### ISSUE TITLE
Send Mail directly from a Report im Pimcore

### ISSUE THREAD

**Issue by TimWeyr** [pimcore/pimcore#4254]
# Feature Request

## Feature description
i'd like to be able to send a specific mail-object to a selected or all rows in a Report filled with Data from the Report

**Comment by brusch** [comment]
Sounds like a very specific use-case -> closed. 
But feel free to further explain your use-case, maybe I got something wrong :) 
Thanks!

**Comment by TimWeyr** [comment]
Hi, thanks for the acknowledgement. 
I thougth of it like a series letter (mailmerge) in microsoft word. 
If it would would send automatically it could also be used to send alerts (for example to the admin about critical conditions)

**Comment by TimWeyr** [comment]
Hi, @brusch i cant see if i can reopen this issue and i cant see if you read my update. Greetings Tim

**Comment by brusch** [comment]
Hey @TimWeyr 
In general that sounds like a great idea, maybe that's a topic for an additional bundle?
