### ISSUE TITLE
Port not passed when clicking preview link to open in new window

### ISSUE THREAD

**Issue by roland4432** [pimcore/pimcore#4256]
When running on, for example, localhost:8000, then
- rightclick on any document and click "Open in new window" => localhost:8000/my-url
- leftclick the document and select "Open in new window" from the top toolbar => localhost/my-url

**Comment by brusch** [comment]
Can you please provide a PR for that? 
Thanks in advance!  😊

**Comment by roland4432** [comment]
There you go sir:
https://github.com/pimcore/pimcore/pull/4264

**Comment by brusch** [comment]
Fixed  by #4264
