### ISSUE TITLE
Cannot redeclare class Object_Data_QuantityValue

### ISSUE THREAD

**Issue by chix** [pimcore/pimcore#426]
Hi,

I in my wamp environment (lamp is ok) I get this error with objects containing a QuantityValue field:

`Fatal error: Cannot redeclare class Object_Data_QuantityValue in C:\wamp\www\npu\pimcore\models\Object\Data\QuantityValue.php on line 15`

I don't know where it was declared in the first place, but when I changed the class name in https://github.com/pimcore/pimcore/blob/master/pimcore/models/Object/Data/QuantityValue.php#L15 and added the namespace the problem seemed to be fixed.

So, is there a reason why Object_Data_QuantityValue still uses the old zend-like class name or can we update it?

Martin

**Comment by brusch** [comment]
Thanks!

**Comment by brusch** [comment]
fixed in build 3637
