### ISSUE TITLE
[Bug] Headlink method doesn't exist

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4260]
Hello,

Following the documentation and using the headlink method, we get an error message saying this method doesn't exists:

`$this->headLink()->headLink(['rel' => 'icon', 'href' => '/img/favicon.ico'], 'PREPEND')`

To reproduce it, on the Pimcore demo, in the layout.html.php, just change:

`<?= $this->headLink(); ?>`

by

```
<?php $this->headLink()->headLink(['rel' => 'icon', 'href' => '/img/favicon.ico'], 'PREPEND') ?>
<?= $this->headLink(); ?>
```

And you get the following exception:
`Method "headLink" does not exist`

Thanks.

**Comment by brusch** [comment]
Can't find `$this->headLink()->headLink()` in the docs, where have you seen this? 
Thanks!

**Comment by brusch** [comment]
Correct syntax would be `$this->headLink()->prepend(['rel' => 'icon', 'href' => '/img/favicon.ico']);` for your example.

**Comment by brusch** [comment]
Closed for now, unable to find any occurrence of `headLink()->headLink` in the repository.

**Comment by Yivan** [comment]
Thanks @brusch 
I have seen it here: https://pimcore.com/docs/5.x/Development_Documentation/MVC/Template/Templating_Helpers/HeadLink.html#page_Basic-Usage

```
$this->headLink()->appendStylesheet('/styles/basic.css')
                 ->headLink(['rel' => 'icon', 'href' => '/img/favicon.ico'], 'PREPEND')
                 ->prependStylesheet('/styles/moz.css', 'screen', true,  ['id' => 'my_stylesheet']);
```

I was thinking `appendStylesheet` return `headLink` object and not `this`.

Maybe this exemple should be formatted like this:

```
$this->headLink(['rel' => 'icon', 'href' => '/img/favicon.ico'], 'PREPEND');
$this->headLink()->appendStylesheet('/styles/basic.css')
                           ->prependStylesheet('/styles/moz.css', 'screen', true,  ['id' => 'my_stylesheet']);
```
