### ISSUE TITLE
[Mail Document] Whitespaces in from address prevents system from sending mail.

### ISSUE THREAD

**Issue by mattamon** [pimcore/pimcore#4266]
# Bug Report
### Expected behavior
Removing uneeded whitespaces from, from mail adress, in mail document.
### Actual behavior
Using the from mail address exactly as is, resulting in an exception. 
### Steps to reproduce
Generate a new mail docucment. Fill in from mail address with a blank at the end. Try to send mail. 
### Code example
```php
  $adminMailDocument = $this->getDocumentTag('href', "adminMail")->getElement();
   if ($adminMailDocument instanceof Document\Email) {
           $adminMail = new Mail();
           $adminMailDocument->setFrom(trim($adminMailDocument->getFrom())); // current fix of whitespace problem
           $adminMail->setDocument($adminMailDocument);
           $adminMail->setParams($mailParams);
           $adminMail->setFrom(trim($mailParams["email"]));
           $adminMail->setReplyTo([$mailParams['email'] => $mailParams['firstname'] . ' ' . $mailParams['lastname']]);
           $adminMail->send();
    }
```

**Comment by brusch** [comment]
Well, with a trailing whitespace the email address is not correct and throwing an exception is the right behavior (comes from Swiftmailer anyway), I don't think Pimcore should change the behavior of Swiftmailer.
