### ISSUE TITLE
"Show in tree" not working because of utf8_bin

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#4269]
The collation of objects.o_key got changed to utf8_bin in af037cc821bddabec093ace981874c31791bea12 - this leads to objects being sorted case-sensitive, e.g. object with key "Z" gets listed before "a". As described in #2530 this is problematic for the "show in tree" function as this is not case-sensitive - and it is also counter-intuitive when you look for a certain object.
Currently we have a case where last object key on a data object tree page begins with "KROSS" and we look for "Koga". In utf8_bin "KROSS" < "Koga" (that is why "KROSS" is listed before "Koga", in JS "KROSS" > "KOGA" - and so "show in tree" cannot find the object.

PS: This question has also been asked in https://github.com/pimcore/pimcore/commit/af037cc821bddabec093ace981874c31791bea12#commitcomment-32884333 - but I do not see an answer there why utf8_bin got chosen sacrificing the alphabetical order.

**Comment by brusch** [comment]
Regression of #4086
