### ISSUE TITLE
Custom Reports: settings window has double scroll

### ISSUE THREAD

**Issue by cleggypdc** [pimcore/pimcore#427]
1 in the custom reports tab
1 inside a custom report

![image](https://cloud.githubusercontent.com/assets/1098498/12780059/a3f5d85a-ca63-11e5-8bc9-c1c2705f93c6.png)

**Comment by brusch** [comment]
![image](https://cloud.githubusercontent.com/assets/142037/12813440/50ae9dfa-cb38-11e5-943d-cce2f110ac84.png)

I cannot reproduce this problem :( 
Can you send us a PR? 
Thanks!

**Comment by brusch** [comment]
i think one of the panels need 
scrollable: "y"

**Comment by cleggypdc** [comment]
sure, will add it to my todo list today :smile:

**Comment by brusch** [comment]
see Merge pull request #432 from cleggypdc/bugfix_custom-report-scroll
