### ISSUE TITLE
[Elements] Locked elements should not be deleted from grid

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#4281]
# Bug Report
### Expected behavior
Locked elements should not be deleted from grid
### Actual behavior
It is possible to delete **locked** elements from grid

### example
![image](https://user-images.githubusercontent.com/5137917/56744069-1bb39080-6778-11e9-9746-cb2ad20ace0d.png)

**Comment by mchuatak** [comment]
Hi, how did you disable or remove the Delete Folder Icon  between the "save" and "reload" icon?
