### ISSUE TITLE
[DataObject] add interface for calculated fields

### ISSUE THREAD

**Issue by FredoVelcro-zz** [pimcore/pimcore#4283]
Hello,

Could be nice to add an interface for calculated field as describe here :
https://pimcore.com/docs/5.x/Development_Documentation/Objects/Object_Classes/Data_Types/Calculated_Value_Type.html

For instance : 

```php
interface CalculatedFieldInterface
{
    public static function compute($object, $context);
    public static function getCalculatedValueForEditMode($object, $context);
}
```

**Comment by brusch** [comment]
Absolutely! It should be also possible to define the calculator class as a service using the `@Service\Calculator` syntax, like we do for the path formatter (relational data-types) and the options provider (select data-type). 

Would you provide a PR for that?

**Comment by FredoVelcro** [comment]
PR has been submitted ! 
Was not sure of adding "getCalculatedValueForEditMode()" in the default interface cause it could be optional..

**Comment by fashxp** [comment]
should be fixed with https://github.com/pimcore/pimcore/pull/5027
