### ISSUE TITLE
Admin GUI Receive deleted image after adding new one 

### ISSUE THREAD

**Issue by steel-archer** [pimcore/pimcore#4285]
# Bug Report

Both on existing project and fresh install of pimcore/demo-ecommerce

### Steps to reproduce

1. Create new page in the admin area.
2. Add 2 image blocks and fill them with different images.
3. Save & Publish.

![Selection_020](https://user-images.githubusercontent.com/18716954/56794575-16f1e980-6817-11e9-890e-1345a4a3b802.png)

4. Remove both blocks *without* saving.
5. Try to add new image block.

### Expected behavior
1. Brand new image block without any custom data.

### Actual behavior
1. One of the previously deleted blocks is displayed instead.

### Notes
1. The same is for different blocks types, not only images.

**Comment by brusch** [comment]
This behavior cannot be changed for the moment, this is due to the way how Pimcore stores the data in the background and how the block editables (areablock, block) work. You can use the _clear content_ button instead, which clears the entire document.
