### ISSUE TITLE
Scheduling an object with unfilled mandatory fields should give a warning when saving

### ISSUE THREAD

**Issue by jstsch** [pimcore/pimcore#4294]
# Feature Request

## Feature description

Display a warning when you schedule to publish an object that cannot be published because mandatory fields are incomplete.

## Example use case

I have a blog section. A blog post needs an author, otherwise it renders incorrectly. Currently, I can save the blog post without the author. This is great, so I can save a draft version. However, if I forget to add an author, and schedule the post to go up at a certain time, the publish process will fail at that moment.

It would be great if Pimcore would show a warning beforehand when scheduling to publish an object when it cannot be published.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
