### ISSUE TITLE
[Adapter] Possibility to configure third party Image adapter

### ISSUE THREAD

**Issue by FredoVelcro** [pimcore/pimcore#4299]
Would be great to configure our own Image adapter (we need this in our project to speed up thumbnails generation in fact, same question for PDF, videos etc)
instead of hard coding this like in pimcore\pimcore\lib\Image.php : 

```php

    /**
     * @return null|Adapter\GD|Adapter\Imagick
     *
     * @throws \Exception
     */
    public static function create()
    {
        try {
            if (extension_loaded('imagick')) {
                return new Adapter\Imagick();
            } else {
                return new Adapter\GD();
            }
        } catch (\Exception $e) {
            Logger::crit('Unable to load image extensions: ' . $e->getMessage());
            throw $e;
        }
    }
```

Could be configured via Yaml config, services etc

Is there a way to do this without cloning the repo ?

Thanks,
Best regards.

**Comment by brusch** [comment]
Duplicates #2914 - PRs are welcome :)
