### ISSUE TITLE
Cache won't save after saving/deleting object

### ISSUE THREAD

**Issue by timhonders** [pimcore/pimcore#430]
I don't know if this is a bug or intentional but when an object is saved 
clearDependentCache gets called on line 628 witch calls Cache::clearTags($tags);

when clearTags is run its set a writelock, but never clears the writelock after removing the tags.

So if u try to save somthing like Cache::save('testvalue','testkey']) after an object save nothing happens

**Proposed solution:**

in file /pimcore/lib/Pimcore/Cache.php
after line 678

`
  // clean tags, except output
        if ($cache = self::getInstance()) {
            $cache->clean(
                \Zend_Cache::CLEANING_MODE_MATCHING_ANY_TAG,
                 $tags
            );
        }
`

add:

`
self::removeWriteLock();
`

So u can use Cache::save after an object save

**Comment by brusch** [comment]
That's indeed intentional. The idea is/was that a process that has already invalidated cache items shouldn't write anything back to the cache. This is primary caused by the fact that the pimcore cache needs to be consistent at any time, so we absolutely need to avoid race-conditions or any other unwanted item in the cache.

**Comment by brusch** [comment]
you can use the force option if you'd like to ensure that your item is written directly to the cache: 
https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Cache.php#L335

**Comment by timhonders** [comment]
Ok but when i set $force to true it still not gets saved.

`
if(self::getForceImmediateWrite() || $force) {

  if(self::hasWriteLock()) {
     return;
   }

   return self::storeToCache($data, $key, $tags, $lifetime, $priority, $force);
  } else {
    self::addToSaveStack(array($data, $key, $tags, $lifetime, $priority, $force));
}
    
`
