### ISSUE TITLE
Embed videos via drag and drop in wysiwyg editor

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#4304]
Currently wysiwyg area in documents does only support embedding images via drag and drop. It would be nice if this would also be possible for videos.

We could extend https://github.com/pimcore/pimcore/blob/8f3c8473ca855cb4c25444ebd5bf10d496262b68/bundles/AdminBundle/Resources/public/js/pimcore/document/tags/wysiwyg.js#L193 for videos and call a controller via AJAX which generates the HTML code for the video tag via https://github.com/pimcore/pimcore/blob/8f3c8473ca855cb4c25444ebd5bf10d496262b68/models/Document/Tag/Video.php#L422. 
What do you think? Does this make sense?

**Comment by brusch** [comment]
Hmm, we could generate the HTML also in JS, but since videos are a bit more complex topic than images I don't think this is really a good idea. I'm just thinking of things like: poster images, controls, ...

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
