### ISSUE TITLE
[Workflows] Permissions allow usage of Key Shortcuts

### ISSUE THREAD

**Issue by jansarmir** [pimcore/pimcore#4308]
Setting permissions (modify: false) for state in workflows
- disables buttons in layout (OK)
- Key Shortcuts are still functional, which allows to Unpublish or Save object (SHOULD NOT)

**Comment by fashxp** [comment]
is that solved, or why did you close the issue?

**Comment by kvaka-dev** [comment]
@jansarmir is this issue resolved?
Beacuse I can still save objects with ctrl+s even though I have modify: false set in workflow place.

It's kind of a big deal.

**Comment by kvaka-dev** [comment]
@fashxp can you make some light of this, please?

**Comment by fashxp** [comment]
If issue still persists please create new issue or even better a PR
