### ISSUE TITLE
Undefined method getClassName in class Pimcore\Model\Object\Folder

### ISSUE THREAD

**Issue by zoransalamun** [pimcore/pimcore#431]
Pimcore version: 4.0.0.B3 - 3637

When user try to rename object folder error will be shown:
"~Call to undefined method getClassName in class Pimcore\Model\Object\Folder~"

Class i missing method:
    public function getClassName() { }

**Comment by brusch** [comment]
Renaming object folders works fine for me (see also demo.pimcore.org). 
Can you provide me some more details, like a stacktrace? 

Thanks!

**Comment by zoransalamun** [comment]
If you enable developer mode it will not work, you have that problem on that class but it is not visible... You can check class for that method...

**Comment by brusch** [comment]
Sorry, I cannot reproduce this problem, even with debug and dev-mode off. 
Please provide us a detailed description how to reproduce this problem on https://demo.pimcore.org/admin/ (admin/demo) or a stack trace or anything else that points to the real cause of this problem. 

Thanks!

**Comment by zoransalamun** [comment]
You are right, traced code and it looks like one test plugin called in preUpdate hook method getClassname, and that method doesn't exist for folder object...

Sorry for false response, closing issue.

**Comment by brusch** [comment]
Thanks for your feedback :)
