### ISSUE TITLE
[Improvement] Pagination for relations list in object tab

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4312]
Hello,

In some cases, the list of object affected to a relation field (href, multi-href, etc.) can be pretty long, and the human management of this list become hard, and the GUI is performance impacted when opening such object with many relations affected to a relation field.

![image](https://user-images.githubusercontent.com/9025839/57080703-59be3080-6cf3-11e9-85a2-9918be65d382.png)

Having a pagination system in object relation fields will solve this problem elegantly.

Best regards,
Thomas

**Comment by fashxp** [comment]
paging of many-to-many relation fields would require either major changes to whole data object module or would not have desired effects. 

following two things should have a similar effect: 
- if you define a fixed height for multi-relation fields, rendering performance should not be an issue (as ext only renders visible rows). 
- https://github.com/pimcore/pimcore/pull/4122 should improve loading performance of objects with many relations in general.

**Comment by medovanx** [comment]
@fashxp is there any plan in the future to maybe add pagination to the relations field?

**Comment by fashxp** [comment]
no, currently not.
