### ISSUE TITLE
[Improvement] Search filter for relations list in object tab

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4313]
This issue is linked to this one: https://github.com/pimcore/pimcore/issues/4312

Purpose of this one, is in case of long listing to be able to filter the list of the relationnal objects to find them easily (default colomns and added columns in class definition of the relation field).

![image](https://user-images.githubusercontent.com/9025839/57080845-b6b9e680-6cf3-11e9-8d47-38de7545a105.png)

It is less important than the pagination system, but it can help managing relations.

Best regards.

**Comment by fashxp** [comment]
already implemented with https://github.com/pimcore/pimcore/pull/4194

**Comment by Yivan** [comment]
Great, thanks !
I missed it. Everytime a new Pimcore version is released i try to find the list of changelog, but the only way is to go through all the commits... Do you know how to get this list easily ? (sorry this is a littre outside of this issue). Is it planned ? (i can a open a separate issue if needed)

**Comment by fashxp** [comment]
you can use the milestones at github for that - here e.g the milestone for 5.8.0 https://github.com/pimcore/pimcore/milestone/59?closed=1
