### ISSUE TITLE
File::mkdir() doesn't work properly when open_basedir directive is used

### ISSUE THREAD

**Issue by thgross** [pimcore/pimcore#4315]
# Bug Report

The following function does not work when the webspace is in a directory that is not accessible by php:
https://github.com/pimcore/pimcore/blob/497714f9a9273aa7e39b61a0cff04cf22371e530/lib/File.php#L159-L197

for example: all our webs are in `/srv/www/`:
- `/srv/www/webspace1/`
- `/srv/www/webspace2/`
PHP is NOT allowed to read/write directories above the webspace-directories ("open_basedir restriction").
The above function however tries to `mkdir('/srv')`, which obviously returns `false`, so it fails.

The above function should **not** begin at the topmost directory trying to create it, but at `PIMCORE_TEMPORARY_DIRECTORY`instead.

**This is urgent, since 2 of our pimcore webs are broken by this.** 

### Expected behavior
pimcore is able to create the thumbnail directories and also the thumbnails.

### Actual behavior
pimcore is not able to create the thumbnail-directories nor the thumbnails themself.

**Comment by brusch** [comment]
@thgross please check if the patch https://github.com/pimcore/pimcore/commit/c4ef5784d52241e310a305637238ff5220a28034.patch fixes your problem. Thanks for your feedback.

**Comment by thgross** [comment]
> 
> 
> @thgross please check if the patch https://github.com/pimcore/pimcore/commit/c4ef5784d52241e310a305637238ff5220a28034.patch fixes your problem. Thanks for your feedback.

I can confirm that this patch fixes the problem for me!

Thank you!

**Comment by dpfaffenbauer** [comment]
It just occurred for me as well and your patch fixes the issue 👍
