### ISSUE TITLE
maintenance command deprecation

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#4316]
In Pimcore 5.8 the `./bin/console maintenance` command is no longer available. 
There should either be 

- a documentation that it is now no longer supported and has to be called under the `pimcore:` namespace (https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/Within_V5/index.html#page_Version-5-8-0)

- or the alias should be activated again.

![image](https://user-images.githubusercontent.com/9052094/57092044-cee93000-6d0a-11e9-9fe0-ce904672f5ad.png)

**Comment by dpfaffenbauer** [comment]
1. Note should be enough
