### ISSUE TITLE
[Migrations] Version20190408084129 results in errors

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4321]
In the latest migration script:
https://github.com/pimcore/pimcore/blob/master/bundles/CoreBundle/Resources/migrations/Version20190408084129.php

The SQL request :

ALTER TABLE `quantityvalue_units`
            CHANGE `id` `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
            CHANGE `baseunit` `baseunit` INT(11) UNSIGNED DEFAULT NULL,
            ADD `converter` VARCHAR(255) DEFAULT NULL,
            ADD CONSTRAINT `fk_baseunit`
            FOREIGN KEY (`baseunit`)
            REFERENCES `quantityvalue_units` (`id`)
            ON DELETE SET NULL
            ON UPDATE CASCADE;

Returns:
errno: 150 "Foreign key constraint is incorrectly formed"

SQL is in strict mode.

Table:

![image](https://user-images.githubusercontent.com/9025839/57148102-32399780-6dc9-11e9-8ce9-e5856cd3b0b8.png)

![image](https://user-images.githubusercontent.com/9025839/57148135-4a111b80-6dc9-11e9-976e-8184c313dbfc.png)

For now we are stuck in this last step.
We where migration from a Pimcore 4, all went ok except this latest migration.

By the way, thanks for the excellent work you made on migration from Pimcore 4 by providing procedures and custom scripts, very effective.

**Comment by brusch** [comment]
Fixed by 0c0d82d18ac9516047917635f1825ab6362dd7d3, just update to the latest version and run the migration again (if not already done automatically by the update).

**Comment by Yivan** [comment]
@brusch thanks for looking into it.

I ran composer update, but error is always here:

```
Migration 20190408084129 failed during Execution. Error An exception occurred while executing 'ALTER TABLE `quantityvalue_units`
            CHANGE `id` `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
            CHANGE `baseunit` `baseunit` INT(11) UNSIGNED DEFAULT NULL,
            ADD `converter` VARCHAR(255) DEFAULT NULL,
            ADD CONSTRAINT `fk_baseunit`
            FOREIGN KEY (`baseunit`)
            REFERENCES `quantityvalue_units` (`id`)
            ON DELETE SET NULL
            ON UPDATE CASCADE':

SQLSTATE[HY000]: General error: 1005 Can't create table `int_hubokee`.`#sql-8_26b` (errno: 150 "Foreign key constraint is incorrectly formed")
```

**Comment by BenjaminEden** [comment]
You first have to change the id- and baseunit-columns and then add the constraint. Use two queries for that.

**Comment by brusch** [comment]
@BenjaminEden thank you very much for the hint, for me it was working fine with the DDL above, probably it's an issue with older versions of MySQL/MariaDB.

**Comment by brusch** [comment]
@Yivan changed the migration script accordingly to @BenjaminEden suggestion, can you please try if it works now for you? 
Thanks!

**Comment by BenjaminEden** [comment]
@brusch It's working for you, because your id column was probably already an INT. So there was nothing to change. My column was a BIGINT. The reason could be, that my web is migrated from Pimcore 4.

**Comment by Yivan** [comment]
@brusch I confirm that the migration worked with the fix, thanks !
Thank you @BenjaminEden for your help.
