### ISSUE TITLE
[Asset] Sorting in Preview Grid and List View on Filename and Path not correct

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#4326]
When you choose in a listview the sorting A-z ascending or A-z descending the result will be grouped in uppercase and lowwercase instead of A-z ignoring uppercase and lowercase.

![sorting](https://user-images.githubusercontent.com/1086343/57233371-cb152080-701e-11e9-9d26-30e1b1adb39c.png)

**Comment by dpfaffenbauer** [comment]
FYI: If that is a extjs offline sort (client wise sort): that is actually intended by extjs sort function. To fix that, you have to make the fields all lowercase in the store or implement a custom sort function

**Comment by brusch** [comment]
Regression of #4086 , fix similar to #4269 (780a4ed281168a08d8f00f121aefd6d2c9976c28)
