### ISSUE TITLE
Copying an object with mandatory and unique field is not possible.

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#4333]
I see that there are already some issues regarding this, but I am not sure whether this is wanted behavior or not:

I have got a class that contains just one field named "remoteId" (unique, mandatory).
When I create an object, publish it and then copy & paste it, this is not possible 
with "unique constraint violation".

Version: v5.7.3
Git Hash: d2acc6e0bbf363175975fce77af0557b017739cb

**Comment by fashxp** [comment]
what would be your expected behavior?

**Comment by andreas-gruenwald** [comment]
In my opinion the "best" behavior would be to create the object with an empty remoteId (null), so that the error does not occur.
Optionally, the object can be unpublished on paste.

**Comment by tomseifert** [comment]
Copying products is a key requirement for us. Since all products have a unique product number, the copy function is unfortunately not usable.
