### ISSUE TITLE
[Symfony 4] Replace sensio/distribution-bundle

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#4340]

**Comment by dpfaffenbauer** [comment]
why not take the opportunity and update to symfony 4 and do it properly?

**Comment by brusch** [comment]
`"symfony/symfony" : "^3.4 || ^4.0"` ...

**Comment by brusch** [comment]
For now it should be sufficient to move the functionality of 
`Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache`
and 
`Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets`

to: 
`Pimcore\Composer::clearCache`
and 
`Pimcore\Composer::installAssets`

This has less impact and still gives the possibility to optionally use Flex.

**Comment by dpfaffenbauer** [comment]
so what? Just because flex supports 3.4 doesn't mean pimcore has to stay on it.

**Comment by brusch** [comment]
We don't stay on `3.4` we just give our developers the choice between `^3.4` (which is LTS) and `^4.0` ...

**Comment by brusch** [comment]
For installing the assets we have already an existing service:  `\Pimcore\Tool\AssetsInstaller::install()` 
and also for clearing the cache: `\Pimcore\Cache\Symfony\CacheClearer::clear()` we should be able to reuse those ...

**Comment by weisswurstkanone** [comment]
TODO:

replace:
https://github.com/pimcore/skeleton/blob/master/composer.json
https://github.com/pimcore/demo-ecommerce/blob/master/composer.json
https://github.com/pimcore/demo-basic/blob/master/composer.json
