### ISSUE TITLE
Setting Visible Fields in Many-to-Many-Relations leads to the relations not showing up in the tag at all

### ISSUE THREAD

**Issue by FranzRest** [pimcore/pimcore#4341]
# Bug Report
Setting Visible Fields of Many-to-Many-Relations in the class definition leads to relations not showing up
It seems that the information is still there, but not correctly shown in the tag

### Expected behavior
I can specifiy the shown tag columns by setting visible fields in the class definition and the objects in the tag still are shown with the information of the fields selected

### Actual behavior
Setting Visible Fields leads to the relations not showing at all (even though it seems they are at least there) 
On the most recent version the Visible Field Settings are ignored and the default settings show the relations correctly

### Steps to reproduce
1. Define a multi-relation in a class definition
2. Place a relation in the tag
3. Change the Visible Field Settings and specify fields that should be shown in the tag
4. Reload -> the tag does not show any deposited relations anymore

most recent version
1. Define a multi-relation in a class definition
2. Place a relation in the tag
3. Change the Visible Field Settings and specify fields that should be shown in the tag
4. Reload -> the tag shows the objects with the default columns

**Comment by fashxp** [comment]
can't be reproduced. 
can you reproduce that in our public demos?

**Comment by FranzRest** [comment]
![visiblefieldsbug2](https://user-images.githubusercontent.com/6606770/57385695-3263d980-71b3-11e9-8fd8-203aaa68ad9e.JPG)
![visiblefieldsbug1](https://user-images.githubusercontent.com/6606770/57385696-3263d980-71b3-11e9-9a76-ed664920a144.JPG)
Reproduced on the advanced Pimcore demo
The visible fields are set to only show ID + Filename
Nevertheless the default view is shown (ID + Reference + Class)
Tested with multiple variations, all show the default layout

**Comment by fashxp** [comment]
in advanced demo, due to workflow, the products are loaded in a custom layout named `readonly` ... so you need to change that (not the main class definition).

**Comment by fashxp** [comment]
for me everything works fine and as expected.

**Comment by FranzRest** [comment]
ok, when reloading as master admin it works as expected, so the first bug should be solved with updating pimcore
thank you, issue can be closed
