### ISSUE TITLE
[Newsletter] Resolved host url is not correct

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#4343]
# Bug Report
When sending a newsletter, the host url gets resolved incorrectly. This is because `[\Pimcore\Tool::getHostUrl()](https://github.com/pimcore/pimcore/blob/master/lib/Tool.php#L452)` can't resolve the current request.

The host url is used to for example prefix image resources. Now, if you are sending the newsletter from a secure domain, the `https` protocol is ignored and `http` is used to process the newsletter template. This causes a lot of issues, some email clients don't even display "insecure" image resources.

Also if you're using the `www` prefix for your website's domain, that also gets ignored. That shouldn't be a big issue though.

### Expected behavior
Images getting prefixed with the correct host url, e.g. `https://www.domain.com`

### Actual behavior
Images getting prefixed with the wrong host url, e.g. `http://domain.com`

### Steps to reproduce

1. Go to https://demo-basic.pimcore.org/admin and sign in
2. Open the newsletter template `newsletters / example-mailing`
3. Send a newsletter to a random email address (doesn't matter which one)
4. Preview the HTML email in the "Sent Emails" tab and inspect the large image with the palm trees in it

**Comment by solverat** [comment]
maybe related: #3579

**Comment by aarongerig** [comment]
@brusch WDYT?

**Comment by brusch** [comment]
The problem is that the newsletter is sent via CLI, therefore no request is available. 
In that case `Pimcore\Tool::getHostUrl()` falls back to the host which is configured in System Settings. 

I'd say this is fine, but we should make the default protocol `https://` instead of `http://`. 
What do you think?

**Comment by aarongerig** [comment]
I'm not sure if that would be good default value, because then Pimcore would infer that the domain is https ready. Of course every domain should be https secured, but I just don't think that is always the case.

Something that comes to my mind would be to use cURL to see what the redirect location of an incomplete url would be. `http://domain.com` => cURL => `https://www.domain.com`

Maybe something along those lines could help?
https://gist.github.com/davejamesmiller/dbefa0ff167cc5c08d6d

**Comment by brusch** [comment]
@aarongerig To be honest, I don't like the idea of making a HTTP request and see if there's a redirect (debugging, ...). 
Then I'd rather go for an optional config option to set the scheme/host prefix manually and keep the default behavior as it is now. 
This is how the config could look like: 

```yml
pimcore:
  documents: 
   newsletter: 
      defaultUrlPrefix: 'https://my-host.com'
```

**Comment by aarongerig** [comment]
@brusch That would be totally fine with me. 👍

**Comment by brusch** [comment]
@aarongerig so can you provide a PR for that?  😉

**Comment by aarongerig** [comment]
Sure, I'll give it a try.

**Comment by aarongerig** [comment]
@brusch Wouldn't it make sense to introduce an interface and an abstract class (which implements the interface) for Newsletter DataObjects? This could replace [this check](https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php#L220-L226) and also auto complete [the many method calls](https://github.com/pimcore/pimcore/blob/master/lib/Tool/Newsletter.php#L351-L356) in an IDE.

Also, I wasn't able to find [`Pimcore\Model\Tool\Newsletter\Config`](https://github.com/pimcore/pimcore/blob/master/lib/Tool/Newsletter.php#L162). Do you know if that class had been renamed or removed?

**Comment by aarongerig** [comment]
ping @brusch

**Comment by aarongerig** [comment]
@brusch Sorry to bother you, but I need those infos to finish the PR. Thanks!

**Comment by brusch** [comment]
@aarongerig an interface would be a nice solution, but would be a bc-break and is in general a different topic :). So I'd concentrate on the original problem for now, and just introduce the config option for the host prefix.

**Comment by aarongerig** [comment]
@brusch ok, what about the missing class?

**Comment by brusch** [comment]
@aarongerig it seems that https://github.com/pimcore/pimcore/blob/master/lib/Tool/Newsletter.php#L167 isn't even used anymore ...  at least I haven't found any usage, so I'd assume it's legacy code anyway. 
I guess it got obsolete with this change: https://github.com/pimcore/pimcore/issues/748
Maybe @fashxp can confirm this.

**Comment by aarongerig** [comment]
@brusch Alright, I deprecated the method to keep BC.
