### ISSUE TITLE
[Newsletter] Exception on send

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#4344]
# Bug Report

When sending a newsletter in the sending panel an exception is thrown:

**Message**
```
Call to a member function getTmpStoreId() on null
```

**Trace**
```
Pimcore\Bundle\AdminBundle\Controller\Admin\Document\NewsletterController::sendAction() on [line 318](https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php#L318)
```

I think [this commit](https://github.com/pimcore/pimcore/commit/27219a02c152d88afe7446b217c4f0c93cb2df17) is responsible for this.

### Expected behavior
Newsletter is sent without an exception being thrown.

### Actual behavior
Newsletter cannot be sent, because an exception is thrown.

### Steps to reproduce

1. Go to https://demo-basic.pimcore.org/admin and sign in
2. Open the newsletter document `newsletters / example-mailing`
3. Go the the sending panel and try to send the newsletter with CSV provider to a random email (doesn't matter which one)
4. Confirm the dialog and then the error occurs

**Comment by brusch** [comment]
Regression of #4286

**Comment by aarongerig** [comment]
@brusch Thanks!
