### ISSUE TITLE
[Image-Thumbnails] WebP Support issues with Firefox and Edge

### ISSUE THREAD

**Issue by thgross** [pimcore/pimcore#4345]
# Bug Report

On Firefox, there are certain problems regarding the usage of the Accept-Header "image/webp". Current Firefox (V 66) does **not** send this header on page request, but only on image requests. (Chrome currently sends "image/webp" on all requests)

This leads to several problems:
- pimcore does not create correct html for image-thumbnails; `src` and `srcset` contain links to `.jpeg`, but not `.webp`. Since the `.jpeg` files are usually created anyway, this usually goes unnoticed.
- In the case of the above mentioned "Select specific area of image" function, things are a bit different - the image is visible inside the page, because Firefox sends the Accept-Header "image/webp" along with the request to `.jpeg`, and for some reason, pimcore delivers the existing `.webp`-file on this `.jpeg`-request.
    
    However, when requesting only the image (right click on the image, "view image"), pimcore responds with a 404 error, because the requested `.jpeg` has never been created anyway.

### It looks like there are 2 main problems:
1. pimcore uses the page-request Accept-Header to create thumbnail html code fixing the image type in `src`/ `srcset`.
    Instead, something like this should be used:
    ```html
    <picture>
      <source type="image/webp" srcset="/image-thumb__3__teaser/image.webp">
      <source type="image/jpg" srcset="/image-thumb__3__teaser/image.jpeg">
      <img src="/image-thumb__3__teaser/image.jpeg" alt="">
    </picture>
    ```
2. The "Select specific area of image" does **not** work the same way as normal thumbnails, making the problem worse because the `.jpeg`-image is not even created.

### Expected behavior
Thumbnail-images should always be created

### Actual behavior
Thumbnail-images are not created when using "Select specific area of image"

### Steps to reproduce
**This is not possible on demo-basic.pimcore.org, because the `webp`-format ist not supported on that site anyway.**
- Use Firefox
- Set up a thumbnail with "Format: Auto (Web-optimized - recommended)"
- Use am Image in a page using that thumbnail
- Right click on the image and choose "Select specific area of Image"
- Choose any area and save, then save the page
- View the page outside the admin interface
- The cropped image shoud be visible
- Right click on the image, select "view image"
- The image is not there (404 error)

**Comment by brusch** [comment]
bfd2bcddd7baa811bda89259ded5b50ed026b8f8 is just a workaround for now.
