### ISSUE TITLE
Get image with @2x version using .getThumbnail(), not getHtml()

### ISSUE THREAD

**Issue by julmot** [pimcore/pimcore#4347]
# Feature Request

## Feature description

It seems that it's impossible to read out the @1x and @2x version of a thumbnail at once, within Twig, without directly outputting the HTML.
I just need to get the path to these two versions of a thumbnail to handle it internally. I can't handle it using generated HTML. 

The `.getHtml()` methods seems to handle this:
https://github.com/pimcore/pimcore/blob/a9d5e1ef6ab831914466f95f5ab2344d9fc051de/models/Asset/Image/Thumbnail.php#L486-L494

However, if I'm calling e.g. `{{ image.getThumbnail('one-column-banner-image') }}` I'm directly getting the @1x path (string). What I would like to have is an object with keys `1x` and `2x`, each referencing the thumbnail in the corresponding resolution.

Currently, I think I only have two choises: Create a second image style for each image style just with double widths/heights, then I could use `{{ image.getThumbnail('one-column-banner-image') }}` and `{{ image.getThumbnail('one-column-banner-image-2x') }}`. Or, add `@2x` before the file extension. I will choose for the second option, as it'll be better to migrate in case someone comes up with a better approach.

**Comment by julmot** [comment]
Solution for me, for now:

1. Add this to the Twig folder of the bundle

```php
<?php

declare(strict_types=1);

namespace TheBundle\Twig;

class HighResolutionImage extends \Twig_Extension
{
  /**
   * {@inheritdoc}
   */
    public function getFunctions()
  {
    return [
      new \Twig_Function('highResolutionImage', function (string $path) {
        return str_replace(
          array('.jpeg', '.jpg', '.png'),
          array('@2x.jpeg', '@2x.jpg', '@2x.png'),
          $path
        );
      })
    ];
  }
}
```

2. Register it within templating_twig.yml, e.g.

```yml
    TheBundle\Twig\HighResolutionImage:
        tags:
            - { name: twig.extension }
```

3. Usage:

```twig
{{ image.getThumbnail('one-column-banner-image') }} <br>
{{ highResolutionImage(image.getThumbnail('one-column-banner-image')) }}

{#
 Outputs:
 /image-thumb__7__one-column-banner-image/swiss-alps.jpeg
 /image-thumb__7__one-column-banner-image/swiss-alps@2x.jpeg
#}
```

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
