### ISSUE TITLE
Sorting in Asset Grid doesn't work

### ISSUE THREAD

**Issue by atietje** [pimcore/pimcore#435]
Sorting the list view of the assets doesn't work as expected when using the new Ext JS 6 user interface. 

It seems the functionality is not finally implemented yet, since `Admin_AssetController::gridProxyAction()` does not use the same mechanisms as the `Admin_ObjectController::gridProxyAction()` does. For example, `\Pimcore\Admin\Helper\QueryParams::extractSortingSettings()` is obviously not used yet to, well, extract the sorting settings, so sorting by fullpath throws an error.

Is this on your roadmap?

**Comment by weisswurstkanone** [comment]
many thanks! fixed in build 3646
