### ISSUE TITLE
Exception Handling for Bricks

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#4353]
Since Bricks are actually nothing else than a Symfony Sub Request, shouldn't symfony be able to handle exceptions for them? For example: I am currently building a Security Area where all of the backend pages are build within Pimcore. I have to check for authorization and would just throw a AccessDeniedException, but that doesn't work cause Pimcore handles any throwable directly in the Document\Tag.

https://github.com/pimcore/pimcore/blob/master/models/Document/Tag.php#L475

What do you guys think about changing that behaviour for Bricks? For BC reasons, we could add a property/method to keep the behaviour as it is right now but have the possibility to throw exceptions and let them handle from symfony?

**Comment by brusch** [comment]
To be honest I can't guess the impact of such a change ...
What do you think about an additional config option on editable level? At least this would be a bullet-proof solution. 

Example: 
```twig
{{ pimcore_areablock('content', {
    'allowed': ['blockquote', 'embed'],
    'suppressExceptions': false
}) }}
```

**Comment by dpfaffenbauer** [comment]
Yes, that would work perfectly.

**Comment by brusch** [comment]
Doesn't seem to be that easy ... if we don't catch the exception a fatal error is thrown: 
`Method Pimcore\Model\Document\Tag\Areablock::__toString() must not throw an exception, caught Exception: ....`

**Comment by ultramegatom** [comment]
php 7.4 will make it possible to thorw exceptions in __toString methods

**Comment by dpfaffenbauer** [comment]
get rid of the __toString then :P

**Comment by brusch** [comment]
Twig wouldn't be a problem at all, but as long as we support the PHP templating engine, I guess we have an issue :|

**Comment by dpfaffenbauer** [comment]
what does the PHP Engine need __toString for?

**Comment by brusch** [comment]
It's called when you do e.g. `<?= $this->input('foo') ?>` , because this returns the actual editable/tag object. 
See: 
https://github.com/pimcore/pimcore/blob/c62924ca5c3d0c482a71097cb0231aff143208d6/lib/Templating/HelperBroker/DocumentTag.php#L73

**Comment by dpfaffenbauer** [comment]
What if you do following:

https://github.com/pimcore/pimcore/blob/c213b67b781feeaa0fa84de8f5121daada02e94c/lib/Templating/Renderer/TagRenderer.php#L141

change this to call a function `renderTag`

in here

https://github.com/pimcore/pimcore/blob/89bc89e71e3d33b4c4b8ac80aee639a974bcc374/lib/Templating/HelperBroker/DocumentTag.php

You add the function `renderTag`, which does the same as `__toString` except for actually throwing exceptions.

I don't see an issue with that, since the TagRenderer is anyway responsible for rendering and returning a string, isn't it?

**Comment by brusch** [comment]
But this will break a lot of code ... e.g. `<?= $this->input('foo')->getData() ?>`

**Comment by dpfaffenbauer** [comment]
oh yeah... thats true... haven't thought about that. But that also means we have the same problem with twig right? cause it also uses then tagRenderer which then gets displayed using `__toString`.

What if he introduce a new `render` function which does what we expect, basically what the `__toString` does for now, but without exception handling, so we have the possibility to manually call `$this->areablock('blub')->render()` or `{{ pimcore_areablock('blub').render() }}`?

This wouldn't break BC, and as soon as Pimcore uses Symfony 5 thus dropping PHP Engine support, we can figure out how we can solve it for Twig and naturally also be BC with `->render()`

**Comment by brusch** [comment]
Yep, I guess that would be possible! 👍

**Comment by dpfaffenbauer** [comment]
Do you? Or should I?

**Comment by brusch** [comment]
A PR would be nice, if you have time 😉
