### ISSUE TITLE
pimcore:deployment:classes-rebuild command fails with error

### ISSUE THREAD

**Issue by Ben305** [pimcore/pimcore#4357]
# Bug Report

## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [x] This is not a security issue / vulnerability -> use [this form](https://pimcorehq.wufoo.com/forms/pimcore-security-report/) instead
- [ ] Behavior is reproducible on http://demo-basic.pimcore.org/admin/ (admin/demo)
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...)
- [x] You're not able to fix the problem yourself and send us a pull request instead of an issue.
- [x] There's no existing ticket for the same issue
- [x] Remove unused sections from below and this bullet points

### Expected behavior

Command should work as expected

### Actual behavior

After updating to 5.8.2, I see the following error:

```[OK] Cache for the "prod" environment (debug=false) was successfully cleared.  

15:31:56 ERROR     [console] Error thrown while running command "pimcore:deployment:classes-rebuild -c". Message: "Call to a member function createOrUpdateClassDefinitions() on null" ["exception" => Error { …},"command" => "pimcore:deployment:classes-rebuild -c","message" => "Call to a member function createOrUpdateClassDefinitions() on null"]

In ClassesRebuildCommand.php line 100:
                                                                      
  Call to a member function createOrUpdateClassDefinitions() on null  
                                                                      

pimcore:deployment:classes-rebuild [-c|--create-classes] [-d|--delete-classes] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--ignore-maintenance-mode] [--maintenance-mode] [-e|--env ENV] [--no-debug] [--] <command>
```

### Steps to reproduce

Run
```
bin/console pimcore:deployment:classes-rebuild -c
```

**Comment by aarongerig** [comment]
Duplicate of https://github.com/pimcore/pimcore/issues/4354

**Comment by brusch** [comment]
See #4354 
... please look for existing issues before creating new ones, thanks!
