### ISSUE TITLE
[Bug] Custom layouts naming changing between version - BC Break.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4359]
Hello,

We migrated from an old Pimcore 5.0.2 to 5.6.5.

We cannot no more save classes custom layouts because naming conventions changed.
`-` and `_` are no more allowed (and maybe some others characters).
Space cannot be used too ! (v5.6.5) But in the lastest Pimcore space character works (dev-master at this day).
An invalid name error is sent:

![custom-layout-name](https://user-images.githubusercontent.com/9025839/57628591-8ba88000-759a-11e9-94ac-8be756fbaf3b.png)

I cannot find any mention of change of naming conventions for custom layouts.
https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/Within_V5/index.html

Is it a bug, a regression ? At least `-` and `_` should be added, they are common characters, and will prevent some backward compatibility.

Can we safely rename custom layouts without breaking anything (i thin name is just used for displaying) ?

Thanks.

**Comment by brusch** [comment]
This is intentional, the name policy was introduced by #3615

**Comment by brusch** [comment]
Added note to upgrade notes.

**Comment by Yivan** [comment]
@Brush, thanks a lot for your very fast answer.

Can we safely rename them via the GUI without any impact ? (except custom made code relying on it).

**Comment by brusch** [comment]
Yep, as far as I'm aware.

**Comment by Yivan** [comment]
Ok thanks !
