### ISSUE TITLE
Asset csv export

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#4363]
# Feature Request

It would be great if there was the possibility to export the `list` tab for assets as a simple csv file.

![image](https://user-images.githubusercontent.com/9052094/57681345-cad4e080-762f-11e9-9d26-8d56fe4bccf7.png)

**Comment by brusch** [comment]
What would be an example use case for this feature? Thanks ☺

**Comment by jremmurd** [comment]
> What would be an example use case for this feature? Thanks ☺

We recently got a request from a customer concerning the functionality, I now can't exactly tell the concrete use case. We then just exported a csv from the db adminer interface, but as requested it would be nice if it would also be possible for none admin users directly from the asset list.

**Comment by fashxp** [comment]
this especially would make sense in combination with https://github.com/pimcore/pimcore/issues/1662

**Comment by markus-moser** [comment]
The same functionality was requested multiple times by our customers. 
(the metadata grid too)

There are quite a lot of use cases where this could be helpful.

**Comment by HoloborodkoBohdan** [comment]
We also needed this functionality. It will be very convenient if there is a native export in assets.

**Comment by fashxp** [comment]
PRs are as always welcome ;-)
