### ISSUE TITLE
Setting fields empty stores empty strings rather than NULL values

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#4369]
# Bug Report

Empty fields in data objects are stored as empty strings inside the `object_store` table which results in errors/unexpected behaviour when using unique keys especially when using dataobject inheritence.

As a result you cannot set an empty value in more than one object in a unique field and save the object (because these are empty strings `''`). But you can create an arbitrary amount of objects (because those newly created objects have `NULL`values). This behaviour makes it very difficult to change any unique field's value, especially when using inheritence where you are depent on being able to set empty values.

This is related to #4333.

![image](https://user-images.githubusercontent.com/9052094/57711908-ed86e980-766f-11e9-9072-dc98f2e38885.png)

**Comment by mschweiger90** [comment]
+1

**Comment by fashxp** [comment]
would be fixed with https://github.com/pimcore/pimcore/pull/13963
