### ISSUE TITLE
Assets tree is lexicographic sorted instead of natural sorted

### ISSUE THREAD

**Issue by tugboat-group** [pimcore/pimcore#4370]
# Bug Report

### Expected behavior
Assets tree files should be sorted by a natural sort.
i.e:
test1 
test2
test3 
test12
test13 

**On my Mac**
![Mac-natural-sorting](https://user-images.githubusercontent.com/35277797/57739481-90d40080-7668-11e9-8959-80baac33cd5d.png)

**MySQL 'Order By' - sorting alphanumeric correctly:** 
[https://stackoverflow.com/questions/8557172/mysql-order-by-sorting-alphanumeric-correctly](url)

### Actual behaviour 
Assets tree files are lexicographic sorted

test1
test10
test11
test12
test2
test3
test4

**From the demo instance**
![Lexi-sort](https://user-images.githubusercontent.com/35277797/57739474-89acf280-7668-11e9-9333-d04b4568840e.png)

**Comment by weisswurstkanone** [comment]
Works as designed. Mysql is only one part of the story. 

Note that the "show in tree" feature is currently implemented entirely  on the client-side as javascript code.

**Comment by NiklasBr** [comment]
> Works as designed.

Maybe the design is not as good as it could be?

**Comment by brusch** [comment]
Maybe ..., but it's not our top priority. 
If you feel this is an essential feature, please feel free to create a PR for us.

**Comment by NiklasBr** [comment]
Ok. Can we re-open this issue?

**Comment by brusch** [comment]
A PR is equivalent to an issue, so just open a PR once you have implemented this feature :)

**Comment by tugboat-group** [comment]
> Works as designed. Mysql is only one part of the story.
Hi Josef,
Could you please add some more information so I'll be able to have a better understanding of the task ahead?

Thanks.

**Comment by weisswurstkanone** [comment]
Just to summarize
- this needs to be done for objects as well (changed the title)
-the tree data is generated by AssetController::treeGetChildsByIdAction (and DataObjectController). This is the server-side place where the sorting happens (mysql).

"Show in tree" is completely handled on the client-side.

![image](https://user-images.githubusercontent.com/6142086/58160819-7826a480-7c7f-11e9-8d89-994f6cda7800.png)

Best place to look at:
https://github.com/pimcore/pimcore/blob/095abd441a7507525b6594e1b3da8bb4387d1ff1/bundles/AdminBundle/Resources/public/js/pimcore/treenodelocator.js

It basically decides whether to switch forward (increase the list offset) or backward depending one the asset filename / object key (note that it can also be sorted by indices - so be careful) **based on a string comparison**.

**Comment by tugboat-group** [comment]
Thank you for the information Josef.
I now have a better understanding on this update scope and possible implications.
