### ISSUE TITLE
[Ecommerce] Add possibility to define expiry date for voucher tokens

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#4374]
on voucher token level

**Comment by NiklasBr** [comment]
Isn't this already implemented as a price rule condition? I.e. you always add the voucher to a price rule as a condition anyway so the logical place would be to also keep the date range condition in the same interface. No?

**Comment by fashxp** [comment]
it is. 
but there may be use cases where a voucher-code is valid e.g. 1 year from voucher-code handout. and voucher-codes are handed out on different dates ... so one would have to create a separate pricing rule for each voucher-code

**Comment by fashxp** [comment]
won't fix for now
