### ISSUE TITLE
Composer::clearCache/installAssets is not callable

### ISSUE THREAD

**Issue by Siqu** [pimcore/pimcore#4377]
# Bug Report

## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [X] This is not a security issue / vulnerability
- [X] Behavior is reproducible on http://demo-basic.pimcore.org/admin/ (admin/demo)
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...)
- [X] You're not able to fix the problem yourself and send us a pull request instead of an issue.
- [x] There's no existing ticket for the same issue
- [X] Remove unused sections from below and this bullet points

### Expected behavior
Composer "pimcore-scripts" should properly clear cache and install the assets 
### Actual behavior
Pimcore\Composer.php is missing the static functions mentioned inside of the Upgrade Notes.

- Pimcore\Composer::clearCache();
- Pimcore\Composer::installAssets();

### Steps to reproduce
Install Composer with the scripts Sections from the Upgrade Notes:
[Upgrade Notes](https://github.com/pimcore/pimcore/tree/master/doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5#version-59)

**Comment by brusch** [comment]
That's for the upcoming 5.9 (dev-master) it has nothing to do with the current stable releases...
