### ISSUE TITLE
OpCache Status Page

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#438]
In system infos & tools
https://github.com/amnuts/opcache-gui

**Comment by bbak** [comment]
When running multiple Pimcore Systems on a shared server, the _file usage_ tab reveals the file path's used by other Systems. Additionally the _reset cache_ function will reset the cache for the other Systems also. 
I propose to patch Opcache-GUI to disable the _reset cache_ button (and instead provide a CLI call), as well as to Filter files for those not below the Pimcore Document Root.
