### ISSUE TITLE
[Object Bricks] Feature request: stick tabs on top when vertical scrolling.

### ISSUE THREAD

**Issue by jacobsyentl** [pimcore/pimcore#4389]
## Feature description
It would be nice if an object bricks section on a class would always be in sight.
This is especially handy when an object brick contains a lot of attributes. 

Currently you lose track of the "opened object brick tabs" when scrolling down.
This confuses some users. Therefore it would be handy if this could be made sticky.

![Screenshot 2019-05-17 at 08 22 09](https://user-images.githubusercontent.com/9139261/57907341-6e670080-787d-11e9-971b-7bd5785b65d5.png)
![Screenshot 2019-05-17 at 08 22 03](https://user-images.githubusercontent.com/9139261/57907347-72931e00-787d-11e9-86dc-2d7f2b935a53.png)

**Comment by brusch** [comment]
Thank you very much for your proposal. 
Unfortunately this isn't possible in ExtJS, but what we can think of is making the brick tabs vertical similar to what is possible with localized fields and tab panels, see also #4480 and #4478
