### ISSUE TITLE
[DataObject] allow data tags to be loaded via DI

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#4390]
### First Problem: __set_state
Pimcore already allows to implement custom implementation loaders, which is good. That already basically allows to to implement Implementation Loaders from DI. The Problem with that is, how Pimcore stores ClassDefinitions. They are saved as PHP Classes, but it does it by using `var_export`, which creates files like that:

```php
CoreShop\Bundle\ResourceBundle\CoreExtension\DataObject\ResourceSelect::__set_state(array(
 'allowEmpty' => false,
 'model' => 'CoreShop\\Component\\Core\\Model\\Country',
 'params' => 
array (
),
 'fieldtype' => 'coreShopCountry',
 'options' => NULL,
 'width' => '',
 'defaultValue' => NULL,
 'optionsProviderClass' => NULL,
 'optionsProviderData' => NULL,
 'queryColumnType' => 'varchar',
 'columnType' => 'varchar',
 'columnLength' => 190,
 'phpdocType' => 'CoreShop\\Component\\Core\\Model\\Country',
 'name' => 'country',
 'title' => 'Country',
 'tooltip' => '',
 'mandatory' => false,
 'noteditable' => false,
 'index' => false,
 'locked' => false,
 'style' => '',
 'permissions' => NULL,
 'datatype' => 'data',
 'relationType' => false,
 'invisible' => false,
 'visibleGridView' => false,
 'visibleSearch' => false,
)),
```

In here, you then already create the data tag:

https://github.com/pimcore/pimcore/blob/master/models/DataObject/ClassDefinition/Helper/VarExport.php

Which is wrong when you wanna use Dependency Injection.

### Second Problem: var_export
The definitions are created using var_export. Which is fine for now, since the Data Tags don't have any non scalar properties. But: Once you start using DI, they will and have. `var_exports` exports the whole object, even `private` and `protected` properties.

Current solution to use DI is a tricky one:
```php
public function __construct(EntityManagerInterface $entityManager) 
{
    $this->entityManager($entityManager);
}

private function entityManager(EntityManagerInterface $newValue = null)
{
    static $value;
    if ($newValue !== null) {
        $value = $newValue;
    }
    return $value;
}

....

$this->entityManager()->persist($quantityPriceRule);
```

### Wrong but easy solution
```php
public static function __set_state($data)
{
    $thing = \Pimcore::getContainer()->get('pimcore.implementation_loader.object.data')->build($data['fieldtype'], $data);
    $thing->setValues($data);
    return $thing;
}
```

### Right but more complex solution
Don't use `var_export` to save Pimcore Class Definitions. You still can use PHP Files, but they should be in a format that will be parsed from Pimcore. Sort of like it was years ago. You could potentially also use the JSON Format for storage that is also used for exports. I would prefer YML or XML that can be validated against something.

**Comment by davidhoeck** [comment]
YAML class definition would be awesome!

**Comment by dpfaffenbauer** [comment]
ping @brusch maybe this can be tackled with the next major release? We currently see this as a major Problem again, since symfony 6 has private services by default.

**Comment by dlhck** [comment]
@dpfaffenbauer that would (still) be a great feature! ... also in combination with storing the class definitions in yaml. Especially when you have to manually edit the class definition the PHP files are a pain.

**Comment by dpfaffenbauer** [comment]
@davidhoeck as well as merge conflicts are a nightmare right now, with YAML, it would be a bit easier.

**Comment by brusch** [comment]
@dpfaffenbauer I agree, having class definitions as YAML would be very nice! 💜
But that's different from this ticket (although it's related) - I could swear that there is already a ticket for storing class definitions as yaml, but wasn't able to find it - could someone create one plz? Thanks
