### ISSUE TITLE
Numeric problem with inheritance

### ISSUE THREAD

**Issue by jansarmir** [pimcore/pimcore#4392]
as of 5.8.2 there is problem with inheritance for numeric fields
setter uses $fd->preSetData, which causes reseting inherited value to 0
problem can be seen in demo-advanced.pimcore.org, as all variants have cost 0

quick fix is to remove preSetData from classes/DataObject till it will be fixed

**Comment by weisswurstkanone** [comment]
can you please provide a code sample / steps to reproduce ?

**Comment by fashxp** [comment]
just use demo advanced, try to make price fields in products be inherited

**Comment by weisswurstkanone** [comment]
only happens if a decimal precision is provided

**Comment by weisswurstkanone** [comment]
regression of https://github.com/pimcore/pimcore/pull/4323

**Comment by dpfaffenbauer** [comment]
@weisswurstkanone @brusch That should be backported to 5.8.*

**Comment by brusch** [comment]
Yes, this patch will be available in our 5.8 LTS (Enterprise Subscription only).
