### ISSUE TITLE
User can copy objects even when they have only list and view permission.

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#4393]
User can copy objects even if they have only list and view permission. I have given only list and view permission on a folder to a user and all permission on another folder.User can copy data one 1st folder (having only list and view permission)and can easily paste data in other folder on which he/she is having all the permissions...

![user workspaces](https://user-images.githubusercontent.com/21308144/57930090-b106f800-78d2-11e9-826a-f212dcaff7f2.png)

![copy](https://user-images.githubusercontent.com/21308144/57930390-7c477080-78d3-11e9-9648-09cf5ee2ce4c.png)

Permission to copy data must be ther in workspace settings...

**Comment by weisswurstkanone** [comment]
Which is fine. You are allowed to copy (i.e. "add it to the clipboard" if you want) as soon as you are allowed to view it.
