### ISSUE TITLE
User can copy and download assets even when they have only list and view permission

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#4394]
I have given only list and view permission on a folder in assets to a user , but that user can copy the assets to any other folder as well as can easily download all the assets of that folder.

There must be permission in settings ti control whether user can copy or download assets or not..
![user workspaces](https://user-images.githubusercontent.com/21308144/57930539-d7796300-78d3-11e9-9fe3-7a7868fa3dec.png)

![copy and download permission](https://user-images.githubusercontent.com/21308144/57930540-d7796300-78d3-11e9-8710-e48a0029fb87.png)

**Comment by weisswurstkanone** [comment]
Unable to reproduce. How do you paste the items? And why would prevent a download (user has view permission, right?)

**Comment by neha04** [comment]
On 1st folder I have given only view and list rights and on other folder all the rights.User can copy Assets from 1st folder on which he/she have view and list rights and can paste in a folder in which he/she has all the rights...In this way I can easily have all the assets... 

I have given permission for view and list only ..Can't we make download a permission..I can download other user's assets in the system and upload them into my own folder...

**Comment by weisswurstkanone** [comment]
sorry, I don't see the point. After pasting them (which is allowed because you have all rights) you will also have all rights that apply to that folder & files contained in that folder.

**Comment by neha04** [comment]
Got Your point!!Actually I was looking at view and copy as two different permissions.But yeah if i can view and copy manually ,it is same as copying it from the copy option...
