### ISSUE TITLE
User can add as many rows in a table even if we have fixed no. of rows and columns.

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#4396]
1.Add a table in the class and fix the no of rows and no. of columns let say 10.

![fixed rows and column](https://user-images.githubusercontent.com/21308144/57932174-f24dd680-78d7-11e9-937f-f383303c7771.png)

2.Now create an object .When the object opens there are exactly 10 rows and 10 columns as configured in class settings .But there is a delete button.

![initially 10 rows and columns](https://user-images.githubusercontent.com/21308144/57932261-232e0b80-78d8-11e9-8bfa-da6293eabb76.png)

3.Now delete all the rows and columns by clicking the delet button.Now add new columns and rows.I can add max 10 columns as specified in the settings but can add as many rows as i want..All the settings to fix the no.of rows and columns wasted...

![add as many as rows as you want](https://user-images.githubusercontent.com/21308144/57932367-625c5c80-78d8-11e9-8223-a5dcc8d22388.png)

**Comment by weisswurstkanone** [comment]
What is the expected result after clicking on the trash icon?
- if both columns and rows are fixed
- if only one of them is fixed

**Comment by neha04** [comment]
Quick question - If I have fixed the no.of rows and columns why I see trash button ? if that's to reset the content why the no.of rows and columns get deleted ?

My observation was On adding the columns i was able to add max 10 columns (as specified in the class definition) but for the rows i can add as many as I want , whats the purpose of fixed rows and column here then?

**Comment by weisswurstkanone** [comment]
The typical behavor for non-fixed rows/columns is to remove all rows & columns. That's exactly my question. Would would be the expected behavor for a fixed (or maybe mixed) configuration. Just empty the data but leave the number of columns and rows untouched ?

**Comment by neha04** [comment]
Yeah just empty the data or allow to add only 10(specified in class definition) max rows as was in case of columns

**Comment by weisswurstkanone** [comment]
Empty button will reset the grid to the same state as for a new object.
