### ISSUE TITLE
[DataObject] Fatal exception while trying to create a new object class

### ISSUE THREAD

**Issue by suhl79** [pimcore/pimcore#4398]
# Bug Report

### Expected behavior
Creation of new object class

### Actual behavior
500 Error. No new Object class created

### Steps to reproduce
Pimcore 5.8.3. Try to create the new object class in the admin backend.
Seems that in the file vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php:241 throws a fatal exception if the class doesn't already exist. After commenting out this line processing can reach line 246 and the new class can be created.

**Comment by brusch** [comment]
Unable to reproduce, creating classes works just as expected.

**Comment by suhl79** [comment]
Sorted it out. It was Rollbar extension for Symfony never letting recover back from the Exception caused by getById function not finding the newly created class in the DB.
