### ISSUE TITLE
[Search] Filter for classification store attributes in search result is not working

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#4407]
1) open data object search
2) select specific data object class with classification store attributes
3) add classification store attributes columns to result list
4) try to filter for them 
--> does not filter, no error message

![image](https://user-images.githubusercontent.com/8792145/58082355-231f5b80-7bb7-11e9-826e-f87f353688de.png)

**Comment by weisswurstkanone** [comment]
disabled filtering for now. needs complete refactoring.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
