### ISSUE TITLE
ExtJS 6 - Application Logger is missing link to file object

### ISSUE THREAD

**Issue by maff** [pimcore/pimcore#441]
Seen on 4.0.0-b4 (Build: 3642)

![application_logger_fileobject_ext3](https://cloud.githubusercontent.com/assets/27403/12971807/5139cb0c-d09f-11e5-820f-cef2f8aafbe0.png)

vs 

![application_logger_fileobject_ext6](https://cloud.githubusercontent.com/assets/27403/12971809/5469ad10-d09f-11e5-8819-bfd1670cb00d.png)

**Comment by weisswurstkanone** [comment]
fixed in build 3652
