### ISSUE TITLE
[Data Objects] WYSIWYG data-type: use <br> instead of <p>

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#4411]
Currently the inserted text of an wysiwyg field of a data object gets wrapped in a p-tag by default. We can disable this by setting `editor configuration` of the field definition to
```json
{
  enterMode:2
}
```

In our experience only few customers are aware of this "feature", most just recognize it when output layout gets scrambled.

Imho it would be better to set enterMode: 2 by default as it is much easier to wrap the output in a p-tag whereever needed than to remove the p-tag afterwards.

What do you think?

**Comment by ckemptner** [comment]
Please undo this change asap. It is now not possible anymore to add a new paragraph by hitting the "Enter" key. (Which is the default text editing behavior in all major text editing software such as Word or Wordpress - Why make it different in Pimcore than how most users know it?)
I would expect that such a change gets voted on by asking at least some community content editors -before implementing it - as this is a major change in the of content editor experience.

**Comment by NiklasBr** [comment]
I'm in agreement with @ckemptner

**Comment by brusch** [comment]
Feel free to continue the discussion, until v7 we have some time left.

**Comment by BlackbitNeueMedien** [comment]
The question is what should be default behaviour. 

If you want the old behaviour with p-tags back you can enter 
`{
  enterMode:1
}`
in the wysiwyg field's editor configuration.

**Comment by katharina-kopf** [comment]
Please undo this change asap! I work a lot in pimcore and I prefer adding a paragraph by hitting the "Enter" key - the same way as it works in word!

**Comment by NiklasBr** [comment]
> p-tags can be counter intuitive in my (and a lot of our customers') experience.

This is where my experience is the exact inverse of yours, customers expect consistency and paragraphs. And the default behaviour of other systems is now different from Pimcore.

**Comment by BlackbitNeueMedien** [comment]
There are 2 problems which initially got me to issue this: 
1. When you only have one line in a wysiwyg field, e.g. `This is <b>bold</b>` and press save it gets converted to `<p>This is <b>bold</b></p>`. It is not possible to enter something without the p-tags - they always got wrapped around the content.
2. When you set a wysiwyg field's content by code, e.g. `$object->setXyz('This is <b>bold</b>');` the content really is `This is <b>bold</b>` but when you later open the object in the Pimcore admin GUI and save the object, it gets converted as in 1. Especially this behaviour is problematic because nobody actually changed the content of the field via GUI and nevertheless its content in the database changed.

It would be fine if p-tags where only added if really "enter" gets pressed in the GUI - but if you only enter one line, p-tags should not be added automatically. 
And contents must not be altered on saving via GUI if the field has not been touched.

If above problems do not apply for your case and you do want to add a paragraph by pressing "enter", then simply add `{ enterMode:1 }` in the wysiwyg field's editor configuration.

Perhaps we could add a little more documentation about this or even add a dropdown in the wysiwyg field definition to set the enter mode.

**Comment by jansarmir** [comment]
I think, everyone will later customize editor for what he is expecting
making frontend design consistent, you want to remove h1 tag mainly and styles too
make one stable decision, and add better example in doc how customize it on you own
like mine example, its easy
````js
"use strict";
// src/AppBundle/Resources/public/js/pimcore/ckeditor.config.js
pimcore.object.tags.wysiwyg.defaultEditorConfig = {
    enterMode: CKEDITOR.ENTER_P,

    format_tags: 'p;h3;h4;h5;h6;pre;div',

    removePlugins: 'stylescombo',
    removeButtons: 'Font'
};
````
````php
// src/AppBundle/AppBundle.php
class AppBundle extends AbstractPimcoreBundle implements DependentBundleInterface
{
    public function getJsPaths()
    {
        return [
            '/bundles/app/js/pimcore/ckeditor.config.js'
        ];
    }
}
````

**Comment by BlackbitNeueMedien** [comment]
@jansarmir, you are right but this isn't even necessary as you could just write 
```
{
    enterMode: CKEDITOR.ENTER_P,
    format_tags: 'p;h3;h4;h5;h6;pre;div',
    removePlugins: 'stylescombo',
    removeButtons: 'Font'
}
```
to the wysiwyg field's editor configuration (this is a field in class definition). Then you would not need any additional files.

**Comment by brusch** [comment]
If the majority votes for reverting the change (in the next bug-fix release), I'd be happy with that as well, but please, do not complain about SemVer afterwards ...

**Comment by NiklasBr** [comment]
🙇 thanks

I think starting with semver at v7.0 would be most true to the reality of the situation and easiest to do. Even though I hope it can be introduced earlier (and semver includes provisions for BC breaks and restoring them if done in a minor/patch release).

**Comment by BlackbitNeueMedien** [comment]
To all who want `enterMode: CKEDITOR.ENTER_P` back as default: Beside that you cannot add a paragraph by pressing the "enter" key, don't you think the points mentioned in https://github.com/pimcore/pimcore/issues/4411#issuecomment-509692687 are problematic for a default setting?

**Comment by ckemptner** [comment]
Hello Blackbit - Imho for the WYSIWYG editor, which is one of the most-used features of Pimcore users, we have to think "user-first" and not "developer-first". The problems you have mentioned might be solved in some other way - The experience for the users in Pimcore should be consistent with what they know and expect.

**Comment by NiklasBr** [comment]
> don't you think the points mentioned in #4411 (comment) are problematic for a default setting?

Point 1,  I think it is an analysis from an incorrect assumption that short paragraphs are not paragraphs. Any and all paragraphs of texts should be wrapped in `<p>` tags, even if the paragraph is just a short one-line paragraph. It is still a paragraph.

Point 2, yes, this can be problematic, but entirely possible to solve, for example WordPress has had the [wpautop()](https://core.trac.wordpress.org/browser/tags/5.2.1/src/wp-includes/formatting.php#L440) since basically forever and it works beautifully.

**Comment by BlackbitNeueMedien** [comment]
@NiklasBr Of course short paragraphs are paragraphs but what if you want to enter a product name which later on gets output as <h1> or whatever - which actually does not allow a <p>-tag within? Of course you can remove it but which frontend developer will think about this?

And no doubts that the mentioned problems are solvable - and if there is a solution I am the last to stem against `CKEDITOR.ENTER_P`.
But if you open an object, do nothing and press save there MUST not be a change to the data. Of course this is a developer perspective but when you use `enterMode: CKEDITOR.ENTER_P` you better be prepared when you imported your data from an external source without <p>-tags and later (after the customer saved some Pimcore objects) get calls why the layout is broken.

**Comment by NiklasBr** [comment]
> but what if you want to enter a product name which later on gets output as <h1> or whatever - which actually does not allow a <p>-tag within

I don't understand why you are using a *What You See Is What You Get* input field for output where what you get is not what you want to see.

**Comment by BlackbitNeueMedien** [comment]
> I don't understand why you are using a What You See Is What You Get input field for output where what you get is not what you want to see.

Because the customer wants e.g. to put somethin in italic or bold or change font color of a part of the product name.

**Comment by NiklasBr** [comment]
For such highly specialised input fields I would configure a very small subset of editor buttons, removing things like images, styles, links, tables and so on to prevent breaking layouts. I can understand that as a valid requirement, but I do not think it is a good reason to set the default behaviour to something non-standard and something which deviates from best practices.

**Comment by BlackbitNeueMedien** [comment]
> For such highly specialised input fields I would configure a very small subset of editor buttons, removing things like images, styles, links, tables and so on to prevent breaking layouts.
This does not help against `<p>` tags getting magically added.

Whatever, I have written everything I have to say about this topic. When the majority or the Pimcore team thinks `enterMode: CKEDITOR.ENTER_P` is a better default, I am fine with this. As described in https://github.com/pimcore/pimcore/issues/4411#issuecomment-509784157 everybody can configure the default behaviour of wysiwyg fields. And if `enterMode: CKEDITOR.ENTER_P` gets reinroduced as default, I will add this little JS file to future projects and everybody is fine.

**Comment by jansarmir** [comment]
i think most cases are using `CKEDITOR.ENTER_P`
if you need other behavior then bunch of html text (mostly content does not care), you can handle it per situation, rather then making global settings

my opinion about wysiwyg field is
- contains just some html text, always rendered even if its empty, empty <p> doesnt effect design
- but i have option to do some control a settings, if its needed
