### ISSUE TITLE
[DataObjects] improve language behavior of grid view for localized fields 

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#4412]
Currently I see no option to change the language of localized fields in the grid. Although I set the user's language to German, the message above the grid states "Aktuelle Sprache: Englisch". 
Shouldn't localized fields be shown in the currently logged in user's language?
And how to change the language of the shown grid data?

**Comment by fashxp** [comment]
it is in grid config
![image](https://user-images.githubusercontent.com/8792145/58102983-7bb81e00-7be2-11e9-9782-68a4093cfd59.png)

**Comment by BlackbitNeueMedien** [comment]
@fashxp Why is the language of the logged-in user not used as default? And if this is not possible: Can the default language be set anywhere?
Because it is difficult to explain to our customers with 100% german employees why the grid columns are in english by default.

**Comment by BlackbitNeueMedien** [comment]
@fashxp what do you think about my proposal?

**Comment by weisswurstkanone** [comment]
I would not use the user's backend UI language as the default.

Instead, why not just pick the firs one of this list from the user settings ?

![image](https://user-images.githubusercontent.com/6142086/58320153-56622480-7e1b-11e9-8971-126dcf3dff07.png)

**Comment by BlackbitNeueMedien** [comment]
Sounds good to me @weisswurstkanone but where is this setting? I also thought of using the first language - but I thought of the one in system settings > localization & internationalization (but you cannot change the order there, so I think your "editor settings" are the better place - but where are they?)

**Comment by weisswurstkanone** [comment]
![image](https://user-images.githubusercontent.com/6142086/58322225-a5f71f00-7e20-11e9-918b-248df4518414.png)

Same order is used for localized field tabs.

**Comment by BlackbitNeueMedien** [comment]
Ah great, then different users can set a different first language and everybody gets grid data in his preferred language. Would you implement a PR?

**Comment by weisswurstkanone** [comment]
Good news: no change needed, this is already the standard behavior. So just reorder your languages ;-)

There is one more thing you can do: Set the grid language on folder level.
- Open the grid config (red arrow)
-  change the grid language
- apply
- save the configuration (orange arrow)
- mark it as default (green arrow)

![image](https://user-images.githubusercontent.com/6142086/58326717-f6c14480-7e2d-11e9-9bc0-4a4849a59d91.png)

![image](https://user-images.githubusercontent.com/6142086/58326748-093b7e00-7e2e-11e9-9433-3139d3979a38.png)

=> grid will always open with the chosen language
