### ISSUE TITLE
Symfony 4: HeadTitle/HeadMeta/etc.

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#4414]
HeadTitle gets inlined in Symfony and thus should be marked public, since it is getting used quite often in Controllers with `$this->get`

https://github.com/pimcore/pimcore/blob/160cf81c5478f6c1a74b92ed8487708fb8f00849/bundles/CoreBundle/Resources/config/templating_php.yml#L76

https://travis-ci.com/coreshop/CoreShop/jobs/201949826#L2563

**Comment by brusch** [comment]
But it's quite easy to inject via DI ... don't think this is really necessary ... other opinions?

**Comment by dpfaffenbauer** [comment]
not really. The funny thing is, I always use it with DI, and it only fails in the behat context.

I'll guess I find another way of fixing it.
