### ISSUE TITLE
Upgrade to 4.6.x results in Internal Server Error

### ISSUE THREAD

**Issue by alphaDev23** [pimcore/pimcore#4415]
I receive the following error when updating to 4.6.x.  Is there a resolution?

Status: 500 | Internal Server Error
URL: /admin/update/index/job-parallel
Params:
-> type: download
-> revision: 4064
-> url: https://update.pimcore.org/v2/getFiles.php?for=4064&offset=0&limit=50
Message: 

Fatal error:  Uncaught Zend_Db_Statement_Mysqli_Exception: Mysqli statement execute error : Got error 35 "Resource deadlock avoided" during COMMIT in /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `_t...', Array)
#3 [internal function]: Zend_Db_Adapter_Abstract->insert('_tmp_update', Array)
#4 /var/www/html/pimcore/lib/Pimcore/Db/Wrapper.php(296): call_user_func_array(Array, Array)
#5 /var/www/html/pimcore/lib/Pimcore/Db/Wrapper.php(266): Pimcore\Db\Wrapper->callResourceMethod('insert', Array)
#6 /var/www/html/pimcore/lib/Pimcore/Update.php(245): Pimcore\Db\Wrapper->__call in /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Mysqli.php on line 214

**Comment by brusch** [comment]
Sorry, Pimcore 4 is EOL.
