### ISSUE TITLE
Using undefined method 'isDocumentSupported'

### ISSUE THREAD

**Issue by AlternateIf** [pimcore/pimcore#4423]
With #4405 legacy functionality was removed including the isDocumentSupported method in the DocumentRouteHandler.

This causes a 'call an undefined method named "isDocumentSupported" of class "Pimcore\Routing\Dynamic\DocumentRouteHandler' since isDocumentSupported is still used here: [DocumentRouteHandler.php](https://github.com/pimcore/pimcore/blob/master/lib/Routing/Dynamic/DocumentRouteHandler.php#L113)

The method call should probably just be removed. What do you think @brusch

**Comment by AlternateIf** [comment]
using pimcore #76a2e424bcf9221e52c312d5f5d4de5d8366bfea

**Comment by brusch** [comment]
Yep, you're right, just forgot this one usage :) Thanks!
