### ISSUE TITLE
Possible incorrect deeplink generation for Workflow-Emails?

### ISSUE THREAD

**Issue by Siqu** [pimcore/pimcore#4425]
# Bug Report

### Expected behavior

* Deep Link Url is correct e.g. [scheme]://[domain]/[pimcore_admin_login]/deeplink?[object_id]

### Actual behavior

* Deep Link Url is incorrect [scheme]://[domain]//[pimcore_admin_login]/deeplink?[object_id]
* There is actually a double / after the domain part and before the login part.

The problem is the following line https://github.com/pimcore/pimcore/blob/361bba44dced98a9f51be91dc133f74f050691d4/lib/Workflow/NotificationEmail/NotificationEmailService.php#L82

In my opinion the appended '/' after the host url should be removed, because the host Url has no '/' at the end and the router will generate a Url '/login', the appended '/' would then result in '//login'.

If this is actually a problem i would gladly create a merge request for the bugfix.

I currently fixed this problem in my system by overwriting the NotificationEmailService.

Best regards

**Comment by justbane** [comment]
I think is still an issue - the link is being formed correctly but all the links are sent as object links.

I am getting object links when i am, editing pages.

For instance here is the deeplink to the page: https://www.mysite.com/admin/login/deeplink?document_1824_page

Here is the link that came in the email when i edited the page and submitted the workflow: https://www.musite.com/admin/login/deeplink?object_1824_object

The ID is correct but the link is wrong.
