### ISSUE TITLE
Switching between asset versions

### ISSUE THREAD

**Issue by Maksonis** [pimcore/pimcore#4426]
# Bug Report

### Expected behavior
Show the latest image version on all dependencies

### Actual behavior
Show old image version on all dependencies

### Steps to reproduce

1. Open Home/en/introduction document in demo-basic.pimcore.org/admin
2. Find brick "Featurette" and open image (right click -> Open)
3.  Upload new version of the image and hit Save&Publish
4. Old image version is still present on the site (while switching version - on the frist time works because Versions tab is empty) 

### Video
![ezgif com-resize](https://user-images.githubusercontent.com/17277953/58239652-bc7e7700-7d49-11e9-9449-97e91a237847.gif)

**Comment by weisswurstkanone** [comment]
Seems that this is a browser caching issue. After refreshing the page everything is fine.
Please add cacheBuster=true if you want to be on the safe side.

https://pimcore.com/docs/5.x/Development_Documentation/Documents/Editables/Image.html

**Comment by dgheorgheavira** [comment]
@weisswurstkanone this is not a page caching issue.

We were able to reproduce this with debug mode, cache-buster, query string and cache disabled inside browser.

Moreover, when you use webp .. the image is NEVER changed.

Please try uploading multiple pictures and then moving through the versions

**Comment by weisswurstkanone** [comment]
That is exactly what I did :-)

**Comment by dgheorgheavira** [comment]
Well .. it does not work for us on 5.8.3. We are using S3 instead of the local storage ...

**Comment by brusch** [comment]
We are not able to reproduce it, if you think that this is a Pimcore bug, I'd like to ask to to provide us a pull request. 
Thanks a lot!
