### ISSUE TITLE
Relative changes via object grid editing

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#4437]
Currently it is only possible to edit objects data via grid to an absolute value. It would be nice if you could change multiple object's data based on their current values - e.g. raise prices by 10%.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
