### ISSUE TITLE
Website settings problem

### ISSUE THREAD

**Issue by kkarkus** [pimcore/pimcore#4444]
# Bug Report

- [ ] This is not a security issue / vulnerability
- [x] Behavior is reproducible on http://demo-basic.pimcore.org/admin/ (admin/demo)
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...)
- [x] You're not able to fix the problem yourself and send us a pull request instead of an issue.
- [x] There's no existing ticket for the same issue

### Steps to reproduce

1. Open website settings.
2. Add new setting with type text, fill value with some data and click or double click on sites input.

I've recorded how I reproduce this https://streamable.com/x6t48

### Actual behavior 

ExtJS stops to work correctly so you need to refresh a page.

**Comment by weisswurstkanone** [comment]
nice ticket number :-)
