### ISSUE TITLE
Pimcore 6 Many-To-One Relation with Lazy-Loading in Fieldcollection is not working

### ISSUE THREAD

**Issue by MercuryKojo** [pimcore/pimcore#4446]
# Bug Report
Í can't save an object with a fieldcollection with Lazy-Loading Many-To-One Relation:

Status: 500 | Internal Server Error
URL: /admin/object/save?task=publish
Method: PUT
Message: property athlete does not exist
Trace: 
\#0 vendor/pimcore/pimcore/models/DataObject/Fieldcollection.php(283): Pimcore\Model\AbstractModel->setObjectVar('athlete', NULL)
\#1 vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php(576): Pimcore\Model\DataObject\Fieldcollection->loadLazyField(Object(Pimcore\Model\DataObject\BlogBundleArticle), 'MagazinCitation', 'content', 3, 'athlete')
\#2 vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/ManyToOneRelation.php(587): Pimcore\Model\DataObject\ClassDefinition\Data\Relations\AbstractRelations->loadLazyFieldcollectionField(Object(Pimcore\Model\DataObject\Fieldcollection\Data\MagazinCitation))
\#3 var/classes/DataObject/Fieldcollection/Data/MagazinCitation.php(36): Pimcore\Model\DataObject\ClassDefinition\Data\ManyToOneRelation->preGetData(Object(Pimcore\Model\DataObject\Fieldcollection\Data\MagazinCitation))
\#4 var/classes/DataObject/Fieldcollection/Data/MagazinCitation.php(50): Pimcore\Model\DataObject\Fieldcollection\Data\MagazinCitation->getAthlete()
\#5 vendor/pimcore/pimcore/lib/Model/AbstractModel.php(211): Pimcore\Model\DataObject\Fieldcollection\Data\MagazinCitation->setAthlete(NULL)
\#6 vendor/pimcore/pimcore/lib/Model/AbstractModel.php(193): Pimcore\Model\AbstractModel->setValue('athlete', NULL)
\#7 vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Fieldcollections.php(210): Pimcore\Model\AbstractModel->setValues(Array)
\#8 vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(1226): Pimcore\Model\DataObject\ClassDefinition\Data\Fieldcollections->getDataFromEditmode(Array, Object(Pimcore\Model\DataObject\BlogBundleArticle))
\#9 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
\#10 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
\#11 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
\#12 web/app.php(42): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
\#13 {main}

**Comment by weisswurstkanone** [comment]
Unable to reproduce. Please provide more infos. Did you try on https://demo-advanced.pimcore.org or https://demo-basic.pimcore.org ?

**Comment by brusch** [comment]
@MercuryKojo Any updates on this? Thanks!

**Comment by brusch** [comment]
@MercuryKojo anything?

**Comment by weisswurstkanone** [comment]
Relation fields lazy-loading but Fieldcollection itself must be non-lazyloading.
