### ISSUE TITLE
Export to Excel

### ISSUE THREAD

**Issue by kubaplas** [pimcore/pimcore#4455]
# Feature Request
Possibility to export to xls or ods format from a grid perspective.
## Feature description
Expand grid CSV export feature to include xls format. Converting between csv and excel (or ods) format is rather easy. It can solve issues with interoperability caused by different encoding used by Microsoft Office and Pimcore. Also, it would allow skipping configuration step when opening an exported file in Libre Office.
If feature proposal is accepted, I could implement it.

**Comment by brusch** [comment]
Sounds good! 
Can you also have a look at this one here #2358 ? I guess it makes sense to optimize the CSV export first before implementing new features on top of it.

**Comment by brusch** [comment]
I guess we should go for `xlsx` as it's more common than `ods` I guess.
