### ISSUE TITLE
Block with lazyload in LocalizedField leads to error

### ISSUE THREAD

**Issue by AlternateIf** [pimcore/pimcore#4456]
Steps to Reproduce: 

1) Create a classdefintion in pimcore
2) add a Tabpanel
3) add a Panel as child of tabpanel
4) add a localized field as child of panel
5) add a block as child of the localized field
6) add a input field as child of the block
7) set the lazyload flag on the block
8) save the definition and create an object off of the classdefinition in pimcore 

in step 8 you should experience the following bug:

Message: Call to a member function getClassId() on null
Trace: 
#0 /home/pimcore/www/vendor/pimcore/pimcore/models/DataObject/Localizedfield.php(351): Pimcore\Model\DataObject\ClassDefinition\Data\Block->load(Object(Pimcore\Model\DataObject\Localizedfield), Array)

this is also reproducible when you don't set the lazy load at first, create the object, close it, then set the lazy load flag and try to reopen it

i've tested this on the pimcore demo demo-basic.pimcore.org with the classdefinition blocktest @weisswurstkanone

**Comment by AlternateIf** [comment]
pimcore version is 5.8.3

**Comment by ITspirit** [comment]
It seems it´s functional, but i still geht the error if i to this on child/variants when i set this:

```
$productVariant
->setType(DataObject\AbstractObject::OBJECT_TYPE_VARIANT)
->setParentId($parentId)
```
Error occurs in /home/pimcore/www/vendor/pimcore/pimcore/models/DataObject/Localizedfield.php(303):
Call to a member function getFieldDefinition() on bool

The parameter "context" contains "containerType" = "block", but in line 295 it refers to an array key "containerKey" which is missing in that case, so "$blockDefinition" an "$container" will be "null".

Looks like a similar bug. The code works a long time before and after upgrade, it's broke now.

**Comment by weisswurstkanone** [comment]
Please provide your class definition and more detailed steps on how to reproduce.

**Comment by ITspirit** [comment]
I´ve just a short test and class definition, which reflects the problem with localicedfields within block variant.
(Sorry for the late response, was on vacation for two weeks).

[pimcore_test.zip](https://github.com/pimcore/pimcore/files/3320618/pimcore_test.zip)
