### ISSUE TITLE
Mandatory fields of type StructuredTable cannot be saved

### ISSUE THREAD

**Issue by atietje** [pimcore/pimcore#446]
I have a mandatory field of type structured table for storing prices as integers (yes, integers, no cents, just euros).

One product has all prices set to zero, since it's free of charge. Setting a price of 0 should be perfectly valid, but `Pimcore\Model\Object\ClassDefinition\Data\StructuredTable::checkValidity()` checks for `!empty($dataArray[$r['key']][$c['key']])` and says it's not. 

When I tested in demo.pimcore.org storing data in a mandatory structured table was completely impossible:

![structured-table-mandatory](https://cloud.githubusercontent.com/assets/416583/13013119/5d068190-d1ae-11e5-88a3-8bb310bcc007.png)

Here's my [class_test_export.json.zip](https://github.com/pimcore/pimcore/files/128279/class_test_export.json.zip)

**Comment by weisswurstkanone** [comment]
fixed in build 3660
