### ISSUE TITLE
allow env config to extend default system config

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#447]
to prevent redundancy it would be great to add only env specific infos to the given environment. for an example:

`system.development.php` only contains db config values, the rest will be inherited from the original `system.php`:

```php
<?php

return [
    "database" => [
        "params" => [
            "username" => "xyz",
            "password" => "xxx",
            "dbname" => "pimcore",
            "host" => "localhost" 
       ]
    ]
];
```

**Comment by atietje** [comment]
Wouldn't that mean that you shouldn't edit env specific system preferences in the backend, but manually in an editor? I suppose specific settings would be overwritten when clicking the save button in the system settings gui, unless you create a diff between env specific settings and settings in system.php before storing them. I'd prefer the more stable an less error prone way…

**Comment by solverat** [comment]
you're right. i always forget about the backend settings gui. it would be more confusing than helpful. :)
