### ISSUE TITLE
[Improvement] Add lazy loading for tags (if many tags UI lags)

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4474]
Hello,

We have some projects with many tags.
One of them has around 7000 tags. Resulting is tag manager is slow, but the problem is more disturbing when an object is open, because tag panel for this object is loaded and thus making the object long to open and lagging the UI experience. If several object are open together, it is slower and slower.

Making the tags tree lazy loading will be great (like the document/element/object tree), thus this problem won't happen if many tags are created.

Thanks.

**Comment by dvesh3** [comment]
already fixed in 5.7.3. see https://github.com/pimcore/pimcore/pull/4206
