### ISSUE TITLE
[Shared Translations] Filter not working

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#4481]
When filtering for some text in a language column of Shared Translations, following error message is thrown:

Server threw exception - could not perform action. Please reload the admin interface and try again.

Timestamp: Tue Jun 04 2019 15:57:51 GMT+0200 (Central European Summer Time)
Status: 500 | Internal Server Error
URL: /admin/translation/translations?xaction=read&_dc=1559656671175
Method: POST
Message: An exception occurred while executing 'SELECT `translations_website`.`key` FROM `translations_website` WHERE (translations_website._en_GB LIKE '%t%') GROUP BY `translations_website`.`key` ORDER BY translations_website.key ASC LIMIT 25':

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'translations_website._en_GB' in 'where clause'

![image](https://user-images.githubusercontent.com/13643455/58885090-dc1a8580-86e1-11e9-9e69-f7f3bd48344c.png)

![image](https://user-images.githubusercontent.com/13643455/58885005-b3928b80-86e1-11e9-9f59-5648f5ea6b92.png)

**Comment by weisswurstkanone** [comment]
regression of #3367
