### ISSUE TITLE
CLI Commands are not registered

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#4497]
CLI Commands won't be registered

![command](https://user-images.githubusercontent.com/1086343/59083728-c03cfc80-88f8-11e9-87f8-cc0c152d0a60.png)

![command2](https://user-images.githubusercontent.com/1086343/59083731-c3d08380-88f8-11e9-8a54-2f134473feb2.png)

**Comment by brusch** [comment]
Works for me as expected ... 

```php
<?php

namespace AppBundle\Command;

use Pimcore\Console\AbstractCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class BernieCommand extends AbstractCommand
{
    protected function configure()
    {
        $this->setName('testimport');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $output->writeln('Foo');
    }
}
```

```bash
bernie@pimcore:~/demo-basic$ ./bin/console testimport
Foo
bernie@pimcore:~/demo-basic$
```

**Comment by dpfaffenbauer** [comment]
@putzflorian Since you are doing this on a Server, maybe production mode is enabled thus Symfony not rebuilding the container and that is the reason its not working?

**Comment by putzflorian** [comment]
@dpfaffenbauer thx for the info but after cache:clear the container should be rebuilded!

**Comment by dpfaffenbauer** [comment]
yep, and it didn't work after rebuilding either?

**Comment by putzflorian** [comment]
solved now
https://github.com/pimcore/skeleton/commit/ed778adfadebfabc13eb1c7b9aed3e37bb31c541

**Comment by fashxp** [comment]
commands are not autoloaded anymore, need to be registered as tagged services.
