### ISSUE TITLE
[Improvement] Allow debug without using debug email.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4500]
Hello,

For some maintenance work, sometimes it is needed to activate debug mode in production.
Activating it, make all email to be send to the debug email...
This is really a problem as sometimes we just want rapidly activate it to see an error message, but in the meantime email will no more be routed to the true final user.
I know we could read the log and don't activate debug, but some tasks could need it.
This is a real problem we have struggled sometimes.

Suggestion:
Create a new debug_email option, so we can activate the debug or debug_email options separatly.
Or if we want to keep that by default, activating debug redirect the email to, the option name could be a checkbox "don't send email to debug email in debug mode".

Thanks.

**Comment by aarongerig** [comment]
Hi @Yivan,

Correct me if I’m wrong, but as far as I know, you can specify the debug mode to be active for only a certain IP address. For all other users with a different IP address the debug mode won‘t take effect, same goes for sending emails of course.

**Comment by Yivan** [comment]
@aarongerig Yes you are true, this is a way to limit this problem.

The problem/danger is behind a reverse proxy.
What is dangerous I mean, is if trusted proxies are not set in the symfony config (or app.php), $_SERVER['HTTP_X_FORWARDED_FOR'] nor  $_SERVER['HTTP_X_REAL_IP'] are not used, and just the $_SERVER['REMOTE_ADDR'] is used to prefill IP in the GUI and to make the PHP check too.
In this case, Pimcore prefill IP in the GUI with the one of the reverse proxy (so all request are considered in debug mode), making all emails be sended on the debug email : (

I know developper should configure the trusted proxies (see https://symfony.com/doc/current/deployment/proxies.html), but if it is not done, debug mode is clicked... all emails are sent to the debug address...
Having a separate settings will allow to be sure not even one email is lost in any case.

We have been experienced this, so that is why i suggest this improvement, to prevent more easily this.

At least if you think this should not be a separate settings, those things can be done:
- add to the documentation a warning about this (here : https://pimcore.com/docs/5.x/Development_Documentation/Tools_and_Features/System_Settings.html#page_Debug-Mode) like a hint (why not pointing to the symfony documentation) so developper knows immediatly the debug mode rely on getClientIP from symfony.
- add an input field to set the thrusted reverse proxy
- or/and add a checkbox "website is behind a reverse proxy" making active a configuration like this `['127.0.0.1', $request->server->get('REMOTE_ADDR')]`

Those are some ideas, to discuss, but i really think some improvement can be done at this level.

Thanks.
