### ISSUE TITLE
Custom Tooltips element inheritance

### ISSUE THREAD

**Issue by Pierre-Datasolution** [pimcore/pimcore#4502]
Hi Pimocre Team,

# Bug Report
While using Custom Tooltips example [https://pimcore.com/docs/5.x/Development_Documentation/Objects/Object_Classes/Class_Settings/Custom_Icons.html], I saw that variant objects don't heritate parent values for inheritated fields

### Expected behavior
Variant object should heritate parent value

### Actual behavior
Inheritated fileds are empty/null

### Steps to reproduce
Create a class with variants and at least one input inherited field (in my case, for class ModeleVoiture, constructeur, ManyToOne relation, and descriptionCommerciale, input text, can be inherited from parent object)
Create a variant leaving this input field empty (inherited)
Override getElementQtipConfig() method and dump inherited value of object (in my case, getConstructeur() and getDenominationCommerciale() are empty as parent values are correct)

### Code example
```php
namespace AppBundle\Admin;

use AppBundle\Model\DataObject\ModeleVoiture;

class AdminStyle extends \Pimcore\Model\Element\AdminStyle {

    public function __construct($element) {
        parent::__construct($element);
    }

    public function getElementQtipConfig()
    {
        if ($this->element instanceof ModeleVoiture) {
            //$thumbnail = $this->element->getImage()->getThumbnail("exampleResize");
            return [
                "title" => (($this->element->getConstructeur())?$this->element->getConstructeur()->getNom():"Unknown")." - ".$this->element->getDenominationCommerciale(),
                "text" => $this->element->getDescriptionCommerciale()?$this->element->getDescriptionCommerciale():"No description"
            ];
        }
        return parent::getElementQtipConfig();
    }

}
```

# Feature Request
Get proper inherited value for variant object

Thanks for your help
Pierre

**Comment by weisswurstkanone** [comment]
Actually this is not a mistake as inheritance is disabled by default in admin mode.

Try something like this.

``
        if ($this->element instanceof News) {


            $originalSetting = AbstractObject::getGetInheritedValues();
            // turn it on
            AbstractObject::setGetInheritedValues(true);

            $result = [
                "title" => $this->element->getTitle(),
                "text" => "..."
            ];

            // restore original setting
            AbstractObject::setGetInheritedValues($originalSetting);

            return $result;
        }

        return parent::getElementQtipConfig();
``

**Comment by Pierre-Datasolution** [comment]
Sorry for late answer (Holidays)
I will try this
