### ISSUE TITLE
[Pimcore 6 / Symfony 4] still got Symfony 3.4 directory structure

### ISSUE THREAD

**Issue by FredoVelcro** [pimcore/pimcore#4519]
Hello,

We are trying to use the latest Pimcore (dev-master alias 6.x) using the Pimcore/skeleton
We would like to use natively the full Symfony 4.x directory structure.
When we create the project, it installs Symfony 3.4 and its related structure.
Is it a normal behavior ?
**What is the easy way to have Pimcore 6.0 + Symfony 4.3 stack ?**
Thank you very much !

**Comment by brusch** [comment]
https://talk.pimcore.org/

**Comment by brusch** [comment]
Pimcore 6 installs Symfony 4 per default, you can optionally use 3.4.
The directory structure is still 3.4 style since we're supporting both 3.4 and 4.x 
4.x runs perfectly with the dir structure of 3.4 if you prefer to use the 4.x structure this should be possible, but you'd have to change some settings.

Anyway, this is not a topic for the issue tracker ... thanks.

**Comment by brusch** [comment]
https://github.com/pimcore/pimcore/blob/9dcdd56e60992e49735cf932d73a406e9c5c053e/composer.json#L83

**Comment by FredoVelcro** [comment]
ok, but using  : 
```bash
COMPOSER_MEMORY_LIMIT=-1 composer create-project pimcore/skeleton .
```
it installs Symfony 3.4 not 4.x 
So we needed to "force" 4.x by modifying the skeleton composer.json

**Comment by brusch** [comment]
No need to force, for me it automatically installs 4.3.1

**Comment by brusch** [comment]
Ah, ok, now I see, you installed the latest release of the skeleton, which was at this time still bound to 5.8 not to dev-master (6.0). 

We've just released 6.0 so if you run it again you'll get Pimcore 6 incl. Symfony 4.3.1 ;)

**Comment by FredoVelcro** [comment]
nice ! :)
so let's try again !

**Comment by FredoVelcro** [comment]
all is ok now ! great !
that's a pitty that directory structure is not 4.3 compliant...

**Comment by dpfaffenbauer** [comment]
why not?

**Comment by brusch** [comment]
@FredoVelcro you can use the 4.3 directory structure, but the default is 3.4 ...

**Comment by FredoVelcro** [comment]
moving app/Resources/views to templates/ for instance does not works

**Comment by brusch** [comment]
RTFM 😁
https://symfony.com/doc/current/setup/flex.html#upgrading-existing-applications-to-flex
https://symfony.com/doc/current/configuration/override_dir_structure.html

If you still need help, please use talk.pimcore.org

Thanks!

**Comment by D37R4C7** [comment]
@FredoVelcro Did you successfully switched to Symfony 4 directory structure?

**Comment by FredoVelcro** [comment]
Not tested Flex yet cause not enough time...
