### ISSUE TITLE
Area Edit Dialog WYSIWYG toolbar z-index

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#452]
When using the WYSIWYG Tag in the edit of an area, the wysiwyg toolbar is outside/behind the dialog.

![bildschirmfoto 2016-02-15 um 13 08 35](https://cloud.githubusercontent.com/assets/5981845/13048369/b27e3238-d3e5-11e5-8dc8-19132a06c005.png)

**Comment by ThomasKeil** [comment]
Isn't 200 very low for elements that need to be "always on top"?
This also influences e.g. the dropdown-elements of area bricks.

I'm currently debugging a pre-4 site, that has a background z-index of 1000, which of course is over the dropdown.

Could you set it to 100000 like in https://github.com/pimcore/pimcore/commit/5ce04ab6b3fa4e427b0fcf98f3d66bffe2acebf6 ?
