### ISSUE TITLE
Values for select and multiselect are displayed incorrect on object detail view.

### ISSUE THREAD

**Issue by jacobsyentl** [pimcore/pimcore#4534]
# Bug Report

### Expected behavior
Values stored in the database are displayed correctly on the object detail view.

### Actual behavior
Values stored in the database are not correctly displayed on the object detail view.

### Steps to reproduce
1. Import products with values for a select and multiselect attribute.
2. Check the object grid view -> values are shown correctly.
3. Open the object detail view -> values are not shown correctly 

#### Database value 
![Screenshot 2019-06-18 at 10 52 14](https://user-images.githubusercontent.com/9139261/59668013-08410680-91b8-11e9-804d-605517066383.png)

#### Grid view value
![Screenshot 2019-06-18 at 10 51 35](https://user-images.githubusercontent.com/9139261/59668048-1727b900-91b8-11e9-8c9a-d0fbdd079851.png)

#### Object detail view value
![Screenshot 2019-06-18 at 10 51 43](https://user-images.githubusercontent.com/9139261/59668077-26a70200-91b8-11e9-8b66-9f697966c8a8.png)

**Comment by dvesh3** [comment]
@jacobsyentl can you please share screenshot of select option values in class config? and grid always shows the raw data!

**Comment by jacobsyentl** [comment]
**Care and use:**
![image](https://user-images.githubusercontent.com/9139261/59669223-1f80f380-91ba-11e9-9df3-afbea2fc06d1.png)

**Included materials:**
![image](https://user-images.githubusercontent.com/9139261/59669244-290a5b80-91ba-11e9-9c96-31c2e3f54265.png)

**Comment by jacobsyentl** [comment]
@dvesh3 I see what went wrong, the imported values do not match the values in the class definition.
Excuse me for not seeing that earlier.

Thanks for the help!
