### ISSUE TITLE
"Range" data type

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#4535]
# Feature Request

- [x] There is no existing issue regarding the same topic

### `Range`

Adding a new data type `Range` would allow to model attributes meant to hold two values. 

Examples include:
- weight for child diapers (6kg - 10kg)
- age for toys (2yr - 5yr)
- operational temperature (-30°C - 40°C)

etc.

Note: this is **not** the same as existing min/max values because they're used to **constrain** a single value, this is meant to **specify** min/max as a single property. We should still have min/max to constrain (lower end must be >= min, <= higher end, higher end must be <= max).

### `QuantityRange`

Same as above, with a (single) unit attached. Since all my examples actually include units, this makes more sense to have, but for completeness sake, I've included the plain `Range` type too.

**Comment by aarongerig** [comment]
Another type could be ...

### `DateRange`

... which returns a [`CarbonPeriod`](https://carbon.nesbot.com/docs/#api-period) object.

**Comment by Yivan** [comment]
Hello @aarongerig 
I like pretty much the idea to have new "range" data type for number and for dates.
Dates especially because this is a pain actually for project where you need to manage booking for instance ; )

Actually the work around are two fieds and check in the save of the model the value are coherent, if not send an error message. You can do it in preSave event.

**Comment by ITspirit** [comment]
Should also be supported within ClassifcationStore Quantity Values.

**Comment by brusch** [comment]
@dkarlovi @aarongerig Anyone willing to contribute this data-type? Shouldn't be too much effort. 
The GeoPoint data-type is quite similar, it also uses 2 columns for the store and query tables: 
https://github.com/pimcore/pimcore/blob/e464b003b51a92ebd7abc989883a1d3da34bebeb/models/DataObject/ClassDefinition/Data/Geopoint.php#L50

**Comment by aarongerig** [comment]
@brusch Sure, I'll give it a try.
