### ISSUE TITLE
Variants are not linked to the product

### ISSUE THREAD

**Issue by turgic** [pimcore/pimcore#4552]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no

Hello guys, I have a very specific problem on my side. I have 2 products with 2 different references. I tried to add one variant per product : 
```
$productVariant = new CoreShopProduct();
$productVariant->setActive(true);
$productVariant->setKey($supplier->getName());
$productVariant->setPublished(true);
$productVariant->setParent($product);
$productVariant->setType(AbstractObject::OBJECT_TYPE_VARIANT);
$productVariant->setSpecificPriceRules($this->createProductVariantPriceRule([]));
$productVariant->setReference($config['variantReference']);
$productVariant->setSuppliers([$supplier]);
$productVariant->setDelay($config['variantDelay']);
$productVariant->save();
```
When I do : `$variants = $product->getChildren([AbstractObject::OBJECT_TYPE_VARIANT]);`
For the product : 000000827 I have an array with variants : 
![Screenshot from 2019-06-20 18-43-21](https://user-images.githubusercontent.com/6445778/59862587-bc46bb00-938b-11e9-81ef-accbc365445a.png)

For the product : 3000325 I have an empty array : 
![Screenshot from 2019-06-20 18-47-26](https://user-images.githubusercontent.com/6445778/59862722-f748ee80-938b-11e9-9dc6-eaae2688a8fc.png)

I think is a bug, because for 2 differents products I have different behaviours

Can you take a look please ? Thx in advance.

**Comment by fashxp** [comment]
Hi,
could be many things ... cache, specific code, timing issues, ... need more insights to can answer that. 
First place I would check is DB if variants are added correctly. But please use our forum for such kind of questions https://talk.pimcore.org/.
If there is a general Pimcore problem, please come back here and create a new issue.

Thx.
