### ISSUE TITLE
Clear navigation cache in 'scheduledtasks'

### ISSUE THREAD

**Issue by yariksheptykin** [pimcore/pimcore#4555]
# Bug Report

Navigation cache is not invalidated when publishing pages via scheduled tasks. This behaviour cannot be reproduced in demo store as scheduled tasks don't seem to be set up there. 

### Expected behavior

Documents published by schedule appear in the website navigation automatically.

### Actual behavior

The page gets published but documents published by schedule do not appear in the website navigation automatically.

### Steps to reproduce

The following scenario illustrates the issue. The user creates a document without publishing it. Instead, publishing is scheduled as described in [the documentation](https://pimcore.com/docs/5.x/Development_Documentation/Tools_and_Features/Scheduling.html). When `./bin/console pimcore:maintenance -j scheduledtasks` is executed by a cronjob (CLI) the document is published as expected. However website [navigation](https://pimcore.com/docs/5.x/Development_Documentation/Documents/Navigation.html) still returns a list without a link to the newly published document due to navigation caching.

Pimcore version: 5.4.4

**Comment by yariksheptykin** [comment]
@fashxp , I would be interested in contributing MR if you could give me some pointers for getting started. How would you approach soving this issue?

**Comment by fashxp** [comment]
navigation as cache tags `output` and `navigation` ... 
so clearing cache tag `navigation` in the command should do the trick?

**Comment by fashxp** [comment]
or maybe `output` is even better, since publishing a document might not only affect navigation.

**Comment by brusch** [comment]
I'm wondering why this even happens ... 
The scheduler task, calls the `save()` method of the document which then also clears the cache, just the same as it would happen when you save a document in the admin user-interface. 
See: 
https://github.com/pimcore/pimcore/blob/08b6245bcc828321f7555faf37ea546ed4ab2633/lib/Maintenance/Tasks/ScheduledTasksTask.php#L68
https://github.com/pimcore/pimcore/blob/f288d6944a72c1e228b042d8e7d40901d77d19b2/models/Document.php#L474
https://github.com/pimcore/pimcore/blob/09258d8616b3f088b2829138fad821b12d70a38c/lib/Navigation/Builder.php#L59

I haven't got the time yet to try to reproduce the issue, but it really sounds a bit weird to me. 
Anyone else experiencing this issue?

**Comment by dvesh3** [comment]
yes, saving a document in admin & from scheduler task follows the same process of saving & clearing the cache. 

only diff is: 
`output` is a special tag which is cleared at shutdown (please see comments) https://github.com/pimcore/pimcore/blob/3c9534b776798ea37cf6cfda686d3b759b55b40c/lib/Cache/Core/CoreHandler.php#L709

And in shutdown, it skips cache cleanup **if PHP interface is CLI**
https://github.com/pimcore/pimcore/blob/ba74ed817976eec8ee65c2b26cbe49cab155b0d6/lib/Pimcore.php#L307

so it skips in case of scheduler task

@brusch can you explain why we have cli check for shutdown cache cleanup?

**Comment by yariksheptykin** [comment]
Thanks for fixing this @brusch . I was trying to come up with an automated test to reproduce this problem but it turned out to be non-trivial.
