### ISSUE TITLE
Pimcore 6:  sending newsletters does not work

### ISSUE THREAD

**Issue by Corepex** [pimcore/pimcore#4560]
# Bug Report

### Expected behavior
Pimcore sends the newsletter ...

### Actual behavior
If you click on "send Newsletter Now" it throws an error.
The error will not be shown to the user ... but if you check the logfile (newsletter-sending-output.log) you see an UndefinedMethodException. 

```php
Fatal error: Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getContainer" of class "Pimcore\Bundle\CoreBundle\Command\InternalNewsletterDocumentSendCommand". in /var/www/vendor/pimcore/pimcore/bundles/CoreBundle/Command/InternalNewsletterDocumentSendCommand.php:67
```

**Here is the point where the error occurs:**
https://github.com/pimcore/pimcore/blob/fdb493e84ad41e05d7790de4fc175f68e603c812/bundles/CoreBundle/Command/InternalNewsletterDocumentSendCommand.php#L67

**Pimcore Version**
Pimcore 6.0.0

### Steps to reproduce

just try to send an newsletter (it doesnt matter what address source adapter you use).

**Comment by AlternateIf** [comment]
looks like this is caused by the symfony constraint raise since which deprecated the ContainerAwareCommand. due to that \Pimcore\Console\AbstractCommand doesn't extend it anymore
