### ISSUE TITLE
Quicksearch throw error when using + character

### ISSUE THREAD

**Issue by tomseifert** [pimcore/pimcore#4562]
# Bug Report
Using the quicksearch with special characters e.g. a + will raise an exception.

### Steps to reproduce
* Go to "quicksearch"
* Type "calendar+" (from left to right) or any other existing object by using "+" character

> Timestamp: Mon Jun 24 2019 12:36:29 GMT+0200 (Mitteleuropäische Sommerzeit)
Status: 500 | 
URL: /admin/search/search/quicksearch?_dc=1561372589775
Method: GET
Message: An exception occurred while executing 'SELECT * FROM search_backend_data WHERE (( MATCH (`data`,`properties`) AGAINST ('calendar+' IN BOOLEAN MODE) ) AND type != 'folder')   ORDER BY ( MATCH (`data`,`properties`) AGAINST ('calendar+' IN BOOLEAN MODE) ) DESC LIMIT 50':

SQLSTATE[42000]: Syntax error or access violation: 1064 syntax error, unexpected $end

**Comment by brusch** [comment]
Unable to reproduce in latest release, probably because this issue was already solved some time ago, see #3942
