### ISSUE TITLE
Plugin/ObjectForm to easily create forms out of object data

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#457]
In 2014, I requested a generic way to create forms for object creation / update for the front-end.
@brusch replied that they'd be working on a plugin called ObjectForm which does work in such a way and would probably be done in summer 2015.
If it has been done and if it's somewhere, I'd like to see it in the core or as a plugin release.

Forum thread of 2014 with all details: https://www.pimcore.org/board/viewtopic.php?f=24&t=1784

Code example:
```
<?php
  $this->objectForm()->setObject(Object_Abstract::getById(123));
?>
<form action="<?= $this->objectForm()->getSaveUrl(); ?>" method="post">
    <label>Name</label>
    <?= $this->objectForm("myName", ["class" => "my-css-class"]) ?>

    <label>Date</label>
    <?= $this->objectForm("myDate"); ?>
</form>
```
Expected output:
```
<form action="/plugin/ObjectForm/save/generic/id/123" method="post">
    <label>Name</label>
    <input name="objectData[myName]" type="text" class="my-css-class">

    <label>Date</label>
    <input name="objectData[myDate]" type="date">
</form>
```

It just seems odd to create extra Zend Form instances to recreate object creation forms for the frontend which already exist in the backend.

**Comment by brusch** [comment]
This is nothing that should be here in the core issue tracker. 
Thanks for your understanding.

**Comment by Cruiser13** [comment]
Sorry, in the Contributing.md it's written that this is the place for Feature Requests. Where should I put this instead?
