### ISSUE TITLE
no inheritance after deleting a brick in objekt

### ISSUE THREAD

**Issue by Tandur** [pimcore/pimcore#458]
If you delete an assigned brick from an object, this brick will then not be inherited from parent objects.

Objekt Struktur:
- object A 
  - objekt B (child of A)
  - object C (child of A)
 
Steps to crete the error:
1) Assign a brick to B and set a value on a field in this brick.
2) Assign a brick of the same Type as in 1) to A and set a value on a field in this brick.
3) Delete the brick in B

Result:
A has a brick with the assigned value in the field.
B has a brick with NULL as value in the field.
C has an inherited brick from A.

Expectation:
B should inherited brick from A.

Reason:
The deletion of the brick in B, sets the value in DB-tables "object_brick_query_..." and "object_brick_query_..." to NULL, but leaves the rows in the DB.

Experimental solution:
After deleting the rows in the tables (and clearing the cache), the brick in B is inherited from A.

Request to developers:
The deletion of the brick in B should delete the rows in the tables, so that the inheritance is reactivated for the brick.

Greetings
Heiko Vollmann from Blackbit

**Comment by brusch** [comment]
@Tandur can you reproduce this problem using the latest build? (you can also use demo.pimcore.org)
I've just tried to reproduce the problem, but everything behaved as expected, see also my screen recording: 
[brick-example.zip](https://github.com/pimcore/pimcore/files/134189/brick-example.zip)

Thanks for your feedback!

**Comment by Tandur** [comment]
@brusch : I've reproduced your findings.
It's working as expected in 4.0.0-b4.
The bug seems to be present in 3.1.1 and already fixed in 4.0.0-b4. I will therefore wait for 4.0 to go stable and update the clients system. 

Thanks for checking and feedback.
Greetings Heiko

**Comment by brusch** [comment]
Thanks for your feedback!
