### ISSUE TITLE
[Improvement] Link color and translation for login screen.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4585]
Hello,

New customizations of login screen are really great to make user feel they are at home ! We use it a lot when presenting demo of Pimcore : )

Trying to customize the Pimcore 6 login screen, when "Invert Colors on Login Screen" is checked on the System Config, the link to regenerate the password stay in purple.
It would be nice to have it the same than the customized colors, because actually it make stange to have purple with a green color for the bouton for instance (our customized color for login screen).
(top notch would be a text area to fill some CSS code so the login page can be further customised without having to deploy an extension for this, but this is outside of the scope of this issue, but if you think it is great i am for it ; ) ).

Second point is the translation of "Login". In french "Login" is translated by "Identifiant", it is ok for instance a field "Login" where we fill the user name. But for an action to be logged it means nothing "Identifiant" in french.
Maybe a separate translation key would be great. Because actually all our french Pimcore user get "Identifiant" in the action button to log... We this new key a good translation could be done on poedit after.

I hope those two small improvments make sense to provide a better login screen ! And more catch eyes Pimcore demo's ; )

Thanks.

**Comment by Yivan** [comment]
Just for reference, on the same subject abilities to have a custom favicon: https://github.com/pimcore/pimcore/issues/4594

**Comment by brusch** [comment]
The `Login` translation key is only used on the login screen, so please feel free to change the translation for `fr` on POEditor.

**Comment by Yivan** [comment]
Thanks!
I just updated the translation on poedit (i was thinking it was used somewhere).
