### ISSUE TITLE
[Pimcore 6] PSR ContainerInterface does not support Parameter Fetch

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#4589]
Within pimcore6, the container gets injected as `Psr\Container\ContainerInterface`. This Interface does not know anything about the parameter bag. 
 
So the method `getParameter` is unknown to any IDE and code analyzers like phpstan:

https://github.com/pimcore/pimcore/blob/16c1d538462ca4b348aa447abd4ba0cc41d0242c/lib/Controller/Controller.php#L42

**Comment by brusch** [comment]
Added a check, cannot change type hint.
