### ISSUE TITLE
[Improvement] BO custom favicon settings

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4594]
Hello,

Actually favicon is hardcoded for BO.
(please see https://talk.pimcore.org/t/custom-favicon-for-backend/2016)

I think it would be great like colors and logo to be able to customize it.

Advantages are:
- More polished branding possible for end customer
- In case of multiple Pimcore instance, in the browser the tabs could be easily spotted (for developpers and for customer having multiple Pimcore)

Maybe a field could be added in the color/logo section of Pimcore settings in the GUI ?

Thanks.

**Comment by brusch** [comment]
Thanks your your ideas, currently I don't see the need for this, therefore I close the issue. 
But feel free to continue the discussion or vote for the issue.

**Comment by clarkedb** [comment]
This feature would be very welcome. The favicon is important to the company I am working with on a Pimcore project as part of their Appearance and Branding.

Currently we swap out the favicon after every upgrade by [changing the actual file in the 'vendor' folder](https://talk.pimcore.org/t/custom-favicon-for-backend/2016/2).

**Comment by brusch** [comment]
@clarkedb @Yivan  What about a PR? Would be accepted 😉
