### ISSUE TITLE
[Tests] Make Tests compatible to guzzlehttp/psr7:1.6.0

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#4595]
error message: `Header value must be a string or numeric but boolean provided.  `

**Comment by solverat** [comment]
@fashxp they reverted it in 1.6.1 (https://github.com/symfony/symfony/issues/32292). I don't think it's a good idea to typecast each server value as string since symfony browser accepts the https value as a true boolean type.

**Comment by brusch** [comment]
@solverat but they are reapplying it in 2.x so probably it's better to keep the change?
