### ISSUE TITLE
[Pimcore website] French version - Link missing or broken

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4597]
Hello,

I don't know where to post it, so i make it here. I hope i am right !
This issue concerns the Pimcore website, in french version:
https://pimcore.com/fr

I would like to report those difference on the FR pimcore site with EN and one bad link.

1- Bad link
This link don't work:
Ressources -> Pimcore vs Compitors
It work ok on EN version.

2- Missing links (not in FR, but present in EN)
Services -> Pimcore 4 LTS
Ressources -> Academy
Ressources -> Marketplace
Ressources -> Roadmap
(and there is Ressource -> Pimcore 4 LTS here, should be in Services as EN maybe)

Thanks!

**Comment by brusch** [comment]
Thanks for reporting! Forwarded this to our marketing crew.
