### ISSUE TITLE
Twig Rendering not working with v6

### ISSUE THREAD

**Issue by Siqu** [pimcore/pimcore#4601]
# Bug Report

### Expected behavior

The ```@Template``` annotation changes the renderer to Twig like in the documentation about Twig.
[Pimcore Documentation](https://pimcore.com/docs/5.x/Development_Documentation/MVC/Template/Twig.html)

### Actual behavior
The auto renderer always tries to render via php.

### Steps to reproduce

Ether on FrontendController Action level:

```@Template```

or on FrontendController level.
```
public function onKernelController(FilterControllerEvent $event)
    {
        // set auto-rendering to twig
        $this->setViewAutoRender($event->getRequest(), true, 'twig');
    }
```

**Comment by Siqu** [comment]
Current workaround for other people with the same problem:
Use the direct rendering inside the controller via $this->render

**Comment by dpfaffenbauer** [comment]
BTW: that is not a workaround, that is the proper solution.

**Comment by Siqu** [comment]
Shouldn't the documentation be updated then? ;) 
Currently the ```@Template``` it is the first explained way how to enable twig rendering.

**Comment by dpfaffenbauer** [comment]
documentation is a whole different thing. Since templating rendering is a Symfony thing, read that documentation on how it works.

But: Your issue is valid, since Pimcore offers this feature, it should work as well.
