### ISSUE TITLE
[Improvement] First day of week localized on calendars

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4602]
Hello,

Calendars on "date" field datatype doesn't seems localized (and other caldendar in the Pimcore UI)
For instance, in french, it should be Monday the first day of week, actually it is Sunday.
Is it extjs harcoded or can Pimcore handle this ?

Thanks.

**Comment by weisswurstkanone** [comment]
Sunday (0) is the default by extjs

**Comment by NiklasBr** [comment]
But it would indeed be nice if we could set Monday as first day of week (which is [ISO standard](https://en.wikipedia.org/wiki/ISO_week_date)) and in Sweden, like in France, it is the common way of thinking of the days of the week.

**Comment by Yivan** [comment]
Yes the issue was aboyt adding a config param to allow to choose the fisrt day of week (with monday and sunday, i think we covers most case).
It cannot be a setting a the datatype date level, because calendars are use everywhere on pimcore. It should be a global settings. I think two possibility:
- automatically based on the locale of the currently logged user (i don't know if extjs can set the first day of week according to a local like "fr" and "fr_FR", or maybe ot can be resolved in PHP to find first day of week depending a locale) : this the cleaner way
- or another way, adding a global (system settings) + role/user (will inherit of role param) parameter to set it

**Comment by Yivan** [comment]
Thanks for the fix, monday is better than sunday as default yes!
