### ISSUE TITLE
Filter on size is not working in Assets List

### ISSUE THREAD

**Issue by SameerPCore** [pimcore/pimcore#4607]
# Bug Report
In assets list filter on size column is not working, when  user is trying to apply filter on size column the error message is coming  

### Expected behavior
The Filter should be applied successfully and data should be filtered as per the entered criteria  
### Actual behavior
As soon as user enters data and apply the filter sql error is coming
### Steps to reproduce
-->Login into Pimcore advance demo
-->Go to Assets tab
-->Click on any folder which has assets and then select list view type
-->Click on the down arrow of size column and go to filter menu option and enter any value and press enter.
-->Boom! Error pop up is there. 

### Code example
```php
// your code
```

# Feature Request

**Comment by weisswurstkanone** [comment]
Disabled filter for now as size is calculated on the fly for the current list page.
