### ISSUE TITLE
LibreOffice conversions as a maintenance job

### ISSUE THREAD

**Issue by kubaplas** [pimcore/pimcore#461]
Hi,

I would like to propose a change (or an addition) in the way Pimcore handles docx/xls/ppts previews/pdf conversions. I think it should be done outside application - in the maintenance, run by a cron.

Why?
1. Server configuration issues - LibreOffice needs a home folder to run but in most cases, web server is executed under a unprivileged user (www-data, nginx, nobody, etc) which doesn't have it's own home folder. It can be solved either by upgrading those users to "regular" user or by switching server and php to run as "regular" user. Unfortunately, both of the ways can be considered as a security issue.
2. Performance issues - now, the conversion has to be done during upload or when the preview/thumbnail is requested, which can result in slow server response on those actions.

I'll be glad to hear Your opinions on this issue. Also, I could implement it as I'm using this feature a lot in my projects.

**Comment by ThomasKeil** [comment]
This is by the way also a huge performance issue with Photoshop or EPS files.

We have a plugin ready that modifies the thumbnailing process and uses a queue for creating those thumbnails and returns a dummy image in the meantime. 

If anyone is interested in that please contact me.

**Comment by frithjof** [comment]
hey thomas,
this sounds nice ... you have a public repo for this plugin?

**Comment by brusch** [comment]
Fixed by 47f2e3fa2c39e110e93c14e32b2b2f20c1c36307
Related to: #3974
