### ISSUE TITLE
PC 6.0.1 install fails because of SensioFrameworkExtraBundle v5.4.0

### ISSUE THREAD

**Issue by gadget60** [pimcore/pimcore#4613]
A fresh install of PC 6.0.1 fails since SensioFrameworkExtraBundle 5.4.0 has been released a few hours ago:

`Fatal error: Uncaught ErrorException: Warning: Declaration of Pimcore\Bundle\CoreBundle\EventListener\LegacyTemplateListener::onKernelView(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent $event) should be compatible with Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelView(Symfony\Component\HttpKernel\Event\KernelEvent $event) in /workspace/foo5/vendor/pimcore/pimcore/bundles/CoreBundle/EventListener/LegacyTemplateListener.php on line 17`

**Comment by fashxp** [comment]
duplicate https://github.com/pimcore/pimcore/issues/4614

**Comment by gadget60** [comment]
You've been 2 minutes faster :-)
