### ISSUE TITLE
Possibility for marking redirects as inactive (yes/no)

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#462]
When redirect is marked as inactive than the system would not match it while routing.
Useful for temporary (in days) disabling.
Useful for tests. Inactivate -> look whats happening -> enable again if needed.
Saves administrators time.

**Comment by Yivan** [comment]
I vote for this too, because it is often need for testing/debug purpose.
Same idea can be apply for routes too.
Actually only way is to delete the line and it is not user friendly (several field to fill in again to restore it).

**Comment by brusch** [comment]
![image](https://cloud.githubusercontent.com/assets/142037/15364101/7d93aa88-1d1b-11e6-9955-117ce5603d42.png)

build 3786
