### ISSUE TITLE
Symfony 4.3 Changes on EventDispatcherInterface

### ISSUE THREAD

**Issue by Siqu** [pimcore/pimcore#4624]
The function definition for dispatch changed. The first parameter of dispatch is now the Event object.
When called otherwise a silenced deprecation error is triggered. This leads to almost non readable log when developing because the log is full of those warnings.

If this is not already handled by one of the devs, i will gladly change it myself and create a merge request for the change.

**Comment by brusch** [comment]
@Siqu Please keep in mind that we still have to support Symfony 3.4 as well as the other 4.x versions.

**Comment by Siqu** [comment]
@brusch hmm, the only way i could think of would be a check before the call which symfony version would be used and then call the function depending on the version &#x1F914;

Just made a quick check of the code, the calls are made via 
```
\Pimcore::getEventDispatcher()->dispatch(...);
```
or via the DependencyInjection
```
EventDispatcherInterface $eventDispatcher
```
There are currently 241 occurrences of those calls.

I am not a really big fan of adding a if directive to all those calls, do you have an idea how it could be cleaner to change it, or should i just downgrade to symfony 4.2?

**Comment by Siqu** [comment]
One way could also be to create a Custom EventDispatcher which extends the Symfony one and handles the check, then there would only be one place to change it.

**Comment by dpfaffenbauer** [comment]
or better leave it as it is and wait for the transition to only Symfony 4.3 or Symfony 4.4 | 5.0

**Comment by Siqu** [comment]
Then i'm going to downgrade to a previous version ;). 

But when it's time to perform the change i am glad to help.

**Comment by dpfaffenbauer** [comment]
why? what bothers you about the deprecation notice?

**Comment by Siqu** [comment]
For very database extensive tasks the system slows down extremely because of all the event calls beeing logged to the filesystem. I know i can increase the log level to ommit those warnings but in dev mode i still want the info messages sometimes.
