### ISSUE TITLE
[bug]Upgrade from 5.8 to 6.0.x error;Undefined class constant 'MAINTENANCE'

### ISSUE THREAD

**Issue by Thommass** [pimcore/pimcore#4633]
# Bug Report

### Actual behavior
Getting error;

Undefined class constant 'MAINTENANCE'
![image](https://user-images.githubusercontent.com/28269645/60729036-06aa6900-9f42-11e9-9bf2-1f509d8e324e.png)

### Steps to reproduce
5.8 pimcore installation update to 6.0.x

**Comment by fashxp** [comment]
Does this CleanupListener come from Pimcore (I guess not) or from your Project?

**Comment by Thommass** [comment]
It comes from Pimcore. I cannot figure out if aws-sdk is the problem.

**Comment by GALCF** [comment]
I came across the same problem just now, but the trace shows that the error comes from `FormBuilderBundle\EventListener\Core\CleanUpListener`

This seems to be a [FormBuilder](https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/src/FormBuilderBundle/EventListener/Core/CleanUpListener.php#L33) incompatibility issue registering a maintenance task.

**Comment by GALCF** [comment]
FYI: The pull request for v6 compatibility is still in review: dachcom-digital/pimcore-formbuilder#176
