### ISSUE TITLE
[Feature request] Semantic versioning

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#4647]
# Feature Request

Fully commit to use [Semantic Versioning](https://semver.org/).

## Feature description

With the introduction of Composer support in 5.x updating is much easier from a technical perspective, but it is still not clear if we can trust minor and patch versions fully, for example #4645 which has some nice changes but is a BC break and appears soon to be ready to merge.

From my perspective it would add a lot of confidence in releases which are tagged as minor and patches if Pimcore promises not to add BC breaking changes without either:

 * Incrementing the major version number, or
 * Adding a compatibility layer until the major version number can be increased, or
 * Waiting with these changes until you feel a new major version is warranted, for example committing these to a 7.x branch while 6.x is the current stable release.

**Comment by dpfaffenbauer** [comment]
+:1

**Comment by julmot** [comment]
Can't believe no one from the Pimcore team took the responsibility for this yet :cry:
https://semver.org/#why-use-semantic-versioning

**Comment by brusch** [comment]
Starting with 7.0 we're going to fully commit to semver and there will be guidelines similar to https://symfony.com/doc/current/contributing/code/bc.html

For the 6.x branch we promise to be as close to semver as possible.

**Comment by julmot** [comment]
👍 👍 👍 Thanks @brusch!

![ezgif-3-d9cd9cc51de0](https://user-images.githubusercontent.com/8310677/80184184-64f82380-860a-11ea-8b6f-c8c2f5536d8d.gif)
