### ISSUE TITLE
Update whoops lib to support PHP 7

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#465]
For example I had problem when PHP7's \Error object was thrown and the library expected \Exception as parameter in one of the methods part of the library.
That happened on Pimcore 3.1.1

**Comment by brusch** [comment]
pimcore 4 uses already always the latest version of whoops, see: https://github.com/pimcore/pimcore/blob/master/composer.json#L47
'composer update' is automatically executed before every build of pimcore.
