### ISSUE TITLE
[Pimcore6] Fix TODOs

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#4660]
Cleanup Pimcore 6 TODOs
https://github.com/pimcore/pimcore/blob/08b6245bcc828321f7555faf37ea546ed4ab2633/lib/Routing/RedirectHandler.php#L55
https://github.com/pimcore/pimcore/blob/08b6245bcc828321f7555faf37ea546ed4ab2633/lib/Routing/RedirectHandler.php#L70
https://github.com/pimcore/pimcore/blob/83954a2ccc546be919bd8d0b30f8224907a7c849/lib/Document/Tag/TagHandler.php#L282
https://github.com/pimcore/pimcore/blob/4c986d60d890898e466533a21dfd29bde2acb9f6/lib/Document/Renderer/DocumentRenderer.php#L79
https://github.com/pimcore/pimcore/blob/4c986d60d890898e466533a21dfd29bde2acb9f6/lib/Analytics/Google/Tracker.php#L112
https://github.com/pimcore/pimcore/blob/4c986d60d890898e466533a21dfd29bde2acb9f6/lib/Templating/Helper/Placeholder/ContainerService.php#L71
https://github.com/pimcore/pimcore/blob/877413a3d6a454f4827139460fc9bf29e4384794/bundles/EcommerceFrameworkBundle/IndexService/Config/AbstractConfig.php#L113
https://github.com/pimcore/pimcore/blob/877413a3d6a454f4827139460fc9bf29e4384794/bundles/EcommerceFrameworkBundle/IndexService/Config/AbstractConfig.php#L232
https://github.com/pimcore/pimcore/blob/877413a3d6a454f4827139460fc9bf29e4384794/bundles/EcommerceFrameworkBundle/IndexService/Config/AbstractConfig.php#L247
https://github.com/pimcore/pimcore/blob/877413a3d6a454f4827139460fc9bf29e4384794/bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php#L128
https://github.com/pimcore/pimcore/blob/c62924ca5c3d0c482a71097cb0231aff143208d6/bundles/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/AbstractAnalyticsTracker.php#L35
https://github.com/pimcore/pimcore/blob/5940f28f12e2b08ab48fafa915eab2205e497321/bundles/EcommerceFrameworkBundle/DependencyInjection/Configuration.php#L910
https://github.com/pimcore/pimcore/blob/c213b67b781feeaa0fa84de8f5121daada02e94c/lib/Templating/Renderer/TagRenderer.php#L92
https://github.com/pimcore/pimcore/blob/e2515cdbfc2548f46d1e123b4f1efbf35ef337c7/lib/Composer.php#L139

https://github.com/pimcore/pimcore/blob/2c3a5786646c5ac968b5aec679680df5a08e3d3f/bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js#L267

https://github.com/pimcore/pimcore/blob/4b93d66fa1238ffedb1f3a5e0420eb81da48572c/bundles/AdminBundle/Resources/public/js/pimcore/document/tags/relation.js#L329

https://github.com/pimcore/pimcore/blob/957ce78871f7078f555853f36d09f4d79c00f0f5/bundles/AdminBundle/Resources/public/js/pimcore/document/tags/relations.js#L518

some classes in path `pimcore/bundles/AdminBundle/Resources/public/js/pimcore/object/tags/` e.g.
https://github.com/pimcore/pimcore/blob/c74555e89ae59bd76ab576639b67426b23724837/bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js#L740

some classes in path `pimcore/bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/` e.g.

https://github.com/pimcore/pimcore/blob/dfcbf841a26c08d3649798099b53e75909dc36e0/bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToManyObjectRelation.js#L245

**Comment by dpfaffenbauer** [comment]
I also found some in the JS files, maybe you can check them as well

**Comment by blankse** [comment]
Here is also a Pimcore 6 TODO:
https://github.com/pimcore/pimcore/blob/5940f28f12e2b08ab48fafa915eab2205e497321/bundles/EcommerceFrameworkBundle/DependencyInjection/Configuration.php#L422
