### ISSUE TITLE
[Feature request] Focus and primary indicator

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#4663]
# Feature Request

![Skärmbild (87)](https://user-images.githubusercontent.com/279826/60967759-b48b8e00-a31b-11e9-94bf-f7ad8c267efa.png)

## Feature description

It is not clear which input element has focus in many positions, and it is not clear which is the primary button, in the administration interface. For example the *Add Object* modal dialogue, it is possible to navigate the items with the Tab key, but the highlight is barely visible in the text field and not at all in the buttons.

The same issue exists in the *Edit* screen on objects, the first *Save* button gets slightly darker when it has focus, but the second *Save & Publish* does not.[1]

It would be very nice to have a clear focus ring or significant hue/lightness change in the interface for the currently focusable item

[1] Footnote, it is also a little odd that "Save" and "Save & Publish" are effectively the only places in the UI with capital letters. All other primary action buttons are following the same title capitalisation rule. Which is odd because words in capital letters are [generally regarded as slower to process and harder to read](https://github.com/humanmade/hm-pattern-library/issues/75#issuecomment-235672885). :)

**Comment by ckemptner** [comment]
+1 for your Footnote ;)

**Comment by brusch** [comment]
+1 but you know, designers ... ;-)

**Comment by NiklasBr** [comment]
This is still relevant

**Comment by NiklasBr** [comment]
This is still relevant, apparently a designer has to be involved here ;)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Comment by NiklasBr** [comment]
Nothing has changed on your end @fashxp, in fact doing this has become a legal requirement in many places across the globe (EU, EEA, USA, Australia, ...).

**Comment by fashxp** [comment]
It doesn't seem to be a significant problem, as for more than 4 years nobody has found the urgency to fix it. 
We will consider that in the new UI and as mentioned, we are still happy to merge PRs.

**Comment by NiklasBr** [comment]
Wow....
