### ISSUE TITLE
Replace / overwrite files via WebDAV

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#4669]
Currently it is not possible to update an asset via WebDAV, is it? If you upload a file with the same file name you get the error "Duplicate full path [ <path> ] - cannot save asset". This is caused by https://github.com/pimcore/pimcore/blob/7034964c93652edd2afc1b0a358297d2bcf4785c/models/Asset/WebDAV/Folder.php#L118-L137

Or is there another way to update an existing asset?
(Removing and reuploading of course is no option as references to the asset get lost)

**Comment by brusch** [comment]
Just tested with Cyberduck, works just as expected, see: 
[24-07-_2019_16-40-54.zip](https://github.com/pimcore/pimcore/files/3427358/24-07-_2019_16-40-54.zip)

**Comment by BlackbitNeueMedien** [comment]
Hmm, I tested with the built-in sabre/dav to upload the same file twice and that gives an error. I think changing an existing file (as @brusch did in https://github.com/pimcore/pimcore/files/3427358/24-07-_2019_16-40-54.zip) is handled differently than uploading a file with the same file name.

**Comment by brusch** [comment]
@BlackbitNeueMedien Update is different from creating a new file ... 
https://github.com/pimcore/pimcore/blob/eadf06784ab56c5c42ba470a4a80c4b09f5f2576/models/Asset/WebDAV/File.php#L115
https://github.com/pimcore/pimcore/blob/c62924ca5c3d0c482a71097cb0231aff143208d6/models/Asset/WebDAV/Folder.php#L118

It's probably a question of how the default behavior should be ... and how the client implements replacing.

**Comment by BlackbitNeueMedien** [comment]
Ah ok, than this is some kind of intended behaviour.

In our case we have customers with separate media servers where assets are stored. They want to use these assets in Pimcore. I thought of using Pimcore's WebDAV interface for this but then files would have to be "uploaded" from the file server to the WebDAV drive / folder. And then the problem with replacing comes into play.

Another solution would be to mount the media server as NFS on the Pimcore server but how to integrate the folder then? When you periodically use "import from server" Pimcore always creates duplicates instead of overwriting existing files.
Is there any way to integrate a file system folder to Pimcore's assets without writing an own import script / plugin?

The only option I see at the moment is to import all assets from the media server to Pimcore and replace the media server by using the WebDAV interface. This certainly sounds nice but is hard to explain to big companies who think of Pimcore being only used by the company's online shop department while the print and catalogue department continues to use a whole set of other tools.

**Comment by brusch** [comment]
I think in your case the easiest would be indeed a custom sync script, that syncs the assets from the NFS mount into Pimcore. You can even think about using symlinks from `web/var/assets/` to the NFS share (if high-performance). 
The sync script should be quite easy.
The deluxe option would be to use Inotify in combination with a queue that calls the import script on every change.

**Comment by BlackbitNeueMedien** [comment]
Ok, I think we will create a plugin for this task...

Nevertheless, what do you think of a checkbox "Overwrite existing files" for "Add assets > Import from server"?
This could be evaluated in https://github.com/pimcore/pimcore/blob/1b5820d0b17e9967588d1367fe818d721d616b99/bundles/AdminBundle/Controller/Admin/AssetController.php#L2110-L2143

**Comment by brusch** [comment]
That would be fine for me.
