### ISSUE TITLE
routing annoation don't work anymore

### ISSUE THREAD

**Issue by LukiLuko** [pimcore/pimcore#4671]
Hello,

I've got a problem since upgrading pimcore on 6.0.2 not in 6.0.0....
My injection dependance in a controller with annotation route ( with id param) don't `work.`
See the exemple below, 
i can't get this obejct Company with the rout .../{id], return null.

`/**
     * @Route("/changeCurrentCompany/{id}", name="change_current_company", options={"expose"=true})
     *
     * @param Company $company
     * @param Request $request
     * @return JsonResponse
     */
    public function changeCurrentCompanyAction(Company $company, Request $request)
    {`

I've got this in service.yml

` AppBundle\Controller\:
        resource: '../../Controller'
        public: true
        autowire: true
        tags: ['controller.service_arguments']

Pimcore\Model\DataObject\Company:
        autowire: true
        public: true`

Ive u got an issue ?

thanks in advance

**Comment by brusch** [comment]
For me this is working fine ... 
```php
<?php

namespace AppBundle\Controller;

use Pimcore\Controller\FrontendController;
use Symfony\Component\Routing\Annotation\Route;

class BernieController extends FrontendController
{
    /**
     * @Route("/bernie/test/{id}")
     */
    public function testAction()
    {
        dump('foo');
        exit;
    }
}


```

In future, please use our forums/Gitter first ;)
