### ISSUE TITLE
Reload DataObject on Save

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#4678]
Some Data Tags are changed on save (CalculatedValue) or even some others are changed from EventListeners during the update event. To show this change in the UI, the user has to reload the DataObject, when in fact, it would be possible to return the result of `/admin/object/get` after save and "rebuild" the UI with the data of the response where each Data Tag is responsible of handling its new data.

In guess that should be quite easy to handle right?

this is actually related to the PR #3061 but I haven't found any issue regarding it.

**Comment by florian25686** [comment]
Hello @brusch this issue occurs again and again by customer asking for a solution. If they update a dataobject they manually need to reload the page.
Is it possible to accelerate the process for fixing this issue somehow?

**Comment by brusch** [comment]
@florian25686 yep of course: you can either implement it yourself and create a PR for us or alternatively you can sponsor the development of this feature 😊

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
