### ISSUE TITLE
Empty minified_javascript_core JS returns status code 200 instead of 404

### ISSUE THREAD

**Issue by sknuell** [pimcore/pimcore#4686]
### Expected behavior
When the main minified JS for the CMS UI cannot be loaded via the script proxy a meaningful  HTTP status code (e.g. 404) is returned and an error is logged. 

/admin/misc/script-proxy?scripts=minified_javascript_core_{hash}.js&_dc={hash}

### Actual behavior

When the main minified JS for the CMS UI cannot be loaded via the script proxy a 200 HTTP status code is returned with the file being empty. That leads to a broken UI after login and the reason for this is quite hard to debug, because of the 200 status code and only shows in form of follow up errors in the browser console

### Steps to reproduce

- Make minified_javascript_core_{hash}.js e.g. not readable by web server
- login in and see that UI is not loaded with errors showing in the browser console

Btw, are there any plans to get rid off the script proxy and the lazy generation of the core JS?

**Comment by MathewSalazarTS** [comment]
I'm actually having this issue today...How was this resolved?
