### ISSUE TITLE
Dotenv with Symfony 3.4 doesn't work anymore

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#4692]
# Bug Report
After update to Pimcore v6.0.3 with Symfony 3.4 and .env File the System doesn't work anymore.

Following error in the log:
`PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\\Component\\Dotenv\\Dotenv::loadEnv() in /var/www/pimcore/vendor/pimcore/pimcore/lib/Bootstrap.php:180`

The loadEnv method exists only in Symfony >4.2

**Comment by brusch** [comment]
Damn, thanks for reporting - 6.0.4 is on it's way.

**Comment by pierrealexaline** [comment]
I've the same here : 
Call to function method_exists() with 'Symfony\\Component…' and 'bootEnv' will always evaluate to false.
Call to an undefined method Symfony\Component\Dotenv\Dotenv::bootEnv().

**Comment by pierrealexaline** [comment]
symfony 4.4

**Comment by brusch** [comment]
@pierrealexaline please open a new ticket if you're having issues with Symfony 4.4.
Please also include a complete guide how to reproduce the issue. 
Thanks!

**Comment by jdreesen** [comment]
There's no `Dotenv::bootEnv()` in Symfony 4.4, [it was added in Symfony 5.1](https://github.com/symfony/symfony/blob/ba4d57bb5fc0e9a1b4f63ced66156296dea3687e/src/Symfony/Component/Dotenv/CHANGELOG.md#L7).

Also, Pimcore nowhere tries to call it.
