### ISSUE TITLE
[Bug] Command pimcore:thumbnails:image return an error.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4694]
Hello,

The console command `pimcore:thumbnails:image` returns an error:
`Unable to display the estimated time if the maximum number of steps is not set.`

(for information all thumbnails cache where cleared, maybe this is related...)

It is an error coming from symfony console: https://github.com/symfony/console/blob/master/Helper/ProgressBar.php#L508

**Comment by brusch** [comment]
Unable to reproduce: 
```
bernie@pimcore:~/demo-basic$ ./bin/console pimcore:thumbnails:image -s
 40/40 [============================] 100% ( 1 sec/1 sec ) 24.0 MiB: generated thumbnail: web/var/tmp/image-thumbnails/examples/panama/image-thumb__24__pimcore-system-treepreview/img_0410.pjpegbernie@pimcore:~/demo-basic$ ^C
bernie@pimcore:~/demo-basic$
bernie@pimcore:~/demo-basic$
bernie@pimcore:~/demo-basic$ ./bin/console pimcore:thumbnails:image
   7/897 [>---------------------------]   0% ( 1 sec/2 mins) 24.0 MiB: generated thumbnail: web/var/tmp/image-thumbnails/portal-sujets/image-thumb__4__exampleFrame/slide-01.jpeg^C
bernie@pimcore:~/demo-basic$
```

**Comment by dpfaffenbauer** [comment]
@Yivan @brusch this can only happen if you don't have any images or no thumbnails in Pimcore. so a rare case in my opinion

**Comment by brusch** [comment]
🤦‍♂️ok, not even worth to think about it then, thanks for clarifying!

**Comment by Yivan** [comment]
Hum yes it was an empty projet (base skeleton) when i make the test.
Sorry about the noise.
