### ISSUE TITLE
Cannot prepare index for a specific tenant

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#4700]
# Bug Report
When executing the indexservice queue preparation for a specific tenant, then an exception occurs that the session moduls's init settings cannot be changed after the headers were already sent.

I think we already had that message in the past, not sure how to get rid of it. Might this be something application-specific, or is it related to the architecture of the index service / the ecommerce factory?

![image](https://user-images.githubusercontent.com/16687355/61272412-62c58680-a7a7-11e9-896d-c080c0d8e965.png)

![image](https://user-images.githubusercontent.com/16687355/61272465-84267280-a7a7-11e9-9661-65a1579cd5a3.png)

**Comment by andreas-gruenwald** [comment]
Executing 
``` 
Factory::getInstance()->getEnvironment();
``` 
in the ProcessQueueCommand before the IndexUpdater is called would work.

**Comment by fashxp** [comment]
cannot be reproduced ... maybe already fixed with recent changes, or something specific to your application.
