### ISSUE TITLE
Setting PIMCORE_ENVIRONMENT in dotenv file not working anymore

### ISSUE THREAD

**Issue by bramstroker** [pimcore/pimcore#4703]
# Bug Report
- [X ] This is not a security issue / vulnerability -> use [this form](https://pimcorehq.wufoo.com/forms/pimcore-security-report/) instead
- [ X] Behavior is reproducible on http://demo-basic.pimcore.org/admin/ (admin/demo)
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...)
- [X ] You're not able to fix the problem yourself and send us a pull request instead of an issue.
- [X ] There's no existing ticket for the same issue
- [X ] Remove unused sections from below and this bullet points

### Expected behavior
Pimcore is run in with the environment I define is my DotEnv file

### Actual behavior
Pimcore environment is set to `prod`

### Steps to reproduce
Add the following to `.env` file in pimcore root folder:
```
PIMCORE_ENVIRONMENT=dev
```

Add a breakpoint to line after `prepareEnvVariables` call in `Bootstrap.php` and inspect `$_ENV` contents. `PIMCORE_ENVIRONMENT` should be `dev` but is `prod`.

This is an issue with Pimcore 6.0.4. In pimcore 6.0.1 everything was working as expected.

### Possible cause of issue.
In one of the latest [commits](https://github.com/pimcore/pimcore/commit/4622d0198ca4d7539644754c5b7e2945be6bb740#diff-0f24a255d82c3b7037c4b0bbb26470a7) `$_ENV['PIMCORE_ENVIRONMENT']` is set hard in the code before `$dotEnv->loadEnv()` is called. DotEnv by default does NOT override existing environment variables, so there is no way to override it with the dot env file anymore.

**Comment by brusch** [comment]
@bramstroker thanks for reporting! 
Can you please test this patch: https://github.com/pimcore/pimcore/commit/f0abc8c5ca78216d1caf228adac337b6dbc9617a.patch ? 

Thanks for a quick feedback!

**Comment by bramstroker** [comment]
@brusch Yes this patch is working correctly for me. Thanks for the quick resolution!

**Comment by rajesh17692** [comment]
Hello Can anyone guide me on how the patch can be installed

**Comment by NiklasBr** [comment]
@rajesh17692 While waiting for the patch to be implemented into Pimcore, you can install [Composer Patches](https://github.com/cweagans/composer-patches) and then follow the instructions for [External patches](https://github.com/cweagans/composer-patches#using-an-external-patch-file) (or download it and use the instructions for internal).
