### ISSUE TITLE
[Improvement] No notice errors in back-office and Pimcore code + activate E_ALL in debug mode

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4708]
Hello,

I have seen phpstan is on his way for Pimcore test suite, kool !
On our side, we are trying to enforce code quality, by setting `error_reporting(E_ALL);` for bundles in the `src` directory.

We cannot enforce this setting globally including Pimcore because Pimcore send some notice errors in back-end.
It would be nice a global pass could be done to eliminate all those notice errors.
For instance `$limit` here could not be defined (empty skeleton, just open the BO and check for error 500 in browser dev console): https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L196

![image](https://user-images.githubusercontent.com/9025839/61337718-db275880-a836-11e9-9946-ddc6b697e1fc.png)

There is more (i didn't check everywhere... the recycle bin for instance, etc.)

Idea behind this, is to be able to develop on the Pimcore GUI with notice errors being reported.
It will make Pimcore code more robust too.

The final objective is to be able to change this line: https://github.com/pimcore/pimcore/blob/31fd11bcf370ab92b6539b68fc88da53cfec0e12/lib/Pimcore.php#L73 by `error_reporting(E_ALL);`
This way people developping Pimcore extension would produce better code too.

**Comment by Yivan** [comment]
I ran a phpstan level 1 to report undefined variables, here is the file:

[report-notices.txt](https://github.com/pimcore/pimcore/files/3403904/report-notices.txt)

Not so many ; ) There is false report for sure, and some missing too. But will be a good cleanup.

**Comment by brusch** [comment]
Please directly create a PR, we're not going to work through endless lists here. 
Thanks for your understanding & looking forward to the first PRs :)

**Comment by Yivan** [comment]
@brusch 

Great that you are open to a PR for this ! I really think it is a good new feature which will improve code quality.

Ok we will try to proceed in this order, if it is ok for you:
- I will fix legitimate PHPStan undefined variable
- I will manually check: backend Pimcore, demo website (php), demo website (twig), demo website (ecommerce). Clicking eveywhere to use as much as possible functionnalities to spot notice errors. I will manually check bin/console commands (including command for ecommerce).
- I will make a PR (i think as it will take some times, maybe merge problem could occurs, so you will have to fix them)
- You will ran the unit test you usually ran in E_ALL mode, and fix latest notices if there is
- You will change Pimcore code so in Debug mode we can chose the error level (E_ALL or E_ALL & ~E_NOTICE, to discuss which default value... E_ALL would be great so when new code Pimcore code are injected we saw directly if working, but could break BC or simply indicate in update doc that this can be revert to E_ALL without notice).
- You will change the unit test code so it ran in E_ALL.

Do you think it is good ?
Idea is after this to avoid in the future code updates of core Pimcore the injection of new notice errors and that bundle developpers (at their choice) could activate E_ALL and fix their bundles (i think to the most famous/used one, like CoreShop form @dpfaffenbauer, Formbuilder @solverat , etc.).

People can join to the discussion, so this is constructive ! : )

Thanks.

**Comment by dpfaffenbauer** [comment]
I am pretty certain that CoreShop doesn't produce any notices or at least just a few, since it's PHPStan tested on LVL2, and that catches many of those issues.

But yes, once Pimcore is fixed, I can test CoreShop as well.

**Comment by brusch** [comment]
@Yivan I'm fine with that, go ahead! 
Maybe just one more thing: I think it would make sense split this topic into smaller parts so that the PRs can be easily reviewed and to avoid too much conflicts. Thanks!
