### ISSUE TITLE
Close tabs of sub-trees of deleted objects

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#4717]
Steps to reproduce:
1. Create object "in-root"
1. Create object "sub" under "in-root"
1. Ensure both objects are opened
1. Delete object "in-root"

Tab of "in-root" gets closed but tab of "sub" stays open. When you press "Save" in "sub" tab, there is an error.
Would be cool if PImcore would also close tabs of objects below the deleted one. This should be possible by closing all tabs whose object's path has the deleted object's path as prefix (deleting /a closes objects with paths /a, /a/b, /a/b/c etc.)

**Comment by brusch** [comment]
see #4748
