### ISSUE TITLE
[bug] On the GUI, filter in gridlist need sql alias if object class and objectbrick have same column name.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4721]
Hello,

We ran into an error on the gridlist on the backend GUI Pimcore.

Using an object class and an objectbrick having both a datatype (text for instance) with the same name ('wording' in our case) bring an SQL error because mysql don't manage to know how to act.
Alias should be used in the sql construction to desambiguate the sql request.

![image](https://user-images.githubusercontent.com/9025839/61411673-2731d600-a8e7-11e9-8256-7cc95eda8772.png)

How to reproduce, on the Pimcore backend GUI:
- create an object class, add a datatype text named 'wording' and a datatype objectbrick
- create an objectbrick having a datatype text named 'wording' too
- associate the objectbrick to the class
- create some object class instances and go in the grid list mode in the parent folder
- add 'wording' field of the class and 'wording' field of the object brick to the grid as colum to display
- try to filter on those...

Thanks.

**Comment by fashxp** [comment]
not reproducible anymore
