### ISSUE TITLE
Tag filter in assets search

### ISSUE THREAD

**Issue by jones1008** [pimcore/pimcore#4725]
# Bug Report

### Expected behavior
Being able to search for tags lower than the 5th level.

### Actual behavior
ext-all.js throwing an error in the console and no results are shown.
```
too much recursion
```
Furthermore the admin site has to be refreshed when closing the "Search Asset"-panel after the error occured, because the admin site isn't usable afterwards.
The same error occurs when using the "Search Documents" or "Search Objects"-panel.

### Steps to reproduce
1. create tags down to the 5th level:
![grafik](https://user-images.githubusercontent.com/25104859/61447482-52e9a600-a951-11e9-87b8-121570557b9a.png)
2. open the "Filter for Tags" in "Search Assets"-panel
3. search for the tag on the 5th level:
![grafik](https://user-images.githubusercontent.com/25104859/61447769-e91dcc00-a951-11e9-9432-40cb8570dabe.png)

**Edit:** I just noticed that the error only occurs when the tag-tree wasn't opened before. And it fails when opening the 3rd level.

**Comment by brusch** [comment]
For more information see also #4797
