### ISSUE TITLE
[Asset] Possibility to delete image features

### ISSUE THREAD

**Issue by elements-team** [pimcore/pimcore#4728]
# Report
After my [intial issue](https://github.com/pimcore/pimcore/issues/4625) (https://github.com/pimcore/pimcore/issues/4625) was fixed, I quickly came to realize that I forgot to mention the feature images in the description.

So, while focal points now work fine, the feature images are still displayed. Could you please remove/hide them when not needed?

### Expected behavior
If all focal points of an image are removed, the image features are removed too. Or at least stay hidden after one toggles the image features, so that they are invisble.

### Actual behavior
Removing all focal points will still show the image features after saving & reloading the asset.

### Steps to reproduce
Pretty much the same steps as in the referenced issue.

**Comment by brusch** [comment]
Image features are completely independent from focal points, so we just need the possibility to delete the image features.
