### ISSUE TITLE
Objects with multi language field collection save problem

### ISSUE THREAD

**Issue by manuelkleinert** [pimcore/pimcore#4732]
# Objects with field collection memory problem

Pimcore Version: v5.8.3

We have a field collection with multi language wysiwyg editor, inputs, pictures, videos and checkboxes. If we customize and save the field collection content, it works. If we have opened the object, adjust something, open the page about the static route in the frontend and then want to save the object in the Pimcore, we always get the following error. As long as we don't open the object page, everything works.

### Error Message:
Could be that someone messed around with the fieldcollection in the meantime. Please reload and try again

### Fieldcollection:
![fieldcolection](https://user-images.githubusercontent.com/1038688/61463234-46c31000-a974-11e9-9093-8ee21f8534f5.png)

**Comment by brusch** [comment]
Unable to reproduce. 
Would be nice if you could debug that on your end, it seems that the definition of the field-collection get's saved in the meantime. 

The related code can be found here: 
https://github.com/pimcore/pimcore/blob/f3cd4a7dc99af48f60e43b5742547abd13d0d630/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L1432
https://github.com/pimcore/pimcore/blob/3ace074f31f970a133857eef96737e28691d6ea0/models/DataObject/Fieldcollection/Definition.php#L285

Thanks!

**Comment by dominikager** [comment]
@brusch this is happening now with a new pimcore X installation also.. we can't figure out what happens here

**Comment by brusch** [comment]
@dominikager ok, very interesting, just tried to reproduce it again, but I'm still not able to do so. 🤔
