### ISSUE TITLE
very bad wysiwyg performance on google chrome

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#4734]
Steps to reproduce in the pimcore advanced demo (google chrome):

1. open some products with wyswiyg editors (for example ID 1464, 1455, 1433, 1502)
2. click around somewhere in the backend (for example try to open some other objects)

=> chrome is close to death 

On my PC it works with about 2-3 WYSWIYGs without a problem but starting with 4 it becomes very slow. With 8-20 it then finally crashes.

**Comment by markus-moser** [comment]
In documents it's possible to open 30 WYSIWYGs without a problem. There needs to be a strange bug in data object WYSIWYGs which makes Pimcore nearly unusable... It's reproducable with many different kinds of objects.

**Comment by fashxp** [comment]
can't be reproduced on my machine. 
anyone else experiencing these problems?

**Comment by brusch** [comment]
I'm also not able to reproduce the issue, even with tons of objects open incl. the dev-tools.
![image](https://user-images.githubusercontent.com/142037/61517521-b9310000-aa07-11e9-81be-c3fced6ab34f.png)

Maybe this is caused by a Chrome extension? Have you tried to reproduce this in incognito mode?

**Comment by markus-moser** [comment]
There must be some kind of problem with the configuration of my PC and the PC of my colleague. We are not able to reproduce it anymore too at the moment allthough yesterday it happend on many different Pimcore instances on both of our PCs. Lets close it and hope that its fixed now. Maybe a chrome version problem.

**Comment by markus-moser** [comment]
It happend in incognito mode too.
