### ISSUE TITLE
[Data Objects] New Data-Type ReverseAdvancedManyToManyObjectRelation

### ISSUE THREAD

**Issue by questionmark78** [pimcore/pimcore#4736]
Would it be possible to also have a ReverseAdvancedManyToManyObjectRelation next to the ReverseManyToManyObjectRelation ?

For my particular use case it would already be nice to have the option to select a advancedManyToManyObjectRelation field in the existing ReverseManyToManyObjectRelation 

I tried adding the classname in /pimcore/bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/reverseManyToManyObjectRelation.js and that works fine.
```
this.fieldComboStore = new Ext.data.Store({
            proxy: {
                type: 'ajax',
                url: '/admin/object-helper/grid-get-column-config',
                reader: {
                    type: 'json',
                    rootProperty: "availableFields"
                },
                extraParams: {
                    types: 'manyToManyObjectRelation,**advancedManyToManyObjectRelation**',
                    name: this.datax.ownerClassName
                }
            },
            fields: ['key', 'label'],
            disabled: this.isInCustomLayoutEditor(),
            autoLoad: false,
            forceSelection:true
        });
```
But it would be extra nice to have the metadata present too.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
