### ISSUE TITLE
[Feature request] Provide end-user friendly error messages instead of stack traces.

### ISSUE THREAD

**Issue by jacobsyentl** [pimcore/pimcore#4738]
## Context
Currently backoffice errors are catched by exception handlers and provide stack traces in the back office. This is very handy to determine the origin of the error.

However, for end-users this message can create a lot of confusion which results in an instant 
call/email to IT support.

## Feature description
My suggestion would be to provide end-user friendly messages which stipulate the actual problem. (Maybe even make the messages configurable)

An additional link in the dialog could show the developer relevant information.

## Example Scenario
1. User has access to view products but not save them.
2. User goes to product.
3. User uses CTRL+S to save product
4. Exception is thrown:
![image](https://user-images.githubusercontent.com/9139261/61534074-dfb66180-aa2e-11e9-9ffb-2b2d5d6862e9.png)

My suggestion is to make something like this:
![image](https://user-images.githubusercontent.com/9139261/61534547-32dce400-aa30-11e9-8c94-c50f28dc92ee.png)

**Comment by brusch** [comment]
Stack trace is only shown when system is in debug mode, otherwise only the error message is shown. 
For your custom messages, you can throw a `\Pimcore\Model\Element\ValidationException` which will be displayed in a user-friendly box.
