### ISSUE TITLE
[Data Objects] Mandatory fields in block type within an object brick are not being validated

### ISSUE THREAD

**Issue by choppe3766** [pimcore/pimcore#4755]
# Bug Report

### Expected behavior
on publish an existing version all mandatory fields in all added objects (e.g. object bricks in blocks) should be validated and if the validation fails, an error message should be displayed and the object is not published

### Actual behavior
on publishing an exiting version of a data object, the mandatory fields in the added object bricks in a block element will not verified and the "incorrect" object is published.

### Steps to reproduce
- create an object brick with a mandatory field
- create a class with a block element, which contains the object brick
- add a data object an fill out all mandatory fields in the object brick, save and publish
- clear the at least one mandatory field in the object brick, save only as new version
- go to the versions tab in the data object and publish the latest version
- the data object with the empty mandatory field in the object brick is published

**Comment by brusch** [comment]
Object-Bricks in Block Data-Type are not supported. 
![image](https://user-images.githubusercontent.com/142037/61722206-275c2680-ad6a-11e9-9a69-ae9f8d5afcec.png)

**Comment by choppe3766** [comment]
Sorry, my fault:
- create a class with a object brick element inside
<img width="1165" alt="Bildschirmfoto 2019-07-23 um 19 22 32" src="https://user-images.githubusercontent.com/6122199/61733106-5cbf3f00-ad7f-11e9-993a-ec0639c64636.png">

- create a object brick with a block element and at least one mandatory field and attach the object brick to the associated class field
<img width="995" alt="Bildschirmfoto 2019-07-23 um 19 16 00" src="https://user-images.githubusercontent.com/6122199/61732767-a5c2c380-ad7e-11e9-9d38-148a9c5ddc7c.png">

We're using pimcore 5.8.1

**Comment by weisswurstkanone** [comment]
Unable to reproduce using the latest version.
Can you verify this on the demo instance please?

**Comment by weisswurstkanone** [comment]
@choppe3766  ping

**Comment by weisswurstkanone** [comment]
@choppe3766 last ping

**Comment by choppe3766** [comment]
I've try it out in Pimcore 5.8.1. At the moment I have no possibility to test the problem in version 6.1x.
Because this is an edge case, i think this ticket can be closed ;-)
