### ISSUE TITLE
Don't store class ID in class definitions

### ISSUE THREAD

**Issue by justbane** [pimcore/pimcore#4756]
It doesn't make sense to store the class ID in the definition file. This is data imposed by the DB and makes working across multiple developers a real pain. Currently, you have to remove the id before pushing as it will cause ID collisions for other developers.

There is no reason for the ID to be there that I can see, rebuilding classes without it works well.

**Comment by dpfaffenbauer** [comment]
https://github.com/pimcore/pimcore/issues/2916

**Comment by brusch** [comment]
Won't work without an ID, please use #2916 approach as @dpfaffenbauer suggested.
