### ISSUE TITLE
[bug] Multiple email receiver, space in separator don't work

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4757]
Hello,

In the email settings panel, it is said we can separe emails with ", " (notice the space please).

![image](https://user-images.githubusercontent.com/9025839/61746253-94d47b00-ad9b-11e9-81ba-b37b1a1a1c8c.png)

But using ", " make an RFC error when mail is sent to multiple receiver if space is present:

`Address in mailbox given [ xxx@xxx.fr] does not comply with RFC 2822, 3.6.2.`
(true address obfuscated)
Notice the space after the first [ in the error message.

Maybe a trim is missing somewhere in the code ?

It happen on a Pimcore 5.7.1 and maybe always on Pimcore 6 (i hadn't the opportunity to check).

Thanks.

**Comment by brusch** [comment]
As Pimcore 5 isn't supported anymore, please always check if an issue exists in Pimcore 6. 
In this case it doesn't and everything works for me as expected.

**Comment by brusch** [comment]
see #4267

**Comment by Yivan** [comment]
Thanks (noted the support end of Pimcore 5). Yes it has been corrected in 5.8.0 so.
