### ISSUE TITLE
[Data Objects] Preview: possibility to provide multiple preview links

### ISSUE THREAD

**Issue by ckogler-elements** [pimcore/pimcore#4759]
It would be great if we can define multiple preview urls for objects.
The main goal is to privide the user the opportunity to see the preview in a specific Language.

**Comment by ckemptner** [comment]
If you have a language switcher this is already possible (user can change the language in the preview tab). But I agree with you, the current solution should be improved - especially it is not clear to the user which language will be shown as the default language in the preview tab and how to configure the behavior.

**Comment by dpfaffenbauer** [comment]
I did something like this in CoreShop, so +1 here for me as well

<img width="1308" alt="Bildschirmfoto 2019-07-24 um 18 04 59" src="https://user-images.githubusercontent.com/5981845/61809447-98b8d980-ae3d-11e9-8dbf-0c604c12ce4c.png">

**Comment by fashxp** [comment]
fixed with https://github.com/pimcore/pimcore/pull/7005
