### ISSUE TITLE
[Matomo] Implement Tag Manager

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#4766]
Since Matomo 3.7.0 the plugin is automatically included as part of the Matomo Analytics release so pimcore should allow to configure the tag manager configuration in backend like the GTM:

```javascript
<!-- Matomo Tag Manager -->
<script type="text/javascript">
    var _mtm = _mtm || [];
    _mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src='https://{$MATOMO_URL}/js/container_{$CONTAINER}.js'; s.parentNode.insertBefore(g,s);
</script>
<!-- End Matomo Tag Manager -->
```

Reference: https://developer.matomo.org/guides/tagmanager/introduction

**Comment by fashxp** [comment]
matomo integration was removed with Pimcore X ... should be done as a bundle
