### ISSUE TITLE
Path Formatter for grid view

### ISSUE THREAD

**Issue by esorthapa** [pimcore/pimcore#4771]
Can we have [Path Formatter ](https://pimcore.com/docs/5.x/Development_Documentation/Objects/Object_Classes/Class_Settings/Path_Formatter.html)for grid view as well ? seems like Path formatter doesn't work for grid view.

**Comment by weisswurstkanone** [comment]
can you give an example?

**Comment by weisswurstkanone** [comment]
@esorthapa  ping

**Comment by alexbaat** [comment]
I think the question was if the path formatter that can be used on object layout page, can also be applied to the values on the grid. This would be a great enhancement.

**Comment by weisswurstkanone** [comment]
No, this is currently not supported.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
