### ISSUE TITLE
Not able to create variant/variant not visible

### ISSUE THREAD

**Issue by dpfahlbusch** [pimcore/pimcore#4772]
# Bug Report

- Behavior is reproducible on http://demo-advanced.pimcore.org/admin/

### Expected behavior
Variant should be created under the selected object.

### Actual behavior
Variant is apparently created, but not visible

### Steps to reproduce
- Go to product
- Create variant
- Enter name
- Submit (variant not visible)
- Create a new variant with the same name
- Error because "object with the same name exists" but variant is not visible

**Comment by dvesh3** [comment]
Please check the show variants in tree property in Product class
![screenshot-github com-2019 07 29-10-06-39](https://user-images.githubusercontent.com/5137917/62031882-a331f500-b1e8-11e9-9e9e-58741a902005.png)
