### ISSUE TITLE
CalculatedValue & QuantityValue share the same icon on Pimcore 6

### ISSUE THREAD

**Issue by Zamralik** [pimcore/pimcore#4773]
CalculatedValue & QuantityValue share the same icon on Pimcore 6

**Comment by weisswurstkanone** [comment]
can you provide a PR ?

**Comment by skoch98** [comment]
Hi,

here is my suggestion:
![icons](https://user-images.githubusercontent.com/31919154/64476907-23a72680-d195-11e9-8c72-7bbe5137dc11.png)

In addition, I would correct the assignment of the icon "Input Quantity Value".

I'm about to create a PR.
