### ISSUE TITLE
Finnish language not available in admin translations

### ISSUE THREAD

**Issue by tobiashelmer** [pimcore/pimcore#4775]
**Bug Report**

**Expected behavior**
Adding the Finnish language in your localization should allow to add admin translations for it as it's a common language

**Actual behavior**
If you add Finnish as a language you can't add translations for it in the admin translations as there is only an option for "Swedish (Finnland)" (shared translations got Finnland as an option. So you can set the document language to Finnish but can't add translations for it.

**Steps to reproduce**

1) Try to add Finnish language in the Localization option - shorthand is "fi" (correct)
![localization_finnish](https://user-images.githubusercontent.com/13036575/61957488-a7c79500-afbf-11e9-9b38-b7c9b40bca63.png)

2) Swedish Finnish as comparsion - shorthand is "sv_fi"
![localization_swedish_finnish](https://user-images.githubusercontent.com/13036575/61957490-a7c79500-afbf-11e9-9576-976dabfcbf82.png)

3) Admin Translation don't show "Finnish" as language, only "Swedish (Finnland)"
![pimcore_admin_translations](https://user-images.githubusercontent.com/13036575/61957491-a7c79500-afbf-11e9-804c-39e2ec1340e4.png)

4) Now take a look at the "translations_admin" table in the database and see that the translations are saved under the language "sv_FI" but the locale you get from the documents is "fi" -> no translations are available. I fixed it by manually changing the language in the database from "sv_FI" to "fi"

**Comment by brusch** [comment]
Works for me as it should, just tested on the public demo: 

![image](https://user-images.githubusercontent.com/142037/62133679-7d3b4c00-b2df-11e9-8dfa-34268500ac10.png)

![image](https://user-images.githubusercontent.com/142037/62133768-ae1b8100-b2df-11e9-97a1-5f63be1d81e8.png)

**Comment by tobiashelmer** [comment]
And what about the **admin translations**? There is only a fixed set of languages disconnected from the languages inside the localization in the system settings. The shared translations are working fine with the selected languages

**Comment by brusch** [comment]
Admin translations are only available in the languages where there's a translation of the admin UI. 
It won't make sense to allow Finnish admin translation if the entire UI isn't available in this language.
