### ISSUE TITLE
Warning that entity is currently opened not showing user anymore

### ISSUE THREAD

**Issue by deltatag** [pimcore/pimcore#4777]
In Pimcore 6: When an entity, which was already opened by another user, is opened in Pimcore 6 backend there comes a warning. 

This warning or dialog was showing the user which has opened the entity in Pimcore 5 but is not showing the user reference anymore in Pimcore 6.

![image](https://user-images.githubusercontent.com/7627410/62034240-ef336880-b1ed-11e9-8e03-c1c142ad122d.png)

**Comment by brusch** [comment]
For me this works as it should. 
Just tested on the public demo `https://demo-basic.pimcore.org/admin/` with documents, assets and objects and it works as expected (one tab in incognito mode and one normal tab).

**Comment by deltatag** [comment]
The warning popup is showing but it is missing **_which_** user has opened the document, asset or object. In Pimcore 5 this was a default feature:

![image](https://user-images.githubusercontent.com/7627410/62133997-0d799100-b2e0-11e9-8f77-f143b2343cfb.png)

**Comment by brusch** [comment]
Yep, sorry, my fault, that's why I've reopened the issue already :) 
Sorry for that :)
