### ISSUE TITLE
[Workflow] Saves before validation

### ISSUE THREAD

**Issue by baloraki** [pimcore/pimcore#4779]
# Bug Report
Should the workflow not be aborted if, for example, data is not saved?

### Expected behavior
The workflow is not changed if, for example, data is not saved.

### Actual behavior
The workflow is changed although there is data that is not yet stored.

### Steps to reproduce
Simply change data for an object with a workflow do not save and change the workflow.

Then the workflow is already set further and the message "All unsaved changes will be lost, are you really sure?" appears.
But the workflow has already been set further.

After answering the popup with no you can save but no longer continue the workflow

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
