### ISSUE TITLE
Overlays are not scaled on retina thumbnail images

### ISSUE THREAD

**Issue by John5** [pimcore/pimcore#478]
To reproduce:
1. Create a thumbnail definition with name 'test', for example "cover" 200 x 200 pixels.
2. Add an overlay with an image that is 200 x 200 pixels.
3. Add image to page and use Pimcore's `Asset_Image->getThumbnail('test')->getHTML()`
4. Display image, observe that it is working and the overlay covers the entire image.
5. Display image on retina screen (or retrieve path for 2x image from srcset attribute)
6. Observe that the overlay only covers a quarter of the image.

Expected result: overlay should cover entire image on retina resolutions.

![screen shot 2016-02-25 at 14 35 35](https://cloud.githubusercontent.com/assets/1368590/13321323/ac705006-dbce-11e5-95d7-b709758673d9.png)

**Comment by brusch** [comment]
Yes, you have to use "Add overlay fit" instead of "Add overlay" - this supports retina images as expected.
Currently we didn't find a way how we can realize "Add overlay" also for retina, but you're welcome to contribute this feature if you find a way how to implement this. 

Thanks!

**Comment by John5** [comment]
If it's not possible, to do this correctly, and there is another filter that achieves the same effect already without this problem I think it should be deprecated.

Many developers will not test on Retina screens, but retina thumbnail images are automatically generated. Users with retina screens will see unexpected results.
