### ISSUE TITLE
Open object in grid by double click only works in language English

### ISSUE THREAD

**Issue by deltatag** [pimcore/pimcore#4782]
In grid view double clicking on object path won't trigger open tab with object when backend language is set to other language then English.

**Steps to reproduce:**
1. Create new customer with admin rights and language other then English
2. Login new customer
3. Open folder of objects in grid view and try to open object by clicking on the object path => **nothing happens**
4. After changing the backend language for the customer to English double clicking the path in grid => **opens the corresponding object**

![image](https://user-images.githubusercontent.com/7627410/62042914-7ccb8400-b1ff-11e9-9274-a624c6d81a67.png)

**Comment by dvesh3** [comment]
Cannot reproduce on latest Pimcore version.
![2019-07-30_10-26-35](https://user-images.githubusercontent.com/5137917/62113634-39335180-b2b5-11e9-9ba3-1a29a76c5400.gif)

**Comment by deltatag** [comment]
This is not the way to product this bug. Try to follow these steps:

1. Login to https://demo-basic.pimcore.org/admin/login
2. Create new Pimcore user with language "German" and admin rights
3. Login as new Pimcore user
4. Open /news
5. Try to click on path to open object => **Doesn't work**
6. Logout again and login as admin
7. Set language of new user to English
8. Login again with new user
9. Open /news
10. Try to click on path to open object => Working

This problem still persists in most current Pimcore Version.

**Comment by dvesh3** [comment]
Sorry, I missed some steps from first comment. Thanks for clarifying :)
