### ISSUE TITLE
[Roles] Unpublish right

### ISSUE THREAD

**Issue by baloraki** [pimcore/pimcore#4783]
# Bug Report
### Expected behavior
If a role doesn't have the right unpublished, it still shouldn't have sideeffects, like when changing the sorting the contents disappear

### Actual behavior
If a role does not have that right unpublished, and changes the sorting in the tree, all content is deleted and an empty version is created.

As soon as you give this right, the error no longer occurs.

I looked at the events VersionEvents::POST_SAVE and DataObjectEvents::POST_UPDATE at this param the contents are no longer there only a empty version.

### Steps to reproduce

1. Create a role and a perspective.
2. Add to the role at the tab Data Objects a folder and remove the permission unpublish.
3. Add the role to a user.
4. Login as the user 
5. Create an object and fill the data.
6. Change the sort order to eg. manuelly

= Now the data should be gone.

**Comment by brusch** [comment]
Sorry, I followed exactly your instructions but wasn't able to reproduce the behavior.
