### ISSUE TITLE
[Pimcore5] Exception handling for versioning

### ISSUE THREAD

**Issue by mike4git** [pimcore/pimcore#4784]
### Expected behavior
There should be a typed exception and a proper exception handling in case of version saving failures in class Concrete.php

### Actual behavior
ATM, there is no try...catch...block or other code which would help to ignore saving versions failure and go on with the normal progress.

### Current code for class Concrete:
```php
    public function saveVersion(...)
    {
        ...
        // only create a new version if there is at least 1 allowed
        // or if saveVersion() was called directly (it's a newer version of the object)
        if (Config::getSystemConfig()->objects->versions->steps
            || Config::getSystemConfig()->objects->versions->days
            || $setModificationDate) {
            // create version
            ...
            $version->save();
        }
        ...

        return $version;
    }
```

There should be something like:
```php
    public function saveVersion(...)
    {
        ...
        // only create a new version if there is at least 1 allowed
        // or if saveVersion() was called directly (it's a newer version of the object)
        if (Config::getSystemConfig()->objects->versions->steps
            || Config::getSystemConfig()->objects->versions->days
            || $setModificationDate) {
            // create version
            ...
            try {
                $version->save();
            } catch (VersionUpdateFailureException $e) {
                if ($this->skipVersionUpdateFailure()) {
                    return null;
                } else {
                    throw e;
                }
            }
        }
        ...

        return $version;
    }
```
I'll hope I did not miss any hook magic to avoid that problem, but we ran into a "Checkout did not work anymore because of Order/OrderItem versions cannot be created" situation.
In these case I would prefer to "skip versioning" but go on with business process anyway.

**Comment by brusch** [comment]
`Version::disable();`

**Comment by mike4git** [comment]
Hi Bernhard,

the problem is not, how to disable versioning "globally" for this process.
I just want to see versioning in some cases as a minor prioritized feature which should be done if it is possible and if not the show must go on.
For the current Pimcore implementation the show ends up in a thrown generic exception version. This is NO solution.
Thanks anyway for the time you have spent.

**Comment by brusch** [comment]
PRs are welcome 😉
