### ISSUE TITLE
[Data Objects] Checkbox visualization when value is null

### ISSUE THREAD

**Issue by bramstroker** [pimcore/pimcore#4788]
### Expected behavior
In Pimcore 6 a checkbox seems to have a new state `null`. 
When this state is selected and I save the object I expect this to be somehow visible in the GUI. Preferable by the field being grayed out and value of parent object shown. This is how it is done with all the other fields.

### Actual behavior
The checkbox has a `null` state, but there is no differentiation in the UI. It looks like the checkbox is unchecked, but in reality the value is checked, because it is inherited from the parent.

### Steps to reproduce
- Create a variant object of a class having a checkbox field
- Click the trashbin next to the checkbox. Now the checkbox border is turning blue (which is a very strange choice imo consistency wise).
- Click "save and publish"
- Reload the object
- Now the checkbox does not have the blue border, so there is no indication of a `null` state.

### Images
[Here](https://imgur.com/a/dih7Fqm) are some images describing my issue.

**Comment by bramstroker** [comment]
This issue seems to be related to the default value of the checkbox. When I change the checkbox default value to `null` everything is working as expected. When it is set to `false` this visualization issue arrises

**Comment by brusch** [comment]
If inheritance is enabled, there's a visualization of null: 
![image](https://user-images.githubusercontent.com/142037/157412007-7e4832b7-0df6-4a94-9829-7a4d7ab4fc8a.png)

If inheritance is disabled, there's no need to do so.
