### ISSUE TITLE
[Data Objects] Relational fields: possibility to sort entries by path

### ISSUE THREAD

**Issue by deltatag** [pimcore/pimcore#4789]
### Feature Request
___
It is not possible to quickly sort entities in many-to-many relation editables e.g. by path ([Documentation](https://pimcore.com/docs/6.x/Development_Documentation/Documents/Editables/Relations_(Many-To-Many).html)).

The sort options are disabled:
![image](https://user-images.githubusercontent.com/7627410/62135372-634f3880-b2e2-11e9-9240-bcf471f31155.png)

**Comment by brusch** [comment]
But what to do with the manual order then? 
Use case: 
- Open data object
- Sort relational field _Manufacturers_ by path
- Click save

**Comment by brusch** [comment]
See also #4193

**Comment by brusch** [comment]
Currently I don't see any practical way of making this feature possible 🤔

**Comment by deltatag** [comment]
Then at least it should be possible to sort entries via drag & drop. Having a list of 100+ entries and placing the new entry (which is added at the bottom) at a specific position is painful. Clicking the down- or up-icons 100 times should not be the solution.

**Comment by brusch** [comment]
@deltatag that should work already ... 
![07-08-_2019_14-37-50](https://user-images.githubusercontent.com/142037/62623385-fdd1fc00-b920-11e9-9a08-11306045762f.gif)

**Comment by deltatag** [comment]
This feature is possible for objects but doesn't work for editables many-to-many relations:

https://pimcore.com/docs/5.x/Development_Documentation/Documents/Editables/Relations_(Many-To-Many).html

**Comment by deltatag** [comment]
Is there any update for sorting possibility for the relation editable?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
