### ISSUE TITLE
[Bug] Custom admin entrypoint don't work when path begining with "admin..." and doc not up to date

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4790]
Hello,

We were trying implementing custom admin path.
We get two problems.

1- The easy one, is the documentation is not correct (invalid Yaml).
Here https://pimcore.com/docs/6.x/Development_Documentation/Development_Tools_and_Details/Custom_Admin_Login_Entry_Point.html, good code is:
```
my_custom_admin_entry_point:
    path: /my-custom-login-page
    controller: Pimcore\Bundle\CoreBundle\Controller\PublicServicesController::customAdminEntryPointAction
```

2- And we where strugling trying to make work path with `/admin-mytest` and it didn't work (don't go in the customAdminEntryPointAction and eventlistener (https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/EventListener/CustomAdminEntryPointCheckListener.php#L57) is runned before going into the routed action.
Same with `/adminmytest`.
But path with `/roberto` work well.
So it seems all path begining with `/admin...` don't work as custom admin entry point.
I think it should corrected because many people will do somethings custom but meaningfull so possibility of path starting with admin word is not negligible.
Globally it means we cannot do any routes in yaml beginning with admin even in the frontend... a more harder bug.

Thanks.

**Comment by brusch** [comment]
1. changed that - probably a Symfony 3.4 vs 4.3 issue 
2. not possible to fix, added a not in the docs

**Comment by Yivan** [comment]
@brush Thanks for your return / fix.

I think it need some code fixing at this level:
https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/EventListener/CustomAdminEntryPointCheckListener.php#L57

Because any custom route beginning with "/admin*" will fall in this exception. So imagine a front-end custom rule for acccessing a custom admin having url beginning by /admin*. It won't work.
Maybe at this level, it should only send the exception if we are trying to access to the admin BO Pimcore related bundle ?
And it will allow in the same way to use /admin* even for BO Pimcore custom route.

The real problem is this exeption is throw for any bundles... If it is not throw the route is well resolved after.

Thanks!

**Comment by brusch** [comment]
As I said, ... I don't think we can fix that, because the context resolver uses /admin/* . However, if you think you can fix that without breaking anything else, we're happy to mere a PR.

**Comment by dpfaffenbauer** [comment]
Container Parameters could work...

**Comment by Yivan** [comment]
@brush You mean every url like `/admintest`, is resolved as an "admin" context ?
(i try to dig it, and i suppose it use the guesser here: https://github.com/pimcore/pimcore/blob/0b2794b9c2c999337f65a97e1592f9a976a25eec/lib/Http/Request/Resolver/PimcoreContextResolver.php#L64).
Maybe this part need to be more accurate in this case.
Why you said `/admin/*`... i don't anderstand very well, here the problem is for url like `/admintest` for instance. Yes `/admin/*` must resolve to admin context, but `/admintest` should not. Maybe i misanterstood somethings sorry.

My idea for a patch so is to add a AND condition to the if which trigger the exception. This condition would check url of the request begin with "/admin/".
Do you think it is ok ?
(here: https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/EventListener/CustomAdminEntryPointCheckListener.php#L55)
I would have prefered to fix it in the context scope so the `$this->matchesPimcoreContext($request, PimcoreContextResolver::CONTEXT_ADMIN)` would resolve to false to url like `/admintest` and so not trigger the exception if we have url like /admintest, but i don't know very well how it work and if you say it cannot be corrected because of symfony you are surely right. At least my proposed patch will allowing use url beginning with /admin for custom admin url and custom route beginning with /Admin in the frontend (even if we fall in context "admin").

@dpfaffenbauer You said there is maybe a way to fix it... any clues ?

Thanks again !

**Comment by dpfaffenbauer** [comment]
@Yivan: Yes, I might have a solution, but it requires a lot more work and also needs changes in a lot of files.

My idea would be to make the /admin path configurable, but that also means that all Ajax requests in Pimcore need to be changed, quite a big change for "just" changing a path.

**Comment by brusch** [comment]
Agree, not worth the effort at all. 
As a workaround you can configure a redirect directly on your webserver e.g. `/administration-super-secret` and just point it to your custom admin entry point e.g. `/my-custom-admin-entry-point` - done.

**Comment by dpfaffenbauer** [comment]
Also would be a BC break... Technically it would work, I just tested it. But its way to much work "just" to change from /admin to /custom.

as @brusch said, use rewrite rules on the webserver...

**Comment by Yivan** [comment]
@brusch @dpfaffenbauer 
I don't undestand very well what was your ideas...
I made some fix with this PR https://github.com/pimcore/pimcore/pull/4802 and it make them work great now, and fix the same way this problem which could have occured with any custom url used in project bundles begining with /admin*, /webservice*, /plugin*...
Now the guest context matcher is more robust.

I hope my solution is ok !
Thanks !
