### ISSUE TITLE
[XLIFF] Export: Option to export related objects

### ISSUE THREAD

**Issue by baloraki** [pimcore/pimcore#4792]
## Feature description
My idea would be to extend the Pimcore XLIFF translation to relationships.
E.g. objects within a Many-To-Many Object relation can be exported/imported for translation.
This option should be optional as with the child elements.

![image](https://user-images.githubusercontent.com/41831573/62201993-b8458a00-b388-11e9-9a7b-ee0a336e7447.png)

### Why?
At the moment these objects are completely ignored, which is annoying for some processes.

**Comment by brusch** [comment]
We'd be happy to merge a PR for that! 😉

**Comment by brusch** [comment]
Functionality should be based on dependencies, so all data-types are covered and this approach would work for documents as well.
