### ISSUE TITLE
[Data Objects] Improve Variant functionalities in object tree

### ISSUE THREAD

**Issue by RuudvdvNB** [pimcore/pimcore#4793]
# Feature Request
For variants it's not possible to duplicate or move variants inside the tree structure. The [docs](https://pimcore.com/docs/6.x/Development_Documentation/Objects/Object_Classes/Class_Settings/Variants.html) are stating that variants are exactly the same as objects and offer the same functions, but it turns out not everything is working exactly the same.

To make things easier for customers we would like to add variants automaticly in the second level of the variant tree. But the customer should be able to move the variant further down the tree.

**Comment by pspierce** [comment]
Is this not a matter of DataObject\AbstractObject::OBJECT_TYPE_VARIANT being missing in a few places?  I had to write a command-line script and feed it IDs and a new parent because I was being asked to move variants so often.  Changing the parent ID doesn't appear to impact anything outside of inheritance, which is appropriate.

**Comment by brusch** [comment]
@pspierce unfortunately not, @RuudvdvNB is talking about topics like that: 
https://github.com/pimcore/pimcore/blob/1d8a09f927ff92a3d4be4e501af0db67d1aca40d/bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js#L296

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
