### ISSUE TITLE
Translateable Block fields doesn't work in Objectbricks

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#4798]
# Bug Report

### Expected behavior
If I define a tranlateable block field with input fields I can't save this objects.

### Actual behavior
I get an Internal Server Error:
Call to undefined method getTestBlock3 in class Pimcore\Model\DataObject\Test

### Steps to reproduce
1. Create an Objectbrick with an translateable block field and an input field:
![image](https://user-images.githubusercontent.com/998558/62298902-3af74380-b474-11e9-82fa-f8a33c3a66f5.png)
2. Fill this block/input fields and try to save
![image](https://user-images.githubusercontent.com/998558/62298974-5a8e6c00-b474-11e9-8b40-cca94d7e3f1d.png)
3. Get error:
![image](https://user-images.githubusercontent.com/998558/62299009-65e19780-b474-11e9-8647-d3fd0772331b.png)

### Additional information
The same definition in the object itself works.

**Comment by brusch** [comment]
@weisswurstkanone is that even possible?

**Comment by weisswurstkanone** [comment]
currently we support only 3 nesting levels, in this case we would have 4.
- object
- brick
- block
- localized fields

would require some refactoring and maybe BC breaks

**Comment by brusch** [comment]
@weisswurstkanone thanks for clarifying, can you add a note about that to the docs? 
I guess it's not possible to restrict those cases in the UI editor, right?

**Comment by weisswurstkanone** [comment]
In the UI editor you probably can somehow catch this (but needs a bit of effort). Before doing this we should check other scenarious as well as IMHO you can do a lot more in the UI than allowed.
