### ISSUE TITLE
[Asset] Image Editor saves image as PNG even when source file is JPEG

### ISSUE THREAD

**Issue by SameerPCore** [pimcore/pimcore#4805]
# Bug Report

Edited Image is not opening after Original File download option
### Expected behavior
Image should open without any error
### Actual behavior
A format exception is coming after opening the downloaded image
### Steps to reproduce
-->Go to asset tab, open an image from left tree view
-->Go to edit tab, edit the image and save it.
-->Go to preview tab, download the image by clicking on Original File button
-->Go to the downloaded file and open it.
--> Image doesn't open an error message comes in the bar. See the attach screenshot
![Screenshot from 2019-08-05 19-13-33](https://user-images.githubusercontent.com/52485995/62469209-6bf9b000-b7b5-11e9-99d7-0c1cf4098903.png)

### Code example
```php
// your code
```

# Feature Request

**Comment by brusch** [comment]
Just tested on demo.pimcore.org ... works as expected when using the download button: 

![image](https://user-images.githubusercontent.com/142037/62469477-a739b600-b798-11e9-9262-6b618f9f4664.png)

**Comment by SameerPCore** [comment]
edit a jpg file and download with original file button.
![Screenshot from 2019-08-05 19-22-49](https://user-images.githubusercontent.com/52485995/62469799-a6b01800-b7b6-11e9-9547-1f9bb27e90e6.png)

**Comment by SameerPCore** [comment]
the issue is very much there it is not working. please see the screen shot
testing on demo-advanced.pimcore.org
![Screenshot from 2019-08-05 19-27-46](https://user-images.githubusercontent.com/52485995/62470047-2b029b00-b7b7-11e9-85de-63ff48d47ad7.png)

**Comment by brusch** [comment]
Just tested it on demo-basic.pimcore.org (advanced currently not working), works as expected...

**Comment by SameerPCore** [comment]
Please upload a JPG file and edit and save it. then download it from either download button of toolbar or original file button present on the right panel. The error is very much there. this error is occurring because while editing the format is changed to PNG but the extension of file remains JPG.

**Comment by dvesh3** [comment]
@brusch It works fine if you try to open image on Windows default image viewer but reproducible on some softwares so maybe Linux is affected. @SameerPCore is right, this is the issue https://stackoverflow.com/questions/11310220/why-am-i-getting-the-error-not-a-jpeg-file-starts-with-0x89-0x50
![image](https://user-images.githubusercontent.com/5137917/62518710-6e4a2180-b82a-11e9-8826-e23ae28e9407.png)
