### ISSUE TITLE
versioncleanup does not remove ophan version files

### ISSUE THREAD

**Issue by yariksheptykin** [pimcore/pimcore#4807]
# Bug Report

When executing "versioncleanup" maintenance task as [described in the documentation](https://pimcore.com/docs/5.x/Development_Documentation/Administration_of_Pimcore/Cleanup_Data_Storage.html) files that are not referenced in `versions` table (orphan version files) are not cleaned up. If therefore the contents of `var/versions` and the database table `versions` get out of sync, filesystem will indefinitely store version files under `var/versions` with IDs not present in `versions` table. This situation may arise when transfering database dumps between stages or when filesystem was inaccessible / read-only during version deletion.

## Background

`versioncleanup` is implemented in [Pimcore\Maintenance\Tasks\VersionsCleanupTask](https://github.com/pimcore/pimcore/blob/6d0db02c7527908f61e7cc5d1d0521f00b1b3061/bundles/CoreBundle/Resources/config/maintenance.yml#L49) and it cleans outdated versions [provided by Version::maintenanceGetOutdatedVersions](https://github.com/pimcore/pimcore/blob/08b6245bcc828321f7555faf37ea546ed4ab2633/lib/Maintenance/Tasks/VersionsCleanupTask.php#L76). [maintenanceGetOutdatedVersions](https://github.com/pimcore/pimcore/blob/a84c6697a91e06969ce3f291685c2fa2738a0c18/models/Version/Dao.php#L129) in turn collects versions to be cleaned via a DB lookup into `versions` table (for example [here](https://github.com/pimcore/pimcore/blob/a84c6697a91e06969ce3f291685c2fa2738a0c18/models/Version/Dao.php#L146)). Only versions that are referenced in the `versions` table will be returned and therefore cleaned.

### Expected behavior

`versioncleanup` reconsiles contents of the `versions` table and the filesystem under `var/versions`.  Orphan version files are removed.

### Actual behavior

Contents of the filesystem and `versions` table remain out of sync. Orphan version files persist.

### Steps to reproduce

Create a pimcore object and save it a couple of times to generate several versions. Delete one of the versions directly in `versions` table. Execute `versioncleanup`. Orphan version files remain in the versions folder.

### NOTE

Not sure if this is a bug or feature request.

**Comment by yariksheptykin** [comment]
@brusch , @fashxp would be interested to have your opinion on how to approach this issue. Should the [maintenanceGetOutdatedVersions](https://github.com/pimcore/pimcore/blob/a84c6697a91e06969ce3f291685c2fa2738a0c18/models/Version/Dao.php#L129) provide a list of versions using filesystem instead of DB?

**Comment by brusch** [comment]
@yariksheptykin Working directly in the database is not supported by Pimcore and I highly recommend to not do so unless you know what you're doing. 
If you're manually deleting items in the database you have to care about the referenced files yourself, that's neither a bug nor a feature request.

**Comment by yariksheptykin** [comment]
Thaks for taking a look @brusch! The thing is we never deleted versions in the DB directly. Those "Steps to reproduce" of mine were quite misleading, sorry about that. That is just a way to hack oneself into the issue :)

To me the important part is that `versioncleanup` assumes that filesystem and `versions` table are always in sync. In that case it cleans outdated versions properly. What it does not account for is the two getting out of sync when there are more version files than entries in the versions table. Those "orphans" will never be considered for a clean-up, and stick to the filesystem forever.
This is the case we are experiencing with a pimcore installation. After about a year of operation we accumulated around 20 GB of "orphanated" version files. They sit on disk but have no references in versions table. I cannot name a single reason for how arrived at this, but here are some things that could explain that. 1) Infrequent DB rollbacks, 2) denial of writing access to version files due to a permission mess up (i. e. executing bin/console search:reindex as root), 3) various bugs in our code leading to objects being frequently saved.

Do you think iterating through the filesystem in var/versions in maintenanceGetOutdatedVersions and deleting files not referenced in versions would be a reasonable way to address this? If so I would try to patch maintenanceGetOutdatedVersions and submit a PR.

**Comment by yariksheptykin** [comment]
@fashxp , @brusch I had to write a bit of code to clean up the orphaned versions in our pimcore installations. I decided to put out as a standalone lib to help someone who comes across a similar issue.

**Comment by brusch** [comment]
@yariksheptykin can you share the link to the library?

**Comment by yariksheptykin** [comment]
@brusch , oh sorry forgot to include the link. Here it is: https://github.com/teamneusta/pimcore-maintenance
