### ISSUE TITLE
Prevent data loss when two users save same object

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#4810]
Currently Pimcore is prone to data loss when two users open the same object.
Steps to reproduce:
1. User A opens object 1
  * at this time data of object 1 gets loaded
1. User B opens object 1 (a little message appears that this object is already being opened by another user - this is currently the only protection against data loss through multiple user savings)
  * User A and B see the same data
1. User A changes data of object 1 and saves object
1. User B changes data of object 1 and saves object
1. Object 1 now has only the data of user B. All changes of user A have been overwritten due to user B's saving.

Proposal:
* Remember loaded version ID which underlies the loaded data of the opened object
* When object is getting saved, check if loaded version ID is identical with current version:
  * if true: save object
  * if not:
    1. Load current version's data
    1. Check if there are changes done in the same fields in the meantime as of the ones being saved now (and field's contents between current version and saved data differ)
       * if yes: error message because Pimcore cannot decide which data in a certain field is wanted; 
       * if not: save only fields which got changed and keep all other data from the current version

**Comment by brusch** [comment]
Actually I think this would add a lot of extra complexity to the entire process which is currently already quite complex. Just think of nested data-types such as field-collections, ... that would be just a freaking nightmare. In my opinion it's just not worth it, even though I understand the problem. 

I'll close this issue for now, since that's not gonna be implemented by the core-team, but feel free the continue the discussion 😊

**Comment by BlackbitNeueMedien** [comment]
I could imagine remembering the loaded version id and then remember all setter calls.
When save() gets called, the underlying version ID gets compared to the current version ID of the object. If they differ, the current version gets loaded and all setter calls get called again.
Am I underestimating this task?

**Comment by brusch** [comment]
> Am I underestimating this task?
I'd think so ... 😉

But feel free to create a PR for that, just remember that we won't accept an extra layer of complexity.

**Comment by BlackbitNeueMedien** [comment]
@brusch what do you think of showing the "another user has already opened this object" only to users who have the right to edit the object? Because if the current user only has the right to read the object, the info message does not make much sense, does it?
