### ISSUE TITLE
[Bug] Inheritance with localized fields within a block

### ISSUE THREAD

**Issue by s-ormanns** [pimcore/pimcore#4818]
# Bug Report
When having localized fields within a block, let's say two input fields (input1 and input2) and inheritance is allowed, the data gets inherited just fine. Now I change the value of input1 in the data object with the inherited values, hit save and everything seems fine, but on reload one must see that the value of input2 was emptied. I tested this on https://demo-basic.pimcore.org too.

### Expected behavior
Only the explicitly changed fields are overridden. Other inherited values are kept.

### Actual behavior
The changed fields are being saved. Inherited values from other fields are lost.

### Steps to reproduce
* create a new class (allow inheritance, allow variants, show variants in tree)
* add a layout component
* add a block with localized fields in it, the localized fields holding two input fields
* create a new object of it, add a block, provide some values
* add a new child object, override the input1 field
* hit save
* hit reload -> see that the input2 value disappeared

**Comment by brusch** [comment]
Inheritance in localized fields within a block is not supported. 
I even don't see any change how to make that possible, ... same for field collections.
