### ISSUE TITLE
New command to create/update custom layouts from definition files

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#4825]
If you want to deploy custom layouts between instances you also have to 'copy' the database entry for the layout.

All the information from the database also seems to be present in the definition file.

It would be cool if we would have a job similar to ```pimcore:deployment:classes-rebuild``` for custom layouts.

**Comment by brusch** [comment]
Good news ... it's already there, see #4729 ;-) 
The release of 6.1.0 is coming 🎉
