### ISSUE TITLE
[Assets] Bulk thumbnails generation doesn't work properly

### ISSUE THREAD

**Issue by mloock** [pimcore/pimcore#4826]
# Bug Report

### Expected behavior

Missing thumbnails generation for all existing images or videos

### Actual behavior

It works only for the 10 first elements in the list. There is a loop stuck on these first 10.

### Steps to reproduce

Just run the pimcore:thumbnails:image [-f] command

### Bug origin

This bug has been introduced with the commit issued on 6th June : https://github.com/pimcore/pimcore/commit/d5a2a1226b24ad43e8b0765ec19cdb11175f61b6

On the following files :

-  bundles/CoreBundle/Command/ThumbnailsImageCommand.php
- bundles/CoreBundle/Command/ThumbnailsVideoCommand.php

### (Proposed) solution

In my opinion, an explicit $list->getDao()->load() must be done in order to update new values for limit and offset in the listing, for each iteration.

What do you think?

**Comment by brusch** [comment]
Thanks for reporting!
