### ISSUE TITLE
LocaleListener should not set LC_NUMERIC locale

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#4829]
Currently string casts of floats are printed in a locale specific format.

#### Example:
```
float 30.52 => output 30,52 with locale de
```

This behaviour can cause many problems for example in export scripts or when using external libraries/APIs. I think it would be better to exclude LC_NUMERIC in the locale listener. If someone needs locale specific formatting of floats (for example in templates) it's better to use custom application specific helpers for this.

**Comment by ultramegatom** [comment]
should be fixed to c imo: ```setlocale(LC_NUMERIC, 'C');```
