### ISSUE TITLE
[Custom Reports] Problem with formatting date in a export to CSV

### ISSUE THREAD

**Issue by jorisros** [pimcore/pimcore#4833]
When you have a custom report that contains dates in to it, you can configure the displaytype to Date and in the result there is a nice date formatted. But in when I press the export to CSV the date is unixtimestamp. 

### Expected behavior
I expect that the date is formatted in a proper way in the CSV export.

### Actual behavior
There is a unixtime stamp in the export at this moment.

### Steps to reproduce
- Create a customreport
- Select a date field
- Set the displaytype to Date
- Show the report result
- Press `Export to CSV`
- Open the export and you see the timestamp in the date column.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
