### ISSUE TITLE
Link drag and drop still possible even when links are deactivated in CKEditor profile

### ISSUE THREAD

**Issue by julmot** [pimcore/pimcore#4848]
# Bug Report

When having a WYSIWYG editable within the CMS area, with a CKEditor configuration (JS) without links:

```javascript
CKEDITOR.editorConfig = function(config) {
  config.removeButtons = 'Form,Checkbox,Radio,TextField,Textarea,Select,Button,HiddenField,Link,Unlink,Anchor,Image,Flash,Table,HorizontalRule,Smiley,SpecialChar,PageBreak,Iframe,Format,Font,FontSize,Styles,About';
};
```

you can still drag and drop a document from the tree into a WYSIWYG field, even though the link button in the CKEditor toolbar is hidden and thus the feature deactivated.

### Expected behavior

It should not be possible to drag and drop documents into a WYSIWYG field with deactivated links.

### Actual behavior

It's still possible.

### Steps to reproduce

Open a new document and place a brick with a WYSIWYG field on the page. Then drag and drop a document on the field. This is posible – even if the link is deactivated in the CKEditor configuration of the field.

![000163](https://user-images.githubusercontent.com/8310677/63021034-e904e380-be9f-11e9-85ad-660029b470c7.png)

**Comment by brusch** [comment]
The config is just to remove the link button, not the link functionality, that's why it's called `removeButtons`. 
If you'd like to disallow link elements, please have a look at CKEditor's possibilities.
