### ISSUE TITLE
FR: Add links to objects in WYSIWYG editor

### ISSUE THREAD

**Issue by atietje** [pimcore/pimcore#485]
# Feature Request
- [x] There is no existing issue regarding the same topic
## Feature description

This is a suggestion for a new feature:

**„As a backend user I can drag and drop any object tree node onto a text selection in any WYSIWYG editor in order to create a hyperlink to that object“.**

Say you have a class `Product` and you'd like to add a link to a specific product in a WYSIWYG editable. Then you could open the object tree and drag a corresponding tree node onto a text selection just as you can do it with documents. The object ID would be added to the link so that changing values of the objects properties won't break the link. The dependency would be inserted into the table `depencencies`.

To create the URL I suggest to add a selection field to the class definition dialog to select an existing static route with named placeholders. Then, when the editable is rendered, the URL to the object could be created by using the specified static route. If no route is selected the link tag wouldn't be rendered or - as a fallback solution - the objects preview URL or full path would be used as the URL. Tree nodes of objects without a configured static route can not be dragged onto the editor.

What do you think?

**Comment by timhonders** [comment]
Added a new pull request: https://github.com/pimcore/pimcore/pull/529

**Comment by kanevbg** [comment]
It seems correct that, this functionality to be available all around the system not only in the objects. I mean in each WYSIWYG editor. Or at least to that editor in the documents too.

Dynamic document and asset (by specifying thumbnail config) URL generation on the same principle can be done too and that is going to be powerful and contemporary which I bet will be highly appreciated by users.

**Comment by fashxp** [comment]
see https://pimcore.com/docs/5.x/Development_Documentation/Objects/Object_Classes/Class_Settings/Link_Generator.html
