### ISSUE TITLE
I can't run xx.com/admin where i finished install

### ISSUE THREAD

**Issue by Christbye** [pimcore/pimcore#4850]
# Bug Report

### Actual behavior

Warning: file_put_contents(/home/christ/pimcore/pimcore/var/cache/dev/appAppKernelDevDebugContainerDeprecations.log): failed to open stream: No such file or directory

### Steps to reproduce
1.I'm installed pimcore with composer
2.Configrution apache and can print phpinfo() correct
3.Access xx.com/admin
4.Response 500 and the error is that
5.There's no file or folder at myProject/var/cache/
### Code example
```php
// your code
```

# Feature Request

**Comment by brusch** [comment]
Support: https://talk.pimcore.org
