### ISSUE TITLE
Email delivery not working if debug mode is disabled

### ISSUE THREAD

**Issue by dpfahlbusch** [pimcore/pimcore#4851]
## Expected behavior
Send email with disabled debug mode

### Actual behavior
Email is only sent when debug mode is enabled

### Steps to reproduce
- Enable debug mode
- Send testmail in backend
- Email sent
- Disable debug mode
- Send testmail again
- No mail sent

(Current Version (6.1.1) and 5.7.2)

**Comment by brusch** [comment]
Unable to reproduce.
