### ISSUE TITLE
Thumbnail Fallback can't be overriden

### ISSUE THREAD

**Issue by msphn** [pimcore/pimcore#4853]
# Feature request
Thumbnails are doing a great job generatic srcsets! But they define the smallest image as a fallback.
This causes in browsers which are not supporting srcsets to always display a quite low quality image (yes boys, we talking about ie11.)

It would be great to pass a parameter allowing to override the fallbackimage.

If you guys agree I can implement myself.

**Comment by msphn** [comment]
@brusch If I add config for that, would you accept it?

**Comment by brusch** [comment]
@msphn 👍 fine for me, go ahead 😊

**Comment by msphn** [comment]
In meanwhile I figured out creating an image with 1px max-width works great on IE. But I'll try to improve that one!

**Comment by brusch** [comment]
Resolved by #6085
