### ISSUE TITLE
Version restore of objects with inexisting advanced many to many object relations fails

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#4855]
Steps to reproduce:

1. create a object A with a advanced many to many relation field
2. add object B as relation to A in the advanced many to many relation field
3. press "only save new version" in object A
4. delete object B
5. try to (re)open object A

=> it's impossible to open the object as the following error will appear:
![image](https://user-images.githubusercontent.com/4639428/63164390-930f7780-c028-11e9-9edc-9f2eba7c1078.png)

**Comment by brusch** [comment]
I would say the expected behavior is that it is simply silently ignored
