### ISSUE TITLE
Problems arise when installing workflow.

### ISSUE THREAD

**Issue by dengyupeng** [pimcore/pimcore#4857]
Problems arise when installing workflow. After I composer require you to / workflow-gui dev-master installation, I executed bin/console pimcore: bundle: enable Workflow GuiBundle without error, but this error occurred when I installed bin/console pimcore: bundle: install Workflow GuiBundle.

Migrating up to 00000001 from 0

  ++ migrating 00000001
 

Migration 00000001 was executed but did not result in any SQL statements.

  ++ migrated (0.04s)

  ------------------------

  ++ finished in 0.04s
  ++ 1 migrations executed
  ++ 0 sql queries

![QQ截图20190818162009](https://user-images.githubusercontent.com/29151484/63222023-51bbcb00-c1d4-11e9-9718-3925d71b14da.jpg)

![QQ截图20190818162034](https://user-images.githubusercontent.com/29151484/63222038-89c30e00-c1d4-11e9-9cc4-18b4932986c3.jpg)
![image](https://user-images.githubusercontent.com/29151484/63222043-95aed000-c1d4-11e9-95f5-0ba564266d3d.png)

Although the installation was successful, it did so in. / bin / console pimcore: bundle: install Workflow GuiBundle

It's time to show up.

Migration 00000001 was executed but did not result in any SQL statements.

This prompt.

When you look at the workflow later, there are no graphics.

Urgent, I hope you can answer, thank you!

Deng Yupeng

**Comment by fashxp** [comment]
Workflow GUI Bundle is not part of Pimcore core. 
Please use its issue tracker https://github.com/YouweGit/pimcore-workflow-gui for issues or https://talk.pimcore.org/ for support.

**Comment by dpfaffenbauer** [comment]
@fashxp that is absolutely not a workflow gui bundle issue, thats a server configuration problem, since the screen don't show anything related to workflow gui, they show pimcore workflow stuff.
