### ISSUE TITLE
Pimcore 3.1.1 class import/export: Class cannot be saved

### ISSUE THREAD

**Issue by DominicDetta** [pimcore/pimcore#487]
Im using the 3.1.1 version, build 3543.

After a fresh install of pimcore I checked the System - Requirements- Check page and I noticed that there was an error on the row: SELECT (from view).
I solved this error changing the database adapter from Mysqli to Pdo_Mysql.

When importing a class which have even only one input, the system show me the error message 'Class cannot be saved'.

Steps to reproduce :
1. Create a class with one input
2. Export the class
3. Delete all configuration
4. Save
5. Import the class
6. Save

If I try to re-create all the class manually no problem occurs, only when using the feature import/export of the class.
This is the error message in website/var/log/debug.log:
`
2016-02-29T11:09:22+01:00 ERR (3):  10 MB | Array
(
    [message] => SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'p_index_Name'; check that column/key exists, query was: ALTER TABLE `object_query_10` DROP INDEX `p_index_Name`;
    [method] => query
    [arguments] => Array
        (
            [0] => ALTER TABLE `object_query_10` DROP INDEX `p_index_Name`;
        )
)
`

**Comment by brusch** [comment]
Unreproducible. Works as expected, in latest build. 
Thanks anyway :)
