### ISSUE TITLE
Xampp - Unable to open base address file when saving system settings

### ISSUE THREAD

**Issue by DevelGitH** [pimcore/pimcore#4875]
# Bug Report

### Expected behavior
It should be possible to save the options from the system settings.
### Actual behavior
The request "/admin/settings/set-system" is returning an invalid response. Afterwards an error popup is shown.
```
environments: ["dev", "prod"]
0: "dev"
1: "prod"
errors: [,…]
0: "The command "C:\xampp\php\php.exe "bin/console" cache:clear --env=dev" failed.↵↵Exit Code: -2(Unknown error)↵↵Working directory: C:\xampp\htdocs\pimcore↵↵Output:↵================↵↵↵Error Output:↵================↵Tue Aug 20 21:27:32 2019 (2648): Fatal Error Unable to open base address file↵"
1: "The command "C:\xampp\php\php.exe "bin/console" cache:clear --env=prod" failed.↵↵Exit Code: -2(Unknown error)↵↵Working directory: C:\xampp\htdocs\pimcore↵↵Output:↵================↵↵↵Error Output:↵================↵Tue Aug 20 21:27:32 2019 (12964): Fatal Error Unable to open base address file↵"
success: false
```

When I'm executing the two commands manually within the cli, no error is thrown.
Another bug that I noticed and could be related with this is when I'm changing the speaking url or title from a page, the navigation on the website will not be synchronized (due to caching). I have to clear the data cache to effect the changes on the website.

### Steps to reproduce

1) Install Pimcore on Xampp
2) Go to the system settings and press the save button

**Comment by brusch** [comment]
Pimcore is not officially supported on Windows, however, we'd accept PRs fixing the issue 😉
The right place to fix this would be probably somewhere around here: 
https://github.com/pimcore/pimcore/blob/4c986d60d890898e466533a21dfd29bde2acb9f6/lib/Cache/Symfony/CacheClearer.php#L113
