### ISSUE TITLE
[Bug] Cannot save Email settings

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#4876]
# Bug Report

Trying to save some fields in the Mail section of System Settings seems impossible on both Demo Basic and local installation with version 6.1.2.

### Expected behavior

All fields should have their settings saved.

### Actual behavior

Some fields are left blank locally and all fields are blank on Demo Basic. Locally, this only resets the **SMTP Host** value to blank, but still saves all other fields.

### Steps to reproduce

1. Go to System Settings, expand Email Settings
2. Fill in values:
![Skärmbild (170)](https://user-images.githubusercontent.com/279826/63423633-06d8c800-c40d-11e9-8cec-d68e8052de88.png)
3. Reload the admin area, open the System settings again:
![Skärmbild (171)](https://user-images.githubusercontent.com/279826/63423667-1b1cc500-c40d-11e9-8d25-f67053ec2739.png)

**Comment by brusch** [comment]
I've just tested this on the latest basic demo - no problems... 

![image](https://user-images.githubusercontent.com/142037/63505463-e58edf00-c4d3-11e9-8602-6e16c2e91053.png)

**Comment by NiklasBr** [comment]
Really? Because it is fully broken with Chrome 76, and Firefox 68.

Reopen please.

**Comment by bobdenotter** [comment]
@NiklasBr As explained to me by @aarongerig [here](https://github.com/pimcore/pimcore/issues/4878#issuecomment-523906468), You have to click the "Save" button, that might be obscured from sight by the symfony toolbar: 

![63518536-88a22180-c4f1-11e9-8b51-6ebd68c6920a](https://user-images.githubusercontent.com/1833361/63520061-5c3bd480-c4f4-11e9-854e-0816d71aef57.png)

**Comment by NiklasBr** [comment]
_Look at the video! I am clicking the save button on second 47..._

After I click the save button I reload the interface and the settings are gone.

I have also verified locally that the value is not actually saved to the system.yml file either.

**Comment by fashxp** [comment]
as we cannot reprocude it, can you try to dig a bit deeper and find the cause of the problem? 

thx!

**Comment by NiklasBr** [comment]
Please reopen this issue

**Comment by NiklasBr** [comment]
A better screen recording using Chrome 76 on Windows 10 showing the issue.

[screencast-demo-basic.pimcore.org-2019.08.23-08_48_52.webm.zip](https://github.com/pimcore/pimcore/files/3533155/screencast-demo-basic.pimcore.org-2019.08.23-08_48_52.webm.zip)

**Comment by brusch** [comment]
Just tested it again on a fresh install, no problems .. see: 
[23-08-_2019_13-11-33.zip](https://github.com/pimcore/pimcore/files/3534181/23-08-_2019_13-11-33.zip)

**Comment by NiklasBr** [comment]
Why is it happening on both the Demo Advanced and Demo Basic sites and locally on a fresh install?

**Comment by brusch** [comment]
It doesn't happen to me on demo basic, didn't test advanced.

**Comment by NiklasBr** [comment]
[screencast-demo-advanced.pimcore.org-2019.08.23-14_18_41.webm.zip](https://github.com/pimcore/pimcore/files/3534352/screencast-demo-advanced.pimcore.org-2019.08.23-14_18_41.webm.zip)

**Comment by brusch** [comment]
Well, on our public demo instances (e.g. demo-advanced.pimcore.org) saving the system settings is not supported ...

**Comment by NiklasBr** [comment]
Despite your assurances to the contrary I cannot get it to work on a fresh installation of 6.1.2 locally

**Comment by fashxp** [comment]
on demo advanced we have removed write access to the `system.yml` ... maybe a similar issue on your site. does php have write access to `/var/config/system.yml`? 
or are these configs set somewhere else so that the `system.yml` gets overwritten with another symfony config file?

**Comment by NiklasBr** [comment]
Other settings such as timezone and debug mode can be toggled and `var/config/system.yml` changes accordingly, it is *only* the email settings which are not saved.

**Comment by fashxp** [comment]
as I said before ... please can you dig deeper as we cannot reproduce it. 
check, if system.yml is updated, if not try to debug and see where the data gets lost.

**Comment by solverat** [comment]
i also can confirm it. mail settings are stored in swiftmailer.mailers.pimcore_mailer, after reopen the settings, they're gone. 

- after i executed a ca:cl, everything is back to normal.
- i do have multiple system_ENV.yml files

**Comment by solverat** [comment]
@NiklasBr : do you have any special environment name? (just ran into this one: #4886)

**Comment by solverat** [comment]
found it. you need to decleare the same mailer type in `pimcore.email.method`:

![image](https://user-images.githubusercontent.com/700119/64060962-41442100-cbd4-11e9-8abe-6f62351f825e.png)

to match it with `swiftmailer.mailers.pimcore_mailer`:

![image](https://user-images.githubusercontent.com/700119/64060970-515c0080-cbd4-11e9-84e1-1cf83476a516.png)
