### ISSUE TITLE
[bug] Can't modify user

### ISSUE THREAD

**Issue by bobdenotter** [pimcore/pimcore#4878]
Running version 6.1.2. Brand new setup. - Possibly related to #4876 

It seems like I can't modify user settings, after the initial creation of the user. 

I make some changes, like this: 
 
![Schermafbeelding_2019-08-21_om_14_51_51](https://user-images.githubusercontent.com/1833361/63433474-8a9daf00-c423-11e9-808d-27c51406cf06.png)

And I close the tab, and reload it, the data is gone: 

![Schermafbeelding_2019-08-21_om_14_52_07](https://user-images.githubusercontent.com/1833361/63433607-d05a7780-c423-11e9-8ad8-c70f0328edaa.png)

There are no notices (nor XHR requests) visible in the browser's developer tools. I've tried both Chrome and Firefox.

**Comment by brusch** [comment]
Just tested this on the latest basic demo using Chrome, and I was not able to reproduce the issue.

**Comment by bobdenotter** [comment]
Well, if you're just closing this with a "WFM", i don't think there's much use in digging in deeper here. 

There absolutely _is_ an issue in this regard, so I expect there will be more reports about this.

**Comment by aarongerig** [comment]
@bobdenotter If you change data in the user panel, you also have to click the save button (bottom right). Then a notification (also bottom right) should pop up and there should definitely be a XHR request in the dev console.

![Bildschirmfoto 2019-08-22 um 15 28 10](https://user-images.githubusercontent.com/17384333/63518536-88a22180-c4f1-11e9-8b51-6ebd68c6920a.png)

**Comment by bobdenotter** [comment]
@aarongerig Wow, thanks. 

I took that little nub to be a "Status == saved" notification. Because it has a green checkmark, and it was partially overlapped by the symfony toolbar, it didn't strike me to be a button at all. 

Thanks for taking the time to explain it to me!
