### ISSUE TITLE
2 Factor Auth seems to be broken

### ISSUE THREAD

**Issue by Sonja-Schubert** [pimcore/pimcore#4889]
# Bug Report

### Expected behavior
Login in to https://demo-basic.pimcore.org/admin , go to own user profile, press "Setup 2 Factor Authenication", scan qrcode with google authenticator app and enter code from app into backend input field

### Actual behavior
After pressing "Setup 2 Factor Authentication" a popup is shown up but no qrcode is generated. Closing the popup again does not change anything, login via username and password is still possible.

### Steps to reproduce
Go to https://demo-basic.pimcore.org/admin and login with admin user, go to own user profile, press "Setup 2 Factor Authentication"

**Comment by brusch** [comment]
This feature is disabled in our public online demo.
Unfortunately it was used many times to lock out other users from the admin interface 😟
Try it in your local installation and it will work as expected.
