### ISSUE TITLE
SET storage_engine is deprecated since MySQL 5.6

### ISSUE THREAD

**Issue by mroedel** [pimcore/pimcore#490]
Since MySQL 5.6, InnoDB is already the default.
  
If you want to set the storage_engine using MySQL > 5.6 the following warning occurs:

`2016-03-01T11:19:07+01:00 WARN (4):   2 MB | Pimcore\Resource\Mysql::getConnection() [87]: [Exception] with message: SQLSTATE[HY000]: General error: 1193 Unknown system variable 'storage_engine', query was: SET storage_engine=InnoDB;
In file: /home/vagrant/Code/pimcore.dev/pimcore/lib/Zend/Db/Statement/Pdo.php on line 235
#0 /home/vagrant/Code/pimcore.dev/pimcore/lib/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/vagrant/Code/pimcore.dev/pimcore/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /home/vagrant/Code/pimcore.dev/pimcore/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SET storage_eng...', Array)
#3 /home/vagrant/Code/pimcore.dev/pimcore/lib/Pimcore/Resource/Mysql.php(85): Zend_Db_Adapter_Pdo_Abstract->query('SET storage_eng...')
#4 /home/vagrant/Code/pimcore.dev/pimcore/lib/Pimcore/Resource/Wrapper.php(104): Pimcore\Resource\Mysql::getConnection(true)
#5 /home/vagrant/Code/pimcore.dev/pimcore/lib/Pimcore/Resource/Mysql.php(166): Pimcore\Resource\Wrapper->getResource()
#6 /home/vagrant/Code/pimcore.dev/pimcore/lib/Pimcore/Resource/Mysql.php(145): Pimcore\Resource\Mysql::set(Object(Pimcore\Resource\Wrapper))
#7 /home/vagrant/Code/pimcore.dev/pimcore/lib/Pimcore/API/Plugin/AbstractPlugin.php(58): Pimcore\Resource\Mysql::get()
#8 /home/vagrant/Code/pimcore.dev/plugins/Zendformbuilder/lib/Formbuilder/Plugin.php(110): Pimcore\API\Plugin\AbstractPlugin::getDb()
#9 /home/vagrant/Code/pimcore.dev/pimcore/lib/Pimcore/API/Plugin/Broker.php(81): Formbuilder_Plugin::isInstalled()
#10 /home/vagrant/Code/pimcore.dev/pimcore/lib/Pimcore.php(622): Pimcore\API\Plugin\Broker->registerPlugin(Object(Formbuilder_Plugin))
#11 /home/vagrant/Code/pimcore.dev/pimcore/lib/Pimcore.php(77): Pimcore::initPlugins()
#12 /home/vagrant/Code/pimcore.dev/index.php(18): Pimcore::run()
#13 {main}`

This warning blowing up my log file...

My suggestion is to cache the MySQL-Version in order to check it before setting the storage_engine in ./pimcore/lib/Pimcore/Resource/Mysql.php

**Comment by bbak** [comment]
That Variable Name was changed to 'default_storage_engine', but it still exists as of 5.7.
https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_default_storage_engine
