### ISSUE TITLE
Do not use MEMORY Storage-Engine

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#4901]
Percona produces this lock

```
[ERROR] WSREP: Percona-XtraDB-Cluster prohibits use of DML command on a table (fotobuchDB.locks) that resides in non-transactional storage engine with pxc_strict_mode = ENFORCING or MASTER
```

Guess that happens cause Pimcore creates a transaction and executes commands on the MEMORY locks table, thus Percona complaining about it. Not sure though

**Comment by brusch** [comment]
Let's change the locks table to `InnoDb` storage engine, not real benefit of the memory engine anyway.
