### ISSUE TITLE
Amazon AWS S3 Setup error: Unable to create directory / stream_get_meta_data(): supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by ceefour** [pimcore/pimcore#4907]
# Bug Report

Following instructions in https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Amazon_AWS_Setup/Amazon_AWS_S3_Setup.html

After doing the setup and trying to upload, there are errors in several steps.

### Expected behavior

Amazon S3 works and assets are stored there.

#### Error 1: `Exception: Unable to create directory`

Exception:
Unable to create directory: s3://media.lovia.life/assets/_default_upload_bucket for asset :102

DEBUG 12:45:52 php User Warning: Error executing "PutObject" on "https://s3.amazonaws.com/media.lovia.life/assets/_default_upload_bucket/"; AWS HTTP error: Client error: `PUT https://s3.amazonaws.com/media.lovia.life/assets/_default_upload_bucket/` resulted in a `403 Forbidden` response: AccessDeniedAccess DeniedB5A0D6 (truncated..

**Workaround**

Edit vendor/pimcore/pimcore/models/Asset.php : (is_dir()... parts)

        $destinationPath = PIMCORE_ASSET_DIRECTORY . $destinationPathRelative;

        $dirPath = dirname($destinationPath);
        if (!is_dir($dirPath) && substr($dirPath, 0, 3) !== "s3:") {
            if (!File::mkdir($dirPath)) {
                throw new \Exception('Unable to create directory: '. $dirPath . ' for asset :' . $this->getId());
            }
        }

        $typeChanged = false;

        // fix for missing parent folders
        // check if folder of new destination is already created and if not do so
        $newPath = dirname($this->getFileSystemPath());
        if (!is_dir($newPath) && substr($dirPath, 0, 3) !== "s3:") {
            if (!File::mkdir($newPath)) {
                throw new \Exception('Unable to create directory: '. $newPath . ' for asset :' . $this->getId());
            }
        }

After that workaround, we'll get to Error 2

#### Error 2: Uncaught PHP Exception ErrorException: "Warning: stream_get_meta_data(): supplied resource is not a valid stream resource"

Uncaught PHP Exception ErrorException: "Warning: stream_get_meta_data(): supplied resource is not a valid stream resource" at /var/www/pimcore/vendor/pimcore/pimcore/models/Asset.php line 1279

At this point I'm not sure what is the proper fix/workaround.

### Steps to reproduce

1. Install Pimcore 6.1.x
2. Follow https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Amazon_AWS_Setup/Amazon_AWS_S3_Setup.html
3. Try to upload image/asset

### References

* Documentation PR: https://github.com/pimcore/pimcore/pull/2755 (seems it worked with Pimcore 5.x)
* Initial request: #340 
* Pimcore talk: https://talk.pimcore.org/t/pimcore-shared-fs-can-we-replace-it-with-s3/130/7
* Pimcore talk: https://talk.pimcore.org/t/aws-s3-for-assets-in-pimcore-5/725/4

**Comment by brusch** [comment]
You're getting `403 Forbidden` from S3, so I guess it's a permission topic ... not Pimcore.

**Comment by ceefour** [comment]
@brusch it is not permission.

The error occurs because Pimcore Asset tries to mkdir() a "folder", which AWS S3 StreamWrapper *always* return access denied. In short, all mkdir() calls must be skipped when using S3, because S3 can create files inside any "folder" without creating them first.

**Comment by dpfaffenbauer** [comment]
@ceefour that is not true, mkdir worked fine for me on s3 in pimcore 5

**Comment by brusch** [comment]
Same for Pimcore 6 ... no difference there.

**Comment by ceefour** [comment]
https://github.com/aws/aws-sdk-php/issues/133 said that mkdir not supported for folders, but it's an old discussion.

it's also possible I got hit by this: https://github.com/aws/aws-sdk-php/issues/1779

**Comment by dpfaffenbauer** [comment]
I've had issues with ACLs one, try this:

```
<?php

use Aws\S3\S3Client;

$s3BucketName = getenv("S3_BUCKET");

if (!empty($s3BucketName)) {
    $s3Client = new S3Client([
        'version' => 'latest',
        'region' => getenv("S3_REGION"), // choose your favorite region
        'credentials' => [
            // use your aws credentials
            'key' => getenv('S3_KEY'),
            'secret' => getenv('S3_SECRET'),
        ],
    ]);

    // Set right ACL
    $default_opts = [
        's3' => [
            'ACL' => 'private',
            'seekable' => true
        ],
    ];

    $default = stream_context_set_default($default_opts);

    $s3Client->registerStreamWrapper();

// set default file context
    \Pimcore\File::setContext(stream_context_create([
        's3' => ['seekable' => true],
    ]));
}
```

**Comment by neoacevedo** [comment]
I try to create a directory just with a simple mkdir call: `mkdir('s3://myBucket/myDirectory/");` but I get an error:
> No client in stream context

**Comment by ghost** [comment]
Hi guys,
I'm working with Pimcore 6.9.3 and aws/aws-sdk-php v3.181.2 and I was also experiencing the same issue with creating folders in AWS S3 buckets. 
The workaround works just fine, but I want to solve this in a more sustainable way, without having to edit external code. 

@ceefour did you find a better way to solve this issue?
