### ISSUE TITLE
[Core][Device Detector] Read CloudFront headers

### ISSUE THREAD

**Issue by puecher** [pimcore/pimcore#4910]
# Feature Request
Improve the current Device Detector to read CloudFront headers

## Feature description
Use CloudFront headers if available, if not, continue with the User-Agent string.

We can use for example https://github.com/serbanghita/Mobile-Detect.

**Comment by brusch** [comment]
@puecher can you please verify that this patch works: 
https://patch-diff.githubusercontent.com/raw/pimcore/pimcore/pull/4921.patch

Thanks a lot!

**Comment by puecher** [comment]
Thank you for your fast response.

The $userAgent is never 'Amazon CloudFront', so we have to set it.

See https://github.com/serbanghita/Mobile-Detect/blob/master/Mobile_Detect.php#L796 and https://github.com/serbanghita/Mobile-Detect/blob/master/Mobile_Detect.php#L865.

At the moment we use:

```php
        // check CloudFront headers
        if (isset($_SERVER['HTTP_CLOUDFRONT_IS_MOBILE_VIEWER']) && $_SERVER['HTTP_CLOUDFRONT_IS_MOBILE_VIEWER'] === 'true') {
            $type = 'phone';
        }
        if (isset($_SERVER['HTTP_CLOUDFRONT_IS_TABLET_VIEWER']) && $_SERVER['HTTP_CLOUDFRONT_IS_TABLET_VIEWER'] === 'true') {
            $type = 'tablet';
        }

        // default is desktop
        if (!$type) {
            $type = $this->default;
        }
```

**Comment by brusch** [comment]
@puecher ah, great - I've updated the PR, can you please check again! 
Thanks!

**Comment by puecher** [comment]
```php
        // check CloudFront headers
        foreach (['mobile', 'tablet', 'desktop'] as $cfType) {
            $cfHeaderName = 'HTTP_CLOUDFRONT_IS_' . strtoupper($cfType) . '_VIEWER';
            if (isset($_SERVER[$cfHeaderName]) && $_SERVER[$cfHeaderName] === 'true') {
                if ($cfType === 'mobile') {
                    $type = 'phone';
                } else {
                    $type = $cfType;
                }
            }
        }
```

Should do the trick.

**Comment by brusch** [comment]
@puecher oh dear, thanks a lot :)
