### ISSUE TITLE
[Workflows] Additional field of type "user" has no entries

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#4922]
When adding an additional field of type "user" to a transition, the overlay shows only an empty select field.

As a quick fix, I have modified the [enrichNotes method in ActionsButtonService](https://github.com/pimcore/pimcore/blob/master/lib/Workflow/ActionsButtonService.php#L95-L105), but I don't know of that would be the correct place for this change. I have added this:
```
if (!empty($notes['additionalFields'])) {
    foreach ($notes['additionalFields'] as $key => $additionalField) {
        if ($additionalField['fieldType'] === 'user') {
            $def = new \Pimcore\Model\DataObject\ClassDefinition\Data\User();
            $def->configureOptions();

            $notes['additionalFields'][$key]['fieldTypeSettings']['options'] = $def->getOptions();
        }
    }
}
```

This could also go to the [NotesAwareTrait](https://github.com/pimcore/pimcore/blob/master/lib/Workflow/Notes/NotesAwareTrait.php) instead

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
