### ISSUE TITLE
Duplicate editable name everywhere

### ISSUE THREAD

**Issue by dasraab** [pimcore/pimcore#494]
I´ve made an update from Pimcore 3.1 to latest Version 4.0.0-b4 (Build: 3684). When i do open a Document in editmode i get lots of "Duplicate editable name"-Errors. My views didn´t change since the update. There are no duplicate Items in the views.

There are no duplicate entrys in documents_elements db table either.

Do you guys have any idea how to fix this issue?

**Comment by brusch** [comment]
- Using ExtJS 3.4 or the new ExtJS 6.0?
- Open your JS console, see if there are any errors
- Open HTML source of the editing iframe ("view frame source", check if there are any duplicate editable names in it `editableConfigurations.push(....`
- Open your JS debugger, add a breakpoint here: https://github.com/pimcore/pimcore/blob/master/pimcore/static6/js/pimcore/document/edit/startup.js#L116

**Comment by dasraab** [comment]
Hi Bernhard,
1. using extjs 3.4
2. there are no js errors in the console
3. there are no duplicates in  .push() method

**Comment by dasraab** [comment]
the problem also exists in extjs6

**Comment by dasraab** [comment]
![screenshot 2016-03-02 07 59 25](https://cloud.githubusercontent.com/assets/1923919/13452932/bc2f00dc-e04c-11e5-94b7-f1fab03d0d70.png)

**Comment by brusch** [comment]
Ok, that's strange, ... then it's necessary to use the JS debugger. 
You have to find out why there are duplicate names in the variable "editableNames".
https://github.com/pimcore/pimcore/blob/master/pimcore/static6/js/pimcore/document/edit/startup.js#L116 

Shouldn't be too hard to debug this :)

**Comment by dasraab** [comment]
Hi Bernhard, it seems like 
<script type="text/javascript" src="/pimcore/static/js/pimcore/document/edit/startup.js?_dc=3685"></script> 
is added twice to the document in editmode.

where does pimcore add this line of code? is this a problem with backwardcompatibility?

**Comment by brusch** [comment]
This code is generated by: 
https://github.com/pimcore/pimcore/blob/be88bf70882ede6111b48bbca6ae0ea0a28670d9/pimcore/models/Document/Tag.php#L110-L110

The editables: 
area, areablock, block and video have their own implementation of admin().

**Comment by dasraab** [comment]
i´ve got the problem.
i accidentally had two closing body tags in my layout. the startup.js file is included before those closing-tags. so it was included twice.
thanks for your help!

**Comment by brusch** [comment]
ok, thanks for your feedback!

**Comment by brusch** [comment]
I've just made the following changes 6f45f7a862c8f94433c9d107bba0f3cf381e56ca , this should avoid such problems in the future :)

**Comment by dasraab** [comment]
perfect, thank you!

**Comment by ceefour** [comment]
I got this issue too. But in my case, it's because I called `pimcore_href` twice in my template. I didn't realize it because I was using it to do selective layout on both mobile & desktop. Solution is to put the "duplicate" stuff inside `{% if not editmode %}`.
