### ISSUE TITLE
[Data Object]  array_unique for ManyToMany relations is not working in every use-case

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#4958]
To check weither many-to-many relations in pimcore are unique, it uses array_unique internally on save:

https://github.com/pimcore/pimcore/blob/d35fb259cdce0867b42b65d7d121c2bdc01b8a4b/models/DataObject/Concrete.php#L128

But: array_unique compares object by its __toString function, if you overwrite it, and you are not producing unique issues, pimcore filters out non unique values as well. It would be better if pimcore internally iterates over the values and checks for the actual id's and types.

PS: Not even sure if that works if an asset and an object sit in the same place. (cause pimcore implements the __toString function and returns the full-path for the element)

**Comment by dpfaffenbauer** [comment]
thanks, solution looks good, does this also cover ManyToMany Metadata? Where $item is not an Element, it is a ElementMetadata

**Comment by brusch** [comment]
yep, that's why the tests are failing - I'm on it already :)

**Comment by brusch** [comment]
@dpfaffenbauer ok, took longer than expected, but now it should be finally fixed ☺

**Comment by dpfaffenbauer** [comment]
seems good to me.

thanks

**Comment by aarongerig** [comment]
@brusch Since the milestone 6.2.1 is completed, when can we expect the release? We need this fix as well.

**Comment by brusch** [comment]
@aarongerig release is planned for next week (17 Sep.), maybe even earlier.
