### ISSUE TITLE
Optimization: Installing Pimcore demo shop - It takes ages

### ISSUE THREAD

**Issue by Heiko-H** [pimcore/pimcore#4959]
# Optimization request

### Expected behavior
I except to have a working demo shop ready in less than 5 minutes. 

### Actual behavior
It takes more than 20 min to setup a demo shop. The problem is that some database tables are huge. The table _ecommerceframework_vouchertoolkit_tokens_ for example has more than 100.000 rows. 

### Steps to reproduce
Install pimcore demo shop via console
```
COMPOSER_MEMORY_LIMIT=-1 composer create-project pimcore/demo-ecommerce my-project
```

### Suggested solution
Delete old data from demo shop database so that the pimcore is clean and can be installed fast.

**Comment by brusch** [comment]
For me the installation of the database takes only about 1 minute, maybe take a look at the config of your db server. 
In general ... the demo is there to show some example data, so it doesn't make sense to get rid of it ;-)
