### ISSUE TITLE
[ASSETS] upload from Asset in Tree should update Preview Window in Main View

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#4960]
# Feature Request

after an asset upload in the asset tree the main view window of the folder should update if it is open.

![main_window](https://user-images.githubusercontent.com/1086343/64588245-2c207c80-d3a2-11e9-976f-18caa8abd48b.png)

**Comment by skoch98** [comment]
I made this wish come true :wink:

However, I have implemented this so that it does not only happen with the upload, it also happens when moving, deleting, inserting, renaming and more...

Let's see if pimcore accepts the change :grimacing:

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
