### ISSUE TITLE
Inconsistent user interface for schedule and versions

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#4961]
# Bug Report

There is a user interface mismatch which came to light when demonstrating content editors.

### Expected behavior

The same sort by (descending or ascending) should be used on all locations.

### Actual behavior

On the *Versions* tab the date and time is sorted descending
On the *Schedule* tab the date and time is sorted ascending.

### Steps to reproduce

Open a Data object, save it more than once.
Go to the *Versions* tab, the latest version is on top of the list
Go to the *Schedule* tab, open the dropdown, the latest version is on the bottom of the list.

**Comment by skoch98** [comment]
Hi @NiklasBr,

this has already been changed in Pimcore version 6.2.

See the following Issues and Commit for details:
#4556
 7f9525347ff8969a683c0b37d6c40f2592208967

**Comment by NiklasBr** [comment]
Great! :)

**Comment by NiklasBr** [comment]
@brusch Just updated to 6.2.1 and the *Versions* tab does not sort correctly.
