### ISSUE TITLE
Redirects: moving document from one site to another

### ISSUE THREAD

**Issue by Maksonis** [pimcore/pimcore#4967]
In System Settings I have checked an option "Create automatically a redirect when a page is moved or renamed", and I moved document from one site to another one, but the created redirect is not working. It has wrong Source and Target site. 
If I change source (by removing site key) and correct Source and Target Site it works.

Tested on the latest pimcore version.

**Comment by brusch** [comment]
@dvesh3 can you please check if we can solve that pragmatically? 
If not, we should at least issue a warning. Thanks!
