### ISSUE TITLE
No fallback language in the Webservice API

### ISSUE THREAD

**Issue by patrickfabrizius** [pimcore/pimcore#4981]
# Bug Report

### Expected behavior
When GET:ing /webservice/rest/object/id/x, a localized field that is empty should contain a value following the fallback language chain, if applicable, just as when using Pimcores internal API ( $object->getMytext($language); )

### Actual behavior
The value is null

### Steps to reproduce
* Setup at least two languages with one language using the other as a fallback language
* Create a object class with a text field inside a localizedFields field
* Create a object using the class, populate the field for the default language, leave the field for the other language empty
* Simulate a GET request on /webservice/rest/object/id/<OBJECT_ID>

### Code example
N/A

[class_test_export.json.zip](https://github.com/pimcore/pimcore/files/3610654/class_test_export.json.zip)

# Feature Request

**Comment by brusch** [comment]
The REST API actually returns the data as is on the object, this is on purpose e.g. for syncing data between 2 instances.
