### ISSUE TITLE
layout file in send newsletter not found in pimcore 4

### ISSUE THREAD

**Issue by choppe3766** [pimcore/pimcore#4985]
# Bug Report

The layout file, which are defined in the controller, was not found, but it always exists in the directory /website/views/scripts/layouts and is readable.
It's look like the layout directory could not found, which it set in the controller.
If i set the layout path in the controller, it works.

Error and stack trace:

URL: /admin/newsletter/send-test
Params:

Fatal error:  Uncaught Zend_View_Exception: script 'newsletter.php' not found in path (/var/www/vhosts/kundensysteme.de/kiaorasports.de/pimcore/modules/admin/views/scripts/:/var/www/vhosts/kundensysteme.de/kiaorasports.de/pimcore/modules/admin/views/layouts/:/var/www/vhosts/kundensysteme.de/kiaorasports.de/pimcore/modules/admin/views/layouts/:/var/www/vhosts/kundensysteme.de/kiaorasports.de/pimcore/modules/admin/views/scripts/) in /var/www/vhosts/kundensysteme.de/kiaorasports.de/vendor/zendframework/zendframework1/library/Zend/View/Abstract.php:988
Stack trace:
#0 /var/www/vhosts/kundensysteme.de/kiaorasports.de/vendor/zendframework/zendframework1/library/Zend/View/Abstract.php(884): Zend_View_Abstract->_script('newsletter.php')
#1 /var/www/vhosts/kundensysteme.de/kiaorasports.de/vendor/zendframework/zendframework1/library/Zend/Layout.php(796): Zend_View_Abstract->render('newsletter.php')
#2 /var/www/vhosts/kundensysteme.de/kiaorasports.de/pimcore/models/Document/Service.php(123): Zend_Layout->render()
#3 /var/www/vhosts/k in /var/www/vhosts/kundensysteme.de/kiaorasports.de/vendor/zendframework/zendframework1/library/Zend/View/Abstract.php on line 988

### Expected behavior
on click on button "Send Test-Newsletter" in newsletter sending panel a newsletter should be send out

### Actual behavior
on click on the button "Send Test-Newsletter"  an poppu with a server error occurs, see the atacched image
![Bildschirmfoto 2019-09-15 um 18 19 07](https://user-images.githubusercontent.com/6122199/64924517-b07d6000-d7e5-11e9-9e7f-a9d84ecd85d2.png)

I has updated from version 3.11 to 4.6.5.
After getting these error, i replaced the folders pimcore and vendor with the sources from these repository (the idea behind: there are some files missing during the update process). Then i replaces the current composer.json with the version from this repository and call "composer update". This works without errors.

### Steps to reproduce
in pimcore 4.6.5 create a new newsletter, insert all needed informations and click on "Send Test-Newsletter".

### PHP-Code in the NewsletterController.php
`
$this->layout()->setLayoutPath(__DIR__ . '/../views/layouts');
$this->layout()->setLayout('newsletter');
`

**Comment by brusch** [comment]
Sorry, v4 is not supported anymore 😐
