### ISSUE TITLE
headLink()->appendAlternate (pimcore_head_link) should omit type & title attributes if empty

### ISSUE THREAD

**Issue by ceefour** [pimcore/pimcore#4986]
### Expected behavior

```html
<link href="https://lovia.life/" rel="alternate" hreflang="en" />
```

### Actual behavior

```html
<link href="https://lovia.life/" rel="alternate" type="" title="" hreflang="en" />
```

### Code example

```twig
{% do pimcore_head_link().appendAlternate("https://lovia.life/", null, null, {'hreflang': 'en'}) %}
```

**Comment by nicklassandell** [comment]
I also think this should be corrected. For now, you can exclude the unwanted attributes through the `$extras` parameter, like so:

    {% do pimcore_head_link().appendAlternate(canonicalUrl, 'canonical', null, { rel: null, title: null }) %}

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
