### ISSUE TITLE
Inheritance performance issue

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#4997]
# Improvement Request
Saving an object with localized fields, a lot of child-nodes and inheritence enablde, the `doUpdate()` method in https://github.com/pimcore/pimcore/blob/master/models/DataObject/Concrete/Dao/InheritanceHelper.php#L203 may take over 10 seconds for each language. In our case there where about 210.000 child nodes and 10 languages. So saving the object even though nothing changed and not even a single field contained any data took several minutes. To me the main levers are in the following code sections:

1. https://github.com/pimcore/pimcore/blob/master/models/DataObject/Concrete/Dao/InheritanceHelper.php#L361
    a) Loading several thousands of ids at once takes some time: https://github.com/pimcore/pimcore/blob/master/models/DataObject/Concrete/Dao/InheritanceHelper.php#L367
    b) Recursive iteration and building the std class tree takes a lot of time: https://github.com/pimcore/pimcore/blob/master/models/DataObject/Concrete/Dao/InheritanceHelper.php#L394
2. Performing an `IN `mysql statement on an array containing a quater of a million ids also takes a lot of time and may even exceed the max query length `max_allowed_packet`.

I gues there are several options for improvement:

1. Improve the dirty detection and only perform a data save if data actually changed.
2. Optimize queries and data structures mentioned above

This issue may be related to https://github.com/pimcore/pimcore/issues/4154.

**Comment by weisswurstkanone** [comment]
also see #1149

**Comment by weisswurstkanone** [comment]
@jremmurd could you please provide the exact data model please?

**Comment by brusch** [comment]
Should be all resolved by the linked PRs.
