### ISSUE TITLE
[Feature Request] Alternative to minipaint

### ISSUE THREAD

**Issue by julmot** [pimcore/pimcore#5003]
# Feature Request

## Feature description

I'd love to see a documentation of integrating alternatives of [minipaint](https://viliusle.github.io/miniPaint/) into Pimcore, like e.g. [Photopea](https://www.photopea.com/). It looks more professional and is easy to use for those that are familiar with Photoshop.

What are your thoughts about this?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
