### ISSUE TITLE
Documentation | Input Quantity Value

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#5005]
# Feature Request
It might be helpful to have a cross-reference in the documentation between

- "Quantity Value"  https://pimcore.com/docs/5.x/Development_Documentation/Objects/Object_Classes/Data_Types/Number_Types.html  
- and "Input Quantity Values" https://pimcore.com/docs/5.x/Development_Documentation/Objects/Object_Classes/Data_Types/Number_Types.html 

as some users, who are familiar with the Quantity Value concept, are not aware of this alternative, and might overlook it.

What about adding a warning at the end of the Quantity Values section with a link to the Input Quantity Value datatype?

**Comment by weisswurstkanone** [comment]
@andreas-gruenwald , can you provide a PR for that ?
