### ISSUE TITLE
[DataObject] MultiSelection value with commas not working

### ISSUE THREAD

**Issue by ramundomario** [pimcore/pimcore#5010]
# Bug Report

### Expected behavior
Insert a value with commas in Selection Options of Multiselection type into DataObject class definition.
After save an object and reload, retrieve correct value.

### Actual behavior
Currently after an object is saved & refreshed, the value previously selected (with commas) is not shown

### Steps to reproduce

1. Insert a value with commas in Selection Options of Multiselection type into DataObject class definition.
 <img width="1402" alt="class_definition" src="https://user-images.githubusercontent.com/16133208/65531891-2e82ea80-defb-11e9-934b-c9e8681e73aa.png">
2. Select this value with commas into object creation
<img width="1408" alt="object_creation" src="https://user-images.githubusercontent.com/16133208/65532012-5c682f00-defb-11e9-898a-a0eef19903cd.png">
3. Reload object without correct value selected
<img width="1404" alt="object_reload" src="https://user-images.githubusercontent.com/16133208/65532058-730e8600-defb-11e9-8105-79d12106b041.png">

This is the value saved into the database:
<img width="1404" alt="database_value" src="https://user-images.githubusercontent.com/16133208/65532088-7efa4800-defb-11e9-88a6-970a02064b67.png">

Since the values are saved with commas in the multiselect data type into database, it seems that the values are saved as two distinct elements.

**Comment by HeikoNF** [comment]
This issue is more than a year old and it ist still not possible to use commas neither as key nor as value in multiselects. Is there any known workaround or plan to changed this in the near future?

**Comment by podarcis** [comment]
We just got hit by this bug/behavior, too.

Imagine having values for a field `scale` with possible values `1:2` and `1:2,5`. The field value is stored as `1:2,1:2,5` and thus values `1:2`, `1:2` and `5` are read back.

**Comment by MadeP** [comment]
Strangely enough, this was not a problem in PIMCORE 6. In PIMCORE X it suddenly doesn't work anymore.

**Comment by podarcis** [comment]
@MadeP Please elaborate on what's not working anymore. Previously commas were accepted but led to silent data loss. Now there's a sanity check as a workaround in place, which just prevents commas.

**Comment by MadeP** [comment]
Ok, the silent loss could not be determined in the way so far. Have checked and it is true. Then the workaround that no commas are allowed is probably best for now. Would still be good if commas work in the future though.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
