### ISSUE TITLE
Localised fields in Object brick do not work in Listing

### ISSUE THREAD

**Issue by AroraVaishali** [pimcore/pimcore#5017]
# Bug Report

### Steps to reproduce
1) Create object brick
2) Add a localised field (text) , click on property "Visible in Grid View"
3) When we list that class "Call to a member function supportsInheritance() on null " popup will come
### Code example
```php
// your code
```

# Feature Request

## Feature description
Reference.
https://github.com/pimcore/pimcore/issues/2809
https://github.com/pimcore/pimcore/issues/2810

**Comment by weisswurstkanone** [comment]
Unable to reproduce on demo.pimcore.fun

maybe already fixed, see https://github.com/pimcore/pimcore/issues/5083

**Comment by weisswurstkanone** [comment]
@AroraVaishali any feedback?

**Comment by AroraVaishali** [comment]
@weisswurstkanone Yes, it is working fine. I checked in version 6.3.6

**Comment by weisswurstkanone** [comment]
thx for checking!
