### ISSUE TITLE
Not enough "Weißbier" at third table

### ISSUE THREAD

**Issue by joschi127** [pimcore/pimcore#5019]
# Bug Report

### Expected behavior
Lot of "Weisse Weißbier" 

### Actual behavior
Only "Helles" brought to the table 

### Steps to reproduce
Try to ask for some beer

### Code example
```php
// your code
```

**Comment by joschi127** [comment]
![IMG_20190926_193430](https://user-images.githubusercontent.com/1758468/65711268-d67feb80-e094-11e9-99ee-bea8d1ef1f40.jpg)

Ah. Very nice. Improved a lot already now with the latest update.

Issue can be closed. Thanks for the super quick fix.

**Comment by weisswurstkanone** [comment]
well documented ;-)
