### ISSUE TITLE
Add CustomLayout "name" to CustomLayout  JSON export

### ISSUE THREAD

**Issue by FredoVelcro-zz** [pimcore/pimcore#5023]
Hello,

We are using CustomLayout export / import and i wonder why the "name" field is not exported : 

https://github.com/pimcore/pimcore/blob/b9cb305e60518a3b4968d9227fb1f8a11603b43d/bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php#L631

It's would be easier instead of retrieving the name from the filename...

Thanks for considering this.

**Comment by aryaantony92** [comment]
Fixed by #12420
