### ISSUE TITLE
Incorrect values of breadcrumb & navigation shown when Full Page Cache is enabled.

### ISSUE THREAD

**Issue by avinashpimcore** [pimcore/pimcore#5024]
Upon enabling full page cache with 3600 sec lifetime, pimcore navigation (pimcore_build_nav) doesn't work properly if it called from any snippet. It is working fine if we place navigation directly in the layout file.

It can be reproduced with demo-twig instance after enabling full page cache and setting the lifetime to any bigger value. Also, need to place the breadcrumb in any snippet.

**Comment by dvesh3** [comment]
can you please explain "doesn't work properly!" issue in detail? thanks!

**Comment by dvesh3** [comment]
Snippets are master for multiple pages so if you using `pimcore_inc` in your layout file to include snippets please provide extra param for output cache hashing https://pimcore.com/docs/5.x/Development_Documentation/MVC/Template/Templating_Helpers/index.html#page_section_17
e.g.
```twig
pimcore_inc(document, {current_document_id: 123});
```
