### ISSUE TITLE
XLIFF Export 

### ISSUE THREAD

**Issue by GALCF** [pimcore/pimcore#5030]
# Bug Report

The XLIFF Export MultiSelect handles IDs as the unique identifier for dataobjects as well as documents. This leads to conflicts if a document and an object have the same ID.

### Expected behavior
Export should handle all dataobject and document entries provided.

### Actual behavior
Export removes duplicate IDs (Some dataobject and document have the same ID)

### Steps to reproduce
* Log into [Pimcore Demo](https://demo.pimcore.fun/admin)
* Open [Manufacturer Fiat Object](https://demo.pimcore.fun/admin/login/deeplink?object_100_object)
* Open [Classic Car Culture Document](https://demo.pimcore.fun/admin/login/deeplink?document_100_page)
* Try to add both of them to the XLIFF Export List
* Only one of the items will be shown at the same time

### Proposed solution

Replacing the IDs [here](https://github.com/pimcore/pimcore/blob/v6.2.1/bundles/AdminBundle/Resources/public/js/pimcore/settings/translation/xliff.js#L128) and [here](https://github.com/pimcore/pimcore/blob/v6.2.1/bundles/AdminBundle/Resources/public/js/pimcore/settings/translation/xliff.js#L175) with a more unique reference should do the trick.

**Comment by brusch** [comment]
Important to consider is the compatibility to older versions ... e.g. export on 6.1.1 import on 6.6.7 ...
