### ISSUE TITLE
When saving a data object, index definitions are not applied to the object_query table.

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#5031]
# Bug Report
In my product's class definition there is a field called "remoteId". I recognized performance issues in relation with the product, so I revised the field's index definition:

First of all, the field is marked as "unique", so I assumed that the database definition (object_query_product) would contain a key with a "unique index" definition, or at least a non-unique index. However this was not the case.

### Expected behavior
- index flag creates a SQL index for the field "remoteId" in the object_store table.
- index flag creates a SQL index for the field "remoteId" in the object_query table.
- unique flag creates a SQL "unique" index constraint  for the field "remoteId" in the object_store table.
- unique flag creates a SQL "non-unique" index constraint  for the field "remoteId" in the object_query table (as unique in query_tables is a too big constraint).

### Actual behavior
- Indices are created for the store tables, but no index is created for the query table at all.

### Steps to reproduce
- Create a product class.
- add a text field named "remoteId".
- Save the class definition.
- Make some changes.
- Edit the class definition and mark the field as "unique" and "index".
- Index is not updated (may require that there are many products/objects in Pimcore).

### Pimcore Version
Your Version: v5.8.0

**Comment by andreas-gruenwald** [comment]
We will look at it in our application anyway. However, I wanted to report it, as it seems to be a critical issue.

**Comment by fashxp** [comment]
hmm, cannot be reproduced on demo application. 

on which table are you checking?

**Comment by andreas-gruenwald** [comment]
Please see my screenshot:
$considerUniqueIndex is false for the table "object_query_product", so both, unique index, and index are getting disabled, if both "index" and "unique" are selected. If only "unique" is selected, then it seems that also no index is set on the object_query_product table. 

![image](https://user-images.githubusercontent.com/16687355/65997147-1e3db300-e499-11e9-8445-dd3a0fbd691e.png)

Is this on purpose? In my opinion, the query table should at least receive a index.

**Comment by andreas-gruenwald** [comment]
Issue description updated.

**Comment by weisswurstkanone** [comment]
just as a reference but not directly related to it
https://github.com/pimcore/pimcore/issues/2943
