### ISSUE TITLE
Syntax error or access violation: 1305 FUNCTION pimcore_ecomm.PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS does not exist

### ISSUE THREAD

**Issue by Digital-Media-Team** [pimcore/pimcore#5032]
After installing pimcore/ecommerce :"v6.2.1 build 7cf81c67e93e113ef855ff3643f5fda328f3f6af",  i am getting this error message. 

An exception occurred while executing 'SELECT PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS(?)' with params [16]: SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION pimcore_ecomm.PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS does not exist

Server threw exception - could not perform action. Please reload the admin interface and try again.

"
Timestamp: Tue Oct 01 2019 12:32:21 GMT+0300 (Arabian Standard Time)
Status: 500 | Internal Server Error
URL: /admin/customermanagementframework/segment-assignment/inheritable-segments?id=19&type=document&_dc=1569922340472
Method: GET
Message: An exception occurred while executing 'SELECT PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS(?)' with params [16]:

SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION pimcore_ecomm.PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS does not exist
Trace: 
#0 /opt/bitnami/apps/pimcore/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(169): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /opt/bitnami/apps/pimcore/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'An exception oc...')
#2 /opt/bitnami/apps/pimcore/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(911): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT PLUGIN_C...', Array)
#3 /opt/bitnami/apps/pimcore/htdocs/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(93): Doctrine\DBAL\Connection->executeQuery('SELECT PLUGIN_C...', Array, Array, NULL)
#4 /opt/bitnami/apps/pimcore/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(578): Pimcore\Db\Connection->executeQuery('SELECT PLUGIN_C...', Array, Array)
#5 /opt/bitnami/apps/pimcore/htdocs/vendor/pimcore/customer-management-framework-bundle/src/SegmentAssignment/StoredFunctions/DefaultStoredFunctions.php(24): Doctrine\DBAL\Connection->fetchColumn('SELECT PLUGIN_C...', Array)
#6 /opt/bitnami/apps/pimcore/htdocs/vendor/pimcore/customer-management-framework-bundle/src/SegmentManager/DefaultSegmentManager.php(159): CustomerManagementFrameworkBundle\SegmentAssignment\StoredFunctions\DefaultStoredFunctions->retrieve('16', 'document')
#7 /opt/bitnami/apps/pimcore/htdocs/vendor/pimcore/customer-management-framework-bundle/src/Controller/Admin/SegmentAssignmentController.php(53): CustomerManagementFrameworkBundle\SegmentManager\DefaultSegmentManager->getSegmentsForElementId('16', 'document')
#8 /opt/bitnami/apps/pimcore/htdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): CustomerManagementFrameworkBundle\Controller\Admin\SegmentAssignmentController->inheritableSegments(Object(Symfony\Component\HttpFoundation\Request))
#9 /opt/bitnami/apps/pimcore/htdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /opt/bitnami/apps/pimcore/htdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(198): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /opt/bitnami/apps/pimcore/htdocs/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#12 {main}"

**Comment by dvesh3** [comment]
duplicate https://github.com/pimcore/demo/issues/142
