### ISSUE TITLE
Deadlock with WebService parallel creation of objects with multiple references on "dependencies" table

### ISSUE THREAD

**Issue by Mariano76** [pimcore/pimcore#504]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [x] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [ ] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) : Tested on version 3.1.1 (Build: 3543)
- [x] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [x] There's no existing ticket for the same issue

## Please answer the following questions 

Tested on version 3.1.1 (Build: 3543)

### Expected behavior 
Multiple parallel creation of objects  should not create deadlocks on database.

### Actual behavior  
Parallel creation of objects with multiple references causes deadlock and fails in unpredictable manner.
This is the error reported in Pimcore debug.log:

```
2016-03-03T18:06:17+01:00 EMERG (0):  12 MB | Pimcore\Model\AbstractModel->__call() [254]: [Exception] with message:
 SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction,
  query was: INSERT INTO `dependencies` (`sourceid`, `sourcetype`, `targetid`, `targettype`) VALUES (?, ?, ?, ?)
```

In MySql the deadlock is reported like this:
```
------------------------
LATEST DETECTED DEADLOCK
------------------------
2016-03-04 10:24:22 7f38731b8700
*** (1) TRANSACTION:
TRANSACTION 50110467, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
LOCK WAIT 6 lock struct(s), heap size 1184, 3 row lock(s), undo log entries 1
MySQL thread id 7004, OS thread handle 0x7f387011e700, query id 4512165 10.0.0.6 pimcoreuser update
INSERT INTO `dependencies` (`sourceid`, `sourcetype`, `targetid`, `targettype`) VALUES ('156348', 'object', '156345', 'object')
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 37525 page no 1001 n bits 608 index `PRIMARY` of table `pimcore`.`dependencies` trx id 50110467 lock_mode X insert intention waiting
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

*** (2) TRANSACTION:
TRANSACTION 50110472, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
6 lock struct(s), heap size 1184, 3 row lock(s), undo log entries 1
MySQL thread id 7002, OS thread handle 0x7f38731b8700, query id 4512169 10.0.0.6 pimcoreuser update
INSERT INTO `dependencies` (`sourceid`, `sourcetype`, `targetid`, `targettype`) VALUES ('156349', 'object', '156346', 'object')
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 37525 page no 1001 n bits 608 index `PRIMARY` of table `pimcore`.`dependencies` trx id 50110472 lock_mode X
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 37525 page no 1001 n bits 608 index `PRIMARY` of table `pimcore`.`dependencies` trx id 50110472 lock_mode X insert intention waiting
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

*** WE ROLL BACK TRANSACTION (2)
``` 
### Steps to reproduce  
Create a class definition with two or more object references and load the system with parallel creation of several objects through WebService.

### Code example 
None

**Comment by brusch** [comment]
But the transaction is restarted and the object is created, right?

**Comment by brusch** [comment]
see also: 
https://github.com/pimcore/pimcore/blob/4d8c3177bd6504a930ad87da2f55c9142d3c566f/pimcore/models/Object/AbstractObject.php#L550-L550

**Comment by Mariano76** [comment]
No, we found that the object is not created at all. I think that in our environment where we are trying to create thousands of objects with a parallelism of 10 concurrent processes the 5-retry loop maybe fails. I'll check if this is the case.

**Comment by brusch** [comment]
Ok, thanks!

**Comment by Mariano76** [comment]
I confirm that the transactions fails after 5 retries, with the following message:
    2016-03-09T20:55:42+01:00 ERR (3): 771 MB | Pimcore\Model\Object\AbstractObject->save() [611]:
    Finally giving up restarting the same transaction again and again, last message: SQLSTATE[40001]:
    Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was:
    INSERT INTO `dependencies` (`sourceid`, `sourcetype`, `targetid`, `targettype`) VALUES (?, ?, ?, ?)

**Comment by brusch** [comment]
It seems that your server is pretty busy at this time, so probably you should optimize your setup to allow this amount of cuncurrent jobs. 

Maybe you'll also need to optimize your class model, since over 700mb of memory usage (see log message above) seems a way too much to me. 

In general there isn't much we (in pimcore) can do about this, increasing the amount of retries would be just a workaround and deadlocks in general are not avoidable in multi-threaded/process environments. So it's all about optimizing the throughput of your MySQL server.
