### ISSUE TITLE
Delete button is always present, even with no delete permission

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#5048]
Hello,

The delete action is always present in the grid mode, even if the user don't have the permission to delete. Even if a denied message is return (check permission on php side), it would be more reassuring for final pimcore users if it is not displayed.

Here is an example on the website demo online :

![delete](https://user-images.githubusercontent.com/9025839/66079947-67f3cf80-e565-11e9-939d-429024cc8005.jpg)

I know this can be tiedous to manage as the grid can display objects from subfolder having different permissions. But same problematic exists for the tree object too and is well handled ?

Purpose of this issue is to:
- no more display delete action if the user cannot delete
- maybe check all is ok on the object tree too

Thanks

**Comment by weisswurstkanone** [comment]
I think that is hard the achieve when it comes to multiselections.

**Comment by NiklasBr** [comment]
I think this issue is related: #4943 where the *Unpublish* action is possible in grid view but not on single data objects.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
