### ISSUE TITLE
Missing UUIDs 

### ISSUE THREAD

**Issue by slaumann** [pimcore/pimcore#505]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [X] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [X] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [X] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [X] There's no existing ticket for the same issue

### Expected behavior 
To get an individual UUID per Object in Pimcore 4 (like in Picmore 3.11)
### Actual behavior  
Get the same UUID for each Object
### Steps to reproduce  
Get UUID for some Objects
  
### Code example 
```php

$Object = Object_Concrete::getById(211);
$uuid = Tool_UUID::getByItem($Object);
$uuid = $uuid->getUuid();
echo $uuid;

echo "<hr>";

$Object = Object_Concrete::getById(138);
$uuid = Tool_UUID::getByItem($Object);
$uuid = $uuid->getUuid();
echo $uuid;
```

### Result
05142cfc-c559-50dd-8c5f-37ee49eb71ad
05142cfc-c559-50dd-8c5f-37ee49eb71ad

**Comment by weisswurstkanone** [comment]
build 3693
