### ISSUE TITLE
calling classification store function with invalid id

### ISSUE THREAD

**Issue by AlternateIf** [pimcore/pimcore#5056]
Upon calling the getLocalizedKeyValue function an error occurs if the key-id given does not exist since there would be an call of getType on null. According to PHPDoc we should return null in the case of $keyValue being null or add a throw tag to the doc

https://github.com/pimcore/pimcore/blob/4539b5d6b35a02021ed8d11aebfe1e6600433888/models/DataObject/Classificationstore.php#L347

**Comment by weisswurstkanone** [comment]
can you create a PR ?
