### ISSUE TITLE
New Installation with installer fails with MySQL Error

### ISSUE THREAD

**Issue by Jan0707** [pimcore/pimcore#5057]
### Expected behavior

A fresh installation should be running flawlessly after successful completion of installer command.

### Actual behavior

Running into MySQL error:

```
An exception occurred while executing 'SELECT PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS(?)' with params [1]:

SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION project_database.PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS does not exist
```

### Steps to reproduce

`$ COMPOSER_MEMORY_LIMIT=-1 composer create-project pimcore/demo-ecommerce pimcore-demo`
`$ mysql -u root -p -e "CREATE DATABASE project_database charset=utf8mb4;"`
`$ cd ./my-project`
`$ ./vendor/bin/pimcore-install`

As outlined in : https://pimcore.com/docs/5.x/Development_Documentation/Getting_Started/Installation.html

### Code example
none

It seems that some function was not properly created, but I cannot seem to find it / add it manually to the database ...

**Comment by AlternateIf** [comment]
@Jan0707 can you please check out the customer-data-framework (customer-management-framework) and create an issue there.
The [function](https://github.com/pimcore/customer-data-framework/blob/master/src/Resources/sql/segmentAssignment/storedFunctionObject.sql) you are looking for can be found in the customer management framework repo.

**Comment by fashxp** [comment]
see https://github.com/pimcore/demo/issues/142
