### ISSUE TITLE
[Feature request] Make it possible to assign a default "create" folder for relational object types. 

### ISSUE THREAD

**Issue by jacobsyentl** [pimcore/pimcore#5058]
# Feature Request
It would be nice if it was possible to assign a default create folder for relational object types in the class definition. That way it is easier to create relational objects from other objects.

## Current behavior example
1) Open a product
2) Go to a relational field (many-to-one or many-to-many) e.g. colours
3) Since the colour "orange" does not exist we Press the "plus" icon to create a new one.
4) Now Pimcore asks us a parent folder.

It would be nice if we could skip step 4 by having a default folder for this field. This way we just have to assign a key (non-duplicate of course).

##Additional idea
It would also be very interesting to have a small dialog that just shows the mandatory fields for the new object, since it is not possible to create the new object without filling these.

By any means, if this is not clear, i'm glad to provide some screenshots of the idea.

**Comment by weisswurstkanone** [comment]
can you create a PR for that ?

**Comment by ckemptner** [comment]
I have another idea, which is related: I suggest to define default folders in the Object Class definition for certain object classes (multi-relation with sorting - the first one will be the default for creating as described above). When a user now right-clicks on a folder or uses the functionality described above, 2 things will happen

a) The context-menu  "Add object" will only show the classes which have the default folder assigned. This will make the interface more comfortable to use (especially if there are many object classes).

b) Objects will by default be created in this default folder.

**Comment by dpfaffenbauer** [comment]
I like the idea of a default folder per Object Class. I already do that in CoreShop for entities like "Cart" or "Order" where they always are in a specific folder.

Would I would much rather love is what the CMF already does: Having sort of a configuration or even a service to automatically default objects to a folder. and also the auto-generation of the key.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
