### ISSUE TITLE
Pimcore completely broken after upgrade to 4.0.0 RC1

### ISSUE THREAD

**Issue by John5** [pimcore/pimcore#506]
After upgrading to Pimcore 4.0.0 RC1 the installation is completely broken. A white screen is displayed both on the frontend and the backend. (there is no admin interface)

In the error log there are two warnings and one fatal error because the class Zend_Loader_Autoloader cannot be found in startup.php on line 81.

I will investigate further and report my findings here, if other people are having the same issue, I suggest they leave a comment with this issue.

Update: It seems like after the upgrade the directory pimcore/lib/Zend/Loader no longer exists. All folders of the Zend Framework contain only directories, but no PHP files.

Update 2: I downloaded 4.0.0 RC1 pimcore-latest.zip from https://www.pimcore.org/en/resources/download and found that startup.php file there is completely different from mine, after the upgrade, additionally, the directory pimcore/lib does not include any external libraries like Zend.

Error log:
`[Wed Mar 09 09:46:08.013866 2016] [:error] [pid 24526] [client 192.168.1.58:64322] PHP Warning: include_once(/home/mypath/autoload.php): failed to open stream: No such file or directory in /home/mypath/pimcore/config/startup.php on line 71
[Wed Mar 09 09:46:08.014129 2016] [:error] [pid 24526] [client 192.168.1.58:64322] PHP Warning: include_once(): Failed opening '/home/mypath/vendor/autoload.php' for inclusion (include_path='/home/mypath/pimcore/lib:/home/mypath/pimcore/models:/home/mypath/website/lib:/home/mypath/website/models:/home/mypath/website/var/classes:') in /home/mypath/pimcore/config/startup.php on line 71
[Wed Mar 09 09:46:08.126191 2016] [:error] [pid 24526] [client 192.168.1.58:64322] PHP Fatal error: Class 'Zend_Loader_Autoloader' not found in /home/mypath/pimcore/config/startup.php on line 81 `

**Comment by cleggypdc** [comment]
Hi @John5, there are many changes with pimcore 4. You will find that the entire Zend library has been moved to /vendor, and is now included within composer as are many other dependant libraries.

You can read more about these changes here
https://www.pimcore.org/wiki/display/PIMCORE4/Update+from+Version+3.x+to+Version+4

Please could you post the build number you were upgrading from onto this thread?

**Comment by John5** [comment]
I am upgrading from  Pimcore Version: 3.1.1 (Build: 3543). I have now installed composer and used the following script: https://github.com/pimcore/pimcore/blob/master/composer.json

Composer installed many files in the vendor directory, but also has an error at the end.

`Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing filp/whoops (2.0.0)
    Downloading: 100%         

  - Installing pear/net_url2 (v2.2.0)
    Downloading: 100%         

  - Installing linfo/linfo (v3.0.0)
    Downloading: 100%         

  - Installing symfony/css-selector (v3.0.3)
    Downloading: 100%         

  - Installing tijsverkoyen/css-to-inline-styles (1.5.5)
    Downloading: 100%         

  - Installing zendframework/zendframework1 (1.12.17)
    Downloading: 100%         

  - Installing symfony/polyfill-mbstring (v1.1.0)
    Downloading: 100%         

  - Installing symfony/console (v3.0.3)
    Downloading: 100%         

  - Installing symfony/finder (v3.0.3)
    Downloading: 100%         

  - Installing symfony/process (v3.0.3)
    Downloading: 100%         

  - Installing symfony/var-dumper (v3.0.3)
    Downloading: 100%         

  - Installing symfony/event-dispatcher (v3.0.3)
    Downloading: 100%         

  - Installing hybridauth/hybridauth (v2.6.0)
    Downloading: 100%         

  - Installing google/apiclient (1.1.7)
    Downloading: 100%         

  - Installing oyejorge/less.php (v1.7.0.10)
    Downloading: 100%         

  - Installing maxmind/web-service-common (v0.0.4)
    Downloading: 100%         

  - Installing maxmind-db/reader (v1.1.0)
    Downloading: 100%         

  - Installing geoip2/geoip2 (v2.3.3)
    Downloading: 100%         

  - Installing psr/log (1.0.0)
    Downloading: 100%         

  - Installing monolog/monolog (1.18.0)
    Downloading: 100%         

  - Installing sabre/uri (1.1.0)
    Downloading: 100%         

  - Installing sabre/event (3.0.0)
    Downloading: 100%         

  - Installing sabre/http (4.2.1)
    Downloading: 100%         

  - Installing sabre/xml (1.4.0)
    Downloading: 100%         

  - Installing sabre/vobject (4.0.2)
    Downloading: 100%         

  - Installing sabre/dav (3.1.1)
    Downloading: 100%         

  - Installing ramsey/uuid (3.2.0)
    Downloading: 100%         

  - Installing colinmollenhour/credis (1.6)
    Downloading: 100%         

  - Installing endroid/qrcode (1.5.7)
    Downloading: 100%         

  - Installing amnuts/opcache-gui (v2.2.2)
    Downloading: 100%         

  - Installing vrana/adminer (v4.2.4)
    Downloading: 100%         

  - Installing sebastian/version (1.0.6)
    Downloading: 100%         

  - Installing sebastian/global-state (1.1.1)
    Downloading: 100%         

  - Installing sebastian/recursion-context (1.0.2)
    Downloading: 100%         

  - Installing sebastian/exporter (1.2.1)
    Downloading: 100%         

  - Installing sebastian/environment (1.3.5)
    Downloading: 100%         

  - Installing sebastian/diff (1.4.1)
    Downloading: 100%         

  - Installing sebastian/comparator (1.2.0)
    Downloading: 100%         

  - Installing symfony/yaml (v3.0.3)
    Downloading: 100%         

  - Installing doctrine/instantiator (1.0.5)
    Downloading: 100%         

  - Installing phpdocumentor/reflection-docblock (2.0.4)
    Downloading: 100%         

  - Installing phpspec/prophecy (v1.6.0)
    Downloading: 100%         

  - Installing phpunit/php-text-template (1.2.1)
    Downloading: 100%         

  - Installing phpunit/phpunit-mock-objects (2.3.8)
    Downloading: 100%         

  - Installing phpunit/php-timer (1.0.7)
    Downloading: 100%         

  - Installing phpunit/php-token-stream (1.4.8)
    Downloading: 100%         

  - Installing phpunit/php-file-iterator (1.4.1)
    Downloading: 100%         

  - Installing phpunit/php-code-coverage (2.2.4)
    Downloading: 100%         

  - Installing phpunit/phpunit (4.8.23)
    Downloading: 100%         

filp/whoops suggests installing whoops/soap (Formats errors as SOAP responses)
linfo/linfo suggests installing ext-com (On Windows)
symfony/var-dumper suggests installing ext-symfony_debug ()
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing videlalvaro/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
sabre/vobject suggests installing hoa/bench (If you would like to run the benchmark scripts)
ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
sebastian/global-state suggests installing ext-uopz (*)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating optimized autoload files
Method Pimcore\Composer::postInstall is not callable, can not call post-install-cmd script`

**Comment by brusch** [comment]
Seems to be a specific problem on your platform. 
Have you tried to install the demo on your system? If not, can you try it?

**Comment by John5** [comment]
I have started with a clean installation, and Pimcore 4.0.0 RC1 is working fine on the same server. However, the update process destroyed the database. Neither Pimcore versions will work with it anymore.

**Comment by brusch** [comment]
Hmm, we tested this already several times, without any problems, so it can't be a problem in general. Can you provide us a little bit more details? 

Is it maybe a permission issue? 
Was there a /vendor folder after the update? or the composer.* files? 
If so, ... which contents were in it? 
What is the diff between a fresh install and the upgraded /pimcore folder? 

Thanks!

**Comment by msenkpiel** [comment]
I have the same problems while updating to Pimcore 4.0.0 RC1 on two different systems. There is no /vendor folder.

**Comment by StephanWeinhold** [comment]
We had a similar issue on all of our instances. The problem was a broken MySQL-Query during the update (http://update.pimcore.org/v2/getUpdateFiles.php?for=3565).
Our solution: install composer. Then initiate the update in pimcore. Wait until it crashes. Download the nightly build (https://www.pimcore.org/download/pimcore-build.zip) via wget in your server-console. Unzip it and overwrite all pimcore-folders (and don't forget the new vendor-folder). Set chown and chmod correctly. Then log in into pimcore and start the update there again.

**Comment by brusch** [comment]
Hmm, that's very strange. 
Do you have any more information to the systems where pimcore is running on? 
- OS
- phpinfo()
- mysql version
... 

Additionally it would be very interesting if the same also happens if you update a fresh install of 3.1.1 to the latest build. And of course it would be really helpful if you could provide us a test-case where we can reproduce the problem (VM, Docker, ZIP, ...). 

Thanks in advance!

**Comment by brusch** [comment]
Any updates?

**Comment by StephanWeinhold** [comment]
I'm not quite sure who is asked :) Here everything is running fine now. Thanks!

**Comment by kardasz** [comment]
`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead' in /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228 Stack trace: #0 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array) #1 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array) #2 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array) #3 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('\nCREATE TABLE `...', Array) #4 [internal function]: Zend_Db_Adapter_Pdo_Abstract->query('\nCREATE TABLE `...') #5 /var/www/pimcore/lib/Pimcore/Db/Wrapper.php(267): call_user_func_array(Array, Array) #6 /var/www/pimcore/lib/Pimcore/Db/W in /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235`

There is always this error, no matter if I download zip: https://www.pimcore.org/download/pimcore-latest.zip or install via composer: php composer.phar create-project -s dev pimcore/pimcore ./pimcore dev-master

**PHP 5.6.17, MySQL 5.7.10, Nginx 1.6.2**

![zrzut ekranu 2016-03-23 o 16 25 34](https://cloud.githubusercontent.com/assets/1894170/13990640/5e1342d6-f115-11e5-8edd-7379237e2c40.png)
![zrzut ekranu 2016-03-23 o 16 34 15](https://cloud.githubusercontent.com/assets/1894170/13990641/5e13f32a-f115-11e5-9c2b-f35da89a4960.png)

**Comment by brusch** [comment]
Any other new findings?

**Comment by brusch** [comment]
Closed due inactivity.

**Comment by kovinet** [comment]
Hi. I have same problem on two different servers. When updating from 3.1.1. to 4.0.0..

> PHP Fatal error:  Uncaught Error: Class 'Zend_Loader_Autoloader' not found in

I get blank page for frontend and /admin
