### ISSUE TITLE
[Classification Store] Group/Object Relation

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#5067]
## Acceptance Criteria
If you're dealing with a lot of groups/keys in classification store, it should be possible to determinate all groups/objects relations.

### Group Collection
- Add an `Object Relation` action button to each Collection. This should open a modal window which contains a paged data grid with all linked objects

### Groups
- Add an `Object Relation` action button to each group (left side). This should open a modal window which contains a paged data grid with all linked objects.
- Add an `Group Relation` action button to each Key Relation (right side, see screenshot). This should open a modal window which contains a paged data grid with all linked groups.

### Key Definitions
- Add an `Group Relation` action button to each Key Definition. This should open a modal window which contains a paged data grid with all linked groups.

![image](https://user-images.githubusercontent.com/700119/66382033-bb797980-e9ba-11e9-9c5a-9704f4725014.png)

We could provide a PR for that.

**Comment by dpfahlbusch** [comment]
Is this still a thing? @solverat
