### ISSUE TITLE
[Classification Store] Drag & Drop on Key Relations

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#5068]
Allow changing `sorter` by drag and drop instead of manually changing the`sorter` field.

On Drop Event: Re-sort all key relations by automatically set `sorter` (`0`, `1`, `2`...)

![image](https://user-images.githubusercontent.com/700119/66383157-c9c89500-e9bc-11e9-831e-8064f98bbb2a.png)

We could provide a PR for that.

**Comment by AlternateIf** [comment]
@solverat is dragging/dropping possible in case of sorting by one field other than "Sorter"? (e.g. Key ID)

**Comment by weisswurstkanone** [comment]
I think we cannot do both. Would it be an option to disable dnd of column sorting is active?

**Comment by weisswurstkanone** [comment]
@solverat what is your opinion?
