### ISSUE TITLE
open_basedir restriction

### ISSUE THREAD

**Issue by chix** [pimcore/pimcore#507]
Hi,

I just want to point out a small issue and apologize for not following the issue template :).

On a client server with enabled open_basedir restriction pimcore (build 3623) produces warnings like this https://www.pimcore.org/board/viewtopic.php?f=19&t=418. I can solve it by overriding the include_path, but in the topic @brusch mentions that pimcore already takes care of this. Is that still the case? According to this comment https://github.com/pimcore/pimcore/blob/master/pimcore/config/startup.php#L103 it should be, but in the code, the include_path from php.ini is still inherited.

Regards,
Martin

**Comment by brusch** [comment]
fixed in build 3695
