### ISSUE TITLE
[ClassificationStore] group page is not correct

### ISSUE THREAD

**Issue by AlternateIf** [pimcore/pimcore#5071]
If you have more than 25 groups in case of 25 items per page in the classification store group interface the page count is not displayed correctly. it is showing "Page 1 / 1" although there is more than one page.

The next page button is working though. If you click it the max page value is updated. The Max Item Count (e.g. 1 - 25 / 28) is also correct

tested on the new demo

**Comment by weisswurstkanone** [comment]
Are you referring to the group definition (settings | dataobjects | classification store) UI or the group selection inside the object editor?

**Comment by AlternateIf** [comment]
this is referred to the group definition UI
![image](https://user-images.githubusercontent.com/14984260/66486968-daa40400-eaab-11e9-9482-ea95c2bb845b.png)

There should be shown 2 pages here since there are 28 items
