### ISSUE TITLE
[ClassificationStore] - adding groups with the same name

### ISSUE THREAD

**Issue by AlternateIf** [pimcore/pimcore#5072]
Currently it is not possible to add multiple classification store groups with the same name.
The create-group request returns true although the group is never added

It should either be possible to add a group with the same name (the group is identified by id anyway - similar to classification store keys where adding multiple keys with the same name is possible)
Or there should be displayed an error message upon trying to add a new group with a name that already exists
tested on the new pimcore demo

**Comment by weisswurstkanone** [comment]
Since the name is currently the unique identifier I would suggest to go for the second option
