### ISSUE TITLE
Grid view doesn't filter by an item from the classification store

### ISSUE THREAD

**Issue by davi-mo** [pimcore/pimcore#5078]
# Bug Report

### Expected behavior
It should be possible to filter by items from the classification store.

### Actual behavior
An exception is thrown when I am trying to filter by the item.
<img width="698" alt="Screenshot 2019-10-09 at 12 25 18" src="https://user-images.githubusercontent.com/20536831/66552402-8c454280-eb49-11e9-92ab-db56daa39d56.png">

### Steps to reproduce

1. Go to Data Objects
2. Navigate to a folder that contains items in the grid view
3. Click on grid options.
4. Select an item from the classification store
5. Click on apply
6. Click on the column that contains the item from the classification store
7. Select filters and choose an item
8. See the popup with the exception
 
I could provide a PR for this issue.

**Comment by davi-mo** [comment]
@weisswurstkanone PR is opened

**Comment by davi-mo** [comment]
<img width="1073" alt="Screenshot 2019-10-10 at 11 15 13" src="https://user-images.githubusercontent.com/20536831/66555719-69b62800-eb4f-11e9-902b-5ba3dee38a4f.png">

**Comment by weisswurstkanone** [comment]
IMHO the right place for that would be Pimcore\Model\DataObject\ClassDefinition\Data\Multiselect::getFilterConditionExt

**Comment by davi-mo** [comment]
Hi @weisswurstkanone, why do you think that would be the right place? The problem is for this specific case, the method Pimcore\Model\DataObject\ClassDefinition\Data\Multiselect::getFilterConditionExt is not been called.

**Comment by weisswurstkanone** [comment]
I my case it was called.
I created a CS key of type multiselect.
Then added the key to the grid and enabled filtering.

**Comment by davi-mo** [comment]
Hi @weisswurstkanone, I discovered why is not been called. That's because I am using a type select and not multi-select. And in the select class, we don't have a method called getFilterConditionExt.
<img width="1019" alt="Screenshot 2019-10-10 at 14 57 28" src="https://user-images.githubusercontent.com/20536831/66570767-89a91400-eb6e-11e9-97b4-233f50bb4085.png">

**Comment by weisswurstkanone** [comment]
Great :-) My assumption was that we are talking about a multiselect field.
So my suggestion would be to implement it for the datatype instead of relying on the fallback.

**Comment by davi-mo** [comment]
@weisswurstkanone Great. Done.
