### ISSUE TITLE
Inconsistent language about config file types in source

### ISSUE THREAD

**Issue by John5** [pimcore/pimcore#508]
`I` am trying to figure out how extending an object works and have found some inconsistencies in the method getModelClassMappingConfig() in pimcore/lib/pimcore/Config.php. A file classmap.php is loaded, the documentation mentions XML and the exception refers to it as JSON file.

Since the configuration files are now PHP files that return an array I assume that is the correct one?

    /**
     * @static
     * @return \Zend_Config_Xml
     */
    public static function getModelClassMappingConfig()
    {
        $config = null;

        if (\Zend_Registry::isRegistered("pimcore_config_model_classmapping")) {
            $config = \Zend_Registry::get("pimcore_config_model_classmapping");
        } else {
            $mappingFile = \Pimcore\Config::locateConfigFile("classmap.php");

            if (is_file($mappingFile)) {
                $config = include($mappingFile);

                if (is_array($config)) {
                    self::setModelClassMappingConfig($config);
                } else {
                    \Logger::error("classmap.json exists but it is not a valid JSON configuration. Maybe there is a syntax error in the JSON.");
                }
            }
        }
        return $config;
    }

**Comment by brusch** [comment]
Thanks! 
Docs are already up to date (PHP files): 
https://www.pimcore.org/wiki/display/PIMCORE4/Class-Mappings+-+Overwrite+pimcore+models 

Maybe you have used the version 3 docs :)
