### ISSUE TITLE
Localized fields in object bricks with inheritance results in error

### ISSUE THREAD

**Issue by deltatag** [pimcore/pimcore#5083]
## Expected behaviour

Getting a localized field value for an object brick within an object that inherits from a parent object should give the localized value.

## Actual behaviour

Getting a localized field from an object brick within an inherited object fails.

## Steps to reproduce

1. Child object inherit values form parent object of same object type.
2. Parent object has object brick with localized field.
3. Filling the localized field in parent object and saving is successful.
4. Getting localized value from child object results in error.
``` php
$childObject->getBricks()->get('ObjectBrick')->getMyLocalizedField()
```

The error was pinned down to this line of code: https://github.com/pimcore/pimcore/blob/c83c83fe6b0d0521414e373189852a343341a8bc/models/DataObject/Localizedfield.php#L423
The context array is missing the value for key 'fieldname' and then could not build the getter method name.

**Comment by weisswurstkanone** [comment]
Unable to reproduce

**Comment by deltatag** [comment]
Saving of the object containing the brick solved the error.
