### ISSUE TITLE
Add custom postfix to full page cache key

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#5086]
# Feature Suggestion
Pimcore's fullpage cache is very helpful, but it is very difficult to leverage the fullpage cache in a user-specific context. 

**Example:**
A Website contains generic context, which are the same for all users. However, in the header of the Website, for logged in users, the username is shown.

**Idea:**
Our idea was to cache only the non-generic version of the page (will be the case 90% of the time), and disable the cache as soon as a user is logged in. There are several events in ``FullPageCacheListener.php`` but none of them is suitable, as the decision, whether to use the cached version or not, depends on the cache key, and is already taken in the ``onKernelRequest`` method.

**Solution Suggestion:**
I suggest to add an event that 

1. allows the appliation to change the determined ``$cacheKey``. In our case we could leverage that event to add an ``_is_guest_yes_no``, or a ``_user_123`` postfix to support fullpage cache for guests and logged in users. We would then leverage the ``FullPageCacheEvents::IGNORED_SESSION_KEYS`` event to disable the fullpage cache for logged in users.

2. allows cache disabling already in the  ``onKernelRequest`` method. I don't know if this is sufficient, as the browser cache might be active as well?

Let's discuss this issue, so that we can provide a PR.

**Comment by brusch** [comment]
This is already possible by filling `$_REQUEST['pimcore_cache_tag_suffix']` (needs to be an array). 

Example: 
```php
$_REQUEST['pimcore_cache_tag_suffix'] = ['foo']; 
```

Of course it would be nicer to have a method on the service in the future, but this method exists already since ages ;)

**Comment by andreas-gruenwald** [comment]
Ok, wasn't aware of that. I'll give it a try. Thx!

**Comment by andreas-gruenwald** [comment]
I tried modifying the REQUEST parameter as suggested and actually it worked.
