### ISSUE TITLE
Pimcore 4. Date from date fields not correctly set in backend or displayed in FrontEnd  

### ISSUE THREAD

**Issue by dctmc** [pimcore/pimcore#510]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [X ] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [ ]X Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [ X] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [ X] There's no existing ticket for the same issue

### Expected behavior 
Set Date in date field in any Object (for example News) in backend. After Object (News) is displayed you should see same date which are set in backend.

### Actual behavior  
Displayed in frontend date is 1 day less (for example if you set 14/03/2016 you get 13/03/2016)   

### Steps to reproduce  
Just add News and set date to it in backend and load it in frontend
  
### Code example 
```php
// your code
```

# Feature Request 
## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [ X] There is no existing issue regarding the same topic

**Comment by atietje** [comment]
Tried it reproduce it, but couldn't. Seems to work properly, see http://recordit.co/zLKXk66Qeu

**Comment by dctmc** [comment]
Problem is when you are set time of publishing of news - if you are set in from 00:00 till 2:00 you will get 1 day less in date...

**Comment by weisswurstkanone** [comment]
Also tried it with 00:00, unable to reproduce.

**Comment by ThomasKeil** [comment]
@dctmc Where are you located?

**Comment by dctmc** [comment]
in Moscow, Russia.. server is in Germany.. may be thats why 2 hours difference... between local time on computer and server time settings

**Comment by ThomasKeil** [comment]
That's the most probable reason, the two hours difference point to that.

For further considerations you should take in account that you don't have daylight saving time anymore.
It's not unlikely that JavaScript probably know that, but php does since it uses a very up-to-date timezone database (see https://en.wikipedia.org/wiki/Tz_database). This can result in at least one hour difference.

**Comment by weisswurstkanone** [comment]
Changed my local timezone to RTZ 2. Seems that the time is stored correctly in the database. However, be aware that the time you see in the preview&frontend is the formatted in the server's timezone (unfortunately without giving you a hint about the actual timezone which is CET in the demo case).

**Comment by dctmc** [comment]
thank's to everybody, seems this is because of server's formatted timezone used for display date in frontend... I will take it in account.
