### ISSUE TITLE
Not working field with properties "not editable" and "show counter"

### ISSUE THREAD

**Issue by jacdobro** [pimcore/pimcore#5100]
# Bug Report
### Expected behavior
Show not editable field (input or textarea) with characters counter
### Actual behavior
Pimcore admin panel stops working
throw js error:
`TypeError: this.component.setReadOnly is not a function`

### Steps to reproduce
Create a class with field input and checked properties "not editable" and "show character counter"
Create an object of the created class
Open created object

**Comment by weisswurstkanone** [comment]
fixed via https://github.com/pimcore/pimcore/pull/5102
