### ISSUE TITLE
Object Preview doesn't work with lazy loaded relations

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#5106]
I debugged the issue, the problem are lazy loaded fields, since they don't get serialized without _fulldump. Also, when you add _fulldump for the session serialization, it get's removed later, cause \Pimcore\Tool\Session opens and closes the session like a million times per request... which unserializes it, removes the _fulldump and serializes it again.

**Comment by dpfaffenbauer** [comment]
Solutions might be:

1. Change how Pimcore manages the Session by not opening or closing it like a million times.
2. Serialize the Session Object into the TmpStore with an identifier saved into the session. So the Object doesn't get unserialized and serialized like a million times.
3. Remove the `unset($this->_fulldump)` on ``__wakeup`` in `AbstractObject`, but that for sure has sideeffects for Versions.
4. Introduce proper serialization und unserialization for Pimcore DataObjects.

The quick fix would be Solution 2.

**Comment by brusch** [comment]
@dpfaffenbauer I've done some optimizations on the admin sessions, would be nice if you could review them, see #5145

**Comment by dpfaffenbauer** [comment]
Just tested, doesn't work for me....

**Comment by brusch** [comment]
I'd go for option 2 as well. The session storage is anyway not really the best place for temporary storing objects as it potentially has limited space as well (memcache, ...)

**Comment by brusch** [comment]
We should also use the `TmpStore` for the document preview.
