### ISSUE TITLE
[Bug/Doc] JS Event postSaveObject send old object datas

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#5116]
Hello,

Using the postSaveObject event in Pimcore BO, the old datas are in the object:

```
    postSaveObject: function (object) {
        console.log(object);
    }
```

`object.data.data` and `object.data.general` are the one before the save action.
Is it a bug ? Do we have to trigger an JS ajax request to have manually those datas ?
If no this should be mentionned in the documentation, as well a sample code to get the new datas.
If yes and new data should be received, so how to get old datas ?

I think for the best possibility, it would be great to have old and new datas, so we can make some comparaison to make some actions based on this.

Thanks.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
