### ISSUE TITLE
[Data Object] Full support for advanced many-to-many data-types in grid view

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#5118]
Data-Types: 
- advanced many to many object relations
- advanced many to many relations 

Features: 
- display meta-data in grid
- possibility to edit data (popup)

**Comment by weisswurstkanone** [comment]
![image](https://user-images.githubusercontent.com/6142086/67688067-8cdb3700-f999-11e9-9042-3e41ab02875c.png)
