### ISSUE TITLE
[DataObject][ClassificationStore] API improvements

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#5129]
Improve Classification Store API
- add option for getItems() to get all items (inkl. inherited data)
- add option for getActiveGroups() to get all active groups (inkl. inherited data)
- add method to get all keys of a group
- add method to get all groups of a collection

nice-to-have
- add method to get all groups/keys in correct order

**Comment by weisswurstkanone** [comment]
resolved via https://github.com/pimcore/pimcore/pull/7174
