### ISSUE TITLE
[Documents] Clearer error message when renaming unpublished document

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#5130]
When renaming a document which has an unpublished version, following error message is displayed
![image](https://user-images.githubusercontent.com/13643455/67376516-8eb18e80-f584-11e9-9282-dc56c15a057e.png)

It would be great to show the user a clear error message - for example "You cannot rename a document with an unpublished version. Please publish your document first."

**Comment by weisswurstkanone** [comment]
Unable to reproduce

**Comment by ckemptner** [comment]
Just reproduced in latest demo
![2019-10-23_11-16-56](https://user-images.githubusercontent.com/13643455/67377913-adb12000-f586-11e9-81ef-77fe8e20ac9d.gif)
