### ISSUE TITLE
Add Documentation for Pimcore AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#5153]
# Feature Request

Within the newest Pimcore documentation there is information on how to use Pimcore in a multi-environment setup and there is also a specific chapter for usage with AWS S3 (https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Amazon_AWS_Setup/Amazon_AWS_S3_Setup.html). 

However scalable applications should be deployed with Elastic Beanstalk - otherwise the real benefits of the Amazon infrastructure can not be used. Problem is, there is not any guidance within the docs on how to set this up. The .gitignore file within the current version is not helpful for this setup. 

There should be a proper guide or tutorial for Pimcore usage with Elastic Beanstalk within the documentation. **The most important thing with this setup is that Amazon can spawn an shutdown server instances depending on the current load. Therefore we have to know which folders have to be shared, which folders can be duplicated and which Pimcore console instructions we have to integrate into a deployment script.** 

There is no adequate guidance or tutorial on how to use Pimcore with AWS Elastic Beanstalk (or a similar setup infrastructure).

**Comment by davidhoeck** [comment]
Hi @Blackbam - this should give you an idea of which folder and files must be shared.

https://github.com/w-vision/pimcore-deployer/blob/master/deploy.sample.php

**Comment by Blackbam** [comment]
@davidhoeck Thank you this is a helpful start.

**Comment by brusch** [comment]
@Blackbam Got it to work? Are you willing to contribute a guide for our docs?

**Comment by Blackbam** [comment]
@brusch We are not running the projects with Elastic Beanstalk at the moment because things became to complicated. But it is planned for the future - as soon as we switch to Elastic Beanstalk and it works we can provide a guide for the docs.

**Comment by davidhoeck** [comment]
@brusch we have applications in production which are running on AWS ECS (elastic container service), AWS S3 and AWS RDS, with Load Balancers and so on. Would that be interesting for the docs?

**Comment by brusch** [comment]
@davidhoeck absolutely!
I'd say a good start would be a PR, we can then discuss the details in the community. Would that be ok for you?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
