### ISSUE TITLE
[FeatureRequest] LocalizedFields add option to remove (or limit to) certain languages

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#5154]
Right now a localized field always contains all available system languages.

Some fields however only exist in certain languages. Would be nice if we could decide what languages we want to display.

**Comment by roland4432** [comment]
If you don't login as admin you can go with the permission views to achieve that:

/bundles/AdminBundle/Resources/public/js/pimcore/object/tags/localizedfields.js
```
...
//line: 44
        if (pimcore.currentuser.admin || fieldConfig.permissionView === undefined) {
            this.frontendLanguages = pimcore.settings.websiteLanguages;
        } else {
            this.frontendLanguages = fieldConfig.permissionView;
        }
....
```

Or do you rather think as a global option to select which languages are included? Or on specific localizedfields? Or configure each localizedfield in the class section?

**Comment by weisswurstkanone** [comment]
@roland4432 he is talking about a specific localizedfield. so on field - level.

**Comment by roland4432** [comment]
Since you might have the use cases @weisswurstkanone ... is this generic all day requirement?

**Comment by ultramegatom** [comment]
Use case would be:
I have 20 languages in my system with multiple localized fields that use these languages.
I do however also have other fields that simply can only exist in 2 specific languages.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
