### ISSUE TITLE
List of RequiresDependencies not updated onPostUpdate event during Save Only

### ISSUE THREAD

**Issue by zeor59** [pimcore/pimcore#5158]
### Expected behavior
Add an image on a field of my object, click on the button "SaveOnly" and get my Asset Id in the list of Requires Dependencies of my object  (into onPostUpdate event)

### Actual behavior
During a "saveOnly", my Asset Id is not in the list of require dependencies of my current object  (into onPostUpdate event) whereas that's working during a "Save & Publish"

### Steps to reproduce
- Upload an image on my object
- click on the button "Save Only" or "Only Save new version"
- Create a Log file during the postUpdate event of the following array: `$object->getDependencies()->getRequires();`

The id of the asset previously added should be in the list as is the case when I click on the "Save and publish" button

Thanks in advance for your support

Regards,

Benjamin

**Comment by fashxp** [comment]
dependencies are only considering published version of object.
