### ISSUE TITLE
Installing RC1 with Sample Data

### ISSUE THREAD

**Issue by gsomoza** [pimcore/pimcore#516]
- [x] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [x] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [x] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [x] There's no existing ticket for the same issue (that I could find)

### Expected behavior 
Installation of sample data works.

### Actual behavior  
A fatal error is thrown:

```
Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead in /Users/gabrielsomoza/work/personal/php/pimcore-4/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

Zend_Db_Statement_Exception: SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead, query was: CREATE TABLE `documents_translations` ( `id` int(11) unsigned NOT NULL DEFAULT '0', `sourceId` int(11) unsigned NOT NULL DEFAULT '0', `language` varchar(10) DEFAULT NULL, PRIMARY KEY (`sourceId`,`language`), KEY `id` (`id`), KEY `sourceId` (`sourceId`), KEY `language` (`language`) ) DEFAULT CHARSET=utf8 in /Users/gabrielsomoza/work/personal/php/pimcore-4/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235
```
### Environment
Max OSX 10.11.3 (El Capitan)
Brew PHP 7.0
Apache 2.4.16
MySQL 5.7
All required php extensions installed

### Steps to reproduce  

1. Get Quick Start Bundle
2. Follow the [Quick Installation Guide](https://www.pimcore.org/wiki/display/PIMCORE4/Installation+and+Upgrade)
3. Go to webpage, get redirected to the installation tool.
4. Fill-in database information (DB exists and is empty). Using PDO_MySQL driver.

**Comment by brusch** [comment]
Thanks!

https://github.com/pimcore/pimcore/commit/82409854f11901cb253799dab7dd57b2d0e47a6b
build is in progress

**Comment by brusch** [comment]
Build is finished. Can you try it again with the latest build (demo package)? 
Thanks for your feedback.
