### ISSUE TITLE
defer creating video thumbnail

### ISSUE THREAD

**Issue by datom** [pimcore/pimcore#518]
Method:
\Pimcore\Model\Asset\Video::getImageThumbnail()

Should work like the getThumbnail method from the Image class

**Comment by deltatag** [comment]
The method should also support generating thumbnails for other video types then assets like YouTube, Vimeo and Dailymotion videos. These types are already supported by the video type in Pimcore. But it's not possible to generate thumbnails for them directly via the video data object or the video tag.

**Comment by brusch** [comment]
Similar to #3974 just for videos. 
Do the processing in the background and display a placeholder in the meantime.
