### ISSUE TITLE
Many to one Relation - invalid database data

### ISSUE THREAD

**Issue by ckogler-elements** [pimcore/pimcore#5189]
Relations are not properly "cleaned". 
Eg. you have a customer object with a many to one relation (mainAddress) to a address.
If you delete an assigned address the  mainAddress__id of the customer table - e.g. "object_customer".mainAddress__id won't be resettet. The now invalid id of the address stays in the database.

**Comment by weisswurstkanone** [comment]
Unable to reproduce.

Procedure:
- delete target
- check sanitycheck table, entry for source object is there (resolved via dependencies table)
- run maintenance script
- relation is gone

**Comment by ckogler-elements** [comment]
Hmmm.... seems to be a Pimcore 5.8.6 issue. In Picmore 6 it works as described. 
In Pimcore 5.8.6 the item is added to the sanitycheck table. 

After executing php ~/www/bin/console pimcore:maintenance --job="runSanityCheck" -vvv the id is removed from the sanitycheck table, but not in the objcte_xxx table.

**Comment by weisswurstkanone** [comment]
Can this be reproduced (i.e. same behavior the second time) on your side ?

**Comment by brusch** [comment]
@ckogler-elements ping 😊

**Comment by ckogler-elements** [comment]
currently not repoduceable anymore
