### ISSUE TITLE
Schedule: Invisible text in field [ExtJS]

### ISSUE THREAD

**Issue by luklewluk** [pimcore/pimcore#521]
Hi. I just found an issue when I was about to set schedule for my document. When I set "action" and then clicked on another field, the text in "action" field become invisible.
![image](https://cloud.githubusercontent.com/assets/6748300/14040958/cf97c672-f26c-11e5-8c5e-f010ef37cc65.png)

If I want to change the field the text is visible again:
![image](https://cloud.githubusercontent.com/assets/6748300/14040965/e77fc654-f26c-11e5-8fe7-b3039ea20d53.png)

The problem does not appear if you use English language in Pimcore.

**Comment by weisswurstkanone** [comment]
fixed in build 3710.
note that everything should still be scheduled correctly. there was just a problem in the combobox renderer.

**Comment by luklewluk** [comment]
Thank you very much!
