### ISSUE TITLE
Decimal precision for Quantity Value data type

### ISSUE THREAD

**Issue by mmcbride1968** [pimcore/pimcore#522]
## Feature description

In the data type, Number, there's the ability to define the Decimal precision of the field. The same feature needs to be added to Quantity Value data type as well.

**Comment by Yivan** [comment]
Hello mmcbride1968, i just made a pull request for your issue: https://github.com/pimcore/pimcore/pull/845
Regards.

**Comment by BlackbitNeueMedien** [comment]
As some of our clients have requests this exact feature, it would be nice to see Yivan's changes merged into Pimcore soon.

**Comment by fashxp** [comment]
already implemented
