### ISSUE TITLE
Demo-Advanced Certificate incorrect domain

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#5223]
### Expected behavior

A secure uninterrupted connection to https://demo-advanced.pimcore.org/

### Actual behavior

SSL_ERROR_BAD_CERT_DOMAIN Certificate is only valid for ` *.elements.at, elements.at`

**Comment by brusch** [comment]
https://demo-advanced.pimcore.org/ was turned off some weeks ago, please use our new public demo instead: https://demo-advanced.pimcore.org/

**Comment by brusch** [comment]
DNS records deleted.

**Comment by NiklasBr** [comment]
@brusch Please update links from the Academy *before* deleting the DNS records... Now they don't work at all.

Also https://www.w3.org/Provider/Style/URI

**Comment by brusch** [comment]
@NiklasBr Thanks, done!
