### ISSUE TITLE
[Documents] Publish/Unpublish multiple documents in tree

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#5225]
Currently only "Delete" is possible.

![image](https://user-images.githubusercontent.com/13643455/68486942-77d89080-0242-11ea-87c1-bb05d5679911.png)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
