### ISSUE TITLE
Backward Compatibility FAQ + tagging of code for internal use only

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#5232]
Similar to https://symfony.com/doc/current/contributing/code/bc.html 

Describe which code is safe to use within a major branch, e.g.: 
All code in `/models/` is safe to use except methods/classes/... tagged as `@internal` 
... 
...

**Comment by NiklasBr** [comment]
> Similar to https://symfony.com/doc/current/contributing/code/bc.html

The most important part:

> we promise you backward compatibility (BC) for all minor Symfony releases.

**Comment by NiklasBr** [comment]
Relevant: #4647 concerns trust more than it is about (developer) convenience.

**Comment by brusch** [comment]
Related to #7189
