### ISSUE TITLE
Unable to restore deleted objects-folder recursively from recycle bin

### ISSUE THREAD

**Issue by thgross** [pimcore/pimcore#5235]
If you delete a folder in data objects and try to restore it, only the empty folder is restored. the objects are gone.

This has been fixed for asset-folders (see #5022), but unfortunately, the issue still exists for object-folders.

### Expected behavior
restoring a deleted objects-folder from recycle-bin should restore all objects inside the folder, too.

### Actual behavior
restoring a deleted objects-folder only restores the folder, but not the objects.

### Steps to reproduce

1. visit https://demo.pimcore.fun/admin/
2. delete the folder Data Objects/News
3. restore the folder News

Please fix this as soon as possible. One of our clients already lost data because of this.

**Comment by blankse** [comment]
@thgross I create a PR. We had the same problem today...
Can you test it?
