### ISSUE TITLE
allow dynamic pimcoreNavigation manipulation

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#524]
I'm currently developing a plugin which dynamically needs to enable or disable some menu elements because of user role restrictions. 

**my first approach** was to extend the `Pimcore\Model\Document\Page` with the *classmap* functionality. with that custom class i'll override the `getProperty()` method and return the "navigation_exclude" property with true or false - depending on the restriction. 
the problem: this will work only for the first call, before the whole navigation tree gets cached by pimcore. 

**my second approach, which needs some improvements from your side:**
In `Pimcore\View\Helper\PimcoreNavigationController` the navigation will be loaded with 
`$navigation = CacheManager::load($cacheKey);` (line 70)
after that, pimcore is looking for the active page(s). it would be great if we could fetch the navigation after the cache load.

for an example we could add this after line 85:

```
$navHook = \Pimcore::getEventManager()->trigger("navigation.postBuild", $navigation);

if ($navHook->stopped()) {
   $navigation = $result->last();
}
``` 
what do you think? do i miss something? but i think it's not possible to manipulate the navigation dynamically in a different way with the currently given environment.

**Comment by brusch** [comment]
You can use the callback function to add your own pages: 

```php
<?php
    $this->pimcoreNavigation($this->document, $startNide, null, function ($page, $document) {
		if($page->getId() == 123) {
		    $page->addPage(...); 
		}
    });
?>
´´´

**Comment by brusch** [comment]
Of course you can use the same to manipulate your navigation: 

```php
<?php
    $this->pimcoreNavigation($this->document, $startNode, null, function ($page, $document) {
		// this callback is called for every single page in your navigation
		// do a check for whatever you need
		if($document->getProperty("myCustomProperty") == "whatever") {
			// manipulate your navigation page
			$page->setActive(false); 
			// ...
			$page->setVisible(false); 
			// ...
			//$page->set....(...); 
		}
    });
?>
```

More information on that, see: 
https://www.pimcore.org/wiki/display/PIMCORE4/Navigation#Navigation-Cacheable/High-PerformanceNavigation(since3.0.6)

If you do manipulate your navigation it might by necessary to take care of the build in navigation cache, although it shouldn't be necessary.

**Comment by solverat** [comment]
ok, that's a working solution (and yes, it's working without taking care about the nav cache). but i was hoping we could access the navigation tree via a plugin. with your solution i need to tell my _website constructors_ to implement a callback in each of their navigations. in my opinion it would by nice to have a navigation filter in a earlier state.

**Comment by solverat** [comment]
ok, after some tests i can confirm that **it is not** possible to inject dynamic elements into the pimcore navigation. 

i was hoping to manipulate the cachekey in the `getNavigation()` method from the `PimcoreNavigationController.php` Class: 
```php
if ($pageCallback instanceof \Closure) {
      $cacheKeys[] = "pageCallback_" . closureHash($pageCallback);
}
```
But that's also not possible because in my case the callback function stays always the same.

So what we're gonna do? Disable the complete navigation cache to inject some dynamic elements can't be a solution. Imagine a huge navigation with dozens of subnavs and one single dynamic element.

**Comment by brusch** [comment]
You can pass an individual cache key using the last parameter of ->pimcoreNavigation(), see: 
https://github.com/pimcore/pimcore/blob/3b3643260ef9a5bc5c803ce25bda95a3307cf340/pimcore/lib/Pimcore/View/Helper/PimcoreNavigation.php#L49-L49 

Example: 
```php
$this->pimcoreNavigation($this->document, $mainNavStartNode, null, null, "yourindividualkey");
```

see also: 
https://www.pimcore.org/wiki/display/PIMCORE4/Navigation#Navigation-Dynamickeyforthenavigationcache

**Comment by solverat** [comment]
dammit, i totally missed that. That should work, thanks for the hint!

**Comment by langert** [comment]
$this->pimcoreNavigation() is not available in pimcore x. How can I extend the navigation with a custom page in pimcore x? Thanx for any hints
