### ISSUE TITLE
Error on copy & paste a folder in "Data Objects"

### ISSUE THREAD

**Issue by thgross** [pimcore/pimcore#5251]
# Bug Report

pimcore throws an error every time one tries to duplicate an objects-folder.

### Expected behavior

the folder is duplicated, including objects

### Actual behavior

The folder is not duplicated. Instead, pimcore displays an error:
**Call to undefined method getClass in class Pimcore\Model\DataObject\Folder
Server threw exception - could not perform action. Please reload the admin interface and try again.**

    Status: 500 |
    URL: /admin/object/copy
    Method: POST
    Message: Call to undefined method getClass in class Pimcore\Model\DataObject\Folder

### Steps to reproduce
1. go to https://demo.pimcore.fun/admin
2. in "Data Objects", right-click on "News" and select "Copy"
3. right-click on "Home" and select "Paste" > "Paste as Child (recursive)"

**Comment by brusch** [comment]
Regression of #5243
