### ISSUE TITLE
[Recycle Bin] Restoring an objects-folder from recycle bin restores objects to "Home"

### ISSUE THREAD

**Issue by thgross** [pimcore/pimcore#5252]
# Bug Report

### Expected behavior

The folder should be restored. The objects should be restored into that folder.

### Actual behavior

The folder ist beeing restored. However, the objects contained are restored to the "Home"-folder.

### Steps to reproduce
1. visit https://demo.pimcore.fun/admin
2. In "Data Objects", right-click on "News" ans select "Delete", then "OK"
3. In "Tools" > "Recycle Bin", right-click on "/News" and select "Restore".

**Comment by brusch** [comment]
Regression of #5237

**Comment by brusch** [comment]
Related to #4261
