### ISSUE TITLE
[IndexService][ElasticSearch] - Duplicate entries (same _id) in elastic search

### ISSUE THREAD

**Issue by AlternateIf** [pimcore/pimcore#5259]
Whenever a product gets indexed and the product type changes its index-type  (e.g. from object to variant) given by getOsIndexType through dynamic context (e.g. it's a object if an specific attribute is given and a variant if this specific attribute is not given) the product will be inserted twice 

This happens whenever the product is indexed with one type and id and gets indexed again with a different type and the same id.

setting the following line to `$routingId = $indexSystemData['o_id'];` resolves the issue for me
https://github.com/pimcore/pimcore/blob/63bf29b8aa5bfe32dff1d86d6b56148c6e3b3e92/bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php#L431

**Comment by AlternateIf** [comment]
@fashxp

**Comment by AlternateIf** [comment]
consider that the entry might be in different shards in case of different _routing. this may cause problems search for parent/child entries if they are in different shards due to a different _routing

**Comment by fashxp** [comment]
possible solution: 
- store `previous routing` for each element to store table
- when routing changes, add `delete` to bulk update before new index row of element.

**Comment by fashxp** [comment]
resources: 
- https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-routing-field.html#_unique_ids_with_custom_routing
- https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html

**Comment by fashxp** [comment]
query for checking for duplicate entries: 
```
GET /pimcore-demo/_search
{
  "size": 0, 
  "query": {
    "match_all": {}
  },
  "aggs": {
    "system.o_id": {
      "terms": {
        "field": "system.o_id",
        "size": 10000,
        "min_doc_count": 2
      }
    }
  }
}
```

**Comment by fashxp** [comment]
temporary solution: 
limit ES index to one shard
