### ISSUE TITLE
[ClassificationStore] Validation error when changing values in inherited object

### ISSUE THREAD

**Issue by kjkooistra-youwe** [pimcore/pimcore#5264]
Steps to reproduce:

- Create a classification store with (at least) 2 **mandatory** keys
- Create a classification store group and add the keys to it
- Create a class and enable 'Allow inheritance'
- Add a panel and classification store field
- Create a new object, add the classification store group, fill the fields and save and publish
- Create a new object nested nested within the previous object
- Add the classification store group, change 1 of the fields and save and publish

This will cause a validation error on the field which was not changed. This applies to all mandatory fields loaded in the classification store field on the nested object, which is quite a nasty problem when you try to override one value but there are a dozen mandatory fields.

![Inherited_object_classification_store_field_validation_error](https://user-images.githubusercontent.com/24292941/68934058-4574e900-0796-11ea-8328-7a931581dce6.png)

**Comment by kjkooistra-youwe** [comment]
Inheritance is handled in the Concrete::update() method, but since the classification store is no regular field it seems inheritance will have to be implemented separately within its validation logic. Unfortunately this seems to be quite complex, since the individual key value of the parent object will need to be checked if validation fails and inheritance is enabled. In addition to that, inheritance is not limited to 1 level, so it also involves recursion.

**Comment by weisswurstkanone** [comment]
please review my changes

**Comment by kjkooistra-youwe** [comment]
@weisswurstkanone Very nice. I copied the changes to my local project and the validation is working correctly now. Less complex than I assumed fortunately.

**Comment by weisswurstkanone** [comment]
thanks for testing!

**Comment by kjkooistra-youwe** [comment]
Thanks for fixing! :)
