### ISSUE TITLE
[DataObject] Many to Many Object Relations - "Enable Async Load in Admin" not working for some column types

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#5265]
# Bug Report
1. Add (Advanced) Many-To-Many Object Relations
2. Select "Allowed Classes" & In "Visible Fields" select different field types like Relations, Image, Geo Types.
3. Add object data and reload.
![image](https://user-images.githubusercontent.com/5137917/68936604-347aa680-079b-11ea-8b2d-63fcf5e26a77.png)

**Comment by weisswurstkanone** [comment]
seems that record.data.inheritedFields is not set anymore.
see manyToManyObjectRelations.js line 69
