### ISSUE TITLE
[ASSETS] Adding a new PDF (or .docx) asset fails to create an image thumbnail in 6.3.0 & 6.3.1

### ISSUE THREAD

**Issue by talanko** [pimcore/pimcore#5266]
# Bug Report
Adding a new PDF (or .docx) as an asset in pimcore 6.3.0 & 6.3.1 fails to create an image thumbnail.

### Steps to reproduce
Add a single page or multi-page PDF document via 'Add Asset(s) -> Upload File'
Observe that no thumbnail is generated

### Error message in logs
pimcore.ERROR: Couldn't create image-thumbnail of document /folder/test.pdf no document adapter is available [] []
 
### Fix
Reverting changes in https://github.com/pimcore/pimcore/issues/3974 fixes the issue

Row to blame
https://github.com/pimcore/pimcore/blob/47f2e3fa2c39e110e93c14e32b2b2f20c1c36307/models/Asset/Document.php#L109

**Comment by brusch** [comment]
Thanks for reporting! 
Unfortunately the error message is misleading, as it isn't an error, just the processing is done asynchronously now (maintenance command has to run first). Fixed now.
