### ISSUE TITLE
[Documents][Editable Link] custom classes are ignored when class is defined in markup

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#5268]
Editable configuration:
```twig
            {{
                pimcore_link('link' ~ suffix, {
                    class: 'btn btn-lg btn-secondary'
                })
            }}
```

Config in Backend: 
![image](https://user-images.githubusercontent.com/8792145/68945892-cb525d80-07b1-11ea-99af-bfcd9a296cbf.png)

In generated markup, manual classes are ignored. 

![image](https://user-images.githubusercontent.com/8792145/68945929-e1f8b480-07b1-11ea-8ddf-dc30036b165f.png)

**Comment by brusch** [comment]
Expected behavior: classes get merged.
