### ISSUE TITLE
[bug] Twig pimcore_iterate_block() UnderflowException: There are no indexes to pop from as index list is empty

### ISSUE THREAD

**Issue by ceefour** [pimcore/pimcore#5272]
# Bug Report

### Expected behavior

Empty HTML output.

### Actual behavior

![image](https://user-images.githubusercontent.com/24123/68988360-9a812f80-0868-11ea-8e23-c95b4c66ff59.png)

UnderflowException  RuntimeError
HTTP 500 Internal Server Error
An exception has been thrown during the rendering of a template ("There are no indexes to pop from as index list is empty").

Exceptions 2Logs 2Stack Traces 2
Twig\Error\
RuntimeError
in app/Resources/views/Includes/sidebar.html.twig (line 11)
<ins class="klookaff_v4" data-wid="11949" data-adid="82720" data-lang="" data-currency="" data-cardH="142" data-padding="120" data-lgH="392" data-edgeValue="655" data-cid="-1" data-tid="-1" data-amount="1" data-prod="dynamic_widget"><a href="//www.klook.com/">Klook.com</a></ins><script type='text/javascript'>(function(d, sc, u) { var s = d.createElement(sc), p = d.getElementsByTagName(sc)[0]; s.type = 'text/javascript'; s.async = true; s.src = u; p.parentNode.insertBefore(s,p); })(document, 'script', '//cdn.klook.com/affiliate_web/s/dist/desktop/affiliate_base_v3.5.js')</script>{{ pimcore_areablock('content') }}<div class="teasers">    {% for i in pimcore_iterate_block(pimcore_block('teasers')) %}        {{ pimcore_snippet('teaser') }}    {% endfor %}</div>{% set articleSelect = pimcore_select('blogArticles', {

### Steps to reproduce

1. You can use the built-in sidebar from twig-demo-basic
2. Delete all teasers from the iterable blocks
3. Template code:

```twig
<div class="teasers">
    {% for i in pimcore_iterate_block(pimcore_block('teasers')) %}
        {{ pimcore_snippet('teaser') }}
    {% endfor %}
</div>
```

**Comment by dvesh3** [comment]
@ceefour cannot reproduce! can you please try with latest version?

**Comment by ceefour** [comment]
code snippey no longer exists in latest demo

**Comment by leuchtdiode** [comment]
I have the same issue in my code as well. Looks like it is only appearing when you one is using pimcore_snippet in pimcore_iterate_block(pimcore_block())

**Comment by dvesh3** [comment]
@leuchtdiode Pimcore version?

**Comment by leuchtdiode** [comment]
> @leuchtdiode Pimcore version?

6.8.5

**Comment by leuchtdiode** [comment]
@dvesh3 Could you take a look at it? Thx!
