### ISSUE TITLE
Field Lookup for Objects

### ISSUE THREAD

**Issue by ckogler-elements** [pimcore/pimcore#5277]
It would be great if we can have the "Field Lookup" Plugin directly in the core. In various projects it is really handy when you have large product classes.... to easy find the field location or its value.

![image](https://user-images.githubusercontent.com/8791970/69047846-663e7800-09fc-11ea-94b4-1ef73db025b5.png)

**Comment by weisswurstkanone** [comment]
somehow related to https://github.com/pimcore/pimcore/issues/2409

Please note that there is currently no language selection which would be necessary for preview of localized data.

**Comment by weisswurstkanone** [comment]
![image](https://user-images.githubusercontent.com/6142086/69162313-bf85d480-0aec-11ea-9739-37d3221844e2.png)

**Comment by weisswurstkanone** [comment]
![image](https://user-images.githubusercontent.com/6142086/69162406-e93efb80-0aec-11ea-97b1-cbf85d6e1ee1.png)

**Comment by weisswurstkanone** [comment]
think about a strategy for class editor as well

**Comment by weisswurstkanone** [comment]
@brusch would this be available for all users or do we need a special permission or user setting ?

**Comment by brusch** [comment]
@weisswurstkanone I'd make that available for all users.

**Comment by weisswurstkanone** [comment]
*) show it only if enabled in class definition (general tab)

**Comment by dpfaffenbauer** [comment]
I wouldn't just limit to just a lookup, also think about the "transformers" used in the grid-editor and graphql. that is quite similar already.
