### ISSUE TITLE
Assets List: Filter "IN" on CreationDate / ModificationDate field not working

### ISSUE THREAD

**Issue by zeor59** [pimcore/pimcore#5279]
### Expected behavior

Be able to use the "ON" filter on the modificationData/CreationDate filters to get the list of Assets created/modified for a provided date.

### Actual behavior
The filter "IN" doesn't works. Only the filters "Before" and "After" are currrently working

### Steps to reproduce

Pimcore V 6.3.1
Try to filter on "ON" Filter on the Asset List to get products created/modified for a provided date.
No results.

![default_asset_list](https://user-images.githubusercontent.com/6772486/69068827-b978f080-0a25-11ea-9b1e-0efc7783fa77.png)

![asset_filter_in_not_working](https://user-images.githubusercontent.com/6772486/69068833-bbdb4a80-0a25-11ea-8116-8317d9331527.png)

Thanks in advance to fix it.

Regards,
Benjamin

**Comment by zeor59** [comment]
Hello,
In which release the fix will be applied ?

Thanks
Benjamin

**Comment by dvesh3** [comment]
@zeor59 I have added this to 6.3.4 release.

**Comment by zeor59** [comment]
Hello,

I just upgraded our PIM into the 6.3.4 version but the filter "ON" seems still not working correctly
If i want to retrieve my assets created the 01 august 2019, i have still no results with the filter "ON".

![list_assets_created](https://user-images.githubusercontent.com/6772486/70310788-c3b23180-1810-11ea-8ff4-11666ee0f1da.png)

![no_items_founds_assets](https://user-images.githubusercontent.com/6772486/70310811-d0368a00-1810-11ea-9b98-12622d2e55de.png)

It's an important feature for our client, can you please check ?

Thanks in advance

Regards,

Benjamin

**Comment by dvesh3** [comment]
Hi @zeor59 you are right. Previous fix works for custom date columns but not for system date columns.

**Comment by dvesh3** [comment]
fixed by f7978b2f343526ac54adaf6dcc2d2573e2447817
