### ISSUE TITLE
[Document][Email] Content is lost when pasting with inheritance

### ISSUE THREAD

**Issue by ljthiel** [pimcore/pimcore#5281]
Firstly, forgive me if this topic has been broadly discussed and dismissed before. I could not find any reference in the issues...

There is currently no option to specify a MasterDocument for Email documents and thus inheritance is seemingly not supported.
I'm sure there is good reason for this but just in case there isn't, inheritance for Email docs would be great :)

Another side effect is that content is lost when pasting an Email doc with inheritance, which is rather unexpected behaviour.

This is easily reproducible in the current demo.
- "Copy" any Email doc.
- "Paste (inheritance)" - any option will do.
- No content in new document.

Thanks!

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
