### ISSUE TITLE
[Data Objects] CSV Import - New Objects Based On Key

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#5303]
# Bug Report

### Expected behavior
Trying to create new data objects by CSV import. I have a CSV file in which the "keys/filenames" are included. 
https://demo.pimcore.fun/admin/login/deeplink?object_763_folder
[csv-import-test-key.zip](https://github.com/pimcore/pimcore/files/3873955/csv-import-test-key.zip)

![image](https://user-images.githubusercontent.com/13643455/69325518-967b5600-0c4a-11ea-8e61-c7139b879dc7.png)

### Actual behavior
Data objects do not get named as configured in import. New objects are created even though there are existing ones with the same key in the CSV.
![image](https://user-images.githubusercontent.com/13643455/69325018-c83fed00-0c49-11ea-8b7b-48a46d0c071a.png)

**Comment by Cruiser13** [comment]
This bug is a huge problem for imports. This used to work fine in older pimcore versions.

**Comment by Yivan** [comment]
@Cruiser13 Same here, we wanted to use it, but we didn't find how to key keys setted... : ((
So all object are created with 1, 2, 3, etc as keys...
It don't work in **Pimcore 6.6.4**

We tried like @ckemptner suggest setting resolver by filename.
And we tried to by assigning the Key system colum in the mapping.
Both end up with numeric keys.

I really hope it could fixed.
Thanks

**Comment by Yivan** [comment]
Just get it !
You need to check overwrite checkbox:

![image](https://user-images.githubusercontent.com/9025839/86176069-b221d580-bb24-11ea-807d-a2227117c2e0.png)

**Comment by ckemptner** [comment]
@Yivan ohh, now I get it too =) 

So it works! I think the user would expect this to be the default behavior (not only should Pimcore create the new object, like it already does, but also name it correctly - there should be no need to tick this "Overwrite" checkbox)

@weisswurstkanone, what do you think?
