### ISSUE TITLE
Object grids are broken after Pimcore 6.3.0 release

### ISSUE THREAD

**Issue by vmalyk** [pimcore/pimcore#5304]
# Bug Report

In PR #5093 was updated classes for Object Grids and removed a lot of methods related with columns, batch update (ex buildColumnConfigMenu). 

So, looks need to fix that:
1. Add these BC changes to Pimcore 6.3.0 backlog
2. Guide how to fix that in another modules.

For ex., Pimcore Advanced Object search

**Comment by fashxp** [comment]
see https://github.com/pimcore/advanced-object-search/issues/64
