### ISSUE TITLE
Issues in Asset CSV/XLSX Export

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#5309]
- Wrong headers in the export file.Headers must be same as those shown in the grid.
- Instead of timestamp,Human readable date format must be exported.

![headers issue in xls export](https://user-images.githubusercontent.com/21308144/69337694-7e75f780-0c87-11ea-958a-490671c34011.png)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
