### ISSUE TITLE
ExtJS 6 Styling - combo boxes line height to big

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#531]
Line height is too big for combo boxes. Here an example for predefined properties:

![image](https://cloud.githubusercontent.com/assets/4639428/14250131/50cf7d62-fa7d-11e5-9f4e-dd467ecd75a0.png)

But this styling "bug" occurs for all combo boxes. It's very hard to recognize the different entries...

**Comment by fashxp** [comment]
fixed in build 3774
