### ISSUE TITLE
Unable to switch to Master layout after opening custom layout

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#5318]
- Open an object.

![default master mode](https://user-images.githubusercontent.com/21308144/69417204-336aeb80-0d3e-11ea-9096-6a84e4af7e98.png)

- Select any custom layout other than master - test

![custom layout 2](https://user-images.githubusercontent.com/21308144/69417205-34038200-0d3e-11ea-992f-5759bc824bdb.png)

- Try to select master layout again.After reload test layout is applied instead of master.

![master not opened](https://user-images.githubusercontent.com/21308144/69417203-336aeb80-0d3e-11ea-8fcc-c1c46e1ee266.png)

**Comment by weisswurstkanone** [comment]
regression of #4866
