### ISSUE TITLE
Wrong Image Preview shown for videos

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#5319]
1. Open a video.

![1](https://user-images.githubusercontent.com/21308144/69419741-1553ba00-0d43-11ea-9432-21567355ff28.png)

2. Drag and Drop an image in the image preview section.Save asset and reload.

![2](https://user-images.githubusercontent.com/21308144/69419740-1553ba00-0d43-11ea-8115-7f0b26ae407e.png)

3. The thumbnail gets updated in the image preview section but not in video.Sometimes it gets updated in both the sections. But the image dragged in previous step was not saved in the asset.

![3](https://user-images.githubusercontent.com/21308144/69419738-1553ba00-0d43-11ea-830c-79dce2bc5879.png)

4. Now drag and drop another image.Save and reload the asset.

![4](https://user-images.githubusercontent.com/21308144/69419736-14bb2380-0d43-11ea-8ee5-f91be66ca308.png)

5. Correct image is show in the preview section but the image used in step 2 is shown in the video.

![5](https://user-images.githubusercontent.com/21308144/69419737-1553ba00-0d43-11ea-8c32-ebd173888c88.png)

**Comment by fashxp** [comment]
cannot be reproduced. 
normally, no save&publish is needed to update the preview-image. 

can you please verify that a request similar to the following is made as soon as a thumbnail is defined: 
https://demo.pimcore.fun/admin/asset/get-video-thumbnail?id=353&width=265&aspectratio=true&image=292&setimage=true&_dc=1574770982695
