### ISSUE TITLE
ExtJs 6 - Text field in object layout - add source button

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#532]
Text hints in object layouts are very limited in styling possibilites. Which is ok - but at least we should add the "show source" button which we had in the Ext3-version. Sometimes it's helpfull to add lists or other things here and there should be at least an "export mode" to accomplish this.

![image](https://cloud.githubusercontent.com/assets/4639428/14252371/5091ba40-fa87-11e5-8bf7-4ae8aab3403a.png)

**Comment by fashxp** [comment]
fixed in build 3774. 
if screen is to small, see 
![image](https://cloud.githubusercontent.com/assets/8792145/15180452/0e60dcec-1782-11e6-9697-d525c31f304d.png)
