### ISSUE TITLE
defunct issue with CDP

### ISSUE THREAD

**Issue by vasanthchellappa** [pimcore/pimcore#5325]
Hi.,
I am facing defunct issue with the CDP-Agent on few of the nodes. 

root@e2e-35-159:~# ps -ef | grep cdp
root       750     1  0  2018 ?        21:52:45 [cdp-2-6] <defunct>

And this one is randomly occurs on mutiple nodes and final solution is to reboot the server. I cannot able to restart the service or even not able to kill the process. 

Also due to this defunct state, server load gets increased and then server become unresponsive. I am trying to find the solution for the same permanent fix.

One of the server is Ubuntu 16.04 LTS

r1soft-cdp-enterprise-agent    -  6.4.2-135

Thanks

**Comment by brusch** [comment]
Sorry, but how is this related to Pimcore? 🤔
