### ISSUE TITLE
[Custom Reports] Timestamp shown in filter dropdown instead of date format

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#5328]
Create a custom report.Select display type as date and filter type as date and filter drilldown as filter and show for o_Modification date

![custom report](https://user-images.githubusercontent.com/21308144/69527898-41657a00-0f93-11ea-8670-eb1c219978cd.png)

In filters human readable format must be shown.Instead of date format, timestamp is shown in filters.

![filter type](https://user-images.githubusercontent.com/21308144/69528049-8b4e6000-0f93-11ea-87cb-daabf29617bc.png)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
