### ISSUE TITLE
[Calculated value] Context for localized calculated field in object brick

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#5337]
When you have a *localized* calculated field in an object brick there is a conflict with the context. As https://pimcore.com/docs/6.x/Development_Documentation/Objects/Object_Classes/Data_Types/Calculated_Value_Type.html states about context:
* Localized fields:
  * position | the language ("en", "de", ...)
  * ownerType | "localizedfield"
  * ownerName | the name of the localized field ("localizedfields")
* Objectbricks
  * ownerType | "objectbrick"
  * ownerName | the name of the objectbrick field inside the object
  * fieldName | the name of the attribute inside the brick
  * index | the name of the brick
  * keyDefinition | the calculated-value field definition

For object bricks also field `position` gets set but to the same value as `fieldName`:
https://github.com/pimcore/pimcore/blob/22882bee401ac3c411a18deb36a3198e942ccc41/models/DataObject/ClassDefinition/Data/Objectbricks.php#L179-L180

When you want to determine the language for the value generation of the calculated field, we need to set `position` to the language here. This currently does not work because the object brick fetches all descendant calculated value fields, not only children - bypassing the localized value field which would add the language as field `position`:
https://github.com/pimcore/pimcore/blob/22882bee401ac3c411a18deb36a3198e942ccc41/models/DataObject/ClassDefinition/Data/Objectbricks.php#L175

**Comment by weisswurstkanone** [comment]
what would be your proposed solution? mayne we can add an additional value?
