### ISSUE TITLE
Geographic Point (object element) broken

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#534]
Tested on online demo version (with extJS6) :
- add "Geographic Point" element to an object classe (exemple to inquiry object on the demo)
- edit an inquiry, maps is broken.

I didn't tested the other geographic elements (bounds an polygon), but must be bugged too maybe.

Thanks

**Comment by brusch** [comment]
Thanks for the info. 
This was only a problem in the demo, because the static maps API wasn't enabled in the Google Cloud Console. 

So this feature requires a valid Google API Browser key in the system settings to work correctly.
