### ISSUE TITLE
[Feature] Yubikey/webauthn support for TwoFactor module

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#5342]
# Feature Request (maybe)

Would Pimcore be interested in a PR that extends the functionality of the current Two-factor authentication to something which implements [Web Authn](https://webauthn.io/) (such as Yubikeys)?

**Comment by brusch** [comment]
Basically yes, but since we don't have the possibility to test it, we're also not able to support it 😟So I'm thinking if it would make sense to make the MFA integration in Pimcore more generic so that also bundles can provide MFA functionalities. 

What do you think?

**Comment by NiklasBr** [comment]
Starting out as a new bundle, similar to how Data-hub is developed, might be a good idea.

Looking at [WordPress/two-factor](/WordPress/two-factor) for inspiration.
