### ISSUE TITLE
Regex non validation doesn't prevent publish object

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#535]
For objects, regex validation (for instance on text field) doens't prevent saving object in case of non regex validation for the field (red marker near the field, but the field is saved and the object published).

Thanks.

**Comment by brusch** [comment]
Really? 
When I create a simple class with one input with a regex validation and press save & publish but the input value doesn't match the regex then i get an error message, and the object is not saved. 

Did i understand anything wrong?

**Comment by brusch** [comment]
see also the attached video: 
[regex-validation-input.zip](https://github.com/pimcore/pimcore/files/206640/regex-validation-input.zip)

**Comment by Yivan** [comment]
Really sorry, it is my mistaque. I was using bad the button on the new extJS6 object edition for publish/unpublish (as it is a littre différent now, but great!). I confirm you it work well (my object was not published in fact).
You can close the task, sorry again about this.
