### ISSUE TITLE
Can't delete folder in backend Users management tree

### ISSUE THREAD

**Issue by FredoVelcro** [pimcore/pimcore#5357]
Hello,

In backend Users management, we can create folders but we can't delete them if needed...
Normal ?
Thank you
Best regards,

Fred

**Comment by dvesh3** [comment]
you mean this? 
![image](https://user-images.githubusercontent.com/5137917/69873800-99fd8580-12b9-11ea-99d5-bbd172daa87f.png)
Unable to reproduce! can you reproduce it on https://demo.pimcore.fun/?

**Comment by FredoVelcro** [comment]
OK perfect ! thank you, we have an oldest version of Pimcore...5.6.6
All is here in 6.x
