### ISSUE TITLE
Export object list don't use no more filter (export all).

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#536]
In previous Pimcore, exporting in the panel object list, exported only the list filtered. It was very good.
In last version all objects are exported, whatever filter you choose.
I think it is a bug, as it is a very needed feature to be able to export qualified listing.

By the way, could it be possible to export only those checked (and if none checked, the complete filtered listing) ? (maybe i should open a separate issue, as it is more an improvement, but very usefull i think if you want juste some lines you cannot actually).

Best regards.

**Comment by weisswurstkanone** [comment]
fixed in build 3722
