### ISSUE TITLE
Feature Request: Twig {% switch %}

### ISSUE THREAD

**Issue by steve-buri** [pimcore/pimcore#5364]
# Feature Request

## Feature description
A switch equal to https://docs.craftcms.com/v2/templating/switch.html

If you currently use` {% switch %} {% endswitch %}` inside a custom area brick, you will receive the message "**Unknown "switch" tag. Did you mean "with"?**"

## Steps to test the feature
Create a folder inside `app/Ressources/views/Areas/test/>` named `view.html.twig`
Create a file inside `src/AppBundle/Document/Areabrick`named `Test.php`

## Code example

```
<?php
// Test.php
namespace AppBundle\Document\Areabrick;

class Test extends AbstractAreabrick
{
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'Test';
    }
}
```

```twig
{# app/Ressources/views/Areas/test/view.html.twig #}

{% set var = "text" %}
{% switch var %}
 {% case "text" %}
    <p>switch works!</p>
{% endswitch %}
```

Thanks in advance
Steve

**Comment by dpfaffenbauer** [comment]
Switch is not a standard Twig Feature, if you want to have it, you can install custom bundles that add it for you.... I don't think that is a requirement Pimcore needs.

**Comment by steve-buri** [comment]
Would be nice to have, but yes. We will add in manually.
Thanks @dpfaffenbauer

**Comment by dpfaffenbauer** [comment]
separation of concerns is the key argument here ;) Thanks for your understanding.
