### ISSUE TITLE
WYSIWYG Images are not shown

### ISSUE THREAD

**Issue by tag-hoaquo** [pimcore/pimcore#5365]
# Bug Report

### Expected behavior

Image displays in CKeditor

### Actual behavior
Image does not display. 

### Steps to reproduce

When adding a picture in the editor (via drag and drop from the assets) the picture appears in the editor as expected. After saving, closing and reopening the topic, the picture does not display. It is also not displayed in the mobile preview. 

# Feature Request
Please fix for WYSIWYG can display image

I realize the WYSIWYG image thumbnail is deferred generated but it never work. I disable the deferred generate then it works as expect. But I'm not sure this behavior is expected or make mistake in other cases

```php

// pimcore\vendor\pimcore\pimcore\models\Asset\Image\Thumbnail\Processor.php / Line 170
// disable following block
if ($deferred) {
      // only add the config to the TmpStore if necessary (the config is auto-generated)
      if (!Config::getByName($config->getName())) {
            $configId = 'thumb_' . $asset->getId() . '__' . md5(self::returnPath($fsPath, false));
                TmpStore::add($configId, $config, 'thumbnail_deferred');
            }

            return self::returnPath($fsPath, $returnAbsolutePath);
        }
}
```

**Comment by dvesh3** [comment]
@tag-hoaquo cannot reproduce! can you please check at demo.pimcore.fun?

**Comment by tag-hoaquo** [comment]
Thanks @dvesh3 , the problem is in our custom CKEditor config make the GD adapter work incorrectly.
