### ISSUE TITLE
[Data objects] Previously inherited relation not removed from query table

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#5374]
Steps to reproduce bug:
1. Create class X
1. Create class Y with inheritance enabled and with a many-to-many object relation field. Allow class X in this relation field
1. Create object "abc" of class X
1. Create object "parent" of class Y
1. Create object "child" of class Y as child of object "parent"
1. Assign object "abc" to the relation field of object "parent"
1. Reload object "child" to ensure the relation field gets its item inherited from "parent", also look at database table object_query_Y to ensure that "parent" and "child" have abc's object id in the relation column
1. Remove "abc" from the relational field of object "child" and save it
1. Look at table object_query_Y, "child" still has the relation to "abc" although we just deleted it

**Comment by dvesh3** [comment]
@BlackbitNeueMedien This is the intention....if the child object field is empty then it should be inherited from parent. I don't understand what is wrong here?

**Comment by BlackbitNeueMedien** [comment]
Oh, you are right, my fault.
