### ISSUE TITLE
getGridFilters() called twice

### ISSUE THREAD

**Issue by alexbaat** [pimcore/pimcore#5377]
In the file bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js in the function createGrid it has these lines

        var gridColumns = gridHelper.getGridColumns();

        // add filters
        this.gridfilters = gridHelper.getGridFilters();

However within the gridHelper.getGridColumns(); in the file bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/grid.js it also contains this line:

        var gridFilters = this.getGridFilters();

So now the function getGridFilters is called twice. I noticed this because I have a long options list and it was causing a delay. I think the call in the file search.js is unneccesary and it seems to work fine when I comment it but I am not sure if this will cause any other problems. Maybe you've put this in ther on purpose. Can you check this?

**Comment by dvesh3** [comment]
@alexbaat you are right, it is not being used anymore. please see https://github.com/pimcore/pimcore/commit/86b07308b66414801bf94c932e3dd6742383a4ba#diff-9b1d0fbb571bb089b7b4839f5dabaa44L283
