### ISSUE TITLE
Cannot set non-owner relation in class editor

### ISSUE THREAD

**Issue by John5** [pimcore/pimcore#538]
In Pimcore 4.0.0 RC2 I cannot set a non-owner relation in the class editor. After choosing an owner class the input "owner field" should show the multihref fields of the selected owner class. Instead it remains empty. Clicking on it opens it and closes it again. The JSON response is as follows:

{"sortinfo":null,"language":"nl","availableFields":[],"onlyDirectChildren":null,"pageSize":null}

The array "availableFields" is empty. But should contain the names of the multihref fields.

**Comment by weisswurstkanone** [comment]
Are we talking about the ExtJS6 user interface ?

**Comment by John5** [comment]
Yes.

**Comment by weisswurstkanone** [comment]
I wasn't able to reproduct this. Can you provide further information?

**Comment by fashxp** [comment]
non owner relations only work with objects fields, not with multihref fields.

**Comment by camico** [comment]
Hi, any chance this (non owner relations) might be added for hrefs (multi and single 1:1)? Or is there a reason it is not possible? At least for those hrefs restricted to objects it should make sense. Or am I missing something?
