### ISSUE TITLE
[Data Objects] Add block above instead of below

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#5380]
# Feature Request
## Feature description
![image](https://user-images.githubusercontent.com/13643455/70148163-eecc4200-16a5-11ea-9eb1-4141e82c4223.png)

Use Case: I am adding new data to a block. I would like to add the new data on the top. If I click on the (+) icon it currently always inserts the new data below the first existing entry. Would be quite helpful if this behavior could be adjusted. I suggest to keep the (+) icon on the top and move the block control icons to the bottom of the block. See my mock up screenshot below. 

![image](https://user-images.githubusercontent.com/13643455/70148935-6e0e4580-16a7-11ea-9333-37a099835449.png)

**Comment by dvesh3** [comment]
would nice to use same add options like Document Bricks:
![image](https://user-images.githubusercontent.com/5137917/70150531-72882d80-16aa-11ea-8df4-16e30db474d0.png)
