### ISSUE TITLE
[Feature Request] Multi-site ready Translations

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#5383]
# Multi-site ready Translations
It would be nice to have at least the shared translations (`Pimcore\Model\Translation\Website`) multi-site ready. This would have the benefit to be able to use the same template across different sites but display different content in each site. Another use-case would be to properly separate the translations for client applications (JavaScript).

**Example:**
- JS-App within site 1 loads only the translations assigned to site 1.
- JS-App within site 2 loads only the translations assigned to site 2.

This massively reduces the network payload and the website loads faster for large applications, where couple of thousands translation keys are available.

**Comment by brusch** [comment]
Why not prefixing them? 
e.g. `site1.myKey` and `site2.myKey`

**Comment by aarongerig** [comment]
Well, let's say I have a template with following code:
```twig
{{ 'site1.my_key'|trans }}
```
Now we can translate that key exactly once in the shared translation panel. If that template is used on multiple pimcore sites, the output is the same everywhere. Whereas it would be useful to define different content on different sites.

Also, providing the client application with that kind of hacky solution (splitting the translation key on `.` and separate them according to the first exploded part) isn't really a good solution for a community bundle, where everyone has to use that approach. As well as it being bad DX ;)

**Comment by passioneight** [comment]
@aarongerig maybe translation domains is what you are looking for? You could create a translation domain for each `Site`, then pass it to the `trans` filter like so:

```twig
{{ 'my_key'|trans({}, pimcore_site_is_request() ? pimcore_site_current().mainDomain) }}
```

**Comment by aarongerig** [comment]
@passioneight That solution would work, yes. Unfortunately one cannot edit any other translation domains than "messages" and "admin" within the Pimcore UI. If that would be possible, this would be the perfect solution to this issue.

**Comment by passioneight** [comment]
@aarongerig have a look at https://github.com/pimcore/pimcore/issues/9738#issuecomment-1145663353. It contains an example of how to create custom translation domains. The domains will be available in the UI afterwards - at least when using Pimcore X.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/57256630/187835728-f597a44a-0f12-4c48-867a-8c3333f64a0d.png)

**Comment by dvesh3** [comment]
@aarongerig @passioneight you can even create a new domain with API:
```php
$translation = new Translation();
$translation->setDomain('custom'); //creates a domain table if doesn't exist.
$translation->setKey('custom key 1');
$translation->setTranslations(['en' => 'custom value en']);
$translation->save();
```
once the table is created by API for new domain then this can be managed in the UI:
![image](https://user-images.githubusercontent.com/5137917/187863372-a9b1f18a-b643-43b4-94a9-acb5bfbf3c11.png)

**Comment by aarongerig** [comment]
@dvesh3 @passioneight Ha, did not know that – but thank you for the hint! I'll close the issue then.
