### ISSUE TITLE
Class name/casing for area brick action

### ISSUE THREAD

**Issue by michaelclaesson** [pimcore/pimcore#539]
# Bug Report
I have an area brick that I have created called **list-events**. The area block works perfectly in admin and frontend, but when trying to add a corresponding action.php the class name expected is "List-events". Since hyphens aren't allowed in class name it will never be able to instantiate this class. Would be neat if instead the class expected was for instance ListEvents. 
  
### Expected behavior 
Would be neat if a folder name of **list-events** (for instance) converted into **ListEvents** instead of **List-events**.
  
### Actual behavior  
Now all the code does it run ucfirst on the folder name. 

### Steps to reproduce 
1) Create an area block where the code resides within a folder with a dash
2) Create an action.php file within this folder
3) Try to have Pimcore find the corresponding class within this file
  
### Code example 
Here ucfirst could be replaced with smarter code for removing dashes, underscores and the likes.

```php
$actionClassname = "\\Pimcore\\Model\\Document\\Tag\\Area\\" . ucfirst($this->currentIndex["type"]);
```

Thanks!
  
 
Regards,
Michael

**Comment by nspacex** [comment]
Hi,

a proposal:

```
.../models/Document/Tag/Area.php ~ 149
$delimiters = ['-','_'];
$actionClassname = "\\Pimcore\\Model\\Document\\Tag\\Area\\" . str_replace($delimiters, '', ucwords($options["type"], implode('', $delimiters)));

.../models/Document/Tag/Areablock.php ~ 208 
$delimiters = ['-','_'];
$actionClassname = "\\Pimcore\\Model\\Document\\Tag\\Area\\" . str_replace($delimiters, '', ucwords($this->currentIndex["type"], implode('', $delimiters)));
```

**Comment by brusch** [comment]
@nspacex looks good - thanks a lot!

**Comment by cleggypdc** [comment]
@brusch added this to the upgrade docs :)

**Comment by brusch** [comment]
@cleggypdc thanks a lot!
