### ISSUE TITLE
Wrong German Translation "Addieren" instead of "hinzufügen"

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#5399]
I currently don't have time to fix that, and I am not sure why it got changed anyway....

![Bildschirmfoto 2019-12-09 um 09 35 21](https://user-images.githubusercontent.com/5981845/70420136-49c7b580-1a67-11ea-8d0c-861d23cb3096.png)

**Comment by blankse** [comment]
It seems it exists the same translation key "add" for "Addieren" and "Hinzufügen"

https://github.com/pimcore/pimcore/blob/f7978b2f343526ac54adaf6dcc2d2573e2447817/bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/Arithmetic.js#L100

https://github.com/pimcore/pimcore/blob/f7978b2f343526ac54adaf6dcc2d2573e2447817/bundles/AdminBundle/Resources/public/js/pimcore/object/class.js#L92
