### ISSUE TITLE
Stream not closed when creating temporary file

### ISSUE THREAD

**Issue by petterjv** [pimcore/pimcore#5402]
# Bug Report

### Description
When public method Pimcore\Model\Asset::getTemporaryFile() is called without having a source stream, a new one is created. But it is not closed until descruct is called. If there is a long running job there is a lot of open files. 

The issue was found is when using imagick adapter with external source storage (stream is not local).
```php
// In Pimcore\Image\Adapter\Imagick
if (!stream_is_local($imagePath) && isset($options['asset'])) {
	// imagick is only able to deal with local files
	// if your're using custom stream wrappers this wouldn't work, so we create a temp. local copy
	$imagePath = $options['asset']->getTemporaryFile();
	$this->tmpFiles[] = $imagePath;
}
```

### Expected behavior
Stream is closed properly when creating temporary file.

### Actual behavior
Stream is not closed properly.

### Steps to reproduce
Load a list of assets, create temporary file for each asset. Between each loop, check open files with for the process for example by using lsof -p.

### Code example
My suggestion is to always close the source stream after creating the temporary file.

```php
/**
 * returns the path to a temp file
 *
 * @return string
 */
public function getTemporaryFile()
{
	$destinationPath = PIMCORE_SYSTEM_TEMP_DIRECTORY . '/asset-temporary/asset_' . $this->getId() . '_' . md5(microtime()) . '__' . $this->getFilename();
	if (!is_dir(dirname($destinationPath))) {
		File::mkdir(dirname($destinationPath));
	}

	$src = $this->getStream();
	$dest = fopen($destinationPath, 'w+', false, File::getContext());
	stream_copy_to_stream($src, $dest);
	fclose($dest);
	$this->closeStream(); // ADDED

	@chmod($destinationPath, File::getDefaultMode());

	$this->_temporaryFiles[] = $destinationPath;

	return $destinationPath;
}
```

**Comment by brusch** [comment]
I guess there's no way for solving this in a generic way. 
Please just do not call `getTemporaryFile()` (which is anyway `@internal` ) before the data was persisted.
