### ISSUE TITLE
[DataObject] Link field after Pimcore update has invalid data

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#5404]
- Start with Pimcore 4
- Have a `Link` field inside an object
- Update to Pimcore 5 (never save the object)
- Update to Pimcore 6
- Call `$object->getLink()`

You will get the following error:
`The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;Pimcore\Model\Object\Data\Link&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition`

You will get an incomplete class because Pimcore tries to unserialize the data from the db and `Pimcore\Model\Object\Data\Link` does not exist anymore.
![image](https://user-images.githubusercontent.com/7206334/70448674-fe31fd80-1aa0-11ea-9ec2-03a4bfa870a2.png)

To fix this we will need an update script somewhere in Pimcore 5 that rewrites the serialized data for the Link field from `Pimcore\Model\Object\Data\Link` to `Pimcore\Model\DataObject\Data\Link`

**Comment by brusch** [comment]
This script should do the job of migrating the content: 
https://gist.github.com/brusch/56f0405b5210e97bf9db6c48cd237bf3 

Feedback highly appreciated! 😊

**Comment by brusch** [comment]
Instructions see: https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/Updating_Pimcore/V5_to_V6.html#page_Run-the-content-migration-script

**Comment by ultramegatom** [comment]
worked for me thanks :)

**Comment by brusch** [comment]
Awesome, thanks for your feedback!
