### ISSUE TITLE
Bulk import not working with Ext JS 6

### ISSUE THREAD

**Issue by zieglerh** [pimcore/pimcore#541]
# Bug Report

### Expected behavior 
  Can use bulk import with the new extjs6 ui enabled
### Actual behavior  
  When uploading a previously exported bulk_export.json you'll get an js exception
```
TypeError: Ext.data.GroupingStore is not a constructor
```
The class "Ext.data.GroupingStore" is not part of Ext JS 6 anymore and nowhere defined in /static6/
Haven't tested any further.

### Steps to reproduce  
  Use bulk export and import with extj6 enabled

**Comment by weisswurstkanone** [comment]
fixed in build 3724

**Comment by zieglerh** [comment]
Thank you
