### ISSUE TITLE
Field Level Controlled Inheritance

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#5416]
Sometimes, you don't want certain fields to inherit but you want some to inherit. In that case, I always work with "dummy" values to break inheritance. (Thinks like a Metadata ManyToMany with Warehouses and Stock Quantity, a product can not inherit stock-values, since it is SKU based)

I think it should be quite easy possible for Pimcore to check on a field-definition level if inheritance is enabled or not, if not, don't inherit.

WDYT?

**Comment by fashxp** [comment]
updating query tables could be somehow challenging.

**Comment by dpfaffenbauer** [comment]
why?

**Comment by NiklasBr** [comment]
I would like to push for this once again, we discovered that it's not a good idea to allow URL Slugs (in addition to the examples mentioned), so it would be nice to be able to stop inheritance at the model level for some fields.

**Comment by brusch** [comment]
I agree, would love to see that as well 😊
However I think that needs to be carefully prepared and shouldn't be a quick shot development. 
A minimum requirement is to cover all possible cases (existing and new) by tests.

**Comment by TS1997** [comment]
I agree and would also like to push for this

**Comment by passioneight** [comment]
+1 for this feature. Which milestone can we expect?

**Comment by brusch** [comment]
Reopened since we had to revert #10719 because of challenge described in follow-up PR #10931

**Comment by Cruiser13** [comment]
@dpfaffenbauer I don't see that this is completed yet but I might miss something here?

**Comment by dpfaffenbauer** [comment]
@Cruiser13 it's been over 4 years now. didn't happen so I closed it

**Comment by Cruiser13** [comment]
I think we've almost been there with #10719 in 2022. @brusch what do you think? Might be a strong feature if I look at all the comments in this thread.

**Comment by MarcoLeko** [comment]
+1 From our side - this would be a pretty handy feature to have configurable

**Comment by medovanx** [comment]
+1 would be nice to have this!
