### ISSUE TITLE
Don't merge Security Config

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#5417]
What actually is the idea behind Pimcore to merge the Symfony Security Config of Bundles? This can cause issues like:

 - I cannot change Pimcore's or Bundle's Security configurations. Like Changing certain Guards or other things
 - Developers might not understand what is going on, cause it is not Standard Symfony behaviour.

My proposal: Deprecate it with Pimcore 6.4 and remove it with Pimcore 7.0. With the skeleton, Pimcore has the chance anyway to delivery a security config for Pimcore Backend anyway.

**Comment by dpfaffenbauer** [comment]
Just came across that again. Imagine following scenario:

 - Install CMF
 - Install Dachcom Members
 - Install CoreShop

Use one User for all 3 bundles, you still end up having 3 firewalls in your security config where only one is actually needed.....

**Comment by aarongerig** [comment]
Another scenario where this makes problems. Imagine multiple security configs from different bundles are getting merged. In your AppBundle you want to introduce an OAuth Firewall, which listens to requests being made to `/oauth/*`. Now because multiple security configs are merged in an order you cannot change, the wrong firewall gets applied because it doesn't exclude the pattern `/oauth/*` and therefore the wrong actions are being called.

**Comment by albertmueller** [comment]
that always annoys me too, every time i have to set exclude patterns...

**Comment by brusch** [comment]
A detailed description for the reason can be found here: 
https://github.com/pimcore/pimcore/blob/3c61087ee0b37fd3d58d762d31ca539bd7e399e8/bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php#L532

**Comment by dpfaffenbauer** [comment]
Symfony Flex solves this by adding needed configs automatically on installation. Also, since the skeleton is provided by Pimcore anyway, the security config could be there.

**Comment by dpfaffenbauer** [comment]
Since Pimcore 7 is on the way now, can we please discuss this? Having security configs merged, gives you bad DX and no control over security (since bundles have that control)

**Comment by kjkooistra-youwe** [comment]
Use case: https://talk.pimcore.org/t/how-to-integrate-users-of-pimcoremember-bundle-with-coreshop/2384

**Comment by brusch** [comment]
https://github.com/pimcore/pimcore/blob/2662d44a8828ad8fc7c8d878020b115f8ba61d69/bundles/AdminBundle/Controller/AdminController.php#L36

With that we also have a 2nd layer of security in this regard, so I guess it would be fine to move that to the project config.
