### ISSUE TITLE
search in object tree (paging-toolbar) disappears after use

### ISSUE THREAD

**Issue by fmuelhaupt** [pimcore/pimcore#5421]
### Expected behavior
If you filter the object tree with the search functionality (in the paging-toolbar), the toolbar stays visible after filtering, regardless of result numbers
### Actual behavior
If the search returns less than 30 elements, the paging-toolbar disappears and there is no indication, that the current tree is filtered.
You can only reset the filter if you reload the object tree via context menu.

### Steps to reproduce
- Open an object tree with more than 30 elements
- filter the tree to have less than 30 elements

**Comment by weisswurstkanone** [comment]
Unable to reproduce, see recording from demo

[treefilter.zip](https://github.com/pimcore/pimcore/files/3950457/treefilter.zip)

**Comment by weisswurstkanone** [comment]
maybe you forgot to mention the perspective scenario: see https://github.com/pimcore/pimcore/issues/5398

**Comment by fmuelhaupt** [comment]
thats it, thanks for linking
