### ISSUE TITLE
ExtJS 6: checkbox HTML markup error

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#543]
The new checkbox in pimcore 4 (ExtJS 6) has to me a wrong HTML markup.

**Expected behaviour**
```html
<div class="pimcore_editable pimcore_tag_checkbox">
    <input type="checkbox">
    <label for="">Checkbox Label</label>
</div>
```
The label tag should be right next to the input[type="checkbox"] tag. This way you can style a checkbox correctly.

**Actual behaviour**
```html
<div class="pimcore_editable pimcore_tag_checkbox">
    <input type="checkbox">
</div>
<label for="">Checkbox Label</label>
```

**Comment by brusch** [comment]
How did you add the label?
Actually I don't see the possibility to add a label at all. 

Thanks for clarifying.

**Comment by aarongerig** [comment]
<div class="custom-check">
<?= $this->checkbox("myCheckbox") ?>
<label for="myCheckbox">My Checkbox</label>
</div>

Worked perfectly fine until pimcore v3.1.1, that's why I reported this issue.

**Comment by brusch** [comment]
Thanks! 

But the output of  
```php
<?= $this->checkbox("myCheckbox") ?>
``` 
was also wrapped by a `div` in version 3 - so maybe it's a different issue?

**Comment by aarongerig** [comment]
This is what it looked like in version 3:

```html
<div class="pimcore_editable pimcore_tag_checkbox">
    <div class="x-form-check-wrap" id="ext-gen55">
        <input type="checkbox" autocomplete="off" class="x-form-checkbox x-form-field" checked="">
        <label class="x-form-cb-label" for="ext-comp-1021" id="ext-gen56">&nbsp;</label>
    </div>
</div>
```

**Comment by brusch** [comment]
Yes, but the label way generated by pimcore and was not part of your template :) 
So your example would produce the following output: 

```php 
<div class="custom-check">
    <div class="pimcore_editable pimcore_tag_checkbox">
        <div class="x-form-check-wrap" id="ext-gen55">
            <input type="checkbox" autocomplete="off" class="x-form-checkbox x-form-field" checked="">
            <label class="x-form-cb-label" for="ext-comp-1021" id="ext-gen56">&nbsp;</label>
        </div>
    </div>
    <label for="myCheckbox">My Checkbox</label>
</div>
```

**Comment by aarongerig** [comment]
Sure, but why is there no <label> inside the <div> anymore?

**Comment by brusch** [comment]
The reason is that pimcore 4 doesn't use the ExtJS component for the checkbox anymore.
I've now implemented a new `label` option, which adds a label after the `<input>` when specified: 

```php
<?= $this->checkbox("myCheckbox", ["label" => "My Text Label"]) ?>
```

see also: 
https://www.pimcore.org/wiki/display/PIMCORE4/Checkbox

**Comment by brusch** [comment]
Build => 3734

**Comment by aarongerig** [comment]
Thank's @brusch !
