### ISSUE TITLE
Error while creating PDF asset : Couldn't get text out of document...

### ISSUE THREAD

**Issue by FredoVelcro** [pimcore/pimcore#5437]
When creating an asset from a PDF file, in CLI mode, i have this error : 
```
Couldn't get text out of document "mydoc.pdf" no document adapter is available
```
We have ghostscript installed for info.
Any idea ?

The asset is however created...but cannot be previewed en backend !
When we download it from backend, we got the file.

**Comment by brusch** [comment]
This is not really an error, I've changed the log level.
