### ISSUE TITLE
[Document] Area Block: display info message when pressing a button in the shared toolbar

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#5438]
# Bug Report

Pimcore Version: 6.3.5 (happend also in 6.2)

The problem was already described extensivly in: https://talk.pimcore.org/t/areabrick-plus-is-not-working/2915/2

# Expected behaviour

When selecting a brick within the plus in the toolbar it should be added to (one of?) the Pimcore Areablocks. If this is not possible, there should be no plus in the toolbar.

# Actual behaviour

The menu freezes when clicking on a Brick.

# Steps to reproduce

Add one - or maybe multiple `pimcore_areablock('uniqueId')` to your twig template. This makes the plus in the toolbar show up. Click the plus and select select a Brick. Not sure if the Bug exists in multiple installations.

The following picture illustrates the Problem:

![Bug with adding bricks](https://talk.pimcore.org/uploads/default/original/2X/e/e46d1feb5025e9c24424b2b4bccfd0a819d32813.png)

Guess that this might happen in some brick template nesting or with some HTML? Can you implement a more robust script in order to avoid this problem?

**Comment by brusch** [comment]
Added an info message: 
![image](https://user-images.githubusercontent.com/142037/70722890-51ea5400-1cf8-11ea-8b05-f48512a24fb3.png)

**Comment by Blackbam** [comment]
Thanks!
