### ISSUE TITLE
[Pimcore Bundles] Execute migrations of Pimcore Bundles automatically on composer update? 

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#5445]
right now, composer update updates composer dependencies, but potential migrations are not executed - and therefor project might be broken unless migrations are executed.

**Comment by dpfaffenbauer** [comment]
composer is not responsible of executing migrations. This should be sorted in a proper deployment procedure like: https://github.com/w-vision/pimcore-deployer/blob/master/deploy.sample.php#L78

**Comment by dpfaffenbauer** [comment]
I also always remove the composer script where Pimcore executes core migrations. That is completely wrong. Composer is about handling dependencies, not deployment tasks!

**Comment by BlackbitNeueMedien** [comment]
What do you think of a configuration in `app/config/config.yml` to set if migrations should be executed automatically on composer update - be it core or bundle migrations?
