### ISSUE TITLE
The notifications table should have an index on "recipient"

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#5454]
# Feature Request
The notification table is polled frequently in the Pimcore backend. 

1. Many applications event don't use this feature. Is there a way to disable notifications?
2. ``ALTER TABLE `notifications` ADD INDEX `recipient` (`recipient`);`` should be applied to the database table so that querying notifications for a specific Pimcore user is done via index.

**Comment by brusch** [comment]
Currently there's no way to disable the feature globally, I'd say that's a topic for another issue. 
The index on the `notifications` table should be added to the `install.sql` + a migration script.
