### ISSUE TITLE
[Document] Use CSS cursor:move for brick selection toolbar in editmode

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#5455]
# Feature Request

## Feature description
Draggable elements within the admin UI have led to a lot of confusion to use because it is not always obvious that elements are draggable / droppable (as described here: https://github.com/pimcore/pimcore/issues/5438). One reason is that they are using

`cursor:pointer;`

which is usually used for **_clickable elements, not draggable elements_**. It would be quite an easy change to use:

`cursor:move;`

for drag and droppable elements within the admin UI. This would also be correct in terms of the official cursor specifications - https://developer.mozilla.org/de/docs/Web/CSS/cursor . E.g. cursor:move is explicitly specified for drag & drop purposes.

**Comment by brusch** [comment]
Can you be a bit more specific? Which elements are you talking about in detail? 
Imho elements which are clickable AND draggable should use `cursor:pointer;`. 
Elements wich are just draggable should use `cursor:move;`.

**Comment by Blackbam** [comment]
It seems like meanwhile you have implemented an info message:

"Please use drag & drop to assign a brick to the desired block"

This is also o.k. Still in terms of usability I think that `cursor:move;` would be the correct answer here.

**Comment by brusch** [comment]
Ah you meant for the brick selection, you're right, here `cursor:move;` would be definitely the better option. 😊
