### ISSUE TITLE
Cannot unset search field in elementtree in other perspective

### ISSUE THREAD

**Issue by alexbaat** [pimcore/pimcore#5456]
Within the element tree in my default perspective I can easily search within the elementtree. To unset the search field I can click the cross icon.
However in another perspective with a customview I can also search, but I cannot unset the searchfield because the icon is not appearing.
Please see my screencast in attached zip.

I've tested in Pimcore 5 and 6. Is this a known bug?

[screencast-localhost-2019.12.16-16_28_11.zip](https://github.com/pimcore/pimcore/files/3968777/screencast-localhost-2019.12.16-16_28_11.zip)

**Comment by weisswurstkanone** [comment]
already fixed. see #5398
