### ISSUE TITLE
Grouping Bricks and implement Multi-Level Menu in Pimcore Admin

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#5465]
# Feature Request

## Feature description

This is an explicit request by one of our clients and it would be great if someone finds time for that. In a big project we have a lot of custom brick definitions in `AppBundle\Document\Areabrick` - they are all extending  `Pimcore\Extension\Document\Areabrick\AbstractTemplateAreabrick`. 

This results in a long scrollable list of bricks as you can see here:

![Many Bricks](https://user-images.githubusercontent.com/1703552/70987200-b5d99780-20bf-11ea-9777-c15ddcb2a185.png)

In the future some more are yet to come. For users it becomes a bit clumsy to always scroll through such a large number of bricks in order to find a certain one. 

Therefore we think it would be great to have a possibility of nativley grouping bricks like e.g. "Basic Bricks", "Full Content Bricks", "Includer Bricks", "Columnized Bricks", ... whatever.

Within the admin menu instead of directly selecting a brick one should be able to select a group flyout menu and if you hover it the corresponding menu with the bricks is opened.

**Comment by dpfaffenbauer** [comment]
That is already possible.... 

https://pimcore.com/docs/6.x/Development_Documentation/Documents/Editables/Areablock/index.html

Or, even better with the Toolbox:

https://github.com/dachcom-digital/pimcore-toolbox/blob/master/docs/0_Usage.md#toolbar-configuration
