### ISSUE TITLE
Wrong position of the wysiwig toolbar

### ISSUE THREAD

**Issue by baloraki** [pimcore/pimcore#5469]
# Bug Report
The Ck4Editor toolbar has a wrong position.

![image](https://user-images.githubusercontent.com/41831573/71011515-d3255a80-20ed-11ea-9240-747f41f765f3.png)

### Expected behavior
The toolbar is positioned above or below the field.

### Steps to reproduce
1. Fill Wysiwig field with content until a scrollbar appears.
2. Remove the focus from the field
3. Scroll without a focus on the field to e.g. the center of the field
4. Put the focus on the field

**Comment by weisswurstkanone** [comment]
There is nothing we can do about this because the position of the floating toolbar is handled by CKEditor itself.
