### ISSUE TITLE
autoload-classmap.php not loading from /website/config

### ISSUE THREAD

**Issue by timhonders** [pimcore/pimcore#547]
When i put a startup.php in /website/config/ it isn't loading like explained in 

https://www.pimcore.org/wiki/display/PIMCORE4/Hook+into+the+startup-process

When i debug: $websiteStartup = \Pimcore\Config::locateConfigFile("startup.php");

it tries to include the startup from the /website/var/config
  
the /autoload-classmap.php has the same problem

**Comment by brusch** [comment]
Just tried it and it works as expected... 

see also: https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Config.php#L37-L37

first it looks in /website/config/ then (for compatibility reasons) in /website/var/config/

**Comment by brusch** [comment]
Not sure what your problem is, but it doesn't seem to be a general problem. 
Please further investigate this and tell us how to reproduce it or even better create a pull request for us :)

**Comment by timhonders** [comment]
Ok im gonna investigate further

**Comment by timhonders** [comment]
Strange its working now startup.php at least, but the problem is the auto-classmap.php

https://github.com/pimcore/pimcore/blob/master/pimcore/config/startup.php

From line 136

// register class map loader => speed
$autoloaderClassMapFiles = array(
    PIMCORE_CONFIGURATION_DIRECTORY . "/autoload-classmap.php",
    PIMCORE_PATH . "/config/autoload-classmap.php"
);

This code ony checks the var config for autoload-classmap.php, when i add an extra path:

// register class map loader => speed
$autoloaderClassMapFiles = array(
    PIMCORE_WEBSITE_PATH . "/config/autoload-classmap.php",
    PIMCORE_CONFIGURATION_DIRECTORY . "/autoload-classmap.php",
    PIMCORE_PATH . "/config/autoload-classmap.php"
);

It works.

i can't make a pull request at the moment sorry.

**Comment by brusch** [comment]
autoload-classmap.php wasn't intended to be loaded from /website/config/ but it can't hurt :)

**Comment by timhonders** [comment]
Ah ok the sample was in that dir :)
