### ISSUE TITLE
Ecommerce Performance | Cart Queries should use index

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#5476]
# Performance Improvement

## Problem Summary
Every cart load includes loading all cart items. Slow query log analysis shows that in webshops typically
-  cart items are loaded frequently.
- the query for loading cart items currently does not utilize any SQL index.

## Problem Details
Those are two of the queries that do not use an index:
```sql
SELECT cartid, itemKey, parentItemKey FROM ecommerceframework_cartitem WHERE cartId =2232 AND parentItemKey = ''  ORDER BY `sortIndex` ASC, `addedDateTimestamp` ASC;
```

```sql
SELECT COUNT(*) as amount FROM `ecommerceframework_cartitem` WHERE cartId = '2246' AND parentItemKey = '';
```

## Solution Concept
Add an additional index to the cartitem table:
```sql
ALTER TABLE `ecommerceframework_cartitem` ADD INDEX `cartIdIndex` (`cartId`,`parentItemKey`);
```
This statement should be added to the Pimcore (migrations?).

**Comment by brusch** [comment]
Installer + migration script.

**Comment by dvesh3** [comment]
resolved by https://github.com/pimcore/pimcore/pull/5506
