### ISSUE TITLE
Support for Xdebug JIT mode

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#5484]
Hello,

Using xdebug on Pimcore, when using REQ mode or more annoying when using JIT mode, it send an error.
I think the include should properly verify file existence instead using a dirty `@`
Please see the revelant code here: https://github.com/pimcore/pimcore/blob/master/lib/Bootstrap.php#L178

And the xdebug message (on visual code, but shluld be same on all IDE I think):

![pimcore-xdebug](https://user-images.githubusercontent.com/9025839/71097191-e7319080-21af-11ea-93e1-d563d0cc5c28.png)

I hope it could be fixed, as for now JIT feature of xdebug is not usable as there will be an error directly when Pimcore bootstrap (for information JIT feature is explained here: https://xdebug.org/docs/all_settings on setting `xdebug.remote_mode`).

Thanks

**Comment by brusch** [comment]
We borrowed this line from Symfony: 
https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/config/bootstrap.php#L9 

So maybe you can create an issue there as well - Thanks!

**Comment by Yivan** [comment]
Thanks!
I opened an issue on Symfony side too: https://github.com/symfony/recipes/issues/717

**Comment by solverat** [comment]
@brusch over at symfony, nicolas-grekas came up with a [good point](https://github.com/symfony/recipes/issues/717#issuecomment-570398726):

> "We rejected using file_exists() before because it creates i/o, which we'd better avoid on the hot path when we can, especially for working around broken tools."

I'm with him, how about you? :)

**Comment by brusch** [comment]
@solverat good point, haven't thought about that yet 😊

**Comment by brusch** [comment]
But it could be also dangerous ... u know using `@` is in general not really a good idea 😐
But for me it would be ok to change that in Pimcore as well for the includes in the hot path. PR's are as always welcome 😉
