### ISSUE TITLE
[Improvement] When using one click save grid, ask always for name

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#5491]
Hello,

This issue is for user improvment experience.

When saving a grid, it ask for name only if user was on the predefined grid.
If he is already on a custom grid saved grid, it will update it without any warning/confirmation.

It would be better to ask for name (like the first time you save a grid), so user can confirm the action or change the name to a new saved grid.

Please see:
![image](https://user-images.githubusercontent.com/9025839/71186780-17476500-227e-11ea-85fd-c75a92cbb63f.png)

Actually it is a problem because user can save on existing preset without any confirmation. Human error can be easy. A confirm message would be better. And open the name popin so he can change it would be even better.
In case of shared filter, it will prevent changing it untintentionnaly (i didn't test if other user can save againt a shared one).

Thanks.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
