### ISSUE TITLE
PDFreactor losslessly embed pdf pages

### ISSUE THREAD

**Issue by haapakanni** [pimcore/pimcore#5493]
# Feature Request

## Feature description
Feature improves significantly quality of pdf output by using pdfreactor losslessly embed pdfs. Todo so please refactor models/Document/Tag/Pdf::frontend method, https://github.com/pimcore/pimcore/blob/master/models/Document/Tag/Pdf.php, to meet the pdfreactor documentation, https://www.pdfreactor.com/product/doc_html/index.html#PdfImages, by using the pdf file instead of lossy thumbnail image. May also reduce filesize of output pdf to even half and more of original size depending on source pdf.

### Code example
```php
            /* Use the pdf file as src to improve quality and to reduce output file size */
            $code = <<<HTML
                <div id="$divId" class="pimcore-pdfViewer">
                    <img src="$pdfPath" />
                </div>
HTML;
            
            /* Use the lossy thumbnail img only for preview tab in UI */
            if (isset($_GET["pimcore_preview"]) && $_GET["pimcore_preview"]) {
                $code = <<<HTML
                <div id="$divId" class="pimcore-pdfViewer">
                    <a href="$pdfPath" target="_blank"><img src="$thumbnailPath"></a>
                 </div>
HTML;
            }
```

**Comment by haapakanni** [comment]
Overriding the pimcore pdf model would be one way to solve the issue but it's not possible (yet) as referred here for another purpose https://talk.pimcore.org/t/is-overriding-pimcore-pdf-model-supported/2518

**Comment by haapakanni** [comment]
Also css-property-ro-source-area implementation https://www.pdfreactor.com/product/doc_html/index.html#css-property-ro-source-area would be nice addition. Perhaps custom property named as "ro-source-area" could be set for pdf-assets and then generated as attribute for the img-html element in the models/Document/Tag/Pdf::frontend method.

**Comment by haapakanni** [comment]
Comparison and example between losslessly embed pdf and lossy as attachment.
![lossless-embredded-pdf-by-pdfreactor](https://user-images.githubusercontent.com/39362660/72060768-4b420300-32dd-11ea-8baa-9764372f800c.jpg)

**Comment by fashxp** [comment]
if we add this feature, it needs to be a configuration option (since the pdf editable can also be used on normal document pages and browsers cannot render pdf then). 

could you provide a PR?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
