### ISSUE TITLE
[DataObjects] Calculated Values in localized fields broken

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#5504]
regression of #5390

see https://github.com/pimcore/pimcore/pull/5390/files#diff-0ff986fbdd2f0c6a070ea4d2f14dc8caR366 ... there is no `$this->getFieldname` in data object context...

**Comment by fashxp** [comment]
reverted change for now. 

@BlackbitNeueMedien  please check and fix that properly.

**Comment by BlackbitNeueMedien** [comment]
Thanks @weisswurstkanone for fixing this. That is collective code ownership!
