### ISSUE TITLE
Remove MaxMind GeoIP2 download/update task

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#5512]
# Bug Report
### Expected behavior
Pimcore Maintenance Cronjob does work without issues.
### Actual behavior
Pimcore Maintenance Cronjob does throw an exception:

> ERROR     [pimcore] Failed to update MaxMind GeoIP2, size is under about 1M

### Reason
The source for the geoip database (located at https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz ) is offline. The relevant code can be found here:
https://github.com/pimcore/pimcore/blob/master/lib/Maintenance/Tasks/DownloadMaxMinDbTask.php#L42

Looks like Maxmind took this offline at 31-12-2019:
https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

**Comment by mediafant** [comment]
Database is not offline. Now it is necessary to sign in and take a token to get the database.

**Comment by Yivan** [comment]
@Cruiser13 
We are hitting this problem on v5 Pimcore, and we cannot update it.
How do you resolved it, is there any way to fix it exept updating pimcore or manually patch files core ?

@brush Is there any official advice on this please as it would affect any Pimcore in production running maintenance job ? I checked documentation and cannot find any mentions. Maybe this advice could be given in this issue (I asked on gitter but it will fall in the limb of gitter in a few day/week) so people encoutering the same problem can patch it a good way.

Just a side question, does this exception stop the maintenance script or it is just "visual" ?

Thanks

**Comment by dpfaffenbauer** [comment]
Check this: https://dev.maxmind.com/geoip/geoipupdate/

**Comment by Yivan** [comment]
Thanks @dpfaffenbauer I saw we can register (as now it is paid account), but as request is done during maintainance by Pimcore I was thinking it need some special "patches". You mean so Picmore would detect there is geoip installed and run "geoipupdate" program (which will get crednetials form the GeoIP.conf file) ? If yes this is great and solution the problem without patching core files.

**Comment by dpfaffenbauer** [comment]
no. patch pimcore yourself or update the project... Pimcore is not responsible for dealing with changes made by others causing issues with past versions...

**Comment by Yivan** [comment]
Yes totally agree, but as it breaks maintenance script, i was thinking there was maybe some official way (i imagine it hurts all production instances so maintenance jobs does not work no more... and updating them is not so easily).

A solution would be to duplicate the maintenance job as another job and strip out geoip from it. And call in cron this new job instead the core one. I think it is the best proper way. But before reinventing the weel, i was invastigating here to see if official recommendation exists.

Thanks!

**Comment by dpfaffenbauer** [comment]
I think you can already call the maintenance script with only certain tasks, or also exclude some, so that should already work for you.

**Comment by Yivan** [comment]
Yes, i confirm task can be excluded:

```
php bin/console maintenance --excludedJobs=downloadmaxminddb
```

Perfect solution : ) Many thanks @dpfaffenbauer 

By the way after digging the logs, the geo2ip error in the maintenance job does not prevent the maintenance to finish. So (except it doesn't update the ip db) it doesn't affect the rest of the jobs.

**Comment by brusch** [comment]
@Yivan yep, excluding the job is the way to go! 👍

**Comment by ayoob-lfc** [comment]
@Yivan 
FYI: We ran into the same issue, and are migrating to lite.ip2location.com. I'm find there locations much more accurate than maxmindDB
