### ISSUE TITLE
[ApplicationLogger] Error on showing FileObject on Windows

### ISSUE THREAD

**Issue by MarcoGuiducci** [pimcore/pimcore#5518]
Hi,

I have succesfully created a couple of entries on the ApplicationLogger.
When I try to open the attached FileObject I get the following error:

preg_match(): Compilation failed: unknown property name after \P or \p at offset 18

The error is in the LogController class; here the reference https://github.com/pimcore/pimcore/blob/91a113ea5a14479f49bad9e463349018aae71b93/bundles/AdminBundle/Controller/Admin/LogController.php#L247

The problem is that, on Windows, file paths contains the backslash "\\" character instead of the slash "/" as linux.
It's common to have a \pimcore subfolder in Pimcore's projects, but for the preg_match function, \p is a pattern escape, and so the error.

**Comment by MohammedAlkutrani** [comment]
I'll fix it
