### ISSUE TITLE
[Documents|Objects] Non-deterministic results of getChildren and hasChildren

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#5521]
- if on a document `getChildren(true)` is called, also unpublished children are loaded into local `children` variable and returned. 
- if later in same process `getChildren()` is called, unpublished children are still returned even not expected. 

- when calling just `getChildren()` first and later `getChildren(true)`, on second call no unpublished children are returned even they are expected though. 

same goes for `hasChildren`. 

`$unpublished` parameter needs to be considered when caching the results of these methods.

**Comment by brusch** [comment]
Same happens for all kind of list parameters such as `setObjectTypes()` `setUnpublished()` `setLocale()` `setIgnoreLocalizedFields()` `addFieldCollection()` ... and probably many others.

**Comment by brusch** [comment]
And of course also for Data Objects ...

**Comment by weisswurstkanone** [comment]
maybe relevant for #5103
