### ISSUE TITLE
Deprecated array_key_exists in cache Runtime.php

### ISSUE THREAD

**Issue by dersuperheld** [pimcore/pimcore#5534]
Hello,
After Upgrade to PHP 7.4 we got many annoying deprecated warnings from
https://github.com/pimcore/pimcore/blob/61c377593d81e0c0daf5013e49bd450142a1a549/lib/Cache/Runtime.php#L174

This is because Runtime extends an ArrayObject.

Can you please fix this?

Using Pimcore 6.3.6

**Comment by brusch** [comment]
@dersuperheld I'm not able to reproduce this, can you please give me an example or even better a working PR? 

Tried the following code: 
```php
        error_reporting(E_ALL);
        $foo = Runtime::getInstance();
        $foo->offsetExists('foo');
```

**Comment by NiklasBr** [comment]
`array_key_exists` on objects [is being deprecated](https://wiki.php.net/rfc/deprecations_php_7_4)

From [the docs](https://www.php.net/manual/en/function.array-key-exists.php):

>  For backward compatibility reasons, array_key_exists() will also return TRUE if key is a property defined within an object given as array. This behaviour should not be relied upon, and care should be taken to ensure that array is an array.
> To check whether a property exists in an object, use property_exists().
