### ISSUE TITLE
Sort objects in tree from Z-A

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#5540]
Especially useful when objects are named by year/date to show latest date on top.

How it looks now
![image](https://user-images.githubusercontent.com/13643455/71905382-57f11a80-3168-11ea-9eed-573831587f67.png)

Suggested improvement
1) Rename "Key (Alphabetically)" to "A to Z"
2) Add option "Z to A"
3) Rename "Index (Ordered by Manually)" to "Manual"

=> Similar like Excel
![image](https://user-images.githubusercontent.com/13643455/71905495-8e2e9a00-3168-11ea-8086-88b2aff49ca0.png)

**Comment by mehlichmeyer** [comment]
@weisswurstkanone @brusch I am currently working on this, what do you think? Is the naming as suggested by @ckemptner alright, or do you disagree?

**Comment by weisswurstkanone** [comment]
I am fine with it

**Comment by NiklasBr** [comment]
Good initiative!

Can I make a wish for [natural sorting](http://www.davekoelle.com/alphanum.html) (see also [Sorting for Humans](https://blog.codinghorror.com/sorting-for-humans-natural-sort-order/)? :) 

This works in [JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) and [PHP](https://www.php.net/manual/en/function.natsort.php).

**Comment by mehlichmeyer** [comment]
@NiklasBr Sure thing. Were you thinking for the natural sort to replace the current sort (A to Z) or to have it as an extra sorting option?

**Comment by NiklasBr** [comment]
I'd personally prefer to replace the current.

**Comment by ckemptner** [comment]
@mehlichmeyer thanks for taking the lead here =)

**Comment by judip** [comment]
I noticed that the objects in the tree are not sorted correctly when they start with diacritical characters, for example Ł, Ś etc.
The problem is in the DataObjectController.php file where

`COLLATE utf8_general_ci ASC`

is added to the SQL condition. With COLLATE utf8_unicode_ci works fine.
