### ISSUE TITLE
[IDEA] Revert single language overwrite to master content document

### ISSUE THREAD

**Issue by nwijnNobears** [pimcore/pimcore#5546]
It would be a nice feature if it was possible to revert a single overwrite you made in inherited document.

As use case: A client of ours, made an overwrite on a single image on the page for a special event specific to this language / site. And after this change he also made some textual changes.

A week or so has passed, and the special event has ended. And my client would like to revert back to the original inherited image, but not the textual changes that where made after the image overwrite.

### Code example
Added Context menu item to Image.js in AdminModule ext

        menu.add(new Ext.menu.Item({
            text: t('reset_overwrite'),
            iconCls: "pimcore_icon_overwrite",
            handler: function (item) {
                item.parentMenu.destroy();

                this.resetOverwrite();
            }.bind(this)
        }))

And added the following function.

    resetOverwrite: function () {
        this.inherited = true;
        this.empty();
    },

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
