### ISSUE TITLE
Web Service returns empty objects instead of localized fields nested within a block

### ISSUE THREAD

**Issue by SecretPocketCat** [pimcore/pimcore#5551]
# Bug Report
### Expected behavior
The web service returns the localized values of fields nested within localized values that are nested within a block

![2020-01-08 14_38_08-pimcore westeurope cloudapp azure com __ Pimcore](https://user-images.githubusercontent.com/17273703/71982343-8c2a1100-3224-11ea-9d26-e506b17278c2.png)

### Actual behavior
The localized values returned by the REST API are just empty objects
![2020-01-08 14_36_50-https___pimcore westeurope cloudapp azure com_webservice_rest_object_id_2263_api](https://user-images.githubusercontent.com/17273703/71982282-669d0780-3224-11ea-861b-d57b8170048d.png)

### Steps to reproduce
Create a class with a field nested within localized fields nested within a block.  
Save a new object and request the object by id using the web service.  
![2020-01-08 14_39_33-pimcore westeurope cloudapp azure com __ Pimcore](https://user-images.githubusercontent.com/17273703/71982441-c3002700-3224-11ea-843e-3f9224af3ceb.png)

**Comment by brusch** [comment]
Probably related to #4767

**Comment by brusch** [comment]
Obsolete see #7279
