### ISSUE TITLE
Updating Pimcore from v6.1.2 to 6.3.6 breaks

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#5562]
When updating from Pimcore v6.1.2 to v6.3.6 I got the error message that in a self programmed tag the method isEmpty() is missing. Unfortunately I could not find any hint in the upgrade notes that this method needs to be added.

Is it not possible to add a general method isEmpty() to the class pimcore/model/Document/Tag.php

For Example:
```
    /**
     * @return bool
     */
    public function isEmpty(): bool
    {
        return empty($this->getData());
    }
```

**Comment by brusch** [comment]
A generic method is unfortunately not possible, e.g.
https://github.com/pimcore/pimcore/blob/e38565fd18af2497f8119e447985f74b6932d39e/models/Document/Tag/Numeric.php#L97
or https://github.com/pimcore/pimcore/blob/e38565fd18af2497f8119e447985f74b6932d39e/models/Document/Tag/Areablock.php#L573

But you're right, this info is missing in the upgrade notes for 6.3.0 - thanks for the info!
