### ISSUE TITLE
Error "Failed to start the session" in shutdown procedure

### ISSUE THREAD

**Issue by ContsultGmbH** [pimcore/pimcore#5563]
On a clean installation we see the following error in the log file after clicking on "Magazin" or "Weiteres" in the documents tree. If display_errors is enabled the loading animation keeps rotating and the child elements will never show up.

> pimcore.ERROR: RuntimeException: Failed to start the session because headers have already been sent by "/var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Response.php" at line 1219. in /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php:147 Stack trace: #0 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php(320): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() #1 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Session.php(244): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->getBag('ecommerceframew...') #2 /var/www/pimcore/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/SessionEnvironment.php(124): Symfony\Component\HttpFoundation\Session\Session->getBag('ecommerceframew...') #3 /var/www/pimcore/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/SessionEnvironment.php(62): Pimcore\Bundle\EcommerceFrameworkBundle\SessionEnvironment->getSessionBag() #4 /var/www/pimcore/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/Environment.php(300): Pimcore\Bundle\EcommerceFrameworkBundle\SessionEnvironment->load() #5 /var/www/pimcore/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/IndexService/IndexService.php(320): Pimcore\Bundle\EcommerceFrameworkBundle\Environment->getCurrentAssortmentTenant() #6 /var/www/pimcore/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/IndexService/IndexService.php(198): Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\IndexService->resolveTenantWorker(NULL) #7 /var/www/pimcore/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelectionCombo.php(46): Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\IndexService->getIndexAttributes(true) #8 /var/www/pimcore/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelectionCombo.php(37): Pimcore\Bundle\EcommerceFrameworkBundle\CoreExtensions\ClassDefinition\IndexFieldSelectionCombo->buildOptions() #9 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Helper/VarExport.php(28): Pimcore\Bundle\EcommerceFrameworkBundle\CoreExtensions\ClassDefinition\IndexFieldSelectionCombo->__construct() #10 /var/www/pimcore/var/classes/fieldcollections/OrderByFields.php(61): Pimcore\Model\DataObject\ClassDefinition\Data::__set_state(Array) #11 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/Fieldcollection/Definition.php(268): include('/var/www/pimcor...') #12 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Fieldcollections.php(387): Pimcore\Model\DataObject\Fieldcollection\Definition::getByKey('OrderByFields') #13 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data.php(335): Pimcore\Model\DataObject\ClassDefinition\Data\Fieldcollections->setAllowedTypes(Array) #14 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Helper/VarExport.php(29): Pimcore\Model\DataObject\ClassDefinition\Data->setValues(Array) #15 /var/www/pimcore/var/classes/definition_FilterDefinition.php(242): Pimcore\Model\DataObject\ClassDefinition\Data::__set_state(Array) #16 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition.php(200): include('/var/www/pimcor...') #17 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/Concrete.php(448): Pimcore\Model\DataObject\ClassDefinition::getById('EF_FD') #18 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/Concrete/Dao.php(147): Pimcore\Model\DataObject\Concrete->getClass() #19 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/Concrete/Dao.php(57): Pimcore\Model\DataObject\Concrete\Dao->getData() #20 /var/www/pimcore/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(303): Pimcore\Model\DataObject\Concrete\Dao->getById(696) #21 /var/www/pimcore/vendor/pimcore/pimcore/models/Element/Service.php(443): Pimcore\Model\DataObject\AbstractObject::getById(696, false) #22 /var/www/pimcore/vendor/pimcore/pimcore/models/Document/Tag/Relation.php(175): Pimcore\Model\Element\Service::getElementById('object', 696) #23 /var/www/pimcore/vendor/pimcore/pimcore/models/Document/Tag/Relation.php(144): Pimcore\Model\Document\Tag\Relation->setElement() #24 /var/www/pimcore/vendor/pimcore/pimcore/models/Document/PageSnippet/Dao.php(54): Pimcore\Model\Document\Tag\Relation->setDataFromResource(Array) #25 /var/www/pimcore/vendor/pimcore/pimcore/models/Document/PageSnippet.php(507): Pimcore\Model\Document\PageSnippet\Dao->getElements() #26 /var/www/pimcore/vendor/pimcore/pimcore/models/Document/PageSnippet.php(209): Pimcore\Model\Document\PageSnippet->getElements() #27 /var/www/pimcore/vendor/pimcore/pimcore/models/Document/Link.php(119): Pimcore\Model\Document\PageSnippet->getCacheTags(Array) #28 /var/www/pimcore/vendor/pimcore/pimcore/lib/Cache/Core/CoreHandler.php(482): Pimcore\Model\Document\Link->getCacheTags(Array) #29 /var/www/pimcore/vendor/pimcore/pimcore/lib/Cache/Core/CoreHandler.php(847): Pimcore\Cache\Core\CoreHandler->prepareCacheTags(Object(Pimcore\Cache\Pool\CacheItem), Object(Pimcore\Model\Document\Link), Array) #30 /var/www/pimcore/vendor/pimcore/pimcore/lib/Cache/Core/CoreHandler.php(902): Pimcore\Cache\Core\CoreHandler->writeSaveQueue() #31 /var/www/pimcore/vendor/pimcore/pimcore/lib/Cache.php(202): Pimcore\Cache\Core\CoreHandler->shutdown(false) #32 /var/www/pimcore/vendor/pimcore/pimcore/lib/Pimcore.php(273): Pimcore\Cache::shutdown() #33 /var/www/pimcore/vendor/pimcore/pimcore/lib/Kernel.php(202): Pimcore::shutdown() #34 [internal function]: Pimcore\Kernel->Pimcore\{closure}() #35 {main} [] []

After debugging it came out that the error occurs in the shutdown procedure when Pimcore tries to save the cache queue. Then it tries to determine the current tenant from the current session which has already been closed at that time.

**Comment by PimLab** [comment]
Hey @ContsultGmbH 
can you give information about the system you've installed pimcore on; OS, Version of PHP, etc.? Looks like a problem in filesystem rights.
Best Wishes
Felix

**Comment by brusch** [comment]
Unable to reproduce. 
Maybe really related to your infrastructure? Can you provide a bit more details? Have you checked the system requirements page in Pimcore?
