### ISSUE TITLE
Word / Excel files are not open in pimcore

### ISSUE THREAD

**Issue by jimeshm** [pimcore/pimcore#5566]
Hi,

I install latest version of Pimcore.
OS - Ubuntu 18.04
DB - MYSQL

also install libreoffice using below commands. 

sudo apt-get install libreoffice libreoffice-script-provider-python libreoffice-math xfonts-75dpi poppler-utils inkscape libxrender1 libfontconfig1 ghostscript

but documents are not open in pimcore

**Comment by jimeshm** [comment]
Installation done as per below link guideline.

https://websiteforstudents.com/install-pimcore-cms-on-ubuntu-16-04-17-10-18-04-with-apache2-mariadb-php-7-1-and-lets-encrypt-ssl-tls-certificates/

**Comment by msphn** [comment]
@jimeshm Pimcore does not open documents for editing but generates previews of those documents. Correct me if I'm wrong. Are you trying to preview the document or are you trying to edit it?

**Comment by jimeshm** [comment]
@msphn for priview

**Comment by msphn** [comment]
Is it shown green in the requirements list and are asset previews enabled?

**Comment by jimeshm** [comment]
It's shown green in the requirements. how to check asset previews are enabled or not?

![image](https://user-images.githubusercontent.com/55339122/72146351-3f7c3c80-33c2-11ea-9325-d6395868ca53.png)

**Comment by brusch** [comment]
@jimeshm Previews are generated asynchronously, please ensure your maintenance task is running correctly. See also #3974
