### ISSUE TITLE
[Data objects] Thumbnail transformations for images in wysiwyg fields

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#5574]
You can insert Pimcore assets via drag and drop to wysiwyg fields of data objects. It would be nice if one could enter a thumbnail definition so you could get responsive images / image effects etc.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
