### ISSUE TITLE
[Data Object] Custom URL-Slug for Data Objects

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#5575]
## URL-Slug Data-Type
- basically like the input data-type
- client-side regex validation for valid URL path-info (starting with a `/`) 
- server-side validation against existing document URLs (incl. pretty URLs)  and object URLs
- storage is a central `object_url_slugs` table (needed for lookup)
- support for localized fields
- support for sites
- in config: controller/action to be called (incl. services) e.g. `AppBundle\Controller\NewsController::detailAction`

## Router for Object URL Slugs
See also: 
https://symfony.com/doc/current/routing/routing_from_database.html
and
existing Pimcore implementation for dynamic routing used by documents: 
https://github.com/pimcore/pimcore/blob/4c986d60d890898e466533a21dfd29bde2acb9f6/lib/Routing/DynamicRouteProvider.php
https://github.com/pimcore/pimcore/blob/947e4b62e48610bb71615e39d937a3e67287258f/lib/Routing/Dynamic/DocumentRouteHandler.php
...

- the context should be available on the request, like, object, fieldname, locale (if within LF), ...

**Comment by solverat** [comment]
@brusch! YES! Also consider some uniqueness, so we could get rid of ids in URLs for example.

- instead of `news/my-entry-12` it should be possible to fetch `news/my-entry`
- but also `blog/my-entry` should be possible

Maybe there should be a "regex unique validation" per route? Available in a pre-save event?

**Comment by solverat** [comment]
second thought: if there is a lookup table and the full path will be stored, a unique key for `path` on db side should be enough?

**Comment by dpfaffenbauer** [comment]
Also: One object could have multiple routes!

**Comment by brusch** [comment]
@solverat of course, see 
> server-side validation against existing document URLs (incl. pretty URLs) **and object URLs**

@dpfaffenbauer that's why I think a data-type is the best solution, you can then  do whatever you want

**Comment by dpfaffenbauer** [comment]
so the data-type value gets stored into a central table?

**Comment by brusch** [comment]
Yes, at least this was my first idea 😉 
In my opinion this would make sense, otherwise the lookup for routing and validation would be very complicated and slow. Since every data-type can decide on it's own how it get's saved, this should be also the easiest solution. Do you have any concerns about that?

**Comment by solverat** [comment]
There is already the object table. Extend it with a „slug“ row could do the job?

**Comment by dpfaffenbauer** [comment]
@solverat still could work, if it is a data-type, it just persists itself into the object table. But, I think having a separate table for it will make it work faster, since you can have special indicies for querying that table.

@brusch no, not at all. Also think about multi-site here. With Static Routes I have the possibility to let a route only resolve for a certain site. It should also be possible to use the slug type within localized fields, so one entry for every language then.

**Comment by brusch** [comment]
@dpfaffenbauer sure, see above. 
> support for localized fields

Multi-site: good point! 👍(added to the list above)

**Comment by markus-moser** [comment]
Maybe we could think about creating (301) redirects when the slug changes too?

**Comment by brusch** [comment]
Yep, but in a later stage :)

**Comment by weisswurstkanone** [comment]
datahub: https://github.com/pimcore/data-hub/issues/157

**Comment by kovinet** [comment]
I have url pattern for news like 

/en/news/news-1-slug
/de/news/news-1-slug 

how could I implement this, without clients needing to enter whole slug but only the last part ("/news-1-slug") ?

**Comment by dpfaffenbauer** [comment]
@kovinet this can help you: https://docs.coreshop.org/4.0.0/CoreShop/Bundles/Pimcore_Bundle#slug

**Comment by kovinet** [comment]
Thanks @dpfaffenbauer - I now generate slugs with EventListener and set them there, which works fine.  

What would be recommended way to generate URLs in this case? Before I was using `{{ path('news', {'id': item.id}) }}` and now I am using `{{ item.slug[0].slug }}` but I am not sure this is the best way. Documentation is a bit lacking on this.

**Comment by dpfaffenbauer** [comment]
@kovinet CoreShop has a solution for this as well ;) Just added it to the docs: https://docs.coreshop.org/4.0.0/CoreShop/Bundles/Pimcore_Bundle/index.html#pimcore-link-generation (docs are cached on edge, so you might need to reload with disabled cache or wait some time to see it).
