### ISSUE TITLE
Fields created not visible for any language in classification store

### ISSUE THREAD

**Issue by amarjeet6694** [pimcore/pimcore#5580]
**Steps to Reproduce**

1. Create a new classification store with few input fields.
2. Map the classification store and make it localized and map it to a class
3. Create a new object for that and add classification store data.
4. After adding fields under Default tab, verify data under other languages, but fields are not populated for other languages.

_But if you save n publish the object, then after reload fields are visible under all languages._

**Comment by weisswurstkanone** [comment]
Why would expect that other languages are populated without saving the object?

**Comment by amarjeet6694** [comment]
@weisswurstkanone but even if I move to any of the language tab and click the plus icon to add classification store fields, the fields are added only in the Default tab of the store and not in the corresponding language tab when I added them.

Actually in our project, we have removed the Default tab and shown only the language tabs and we are populating the fields in the store dynamically (after selecting a category field) but the fields are populated in the first tab only. It is only after save and reload, we are able to view fields for other languages.

**Comment by weisswurstkanone** [comment]
What does "...Actually in our project, we have removed the Default tab and shown only the language tabs..." mean ?

Above you say (point 4) that you are adding fields "under Default tab"

**Comment by weisswurstkanone** [comment]
@amarjeet6694  ping

**Comment by weisswurstkanone** [comment]
@amarjeet6694 ping, last reminder :-)

**Comment by dvesh3** [comment]
- Issue occurs when you add fields by Key/Group Search window to a tab then other language tabs are not populated with new fields. 
- User has to save and reload the object to populate fields to all tabs.
