### ISSUE TITLE
copy ID to clipboard

### ISSUE THREAD

**Issue by chrishaindl** [pimcore/pimcore#5589]
would be nice to have the option to copy IDs of documents/assets/objects directly to the clipboard instead of manually mark and copy it

![clipboard](https://user-images.githubusercontent.com/58854428/72426509-1ffe5e80-378a-11ea-8918-095de83dc5df.png)

**Comment by dvesh3** [comment]
already there
![image](https://user-images.githubusercontent.com/5137917/72426701-897e6d00-378a-11ea-8ae2-8ca7f9735663.png)

**Comment by weisswurstkanone** [comment]
see https://github.com/pimcore/pimcore/commit/0610911e429392b58ad46d6b6758378d37837d37
