### ISSUE TITLE
show dependencies of CustomerSegments

### ISSUE THREAD

**Issue by chrishaindl** [pimcore/pimcore#5593]
When an object is somehow used on a doument, you can see the relation in the tab "dependencies".
If CustomerSegments are used on documents, dependencies on the CustomerSegment-object are **not** visible even though the respective CustomerSegment is in use.

![dependencies](https://user-images.githubusercontent.com/58854428/72429005-30fd9e80-378f-11ea-8f14-53c4ea1cf0bd.png)

**Comment by fashxp** [comment]
not a pimcore issue, --> see https://github.com/pimcore/customer-data-framework/issues/148
