### ISSUE TITLE
my vendor/pimcore/pimcore is broken, can any help me? iam using pimcore 6

### ISSUE THREAD

**Issue by tohaindra** [pimcore/pimcore#5601]
![image](https://user-images.githubusercontent.com/46700122/72589510-1150ac80-392e-11ea-90ac-2c54891d54d4.png)

error after iam update composer.json in vendor/pimcore/pimcore

**Comment by brusch** [comment]
https://talk.pimcore.org/
http://gitter.im/pimcore/pimcore
