### ISSUE TITLE
[DataObject] Preview Relation changes not possible from session

### ISSUE THREAD

**Issue by daves-weblab** [pimcore/pimcore#5602]
# Bug Report
When implementing the data object preview to use the object from the session "object_{id}" it is possible to actually preview the data currently in the object without saving the object.

### Expected behavior
Changing any value on the object should be visible in the object preview.

### Actual behavior
Single and multi relations are not stored in the session due to lazy loading and are blocked from being serialized in the session --> not possible to get these changes in the preview.

### Steps to reproduce
Create a preview controller which uses the object from the session to render the preview view.

### Code example
```php
$key = "object_{$id}";

$session = Session::getReadOnly('pimcore_objects');

if (!$session->has($key)) {
   return new Response("Preview not available, it seems that there's a problem with this object.");
}

$object = $session->get($key);
```

### Possible Solution
Maybe the logic from the data object controller which stores the data which is send via /save?task=session could be extracted and used in a seperate preview controller. If the preview would not use redirects inbetween and immediately render the object, storing to the session would not be necessary at all. 

So maybe a new PreviewService configurable in the class would be a neat solution which provides the necessary bootstrap logic for rendering the object.

This way it could also be possible to render multisite / multilingual previews and let the generator decide based on different params (eg. site / language selects in the preview tab).

```php
class PreviewController extends AdminController
{
   public function previewDataObjectAction(Request $request) 
      {
         # logic from DataObjectController:saveAction() without saving
         # this way the $object is 1:1 what is currently in the editmode

         if ($generator = $object->getClass()->getPreviewGenerator()) {
            # generator decides which template to render and which params to pass to it
            return new Response($generator->render($request, $object, ...));
         }

         return new Response("Preview is not configured for this object");
   }
}
```

**Comment by weisswurstkanone** [comment]
already fixed by https://github.com/pimcore/pimcore/issues/5106

**Comment by weisswurstkanone** [comment]
In addition: Use the API provided by Element\Service for accessing the session data instead of relying on the actual implementation.
