### ISSUE TITLE
[Recycle Bin] Show warning if item is too big for the recycle bin

### ISSUE THREAD

**Issue by dweichselbaum** [pimcore/pimcore#5603]
### Problem Summary
When a folder containing more than 100 child items is deleted, they are not moved to the recycle bin but permanently deleted. The user is not notified of this at present. 

### Solution Concept
In this case, the user should have to confirm the deletion process again, with a note like:
"You are about to delete more than 100 files. These cannot be moved to the Recycle Bin but will be deleted permanently. Would you like to continue?"

**Comment by weisswurstkanone** [comment]
You don't see this warning ?

![image](https://user-images.githubusercontent.com/6142086/72611225-d187c600-3929-11ea-8da0-d82e389dd016.png)

**Comment by weisswurstkanone** [comment]
changed wording
