### ISSUE TITLE
pimcore behind reverse proxy

### ISSUE THREAD

**Issue by r4a5a88** [pimcore/pimcore#5617]
# Bug Report

I installed pimcore behind an apache reverse proxy, according to the instructions on the pimcore homepage

### Expected behavior
Some minor problems but fixable if you can add a proxy parameter

### Actual behavior
Due to rewrites everything is rewritten onto the main / 

### Steps to reproduce
Install pimcore according to the install instructions on a debian 10 with php 7.3 machine behind an apache2 reverse proxy
### Code example
My apache and proxy conf

DocumentRoot /var/www/pimcore/web

SetEnvIfNoCase Request_URI "\.(php)$" no-gzip dont-vary

AddHandler php7.3 .php
Action php7.3 /php7.3
Alias /php7.3 /usr/lib/cgi-bin/php7.3

<Directory /usr/lib/cgi-bin>
    Options ExecCGI FollowSymLinks
    SetHandler fastcgi-script
    Require all granted
</Directory>
<Location /var/www/pimcore/web/>
Options FollowSymLinks
Require all granted
AllowOverride all
</Location>

This is the apche conf on the proxy

    Define VPATH /pimcore
    Define DS_ADDRESS IP adress

    Alias heicumedia ${VPATH}
    ProxyPass ${VPATH} “http:// ${DS_ADDRESS}”
    ProxyPassReverse ${VPATH} “http:/ /${DS_ADDRESS}”

    <Location ${VPATH}>
    ProxyPreserveHost On
    Require all granted
    SetEnvIf Host "^(.)$" THE_HOST=$1
    RequestHeader setifempty X-Forwarded-Proto https
    RequestHeader setifempty X-Forwarded-Host %{THE_HOST}e
    #caused header error after login on e.g. Chrome, mobile Browsers, etc.
    #RequestHeader edit X-Forwarded-Host (.) $1${VPATH}
    ProxyAddHeaders ON

# Feature Request

Please add a feature for reverse proxy usage such as a prameter in a conf file

**Comment by brusch** [comment]
https://talk.pimcore.org/
http://gitter.im/pimcore/pimcore

**Comment by r4a5a88** [comment]
I did post it there.
https://talk.pimcore.org/t/pimcore-behind-apache-reverse-proxy/3111
