### ISSUE TITLE
[Bug] Pimcore\Model\Element\AdminStyle throws PHP Error when having sites in project

### ISSUE THREAD

**Issue by AlexanderHeidrich** [pimcore/pimcore#5618]
# Bug Report
### Expected behavior
The admin interface can be opened.

### Actual behavior
The Pimcore Backend shows a popup with the PHP-Error: 
```
Argument 2 passed to Pimcore\Translation\Translator::trans() must be of the type array, string given, called in /php/vendor/pimcore/pimcore/models/Element/AdminStyle.php on line 99

Server threw exception - could not perform action. Please reload the admin interface and try again.
```
Therefor, no trees or Settings can be accessed.

### Steps to reproduce
See `pimcore/pimcore/models/Element/AdminStyle.php:99` where the second parameter for the `Translator::trans()` method is still a string and not an array.
This seems to happen especially if you use Pimcore Sites in your project.

### Code example
```php
if ($site instanceof Model\Site) {
    $translator = \Pimcore::getContainer()->get("pimcore.translator");
    $this->elementQtipConfig['text'] .= '<br>' . $translator->trans('site_id', 'admin') . ': ' . $site->getId();
}
```

**Comment by blankse** [comment]
I created a PR with an fix

**Comment by brusch** [comment]
@blankse thanks a lot!
