### ISSUE TITLE
Adding custom HTML to option labels is leading to unexpected behaviour: The selected option is shown wrong (escaped) while it works for the options

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#5626]
# Bug Report

### Expected behavior
Add basic HTML to `pimcore_select()` labels in Twig. 

### Actual behavior
All options are displayed correctly and show the interpreted HTML, but the selected option is escaped and shows the escaped HTML instead.

![select_bug](https://user-images.githubusercontent.com/1703552/72824773-256e1400-3c76-11ea-8bc6-190520d9bf34.png)

### Steps to reproduce
Just create e.g. a view for any Areabrick and put a  `pimcore_select()` with labels containing HTML inside.

### Code example

```
{{ pimcore_select('colorSel', {
    store: [
              ["blue","<span style='color:blue;width:10px;height:10px;display:inline-block;'></span> Blue"],
              ["red","<span style='color:red;width:10px;height:10px;display:inline-block;'></span> Red"],
     ],
    reload: true,
    width: 130
}) }}
```

Because I heard a demand for HTML within the select options from multiple customers it would be awesome if you do not disallow HTML in selectors but make it display correctly within selected options instead 😎

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
