### ISSUE TITLE
AWS S3 integration issue in download assets zip file

### ISSUE THREAD

**Issue by kudeepak** [pimcore/pimcore#5628]
# Bug Report

### Expected behavior
Image should be douwnload by clicking button "Download selected items as ZIP" under assets listing. 
### Actual behavior
It is giving 500 internal server error.
### Steps to reproduce
-> Go in assets
-> Click on list
-> Select checkbox 
-> Click "Download selected items as ZIP"

### Code example
```php
// your code
```

# Feature Request

**Comment by brusch** [comment]
Please provide the full error message incl. the stack trace, otherwise we're not able to help. You should find this information in your log files.

**Comment by kudeepak** [comment]
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.


The file "/var/www/fssqa.joyousminds.com/pmifss01/var/tmp/download-zip-5e27e6b4688e2.zip" does not exist


in vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/File/File.php (line 36)

**Comment by kudeepak** [comment]
It is a path issue. But we have this path and that one is writable as well. Then why this error is coming. 
We are using Pimcore 6. Also we followed all the steps of Pimcore 6 to integrate the S3.

**Comment by brusch** [comment]
You don't have a stack trace? 
Would be nice if you could fix that and provide us a PR as we don't have a dev-system with S3 ready. 
Should be quite easy, just have a look at this action: 
https://github.com/pimcore/pimcore/blob/ca75246d82fe1190ce2268767ace84f157b168d9/bundles/AdminBundle/Controller/Admin/AssetController.php#L1766

Btw. `PIMCORE_SYSTEM_TEMP_DIRECTORY` shouldn't be on S3 ... if that's the case, change it to a local path.

**Comment by kudeepak** [comment]
Thanks Brusch, Will look as per your suggestion. 
As you hint will check in that direction.

I will update in this ticket only.

**Comment by kudeepak** [comment]
Hi Brusch,
Just after updating the Line no 1880 of file   
`pimcore/bundles/AdminBundle/Controller/Admin/AssetController.php

`$zip->addFile($a->getFileSystemPath(), preg_replace('@^' . preg_quote($asset->getRealPath(), '@') . '@i', '', $a->getRealFullPath()));`
with 
`$zip->addFromString(preg_replace('@^' . preg_quote($asset->getRealPath(), '@') . '@i', '', $a->getRealFullPath()), file_get_contents($a->getFileSystemPath()));`
It is getting downloaded.
But it is lib change will take care needed at the time of deployment.
