### ISSUE TITLE
[Workflow] Workflow broken since 6.4.1 when using Symfony 3.4

### ISSUE THREAD

**Issue by MVermue** [pimcore/pimcore#5635]
### Expected behavior
`php bin/console pimcore:workflow:dump <workflowname>` doesn't throw an error

### Actual behavior
`php bin/console pimcore:workflow:dump <workflowname>` throws an error

```
In Definition.php line 76:
                                                             
  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Warning: Illegal offset type in isset or empty             
                                                             

Exception trace:
  at /phpapp/vendor/symfony/symfony/src/Symfony/Component/Workflow/Definition.php:76
 Symfony\Component\Workflow\Definition->setInitialPlace() at /phpapp/vendor/symfony/symfony/src/Symfony/Component/Workflow/Definition.php:43
 Symfony\Component\Workflow\Definition->__construct() at /phpapp/var/cache/dev/ContainerM7ngjmc/getStateMachine_VvsgApprovalWorkflowService.php:20
 require() at /phpapp/var/cache/dev/ContainerM7ngjmc/appDevDebugProjectContainer.php:3754
 ContainerM7ngjmc\appDevDebugProjectContainer->load() at /phpapp/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:304
 Symfony\Component\DependencyInjection\Container->get() at /phpapp/vendor/pimcore/pimcore/bundles/CoreBundle/Command/WorkflowDumpCommand.php:60
 Pimcore\Bundle\CoreBundle\Command\WorkflowDumpCommand->execute() at /phpapp/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /phpapp/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:1001
 Symfony\Component\Console\Application->doRunCommand() at /phpapp/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /phpapp/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /phpapp/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /phpapp/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at /phpapp/bin/console:26
```

### Steps to reproduce
* Use symfony 3.4, pimcore 6.4.1 (or higher) and workflow configuration uses `initial_place`
* Symfony now throws an error at https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Workflow/Definition.php#L76

I assume the issue has been introduced in https://github.com/pimcore/pimcore/commit/aa016066ba4a6643940f190de10af48a13194d9c though I haven't tested it to be sure. The issue is not present in pimcore 6.4.0. It now ignores the `initial_place` I set in my config and now passes the `initial_markings` empty array from the above commit which symfony 3.4 does not understand

I assume I'd be able to fix this in my project by upgrading it to symfony 4+

**Comment by brusch** [comment]
@MVermue there would be a check here: 
https://github.com/pimcore/pimcore/pull/5541/files#diff-6d018d80bd480f46d56fd20f73d16138R126

Doesn't that work for you? 
Is `initial_markings` set in your case? If yes, what's the value? 

Thanks for the info!

**Comment by brusch** [comment]
Ah, I see `initial_markings: {  }` is set with an empty array.
