### ISSUE TITLE
[Bug] (Reverse) ManyToManyRelation tables stuck in refresh loop

### ISSUE THREAD

**Issue by Shobba** [pimcore/pimcore#5644]
# Bug Report

### Expected behavior
(Reverse) ManyToManyRelation tables only refresh data once on opening DataObject in Pimcore admin and won't get stuck in a loop.

### Actual behavior
Commit https://github.com/pimcore/pimcore/commit/515c27c2b1f42b66f3b6e4fa1eeecd2d83cf853e (fixed another issue) introduced a problem which puts the relation table in a refresh loop. Often this is not visible in the UI, you can just sometimes see the icons on the right flickering (for example after you open the browser dev tools).
It's more problematic if you have a formatter on this table. Then the table will keep blinking white & blue because after refreshing the table data it will request the nice path.

![pimcore-bug](https://user-images.githubusercontent.com/2971787/72906864-2f098180-3d33-11ea-81db-63bc183b3bed.gif)

### Steps to reproduce
1. Create a class that has a ManyToMany or Reverse-ManyToMany relation.
2. Add a Formatter service/class to that data component.
3. Create an object with this class and add some relations.
4. Enjoy the blue/white party lights :)

**Comment by StephenBeirlaen** [comment]
We can also confirm this problem.

Not sure if this issue is relevant to a secondary issue, but when clicking on "search" in a reverse many-to-many relation, the dialog opens with incomplete columns:
![image](https://user-images.githubusercontent.com/11806615/73860835-71a38180-483c-11ea-9a2a-df31108c1a4d.png)
