### ISSUE TITLE
[Asset] Open new created Folder automatically

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#5660]
Open a new created Folder automatically, is's hard to find the Folder when you have a huge amount of folders in your tree

**Comment by brusch** [comment]
Hmm, I got your point, but wouldn't that be very annoying in other cases like when creating an initial folder-structure, or in general when creating many folders in batch?

**Comment by putzflorian** [comment]
maybe in this case yes.

**Comment by brusch** [comment]
So'll close this issue for now as this seems to be rather an edge case. If anyone has a creative idea how to solve that issue, please feel free to provide a PR or continue the discussion here. Thanks a lot! 😊
