### ISSUE TITLE
Thumbnails of large PDF documents can not be created 

### ISSUE THREAD

**Issue by vuorijv** [pimcore/pimcore#5667]
### Expected behavior
When uploading a PDFa thumbnail is shown on DAM and related image thumbnails are created when necessary.

### Actual behavior
Upload a PDF and no thumbnail is shown on DAM (instead the filetype-not-supported.svg is shown). The same happends when trying to access via code the related image thumbnails defined in the "Settings" -> "Thumbnails" -> "Image Thumbnails". 

### Steps to reproduce
Upload large PDF asset to DAM. Attached one example file 
[47150_NordicTurf_lakana_4800x2800.pdf](https://github.com/pimcore/pimcore/files/4108668/47150_NordicTurf_lakana_4800x2800.pdf)

Looks like it is somehow related to the Imagick php library's readImage -function limitations.

**Comment by brusch** [comment]
Worked fine for me, probably related to your environment. 

Tested with code: 
```php
    /**
     * @Route("/bernie/test")
     */
    public function testAction(Request $request) {

        $asset = Asset::getById(410);
        $foo = $asset->getImageThumbnail('exampleCover');
        dump($foo->getFileSystemPath());
        exit;
    }
```

Result: 
![image](https://user-images.githubusercontent.com/142037/73955457-b21a0280-4903-11ea-8287-7863c55fe3ba.png)

**Comment by vuorijv** [comment]
Thanks for taking a look at this. 
We are running Pimcore 6.4.2  on Debian with PHP 7.3.9, Ghostscript 9.27 and ImageMagick 6.9.10
In php.ini memory_limit = 512M

Anything that differs heavily on your test environments settings? 

Our logs are filled with the following messages: 

> 08:20:08 ERROR [pimcore] Unable to load image: /data/dam_storage/tmp/document-image-cache/document_1682__thumbnail_1.png
08:20:08 ERROR [pimcore] ImagickException: Failed to read the file in /var/www/dam/vendor/pimcore/pimcore/lib/Image/Adapter/Imagick.php:120

And when taking look at the initial thumbnail (/data/dam_storage/tmp/document-image-cache/document_1682__thumbnail_1.png) generated py GhostSrcipt it does exist and the size of it seems to be very huge like over 30MB.

**Comment by brusch** [comment]
@vuorijv my tests were using `memory_limit = 256M`.

**Comment by vuorijv** [comment]
What was the size of the initial GS generated thumb that the Imagick is trying to read? 

I am trying to get the idea why it is failing on our prod and dev environments.

**Comment by brusch** [comment]
@vuorijv `document_410__thumbnail_1.png` = `32M` so similar to yours.

**Comment by vuorijv** [comment]
Do you see anything significantly different on those versions on our system vs your test setup? Or anything else that could affect to that?

**Comment by brusch** [comment]
Not that I can think of :| You can do some further testing also with our Docker images: https://github.com/pimcore/docker

**Comment by vuorijv** [comment]
@brusch Thank you for your help. Was about to ask if that test environment is shareable... Will check those.
