### ISSUE TITLE
permissions are not considered in folder object grid

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#567]
user can see objects he must not see. 

to reproduce see screenshots: 
![image](https://cloud.githubusercontent.com/assets/8792145/14766516/bfed1e44-0a0d-11e6-9f35-e363d24cf636.png)

![image](https://cloud.githubusercontent.com/assets/8792145/14766518/d45b711e-0a0d-11e6-9ba0-40461df92796.png)

**Comment by weisswurstkanone** [comment]
fixed in build 3758
