### ISSUE TITLE
Select/Multiselect default value: take options provider class into account

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#5673]

**Comment by brusch** [comment]
Resolved by #5676

**Comment by NikitaKharkov** [comment]
Guys, is really this problem resolved? I don't see the option to setup default options for multiple select. Only for **SelectOptionsProviderInterface** I see **getDefaultValue**, and there is no for **MultiSelectOptionsProviderInterface**.

My case is I have 20 categories and most of the values should contain all of them, and only some of them 2-3. I do need to setup all of them to be pre-selected, but I cannot do it...

Any existed suggestion?

**Comment by mohammed-mahmoud-scandi** [comment]
updates @brusch @weisswurstkanone ....

**Comment by dvesh3** [comment]
please start a discussion here https://github.com/pimcore/pimcore/discussions as you have the possibility to get answers from the community not just core devs.
