### ISSUE TITLE
[DataObjects] Recheck indices on relations table

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#5687]
- check if all index are necessary
- eventually use compound index 

--> reduce update/insert costs, reduce memory consumption for index

**Comment by weisswurstkanone** [comment]
Without relations cache:

| Scenario |           Owner           | src_id<br>(int) | dest_id<br>(int) | type<br>(varchar) | fieldname<br>(varchar) | index<br>(int) | ownertype<br>(enum) | ownername<br>(varchar) | position<br>(varchar) |
|:--------:|:-------------------------:|:---------------:|:----------------:|:-----------------:|:----------------------:|:--------------:|:-------------------:|:----------------------:|:---------------------:|
|  select  |           object          |        X        |                  |                   |            X           |                |          X          |                        |                       |
|  delete  |           object          |        X        |                  |                   |                        |                |          X          |                        |                       |
|  select  |      object localized     |        X        |                  |                   |            X           |                |          X          |                        |           X           |
|  delete  |      object localized     |        X        |                  |                   |                        |                |          X          |            X           |           X           |
|  select  |        objectbrick        |        X        |                  |                   |            X           |                |          X          |            X           |           X           |
|  delete  |        objectbrick        |        X        |                  |                   |                        |                |          X          |            X           |           X           |
|  select  |      fieldcollection      |        X        |                  |                   |            X           |                |          X          |            X           |           X           |
|  delete  |      fieldcollection      |        X        |                  |                   |                        |                |          X          |          LIKE          |                       |
|  select  | fieldcollection localized |        X        |                  |                   |            X           |                |          X          |          LIKE          |           X           |
|  delete  | fieldcollection localized |        X        |                  |                   |                        |                |          X          |          LIKE          |                       |
|  select  |   objectbrick localized   |        X        |                  |                   |            X           |                |          X          |          LIKE          |           X           |
|  delete  |   objectbrick localized   |        X        |                  |                   |                        |                |          X          |          LIKE          |           X           |

**Comment by weisswurstkanone** [comment]
With raw relations cache:

| Scenario |           Owner           | src_id<br>(int) | dest_id<br>(int) | type<br>(varchar) | fieldname<br>(varchar) | index<br>(int) | ownertype<br>(enum) | ownername<br>(varchar) | position<br>(varchar) |
|:--------:|:-------------------------:|:---------------:|:----------------:|:-----------------:|:----------------------:|:--------------:|:-------------------:|:----------------------:|:---------------------:|
|  select  |           object          |        X        |                  |                   |                        |                |                     |                        |                       |
|  delete  |           object          |        X        |                  |                   |                        |                |          X          |                        |                       |
|  select  |      object localized     |        X        |                  |                   |                        |                |                     |                        |                       |
|  delete  |      object localized     |        X        |                  |                   |                        |                |          X          |            X           |           X           |
|  select  |        objectbrick        |        X        |                  |                   |                        |                |                     |                        |                       |
|  delete  |        objectbrick        |        X        |                  |                   |                        |                |          X          |            X           |           X           |
|  select  |      fieldcollection      |        X        |                  |                   |                        |                |                     |                        |                       |
|  delete  |      fieldcollection      |        X        |                  |                   |                        |                |          X          |          LIKE          |                       |
|  select  | fieldcollection localized |        X        |                  |                   |                        |                |                     |                        |                       |
|  delete  | fieldcollection localized |        X        |                  |                   |                        |                |          X          |          LIKE          |                       |
|  select  |   objectbrick localized   |        X        |                  |                   |                        |                |                     |                        |                       |
|  delete  |   objectbrick localized   |        X        |                  |                   |                        |                |          X          |          LIKE          |                       |

**Comment by brusch** [comment]
Only relation cache is relevant anymore, see #5757 
If I see it correctly, we should be good with one single composite index: `INDEX name (src_id, ownertype, ownername, position)`.  We have then of course consider the right order in the code. I also don't think we still need the `PRIMARY` index ...

**Comment by brusch** [comment]
Additonally we should already consider the ReverseManyToMany Getter feature: #4262 
So we should add another composite index for the reverse lookup: `INDEX reverse_lookup (dest_id, fieldname)`
