### ISSUE TITLE
[DataObject][Geo Datatypes] Add possibility to use Spatial Datatypes on Database

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#5688]
see https://dev.mysql.com/doc/refman/5.7/en/spatial-type-overview.html

**Comment by mrpdean** [comment]
This would indeed be a useful feature.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
