### ISSUE TITLE
[Thumbnails] Check introduction of Client Hints

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#5692]
to reduce markup size for thumbnails

**Comment by brusch** [comment]
https://developers.google.com/web/updates/2015/09/automating-resource-selection-with-client-hints

Not yet supported across all major browsers, so no option yet. 
https://caniuse.com/#feat=client-hints-dpr-width-viewport

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
