### ISSUE TITLE
[DataObjects] layout jumps back to top

### ISSUE THREAD

**Issue by dpfahlbusch** [pimcore/pimcore#5697]
# Expected behavior
It's possible to scroll down

### Actual behavior
If you open for example a OnlineShopOrder object and expand the "System Informations"-tab and you try to scroll down, the layout jumps back

### Steps to reproduce
Go to https://demo.pimcore.fun/admin
Open OnlineShopOrder object and expand the "System Informations"-tab and try to scroll down

Pimcore Version: dev-master

**Comment by weisswurstkanone** [comment]
TODO: check https://github.com/pimcore/pimcore/commit/515c27c2b1f42b66f3b6e4fa1eeecd2d83cf853e

**Comment by weisswurstkanone** [comment]
Which "System Informations" Tab ? Was there a layout change maybe?

**Comment by dpfahlbusch** [comment]
It's the last field set in the "General Information" tab of the OnlineShopOrder.
But it's only as an example. The jump back seems to be happening on every "larger" layout.

**Comment by weisswurstkanone** [comment]
sorry, then I am not able to reproduce this

**Comment by dpfahlbusch** [comment]
Seems to be fixed in current version ... could swear in version 6.4.x it jumped back
