### ISSUE TITLE
Hardlink Wrapper getChildren() not working

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#5706]
The `getChildren()`method in the Hardlink Wrapper Class is broken. I guess it happened within this PR: https://github.com/pimcore/pimcore/pull/5550

It took me some hours - it's pretty hidden and easy to miss. Instead of:

https://github.com/pimcore/pimcore/blob/96b7073e4b2af122b254923c7ebf3e9b3ba06b44/models/Document/Hardlink/Wrapper.php#L128-L149

The method also needs to respect the cache key, right?

```php
public function getChildren($unpublished = false)
    {
        $children = [];
        $cacheKey = $this->getListingCacheKey();
        if (!isset($this->children[$cacheKey])) {
            $hardLink = $this->getHardLinkSource();

            if ($hardLink->getChildrenFromSource() && $hardLink->getSourceDocument() && !\Pimcore::inAdmin()) {
                foreach (parent::getChildren() as $c) {
                    $c = Service::wrap($c);
                    if ($c instanceof Document\Hardlink\Wrapper\WrapperInterface) {
                        $c->setHardLinkSource($hardLink);
                        $c->setPath(preg_replace('@^' . preg_quote($hardLink->getSourceDocument()->getRealFullpath(), '@') . '@', $hardLink->getRealFullpath(), $c->getRealPath()));

                        $children[] = $c;
                    }
                }
            }

            $this->setChildren($children);
        }

        return $this->children[$cacheKey];
    }
```

There should be some hardlink tests too. Our i18n bundle tests are failing so at least there is some coverage. :)

**Comment by dvesh3** [comment]
Hey @solverat you are right, hardlink `getChildren()` method should respect the cache key. Can you please check if these changes fix your problem? https://github.com/pimcore/pimcore/pull/5712/commits/d980e1bf8b359257d679ec5c969102eff602388c
