### ISSUE TITLE
[Bugreport] empty tables in class layouts produce unreported error 

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#5713]
# Bug Report

**Pimcore 6.4.2**
 **Php 7.4.0**

Saving an object which has a `table` field in the class definition with no data assigned to the table results in the following error:
 
`[2020-02-04 13:17:03] pimcore.WARNING: ErrorException: Warning: Invalid argument supplied for foreach() in /home/gabor/www/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Table.php:331 Stack trace: #0 /home/gabor/www/vendor/pimcore/pimcore/models/DataObject/Concrete/Dao.php(170): Pimcore\Model\DataObject\ClassDefinition\Data\Table->getDataFromResource('N;', Object(AppBundle\Entity\DataObject\SiteConfig)) #1 /home/gabor/www/vendor/pimcore/pimcore/models/DataObject/Concrete/Dao.php(57): Pimcore\Model\DataObject\Concrete\Dao->getData() #2 /home/gabor/www/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(293): Pimcore\Model\DataObject\Concrete\Dao->getById(6) #3 /home/gabor/www/vendor/pimcore/pimcore/models/Element/Service.php(450): Pimcore\Model\DataObject\AbstractObject::getById(6, false) #4 /home/gabor/www/vendor/pimcore/pimcore/models/Element/Editlock/Dao.php(44): Pimcore\Model\Element\Service::getElementById('object', '6') #5 /home/gabor/www/vendor/pimcore/pimcore/models/Element/Editlock.php(95): Pimcore\Model\Element\Editlock\Dao->getByElement('6', 'object') #6 /home/gabor/www/vendor/pimcore/pimcore/models/Element/Editlock.php(153): Pimcore\Model\Element\Editlock::getByElement('6', 'object') #7 /home/gabor/www/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/ElementController.php(59): Pimcore\Model\Element\Editlock::unlock('6', 'object') #8 /home/gabor/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(146): Pimcore\Bundle\AdminBundle\Controller\Admin\ElementController->unlockElementAction(Object(Symfony\Component\HttpFoundation\Request)) #9 /home/gabor/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /home/gabor/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /home/gabor/www/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 {main} [] []`

When saving the object in the Pimcore interface it does not display any error, but all data in fields which are defined after the table in the class layout is lost. Pimcore interprets the error as a warning as far as I can see.
 
![image](https://user-images.githubusercontent.com/9052094/73749483-c6230000-475b-11ea-8b92-358804092d77.png)
![image](https://user-images.githubusercontent.com/9052094/73749490-ca4f1d80-475b-11ea-9222-7b933f76ad06.png)

My table config in the class definition:

![image](https://user-images.githubusercontent.com/9052094/73749751-45183880-475c-11ea-9936-d593ad1ee034.png)

**Comment by weisswurstkanone** [comment]
already fixed => 6.5.0
see https://github.com/pimcore/pimcore/pull/5610
