### ISSUE TITLE
InheritanceHelper: Analyse memory consumption

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#5714]

**Comment by weisswurstkanone** [comment]
Follow-up of #4997

**Comment by brusch** [comment]
#5724 implemented some improvements by not fetching and storing some unnecessary data and by using references. We have seen a reduction of memory of one third, which is a good improvement in my opinion.
Further improvements would be possible, but only in terms of memory consumption. But that would mean implementing a completely new approach, which processes the data in batches. That possibly has negative effects on the execution time, so I'd rather not try this approach unless it's really necessary.
