### ISSUE TITLE
[Data Objects] Possibility to configure Interfaces on Class Definitions

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#5715]
# Feature Request

Create a possibility to define interfaces in Pimcore class definitions.

## Feature description

We already can define parent classes and traits:

![class-definition](https://user-images.githubusercontent.com/1703552/73757784-08ebd480-476a-11ea-83fa-606918c33acf.png)

https://pimcore.com/docs/6.x/Development_Documentation/Objects/Object_Classes/Class_Settings/Inheritance.html

So why not interfaces? It would be useful for certain scenarios. Recently I was writing a form builder built on Data objects. It contains four class definitions:

FormInputText
FormInputOptions
FormInputSelect
FormInputFile

They all have some common methods, but a trait would be unnecessary as there is no code reuse. I just want the class definition to use the interface FormInput such that I can check with instanceof in the service.

Or did I miss something?

**Comment by dpfaffenbauer** [comment]
I personally don't like the idea of auto-generated code that "magically" implements some interfaces. I'd rather say create a parent class and implement the interface there, much clearer that way what is going on.

**Comment by Blackbam** [comment]
In case of multiple interfaces you might need multiple parent classes extending AbstractObject just to combine different interfaces. Even if their only purpose is to indicate an "is-a" relationship. We have traits and parent classes already can you really do more damage by interfaces definitions? ;-)

**Comment by dpfaffenbauer** [comment]
Just add one parent class and implement multiple interfaces for one DataObject.

the issue might be that the DataObject is not really capable of implementing a certain interface... that is my biggest concern.

**Comment by Blackbam** [comment]
@dpfaffenbauer

**Comment by Blackbam** [comment]
@dpfaffenbauer 

We have the following four interfaces (which might have methods or not):

> AppBundle\CommonInterface\Animal
> AppBundle\CommonInterface\Flyer
> AppBundle\CommonInterface\Insect
> AppBundle\CommonInterface\Robot

Lets say we have five DataObject Classes:

> Bird implements Animal,Flyer
> Ape implements Animal
> Fly implements Animal, Flyer,Insect
> RobotApe implements Animal,Robot
> RobotFly implements Animal,Robot,Insect

Now we would have to create five different parent classes (no multi-inheritance in PHP) though within the services I just want to now if this is for instance a Robot.

I understand your concern that you may cause exceptions in case you implement the wrong interfaces or in case the interfaces have methods which are not represented in the generated class. But with abstract methods in traits or parent classes you can cause pretty much the same damage right?

**Comment by dpfaffenbauer** [comment]
yes, you can.

Maybe you're right, maybe it does more good than harm. 

Anyhow: it is not my decision anyway to implement it or not.

**Comment by Blackbam** [comment]
@dpfaffenbauer It is just an improvement suggestion which I think would be useful. Thanks for your first feedback anyway 👍

**Comment by jdreesen** [comment]
Makes sense to allow interfaces, too. I've created abstract classes with (only) abstract methods as parent classes for data objects just to have a type contract that I can check for. An interface would have been enough there.

**Comment by brusch** [comment]
Sounds good to me - anyone willing to create a PR for that?
