### ISSUE TITLE
[DataObject] Localized-Field Relation from Field-Collection in Data Object cannot be saved

### ISSUE THREAD

**Issue by albertmueller** [pimcore/pimcore#5719]
# Bug Report

### Expected behavior
Update a existing releation, instead catch the exception from insert in logger.

### Actual behavior
Throw exception and shows validation failed "unique constraint violation" in backend.
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-3-localizedfield-/fieldcollection~footerColumn1/0/localizedfie' for key 'PRIMARY'

### Steps to reproduce
Add a field collection with a localized field with a many to one field and use it as footerColumn1... in a class like:
![image](https://user-images.githubusercontent.com/2986829/73827938-b3163b80-4800-11ea-8b4b-d995f6eddb3d.png)
Create a new object and drag a document to the many to one field, save the object -> press the reload button and click on save & publish.

### Code example
use
```php
$db->insertOrUpdate('object_relations_' . $classId, $relation);
```
instead of insert exception:
```php
$db->insert('object_relations_' . $classId, $relation);
```

**Comment by weisswurstkanone** [comment]
IMHO, instead of hiding the problem by doing an insertOrUpdate we should try to find out what causes the violation. This shouldn't happen.

**Comment by weisswurstkanone** [comment]
Am not able to reproduce the problem following your description. Are you on the latest version?

**Comment by albertmueller** [comment]
yes, on dev-master, i can send you the class if you want

**Comment by weisswurstkanone** [comment]
yes, please.

and maybe add detailed instructions which steps I should follow (maybe I am missing something).
video should be sufficient.

**Comment by albertmueller** [comment]
[classes.zip](https://github.com/pimcore/pimcore/files/4165542/classes.zip)
1. create a new object -> SiteConfiguration
2. add two elements in the first field collection
3. drag a document to element 1, t1 and drag a object (SiteConfiguration) to t2
4. save & publish the object
5. press the reload button on the object
6. press save & publish again -> then it shows the error "unique constraint violation"

**Comment by weisswurstkanone** [comment]
Unable to reproduce. Object looks like

![image](https://user-images.githubusercontent.com/6142086/73952819-c5c36a00-48ff-11ea-9f11-f77aa04fde89.png)

**Comment by albertmueller** [comment]
@weisswurstkanone lets try again with a screencast video, based on PHP 7.3.14 / Pimcore 6.4.2:
[screencast_video.zip](https://github.com/pimcore/pimcore/files/4167688/screencast_video.zip)

**Comment by weisswurstkanone** [comment]
Please clarify: above you say dev-master, but now it is 6.4.2 ?

**Comment by weisswurstkanone** [comment]
mhm, the screencast doesn't exactly show what you were describing above :-)

**Comment by albertmueller** [comment]
that doesn't matter, it's the same issue on dev-master and the screencast shows exactly that what i describing above :)

**Comment by weisswurstkanone** [comment]
you didn't mention that I have to fill the second element

**Comment by albertmueller** [comment]
sry for that, you're right on this point and i hope that you can reproduce it now on your side?

**Comment by weisswurstkanone** [comment]
still, not able. I am exactly following the steps in the screencast

**Comment by albertmueller** [comment]
i prepared a example for you:
https://demo.pimcore.fun/admin/?perspective=CMS
open object id: 1131 and just click on save & publish

**Comment by weisswurstkanone** [comment]
ok, we did it in parallel :-)
there it can be reproduced. notice that the problem is gone after clearing the cache.

**Comment by albertmueller** [comment]
what exactly do you mean by that? my PR fixes this issue. but to be more precise, i think the issue arises before, there should be no save event fired, because no data was changed. by the way i recommend to refactor the whole data object releation topic to doctrine entities :)

**Comment by weisswurstkanone** [comment]
rejected

**Comment by davidhoeck** [comment]
@weisswurstkanone i am experiencing exactly the same issue with a similar setup as @albertmueller  has. The PR of Albert fixed it - why should that be rejected? Just because Albert said the truth - I just don't get it ...

**Comment by dpfaffenbauer** [comment]
@albertmueller Re Doctrine: Provide a PR for it :D, good luck with that. It is possible, but very hard to achieve.

**Comment by albertmueller** [comment]
@dpfaffenbauer i know, it's a huge change, but if i have a look at the releation db table...

**Comment by weisswurstkanone** [comment]
@davidhoeck , the collission shouldn't be even there because before the insert the existing rows should be deleted which isn't the case here.
So rather than hiding the real problem by doing an insertOrUpdate I would check why they don't get deleted.

**Comment by albertmueller** [comment]
this logic was unclear to me, should the relations be deleted if i save the object? with xdebug i can't see that the releations be cleared on save.

**Comment by weisswurstkanone** [comment]
Yes, exactly.

On my local instance I see stuff like that (before the insert)

pimcore-5@pimcore:~/demo-basic/var/logs$ tail -f dev.log  | grep object_rela
[2020-02-07 11:37:17] doctrine.DEBUG: SELECT * FROM object_relations_37 WHERE fieldname = 't2' AND ownertype = 'localizedfield' AND ownername LIKE '/fieldcollection~footerColumn1/1/%' AND position = 'en_US' AND src_id = '1482' [] []
[2020-02-07 11:37:26] doctrine.DEBUG: SELECT * FROM object_relations_37 WHERE fieldname = 't1' AND ownertype = 'localizedfield' AND ownername LIKE '/fieldcollection~footerColumn1/0/%' AND position = 'en' AND src_id = '1482' [] []
[2020-02-07 11:37:26] doctrine.DEBUG: SELECT * FROM object_relations_37 WHERE fieldname = 't1' AND ownertype = 'localizedfield' AND ownername LIKE '/fieldcollection~footerColumn1/0/%' AND position = 'de' AND src_id = '1482' [] []

but I don't understand why this doesn't happen on demo.pimcore.fun

**Comment by weisswurstkanone** [comment]
@albertmueller  Can you check why this line isn't executed ?
https://github.com/pimcore/pimcore/blob/739957f849b8804683f71eef9be5c21493d932f5/models/DataObject/Fieldcollection/Dao.php#L240

**Comment by weisswurstkanone** [comment]
Update: error does not happen if error reporting is set to E_ALL

**Comment by weisswurstkanone** [comment]
partly a regression of https://github.com/pimcore/pimcore/commit/ab4dd686f937376b2b158f3ae5c2f37176baf4f4
