### ISSUE TITLE
[Document|Data Object] Content is not copied unless the content is saved & published.	

### ISSUE THREAD

**Issue by PandeleCristian** [pimcore/pimcore#5721]
Version: v3.6.3

Description:
Content is not copied unless the content is saved and published.

Steps to reproduce:

1. Create a new content page or modify one,
2. Only save, DON't Publish,
3. Copy and Paste with inheritance as a new language variant,
4. Notice that the modified content is not visible on the copied page.

Video: https://we.tl/t-tJzR0VFnEO

Current behavior:
Content is not copied when the user whats to paste it on a new page.

Expected behavior:

When the user wants to copy and paste a Page he should do it without publishing it.

**Comment by brusch** [comment]
@PandeleCristian can you please check if this bug is also reproducible on our public demo running the latest version of Pimcore? 

http://demo.pimcore.fun/admin/ (`admin` | `demo`) 

Thanks!

**Comment by PandeleCristian** [comment]
@brusch 
I did. Please check the video here: https://we.tl/t-tJzR0VFnEO
