### ISSUE TITLE
Workflow Publishes last Version on Submit when object is published

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#5726]
My use case is following:

An Object should only be allowed to change when in a specific state. That all is possible with the Workflow and an OBJECT_PRE_SEND Event to remove the save permission. But: as soon as I trigger the review transition, Pimcore internally calls the `save` method:

https://github.com/pimcore/pimcore/blob/master/lib/Workflow/Manager.php#L248

That causes the current version to be published. I cannot unpublish the object first, cause it should also be available in other places.

It should be configurable if it should just create a new version or "publish" the changes immediately

**Comment by MVermue** [comment]
I'm also running into this issue

**Comment by nielvrom** [comment]
Also experiencing this issue, what's the status of this problem?

**Comment by dpfaffenbauer** [comment]
@nielvrom nothing....

**Comment by fabfischer** [comment]
Any progress on this matter?

**Comment by macghriogair** [comment]
Looking forward to see this fixed 🙏 🙂
