### ISSUE TITLE
[Versions] Copy paste specific version

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#5734]
# Feature Request
![image](https://user-images.githubusercontent.com/5137917/73932981-c64a0980-48db-11ea-83c3-f7862e8ab99a.png)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
