### ISSUE TITLE
if adding Table without default values to DataObject Class in localizedField-Type, nothing will be saved in DataObject

### ISSUE THREAD

**Issue by rustymcfly** [pimcore/pimcore#5746]
# Bug Report

### Expected behavior
DataObject should be saved with the User-given Data
### Actual behavior
DataObject isn't saving any data
### Steps to reproduce
 - Create a DataObject Class
 - add Localized Fields
 - add a textInput and a table to localized Fields
 - Create an Object of this Class
 - fill in the Data and Save

**Comment by weisswurstkanone** [comment]
Unable to reproduce

**Comment by brusch** [comment]
@rustymcfly maybe you can share some more details on that as we're not able to reproduce the issue. Thanks a lot!

**Comment by weisswurstkanone** [comment]
maybe related to https://github.com/pimcore/pimcore/issues/5713 ?

@rustymcfly please provide details and check if the problem still persists.

**Comment by weisswurstkanone** [comment]
@rustymcfly ping, last reminder
