### ISSUE TITLE
[DataObject] [Slider] Improve display of the slider component

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#5748]
When creating a new DataObject with a slider component the value of it is NULL. The Slider is however set to the lowest position that is some numeric value. To set the slider to the lowest value you have to first change the value and drag it back again.

This seems very confusing for customers. They essentially also have no idea what NULL means.
Maybe we should display something like 'No Value Set' instead of NULL and mark the slider differently somehow?

I think we should also introduce a way to reset the slider value back to NULL to enable inheritance again. Similar to the trashcan for the checkbox type.

![image](https://user-images.githubusercontent.com/7206334/74024225-a9780980-49a1-11ea-8966-d2b47b0bc7e2.png)

What do you guys think?

**Comment by weisswurstkanone** [comment]
@brusch needs discussion

**Comment by brusch** [comment]
Sounds reasonable for me ... just the same way we do for boolean.
