### ISSUE TITLE
Keep version of different user

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#5753]
If 2 or more users are editing a document/asset/object after each other and the version save history is set to "x" steps I suggest that Pimcore should also keep the last version another user has created. In the case of more than 10 other users, this would mean an error message would have to be displayed, but I think this would rarely be the case.

![image](https://user-images.githubusercontent.com/13643455/74035294-04c8ec80-49e0-11ea-8e5f-6a1220fc21f9.png)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
