### ISSUE TITLE
Image Src Attribute as Data Attributes

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#5755]
Google PageSpeed Analysis treats us hard these days, and we should consider serving image sources in other ways than a simple `src` or `srcset`. This would allow us to implement recommended scripts like [lazysizes](https://github.com/aFarkas/lazysizes) with ease. 

Read more about it here: https://web.dev/codelab-use-lazysizes-to-lazyload-images/

Adding an option like `['renderAsData' => true]` to `pimcore_image` e.g. `getHtml()` could solve this. WDYT?

**Comment by brusch** [comment]
That's already there, when you're using the low quality image previews: 
```
$image->getThumbnail()->getHtml(['lowQualityPlaceholder' => true])
```
Starting with v6.5.0 it's getting even better, because this config even works if the LQIP file doesn't exist, see #5728

**Comment by solverat** [comment]
@brusch It was there! ALL THE TIME! Sorry, I totally missed that! Thank you!

**Comment by brusch** [comment]
😎 You're welcome, enjoy using it 😉
Btw. there's also a cmd that helps to ensure that every image has a LQIP 
`./bin/console pimcore:image:low-quality-preview`
