### ISSUE TITLE
Avoid deadlocks caused by many concurrent insert/update operations

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#5761]
Deadlocks are mainly caused by delete/inserts into the `dependencies` and  `object_*_relations` table, but maybe there are also other tables affected, such as `versions`, ...

**Comment by brusch** [comment]
One possible solution would be using something like that on  `Pimcore\Db\PimcoreExtensionsTrait`
```
    public function deleteWhereById($table, $where = '', $idColumnName = 'id')
    {
        $sql = sprintf('SELECT `%s` FROM `%s`', $idColumnName, $table);
        if ($where) {
            $sql .= ' WHERE ' . $where;
        }

        $ids = $this->fetchCol($sql);
        if(!empty($ids)) {
            return $this->deleteWhere($table, sprintf("`%s` IN (%s)", $idColumnName, implode(",", $ids)));
        }

        return null;
    }
```

**Comment by brusch** [comment]
I'm wondering why we're experiencing deadlocks there, because that shouldn't happen at all :( 
https://dev.mysql.com/doc/refman/5.7/en/innodb-locks-set.html 
https://dev.mysql.com/doc/refman/5.7/en/innodb-locking.html

**Comment by weisswurstkanone** [comment]
Maybe off-topic, but should be notices. Managed to create the following situation after
- open object with relation data
- clear cache
- save it without touching anyhting

The hash is different which triggers:
- remove all existing dependencies
- re-insert the same ones

![image](https://user-images.githubusercontent.com/6142086/75039096-3948a800-54b8-11ea-9b9b-f6c094a2b6fa.png)

**Comment by weisswurstkanone** [comment]
group_concat returns a different result because the default max length is 1024 which doesn't scale very wellfor that purpose.
see https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_group_concat_max_len

**Comment by weisswurstkanone** [comment]
maybe replace this:
https://github.com/pimcore/pimcore/blob/ae677a1de09d1c488cce9cea3ba95a3e44954ae0/models/DataObject/AbstractObject/Dao.php#L123

- delete only needed if it is not locked anymore.
- otherwise insert or update

**Comment by weisswurstkanone** [comment]
not directly related. do we need both or is a composite enough?
https://github.com/pimcore/pimcore/blob/17d4ce07869ffad2aa0c920ed75aa55a3e6ff44e/bundles/InstallBundle/Resources/install.sql#L106

**Comment by brusch** [comment]
Todo: relations tables, field collections, ...

**Comment by shubhangi101092** [comment]
> Todo: relations tables, field collections, ...

@weisswurstkanone  @brusch @dvesh3 any solution we still have this issue while updating dependencies and relations tables 

Import failed for class: Catalog. [Reason: An exception occurred while executing 'UPDATE object_relations_catalog SET dest_id=? WHERE src_id=? AND ownertype=? AND dest_id=?' with params [1758145, 1755661, "object", 792567]:
 
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction ] [ErrorCode: 1002]

Looking for solution at earliest!
