### ISSUE TITLE
Calculated values in classification store doesn’t get saved in database

### ISSUE THREAD

**Issue by Maksonis** [pimcore/pimcore#5776]
Hi, when saving an object with a Calculated value field in the classification store, the calculated value doesn’t get saved in the database. Also when using setLocalizedKeyValue to set the calculated value manually i get this error:

![image](https://user-images.githubusercontent.com/17277953/74314811-6db0bb80-4d76-11ea-8761-5efe81f042f1.png)

**Comment by weisswurstkanone** [comment]
Calculated values are not saved in the database.
See https://pimcore.com/docs/5.x/Development_Documentation/Objects/Object_Classes/Data_Types/Calculated_Value_Type.html

I will have a look at the error though

**Comment by weisswurstkanone** [comment]
Why would you try to call the setter for the calculated value.

Please check the docs on how to use it.

**Comment by interuros** [comment]
How can i get the value, name(translated) of a calculatedValue data type from the classification store in my controller/view?
