### ISSUE TITLE
Password-reset when saving an user

### ISSUE THREAD

**Issue by StephanWeinhold** [pimcore/pimcore#578]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [x] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [x] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [x] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [x] There's no existing ticket for the same issue

### Expected behavior 
When saving an user in Chrome I do not expect the password of this user to be reseted.
  
### Actual behavior  
When saving an user in Chrome the password of this user is reseted.
  
### Steps to reproduce  
Add a user, set a password for this user, close the user, reopen it in Chrome, click "save" and the password of this user is reseted to some Chrome-saved-passwords-value. Maybe it's the fieldname? I can't figure it out.

**Comment by brusch** [comment]
Sorry, I'm not able to reproduce this problem. 
According to https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion this depends on your own  browser settings and there is not much you can do about that in your web application. 

I've also enabled the integrated password manager and do not face any issues, so I recommend to double check your browser settings. 

Thanks!
