### ISSUE TITLE
[Sitemap] DocumentTreeGenerator does not consider Pretty URLs

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#5780]
Pretty URLs should also appear in the sitemap.

![image](https://user-images.githubusercontent.com/7206334/74326749-37ca0200-4d8b-11ea-9270-bf83fed010b1.png)

**Comment by dvesh3** [comment]
@ultramegatom works for me on latest version:
![image](https://user-images.githubusercontent.com/5137917/74664824-c3ce9600-519e-11ea-8d48-e7ae41aa3275.png)

![image](https://user-images.githubusercontent.com/5137917/74664787-b0232f80-519e-11ea-8d5c-b35ea767380a.png)

**Comment by ultramegatom** [comment]
ahh right was using an older version - seems it was added here: https://github.com/pimcore/pimcore/commit/2268f42922de6b1f61078851fb458815fa157889

nvm then sry
