### ISSUE TITLE
Pimcore Mail does not provide mail params in view model

### ISSUE THREAD

**Issue by podarcis** [pimcore/pimcore#5785]
# Bug Report

The documentation https://pimcore.com/docs/6.x/Development_Documentation/Development_Tools_and_Details/Email_Framework/Pimcore_Mail.html states that `setParams` sets the parameters for both placeholders and the email view. However, the view can not access these parameters as they aren't set

### Expected behavior

Mail param `foo` can be accessed in template by using `$this->foo`.

AFAICR that was the behavior in Pimcore 4.

### Actual behavior

View model does not contain key `foo` and thus cannot be accessed from within template (in this case PHP template).

However, the params are accessible through request's attributes (`$request->attributes`) from e.g. within controller action.

### Steps to reproduce

1) Prepare and send a mail with \Pimcore\Mail using params and a document: 
```php
$mail = new \Pimcore\Mail();
$mail->addTo('example@pimcore.org');
$mail->setDocument('/email/myemaildocument');
$mail->setParams(['foo' => 'bar');
$mail->send();
```

2) Create email document `/email/myemaildocument` and set `FooController` and `fooAction`.
3) Have `FooController` and `fooAction` render a template `foo.html.php`.
4) Template `foo.html.php` tries to access `$this->foo`, but its unset and thus null.

### Crude workaround

Set some/all request's attribute keys as view model variables.

```php
    public function onKernelController(FilterControllerEvent $event)
    {
        parent::onKernelController($event);

        // set params for view
        $request = $this->requestHelper->getCurrentRequest();
        $viewParams = $request->attributes->all();
        foreach ($viewParams as $key => $value) {
            $this->view->$key = $value;
        }
    }
```

---
Using Pimcore 6.4.2

**Comment by dpfaffenbauer** [comment]
that is actually on purpose, since how should attributes be passed on the template when the controller is responsible to render the template?

**Comment by podarcis** [comment]
@dpfaffenbauer Thanks for your reply. I'm just noting that either the documentation is outdated and/or the behavior differs from Pimcore 4, or am I wrong? I have no problem extracting the params from attributes manually and provide these to the view model if that's the way it's intended.

**Comment by dpfaffenbauer** [comment]
It does differ from Pimcore 4, but that should be clear, since there was quite a major change in between ;)

Yes, extract that in your action and pass it on to the view

**Comment by brusch** [comment]
Docs need to be updated. 
Thanks for reporting!
