### ISSUE TITLE
Object links in wysiwyg fields - use Link Generator

### ISSUE THREAD

**Issue by zerlpaMMT** [pimcore/pimcore#5796]
In WYSIWYG fields you can drag and drop an object to make a link inside the field. 
It is allowed and will be saved correctly to the database (same behavior like with documents). After reloading the document in the backend the link is cleaned up the same behavior is in the frontend. With documents there is no problem you can drag and drop into WYSIWYG field and create links without any issues.

### Expected behavior
As it is allowed here https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Resources/public/js/pimcore/document/tags/wysiwyg.js#L251 i expect that the object use the linkgenerator to displays an correct link.

**Comment by brusch** [comment]
Hmm, I guess that's a bug, that worked already as far as I can remember.

**Comment by zerlpaMMT** [comment]
i think it was a bug at 6.3.6 after pimcore update to 6.4.2 everything works fine.
