### ISSUE TITLE
Asset preview overloads server

### ISSUE THREAD

**Issue by John5** [pimcore/pimcore#580]
Some of our customers are complaining that Pimcore becomes unresponsive when working with images in Pimcore.

The problem is the asset preview which starts to generate thumbnails as soon as the mouse cursor hovers over a folder. When a folder contains a large amount of (high resolution) images it seems like Pimcore will try generate thumbnails all simultaneously.

I assume this problem could be relieved by generating the previews as part of the maintenance cycle.

**Comment by brusch** [comment]
Not only - the thumbnails for the preview are also generated when saving an asset. 
So I guess you cleaned the tmp files or anything else is not completely correct. 

But anyway, you can use the maintenance job to create them in advance. 

See also: 
php pimcore/cli/console.php list 
and
https://github.com/pimcore/pimcore/blob/87bfef793580b0ac41586db9f95056a342c452ee/pimcore/models/Asset/Image.php#L65-L65

Btw. I think this type of question should be discusses somewhere else :)
