### ISSUE TITLE
[Travis] Use different MySQL/MariaDB versions for existing jobs

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#5811]

**Comment by weisswurstkanone** [comment]
Succeeded with maria 10.2 and 10.3, mysql 5.7

https://github.com/pimcore/pimcore/issues/5809 would have been detected.
see
https://travis-ci.com/pimcore/pimcore/jobs/288821858?utm_medium=notification&utm_source=email

**Comment by brusch** [comment]
@weisswurstkanone That's fine for now (better than nothing), let's go ahead with those versions. Thanks!

**Comment by brusch** [comment]
Todo: check if it would be better to script the install of individual MySQL/MariaDB versions, because not all versions supported by Pimcore are available as an add-on on Travis and using different add-ons for different tasks blows up the config.

**Comment by brusch** [comment]
Done by #6014
