### ISSUE TITLE
CleanupBrickTables maintenance task does not recognize bricks with capitalization in name

### ISSUE THREAD

**Issue by efnack** [pimcore/pimcore#5824]
Maintenance task does not recognize bricks with capitalization in name causing ERROR in processing. 
Was this intended for some reason?

Ref: lib/Maintenance/Tasks/CleanupBrickTablesTask.php

Fixed locally

```php
private function getBrickDef($brickType) {
        $list = new Definition\Listing();
        $list = $list->load();
        
        foreach ($list as $brickDefinition) {
            if (strtolower($brickDefinition->getKey()) === $brickType) {
                return $brickDefinition;
            }
        }
}
```
And replace line 56
```php
$brickDef = $this->getBrickDef($brickType);
```

**Comment by weisswurstkanone** [comment]
Unable to reproduce.

Example: 
- brick name "LazyLoadingTest"
- class: numbertest
- renamed field from "brickfield" to "brickfield2"
- executed command
- table "object_brick_store_LazyLoadingTest_30" got cleaned up properly

**Comment by brusch** [comment]
@efnack see @weisswurstkanone answer ... can you please share some more details please? 
Thanks a lot!

**Comment by weisswurstkanone** [comment]
Can you please explain:
- how is you brick called (was it renamed maybe)
- how it your class name
- which table causes the problem?

**Comment by efnack** [comment]
If I reverse the changes and create a brick called TestBrick and save, it will create the tables
- object_brick_query_testbrick_5
- object_brick_store_testbrick_5

And when the maintenance task will give error:
10:52:37 ERROR     [app] Brick 'testbrick' not found. Please check table object_brick_store_testbrick_5
10:52:37 ERROR     [app] Brick 'testbrick' not found. Please check table object_brick_query_testbrick_5

As i've read the code it uses the table names to get brick definition. Is there a setting which makes table names keep capitalization of brick name as it does in your system?

Hope this clears things up

**Comment by weisswurstkanone** [comment]
Mhm, if I create a brick called "HelloYou" it creates a table object_brick_store_HelloYou_[classid]

**Comment by efnack** [comment]
Yes, I've found the issue. It's cause my development database is located on a Windows server, with `lower_case_table_names` set to 1. Which is default on Windows systems. So it will decapitalize, which will make the approch to checking if brick by key exists fails in the task.

Perhaps using the actual list of bricks as I suggest (or something more elegant) would be safer (or more universal) approch.

Thanks for the brainstorm :)

**Comment by brusch** [comment]
See #5829, a check for that setting would be definitely useful I guess.
