### ISSUE TITLE
Add hreflang alternates to Pimcore documents in sitemaps

### ISSUE THREAD

**Issue by davidhoeck** [pimcore/pimcore#5825]
# Bug Report

### Expected behavior
Either having separated sitemaps per language like `sitemap_de.xml` or `sitemap_en.xml` or alternate hreflang links per `<url>` section in the sitemap.

### Actual behavior
Everything in one `sitemap.xml` 

### Steps to reproduce
Just follow the docs. 

# Feature Request

## Feature description

Add hreflang links to the `<url>` containers for every document, if translations for the documents are available. https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/5-decorating-urls.md#adding-alternales

**Comment by dpfaffenbauer** [comment]
that is use-case dependent. For example, if you have multi-sites, Pimcore should never throw everything in one sitemap or sitemap_en/sitemap_de. It should do it site based. 

For that reason, I see that as a project implementation decision which you need to take care of. Pimcore gives you a simple example of how it works, you need to decide what works for your project.

**Comment by davidhoeck** [comment]
@dpfaffenbauer Pimcore already handles the sites and then adds the documents for every site. I would prefer the way with https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/5-decorating-urls.md#adding-alternales

I think that should be implemented for documents when localized documents are available.

**Comment by dpfaffenbauer** [comment]
yes, but I have to change that behaviour everytime cause it doesn't suite my usecase. They just generate one sitemap.xml where they refer to the sites sitemap.xml, which in my point of view is not right, cause every site should deliver it's own sitemap.xml.

**Comment by davidhoeck** [comment]
@dpfaffenbauer yes - that's totally right what you say, but I think also the documents of every site should have their hreflang tags.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
