### ISSUE TITLE
Update Codeception

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#5827]
To the latest version. 
Also update here: 
https://github.com/pimcore/demo/blob/master/composer.json#L24
https://github.com/pimcore/skeleton/blob/master/composer.json#L16

**Comment by brusch** [comment]
See also https://github.com/pimcore/skeleton/issues/18

**Comment by brusch** [comment]
There seem to be problems with Symfony 3.4 support in newer version of codeception, so I'm afraid we have to wait until Pimcore v7. 
Or did anyone else got it to work? 😊

**Comment by jdreesen** [comment]
Can you give more details about the problem? 
We used Codeception v3 for the acceptance tests (with Selenium) in one of our projects and it worked fine.

**Comment by weisswurstkanone** [comment]
As far as I remember we struggled a lot to get it working for both Symfony 3.4 and 4 at the same time. 
We would be happy about any input about this topc. Would be nice if you could share your experiences ;-)

**Comment by brusch** [comment]
Resolved by #7542
