### ISSUE TITLE
Calculated field not working in ObjectBricks LocalizedFields

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#5828]
```
Message: Call to undefined method getName in class Pimcore\Model\DataObject\Objectbrick\Definition
Trace: 
#0 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/CalculatedValue.php(502): Pimcore\Model\AbstractModel->__call('getName', Array)
#1 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Localizedfields.php(831): Pimcore\Model\DataObject\ClassDefinition\Data\CalculatedValue->getSetterCodeLocalizedfields(Object(Pimcore\Model\DataObject\Objectbrick\Definition))
#2 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Objectbrick/Definition.php(277): Pimcore\Model\DataObject\ClassDefinition\Data\Localizedfields->getSetterCode(Object(Pimcore\Model\DataObject\Objectbrick\Definition))
#3 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php(1082): Pimcore\Model\DataObject\Objectbrick\Definition->save()
#4 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\ClassController->objectbrickUpdateAction(Object(Symfony\Component\HttpFoundation\Request))
#5 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#6 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(198): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/html/web/app.php(50): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main
```

It assumes it is within a regular classes LocalizedFields.

**Comment by brusch** [comment]
I guess this is currently just not supported. 
Looking at the [contextual information](https://pimcore.com/docs/6.x/Development_Documentation/Objects/Object_Classes/Data_Types/Calculated_Value_Type.html#page_Context-Information-for-Calculation-Class), it seems that adding support for this could be a bit challenging 😊

**Comment by dpfaffenbauer** [comment]
I guessed that as well, but, why does the generated getter has a `$language` param?

https://github.com/pimcore/pimcore/blob/eb6be7725a9a9c4d34248df69a945ac3e3f5606c/models/DataObject/ClassDefinition/Data/CalculatedValue.php#L398

**Comment by dpfaffenbauer** [comment]
which it doesn't use...

**Comment by weisswurstkanone** [comment]
Maybe time has come to introduce a more flexibel approach for the context info (which should of course provide in addition to the current one for BC reasons).
I can imagine a doubly-linked list where each node describes the container starting from top level (object) down to the actual field including every container in the middle.

**Comment by weisswurstkanone** [comment]
somehow related: #6128

**Comment by weisswurstkanone** [comment]
Hi @dpfaffenbauer , could it be that your specific problem is already fixed by the commit shown here (it is a pretty old one) ?

![image](https://user-images.githubusercontent.com/6142086/80070705-ae317000-8543-11ea-89cd-f87620718894.png)

**Comment by weisswurstkanone** [comment]
@dpfaffenbauer ping

**Comment by brusch** [comment]
See also #6411

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
