### ISSUE TITLE
System Requirements Check: add lower_case_table_names check

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#5829]
Related to #5824

**Comment by efnack** [comment]
Windows filesystem is case insensitive so setting this to 0 will not work. Setting it to 2 seems to solve it.

**Comment by brusch** [comment]
@efnack but according to the docs `0` should be the way to go, and it's the default value as well. 
See https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_lower_case_table_names

**Comment by efnack** [comment]
The documentation say that you should not set 0 on systems with case-insensitive file system

>  You should not set lower_case_table_names to 0 if you are running MySQL on a system where the data directory resides on a case-insensitive file system (such as on Windows or macOS). It is an unsupported combination that could result in a hang condition when running an INSERT INTO ... SELECT ... FROM tbl_name operation with the wrong tbl_name lettercase. With MyISAM, accessing table names using different lettercases could cause index corruption.

> An error message is printed and the server exits if you attempt to start the server with --lower_case_table_names=0 on a case-insensitive file system. 

Also says if your using InnoDB that it should be set to 0 on all platforms
> If you are using InnoDB tables, you should set this variable to 1 on all platforms to force names to be converted to lowercase.

Pimcore using InnoDB should perhaps ony allow lowercase table names, would be safer in regards to portability between platforms.

**Comment by jdreesen** [comment]
Setting it to `1` should be the way to go. We used this value after experiencing problems with duplicated tables with different casings.

**Comment by brusch** [comment]
@jdreesen don't think so, handling in Pimcore is case-sensitive ... that was actually the reason why @efnack experienced those problems.

**Comment by dpfaffenbauer** [comment]
FIY: talking about database case-sensitive and insensitive tables. There is actually a problem with doctrine orm as well. Pimcore creates tables case-sensistive, doctrine ORM creates them insensitive. Using the Doctrine DBAL Schema Manager, you actually encounter issues that the Schema Manager picks up the case-sensitive tables, but it tries to create/edit them case-insensitive, resulting in duplicate table errors.

**Comment by jdreesen** [comment]
@brusch but why? Do you really want to have the same table with different casings? This does not work on Windows systems anyways.

**Comment by brusch** [comment]
Not really, but it's the default setting 😊
Maybe we should just leave everything as it is, wasn't a problem for years now anyway 😉

Btw. Windows is not supported officially.

**Comment by solverat** [comment]
According to the mysql docs, this can be a real issue: 

```
On Unix, the default value of lower_case_table_names is 0. 
On Windows, the default value is 1. 
On macOS, the default value is 2.

– https://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html
```

If you're running mysql on a docker client on os x for example, the default value would be `2` which leads to issues described in #5824. I don't know why this is a bigger issue  here, but this is an important setting which should be covered by the system requirements  check.
