### ISSUE TITLE
Issue with *Date & Time* field's *Use current date* option

### ISSUE THREAD

**Issue by jbq** [pimcore/pimcore#584]
# Bug Report

### Expected behavior 

When adding a *Date & Time* field, I assign a name to the field and check the *Use current date* option.  Then I select another field.  When I select the *Date & Time* field again the *Use current date* option should still be checked.
### Actual behavior  

The *Date & Time* field's *Use current date* option is unchecked
  
### Steps to reproduce  

1. Add a *Date & Time* field in a class
1. Check the *Use current date* option
1. Select another field
1. Select the newly-created *Date & Time* field

**Comment by brusch** [comment]
Thanks! 
This was also the case for the "Date" field.
