### ISSUE TITLE
Rendering of pages with Areablock in an EventListener gives a recursion error

### ISSUE THREAD

**Issue by BenjaminEden** [pimcore/pimcore#5843]
# Bug Report
In an EventListener I render the saved page in pimcore.document.postUpdate event via

`Service::render($doc, [], true)`

to extract the content for a Solr index. I get a recursion error, but only if the page has a not empty Areablock. This is **not** the case outside of the Trigger (eg. in a simple view template).

**Comment by brusch** [comment]
Can you please share some more details, like a stack trace? 
Or even better, since you have a running use-case, it would be really nice if you can try to fix it and provide us directly a PR 😊

**Comment by BenjaminEden** [comment]
Sure, the stack trace is really huge.

[stacktrace.txt](https://github.com/pimcore/pimcore/files/4218326/stacktrace.txt)

And from php.log:

`php.CRITICAL: Uncaught Exception: Recursion detected {"exception":"[object] (Symfony\\Component\\Serializer\\Exception\\NotEncodableValueException(code: 0): Recursion detected at /.../vendor/symfony/symfony/src/Symfony/Component/Serializer/Encoder/JsonEncode.php:51)"} []`

It must have something to do with the fact that I'm rendering in context of the trigger. This seems to lead to some problems when rendering the Areabricks.
The same command with the same document outside of the trigger context is not throwing an error. And the error only occurs, when the page has an none empty Areablock.

What's also strange, is that in both cases the render command does return the correct document markup. But the error bubbles to the UI and you have to reload the backend or at least reopen the document.

Regarding PR: I've tried to find the cause of the error for more than two hours now. I'm afraid this is a job for the cool guys from Elements. ;)

**Comment by BenjaminEden** [comment]
Fixed by #5866 and 02efc01.
Thanx!
