### ISSUE TITLE
In a video editable, if a poster asset is set, it is not used.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#5846]
Hello,

In a video editable, if a poster asset is set, it is not used.
It seems it always use the generated thumbnail.
It is on Pimcore 6.4.2, so this fix is already in the code https://github.com/pimcore/pimcore/pull/4005 

Code:

```
<div class="cms_video_block">
    {% set video = pimcore_video('cms_video_block',
        {
            'class':'cms_video_block',
            'disableProgressReload' : true
        })
    %}
    {{ video |raw}}
</div>
```

BO config:

![image](https://user-images.githubusercontent.com/9025839/74737821-eff91e00-5255-11ea-85df-9dca7c8cae84.png)

If we display manually `{{ video.getPosterAsset()}}` the poster is well here.

Don't hesitate to ask any further information.
Thanks.

**Comment by dvesh3** [comment]
@Yivan Sorry, cannot reproduce on latest version.

**Comment by Yivan** [comment]
@dvesh3 So this has been patched meanwhile, good.
I will make some diff to patch this on our version if necessary.
You can close this issue so. Thanks!
