### ISSUE TITLE
change elements per page in folder list view has no effect

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#585]
![bildschirmfoto 2016-05-11 um 11 58 59](https://cloud.githubusercontent.com/assets/700119/15177339/c5241416-176f-11e6-8b3d-8ff89f64734b.png)

1.) Open a Folder with objects
2.) try to change elements per page
3.) xhr request does not change limit (stays at 25)

also reproducible on demo environment (tested with news objects).

**Comment by fashxp** [comment]
fixed in build 3774
