### ISSUE TITLE
Require_once in startup.php in RC2.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#586]
### Expected behavior 
Using "require_once" should work in custom /website/config/startup.php
  
### Actual behavior  
Using "require_once" in custom /website/config/startup.php send an HTTP 500 error 
If moving the same startup.php in  website/var/config, it works well.

### Steps to reproduce  
Create a startup.php in /website/config/ containing a require_once directive.

### Code example 
require_once...

**Comment by brusch** [comment]
Where is the file in require once located? 
In my case this works quite well? 

Thanks!

**Comment by Yivan** [comment]
I made some other test. In fact the HTTP 500 is send if there is an error in the file.
I just try on a blanck nightly build, copy the startup exemple to startup.php and just add at the all end:
`require_once 'nothing';`
(PHP 5.6, Windows 8)

It send a HTTP 500, with strange binary character on the screen. But it should send PHP errors...
Here is a screenshot:

![strange_error](https://cloud.githubusercontent.com/assets/9025839/15194509/81c91fbe-17c3-11e6-8bc3-e24e1f9d07f1.png)

**Comment by brusch** [comment]
Well, I don't think that this has something to do with pimcore, but with the PHP setup. 
What happens if you place the require_once in your index.php before the line `include_once("pimcore/config/startup.php")` ? The same? 

Maybe you can debug this for us, as I cannot see any issue here. 
Thanks!

**Comment by Yivan** [comment]
I made the test in index.php, and same problem. So it is my setup fault.

If i remove:

```
    <IfModule mod_filter.c>
        AddOutputFilterByType DEFLATE application/atom+xml application/javascript application/json \
            application/vnd.ms-fontobject application/x-font-ttf application/rss+xml \
            application/x-web-app-manifest+json application/xhtml+xml \
            application/xml font/opentype image/svg+xml image/x-icon \
            text/css text/html text/plain text/x-component text/xml text/javascript
    </IfModule>
```

from the .htaccess, i get no more the strange caracters.

With original .htaccess:
![original](https://cloud.githubusercontent.com/assets/9025839/15229118/e283d6ec-188f-11e6-9320-d18e867a9481.png)

With the same just removing the <IfModule mod_filter.c> directive from the original .htaccess:
![lines_removed](https://cloud.githubusercontent.com/assets/9025839/15229143/f788da4c-188f-11e6-8db1-1b76407884b8.png)

Seems this rules compress the output in cas of 500 error. Maybe there is something you can add on this rule so it doesn't compress the output in those case ?
