### ISSUE TITLE
[Email] Replace html2text binary

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#5868]
In https://pimcore.com/docs/6.x/Development_Documentation/Development_Tools_and_Details/Email_Framework/Pimcore_Mail.html stands:
`Optionally, you can use html2text from Martin Bayer for the generation of the text version by calling enableHtml2textBinary().`

The current version of this binary is from 2004. In the man page the author describes `html2text was written to convert HTML 3.2 documents. When using it with HTML 4 or even XHTML 1 documents, some constructs present only in these HTML versions might not be rendered.`

Could we replace it with something more modern like https://github.com/mtibben/html2text ?

**Comment by dpfaffenbauer** [comment]
If you gonna to refactor that, please create a Swiftmailer Plugin instead of the how Pimcore does it right now :)

**Comment by dpfaffenbauer** [comment]
or even better: we should propose moving from Swiftmailer to Symfony Mailer and create the plugin there ;)

**Comment by BlackbitNeueMedien** [comment]
Oh, stirred up a hornets' nest ;-)
I actually have no idea of Mailing libraries. I can only offer to integrate above mentioned html2text library to generate the text content in https://github.com/pimcore/pimcore/blob/aad294e482efbb97fb10490bc9a56755f82e54a0/lib/Mail.php#L893-L912

If the core team would only accept it as a Swiftmailer plugin or completely rewrite to Symfony Mailer, I cannot help much.

**Comment by dpfaffenbauer** [comment]
so much things todo ;) Maybe start with the refactor of the current solution, from there we can start to improve anyway

**Comment by brusch** [comment]
Symfony Mailer would be a topic for v7 (Symfony 3.4 unsupported). 
For me it would be ok to just replace the current solution with `html2text/html2text` - don't think it's absolutely necessary to invest too much time into a plugin that will be replaced soon anyway.

**Comment by solverat** [comment]
I'm with @brusch, this could be an all-in-one improvement for 7.0.0.
