### ISSUE TITLE
Width of the google map for geographic datas on object edition

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#588]
When editing geographic point, after searching the adress with the input, width is ok, as seen below:
![after_selecting_adresse](https://cloud.githubusercontent.com/assets/9025839/15193385/f8aec968-17bd-11e6-9571-acdbdaaa1395.png)

But after reloading the object, width is smaller as seen below:
![after_reloading_object](https://cloud.githubusercontent.com/assets/9025839/15193405/0626825c-17be-11e6-9c79-9bcab14b1ed0.png)

Maybe this problem is on polygon and other google map datas for object.

Thanks!

**Comment by brusch** [comment]
Thanks!
