### ISSUE TITLE
Add option to disable/setInterval of the notification polling

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#5881]
Every 30 seconds there is a request to /admin/notification/find-last-unread

This can make debugging extremely frustrating.

Please add an option to disable this or at least let me set the interval to a really high number.

**Comment by brusch** [comment]
You can run `clearInterval(pimcore["intervals"]["checkNewNotification"])` in your console to temp. disable the polling.

**Comment by aarongerig** [comment]
I would like to have the option to disable the notification polling on my dev environment as well. That would increase DX a lot.

**Comment by glaand** [comment]
How can i change the interval of the `find-last-unread` ?

**Comment by dkarlovi** [comment]
This would be a nice candidate for #8537.
