### ISSUE TITLE
Enable multiline on filter active popin for object folder.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#589]
As seen below, the popin displayed after clicking on the "Filter active" button, display online one line, so the end is missing.

![folder_filter](https://cloud.githubusercontent.com/assets/9025839/15193476/5fa264cc-17be-11e6-8886-45ab55e5db30.png)

It should display in multi line so it doesn't cut the sentence.

--- New feature idea ---
I was looking for reseting filter but don't find any direct button. Maybe instead popin those information (very technical for non-SQL axare people), it sould only reset the filters (and change the color of the button) ?
Actually the only way to rapidly reset filter i found is reloading the object folder, which is not as friendly than an ajax refresh of the table.

**Comment by brusch** [comment]
Can't see any problem there, ... works as expected: 
![image](https://cloud.githubusercontent.com/assets/142037/15205698/dc0d0d68-1819-11e6-8cb5-4f7593fdf71e.png)

Tested in demo.pimcore.org using the news objects.

**Comment by Yivan** [comment]
I confirm this is ok on my side now too (tested from the last v4 release).
Thanks.
