### ISSUE TITLE
CSRF Attach with an iFrame in Pimcore and a Post Form

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#5891]
Simple use case:

 - iFrame in Pimcore Admin
 - Form in that iFrame
 - On Submit: CSRF Attack

Why does Pimcore think and assume that this is a CSRF Attach? Why can't you use the default Symfony way of handling that?

**Comment by dpfaffenbauer** [comment]
BTW: I am aware of the config that excludes certain routes, but that is not a proper solution for that issue

**Comment by brusch** [comment]
> Why can't you use the default Symfony way of handling that?  

Because our use-case is a bit more complex. If you know how to do it the Symfony way without breaking everything and still keep it read- and maintainable -> PRs are welcome! 😉

> Why does Pimcore think and assume that this is a CSRF Attach?  

Please find the answer here: 
https://github.com/pimcore/pimcore/blob/ca75246d82fe1190ce2268767ace84f157b168d9/bundles/AdminBundle/EventListener/CsrfProtectionListener.php#L69

**Comment by dpfaffenbauer** [comment]
> Because our use-case is a bit more complex. If you know how to do it the Symfony way without breaking everything and still keep it read- and maintainable -> PRs are welcome! 😉

What is more complex? Others can do it as well, also with SPA....

**Comment by brusch** [comment]
Sorry, I can't remember the details. But like I said, if you know how do do it a better and more easy way, we're always happy to get contributions.

**Comment by dpfaffenbauer** [comment]
Might it cause you don't use Symfony Forms in Backend? That is where Symfony usually does the CSRF Check....

**Comment by brusch** [comment]
Probably. But to be honest, ExtJS forms in combination with Symfony Forms ... 🏃‍♂️💨

**Comment by dpfaffenbauer** [comment]
Honestly: Not true, it works, quite good actually. All Forms in CoreShop are Symfony Forms as well. It is quite cumbersome, cause you have todo things twice, but it is how it is. And it also works in combination with DataObject ClassDefinition Tags.

**Comment by brusch** [comment]
> It is quite cumbersome, cause you have todo things twice
Well, I like to keep things simple, but I'm happy that it works well for you. 👍😊

**Comment by dpfaffenbauer** [comment]
Simple? Forms a more simple than most of the Controllers in Pimcore. 

But yes, I can see where the "simplicity" in Pimcore comes from....

**Comment by brusch** [comment]
... 😉

**Comment by iibs** [comment]
How should one approach this issue, if Symfony way is not supported? I want to have a custom settings controller in admin, and so far my research has led me to iFrame + Symfony form solution, but if that's not going to work, what should I change?

Should I scratch the Symfony form and just make the form in my Twig template, and send data through AJAX? Or is there another way to make admin view addition to iFrame solution?
