### ISSUE TITLE
Class Object Definition is Missing

### ISSUE THREAD

**Issue by victorfonseca** [pimcore/pimcore#5892]
### Expected behavior
Create a new Object
### Actual behavior
Pimcore Command can find Object class definition, but the PHP class is in the folder DataModel/
### Steps to reproduce
Using latest version of pimcore bitnami install local machine
Create a new class or use existing one like Car
Create a new Command and create a new object from the class

**Comment by victorfonseca** [comment]
<?php

namespace AppBundle\Command;

use Pimcore\Console\AbstractCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Pimcore\Model\DataObject;

class ProductImportCommand extends AbstractCommand
{
    protected function configure()
    {
        $this
            ->setName('app:awesome')
            ->setDescription('Awesome command');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $object = new DataObject\Car();

        $object->setKey("Car Test");
        $object->setParent(1073);
        $object->setPublished(true);
        $object->save();
    }
}

ERROR     [pimcore] Exception: Class definition with name  or ID CAR does not exist in

**Comment by brusch** [comment]
Sounds like a specific problem with the Bitnami image, it's not reproducible on our demo.
