### ISSUE TITLE
Route collision when unpublished document has same name as asset folder

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#5893]
# Bug Report

When you have an unpublished document named "/test" and an asset under "/test/123.jpg" you cannot access a thumbnail of this image.

### Expected behavior

Thumbnail image should be shown

### Actual behavior

Exception thrown

### Steps to reproduce
1. Create thumbnail definition "abc"
2. Create document named "test" under "/", ensure it is unpublished
3. Create asset folder "test" under "/"
4. Upload image 123.jpg to asset folder "/test"
5. Create this little script test.php
```php
$asset = \Pimcore\Model\Asset::getByPath('/test/123.jpg');
echo $asset->getThumbnail('abc')->getPath());
```
6. Run script via `bin/console pimcore:run-script test.php`, should output something like `/test/image-thumb__410__abc/123.jpeg`
7. Open this URL via browser (and prepend domain name), e.g. https://demo.pimcore.fun/test/image-thumb__410__abc/123.jpeg

Now you get an exception thrown. 
If you publish the document "/test", it works and you get the thumbnail shown. 

PS: Beware that if you again unpublish the document and try to load the URL it still works. This is because then the generated thumbnail file exists and thus gets directly served without PHP being involved.

**Comment by brusch** [comment]
Related to #2704

**Comment by BlackbitNeueMedien** [comment]
Hmm, as @dvesh3 pointed out in #2826 the problem is in https://github.com/pimcore/pimcore/blob/12ca8e1fe84527111e54812ee3b2b6d90137fb5d/models/Document/Service.php#L542-L575

Is it actually possible to tell here whether the URL should point to a document or an asset? I think not, so the solution in https://github.com/pimcore/pimcore/pull/2826/commits/ba175d3bcd6a584fd3a059a4f188825c1fdb7978 is pragmatic. Or does someone have an idea how to solve this in a cleaner way?

**Comment by brusch** [comment]
@BlackbitNeueMedien #5893 should fix the issue, simple but effective it seems 😊
Let me know if this works for you.
