### ISSUE TITLE
System Breaks if we maximize the search popup window.

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#5897]
#Steps to reproduce

- Open Object Search from the left toolbar.
- Search any object.Make sure you select values from the drop-down.Lets search car of type 'object' and class-name is 'car'.

![search ](https://user-images.githubusercontent.com/21308144/75223774-2f32ec00-57cd-11ea-9397-ba6c45ecede3.png)

- Maximize the window (move to tab).
![move to tab](https://user-images.githubusercontent.com/21308144/75223762-27734780-57cd-11ea-9e39-b638f3106b0b.png)

- Now try to do another search,change the values of drop-down or close the tab.System breaks if we try to close the tab.

![system breaks](https://user-images.githubusercontent.com/21308144/75223776-30fcaf80-57cd-11ea-996a-667a6051b3ff.png)

Same is the case with document and object search.

**Comment by weisswurstkanone** [comment]
sounds like https://github.com/pimcore/pimcore/issues/1016

**Comment by neha04** [comment]
Yeah!! If we know the functionality will break so why are we providing this? Can't we just provide a search popup window or the tab one.There must be some reason for this...

**Comment by brusch** [comment]
Let's change it the way that we open the search directly as a tab, I guess that's reasonable.
