### ISSUE TITLE
Instead of column name ext element name is shown in Bar Graph Report

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#5898]
Instead of column name ext element name is shown in Bar Graph Report

![Screenshot from 2020-02-25 12-23-07](https://user-images.githubusercontent.com/21308144/75223973-9a7cbe00-57cd-11ea-8b48-f8ca4c79c3b5.png)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
