### ISSUE TITLE
Login page in other languages

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#590]
Hello,

To improve consistent user experience, starting from the login page, it would be great to be able to define a default language. So people using pimcore only in one language can have a login page in the same language and have a all-in-one native language solution for instance.

Another option would be to choose the langage automaticaly from the navigator language.

So this would maybe be a system option with a unique choice beetween:
- English (default)
- Automatic (based on navigator settings)
- Forced (list of language)

Translation for this page could be managed in the Admin translation maybe.

Hope it make sense! Thanks.

**Comment by brusch** [comment]
Language on login page is now determined from the user agent setting.
