### ISSUE TITLE
Pimcore Date at backend is one day behind 

### ISSUE THREAD

**Issue by shashi5678** [pimcore/pimcore#5900]
Hello,

Whenever i am trying  to save a date in date field it's storing  one day behind.
I am also attaching the screen-shots with mail.

problem is that my users is in two different timezone.
So for the same timezone user it stores  data correctly but in diff timezone it is always one day behind.

[date_issue.zip](https://github.com/pimcore/pimcore/files/4249121/date_issue.zip)

**Comment by brusch** [comment]
I guess this is because Pimcore stores a unix timestamp in the database, so this behavior is kind of intentional. 
You can try to use 
![image](https://user-images.githubusercontent.com/142037/75240061-05c19280-57c4-11ea-92cb-3b3a1ada6a40.png) in the field definition, I'd assume that fixes your issue.

**Comment by shashi5678** [comment]
Hi,
our application need only date. Ex: First Date Of Delivery and Release Date 
is it possible throu

**Comment by brusch** [comment]
Like I said, please try the DATETIME setting on the field 😊

**Comment by brusch** [comment]
Did changing the field to DATETIME fixed your issue? 
Thanks for your feedback!

**Comment by shashi5678** [comment]
Hi ,
Yes it is working with datetime but  it would have great if it could work with date as well.
As you mentioned above it's intentional functionality. If you want can you elaborate what was the reason ? It will help. in any how i have to  write custom code to handle this my application.

**Comment by brusch** [comment]
The behavior with the timestamp is intentional, as there are use-cases where the timezone shouldn't matter.

**Comment by shashi5678** [comment]
after testing we noticed that even from India if you select time before 3:30 AM for any date and timezone is set as "Europe/Helsinki" . it stores date a day behind in backend.
