### ISSUE TITLE
[DataObjects] Refactor multiple assignments check for Advanced relation types breaks Pimcore

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#5902]
https://github.com/pimcore/pimcore/pull/5852#issuecomment-590774419

Local fix: 
https://github.com/pimcore/pimcore/blob/b22960db68b4f30b468c769071f0128163fba9ba/models/Element/Service.php#L543

Returning `uniqeid` to sort of prove what is going wrong

> Besides that, the policy should be that if you find bugs then contribute a test covering the issue.
This would also help others.
> Thanks a lot.

I have no intention of creating a PR, that is not my responsibility. I already spent loads of hours in creating loads of plugins for FREE for the community and also supporting the community in many other ways. Introducing another bug in another release should be and is your responsibility to fix.

Just appreciate the fact that I already spent couple of hours investigating what is going on and not demanding PR's from the reporter!

Also, changing behaviour and not introducing new tests, is irresponsible for a product this size. And as you see, it breaks things not having them. Like with the release of 6.4 and now 6.5 as well.

**Comment by brusch** [comment]
@dvesh3 in my opinion the following should fix the issue: 

- `\Pimcore\Model\Element\Service::getElementHash()` should return `null` in case building a hash isn't possible. 
- ignore objects with no ID
- ensure objects without an ID doesn't cause any weird issues in case the relation owner object gets saved (should be just ignored as well for the time being -> BC break). 

We should also move `\Pimcore\Model\Element\Service::filterMultipleElements` to `\Pimcore\Model\DataObject\ClassDefinition\Data\Relations\AbstractRelations` as a non static method, this is the place where it belongs to, right 😊
