### ISSUE TITLE
Custom grid as favorite not saved

### ISSUE THREAD

**Issue by FredoVelcro-zz** [pimcore/pimcore#5907]
In backend, left "Data Objects" panel,  I have objects (e.g. : users class) under a "Contacts" folder.
When i click this folder and create a custom grid, i save it, and then click "As favorite".
The record is not created in database (gridconfig_favourites table empty) and when i reopen/refresh my folder, the grid is still the default one.

Found the error here : 

https://github.com/pimcore/pimcore/blob/309dc5b4544370816c4e8138a5d05db90c0e34f9/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php#L939

It generate an hidden exception : 

```text
An exception occurred while executing 'select * from gridconfig_favourites where ownerId = 2 and classId = 'CG_User' and searchType = 'folder' and objectId != 3388 and objectId != 0 and type != 'object'':

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'where clause'
```

**Comment by dvesh3** [comment]
@FredoVelcro looks like some are migrations missing on your instance.

please check if this migration is executed:
https://github.com/pimcore/pimcore/blob/bfc6235fb7f3d965f6c33acde235fa561aace1af/bundles/CoreBundle/Resources/migrations/Version20191015131700.php

Command for checking migrations status `bin/console pimcore:migrations:status -s pimcore_core --show-versions`

**Comment by dvesh3** [comment]
Hello, @FredoVelcro! still facing the issue?

**Comment by matchii** [comment]
I had exactly the same problem, executing core migration 20191015131700 fixed it.
