### ISSUE TITLE
Advanced Many To Many Objects metadata column names  get "strtolowered" 

### ISSUE THREAD

**Issue by romainbessugesmeusy** [pimcore/pimcore#5908]
# Bug Report

I think this isn't supposed to be a feature, but if it's the case please forgive me. 

### Expected behavior & actual behaviours

As an admin, when I design DataObjects and create an Advanced Many To Many Object relation property, I want my metadata column names to take into account the correct capitalization of the names I input. 

For example, when I type `productionCost`, I expect that the name displayed and saved in the database to be `productionCost`, and not `productioncost`. I also expect the Metadata object to have a magic getter `$metadata->getProductionCost()` instead of `$metadata->getProductioncost()`.

### Steps to reproduce

DataObject > Classes > Add an Advanced M2M relation and create a column with a custom capitalization. Save the Class and reload definition.

**Comment by weisswurstkanone** [comment]
same for Advanced Many to Many Relations (not only objects)

Lines to check:

https://github.com/pimcore/pimcore/blob/00db04cdae1d506ba0bdee8794e5b93f232e4137/models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php#L851

https://github.com/pimcore/pimcore/blob/dd9fc1a906b7b6eed72af8ebffa9733baf1f9708/models/DataObject/Data/ObjectMetadata.php#L96-L114

In addition:
Max key length check currently missing.

**Comment by weisswurstkanone** [comment]
Can't think of a good reason why we should restrict it to lower case.

**Comment by weisswurstkanone** [comment]
Guess this would be a BC break then
