### ISSUE TITLE
areablock.php: ucwords() filled with 2 params

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#591]
since commit https://github.com/pimcore/pimcore/commit/e07b9ec4e5bc8ca64f5cb94c41550ad89a24c583, the method `ucwords` is called with wrong amount of parameters:

`Warning: ucwords() expects exactly 1 parameter, 2 given.`

**Comment by brusch** [comment]
Thanks.
The 2nd parameter of ucwords() is supported since 5.5.16, so I guess you're using a version lower than that. I've patched this, since we still have support for 5.5 in version 4.
