### ISSUE TITLE
[Improvement] Simplify comprehension of paste feature for CMS.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#5915]
Hello,

This issue is more an experience return. I think I know how works Pimcore, use it during several years. But a few days ago, i had to do a copy and paste of a CMS directory... and when i saw the menu, even me was asking me what is the good option to choose... and I was thinking "ho poor cms content user who manage the documents, they would be lost" : ))

Now Pimcore got this:

![image](https://user-images.githubusercontent.com/9025839/75398732-c9448280-58fa-11ea-8d28-eb6bde1531a5.png)

and this:

![image](https://user-images.githubusercontent.com/9025839/75398771-e0837000-58fa-11ea-8d96-71a36de1ee73.png)

No more than 13 choices.
Like for coding where at some times we think some methods need refactoring, maybe the way paste feature work for enduser should be rethinking.

I don't have any solution, it could be less options and having an intermediate popin where we can check the options (language, updating refs, etc...) with some helpfull hints because not everyboding can remember what each one of those 13 action do. For exemple in the popin there will be checkbox so we can check:
- recursive (?)
- update reference (?)
- with inheritance (?)
- langage (?)

The (?) will provide some help/tooltips so the good options are checked.

It 's just my point of view, as Pimcore user. I manage to use it like this, but for enduser it seems complicated.  The CMS feature is so easy (drag asset, type code directly in the page, etc.) and a very strong point of Pimcore over other CMS, but the paste feature on the other side is less easy/comprehensible to use I think. Should i paste as langage variant with inheritance updating references : ) Forgot recursive in the mix.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
