### ISSUE TITLE
Pimcore Date at backend  With datetime Field 

### ISSUE THREAD

**Issue by shashi5678** [pimcore/pimcore#5916]
after testing we noticed that even from India if you select time before 3:30 AM for any date and timezone is set as "Europe/Helsinki" . it stores date a day behind in backend.

Please refer this for more details

https://github.com/pimcore/pimcore/issues/5900

**Comment by brusch** [comment]
Please see https://en.wikipedia.org/wiki/Unix_time 
And please don't open new tickets if there are already existing ones ... #5900
