### ISSUE TITLE
[DataObject] check of sql backticks are missing on setOrderKey

### ISSUE THREAD

**Issue by albertmueller** [pimcore/pimcore#5927]
# Bug Report

```php
$myStockList->setOrderKey( '`object_25`.o_modificationDate');
```
runs into a error, because the check of sql backticks is missing.

**Comment by brusch** [comment]
Call `$myStockList->setOrderKey( '`object_25`.o_modificationDate', true);` 😉

**Comment by albertmueller** [comment]
@brusch oh thx, u're right. but i would recommend to adapt the methods setOrderKey and setGroupBy?
