### ISSUE TITLE
Created Role/User doesn't have access to the whole plattform

### ISSUE THREAD

**Issue by nguyenjagi** [pimcore/pimcore#5928]
I created some roles for pimcore and followed the instructions, but when the Users  are logged in they can't see anything but their own profile.

![grafik](https://user-images.githubusercontent.com/50870782/75548280-30faea80-5a2d-11ea-902f-aff2bb50b701.png)

that are the permissions I gave to the Roles and also to the users
![grafik](https://user-images.githubusercontent.com/50870782/75548402-78817680-5a2d-11ea-8bd6-4a6c06fb7533.png)

I think I made big mistake somewhere but couldnt figure out where

**Comment by brusch** [comment]
This issue tracker is not for support!
Use 
https://talk.pimcore.org/
http://gitter.im/pimcore/pimcore
instead. Thanks!
