### ISSUE TITLE
setUnpublished for list don't work in Release v4.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#593]
We just updated a project and noticed that $this->document->getChilds() send back non published document.

To reproduce:
In www\website\controllers\DefaultController.php

Add this code at the begining of default action:
```
            $list = new Document\Listing();
            $list->setUnpublished(false);
            $list->setCondition("parentId = ?", 3);
            $list->setOrderKey("index");
            $list->setOrder("asc");
            $childs = $list->load();
            foreach ($childs as $child) echo $child->getId()."<br>";
            die();
```

On the backend, desctivate /en/basic-examples/html5-video (ID 7), il will always be printed in the list of ID displayed in the frontend by the code in defaultController.

I try to clear cache, check the Pimcore code... seems to be deep in the condition modeling i think.
Maybe same problem for asset/object (don't test it).

Thanks.

**Comment by gallexme** [comment]
Same Problem at 3.1.1
