### ISSUE TITLE
[Ecommerce new feature] Stripe.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#5934]
Hello,

Is there any reason stripe is not in the default available payment methods ? It is one of the most used one, and is particularly usefull on marketplace subject, transverse retribution for partners. This is a very powerfull solution for this and very well-know.

Purpose of this issue is to add it to the stack of payment providers availble to the Pimcore e-commerce. I think it will bring help and values to it.

Thanks.

**Comment by fashxp** [comment]
PRs are welcome ;-)

**Comment by brusch** [comment]
Obsolete due to #6805
