### ISSUE TITLE
[Imporvement] Database.yml format and with empty password add '' or ~ during install

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#5936]
Hello,

I was just trying lint/format on projects, and i found that Prettier (https://prettier.io/) breaks the database.yml file (Yaml formatting) in case of empty password. It reformat the yaml like:

```
doctrine:
    dbal: { connections: { default: { host: localhost, port: 3306, user: myuser, password: , dbname: mydb } } }
```

to:

```
doctrine:
  dbal:
    {
      connections:
        {
          default:
            {
              host: localhost,
              port: 3306,
              user: myuser,
              password,
              dbname: mydb,
            },
        },
    }
```

Please see: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATCYYCcCWU5IA6UABGSagEYCGANkicCZFPpjtAM4NOpwBm1AK60YPEgAsInMSVoY6UmQBoSABwhZZAZm0AGAGyqhnOFgYBbAJ4mzqtdU6cA7ptQNVVKNQsES1qhIAX2DgkGUQCDUYDihOZFBqLCwIZwAFJIR4lGoANwgcVHCQSixqMABrOBgAZQcwPABzZGwhOAiJGAtaAHUJHHhOergarIGcXIGrZHAnYrxTLTSyxotqZEFaUwiAK04ADwAhMsrqmp84ABk8OA26bZA9-Zqm2jgARSEIeDut9pAHFhFjMrD5aMU1LhYD1CjAJMgABx6CKQ6RwHplNQzSFwRa5W4RACOX3gyyi2RAjgAtPg4HwihEsHBiTgmctqKt1khNg9TBYcC0sG0IpxXh8Sbdufd-jBqJQYag4cgAEwRbDUHC0JoAYQgFjWMyg0AJIFsABU5dkef9cm0AJJQPiwGpgXDRACCjpqMCsb1+piCQSAA

As you can see the password line is transformed to `password,`, which make simply symfony no more work :)

**Solution: during install process, if password is empty use ~ or ''.**

I get a transversal warning as after prettier transformation (using `php bin/console lint:yaml`), Symfony send `Support for mapping keys in multi-line blocks is deprecated since Symfony 4.3 and will throw a ParseException in 5.0 at line 16.`. **Maybe the database credential form should be adapted by the way to use another format like `mysql://db_user:db_password@127.0.0.1:3306/db_name`** ?

I know it is really a side case, but as all the other Pimcore yaml files get linted perfectly and this was the only one it seems, this improvement could be good.
database.yml could be easily excluded from prettier formatting, so this is not critical. But as more and more prettier is used, and this is a central file make those small changes could be good for prevention.

Best regards.

**Comment by brusch** [comment]
Thanks for reporting! 
However, that's really a mega edge-case. We're happy to merge a PR for that, but we're not going to fix that ourselves. 
Thanks for your understanding.

**Comment by Yivan** [comment]
Yes sure, this is edge case like you said ; )
If i had time i will try to look for a PR, but this is not urgent.
Thanks.
