### ISSUE TITLE
Document Preview issue with spreadsheets - No scaling option in libreoffice Library.

### ISSUE THREAD

**Issue by abhisheksingh-pimcore** [pimcore/pimcore#5937]
# Feature Request

## Feature description
 **Document Preview issue with spreadsheets. [  Pimcore Version: 5.2.3 ]**
I want to generate PDF previews with "Scale to fit" mode so that content will be scaled to fit single page. We can do that manually (can refer this https://stackoverflow.com/a/19947539 ) through Menu Formatting -> Page ->Sheet ->Scale Scaling mode. But I don't want user interference during conversion of XLS to PDF.

**Proposed Solution : -** 
 We can achieve this through applying macros on that specific XLSX on run time and after than we can execute PDF conversion command. The steps I followed to implement this solution mentioned below.

**File path : - /PIMCORE-ROOT/pimcore/lib/Pimcore/Document/Adapter/LibreOffice.php**

**Step 1 :- Store a macro on server.**
                          in my case I have stored here (/opt/libreoffice/presets/basic/Standard/Module1.xba).
                          Content of Module1.xba is

            <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE script:module PUBLIC "-//OpenOffice.org//DTD OfficeDocument 1.0//EN" "module.dtd">
            
            <script:module xmlns:script="http://openoffice.org/2000/script" script:name="Module1" script:language="StarBasic">REM  *****  BASIC  *****
            Sub FitToPage
              Dim document As Object, pageStyles As Object
              document   = ThisComponent
              pageStyles = document.StyleFamilies.getByName("PageStyles")
              For i = 0 To document.Sheets.Count - 1
               Dim sheet As Object, style As Object
               sheet = document.Sheets(i)
               style = pageStyles.getByName(sheet.PageStyle)
               style.ScaleToPagesX = 1
              Next
              On Error Resume Next
              document.storeSelf(Array())
              document.close(true)
            End Sub
            Sub Main

            End Sub
            </script:module>

 **Step 2:- Apply the above macro on xls file through below command.**

            $cmd = 'export HOME=/var/www &&  /opt/libreoffice/program/soffice --headless --nologo --nofirststartwizard --norestore  /home/usr/demo.xls  macro:///Standard.Module1.FitToPage';

 **Step 3 :- Generate Pdf after applying macro through command line.**

            $cmd = 'export HOME=/var/www && /opt/libreoffice/program/soffice --headless --nologo --nofirststartwizard --norestore  --convert-to pdf:writer_web_pdf_Export  --outdir  /home/usr/  /home/usr/demo.xls';

**NOTE : -** This implementation required changes in PIMCORE Core files. Please suggest if there is any other way to implement this feature or I can create a pull request for changing in core file?

**Comment by brusch** [comment]
I think an event is the way to go in this case. As this is really a very specific use-case we're not going to implement this in the core. 
Please create a PR that introduces an event, that allows to control the conversion process. 
Thanks a lot!
