### ISSUE TITLE
ID popin slow down navigation (need to wait 4sec sometimes so it disapear).

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#594]
On firefox when opening a document tree, the ID popin cover the immediate child. And thus it is needed to wait it deasapear so we can click on the next cross... and same after... so navigation is not user fiendly just because of this popin.
On Chrome it seems to have more left padding, so we can click on the + to deploy the children and click the document name.

Here is a firefox capture, form the online demo (last firefox version -> 46.0.1, Windows 8.1).
Balck arrow (bad drawing by me) is the current mouse cursor position and pointing the cross just clicked to exapand the childs. As you can see introduction is hidden behind the popin and need to wait a few second to deasapear so i can go on to expand introduction children or event edit introduction document:
![navigation](https://cloud.githubusercontent.com/assets/9025839/15252595/faf6012e-192e-11e6-9e07-6f22bc978ac6.png)

Maybe some more padding right on firefox, or the ability to desctivate it from system config.

Thanks!

**Comment by weisswurstkanone** [comment]
Not sure if I understand this correctly. As you see in the screencast the tooltip moved in the same way as the mouse cursor.
[2016-05-25_15-53-48.zip](https://github.com/pimcore/pimcore/files/282102/2016-05-25_15-53-48.zip)

**Comment by Yivan** [comment]
You are right. I just try on the computer i used now, and no problem.
I don't have the computer i used near me. I will try on it when i can, but the popin wasn't moving with the mouse... strange maybe something about my other computer configuration.
Right now you can close the issue, and if i got problem with popin following the mouse on other computer i will open an issue specific about his (and reference to this one).
Thanks.
