### ISSUE TITLE
data mismatch errors

### ISSUE THREAD

**Issue by ramya343** [pimcore/pimcore#5948]
# Bug Report

### Code example
```php
// your code
```

# Feature Request

**Comment by ramya343** [comment]
data loaded into portal,below screenshot is for your reference
![image](https://user-images.githubusercontent.com/61545414/75747549-43359b00-5d43-11ea-9378-5861ee93aada.png)

please help me with this?

**Comment by brusch** [comment]
Please stop creating such unqualified issues. This is the last reminder!
