### ISSUE TITLE
[Ecommerce] Refactor AbstractOrderItem

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#5954]
see comment https://github.com/pimcore/pimcore/pull/5935#issuecomment-593369731

"...
@weisswurstkanone I know one concrete case for a BC (see #5720, file bundles/EcommerceFrameworkBundle/Model/AbstractOrderItem.php) There we have a TODO in code.

We can add to the v7.0 list to complete phpstan level 2/3 ;)

I find a list in the 0.12 release notes (https://medium.com/@ondrejmirtes/phpstan-0-12-released-f1a88036535d):
..."

**Comment by weisswurstkanone** [comment]
Hi @blankse , this is already done via https://github.com/pimcore/pimcore/pull/7553, right? Thx!

**Comment by blankse** [comment]
@weisswurstkanone Yes it's done already

**Comment by weisswurstkanone** [comment]
Merci! 👍
