### ISSUE TITLE
[Documents] Document::hasElement() returns false for inherited elements

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#5959]
# Bug Report

### Expected behavior
`Document::hasElement()` should return `true` for inherited elements

### Actual behavior
`Document::hasElement()` returns `false` for inherited elements

### Steps to reproduce
1. Create document with editable elements
2. Copy document from 1. and set content master document to 1.
3. In the controller of both documents `Document::hasElement()` returns `true` for the original document but `false` for the inherited document.

I do not know if this is really a bug as the copied document does not really **have** the element in the sense of being the owner of the element but it is an unexpected behaviour that `Document::hasElement()` returns `false` but you actually can get the element via `Document::getElement()`.

**Comment by nspacex** [comment]
Hi,
this change seems to lead to an infinite loop as soon as DocumentTargeting / TargetingGroups comes into play. I haven't really looked at it yet but it seems that the getElement (Document\TargetingDocument, Document\PageSnippet) method is getting a "problem". 
BG Erik
