### ISSUE TITLE
[Elements] Transaction retry should be only performed if deadlock occurs

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#5966]
See: 
https://github.com/pimcore/pimcore/blob/d1485ff9d2b263be9bccb2a1fcd43b59734be8c5/models/DataObject/AbstractObject.php#L645
https://github.com/pimcore/pimcore/blob/d1485ff9d2b263be9bccb2a1fcd43b59734be8c5/models/Asset.php#L546
https://github.com/pimcore/pimcore/blob/d1485ff9d2b263be9bccb2a1fcd43b59734be8c5/models/Document.php#L440

I think if would make sense to just `catch` if the exception is of type: `\Doctrine\DBAL\Exception\DeadlockException` all other exceptions shouldn't be catched at all.

**Comment by dvesh3** [comment]
resolved by #5984
