### ISSUE TITLE
Navigation Cache custom Lifetime

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#5972]
I think it would be useful to define a custom Lifetime for Navigation Caching 
https://github.com/pimcore/pimcore/blob/master/lib/Navigation/Builder.php#L116

and also to set in
https://github.com/pimcore/pimcore/blob/master/lib/Templating/Helper/Navigation.php#L83

**Comment by andreas-gruenwald** [comment]
The problem is that currently the navigation cache has an infinite lifetime, which is most probably not wanted.
By adding an additional ``lifetime`` parameter to the ``buildNavigation`` method of the navigation helper, the developer can pass a custom lifetime.
