### ISSUE TITLE
[ECommerce] add in_preparation_queue index

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#5997]

**Comment by andreas-gruenwald** [comment]
Proably compare and add

```SQL
ALTER TABLE ecommerceframework_productindex_store_elastic ADD INDEX `in_prep_idx` (`in_preparation_queue` ASC, `tenant` ASC)',
```

```SQL
ALTER TABLE ecommerceframework_productindex_store_elastic ADD INDEX `productindex_crc` (`tenant` ASC, `crc_current` ASC, `crc_index` ASC, 
                `worker_timestamp` ASC)',
```

to https://github.com/pimcore/pimcore/blob/bbb4b30f705c3f7cf50bf0b0820d7d5108a3c28e/bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php#L56 and migrations.

**Comment by weisswurstkanone** [comment]
https://github.com/pimcore/pimcore/blob/bbb4b30f705c3f7cf50bf0b0820d7d5108a3c28e/bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php#L56

**Comment by andreas-gruenwald** [comment]
@weisswurstkanone  I created a pull request. May you please add the related line to the migrations, or send me the link to the related file so that I can add it on my own?

**Comment by brusch** [comment]
@andreas-gruenwald to generate a migration just run: `./bin/console pimcore:migrations:^Cnerate -s pimcore_core` 
This will generate a migration class in `bundles/CoreBundle/Resources/migrations/` , then just add this file to the Git repo and implement the `up()` and `down()` method 😊
Example: https://github.com/pimcore/pimcore/blob/master/bundles/CoreBundle/Resources/migrations/Version20190102153226.php

**Comment by andreas-gruenwald** [comment]
@brusch done. https://github.com/pimcore/pimcore/pull/6006/files
