### ISSUE TITLE
Error when saving object that has relation with a Classification store and has a empty value set

### ISSUE THREAD

**Issue by michel-paiva** [pimcore/pimcore#6000]
Guys I am having some trouble with classification store because it keeps throwing some undefined index errors, first one I solved with this PR: https://github.com/pimcore/pimcore/pull/5896
But I think that was just a symptom, the problem is when some empty value is passed to the function 
setLocalizedKeyValue() this lines https://github.com/pimcore/pimcore/blob/214e7db846ff0b59c4af9211573215cdd81a502c/models/DataObject/Classificationstore.php#L222 goes and unset everything.

This causes some problems, for example in the save validation when some language is passed the line https://github.com/pimcore/pimcore/blob/214e7db846ff0b59c4af9211573215cdd81a502c/models/DataObject/Classificationstore.php#L381 throws an undefined index error, because it thinks that the index will be there for sure.

Now my question is, do we really need to unset everything if the value is empty? Because in my opinion if I don't want this field in my object anymore I would just delete the relation between the key and the group, and if I am passing an empty value to be set I really mean it, I want a empty value to be on the field, I don't want it to be unset and cause all this trouble.

**Comment by brusch** [comment]
@weisswurstkanone fixed by #6034 ?

**Comment by weisswurstkanone** [comment]
Manual testing was successful.
