### ISSUE TITLE
[Data Object Listings] Filter by workflow state

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#6008]
It would be nice to add a method to Data Object Listing classes to filter by object's workflow state. So we would need to add a join on `element_workflow_state` table but I currently do not see a way to do so. Is this already possible?

**Comment by fashxp** [comment]
You can use a marking store that stores workflow places to data object fields

**Comment by BlackbitNeueMedien** [comment]
Can you please explain a bit more? I already have a workflow as described in https://pimcore.com/docs/5.x/Development_Documentation/Workflow_Management/index.html with 
```yaml
marking_store:
    type: state_table
```

This workflow supports `Pimcore\Model\DataObject\MyClass`. Now I want to create a Listing via `$listing = Pimcore\Model\DataObject\MyClass::getList()` and filter the returned objects of this listing by a certain workflow state. Is this possible?

**Comment by fashxp** [comment]
Have a look [here](https://pimcore.com/docs/6.x/Development_Documentation/Workflow_Management/Marking_Stores.html#page_single-_-state)

You can configure, that the workflow uses a dataobject field for storing places ... Then you can use standard pimcore functionality for filtering

**Comment by BlackbitNeueMedien** [comment]
Thanks, that is what I was looking for.
