### ISSUE TITLE
Document Adding and Object Adding does not work after upgrading to Pimcore 4

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#601]
### Expected behavior 
Clicking Add Page in the page tree should bring up a dialog and after confirming the dialog, the page should be added.
Same goes for adding object. After inserting the object key, object should be added.
### Actual behavior  
Adding the page to the tree does cause this error:
> Status: 404 | Not Found
> URL: /admin/document/add/
> Params:
> -> key: test
> -> name: test
> -> title: 
> -> type: page

Adding the object does cause this error:

> Status: 404 | Not Found
> URL: /admin/object/add
> Params:
> -> elementType: object

### Steps to reproduce  
Update from 3.1.1 to 4.0. Enable ExtJS 6 (Switching to ExtJS 3.4 on the same installation does enable the document and object adding - no errors on 3.4).
Tests run on Windows Server 2012 and 2012 R2. Recent .htaccess was converted to web.config in case and should contain any changes.

Nothing appears in php error log or in debug log. Editing pages or objects does work fine. Adding assets does work too. It seems to be an issue with ExtJS 6. Tested with Firefox 46.0.1.

**Comment by brusch** [comment]
I don't think this is caused by ExtJS, since the response code or /admin/document/add is 404. 
Please open /admin/document/add/ in your browser (without any parameter) and see what happens. The expected result should be a PHP error `Call to a member function isAllowed()  ...` if you're still getting an 404 you have to debug this on your system.

**Comment by brusch** [comment]
Btw. we're not officially supporting Windows and IIS, but we're always happy to include improvements. We cannot test or debug issues on this system, so we are dependent on your inputs and pull-requests. 
Thanks for your understanding. 

In your case I'm pretty sure that there's a mistake in the web.config and that the request to /admin/document/add isn't passed to PHP properly, because otherwise you won't get a 404.

**Comment by Cruiser13** [comment]
If I do open /admin/document/add/ directly I'll get the following error:
Fatal error: Call to a member function isAllowed() on null in C:\pimcoredomain\pimcore\modules\admin\controllers\DocumentController.php on line 125

Switching from ExtJS 6 to 3.4 solves my issue so I'd guess it's a ExtJS issue.

**Comment by brusch** [comment]
Ok, but the 404 makes absolutely no sense :-|
It can't be an ExtJS issue, since version 4 works well on many systems, eg. on our demo and many other systems out there.

What's in the network panel of the browser dev-tools? Anything interesting?

**Comment by Cruiser13** [comment]
I debugged with firebug. The request (on the same installation) with ExtJS 3.4 looks like this:

> http://example.com/admin/document/add/?_dc=123456789&key=testing&name=testing&title=&type=page&docTypeId=&index=4&parentId=1

If I do the same thing with ExtJS 6 it'll look like this:

> http://example.com//admin/document/add/?_dc=123456789&key=testing&name=testing&title=&type=page&docTypeId=&sourceTree=%5Bobject%20Object%5D&sourceTree=pimcoretreeview-1114&sourceTree=true&sourceTree=&sourceTree=function%20()%7B%7D&sourceTree=true&sourceTree=function%20()%7Bvar%20g%3Dthis%3Bg%5Bc%5D%3Dtrue%3Bdelete%20g%5Bb%5D%3Bg%5Bd%5D(g.config%5Ba%5D)%3Bdelete%20g%5Bc%5D%3Breturn%20g%5Bb%5D.apply(g%2Carguments)%7D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=false&sourceTree=false&sourceTree=true&sourceTree=true&sourceTree=false&sourceTree=pimcoretreeview&sourceTree=%5Bobject%20Object%5D&sourceTree=&sourceTree=false&sourceTree=&sourceTree=%5Bobject%20Object%5D&sourceTree=&sourceTree=true&sourceTree=false&sourceTree=false&sourceTree=%5Bobject%20Object%5D&sourceTree=&sourceTree=%5Bobject%20Object%5D&sourceTree=&sourceTree=x-tree-view&sourceTree=true&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=true&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=0&sourceTree=false&sourceTree=%5Bobject%20Object%5D&sourceTree=x-tree-view&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=table.x-grid-item&sourceTree=%5Bobject%20Object%5D&sourceTree=true&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=data-savedtabindex-pimcoretreeview-1114&sourceTree=&sourceTree=&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=4&sourceTree=true&sourceTree=function%20()%7B%7D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=&sourceTree=%5Bobject%20Object%5D&sourceTree=0&sourceTree=&sourceTree=default&sourceTree=default&sourceTree=&sourceTree=&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=true&sourceTree=%5Bobject%20Object%5D&sourceTree=true&sourceTree=%5Bobject%20Object%5D&sourceTree=0&sourceTree=%5Bobject%20Object%5D&sourceTree=8&sourceTree=true&sourceTree=0&sourceTree=false&sourceTree=2&sourceTree=false&sourceTree=%5Bobject%20Object%5D&sourceTree=true&sourceTree=2&sourceTree=false&sourceTree=&sourceTree=&sourceTree=&sourceTree=%5Bobject%20Object%5D&sourceTree=&sourceTree=%5Bobject%20Object%5D&sourceTree=%5Bobject%20Object%5D&sourceTree=false&sourceTree=&sourceTree=false&sourceTree=false&sourceTree=true&sourceTree=%5Bobject%20Object%5D&elementType=document&index=4&parentId=1

Firebug does output **xhr request failed** in console. Pimcore does throw the 404 mentioned above.

**Comment by brusch** [comment]
Maybe IIS isn't able to cope with this request. 
Please apply the patches above ( 8173e348729df0e64d9209bd6b4143492960547f and a8d05b2a9b42a821c1bc72ac69a4d9b6230caa0b ) and check it it makes it any better.

**Comment by Cruiser13** [comment]
Applying  	https://github.com/pimcore/pimcore/commit/8173e348729df0e64d9209bd6b4143492960547f does work for me. The object and documents are being added.
https://github.com/pimcore/pimcore/commit/a8d05b2a9b42a821c1bc72ac69a4d9b6230caa0b seems to solve the issue aswell.

**Comment by brusch** [comment]
Glad to hear :)

**Comment by Cruiser13** [comment]
Thank you for the fast solution!

Will this change be merged into the core or shall we apply it manually to our systems?

**Comment by brusch** [comment]
is already in the core - will be part of the upcoming build 3786

**Comment by Cruiser13** [comment]
Thank you very much!
