### ISSUE TITLE
Paste -> Paste only contents here: Improve Usability / add warning

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#6011]
# Feature Request

We had multiple complaints of Pimcore backend users which were accidently using the function "Paste -> Paste only contents here" (See this article: https://www.w-vision.ch/en/support/95/copying-and-pasting-objects).

## Feature description

Possible solution: In case the functionality "Paste only contents here" is applied to a page with existing contents there should be a warning for the backend user. 

> The contents of this page will be overwritten and might not be recoverable. Are you sure you want to overwrite this contents?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
