### ISSUE TITLE
pimcore installation issues

### ISSUE THREAD

**Issue by KafeelSyed73** [pimcore/pimcore#6012]
# Bug Report

### Code example
```php
// your code
```

# Feature Request

**Comment by KafeelSyed73** [comment]
Hey Brusch,

Could you please answer ot my question as well since you closed the ticket?

**Comment by brusch** [comment]
You didn't asked a question ... 
But anyway, for support please use https://talk.pimcore.org/ or http://gitter.im/pimcore/pimcore 
Thanks!
