### ISSUE TITLE
Colorpicker Document Editable

### ISSUE THREAD

**Issue by GamerFac3** [pimcore/pimcore#6017]
### Feature Request
I would like to see the rgba Color data type, which already exists in Objects, as an document editable.
I often have customers that want to choose the background color themself and creating an object doesn't make sense.

**Comment by hadl** [comment]
You could use this as a base: https://gist.github.com/hadl/b508d12f5e3150426afb1bf93fd70033

**Note:** This is really basic, but it fits my needs

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
