### ISSUE TITLE
Data loss when saving localized values

### ISSUE THREAD

**Issue by zieglerh** [pimcore/pimcore#602]
# Bug Report
  
### behavior  
When saving an object with localized columns and a collection with localized columns, the object loses it's localized values
  
#### Defintions
TestClass & Collection
[export.zip](https://github.com/pimcore/pimcore/files/270905/export.zip)

#### Step 1
Create a new object with filled values in "localizedfile" and "localizedmultifile"
![screen shot 2016-05-18 at 17 59 02](https://cloud.githubusercontent.com/assets/18331614/15366159/5238954e-1d23-11e6-9b0b-2b3188f8ca18.png)
Save this object
Reload object
Both values are still set
### Step 2
Add an empty collection entry to the object
![screen shot 2016-05-18 at 17 59 20](https://cloud.githubusercontent.com/assets/18331614/15366199/7acdbb38-1d23-11e6-9538-2b31db7f2877.png)
Save the object
Reload the object
### Step 3
After reloading the object the values for both columns are gone
![screen shot 2016-05-18 at 17 59 41](https://cloud.githubusercontent.com/assets/18331614/15366217/945cd2be-1d23-11e6-81de-c53916ab0e06.png)

### Code 
Version 4.0.0

Looking at pimcore/models/Object/ClassDefinition/Data.php
![screen shot 2016-05-18 at 18 12 53](https://cloud.githubusercontent.com/assets/18331614/15366339/2c5194ba-1d24-11e6-956b-11e1cf4aeabb.png)
$resolved will only be set when $originalIndex is not null
and thus as the name "localizedfields" does exists in the collection and in the object
![screen shot 2016-05-18 at 18 13 53](https://cloud.githubusercontent.com/assets/18331614/15366410/77f48576-1d24-11e6-8e23-b12fb4fa1f44.png)
will load the localized values from the main object itself and not from the collection

I've tried setting $resolved before the is_null($originalIndex) but that does only fix one part of the problem. I don't know where the other part is, because the values are still overwritten.

**Comment by weisswurstkanone** [comment]
Thanks! fixed in build 3786

**Comment by zieglerh** [comment]
Thanks, works as expected now.
