### ISSUE TITLE
Update CKEditor to version 4.3 or higher

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#6023]
# Feature Request

CKEditor is currently in version 4.1.13. Therefore it is not possible to use some of the great new plugins (like e.g. https://ckeditor.com/docs/ckeditor4/latest/examples/image2.html which we got requests for).

Seems like the CKEditor has some Pimcore specific modifications therefore it has to be done by someone who is aware of those. Would be great if someone can do it 🚀

**Comment by brusch** [comment]
Pimcore is currently on `4.13.1` not on `4.1.13`, so you should be fine using those plugins 😉

**Comment by brusch** [comment]
Just for reference: 
https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Resources/public/js/lib/ckeditor/CHANGES.md#L4
https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Resources/public/js/lib/ckeditor/ckeditor.js#L5

**Comment by Blackbam** [comment]
Thank you very much for clarification :+1:
