### ISSUE TITLE
Default value is null for existing objects

### ISSUE THREAD

**Issue by kubaplas** [pimcore/pimcore#6027]
# Bug Report
Default values are displayed in admin panel only for newly created objects

### Expected behavior
When adding a new select field with default value, all existing objects should have this value set.

### Actual behavior
Only newly created objects have the default value set. Previously existing objects have `(Empty)` in edit mode and `null` on the grid displayed.

### Steps to reproduce
Add new select field to an existing class, set default value. Open existing object - it will have no value set (`(Empty)`). Open grid - `null` is displayed there.
Create new object - it has default value correctly displayed in both cases.

**Comment by kubaplas** [comment]
Did some additional tests - it seems that in object_store_ table default value is saved for newly created object, for the rest is set to NULL.
object_query_ table and object_ view both have NULL in attribute column.

**Comment by brusch** [comment]
@kubaplas currently this is intentional, see also: 
https://github.com/pimcore/pimcore/blob/bf5070deb00e7d428f3c061878cbdc191751bc30/models/DataObject/ClassDefinition/Data/Select.php#L207

Default values are applied on save and nowhere else.

**Comment by brusch** [comment]
But you're right, there's an issue with the query table for select data-types, I'm going to create a PR for that.

**Comment by brusch** [comment]
Other data-types are luckily not affected by this bug.
PR see: #6028

**Comment by kubaplas** [comment]
@brusch I noticed the change after upgrading Pimcore from 5 to latest 6 release - objects that previously showed default value in edit mode now are displaying (Empty).

Nevertheless, the save in those cases wouldn't help, as the values needs to be explicitly switched by user. It seems like NULL is interpreted as value that has been already set, so no default value is used.

I checked out your PR, but `null` is still visible in grid - I think it's not correct - if not default value, empty string should be displayed? When exported to csv it is empty... I'm afraid I'm lost here...

![Screenshot_20200311_151139](https://user-images.githubusercontent.com/1809664/76426748-becec200-63ab-11ea-9c5f-e4c3de88c1e1.png)

**Comment by brusch** [comment]
@kubaplas 
Difference between v5 and v6: probably because of #5594 
Null values: yes of course, because otherwise it wouldn't be possible to set a value back to null. 

To be more specific: default values are only applied on create, that's it, see also: 
https://github.com/pimcore/pimcore/blob/626da93cdc9e6d27312eb65b57a28c0165749375/models/DataObject/Traits/DefaultValueTrait.php#L50

**Comment by kubaplas** [comment]
@brusch to be sure:
If value in the database is null, (Empty) and null should be shown to the user if defaultValue is set?
I found this code in select.js
https://github.com/pimcore/pimcore/blob/b3229d785c6e6eebab8d3fc42c3340e1a1edd6d5/bundles/AdminBundle/Resources/public/js/pimcore/object/tags/select.js#L357
```applyDefaultValue: function() {

        this.defaultValue = null;
        if ((typeof this.data === "undefined" || this.data === null) && this.fieldConfig.defaultValue) {
            this.data = this.fieldConfig.defaultValue;
            this.defaultValue = this.data;
        }
    }```
Which I think should display default value in such case. Is this code not used then?
