### ISSUE TITLE
setCondition on href strange notation

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#603]
In Pimcore v4 release, setCondition on href is not documented. Only for multiHref:

```
$relationId = 345;
$list = new \Pimcore\Model\Object\Example\Listing();
$list->setCondition("myMultihref like '%,".$relationId.",%'");
$objects=$list->load();
```

Condition on href only work with:
```
$list = new Object\MyClass\Listing();
$list->setCondition("myhref__id = ?", 120);
$list->load()
```

I was thninking using:
```
$list->setCondition("myhref = ?", 120);
```
will be ok, but it bring back an exception.

Maybe it could be documented this way "__id" for single href, or corrected so it work directly with the field name without __id.

Thanks!

**Comment by brusch** [comment]
Thanks! 
The docs are open to edit for everyone - you are always welcome to make such improvements directly in our wiki :-)

**Comment by Yivan** [comment]
Documentation updated:
https://www.pimcore.org/wiki/display/PIMCORE4/Href%2C+Multihref%2C+Objects+-+Relations%2C+Dependencies+and+Lazy+Loading%2C+Objects+with+Metadata%2C+Multihref+with+Metadata

With:
```
$relationId = 162;
$list = new \Pimcore\Model\Object\Example\Listing();
$list->setCondition("myHref__id = ".$relationId);
$objects=$list->load();
```

**Comment by brusch** [comment]
Thank you very much! :-)

**Comment by parameter** [comment]
Is realationId the id f the object we have realted in multi href or is it the id from object_relations_ID I need? If yes, how do I get that using pimcore api?

**Comment by brusch** [comment]
It is the target object id. 

```php
$foo = \Pimcore\Model\Object::getById(123); 

// find all objects with a relation to $foo
$list = new \Pimcore\Model\Object\Example\Listing();
$list->setCondition("myHref__id = ".$foo->getId());
```

**Comment by parameter** [comment]
Nice one Brusch. Nice handle/nick BTW. 
I guess this doesn't work that easy with multi-href fields right? 
We solved it by using another type of field instead

**Comment by parameter** [comment]
... fail. Should this work on a href-field with one or more objects added?

**Comment by brusch** [comment]
Only with one (href, not multi-href) ... but this is not the right place to discuss such questions :) 
Please visit our Google Group or the Gitter chat for support ;) 
Thanks!
