### ISSUE TITLE
call loadData() on null : should test if Version object exists

### ISSUE THREAD

**Issue by FredoVelcro-zz** [pimcore/pimcore#6038]
https://github.com/pimcore/pimcore/blob/dfae21387a007373e723574b9306f7329aa52686/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L1488

We've got a case in our projet where this fails because $version = Model\Version::getById($id); returns null object

Can you surround this with a test ?
(in other functions in this controller, same problem)

Thanks

Best regards

**Comment by weisswurstkanone** [comment]
Please check what the exception in Version::getById is

**Comment by brusch** [comment]
@FredoVelcro any feedback? Thanks a lot!

**Comment by FredoVelcro** [comment]
I thinks the possible null return should be handled by the core, not by the user's code no ? 
```php
...
$version = Model\Version::getById($id);
$object = $version->loadData(); // here 
```
if not a very safe approach

**Comment by brusch** [comment]
It's the default behaviour that Pimcore returns null for non existing entities when using the static getters. It makes sense to keep this consistent,  also for versions.
