### ISSUE TITLE
Pimcore 6.5.3: Sometimes Objects cannot be found when click "Show In Tree". Target is no on first page

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#6045]
Currently we have a customer where the problem also occurs. We have recently updated to Pimcore version 6.5.3.
The customer reports that when he searches for an object and presses the "Show in tree" button after opening it, there are some objects that are not found. 

My observation showed that the root node is already found, but the offset is not given with the second request.
<img width="847" alt="Bildschirmfoto 2020-03-16 um 14 17 11" src="https://user-images.githubusercontent.com/8749138/76762130-ff09b800-6790-11ea-9a43-61e2801001c1.png">

Here are the requests, where an object is :
<img width="1125" alt="Bildschirmfoto 2020-03-16 um 14 17 45" src="https://user-images.githubusercontent.com/8749138/76762195-1b0d5980-6791-11ea-91dd-3bdc1e834608.png">

I am a little desperate right now. Does anyone have a solution for this problem?

_Originally posted by @BlackbitNeueMedien in https://github.com/pimcore/pimcore/issues/3497#issuecomment-599532050_

**Comment by weisswurstkanone** [comment]
Hello @BlackbitNeueMedien ,
please check if https://github.com/pimcore/pimcore/pull/6451 solves your problem.
