### ISSUE TITLE
Dynamic select in objectbricks

### ISSUE THREAD

**Issue by RuudvdvNB** [pimcore/pimcore#6046]
# Bug Report

### Expected behavior
In Data Objects it is possible to add an option provider for a select or multiselect to add dynamic values. When loading a data object the options provider is used to load the dynamic options. This is possible for both classes and object bricks.

We created a second class (see screenshot) with a table in which we added the values for the options provider. (2 columns, key and value). As soon as we add a new row in the table we expect the select options for the object brick to change when we (re)load a data object.

![image](https://user-images.githubusercontent.com/36728652/76774531-51080900-67a4-11ea-8c5d-4f5e0f637cd4.png)

### Actual behavior
When (re)loading a data object the options for the dynamic select in a object brick are not reloaded. The options for the select that is added directly in the class are loaded as expected.

### Steps to reproduce
1. Create a class (eg. product)
2. Add a select as field with an an option provider (https://pimcore.com/docs/6.x/Development_Documentation/Objects/Object_Classes/Data_Types/Dynamic_Select_Types.html), see the screenshot below for an example as we implemented it and see the code for our provider
3. Add object brick field
4. Create object brick with same select field you added in step 2
5. Create a second (dropdown) class with table (see screenshot)
4. Create a new data object from step 5 and add some rows to the table
5. Create a new data object for the class you created in step 1
6. Check the options in both selects
7. Add new rows to the dropdown object
8. Close and reopen the product object and check options

![image](https://user-images.githubusercontent.com/36728652/76774767-a2b09380-67a4-11ea-8fee-43154d8a7f49.png)

### Code example
**DropdownOptionsProvider.php**
```php
<?php

namespace AppBundle\Product\OptionsProvider;

use Exception;
use Pimcore\Model\DataObject\ClassDefinition\Data;
use Pimcore\Model\DataObject\ClassDefinition\DynamicOptionsProvider\SelectOptionsProviderInterface;
use Pimcore\Model\DataObject\Dropdown;

class DropdownOptionsProvider implements SelectOptionsProviderInterface
{
    /**
     * @param array $context
     * @param Data $fieldDefinition
     * @return array
     * @throws Exception
     */
    public function getOptions($context, $fieldDefinition)
    {
        $dropdownPath = $this->getOptionsProviderData($fieldDefinition);
        if (empty($dropdownPath->dropdown)) {
            throw new Exception('No dropdown path is provided!');
        }

        $dropdown = Dropdown::getByPath($dropdownPath->dropdown);
        if (empty($dropdown) || !$dropdown instanceof Dropdown) {
            throw new Exception('Dropdown path does not exsist!');
        }

        return $dropdown->getItems();
    }

    /**
     * Returns the value which is defined in the 'Default value' field
     * @param array $context
     * @param Data $fieldDefinition
     * @return mixed
     */
    public function getDefaultValue($context, $fieldDefinition)
    {
        return $fieldDefinition->getDefaultValue();
    }

    /**
     * @param array $context
     * @param Data $fieldDefinition
     * @return bool
     */
    public function hasStaticOptions($context, $fieldDefinition)
    {
        return true;
    }

    private function getOptionsProviderData(Data $fieldDefinition)
    {
        return json_decode($fieldDefinition->getOptionsProviderData());
    }

}
```

**Comment by weisswurstkanone** [comment]
@RuudvdvNB tried it step by step and even using your code. wasn't able to reproduce. maybe some detail is missing? can you double-check the description.

**Comment by weisswurstkanone** [comment]
@RuudvdvNB tried it step by step and even using your code. wasn't able to reproduce. maybe some detail is missing? can you double-check the description please?

**Comment by RuudvdvNB** [comment]
After you have done all the above steps, could you now give the object brick a title and a group? Now change the items in the dropdown class, and re-open the data object.

**Comment by weisswurstkanone** [comment]
thanks for the clarification!
