### ISSUE TITLE
cannot delete group collection from classification store in pimcore 3

### ISSUE THREAD

**Issue by roelfooip** [pimcore/pimcore#605]
# Bug Report
  
### Expected behavior 
delete group collection  

### Actual behavior  
throws error ( screenshot attached )
  
### Steps to reproduce  
open classification store
click the group collections tab
try to delete one

**Comment by brusch** [comment]
The support for the classification store using the legacy user interface (ExtJS 3.4) was discontinued beginning with version 4. 

Please update to v4 and use the modern interface instead. 
Thanks!
