### ISSUE TITLE
Document\Tag Public properties

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#6050]
Remove Public Properties there as well to be consistent with DataObjects and Assets (https://github.com/pimcore/pimcore/blob/master/models/Document/Tag/Relation.php#L58). 

It is quite painful sometimes to work with that in templates, you always have to remember where to use a getter or the property name itself (which for private/protected properties, symfony checks for a getter and uses that one)

**Comment by brusch** [comment]
Makes sense, topic for v7 then.
