### ISSUE TITLE
[Document] Issues with WYSIWYG floating toolbar

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#6051]
There's an issue when the WYSIWYG field is quite at the end of a page, then the CKEditor floating toolbar is displayed over the actual field, so editing is quite hard. 

![image](https://user-images.githubusercontent.com/142037/76844515-b0febe00-683d-11ea-92bf-df5e847ec0be.png)

**Comment by dvesh3** [comment]
It is a CSS issue not Pimcore.
