### ISSUE TITLE
[Sitemap]  DocumentTypeFilter ignores Hardlinks

### ISSUE THREAD

**Issue by MosiiAUT** [pimcore/pimcore#6053]
# Bug Report

### Expected behavior
DocumentTypeFilter should check if element is of type page/link/hardlink

### Actual behavior
DocumentTypeFilter ignores hardlinks because it is of the type 'Pimcore\Model\Document\Hardlink\Wrapper\Page' and returns 'page' instead of 'hardlink' on the function $element->getType()

[https://github.com/pimcore/pimcore/blob/master/lib/Sitemap/Document/Filter/DocumentTypeFilter.php](url)

**Comment by brusch** [comment]
Hardlinks should be ignored in the sitemap anyway, right? Because they send a canonical header to the source anyway, see: https://github.com/pimcore/pimcore/blob/4c986d60d890898e466533a21dfd29bde2acb9f6/bundles/CoreBundle/EventListener/Frontend/HardlinkCanonicalListener.php#L108

**Comment by MosiiAUT** [comment]
Yes, I modified the "canBeAdded"- function in the [DocumentTypesFilter.php](https://github.com/pimcore/pimcore/blob/master/lib/Sitemap/Document/Filter/DocumentTypeFilter.php) so it ignores every hardlink. The "handlesChildren"- function could stay as it is

````php
    public function canBeAdded(AbstractElement $element, GeneratorContextInterface $context): bool
    {
        if (!$element instanceof Document || $element instanceof Hardlink\Wrapper\Page) {
            return false;
        }

        return in_array($element->getType(), $this->documentTypes);
    }

````
