### ISSUE TITLE
Image preview shows default pimcore placeholder because "aspectratio" parameter is ignored

### ISSUE THREAD

**Issue by alexej-d** [pimcore/pimcore#6057]
# Bug Report

### Expected behavior
Using this twig code an image preview should be visible in backend: `{{ pimcore_image('visual', {class: 'mx-auto w-full', thumbnail: {aspectratio: true, width: 476}}) }}`

### Actual behavior
Only pimcore's placeholder is showing.

### Steps to reproduce
Use the top code in a document template and upload an image to the field in editmode. After attaching the image to the field, a broken preview is being shown. Addind a height parameter to the image fixes this behaviour but unsets the possibility to scale an image by width.
The problem is that the image editable generates following url `/admin/asset/get-image-thumbnail?id=5&width=476&height=0&id=5&path=%2Fvisuals%2Fvisual_home_1.png&alt=&cropPercent=&cropWidth=&cropHeight=&cropTop=&cropLeft=&predefinedDataTemplates=`. When `&aspectratio=1` is appended to the url all works well so I assume the JavaScript code is ignoring aspectratio right now which is a bug.

**Comment by dvesh3** [comment]
@alexej-d Sorry, cannot reproduce with given code snippet. Could you please provide clear steps? thanks!

**Comment by alexej-d** [comment]
@dvesh3 can you try in dev mode with debugging on? I always see the image filetype-not-supported.svg of the AdminBundle. Once you change  line 357 in vendor/pimcore/pimcore/bundles/AdminBundle/Resources/public/js/pimcore/document/tags/image.js to something like this `+ Ext.urlEncode(this.datax) + (this.options.thumbnail.aspectratio ? '&aspectratio=1' : '');` the correct thumbnail is being shown in the editmode.

**Comment by dvesh3** [comment]
@alexej-d please share affected Pimcore version. Thanks!

**Comment by alexej-d** [comment]
@dvesh3 it's 6.5.3
