### ISSUE TITLE
Upload Plugin zip doesnt work

### ISSUE THREAD

**Issue by dominicdettabp** [pimcore/pimcore#606]
I created a simple plugin following the guide [https://www.pimcore.org/wiki/display/PIMCORE4/Example] but when I try to upload the plugin zip to https://demo.pimcore.org/admin/ 
I receive the following error as you can see below:
![schermata 2016-05-19 alle 16 49 56](https://cloud.githubusercontent.com/assets/17565958/15397828/c459c832-1de1-11e6-96b9-2377bfe3166e.png)

This is the plugin zip: 
[MyPlugin.zip](https://github.com/pimcore/pimcore/files/272827/MyPlugin.zip)

**Comment by brusch** [comment]
Unfortunately we cannot reproduce the problem using your ZIP file. 
Please open the browser network panel and try the upload again, then check the response: 

![image](https://cloud.githubusercontent.com/assets/142037/15400560/3d259764-1dec-11e6-87bd-0ccc0c214ed8.png)

I'm pretty sure you'll find the answer there.
Probably it's a permission issue.
