### ISSUE TITLE
Update the required Embera version

### ISSUE THREAD

**Issue by mpratt** [pimcore/pimcore#6061]
# Feature Request

The version of [Embera](https://github.com/mpratt/Embera) you are using is currently out of date. The 1.x.x branch is not receiving any updates, unless they are security related.

Version 2.0.x is out since january, Its stable and has a bunch of new features, it's being updated regularly and has support for +160 websites.

After a quick inspection, it seems you only need to update your composer.json with

```
"mpratt/embera": "^2.0.3",
```

**Comment by brusch** [comment]
@mpratt good idea, can you maybe provide us a PR for that? Thanks a lot in advance!

**Comment by dvesh3** [comment]
resolved by https://github.com/pimcore/pimcore/commit/658d9918930dd18419dde151e83845d2f478f5ba
