### ISSUE TITLE
[dev-master] Asset upload broken by missing "id" column in "dependencies" table.

### ISSUE THREAD

**Issue by romainbessugesmeusy** [pimcore/pimcore#6063]
Since last composer update, I noticed that I can't upload assets anymore. I believe this is due to a schema change in the dependencies table, where the primary key "id" has been replaced by a compound index, am I right?

<img width="704" alt="Capture d’écran 2020-03-19 à 09 10 27" src="https://user-images.githubusercontent.com/3127404/77045535-aa994f00-69c1-11ea-884c-8ec75ea366f4.png">

**Comment by dvesh3** [comment]
@romainbessugesmeusy looks like you are missing some migrations. can you please check if all migrations executed? including https://github.com/pimcore/pimcore/blob/f5b02e99a581eaeef90b4122de94357a5d873d18/bundles/CoreBundle/Migrations/Version20200226102938.php

**Comment by romainbessugesmeusy** [comment]
Thanks for the heads up, but the migrations have been executed... strange. I'll keep investigating

**Comment by romainbessugesmeusy** [comment]
Can we agree this migration should have been played by Pimcore\Composer::executeMigrationsUp ?

**Comment by dvesh3** [comment]
Yes, this method is responsible for executing migrations after composer update. Also, you can check migrations status with command `bin/console pimcore:migrations:status -s pimcore_core --show-versions`

**Comment by romainbessugesmeusy** [comment]
Thank you for the fast reply and the very helpful snippet. It looks like the migrations were stalled, even if the `Pimcore\Composer::executeMigrationsUp` had been ran several times.
![image](https://user-images.githubusercontent.com/3127404/77058133-4ed8c100-69d5-11ea-814d-7af73712a7d4.png)

Closing the issue, but I think there's some deeper trouble behind the core migration process.

**Comment by dvesh3** [comment]
Thanks @romainbessugesmeusy, for sharing insights. we'll investigate the migration process.
