### ISSUE TITLE
[Data Objects] Grid Configurator: No preview for select

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#6065]
![image](https://user-images.githubusercontent.com/6142086/77059183-d5da6900-69d6-11ea-8113-ade80c1956ad.png)

**Comment by dvesh3** [comment]
@weisswurstkanone Cannot reproduce! is there an issue with specific case e.g. option provider?
![image](https://user-images.githubusercontent.com/5137917/77421511-4107af00-6dcc-11ea-9440-cb274bb127ea.png)

**Comment by weisswurstkanone** [comment]
Would say a combination with options provider - works fine for static fields
