### ISSUE TITLE
[Bug/Doc] Full url redirection doesn't seems to handle protocol

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#6068]
Hello,

First, I hope all is going fine on this period for Pimcore Team and contributors.

I tried to make a http to https redirection for a subsite, but i get no way to manage it.
Settings:
- Entire URL
- Source: @^http:@
- Redirection: @https://www.mydomain.com/@

I tried to keep it simple here.
(i tried any variation including (.*) after domain and $1 replace, hardccoded domain name, etc...)

Is it possible ? I was thinking yes, because Entire url on the GUI has the protocol :
![image](https://user-images.githubusercontent.com/9025839/77122338-a27ef500-6a3d-11ea-9eb7-fe1838adf51f.png)

Is it a doc problem (so not feseable), a bug, or me ? ; )

Many thanks.
(by the way doc seems to present old gui way: https://pimcore.com/docs/6.x/Development_Documentation/MVC/Routing_and_URLs/Redirects.html)

**Comment by Yivan** [comment]
Just to add: i tested even simplier:
Source: http://www.mydomain.com/my-page
Destination: https://www.mydomain.com/my-page
Does not work : (

This is a subsit (i tried empty, main domain, and subsite as source/target too)
(pimcore v6.4.2)

**Comment by M-Ali-Aziz** [comment]
Hello,
I've the same problem. Any update on this issue ?
(Pimcore v6.8.12)

**Comment by brusch** [comment]
For me this works exactly as expected. 
I've the following config: 

![image](https://user-images.githubusercontent.com/142037/114869160-f867cd00-9df6-11eb-8d39-8352158523cb.png)

Please ensure that neither HSTS nor any other app-server related config is in place that doesn't delegate the original request to Pimcore.

**Comment by brusch** [comment]
See also: 

![image](https://user-images.githubusercontent.com/142037/114869968-e5a1c800-9df7-11eb-8158-5c1988386f4d.png)

**Comment by Yivan** [comment]
@brusch Thanks for your answer.

From what I remember from this issue, the site was accessible in http://, this was really the redirection which has not effect, so no HSTS problem.

But I checked app server and we get a reverse proxy in front, the connection between this reverse proxy and php is made in https.
So PHP, from a browse HTTP request, PHP/Pimcore see (I got those from phpinfo in BO Pimcore):
$_SERVER['HTTPS'] => on
$_SERVER['SERVER_PORT'] => 443
$_SERVER['REQUEST_SCHEME'] => https
**$_SERVER['HTTP_X_FORWARDED_PORT'] => 80
$_SERVER['HTTP_X_FORWARDED_PROTO'] => http**
$_SERVER['HTTP_REFERER'] => http://mydomain.com

So I think maybe redirection tool on Pimcore don't use X_FORWARDED directives. Maybe it could be an improvement to use them (HTTP_REFERER is not safe and not always available because antivirus and so).
Purpose on this redirection tool is to redirect front-end url so using X_FORWARDED directives make sense I think.

**Comment by brusch** [comment]
If you're using a reverse proxy, please configure it accordingly: 
https://symfony.com/doc/4.4/deployment/proxies.html
Everything should then work as expected (redirect matching just uses Symfony's `Symfony\Component\HttpFoundation\Request::getUri()` 😉)

**Comment by M-Ali-Aziz** [comment]
After checking I can confirm that we don't use neither HSTS, Load Balancer, Reverse Proxy  nor any other app-server related config on the server.

All other old redirect works fine,
but after updating Pimcore when i create a new redirect using Pimcore Admin UI so it only saves on the database ( redirects table ) but not working at all.

**Comment by Yivan** [comment]
Thanks @brusch We already set proxy on all our projects. To be sure, I just made a test again :

![image](https://user-images.githubusercontent.com/9025839/115302669-f8ebc500-a162-11eb-883a-70f210a7a3d9.png)

Proxy was well setted, with the two way of doing it:
- https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Configuration.html#page_Adding-logic-to-the-startup-process
- https://github.com/pimcore/pimcore/blob/master/lib/Bootstrap.php#L138
As can be seen:

![image](https://user-images.githubusercontent.com/9025839/115302881-351f2580-a163-11eb-997e-58844523aec4.png)

and:

![image](https://user-images.githubusercontent.com/9025839/115302923-3f412400-a163-11eb-8bc9-e65adb51b66f.png)

And I always got no redirection to https when using http url:

![image](https://user-images.githubusercontent.com/9025839/115303203-9e069d80-a163-11eb-844d-44d05ce70895.png)

It really seems proxy isn't used at all or am I missing something ?
I can make further test if you can hint me.

Thanks.

**Comment by M-Ali-Aziz** [comment]
I get this error now and nothing works until I import a database-dump from backup.
```
Failed to acquire the "\Pimcore\Routing\RedirectHandler" lock.
```

<img width="1485" alt="pimcore-redirect-error" src="https://user-images.githubusercontent.com/8568212/115354801-50694f80-a1ba-11eb-864a-ec27608bf879.png">

`Pimcore Version 6.8.12`

Regards

**Comment by Ibrahim1238** [comment]
you have to change your CURRENT_USER to be root or your right user name  in the database

**Comment by M-Ali-Aziz** [comment]
Thanks for your reply @Ibrahim1238 
Could you please explain more how do you mean by changing the CURRENT_USER to be root !?
I mean to get the redirection work!

**Comment by Ibrahim1238** [comment]
**first you have to clear the cache and load the page Strg + F5**  for your dump maybe the user for some segments 'plugin_cmf_segment_assignment' has been changed 
where you store your data base you have **only xampp or aws or azure ....**

**Comment by M-Ali-Aziz** [comment]
I'm not using CMF in this project !!
Any way I'll clear the cache and load the page late and test.
Thank you!

**Comment by Ibrahim1238** [comment]
your welcome
