### ISSUE TITLE
Error ExtJS with the MyPlugin example

### ISSUE THREAD

**Issue by dominicdettabp** [pimcore/pimcore#607]
I created the MyPlugin example following the guide https://www.pimcore.org/wiki/display/PIMCORE4/Example but after installing and enabling the plugin when I navigate on Tool/MyPlugin I receive the following javascript error: _Uncaught TypeError: tabPanel.activate is not a function_
I modified the following code plugins/MyPlugin/static/js/admin.js:
`tabPanel.activate('my_plugin_check_panel');`
to `tabPanel.setActiveTab('my_plugin_check_panel');` and now no errors are displayed.

**Comment by brusch** [comment]
Please use our forums for support, not our bug tracker. 
Thanks for your understanding!
