### ISSUE TITLE
Admin search filter on null not working for Select type

### ISSUE THREAD

**Issue by belendel** [pimcore/pimcore#6072]
On our application we have a subscriber that adds extra filters on the AdminEvents::SEARCH_LIST_BEFORE_FILTER_PREPARE event.

Filter looks like this:

```php
array:4 [
  "operator" => "like"
  "value" => array:3 [
    0 => ""
    1 => "NULL"
    2 => "10"
  ]
  "property" => "CompanyId"
  "type" => "list"
]
```

The problem is that the NULL value isn't converted to **IS NULL** for Select fields. This is because the logic from Pimcore\Model\DataObject\ClassDefinition\Data::getFilterConditionExt() is overridden by Pimcore\Model\DataObject\ClassDefinition\Data\Select::getFilterConditionExt()

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
