### ISSUE TITLE
XLIFF-Export: error when exporting documents

### ISSUE THREAD

**Issue by skrahlQW** [pimcore/pimcore#6073]
When trying to export a document with the XLIFF export function, we get the following error:

`{"success":false,"message":"Argument 2 passed to Symfony\\Cmf\\Component\\Routing\\ContentAwareGenerator::getRouteByName() must be of the type array, null given, called in \/usr\/www\/users\/weissj\/live\/vendor\/symfony-cmf\/routing\/src\/ContentAwareGenerator.php on line 74"}`

This happens when we try to export a single document as well as whole document trees.

It seems that also the MS-Word export is affected by this issue, although we get an empty HTML-File here...

**Comment by brusch** [comment]
Seems to be related with your application as this cannot be reproduced on our public demo instance (demo.pimcore.fun). 
Maybe you can further debug this for us? Thanks a lot!

**Comment by brusch** [comment]
Closed due to inactivity.
