### ISSUE TITLE
Object variant tab - missing Add button

### ISSUE THREAD

**Issue by jansarmir** [pimcore/pimcore#6075]
https://github.com/pimcore/pimcore/blob/57e860452e5bfa7a34deb11abefb4246fa66d691/bundles/AdminBundle/Resources/public/js/pimcore/object/variantsTab.js#L274

tbar: this.getToolbar(fromConfig, save),
is missing Add Button, which was great
now its only possible to add variant from Product (context menu)

**Comment by dvesh3** [comment]
thanks for reporting 👍
