### ISSUE TITLE
Improve Class-Editor Field Restrictions

### ISSUE THREAD

**Issue by zieglerh** [pimcore/pimcore#608]
When creating a structure like this with a text layout component having children components
![screen_shot_2016-05-20_at_11_09_30](https://cloud.githubusercontent.com/assets/18331614/15423087/100de070-1e7c-11e6-9e31-a345c764f5fc.jpg)
the submenu is not displayed
Dragging the sub elements out of the text component makes it work again as expected

**Comment by zieglerh** [comment]
I forgot to mention, that this presumes that you are allowed to add subelements below text components.
You can currently only move elements into text components, but not add them directly
![screen shot 2016-05-23 at 11 06 20](https://cloud.githubusercontent.com/assets/18331614/15465735/6ac8f11a-20d6-11e6-820f-dd0f8b63a114.png)
It is completely valid and we like the way it's being displayed and used in the forms as another grouping layout component.
![screen shot 2016-05-23 at 11 08 21](https://cloud.githubusercontent.com/assets/18331614/15465793/ac14c0fe-20d6-11e6-8fe2-5002a29da2f0.png)

**Comment by brusch** [comment]
The layout component "text" isn't designed to have children. 
Please use the fieldset or panel component instead. 

The text-layout component is intended to be used for help texts and other describing elements within your editing interface. 

Unfortunately it's pretty tough to restrict the drag & drop / copy & paste functionality, so this isn't implemented yet, as we see this as an administrator tool.

**Comment by zieglerh** [comment]
Thanks for your answer.
Would you consider adding borders to the panel inside other panels to look like the component text? Then we could switch the components text with panels (to be precise for this case we will switch the fieldsets with panels and the text with fieldsets to distinguish different depths)
![screen_shot_2016-05-24_at_17_51_47](https://cloud.githubusercontent.com/assets/18331614/15510861/7c43991e-21d9-11e6-9007-d3b957d1c178.jpg)
![screen shot 2016-05-24 at 17 51 40](https://cloud.githubusercontent.com/assets/18331614/15510873/88856a18-21d9-11e6-9c29-d93c9f613ca6.png)

**Comment by brusch** [comment]
Borders are fixed.

**Comment by zieglerh** [comment]
I'm not sure if you are done yet, but the black border does not look intended. The interfering class looks like a fix and the black border is also around the wrong element
![screen shot 2016-05-25 at 14 09 34](https://cloud.githubusercontent.com/assets/18331614/15539397/769eddf8-2282-11e6-8d08-9621f123e57c.png)
Here's the class export: 
` {
	"description":null,
	"parentClass":null,
	"useTraits":null,
	"allowInherit":false,
	"allowVariants":false,
	"showVariants":false,
	"layoutDefinitions":{
		"fieldtype":"panel",
		"labelWidth":100,
		"layout":null,
		"name":"pimcore_root",
		"type":null,
		"region":null,
		"title":null,
		"width":null,
		"height":null,
		"collapsible":null,
		"collapsed":null,
		"bodyStyle":null,
		"datatype":"layout",
		"permissions":null,
		"childs":[
			{
				"fieldtype":"tabpanel",
				"name":"Layout",
				"type":null,
				"region":"",
				"title":"",
				"width":"",
				"height":"",
				"collapsible":false,
				"collapsed":false,
				"bodyStyle":"",
				"datatype":"layout",
				"permissions":null,
				"childs":[
					{
						"fieldtype":"panel",
						"labelWidth":220,
						"layout":"",
						"name":"sprache",
						"type":null,
						"region":"",
						"title":"Sprache",
						"width":"",
						"height":"",
						"collapsible":false,
						"collapsed":false,
						"bodyStyle":"",
						"datatype":"layout",
						"permissions":null,
						"childs":[
							{
								"fieldtype":"localizedfields",
								"phpdocType":"\\Pimcore\\Model\\Object\\Localizedfield",
								"childs":[
									{
										"fieldtype":"panel",
										"labelWidth":100,
										"layout":null,
										"name":"Layout",
										"type":null,
										"region":null,
										"title":"panel title",
										"width":null,
										"height":null,
										"collapsible":true,
										"collapsed":false,
										"bodyStyle":"border: 1px solid black;",
										"datatype":"layout",
										"permissions":null,
										"childs":[
											{
												"fieldtype":"text",
												"html":"",
												"name":"text",
												"type":null,
												"region":null,
												"title":"text",
												"width":null,
												"height":null,
												"collapsible":true,
												"collapsed":false,
												"bodyStyle":"padding:10px;",
												"datatype":"layout",
												"permissions":null,
												"childs":[
													{
														"fieldtype":"input",
														"width":null,
														"queryColumnType":"varchar",
														"columnType":"varchar",
														"columnLength":255,
														"phpdocType":"string",
														"regex":"",
														"name":"name_print",
														"title":"Name Print",
														"tooltip":"",
														"mandatory":false,
														"noteditable":false,
														"index":false,
														"locked":false,
														"style":"",
														"permissions":null,
														"datatype":"data",
														"relationType":false,
														"invisible":false,
														"visibleGridView":false,
														"visibleSearch":false
													}
												],
												"locked":false
											},
											{
												"fieldtype":"panel",
												"labelWidth":100,
												"layout":null,
												"name":"subpanel",
												"type":null,
												"region":null,
												"title":"subpanel",
												"width":null,
												"height":null,
												"collapsible":true,
												"collapsed":false,
												"bodyStyle":"border: 1px solid black;",
												"datatype":"layout",
												"permissions":null,
												"childs":[
													{
														"fieldtype":"input",
														"width":null,
														"queryColumnType":"varchar",
														"columnType":"varchar",
														"columnLength":255,
														"phpdocType":"string",
														"regex":"",
														"name":"subelement",
														"title":"subelement",
														"tooltip":"",
														"mandatory":false,
														"noteditable":false,
														"index":false,
														"locked":false,
														"style":"",
														"permissions":null,
														"datatype":"data",
														"relationType":false,
														"invisible":false,
														"visibleGridView":false,
														"visibleSearch":false
													}
												],
												"locked":false
											},
											{
												"fieldtype":"fieldset",
												"labelWidth":100,
												"name":"fieldset",
												"type":null,
												"region":null,
												"title":"fieldset",
												"width":null,
												"height":null,
												"collapsible":false,
												"collapsed":false,
												"bodyStyle":"",
												"datatype":"layout",
												"permissions":null,
												"childs":[
													{
														"fieldtype":"input",
														"width":null,
														"queryColumnType":"varchar",
														"columnType":"varchar",
														"columnLength":255,
														"phpdocType":"string",
														"regex":"",
														"name":"subelement1",
														"title":"subelement",
														"tooltip":"",
														"mandatory":false,
														"noteditable":false,
														"index":false,
														"locked":false,
														"style":"",
														"permissions":null,
														"datatype":"data",
														"relationType":false,
														"invisible":false,
														"visibleGridView":false,
														"visibleSearch":false
													}
												],
												"locked":false
											}
										],
										"locked":false
									}
								],
								"name":"localizedfields",
								"region":"",
								"layout":"fit",
								"title":"",
								"width":"",
								"height":"",
								"maxTabs":"",
								"labelWidth":"",
								"tooltip":"",
								"mandatory":false,
								"noteditable":false,
								"index":null,
								"locked":false,
								"style":"",
								"permissions":null,
								"datatype":"data",
								"columnType":null,
								"queryColumnType":null,
								"relationType":false,
								"invisible":false,
								"visibleGridView":true,
								"visibleSearch":true
							}
						],
						"locked":false
					}
				],
				"locked":false
			}
		],
		"locked":null
	},
	"icon":null,
	"previewUrl":null,
	"propertyVisibility":{
		"grid":{
			"id":true,
			"path":true,
			"published":true,
			"modificationDate":true,
			"creationDate":true
		},
		"search":{
			"id":true,
			"path":true,
			"published":true,
			"modificationDate":true,
			"creationDate":true
		}
	}
}`

**Comment by brusch** [comment]
Thanks - this only happend when using tabs, which I wasn't.

**Comment by zieglerh** [comment]
thanks, but the 2nd problem I mentioned is the border is around the wrong element :)
Maybe this runs deeper.
![screen_shot_2016-05-25_at_15_42_19](https://cloud.githubusercontent.com/assets/18331614/15542186/fb071300-228f-11e6-961e-165130483b69.jpg)

**Comment by brusch** [comment]
Well, that's a problem with your configuration. 
Remove the additional panel: 
![image](https://cloud.githubusercontent.com/assets/142037/15542832/a16b6d16-2292-11e6-87a8-3a98845ae63f.png)

And give the localized field panel a title.
Then it looks like it should: 
![image](https://cloud.githubusercontent.com/assets/142037/15542781/76f0d058-2292-11e6-9a1a-bd3e66b87d36.png)

**Comment by zieglerh** [comment]
Maybe it's more clear when using just a normal panel
This is what it looks like
![screen shot 2016-05-25 at 16 20 39](https://cloud.githubusercontent.com/assets/18331614/15543529/863c320c-2295-11e6-8b3c-51a578f46388.png)
This is what I mean it has to look like
![screen shot 2016-05-25 at 16 32 49](https://cloud.githubusercontent.com/assets/18331614/15543760/6f14d57e-2296-11e6-9a4f-a70b4b535ed9.png)
It's independent of the localized tab and only inconsistent for the first (panel) child of .pimcore_object_panel_edit
The nested panels inside looks fine now
![screen_shot_2016-05-25_at_15_42_19](https://cloud.githubusercontent.com/assets/18331614/15542186/fb071300-228f-11e6-961e-165130483b69.jpg)
If you compare it with the first version, then you see there were no borders at all
![screen_shot_2016-05-24_at_17_51_47](https://cloud.githubusercontent.com/assets/18331614/15510861/7c43991e-21d9-11e6-9007-d3b957d1c178.jpg)

Just wanted to notice you

**Comment by brusch** [comment]
Done
