### ISSUE TITLE
Classification Store only works in Grid Options with "Classes" Permissions

### ISSUE THREAD

**Issue by FranzRest** [pimcore/pimcore#6083]
Can be verified on the latest Pimcore Demo 

### Expected behavior
I can select and use Classification Store Attributes in the Grid View (of the children grid) without needing the permissions for "Classes"

### Actual behavior
When selecting the Classification Store and pulling it into the Grid View the Error message:

"You don't have sufficient permissions to open the element or perform the desired action." 

is shown.
The error message is not shown when the user has the permissions to edit classes.

### Steps to reproduce
1) Create a user with the necessary rights to open the children grid of an object with a classification store
2) Do not give the user permissions for "classes"
3) Open the children grid -> Grid Options
4) Drag & Drop the classification store
5) Error message is shown

**Comment by weisswurstkanone** [comment]
![image](https://user-images.githubusercontent.com/6142086/77396915-e9098200-6da4-11ea-8680-e1c6c8806133.png)
