### ISSUE TITLE
Calculated Value not generated in child elements

### ISSUE THREAD

**Issue by zieglerh** [pimcore/pimcore#609]
# Bug Report
When using a calculated value field and putting it under a fieldset as child, the value is not generated

![screen shot 2016-05-23 at 11 11 55](https://cloud.githubusercontent.com/assets/18331614/15466130/57798dde-20d8-11e6-925a-0d455406ed7b.png)

See https://github.com/pimcore/pimcore/issues/608 for Text-Component

![screen shot 2016-05-23 at 11 22 32](https://cloud.githubusercontent.com/assets/18331614/15466214/a5071d32-20d8-11e6-9ddf-2ca6cb9fbb52.png)

```php
<?php

namespace Staedter;

class CalculatedTest
{
	public static function compute($object, $context)
	{
		return 'value';
	}
}


```

**Comment by weisswurstkanone** [comment]
fixed in build 3791
