### ISSUE TITLE
Import and Export CSV Configurations

### ISSUE THREAD

**Issue by MarcoGuiducci** [pimcore/pimcore#6091]
# Feature Request
Possibility to Import and Export the configurations created for CSV Imports

## Feature description
In Pimcore we can create a lot of CSV Column configurations, save and share those configurations between users, load them in a second moment and also import the export configurations.

The problem is that if I have more environments for the same Pimcore project (such as develop, test and production) I am not able to export and import those configuration through these environments. The only way is to extract them from the database.

I think that let people export and import the json configuration (as we can do for classes definitions) can save a lot of time, because in real scenarios CSV import could be very complex.

### Pull Request
#6092

**Comment by weisswurstkanone** [comment]
@MarcoGuiducci , why did you close this one?

**Comment by MarcoGuiducci** [comment]
> @MarcoGuiducci , why did you close this one?

I have closed because I've seen that an issue was opened when the Pull Request was created, so this issue is just a duplicate. Should I reopen it?

**Comment by weisswurstkanone** [comment]
![image](https://user-images.githubusercontent.com/6142086/77924806-7288ea80-72a4-11ea-9cb7-e2c95c177540.png)

how do I export the current configuration?

**Comment by MarcoGuiducci** [comment]
The export functionality becomes enabled as soon as you load a previously saved configuration in the database.

**Comment by weisswurstkanone** [comment]
Can you post a video showing the whole procedure?

We would love to see this in the next release which is due tomorrow.

**Comment by MarcoGuiducci** [comment]
That's a link on WeTransfer with videos of the Export and Import procedures

https://we.tl/t-P7ntYiz9aD

**Comment by weisswurstkanone** [comment]
Thanks for sharing. Export.avi doesn't work for me. The export button stays gray.

Apart from that: not sure if this can confuse the user. So, right now you have to save the config. Then load it again so that you can export it as JSON ?

**Comment by MarcoGuiducci** [comment]
> Thanks for sharing. Export.avi doesn't work for me. The export button stays gray.

I'll check fort this problem

> Apart from that: not sure if this can confuse the user. So, right now you have to save the config. Then load it again so that you can export it as JSON ?

Yes, but I think that just after saving the configuration the export has to be enabled, without reloading. I'll make sure that this happens

**Comment by weisswurstkanone** [comment]
imho, export should be enabled all the time and even contain changes you do in the meantime. if latter one is not possible then at least show a warning that you have to save it first and prevent the export.
having it to save and load just to be able to export the latest saved version is a bit hard to understand I guess.

**Comment by MarcoGuiducci** [comment]
> imho, export should be enabled all the time and even contain changes you do in the meantime. if latter one is not possible then at least show a warning that you have to save it first and prevent the export.
> having it to save and load just to be able to export the latest saved version is a bit hard to understand I guess.

Ok, got it.
Meanwhile, i have committed a fix. Can you please clear the cache and try again the export part?

**Comment by MarcoGuiducci** [comment]
@weisswurstkanone A possible solution is to re-use the [prepareSaveData](https://github.com/pimcore/pimcore/blob/e64d4c0d923362a6b4eac9e2fc7961a41282748e/bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/configDialog.js#L263) function to download the current configuration instead of the one that is loaded.
For doing this, I need to send the whole configuration in the GET request. Is this OK?

**Comment by weisswurstkanone** [comment]
Let me quickly outline my thoughs.
Saving (regular save) the configuration is currently handled by importSaveConfigAction.
I guess what we need for export is basically the same stuff but instead of saving it we have to generate the JSON we wanna export.
Why not extract and share&use the common code.

**Comment by MarcoGuiducci** [comment]
Maybe it's easier than you said. The prepareSaveData function in configDialog.js exactly produce the JSON that we want to export. We just need to put this on a file and download it

**Comment by weisswurstkanone** [comment]
check this code as well 

    doSave: function () {
        var config = this.prepareSaveData();
        config = Ext.encode(config);
        try {
            var data = {
                importConfigId: this.importConfigId,
                classId: this.classId,
                config: config
            };

            Ext.Ajax.request({
                url: '/admin/object-helper/import-save-config',

**Comment by MarcoGuiducci** [comment]
@weisswurstkanone made changes for getting the current configuration without needs to load or save. Can you please check and tell me if could be ok?

**Comment by weisswurstkanone** [comment]
resolved via 
#6092 and #6147
