### ISSUE TITLE
Import and Export Icons seem to be wrong

### ISSUE THREAD

**Issue by knoepfchen23** [pimcore/pimcore#6098]
We are actually using the pimcore icons for „export“ and „import“, the colored and the non-colored (black & white) ones. The colored icons seem to be inverted the wrong way. The non-colored seem to be right.

The direction of the arrow of the export icon must be outside the element / circle / square.
The direction of the arrow of the import icon must be inside the element / circle / square.

In these lines, you can see that it’s interchanged:

> .pimcore_icon_export -> /bundles/pimcoreadmin/img/flat-color-icons/internal.svg
> .pimcore_icon_import -> /bundles/pimcoreadmin/img/flat-color-icons/external.svg
> 1197 - 1203 /bundles/AdminBundle/Resources/public/css/icons.css

The same is for ".pimcore_nav_icon_export" and ".pimcore_nav_icon_import". (Lines: 406 - 412)

**Comment by NiklasBr** [comment]
So, I created a PR to fix this, but I can also understand why the current state is why it is. The person who initially choose these icons probably considered the upwards/downwards direction of the arrows to be the primary indicator of function. But I agree that it is actually the direction of the arrow *in relation* to the secondary figure (the circle) which is the primary indicator of function.

A more thourough "fix" would probably mean redrawing the icons altogether to align both of these bearers of information.
