### ISSUE TITLE
assetType lost after reimport of classes

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#610]
1.) create a class with a href relation
2.) choose some assettypes
3.) export class
4.) re-import class
5.) selected assettypes are gone

you can reproduce this on demo.pimcore.org.

![](http://g.recordit.co/GuyyXk0WnB.gif)

**Comment by weisswurstkanone** [comment]
same behavior in legacy interface

**Comment by weisswurstkanone** [comment]
fixed i build 3798
