### ISSUE TITLE
Possible affectation miss in ImageGallery

### ISSUE THREAD

**Issue by FredoVelcro** [pimcore/pimcore#6103]
https://github.com/pimcore/pimcore/blob/329815fcf751da1a847430a686c45eee117af50e/models/DataObject/Data/ImageGallery.php#L134

should be set like this no ?  
```php
if (!is_array($items)) {
            $items = [$items];
        }
```

**Comment by weisswurstkanone** [comment]
why?

The doc says it should be an array
@param Hotspotimage[] $items

so you cannot pass a single item

**Comment by FredoVelcro** [comment]
ok...never mind
