### ISSUE TITLE
image gallery field not persisted well

### ISSUE THREAD

**Issue by FredoVelcro** [pimcore/pimcore#6105]
[Pimcore dev-master branch]

I have an "Image Gallery" field type on an object class definition.
In backend, when i drag drop an asset into the placeholder an then save, if a reload the object, the asset is not here anymore...

![image](https://user-images.githubusercontent.com/1422477/77671943-95578e00-6f88-11ea-9ec7-9010e3562b9f.png)

![image](https://user-images.githubusercontent.com/1422477/77672038-b28c5c80-6f88-11ea-8e6c-c724421298e2.png)

https://www.loom.com/share/fcf5e5fc938644dfa19dac11c8815736

Setting it programmatically show an empty placeholder (see up)

**Comment by weisswurstkanone** [comment]
No error on save?

Please take a look at #6106 if this fixes your problem.

**Comment by FredoVelcro** [comment]
no, no error on save (look a the loom video)
with your patch applied, same result....

**Comment by weisswurstkanone** [comment]
Unable to reproduce on demo instance demo.pimcore.fun
