### ISSUE TITLE
Frontend error while refresh all trees after recycled bin

### ISSUE THREAD

**Issue by baloraki** [pimcore/pimcore#6107]
# Bug Report
When I restore a deleted object and one of the trees for object, documents or assets is not displayed by perspectives, the trees are not updated.

### Expected behavior
After restoring the objects, the trees should be updated automatically.

### Actual behavior
After restoring the objects an error is thrown.

### Steps to reproduce
1. Remove a tree in the default perspective (pimcore-demo) e.g. Data Objects
2. Delete an object under Data Objects
3. Restore object

![image](https://user-images.githubusercontent.com/41831573/77739743-55d58400-7012-11ea-92fd-7449441873ee.png)

**Comment by baloraki** [comment]
#6108

**Comment by dvesh3** [comment]
@baloraki why closed it?
