### ISSUE TITLE
Grid editing doesen't work after adding a select-datatype

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#6111]
reproducible on the demo:
https://demo.pimcore.fun/admin/login/deeplink?object_27_folder

After you add the 'carClass' - select to the grid all fields become uneditable.
![image](https://user-images.githubusercontent.com/7206334/77766660-3ce3c780-7040-11ea-8344-3c03216d906c.png)

**Comment by dvesh3** [comment]
regression of #6087
