### ISSUE TITLE
Cache-Tree is not properly cleared when updating Block-Elements

### ISSUE THREAD

**Issue by ChrisB9** [pimcore/pimcore#6113]
# Bug Report

### Setup:

Following Data-Objects:
- ObjectA
   - ObjectB
       - Blocks
           - BlockElement
- ObjectC
  - Relation to ObjectB

I make changes to the BlockElement
BlockElement->setTitle('title')->save();

### Expected behavior

Saving (no difference, whether i save through web or php-api) the BlockElement, then accessing the values of BlockElement from either ObjectA or ObjectC shows the updated values

ObjectC->getObjectB()->"getBlocks()"->getBlockElement()->getTitle() === 'title';

### Actual behavior

Saving (no difference, whether i save through web or php-api) the BlockElement, then accessing the values of BlockElement from either ObjectA or ObjectC shows the old value, pre-update

ObjectC->getObjectB()->"getBlocks()"->getBlockElement()->getTitle() !== 'title';
ObjectC->getObjectB()->"getBlocks()"->getBlockElement()->getTitle() === 'previousTitle';

### Reason:

I narrowed the saving process down:
- while saving, the BlockElement clears the cache of the Parent
- it does not however "inform" the related objects about this change.

My Workaround so far is, that i get the CacheTags and clear manually:
- ObjectA
- ObjectB
- ObjectC

Doing that manually feels wrong to me, thus here i am opening this issue.
What could be a better way of solving this issue?

**Comment by weisswurstkanone** [comment]
Can you attach a JSON export of your class definition please ?

**Comment by weisswurstkanone** [comment]
Please also provide the pimcore version you are on.

Since
- Object B should get kicked out of the cache on save
- and Relation C -> B is lazy loaded

there shouldn't be any issue.

**Comment by ChrisB9** [comment]
I did test it with pimcore 6.5 (by that time the 6.6 was not out yet)
I am going to prepare a small setup this weekend to better illustrate my issue

**Comment by ChrisB9** [comment]
Thank you first of all for checking this out, i hope i am going to make every step i took, clear.
I was able to reproduce my situation with the latest release.

The following gist is the bulk export of the class setup (it represents pretty much the business logic we are using in the internal project)
[https://gist.github.com/ChrisB9/69cd549e141f3121a658d73888bd4816](Gist)

The following code represents the way i am accessing the data.
The content of h1 is only changing, once i clear the cache  

```php

<?php

declare(strict_types=1);

namespace AppBundle\Controller;

use Exception;
use Pimcore\Controller\FrontendController;
use Pimcore\Model\DataObject\Fourth;
use Symfony\Component\HttpFoundation\Response;

class DefaultController extends FrontendController
{
    /**
     * @return Response
     * @throws Exception
     */
    public function defaultAction(): Response
    {
        $elementData = [];
        $fourths = Fourth::getList();
        /** @var Fourth $fourth */
        foreach ($fourths as $fourth) {
            if (
                (($main = $fourth->getMain()) !== null)
                && (($sub = $main->getSub()) !== null)
                && ($third = $sub->getThird()) !== null
            ) {
                $blocks = $third->getBlock();
                foreach ($blocks as $elements) {
                    foreach ($elements as $element) {
                        $elementData = $element->getData()->getTitle();
                    }
                }
            }
        }
        return new Response('<h1>' . print_r($elementData, true) . '</h1>');
    }
}

```

**Comment by weisswurstkanone** [comment]
regression of https://github.com/pimcore/pimcore/issues/5772

relation types assume that they are lazy loaded which is not the case for blocks
