### ISSUE TITLE
Visible fields in Object Relation Field are not visible in Object Bricks

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#6122]
# Bug Report
### Expected behavior
The visible fields must be visible in the object relation field (Many To many object Relation) in the object brick.

### Actual behavior
If visible fields are selected no fields are displayed in the relationship fields in object Bricks

### Steps to reproduce
1.Create an Object Field and map that object field to a class attribute.

![Screenshot from 2020-03-31 15-07-59](https://user-images.githubusercontent.com/21308144/78011699-8b0b0a80-7361-11ea-8a1a-1aed80898c0d.png)

2.In the object brick definition, create a field of type 'Many to many object relation' and select some visible fields.

![Screenshot from 2020-03-31 15-08-17](https://user-images.githubusercontent.com/21308144/78011693-89d9dd80-7361-11ea-9a3d-b24498afab6c.png)

3.Create object and add object brick to that object.No visible fields are displayed.

![Screenshot from 2020-03-31 15-08-36](https://user-images.githubusercontent.com/21308144/78011684-87778380-7361-11ea-9ddc-a91b53c21338.png)

**Comment by dvesh3** [comment]
Unable to reproduce...can you please try it on demo?

**Comment by neha04** [comment]
I have attached the screenshots of demo.Already Tried
