### ISSUE TITLE
Improvement  : Text Wrap in Grid

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#6123]
Grid display data in single row even when we have extra space in the cell.
Can we use Text wrap for fields like wysiwyg?

![Screenshot from 2020-03-31 15-13-24](https://user-images.githubusercontent.com/21308144/78012327-6a8f8000-7362-11ea-8745-1ad8058be3ed.png)

In the Picture above description column has a lot of space...

**Comment by macroplan** [comment]
I also vote for this feature. I thirsted for this with a simple text field that is holding "html" and it would be excellent to text wrap. A new formatter called "TextWrap""

**Comment by dvesh3** [comment]
we would be happy to receive a PR 😊

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
