### ISSUE TITLE
Using calculated fields within blocks doesn't work

### ISSUE THREAD

**Issue by msphn** [pimcore/pimcore#6128]
# Bug Report
The calculator isn't called if the field is placed within a block.

Appears in Pimcore 6.6 using services and simple classes.

### Expected behavior
The calculator being called for each field, with right context, even in blocks. If if blocks not supported, restrict fields which are not supported.

### Actual behavior
The calculator class ist not called and field stays blank.

### Steps to reproduce
Add a calculator class within a block and add simple calculator either as class or service. Value is not set and class never called.

**Comment by brusch** [comment]
See also #6411

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
