### ISSUE TITLE
On cloning/copying object brick field, the allowed types must not get copied.

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#6129]
On cloning/copying object brick field, the allowed types must not get copied.

![Screenshot from 2020-03-31 23-19-43](https://user-images.githubusercontent.com/21308144/78058563-1f975c00-73a6-11ea-83ab-7cd60a9112c2.png)

![Screenshot from 2020-03-31 23-16-14](https://user-images.githubusercontent.com/21308144/78058546-173f2100-73a6-11ea-9b25-9b6e781f03f4.png)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
