### ISSUE TITLE
Undefined key in field collection after flushing cache

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#613]
After flushing the cache, we get an undefined key for field collection (Pimcore v4.00 release)

Error: [Notice] Undefined index: force in ...\www\pimcore\models\Object\ClassDefinition\Data\Fieldcollections.php on line 291

Patch:
Replace
`if (!$this->getLazyLoading() or $params["force"]) {`
By
`if (!$this->getLazyLoading() || (isset($params["force"] && $params["force"]))) {`

A very good work has been done on notice error on the Pimcore 4 library as this is for now the only notice (in front-end) for a nearly all developped new project. Thanks a lot for this mature release!

By the way, just for information for people interrested, we tried to enable notice on back-end (directly from a predispatch Zend plugin) but seems not possible for now (like v3 too many notice error prevent us working with E_ALL errors on back-end side / full log with notice level). For record i made a pull request for it for v3 (https://github.com/pimcore/pimcore/pull/113), but as many changes is involved in v4 i think it need to be done again from scratch. If someone want to try for v4 he is welcome : )

Thanks!

**Comment by brusch** [comment]
Thanks Yivan!
