### ISSUE TITLE
[DataObject OptionProvider] obsolete Options when OptionProvider is selected for SelectfieldType

### ISSUE THREAD

**Issue by roland4432** [pimcore/pimcore#6130]
# Improvement

### Expected behavior
With a selected OptionProvider for SelectFieldTypes, the field for manually added options should either be merged with the options from the OptionProvider or hidden and discarded, as soon as the OptionProvider is set and the object saved.
### Actual behavior
Even if one sets an OptionProvider you can still add options but those will be ignored when adding instances of this class.

### Steps to reproduce
 * Create a DataObject
 * Add a SelectFieldType
 * Set an OptionProvider for this field
 * Add options for this field manually in the class definition

# Feature Request
Either merge the OptionProvider options with the ones from the class definition or discard the options from the class definition
## Feature description
As soon as you guys come to a conclusion, I will generate a PR for this :)

**Comment by msphn** [comment]
Since those are anyway dynamic, why are they added at all to the class definition?

**Comment by roland4432** [comment]
The options from the OptionProvider won't be added to the class definition. But you can define options in the optionsfield which will be ignored when generation an instance of the class.

**Comment by weisswurstkanone** [comment]
Would say if you add static options and later own decide to use an options provider instead
pimcore shouldn't throw them away deliberately (on your behalf).

**Comment by roland4432** [comment]
Any thoughs from @brusch or @fashxp ?

**Comment by fashxp** [comment]
Well, in my small ideal world it should be defined explicitly what should be used - dynamic options via options provider or static options via static list.
That means maybe add e.g. a select box what to use (options provider, static list) and depending on the value of the select box either show the input fields for defining the options provider, or the definition of the static list. 
Then there is no need to throw away static values, it should be clear for users what is active and used. 

If we change that, we need to consider migrating existing class definitions and updating the docs.

**Comment by solverat** [comment]
@fashxp I just stumbled on that too. What is the point of using a dynamic option provider if all the dynamic will be added statically to the definition. As soon you save your object brick/class,  the `getOptions` triggers which will add **all** the dynamic options to the definition which is sort of... pointless?

**Comment by solverat** [comment]
quick fix: 

```php
public function getOptions($context, $fieldDefinition)
    {
        // "object" is available in object context only
        if(!isset($context['object'])) {
            return [];
        }

        // [...]

        return $options;
    }
```

**Comment by fashxp** [comment]
should be fixed in latest version
