### ISSUE TITLE
[Classification Store] Quantity Value – Default value is not taken into account

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#6139]
# Bug Report

### Expected behavior
When defining a key in a classification store with a default unit selected, it is expected that the unit is preselected when creating a new object with that classification store.

### Actual behavior
The unit is not preselected, hence the default unit select doesn't work properly. I've also tested the same behaviour with the input quantity type and there it works flawlessly.

### Steps to reproduce

1. Create a classification Store
2. Create a key with type quantity value and select a default unit
3. Create a class which includes the previously created classification store
4. Create an object and see that the default unit is not selected

**Classification Store**
![key_definition](https://user-images.githubusercontent.com/17384333/78259817-78c5d380-74fd-11ea-9c61-5b2b805cd8d1.png)

**New Object**
![new_object](https://user-images.githubusercontent.com/17384333/78259839-7f544b00-74fd-11ea-8016-a4e3c4d59aca.png)

**Comment by aarongerig** [comment]
@brusch @weisswurstkanone @dvesh3 Any feedback on this would be appreciated, thanks! :)

**Comment by brusch** [comment]
@aarongerig please be patient ... this is not on our todo list for the current dev-sprint ...

**Comment by aarongerig** [comment]
@brusch Sure, I didn't demand a quick fix for that. A feedback after almost a week would still be appropriate, right? Maybe I could even provide a fix. ;)

**Comment by brusch** [comment]
> A feedback after almost a week would still be appropriate, right?

Not really for free support - paid support I fully agree 😉

**Comment by aarongerig** [comment]
I'm not asking for support, I reported an issue in your software. I would say this is in your interest as well, that this gets resolved, right?

**Comment by skochTC** [comment]
@weisswurstkanone - I think the issue can be closed?

**Comment by rushit-credencys** [comment]
QuantityValue has supported only numeric unique identifiers that need to add validation or remove the condition.

please check [here](https://github.com/pimcore/pimcore/discussions/8858) maybe it's help

**Core File:** \pimcore\models\DataObject\ClassDefinition\Data\QuantityValue.php
![image](https://user-images.githubusercontent.com/52573912/116391990-8010fb00-a83d-11eb-9fe0-c6d56cf2862a.png)
