### ISSUE TITLE
Argument 1 passed to Pimcore\Model\Document\Tag\Block\Item::__construct() must be an instance of Pimcore\Model\Document\Page, instance of Pimcore\Model\Document\Snippet given

### ISSUE THREAD

**Issue by leuchtdiode** [pimcore/pimcore#614]
Hi,

I have a block area in one of my snippets. Unfortunately a call to `Pimcore\Model\Document\Tag\Block::getElements()` causes this error:

`Argument 1 passed to Pimcore\Model\Document\Tag\Block\Item::__construct() must be an instance of Pimcore\Model\Document\Page, instance of Pimcore\Model\Document\Snippet given`

because `Pimcore\Model\Document\Tag\Block\Item` only takes a `Model\Document\Page` as first argument. I think changing the first argument to `Model\Document\PageSnippet` would solve the issue.

At least it does for me.

BR,
Alex

**Comment by brusch** [comment]
Funny, this was actually fixed yesterday :) 
See: https://github.com/pimcore/pimcore/commit/0d9341e7ca4687a49c3d0798946b7e99df8ef7c2 
So if you update to the latest build, this problem should be fixed.

**Comment by leuchtdiode** [comment]
Nice, thx.
