### ISSUE TITLE
Modification date doesn't update after object change

### ISSUE THREAD

**Issue by piotrecky** [pimcore/pimcore#6141]
Reproducible on the demo:
https://demo.pimcore.fun/admin/?perspective=PIM

After change any object and save, modification date not change.

**Comment by NiklasBr** [comment]
A limitation of the Pimcore admin interface is that you have to reload objects after updating them to see changes like this. The demo is offline at the moment, but did you try reloading the object (or closing and opening it again)?

**Comment by NiklasBr** [comment]
See #4678

**Comment by piotrecky** [comment]
reloading object nothing change.

**Comment by NiklasBr** [comment]
The demo site is online again, I can reproduce it there (it works locally), might be a bug?

**Comment by piotrecky** [comment]
yes I checked before a second on demo pimcore

**Comment by dvesh3** [comment]
regression of https://github.com/pimcore/pimcore/pull/6047
