### ISSUE TITLE
[Document] getRealFullPath() vs getFullPath()

### ISSUE THREAD

**Issue by roland4432** [pimcore/pimcore#6144]
# Bug Report

### Expected behavior

The url returned from both functions should either be encoded for both or not encoded for both

### Actual behavior

ExampleURL: www.mysite.com/my nav point/subsite

getRealFullPath will return: /my nav point/subsite  
getFullPath will return:        /my%20nav%20point/subsite

### Steps to reproduce

Create a document with special chars in the url and call both the stated methods in the controller on the current document.

Which behavior is the desired one?

**Comment by brusch** [comment]
In my opinion everything is correct here: 
- `getRealFullPath` returns the internal full path
- `getFullPath` returns the frontend path (considering sites, encoded, ...)

**Comment by NiklasBr** [comment]
It's unclear to me as well.

@brusch I think this could be a lot clearer if there was some documentation (in code or docs) as to why one is encoded and the other one is not. As it is right now you know, but we do not, it's a hidden knowledge that could be codified.

It also appears that `PageSnippet::getUrl()` is using `getRealFullPath()` for frontend similarly to how `getFullPath()` should be used?

**Comment by brusch** [comment]
Regarding: https://github.com/pimcore/pimcore/blob/163f95e61ac97b8d5997932827ba93cc85755b0b/models/Document/PageSnippet.php#L615 
Unfortunately this is currently the only way of doing this without changing the signature of `getFullPath()` , we'll change that in the future.

**Comment by brusch** [comment]
Clarified that in 9b0dff2c30656d48f54f82b3da5fabb9d9de1255
Thanks for your feedback.
