### ISSUE TITLE
Pimcore renders invalid HTML for SVG image with image thumbnail

### ISSUE THREAD

**Issue by julmot** [pimcore/pimcore#6150]
# Bug Report

When using an image thumbnail to scale an *SVG* image with the following configuration:

![000176](https://user-images.githubusercontent.com/8310677/78391410-9a4eba00-75e6-11ea-83f3-c79d7be4d85a.png)

*Note* that it has enabled `Force <picture> HTML tag` (to make it consistent with non-SVG images).

And calling it in Twig like:

```twig
pimcore_image('image', {
  removeAttributes: ['width', 'height'],
  class: 'image__img text-image-left-right__image',
  thumbnail: 'three_column_text_image_svg',
  cacheBuster: true,
})
```

I'm getting an invalid output:

```html
<picture data-alt="" data-default-src="/cache-buster-1585728835/content/CMS/Illustrationen%20USP%27s/Preis.svg">
	<source srcset="/cache-buster-1585728835/content/CMS/Illustrationen%20USP%27s/Preis.svg 1x, /cache-buster-1585728835/content/CMS/Illustrationen%20USP%27s/Preis.svg 2x" type="image/webp">
	<source srcset="/cache-buster-1585728835/content/CMS/Illustrationen%20USP%27s/Preis.svg 1x, /cache-buster-1585728835/content/CMS/Illustrationen%20USP%27s/Preis.svg 2x" type="image/png">
	<img class="image__img text-image__image" alt="" src="/cache-buster-1585728835/content/CMS/Illustrationen%20USP%27s/Preis.svg">
</picture>
```

The problem here is, that:

* An SVG image should not have high res nor low res alternatives. This currently causes an issue showing the image in @2x in Chrome and @1x in Firefox for me.
* Furthermore the `type` is invalid, an image does not have the type `ìmage/png` nor `image/webp`.

When disabling `Force <picture> HTML tag` I'm getting a single image without high res or low res, which is correct. But I want to have the `<picture>` tag to be consistent with rastered images for styling purposes.

### Expected behavior

Rendering SVG images with image thumbnails should not cause high res or low res alternatives, nor should it cause invalid types.

### Actual behavior

It does.

## Additional Information

Maybe I'm wrong, but I also think `cacheBuster: true` isn't working for SVG images. I'm still getting the URL without cache-buster prefix when calling `.getSrc()` or `.getThumbnail()`

**Comment by brusch** [comment]
Cache buster works for me, used the following code: 
```twig
{{ pimcore_asset(368).thumbnail('bernie').html({
    cacheBuster: true
})|raw }}
```

**Comment by NiklasBr** [comment]
> Furthermore the type is invalid, an image does not have the type ìmage/png nor image/webp.

`<img>` does not but `<source>` [does](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source).

**Comment by brusch** [comment]
@NiklasBr  what  @julmot actually meant is that: 
![image](https://user-images.githubusercontent.com/142037/78549984-96e44a00-7803-11ea-8067-cdfa1c5cac96.png)

😉

**Comment by NiklasBr** [comment]
:D I thought it was a general comment: An image does not have the type... which of course it can have, not specific to this .svg bug
