### ISSUE TITLE
[Asset Import from ZIP] Error when folder names contain dots

### ISSUE THREAD

**Issue by rberneder** [pimcore/pimcore#6156]
# Bug Report
### Expected behavior
When uploading a ZIP archive containing folders with dots in their names (like the folder structure below), the corresponding folders in the assets shall be created.
```
19...
  |- 19123.jpg
  `- 19124.jpg
20...
  |- 20123.jpg
  `- 20124.jpg
```

### Actual behavior
An exception is thrown:
```
Warning: ZipArchive::extractTo(/var/www/html/var/tmp/zip-import//): failed to open stream: Is a directory
```

**Comment by dvesh3** [comment]
@rberneder the problem is with folder names mentioned in the example are not valid (at-least on Windows https://docs.microsoft.com/en-gb/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming-conventions) so i assume these folders are created with trailing dots stripped from the name. Is there any error on UI?

**Comment by rberneder** [comment]
@dvesh3 thanks for the reply.
Pimcore v3 allowed dots in folder key names (so also the physical folders had trailing dots in their names). When you want to migrate these assets via a ZIP archive, these trailing dots in the folder names still persist. This causes Pimcore v6 to throw the errors below:
![1](https://user-images.githubusercontent.com/11333457/78684719-1b60c680-78f1-11ea-89d1-35947af23856.png)
![2](https://user-images.githubusercontent.com/11333457/78684724-1bf95d00-78f1-11ea-8927-317b46810fa2.png)

**Comment by dvesh3** [comment]
@rberneder unable to reproduce the issue on windows. Can you please provide a fix?
