### ISSUE TITLE
Personas have no action, send error notice

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#616]
It seems personas have no action possible (GUI Back-End), only conditions.
A notice error is sent:
Error: [Notice] Undefined index: actions in ...\www\pimcore\models\Tool\Targeting\Persona\Dao.php on line 39

Maybe:
`$data["actions"] = Serialize::unserialize($data["actions"]);`
Should be replaced by (if empty is array) :
`$data["actions"] = (isset($data["actions"]) ? Serialize::unserialize($data["actions"]) : array());`

Maybe this is old code wich need to be removed as i don't see in the backend the possibility to add action to a personas (action tab is only available for global targeting rule).

**Comment by brusch** [comment]
That's intentional. 
Personas can't have actions, they have only entry conditions. 

Notice: removed

**Comment by brusch** [comment]
see 8100fa68ab715c93f02fe8e529694791c8ef7975
