### ISSUE TITLE
Codeception is old

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#6161]
https://github.com/pimcore/pimcore/blob/44c8a31cdc01bd699b13dcc968189829f00fd1ce/composer.json#L103

[Codeception ](/codeception/codeception)installed is 2.4.5, which is not the latest on 2.x, the most recent is 4.1.4. Any reason why it was version locked to 2.4.x?

**Comment by weisswurstkanone** [comment]
see #5827
