### ISSUE TITLE
Resolver/Operator classes used in csv import can't be configured via container

### ISSUE THREAD

**Issue by kwreczycki** [pimcore/pimcore#6164]
# Bug Report

I should be able to configure resolver clasess within container. Right now it's not possible since 
the definition of class is resolved by pimcore in pimcore/lib/DataObject /Import/Resolver/Code.php, class in line 37 by "new", without getting object from container.

### Expected behavior
```php
        /** @var ResolverInterface $resolverImplementation */
        $resolverImplementation = $container->get($config->resolverSettings->phpClass());
```

### Actual behavior
```php
        /** @var ResolverInterface $resolverImplementation */
        $resolverImplementation = new $config->resolverSettings->phpClass();
```

####
```yml
services:
     MyApp\MyResolver: ~
     public: true 
```

```php
namespace MyApp;

class MyResolver extends AbstractResolver {
   public function __construct(LoggerInterface $logger) {
          $this->logger = $logger;     
   }
}
```

**Comment by weisswurstkanone** [comment]
Be aware that this needs more ... the whole UI part.

Please feel free to create a PR :-)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
