### ISSUE TITLE
[DataObject][Advanced Many-to-Many Relation] Object cannot be saved with boolean columns

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#6178]
Steps to Reproduce: 
- Create Class with many-to-many relation with boolean columns - as this one 
[class_Test_export.zip](https://github.com/pimcore/pimcore/files/4442570/class_Test_export.zip)
- Create object with that class, assign relation and save --> all fine
- Reload object and then save object again without changing relation field --> error message
![image](https://user-images.githubusercontent.com/8792145/78641232-357ab480-78b1-11ea-8068-661972168c0f.png)
- Changing something in relation field and save again --> all fine again.

**Comment by dvesh3** [comment]
**Root cause:** When AdvancedObjectSearch plugin is enabled, it calls the `getForWebserviceExport` which delivers different results for bool columns when loading the data 0/1(not true/false) so ES tries to map the initial values which are true/false leads to mapping_parsing_exception.
