### ISSUE TITLE
Zend Paginator is abondoned, replace with Laminas?

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#6187]
[zendframework/zend-paginator](/zendframework/zend-paginator) is abandoned and suggests  [laminas/laminas-paginator](/laminas/laminas-paginator) instead. Listing classes will need to implement `Laminas\Paginator\Adapter\AdapterInterface` which is likely a BC break.

Something for Pimcore 7.0 perhaps?

**Comment by vmalyk** [comment]
@brusch , I suggest to change Zend packages to Laminas in next major release and use laminas/laminas-zendframework-bridge for using new packages without code update now and prepare to full code migration in 7.0 (or maybe a bit later - 7.1, 7.2).
What do you think?

Thanks!

**Comment by tecbird** [comment]
+1, please update and use laminas instead of deprecated zend modules
