### ISSUE TITLE
[Tag & Snippet Management] Make it possible to specify location where tags are generated

### ISSUE THREAD

**Issue by julmot** [pimcore/pimcore#6189]
# Feature Request

## Feature description

Currently, Pimcore Tag & Snippet Management is an [undocumented feature](https://github.com/pimcore/pimcore/issues/1205#issuecomment-609609305). And it's currently not possible to specify the location where exactly tags are generated. You can configure Start/End within Head oder Body, but there are no blocks like `{{ pimcore_head_script() }}` that you can use. This causes problems like https://github.com/pimcore/data-hub/issues/188 and others.

My current problem: I'm embedding Freshchat with Pimcore Tag & Snippet Management. So I see visually where it gets embedded. And it gets embedded everywhere. I don't want it to be embedded e.g. in the Preview Mode of documents. But there's no chance I can configure this in my template. I would have to create a RegExp condition (if possible).

It would be good to give developers control over any stuff that is embedded into the generated HTML code. Otherwise this feels like loosing control.

**Comment by dvesh3** [comment]
Document along feature: how to disable Tag & Snippet Management in code https://github.com/pimcore/data-hub/pull/202/files

**Comment by brusch** [comment]
Obsolete see #7320
