### ISSUE TITLE
Select/Multiselect element object grid/export for value/display name

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#619]
I just tried on pimcore demo how is display select and multiselect in grid and export.

Actually in grid we have: display value for select and values for multiselect:
![gridlist](https://cloud.githubusercontent.com/assets/9025839/15604470/e2d49fba-2400-11e6-8f97-c8492546f783.png)

And in export, we have values for both:
![exportcsv](https://cloud.githubusercontent.com/assets/9025839/15604478/ee922728-2400-11e6-8003-88d8f4117487.png)

It is great to have display value for people filtering grid list as it is more "human" or non english languages (chinese, russian, japanese, etc.). Could be need in export too (for excel rework/analysis by non-technical manager/director).
On other side values are needed for technical people (search in the grid or reimport CSV in others systems which need link by value, wich make sense to use values as it is non-utf8).

Could it be possible to have both displayed in the grid and in the export so it matche all case ? If it is not possible, maybe have display value for multiselect too (more human reading and to be coherent with select field) and in csv export for field of type select/mutiselect add a colum with display names (programmaticaly during csv preparation).

Thanks.

**Comment by brusch** [comment]
Hmm, I don't think it is a good idea to put both values into the export. Yes, that's probably solving your very specific use-case, but makes many other problems. Just think of an export which is used to import data to a different system or is edited in Excel an re-imported. This seems to me the more common use-case for the exports. So in my opinion is better to stay in the format as it is now. 

Feedback is always welcome!

**Comment by Yivan** [comment]
Yes you ara right, i wasn't thinking about export and re-import but it could break to have multiple colomn for same field.
And was it intentionnal that simple select display the "display value" on the grid and multiselect display the "values" ? Maybe multi select should display on the grid the "display value" (separated by comma as it is already) as filter on multiselect column use the "display value".

**Comment by pradeep-pimcore** [comment]
@brusch I think we should achieve this by creating an operator.

**Very Demanding Use Case**:
Many times we create a master class for an entity ( for example Manufacturer ). And then we create an Option provider for
for a select type field in our product class.In this case, in majority of the time the value in the option is the master entity's ID and display name is the name/code of the entity.

Now if a user exports the product with this select then the export file contains the id of the master entity not name/code.
In this case this exported data is of no use to a distributor or some other third party.

To resolve this issue and keeping the above mentioned import use case in mind, Pimcore can provide an easily usable operator to export the display name of the selected option instead of the value.

**Comment by Yivan** [comment]
Back on this old subject, because more and more needs on this ; )

For those who need (maybe @pradeep-pimcore) of being able to export displayed value, it is possible to use "PHP Code" operator with code like this one. Field must be child:

![image](https://user-images.githubusercontent.com/9025839/101958179-19c76b00-3c03-11eb-9d1f-00d0fd6cbc9c.png)

@brusch If you think it is valuable to be added to default Pimcore operators, you can add it in source code Pimcore so it will be more easier to use for enduser.

```
<?php

namespace AppBundle\Operators;

use Pimcore\DataObject\GridColumnConfig\Operator\AbstractOperator;
use Pimcore\DataObject\GridColumnConfig\ResultContainer;

class SelectDiplay extends AbstractOperator
{
    private $additionalData;
    
    public function __construct(\stdClass $config, $context = null)
    {
        parent::__construct($config, $context);

        $this->additionalData = $config->additionalData;
    }

    public function getLabeledValue($element)
    {
        $displayValue = "";
        $childs = $this->getChilds();
        if (count($childs) === 1) {
            $fieldDefinition = $childs[0]->getLabeledValue($element)->def;

            // Single select
            if ($fieldDefinition instanceof \Pimcore\Model\DataObject\ClassDefinition\Data\Select) {
                $fieldName = $fieldDefinition->getName();
                $getter = 'get' . ucfirst($fieldName);
                if (method_exists($element, $getter)) {
                    $options = \Pimcore\Model\DataObject\Service::getOptionsForSelectField($element, $fieldName);
                    $value = call_user_func_array([$element, $getter], []);
                    $displayValue = $options[$value]; 
                }
            }

            // Multiselect
            if ($fieldDefinition instanceof \Pimcore\Model\DataObject\ClassDefinition\Data\Multiselect) {
                $fieldName = $fieldDefinition->getName();
                $getter = 'get' . ucfirst($fieldName);
                if (method_exists($element, $getter)) {
                    $options = \Pimcore\Model\DataObject\Service::getOptionsForSelectField($element, $fieldName);
                    $values = call_user_func_array([$element, $getter], []);
                    $displayValueArray = [];
                    if (is_array($values)) foreach ($values as $value) {
                        $displayValueArray[] = $options[$value];
                    }
                    $displayValue = implode(',', $displayValueArray);
                }
            }
        }

        $result = new ResultContainer();

        $result->setValue($displayValue);

        return $result;
    }
}
```

**Comment by pradeep-pimcore** [comment]
@Yivan I tried a similar kind of approach. I created an operator for this. But operators fail when you try to apply then on 
an attribute of an object brick. (https://github.com/pimcore/pimcore/issues/6713). This is a bug in Pimcore.

As far as i can remember  $childs[0]->getLabeledValue($element) function does not do its job in case of brick attributes. Though not sure now.

**Comment by Yivan** [comment]
I didn't try it on object brick, thanks for this warning ! https://github.com/pimcore/pimcore/issues/6713 has been fixed just yesterday.
