### ISSUE TITLE
Full-Page-Cache: Wrong links in multi site system

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#6199]
# Bug Report

In a system with multiple sites I can't activate Full-Page-Cache. Because the links a often wrong. I think the backend previews have the same cache as the frontend.

In the backend the links are with the complete system uri. 
In the frontend, they should be shortened without the site uri.

**Comment by brusch** [comment]
@blankse can you describe the problem a bit more in detail? 
Or even provide a fix, the full page cache is pretty simple, so maybe even quicker 😉
https://github.com/pimcore/pimcore/blob/23e5ff63213f688563101087ad6a78981f11d5ed/bundles/CoreBundle/EventListener/Frontend/FullPageCacheListener.php#L36

**Comment by blankse** [comment]
@brusch I am in debugging in the moment and try to make a fix.

I think its not the problem of links in the current document but the links in snippets. The Snippet Tag has its own cache, when Full-Page-Cache is activated.

I can reproduce it:
- Clear Full-Page-Cache
- Open Site in Frontend (Links ok)
- Clear Full-Page-Cache
- Open Site in Backend
- Open Site in Frontend (Links wrong)

**Comment by blankse** [comment]
@brusch I created a PR
