### ISSUE TITLE
Resend email

### ISSUE THREAD

**Issue by to-bee** [pimcore/pimcore#620]
### Expected behavior 
 Resend email

### Actual behavior  
Email not sent
  
### Steps to reproduce  
Settings -> Emails -> Sent Emails -> Click on  the right side to resend.

**Comment by brusch** [comment]
Any more details on that? 
Anything in the logs? Any error message? 
What's the server response for the ajax request which send the email? 
Does normal email work? 

Thanks!

**Comment by to-bee** [comment]
Hi Bernhard

Below you can find the error of the ajax request. Normal email is working.
We are sending over smtp. Sendmail is disabled on the server.

[image: Inline image 3]

[image: Inline image 1]

The test email content was (send testmail)

[image: Inline image 6]

The query params (resend)

[image: Inline image 5]

Here is another issue:
System settings -> Email -> Imap Settings
- Password shouldn't be cleartext
- Host and Port field content is not saved yet

[image: Inline image 4]

I am using pimcore 4.0.0.
Thank you for programming such a great product. We love pimcore!

Just ask if you need more informations

Tobias








www.wallscrapers.ch

Tobias Ernst
Tüftelstrasse 53
5322 Koblenz
079 325 96 40

**Comment by brusch** [comment]
Your problem seems to be caused by the debug mode. 
Should be fixed in the latest build => 3804
