### ISSUE TITLE
Data lost in 'Allowed Class' in 'Advanced Many-to-Many Object relation' field in class settings.

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#6210]
1. Add an 'Advanced Many-to-Many Object relation' field in class and add some metadata fields as well.Do not close the class settings and do select any other attribute in the class.

![Screenshot from 2020-04-12 22-32-22](https://user-images.githubusercontent.com/21308144/79075695-0e3d4080-7d12-11ea-842b-1c3f94e7a35d.png)

2. Now create an object,We are able to assign objects.

![Screenshot from 2020-04-12 22-32-52](https://user-images.githubusercontent.com/21308144/79075792-84da3e00-7d12-11ea-87e6-a2460052a5f0.png)

3.Now enable 'Enable Batch Edit for Columns' and save the class.Please note do not reload class definition or change the attribute.

Now enable Allow Multiple Assignments' and save the class.Please note do not reload class definition or change the attribute.

![Screenshot from 2020-04-12 22-33-12](https://user-images.githubusercontent.com/21308144/79075887-311c2480-7d13-11ea-95a9-d5fa3f5818a3.png)

5.Now reload the object

![Screenshot from 2020-04-12 22-37-37](https://user-images.githubusercontent.com/21308144/79075920-6b85c180-7d13-11ea-85eb-78c4c4f823aa.png)

This issue occurs when you open the 'Advanced Many-to-Many Object relation' settings and save class multiple times without switching to the any other field or reloading class definitions.

**Comment by brusch** [comment]
That's not really a bug, you're changing the class definition, that's all ...

**Comment by neha04** [comment]
> That's not really a bug, you're changing the class definition, that's all ...

but I am not changing the class name or the visible columns.Why does enabling batch edit for columns or allowing multiple assignments change my selected class or the visible fields ?
