### ISSUE TITLE
Docblocks in generated classes/objectbricks

### ISSUE THREAD

**Issue by bramstroker** [pimcore/pimcore#6211]
All generated definition files for classes and objectBricks contain docblocks with "Changed by" and "Generated at" fields.
As mentioned in the Pimcore manual these files should be committed to version control to keep DB structures consistent among DTAP environments. However these two fields obviously cause changes everytime a field is added and cause merge conflicts during GIT merge process.
In my opinion this information has no added value so it should be removed to make the GIT workflow less frustrating. 
We tried by extending/event listeners etc. to modify this behaviour, but this part of Pimcore code is designed in such a bad way this is no option. So the only solution left is to modify the Pimcore core code.
What do you think? Should we remove the two docblock fields or make this configurable somehow? We could provide a PR for this.

**Comment by weisswurstkanone** [comment]
I believe the reason for that is that we want to track the modification user  and timestamp in case a customer with admin permissions does his own class modifications which is then hard to prove otherwise.

**Comment by dpfaffenbauer** [comment]
I agree with @bramstroker on this one. ClassDefinitions should only change what actually has been changed. If you want to know when it changed, check git..

**Comment by weisswurstkanone** [comment]
Well, I am basically talking about a running live system. Just imagine a customer messing up his classes and then claims he didn't. Maybe find a better solution for that.

**Comment by gdvisser** [comment]
I would prefer a specific log table to track changes made by admin users.
This also gives the possibility for a UI change log grid.

**Comment by bramstroker** [comment]
> I believe the reason for that is that we want to track the modification user and timestamp in case a customer with admin permissions does his own class modifications which is then hard to prove otherwise.

In the documentation it is mentioned that definition files should be commited to GIT: https://pimcore.com/docs/5.x/Development_Documentation/Deployment/Deployment_Tools.html#page_Pimcore-Class-Definitions.
This implies in our case that product admin's may never create class attributes themself, but this must be done by developers which commit the changes to GIT. This is the workflow we use for 3 of our Pimcore projects currently. Or I must be missing something here?

When you have a single environment (can't imagine this case in professional development) and allow direct changes of classes by customers than still this docblock does not prove anything.
Imagine customer A changes a class, and 5 minutes later customer B changes another. How can you know the changes were done by customer A or customer B?
A better option would be what @gdvisser mentioned to keep track of all changes in a DB, but still you are rebuilding GIT this way ;-)

**Comment by weisswurstkanone** [comment]
I agree, but in real life it turns out that some customers want to adapt at least minor things such as tooltips, static layout elements and so on.

I also agree that the current solution is not ideal and changes should be tracked somewhere else.

**Comment by bramstroker** [comment]
@weisswurstkanone Could you discuss this issue internally with the other core devs. I can provide a PR for removing the docblocks or make this configurable, as this solves our current highly frustrating problem. But I don't have time / resources to create a fully blown audit log UI / datastructure, and also don't see the added value of such feature.

**Comment by brusch** [comment]
@bramstroker removing the doc-block would be fine for me (at least the changing bits), I don't think this needs to be configurable. 
Looking forward to your PR 😊

**Comment by blankse** [comment]
ClassDefinition has also a modificationDate which will change everytime:
![image](https://user-images.githubusercontent.com/998558/79567015-c02e9100-80b3-11ea-81ad-980141e05c0a.png)
