### ISSUE TITLE
Opening object grid in admin throws getPermission() on null error

### ISSUE THREAD

**Issue by pspierce** [pimcore/pimcore#6217]
Pimcore 6.6
When loading an object in the admin interface by non-admin users, Call to a member function getPermissions() on null is thrown.
### Expected behavior
No error thrown.
### Actual behavior
Timestamp: Tue Apr 14 2020 12:28:13 GMT-0400 (Eastern Daylight Time)
Status: 500 | Internal Server Error
URL: /admin/object-helper/grid-get-column-config
Message: Call to a member function getPermissions() on null
Trace: 
in /var/www/pim/vendor/pimcore/pimcore/models/DataObject/Service.php:573
#0 /var/www/pim/vendor/pimcore/pimcore/models/DataObject/Service.php(1408): Pimcore\Model\DataObject\Service::getLanguagePermissions(NULL, Object(Pimcore\Model\User), 'lView')
#1 /var/www/pim/vendor/pimcore/pimcore/models/DataObject/Service.php(1427): Pimcore\Model\DataObject\Service::enrichLayoutDefinition(Object(Pimcore\Model\DataObject\ClassDefinition\Data\Localizedfields), NULL, Array)
#2 /var/www/pim/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php(1277): Pimcore\Model\DataObject\Service::enrichLayoutDefinition(Object(Pimcore\Model\DataObject\ClassDefinition\Data\Block), NULL, Array)
#3 /var/www/pim/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php(732): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectHelperController->getFieldGridConfig(Object(Pimcore\Model\DataObject\ClassDefinition\Data\Block), 'grid', 5, false, NULL, Object(Pimcore\Model\DataObject\ClassDefinition), '64915')
#4 /var/www/pim/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php(493): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectHelperController->getDefaultGridFields(NULL, Object(Pimcore\Model\DataObject\ClassDefinition), 'grid', NULL, Array, Array, '64915', Array)
#5 /var/www/pim/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php(347): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectHelperController->doGetGridColumnConfig(Object(Symfony\Component\HttpFoundation\Request), Object(Pimcore\Config))
#6 /var/www/pim/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectHelperController->gridGetColumnConfigAction(Object(Symfony\Component\HttpFoundation\Request), Object(Pimcore\Config))
#7 /var/www/pim/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#8 /var/www/pim/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(198): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /var/www/pim/web/app.php(37): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#10 {main}

### Steps to reproduce
Open object in admin as non-admin user.

### Code example
```php
// your code
```

# Feature Request

**Comment by weisswurstkanone** [comment]
Additional info: 
- Localized field inside block like this
- block visible in grid view (checkbox doesn't make sense, should be removed)

![image](https://user-images.githubusercontent.com/6142086/79260357-731da580-7e8e-11ea-8810-439040d84f27.png)

**Comment by pspierce** [comment]
Unchecking "Visible in Grid View" for the block fixed the issue.  Thanks.

**Comment by pspierce** [comment]
haven't checked 6.6.1 yet, will try to do so tonight but the issue returns when searching (Search Objects) to insert an object into a many-to-many object relation despite the "Visible in Grid View" being unchecked in the searched for class.

**Comment by weisswurstkanone** [comment]
Please check 6.6.1. I am not able to reproduce what you describe for that release.

**Comment by pspierce** [comment]
Yes, 6.6.1 appears to have dealt with it.  Thanks.

**Comment by eramit11** [comment]
I have face some issue and find other solutions.  there are some junk data in gird table and aftarthat  deleted unused and junk datat and clear cache...now working fine for me.
Table :Table: gridconfigs
