### ISSUE TITLE
Tag : missing useful Tag::getByName() method

### ISSUE THREAD

**Issue by FredoVelcro** [pimcore/pimcore#6229]
Hello,

I wonder how to get a Tag by its name instead...
Maybe i missed something but a getByName() is not present...
Thanks you

**Comment by weisswurstkanone** [comment]
which kind of tag ? can you provide the full namespace?

**Comment by FredoVelcro** [comment]
For DataObject objects....it's Pimcore\Model\Element\Tag i think ?

**Comment by weisswurstkanone** [comment]
it is missing, can you create a PR ?

**Comment by FredoVelcro** [comment]
great

**Comment by FredoVelcro** [comment]
https://github.com/pimcore/pimcore/pull/6231

**Comment by FredoVelcro** [comment]
https://github.com/pimcore/pimcore/pull/6234

**Comment by brusch** [comment]
I'm afraid that `getByName()` doesn't make sense, since the same name can exist in different hirarchy levels. 
It's probably better to use the existing `getByPath()` instead (added by #6964)
