### ISSUE TITLE
[Multi-channel implementation] : Question

### ISSUE THREAD

**Issue by abernardgalilee** [pimcore/pimcore#6230]
# Feature Request

## Feature description
Dear all.
We face more and more competition with Akeneo whose solution provides a notion a of multi-channel for objects. 
Globally they use the following tree architecture : 
Category
    - Products
        - Article
Articles are very well handled in pimcore when using variants for exemple and can be directly attached to products in the tree for example and then products can be attached to categories, no problem. All your demo scenario is fine up to this point.

The question is when we need to have different prices, descriptions, titles, images for different channels. Then we would need to have variants on a per channel based which would let the left navigation bar tree unreadable for users.
-> how would you handle multiple-channels where only a certain number of fields of the articles/products/category would vary? This channel would also contain only parts of the original channel also.
-> how would you let users dedicated to specific channel only see objects of their own channels but not objects of channels they are not assigned to?

This is more a global roadmap question or approach which you might have already thought of with other users.

Hope this question makes sense.

Looking forward to earring from you, 

Arnaud.

**Comment by dpfaffenbauer** [comment]
This would come in handy for these kinds of scenarios: https://github.com/pimcore/pimcore/issues/3691

For CoreShop we solved different prices by adding a custom data-object editable and disabling channels (Stores as well call them there) with a multiselect. We don't have any features for different titles or something like that.

**Comment by abernardgalilee** [comment]
Dear Dominik. 
Just for me to understand well, therefore there is no plan today to handle this kind of problematic? Am I right? Since of course, normally we would need inheritance accros channels and generally speaking not over  all fields in the product/article object.
The idea would be to be able to have a kind of primarily Channel to start with.
Then all categories/products/articles would be created into this channel.
Then, a user would create another channel. Products/Articles could be sent from one channel to another keeping inheritance.
Regarding the left object tree, one could only see the active channel and of course not all of them at the same time.

**Comment by dpfaffenbauer** [comment]
no, that is not possible at the moment

**Comment by dpfaffenbauer** [comment]
not like this at least

**Comment by brusch** [comment]
Probably better to discuss this topic in our forums ... https://talk.pimcore.org/
