### ISSUE TITLE
[Bug] Localized field and objectbricks

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#6238]
Hello,

There is a problem with localized fields and objectbricks.
I don't know if we can put objectbrick in localized field. I was thinking not, but the system can be tricked because we can drag and drop objectbrick in localized field section:

![image](https://user-images.githubusercontent.com/9025839/79474330-8d7a8f00-8006-11ea-8f84-8141af9d40c9.png)

Saving the object work well, does it means objectbrick can be in localized field ? We have a project where we wanted to do this for modeling reason. So it would be great.

Proposed fix:
- If objectbrick can be inside localized field : allow creating of objectbrick directly inside (actually gui doesn't provide objectbirck as choice)
- If not, forbid the drag and drop

EDIT : by the way same trick can be done with fieldcollection, and maybe other fields.

Best regards

**Comment by brusch** [comment]
Yes, that's a known issue, which we're not going to fix, because this would need too much additional code and would have bad effects on the user experience. 
Thanks anyway for reporting 😊
