### ISSUE TITLE
6.6.1 Migration 20200407132737 failed during Execution. Error Index '' does not exist on table 'uuids'.

### ISSUE THREAD

**Issue by picman** [pimcore/pimcore#6241]
The table _uuids_ in MySQL hasn't got a primary key just an unique key.

```bash
mysql> show create table uuids;
```

```sql
CREATE TABLE `uuids` (
  `uuid` char(36) NOT NULL,
  `itemId` bigint(20) unsigned NOT NULL,
  `type` varchar(25) NOT NULL,
  `subType` varchar(20) DEFAULT NULL,
  `instanceIdentifier` varchar(50) NOT NULL,
  UNIQUE KEY `itemId_type_uuid` (`itemId`,`type`,`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |
```
Then in the migration:

```php
public function up(Schema $schema)
    {
        $table = $schema->getTable('uuids');

        $table->dropPrimaryKey();
        $table->setPrimaryKey(['uuid', 'itemId', 'type']);
    }
```

=>

```php
public function dropPrimaryKey()
    {
        $this->dropIndex($this->_primaryKeyName);
        $this->_primaryKeyName = false;
    }
```

The call **dropIndex** with '' as the parametr causes the error, I think.

**Comment by picman** [comment]
A workaround for MySQL:

```sql
alter table uuids drop key itemId_type_uuid;
alter table uuids add primary key itemId_type_uuid(`itemId`,`type`,`uuid`);
```
Then re-run the migration:

```bash
$ bin/console pimcore:migrations:migrate -s pimcore_core -n
```
And everything is Okay.

**Comment by brusch** [comment]
@picman don't know why you are having a unique index instead of a primary, but it was definitely a PK before, see: 
https://github.com/pimcore/pimcore/commit/f9363b0555f2dccee45eb629712e3792d3159a70#diff-b5d94657594dd75c59d829fedc5c39beL749

**Comment by picman** [comment]
Neither do I. Thank you for your feedback.

**Comment by brusch** [comment]
Just checked the entire history and it has been a PK ever since, ... very strange.

**Comment by picman** [comment]
Don't worry. I've been using Pimcore for many years. I can't rule out that I caused it myself by a manual change in the database during a previous unsuccessful migration. Especially migration to v5 was really painful.

**Comment by M-Ali-Aziz** [comment]
I have the same problem and the workaround works for me 👍

**Comment by weisswurstkanone** [comment]
@brusch it changed long time ago from unique to primary here (16.09.2016), pimcore 4
https://github.com/pimcore/pimcore/commit/f3ffba3a2afdf2fed28b00df0057883ea681877c

we could add something like

if($table->hasIndex('itemId_type_uuid) {
    $table->dropIndex('itemId_type_uuid'):
}

**Comment by brusch** [comment]
@weisswurstkanone let's keep it as it is for now, since this is probably caused by a failed Pimcore 4 migration we shouldn't mix that up.

**Comment by weisswurstkanone** [comment]
ok, didn't check if a pimcore 4 migration would cover this

**Comment by brusch** [comment]
Ah, ok me neither, maybe you can check that, if not we can of course include your proposed solution. 
Thanks a lot!
