### ISSUE TITLE
XLIFF Export/Import does not work properly

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#626]
When i try to translate a given english page, the translation will append the content to the wrong language context. This has been tested on the demo environment.

## Document

**Scenario 1** 
[Video 1](http://recordit.co/aM7FeXsSq3)

Then i tried to switch the source/target in the export dialog, the problem stays the same.

**Scenario 2** 
[Video 2](http://recordit.co/uEbKfbIXcz)

## Linked Document translation

i also tried to add a new document to a given english document with the translation context menu.

![bildschirmfoto 2016-05-30 um 11 21 52](https://cloud.githubusercontent.com/assets/700119/15645520/3e2829d6-2659-11e6-841a-49e14ef4d6f6.png)

**Issues**
- the translation does not respect the linked document
- the translation behaviour is the same as shown in Scenario 1.

**Comment by solverat** [comment]
**EDIT**: The gifs has been trimmed, i've added the original videos. sorry for that.

**Comment by brusch** [comment]
I guess you misunderstood something :) 
Please see the attached video:  [30-05-_2016_13-02-15.zip](https://github.com/pimcore/pimcore/files/289419/30-05-_2016_13-02-15.zip)

So basically that means: 
The document to export is in EN ans should be translated to DE. 
So we select source EN (which is actually the language of the content) and target DE. 
Now you can translate and import the xliff again.
