### ISSUE TITLE
Endless loop in `TargetingDocument`

### ISSUE THREAD

**Issue by jdreesen** [pimcore/pimcore#6260]
# Bug Report

### Expected behavior
Targeting works.

### Actual behavior
Targeting leads to an endless loop.

### Steps to reproduce
- go to https://demo.pimcore.fun/admin and enable the targeting toolbar
- go to https://demo.pimcore.fun/ and override the e.g. the "Document Target Group" and apply.
-> a blank page with status code `500` appears

---

The change that broke this was: https://github.com/pimcore/pimcore/pull/5960

The problem is, that `PageSnippet::hasElement()` now uses `getElement()` which is overridden in `TargetingDocument` and itself uses `hasElement()`.

See: https://github.com/pimcore/pimcore/blob/2ec7fc523ad6ec0f5322863f5d2b524782cdbbce/models/Document/TargetingDocument.php#L124-L130

---

The problem was previously reported here https://github.com/pimcore/pimcore/issues/5959#issuecomment-615188119 and here https://github.com/pimcore/pimcore/pull/5960#issuecomment-617039050

**Comment by brusch** [comment]
@jdreesen can you confirm #6261 fixes the issue? 
Thanks a lot!

**Comment by jdreesen** [comment]
Yes, it fixes the issue. Thx for the quick fix!
