### ISSUE TITLE
[Bug] Texts that are longer than 190 characters cannot be translated

### ISSUE THREAD

**Issue by skochTC** [pimcore/pimcore#6277]
# Bug Report

### Expected behavior
That every text will be translated ;-)

### Actual behavior
It is not the case.

### Steps to reproduce
Simply write a longer text in the class definition into a layout element.

Now call the object and wait until the translation is added to the database with the request `/admin/translation/add-admin-translation-keys

The database now limits the key to 190 characters according to the column definition.

The key is cut off and can be translated in the admin-translations, but this has no effect, because the translation is always requested with the full text.
My solution is simple, the key is limited to 158 characters, so the context to the real text still exists.
So that the texts do not appear twice, if there are two different texts that start equal, a MD5 hash is created from the complete text and appended to the key.

### Edited on 2020/04/23
It is a bug, because texts that are longer than 190 characters are imported into the database, although they can never be accessed.

If it were the case that 190 characters long texts are not allowed at all I would most likely send a feature request ;-)

More information why this PR is useful, see below.

I hope the PR will be accepted.

**Comment by solverat** [comment]
You’re just doing it wrong. It is symfony standard to use keywords instead of original text phrases. Use „app.my_label“ as key for example and translate it (value is close to unlimited) in your admin translations - and you‘re good to go.

**Comment by skochTC** [comment]
> 
> 
> You’re just doing it wrong. It is symfony standard to use keywords instead of original text phrases. Use „app.my_label“ as key for example and translate it (value is close to unlimited) in your admin translations - and you‘re good to go.

Yes, that is correct. Symfony using keys.

But in the admin area there is a lot of stuff going through the translations that needs to be translated. Or simply written into the translations.

Our use case was for example the WYSIWYG in the class definition for the layout element text, where a div-wrapper is automatically added and would make the translation key unusable.

The class definitions are usually not created by a developer who can switch to source in WYSIWYG and remove the HTML.

My PR doesn't change the behavior of anybody, because it only applies if the text is shortened by the database anyway.

The same applies to languages that the Pimcore software itself automatically generates as admin translation as soon as they are called, there is no identifier available:
![grafik](https://user-images.githubusercontent.com/54348050/80040532-9255ac00-84fa-11ea-8f56-fd94d2b2f3b9.png)

**Comment by dpfaffenbauer** [comment]
Sorry where do you have an wyswiyg in the backend that needs translation? You can always use keys in Pimcore for translations. Also for ClassDefinitions labels and tooltips. I don't see where that doesn't apply.

**Comment by skochTC** [comment]
> 
> 
> Sorry where do you have an wyswiyg in the backend that needs translation? You can always use keys in Pimcore for translations. Also for ClassDefinitions labels and tooltips. I don't see where that doesn't apply.

I've already explained this ;-)
> Our use case was for example **the WYSIWYG in the class definition for the layout element text**, where a div-wrapper is automatically added and would make the translation key unusable.

From a definition out of the Pimcore demo:
![image](https://user-images.githubusercontent.com/54348050/80071614-3cf2bc80-8545-11ea-9960-c346ce7a80b0.png)


Have a look at the Pimcore Demo, there are couple of translation keys that are not and contain html:
![image](https://user-images.githubusercontent.com/54348050/80070915-0f594380-8544-11ea-90b7-fe8da716cda7.png)

If your argument is that a translation can only be used if a valid key is used, it is wrong to push the data into the database.

This will not only generate trash data in the database, it will also result in bad usability due to overcrowded translations.

We have the use case that people adapt the definitions, who are not necessarily trusted to create translation keys and store the fallback translation in a translation YAML. In addition, the people should not have access to the source code.

**Comment by dpfaffenbauer** [comment]
So, you are saying not allowing this will create trash? But: allowing this, will create md5 keys that aren't transparent neither, imagine having a translation that starts quite similar, the key then will start the same, but the md5 doesn't give any clue what the key actually means. Using proper keys solves that.

Also: Having untrused people editing class-definitions is:
 - Quite unsecure anyway, cause it could lead to data-loss
 - People can be trained to use keys and add translations
 - These people don't need to access any YAML, since they can do it in backend using Admin Translations anyway

This change is not good IMO.

**Comment by solverat** [comment]
So true @dpfaffenbauer! Also: Why using this editor in first place? A better approach would be: **Don't** push RTE data to the translation engine! Adding html data as translation keys is totally nonsense!

**Comment by brusch** [comment]
But it dowsn't hurt in my opinion and to be honest, ... for teanslation key the md5 suffix is quite safe.

**Comment by dpfaffenbauer** [comment]
Just because it doesn't hurt, doesn't mean it is good and right.

**Comment by solverat** [comment]
@brusch, you need to revert this! It's also a bc break. 

What if someone already added thousands of keys with a length of 191? They may also have translated them (Even if the key has been shortened to 190 chars)! 

With this change - btw. a evil approach by using md5 in js and php..., they have totally different keys in their translation table and need to translate them again!

**Comment by skochTC** [comment]
> What if someone already added thousands of keys with a length of 191? They may also have translated them (Even if the key has been shortened to 190 chars)!

Please take a look at the issue description:
> The database now limits the key to 190 characters according to the column definition.

This does not work because the key with 191 characters is searched but no key is found because the database only contains a key with 190 characters.

> With this change - btw. a evil approach by using md5 in js and php..., they have totally different keys in their translation table and need to translate them again!

No, because the texts are currently not translatable anyway.

**Comment by skochTC** [comment]
> So, you are saying not allowing this will create trash? But: allowing this, will create md5 keys that aren't transparent neither, imagine having a translation that starts quite similar, the key then will start the same, but the md5 doesn't give any clue what the key actually means. Using proper keys solves that.

The MD5-Hash will only appended at the end. The context is the same as before except for 32 characters at the end.

> but the md5 doesn't give any clue what the key actually means. Using proper keys solves that.

Sure but I have implemented a solution that is more compatible with the current one. There is nothing in the way of using proper keys.

> Also: Having untrused people editing class-definitions is:
>
>    Quite unsecure anyway, cause it could lead to data-loss

The people are trained in Pimcore just not in HTML. 

> People can be trained to use keys and add translations
    These people don't need to access any YAML, since they can do it in backend using Admin Translations anyway

This doesn't make any sense at all, because development is done on internal development instances. Using admin translation every time to export and import is a major disadvantage for code deployments.

**Comment by dpfaffenbauer** [comment]
> This doesn't make any sense at all, because development is done on internal development instances. Using admin translation every time to export and import is a major disadvantage for code deployments.

Doing class changes on the server as well, cause once you change it on the server, you loose it with the next deployment anyway.

Also, you can add translation keys with Migrations.

**Comment by skochTC** [comment]
> Doing class changes on the server as well, cause once you change it on the server, you loose it with the next deployment anyway.

> Also, you can add translation keys with Migrations.

No, there are various workflows for this.

The class definitions are checked into git and a script is automatically executed on deplyment, which rebuilds the class definition.

This is recommended by Pimcore, for this there are the pimcore:deployment commands

But Admin-Translation are stored in the database.

**Comment by dpfaffenbauer** [comment]
sorry what? If you change anything on a class-definition on a server, and you deploy local files again (where class-definitions should be stored), you overwrite all your class-definitions on the server, when running `pimcore:deployment:classes-rebuild` you might also loose data and columns created on the server. That is the recommended workflow.

**Comment by skoch98** [comment]
No, the class definition is never made on the live server.  That would be totally wrong

It will be set up and automatically checked in by us by appropriate personnel, since the people do not have git experience and do not need it.

But this is not about our way of working but about the general pimcore problem with longer texts.

**Comment by dpfaffenbauer** [comment]
so you're saying that trusted people check what untrusted people did before you deploy?

**Comment by solverat** [comment]
True, there is an exception! However, adding RTE data to a translator makes **no** sense to me. This is the totally wrong way of "fixing" it.

**Comment by skochTC** [comment]
So, there are two options:
 - the PR is accepted as it was received
 - the PR will be revoked and open a new one, where keys over 190 characters are not played into the database.

These are two ways of dealing with the matter. Suggestions are welcome.

But making it clear to the client that he can translate the texts, because the key is partly in the database, that is not an option!

Yes, we have misinterpreted the WYSIWYG in the past and the HTML that is sent in here is stupid and has caused some problems.

Additionally the WYSIWYG is a bad field for translatable content. In this case you should consider to extend a field that can be used instead of a translation.

Another, option 2 does not provide a good argument against running countless texts into the database which are not valid keys at all. 

In the Pimcore Demo for example a 505 error message.

In our opinion the Admin Translation can be used for two use cases:
 - for use with keys
 - and for use without a key, since the texts are imported without further action.
Based on this, I think PR is justified.

**Comment by skoch98** [comment]
> so you're saying that trusted people check what untrusted people did before you deploy?

We have misused the wysiwgy in the past.  But that is not the point, again:

> But this is not about our way of working but about the general pimcore problem with longer texts.

**Comment by skoch98** [comment]
The commit was reverted.

@dpfaffenbauer and @solverat is it ok for you, if keys larger than 190 characters are blocked so they are not written to the database?

**Comment by dpfaffenbauer** [comment]
Yes

**Comment by solverat** [comment]
yes

**Comment by skochTC** [comment]
@dpfaffenbauer and @solverat thanks for the detailed feedback in this issue!
