### ISSUE TITLE
[Feature Request] Classification-Store group limitation

### ISSUE THREAD

**Issue by skochTC** [pimcore/pimcore#6285]
# Feature Request

## Feature description
We use the Classification store for the classification system ETIM and will also integrate eCl@ss into a customer project in a few weeks.

Many classification systems are very extensive and allow only one class, in Pimcore group. Unfortunately there is no option to set this in Pimcore via the class definition.

Some months ago I implemented this for a customer project based on a bundle and now I want to share the code in the core.

**Comment by 88Manuel88** [comment]
Hi @skochTC 
I'm trying to study the best aproach on implement ecl@ss in pimcore.
I've tryed with classification store, but with that, user lost track of ecl@ss tree.
Does you have some pointers?

**Comment by skochTC** [comment]
> 
> 
> Hi @skochTC
> I'm trying to study the best aproach on implement ecl@ss in pimcore.
> I've tryed with classification store, but with that, user lost track of ecl@ss tree.
> Do you have some pointers?

For us it was very easy, the customer knows the class numbers :-D

I think here a custom renderer is useful, which represents the tree when clicking on a class an ajax request is resolved to set the e@class class and then reloads the object tab.

pimcore.globalmanager.get('object_2').reload();
Replace "2" with the object id.

Currently I don't know how to implement the assignment directly via Ext-JS (because Ext-jS is not so interactive like Vue or React). Before the reload: The user should confirm that the changes will be applied. Because the function behind the Ajax call has carried out the assignment and creates a new object version.

**Comment by 88Manuel88** [comment]
Hi @skochTC 
Thank you for the reply 👍 

I think I've to draw the entire tree (🌳 unfortunately), so the plan I've made is: new tab with eclass tree, user can pick the code, and it will reload the object_ like you said, when the object is reload you'll have the classification_store with those attributes :)
