### ISSUE TITLE
Converting PDF to text with libreoffice seems no more working (at least Debian)

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#6289]
Hello,

It seems conversion to txt using libre office do not more work, at least on Debian systems.

Code is started from here:
https://github.com/pimcore/pimcore/blob/ae6bf9bef67793dbb5a91ee91a37cbce614b1094/lib/Document/Adapter/LibreOffice.php#L189

Run manually on shell, using a pdf file (take a really light one in size please):
`/usr/bin/soffice --headless --nologo --nofirststartwizard --norestore --convert-to txt:Text mydoc.pdf`
Returns:
```
convert /var/www/html/git-excluded/mydoc.pdf -> /var/www/html/git-excluded/mydoc.txt using filter : "Text"
Error: Please verify input parameters... (SfxBaseModel::impl_store <file:///var/www/html/git-excluded/mydoc.txt> failed: 0x81a(Error Area:Io Class:Parameter Code:26))
```

If you take some more big PDF, the command line stay struggle and the cpu works hard... command **never finish** (i must do CTRL+C). **Here this is problematic as it can be CPU/memory hogger.**

I tried to search through internet (libreoffice github, etc.) and it seems text filter has been removed from some distribution:
Redhat: https://ask.libreoffice.org/en/question/82541/how-can-i-install-all-the-convert-to-filters-i-am-missing-txttext-but-have-pdf/
And debian (this is my test environment)

Going further, i upload a very simple PDF in the assets section, and just right after made a search with a string contained in the PDF... nothing is returned.
I made the test on the Pimcore online demo, and same. It uses Debain buster too, so same libreoffice version I imagine.
But from the Pimcore code if libreoffice fail it should use pdftotext (parent method ghostscript adapter).
**So there is this libreoffice pbl, but why it don't fall back to pdftotext after ? At the end no text is indexed from the PDF into the database.**

So it is not a bug with Pimcore, but the tool (libreoffice) and to me more exact the filter txt works no more.
This is a really great feature to be able to search through documents, and having it working is a really good feature for DAM I think.

I tried to update libre office using the backport on buster (really recent version of libreoffice), but same problem.

Feel free to ask any further questions to help.

EDIT: here the comment seems to say we should have a PDF ?? Is it a just a typo pbl https://github.com/pimcore/pimcore/blob/ae6bf9bef67793dbb5a91ee91a37cbce614b1094/lib/Document/Adapter/LibreOffice.php#L202 and should be `Couldn't convert document to TXT` i imagine.

Sorry if this post is a little confuse, i wanted to give as many insight as possible.

Thanks.

**Comment by dvesh3** [comment]
Hi @Yivan please confirm, if you have maintenance job running for your application, which executes the `AssetDocumentConversionTask `command wihch generates previews asynchronously in the background and then `SearchBackendListener ` indexes the document content. 

Also, I have provided a PR https://github.com/pimcore/pimcore/pull/6460 for `SearchBackendReindexCommand` so that it will not have any dependency on `AssetDocumentConversionTask `for page count processing.

**Comment by Yivan** [comment]
Hello @dvesh3 thanks for looking into it.

I just tried and after running maintenance, and text was well indexed : )

But it used GhostScript, not LibreOffice (I saw it in the logs).
GhostScript has precedence on LibreOffice, so it will work as long... ".pdf" is in lowercase.
Reproducing the same with ".PDF" run the problem i talk about in my first post.

Maybe **as a supplementary fix**, as I think it could come from this regex which should be made case insensitive:
https://github.com/pimcore/pimcore/blob/891b0f6faa31ce48893f76810b381088df83610c/lib/Document/Adapter/Ghostscript.php#L56
So at least on debian/redhat (where libreoffice seems no more having text filter) it will work always as long GS is installed, as GS will be tried first (https://github.com/pimcore/pimcore/blob/18f714eacb4874522b1f15d05c18965d8b785040/lib/Document/Adapter/LibreOffice.php#L184).

But it won't fix the pdf problem for system using libreoffice. I don't think Pimcore can do something on this (as the cli soffice don't work). Maybe using another filter `txt:Text` than the currently used which is no more available.
**As a possible improvement** having a way to disable LibreOffice text conversion would be a solution (if libreoffice is needed on the OS system so uninstalling it is not a solution).

Thanks!

**Comment by dvesh3** [comment]
GhostScript takes priority over LibreOffice so disabling LibreOffice text conversion would not help here. Even when text conversion fails with Libreoffice then Ghostscript is used as fallback. I'm marking this issue as "Third party Bug" as it is related to specific version of Libreoffice installed on server.
