### ISSUE TITLE
Mix of Collations (betwen ascii_general_ci and utf8mb4_general_ci)

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#6299]
Our monitoring brought up a mix of collations exception (Doctrine\DBAL\Exception\DriverException), thrown here:

https://github.com/pimcore/pimcore/blob/f42667508e6b475a64844ae0e2348a0195169b7f/bundles/CoreBundle/EventListener/ResponseExceptionListener.php#L157-L163

Sometimes `$request->getUri()` obviously returns an utf8 string (usually this should be a encoded string, I was not able to reproduce it by myself, only after I changed the value of `$uri` to "https://a-wüde-uörl"` by hand. But hey, monitoring tools never lie. 

I'm not sure how to fix this. Should we change the collation or should we assert the provided string?

***

Btw. there are two rows with a `ascii_general_ci`collation, and they may receive utf8 data, right?. 

https://github.com/pimcore/pimcore/blob/ca3c569a87d2e634ac5178055148305d1e89e6b4/bundles/InstallBundle/Resources/install.sql#L135

https://github.com/pimcore/pimcore/blob/ca3c569a87d2e634ac5178055148305d1e89e6b4/bundles/InstallBundle/Resources/install.sql#L314

**Comment by brusch** [comment]
Thanks for reporting, I assume this is a leftover from the times where Pimcore didn't support utf8 URLs.
So this just needs to be changed to `utf8_bin` and the length should be reduced as well.
