### ISSUE TITLE
[VersionsCleanupTask] All Versions gone

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#6301]
See here:

https://github.com/pimcore/pimcore/commit/cd1d124b0a061f12608180d03c8d725edaed0bf4#diff-1b42cadef0498a448a437b2a7b67f775

```php
$conf['document'] = $this->config['documents']['versions'] ?? null;
$conf['asset'] = $this->config['assets']['versions'] ?? null;
$conf['object'] = $this->config['objects']['versions'] ?? null;
```

returns:

```bash
Array
(
     [document] =>
     [asset] =>
     [object] =>
)
```

Because of `\ArrayAccess`, `isset($this->config['documents']['versions'])` returns `false`.

That said, every pimcore instance > 6.5.2  will have no versions anymore after the maintenance has been executed.

This is huge.

**Comment by fashxp** [comment]
see also https://github.com/pimcore/pimcore/issues/6265

**Comment by dvesh3** [comment]
Hi @solverat can you please share more insights like environment, php version and so? for me `isset($this->config['documents']['versions'])` returns true even when running task in isolation.

**Comment by solverat** [comment]
php 7.3, debian. Happens on production and also on development production. Also on different installations.

**Comment by dpfaffenbauer** [comment]
Also with PHP7.4 on debian

**Comment by fashxp** [comment]
not for us

**Comment by dpfaffenbauer** [comment]
Have you tried it with the pimcore/docker images? it happens for me with them

**Comment by fashxp** [comment]
just did

**Comment by dpfaffenbauer** [comment]
Could it be you fixed it in a newer version? I tested it with 6.5.2

**Comment by dvesh3** [comment]
could you please check if this fixes your issue? https://github.com/pimcore/pimcore/pull/5920

**Comment by dpfaffenbauer** [comment]
I'll test it later, have to update the project anyway. I'll let you know in the afternoon

**Comment by solverat** [comment]
@dvesh3 yes, i can confirm it - fixed with 6.5.3!

**Comment by dvesh3** [comment]
thank you @solverat for your confirmation 👍

**Comment by solverat** [comment]
Hopefully no one on this planet is on version 6.5.2 - except us idiots.
