### ISSUE TITLE
Attributes with multiselection type of field form Classification don`t allow to filter

### ISSUE THREAD

**Issue by Bartosz-UG** [pimcore/pimcore#6307]
Hello,

There is a problem with filtering at grid during using multiselection field. I am talking about multiselection field form **classification store.**

**Expected behavior**
When I add multiselection attributes form classification store to grid I would like to 
filter using this attribute column.  In this case, by checking the desired field values.

**Actual behavior**
I add  attributes form classification store (by using Grid Option) to product grid. When I try to filter the option there is no product  on the product grid despite the fact that the attributes have a filtered value.

**Steps to reproduce**
1. Adding  attributes form classification store to the product grid by using Grid Option.
2. I unfold filter options in the column
3. I select the desired value filter option
4. I get empty grid

**Comment by Bartosz-UG** [comment]
@fashxp 
Hello, 
Would you like to take a look at this issue or pass to the right person?

**Comment by fashxp** [comment]
We have classified this as bug and will have a look at it as soon as possible. 
to speed things up we are happy to merge pull requests.

**Comment by Bartosz-UG** [comment]
@fashxp 
Hi, I would like to ask about status of work on this bug. Do you have any information when this bug can be resolved?

**Comment by fashxp** [comment]
sorry, not more than in my last comment ...

**Comment by Bartosz-UG** [comment]
Hi Christian! Is there any news on this bug? Can you estimate when the bug will be taken?

**Comment by brusch** [comment]
@Bartosz-UG sorry, this bug is currently not on our priority list.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Comment by kingjia90** [comment]
Resolved by https://github.com/pimcore/pimcore/pull/13130
