### ISSUE TITLE
Error in cloning image gallery or copying any layout having image gallery.

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#6314]
- Unable to copy/paste any layout consisting of image gallery attribute.
- Js error while copying image gallery.

![Screenshot from 2020-04-29 15-05-06](https://user-images.githubusercontent.com/21308144/80581747-3ecbec80-8a2b-11ea-9705-b74d75243758.png)

**Comment by weisswurstkanone** [comment]
@neha04 , can you provide a fix please  ?

**Comment by neha04** [comment]
#6315
