### ISSUE TITLE
Clarify purpose of apcu

### ISSUE THREAD

**Issue by juckerf** [pimcore/pimcore#6334]
# Bug Report
The system requirements check highly recommends to have APCu installed (https://github.com/pimcore/pimcore/blob/3ae3cc354e8a66fa983cf607889ce0470bbbafcb/lib/Tool/Requirements.php#L621).
Since I don't see any apcu calls in the pimcore cache and I'm not aware of any default APCu usage in e.g. symfony or doctrine I don't see the point in enabling APCu.
Probably someone can clarify the purpose of APCu in pimcore?

### Expected behavior
Either APCu is used (and the details about itare probably explained somewhere) or the system requirements check does not recommend APCu.

### Actual behavior
System requirements check highly recommends APCu without any obvious usage.

**Comment by brusch** [comment]
https://getcomposer.org/doc/articles/autoloader-optimization.md#optimization-level-2-b-apcu-cache

But this is definitely not the right place for asking questions like this, please use talk.pimcore.org or gitter.im/pimcore/pimcore instead. Thanks
