### ISSUE TITLE
Migration from pimcore 4.6.5 to pimcore 5.x, 6.x broken

### ISSUE THREAD

**Issue by thgross** [pimcore/pimcore#6335]
I had a really hard time trying to migrate a project from pimcore 4.x.

The documentation says it is a 4-step process (https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/Updating_Pimcore/V4_to_V6.html):

1. Upgrade to 4.6.5 (no problem here!)
2. Start migration to pimcore 5
3. Upgrade to latest version 5
4. Upgrade to version6

The main problem is step 2. The basic migration guide (https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/Updating_Pimcore/Upgrade_from_4_to_5/Basic_Migration.html) handles migration from pimcore 4 to pimcore 5.4.

However, the composer.json to download: https://github.com/pimcore/skeleton/blob/master/composer.json can only be used for pimcore 6! The migration will NOT work this way.

Can someone please verify that the migration really still works? There are many older pimcore installations out ther waiting to be migrated, but currently I don't think it is really possible.

I feel like the whole migration process for migrating 4.6.5 to the latest pimcore version should be verified to make sure everything still works.

Thank you!

**Comment by juckerf** [comment]
have you tried with a composer.json which contains a 5.x version (e.g. https://github.com/pimcore/skeleton/blob/v1.3.0/composer.json)?

**Comment by brusch** [comment]
https://talk.pimcore.org/
https://gitter.im/pimcore/pimcore
