### ISSUE TITLE
Upgrade to PrestaSitemapBundle v2

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#6340]
# Feature Request
## Feature description
PrestaSitemapBundle v2 has been released on January 8th and requires at least PHP 7.1 as well as Symfony 3.4. Therefore, I think it could be upgraded without any problems. As far as I have seen there have no changes to be made to the Pimcore code: https://github.com/prestaconcept/PrestaSitemapBundle/releases/tag/v2.0.0

What do you think?

**Comment by aarongerig** [comment]
@brusch This could be something for 6.7. Not that I really need it, but it's always good to be up-to-date, right? Plus not many changes are needed. :)

**Comment by brusch** [comment]
@aarongerig if it does break anything, it's not for `6.7`. If upgrading works without changing anything it would be fine for me (if PR is provided).

**Comment by dpfaffenbauer** [comment]
checking the changes, it doesn't break anything. It just fixes some deprecation notes (BC safe) and adds support for symfony 5: https://github.com/prestaconcept/PrestaSitemapBundle/compare/v1.7.0...v2.0.0

**Comment by brusch** [comment]
Thanks for checking! Then we're more than happy to receive and merge PRs 😎
