### ISSUE TITLE
[Improvement] Language/country and multilanguage/multicountry slow and GUI impact

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#6343]
Hello,

We were trying a simple object class with all type of fields.

Here the json export.
[class_testcls_export.zip](https://github.com/pimcore/pimcore/files/4583057/class_testcls_export.zip)

We find GUI was really slow, loading the object, and in localized panel switching language.
As one some project we have object with more fields, we arrived to the conclusion some type of field where making this slow. After manually trying delete then to see when speed is improved we find language/country and multilanguage/multicountry seems to have big impact.

![image](https://user-images.githubusercontent.com/9025839/81104943-882ca800-8f13-11ea-84b6-2701f93a62e1.png)

For localized field i think it is slow because it is lazy loaded.
So slowness is on PHP side of this datatype i think, to fetch the list of the options.

Could it be improved with a cache mecanisme or some other tricks ?

Actually if you try creating a class with the provided json export on the demo Pimcore, and create an object from this class, you can easily reproduce this problem : slow display. And if local developpement the CPU is working hard (because PHP or GUI ?).

Thanks.

**Comment by Yivan** [comment]
I should add that i tested on a project with 20 locales (real project, yes i know it is a lot!), and just opening the object take around 30 sec. Removing those 4 fields improve dramaticaly this (always slow but manageable). Maybe some other fields could be imporved. But those four are the main cpu hooger !
So it seems the data needed for language/country and multilanguage/multicountry in localized field impact even the object opening.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
