### ISSUE TITLE
[Bug] Validation by updating objectbricks via the grid view

### ISSUE THREAD

**Issue by skochTC** [pimcore/pimcore#6350]
# Bug Report
I'm not sure if this is a real bug or if it's just deliberate. Please give me some feedback about this.

### Expected behavior
A validation message should be displayed.

### Actual behavior
The object is stored invalidly.

### Steps to reproduce
If an objectbrick is assigned in the object, you can still assign another one in the GRID view, but only one object brick is allowed according to the class definition. 
When the edit view is opened, you will only see one object brick and the message "limit reached" will appear immediately.

I have found this line that disables the validation:
https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L1719

I think instead of `||` you mean `&&`?

**Comment by dvesh3** [comment]
Hey @skochTC, there are two different issues:
1. "**Max Limit**" validation missing for Objectbricks & Fieldcollections in API.
2. **OmitMandatoryCheck** is enabled for all edit actions from Grid. (should be in a separate issue).

**Comment by skochTC** [comment]
@dvesh3 Thank you! 👍
