### ISSUE TITLE
Problems with video Preview in version 6.6.x

### ISSUE THREAD

**Issue by r4a5a88** [pimcore/pimcore#6352]
# Bug Report

I installed pimcore fresh on a new debian 10 , with php 7.3 and on a ubuntu 18.04 with php 7.2 Servers with Apache as the web server. Both with ffmpeg.

I had it installed on a 6.4 version of pimcore and everything worked fine. 
The videos which we uploaded in mp4 format previewed and played in the admin UI.

### Expected behavior
I expected the videos tho preview and play in the admin UI

### Actual behavior
As described in my forum post :
https://talk.pimcore.org/t/problems-with-video-preview-in-admin-ui/3613

the videos did not preview or play. I waited for 30 minutes and more and nothing happened
I tried the video in the pimcore demo server and it did not preview or play either.

### Steps to reproduce

Install a fresh ubuntu 18.04 or debian 10 Server and install pimocre acording to the manual.
Then upload a mp4 file and play it in the admin ui.

# Feature Request

What changed ? What can I do to make the videos preview ? 
Please fix it so videos preview and play in the admin UI again

**Comment by dvesh3** [comment]
resolved by https://github.com/pimcore/pimcore/pull/6511

**Comment by dvesh3** [comment]
Issue persists in 6.6.5 for new folders

**Comment by dvesh3** [comment]
issue related to new video upload, resolved in #6602
