### ISSUE TITLE
wysiwyg manual link adjustment does not work 

### ISSUE THREAD

**Issue by brillentraeger** [pimcore/pimcore#6355]
1. Step: Assign a link to a document 
![image](https://user-images.githubusercontent.com/64948655/81305523-b5e23000-907e-11ea-93fd-18c6220c6210.png)
2. Step: Pimcore stores (old) ID
![image](https://user-images.githubusercontent.com/64948655/81305436-9fd46f80-907e-11ea-9240-d4bd4d2ebf7d.png)

3. Step: Pimcore changes URL field to a manual value 

4. Step: Pimcore still stores the old ID and so links to the old document instead to the set link 

Expected behavior:  (old) ID should be deleted when manual adjustment is done.

**Comment by brusch** [comment]
This is currently not possible due to the limitations of CKEditor. 
Please just remove and reassign the link (drag & drop).
