### ISSUE TITLE
[DataObject] Dataloss when saving localized fields in field collections

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#6357]
- use data object with localized fields in field collections (e.g. news object in demo) 
- make change in localized fields in field collections 
- save object
-> data of all other languages than changed language is deleted in localized fields of field collections (at least after second save)

**Comment by MercuryKojo** [comment]
might be connected with this:
Open News Object in pimcore Demo and change one of the localized field in a field collection and save.
After reload all other localized fields are empty. Only the changed localized fields persist

**Comment by dvesh3** [comment]
@MercuryKojo yes, saving localized fields inside field-collection leads to data loss. thanks for looking into it and we are working on the fix.
