### ISSUE TITLE
getRequiredByDependenciesForFrontend() different result depending on context

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#6361]
# Bug Report

### Expected behavior

When viewing the *Dependencies* tab when editing a Data Object there is a XHR request to:

`/admin/element/get-required-by-dependencies?id=9&elementType=object&page=1&start=0&limit=25`

This is a call to [the Admin ElementController](https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Controller/Admin/ElementController.php#L693-L724)

The dependencies returned from this conroller works as expected and will return JSON like this:

```json
{
  "hasHidden": false,
  "requiredBy": [
    {
      "id": 26,
      "path": "/products",
      "type": "document",
      "subtype": "page"
    },
    {
      "id": 5,
      "path": "/Assortment/test",
      "type": "object",
      "subtype": "object"
    },
    {
      "id": 74,
      "path": "/Assortment/1166605",
      "type": "object",
      "subtype": "object"
    }
  ],
  "start": "0",
  "limit": "25",
  "total": 3
}
```

### Actual behavior

However, when copying and pasting and running the same code in a different (non-Controller context), e.g. in the Class Model, it will fail to return any actual dependencies, example:

### Code example
```yml
pimcore:
    models:
        class_overrides:
            'Pimcore\Model\DataObject\Product': 'AppBundle\Model\DataObject\Product'
```

```php
<?php

namespace AppBundle\Model\DataObject;

use Pimcore\Bundle\AdminBundle\HttpFoundation\JsonResponse;
use Pimcore\Model;
use Pimcore\Model\DataObject\Product as PimProduct;

class Product extends PimProduct
{
    public function getCategoryPage()
    {
        $categories = $this->getCategory();
        if (empty($categories)) {
            return null;
        }

        $soughtCategory = $categories[0];
        $id = 9; // $soughtCategory->getId(); // Actual Pimcore ID
        $type = 'object';
        $allowedTypes = ['asset', 'document', 'object'];

        if ($id && in_array($type, $allowedTypes)) {
            $element = Model\Element\Service::getElementById($type, $id);
            $dependencies = $element->getDependencies();

            if ($element instanceof Model\Element\ElementInterface) {
                $dependenciesResult = Model\Element\Service::getRequiredByDependenciesForFrontend($dependencies, $offset = 0, $limit = 25);

                $dependenciesResult['start'] = $offset;
                $dependenciesResult['limit'] = $limit;
                $dependenciesResult['total'] = $dependencies->getRequiredByTotalCount();

                $json = json_encode($dependenciesResult, JsonResponse::DEFAULT_ENCODING_OPTIONS); // {"hasHidden":true,"requiredBy":[],"start":0,"limit":25,"total":3}

            }
        }
    }
}
```

**Comment by NiklasBr** [comment]
Noone?

**Comment by NiklasBr** [comment]
@brusch perhaps?

**Comment by NiklasBr** [comment]
Anyone? @dvesh3?

**Comment by dvesh3** [comment]
Hi @NiklasBr sorry for late response. `Pimcore\Model\Element\Service::getRequiredByDependenciesForFrontend` & `Pimcore\Model\Element\Service::getRequiresDependenciesForFrontend` used by admin and needs user permission to list `RequiredBy` & `Requires` dependencies so as not to expose restricted elements.

what is your actual usecase for extending the functionality?

**Comment by NiklasBr** [comment]
I want to know which renderlet (in a Document) this Data Object is currently a part of to allow me to build a navigation and breadcrumb trail to it from a controller action.

**Comment by dvesh3** [comment]
Isn't just calling `$element->getDependencies()->getRequiredBy($offset, $limit)` and `$element->getDependencies()->getRequiredByTotalCount()` solves your purpose?

**Comment by brusch** [comment]
@NiklasBr ping 🏓

**Comment by NiklasBr** [comment]
I couldn't solve it with your suggestion either, sorry.
