### ISSUE TITLE
[Asset] Unable to save in image editor

### ISSUE THREAD

**Issue by dccfena** [pimcore/pimcore#6372]
# Bug Report

**Expected behavior**

1. As a user, I am expecting the Button "Save & Publish" to generate a new version that is published and that I can see in the frontend.

2. As a user, I am expecting the option "Quick save" in the miniPaint tool to generate a new version of the asset (image) that i can schedule. 

**Actual behavior**
1. "Save & Publish" has no impact to the image in the frontend, the changes are not visible.
2. "Quick save" is not generating a new version.

**Steps to reproduce**
1. Open an image from the assets (e.g. Pimcore Demo Package)
2. Edit Image (e.g. add some text)
3. Quick Save
4. Check the frontend
5. Save & Publish
6. Check the frontend

As in this state, the "MiniPaint" functionality is not usable for a user.

**Comment by brusch** [comment]
Seems to be related to #6253 
It seems they replaced the single `Save` button by some more saving options. 
Needs investigation how this can be solved with the newer version. 

See also: 
https://github.com/pimcore/pimcore/blob/ae0e69134f5fac596893ca0ad3ba2887c8393986/bundles/AdminBundle/Resources/views/Admin/Asset/imageEditor.html.php#L94

**Comment by dccfena** [comment]
Functionality is also odd with old version of MiniPaint:
- Edit an Asset
- Click "Save" 
- No new version is generated in Versions-Tab but Asset is already published
- Work on last version is not possible unless complete clearance of browser cash
-- Until this, original version is shown in edit

**Comment by brusch** [comment]
That's just the way how assets work ... there's no "unpublished" state for assets.

**Comment by dccfena** [comment]
Ah, ok - this then makes sense, our understanding was just different in this case :)
