### ISSUE TITLE
[Discussion][DataObjects] Behavior of default values in combination with inheritance

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#6376]
related to #4600 #6338 #6342

Right now default value, behavior is as follows: 
1) no inheritance: **default value** is persisted to store/query table on create
2) with inheritance and NO parent value: **default value** is persisted  to store/query table on create
3) with inheritance and existing parent value: **parent value** is persisted to store/query table on create, inheritance is broken.

For my understanding, 3) is confusing. More logical behaviors would be

3.a) with inheritance and existing parent value: **no value** is persisted to store table, **inherited value** is persisted to query table, inheritance is active

3.b) with inheritance and existing parent value: **default value** is persisted to store/query table on create, inheritance is broken.

What are your thoughts? How should it be?

**Comment by msphn** [comment]
I'd expect to only persist values for e.g. variants if they differ from their inherited values. That should work for static default values. 

I'm not sure about dynamic default generators should be evaluated and their result compared to the inherited values and only persisted if they differ as well.

**Comment by vandanasingal** [comment]
In case of 2: wat will happen if we update the Parent with a value later? Will it update the value in child as well?

in case of 3b) when parent has a value, this value should be inherited to child, not the default value. As i understand default, it is only if there is no value defined explicitly use default. When we define a value for parent, that should be used.

**Comment by fashxp** [comment]
> In case of 2: wat will happen if we update the Parent with a value later? Will it update the value in child as well?

No, is the same as a value would be set to the child object manually.

**Comment by brusch** [comment]
We agreed that 3a is the right behavior. 
Please also add a note in the docs how the behavior is.

**Comment by vandanasingal** [comment]
> > In case of 2: wat will happen if we update the Parent with a value later? Will it update the value in child as well?
> 
> No, is the same as a value would be set to the child object manually.

If I understood correctly, user will have to manually update the value in child if parent is updated. If yes, then aren't we breaking the inheritence.

**Comment by shashanks0110** [comment]
> > In case of 2: wat will happen if we update the Parent with a value later? Will it update the value in child as well?
> 
> No, is the same as a value would be set to the child object manually.

case 2 : can we not perisist the value at child?

**Comment by weisswurstkanone** [comment]
> > > In case of 2: wat will happen if we update the Parent with a value later? Will it update the value in child as well?
> > 
> > 
> > No, is the same as a value would be set to the child object manually.
> 
> If I understood correctly, user will have to manually update the value in child if parent is updated. If yes, then aren't we breaking the inheritence.

This is all about applying values "on create", not about updates. So nothing will happen.

**Comment by shashanks0110** [comment]
Expected behaviour when default value is set : **OnCreate**

1. no inheritance: default value is persisted to store/query table on create
2. with inheritance and NO parent value:  
2.1 At child :  default value is not persisted to store table. inherited value is persisted to query table. 
3. with inheritance and existing parent value: 
3.1 At child - default value is not persisted to store table, inherited value is persisted to query table, inheritance is active

Our customer is facing issue with default values and their opinion is also the same as above.

**Comment by weisswurstkanone** [comment]
so you are saying that if inheritance is enabled then no default (the static one) is written to the store table.

**Comment by msphn** [comment]
Since we have default generators we need to evaluate if a value is different from it's inherited value. The generatos could e.g. concatinate data from other fields or vary depending on previously filled data.

**Comment by weisswurstkanone** [comment]
default generators always have higher priority meaning that as soon as a default generator is configured no static default value is considered anymore.
consequence: it is your decision if you want to implement 3a or 3b behavior.
