### ISSUE TITLE
Scheduled tasks to publish creates new version with old data when executed.

### ISSUE THREAD

**Issue by rndfm** [pimcore/pimcore#6379]
### Expected behavior
The selected or newest version is published and data remains the same.

### Actual behavior
A new version is created with stale data from some earlier version and this version is published.

### Steps to reproduce
Select a data object with past versions.
Edit one or more fields.
Click "Only save new version"
Create scheduled task to publish (does not matter if specific version is selected)
Wait for schedule to execute.
Observe old data in a new version that is published.

**Comment by dvesh3** [comment]
@rndfm I guess you are using wrong option **"publish"** (used to just change publish status of object) to publish a version. Please use **"public version"** option instead.

**Comment by rndfm** [comment]
@dvesh3 As i wrote in the issue description it doesn't matter if i select a specific version.

I would expect publish version to publish a specific version. Not create a new version with old data.
I would expect publish to publish the newest version. Not create a new version with old data.

**Comment by dvesh3** [comment]
These options have different purpose:
1. **Publish Version** - To publish a specific version (when object is already published).
2. **Publish** - To change the o_published status from false to true.

It might be useful to update docs to make it more clear.

**Comment by rndfm** [comment]
So the problem is when the object i already published and a scheduled publish is executed. Then old data replaces the last saved data and is then published? How is that "by design"? When would you ever want some random old data to replace newer data on a publish?
Seams like a pretty dangerous trap for content editors.

I'm pretty sure almost everybody that sees the two options Publish or Publish version will think that publish will... well... publish whatever data last saved. And publish version would be if you wanted to publish another version other then the latest.

**Comment by dvesh3** [comment]
It is by design to save a user from publishing incomplete version. Imagine a scenario where user A creates a schedule task to publish and user B comes in between and creates a new version(draft). So if a user is publishing an object manually then they see there's a new but not published version however it is not the case with scheduler as it will publish the last version(which might not be complete).

I have updated the docs to make the point clear. please see https://github.com/pimcore/pimcore/commit/c23d5afbfdb8e3f0b70f9fca9e69342aeb35b581  :)

**Comment by rndfm** [comment]
Okay i see your edge case but i don't think that's reason enough to do something unintuitive. No user would guess that publish only works when the object has not previously been published.

Okay. Let's say that i accept the condition that publish is only for first time publishing or publishing again after an object has been unpublished.
Let's take the draft example you gave.
So the logic is: To protect a draft from being published, a new version is created with data from a previous published version and the draft is overwritten?

This is a big user trap. I don't like traps in master data systems. Especially not them that alters data in a complete unpredictable way.

Either the functions should work predictable or be hidden if they are not meant to be used in the current state.

Suggestion:
1. Scheduled publish should publish latest version. It's what a user would expect.
2. When editing a newer not published version there is already a warning saying just that. Maybe add a message to that warning if a scheduled publish is planned.

In most cases working with a object that has a planned publish. You want those changes to be published. Last minutes edits, spelling corrections ect ect. 

If ... big if. You want to work on a draft that is not supposed to be published with the upcoming planned publish. You see the warning and can change the planned publish to a "Publish version".
But when you change to "publish version" and start making changes on your draft. Then you're kinda locking the version for the planned publish and all changes in the draft must be rolled back to make a change to the upcoming planned publish.
And by the way. If you use publish version. Any drafts will be overwritten when the publish version happens.
