### ISSUE TITLE
Documentation update for Pimcore Navigation.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#638]
Just to say I updated the page https://www.pimcore.org/wiki/display/PIMCORE4/Navigation by adding:
$navigation = $mainNavigation->getContainer();
because it was not mentioned how to get $navigation before.

(are you advised when we update the documentation, or is it better i make an issue like this for better following/tracking ?)

Thanks.

**Comment by brusch** [comment]
Hi Yivan, 

Thanks for updating the documentation! 
We get summaries of all updates made in the wiki which we review, so it's perfectly fine for us if you make changes directly. 

Thanks!
