### ISSUE TITLE
[Feature Request][DataObjects] Allow blocks within blocks

### ISSUE THREAD

**Issue by msphn** [pimcore/pimcore#6382]
Apparently it's working to move blocks into blocks and for now they working fine. But the creation of blocks inside blocks isn't allowed.

I'd like to discuss the side effects of using that. The docs are stating, that it's not supposed to work, maybe it's a hidden feature already made possible by any refactoring.

**Comment by brusch** [comment]
Blocks in blocks are currently not supported. 
When moving nodes in the class definition there's no validation, because this would significantly harm the performance of the editor.

**Comment by msphn** [comment]
Yeah I know! I'm curious what needs to be done to make that fully supported?

**Comment by weisswurstkanone** [comment]
also see https://github.com/pimcore/pimcore/issues/4798

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
