### ISSUE TITLE
Document_Email: on Pimcore GUI choosing module is not possible

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#639]
On Pimcore backend GUI (tested on the online demo and release 4.01), if an email document is created, there is not select field for module (and so controller/view are not refreshed).

![email](https://cloud.githubusercontent.com/assets/9025839/15760913/cc4caa70-2915-11e6-85e2-5333e0c27f07.png)

**Comment by brusch** [comment]
fixed by 88060fe61e01e62b164846c746aa6b7204092841 
was also the case for snippets
