### ISSUE TITLE
[Ecommerce] Session shouldn't be started automatically

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#6395]
Currently this code does start a session on every request: 
https://github.com/pimcore/pimcore/blob/master/bundles/EcommerceFrameworkBundle/EventListener/Frontend/TrackingCodeFlashMessageListener.php#L68

This can be problematic if you want to use a proxy cache for certain areas. 
I'd suggest a different approach then sessions or the possibility to control the behavior somehow.

**Comment by fashxp** [comment]
any ideas for a different approach?

**Comment by fashxp** [comment]
fixed with https://github.com/pimcore/pimcore/pull/7135
