### ISSUE TITLE
Default module when creating empty document for multisite

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#640]
When creating an empty document, module is the default module (website for instance).
When the document is created in a sub-site, this is always the default module.
I think it will be better if it is set to the module of the subsite (to be more technical the module associated to the rootsite document).

In multisite environnement, it is not possible to disable creating empty document, so editors can add empty document, by it will by default point to the module website... making it hard to make a default controller/action common for all the module in the website module (if each module have different template, predispatch hook, etc...).

To be more clear, for instance, creating an empty document could bring a page with just a big wysiwyg with the module layout/template. Actually creating an empty document will be "website" module (and default controller/action), but very often each module has his own template/layout (**as we speak of multi-sites**). So it will be better if by default it create a document with {module of the rootSite document}/default/default as module/controller/action.

**Comment by brusch** [comment]
Currently not on our roadmap.
