### ISSUE TITLE
[Bug][Ecommerce][FilterService] Category filter doesn't save the term of search

### ISSUE THREAD

**Issue by MyZik** [pimcore/pimcore#6405]
Hello!

I try to explain the problem. If we do the search like "blue", we will get all results for this term.

![image](https://user-images.githubusercontent.com/12817320/82141602-436c0f80-9837-11ea-96b5-39c65e03d495.png)

But if I want to filter the results for one category, I will get just all items from this category (like normal category page) without my term:

![image](https://user-images.githubusercontent.com/12817320/82141636-7ca47f80-9837-11ea-849d-22ef7b25762d.png)

A similar problem. If I go to the category page, I can filter by some checkbox field (in our example *Manufacturer*: _Alfa Romeo_):

![image](https://user-images.githubusercontent.com/12817320/82141748-3ef42680-9838-11ea-80e6-28c4f78b2d22.png)

But if I want to select from Luxury cars (category), my search doesn't save, and I need to filter them one more time...

**Comment by fashxp** [comment]
This is not a Pimcore topic but more a demo topic. 
There the category navigation is implemented (for simplicity reasons) that way, that category links always reset all filters. 

To change that, generated links would need to be adapted in [template](https://github.com/pimcore/demo/blob/master/app/Resources/views/product/filters/select_category.html.twig) and [twig extension](https://github.com/pimcore/demo/blob/master/src/AppBundle/Twig/Extension/CategoryFilterExtension.php)
