### ISSUE TITLE
CustomReport | CSV Download | Add pagination

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#6408]
# Bug Report

## Problem Description
Currently on CSV-Download, the entire data is fetched at once from the database. 
Offset-/Limit is not taken into consideration internally:

This causes internal server errors / SQL timeouts, if many datasets are part of the result (e.g. 600.000 records). 

## Solution Suggestion
Fetch the dataset using blocks shouldn't be that hard.
Line:
https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Controller/Reports/CustomReportController.php#L409

One just has to verify if the SQL statement defined in the custom report already defines offset / limit on its own. If yes, then the download can remain the same. If no, then pagination can be applied.

We can provide a PR if you like the suggestion.

**Comment by fashxp** [comment]
hmm, I think there are also use cases where you want to download the whole data set, also in other places of Pimcore (e.g. data object grid) the whole data set is exported as csv, not only the current page. 
I guess we will need to find a solution to make that more robust.

**Comment by andreas-gruenwald** [comment]
Actually the whole data set should be downloaded, but internally not the whole data should be fetched with one query, but the download should be chunked into smaller blocks by using offset and limit. 

 - ``SELECT * FROM some_table OFFSET 0 LIMIT 500``
 - ``SELECT * FROM some_table OFFSET 500 LIMIT 500``
 - ``SELECT * FROM some_table OFFSET 1000 LIMIT 500``
 - ``SELECT * FROM some_table OFFSET 1500 LIMIT 500``
...
in the end resulting in a CSV containing the entire data.

That's what I wanted to say.

**Comment by andreas-gruenwald** [comment]
I just had a second thought.

If the datasets would be fetched based on offset/limit that would already be a minor improvement and will suffice for our specific use-case.

However, for large datasets, server timeouts may still occur, as the response won't finish within e.g. 60 seconds (no SQL timeout anymore, but a server timeout).

So to really solve the problem, we should return the progress after each chunk, and then let the client resume piece by piece (introducing a progress bar?).

**Comment by fashxp** [comment]
that was what I had in mind, yes.
