### ISSUE TITLE
[Document|Object] Introduce new scheduler action "Publish latest available version"

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#6409]
There should be a new scheduler action that allows the user to schedule publishing the latest available version of documents and objects. 

The other "publish" actions should be renamed accordingly. 

See also #6379

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
