### ISSUE TITLE
Translation of "Close Tab"

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#641]
It seems "Close Tab" is not in translation POEditor (i don't find it https://poeditor.com/join/project/VWmZyvFVMH).
So in every language it is writen "Close Tab" and we cannot provide the translation.
I just open this issue for this one, because it is very often see as it is a central action for all document/asset/object in all day work on pimcore.

![tab](https://cloud.githubusercontent.com/assets/9025839/15763753/4d2e813a-2926-11e6-8eea-ad5cbfb31ec1.png)

Thanks!

**Comment by brusch** [comment]
This text was directly defined in ExtJS, but they provide a config option to change it :)
