### ISSUE TITLE
[Custom Reports] Drilldown filters not work (Database error)

### ISSUE THREAD

**Issue by danielerne** [pimcore/pimcore#6412]
# Bug Report

### Expected behavior
Drilldown filters in Custom Reports can be assigned and shows a dropdown Filter in the report.

### Actual behavior
It shows a database error after opening the report:
URL: /admin/reports/custom-report/drill-down-options?&xaction=read
Message: Database error, see logs for details

### Steps to reproduce
Go to the Pimcore Demo. And set a drilldown filter for example the Workflow ToDo "name".
After reopening the report it shows the error.

<img width="1405" alt="Bildschirmfoto 2020-05-18 um 19 47 30" src="https://user-images.githubusercontent.com/546931/82244051-e65c8080-9940-11ea-98a9-eb0ef9743477.png">

**Comment by fashxp** [comment]
for this feature to work it is important that FROM and WHERE fields are filled... 
see for example
![image](https://user-images.githubusercontent.com/8792145/82255494-05650d80-9955-11ea-998e-c351ce1bee7d.png)

**Comment by danielerne** [comment]
Ok, great. A bit special for the WHERE field. Especially if someone want's to fetch all rows. But it works now.

**Comment by fashxp** [comment]
the reason for it is that for the drill-down filters we need to modify the query (use from and where parts, but not select part) ... 
and nobody has created a parser yet :)
