### ISSUE TITLE
[Ecommerce][IndexService] Store table processing does not scale

### ISSUE THREAD

**Issue by podarcis** [pimcore/pimcore#6417]
# Bug Report

This report relates to the "Optimized Architecture" of IndexService using Elasticsearch, but should apply to all implementations using "Optimized Architecture".

While the concept of a multistage index (preparation and index) using a store table is great, the concept of using this very MySQL store table [as a queue](https://blog.engineyard.com/5-subtle-ways-youre-using-mysql-as-a-queue-and-why-itll-bite-you) seems [not to scale well](https://www.cloudamqp.com/blog/2015-11-23-why-is-a-database-not-the-right-tool-for-a-queue-based-system.html) when lots of objects (>100.000, depending on DBMS setup) are being used.

Problems processing the queues:

  * Work required to determine and mark the next entries to process takes longer than the actual work (e.g. preparation of data).
  * As those queries might take a long time, locking becomes an additional problem (see also recent #5499 and its workaround #6377), especially when processes run in parallel.
  * You'll have slow queries/updates in one half or the other of the data set, depending on having additional indices or not (see recent #5997).
  * Parallel syncs of products with external system also updates the preparation queue (parent object) and thus suffers from mentioned locks.

The problem painfully shows up in a customer project (about 2M products/variants and about 4M rows in store table).

Can you confirm the described behavior?

### Expected behavior

* Queue related work should be minimal and processing should not block other processes.

### Actual behavior

* Queue related work is a multiple of the actual work and thus slow.
* Database locks blocking other processes (in worst case the frontend, when single item is prepared on demand).
* Example: Data set ~600k (300k objects w/ each 1 variant); each iteration w/ 200 items takes about 12 seconds, of which 11 seconds are queue related work:
```
processed preparation queue elements: 200
Starting round: 563
Component: default
Lap                                               mark   Accum: 10.88694   Self: 10.88694
Lap                                              fetch   Accum: 11.35758   Self: 0.47064
Lap                                            prepare   Accum: 12.49153   Self: 1.13395
                                                         Total: 12.49155 <<<<<<<<<<<<<<<
```

### Steps to reproduce

I've set up a test repo [podarcis/ecommerceframework-indexservice-test](https://github.com/podarcis/ecommerceframework-indexservice-test) which contains a minimal configuration to reproduce the problem.

Besides the steps are:

1. Create project from pimcore/skeleton:master and enable Redis.
2. Enable/install ECF and configure the IndexService to use Elasticsearch.
3. Create lots of dummy products/variants (test repo contains console command `app:create-products`), e.g. 300K products with each 3 variants, resulting in about ~1M store table rows.
4. Reset the preparation queue.
5. Process the preparation queue and profile a) time needed for queue related work b) time needed for actual preparation (test repo contains simple profiling using good old StopWatch).
6. (optional & parallel) Process update-index queue.
7. (optional & parallel) Save lots of products (simulate sync from external system).

### Environment info

  * Pimcore 6.6.4 (569a798ef)
  * pimcore/skeleton:e85f97cf95
  * using Redis
  * IndexService "Optimized Architecture" with Elasticsearch5 adapter using Elasticsearch 2.4

### Possible solutions? Ideas

  * Use NoSQL database for the store table, implemented in custom worker.
  * Use specialized queue software for the queue aspect and store remains in MySQL.
  * Separate store, preparation-queue and update-index-queue in separate tables. Store is really just the store with fast lookup/update. Queue tables prepation and update-index are filled (e.g. fillPreparationQueue or on reset) and emptied (e.g. after prepareDataForIndex()).
  * More a dirty workaround: Arbitrarily divide single assortment into multiple assortment tenants. Has performance penalty as each tenant needs to be processed.

Note: Unfortunately, the current worker class structure (`DefaultElasticSearch5 -> AbstractElasticSearch -> AbstractMockupCacheWorker -> AbstractBatchProcessingWorker -> AbstractWorker`) seems not to support using a different store implementation/adapter without re-implementing/duplicating functionality such as CacheMockup and in this case, the backend Elasticsearch. As I understand we could solve this by "composition over inheritance".

**Comment by fashxp** [comment]
We are thinking about integrating https://github.com/webmozarts/console-parallelization to the indexing process. 
That would allow us to remove the whole worker_timestamp and worker_id stuff from the indexing process and should improve scaling a lot. Lets see what results this will have, and then decide about further improvements.

**Comment by fashxp** [comment]
I'll close this due to the improvements we made here: https://github.com/pimcore/pimcore/pull/6487
