### ISSUE TITLE
custom main navigation hovering not working correctly

### ISSUE THREAD

**Issue by zieglerh** [pimcore/pimcore#642]
# Bug Report
### Behavior  
When clicking onto a custom main navigation item, then hovering to a pimcore item and then hovering back onto the custom item, the menu is not opened anymore
### Steps to reproduce  
Create a new main navigation item like explained in https://www.pimcore.org/wiki/display/PIMCORE4/Adding+custom+main-navigation+item

Hover forth and back over the menu
![screen_shot_2016-06-03_at_11_16_00](https://cloud.githubusercontent.com/assets/18331614/15774489/db54b99c-297c-11e6-957c-2f6019df23a2.jpg)

(Tested with ExtJS 6, but the same code is also found in ExtJS 3.4)
This behavior is caused by the following lines in pimcore/static6/js/pimcore/layout/toolbar.js line 976+
### Code 
```javascript
        Ext.each(Ext.query(".pimcore_menu_item"), function (el) {
            el = Ext.get(el);

            if (el) {
                if (el.hasCls("pimcore_menu_needs_children")) {
                    var menuVariable = el.id.replace(/pimcore_menu_/, "") + "Menu";
                    if (!this[menuVariable]) {
                        el.setStyle("display", "none");
                    }
                }

                el.on("mouseenter", function () {
                    if (Ext.menu.MenuMgr.hideAll()) {
                        var offsets = el.getOffsetsTo(Ext.getBody());
                        offsets[0] = 60;
                        var menu = this[menuVariable];
                        if (menu) {
                            menu.showAt(offsets);
                        }
                    }
                }.bind(this));
            } else {
                console.error("no pimcore_menu_item");
            }
        }.bind(this));
```
because it does not apply to custom menu items

**Comment by brusch** [comment]
Call `pimcore.helpers.initMenuTooltips();` after you have added your custom menu item.

**Comment by zieglerh** [comment]
that did not resolve the issue.
initMenuTooltips() only initializes the tooltips  (which are not mentioned in the example) but our problem was the mouseenter function, which does hide all menus that are not in available via this[menuVariable]

```javascript
// the function
el.on("mouseenter", function () {
// hides all menus
                    if (Ext.menu.MenuMgr.hideAll()) {
...
// show only menus which have .pimcore_menu_needs_children and are available as object variable
var menu = this[menuVariable];
```

the currently working approach is to get the menu into the prototype toolbar as variable and to set data-menu-tooltip attribute and .pimcore_menu_item and .pimcore_menu_needs_children css classes. an insert 'after' the search menu and not before is better.

```javascript
	initialize: function() {
		pimcore.plugin.broker.registerPlugin(this);

		this.navEl = Ext.get('pimcore_menu_search').insertSibling('<li id="pimcore_menu_mds" data-menu-tooltip="mds Erweiterungen" class="pimcore_menu_item pimcore_menu_needs_children">mds Erweiterungen</li>', 'after');
		this.menu = new Ext.menu.Menu({
			cls: "pimcore_navigation_flyout"
		});
		pimcore.layout.toolbar.prototype.mdsMenu = this.menu;
	},

	pimcoreReady: function(params, broker) {
		var toolbar = pimcore.globalmanager.get("layout_toolbar");
		this.navEl.on("mousedown", toolbar.showSubMenu.bind(toolbar.mdsMenu));
		pimcore.plugin.broker.fireEvent("mdsMenuReady", toolbar.mdsMenu);
	}
``` 

you might want to update the documentation

**Comment by brusch** [comment]
Thanks, done: https://www.pimcore.org/wiki/display/PIMCORE4/Adding+custom+main-navigation+item
