### ISSUE TITLE
Versioning after update

### ISSUE THREAD

**Issue by metaflux** [pimcore/pimcore#6424]
Hello, we have received a message from the customer that he can no longer use the versions of objects after updating from Pimcore 5.8.9 to Pimcore 6.6.2. The message from the Error Log: "Cannot read version data from file system because of incompatible classVersion". When I look into a version file that can no longer be loaded, I see things like "Zend_Date_DateObject"... which most likely no longer exists. So am I right in assuming that it is actually impossible to deserialize old versions? Is there a solution for this problem?

**Comment by brusch** [comment]
Don't think theres any solution, sorry about that 😐
