### ISSUE TITLE
Problem with displaying variable-height content in grid

### ISSUE THREAD

**Issue by kubaplas** [pimcore/pimcore#6429]
# Bug Report
There is a problem with displaying multiple rows with variable height. For example large grid with images, where some data object doesn't have image assigned. As a result the grid is badly renderred.

### Steps to reproduce
Tested on official demo:

1. Open Product Data folder, select AccessoryPart Class
2. Change gridconfig to have image field and multiple other fields, like this:
![Screenshot_20200521_141819](https://user-images.githubusercontent.com/1809664/82558660-76cbd880-9b6e-11ea-83de-b7db394bc244.png)
3. Display all objects in grid (bug occurs for large sets of data)
4. Delete images from lower part of dataset.
5. After reloading data, the grid is broken:
![Screenshot_20200521_141808](https://user-images.githubusercontent.com/1809664/82558794-b98db080-9b6e-11ea-8a40-bfee7db709b6.png)
![Screenshot_20200521_141757](https://user-images.githubusercontent.com/1809664/82558796-ba264700-9b6e-11ea-9378-e3a7b0ecc43a.png)

### Possible reason
For large dataset ExtJS does not render the whole thing, instead renders only the beginning and assumes the height of the grid based on existing data. This is not recalculated when data is renderred, resulting in scrollbar allowing to scroll pass the data.

### Possible solution
For variable height fields set it to constant, nevertheless the content. For example, for image (bundles/AdminBundle/Resources/public/js/pimcore/object/tags/image.js:42):
```js
if (value && value.id) {
    var baseUrl = '<div style="width: 88px; height: 88px; background-image: url(/admin/asset/get-image-thumbnail?id=' + value.id;
    if (forGridConfigPreview) {
        return baseUrl + '&width=88&height=20&frame=true);" /></div>';
    } else {
        return baseUrl + '&width=88&height=88&frame=true);" /></div>';
    }

} else return "<div style=\"width: 88px; height: 88px;\"></div>";
```

**Comment by kubaplas** [comment]
Video to better show how it affects the grid. There it also jumps making scrolling very hard, in some cases impossible:
![ezgif-5-d97bbf9cafe1](https://user-images.githubusercontent.com/1809664/82560110-10948500-9b71-11ea-88f1-1ec116da8823.gif)

**Comment by kubaplas** [comment]
@brusch any idea how to fix this?

**Comment by Hbitvof** [comment]
This is also for us pretty big of an issue. When using images in grid view you can hardly work with Pimcore because differt row sizes.

Would be nice if this can be fixed soon.

@brusch can you please take a look at this?

**Comment by tecbird** [comment]
Any solutions here or fixes? 
We have the same problem

**Comment by brusch** [comment]
Would be nice if someone could debug this and provide a fix as a PR 😊

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
