### ISSUE TITLE
Consistent class grouping based on CamelCase

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#643]
Grouping classes seems to be case independant and only string length.
This arise some strange group like those one (online demo), where all "screenXxxx" should be in the same group:

![classes](https://cloud.githubusercontent.com/assets/9025839/15777316/8576cf12-298e-11e6-972f-c106b04c8122.png)

Make the group algorythm could be more good robust if it detect the case and use it to perfom nice group ?

**Comment by Yivan** [comment]
I would like to add, maybe it is a bug linked: in the object tree, the groups are not made the same than the class editor... so as user i did'nt understand the magic operating behind ; )
Maybe having the possibility to create folder in the add class panel and left the user to arrange the way it like could be the best. And using the same preference he made for the object tree when he has to choose the class when creating an object.

Here is another exemple: class tree is different than object tree for class arrangement:

![case2](https://cloud.githubusercontent.com/assets/9025839/15801599/c44cd8be-2a9a-11e6-8626-5c44f350448e.png)

**Comment by Yivan** [comment]
I made some other test, and it seems groups are based on translated class name (on the object tree rearrangement). It is complex in fact because sometime you want to group object not because they begin with the same name (in some language it could be the end which is more common), but because of business logic. I think ordering by name could cause some strange behaviour and even if we stick only to classname (not using translated name) it involves the developper must modeling/choose the class name depending user GUI... not a good thing i think.

Here is another exemple wich show that translated class name change the object tree object for creating object (see the difference between this and my previous comment):

![case4](https://cloud.githubusercontent.com/assets/9025839/15802372/e915a5f8-2aaf-11e6-862a-34e83e07f632.png)

**Comment by kanevbg** [comment]
It may be obsolete by https://github.com/pimcore/pimcore/issues/222

**Comment by Yivan** [comment]
It seems not corrected... in the last release, always auto-arrangement wich mean nothing for the human using the back end ; )

Screenshot for the class editor:
![classes](https://cloud.githubusercontent.com/assets/9025839/16211373/6c128582-3741-11e6-8af9-82315ebfe923.png)

Screenshot for the action "New" in the object tree:
![tree](https://cloud.githubusercontent.com/assets/9025839/16211393/89227330-3741-11e6-8e9f-11a9f2b390e5.png)

It is not convenient at all for end user this auto-group as it means nothing and seems totally arbitrary in this case. All object begin with "demande" but strange group are made automatically.
I hope will be fixed. At least having the option in system to disable auto-grouping will be fine (better than something where grouping is not good).

Like i said it in my previous post, i think grouping by name is too ambiguous, because same beginning name doesn't mean have to be grouped for user action "New". Best would be creating group in the class tree (by right click, or **simpler just by adding a field in the class definition called "parent group" for instance**, and use this information to construct the "New" object tree.

Thanks!

**Comment by weisswurstkanone** [comment]
I doubt that this magic can ever work in a satisfactory way for all scenarios. I am wondering if it isn't a better approach to define the class groups somewhere in a configuration file.

**Comment by Yivan** [comment]
Thanks weisswurstkanone for your idea.
Yes it is a ggod one. Like other new possibilitiers (custom views, perspective wich are made by custom files), we could make grouping this way in a configuration files.
Maybe the same files could be used for grouping document type (see https://github.com/pimcore/pimcore/issues/659)

**Comment by brusch** [comment]
Grouping now only works for classes using camel case and has a central place where the logic sits, so grouping is now consistent no matter if it's in the class editor or in the tree context menu. 

The way grouping works now is pretty straightforward and is basically just a regex: 
https://github.com/pimcore/pimcore/blob/9a8d0b13ab8c8adbd00bf07caba49ba1e9d9df56/pimcore/modules/admin/controllers/ClassController.php#L97-L97

It's also prepared now for additional custom groups, as described here #222 
If we implement custom grouping or not is not yet decided.
