### ISSUE TITLE
SEO and Settings doesn't consider Pretty URL

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#6440]
### Expected behavior

If there is a Pretty URL / URL Slug it should be used when SEO previewing

### Actual behavior

Only the path is used.

### Steps to reproduce

1. Create/open a Page
2. Go to the SEO tab
3. Add a Pretty URL -- the preview doesn't update

**Comment by NiklasBr** [comment]
This is still relevant

**Comment by NiklasBr** [comment]
This is still relevant

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Comment by NiklasBr** [comment]
I would like to add a comment saying that this is still a problem.

**Comment by fashxp** [comment]
It doesn't seem to be a significant problem, as for more than 3 years nobody has found the urgency to fix it. 
As mentioned, we are still happy to merge PRs.

**Comment by NiklasBr** [comment]
I'll re-open this issue first.
