### ISSUE TITLE
[BUG][Classification stores] Classification store inheritance in PHP API

### ISSUE THREAD

**Issue by RuudvdvNB** [pimcore/pimcore#6447]
# Bug Report

### Expected behavior
In Pimcore 6.6.4, when loading a variant Data Object that uses a classification store, i expect to get the parent data when the fields for the variant are not set/overwritten from the parent.

### Actual behavior
An empty classification store is returned.

### Steps to reproduce
1. Create a classification store
2. Create a class
3. Set `Allow inheritance`
4. Set `Allow variants`
5. Add a classification store field that uses the store you created in step 1
6. Save class
7. Create parent object, add fields and set values
8. Create a variant, do not set any data, just publish
9. Now use the PHP API to get the variant and load the store `getStore`

### Code example
Looking at the following code in the PHP class that is generated by Pimcore, the variable `$data` is set with `preGetData` this returns `\Pimcore\Model\DataObject\Classificationstore`. Then there is a check `isEmpty` but this just checks if the variable `$data` is empty in `\Pimcore\Model\DataObject\ClassDefinition\Data`. Because it returns a Classificaitonstore this variable is never empty.

```php
/**
* Get store - Store
* @return \Pimcore\Model\DataObject\Classificationstore
*/
public function getStore () {
	if($this instanceof PreGetValueHookInterface && !\Pimcore::inAdmin()) { 
		$preValue = $this->preGetValue("store"); 
		if($preValue !== null) { 
			return $preValue;
		}
	} 

	$data = $this->getClass()->getFieldDefinition("store")->preGetData($this);

	if(\Pimcore\Model\DataObject::doGetInheritedValues() && $this->getClass()->getFieldDefinition("store")->isEmpty($data)) {
		try {
			return $this->getValueFromParent("store");
		} catch (InheritanceParentNotFoundException $e) {
			// no data from parent available, continue ... 
		}
	}

	if ($data instanceof \Pimcore\Model\DataObject\Data\EncryptedField) {
		    return $data->getPlain();
	}

	return $data;
}
```

**Comment by weisswurstkanone** [comment]
What is step 10 ?

As far as I remember you have to get the Store (getStore()) and then call getLocalizedKeyValue on it.

**Comment by RuudvdvNB** [comment]
Yes with getLocalizedKeyValue i'm able to get the fallback value's. What i was using at the moment was the `getItems()` that is available in the `getStores()`. As i expected it, when the items are empty there is a fallback to the items from the parent.

For now the inheritance check in the PHP API getter is of no use.

**Comment by weisswurstkanone** [comment]
I assume the generated code is just the standard code fro all data types and can ommitted in case of classification store.

For getItems:  it should be made clear in the documentation that you get the raw data and nothing like fallback values.  I don't think that it should be marked as internal. Both have their use cases.

**Comment by RuudvdvNB** [comment]
Yes, i think changing the docs would made it more clear. Because of the standard code i now got confused. Issue could be closed.
