### ISSUE TITLE
Check controller utf8mb4 database, composer mandatory for v4.1?

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#645]
Changes to allow utf8mb4 has been done in index controller, but not in check controller of the install module.
So pimcore\modules\install\controllers\CheckController.php, line 250:
`"state" => ($result['Value'] == "utf8") ? "ok" : "error"`
should be replaced by:
`"state" => (in_array($result['Value'], ["utf8", "utf8mb4"]) == "utf8") ? "ok" : "error"`

I don't know if some other recent change in index controller have not been reported to check controller.

By the way, when trying upgrading from 4.01 to 4.1, the updater ask and require Composer. It was a fresh 4.0 release, upgraded a few days ago to 4.01... and until today for the 4.1 composer was not asked. **I think starting from the 4.1 Composer is now mandatory to upgrade ?**

Thanks.

**Comment by brusch** [comment]
Yes, composer is now a requirement. 
See also: 
https://www.pimcore.org/wiki/display/PIMCORE4/Within+Version+4.x
https://www.pimcore.org/wiki/display/PIMCORE4/System+Requirements
