### ISSUE TITLE
Apply tagging to object's children

### ISSUE THREAD

**Issue by khusseini** [pimcore/pimcore#6450]
# Feature Request
At the moment it is possible to tag objects and have the tags be applied to children with a click of a button in the admin backend, however creating new variants of the object will not add those tags automatically. 

## Feature description
An option should be available to objects that allows the system to automatically assign tags to newly created variants and/or children.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
