### ISSUE TITLE
[Data Objects] Bug with import when headers contains comma

### ISSUE THREAD

**Issue by j-ts** [pimcore/pimcore#6462]
# Bug Report

I found out that if you try to import CSV-file from Google Spreadsheets that contains coma in first row, Pimcore won't recognise columns correctly.
![image](https://user-images.githubusercontent.com/58213627/83003709-5ccf4180-a017-11ea-8427-088062e27f4b.png)
Well, I knew about it for a long time and fixed it by re-saving file with semicolon delimiter. But it would be more comfortable to fix such things inside import itself. 
### Expected behavior
Correct column recognising
### Actual behavior
Pimcore perceives file as _semicolon-separated_ with line terminator `0d0a` or `0a` (or sometimes can't recognise it at all), although Spreadsheets created comma-separated file with line terminator `0d0a`.
No changes in **CSV settings** or **Reload column configurations** features does't help.
### Steps to reproduce
1. Create a spreadsheet (https://spreadsheet.new/), add some data with comma in first row and download file.
![image](https://user-images.githubusercontent.com/58213627/83007919-0cf37900-a01d-11ea-832e-1c5139aa7cc9.png)

2. Import it to any class.

**Comment by fashxp** [comment]
Importer got removed
