### ISSUE TITLE
[CRITICAL] Context menu for document broken in Pimcore 4.1.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#647]
We just updated to 4.1 version.
By default web2print is desactivated (for trying you need to do: web2print (system -> Web2Print -> uncheck it. Reload backend).
Context menu (right click) on document does not open, and send the javascript error in console log:

```
TypeError: menuItem is null
if (menuItem.hidden) {
```
source file: website/var/tmp/minified_javascript_core_c671756ff9993ee4262c0c43477a855b.js?_dc=3816

I tag it critical because it prevent usage of documents with Pimcore and can be a stopper for many people upgrading production application.

**Temporary solution for people being stuck for this on the 4.1:
activate in settings the web2print new module**

I think javascript try to render some web2print menu but as it is not activated it send an JS error.

I would like just to add a big thanks to the Pimcore team for this new PDF geneartor addition to Pimcore... so great ! : )

Best regards.

**Comment by fashxp** [comment]
fixed in build 3820

quick fix is: activate and deactivate the web2print module and save the settings - then is should work.

**Comment by Yivan** [comment]
Thanks a lot for your fast action!
