### ISSUE TITLE
[Documents] Update tree after exclude_from_navigation is set

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#6470]
see: https://github.com/pimcore/pimcore/issues/1749

The tree should be updated after the exclude_from_navigation property is changed and the document is saved.

**Comment by ultramegatom** [comment]
@dvesh3 thats done and can be closed, right?

thanks alot :)

**Comment by dvesh3** [comment]
> @dvesh3 thats done and can be closed, right?
> 
> thanks alot :)

@ultramegatom Hey! yes, it is fixed. thanks for taking care of it 😉 we need to close issues manually which are merged on 6.6 branch as GitHub auto-closing linked issue works only for default branch.
