### ISSUE TITLE
[UI] Timeout when saving system settings in certain cases

### ISSUE THREAD

**Issue by alexgit2k** [pimcore/pimcore#6475]
# Bug Report

Saving settings at System settings always fails with "Error: Saving failed!" on a clean demo-installation. However, when reloading the page the changed settings have been stored.

### Expected behavior
Show a success message

### Actual behavior
Message says: "Error: Saving failed!"
No entry in logs or PHP-error-Log

### Steps to reproduce
1. COMPOSER_MEMORY_LIMIT=-1 composer create-project pimcore/demo application
2. cd application && vendor/bin/pimcore-install
3. Go to Settings -> System Settings
4. Click Save button

### Environment
PHP 7.4

**Comment by NiklasBr** [comment]
I also encounter this quite a lot, it seems the ExtJS timeout is too short to account for some system load.

**Comment by fashxp** [comment]
now, system settings can be stored in settings store, details see https://pimcore.com/docs/platform/Pimcore/Tools_and_Features/System_Settings/

**Comment by NiklasBr** [comment]
That's not the same thing @fashxp

**Comment by fashxp** [comment]
Well it is in the consequence ... as the timeout most likely was issues by a container rebuild. With saving settings in settings store, container rebuild is not necessary anymore. 

If there is another cause for that problem, we are happy to get more information and contributions to fix it. Thank you.

**Comment by NiklasBr** [comment]
Would you like me to reopen this issue?

**Comment by fashxp** [comment]
We would appreciate it - if the problem still exists - when you provide additional information as comment in that issue or, if possible, even create pull request to improve that behavior.
