### ISSUE TITLE
View interface on areabrik - Typehint make PHPStan fail

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#6478]
Hello,

Using areabrick, getView() method return a ViewModelInterface (please see: https://github.com/pimcore/pimcore/blob/master/models/Document/Tag/Area/Info.php#L173)
Problem is the result is used to assign property like this `$info->getView()->myVar = $myVar;` like explained here: https://pimcore.com/docs/5.x/Development_Documentation/Documents/Editables/Areablock/Bricks.html#page_Methods-on-the-brick-class

But PHPStan return an arror `Access to an undefined property Pimcore\\Templating\\Model\\ViewModelInterface`.

If phptype hint in https://github.com/pimcore/pimcore/blob/master/models/Document/Tag/Area/Info.php is changed to Pimcore\\Templating\\Model\\ViewModel instead Pimcore\\Templating\\Model\\ViewModelInterface it works fine.

Maybe ViewModel should be the typehint instead ViewModelInterface.

Best regards.

**Comment by brusch** [comment]
Obsolete due to #7224
