### ISSUE TITLE
Classification Store not deletable

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#648]
After creating a classification store, it cannot be removed/deleted from the system.
There is no action do do this (or if there is it is hard to find because i don't find it, so maybe it should be like other object, right click and delete action).

See this test on the online demo, nothing to delete it:

![store](https://cloud.githubusercontent.com/assets/9025839/15801527/39261a54-2a98-11e6-8331-074f34b2c1d4.png)

Thanks.

**Comment by weisswurstkanone** [comment]
Actually this is currently by intention. Deleting a store would consequently also remove the groups and keys including the data. This could happen very quickly accidentally. Nevertheless, we have to think about a safe way to accomplish this.

**Comment by Yivan** [comment]
Thanks for your answer weisswurstkanone. I come back to see if there is some workaround to delete it ?
Maybe you could provide in the documentation the table/config files to delete/remove custom store ?
Actually we have some instance of Pimcore having some store created just for testing purpose but we cannot remove them ; )
Thanks!

**Comment by weisswurstkanone** [comment]
Build 3936
Example: 
~/www/pimcore/cli$ php console.php classificationstore:delete-store --storeId=2

**Comment by maff** [comment]
**Note:** I changed the command to accept the store ID as argument instead of an option. New usage:

```
$ php pimcore/cli/console.php classificationstore:delete-store 2
```

**Comment by Yivan** [comment]
Thanks for the update!
