### ISSUE TITLE
Some main menu action are not translatable.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#649]
Hello,

I made a bunch of translation for french langages on POEditor for Pimcore (nearly all possible is translated now : ) ).

There are two main menu action which have no key and so cannot be translated:
"System-Requirements Check"
"About Pimcore(r)"

See capture please:

![nokey1](https://cloud.githubusercontent.com/assets/9025839/15801564/7b2e6298-2a99-11e6-9343-08d8fb373503.png)

![nokey2](https://cloud.githubusercontent.com/assets/9025839/15801567/80eba43e-2a99-11e6-9780-dc2631d76f08.png)

Could you please add them so  those item menu can be translated ?
I don't know if it is easy to check from the code if all main menu action have translation key. I just found those 2 but maybe some other are missing. Thanks.

Aside from this, i was asking me: when you change an existing english translation (keeping the same key), do you empty the other language or not ? Or do you create a new key each time you need to make a change/adjust in english language ? Just to know, because finding new translation is easy because empty, but finding translation which already exist but english sentence changed in the meantime is impossible/hard to find.

Thanks a lot!

**Comment by brusch** [comment]
Actually there were some more translations missing - see commit, but now it should be alright.

**Comment by Yivan** [comment]
Thanks a lot for your fast action!
I added the translation in french in POEdit.
