### ISSUE TITLE
Unable to delete selected objects from object grid

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#6495]
Select few/all objects and try to delete them.Only first one gets deleted and then error.

![Screenshot from 2020-06-02 14-44-28](https://user-images.githubusercontent.com/21308144/83503081-30686900-a4e0-11ea-8c66-b2b7d100490d.png)

![Screenshot from 2020-06-02 14-44-35](https://user-images.githubusercontent.com/21308144/83503082-32cac300-a4e0-11ea-9edc-b2d371bb8e9f.png)

![Screenshot from 2020-06-02 14-44-40](https://user-images.githubusercontent.com/21308144/83503090-33fbf000-a4e0-11ea-9f76-89ff284e85ba.png)

**Comment by dvesh3** [comment]
sorry...cannot reproduce with given steps on demo.

**Comment by neha04** [comment]
Still facing issue on demo.Try deleting Cars from demo.Open a folder click on select all deleting objects.The folder must have more than one object.
