### ISSUE TITLE
while deleting multiple folders the progress bar of the previous delete stops as a new progress bar is added.

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#6496]
Delete multiple folders.The progress bar of the first folder will stop showing progress as soon as progress bar of second folder appears.

![screencast-demo pimcore fun-2020 06 02-15_05_11](https://user-images.githubusercontent.com/21308144/83505709-c782f000-a4e3-11ea-8c47-0b4c603f261e.gif)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
