### ISSUE TITLE
frontend.path.staticroute, adding urlParams

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#650]
With new frontend.path.staticroute it is possible to construct url for object depending their own data.
So simply calling `$this->url(array("id" => $objectId, "objectRoute")` and catching it with frontend.path.staticroute, we can construct the url (from the title or another object field).
But there is a limitation so actually it cannot be possible... the only available datas in the event hook are the staticroute object and the final url... but we cannot have the parameter mapped to the call. So we cannot get the object id... (or we need to try to extact it from the final URL with some pregmatch wich is prone to errors...).

Changing \pimcore\models\Staticroute.php, line 521, by just adding one line with urlParams:

        $results = \Pimcore::getEventManager()->trigger("frontend.path.staticroute", $this, [
            "frontendPath" => $url
        ]);

to

        $results = \Pimcore::getEventManager()->trigger("frontend.path.staticroute", $this, [
            "frontendPath" => $url,
            "urlParams" => $urlParams
        ]);

And now we can have the parameters and play nicely with the event : )

Thanks!

**Comment by brusch** [comment]
Good idea!
Added `encode` and `reset` as well.
