### ISSUE TITLE
Objectbrick mandatory fields shows system(PHP) error message to User

### ISSUE THREAD

**Issue by beingdivs** [pimcore/pimcore#6507]
# Bug Report

### Expected behavior
It should not shown the system(PHP) error to user

### Actual behavior
The list of Mandatory field should be shown to user
### Steps to reproduce
1. Create an object brick with some mandatory fields
2. associate it with class
3. Create the object of class and Do not fill any of the mandatory field of object.
4. It shows error as per the attcahed Image 

### Image of ERROR

![Image of Error]
![Objectbrick](https://user-images.githubusercontent.com/3806644/83994617-93d91780-a974-11ea-9aca-7c4127b80cfc.png)

**Comment by beingdivs** [comment]
Any Updates ????

**Comment by dvesh3** [comment]
@beingdivs please try setting debug mode off...stack trace is returned only in case debug mode is on.
