### ISSUE TITLE
No more individual configuration paths for executables

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#651]
### Expected behavior 
  Set path to individual executables in system settings for windows servers.
### Actual behavior  
  Individual paths have been removed with https://github.com/pimcore/pimcore/commit/d2bbcd6450153b2d091e6eebebfef04bed762679
### Steps to reproduce  
  See system settings in Pimcore Admin (works on demo.pimcore.org), individual settings are gone with version 4.1.

Is there a reason the settings are gone? That'll probably cause some issues on windows systems.

Absolute path to wkhtmltopdf binary does now exist twice (system settings and web2print settings) while ffmpeg path for example is gone completely.

**Comment by brusch** [comment]
You can specify your custom paths here: 
![image](https://cloud.githubusercontent.com/assets/142037/15824209/5a2bf1f8-2bfe-11e6-874e-2dcfc11d2bfb.png)

This works also for Windows (platform independent). 
We just removed the individual configurations for every application and made it more generic (like operating system do). 

See also: https://github.com/pimcore/pimcore/blob/393d8e2d6ccd0145f2f129f68012da74ebd54f63/pimcore/lib/Pimcore/Tool/Console.php#L66-L66

**Comment by brusch** [comment]
btw. existing configurations are migrated automatically, see: 
https://github.com/pimcore/pimcore/blob/d2bbcd6450153b2d091e6eebebfef04bed762679/update/3786/postupdate.php#L11-L11

**Comment by Cruiser13** [comment]
I see, thank you!
