### ISSUE TITLE
Translations database bug

### ISSUE THREAD

**Issue by leuchtdiode** [pimcore/pimcore#652]
Hi,

there's a bug in the translations backend when changing a translation. It causes some unnecessary rows in the DB table.

My database rows look like this before I update them:

`'- system auswählen -', 'de', 'test', '1426161105', '1465282696'`
`'- system auswählen -', 'en', 'test', '1426161105', '1465282696'`

When I change "test" to "test2" in all languages, I get this 3 additional error rows in database, so I have 5 total rows for this entry instead of 2:

`'- system auswählen -', 'de', 'test2', '1426161105', '1465283071'`
`'- system auswählen -', 'en', 'test2', '1426161105', '1465283071'`

`'- system auswählen -', 'id', 'extModel1421-34', '1426161105', '1465283071'`
`'- system auswählen -', 'modificati', '0', '1426161105', '1465283071'`
`'- system auswählen -', 'creationDa', '0', '1426161105', '1465283071'`

I think lines `256-260` in class `Admin_TranslationController` are the problem:

`foreach ($data as $key => $value) {
                    if ($key != "key") {
                        $t->addTranslation($key, $value);
                    }
                }`

It only ignores `key`, but should also ignore `id`, `creationDate` and `modificationDate`

BR,
Alex

**Comment by leuchtdiode** [comment]
I think changing line 257 from

`if ($key != "key") {`

to

`if (!in_array($key, [ 'key', 'id', 'creationDate', 'modificationDate' ])) {`

should do it.

BR,
Alex

**Comment by weisswurstkanone** [comment]
fixed in build 3828
