### ISSUE TITLE
Unclear deprecation/internal method loop for Config

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#6522]
Calling `Config::getSystemConfig();` is `@deprecated` with the warning:

> `@deprecated use getSystemConfiguration()/Pimcore\Config service instead to be removed in v7.0`

But calling `Config::getSystemConfiguration()` is `@internal` instead. Can we make it more clear which method should actually be used?

https://github.com/pimcore/pimcore/blob/1cd96f4ad71da30a375fe256a6ba59bf5f9a7752/lib/Config.php#L514-L537

**Comment by NiklasBr** [comment]
@brusch do you know which one should be used?

**Comment by brusch** [comment]
@NiklasBr no one, better use the standard Symfony way to access the config

**Comment by NiklasBr** [comment]
Why not say so?
