### ISSUE TITLE
Bug import image - Handling error gracefully

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#6531]
Hello,

Pimcore is stuck when drag and drop this image on the BO asset section (uncompress the zip please) :

[flamme rc.zip](https://github.com/pimcore/pimcore/files/4731978/flamme.rc.zip)

You can easily reproduce it on the online demo, it stays indefinitly like this:

![image](https://user-images.githubusercontent.com/9025839/83795655-107fa380-a6a0-11ea-8243-988a61cef15f.png)

For our use case, this make batch import via server break (upload of more 10000 files via server import which take several hours and has been breaked by this file).
In batch mode Pimcore should skip file if problem and if possible report failure log at the end it would be great.

In any case, I don't know if this image reveal a Pimcore bug or if this image is buggy (i managed to open it on windows viewer, xnview, irfanview, etc... the file seems ok), but it should be handled gracefully by pimcore.

Best regards

**Comment by Yivan** [comment]
We looked more precisly on this image, and it seems the ICC profile is not good. Opening it on GIMP or photoshop brings a warning saying ICC is not RVP profile and will be ignored.

I hope it can help to add some php code to prevent Pimcore to keep freezed when adding file having this problem.

**Comment by brusch** [comment]
That seems to be an Imagick issue then ...

**Comment by brusch** [comment]
... but yes, Pimcore should handle that case gracefully in the UI and should report the problem to the user.

**Comment by dvesh3** [comment]
Hi @Yivan thanks a lot for reporting and investigating this issue. Even though this issue is already handled in Imagick(below), It still produces 503 error sometimes like on demo:
https://github.com/pimcore/pimcore/blob/cd1d124b0a061f12608180d03c8d725edaed0bf4/lib/Image/Adapter/Imagick.php#L343-L348
we are not able to identify the real cause so need more information from you. It would be great if can share some more info like php ver, imagick ver, or any error logs you find related to this issue. Thanks!

**Comment by Yivan** [comment]
Hello @dvesh3 

We got exactly the same error than the one on your online Pimcore demo.
"503 Service Unavailable" (the return of the ajax request https://demo.pimcore.fun/admin/asset/add-asset?parentId=1&dir=)
On the log side, dev.php (log Pimcore/PHP) bring nothing wrong...
But on the php-fpm log side: ` WARNING: [pool www] child 21103 exited on signal 11 (SIGSEGV - core dumped) after 490797.738297 seconds from start`

Here you will find our phpinfo (pdf format) zipped:
[phpinfo.zip](https://github.com/pimcore/pimcore/files/4755031/phpinfo.zip)
This is a pretty recent stack (php version / modules). Running on Debian Buster, using a docker container for PHP.

Hope it can helps!

**Comment by brusch** [comment]
Seems to be a PHP issue, no error message, no exception, basically nothing. 
I'm afraid there's nothing we can do to catch / gracefully handle this error ...
