### ISSUE TITLE
remove PIMCORE_DEVMODE?

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#654]
## ambiguous setting
There is a button which we should not activate. :) Remove it?
![bildschirmfoto 2016-06-07 um 16 45 59](https://cloud.githubusercontent.com/assets/700119/15862237/58782058-2ccf-11e6-9abc-4c863eafba21.png)

## Startup
In ```\Pimcore::initConfiguration()``` the PIMORE_DEVMODE will set a custom error reporting. This state will never be triggered because the try / catch returns true if the _systemconfig_ is available.

```php
// custom error logging in DEVMODE
if (PIMCORE_DEVMODE) {
    error_reporting((E_ALL ^ E_NOTICE) | E_STRICT);
    ini_set('error_log', PIMCORE_LOG_DIRECTORY . '/php.log');
}
```
## General
there is no nice way to activate the E_STRICT mode without PIMCORE_DEVMODE. Maybe we should activate strict mode if PIMCORE_DEBUG is true?

**Comment by brusch** [comment]
Startup: makes sense!
Dev-Mode: is designed to develop plugins. So a flag in the system settings makes it easier to change the behavior of pimcore when developing/debugging the core or plugins. The reason why we added "DON'T ACTIVATE IT" was that some funny clowns think "Dev-Mode" is something like putting pimcore on steroids ;-)
