### ISSUE TITLE
[Data Object] Can't save fieldcollection -> blocks -> localizedfields -> field, Call to undefined method

### ISSUE THREAD

**Issue by yvess** [pimcore/pimcore#6540]
I can't save a data object in the backend with a fieldcollection when it has

block -> localizedfields -> field

I get the error
`Call to undefined method getBlocks` (getBlocks is the name of the blocks objects)

what works is

localizedfields -> block -> field

what also works is when I use blocks -> localized fields -> field
on a data object class

![fieldcollections-blocks-not_working](https://user-images.githubusercontent.com/178436/83915775-32e2f100-a774-11ea-92cb-8abb7d583e52.png)
![fieldcollections-blocks-works](https://user-images.githubusercontent.com/178436/83915777-34141e00-a774-11ea-808f-f0bf7e76dee0.png)

Perhaps also related to #6411

I can reproduce the error on http://demo.pimcore.fun

**Comment by vg-bgp** [comment]
Hi there
I have the same issue. Just wanted to implement a fieldcollection that holds a image gallery with caption... The same as your proposal @yvess.
There seams to be a getter method missing:
```
Timestamp: Mon Jun 08 2020 10:33:58 GMT+0200 (CEST)
Status: 500 | 
URL: /admin/object/save?task=publish
Method: PUT
Message: Call to undefined method getGallery in class Pimcore\Model\DataObject\TestClass
```

**Comment by weisswurstkanone** [comment]
This is currently not supported as summarized in #6411 
You have to wait until 7.0

**Comment by rberneder** [comment]
What is the progress about this issue?
