### ISSUE TITLE
Class/field not settable in Objectbricks

### ISSUE THREAD

**Issue by ewitt7u0** [pimcore/pimcore#6542]
Hi there!
Just got the docker image working on my machine. Now i am playing around with the demo. - I wanted to add some custom Objectbricks. 
Unfortunately the field **Settings-->Data Objects-->Objectbricks-->General Settings-->Class-->Allowed class/field** is not working. I can choose a class but not a field. It opens but i get no suggestions. I can just leave it empty.
Any advice?
BR

![image](https://user-images.githubusercontent.com/41633179/83979744-eb459c00-a910-11ea-8970-9741b8e1f45e.png)

**Comment by dvesh3** [comment]
regression of #6146

**Comment by dvesh3** [comment]
already fixed in #6538
