### ISSUE TITLE
Error: The route pimcore_admin_document_renderlet_renderlet does not exist

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#6547]
# Bug Report

After composer update to latest version renderlets no longer work.

```php
@Route("/document_tag/renderlet", name="pimcore_admin_document_renderlet_renderlet")
```

Is not recognised by Pimcore as existing. I haven't seen anything else broken by the new JS routing  (#6146), but the debugger says it is there:

```sh
 $ bin/console debug:router | grep pimcore_admin_document_render
  pimcore_admin_document_renderlet_renderlet                                ANY               ANY      ANY    /admin/document_tag/renderlet
```

And the JS (renderlet.js) and PHP (renderletController.php) both are updated fine. No difference in Chrome or Firefox, both report the same error.

System info:
PHP 7.4.6
Pimcore  6.6.5
Symfony 4.4.9

**Comment by jdreesen** [comment]
Maybe a duplicate of #6533 / #6534

**Comment by NiklasBr** [comment]
I applied the patch in #6534, thanks @jdreesen, but it did not work, in fact I now got the original error and a second error which did not appear in the browser console previously:

```console
ReferenceError: fos is not defined        routing:1:5
```

**Comment by NiklasBr** [comment]
Update: Sorry, I applied the fix on the wrong line, by changing the order of the scripts the fix in #6534  worked.

**Comment by dvesh3** [comment]
Hi @NiklasBr can you please give another try with #6534 patch and clearing cache?..it works on demo which is using 6.6 branch latest chnges
![image](https://user-images.githubusercontent.com/5137917/84119845-4670af00-aa35-11ea-880f-0a4213ec7317.png)

**Comment by dvesh3** [comment]
@NiklasBr thanks for confirmation! 😉
