### ISSUE TITLE
The user or the editor is not asked if he wants to redirect the folder or a file when cutting/moving into a new location. 

### ISSUE THREAD

**Issue by PandeleCristian** [pimcore/pimcore#6550]
Verified in v6.6.4
Expected behavior:

When using cut or move to move a file or folder there should be a pop-up message that asks you if you want to create a redirect or not.

Actual behavior:

There is no pop-up only the cut-paste option.

Steps to reproduce
Cut a page or move a folder.
Go to another folder and paste/move it there.
Notice that the pop-up that asks you if you want to create a redirect is not displayed.

**Comment by PandeleCristian** [comment]
also, I  reported this here https://github.com/pimcore/pimcore/issues/6476

**Comment by brusch** [comment]
Why then create another issue if you created already one? 🤔

**Comment by PandeleCristian** [comment]
I didn't receive any updates from the initial one I thought that I reported the issue wrong or something.
