### ISSUE TITLE
Pages with `+` sign in its key/path can be created but not accessed

### ISSUE THREAD

**Issue by jdreesen** [pimcore/pimcore#6551]
# Bug Report

### Expected behavior
It's possible to create a Document/Page with a key that contains a `+` (plus) sign.

### Actual behavior
Actually it is possible to create it, but it's not possible to access it because the resulting route cannot be found: `No route found for "GET /Test+Sign"`

### Steps to reproduce
- Go to https://demo.pimcore.fun/admin/
- Create a new page with key `Test+Sign` (or something else that contains a `+`)
- The newly created page opens with a `NotFoundHttpException`
![grafik](https://user-images.githubusercontent.com/424602/84135687-91e18800-aa4a-11ea-9f4e-4613b2a50896.png)

---

Probably the problem is, that the `+` is a special character in a URI and should be escaped.

**Comment by brusch** [comment]
Yes, pretty sure that `+` is the problem, probably it's more safe to just "exclude" `+` and replace it with ` ` on create ... like we do with other forbidden characters.

**Comment by brusch** [comment]
Fixed by #6565

**Comment by jdreesen** [comment]
Thx for the quick fix :)
