### ISSUE TITLE
[Bug] Download as ZIP causes redirect to JSON fle

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#6562]
# Bug Report

### Expected behavior

Download as ZIP should initiate a browser download event

### Actual behavior

Redirect happens to `https://demo.pimcore.fun/admin/asset/download-as-zip-add-files?jobId=5edf974345319&id=287` with the content `{"success":true}`

### Steps to reproduce

1. Open Assets on https://demo.pimcore.fun/admin
2. Right-click on any folder
3. Choose *Download as ZIP* and wait for it to finish

**Comment by dvesh3** [comment]
regression of #6146

**Comment by dvesh3** [comment]
resolved by #6563
