### ISSUE TITLE
[Translations] Domain Support + Context Information + Merging Admin & Shared ...

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#6568]
- [x]  Merging Admin and Shared Translations
- [x]  Manage them within one single UI
- Shortcuts in the UI for frontend and backend locales Moved to new issue https://github.com/pimcore/pimcore/issues/11065
- [x] Shortcuts for domain filtering
- [x] Support for multiple domains (default `messages` and `admin`)

**Comment by NiklasBr** [comment]
Support for #4979 as well?

**Comment by brusch** [comment]
Yes, we talked about that as well, but first things first and not too many things in one go 😊
