### ISSUE TITLE
Adding user permission on properties name (not only the tab)

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#657]
I would like to submit an improvement which could help developpers to make code less prone to break by user manipulation. Application case example concerne getting elements (document/asset/object), but has to bee seen more globaly has "internal admin" data for elements.

Actually, to get directly an element, we use getById or getByPath.

The problem is:

- getById: can change from one instance to another, and on existing project adding elements the id on the production has chance not beeing the same than development stack. This is not reliable. More of that this is not "human". Document::getById(83)... (83 is the sitemap page for example).

- getByPath: more friendly. We can use Document::getByPath(/directory1/directory2/sitemap). But if the user move/rename the document, it broke. So we need to lock it. And now this is reliable to use this in the code for long term purpose. But the user loose one of the best of Pimcore: the possibility to rename and move the document for better organisation to his need.

Actually sometimes we use a workaround, by creating a custom property named "uid" for instance. And set it to the element. So we just do: MyCustomClass::getByUid("sitemap") (this is a custom method to get element by property value). And we get the document, even if the user move it. This works for object and asset too (asset are often moved/arranged).
The only problem of this, is that the user could delete the property if he has access to the property. So we do not allow him access to the property tab, and loose the ability to provide him some element customisation from this page (for instance we use properties to add some metrics or specifics parameters an user could modify: sitemap priority for XML sitemap for each document, etc.).

On way to protect definitively predefined property would be to have the same system than "lock/unlock"  wich are only super-administrator available.
The improvement consist of adding an "only admin" column with a checkbox for each property.
All super-admin, and only them, can see/edit property checked "only admin". Other user don't see at all the property (and they don't see the only admin column). This could be added to this page:

![properties](https://cloud.githubusercontent.com/assets/9025839/15866574/83d659b2-2cdf-11e6-886e-c0e5da7bc60a.png)

This way we can create property protected from user view, and often needed in the code/developper view. It is the only way to add some "data" to document and protect it from basic user edition.
If more easy "only admin" could mean only admin can edit/delete. It is ok too (and maybe more simple because of document predefined property to handle...).

I hope the idea make some senses ; ) I know has developper than it would help greatly to ensure better solid application less prone to be break by user manipulation (move/rename the document, deleting some properties, etc...).

**Comment by brusch** [comment]
Hmm ... I'm not sure if we need a 4th unique identifier, currently we have auto-increment ID, path and UUID. I'm not sure if a fourth one will be the holy grail :| 

Any other suggestions based on the existing identifiers?

**Comment by bbak** [comment]
Better approach would be to disallow new Content to enter the system at 2 instances. This inevitably leads to synchronisation issues and there's no (generalized) approach to solve them (to my knowledge no RDBMS-Vendor found one, neither did GIT or other VCS).

Alternatives:
1. Declare one of the instances to be the "master" (i.e. the "production" instance), setup a MySQL Slave and rsync Process to continously (or on demand) sync the development-environment.
2. Don't rely on (autogenerated) ID's at all or use one that's very, very, very unlikely to generate the same ID twice (UUID). You still have to merge databases (and files) in this case of course.

**Comment by Yivan** [comment]
Thanks bbak for your comment!
Problem is not multiple instance or dev/prod environment.
It is just editor user in the backend can move document/object/asset (if we don't look it), and so relying on getByPath is not the holy grail (as it involves removing the drag and drop functionnality so nice for user). During development phase we don't know the final document tree (it can evolves during the project), so relying on the combination getByPath/$this->url to get document path in front end PHP code is prone to be broken. So we try to find a way wich don't break when we move document.

Brush, **the issue is not about adding an uid**, (this is just my specific case/need and way to ensure user can move document without breaking some code). There is no need to add in pimcore core code another identifier : )

The issue is more global, and is just about **adding an column in database for properties called "only_admin"** for instance. This way we can create properties user cannot edit (or view, go to the simplest way of implement it), while leave him the possibility to see the property tabs. It can be seens like system/admin property if you prefer. Can be seen too as a way to more defined user right on properties edition.

Problem is for documents: property tab is for properties **_and_** for navigation/language property too... so hiding it from the user remove great editing possibility. So actually an editor need this tab. So he can edit property. And finally developper cannot put some property he don't want the user to acces/modify/view (lile u prefer).

It is hard to explain, but i hope you anderstand what i try to explain ; )) I don't hink in terms of code that it involves many change (adding column "only_admin" in properties table, checkbox labeled "Only admin can edit" (or view) in the properties list on the backend and some logic/access right), but will offer the possibility to add to document/object/asset some "data" (via properties) the developper can be confident and use it for every usecase he need.

Other approach can be adding in the user permissions tab the possibility to select properties permissions. For me it seems more complicated to go this way in term of development time... by maybe i am wrong. Result will be the same possibility of configuring permission for properties.

Thanks.

**Comment by Yivan** [comment]
I changed the title so it is more explicit now.

**Comment by brusch** [comment]
Imho: permissions on property level are a massive overkill and would add a lot of complexity compared to the benefits. 
But I'm looking forward to other opinions on that.

**Comment by Yivan** [comment]
Brush, if you just add an "is_admin" colum in properties database table, it should not add to many complexity from the database model.
And only super-admin (like for lock/unlock) can access to the property if it is admin only.

I think there is already some code to exclude the navigation_property as they are not listed in the property tab by on the side in a specific panel. So when lisitng the properties you will bypass those where is_admin is "1" for example.
(i simplify, but just to show it can be not so complexe maybe if we think it like that).

Thanks again for taking the time to discuss and answer our improvement idea.

**Comment by brusch** [comment]
`navigation_*` and `language` are system reserved properties, which is a completely different story and has nothing to do with permissions. 

Adding permissions would bring a lot of new problems and complexity, like for example the entire saving process: currently all properties are saved in one go, with permissions (even if it is just an `is_admin` flag) you'd need a logic that checks existing properties against the submitted ones and calculates a diff based on the actual user permissions to know which properties can be deleted and which ones are just hidden for the user. 

To be honest, I like to keep things simple and this approach would transform a simple thing like the properties are designed to be (key value store) to a freaky monster. 

Just out of interest, why you don't prefix the properties the editor shouldn't touch with `admin_`? Is it really necessary to restrict everything with permissions?

**Comment by Yivan** [comment]
Thanks for your answer. I was thinking it was more easy, but if it is recorded in one go (i saw in the code the setProperties method, and after it is on the model/DAO level), it makes changing core to add those permissions.

Prefixing them by admin_ won't protect them from the user deleting/changing them. We never know what an user can do ; ) (and sometimes he can do strange things we never think of it !) As properties is used for some classic config left to user (navigation, etc.) and sometimes for some properties very importante which are not mean to be edited by a simple editor user (like say it Niwann).

So i will try to find another way by myself to protect some properties, by using the document.preUpdate or document.preAdd event hook. If user is not super-admin, i will remove the keys begining with admin_ for instance (and if one already existe for the document in database i will add it so it is not lost). This way at least key with admin_ can only be modified by super-admin. Niwann, if you read this comment, it can be a solution for you too maybe.

Thanks to have discussed about it.

**Comment by brusch** [comment]
Thanks for your answer! 
I close this issue for now, but additional comments are still welcome.
