### ISSUE TITLE
cache:clear does not delete old cached settings

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#6576]
We wanted to change the database connection setting in `app/config/local/database.yml`. We wondered why even after executing `bin/console cache:clear` the old database got used.
Important to say: The new database host `new-db.pimcore.de` was not accessible at this moment, we only wanted to make sure that no write operations go to `old-db.pimcore.de`. So we expected a connection error after changing the setting and clearing the cache.

Here is what we did:
```
Change database host from old-db.pimcore.de to new-db.pimcore.de 
web1@preview:/var/www/clients/client1/web1/web$ vi app/config/local/database.yml
web1@preview:/var/www/clients/client1/web1/web$ bin/console cache:clear
 
// Clearing the cache for the prod environment with debug false
[OK] Cache for the "prod" environment (debug=false) was successfully cleared.

web1@preview:/var/www/clients/client1/web1/web$ cat var/cache/prod/
ContainerClzJW7U/                   UrlGenerator.php                    UrlMatcher.php.meta                 appAppKernelProdContainer.php       serialization.php                   validation.php
ContainerUvItMRF/                   UrlGenerator.php.meta               annotations.map                     appAppKernelProdContainer.php.meta  templates.php
ContainerUvItMRF.legacy             UrlMatcher.php                      annotations.php                     pools/                              twig/
web1@preview:/var/www/clients/client1/web1/web$ grep -Hirn pimcore_preview
 
web1@preview:/var/www/clients/client1/web1/web/var/cache$ grep -Hirn pimcore_preview
prod/ContainerUvItMRF/appAppKernelProdContainer.php:1448:        return $this->services['doctrine.dbal.default_connection'] = (new \Doctrine\Bundle\DoctrineBundle\ConnectionFactory([]))->createConnection(['driver' => 'pdo_mysql', 'charset' => 'UTF8MB4', 'user' => 'pimcore', 'password' => 'c***8', 'dbname' => 'pimcore_preview', 'host' => 'old-db.pimcore.de', 'port' => 3306, 'driverOptions' => [], 'wrapperClass' => '\\Pimcore\\Db\\Connection', 'defaultTableOptions' => ['charset' => 'UTF8MB4', 'collate' => 'utf8mb4_general_ci']], new \Doctrine\DBAL\Configuration(), $a, ['enum' => 'string', 'bit' => 'boolean']);
prod/ContainerClzJW7U/appAppKernelProdContainer.php:1448:        return $this->services['doctrine.dbal.default_connection'] = (new \Doctrine\Bundle\DoctrineBundle\ConnectionFactory([]))->createConnection(['driver' => 'pdo_mysql', 'charset' => 'UTF8MB4', 'user' => 'pimcore', 'password' => 'c***8', 'dbname' => 'pimcore_preview', 'host' => 'new-db.pimcore.de', 'port' => 3306, 'driverOptions' => [], 'wrapperClass' => '\\Pimcore\\Db\\Connection', 'defaultTableOptions' => ['charset' => 'UTF8MB4', 'collate' => 'utf8mb4_general_ci']], new \Doctrine\DBAL\Configuration(), $a, ['enum' => 'string', 'bit' => 'boolean']);
```

Actually I would have thought that after `cache:clear` the current configuration in `var/cache/prod/` gets deleted and on the next request gets recreated. But actually `cache:clear` creates another configuration file and leaves the old one in place - and even worse: it still uses the old configuration on consequent requests in Pimcore backend.

In the end only `rm -rf var/cache/*` helped.

**Comment by brusch** [comment]
I'll close this for now ... Pimcore doesn't hook into Symfony's `cache:clear` command, so I don't think this problem is originated by Pimcore.

**Comment by blankse** [comment]
@BlackbitNeueMedien We also had this problem. The database settings are probably also in the pimcore cache. 
Therefore pimcore: cache: clear must also be executed. We always execute both commands. Maybe it is possible to merge the both?
```
php bin/console cache:clear
php bin/console pimcore:cache:clear
```

**Comment by brusch** [comment]
@blankse really? Couldn't think of where this should be the case ... 😐

**Comment by blankse** [comment]
@brusch Yes. And when we transfer the database, we truncate cache and cache_tags. I think I remembered that we also had the problem that the database settings were there.

**Comment by blankse** [comment]
@brusch I have just checked it in current projects. Can't find it anymore. Was probably only in Pimcore 5 when the DB settings were not directly in doctrine.

**Comment by brusch** [comment]
@blankse yep, probably. Thanks for checking!
