### ISSUE TITLE
Clearing document\link path is not possible

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#658]
I just get into this bug:
- create a link
- add a document to the path and save the link
- clearing the link path (empty) and save again
-> it keep the previous value, so there is no way to provide empty path (only at creation).

It can be a problem because empty path is used in pimcore navigation to provide menu with no link (no "a" tag, so no clickable), and so it should save even empty value i think.

![link](https://cloud.githubusercontent.com/assets/9025839/15868164/cac9be20-2ce6-11e6-98bd-14a8285f1e27.png)

**Comment by brusch** [comment]
At the moment it's not possible to use a link with a blank path. 
Please use # at the moment.

**Comment by Yivan** [comment]
I agree it is not a classic use to left it empty, but it works actually to make not clickable link from pimcore/zend navigation. There is no other way actually to provide this functionnality.

Using # is not the same as it create a "a" tag (`<li><a href="#">navigation name</a></li>`). With empty link we get: `<li>navigation name</li>`, wich is great if we just want a separator or parent document from the children not being an html link.

We can continue to use it like this, but the issue was if we fill it, we cannot re-empty it (so a solution is to recreate a new one...).

I understand an empty link is not a working link (as if we try to get document we get nothing), so maybe to publish it it should not be empty ?
And as improvement providing the possibility in the navigation property to not create "a" tag by adding an property option (like "no html link" with a checkbox) would bring the possibility to provide more flexibity in menu construction (this option could be use like the "separator" type element menu of wordpress. Just an idea.

And just to give you our method/thinking way on document/menu modeling, usually when we need menus, we create a directory called "menu", and inside put some directory for each menu (named like "header", "footer", etc.). And in each of those directory we create link. So editor user in backend can create menu independant from the document tree. Here is an example (for instance "calculettes" link would be a link not clickable in the rendering menu because not path is set).

![menu](https://cloud.githubusercontent.com/assets/9025839/15875309/8c759d9e-2d07-11e6-99a3-287b1fb8fe0f.png)

I think maybe one day a document_menu type would be needed to make things more clean (like email, printing now, etc...).

Anyway, if you think it is not needed/not a bug you can close the issue.
Thanks!
