### ISSUE TITLE
[Data Objects] API-saving unpublished with empty mandatory field throws exception

### ISSUE THREAD

**Issue by jimmyjammyj** [pimcore/pimcore#6587]
### Expected behavior
Saving unpublished data object via API with unset mandatory field should not throw ValidationException (just like when saving via the UI)

### Actual behavior
Pimcore\Model\Element\ValidationException is thrown if there is an empty mandatory field, even if data object is unpublished.

**Comment by brusch** [comment]
Needs internal discussion ...

**Comment by brusch** [comment]
Check if we can get rid of `omitMandatoryCheck` and just rely on the published state. 
Maybe it would be nice to provide a functionality to force the validation of mandatory fields.

**Comment by dvesh3** [comment]
@brusch I'm not sure, if we should really go with suggested approach, as it has downsides compare to current scenario:

- _Current scenario:_  Still possible to omit mandatory checks for publish & unpublish state

- _if we can get rid of omitMandatoryCheck and just rely on the published state:_ Not possible to omit checks for publish state

So we need an approach where **by default mandatory checks are validated on only published state**(just like Admin UI) and it should still be possible to omit/force mandatory checks irrespective of publish state.

WDYT?

**Comment by brusch** [comment]
@dvesh3 sounds good, so basically we can do an additional check for the published state in `getOmitMandatoryCheck` if it's unpublished we can directly return `true` if not, we just keep the current behavior, so basically just: 

```php
public function getOmitMandatoryCheck()
{
    if(!$this->isPublished()) {
        return true;
    }

    return $this->omitMandatoryCheck;
}
```

This would be then exactly the described behavior, right?

**Comment by dvesh3** [comment]
@brusch partially, yes. but we still need a way to **force** mandatory checks e.g. force checks (omitMandatoryCheck => false)  on unpublished state.

How about we remove default value `false` for `$omitMandatoryCheck` and if mandatory check has been changed then takes priority otherwise just omit based on publish state, so like:
```php
public function getOmitMandatoryCheck()
  {
    if ($this->omitMandatoryCheck == null) {
       return !$this->isPublished();
    }

    return $this->omitMandatoryCheck;
}
```
WDYT?

**Comment by brusch** [comment]
@dvesh3 agree, sounds good to me!
