### ISSUE TITLE
Unable to upload zip archive

### ISSUE THREAD

**Issue by Maksonis** [pimcore/pimcore#6589]
# Bug Report

When I try to upload zip archive to Asset tree

![image](https://user-images.githubusercontent.com/17277953/84473460-64cee880-ac89-11ea-9545-3346a9650b20.png)

I get 

![image](https://user-images.githubusercontent.com/17277953/84473483-6f897d80-ac89-11ea-9806-d695a9f82c94.png)

**Comment by dvesh3** [comment]
regression of #6146
