### ISSUE TITLE
Document Types Grouping

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#659]
It would be cool if there is a possibility to group document types. 

Sometimes there are situations where you handle multiple sub-sites with different document types in one Pimcore instance. And therefore a clean separation would it make much clearer then one long list with quite complicated names...

Maybe just by a convention in the name like "My Group/My Document Type" or "My Group > My Document Type"?

**Comment by brusch** [comment]
We should add another column for **Group** to the configuration grid. 
![image](https://user-images.githubusercontent.com/142037/40050532-07ed65ee-5838-11e8-9537-efc97f16faaa.png)

Visualization: 

![image](https://user-images.githubusercontent.com/142037/40050594-312b0b82-5838-11e8-9de7-86a71cf1b4e8.png)

![image](https://user-images.githubusercontent.com/142037/40050696-85adb542-5838-11e8-80b8-b68540daa948.png)
