### ISSUE TITLE
"Paste as Child" not working since Backend Routing rework

### ISSUE THREAD

**Issue by MercuryKojo** [pimcore/pimcore#6598]
# Bug Report

copy any DataObject in the Treeview of the Pimcore Backend. Try pasting it without inheritance and not recursive "Paste as Child". "Paste as Child (recursive)" and "Paste recursive, updating references" both work fine!

Same goes for Documents "Paste as Child" and "Paste contents only here" other I did not check yet.

## Error
No route found for "POST /admin/object/copy-rewrite-ids": Method Not Allowed (Allow: PUT)
No route found for "POST /admin/document/copy-rewrite-ids": Method Not Allowed (Allow: PUT)

**Comment by weisswurstkanone** [comment]
regression of #6146
