### ISSUE TITLE
Use Carbon instead of DateTime

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#661]
Object data types `Date` and `DateTime` as well as the document editable `Date` should return a Carbon instance instead of DateTime. 

See also: 
https://github.com/briannesbitt/Carbon
http://carbon.nesbot.com/

**Comment by josh-palan** [comment]
I am running on 4.1.3 and having trouble with carbon. I am getting the following error when attempting to save an object with a date, or datetime field:

>  [Wed Aug  3 11:46:13 2016] [hphp] [976:7f7ba7bff700:1009:000001] [] \nFatal error: Uncaught exception 'InvalidArgumentException' with message 'Unknown setter 'date'' in /var/www/pimcore/vendor/nesbot/carbon/src/Carbon/Carbon.php:726\nStack trace:\n#0 (): Carbon\\Carbon->__set()\n#1 (): DateTime->__sleep()\n#2 /var/www/pimcore/pimcore/lib/Pimcore/Tool/Serialize.php(28): serialize()\n#3 /var/www/pimcore/pimcore/models/Version.php(148): Pimcore\\Tool\\Serialize::serialize()\n#4 /var/www/pimcore/pimcore/models/Object/Concrete.php(284): Pimcore\\Model\\Version->save()\n#5 /var/www/pimcore/pimcore/models/Object/Concrete.php(197): Pimcore\\Model\\Object\\Concrete->saveVersion()\n#6 /var/www/pimcore/pimcore/models/Object/AbstractObject.php(593): Pimcore\\Model\\Object\\Concrete->update()\n#7 /var/www/pimcore/pimcore/modules/admin/controllers/ObjectController.php(1093): Pimcore\\Model\\Object\\AbstractObject->save()\n#8 /var/www/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Admin_ObjectController->saveAction()\n#9 /var/www/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch()\n#10 /var/www/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()\n#11 /var/www/pimcore/pimcore/lib/Pimcore.php(260): Zend_Controller_Front->dispatch()\n#12 /var/www/pimcore/index.php(18): Pimcore::run()\n#13 {main}

**Comment by brusch** [comment]
> No this has to be an HHVM thing. Wasn't able to find a fix and had to move everything to a PHP env. Things are working now

@josh-palan please create an issue here https://github.com/briannesbitt/Carbon/issues

**Comment by josh-palan** [comment]
@brusch Carbon seems to have already been notified. I believe this HHVM issue references this problem:

[https://github.com/facebook/hhvm/issues/5893](https://github.com/facebook/hhvm/issues/5893)
