### ISSUE TITLE
Maintenance job errors

### ISSUE THREAD

**Issue by msphn** [pimcore/pimcore#6614]
Since updating to 6.6 I log following errors during maintenance job:

```
14:55:02 ERROR     [app] Fieldcollection 'documents' not found. Please check table object_collection_documents_product
14:55:02 ERROR     [app] Fieldcollection 'images' not found. Please check table object_collection_images_product
14:55:02 ERROR     [app] Fieldcollection 'videos' not found. Please check table object_collection_videos_product
```

I don't know where they are coming from, but probably any change introduced a bug. Or any migration missing not working - I'm not sure.

**Comment by brusch** [comment]
https://github.com/pimcore/pimcore/blob/cc29edea22d412c0fe6a54c78c8b46535d2d28d2/lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php#L65
