### ISSUE TITLE
[Routing error] Copy object as child

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#6619]
# Bug Report

When copying an object as child, you'll get the following error message.
![error_message](https://user-images.githubusercontent.com/17384333/84798882-c2ea2b80-affb-11ea-9b5b-05b8ee7e780e.png)

This is because here the called URL `/admin/object/copy-rewrite-ids` only allows requests with the PUT method ([here](https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L1928)]). Although the generated route has the POST method defined ([here](https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L1912)]).

The question is, which method is the correct one to use, PUT or POST?

**Comment by solverat** [comment]
@aarongerig i just have the same issue - how did you fixed that?

**Comment by solverat** [comment]
ah i see (#6598).

**Comment by aarongerig** [comment]
@solverat Yeah, saw that late as well. ;)
