### ISSUE TITLE
Add event hook, during parsing content asset of type document.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#662]
It would be great to have an event hook on the parse of the content of PDF.
This way developper can insert some custom logic.

One use case could be for instance for OCR (would resolve this by the way https://github.com/pimcore/pimcore/issues/179). So developper can use the hook to add some OCR and store in the search database the content.
If i am not wrong, the process is something like that:
1- transform Word/Excel/Powerpoint/Text to PDF
2- Extract text of the PDF
3- Save text to the search table

Hook event could be between the 2 and 3. So developper can manipulate the result, run some OCR, etc... and provide the final modified text to save.
As target: Pimcore\Model\Asset
As parameters: (i don't think there is need...)
As return: text

I don't know if it make sense this proposition, but if it makes it would be great so developper can extend search feature by manipulating what is stored on the full search table/database.

**Comment by brusch** [comment]
Implemented a more generic way, see:  
https://www.pimcore.org/wiki/pages/viewpage.action?pageId=16854309#EventAPI(EventManager)-SearchBackend(sincebuild3861)

2 new events `search.backend.preSave` and `search.backend.postSave` 

To modify the content of the search item (as requested): 

````php 
\Pimcore::getEventManager()->attach("search.backend.preSave", function (\Zend_EventManager_Event $event) {
    $element = $event->getTarget();
    if($element->getMainType() == "asset") {
        $asset = \Pimcore\Model\Asset::getById($element->getId());
        // extract your content ...
        // and assign it to the data
        $element->setData("your custom data");
    }
});
```

**Comment by Yivan** [comment]
Great! It is exactly what was asked, but you made it better in a generic way yes.
Thanks a lot Brusch.
