### ISSUE TITLE
Operator ObjectBrick getter breaks if 'Brick Attribute' left empty

### ISSUE THREAD

**Issue by pradeep-pimcore** [pimcore/pimcore#6620]
# Bug Report
While doing grid configuration using 'Grid Options' button on folder listing toolbar, 'Operator ObjectBrick Getter' breaks if 'Brick Attribute' is left empty.

I may not want to type in the 'Brick Attribute' field name rather I would like to drag and drop a brick field from 'Class Attributes' panel.

Now even if I drag a brick field from 'Class Attributes' and drop it on the 'Operator ObjectBrick Getter',
it still breaks even after giving a valid brick field.

### Expected behavior

System should be able to handle the empty value of 'Brick Attribute' field in 'Operator ObjectBrick Getter'. It should not break, and should also populate the data when a brick field is dropped onto the operator.

### Actual behavior
System breaks with following error

![brickGetter_error_msg](https://user-images.githubusercontent.com/58973662/84880153-cdfb9500-b0a9-11ea-95c5-96a8a4d28e27.png)

### Steps to reproduce
**As per https://demo.pimcore.fun/**
- Click on 'Data Objects' -> 'Home'
- Select type 'AccessoryPart'
- Click on 'Grid Options'
- Drag and drop an 'Operator ObjectBrick Getter' into the right selection panel
- Fill in the settings popup as
     Attribute: saleInformation
     Brick Type: SaleInformation
     Brick Attribute: (Leave it blank)
- Click Apply ( BREAKS HERE )
- Click 'OK' on error message 
- Drag and drop a brick field into operator ( BREAKS AGAIN )

**Comment by dvesh3** [comment]
bricks as a whole are not supported  on grid,.you need to specify all config to fetch the required attribute from brick on grid i.e.
![image](https://user-images.githubusercontent.com/5137917/84883114-74d33780-b090-11ea-9425-3a06f20aaf16.png)

**Comment by pradeep-pimcore** [comment]
@dvesh3  In that case user should not be able to drop anything on a 'Operator ObjectBrick Getter' and 'Brick Attribute' should be made mandatory for applying the settings.

Or even if it accepts the empty value for 'Brick Attribute', system should not break.

**Comment by dvesh3** [comment]
I would say, grid configuration is free form in a way that it allows you to combine different filters & operators to fetch the required data on grid.

Regarding empty value issue, if you leave all fields empty then it will not complain but if you add any config then it tries to fetch the required value.

Sorry, i don't think it is a bug!

**Comment by NiklasBr** [comment]
Comments like the one above can be used to ignore any and every valid bug report.

1. _The bug may or may not be in the specific implementation of the written code._ <- I suspect this is where @dvesh3 argues the bug does not exists. Possibly correct. But it also dismisses many other sources of errors, such as:
2. The bug may be in the code **not implemented** (such as type checks or `catch`:es to gracefully handle exceptions and maybe display an *actionable error message*)
3. The bug may be in the **interface** (such as clearer design cues or descriptions, or what is allowed by logic constraints)
4. The bug may be in outdated or missing **documentation**.
5. The bug may be in the **design and specification** of the feature. The feature may be implemented in a totally bug-free way according to spec, but did the spec did take everything into account as it should?

The simple fact that a user interface action results in a PHP exception for *Too few arguments* lends credence to the fact that this is likely a bug of type 2 (or less likely type 1). Even if we 100% rule out possibilities for bugs of type 1, 2, and 3 there is no reason not to at least look into the possibility of improving it at type 4.

**Comment by pradeep-pimcore** [comment]
@dvesh3 Server response of 500 with an un-handled exception message on the screen ( with source file path and line number in source file) which is definitely not intended to be seen by an application user and definitely should be termed as application break point.

I think this much is enough to make it count as a valid 'Critical' bug.

**Comment by dvesh3** [comment]
@pradeep-pimcore @NiklasBr Issue rep-open for internal discussion. thanks!

**Comment by fashxp** [comment]
Operator ObjectBrick Getter doesn't make sense anyway ... object brick attributes can be added  to grid configuration directly (with all benefits of filtering, batch assignment, etc.). 

so we should deprecate it and remove it with Pimcore 7.

**Comment by kubaplas** [comment]
@fashxp currently object brick attributes can be added only directly to grid, but not to other operators (try adding input from object brick into e.g. concatenator operator)

**Comment by fashxp** [comment]
@kubaplas thx for the hint, I added it to the remove issue to double check this ...

**Comment by dvesh3** [comment]
Fixed by #7789
