### ISSUE TITLE
Pimcore link: cannot pass custom attributes anymore 

### ISSUE THREAD

**Issue by PandeleCristian** [pimcore/pimcore#6621]
v6.6.4

Description:
We cannot pass custom link attributes such as “data-toggle”, “data-title”, “some-other-custom-attribute” because it’s filtered by $allowedAttributes array, this means they are not being added to the anchor tag.

Example:
`{{ pimcore_link('install-link', {class: 'preheader__install__btn', 'data-type': 'sometype', 'data-toggle': 'modal'}) }}`

This was working before, until https://github.com/pimcore/pimcore/commit/b01256d89764b1eabd985276e3db65f7fe2c6b6c#diff-d045860d712fb1d19c493e0d4fc702fd

**Comment by brusch** [comment]
Attributes prefixed with `data-*` should be possible.

**Comment by dvesh3** [comment]
resolved by #6677
