### ISSUE TITLE
Classification store groups do not work anymore

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#6623]
Regression of https://github.com/pimcore/pimcore/pull/6146

Two routes with name pimcore_admin_dataobject_classificationstore_groupsactionget exist therefore get calls are not possible anymore and will result in the following error:
![image](https://user-images.githubusercontent.com/4639428/84909903-87f8fe00-b0b6-11ea-9924-27ec14917e0d.png)

**Comment by weisswurstkanone** [comment]
already fixed via https://github.com/pimcore/pimcore/pull/6580

**Comment by markus-moser** [comment]
ah sorry, you are right
