### ISSUE TITLE
No context menu when right-clicking in empty space of left sidebar

### ISSUE THREAD

**Issue by themreza** [pimcore/pimcore#6626]
# Bug Report

### Expected behavior
Right clicking on an empty area in the Data Objects sidebar (and others) should show a context menu to add new items.

### Actual behavior
The browser's default context menu is shown upon right clicking in the empty space, which is confusing and unintuitive. This is specially important for a skeleton project.

### Steps to reproduce
Right click anywhere in the empty space of the left sidebar.

[Video demo](https://i.imgur.com/kRQwR9s.mp4)

**Comment by brusch** [comment]
Adding new items in the tree needs a parent, so context menu can only be available on  tree nodes.
