### ISSUE TITLE
Maintenance job archiveLogEntries fails to archive data

### ISSUE THREAD

**Issue by andma03** [pimcore/pimcore#6628]
# Bug Report

### Expected behavior
The execute function in LogArchiveTask.php should insert data from application_logs to an archived application logs table.
### Actual behavior
Using Pimcore v6.6.2 and mysql 8.

The task fails when inserting data to a mysql 8 innodb cluster using group replication because the created application_logs_archive does not have any primary key.

**Stacktrace and info:**
[app] Failed to execute job with ID archiveLogEntries: Doctrine\DBAL\Exception\DriverException {-driverException: Doctrine\DBAL\Driver\PDOException {#1 …}#message: """  An exception occurred while executing 'INSERT INTO application_logs_archive_06_2020  SELECT * FROM application_logs WHERE `timestamp` < DATE_SUB(FROM_UNIXTIME(1592411126), INTERVAL 30 DAY)':\n  \n  SQLSTATE[HY000]: General error: 3098 The table does not comply with the requirements by an external plugin.  """#code: 0#file: "./vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php"#line: 106-previous: Doctrine\DBAL\Driver\PDOException {#1 …}trace: {./vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:106 { …}./vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:169 { …}./vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:149 { …}./vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1019 { …}./vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php:74 { …}./vendor/pimcore/pimcore/lib/Maintenance/Tasks/LogArchiveTask.php:79 { …}./vendor/pimcore/pimcore/lib/Maintenance/Executor.php:88 { …}./vendor/pimcore/pimcore/bundles/CoreBundle/Command/MaintenanceCommand.php:93 { …}./vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255 { …}./vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:1019 { …}./vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:97 { …}./vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:271 { …}./vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:83 { …}./vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:147 { …}./bin/console:26 {› $application = new \Pimcore\Console\Application($kernel);› $application->run();› } …}} ["id" => "archiveLogEntries","exception" => Doctrine\DBAL\Exception\DriverException { …}]
### Steps to reproduce
Use group replication with MySQL 8 and Trigger the maintenance job with ".../bin/console maintenance".
### Code example
```php
// your code
```

# Feature Request
Add configuration to be able to choose if primary keys should be mandatory for all pimcore tables, to fully support MySQL group replication requirements. If performance is not an issue, then primary keys should always be added, and this feature could be ignored.

**Comment by brusch** [comment]
Support for group replication is currently not on our roadmap ... if the needed changes are not too extensive we'd accept PRs for that topic. 
For now I'll close this issue. 

Thanks anyway.
