### ISSUE TITLE
Localized fieldcollection overwrites localized fields in object

### ISSUE THREAD

**Issue by maff** [pimcore/pimcore#663]
1. Create a class with a localized field
2. Add a fieldcollection to the class containing a localized field with the same name as the one on the class
3. Create an object of that class and save it
4. Add a fieldcollection item to the object and save again

Result: the value from the localized field in the fieldcollection is saved to both the fieldcollection item and the object itself, overwriting the existing object value.

Tested on 4.1.1 / build 3821

Class/FC definitions: [LocalizedFC.zip](https://github.com/pimcore/pimcore/files/315666/LocalizedFC.zip)

**Comment by weisswurstkanone** [comment]
fixed in build 3849
