### ISSUE TITLE
Improvement - Set allowed units to empty array when saving a quantity value attribute.

### ISSUE THREAD

**Issue by jacobsyentl** [pimcore/pimcore#6641]
## Description
When adding a new unit for quantity values in Pimcore, we must redefine the class definitions to allow the unit to be able to use them, instead of just leaving no unit selected in the class definition so that by default all units are allowed.

### Expected behavior
We would expect that this attribute behaves the same as an object relation. On object relations: if no classes are selected as allowed, then all classes are allowed. The same would be expected for quantity value units.

### Actual behavior
When we don't select allowed units, then only the units at the time of saving will be allowed for the attribute, any attributes made on-demand will not be added to the list of allowed units.

### Steps to reproduce
1. Add a quantity value attribute to a class.
2. Create a unit on-demand programmatically 
3. Set unit on attribute programmatically
4. The unit will not show on the object since it's not in the collection of allowed units.

**Comment by weisswurstkanone** [comment]
Hi @jacobsyentl could you please share the code, thanks a lot!

**Comment by jacobsyentl** [comment]
```public function processRawFieldData(Concrete $dataObject, string $rawFieldName, string $relationalFieldName = null, $additionalInfo = null)
    {
        $value = $dataObject->{'get' . $rawFieldName}();

        $classDefinition = ClassDefinition::getById($dataObject->getClassId());
        $fieldDefinition = $classDefinition->getFieldDefinition($relationalFieldName);

        //convert to quantityvalue object if necessarry
        if (get_class($fieldDefinition) == QuantityValue::class) {
            /** @var QuantityValue $fieldDefinition */
            $quantityFieldData = floatval($value);
            $rawFieldUnit = $additionalInfo;

            if ($rawFieldUnit) {
                $unitId = Unit::getByAbbreviation($rawFieldUnit);
                if (!$unitId) {
                    $unit = Unit::create([
                        'abbreviation' => $rawFieldUnit,
                        'longname' => $rawFieldUnit,
                    ]);
                    $unit->save();
                    $unitId = $unit->getId();
                }
            } else {
                $unitId = null;
            }

            $value = new \Pimcore\Model\DataObject\Data\QuantityValue($quantityFieldData, $unitId);
        }

        $dataObject->{'set' . ucfirst($relationalFieldName)}($value);
    }
```

The unitId that we are trying to set to the $value variable won't be in the allowed unitId's of the quantity value attribute.

**Comment by weisswurstkanone** [comment]
The data is there but the problem is that the backend UI caches the list of available units.

https://github.com/pimcore/pimcore/blob/a9f787995202fa4729ab26405c940464ae7f35f4/bundles/AdminBundle/Resources/public/js/pimcore/helpers/quantityValue.js#L20

**Comment by jacobsyentl** [comment]
@weisswurstkanone Seems indeed that this would be it. Thanks for picking it up so fast :)
