### ISSUE TITLE
get executables returns true despite command not found

### ISSUE THREAD

**Issue by zieglerh** [pimcore/pimcore#665]
# Bug Report

The process to get an executable returns true, despite command not available
Tested on mac osx and debian linux. Seems to be a php issue.

### Steps to reproduce  
If you do not have e.g. cli binary pdftotext installed but with installed ghostscript and try to save a pdf 

Getting the executable via
```php
\Pimcore\Tool\Console::getExecutable("pdftotext", true);
```
and using a debugger 
![screen_shot_2016-06-16_at_11_01_48](https://cloud.githubusercontent.com/assets/18331614/16111885/01bc4b94-33b5-11e6-8289-949f4a919c19.jpg)

will get a valid resource but with an error

Maybe this can be fixed with "stream_set_blocking()". Take a look at the comments http://php.net/proc_open or just check for errors in streams

**Comment by brusch** [comment]
Interesting, on Debian 8 it works fine for me. 
I'm also not sure whether this is a Pimcore or a Symfony issue, since `->mustRun()` should ensure the program exists and was executed properly.

**Comment by brusch** [comment]
I guess i found the error :-) 
->isSuccessful() should do the trick. 
´
Thanks!

**Comment by zieglerh** [comment]
That was easy. Thanks :)
