### ISSUE TITLE
Unpublished objects showing on 'Error' page

### ISSUE THREAD

**Issue by questionmark78** [pimcore/pimcore#6650]
When there is a page showing e.g. news DataObjects and this page is also set as the default Error page in the System Settings it shows the unpublished News items (DataObjects) when there is displayed through an error. 
In case of a 'normal' visit it behaves as expected and unpublished items are not displayed.

I found out that in Pimcore\Bundle\CoreBundle\EventListener\PimcoreContextListener in the onKernelRequest in case of an error the check on `$event->isMasterRequest()` is returning false and so the `initializeContext()` is not called.
In the `initializeContext()` function the value for hideUnpublised DataObjects is set to true as the default value is to false.

My first reaction would be to set the default value to true, but it is hard to oversee all the implications and perhaps changed behaviour. Or what was the design decision to have the default value false there? Should it be set to some value in any other case?

**Comment by brusch** [comment]
Fixed by #6811
