### ISSUE TITLE
ACL error on overlapping rules for same tree element

### ISSUE THREAD

**Issue by roland4432** [pimcore/pimcore#6654]
# Bug Report

### Expected behavior

ACL with overlapping rules will adopt the correct value for access

### Actual behavior

ACL discards results with the current SQL query and can ommit correct ACLs rights

### Steps to reproduce

Given in PR

### Code example

Given in PR

Please see #6652 for fix and details on how to reproduce

**Comment by dvesh3** [comment]
closed by #6670
