### ISSUE TITLE
Localizedfield: Call to a member function supportsInheritance() on null

### ISSUE THREAD

**Issue by yariksheptykin** [pimcore/pimcore#6658]
A call to `...->getLocalizedfields()->getLocalizedValue('non-existing-field-name')` with a non-existing field name results in the following error:

```
Error : Call to a member function supportsInheritance() on null
```

This is due to `getLocalizedValue` [disregarding](https://github.com/pimcore/pimcore/blob/9eae41107a2f32cf94f371959bd8a843d72c8290/models/DataObject/Localizedfield.php#L438) the fact that `$fieldDefinition` could be `null`. Maybe we should return `null` in this case?

**Comment by brusch** [comment]
In my opinion this is the correct behavior ... calling a non existing getter will throw an exception as well ...
