### ISSUE TITLE
DateTime input in object class has different types after 4.0 upgrade

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#666]
# Bug Report
I'm in the progress of updating a Pimcore installation from 3.x to 4.1.1. I'll switch from Zend_Date to DateTime - I did disable the useZendDate flag as described here: https://www.pimcore.org/wiki/display/PIMCORE4/Update+from+Version+3.x+to+Version+4

I do have a class (todo) which does has a Date & Time field named deadline. I do get some instances of this class using the following code:

`	

			$todolist = new Object_Task_List();
			$todolist->setOrderKey("deadline");
			$todolist->setOrder("asc");
			$todolist->setCondition("IFNULL(done, 0) = 0");
			$this->view->todolist = $todolist;`

In my script I'm iterating about these todos:

`	
foreach($this->todolist as $todo){
	$this->template("default/listtodos.php", array(
		"todo" => $todo
	));
}
`

And I want to execute this code:

`if(($this->todo->deadline->getTimestamp() < time()) && ($this->todo->done != "1")){
	echo '<span class="text-danger"> '.$this->todo->deadline->format('d.m.Y, H:i').' </span><br />';
}`
  
### Expected behavior 
Since todo->deadline should be DateTime object, so I expect format to work.

### Actual behavior  
I'm getting an error: **Call to undefined method Pimcore\Date::format()**

I debugged the script using the following code:

`if(($this->todo->deadline->getTimestamp() < time()) && ($this->todo->done != "1")){
	print_r($this->todo->deadline);
}`

The output looks like this:

> DateTime Object ( [date] => 2016-01-13 10:45:00 [timezone_type] => 3 [timezone] => Europe/Berlin ) 
> DateTime Object ( [date] => 2016-01-28 15:00:00 [timezone_type] => 3 [timezone] => Europe/Berlin ) 
> Pimcore\Date Object ( [_locale:Zend_Date:private] => de [_fractional:Zend_Date:private] => 0 [_precision:Zend_Date:private] => 3 [_unixTimestamp:Zend_Date_DateObject:private] => 1464127200 [_timezone:Zend_Date_DateObject:private] => Europe/Berlin [_offset:Zend_Date_DateObject:private] => -3600 [_syncronised:Zend_Date_DateObject:private] => 0 [_dst:protected] => 1 ) 

There are three todos in the result. Two are DateTime Objects as expected and can handle the format command. The third todo is a Pimcore\Date Object with Zend_Date parts inside. But they are all part of the same class, given the same treatment in the controller and view.

### Steps to reproduce  
As this would require controller coding I can not reproduce this easily on the official live demo. I hope that I gave enough information about the issue. If I can give any further informatino (class export, more code) please tell me.

**Comment by brusch** [comment]
You removed the flag `useZendDate` out of `system.php` right? 
And you cleaned the cache after you did remove the flag? 
Because it's not reproducible on our testing environments.

**Comment by brusch** [comment]
Sorry, pressed the wrong button :)

**Comment by Cruiser13** [comment]
My system.php:

`    "flags" => [
        "useZendDate" => FALSE
    ]`

You are right, clearing the cache solved the problem! Wonder why the system has cached that stuff anyway (Debug mode enabled, output-cache disabled).

Thank you for the fast support - can be closed :)
