### ISSUE TITLE
Database version check

### ISSUE THREAD

**Issue by alexthunder3** [pimcore/pimcore#6663]
# Feature Request

## Feature description
I've seen a lot of issues here open because of some migration script that failed or a mismatch between the actual version pimcore is running, and the version that the database has been updated to.
Another example we just found in a project, some field should have been an enum, but is an integer in our database. Found a migration script for it ages ago, but not applied to our database because there have been not-ideal migrations done, databases moved and so on.
So my question is, is there some command that checks all fields and indexes and such for all the default tables against what should be the correct schema for the version of pimcore the system is running?
I assume there is no such thing yet, so wouldn't it make sense to add such a check? Either based on the latest database migration version, or based on the pimcore version. 

Thanks and kind regards,
Alex.

**Comment by dpfaffenbauer** [comment]
Nope, there isn't. But Pimcore marks migrations as completed, so if you manually run `bin/console pimcore:migrations:migrate -s pimcore_core` all missing migrations should get applied

**Comment by dpfaffenbauer** [comment]
But: what could be done from a Pimcore side, don't create/alter tables with SQL directly, it could use Doctrine Schema to make it and create a "migration" sql command to fix the db. But that needs some core changes first.

**Comment by alexthunder3** [comment]
We fixed the problem, but made me wonder how many imperfections are still out there. Maybe I'll install a fresh copy of pimcore locally to get the correct default schema, and compare that to our project 🤔
