### ISSUE TITLE
Proposal: Add event hook into Web2Print PDF generation

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#667]
I'd like to see event hooks here:
https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Controller/Action/Admin/Printpage.php

We could for example save generated PDFs as assets into Pimcore, assign them to objects and other useful actions if we could trigger the pdfDownloadAction or some other places. At the moment generated PDFs will be placed into the tmp folder and will be gone easily.

At the moment the interaction possibilities of our own controllers with the Web2Print system are very limited.

**Comment by fashxp** [comment]
where exactly?

**Comment by Cruiser13** [comment]
Maybe here? https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Controller/Action/Admin/Printpage.php#L160
At this line the PDF does exist for sure, so we can do something with it.

**Comment by fashxp** [comment]
put it at a bit different position - see https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Web2Print/Processor.php#L91

you position would get executed only when the pdf is downloaded manually in frontend, not when it is generated. 

see also https://www.pimcore.org/wiki/pages/viewpage.action?pageId=16854309

**Comment by Cruiser13** [comment]
Thank you, perfect solution!
