### ISSUE TITLE
Editables required - Can't change to a template with a required editable

### ISSUE THREAD

**Issue by MosiiAUT** [pimcore/pimcore#6673]
Pimcore v6.5.3
### Expected behavior

Change pimcore-document to specific controller+action / template and save the change

### Actual behavior

Unable to create a predefined pimcore-document with an editable in it's template, that is required e.g. input-editable, or change to this controller+action

### Steps to reproduce

Change pimcore-document to specific controller+action / Template with an required editable in it and save it, or try to create a pimcore-document from a predefined document

**Comment by KatrinAckermannEk** [comment]
This is an issue we have stumbled upon as well and it is preventing us from using the required option in editables to its full extent. Hope you guys take a closer look at this!

**Comment by dvesh3** [comment]
@MosiiAUT @KatrinAckermannEk Unable to reproduce! could you please share precise steps to reproduce the issue? thanks!

**Comment by KatrinAckermannEk** [comment]
Basically what has been written in "Steps to reproduce".
We have a document with any kind of controller/action assigned to it. Now, we change the controller/action to one that comes with a template, that has editables in it with "required: true".
Saving, and therefor changing the document to that new controller/action, fails.

**Comment by brusch** [comment]
Fixed by #7198
