### ISSUE TITLE
Resend/Forward e-mail in e-mail logs with sender name does not work

### ISSUE THREAD

**Issue by MercuryKojo** [pimcore/pimcore#6680]
# Bug Report

When the from address of the log line contains the sendername (e.g. "example@test.com (Example Test)"). The resend and forward function does not work

## Error
```
Timestamp: Thu Jun 25 2020 15:36:57 GMT+0200 (Central European Summer Time)
Status: 500 | 
URL: /admin/email/resend-email
Method: POST
Message:  - Expected response code 250 but got code "501", with message "501 5.1.7 Bad sender address syntax
"
Trace: 
in .../vendor/pimcore/pimcore/lib/Mail.php:621
#0 .../vendor/pimcore/pimcore/lib/Mail.php(560): Pimcore\Mail->sendWithoutRendering(Object(Swift_Mailer))
#1 .../vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/EmailController.php(353): Pimcore\Mail->send()
#2 .../vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(158): Pimcore\Bundle\AdminBundle\Controller\Admin\EmailController->resendEmailAction(Object(Symfony\Component\HttpFoundation\Request))
#3 .../vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#4 .../vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 .../web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#6 {main}
```

## Reproduce

- find a email log where the from address contains the sendername
- click on resend email and confirm
- error message will pop up

**Comment by brusch** [comment]
This should be fixed by #3661 , right? This PR changed the format to `NAME <name@email.com>`

**Comment by aicma** [comment]
@brusch we are running pimcore v6.7.3 an we have the same issue.
Logs are formatted as address@domain.tld (name) which results in an error on resend/forward

**Comment by brusch** [comment]
@aicma ok, interesting, can you maybe debug this and provide a PR? Thanks in advance!

**Comment by aicma** [comment]
is already fixed in current Version [via this commit](https://github.com/pimcore/pimcore/commit/63115ea3346d9c3b2b5718314be6b9af74a4fcd9)
Can you cherry pick this into a Bugfix version for 6.7. ?

**Comment by brusch** [comment]
Sorry, there won't be any further 6.7 releases.
