### ISSUE TITLE
[New feature] Hook JS before redrawing grid (ex: for customizing row color depending calculated value)

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#6681]
Hello,

There are some case where is would be usefull to be able to act on the object grid listing before drawed by ExtJS. So it would be able to change settings, etc.

For instance, add a css class for some rows so they can have a green/red baground color depending on the object value for this row (inactive status, order not paid, etc.)

For exemple, we could color in red the news object in this listing having an outdated date:
![image](https://user-images.githubusercontent.com/9025839/85777762-34278e00-b722-11ea-9508-14af8af3c50c.png)

I don't known if this is just an event to add, or if this is more complicated (because data are not related to grid structure in ExtJS as they are requested in ajax after grid structure/settings has been setted).

Best regards.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
