### ISSUE TITLE
FosJsRouting: Route generation not working for pimcore_admin_reports_qrcode_tree

### ISSUE THREAD

**Issue by guidoheckmann** [pimcore/pimcore#6683]
Js generating of routes is not working. I get this error in browser console when I try to open Marketing -> QR-Codes:
`Error: The route "pimcore_admin_reports_qrcode_tree" does not exist. router.js:272:19`

QR-Codes tab will not open.
My pimcore version is 6.6.7

**Comment by weisswurstkanone** [comment]
Unable to reproduce on demo.pimcore.fun

**Comment by brusch** [comment]
See #6648
