### ISSUE TITLE
CSV Export: quantity value type field exports the database id of unit instead of unit abbreviation

### ISSUE THREAD

**Issue by pradeep-pimcore** [pimcore/pimcore#6684]
# Bug Report
In CSV export for a class, quantity value type field exports the database id of unit instead of unit abbreviation.
And an underscore is added between the quantity and unit value in export.

### Expected behavior
System should export unit abbreviation as it works in grid view

### Actual behavior
System exports the database id of unit

### Steps to reproduce ( as per demo.pimcore.fun )

- Click on DataObject -> Home
- Select class AccessoryPart
- Click on 'Grid Options'
- Drag 'Milage' ( quantity value ) field from SaleInformation Brick and drop on right panel
- Apply the changes
- Click on 'CSV export'
- Observe the value exported for 'Milage' (quantity value) field

**Comment by fashxp** [comment]
fixed with https://github.com/pimcore/pimcore/pull/6667
