### ISSUE TITLE
Asset Metadata not being displayed

### ISSUE THREAD

**Issue by elements-team** [pimcore/pimcore#6686]
Related to a [recent update from 6.0.5 to >6.6.4](https://github.com/pimcore/pimcore/issues/6648), we found that the metadata of assets is not displayed anymore - despite the `assets_metadata` table containing data.

Some debugging resulted in finding the culprit: https://github.com/pimcore/pimcore/commit/6b5316af120186f6d6fc048943428ad9e21aca02

Specifically, the following happens:
> Assume that metadata is available for the asset in the following scenario, with `hasMetadata` being 1 in the `DB` - but there is no `type` set for the metadata entry (i.e., `type` is `null`).

1. An  `Asset` is loaded for the first time (so it's not cached).
2. Eventually, `setMetadata` (of the `Asset` model) is called in order to populate the model.
3. As per the referenced commit, `setHasMetadata(false)` is called, followed by a call to `addMetadata`.
4. Since `addMetadata` checks whether a `type` is available, the metadata-entries are not added to the modal.
    1. The call to `setHasMetadata(true)` is therefore never reached, which results in no metadata being displayed in the backend.

Before the referenced commit, the metadata was simply set using `$this->setHasMetaData(!empty($metadata));`, thus always displaying metadata if available.

**While the behaviour is not a bug, there should be a migration script that migrates `null` values of the `type` column to `input`.**

**Comment by weisswurstkanone** [comment]
important question to figure out: why is the type "null" ?

**Comment by brusch** [comment]
Fixed by #7685
