### ISSUE TITLE
ZIP Upload for Assets very slow

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#6687]
Just reproduced in the official demo. I tried to upload the attached file (264kb)
[Archiv.zip](https://github.com/pimcore/pimcore/files/4837347/Archiv.zip)

The progress bar was stuck at 0% for about 3 minutes before the upload started.

**Comment by andreas-gruenwald** [comment]
@ckemptner @putzflorian 
I think the reason for the bottleneck is as follows.

1) The ZIP-File is chunked into smaller jobs.
2) For each job the ZIP file is unpacked again. 

The ZIP file should only be unpacked once at the very beginning, and then the jobs should only convert the files into Pimcore assets.

A more sophisticated solution would be to decouple the upload process from the user interface and make it run in the background, independently. This might also provide additional means for parallelization.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
