### ISSUE TITLE
Search/Filter for Email Documents not working properly with "-"

### ISSUE THREAD

**Issue by FranzRest** [pimcore/pimcore#6690]
# Bug Report
The "Filter/Search" in the "Sent Emails" Tab of email-documents is not working properly with emails containing "-".
When searching for an email with an included "-" no results are shown.
A lot of emails are using "-", therefore the expected behavior would be highly appreciated.

### Expected behavior
I can also Filter/Search for emails containing "-"

### Actual behavior
Searching for an email containing "-" leads to 0 results

### Steps to reproduce
1. Open an email-document in the Pimcore demo (e.g. confirmation-mail)
2. Send a Test-Email to an email containing "-" (e.g. test.testing-test@testing.at)
3. Open the "Sent Emails" Tab
4. Filter/Search for "test.testing-test"
5. No result is shown

Interesting variations:

test. -> results are shown
test.testing -> results are shown
test.testing-t -> results are shown
test.testing-test@ -> results are shown
test.testing-test@testing.at -> results are shown

**test.testing-test -> no results are shown**

Screenshots for a working & not-working example
![Search-working](https://user-images.githubusercontent.com/6606770/85988292-1f334f00-b9ef-11ea-9b71-7ade9c30b42d.png)
![Search-notworking](https://user-images.githubusercontent.com/6606770/85988296-1fcbe580-b9ef-11ea-95ef-14826e74eaab.png)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
