### ISSUE TITLE
Service::getValidKey() should remove quotation marks ( " ) 

### ISSUE THREAD

**Issue by MosiiAUT** [pimcore/pimcore#6692]
Using this funktion should remove quotation marks in object-keys.

If a object has a name like 'The "bug" object' and you put it in a Wysiwyg (with a correct linked link-generator), the created <a>-tag is destroyed and will lead to a 404.

**Comment by brusch** [comment]
@MosiiAUT I'd say it's up to the link generator to generate valid links, if you are using the object key for building the URL you have to ensure that the result is a valid URL.
