### ISSUE TITLE
Newsletter documents - no preview button available in toolbar

### ISSUE THREAD

**Issue by StephenBeirlaen** [pimcore/pimcore#6695]
# Bug Report

### Expected behavior

When editing Newsletter items, the "Open preview in new window" button is not available, even though this kind of document has a preview URL if we construct it manually (/newsletters/folder/newsletter?pimcore_preview=true&_dc=12345).

![image](https://user-images.githubusercontent.com/11806615/86019797-5887b100-ba27-11ea-9a3f-7e3e5821ea18.png)

### Actual behavior

Both buttons do not appear:

![image](https://user-images.githubusercontent.com/11806615/86020174-dd72ca80-ba27-11ea-8bbd-4d9fea543d6f.png)

### Steps to reproduce

Add a newsletter document in the Pimcore admin.

### Code example

The button being left out is caused by the `this.data["url"]` null check in [page_snippet.js](https://github.com/pimcore/pimcore/blob/c4e091969e509f33b3b92b5ed573c1ecc2ba616d/bundles/AdminBundle/Resources/public/js/pimcore/document/page_snippet.js#L229) where both the open_in_new_window and open_preview_in_new_window buttons are depending on. The check seems appropriate for the open_in_new_window (where the data.url is used) but not for the open_preview_in_new_window (where data.path + data.key are used).

Should this preview button get placed outside the if condition, or should the Newsletter object data be provided with a "url" field as well? In the latter case, I do not know how to fix this myself.

**Comment by dvesh3** [comment]
closed by #6770
