### ISSUE TITLE
Accessing Pimcore Assets via WebDAV not working

### ISSUE THREAD

**Issue by woellundwoell** [pimcore/pimcore#6696]
# Bug Report

### Steps to reproduce
* Open https://demo.pimcore.fun/admin/asset/webdav in webbrowser (using demo credentials)
* check var/logs/prod.log 
`[2020-06-29 16:54:14] pimcore.ERROR: Symfony\Component\Routing\Exception\MissingMandatoryParametersException: Some mandatory parameters are missing ("path") to generate a URL for route "pimcore_admin_webdav"`

### Possible reason
Missing default or emtpy value for parameter "path" in 
https://github.com/pimcore/pimcore/blob/c4e091969e509f33b3b92b5ed573c1ecc2ba616d/bundles/AdminBundle/Controller/Admin/AssetController.php#L901

### Possible solution
Add a default for $path
`public function webdavAction(Request $request, string $path = '')`

Is this solution feasible? If so we could provide a PR

**Comment by brusch** [comment]
Fixed by #6777
