### ISSUE TITLE
[Console commands] Long running processes might run into MySQL timeout

### ISSUE THREAD

**Issue by podarcis** [pimcore/pimcore#6699]
# Bug Report

(While this seems to be a general issue, it's only relevant to console command/ CLI context and long running processes.)

When a process has a long runtime and does not issue any MySQL query for a time longer than MySQL's `wait_timeout` and after that period issues a query, the process might run into a MySQL timeout `SQLSTATE[HY000]: General error: 2006 MySQL server has gone away`.

### Expected behavior

- No timeout at all or handling of MySQL disconnect OR
- Information/ note about mysqld configuration of `wait_timeout` in [system requirements](https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/System_Requirements.html) (MySQL default seems to be 480m. However, most likely the value is being configured much lower. The hoster of the project in question has a `wait_timeout` of 5m)

### Actual behavior

When MySQL timeout occurs and query is issued, a Doctrine DBAL exception is thrown and the code is not working as expected.

### Steps to reproduce

 Have a big dataset and a console command performing work other than communicating with the database long than `wait_timeout`.

Example:

- A big Elasticsearch index (4GB+) and
- `wait_timeout` of 5m
- Console command `ecommerce:indexservice:elasticsearch-sync reindex` (Reindexing Elasticsearch index)

### Possible solutions

1) Increase `wait_timeout` (either per mysqld configuration GLOBAL or at runtime SESSION)
  - either by Pimcore itself
  - or mentioned in documentation
2) Keep alive mechanism such as https://gist.github.com/boekkooi/ff2ff146246d5ea20764 ? (didn't work for me, as `ticks` needed to be declared in different scope)
3) Using Doctrine's PingableConnection?

#### Project's workaround (increasing wait_timeout at runtime in console command context)

Subscribe to `console.command` event and set MySQL `wait_timeout` SESSION variable.

```php
<?php
namespace AppBundle\EventSubscriber;

use Pimcore\Db;
use Symfony\Component\Console\ConsoleEvents;
use Symfony\Component\Console\Event\ConsoleCommandEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class ConsoleSubscriber implements EventSubscriberInterface
{
    const MYSQL_WAIT_TIMEOUT = 3600;     // use 60m as timeout (default MySQL:480m, used hoster:5m)

    protected Db\Connection $db;

    /**
     * ConsoleSubscriber constructor.
     * @param Db\Connection $db
     */
    public function __construct(Db\Connection $db)
    {
        $this->db = $db;
    }

    /**
     * @inheritDoc
     */
    public static function getSubscribedEvents()
    {
        return [
            ConsoleEvents::COMMAND => 'onConsoleCommand',
        ];
    }

    public function onConsoleCommand(ConsoleCommandEvent $e)
    {
        try {
            // Workaround: Increase MySQL wait_timeout for this session
            $this->db->query('SET SESSION wait_timeout = ' . self::MYSQL_WAIT_TIMEOUT);
        } catch (\Exception $e) {
            \Pimcore\Logger::warn('Could not increase MySQL SESSION variable wait_timeout.');
        }
    }
}
```

**Comment by kdefives** [comment]
@podarcis , i would like to say you "Thank You!". I tried to find a nice and clean workaround during many hours to cover my needs and the workaround executing SET SESSION wait_timeout = ... at the beginning of the Command exeution works perfectly!
Thx dude :)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
