### ISSUE TITLE
Feature Request - CSV/XLSX export WYSIWYG attributes without html tags.

### ISSUE THREAD

**Issue by jacobsyentl** [pimcore/pimcore#6700]
# Feature Request
Many of our clients make use of WYSIWYG attributes to format texts for web purpose, but also make use of the CSV/XLSX export functionality to reuse these same texts in offline documents like tenders and quotations.

It would be nice if there is some sort of possibility, maybe a grid operator, that makes it possible to export WYSIWYG fields without HTML formatting. Additionally, it would be nice if HTML formatting could be converted to excel formatting in case of the XLSX-export. 

## Feature description
- Export WYSIWYG attributes without HTML tags.
- Export WYSIWYG attributes with Excel formatting for XLSX export.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
