### ISSUE TITLE
Image in image-editable breaks if too many Hotspots 

### ISSUE THREAD

**Issue by MosiiAUT** [pimcore/pimcore#6703]
This issue is only relevant for the Pimcore-Backend.
If too many Hotspots are used, the image breaks or rather the URL gets extremely long.

I guess every info of these Hotspots are stored in the URL. 
Maybe add some settings to limit the number of usable hotspots.

**Comment by dvesh3** [comment]
@MosiiAUT please share steps to reproduce. thanks!

**Comment by MosiiAUT** [comment]
@dvesh3 easiest way would be:

1.  Create a Image-Editable in a template
2.  In the pimcore-backend, put a image in it and add a lot of Hotspots
(3. In my case, I also added a object to every hotspot)

**Comment by brusch** [comment]
@MosiiAUT can you please concretise  _a lot of hotspots_ are we talking about 10 or 1000? Thanks :)

**Comment by MosiiAUT** [comment]
in my case, there were about 15 hotspots, each with an object in it :)

so the url of the image in the pimcroe looked like this: 

/admin/asset/get-image-thumbnail?id=12051&path=/bilder/sommerpano-neutral-015-web.jpg&alt=&hotspots%5B0%5D%5Btop%5D=79.4251134644478&hotspots%5B0%5D%5Bleft%5D=27&hotspots%5B0%5D%5Bwidth%5D=2.1&hotspots%5B0%5D%5Bheight%5D=2.8744326777609683&hotspots%5B0%5D%5Bdata%5D%5B0%5D%5Bname%5D=Slow%20Trail%20Pressegger%20See&hotspots%5B0%5D%5Bdata%5D%5B0%5D%5Btype%5D=document&hotspots%5B0%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/test/de/Summer-World/World-of-Lakes/Wasser-erleben/Pressegger-See/Slow-Trail-Pressegger-See&hotspots%5B0%5D%5Bname%5D=Slow%20Trail%20Pressegger%20See&hotspots%5B1%5D%5Btop%5D=31.164901664145233&hotspots%5B1%5D%5Bleft%5D=70.1&hotspots%5B1%5D%5Bwidth%5D=2.1&hotspots%5B1%5D%5Bheight%5D=2.8744326777609683&hotspots%5B1%5D%5Bdata%5D%5B0%5D%5Bname%5D=Sommerrodelbahn&hotspots%5B1%5D%5Bdata%5D%5B0%5D%5Btype%5D=document&hotspots%5B1%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/test/de/Family-World/Sommer/Kids-Erlebniswelten/Sommerrodeln&hotspots%5B1%5D%5Bname%5D=Sommerrodelbahn&hotspots%5B2%5D%5Btop%5D=37.97276853252647&hotspots%5B2%5D%5Bleft%5D=65.1&hotspots%5B2%5D%5Bwidth%5D=2.1&hotspots%5B2%5D%5Bheight%5D=2.8744326777609683&hotspots%5B2%5D%5Bdata%5D%5B0%5D%5Bname%5D=Outdoor%20Park%20test&hotspots%5B2%5D%5Bdata%5D%5B0%5D%5Btype%5D=document&hotspots%5B2%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/test/de/Family-World/Sommer/Kids-Erlebniswelten/Outdoor-Park-test&hotspots%5B2%5D%5Bname%5D=Outdoor%20Park%20test&hotspots%5B3%5D%5Btop%5D=93.04084720121028&hotspots%5B3%5D%5Bleft%5D=1.7&hotspots%5B3%5D%5Bwidth%5D=2.1&hotspots%5B3%5D%5Bheight%5D=2.8744326777609683&hotspots%5B3%5D%5Bdata%5D%5B0%5D%5Bname%5D=Schaubergwerk%20Terra%20Mystica%20%26%20Montana&hotspots%5B3%5D%5Bdata%5D%5B0%5D%5Btype%5D=object&hotspots%5B3%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/Infrastructure/Infrastructures/Schaubergwerk%20Terra%20Mystica%20%26%20Montana1f961278-7d82-44ae-ab0b-0c410f8c49ac&hotspots%5B3%5D%5Bname%5D=Schaubergwerk%20Terra%20Mystica%20%26%20Montana&hotspots%5B4%5D%5Btop%5D=87.5945537065053&hotspots%5B4%5D%5Bleft%5D=16&hotspots%5B4%5D%5Bwidth%5D=2.4&hotspots%5B4%5D%5Bheight%5D=3.02571860816944&hotspots%5B4%5D%5Bdata%5D%5B0%5D%5Bname%5D=1.%20K%C3%A4rntner%20Erlebnispark&hotspots%5B4%5D%5Bdata%5D%5B0%5D%5Btype%5D=object&hotspots%5B4%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/Infrastructure/Infrastructures/1.%20K%C3%A4rntner%20Erlebnispark42d26f50-b228-4774-883b-ae8862db4071&hotspots%5B4%5D%5Bname%5D=1.%20K%C3%A4rntner%20Erlebnispark&hotspots%5B5%5D%5Btop%5D=91.37670196671709&hotspots%5B5%5D%5Bleft%5D=97.1&hotspots%5B5%5D%5Bwidth%5D=2.1&hotspots%5B5%5D%5Bheight%5D=2.8744326777609683&hotspots%5B5%5D%5Bdata%5D%5B0%5D%5Bname%5D=Aquarena&hotspots%5B5%5D%5Bdata%5D%5B0%5D%5Btype%5D=object&hotspots%5B5%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/Infrastructure/Infrastructures/Aquarenae17be27e-f290-4d11-bf8e-462bc96151a8&hotspots%5B5%5D%5Bname%5D=Aquarena&hotspots%5B6%5D%5Btop%5D=86.9894099848714&hotspots%5B6%5D%5Bleft%5D=25.6&hotspots%5B6%5D%5Bwidth%5D=2.1&hotspots%5B6%5D%5Bheight%5D=2.8744326777609683&hotspots%5B6%5D%5Bdata%5D%5B0%5D%5Bname%5D=Abenteuerspielplatz%20%22Im%20Reich%20der%20Seehexe%22&hotspots%5B6%5D%5Bdata%5D%5B0%5D%5Btype%5D=object&hotspots%5B6%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/Infrastructure/Infrastructures/Abenteuerspielplatz%20Im%20Reich%20der%20Seehexeafa19cfd-c956-495a-b29f-64cc893c057c&hotspots%5B6%5D%5Bname%5D=Abenteuerspielplatz%20%22Im%20Reich%20der%20Seehexe%22&hotspots%5B7%5D%5Btop%5D=69.44024205748866&hotspots%5B7%5D%5Bleft%5D=32.3&hotspots%5B7%5D%5Bwidth%5D=2.1&hotspots%5B7%5D%5Bheight%5D=2.8744326777609683&hotspots%5B7%5D%5Bdata%5D%5B0%5D%5Bname%5D=Radweg%20R3&hotspots%5B7%5D%5Bdata%5D%5B0%5D%5Btype%5D=object&hotspots%5B7%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/Infrastructure/Infrastructures/Radweg%20R3a4d48a64-a251-48ff-82ee-99c8a37d9637&hotspots%5B7%5D%5Bname%5D=Radweg%20R3&hotspots%5B8%5D%5Btop%5D=62.32980332829047&hotspots%5B8%5D%5Bleft%5D=62.4&hotspots%5B8%5D%5Bwidth%5D=2.1&hotspots%5B8%5D%5Bheight%5D=2.8744326777609683&hotspots%5B8%5D%5Bdata%5D%5B0%5D%5Bname%5D=Flow-Trail%20%22MEX-Line%20I%22&hotspots%5B8%5D%5Bdata%5D%5B0%5D%5Btype%5D=object&hotspots%5B8%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/Tour/Tours/Flow-Trail%20MEX-Line%20I917e1be9-a38f-4162-a953-49bbf20721a7&hotspots%5B8%5D%5Bname%5D=Flow-Trail%20%22MEX-Line%20I%22&hotspots%5B9%5D%5Btop%5D=16.792738275340394&hotspots%5B9%5D%5Bleft%5D=42.3&hotspots%5B9%5D%5Bwidth%5D=2.1&hotspots%5B9%5D%5Bheight%5D=2.8744326777609683&hotspots%5B9%5D%5Bdata%5D%5B0%5D%5Bname%5D=Klettersteig%20D%C3%A4umling&hotspots%5B9%5D%5Bdata%5D%5B0%5D%5Btype%5D=object&hotspots%5B9%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/Tour/Tours/Klettersteig%20D%C3%A4umlingcb7d6740-6743-4c0f-b5d1-aa03d1dd334e&hotspots%5B9%5D%5Bname%5D=Klettersteig%20D%C3%A4umling&hotspots%5B10%5D%5Btop%5D=20.574886535552192&hotspots%5B10%5D%5Bleft%5D=45.2&hotspots%5B10%5D%5Bwidth%5D=2.1&hotspots%5B10%5D%5Bheight%5D=2.8744326777609683&hotspots%5B10%5D%5Bdata%5D%5B0%5D%5Bname%5D=Bergspielplatz%20Almrausch&hotspots%5B10%5D%5Bdata%5D%5B0%5D%5Btype%5D=object&hotspots%5B10%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/Infrastructure/Infrastructures/Bergspielplatz%20Almrausch%20%28Gartnerkofel%2987e5fd28-2424-418d-b41e-af5c7409ea20&hotspots%5B10%5D%5Bname%5D=Bergspielplatz%20Almrausch&hotspots%5B11%5D%5Btop%5D=25.416036308623298&hotspots%5B11%5D%5Bleft%5D=44&hotspots%5B11%5D%5Bwidth%5D=2.1&hotspots%5B11%5D%5Bheight%5D=2.8744326777609683&hotspots%5B11%5D%5Bdata%5D%5B0%5D%5Bname%5D=Panoramaterrasse%20mit%20%22Sky%20Plate%22&hotspots%5B11%5D%5Bdata%5D%5B0%5D%5Btype%5D=object&hotspots%5B11%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/Infrastructure/Infrastructures/Panoramaterrasse%20mit%20Sky%20Platec0f3b382-8105-41cf-943e-4496e7b6c693&hotspots%5B11%5D%5Bname%5D=Panoramaterrasse%20mit%20%22Sky%20Plate%22&hotspots%5B12%5D%5Btop%5D=21.78517397881997&hotspots%5B12%5D%5Bleft%5D=41.7&hotspots%5B12%5D%5Bwidth%5D=2.1&hotspots%5B12%5D%5Bheight%5D=2.8744326777609683&hotspots%5B12%5D%5Bdata%5D%5B0%5D%5Bname%5D=Fotopoint%20Gartnerkofel%20%26%20test%20Kino&hotspots%5B12%5D%5Bdata%5D%5B0%5D%5Btype%5D=object&hotspots%5B12%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/Infrastructure/Infrastructures/Fotopoint%20Gartnerkofel728d57c8-79e9-49d0-9a15-bd6af57d1143&hotspots%5B12%5D%5Bname%5D=Fotopoint%20Gartnerkofel%20%26%20test%20Kino&hotspots%5B13%5D%5Btop%5D=33.28290468986384&hotspots%5B13%5D%5Bleft%5D=56.1&hotspots%5B13%5D%5Bwidth%5D=2.1&hotspots%5B13%5D%5Bheight%5D=2.8744326777609683&hotspots%5B13%5D%5Bdata%5D%5B0%5D%5Bname%5D=Erlebnismeile%20%22Im%20Reich%20der%20Wilden%20Bande%22&hotspots%5B13%5D%5Bdata%5D%5B0%5D%5Btype%5D=object&hotspots%5B13%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/Infrastructure/Infrastructures/Erlebnismeile%20Im%20Reich%20der%20Wilden%20Bande5cafe6a7-fda3-463e-943d-74d16239336a&hotspots%5B13%5D%5Bname%5D=Erlebnismeile%20%22Im%20Reich%20der%20Wilden%20Bande%22&hotspots%5B14%5D%5Btop%5D=94.40242057488653&hotspots%5B14%5D%5Bleft%5D=97.1&hotspots%5B14%5D%5Bwidth%5D=2.1&hotspots%5B14%5D%5Bheight%5D=2.8744326777609683&hotspots%5B14%5D%5Bdata%5D%5B0%5D%5Bname%5D=Gailtal%20Bauer&hotspots%5B14%5D%5Bdata%5D%5B0%5D%5Btype%5D=object&hotspots%5B14%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/Infrastructure/Infrastructures/Gailtal%20Bauerf00a7c5c-b7e7-4758-981e-53e95711bdca&hotspots%5B14%5D%5Bname%5D=Gailtal%20Bauer&hotspots%5B15%5D%5Btop%5D=80.48411497730712&hotspots%5B15%5D%5Bleft%5D=46.2&hotspots%5B15%5D%5Bwidth%5D=2.1&hotspots%5B15%5D%5Bheight%5D=2.8744326777609683&hotspots%5B15%5D%5Bdata%5D%5B0%5D%5Bname%5D=Familienrafting&hotspots%5B15%5D%5Bdata%5D%5B0%5D%5Btype%5D=object&hotspots%5B15%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/Infrastructure/Infrastructures/Rafting%20Carnica9f28c069-dc64-439a-84eb-adc942c5ab5c&hotspots%5B15%5D%5Bname%5D=Familienrafting&hotspots%5B16%5D%5Btop%5D=30.408472012102873&hotspots%5B16%5D%5Bleft%5D=63.4&hotspots%5B16%5D%5Bwidth%5D=2.1&hotspots%5B16%5D%5Bheight%5D=2.8744326777609683&hotspots%5B16%5D%5Bdata%5D%5B0%5D%5Bname%5D=Madritschen-Tour&hotspots%5B16%5D%5Bdata%5D%5B0%5D%5Btype%5D=object&hotspots%5B16%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/Infrastructure/Infrastructures/Madritschen%20Toure2d77b94-743e-48bb-9290-a48ab4579c86&hotspots%5B16%5D%5Bname%5D=Madritschen-Tour&hotspots%5B17%5D%5Btop%5D=21.02874432677761&hotspots%5B17%5D%5Bleft%5D=73.4&hotspots%5B17%5D%5Bwidth%5D=2.1&hotspots%5B17%5D%5Bheight%5D=2.8744326777609683&hotspots%5B17%5D%5Bdata%5D%5B0%5D%5Bname%5D=Fotopoint%20Madritsche%20%26%20test%20Kino&hotspots%5B17%5D%5Bdata%5D%5B0%5D%5Btype%5D=object&hotspots%5B17%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/Infrastructure/Infrastructures/Fotopoint%20Madritschee93b78b8-cdf5-4f25-bd66-26753fae0768&hotspots%5B17%5D%5Bname%5D=Fotopoint%20Madritsche%20%26%20test%20Kino&hotspots%5B18%5D%5Btop%5D=25.264750378214828&hotspots%5B18%5D%5Bleft%5D=75.2&hotspots%5B18%5D%5Bwidth%5D=2.1&hotspots%5B18%5D%5Bheight%5D=2.8744326777609683&hotspots%5B18%5D%5Bdata%5D%5B0%5D%5Bname%5D=Aqua%20Trail%20%22BergWasser%22&hotspots%5B18%5D%5Bdata%5D%5B0%5D%5Btype%5D=object&hotspots%5B18%5D%5Bdata%5D%5B0%5D%5Bvalue%5D=/Infrastructure/Infrastructures/Aqua%20Trail%20BergWasser7a04e11f-dba0-417e-9b9e-5904fb7bd60a&hotspots%5B18%5D%5Bname%5D=Aqua%20Trail%20%22BergWasser%22&height=undefined&thumbnail=hotspot-background&pimcore_editmode=1

**Comment by brusch** [comment]
Resolved by #6778
