### ISSUE TITLE
JS error in editables in master branch

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#6710]
# Bug Report

I have multiple bricks with wysiwyg editables and edit button in one document.

## 6.6 Branch
All is okay.

## master Branch
Only the first brick has an edit button and there is an error in the Chrome console:
```
TypeError: Cannot read property 'wysiwyg' of undefined
```
This error is from here:
https://github.com/pimcore/pimcore/blob/7a5acaa75d7f8fbe614824905314c6a66135c34a/bundles/AdminBundle/Resources/public/js/pimcore/document/edit/startup.js#L153

I want to test it in the pimcore demo. But there is branch 6.6. Exists a demo with master branch?

**Comment by dvesh3** [comment]
@NiklasBr can you please share reproducible scenario? thanks!

**Comment by blankse** [comment]
@dvesh3 I find the error and create a PR. If I have time, I can install the demo with master branch for my one and test it there.

If I have time, I can install the demo with master branch and test it there. Than I can you give a scenario.

**Comment by dvesh3** [comment]
maybe you can share your view & brick template structure. I'll give it a try!

**Comment by blankse** [comment]
It is enough to create a new page in the demo:

1. Open Context menu in documents
2. Add Page > Content-Page
3. Errors in Chrome JS Console:
![image](https://user-images.githubusercontent.com/998558/86255340-49376d80-bbb7-11ea-89b5-3a97a16609f5.png)
`TypeError: Cannot read property 'blockquote' of undefined`

**Comment by dvesh3** [comment]
It works for me on demo.pimcore.fun 😕 no error in console
![image](https://user-images.githubusercontent.com/5137917/86256601-cd3e2500-bbb8-11ea-82b5-c385cdf5e99b.png)

**Comment by blankse** [comment]
Yes the public demo is in branch 6.6. There it works.
