### ISSUE TITLE
Object listing grid: objectbrick fields are not working with operators

### ISSUE THREAD

**Issue by pradeep-pimcore** [pimcore/pimcore#6713]
# Bug Report

In the object listing grid, objectbrick fields do not work with operators.

### Expected behavior
Data should be populated with the expected action of the applied operator

### Actual behavior
No data is populated, data is empty for all the records.

### Steps to reproduce
As per demo.pimcore.fun

- Click DataObejcts -> home
- Select class 'AccessoryPart'
- Click on 'Grid Options' button
- Drag and drop operator ' Operator Trimmer' to the right panel ( though any operator can be used, no operator works fine )
- Drag and drop objectbrick field 'Availability Type' to the 'Operator Trimmer'
- Click 'Apply' button
- Observe the data produced by operator

**Comment by dvesh3** [comment]
Fixed by #7688
