### ISSUE TITLE
CSV import - Appending relations with the CSV import functionality does not work.

### ISSUE THREAD

**Issue by jacobsyentl** [pimcore/pimcore#6715]
# Bug Report
This bug report concerns the import of an asset relation with the CSV import functionality.

### Expected behavior
When "Do not overwrite" is checked on the many-to-many attribute during the mapping, then assets/objects should be appended to already linked elements. Instead, nothing happens.

### Actual behavior
If "do not overwrite" is checked, then nothing happens on the attribute, this seems not logical since this also could be achieved if we do not map the attribute on a CSV column.

### Steps to reproduce
- Open an object and add an asset to a many-to-many attribute.
![image](https://user-images.githubusercontent.com/9139261/86225110-14f98800-bb8a-11ea-8e00-f6d2798624a6.png)

- Make a CSV that should append a file to the same attribute.
![image](https://user-images.githubusercontent.com/9139261/86225211-378ba100-bb8a-11ea-8df3-756f70db72ca.png)

- Set the "do not overwrite" setting during the CSV mapping on the many-to-many attribute.
![image](https://user-images.githubusercontent.com/9139261/86225290-512ce880-bb8a-11ea-8a13-8de3f1403c81.png)

- Try to import
- The original file will still be in the relational attribute, but no new relation will be added.

### Closing thoughts
Maybe this is not the concern of the "Do not overwrite" checkbox, but it should be possible to just append a new relation, no? Otherwise, a user should always take care of full imports instead of incremental ones.

**Comment by brusch** [comment]
Obsolete. Pimcore 6 Community Edition is EOL, CSV import was removed in Pimcore 10.
