### ISSUE TITLE
DataObjectImporter uses original block item when importing

### ISSUE THREAD

**Issue by elements-team** [pimcore/pimcore#6722]
# Bug Report
When using the [`DataObjectImporter`](https://github.com/pimcore/pimcore/blob/master/lib/Translation/ImporterService/Importer/DataObjectImporter.php) to translate a block from one language to another, it may happen that the _original_ block item is used, without cloning it. Ultimately, this will override the original data.

### Expected behavior
The original data should not be overridden.

### Steps to reproduce
1. Create a block in a localized field.
2. Add multiple block items to the block (e.g., a text field) for your **source** language.
3. Do not add the fields to the block for your **target** language.
4. Translate from one language to another. 

You will now find that the original data was overridden, due to [this line](https://github.com/pimcore/pimcore/blob/master/lib/Translation/ImporterService/Importer/DataObjectImporter.php#L73).

### Suggested solution
You should rather use 
```php
$blockItemData = !empty($blockData) ? clone $blockItem[$fieldname] : clone $originalBlockItemData;
```
This way the value in `$blockItem[$fieldname]` will be cloned as well, leaving the original value untouched.

**Comment by weisswurstkanone** [comment]
Can you create a PR please ?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
