### ISSUE TITLE
[DataObject] Block in Fieldcollection not working anymore

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#6726]
only in master-branch

- Error when creating new data object with block in field collection: `Message: params contains owner but no fieldname`
- Error when opening existing data object with block in field collection: `owner missing`

Sample: 
News objects in demo, e.g ID 773 in demo

**Comment by weisswurstkanone** [comment]
regression of https://github.com/pimcore/pimcore/pull/6328
