### ISSUE TITLE
[CustomLayouts] Allow edit required fields in Custom layout definition

### ISSUE THREAD

**Issue by MyZik** [pimcore/pimcore#6728]
Hi there.

I did the custom layouts for `Car` DataObject variants with this tutorial:
https://pimcore.com/docs/6.x/Development_Documentation/Best_Practice/Showing_Custom_Layouts_based_on_Object_Data.html

In my layout for parent object I don't have "Sale information":
![Bildschirmfoto 2020-07-02 um 12 41 42](https://user-images.githubusercontent.com/12817320/86349505-822c1c80-bc61-11ea-8ea3-aca253f5e4dc.png)

But I would like to set some required fields in "Sale information" data only for `Car` variant custom layout. If I do this and try to add new parent object `Car`, I cannot save the DataObject because the required fields in "Sale information" panel are empty, but we cannot see them...

And we cannot set required fields in the custom layout, because checkbox is inactive.

How can we do this? Is it a bug?

Thanks in advance.

**Comment by MyZik** [comment]
I tried to it so:

```php
private function doModifyCustomLayouts($data, $object, $customLayoutToSelect = null, $layoutsToRemove = [])
    {
        if ($customLayoutToSelect !== null) {
            $data['currentLayoutId'] = $customLayoutToSelect;
            $customLayout            = CustomLayout::getById($customLayoutToSelect);
            $data['layout']          = $customLayout->getLayoutDefinitions();
            Service::enrichLayoutDefinition($data['layout'], $object);
        }

       ...

        if ($customLayoutToSelect === 'variant') {
            $marketingName = $customLayout->getFieldDefinition('marketingName');
            $marketingName->setMandatory(true);

            $marketingDescription = $customLayout->getFieldDefinition('marketingDescription');
            $marketingDescription->setMandatory(true);

            $price = $customLayout->getFieldDefinition('priceInEUR');
            $price->setMandatory(true);

            $customLayout->save();
        }

        return $data;
    }
```

And these fields are required with red asterisk symbol (*). But also I can save the empty fields...

**Comment by fashxp** [comment]
Not sure if I get your point. 
But mandatory fields are mandatory for all objects of a class definition. It is not possible to define mandatory fields on custom layout level, so it doesn't seem to be a bug.

For support please use our forums or gitter chat.

**Comment by betterapp** [comment]
I think there should be possible to set mandatory on custom layout level separately.
BTW: where in Ext.JS the mandatory field in custom layout is set to disabled/readonly ?

**Comment by betterapp** [comment]
bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/data.js
