### ISSUE TITLE
[DataObjects][Custom Layouts] Setting fields to unique on custom layout level doesn't make sense

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#6729]
or do I miss something? 

![image](https://user-images.githubusercontent.com/8792145/86366783-7cdbcb80-bc7b-11ea-95ff-b0bf0c20ed27.png)

**Comment by weisswurstkanone** [comment]
should be grayed out just like the mandatory checkbox

**Comment by cancan101** [comment]
@weisswurstkanone , why is `mandatory` grayed out for custom views? That actually causes issues if the field is marked marked mandatory on the class definition _after_ the custom view is created. At that point, the custom view does not reflect that the field is mandatory and the the UI does not allow checking the box.
