### ISSUE TITLE
Content of editables can't be saved in Snippets

### ISSUE THREAD

**Issue by Brecherchef** [pimcore/pimcore#6730]
# Bug Report

### Expected behavior
I should be able to Save Editable-Input fields. I've used this method before in the exact same way and never had an Issue

### Actual behavior
I click on "Save and publish" in my Snippet, pimcore just says successfully saved but as soon as I reload the page all of my content will be gone. It won't show up in the frontend either. 

### Steps to reproduce
First I've created a Snippet-Controller to implement my Footer on every page: 
```php
<?php

namespace AppBundle\Controller;

class SnippetController extends BaseController
{
    public function footerAction()
    {
    
    }
}
```

I implemented it into my base-template like this: 
```twig
{% set sitepath = currentSite.getKey() %}
{{ pimcore_inc('/'~sitepath~'/Snippets/Footer') }}
```

And created the actual template-file like this: 
```twig
<footer>
    <div class="container-fluid dark-gray-bg meta-menu">
        <div class="container">
            <div class="row ">
                <div class="{% if editmode %}col-3{% else %}col-md-6 col-xl-3{% endif %}">
                    <h3 class="mt-0">{{ pimcore_input("footer_contact_headline") }}</h3>
                    {% if editmode %}
                        {{ pimcore_wysiwyg("footer_contact_content") }}
                        {{ pimcore_link("footer_contact_button", {"class": "btn"}) }}
                    {% else %}
                        {{ pimcore_wysiwyg("footer_contact_content")|raw }}
                        <a href="{{ pimcore_link("footer_contact_button").getHref() }}" {{ pimcore_link("footer_contact_button").getTitle() }}>{{ pimcore_link("footer_contact_button").getText() }}</a>
                    {% endif %}
                </div>
                <div class="{% if editmode %}col-3{% else %}col-md-6 col-xl-3{% endif %}">
                    {% if editmode %}
                        {{ pimcore_wysiwyg("footer_center_content") }}
                    {% else %}
                        {{ pimcore_wysiwyg("footer_center_content")|raw }}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</footer>
```

Now I've added the footer-document in my Snippets-Folder and set the controller to be the Snippet-Controller with my footer-template in the backend. Everything works fine and I can edit the editables, save them and won't get any errors, the footer itself is visible but no editable content will be shown. I've used thie method multiple times so far and never had any problems with it. Somehow this time It just won't work.

Pimcore version is v6.6.1

**Comment by dvesh3** [comment]
Unable to reproduce on latest version 6.6.7

**Comment by brusch** [comment]
Closed due to inactivity.
