### ISSUE TITLE
Extend Grid config dialog (object)

### ISSUE THREAD

**Issue by ckogler-elements** [pimcore/pimcore#6739]
Extend the "pimcore.object.helpers.gridConfigDialog" dialog so we can use it in different locations.
- add an option to pass a context eg. ["source" => "myBundle", "configName" => $myConfig] (should be passed to \Pimcore\Model\DataObject\Service::getCsvDataForObject() )
- add the availability to open the config dialog with "preview" but without passing an objectId (object selector in the window)
- add an option so that the preview uses the \Pimcore\Model\DataObject\Service::getCsvDataForObject() method to be able to display the exported data

**Comment by ckogler-elements** [comment]
In addition it should not be possible to delete all field definitions because you can not add any fielddefition if none is available (missing drop zone...)

**Comment by weisswurstkanone** [comment]
Part 1:  added an additional param which will be passed in the $context array passed to getCsvDataForObject

Example:

```
        var dialog = new pimcore.object.helpers.gridConfigDialog(columnConfig, function (data, settings, save, context) {
                this.gridLanguage = data.language;
                this.gridPageSize = data.pageSize;
                this.createGrid(true, data.columns, settings, save, context);
            }.bind(this),
            function () {
                Ext.Ajax.request({
                    url: Routing.generate('pimcore_admin_dataobject_dataobjecthelper_gridgetcolumnconfig'),
                    params: {
                        id: this.classId,
                        objectId: objectId,
                        gridtype: "grid",
                        searchType: this.searchType
                    },
                    success: function (response) {
                        response = Ext.decode(response.responseText);
                        if (response) {
                            fields = response.availableFields;
                            this.createGrid(false, fields, response.settings, false);
                            if (typeof this.saveColumnConfigButton !== "undefined") {
                                this.saveColumnConfigButton.hide();
                            }
                        } else {
                            pimcore.helpers.showNotification(t("error"), t("error_resetting_config"),
                                "error", t(rdata.message));
                        }
                    }.bind(this),
                    failure: function () {
                        pimcore.helpers.showNotification(t("error"), t("error_resetting_config"), "error");
                    }
                });
            }.bind(this),
            true,
            this.settings,
            {
                allowPreview: true,
                classId: this.classId,
                objectId: objectId
            },
            null,
            {
                **source : "value1",
                key2 : "value2"**
            }
        )

```

**Comment by weisswurstkanone** [comment]
In order to getCsvDataForObject for preview, use the following config

![image](https://user-images.githubusercontent.com/6142086/89512867-1b57d100-d7d4-11ea-9bf0-ddd0f6fd2c72.png)

**Comment by weisswurstkanone** [comment]
You can open the dialog without objectId. For the preview item selector button to work add the following config.

![image](https://user-images.githubusercontent.com/6142086/89533293-7f3dc200-d7f3-11ea-8b89-30a62496895b.png)

![image](https://user-images.githubusercontent.com/6142086/89533354-954b8280-d7f3-11ea-98c7-4a9d22745a24.png)

**Comment by weisswurstkanone** [comment]
@ckogler-elements , does this fit your needs ?

**Comment by ckogler-elements** [comment]
Yes, looks great :-).
Going to test it and create a new ticket if something wouldn't work (dont expect this.).

thx.
