### ISSUE TITLE
default asset upload is broken

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#674]
try to upload an asset by default won't work anymore.

![bildschirmfoto 2016-06-17 um 15 08 23](https://cloud.githubusercontent.com/assets/700119/16151471/7ac91a92-349d-11e6-8d51-c66ab030d9e0.png)

![bildschirmfoto 2016-06-17 um 15 08 29](https://cloud.githubusercontent.com/assets/700119/16151470/7ab219fa-349d-11e6-9a7c-a284cc5e7a0d.png)

**Comment by fashxp** [comment]
fixed in build 3857
