### ISSUE TITLE
[DAM] Thumbnails for PDF, PPT, etc. not showing in Admin UI

### ISSUE THREAD

**Issue by rt-pim-dam** [pimcore/pimcore#6746]
# Bug: Thumbnails for PDF, PPT, etc. not showing in Admin UI

If you are logged-in to Pimcore and have uploaded a PDF, PPT or other office file formats, you do not get a thumbnail displayed. The behaviour has been discussed on the forum in several threads and one user has come up with a solution that works for me and most users, but it is a hack inside Documents.php (add the following after line 125) so it is part of all updates. 

This piece of code does the trick:

```php
       // Get thumbnail
        if ($asset instanceof Asset\Document) {
            // Fix preview document
            // @see Pimcore\Model\Asset\Document getImageThumbnail method
            try {
                $asset->getCustomSetting(‘document_page_count’);
            } catch (\Exception $e) {
                $asset->processPageCount();
            }
            $thumbnail = $asset->getImageThumbnail('system-download');
        } 
```

**Comment by dvesh3** [comment]
This is intended behavior to avoid issues with processing huge documents. please see https://github.com/pimcore/pimcore/pull/6001#issuecomment-596410603

**Comment by BlackbitNeueMedien** [comment]
@dvesh3 Is this really intentional? It doesn't even work with https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf - neither gets the thumbnail shown when hovering the file in the asset tree, nor do I see the PDF being rendered when I open it (tested on https://demo.pimcore.fun)

**Comment by dvesh3** [comment]
@BlackbitNeueMedien yes, processing done in the background with maintenance job. It is not based on size of document rather just a default behavior https://github.com/pimcore/pimcore/blob/606a0ae150a56c829f924575f1676c0502387d17/models/Asset/Document.php#L118-L119
but PDF rendering is not asynchronous, so it should work when you open it.

**Comment by dvesh3** [comment]
@brusch what do you think about considering document size for delayed processing?

As it was stated in initial problem also:
"It seems the error only occures on bigger Excel Files". https://github.com/pimcore/pimcore/issues/3974#issue-412813229

**Comment by BlackbitNeueMedien** [comment]
@dvesh3 The maintenance job tries to create the thumbnail (for https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf) but fails with the error:
```
09:44:58 ERROR [pimcore] Exception: Unable to get page-count of /var/www/html/var/tmp/imagick-tmp-5f34ef7a9ab39.pdf in /var/www/html/vendor/pimcore/pimcore/lib/Document/Adapter/Ghostscript.php:148
Stack trace:
#0 /var/www/html/vendor/pimcore/pimcore/models/Asset/Document.php(86): Pimcore\Document\Adapter\Ghostscript->getPageCount()
#1 /var/www/html/vendor/pimcore/pimcore/lib/Maintenance/Tasks/AssetDocumentConversionTask.php(55): Pimcore\Model\Asset\Document->processPageCount()
#2 /var/www/html/vendor/pimcore/pimcore/lib/Maintenance/Executor.php(88): Pimcore\Maintenance\Tasks\AssetDocumentConversionTask->execute()
#3 /var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/Command/MaintenanceCommand.php(93): Pimcore\Maintenance\Executor->executeMaintenance(Array, Array, false)
#4 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): Pimcore\Bundle\CoreBundle\Command\MaintenanceCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1018): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\MaintenanceCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(271): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\MaintenanceCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(147): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/bin/console(26): Symfony\Component\Console\Application->run()
#11 {main}
```

**Comment by dvesh3** [comment]
@BlackbitNeueMedien jup, please see https://github.com/pimcore/pimcore/issues/6911

**Comment by brusch** [comment]
@dvesh3 we thought already about making it dependent on the document size, ... but e.g. for huge Excel files this is quite problematic ... see also #3974 
The excel file itself is just a few kB, but results in hundreds of pages 😕
