### ISSUE TITLE
[Data objects] Objects of wrong folder displayed

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#6751]
Steps to reproduce:
In Pimcore backend:
1. Create folder `_0` under `/`
2. Create folder `00` under `/`
3. Create object `A` in `/_0`
4. Create object `B` in `/00`
5. Open folder `_0` --> you will see both objects in the grid although actually only `A` is in folder `/_0` while `B` is not.

**Comment by brusch** [comment]
Done by #6809
