### ISSUE TITLE
Deprecate Auto View Rendering with 6.7 and remove with 7.0

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#6760]
Since that feature was introduced for BC reasons with Zend, it is time to finally remove it and stick more to Symfony standard behaviour. WDYT?

**Comment by fashxp** [comment]
does it hurt?

**Comment by dpfaffenbauer** [comment]
Yes, developers learn things that are not necessary and they might fall over this in the future sometime. I would keep things as close to Symfony best-practice as possible, and auto-view-rendering is not part of it.
