### ISSUE TITLE
Version stackTrace disable / clean-up

### ISSUE THREAD

**Issue by t-zilla** [pimcore/pimcore#6764]
# Feature Request

## Problem
Stack trace is included to every version `vendor/pimcore/pimcore/models/Version.php:180` which is a problem if several previous versions need to be kept but they take up too much space. In many use cases utility of stackTrace column is very minor, especially on old versions.

## Feature description
A way to disable or regularly clean up stackTrace in versions.

## Possible solutions
1. Add a configuration/setting for disabling adding stackTrace to every version.
2. Add a maintenance task to delete stackTraces in versions older than, say, 7 days.

**Comment by brusch** [comment]
I'd go for both solutions. 
- Config to disable the feature (default stays as it is now) 
- Maintenance task that sets the stack trace column to `NULL` if version is older than 7 days
