### ISSUE TITLE
[Permissions] Inconsistent permissions implementation

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#6771]
Permissions implementation for search and tree listing is not consistent. 

![image](https://user-images.githubusercontent.com/8792145/87313558-54c55580-c522-11ea-825e-4358373de325.png)

- navigation in tree shows alfa romeo cars
- search doesn't find any alfa romeo cars

additional aspect 
- bad performance impact of permission implementation in tree navigation (see #6383) 
- maybe also #1634
- implementation of CMF would also not find alfa romeo cars, see https://github.com/pimcore/customer-data-framework/blob/master/src/Listing/Filter/Permission.php#L11 - but is much faster

**Comment by ckogler-elements** [comment]
I had just a similar issue. 
In my use case the user had workspace permissions and a lot of items matched where the user did not have the list permission. Because the first matches were empty (no permissions to the objects) the "real matches" didn't show up. 
Therefore the workspaces paths should be added to the DB query to get the right data. 

I just solved it by creating an event listener but it would be great if the core also handles workspaces...

`
class SearchBackend
{

    public function searchAdmin(\Symfony\Component\EventDispatcher\GenericEvent $event){

        $searcherList = $event->getArgument('list');
        $context =$event->getArgument('context');
        if($context['type'] == 'object'){
            $db = \Pimcore\Db::get();
            $user = \Pimcore\Tool\Authentication::authenticateSession();
            if(!$user->isAdmin()){
                $validPaths = [];
                foreach($user->getWorkspacesObject() as $ws){
                    if($ws->getList()){
                        $validPaths[] = $ws->getCpath();
                    }
                }

                foreach($user->getRoles() as $rId){
                    $role = Role::getById($rId);
                    /**
                     * @var $ws \Pimcore\Model\User\Workspace\DataObject
                     */
                    foreach($role->getWorkspacesObject() as $ws){
                        if($ws->getList()){
                            $validPaths[] = $ws->getCpath();
                        }
                    }
                }
                $validPaths = array_filter(array_unique($validPaths));

                if($validPaths){
                    $queryParts = [];
                    foreach($validPaths as $path){
                        $queryParts[] = ' ' . $db->quoteIdentifier('fullpath') . ' LIKE '. $db->quote($path."%");
                    }
                    $q = implode(' OR ',$queryParts);
                    $searcherList->setCondition($searcherList->getCondition().' AND (`type` = "object" AND (' .$q.'))'  );
                }
            }
        }

    }
}
`

**Comment by fashxp** [comment]
@ckogler-elements do you still know what your exact problem was? because I cannot really follow you :-)

thx.

**Comment by fashxp** [comment]
first problem cannot be reproduced anymore, second problem is now a separate issue #11822
