### ISSUE TITLE
Grid Options, cannot add any after deleting all options

### ISSUE THREAD

**Issue by michgero** [pimcore/pimcore#6772]
Delete all options, now you can't add any options (probably because grid height = 0)

![](https://media3.giphy.com/media/dt06BMaNRxFs11kCVM/giphy.gif)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Comment by fashxp** [comment]
Item still can be added with double click.
