### ISSUE TITLE
[DataObjects] Fieldcollection - use localized fields in Block field

### ISSUE THREAD

**Issue by anyMOTION-GRAPHICS** [pimcore/pimcore#6779]
# Bug Report
In the current Version it is not possible to save Objects witch have an Field Collection with Localized Fields in Block Component 

Tested on https://demo.pimcore.fun
Pimcore Platform (6.6.x-dev|8d299422584686dc18ca9bfc69296800d131be92)

## Expected behavior
Save Object

## Actual behavior
Call to undefined method getTestblock in class Pimcore\Model\DataObject\DummyBlockFC
Server threw exception - could not perform action. Please reload the admin interface and try again.

Timestamp: Tue Jul 14 2020 13:02:26 GMT+0200 (Mitteleuropäische Sommerzeit)
Status: 500 | Internal Server Error
URL: /admin/object/save?task=publish
Method: PUT
Message: Call to undefined method getTestblock in class Pimcore\Model\DataObject\DummyBlockFC

## Steps to reproduce
- create Class "DummyBlockFC" and import [class_DummyBlockFC_export.json](
https://anymotiongraphics-my.sharepoint.com/:u:/g/personal/s_mueller_anymotion_de/EZheoj3DQIhBllO0mC2LBFMBYdij-vuQBxP3moaeh8Z4Bw?e=LFIU1Y)
- create FieldCollection "LocalizedBlockFC" and import [fieldcollection_LocalizedBlockFC_export.json](https://anymotiongraphics-my.sharepoint.com/:u:/g/personal/s_mueller_anymotion_de/EdM1apcCg85DntF9jb90rtYBlBj6V4UZ7Jx-LD_FcASz7g?e=7gE6eJ)
- create Object of Class "DummyBlockFC"
- add field collection
- fill required fields
- try to save object

**Comment by weisswurstkanone** [comment]
This kind of nesting level is currently not supported.
See https://github.com/pimcore/pimcore/issues/6540 and related issues for more info.
