### ISSUE TITLE
Numeric Document Editable does not output on preview but on Web2Print PDF

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#678]
# Bug Report

I created a new numeric document editable with the following code:

```php
<?= $this->numeric("amount", [
								"width" => 300,
								"minValue" => 0,
								"decimalPrecision" => 2
							]); ?>
```

### Expected behavior 

Show form field in editmode, show number entered in preview mode and in document rendering (in this case in PDF of Web2Print)

### Actual behavior  

Does not show up in the preview mode (nothing displayed) but is rendered in PDF. If I use this code:

```php
echo $this->numeric("amount")->number;
```

It'll show in preview mode in this case but shows twice in PDF.

I think the output shoud be the same in preview and in generated PDF as it is with other editables (input, wysiwyg).

**Comment by brusch** [comment]
Thanks!
Fixed in build 3862

**Comment by Cruiser13** [comment]
Thanks!
