### ISSUE TITLE
Sorting data objects on key in search grid gives an error (column doesn't exist)

### ISSUE THREAD

**Issue by MartijnVanDoornik** [pimcore/pimcore#6782]
# Bug Report

### Expected behaviour
Sorting on key in search grid

### Actual behaviour
Error because the "key" column doesn't exist on the "search_backend_data" table

### Steps to reproduce
1. Enable "Key (Search)" in the "General Settings" of a data object class.
2. Open that class in a search grid and try to sort on "Key". For example by placing a "Many to one" field on a data object class and clicking the magnifier icon to add an object.

(See attached GIF for reproduction on the demo environment)

![key-in-search-grid](https://user-images.githubusercontent.com/58683336/87432394-37f35580-c5e8-11ea-89a6-3aa75f72a867.gif)

**Comment by fracsi** [comment]
This error is also present in 6.8.10.
