### ISSUE TITLE
XLIFF Import fails when target tag is missing

### ISSUE THREAD

**Issue by msphn** [pimcore/pimcore#6785]
# When exporting not all values get target tags in XML
No target tag:
<img width="801" alt="missing_target" src="https://user-images.githubusercontent.com/579227/87437520-b94de680-c5ee-11ea-80d0-832d7c7f7ea6.png">
Crashes here:
<img width="1172" alt="crash_without_target" src="https://user-images.githubusercontent.com/579227/87437596-d387c480-c5ee-11ea-96f5-7530b3fc1b96.png">
Can be fixed with a simple check for an existing target tag, I added isset check to see if it exists or not.

So should it be fixed during import or export?

**Comment by weisswurstkanone** [comment]
At least on the import side but better on both sides.
Can you create a PR please ?
