### ISSUE TITLE
Login and reset password not working - CSRF changes token value.

### ISSUE THREAD

**Issue by dgheorgheavira** [pimcore/pimcore#6788]
Hello. 

We are working with pimcore 6.3.6 and php 7.2. 

For a few days we are receiving this error: "Detected CSRF Attack! Do not do evil things with pimcore ... ;-)" when we try to login to admin or try to recover password. We have not made any important modifications to either the infrastructure or pimcore itself.

So far it seems that for some reason the csrf token changes between the get of the login page and the post for login. We were not able to pinpoint the issue or reproduce it on any other server. 

Any ideeas on why this might happen?
Thank you

**Comment by brusch** [comment]
Probably there's a problem with your session storage. 
But this is not the right place for getting support, please use: 
https://talk.pimcore.org/
or 
https://gitter.im/pimcore/pimcore

Thanks! 😊

**Comment by dpfaffenbauer** [comment]
yeah no @brusch, I don't think so, I've noticed the same issue with lots of my installations on different systems.

**Comment by brusch** [comment]
@dpfaffenbauer then we need more details ... for me it's not reproducible.

**Comment by dpfaffenbauer** [comment]
It is not reproducible for me neither, thats why I never created an issue. What I think might be an issue is when you use different installations on the same domain. like when you use localhost for DEV or some sort of staging domain. But I still don't know when that happens exactly, it just happens from time to time. (also on one domain with no other installation)

**Comment by dpfaffenbauer** [comment]
same domain is meant like: install1.pim-stage.com, install2.pim-stage.com

**Comment by smaier** [comment]
we had that exact issue on some systems after activating
session.cookie_httponly=On
session.cookie_secure=On
in php.ini but calling the dev-systems via http (for obvious reasons)
so not a real pimcore issue - but might be your issue, too

**Comment by dgheorgheavira** [comment]
so it seems like sometimes it manages to go through the initial login procedure ... but after login .. within a few seconds i get this error: You don't have sufficient permissions to open the element or perform the desired action. making all xhr calls to fail.

\\

**Comment by mochigroup** [comment]
For us we moved to a new server, in the process changed from /var/lib/session_monetsim to /var/lib/session/monetsim to keep it consistent, turns out there is a problem with the session/monetsim, once it was changed back to session_monetsim no more csrf error on admin login, strange but true!
