### ISSUE TITLE
Creating new asset doesn't set user Owner and userModification (null value)

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#679]
In the recent Pimcore version, in the documentation there is no more the necessity to do:
$object->setUserOwner(1);
$object->setUserModification(1);
Like it was in previous Pimcore version (before it was clearly on the page for class object if i remember).
(ex: https://www.pimcore.org/wiki/display/PIMCORE4/Data+Objects)

Creating an object (by PHP code/API) set it to 0 automatically (system ID user) so great.
But for **creation new Asset** nothing is set (null value)... maybe better if 0 is set because it could make some side effects later if an object has no userOwner/userModification ?

I didn't test with Document.

**Comment by brusch** [comment]
Creating a new object does also not set `0` automatically. 
Tested with the following code: 
```php
        $element = new Object\News();
        $element->setParentId(1);
        $element->setKey("test-" . uniqid());
        $element->save();
```

checked in the database.
