### ISSUE TITLE
[Asset thumbnails] Inverted colors for CMYK images

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#6790]
We get inverted colors in the thumbnails for some images, e.g. https://www.dropbox.com/s/rhdzn76wtosu5tj/10555J__01.tif.zip?dl=0 (had to zip it, otherwise Dropbox had an error - for testing please unzip it)

Obviously in https://github.com/pimcore/pimcore/blob/b17b05a84a3946fbc1dc5eb88b0fc33682de2690/lib/Image/Adapter/Imagick.php#L319-L331 the comment https://www.php.net/manual/en/imagick.setimagecolorspace.php#107716 has been applied - but with the addition of setting the colorspace to sRGB:
https://github.com/pimcore/pimcore/blob/b17b05a84a3946fbc1dc5eb88b0fc33682de2690/lib/Image/Adapter/Imagick.php#L330

With above image I get this result in the default asset preview in Pimcore backend
![get-image-thumbnail](https://user-images.githubusercontent.com/8749138/87510852-9bc36000-c674-11ea-8ec9-2be0a3701c99.jpg)

When I remove https://github.com/pimcore/pimcore/blob/b17b05a84a3946fbc1dc5eb88b0fc33682de2690/lib/Image/Adapter/Imagick.php#L330
then it looks correctly:
![get-image-thumbnail](https://user-images.githubusercontent.com/8749138/87510911-beee0f80-c674-11ea-80b3-f9d146a10788.jpg)

On https://demo.pimcore.fun it nevertheless works also with this line. And also without. 
Do you know what this line is good for - or where thumbnail generation does not work properly without this line?

ImageMagick is version 6.9.11-23 Q16 x86_64 2020-07-14, Imagick 3.4.4 - so this is nearly the same as on https://demo.pimcore.fun (ImageMagick 6.9.10-23 Q16 x86_64 20190101, Imagick 3.4.3)
We have no additional color profiles set in system settings.

**Comment by brusch** [comment]
This seems to be a known ImageMagick bug, see also: https://talk.pimcore.org/t/cmyk-to-rgb-displaying-as-negative/908/17?u=brusch
