### ISSUE TITLE
Notice: Undefined index: ga:uniquePageviews

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#6796]
Request URL: /admin/reports/analytics/summary?_dc=1594892448248&type=&id=&path=&page=1&start=0&limit=25
Request Method: GET

Message: Notice: Undefined index: ga:uniquePageviews
Trace: 
in /home/pimcore-5/demo-basic/dev/pimcore/pimcore/bundles/AdminBundle/Controller/Reports/AnalyticsController.php:267
#0 /home/pimcore-5/demo-basic/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(158): Pimcore\Bundle\AdminBundle\Controller\Reports\AnalyticsController->summaryAction()
#1 /home/pimcore-5/demo-basic/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#2 /home/pimcore-5/demo-basic/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle()
#3 /home/pimcore-5/demo-basic/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle()
#4 {main}

**Comment by brusch** [comment]
Fixed by #6797
