### ISSUE TITLE
Wrong High-Res Images when using specific Image Area

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#6798]
- Reproducible on latest demo
- Maybe related: https://github.com/pimcore/pimcore/pull/5443

## Image Configuration
![image](https://user-images.githubusercontent.com/700119/87666262-96474200-c768-11ea-976a-3e0aa910cc45.png)
![image](https://user-images.githubusercontent.com/700119/87666269-9a735f80-c768-11ea-829d-58c8d436d560.png)

## Area 
Using a default `image` area with a specific area
![image](https://user-images.githubusercontent.com/700119/87666212-7d3e9100-c768-11ea-96af-4ac75a448869.png)

## Frontend
Checkout the source code. Some of those 2x images renderings are wrong. (`...2x.webp`, `...2x.jpg`):

![image](https://user-images.githubusercontent.com/700119/87666398-d8708380-c768-11ea-8093-376cbe072b85.png)

**Comment by brusch** [comment]
Fixed by #7768
