### ISSUE TITLE
DataObject Id can be set with setValues()

### ISSUE THREAD

**Issue by daves-weblab** [pimcore/pimcore#6801]
# Bug Report
When using e.g MyDataObject::create([...]) or $myDataObject->setValues([...]) the actual data object id can be set, if the given array provides a ["id" => xxx]. This can lead to inconsistent data in the database, since the new object can override an old object. The data of the old object will not be removed from query and store tables. Thus it can be found with queries but leads to the wrong data object when loaded from the database.

### Expected behavior
The id offset should be removed from the data array when setting values.

### Actual behavior
The id offset is not removed.

### Steps to reproduce
Create two classes (MyDataObject1, MyDataObject2). Create an object from type MyDataObject1. Let's say it gets the id 2. Then create an object in code from type MyDataObject2 with ```MyDataObject2::create(["id" => 2, "title" => "data object 2"])```. When querying the MyDataObject1\Listing the data object with id 2 is found but is returend as MyDataObject2. 

### Common scenarios
For example when using a logger that stores an id per entry and provides an api to fetch the data as array. When creating an object from that array conveniently with `MyDataObject::create($loggerEntryData)` while `$loggerEntryData` provides the id from the log entry with ["id" => <loggerEntryId>] such a scenario can occur rather easy.

**Comment by brusch** [comment]
I'd not silently remove attributes, I'd rather throw an Exception in that case.

**Comment by brusch** [comment]
Unfortunately this sounds easier than it is ... `setValues()` is used across all entities, and there are a couple of entities where it is intended to set the `id` property as well, e.g. data object class definitions. 
So I'd just filter them in `::create()` rather than doing that in `setValues()`.
