### ISSUE TITLE
Object relation field for lazy loading field lost between two request.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#681]
If we create a new object (by API code):
$myObject = new Pimcore\Model\Object\MyClass();

Add a relation object:
$myObject->setMyRelation($myOtherObject);

And save it in session (**without calling $myObject->save()**, we just put in the session the Pimcore object), on the next client HTTP request, if we get the object from the session, the relation is empty. (for record, we use Zend Session Namespace).
It is only empty when "lazy loading" is checked for the relation field (if there is no lazy loading, relation is keeped).

I think there are some cleaning in the Pimcore startup wich clean lazy loading relation in memory.
But from the developper view it is strange because the object saved in session, is not the same at the next request... and lost the relation.

Just to explain with a real case so it is more comprehensible: our use case, is preparing a shopping cart using a Pimcore object, but not saving it in Pimcore - ie we don't call -> save() (we put the object in session to be able to retrive it from request to another request). So we can manipulate it and retrieve it by session (we just do the save of the object when order is further). We add products to it (with lazy loading relation field). Products linked to the Cart are lost on the next customer HTTP request. It happen only if "lazy loading" is checked.

I hope i managed to explain it. If you need further information i will be happy to provide it.
Thanks.

**Comment by brusch** [comment]
If lazy loading is ticked the data is flushed in `__sleep()`. On `__wakeUp()` the data is loaded from the database again. This is just the way how lazy loading works and should work.
