### ISSUE TITLE
[DataObjects][DataTypes] Clarify and eventually unify enrichFieldDefinition vs. enrichLayoutDefinition

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#6814]
for example see 
https://github.com/pimcore/pimcore/blob/45ef287afc65e199353e976c91b14b059c5c1959/models/DataObject/ClassDefinition/Data/Select.php#L412 vs https://github.com/pimcore/pimcore/blob/45ef287afc65e199353e976c91b14b059c5c1959/models/DataObject/ClassDefinition/Data/Select.php#L436

- would it not be enough to apply options from options provider in just one of these methods? 
- should the calculation of options not be the same - one time inheritance is explicitly activated, one time not...

**Comment by brusch** [comment]
See also: https://github.com/pimcore/frontend-permission-toolkit/blob/2d209ea43fc5ea02817cced8c048b136ddb63169/src/CoreExtensions/ClassDefinitions/DynamicPermissionResource.php#L351

**Comment by brusch** [comment]
Please also consider: #8827

**Comment by brusch** [comment]
#9439 introduced already interfaces for those 2 methods. 

Todos: 
- Describe methods on the interfaces: 
https://github.com/pimcore/pimcore/blob/10.x/models/DataObject/ClassDefinition/Data/FieldDefinitionEnrichmentInterface.php#L27
https://github.com/pimcore/pimcore/blob/10.x/models/DataObject/ClassDefinition/Data/LayoutDefinitionEnrichmentInterface.php#L33
- Check `Select` & `Multiselect` data-types, see issue description above.
