### ISSUE TITLE
MP4 asset opening times in Admin portal

### ISSUE THREAD

**Issue by jeremygnoonan** [pimcore/pimcore#6820]
# Bug Report

### Expected behavior
Open MP4 assets in Admin console in a time comparable to other assets

### Actual behavior

MP4 assets attempt to load `SphericalMetadata` each time the asset is opened. We have 5GB+ video assets stored in Pimcore. This function is very slow on the large files as it traverses the entire file looking for tags.

### Steps to reproduce

1. Upload a large MP4 asset
2. Open asset in admin
3. Wait :)

### Code example
```php
// Inside of pimcore/bundles/AdminBundle/Controller/Admin/AssetController.php here is the offending line in the function
// getDataByIdAction 
$metaData = $asset->getSphericalMetaData(); //this function takes A LONG TIME to execute on large files 
```

# Feature Request

## Feature description
My suggested work around would be to have this function executed when an Asset is created / updated and stored as a metadata property of the asset. Having this function called every time the asset it opened seems like unnecessary overhead. I would be interested in learning how to create a pull-request for this feature, but I don't think I understand the details of VR enough to ensure I am taking all things into consideration. 

It looks like the main item of concern is the metadata `ProjectionType` with a value of `equirectangluar`. 

Could it be just as easy as looking for this on upload then setting it as a property on the Asset?

**Comment by brusch** [comment]
This should be done by `\Pimcore\Messenger\Handler\AssetUpdateTasksHandler::processVideo()` and saved into the custom settings.

**Comment by dvesh3** [comment]
It might related to #14998 that the processing can be done in the background.
