### ISSUE TITLE
[Element] POST_DELETE_FAILURE could be triggered multiple times

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#6821]
In case you're deleting a page and that fails, let's say here: 
https://github.com/pimcore/pimcore/blob/2662d44a8828ad8fc7c8d878020b115f8ba61d69/models/Document.php#L823

Then the `DocumentEvents::POST_DELETE_FAILURE` event get's triggert 3 times here: 
https://github.com/pimcore/pimcore/blob/2662d44a8828ad8fc7c8d878020b115f8ba61d69/models/Document.php#L840
https://github.com/pimcore/pimcore/blob/a9f23dd2c7913a5d573e3dd101e3ae2da7751f63/models/Document/PageSnippet.php#L202
https://github.com/pimcore/pimcore/blob/e62ed40c25b802ae56c571ef70398088a8046e17/models/Document/Page.php#L100

Maybe we can use the `$isNested` argument to avoid this behavior.

**Comment by brusch** [comment]
Related to: #6819
Fix should go on the master, due to the dependency to #6819

**Comment by jdreesen** [comment]
This is also the case for `DataObjects` and `DataObjectEvents::POST_DELETE_FAILURE`:

https://github.com/pimcore/pimcore/blob/fc806fee0a5b13f8f7566153474f06f604c23ed2/models/DataObject/AbstractObject.php#L566

https://github.com/pimcore/pimcore/blob/fc806fee0a5b13f8f7566153474f06f604c23ed2/models/DataObject/Concrete.php#L252
