### ISSUE TITLE
Improvement - Do not alter vendor package with generated file filetype-not-supported

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#6828]
Hello,

Actually the `filetype-not-supported` image file is auto generated:
https://github.com/pimcore/pimcore/blob/55cdb8cd41ac4b55668bbf6b51e42a787c752f37/models/Asset/Document/ImageThumbnail.php#L75
https://github.com/pimcore/pimcore/blob/55cdb8cd41ac4b55668bbf6b51e42a787c752f37/models/Asset/Video/ImageThumbnail.php#L85
https://github.com/pimcore/pimcore/blob/55cdb8cd41ac4b55668bbf6b51e42a787c752f37/models/Asset/Image/Thumbnail/Processor.php#L101
https://github.com/pimcore/pimcore/blob/55cdb8cd41ac4b55668bbf6b51e42a787c752f37/models/Asset/Image/Thumbnail.php#L114

It ends up with created files in `vendor/pimcore/pimcore/bundles/AdminBundle/Resources/public/img/filetype-not-supported.webp` for instance (webp supporting browser).

This issue is about using an already existing file in the vendor package, or generate it somewhere else than in vendor, because:
- it is not good practice to alter vendor package
- in case vendor is in GIT repository it leads to created file in different environment which could cause merge problem/not clean git status even in prod.
(I know having vendor in GIT is not ideal but some made this choice, like us because composer v1 is so slow sometimes so starting a project is a lot more faster with git clone than git clone + composer update, especialy in CI tests)

A temporary solution could be adding in git ignore `vendor/pimcore/pimcore/bundles/AdminBundle/Resources/public/img/filetype-not-supported.*` but it is a dirty hack.

Thanks.

**Comment by brusch** [comment]
Fixed by #8043

**Comment by Yivan** [comment]
Great thank you !
