### ISSUE TITLE
More correct return value types

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#6830]
Currently, the code generated for a boolean called `HideProducts` looks like this:

```php
/**
* Get HideProducts - Hide Products
* @return boolean
*/
public function getHideProducts () {
	if($this instanceof PreGetValueHookInterface && !\Pimcore::inAdmin()) { 
		$preValue = $this->preGetValue("HideProducts"); 
		if($preValue !== null) { 
			return $preValue;
		}
	} 

	$data = $this->HideProducts;

	if ($data instanceof \Pimcore\Model\DataObject\Data\EncryptedField) {
		    return $data->getPlain();
	}

	return $data;
}
```

If you're using it with strict types like this:

```php
// $object is from Pimcore
$document->setHideProducts($object->getHideProducts());
```

You get:
```
setHideProducts() must be of the type bool, null given, called
```

so obviously null is possible here, meaning `@return boolean` is lying.

If I do

```
$document->setHideProducts((bool) $object->getHideProducts());
```

then I get an error from PHPStan

```
Casting to bool something that's already bool.
```

# Solution

The obvious solution here is to fix the `@return` tag to be more correct: if it's nullable, then it needs to specify this.

```php
/**
* Get HideProducts - Hide Products
* @return boolean|null
*/
public function getHideProducts () {
        // ...
	return $data;
}
```

Even better would be if the types declared matched the actual types returned, so if you say it's boolean, return actual boolean. This would mean enabling strict types and actual return type would be within reach:

```php
/**
* Get HideProducts - Hide Products
*/
public function getHideProducts (): ?bool {
        // ...
	return $data !== null ? (bool) $data : null;
}
```

WDYT?

**Comment by dpfaffenbauer** [comment]
wasn't that solved with https://github.com/pimcore/pimcore/pull/6484 already?

**Comment by dkarlovi** [comment]
@dpfaffenbauer seems similar, but in this case the current information is invalid so I'd argue this to be a bug, that one looks like an optional feature.

**Comment by brusch** [comment]
@dkarlovi you're right. 
Should be easily to fix by implementing the functions defined in `\Pimcore\Model\DataObject\ClassDefinition\Data\TypeDeclarationSupportInterface` can you provide a PR for the master branch? 
Thanks a lot!
