### ISSUE TITLE
Allow saving document CMS even if exception

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#6831]
Hello,

In recent Pimcore version (there was not this in older ones), on the GUI backend saving a document is not possible if the document send an exception.

When developping this is annoying because you need to patch temporary the controller with something like `return;` directly at the start of the controller to be able to change the view layout for instance or some other settings of the document CMS.

I classified it has a bug, because admin user should be able to set/change bundle/controller/view even if there is errors (sometimes this change is to no more having this error... for instance if the view does not more exists and you want to set the new one). For one document is is ok, but if you changes some project structure and have to handle many docs, you need to put a temporary return in every controller... you see ; )

Thanks.

**Comment by brusch** [comment]
I wouldn't classify this as a bug nor as a feature. If there is a code triggered exception, there must be a reason for it and the existing contents should stay unchanged.

**Comment by Yivan** [comment]
Yes I don't know the classification : ), but the problem here is for instance:
- you rename the view script (IDE)
- you get on the GUI backend to change the view for the new file on the document CMS
- as there is an exception which prevent saving... you are stuck and need to do some hack on the controller to be able to save

Or another use case: you have an old controller action which is buggy (throw exception) and you made a brand new controller, but as document cannot be saved you cannot change the controller.

The real purpose of this issue is being to be able to set bundle/controller/view for page sending an exception (because of refactoring, chaning file structure, etc.).

**Comment by msphn** [comment]
I'd consider it a bug in the implementation and not in pimcore itself if that happens. If let's say the request can't be parsed by symfony and throws an exception it might wipe the page you saved.

If an errors occurs it feels natural to rollback any transaction and throw the error.

Deprecations btw. shouldn't be exposed towards the user, better mark them as deprecated in phpstorm and use the deprecation helper and CI to get aware of those usages.
