### ISSUE TITLE
Changing an object class attribut from image to externalImage and vice et versa

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#6832]
Hello,

1- Changing an object class attibut **from image to externalImage**, lead to inconsitent database, as asset field is keeped in the DB structure.
We get problem with this change in a `block`.
To recreate: on an object class, in a `block` create an attribut image, put an asset on a object instance, save&publish it, and after change the class attribut in the `block` to an external image. It leads to error when manipulating the object.

![image](https://user-images.githubusercontent.com/9025839/88548207-10a47b80-d01f-11ea-8c2d-cb515103ae8f.png)

Here is a dump of structure of the block element:

![image (1)](https://user-images.githubusercontent.com/9025839/88548261-2a45c300-d01f-11ea-9bff-4428a2583ca3.png)

2- Changing an object class attibut **from externalImage to image**, lead to error when accessing the object:

```
Status: 500 | Internal Server Error
URL: /admin/object/get
Message: Cannot use object of type Pimcore\Model\DataObject\Data\ExternalImage as array
Trace: 
in /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Image.php:515
#0 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Block.php(207): Pimcore\Model\DataObject\ClassDefinition\Data\Image->unmarshal()
#1 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Block.php(1028): Pimcore\Model\DataObject\ClassDefinition\Data\Block->getDataFromResource()
#2 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Fieldcollection/Dao.php(97): Pimcore\Model\DataObject\ClassDefinition\Data\Block->load()
#3 [internal function]: Pimcore\Model\DataObject\Fieldcollection\Dao->load()
#4 /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(247): call_user_func_array()
#5 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Fieldcollections.php(340): Pimcore\Model\AbstractModel->__call()
#6 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Fieldcollections.php(639): Pimcore\Model\DataObject\ClassDefinition\Data\Fieldcollections->load()
#7 /var/www/html/var/classes/DataObject/RBCCountrySelection.php(48): Pimcore\Model\DataObject\ClassDefinition\Data\Fieldcollections->preGetData()
#8 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(612): Pimcore\Model\DataObject\RBCCountrySelection->getSections()
#9 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(538): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->getDataForField()
#10 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(435): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->getDataForObject()
#11 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(158): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->getAction()
#12 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#13 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle()
#14 /var/www/html/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle()
#15 {main}
```

I think maybe data will need to be sanitized when such change occurs to prevent this ?

Best regards.

**Comment by dpfaffenbauer** [comment]
Don't think this is possible to handle inside a block, since the block is directly serialized into the database. If you, as an admin change a field from image to external image, deal with that in your code and or rename the new field to get rid of these messages.

**Comment by Yivan** [comment]
Thanks,
yes I know this is side case and changing attribut type can lead to some problem. But in those case it breaks the BO. Object can no more be opened. This is why it is tiedous.
I totally agree, renaming it or changing to a totally different type would properly do the job.
We know a litte pimcore, but for people less experienced it can be confusing.

If this issue is irrevelent you can close it or could be left as it, it is not at all prioritary for sure. But it would be nice the BO didn't breaks when opening object after making on such actions.
At least handle the case so object can be opened maybe.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
