### ISSUE TITLE
Improvement - Create default "native" properties when creating document, at least for navigation_exclude

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#6833]
Hello,

Some document properties are not created in the `properties` table when creating/saving a document.
Only the one filled are created and property_name.

For most of them this is not a problem, but for "navigation_exclude" this make it tiedous to find document not exluded.
Resolving it by SQL request make it not possible as this will be a SQL join between document and properties table like:

```
SELECT
    id
FROM
    documents
INNER JOIN
    properties ON documents.id = properties.cid
WHERE
        documents.published = 1
    AND
        properties.name = "navigation_exclude"
    AND
        properties.data != 1
```

navigation_exclude property will only be set if checked on the GUI. So there is no join for them.

I opened this issue, because I think this would be usefull to create it to value 0 when creating a document so finding not excluded one will be easier and could be handle fast with SQL directly.
As this field is often used to check pages to generate some sitemap or other thing it will help.

I don't know if it is needed to set other properties (risk is to make the property table bigger...). But navigation_exclude is the one i think is the most usefull and deserve to be setted to value 0 at document creation.

Thanks.

**Comment by brusch** [comment]
Just use `LEFT JOIN` and you're fine 😉

**Comment by SmashingQuasar** [comment]
> Just use LEFT JOIN and you're fine 😉

I am sorry but this is highly sub-optimal. If you save it properly from the beginning, you do not need the join at all. This means you only do the operation once per save. With your suggestion the operation would be repeated every page viewed by every visitor. It's not acceptable for an optimized production environment.

Moreover, there is a discrepancy between what is done through code and what is done through the administration panel. If there is a default value in the administration panel, then this value should be set **by default in all cases**. In this case, if you save the document through the GUI, you have a different behavior than with the PHP API while thinking you are achieving the same thing.

**Comment by brusch** [comment]
Well, yes and no 😊If you think of projects with hundreds of thousands documents, that might have a huge performance impact, while using an optimized query with `JOIN` shouldn't stress the system at all. 
But let's see if there are other opinions on that 😊

**Comment by dpfaffenbauer** [comment]
You can also add an event-listener to create these properties for you. I don't see that as a Pimcore obligation to always store these values even though you might not need it

**Comment by SmashingQuasar** [comment]
@dpfaffenbauer Well we use this feature in most of our projects. It is a pretty basic thing to use to provide advanced user experience when it comes to CMS. I guess I'll just have to create a global polyfill in our bundle through an event listener.
Thanks anyway.

**Comment by dpfaffenbauer** [comment]
@SmashingQuasar I never had a use-case to query documents based on if they are excluded in the navigation or not...
