### ISSUE TITLE
Elements of an ereablock remain in db when removing a areablock

### ISSUE THREAD

**Issue by timhonders** [pimcore/pimcore#684]
When i remove a areablock from a page the elements in that block remain in the documents_elements.

The Document class also loads this data, when u loop through $document->elements.

Is this intended behavior?

**Comment by brusch** [comment]
Yes. 
Please have a look at: 
https://www.pimcore.org/board/viewtopic.php?f=22&t=1786
https://www.pimcore.org/board/viewtopic.php?f=11&t=1399
...
...

**Comment by Cruiser13** [comment]
@brusch some posts of the forum can not be read, there is a warning message: [phpBB Debug] PHP Warning: in file [ROOT]/includes/bbcode.php on line 113: preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead

You might want to fix that so the forum threads can be read again. Your first linked topic has the issue for example.

**Comment by brusch** [comment]
@Cruiser13 I've updated phpBB already to the latest version, unfortunately it seems that the phpBB team hasn't fixed all issues with PHP7 yet. 

We have to wait for a new release from them ...
