### ISSUE TITLE
Using http (with server enabled http/https) admin connexion not possible.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#6840]
Hello,

On a serveur with http/https enabled (no http to https redirection), if you try to log in /admin on http://www.domaine.com/admin a CSRF error is sent.

![image](https://user-images.githubusercontent.com/9025839/88667481-b7e9e700-d0e1-11ea-9002-9e41b31661e1.png)

I think Pimcore use https for something and http for other, so messing the csrf/session.
User should be able to connect without error on http, or on login if pimcore detects https is enabled and working redirect to https. For now the message is a little cryptic and people can struggle to understand what happen.

I will post on gitter as someone get maybe this same problem:

![image](https://user-images.githubusercontent.com/9025839/88668014-5e35ec80-d0e2-11ea-9e13-21cb05d6631e.png)

Thanks.

**Comment by brusch** [comment]
I'm not able to reproduce the problem, I guess this is something specific to your setup. 
Maybe it has something to do with the configured session storage or so.

**Comment by Yivan** [comment]
Hum in our setup there is a reverse proxy in frontal, maybe it interferes...
Setup is like that:

Trafik Reverse Proxy (accept HTTP or HTTPS)   ===>  Apache 2.4 HTTPS only (443)

We don't have any problem with Pimcore or any frontend mecanism with this setup on which we made many Pimcore profesionnal setup (we use custom csrf check for forms and works fine, session works fine, etc...). So I think something could be improved in this admin login csrf check to be more robust on setup like those.

**Comment by brusch** [comment]
Probably it's related with the reverse-proxy. 
The CSRF check just uses normal sessions, there isn't anything custom from our side. 
But if you find a way how we can improve the session/CSRF handling we're more than happy to integrate a patch 😊

All the related code regarding CSRF can be found in https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/EventListener/CsrfProtectionListener.php

**Comment by dpfaffenbauer** [comment]
it is very likely it has something todo with the setup, but I see that screen very often and I still haven't figured why this happens... It is not really re-producable, just happens from time to time....

**Comment by brusch** [comment]
I agree, I also face this issue from time to time. But in my case it always had a very simple reason: 
I had the login page already open for quite some time in the background or it was loaded from the browser cache (even Chrome shouldn't cache the page, from time to time it's delivered from the cache). In this case the session expired already on the server side, so if you then submit the login form, the CSRF token which is not known anymore by the server and the error is thrown. 

Maybe that's also the reason why you're facing the issue? 🤔

**Comment by dpfaffenbauer** [comment]
Sounds reasonable.

**Comment by dpfaffenbauer** [comment]
Maybe it helps to add cache headers to the login page?

```
$response->headers->addCacheControlDirective('no-cache');
$response->headers->addCacheControlDirective('no-store');
$response->headers->addCacheControlDirective('max-age', 0);
```

**Comment by brusch** [comment]
A possible fix would be to store the calculated session expiry timestamp in a JS variable and just force a refresh on tab activate.
Regarding the additional headers: most of them are already there, but would be worth a try, doesn't hurt anyway 😊

**Comment by NiklasBr** [comment]
> I had the login page already open for quite some time in the background

This happens from time to time. An example is the server has been rebooted during the night (or just shut off for a few hours to save money on AWS). The user is therefore logged out automatically due to the session expiring and presented with a login screen, but on the first attempt they will see the CSRF error screen.

**Comment by NiklasBr** [comment]
> just force a refresh on tab activate

Would it be possible to just fetch a new CSRF token rather than a full page refresh?

**Comment by brusch** [comment]
@NiklasBr yes, I guess this should be also possible 😊 
Would be great if someone could contribute that for `6.7` 😊

**Comment by Yivan** [comment]
I confirm I (and my dev team too) got the problem from time to time, for the same reason (old cached datas). Refreshing page, or sometimes it doesn't suffice and we need to clear browser caches manually, correct the problem.
For sure this problem should be fixed I think as it can affect final Pimcore enduser which are not technicaly aware of this and can be blocked.

For the initial problem of this issue, in our proxy setup when using http to connect, I will dig the problem to see what could be improved.

**Comment by Yivan** [comment]
I found the problem for http connection, we have set "Secure" for php cookies so php session id is not set on http (80). So csrf session token is not persistant accross request.
The initial purpose of this issue is resolved and was due to our setup config, sorry about this false issue.

Anyway, like @brusch suggest it, maybe improve the cache mecanism so browser never cache login page or if not possible fetch it via ajax, would be more robust.
Maybe this issue can be close, and another issue open for login page csrf improvement to fix the problem happened randomly about the csrf message (when browser use local page cached).
Thanks.

**Comment by brusch** [comment]
Thanks a lot for your feedback! 
Will create a PR for the login page issues, let' see if it makes it any better 😊

**Comment by brusch** [comment]
#6849 should fix the issues described.

**Comment by Yivan** [comment]
Many thanks for this fast improvement. I will keep updated if we get some random csrf problem on the future version of Pimcore having this improvement.
