### ISSUE TITLE
Asset Preview Not Visible In Admin Asset Search

### ISSUE THREAD

**Issue by jeremygnoonan** [pimcore/pimcore#6841]
# Bug Report

### Expected behavior
Admin asset search should show video previews
### Actual behavior
Admin asset search only shows previews for image types
### Steps to reproduce
Search for a video asset in the admin

# Feature Request

## Feature description
I have found a solution for this and will be submitting a PR

**Comment by brusch** [comment]
For me the video is shown, it also works in our public demo. 
![image](https://user-images.githubusercontent.com/142037/88670699-ac002400-d0e5-11ea-8f0b-f2313f8bd3d6.png)

For support, please: 
https://talk.pimcore.org/
https://gitter.im/pimcore/pimcore

**Comment by brusch** [comment]
Ah, sorry, wrong "search" 😄 Thanks for the PR!

**Comment by jeremygnoonan** [comment]
No problem. This is my first time submitting. I hope all went well!
