### ISSUE TITLE
[Ecommerce] PriceInfo with Mockups and Categories

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#6850]
The PricingManager calls a ```method_exist``` here: ```if (method_exists($priceInfo->getProduct(), 'getCategories'))```
https://github.com/pimcore/pimcore/blame/master/bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php#L327

```$priceInfo->getProduct()```can potentially be a Mockup-Object that does not have the ```getCategories``` Method implemented.
The call gets skipped and the original Object is never loaded.

Therefore some Price rules that depend on the Category-Condition will get skipped on Mockup-Objects.

Is this behavior wanted?

**Comment by fashxp** [comment]
hmm guess not, is quite dangerous I would say.
