### ISSUE TITLE
Invitation link for new user not working with custom admin login entry point

### ISSUE THREAD

**Issue by kjkooistra-youwe** [pimcore/pimcore#6856]
### Expected behavior
Logging in when clicking the link in the email and be able to (re)set the password (among other settings).

### Actual behavior
Server returned a 404 error.

### Steps to reproduce
- [Configure a custom admin entry point](https://pimcore.com/docs/6.x/Development_Documentation/Development_Tools_and_Details/Custom_Admin_Login_Entry_Point.html)
- Create a new user, set an email address and save
- [Send an invitation link](https://github.com/pimcore/pimcore/pull/4935)
- Use a private window or another browser, simulating a user opening the environment for the first time
- Copy the link from the email or look it up in Sent Emails and open it in the private window

Replacing '/admin' in the link with the custom login entry point name results in a Pimcore page not found error (the one with the unicorn).

### Workaround
Open the custom admin login entry point first. It will redirect to /admin and this state is stored it in the session it seems. The link will open correctly now.

**Comment by brusch** [comment]
Fixed by #6883
