### ISSUE TITLE
Objects Tree Panel not available since latest update to v6.6.10 (previous version was v6.6.0)

### ISSUE THREAD

**Issue by abernardgalilee** [pimcore/pimcore#6858]
Dear all.
I just upgraded to latest version and since then, I no longer have access to my objectTree.
The functions which is supposed to initialise the route calls 
        this.treeDataUrl = Routing.generate('pimcore_admin_dataobject_dataobject_treegetchildsbyid');
However, this function enters in : 
key: 'getRoute',
        value: function getRoute(name) {
            var prefixedName = this.context_.prefix + name;
            var sf41i18nName = name + '.' + this.context_.locale;
            var prefixedSf41i18nName = this.context_.prefix + name + '.' + this.context_.locale;
            var variants = [prefixedName, sf41i18nName, prefixedSf41i18nName, name];

            for (var i in variants) {
                if (variants[i] in this.routes_) {
                    return this.routes_[variants[i]];
                }
            }

            throw new Error('The route "' + name + '" does not exist.');
        }
the variants are : 
(4) ["pimcore_admin_dataobject_dataobject_treegetchildsbyid", "pimcore_admin_dataobject_dataobject_treegetchildsbyid.en", "pimcore_admin_dataobject_dataobject_treegetchildsbyid.en", "pimcore_admin_dataobject_dataobject_treegetchildsbyid"]
However they are not found in the this.routes_
Therefore I get a "The route does not exist".

This is surprising since a bin/console debug:route shows that the route effectivelly exists : 
web-user@pimcore:~/htdocs/pimcore$ bin/console debug:router | grep pimcore_admin_dataobject_dataobject_treegetchildsbyid
  pimcore_admin_dataobject_dataobject_treegetchildsbyid                                GET               ANY      ANY    /admin/object/tree-get-childs-by-id

So the JS route_ table seems to be missing some of the routes.

**Comment by fashxp** [comment]
did you clear all symfony caches and rebuild your container? 
works on demo instance, so seems to be a problem related to your setup?

**Comment by abernardgalilee** [comment]
Dear fashxp.
Cache clearing did not work.
I restored my snapshot, I 
1) uninstalled the ecommercebundle (from the pimcore admin bundle interface) 
2) re-updated to v6.6.10 modifying my composer.json and using composer update
3) re-install the ecommercebundle (from the pimcore. admin bundle interface) 
And now this is working and I no longer have the exception.
Not sure then whether this is this bundle that created the problem.
You can close the ticket.

**Comment by debanshu411** [comment]
@fashxp I am facing the same issue tried cache clear and every thing even we dont have the ecommercebundle bundle still DataObject section is not getting loaded.

![Screenshot-from-2020-11-20-00-34-21](https://user-images.githubusercontent.com/69641583/99711840-47b80480-2ac8-11eb-8b86-109595bf7859.png)

**Comment by fashxp** [comment]
do you have any other bundles installed? seems that some bundle is messing up the routes ... does some bundle creates routes in the /admin route hat is not exposed?

**Comment by debanshu411** [comment]
@fashxp found it out on the 6.6.0 version we have overriden the DataObject Controller which was causing the problem.
