### ISSUE TITLE
[Thumbnails] Frame positioning option

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#6869]
# Feature request

Add a positioning option to the `frame` thumbnail configuration.

Currently the image is always centered, so the "frame" adds transparent borders left/right or top/bottom to the image. It would be great if there was an option to only add space on the top/bottom/left/right side.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
