### ISSUE TITLE
Unable to add category in grid view, icons missing

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#6875]
Hi, 

When in grid view in PimCore version 6.6.10 the icons are missing when adding/searching a category:

![image](https://user-images.githubusercontent.com/41229269/89104265-46c76e00-d418-11ea-90c7-dcc353ede19f.png)

When you go to the category in de object detailsettings the icons are available:

![image](https://user-images.githubusercontent.com/41229269/89104283-74acb280-d418-11ea-825e-965d1a6262df.png)

**Comment by dvesh3** [comment]
Sorry, unable to reproduce
![image](https://user-images.githubusercontent.com/5137917/89163528-01b94e00-d576-11ea-8d42-486a215983a3.png)

**Comment by Hbitvof** [comment]
My fault. There was a configuration error in our PimCore installation.
