### ISSUE TITLE
Filter select column not working with ' in selection

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#6877]
Hi,

When filtering in grid view on an select column it's not possible to filter on a selection with a ' in the name:

![afbeelding](https://user-images.githubusercontent.com/41229269/89158149-f8c47e80-d56d-11ea-9c3d-e12b81003add.png)

In this case we wan't to filter on: _Zita's Yape / Wings Byou B.V._

**Comment by brusch** [comment]
Closed by #6878
