### ISSUE TITLE
Workflowmanagement - Quick actions on elements

### ISSUE THREAD

**Issue by cleggypdc** [pimcore/pimcore#688]
The ability to specify quick actions as a dropdown from the Action button.
(Much like the Refresh & Publish buttons)

inspired by JIRA ;-)

![image](https://cloud.githubusercontent.com/assets/1098498/16301574/fc4557b2-393d-11e6-90c7-011af3b9f094.png)

**Comment by Yivan** [comment]
I like it! We could use map action to some module/controller/action. Would be easy to adapt the GUI to add printing fonctionnality (invoice concerning an order object for exemple, etc.).

**Comment by cleggypdc** [comment]
@Yivan this is more concerned with actions in the the workflowmanagement configuration see here: https://github.com/pimcore/pimcore/blob/master/website_example/config/workflowmanagement.example.php#L79

so configuration would add an option that could be specified either in action configuration or preferably in transitionDefinitions (extending the action configuration)

```
"in_progress"=> [
                    "validActions" => [
                        "mark_as_in_review"=> [
                           "quickAction" => true
                        ],
                        "stop_progress"=> null
                    ],
                ],
```

**Comment by markus-moser** [comment]
In the new workflow engine (Pimcore 5.5) each action/transition is somehow like this quick action feature by default. Therefore I'll close this issue.
