### ISSUE TITLE
$view shared within all areas in one areabrick

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#6885]
I just noticed that the `$view` Variable is shared between all areas/bricks within one areabrick. Since the view variable is created by the `TagHandler`, it doesn't get disposed within the brick. Which is unexpected and can lead to unknown errors by having a view variable set by one brick that could also be within a following brick. Is this intentional?

**Comment by brusch** [comment]
Yes, this was intentional, since this was the way how it worked with ZF as well. 
However we cannot change this without a breaking change and it's obsolete for X anyway.

**Comment by breakone** [comment]
just came across that in 6.6 and it was fixed with X: https://github.com/pimcore/pimcore/pull/7247.
