### ISSUE TITLE
Asset Upload | Replace existing asset instead of adding a duplicate

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#6893]
# Feature Request

## Problem Description
When uploading the same asset several times, Pimcore adds multiple versions of the same asset, by adding an incremental number at the end of the file name.

Example:
![image](https://user-images.githubusercontent.com/16687355/89284456-1c132a80-d64f-11ea-8bd0-aed1237ab95f.png)

```
test.txt
test_1.txt
test_2.txt
```

are identical.

---

## Improvement Suggestion
Add a configuration option, so that when uploading assets with the same file name, the user is asked if the existing file should be replaced, instead of adding an additional file without prompting.

There are several challenges related to this issue, as mass uploads, etc. need to be considered as well. However, as this feature seems to be quite important for some of our customers, because they want to avoid redundantly saved data, I hope that other members of the community will vote for that issue as well, so that it might get realized some day.

**Comment by NiklasBr** [comment]
Good idea, I would be in favour of something like this:
![image](https://user-images.githubusercontent.com/279826/89286359-5af6af80-d652-11ea-983f-63e9eaad8553.png)
