### ISSUE TITLE
Grid editing of quantity values in variants tab is broken

### ISSUE THREAD

**Issue by msphn** [pimcore/pimcore#6898]
Hello,

editing a quantity value in the grid using the tree (screen 1) works flawlessly, but editing it in the grid of an object's variants list is failing (screen 2).

Screen 1:
<img width="1411" alt="Screenshot 2020-08-04 at 16 51 53" src="https://user-images.githubusercontent.com/579227/89308946-221b0280-d673-11ea-9538-9d3eeff91eb2.png">

Screen 2:
<img width="1414" alt="Screenshot 2020-08-04 at 16 52 03" src="https://user-images.githubusercontent.com/579227/89308974-29421080-d673-11ea-9045-79dd3d94f718.png">

I reproduced it on Pimcore Demo, you may experience it yourself if you are fast enough 😎

**Comment by weisswurstkanone** [comment]
I wasn't able to reproduce this on the current demo instance. If you experience this again could you please attach the stack trace (click on "details") thx!

**Comment by msphn** [comment]
Hey weisswurstkanone,

make sure you follow those steps:

- Edit car object definition
- Add a quantity field with e.g. kg and default unit kg
- Add a new car object called liked e.g. test1
- Add a variant to that object e.g. test1.1
- Go to variant grid
- Edit variant grid to display you quantity field, name it save and share it
- Reload grid if required
- Klick on field now displaying kg or the default unit you've specified
- Enter number 1
- Press ok

<img width="1071" alt="Screenshot 2020-08-05 at 16 55 59" src="https://user-images.githubusercontent.com/579227/89428443-aeddc300-d73c-11ea-93a1-2822042ab3b4.png">

<img width="1360" alt="Screenshot 2020-08-05 at 16 56 45" src="https://user-images.githubusercontent.com/579227/89428422-a84f4b80-d73c-11ea-9e73-3f648974e71b.png">
