### ISSUE TITLE
Improvement - Filter on empty in Grid View for (multi)select Component

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#6903]
Hi,

Is it possible to make an adjustment to the filter for the (multi)select component in the grid view to filter on empty rows where a selection is not filled in yet?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
