### ISSUE TITLE
Remote Connection to Database when installing pimcore

### ISSUE THREAD

**Issue by aadewojo** [pimcore/pimcore#6908]
# Bug Report

### Actual behavior
I am trying to install Pimcore but get stalled at the installer stage. It returns an error related to the database as follows: ``` Couldn't establish connection to MySQL: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'SSL_USER'@'x.x.x.x' (using password: YES)```. I defined database parameter in installer.yml file as described here https://pimcore.com/docs/5.x/Development_Documentation/Getting_Started/Advanced_Installation_Topics.html

my yml file looks like this :
``` pimcore_install:
    parameters:
        database_credentials:
            user:                      SSL_USER
            password:             password
            dbname:               project_database

            # env variables can be directly read with the %env() syntax
            # see https://symfony.com/blog/new-in-symfony-3-2-runtime-environment-variables
            host:                 x.x.x.x (Ip address of db server)
            port:                 3306
```

The database is on another server and I can connect to it using mysql client on the server which pimcore is suppose to run on. Also connection requires SSL.
### Steps to reproduce
run ./vendor/bin/pimcore-install
### Code example
```php
// your code
```

# Feature Request

**Comment by agendartobias** [comment]
I have the same problem. Any idea how to do this?
