### ISSUE TITLE
Area copy looses data in some cases

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#691]
# Bug Report

Tested with Pimcore version 4.1.2.

I have the following area block (placed in website/views/areas/blocktest/view.php):
```php
<div class="area-blocktest">
<?php $block = $this->block("gridblock", ["manual" => true])->start(); ?>
<?php if($this->editmode) { ?>
<?php echo $this->input("testinput"); ?>
<?php } ?>
<table>
    <tr>
        <?php while ($block->loop()) { ?>
            <?php $block->blockConstruct(); ?>
                <td customAttribute="<?= $this->input("myInput")->getData() ?>">
                    <?php $block->blockStart(); ?>
                        <div style="width:200px; height:200px;border:1px solid black;">
                            <?= $this->input("myInput"); ?>
                        </div>
                    <?php $block->blockEnd(); ?>
                </td>
            <?php $block->blockDestruct(); ?>
        <?php } ?>
    </tr>
</table>
<?php $block->end(); ?>
</div>
```
It's basically the block example from the documentation: https://www.pimcore.org/wiki/display/PIMCORE4/Block
I only added the first input **testinput**

I fill the block with data like this:
![blocktest](https://cloud.githubusercontent.com/assets/2771909/16302876/c66295b4-394d-11e6-9d9d-26f3823378c2.png)

If I do now copy the area to another document, the value of the testinput is gone in some cases. The value of myInput will be copied. It does not always happen but most of the time, so it should be reproducable although I can not deliver a reason for it yet.

Am I misusing the block element in some way? Or is there another reason the copying of this field fails?

**Comment by brusch** [comment]
see #559

**Comment by Cruiser13** [comment]
@brusch I wasn't sure if that's the same issue. It only happens in conjunction with block elements for me and it does not always happen.
Thanks for clarification.

**Comment by brusch** [comment]
No, problem - thanks. It is absolutely the same issue, blocks and areablocks are using the same functionality.
