### ISSUE TITLE
Improvement - Autorefresh Calculated Value

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#6919]
When editing a field related to a calculated field the calculated field itself is not updated. This is both in the grid view as the objectdetail view.

Now you have to refresh the page to see the results.

Is it possible to change this behaviour?

**Comment by NiklasBr** [comment]
I believe implementing #4678 could solve this.

**Comment by weisswurstkanone** [comment]
No, you never know which fields the calculation depends on. Could be something related to the obect itself or something completely different like the weather forecast.
Could imagine however to add a refresh button similar to the preview / iframe layout component.
https://pimcore.com/docs/6.x/Development_Documentation/Objects/Object_Classes/Layout_Elements/Preview_Iframe.html

**Comment by Hbitvof** [comment]
@weisswurstkanone, true but a workaround could be to make a setting in for the calculated field to setup one or more relationships between the calculated field and the datafield so the calculated field gets a trigger to refresh when the datafield is updated.

**Comment by Hbitvof** [comment]
Anyone already thought about this?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
