### ISSUE TITLE
Improvement - No case sensitive and wildcard usage in filter grid view

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#6954]
Hi,

At the moment when using a filter in an input column this is case sensitive so you have to search for exact term.
This is not very user friendly. Can this be changed? 

Also using wildcards are not working in this filter like *. Can this also be added?

**Comment by Hbitvof** [comment]
Hi, 

Any comment on this suggestion?

**Comment by Hbitvof** [comment]
Still no one reacting?

**Comment by jdreesen** [comment]
I'm sure the Pimcore team will gladly merge your PRs that implement the requested feature.

**Comment by robin-ntriga** [comment]
I managed to fix the case sensitivity issue in: vendor/pimcore/pimcore/bundles/AdminBundle/Helper/GridHelperService.php

By adding `lower()` around the column names & values:

[GridHelperService.php:331](https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/src/Helper/GridHelperService.php#L332)
`	$conditionPartsFilters[] = 'concat(lower(o_path), lower(o_key)) ' . $operator . ' lower(' . $db->quote('%' . $filter['value'] . '%') . ')';`

[GridHelperService.php:334](https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/src/Helper/GridHelperService.php#L334)
`  $conditionPartsFilters[] = 'lower(o_key) ' . $operator . ' lower(' . $db->quote('%' . $filter['value'] . '%') . ')';`

Is this change correct? If so I will make a PR with the fix.

**Comment by fashxp** [comment]
can you still create a PR for that?

**Comment by robin-ntriga** [comment]
I have created a PR to fix the case sensitivity issue:
https://github.com/pimcore/admin-ui-classic-bundle/pull/389

**Comment by cancan101** [comment]
In order to not affect performance, does this require there to be a new functional index added to the database?
