### ISSUE TITLE
XLIFF Import deleting HTML special chars in 6.7.0

### ISSUE THREAD

**Issue by foxgreek** [pimcore/pimcore#6956]
# Bug Report

### Expected behavior

When importing edited/unedited XLIFF-File, all unedited WYSIWYG fields should keep their formats and special chars.

### Actual behavior

If a WYSIWYG field was not edited the HTML special chars are missing after reimporting the XLIFF file.

### Steps to reproduce

**1. open the lifestyle site (/en/Magazine/Lifestyle) in the demo and add some formats to the WYSIWYG (e.g. strong):**

<img width="1227" alt="Bildschirmfoto 2020-08-17 um 09 32 13" src="https://user-images.githubusercontent.com/40141606/90369970-e289e880-e06c-11ea-9eaa-9a4ec4e15df6.png">

**2. export the Lifestyle site via XLIFF**
<img width="921" alt="Bildschirmfoto 2020-08-17 um 09 38 30" src="https://user-images.githubusercontent.com/40141606/90370253-6f34a680-e06d-11ea-9213-99bea787cf02.png">

**3. reimport the XLIFF file**

**4. open the updated Lifestyle site and the bold text format is missing:**
<img width="1156" alt="Bildschirmfoto 2020-08-17 um 09 41 17" src="https://user-images.githubusercontent.com/40141606/90370524-d2263d80-e06d-11ea-80c2-5cb2e96b0d2d.png">

If I'm changing the WYSIWYG translation field it gets updated:
<img width="1167" alt="Bildschirmfoto 2020-08-17 um 09 43 48" src="https://user-images.githubusercontent.com/40141606/90370740-2b8e6c80-e06e-11ea-83bc-47325fdc3c8a.png">

Any ideas why it removes the HTML special chars?

**Comment by msphn** [comment]
@fashxp probably that (string) cast we added behaving different?
