### ISSUE TITLE
Improvement - Adding Dailymotion video type

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#696]
Actually, video support (in document or object) is for asset/youtube/vimeo.
Could maybe dailymotion be added ? So all the big 3 videos providers can be managed.

**Comment by brusch** [comment]
PRs are welcome :-)
Alternatively you could use the "embed" editable, which utilizes oembed and works also for dailymotion.

**Comment by Yivan** [comment]
Thanks, ok i will try to make a PR for dailymotion as soon as i can.
