### ISSUE TITLE
Percona XtraDB Cluster broken with 6.6

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#6960]
I just updated a project running on an Percona XtraDB Cluster and 6.6 is not running on it anymore:

*An exception occurred while executing 'DELETE FROM object_relations_customer WHERE src_id = '8' AND ownertype = "object"':*

*SQLSTATE[HY000]: General error: 1105 Percona-XtraDB-Cluster prohibits use of DML command on a table (object_relations_customer) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER*

So, Percona basically disallows DML commands on tables without a primary key, since Pimcore doesn't have one on relation tables, it doesn't run there.

**Comment by brusch** [comment]
Ok, but Percona cluster is not officially supported, however, we'd of course merge a PR fixing the issue.

**Comment by brusch** [comment]
As far as I can remember we removed the PK for several reasons, especially to keep the memory footprint as small as possible, probably this needs an extra config or so 🤔 Because maintaining data that isn't used in 99,7% isn't really practicable.

**Comment by dpfaffenbauer** [comment]
What cluster is then supported by Pimcore? There for sure is a pretty good reason why Percona complains about tables without PK. I don't see any reason why a table should not have a PK?

**Comment by dpfaffenbauer** [comment]
Reading on https://www.percona.com/blog/2013/10/18/innodb-scalability-issues-tables-without-primary-keys/ and https://forums.percona.com/discussion/10603/limitations-on-tables-w-o-primary-keys:

> However, it's still generally a best practice to have explicit PKs. If you don't define them, then you will have in implicit hidden 6-byte PK in your Innodb table taking up space that you can't use for any querying. Innodb is very much optimized towards PK lookups, so it benefits you to have one you can query by.

So, if you don't explicitly create a PK, InnoDB does it for you anyway, so what is the point of "saving data space" when InnoDB then fills it anyhow on non usable data?

**Comment by brusch** [comment]
>  I don't see any reason why a table should not have a PK? 
We had a PK over several columns, which was pretty big then (on the disk), so we decided to drop it. 
See also #5769 and #5687

**Comment by brusch** [comment]
Well, why XtraDB does it then 😉 
Just kidding, probably we'd have to use an auto increment column then for that, but like I said, not on our priority list.

**Comment by dpfaffenbauer** [comment]
I'll create a PR for a primary col (auto-increment) on relation tables, ok?

**Comment by brusch** [comment]
Yep. Thanks! Looking forward to the PR 😊
