### ISSUE TITLE
Audio asset type: preview (using HTML5 browser native player)

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#698]
Maybe a preview tab (like for PDF, video, ...) could be added for audio type with HTML5 native player ?
So administrator can preview audio directly without downloading it.

**Comment by brusch** [comment]
only mp3 is supported at the moment

**Comment by Yivan** [comment]
Thanks! With icon (https://github.com/pimcore/pimcore/issues/697) and this preview feature, audio is better on Pimcore.

Just, why did you limitated audio preview to mp3 as audio HTML5 tag support others formats ? (https://github.com/pimcore/pimcore/commit/dc468361b4c3a4635833ebb9365706583e27ed58#diff-cb1142d0770531bb402a43cca902aa93R86)
For instance WAV is a very used format, and is often the "source" format (like "PSD" for graphism). It make sense to store audio file in a raw format in WAV on a PIM for company using audio materials.
If you check for WAV support (in the bottom of this page there is link to the different format support: http://caniuse.com/#feat=audio), it seems pretty well suported (just internet explorer is lacking, but we know it is often behind ; ) ). AAC is great too (more used for Apple stuff).

**Comment by brusch** [comment]
It's limited to MP3 because it's the only format that is supported by all major browsers and version which Pimcore supports. 
See: https://www.pimcore.org/wiki/display/PIMCORE4/System+Requirements#SystemRequirements-BrowserRequirements 

It's as simple as that :)

**Comment by Yivan** [comment]
Ok i undestand, but WAV is only not supported by IE (Edge support it): http://caniuse.com/#feat=wav (comparing to MP3 : http://caniuse.com/#feat=mp3).
So maybe just adding something on pimcore/static6/js/pimcore/asset/audio.js, line 89, like:

```
if(!Ext.isIE && this.data.filename.match(/\.(wav)$/)) {
	html = '<audio controls><source src="' + this.data.path + this.data.filename + '" type="audio/wav"></audio>';
}
```

would offert for all the other the possibility to play wav directly. So MP3/WAV will cover major audio needs.

(AAC is a lot less used and not fully compatible with Firefox only comparing to MP3: http://caniuse.com/#feat=aac)

**Comment by Yivan** [comment]
Thanks for the commit adding WAV !

Is it intentionnal that `type="audio/mpeg"` is for both ? For WAV, it seems it is `type="audio/wav"`.
