### ISSUE TITLE
Pimcore Fulltextsearch ignores certain words when using hyphens

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#6980]
# Bug Report
When using strings such as "TE-ST", "HE-VA", etc. in input fields of data objects, Pimcore object search does not find the related data objects.

Probably it has to do with the fact that Pimcore relies on MYSQL-Fulltext search and the default value of ``ft_min_word_len`` is 4. https://mariadb.com/docs/reference/mdb/system-variables/ft_min_word_len/ When using hyphens, MySQL will split the word into "TE" and "ST" and because of the limit of 4 those words obviously are not added to the search index.

I am looking for a solution suggestion, as decreasing the value of `ft_min_word_len`` is probably not a good practicse, and the search shouldn't depend on environment settings.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
