### ISSUE TITLE
Currency shown in Pimcore admin may differ from actual transaction currency

### ISSUE THREAD

**Issue by alasdair-shields** [pimcore/pimcore#6984]
# Bug Report
The following happens when sales transactions are completed in a currency different from that of the admin's current environment.

### Expected behavior
Pimcore Admin Ecommerce Back Office order detail should display currency for the actual transaction

### Actual behavior
The currency shown is that for the current admin's environment, not the transaction currency

### Steps to reproduce
Create and commit an order in USD

In Pimcore Admin, with environment currency as EUR, view the order detail.
The price shown will be EUR

### Code example
Possible solution:

Pimcore\Bundle\EcommerceFrameworkBundle\OrderManager\Order\Agent::getCurrency()

```
public function getCurrency()
    {
        if ($order = $this->getOrder()) {
            if ($shortName = $order->getCurrency() {
                return new Currency($shortName );
            }
        }
        return $this->environment->getDefaultCurrency();
    }
```

**Comment by schacki** [comment]
Is anybody working on this? We are affected, but have certainly not enough knowledge to fix it properly (I am afraid the code example is the first step but not sufficient yet for a pr).
