### ISSUE TITLE
[DataObject Grid] Add select label operator

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#6985]
# Feature Request
- Add an operator to fetch select/multi-select label

**Comment by weisswurstkanone** [comment]
Anybody wants volunteer ? 🤔

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Comment by la-lisa** [comment]
Is there already a way to get the label of a select field when using a object field getter? When using the select field in the object directly i get the label instead of the value. In ObjectFieldGetter i get value instead of label.
