### ISSUE TITLE
Config Option to disable code/config generation by Admin-UI

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#6987]
This is mainly about deploying Pimcore on read-only file-systems or to ensure that changes in the config cannot be done in the admin interface. 

This affects among other things: 
- class definitions
- image/video thumbnails
- system settings
- custom reports
- bundle manager
- document-types
- predefined properties
- predefined asset metadata 
- website settings
- web to print 
--- 

It should be possible to just disable single functionalities or all at once. 
The UI for those features should be still available but the save-buttons should be grayed-out or the editing functionality should be disabled (eg in grids, ...).

**Comment by dpfaffenbauer** [comment]
YES :) 🍻 ❤️

**Comment by brusch** [comment]
This is covered by #9330
See also: https://github.com/pimcore/pimcore/blob/984e323a3842cbca77b6a36096ff3fbd3cd7bc62/doc/Development_Documentation/21_Deployment/03_Configuration_Environments.md#configuration-storage-locations--fallbacks
