### ISSUE TITLE
Images Upload Failing in Debug Mode with S3 Setup

### ISSUE THREAD

**Issue by ivanmerta** [pimcore/pimcore#6988]
Images are failing to be uploaded when the debug mode is turned on and S3 is setup as a stoarge according to 
[Pimcore Guide](https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Amazon_AWS_Setup/Amazon_AWS_S3_Setup.html)
This fails both for UI and WebDAV. 

![Screenshot from 2020-08-25 12-09-40](https://user-images.githubusercontent.com/39729841/91162095-e8ff0c80-e6cb-11ea-9ea1-6dc6c62ad2e5.png)

**Comment by dpfaffenbauer** [comment]
just had the same recently, this happens when another error (which was caught) happened before. We disabled system preview thumbnails and then it worked.

**Comment by putzflorian** [comment]
also a solution is documented here -> https://github.com/pimcore/pimcore/issues/6339

**Comment by dvesh3** [comment]
duplicate of #6339
