### ISSUE TITLE
[Improvement] Grid filter improvement: link (href/mutlihref), images, and empty values.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#699]
On the object grid, it is possible to filter "path" column. But for instance "href"/"multihref"(asset/objectdocument link) type column can not be filtered.

By the way adding the possibility to filter "empty" values would help administrator to find for instance object with empty href/multihref link. Or object where image (image type field) is not filled. I know it could be done by making a custom report to find empty value, but is is more convenient for enduser to use directly the grid when he work on his dataset.

**Comment by kubaplas** [comment]
@brusch do you have any plans regarding this issue?

**Comment by fashxp** [comment]
not on our prio list yet, we are happy to merge PRs for that though (maybe with a short discussion about the planned solution before implementing it completely)

**Comment by greefhorst** [comment]
@fashxp I've been working on the issue for some time, but ran into the same issues as @BlackbitNeueMedien in #3031: how to fill the filters and trigger an ajax call? In the meantime, I was able to do build a well working list filter, but this might result in a very long options list (although 200 options is already accepted for Country select fields). How do you feel about this? Or do you have any suggestions on how linking the values from a popup to the filter?
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/70212046/94911631-b9031000-04a6-11eb-99c4-ede2ed0fbf21.png">
(I used the object key in the example, but this might also be another column (path?), or maybe using the PathFormatter class configured for the field.

**Comment by fashxp** [comment]
@greefhorst  thank you for your input. 
> How do you feel about this?
looks nice, but I'm not sure if this really scales and is robust enough. what, if you have thousands of objects of the liked class (or no class limit in the class definition at all, so all data objects in the system are valid options). 

> Or do you have any suggestions on how linking the values from a popup to the filter?
sorry, not really. 
maybe not implement it as grid filter from ext but as some custom filter similar to the sql filter?

**Comment by kubaplas** [comment]
@greefhorst Did you continue working on this feature? If you dropped it, maybe you can share the code? I can try to finish the job ;)

**Comment by brusch** [comment]
Fixed by #10022 🥳
