### ISSUE TITLE
Personas not assigned for document included with helper.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#700]
I don't know if it is intentionnal, but we wanted to change wysiwyg text depending of personnas for a common block on a left column of a website. Snippet doesn't offer the possiblity of document for personnas targeting, so we tried to use $this->inc helper.

Creating a new document, assigning personnas (for instance just browser detection) and customize the text of a wysiwyg for this personas. Using the direct url is working for this persona. But using the view helper $this->inc doesn't assign the personnas.

Is this intentional ? (i think that the process behing personas are assigned during the predispatch and $this->inc doesn't pass through it). If yes maybe a short line about this could be included in the documentation (i can add it) ? On the other way it could be an improvment to have the possibility to target snippet or $this->inc for personnas, so user can make different block/banner (common to several pages) targeted for personas. Actually, being limited to "pure" document make it a hard and long process besause each document have to be unique and cannot be reincluded in another page.

**Comment by Yivan** [comment]
In fact even if the main document (the one called in the url browser) is assigned to the personna, the document included on this same page with $this->inc doesn't display this personnas version. So this is not a personna assignement problem maybe...

**Comment by Yivan** [comment]
Just to know, so it is an intended woking mechanism or a bug ?
If it is intended and personnas don't work with $this->inc could it be tagged as improvment for later/history ?

**Comment by brusch** [comment]
There will be a new concept for targeting / personalization in Pimcore v5 and therefore the entire module will be refactored / redesigned. 
Closed.
