### ISSUE TITLE
boolean select csv import and export not working

### ISSUE THREAD

**Issue by moritzdingerheraeus** [pimcore/pimcore#7003]
# Bug Report

### Expected behavior
When CSV exporting a boolean select which is set to "No" or "empty" corresponding values should be exported.
It should be possible to import "No" and "empty" values via CSV.

### Actual behavior
"No" and "empty" attributes leave an empty cell in a CSV export.
"No" and "empty" cannot be imported via CSV import.

### Steps to reproduce
1. Add a boolean select field to a class.
2. In an object set its value to "no" or "empty"
3. Export a CSV and look up the corresponding cell which will be empty

**Comment by weisswurstkanone** [comment]
Discussion point: what would be the expectation? Do we want to work with the display values ("yes", "no", "empty") or the database values (1, 0, -1) ?

**Comment by moritzdingerheraeus** [comment]
I'd personally prefer "yes", "no", "empty" in excel / CSV files as they should be userfriendly to read.

**Comment by weisswurstkanone** [comment]
Next question would be: use the "hardcoded" values or better take the ones from the class definition.

![image](https://user-images.githubusercontent.com/6142086/91299415-d820ca80-e7a1-11ea-9eb3-b79d9a02cd4c.png)

**Comment by moritzdingerheraeus** [comment]
Probably it's best to use the user-chosen values. Otherwise one could use the checkbox.

**Comment by weisswurstkanone** [comment]
"checkbox" ?

**Comment by moritzdingerheraeus** [comment]
I mean you could use the checkbox field type instead of the boolean select for a simple yes / no. I think the main advantage of the boolean select is that you may define the values yourself so that should be consistent with imports and exports.

**Comment by weisswurstkanone** [comment]
The main value of the boolean select datatype is that it is tri-state (yes, no and empty) whereas the checkbox only had 2 states (checked, unchecked)

**Comment by weisswurstkanone** [comment]
Suggestion:
"1" means yes
"0" means false
"" (= empty string) means empty

**Comment by moritzdingerheraeus** [comment]
Thanks a lot!

**Comment by brusch** [comment]
fixed by #7007
