### ISSUE TITLE
[Asset] Apache Vs. Nginx Configuration

### ISSUE THREAD

**Issue by puecher** [pimcore/pimcore#7008]
# Bug Report
https://github.com/pimcore/skeleton/blob/master/web/.htaccess#L80 is slightly different from https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Nginx_Configuration.html line 107:

`location ~* ^(?!/admin/asset/webdav/)(?!/admin)(.+?)\.((?:css|js)(?:\.map)?|jpe?g|gif|png|svgz?|eps|exe|gz|zip|mp\d|ogg|ogv|webm|pdf|docx?|xlsx?|pptx?)$ {`

### Expected behavior
All files uploaded to Assets should be directly accessible.

### Actual behavior
Nginx still use a whitelist approach and do not open files like txt|xml.

### Steps to reproduce
Upload a txt file to Assets eg. ads.txt in Home directory. On Apache the GET /ads.txt response is 200, on Nginx 404.

**Comment by Thanathros** [comment]
Greetings!

Perhaps something along these lines could be used:
```
location ~* ^(?!/admin/asset/webdav/)(?!/admin)(.+?)\.(?!php) {
    limit_except GET {
        deny all;
    }
    try_files /var/assets$uri $uri =404;
    expires 2w;
    access_log off;
    log_not_found off;
    add_header Cache-Control "public";
}
```
I wouldn't know anything else that would actually require limiting except for php... html perhaps ? I do not believe it is an issue here, though.

I'd appreciate feedback on this. 

Kind Regards,
Enno

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
