### ISSUE TITLE
Failing to load class definition for column config without admin permission or object instance

### ISSUE THREAD

**Issue by nivseb** [pimcore/pimcore#7009]
# Bug Report
The following happens every time, when a user without admin permission, try to import a CSV-File or open the grid options.
I have this issue with version 6.7.1. I think the issue is related to the changes for #6204.  

### Expected behavior
No Error and correct load of the class definition.

### Actual behavior
![image](https://user-images.githubusercontent.com/1013829/91427421-2a272600-e85e-11ea-856f-d5f4572cb168.png)

The log shows the error "Call to a member function getPermissions() on null" in vendor/pimcore/pimcore/models/DataObject/Service.php line 575 

### Steps to reproduce
- open grid options with a non-admin user
or 
- import a csv file with a non-admin user

**Comment by dvesh3** [comment]
fixed by #7010
