### ISSUE TITLE
Override Admin Controller is creating an issue.

### ISSUE THREAD

**Issue by debanshu411** [pimcore/pimcore#7013]
I am using version 6.7.0

I am trying override the UserController in 2 different ways but facing challenges:

Procedure 1.
------------------
Creating the UserController and extends it from the AdminController.

namespace Pepsico\COPBundle\Controller\Admin;

use Pimcore\Bundle\AdminBundle\Controller\AdminController;
use Pimcore\Bundle\AdminBundle\HttpFoundation\JsonResponse;
use Pimcore\Config;
use Pimcore\Controller\EventedControllerInterface;
use Pimcore\Logger;
use Pimcore\Model\DataObject;
use Pimcore\Model\Element;
use Pimcore\Model\User;
use Pimcore\Tool;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Attribute\AttributeBagInterface;
use Symfony\Component\HttpKernel\Event\FilterControllerEvent;
use Symfony\Component\HttpKernel\Event\FilterResponseEvent;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class UserController extends AdminController
{
   /**
     * @Route("/admin/user/update-current-user", name="pimcore_admin_user_updatecurrentuser", methods={"PUT"})
     * @param Request $request
     * @return JsonResponse
     */
   public function updateCurrentUserAction(Request $request)
    {
        .........
    }
}

In this way I am getting the error that the route pimcore_admin_user_updatecurrentuser does not exists.

Procedure 2
------------------

For the same I am providing the zip

[PimcoreModBundle.zip](https://github.com/pimcore/pimcore/files/5140267/PimcoreModBundle.zip)

In this way I have to keep all the methods in the UserController then only its working.

Please let me know the exact way to achieve the same.

**Comment by brusch** [comment]
https://talk.pimcore.org/
https://gitter.im/pimcore/pimcore
