### ISSUE TITLE
Do not allow creating gridconfigs with the same name

### ISSUE THREAD

**Issue by kubaplas** [pimcore/pimcore#7016]
# Bug Report

### Expected behavior
I am able to easily differentiate between two grid configurations.

### Actual behavior
It is possible and quite easy to add gridconfig copy with the same name but different id, which causes situations like this:

### Steps to reproduce
Create a gridconfig as an user and share it globally. As an other user edit this grid and save and share it without changing name. Now we have two gridconfigs on the dropdown list with the same name.

### Possible solution
For gridconfigs created by one user and shared globally, make name field unique.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
