### ISSUE TITLE
Block Data-Type for Objects

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#702]
Similar to document block editable. 
Works only with a subset of data types (input, textarea, checkbox, image(adv), ...)

**Comment by weisswurstkanone** [comment]
release 4.2

**Comment by weisswurstkanone** [comment]
see https://www.pimcore.org/wiki/display/PIMCORE4/Structured+Data+Fields+-+Block

**Comment by kkarkus** [comment]
@weisswurstkanone is there any reason why block can't have nested block field?
