### ISSUE TITLE
Showing backend images using thumbnail configuration is not working as intended

### ISSUE THREAD

**Issue by roland4432** [pimcore/pimcore#7023]
# Bug Report

### Expected behavior

Show images in the edit mode with a dimension optimized for needed size

### Actual behavior

The image, when being passed a thumbnail config, will be shown in the original dimensions. 
The thumbnail config is passed to the admin controller but, since there is no info about the viewport, the thumbnail config will use the config for the default, which _can_ be set to e.g. original dimensions or a fixed width/height, etc resulting in very large picture in the editmode. Since the thumbnail is not even sufficent to determine anything near the needed picture dimensions I would suggest to go for a little tweak to the image tag

### Steps to reproduce

Create brick and use a pimcore_image with a thumbnail configuration

### Code example
```php
# var/config/image-thumbnails.php

    "website" => [
        "items" => [

        ],
        "medias" => [
            "(max-width: 400px)" => [
                [
                    "method" => "scaleByWidth",
                    "arguments" => [
                        "width" => 400,
                        "forceResize" => FALSE
                    ]
                ]
            ],
        ],
        "name" => "website",
        "description" => "",
        "group" => "",
        "format" => "ORIGINAL",
        "quality" => 85,
        "highResolution" => 0.0,
        "preserveColor" => FALSE,
        "preserveMetaData" => FALSE,
        "rasterizeSVG" => FALSE,
        "downloadable" => FALSE,
        "modificationDate" => 1586340211,
        "creationDate" => 1564560094,
        "forcePictureTag" => FALSE,
        "id" => "website"
    ],

```
and a brick with the following setup
```twig
{{ pimcore_image('image', {thumbnail: 'website'}) }}
```

# Feature Request
```js
//bundles/AdminBundle/Resources/public/js/pimcore/document/tags/image.js,
//line: 346
 if (!this.originalDimensions["width"] && !this.originalDimensions["height"]) {
    path = Routing.generate('pimcore_admin_asset_getimagethumbnail', this.getThumbnailConfig({
        'width': this.element.getWidth(),
        'aspectratio': true
    }));
} else if (this.originalDimensions["width"]) {
    path = Routing.generate('pimcore_admin_asset_getimagethumbnail', this.getThumbnailConfig({
        'width': this.originalDimensions["width"],
        'aspectratio': true
    }));
} else if (this.originalDimensions["height"]) {
    path = Routing.generate('pimcore_admin_asset_getimagethumbnail', this.getThumbnailConfig({
        'height': this.originalDimensions["height"],
        'aspectratio': true
    }));
}
else {
    path = Routing.generate('pimcore_admin_asset_getimagethumbnail', this.getThumbnailConfig({
        'width': this.element.getWidth(),
        'aspectratio': true
        'pimcore_editmode': '1'    
    }));
}

var image = document.createElement("img");
image.src = path;
```

## Feature description

This way the image will be as wide as needed in the brick in backend mode only. Frontend of course will render the image correctly with the used thumbnail configuration

**Comment by roland4432** [comment]
@weisswurstkanone could you take a look, since we just fixed the other issue in the this tag (document/tags/image).
Looking forward to creating a PR if wanted/needed

**Comment by msphn** [comment]
For me it never applies any thumbnail in editmode. E.g. setting cover with a fixed size even for default it doesn't apply. In non-editmode it works for me.

**Comment by roland4432** [comment]
Well it does apply the thumbnail but only the default settings of the thumbnail which doesn't help at all :D

**Comment by msphn** [comment]
Hm - default doesnt apply either here. Am I doing something wrong whole time?

**Comment by roland4432** [comment]
I can have a look if you'd like.. all I need is the line of code in your brick template where you implement the image tag and the part of the thumbnail-config.php with your thumbnail

**Comment by msphn** [comment]
Just using default thumbnail with cover, let's say like 200x400, adding two images of different ratios and they won't be same size in editmode when just using:

```twig
{% set image = pimcore_image('foo', {thumbnail: 'mythumb'}) %}

{{ image|raw }}
```

I always use a var and passing it then to either an edit or view template to keep it a little clean. Dunno if it's related to this.

**Comment by roland4432** [comment]
mhh. don't think so.. the object stored in your variable _image_ is a representation of Pimcore\Model\Document\Tag\Image with all its set properties and options. Since this class uses its __toString method to render itself, there shouldn't be any issues regarding your experience with missing thumbnails in backend at all :thinking:

**Comment by Gogtsu** [comment]
anyone found a fix for this?
I'm using 'mobile-first' so my Default is for mobile.
I'd like my backend (editmode) to be 1 to 1 as frontend. Meaning in the backend I'd like a <picture> with all <source> instead of just an <img>

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
