### ISSUE TITLE
Can't extend the UserController in Pimcore Version 6.7

### ISSUE THREAD

**Issue by debanshu411** [pimcore/pimcore#7027]
Expected behavior
Should be able to override the UserController
The same piece of code is running in Pimcore Version 6.2.0 but giving error in 6.7.0

Actual behavior
![Screenshot-from-2020-09-01-16-34-06](https://user-images.githubusercontent.com/69641583/91842645-0d318f00-ec72-11ea-92b6-80da19cda5a6.png)

Steps to reproduce
service.yml
--------------
Pimcore\Bundle\AdminBundle\Controller\Admin\UserController: 
        class: AdvancedFieldsBundle\Controller\UserController
        public: true
        arguments:
            - '@event_dispatcher' 

UserController.php
------------------------
<?php

namespace AdvancedFieldsBundle\Controller;

use Pimcore\Bundle\AdminBundle\Controller\Admin\UserController as BaseUserController;
use Pimcore\Bundle\AdminBundle\Controller\AdminController;
use Pimcore\Controller\EventedControllerInterface;
use Pimcore\Logger;
use Pimcore\Model\DataObject;
use Pimcore\Model\Element;
use Pimcore\Model\User;
use Pimcore\Tool;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Attribute\AttributeBagInterface;
use Symfony\Component\HttpKernel\Event\FilterControllerEvent;
use Symfony\Component\HttpKernel\Event\FilterResponseEvent;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class UserController extends BaseUserController
{
    public function updateCurrentUserAction(Request $request)
    {
      ..............
    }
}

**Comment by brusch** [comment]
https://talk.pimcore.org/
https://gitter.im/pimcore/pimcore
