### ISSUE TITLE
Downloading asset with thumbnail configuration impossible in Pimcore backend

### ISSUE THREAD

**Issue by deltatag** [pimcore/pimcore#7028]
# Bug Report

### Expected behavior
Downloading an asset within Pimcore backend with specific thumbnail configuration is possible.

### Actual behavior
![image](https://user-images.githubusercontent.com/7627410/91850743-55df4d00-ec5e-11ea-8ffc-164794e5c5a2.png)

Selection of thumbnail configuration is not possible due to empty select drop down field:

![image](https://user-images.githubusercontent.com/7627410/91850484-ef5a2f00-ec5d-11ea-80f5-a8e9cc9550b2.png)

### Steps to reproduce
1. Login to Pimcore demo under https://demo.pimcore.fun/admin/?perspective=default
2. Open asset (e.g. https://demo.pimcore.fun/admin/login/deeplink?asset_68_image)
3. On the right side bar try to choose thumbnail configuration for download

**Comment by dvesh3** [comment]
@deltatag It works....we just need to enable thumbnails to be listed in the download list here:
![screenshot-demo pimcore fun-2020 09 01-16_16_16](https://user-images.githubusercontent.com/5137917/91862701-99da4e00-ec6e-11ea-807d-abee9b9cbde6.png)
