### ISSUE TITLE
[Bug] Unable to save object with Video inside a Block 

### ISSUE THREAD

**Issue by AndiKeiser** [pimcore/pimcore#7044]
# Bug Report

### Expected behavior

Save Object without an error

### Actual behavior

After updating Pimcore to version 6.7.1, the object throws an error on saving (No route found for "GET /admin/object/save": Method Not Allowed (Allow: POST, PUT))  if the object already contains a video inside a block.

### Steps to reproduce

1. Create Class with a Video Type inside a Block Type
2. Create new Object with a Youtube Video and save
3. Reload the Object
4. Save
5. Error

**Comment by dvesh3** [comment]
seems related to #6976

**Comment by dvesh3** [comment]
@AndiKeiser can you please check the error again? (I'm not able to reproduce the No route found error) or better try on https://demo.pimcore.fun/admin

**Comment by AndiKeiser** [comment]
@dvesh3 On the pimcore demo I get the error: 503 Service unavailable.

When I save the video first and then try to save the object it works. It just throws an error when I open the object with an existing video and saving it without changing anything.

![Bildschirmfoto 2020-09-03 um 11 01 43](https://user-images.githubusercontent.com/9332971/92094665-feafb880-edd4-11ea-977e-ff01d9d5178a.png)

**Comment by dvesh3** [comment]
@AndiKeiser yes, I'm able to reproduce your issue with latest changes on 6.7

**Comment by jdreesen** [comment]
Why close it then?

**Comment by dvesh3** [comment]
@jdreesen sorry, it was a typo. updated my comment now 😄

**Comment by dvesh3** [comment]
@aarongerig thanks for your efforts! 

I closed this issue for 2 reasons:
 1. Not able to reproduce error mentioned "_No route found for "GET /admin/object/save": Method Not Allowed (Allow: POST, PUT)_"
 2. Error reproducible on demo is related to #6976
