### ISSUE TITLE
Text is not struck through after unpublishing document

### ISSUE THREAD

**Issue by jimmyjammyj** [pimcore/pimcore#7047]
Open published document, click "unpublish" => the document in the tree should be struck through, but it's not

![image](https://media.giphy.com/media/hvpUWn8Yja0fMZVY3L/giphy.gif)

**Comment by jdreesen** [comment]
It is, when you reload the tree, though...

...but you're right, it is for a small amount of time and it should stay this way without having to manually reload the tree.

**Comment by dvesh3** [comment]
regression of #6617
