### ISSUE TITLE
Bug: Exception when locale doesn't exist for Carbon

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#705]
I have a Pimcore document with locale bs_BA. Unfurtunately it failes with the newest Pimcore Version:

`Carbon\Carbon::setLocale(): Failed opening required    '/home/pimcore/vendor/nesbot/carbon/src/Carbon/Lang/bs.php' `

This happens allthough the useZendDate flag is set to TRUE.

I tried to surround the `Carbon\Carbon::setLocale($locale->getLanguage());` in Pimcore's Controller\Action\Frontend with a try/catch but this error cannot be catched. Only deleting this line helps.

**Comment by brusch** [comment]
see 3e67d187c85a619374bce33711987d10cc206d26 

Unfortunately it's not possible to retrieve all supported languages by Carbon, so it's necessary to call this method manually if necessary. -> removed the call entirely out of the code

**Comment by markus-moser** [comment]
thanks
