### ISSUE TITLE
Pimcore 6.7: BC Break in Layout\Text rendering class

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#7055]
# Bug Report
After upgrade to Pimcore 6.7.x I have an error in the table option dialog:
```
Call to a member function getClassId() on null
```

After debug I see, the error came from my renderLayoutText method of an Layout\Text rendering class.

The interface say we get always an **Concrete**, but now we get **null** here.

The code in the documentation should throw also an error now:
https://github.com/pimcore/pimcore/blob/6324fa8ee9e85b83d894e091e561e50aa30291be/doc/Development_Documentation/05_Objects/01_Object_Classes/03_Layout_Elements/01_Dynamic_Text_Labels.md

We can change the PhpDoc of the interface, but its an BC break, right?

Regression from #6204

**Comment by weisswurstkanone** [comment]
Changing the interface so that it also accepts null doesn't make sense for a renderer :-)

**Comment by weisswurstkanone** [comment]
fixed via #7055
