### ISSUE TITLE
Corrupt data when restoring from sql dump

### ISSUE THREAD

**Issue by AustinKobayashi** [pimcore/pimcore#7061]
When restoring from an sql dump, the folder structure for assets and data objects exists, but the server returns a 500 (Internal Server Error) when trying to access an object. Here you can see that the folder structure for data objects has been imported correctly:

![image](https://user-images.githubusercontent.com/14931192/92317196-2492b400-efb3-11ea-84b5-2314386f4cf4.png)

Trying to click on a folder throws an error:

![image](https://user-images.githubusercontent.com/14931192/92317200-35432a00-efb3-11ea-9228-2bbd9a4023dc.png)

`
Timestamp: Sat Sep 05 2020 20:05:35 GMT-0700 (Pacific Daylight Time)
Status: 500 | Internal Server Error
URL: /admin/object/get-folder
Message: Call to a member function getId() on null
Trace: 
in /home/ubuntu/pimcore/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php:812
#0 /home/ubuntu/pimcore/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(769): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->prepareChildClasses(Array)
#1 /home/ubuntu/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(158): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->getFolderAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#2 /home/ubuntu/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#3 /home/ubuntu/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /home/ubuntu/pimcore/web/app.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#5 {main}`

Here is the entry for the "Brands" folder in the "objects" table:

![image](https://user-images.githubusercontent.com/14931192/92317283-e2b63d80-efb3-11ea-9b7c-3e539b1ada71.png)

<hr />

The databub configuration list and the data object class lists are also empty:

![image](https://user-images.githubusercontent.com/14931192/92317216-59067000-efb3-11ea-9bb9-245abc30a707.png)

despite having entries in the database:

![image](https://user-images.githubusercontent.com/14931192/92317219-658ac880-efb3-11ea-8de2-c0a022c1099e.png)

**Comment by brusch** [comment]
https://talk.pimcore.org/ 
https://gitter.im/pimcore/pimcore
