### ISSUE TITLE
Pimcore navigation multiple call bug

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#707]
We have a page with 2 calls of pimcoreNavigation on the same page :

```
<?php
	echo $this->pimcoreNavigation($this->document, $nodeMenu1, 'footer-menu1-')->menu()->setUseTranslator(false)->renderMenu(null, [
		"maxDepth" => 0,
		"ulClass" => ""
	]);
?>
```

And second one with a little further (same code, just different id for the `<ul>`):

```
<?php
	echo $this->pimcoreNavigation($this->document, $nodeMenu1, 'footer-menu1-accordion-')->menu()->setUseTranslator(false)->renderMenu(null, [
		"maxDepth" => 0,
		"ulClass" => ""
	]);
?>
```

When echoing, the second one get the same id than the fisrt one for all link (`<a>` tag).
So for the second menu it render `<a id="menu-footer-menu1-38"...` but it should be `<a id="menu-footer-menu1-accordion-38"...`.
It brings the problem of duplicate id on the page, as soon same menu is rendered two times.

I suspect some cache/registry behind.
I test with the ulClass parameters setted, and it take the good one (no cache problem). So the cache problem seems only to occurs for link (`<a>` tag).

**Comment by brusch** [comment]
Thanks - fixed in build 3887
