### ISSUE TITLE
home page issue

### ISSUE THREAD

**Issue by remyahalza** [pimcore/pimcore#7076]
when i go to 127.0.0.1 - it shows "An exception occurred while executing 'SELECT PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS(?)' with params [1]:

SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION bitnami_pimcore.PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS does not exist"

but 127.0.0.1/admin and all others are working

Is there any way to change my home page to newly created one?

**Comment by brusch** [comment]
https://talk.pimcore.org/
https://gitter.im/pimcore/pimcore
