### ISSUE TITLE
minified_javascript_core admin js is not really minified

### ISSUE THREAD

**Issue by tfarmer00** [pimcore/pimcore#7078]
The call to the Pimcore admin seems to take 3 minutes to download this 3.6MB file. It indicates it should be minified, but I tested the call with curl, and the resulting js file is not minified.

Is there something wrong that's causing this file to be so large and not minified?

/admin/misc/script-proxy?scripts=minified_javascript_core_053a41242ba56be939afa8af61af4a53.js

Version: v6.2.3

**Comment by NiklasBr** [comment]
Looks like you are correct, this:
https://github.com/pimcore/pimcore/blob/1314ea955e06c82c9613619cee9c7e4a00651f1a/bundles/AdminBundle/Resources/views/Admin/Index/index.html.php#L775-L781
Fetches from the array above in the same file, with no minification as far as I can see.

**Comment by brusch** [comment]
This is intentional, minimization doesn't really make it faster, actually the opposite is happening since the minification process takes quite some time. Since this JS is just loaded once, I guess it's not really a problem if it is some kB bigger than minimized.

**Comment by NiklasBr** [comment]
@brusch doesn't it make sense then to not name it "minified/minimized*?

**Comment by brusch** [comment]
@NiklasBr well, yes, it used to be minimized, so I guess this is a leftover - would say this is more a cosmetically thing 😊

**Comment by NiklasBr** [comment]
It's also a documentation thing, because in the lack of comments detailing things like this the only indication given if it is a bug or an intentional effect is the naming of variables and function in code.
