### ISSUE TITLE
[DataObject] Classes - generated Docblock for setter is wrong

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#7079]
## Expected behavior
![image](https://user-images.githubusercontent.com/5137917/92891672-663eb700-f418-11ea-8fcb-71351647033f.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/5137917/92891575-54f5aa80-f418-11ea-9d9d-e4a34199c232.png)

**Comment by kanevbg** [comment]
Seeing these images, I can ask what is the **$fd** unused variable for?

**Comment by jdreesen** [comment]
It is used only in *some* generated code, but it's added every time ;)

**Comment by dvesh3** [comment]
resolved by #7080
