### ISSUE TITLE
[Grid View] JS Error when editing select fields

### ISSUE THREAD

**Issue by emanmagni** [pimcore/pimcore#7083]
# Bug Report

### Expected behavior
After opening a Data Object folder and applying a filter on any field, users should be able to modify select-type fields and continue editing.

### Actual behavior
Reproduced on demo.pimcore.fun
If the grid has enough entries and the user scrolls down to the end of the list, after selecting an option the UI crashes, outputting the following error in the JS console:
```
Uncaught TypeError: Cannot read property 'down' of null
```
In spite of the error, the update on the object gets saved.

### Steps to reproduce

1. On the official demo, open "Product Data" folder in the DataObject custom view
2. Select "Car" type
3. Add the "Country" field to the displayed columns
4. Set "Items per page" to "All"
5. Set a filter on the query result (e.g.: on "Path" column)
6. Start changing the "Country" field from the grid view
7. Scroll down to the last results
8. Edit the Country field and unfocus the select -> error!

![Grid_Bug (2)](https://user-images.githubusercontent.com/56591443/92908187-48784e80-f426-11ea-9e6a-5f81357743cd.gif)

**Comment by dvesh3** [comment]
Closing it as not reproducible anymore on latest version 10.2.1. thanks!
