### ISSUE TITLE
[Improvement] Move deletion code from UserController to User Model

### ISSUE THREAD

**Issue by mkwlf** [pimcore/pimcore#7085]
# Improvement
It's not really a bug, nor a feature - more an improvement:

In #1431 you guys fixed the issue 
> User-role relation should be removed when role gets deleted.

This is done in the `UserController` but imho it should be in the `AbstractUsers` `delete` method. 

When a user gets deleted from within the code, the user role relations are still kept. Also this would align with the Single Responsiblity Priciple, since the model is responsible for correct (and complete) deletion.

edit: same goes with deleting a `User\Role\Folder` - the deletion is all done within the Controller.
I'd consider a controller not responsible for the actual deletion - it just handles the request and triggers the deletion code in the model.

**Comment by dvesh3** [comment]
I would still consider it an API bug.

**Comment by dvesh3** [comment]
resolved by #7109
