### ISSUE TITLE
[Improvement] UI: In grids - sort and filter by relation fields

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#7086]
Look at the Pimcore demo: https://demo.pimcore.fun/admin/login?perspective=PIM

Open folder Cars->mercedes.

![image](https://user-images.githubusercontent.com/11477130/92930314-90a96800-f44a-11ea-87d8-95e99adcdbe6.png)

Now I'd like to see only the objects that are not having "body style" or have a specific one. In the same manner we can have a need to filter by a field of type "many-to-many relations". Even by advanced many-to-many relational field (with metadata) which would be great if can specify the metadata to filter too. Filtering by relations count for many-to-many fields can be very useful too. Sorting can be implemented too, eg: sort by count of relations ASC/DESC, sort by target object ID ASC/DESC.

**Comment by kubaplas** [comment]
@brusch are there any plans for this feature?

**Comment by fszenborn** [comment]
I have implemented filter by relation for pimcore 6.9.6 and I am going to prepare Pull request to Pimcore X soon.
My approach is to select relations to be filtered by re-using batch edit window to apply filters.
@brusch @fashxp 
Could someone review/test my changes and leave some feedback or suggestions? 
My fork is here: https://github.com/pimcore/pimcore/compare/v6.9.6...DivanteLtd:divante-filter-by-relation?expand=1

Here is the quick demo of the functionality:
https://user-images.githubusercontent.com/54931392/123623624-f6b28080-d80d-11eb-8274-8c091e409235.mp4

Supported field types are:
- one to many
- many to many
- many to many object
- advanced many to many
- advanced many to many object
- image
- advanced image

**Comment by dvesh3** [comment]
@fszenborn implementation looks good. please go ahead with PR for Pimcore X. so that we can review it thoroughly. great work 👍

**Comment by C-R-W** [comment]
Hi there, any news on this?

**Comment by fszenborn** [comment]
Please check https://github.com/pimcore/pimcore/pull/10022

**Comment by brusch** [comment]
I think this can be closed then, right 😉

**Comment by kanevbg** [comment]
#10022 implemented one-to-one relation filtering, here is proposed much more:
- sorting of one-to-one relation
- one-to-many relation - filter & sort
- one-to-many relation with metadata - filter & sort

What is better to do - separated issues with suggested functionality details or one well formatted description here for reopen of that issue?
