### ISSUE TITLE
[improvement] support Symfony workflow "metadata" in Pimcore workflows

### ISSUE THREAD

**Issue by FredoVelcro-zz** [pimcore/pimcore#7089]
Hello,

With Symfony Workflow component >=4.1, we have possibility to add metadata in workflows :
https://symfony.com/doc/current/workflow.html#storing-metadata

But apparently it is not supported in Pimcore worflows layer/overrides.
Why ? Do you plan to integrate this feature soon ? Would be great.
Thanks you
Best regards,
Fred

**Comment by brusch** [comment]
Would be a topic for v7 when we get rid of Symfony 3.4
But you can already submit PRs for v7 😉

**Comment by faiyazalampim** [comment]
this issue still exists in v10.5.3

**Comment by faiyazalam** [comment]
this issue still exists in v10.5.3

**Comment by fashxp** [comment]
PRs are still welcome ;-)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
