### ISSUE TITLE
admin panel interface

### ISSUE THREAD

**Issue by remyahalza** [pimcore/pimcore#7090]
![image](https://user-images.githubusercontent.com/68893691/93011099-4f2cd000-f5a4-11ea-9d61-b2460f7da14e.png)
 Is it possible to change these?

**Comment by remyahalza** [comment]
welcome to pimcore, footer text and black color

**Comment by brusch** [comment]
@remyahalza this is **NOT** the right place for asking questions. 
Use: 
https://talk.pimcore.org/
https://gitter.im/pimcore/pimcore
