### ISSUE TITLE
Counting the redirects

### ISSUE THREAD

**Issue by fabiofabbrucci** [pimcore/pimcore#7103]
Try to immagine a list of 10 to 1000 redirects and you need to answer the question: "which redirects of these I need? Which ones are alive"

It would be interesting to count the number of occurrences. In this way is easier to maintain this liquid list.
And if we could refresh this counter it would be even better!!!
For a marketing manager it would be great to look at this number.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
