### ISSUE TITLE
Improvement No auto refresh on filter but apply button in grid view

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#7105]
Hi,

When you want to set multiple filteroptions the screen is refreshing everytime after setting an option.

For example, you want to filter on three brands, you have to click alot between all the fields. Also when you typ a text in a free field the screen is updating too fast.

Perhaps it's better to add a button to the filter to apply the filter manually?

**Comment by Hbitvof** [comment]
Anyone?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
