### ISSUE TITLE
Block definitions should not return the layout definitions

### ISSUE THREAD

**Issue by Karthi96** [pimcore/pimcore#7106]
### Expected behavior
Block definition should not return layout definitions when we get the definition programmatically. Expecting the same behavior of DataObject

### Actual behavior
Currently, Block is returning the layout definitions.

### Steps to reproduce
1. create a block under DataObjects.
2. create few fields and make some fields under some layout like FieldSet, FieldContainer, ..etc
3. Save the class and try to get the definition of block. 
4. It will return the layout definition which is wrong. we should not get the layout definition. we are not getting the layout definition in DataObject why block behavior is completely different in terms of definitions.

### Code example 
```php
$blockObject = $object->getBlockName();
$blockDefinitions=$blockObject->getChilds();

```

**Comment by weisswurstkanone** [comment]
I guess what you are looking for is the following method:

getFieldDefinitions
