### ISSUE TITLE
Custom Report Bar Chart : Impossible to edit legends

### ISSUE THREAD

**Issue by zeor59** [pimcore/pimcore#7110]
# Bug Report

### Expected behavior

Set a custom legend to a custom report which use a Bar Chart
### Actual behavior

cannot configure the legends of the chart

### Steps to reproduce

- Create a custom report, configure chart settings. 

- No place to configure the legends (ext-chart-series-bar-1 etc displayed)

![custom_report_bo](https://user-images.githubusercontent.com/6772486/93231434-05e1a980-f779-11ea-82af-d253938a3ce7.png)

![custom_report_legend](https://user-images.githubusercontent.com/6772486/93231438-067a4000-f779-11ea-97e7-e19c59068a05.png)

Using Pimcore 6.7.1

Thanks

**Comment by zeor59** [comment]
up

**Comment by fashxp** [comment]
we would love to merge a PR for that, thanks.

**Comment by fashxp** [comment]
should be fixed via https://github.com/pimcore/pimcore/pull/11170
