### ISSUE TITLE
Unpublishing root document causing errors preventing to load the admin

### ISSUE THREAD

**Issue by msphn** [pimcore/pimcore#7113]
When disabling the root document of the cms, the backend can't be opened anymore. Only way to fix it is to manually publish it using the dabase and clearing the cache.

<img width="586" alt="Screenshot 2020-09-16 at 09 36 56" src="https://user-images.githubusercontent.com/579227/93306593-623bdc00-f800-11ea-874f-74f06ac564f0.png">

This can be reproduced on pimcore demo.

**Comment by brusch** [comment]
Fixed by 6a638724bd29f777658086c502085a8079c01e9e
