### ISSUE TITLE
Editable setting for links

### ISSUE THREAD

**Issue by florian25686** [pimcore/pimcore#7114]
# Bug Report
I've created a user with limited rights to a document space and settings
<img width="1992" alt="Bildschirmfoto 2020-09-16 um 11 07 21" src="https://user-images.githubusercontent.com/15780280/93316989-2e1ae800-f80d-11ea-89d6-7fcaf1000c90.png">
<img width="512" alt="Bildschirmfoto 2020-09-16 um 11 07 14" src="https://user-images.githubusercontent.com/15780280/93317006-3410c900-f80d-11ea-93c5-dc02e0626b78.png">

The user is able to see and change the `path` for the link `en`. He is not able to save this, due to a missing save button.
<img width="2554" alt="Bildschirmfoto 2020-09-16 um 11 07 05" src="https://user-images.githubusercontent.com/15780280/93317136-64586780-f80d-11ea-837e-34076286d865.png">

### Expected behavior
The user is not able to change the path for this link

### Actual behavior
The user can drag 'n' drop or change the link

### Steps to reproduce
Create a user with the mentioned rights/roles and log in. Click on the `en`-link and change the `path`

# Feature Request
## Feature description
Prevent user from change the path if he doesn't have the rights.

**Comment by dvesh3** [comment]
> The user can drag 'n' drop or change the link

but cannot save the changes...isn't it enough?

**Comment by florian25686** [comment]
The use should not be able to drag 'n' drop the first place if there is no way to save it in my opinion

**Comment by brusch** [comment]
Ok, this sounds more cosmetic to me, not really a bug.

**Comment by florian25686** [comment]
Should be fixed anyways and might be just a smaller fix I assume

**Comment by brusch** [comment]
Solved by #7130
