### ISSUE TITLE
[Document] Areablocks should not trigger a reload

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#7119]
# Feature Request

## Feature description

We are getting a some complaints from clients that editing Pimcore Editables (https://pimcore.com/docs/6.x/Development_Documentation/Documents/Editables/index.html) is basically a great thing but that it is clumsy in comparison to other website builders especially because of the reason that we have only two options:

- Reloading the whole site within the Frame in editmode
- Not reloading at all - which means that the changes to a certain brick are not visible until a reload happens

## Example

Lets have a look at the select editable for example:

https://pimcore.com/docs/6.x/Development_Documentation/Documents/Editables/Select.html

It has the following configuration possibility:

reload | bool | Set true to reload the page in editmode after selecting an item

It would be great to have an option 

reloadEditable | bool | Set true to reload the editable

Most probably this is a little bit harder to implement because one would have to be able to fetch the contents of the changed brick via Ajax and replace the corresponding HTML of the Brick via JavaScript. Nevertheless I want to suggest it here as i guess this would be a major usability improvement. It would also be nice for adding and removing bricks.

**Comment by brusch** [comment]
But what should be refreshed then? Just the select? For what use? 🤔

**Comment by Blackbam** [comment]
@brusch Not just the select but the whole brick via ajax (instead of the whole page). 

Brick rendered HTML is usually wrapped like

```
<div class="pimcore_area_heading pimcore_area_content ">
<!-- .... all the editables and output .... --->
 </div>
```

So what I mean is fetch the rendered brick and replace the content of the "pimcore_area_content" element. 

The use is pretty clear: Instead of reloading after changing e.g. a select only this part within the document is re-rendered, which results in a way smoother editing experience.

**Comment by brusch** [comment]
Ok, that's something different ... then you'd have to call the option `refreshBrick` or so ... 
But anyway, since the editable doesn't have the context information this could be quite challenging. 
For now this is not on our roadmap, but if someone has the time to play around with that, we'd be happy to merge a PR for that 😊
