### ISSUE TITLE
Opening grid options on object grid as non admin throws getPermission() on null error 

### ISSUE THREAD

**Issue by wpeisert** [pimcore/pimcore#7129]
# Bug Report

### Expected behavior
Opens window "Grid Options" with the possibility to edit grid fields.
### Actual behavior
There is error window: "Call to a member function getPermissions() on null"
Details button shows:
"Status: 500 | Internal Server Error
URL: /admin/class/get-class-definition-for-column-config
Message: Call to a member function getPermissions() on null"

In log: Call to a member function getPermissions() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getPermissions() on null at /var/www/vendor/pimcore/pimcore/models/DataObject/Service.php:575)"

This comes from Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\ClassController::getClassDefinitionForColumnConfigAction() line 978.

**Then window "Grid Options" does not contain any class attributes**.
### Steps to reproduce
1. Create non admin user, give him permissions to objects and to objects area.
2. Create class (I'm not sure what the class should contain, but in my case the problem appears with: localized fields) like that: 
![pimcore](https://user-images.githubusercontent.com/15231891/93456790-748c4780-f8de-11ea-9802-91b4e11fabc4.png)
3. As non admin user: Click on folder containing objects.
4. As non admin user:  Click "Grid options" button.
### Code example
```php
// your code
```

# Feature Request

**Comment by dvesh3** [comment]
please see https://github.com/pimcore/pimcore/issues/6217
