### ISSUE TITLE
[DataObject] Missing admin translations on object relations

### ISSUE THREAD

**Issue by tvedderTC** [pimcore/pimcore#7132]
# Bug Report

### Expected behavior
![Excepted behvaiour](https://user-images.githubusercontent.com/71321237/93472732-5f6ee300-f8f5-11ea-80dc-e48f098ce575.png)

That the ~column-names and~ select/multiselect values are translated as in the object editing.

### Actual behavior
![Actual behvaiour](https://user-images.githubusercontent.com/71321237/93472740-6269d380-f8f5-11ea-96bb-92437595dfe9.jpg)

My bad: The column title is translated correctly, i just forgot the translation in the admin translation.

### Steps to reproduce
![Steps to repoduce 1](https://user-images.githubusercontent.com/71321237/93472919-a52bab80-f8f5-11ea-9c0a-f81854c7e816.png)

![Steps to repoduce 2](https://user-images.githubusercontent.com/71321237/93472938-ab218c80-f8f5-11ea-9129-dc397ebe2dc4.png)

**Comment by brusch** [comment]
Fixed by #7133
