### ISSUE TITLE
[Object Grid] Missing field name and values when edit related fields from/in grid view table popup

### ISSUE THREAD

**Issue by Fahl-Design** [pimcore/pimcore#7140]
# Bug Report

### Expected behavior
- I open the grid view https://demo.pimcore.fun/admin/login/deeplink?object_94_folder
- I add the "Categories" relation field to the table
- I double-click the category field in row (e.g id: 98)  to edit the categories
- I will see the category path and other fields selected in object definition

### Actual behavior
![image](https://user-images.githubusercontent.com/6690962/93618698-eb593b80-f9d7-11ea-8f0f-9bda3fd729e8.png)

![image](https://user-images.githubusercontent.com/6690962/93618647-d8466b80-f9d7-11ea-9b6b-50e38ce9def9.png)

![image](https://user-images.githubusercontent.com/6690962/93618844-1cd20700-f9d8-11ea-8425-bb0ee4de4323.png)

### Steps to reproduce
- see "Expected behavior"

**Comment by weisswurstkanone** [comment]
regression of https://github.com/pimcore/pimcore/pull/7056

**Comment by dvesh3** [comment]
Resolved by #7156
