### ISSUE TITLE
Unable to update the version note for assets programmatically

### ISSUE THREAD

**Issue by Karthi96** [pimcore/pimcore#7141]
# Bug Report

### Expected behavior
As a user, i should be able to update the version note for assets.

### Actual behavior
Unable to update the version note for assets via the program. I can able to update for objects but not for assets

### Code example
```php
 $assetObject->save(["versionNote" => "Adding property"]);
```
FYI : I'm using pimcore 6.4.2

**Comment by dvesh3** [comment]
Closing as it works on master...thanks!
![image](https://user-images.githubusercontent.com/5137917/93749340-0efbcc00-fbfa-11ea-89a1-adc4d9248a56.png)
![image](https://user-images.githubusercontent.com/5137917/93749421-318de500-fbfa-11ea-8309-42e730baca65.png)
