### ISSUE TITLE
Add full support for ogg files within assets and subtype definition for bricks

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#7145]
# Feature Request

Building a brick which basically represents the HTML Audio Element (https://www.w3schools.com/html/html5_audio.asp) I have noticed that .mp3 files and .wav files within the Pimcore admin interface are having a preview and a custom metadata tab, while .ogg files do not have this. 

Furthermore the type within the info is **unknown (MIME: application/ogg)** which is also written into the Deeplink. 

In my test there was also no possibility to check if an ogg file is audio or video. They all have the MIME type **application/ogg** but I guess there should be a possibility within pimcore to differentiate this, though I am not sure if the files themselves have saved this _deprecated_ MIME type (https://gingertech.net/2008/09/05/new-ogg-mime-types-ratified/).

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
