### ISSUE TITLE
Asset save with argument runs into a infintie loop

### ISSUE THREAD

**Issue by Karthi96** [pimcore/pimcore#7146]
# Bug Report

### Expected behavior
As a user, I should be able to hook the asset event and able to update the asset with an argument.

### Actual behavior
When I tried to hook an asset event and update the object by passing some version notes to it and the program went into an infinite loop. I can able to reproduce this issue on the master branch. 

### Steps to reproduce
1. Add the postupdate asset event in service.yml
2. In the method of the hook, call to save with argument. 

### Code example

Service.yml
```php
AppBundle\EventListener\AssetListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.asset.postUpdate, method: onPostUpdateAsset}
```

method: onPostUpdateAsset logic
```php
public function onPostUpdateAsset(ElementEventInterface $e)
    {
        if (($e instanceof AssetEvent) && ($e->getAsset()->getType() != "folder") && $e->getArguments() == null ) {
            $assetObj = $e->getAsset();
            $assetObj->save(['versionNote' => "Adding property"]);
        }
    }
```

**Comment by Karthi96** [comment]
@dvesh3 could mind have a look at this, please?

**Comment by dvesh3** [comment]
please use official forum for queries https://talk.pimcore.org/
