### ISSUE TITLE
Objects - calculatedValue - contextinformation when showing data in grid is not set correctly

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#715]
there is a difference in context information for getDataForEditmode when loading object in object editor and object grid.

**Comment by weisswurstkanone** [comment]
What is the expectation here ?

**Comment by fashxp** [comment]
it should be the same context information as in object editor :) 

example I found in combination with localized fields > language information is missing in grid:

object editor: 
![image](https://cloud.githubusercontent.com/assets/8792145/20134527/fe6d3f96-a66b-11e6-82f6-2804e2852090.png)

grid: 
![image](https://cloud.githubusercontent.com/assets/8792145/20134531/01de0688-a66c-11e6-817f-e2f23c10569a.png)

**Comment by weisswurstkanone** [comment]
build 3999.

Note that you have to save your class once again in order to generate the required getter code.
