### ISSUE TITLE
the white background of the image disappears

### ISSUE THREAD

**Issue by dev-pim** [pimcore/pimcore#7151]
# Bug Report

### Expected behavior
the loaded image with a white background is displayed correctly
### Actual behavior
when loading a image, part of the white background disappears
### Steps to reproduce
upload image with a white background to assets

image for uploud
![Passion1](https://user-images.githubusercontent.com/66632919/93847699-ae7f9400-fcb8-11ea-8877-bac01d545599.jpg)

behavior on demo.pimcore.fun (6.7.2+)
![2020-09-22_09-48](https://user-images.githubusercontent.com/66632919/93847781-f2729900-fcb8-11ea-950d-6760fe33f888.png)

behavior on localhost (6.7.1)
![2020-09-22_09-52](https://user-images.githubusercontent.com/66632919/93847891-5006e580-fcb9-11ea-9bdb-d44bbdb34164.png)
that is, this problem was reproduced back in 6.7.1 and was PARTIALLY solved in 6.7.2
unfortunately could not find the corresponding pull request(

**Comment by dvesh3** [comment]
With v6.8.0 it will be possible to disable the auto clipping of image thumbnails. please see https://github.com/pimcore/pimcore/pull/6950/files#diff-0464add0c5e91927685524cfa8902733
