### ISSUE TITLE
Slider cannot be a mandatory field

### ISSUE THREAD

**Issue by d3xter** [pimcore/pimcore#7152]
### Expected behavior
It should be possible to set a Slider as mandatory.

### Actual behavior
_Mandatory field_ checkbox is disabled for Sliders

![grafik](https://user-images.githubusercontent.com/159784/93863228-8ea19d80-fcc3-11ea-9011-c06d65fbfc92.png)

**Comment by dvesh3** [comment]
Agree! ..It is possible to empty Slider value since v6.6.2 https://github.com/pimcore/pimcore/pull/6166

**Comment by dvesh3** [comment]
resolved by #7153
