### ISSUE TITLE
[DataObject Grid] Undo batch action

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#7155]
# Feature Request

## Feature description
Sometimes batch actions can go wrong - you might want to add a relation but select to "set" the relation instead. At the moment you'd have to go through all the batched objects and go back one version manually.
It'd be great to have some "undo" function in this case. We could save all dataobject IDs for example and go back one version foreach of these to undo the batch changes.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
