### ISSUE TITLE
A Geographic Point being mandatory isn't enforced

### ISSUE THREAD

**Issue by d3xter** [pimcore/pimcore#7162]
### Expected behavior

Setting a Data Component which has the Input Type "Geographic Point" to mandatory should enforce
that the Backend User has actually selected a Location/Lat&Long are not empty

### Actual behavior

A Data Object with a mandatory Geographic Point can be saved even when Latitude and Longitude is empty

![grafik](https://user-images.githubusercontent.com/159784/94007951-79e80700-fda2-11ea-9b4d-31fdb1c12d2b.png)

**Comment by weisswurstkanone** [comment]
Empty mandatory fields can always be saved but not published.
I suspect, that your object is not published, right? At least the screenshot gives me that impression.

**Comment by d3xter** [comment]
You are right, sorry for the distraction
