### ISSUE TITLE
Deleting application_logs_archive tables after some configured time

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#7163]
Currently application_logs get archived to application_logs_archive_MM_YYYY. They never get deleted and thus bloat the size of database dumps. Of course you could delete those if you customize the call to mysqldump or have any other backup strategy. But I wonder if it is really necessary in all cases to be able to see application logs from 2 years ago for example.
What do you think of deleting those tables after a configurable time?

**Comment by dpfaffenbauer** [comment]
YES, please. I don't use application_logs at all and I don't like having empty archive tables....

**Comment by BlackbitNeueMedien** [comment]
Empty application_logs_archive tables should not be a problem anymore since ef10fab722353bde18d5a401657eb7805434a64b

**Comment by dpfaffenbauer** [comment]
oh good, thanks. Missed that PR.

**Comment by brusch** [comment]
@BlackbitNeueMedien yes, I guess a configurable cleanup with default values (maybe 8 month or so?) would definitely make sense.
