### ISSUE TITLE
exported XLIFF wraps every element of the last document in a CDATA section

### ISSUE THREAD

**Issue by thgross** [pimcore/pimcore#7165]
# Bug Report

This is a strange bug, and it was quite difficult to figure out what really happens. **Unfortunately, this behaviour leads to several problems with translation tools and services.**

### Expected behavior

pimcore exports all data without CDATA-sections.

### Actual behavior

pimcore exports all data without CDATA-sections except for the last document of the exported element, where everything is wrapped in CDATA-sections.

### Steps to reproduce

1. log into https://demo.pimcore.fun/admin
1. open "Tools" / "Translations" / "XLIFF Export/Import"
1. from "Documents" / "en", drag "Magazine" to "Elements to Export" and klick "Export" to Download the xliff-file
1. open the exported file in any texteditor.
1. the file should contain 8 `<file>`-tags: 1 for the document "Magazine" and 7 for the child documents.

If you look at the xml-code inside the xliff-file, you can see that none of the `<file>`-tags contains any CDATA-sections except for the last `<file>`-tag, where everything is wrapped in CDATA-sections.

**Comment by thgross** [comment]
Some more details:

It looks like every element in the xliff-file was supposed to be wrapped in CDATA-sections, see https://github.com/pimcore/pimcore/blob/1efe383763df52f8aeedfb17d461f092184f4781/lib/Translation/Escaper/Xliff12Escaper.php#L26 I don't know why that is, because it usually is not necessary.

However, after exporting one document, the temporary xliff-file is reloaded again, purging all existing CDATA-wrappers:
https://github.com/pimcore/pimcore/blob/1efe383763df52f8aeedfb17d461f092184f4781/lib/Translation/ExportService/Exporter/Xliff12Exporter.php#L48

After loading the xliff-file like this, the following document is processed and appended to the file, wrapping each translation element in CDATA-sections.

So after the last processed document, only the contents of the last document still contains CDATA-sections, while each existing CDATA-section fron the other documents have been purged by the `simplexml_load_file()`-command.

The forced CDATA-wrapping of elements should be removed altogether; instead, the content should be properly escaped, for example by `htmlspecialchars()`. Or even better, PHPs [DOMDocument](https://www.php.net/manual/de/class.domdocument.php) could be used to create the xliff-file.

It is also recommended by the OASIS Standard to **not** use CDATA-sections: https://docs.oasis-open.org/xliff/v1.2/xliff-profile-html/xliff-profile-html-1.2-cd02.html#General_CDATA

**Comment by dvesh3** [comment]
Fixed by #8361
