### ISSUE TITLE
[Ecommerce][Productindex] elasticsearch preparation queue children do not update if parent is not in index

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#7168]
In previous Pimcore versions the product index mechanism did always reset the preparation queue for all children if they are in the index.

In one of the last releases this if was added (seems like for performance reasons):
https://github.com/pimcore/pimcore/blob/master/bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php#L361

Now the children are only updated if the parent is in the index too. I dont't think that this is a good idea as there are many constellations where this might happen.

**Comment by fashxp** [comment]
true, `fillupPreparationQueue` should be moved.

**Comment by brusch** [comment]
Fixed by #7179
