### ISSUE TITLE
[Improvement] Possibility to configure whether a thumbnail should be optimized or not (filesize)

### ISSUE THREAD

**Issue by skochTC** [pimcore/pimcore#7175]
# Feature Request
## Feature description

If the context of the image in the frontend requires transparency, image thumbnails are often created in PNG format. However, PNG images have the big disadvantage that they are disproportionately large compared to JPG or even more modern image formats. These too large image thumbnails cause a bad performance of the frontend that integrates the images - especially in the mobile area.
The standard PNG thumbnails created by Pimcore still have a high potential of optimizing the file size. By using the command-line utility "pngquant" the file size can be reduced, which has optically not very visible quality losses (see https://pngquant.org/). It is possible to reduce the file size by >50% while keeping the transparency.

The idea is to integrate a postprocessing of PNG thumbnails, which can be activated in the thumbnail definition in Pimcore by an option (default off). If this is activated, the PNG previously created by Imagemagick will be optimized later using pngquant. The performance advantage of a website that uses several transparent PNGs is enormous.

@dvesh3 / Pimcore and Community 🚀 
Please give us feedback about it, then we will implement it 😉

**Comment by brusch** [comment]
@skochTC sounds good and should be pretty easy to implement. 
I'd just add an additional config here: 
![image](https://user-images.githubusercontent.com/142037/95965027-bfc84600-0e09-11eb-8ca2-9ad1f4227fb8.png)

and if this is set, just add the generated thumbnail image to the image optimizer queue. 
If the target format is "Auto" this option has no effect as there the image optimization is forced anyway. 

Looking forward to you PR.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
