### ISSUE TITLE
Improvement: option to hide arrow up and down in number field

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#7180]
Hi,

Is it possible to add an option to remove the arrows in the number field?

![image](https://user-images.githubusercontent.com/41229269/94395707-8bddf700-0160-11eb-8211-9e0da2b304fb.png)

 This can cause problems in Grid view where the screen is small and you click on the arrows by accident.

**Comment by NiklasBr** [comment]
Have you tried [injecting an admin CSS](https://pimcore.com/docs/6.x/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/Loading_Admin_UI_Assets.html) and then [hide it like this](https://stackoverflow.com/questions/3790935/can-i-hide-the-html5-number-input-s-spin-box)?

**Comment by Hbitvof** [comment]
Hi, for some fields we like to keep these arrows. Solving this with css is a solution but I prefer an option to show/hide these arrows.

**Comment by NiklasBr** [comment]
They have distinct HTML `id`' and `name` attributes, that should help, right?

**Comment by Hbitvof** [comment]
Css is not the problem but I have no idea how to inject this in the backend. I am not a Symphony expert and don't understand the instructions in [this url](https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/Loading_Admin_UI_Assets.html). Can you please shorly tell what I need to do?

**Comment by NiklasBr** [comment]
[This page](https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/index.html) is a better start. Follow the step *Generating Pimcore Bundles*.

Then follow this the *General* section on [Plugin Backend UI](https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/Plugin_Backend_UI.html) (but you can leave out the JS parts).

You need to create the file with the class `YourBundleName\EventListener\PimcoreAdminListener`(.php) to add the code into.

**Comment by Hbitvof** [comment]
@NiklasBr Thanks for your explanation. Now I know what to do. But there is another issue, the numberfield ID's are random generated every time you load the page. For this reason I am unable to remove the arrows on specific fields. Is there a solution for this?

**Comment by NiklasBr** [comment]
I didn't think they would change. Yeah, in that case it suddenly becomes very hard since the only other distinct selectors are hard to reach.

**Comment by Hbitvof** [comment]
@NiklasBr True :). 

So @Pimcore developers the question, is it possible to add this "feature"?

**Comment by brusch** [comment]
@Hbitvof should be possible by using the `hideTrigger` config: 
https://docs.sencha.com/extjs/6.0.2/classic/Ext.form.field.Number.html#cfg-hideTrigger 
You can create us a PR for that 😊

**Comment by Hbitvof** [comment]
@brusch Can you please make a PR for this?

**Comment by Hbitvof** [comment]
@brusch can you please take a look at this? I don't know what to do further.

**Comment by NiklasBr** [comment]
@Hbitvof This might help solve it for you https://github.com/pimcore/pimcore/pull/9919

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
