### ISSUE TITLE
[Data Object] Modifing an object having a fieldcollection with inside a localized fields delete the localized values

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#7192]
Hello,

This is a critical issue as it impact several Pimcore versions (at least from 6.6.4 to 6.7.x-dev) and **lead to lost datas silently**. It could impact many project in production.

It is easily reproducible on online demo, and this is a pretty classic setup on multilingual project.

Create an object with a field collection:

![image](https://user-images.githubusercontent.com/9025839/94551404-9928dd80-0255-11eb-818c-b934800c9945.png)

Create a field collection:

![image](https://user-images.githubusercontent.com/9025839/94551432-a5ad3600-0255-11eb-8393-e0f291616c59.png)

Create an instance of this object, and fill some values and save&publish:

![image](https://user-images.githubusercontent.com/9025839/94551524-c4abc800-0255-11eb-80c3-60888fcfe6e4.png)

Close and reopen the object, and change the value in the text field, save&publish, and reload the object, **the multihref in localized field has been emptied**:

![image](https://user-images.githubusercontent.com/9025839/94551641-f4f36680-0255-11eb-9641-ddc4b249667a.png)

This affect production project for now (we are on 6.6.4 on production projects) and last Pimcore version.

Thanks.

Note : we encountered the same problem with localized fields inside an object brick for information. After investigation, it seems only one table in the database get updated, the other not (localized fields are in two table in the database in case of them inside an object brick). Maybe can be a hint for this issue.

**Comment by brusch** [comment]
Fixed by #7197

**Comment by weisswurstkanone** [comment]
@Yivan , I believe there was a major change via #6612  which was done after 6.6.4

**Comment by Yivan** [comment]
Thanks very much @weisswurstkanone for your answer on this subject.

I just try, the only line changing is the 160 : https://github.com/pimcore/pimcore/pull/6612/files#diff-16f9a3cbf890a5bd4d3ba500c90e2478R160
(the just below part was already modified from the code of this new commit from this issue, I have take all the if block of this fix).

Sadly problem is always here with this second commit backported : (
I tried disably lazyloading, change nothing.

(a strange things I noted, if I don't reload the object, we can modify the "mytext" field (in my original exemple) as much as we want and save as much as we want, and no data is lost. But if object is reloaded, data is lost if we change mytext. It seems like this is an extjs / dirty fields problem, but in this commit of this issue I see only PHP fix, no JS fix. Maybe my remark is not usefull but i wanted to tell this experience.)

**I will try locally updating our project from 6.6.4 to last Pimcore stable version and apply this fix to check it works well on our side.**

If you have any clues about others commit which could be needed to make it work on 6.6.4, i am very interested ! (and for people reading this issue and wanting to backport the fix in production)

Thanks again.

**Comment by Yivan** [comment]
Here are the result of my local test:
- I updated to the last stable and backported the fix : don't work : (
- I updated to `6.7.x-dev` which has the fix merged : don't work too : (
- And finaly just tested on the online Pimcore demo (just 10 min ago before writing this issue so I think it is uptodated with the fix) : don't work ...

Are you sure this fix is ok ? **If not could this issue be reopened please.**

Here you will find the two class (object and fieldcollection) from my exemple and which don't work:

[test.zip](https://github.com/pimcore/pimcore/files/5314692/test.zip)

Thanks.

**Comment by brusch** [comment]
Fixed by #7222

**Comment by Yivan** [comment]
Thanks a lot ! I confirm, the fix works fine now.
