### ISSUE TITLE
Object with gallery inside localized field inside block throws an error when saving

### ISSUE THREAD

**Issue by Myrmidonut** [pimcore/pimcore#7208]
# Bug Report

### Expected behavior
Saving an object with a populated gallery inside a localized field inside a block is possible. Tested on Pimcore 6.7.2.

Using an image instead of gallery works by the way.

### Actual behavior
The following error shows up when saving:
"Cannot use object of type Pimcore\Model\DataObject\Data\ImageGallery as array"

Emptying the gallery is not enough to be able to save the object, you have to remove the whole block first. Keeping the gallery empty lets you save the object, but once there is or was an image in the gallery the block is unusable.

### Steps to reproduce
Create a class with the following setup:
block
-- localized field
-- -- gallery

Create an object with that class, add a block with an image in the gallery and save the object.

### Related issue
A similiar issue was fixed in August 2018 (https://github.com/pimcore/pimcore/issues/3211) but it didn't involve a localized field.

**Comment by dvesh3** [comment]
Resolved by #7209

**Comment by Myrmidonut** [comment]
Thanks for fixing it so quickly! 👍
