### ISSUE TITLE
Non-Mandatory number field with min setting does prevent object saving

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#722]
# Bug Report

Create a number field with a min and max value but without the mandatory checkbox checked.

I used this:

`
					{
						"fieldtype":"numeric",
						"width":"",
						"defaultValue":null,
						"queryColumnType":"double",
						"columnType":"double",
						"phpdocType":"float",
						"integer":true,
						"unsigned":true,
						"minValue":1,
						"maxValue":99999,
						"decimalPrecision":null,
						"name":"postal",
						"title":"Postleitzahl",
						"tooltip":"",
						"mandatory":false,
						"noteditable":false,
						"index":false,
						"locked":false,
						"style":"",
						"permissions":null,
						"datatype":"data",
						"relationType":false,
						"invisible":false,
						"visibleGridView":false,
						"visibleSearch":false
					},
`

Create a new object and fill some fields but leave the numeric postal field empty. Try to save it.

### Expected behavior 

Object is being saved.

### Actual behavior  

Pimcore validator does throw an error 

> [Pimcore\Model\Element\ValidationException]  Value in field [ postal ] is not at least 1 fieldname=postal

The error itself is correct but I believe it should still save the object because the field postal is not mandatory.

Tested with official pimcore version 4.1.2

**Comment by brusch** [comment]
Thanks!
