### ISSUE TITLE
Image Gallery with drop zones only can be saved and returns NULL array

### ISSUE THREAD

**Issue by aclDeveloper** [pimcore/pimcore#7220]
# Bug Report

If there is an Image Gallery in a class definition, the user can add new gallery items by clicking the (+) button. When clicking the (+) the component generates a drop zone for either existing Pimcore assets or external files to upload to be dragged onto.

[See example Image here](https://imgur.com/a/aTaRoVO)

Saving the object without linking anything on the drop zone generates an empty (NULL) gallery entry. Iterating over all available gallery entries with the `getItems()` method requires an extra check if there is actually an item in there.

### Expected behavior

If there's no image in the Gallery entry, don't reserve an array cell. Only fill the array returned by `getItems()` with actual values.

### Actual behavior

If the user saves the gallery in an empty state, the result of `getItems()` contains NULL values which need to be checked additionally when iterating over the result.

### Steps to reproduce

- Click (+) in an Image Gallery
- Save the Data Object
- Retrieve the images from the Image Gallery through `getItems()`

### Code example
```php

$ob = MyObject::getById(156975);
$galleryItems = $ob->getSomeGallery()->getItems();
var_dump($galleryItems);

```

```bash
pimcore-console test:playground
/var/www/src/Acl/GalleryTest/Command/PlaygroundCommand.php:30:
array(1) {
  [0] =>
  NULL
}
```

**Comment by kingjia90** [comment]
Thank you for reporting and your patience!
Closing this issue as it seems it was indirectly resolved by https://github.com/pimcore/pimcore/pull/11177
