### ISSUE TITLE
[Security] Links with target set to _blank should use noopener noreferrer for the rel attribute to not leak sensitive data

### ISSUE THREAD

**Issue by alexej-d** [pimcore/pimcore#7227]
# Feature Request

## Feature description
It's a feature request and a security fix at the same time one could say:
Setting a link in CK Editor to use target `_blank` should automatically set the rel attribute of the link to `noopener noreferrer` as you are otherwise possibly leaking sensitive data to other sites (see this [article](https://web.dev/external-anchors-use-rel-noopener/)). Maybe the CK Editor popup for links should automatically set the rel attribute, once someone changes the target attribute? Or you could provide an Event to hook into before rendering WYSIWYG editables, so that site builders can solve this on their own?

Thanks in advance!

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
