### ISSUE TITLE
Replace SensioGeneratorBundle with MakerBundle

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#7237]
https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html

**Comment by brusch** [comment]
Follow up to #7238

**Comment by brusch** [comment]
Generator bundle was already removed with #7559 
Discussion topic: should we again provide a Pimcore specific maker bundle?

**Comment by fashxp** [comment]
see https://github.com/pimcore/bundle-generator
