### ISSUE TITLE
Firefox input editable cursor position bug

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#724]
Firefox renders the cursor focus for empty input elements wrong.

An example:
![image](https://cloud.githubusercontent.com/assets/4639428/16611991/e8e3a490-4364-11e6-8167-bfca6f5ea950.png)

This also happens for input elements in the Pimcore demo.

This happens because of this line in the CSS:
![image](https://cloud.githubusercontent.com/assets/4639428/16612010/0578d5bc-4365-11e6-88f5-950eba7b89dd.png)

It seems like this is a known problem:
http://stackoverflow.com/questions/28122665/contenteditable-placeholder-issue

Replacing the attribute "data-placeholder" with "placeholder" would solve the problem...

**Comment by brusch** [comment]
Unfortunately this doesn't fix the problem in my case, have you verified this? 
Thanks!

**Comment by markus-moser** [comment]
Yes for me this worked. Also adding an attribute data-placeholder="my placeholder" works...
