### ISSUE TITLE
User Permission: Marketing Settings 

### ISSUE THREAD

**Issue by ckastner-vf** [pimcore/pimcore#7243]
# Feature Request

## Feature description
Enable Marketing Settings (Placing Google Analytics ID, Tag Manager ID etc.) for Non-Admin-Users. Is not selectable in User Settings/Permissions. Only accessable with Admin User atm.

**Comment by brusch** [comment]
Done by https://github.com/pimcore/pimcore/issues/12524

See also: https://github.com/pimcore/google-marketing-bundle/blob/1.x/src/Installer.php#L27
