### ISSUE TITLE
Error in Generationg Video Thumbnails

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#7244]
Hover on the video ,Error in thumbnail generation
Open Video.No preview available

![Screenshot from 2020-10-07 03-05-21](https://user-images.githubusercontent.com/21308144/95262757-5f099e00-084a-11eb-923e-5b6d3f4bb1da.png)

**Comment by brusch** [comment]
Works fine for me: 
![image](https://user-images.githubusercontent.com/142037/95432235-ae38f700-094e-11eb-88ea-8e996d363607.png)
