### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by 4selin** [pimcore/pimcore#7248]
# Bug Report

### Expected behavior
Working demo after installation using [instructions](https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Installation.html)

### Actual behavior
White screen on access to home url / or /admin (code is 200 ok)

### Steps to reproduce

create db and user
`composer create-project pimcore/demo rw_backend`
`cd rw_backend && ./vendor/bin/pimcore-install`

I suppose the issue is due to environment misconfiguration. But all checks are passed during installation. Messages are green and looks OK.

Here is the [var/logs/prod.log](https://www.dropbox.com/s/ypd23jm0q5ioilh/prod.log?dl=0) 

This one seems to be the clue. But makes no sense for me yet why it is occurs
`pimcore.ERROR: RuntimeException: Configured CMF customer data object class "Customer" does not exist. in /usr/local/www/pimcore_reywood.ru/rw_backend/vendor/pimcore/customer-management-framework-bundle/src/CustomerProvider/DefaultCustomerProvider.php:62`

My System Info
- FreeBSD 11.3-RELEASE-p13
- PHP 7.4.10
- Composer version 1.10.13 2020-09-09 11:46:34

**Comment by brusch** [comment]
https://talk.pimcore.org/
https://gitter.im/pimcore/pimcore
