### ISSUE TITLE
[Bug] [Redirects] CSV import error

### ISSUE THREAD

**Issue by MyZik** [pimcore/pimcore#7250]
How to reproduce the error.

https://demo.pimcore.fun/admin/?

1. Create 1 -2 redirects in Pimcore Backend (or more :)). Optional fields should be empty.
![Bildschirmfoto 2020-10-07 um 15 17 21](https://user-images.githubusercontent.com/12817320/95336463-ff92a900-08b0-11eb-97c6-b4b988748e13.png)
2. Click on "Export" button.
3. Try to import the downloaded file.
3.1. If you haven't the errors, just delete the imported redirects and try again to import them.
4. You will get an error:
```
Line 1:	Call to a member function setValues() on null
Line 2:	Call to a member function setValues() on null
```
![Bildschirmfoto 2020-10-07 um 15 20 41](https://user-images.githubusercontent.com/12817320/95336706-42548100-08b1-11eb-8b86-05fdc8aac14f.png)

**Comment by dvesh3** [comment]
Fixed by #7334
