### ISSUE TITLE
Update to 6.8.0 failed

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#7256]
The update from PimCore 6.7.x to 6.8.0 gives errors during update and PimCore failed to start afterwards.

Here is the output:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 32 updates, 0 removals
  - Updating amnuts/opcache-gui (2.5.4 => 3.0.1): Downloading (100%)
  - Updating doctrine/dbal (2.10.3 => 2.11.1): Downloading (100%)
  - Updating egulias/email-validator (2.1.19 => 2.1.22): Downloading (100%)
  - Updating symfony/symfony (v4.4.13 => v4.4.15): Downloading (100%)
  - Updating symfony/contracts (v1.1.9 => v1.1.10): Downloading (100%)
  - Updating phpdocumentor/type-resolver (1.3.0 => 1.4.0): Downloading (100%)
  - Updating phpdocumentor/reflection-docblock (5.2.1 => 5.2.2): Downloading (100%)
  - Updating dasprid/enum (1.0.2 => 1.0.3): Downloading (100%)
  - Updating endroid/qr-code (3.9.1 => 3.9.2): Downloading (100%)
  - Updating maxmind/web-service-common (v0.7.0 => v0.8.0): Downloading (100%)
  - Updating maxmind-db/reader (v1.7.0 => v1.8.0): Downloading (100%)
  - Updating geoip2/geoip2 (v2.10.0 => v2.11.0): Downloading (100%)
  - Updating guzzlehttp/psr7 (1.6.1 => 1.7.0): Downloading (100%)
  - Updating guzzlehttp/promises (v1.3.1 => 1.4.0): Downloading (100%)
  - Updating phpseclib/phpseclib (2.0.28 => 2.0.29): Downloading (100%)
  - Updating google/apiclient-services (v0.144 => v0.149): Downloading (100%)
  - Updating google/auth (v1.11.1 => v1.14.1): Downloading (100%)
  - Updating google/apiclient (v2.7.0 => v2.7.2): Downloading (100%)
  - Updating nesbot/carbon (2.39.1 => 2.41.0): Downloading (100%)
  - Updating presta/sitemap-bundle (v2.3.0 => v2.3.1): Downloading (100%)
  - Updating sensiolabs/ansi-to-html (v1.2.0 => v1.2.1): Downloading (100%)
  - Updating symfony/monolog-bundle (v3.5.0 => v3.6.0): Downloading (100%)
  - Updating symfony/swiftmailer-bundle (v3.4.0 => v3.5.1): Downloading (100%)
  - Updating symfony-cmf/routing (2.3.2 => 2.3.3): Downloading (100%)
  - Installing cbschuld/browser.php (v1.9.6): Downloading (100%)
  - Updating pimcore/pimcore (v6.7.1 => v6.8.0): Downloading (100%)
  - Updating elements/process-manager-bundle (v3.0.30 => v3.0.32): Downloading (100%)
  - Updating phpspec/prophecy (1.11.1 => 1.12.1): Downloading (100%)
  - Updating php-http/discovery (1.10.0 => 1.12.0): Downloading (100%)
  - Updating clue/stream-filter (v1.4.1 => v1.5.0): Downloading (100%)
  - Updating pear/archive_tar (1.4.9 => 1.4.10): Downloading (100%)
  - Updating stof/doctrine-extensions-bundle (v1.4.0 => v1.5.0): Downloading (100%)
  - Updating pimcore/data-hub dev-master (0e219c8 => c6c351c):  Checking out c6c351cbd7
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package facebook/webdriver is abandoned, you should avoid using it. Use php-webdriver/webdriver instead.
Package paypal/rest-api-sdk-php is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.
Package zendframework/zend-paginator is abandoned, you should avoid using it. Use laminas/laminas-paginator instead.
Package zendframework/zend-servicemanager is abandoned, you should avoid using it. Use laminas/laminas-servicemanager instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Writing lock file
Generating optimized autoload files
Deprecation Notice: Class Elements\Bundle\ProcessManagerBundle\Command\SampleCommand located in ./vendor/elements/process-manager-bundle/src/examples/ProcessManager/Command/SampleCommand.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Elements\Bundle\ProcessManagerBundle\SampleClassMethod located in ./vendor/elements/process-manager-bundle/src/examples/ProcessManager/SampleClassMethod.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Doctrine\Bundle\MigrationsBundle\Tests\DependencyInjection\DoctrineCommandTest located in ./vendor/doctrine/doctrine-migrations-bundle/Tests/Command/DoctrineCommandTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class AppBundle\Model\Product\Product located in ./src/AppBundle/Model/Product/Products.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
41 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> Pimcore\Composer::postUpdate
> Pimcore\Composer::clearCache

 [WARNING] Some commands could not be registered:

In ProcessQueueCommand.php line 40:

  Too few arguments to function Pimcore\Bundle\EcommerceFrameworkBundle\Comma
  nd\IndexService\ProcessQueueCommand::__construct(), 0 passed in /var/www/ht
  ml/pimcore/var/cache/prod/ContainerVXQraRI/getProcessQueueCommandService.ph
  p on line 14 and at least 1 expected

 [WARNING] Some commands could not be registered:

In ProcessQueueCommand.php line 40:

  Too few arguments to function Pimcore\Bundle\EcommerceFrameworkBundle\Comma
  nd\IndexService\ProcessQueueCommand::__construct(), 0 passed in /var/www/ht
  ml/pimcore/var/cache/prod/ContainerVXQraRI/getProcessQueueCommandService.ph
  p on line 14 and at least 1 expected

 // Clearing the cache for the prod environment with debug
 // false

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.

> Pimcore\Composer::installAssets
Script Pimcore\Composer::installAssets handling the pimcore-scripts event terminated with an exception

  [RuntimeException]
  An error occurred when executing the "'assets:install --symlink --relative '\''web'\'''" command:

**Comment by brusch** [comment]
Unable to reproduce - just updated a fresh demo installation from 6.7.0 to 6.8.0 without any issues - seems to be environment related. Have you tried to kick the cache manually by running `rm -rf var/cache`

**Comment by Hbitvof** [comment]
Hi, 

Clearing cache is not solving anything (i tried the update another time after clearing the cache before). I can revert back to 6.7.3 without any problem. This is a development environment to test updates, this is a clean machine without any activity besides testing updates. Never had any issue with an update before.
