### ISSUE TITLE
Error while generating pdf 

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#7257]
Open a Print container and click on the generate PDF Button.
The progress bar remains at 0% and PDF is not generated.
On clicking cancel button error message is displayed.

![Screenshot from 2020-10-07 23-29-10](https://user-images.githubusercontent.com/21308144/95369696-62a62f00-08f5-11eb-80a9-ff98671d0ced.png)

**Comment by brusch** [comment]
Already fixed by #7254
