### ISSUE TITLE
[DataObject] Undefined notice warning for $params['language']

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#7266]
regression of #3706

`$params['language']` not seems to be set always. why? 

e.g. https://github.com/pimcore/pimcore/blob/01e71d5be10f95582a16e24d3d2d4aedd7fe7670/models/DataObject/ClassDefinition/Data/Video.php#L170 

or

https://github.com/pimcore/pimcore/blob/45ef287afc65e199353e976c91b14b059c5c1959/models/DataObject/ClassDefinition/Data/StructuredTable.php#L277

**Comment by fashxp** [comment]
@blankse  did you notice that during testing?

**Comment by fashxp** [comment]
happens in context of field collections, e.g. when opening object ID 1123 of demo

**Comment by blankse** [comment]
@fashxp That was 2 years ago, but I don't think I noticed.

In my case, the field was translatable. Is the parameter not available for fields that cannot be translated?

**Comment by brusch** [comment]
Fixed by #7284
