### ISSUE TITLE
unable to get 6.8.1 package using composer install

### ISSUE THREAD

**Issue by GaneshKandu** [pimcore/pimcore#7275]
# Bug Report
### Expected behavior
This command ```composer create-project pimcore/skeleton my-project``` do not install ```6.8.1``` of ```pimcore/pimcore```
### Actual behavior
This command ```composer create-project pimcore/skeleton my-project``` do install ```6.8.0``` of ```pimcore/pimcore```
### Steps to reproduce
execute this command ```composer create-project pimcore/skeleton my-project``` to install pimcore
### Solution
[https://getcomposer.org/doc/articles/versions.md#summary](https://getcomposer.org/doc/articles/versions.md#summary)
i think you need to change 
```json
  "require": {
    "php": ">=7.2",
    "wikimedia/composer-merge-plugin": "^1.4",
    "pimcore/pimcore": "~6.8.0"
  },
```
to
```json
  "require": {
    "php": ">=7.2",
    "wikimedia/composer-merge-plugin": "^1.4",
    "pimcore/pimcore": "~6.8"
  },
```
in
```composer.json``` of ```pimcore/skeleton``` to download 6.8.1 of ```pimcore/pimcore```

**Comment by dpfaffenbauer** [comment]
no, `~6.8.0` installs every 6.8 patch version. I guess the problem is the composer.lock is out-of-date. Try running composer update

**Comment by brusch** [comment]
There wasn't a release yet of the `pimcore/skeleton` packge with the updated `composer.lock` - which is now the case - so should work now as expected.
