### ISSUE TITLE
[Pimcore 7] Discussion: just support for Symfony v5? 

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#7283]
... and dropping support for Symfony v4.

**Comment by dpfaffenbauer** [comment]
I'd be down :)

**Comment by albertmueller** [comment]
i am also in favour

**Comment by aarongerig** [comment]
Would be happy with that as well. 👍🏻

**Comment by Blackbam** [comment]
Would be great.

**Comment by thgross** [comment]
There is no way to update all out existing pimcore installations by february 2021.

Since Symfony 5 does no longer support PHP-Templating, every layout, template and areablock needs to be rewritten.

Are there any plans to support pimcore 6.x even after the release of pimcore 7?

**Comment by brusch** [comment]
Pimcore 7 will anyway drop support for PHP templates, see #7224 

Yes, 6.8.x will be further supported by our commercial offering (Enterprise Subscription). It is also planned to offer the PHP templating support for v7 as an enterprise bundle.

**Comment by Yivan** [comment]
Hello, thanks for opening a discussion about this.

Just to give our way to work on projects with Pimcore, on our side, we don't use at all twig, all our project use the PHP template rendering.
Making the jump to Symfony 5 will be a big work for all our customer, and probably many of them wont upgrade so, except those using the enterprise bundle.

I would say, **I would prefer drop Symfony 4** (it seems it is a less breaker than dropping php template) **but keep PHP templating working in Pimcore 7 as native feature** : )

Having the possibility to have the php template working as enterprise bundle is a good thing, thanks for making this possible. I think it is important so current users/customers can stay and be happy of their Pimcore choice.
I know Pimcore team made any major upgrade the more fluid possible, think about the compatibility of Zend in conjonction of Symfony, really a very good attention for your Pimcore users/developpers ! I appreciate this and wanted to say it here. I am confident with Pimcore 7 👍

**Comment by Blackbam** [comment]
> Hello, thanks for opening a discussion about this.
> 
> Just to give our way to work on projects with Pimcore, on our side, we don't use at all twig, all our project use the PHP template rendering.
> Making the jump to Symfony 5 will be a big work for all our customer, and probably many of them wont upgrade so, except those using the enterprise bundle.
> 
> I would say, **I would prefer drop Symfony 4** (it seems it is a less breaker than dropping php template) **but keep PHP templating working in Pimcore 7 as native feature** : )
> 
> Having the possibility to have the php template working as enterprise bundle is a good thing, thanks for making this possible. I think it is important so current users/customers can stay and be happy of their Pimcore choice.
> I know Pimcore team made any major upgrade the more fluid possible, think about the compatibility of Zend in conjonction of Symfony, really a very good attention for your Pimcore users/developpers ! I appreciate this and wanted to say it here. I am confident with Pimcore 7

My opinion about this is that dropping PHP templates is a good thing, because PHP templates do not give you any certain benefits over Twig templates. I know PHP itself is a templating language and if you are using it in a clean and structured way this is sufficient. 

However I have seen a lot of horrible PHP templates in (Pimcore) legacy projects, containing logic and super confusing output generation.. It is a good thing that Twig forces you to seperate the views from the logic and you can do just anything with Twig as with PHP if writing Twig extensions.

For legacy projects of course some refactoring might be required and you have to learn Twig, but IMHO its worth it.

**Comment by brusch** [comment]
Just for reference, Pimcore will drop the support for PHP templates anyway (see #7224), no matter if we continue to support Symfony 4 or not 😉

**Comment by markus-moser** [comment]
Pimcore 7 Upgrades will be quite a bit of effort anyway therefore I'd say let's drop Symfony 4!

**Comment by dpfaffenbauer** [comment]
@Yivan I told you many times to use Twig when Pimcore switched to Symfony, now it would have been a good idea to listen to me ;)

**Comment by ChrisB9** [comment]
Switching to symfony 5 would make this even much easier to support: https://github.com/pimcore/pimcore/issues/5387

**Comment by blankse** [comment]
I'm also for dropping Symfony v4 support. I think that would simplify a lot.

**Comment by grizzlydotweb** [comment]
yeah drop it :)
