### ISSUE TITLE
setViewAutoRender() method not working anymore?

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#7287]
# Bug Report

Version: 6.8.2

After removing the deprecations in Version 6.8.2 the default FrontendController.php from the pimcore/demo is not working anymore because the deprecated method setViewAutoRender() was removed.

```
abstract class FrontendController extends BaseFrontendController {
    /**
     * @inheritDoc
     */
    public function onKernelController(FilterControllerEvent $event) {
        // enable twig view auto-rendering
        $this->setViewAutoRender($event->getRequest(), true, 'twig');
    }
}

```
How to fix this after updating?

**Comment by brusch** [comment]
Deprecations are not removed in 6.8.2, so it should all work as before. 
But we had a small issue earlier today ... the 6.8.2 had the wrong base branch, maybe that's what caused your issue. 
Mabe just flush your caches and try again.
