### ISSUE TITLE
Incorrect encoding detection

### ISSUE THREAD

**Issue by ilienkors** [pimcore/pimcore#7288]
# Bug Report
### Expected behavior
Should correctly detect encoding
### Actual behavior
Instead of windows-1251 it detects ISO-8859-1
### Steps to reproduce
Just try to import CSV with this encoding
### Code example
https://github.com/pimcore/pimcore/blob/fd26e7b7c5aae8d7fa9d6c9c44b0ca3258742b05/lib/Tool/Text.php#L380

# Feature Request
Rewrite `detectEncoding` function
## Feature description
I can rewrite it using https://github.com/onnov/detect-encoding
Is it ok to make PR?

**Comment by brusch** [comment]
@ilienkors a PR would be very nice! Thanks in advance!
