### ISSUE TITLE
Default perspective for user / role

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#729]
currently, the perspective only get applied when a query param has been set (`?perspective=xy`). i think that's happening here:

https://github.com/pimcore/pimcore/blob/c0081d59e9e71097ea07e42e24b2b0230f32b3f7/pimcore/lib/Pimcore/Controller/Action/Admin.php#L183

![bildschirmfoto 2016-07-07 um 12 30 52](https://cloud.githubusercontent.com/assets/700119/16650501/c2aed4d6-443e-11e6-8f7d-df04ad7201df.png)

if the user is logged in, no perspective is available because there is just one (but it's not activated, instead the default is)

### Proposal
- if a user or a user role does have just one perspective, this perspective should be applied when logging in immediately.
- if a user or role has multiple perspectives, the first of them should be applied
- if a user does have multiple user roles (within multiple perspectives), all the perspectives should be merged and the first one should be applied.

**Comment by chix** [comment]
:+1: i was thinking the same thing a while ago, this would be a nice addition
