### ISSUE TITLE
Change JS core events for bundles to native JS events

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#7290]
see https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#example

Event names should be consistent with the Symfony ones, so e.g. `pimcore.document.preSave` (see e.g. https://github.com/pimcore/pimcore/blob/be857eb3ccdaf8fea5ab6639b8a8ef9c5c5cc49e/lib/Event/DocumentEvents.php#L18 ) 

We should change: 
`pimcore.eventDispatcher` : https://github.com/pimcore/pimcore/blob/e8514a18bcaef81f9f57507ed415e3d700f1afa3/bundles/AdminBundle/Resources/public/js/pimcore/event-dispatcher.js

and

`pimcore.plugin.broker` : 
https://github.com/pimcore/pimcore/blob/e8514a18bcaef81f9f57507ed415e3d700f1afa3/bundles/AdminBundle/Resources/public/js/pimcore/plugin/broker.js

BC layer should be possible to implement in both classes, where the class register for the new event and dispatches then the old style events in the new listener: 

### Example dummy
```js
pimcore.plugin.broker = {
    initialize: function() {
        const eventMappings = {
            "preSaveDocument": "pimcore.document.preSave",
            // ...
        };

        for (let oldKey in eventMappings) {
            document.addEventListener(eventMappings[oldKey], function (e) {
                
                pimcore.plugin.broker.fireEvent(oldKey, '...');
            });
        }
    }
    
    // ...
};
``

**Comment by brusch** [comment]
+ BC Layer

**Comment by gjorgic** [comment]
Hi @brusch, please can you tell me what is the further intention behind this migration to native JS? Are you planning to change all current plugin logic including `Class.create`?

Can i simple make my own broker which will act as proxy between JS native events and my component?

**Comment by brusch** [comment]
@gjorgic Sure: using native events makes it a lot easier to hook into the UI, because you actually don't need a bundle anymore or following a specific structure - you just do it the normal JS way - and of course the code is more readable and shorter 😉 

Broker: yes, this is what we actually did here for `10.5`: 
https://github.com/pimcore/pimcore/pull/12566/files#diff-068bb2dae95fa59414280126f267d3e7a2a212ff07f753f24273493f75338f8c

So for 10.5 you're fine, for 11 you need to change it or re-intruduce this BC layer in your custom code (not recommended 😉)
