### ISSUE TITLE
Input Label is alligned to right while all other data types have label aligned to left

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#7292]
Input Label is alligned to right while all other data types have label aligned to left and the layout becomes messy and inconsistent.

![Screenshot from 2020-10-12 20-50-01](https://user-images.githubusercontent.com/21308144/95763536-c56c4180-0ccc-11eb-8fe5-c6383c5521f0.png)

**Comment by dvesh3** [comment]
Fixed by #7361
