### ISSUE TITLE
Blocks with many entries causes fatal error / probably infinite loop

### ISSUE THREAD

**Issue by woellundwoell** [pimcore/pimcore#7297]
# Bug Report

### Expected behavior

- Objects with several block items load correctly

### Actual behavior

- Objects with several block items won't load

### Steps to reproduce

(Tested on live demo system, pimcore 6.8.x-dev)

- Create Class (block with Advanced Many-to-Many Object Relations with 1 meta data field for car objects)

<img width="291" alt="Bildschirmfoto 2020-10-13 um 08 57 02" src="https://user-images.githubusercontent.com/16014748/95826701-fda66b00-0d32-11eb-89a0-783dadebfb90.png">

- Create object and populate block attribute with about 15 entries (maybe some more or less) and assign car-objects with some META data

- Save the object

- Reload or click in tree

- Check php.log: 

<img width="908" alt="Bildschirmfoto 2020-10-13 um 08 56 36" src="https://user-images.githubusercontent.com/16014748/95827010-7dccd080-0d33-11eb-9f31-3d4ff44d5b91.png">

**Comment by woellundwoell** [comment]
Error did not occur under version 6.3.x (and possibly later)

**Comment by pspierce** [comment]
This largely what I described in #6789

**Comment by pspierce** [comment]
I went ahead and moved my blocks into bricks and this appears to have cleared things up for me.

**Comment by Ben-WD** [comment]
I'm running into the same problem. 

@weisswurstkanone Is there any ETA for a fix?

**Comment by dvesh3** [comment]
Fixed by #7563
