### ISSUE TITLE
Thumbnail Generation increases Server CPU to almost 100% (after update to v6.7.2)

### ISSUE THREAD

**Issue by Siqu** [pimcore/pimcore#7301]
# Bug Report

### Actual behavior

We recently updated pimcore to 6.7.2 and since then, every time a thumbnail is generated, the CPU Load spikes to almost 100%.
This problem did not exist in 6.4. 
Did something fundamentally change concerning the thumbnail generation?
If you need more information just ask.

**Comment by brusch** [comment]
Maybe #5505 ?

**Comment by Siqu** [comment]
@brusch i looked into some of our images and could not find any with the clipping path enabled. Could this feature still effect the generation of other images?

**Comment by brusch** [comment]
Not that I'm aware of.

**Comment by dpfaffenbauer** [comment]
had a similar problem with one of the image optimizers... maybe check them out and update if a newer version is available. (jpegoptim and all of those are meant)

**Comment by Siqu** [comment]
@dpfaffenbauer just checked the installed libraries, all are currently up to date

**Comment by NiklasBr** [comment]
> 
> 
> Maybe #5505 ?

I suppose this could be tested by comparing the load with *Keep metadata* checked versus not.

**Comment by ayoob-lfc** [comment]
I don't know if this helps. But we had the same issue with the thumbnails after the upgrade. However when we restarted out instance, everything started to work normally.

**Comment by Siqu** [comment]
@ayoob-lfc are you using docker for the instance and if, which image are you using?

**Comment by ayoob-lfc** [comment]
@Siqu Sorry no docker setup. Perhaps this may help: https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Nginx_Configuration.html#page_Thumbnail-generation-overload-protection

**Comment by RuudvdvNB** [comment]
We experienced the same issue, after upgrading Pimcore thumbnail generation was using 100% CPU but also the image quality was really bad. Our servers where running Imagemagick v7 (imagick lib v3.4.4), after we downgraded ImageMagick v6 everything worked great again and te image quality was normal.

Guess it has to do with the combination Pimcore and ImageMagick v7.

**Comment by NiklasBr** [comment]
@RuudvdvNB ImageMagick v6 was per default compiled with `--with-quantum-depth=8` while the default value for version v7 is 16 bits, see https://imagemagick.org/script/advanced-unix-installation.php

You could try to use the smaller value in v7 to see if it makes a different.

> Larger pixel quantums can cause ImageMagick to run more slowly and to require more memory. For example, using sixteen-bit pixel quantums can cause ImageMagick to run 15% to 50% slower (and take twice as much memory) than when it is built to support eight-bit pixel quantums.

**Comment by brusch** [comment]
I'll close that for now as it isn't reproducible.
