### ISSUE TITLE
Untouched relations get lost when contained in localizes fields in object bricks on save

### ISSUE THREAD

**Issue by dold** [pimcore/pimcore#7302]
# Bug Report
If you have a relation field (e.g. Many-To-One) in an localized field in an object brick and you are editing the content of this relation in one locale while leaving the other locales untouched, the content of the other locales is lost on saving the object.

### Expected behavior
If the content for one locale of a relation field in a localized object brick is changed, the content of the other locales should not get lost, when untouched.

### Actual behavior
The content of the other locales is lost.

### Steps to reproduce
Create an object brick with localized fields and a relation attribute (e.g. Many-To-One). Add this object brick to a class. Create an object of that class. Add the object brick to that object and fill the relation attribute for one locale. Save the object. Now reopen the object and fill the relation attribute for a second locale. Save again. After reloading the object, the content of the first locale is gone.

## Possibly related:
https://github.com/pimcore/pimcore/issues/7059 But the commit that solves the issue there, does not resolve the bug as described here.

**Comment by dvesh3** [comment]
Fixed by #7318
