### ISSUE TITLE
Enable Redirects with Umlaute / non ASCII characters

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#731]
# Feature Request 
At the moment, it does not seem to be possible to create redirects in the admin that do contain Umlaute (ä,ö,ü). A redirect like _@käufer@i_ does not cause https://demo.pimcore.org/k%C3%A4ufer to redirect properly. Nor does it work for https://demo.pimcore.org/käufer directly.

There has been no solution (using utf8 or html characters) within a discussion at gitter so far so I guess that's a pimcore limitation?

**Comment by brusch** [comment]
UTF8 characters are now supported in the regex, for instance `@^/üäö[\/]?$@i`
