### ISSUE TITLE
[FeatureREQ]Impersonate User by just 1 click

### ISSUE THREAD

**Issue by plexmaniax** [pimcore/pimcore#7313]
As a lazy supporter as I am, I would like to have a function to switch into a users role by only one klick.

Now: You must get into the user administration, click on a user and copy the code into a new browser window

Solution 1: Add the funktion to the sidebar menu by clicking at the user you wish to impersonate
![1](https://user-images.githubusercontent.com/18365319/95878962-197f3080-0d76-11eb-810b-437f578f87cd.png)

Solution 2: Add a third button into users config.
![2](https://user-images.githubusercontent.com/18365319/95879077-3ddb0d00-0d76-11eb-8a83-4e76d9e53a3f.png)

**Comment by NiklasBr** [comment]
On solution 1. Using the [UserController.php](https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Controller/Admin/UserController.php#L901-L909) and [Customizing the Tree Context Menu](https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Class_Settings/Custom_Views.html#page_Customizing-the-Tree-Context-Menu) would it be possible for you to add it to your site?

**Comment by solverat** [comment]
Solution 2 is not possible. One browser cannot open another one (not even within current browser -> new inkognito tab i think)

**Comment by aarongerig** [comment]
Solution 2 might be possible with `window.create({ url: url, incognito: true });`. See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create#Browser_compatibility

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
