### ISSUE TITLE
Select with HTML values don't render in some place.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#732]
Before ExtJS6, if i remember using html in select/multiselect field workeded nicely (for color choice for instance, like the pimcore e-comerce demo).
With ExtJS6, in object edition and list grid the html code source is printed and not rendered.

Here is an exemple:

The model (all is ok):
![select-model](https://cloud.githubusercontent.com/assets/9025839/16655992/215b8e02-445d-11e6-88f6-787a5b89f6a6.png)
With CSV detail (all is ok):
![select-model-csv](https://cloud.githubusercontent.com/assets/9025839/16656000/27bbfe94-445d-11e6-9d84-9b9bba0338f4.png)

On the object edition (**problem: don't render the html code**):
![object-edit](https://cloud.githubusercontent.com/assets/9025839/16656009/2e442516-445d-11e6-9dfc-0d20cc99c103.png)

On the grid list (all is ok):
![grid-list](https://cloud.githubusercontent.com/assets/9025839/16656027/4aec5a26-445d-11e6-8d9b-6798d696346f.png)
But when editing the field there is the **same problem than on the object edition**:
![grid-edit](https://cloud.githubusercontent.com/assets/9025839/16656042/5d9a694c-445d-11e6-99ff-b268802dd1d9.png)

All those test was made on the demo website (on news object).
Actually this bug prevent using HTML in select. I didn't try on multiselect but i think the same problem occur.

Best regards.

**Comment by brusch** [comment]
Since this is pure ExtJS functionality I'm not sure if we can change the behavior, it was also not documented to be possible - so we need to see. 

Actually it would be good if you could further investigate this and provide us a proper fix (PR) if possible.

**Comment by Yivan** [comment]
You are right. I just checked if there was way to do this, but it is ExtJS6 way of printing select. The only way would be to hide native box and create a custom one... not a very good way.
So for now, i think we can keep it like this.

I tried multiselect, this one work great. As the grid print the value (and not the display name as single select) it is ok for the grid too.
So it can replace single select if we need HTML display value. Only problem is user can choose multiple choice, so we need to check this with the save() method or by plugin using beforeSave to limit to one choice.

This could be maybe natively managed if we add an improvment to multi select field with "maximum selected" for instance. It could be one or more (like the fieldcollection field for instance).
So on the object model, user could limit to maximum of X choice. This improvement could be used for many case where we need to limit max number of selection in a multiselect.
What do you think of this ? Do I open an issue for multiselect improvement with the ability to choose max number of selected possible ?

**Comment by brusch** [comment]
Thanks for coming back on this. 
Regarding the Multiselect: yes, please create another task for this improvement. Thanks!
