### ISSUE TITLE
Colorpicker data-type for objects

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#733]
I know some plugin existed before (i did not find them on packagist or github... maybe i made bad my search work ; )).

But maybe it could be natively integrated to Pimcore, as it is a common field involved in many project (for edition customer want to select color for header, some background, product color, etc...).

It could be a new type of field for object, named "colorpicker". To keep things simple and easy, it could be same like "input" field but with a colorpicker on the right of the field on the object edition. The ExtJS6 colorpicker could be used. When selecting the color it fills the input field (with "#ff0000" for red for instance). We can keep the regex validation of input so administrator can restrict to some color.
For the grid list, no colorpicker (won't be easy to add it on the grid), but user can edit the color in text mode like input.

So it keep thing simple. Adding the alpha layer seems difficult i think, so it could be a later improvment (and in this case i think using input type field as base is not a good idea, but separation of channels on different fields would be better, and having some method like getRGB(), getCMYK,... to use the color in the front end in CSS/HTML tag/style).

**Comment by brusch** [comment]
See: http://docs.sencha.com/extjs/6.0.0-classic/Ext.picker.Color.html 
Needs palette configuration, default color palette is unusable. 

Since this would be also easily possible with a plugin I'd like to open a voting whether this should be a core feature or not.

**Comment by fashxp** [comment]
at first glance I'm more into plugin integration

**Comment by dpfaffenbauer** [comment]
Just take the existing plugin and port it to extjs 6?

**Comment by Yivan** [comment]
Hum yes the extjs colorpicker is only a panel with some color. It is great for some cases (product color, etc.), as it could be setted in gridlist (i think for ecommerce shop). See capture: http://tinyurl.com/jsh8ffd
On the other way something like that could be achieved with multiselect (if we could limit to one, see improvement #734).

Another case, and wich cannot be resolved with the extjs color picker is let the user choosing the color he want (from all existing one). For this we can use a plugin (like http://www.eyecon.ro/colorpicker/ for instance). The simplest would be adding an option (a checkbox) on the model on the input field called "show colorpicker". And it will just make appear the colorpicker when the user edit the input field. So there is no new data-type to do, only GUI call.

This way we could have both classic use case of colorpickers. 
If we don't want introduce new data-type just making multiselect able to limit number of choice and adding "show colorpicker" for input field coudl do the trick.
Creating a new datatype based on extjs colorpicker is not necessary but has better GUI than multiselect (i think about gridlist, for batch color assignation visually: very nice for the enduser).
