### ISSUE TITLE
Maintenance not working anymore after upgrading from 6.7.x to 6.8.2

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#7333]
Hi,

Since the upgrade to 6.8.2. we get the notice to setup maintenance in PimCore.

When running the maintenance manually I receive these errors:

12:26:52 EMERGENCY [pimcore] PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleteAfterHours' in 'where clause' in /var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:96
Stack trace:
#0 /var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(96): PDO->query('SELECT id FROM ...')
#1 /var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1159): Doctrine\DBAL\Driver\PDOConnection->query('SELECT id FROM ...')
#2 /var/www/html/pimcore/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(93): Doctrine\DBAL\Connection->executeQuery('SELECT id FROM ...', Array, Array, NULL)
#3 /var/www/html/pimcore/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(279): Pimcore\Db\Connection->executeQuery('SELECT id FROM ...', Array, Array)
#4 /var/www/html/pimcore/vendor/elements/process-manager-bundle/src/Model/MonitoringItem/Listing/Dao.php(62): Pimcore\Db\Connection->fetchCol('SELECT id FROM ...', Array)
#5 [internal function]: Elements\Bundle\ProcessManagerBundle\Model\MonitoringItem\Listing\Dao->load()
#6 /var/www/html/pimcore/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(242): call_user_func_array(Array, Array)
#7 /var/www/html/pimcore/vendor/elements/process-manager-bundle/src/Maintenance.php(52): Pimcore\Model\AbstractModel->__call('load', Array)
#8 /var/www/html/pimcore/vendor/elements/process-manager-bundle/src/Maintenance.php(45): Elements\Bundle\ProcessManagerBundle\Maintenance->deleteExpiredMonitoringItems()
#9 /var/www/html/pimcore/vendor/elements/process-manager-bundle/src/Maintenance/MaintenanceTask.php(41): Elements\Bundle\ProcessManagerBundle\Maintenance->execute()
#10 /var/www/html/pimcore/vendor/pimcore/pimcore/lib/Maintenance/Executor.php(95): Elements\Bundle\ProcessManagerBundle\Maintenance\MaintenanceTask->execute()
#11 /var/www/html/pimcore/vendor/pimcore/pimcore/bundles/CoreBundle/Command/MaintenanceCommand.php(93): Pimcore\Maintenance\Executor->executeMaintenance(Array, Array, false)
#12 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): Pimcore\Bundle\CoreBundle\Command\MaintenanceCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\MaintenanceCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(273): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\MaintenanceCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/pimcore/bin/console(26): Symfony\Component\Console\Application->run()
#19 {main}

Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleteAfterHours' in 'where clause' in /var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
Stack trace:
#0 /var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(101): Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
#1 /var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1159): Doctrine\DBAL\Driver\PDOConnection->query('SELECT id FROM ...')
#2 /var/www/html/pimcore/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(93): Doctrine\DBAL\Connection->executeQuery('SELECT id FROM ...', Array, Array, NULL)
#3 /var/www/html/pimcore/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(279): Pimcore\Db\Connection->executeQuery('SELECT id FROM ...', Array, Array)
#4 /var/www/html/pimcore/vendor/elements/process-manager-bundle/src/Model/MonitoringItem/Listing/Dao.php(62): Pimcore\Db\Connection->fetchCol('SELECT id FROM ...', Array)
#5 [internal function]: Elements\Bundle\ProcessManagerBundle\Model\MonitoringItem\Listing\Dao->load()
#6 /var/www/html/pimcore/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(242): call_user_func_array(Array, Array)
#7 /var/www/html/pimcore/vendor/elements/process-manager-bundle/src/Maintenance.php(52): Pimcore\Model\AbstractModel->__call('load', Array)
#8 /var/www/html/pimcore/vendor/elements/process-manager-bundle/src/Maintenance.php(45): Elements\Bundle\ProcessManagerBundle\Maintenance->deleteExpiredMonitoringItems()
#9 /var/www/html/pimcore/vendor/elements/process-manager-bundle/src/Maintenance/MaintenanceTask.php(41): Elements\Bundle\ProcessManagerBundle\Maintenance->execute()
#10 /var/www/html/pimcore/vendor/pimcore/pimcore/lib/Maintenance/Executor.php(95): Elements\Bundle\ProcessManagerBundle\Maintenance\MaintenanceTask->execute()
#11 /var/www/html/pimcore/vendor/pimcore/pimcore/bundles/CoreBundle/Command/MaintenanceCommand.php(93): Pimcore\Maintenance\Executor->executeMaintenance(Array, Array, false)
#12 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): Pimcore\Bundle\CoreBundle\Command\MaintenanceCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\MaintenanceCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(273): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\MaintenanceCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/pimcore/bin/console(26): Symfony\Component\Console\Application->run()
#19 {main}

Next Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT id FROM plugin_process_manager_monitoring_item WHERE (status = "finished" OR status = "finished_with_errors") AND (deleteAfterHours > 0 AND (UNIX_TIMESTAMP()-(deleteAfterHours*3600)) > modificationDate) ':

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleteAfterHours' in 'where clause' in /var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79
Stack trace:
#0 /var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(182): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDO\Exception))
#1 /var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(159): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDO\MySQL\Driver), Object(Doctrine\DBAL\Driver\PDO\Exception), 'An exception oc...')
#2 /var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2021): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\MySQL\Driver), Object(Doctrine\DBAL\Driver\PDO\Exception), 'SELECT id FROM ...', Array)
#3 /var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1163): Doctrine\DBAL\Connection->handleExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), 'SELECT id FROM ...', Array, Array)
#4 /var/www/html/pimcore/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(93): Doctrine\DBAL\Connection->executeQuery('SELECT id FROM ...', Array, Array, NULL)
#5 /var/www/html/pimcore/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(279): Pimcore\Db\Connection->executeQuery('SELECT id FROM ...', Array, Array)
#6 /var/www/html/pimcore/vendor/elements/process-manager-bundle/src/Model/MonitoringItem/Listing/Dao.php(62): Pimcore\Db\Connection->fetchCol('SELECT id FROM ...', Array)
#7 [internal function]: Elements\Bundle\ProcessManagerBundle\Model\MonitoringItem\Listing\Dao->load()
#8 /var/www/html/pimcore/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(242): call_user_func_array(Array, Array)
#9 /var/www/html/pimcore/vendor/elements/process-manager-bundle/src/Maintenance.php(52): Pimcore\Model\AbstractModel->__call('load', Array)
#10 /var/www/html/pimcore/vendor/elements/process-manager-bundle/src/Maintenance.php(45): Elements\Bundle\ProcessManagerBundle\Maintenance->deleteExpiredMonitoringItems()
#11 /var/www/html/pimcore/vendor/elements/process-manager-bundle/src/Maintenance/MaintenanceTask.php(41): Elements\Bundle\ProcessManagerBundle\Maintenance->execute()
#12 /var/www/html/pimcore/vendor/pimcore/pimcore/lib/Maintenance/Executor.php(95): Elements\Bundle\ProcessManagerBundle\Maintenance\MaintenanceTask->execute()
#13 /var/www/html/pimcore/vendor/pimcore/pimcore/bundles/CoreBundle/Command/MaintenanceCommand.php(93): Pimcore\Maintenance\Executor->executeMaintenance(Array, Array, false)
#14 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): Pimcore\Bundle\CoreBundle\Command\MaintenanceCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\MaintenanceCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(273): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\MaintenanceCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/pimcore/bin/console(26): Symfony\Component\Console\Application->run()
#21 {main}
12:26:52 ERROR     [app] Failed to execute job with ID process_manager_maintenance: Doctrine\DBAL\Exception\InvalidFieldNameException {-driverException: Doctrine\DBAL\Driver\PDO\Exception {#1 …}#message: """  An exception occurred while executing 'SELECT id FROM plugin_process_manager_monitoring_item WHERE (status = "finished" OR status = "finished_with_errors") AND (deleteAfterHours > 0 AND (UNIX_TIMESTAMP()-(deleteAfterHours*3600)) > modificationDate) ':\n  \n  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleteAfterHours' in 'where clause'  """#code: 0#file: "/var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php"#line: 79-previous: Doctrine\DBAL\Driver\PDO\Exception {#1 …}trace: {/var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79 { …}/var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:182 { …}/var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:159 { …}/var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:2021 { …}/var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1163 { …}/var/www/html/pimcore/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php:93 { …}/var/www/html/pimcore/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php:279 { …}/var/www/html/pimcore/vendor/elements/process-manager-bundle/src/Model/MonitoringItem/Listing/Dao.php:62 { …}Elements\Bundle\ProcessManagerBundle\Model\MonitoringItem\Listing\Dao->load() {}/var/www/html/pimcore/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:242 { …}/var/www/html/pimcore/vendor/elements/process-manager-bundle/src/Maintenance.php:52 { …}/var/www/html/pimcore/vendor/elements/process-manager-bundle/src/Maintenance.php:45 { …}/var/www/html/pimcore/vendor/elements/process-manager-bundle/src/Maintenance/MaintenanceTask.php:41 { …}/var/www/html/pimcore/vendor/pimcore/pimcore/lib/Maintenance/Executor.php:95 { …}/var/www/html/pimcore/vendor/pimcore/pimcore/bundles/CoreBundle/Command/MaintenanceCommand.php:93 { …}/var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255 { …}/var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:1027 { …}/var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:97 { …}/var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:273 { …}/var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:83 { …}/var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:149 { …}/var/www/html/pimcore/bin/console:26 {› $application = new \Pimcore\Console\Application($kernel);› $application->run();› } …}} ["id" => "process_manager_maintenance","exception" => Doctrine\DBAL\Exception\InvalidFieldNameException^ { …}]

Is this a known issue and can how can I solve this?

**Comment by dvesh3** [comment]
> An exception occurred while executing 'SELECT id FROM plugin_process_manager_monitoring_item WHERE (status = "finished" OR status = "finished_with_errors") AND (deleteAfterHours > 0 AND (UNIX_TIMESTAMP()-(deleteAfterHours*3600)) > modificationDate)

@Hbitvof Seems related to ProcessManager plugin. Please report at the correct Repo. Thanks!

**Comment by Hbitvof** [comment]
This is fixed, no errors anymore when running maintenance, but still the warning. I'll open a new issue.

**Comment by brusch** [comment]
@Hbitvof which warning, is it really triggered by the core?

**Comment by Hbitvof** [comment]
@brusch I made a new issue under https://github.com/pimcore/pimcore/issues/7347 with the warning screenshot.
