### ISSUE TITLE
Feature suggestion: Provide default text in a scenario having translations with keys

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#7336]
# Feature Request

This is how translations in the Pimcore backend currently look like:

![Translations](https://user-images.githubusercontent.com/1703552/96124305-bc10ee00-0ef3-11eb-8ece-affecc4d1827.png)

Creating translations there are basically two possibilities:

1) You can put the correct default language text

`$this->translator->trans('a searchable and sortable table for data');`

Using this approach has a drawback: You do not know the context where this translation is used immediatly and you always have to use the same translation no matter where it appears within the page.

2) You can put a key which somehow forces the admins to translate

`$this->translator->trans("datatable_decimalSign")`

`$this->translator->trans("datatable_menuEntries")  // default "Show _MENU_ entries"`

This approach also has a drawback: You can not show placeholders and you have to translate, you also do not know how the default text should look like.

## Possible solution 

This is the definition of the Translator->trans() function:

```
    public function trans($id, array $parameters = [], $domain = null, $locale = null)
    { ... }
```

In order to avoid the drawbacks of both approaches I suggest to implement the possibility to have key-based translations with a default text - showing the default text within the shared translations admin interface.

You could simply add a custom parameter like `"default" => "My default english text"`. This text is shown instead of the key in case no translation is made. This text is also shown within an admin column for users who are not sure what to put into the translation for this key.

What do you think about this improvement?

**Comment by dpfaffenbauer** [comment]
honestly, you are responsible for fallbacks, not Pimcore. So you could check if the key is set, if not, fallback to something else

**Comment by Blackbam** [comment]
> honestly, you are responsible for fallbacks, not Pimcore. So you could check if the key is set, if not, fallback to something else

Well I got your point but you do not see the full potential of this. Of course I can check if a translation is set and display the fallback otherwise (could also extend the Translator class). The main thing about this request is to also provide a help for translating the keys in the Pimcore admin interface - translations are usually not done by the programmer.

**Comment by NiklasBr** [comment]
Looks like @Blackbam wants something like the [Drupal Translation Context](https://www.drupal.org/docs/8/api/translation-api/overview#s-context-in-drupalt-and-drupalformatplural), which I would very much like.

**Comment by dpfaffenbauer** [comment]
I'd prefer to be as close to Symfony Translator as possible. Fallbacks are not part of it... There was also a discussion of this on symfony: https://github.com/symfony/symfony/issues/35466. They didn't reach a consensus of whats the right path. (also considering symfony already has fallbacks in terms of other locales, which Pimcore doesn't do (?) with SharedTranslations)

I like to keep things simple and stupid. If you need more, extend it. (even bundle it and share it with the community).

Using Pimcore for 7 years now, never had this use-case. Just use proper keys that describe the context... IMO

**Comment by Blackbam** [comment]
The Symfony Translator can stay as it is. For my use case the functionality I want to implement is really easy to achieve using one method:

```
    protected function transdef($var,$default) {
        $translated = $this->translator->trans($var);
        return (empty($translated) || ($translated === $var)) ? $default : $translated;
    }
```

The only thing I really miss - and this has nothing to do with Symfony - is a possibility to show the default within the Pimcore Admin column within the shared translations. This requires a tiny modification of the Pimcore Admin interface and the Translator class. Pimcore is extending Translator anyway.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
