### ISSUE TITLE
XLIFF Import issue with special chars / umlaut

### ISSUE THREAD

**Issue by gpalmisano** [pimcore/pimcore#7337]
XLIFF Import issue with special chars / umlaut

# Bug Report

### Expected behavior
On XLIFF Import all the fields are imported correctly, even if there are some special chars in it.

### Actual behavior
In SEO title and description as well as Navigation name the special chars / umlaut are encoded wrong

### Steps to reproduce
export XLIFF, translate it, put some special chars in the fields for testing purpose, import XLIFF.

### Examples

![Bildschirmfoto 2020-10-15 um 15 33 02](https://user-images.githubusercontent.com/11161922/96137627-25e1c580-0efd-11eb-8ba8-a9f412f08497.png)

![Bildschirmfoto 2020-10-15 um 15 35 22](https://user-images.githubusercontent.com/11161922/96137647-2d08d380-0efd-11eb-83b3-39b6ecc65a37.png)

Tested on Pimcore 6.8.2

**Comment by jeykodev** [comment]
We have the exact same problem in 6.8.4 and it seems, that it is still present in the latest Pimcore X Version. We traced down the issue to this line:

https://github.com/pimcore/pimcore/blob/6ce64f4ada34bbcc27e0aba4a7677100e0048e46/lib/Translation/Escaper/Xliff12Escaper.php#L119

Is `asXML()` really necessary? As already mentioned [here](https://www.php.net/manual/en/simplexmlelement.asxml.php#110485), it would be sufficient to provide an approriate XML header inside the XML import file. When doing so, `asXML()` could be removed entirely.

**Comment by dvesh3** [comment]
Closing it as not reproducible on Pimcore X.
![image](https://user-images.githubusercontent.com/5137917/135075189-e7206e1a-a3a9-4f7c-a836-1bff260de0d3.png)
![image](https://user-images.githubusercontent.com/5137917/135075310-c2d04eb4-8375-444f-b71d-dde33f410392.png)
