### ISSUE TITLE
Error in opening documents in chrome

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#7338]
- Open any document in chrome.
- The page never opens and stuck at please wait....
- There are a lot of errors in the console.
- Getting this issue only in chrome.Also tried clearing browser cache
- Screenshot of pimcore demo attached.
![Screenshot from 2020-10-15 22-17-28](https://user-images.githubusercontent.com/21308144/96162011-a2909600-0f35-11eb-9354-63f7877a9560.png)

![Screenshot from 2020-10-15 22-17-10](https://user-images.githubusercontent.com/21308144/96162003-9efd0f00-0f35-11eb-8ceb-3b9b0f9ffcef.png)

![Screenshot from 2020-10-15 22-17-38](https://user-images.githubusercontent.com/21308144/96162015-a3c1c300-0f35-11eb-9c10-2c7f379c76ce.png)

**Comment by brusch** [comment]
Please do not report any issues here that are not reproducible in a local instance but just on the public demo. 
The public demo is available to everyone and sometimes funny 🤡 guys are destroying it intentionally.

**Comment by neha04** [comment]
@brusch This issue is also reproducible in my local instance and i get it verified on the pimcore demo instance.
I have a few more instances that are setup on server , I am getting the same error on those instances as well...

**Comment by dvesh3** [comment]
@neha04 Pimcore version on your local?

**Comment by neha04** [comment]
I am using 6.8.0 and 6.8.2. Getting same issues on both the instances.

**Comment by neha04** [comment]
@dvesh3 please make sure that you are on production environment.

**Comment by brusch** [comment]
I definitely can't reproduce the issue, just opened document with id `200` on the public demo ... no problem.
![image](https://user-images.githubusercontent.com/142037/96235578-452f3000-0f9b-11eb-8b5f-c31461fd528e.png)

**Comment by neha04** [comment]
![screencast-nimbus-capture-2020 10 16-14_09_23](https://user-images.githubusercontent.com/21308144/96236865-34da7d80-0fba-11eb-9619-98199273c17c.gif)

Still getting the issue.

**Comment by brusch** [comment]
Well, probably an issue with your Chrome then?

**Comment by jdreesen** [comment]
Works for me, too.

**Comment by neha04** [comment]
Instances with pimcore version <=6.7 were working fine on my chrome version (77.0.3865) but all instances with version 6.8 were facing issues.
Now I updated chrome to latest version and and its working fine.
Seems pimcore does not support this version anymore.I''ll try to keep my chrome updated before creating issues :sweat_smile: and I think that would be a good practice.
Thanks @brusch for help.
