### ISSUE TITLE
Maintenance warning after upgrading from 6.7.x to 6.8.x

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#7347]
Hi,

Since the upgrade to 6.8.x I see the maintenance warning in PimCore the maintenance is not setup properly:

![image](https://user-images.githubusercontent.com/41229269/96331207-c1894800-105b-11eb-8875-beae91b23267.png)

The maintenance is setup properly and is running every 5 minutes. Also when running maintenance manually with -vvv there are no errors.

Before 6.7.x no issues.

**Comment by brusch** [comment]
Works ok for me. 
The functionality is here: 
https://github.com/pimcore/pimcore/blob/11b202379a6ff6e18510d43094baff1157e2581c/bundles/AdminBundle/Controller/Admin/IndexController.php#L323
and here: 
https://github.com/pimcore/pimcore/blob/810ac4e50701e98e8b5d78084676e7b93cfb6c50/lib/Maintenance/Executor.php#L132

maybe you can quickly debug this on your instance. 
If it is a general problem, a PR fixing the issue would be nice 😊

**Comment by Hbitvof** [comment]
Only strange thing in the verbose logging I found is this:

11:21:48 INFO      [php] User Deprecated: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead.
[
  "exception" => ErrorException {
    #message: "User Deprecated: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead."
    #code: 0
    #file: "/var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php"
    #line: 58
    #severity: E_USER_DEPRECATED
    trace: {
      /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:58 { …}
      /var/www/html/pimcore/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManager.php:187 { …}
      /var/www/html/pimcore/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManager.php:155 { …}
      /var/www/html/pimcore/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CheckoutManager/V7/CheckoutManager.php:55 { …}
      /var/www/html/pimcore/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManagerFactory.php:175 { …}
      /var/www/html/pimcore/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/Factory.php:235 { …}
      /var/www/html/pimcore/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/Maintenance/CleanupPendingOrdersTask.php:25 { …}
      /var/www/html/pimcore/vendor/pimcore/pimcore/lib/Maintenance/Executor.php:95 { …}
      /var/www/html/pimcore/vendor/pimcore/pimcore/bundles/CoreBundle/Command/MaintenanceCommand.php:93 { …}
      /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255 { …}
      /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:1027 { …}
      /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:97 { …}
      /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:273 { …}
      /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:83 { …}
      /var/www/html/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:149 { …}
      /var/www/html/pimcore/bin/console:26 {
        › $application = new \Pimcore\Console\Application($kernel);
        › $application->run();
        ›
      }
    }
  }
]
 Perhaps this can cause this problem?

**Comment by brusch** [comment]
No, that's ok.

**Comment by Hbitvof** [comment]
@brusch anything else you want me to provide to debug?

**Comment by brusch** [comment]
Like I wrote earlier, I'd check if something is saved in the `TmpStore` and if so, if the value get's updated on every run.

**Comment by Hbitvof** [comment]
I did what you asked.

Before I started the maintenance job:

![image](https://user-images.githubusercontent.com/41229269/96439375-04d3ea00-1207-11eb-8f42-913897f59fb6.png)

After starting the maintenance job I see some activity:

![image](https://user-images.githubusercontent.com/41229269/96439636-161cf680-1207-11eb-97c1-d807d4fd9197.png)

And when the activity stops I see the date is not changing for the maintenance.pid row:

![image](https://user-images.githubusercontent.com/41229269/96439803-53818400-1207-11eb-9624-cd69c063aa39.png)

**Comment by Hbitvof** [comment]
@brusch Can you please reopen this issue?

**Comment by Hbitvof** [comment]
@brusch Can you please reopen this issue. This is not solved.

**Comment by fracsi** [comment]
The timestamp in the database for `maintenance.pid` is only updated when the row expires ([1 week](https://github.com/pimcore/pimcore/blob/master/models/Tool/TmpStore.php#L78)).
If you follow the callstack for updating the last execution time for the maintenance, you can see that the update only occurs if the row is expired.
[TmpStore::add](https://github.com/pimcore/pimcore/blob/master/models/Tool/TmpStore.php#L99)
[TmpStore::get](https://github.com/pimcore/pimcore/blob/master/models/Tool/TmpStore.php#L146)

**Comment by Hbitvof** [comment]
Hi,

So what do you want me to check? Can you please tell me what I need to do to debug this.

**Comment by fracsi** [comment]
@Hbitvof I think this is a bug in pimcore itself.
Maybe the code should set 0 expiration time for the `maintenance.pid` thus, everytime the maintenance is run, the row gets updated.
https://github.com/pimcore/pimcore/blob/7f802ce45eef4b43da2468b2a622b23c2cb6f41a/lib/Maintenance/Executor.php#L122-L125

**Comment by ssiergl** [comment]
yep I can confirm...same Problem here. IMHO `setLastExecution()` in `Executor.php` should call `TmpStore::set()` and not `TmpStore::add()` to ensure that the table entry is updated for real.

@brusch will submit a patch this evening

**Comment by brusch** [comment]
@ssiergl nice, looking forward to it! Thanks a lot in advance!

**Comment by fracsi** [comment]
@ssiergl I missed the `set` function by 10 lines... :smile:

**Comment by ssiergl** [comment]
@brusch done

**Comment by brusch** [comment]
Fixed by #7405 
@ssiergl Thank you so much!
