### ISSUE TITLE
Question: when master branch will be in not dev pimcore?

### ISSUE THREAD

**Issue by ilienkors** [pimcore/pimcore#7354]
Can you please answer when should I wait and in what version [these changes](https://github.com/pimcore/pimcore/commit/75a03b50f26afcc2f35ef5f3e5d2e483ddde4618) ?
Thank you!

**Comment by brusch** [comment]
This is not the right place for asking questions ... 
either comment directly on the corresponding PR or use our forums or Gitter channel.
