### ISSUE TITLE
SQL error when trying to add a classification store

### ISSUE THREAD

**Issue by John5** [pimcore/pimcore#736]
I am using the CoreShop plugin, which has the ability to add a classification store for every product object. When attempting to add one, BEFORE a classification store has been configured. This results in an internal server error when Pimocore attempts to retrieve the URL  admin/classificationstore/collections?_dc=1468316206621&storeId=&oid=11&fieldname=classificationStore&page=1&start=0&limit=25

The problem is caused by the empty storeId parameter. In the file pimcore/modules/admin/ClassificationstoreController.php the method collectionsAction() constructs an SQL condition "(storeId = )" which is invalid.

To prevent this error the code should check if the parameter storeId contains a valid value and fail more gracefully by throwing an exception, telling the user that a classification store needs to be configured first.

**Comment by brusch** [comment]
Shouldn't this checked by CoreShop in advance?

**Comment by dpfaffenbauer** [comment]
I don't think so. The problem affects all kind of automated installed classes with classification store fields. This problem would also happen when adding a classification store field without any store configured.
