### ISSUE TITLE
Thumbnail for PDF files are not getting created

### ISSUE THREAD

**Issue by pradeep-pimcore** [pimcore/pimcore#7363]
# Bug Report
Thumbnail for PDF are not getting created

### Steps to reproduce
Upload any PDF file in the pimcore assets
Check tree-view thumbnail or folder listing thumbnail for the uploaded PDF file
Thumbnail does not appear

**Comment by brusch** [comment]
See: 
#6001
#3974
#6190

**Comment by pradeep-pimcore** [comment]
@brusch Ok, my bad. Did not search the existing issues with enough keywords. :)

But I tried to look for this in the pimcore development documentation, But I could not find any mention of this.
**I think this should also be mentioned in the [Asset Document Thumbnails page](https://pimcore.com/docs/pimcore/current/Development_Documentation/Assets/Working_with_Thumbnails/Document_Thumbnails.html) in the documentation**

**Comment by brusch** [comment]
@pradeep-pimcore done, see 5eda760f82554853398cffe32787d1cf28ed5e3c
