### ISSUE TITLE
Migration - Pimcore runs his own migration in a non-related bundle

### ISSUE THREAD

**Issue by palazzetti** [pimcore/pimcore#7364]
### Expected behavior
`ProcessManager` version: 3.0.35
`Pimcore` version: 6.8.3
Expect migration to run bundle code and not Pimcore code.

@ckogler-elements is the author of the Bundle, I opened an issue and we came to the conclusion that the problem is related to Pimcore itself.
Issue URL https://github.com/elements-at/ProcessManager/issues/64#issuecomment-712737473
### Actual behavior
Migration, even if bundle is specified, runs Pimcore stuff.
### Steps to reproduce
`bin/console pimcore:bundle:update ElementsProcessManagerBundle`
### What I have tried to solve the problem
Tried dropping the target table 'object_localized_query_10_es_es' without success, later there are as many tables to delete and I don't feel very confident in doing so.
The problem could be related to unsuccessful migrations.
Commands that I've run to try fix the issue:
`bin/console pimcore:migrations:migrate -s pimcore_core`
`bin/console cache:clear`
`bin/console pimcore:deployment:classes-rebuild`
`bin/console pimcore:migrations:migrate 00000016 --bundle=ElementsProcessManagerBundle`

**Comment by brusch** [comment]
bin/console pimcore:bundle:update does not run pimcore migrations ... 
can you please be a bit more specific what your issue is?

**Comment by palazzetti** [comment]
> bin/console pimcore:bundle:update does not run pimcore migrations ...
> can you please be a bit more specific what your issue is?

If you take a look at the issue url that I've provided, you can see this error:
![](https://user-images.githubusercontent.com/49283657/96571022-53e35300-12cb-11eb-8d37-bad1d0e710ec.png)
it has nothing to do with the bundle update/migrations, it is closely related to the pimcore code, in particular with a migration that occurred many versions ago which created tables for translations using only lower case codes

**Comment by brusch** [comment]
Seems to be related to Doctrine Migrations

**Comment by palazzetti** [comment]
> Seems to be related to Doctrine Migrations

So the issue is a real pimcore issue?
