### ISSUE TITLE
Adding Table with columns config activated on existing object class creates an exception on DAO load

### ISSUE THREAD

**Issue by ChristopheBraud** [pimcore/pimcore#7365]
# Bug Report
### Expected behavior
Adding a table with colum config on an existing object should work
### Actual behavior
It works in pimcore ui but make an exception in PHP API
### Steps to reproduce
On an existaing object, create a table with config colums activated, then try a foreach loop on a listing of your objects. you can't access your objects anymore

### Code example
```php
$skus = new Sku\Listing();
foreach ($skus as $sku) {
  echo 'ok'
} // each loop will generate an exception without executing the core loop code
```

The error is located in this function :
[Table.php:324](https://github.com/pimcore/pimcore/blob/master/models/DataObject/ClassDefinition/Data/Table.php#L324)

I can do a PR but i don't know what is the best solutuion to solve the problem : 
This bug appears because $data (witch is null) is casted to string ('') before unserializing. so the next condition on null is never verified. Then the foreach on line 341 is trying to iterate on an empty string.

- Solution 1: remove the string cast
- Solution 2: replace the '=== null' condition by an 'empty()' condition
- Solution 3: protect the foreach loop with an 'is_array' condition

**Comment by ChristopheBraud** [comment]
@fashxp @circular-code, you're the two guys who work on this code, can you take a look? Thank you!

**Comment by fashxp** [comment]
can you please share the actual error message?

**Comment by fashxp** [comment]
ahh ... I'm not sure if removing string cast does not have any other side effects... 
I would go for something like that: 
```
        $unserializedData = Serialize::unserialize((string) $data);

        if ($data === null || $unserializedData === null) {
            return null;
        }
```

**Comment by ChristopheBraud** [comment]
ok thanks @fashxp, i'll do a PR soon!

**Comment by fashxp** [comment]
fixed via https://github.com/pimcore/pimcore/pull/7457
