### ISSUE TITLE
content of unpublished documents lost; document versions get overwritten with current content

### ISSUE THREAD

**Issue by thgross** [pimcore/pimcore#7366]
After updating from 6.6.9 to 6.8.3, all document versions and also all current content of unpublished documents are gone.

### Expected behavior

When opening an unpublished document, it should still contain its content.
When looking at/editing older versions of any document, one should be able to see/edit the content of that version.

### Actual behavior

When opening an unpublished document, either its contents are very old, or it even sometimes contains content from different documents. This makes most unpublished documents unusable.

When opening published documents, all seems to be OK, but when trying so look at older document versions, it only ever shows the most recent content.
**When viewing a specific older version of an document (checking "Show"-checkbox of a version in the "Versions"-Tab), pimcore overwrites the version file in `/var/versions/document/g0/<document-id>/<version-id>` with the content of the most recent version instead of showing the content of that version file.
This seems to not affect versions that are saved after the update to pimcore 6.8.3.**

### Steps to reproduce

I am not able to reproduce this behaviour on demo.pimcore.fun, because there are no unpublished documents or any older document versions.

This really is a major problem, since it destroyed a lot of soon-to-be-published documents of our customers.

**Comment by weisswurstkanone** [comment]
Could you please clarify:
"all document versions are gone" in combination with "viewing a specific older version"

Would it be possible to attach a screen recording showing your steps
+ a version file from 6.8.3 ?

Thanks a lot!

**Comment by thgross** [comment]
this is a document I created in **pimcore 6.6.9**. I saved several different versions:

![testpage-6 6 9](https://user-images.githubusercontent.com/5030864/96721276-2c17ec00-13ac-11eb-9a18-6dd7d95fc5fa.gif)

this is the same document after the update to **pimcore 6.8.3**. all content is gone - it seems that the content is back to the initially created, empty document (in this case, 5126):

![testpage-6 8 3](https://user-images.githubusercontent.com/5030864/96721361-4eaa0500-13ac-11eb-98b4-ad4ffd5e15d9.gif)

Here are the version files 5128 (should contain "second save") . I renamed them to `.txt` to be able to upload them.
1. from pimcore 6.6.9:
[5128.txt](https://github.com/pimcore/pimcore/files/5415933/5128.txt)

2. from pimcore 6.8.3 (after previewing this version once like in the `gif` above, because the update of pimcore itself does not change the file, but previewing the version does):
[5128.txt](https://github.com/pimcore/pimcore/files/5415936/5128.txt)

**Comment by weisswurstkanone** [comment]
Can you provide one from before you preview it?

**Comment by thgross** [comment]
> Can you provide one from before you preview it?

That is actually the first "5128.txt" download from my comment, see "1. from pimcore 6.6.9".
pimcore 6.6.9 **does not** change the content of the version file at all on preview - the contents are identical, just the file date gets changed.

So, the first version file is from before previewing the version in pimcore 6.8.3, the second one ist after previewing.
pimcore 5.8.3 **does** change the content of the version file.

**Comment by nicklassandell** [comment]
I am experiencing the same issue. Are there any news on this?

**Comment by brusch** [comment]
Fixed by #7406

**Comment by Sats-25** [comment]
what is the difference between published version and unpublished version in file system?
