### ISSUE TITLE
[Twig] Pimcore editables are not working

### ISSUE THREAD

**Issue by palazzetti** [pimcore/pimcore#7371]
## Expected behavior
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/49283657/96700125-5f984d80-138f-11eb-94fc-58bb48f6fa7a.png">

## Actual behavior
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/49283657/96700154-6a52e280-138f-11eb-8023-16458235bcdc.png">

### Steps to reproduce
Pimcore version 6.8.3
Just create a twig template and try to render it using $this->render('templatePath', params)

### Code example
We are converting php templates to twig in order to remove the deprecations.
PHP Working Code:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/49283657/96700287-8fdfec00-138f-11eb-9ad9-8cca5491028b.png">

Twig NOT Working Code:
<img width="478" alt="image" src="https://user-images.githubusercontent.com/49283657/96700326-9cfcdb00-138f-11eb-80b7-5e76da860bea.png">

I don't know if this could help but in web inspector I see this:
<img width="930" alt="image" src="https://user-images.githubusercontent.com/49283657/96700618-efd69280-138f-11eb-9b65-95f840310823.png">
So I actually feel that he is trying to render it but it does not end successfully
Thanks 

### Pimcore documentation
https://pimcore.com/docs/pimcore/master/Development_Documentation/Documents/Editables/Relation_(Many-To-One).html
<img width="317" alt="image" src="https://user-images.githubusercontent.com/49283657/96701122-860ab880-1390-11eb-8e94-c70f888bbd3c.png">

**Comment by palazzetti** [comment]
Just updated the title, the problem is related to all the pimcore editables (if used in twig)

**Comment by brusch** [comment]
Our public demo uses Twig as well, no problems there ... maybe related to your setup?

**Comment by palazzetti** [comment]
> Our public demo uses Twig as well, no problems there ... maybe related to your setup?

Could be, what do you suggest?
`Twig_Environment::VERSION` outputs 2.13.1

**Comment by brusch** [comment]
Hmm, acutally I don't know, you probably have to debug it on your setup, a good starting point would be here: 
https://github.com/pimcore/pimcore/blob/8123d0dd377f8f841b09ecb077bd2d09154fe837/lib/Twig/Extension/DocumentEditableExtension.php#L83

**Comment by palazzetti** [comment]
> Hmm, acutally I don't know, you probably have to debug it on your setup, a good starting point would be here:
> 
> https://github.com/pimcore/pimcore/blob/8123d0dd377f8f841b09ecb077bd2d09154fe837/lib/Twig/Extension/DocumentEditableExtension.php#L83

You are right, https://github.com/pimcore/pimcore/blob/8123d0dd377f8f841b09ecb077bd2d09154fe837/lib/Twig/Extension/DocumentEditableExtension.php#L85 is null. What could be the issue?

**Comment by palazzetti** [comment]
@brusch Fixed...I was not passing all parameters to the view but only some...
![image](https://user-images.githubusercontent.com/49283657/96835075-5c5e9980-1443-11eb-8989-ca96820603e6.png)

**Comment by brusch** [comment]
@palazzetti 👍😉
Btw. `$this->view` is deprecated as well.

**Comment by palazzetti** [comment]
> @palazzetti 👍😉
> Btw. `$this->view` is deprecated as well.

What's the new method to get all parameters? Thanks
