### ISSUE TITLE
[DOC] Random cron % must be escaped

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#7378]
Hello,

Cronjob exemple given in the documentation don't work.

On the page https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Advanced_Installation_Topics.html#page_Add-some-randomness-to-the-maintenance-cron-job

```
*/5 * * * * sleep $[ ( $RANDOM % 120 ) + 1 ]s ; /your/project/bin/console maintenance
```

should be

```
*/5 * * * * sleep $[ ( $RANDOM \% 120 ) + 1 ]s ; /your/project/bin/console maintenance
```

% must be escaped in cron (`A "%" character in the command, unless escaped with a backslash (\), will be changed into` as said in the man page https://man7.org/linux/man-pages/man5/crontab.5.html)

Thanks

**Comment by brusch** [comment]
Was fixed already by #7867
