### ISSUE TITLE
[Maintenance bug?] Versions Cleanup query contains errors

### ISSUE THREAD

**Issue by palazzetti** [pimcore/pimcore#7390]
## Expected behavior
Cmd `bin/console pimcore:maintenance -f -j versioncleanup` to work

### Actual behavior
![image](https://user-images.githubusercontent.com/49283657/97149183-a78eea00-176c-11eb-8ab1-f0929945f9d3.png)
The error is in the query at the` id NOT IN` segment.

`09:16:31 ERROR     [app] Failed to execute job with ID versioncleanup: Doctrine\DBAL\Exception\SyntaxErrorException {-driverException: Doctrine\DBAL\Driver\PDO\Exception {#1 …}#message: """  An exception occurred while executing 'SELECT cid, GROUP_CONCAT(id ORDER BY id DESC) AS versions FROM versions WHERE ctype = ? AND NOT public AND id NOT IN (,,,,) GROUP BY cid HAVING COUNT(*) > ? LIMIT 1000' with params ["document", 1]:\n  \n  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ',,,) GROUP BY cid HAVING COUNT(*) > '1' LIMIT 1000' at line 1  """#code: 0#file: "./vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php"#line: 98-previous: Doctrine\DBAL\Driver\PDO\Exception {#1 …}trace: {./vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:98 { …}./vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:182 { …}./vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:159 { …}./vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:2121 { …}./vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1264 { …}./vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php:93 { …}./vendor/pimcore/pimcore/models/Version/Dao.php:151 { …}./vendor/pimcore/pimcore/lib/Maintenance/Tasks/VersionsCleanupTask.php:83 { …}./vendor/pimcore/pimcore/lib/Maintenance/Executor.php:95 { …}./vendor/pimcore/pimcore/bundles/CoreBundle/Command/MaintenanceCommand.php:93 { …}./vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255 { …}./vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:1027 { …}./vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:97 { …}./vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:273 { …}./vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:83 { …}./vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:149 { …}./bin/console:26 {› $application = new \Pimcore\Console\Application($kernel);› $application->run();› } …}} ["id" => "versioncleanup","exception" => Doctrine\DBAL\Exception\SyntaxErrorException^ { …}]`

### Steps to reproduce
Run `bin/console pimcore:maintenance -f -j versioncleanup`.
That may be a problem related to my instance but anyway the code does not expect the "NOT IN" element list to be empty

**Comment by dvesh3** [comment]
@palazzetti [this line](https://github.com/pimcore/pimcore/blob/163f95e61ac97b8d5997932827ba93cc85755b0b/models/Version/Dao.php#L134) should set default value in case list is empty to avoid errors....right?

**Comment by palazzetti** [comment]
> @palazzetti [this line](https://github.com/pimcore/pimcore/blob/163f95e61ac97b8d5997932827ba93cc85755b0b/models/Version/Dao.php#L134) should set default value in case list is empty to avoid errors....right?

Yes in case the list is empty but it's not, in this case the list is full of **empty string**

**Comment by dvesh3** [comment]
but how come the version id is empty?

**Comment by palazzetti** [comment]
> but how come the version id is empty?

Nice question

**Comment by dvesh3** [comment]
I cannot reproduce this issue....so let's wait if someone else reports it. meanwhile you can check versions table and logs for the root cause. thanks!

**Comment by palazzetti** [comment]
> I cannot reproduce this issue....so let's wait if someone else reports it. meanwhile you can check versions table and logs for the root cause. thanks!

Can't reproduce anymore the issue, the versions causing the problem have been deleted by the cleanup.
I still recommend adding that `if` to avoid future problem, it can only do good.
However, I think those entities were generated during the migration from one machine to another, in which we had to regenerate the rows of the tables from the files.
Have a good day 😉

**Comment by theobscenezen** [comment]
I've got the same behaviour. A string list of empty IDs like here:

> > @palazzetti [this line](https://github.com/pimcore/pimcore/blob/163f95e61ac97b8d5997932827ba93cc85755b0b/models/Version/Dao.php#L134) should set default value in case list is empty to avoid errors....right?
> 
> Yes in case the list is empty but it's not, in this case the list is full of **empty strings** I added a pull request

Another possible solution would be to array_filter the $ignoredIds [here](https://github.com/pimcore/pimcore/blob/163f95e61ac97b8d5997932827ba93cc85755b0b/models/Version/Dao.php#L132) or before passing the parameter in the Maintenance-Task [here](https://github.com/pimcore/pimcore/blob/54021096da2b0f74df2d65b68b727791d6adf923/lib/Maintenance/Tasks/VersionsCleanupTask.php#L118)

**Comment by Zodiarc** [comment]
Same issue here interestingly it occurs in one project on one environment (pimcore version 10.3.1). I'm trying to reproduce it:

`Next Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'SELECT cid, GROUP_CONCAT(id ORDER BY id DESC) AS versions FROM versions WHERE ctype = ? AND NOT public AND id NOT IN (,,,,,,,,) GROUP BY cid HAVING COUNT(*) > ? LIMIT 1000' with params ["document", 10]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ',,,,,,,,) GROUP BY cid HAVING COUNT(*) > '10' LIMIT 1000' at line 1 in /var/www/pimcore/releases/8/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:98
Stack trace:
#0 /var/www/pimcore/releases/8/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(182): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException()
#1 /var/www/pimcore/releases/8/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(159): Doctrine\DBAL\DBALException::wrapException()
#2 /var/www/pimcore/releases/8/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2225): Doctrine\DBAL\DBALException::driverExceptionDuringQuery()
#3 /var/www/pimcore/releases/8/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1312): Doctrine\DBAL\Connection->handleExceptionDuringQuery()
#4 /var/www/pimcore/releases/8/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(99): Doctrine\DBAL\Connection->executeQuery()
#5 /var/www/pimcore/releases/8/vendor/pimcore/pimcore/models/Version/Dao.php(152): Pimcore\Db\Connection->executeQuery()
#6 /var/www/pimcore/releases/8/vendor/pimcore/pimcore/lib/Maintenance/Tasks/VersionsCleanupTask.php(118): Pimcore\Model\Version\Dao->maintenanceGetOutdatedVersions()
#7 /var/www/pimcore/releases/8/vendor/pimcore/pimcore/lib/Maintenance/Tasks/VersionsCleanupTask.php(57): Pimcore\Maintenance\Tasks\VersionsCleanupTask->doVersionCleanup()
#8 /var/www/pimcore/releases/8/vendor/pimcore/pimcore/lib/Maintenance/Executor.php(78): Pimcore\Maintenance\Tasks\VersionsCleanupTask->execute()
#9 /var/www/pimcore/releases/8/vendor/pimcore/pimcore/lib/Messenger/Handler/MaintenanceTaskHandler.php(33): Pimcore\Maintenance\Executor->executeTask()
#10 /var/www/pimcore/releases/8/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php(96): Pimcore\Messenger\Handler\MaintenanceTaskHandler->__invoke()
#11 /var/www/pimcore/releases/8/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(74): Symfony\Component\Messenger\Middleware\HandleMessageMiddleware->handle()
#12 /var/www/pimcore/releases/8/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\Component\Messenger\Middleware\SendMessageMiddleware->handle()
#13 /var/www/pimcore/releases/8/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware->handle()
#14 /var/www/pimcore/releases/8/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(48): Symfony\Component\Messenger\Middleware\DispatchAfterCurrentBusMiddleware->handle()
#15 /var/www/pimcore/releases/8/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware->handle()
#16 /var/www/pimcore/releases/8/vendor/symfony/messenger/MessageBus.php(77): Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware->handle()
#17 /var/www/pimcore/releases/8/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\Component\Messenger\MessageBus->dispatch()
#18 /var/www/pimcore/releases/8/vendor/symfony/messenger/Worker.php(158): Symfony\Component\Messenger\RoutableMessageBus->dispatch()
#19 /var/www/pimcore/releases/8/vendor/symfony/messenger/Worker.php(107): Symfony\Component\Messenger\Worker->handleMessage()
#20 /var/www/pimcore/releases/8/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(225): Symfony\Component\Messenger\Worker->run()
#21 /var/www/pimcore/releases/8/vendor/symfony/console/Command/Command.php(298): Symfony\Component\Messenger\Command\ConsumeMessagesCommand->execute()
#22 /var/www/pimcore/releases/8/vendor/symfony/console/Application.php(1033): Symfony\Component\Console\Command\Command->run()
#23 /var/www/pimcore/releases/8/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand()
#24 /var/www/pimcore/releases/8/vendor/symfony/console/Application.php(299): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()
#25 /var/www/pimcore/releases/8/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun()
#26 /var/www/pimcore/releases/8/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#27 /var/www/pimcore/releases/8/bin/console(46): Symfony\Component\Console\Application->run()
#28 {main} ["id" => "versioncleanup","exception" => Doctrine\DBAL\Exception\SyntaxErrorException { …}]
`

**Comment by Zodiarc** [comment]
Also maybe important info. The error seems to occur on document version cleanup, but the project in question has no documents.

**Comment by kingjia90** [comment]
This #11794 in 10.3.4 might have indirectly fixed that, as `intval` converts everything (null,empty strings,etc..) to `0` resulting as `IN (0,0,0)` after the implosion, which at least doesn't crash as a SQL syntax problem.

It would be interesting to know how it is originated in the first place since `id` should be an autoincrement index, maybe there was a `RIGHT JOIN` in the past?
Can you double-check the table `versions` and see if there's any empty values in the `id` column?

**Comment by ThisIsJustARandomGuy** [comment]
We are running into this issue with a 10.5.9 instance, so #11794 didn't fix it. It appears that simply adding a call to `array_filter` on the `$ignoreIds` argument of `Pimcore\Model\Version\Dao::maintenanceGetOutdatedVersions()` (line 134) prevents the Exception from being thrown:

```PHP
public function maintenanceGetOutdatedVersions($elementTypes, $ignoreIds = [])
{
    $ignoreIdsList = implode(',', array_filter($ignoreIds)); // Prevents the Exception
    if (!$ignoreIdsList) {
        $ignoreIdsList = '0'; // set a default to avoid SQL errors (there's no version with ID 0)
    }
    $versionIds = [];

    // .......
}
$ignoreIdsList = implode(',', array_filter($ignoreIds));
```

 However, I haven't checked if this could remove versions that should stay. Could someone check?

**Comment by elburro1887** [comment]
Just received this error today, on 10.6.1


````
20:38:00 ERROR     [app] Failed to execute job with ID versioncleanup: 
Doctrine\DBAL\Exception\SyntaxErrorException
 {#message: """  An exception occurred while executing 'SELECT id FROM versions as a 
WHERE (ctype = ? AND date < ?) AND NOT public AND id NOT IN (2859948,,,,,,,,,)' 
with params ["document", 1714509480]:\n  \n  

SQLSTATE[42000]: Syntax error or access violation: 
1064 You have an error in your SQL syntax; check the manual that corresponds to your 
MySQL server version for the right syntax to use near ',,,,,,,,)' 
at line 1  """#
code: 0
#file: "/var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php"
#line: 98-previous: 
Doctrine\DBAL\Driver\PDO\Exception {#1 …}
-driverException: Doctrine\DBAL\Driver\PDO\Exception {#1 …}
trace: {/var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:98 { …}
/var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:182 { …}
/var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:159 { …}
/var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:2226 { …}
/var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1313 { …}
/var/www/html/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php:92 { …}
/var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1119 { …}
/var/www/html/vendor/pimcore/pimcore/models/Version/Dao.php:149 { …}
/var/www/html/vendor/pimcore/pimcore/lib/Maintenance/Tasks/VersionsCleanupTask.php:118 { …}
/var/www/html/vendor/pimcore/pimcore/lib/Maintenance/Tasks/VersionsCleanupTask.php:57 { …}
/var/www/html/vendor/pimcore/pimcore/lib/Maintenance/Executor.php:81 { …}
/var/www/html/vendor/pimcore/pimcore/lib/Messenger/Handler/MaintenanceTaskHandler.php:33 { …}
/var/www/html/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:97 { …}
/var/www/html/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php:73 { …}
/var/www/html/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php:34 { …}
/var/www/html/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php:68 { …}
/var/www/html/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php:48 { …}
/var/www/html/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php:37 { …}
/var/www/html/vendor/symfony/messenger/MessageBus.php:77 { …}
/var/www/html/vendor/symfony/messenger/RoutableMessageBus.php:54 { …}
/var/www/html/vendor/symfony/messenger/Worker.php:158 { …}
/var/www/html/vendor/symfony/messenger/Worker.php:107 { …}
/var/www/html/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php:234 { …}
/var/www/html/vendor/symfony/console/Command/Command.php:298 { …}
/var/www/html/vendor/symfony/console/Command/LazyCommand.php:71 { …}
/var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/Command/MaintenanceCommand.php:134 { …}
/var/www/html/vendor/symfony/console/Command/Command.php:298 { …}
/var/www/html/vendor/symfony/console/Application.php:1058 { …}
/var/www/html/vendor/symfony/framework-bundle/Console/Application.php:96 { …}
/var/www/html/vendor/symfony/console/Application.php:301 { …}
/var/www/html/vendor/symfony/framework-bundle/Console/Application.php:82 { …}
/var/www/html/vendor/symfony/console/Application.php:171 { …}
/var/www/html/bin/console:49 
{› $application = new \Pimcore\Console\Application($kernel);› $application->run();› } …}} 
["id" => "versioncleanup","exception" => Doctrine\DBAL\Exception\SyntaxErrorException^ { …}]
````



Seems like Pimcore\Model\Version\Dao::maintenanceGetOutdatedVersions() (line 134):

`$ignoreIdsList = implode(',', $ignoreIds);`

is generating this (invalid) SQL command: `(2859948,,,,,,,,,)`, when the `$ignoreIdsList` contains empty values somehow? 

I added a quick fix to remove the empty values, and it doesnt error now. 

`$ignoreIds = array_filter($ignoreIds, 'is_numeric');`
