### ISSUE TITLE
Compatibility with Composer 2.0

### ISSUE THREAD

**Issue by limenet** [pimcore/pimcore#7391]
# Bug Report

A couple days ago, Composer 2.0 [was released](https://blog.packagist.com/composer-2-0-is-now-available/) and for a while now, Composer `1.10.x` has been warning about invalid PSR-0 and PSR-4 configurations and most packages have been upgraded/fixed.

From the release post:

> Invalid PSR-0 / PSR-4 configurations will not autoload anymore in optimized-autoloader mode, as per the warnings introduced in Composer 1.10.

Further, the release post contains this snippet:

> As for Composer 1.x, it is now more or less EOL. It will also receive critical fixes if anything comes up but the goal for everyone should be to migrate to 2.x as soon as possible.

Almost all of Pimcore's dependencies are compatible with Composer 2.0 except for [`doctrine/doctrine-migrations-bundle`](https://github.com/pimcore/pimcore/blob/master/composer.json#L56) which uses an almost [two-year old version](https://github.com/doctrine/DoctrineMigrationsBundle/releases/tag/v1.3.2) with now being superseded by two major versions.

### Expected behavior

Pimcore can safely be installed with Composer 2.0 which is the new stable version of Composer and replaces Composer 1.x which is now EOL.

### Actual behavior

Due to depending on an old version of `doctrine/doctrine-migrations-bundle`, which is not compatible with Composer 2.0, it is currently not safely possible to use Composer 2.0 when installing Pimcore.

### Steps to reproduce

1. Install Composer 1.x
1. Run `composer install`
1. Observe the following message: `Deprecation Notice: Class Doctrine\Bundle\MigrationsBundle\Tests\DependencyInjection\DoctrineCommandTest located in ./vendor/doctrine/doctrine-migrations-bundle/Tests/Command/DoctrineCommandTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201`

I realize this is unlikely to cause any issues (since the message affects a test used by that bundle) yet it unfortunately prevents us from safely using Composer 2.0 in production in conjunction with Pimcore and instead relying on a now EOL version of Composer.

**Comment by dpfahlbusch** [comment]
There is currently another problem with composer v2.
The wikimedia/composer-merge-plugin is not composer v2 compatible at the moment.

https://github.com/wikimedia/composer-merge-plugin/issues/184

**Comment by HaaseIT** [comment]
Furthermore, in the pimcore dockerfile:

https://github.com/pimcore/docker/blob/df45b64f4875a5cf1bbeabd91d1d5adc3954dfbb/Dockerfile.template

hirak/prestissimo:^0.3

is required, this is also incompatible with Composer 2.0

**Comment by brusch** [comment]
Fixed by 
#7349 
https://github.com/pimcore/skeleton/commit/58516d5ef2a542ca1bb3903a4bf1fe31142e5880 
https://github.com/pimcore/demo/commit/116f44e9c1c2792a530f7d76048f1fdd7c32568b

**Comment by HaaseIT** [comment]
@brusch What about the the docker part?

**Comment by brusch** [comment]
@HaaseIT https://github.com/pimcore/docker/pull/29

**Comment by limenet** [comment]
@brusch thanks for the changes! Most Composer 2.0 issues now appear fixed.

However, while #7349 upgraded a number of Doctrine packages, the one mentioned in my initial report, `doctrine/doctrine-migrations-bundle`, remained [untouched](https://github.com/pimcore/pimcore/pull/7349/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L56) and as such the deprecation notice still appears. I've verified this with the current `master`s of both the demo and skeleton repo.

Do you have any plans on upgrading that package as well?

**Comment by jdreesen** [comment]
I don't think that's an issue as it's only a test file that cannot be loaded. You don't want to run the tests locally which is why they are ignored in the export for version 2 & 3.

**Comment by brusch** [comment]
For 6.x it's fine as it is I'd say (however PRs are welcome), for 7 we're going to update the dependencies anyway.
