### ISSUE TITLE
[Document] Link editable can generate invalid type="" attribute

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#7394]
# Bug Report

### Expected behavior

The editable `pimcore_link('link_fooBar')` should produce valid HTML.

### Actual behavior

It adds `type="interal"` on some links, this is a violation of the HTML standard which should, [according to the spec](https://html.spec.whatwg.org/multipage/links.html#attr-hyperlink-type):

> The type attribute, if present, gives the MIME type of the linked resource. It is purely advisory. The value must be a valid MIME type string. User agents must not consider the type attribute authoritative — upon fetching the resource, user agents must not use metadata included in the link to the resource to determine its type.

**Comment by brusch** [comment]
@NiklasBr just tried to reproduce this on our demo, but wasn't able to do so 😐 Can you please share the details how to reproduce this issue? Thanks!

**Comment by NiklasBr** [comment]
The footer for example:

![image](https://user-images.githubusercontent.com/279826/97293135-87365c80-184c-11eb-9f8e-305468be03d7.png)
