### ISSUE TITLE
Using areaBlock getting js error cannot read property 'types' of undefined in version 6.8.2

### ISSUE THREAD

**Issue by pdchaudhary** [pimcore/pimcore#7395]
# Bug Report

### Expected behavior
Areablock should be working 
### Actual behavior
Areablock is not working, Areablock option seciton missing not able to add other sections.
### Steps to reproduce
1. add areaBlock code in the template
2. getting error in the admin when opening the edit tab in document.
3. this.config getting undefined
![image](https://user-images.githubusercontent.com/30948231/97256400-e8eccb80-1838-11eb-8b2b-2dda84d83b43.png)
![image](https://user-images.githubusercontent.com/30948231/97256437-fb670500-1838-11eb-9011-c307cffb19db.png)

**Comment by brusch** [comment]
Unable to reproduce in our public demo.
