### ISSUE TITLE
Debug Mode for Console CLI

### ISSUE THREAD

**Issue by datom** [pimcore/pimcore#740]
add new option to enable pimcore debug mode from cli like

php pimcore/cli/console.php --debug

**Comment by cleggypdc** [comment]
could the same be achieved through --environments? so setup a copy of the same environment but with debug enabled and run CLI using that?

**Comment by brusch** [comment]
yes, that's possible, but not that comfortable I'd say ;-)

**Comment by deltatag** [comment]
+1

**Comment by dpfaffenbauer** [comment]
`--env=dev` wouldn't do that the same?

**Comment by dpfaffenbauer** [comment]
seems that dev and test always activate debug mode.

https://github.com/pimcore/pimcore/blob/master/lib/Config/EnvironmentConfig.php#L54

https://github.com/pimcore/pimcore/blob/master/lib/Bootstrap.php#L292

**Comment by brusch** [comment]
Yep `--env=dev` should do the trick.
