### ISSUE TITLE
Admin login is not recognizing Edge correctly anymore and hides the login form

### ISSUE THREAD

**Issue by Myrmidonut** [pimcore/pimcore#7411]
### Expected behavior
Admin login using Edge browser (at least on MacOS) shows the login form.

### Actual behavior
Admin login shows the warning that the browser is not supported.

### Steps to reproduce
Open https://demo.pimcore.fun/admin using Edge.

# Feature Request
Check for Edge in Resources/views/Admin/login/login.html.php in the AdminBundle.

## Feature description
Edge identifies as "Edge" now and not as "Chrome" anymore for at least Version 86.0.622.56 (Offizielles Build) (64-Bit) on MacOS.

**Comment by brusch** [comment]
Fixed by #7412
