### ISSUE TITLE
Floating point filtering issue

### ISSUE THREAD

**Issue by kubaplas** [pimcore/pimcore#7423]
## Expected behavior
I can filter number fields using float values.

### Actual behavior
When filtering using floating point values, e.g. `0.00002`, no results are shown. Also, removing filters doesn't reverts to original grid.

### Steps to reproduce
1. Create a numeric field with decimal precision of at least 5, or with no precision.
2. Set the value in object editor to 0.00002
![Zrzut ekranu z 2020-10-30 12-17-39](https://user-images.githubusercontent.com/1809664/97699701-e09bc700-1aaa-11eb-88a1-150a964804cc.png)

3. Open the grid, filter for objects with value equal to 0.00002 - no results are found
![Zrzut ekranu z 2020-10-30 12-17-54](https://user-images.githubusercontent.com/1809664/97699646-ca8e0680-1aaa-11eb-9b53-80d17eaa714d.png)

4. Remove the filters - all the results are missing now, folder reload is needed
![Zrzut ekranu z 2020-10-30 12-18-09](https://user-images.githubusercontent.com/1809664/97699658-cf52ba80-1aaa-11eb-837e-3de8710660d3.png)

5. Using direct sql query - results are shown
![Zrzut ekranu z 2020-10-30 12-19-08](https://user-images.githubusercontent.com/1809664/97699666-d2e64180-1aaa-11eb-9a76-dec184ab99c8.png)

### Possible related issue
It may be related to #5088 ?

**Comment by brusch** [comment]
Fixed by #7550
