### ISSUE TITLE
[ECommerce] Followup Symfony Lock - isAcquired vs. acquire

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#7430]
see https://github.com/pimcore/pimcore/blob/20e15263b8cc8f016d651fbca2842cc0f6f43022/bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php#L1077

- check, if this might be a problem when executing indexing command in parallel -> processes might lock each other only for checking if lock is set by a third process (for reindexing) 
- release lock might be missing at this point.

**Comment by mugge6** [comment]
Exactly this happens on 6.8.5

**Comment by fashxp** [comment]
fixed with https://github.com/pimcore/pimcore/pull/7757
