### ISSUE TITLE
[DataObject] Preview with Image Advanced and Thumbnails failing, wrongly ElementDescriptor returned

### ISSUE THREAD

**Issue by melissakittl** [pimcore/pimcore#7434]
# Bug Report

### Expected behavior

If an object gets opened by the preview - button, the edited version of the object will be shown.

![image](https://user-images.githubusercontent.com/23357021/97855262-cbb57280-1cfa-11eb-9969-7466816672b0.png)

### Actual behavior
If the object contains a Hotspotimage **(image (Type: Image Advanced),** the preview doesn't work, if a thumbnail of the image should be loaded.

Following error will be shown:
```php
Attempted to call an undefined method named "getThumbnailConfig" of class "Pimcore\Model\Element\ElementDescriptor".
```

At [ Pimcore\Model\DataObject\Data\Hotspotimage.php Line 178](https://github.com/pimcore/pimcore/blob/master/models/DataObject/Data/Hotspotimage.php#L178)
```        
$thumbConfig = $this->getImage()->getThumbnailConfig($thumbnailName);        
```
Because ``$this->getImage()`` is at that moment ``Pimcore\Model\Element\ElementDescriptor {
  type: "asset"
  id: 74741
}``

### Steps to reproduce

- create a class with a Hotspotimage **(image (Type: Image Advanced)** and a preview url
- render the image via ``object.image().getThumbnail('some-thumbnail')`` in view
- create and open object in backend, add image and click on preview button
- error

**Comment by weisswurstkanone** [comment]
fixed via #7440
