### ISSUE TITLE
[Image Thumbnails] Support loading="lazy"

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#7438]
Pimcore already has support for lazy-loading image thumbnails with `lowQualityPlaceholder` parameter. While this does work, it requires a JS implementation for actually loading the images. Meanwhile most browsers support this feature natively with [`loading="lazy"`](https://web.dev/browser-level-image-lazy-loading/) in the `img` tag. Would be cool if we could add a parameter for that too, e.g. `$image->getThumbnail()->getHtml(['lazy' => true])`

**Comment by dpfaffenbauer** [comment]
`$image->getThumbnail()->getHtml(['loading' => 'lazy'])` does not work?

**Comment by BlackbitNeueMedien** [comment]
Currently not because in https://github.com/pimcore/pimcore/blob/530098ea48745926d8f155cce5e6228c222968ac/models/Asset/Image/Thumbnail.php#L264-L266 the `loading` attribute gets thrown away. But perhaps this is already the fix to just add it to https://github.com/pimcore/pimcore/blob/530098ea48745926d8f155cce5e6228c222968ac/models/Asset/Image/Thumbnail.php#L205

Will check that in the evening...

**Comment by dpfaffenbauer** [comment]
honestly, Pimcore should support any tag given here... even if it is not valid, it is developer responsibility to only add valid tags.

**Comment by christopher-siegel** [comment]
I think so too  @dpfaffenbauer. Lots of frontend libraries use attributes that aren't "valid".

**Comment by brusch** [comment]
Fixed by #7461

**Comment by brusch** [comment]
@dpfaffenbauer Pimcore DOES accept any given attribute 😉
