### ISSUE TITLE
BUG: Database row size too large while having a class with only 119 attributes

### ISSUE THREAD

**Issue by jacobsyentl** [pimcore/pimcore#7458]
# Bug Report
While working on a simple class model for a retailer we hit the maximum of the row size very fast in the database.
In comparison with previous versions of Pimcore, we were able to have at least double the number of attributes without having this limitation.

### Expected behavior
Being able to have a class model with more than 119 (average column length of 190) simple attributes.

### Actual behavior
Saving causes the following error:
![Screenshot 2020-11-04 at 09 01 47](https://user-images.githubusercontent.com/9139261/98086313-d8fb6a00-1e7e-11eb-8e24-07a431ce32af.png)

This error shows us a maximum of 65.535 per row.
If we take into account the default setting of 190 per column and multiply by 120 = 22.800.
This is not even close to the 65.535

We tested the class also on the online demo of Pimcore, this resulted in the same error message.

**Comment by brusch** [comment]
That's actually a limitation of MySQL/MariaDB. 
Please use the length setting to not use the default. 
Please be aware that Pimcore is using utf8mb4, that actually means: 190 characters = 190 x 4 = 760 bytes.
