### ISSUE TITLE
[Assets] Folder name "icons" leads to 404 error on image thumbnails

### ISSUE THREAD

**Issue by Brainshaker95** [pimcore/pimcore#7481]
# Bug Report

### Expected behavior
Folder name "icons" is a valid name or an error is thrown that this name is a reserved word

### Actual behavior
No error is thrown and generated thumbnails lead to a not found error (not in editmode, only in frontend)

### Steps to reproduce
* Add an asset folder named "icons"
* Upload assets to this folder
* Use these assets somewhere where a thumbnail version of them should be displayed

**Comment by Cruiser13** [comment]
Also reproducable on the pimcore demo. Simply rename the sample content folder to "icons".

**Comment by IgorBenko** [comment]
The problem most probably lies in the default apache config.
The mod_alias config includes by default a rewrite for /icons.
See: /etc/apache2/mods-available/alias

It looks like this:
```
<IfModule alias_module>
	# Aliases: Add here as many aliases as you need (with no limit). The format is
	# Alias fakename realname
	#
	# Note that if you include a trailing / on fakename then the server will
	# require it to be present in the URL.  So "/icons" isn't aliased in this
	# example, only "/icons/".  If the fakename is slash-terminated, then the
	# realname must also be slash terminated, and if the fakename omits the
	# trailing slash, the realname must also omit it.
	#
	# We include the /icons/ alias for FancyIndexed directory listings.  If
	# you do not use FancyIndexing, you may comment this out.

	Alias /icons/ "/usr/share/apache2/icons/"

	<Directory "/usr/share/apache2/icons">
		Options FollowSymlinks
		AllowOverride None
		Require all granted
	</Directory>

</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```
Removing this symlink should resolve it: `/etc/apache2/mods-enabled/alias.conf`

**Comment by brusch** [comment]
@IgorBenko thanks a lot for sharing, I can confirm this fixed the issue. 👍

**Comment by imranertaza** [comment]
@IgorBenko Thanks, Man. It fixed my problem.
