### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#7484]
# Feature request

According to the documentation Pimcore requires one of those database servers:

MariaDB >= 10.0.0.5
MySQL >= 5.6.4
AWS Aurora (MySQL)
Percona Server

PostgreSQL (https://www.postgresql.org/) integrates great with Symfony 5 (https://symfony.com/doc/current/cloud/services/postgresql.html). PostgreSQL has many advantages over MySQL/MariaDB - it has faster read and write times, more optimization possibilities and more advanced features. Overall it is more stable. Due to use of DBAL I really do not see any good reason why not to support it? Would be great to have support for it in Pimcore V7.

**Comment by brusch** [comment]
It's mainly because of the data-objects, I don't see a chance we can make that for 7
