### ISSUE TITLE
[DataObject][Custom Layouts] Missing layout components

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#7489]
- fieldset
- field container
- button

![image](https://user-images.githubusercontent.com/8792145/98540196-dbe6c800-228d-11eb-9952-dda453ce4d44.png)

vs. 

![image](https://user-images.githubusercontent.com/8792145/98540254-f1f48880-228d-11eb-8800-a6aad2495ec6.png)

**Comment by weisswurstkanone** [comment]
Same is true for the class definition. In the class editor, try to right click on the root node.

![image](https://user-images.githubusercontent.com/6142086/103554503-53605e80-4eaf-11eb-81e5-3523da80adff.png)
