### ISSUE TITLE
Deprecate Translation\Website|Admin introduce Translation

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#7504]
Introduce new `Translation` Model, which just extends `AbstractTranslation`. 

Deprecate: 
`AbstractTranslation`
`Website` (incl. sub-classes)
`Admin` (incl. sub-classes)

New translation model should have "domain" support and persist each domain in a dedicated table ( e.g. `translations_DOMAIN`), if the table doesn't exist, it should be created automatically. 

We should also make `messages` as the default and don't use `website` anymore.

**Comment by dvesh3** [comment]
Fixed by #7800
