### ISSUE TITLE
Deprecate PageSnippet::$module and PageSnippet::$action

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#7516]
Including their getters & setters. 
That's because Symfony 5 only supports the `AppBundle\Controller\FooController::barAction` notation. 

Also change DocTypes as well as StaticRoutes accordingly.

**Comment by dpfaffenbauer** [comment]
A proper migration would be handy there.... Otherwise it's a pain in the a** to manually do that. Should be possible to automatically migrate right?

**Comment by brusch** [comment]
Resolved by #7517
