### ISSUE TITLE
Problems with exports on replicated instances with shared folders

### ISSUE THREAD

**Issue by kubaplas** [pimcore/pimcore#7521]
### Expected behavior
Exports (like csv from grid or reports) work correctly.
### Actual behavior
On a replicated instance using Kubernetes and NFS share as a shared folder for tmp/ etc folders, sometimes exports are not complete. It seems that due to the nature of NFS, if consecutive writes are done too quickly (as can happen during export from admin panel), the write will not propagate to the other replicas, which can be next to write to the file, resulting in desynchronisation of file contents and missing lines in export.

### Possible solution
Replace current file write method (fopen, fwrite, fclose) to the one corresponding to the `echo "sth" >> file` from Unix. This could guarantee that the data will not be lost, although it may be in incorrect order.
Maybe file_put_contents with FILE_APPEND flag is a solution here? I'm not sure how it works under the hood.

**Comment by brusch** [comment]
Probably best to use an object storage instead and configure it using Flysystem: 
https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/File_Storage_Setup.html
