### ISSUE TITLE
editable type "input" validation not implemented in Pimcore 4.x

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#753]
```php
//basic in-built validation
<?= $this->input("headline", ["vtype"=>"alphanum"]); ?>
```
this advice has no effect on validation. however, the docs describes validation possibilities for input elements here: https://www.pimcore.org/wiki/display/PIMCORE4/Input#Input-Validation

**Comment by mrudnicki** [comment]
At the moment, you can only use validator passed as an argument. 
Example:

```<?php echo $this->input('test_validation', [
    'validator' => new Zend_Json_Expr('function(value){
        console.log(value);
        return value == "test" ? true : "bad value";
    }')
]); ?>````

Unfortunately, it only provides the visual indicator to invalid elements. You can still save a document.

In the future, we will discuss improvements in documents validation.

**Comment by julmot** [comment]
Is there any news in terms of brick editables validation? I'd also like to specify a set of mandatory editables within a brick.
