### ISSUE TITLE
[Document] Select Editable: Behavior for default values

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#7533]
# Bug Report

I just tested what should be the future 6.8.5 release and similar to #6459, any defaultValue is not available unless the panel has been opened and saved, rendering `getData()` useless.

### Expected behavior

`defaultValue` should be made available via `getData()`

### Actual behavior

Default value is not returned.

### Steps to reproduce

This code:
```php
            [
                'type' => 'select',
                'label' => $this->translate('brick.options.label.background-colour'),
                'name' => 'backgroundColorConfig',
                'config' => [
                    'store' => $this->getColors(),
                    'width' => 300,
                    'defaultValue' => '#232736',
                ],
            ]

```

### Code example
This returns `null`
```twig
{% set backgroundColor = pimcore_select("backgroundColorConfig").getData() %}
```

# Feature Request

**Comment by cadeyrn** [comment]
It's more like #6458 than #6459.

**Comment by brusch** [comment]
There we should have the same behavior as with the default values at data objects. 
Since it's a BC break anyway, we can discuss this topic for v7.

**Comment by NiklasBr** [comment]
I do not agree that this should be pushed to Pimcore 7 @brusch, since it was the new dialogue box which introduced the BC break in the first place and fixing this now would solve the BC break. Something which should be done in 6.x.

The primary problem here lies in the fact that previously you had the settings in the editable itself, embedded in the document. So when adding a brick to a document and then you saved the document, the default value would saved and then exposed through the `getData()` method, however, since the settings are not loaded the same way in the dialogue box, even when saving the document the data is no longer exposed through the `getData()` method.

So, now the getData() method was actually changed in 6.x in a breaking way, and I would like it to remain as it was previously: Compatible with the old way. This is why I consider this a bug and not a change to be punted to 7.

**Comment by brusch** [comment]
I do not agree that the editable dialog box introduced a bc break! This is just wrong,  it is a new feature and the behavior is as it is. So changing it would be a bc break.

**Comment by NiklasBr** [comment]
Are we talking about the same thing @brusch? It reads like and feels like you are dismissing my concern without considering or explaining the impact.  _You literally wrote in the documentation_ that they should behave the same way, but in this issue you claim it should be different. I don't understand.

> [...] you can use all supported editables in a structured layout in the context of the current brick. The editing interface is configured by implementing the EditableDialogBoxInterface on your brick class and by providing a simple config array.
>[...]
> Accessing Data of the Editable Dialog
> The editables in the dialog are just normal editables, there's **_not difference to editables which are defined via the template_**. So can either use them as well in the template or access them in your custom code.

My emphasis. Either the above documentation is incorrect or the implementation is not working the way the documentation says it does. And to me the documentation makes most sense because I cannot imagine why anyone would be content with the way it works now.

**Comment by brusch** [comment]
#7477 #6458 #6459 didn't change the behavior, just updated the docs accordingly. 

The behavior of the default value used with the select editable should be therefore identical, no matter in which context it is used.
