### ISSUE TITLE
Bugs with ExtJS 6.0 and Chrome (Version 52.0.2743.82 m)

### ISSUE THREAD

**Issue by rolandstoll** [pimcore/pimcore#756]
### Expected behavior 
- Chrome works like Firefox
  
### Actual behavior  
on Chrome (Version 52.0.2743.82 m / Windows 10)
- objects: localized fields look broken for 2nd, 3rd, ... language tab
- assets: "uploading files" is broken, only compatibility mode works)
  
### Steps to reproduce  
with Chrome:
- open "https://demo.pimcore.org/admin/login/deeplink?object_4_object" and click on language tab "German"...
- try to upload an asset

**Comment by brusch** [comment]
Unable to reproduce, ... see the following: 

[21-07-_2016_12-36-00.zip](https://github.com/pimcore/pimcore/files/375711/21-07-_2016_12-36-00.zip)

**Comment by rolandstoll** [comment]
Hi Berhard!
tried on Chrome/Windows (10)?
here is how it looks on my Windows 10 Laptop with latest Chrome:

[demo.pimcore.org __ pimcore - Google Chrome 21.07.2016 13_34_03.zip](https://github.com/pimcore/pimcore/files/375855/demo.pimcore.org.__.pimcore.-.Google.Chrome.21.07.2016.13_34_03.zip)

**Comment by brusch** [comment]
Just updated chrome to the latest version, but still now problem. 
Also tested it on BrowserStack, again, no Problem. 
Have you tested it without extensions (Inkognito-Mode)?

**Comment by rolandstoll** [comment]
ok, that seems to be something really weired...
just tested it on my (private) laptop at home - all good - same OS, same browser...
must be something "special" on my office device (Surface Pro 3)... will try to investigate further the next days...

thanks so far!!
/close
