### ISSUE TITLE
Listings getById() not working with IN operator and or multiple IDs

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#7560]
# Bug Report

My Code:

```
            $tagIds = [16,27];
            $listing = (new \Pimcore\Model\DataObject\TagIndustry\Listing())->filterById($tagIds,"IN")->setUnpublished(false);
            $listing->count();
```

The exception thrown by Symfony:

> An exception occurred while executing 'SELECT COUNT(*) AS `totalCount` FROM `object_localized_TAG_INDUSTRY_de` WHERE (((`o_id` IN ?) AND object_localized_TAG_INDUSTRY_de.o_type IN ('object','folder')) AND object_localized_TAG_INDUSTRY_de.o_published = 1)' with params [16, 27]:
> 
> SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens

According to the method this should work:

```
    /**
     * Filter by id (system field)
     *
     * @param string|int|float|float|array $data  comparison data, can be scalar or array (if operator is e.g. "IN (?)")
     * @param string $operator  SQL comparison operator, e.g. =, <, >= etc. You can use "?" as placeholder, e.g. "IN (?)"
     *
     * @return static
     */
    public function filterById($data, $operator = '=')
    {
        $this->addFilterByField('o_id', $operator, $data);

        return $this;
    }
```

Therefore I guess it is a bug (Pimcore version is 6.8.4)?

If it helps - my temporary fix works (seems not like a good way to go though)?         
```
$listing = (new \Pimcore\Model\DataObject\TagIndustry\Listing())->addConditionParam('`o_id` IN ('.substr(str_repeat("?,",count($tagIds)),0,-1).')', $tagIds)->setUnpublished(false);
```

**Comment by jdreesen** [comment]
I noticed this too and fixed it like this for now:

```php
final class Sql
{
    public static function createInArrayOperator(array $data): string
    {
        return sprintf('IN (%s)', implode(',', array_fill(0, count($data), '?')));
    }
}

$groups = (new Group\Listing())->filterByKey($keys, Sql::createInArrayOperator($keys));
```

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
