### ISSUE TITLE
DeepCopy cache object problem

### ISSUE THREAD

**Issue by kamilkosciuk** [pimcore/pimcore#7565]
In pimcore 6.8 (latest) + coreshop 2.2.6 there's bug while creating deepcopy of object CoreShopOrder. Cache item created recursively when currency is set for CoreShopOrder is holding too much data (around 900KB) causing orders list to crush 

Attaching file with what is saved in single cache item in redis. 

[CoreShopOrder cache item.pdf](https://github.com/pimcore/pimcore/files/5562758/CoreShopOrder.cache.item.pdf)

Setting currency in order to null solves that but thats temporary solution.

**Comment by dpfaffenbauer** [comment]
DeepCopy ignore DoctrineCollections is the solution here

**Comment by kamilkosciuk** [comment]
Thanks, seems like it will help, could it be done by config settings somehow now?

**Comment by ramundomario** [comment]
> Thanks, seems like it will help, could it be done by config settings somehow now?
> 
> adding filter like that helps
> $copier->addFilter(new DoctrineCollectionFilter(), new PropertyTypeMatcher('Doctrine\Common\Collections\Collection'));
> could it be done globally without overwriting stuff?

Yes, for a quick fix you can add through an Event subscriber or listener.
I'm using an Event subscriber like this:

```php
<?php

namespace AppBundle\EventSubscriber;

use DeepCopy\DeepCopy;
use DeepCopy\Filter\Doctrine\DoctrineCollectionFilter;
use DeepCopy\Matcher\PropertyTypeMatcher;
use Pimcore\Event\SystemEvents;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\EventDispatcher\GenericEvent;

class DeepCopySubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return [
            SystemEvents::SERVICE_PRE_GET_DEEP_COPY => 'addDoctrineCollectionFilter',
        ];
    }

    public function addDoctrineCollectionFilter(GenericEvent $event)
    {
        /**
         * @var DeepCopy $copier
         */
        $copier = $event->getArgument('copier');
        $copier->addFilter(new DoctrineCollectionFilter(), new PropertyTypeMatcher('Doctrine\Common\Collections\Collection'));
        $event->setArgument('copier', $copier);
    }
}
```

**N.B:** Don't forget to register the Event subscriber

**Comment by kamilkosciuk** [comment]
Thanks for that @ramundomario, works nicely! Only one change for the record (already changed in my post above) - a filter that solves a problem is 
$copier->addFilter(new SetNullFilter(), new PropertyTypeMatcher('Doctrine\Common\Collections\Collection')); 
which is disabling doctrine collections from deepcopy as @dpfaffenbauer suggested
closing an issue
