### ISSUE TITLE
Tree gets broken if you move several times documents or objects 

### ISSUE THREAD

**Issue by m3allim** [pimcore/pimcore#7567]
Pimcore version 6.5.2
Move an object or an document per drag and drop in the tree for several times.
The tree becomes broken and you have to reload the page.
![image](https://user-images.githubusercontent.com/2891496/99640722-95d9f300-2a49-11eb-96c5-301cedaeda54.png)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
