### ISSUE TITLE
Output cache always gets cleaned even if lifetime is set in settings part 2

### ISSUE THREAD

**Issue by timhonders** [pimcore/pimcore#757]
I patcht my files from the fix: https://github.com/pimcore/pimcore/issues/754

But all the output cache still gets cleand on save, because of the $this->defaultCacheKey has the "output_" prefix in it 

i added 

        $output_prefix = "output";
        if($this->lifetime) {
            $output_prefix = "output_lifetime";
        }

        $this->defaultCacheKey = $output_prefix . "_" . md5($request->getHttpHost() . $requestUri . $appendKey);

on line 188 in Pimcore\Controller\Plugin\Cache.php

that should fix it :)

**Comment by brusch** [comment]
I tested it and the output cache was not cleared anymore, definitely. 
The invalidation is done based on tags, the key doesn't matter at all. 

See: https://github.com/pimcore/pimcore/blob/59c65b35c81e760439ce0b1c1d28ef58a94e8798/pimcore/models/Document.php#L565-L565
