### ISSUE TITLE
Adding new select options directly in the objects attribute 

### ISSUE THREAD

**Issue by Timonwatteny** [pimcore/pimcore#7570]
# Feature Request

## Feature description
When enriching a product it happens that a select field does not cover all the possibilities desired. The person enriching might not have permissions to access the class definition, which makes it impossible to finish the enriching process. 

Therefore it might be useful that this person can add a select value to the attribute. At the bottom of the select values could be a text field that allows the user to enter a new value that will create a new admin value in the select attribute.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
