### ISSUE TITLE
Checkbox has wrong value in the view of the localized fields

### ISSUE THREAD

**Issue by ascheider** [pimcore/pimcore#7573]
How to reproduce:
Import class in pimcore: 
[class_LocalizedFieldsView_export.json.zip](https://github.com/pimcore/pimcore/files/5572764/class_LocalizedFieldsView_export.json.zip)

create languages and fallback languages like in screenshot:
![image](https://user-images.githubusercontent.com/6016485/99787694-5af6be80-2b20-11eb-92b5-28b08ea338ce.png)

create object of the type LocalizedFieldsView and activate checkbox in language 'de' but not in 'de_AT'
![image](https://user-images.githubusercontent.com/6016485/99787854-942f2e80-2b20-11eb-9519-96c10492c642.png)
![image](https://user-images.githubusercontent.com/6016485/99787894-a01af080-2b20-11eb-9085-1d27af20e898.png)

save and publish the object.
open the database view
![image](https://user-images.githubusercontent.com/6016485/99787983-be80ec00-2b20-11eb-9ca5-40185bfa91ce.png)
expected value of myCheckboxWithWrongViewValue is 0 but value is 1.

Listing uses also the views, this snippets must select only the objects which have checkbox not active in the language 'de_AT' but it selects objects which have checkbox active in 'de'

// example
$test = new DataObject\LocalizedFieldsView\Listing();
$test->setLocale('de_AT');
$test->setCondition('myCheckboxWithWrongViewValue = ?', '0');

This generated condition in the view is the problem
if((isnull(`de_AT`.`myCheckboxWithWrongViewValue`) or (`de_AT`.`myCheckboxWithWrongViewValue` = ''))

(`de_AT`.`myCheckboxWithWrongViewValue` = '') on type 'int' or 'tinyint' leads to the bug and outputs 1 instead of null

**Comment by brusch** [comment]
@ascheider Thanks a lot for your PR! Just one thing, since it's a bug, it should go into the `6.8` branch. Can you please rebase onto the `6.8` branch and change the base for this PR accordingly? Thanks a lot!

**Comment by weisswurstkanone** [comment]
@ascheider see https://github.com/pimcore/pimcore/issues/7573
