### ISSUE TITLE
Not possible to open video asset in fullscreen mode

### ISSUE THREAD

**Issue by muspelheim** [pimcore/pimcore#7585]
# Bug Report

### Expected behavior

Video preview in admin panel should have possibilities to be opened in fullscreen mode

### Actual behavior

Video opened in fullscreen mode for a super short time then it closed and the video frame reloaded

### Steps to reproduce

1. Open any video asset
2. Try to open fullscreen mode of HTML player

**Comment by rkleo** [comment]
Any news on this? Still not working.

**Comment by thampe** [comment]
Same here, I also need this feature. Is there any progress?

Thanks in advance.

**Comment by dvesh3** [comment]
already fixed by https://github.com/pimcore/pimcore/pull/12909?

**Comment by NiklasBr** [comment]
@dvesh3 It works in Pimcore 10.5 but I think there may be something odd in Pimcore 11, I can only open it for a few seconds on the demo site before it closes again with the following console messages:

![image](https://github.com/pimcore/pimcore/assets/279826/d4b131d5-e193-44ac-8f04-026acbadd978)

Note the *Exited fullscreen because fullscreen element was removed from document.* line

**Comment by thampe** [comment]
As far as I can tell it does not work in 10.5.* (tested with 10.5.22).

**Comment by rkleo** [comment]
> already fixed by #12909?

Unfortunately not, that issue references a different problem.

Here we have arbitrary video files which gets uploaded and previewed in the backend. The iframe is created by this JS code:

https://github.com/pimcore/pimcore/blob/10.5/bundles/AdminBundle/Resources/public/js/pimcore/asset/video.js#L322

But I am not sure that adding `allow="fullscreen"` actually solves the problem, it seems to be correlating with backend JS or something, as a fullscreen windows gets opened for a split second and then weird window resizing stuff happens, iframe seems to reload etc.

Browser I am experiencing this in: current Chrome on macOS 13.3

**Comment by kingjia90** [comment]
I've found the culprit: 
https://github.com/pimcore/pimcore/blob/40cbb679c9755f3ff66c8f290cc390409328b16b/bundles/AdminBundle/Resources/public/js/pimcore/asset/video.js#L122
whenever is resized (fullscreen included), it reinitializes the video html tag.
Will provide the PR that fixes it

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/15362

**Comment by rkleo** [comment]
Big thanks to all of you!
