### ISSUE TITLE
Update a questionnary on PIMECORE not working

### ISSUE THREAD

**Issue by Gab19871006** [pimcore/pimcore#7613]
Dear,

I do not have the posibility to update the questionnary that I linked to an account that I manage. I do not knwo why it does not work. 
Could you please take a look and get back to me ASAP as the corporate website should be alerady done by now. 

https://www.preinscriptioncreche.com/admin/?_dc=1606487626   

The bellow does not want to be uploaded. The question coming on the web site are not linked and there is juste a blank page.

Thank you for your time. 

Kind regards,

Gabrièle.silga@people-and-baby.com
+33 7 66 72 69 79 

What way should I use to the proper results on the web site?
-->

### The update of the questionnary is well confirmed, but the web site does not show up the questions. 

Regards,

### Code example
```php
// your code
```

# Feature Request

**Comment by brusch** [comment]
This is not the right place to get support. 
You can either use our community support ( talk.pimcore.org) or our enterprise offering on https://pimcore.com
