### ISSUE TITLE
Search in grid view not working with apostrophe

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#7620]
Hi,

When searching in grid view no results are shown when there is an apostrophe (') in the query:

![image](https://user-images.githubusercontent.com/41229269/100542794-a4e05280-324c-11eb-87ef-677f5fc5557b.png)

It should give this result:

![image](https://user-images.githubusercontent.com/41229269/100542807-b9bce600-324c-11eb-9b92-a6a53acdba01.png)

**Comment by Hbitvof** [comment]
Additional to this issue, there is also a problem with the search when a number is used in the search:

No results:

![image](https://user-images.githubusercontent.com/41229269/100584181-0a375080-32ec-11eb-9adc-2d1faf4b3617.png)

Without the 4 result:

![image](https://user-images.githubusercontent.com/41229269/100584223-1b805d00-32ec-11eb-9a76-5718a20938c5.png)

**Comment by Hbitvof** [comment]
Can anyone look at this issue?

**Comment by kingjia90** [comment]
@Hbitvof Does this still happen with a later version (at least 10.3.7) of Pimcore? 
It should be fixed, i am closing this. If it's still happening, please re-open and i will personally take a look to it

**Comment by Hbitvof** [comment]
> @Hbitvof Does this still happen with a later version (at least 10.3.7) of Pimcore? It should be fixed, i am closing this. If it's still happening, please re-open and i will personally take a look to it

Just tested this in v 10.4.3 and I can confirm this is fixed.
