### ISSUE TITLE
Cannot target field in an object brick which is being referred inside a class --> block --> panel

### ISSUE THREAD

**Issue by hellosmriti** [pimcore/pimcore#7621]
Below is my class (Offers) setting with object brick (CTAs) inside a Block --> Panel

![image](https://user-images.githubusercontent.com/54179597/100579033-6f4d6f00-3309-11eb-9570-04af5170f2f2.png)

Below is the object brick (Info) setting which I wish to refer in this:

![image](https://user-images.githubusercontent.com/54179597/100579194-c3585380-3309-11eb-8440-cb636de827ba.png)

I'm not able to select the field (CTAs) from the class (Offers).

However if I move object brick field (CTAs) out of the block inside the class (Offers), I can select field (CTAs) from the class (Offers) in object brick (Info) setting.

**Comment by aarongerig** [comment]
@hellosmriti AFAIK object bricks are not supported inside blocks.

**Comment by hellosmriti** [comment]
![image](https://user-images.githubusercontent.com/54179597/100579798-d9b2df00-330a-11eb-9e7c-e8cd8a512d1b.png)

but then, it gives the option of adding it in hierarchy **block --> panel --> object brick**.

Yes, but directly in a block, it doesn't **block --> object brick**.

![image](https://user-images.githubusercontent.com/54179597/100579944-17176c80-330b-11eb-8fd2-109f237fcc18.png)

**Comment by weisswurstkanone** [comment]
related: https://github.com/pimcore/pimcore/issues/6325

**Comment by weisswurstkanone** [comment]
currently even forbidden on UI side but it seems that putting a panel inbetween breaks the check. so in other words, if you remove the panel and try to add the object brick this wouldn't be possible as @aarongerig said correctly.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
