### ISSUE TITLE
[Feature request] Document\Link permanent redirect or not

### ISSUE THREAD

**Issue by michaelclaesson** [pimcore/pimcore#7638]
# Feature Request
Ability to select whether link should be permanent or not

## Feature description
It would be great to be able to select whether we want a permanent or a temporary redirect for our documents of type link. Right now they always end up being a 301 which is a shame since the browser caches this without expiry. If this link changes on a monthly basis for instance it would be great if the browser fetches the latest link.

**Current**
```
private function handleLinkDocument(Document\Link $document, DocumentRoute $route)
    {
        $route->setDefault('_controller', 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction');
        $route->setDefault('path', $document->getHref());
        $route->setDefault('permanent', true); 

        return $route;
    }
```

**Could be (with proper setting checkbox of course)**
```
private function handleLinkDocument(Document\Link $document, DocumentRoute $route)
    {
        $route->setDefault('_controller', 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction');
        $route->setDefault('path', $document->getHref());
        $route->setDefault('permanent', $document->getPermanent()); 

        return $route;
    }
```

https://github.com/pimcore/pimcore/blob/master/lib/Routing/Dynamic/DocumentRouteHandler.php#L211

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
