### ISSUE TITLE
[Asset] Clear thumbnail only if data has changed

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#7648]
See: https://github.com/pimcore/pimcore/blob/5aa21e2519a47fd1a1b76625849cd820592f9ae1/models/Asset/Image.php#L74

It's not necessary to clear thumbnails if the original data hasn't changed.

**Comment by dvesh3** [comment]
@brusch this is the case in clearThumbnails() method, unless you pass `$force = true`, 
https://github.com/pimcore/pimcore/blob/e9c2de157e5888e9bbc6267428bdf5cb400735c3/models/Asset/Image.php#L298-L300
