### ISSUE TITLE
Saving a Preview / Iframe layout component without iframeUrl or renderingData in a Custom Layout throws error

### ISSUE THREAD

**Issue by alexthunder3** [pimcore/pimcore#7649]
### Expected behavior
Add an empty preview / iframe to a custom layout and save. An empty preview / iframe has been saved to the layout without errors.

### Actual behavior
When first saving an empty preview / iframe to a custom layout, it throws an error. Removing the preview / iframe does not make the error go away. The same error also shows up when trying to open an object using that layout, or when clicking the layout selection dropdown (top left in the "Custom Layout Definition" window).
![Screenshot from 2020-12-02 13-32-55](https://user-images.githubusercontent.com/20271194/100878610-b45cd700-34aa-11eb-979d-976313607a15.png)

### Steps to reproduce
In the Admin area go to Settings, Data Objects, Classes. 
Open a Class, click the bottom right button "Configure Custom Layouts".
Select a Layout from the top left dropdown.
Right click a "Panel" (three blue horizontal lines, with middle one being thicker and a darker shade of blue), "Add Layout Component", "Preview / Iframe".
Save Layout.

### Quick Fix
open var/classes/customlayouts/custom_definition_id.php (where "id" is the Layout ID)
search "iframe", replace NULL with ' ' (empty string).

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
