### ISSUE TITLE
Notes not editable

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#766]
# Bug Report  
### Expected behavior 
Create a note on a document and have the ability to edit it later.
### Actual behavior  
Created notes can not be edited.
### Steps to reproduce  
Create a note on a document:
![pimcore-notice](https://cloud.githubusercontent.com/assets/2771909/17105080/f633c410-5285-11e6-90eb-caf4ce8bd21f.png)
After saving it, go to Notes & Events and click the pen to edit. Nothing happens:
![pimcore-notice-edit](https://cloud.githubusercontent.com/assets/2771909/17105094/03aaf096-5286-11e6-8ae8-694e21e4c874.png)

The newsletter entries can be edited though.

Tested on the latest online demo at pimcore.org

**Comment by brusch** [comment]
Editing notes & events is not possible, maybe the icon is a bit misleading in this case :) Clicking on the action column opens the corresponding element and not an editing dialog. 
I've changed the icon to something more meaningful: 
![image](https://cloud.githubusercontent.com/assets/142037/17126977/4436dbc6-5302-11e6-8359-83557ea191de.png)

**Comment by Cruiser13** [comment]
Thank you for the clarification @brusch 
It seems inconsistent to me that we can edit the newsletter entries there and the notes can't be edited.

Is there a reason notes can not be edited or removed? Otherwise I'd add a feature request for that functionality.

**Comment by brusch** [comment]
Yes, there's actually a reason why it's not possible to edit entries in notes & events. The idea behind this feature was to provide a kind of logging functionality, so that you can see what happened to an element in pimcore (eg. when using importers, ...). Normally you don't edit log entries, because this would distort your audit trail.

**Comment by Cruiser13** [comment]
I see. Seems we're misusing this feature a little bit. Thanks!
