### ISSUE TITLE
[UX] Workflow Transition for modified DataObject

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#7660]
It is currently possible to trigger a Workflow Transition even though the Object (guess also Asset/Document) has modifications. That ends up in loosing all changed stuff and having an "empty" DataObject again.

What do you think if we just add a Popup message telling the User that there are unsaved changes?

**Comment by dnaponobears** [comment]
This sounds like the same problem that I'm experiencing. In my case an 'Element has unsaved changes' popup shows up, but the workflow button does not seem to await the result of this confirm dialog. After some digging around, this appears to be a bug in the `submitWorkflowTransition` function, which can be found in AdminBundle/Resources/public/js/pimcore/workflow/transitionPanel.js.

![image](https://user-images.githubusercontent.com/61834167/103365207-d5234700-4abf-11eb-9748-7c312b122503.png)

This function does not check for changes in the object before making a request to the WorkflowController::submitWorkflowTransitionAction. I would expect it to do a check similar to `_confirmDirtyClose`, which can be found in bundlesAdminBundle/Resources/public/js/pimcore/element/abstract.js.

![image](https://user-images.githubusercontent.com/61834167/103365297-0b60c680-4ac0-11eb-8274-4a4fc76cb27a.png)

**Comment by RuudvdvNB** [comment]
@fashxp this looks like a bug in Pimcore because changing the workflow state does not check for changes inside the current tab, this results in empty objects.

**Comment by fashxp** [comment]
I guess @dpfaffenbauer 's approach would be the best to solve this. I don't think it is a good idea to save changes implicitly when triggering workflow transitions...

**Comment by RuudvdvNB** [comment]
When we have unsaved changes the popup with the notice of unsaved changes is shown. But in the background the workflow state is submitted and the popup is ignored. 

I agree that the workflow transitions shouldn't implicitly save changes.

**Comment by RuudvdvNB** [comment]
@fashxp any expectations on when you're able to fix this? It's causing issues with product data at the moment in production environments that are using workflows to manage products.
