### ISSUE TITLE
[Assets] pdf thumbnails are not being created / getPageCount() = null

### ISSUE THREAD

**Issue by dev-flti** [pimcore/pimcore#7665]
# Bug Report

### Expected behavior
Thumbnails for pdf files should be generated and shown in asset area & no errors
### Actual behavior
no thumbnail available and by adding it to a document following error appears: 
- getPageCount() returns null
- Preview Thumbnail of pdf is not being created
### Steps to reproduce
1. Go to your Demo Site
2. Download a pdf file out of asset folder
3. upload same pdf again
4. check if thumbnail is there (it is not)

**Comment by brusch** [comment]
See: 
#6001
#3974
#6190
#7363
