### ISSUE TITLE
Add right click context menu to "recently opened elements"

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#7668]
* open element
* etc...

![image](https://user-images.githubusercontent.com/6142086/101097806-26740f80-35c2-11eb-932e-478af1801023.png)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
