### ISSUE TITLE
Exporting asset details are skipping the size property

### ISSUE THREAD

**Issue by Karthi96** [pimcore/pimcore#7669]
# Bug Report

### Expected behavior
As a user, I should be able to export all the attributes listing on GridView under assets
### Actual behavior
I was able to export but the size property is not exporting in that
### Steps to reproduce
Click on the asset folder and you will see the properties of assets on the right side. Try to export all the properties of the asset

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
