### ISSUE TITLE
Improvement Class Deployment - move configurations to PHP-file

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#767]
in order to improve deployment features move following information from database to psf-files:
* allowInherit
* allowVariants
* parentClass
* useTraits
* icon
* previewUrl
* showVariants
* group

**Comment by ThomasKeil** [comment]
Would it be possible to use nicely formatted XML instead of serialization? This would be very useful to use with Version Control Systems like Git.

**Comment by fashxp** [comment]
xml for sure not, but maybe switch to php-files like all the other configuration files?

**Comment by ThomasKeil** [comment]
Yes, my bad - of course something that suites the current configuration file strategy.

Anything that can be used with line based VCS and is not a one-liner like psf  :-)

**Comment by brusch** [comment]
Idea: also the ID?

**Comment by cleggypdc** [comment]
Good to see this discussion as I'm making a similar decision for an extension. Perhaps all of the information in this table? If the creation/modification dates were in a php file for instance you could quickly compare those values in deployment.

**Comment by brusch** [comment]
All configurations of a class definition are now stored in a PHP file in `/website/var/classes/definition_NAME.php` . 
The file name and the content of the file do not contain any ID anymore, so it makes it very comfortable to manage them in a VCS. 
The name <=> ID mapping is still in the database (classes table).
