### ISSUE TITLE
Improvement: EditableDialogBox - Auto-Add Editables to View

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#7673]
<s># Description
By automatically adding the `Editable`s defined in the `EditableDialogBox` to the view, the maintainability increases significantly, as there is **only one source of truth**. 

Imagine a config like this:

```php
$config->setItems([
    [
        'type' => 'textarea',
        'name' => 'exampleText'
    ],
]);
```

In case the client wants to change this to a `WYSIWYG` later on, one has to change the PHP-code _and_ **every** part of the template that acceses the conifg using the `pimcore_*` twig functions.

Of course, this also implies that another twig function is needed to properly render the `Editable`s: `{{ pimcore_render_editable(exampleTextEditable) }}` that were automatically added to the view.

> Appending the word *Editable* to the name of the `Editable` to create the variable will help avoiding collisions with user defined variables.

###### Additional Thoughts
This will further allow to deprecate the `pimcore_*` functions, as one can now define the `Editable`s in the `action` method of the `brick` (or in the `getEditableDialogBoxConfiguration` method), thus, resutling in even cleaner templates.</s>

---

### Update
Coming back to this after some time, the suggested approach seems a bit off. Instead, maybe we can automatically add the `EditableDialogBoxConfiguration` instance to the template and provide getters for the available editables:

```twig
{{ editable_dialog_box_configuration.my_editable_name }}
```

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.

**Comment by passioneight** [comment]
Hey @fashxp, may I suggest to shift gears a bit and focus on _relevancy_ instead of the _timestamp_ of an issue?

Take this issue, for example. Even though it's been around a while, it's still really important, at least from where I stand. However, the core team never commented on what they would expect how an implementation of this feature should work, or if they even want a feature like this. Without any input, of course, there won't be any activity, but that doesn't mean it should be disregarded.

**Comment by brusch** [comment]
Hey @passioneight, our aim is to prioritize relevancy rather than simply considering how long an issue has been open. Still, we need to do some housekeeping to better manage resources, maintain focus and clarify it to the community. But to be honest, in that specific issue, we didn't completely grasp the issue. We would appreciate any clarification 😊

**Comment by passioneight** [comment]
Hi @brusch, sounds great, but I'm wondering how you are able to determine if something is relevant if you don't understand what the issue is about. 

Also, the [comment that was used to close the issue](https://github.com/pimcore/pimcore/issues/7673#issuecomment-1863086061) clearly specifies that it was closed due to being inactive:
> Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. [...]

Additionally, @fashxp also closed the following issues with the same message:
- https://github.com/pimcore/pimcore/issues/11547
- https://github.com/pimcore/pimcore/issues/11371

Are there any open questions there as well? If so, why would you not ask them before closing? If not, why are you closing issues that clearly point out bugs/ask for improvements? Surely, at least bug reportings should be relevant - espcially, if [the bug mentioned in 11547](https://github.com/pimcore/pimcore/issues/11547) seems to [still persist](https://github.com/pimcore/pimcore/blame/f2fb355d54e80f0c51e41df3ea765289ae9133f0/models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php#L725) - right?

---

As for this issue, let me try to ellaborate a bit further in the hopes to provide some clarification:

More often than not, our client requests a change which essentially implies that we need to switch from a `Textarea` to a `Wysiwyg` or vice-versa (**_for example_**). It every so often happens that these editables are part of the editable dialog, but they are still accessed or rendered in the template itself.

This means that there might be an arbitrary number of `pimcore_textarea` calls that need be replaced with `pimcore_wysiwyg` or vice-versa.

To improve developer experience, it would be great to have a single point of definition for these kinds of editables (i.e., the `getEditableDialogBoxConfiguration` method), while still being able to access the editables without using the Twig extensions. 

For example, see the following `Textarea` definition and how I could imagine accessing it:

```php
// Omitted

public function getEditableDialogBoxConfiguration(Document\Editable $area, ?Info $info): EditableDialogBoxConfiguration
{
    $config = new EditableDialogBoxConfiguration();
        
    $config->setItems([
        [
            (new Editable\Textarea())
                ->setName('example_text')
        ]
    ]);

    return $config;
}

// Omitted
```

```twig
{{ example_text.frontend|raw }}
```

Now, if the definition changes, the template stays the same. The only question left is, how we'd implement this, without adding any magic.

Hope this clears things up 😊
