### ISSUE TITLE
error_reporting Default Setting

### ISSUE THREAD

**Issue by CountZero1981** [pimcore/pimcore#7681]
The default value for error_reporting in Symfony and others on the development environment is E_ALL. So the errors of level E_NOTICE would cause execution failure. This is important, because such errors, though they're not fatal, might lead to ambiguous behaviour and data inconsistency.
Pimcore by default uses on development production settings, E_ALL & ~E_NOTICE & ~E_STRICT. Looks like the same setting is used during the core development. So its code isn't very clear and on the test environment execution failed (test env uses E_ALL by default). I've configured PIMCORE_PHP_ERROR_REPORTING=32767 to set error_reporting to E_ALL on the dev env, and with the default installation it works. However, we've made some changes (added some products/classes/objectbricks) and now it fails with the E_NOTICE error while trying to access non-existent array offset.

### Expected behavior
By default, after installation on the development environment, Pimcore uses error_reporting level E_ALL. All the errors of the class E_NOTICE are reported.

### Actual behavior
After installation on the development environment, Pimcore uses error_reporting level E_ALL & ~E_NOTICE & ~E_STRICT. The errors of the class E_NOTICE are hidden.

### Steps to reproduce
Install Pimcore, add the code which would generate an E_NOTICE error.

**Comment by brusch** [comment]
Done already for v10, see #7285 😉
