### ISSUE TITLE
Ghostscript getVersion() returns wrong format

### ISSUE THREAD

**Issue by foxgreek** [pimcore/pimcore#7683]
# Bug Report

### Expected behavior
$this->getVersion() should return string without newline
e.g. "9.50"
### Actual behavior
$this->getVersion() returns:
e.g. "9.50
"
--> if clause is always **false**

### Steps to reproduce
add **var_dump($this->version);** in Ghostscript Adapter before line 192
(We use Ubuntu 20.04.1 LTS and Ghostscript 9.50)
### Code example
```php
protected function getVersion()
{
    if (is_null($this->version)) {
        $this->version = Console::exec(self::getGhostscriptCli() . ' --version');
    }
    var_dump($this->version);
    return $this->version;
}
```

### Possible Solution
add **trim()** function to **return $this->version**
```php
protected function getVersion()
{
    if (is_null($this->version)) {
        $this->version = Console::exec(self::getGhostscriptCli() . ' --version');
    }
    return trim($this->version);
}
```
This could be a solution for #7665

**Comment by dvesh3** [comment]
Fixed by #7694
