### ISSUE TITLE
Classificationstore Exception when removing quantity-value-field value from group/key in Object

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#770]
Pimcore throws an exception when trying to remove a, already saved, value from a quantity field.

Steps to reproduce:
1. Create a classification store
2. Create a quantity value key (you also need to create a quantity-value type)
3. Create a group
4. Create a Class with the classification store
5. Create a new Object
6. Add CS-Group to Object and add some value
7. save
8. reload
9. remove the value and save
10. Throws exception

![bildschirmfoto 2016-07-26 um 11 04 59](https://cloud.githubusercontent.com/assets/5981845/17132284/5634e2cc-5321-11e6-82ed-8dad8ff34a63.png)

I also managed to reproduce it on the demo.

**Comment by weisswurstkanone** [comment]
fixed in build 3915

**Comment by dpfaffenbauer** [comment]
Yeah, thank you :)
