### ISSUE TITLE
[NotificationService] sendToGroup id lookup in varchar field

### ISSUE THREAD

**Issue by macghriogair** [pimcore/pimcore#7707]
# Bug Report

## Expected Behaviour

`NotificationService::sendToGroup` sends notification only to a user that has exactly the given role assigned.

## Actual Behaviour

`NotificationService::sendToGroup` has the following lines which may result in unexpected results depending the number of users/roles a system has:

```php

        $filter = [
            'id != ?' => $fromUser,
            'active = ?' => 1,
            'roles LIKE ?' => '%' . $groupId . '%',
        ];
```

https://github.com/pimcore/pimcore/blob/f6938e3dd8fc2158364d21f02e758a12c299eb33/models/Notification/Service/NotificationService.php#L102

With ids greater 10 this may give false results & hence notify the wrong group.

## Example

Having a group with ID 3 and a group with ID 33. The following query `select id, name,roles from users where active = 1 AND type = 'user' AND roles LIKE "%3%"` will return users attached to group 33 too.

![Bildschirmfoto 2020-12-09 um 15 10 30](https://user-images.githubusercontent.com/4060352/101641263-d4a00f00-3a31-11eb-9a19-bf31d1c33314.png)

**Comment by kingjia90** [comment]
Closing as It was fixed by https://github.com/pimcore/pimcore/pull/8990
