### ISSUE TITLE
Versions -> Delete empty folders

### ISSUE THREAD

**Issue by ckogler-elements** [pimcore/pimcore#7717]
Currently when versions are deleted only the version file get removed but the directory of the version dosn't get deleted. 
Over the time this can cause a lot of disc usage. 

Tested it with 2 Projekt:
First:
Version directory had 8,3GB and after "find ./var/versions/ -type d -empty -delete" it has only 205MB.
Second: 
Version directory had 125GB and after "find ./var/versions/ -type d -empty -delete" it has only 111GB. (3.6Million empty folders deleted)

**Comment by brusch** [comment]
We need to investigate how Flysystem deals with that, since this has changed in in Pimcore X.

**Comment by kaurov** [comment]
> Currently when versions are deleted only the version file get removed but the directory of the version dosn't get deleted. Over the time this can cause a lot of disc usage.
> 
> Tested it with 2 Projekt: First: Version directory had 8,3GB and after "find ./var/versions/ -type d -empty -delete" it has only 205MB. Second: Version directory had 125GB and after "find ./var/versions/ -type d -empty -delete" it has only 111GB. (3.6Million empty folders deleted)

I think it should only occupy the filesystem indexes, e.g. inodes. Isn't it?

**Comment by jdreesen** [comment]
This is still a problem. We have run out of inodes several times in a project because of this.
