### ISSUE TITLE
Print documents UI: new document using inheritence

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#772]
In document of type "pringpage" and "printcontainer" the dropdown option for creating new documents using inheritence is missing in the toolbar on the top.

![inheritence issue](https://cloud.githubusercontent.com/assets/9052094/17170837/369e04fc-53ee-11e6-8515-18d8991702dc.png)

Pimcore Version 4.2.0

**Comment by dpfaffenbauer** [comment]
this is not meant for inheritance only, this is meant for linked localized documents. It also does inheritance cause it makes sense for localized documents to inherit from each other.

Or am I wrong?
