### ISSUE TITLE
WorkFlowManager : Data Lost while making Action on Object

### ISSUE THREAD

**Issue by tarun-singhal** [pimcore/pimcore#773]
### Expected behavior 
It should persist the new value in Object.

### Actual behavior  
You will see saved data lost from object and it create new version with previous filled values.

### Steps to reproduce  

1. Create User who has create object rights not Publish rights
2. Login with that user.
3. Open the object and fill some information there.
4. Save the object not publish.  
5. Perform Work-flow Action like Start progress/Ready to review etc..
### Code example of "pimcore/lib/Pimcore/WorkflowManagement/Workflow/Manager.php"
```php
           $this->element->setUserModification($this->user->getId());
            if (($task === "publish" && $this->element->isAllowed("publish")) || ($task === "unpublish" && $this->element->isAllowed("unpublish"))) {
                $this->element->save();
            } elseif ($this->element instanceof Concrete || $this->element instanceof Document\PageSnippet) {
                //Below code making issue on saved version : ISSUE LN#569
                $this->element->saveVersion();
            } else {
                throw new \Exception("Operation not allowed for this element");
            }
```
If i comment the Issue line then i am able to get the expected results. But still need to identify is there any other impacts of it.

**Comment by mrudnicki** [comment]
Hello @tarun-singhal,

I've checked it, and it's true. The process is not working properly when you're logged as a user without publish and unpublish permissions. 

I try to fix it until the next week.

Thank you

**Comment by cleggypdc** [comment]
Hi @tarun-singhal,

Yes I can also re-produce this. @mrudnicki could this line being commented out have anything to do with the data loss

https://github.com/pimcore/pimcore/blob/master/pimcore/modules/admin/controllers/WorkflowController.php#L73

**Comment by cleggypdc** [comment]
Also @fashxp was that comment out (above) intentional?

**Comment by mrudnicki** [comment]
> Also @fashxp was that comment out (above) intentional?
Yes, I've also found that line. I sent the message to Christian. I think, he will explain why he has commented that line.

**Comment by fashxp** [comment]
hi guys, actually I'm not sure anymore why I commented this line. I guess it was because of an error in reasoning on my side. so @mrudnicki please just include this line again and check what happens. 
thank you very much!
