### ISSUE TITLE
HotspotImage modal window background issue with white transparent image

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#7731]
# Bug Report
When using white image with transparent background on hotspotImage field, the background merges with image on crop & marker modal window.

### Actual behavior
![image](https://user-images.githubusercontent.com/5137917/101894252-2f5a7780-3ba6-11eb-95c5-807bc2bf88ea.png)

![image](https://user-images.githubusercontent.com/5137917/101894267-34b7c200-3ba6-11eb-9977-08a6a7b2d598.png)

### Expected behavior
use checker background so that transparent images don't merge with background
![image](https://user-images.githubusercontent.com/5137917/101894294-44370b00-3ba6-11eb-8b34-aed59722a1fd.png)

**Comment by brusch** [comment]
Fixed by #7733
