### ISSUE TITLE
Quantity Value is set to zero even if no default value is given

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#7738]
# Bug Report

## Precondition
- Pimcore Version 6.6.4
- Data Object contains a quantityValue field
- the default unit is set (e.g., "m"), but the default value is left empty.

## Behavior
- when a new data object is created, the field value is initialized with "0".

## Expected Behavior
- in prior Pimcore versions the value was left empty, which is the correct behavior.
- pre-initializing the value with "0" is dangerous, as "0" has a meaning in most use cases.

I think it has to do with the refactoring that resulted in this line https://github.com/pimcore/pimcore/blob/0dd333b4796f72e16e999dc3f5f91b027eee39fa/models/DataObject/ClassDefinition/Data/QuantityValue.php#L598

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
