### ISSUE TITLE
Localized field in Objectbrick breaks the context for all the following non-localized fields.

### ISSUE THREAD

**Issue by CountZero1981** [pimcore/pimcore#7739]
# Bug Report

### Expected behavior
Pimcore displays variants in the variants grid.

### Actual behavior
Pimcore displays an error popup message "Call to a member function supportsInheritance() on null".

### Steps to reproduce
Create an ObjectBrick with two fields: one is localized, placed above another, non-localized field. Create an object of this class. Create a variant, the non-localized field must be allowed to be displayed in the variants grid. Try to open the parent object and show the variants.
Unfortunately, I'm unable to reproduce it on a demo server as it displays another error: No alive nodes found in your cluster.

### Code example
https://github.com/pimcore/pimcore/blob/b3fbaeb862479e7b3213c2a58ec4ea1e82ddb672/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php#L773-L778

**Comment by brusch** [comment]
Fixed by #7749
