### ISSUE TITLE
Newsletter.php bug, creation date changed

### ISSUE THREAD

**Issue by Latschei** [pimcore/pimcore#7742]
# Bug Report

### Expected behavior
in the newsletter.php´s subscribe method (https://github.com/pimcore/pimcore/blob/v6.8.5/lib/Tool/Newsletter.php):
if a object exists, the creation date should not be changed.

### Actual behavior
The creation date is always set to the current time (like the modification date).

### Code example
i fixed it like this: 
if(!$onlyCreateVersion) {
      $object->setCreationDate(time());
}

**Comment by dvesh3** [comment]
Fixed by #7795
