### ISSUE TITLE
[bug] Table datatype: paste clipboard on object instance don't work, it paste only one column

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#7764]
Hello,

On a table datatype on an object instance, using "paste" feature, it only fill the first colum.
I tried with | , ; as data separator with or without " or ', but it always fill juste the first column.
Is there some specific format to use or is there a bug to fix ?

On the online demo create a class like:

![image](https://user-images.githubusercontent.com/9025839/102276452-198ede80-3f27-11eb-9a98-11528aa611f3.png)

Create an object, open the paste popin:

![image](https://user-images.githubusercontent.com/9025839/102276696-77232b00-3f27-11eb-9e1e-334afdfa58d1.png)

And copy/paste date like:
```
keyA|valA
keyB|valB
```
(this is format used here: https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Table.html)

It gives:

![image](https://user-images.githubusercontent.com/9025839/102276732-87d3a100-3f27-11eb-9222-fcb2f340c719.png)

Use case: if data comes from a CSV files having many lines and that data are updated regularly, using paste feature is very conveniant for this as it prevent having to fill all manually!

Best regards.

**Comment by weisswurstkanone** [comment]
Procedure would be to mark the cells in your Excel sheet you want to copy.

![image](https://user-images.githubusercontent.com/6142086/102328354-3eb33980-3f87-11eb-9014-43e5a5aaf16d.png)

Copy and paste it, worked for me ...

**Comment by weisswurstkanone** [comment]
As far as I read the code and compare it with the scenario described the cells are seperated using a tab (which is different compared to the format used in the class definition for default values)

**Comment by weisswurstkanone** [comment]
see https://github.com/pimcore/pimcore/blob/2af4b312d48902e2d3cf47eb5b864067a47aac1d/bundles/AdminBundle/Resources/public/js/pimcore/object/tags/table.js#L354

Could you please clarify this in the docs and provide a PR with a nice example ?

**Comment by Yivan** [comment]
Thanks @weisswurstkanone , it works fine knowing this ! : )
I just created a pull request: https://github.com/pimcore/pimcore/pull/7779
Feel free to adpat it if necessay before merging.
Thanks.
