### ISSUE TITLE
Collapsed panel without title breaks closing of objects

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#778]
Steps to reproduce:
- create a class with a collapsed panel without title
- create an object of this class
- open the object
- try to close the object 

=> total Pimcore will crash and only a reload of the backend will help (but the object will never really be closable)

Reproducible in the latest Pimcore demo instance

**Comment by markus-moser** [comment]
Additional hint: maybe this just occurs as the panel is collapsible in this case allthough the "Collapsible" checkbox isn't checked in the class editor?

**Comment by mrudnicki** [comment]
@markus-moser , I've tested it and you're right. 
The issue occurs, when a panel collapsed option is checked but is not collapsible (in that case there is an exception thrown by ExtJS).

The one solution is to make the relation for both options. I look into the problem deeper Today and Tomorrow.

**Comment by weisswurstkanone** [comment]
could be this one (the stack trace could be the same as far as I remember)
https://www.sencha.com/forum/showthread.php?306212

**Comment by markus-moser** [comment]
many thanks!
