### ISSUE TITLE
Twig helper pimcore_device() is not detecting inside areablocks

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#7802]
# Bug Report

Consider the following structure:

pimcore/templates/snippet/footer.html.twig
```twig
{{ pimcore_areablock('footer_content', {
    allowed: areaConfigsFooter,
    limit: 1,
    controlsAlign: 'left',
    params: {
        columns: {
            renderOuterDiv: false,
            maxNumOfColumns: 3,
            gridSizePerColumn: 3
        }
    }
}) }}
```

pimcore/templates/Areas/columns/view.html.twig
```twig
{{ dump(pimcore_device()) }}
```

### Expected behavior

`pimcore_device()` should be able to detect the device in included template files, especially if the device type is forced using the `forceDeviceType=` query parameter.

### Actual behavior
It's always *default* and not detected:

![image](https://user-images.githubusercontent.com/279826/102885448-a9ff7e80-4453-11eb-8db8-5bb5a3428716.png)

**Comment by brusch** [comment]
Actually this works, but it's necessary to call one of the public methods of the device detector, e.g. 

```twig
{{ dump(pimcore_device().isDesktop) }}
{{ dump(pimcore_device().device) }}
...
```

Reason: `determineDeviceType()` needs to be called first.

**Comment by NiklasBr** [comment]
> Reason: `determineDeviceType()` needs to be called first.

This is not clear in the documentation or in the code, can you update the documentation so that it is clear why that is needed? I just followed this example:

![image](https://user-images.githubusercontent.com/279826/114371245-99008780-9b80-11eb-841e-d2706f536cf7.png)

**Comment by brusch** [comment]
Sure, done in f6d6b1175e36170f449a84929f782295253d42ce 😊

**Comment by NiklasBr** [comment]
Thanks!
