### ISSUE TITLE
Ecommerce | Index Service | Elastic Search Timeout Settings

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#7803]
# Improvement
Support timeout in Elastic Search requests.

### Expected behavior
It should be possible to set the timeout of an Elastic Search (ES) request, ideally in milliseconds.
The parameter can help to avoid performance issues on ES server bottlenecks.

### Current behavior
There is already a timeout parameter in the product list service:
https://github.com/pimcore/pimcore/blob/8e02b8deca7fb75ad25dea9e6750228ba8b20d91/bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php#L40
However, the implementation is missing.

### Solution Suggestion
In https://github.com/pimcore/pimcore/blob/84313b448af88570e7e8deeb721e5ea3be64949f/bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php#L189

add the following lines: 

```php
$builder = \Elasticsearch\ClientBuilder::create();
$builder->setConnectionParams([
    'client' => [
        'curl' => [
            CURLOPT_TIMEOUT_MS => $timeout
        ]
    ]
]);

```

We could change the signature of
 ``public function getElasticSearchClient()`` to ``public function getElasticSearchClient(array $customConnectionParams = [])``

and then pass the ``timeout`` variable of https://github.com/pimcore/pimcore/blob/8e02b8deca7fb75ad25dea9e6750228ba8b20d91/bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php#L40

as a parameter.  It is very handy to use ms insead of seconds for testing purposes. With this approach, ms (CURLOPT_TIMEOUT_MS) can still be passed by overriding ``AbstractElasticSearch`` and providing the parameter in the array directly.

----

I can create a PR as soon as we agree on the solution.

**Comment by fashxp** [comment]
sounds like a plan 👍

**Comment by andreas-gruenwald** [comment]
I found a way so configure the parameters without changing the signature.
Also, I think it is an improvement to set default timeout values (although they are set pretty high to avoid unwanted effects).
