### ISSUE TITLE
Remove Device Detector

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#7807]
follow up to #7806

**Comment by NiklasBr** [comment]
I think it is too premature to do this since Google says:

> Once UA-CH ships as an alternative means for browser-specific content adaptation, we would like to freeze the User-Agent string. 

The device detector will continue to be useful since the user agent header will be replaced with user agent client hints, so generalised feature detectors like this will still be able to work just fine.

**Comment by brusch** [comment]
I agree that there is no ultimate decision yet, but it seems that UA client hints are the way to go in the future. 
In my opinion this little helper can just live as project code or maybe even in an additional toolbox for Twig/Pimcore.

**Comment by NiklasBr** [comment]
The U-A Client Hints is still an *unofficial draft* meaning we have **years** left of fully working User Agent strings. And the usage of Pimcore's device detector aligns with the default allowed headers in `Sec-CH-UA-Mobile`.

> User agents will attach the `Sec-CH-UA` header to every secure outgoing request by default, with a value that includes only the significant version (e.g. `"Chrome"; v="69"`). They will also attach `Sec-CH-UA-Mobile` headers by default. Servers can opt-into receiving more detailed UA information using the other available Client Hints, by delivering an `Accept-CH` header opt-in, that includes the information they are interested in.

**Comment by brusch** [comment]
https://github.com/suncat2000/MobileDetectBundle
https://github.com/bes89/mobiledetect-twig-extension

Are probably appropriate replacements.
