### ISSUE TITLE
pimcore as module via composer with own public folder as webserver root

### ISSUE THREAD

**Issue by MajPay** [pimcore/pimcore#781]
I am trying to set up a pimcore installation with pimcore added as composer requirement but i have some troubles doing just so.

The path pimcore declares in the startup.php does not respect symlinked installations, so the constants.php MUST exist directly in the pimcore folder. It should be in the document root though.

I managed my setup for now by copying the index.php in the document root and placing the following lines on top:

``` php
if (!defined("PIMCORE_DOCUMENT_ROOT")) {
    define("PIMCORE_DOCUMENT_ROOT", __DIR__);
}

include_once("../vendor/pimcore/pimcore/pimcore/config/startup.php");
```

That - of course - will eventually break the updating process.

Also the scripts-section in pimcore/composer.json will not be used when installed as plugin, i dont know exactly what those are doing but it does seem my installation will be facing some problems there.
## What i want to achieve:

I want to have a project with pimcore as composer module and a public-folder as my vhost root, so the folder structure may be:

```
vendor
--|--pimcore/pimcore
--|--|--index.php
public
--|--index.php -> {composerroot}/pimcore/pimcore/index.php
--|--assets
composer.json
```

That way i could keep all my private stuff outside the public folder of the webserver

For that purpose a package to run

```
composer create-project pimcore/distribution
```

that holds the skeleton would be nice. But first the bootstrap would have to be adjusted.

**Comment by MajPay** [comment]
There is a better temporary workaround than copying index.php and console.php

If you create the index.php like this (within "public"):

```php
<?php

if (!defined("PIMCORE_DOCUMENT_ROOT")) {
    define("PIMCORE_DOCUMENT_ROOT", __DIR__);
}

include_once("../vendor/pimcore/pimcore/index.php");
```

It may be more robust

the console.php would look like (in project-root folder):
```php
#!/usr/bin/env php
<?php

ob_start();

if (!defined("PIMCORE_DOCUMENT_ROOT")) {
    define("PIMCORE_DOCUMENT_ROOT", __DIR__ . '/public');
}

include_once("vendor/pimcore/pimcore/pimcore/cli/console.php");
```

If you additionally create a link from public/vendor to ../vendor pimcore thinks all is good.

But it is kind of a dirty solution

**Comment by brusch** [comment]
New architecture in v5.
