### ISSUE TITLE
Documentation Update needed: I cannot follow the tutorial of getting started

### ISSUE THREAD

**Issue by 0mars** [pimcore/pimcore#7812]
![Screenshot 2020-12-27 at 07 27 47](https://user-images.githubusercontent.com/1150811/103165209-0c220000-4815-11eb-9c66-cd2af6cc7a19.png)
It looks like the documentation is out of date:

here in the instructions:
https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/Create_a_First_Project.html

> Go to the edit page of the class product
    Click right on Base and select Add Layout Component -> Panel - This is the main panel/container for the following product attributes
    To add attributes:
        Click right on Panel, then Add data component -> Text -> Input, then change the name of the input component to sku (in the edit panel on the right side)
        Just the same way you add the new data field for name
        Now we're going to add a WYSIWYG attribute for the description. Again, click right, select Add data component -> Text -> WYSIWYG. We name it description.
        The last attribute is for the picture. We can use on of the specialized image components in Other -> Image. Name the attribute picture.
If everything goes well, the new class looks like in the picture:

The layout doesn't look like the picture, and there is no 'Base'! :(

**Comment by carow-mwx** [comment]
It's all still there. Instead of "Base", right click on "General setting" and follow along. There you can add a Layout Component and all the other elements.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
