### ISSUE TITLE
Block element data doesn't get loaded when in objectbrick and lazy loading is on.

### ISSUE THREAD

**Issue by AlexanderWeckmer** [pimcore/pimcore#7818]
Tested with latest version of pimcore/demo -> Version: v6.8.6

![2020-12-28 17_51_57-demopimcore __ Pimcore](https://user-images.githubusercontent.com/20427487/103230806-9e6df500-4936-11eb-85e0-b560b2c1214c.png)

Steps to reproduce
-> Create block element within objectbrick and switch on lazy loading. Create a object which includes the objectbrick, add an item to the block element. -> Reload 

Expected behavior
-> Item of the block element would appear with a small delay
![2020-12-28 17_53_39-demopimcore __ Pimcore](https://user-images.githubusercontent.com/20427487/103231020-150af280-4937-11eb-8076-a44a762488ed.png)
(Screenshot was taken with lazy loding switched off!)

Actual behavior
-> Block element never shows it elements
![2020-12-28 17_53_04-demopimcore __ Pimcore](https://user-images.githubusercontent.com/20427487/103231083-4257a080-4937-11eb-9121-c26941c0c71a.png)

**Comment by passioneight** [comment]
This is reproducible on demo (10.5.7). @AlexanderWeckmer were you able to fix this? If so, any chance you can share the fix?

Update: _without_ disabling lazy load.

**Comment by kingjia90** [comment]
Thank you for reporting

It would be potentially fixed by https://github.com/pimcore/pimcore/pull/17270, could you please help reviewing it?

**Comment by AlexanderWeckmer** [comment]
Sorry for being late.
I can confirm it resolves the issue. 
Thanks.
