### ISSUE TITLE
Non-Localised fields in Object brick do not work in Listing or get add in Grid View

### ISSUE THREAD

**Issue by Dinesh2703** [pimcore/pimcore#7819]
Steps to reproduce - 
1. Create some localized and non-localized fields in an Object brick
2. Create a class and use above brick created in step-1
3. Create a folder and inside it create an item of type class created in step-2
4. Add localized fields in grid view.
5. Click on the folder you will see localized fields in grid.
5. Add non-localized fields in grid view. and again click on the folder to see non-localized fields in grid view. It will show error message - 
"Call to a member function supportsInheritance() on null".

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
