### ISSUE TITLE
Bug: Export custom reports doesn't work

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#782]
On the online demo website:
- create a custom reports from SQL adapter: "SELECT * FROM objects" (reports as list)
- save it

Trying to display the report send a fatal error:

Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /home/pimcore_demo/www/pimcore/modules/reports/controllers/CustomReportController.php:254 Stack trace: #0 /home/pimcore_demo/www/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Reports_CustomReportController->downloadCsvAction() #1 /home/pimcore_demo/www/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('downloadCsvActi...') #2 /home/pimcore_demo/www/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #3 /home/pimcore_demo/www/pimcore/lib/Pimcore.php(257): Zend_Controller_Front->dispatch() #4 /home/pimcore_demo/www/index.php(18): Pimcore::run() #5 {main} thrown in /home/pimcore_demo/www/pimcore/modules/reports/controllers/CustomReportController.php on line 254

Thanks.

**Comment by mrudnicki** [comment]
Thank you, I've fixed it in b5f7213cd0fdc2b6addabba02d3ed4692fd8d051
