### ISSUE TITLE
Missing "forceResize" parameter for asset inline thumbnail

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#783]
"forceResize" parameter is missing for asset inline thumbnail generation from PHP code.

Here:
https://github.com/pimcore/pimcore/blob/master/pimcore/models/Asset/Image/Thumbnail/Processor.php#L28 : 

And here:
https://github.com/pimcore/pimcore/blob/master/pimcore/models/Asset/Image/Thumbnail/Processor.php#L29

It should be:
```
        "scaleByWidth" => ["width", "forceResize"],
        "scaleByHeight" => ["height", "forceResize"],
```

Thanks.

**Comment by brusch** [comment]
Makes currently absolutely no sense, since this parameter is currently only used internally and not used by the thumbnail configuration in the user interface. 

![image](https://cloud.githubusercontent.com/assets/142037/17519692/4af77b40-5e4d-11e6-8f62-a9887cdd2ef8.png)

**Comment by Yivan** [comment]
Yes it is not in the GUI (so could be added maybe ?), but the purpose was to be able to use it if extending/DI Asset model.

Here is a working case, where we had to change the core file as asked in this issue so we can use this option when extending image asset class (purpose was to create custom thumbnail parameters to force scale up, to cover the asking improvment https://github.com/pimcore/pimcore/issues/786):

[Image.zip](https://github.com/pimcore/pimcore/files/422706/Image.zip)

For me it doesn't make non sense as it could be used for some case, and it is just a slight modification on core files. I hope it make sense finaly ; )
Thanks.
