### ISSUE TITLE
Copy plain/word with CKEDITOR sometimes don't take style for word pasting

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#784]
There is a strange random bug on copining text on wysiwyg field (object).
Copying with the word test icon sometimes doesn't use style.
It is random (you need to try at last 10 times switching from copying using plain and word icons -> "Paste as plain text" and "Past from word").
At some times, using the copy word text, the style are not taken and it is printed on the wysiwyg as plain.

Here is a sample word text used for testing on demo online site, with the wysiwyg on news object:
[sample.docx](https://github.com/pimcore/pimcore/files/396853/sample.docx)

Here is a screenshot after coping using "Paste from Word" option:
![exemple](https://cloud.githubusercontent.com/assets/9025839/17326754/94544308-58b3-11e6-9b7d-35346a0fb4a2.png)

As I said it is random, but if you try 10 times switching "Paste as plain text" and "Past from word", at some times pasting from word would paste it as text without style, and it shouldn't (it shoud keep style).
Maybe it is a CKEditor problem, but maybe it is because of some Pimcore background work during pasting.
I trying to reproduce it here, and there is not this problem: http://ckeditor.com/demo
Maybe CKEditor should be updated on Pimcore ?

Thanks.

**Comment by brusch** [comment]
I used Chrome and repeated it at least 15 times (at our demo using the text field in a blog article object), but didn't see any problems :( 
We'll upgrade CKEditor as soon as they have finished 4.6 anyway, maybe this fixes what you have experienced.

**Comment by Yivan** [comment]
Thanks for testing it.
I think it is environment/CKEditor version problem yes (mine environment was Windows 8.1). If i remember well i checked Firefox and Chrome, same problem.

Sure, i will retest as soon ckeditor is updated in Pimcore (as it works on the official ckeditor demo, i think the problem would be corrected with this new version on Pimcore).

**Comment by brusch** [comment]
We've recently upgraded to the latest version of CKEditor (4.5.1), can you please try it again on demo.pimcore.org? 

Thanks!

**Comment by Yivan** [comment]
Brusch, i confirm it work great now : )
You can close this issue,
Thanks.
