### ISSUE TITLE
Geopoint latitude/longitude constructor

### ISSUE THREAD

**Issue by KatrinAckermannEk** [pimcore/pimcore#7840]
# Improvement Request

Change the signature of Geopoint by flipping the arguments _longitude_ and _latitude_.

## Improvement description

A Geopoint or Geocode is commonly defined as a pair of value consisting of latitude and longitude.
The signature of the constructor in Pimcore defines the reverse order and expects the longitude at first.

As this is not intuitive, I suggest to change the order to adjust it to the common sense:

In pimcore/pimcore/models/DataObject/Data/Geopoint.php:
Is: 
`public function __construct($longitude = null, $latitude = null) {}`

Should: 
`public function __construct($latitude = null, $longitude = null) {}`

**Comment by NiklasBr** [comment]
Seems like a good idea: https://en.wikipedia.org/wiki/ISO_6709#Order,_sign,_and_units

**Comment by weisswurstkanone** [comment]
Hi @NiklasB, ,this definitely makes sense (!) but I don't see a migration scenario from a code perspective. I don't believe that existing code (e.g. import scripts) can be updated without effort and even the customers (and developers) will be aware that the signature changed. Scripts will still work but the data will be wrong. There will be no hard error ;-)

**Comment by Cruiser13** [comment]
We stumbled upon this quite a few times in the past. But you usually note it in development. I'd not change the behaviour as this would require a lot of code changes in customer projects and as weisswurstkanone said, this will throw no deprecation warnings or anything to let developers know about the change.

**Comment by NiklasBr** [comment]
It would be possible to solve by deprecating the `Geopoint` class, while introducing a new effectively identical class in 6.9.0 but with the correct order of the constructor arguments.

**Comment by brusch** [comment]
I'd prefer @NiklasBr  proposal.

**Comment by weisswurstkanone** [comment]
@NiklasBr do you have a meaningful name for the new class ?

**Comment by brusch** [comment]
What do you think about `GeoCoordinates` which is also used by schema.org

**Comment by NiklasBr** [comment]
Seems like a good choice, the only thing I don't like is that it feels odd with a pluralised classname when all others are singular such as as `RgbaColor`.

**Comment by KatrinAckermannEk** [comment]
What about `GeoPoint`, just as in the context of Pimcore's Targeting and Data Type?

**Comment by brusch** [comment]
Done by #8306
