### ISSUE TITLE
[CSV Import] Error if class contains a reverse relation field

### ISSUE THREAD

**Issue by MarcoGuiducci** [pimcore/pimcore#7854]
I'm trying to import a simple CSV with only full path and a textual field.
My class is composed of a text input and a Reverse-Many-to-Many Object Relation.

When I run the import, I got an error saying that the getter function for my reverse relation does not exist. That's correct because I see that also in the official demo those fields do not have any getter, But I can't understand why the import should fail.

I'm using Pimcore version 6.8.6.
In a different project, I have version 6.7.2 a similar configuration with reverse relations, but no errors.

This is my class configuration:
![Class Settings](https://user-images.githubusercontent.com/36894331/103673996-8291d100-4f7e-11eb-8d6e-85046ebcafd5.png)

### Expected behavior
Import should work correctly

### Actual behavior
This error is shown during import:
![Import Error](https://user-images.githubusercontent.com/36894331/103674178-be2c9b00-4f7e-11eb-8f09-a25acfb1c4a4.png)

**Comment by brusch** [comment]
Obsolete. Pimcore 6 Community Edition is EOL, CSV import was removed in Pimcore 10.
