### ISSUE TITLE
[Ecommerce] Last rule behaviour in combination with Min Cart Amount not working

### ISSUE THREAD

**Issue by IgorBenko** [pimcore/pimcore#7855]
# Bug Report

We are noticing an undesirable behaviour with pricing rules when using the "Last rule" option in Combination with a Min Cart Amount condition. We would like to understand if this is an accepted behaviour or a bug.

The problem in short is:
- when setting a Minimal Cart Amount condition the "Last rule" behaviour seems to be ignored and the pricing rules afterwards get applied
- without setting Minimal Cart Amount we see the expected behaviour

The following screenshots were done with a current Pimcore Demo.

### Expected behavior
When setting a Minimal Cart Amount condition in combination with the `Last rule` behaviour the pricing rules afterwards should not get applied.

### Actual behavior
When setting a Minimal Cart Amount condition in combination with the `Last rule` behaviour the pricing rules afterwards DO get applied. The "Last rule" behaviour is not working and the chain is not broken.

#### Test pricing rule chain
<img width="344" alt="Bildschirmfoto_von_Google_Chrome_(06-01-21_01-16-16)" src="https://user-images.githubusercontent.com/10233647/103715960-32d4f900-4fc2-11eb-97ae-973c0f4bdde5.png">
Both rules with voucher have behaviour set to `Last rule` and have a cart discount as Action.

`my-product-discount` only reduces the price of the product in cart and should not take any action when any of the other two rules are valid.

#### Pricing rule with vouchers with no min cart amount set

- Behaviour: Last rule
- Active: checked
- Actions:
    - Cart discount: 50%
- Voucher token to activate: `voucher-a`
<img width="763" alt="Screenshot_2021-01-06_at_01 35 092x" src="https://user-images.githubusercontent.com/10233647/103716032-57c96c00-4fc2-11eb-8d4a-84054056a3d8.png">

#### Pricing rule with vouchers with min cart amount set

- Behaviour: Last rule
- Active: checked
- Cart amount: 10000
- Actions:
    - Cart discount: 30%
- Voucher token to activate: `voucher-b`

<img width="781" alt="Screenshot_2021-01-06_at_01 16 552x" src="https://user-images.githubusercontent.com/10233647/103716079-76c7fe00-4fc2-11eb-9a22-bffe8ef7c135.png">

#### Just 5 products added
No pricing rules are active or applied.
<img width="1123" alt="Screenshot_2021-01-05_at_23 59 442x" src="https://user-images.githubusercontent.com/10233647/103716139-8e06eb80-4fc2-11eb-939b-b6ea31f6a744.png">

#### With product discount
Only product discount rule active: `my-product-discount`
<img width="1126" alt="Screenshot_2021-01-06_at_00 07 132x" src="https://user-images.githubusercontent.com/10233647/103716181-ac6ce700-4fc2-11eb-908d-e4b57694ac99.png">

#### With Voucher, without min cart amount and with `Last rule` checkbox checked
The `my-product-discount-rule` is not applied anymore and the voucher-without-min-cart-amount rule takes action. 
<img width="1123" alt="Screenshot_2021-01-06_at_01 46 332x" src="https://user-images.githubusercontent.com/10233647/103716213-c8708880-4fc2-11eb-8708-68ffdbd90c80.png">

#### With Voucher, with Min cart amount and with `Last rule` checkbox checked
`my-product-discount` still takes action although the "Last rule" behaviour is chosen in the voucher-with-min-cart-amount pricing rule. 
![Screenshot_2021-01-06_at_01 48 112x](https://user-images.githubusercontent.com/10233647/103716273-e76f1a80-4fc2-11eb-8b21-e49930cea9fb.png)

Please let me know if you need any additional information!

**Comment by fashxp** [comment]
I would say this is a bug.

**Comment by IgorBenko** [comment]
Hi Christian @fashxp ,
are there any plans to fix this bug? This is quite critical for one of or key clients, so a fix would be highly appreciated.

Thanks in advance for your reply!

**Comment by fashxp** [comment]
sure it needs to be fixed. since we are quite busy with Pimcore X there was not time yet though. 
PRs are welcome ;-)

**Comment by dvesh3** [comment]
Fixed by #8330
