### ISSUE TITLE
Image Thumbnails: possibility to force resize for any resizing transformation

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#786]
Actually using Pimcore native thumbnail processor frame and contain doesn't have parameter like "forceResize" (or "doNotScaleUp"), same but inverted logic), like cover.
See: https://github.com/pimcore/pimcore/blob/master/pimcore/models/Asset/Image/Thumbnail/Processor.php#L31

So if original image is smaller, final image is not of the exepected size. I think it is a wanted behaviour (so image is not pixelated), but in many case we need to enforce the size, to be sure the output thumbnail is exactly the size expected (so it won't break some templating for instance).
As improvement, like cover, frame and contain could have an option to force resize. this option could be set in the Pimcore GUI thumbnail processor, and in online PHP call of thumbnail method by parameters.

Best regards.

**Comment by brusch** [comment]
What is the actual use-case for scaling up the image?

**Comment by brusch** [comment]
See also: https://github.com/pimcore/pimcore/issues/783

**Comment by brusch** [comment]
Would also affect: scaleByWidth/Height and any other resizing transformation.

**Comment by Yivan** [comment]
Thanks for your answer.

scaleByWidth/Height already have their force parameters in the core code, just missing the possibility to configure it during inline thumbnail generation (https://github.com/pimcore/pimcore/issues/783).

The actual case where we needed it for instance is, whatever the image size uploaded in pimcore backend, the output image should be of the given width/height (so scaled up if to small). So the output of the thumbnail generator give us an image of **always the same width/height**. Actually this is not possible as the thumbnail generator do not scale up if to small (for non vector graphics).
We managed to get the same effect by extending image asset (see the zip file i just added here https://github.com/pimcore/pimcore/issues/783#issuecomment-240417283), so this improvment could be managed by custom code (but is need https://github.com/pimcore/pimcore/issues/783 to be integrate to core code because it relay on scaleByWidth/Height).

And for homogeneity, why it has been added an option to force scale up on "Contain" but not on Frame or Cover ? I think really such possibility to force scaleup would be a great addition for some user case. For people wanting consistent width/height in output thumbnail generated.

**Comment by Yivan** [comment]
For reference in https://github.com/pimcore/pimcore/pull/824 I asked if i could submit a more global pull request for this feature ?

Purpose of this pull request will be:
- I will try to implement for cover and frame the "doNotScaleUp" parameter
- I will add to the GUI (Image thumbnail in the backend): the checkbox "Do not scale up" for cover and frame, and the checkbox "Force resize" to scaleByWidth and scaleByHeight.

Is it ok like this ?

Side question:
- Actually we have two logic implemented: forceResize and doNotScaleUp, maybe we can make it more homogenous: i was thinking about renaming the parameter "doNotScaleUp" for cover as "forceResize" (and so reverse the logic... but will break backward compatibility), so we could maybe have only one way logic (all parameters will be called forceResize, and in GUI "Force resize". Or maybe you prefer use the "doNotScaleUp" instead ?
One way or another way it will break backward fonctionality, so i think it is preferable to leave it as this ?

**Comment by brusch** [comment]
Yep, is ok - looking forward to your PR. 
Regarding the consistent naming: yes, that would be also very appreciated.

**Comment by Yivan** [comment]
@brusch I think this one can be closed! Thanks.
