### ISSUE TITLE
Improvement: link custom reports to new newsletters

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#788]
I just tried the new newsletter document type. This is a nice addition. But actually, setting the receiver using Pimcore datas is tiedous or could be improved. As it is we can:
- use custom reports to export CSV, and open it and after cut/paste using the CSV List
- use Default object list (end-user/marketing administrator will be lost here with SQL request ; ) )

Maybe, having an adapter using custom reports could make end user management more friendly and global (could use any object and not those with only CRM email field).
For instance it could be:
- the user choose a custom reports and a column of this report as email address (could be improved: he could chose "name column", etc... and those used for placeholder/condition already prepared on the newsletter => customized newsletter). It could be a good base and so there is no more the export CSV/copy/paste procedure to do manually. It could be even improved by using extjs list (grid) to filter the receivers directly from the list grid (like we can do when viewing a custom reports).
It will make a powerfull receivers assignement, and those using the fluid extjs GUI.

I think there is something powerfull to take advantage of having datas on Pimcore and the possibility to use them to drive newsletter receveirs list and newsletter content customisation on those datas (field values, personnas, etc.). Atually most of the time we use Mailchimp by sending data via API from Pimcore to Mailchimp. But in fine graining mailling campaign, it would be so great to be able to use directly Pimcore datas to send newsletter directly from Pimcore (for instance customer who has buy some category of product, etc...).
Creating a "Custom reports adapter" and having at least just two field: "custom report name" and "email colum name" could greatly improve this. Later it could be improved (filtering, placeholder issued from the list that can be reinjected in the newsletter in wysiwyg mode...).

Best regards.

**Comment by fashxp** [comment]
actually this is a good idea. we would be very happy to see an pull-request for this one ;-) 

see also the Extending 'Address Source Adapters' section at https://www.pimcore.org/wiki/pages/viewpage.action?pageId=23101460

**Comment by Yivan** [comment]
Hello fashxp, I just made the pull request here https://github.com/pimcore/pimcore/pull/851
I hope it will be merged with the core!
Thanks.

**Comment by mrudnicki** [comment]
https://github.com/pimcore/pimcore/pull/851
