### ISSUE TITLE
Override class not working

### ISSUE THREAD

**Issue by do-web** [pimcore/pimcore#7906]
If i try this

pimcore:
    models:
        class_overrides:
            Pimcore\Model\DataObject\Data\Link: UiBundle\Model\DataObject\Data\Link

this is not working.

**Comment by brusch** [comment]
Please see the docs ... https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Overriding_Models.html#page_Overriding-Models-Entities-in-Pimcore

> Currently this works for all implementations of the following classes (but not for these classes directly) ...

... see the list of supported classes.

**Comment by do-web** [comment]
Ok is there another way how  i can override these?
