### ISSUE TITLE
[feature] Auto-generate "adder" for manyToMany or other relations

### ISSUE THREAD

**Issue by FredoVelcro** [pimcore/pimcore#7907]
Would be great to generate / add "adder/remover" to DataObject classes that contain a Many2Many relation (or collection) to avoid this :
```php
$newSku = new Sku();
$skus = $product->getSkus();
$skus[] = $newSku;
$product->setSkus($skus)->save();
```
better / simplier : 
```php
$product->addSkus($sku)->save();
$product->removeSkus($sku)->save();
```

Best regards

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
