### ISSUE TITLE
Tag create strips characters from name

### ISSUE THREAD

**Issue by manea-eugen** [pimcore/pimcore#791]
There seems to be an inconsistency between creating and renaming a tag
The name gets trimmed on create but on rename everything is ok 
_I am in build 3915_  
![screen shot 2016-08-05 at 15 27 08](https://cloud.githubusercontent.com/assets/8200242/17438106/7f9512ba-5b21-11e6-9352-8ed6c4e838dc.png)
![screen shot 2016-08-05 at 15 27 15](https://cloud.githubusercontent.com/assets/8200242/17438112/8408dc3c-5b21-11e6-9415-02cdb144534a.png)
![screen shot 2016-08-05 at 15 27 37](https://cloud.githubusercontent.com/assets/8200242/17438126/88f077aa-5b21-11e6-8c7c-3e4b693d6b4d.png)
![screen shot 2016-08-05 at 15 30 31](https://cloud.githubusercontent.com/assets/8200242/17438134/9652fca6-5b21-11e6-8bff-66b842bfa973.png)

**Comment by mrudnicki** [comment]
Thank you @manea-eugen 
Yes, it looks like the filter doesn't work with edit action. I will look into it.

**Comment by bury30** [comment]
why does the tags have to have a limit of 20 characters ?

**Comment by mrudnicki** [comment]
At the moment, I added the reload after renaming tags (the same like in addAction). 
As @bury30 mentioned. There is the limit for 20 characters in the database. I don't think that more characters would be necessary for tags feature, but I will discuss internally what is the reason of that limit.

**Comment by Sunohara666** [comment]
I need tags to be more than 20 characters for the project i am currently working on. How can i achieve this?
