### ISSUE TITLE
Google Analytics integration does not work for multi sites

### ISSUE THREAD

**Issue by sattes-faction** [pimcore/pimcore#794]
When I enter a Track-ID for a subsite it's not present in the html code - it only works with a Track-ID in the Main Site:

![image](https://cloud.githubusercontent.com/assets/1065116/17512164/d64a4a8c-5e26-11e6-870e-7f808c33982b.png)

I'm not sure, but I think the problem might be in `\Pimcore\Google\Analytics::getCode` where it tries to load the code with `$config = self::getSiteConfig();`, which seems to only load the main site configuration, because the methods parameter defaults to `null`.

**Comment by brusch** [comment]
Just tested it using the latest build and works as expected. 
Please keep in mind that this works only if you are accessing the site using the configured domain (not when using the main-domain).

**Comment by sattes-faction** [comment]
Ok, that might be an issue with our setup here (we internally redirect a domain to the pimcore system to a specific sub-site). Thanks nevertheless for checking.
