### ISSUE TITLE
Admin area: nested areablocks open wrong edit.php windows

### ISSUE THREAD

**Issue by sattes-faction** [pimcore/pimcore#795]
I have a nested areablock setup (two columns where each column is an areablock):

![image](https://cloud.githubusercontent.com/assets/1065116/17517752/1a8baed4-5e45-11e6-971e-18a768a1b3f5.png)

 So far it works fine.

However, there is one problem, if both the two-column-area and the areas within have an edit.php. The problem is as follows:

I click on the edit button for the two-column-area (the first one on the top right of the first screenshot), but I get the contents of the second edit.php within this areablock (the one that's behind the second edit-button in the left column).

I narrowed the bug down to the javascript function `editModeOpen` in the `areablock.js` file. The function loads the first element with the class `.pimcore_area_mode` which holds the edit.php content. But it returns the wrong one, it's always the last one.

Here's a screenshot for clarification:

![image](https://cloud.githubusercontent.com/assets/1065116/17517618/70c2d300-5e44-11e6-8ffd-8d003d74d3f9.png)

But when looking for `.pimcore_area_editmode` manually you can see there are two of them where the last one is the right one:

![image](https://cloud.githubusercontent.com/assets/1065116/17517681/ba130caa-5e44-11e6-8b25-e4e5f67b7141.png)

So, to solve it I guess it's best to use the correct area-name selector instead like e.g. `.pimcore_area_editmode_contentLeftlandingPageContentUE1`.

Maybe like this?

`var content = Ext.get(element).down('.pimcore_area_editmode_' + element.parentElement.getAttribute('name'));`

**Comment by brusch** [comment]
I'm not really able to reproduce this, can you give me some example code? 
Thanks!

**Comment by brusch** [comment]
@sattes-faction Anyway, ... 0b5ae731836f15da9fbd7fc8fae72a4024f6925f should fix it :) 
Feedback is always appreciated.

**Comment by sattes-faction** [comment]
Sorry for the late replay, I was on vacation. Works perfectly now in 4.3.0. :-) thanks!
