### ISSUE TITLE
CSV Export: Anygetter not exporting all records for Many-to-Many object relation

### ISSUE THREAD

**Issue by pradeep-pimcore** [pimcore/pimcore#7958]
# Bug Report

On demo.pimcore.fun, tried exporting all category names for a product.

### Expected behavior
Pimcore should export correct data as shown in grid

### Actual behavior
Pimcore does not export the names of multiple categories with product export.

### Steps to reproduce
ON demo.pimcore.fun

1. Open 'Grid Options' on 'cars' folder in dataobjects.
2. Configure the 'Anygetter' as shown in screenshot.
3. Drop 'category' field in the 'Anygetter'
4. Click 'Apply'
5. Observe that data shown in grid is fine.
6. Now click 'CSV Export' to export the data.
7. Observe the 'AnyGetter' data, **it fetches only single category's name**.

![pimcore_issue_anygetter_config](https://user-images.githubusercontent.com/58973662/105281471-442d2080-5bd2-11eb-8522-0095bcf63217.png)

![pimcore_issue_csv_export](https://user-images.githubusercontent.com/58973662/105281599-86eef880-5bd2-11eb-9002-15e9260d2b98.png)

**Comment by weisswurstkanone** [comment]
Unable to reproduce on demo.pimcore.fun. For me it looks like in the screenshot

![image](https://user-images.githubusercontent.com/6142086/105326728-5ad17880-5bce-11eb-87f4-b3231a5c5dd4.png)

**Comment by weisswurstkanone** [comment]
@pradeep-pimcore ping 🏓

**Comment by pradeep-pimcore** [comment]
Sorry for delay @weisswurstkanone .
This was an issue with my CSV reader. I tried again with a different reader and it worked fine.
Thank you.
