### ISSUE TITLE
liveupdate.pimcore.org/update-check returns "aus" in some cases and results in console error due to invalid JSON string

### ISSUE THREAD

**Issue by tomhatzer** [pimcore/pimcore#7960]
# Bug Report

The call home functionality of the live update checker results in an error in some cases ( https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Resources/public/js/pimcore/startup.js#L465 )

```
Uncaught Error: You're trying to decode an invalid JSON String: aus
```

### Expected behavior
Return a valid json object.

### Actual behavior
Returns the string `aus` and results in a console error.

### Steps to reproduce
Execute the following curl command to emulate behaviour: `curl -X POST -d'id=d3d4f7f5d3136f0b682c8f466df6ae0c69515915&revision=d66a9628f92d75ecb75d5ade8a50283da70a0070&version=v6.8.7&debug=false&devmode=false&environment=prod&language=en&main_domain=&domains=&timezone=Europe/Berlin&websiteLanguages=en,de' https://liveupdate.pimcore.org/update-check`

**Comment by brusch** [comment]
Done, thanks!
