### ISSUE TITLE
Assets - show in tree not working with pagination

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#797]
Show in tree gives the following error when there are enough assets for paging. Reproducible on the latest demo.

> Error
> Sorry, this is not possible in elements which are paged, try to restructure your data to avoid pages in the tree

Since this works for objects for quite some time, i think this should work for assets to.

A quick fix: in treenodelocator.js line 112 
change 
`fullPath = element.path + element.filename;`
to
`fullPath = element.fullpath;`

however i didnt check if this has any side effects - it also seems to me that a lot of code arround this line is unnecessary

**Comment by weisswurstkanone** [comment]
thx. fixed in build 3929

**Comment by betterapp** [comment]
In Pimcore 11 the issue exist still for assets.
For objects it is working fine.


We have many assets in folder and we have 10 pages there.
We go to 5th page and open one image.
Then we collapse the tree.
When we clik on "Show in tree" button for this image Pimcore display 1st page of the folder
not 5th.
