### ISSUE TITLE
Fieldcollection with Localized Fields deletes and overwrites content after unpublished save

### ISSUE THREAD

**Issue by foxgreek** [pimcore/pimcore#7974]
# Bug Report

### Expected behavior
The Fieldcollections with Localized Fields should keep the data at the right positions after saving. 

### Actual behavior
1. After adding new FC and saving without any changes, adding afterwards data and hit save again, data of next element is missing.
2. Another Bug appears, when you add a new FC above the current elements, add Data and hit save multiple times afterwards, contents of data of elements below get overwritten.

### Steps to reproduce
Add following Test FC and Class to demo:
[TEST_FC_BUG.zip](https://github.com/pimcore/pimcore/files/5856519/TEST_FC_BUG.zip)

First behavior:
1. Create Object from Class Test
2. Add 1 FC element "test", add data and hit save + reload object
![image](https://user-images.githubusercontent.com/40141606/105506478-63a77480-5cca-11eb-815d-ad7b0a8cb2a8.png)

3. Add another FC element before and hit save without reload
![image](https://user-images.githubusercontent.com/40141606/105506549-7a4dcb80-5cca-11eb-8e47-55d31b8fe4d5.png)

4. Add data to the new FC element and hit save
![image](https://user-images.githubusercontent.com/40141606/105506625-89cd1480-5cca-11eb-9404-b20c0b4f1877.png)

5. reload and data from first element should be missing
![image](https://user-images.githubusercontent.com/40141606/105506671-9487a980-5cca-11eb-918a-651296cdd0b5.png)

Second behavior::
1. Create Object from Class Test
2. Add 3 FC element "test" add unique data to the elements and hit save + reload
![image](https://user-images.githubusercontent.com/40141606/105506854-cac52900-5cca-11eb-9147-b443cd02678c.png)

3. add new field before the other 3 elements, add data and save multiple times 
![image](https://user-images.githubusercontent.com/40141606/105506905-dd3f6280-5cca-11eb-9e2e-e7775bd4969c.png)

4. Fields below last element should have same content as previous
![image](https://user-images.githubusercontent.com/40141606/105506989-f47e5000-5cca-11eb-9a60-5ad7a7289071.png)

**Comment by dev-flti** [comment]
Exactly this bug also occurs in our systems! 
-> Saving FieldCollections leads to overriding the fields below!

**Comment by foxgreek** [comment]
@brusch any ideas? Our customer can't save/generate new Content

**Comment by brusch** [comment]
@foxgreek no, I'm sorry - haven't got the time yet.
