### ISSUE TITLE
Class definition: renaming a property should keep the data

### ISSUE THREAD

**Issue by axel-tietje** [pimcore/pimcore#798]
### Expected behavior 

A classes property has a new name after changing the name in the Pimcore GUI: Settings > Object > Classes. Data stays intact.

### Actual behavior  

Data is lost.
  
### Steps to reproduce  

* Login to demo.pimcore.org
* Navigate to Settings > Object > Classes
* Edit class "news"
* Change property name title to somethingElse
* Save changes
* Navigate to Objects, open folder "Home/news"
* Change column config to show renamed title column, or open a news object
* Field "Title" is empty, but shouldn't.

**Comment by brusch** [comment]
This is actually no bug, this feature is simply not implemented yet :) 
The requested renaming functionality sounds easier to implement that it actually is, because it depends on the data type of the field and needs to be addressed by every data type. 

So currently this feature is not on our roadmap at all.

**Comment by brusch** [comment]
Implementation currently unrealistic -> closed. 
@axel-tietje thank you anyway :)

**Comment by elburro1887** [comment]
This has also bitten me a couple of times already.

I understand that you might not want to implement this feature, but what if pimcore could at least show a warning, upon saving for example? Something like "Are you sure you want to save? FieldXXX might lose data!" And then the user could also roll back the changes?

**Comment by bcastagna** [comment]
Just lost 10.000 lines in db because of just renaming the class -_-

**Comment by bigiagipa** [comment]
I was thinking to use the migration. But changing the field will update the class definition file, and will be detected as git change.
This will be very important for project development.
