### ISSUE TITLE
Resend E-Mail

### ISSUE THREAD

**Issue by ckogler-elements** [pimcore/pimcore#7986]
The resend e-mail functionality doesn't work when an E-Mail was sent with an empty name.

`
$toMail = 'test@test.com';
$toName = "";
$mail->addTo($toMail, $toName);`

The "to" E-Mail adress in the email_log table is then logged as "example.asdf@demain.com ()" and this format ist not recognized.

It occures in an old Pimore 6 versions so i don't know if this happens also in Pimcore X.

**Comment by dvesh3** [comment]
already fixed by https://github.com/pimcore/pimcore/pull/7492

**Comment by NiklasBr** [comment]
@dvesh3 I suspect my fix in #7492 could be incomplete and only works for new log entries, it may be the case that existing log entries still with stored data like `example.asdf@demain.com ()` could fail. @ckogler-elements maybe you can update to 6.8.5 and test?

**Comment by brusch** [comment]
Fixed by #8001
