### ISSUE TITLE
Add console task to reindex assets

### ISSUE THREAD

**Issue by MajPay** [pimcore/pimcore#799]
# Feature: Add console task to reindex assets

First of all: If there IS a way to achieve what i am looking for - sorry, i did not find any.

To keep it short and simple:
There should be a task that you can run (eg: console.php index-assets) to reindex the assets within your assets folder. When we migrate a website to pimcore we want to migrate all user-assets as well, but copying them to website/var/assets wont do it, because the files are not indexed in pimcores abstraction.

A task, that walks through the directory structure and adds all new files _not uploaded via the backend_ would do the job.

**Comment by axel-tietje** [comment]
Hi, AFAIK there's no way to do that. I've written an import function to do exactly that. PN me in case you're interested.

**Comment by brusch** [comment]
You can use the server import functionality in pimcore: 

![image](https://cloud.githubusercontent.com/assets/142037/17558973/ba9d2f06-5f1c-11e6-9104-2a40988a9b76.png)

**Comment by wschopohl** [comment]
This feature seems to be gone now. Is there any other way to achieve this?
