### ISSUE TITLE
[Ecommerce] Index Field Combobox icon not displayed

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#7993]
![image](https://user-images.githubusercontent.com/6142086/105852858-4550ba00-5fe5-11eb-81f4-69bf848aefb1.png)

**Comment by weisswurstkanone** [comment]
also on demo.pimcore.fun

![image](https://user-images.githubusercontent.com/6142086/105853945-8ac1b700-5fe6-11eb-85b3-b02bb68624da.png)

**Comment by dvesh3** [comment]
Fixes by #7993
