### ISSUE TITLE
Secure Cookie breaks Pimcore CSRF Listener

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#8006]
Setting this:

```
framework:
    session:
        cookie_secure: true
```

makes login impossible, since Pimcore complains about CSRF and "do not do evil things with Pimcore".

**Comment by dvesh3** [comment]
@dpfaffenbauer you mean: it is broken on secure connections(https)? coz if `cookie_secure: true` then cookies should only be sent over secure connections.

**Comment by dpfaffenbauer** [comment]
well, just tried it and pimcore didn't let me login anymore....

**Comment by dvesh3** [comment]
ok. thanks for confirming! 👍

**Comment by dvesh3** [comment]
@dpfaffenbauer Sorry, it works for me on secure connection with `cookie_secure: true`.

**Comment by brusch** [comment]
Same here, works as expected - doesn't seem to be a general issue.

**Comment by brusch** [comment]
![03-02-_2021_12-17-29](https://user-images.githubusercontent.com/142037/106739825-e52bca80-6619-11eb-9289-a33a96bd62be.gif)

**Comment by dpfaffenbauer** [comment]
yep, just deployed it at the customer installation and worked there as well.

**Comment by brusch** [comment]
Thanks for your feedback!

**Comment by dpfaffenbauer** [comment]
sorry for bothering you with this... it was quite odd for me seeing the CSRF Listener locally....
