### ISSUE TITLE
S3: Pimcore User Image breaks User Setting / User Login

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#8015]
Following Scenario:
 - S3 configured
 - User Image Directory on S3
 - User Uploads Image
 - Immediately breaks the Users Account
 - Can't login
 - Admin cannot change user
 - Admin cannot even remove the Image. You have to delete the image from S3 to make it work again

**Comment by brusch** [comment]
Fixed by #8022
