### ISSUE TITLE
Incorrect value in system settings prevents user from login

### ISSUE THREAD

**Issue by PlesnikJakub** [pimcore/pimcore#8016]
# Bug Report
Hi, 
I found a bug or definitely unexpected behavior in system settings. 

When an admin user sets an invalid URL string into the **login_screen_custom_image** field in **system settings**. after logout, another login to administration is unsuccessful and ends with an error. The error prevents users from login.

```
"code":400,
"message":"Detected CSRF Attack! Do not do evil things with pimcore ... ;-)"
```

This problem is hard to debug because, after this small issue, you are no longer able to log into the application.

### Expected behavior
* I would expect that field would be validated.
* Such issues should not prevent users from login.

### Actual behavior
It prevents users from logging in and fixing system settings.

### Steps to reproduce
* Update system settings > login screen custom URL with value that is not corect url. 
* eg.: "#FF0000asdasdasd" 
* save settings
* logout
* refresh browser
* try to login
* error is thrown

### Code example
```php
pimcore_admin:
    branding:
        color_login_screen: '#FF0000'
        color_admin_interface: ''
        login_screen_custom_image: '#FF0000asdasdasd'
        login_screen_invert_colors: false
```

**Comment by brusch** [comment]
Fixed by #8023
