### ISSUE TITLE
table 'documents' has the column named 'key' which is mysql reserved word, that causes mysql error code 1064 

### ISSUE THREAD

**Issue by guilanh** [pimcore/pimcore#802]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [ ] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [ ] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [ ] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [ ] There's no existing ticket for the same issue

### Code example 
```php
// your code
```

# Feature Request 
## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [ ] There is no existing issue regarding the same topic

**Comment by brusch** [comment]
If you are using this in your own queries, please quote the name of the column properly. If this produces some kind of error in the Pimcore core, please provide us more details. 

Thanks

**Comment by guilanh** [comment]
Hiya,

Thank you for your reply. Please see the screen print when I work on Mysql workbench

[cid:image001.png@01D1F476.BC847290]

Regards
Guikan Huang

**Comment by brusch** [comment]
The screenshot is unfortunately not visible. 
But anyway, reserved keywords need to be quoted in MySQL: http://dev.mysql.com/doc/refman/5.7/en/identifier-qualifiers.html

So this is definitely not a bug of Pimcore.

**Comment by guilanh** [comment]
Please find the attached document. Where id=4 return the row in which the key is ‘introduction’, but if you put key condition there, no matter in which way you put, the row was not returned.

Regards
Guilan Huang
