### ISSUE TITLE
"Column Configuration" in Object Folder can´t be stored and not working in 4.2.0

### ISSUE THREAD

**Issue by robert-weblizards** [pimcore/pimcore#803]
And users who stored their own Column Configuration can´t open object folders after an Update to 4.2.0.

**Comment by weisswurstkanone** [comment]
Regarding the 2nd point: Do you see any error in the response?

**Comment by weisswurstkanone** [comment]
Wait, are you aware that the config must be saved separately now? There is a new button on the very right. See screenshot.

**Comment by robert-weblizards** [comment]
Well - you are right. But the Problem is, if i have old configurations stored then the folder doesn´t open any longer.

So - where can I reset the "User -> Folder -> View Settings"

Thanks!

**Comment by weisswurstkanone** [comment]
Currently you can't. Would be useful to know the exact error. Does the folder not load at all, does it load but throw an error, do you see anything in the console?

**Comment by robert-weblizards** [comment]
I can´t open the Folder - here´s the error:
Error: You're trying to decode an invalid JSON String: <br /> <b>Fatal error</b>: Call to a member function getId() on array in <b>/html/pimcore/modules/admin/controllers/ObjectController.php</b> on line <b>652</b><br />

**Comment by robert-weblizards** [comment]
Maybe because Fieldcollections where stored in the Folder View?

**Comment by weisswurstkanone** [comment]
You are probably using the stable 4.2.0 (build 3900).
This issue should be fixed already, build 3902 (built a few hours later :-)) 

This is the relevant change:
https://github.com/pimcore/pimcore/commit/bb43943cb6983bafc0ce554ed240ddf6ccd8270d

**Comment by robert-weblizards** [comment]
Thanks ;-) i will try it and give feedback

**Comment by robert-weblizards** [comment]
Works fine - thanks very much

**Comment by weisswurstkanone** [comment]
then let's close it ;-)
