### ISSUE TITLE
Pimcore\Model\DataObject\Concrete::update when a ValidationException is re-thrown it does not have the subitems from the original exception

### ISSUE THREAD

**Issue by strentz** [pimcore/pimcore#8049]
# Bug Report

### Expected behavior
When a validation exception is thrown the exception should contain the sub items for each of the fields that cause the exception. (For example mandatory fields set as empty)
### Actual behavior
When the exception happens the subitems from the validation exception are ignored.
### Steps to reproduce
For example the method Pimcore\Model\DataObject\ClassDefinition\Data\Localizedfields::checkValidity throws a ValidationException with the subitems for each field, when this exception is catch in Pimcore\Model\DataObject\Concrete::update, a new exception is created instead and ignoring the sub items from the original one.

**Comment by jdreesen** [comment]
I think this can be closed now.
