### ISSUE TITLE
"Default" language values in Classification Store parameters don't cascade to other languages on the grid (6.7.2)

### ISSUE THREAD

**Issue by AlekMosingiewicz** [pimcore/pimcore#8051]
# Bug Report

### Expected behavior

The values set for the "Default" language cascade into other languages (especially the one set as "default" in system settings) when displayed and filtered by on the grid.

### Actual behavior

The values set for the "Default" language are only visible on the grid when the "Default" language is set for the grid.

### Steps to reproduce

Create a classification store and set of parameters, then assign them to a few objects. Fill out the values of said parameters using the default language. Then navigate to the grid, navigate to the settings, choose the language set for the system as "default" (not the same as "Default" language) as the language for the grid and choose the classification store attributes that have been previously filled to appear on the grid. Their values won't appear, even if they should.

### Implications

The current implementation forces the user to explicitly fill out all the language versions for the classification store parameters if they are to appear on the grid. This is especially troublesome when exporting the data to CSV from the grid, as we already experienced.

**Comment by AlekMosingiewicz** [comment]
Is anyone willing to take this on?

**Comment by brusch** [comment]
@AlekMosingiewicz why not yourself? We're always thankful for any kind of contribution 😊

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
