### ISSUE TITLE
No Options in user dropdown in additional fields in workflow actional panel

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#8059]
Hi
I am tring to add users select box in workflow action panel as given in documentaion .
additionalFields:
-
name: workflowUser
title: Select User
setterFn: setWorkflowUser
fieldType: user

The select box is added to the action panel but the select box does not have any options.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
