### ISSUE TITLE
Doctrine QueryBuilder regression

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#8069]
Regression of #7817

When running the maintenance job `ecommerce_pending_orders` the following error is thrown: 

```
[app] Failed to execute job with ID ecommerce_pending_orders: Doctrine\DBAL\Exception\SyntaxErrorException {​​​​​​​


You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '~paymentinfo ON 1\n
AND `PaymentInfo~paymentinfo`.o_id = `object_EF_OSO`.o_id ...' at line 1
"""
```

It's probably related to how the joins are being build here: 
https://github.com/pimcore/pimcore/blob/d101e12b16c243ab062c79ed5541a6460a97e805/models/DataObject/Listing/Concrete/Dao.php#L220

**Comment by dvesh3** [comment]
Fixed by #8086
