### ISSUE TITLE
Video Editable - Thumbnail creation progress always stays 0%

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#807]
![image](https://cloud.githubusercontent.com/assets/7206334/17734351/ff3311b2-647b-11e6-8623-7fe28e2d6b87.png)

This is just visual ofc - when finished everything workes fine.

Seems to me that $progress is not defined in https://github.com/pimcore/pimcore/blob/master/pimcore/models/Document/Tag/Video.php#L724

Also: Shouldn't getVideoAsset https://github.com/pimcore/pimcore/blob/master/pimcore/models/Document/Tag/Video.php#L790 return `Asset\Video` instad of just `Asset`?

**Comment by brusch** [comment]
The actual percentage of the progress isn't supported anymore (removed by 08b3186ce8767bd172471b19ace0240cf6846f58 ).

So this was just forgot :) 
Thanks!
