### ISSUE TITLE
Parallelize SearchBackendReindexCommand

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#8077]
Currently for big Pimcore installations the SearchBackendReindexCommand is un-usable due to doctrine memory leak problems as all Pimcore elements are loaded within one command. I tried it for an installation with 1 million assets and 4 million data objects.

As improvement it should perfectically be possible to parallelize this command using the Webmozarts console parallelization trait.

**Comment by brusch** [comment]
Done by #10423
