### ISSUE TITLE
[Redirects] Redirect asset URLs

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#8081]
When there is a link to a Pimcore asset somewhere in the internet where I cannot change it but I want to rename / move the asset file, it would be nice if redirects would be working for assets. So that if the asset cannot be found at the requested location it gets checked if there is a redirect for this location.

**Comment by HaraldDe** [comment]
Has something changed here in the priorities? I have the same topic.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
