### ISSUE TITLE
[Bug] Can't change the position of references in a data object

### ISSUE THREAD

**Issue by fatihb91** [pimcore/pimcore#8084]
### Expected behaviour:
The order of references in a data object should be changed manually, using the up and down key.

### Actual behavior:
When you want to change the order of references in a data object, the error Uncaught RangeError appears. This error occurs on a Windows computer. However, it works on the MacOS operating system.

### Steps to reproduce 
1. Open: https://demo.pimcore.fun/admin/ (admin/demo):
2. Open the Events directory in the Data Objects section.
3. Open Custom Wheels Vienna
3. Open the Cars tab and click the up and down arrow to reproduce the failure

**Comment by dvesh3** [comment]
@fatihb91 sorry, it works on demo. (followed the steps mentioned)
