### ISSUE TITLE
ClassificationStore: Adding Groups to CollectionGroups doesn't add them to Objects already using the CollectionGroup

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#809]
Adding a new Group to a ClassificationStore's CollectionGroup doesn't add the new Group to all existing Objects. 

The main problem is, that the Object doesn't even know what CollectionGroups are assigned to it (doesn't it?). It only knows about Groups.

Is this a feature that is missing or is it missing in purpose?

**Comment by weisswurstkanone** [comment]
This is intentional. A collection is merely a mechanism to quickly add several groups in a single step.
Objects only know about groups and keys, not collections. Also note that you can add groups either directly or via the collections tab.
