### ISSUE TITLE
Thumbnail generation hook shows different behavior depending on what transformator was used

### ISSUE THREAD

**Issue by monaBinder** [pimcore/pimcore#810]
# Bug Report
I have a plugin rewriting the path of requested thumbnails by using the EventManager. Thumbnails show a different behavior depending on what transformator was used. So usually the event is fired before an thumbnail is created, but in case the ROTATE transformator was used, it is fired only after generation.
  
### Expected behavior 
Events are fired before the thumbnails are generated.
  
### Actual behavior  
Thumbnails using the rotate transformation are generated first before you can hook into the process

### Code example 
```php
\Pimcore::getEventManager()->attach([
            "frontend.path.asset.image.thumbnail",
            "frontend.path.asset.document.image-thumbnail",
            "frontend.path.asset.video.image-thumbnail",
            "frontend.path.asset.video.thumbnail",
        ], function ($event) {

            $thumb = $event->getTarget();
            .....

        });
```

**Comment by brusch** [comment]
Well, _frontend.path.asset.image.thumbnail_ isn't fired **before** the thumbnail is generated and that's also not the definition of this event. 

If the thumbnail was generated before the event is fired or not depends on the _deferred_ parameter: 
https://github.com/pimcore/pimcore/blob/b98bef1620ab930eccf1e5ee0fab18042b49ea11/pimcore/models/Asset/Image/Thumbnail.php#L100-L100
