### ISSUE TITLE
Delete Object in workflow transition not possible

### ISSUE THREAD

**Issue by damix1984** [pimcore/pimcore#8104]
### Expected behavior

workflow transition (config.yaml):

_new_to_old:
    from: new
    to: old_

Method added as **EventSubscriber** for "old" place **Enter** event.
In the method i have in some cases to delete the **Subject object** of the event and i expect that when i do `delete()` the object is deleted.

### Actual behavior

Actually when i call delete() method it deletes (the object is no more in the database) but after the end of the method the transition completes and the object is again at his place in the database.

### Steps to reproduce

- Create a DataObject
- Create a workflow with two places for the object and a transition between them
- Create an eventSubscriber for the enter event on the second place
- call $event->getSubject()->delete() in the method called by the subscriber

Is it correct?
Is there something i am missing if i want to **completely delete the object** when i do the transition (obviously only in some conditions, i wrote the simplest way to reproduce my problem)

**Comment by fashxp** [comment]
I think the only way in that case is also to completely stop the workflow transition... or add a marker and create a subscriber to post transition event where the actual deletion in done.
