### ISSUE TITLE
Buttons missing with long external URL name

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#8106]
When using a long name (we use the url as name in the external url field) the buttons are is missing.

Normal behaviour:

![image](https://user-images.githubusercontent.com/41229269/107147101-8aada980-694c-11eb-9abd-90b9f24f3c24.png)

With large URL:

![image](https://user-images.githubusercontent.com/41229269/107147132-add85900-694c-11eb-9342-eab765ac4fde.png)

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
