### ISSUE TITLE
Classification Store does not save Quantity Values

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#8110]
# Bug Report
In version: v6.8.7 quantity values in classification stores are lost.

Data before Save:
![image](https://user-images.githubusercontent.com/16687355/107194224-0ca2de80-69f0-11eb-8520-c0f2f00cca24.png)

Request data on save (the values are still there):
![image](https://user-images.githubusercontent.com/16687355/107194377-3f4cd700-69f0-11eb-8014-0e6f2cfb6a97.png)

Database Table (the values are missing):
![image](https://user-images.githubusercontent.com/16687355/107194276-204e4500-69f0-11eb-8f27-3e31b911422d.png)

After Reload (the values are missing):
![image](https://user-images.githubusercontent.com/16687355/107194499-686d6780-69f0-11eb-89de-39abb724706b.png)

---

Note: it is working on the demo (6.8.x-dev).

**Comment by dvesh3** [comment]
@andreas-gruenwald can you please try 6.8.8? thanks!

**Comment by weisswurstkanone** [comment]
see https://github.com/pimcore/pimcore/issues/8114
