### ISSUE TITLE
Wrong language used if key equals translation in shared translations

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#8117]
# Bug Report
### Expected behavior
If the translation key "Artikel suchen" has an english translation "search article" and german translation "Artikel suchen" it should read "Artikel suchen" on a german website.

### Actual behavior
It does show "search article" instead.

### Steps to reproduce
Setup a pimcore instance with languages german and english. Use english as fallback language for german.
Setup a website using the german language.
Use a translation key in twig like this:
```twig
{{ 'Artikel suchen'|trans }}
```
Fill in "search article" as english translation in the shared translations and "Artikel suchen" as german translation.

This issue has been discussed in #7184 before. Reproducable in Pimcore 6.8.8.

**Comment by brusch** [comment]
Please also add test-cases.

**Comment by brusch** [comment]
Resolved by #8189
