### ISSUE TITLE
[Pimcore X] Can't use Pimcore without redis

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#8119]
# Bug Report
If I want call Pimcore X after the installation I get following error:
`Cannot find the "redis" extension nor the "predis/predis" package: "redis://localhost".`

This came from the "pimcore.cache.adapter.redis_tag_aware" service which has a "cache.pool" tag.
The Symfony Profiler load this services.

**Comment by brusch** [comment]
Thanks for reporting!
