### ISSUE TITLE
Custom Reports - Extend export functionality

### ISSUE THREAD

**Issue by ctippler** [pimcore/pimcore#8127]
Currently the export feature for custom reports is very limited.
It would be great if we can define the line seperator, identifying marks... when the csv is exported - or in the settings of the report.

Maybe also supporting grid config Transformers, Operators.... would be nice.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
