### ISSUE TITLE
Error in localized GraphQL Query

### ISSUE THREAD

**Issue by Dinesh2703** [pimcore/pimcore#8128]
I am trying to get a particular localized field in another language. I have follwed PIMCore GrapQl query documentation for this as shown in below image.
![sampleQuery](https://user-images.githubusercontent.com/41935464/107482118-45d07f80-6ba5-11eb-9ce7-f4b413bca4c2.PNG)

My query is-
![localizedGraphQL](https://user-images.githubusercontent.com/41935464/107482162-4ec15100-6ba5-11eb-981c-58561fd6b853.PNG)

Its showing error - 
![error](https://user-images.githubusercontent.com/41935464/107482274-787a7800-6ba5-11eb-8d44-ff0d1e61df14.PNG)

Please Suggest the fix. My PIMCore version is v6.8.6

Thanks

**Comment by weisswurstkanone** [comment]
As the documentation indicates, language selection is only supported on request level, not on field level.
