### ISSUE TITLE
Login-Background: Custom Image not displaying anymore

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#8129]
# Bug Report
When defining a custom login background image path in the system settings, which isn't hosted on the same domain, the image isn't displayed anymore. [This commit](https://github.com/pimcore/pimcore/commit/417e3a42b6035371663d397ce29a63f4fdc63e7b) is causing this.

### Expected behavior
Before it was possible to host the background image on another host. This had the benefit, that you wouldn't need to always store the same images on all Pimcore instances.

### Actual behavior
Now the code checks if the image exists on the filesystem, which of course is `false` when the image lies on another system.

### Steps to reproduce

- Define an image of a different host in the system settings
- Logout
- Default Pimcore background images are display instead of your own custom image

**Comment by aarongerig** [comment]
Awesome, thank you @dvesh3 !

**Comment by brusch** [comment]
Fixed by #8129
