### ISSUE TITLE
Remove SQL_CALC_FOUND_ROWS to speed up query

### ISSUE THREAD

**Issue by xlttj** [pimcore/pimcore#814]
# Have a look a [this line of code in Pimcore\Model\Object\Listing\Concrete\Dao](https://github.com/pimcore/pimcore/blob/5036920fca970ab124914d55aed9180cf50541dd/pimcore/models/Object/Listing/Concrete/Dao.php#L63).

Would it be a good idea to remove the `SQL_CALC_FOUND_ROWS` part of the query, as it slows down the query essentially?

When I do `$list = new MyClass::getList(['limit' => 5]);`

this query will be created:

`SELECT SQL_CALC_FOUND_ROWS object_1.o_id as o_id, object_1.o_type FROM object_1 WHERE ((object_1.o_type IN ('object','folder')) AND object_1.o_published = 1) LIMIT 5`

This takes 450ms to run on my server (~50.000 rows), without `SQL_CALC_FOUND_ROWS` it takes 78ms, that's almost 6 times faster.

`SQL_CALC_FOUND_ROWS` is only used to calculate $totalCount, which could be calculated using an additional `SELECT COUNT(*) […]` query only on demand, since one doesn't always need the total number of rows.

**Comment by xlttj** [comment]
Thx!

**Comment by kanevbg** [comment]
Just to note I did not saw performance improvement implementing these two commits:
- https://github.com/pimcore/pimcore/commit/c2a5afa7abef0db802c7df2ea212577936fa37b5
- https://github.com/pimcore/pimcore/commit/a38554119245dbd49a1c8968b04c2689f78f2408
