### ISSUE TITLE
[Ecommerce][PricingRules] First condition is always ignored

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#8142]
steps to reproduce: 

use `FREE_SHIPPING` voucher in demo shop -> free shipping should only be applied to sports cars, but is now always applied 

![image](https://user-images.githubusercontent.com/8792145/107617965-137c5c00-6c51-11eb-8865-b872b0735c70.png)

![image](https://user-images.githubusercontent.com/8792145/107617994-1c6d2d80-6c51-11eb-9fec-cbd0bdcf194f.png)

regression of https://github.com/pimcore/pimcore/pull/7904

**Comment by brusch** [comment]
Fixed by #8148
