### ISSUE TITLE
Copy-pasting DataObjects with references

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#8147]
# Bug Report

### Expected behavior

When copying and pasting a Data Object which has references such as other Data Objects and assets they should also be referenced in the new copy.

### Actual behavior

Some references are lost.

### Steps to reproduce

1. Copy an object tree.
2. Paste using *Paste as a child (recursive)*
3. Paste again *Paste recursive, updating references*
3. Inspect both new trees, nether will have had all its references intact.

## Source object

![image](https://user-images.githubusercontent.com/279826/107626230-c488f380-6c5d-11eb-8b74-f44ca4989bf8.png)

## 1. *Paste as a child (recursive)*

![image](https://user-images.githubusercontent.com/279826/107626329-eda98400-6c5d-11eb-969f-f5d445a96e12.png)

## 2. *Paste recursive, updating references*

![image](https://user-images.githubusercontent.com/279826/107626386-fef29080-6c5d-11eb-8db8-a089bfcc748b.png)

**Comment by dvesh3** [comment]
@NiklasBr looking at your screenshots, it seems you are working with **Reverse ManyToMany Object** datatype which shows relations of the current object in remote objects. so when you copy data object, this new copied data object has no relation to remote objects so they are not displayed. what do you expect here?

**Comment by NiklasBr** [comment]
I (and my users) expect the references to be copied and pasted, *especially* on the "Paste recursive, updating references". It really makes no sense to none of us why any data at all should be removed when pasting, let alone something as onerous to restore as references.

**Comment by milesimarco** [comment]
Same problem here: the inclusion of reverse relations in the copy seems a legit and expected behaviour. Any updates about go/no-go decision?

**Comment by NiklasBr** [comment]
This is still relevant

**Comment by NiklasBr** [comment]
This is still relevant

**Comment by fashxp** [comment]
then we would love to see a PR
