### ISSUE TITLE
Increase max length of "Tags" to 255 characters

### ISSUE THREAD

**Issue by Sunohara666** [pimcore/pimcore#815]
suggestion: lets get rid of the 20 character limit

**Comment by brusch** [comment]
See also: #791

**Comment by Sunohara666** [comment]
Dear Bernie,

Created this issue because #791 was closed and i still need the longer tag names.

Please consider my request. Otherwise I will have to make some workaround for it.

Kind regards!

**Comment by brusch** [comment]
I know, this note was just for me/us as a reference ;-)
