### ISSUE TITLE
Wrong URL paths generated when using multiple sites

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#8151]
## Bug Description
When a document is called via different domains / sites, wrong URL paths are generated.

### Requirements
- usage of documents as a ``site`` in Pimcore
- full page cache feature is activated via system settings.

### Current behavior
 - Document is called in preview mode: https://www.domain1.com/siteA.com?pimcore_preview=true.
 - Document is called via actual domain name: https://www.siteA.com/
 - As a result, all navigation links are wrong (e.g., "www.domain1.com/siteA.com/some-document" instead of "/some-document").  The wrong paths are already part of the fullpage cache.

### Expected behavior
 - Document is called in preview mode: https://www.domain1.com/siteA.com?pimcore_preview=true and must not be cached.

### Solution Suggestion
As a workaround we suggest the following change in the ``FullPageCacheListener.php``:

Method `` public function onKernelResponse(FilterResponseEvent $event)``:
- Add ``$this-disable()`` before return statement.

```php
        $request = $event->getRequest();
        if (!\Pimcore\Tool::isFrontend() || \Pimcore\Tool::isFrontendRequestByAdmin($request)) {

            // hotfix start
            $this->disable('no frontend request or admin request.');
            // hotfix end

            return;
        }

       //...
```

**Comment by passioneight** [comment]
Seems to be resolved by https://github.com/pimcore/pimcore/pull/8328/commits/d7e88aec8a073f9c8d7ca5aaef9d34ab31f411f6
