### ISSUE TITLE
[Website Settings] Change storage to database

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#8156]
Better cloud compatibility.

**Comment by solverat** [comment]
Finally! 👌👍👍

This also applies to
- robots.php
- reports.php
- qrcode.php (deprecated i guess)
- customreports.php

these are environment sensitive and can be changed at runtime.

**Comment by brusch** [comment]
Robots could go to the new settings store I guess #8332

**Comment by NiklasBr** [comment]
I ❤️ this, but can you clarify in docs how this works with Environments? Today we have API keys ([as mentioned](https://pimcore.com/docs/pimcore/current/Development_Documentation/Tools_and_Features/Website_Settings.html)) which are different for each env and this means we can no longer quickly copy the DB from e.g. Prod to QA without having to ignore some tables.

**Comment by brusch** [comment]
If you have env. specific settings, probably Symfony Config is the way to go.

**Comment by dpfaffenbauer** [comment]
@brusch is right here. Website Config is installation dependant. as it references ID's of assets, objects and documents.

**Comment by brusch** [comment]
Robots.txt: done #8551 

For custom-reports I do not fully agree, here it depends on the use-case 🤔

**Comment by dpfaffenbauer** [comment]
honestly, every config that can be changed in backend should be stored in database.

**Comment by brusch** [comment]
Well your opinion and your use-cases, ... I honestly don't want to see the class definitions stored in DB.

**Comment by dpfaffenbauer** [comment]
true, that could be a symfony config (or other form of config read and interpreted on container compilation): https://github.com/pimcore/pimcore/issues/8250.

I would see the backend UI as an addition to the file format.

**Comment by dpfaffenbauer** [comment]
BTW: compiled data for the class definition might also increase performance a bit, since it doesn't have to read the file and interpret that everytime pimcore needs a class-definition ;)
