### ISSUE TITLE
[DataObject] ColumnType change for existing classes

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#8158]
# Improvement
At the moment, if there's a change in Object Datatype (query) column type then it is quite hard to update existing class tables as they are always rebuild based on generated definition file.

Solution: Consider column type from Datatype class on every class save.

Also remove temp solution: https://github.com/pimcore/pimcore/pull/8116/files#diff-d2564b1d2701cc3ab300240f945b53cb21a2466232ad24ad2e5d75f10f5789faR679-R688

**Comment by dpfaffenbauer** [comment]
Suggesstion: Add List of Options a certain has and should save. These options (OptionsResolver maybe) get exported and imported. everything else is static to the certain type.

**Comment by dvesh3** [comment]
@dpfaffenbauer how about we just maintain a list of blocked properties, which are cleaned up on export? then we don't need to maintain extra list of options for every data-type.

**Comment by dpfaffenbauer** [comment]
that works for internals, but not for external types where you might add new properties that should not be exported

**Comment by dvesh3** [comment]
When data type itself can decide if a property should be exported or not, that can be overridden in custom types. that will solve the purpose...right?

**Comment by dpfaffenbauer** [comment]
guess so, yes

**Comment by dvesh3** [comment]
@dpfaffenbauer could you please review https://github.com/pimcore/pimcore/pull/8200/commits/320b69ac19f792edd4eba79c970a2ebd6975e672? thanks!
