### ISSUE TITLE
Error while removing Base unit from a quantity value.

### ISSUE THREAD

**Issue by neha04** [pimcore/pimcore#8159]
Set base unit in a quantity value. Now try to remove that selected value. Error will apprear in popup.

An exception occurred while executing 'INSERT INTO `quantityvalue_units` (`id`, `abbreviation`, `group`, `longname`, `baseunit`, `reference`, `factor`, `conversionOffset`, `converter`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE `id` = ?, `abbreviation` = ?, `group` = ?, `longname` = ?, `baseunit` = ?, `reference` = ?, `factor` = ?, `conversionOffset` = ?, `converter` = ?;' with params ["EUR", null, null, "", "-1", null, null, null, "", "EUR", null, null, "", "-1", null, null, null, ""]: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`marriot`.`quantityvalue_units`, CONSTRAINT `fk_baseunit` FOREIGN KEY (`baseunit`) REFERENCES `quantityvalue_units` (`id`) ON DELETE SET NULL ON UPDATE CASCADE)

Server threw exception - could not perform action. Please reload the admin interface and try again.

**Comment by weisswurstkanone** [comment]
Already fixed via https://github.com/pimcore/pimcore/issues/9865
