### ISSUE TITLE
Pimcore WebTestCase Error

### ISSUE THREAD

**Issue by MyZik** [pimcore/pimcore#8172]
# Bug Report

### Expected behavior
Pimcore WebTestCase (PHPUnit) should work :)

### Actual behavior
I've opened a discussion here https://github.com/pimcore/pimcore/discussions/8162 and thought that it can be my implementation error. But it doesn't work on a clean Pimcore skeleton project.
### Steps to reproduce
I've tried to reproduce it with the clean pimcore-skeleton project. (Pimcore Demo package doesn't have any tests)

**composer.json:**
```json5
{
...
"autoload": {
    "psr-4": {
      "": ["src/"],
      "Pimcore\\Model\\DataObject\\": "var/classes/DataObject",
      "Pimcore\\Model\\Object\\": "var/classes/Object",
      "Website\\": "legacy/website/lib",
      "Tests\\": "tests"
    },
    "classmap": [
      "app/AppKernel.php"
    ]
  },
...
}
```

The [documentation](https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Testing/Application_Testing.html#page_PHPUnit) says, that we need to add this in composer.json:
```json5
"exclude-from-classmap": [
  "vendor/phpunit"
]
```
But if we do this, we will get an error by phpunit command:
`PHP Fatal error:  Uncaught Error: Class 'PHPUnit\TextUI\Command' not found in /.../pimcore-skeleton/vendor/phpunit/phpunit/phpunit:61`

Okay. Let's try to implement the simple test.

**tests/bootstrap.php**
```php
<?php

// tests/bootstrap.php

include "./vendor/autoload.php";

\Pimcore\Bootstrap::setProjectRoot();
\Pimcore\Bootstrap::bootstrap();
```

/**phpunit.xml.dist**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/7.4/phpunit.xsd"
         bootstrap="tests/bootstrap.php"
         colors="true">
    <testsuite name="default">
        <directory suffix="Test.php">tests</directory>
    </testsuite>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">src</directory>
        </whitelist>
    </filter>

    <php>
        <!-- adjust as needed -->
        <env name="PIMCORE_ENVIRONMENT" value="test" />
        <env name="SYMFONY_PHPUNIT_VERSION" value="7.4" />
        <env name="KERNEL_DIR" value="app" />
        <env name="KERNEL_CLASS" value="AppKernel" />
        <env name="SYMFONY_DEPRECATIONS_HELPER" value="disabled" />
    </php>
</phpunit>
```

And a controller:
**/src/AppBundle/Controller/MyController.php**
```php
<?php

declare(strict_types=1);

namespace AppBundle\Controller;

use Pimcore\Controller\FrontendController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends FrontendController
{
    /**
     * @Route("/main")
     */
    public function mainAction()
    {
        return new Response('Success!', 200);
    }
}
```
I can see the response. So, it works.
<img width="415" alt="Bildschirmfoto 2021-02-15 um 11 22 07" src="https://user-images.githubusercontent.com/12817320/107934198-0bd5f380-6f80-11eb-8f06-302098c121af.png">

And let's write the test:
```php
<?php

declare(strict_types=1);

namespace Tests\AppBundle\Controller;

use Pimcore\Test\WebTestCase;

class MainControllerTest extends WebTestCase
{
    public function testMainAction()
    {
        $client = static::createClient();
        $client->request('GET', '/main');
        // $client->request('GET', 'http://localhost:2000/main'); // It doesn't work too

        $response = $client->getResponse();

        $this->assertTrue($response->isSuccessful());
    }
}
```

If I try to run this test, an error will be thrown:
<img width="777" alt="Bildschirmfoto 2021-02-15 um 11 33 25" src="https://user-images.githubusercontent.com/12817320/107935593-e0540880-6f81-11eb-8c56-8d62383cea1e.png">

So, if I want to dump the response, at the end of the dump, we will get a reason:
`dump($response = $client->getResponse());`
<img width="817" alt="Bildschirmfoto 2021-02-15 um 11 39 27" src="https://user-images.githubusercontent.com/12817320/107936080-7c7e0f80-6f82-11eb-8f5e-388e678815e0.png">

**Comment by mauveine** [comment]
@MyZik 

If you haven't fixed this issue yet, you have to modify the `config_test.yml` inside `app/config`.
Basically you have to copy the values from `app/config/local/database.yml` to this `config_test`.

Here is an example:
Before it was:
```
doctrine:
    dbal:
        connections:
            default:
                url: '%pimcore_test.db.dsn%'
                host: ~
                port: ~
                dbname: ~
                user: ~
                password: ~
```
And this is how it should be:
```
doctrine:
    dbal:
        connections:
            default:
                url: '%pimcore_test.db.dsn%'
                host: mysql
                port: 3306
                dbname: pimcore
                user: pimcore
                password: pimcore
```

My database.yml file looks like this:
```
doctrine:
    dbal: { connections: { default: { host: mysql, port: 3306, user: pimcore, password: pimcore, dbname: pimcore } } }
```

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
