### ISSUE TITLE
[FR] Copy mail parameters from sent mail to test mail

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#8173]
# Feature Request
## Feature description

If you send emails, they can have parameters. You can also fill these parameters manually when sending a testmail (for example to test a document of type email). Those parameters can be complex and there can be a lof of parameters, which have to be filled manually for testing a mail template. It'd make things easier, if we could copy the parameters from sent emails:
![sent-mails-parameters-copy](https://user-images.githubusercontent.com/2771909/107947005-16998400-6f92-11eb-93e4-473c87aca043.png)

And paste them in the test email creation:

![email-document-send-test-paste](https://user-images.githubusercontent.com/2771909/107947016-18fbde00-6f92-11eb-9513-cec0e3c90aad.png)

You could easily reproduce mails with new templates this way.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
