### ISSUE TITLE
[DOCS] Update Migrations

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#8176]
Mainly on this page: 
https://github.com/pimcore/pimcore/blob/master/doc/Development_Documentation/19_Development_Tools_and_Details/37_Migrations.md#L117-L116

Follow up to #7543

The new abstract class for bundles `BundleAwareMigration` should be included as well:
https://github.com/pimcore/pimcore/pull/8337/files#diff-81a85db243d7ceab10391b5962777708d43996d7b8f6688bb214aaf766870898R21

**Comment by fashxp** [comment]
all custom data types now need to implement `TypeDeclarationSupportInterface`

https://github.com/pimcore/pimcore/pull/7583/files#diff-b5f1d85f837f86e84cd4a1a905d034c9c71bf3124bf03e6fcbf6de61919b47e7R24

**Comment by fashxp** [comment]
resave all classes
https://github.com/pimcore/pimcore/pull/8317

**Comment by fashxp** [comment]
changed default values of `setProperty` in document ... `inheritable` now `false`, was `true`

see https://github.com/pimcore/pimcore/commit/3897a15e11da593239910f2130a383599737d4d0#diff-48235de7b392a4ff9ed273062d750e2732a5b1f8355cd76109abf4c5538a6c45R1323
