### ISSUE TITLE
Remove Bruteforce Checker and Use Symfony Login Throtteling

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#8195]
Basically this: https://symfony.com/blog/new-in-symfony-5-2-login-throttling

WDYT?

**Comment by brusch** [comment]
Removed classes should be deprecated in `6.9` first.

**Comment by dvesh3** [comment]
Login-throttling is based on new authentication-based system, so first we need to refactor current authentication system.

**Comment by brusch** [comment]
Moved to Pimcore XI because the new auth system is just optional in Pimcore X, so we can't rely on it.

**Comment by dvesh3** [comment]
Already covered in https://github.com/pimcore/pimcore/pull/10967
