### ISSUE TITLE
[Documents] Static Page Generator

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#8196]
It should be possible to export pages statically onto the public var directory, where the page can then be delivered directly by the web-server (without PHP!). For this the page needs to be saved to a structure that can be resolved by the web-server depending on the request uri. The concept is similar to the one we also use for delivering Assets and Thumbnails. 

#### Examples
Path of document: `/en/Magazine/Lifestyle`
Path of static rendered HTML document: `public/var/tmp/pages/en/Magazine/Lifestyle.html`  

Pretty URL of document: `/Culture`
Path of static rendered HTML document: `public/var/tmp/pages/Culture.html`

# Detailed description

- additional settings (stored in `documents_page` table for static generator
![image](https://user-images.githubusercontent.com/142037/120777459-976e9280-c525-11eb-830f-e0e3a7c011b0.png)
- those settings should be also possible to set on document-types 
- maintenance job that (re-)generates the static pages  (business logic should be in a shared service that can be used by the command as well)
- command that generates the static pages incl. the possibility to filter pages e.g. by parent path
- Apache/Nginx rule to serve static pages directly (similar to Assets & thumbnails), in case using a local storage
- public action (in `PublicServicesController` that can serve static pages even if using a remote storage
- #8081 could probably also be helpful

**Comment by solverat** [comment]
Do you also consider object SSR? This should be possible by using link generators, right?

**Comment by brusch** [comment]
@solverat yep, we should definitely consider that as well, even if we implement it later on.

**Comment by solverat** [comment]
Very! Nice!

**Comment by drietsch** [comment]
Let's go Pimcore. Great feature.

**Comment by dpfaffenbauer** [comment]
@brusch whats the time horizon for this?

**Comment by brusch** [comment]
@dpfaffenbauer This topic is actually on our list for the next 2 weeks in terms of new features  (@dvesh3 is working on that, if you want to contribute or if you have additional thoughts on that) . But as bugs have always priority I can't promise anything, but it's definitely one of the features that will be in `10.1.0`.

**Comment by dpfaffenbauer** [comment]
Just let me know when you have some progress, I could help in a way or another.

**Comment by dvesh3** [comment]
Hi @dpfaffenbauer, you can review the progress here #9447. I would appreciate your feedback on this 😉

**Comment by NiklasBr** [comment]
Will this have support for [ESI](https://symfony.com/doc/current/http_cache/esi.html)? We use it for GDPR consent at the moment.
