### ISSUE TITLE
Filtering by columns does not work in search dialog

### ISSUE THREAD

**Issue by mediafant** [pimcore/pimcore#821]
### Steps to reproduce  
- select Moderne Benutzungsschnittstelle (Ext JS 6)
- on objectFolder select "search&move"
- filter objects by header/select by "filter" -> it doesn't work

**Comment by fashxp** [comment]
see: 
![image](https://cloud.githubusercontent.com/assets/8792145/18000235/5d2b2770-6b7d-11e6-9d02-84625b2702b0.png)

**Comment by mediafant** [comment]
yes - screen is ok, but it doen't filter it. I selected a long eventlist
with older and newer dates. When i filter "before date" list is empty,
and "after" it is also empty. Than a test by name also empty results.


Am 26.08.16 um 11:08 schrieb fashxp:

**Comment by fashxp** [comment]
it seems there is a general problem with filtering in search dialog. we'll have a look at it...
