### ISSUE TITLE
Mass Uploading images with AWS and S3

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#8213]
We have a really weird issue with Mass Uploading Images on AWS (Serverless Container with ALB) and S3:

1. It runs into transaction timeouts (probably cause copy to s3 takes longer than the keeps transactions open):

```
message: "Transaction commit failed because the transaction has been marked for rollback only."
```

Workaround: Change transaction timeout on mysql level.

2. It runs the uploads not sequential, like it does locally, it runs all of them at once, which leads to lot of different timeouts:

Local (Sequential, 5 at once): http://recordit.co/kpgm4BHKSM
AWS (Parallel, all at once):   https://recordit.co/h91l1ChYog

I am not sure what causes the sequential upload... Pimcore starts uploads all at once, without a queue so to say.

No workaround found yet...

**Comment by rubanooo** [comment]
Relates to #6682
