### ISSUE TITLE
Restore from recycle bin throws error

### ISSUE THREAD

**Issue by fracsi** [pimcore/pimcore#8236]
# Bug Report
- [x] Behavior is reproducible on https://demo.pimcore.fun/admin/ (admin/demo)

### Expected behavior
If a DataObject is deleted, and the parent folder is also deleted, the DataObject cannot be restored.

### Actual behavior
The DataObjet cannot be restored. An Exception is thrown.
`Call to a member function isAllowed() on null` at https://github.com/pimcore/pimcore/blob/master/models/Element/Recyclebin/Item.php#L159
### Steps to reproduce
1. Create a new folder for Data Objects
2. Add a DataObject in the folder
3. Delete the DataObject
4. Delete the folder previously cerated
5. Try to restore the DataObject from the Recycle Bin

**Comment by dvesh3** [comment]
Fixed by #8267

**Comment by laurent-pi** [comment]
Hey.
I have the same error on my v5.6.5

Timestamp: Wed Oct 09 2024 13:28:45 GMT+0200 (Central European Summer Time)
Status: 500 | Internal Server Error
URL: /admin/recyclebin/restore
Method: POST
Message: Call to a member function isAllowed() on null

Should it be fixed for this version too or do i have to update my version?

Thank you
