### ISSUE TITLE
Implement Symfony HttpExceptionInterface for some exceptions

### ISSUE THREAD

**Issue by fracsi** [pimcore/pimcore#8243]
# Feature Request
- [X] There is no existing issue regarding the same topic
## Feature description
Symfony's ErrorListener (`\Symfony\Component\HttpKernel\EventListener\ErrorListener`) always logs errors with critical if the Exception does not implement HttpExceptionInterface (`\Symfony\Component\HttpKernel\Exception\HttpExceptionInterface`) or the status code is 5xx.

https://github.com/symfony/symfony/blob/8054d1d04cb6c8162b6bd414691ff2acd1536422/src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php#L126-L130

Some of the exception (not all of course) thrown in Pimcore should implement this interface - so developers could [filter out](https://symfony.com/doc/4.4/logging/monolog_exclude_http_codes.html) these logs.

### Example:
`Pimcore\Model\Element\ValidationException` should not be treated as `500 Internal Error`, but as `422 Unprocessable Entity`.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
