### ISSUE TITLE
Block in FieldCollections with Localized fields fails in an exception

### ISSUE THREAD

**Issue by abernardgalilee** [pimcore/pimcore#8248]
# Bug Report

This problem occurs with demo environment after update of the core to 6.8.10.

### Expected behavior
I am expecting my product to be saved

[Archive.zip](https://github.com/pimcore/pimcore/files/6028170/Archive.zip)

### Actual behavior
Exception is raised.

Timestamp: Tue Feb 23 2021 11:06:12 GMT+0100 (heure normale d’Europe centrale)
Status: 500 | Internal Server Error
URL: /admin/object/save?task=publish
Method: PUT
Message: Call to undefined method getOptions in class Pimcore\Model\DataObject\Product
Trace: 
in /home/web-user/htdocs/pimcore/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:251
#0 /home/web-user/htdocs/pimcore/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(1340): Pimcore\Model\AbstractModel->__call('getOptions', Array)
#1 /home/web-user/htdocs/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data.php(1475): Pimcore\Model\DataObject\AbstractObject->__call('getOptions', Array)
#2 /home/web-user/htdocs/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Localizedfields.php(295): Pimcore\Model\DataObject\ClassDefinition\Data->getDataFromObjectParam(Object(Pimcore\Model\DataObject\Product), Array)
#3 /home/web-user/htdocs/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Block.php(340): Pimcore\Model\DataObject\ClassDefinition\Data\Localizedfields->getDataFromEditmode(Array, Object(Pimcore\Model\DataObject\Product), Array)
#4 /home/web-user/htdocs/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Localizedfields.php(314): Pimcore\Model\DataObject\ClassDefinition\Data\Block->getDataFromEditmode(Array, Object(Pimcore\Model\DataObject\Product), Array)
#5 /home/web-user/htdocs/pimcore/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Fieldcollections.php(210): Pimcore\Model\DataObject\ClassDefinition\Data\Localizedfields->getDataFromEditmode(Array, Object(Pimcore\Model\DataObject\Product), Array)
#6 /home/web-user/htdocs/pimcore/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(1217): Pimcore\Model\DataObject\ClassDefinition\Data\Fieldcollections->getDataFromEditmode(Array, Object(Pimcore\Model\DataObject\Product))
#7 /home/web-user/htdocs/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(158): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#8 /home/web-user/htdocs/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#9 /home/web-user/htdocs/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /home/web-user/htdocs/pimcore/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#11 {main}

### Steps to reproduce
https://www.loom.com/share/aeba8bb020d04f61aaa655282fa67d5c

It tries to call method getOptions from the Product Class but this method does not exist.

**Comment by robin-ntriga** [comment]
https://pimcore.com/docs/platform/Pimcore/Objects/Object_Classes/Data_Types/Blocks

> A block element can be placed into a localized field but can also contain a localized field itself. Nesting is not possible.

According to the documentation using a Localized field inside of a Block should work, but as of Pimcore 11.0.11 the issue still persists for FieldCollections.

**Comment by fashxp** [comment]
sadly that is not supported, see also https://github.com/pimcore/pimcore/issues/6319#issuecomment-621645271
