### ISSUE TITLE
Multisite site-specific website settings not available in admin

### ISSUE THREAD

**Issue by Swissbrain** [pimcore/pimcore#825]
We use the website settings with the Site Attribute for each specific site.
In the frontend, this works. However, if we log into the admin with site1/admin and open the site2 documents, the website settings for site2 are not available and the website settings for site1 are shown.
### Expected behavior 
  Site specific website settings displayed in admin mode
### Actual behavior  
  default/main site website settings displayed in admin mode
### Steps to reproduce  
1. Create additional site
2. Create website setting for newly created site
3. Output website setting in the newly created site

**Comment by mrudnicki** [comment]
Hi @Swissbrain,
Thanks, I've checked it and is like you mentioned. Website settings are not accessible in admin mode for sites with a different domain.
I'm going to look into it.

**Comment by Swissbrain** [comment]
We tested the solution and now works perfectly. 

Thanks for the fix.

**Comment by dangvantanh** [comment]
Hi Team,

I thinks Pimcore should support multi site which will good a big company. currently, our company have 15 brands and use drupal 7 but drupal 7 is too slow than pimcore. and have a site use pimcore and it is perfectly.   

thanks
