### ISSUE TITLE
[Assets] ui broken if asset metadata is edited in list

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#8260]
# Bug Report

### Steps to reproduce

1. Add 2 text columns to the asset list's gridoptions (i.e. title and alt)
2. Edit these columns in several lines
3. A JS error is thrown and the whole ui becomes unresponsive

Issue could be reproduced in 6.6.2 and 6.8.8 (current demo version).

![45666B22-EF3F-4BFA-97AE-171AA7734290](https://user-images.githubusercontent.com/9052094/108863321-5e9f5300-75f1-11eb-9f70-78708234879b.GIF)

**Comment by dvesh3** [comment]
This comes from ExtJS https://forum.sencha.com/forum/archive/index.php/t-305120.html?s=a4015ba2662ffa2197430d743bd1c301. Also, confirmed this works on Pimcore 10 with ExtJS7

**Comment by brusch** [comment]
Fixed in ExtJS 7 -> Pimcore X
