### ISSUE TITLE
AbstractOrderList:getItems doesn't match interface

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#8261]
currently in the baseline: https://github.com/pimcore/pimcore/blob/8b18a7e7126948df2e77fb0b76a188c29dec1c78/phpstan-baseline.neon#L5

message: "#^Method Pimcore\\\\Bundle\\\\EcommerceFrameworkBundle\\\\OrderManager\\\\AbstractOrderList\\:\\:getItems\\(\\) should return array\\<Pimcore\\\\Bundle\\\\EcommerceFrameworkBundle\\\\OrderManager\\\\OrderListItemInterface\\> but returns Pimcore\\\\Bundle\\\\EcommerceFrameworkBundle\\\\OrderManager\\\\OrderListInterface\\.$#"

needs investigation...

**Comment by brusch** [comment]
@weisswurstkanone @fashxp don't think this is a BC break as it is just PhpDoc, isn't it? Thanks for confirmation.
