### ISSUE TITLE
Catalog page using aerablock PrintProductTable does not work properly

### ISSUE THREAD

**Issue by MagPim** [pimcore/pimcore#8264]
# Bug Report

### Expected behavior
The PrintProductTable allows to select different items like cars and select which fields should be shown.
It should be possible to save and see the nice resulting table

### Actual behavior
Once the list is filled with data, impossible to save. 
Worse, if you try to just save and publish your Muscle Cars Highlights for instance, on the catalog example from your demo site, you can't... You get the error : Attempted to call an undefined method named "getFullPath" of class "Pimcore\Model\Element\ElementDescriptor".

### Steps to reproduce
Open a print page and use the PrintProductTable aerablock or open an existing page containing one and try to save the page. 

### Code example
```php
// your code
```
No need

# Feature Request

**Comment by MagPim** [comment]
It is also not possible to generate the pdf (using pdfReactor) on most of your catalog demo pages, maybe for the same reason.

**Comment by fashxp** [comment]
will be fixed with https://github.com/pimcore/web2print-tools/pull/16
