### ISSUE TITLE
Not All Tables Have Primary Keys

### ISSUE THREAD

**Issue by jeremygnoonan** [pimcore/pimcore#8265]
# Feature Request

## Feature description

I ran into this issue when I was trying to get Pimcore installed on Digital Ocean managed K8s with their managed MySql service. 

Digital Ocean only runs MySQL 8.0 now and always has the setting `sql_require_primary_key` set on their servers. Its not possible to change this, apparently it improves the performance of their data replication. I was able to hack at the code to get it to install, but know I left my environment in a partially broken state.  The only table I can see that is missing a primary key as of lately (thanks to the relations tables getting it a few months back) is the `notes_data` table.

From what I can tell I need to make 2 changes to resolve this.

1. Add a primary key to the `notes_data` table. I think the cleanest solution would be to add a `note_id` column to the `notes_data` table and make it a FK back to the parent notes table. The `id` column could then be repurpose for an actual PK. I understand that may be a "breaking change" for SQL queries, so I would be okay to use a `ndid` (note data id) column to be an auto-increment ID and make the id column an FK back to the `notes` table. I support a non-breaking change, but the 'id' column name is unfortunate if its not going to be the actual id for the table.

2. In the installation process, the requirement checker drops/adds a primary key as part of checking whether the MySQL user has permission to manage indexes. I've think we could change this to work slightly differently. I am suggesting this code:

**NEW:**

```
$db->query('CREATE INDEX field_alter_field ON __pimcore_req_check (field, alter_field);');
          
$db->query('DROP INDEX field_alter_field ON __pimcore_req_check;');
```

**OLD:**

```
$db->query('ALTER TABLE __pimcore_req_check
                  CHANGE COLUMN id id int(11) NOT NULL,
                  CHANGE COLUMN field field varchar(190) NULL DEFAULT NULL,
                  CHANGE COLUMN alter_field alter_field varchar(190) NULL DEFAULT NULL,
                  ADD KEY field (field),
                  DROP PRIMARY KEY ,
                 DEFAULT CHARSET=utf8mb4');

$db->query('ALTER TABLE __pimcore_req_check
      CHANGE COLUMN id id int(11) NOT NULL AUTO_INCREMENT,
      CHANGE COLUMN field field varchar(190) NULL DEFAULT NULL,
      CHANGE COLUMN alter_field alter_field varchar(190) NULL DEFAULT NULL,
      ADD PRIMARY KEY (id) ,
     DEFAULT CHARSET=utf8mb4');
```

If the community approves this I will submit a PR to fix.

**Comment by brusch** [comment]
@jeremygnoonan A PR would be really nice! A breaking change is ok, since this should go on the master (`10.x`). 
Looking forward to your PR!
