### ISSUE TITLE
frontend() method of Document/Tag/Image.php triggers thumbnail event

### ISSUE THREAD

**Issue by sattes-faction** [pimcore/pimcore#827]
When the frontend-method of an image is called now it also throws the event `frontend.path.asset.image.thumbnail`, this change was introduced in this commit:
https://github.com/pimcore/pimcore/commit/b70db9e1fd73383aeeaf8af8fa3e89cbf02ac288

Is this on purpose?

**Comment by brusch** [comment]
Yes, if a thumbnail has to be generated within `frontend()` it has to fire the event `frontend.path.asset.image.thumbnail` otherwise it would be useless :)

**Comment by brusch** [comment]
The event is fired here: 
https://github.com/pimcore/pimcore/blob/b98bef1620ab930eccf1e5ee0fab18042b49ea11/pimcore/models/Asset/Image/Thumbnail.php#L100-L100 

So completely independent from where the thumbnail generation is called from.

**Comment by sattes-faction** [comment]
In my case I have an image editable which just should output the original without creating a thumbnail:

    <?= $this->image('myImage') ?>

After upgrading from 4.2.0 to 4.3.0 the cloudfront integration did not work anymore:

https://www.pimcore.org/wiki/display/PIMCORE4/CDN+-+Amazon+Cloudfront

The rendering of this image now fired the event `frontend.path.asset.image.thumbnail` which did not create the correct frontend path anymore, instead of e,g, `https://d2m10exxxxx123.cloudfront.net/my-images/my-image.jpg` it returned the relative path `/my-images/my-image.jpg`.
