### ISSUE TITLE
[bug] Classification Store doesn't allow null

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#8277]
# Bug Report

After [this change](https://github.com/pimcore/pimcore/commit/508d4e9d069d3259f348c5ff020181872a1a351a#diff-5959ee96b2dc092ba3e0a5d9834745486efc70ed786934bd466e72e310a575f7R104), we noticed a regression where all our quantity values were suddenly giving `0` where they should be empty, corrupting the values (because zero is a valid value in some cases).

The linked change prevents classification store to ever be `null`, which doesn't seem expected.

### Expected behavior

Allow `null` in classification store.

### Actual behavior

`null` cast to an empty string which is then interpreted as `0` by quanity unit.

### Steps to reproduce

1. add Quanity unit to a CS
2. set it to something
3. delete the value, make it empty
4. reload the object, now it's set to `0`

**Comment by brusch** [comment]
Fixed by #8278
