### ISSUE TITLE
Fatal Error when saving objects with password fields in fieldcollections

### ISSUE THREAD

**Issue by axel-tietje** [pimcore/pimcore#828]
### Expected behavior 

I can save an object that has a password field and items in a fieldcollection that contains a password field.
  
### Actual behavior  

When both password fields have the same name, the password of the object will be overwritten by the fieldcollection item's hashed value.

When the fieldnames differ, you'll get a fatal error:

`Fatal error: Uncaught Exception: Call to undefined method setPasswd in class Pimcore\Model\Object\Demo in /home/pimcore_demo/www/pimcore/lib/Pimcore/Model/AbstractModel.php:266 Stack trace: #0 /home/pimcore_demo/www/pimcore/models/Object/AbstractObject.php(1193): Pimcore\Model\AbstractModel->__call('setPasswd', Array) 
#1 /home/pimcore_demo/www/pimcore/models/Object/ClassDefinition/Data/Password.php(174): Pimcore\Model\Object\AbstractObject->__call('setPasswd', Array) 
#2 /home/pimcore_demo/www/pimcore/models/Object/Fieldcollection/Data/Dao.php(59): Pimcore\Model\Object\ClassDefinition\Data\Password->getDataForResource('password', Object(Pimcore\Model\Object\Demo)) 
#3 [internal function]: Pimcore\Model\Object\Fieldcollection\Data\Dao->save(Object(Pimcore\Model\Object\Demo)) 
#4 /home/pimcore_demo/www/pimcore/lib/Pimcore/Model/AbstractModel.php(257): call_user_func_array(Array, Array) 
#5 /home/pimcore_demo/www/pimcore/models/Object/Fieldcollection.php(120): Pimcore\Model\AbstractModel->__call('save', Array) 
#6 /home/pimcore_d in /home/pimcore_demo/www/pimcore/lib/Pimcore/Model/AbstractModel.php on line 266
`

In addition to that, the objects password seems to be hashed twice, see screenshots of my IDE:

first call:
![first call](https://cloud.githubusercontent.com/assets/20833102/18093212/61087a82-6ecf-11e6-9cfd-58907ce89577.png)

second call
![second call](https://cloud.githubusercontent.com/assets/20833102/18093213/61094994-6ecf-11e6-9a6c-15cf35cab60a.png)

By the way: the third parameter in Password::getDataForResource is unused.

### Steps to reproduce  

1. Create a class and a fieldcollection using the attached definition files: [definitions.zip](https://github.com/pimcore/pimcore/files/445074/definitions.zip)
2. Create a new object, set a value in the password field of the object
3. Add a fieldcollection item and set a password too.
4. Save the object, you should get an error message.

Currently I've no idea how to fix the issue, since I don't know how to tell wether the object's or the fieldcollection item's hashed password is set in [Password.php](https://github.com/pimcore/pimcore/blob/master/pimcore/models/Object/ClassDefinition/Data/Password.php#L172) without a silly debug_backtrace().

**Comment by mrudnicki** [comment]
Thanks,
I will look at it

**Comment by axel-tietje** [comment]
Currently I'm working around that by changing Password.php#L172 to:

```
        if ($object) {
            $setter = "set" . ucfirst($this->getName());
	        if (method_exists($object, $setter)) {
	            $object->$setter($hashed);
	        }
        }
```

but that only helps if fieldnames differ.

**Comment by mrudnicki** [comment]
Hi @axel-tietje 
I've found a good solution, In one hour change should be visible in the repository.
