### ISSUE TITLE
Brick validation exception Pimcore\Model\DataObject\AbstractObject::get(), 0 passed 

### ISSUE THREAD

**Issue by ascheider** [pimcore/pimcore#8285]
If brick is placed inside of the localized field and has mandatory fields, pimcore throws exception instead of validation exception.
![Bildschirmfoto 2021-02-25 um 16 05 27](https://user-images.githubusercontent.com/6016485/109173018-abb32e80-7783-11eb-87dc-7ffbdeae0c3f.png)
![Bildschirmfoto 2021-02-25 um 16 05 17](https://user-images.githubusercontent.com/6016485/109173050-b66dc380-7783-11eb-81dc-23eafaec2762.png)
currently reproducible on https://demo.pimcore.com/ system.
it appears if you do not input any data in the mandatory field.

**Comment by brusch** [comment]
@ascheider can you please confirm #8326 solves the issue? 
Thanks for checking!

**Comment by dvesh3** [comment]
Fixed by #8326

**Comment by ascheider** [comment]
@brusch yes, it works. Thanks
