### ISSUE TITLE
Error saving assets with object metdata and the dependency is not saved correctly on the db

### ISSUE THREAD

**Issue by lmeazza** [pimcore/pimcore#8293]
# Bug Report

### Expected behavior
Save metadata resources without errors and see the metadata dependencies.

### Actual behavior
An error is generated when saving the asset containing object type metadata.

## NB: The error message appears only in debug mode but dependencies are not displayed in any case.
- Add object type metadata to the asset and save the asset.
- Reload the asset.
- Save the asset.

![image](https://user-images.githubusercontent.com/63634753/109308488-60138a00-7842-11eb-8a17-8d4f6d87487b.png)

![image](https://user-images.githubusercontent.com/63634753/109308546-74578700-7842-11eb-9661-ef1205201423.png)

![image](https://user-images.githubusercontent.com/63634753/109308657-98b36380-7842-11eb-857f-8b8d2ab56802.png)

![image](https://user-images.githubusercontent.com/63634753/109309262-5179a280-7843-11eb-9bb0-3e4ff5629df6.png)

![image](https://user-images.githubusercontent.com/63634753/109308415-44a87f00-7842-11eb-87db-d984cc7b59ab.png)

# Feature Request

- Saving assets without any errors (debug mode)
- See the metadata linked to the asset in the dependencies.

**Comment by brusch** [comment]
Fixed by #8296
