### ISSUE TITLE
web2print PDF generating not working when using PIMCORE_ENVIRONMENT

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#830]
- be sure that you're using a different PIMCORE_ENVIRONMENT 
- create web2print Document
- try to "generate PDF"

Request will hang up in a infinity loop because no valid db settings has been found.

**Comment by fashxp** [comment]
could you debug this further and give us some more hints or even a pull-request? thank you very much

**Comment by solverat** [comment]
i just pushed a pr.
