### ISSUE TITLE
Units using varchar(50) IDs causes tables to reach maximum row length quickly

### ISSUE THREAD

**Issue by beheist** [pimcore/pimcore#8300]
Hey all,

this is not really a bug per se, but a bit of an nuisance nevertheless. 
I noticed that the ID field for units uses varchar(50) on the database level, instead of int(11) as e.g. the assets or objects tables do. This causes this field type to be used for the foreign key fields in object tables where units are used as well, which in turn leads to unnecessarily big row lengths. In classes that use lots of quantity values, tables reach the maximum row length very quickly. Can this field be changed to a shorter ID in future releases, so that we do not run into this issue as fast?
Thanks!

**Comment by aweichler** [comment]
Hi.
I got an error when Updating from PImcore 6.6.x to Pimcore 6.8.10.
It comes from migration "20210211152319".
The error is "SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large (> 8126). Changing some columns to TEXT or BLOB may help. In current row format, BLOB prefix of 0 bytes is stored inline.".
Is there a solution for this issue?
The table has ~150 columns.
I am on MariaDB 10.5 with default settings. On Mysql 5.7 it works. But in production system i can not change the db server.
What was the intention for this change?

**Comment by johannesdold** [comment]
Hi. We have the same problem. As it is a large PIM system, we cannot easily extract the quantity values into other classes. Is there a change, that the column definition will be changed as @beheist proposes?

**Comment by weisswurstkanone** [comment]
Background: https://github.com/pimcore/pimcore/issues/1023

**Comment by johannesdold** [comment]
@weisswurstkanone  Is there any change or reducing the varchar size to maybe 20 or even 10? I would say this gives enough options to define the unit ids. This is really a show stopper in one of our projects, as a change of the data structure would be quite expensive.
