### ISSUE TITLE
Remove CSV Import

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#8315]

**Comment by beheist** [comment]
Hey, what's the reasoning for taking the CSV import away? This is very important for our clients and would lead to a lot of frustration if it was not available anymore in future versions.

**Comment by brusch** [comment]
@beheist see also #8208
There's a much more powerful and easy to use CSV importer available as a data-hub extension. It will be released soon (latest with Pimcore X). For us it doesn't make sense to maintain 2 components for the same purpose, I guess that's a comprehensible decision 😊

**Comment by solverat** [comment]
Well then there is just one final question: Are you going to release the data-hub extension as enterprise or OS?

**Comment by brusch** [comment]
OS

**Comment by Cruiser13** [comment]
@brusch will datahub csv export and import be ready when pimcore x is released?

**Comment by brusch** [comment]
@Cruiser13 
> It will be released soon (latest with Pimcore X).

**Comment by fashxp** [comment]
We've just made the new Pimcore Data Importer public available. There is no release yet, but you can have a dev preview to it and give feedback. 
See: https://github.com/pimcore/data-importer

**Comment by Cruiser13** [comment]
@fashxp thanks! This looks calmingly familiar. Feeling a lot better now!
