### ISSUE TITLE
pimcore.admin.resolve.element not called on object listing?

### ISSUE THREAD

**Issue by palazzetti** [pimcore/pimcore#8336]
# Bug Report
**pimcore.admin.resolve.element** event is not called on DataObject\Classxyz\Listing().
I need to update a field when the object gets opened/retrieved, for fronted there is **pimcore.admin.resolve.elementAdminStyle** while for backend i imagine that the right event to catch is **pimcore.admin.resolve.element**

### Expected behavior
**pimcore.admin.resolve.element** to be fired on Object listing

### Actual behavior
**pimcore.admin.resolve.element** is not fired on Object listing

### Steps to reproduce

- Create event listener
- Register event listener
- Call Listing on a object class

### Code example
services.yml
```yml
AppBundle\EventListener\AdminEventsListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.admin.resolve.element, method: resolveElement }
            - { name: kernel.event_listener, event: pimcore.admin.resolve.elementAdminStyle, method: resolveElementAdminStyle }
```
AdminEventsListener
```php
    public static function getSubscribedEvents()
    {
        return [
            \Pimcore\Event\AdminEvents::RESOLVE_ELEMENT => 'resolveElement',
            \Pimcore\Event\AdminEvents::RESOLVE_ELEMENT_ADMIN_STYLE => 'resolveElementAdminStyle'
        ];
    }

    public function resolveElement(\Pimcore\Event\Model\ResolveElementEvent $event) {
        // https://github.com/pimcore/pimcore/blob/33172450d4cb6c4810777faa8050db3bd014a6bd/lib/Event/AdminEvents.php#L446
        $id = $event->getId();
        $type = $event->getType();
        // Disable Fallback languages
        \Pimcore\Model\DataObject\Localizedfield::setGetFallbackValues(false);
        \Pimcore\Log\Simple::log("miolog", "Sono qua {$id}");
    }
```

**Comment by palazzetti** [comment]
Any updates?

**Comment by palazzetti** [comment]
Up?

**Comment by dvesh3** [comment]
@palazzetti Hi, this is not a bug. `pimcore.admin.resolve.element` is an Admin event and fired when an element is opened. please check all events here: https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Event_API_and_Event_Manager.html#page_Available-Events
