### ISSUE TITLE
Feature - CSV import into classification store.

### ISSUE THREAD

**Issue by rndfm** [pimcore/pimcore#8344]
# Feature Request

## Feature description

It should be possible to import directly into a classification store field from csv.

I have written my own code to import into the classification store from json in a csv field.
It uses name matching for groups and key definitions to import into the classification store.

ex: (csv field value)
{
    "groupname": {
        "keyname" : value,
        "keyname" : value,
        "keyname" : value
    }
}

I'm using the key definitions type to do a fromCsvImport directly so that QuantityValue etc are parsed with their own "FromCsvImport" function.

Does not support localization but could easily be added.
  
Is this something i should make a pull request for? Or do we want another format for this?

**Comment by brusch** [comment]
Obsolete see #8315 maybe a topic for https://github.com/pimcore/data-importer

**Comment by rndfm** [comment]
So no csv import to classification store until version 10 of Pimcore?

**Comment by brusch** [comment]
No, `6.x` is already in support only mode for quite a long time 😉
