### ISSUE TITLE
Improvement: Add personnas targeting for snippet.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#838]
Actually customize some HTML on page for enduser (document editor/marketing people) could only be done on document of type "page". So it can be a tiedous task if the site has many pages...

It would be great to have the same system than "page", but for "snippet" too. So this snippet could be reused on multiple page, and targeting change will be involved only on the snippet making editor life easier.

As a classic use case, it could be a banner in the right colomn of many pages having a text changing depending personnas.
Adding this improvement will make targeting for enduser a lot more usable in terms of content edition. Actullay you made a very powerfull condition/entry management with the backend GUI for enduser (which is so great!), but after they can only use it on pages document (so page by page, no possible to edit global customization of content... painful) :-( (for non-technical people).

Thanks.

For reference, i tried to get around this limitation by including document in another document (i know it's stange ; ) ), but it didn't work (https://github.com/pimcore/pimcore/issues/700).

**Comment by brusch** [comment]
There will be a new concept for targeting / personalization in Pimcore v5 and therefore the entire module will be refactored / redesigned. 
Closed.

**Comment by Yivan** [comment]
Ok, How, it was already a really great component of v4, so i imagine it will be wonderful tool in the v5!
Thanks.
