### ISSUE TITLE
Increased Memory Usage when Saving DataObject with Block in LocalizedFields

### ISSUE THREAD

**Issue by storbahn** [pimcore/pimcore#8381]
# Bug Report

Increased Memory Usage when saving DataObjects which contains Blocks in LocalizedFields

### Expected behavior
The used memory should not differ.

### Actual behavior
After reloading a DataObject (from Cache), changing it and saving it again, then the used memory is increased.

### Steps to reproduce
**(1) Use class export json to create a new Class StorageBug**
[class_StorageBug_export.zip](https://github.com/pimcore/pimcore/files/6109688/class_StorageBug_export.zip)

**(2) Create a new DataObject with one link in Main Block and one link in Additional Block**

![image](https://user-images.githubusercontent.com/16591421/110498313-80233300-80f7-11eb-9897-202e3b867998.png)

**(3) Check the memory usage in the table _object_localized_data_storagebug_**

use the following query to check the length of the fields

SELECT LENGTH(mainBlock), LENGTH(additionalBlock) FROM object_localized_data_storagebug;

I got a length of **537** characters for both fields.

![image](https://user-images.githubusercontent.com/16591421/110498475-a5b03c80-80f7-11eb-832f-68d6b2ec8b7e.png)

**(4) Reload the DataObject, change the Link of the Main Block and save it again**

![image](https://user-images.githubusercontent.com/16591421/110497801-1440ca80-80f7-11eb-92f0-3a26bee3f252.png)

**(5) Check the memory usage in the table _object_localized_data_storagebug_ again**

Now I got **538** characters for the first changed field and **17287** characters for the second field (cache).

![image](https://user-images.githubusercontent.com/16591421/110499071-325afa80-80f8-11eb-94e7-d268880a5147.png)

### Assumption

My assumption is that it relates to the PR https://github.com/pimcore/pimcore/pull/6328.

The problem is that the owner will be serialized too, when it comes from cache.

A workaround for me was to comment the following lines of the class 

_pimcore/pimcore/models/DataObject/Data/BlockElement.php_

![image](https://user-images.githubusercontent.com/16591421/110501944-fecd9f80-80fa-11eb-900d-96dc7cb887e3.png)

**Comment by storbahn** [comment]
Update: The problem is that the complete link DataObject was serialized (with owner property) saved in db.

**Comment by brusch** [comment]
Fixed by #8416
