### ISSUE TITLE
Document Breaking chang in TagsGetter by #7307

### ISSUE THREAD

**Issue by das-peter** [pimcore/pimcore#8399]
Just came across this commit: https://github.com/pimcore/pimcore/commit/3cc25cb7ddc6d57a6d12937d95b9509786b01924#diff-df83d20ef934199d0f7b0332fba78211d07540c5d73d9094e595160716b526bd when debugging a system recently updated to Pimcore 6.8.10
For at least the last 2 years `Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Getter\TagsGetter` returned a list of tag objects which then could be handled using an interpreter.
With the change made:

1. The getter returns tag names instead of tag objects => type change.
2. Returns non-unique, easily duplicated, values as it doesn't take the tag path in account => possible information loss

In my opinion both points at least warrant a breaking change notice. The later one might even be considered a bug in itself.
For the time being we'll re-implement the original code in a project specific getter by ourselves.

Related issues: #7307 #7306

**Comment by brusch** [comment]
You're right, this is a BC break and needs to be reverted, thanks for pointing out! 👍

**Comment by brusch** [comment]
Fixed by #8413

**Comment by das-peter** [comment]
Thanks, feedback and quick action much appreciated.
