### ISSUE TITLE
Translation merger not translated

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#841]
I open this issue to report just a small translation problem.
In extjs6 pimcore\static\js\pimcore\settings\translation\translationmerger.js, line 160, we have:

**title: t("translation_merger_" + this.translationType),**

And **same problem for extjs4 too**.
This give on Pimcore GUI "translation_merger_website" wich isn't translated (not in the POEdit i think).
Is the translationType the module name ? In this case it would be better to have:

**title: t("translation_merger") + this.translationType,**

So just translation_merger is translated and module name is appended.

**Comment by mrudnicki** [comment]
Hi @Yivan 
Translation merger rows prefix is used to specify translations columns in the translation merger grid. If I approved your proposition it would look like below:

1. translation_merger_csv - Translation merger csv
2. translation_merger_current - Translation merger current

And now this is used to show information like that:

1. translation_merger_csv  - Text from CSV
2. translation_merger_current - Current Text

**Comment by Yivan** [comment]
Thanks for your answer mrudnicki, but why the issue has been closed ?
I understand the translation is used at others places, so mayby the translation key need to be changed for the tab name ?

Here is a screenshot of the online Pimcore demo and the tab name is "translation_merger_website".

![translation_merger](https://cloud.githubusercontent.com/assets/9025839/18199489/bb8f5a06-7100-11e6-8dbe-c3e9dc20e23b.png)

**Comment by mrudnicki** [comment]
Thanks @Yivan I will add the translation.
