### ISSUE TITLE
[Documents] Reload does not save editable data to session

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#8428]
using a `pimcore_select` with `reload: true`

when changing select value, save to session request does not contain editable data -> after reload, selected value is gone again.

**Comment by fashxp** [comment]
probably related to #8420?

**Comment by brusch** [comment]
Seems to be caused by ExtJS 7 #7824 
The `select` event on select components is fired twice, right on selecting an item and on blur.
