### ISSUE TITLE
Formatter Class for one to many relation

### ISSUE THREAD

**Issue by mauveine** [pimcore/pimcore#8432]
# Bug Report

### Expected behavior
When setting a class for Formater Class for one-to-many relation attribute, the reference field should be filled with the return values from the respective class.

### Actual behavior
The before mentioned class only works for many-to-many relationship.

### Steps to reproduce

1. Create a class that implements Pimcore\Model\DataObject\ClassDefinition\PathFormatterInterface
2. Set it in the admin panel, inside the field definition, under the Formatter Service / Class
3. Refresh object to check the changes

### Code example
```php
class TheFormatter implements PathFormatterInterface
{
    public function formatPath (array $result, ElementInterface $source, array $targets, array $params): array {
        /** @var Data $fd */
        $fd = $params["fd"];
        $context = $params["context"];
        foreach ($targets as $key => $item) {
            if ($item["type"] === "object") {
                $targetObject = Concrete::getById($item["id"]);
                if ($targetObject instanceof Color) {
                    $newPath = $targetObject->getName();
                    $result[$key]= $newPath;
                }
            }
        }

        return $result;
    }
}
```

Reference doc: https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Class_Settings/Path_Formatter.html

**Comment by MarcoGuiducci** [comment]
I've got the same error. If I convert the field to a Many-to-Many field relation, everything works as expected, but for the Many-to-One relation this function is not even called

**Comment by weisswurstkanone** [comment]
Mhm, unable to reproduce on latest 6.8

**Comment by mauveine** [comment]
In 6.8.4 didn't work. Updated to 6.8.12 and it works well.
Closing the issue
