### ISSUE TITLE
[Documents] Uncaught TypeError: Cannot read property 'wysiwyg' of undefined when try to use "pimcore.document.editables.wysiwyg"

### ISSUE THREAD

**Issue by pdchaudhary** [pimcore/pimcore#8433]
# Bug Report
Getting Uncaught TypeError: Cannot read property 'wysiwyg' of undefined when try to use "pimcore.document.editables.wysiwyg.defaultEditorConfig" for setting global Configuration for document wysiwyg editor

I added below code snippet in pimcoreReady but getting above js error.
`pimcore.document.editables.wysiwyg.defaultEditorConfig.uiColor = '#AADC6E';`

### Expected behavior
1. Editor uiColor changed 
### Actual behavior
2. Getting js error (Nothing Happen)
### Steps to reproduce
1. created startup.js file
2. In that, I  added `pimcore.document.editables.wysiwyg.defaultEditorConfig.uiColor = '#AADC6E';` code on pimcoreReady function
3. Installed Asset
### Code example
```
//startup.js
pimcoreReady: function (params, broker) {
    pimcore.document.editables.wysiwyg.defaultEditorConfig = pimcore.document.editables.wysiwyg.defaultEditorConfig || {};
    pimcore.document.editables.wysiwyg.defaultEditorConfig.uiColor = '#AADC6E';
}
```

**Comment by brusch** [comment]
You need to inject the script for the editmode, not for the normal admin UI.
See: https://github.com/pimcore/pimcore/blob/2f18a0f26380c56b609d937b40d2050c8d1a3e1a/lib/Extension/Bundle/PimcoreBundleInterface.php#L87

**Comment by pdchaudhary** [comment]
Thanks @brusch
