### ISSUE TITLE
Delete dialog: show key of element

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#844]
Actually deleting a document/asset/object bring only a generic popin: "Do you really want to delete this element". It is prone to human error.

As improvement, like deleting a file on windows desktop for instance, it could at least say the element name in the message so mistake can be prevented. It could be: "Do you really want to delete this element: cum-sociis-natoque-penatibus-et-magnis". (so we can keep actual translations)

Here is a screenshot of actual message:
![message](https://cloud.githubusercontent.com/assets/9025839/18178474/bedd5f46-707e-11e6-8a10-5153b22c0b8b.png)

**Comment by brusch** [comment]
See: #847 - needs discussion
