### ISSUE TITLE
500 Internal Server Error on Versions tab for calculated localized field

### ISSUE THREAD

**Issue by moiashvin** [pimcore/pimcore#8465]
# Bug Report

### Expected behavior
Display of details in Version tab correctly (including localized calculated fields)

### Actual behavior
Selecting Version tab where there is calculated localized field displays
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 

### Steps to reproduce

Steps to reproduce:
(1) Open a Product - e.g. /Product Data/Accessories/rims/alfa romeo-1900-rims-simple
(Here the Versions tab is empty)

(2) Do a Save and Publish to save new version of product.
(Here, a new Version is created and listed in Versions tab)

(3) Select the Version. On field Fullname (en) in the table, the Value is:
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

### Code example
```php
// your code
```

# Feature Request

**Comment by weisswurstkanone** [comment]
fixed via #8475
