### ISSUE TITLE
using the tab key while editing inline will cause javascript error

### ISSUE THREAD

**Issue by stormwind84** [pimcore/pimcore#8483]
# Bug Report

### Expected behavior
Using the tab key to inline edit in the "Search, Edit and Export" list.

### Actual behavior
Jumping from field to field with the tab key will produce a javascript error and freeze the interface.

### Steps to reproduce
In the PIM/MDM demo, open the first Cars element ("ac cars"), in the main tab "Search, Edit and Export" try to inline edit the first row, change the name, then press TAB KEY to jump to the next colum and change the color; now clicking again on the title column or elsewhere will generate a javascript error "Uncaught TypeError: e is null", which freeze everything and force the user to reload the entire page.

**Comment by brusch** [comment]
Duplicates #9079
