### ISSUE TITLE
[DataObject] Allow Geo data types in Classificationstore

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#8492]
# Feature Request
Since Geo data-types already implements marshal() & unmarshal() methods, it can be supported in classification store containers.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
