### ISSUE TITLE
[DataObject] WYSIWYG Element overlaps other fields placed above of it

### ISSUE THREAD

**Issue by gekoraus** [pimcore/pimcore#8496]
# Bug Report

If you add a Field Collection with a WYSIWYG Element to a Data Object (see image), the WYSIWYG Element overlaps other fields above them when a long text is entered.

![Field Collection Definition](https://user-images.githubusercontent.com/1663922/111492665-28ab4580-873d-11eb-8107-f6afd986ba65.png)

### Expected behavior

 Other fields can still be edited even if a long text is entered in the WYSIWYG

### Actual behavior

 Other fields can't be edited any more due to overlapping of the WYSIWYG. 

![Layout Issue](https://user-images.githubusercontent.com/1663922/111492747-395bbb80-873d-11eb-890a-ed35f789c04e.png)

After a reload or a tab switch the layout is fine again.

![After Reload](https://user-images.githubusercontent.com/1663922/111492796-45477d80-873d-11eb-9016-88761cdbcbda.png)

### Steps to reproduce

- Create a Field Collection with some Elements before the WYSIWYG Element

- Add it to a DataObject
- Add a long text into the WYSIWYG Element

This can also be reproduced on demo.pimcore.fun with the "Test" Field Collection in the News DataObject.

**Comment by brusch** [comment]
@dvesh3 please verify if this also happens in Pimcore 10, if not, please close 😊 Thanks!

**Comment by fashxp** [comment]
The thing is, that the wysiwyg field is not growing automatically but adding an additional scrollbar. 
But with scrolling you can still reach the other attributes...
