### ISSUE TITLE
[DataObjects] Encrypted fields with ownerawareinterface leads to recursion on save

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#8501]
# Bug Report
when saving an object with encrypted field having "_owner" property, it leads to recursion. see https://github.com/pimcore/pimcore/blob/fb48e8b95b53fa0cd8efa33de36bea01705210c5/models/DataObject/Data/EncryptedField.php#L104

**Comment by brusch** [comment]
Fixed by #8502
