### ISSUE TITLE
[Feature] Improving the asset tree

### ISSUE THREAD

**Issue by ChrisB9** [pimcore/pimcore#8508]
# Feature Request

## Current Situation

For Assets, it is only possible to add images underneath folders and not underneath other assets. This behavior is not consistent with the other too types: Objects and Documents. I can add a page underneath a page, creating a tree-like structure and the same goes for objects. Object A can be the parent of Object B. There is no folder limitation, except for assets.

## Feature description

I'd like to propose that assets should also be allowed to be nested (at least one level deep). This automatically gives the possibility to create features like image variations and enables the customer to have a clean DAM-experience. 
By doing that, the setParent() Method on Assets, Documents and Objects behave the same way and do not throw an exception if the given path is not a Folder that can be created.
The difficulty here is probably the physical folder representation within the asset folder. 
I imagine, we could solve that, by creating folders with the same name without extension and adding all the files in there

**Comment by brusch** [comment]
To be honest I don't like the idea. I don't see any advantage and it's alo not common practice (filesystems, ...).

**Comment by ChrisB9** [comment]
That's fair. Maybe the way I put the idea is also a little over-complicated for what I actually want to achieve.
In the end, all that is needed is a visual representation for image variants in the tree view. But image variants don't exist yet either even though the demand does exist there (as we have a customer specifically requiring that)

**Comment by brusch** [comment]
I'll close that for now, please feel free to continue the discussion, maybe also #7177 is a possibility to custom implement this?
