### ISSUE TITLE
Classificationsstore KeysConfig - GetByName should return list of keys or Key names should be unique.

### ISSUE THREAD

**Issue by rndfm** [pimcore/pimcore#8518]
### Expected behavior
As there could be keys with the same name. The function GetByName should return a list or Key names should be unique.

### Actual behavior
The first key with a matching name is returned. Even though it might be "deleted" (marked as not enabled in db)

### Steps to reproduce
Create two keys with identical names. 
Use keyconfig getByName function to get the keys.
Observe that only one of the keys is returned.

Maybe delete that key in pimcore backend.
Try getByName again.
Observe that the deleted key is still returned.

**Comment by brusch** [comment]
This needs to be a BC solution ...

**Comment by weisswurstkanone** [comment]
I would rather introduce an additional  getKeysByName method. wdyt?

**Comment by brusch** [comment]
Possibly the only way without breaking anything. 
Would be a topic then for `10.1` I'd say.

**Comment by weisswurstkanone** [comment]
Closing this for now. Will do this properly in Pimcore 11. See https://github.com/pimcore/pimcore/issues/9348
Deleted key configs should be cleaned up.
