### ISSUE TITLE
RFC: real-time two-way communication

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#8537]
# Feature Request

## Feature description

In #8374 a concept of queued jobs is introduced. This would allow all but the most important jobs to be delegated and done in an async way. Having done a few quite complex apps like this, the need to know when some jobs finish (to be able to update the UI, for example) introduces a requirement for the backed to talk back to the client.

A good choice for this is [Mercure](https://mercure.rocks/), which also comes with a [Symfony component](https://symfony.com/doc/current/mercure.html).

Having this available would mean:

- any current or newly introduced polling jobs (notifications, progress bars etc) can be replaced with Mercure
- it fits nicely into the queue concept, where async jobs send notifications they're done, allowing the app to react to it,
- it fits nicely into other concepts like GraphQL subscriptions, with GraphQL being the new direction Pimcore seems to be going
- it could probably be implemented cheaply, with replacing existing Ext.js stores with realtime stores powered by Mercure

**Comment by fashxp** [comment]
we will introduce that into studio.
