### ISSUE TITLE
[ClassDefinition] Can not delete field if marked as unique inside localizedfields

### ISSUE THREAD

**Issue by davidhoeck** [pimcore/pimcore#8538]
### Expected behavior
Delete column, click save and success message.

### Actual behavior
Delete column, click save an error message: Cannot drop column XYZ on table object_localized_data_X 

### Steps to reproduce

Create a localizedfield with for example a text input. Set the "unique" checkbox to checked and save. 
After that remove the text input inside the localized field and click save. The error message should appear.
If setting unique to false and saving the object again, removing is working fine. 

I think it is because the index still exists and there is a problem, when removing a column where an index is set on. 

### Code example
```shell
An exception occurred while executing 'ALTER TABLE `object_localized_data_2` DROP COLUMN `test`;': SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'test' doesn't exist in table
```

**Comment by dvesh3** [comment]
fixed by #9157
