### ISSUE TITLE
Flysystem for content files

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#8547]
https://github.com/thephpleague/flysystem-bundle

A storage for each purpose: 
- assets
- image thumbnails
- video thumbnails
- document thumbnails
- document files
- email
- recyclebin
- application logger

- private temp
- public temp

**Comment by dpfaffenbauer** [comment]
Basically: https://github.com/pimcore/pimcore/issues/8531

**Comment by Cruiser13** [comment]
I love this approach as we're using Flysystem quite often. I do suggest using Flysystem v2 even though some adapters are not ready yet.

**Comment by brusch** [comment]
Yes, v2

**Comment by dkarlovi** [comment]
I've done Azure Blob Storage adapter for Gaufrette, don't see why not do it for Flysystem, since Pimcore is hopefully moving there. :+1:
