### ISSUE TITLE
Sorting by path in grid broken

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#8557]
# Bug Report

### Expected behavior

Sorting by *Path* in the children grid should sort (naively at least).

### Actual behavior

Sorting seems random:

![image](https://user-images.githubusercontent.com/279826/112191275-2433d080-8c06-11eb-8e75-6d685705e6ed.png)

### Steps to reproduce

See also #3618

**Comment by brusch** [comment]
fixed by #8602
