### ISSUE TITLE
Save and share column configurations between Pimcore users

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#857]
# Feature Request

Save and share column configurations between Pimcore users
## Feature description

In the "Search, Edit and Export" view (Pimcore backend object tree) it is possible to modify and save the column configuration.

A helpful extension would be to 
a) also save modifications regarding the width of various columns (e.g. column "path" extended / collapsed), or at least collapse all columns if there is sufficient space within the browser window, and
b) make it possible to share column configurations between users to make them reusable. This feature could be integrated within the Pimcore permission system.

**Comment by Yivan** [comment]
Great idea, because first time user connect, there is only system colomns. I think to non-technical people which sometimes we give ultra-restricted permission to access to one folder object listing. They connect have only one directory, so easy, but when they click on it they have just system (technical for them) columns.

But maybe a more simple way would be at least to have a "Set as default configuration button" only available to administrator with full privilege.
This default configuration will be use instead of nothing when a user has no custom column configuration.

**Comment by cleggypdc** [comment]
@brusch I thought the feature of saving the column configurations of a folder was already in? If so then this does no longer work (tested on demo site in latest build)

FYI remember that a default column configuration can be set in the class builder by specifying each field's grid and search visibility. If you need to change the default columns per user role or group, then this can also be achieved through custom class layouts.

![image](https://cloud.githubusercontent.com/assets/1098498/18322089/d0aec53a-7528-11e6-8956-a563d31e9b69.png)


At the folder level, I can also see this being useful! Perhaps it could be achieved via a tweak to the code and then an adjustment to the psfs i.e.

1. Creating the folder layout needed and saving it (thus creating the config file for that user in var/config/object/grid/FOLDERID-user_USERID.psf
2. Creating a role that you want that layout to apply to
3. Renaming the configuration file to the ID of the user role.

Cheers!
Paul

**Comment by brusch** [comment]
@cleggypdc saving the column configuration still works, but there was a change on how this is done. 
After changing the column configuration a button appears next to the configuration button, press it to save it :) 

![image](https://cloud.githubusercontent.com/assets/142037/19684309/cd530a3c-9ab6-11e6-97ab-dd278fc20e88.png)

And yes, there's the default configuration in the class definition, so the question is if this feature is really necessary.

**Comment by fashxp** [comment]
actually the feature of saving and sharing column configurations would be quite handy. 

Sample usecase: 
I have different folders for pimcore objects and I need to do some tasks on them (e.g. task 1 = check if certain attributes are filled, task 2 = change other attributes of objects). 

For each of these two tasks I would need a grid displaying different attributes. And each of these tasks I need to execute on different pimcore folders. 
Right now, I have to reconfigure the grid columns from scratch each time. It would be a shortcut if I can select from predefined grid columns.

**Comment by Yivan** [comment]
@cleggypdc : thanks yes i forgotten those feature : )

**Comment by weisswurstkanone** [comment]
see https://github.com/pimcore/pimcore/issues/2074
