### ISSUE TITLE
UrlSlug broken in Classification store

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#8586]
UrlSlug does not implement ResourcePersistenceAwareInterface

see https://github.com/pimcore/pimcore/blob/1bf4518a42e4b33c31f6ab0203ac575db39e7c79/models/DataObject/Classificationstore.php#L203

**Comment by weisswurstkanone** [comment]
@dvesh3 can we use the EqualComparisonInterface instead/as a fallback ?

**Comment by weisswurstkanone** [comment]
as well as here
https://github.com/pimcore/pimcore/blob/e9ad0529839a5d5c5ceba55bb36248a917d8996d/models/DataObject/ClassDefinition/Data/Classificationstore.php#L439

**Comment by dvesh3** [comment]
seems like it is not suppose to work in classificationstore. please see: https://github.com/pimcore/pimcore/blob/f473c2ec3779c961f7e551abeefb761bc488d38e/bundles/InstallBundle/Resources/install.sql#L982-L988

**Comment by dvesh3** [comment]
Fixed by #8591
