### ISSUE TITLE
dropClass of pimcore_image expects unique class

### ISSUE THREAD

**Issue by patric-eberle** [pimcore/pimcore#8590]
# Feature Request
- [x] There is no existing issue regarding the same topic
## Feature description
`pimcore_image` allows to extend the drop area with `dropClass`. See https://pimcore.com/docs/pimcore/current/Development_Documentation/Documents/Editables/Image.html

Unfortunately this only works if the component is only placed once on the page. If multiple instances are created, the `dropClass` will always assign the image to the first instance. I can work around this by creating a unique class by concatenating various `info` values, but it's buggy.

This could be improved by limiting the search scope of the related script to the current brick (e.g. by adding `[data-name="<id>"] <dropClass>` to the query selector.

**Comment by NiklasBr** [comment]
A workaround could be to append a random number to the dropclass:

```twig
{% set = "someclass_" ~ random(1000000, 9999999) %}
{{ pimcore_image("image",{
    "thumbnail": "contentfullimage",
    "dropClass": drpCls 
}) }}
```

**Comment by brusch** [comment]
@patric-eberle Agree. A PR for that would be very nice! 😊

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
