### ISSUE TITLE
2FA route on HTPS points to HTTP

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#8592]
# Bug Report

### Expected behavior

The 2FA form uses HTTPS same as everything else.

### Actual behavior

The 2FA form points to HTTP even though the app is hosted on HTTPS.

### Steps to reproduce

1. deploy the app to HTTPS
2. create the user with 2FA enabled
3. try to login
4. login form passes OK, 2FA form shows up
5. 2FA form points to HTTP
6. browser issues a warning

### Code example
```html
<form method="post" action="http://example.com/admin/login/2fa-verify">
    <input name="_auth_code" id="_auth_code" autocomplete="one-time-code" type="password" placeholder="Code" required="" autofocus="">
    <input type="hidden" name="csrfToken" value="eec3c5309687d5acff7040a9a78f5cef12ad1086">

    <button type="submit">Login</button>
</form>
```

**Comment by brusch** [comment]
Not able to reproduce. 
You're probably behind a reverse-proxy and haven't configured that properly (Symfony trusted proxy).

**Comment by dkarlovi** [comment]
@brusch why would just the 2FA form exhibit this behavior then? The login form and everything else works as expected.

**Comment by brusch** [comment]
there's no special behavior for the 2FA form ... see 
https://github.com/pimcore/pimcore/blob/9af9958fbcfb9e86406f8076212196a52b831b81/bundles/AdminBundle/Resources/views/Admin/Login/twoFactorAuthentication.html.twig#L14

**Comment by dkarlovi** [comment]
Oh, I see the reason. All other forms use paths (no hostname), not URLs.

```html
<div id="loginform">
    <form id="form-element" method="post" action="/admin/login/login?perspective=" style="opacity: 1;">

        
        <input type="text" name="username" autocomplete="username" placeholder="Username" required="" autofocus="">
        <input type="password" name="password" autocomplete="current-password" placeholder="Password" required="">
        <input type="hidden" name="csrfToken" id="csrfToken" value="a3e18ed98609af828df51480947c6d9aa1889cfa">

        <button type="submit">Login</button>
    </form>

    <a href="/admin/login/lostpassword" class="lostpassword">Forgot your password?</a>
</div>
```

**Comment by dkarlovi** [comment]
You're right, the proxy was misconfigured :+1:  but this does seem like something which could be fixed either way, the default behavior isn't the best, security wise.

**Comment by dkarlovi** [comment]
For reference of anyone finding this issue in the future, I did this:
```patch
diff --git a/web/app.php b/web/app.php
index 2de934c..ffd667c 100644
--- a/web/app.php
+++ b/web/app.php
@@ -20,6 +20,11 @@ include __DIR__ . "/../vendor/autoload.php";
 \Pimcore\Bootstrap::setProjectRoot();
 \Pimcore\Bootstrap::bootstrap();
 
+Request::setTrustedProxies(
+    ['127.0.0.1', 'REMOTE_ADDR'],
+    Request::HEADER_X_FORWARDED_FOR
+);
+
 $request = Request::createFromGlobals();
 ```
