### ISSUE TITLE
pimcore_image() attributes ignored

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#8600]
# Bug Report

### Expected behavior

Pass attributes to `pimcore_image()` or `image.thumbnail('size').html({})` in twig as described in https://pimcore.com/docs/pimcore/master/Development_Documentation/Documents/Editables/Image.html#page_An-Example-Using-Custom-Attributes.

### Actual behavior

Passed attributes are not present in the html output.

### Steps to reproduce

Create an image editable with attributes:

```
{{ pimcore_image('image', {
    thumbnail: image_size,
    attributes: {
        'custom-attr': 'value',
        'data-role': 'image',
    }
}) }}
```

Or directly output the image thumbnail:

```
{{ image.thumbnail(image_size).html({
    'class': 'my-class',
    'data-test': '123',
}) }}
```

Version: dev-master|1ba3830f59c407400f99aa21d3cb56db816775da

**Comment by dvesh3** [comment]
@valentin- you should pass `imgAttributes` or `pictureAttributes` to thumbnail html() please see https://pimcore.com/docs/pimcore/master/Development_Documentation/Assets/Working_with_Thumbnails/Image_Thumbnails.html#page_Advanced-Examples
