### ISSUE TITLE
Pimcore 6.8 is incompatible with doctrine/dbal 2.13.0

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#8610]
# Bug Report
doctrine/dbal published Version 2.13.0 an hour ago. But I get errors.

For example:
`php bin/console pimcore:deployment:classes-rebuild -n -c -d -v`

```
In Doctrine.php line 216:
                                                                                                               
  [Symfony\Component\Debug\Exception\UndefinedMethodException]                                                 
  Attempted to call an undefined method named "execute" of class "Doctrine\DBAL\ForwardCompatibility\Result".  
                                                                                                               

Exception trace:
  at /var/www/html/vendor/pimcore/pimcore/lib/Cache/Pool/Doctrine.php:216
```

**Comment by brusch** [comment]
Probably best to just set it to conflict. 
Maybe also something that Doctrine needs to fix -> SemVer?

**Comment by Se7en-IT** [comment]
Same issue.

**Comment by brusch** [comment]
Fixed by #8611

**Comment by fracsi** [comment]
I think the failing line is a remnant of a refactoring commit: dd600a23b795c0d4274274d8b9e6b65c6970c990
Through the [`executeQuery`](https://github.com/doctrine/dbal/blob/5339362c8f6e80d884d6aea64bd199d8b4ec5a9f/lib/Doctrine/DBAL/Connection.php#L1242) method, the statement is prepared and executed, the return value is the result. But the code calls `execute` on it again, thus failing.

**Comment by fracsi** [comment]
@brusch I still think there can be a much better fix: eg. check the `rowCount` on the executed query in the if statement.
In the current implementation the SQL query is executed in the `executeQuery` method, which returns the Statement in `doctrine/dbal:2.12.*` and a Result object (which is for forward compatibility) in `doctrine/dbal:2.13`.
But right after execution, the current code **executes the query again**, which fails with the upgraded doctrine/dbal.
The second **execute** call is a remnant, which caused no trouble until now, and totally unnecessary.
https://github.com/pimcore/pimcore/blob/e980e3f3d29afebe3aba2300db47c9a67cca3715/lib/Cache/Pool/Doctrine.php#L209-L217

A simple solution could be - (this can be also further simplified)
```php
$stmt = $this->db->executeQuery($insertQuery, [
    'id' => $item->getKey(),
    'data' => $this->serializeData($item->get()),
    'expire' => $item->getExpiry(),
    'mtime' => time(),
]);

$result = $stmt->rowCount();
if (!$result) {
```

**Comment by brusch** [comment]
@fracsi Yes, this is was I've tried already, but there are a couple of more things, especially regarding PhpDoc that needs to be changed. PRs are welcome 👍😊

**Comment by fracsi** [comment]
@brusch Then maybe we should create another issue for 6.9 to fix this. Not to forget it ;)

**Comment by brusch** [comment]
@fracsi for now this has no priority for us, as our focus is now on `10`, but like I said, we're happy to merge PRs for that. 😉
