### ISSUE TITLE
[Ecommerce] Invalid VoucherTokenInformationDetails for cart vs. product context

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#8636]
# Bug Report

**Issue**
The `getPricingManagerTokenInformationDetails` method in the `VoucherServiceInfercae` returns pricing rules, which contain a vouchercondition for tokens, but where not applied due to other failing conditions in the same rule. This logic is based on the `getAppliedPricingRules` method of the `CartPriceCalculator`, which does not distinguish between applied rules on cart or products. This is problematic in some cases.

**Example**
I.e. if I have products with regular and sales-prices in my shop. Then I create a rule with a birthday vouchertoken which should apply a 10% discount on the cart, but only if there are no products with sales prices in the cart.

In this case the rule would be considered as `applied` (`getNotAppliedRules()` in `VoucherTokenInformation` is empty) as soon as any none-sale product is in the cart. The token does not result in any action, because only a cart-action is configured, even though it is considered applied.

**Possible solutions**
1. I gues the simplest solution would be to add a context to the `getAppliedPricingRules()` method, so you can decide if you want to check for cart or product actions.
2. An even better approach could be to check the applied actions of a rule automatically, it would be necesry to add a method to identify in which context(s) an action gets applied to the `ActionInterface`.

What do you think?

**Comment by fashxp** [comment]
fixed via https://github.com/pimcore/pimcore/issues/8647
