### ISSUE TITLE
Fix warning for pimcore_video() output without poster image

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#8648]
# Bug Report

There is a warning when using videos without poster images.

![image](https://user-images.githubusercontent.com/90033/113390251-a3a56a80-9391-11eb-97b1-b08b2fb11397.png)

Add a check to `ImageThumbnailTrait.php` to prevent the warning.

![image](https://user-images.githubusercontent.com/90033/113390373-e0716180-9391-11eb-871d-4c72377459d5.png)

**Comment by brusch** [comment]
@valentin- Unfortunately I wasn't able to reproduce this issue. Can you please share exactly how to trigger this warning ( preferrable on our public demo)? Thanks!

**Comment by valentin-** [comment]
@brusch I can't reproduce it anymore - closing the issue.
