### ISSUE TITLE
Batch assignment of localized checkboxes in gridview does not work

### ISSUE THREAD

**Issue by simongavelin** [pimcore/pimcore#867]
Hi,
The batch assignment of localized checkboxes in the gridview does not seem to work as intended.
When I perform a batch assignment, the grid reloads and the checkboxes remain unchecked.

Note that this is only for localized checkboxes.

To reproduce in demo environment (see attach image):
- Open demo.pimcore.org/admin (admin/demo)
- Open the class editor and select "news"
- Add a checkbox to the localized values (name it whatever). Save class.
- Click the news folder and add the new value to the grid
- Batch assign the checkbox
- The checkbox remains unchecked

![pimcore localized checkbox batch assign](https://cloud.githubusercontent.com/assets/4134531/18631273/4e0c0c12-7e71-11e6-8e8d-b5c6d6020718.jpg)

**Comment by mrudnicki** [comment]
Thanks @simongavelin 
That's right - it seems that localized checkbox doesn't work with the batch assignment.
I will look at it, Tomorrow.
