### ISSUE TITLE
6.9 breaks sorting Shared Translations by language

### ISSUE THREAD

**Issue by limenet** [pimcore/pimcore#8698]
# Bug Report

### Expected behavior

1. Open Shared Translations
2. Click on language column header
3. Translations are sorted by that column

### Actual behavior

1. Open Shared Translations
2. Click on language column header
3. SQL error due to erroneous JOIN

The query executed in `\Pimcore\Bundle\AdminBundle\Controller\Admin\TranslationController::translationsAction` is:

```sql
SELECT translations_messages.key, text AS de
FROM translations_messages
LEFT JOIN de de ON (de.key = translations_messages.key and de.language = 'de')
GROUP BY translations_messages.key ORDER BY `de` ASC
LIMIT 25
```

The changes were introduced by #7954 and the relevant lines are https://github.com/pimcore/pimcore/blob/6.9/bundles/AdminBundle/Controller/Admin/TranslationController.php#L526-L535

### Steps to reproduce

- Install `pimcore/skeleton` in version 2.8.16 (latest) and perform above steps
- Go to https://demo.pimcore.fun/admin/ and perform above steps

### Code example

A possible, although ugly, fix is the following:

```diff
diff --git a/bundles/AdminBundle/Controller/Admin/TranslationController.php b/bundles/AdminBundle/Controller/Admin/TranslationController.php
index 8e35e17b81..93ecec7ee9 100644
--- a/bundles/AdminBundle/Controller/Admin/TranslationController.php
+++ b/bundles/AdminBundle/Controller/Admin/TranslationController.php
@@ -523,10 +523,10 @@ class TranslationController extends AdminController
                         }
                         $alreadyJoined[$fieldname] = 1;

-                        $select->addSelect('text AS ' . $fieldname);
+                        $select->addSelect($tableName . '.text AS ' . $fieldname);
                         $select->leftJoin(
                             $tableName,
-                            $fieldname,
+                            $tableName . ' AS',
                             $fieldname,
                             '('
                             . $fieldname . '.key = ' . $tableName . '.key'
```

Unfortunately, I wasn't able to come up with a cleaner fix, not least because I don't understand the need for a JOIN when sorting by a column.

**Comment by dvesh3** [comment]
Fixed by #8703
