### ISSUE TITLE
Multihref with metadata throws error when actually linking an object

### ISSUE THREAD

**Issue by Sunohara666** [pimcore/pimcore#871]
### Expected behavior 

link is created
  
### Actual behavior  
  
error is thrown: 
![screen shot 2016-09-23 at 9 21 14 am](https://cloud.githubusercontent.com/assets/20945873/18777422/5f115bb0-816f-11e6-87a9-0975cf8740e9.png)

### Steps to reproduce  
goto demo.pimcore.org/admin
create a new object of type "test2"
in the multi-href field called "attachments", link it to the object called "/testing/yes-yes"
save & publish --> error

**Comment by cleggypdc** [comment]
@Sunohara666 did you use the "Search" button to find the object?

I can reproduce this if you check "Allow objects" in the class editor, but do not select anything. The default behaviour should allow all Classes - it appears it is this functionality which has been reversed

![image](https://cloud.githubusercontent.com/assets/1098498/18781920/c9bee76e-817b-11e6-9435-259585f297c6.png)

**Comment by Sunohara666** [comment]
@cleggypdc affirmative. i wanted to allow any type of object,document or asset, as you can see by my class definition of test2 on demo.pimcore. i also used search object to find the object.

**Comment by Sunohara666** [comment]
@cleggypdc i see the db has reset - let me know if you want me to re-create the situation

**Comment by weisswurstkanone** [comment]
fixed ib build 3971
