### ISSUE TITLE
Credis socket read error

### ISSUE THREAD

**Issue by pfaffenrodt** [pimcore/pimcore#8716]
# Bug Report

Credis produces an read socket error that timeout after 300 seconds.
With nativ phpredis it has no issues to read or write from redis server.

In an AWS env to redis node in elasticache with tls and pw

### Expected behavior
redis cache working
### Actual behavior
timeout / read socket error

### Steps to reproduce
* run code example in aws environment with phpredis 5.3.X

### Code example
```php
<?

$host = "tls://redishost"
$pw = "secret"

echo "connect to $host with pw: $pw";

$redis = new \Redis();
echo 'nativ connected'.$redis->connect($host, 6379, 3). "\n";
echo 'nativ auth'.$redis->auth($pw). "\n";

$redis->set("randomVariable", "Value X!");
echo "Stored string in redis:: " .$redis->get("randomVariable");
echo "\n";


include './vendor/autoload.php';
$redis = new Credis_Client(
    $host,
    6379,
    50,
    '',
    0,
    $pw
);

echo "READ with Credis " .$redis->get("randomVariable");
echo "\n";

```

# Feature Request
- [ ] replace credis with nativ phpredis or predis

## Feature description
I would suggest to replace credis, because it is not mantained properly.

**Comment by brusch** [comment]
That's not a Pimcore issue. 
Pimcore X switched to Symfony Cache, therefore obsolete anyway.
