### ISSUE TITLE
Renaming attributes in Pimcore class ( Columns are getting deleted and creating new columns in database \)

### ISSUE THREAD

**Issue by KailaJayapalreddy** [pimcore/pimcore#872]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [yes ] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [yes ] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [ yes] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [yes ] There's no existing ticket for the same issue

### Expected behavior 
Database column names should alter when we are renaming attributes in pimcore classes.
### Actual behavior  
When we are renaming attributes it is creating new column instead of altering existed column. and existed columns will be replaced by new columns. so data will be lost.
### Steps to reproduce  
Go to pimcore class 
create new class, and add some attributes and create few objects with valid data.
again go to pimcore class 
change attribute name and save the class again
And check the objects data ... thats all empty 
### Code example 
```php
// your code
```

# Feature Request 
## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [ ] There is no existing issue regarding the same topic

**Comment by cleggypdc** [comment]
see https://github.com/pimcore/pimcore/issues/798

**Comment by KailaJayapalreddy** [comment]
thank you
