### ISSUE TITLE
Data Objects won't get migrated on deploy

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#8725]
# Bug Report

### Expected behavior

Add data objects in the local dev environment and check them in. Create the objects (backend) in the staging environment on deploy using `pimcore:deployment:classes-rebuild`.

### Actual behavior

The data objects are not available in the staging environment.

### Steps to reproduce

Create data object -> classes in the local environment
Version control the necessary files
Deploy the changes
run `pimcore:deployment:classes-rebuild`

Pimcore version: dev-master|6a50a9dd9c3ec112ff4ef816e21d084164b87dcf

**Comment by brusch** [comment]
You're talking about class definitions and not actual data-objects right?

**Comment by blankse** [comment]
@valentin-  Do you use `pimcore:deployment:classes-rebuild -c`?
Only with -c it create new class definitions.

**Comment by valentin-** [comment]
@blankse thanks, I wasn't aware of the options, working fine!
