### ISSUE TITLE
Symfony translation files not imported in Shared Translations

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#8733]
# Bug Report

### Expected behavior

Import symfony translation files into Shared Translations.

### Actual behavior

Added translation are not available in Shared Translations.

### Steps to reproduce

Create a translation file (messages.de.yml/messages.en.yml) in /translations
Add test translations
Open Tools -> Translations -> Shared Translations
No translations are added

A few minor versions ago the translations (without values) have been imported. According to the docs, the translation should get imported if the key doesn't exist in the system or the translation is still empty.
https://pimcore.com/docs/pimcore/master/Development_Documentation/Multi_Language_i18n/Shared_Translations.html

Pimcore version: dev-master|0c8b8e9ddc97dd5107a0a4f082857da2e651151c

**Comment by dvesh3** [comment]
I believe this is not a valid case because shared translations are stored in database and importing these translations from yaml files will conflict as what will be the master for storage when changing it on UI. 

I would say these are two separate possibilities to store translations and shouldn't be merged in any case.

**Comment by valentin-** [comment]
Hi @dvesh3, I'd like to dig into this issue once more.

Currently translations used in yaml files will automatically get added to shared translations when required in a template, but only if there is no value.

Example:
I've added two translations to `messages.de.yml`

![image](https://user-images.githubusercontent.com/90033/122542781-5c8f5300-d02b-11eb-9390-094cd935a8fd.png)

And use both of them as simple demo in `layout.html.twig`
![image](https://user-images.githubusercontent.com/90033/122543026-a11aee80-d02b-11eb-89e1-4557fb6bfc6a.png)

Now when opening shared translations in the backend searching for those keys, only `test_translation_1` shows up, because no value is given for this item:
![image](https://user-images.githubusercontent.com/90033/122542941-8d6f8800-d02b-11eb-8968-c4b1fc48ca2a.png)

It would be really convenient if translations **with a value** are also getting added to shared translations if the keys don't exist in shared translations yet.

In my opinion there is already a relation between translation files and shared translations and it would make more sense if translations in yml files are treated equally - no matter if there is a value or no value.

So there shouldn't be a separate import task to provide this functionality - but it would be awesome if the current behaviour get adjusted to solve the described issue.

Does this make more sense to you?
