### ISSUE TITLE
[Quantity Values] Sort by base unit instead of name of specific unit

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#8734]
# Feature Request

Current Quantity Values seem to be sorted alphabetically, this makes sense in most context and is a sensible default. But with quantity values this is less intuitive because related measurements are spread across a spectrum rather than grouped together in a way that makes semantic sense.

Very few people are going to mix millimeters and milliliters and Mega-Ohm in the same input fields. But they are grouped together thanks to the sorting.

![image](https://user-images.githubusercontent.com/279826/114152667-d6fe7100-991e-11eb-8d35-51afc040df25.png)

I suggest the default sorting is based on base unit rather than specific unit.

I can try to make a PR if it is interesting.

**Comment by NiklasBr** [comment]
Examples of how it could be sorted:
![image](https://user-images.githubusercontent.com/279826/114171886-37001200-9935-11eb-9fda-35107b91955f.png)

![image](https://user-images.githubusercontent.com/279826/114172051-6dd62800-9935-11eb-9d5c-53d130e50204.png)

**Comment by weisswurstkanone** [comment]
Just a thought ... maybe introduce some sort of grouping (distance, weight, volume, etc.)

**Comment by NiklasBr** [comment]
Yes, that would be a nice addition. Maybe include something like [marfurt/measurements](https://github.com/marfurt/measurements) which has support for Measurement Subclasses to group by.

This change can be done quickly though, it seems I only need to change a few `QuantityValue\Unit\Listing` sort arguments.

**Comment by weisswurstkanone** [comment]
I can imagine something like a tree. But this would be overkill I guess

**Comment by NiklasBr** [comment]
True. That's an easier change.

**Comment by brusch** [comment]
Sounds very nice, a PR would be highly appreciated. 😊

**Comment by weisswurstkanone** [comment]
@NiklasBr 🏓
