### ISSUE TITLE
Few issues with Many-To-Many Object Relation in Grid View

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#8749]
When using Many-To-Many Object Relation there are some issues in the grid view with this type:

When you select only Name as visible field in the settings you still see full path instead of name.

Also this column is not sortable/filterable and for this reason pretty useless to work with in Grid view. Also the list is not alphabetically:

![image](https://user-images.githubusercontent.com/41229269/114346881-68125980-9b64-11eb-9f96-9cc9a0f9d665.png)

Can this be changed?

**Comment by Hbitvof** [comment]
Since the latest version it's sorting good. Is it possible to fix the other issues?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
