### ISSUE TITLE
CSV Mime/Type for Custom Report Download

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#875]
Maybe this is intentional, but it seems mime-type for CSV is set to text/plain.
Exemple in pimcore\modules\reports\controllers\CustomReportController.php, line 274, we have:

```
header("Content-type: text/plain");
header("Content-Length: " . filesize($exportFile));
header("Content-Disposition: attachment; filename=\"export.csv\""); while (@ob_end_flush());
```
It should be "text/csv" ? (so we can open it directly in Excel for instance, because with text/plain notepad want to open it on Windows ; ) )

I didn't go through all the pimcore file, but maybe same thing is at another places.

Thanks.

**Comment by brusch** [comment]
Thanks! 
All the others are fine so far: 
https://github.com/pimcore/pimcore/blob/3f4291644956a8445e2c5f963ffce4120b50e5af/pimcore/modules/admin/controllers/ObjectHelperController.php#L681-L681
https://github.com/pimcore/pimcore/blob/b6e480f004b7c39f023274be53702492a7d514f2/pimcore/modules/admin/controllers/TranslationController.php#L186-L186
