### ISSUE TITLE
Create document translations using Document Language Overview

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#8762]
# Bug Report

An error occurs when trying to translate Documents with **type Link**, works fine for Page Documents.

![image](https://user-images.githubusercontent.com/90033/114386570-af630f00-9b91-11eb-83a2-0bd0331b6013.png)

Pimcore version: dev-master|20f5ba791dccfb82127e387df7173795f780beae

**Comment by dvesh3** [comment]
Also reproducible on 6.9
