### ISSUE TITLE
Error when delete objects with bricks with calculatedValue field

### ISSUE THREAD

**Issue by woellundwoell** [pimcore/pimcore#877]
# Bug Report

### Expected behavior

Delete object "as usual"
  
### Actual behavior  

Throw error " Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column [name of calculatedValue field] in 'field list'
  
### Steps to reproduce  

1. Create an object with brick field
2. Create an object brick with a calculatedValue field
3. Adding the according class definition to the brick
4. Create the according calculation class and function compute() for the field
5. Add an object in the object tree
6. Save the object
7. Try to delete the object (and see js console)
  
Find the attached video of reproducing the bug on the pimcore demo system.

### Hints

If the compute() function returns not null, it will cause an insert of not null value in the "object_brick_query_" tables. Cause of this the field will be checked as "normal" value field in \Pimcore\Model\Object\Objectbrick\Data\Dao line 241
` $this->inheritanceHelper->addFieldToCheck($key, $fd);`
Afterwards the field will be part of the SQL-Query on the "object_brick_store_" tables. For a calculatedValue field the column is not there - as expected ;)
I don't know pimcore in that deep, but possibly a fix could be that a calcualtedValue classDefinition would be ignored at this place. When I change the code like that it works for me.

[pimcore_BugDemo.mp4.zip](https://github.com/pimcore/pimcore/files/491156/pimcore_BugDemo.mp4.zip)

**Comment by weisswurstkanone** [comment]
Sounds reasonable. Many thanks!
Build #3972

**Comment by woellundwoell** [comment]
Thanks a lot for that very quick fix ;)


a x e l  w o e l l  |  w o e l l . D E S I G N  |  a m  l a n g e n  r e c h  3 3  |  5 5 2 8 3  n i e r s t e i n  |  f o n  0 6 1 3 3 . 5 7 9 5 4 1  |  w w w . w o e l l d e s i g n . d e


Vertraulichkeitshinweis: Diese E-Mail und eventuelle Anlagen enthalten vertrauliche sowie der beruflichen Schweigepflicht unterliegende Informationen. Wenn Sie diese E-Mail irrtümlich erhalten haben, benachrichtigen Sie uns bitte durch direktes Beantworten dieser E-Mail und löschen Sie diese E-Mail inklusive beigefügter Dateien von Ihrem System. Vielen Dank!

Confidentiality Note: This e-mail, including any attachment, may contain confidential and privileged information. If you have received it by mistake, please notify us by reply e-mail and then delete this e-mail and any attached files from your computer system. Thank you!
