### ISSUE TITLE
Objects: Possibility to set `Input` and `Numeric` to unique

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#878]
Having the possibility to instruct the system to ensure for you that concrete field of concrete type of entities will have unique value is valuable feature. Please consider implementing that at least for basic field types such as numbers, text, href, etc.

One use case: importing nomenclatures from external system. In that case you should keep the external ID and you have to ensure that it will be unique, you will make a integer field and set it to be unique. Pimcore will ensure that you will not store duplicate external IDs. You can imagine same thing but that not importer but administrator had to add the external nomenclatures. If Pimcore implements unique check of values it will let the administrator know that it can not store duplicate value when he do so (by mistake if you want).

**Comment by nspacex** [comment]
+1

**Comment by alesak** [comment]
+1

**Comment by chix** [comment]
+1

**Comment by Yivan** [comment]
+1
I think it is in such common case of ecommerce for a sku for instance. Actually it is resolved by using postSave event and send back an error if duplicated, but having this feature at least on base field.
Having this feature on the most common field : input and number.

**Comment by dpfaffenbauer** [comment]
+1

Could also be done using the database UNIQUE constraint. I think this would be faster and would also work easily with object-bricks and fieldcollections.

**Comment by brusch** [comment]
Could be done using MySQL's `UNIQUE` constraint (which wasn't possible in earlier versions - before 3).

**Comment by manea-eugen** [comment]
+1

**Comment by Sunohara666** [comment]
+1 for a proper solution

**Comment by weisswurstkanone** [comment]
build 95

enable it via the 'unique' checkbox

**Comment by dpfaffenbauer** [comment]
@weisswurstkanone @brusch Is it possible to port this feature also for Pimcore 4?

**Comment by brusch** [comment]
@dpfaffenbauer Actually this isn't planned, no.

**Comment by dpfaffenbauer** [comment]
@brusch alright, then I'll just solve it using events. thanks anyway

**Comment by jbq** [comment]
I upgraded to version 5.0.1 and still can't see this new option.  Anything wrong?

**Comment by jbq** [comment]
The problem was on my side of course, please disregard my last comment, I missed the upgrade of the `web` folder containing the JS stuff.  Thanks for the neat feature!
