### ISSUE TITLE
[Documents] Version preview saves resaves version when you click on 'show'

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#8782]
![image](https://user-images.githubusercontent.com/6142086/114527678-8cdffd00-9c48-11eb-9bf7-09faafe21088.png)

    /**
     * @Route("/element/version-update", name="pimcore_admin_element_versionupdate", methods={"PUT"})
     *
     * @param Request $request
     *
     * @return JsonResponse
     */
    public function versionUpdateAction(Request $request)

**Comment by brusch** [comment]
Fixed by #8812
