### ISSUE TITLE
Now getting this error using pagination even demo ecommerce car lists.

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#8784]
Now getting this error using pagination even demo ecommerce car lists.

error is:
```
An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("categoryname", "category") to generate a URL for route "shop-category.en".").
```
in app/Resources/views/includes/pagination.html.twig (line 23)

I saw there was talk of updating using zendframework-bridge from laminas - was something changed that broke this in 6.9.1?

_Originally posted by @justbane in https://github.com/pimcore/pimcore/discussions/8779_

**Comment by brusch** [comment]
Fixed by https://github.com/pimcore/demo/commit/95c07abf7e959fcb4d3dca1063dcc7679a8cad2d
