### ISSUE TITLE
Predefined document custom icon

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#8798]
I've created a custom document type and want to set a custom icon using AdminStyle (https://pimcore.com/docs/pimcore/master/Development_Documentation/Tools_and_Features/Custom_Icons.html)

The icon isn't shown in the menu, neither for the document itself.

![image](https://user-images.githubusercontent.com/90033/114677663-d1cc6800-9d0a-11eb-8da2-39a588f0a63c.png)

![image](https://user-images.githubusercontent.com/90033/114677768-e9a3ec00-9d0a-11eb-98c9-bdf7df21cbed.png)

After changing the `Predefined document type` to `Project` manually and save it, the icon shows up correctly.

![image](https://user-images.githubusercontent.com/90033/114677910-07715100-9d0b-11eb-9222-653691de0947.png)

Aso soon as i reload the page, the icon is gone again.

![image](https://user-images.githubusercontent.com/90033/114678305-68992480-9d0b-11eb-9abd-e05f2206c84b.png)

Pimcore version: dev-master|d0c1422f69ecaba6c8198bf707963a661b4ad3d3

**Comment by brusch** [comment]
The predefined document type is not saved on the document, it's just there to fill the controller & template fields. 
Can you please share the code you're using?

**Comment by valentin-** [comment]
I only check the type and action:

![image](https://user-images.githubusercontent.com/90033/114685412-1d364480-9d12-11eb-9706-bd3f081615f1.png)

There is no condition in the style definition itself.

![image](https://user-images.githubusercontent.com/90033/114684580-54582600-9d11-11eb-9094-d9ebd3bf5453.png)

The icon is also applied when resaving the current state without setting the Predefined Document Type, but is gone after reloading the document:

![image](https://user-images.githubusercontent.com/90033/114684742-8073a700-9d11-11eb-889d-f1f08707b263.png)

**Comment by weisswurstkanone** [comment]
@valentin- , please try to override the elementIconClass like depicted here

```class ProjectDocumentStyle extends AdminStyle
{
    protected ElementInterface $element;

    public function __construct(ElementInterface $element)
    {
        parent::__construct($element);
        $this->element = $element;
        $this->elementIconClass = '';
        $this->elementIcon = '/bundles/pimcoreadmin/img/twemoji/1f697.svg';
    }
}
```

Seems that it has higher priority so you have to explicitely empty it because there is always a value in the base class.

**Comment by valentin-** [comment]
@weisswurstkanone thanks this worked!
