### ISSUE TITLE
Migration error, pimcore.settings_store doesn't exist 

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#8808]
# Bug Report

([original issue](https://github.com/pimcore/web2print-tools/issues/20)) When trying to install the latest version of the web2print-tools bundle with Composer and using Pimcore 6.9.1 I get the following error when running this command:

```sh
bin/console pimcore:migrations:migrate --set=pimcore_core
bin/console pimcore:bundle:install --no-cache-clear Web2PrintToolsBundle
```

```
[ERROR] An exception occurred while executing 'SELECT * FROM settings_store WHERE id = ? AND scope = ?' with params
["BUNDLE_INSTALLED__Web2PrintToolsBundle\\Web2PrintToolsBundle", "pimcore"]:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pimcore.settings_store' doesn't exist
```

It would be nice if all migrations ran automatically on Composer updates

**Comment by fashxp** [comment]
just tried that with a clean 6.9 skeleton installation. worked without any problems. 
`settings_store` is there, bundle can be enabled and installed. 

please check your installation ... `settings_store` table should be installed during [installation](https://github.com/pimcore/pimcore/blob/6.9/bundles/InstallBundle/Resources/install.sql#L581) or (when updating from 6.8) via [migration](https://github.com/pimcore/pimcore/blob/6.9/bundles/CoreBundle/Migrations/Version20210303165115.php#L16) - which gets executed automatically during composer update as it is a core migration.

**Comment by NiklasBr** [comment]
Table does not exist, but migration appears to have completed anyway:
![image](https://user-images.githubusercontent.com/279826/114829757-c0976000-9dcb-11eb-84b1-264ceefcb8a2.png)

**Comment by brusch** [comment]
Hmmm https://github.com/pimcore/pimcore/blob/1955a8f5b19f66b416ec249ec98d173e33ef1a52/bundles/CoreBundle/Migrations/Version20210303165115.php#L16 is pretty straight-forward, doesn't seem to be a Pimcore issue then, since the migration was marked as done by Doctrine 🤔
