### ISSUE TITLE
Ghostscript command line fails

### ISSUE THREAD

**Issue by D37R4C7** [pimcore/pimcore#8809]
@dvesh3 

Conversion typo...  You need to concat  '-r' and $resolution. Otherwise no document thumbnails get generated.

This way it works:
$process = new Process([self::getGhostscriptCli(), '-sDEVICE=pngalpha', '-dLastPage=' . $page, '-dTextAlphaBits=4', '-dGraphicsAlphaBits=4', '-r' . $resolution, '-o', $path, $this->path]);

This way it fails:
 $process = new Process([self::getGhostscriptCli(), '-sDEVICE=pngalpha', '-dLastPage=' . $page, '-dTextAlphaBits=4', '-dGraphicsAlphaBits=4', '-r', $resolution, '-o', $path, $this->path]);

https://github.com/pimcore/pimcore/blob/02c11060cfd4bc025f6c2db544124414d1fb5fe6/lib/Document/Adapter/Ghostscript.php#L215

**Comment by jdreesen** [comment]
Already fixed by #8804 in upcoming `v6.9.2` release.
