### ISSUE TITLE
Production environment installation guide?

### ISSUE THREAD

**Issue by rndfm** [pimcore/pimcore#8816]
Would be nice to have a guide/documentation for a recommended product environment setup.

Maybe we could share some insights, tips and tricks and I could put together a pull request for the documentation?

If it already exists and i missed it somehow. Please point me in the right direction.

**Comment by brusch** [comment]
A good start is definitely https://symfony.com/doc/current/deployment.html and https://symfony.com/doc/current/performance.html

I guess it's better to just direct at the Symfony docs if it's already covered there, but of course you should at least find a summary in the Pimcore docs.

**Comment by brusch** [comment]
A PR would be definitely nice, I think that also makes it easier to collaborate on this topic. 👍

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
