### ISSUE TITLE
App Configuration Best Practice

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#8824]
Since Version 4, symfony recommends to [not](https://symfony.com/doc/current/best_practices.html#don-t-create-any-bundle-to-organize-your-application-logic) create any bundle to organize application logic.

So in a modern structure, `AppBundle.php` should be avoided. 

## Issue
WIthout it, I'm not able to register my additional backend assets with these helper methods (available thrue `AbstractPimcoreBundle`):

- `getJsPaths`  
- `getCssPaths`
- `getEditmodeJsPaths`
- `getEditmodeCssPaths`

Creating a `AppBundle` file just to use these methods is not a good way to go IMO.

## Possible Solutions
- Add these methods to `Kernel.php`?
- Via configuration (`pimcore.static.js_paths`, `pimcore.static.css` for example, placed in `config.yaml`)?

What do you think?

**Comment by fashxp** [comment]
Why not use event listeners? https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/Plugin_Backend_UI.html

**Comment by solverat** [comment]
I completely missed that. Thanks!
