### ISSUE TITLE
Backend Branding broken in 6.9.2

### ISSUE THREAD

**Issue by mittererr** [pimcore/pimcore#8848]
Custom Logo and Custom background image are not shown after update to Pimcore 6.9.2.
The custom logo is shown as broken immediately after upload in system settings.

**Comment by NiklasBr** [comment]
Also noticed this, it appears the image is not showing in the Settings but appears to be still available on disk. In our case a SVG file.

![image](https://user-images.githubusercontent.com/279826/115555309-a66bef00-a2af-11eb-98a5-06051e8799fd.png)

**Comment by brusch** [comment]
I'm not able to reproduce this on https://demo.pimcore.fun/admin/ (admin/demo). 
Maybe it is specific to your setup?

**Comment by dvesh3** [comment]
@brusch I can reproduce it with SVG file.

**Comment by dvesh3** [comment]
Regression of #8447
