### ISSUE TITLE
Console regression with 6.9.x for Console::runPhpScriptInBackground

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#8849]
# Bug Report

- [x] Do not submit reports for unsupported versions, supported versions can be viewed here https://github.com/pimcore/pimcore/milestones
- [x] This is not a security issue / vulnerability -> use [this form](https://pimcorehq.wufoo.com/forms/pimcore-security-report/) instead
- [ ] Behavior is reproducible on https://demo.pimcore.fun/admin/ (admin/demo)
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...)
- [x] You're not able to fix the problem yourself and send us a pull request instead of filing an issue.
- [x] There's no existing ticket for the same issue
- [x] Remove unused sections from below and this bullet points, submit only clean reports

### Expected behavior

The command runs correctly.

### Actual behavior

```
Could not open input file: bin/console data:export -p"{param:true}"
```

Caused by the command line being quoted like this
```
/usr/bin/nohup /usr/bin/nice -n 19 '/usr/local/bin/php' 'bin/console data:export -p"{param:true}"' '--env=dev' > /dev/null 2>&1 & echo $!
```

Note that the`bin/console` is being quoted together with the params, passing to PHP as a single name. This is a BC break since 6.8.x

### Code example
```php
#!/usr/bin/env php
<?php

use Pimcore\Tool\Console;

include __DIR__ . "/../vendor/autoload.php";
\Pimcore\Bootstrap::setProjectRoot();

define('PIMCORE_CONSOLE', true);
define('PIMCORE_KERNEL_CLASS', \AppBundle\AppKernel::class);

/** @var \Pimcore\Kernel $kernel */
$kernel = \Pimcore\Bootstrap::startupCli();

Console::runPhpScriptInBackground('bin/console data:export -p"{param:true}"');
```

**Comment by brusch** [comment]
```php
Console::runPhpScriptInBackground('bin/console data:export -p"{param:true}"');
```
is just wrong, maybe this worked by accident in the past, but right would be: 

```php
Console::runPhpScriptInBackground('bin/console', ['data:export', '-p"{param:true}"']);
```
