### ISSUE TITLE
Classificationstore values are not saved on all languages

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#8854]
# Bug Report

Pimcore 6.9.2

Values on Classification Stores are not saved in a predictable fashion to the DB. For example:

 - checkboxes are only saved for the current language
 - input and numeric and most other fields are saved for all languages

This breaks our ability to use Classification stores because filtering on boolean values are not possible.

Example:

Saving a classification store value for a boolean checkbox will not propagate according to the rules of inheritance.

### Expected behavior

Each value should behave in a predictable manner and be available for all languages [according to the docs](https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Classification_Store.html#page_Inheritance).

### Actual behavior

![image](https://user-images.githubusercontent.com/279826/115666759-4162d880-a345-11eb-819c-1a9dd95b26c9.png)

On the last row is the lone checkbox value, it only ever got saved for the `default` language, but not for the other languages.

![image](https://user-images.githubusercontent.com/279826/115666694-2d1edb80-a345-11eb-8213-6980d4be8cf1.png)

**Comment by weisswurstkanone** [comment]
@NiklasBr , can you provide a detailed example. Values are only persistent if non-empty. Are you accessing the database directly or using official getters?

**Comment by NiklasBr** [comment]
Consider this. These checkboxes, like all other data in a classification store is added on the *default* language. With the exception of one which was tested and it appeared on the *nb* language, but not on the *default* language. Inheritance is not working here:

![image](https://user-images.githubusercontent.com/279826/116686368-ff283f80-a9b3-11eb-9671-39dfa9a72d2f.png)

Because of how inheritance is supposed to work [according to the documentation](https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Classification_Store.html#page_Inheritance), values should fall back:

![image](https://user-images.githubusercontent.com/279826/116686665-6a721180-a9b4-11eb-8daa-aab0966e6a40.png)

So, because the database does not follow this rule for *checkboxes* but does follow those rules for other input fields we cannot trust the data.

In addition to the above, this is also contrary to the behaviour of inheritance on DataObjects where data is saved to the database table in a proper manner, which allows us to filter and query for data and trust the result:

![image](https://user-images.githubusercontent.com/279826/116687673-d739db80-a9b5-11eb-98b0-87b9ee7bc575.png)

**Comment by weisswurstkanone** [comment]
But inheritance is not handled on storage level, just on API (getter) level

**Comment by NiklasBr** [comment]
If this is "working as intended" then I have a lot of questions...

First one is very important and still a bug from my perspective. Why does it work like that in regular input and numeric fields, but not checkboxes. If I save a input field on the *default* language, all languages, including the *default* language get that value.

Why is it not reflected in the admin UI?

Why is it not documented?

What was the decision to make this behaviour so very different from regular DataObjects? It makes it harder to develop with.

How are we supposed to filter for values when the documentation explicitly mentions this inheritance?

**Comment by weisswurstkanone** [comment]
1) First one is probably a bug. It should never propagate the value to other languages. 
2) Which probably also answers question two. 
3) Fetching data directly might be efficient but then you trust on internals. Maybe an API would be good for that
4) Please notice that regular objects use a data row per object but classification store creates one row per key

**Comment by weisswurstkanone** [comment]
@NiklasBr how do we want proceed. Can you try this on the demo instance?

**Comment by NiklasBr** [comment]
I tried twice but the required time to set everything up correctly was too short and the demo site reset everything before I managed to reproduce it. Can still reproduce it locally though.

**Comment by weisswurstkanone** [comment]
Ok, that's sad. The demo is reset every two hours. Maybe can give it another try.

**Comment by NiklasBr** [comment]
Looked to me as I was being logged out more often than that. Is there anything else that can affect the demo account?

**Comment by weisswurstkanone** [comment]
Like? :-)

**Comment by NiklasBr** [comment]
Is there anything else that can affect the demo account?

**Comment by brusch** [comment]
Only other people using it, other than that it's just a default composer install using docker images.

**Comment by NiklasBr** [comment]
Spending fruitless time just to be kicked off the platform when anyone else is using it when I'm mostly done is frustrating. Because of this interference I am unable to prove it on the demo instance for your convenience. Is there anything I can do different other than give you detailed instructions how to reproduce it yourselves?

**Comment by brusch** [comment]
@NiklasBr 🏓

**Comment by NiklasBr** [comment]
This is still relevant

**Comment by NiklasBr** [comment]
This is still relevant.

**Comment by fashxp** [comment]
then we would love to see a PR
