### ISSUE TITLE
loading HTML from 3rd-party server to promote Pimcore X

### ISSUE THREAD

**Issue by fabfischer** [pimcore/pimcore#8870]
# Bug Report

### Expected behavior
Do not load HTML from unknown source to promote new pimcore version, at least not without offering an option to disable it.

### Actual behavior
I have noticed that recently on the login page a message is displayed that promotes Pimcore X, but that can also confuse users. For this, a request is sent to https://liveupdate.pimcore.org/imageservice that injects HTML from an external source (?!). 

I would like to see an option in the system settings that at least disables this behavior.

Apart from the fact that I personally find it quite invasive that a Pimcore installation I have installed, with the "Turn off usage statistics" option enabled, injects HTML from a source unknown to me. This increases the risk of XSS if the requested server is compromised.

### Steps to reproduce
1. install latest Pimcore version
2. go to backend login page
3. 
<img width="1826" alt="Screenshot 2021-04-23 at 09 58 05" src="https://user-images.githubusercontent.com/1053032/115839119-9fadbb00-a41a-11eb-9919-9b71296dc347.png">

# Feature Request
1. Option in system-settings, which will deactivate this behaviour.
2. do not load HTML from external server without permission

**Comment by fabfischer** [comment]
Hello @brusch ,
Can you please explain why you are closing this ticket without any comment? I think, in particular the XSS issue, you can not just ignore?

best,
Fabian

**Comment by brusch** [comment]
It's just a notification to create awareness of the soon end of support of Pimcore 6, this is common practice.
The domain has DNSSEC enabled so no DNS spoofing and the code has always been there.

**Comment by NiklasBr** [comment]
The concern is not so much about DNS spoofing as it is about supply chain attacks, which are a very real threat, especially in eCommerce. 

Notify of upcoming stuff in the UI? Sure! But it should follow some simple best practices with regards to security and not just inject JS directly into the login page.

**Comment by dpfaffenbauer** [comment]
https://github.com/dpfaffenbauer/HidePimcoreXMessageBundle solves that for now...
