### ISSUE TITLE
[DataObjects]  UrlSlug value does not update when we save it blank

### ISSUE THREAD

**Issue by gulshan2020** [pimcore/pimcore#8875]
There is an issue with the SLUG attribute.

object_url_slug, it gets save in the object_url_slug table. and after saving the object when we resave the object having an empty value in the slug field, object_url_slug does not get blank for the same object, But it gets updated when we change the value in the slug field.

**Comment by weisswurstkanone** [comment]
@gulshan2020 could you please provide your pimcore version and exact steps to reproduce?

**Comment by dvesh3** [comment]
Fixed by #8914
