### ISSUE TITLE
[Thumbnails] Some transformations do not work

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#8876]
Imagic transformations? 

see also https://x.pimcore.fun/en/More-Stuff/Developers-Corner/Thumbnails

![image](https://user-images.githubusercontent.com/8792145/115872788-7f91f200-a442-11eb-81bb-cbe5a3a52f6d.png)

**Comment by brusch** [comment]
Wrong references in demo, https://github.com/pimcore/demo/commit/a4cc268f7d0bd843215def44d9484995605d6106 fixes it.
