### ISSUE TITLE
pimcore_head_link().appendStylesheet() is broken in Pimcore 6.9

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#8884]
### Steps to reproduce

Add the following code to your layout (Pimcore 6.9.2):

`{% do pimcore_head_link().appendStylesheet(asset('static/css/style.css')) %}`

### Expected behavior

The page works, as in Pimcore 6.8.

### Actual behavior

An exception is thrown:

`Type error: Argument 2 passed to Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher::dispatch() must be an instance of Symfony\Component\EventDispatcher\Event or null, string given, called in /web/web12608/vendor/pimcore/pimcore/lib/Twig/Extension/Templating/HeadLink.php on line 373`

**Comment by brusch** [comment]
@cadeyrn can you please confirm #8894 fixes the issue? Thanks a lot for your feedback!

**Comment by cadeyrn** [comment]
@brusch I can confirm that #8894 fixes the issue. Thanks for the fast fix!

**Comment by brusch** [comment]
@cadeyrn thanks for your feedback! 🙏

**Comment by brusch** [comment]
Fixed by #8894
