### ISSUE TITLE
Object can not be saved in Pimcore 6.9

### ISSUE THREAD

**Issue by knoepfchen23** [pimcore/pimcore#8886]
When saving an Object which has a field-collection with localized fields, it is not possible if the latest version is not published.

How to reproduce?
1. use class and field-collection from zip file: [classes.zip](https://github.com/pimcore/pimcore/files/6375369/classes.zip)
2. create object with the class
3. add field-collection item
3. save and publish the object
4. reload the object
5. save the object using "Only save new version"
5. change the editor field in field-collection
6. save the object using "save and publish"
7. saving is not working

There is an message in the response which comes from:
https://github.com/pimcore/pimcore/blob/0e611941d21d0b9c463a54d616ba784dae60fb9c/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L1262

**Comment by dvesh3** [comment]
Fixed by #8897
