### ISSUE TITLE
Web2print: no preview when hover on the navigation tree

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#889]
I don't know if it is wanted, but when hovering a document web2print page on the navigation tree, there is no preview like web page document.

Example:

![doc](https://cloud.githubusercontent.com/assets/9025839/18965523/dfd7fb92-867d-11e6-8ab6-e4e1d57c1d48.png)

---

Hovering a container web2print could display all the page of the container (like for a directory in assets).

Exemple:
![folder](https://cloud.githubusercontent.com/assets/9025839/18965529/e75460d6-867d-11e6-8280-c1fd1f899ed0.png)

I think it is a valuable tools here, as we can get faster to check which page we want to edit.

**Comment by fashxp** [comment]
this is wanted since whole web2print catalog can become really huge.
