### ISSUE TITLE
Joins in customviews not working after update 6.8.3 -> 6.9.2

### ISSUE THREAD

**Issue by C-R-W** [pimcore/pimcore#8900]
When working with joins in customviews the folowing error gets thrown.

"The given alias '' is not part of any FROM or JOIN clause table. The currently registered aliases are: objects."

**Comment by brusch** [comment]
@C-R-W Can you maybe provide a pull request or patch that fixes your issue? Actually with the given information it's quite hard to reproduce the issue. Thanks!

**Comment by brusch** [comment]
@C-R-W 🏓

**Comment by C-R-W** [comment]
Hi there, sorry for the late respons. I will try to find the issue. if i can fix it i'll come back with a pr.

**Comment by brusch** [comment]
I guess this was fixed already by #9038
If you still experience this issues, please just let me know, then we'll reopen this issue. Thanks!

**Comment by solverat** [comment]
@brusch experiencing the same on `6.9.4` when using `joins` in `customviews.php`:

![image](https://user-images.githubusercontent.com/700119/120478438-23a97a00-c3ad-11eb-8a3b-beb11f084fda.png)

**Comment by solverat** [comment]
@brusch so there will be no back port to 6.9 I guess?

**Comment by brusch** [comment]
@solverat we're happy to accept PRs for `6.9` until June 23, 2021, would be nice if you could open one. Thanks in advance!
