### ISSUE TITLE
Consistent behaviour for document Title/Navigation/Key

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#8907]
The field order for "Add Page" is Title, Navigation, Key.
When changing the Title, the other fields get prefilled automatically.

![image](https://user-images.githubusercontent.com/90033/116212538-393fda00-a745-11eb-89a4-ba31d86af558.png)

The order in "Create Translation" (Document Language Overview) is Key, Navigation, Title.
Changing the Key prefills Navigation, Title stays empty. Changing the Title does nothing.

![image](https://user-images.githubusercontent.com/90033/116213574-32fe2d80-a746-11eb-8912-1d5034932064.png)

The same logic should be used for use cases.

In addition it would be nice to create a nice key/slug automatically.

As shown in the pimcore demo the following Keys are used:

![image](https://user-images.githubusercontent.com/90033/116213163-d3078700-a745-11eb-8ac1-a251dbe5473c.png)

Which results in URLs like: https://demo.pimcore.com/en/Magazine/Pick%20of%20the%20Day

In my opinion the Key should get prefilled with a nice slug (pick-of-the-day instead of Pick of the Day) if the field is empty.

Version: dev-master|add74462508e662a032f297149e1a7dfe5c042d2

**Comment by brusch** [comment]
ad slug: I'd just replace ` ` (space) with a hyphen `-`, everything else I'd leave as it is.
