### ISSUE TITLE
Improve area brick list

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#8909]
~~Not all bricks can get accessed if working an small screens and/or the list of bricks is to long. Allow the list to scroll if it doesn't fit the screen.~~

Duplicate https://github.com/pimcore/pimcore/issues/8879

---
[Feature]

Also it would be nice to allow setting a default group value for bricks in php, not only in twig using `pimcore_areablock()`.

![image](https://user-images.githubusercontent.com/90033/116217595-15cb5e00-a74a-11eb-91e8-ebf9e7512931.png)

**Comment by brusch** [comment]
The best approach for that would be to create your own Twig extension that provides the functionality you need. 
See also: https://github.com/pimcore/pimcore/issues/4066#issuecomment-607138560
