### ISSUE TITLE
Js Error in fieldCollection

### ISSUE THREAD

**Issue by tarun-singhal** [pimcore/pimcore#891]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [x] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [x] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [x] There's no existing ticket for the same issue

### Expected behavior 
 Mandatory Numeric data type not prompt for the data validation in Field-collection use inside class.
 
 ### Actual behavior  
  Mandatory Numeric data type should prompt for the data validation.

### Steps to reproduce  
 1. Create new Field-Collection with data type of "Number"
 2. Mark that field as Mandatory
 3. Use that field-collection in any class  then save it.
 4. Create object of that class and fill data in object without filling of field-collection Number type data element, then try to "Save" or "Save & Publish".
 You will get error like below 
 **TypeError: this.component.getValue(...) is null**
 Which is continuously coming after "Save"

### Code example 
```php
// your code
```

# Feature Request 
## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [x] There is no existing issue regarding the same topic

**Comment by weisswurstkanone** [comment]
fixed in build 3974
