### ISSUE TITLE
[Documentation Request] Create a how to / best practise page for Development Setup for core development

### ISSUE THREAD

**Issue by frithjof** [pimcore/pimcore#8915]
There is no real easy starting point how to setup your enviroment for core development and running tests local.

A documentation page for this would be great to get more community support.

**Comment by weisswurstkanone** [comment]
Regarding testing:

https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Testing/Core_Tests.html

**Comment by frithjof** [comment]
yeah i read that and used it on a skeleton install

in a perfect world it would be like 
* make a demo skeleton install via composer
* checkout your branch in vendor folder 
* set in .env PIMCORE_TEST=1 
* run ./run_tests.sh
and then it would run all tests that are required for pull requests

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
