### ISSUE TITLE
Custom Reports not working properly in 6.9

### ISSUE THREAD

**Issue by aweichler** [pimcore/pimcore#8925]
After update Pimcore 6.6.11 to 6.9.2 many custom reports not working as expected.
We have reports with an id column, which is set to not "display", not "export" but "order". The id column has an action for open the object.
In Pimcore 6.6 in the report the column is not shown but open is working. In Pimcore 6.9 the column is not shown but the object can not be opened.
The object can only be opened if "export" is checked at the id column. The column configuration "display" for id has also no effect.

I think the following lines caused the failure:
https://github.com/pimcore/pimcore/blob/1b45e4fd88893e76c15ecab03fcf7e9aa4896641/models/Tool/CustomReport/Adapter/Sql.php#L41-L43

The commit is following:
https://github.com/pimcore/pimcore/commit/0479503048fc6229704652556c867a7caeb7b30e#diff-9cbd4becdfb6a1efbfec68730884b82a05a7b987cf2207881daafab4effe0a6c

In the zip file ([reports.zip](https://github.com/pimcore/pimcore/files/6389193/reports.zip)) I put a class definition and a custom report file to demonstrate the issue.

**Comment by dvesh3** [comment]
Fixed by #8930

**Comment by aweichler** [comment]
Thanks for fast fixing.
