### ISSUE TITLE
WYSIWYG: Internal Link Transform Glitch

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#8928]
Reproducible on latest Pimcore (and demo) and also on 6.6.x which is my current test suite.

## Steps to Reproduce
- Add WYSIWYG element
- Add some text
- Select some text
- Drag another document onto the selected text
- Save
- Reopen
- Click in to link text
- Click the "link" symbol in the editor config bar
- Change the URL to an external www.google.at
- Save
- Reopen
- Check source or frontend

## Current Behavior
Link gets transformed back to the internal link because the internally added attributes `pimcore_id="46" pimcore_type="document"` are not getting removed

## Expected Behavior
Link should act as an external link and internally added attributes should be removed

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
