### ISSUE TITLE
PDFReactor 8.1 does not work on windows systems

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#893]
# Bug Report

### Expected behavior 
Generate PDF from Web2Print should work with PDFReactor 8.1 on windows.
### Actual behavior  
Generating PDF throws error:
File Not Found: http://domain.com/website/var/tmp%5Cpdf-reactor-input-6.html
### Replacing this:
```php
$filePath = PIMCORE_TEMPORARY_DIRECTORY . DIRECTORY_SEPARATOR . "pdf-reactor-input-" . $document->getId() . ".html";
```
with this:
```php
$filePath = PIMCORE_TEMPORARY_DIRECTORY . '/' . "pdf-reactor-input-" . $document->getId() . ".html";
```

does fix the issue for me.

**Comment by solverat** [comment]
the question is: what does DIRECTORY_SEPARATOR returns on windows? :)

**Comment by Cruiser13** [comment]
It does return %5c which equals \ . But we try to include the whole domain path here (like displayed from the browser) and not a real path so we probably should use / instead of the file system separator I think.

**Comment by Cruiser13** [comment]
Thank you @brusch
