### ISSUE TITLE
Cannot manualy set block controls position anymore 10.0.0-BETA4

### ISSUE THREAD

**Issue by HaaseIT** [pimcore/pimcore#8946]
Since the blockControls() method is now private, I cannot set the block controls anymore.

The documentation still mentions blockControls():
https://pimcore.com/docs/pimcore/master/Development_Documentation/Documents/Editables/Block.html

What is the replacement?

**Comment by brusch** [comment]
@HaaseIT thanks for reporting. I'm afraid I was to ambitious in #8899 😊
