### ISSUE TITLE
API Key Aviary is hard coded, it should be in system config

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#896]
API Key Aviary is hard coded, it should be in system config i think.

Here is the code:
https://github.com/pimcore/pimcore/blob/master/pimcore/modules/admin/views/scripts/asset/image-editor.php#L29

**Comment by brusch** [comment]
This key is registered for the product *Pimcore*, so it should be fine. 
Getting an API key from Adobe is a manual process and I'm not sure if they issue keys for individual projects, so I don't think it's a good idea to remove it.

**Comment by Yivan** [comment]
Thanks Brush, I understand better so.

I was thinking the purpose of this key was to make aviary able to connect/sync with Adobe Creative Cloud, i was wrong : )
But is there a way to implement this adobe cloud sync on the web version of aviary ?
Here is the aviary documentation for web version, and they talk about sync with the adobe creative cloud (arround middle/end of the page):
https://creativesdk.adobe.com/docs/web/#/brandguidelines/index.html

Would be really nice to be able to push editing on Photoshop CC directly for graphist people working on the Pimcore assets (they open pimcore, edit the image, sync with photoshop and go on editing on photoshop directly without having to export the file and reimport it).
Here a screen capture from this page:
![signin](https://cloud.githubusercontent.com/assets/9025839/19072642/a383c7f4-8a36-11e6-8918-3f67fac14f36.png)

**Comment by brusch** [comment]
Why not using WebDAV?

**Comment by brusch** [comment]
Implementing more Creative Cloud functionalities should be pretty easy using plugins, I don't think we should waste much time on implementing this into the core.

**Comment by Yivan** [comment]
Thanks, we will have a look at creative cloud sdk so to implement it with plugin.

I have search on the documentation (https://www.pimcore.org/docs/latest) to set the webdav with Pimcore but there is no more reference on it (on old documentation there was i i remember, google send this result but i cannot access to the cached page: https://www.pimcore.org/wiki/.../PIMCORE/Setting+up+WebDav).
Only page I found is this one: https://www.pimcore.org/docs/latest/Assets/index.html, and it say to refer to the "Pimcore User Documentation".

Maybe this documentation sould be accessible somewhere, and add a link to it on this page maybe so people find it more easily ?

**Comment by brusch** [comment]
The user documentation is in the works. 
The old docs are still available here for reference: https://www.pimcore.org/confluence/
