### ISSUE TITLE
pimcore.error.ValidationCancelledException is not a constructor

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#8962]
Using `throw new pimcore.error.ValidationCancelledException('error message')` throws an error.

![image](https://user-images.githubusercontent.com/90033/116666207-fe36e400-a99a-11eb-8b32-96d172c303cd.png)

`ActionCancelledException` works fine.

https://pimcore.com/docs/pimcore/master/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/Plugin_Backend_UI.html#page_Validate-Pimcore-Object-s-Data-in-frontend-before-saving

Version: dev-master|f95eab815b1c7584961a8595a4404c5c1af3bb40

**Comment by weisswurstkanone** [comment]
IMHO, the docs should say `pimcore.error.ValidationException`.

**Comment by dvesh3** [comment]
Fixed by #8964
