### ISSUE TITLE
Allow [space] and capitals in keys of Assets, Documents and Objects

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#898]

**Comment by nspacex** [comment]
Hi brusch, 

has this feature an special background or is it maybe possible to disable the spaces? I think spaces in the key or especially  in the url are not optimal. Of course I can manually enter the key without special characters / space but it is a extra (error-prone) step for the editors. I think the system option to allow/disallow spaces and/or captials in the keys was not so bad :)   

Thank's, Eric

**Comment by brusch** [comment]
There was never an option to enable/disable capitals or spaces, they were just completely disallowed. 
Since the web is more and more heading to internationalized URLs (UTF8), I'm pretty sure that this is just the beginning. 

Other opinions are of course always welcome.

**Comment by nspacex** [comment]
Thanks for your fast answer. You're right, that's a point. But i think an option to disable this beaviour would be nice for the following reasons:

- if i copy the url "domain.com/test Test" and paste it somewhere the url looks like that: "domain.com/test%20Test" (firefox to chrome, firefox to editor, ...)
- "on older browsers, copying the URL may leave a space in the URL, so when pasting the link into another webpage like a forum post, the URL will become broken ..." (found in some post on stackexchange)
- if I click an Link with spaces in the href, chrome convert the spaces to %20 in the adressbar
- Maybe it has an impact on google / search engines 
- Maybe the url's in search results on google / search engines becomes also %20 (not really nice)  

What do you think? If you wish I can make a PR but at the moment i unfortunately have not time. I think within the next two weeks it should be possible.

**Comment by brusch** [comment]
1. Yes, that's certainly true
2. Well, yes, hopefully nobody is still using them ;-) 
3. Yes, for a good reason, see 1 & 2 actually pimcore produces valid URLs so the URLs are already encoded
4. I don't think so, ... https://ko.wikipedia.org/wiki/%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC%3a%EB%8C%80%EB%AC%B8
5. No: https://www.google.at/search?q=%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC%253a%EB%8C%80%EB%AC%B8&oq=%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC%253a%EB%8C%80%EB%AC%B8

Actually Google supports them already for a very very long time and is happy to use them.

**Comment by nspacex** [comment]
1. - 5.) Ok ok :)
6.) I don't like it ;) Of course that is no reason to change anything

Thanks for your response brusch

**Comment by brusch** [comment]
I think the best solution would be to allow the modification of the key policies by using an event, because this is the most flexible solution.  
Therefore I've implemented the event `system.service.preGetValidKey` which allows the modification of the key before the global policy is applied. 

### Example
To keep the old behavior you could just add the following code to your `startup.php` : 
```php
\Pimcore::getEventManager()->attach("system.service.preGetValidKey", function (\Zend_EventManager_Event $event) {
    $key = $event->getParam("key");
    $key = \Pimcore\File::getValidFilename($key);
    return $key;
});
```
It's also possible to do this depending on the type: 

```php
\Pimcore::getEventManager()->attach("system.service.preGetValidKey", function (\Zend_EventManager_Event $event) {
    $key = $event->getParam("key");

    if($event->getParam("type") == "document") {
        $key = \Pimcore\File::getValidFilename($key);
    }

    return $key;
});
```

**Comment by nspacex** [comment]
Wow, thats very nice. Thank you very much.

**Comment by brusch** [comment]
Maybe it's better to make the policy change not that drastically within a minor version, especially for documents. New proposal: 
**Capital letters**: Assets, Documents, Objects
**Spaces**: Assets, Objects

See also: 01ff8dfa79af64fc54346f7116e78a0cfb8a9a4e

**Comment by Cruiser13** [comment]
I'd actually like capitals in assets. If you are using WebDav synchronisation with Pimcore and the file system, the files are loosing capitals at the moment which does cause issues with Windows clients.

The modification of the key policies by using the event sounds great.

**Comment by Mellnik** [comment]
Sorry for reopening. Why is this fix not included in current version? https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/File.php#L62

**Comment by brusch** [comment]
@Mellnik it definitely is... just checked it on 2 upgraded projects and in the download files. 
Maybe something went wrong during your update?

**Comment by Mellnik** [comment]
But the commit https://github.com/pimcore/pimcore/commit/4a576fd30a9a967c5eb69751a5e7f8543882c564

Is somehow not in the master branch?
https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/File.php#L62

**Comment by brusch** [comment]
@Mellnik the functionality of `Pimcore\File::getValidFilename()` stayed the same for compatibility reasons. 
Pimcore actually uses `\Pimcore\Model\Element\Service::getValidKey()` to create a valid key.

**Comment by Mellnik** [comment]
Thanks for clarification.
