### ISSUE TITLE
Register custom placeholders via tagged services 

### ISSUE THREAD

**Issue by davidhoeck** [pimcore/pimcore#8984]
# Feature Request

## Feature description

Currently placeholders must be registered via the `Pimcore\Placeholder::addPlaceholderClassPrefix(...)` method. You make it more the Symfony-ish custom placeholders should be registered via the service tag `pimcore.placeholder`.

**Comment by dpfaffenbauer** [comment]
they have been removed with X, so not necessary anymore

**Comment by dvesh3** [comment]
please see https://github.com/pimcore/pimcore/pull/7261
