### ISSUE TITLE
Renaming with the same name (or final name after key formating) show inifinite loading picto

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#900]
On the demo site, on the object tree for instance:
- create a folder named "Test one" (it create a folder test-one)
- rename the folder just created to test-one

The loading picto is infinite and so user need to refresh manually the tree.
Same for object. I didn't try document/asset but maybe same too.

Here is a screenshot:
![inf](https://cloud.githubusercontent.com/assets/9025839/19072968/919418e4-8a38-11e6-96b4-0b9cbc5c8448.png)

Thanks

**Comment by mrudnicki** [comment]
Too fast I marked it as a bug. 
@Yivan The issue is impossible to reproduce in the newest version of Pimcore in any other environment. 
Thanks for the request we try to fix it on the demo.

**Comment by Yivan** [comment]
Thanks mrudnicki!
Just for information, i tried on one of our project about to be released in production based on Pimcore 4.3.0 release (build 3932, ie stable/professional package), and the problem occurs too.
You mean upgrade it to the 4.3.1 (stable/prof package) will correct the problem ? (or do we have to go to nighly build, wich i am more reluctant for production).

**Comment by brusch** [comment]
The demo is always using the latest build not the stable version.
