### ISSUE TITLE
user with only "save" action allowed: strange effet

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#903]
If ou create an user with only "objects" right and allow him in workspace access to an object directory with only "list", "view" and "save" action allowed, like here:

![userright](https://cloud.githubusercontent.com/assets/9025839/19094317/d0584fa8-8a8f-11e6-8590-aeb155bf9ae6.png)

After you log in with this user, and just make a save on an already published object, you can see that in the tree the object the object is unpublished (this is only a graphical problem, in database it is not unpublished), like on this screenshot:

![step1](https://cloud.githubusercontent.com/assets/9025839/19094408/4c571710-8a90-11e6-959f-8469358c5dc0.png)

So if you refresh the tree, it is ok (showing that the object has not really been unpublish by doing save):

![step2](https://cloud.githubusercontent.com/assets/9025839/19094449/7544ece2-8a90-11e6-9651-daed4edf6c78.png)

I think after applying "save" action the object should not been unpublish in the tree, and stay published.

**Comment by brusch** [comment]
Rollback was needed, see #996

**Comment by weisswurstkanone** [comment]
Unable to reproduce in 3998
