### ISSUE TITLE
PHP error on video editable

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#9044]
Hello,

I would like to submit a PHP error (notice) triggered by video editables.

When using video editable on twig template (we work with `error_reporting(E_ALL)` to ensure code quality), `$config['class']` send a `Notice: Undefined index class` in the method `getYoutubeCode()` in the file `models/Document/Editable/Video.php`:
https://github.com/pimcore/pimcore/blob/master/models/Document/Editable/Video.php#L589

I think problem is maybe on the other methods using `$config['class']` on this file (`getVimeoCode()`, `getDailymotionCode()` and `getAssetCode()`).

Thanks.

**Comment by dvesh3** [comment]
Pimcore version?

**Comment by Yivan** [comment]
The Pimcore version is v6.8.10, thanks.

**Comment by Yivan** [comment]
Thanks a lot for your very fast fix 👍
