### ISSUE TITLE
Version UI Improvements

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#905]
Actually reading the version tab is really hard for non-technical people. Even our developper sometimes ask themselves, what line is the active one, the selected one, ...

For instance we could have something like this actually:

![version1](https://cloud.githubusercontent.com/assets/9025839/19094719/f09352d4-8a91-11e6-9186-1cca695096a8.png)

There are 4 colors... white, grey light, grey dark, yellow. from what i understand:
- white/ grey light is a graphical effect wich purpose is to improve reading adjacent line
- yellow is the selected one
- grey dark is the current published version

I think it could make easier to be read by doing those small improvments:
- just abandonning the white/grey alternance, to keep only white background for all cells
- add a small picto with an alt hover for explaining (or a text) for the current published version (and keeping grey background color to identify it faster). It will be more comprehensive than only "gray" background.

The "This is a newer not published version" is very important i think. It means it need to be reviewed by the user before publishing it. Actually this text is not so visible. Maybe with a colored background and/or bold text, will help editor to save by mistake a new version thay have not reviewed ?
(actually i think having this information even in the tree and grid list it will be great, but it is a more complicated developement wich will need a separate issue, because actually only custom reports could list elements having newer versions not published... maybe having by default a reports on dashboard with this could be from great help and will be easier to implement).

Finally, the comparator is a great feature, but hard to find. Maybe a small helper text somewhere saying "use CTRL + Click to select several version and compare them" will be great too.

All those improvements are small one, but they could improve editor's work when working on multi-version datas i think.

Aside from this, just very small problems (not important but as i am on this issue, i talk about them): js console send "edit not available" log (maybe it is intended) and 404 error, and maybe the selected grey background line could be more "visible", as shown on the following screenshot:

![version2](https://cloud.githubusercontent.com/assets/9025839/19095018/bcbf9f2e-8a93-11e6-9fa2-9bf0320d3b7d.png)

I hope all of this make sense to make better use of the pimcore versionning tool for users!
Thanks.

**Comment by brusch** [comment]
Implemented consistent across documents, assets and objects. 
- published version is indicated by the "published" icon (dedicated column)
- 404 warning fixed
- added hint how to compare (objects only) 

![image](https://cloud.githubusercontent.com/assets/142037/19680435/012d153e-9aa6-11e6-9e09-6bf7c29fdaf7.png)
