### ISSUE TITLE
[Assets] Provide text preview for CSV and JSON files 

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#9058]
as we have it for txt files

**Comment by dvesh3** [comment]
@fashxp csv files are already supported.

**Comment by fashxp** [comment]
hmm, doesn't work for me ... neither csv nor json

see also https://demo.pimcore.com/admin/login/deeplink?asset_412_unknown or https://demo.pimcore.com/admin/login/deeplink?asset_413_unknown

![Snag_20b5b3f](https://user-images.githubusercontent.com/8792145/129592793-f7d50e71-6b1e-44ad-b1dc-ad24270768a7.png)

**Comment by weisswurstkanone** [comment]
Fixed the db dump for the demo instance.
