### ISSUE TITLE
[Predefined Properties] /admin/element/get-predefined-properties returns an empty array 10.0.0-BETA4

### ISSUE THREAD

**Issue by HaaseIT** [pimcore/pimcore#9066]
When you define Predefined Properties, they are not listed in the document under the dropdown menu in Navigation & Properties.

The xhr request for them returns an empty array.

**Comment by dvesh3** [comment]
@HaaseIT sorry, it works for me
![image](https://user-images.githubusercontent.com/5137917/117571906-d5b49580-b0d0-11eb-9ccc-4d4415ee0847.png)

**Comment by HaaseIT** [comment]
Oh my dear, this is totally my fault, I misconfigured. Please close this.
