### ISSUE TITLE
Using TAB-Key within Data Object grid breaks ExtJS

### ISSUE THREAD

**Issue by unshapedesign** [pimcore/pimcore#9079]
# Bug Report

Using TAB-Key within Batch Edit breaks ExtJS for the complete Pimcore Backend. 
Tested with https://demo.pimcore.fun/admin/ using newest Versions of Chrome and FF on MacOS.

### Expected behavior
Using TAB-Key within the Grid View in Batch Edit to navigate between the editable input fields like in excel.

### Actual behavior
Using TAB-Key to proceed from Input-Type-Attribute to next Attribute results in a "e is null" ExtJS exception  and the Backend is no longer usable.

### Steps to reproduce
1. Open Batch Edit for any Dataobjects
2. Click any column of type "Input" ("Name" in the pimcore demo) to edit a value
3. Press TAB-Key to proceed to next editable field (and click save or cancel to close the dialog if any)
4. Now ExtJS is getting the exception "e is null" if you click on any column and the backend is not usable anymore

![Bildschirmfoto 2021-05-10 um 22 52 56](https://user-images.githubusercontent.com/3041258/117723906-8b1b4200-b1d2-11eb-9452-37fc3773d8ad.png)

![Bildschirmfoto 2021-05-10 um 22 53 17](https://user-images.githubusercontent.com/3041258/117723928-91a9b980-b1d2-11eb-8d57-9e7e68a8b4ca.png)

![Bildschirmfoto 2021-05-10 um 22 55 56](https://user-images.githubusercontent.com/3041258/117723943-953d4080-b1d2-11eb-955e-c3ccf06722a5.png)

![Bildschirmfoto 2021-05-10 um 22 57 50](https://user-images.githubusercontent.com/3041258/117723953-98d0c780-b1d2-11eb-87a1-09e72a6eb9a4.png)

**Comment by brusch** [comment]
Please check for `v10.0` as well. Thanks!

**Comment by weisswurstkanone** [comment]
Note: this override is only for 6.9 and will be harmful for 10. Do not merge it!

**Comment by dvesh3** [comment]
Fixed by #9150
