### ISSUE TITLE
Error Handling for wrong formatted Customer data

### ISSUE THREAD

**Issue by mike4git** [pimcore/pimcore#9088]
If one is creating (or updating an existing) customer and fills in a wrong formatted birth date:
![CMF_Fehler](https://user-images.githubusercontent.com/5848798/115901134-19689780-a461-11eb-9bb0-35ee08477ef5.png)

After clicking Save button the input field will be **red framed** but toolbox tells **"Saved successfully!"** and reloading of the Customer dismisses all "updated" values.
There should be an alert message instead.

**Comment by dvesh3** [comment]
Fixed by #9148
