### ISSUE TITLE
XLSX Export 500 Error

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#9089]
![image](https://user-images.githubusercontent.com/13643455/117832142-83f94000-b275-11eb-9ab0-3cad8b0b1523.png)

https://demo.pimcore.com/admin/object-helper/download-xlsx-file?fileHandle=export-609a934bee38c

![image](https://user-images.githubusercontent.com/13643455/117832104-793eab00-b275-11eb-912b-4c2c46b0981f.png)

**Comment by brusch** [comment]
Fixed by #9093
