### ISSUE TITLE
TIFF generation break image (bad color nearly black and white)

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#909]
On the demo website of Pimcore, if you create a thumbnail configuration named "mytiff", you choose format "TIFF" and save it, like on this screenshot:

![mytiff](https://cloud.githubusercontent.com/assets/9025839/19111405/b02bd23e-8aff-11e6-83b3-b1d3b68a3c83.png)

Next if you call, automatic generation on asset id 39 for this thumbnail configuration:
https://demo.pimcore.org/website/var/tmp/image-thumbnails/0/39/thumb__mytiff/placeholder.tiff
(if you use Safari Mac or Windows you will see the TIFF as it is supported by the browser, if not it should be downloaded to see the result in a tiff viewer).

The sended image is broken (bad color, near black and white), see it in the following zip please:

[placeholder.zip](https://github.com/pimcore/pimcore/files/510995/placeholder.zip)

I tried with the last build on my local linux environment (debian jessie) and same. Even with ICC profils given in the system configuration for assets section.
I don't know if it is an imagick problem or pimcore, but it seems TIFF format could not be used actually with Pimcore.

**Comment by brusch** [comment]
Seems to be a problem of Imagick when using LZW compression. 
Using `$i->setCompression(\Imagick::COMPRESSION_LZW);` causes the problem, while `$i->setCompression(\Imagick::COMPRESSION_JPEG);` works without any issues. 

I'm now checking which side-effects a change to JPEG compression could possibly have.

**Comment by brusch** [comment]
Using `$i->setCompression(\Imagick::COMPRESSION_ZIP);` has the same issues while `$i->setCompression(\Imagick::COMPRESSION_NO);` is fine.

**Comment by brusch** [comment]
Due compatibility reasons it's not recommended to use lossless JPEG compression in TIFFs so the only alternative is using `$i->setCompression(\Imagick::COMPRESSION_NO);` but then the TIFFs will get huge in terms of filesize. 

I'm not sure if we should change something in Pimcore regarding this issue. 

Code to reproduce: 
```php
        $sourceFile = "/tmp/test.png"; // any source format will do
        $tmpFile = "/tmp/test-" . uniqid() . ".tif";
        $i = new Imagick();
        $i->readImage($sourceFile);
        $i->setCompression(\Imagick::COMPRESSION_LZW);
        $i->writeImage("tiff:" . $tmpFile);
``` 
Feel free to file an issue here: https://github.com/mkoppanen/imagick :)

**Comment by Yivan** [comment]
Thanks Brush to have a look on this issue.

I will try different options on my side to see which one work. Seems there are many compression constants possible (http://php.net/manual/fr/imagick.constants.php)
Some of them need to be enabled in the imagick binary it seems (and LWZ is one of those needed, maybe this is the cause of the problem?) : http://www.imagemagick.org/script/command-line-options.php#compress
I will post here if i find another alternative format.

**Maybe to ensure people can use TIFF we could add as parameter in thumbnail configuration the compression method ?** So people can create thumbnail configuration wich work fot TIFF at least (even if none is perfect like size or other side problem).

**Comment by Yivan** [comment]
Only 4 compressions work for TIFF imagick, they are:
COMPRESSION_FAX
COMPRESSION_GROUP4
COMPRESSION_LZW
COMPRESSION_ZIP

And the 4 are broken : ( as seen on this zip containing the 4 tests:
[test-tiff.zip](https://github.com/pimcore/pimcore/files/513605/test-tiff.zip)

All other leave the file uncompressed:
COMPRESSION_NO
COMPRESSION_UNDEFINED
COMPRESSION_BZIP
COMPRESSION_JPEG
COMPRESSION_JPEG2000
COMPRESSION_RLE
COMPRESSION_DXT1
COMPRESSION_DXT3
COMPRESSION_DXT5

What is strange is that i don't find post on internet about this problem with imagick. I use a stable version of debian jessie, so many people have the same setup. It is a breaked fonctionnality of imagick as tiff cannot be used compressed. Many application use imagick and use tiff i think.
I will make some search and update this issue.

**Comment by brusch** [comment]
For me the following 2 work as well: 
COMPRESSION_NO
COMPRESSION_JPEG

Imagick info: 
```
imagick module version:	3.4.2
Imagick using ImageMagick library version: ImageMagick 6.8.9-9 Q16 x86_64 2016-09-23
```

But anyway, ... we're discussing this internally whether we're implementing a workaround or not.

**Comment by Yivan** [comment]
COMPRESSION_NO and COMPRESSION_JPEG work ok for me too.

Just those four are broken COMPRESSION_FAX, COMPRESSION_GROUP4, COMPRESSION_LZW, COMPRESSION_ZIP

My versions are:
```
imagick module version: 3.2.0RC1
Imagick using ImageMagick library version: ImageMagick 6.8.9-9 Q16 x86_64 2016-09-23
```

I made some further test, and no way to make it work.
You can see the issue on imagick open here: https://github.com/mkoppanen/imagick/issues/178

Yes having a workaround would be great. Thanks.

**Comment by Yivan** [comment]
Issue has been closed on imagick php side, because it was a libtiff problem (mkoppanen/imagick#178)

People interested in this issue can find information here too:
https://www.reddit.com/r/imagemagick/comments/3tqhmx/tiff_compression_broken_on_debian_jessie/
So updating libtiff make tiff working.

SOLUTION:
Updating the libtiff. Here is the exemple for Debian Jessie stable.
As root user:
```
cd ~
wget http://ftp.fr.debian.org/debian/pool/main/t/tiff/libtiff5_4.0.6-2_amd64.deb
dpkg-deb -R libtiff5_4.0.6-2_amd64.deb ./libtiff
cp ./libtiff/usr/lib/x86_64-linux-gnu/libtiff.so.5.2.4 /usr/lib/x86_64-linux-gnu/
rm /usr/lib/x86_64-linux-gnu/libtiff.so.5
ln -s /usr/lib/x86_64-linux-gnu/libtiff.so.5.2.4 /usr/lib/x86_64-linux-gnu/libtiff.so.5
```

Brush, if you think a workaround is no more necessary you can close the task.
Thanks!

**Comment by brusch** [comment]
I can conform that installing the latest libtiff debian package fixes the problem

```bash
wget http://ftp.fr.debian.org/debian/pool/main/t/tiff/libtiff5_4.0.6-2_amd64.deb
dpkg -i libtiff5_4.0.6-2_amd64.deb
```

So in my opinion it's not worth to implement a workaround.

**Comment by psuhane** [comment]
Hey @brusch, I am also getting the same kind of issue while uploading tiff images in pimcore instance. I think issue with color profiles.. If tiff image uploaded in RGB mode, image thumbnail generated correct but if the tiff image uploaded in CMYK mode then thumbnails comes with black and white colour. I think color inversion happens in case of CMYK.

As per detail available on documentation - Due licensing issues Pimcore doesn't include the color profiles (*.icc files) in the download package, but you can download them for free here: Adobe ICC Profiles or here: ICC (color.org). I have tried most of the color profiles in system settings but my bad luck..

I have also installed the libtiff latest version, but still issue not resolved.

**Comment by brusch** [comment]
It is definitely and reproducible an issue with libtiff.
Please ensure that Imagick uses the updated version of libtiff.
