### ISSUE TITLE
[EcommerceFramework - VoucherService] cleanUpReservation doesn't work proper 

### ISSUE THREAD

**Issue by MHundeloh** [pimcore/pimcore#9094]
# Bug Report

### Expected behavior
Voucher reservation that are older than configured reservation_minutes_threshold should be deleted when calling the console command ecommerce:voucher:cleanup-reservations

### Actual behavior
Running the console command leaves older reservation if reservation_minutes_threshold is set to a value greater than 59.
The reason is that the used where-clause MINUTE(TIMEDIFF(timestamp, NOW())) >= ? separates the minute as integer (0 to 59) of the time diff. But it should give the total time diff in minutes for comparison with reservation_minutes_threshold in minutes.

### Steps to reproduce
Add valid vouchers to several carts und leave the carts uncommited
Configure the reservation_minutes_threshold > 59
Run the console command ecommerce:voucher:cleanup-reservations
All reservation will be left in database table ecommerceframework_vouchertoolkit_reservations

### Code example
Current code:
```php
    public static function cleanUpReservations($duration, $seriesId = null)
    {
        $query = 'DELETE FROM ' . \Pimcore\Bundle\EcommerceFrameworkBundle\VoucherService\Reservation\Dao::TABLE_NAME . ' WHERE MINUTE(TIMEDIFF(timestamp, NOW())) >= ?';
        $params[] = $duration;
```
My Code:
```php
    public static function cleanUpReservations($duration, $seriesId = null)
    {
        $query = 'DELETE FROM ' . \Pimcore\Bundle\EcommerceFrameworkBundle\VoucherService\Reservation\Dao::TABLE_NAME . ' WHERE TIMESTAMPDIFF(MINUTE, timestamp , NOW())  >= ?';
        $params[] = $duration;
```

# Feature Request

**Comment by dvesh3** [comment]
Fixed by #9436
