### ISSUE TITLE
[Assets] Thumbnails: calling getLocalFile() on error thumbnail image throws exception

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#9100]
# Bug Report
If there is an error on generating asset thumbnail then getLocalFile() call throws exception:
![image](https://user-images.githubusercontent.com/5137917/117956639-87460780-b319-11eb-92d9-5503d872f233.png)
https://github.com/pimcore/pimcore/blob/10.x/bundles/AdminBundle/Controller/Admin/Asset/AssetController.php#L1185-L1186
https://github.com/pimcore/pimcore/blob/10.x/models/Asset/Thumbnail/ImageThumbnailTrait.php#L312

**Comment by brusch** [comment]
What do you think the expected behavior is? Displaying the error image?

**Comment by brusch** [comment]
It would be also interesting why it fails and how to reproduce 😊

**Comment by dvesh3** [comment]
@brusch faced this issue while reproducing #8316, so i performed these steps:
1. Open Image.
2. Download image with different format from "Custom Download" section(right bottom).
3. Use "upload new version" option to replace image with downloaded one.

I guess we just need to return empty string here if stream is null https://github.com/pimcore/pimcore/blob/10.x/lib/Helper/TemporaryFileHelperTrait.php#L45

**Comment by HaaseIT** [comment]
If I might chime in on this, two of my customers are hosted on Strato, one of them is already on v10, and most (if not all) of the image-functionality is broken there.

I had to disable Thumbnails alltogether to keep the website working.

The instances I am hosting myself are working just fine.

**Comment by dvesh3** [comment]
Fixed by #9182
