### ISSUE TITLE
Working with data objects - warnings/exceptions using PHP 8

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#9103]
# Bug Report

I've faced some issues working with data objects using default error reporting settings.

Object setup:

![image](https://user-images.githubusercontent.com/90033/117972966-10663a00-b32c-11eb-9d29-1c8c44a397b1.png)
![image](https://user-images.githubusercontent.com/90033/117973329-8f5b7280-b32c-11eb-930f-9aa573357be9.png)

Add/remove gallery item and save:

![image](https://user-images.githubusercontent.com/90033/117972614-a3eb3b00-b32b-11eb-9188-02e733a5baa0.png)

Adding a video:

![image](https://user-images.githubusercontent.com/90033/117972847-edd42100-b32b-11eb-9573-3ad2060338c2.png)

I've also tried using Objectbricks and Fieldcollections in Data Objects and faced a lot of issues. I deleted my test scenario for this cases. I think this needs general testing without suppressing PHP warnings.

Version: v10.0.0|015320be1d3358417fd9250a8ee936decd00d710

**Comment by dvesh3** [comment]
Fixed by #9105
