### ISSUE TITLE
Pimcore 6.9 on PHP 8 don't install/compatible | upgrade to X process

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#9111]
Hello,

Running install of Pimcore 6.9 with PHP 8 using:

```
composer -v create-project pimcore/skeleton:"2.8.17"
```

Bring the error:

![image](https://user-images.githubusercontent.com/9025839/118192266-2c5dfe80-b446-11eb-8dbd-39f68ee39134.png)

Is Pimcore 6.9 compatible with PHP 8 ? The doc says Pimcore 6.9 is PHP 8 compatible (https://pimcore.com/docs/pimcore/6.9/Development_Documentation/Installation_and_Upgrade/System_Requirements.html).

This is not a real problem in itself if not, just the documentation for 6.9 can be specifying this.
I was thinking more of migrating an existing Pimcore 6.9 to Pimcore X, we need to switch to PHP 8 (as it is required) before making the upgrade I imagine. But as Pimcore 6.9 don't seem compatible... so how to pass from Pimcore 6.9 to Pimcore 8. Maye, the upgrade doc should explain this and assert that switching on PHP 8 before upgrading is OK even if Pimcore 6.9 is not compatible (could be explained here: https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/Updating_Pimcore/V6_to_V10.html)

Thanks.

nb: by the way, I tried to install fresh Pimcore X on PHP 8 / Mariadb 10.5, all went fine, really big thanks : ))

**Comment by brusch** [comment]
@Yivan `6.9` doesn't support PHP 8  - the docs just haven't been updated at the time PHP 8 was released. 
The reason why `6.9` can't support PHP8 is mostly caused by 3rd party dependencies which cannot be upgraded without a BC break, such as the Doctrine Migrations library and others. 

I've updated the docs & `composer.json` accordingly, see #9114

**Comment by Yivan** [comment]
Thank you for the explanations.
