### ISSUE TITLE
[Pimcore X] Put 0 step/days in system settings, don't display value after reload.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#9122]
Hello,

On Pimcore X, tester on last demo version, if 0 is put for day for document for instance, after reloading the system settings the field is empty.
It should display 0.

To reproduce, set 0 and save:

![image](https://user-images.githubusercontent.com/9025839/118293197-b30feb80-b4d9-11eb-96ea-a347f48b79fd.png)

Reload Pimcore, field is empty:

![image](https://user-images.githubusercontent.com/9025839/118293290-cb800600-b4d9-11eb-905c-a215c9937db2.png)

settings.yaml is well updated, this is more a displaying problem I think (null or 0 leave the field empty, but empty or 0 is not the same things now, one is for unlimited the other for none).

It impacts day and step for document/asset/object.

This can lead to lost initial 0 settings, because resaving with empty field can restore the value to null where the user could have setted it to 1 before.

Thanks.

**Comment by brusch** [comment]
Fixed by #9128
