### ISSUE TITLE
Older docs no longer available

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#9132]
### Expected behavior

Older documentation still available.

### Actual behavior

Only Pimcore X is documented:

![image](https://user-images.githubusercontent.com/279826/118484340-644f9500-b717-11eb-8a87-83f127ce3e87.png)

**Comment by fashxp** [comment]
What docs page? Seems you are on a page that is only available in Pimcore X

**Comment by NiklasBr** [comment]
https://pimcore.com/docs/pimcore/current/Development_Documentation/Documents/Working_with_PHP_API.html

**Comment by fashxp** [comment]
![image](https://user-images.githubusercontent.com/8792145/118485365-a2998400-b718-11eb-8446-784108140285.png)

maybe your browser cache?

**Comment by dvesh3** [comment]
@NiklasBr I guess you are looking at a page which was introduced on Pimcore X i.e. https://pimcore.com/docs/pimcore/current/Development_Documentation/Deployment/Configuration_Environments.html
