### ISSUE TITLE
[Discussion][CustomReports] Do not make Adpater classes final

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#9134]
usecase: more specific sql reports, e.g. [TermSegmentBuilder](https://github.com/pimcore/customer-data-framework/blob/d3f0cf191f23afaa0b0b9c1fd648a3ba6a40da1c/src/CustomReport/Adapter/TermSegmentBuilder.php#L22)

**Comment by brusch** [comment]
Let's tag them `@internal`.
