### ISSUE TITLE
Deeplink multiple browser tabs show same content

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#9135]
Someone opens 2 deep links:
a) https://demo.pimcore.com/admin/login/deeplink?document_136_page
b) https://demo.pimcore.com/admin/login/deeplink?document_66_folder

Both browser tabs will show link (b)

https://user-images.githubusercontent.com/13643455/118486230-a8439980-b719-11eb-8eb6-82f7ae77b42f.mp4

**Comment by fashxp** [comment]
this is a race-condition. Need to wait, until Pimcore is properly loaded before opening the next deeplink.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
