### ISSUE TITLE
[Data Objects] Relation fields inside localized fields loss data when saved as draft

### ISSUE THREAD

**Issue by ramundomario** [pimcore/pimcore#9136]
# Bug Report

IMPORTANT: DO NOT SUBMIT ISSUES WHICH WERE NOT VERIFIED ON THE LATEST VERSION OF PIMCORE! 
Bug reports that do not meet the conditions listed below will be closed/deleted without comment.

- [X] Do not submit reports for unsupported versions, supported versions can be viewed here https://github.com/pimcore/pimcore/milestones
- [X] This is not a security issue / vulnerability -> use [this form](https://pimcorehq.wufoo.com/forms/pimcore-security-report/) instead
- [X] Behavior is reproducible on https://demo.pimcore.fun/admin/ (admin/demo)
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...)
- [X] You're not able to fix the problem yourself and send us a pull request instead of filing an issue.
- [X] There's no existing ticket for the same issue
- [X] Remove unused sections from below and this bullet points, submit only clean reports

### Expected behavior
Save (as draft) object with updated data in a relation field inside localized fields & see changes
### Actual behavior
Save (as draft) object with updated data in a relation field inside localized fields & loss changes 
### Steps to reproduce

1. Add a relation field inside localized fields (Tested with Many-To-One Relation & Many-To-Many Relation)
![Screenshot from 2021-05-17 16-12-19](https://user-images.githubusercontent.com/16133208/118504164-93700180-b72b-11eb-94cf-267adc31ad03.png)
2. Add an initial data to relation field (pdf-test.pdf)
3. Replace relation field data (pdf-test_1.pdf)
![y0P1qm8Ca6](https://user-images.githubusercontent.com/16133208/118504119-8a7f3000-b72b-11eb-8bd4-30c735e799d7.gif)

After saving the object as a draft and reloading, the text field (title) shows the updated data, while the relational field shows the old data 
In addition: when the object is saved and published, the old data are saved.

Found on Pimcore 6.9 but also reproduced on Pimcore X

**Comment by ramundomario** [comment]
Since it's a huge bug,

**Comment by ramundomario** [comment]
@brusch since it's a bug, will be fixed also in 6.9?

**Comment by brusch** [comment]
Fixed by #9159
