### ISSUE TITLE
Custom download on asset images is sometimes broken using Firefox/Safari

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#914]
We have found a strange bug.
On the demo site, if you upload the following two assets:

[assets-for-testing.zip](https://github.com/pimcore/pimcore/files/511589/assets-for-testing.zip)

After you open each one, and try to download it (the "view" tab) on Firefox or Safari (problem does not occurs with Chrome), the file "senzo-rgb-300dpi-no-icc-3508x2480-jpeg-exported-for-the-web-quality-100.jpg" wil be ok, but the otehr file "senzo-rgb-300dpi-no-icc-3508x2480-jpeg-direct-saving-quality-12.jpg" won't download (it start and abort).
For your test you can try "Resize by width" and select 800px for instance, and after click "Download".

The only difference between the two file is the saving options on photoshop. The one wich work good has been saved using "save for the web", the one wich work not has been save with the classic "save" option of the photoshop menu (no fancy option selected, just save, no icc embeded). We tried different DPI but the problem is always here.
And what is more strange is that it download good with Chrome but not with Firefox PC-MAC/Safari MAC (tested on different computer so this is not a specific computer problem).

Here is the PSD (if you have Photoshop to test the two saving options):

[senzo-rgb-300dpi-no-icc-3508x2480-psd-without-layers.zip](https://github.com/pimcore/pimcore/files/511601/senzo-rgb-300dpi-no-icc-3508x2480-psd-without-layers.zip)

As complementaty information, i can give you the envronment of photoshop:
•         Photoshop CC 2015.5.0
•         Mac OS X El Capitan, version 10.11.5
This is graphical station, all software stable and legal, and the "save" options of photshop has been used many times for our project and we didn't encounter those problem with other CMS.

If you need more information I will be happy to provide it to you to help tracking this bug.
Thanks a lot.

**Comment by Yivan** [comment]
Here are some complementary information about how the two files have been seved on Photoshop:

The one wich download ok (saving for the web):

![screenshot-photoshop-jpeg-export-for-the-web](https://cloud.githubusercontent.com/assets/9025839/19120540/5facdbfe-8b23-11e6-9621-14781bfb7e22.png)

The one which download don't work (saving normal):

![screenshot-photoshop-jpeg-direct-saving](https://cloud.githubusercontent.com/assets/9025839/19120565/734d86f4-8b23-11e6-8b0e-b94c15db6783.png)

**Comment by brusch** [comment]
@Yivan which download button are you using? 
There are just too many of them with different functionalities ;-) 
Thanks

**Comment by brusch** [comment]
Memo: check also #915 when testing.

**Comment by Yivan** [comment]
Thanks brush, here is a screenshot with the button indicated by the red arrow:

![bouton](https://cloud.githubusercontent.com/assets/9025839/19122114/5c054b7a-8b29-11e6-9f5c-b6fffa952eb0.png)

**Comment by brusch** [comment]
Thanks for clarifying!
