### ISSUE TITLE
[Pimcore X] New debug system based on symfony and email debug too tighted + dev bundle registration.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#9141]
Hello,

On Pimcore X, now debug mode is tightly tied to Symfony debug mode, and the debug email rely on this state. It makes it difficult to handle those separately... in fact I didn't manage : )

Use cases are:
- I want to active real 404/500 page (no debug mode) but keep emails in debug mode. For instance, for staging environment where customer wants to see/show to their direction the beautiful 404 page designers work hard on it (and not seeing Symfony debug information during pre-showcase!), but for sure we don't want sent emails to real customers !
- I am a developer or a project manager and I want to check, the errors designed page is ok and works fine, but I don't want to trigger real emails during my recipe.
- I am in production, I need to debug an email problem and make some touchy test, so I want to redirect emails on debug email but I don't want to display errors on production
- I am in production, I want to display errors (i configure firewall so just me can access), but I don't want customer lost cronjobs emails (i don't want they go to debug email address)

All of this could arrive one day or another (we had those needs several times).

On Pimcore X the only way I found to get something more fluent for developers/debuggers, is to:
- remove `isDebug` from the condition here : https://github.com/pimcore/pimcore/blob/10.x/lib/Kernel.php#L328 so dev bundles are available even in non-debug mode
- playing with APP_DEBUG=0 or APP_DEBUG=1 in .env.local
It works fine, as well if dev & stage environment for instance are in `getEnvironmentsForDevBundles`, a developer can easily switch debug/no debug to test the real errors page, but with the risk of sending email to real people during those test ! : (( He has to be careful, but it works.

_We needed to remove the condition isDebug because it prevents disabling debug mode on dev environment... (if we set APP_DEBUG=0 on dev environment, Symfony is not happy because he needs the profiler, and developers must change config yaml to adapt them, not really friendly...). This way he can just with a variable enable/disable debug mode (a little like Pimcore 6 with the BO checkbox)._

So this help a little to facilitate those use cases, but always risky concerning email delivery.

**To summarise, this issue is about two things:**
- removing isDebug condition `lib/Kernel.php`, `getEnvironmentsForDevBundles` should be sufficient and it helps switch debug mode off/on with APP_DEBUG.
- maybe add a separate setting for email debugging and modifying slightly doRedirectMailsToDebugMailAddresses here : https://github.com/pimcore/pimcore/blob/10.x/lib/Mail.php#L223, so we can display real error page without redirection email (or redirecting emails but not displaying errors).

Those are just a suggestion and purpose of this issue is to show practical aspect of those tightly coupled debug mode/email debug, and difficulty a developer can arise wanting to switch a dev envrionnement with real errors the way you register dev bundles in lib/kernel.php.

Thanks for reading this long text !
I hope I am not alone in those use cases : )

**Comment by Yivan** [comment]
Just a side things, maybe related to this or maybe a separate issue should be opened:

- Symfony way to check 404 page doesn't seem to work - http://localhost/index.php/_error/404 (please see: https://symfony.com/doc/current/controller/error_pages.html#testing-error-pages-during-development)
- When switching to APP_DEBUG=0 and non-prod envrionnement (using the trick to enable dev bundle even if isDebug is false), we got the Symfony 404 page and not the Pimcore one set in back-office by system settings (or advanced site settings).

This last one makes it for now impossible to render real 404 pages on envrionnement registered as dev environment, so this is a little problematic.

**Comment by dpfaffenbauer** [comment]
why not just disable mail sending on staging with some kind of symfony mailer plugin? I don't really see a big problem here for Pimcore...

**Comment by brusch** [comment]
> I want to active real 404/500 page (no debug mode) but keep emails in debug mode. For instance, for staging environment where customer wants to see/show to their direction the beautiful 404 page designers work hard on it (and not seeing Symfony debug information during pre-showcase!), but for sure we don't want sent emails to real customers !   

see: https://symfony.com/doc/current/mailer.html#always-send-to-the-same-address

> I am a developer or a project manager and I want to check, the errors designed page is ok and works fine, but I don't want to trigger real emails during my recipe.   

see: https://symfony.com/doc/current/mailer.html#disabling-delivery

> I am in production, I need to debug an email problem and make some touchy test, so I want to redirect emails on debug email but I don't want to display errors on production   

Use the Symfony way, set an env var, e.g. based on your IP address: 
```
SetEnv APP_ENV prod
<If "-R '56.26.55.65">
    SetEnv APP_ENV dev
</If>
```

> I am in production, I want to display errors (i configure firewall so just me can access), but I don't want customer lost cronjobs emails (i don't want they go to debug email address)   

Sorry, don't get your point 😉
But maybe the above solutions work for this as well.

**Comment by Yivan** [comment]
**1- Mail: resolved**

@dpfaffenbauer @brusch Thanks for your advice on how to disable emails.

For security we use variable for email credentials `main: '%env(MAILER_DSN)%'`, coupled to a .env.local git excluded with:

```
APP_DEBUG=1
MAILER_DSN=smtp://user:pass@smtp.example.com:port
```

So disabling with `null://null` is a nice solution.

---

**2- Desactivate debug mode on dev environment: not resolved**

@brusch What do you think of the second problem I mentioned, the fact that for environment in `getEnvironmentsForDevBundles ` this is not possible to disable debug_mode easily on dev environments ?

It is easy to reproduce:
- install pimcore/skeleton
- set APP_ENV=dev and APP_DEBUG=0

It brings the following error:

`Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: There is no extension able to load the configuration for "web_profiler" (in "/var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/Resources/config/pimcore/dev.yml").`

Proposition:

Removing the `isDebug` in the condition here: https://github.com/pimcore/pimcore/blob/10.x/lib/Kernel.php#L328
This is more a Pimcore side problem, because Symfony handle well the fact to have APP_ENV=dev and APP_DEBUG=0. Pimcore break this.
Having `getEnvironmentsForDevBundles` makes sense has it is tightly coupled to config yaml file where profiler/dev tools are declared. But `isDebug` is a runtime parameter.

**And thinking more globally, if dev environment doesn't work in non-debug mode, why using a supplementary option to check if isDebug, because actually it can only work in debug mode, so this is always `true`, and this isDebug prevent just from making it work in non-debug mode...  ? : )) `getEnvironmentsForDevBundles` should be self-sufficient ?**

_(there already solutions to make it work by adapting config: forcing registering dev bundles for wanted environment in config/bundles.php or Kernel.php, adapt dev config yaml, etc. but purpose here is to bring Pimcore working out of the box to switch APP_DEBUG)._



**Side problem (maybe separated issue?):** with APP_ENV=dev and APP_DEBUG=0, in case 404 error, the Symfony prod 404 page is shown, not the Pimcore 404 page configured, I think there is something to fix/improve here ? (maybe the 404 Pimcore page relies on getEnvironmentsForDevBundles and not APP_DEBUG, will be better it uses APP_DEBUG I think). Reproductible with the pimcore/demo.

Thanks!

**Comment by Yivan** [comment]
To finish this thread and those interested, the last problem which was trying to display Pimcore error page on DEV environment, you need to set `render_error_document: true` in your config_dev.yaml for instance (it is set to false in pimcore vendor dev.yml file). It is not documented anywhere (neither pimcore documentation, nor as comment in config/config.yaml... needed to dig through the code).

So to summarise, just after a fresh Pimcore install it is possible to display Pimcore 404 page on development environment by:
- Set APP_DEBUG to 0
- Register `\Symfony\Bundle\DebugBundle\DebugBundle` and `\Symfony\Bundle\WebProfilerBundle\WebProfilerBundle` in Kernel.php or `config/bundles.php` for dev environment (because the fact to set APP_DEBUG to 0 prevent them from being registered https://github.com/pimcore/pimcore/blob/10.x/lib/Kernel.php#L328) 
- Set `render_error_document: true` in config/config.yaml or the project config_dev.yaml (like this in pimcore -> error_handling node https://github.com/pimcore/pimcore/blob/10.x/bundles/CoreBundle/Resources/config/pimcore/dev.yml#L31)

And this is good! : )

If you prefer displaying/use Symfony prod 404 page and use those (https://symfony.com/doc/current/controller/error_pages.html) just set `render_error_document: false`.
