### ISSUE TITLE
Tag::getElementsForTag -> Undefined array key

### ISSUE THREAD

**Issue by aKugler** [pimcore/pimcore#9146]
Moin Moin!

Since I only use Pimcore to think outside the box, I'm not sure if this is a bug or I just made a mistake. I have tried to output all specifically tagged documents. I used Tag::getElementsForTag($tag, 'document');, where $tag is an instance tag. Currently this throws an error. Could it be that not el_id but cid should be used here?

![Screenshot_20210518_130404](https://user-images.githubusercontent.com/6008333/118641705-c4f3d600-b7da-11eb-83e0-54bd28b566f0.png)

**Comment by dvesh3** [comment]
Fixed by #9147
