### ISSUE TITLE
Downloading PSD file to JPEG save a broken file

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#915]
On the demo site, upload the following PSD:

[senzo-rgb-300dpi-no-icc-3508x2480-psd-without-layers.zip](https://github.com/pimcore/pimcore/files/511700/senzo-rgb-300dpi-no-icc-3508x2480-psd-without-layers.zip)

After open it on Pimcore, and on the "view" tab, download (keeping same size, to jpeg, not chaning default quality/DPI). The resulting JPEG is corrupted. If it is open on photoshop we get a message:

![screenshot-opening-corrupted-pimcore-export-from-psd-file](https://cloud.githubusercontent.com/assets/9025839/19121674/9bb10efa-8b27-11e6-9846-f98f4ad4924f.png)

(wich translate to: "This document may be damaged (the file may be truncated or incomplete). Continue ?")
If you open it (on mac or on PC - better viewed with Irfanview as the windows viewer fill it with plain color), if you zoom in the bottom-right there is graphical corruption. It can be better seen on PC by doing a resize by width of 1000px before clicking "download" on Pimcore.

So it seems the PSD to JPEG bring a broken file in output.

If needed, here is the corrupted file (so resulting from download in Pimcore):
[senzo-rgb-300dpi-no-icc-3508x2480-psd-without-layers-corrupted.zip](https://github.com/pimcore/pimcore/files/511719/senzo-rgb-300dpi-no-icc-3508x2480-psd-without-layers-corrupted.zip)

Problem occurs on PC and MAC, Chrome/Friefox/Safari (we didn't test others).

If you need more information, don't hesitate.
Thanks

**Comment by brusch** [comment]
I think this is actually the same problem as in #914 
Again, which download button are you using? If the custom download, which settings?

**Comment by Yivan** [comment]
Yes problem is maybe linked, but between this issue and #914, this is not totally the same thing.
This one is about PSD -> JPEG, and #914 is just JPEG -> JPEG.

Same bouton than #914.

You can make all you test with:
- JPEG
- Resize by width
- 1000 pixels (or leave original size when PSD -> JPEG as it brokes too)
- Quality: 95
- DPI: 300

**Comment by brusch** [comment]
As assumed: this was exactly the same problem as #914
