### ISSUE TITLE
pimcore_image without class

### ISSUE THREAD

**Issue by mediafant** [pimcore/pimcore#9154]
# Bug Report

### Expected behavior
That there is the css-class in Frontend which I define in code like:

`{{ pimcore_image('sectionVideoCoverImage', { thumbnail: 'sectionVideoCoverImage', class: 'mfSectionVideoCoverImage mfImg-w100' }) }}`

`<picture >
	<source srcset="/image-thumb__2__sectionVideoCoverImage/Screenshot_20201227_222628.webp 1x, /image-thumb__2__sectionVideoCoverImage/Screenshot_20201227_222628@2x.webp 2x" type="image/webp" />
	<source srcset="/image-thumb__2__sectionVideoCoverImage/Screenshot_20201227_222628.png 1x, /image-thumb__2__sectionVideoCoverImage/Screenshot_20201227_222628@2x.png 2x" type="image/png" />
	<img class="mfSectionVideoCoverImage mfImg-w100" src="/image-thumb__2__sectionVideoCoverImage/Screenshot_20201227_222628.png" width="70" height="100" alt="" loading="lazy" />
</picture>`

This works before in 6.9.3
In Documentation 6.9.3: "You can also pass every valid <img> tag attribute (w3.org Image), such as: class, style"
https://pimcore.com/docs/pimcore/6.9/Development_Documentation/Documents/Editables/Image.html

### Actual behavior

`<picture >
	<source srcset="/image-thumb__2__sectionVideoCoverImage/Screenshot_20201227_222628.webp 1x, /image-thumb__2__sectionVideoCoverImage/Screenshot_20201227_222628@2x.webp 2x" type="image/webp" />
	<source srcset="/image-thumb__2__sectionVideoCoverImage/Screenshot_20201227_222628.png 1x, /image-thumb__2__sectionVideoCoverImage/Screenshot_20201227_222628@2x.png 2x" type="image/png" />
	<img src="/image-thumb__2__sectionVideoCoverImage/Screenshot_20201227_222628.png" width="70" height="100" alt="" loading="lazy" />
</picture>`

**Comment by brusch** [comment]
@mediafant are you talking about `10..0.0` or `6.9.3`?

**Comment by mediafant** [comment]
@brusch I talk about 10.0.0

**Comment by brusch** [comment]
See: 
https://github.com/pimcore/pimcore/blob/e129e527f5aa871b681a8445f0f9e0113e0ec50d/doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md#L161
and
https://github.com/pimcore/pimcore/blob/e129e527f5aa871b681a8445f0f9e0113e0ec50d/doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md#L166

**Comment by mediafant** [comment]
OK - Sorry
