### ISSUE TITLE
URLSlug should allow all valid URL characters

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#9169]
# Bug Report

### Expected behavior

A URL slug should allow [all URI/URL allowed characters](https://www.ietf.org/rfc/rfc3986.html).

### Actual behavior

Pimcore only allows URLSlugs which are compatible with admin element keys.

### Steps to reproduce

Create a URLSlug which may look like `/product/powerline/>36kVolt`

### Code example
Remove to fix:

https://github.com/pimcore/pimcore/blob/f31a2e44e662e1ca65be446c4145f13a9a7f13b3/models/DataObject/ClassDefinition/Data/UrlSlug.php#L199-L202 

Or add a new section in https://github.com/pimcore/pimcore/blob/cda1a4c6211cb65c7d708af3076f2529cbc6dabb/models/Element/Service.php#L1020 to deal with slugs rather than relying on document key rules.

**Comment by brusch** [comment]
See also #8940

**Comment by brusch** [comment]
Fixed by #9171
