### ISSUE TITLE
Grid filters on date fields with exact date ("On") don't work

### ISSUE THREAD

**Issue by podarcis** [pimcore/pimcore#917]
In grid views/ lists the filters on date fields with an exact date ("On"/ equals) don't work as for the filter value the date portion (date with time 00:00:00) is used and the filter operator is "=". So the condition is never met (except for dates with time 00:00:00).
  
### Expected behavior 
Grid/ list shows entries within the selected date.

### Actual behavior  
Only entries with date values 00:00:00 are shown.

### Steps to reproduce  
1) Create a new object.
2) Set filter on (system) field "Creation date" of type "On" (exact) and select the current day and apply.
3) Recently created object is not shown.

### Partial fix  
The following patch fixes this behavior for system fields (e.g. creation date, modification date), only. A general approach might need some restructuring of present code.

```diff
diff --git a/pimcore/models/Object/Service.php b/pimcore/models/Object/Service.php
index 9a5d6d2..df1b4a9 100644
--- a/pimcore/models/Object/Service.php
+++ b/pimcore/models/Object/Service.php
@@ -784,6 +784,8 @@ class Service extends Model\Element\Service
                     // system field
                     if ($filterField == "fullpath") {
                         $conditionPartsFilters[] = "concat(o_path, o_key) " . $operator . " " . $db->quote("%" . $filter["value"] . "%");
+                    } elseif ($filter["type"] == "date" && $filterOperator == "eq") {
+                        $conditionPartsFilters[] = "`o_" . $filterField . "` BETWEEN " . $db->quote($filter["value"]) . " AND " . $db->quote($filter["value"] + 86400 - 1);     // from 00:00:00 to 23:59:59
                     } else {
                         $conditionPartsFilters[] = "`o_" . $filterField . "` " . $operator . " " . $db->quote($filter["value"]);
                     }
```

Fix provided by my colleague Jürgen Hecht.

**Comment by mrudnicki** [comment]
Thanks!
