### ISSUE TITLE
[Bundles] Bundle in /src not listed on Admin

### ISSUE THREAD

**Issue by iidaloiki** [pimcore/pimcore#9173]
# Bug Report

### Expected behavior

When I add a bundle that extends Pimcore\Extension\Bundle\AbstractPimcoreBundle, it should show in admin Bundles & Bricks list.

### Actual behavior

Bundle is not found on the list, and can't be enabled nor installed.

Paths tried:

src/BundleName (includes BundleName.php that extends AbstractPimcoreBundle)
src/Vendor/BundleName (includes VendorBundleName.php that extends AbstractPimcoreBundle)

### Steps to reproduce

1. Create bundle folder `XBundle` in `src`
2. Create bundle file `XBundle.php` in `XBundle`
3. Paste following code to have basic code setup
4. Check bundle list - not found

(This is very simplified example of my issue - problem is that when I'm trying to test my bundle created in Pimcore 6.9, that of course has loads of other content - configs, services etc. - it is not found on Pimcore X when put to `src`. Clearing caches does not affect the issue.)

### Code example
```php
<?php

namespace XBundle;

use Pimcore\Extension\Bundle\AbstractPimcoreBundle;

class XBundle extends AbstractPimcoreBundle
{

  /**
   * {@inheritdoc}
   */
  public function getNiceName()
  {
      return 'Bundle X';
  }

  /**
   * {@inheritdoc}
   */
  public function getDescription()
  {
      return 'Makes things';
  }

  /**
   * {@inheritdoc}
   */
  public function getVersion()
  {
      return '1.0';
  }
}
```

_edit._
# Solution
You should also add the bundle to autoloader in `composer.json`:

```json
"autoload": {
    "psr-4": {
      "XBundle\\": "src/XBundle/",
    }
  },
```

**Comment by NiklasBr** [comment]
Is it registered in `pimcore/app/AppKernel.php` (or `src/Kernel.php` if Pimcore X)?

**Comment by iidaloiki** [comment]
@NiklasBr 
> Is it registered in `pimcore/app/AppKernel.php` (or `src/Kernel.php` if Pimcore X)?

That shouldn't be needed according to [documentation](https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/Pimcore_Bundles/index.html):

> The bundle shows up in the extension manager and can be enabled/disabled from there. Normal bundles need to be registered via code in your Kernel.php.

I did not do that in 6.9 and it showed up automatically.

Though now I tried to add it into Kernel.php, but it still does not show in Bundle list.

**Comment by brusch** [comment]
Thanks should work, but only if you're following the recommended naming scheme of the class. 
Actually Pimcore looks for files ending with `Bundle.php`: 
https://github.com/pimcore/pimcore/blob/2f18a0f26380c56b609d937b40d2050c8d1a3e1a/lib/Extension/Bundle/PimcoreBundleLocator.php#L112

**Comment by iidaloiki** [comment]
@brusch 

Forgot about that, fixed example.

However, when I renamed my example to form XBundle, it still does not show. And neither does the bundle I originally came across this problem with, which has Bundle at the end of name, and it showed on previous version of Pimcore.

Is there something else I'm missing? How is the path defined? It should default to `src/`, but how can I make sure it checks that folder?

**Comment by brusch** [comment]
@iibs I think the easiest to debug this would be to just put a break point at the line above an see what's happening there. Thanks!

**Comment by iidaloiki** [comment]
@brusch 

Did some debugging, and it seems that the classes are actually found! Problem is in function `processBundleClass()`:

https://github.com/pimcore/pimcore/blob/2f18a0f26380c56b609d937b40d2050c8d1a3e1a/lib/Extension/Bundle/PimcoreBundleLocator.php#L175

For some reason, class_exists check does not go through, and therefore it is not added to the list.

Do you have any insight how could I fix it?

**Comment by brusch** [comment]
@iibs seems to be related to the autoloader. Pimcore uses Composer to autoload classes, so check your `composer.json` 😉

**Comment by iidaloiki** [comment]
@brusch Thank you so much, updating composer.json helped! Closing the issue, since the problem was me all along 😄

**Comment by ARY112** [comment]
@iibs, What change u made exactly in composer.
I am facing the same issue after upgrading to version 10.
In Pimcore version 6.9 ,my bundles were in src folder and in composer autoload  "": ["src/"], was used so all bundles were getting registered  without any issue and respective services from were running .

After migration to Pimcore 10 , my bundles are not registered bcz of composer autoload change  "App": ["src/"],
So i changed the namespace and added App in all the bundle classes namespace so they got registered but services are not working now due to dependency injection name space constraint.

Can you please let me know ur composer change
