### ISSUE TITLE
Cannot edit / open target groups

### ISSUE THREAD

**Issue by BerkeAras** [pimcore/pimcore#9176]
# Bug Report

### Expected behavior
Users should get more information about target groups and should be able to edit them. 

### Actual behavior
Error `Uncaught Error: Duplicate component id "pimcore_target_groups_panel_undefined"`

### Steps to reproduce
Login to the demo (https://demo.pimcore.fun/admin/?perspective=default) (admin/demo), go to:
**Marketing** / **Personalization / Targeting** / **Target Groups**, click on am item

**Comment by brusch** [comment]
Fixed by #9214
