### ISSUE TITLE
Change sitemap dir

### ISSUE THREAD

**Issue by aKugler** [pimcore/pimcore#9197]
Hi!

The sitemap generator continues to write to the old web dir even with Pimcore X. Is it possible to store the files under public? In config or via an argument in the cron or something. 
Currently, the integration is still considered experimental. Is there already a plan for when this functionality will leave this stage behind?

Best regards

**Comment by dvesh3** [comment]
@aKugler dir override is removed, so now it should generate in default public dir only. Also, you can change dir by passing target argument like `bin/console presta:sitemaps:dump /www/web`.

Experimental notice was just a leftover in docs so remove it 😉

**Comment by dvesh3** [comment]
fixed by #9219
