### ISSUE TITLE
Inefficient CoreHandler sorting

### ISSUE THREAD

**Issue by kkarkus** [pimcore/pimcore#9202]
Please take a look at the comparison before and after fix https://blackfire.io/profiles/compare/edb45994-14d5-4dca-9b2a-980c6a95968a/graph

Original graph: https://blackfire.io/profiles/fb38771b-cb38-4e36-9d81-39b6459a9f15/graph

The temporary fix is available here: https://github.com/pimcore/pimcore/pull/9199
But it breaks unit tests and I have no time to prepare it correctly.

Sorry I put the wrong comparison, but either way, you can see there're 10 million~ calls for 3400~ elements

**Comment by brusch** [comment]
Fixed by #9227
