### ISSUE TITLE
Bug: 404 MultiSelect.js not found called via startup.js

### ISSUE THREAD

**Issue by ITspirit** [pimcore/pimcore#9206]
# Bug Report

Just noticed, that i have a 404 with PimcoreX on Request of "/admin/ext/ux/form/MultiSelect.js"

Looks this is the reason (and the file isn´t present on this location):

Initiator: AdminBundle/Resources/public/js/pimcore/document/edit/startup.js

```php
Ext.Loader.setPath('Ext.ux', '/bundles/pimcoreadmin/js/lib/ext/ux');

Ext.require([
    'Ext.dom.Element',
    'Ext.ux.form.MultiSelect'
]);
```

**Comment by ITspirit** [comment]
Bogus.

**Comment by github-mayur** [comment]
@ITspirit  I have the same issue. How did you solve it?
