### ISSUE TITLE
Implement key=>value pair for Predefined Asset Metadata fields of type "select"

### ISSUE THREAD

**Issue by ab-kily** [pimcore/pimcore#9210]
# Feature Request
- [x] There is no existing issue regarding the same topic

## Feature description

It would be great tо allow configuration of Predefined Asset Metadata fields of type `select` to be configurable as key=>value pair using, for example, JSON format (or any other) like this:
```json
{"Select option 1": 1, "Select option 2":2, "Select option 3":"aaa"}
```

So, in Admin UI we could choose required option by its label (key):

![image](https://user-images.githubusercontent.com/9202344/119474357-bb2b1f00-bd54-11eb-89d8-059d7f36a8ea.png)

And in backend we could use value according to its key:

```php
$asset = Asset::getById(123);
$metadata = $asset->getObjectVar('metadata');
echo $metadata[0]['data']; // Output: "1"
```

**Currently**, we can only use simple comma-separated list to configure "select" type of field:

```
Select option 1,Select option 2,Select option 3
```

And backend will return the same selected label name in "data" field:

```php
$asset = Asset::getById(123);
$metadata = $asset->getObjectVar('metadata');
echo $metadata[0]['data']; // Output: "Select option 1"
```

Are there any plans to implement key=>value list for such fields? Will it be a breaking change? If not, I think I could try to implement it by providing pull request.

**Comment by fashxp** [comment]
no plans yet, with [Enterprise Metadata](https://pimcore.com/docs/asset-metadata/current/) this would be possible. 

if, we would also have to change that for the properties, as this is the same principle.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
