### ISSUE TITLE
Can't reset number inputs via batch update to null value

### ISSUE THREAD

**Issue by rubanooo** [pimcore/pimcore#9223]
# Bug Report

### Expected behavior
When entering an empty value in a number field in the batch update operation, the value should be reset to null

### Actual behavior
When batch updating a selection of objects in the grids, inserting an empty value results in the value being '0' instead of null

**Comment by dvesh3** [comment]
@rubanooo sorry, not able to reproduce on ver.1.0.1. could you please share exacts steps? thanks!

**Comment by dvesh3** [comment]
Closing it due to no response. please feel free to come back with exact steps to reproduce. thanks!
