### ISSUE TITLE
[Bug] Missing Pimcore 10 migrations

### ISSUE THREAD

**Issue by skoch-twocream** [pimcore/pimcore#9226]
I currently update the Pimcore for our Enterprise customer. Not sure if I missed something?

Where is this **migration** in the pimcore 10 (x) release?
https://github.com/pimcore/pimcore/blob/541196ccf9b129a688628a9e67eb549c05196cf2/bundles/CoreBundle/Migrations/Version20210303165115.php

I also cannot find the migration of the "translations_messages" table.

The table schemas are only available in the installer.sql:
https://github.com/pimcore/pimcore/blob/10.x/bundles/InstallBundle/Resources/install.sql#L550

For now I copied the SQL out of it.

**Comment by brusch** [comment]
See https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/Updating_Pimcore/V6_to_V10.html

> If you're on a version between 6.0.0 and 6.8.x, then please update to 6.9.x first and then continue with the upgrade steps.

**Comment by skoch-twocream** [comment]
Thanks for the fast response 🚀 . Damn I missed the step. But I thought that the instance is not already so old :-D

Let's start again :-)
