### ISSUE TITLE
Classe name change causes issues

### ISSUE THREAD

**Issue by MagPim** [pimcore/pimcore#9260]
# Bug Report

### Expected behavior
When changing the name of a class, everything is normally handled correctly by Pimcore (at least in previous versions).

### Actual behavior
An error message appears as seen below
![Pimcore class renamed error](https://user-images.githubusercontent.com/39189262/119948040-b787da00-bf98-11eb-88c4-94beb8cfafac.PNG)
Note that I could fix the problem by clearing all cache and temporary files, this is probably the part missing in the actual code.

### Steps to reproduce
I reproduced the problem on the demo site. I created a new class and a new instance with at least one field completed. 
I changed the name of the class and saved. 
When I try to work on the object created, I get the error message. 

### Code example
```php
// your code
```

# Feature Request

**Comment by dvesh3** [comment]
Regression of https://github.com/pimcore/pimcore/pull/7635
