### ISSUE TITLE
Object Relation Data-Types: Display individual text in editing form instead of the path

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#927]

**Comment by brusch** [comment]
See: 
1ffde77f2e506c7c4fb6475ca5fb23efa7b36f56
cd1e8e5af4289d8ca0eb7f47e465fee3065725a6
5fc9ed718040a3492ac6b4284b466592312b66ab
47cbcbf8649f1ba96031ea3c25a460bfe881bdb9
094074bd7604c6e15884edcc4760d181446a45c9

**Comment by Yivan** [comment]
:+1: 
So great feature! Thanks for this really nice and useful improvement.
