### ISSUE TITLE
Saving an unpublished object/validation message publish it on the tree (visuel effect)

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#928]
On the Pimcore demo (build 3985), edit the class "person" and add a text field named "mytext" with a regular expression [a-zA-Z]+, like on the following screenshot:

![class](https://cloud.githubusercontent.com/assets/9025839/19204111/33e757f6-8cdb-11e6-8e09-c2a38534c027.png)

After open /crm/inquiries/jane-doe.com and **unpublish it**.
Fill in mytext the value "123", and click "Save & Publish". Object will be published on the tree (and it shoud not), but if you refresh the tree it is in fact always unpublished (so ok). Here is a screenshoot for better explaination:

![edit](https://cloud.githubusercontent.com/assets/9025839/19204229/db7892fa-8cdb-11e6-92fd-3198c1b89122.png)

I was thinking it was linked to https://github.com/pimcore/pimcore/issues/903, but has it has been resolved in build 3985, i think it is another bug.
I tryed only with object, but maybe same with others (document/asset).

Thanks! (and sorry submitting many things those last days but we are working actively on a project and we discover those during our tests, so i prefer reporting them as soon as we notice them)

**Comment by mrudnicki** [comment]
Thanks @Yivan I will check it.
