### ISSUE TITLE
[Assets] Error uploading zip file in Assets

### ISSUE THREAD

**Issue by amarjeet6694** [pimcore/pimcore#9281]
Getting this error every-time, while trying to upload ZIP file in Assets.
Verified at [Pimcore Demo Instance](https://demo.pimcore.fun/admin/)

**File**:  [Uploads.zip](https://github.com/pimcore/pimcore/files/6569725/Uploads.zip)

**Error**: 
![Upload_Zip_Error](https://user-images.githubusercontent.com/29056383/120181955-604d6800-c22b-11eb-8c8b-6963cb0e909c.png)

**Comment by weisswurstkanone** [comment]
Observation: zip file contains subfolders with the actual assets inside

**Comment by weisswurstkanone** [comment]
I fear this needs to be fixed for 6.9 as well

**Comment by brusch** [comment]
Fixed by #9305
