### ISSUE TITLE
[DataHub File Export Plugin] Unable to add new filetype to Datahub File export plugin

### ISSUE THREAD

**Issue by amarjeet6694** [pimcore/pimcore#9282]
I tried to add a new filetype **XLSX** (along-with already added CSV, JSON and XML) for DataHub File Export Plugin.
I followed the steps as given in the [documentation](https://pimcore.com/docs/data-hub-file-export/current/Customize_and_Extend.html#page_Additional-Exporter-Types). But was unable to see new filetype being added in the dropdown

When I checked the code(at _vendor/pimcore/data-hub-file-export/src/Resources/public/js/configuration/fileExport/configItem.js_), I found hard-coded _store_ values for filetype.

```
{
	fieldLabel: t("plugin_pimcore_datahub_file_export_delivery_destination_filetype"),
	xtype: "combo",
	name: "filetype",
	value: this.getValue("deliveryDestination.filetype") || 'CSV',
	store: [
		["CSV", "CSV"],
		["XML", "XML"],
		["JSON", "JSON"],
	],
	mode: "local",
	editable: false,
	triggerAction: "all"
}
```

**Comment by fashxp** [comment]
hi, this is not the right place for issues for the enterprise bundles. 
please contact your sales contact person at Pimcore to get access to the corresponding github repositories. 
there we are happy to help you. thanks.
