### ISSUE TITLE
[DataHub File Export Plugin] Incorrect data exported for Table field data for all filetypes

### ISSUE THREAD

**Issue by amarjeet6694** [pimcore/pimcore#9283]
**Steps to Reproduce**
1. Install and setup Datahub File Export plugin
2. Create a new File Export configuration in the DataHub
3. In _Schema Definition_ tab, define a schema for a data class and add a field of type _Table_ in the schema
4. In _Delivery Destination_ tab, Choose any file type (say CSV) and any Delivery Type
5. Configure Process manager to download the file
6. Open the downloaded file to verify the data

**Issue**
Not meaningful data is shown for _Table_ fields.

**Possible Error**
Table field data is stored as _serialized_ and _base 64 encoded_
Example: YTozOntpOjA7YToyOntpOjA7czo2OiJUZXN0IDEiO2k6MTtzOjg6IlNhbXBsZSAxIjt9aToxO2E6Mjp7aTowO3M6NjoiVGVzdCAyIjtpOjE7czo4OiJTYW1wbGUgMiI7fWk6MjthOjI6e2k6MDtzOjA6IiI7aToxO3M6MDoiIjt9fQ==

**Config Images**

![Config-1](https://user-images.githubusercontent.com/29056383/120187902-0fda0880-c233-11eb-92e0-919efeb5ae1d.png)
![Config-2](https://user-images.githubusercontent.com/29056383/120187912-136d8f80-c233-11eb-896e-7c8f461c26d9.png)
![Config-3](https://user-images.githubusercontent.com/29056383/120187920-15cfe980-c233-11eb-81a6-d22de6b33f12.png)
![Config-4](https://user-images.githubusercontent.com/29056383/120187934-18cada00-c233-11eb-89f3-580737fe7eec.png)

**Comment by fashxp** [comment]
hi, this is not the right place for issues for the enterprise bundles. 
please contact your sales contact person at Pimcore to get access to the corresponding github repositories. 
there we are happy to help you. thanks.
