### ISSUE TITLE
[DataHub File Export Plugin] Invalid XML file being downloaded 

### ISSUE THREAD

**Issue by amarjeet6694** [pimcore/pimcore#9291]
I created a _File export_ configuration  that downloads an XML file with schema definition having various types of fields like _table,_ _classification store_, _object bricks_, _field collections_ etc.

The file gets successfully downloaded on my system but doesn't open.
Below is the downloaded XML fiel content 
```
<?xml version="1.0" encoding="utf-8"?>
<data>
  <item>
    <id>769</id>
    <title>Announcement: Documentary Movie about Henry Ford</title>
    <shortText>Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus.</shortText>
    <date>2019-08-26 03:30</date>
    <listData>YTowOnt9</listData>
    <completenessPercentage>90</completenessPercentage>
    <specificStore~sample-group-1~sample-input/>
    <specificStore~sample-group-1~sample-select/>
    <Dimensions~length/>
    <Dimensions~wheelbase/>
    <Transmission~wheelDrive/>
    <Title (News Car)/>
    <Related Cars (News Cars)/>
  </item>
</data>
```

**Possible Issue**
Error is coming as the XML is unable to read the headers defined for
- _Classification Store fields_ (specificStore\~sample-group-1\~sample-input, specificStore\~sample-group-1\~sample-select)
- _Object Brick Fields_ (Dimensions\~length, Dimensions\~wheelbase, Transmission\~wheelDrive)
- _Custom name defined in Field collection extractor operator_ (Title (News Car), Related Cars (News Cars))

**Comment by fashxp** [comment]
hi, this is not the right place for issues for the enterprise bundles.
please contact your sales contact person at Pimcore to get access to the corresponding github repositories.
there we are happy to help you. thanks.
