### ISSUE TITLE
[Workflow] %_locale% placeholder generate Symfony DI error in mailPath workflow config file

### ISSUE THREAD

**Issue by FredoVelcro** [pimcore/pimcore#9303]
https://github.com/pimcore/pimcore/blob/c1ef11c898a23e410add0d2e9afddb4029f38a8f/lib/Workflow/Notification/NotificationEmailService.php#L99

In my workflow php config file, i use %_locale% in the mailPath parameter for Pimcore email notification BUT it fails to resolve and generates this error : 
```text
You have requested a non-existent parameter "_locale". 
Did you mean one of these: "locale", "kernel.default_locale", "cmf_routing.dynamic.auto_locale_pattern"?
```

Sample of my config file : 
```php
...
'notificationSettings' => [
                            [
                                'notifyRoles' => ['MY_ROLE'],
                                'channelType' => ['mail', 'pimcore_notification'],
                                'mailType' => 'pimcore_document',
                                'mailPath' => '/%_locale%/email/my_email_doc'
                            ]
                        ]
...
```

It seems that Symfony dependency injection process takes control over it...

Any idea welcome ;) thks

**Comment by fashxp** [comment]
`%%_locale%%` doesn't work either?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
