### ISSUE TITLE
Variants tab in object shows only default language for classification store values

### ISSUE THREAD

**Issue by niederberger-qw** [pimcore/pimcore#9304]
### Expected behavior
When I click on the Variants Tab in Pimcore on an Object, then I want to see the data with the current language.

### Actual behavior
At the moment there is a bug with the classification store. You see only the default values in the view. (You can edit it and then the new value is in the right language) 
![grafik](https://user-images.githubusercontent.com/85213755/120428341-c3e2ad00-c373-11eb-9a12-308539769f44.png)

On the folders it is working. It's only a problem in the variants tab.

### Steps to reproduce
1. Add a classification store
2. Add a object with classification store and variants in it
3. Add in the classification store any input field
4. Go to the object on the variants tab
5. Add english and german in the pimcore settings

**Comment by weisswurstkanone** [comment]
Hello @niederberger-qw , maybe related to this open PR? 
https://github.com/pimcore/pimcore/pull/9316

**Comment by niederberger-qw** [comment]
Hi @weisswurstkanone not only related. It tries to resolve this bug. I'm a little confused :)

**Comment by dvesh3** [comment]
Fixed by #9316
