### ISSUE TITLE
`get/setChilds()` to `get/setChildren()`

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#931]
- Properties named `*childs` have to remain as they are (migration issues)
- Compatibility layer using a trait
- Flag `get/setChilds()` as `@deprecated` 
- Docs

**Comment by Yivan** [comment]
I was just looking code of this new feature, just i was asking me, is it ok to have the "use" statement in the class definition and not outside ?
See https://secure.php.net/manual/en/language.namespaces.importing.php (Example #5 Illegal importing rule).
I think I am wrong but i prefered to report it now as it is implemented currently.

**Comment by brusch** [comment]
@Yivan http://php.net/trait

**Comment by Yivan** [comment]
Thanks Brush, i was thinking i was wrong, but i prefered to post. I learned something thanks ; )
