### ISSUE TITLE
Custom Layouts cannot be created or installed

### ISSUE THREAD

**Issue by matthiashamacher** [pimcore/pimcore#9318]
# Bug Report
It seems that it is currently not possible to save Custom Layouts or install them via the `pimcore:deployment:clustom-layouts-rebuild`  command. Our Setup is currently on Version 10.0.0 but it is also in the newest Version 10.0.2 as it is reproducible in the demo and skeleton which both are on 10.0.2

### Expected behavior
Custom Layouts could be created and installed

### Actual behavior
When saving a Custom Layout Pimcore throws an error. The same error occurs when you run `pimcore:deployment:custom-layouts-rebuild` to install Custom Layouts

### Steps to reproduce
1. Install the Skeleton
2. Create a new Data Object with i.e. 2 Fields
3. Create a new Custom Layout for that Data Object
4. Try to save the Custom Layout

It's also reproducible in the Demo:
1. Go to demo.pimcore.fun/admin and login
2. Open any Object in the Class Definition
3. Create a new Custom Layout
4. Try to save the Custom Layout

### Error Message
<img width="716" alt="CleanShot 2021-06-03 at 09 50 20@2x" src="https://user-images.githubusercontent.com/32356549/120608144-28276e80-c451-11eb-81ca-6062c9814b32.png">

**Comment by dvesh3** [comment]
Fixed by #9354
