### ISSUE TITLE
Static route doesn't resolve alias for site (subsite)

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#932]
In multi-site, if we define a sub-site `prod.mysubsite.com` with two alias `staging.mysubsite.com` / `dev.mysubsite.com` (for developpement/staging purpose):

![subsitetest](https://cloud.githubusercontent.com/assets/9025839/19282492/e63498ae-8fee-11e6-8edc-e462287bbe94.png)

And after we want to make some route:

![route](https://cloud.githubusercontent.com/assets/9025839/19282538/0af6fe0c-8fef-11e6-809b-e81dd2c0e2b8.png)

We choose the main url (here `prod.mysubsite.com`).

On the frontend (website), if we test the route on `http://prod.mysubsite.com`, it works great. But on the `http://staging.mysubsite.com` and `http://dev.mysubsite.com` the route is not resolved.
So actualy we cannot use routes for a specific subsite working in a dev/stage/prod environnement.

I think this is a bug and the route should resolve for site alias too.
Thanks.

**Comment by Yivan** [comment]
I think there is another problem on the route for multi-module.
Selecting another module name, and after clic on the controller column only show the ones of `default` module, not the one of the choosen module. (maybe same problem on the action column too).
Thanks again.

**Comment by mrudnicki** [comment]
Hi @Yivan 
To make sure that I understood your issue well. 

You created the site with the main domain and additional domains assigned to it:

![image](https://cloud.githubusercontent.com/assets/20395719/19305179/129095ca-9070-11e6-893a-1b4cfb88b7ab.png)

Then you specified a custom route only for these domains:

![image](https://cloud.githubusercontent.com/assets/20395719/19305236/54d36e6c-9070-11e6-9f63-7e8ed320194f.png)

Now in my case, the static route called: "category-example" is accessible only from two domains: http://en.pimcore-v.local/category-example, http://en2.pimcore-v.local/category-example
And this is proper behaviour. 

Which versions have you been using?

**Comment by brusch** [comment]
I can confirm that everything works as expected.

**Comment by Yivan** [comment]
I think maybe in just one sub-site the problem is not here.

In our case we have 3 sub-sites (say site A, site B, site C), each one has a route called sitemap-a, sitemap-b, sitemap-c, wich need to point to the correct module (different for each site: moduleA, moduleB, moduleC), controller, action.
The 3 sites have each one alias for dev/staging.
With such configuration, the sitemap-b and sitemap-c route from an **alias** (not from the main domain) `give moduleA`... the problem is here: wrong module is send back after route resolution. It should give moduleB and moduleC respectively.

So if you tested on a unique module you won't see the problem.
If it is not very clear i can create some screenshot if you want.

**Comment by brusch** [comment]
Yes, please share a screenshot with us ;-)

**Comment by Yivan** [comment]
It is on the last stable Pimcore (4.3.1) (not the nightly build).
Ok thanks, I prepare some screenshoot!

**Comment by Yivan** [comment]
I just double checking, and **it works ok**. It was my fault. I had some debugging code during the route edition and so the modification i had made to the route where not saved in fact. (if the returned json is wrong while editing the routes on the Pimcore GUI, there is no message so it failed sillently: just a console log "[WARN] Unable to parse the JSON returned by the server").
So i was making my test on a not updated routes!
Just try again and works as intented.
I am sorry for this false issue.

Concerning my second comments on this issue:
`Selecting another module name, and after clic on the controller column only show the ones of default module, not the one of the choosen module. (maybe same problem on the action column too).`
This is a really light problem as we can fill controller directly by typing it, but it can make strange to the user to have the website controller in the list when you put a custom module.
Should i open another issue for this or we keep like this ? (maybe so better to replace the select from controller/action to simple text input).
Here a screenshot (simplier ; ) ):

![routemodulectrl](https://cloud.githubusercontent.com/assets/9025839/19307786/9e6f5e3a-907c-11e6-86e8-418ee7ed9184.png)
