### ISSUE TITLE
Retrieving products through Elasticsearch

### ISSUE THREAD

**Issue by TS1997** [pimcore/pimcore#9323]
# Bug Report

### Expected behavior
I expected to get a list of products returned but an error was thrown in Pimcore 10.0.2.

### Actual behavior
I got an error saying _Warning: Undefined array key "relations"_. When following the exception I can see that it comes from [here](https://github.com/pimcore/pimcore/blob/10.x/bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php#L886)

### Steps to reproduce
Retrieve a list of products through Elasticsearch

### Code example
```php
 $indexService = $factory->getIndexService();
 $productList = $indexService->getProductListForCurrentTenant();
 $productList->setVariantMode($productList::VARIANT_MODE_INCLUDE);
 $productList->setCategory($category);
 $params['productList'] = $productList->getProducts();
```

# Feature Request

**Comment by brusch** [comment]
Fixed by #9331
