### ISSUE TITLE
ImageMagick CLI adapter as an alternative for the Imagick library

### ISSUE THREAD

**Issue by mrudnicki** [pimcore/pimcore#933]
* possibility to use the Convert CLI tool instead of the Imagick library
* a configuration by php-di
* the reference to the new class: \Pimcore\Image\Adapter\ImageMagick

**Comment by brusch** [comment]
I'd prefer `ImageMagick` as class name, since `Imagick` is the name of the PHP extension, so this can lead to misunderstandings.

**Comment by brusch** [comment]
There seem to be some issues, especially with transparency, overlays and masks. 
See below: 

![image](https://cloud.githubusercontent.com/assets/142037/19469881/8c1981de-951d-11e6-8249-6bb55b332839.png)

**Comment by mrudnicki** [comment]
Yes, I've already seen it. I'm going to fix these examples.

**Comment by campino2k** [comment]
How can this be used in Pimcore 5?

**Comment by brusch** [comment]
@campino2k unfortunately this isn't possible at the moment, I've created an issue for that, see #2914
