### ISSUE TITLE
FieldCollection with LocalizedFields and non LocalizedFields not savable

### ISSUE THREAD

**Issue by dpfahlbusch** [pimcore/pimcore#9332]
### Expected behavior
You can have multiple FieldCollections with LocalizedFields and non LocalizedFields and can save the object

### Actual behavior
Saving fails with error

### Steps to reproduce

1. Go to current demo
2. Create new FieldCollection without localized field
3. Make it available in News object
4. Add the created FieldCollection to the existing content
5. Try to save it and it will fail with the following exception:

![image](https://user-images.githubusercontent.com/22637136/120785485-7447e100-c52d-11eb-82a3-6efb14c48414.png)

**Comment by weisswurstkanone** [comment]
@dpfahlbusch unable to reproduce this on demo.pimcore.fun. Could you please set up a demo object there? Thx!

**Comment by dpfahlbusch** [comment]
Strange ... tried it the same way as before, but now it works ^^'
