### ISSUE TITLE
Internal Error when retrieving Data Object using fullpath with GraphQL in Datahub

### ISSUE THREAD

**Issue by Wael-Hamdan** [pimcore/pimcore#9333]
### Expected behavior
Get the id of the given data object in the fullpath argument of the query
### Actual behavior
500 Internal Error as shown in the screenshot below.
![image](https://user-images.githubusercontent.com/39374662/120796431-1ae6ae80-c53b-11eb-93e8-8d6b849c1658.png)

Note:It works fine when trying to retrieve a data object by providing its id instead of the fullpath as argument.
### Steps to reproduce
Open any Datahub configuration and try to get a dataobject using its fullpath.
### Code example
#GraphQL
query {
  getCar(fullpath:"/Product Data/Cars/alfa romeo/Giulietta") {
    id
  }
}

**Comment by weisswurstkanone** [comment]
Hello @Wael-Hamdan , which version you are on? I can neither reproduce this on the official demo.pimcore.fun not on our 6.9 instance. Could you please provide the status of the bundle please. Thx!

**Comment by Wael-Hamdan** [comment]
Hello @weisswurstkanone , 

Thanks for your reply.
I am currently using version 6.8.10. The datahub bundle is installed and enabled on our instance.

**Comment by weisswurstkanone** [comment]
Hi @Wael-Hamdan , what is the version of the data hub bundle?

**Comment by Wael-Hamdan** [comment]
Hi @weisswurstkanone 
The version of the data hub bundle is : "dev-master"

**Comment by Wael-Hamdan** [comment]
I just came across the following issue:
https://github.com/pimcore/data-hub/issues/287
 I guess that the problem lies indeed in the chosen version of the datahub bundle.


Can I use any of the officially tagged releases of Datahub with Pimcore 6.8.10?

**Comment by weisswurstkanone** [comment]
yes

**Comment by weisswurstkanone** [comment]
So this can be closed?

**Comment by Wael-Hamdan** [comment]
Thanks for your support. Have a great day.

**Comment by Wael-Hamdan** [comment]
Hello again,
unfortunately, I am still getting the same error even with an officially tagged release of Datahub (0.7).

**Comment by weisswurstkanone** [comment]
Please note that the current release is 1..0.1

**Comment by Wael-Hamdan** [comment]
This was resolved using a more recent release (0.8).
Thanks.
