### ISSUE TITLE
Cant set roles programmatically

### ISSUE THREAD

**Issue by vnecked** [pimcore/pimcore#934]
Hello,

I am trying to set user roles programmatically, but it is not working. I have a script which creates users, puts them into their folders. It also creates the roles.
The code to set a role looks like this:
```
$user->setRoles(array($role->getName()));
$user->update();
```
If I call $user->getRoles(), I am getting the role which I set before, but in pimcore its not updated. Am I doing something wrong?

I am looking forward to hearing from you.

edit:
OK, I figured it out by myself. In setRoles you have to put the IDs of the roles. You can close this request.

**Comment by weisswurstkanone** [comment]
use the role ID instead of the name

**Comment by vnecked** [comment]
thank you for the fast response!
