### ISSUE TITLE
DataObject\Service::getOptionsForSelectField not working with optionsProviderClass

### ISSUE THREAD

**Issue by akno77** [pimcore/pimcore#9340]
# Bug Report

I already created an discussion (https://github.com/pimcore/pimcore/discussions/9172) for this but with no response yet. As far as I see this seems to be a bug.

### Expected behavior

Calling `DataObject\Service::getOptionsForMultiSelectField` or `DataObject\Service::getOptionsForSelectField` on an object class with optionsProviderClass returns array with elements.

### Actual behavior

Null is returned.

**Warning: foreach() argument must be of type array|object, null given**

### Steps to reproduce

1. Add select field to object class
2. Define an optionsProviderClass which returns values
3. Use `DataObject\Service::getOptionsForMultiSelectField` or `DataObject\Service::getOptionsForSelectField` to get the values.

### Code example

Responsible is the follwing code in `DataObject\Service::getOptionsForSelectField`:

```php
            if ($definition instanceof ClassDefinition\Data\Select || $definition instanceof ClassDefinition\Data\Multiselect) {
                $_options = $definition->getOptions();

                foreach ($_options as $option) {
                    $options[$option['value']] = $option['key'];
                }
            }
```

**`$definition->getOptions()`** returns NULL in my case and causes the Warning.

I use this in the `getEditableDialogBoxConfiguration`.

The optionsProviderClass works correct in the edit mode of an Pimcore\Model\DataObject\Article item.

# Feature Request

**Comment by brusch** [comment]
Fixed by #9365
