### ISSUE TITLE
[Core] composer.json: Cleanup Symfony packages

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#9357]
## Feature description
- Cleanup Symfony packages not required by Core, which were introduced in https://github.com/pimcore/pimcore/pull/9355

**Comment by brusch** [comment]
We should keep this open until #12094 is done, because certain packages are only needed because of functionalities which will be moved to a bundle. 

Example: 
`symfony/form` is only used by Targeting.

**Comment by kingjia90** [comment]
- [x] Making `form` optional in ContentTemplateListener https://github.com/pimcore/pimcore/pull/14830
   - [x] Require it in personalizationBundle https://github.com/pimcore/personalization-bundle/pull/2
   - [x] Require it in ecommerceFrameworkBundle https://github.com/pimcore/ecommerce-framework-bundle/pull/16
- [x] `stopwatch` is moved to PersonalizationBundle https://github.com/pimcore/pimcore/pull/14769
- [x] `web-link` has no usage, so could be removed https://github.com/pimcore/pimcore/pull/14786

**Comment by brusch** [comment]
@kingjia90 I think `form` can be made optional, by using a `class_exists()` in `ContentTemplateListener`

**Comment by dvesh3** [comment]
- [x] `cbschuld/browser.php` can be moved to AdminBundle requirement as not used anywhere in the core. Only [here](https://github.com/pimcore/pimcore/blob/894b9408db2e726f315e9f1c42c74d888aa83581/bundles/AdminBundle/src/Controller/Admin/LoginController.php#L409)
- [x] `sensiolabs/ansi-to-html` can be kicked. was used with ExtensionManager https://github.com/pimcore/pimcore/commit/fcc6d4e7f4ce305aef0f1dca2f7db27c9c5abe07#diff-a84908790f0996389c6d991d81ed0b7141b13ddc4bc9bfc3003b9027725abf8fR277
- [x] `symfony/asset` can be kicked as not used in the core. Only portal engine and CMF is using it and also requires it.
- [x] `masterminds/html5` kick? no usages in the core.. Also required in `symfony/dom-crawler`

**Comment by kingjia90** [comment]
Keeping it open until the bundle extractions are complete
