### ISSUE TITLE
Asset paths not updated after S3 setup

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#9367]
Expected Behaviour

If you move an asset folder with its content in the directory tree then the full path of the folder and the assets should be updated respectively 

Actual behaviour
If you setup S3 file storage and move an asset folder with its content in the directory tree then the full path of the folder is being updated but the full path of the the assets inside the folder does not change.

Example:
Original Pimcore X Asset Directory
 
![image](https://user-images.githubusercontent.com/68632142/121147553-415d6000-c841-11eb-8388-9719c3dfca6b.png)

Move /Hrs/Anw/sample.jpg => /Media/Images/Detail/Anw/sample.jpg

 
![image](https://user-images.githubusercontent.com/68632142/121147704-66ea6980-c841-11eb-84fb-2cb9770ba097.png)

Expected full path: /Media/Images/Detail/Anw/sample.jpg

Actual path: /Hrs/Anw/sample.jpg

Steps to reproduce:

1. Right click on specific asset folder and select “Cut”
2. Right click on destination folder and select “Paste cut-out element”
3. Left click on specific asset in the moved folder and from the menu “copy full path to clipboard”

**Comment by brusch** [comment]
@Silverado2791 which Pimcore version you are using? 
Could you try to debug this behavior on your end? The right palace would be probably here: 
https://github.com/pimcore/pimcore/blob/4b0333e50488a5835b62a05fdef57ffb79a5ffba/models/Asset.php#L513

Thanks!

**Comment by ghost** [comment]
@brusch 

Thank you for your answer Bernhard. I am using 

![image](https://user-images.githubusercontent.com/68632142/121208143-21965e00-c87a-11eb-8f9e-10ff449d2058.png)

I will provide you with debug info

**Comment by nklotter** [comment]
I've noticed this issue as well. However, the path is displayed correctly when the page is refreshed.

**Comment by fashxp** [comment]
@Silverado2791 did you already had the chance to take a look at this?

**Comment by torstent** [comment]
> Could you try to debug this behavior on your end?

I've noticed the same behaviour and tried to debug.

- The path of the folder is updated within database
- The path of containing images is not updated within database

![image](https://user-images.githubusercontent.com/5767413/122057896-60349700-cdeb-11eb-8e4a-0f1c159bdbaf.png)


- The assets are not moved on S3 

I have looked into 

https://github.com/pimcore/pimcore/blob/4b0333e50488a5835b62a05fdef57ffb79a5ffba/models/Asset.php#L513

but can't see where this recursive move of assets happen inside correctPath()? 

@brusch / @fashxp can you guide us further - I would be happy to debug further.

**Comment by dvesh3** [comment]
Fixed by #9693
