### ISSUE TITLE
[DataObject][FieldCollection] Saving localized field values nested in FieldCollection nested in object not working

### ISSUE THREAD

**Issue by rberneder** [pimcore/pimcore#9368]
### Situation
```FieldCollection``` "Text" contains data "content" nested in a ```LocalizedField```.
```Class``` "News" can contain multiple ```FieldCollection``` "Text".

### Error
When trying to save "News", the object does not get saved and no error dialogue shows up. The server responds the following message:

```json
{
  "success": false,
  "message": "Could be that someone messed around with the fieldcollection in the meantime. Please reload and try again"
}
```

This error appears because the method ```performFieldcollectionModificationCheck``` returns false.
https://github.com/pimcore/pimcore/blob/1e5b40f3fbddf15c698d037d20aee9ff2b54143e/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L1356

(Tested on Pimcore v.10.0.1)

**Comment by dvesh3** [comment]
fixed temporarily by https://github.com/pimcore/pimcore/commit/3aa2f4b148f6334fadbe13d0b8764744bc94dac6
