### ISSUE TITLE
Unnecessary setEnclosure call in AssetHelperController::downloadXlsxFileAction

### ISSUE THREAD

**Issue by wujku** [pimcore/pimcore#9375]
Issue is related to https://github.com/pimcore/pimcore/commit/332cd24770780963e699347d6455f1186d91032f#diff-d504764dc26470263c53162e55e93645b847e0f8f6d6b69f133403149af19c4c

https://github.com/pimcore/pimcore/blob/4550a053fac47a1d2c0406bf15c9799ef078bbb7/bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php#L839

**Comment by brusch** [comment]
Fixed by #9376
