### ISSUE TITLE
[Improvement] Allow opening multiple dependencies at once

### ISSUE THREAD

**Issue by jantomicky** [pimcore/pimcore#9377]
# Feature Request

- [x] There is no existing issue regarding the same topic

## Feature description

Right now, clicking on a dependency directly opens the dependency.
It would be nice to be able to select multiple depencencies via checkboxes and open them at once, as is the case in other grids.

![pimcore-dependencies](https://user-images.githubusercontent.com/41518085/121213242-5b696380-c87e-11eb-8f60-45b40d4377d4.png)

I'd love to send a merge request, but don't really know where to start. Can you point me in the direction of the source files that handle the dependencies tab components?

**Comment by fashxp** [comment]
We are happy to merge a PR for that 😊

Starting point should be [here](https://github.com/pimcore/pimcore/blob/10.x/bundles/AdminBundle/Resources/public/js/pimcore/element/dependencies.js)

**Comment by jantomicky** [comment]
Thank you! I'll check it out.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
