### ISSUE TITLE
Duplicate versions are created for video assets

### ISSUE THREAD

**Issue by nklotter** [pimcore/pimcore#9379]
Expected behavior:

Only one version should be created when a new video asset is uploaded

Actual behavior:

Multiple/duplicate versions are created for the same video asset upon upload...

![pimcore-video-versioning](https://user-images.githubusercontent.com/40795701/121250699-a3cb5600-c86b-11eb-8f22-5bd3b71f90e6.png)

Steps to reproduce:

1. Navigate to the "Assets" tab
2. Right-click on "Home", and select "Add Asset(s)" -> "Upload Files"
3. Select an MP4 file that's at least 5mb in size and upload
4. Navigate to the "Versions" tab

**Comment by dvesh3** [comment]
Fixed by #9494
