### ISSUE TITLE
[Elements] Show users who are working on the same element

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#9381]
Introduce a generic update service that also pulls infos about new notifications etc. 
The UI posts the info about open tabs and the active tab to the service. 
The infos about open tabs should be stored in the database incl. a cleanup service and a TTL.

**Comment by brusch** [comment]
Closed that in favor of the generic collaboration tools.

**Comment by jdreesen** [comment]
Which generic collaboration tools?

**Comment by brusch** [comment]
It's on our product roadmap 😉
https://pimcore.com/en/developers/roadmap
