### ISSUE TITLE
Authenticate against Pimcore Objects not working in 10.0.2 & 10.0.3

### ISSUE THREAD

**Issue by MVincentM** [pimcore/pimcore#9394]
### Expected behavior
We expect to have our custom login working as in Pimcore 1.0.1 (see doc > Authenticate against Pimcore Objects).

### Actual behavior
We get an error : `No password hasher has been configured for account "App\Model\DataObject\User".`

### Steps to reproduce
Just configure your Pimcore & follow the documentation Authenticate against Pimcore Objects. It works in 10.0.1 but not in 10.0.2 and 10.0.3

**Comment by dvesh3** [comment]
we need to fix password encoder factory instead of standard Symfony.

**Comment by dvesh3** [comment]
Fixed by #9397
