### ISSUE TITLE
allow to reset image size after using document inline-cropping

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#940]
After a image has been cropped, there is no way to reset the cropping. I think a "reset" button to restore the image (in this example back to thumbnail "test") would be great.

```php
<?= $this->image('image', ['thumbnail' => 'test' ]); ?>
```

![](https://www.pimcore.org/docs/latest/img/image_preview_backend_modification2.png)

**Comment by mrudnicki** [comment]
![image](https://cloud.githubusercontent.com/assets/20395719/19436438/671e95ac-9470-11e6-8b7a-f7eccb44327f.png)
I've added a reset button to the image cropper window.
