### ISSUE TITLE
[Asset] - Metadata primary key constraint violation

### ISSUE THREAD

**Issue by roland4432** [pimcore/pimcore#9402]
# Bug Report

### Expected behavior
Initial saving of assets metadata doesn't throw errors.

### Actual behavior
Saving does throw errors.

### Steps to reproduce
Upload a fresh image. Directly go to the _custom metadata_ tab. Enter something e.g. in the copyright field, but **don't** select any language.
Hit _save & publish_ => error (in detail: the asset_metadata table has the primary key setup as a combination of cid, name, language and language is '' in this case) is caused due to the missing field content.

Set a language, hit _save & publish_ and reload the asset right after.  
You will end up with the following metadata fields:
* alt
* title
* copyright
* copyright
(in the case you entered data in the copyright field, else, the corresponding field will be doubled)

### Code example
```php
#/bundles/AdminBundle/Controller/Admin/Asset/AssetContoller.php
#line 931
$metadataValues = $metadata['values'];
# this will hold 4 array values, that need to be consolidated and the language set (maybe from the current backend language as fallback if none is selected by the user)
```

**Comment by dvesh3** [comment]
already fixed in https://github.com/pimcore/pimcore/pull/9440
