### ISSUE TITLE
[Targeting] Targeting Rules broken

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#9408]
targeting rules cannot be opened, editor is always empty:
![image](https://user-images.githubusercontent.com/8792145/121547657-9dc0ab00-ca0c-11eb-8272-d99af8cd9d5a.png)

cannot be saved:
![image](https://user-images.githubusercontent.com/8792145/121547726-add88a80-ca0c-11eb-8244-886f4643cac4.png)

**Comment by dvesh3** [comment]
Fixed by #9411
