### ISSUE TITLE
Asset PDF: Use native PDF viewer in Safari

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#944]
The file https://github.com/pimcore/pimcore/blob/master/pimcore/static6/js/pimcore/asset/document.js#L92, has hasNativePDFViewer() call which send "undefined", so making not using the native safari pdf viewer and use the google viewer (which don't work in local develpement, as it seems domaine must be accessible externaly). So on Pimcore GUI, it ends with a "Preview not available" in this case.
So for devloppers using safari preview document on local instance seems not possible.

Solution:
Change the hasNativePDFViewer to send true if safari version support native viewer.

Tested on:
Mac OS X El Capitan 10.11.5 - Safari 9.1.1

**Comment by brusch** [comment]
Just tested it on Browserstack (demo.pimcore.org) and everything works as expected. 
So seems to be a problem with your local setup? 

![image](https://cloud.githubusercontent.com/assets/142037/19386866/fb74c00c-9216-11e6-8629-63ef656d9ef4.png)

**Comment by Yivan** [comment]
Yes you are right, it works on our setup too on the demo, because it is internet accessible for google-viewer. If you check the console network you will see i think that it use google viewer and not the native pdf reader of Safari.

Problem is for Safari the method `hasNativePDFViewer()` return "**undefined**", so it use the google-viewer fallback in the view (get-preview-document.php). But the google-viewer seems not working for document on local url (not accessible by internet as http://mydomain.local/mydoc.pdf).

Safari has a native viewer so changing the line:
https://github.com/pimcore/pimcore/blob/master/pimcore/static6/js/pimcore/asset/document.js#L114

Replacing:
`if(Ext.isChrome || Ext.isGecko) {`
By:
`if(Ext.isChrome || Ext.isGecko || Ext.isSafari) {`

should do the trick (i don't tested if safari on tablet/mobile get native pdf for those using backend pimcore on those...).
