### ISSUE TITLE
[DataObject][FieldCollection] FieldCollection > Block > LocalizedField > Field cannot be saved

### ISSUE THREAD

**Issue by rberneder** [pimcore/pimcore#9443]
#### Situation
As already requested in issue #6540, it is still not possible to facilitate the following structure:
```
FieldCollection
└ Block
  └ LocalizedField
    └ Field
```
#### Example use-case
A news entry has multiple ```FieldCollection```-sections. One of it is a ```Gallery``` containing an image with its caption. These images are nested in a ```Block``` and the caption-```Input``` is nested in a ```LocalizedField```.

**Comment by weisswurstkanone** [comment]
This kind of nesting level is currrently not supported. Unfortunately it did not make it into 10.0

**Comment by rberneder** [comment]
Would it be meaningful to adapt the UI so that one cannot create this non-working nesting structure in the first place?
Is there a proposal from your side how such scenarios could be implemented in another way @weisswurstkanone?

**Comment by weisswurstkanone** [comment]
I think there is a similar check already for object bricks. See https://github.com/pimcore/pimcore/blob/3372c2b57e6d2689e39ec07c45a90350acbe65b0/models/DataObject/Objectbrick/Definition.php#L204
But please keep in mind that UI is not enough. Rules have to be always enforced on server side anyway.
Regarding the last question. Not sure if the data model is way to complex :-)
