### ISSUE TITLE
ClassificationStore – issue with object version preview

### ISSUE THREAD

**Issue by wujku** [pimcore/pimcore#9449]
`Impossible to access an attribute ("language") on a string variable ("/ ").` 
https://github.com/pimcore/pimcore/blob/c919f139cc4901156aeed07214d9ff03ae358cb8/bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/previewVersion.html.twig#L136

Quick fix for this:

`"/ " . language` => `"/ " ~ language`

**Comment by dvesh3** [comment]
Fixed by #9455
