### ISSUE TITLE
Modify contrast ratio for active and non-active tabs to faster identify the active tab. 

### ISSUE THREAD

**Issue by Timonwatteny** [pimcore/pimcore#9450]
# Feature Request

## Feature description

The contrast between the active tab and the non-active tabs in the navigation bar is very low. This makes it sometimes difficult for customers to see what tab is currently active. This is mostly an issue for people not yet comfortable navigating through Pimcore. Because of that it would be a cool feature to have the own possibility to select a contrast ratio, or even the possibility to add a color (like the branding section) to the active tab. 

![Screenshot 2021-06-15 at 13 38 05](https://user-images.githubusercontent.com/31765954/122046717-8d7b4800-cddf-11eb-9b6d-dbc747e9fece.png)
![Screenshot 2021-06-15 at 13 40 47](https://user-images.githubusercontent.com/31765954/122046724-8eac7500-cddf-11eb-8e9b-d1cd843bf087.png)

Kind regards 

Timon Watteny 
Studio Emma

**Comment by NiklasBr** [comment]
This is still relevant, WCAG level 2 accessibility is a legal requirement in many European countries, both on the private and the public sector.

**Comment by brusch** [comment]
It's not closed, just got the "PR Welcome" label 😉

**Comment by jdreesen** [comment]
Why is the label removed as soon as someone comments the issue?

**Comment by NiklasBr** [comment]
Because Stale Bot is not a good tool.

**Comment by jdreesen** [comment]
Yeah, it seems to be very noisy and stupid...

**Comment by fashxp** [comment]
will be tackled with new UI.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
