### ISSUE TITLE
Template path for external bundles is invalid

### ISSUE THREAD

**Issue by mugge6** [pimcore/pimcore#9453]
# Bug Report

### Expected behavior

Template selection drop down should display all templates from configured template paths as follows: @<namespace>/<template_path>/<twig_template>. Otherwise all templates from third party bundles has to be manually edited and the drop down is useless.

### Actual behavior

On documents the template selection drop down shows the wrong path in the settings path. For example the CMF templates are shown as follows:

![image](https://user-images.githubusercontent.com/16953779/122059129-9b839580-cdec-11eb-84c7-7a57f5b6228c.png)

Preview shows the following error because the namespace is not correctly used:

![image](https://user-images.githubusercontent.com/16953779/122061075-798b1280-cdee-11eb-8c81-eac5090f8a99.png)

**Comment by brusch** [comment]
Fixed by #9454
