### ISSUE TITLE
Concrete::__callStatic does not allow variants

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#9457]
# Bug Report

Calling a static getter code like `Product::getBySomefield('valueInVaraint')` should return any `Product` regardless of whether or not is is an object or variant. Or the getter must accept a parameter that allows us to toggle this behaviour like for regular DataObject listings.

### Steps to reproduce

1. Add an object
2. Fill it with some data
3. Add a variant of that object
4. Change some field in the varaint
5. Attempt to fetch the variant (or object) via a static getter.

### Code example
```php
// A MyClass object which is a variant will never be returned here even thought it exists in the database.
Product::getBySomeField('data', 1);
```

**Comment by brusch** [comment]
A possible solution could be to specify the type of objects to return as an optional third parameter, similar what we do for lists? 
With `v11` we can then change the default behavior. wdyt?

**Comment by NiklasBr** [comment]
That sounds reasonable 👍 

But I'm not sure the default behaviour need to change later, our use case is only blocked by the inability to fetch variants this way.
