### ISSUE TITLE
User data type not possible on fieldcollection and bricks

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#946]
Multiple User field data type can be add to an object class.
So I don't know if it is a limitation, but this data type is not available on fieldcollection and bricks.
Maybe it could be added if there is no particularity on this field ? (i think it is just an user id)

**Comment by weisswurstkanone** [comment]
Hmm, I don't see why this should be forbidden as it basically just a simple "select".
Please let me know if you notice any side effects. Maybe I am missing an important point here.
