### ISSUE TITLE
[DataObject][FieldCollection][Block] Nested structure causes error and breaks UI and front-end when lazy loading is disabled

### ISSUE THREAD

**Issue by rberneder** [pimcore/pimcore#9460]
### Environment
Pimcore 10.0.4 running in DEV mode (server is allowed to print errors).

### ClassDefinition
A ```FieldCollection``` contains a ```Block``` that contains a simple ```Input```. This ```FieldCollection``` is loaded _without lazy-loading_ in an arbitrary ```Class```, e.g. ```News```.

### Steps to reproduce
- Create a new ```News```-object.
- Save & publish it.
- Tree-view and object still works.
- Add a new ```FieldCollection``` entry to the object with some block values.
- Save & publish and close the object.
- Try to reopen the object (not working).

### Error description
After the object has been saved, every access to it will cause a fatal error (see below) that is appended to the response. This is why the Pimcore backend breaks. Also on front-end pages this error is appended to the HTML, wherever the object is accessed.

```
<b>Fatal error</b>:  Uncaught TypeError: Cannot assign Pimcore\Model\Element\ElementDescriptor to property Pimcore\Model\DataObject\Fieldcollection\Data\AbstractData::$object of type ?Pimcore\Model\DataObject\Concrete in /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:252
Stack trace:
#0 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(252): ReflectionProperty-&gt;setValue(Object(Pimcore\Model\DataObject\Fieldcollection\Data\TestFCA), Object(Pimcore\Model\Element\ElementDescriptor))
#1 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(208): DeepCopy\DeepCopy-&gt;copyObjectProperty(Object(Pimcore\Model\DataObject\Fieldcollection\Data\TestFCA), Object(ReflectionProperty))
#2 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(144): DeepCopy\DeepCopy-&gt;copyObject(Object(Pimcore\Model\DataObject\Fieldcollection\Data\TestFCA))
#3 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(252): DeepCopy\DeepCopy-&gt;recursiveCopy(Object(Pimcore\Model\DataObject\Fieldcollection\Data\TestFCA))
#4 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(208): DeepCopy\DeepCopy-&gt;copyObjectProperty(Object(Pimcore\Model\DataObject\Data\BlockElement), Object(ReflectionProperty))
#5 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(144): DeepCopy\DeepCopy-&gt;copyObject(Object(Pimcore\Model\DataObject\Data\BlockElement))
#6 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(94): DeepCopy\DeepCopy-&gt;recursiveCopy(Object(Pimcore\Model\DataObject\Data\BlockElement))
#7 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Data/BlockElement.php(241): DeepCopy\DeepCopy-&gt;copy(Object(Pimcore\Model\DataObject\Data\BlockElement))
#8 /var/www/html/vendor/pimcore/pimcore/lib/Cache/Core/CoreCacheHandler.php(594): Pimcore\Model\DataObject\Data\BlockElement-&gt;marshalForCache()
#9 [internal function]: Pimcore\Cache\Core\CoreCacheHandler-&gt;Pimcore\Cache\Core\{closure}(Object(Pimcore\Model\DataObject\Data\BlockElement))
#10 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/TypeFilter/ReplaceFilter.php(28): call_user_func(Object(Closure), Object(Pimcore\Model\DataObject\Data\BlockElement))
#11 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(125): DeepCopy\TypeFilter\ReplaceFilter-&gt;apply(Object(Pimcore\Model\DataObject\Data\BlockElement))
#12 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(155): DeepCopy\DeepCopy-&gt;recursiveCopy(Object(Pimcore\Model\DataObject\Data\BlockElement))
#13 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(135): DeepCopy\DeepCopy-&gt;copyArray(Array)
#14 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(155): DeepCopy\DeepCopy-&gt;recursiveCopy(Array)
#15 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(135): DeepCopy\DeepCopy-&gt;copyArray(Array)
#16 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(252): DeepCopy\DeepCopy-&gt;recursiveCopy(Array)
#17 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(208): DeepCopy\DeepCopy-&gt;copyObjectProperty(Object(Pimcore\Model\DataObject\Fieldcollection\Data\TestFCA), Object(ReflectionProperty))
#18 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(144): DeepCopy\DeepCopy-&gt;copyObject(Object(Pimcore\Model\DataObject\Fieldcollection\Data\TestFCA))
#19 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(155): DeepCopy\DeepCopy-&gt;recursiveCopy(Object(Pimcore\Model\DataObject\Fieldcollection\Data\TestFCA))
#20 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(135): DeepCopy\DeepCopy-&gt;copyArray(Array)
#21 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(252): DeepCopy\DeepCopy-&gt;recursiveCopy(Array)
#22 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(208): DeepCopy\DeepCopy-&gt;copyObjectProperty(Object(Pimcore\Model\DataObject\Fieldcollection), Object(ReflectionProperty))
#23 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(144): DeepCopy\DeepCopy-&gt;copyObject(Object(Pimcore\Model\DataObject\Fieldcollection))
#24 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(252): DeepCopy\DeepCopy-&gt;recursiveCopy(Object(Pimcore\Model\DataObject\Fieldcollection))
#25 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(208): DeepCopy\DeepCopy-&gt;copyObjectProperty(Object(Pimcore\Model\DataObject\TestClassFC), Object(ReflectionProperty))
#26 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(144): DeepCopy\DeepCopy-&gt;copyObject(Object(Pimcore\Model\DataObject\TestClassFC))
#27 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(94): DeepCopy\DeepCopy-&gt;recursiveCopy(Object(Pimcore\Model\DataObject\TestClassFC))
#28 /var/www/html/vendor/pimcore/pimcore/lib/Cache/Core/CoreCacheHandler.php(605): DeepCopy\DeepCopy-&gt;copy(Object(Pimcore\Model\DataObject\TestClassFC))
#29 /var/www/html/vendor/pimcore/pimcore/lib/Cache/Core/CoreCacheHandler.php(910): Pimcore\Cache\Core\CoreCacheHandler-&gt;storeCacheData('object_1130', Object(Pimcore\Model\DataObject\TestClassFC), Array, NULL, false)
#30 /var/www/html/vendor/pimcore/pimcore/lib/Cache/Core/CoreCacheHandler.php(958): Pimcore\Cache\Core\CoreCacheHandler-&gt;writeSaveQueue()
#31 /var/www/html/vendor/pimcore/pimcore/lib/Cache.php(200): Pimcore\Cache\Core\CoreCacheHandler-&gt;shutdown(false)
#32 /var/www/html/vendor/pimcore/pimcore/lib/Pimcore.php(240): Pimcore\Cache::shutdown()
#33 /var/www/html/vendor/pimcore/pimcore/lib/Kernel.php(242): Pimcore::shutdown()
#34 [internal function]: Pimcore\Kernel-&gt;Pimcore\{closure}()
#35 {main}
  thrown in <b>/var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php</b> on line <b>252</b><br />

```

**Comment by dvesh3** [comment]
@rberneder sorry, not able to reproduce on ver 10.0.4. Can you please try to reproduce it on https://demo.pimcore.fun/

**Comment by rberneder** [comment]
Sure @dvesh3. I have successfully reproduced this error on the current Pimcore demo with the ```FieldCollection``` "TestFC" and the ```Class``` "FcClass". Below you can find the definition exports:

### Important
- Lazy-loading of the ```FieldCollection``` must be disabled.
- The environment must be set to ```dev``` in the Pimcore demo (I just edited the ```.env.local``` file).

#### Field collection: TestFC
```json
{
    "key": null,
    "parentClass": "",
    "implementsInterfaces": "",
    "title": "",
    "group": "",
    "layoutDefinitions": {
        "fieldtype": "panel",
        "layout": null,
        "border": false,
        "name": null,
        "type": null,
        "region": null,
        "title": null,
        "width": 0,
        "height": 0,
        "collapsible": false,
        "collapsed": false,
        "bodyStyle": null,
        "datatype": "layout",
        "permissions": null,
        "childs": [
            {
                "fieldtype": "panel",
                "layout": null,
                "border": false,
                "name": "Layout",
                "type": null,
                "region": null,
                "title": "",
                "width": "",
                "height": "",
                "collapsible": false,
                "collapsed": false,
                "bodyStyle": "",
                "datatype": "layout",
                "permissions": null,
                "childs": [
                    {
                        "fieldtype": "block",
                        "lazyLoading": false,
                        "disallowAddRemove": false,
                        "disallowReorder": false,
                        "collapsible": false,
                        "collapsed": false,
                        "maxItems": null,
                        "columnType": "longtext",
                        "styleElement": "",
                        "childs": [
                            {
                                "fieldtype": "input",
                                "width": "",
                                "defaultValue": null,
                                "queryColumnType": "varchar",
                                "columnType": "varchar",
                                "columnLength": 190,
                                "regex": "",
                                "unique": false,
                                "showCharCount": false,
                                "name": "title",
                                "title": "title",
                                "tooltip": "",
                                "mandatory": false,
                                "noteditable": false,
                                "index": false,
                                "locked": false,
                                "style": "",
                                "permissions": null,
                                "datatype": "data",
                                "relationType": false,
                                "invisible": false,
                                "visibleGridView": false,
                                "visibleSearch": false
                            }
                        ],
                        "layout": null,
                        "fieldDefinitionsCache": null,
                        "name": "contents",
                        "title": "contents",
                        "tooltip": "",
                        "mandatory": false,
                        "noteditable": false,
                        "index": false,
                        "locked": false,
                        "style": "",
                        "permissions": null,
                        "datatype": "data",
                        "relationType": false,
                        "invisible": false,
                        "visibleGridView": false,
                        "visibleSearch": false
                    }
                ],
                "locked": false,
                "icon": "",
                "labelWidth": "",
                "labelAlign": "left"
            }
        ],
        "locked": false,
        "icon": null,
        "labelWidth": 100,
        "labelAlign": "left"
    },
    "generateTypeDeclarations": true
}
```

#### Class: FcClass
```json
{
    "id": "6",
    "description": "",
    "modificationDate": 1623868768,
    "parentClass": "",
    "implementsInterfaces": "",
    "listingParentClass": "",
    "useTraits": "",
    "listingUseTraits": "",
    "allowInherit": false,
    "allowVariants": false,
    "showVariants": false,
    "layoutDefinitions": {
        "fieldtype": "panel",
        "layout": null,
        "border": false,
        "name": "pimcore_root",
        "type": null,
        "region": null,
        "title": null,
        "width": 0,
        "height": 0,
        "collapsible": false,
        "collapsed": false,
        "bodyStyle": null,
        "datatype": "layout",
        "permissions": null,
        "childs": [
            {
                "fieldtype": "panel",
                "layout": null,
                "border": false,
                "name": "Layout",
                "type": null,
                "region": null,
                "title": "",
                "width": "",
                "height": "",
                "collapsible": false,
                "collapsed": false,
                "bodyStyle": "",
                "datatype": "layout",
                "permissions": null,
                "childs": [
                    {
                        "fieldtype": "fieldcollections",
                        "allowedTypes": [
                            "TestFC"
                        ],
                        "lazyLoading": false,
                        "maxItems": "",
                        "disallowAddRemove": false,
                        "disallowReorder": false,
                        "collapsed": false,
                        "collapsible": false,
                        "border": false,
                        "name": "contentsFC",
                        "title": "contentsFC",
                        "tooltip": "",
                        "mandatory": false,
                        "noteditable": false,
                        "index": false,
                        "locked": false,
                        "style": "",
                        "permissions": null,
                        "datatype": "data",
                        "relationType": false,
                        "invisible": false,
                        "visibleGridView": false,
                        "visibleSearch": false
                    }
                ],
                "locked": false,
                "icon": "",
                "labelWidth": "",
                "labelAlign": "left"
            }
        ],
        "locked": false,
        "icon": null,
        "labelWidth": 100,
        "labelAlign": "left"
    },
    "icon": "",
    "previewUrl": "",
    "group": "",
    "showAppLoggerTab": false,
    "linkGeneratorReference": "",
    "previewGeneratorReference": "",
    "compositeIndices": [],
    "generateTypeDeclarations": true,
    "showFieldLookup": false,
    "propertyVisibility": {
        "grid": {
            "id": true,
            "key": false,
            "path": true,
            "published": true,
            "modificationDate": true,
            "creationDate": true
        },
        "search": {
            "id": true,
            "key": false,
            "path": true,
            "published": true,
            "modificationDate": true,
            "creationDate": true
        }
    },
    "enableGridLocking": false
}
```

**Comment by fkaletsch** [comment]
I have the same problem with Blocks in Objectbricks. (Pimcore 10.0.7)
The problem can _not_ be reproduced on demo.pimcore.com.

I assume that the error still occurs in the Demo-System, but the error message is not appended to the response and therefore is not passed to the backend.

**Comment by brusch** [comment]
Unfortunately this is not reproducible anymore. 
If the issue still exists for you, please either try to provide a fix for us or a reproducible step-by-step guide on our public demo. Thanks

**Comment by piotrecky** [comment]
I have the same problem with objectbricks.

<b>Fatal error</b>:  Uncaught TypeError: Cannot assign Pimcore\Model\Element\ElementDescriptor to property Pimcore\Model\DataObject\Objectbrick::$object of type ?Pimcore\Model\DataObject\Concrete in /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:252
Stack trace:
#0 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(252): ReflectionProperty-&gt;setValue(Object(Pimcore\Model\DataObject\Produkt\Parametry), Object(Pimcore\Model\Element\ElementDescriptor))
#1 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(208): DeepCopy\DeepCopy-&gt;copyObjectProperty(Object(Pimcore\Model\DataObject\Produkt\Parametry), Object(ReflectionProperty))
#2 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(144): DeepCopy\DeepCopy-&gt;copyObject(Object(Pimcore\Model\DataObject\Produkt\Parametry))
#3 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(252): DeepCopy\DeepCopy-&gt;recursiveCopy(Object(Pimcore\Model\DataObject\Produkt\Parametry))
#4 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(208): DeepCopy\DeepCopy-&gt;copyObjectProperty(Object(Pimcore\Model\DataObject\Data\BlockElement), Object(ReflectionProperty))
#5 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(144): DeepCopy\DeepCopy-&gt;copyObject(Object(Pimcore\Model\DataObject\Data\BlockElement))
#6 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(94): DeepCopy\DeepCopy-&gt;recursiveCopy(Object(Pimcore\Model\DataObject\Data\BlockElement))
#7 /var/www/vendor/pimcore/pimcore/models/DataObject/Data/BlockElement.php(246): DeepCopy\DeepCopy-&gt;copy(Object(Pimcore\Model\DataObject\Data\BlockElement))
#8 /var/www/vendor/pimcore/pimcore/lib/Cache/Core/CoreCacheHandler.php(565): Pimcore\Model\DataObject\Data\BlockElement-&gt;marshalForCache()
#9 [internal function]: Pimcore\Cache\Core\CoreCacheHandler-&gt;Pimcore\Cache\Core\{closure}(Object(Pimcore\Model\DataObject\Data\BlockElement))
#10 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/TypeFilter/ReplaceFilter.php(28): call_user_func(Object(Closure), Object(Pimcore\Model\DataObject\Data\BlockElement))
#11 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(125): DeepCopy\TypeFilter\ReplaceFilter-&gt;apply(Object(Pimcore\Model\DataObject\Data\BlockElement))
#12 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(155): DeepCopy\DeepCopy-&gt;recursiveCopy(Object(Pimcore\Model\DataObject\Data\BlockElement))
#13 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(135): DeepCopy\DeepCopy-&gt;copyArray(Array)
#14 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(155): DeepCopy\DeepCopy-&gt;recursiveCopy(Array)
#15 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(135): DeepCopy\DeepCopy-&gt;copyArray(Array)
#16 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(252): DeepCopy\DeepCopy-&gt;recursiveCopy(Array)
#17 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(208): DeepCopy\DeepCopy-&gt;copyObjectProperty(Object(Pimcore\Model\DataObject\Objectbrick\Data\KredytGotowkowy), Object(ReflectionProperty))
#18 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(144): DeepCopy\DeepCopy-&gt;copyObject(Object(Pimcore\Model\DataObject\Objectbrick\Data\KredytGotowkowy))
#19 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(252): DeepCopy\DeepCopy-&gt;recursiveCopy(Object(Pimcore\Model\DataObject\Objectbrick\Data\KredytGotowkowy))
#20 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(208): DeepCopy\DeepCopy-&gt;copyObjectProperty(Object(Pimcore\Model\DataObject\Produkt\Parametry), Object(ReflectionProperty))
#21 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(144): DeepCopy\DeepCopy-&gt;copyObject(Object(Pimcore\Model\DataObject\Produkt\Parametry))
#22 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(252): DeepCopy\DeepCopy-&gt;recursiveCopy(Object(Pimcore\Model\DataObject\Produkt\Parametry))
#23 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(208): DeepCopy\DeepCopy-&gt;copyObjectProperty(Object(App\Model\DataObject\Product), Object(ReflectionProperty))
#24 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(144): DeepCopy\DeepCopy-&gt;copyObject(Object(App\Model\DataObject\Product))
#25 /var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(94): DeepCopy\DeepCopy-&gt;recursiveCopy(Object(App\Model\DataObject\Product))
#26 /var/www/vendor/pimcore/pimcore/lib/Cache/Core/CoreCacheHandler.php(577): DeepCopy\DeepCopy-&gt;copy(Object(App\Model\DataObject\Product))
#27 /var/www/vendor/pimcore/pimcore/lib/Cache/Core/CoreCacheHandler.php(884): Pimcore\Cache\Core\CoreCacheHandler-&gt;storeCacheData('object_1163', Object(App\Model\DataObject\Product), Array, NULL, false)
#28 /var/www/vendor/pimcore/pimcore/lib/Cache/Core/CoreCacheHandler.php(932): Pimcore\Cache\Core\CoreCacheHandler-&gt;writeSaveQueue()
#29 /var/www/vendor/pimcore/pimcore/lib/Cache.php(200): Pimcore\Cache\Core\CoreCacheHandler-&gt;shutdown(false)
#30 /var/www/vendor/pimcore/pimcore/lib/Pimcore.php(242): Pimcore\Cache::shutdown()
#31 /var/www/vendor/pimcore/pimcore/lib/Kernel.php(247): Pimcore::shutdown()
#32 [internal function]: Pimcore\Kernel-&gt;Pimcore\{closure}()
#33 {main}
  thrown in <b>/var/www/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php</b> on line <b>252</b><br />
