### ISSUE TITLE
Classification Store: Grid Issues

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#948]
We just started looking for the new classification store collection. It seems really great to make classified attributs for product, thanks again for this new feature!

I would like just to report some bugs or things wich can be easily improved i think.

- Bug:
In the grid list we can drag the classification store, but it don't work, it break the popin to work so we can not more drag anything after (need to close the popin and reopen it to make it work again)
![grid](https://cloud.githubusercontent.com/assets/9025839/19435086/23e6bfe6-9469-11e6-90f9-9da14232f749.png)
I think it could be listed in the grid and exported as CSV (even for localized classification store) as versionning could get the information in "flat" format:
![filter2](https://cloud.githubusercontent.com/assets/9025839/19435123/51c9958c-9469-11e6-98c2-d3c223a98d91.png)
Maybe it is not possible because inheritance make things complicated ?
If not possible, so better to hide classification store form the column configuration.

- Visual improvement:
Having the same name of the field type than for other object (class, bricks, ...), and so they will be translated to in the backend (if user don't use english for admin language).
Actually we have those (it is more analytics name than human name):
![namefield1](https://cloud.githubusercontent.com/assets/9025839/19434984/bfe47ef2-9468-11e6-837e-2a9ec842dfb8.png)
It could be the same than usually:
![namefield2](https://cloud.githubusercontent.com/assets/9025839/19434999/ca7ce2fa-9468-11e6-86db-e99c2446b78f.png)

- Improvement:
I know just simple data type field could be used (so not things like href, object, multihref, structured table,...), but is there any reason those one can't be used in classification store? : password, user, geographics (point, bounds, polygon), link. For the CRM type i don't know (i don't use them a lot) and as they have some inside linking (for newsletter for instance) maybe they have not their place in classification store.

**Comment by weisswurstkanone** [comment]
Visual Improvement: Done
Improvement: Enabled user and password. will look into geographic stuff later

**Comment by brusch** [comment]
We should have separate tickets for bugs and improvements to generate meaningful release notes.

**Comment by dpfaffenbauer** [comment]
@weisswurstkanone I see you are working hard on the classification store. But there is something that breaks my builds with PHP < 7 (5.5 and 5.6)

https://github.com/pimcore/pimcore/blob/master/pimcore/models/Object/Classificationstore/Dao.php#L89

Anonymous classes is only in PHP7

http://php.net/manual/de/migration70.new-features.php#migration70.new-features.anonymous-classes

**Comment by weisswurstkanone** [comment]
@dpfaffenbauer Good point. Actually I don't need it right now.
See https://github.com/pimcore/pimcore/commit/e4e0f818bcad550242c96638b5052415b39e19ca

**Comment by weisswurstkanone** [comment]
https://github.com/pimcore/pimcore/commit/9520ea6424e77a483330c12e6a6a3fa73080d751 fixes the drag and drop issue

**Comment by weisswurstkanone** [comment]
About the CSV Export: Note that the version diff only shows a condensed (i.e. only the real differences) whereas for the CSV export you would need the superset of all used features across the exported objects.

**Comment by weisswurstkanone** [comment]
Please open another issue for further input/feedback.
