### ISSUE TITLE
[Admin Translations] Debug Admin-Translations not working properly

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#9482]
`+` signs are only shown reliably when translation keys are not added to admin translations table. 
As soon as they are already added to the table (but still not translated), only some of them are shown.

### Steps to reproduce
- open admin translations and cleanup 
- reload pimcore admin ... all translation keys are wrapped in `+` signs
- reload pimcore admin once more ... not all translation keys are wrapped anymore

**Comment by dvesh3** [comment]
Fixed by #9678
