### ISSUE TITLE
Unable to Rebuild Class with -d

### ISSUE THREAD

**Issue by vinitchopra12** [pimcore/pimcore#9493]
When I run the class rebuild command with -d it giving the below error:

> ./bin/console pimcore:deployment:classes-rebuild -d -c

```
In LocateFileTrait.php line 23:
                                                                               
  Pimcore\Model\DataObject\ClassDefinition::locateFile(): Argument #1 ($key)   
  must be of type string, null given, called in /usr/share/nginx/html/pimcore  
  _timberline_dev/vendor/pimcore/pimcore/models/DataObject/ClassDefinition.ph  
  p on line 802       
``` 

FYI, I am using Pimcore v10.0.4 and taking the Class Identifier same as Class Name. eg.  Class Name: Category Unique Identifier: CATEGORY.

**Comment by brusch** [comment]
For me that's just working fine. 
Are you sure you've specified a `name` attribute in the class definition? 

![image](https://user-images.githubusercontent.com/142037/122945571-f41cda80-d378-11eb-8bbc-b177fb7f264d.png)

**Comment by brusch** [comment]
Closed due to inactivity. Please feel free to continue the discussion or provide the missing information on this issue, we'll then reopen it if necessary. Thanks a lot!
