### ISSUE TITLE
Option to upload a Zip Archive and perform an update on existing files/folders

### ISSUE THREAD

**Issue by nklotter** [pimcore/pimcore#9500]
*** FEATURE REQUEST ***

The "Upload ZIP Archive" is a great feature. However, there's currently no option to have the files within the folder hierarchy updated (with versioning) instead of only being duplicated and incrementally renamed.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
