### ISSUE TITLE
Kernel getContainer() throws a LogicException on shutdown 

### ISSUE THREAD

**Issue by ubaranouski** [pimcore/pimcore#9531]
# Bug Report

### Expected behavior
Successfull shutdown.

### Actual behavior
```sh
Fatal error: Uncaught LogicException: Cannot retrieve the container from a non-booted kernel. in /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:307
Stack trace:
#0 /app/vendor/pimcore/pimcore/lib/Kernel.php(238): Symfony\Component\HttpKernel\Kernel->getContainer()
#1 [internal function]: Pimcore\Kernel->Pimcore\{closure}()
#2 {main}
  thrown in /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 307
```

### Steps to reproduce
Running tests which boot multiple containers.
You use parent getContainer() and then check the value
https://github.com/pimcore/pimcore/blob/e9f1d5b03614a5d13e6a2994c25faa22d5f80076/lib/Kernel.php#L238
but the parent throws a LogicException earlier

https://github.com/symfony/symfony/blob/1a2e10137e03ad29c1f4f6fb1ab95ecd02be4518/src/Symfony/Component/HttpKernel/Kernel.php#L307

# Feature Request

Use try-finally to get the container value

**Comment by brusch** [comment]
Fixed by #9532
