### ISSUE TITLE
[Documents][Areabricks] Don't allow to add Areabricks via d&d when areabrick editable is inherited

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#9534]
when areabrick editalbe is inherited from master document, you cannot add area bricks with plus buttons - which is right:
![image](https://user-images.githubusercontent.com/8792145/123079933-af4a7f80-d41c-11eb-9174-82d0a6ba6119.png)

but you can add new bricks via d&d to the same - which is not right:
![image](https://user-images.githubusercontent.com/8792145/123080044-cf7a3e80-d41c-11eb-8245-718a5a64d7fc.png)

especially, as the newly added bricks will be lost after saving and reloading.

**Comment by dvesh3** [comment]
Fixed by #9659
