### ISSUE TITLE
Tree Folder Search - Folder unusable after moving object

### ISSUE THREAD

**Issue by FranzRest** [pimcore/pimcore#9535]
Behavior was reproduced on the current demo Version: v10.0.4

When you use the folder search in the Pimcore Tree to search for a specific object and move this one, the folder gets unusable - only a complete Pimcore reload fixes the issue

### Expected behavior
One of the 2 cases:
1. After moving the only object the filter should reset and the folder shows all objects again
2. After moving the only object the filter is remaining, but shown besides the folder to delete/change it again

### Actual behavior
After moving the object, the folder is not usable anymore and does not show any objects (grid view is still possible)
Right Klick - "Refresh" results in Pimcore dying -> complete reload is necessary

### Steps to reproduce
1. Pick a folder with a lot of objects - Pagination must be available
![TreeSearchBug_1](https://user-images.githubusercontent.com/6606770/123092179-7e714700-d42a-11eb-94a6-df11e3981350.png)
2. Use the Search functionality to filter for an object or multiple objects 
![TreeSearchBug_2](https://user-images.githubusercontent.com/6606770/123092178-7e714700-d42a-11eb-9711-17a0f3cb3639.png)
3. Move the object/the objects to a different folder per drag&drop
![TreeSearchBug_3](https://user-images.githubusercontent.com/6606770/123092173-7dd8b080-d42a-11eb-8361-8912edb96428.png)
4. The folder gets unusable 
![TreeSearchBug_4](https://user-images.githubusercontent.com/6606770/123092181-7f09dd80-d42a-11eb-9954-d47de29fbd31.png)
5. (Optional) Right Click the folder -> Refresh -> Pimcore is not responding anymore

**Comment by dvesh3** [comment]
It happens when there's only one object in search result and you move this object to another folder. **Possible solution:** refresh source folder if empty after node move.

**Comment by dvesh3** [comment]
Fixed by #9574
