### ISSUE TITLE
[Data Objects][Text Layout] Add option to define content via twig

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#9547]
similar to #9546

- probably directly inside existing wysiwyg editor? 
- pass same parameters as to renderLayoutText method to execution context
- also add preview/test view with data object to drag for preview

**Comment by brusch** [comment]
Just similar what we do with emails: 

https://github.com/pimcore/pimcore/blob/43b0963dd9ff7d0faff39db339fd0c15ad324a50/lib/Mail.php#L651
