### ISSUE TITLE
After Updating from 6.8.11 to 6.9.6, it is removing data from link field inside block

### ISSUE THREAD

**Issue by pdchaudhary** [pimcore/pimcore#9550]
# Bug Report

### Expected behavior
It should not remove data inside the link field.

### Actual behavior
Removing data inside link set as empty.

### Steps to reproduce
1. Updated from 6.8.11 to 6.9.6. ( In this process, it is updating class definition and due to this my link data erased after updating) 

![image](https://user-images.githubusercontent.com/30948231/123148894-53b0de00-d47e-11eb-861b-971f4683bed3.png)

**Comment by brusch** [comment]
Pimcore 6 Community Edition is EOL, closed.
