### ISSUE TITLE
No documents, assets & objects in CMS for non-Admins

### ISSUE THREAD

**Issue by akno77** [pimcore/pimcore#9557]
# Bug Report

### Expected behavior

If a non admin is logged into the CMS he gets displayed the documents, assets & objects his role has assigned.

### Actual behavior

The user gets nothing displayed.

### Steps to reproduce

1. Open Pimcore Demo Admin as superuser: https://demo.pimcore.com/admin/
2. See what happens

**Comment by brusch** [comment]
Already fixed by #9556
