### ISSUE TITLE
User with list/view permissions only is allowed to delete draft

### ISSUE THREAD

**Issue by akno77** [pimcore/pimcore#9559]
# Bug Report

### Expected behavior

A user with only documents permission to list & view is not able to delete a draft version.

### Actual behavior

A user with onyl list & view permission is allowed to delete a draft version

### Steps to reproduce

1. Create a draft version
2. Log in as a user with only list & view permission on documents
3. The user has the delete draft button
4. If clicked the draft is deleted

**Comment by dvesh3** [comment]
Fixed by #9580
