### ISSUE TITLE
Fieldcollection / block collapsable/collapsed is not working

### ISSUE THREAD

**Issue by mbaer-tr** [pimcore/pimcore#9569]
Env
Pimcore 10.0.6

Expected behavior

- Fieldcollection panel layout collapsable/collapsed is working, when using in other class
- Block collapsable/collapsed in fieldcollection is working , when using in fieldcollection

Actual behavior

In both cases there is no possibility to collapse/uncollapse both elements.

Class: 
![Bildschirmfoto 2021-06-25 um 08 42 49](https://user-images.githubusercontent.com/86462150/123381788-797ad780-d591-11eb-9785-652d7a7ea8cd.png)

Block - not collapsable: 
![Bildschirmfoto 2021-06-25 um 08 52 31](https://user-images.githubusercontent.com/86462150/123382865-bb584d80-d592-11eb-8912-8e95439c95a9.png)

![Bildschirmfoto 2021-06-25 um 08 44 54](https://user-images.githubusercontent.com/86462150/123381946-a5965880-d591-11eb-9585-66e0b052902d.png)

Fielcollection - not collapsable:
![Bildschirmfoto 2021-06-25 um 08 52 42](https://user-images.githubusercontent.com/86462150/123382890-c14e2e80-d592-11eb-80e4-7714e5a39be2.png)

![Bildschirmfoto 2021-06-25 um 08 43 41](https://user-images.githubusercontent.com/86462150/123381999-b47d0b00-d591-11eb-8f7c-9dfec64c1d21.png)

**Comment by fashxp** [comment]
should be fixed in current versions
