### ISSUE TITLE
[Object Bricks] Weird behavior with inheritance

### ISSUE THREAD

**Issue by matthiashamacher** [pimcore/pimcore#9573]
# Bug Report

It seems that it is not possible to change Object Bricks in Child Objects if they are set in the Parent Object.

The problem is reproducible in Pimcore X as well as in previous versions.

### Expected behavior
Object Bricks can be changed in Child Objects.

### Actual behavior
Object Brick from the parent is readded each time

### Steps to reproduce
1. Create a class with Inheritance enabled and an Object Brick Field that has the limit set to 1
2. Create two Object Bricks and add them to the created class
3. Create a test Object where you set the Object Brick to one of them
4. Create a Child by adding another Object under the first one
5. Save the child

#### First case
1. Remove the Object Brick in the Child
2. Save and reload the Object

Result: The Object Brick is added again

#### Second case
1. Remove the Object Brick in the Child
2. Add the other Object Brick to the Child
3. Save and reload the Object

Result: The error "Limit reached" is shown as we set the Limit to 1

Is this the intended behavior for Object Bricks with inheritance?

**Comment by weisswurstkanone** [comment]
Yes it is. Inheritance works on brick level. In other words, there is no way to remove the inherited parent brick which should explain both cases.
