### ISSUE TITLE
Improvement: adding EU cookie checkbox per subsite

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#958]
Actually, EU cookie is enabled for all sites, it could be enabled/disabled per subsites too.

Here is the global configuraiton wich apply to all sites:

![global](https://cloud.githubusercontent.com/assets/9025839/19474020/25eca2fe-952e-11e6-955f-0c2a21698a7e.png)

There could be a checkbox for EU cookie on the subsite edit popin:

![subsite](https://cloud.githubusercontent.com/assets/9025839/19474048/36a530b6-952e-11e6-942b-d1cba6889875.png)

As a very small detail (i know we are going to the perfection ; ) ), maybe fields of the form could be in the same order on the two panel (main site and sub site), as redirect and error page are not in the same order.

---

As we are on this issue, I have see that additionnal domains is only for subsite and there is no such possibility in system config (main site). Is it intended ?

Thanks again for being so reactive on the issues! We really appreciate it.

**Comment by brusch** [comment]
For now we'll keep the global setting. 
If you want to manually deactivate the notice for certain areas on your website/subsites use the following code: 

```php 
$front = \Zend_Controller_Front::getInstance();
$front->unregisterPlugin('Pimcore\Controller\Plugin\EuCookieLawNotice');
```
