### ISSUE TITLE
Duplicate temporary files are created during preview generation of video assets

### ISSUE THREAD

**Issue by nklotter** [pimcore/pimcore#9583]
During video preview generation, it looks like the process is running multiple times in the background, causing duplicate temporary files to be created (same exact file size as the imported asset). It seems like the larger the video asset the more files get generated in the system temp folder...

![image](https://user-images.githubusercontent.com/40795701/123526554-512ccf00-d69e-11eb-9f86-f68b75a6c3b9.png)

**Comment by dvesh3** [comment]
Fixed by #9697
