### ISSUE TITLE
[XLIFF] The export removes zeros

### ISSUE THREAD

**Issue by baloraki** [pimcore/pimcore#9586]
# Bug Report
When I translate an object, zeros that are alone in a HTML Element are deleted.

## Expected behavior
The XLIFF file should always output the content of a field and never remove content from it.

## Actual behavior
Currently, zeros that are alone in an HTML element are removed.

![image](https://user-images.githubusercontent.com/41831573/123604645-53587000-d7fb-11eb-9646-6118a4e23d7a.png)
![image](https://user-images.githubusercontent.com/41831573/123604655-56536080-d7fb-11eb-8650-e2a35ebe34e0.png)

## Steps to reproduce
1. open an object with a WYSWIG field
2. add a 0 in a paragraph, without any other text
3. add a 0 in another paragraph, with some text.
4. Create a table
5. add a 0 in a single cell
6. add a 0 and random text to another cell
7. save the object
8. open XLIFF Export in the menu
9. drag the saved object into it and export it
10. open the xliff file
=> All zeros without text have been removed

**Comment by dvesh3** [comment]
Fixed by #9588
