### ISSUE TITLE
DI Container is broking IDE's static analysis

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#959]
In my opinion if IDE can not perform static analysis we are doing something bad/dirty and this is resulting in harder to understand and maintain source code. Please consider resolving that issue or let me know if I have missed something, I am open to discussion.

**Comment by Yivan** [comment]
I will let Pimcore team answer, but I can just say that two commits, with many PHPDoc improvements, have been done recently to improve autocompletion:
https://github.com/pimcore/pimcore/commit/693adffde6608dbefd683537b9706e51f6d895b5
https://github.com/pimcore/pimcore/commit/b656431c74df454e5158adb2ff65ef07afdc2c2c
Maybe it will solve your problem. You have to try with the last build (at least build 3989).

**Comment by brusch** [comment]
Constructive feedback is always welcome, if you have specific steps how we can improve our product, please let us know. 
If you want to learn more about the DI solution we're using, please have a look at http://php-di.org/#configuration 
(including the topics of auto-completion, static analysis and refactoring support with any IDE).
