### ISSUE TITLE
AutoSave exception on Link-Documents

### ISSUE THREAD

**Issue by dominikschnieper** [pimcore/pimcore#9590]
# Bug Report
AutoSave feature throws an "Access Denied" exception when typing into path-field on Link-Documents.

### Expected behavior
Either disable autosave in Link-Documents or implement it in LinkController.php

### Actual behavior
Error message "Access Denied" is popping up.

### Steps to reproduce
Open a Link-Document and type something into the path field.

**Comment by dvesh3** [comment]
@weisswurstkanone please make sure, these are not run on Assets as well. thanks!

**Comment by dvesh3** [comment]
Fixed by #9660
