### ISSUE TITLE
Ghostscript: PDF thumbnail of a page

### ISSUE THREAD

**Issue by dominikschnieper** [pimcore/pimcore#9593]
# Bug Report
PDF preview of a single page doesn't work with getImageThumbnail(asset, 2). Is also a bug in Pimcore 6.9.

### Expected behavior
Should generate a preview image of the desired page.

### Actual behavior
Generates temp images from page one to n, but all images containing page 1. It takes a lot of time if page 30 is needed obviously.

### Steps to reproduce
Call getImageThumbnail with a defined page bigger than 1.

### Code example
Add '-dFirstPage=' . $page to cmd array like below in Ghostscript.php on line 196.

```php
$cmd = [self::getGhostscriptCli(), '-sDEVICE=pngalpha', '-dFirstPage=' . $page, '-dLastPage=' . $page, '-dTextAlphaBits=4', '-dGraphicsAlphaBits=4', '-r'. $resolution, '-o', $imageTargetPath, $localFile];
```

**Comment by dvesh3** [comment]
Fixed by #9602
