### ISSUE TITLE
[admin][editable] Image editable has no "required" attribute

### ISSUE THREAD

**Issue by HaaseIT** [pimcore/pimcore#9601]
As the title states, I would like to have the image editable (and some more: link, select, video) to have the required attribute.

I can supply a pull request for these. If so, should I make one pull request per editable or pack them all into one? Seperate issue for each or all linked to this issue?

**Comment by dvesh3** [comment]
Hi @HaaseIT, sounds good. You can provide these editable changes in single PR, if change list is not huge. thanks! looking forward to the PR 😉

**Comment by dvesh3** [comment]
Fixed by #9610
