### ISSUE TITLE
object search shows different results based on context of usage

### ISSUE THREAD

**Issue by akno77** [pimcore/pimcore#9615]
# Bug Report

### Expected behavior

1. If I click in the menu "Search => Data Objects" and select an object class type I get all results of this object class
2. If I have an object relation field and click on the search icon the object class is preselected and I get all results of this object class
3. If I have an reverse object relation field and click on the search icon the object class is preselected and I get all results of this object class

### Actual behavior

1. If I click in the menu "Search => Data Objects" and select an object class type I get a result of any type (wrong)
2. If I have an object relation field and click on the search icon the object class is preselected and I get all results of this object class (works correctly)
3. If I have an reverse object relation field and click on the search icon the object class is preselected and I get a result of any type (wrong)

### Steps to reproduce

1. Add a many-to-many object relation field to an object class
2. Add a reverse object relation field to an object class
3. Click the search icon in the relations
4. Use the main data objects search and search for the object class

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
