### ISSUE TITLE
Classification Store: Possibility to limit attribute sets

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#962]
A typical case would be a use of classification store to choose a set of attributes, and no other set must be choose (if a set of attributes of one brick or one classification store has only to be choose to descript the object and fully qualify it).

Actually this can be done using postSave and making a check just one has been added, but having like native feature could be great.

**Comment by brusch** [comment]
Any other opinions? 
@fashxp @weisswurstkanone ?

**Comment by weisswurstkanone** [comment]
You mean restricting it to one group (i.e. set of keys)?

**Comment by fashxp** [comment]
in terms of classification store it is really the question what you restrict. 
in terms of object bricks I can follow the argumentation.

**Comment by brusch** [comment]
@Yivan please create a seperate issue for the object brick feature request
Thanks
