### ISSUE TITLE
[Installer] Custom Migrations are marked done

### ISSUE THREAD

**Issue by matthiashamacher** [pimcore/pimcore#9622]
# Bug Report
If you reinstall Pimcore and have custom migrations added for custom tables, these are also marked as done even though they aren't executed. This results in missing tables.

Normally you don't reinstall your setup that often and this problem should not occur often, but we have a CI environment where we run PHPUnit on fresh installs. They are now failing because of missing tables.

### Expected behavior
The Installer sets only own Migrations as done

### Actual behavior
The installer sets all existing Migrations as done

### Steps to reproduce
1. Create a custom migration ([Documentation](https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Migrations.html))
2. Delete and recreate your database
```bash
$ bin/console doctrine:database:drop --force --no-interaction
$ bin/console doctrine:database:create --if-not-exists
```
3. Run the pimcore-installer
```bash
$ vendor/bin/pimcore-install --no-interaction --ignore-existing-config
```

If you now look in the migration_version table in your Database you see that the created Migration is listed there, but the changes are not executed. This happens because of this part in the install command [Installer::markMigrationsAsDone()](https://github.com/pimcore/pimcore/blob/10.x/bundles/InstallBundle/Installer.php#L474) where all Migrations are set as executed.

### Workaround
After a reinstall delete your Migration from the migration_version table and rerun the `doctrine:migrations:migrate` command so that the Migration is executed correctly.

```bash
$ bin/console doctrine:migrations:version 'App\Migration\Version20210617110000' --delete -n -q
$ bin/console doctrine:migrations:migrate --no-interaction
```

**Comment by brusch** [comment]
Fixed by #9801
