### ISSUE TITLE
Requirements check fails with mysqli

### ISSUE THREAD

**Issue by cipribucur** [pimcore/pimcore#9642]
![requirements](https://user-images.githubusercontent.com/2951736/124126960-7bee9d00-da7b-11eb-8ebc-9f82a02616cb.png)
Happens when pdo is not installed.

**Comment by brusch** [comment]
I think we need to make PDO required, because also Doctrine uses PDO directly, e.g. for parameter type mappings: 
https://github.com/doctrine/dbal/blob/2.13.x/lib/Doctrine/DBAL/ParameterType.php#L17

**Comment by brusch** [comment]
Fixed by #9800
