### ISSUE TITLE
Template Reloading doesn’t work on unpublished page

### ISSUE THREAD

**Issue by aluckmann-dekom** [pimcore/pimcore#9644]
**Action:**
1. Open Pimcore Backend
2. Create new page (type blank)
3. Change Template under „SEO & Settings“
4. Click on „Save“
5. Switch back to tab „Edit“
6. Click on „Refresh“ or clear cache and reload page

<img src="http://p590599.webspaceconfig.de/refresh-button.png" /> <= Refresh-Button

**Expected Behaviour:**

Template Reloads

**Actual Behaviour:**

Nothing happens

**Tested on Versions:**

10.x-dev
10.0.2
6.9.3
6.9.4

(applies to all of them)

**Note:**

This only applies when the page is not published. After a click on the button „Save & Publish“, everything works fine.

**Comment by brusch** [comment]
Fixed by #9657
