### ISSUE TITLE
ObjectBrick with multiple Localized fields are broken after update to 6.9/10.0

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#9646]
# Bug Report
If you have an object brick with multiple localized fields, its impossible to get the fields or save it in the backend.
For example:
![image](https://user-images.githubusercontent.com/998558/124150709-18239e80-da92-11eb-95fd-e6b6c9095b36.png)

![image](https://user-images.githubusercontent.com/998558/124150799-312c4f80-da92-11eb-84f3-7695d44daad0.png)

![image](https://user-images.githubusercontent.com/998558/124150824-37bac700-da92-11eb-8a07-c01a33cab247.png)

This was all working in 6.7

### Expected behavior

Save and Read the fields

### Actual behavior

Getter doesn't exists and save in the admin interface doesn't work

**Comment by dvesh3** [comment]
Fixed by #9654
