### ISSUE TITLE
object grid - csv export - inherited values are not exported

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#965]
should export represent 1:1 data that is shown in the grid?

**Comment by mrudnicki** [comment]
In my opinion, yes, eventually we can add a checkbox which could define if inherited values shouldn't be exported (the checkbox would be placed in the dialog box shown before export action).
Is it still the proposal or could I implement it?

**Comment by fashxp** [comment]
In terms of switch - we should think about enhancing the csv export capabilities anyway, so lets keep that for later.
For now I would say no switch, just always include inherited values.
