### ISSUE TITLE
Improvement: Linked document for incomplete email settings doesn't have any information about email settings.

### ISSUE THREAD

**Issue by HaaseIT** [pimcore/pimcore#9665]
This links to:
https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Email_Framework/

**Comment by dvesh3** [comment]
@HaaseIT Sorry, I didn't get your point. could you please elaborate? thanks!

**Comment by HaaseIT** [comment]
Good morning.
When the email-settings are incomplete, you get a notification linking to this document.

This document doesn't contain any info on how to set up the email-settings, only on how to use emails in general.

I would suggest to either link to some other place, guiding a user on how to set up the email-settings, or to add this guide on the linked page.

**Comment by dvesh3** [comment]
Fixed by https://github.com/pimcore/pimcore/commit/a657dadfe8ee636efb01c085e1804c63f8075f99
