### ISSUE TITLE
[Bug]: Drop target Icon misplaced in firefox

### ISSUE THREAD

**Issue by petritz** [pimcore/pimcore#9682]
### Expected behavior

The drop target icon is placed correctly on the end of the input field. 

See the example in the chrome webbrowser:
<img width="710" alt="grafik" src="https://user-images.githubusercontent.com/7904630/124493902-71534100-ddb6-11eb-84c9-aaf5e4d464ba.png">

### Actual behavior

In firefox (89.0.2) on mac (10.15.7) the icon is overlapping with the selection. See the screenshot:
![grafik](https://user-images.githubusercontent.com/7904630/124494014-9ba4fe80-ddb6-11eb-8c3c-993d21f9a8e0.png)

### Steps to reproduce

View any data object that has a relational field.
1. Visit https://demo.pimcore.fun/admin/ on firefox
2. Open Data Objects > Product Data > Cars > ac cars > Cobra 427
3. See the issue

**Comment by NiklasBr** [comment]
Looks like `.pimcore_droptarget_display div` need `flex: 1;` to be fixed.

**Comment by brusch** [comment]
fixed by #9799
