### ISSUE TITLE
[Bug]: Grid does not display the default data for Classification Store

### ISSUE THREAD

**Issue by wujku** [pimcore/pimcore#9702]
### Expected behavior

Classification Store attribute for product class has Specific Setting: localized set to `TRUE`.
I create few Key Definitions, I assigned them to a group and I filled them with default data for few Products (I left the tabs with languages blank).
I can see default data for Key Definition column in the grid view.

### Actual behavior

I can not see default data for Key Definition column in the grid view.

### Steps to reproduce

This line ignores fallback language and default language for Grid view. 

https://github.com/pimcore/pimcore/blob/53e8d494faea79fc17c7e43071f0bbb59a4b7bfe/models/DataObject/Service.php#L352

Is this correct behavior?

**Comment by wujku** [comment]
Related: https://github.com/pimcore/pimcore/issues/8051

**Comment by weisswurstkanone** [comment]
Hello @wujku Just for clarification. In the admin UI you will always see the data as it is. No fallbacks or whatsoever. It is about maintining the data and not about the output channel.

**Comment by wujku** [comment]
@weisswurstkanone So if I have the data set for the default language, I should choose the default language in the grid settings.
