### ISSUE TITLE
[Feature]: Update CKEditor more often

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#9704]
### Feature description

> [current version](https://github.com/pimcore/pimcore/blob/10.x/bundles/AdminBundle/Resources/public/js/lib/PIMCORE_MODIFICATIONS.md): 4.14.0 

>[ most recent version](https://github.com/ckeditor/ckeditor4/blob/major/CHANGES.md) 4.16.1 (released May 19)

A lot of bug fixes and even a security patch is missing, relying on memory to do it is destined to fail.

Alternatively, do not bundle at all and let us install this on deploy with NPM maybe?

**Comment by brusch** [comment]
It is already updated in `10.x`, see: https://github.com/pimcore/pimcore/blob/10.x/bundles/AdminBundle/Resources/public/js/lib/ckeditor/CHANGES.md#L4 😉

But you're right, it would make sense to manage that by NPM.
