### ISSUE TITLE
[Feature]: Improve documentation for migration from Pimcore 6 to 10 about when switching PHP version.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#9707]
### Feature description

Hello,

Migration from Pimcore 6 to 10 is described in this documentation page:
https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/Updating_Pimcore/V6_to_V10.html

1- When switching PHP version ?
The PHP software version needs to be handled carefully during this upgrade as Pimcore 6 only work with PHP < 8 and Pimcore 10 only work with PHP >= 8.
Actually, this page gives the procedure to proceed to the upgrade, but there are no hints on when PHP version must be changed ?
I imagine the section `IMPORTANT CHANGES PRIOR THE UPDATE!` must be done while PHP  < 8 and the section `CHANGES AFTER THE UPDATE!` must be done in PHP >= 8 ?

2- When running composer update ?
When must be run "composer update command" ? I imagine after `IMPORTANT CHANGES PRIOR THE UPDATE!` and before `CHANGES AFTER THE UPDATE!`, but having it clearly written will help to follow the process.

Adding those informations (when switching PHP version and when running composer update) would surely help to prepare/doing the update process.

Thanks a lot!

**Comment by brusch** [comment]
@Yivan Thanks for input. Can you maybe just add your suggestions directly to the docs? Just click die button _Edit on GitHub_ in the top right corner :) That would be nice, thanks a lot in advance!

**Comment by Yivan** [comment]
@brusch I didn't know it was possible to directly create a PR this way for the documentation, this is really great!
This makes really easy for contributors to improve documentation (no need to update forks, use git, etc.).

You should make the "Edit on GitHub" link more prohiminent/bigger/colored with a lead line like "Works with us to improve the documentation by directly submit patch on it in a few seconds!" (you see the idea! ; )).
I refer very often to documentation but never saw this link !!! :-) Knowing it exists now, I will surely provide more doc fix easily when I read the doc and thinks it needs some precision for instance.
I am sure other developpers didn't know too and can improve docs as well.

By the way, i submited the PR for this issue: https://github.com/pimcore/pimcore/pull/9718

Thanks!

**Comment by brusch** [comment]
@Yivan thanks a lot for your PR - looking forward to see more in the future 😊
