### ISSUE TITLE
[Bug]: Error during migration from 6 to 10.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#9708]
### Expected behavior

Dunring upgrade from Pimcore 6 to 10, migration should works fine.

### Actual behavior

Migration Version20210107103923 failed with message:

```
[error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20210107103923 failed during Execution. Error: "Class "Pimcore\Model\DataObject\ClassDefinition\Data\ReverseManyToManyObjectRelation" not found"
```

Please see:
![image](https://user-images.githubusercontent.com/9025839/124956287-220c4b00-e018-11eb-816e-abf811db2bf8.png)

### Steps to reproduce

Upgrade from the last 6.9 to Pimcore 10.0.7

**Comment by Yivan** [comment]
Maybe linked to this: https://github.com/pimcore/pimcore/commit/8c067c979ff2aed6e793cafcab120c9177509bc4

But no guidelines is given nor here: https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/index.html, nor here: https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/Updating_Pimcore/V6_to_V10.html

So for now we are stuck : )

**Comment by dvesh3** [comment]
@Yivan Seems like you have class definitions with old class name for ReverseObjectRelation field. I have re-introduced BC layer in #9711 for 10.0.8. Meanwhile, you can re-save classes with ReverseManyToManyObjectRelation field on 6.9 before upgrade to 10.

**Comment by dvesh3** [comment]
Fixed by #9711

**Comment by Yivan** [comment]
@dvesh3 Thanks for your action on this issue!

Actually, I cannot resave the class as I am already on the end of the migration process and I would prefer not restarting from 0 (would be the last chance! ; ).
So I tested with the patch you have done, adding to `models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php`:
```
//TODO remove in Pimcore 11
class_alias(ReverseObjectRelation::class, 'Pimcore\Model\DataObject\ClassDefinition\Data\ReverseManyToManyObjectRelation');
```

After this I have done some cleanup/refresh:
```
/usr/local/bin/composer -v dump-autoload --optimize
php bin/console pimcore:cache:clear
php bin/console cache:clear
```

Good news is now for instance the command `php bin/console cache:clear` works (before it complains about this error).

**But bad news is the migration always fails with this same error... so I think the current patch you have done won't fix the problem.**
I always have this message:

![image](https://user-images.githubusercontent.com/9025839/125142652-8d3d4680-e118-11eb-91bd-7c066b2f692e.png)

If you have idea/provides another fix I, can test it.
(As the command `php bin/console cache:clear` works now the alias is well registered. But for the migration script, as there is always the error, I suspect maybe the migration use another way to load the class like it doesn't see/use the alias...)

Thanks!

**Comment by dvesh3** [comment]
@Yivan thanks a lot for pro-active testing 👍  you are right, It simply looks up for the class during un-serialization, so it does not use autoload namespace. I have pushed a follow-up commit https://github.com/pimcore/pimcore/commit/ba13925c0126c1316a4b6437ca3cd4cee1b4ee9c which also re-introduces class file for BC layer. I have tested this should fix the problem with class rebuilds.

**Comment by Yivan** [comment]
@dvesh3 Thanks again! I confirm the new patch works fine now, all is ok : )
