### ISSUE TITLE
[Bug]: Upgrading from 6.9.x to 10.0.6 - issue Undefined array key \"subContainerType\" in admin/element/get-nice-path

### ISSUE THREAD

**Issue by moiashvin** [pimcore/pimcore#9714]
### Expected behavior

Opening an object in PIM works without any issue.

### Actual behavior

![image](https://user-images.githubusercontent.com/27417231/125082482-50e9f600-e0d8-11eb-8c62-7d6ea6e687ca.png)

### Steps to reproduce

In class definition, I have a field name characteristics with type "Field-Collections"

Field-Collection has "characteristcType" - Many-To-One relation and "characteristics" Many-To-Many-relation
The "characteristicType" also use the Formatter Service / Class for more user-friendly path name

Upgrading to PIM 10 cause issue.

The method admin/element/get-nice-path is called in back-end
And response is: 
message: "Warning: Undefined array key \"subContainerType\""
success: false
trace: [{,…},…]
traceString: "in /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/ElementController.php:882\n#0 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/ElementController.php(563): Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\ElementController->getNicePathFormatterFieldDefinition(Object(App\\Model\\ProductData\\Product), Array)\n#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(157): Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\ElementController->getNicePathAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(79): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#3 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(199): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#4 /var/www/html/public/index.php(36): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#5 {main}"

**Comment by moiashvin** [comment]
It seems that class vendor\pimcore\pimcore\bundles\AdminBundle\Controller\Admin\ElementController.php line 882 misses the isset($context['subContainerType'])

Should have been 
 if (**isset($context['subContainerType'])** && $context['subContainerType'] == 'localizedfield') {

**Comment by dvesh3** [comment]
Fixed by #9715
