### ISSUE TITLE
Object Classes Permissions

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#972]
Actually, using the search tools (Search object, Search & Replace) user can choose the class and object and all classes are listed.
In the role/user permission it can't be limited, neither in the perspective.
Purpose of this improvement is to have a way do to it, because some simple user don't have to know all the entity, but could need the search feature.

Proposition:
- The easier seems to use perspectives
- Another way could to limit to the authorized class in the role/user panel (but those class are limited only for "creation" so it would be strange maybe).

**Comment by brusch** [comment]
I think if we ever touch this topic again we should implement a more complete approach and transform the existing *Allowed types to create* permission into "Restrict access to*, no matter if used in the context of search, create or in the tree ... 

![image](https://cloud.githubusercontent.com/assets/142037/19674315/835f052c-9a87-11e6-880b-8c41cc429cfe.png)

**Comment by brusch** [comment]
But this is still subject to discuss - to be honest: I like to keep things simple and I don't like too many permissions ... 
Any other thoughts on this?

**Comment by Yivan** [comment]
I agree, it need to be keep simple, because their is alredy powerfull and complexe user management, and adding complexity to the final end user should be avoided.

For my part, I would prefer keeping as it is "_Allowed types to create_" permission, as it make sense. User can be disallowed to create some class but can see the object. Ramplacing it by a "_Restrict access_ to" permission we will loose this possibility. So better to keep like it is this part.
Using a restrict access based on classes will really complexe as it could conflict with directory access (workkspace).

At the beginning, this issue was more for visual aspect of not displaying all class name on the search tools.   We have a project with more than 20 classes, and some pimcore user work with only a few class. But if they use the search tools, they see all 20 classes in the select dropdown, some of them with complicate name... For those user the search experience is not so friendly. That was the intitial purpose.
You can have the same problem on the e-commerce demo online, search provide so much class.

Actually, i don't see a easy way ; ) Using perspective is the simplest for coding aspect i think, but as you said it add another options for perspectives so make thing complicated.
Maybe to keep it simple, just have the possibility to hide the class slector in the search tools so user could search at least (but he cannot refined by class) and security information is better as all class name aren't displayed. It could be a simple bolean for instance:
"hide_class_searchtool" => 1
