### ISSUE TITLE
[Improvement]: Performance optimization for Mass Data Import operations via avoidance of redundant DB update operations

### ISSUE THREAD

**Issue by wcchew76** [pimcore/pimcore#9720]
### Feature description

Performance improvement suggestion are as per title description.
When tracing underlying SQL operations for different Admin UI operations, discovered that many of the core DataObject operations are excessively chatty. 

Whilst not a big deal on single record operations, performance severely impacted if we need to perform mass data import, e.g. using Pimcore's Data-Importer.

For example, in models/DataObjects/AbstractObject.php --> update() function, which will be called by save() function as well, the deleteAllProperties() and getProperties() operations are not necessary if intent is to update Data Object attributes via Data importer only.

![image](https://user-images.githubusercontent.com/87258896/125186471-25444880-e25d-11eb-9ed0-cb1bb9b18791.png)

Perhaps Data Object APIs can provide a "Save-Attributes-Only" switch which will ignore other attributes such as Properties, similar to ability to turn off Versioning (ref: https://pimcore.com/docs/pimcore/current/Development_Documentation/Tools_and_Features/Versioning.html#page_Turn-off-Versioning-for-the-Current-Process) to speed up Mass Data Import operations.

**Comment by fashxp** [comment]
I would prefer a dirty state for the properties as we have it for certain data types already.

**Comment by brusch** [comment]
We're doing this for dependencies as well, which is quite similar: 
https://github.com/pimcore/pimcore/blob/53449686033cdb9dd10f5c64c9636b8c725e2a35/models/Dependency/Dao.php#L11

Of course this needs to be done for Assets and Documents as well -> in a central place 😉

**Comment by mcop1** [comment]
What we could do is:

1.) Check if the properties have changed
2.) If yes, then remove all properties and insert the new ones
3.) If not, then do nothing of course

Should be implemented for other types too (Assets, ...)
