### ISSUE TITLE
[MigrateStorageCommand] Use parallelization trait

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#9723]
### Feature description

 Use the parallelization trait for parallel processing of storage migration. please see https://github.com/pimcore/pimcore/pull/9703#issuecomment-877076561

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
