### ISSUE TITLE
Perspective - Custom views: position for both + better documentation

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#973]
We had a look trying new perspective and custom views. They are so so great.
Here are just some minor imporvements based on our first experience with them.

Actually "position" could be defined on both, it seems it isn't needed on custom views as the pespective position (left/right) is used.
**1-** So it may be remove from custom views maybe ?

**2-** I think it should be metionned on the custom views documentation page that it need perspective, if I am not wrong.
(maybe we miss something and the custom views could be used without perspective, but nothing on it on the documentation on the custom views page).

**3-** Documentation for the parameters
It lead us that the documentation (maybe it is currently being updated as you are making some change in the documenation) could be more detailled, parameters by parameters for perspectives and custom views.
Some a the field are not self explainatory, and make using perpective/customviews not so easy as it should.
For instance there is a "condition" parameter for custom view, an we don't know the puspose, as there is "where" parameters too.
It could be something like that in the documentation:
```
[
    "treetype" => "asset", // type of element: document | asset | tree
    "name" => "Panama Impressions", // name of the custom view
    "condition" => NULL, // condition for...
    "icon" => "/pimcore/static6/img/flat-color-icons/camera_identification.svg", // path from the root to the image
    "id" => 1, // unique id
    "rootfolder" => "/examples/panama", // element fullpath
    "showroot" => FALSE, // display the rootfolder: FALSE | TRUE
    "classes" => "", // allowed classes to be listed separated by comma
    "position" => "left", // position of the panel: left | right
...
```
And the same way the file exemples customviews.example and perspectives.exemple in /website/config could contain those too to help developper to use those nice features.

**4-** Security/confidentiality of the data warning
Finally i think one point should be mentionned and alert the user in the documentation: pespectives and custom views manage only displaying and not access right. So it is not because an objects is not listed because we use the join/having/where feature of customviews it could not be accessed. It can depending the right configured in its workspace. It make sense workspace is the only way to control user rights. But a developper could be fooled thinking perspective/customviews can be used this way for limiting access.
(at the origin we tryed them because we wanted some limited user to access object only responding to a specific sheme, and great they are not displayed but we can always access by id for instance or a malicious user by ajax request).

**Comment by brusch** [comment]
1. No, custom views can be used without perspectives so it makes sense to have them in both 
2. No, you don't have to use perspectives to use custom views
3. https://github.com/pimcore/pimcore/blob/2338e6f7d61b36bdbaa98d3623fe621880c94544/website_example/config/customviews.example.php#L3-L3 is't this enough? if not, PRs ale always welcome :) 
4. note added to the docs

**Comment by brusch** [comment]
d0292e6912633a3688ba02f7cc98ebcd9dbd07d0
4edac374403e675830db0875bf1416328b5b2288

**Comment by Yivan** [comment]
1. Ok I found that custom view are use automaticaly if no perspective.php was activated.
2. Same than 1

3. I was working on an updated Pimcore, so customview_exmple and perspective_exemple was not uptodate (it seems those files are not in the update process).

Just small improvement could be done, as i was trying them for first time i give you my experience feedback:
 - **Just here:
https://github.com/pimcore/pimcore/blob/2338e6f7d61b36bdbaa98d3623fe621880c94544/website_example/config/customviews.example.php#L32
This is "import Csv" and not "importFromCsv".
(maybe you should check others, i found it just because i need to hide this one and it wasn't working with importFromCsv, so i looked into he JS code to found the good one)**
 - And maybe just explain more difference between "where" and "condition" could help developpers (i was myself struggling with those and opened a question on the forum : https://groups.google.com/forum/#!topic/pimcore/Nfv_I642Z_4)
 - And in perspective saying that it has precedence on customviews (for position, name...).

4 Thanks!
 - Maybe you could add the same security note to "custom layout" too (because it send all datas in the ajax request when opening an object).

Aside those point, documentation on those subject seems perfect for people discovering them! Thanks a lot for your work on it.
