### ISSUE TITLE
[Bug]: Video previews are no longer working

### ISSUE THREAD

**Issue by nklotter** [pimcore/pimcore#9731]
### Expected behavior

Video previews should be playable from within the Asset section of the Admin console ("Preview" tab)

### Actual behavior

Video previews do not play

----------

See line 1632 of the Pimcore\Bundle\AdminBundle\Controller\Admin\Asset\AssetController class. The following code modification resolved the issue...

REPLACE =>
preg_replace('@^' . preg_quote($asset->getPath(), '@') . '@', '', urldecode($thumbnail['formats']['mp4']))
WITH =>
preg_replace('@.*?' . preg_quote($asset->getPath(), '@') . '@', '', urldecode($thumbnail['formats']['mp4']))

### Steps to reproduce

1. Upload a video
2. Wait for the preview to generate
3. Click on the "Play" button

**Comment by brusch** [comment]
@nklotter for me this works, also in the demo. 
Can you please share more details on it, like which path the asset has and how to reproduce the issue on our [public demo](https://github.com/pimcore/pimcore#demo-community-edition). 

Thanks!

**Comment by nklotter** [comment]
@brusch We're using AWS Cloudfront to house our external assets and thumbnails. The absolute URL paths are set under the assets -> frontend_prefixes section of the config.yaml.

Thanks for the quick response!

**Comment by brusch** [comment]
@nklotter Ah, got it - but then we'd need to implement a different fix. The reason why it fails in this case is that `getPath()` is prefixed with `https://tavi-12345678990.cloudfront.net/....` 
Will try to provide a fix soon 😉

**Comment by nklotter** [comment]
@brusch Awesome, thanks for looking into this!
