### ISSUE TITLE
[Bug]: Areablock groups using wrong language

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#9739]
### Expected behavior

Show group labels in the correct backend language (set to EN).

German document:
![image](https://user-images.githubusercontent.com/90033/125425074-87206332-566c-4172-b80d-dc3496487c41.png)

English document:
![image](https://user-images.githubusercontent.com/90033/125425197-0f833ae8-fb04-4692-84f1-b3c88abc2a57.png)

### Actual behavior

Group labels are using the frontend locale, not the backend locale.

### Steps to reproduce

Create a pimcore_areablock with groups and set the needed translations:

![image](https://user-images.githubusercontent.com/90033/125425545-abc52239-5e12-4ba7-84dc-8476d05f5552.png)

Pimcore version: 10.x-dev|24d099f2d9dd56e7b89910fbe532d35f5972ece5

**Comment by brusch** [comment]
Fixed by #9804
