### ISSUE TITLE
New Events for User/Role Model: user.preSave user.postSave user.preDelete user.postDelete

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#974]
One event could be added in the Event Manager: when a new user is created in the backend.
We could think of pre/post add/update/delete user, if we want generic interaction possible.

For instance instance it could be used by the developper to run some code which will create some necessary folded automaticaly (based on the role) and attribute the needed right to it. It would be a way to prepare the workspace for the user with custom folder...
Actually it has to be done manually by the administrator each times he create a user (for element wich cannot be configured at the role workspace level, **like a dedicated folder for this user as a classic use case**).

In the same time, the documentation could be updated on this page https://www.pimcore.org/docs/latest/Administration_of_Pimcore/Users_and_Roles.html with some code exemple to create an user and configure it by the API (actually we have to dig deep in the code :-) )

**Comment by brusch** [comment]
| Name | Target | Parameters | Description | 
| ---- | ------ | ---------- | ----------- |
| `user.preSave` | `Pimcore\Model\User\AbstractUser` | - |  |
| `user.postSave` | `Pimcore\Model\User\AbstractUser` | - |  |
| `user.preDelete` | `Pimcore\Model\User\AbstractUser` | - |  |
| `user.postDelete` | `Pimcore\Model\User\AbstractUser` | - |  |

**Comment by brusch** [comment]
Should work for all 4 types based on `AbstractUser`: user, userfolder, role, rolefolder

**Comment by Yivan** [comment]
@Brush can i make a pull request on this or do you prefer to handle it / or it is in warning/studying ?
Thanks.

**Comment by brusch** [comment]
You can make a PR :) Thanks!

**Comment by Yivan** [comment]
@brush PR done, thanks!

**Comment by brusch** [comment]
Closed by #1204
