### ISSUE TITLE
[Bug]: Document qr code preview not possible without write permission on var folder

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#9742]
### Expected behavior

The qr code image for the document preview get saved to `var`, this should get changed to `var/tmp`.

Background: Not all production environments support write permission an all folders. `var/tmp` would be a better place to store the temporary qr code file.

### Actual behavior

File can't get saved directly to var without permissions.

### Steps to reproduce

Remove write permissions on var folder.

**Comment by brusch** [comment]
Fixed by #9765
