### ISSUE TITLE
[Feature]: Improve admin translation language list

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#9743]
### Feature description

It looks like the config for `admin_languages` has been removed from `config/system.yml`. Now there is a long list of unneeded languages in the admin translations.

Is there an improvement planned in https://github.com/pimcore/pimcore/issues/6568? In my case there should only be DE and EN available.

![image](https://user-images.githubusercontent.com/90033/125431602-431323c8-bd5e-4d5d-b1eb-1b3987b78251.png)

**Comment by dvesh3** [comment]
Hi @valentin- you can still use `admin_languages` under `pimcore_admin` node in config.yaml:
![image](https://user-images.githubusercontent.com/5137917/144880055-d3647574-ec9c-4382-a750-bc1be875f688.png)

**Comment by valentin-** [comment]
@dvesh3 that's true but saving the system settings in the backend removes the defined `admin_languages`. I guess this isn't intended and should be improved.

**Comment by dvesh3** [comment]
The behavior was changed with Pimcore X as most of the config moved from System settings to `config.yaml` https://github.com/pimcore/pimcore/issues/8754

**Comment by valentin-** [comment]
Ah yes i was focused on the `system.yml` file, defining the `admin_languages` in the `config.yaml` works fine. Thanks for clarification.
