### ISSUE TITLE
[Bug]: Document translation with inheritance uses content from deleted bricks

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#9749]
### Expected behavior

Documents with inheritance should only use content from editables which are still available.

### Actual behavior

Created text bricks on the translated document (can) reuse deleted editable contents from the source document.

### Steps to reproduce

Brick = simple brick with pimcore_input()

1. Create a new document
2. Add a brick with "Text 1"
3. Add a brick with "Text 2"
4. Delete brick "Text 2"
5. Create translation with inheritance for the given document
6. "Text 1" is initially visible
7. Add another brick, it's prefilled with "Text 2" (deleted brick)

**Comment by brusch** [comment]
Fixed by #9922
