### ISSUE TITLE
[Feature]: Asset versions hardlink alternative

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#9754]
### Feature description

The introduction of the Flysystem filesystem abstract layer dropped the support for asset version hardlinks if the binary data does not change during saving the asset (as object storages do not support hardlinks). Therefore we now have two disadvantages:

- Higher storage cost.
- Slower save processes (especially on cloud environments).

An alternative approach would be to create just a link in the database to the relative path of the original asset version file instead of creating a copy. The version cleanup mechanism then needs to be adopted too (delete version files which are not linked to any version only).

see also https://github.com/pimcore/pimcore/issues/3797

**Comment by brusch** [comment]
Fixed by #3797
