### ISSUE TITLE
[Bug]: [DataObject][User] data of user fields empty again after reloading the data object

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#9756]
### Expected behavior

assigned data is visible

### Actual behavior

when closing and reopening the data object, the data is there ... when just reloading the data object, user fields are empty.

![image](https://user-images.githubusercontent.com/8792145/125579662-d2302aab-dbf3-4072-97bc-9fdb12785b5e.png)

### Steps to reproduce

- create data object class definition with `user` field 
- create data object of that class
- assign value to `user` field and save data object
- reload data object --> `user` field empty again

**Comment by dvesh3** [comment]
Fixed by #9760
