### ISSUE TITLE
[Feature]: Asset save asynchronous queue for parts of the save process

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#9757]
### Feature description

Pimcore executes quite a lot of things when a asset gets saved:

- calculation of low quality placeholders
- some image optimizations
- extraction of embedded meta data
- ...?

I've noticed that in an AWS S3 setup that some example 2-3MB PNGs needed about 2-4 sec to be saved. Most of the time was needed by the processes mentioned above.

At least some of them should be delegated to an asynchronous queue.

**Comment by markus-moser** [comment]
Maybe we then can find a better way for this maintenance task too:
https://github.com/pimcore/pimcore/blob/10.x/lib/Maintenance/Tasks/LowQualityImagePreviewTask.php

I have a system with about 1 mio assets and the whole paging through the assets itself really produces a lot of load.

**Comment by brusch** [comment]
Done by #10390
