### ISSUE TITLE
[Bug]: Pimcore\Model\DataObject\ClassDefinition::locateFile(): Argument #1 ($key) must be of type string, null given

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#9759]
### Expected behavior

Command `bin/console pimcore:deployment:classes-rebuild -d` runs without exception 

### Actual behavior

On command  `bin/console pimcore:deployment:classes-rebuild -d`: ![image](https://user-images.githubusercontent.com/5137917/125582422-8ef237fd-aaf2-48a0-9898-d2424cddefba.png)

### Steps to reproduce

1. create a Test class.
2. Delete class definition file from `var/classes`
3. Run command  `bin/console pimcore:deployment:classes-rebuild -d`

Regression of #8774

**Comment by brusch** [comment]
Fixed by #9763
