### ISSUE TITLE
[Bug]: Data Object Class "Label Width" within localized fields

### ISSUE THREAD

**Issue by akno77** [pimcore/pimcore#9761]
### Expected behavior

If you set a label width "150" for localized fields the label width is as expected.

### Actual behavior

The label width is not "150" but "1505px" in the dom element and breaks the whole field display.

### Steps to reproduce

- Add localized fields to an data object class
- Set label width "150" for the localized fields
- Save the class
- Open class item

**Comment by weisswurstkanone** [comment]
This seems to be the reason. 

![image](https://user-images.githubusercontent.com/6142086/125814276-1403e09a-1d12-4521-a8fc-9ea67c1a5c1c.png)

Somehow related to https://github.com/pimcore/pimcore/pull/6899
@blankse any idea how to tackle this in a perfect way ? 🤔 

In my example the label width is 170 and the labelStyle is 1705 then

**Comment by blankse** [comment]
@akno77 I create an PR #9780 
Can you test it?

**Comment by akno77** [comment]
@blankse it works

**Comment by brusch** [comment]
Fixed by #9780
