### ISSUE TITLE
[Bug]: Video preview is not seekable in Chrome

### ISSUE THREAD

**Issue by nklotter** [pimcore/pimcore#9766]
### Expected behavior

Videos should seek to specific times while previewing in the Chrome browser

### Actual behavior

Videos are not seekable (forward or backward) using Chrome. However, it works properly with Firefox.

### Steps to reproduce

1. Play a video preview using Chrome browser
2. Drag seek bar forward and/or back
3. Video does not play from specified position

*** POTENTIAL FIX ***
[AssetController->serveVideoPreviewAction]

$fs = $storage->fileSize($storagePath); // fetch video preview file size
$stream = $storage->readStream($storagePath);

return new StreamedResponse(function () use ($stream) {
    fpassthru($stream);
}, 200, [
    'Content-Type' => 'video/mp4',
    'Content-Length' => $fs, /* provide video file size in response */
    'Accept-Ranges' => 'bytes' /* allow partial requests */
]);

**Comment by brusch** [comment]
@nklotter thanks for reporting, can you maybe provide a PR with the fix? That would be awesome 😊

**Comment by dvesh3** [comment]
Fixed by #9923
