### ISSUE TITLE
Best Practice Guide for Testing

### ISSUE THREAD

**Issue by rightsaidjames** [pimcore/pimcore#977]
The Pimcore documentation has a `Testing` page in the `Development Tools and Details` section:
https://www.pimcore.org/docs/latest/Development_Tools_and_Details/Testing.html

However it is currently blank. As someone who does a lot of Pimcore-related testing (mostly from the frontend and the Pimcore admin interface), I'd like to contribute to this page/sub-section in some way. 

However before I start I'd like to know:
- What would maintainers, developers, testers, Pimcore users (e.g. content editors), etc. expect to see here?
- What types of testing are in scope for the documentation? Functional testing, unit testing, integration testing etc.

I look forward to hearing what other people think about this.

**Comment by brusch** [comment]
Thank you very much for your offer! 
At the moment we're planning to create a guide based on the [Codeception](http://codeception.com/), so we like the idea of combining unit tests with functional testing.

**Comment by fashxp** [comment]
see https://pimcore.com/docs/5.x/Development_Documentation/Development_Tools_and_Details/Testing.html ...
