### ISSUE TITLE
User can see information not allowed in custom layout.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#978]
In the demo website, create an user with a custom layout for `news `class allowed with just `title `and `shorttext`:
![customlayout](https://cloud.githubusercontent.com/assets/9025839/19598356/abc2b012-979a-11e6-898b-148bacd65d1f.png)
Assign this custom layout to the user and log in with his credential on Pimcore.

We can see the other layout components in the grid configuration, here `Date & Images`:
![grid](https://cloud.githubusercontent.com/assets/9025839/19598399/ca34d2aa-979a-11e6-82c1-13a4608d0250.png)
Solution; layout components with no children should be hidden from the grid configuration, so no confidential information (even if it is just a name of the layout component is show, because the name can be sometimes not likely to be show to the user editing object, like a tab "editor reviews" if we don't want he know we review it : )) ).

More problematic and dangerous is the version tab, it show all information, without considering the custom layout:
![vers2](https://cloud.githubusercontent.com/assets/9025839/19598594/f3062a98-979b-11e6-9b87-2c5abfabf4c7.png)
It lead us to a choice:
- if custom layout is used, we don't display the version tab for security reason.
- change the version tab/comparison so it show only fields of the custom layout: better because user can always use version tab to see changes.

I try to check all hole which would permit to a limited user to see not allowed information from custom layout, but it seems the two i found are the only one. Maybe you should check on your side i didn't miss other panel/functionnality where it could lead to information displayed that the user has not to see because of custom layout.

Thanks a lot.
Best regards.

**Comment by Yivan** [comment]
By reviewing commit (i see a recent change in CSV export), i didn't check user cannot export not allowed field, maybe it needs to be check, as batch assign or other feature like this maybe. Thanks!

**Comment by mrudnicki** [comment]
Hi @Yivan thanks for the request.

I will hide unnecessary layout components from the column configuration.

In order to versions. You can disable versions when you create user workspaces. I don't think it's necessary to add additional expressions responsible for auto-disabling the versions tab...
The second solution you proposed would be cool (relates custom layouts with versions tab). Could you create separated task for it?

**Comment by mrudnicki** [comment]
Hi @Yivan thanks for the request.

I will hide unnecessary layout components from the column configuration.

In order to versions. You can disable versions when you create user workspaces. I don't think it's necessary to add additional expressions responsible for auto-disabling the versions tab...
The second solution you proposed would be cool (relates custom layouts with versions tab). Could you create separated task for that?

**Comment by brusch** [comment]
@Yivan **IMPORTANT:** Custom layouts are not intended to be used for restricting the access to data!
Even if you're using custom layouts for the editing tab, **all** the data is sent to the client, not only the visible fields!

**Comment by brusch** [comment]
The intended use is to customize the editing view ... that's it. Therefore nothing has to be changed.

**Comment by Yivan** [comment]
Thanks for your return. I wasn't aware that it was only for displaying. Checking the ajax request, all is sent yes : )
Maybe at least we can hide in colum configuration layout component wich have no children ? (we be more clean and respect custom layout in displaying it).

Brush, I think **this warning should really be added to the documentation.** Some devolopper can mislead and put in production some project without knowing that custom layout is just display, but user can see all informations. It is really dangerous, some project are based on this assumption (exemple: some object have information we don't want limited editor see, so we use custom layout... in fact it is not protected).
It limit a lot the use of custom layout. Just dispplaying, but open firebug and you get all the data...

What about readonly ? Is it only frontend or are their server checks ? All of this sould be stated in documentation so people know where they go. For instance, the new pimcore Workflow is based on custom layout for the different step, so nice! But if user can inject data during the step it would not be reliable.

It would be very nice to limit the data returned considering custom layout, as checking edit rights when saving considering custom layout. **Do you think an improvement issue could be open on this subject ?**
Because we where honestly thinking custom layout where the way to limit data access inside object, and from our undestanding their is not for now a "field" level rights in Pimcore so. It will be a big feature and not so hard to do maybe as we already have custom layout ?

**Comment by Yivan** [comment]
Aside from this, brush, do you know a way to protect our custom layout, or provide to user a custom edit panel ? We need to make it with plugins maybe, hooking the preOpen controller and flush fields not in custom layout ?
Thanks again, this issue is so dangerous for project involving custom layouts.

**Comment by fashxp** [comment]
have a look at the `admin.asset.get.preSendData` event. here you can modify the json that is sent to frontend.

**Comment by Yivan** [comment]
Thanks fashxp, we will try to make our own plugin to consistently filter based on custom layout using this event.

Do i open a new issue as imporvement to add a proxy-edit, like there is actually for grid listing:
![gridproxy](https://cloud.githubusercontent.com/assets/9025839/19601530/fcd6e05e-97a9-11e6-8e50-6004b2476b2a.png)
Grid listing is called by:
/admin/object/grid-proxy/classId/2/folderId/2?xaction=read&_dc=1477059362049

Same thing could be done to editing, at least to provide some security ?

**Comment by brusch** [comment]
I think at some point it's easier to create custom editing forms using Bootstrap or any other toolkit. 
We know that there are millions of different use-cases for Pimcore out there and this makes it even more complicated to keep the core lean and maintainable. 

Thanks for your understanding.

**Comment by BlackbitNeueMedien** [comment]
@Yivan Do you have created such a plugin or found another way to ensure that certain fields can only be edited when the user is allowed to in his custom layout?

**Comment by BlackbitDevs** [comment]
Just for completeness: Since #9730 a user can only see the fields from his allowed custom layouts in the grid. Or in other words: Since then it is possible to restrict the fields which certain users / groups can see / edit.
