### ISSUE TITLE
FullPageCache Optimization

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#9782]
### Expected behavior

The full page cache should require as less resources as possible. 

### Actual behavior

Currently the `FullPageCacheListener` has the `kernel.request` priority `6`, but this is actually after the Symfony routing and therefore also after documents and other information is resolved. 
So even if a page get's delivered by the full page cache, some SQL statements and quite some code get's executed, which is probably not really necessary. 

### Steps to reproduce

Deliver a page from full page cache and see SQL log.

**Comment by fashxp** [comment]
consider targeting in this context
