### ISSUE TITLE
[Improvement]: Identify and remove redundant queries

### ISSUE THREAD

**Issue by wcchew76** [pimcore/pimcore#9790]
### Improvement description

Trying to reverse engineer Data Objects save operations to improve performance by inspecting MySQL operations when performing front end interactions to Admin Backend.

Notice that just performing the following interactions (within 5 seconds) while tracing MySQL operations there are 10 instances of "SELECT id FROM assets LIMIT 1" queries (with "Asset" not expanded).
1) Open "Data Object record"
2) Edit one field.
3) "Save and Publish" the record.

In production environment, if we have huge volume of records in "assets" table, this impose uneccessary load to the database.

**Comment by brusch** [comment]
Can you please describe the topic more in detail or even provide a PR for the improvement. 
Otherwise I'd have to close the issue as it is too generic. 
Thanks a lot!

**Comment by brusch** [comment]
Closed due to inactivity. Please feel free to continue the discussion or provide the missing information on this issue, we'll then reopen it if necessary. Thanks a lot!
