### ISSUE TITLE
[Improvement]: Make personalized target groups recognizable in documents

### ISSUE THREAD

**Issue by akno77** [pimcore/pimcore#9806]
### Improvement description

If you personalize a document for a target group you cannot see which target groups have personalized content in the target group dropdown. So if you make changes to the default content you don't know if you maybe have to modify some personalized content, too. And to check every target group content is not a good solution.

So it would be nice if the target groups with personalized content are marked somehow in the dropdown list.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
