### ISSUE TITLE
WYSIWYG: enterMode does not work correctly

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#981]
### Issue
In my code I want to use a WYSIWYG editor enclosed in a P tag with a custom class of mine.
Just as in your documentation described, I set the WYSIWYG editable to "enterMode" => 2. 
  
### Expected behavior 
I expect the WYSIWYG to not add the P tag in the frontend.
  
### Actual behavior  
The WYSIWYG editable still adds the P tag in the frontend.
  
### Input 
```php
<p class="lead"><?= $this->wysiwyg("text", ["enterMode" => 2]); ?></p>
```

### Output 
```html
<p class="lead"></p>
<p>My text which comes through the WYSIWYG editor...</p>
<p></p>
```

**Comment by brusch** [comment]
You code example works as expected, the output is: 
```html
<p class="lead">This<br />
is<br />
just<br />
a simple<br />
test</p>
``` 

**Please Note**: there is no automatic conversion from `<p>` to `<br>` you have to enter the text in the editable again (that's why it's called `enterMode` ;-)).
