### ISSUE TITLE
[Bug]: Deeplink gets lost after login

### ISSUE THREAD

**Issue by akno77** [pimcore/pimcore#9813]
### Expected behavior

If you get a deeplink and open the URL without beeing logged in in the CMS you get the login page. After you logged in successfully the deeplink is openend in the CMS.

### Actual behavior

After the log in the deeplink is lost and not opened.

### Steps to reproduce

1. Log out from the CMS
2. Open a deeplink like https://demo.pimcore.com/admin/login/deeplink?document_139_page
3. Log in
4. No Deeplink is openend

**Comment by dvesh3** [comment]
Fixed by #9823
