### ISSUE TITLE
[Improvement]: Show only unused Predefined Properties in dropdown

### ISSUE THREAD

**Issue by akno77** [pimcore/pimcore#9817]
### Improvement description

If you have many Predefined Properties it can be very unhandy to see which of the Predefined Properties are unset. Therefor it would be better if the dropdown list filters out all already set predefined properties. This would be a big usability improvement!

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
