### ISSUE TITLE
FieldDefinition in Relation field causes "headers already sent"

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#9818]
### Expected behavior

`pimcore.ERROR: RuntimeException: Failed to start the session because headers have already been sent by ...` error should not occur, thus, not be logged.

### Actual behavior

`pimcore.ERROR: RuntimeException: Failed to start the session because headers have already been sent by ...` is logged in `dev.log`/`prod.log` when saving a `Snippet` (and probably any other element) containing a `Relation`, which references a `FilterDefinition`.

#### Additional Information
The issue occurs while writing to the cache (in `Pimcore::shutdown()`). The `CoreHandler` will call `writeSaveQueue`, which in turn will call `prepareCacheTags` at some point. To prepare the cache tags, you'll have to `getElements`, which are then initialized (i.e., `setDataFromResource`).

However, for a `Relation` the `$this->setElement()` method is called, which will load the element via `DataObject::getById($id, $force)` - thus, calling `$object = Cache::load($cacheKey)`.

As the `FilterDefinition` uses `IndexFieldSelectionCombo`, which is [initialized in the `__construct`](https://github.com/pimcore/pimcore/blob/eed98a084d6e8852788cbbcaf8f2b67fe60a1ba6/bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelectionCombo.php#L42), the EcommerceFramework will try to access the `SessionBag` to load the current assortment tenant. By doing so, the error is triggered, as the headers were already sent. [The exception is caught and, in its stead, a log is created](https://github.com/pimcore/pimcore/blob/eed98a084d6e8852788cbbcaf8f2b67fe60a1ba6/bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelectionCombo.php#L68).

### Steps to reproduce

1. Add a `Relation` to a `Snippet`
2. Drag & Drop a `FilterDefinition` into it
3. Save the `Snippet`
4. Check your logs

**Comment by dvesh3** [comment]
@passioneight Sorry, not able to reproduce with mentioned steps. Can you provide more details?

**Comment by passioneight** [comment]
@dvesh3  not sure which information you need - I'll try:

1. [Set a break point here](https://github.com/pimcore/pimcore/blob/eed98a084d6e8852788cbbcaf8f2b67fe60a1ba6/bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelectionCombo.php#L52)
2. Create a `Snippet` with a `Relation` field and fill it with a `FilterDefinition`.
3. `ssh` to your server and use `tail - f ~/www/var/logs/dev.log | grep "headers have already"` (adjust the path as needed).
4. Save the `Snippet`
   - The debugger will now stop at the line mentioned in 1
   - Try jumping to the next line, an error will be thrown and logged

If you jump into the function called in step 1, you'll find the behaviour described in the "Additional Information" section of the issue's description description.

**Comment by mattamon** [comment]
@passioneight we tried it again and it is still not reproducible anymore. I will close the ticket. If the problem still persists feel free to contact me or reopen another issue.
