### ISSUE TITLE
[Bug]: Log file not created

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#9820]
[UPDATED 2021/07/21]
### Expected behavior

The log file is consistently created even if deleted, moved, or renamed during script execution.

### Actual behavior

The log file may not be created after the first call due to PHP caching file system data.

### Steps to reproduce

Make a simple script that write something in a log file, make the script sleep, then write something again in the same log file. During the sleep, delete/move/rename the log file.

It can be fixed easily by adding `clearstatcache(true, $log);` just after 
https://github.com/pimcore/pimcore/blob/6.9/lib/Log/Simple.php#L28
https://github.com/pimcore/pimcore/blob/10.x/lib/Log/Simple.php#L31

**Comment by brusch** [comment]
Fixed by #9920

**Comment by Yivan** [comment]
Thanks ! : )
