### ISSUE TITLE
[Bug]: Enterprise Extension: CI-Hub //

### ISSUE THREAD

**Issue by christophluehr** [pimcore/pimcore#9826]
### Expected behavior

Assets from Pimcore should be visible within Word in the CI-Hub Plugin. Assets should be downloadable.

### Actual behavior

CI-Hub Plugin behavior in MS Word, image are show as placeholders - not the actual images:

![Screenshot 2021-07-21 at 11 29 33](https://user-images.githubusercontent.com/1352356/126466372-51ab8642-3805-4861-a96b-2c0ec10f36e1.png)

Using the CI-Hub function "Save local" on an Image results in the following error message, too:

![Screenshot 2021-07-21 at 11 34 00](https://user-images.githubusercontent.com/1352356/126467396-e3209eab-f16f-489a-8a2a-c94342a70b80.png)

Configuration in Pimcore X / DataHub (Demo Setup):

![Screenshot 2021-07-21 at 11 31 07](https://user-images.githubusercontent.com/1352356/126466677-f6617d2c-47d1-4491-86a4-59bfe02047a2.png)

### Steps to reproduce

Install Pimcore 10.0.7, set up DataHub, set up CI-Hub, add to MS Word,
browse to an asset folder.

**Comment by fashxp** [comment]
hi, this is not the right place for issues for the enterprise bundles.
please contact your sales contact person at Pimcore to get access to the corresponding github repositories.
there we are happy to help you. thanks.

**Comment by fashxp** [comment]
besides that: for me it works just fine.
