### ISSUE TITLE
Provision of a detailed installation guide for Pimcore X

### ISSUE THREAD

**Issue by HeicoSindel** [pimcore/pimcore#9833]
### Improvement description

The official instructions for installing version 10.0 do not behave as usual from V 6.9. There are obviously many changes - in Pimcore as well as in Symfony - which mostly lead to problems caused by missing or wrong permissions. 
It would therefore be helpful to develop a detailed installation manual - preferably based on Linux. 
The basic installation can then be based on the official description and should be expanded to include the critical elements. Specifics in the permissions, in the configuration on Apache or Nginx. Possibly a blueprint for the cluster setup.

**Comment by brusch** [comment]
@HeicoSindel Thanks for sharing your ideas! 
We're always happy to work together with our community to improve our software and docs. Contributing to the Pimcore documentation is quite easy, either use the  "Edit on GitHub" link right on the doc pages: 

![image](https://user-images.githubusercontent.com/142037/126602388-9082ef76-1fb9-4050-a4c9-00304dc335c8.png)

Or just clone our repo for bigger changes. 

Looking forward to your PRs 😊
