### ISSUE TITLE
[Bug]: Translations XLIFF Import escapes HTML of WYSIWYG editables

### ISSUE THREAD

**Issue by shaselboeck** [pimcore/pimcore#9850]
### Expected behavior

Export a document (containing WYSIWY editable) via XLIFF, translate HTML in XLIFF, import translated XLIFF and see translation with correct HTML.

### Actual behavior

Export a document (containing WYSIWY editable) via XLIFF, translate HTML in XLIFF, import translated XLIFF and see translation with HTML as text.

### Steps to reproduce

1. Visit https://demo.pimcore.com/admin/?perspective=CMS
2. Copy document tree "en"
3. Right click on "Home" and click Paste (inheritance) -> Paste as new language variant (recursive)
4. Select language for New Document French (fr)
5. Rename document tree "en_copy" to "fr"
6. Navigate to Tools -> Translations -> XLIFF Export/Import
7. Drag and drop document "/fr/magazine" to "Elemtns to Export" and deselect option "Children".
8. Select under option "Language" for "Source" = "en" and for "Target" = "fr" and click button "Export"
9. Translate in exported file a WYSIWYG editable with paragraphs, for example replace string "Bavaria ipsum dolor" with "FR new Bavaria ipsum dolor" and save it
10. Import the modified/translated XLIFF file via Tools -> Translations -> XLIFF Export/Import
11. Open document "/fr/magazine" and see the HTML as text in WYSIWYG editable

![01](https://user-images.githubusercontent.com/1867700/126787877-84dbbc19-6e7b-4238-bbee-06c318b4c2a6.jpg)
![02](https://user-images.githubusercontent.com/1867700/126787883-334449c7-bd61-4277-99fa-7ee049c8fa6f.jpg)

**Comment by dvesh3** [comment]
Fixed by #9901
