### ISSUE TITLE
[Bug]: Search and replace assignments do not work

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#9855]
### Expected behavior

It should replace without errors

### Actual behavior

An error is displayed

### Steps to reproduce

On the online demo, set the following settings please : 

![image](https://user-images.githubusercontent.com/9025839/126811946-420af912-6c90-481a-b5b9-80bf02d704c9.png)

Running "Replace assigments for selected items" return:

![image](https://user-images.githubusercontent.com/9025839/126812044-61bbdec1-a5ad-4b42-adaa-471dcbf175f9.png)

Same error if replace all is selected (error is triggered at the end of the process, no replace seems to have been done)

Thanks.

**Comment by dvesh3** [comment]
Fixed by #9880

**Comment by Yivan** [comment]
Great thanks for this fix!
