### ISSUE TITLE
[Improvement]: Filters for SEO Document Editor

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#9856]
### Improvement description

Hello,

There was a time when the SEO Document Editor in Pimcore BO had coloured line if description was missing for instance )
Is there any reason coloration has been removed ?

Purpose of this issue is to make it easy to see cms pages having description not filled or too short, etc.
The easier approach would be to be able to filter the length column by integer (from ... to ..., or less than...).
It would help better than the previous colour system which was existing in old Pimcore.

![image](https://user-images.githubusercontent.com/9025839/126814262-977fbe16-50c5-4084-aaaf-b77342471d18.png)

This way if we can set both length filter (for title and description) we can easily display only short or empty one. It can greatly help for big CMS sites having a lot of pages. This small improvement can really help SEO editors I think.

Thanks.

**Comment by fashxp** [comment]
Sounds reasonable. Anyone in for a PR?

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
