### ISSUE TITLE
[Improvement]: Sort quantity value in config field of classe by base unit

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#9857]
### Improvement description

Hello,

Actually, in the configuration of a Quantity value field, units are ordered alphabetically by abbreviation.

![image](https://user-images.githubusercontent.com/9025839/126815126-bb7b6f72-074a-4812-8711-15af0a4e7d37.png)

Purpose of this improvement is to suggest ordering it first by base unit and second alphabetically abbreviation.

So for instance, "cm, dB, EUR, g, kg, L, m, mm, USD, °C" will give "cm, m, mm, dB, g, kg, L, EUR, USD, °C".
This will be more user-friendly. Especially for selecting several units for the same base. The unit will be near each other instead having to check through all the units.

Thanks for reading this suggestion.

**Comment by fashxp** [comment]
makes sense to me. could you provide a PR for that?

**Comment by NiklasBr** [comment]
I thought I added [support for that](https://github.com/pimcore/pimcore/pull/8780/files#diff-8e50a667ba438bf73ebb65c66455e6013582eafe30da5247a9669fa97e672238R175-R176) in #8780 :)

**Comment by Yivan** [comment]
@NiklasBr  I you are totally right! I didn't saw it. Thanks for this PR.
I will close this issue so.
(I will open another issue on quantity value because i found a bug when trying to set to "(empty)" the base unit)

**Comment by NiklasBr** [comment]
It's not visible in the Demo instance because most values are missing both *Base unit* and *Conversion factor*

**Comment by Yivan** [comment]
@NiklasBr Yes I tried it by settings some base units and works fine ! : )) Thanks!
