### ISSUE TITLE
Consistent Password Policy

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#986]
User password can be changed in 2 places:
- the user management panel
- the profile user edition

Both places doesn't have the same pasword strategy, as seeing the regex:

For user management panel:
https://github.com/pimcore/pimcore/blob/master/pimcore/static6/js/pimcore/settings/user/user/settings.js#L408
`/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^a-zA-Z0-9])(?!.*\s).{10,}$/`

For profile user edition:
https://github.com/pimcore/pimcore/blob/master/pimcore/static6/js/pimcore/settings/profile/panel.js#L216
`/^(?=.*\d)(?=.*[a-zA-Z]).{6,100}$/`

Check should be same (maybe make a global isValidPassword function so checking is handled in just one place).

As improvement, it could be added in system configuration the possibility to configure our own regex for password strategy. Actually it cannot be changed (and i don't see a way to change it even with plugin has checking regex is hardcoded in js files).
(actually we need to hack core files because some project need a more or less password protected scheme and )

(for security reason maybe, the checkin should be done server side too to follow good practice on such a sensible field ? But would prevent to store whatever password using API wich is nice for importing existing account in a migration proccess... So i don't know...)

Thanks!

**Comment by brusch** [comment]
Password policy is now consistent. 
This functionality can only be used by trusted backend users, so I don't think a server-side check is necessary.

**Comment by Yivan** [comment]
Wouh! So fast! Thanks a lot Brusch.

Yes for server side i was thinking same than you.

For the policy configuration (for instance a field in general system configuration where we can fill a regex and it is used if filled, empty by default) do you think i open an improvement for this or not ?

**Comment by brusch** [comment]
For now I'd stick with the given policy, you know I'm not an advocate of too many configurations ;-)
