### ISSUE TITLE
[Feature]: Add config value whether to use imagick if available

### ISSUE THREAD

**Issue by manud99** [pimcore/pimcore#9860]
### Feature description

I currently run a Pimcore application on a server, where the imagick PHP extension doesn't work for PHP 8.0. Therefore I'm looking for an option to disable the imagick extension. Unfortunately it isn't possible to disable a PHP extension on this server. That's why I'm searching a solution in the code.

I suggest to add a config value which defines, whether to use the imagick extension if available, which defaults to `true`. This way users are able to disable imagick because of personal preference or on account of a server error like in my case.

Would you like me to work on a PR for this? Otherwise I'll just create a patch for myself, where I comment out the corresponding sections.

**Comment by brusch** [comment]
Duplicates #2914 ( a bit more generic approach that would solve your case as well). 
A PR fixing #2914 would be welcome 😊
