### ISSUE TITLE
[Task]: Check if workflow model is still needed

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#9863]
### Improvement description

check if [workflow model](https://github.com/pimcore/pimcore/blob/2f18a0f26380c56b609d937b40d2050c8d1a3e1a/models/Workflow.php#L22) is still needed, deprecate/remove it otherwise.

**Comment by pimcore-galilee** [comment]
Dear fashxp.
I just read this comment and I am a little bit affraid about workflows in general in the pimcore core.
Do you intend to remove workflows in Pimcore or do you intend to provide other functionnalities, new librairies, new way of hanndling worflows?
Arnaud.

**Comment by fashxp** [comment]
no, there is no plan to remove workflows at all ... I just supect, that this model is a leftover of times before workflows were migrated to symfony workflows.

**Comment by pimcore-galilee** [comment]
Ouf, glad to hear this. Which actually makes  sens :o)))
However, we still have this issue which is still not fixed : Workflow marking_store arguments are not compatible with Symfony 5.x anymore #9525.
Do you have any release date for the fix?

**Comment by fashxp** [comment]
no .. as noted in the issue, a PR would speed things up.

**Comment by mcop1** [comment]
Already removed in Pimcore 11.x
