### ISSUE TITLE
Quantity value - Set base unit to "empty" value fall in error

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#9865]
### Expected behavior

Base unit could be set to "(empty")

### Actual behavior

If "(empty" is choosen an error is triggered and base unit stay the old value. So it is impossible to set it back to empty.

### Steps to reproduce

On the online demo, change a base unit of one unit to any non empty value.

![image](https://user-images.githubusercontent.com/9025839/126992813-7653bf8b-177c-47e6-99d9-5ac87c3caf89.png)

Set it back to empty and an error will be trigerred. Refresh the list of quantity values : the old value is keeped.

![image](https://user-images.githubusercontent.com/9025839/126992765-088d07c9-c8e5-407b-9dae-48aa8f40b3fc.png)

Thanks!

**Comment by dvesh3** [comment]
Regression of https://github.com/pimcore/pimcore/pull/6965/files#diff-c624477d3d2ae554e390ee2b45c5f4c48c160471609aee1e4df2478ab395c4a8R865

**Comment by dvesh3** [comment]
Fixed by #9929

**Comment by Yivan** [comment]
Great thank you for this fix!
