### ISSUE TITLE
[Bug]: In Pimcore Version 6.8.12  setActiveGroup is not working

### ISSUE THREAD

**Issue by kumar2112** [pimcore/pimcore#9867]
### Expected behavior

`public function updateclassificationstoreAction(Request $request)
    {
        $class = $request->get('class');
        $productId = $request->get('productId');
        $categoryId = $request->get('categoryId');

        if($class == 'Product' || $class == 'Parts'){
            if($class =='Product'){
                $productData = Product::getById($productId);
            }else{
                $productData = Parts::getById($productId);
            }
            
            $categoryData = Category::getById($categoryId);
            //$categoryData = Category::getByPath($categoryId);
            $cattegoryName = $categoryData->getCategoryName();
            $cattegoryName=trim($cattegoryName,'');
            $attributes = $productData->getTechnicalSpecification();
            //$activeGroups = $attributes->getActiveGroups();
            $productData->getTechnicalSpecification()->setActiveGroups([]);
            $collectionMapping = $attributes->getGroupCollectionMappings();
            $db = Db::get();
            $sqlQuery = "SELECT groupId FROM classificationstore_collectionrelations WHERE colId = (SELECT id FROM classificationstore_collections WHERE NAME = '".$cattegoryName."' AND storeId  = (SELECT id FROM classificationstore_stores WHERE NAME = 'Attributes'))";
            $groupList = $db->fetchAll($sqlQuery);
            if(count($groupList) > 0){
                foreach($groupList as $group){
                    $activeGroups[$group['groupId']] = true;
                }
                $productData->getTechnicalSpecification()->setActiveGroups($activeGroups);
            }

            $productData->setCategory($categoryData->getId());
            $productData->setOmitMandatoryCheck(true);
            $productData->save();
            //$activeGroups = $productData->getAttributes()->getActiveGroups();

            echo json_encode(array('errors' => [], 'success' => true));
            exit;
        }
        exit;
    }`

Above code should add a active group and activate in  classification store

### Actual behavior

![image](https://user-images.githubusercontent.com/12470739/127111467-9e2f3535-d2b8-4c7a-8b04-e821f330e4f8.png)
Above code is not activating the classification store .its working fine in 6..8.6.
But in 6.8.12 . its not working

### Steps to reproduce

Steps . 
1 Select the category.
2. on the bases of that category name execute the below query
`SELECT groupId FROM classificationstore_collectionrelations WHERE colId = (SELECT id FROM classificationstore_collections WHERE NAME = '".$cattegoryName."' AND storeId  = (SELECT id FROM classificationstore_stores WHERE NAME = 'Attributes'))`
3. Other Details are mentioned in above code

**Comment by brusch** [comment]
@kumar2112 can you confirm that this bug still exists in latest version of Pimcore 10? 
Pimcore 6 is end-of-life and doesn't get any further fixes.

**Comment by NiklasBr** [comment]
@kumar2112 I believe this was fixed in [6.9.3](https://github.com/pimcore/pimcore/milestone/125?closed=1)

**Comment by kumar2112** [comment]
> @kumar2112 can you confirm that this bug still exists in latest version of Pimcore 10?
> Pimcore 6 is end-of-life and doesn't get any further fixes.

In 6.8.6 its working fine.  i have developed the project in 6.8.6 . but now when i update/intall composer it autometicaly installs the 6.8.12.

**Comment by brusch** [comment]
@NiklasBr thanks for clarifying! 😊

**Comment by kumar2112** [comment]
> @NiklasBr thanks for clarifying! 😊

can you help me how i can fix this . i need only 6.8.6  or should i upgrade it

**Comment by brusch** [comment]
@kumar2112 you can try to get the patch from 6.9.3 and apply it to your installation.

**Comment by kumar2112** [comment]
> @kumar2112 you can try to get the patch from 6.9.3 and apply it to your installation.

can you reffer me commit id or any reffrence of that patch

**Comment by NiklasBr** [comment]
You could use [cweagans/composer-patches](https://github.com/cweagans/composer-patches) and reference https://patch-diff.githubusercontent.com/raw/pimcore/pimcore/pull/8872.patch

**Comment by kumar2112** [comment]
> You could use [cweagans/composer-patches](https://github.com/cweagans/composer-patches) and reference https://patch-diff.githubusercontent.com/raw/pimcore/pimcore/pull/8872.patch

thanx @NiklasBr
