### ISSUE TITLE
[Bug]: Duplicated Pagination in DataObjects

### ISSUE THREAD

**Issue by dpfahlbusch** [pimcore/pimcore#9871]
### Expected behavior

Only one pagination is visible

### Actual behavior

Two paginations are rendered

### Steps to reproduce

1. Go to current demo (demo.pimcore.fun)
2. Open DataObjects
2. Open Product Data / Accessories / lights / head lights
3. Increase size of sidebar
4. Pagination is duplicated

![image](https://user-images.githubusercontent.com/22637136/127147732-b80a6ce9-2b5e-4377-8531-00aa3c42d042.png)

**Comment by dvesh3** [comment]
Fixed by #9883
