### ISSUE TITLE
Search Field in Tag Assignment Tab

### ISSUE THREAD

**Issue by xlttj** [pimcore/pimcore#988]
Currently we have round about 150 tags configured. It's tedious to look for appropriate tags in such a huge tree.

In order to find tags faster, it would be very helpful to have a filter field at the top of the tag trees  in the tag configurator and the objects/assets/documents tag assignment tab.

Entering a string in the filter field should reduce the tag tree to matching elements an their parents.

**Comment by weisswurstkanone** [comment]
Suggestion: see attached video.

[filter.zip](https://github.com/pimcore/pimcore/files/1582862/filter.zip)
