### ISSUE TITLE
[Bug]: Documents, Editables - Block, first add button is not visible anymore

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#9891]
### Expected behavior

To add a block with the plus button.

### Actual behavior

- add block item on first element is not visible

![Bildschirmfoto 2021-07-28 um 15 03 28](https://user-images.githubusercontent.com/56602444/127327485-9fe92ee8-fd0f-4d84-994a-738445cd8b5f.png)

- add block item after adding a new area is not available

![Bildschirmfoto 2021-07-28 um 15 03 41](https://user-images.githubusercontent.com/56602444/127327496-0250c7c3-8be1-46b0-b010-43e9baa42656.png)

### Steps to reproduce

open pimcore demo -> shared -> includes -> footer 

after last update to 10.0.8 the error occured. Maybe it depends on ticket #9776

**Comment by brusch** [comment]
Seems to just affect nested blocks. It's eg fine in the gallery areabrick-

**Comment by brusch** [comment]
Fixed by #9896
