### ISSUE TITLE
Objectbricks ManyToOneRelation throws warning if no relations are present.

### ISSUE THREAD

**Issue by Johnystardust** [pimcore/pimcore#9900]
### Expected behavior

Opening an object in the backend with an object brick that has a many-to-one relation without a relation should open.

### Actual behavior

When the object is opened and there is no relation present, the following error is presented.
`Warning: Undefined array key 0`

Happens cause relations can be empty but is not checked for empty on.
vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Objectbricks.php:251

### Steps to reproduce

Open an object in the backend that has an object brick with a many-to-one relation field that has no value.

**Comment by dvesh3** [comment]
Fixed by #9904
