### ISSUE TITLE
[Bug]: PricingManager shouldn't start session in CLI

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#9905]
### Expected behavior

The `PricingManager` does not start a session in the CLI and any manually set values are not discarded when trying to access them.

### Actual behavior

When rendering documents via CLI, chances are `getOSPriceInfo()` is called, which will eventually trigger this line of code:

https://github.com/pimcore/pimcore/blob/37c8a9bfaa801d18906dab302b8dddc0c827865e/bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php#L232

The call to `$this->session->getBag` will start a session. As the `SessionEnviroment` is the default configuration for the ecommerce framework, calling `getCurrentAssortmentTenant` will call `$this->load()` - which in turn will fetch the current assortment tenant (and any other information for that matter) from the session bag. 

As you can imagine, the session bag is empty, resulting in `null` values. Now, if you happen to set values on the environment yourself, your values will be overridden, resulting in potential errors when trying to call `Helper::setupProductList` later on, as the assortment tenant is `null`, which means there are no `filter_types` available (even though they were registered for all available tenants).

### Steps to reproduce

1. Setup EcommerceFramework (incl. `filter_types`)
2. Create Product
3. Create an `Area` which renders the product's price by calling `$product->getOSPriceInfo()` and also calls `Helper::setupProductList` within the area's action
4. Add the area **twice** (!) as the rendering and thus the call to `getOSPriceInfo` happens after the first call to `Helper::setupProductList`, which will not cause any trouble due to the manual initialization of the environment
5. Create a `Command` to render the document from CLI
6. Manually initialize `SessionEnvironment` (e.g., `Factory::getInstance()->getEnvironment()->setCurrentAssortmentTenant('en')` (before rendering the document)
7. Execute command

**Comment by Butterd** [comment]
I have just recently stumbled upon this issue and went with the following workaround:

- Inject the Symfony\Component\HttpFoundation\Session\SessionInterfaceand the Pimcore\Bundle\EcommerceFrameworkBundle\EventListener\SessionBagListener
- Then call `$this->sessionBagListener->configure(
            $this->session
        );`

Then the error should be gone

**Comment by fashxp** [comment]
will be gone in Pimcore 11 since pricing manager has no session anymore. 
see also https://github.com/pimcore/pimcore/pull/12873
