### ISSUE TITLE
Manage workflow with PHP API

### ISSUE THREAD

**Issue by Mika-59** [pimcore/pimcore#991]
For now, it is impossible to use workflow management though the PHP API.

You can set a new status / state to your object but there is no abilities to programmatically perform configured workflow actions as described in [this post](https://groups.google.com/forum/#!topic/pimcore/kIWeRXy3FO4)

So, this feature will be a great enhancement for workflow management.

Thank you

**Comment by brusch** [comment]
Isn't a new status/state a workflow action? Can you describe your feature request a bit more specific? 
Thanks!

**Comment by fashxp** [comment]
did you already had a look at `Pimcore\WorkflowManagement\Workflow\Manager` 
doesn't this solve you issue?

**Comment by Mika-59** [comment]
The aim is to programmatically perform configured actions when changing status.
Configured actions are centralized in the file website/config/workflowmanagement.php.

If i perform the status change as described in the Google Groups post, i totally override the configuration (events, available states from a specific initial state, access rights, etc) : i can do a setState and setStatus without any controls and without performing any hooked event.

**BUT ! fashxp actually gave me the answer, the performAction() method from Pimcore\WorkflowManagement\Workflow\Manager saves my life. There is no need to improve anything concerning this feature!**

Progammatically dealing with workflows just should be documented

Thank you! :)

**Comment by fashxp** [comment]
we really would appreciate a documentation pull request based on your experiences :-)
