### ISSUE TITLE
Unable to unassign a custom layout from a user

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#992]
When a custom layout has been set for a user in his workspace, it cannot be removed.

How to reproduce:
- Create a user
- Assign custom layout to an object (in the user workspace), for instance /news (in the demo site)
- Login to this user, custom layout is used
- Go back as admin in the user workspace and unselect this custom layout (by CTRL + Click)
- Login to this user again: the custom layout is always used.

I tried by selecting the main layout too, but it don"t work.
![unassign](https://cloud.githubusercontent.com/assets/9025839/19738509/08c483fa-9bb8-11e6-998b-8923bcddba96.png)

So actually it is not possible to unset it (or maybe delete the line save and recreate it will work but it is not friendly ; ) ).
Thanks.

**Comment by Yivan** [comment]
Maybe an improvement can be done on the custom layout selection too (or in the algorythm defining the one to choose when opening an object):

Actually, we cannot set a custom layout on the role level and after adding object to user which will use the role custom layout (as we don't sepecify nothing in the user level).
But it seems by default, it is setted to "no custom layout" and forced (parents custom layout not be checked if setted), so the custom layout definined at the role level is not used.

Maybe by default custom layout shoud be set as "empty", and we opening an object panel, we look for parents to see if one is defined for this class object and use it if found. If nothing is found, we use the classic object layout.

It would make life easier when adding object to user workspace (they don't have to dig in custom layout and/or forget to do it), as the custom layout could be defined at the parent directory on the role level.

I don't know if it is very comprehensive, but i can reexplain if you wish : )

**Comment by weisswurstkanone** [comment]
Unable to reproduce. Ctrl + Click perfectly works fine for me.

**Comment by Yivan** [comment]
Yes, Ctrl + Click visualy unasign it, but if you check by connecting as the user, there is always the custom layout...

I made some screenshot so you are able to recreate it, on the demo website:

1- Create a custom layout for news
![createcustom](https://cloud.githubusercontent.com/assets/9025839/19770966/8e6dcc42-9c61-11e6-868c-615fc93808bf.png)

2- Create a user with /news object workspace and the custom layout:
![user](https://cloud.githubusercontent.com/assets/9025839/19770983/9f1c0c0c-9c61-11e6-9288-466f979e04b6.png)

3- Log as the user in another browser
=> the custom layout is used: ok

4- As admin, unassign the custom layout (using CTRL + Click). Visually this is ok. Make save.
![unassign](https://cloud.githubusercontent.com/assets/9025839/19771020/bf62915c-9c61-11e6-9648-ff35ff57853f.png)

5- Go back to the browser with the user session. Reload the object panel previously open:
=> the custom layout is always used...: not ok

If you need further information don't hesitate to ask.
Thanks.

**Comment by weisswurstkanone** [comment]
Hmm, but that's the intended behavior I guess. If there is no restriction then all custom layouts (including the standard one) are allowed. Also note that a "reload" will always attempt to apply the same layout again whereas close&open will use the standard one (if allowed)

**Comment by Yivan** [comment]
Ok understanded. I forgot about the possibility to choose the custom layout from the refresh button.
So I confirm all work as espected.
Thanks.
