### ISSUE TITLE
Using user workspace, object in grid listing and tree seems to work as "beginning with"

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#993]
Actually on the demo instance, the bug is reproductible.
I made the test on object, but maybe sme problem on document/asset too.

---

**Grid listing**

Set a user workspace like this:
![workspace](https://cloud.githubusercontent.com/assets/9025839/19739726/685ee252-9bbc-11e6-9c93-3a64326a8f86.png)
Purpose is to list only one object (or some other if added to the workspace) and having access to the grid filtering (using /container-news).

Login to this user, he can view in the grid all the object beginning with the same name:
![grid](https://cloud.githubusercontent.com/assets/9025839/19739756/81737ea6-9bbc-11e6-8fbb-52113f6263a0.png)

The object news "lorem-ipsum" and "nam-eget-dui" are not listed in the grid so it is ok, but all "in-enim-justo-x" are listed and should not.

---

**Object tree**

This problem seems to affect the object tree too.
If we set this workspace:
![workspace2](https://cloud.githubusercontent.com/assets/9025839/19740104/c30e9f5c-9bbd-11e6-90dc-506c9bfb6b0f.png)

We got this on the user side:
![tree](https://cloud.githubusercontent.com/assets/9025839/19740109/ce6e4032-9bbd-11e6-87d3-2df3eb26dd45.png)

Just "in-enim-justo" should not be in the tree (as it has not the "list" access), but in the screenshot you can see that all object beginning with "in-enim-justo" are not in the tree.

---

**Object panel**

I didn't manage to reproduce it on the demo, but when we where checking this (on a project which involves some user workspace), we managed to access to some object, always based on the "beginning with" problem. Object was not listed (so ok), but by using "open by id" from the toolbar menu, we managed to open object beginning with the same name.
Maybe we made wrong our test as i cannot reproduce it on the demo, but you should check for the "view" setting (so opening an object) has not this problem, because it can lead to user to access object they are not intended too.

**Comment by Yivan** [comment]
I noticed another small bug making those tests, the "copy" action is available and should not (as their is not paste action...). It make strange for the user.

Actually we could hide this action with the nice perspective feature : ) but maybe this small problem could be corrected.

Here is a screenshot:
![copyleft](https://cloud.githubusercontent.com/assets/9025839/19740540/4f376e0e-9bbf-11e6-8e74-6108d2f00dfe.png)

Thanks.

**Comment by weisswurstkanone** [comment]
I guess the problem is that at this point of time you probably can't guess where you want to drop it. You obviously don't have the permission to drop it at the same place but the destination folder (with sufficient permissions) could be a completely different one.

**Comment by Yivan** [comment]
Concerning the "copy" action, yes you are right, it depends use case. So we can leave as it is, and using perspective we can already hide it.
(i updated my previous message so this point is ok)
