### ISSUE TITLE
Cannot save object drafts 

### ISSUE THREAD

**Issue by manea-eugen** [pimcore/pimcore#994]
I updated pimcore recently 19/10/2016 to build 3994 and i noticed that save without validation is broken :(

How to reproduce:
1. Visit https://demo.pimcore.org/admin/login/deeplink?object_29_object
2. Clear the person field 
3. Click unpublish 
4. Click Save (not Save and publish)
5. Pimcore shows an exception to fill in mandatory field
![screenshot from 2016-10-27 07-36-19](https://cloud.githubusercontent.com/assets/8200242/19755759/30beeaa2-9c18-11e6-9343-d07bc984df5f.png)

Technical explanation:
In latest build Save button is binded directly to save method in [object.js](https://github.com/pimcore/pimcore/blob/master/pimcore/static6/js/pimcore/object/object.js)
``` 
this.toolbarButtons.save = new Ext.SplitButton({
                text: t('save'),
                iconCls: "pimcore_icon_save",
                scale: "medium",
                handler: this.save.bind(this),
                menu:[{
                    text: t('save_close'),
                    iconCls: "pimcore_icon_save",
                    handler: this.unpublishClose.bind(this)
                }]
            });
```
I think that this is not desirable behavior and it should change back to unpublish action or create a new saveUnpublish method  which passes the task as a string because currently in task is the button itself instead of task as string
```
 save : function (task, only, callback, successCallback) {
```

I opened a pr with what i think is the fix

**Comment by brusch** [comment]
see #996
