### ISSUE TITLE
Data loss for localized fields in field collection

### ISSUE THREAD

**Issue by podarcis** [pimcore/pimcore#9941]
### Expected behavior

Entered data for all languages in localized fields within field collection remain intact.

### Actual behavior

Data loss for all languages but the first visible language (first tab) on save when field collection is modified/dirty, e.g. new entry, entry deletion or resorting.

**Additional info:**
  * The problem seems to be in the frontend (ExtJs) as inspecting the request (XHR) shows that the other languages all have an empty value.
  * Affected/tested versions are at least: 10.0.7, 10.0.8 and branch 10.x

### Steps to reproduce

1. Configure multiple languages in the system, e.g. `en` and `de`
2. Create a field collection TestCollection
    - Add a localized field
    - Add an input field to the localized field
3. Create a data object class
    - Add a field collection field and allow previous created field collection. Use defaults for settings.
4. Create a data object of this class
    - Add items to the field collection and fill in all languages into the localized input
    - Save the data object
5. Refresh or re-open the data object **without touching the localized fields tabs**
    - Add a new item or delete an item or reorder items
    - Save the data object again
6. Refresh or re-open the data object again and verify that for each field collection item the languages, that weren't visible in the first language tab, are gone.

**Comment by dvesh3** [comment]
Fixed by #9946
