### ISSUE TITLE
[Bug]: EditableDialogBox Button not rendered

### ISSUE THREAD

**Issue by Brainshaker95** [pimcore/pimcore#9944]
### Expected behavior

The Editable Dialog Box Button is rendered

### Actual behavior

The Editable Dialog Box Button is not rendered

### Steps to reproduce

https://github.com/pimcore/pimcore/blob/v10.1.0/bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js#L308

This feature was broken with this PR: https://github.com/pimcore/pimcore/pull/9785

It seems like that this if here can never be true. 

I think simple moving this line `dialogBoxDiv = Ext.get(this.elements[i]).query('.pimcore_block_dialog[data-name="' + this.name + '"]')[0];` above the if will fix this.

**Comment by brusch** [comment]
Fixed by #9948
