### ISSUE TITLE
[Bug]: older Versions unusable

### ISSUE THREAD

**Issue by roland4432** [pimcore/pimcore#9949]
### Expected behavior

Even older versions that have been zipped by e.g. the maintenance script should still be accesible.

### Actual behavior

When you have versions that got zipped, those versions are still listed in the version tab of e.g. an object. If you either click on them or try to compare them to a newer version you end up with an error 500.

So either don't list them in the versions tab, or alter the accessor for older versions to be able to unzip stuff on the fly to make use of the older versions.

### Steps to reproduce

* Create an object
* Set the maximum versions to keep to 1 in the system settings
* Save two versions
* Run the maintenance scripts
* Check if the older version got zipped (resulting in a file like: /var/versions/objects/g0/<object-id>/<version-id>.gz
* Open the object, navigate to the versions tab
* Click on the older version

**Comment by brusch** [comment]
That's probably something that needs to be documented or integrated into the upgrade guide.
But we can't re-add the support for zipped version files.

**Comment by roland4432** [comment]
Do you think zipping older versions is really necessary? Disk space is cheap and I think you don't save that much of space?

WDYT?

Zipped versions are obsolete then anyways.. you cannot use them as a fallback version, nor compare to.

**Comment by brusch** [comment]
No, it's not necessary that's why we removed zipping in Pimcore X 😉

**Comment by brusch** [comment]
But you can unzip them before X migration, then you should be still fine.

**Comment by roland4432** [comment]
So they don't get zipped anymore?

Fine with me :)

**Comment by brusch** [comment]
Nope, no more zipping 😉 Was removed by #8562

**Comment by roland4432** [comment]
Should I leave this issue open until the update guide is updated or did you delegate this to anyone yet?

**Comment by brusch** [comment]
I'd keep it open until the docs are updated.

**Comment by Fahl-Design** [comment]
@brusch Hi, a better solution is to add some version events in "loadData" method.
Deleting versions that were still valid 1 day before is kind of crazy if you are using versions in production

Some suggestions: 

https://github.com/pimcore/pimcore/blob/10.x/models/Version.php#L358
"VersionEvent::PRE_LOAD_DATA" can be used to unpack .gz files if needed (as fallback)

https://github.com/pimcore/pimcore/blob/10.x/models/Version.php#L369 
```php
\Pimcore::getEventDispatcher()->dispatch($event, \XXXXX\Event\VersionEvent::PRE_DESERIALIZE_DATA);
if ($event->hasArgument("result")) {
 $data = $event->getArgument("result");
}
$data = Serialize::unserialize($data);
 ```
can be used to fix unknown classnames on the fly (move from AppBundle to App) (@roland4432 )
the data inside the versions is still ok

https://github.com/pimcore/pimcore/blob/10.x/models/Version.php#L393
```php
$event = new \Symfony\Component\EventDispatcher\GenericEvent($data);
\Pimcore::getEventDispatcher()->dispatch($event, \XXXX\Event\VersionEvent::POST_LOAD_DATA);
$data = $event->getSubject();
$this->setData($data); 
```
can be used to fix version data on the fly

**Comment by brusch** [comment]
@Fahl-Design Thanks for sharing your ideas, however I'd rather prefer decompressing all versions in preparation of the upgrade.

**Comment by brusch** [comment]
Documented by #10149
