### ISSUE TITLE
Dependency not recognized when using Multihref with Metadata

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#995]
### Expected behavior

When using a class with a Multihref with Metadata field and assigning an asset to it the object should appear on the dependencies tab of the asset ("required by").
### Actual behavior

No dependency displayed  
### Steps to reproduce
- Create a class with a Multihref with Metadata field. Allow assets for this field.
- Upload an asset.
- Create an object of this class and assign the asset
- Look at the dependencies tab of the asset

**Comment by weisswurstkanone** [comment]
build 3999
