### ISSUE TITLE
[Bug]: Uncaught Error: ErrorException::__construct(): Argument #3 ($severity) must be of type int

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#9951]
### Facing issue in PimcoreX 

"pimcore/pimcore": "^10.0"

[2021-08-05T12:38:18.032130+00:00] php.CRITICAL: Uncaught Error: ErrorException::__construct(): Argument #3 ($severity) must be of type int, ErrorException given {"exception":"[object] (TypeError(code: 0): ErrorException::__construct(): Argument #3 ($severity) must be of type int, ErrorException given at /var/www/html/vendor/pimcore/pimcore/models/DataObject/Concrete.php:168)"} []

[2021-08-05T11:59:53.574999+00:00] php.CRITICAL: 
Uncaught Error: ErrorException::__construct(): Argument #3 ($severity) must be of type int,
 ErrorException given {"exception":"[object] (TypeError(code: 0): 
 ErrorException::__construct(): 
 Argument #3 ($severity) must be of type int, ErrorException given at 
/var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Localizedfields.php:996)"} []

### Actual behavior

It shoould not happen

### Steps to reproduce

- Create project using "pimcore/pimcore": "^10.0"
- Create class using multilingual support
- Make any multi-lingual field mandatory
- Try to save & publish object for the same class
- Look into the log

**Comment by dvesh3** [comment]
@deepakkumarpim sorry, can't reproduce on 10.1. Could you please share complete stack trace? thanks!

**Comment by deepakkumarpim** [comment]
@dvesh3 How you tried to reproduce it?

**Comment by ghost** [comment]
Hi @dvesh3 I updated to 10.1 and still same issue : 
![image](https://user-images.githubusercontent.com/85928572/128391445-20ed3fed-8caa-418a-9831-dca318b1c27f.png)

![image](https://user-images.githubusercontent.com/85928572/128391705-24786c5d-cb76-47ec-942d-eeaab5987a78.png)

**Comment by weisswurstkanone** [comment]
In case of an ErrorException the warning is valid because the $exceptionClass has a different signature. The original exception would be interesting though. Could you share it as well please ?

**Comment by brusch** [comment]
@deepakkumarpim 🏓

**Comment by ghost** [comment]
> In case of an ErrorException the warning is valid because the $exceptionClass has a different signature. The original exception would be interesting though. Could you share it as well please ?

Will debug and share you the original exception, fortunately I just corrected signature and things are working. For now we did hack in pipeline. once I will get time will look into again. Thanks.

**Comment by brusch** [comment]
Closed due to inactivity. Please feel free to continue the discussion or provide the missing information on this issue, we'll then reopen it if necessary. Thanks a lot!
