### ISSUE TITLE
[Bug]: Unable to perform direct edit operation on InDesign files

### ISSUE THREAD

**Issue by PGS-gh** [pimcore/pimcore#9955]
### Expected behavior

If we open the _InDesign_ file with _Direct Edit_, and then after editing and saving changes, it should close the _Adobe InDesign_ and ask to apply changes in Pimcore.

![Adobe Indesign Issue](https://user-images.githubusercontent.com/85244913/128384026-584d91af-37ce-47c5-9eff-7421b1f28c43.png)

### Actual behavior

If we open the _InDesign_ file with _Direct Edit_, and then after editing and saving changes, it opens a pop-up and try saving the updated _InDesign_ file in the local system and not saving in the _Pimcore_.

### Steps to reproduce

1. Open any _InDesign_ file(_indd_ extensions) with Direct Edit plugin. It successfully opens in _Adobe InDesign_.
2. Now, edit and save changes.

**Comment by brusch** [comment]
Thank you very much for your issue. This is not the right place for issues for the enterprise extensions though. 

Please contact your sales contact person at Pimcore for how to get support for enterprise extensions and access to the corresponding repositories.

There we are happy to help you. Thanks for your understanding.
