### ISSUE TITLE
Object of a class with Multilingual fields not getting published in PimcoreX 

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#9956]
### Expected behavior

It should Published.

### Actual behavior

It is not Publishing and printing exception. 

### Steps to reproduce

Add multilingual fields and try to save & publish. It will print error in popup.

**Comment by podarcis** [comment]
@deepakkumarpim You may want to provide
  * your exact Pimcore Version,
  * the exception message shown (maybe even a stack trace)
  * and the information, what type of fields you were using in the localized fields

**Comment by brusch** [comment]
@deepakkumarpim 🏓

**Comment by brusch** [comment]
Closed due to inactivity. Please feel free to continue the discussion or provide the missing information on this issue, we'll then reopen it if necessary. Thanks a lot!
