### ISSUE TITLE
Drag and Drop sorting in e.g. "many to many relations" not working since Pimcore 10.0

### ISSUE THREAD

**Issue by tecbird** [pimcore/pimcore#9965]
### Expected behavior

- Sorting items via drap and drop should be work  (in all browsers)
- After sorting changes were made, this change should be detected as DataObject "change" 

### Actual behavior

1 .Drag and drop in Firefox doesnt work since update to 10.x (10.0 + 10.1)
- In Google Chrome it works better, but test is marked and it doesnt't look good

2. After sorting changes were made the dataobject must be marked as "changed" via "*"

Note: Sorting via arrows (up / down) is working as expected.

Firefox: (red, never works)
![image](https://user-images.githubusercontent.com/16688055/128483957-73042659-6ece-40b0-9bc7-837562f7a62a.png)

Chrome: (green tooltip) 
![image](https://user-images.githubusercontent.com/16688055/128483610-f5ab2e5e-6d88-4a9e-8376-8c88e610fafd.png)

### Steps to reproduce

We update our pimcore instance from 6.9 to 10.0 and 10.1 and we got the described problems.
Open any DataObject which contains a relation and try to sort items via drap and drop.

**Comment by dvesh3** [comment]
ExtJS bug. please see https://fiddle.sencha.com/#view/editor&fiddle/3f1l

**Comment by tecbird** [comment]
Thanks for the fiddle. I looks like a problem with the config "enableTextSelection: true".
If i set it to "false" it is working correct (chrome+firefox). Could you change oder implement a setting to change this to false?
We don't need to select any text in this relations elements.

**Comment by dvesh3** [comment]
@tecbird yes, `enableTextSelection: true` config was added to allow text selection on grids, which causes the problem. I would say that this is a nice improvement as it saves steps to copy path of a relation, so setting it false is not an option 😉

**Comment by tecbird** [comment]
@dvesh3: enableTextSelection is not the only one problem - i set it to false in our instance  (we dont need selection feature).  Any sorting changes via drag + drop are not detected as dataobject change.  So if i change sorting and save object - after reload old sorting is shown...

**Comment by dvesh3** [comment]
Fixed by #10010
