### ISSUE TITLE
[Bug]: pimcore_video() in pimcore_block() not rendered correctly

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#9969]
### Expected behavior

Use pimcore_video() in pimcore_block().

### Actual behavior

Adding new block items renders a broken element.

![image](https://user-images.githubusercontent.com/90033/128489396-959389b4-fdf1-42aa-a8c8-00e29ebc5ac3.png)

Adding one element works fine. Adding the second element throws following error:

![image](https://user-images.githubusercontent.com/90033/128489586-baf7ff9f-fa97-4cbd-84e8-d3dc95ce3ea5.png)

### Steps to reproduce

Create a new areabrick with blocks:

```
{% for i in pimcore_block('items').iterator %}
    {{ pimcore_image('image', {
        thumbnail: 'mediaSlider',
        disableInlineUpload: true,
        hidetext: true,
    }) }}
    {{ pimcore_video('video') }}
    {{ pimcore_input('title') }}
{% endfor %}
```

Add more than one items.
After removing the pimcore_video() editable the block is rendered correctly.

Version: 10.x-dev|2e96f99e65c5d1dbeaba2c933d9b39078657d8f9

**Comment by dvesh3** [comment]
Fixed by #9971
