### ISSUE TITLE
[Bug]: DataObjects: Links in Blocks in Fieldcollections wrong after update to Pimcore X

### ISSUE THREAD

**Issue by melissakittl** [pimcore/pimcore#9973]
### Expected behavior

Links inside blocks in fieldcollections in DataObjects are still present after update to pimcore X.

### Actual behavior

Links inside blocks in fieldcollections in DataObjects are empty after update to pimcore X (and php8)
In database the serialized data is still present. The data was saved with pimcore version < 6.9 (and php7.4)

![image](https://user-images.githubusercontent.com/23357021/128523074-374b6c37-6fd3-4dea-9e59-45b1ea4056eb.png)

When creating a new object and saving a link inside the block, it works fine.

Old serialized data:
`a:2:{i:0;a:1:{s:4:"link";a:3:{s:4:"name";s:4:"link";s:4:"type";s:4:"link";s:4:"data";O:34:"Pimcore\Model\DataObject\Data\Link":17:{s:7:" * text";s:19:"System Requirements";s:15:" * internalType";N;s:11:" * internal";i:0;s:9:" * direct";s:116:"https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/System_Requirements.html";s:11:" * linktype";s:6:"direct";s:9:" * target";s:6:"_blank";s:13:" * parameters";s:0:"";s:9:" * anchor";s:0:"";s:8:" * title";s:0:"";s:12:" * accesskey";s:0:"";s:6:" * rel";s:0:"";s:11:" * tabindex";s:0:"";s:8:" * class";s:0:"";s:13:" * attributes";s:0:"";s:9:" * _owner";N;s:13:" * _fieldname";N;s:12:" * _language";N;}}}i:1;a:1:{s:4:"link";a:3:{s:4:"name";s:4:"link";s:4:"type";s:4:"link";s:4:"data";O:34:"Pimcore\Model\DataObject\Data\Link":17:{s:7:" * text";s:22:"System Setup & Hosting";s:15:" * internalType";N;s:11:" * internal";i:0;s:9:" * direct";s:127:"https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/index.html";s:11:" * linktype";s:6:"direct";s:9:" * target";s:6:"_blank";s:13:" * parameters";s:0:"";s:9:" * anchor";s:0:"";s:8:" * title";s:0:"";s:12:" * accesskey";s:0:"";s:6:" * rel";s:0:"";s:11:" * tabindex";s:0:"";s:8:" * class";s:0:"";s:13:" * attributes";s:0:"";s:9:" * _owner";N;s:13:" * _fieldname";N;s:12:" * _language";N;}}}}`

New serialized data:
`a:2:{i:0;a:1:{s:4:"link";a:3:{s:4:"name";s:4:"link";s:4:"type";s:4:"link";s:4:"data";a:17:{s:4:"text";s:19:"System Requirements";s:12:"internalType";N;s:8:"internal";N;s:6:"direct";s:116:"https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/System_Requirements.html";s:8:"linktype";s:6:"direct";s:6:"target";s:0:"";s:10:"parameters";s:0:"";s:6:"anchor";s:0:"";s:5:"title";s:0:"";s:9:"accesskey";s:0:"";s:3:"rel";s:0:"";s:8:"tabindex";s:0:"";s:5:"class";s:0:"";s:10:"attributes";s:0:"";s:6:"_owner";N;s:10:"_fieldname";N;s:9:"_language";N;}}}i:1;a:1:{s:4:"link";a:3:{s:4:"name";s:4:"link";s:4:"type";s:4:"link";s:4:"data";a:17:{s:4:"text";s:22:"System Setup & Hosting";s:12:"internalType";N;s:8:"internal";N;s:6:"direct";s:127:"https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/index.html";s:8:"linktype";s:6:"direct";s:6:"target";s:0:"";s:10:"parameters";s:0:"";s:6:"anchor";s:0:"";s:5:"title";s:0:"";s:9:"accesskey";s:0:"";s:3:"rel";s:0:"";s:8:"tabindex";s:0:"";s:5:"class";s:0:"";s:10:"attributes";s:0:"";s:6:"_owner";N;s:10:"_fieldname";N;s:9:"_language";N;}}}}`

### Steps to reproduce

Create an object and a fieldcollection with a block and inside the block a link.
Maintain some links in the object in pimcore 6.8 and update to pimcore x.

Might be same as https://github.com/pimcore/pimcore/issues/9550

**Comment by brusch** [comment]
Fixed by #10130
