### ISSUE TITLE
[Improvement]: Docker files to install pimcore in my organization

### ISSUE THREAD

**Issue by san4ever** [pimcore/pimcore#9976]
### Improvement description

[Improvement]: Docker files to install pimcore in my organization

**Comment by san4ever** [comment]
@brusch - Hi Im looking for Docker files to install pimcore set up for my organization. not sure why the thread is closed ?

**Comment by brusch** [comment]
... because all the requested information is already there (read the manual!), and this is also not the right place for getting support ...

**Comment by san4ever** [comment]
@brusch - Could you share the manual link  here which describes the installation of pimcore 10.x with nginx. ? i didn't find the documentation related to them

**Comment by nosovk** [comment]
https://github.com/pimcore/skeleton/blob/10.x/docker-compose.yml
but yes, official image depends on apach, not nginx.
