### ISSUE TITLE
[Bug]: Custom View doesn´t show Pagination for more than 30 objects/folders

### ISSUE THREAD

**Issue by ITspirit** [pimcore/pimcore#9984]
### Expected behavior

Custom View should show Pagination

### Actual behavior

In the custom view tree, there are only 30 Folders (some with Object Childs) and no Pagination

### Steps to reproduce

Latest Pimcore Version 10.1

Create Object Custom View, starting point one folder "/testfolder"
Create >30  Folder in the custom view
Maybe with object below the folders, but not neccessary

**Comment by brusch** [comment]
Fixed by #10310
